HIP 1056 Add blockstream domain classes
hashgraph/hedera-mirror-node pull request #10030
Opened 2024-12-31 15:46 UTC by edwin-greene

**Description**:
Adds `BlockItem` and `BlockFile` domain classes and database migration for the new block stream fields.

**Related issue(s)**:

Fixes #9915 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-31 16:36 UTC, xin-hedera requested changes

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/StreamType.java
> +    BLOCK(BlockFile::new, "blockstreams", "block", "", List.of("blk"), Duration.ofSeconds(1L));
block files don't have path or nodePrefix. A 500ms close interval is closer to what's in preview, though by no means it's fixed.

```suggestion
    BLOCK(BlockFile::new, "", "", "", List.of("blk"), Duration. ofMillis(500L));
```

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private String fileHash;
remove it, instead override `getFileHash` to return null, since we don't need block stream file hash

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private Long index;
override `getIndex()` to return `blockHeader.getNumber()`

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private byte[] logsBloom;
Same mechanism as `gasUsed`

```suggestion
```

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private long gasUsed = 0L;
Remove, gasUsed is accumulated when parsing items in `RecordFile` in the parser

```suggestion
```

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private String metadataHash;
Block file doesn't have metadata hash

```suggestion
```

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private int version;
no version defined for block file, perhaps leave it now as an open item.

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private final Version hapiVersion = hapiVersion();
These are not needed, they can be extracted from `blockHeader` when transforming `BlockFile` to `RecordFile`

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    }
if we remove all the hapi*version fields, remove this function too.

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.101.0_add_block_columns.sql
> +alter column if exists running_hash_version drop not null;
```suggestion
  alter column running_hash_version drop not null;
```

and add a new line at the end

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.101.0_add_block_columns.sql
> +alter column if exists running_hash_version drop not null;
Also change the type to `Integer` in domain class `TopicMessage`

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.101.0_add_block_columns.sql
> +alter table if exists record_file
V1.102.0

2024-12-31 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.6.0_add_block_columns.sql
> +alter table if exists record_file
V2.7.0

2024-12-31 16:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.101.0_add_block_columns.sql
> +alter table if exists record_file
And fix the filename to `V1.102.0__add_block_columns.sql`, note the double underscore `__`. Same for V2 migration.

2024-12-31 22:15 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/StreamType.java
> +    BLOCK(BlockFile::new, "blockstreams", "block", "", List.of("blk"), Duration.ofSeconds(1L));
Got it, fixed.

2024-12-31 22:15 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private String fileHash;
Thanks, removed

2024-12-31 22:15 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private Long index;
Thanks, this is now fixed.

2024-12-31 22:15 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private byte[] logsBloom;
Thanks, removed

2024-12-31 22:16 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private long gasUsed = 0L;
Thanks, removed

2024-12-31 22:16 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private String metadataHash;
Thanks, removed

2024-12-31 22:16 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private int version;
Sounds good, I have left it as is. I think the version of the block file was going to be set to 7 for starters.

2024-12-31 22:17 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    private final Version hapiVersion = hapiVersion();
Thanks I have removed them.

2024-12-31 22:17 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    }
Got it, removed.

2024-12-31 22:17 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.101.0_add_block_columns.sql
> +alter column if exists running_hash_version drop not null;
Thanks I've updated it and added tests for nullable runningHashVersion.

2024-12-31 22:17 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.101.0_add_block_columns.sql
> +alter table if exists record_file
Thanks, got it is has been updated.

2024-12-31 22:18 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.6.0_add_block_columns.sql
> +alter table if exists record_file
Thanks I have renamed it.

2025-01-02 14:49 UTC, xin-hedera requested changes

2025-01-02 17:10 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.102.0__add_block_columns.sql
> +  add column if not exists round_end                     bigint       null;
Thanks, these have been added.

2025-01-02 18:17 UTC, steven-sheehy requested changes

2025-01-02 18:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.102.0__add_block_columns.sql
> +  add column if not exists software_version_patch        int          null,
The design states `Add a migration that sets the software_version to the hapi version to populate those fields for previous records. The software_version is always the hapi_version for records prior to the introduction of block streams. Also add software_version to the existing RecordFileReaders at the same time.`

2025-01-03 22:37 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    }
Thanks, removed.

2025-01-03 22:37 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    }
Good catch, removed.

2025-01-03 22:37 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockFile.java
> +    @JsonProperty("prev_hash")
Thanks I have removed them

2025-01-03 22:38 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/BlockItem.java
> +@Builder
Sounds good, added.

2025-01-03 22:38 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordFile.java
> +    @Transient
I've removed the transient, and added updates to the effected migrations.

2025-01-03 22:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.102.0__add_block_columns.sql
> +  add column if not exists software_version_patch        int          null,
Thanks!! I have added that migration and a test for it.

2025-01-03 22:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.7.0__add_block_columns.sql
> +      software_version_patch = hapi_version_patch;
One of the feedback comments was to add an empty line at the end of the migration. This is strange, I see the empty line locally but it doesn't seem to appear here.

2025-01-03 22:47 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddBlockColumnsMigrationTest.java
> +                                .roundStart(null))
Not mentioned in the design, but do we want to add to the migration such that roundStart and roundEnd are set to the index + 1?

2025-01-03 23:31 UTC, steven-sheehy requested changes

2025-01-03 23:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddBlockColumnsMigrationTest.java
> +                                .roundStart(null))
No, we're not tracking rounds until we have block streams so we can't retroactively add it to record stream rows.

2025-01-03 23:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    protected void persistRecordFile(RecordFile recordFile) {
Probably these changes should live in a new `MigrationTest` abstract class.

2025-01-03 23:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    private void perishRecordFile(MigrationRecordFile migrationRecordFile) {
```suggestion
    private void persistRecordFile(MigrationRecordFile migrationRecordFile) {
```

2025-01-03 23:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.102.0__add_block_columns.sql
> +  add column if not exists software_version_patch        int          null,
We'd have to also do the `Also add software_version to the existing RecordFileReaders at the same time` at the same time otherwise we'd have null values after migration for a period.

2025-01-06 21:14 UTC, xin-hedera requested changes

2025-01-06 21:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +            return Optional.of(jdbcTemplate.queryForObject(
`queryForObject` will throw `IncorrectResultSizeDataAccessException ` if no result is found.
we can also simplify the SQL query to just return index so can remove the `map(RecordFile::getIndex)` step in the caller.

2025-01-06 21:14 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddBlockColumnsMigrationTest.java
> +@EnabledIfV2
why is it only for v2? Check `FixAirdropTokenAssociationMigrationTest` about how to have a single db migration test class for a migration script with different versions in v1 and v2.

2025-01-07 16:27 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.102.0__add_block_columns.sql
> +  add column if not exists software_version_patch        int          null,
I've added software version to the record file readers. This is now fixed.

2025-01-07 16:27 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    protected void persistRecordFile(RecordFile recordFile) {
Sounds good I have moved them.

2025-01-07 16:27 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    private void perishRecordFile(MigrationRecordFile migrationRecordFile) {
Thanks, I have fixed the typo.

2025-01-07 16:28 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +            return Optional.of(jdbcTemplate.queryForObject(
Thanks, I have updated the catched exception and simplified the query/logic to just get the index.

2025-01-07 16:28 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddBlockColumnsMigrationTest.java
> +@EnabledIfV2
Awesome thanks, I have updated it to test v1 and v2.

2025-01-07 17:06 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddBlockColumnsMigrationTest.java
> +                version = "2.7.0";
```suggestion
                version = "2.6.0";
```

for v1, version should be `1.101.0`

Because we want to config flyway to run migration to the version right before the migration script we to test.

2025-01-07 17:11 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddBlockColumnsMigrationTest.java
> +                version = "2.7.0";
Makes sense, got it, fixed now.

2025-01-07 17:43 UTC, steven-sheehy approved these changes
LGTM

2025-01-07 18:24 UTC, xin-hedera approved these changes
LGTM

2025-01-07 18:28 UTC, merged