Store verification info in stream file tables
hashgraph/hedera-mirror-node pull request #1009
Opened 2020-09-01 17:11 UTC by xin-hedera

**Detailed description**:
Store the account ID of the node used to download / verify the signature file / stream data file.

- Add node_account_id to record_file table, save the record_file record with corresponding node account ID to db in downloader
- Add account_balance_file table, save the account_balance_file record with corresponding node account ID to db in downloader
- Update parser to update the corresponding stream file record with load stats, consensus timestamp, and etc
 
**Which issue(s) this PR fixes**:
Fixes #919 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-09-02 16:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.29.0__store_verification_node_in_stream_file_tables.sql
> +select updateRecordFileCount();
for dev postgresql db, rows in `record_file` 3,148,259, rows in `transaction` 850,528,026, updateRecordFileCount costs 1885200.557 ms

2020-09-02 23:46 UTC, Nana-EC reviewed
1st look, left some comments

2020-09-02 23:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        DefaultTransactionDefinition def = new DefaultTransactionDefinition();
Here's a suggestion. If we refactored this like the the following would it allow you to use @Transactional and simplify the code instead of having to use the transactionManager directly

`Downloader.java`
```
public Multimap<String, FileStreamSignature> downloadNextBatch() {
     ....(current code minus call to verifySigsAndDownloadDataFiles()) ...

     return sigFilesMap;
}

@Transactional
public void verifyBatch() {
            // Verify signature files and download corresponding files of valid signature files
            verifySigsAndDownloadDataFiles(sigFilesMap);
}
```

`RecordFileDownloader.java`
```
    @Leader
    @Scheduled(fixedRateString = "${hedera.mirror.importer.downloader.record.frequency:500}")
    public void download() {
        downloadNextBatch();
        verifyBatch();
    }
```

This was the download and the verify logic is broken up making it easier to manage and test.

2020-09-02 23:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/event/EventFileDownloader.java
> +            throw new HashMismatchException(fileName, expectedPrevFileHash, eventFile.getPreviousHash());
Should be current hashes not previous
```suggestion
            throw new HashMismatchException(fileName, verifiedHash, eventFile.getFileHash());
```

2020-09-02 23:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +    private static final String UPDATE_ACCOUNT_BALANCE_FILE_STATEMENT = "update account_balance_file " +
q: would it be easier for you to just use repositories at this point? We're trying to move towards that where possible.

Would simplify this class and hopefully shouldn't break too many tests

2020-09-02 23:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordStreamFileListener.java
> +        int count = recordFileRepository.updateLoadStats(recordFile.getName(), recordFile.getLoadStart(), recordFile.getLoadEnd());
Q: Why do we save the recordFile earlier after downloading if we're still passing the object along and eventually hitting the db for its table here as before?

Is there a separation of design we're going for? Just asking in favor of minimizing db calls.

2020-09-03 13:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EventFile.java
> +    private EntityId nodeAccountId;
good catch. the reason there is no converter is EventFile is not an Entity class yet and there is not event_file table. But I agree it's better to add it.

2020-09-03 13:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFile.java
> +    void setNodeAccountId(@NonNull EntityId nodeAccountId);
The three getters/setters in the interface are needed by the abstract base class `Downloader` while getCount is not.

2020-09-03 13:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    log.warn("Failed to verify data file from node {} corresponding to {}. Will retry another node",
I think the log message is appropriate since here it's hash mismatch, not the signature's in the sig files.

2020-09-03 13:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        DefaultTransactionDefinition def = new DefaultTransactionDefinition();
according to spring doc, it won't work because by default `@Transactional` is in `proxy` mode. here even though `verifyBach()` is a `public` method, but calling it inside `download()` is self-invocation, which means the proxy used to add the `Transactional` mechanism is bypassed.

2020-09-03 13:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/event/EventFileDownloader.java
> +            throw new HashMismatchException(fileName, expectedPrevFileHash, eventFile.getPreviousHash());
good catch. will correct it.

2020-09-03 13:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordStreamFileListener.java
> +        int count = recordFileRepository.updateLoadStats(recordFile.getName(), recordFile.getLoadStart(), recordFile.getLoadEnd());
it's the requirement of the ticket and the way we chose to implement the logic.

only in downloader we know the node from which sig file is verified to reach consensus & corresponding data file is downloaded and verified. We need a mechanism to either persist the node info or pass it to parser. We chose to persist the node info of the stream file in downloader thus we have a db record insert in downloader and update (load stats and other info depending on type of file) in parser.

2020-09-03 14:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +    private static final String UPDATE_ACCOUNT_BALANCE_FILE_STATEMENT = "update account_balance_file " +
during the last refactor effort the prepared statement is left as is since I couldn't optimize the repository way to match the original performance. I'd prefer to address the performance in a separate ticket.

2020-09-03 17:08 UTC, steven-sheehy requested changes

2020-09-03 17:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.29.0__store_verification_node_in_stream_file_tables.sql
> +    file_hash           varchar(96),
Should probably be not null

2020-09-03 17:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.29.0__store_verification_node_in_stream_file_tables.sql
> +    name                varchar(250) primary key,
consensus_timestamp should be primary key. Name should probably be unique.

2020-09-03 17:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.29.0__store_verification_node_in_stream_file_tables.sql
> +create table if not exists account_balance_file (
Should we populate past data using account_balance_sets?

2020-09-03 17:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.29.0__store_verification_node_in_stream_file_tables.sql
> +create table if not exists account_balance_file (
yes we could, but we can't get file_hash for the old account balance files.

2020-09-03 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AccountBalanceFile.java
> +
I'm not aware of different versions of account balance file. So I would assume till now, it's all version 1 account balance files.

2020-09-03 17:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        accountBalanceFileRepository.save((AccountBalanceFile)streamFile);
Yeah prefer to wait till we have an `EventFileRepository`.

2020-09-03 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        DefaultTransactionDefinition def = new DefaultTransactionDefinition();
sure. will switch to TransactionTemplate inside `updateApplicationStatus`

2020-09-03 21:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloader.java
> +        RecordFile recordFile = Utility.parseRecordFile(file.getPath(), expectedPrevFileHash,
yes and we can further pull the hash chain and hash verification into the base class.

2020-09-08 18:00 UTC, steven-sheehy requested changes

2020-09-08 18:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> -        return complete;
This looks like a change in behavior. Previously if not complete then it would not move the file and continue to retry it. Now it is skipping it. We should probably throw an exception above, which causes a rollback and will retry the file later.

2020-09-08 18:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +                insertedCount++;
We can probably invert this and just throw an exception if failed instead of using counts to track if failed.

2020-09-08 18:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    StreamFile streamFile = readAndVerifyStreamFile(signedDataFile, signature.getHashAsHex());
It would be cleaner to separate read from verify and to pass the full objects instead of individual fields to verify.
```java
StreamFile streamFile = readStreamFile(signedDataFile);
streamFile.setNodeAccountId(signature.getNodeAccountId());

verify(streamFile, signature);
```

2020-09-08 18:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    moveFile(signedDataFile, destination);
I think `moveFile()` should be within the transaction at the end so if it fails the database updates are rolled back as well.

2020-09-08 18:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                log.error("Roll back the transaction due to error", ex);
This is a change in behavior as it won't try another node now. We shouldn't catch and rollback here manually. Let TransactionTemplate automatically rollback on exception and let the exception bubble up so it can retry the next node.

2020-09-10 17:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                log.error("Roll back the transaction due to error", ex);
The catch and log here is intended to log the original exception so we have the complete stack trace. I'll run it manually to see if it's not needed and the TransactionException thrown by TransactionTemplate has all info.

The logic here does not change the behavior if one node fails we continue with the next in the list because the outer try... with... is inside the for loop.

2020-09-10 21:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/resources/db/scripts/cleanup_V1.28.1.sql
> +TRUNCATE TABLE account_balance_sets RESTART IDENTITY CASCADE;
moved the sql file from main resources to test resources since it's only needed by the java migration test file

2020-09-10 21:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                      PlatformTransactionManager platformTransactionManager, MeterRegistry meterRegistry) {
changed to inject `TransactionTemplate`

2020-09-10 21:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/RecordFileRepository.java
>      List<RecordFile> findByName(String name);
changed to `Optional<RecordFile>`

2020-09-10 21:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileParser.java
> +        } catch (Exception ex) {
my thought is since account balance files are not hash chained so in case of transient database issue, we try the best to process as many files in a batch and pick up what's left in the next scheduled run

2020-09-10 21:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.29.0__store_verification_node_in_stream_file_tables.sql
> +    (consensus_timestamp, count, name, node_account_id)
made the change

2020-09-10 22:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    StreamFile streamFile = readAndVerifyStreamFile(signedDataFile, signature.getHashAsHex());
made the suggested change

2020-09-10 22:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    moveFile(signedDataFile, destination);
moveFile is now called inside transactionTemplate's callback

2020-09-10 22:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                log.error("Roll back the transaction due to error", ex);
removed the catch and log

2020-09-10 22:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +                insertedCount++;
removed unnecessary count, inverted the condition and now it throws ParserSQLException if the underlying db driver will continue execution on failure of a statement

2020-09-10 22:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> -        return complete;
refactored. after changing `tryInsertBatchAccountBalance` to throw under SQL execution failure, the original condition `complete = (insertedCount == validCount)` would always be true so unnecessary

Now in `loadAccountBalances`, any db error would eventually cause `ParserSQLException` so spring will roll back the transaction

2020-09-10 22:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileParser.java
> +        } catch (Exception ex) {
Agreed

2020-09-10 23:19 UTC, steven-sheehy requested changes

2020-09-10 23:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +            updateAccountBalanceSet(updateSetStatement, consensusTimestamp);
Looks like insertAccountBalanceSet is conditional but updateAccountBalanceSet is unconditional. Latter should probably be inside if statement.

2020-09-11 00:54 UTC, steven-sheehy approved these changes

2020-09-11 00:58 UTC, merged