ignore NodeAddress fields not set in protobuf
hashgraph/hedera-mirror-node pull request #1013
Opened 2020-09-02 22:52 UTC by xin-hedera

Signed-off-by: Xin Li <xin.li@swirlds.com>

**Detailed description**:

- Change `port` and `nodeId` in `AddressBookEntry` to boxed types to allow `null` values
- Remove default value of `port`
- Check `NodeAddress` to only set corresponding fields in `AddressBookEntry` when they are set in protobuf

**Which issue(s) this PR fixes**:
Fixes #968 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-09-03 15:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (nodeAddressBook == null) {
Is this a valid scenario? When would we ever pass in a null NodeAddressBook? Should this rather throw?

2020-09-03 16:46 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (nodeAddressBook == null) {
The change here is a refactor of the original negative check `nodeAddressBook != null`.

Indeed the check is redundant since the only place `retrieveNodeAddressesFromAddressBook` is called has already made sure `nodeAddressBook` is not NULL. I'll remove the null check here then.

2020-09-03 17:51 UTC, steven-sheehy requested changes

2020-09-03 17:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    .filter(nodeAddressProto::hasField)
I don't think the implementation of this is correct. It's also unnecessarily complex and uses reflection. Both nodeId and port are primitives, so the `hasField()` implementation returns true if they don't equal the default value (which is zero for both). However, zero is still a valid value for these fields so we still want to set it if it's zero (e.g. testnet's node 0-3).

I think we can revert to previous logic and use some smarter conditional logic to control them being set. For port, I think it's safe to assume that the main nodes aren't going to use port zero so we can just not set it if it's zero. For nodeId, we can first collect all nodeIds into a set and only set nodeId if the size of that set is greater than one.

2020-09-03 17:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void verifyAddressBookWithEmptyAddressBookEntryFields() {
This test and `addressBookWithEmptyAddressBookEntryFields()` are very hard to understand and not maintainable. It'd be much simpler to just `NodeAddressBook.newBuilder().ip()...build()` all fields manually except nodeId and port then assert the current address book has null for those fields.

2020-09-04 14:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    .filter(nodeAddressProto::hasField)
thanks. reverted the changes and implemented the new logic

2020-09-04 14:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void verifyAddressBookWithEmptyAddressBookEntryFields() {
test cases updated

2020-09-04 15:08 UTC, steven-sheehy approved these changes
LGTM

2020-09-04 16:35 UTC, Nana-EC approved these changes

2020-09-04 17:08 UTC, merged