Splitting health check into liveness and readiness checks
hashgraph/hedera-mirror-node pull request #1014
Opened 2020-09-03 01:26 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-09-08 19:45 UTC, steven-sheehy requested changes

2020-09-08 19:45 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +livenessProbe:
The problem here is the probes don't start until Flway migrations complete. So if a migration takes longer than a minute or so the importer will repeatedly crash and never startup. Have to revert this unless you can figure out how to make probes start earlier than Flyway.

2020-09-08 19:45 UTC, steven-sheehy commented on charts/hedera-mirror-grpc/values.yaml
>    initialDelaySeconds: 45
We can probably lower the initialDelaySeconds now that it doesn't have to wait for the db to start. Try starting it locally and seeing how long it takes for that endpoint to return 200.

2020-09-08 19:45 UTC, steven-sheehy commented on charts/hedera-mirror-grpc/values.yaml
>    periodSeconds: 30
We can probably lower the periodSeconds now that we are less likely to crash repeatedly on startup if db is down. Maybe 10s or so

2020-09-08 19:45 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/resources/application.yml
> +    timeout-per-shutdown-phase: 20s
Should probably be a little higher like 30-45s

2020-09-08 19:45 UTC, steven-sheehy commented on hedera-mirror-rest/health.js
> +    setTimeout(resolve, 20000);
This should be configurable

2020-09-08 19:45 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +const getOneTransactionForHealthCheck = function () {
I don't think we need to join from 3 tables for a health check or hit a larger table like transaction. Also, would be better to encapsulate the health check query in health.js. Recommend doing a `select true from t_entity_types limit 1;` inside health.js and verify return value is 1.

2020-09-09 15:56 UTC, ijungmann commented on hedera-mirror-rest/health.js
> +    setTimeout(resolve, 20000);
Fixed to be configurable.

2020-09-09 15:56 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +const getOneTransactionForHealthCheck = function () {
Makes sense, that seemed excessive at the time.  Swapped to your query and stuck it in health.js

2020-09-09 17:15 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
>    initialDelaySeconds: 45
Yeah, seems like it's taking around 10 seconds to get going, I think I'll knock it down to 15 seconds.

2020-09-09 17:42 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
>    initialDelaySeconds: 45
Ran it a few times with different delays, the best I could consistently get is 35 seconds, but still knocked 10 seconds off

2020-09-09 17:43 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
>    periodSeconds: 30
Pulled down to 10s

2020-09-09 17:44 UTC, ijungmann commented on hedera-mirror-grpc/src/main/resources/application.yml
> +    timeout-per-shutdown-phase: 20s
Changed to 40s

2020-09-10 04:17 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +livenessProbe:
The most common suggestion I've seen to get around this is to move the flyway migration into a separate Kubernetes job, though that may cause its own problems.
The other option I'm exploring is try to override the beans in the config, similar to what I've seen [here](https://stackoverflow.com/a/44806540).  It's a little hackey but it may do the trick.  It seems otherwise Spring Boot is pretty insistent on running the flyway migrations right off the bat.

2020-09-10 16:25 UTC, steven-sheehy commented
Please update your description with what was added, removed and changed.

2020-09-10 16:32 UTC, steven-sheehy commented
Can you also bump the versions for hedera-mirror-* charts in `charts/hedera-mirror/requirements.yaml` and run helm dep build? This should fix the helm tests. Helm doesn't seem to like the semver syntax we're using. Recommend changing it from:
`^0.4.0` to `>=0.5.0`.

2020-09-10 16:54 UTC, ijungmann commented on hedera-mirror-rest/config/application.yml
> +        timeout: 20000
Added

2020-09-10 17:33 UTC, ijungmann commented
> Can you also bump the versions for hedera-mirror-* charts in `charts/hedera-mirror/requirements.yaml` and run helm dep build? This should fix the helm tests. Helm doesn't seem to like the semver syntax we're using. Recommend changing it from:
> `^0.4.0` to `>=0.5.0`.

Looks like the issue is actually that it's not picking up the charts that are marked prerelease, in this case 0.5.0-rc1.  Adding -0 to the end in the requirements.yaml does the trick, see [this article](https://github.com/Masterminds/semver#working-with-prerelease-versions) if you want to confirm

2020-09-10 17:35 UTC, steven-sheehy commented
I still want >= as this will just repeat itself when we bump charts to 0.6.0. You can do >=0.4.0

2020-09-10 17:41 UTC, ijungmann commented
> I still want >= as this will just repeat itself when we bump charts to 0.6.0. You can do >=0.4.0

Like this in the requirements.yaml?
`version: >=0.4.0`
I'm getting an error failing to convert the yaml to json when running the dependency update.  I'll keep tinkering with it.

2020-09-10 18:32 UTC, steven-sheehy commented
Looks like below should work:
```diff
-    version: ^0.4.0
+    version: ">=0.5.0-0"
```

2020-09-10 21:26 UTC, ijungmann commented
> Looks like below should work:
> 
> ```diff
> -    version: ^0.4.0
> +    version: ">=0.5.0-0"
> ```

You are correct, that does seem to work.
I tested out a regex to make Maven update the version running the release profile, it seems to work other than it refuses to recognize the version field in the yaml if the caret is present (like ^0.4.0), but for static version numbers it works well.  That being said, it may be overkill now that I see the quotes were all I was missing.

2020-09-10 21:58 UTC, steven-sheehy commented
Why do helm tests still fail?

2020-09-10 22:04 UTC, ijungmann commented
Looks like it's not seeing the liveness check for REST, I was having a similar issue locally with this where it wasn't using the right image, though this may be for a different reason.

2020-09-10 22:51 UTC, steven-sheehy approved these changes

2020-09-11 00:26 UTC, merged