update testnet bucketname and add previewnet
hashgraph/hedera-mirror-node pull request #1015
Opened 2020-09-03 16:26 UTC by xin-hedera

Signed-off-by: Xin Li <xin.li@swirlds.com>

**Detailed description**:

- Update testnet bucket name
- Add previewnet info

**Which issue(s) this PR fixes**:
Fixes #1010 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2020-09-03 17:30 UTC, steven-sheehy requested changes
Need to also:
- Update Marketplace schema.yaml
- Add previewnet address book to classpath
- Update testnet address book in classpath

2020-09-04 19:55 UTC, xin-hedera commented on charts/marketplace/gcp/schema.yaml
> +      - PREVIEWNET
the change triggers helm_install but the task failed at locating dependency grpc 0.5.0-rc1, not sure if it's a red flag or not

2020-09-04 21:21 UTC, steven-sheehy approved these changes

2020-09-04 21:40 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +      - PREVIEWNET
I've seen it before, not related to your changes. Helm doesn't seem to be respecting the caret operator in semver constraint

2020-09-04 22:08 UTC, merged