Improved check-state-proof CLI support and documentation
hashgraph/hedera-mirror-node pull request #1016
Opened 2020-09-03 19:17 UTC by Nana-EC

**Detailed description**:
In 0.18.0 we added example CLI code to carry out independent state proof validation from the mirror node.
This item includes some improvements for support and documentation.

- Renames StateProof.md to README.md
- Changes Step 1-11 in readme to be ordered markup list
- Improves documentation by showing tool output in README
- Adds links to API design doc and REST config
- Adds a requirement section in doc for installation and configuration of REST API
- Adds npm start support for easier local, non-global testing
- Adds a host parameter that overrides environment
- Changes --env parameter to be non-required
- Adds preview net env
- Fixes a Timestamp bug that pads 0's of nanoseconds from record file where necessary 
- Substituted sample flag in favor of file flag
- Replaces notes.txt with apiResponse.json to allow you to store the API response for future re-validation
- Changes command name from `state-proof` to `check-state-proof`

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
Other items would include
- Adding ability to read file from stdin

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-09-03 19:59 UTC, steven-sheehy requested changes

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +```.env
yaml

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +  -t, --transactionId  Your Hedera Network Transaction Id e.g.
Missing new host, file options and still has sample

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +Missing required arguments: t, e
Remove error, instead recommend they explicitly invoke --help and show its output

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/startUp.js
> +  .option('f', {
Should support file as stdin input so you can `curl | check-state-proof`

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/startUp.js
> +        host = 'http://localhost:5551';
Would be better to add local as an explicit option and throw an error for default

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +The node based CLI tool `check-state-proof` can be installed as follows
We should change the folder name to match `check-state-proof`

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +``
Extra ticks

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +To run the CLI you must first install and then configure the REST API as explained below
Not necessarily. Most users will probably depend upon our managed mirror node to invoke against. That's why requirements should be npm and a mirror node with State Proof Alpha REST API enabled. Then we can mention if they'd like to run the REST API themselves, see how to enable it in `docs/configuration.md`. Any steps for how to run mirror node should be moved to the config doc. This doc should stay focused on running the cli against an existing API.

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +- t - The transactionId to be verified
This duplicates the help output above. Can probably remove that output and move it here to consolidate.

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +### Sample Case
Sample case terminology is still weird. I think we should simplify to 3 types of run modes: Environment, Custom Endpoint and Input File, in that order. For environment, can just mention the 3 values instead of showing separate commands for each environment.

2020-09-03 19:59 UTC, steven-sheehy commented on hedera-mirror-rest/state-proof-demo/README.md
> +## State Proof Logic
Think this makes more sense back at the top. Can simplify header to `Algorithm` or `Logic` or `Architecture`

2020-09-04 03:30 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +The node based CLI tool `check-state-proof` can be installed as follows
Updated

2020-09-04 03:30 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +```.env
Updated

2020-09-04 03:30 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +  -t, --transactionId  Your Hedera Network Transaction Id e.g.
Updated

2020-09-04 03:33 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +Missing required arguments: t, e
Updated

2020-09-04 03:33 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/startUp.js
> +        host = 'http://localhost:5551';
Added local and throwing for default

2020-09-04 03:49 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +``
Removed

2020-09-04 03:49 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +To run the CLI you must first install and then configure the REST API as explained below
Moved configuration to configuration doc and added a link

2020-09-04 03:59 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +- t - The transactionId to be verified
Consolidated

2020-09-04 04:07 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +### Sample Case
Good suggestion. Taken

2020-09-04 04:10 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/README.md
> +## State Proof Logic
Moved back up , to before requirements

2020-09-04 06:08 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/startUp.js
> +        host = 'http://localhost:5551';
Move stuff around since with default throwing error when a file is provided -e doesn't need to be set and it throws.
Rearranged by skipping host and env logic when a file is provided

2020-09-04 06:17 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/startUp.js
> +  .option('f', {
Seems weird to support stdin input when the -f option is supported.
Especially for the case of curl when the tool itself makes an http call by design.

I get that it's once less step but node script design makes it not very pretty (trying now) for a script to support both console arguments and stdin input. 
Mainly because the result stdin input isn't available immediately and is chunked through so you have to build it over time and ensure everything came though. 
This process isn't synchronous so I'd have to add await logic and some refactoring which is unnecessary for the non pipe scenario.

Will take another look but I'm suggesting punting for this PR.

2020-09-04 14:31 UTC, steven-sheehy approved these changes
LGTM

2020-09-04 14:31 UTC, steven-sheehy commented on hedera-mirror-rest/check-state-proof/README.md
> +> **_Note 1:_** The host value overrides the value of the environment.
nit: This would be better to add to the help output directly

2020-09-04 14:47 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/README.md
> +> **_Note 1:_** The host value overrides the value of the environment.
I'll add it there and also leave it here since people don't always read --help when the command works the fist time.

2020-09-04 14:47 UTC, Nana-EC commented on hedera-mirror-rest/state-proof-demo/startUp.js
> +  .option('f', {
Found an easier way to do this. Adding in next commit.

2020-09-04 18:55 UTC, merged