Bump hedera-protobuf to 0.9.0-alpha2 and support new fields
hashgraph/hedera-mirror-node pull request #1056
Opened 2020-09-17 02:55 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:
hedera-protobuf 0.9.0-alpha2 has removed the raw TransactionBody from the Transaction proto, and added a new message SignedTransaction that contains the TransactionBody and the SignatureMap, which is stored in the Transaction as a byteString.  This PR will support those changes while still being backwards compatible.

**Which issue(s) this PR fixes**:
Fixes #1027

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-09-18 08:02 UTC, ijungmann commented
[I imagine the way the transaction type is being fetched could be an issue now](https://github.com/hashgraph/hedera-mirror-node/blob/master/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java#L126)

2020-09-18 08:04 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/PubSubMessageTest.java
> +                "\"CjQKCwoFEJWa7zoSAhgKEgIYChiAwtcvIgUIgMLXLzIGYWJjZGVm2gEMCgIYFBIGYWJjZGVmEhIKEAoGYWJjZGVmGgZhYmNkZWY=\"" +
Not sure how this should be formatted, it's a bit ugly any way I put it.

2020-09-18 08:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
>              if (unknownFields.size() != 1) {
This seems like it will be problematic.

2020-09-18 08:09 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
> +            } else if (transaction.getUnknownFields().hasField(1)) {
Is it still appropriate to check the unknown fields (in place of doing getBody()) before looking at getBodyBytes, or should these two be flipped now?

2020-09-18 21:46 UTC, steven-sheehy requested changes

2020-09-18 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
I think this was done since body is a real object that can be converted to json automatically using Jackson. `SignedTransactionBytes` is an object but contains the raw body bytes inside it. So converting everything to `SignedTransactionBytes` doesn't really help conversion due to Jackson still not understanding that inner raw byte array.

We should probably remove this conversion hack, keep the fields exactly where they are and register a custom serializer with Jackson that can convert the body bytes no matter which of the three places it shows up as.

2020-09-18 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/PubSubMessageTest.java
> +                "\"CjQKCwoFEJWa7zoSAhgKEgIYChiAwtcvIgUIgMLXLzIGYWJjZGVm2gEMCgIYFBIGYWJjZGVmEhIKEAoGYWJjZGVmGgZhYmNkZWY=\"" +
This is wrong, base64 output is not queryable in Google BigQuery.

2020-09-18 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemTest.java
> +    private static final Path transactionProtoPath = Paths.get("data", "protoExamples", "transaction");
Not used?

2020-09-18 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemTest.java
> +            .addField(1,
Use constant

2020-09-18 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemTest.java
>      private static final Transaction TRANSACTION = Transaction.newBuilder()
This field no longer useful since it has nothing set on it. Would be clearer to just `Transaction.newBuilder()` in each test.

2020-09-18 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        TransactionBody transactionBody = TransactionBody.parseFrom(
A helper method `TransactionBody getTransactionBody(Transaction transaction)` in parent would help future proof this and reduce duplication.

2020-09-18 21:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
>              if (unknownFields.size() != 1) {
Should be fine as it's the unknown fields set in a different class.

2020-09-21 17:47 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Just to make sure I understand, you're looking for a Jackson serializer that takes the SignedTransaction or the BodyBytes if those are set and serializes them into readable JSON objects?  And then remove this logic and update the pub-sub project to deserialize that.

2020-09-21 17:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Yes, and ensure the unknown field TransactionBody is also passed through as JSON. Not necessarily a Jackson Serializer, but somehow configure Jackson to be made aware of how to encode these byte arrays into a JSON that represents a TransactionBody.

2020-09-21 17:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Makes sense, can do.

2020-09-22 17:35 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        TransactionBody transactionBody = TransactionBody.parseFrom(
Agreed, our tests are notorious for small product changes causing huge test changes

2020-09-23 05:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Based on my testing this isn't a Jackson issue, it's an issue with the JsonFormat printer used in the ProtoJsonSerializer, and I have not found a way yet to customize that.  [This issue](https://github.com/protocolbuffers/protobuf/issues/5919) implies this was an intended effect.

2020-09-23 05:32 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        TransactionBody transactionBody = TransactionBody.parseFrom(
Good idea, I have done just that.

2020-09-23 05:32 UTC, ijungmann commented on pom.xml
> +        <hedera-protobuf.version>0.9.0-alpha3</hedera-protobuf.version>
Upgrade to alpha4 as soon as it appears in Maven

2020-09-23 14:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
I don't believe it uses protobuf's JsonFormat, it uses Jackson to  encode to json. You can see the config [here](https://github.com/hashgraph/hedera-mirror-node/blob/5cabe304c4e2eafd916b3f71ce8ef9b3b6e2144c/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/PubSubAutoConfiguration.java#L59).

You might be able to use [mix-ins](https://stackoverflow.com/a/55532363) to do custom serialization.

2020-09-23 14:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
And if for some reason it's truly not using Jackson despite being configured to do so, that should be addressed first.

2020-09-23 15:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Just saw that we use Jackson but then have a custom `ProtoJsonSerializer` that encodes the entire message to JSON. 🤦  There's no point in using Jackson at all if you're going to write the whole message using protobuf JsonFormat.

Jackson has built-in support for [protobuf](https://github.com/FasterXML/jackson-dataformats-binary/tree/master/protobuf), so not sure why Appy didn't use it. I don't see any related comments on the PR that added it. We can attempt to use that and get it working, but might be a bigger effort.

Other option is to go back to normalizing to the single field `body` even if it's not in the protobuf definition. We can clear the body bytes and signedTransactionBytes and always write a hidden field body=1. That might be the simplest option to do now.

2020-09-23 15:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Yeah, that's definitely what I was running into, I had the debugger set in the integration test and it was definitely hitting the message converter and then going to that custom serializer.
I like that approach, I'll see if the Jackson protobuf option plays ball without too much effort, if that's looking like a bigger issue I'll do the unknown body field approach.

2020-09-23 19:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
I think the same issue is going to occur when using the unknown field `body`, you cannot add a message to the unknown field set (or at least I haven't seen it), you have to turn it into a `ByteString` and set it as a length-delimited value, which means it's going to encode that as Base64 bytes as well.

2020-09-23 20:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Ok, other option is to change `PubSubMessage.transaction` to be a custom pojo with proto fields that match Transaction proto instead of the actual Transaction proto.

2020-09-23 23:50 UTC, ijungmann commented
The new protobuf is also losing the deprecated SignatureList field, is that something we need to handle when publishing the PubSubMessage?  Looks like it wasn't being used in the mirror-node code, but not sure how it affects things downstream.

2020-09-23 23:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Easy enough, is there a particular mapping tool/framework you use to map to pojos, or just write the logic as needed?

2020-09-23 23:54 UTC, steven-sheehy commented
I don't think SignatureList matters. The intent with the proto to JSON is to just passthrough what was given to us into Google BigQuery. This in theory future proofs us against future changes. The only reason the other fields gave us trouble is because they were byte arrays instead of objects and we needed the content of that byte array queryable.

2020-09-24 03:11 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
> +    private final SignatureMap signatureMap;
Added this so that we don't need to do more proto parsing when building the PubSubMessage.

2020-09-24 03:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
> +                SignedTransaction.parseFrom(transaction.getSignedTransactionBytes()).getSigMap();
I'm not a huge fan of parsing the SignedTransaction twice, but I have not come up with a way to refactor it yet.

2020-09-24 03:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
> +                return SignedTransaction.parseFrom(transaction.getSignedTransactionBytes()).getSigMap();
I'm not a huge fan of parsing the SignedTransaction twice, but I have not come up with a way to refactor it yet.

2020-09-24 03:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +        if (transaction.getSignedTransactionBytes() == ByteString.EMPTY) {
Transaction pojo has been added to the PubSubMessage class, expecting some comments/refactoring on that, but the tests do confirm that it is now serializing to the object, so the big issue is resolved.

2020-09-24 15:04 UTC, steven-sheehy requested changes

2020-09-24 15:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemTest.java
> +            .addField(1,
Still not resolved

2020-09-24 15:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
> +{"consensusTimestamp":1567188600419072000,"entity":{"shardNum":0,"realmNum":0,"entityNum":51520,"type":1},"transactionType":11,"transaction":{"body":{"transactionID":{"transactionValidStart":{"second
I can't tell what changed in this file. Just the tokenTransferLists, right?

2020-09-24 16:11 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemTest.java
> +            .addField(1,
Fixed now

2020-09-24 16:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
> +                return SignedTransaction.parseFrom(transaction.getSignedTransactionBytes()).getSigMap();
The two have been combined into a TransactionBodyAndSignatureMap wrapper class.

2020-09-24 16:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/RecordItem.java
> +            if (transaction.getSignedTransactionBytes() != ByteString.EMPTY) {
All != have been swapped to ! .equals(ByteString.EMPTY) in this class

2020-09-24 16:16 UTC, ijungmann commented on hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
> +{"consensusTimestamp":1567188600419072000,"entity":{"shardNum":0,"realmNum":0,"entityNum":51520,"type":1},"transactionType":11,"transaction":{"body":{"transactionID":{"transactionValidStart":{"second
Correct, without the tokenTransferLists the lines are identical.

2020-09-24 16:18 UTC, steven-sheehy approved these changes
LGTM

2020-09-24 16:56 UTC, merged