gRPC notify thread blocked improvement
hashgraph/hedera-mirror-node pull request #1057
Opened 2020-09-17 15:28 UTC by xin-hedera

**Detailed description**:

The backpressure buffer and overflow mechanism was triggered too early in performance tests when ingestion TPS is high, which leads to gRPC clients being dropped before they can catch up. This improvement addresses the following:

- Increases min/max of maxBufferSize and sets the default to 16384
- Adds timeout mechanism after backpressure buffer overflow
- Fixes inaccurate polling stats in `SharedPollingTopicListener`

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-09-17 23:48 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListener.java
> +        private long count = 0;
q: was AtomicLong having adverse effects? Why the change? I thought it was safer given the shared nature of this flow

2020-09-17 23:48 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +    protected abstract Logger getLogger();
Instead you could just add `protected final Logger log = LogManager.getLogger(getClass());` to the class.
Then all the classes extending wouldn't have to implement the `getLogger()`

2020-09-18 02:14 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListener.java
> +        private long count = 0;
- `PollingContext::onNext` was after `repeatWhen`
- it's possible that the messages returned by one poll are still in the queue for subscribers to consume (share() internally has a small queue of size by default 256, i.e., share requests 256 messages and buffer them no matter how big the request of the downstream subscribers is)
- this leads to the situation that onNext is increasing the atmoic counter for the current poll batch and at the same time repeat kicks in to subscribe, which triggers onPollStart and resets `count` to 0
- thus `count` becomes inaccurate

this is why `PollingContext::onNext` is moved. My thought is onNext and onPollStart now will not run concurrently, so atomic is not needed.

2020-09-18 04:24 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListener.java
> +        private long count = 0;
Gotcha

2020-09-18 14:21 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +    protected abstract Logger getLogger();
thanks, made the recommended change

2020-09-18 15:27 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-09-18 19:46 UTC, steven-sheehy requested changes

2020-09-18 19:46 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +                .doOnCancel(() -> processor.onNext("timeout"))
As I understand it, this code will trigger a cancellation after backpressure causes the buffer to fill up. That cancellation will trigger the timeoutFlux to publish after the buffer timeout. If no onNext occurs before the timeout, an exception is thrown. My concern here is I don't see how this can recover from the cancellation? There's no repeat or retry logic here. Please add a test for this scenario.

2020-09-21 19:00 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +                .replay(1)
changed from `publish()` to `replay(1)`

there is a race condition in `Flux.timeout()`:

1. Every timeout subscription has an `index` which is the sequence of the actual subscription's `onNext` call when the timeout subscription is created
1. then onNext of the timeout subscription is called, it delegates to `TimeoutMainSubscriber` to handle the timeout only if the saved `index` equals to the `index` in `TimeoutMainSubscriber`

It's possible that the `onNext` of timeout subscription and the actual subscription happen around the same time in different threads, and the actual's `onNext` triggers `index` increment so timeout won't happened.

Because with `publish()`, the "timeout" message is one-shot and once it's consumed, there will be no timeout triggered. Changing it to `replay(1)` will make the "timeout" message replayed to every subscriber of timeoutFlux thus timeout will happen even with the race condition

2020-09-21 22:30 UTC, steven-sheehy approved these changes

2020-09-21 23:53 UTC, Nana-EC approved these changes

2020-09-22 00:37 UTC, merged