allow individual maxLimit config in rest service monitor
hashgraph/hedera-mirror-node pull request #1060
Opened 2020-09-18 14:34 UTC by xin-hedera

**Detailed description**:

Supports per-resource `maxLimit` config in rest service monitor, so ops can configure a smaller threshold for low traffic environments.

- Adds separate configuration option `maxLimit` for `account`, `balance`, and `transaction`. The value will overrides the global `maxLimit` if it's smaller
- Adds missing consensus timestamp ascending order check for transactions query

**Which issue(s) this PR fixes**:
Fixes #1033  

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-09-18 15:24 UTC, Nana-EC approved these changes

2020-09-18 20:31 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js
> +    previousConsensusTimestamp = txn.consensus_timestamp;
changed from the last revision, directly compare the timestamp string

2020-09-21 16:33 UTC, steven-sheehy requested changes

2020-09-21 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
> +const config = require('../../config');
It's quite strange that we're using the config reader from `hedera-mirror-rest` and that the monitor_api has two different config formats (e.g. application.yaml and serverlist.json). We should remove this dependency and just use serverlist.json.

2020-09-21 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  if (!isGlobal) {
This conditional logic seems unnecessary and breaks encapsulation of the maxLimit properties. We should always have a limit set and include that in the query, regardless if it's the global or not.

2020-09-21 16:44 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
> +const config = require('../../config');
Please also add defaults to serverlist.json

2020-09-21 17:08 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  if (!isGlobal) {
the flag is used to honor the default `maxLimit` if there is no resource specific `maxLimit`

the original test checks whether the rest service honors the `maxLimit` set in application.yml, hence `limit=?` query should not be added

2020-09-21 22:59 UTC, steven-sheehy approved these changes

2020-09-22 00:04 UTC, Nana-EC approved these changes

2020-09-22 01:24 UTC, merged