HTS Design Doc
hashgraph/hedera-mirror-node pull request #1061
Opened 2020-09-18 18:57 UTC by Nana-EC

**Detailed description**:
Main nodes are adding a [TokenService](https://github.com/hashgraph/hedera-protobuf/blob/master/src/main/proto/TokenService.proto) to HAP, the Mirror Node needs to add support for this.

This change adds an HTS design doc with a design to support the changes
- Specifies goals of Mirror HTS support
- Specifies Database Schema updates needed to support tokens. Specifically adds new `token` and `token_balance` tables as well as updates transaction and response types
- Specifies GRPC changes to support streaming of token transfers.
- Specifies Importer changes. Specifically updates to balance CSV parsing and ingestion of new Token transaction bodies - - Specifies  REST API updates. Specifically updates to accounts and balances endpoints, swell as addition of Token REST APIs

**Which issue(s) this PR fixes**:
Fixes #1043 

**Special notes for your reviewer**:
- Please focus on the DB Schema updated and existing REST API updates. GRPC and Token REST API's can be updated in subsequent sprints
- Some refactoring can and should be done especially on GRPC side. Feel free to note out of scope or overly invasive changes that aren't needed initially

To-do's
- [ ] Revisit Balance ingestion to potentially support versions of CSV
- [ ] Revisit compatibility of `account_balance` `accountNum` and `accountRealmNum` with tables that use `entity_id`. Can queries be simplified 
- [ ] Sequence diagram for GRPC Token Service

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +```
Ignore TokenBalanceSerializer, left over from a previous thought, will remove

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +-   Add `TokenBalance` with `tokens` private class member
```suggestion
-   Add `TokenBalance`
```

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +            private static final long serialVersionUID = -2399552489266593375L;
replace serialVersionUID w unique one as this was copied

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +        freeze_default      boolean;
remove repeated
```suggestion
;
```

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +-   Update `AccountBalanceLineParser.parse` to parse additional token columns representing `TokenRelationships`.
```suggestion
-   Update `AccountBalanceLineParser.parse` to parse additional token column representing `TokenRelationships`.
```

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +
Add TransactionHandlers
```suggestion
### Transaction Handlers
```

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +5.  Add a Token Discovery REST API to show available tokens on the network
Eventually we'll need a tokenInfo endpoint
```suggestion
6.  Add a Token Info REST API to show details for a token on the network - `/api/v1/tokens/<symbol>`
```

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +4.  Add a Token Supply distribution REST API to show token distribution across accounts
Add api url here for context

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +Query parameters should include
Need to circle back, these were initial suggestions based on current API's

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +Query parameters should include
```suggestion
Optional Filters
```

2020-09-18 21:55 UTC, Nana-EC commented on docs/design/hts.md
> +Additions
```suggestion
Optional Filters
```

2020-09-18 21:57 UTC, Nana-EC commented on docs/design/hts.md
> +
Working on this

2020-09-18 22:59 UTC, steven-sheehy requested changes

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +This document highlights the architecture and design changes to be made on top of v0.19.0 code to support HTS.
Let's not mention specific versions as things can always change.

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +The behavior will be similar to that of the native HBAR token and as such the Mirror Node will persist token balances and transfer lists and support the retrieval of information through the API's.
nit: `through its APIs`

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +        symbol              character   varying(96),
Shouldn't duplicate symbol. token_id is enough.

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +        add column symbol   character varying(96) not null;
We shouldn't duplicate storage of the symbol especially in our biggest table. Also, I think token ID is immutable but token symbol is mutable. token_id should be enough.

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +        token_id            entity_id,
Should token_id be the primary key? It depends on how queries will use it. Definitely token_id should have a unique index on it.

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +        treasury            entity_id,
`treasury_account` or `treasury_account_id`

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +        symbol              character varying(96),
Have we confirmed with services if there's any limit imposed on the symbol size? There probably should be a limit since it's stored in state.

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +    create table if not exists token
Would prefer column names sorted since any other order would be arbitrary.

2020-09-18 22:59 UTC, steven-sheehy commented on docs/design/hts.md
> +        supply_key          bytea,
Are any of these keys equivalent to the submit_key that would make sense to reuse that field?

2020-09-18 23:48 UTC, Nana-EC commented on docs/design/hts.md
> +        symbol              character   varying(96),
Token API's will likely query via the symbol. 
Repeating it here avoids a join with the `token` table

2020-09-18 23:50 UTC, Nana-EC commented on docs/design/hts.md
> +        add column symbol   character varying(96) not null;
Fair point on the size of the table and mutability of the mentioned columns. 
Like above the hope was to avoid a join with another table on API queries.
Especially since eventually we'll be streaming updates from this table. Joins would be a performance hit on speed mores than the size of the table

2020-09-18 23:50 UTC, Nana-EC commented on docs/design/hts.md
> +        token_id            entity_id,
Correct, good catch. token_id should be the primary key. Will change

2020-09-18 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +        treasury            entity_id,
Yes had made the change to  `treasury_account` locally, will push on next comment

2020-09-18 23:55 UTC, Nana-EC commented on docs/design/hts.md
> +        symbol              character varying(96),
Noted in the `Open Questions` intending to circle back with services on this and others, thanks for highlighting

2020-09-18 23:55 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token
Can do

2020-09-19 00:48 UTC, Nana-EC commented on docs/design/hts.md
> +        supply_key          bytea,
Nope these are all different than the submit key. 
Each one allows a specific Token/Token-Account altering operation and not necessarily whether the account holder of the key can perform token transfers which I think would be the equivalent of submitKey (only those keys could submit messages to the topic entity).
They are similar in that one those keys can perform those operations

2020-09-19 00:59 UTC, Nana-EC commented on docs/design/hts.md
> +        add column symbol   character varying(96) not null;
We could work out not having the symbol here.
On the `/api/v1/transactions` response the current proposed solution returns the tokenId, however there's a chance we actually want to return the symbol.
This would require a join with the token table if so.

On the gRPC API streaming side it's possible for us to make the mapping call once at the beginning for use so that's solvable.
For REST API we may have to explore caching the mapping to optimize on performance

2020-09-19 00:59 UTC, Nana-EC commented on docs/design/hts.md
> +        symbol              character   varying(96),
Performance of the REST API's isn't an issue and if it becomes one we could explore caching the symbol-tokenId on the REST API side.
That's one other option if we feel strongly against the duplicate info here

2020-09-19 01:11 UTC, steven-sheehy commented on docs/design/hts.md
> +        add column symbol   character varying(96) not null;
We definitely can't have mutable data in an insert only table. I don't think the join is an issue since tokens will have thousands _maybe_ hundreds of thousands while cryptotransfer has hundreds of millions. I'm way more concerned about the mutability and storage size of a varchar field than joining with a small table. Plus we can always cache the tokenid to symbol mapping

2020-09-20 03:56 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token
All columns after primary key are sorted a-z

2020-09-20 03:56 UTC, Nana-EC commented on docs/design/hts.md
> +        treasury            entity_id,
Actually had it as `treasury_id`

2020-09-20 03:57 UTC, Nana-EC commented on docs/design/hts.md
> +        add column symbol   character varying(96) not null;
Seems like we're agreed on caching, dropping `symbol` for the mutability reasons you rightly pointed out

2020-09-20 03:57 UTC, Nana-EC commented on docs/design/hts.md
> +        symbol              character   varying(96),
Dropping `symbol`

2020-09-21 22:03 UTC, ijungmann commented on docs/design/hts.md
> +-   Ingest account token balances from balance stream  CSV files from the mainnet and persist to the database
nit: extra space after stream
```suggestion
-   Ingest account token balances from balance stream CSV files from the mainnet and persist to the database
```

2020-09-21 22:05 UTC, ijungmann commented on docs/design/hts.md
> +The behavior will be similar to that of the native HBAR token and as such the Mirror Node will persist token balances and transfer lists and support the retrieval of information through its API's.
nit: apostrophe not needed.
```suggestion
The behavior will be similar to that of the native HBAR token and as such the Mirror Node will persist token balances and transfer lists and support the retrieval of information through its APIs.
```

2020-09-22 00:19 UTC, Nana-EC commented on docs/design/hts.md
> +        symbol              character varying(96),
Current limit seems to be 32. But it's configurable so maybe we should add some padding incase of marginal increases over time

2020-09-22 03:28 UTC, ijungmann commented on docs/design/hts.md
> +    create table if not exists token_account_info
I agree, this is the only table I'm having some trouble following.

2020-09-22 03:36 UTC, ijungmann commented on docs/design/hts.md
> +-   Provide a streaming GRPC API to subscribe to HTS transfers for all accounts and or all tokens
nit: and/or
```suggestion
-   Provide a streaming GRPC API to subscribe to HTS transfers for all accounts and/or all tokens
```

2020-09-22 03:58 UTC, ijungmann commented on docs/design/hts.md
> +5. `crypto_transfer` table updated to persist token transfers and also distinguish between HBAR and other token transfers
I think that would also get rid of the need to allow nullable for the token_id when dealing with hbar, which would be nice.

2020-09-22 15:42 UTC, Nana-EC commented on docs/design/hts.md
> +5. `crypto_transfer` table updated to persist token transfers and also distinguish between HBAR and other token transfers
Yeah, agree that might be a better approach, especially for the streaming reasons as tokens bubble out in size and transfers.
Will make this change

2020-09-22 15:43 UTC, Nana-EC commented on docs/design/hts.md
> +    alter table if exists account_balance
Will remove from here as address already in #1070

2020-09-22 16:09 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token_account_info
I don't think that's correct.
Freeze, KYC and Wipe are all operations that are performed on an account with respect to a particular account.
Here's more context.
1. You have an existing account w HBAR's or create a new account and fund it HBARs. Said account has no tokens
2. Token FOOBAR is created and supplied etc
3. [NEW] There's will be an `accept token` flag set for an account to accept FOOBAR that needs to be set to receive that token
4. Account is sent FOOBAR tokens. This adds the account to the ledger for this token with a nonzero balance. The account will have a freeze status based on the freezeDefault value for the token. It will have a wipe value set to false at beginning.
5. [NEW] KYC is likely needed for many tokens and may even be a precursor to receiving tokens. Need for KYC is now specified by the presence of a kycKey. If present then KYC must be performed on an account for a token before it can receive tokens. KYC for an account for a given token can be undone. In which case we need to be able to represent the toggling of the flag KYC
6. Similarly an account can be frozen and unfrozen in respect to a single token. i.e. You could have FOO tokens and BAR tokens and only have your account frozen for BAR tokens. If an account is frozen by default/toggled it needs to be unfrozen before tokens can be received.
7. [NEW] Wipe seems to have been cut off. Originally, an account for a given token could be wiped. This would also burn the tokens the account held for that token. Again, this would be done for only a given token and not all tokens and may or may not affect your actual account with respect to HBARs.

I've highlighted the new information I've received.
Ultimately the need for this table is to represent the different token->account properties that can change and are not related to HBAR.
If an account had 3 tokens they'd be represent by 3 rows here. Each row per token-account

2020-09-22 16:16 UTC, xin-hedera requested changes

2020-09-22 16:16 UTC, xin-hedera commented on docs/design/hts.md
> +            "key": {
should this be `adminKey`?

2020-09-22 16:16 UTC, xin-hedera commented on docs/design/hts.md
> +-   `/api/v1/tokens?adminkey=HJ^&8` - All tokens with matching admin key
protobuf `Key` is a complicated structure, it can be a single key of different algorithms, it can be a threshold key with a threshold then recursively includes `Key`, or a `KeyList` recursively includes a list of `Key`s

in order to support such a filter, we need more clarity on how it works

2020-09-22 16:16 UTC, xin-hedera commented on docs/design/hts.md
> +        .proto.TokenID tokenID = 1; // The token ID to retrieve transfers for
may want to support `TokenRef` instead of just `TokenID`

2020-09-22 17:07 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token_account_info
2 new transaction types to be added to cover number 3.
These will mark the `onboarding` of an account to accept a token or to stop accepting.
At the time of accepting the defaults would be set and an entry in `token_account_info` would be added.
Future `TOKENFREEZE`, `TOKENUNFREEZE`,  `TOKENGRANTKYC`, `TOKENREVOKEKYC` and `TOKENWIPE` transactions would modify a single row in the `token_account_info` table
`TOKENASSOCIATE` & `TOKENDISSOCIATE`, yet to be added on service side

2020-09-22 17:39 UTC, ijungmann commented on docs/design/hts.md
> +    create table if not exists token_account_info
This makes more sense to me now, with those being per-account per-token operations I see the need for this.

2020-09-22 17:50 UTC, steven-sheehy requested changes

2020-09-22 17:50 UTC, steven-sheehy commented on docs/design/hts.md
> +          "tokenBalances": [
`tokens`

2020-09-22 18:15 UTC, Nana-EC commented on docs/design/hts.md
> +        symbol              character varying(96),
Actually the [default limit](https://github.com/hashgraph/hedera-services/blob/separate-tokenrels-fcm/hedera-node/src/main/resources/bootstrap.properties#L56) for the tokens.maxTokenNameLength property is 100 UTF-8 characters. This matches the maximum length of a memo

2020-09-22 19:53 UTC, Nana-EC commented on docs/design/hts.md
> +        supply_key          bytea,
I think it can be null. IN the doc there's expected behavior for when it is null under the "Key Types" section

2020-09-22 19:54 UTC, Nana-EC commented on docs/design/hts.md
> +        token               character varying(96)   not null,
Yes will revert back to `symbol` and I'm adding a serial primary key.
There will be 2 indexes added
```
create unique index if not exists token_account__token_account on token_account(token_id, account_id);

create index if not exists token_account__token_account_timestamp
     on token_account (token_id desc, account_id desc, create_timestamp desc);
```

2020-09-22 21:20 UTC, xin-hedera commented on docs/design/hts.md
> +        supply_key          bytea,
yes you are right

2020-09-22 23:33 UTC, Nana-EC commented on docs/design/hts.md
> +            "key": {
Design request seemed to want admin key as part of discoverability, can circle back

2020-09-22 23:34 UTC, Nana-EC commented on docs/design/hts.md
> +            "key": {
Yes, but I believe other REST APIs were using just key so I tried to match. Will confirm

2020-09-22 23:34 UTC, Nana-EC commented on docs/design/hts.md
> +        .proto.TokenID tokenID = 1; // The token ID to retrieve transfers for
Yes good idea

2020-09-22 23:39 UTC, Nana-EC commented on docs/design/hts.md
> +-   [ ] What filer options should be provided for new Token API's
Updated

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +            "tokenBalances": []
Updated

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +To achieve this
Removed

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +          "tokenBalances": [
Updated

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +1.  The `accounts` REST API must be updated to support `tokenBalances`
Updated

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +-   Add `insertTokenCreateTransferList()` and `insertTokenTransferList()` to parse out `txRecord.getTokenTransferListsList()`. Create a new CryptoTransfer object for each `TokenTransferList` item and
Simplified

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +    private static final String INSERT_TOKEN_BALANCE_STATEMENT = "insert into token_balance " +
Removed

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +    -   If the first line is `# version:2`, and 2nd line is `# TimeStamp` then use `BalanceFileReaderImplV2` as the reader
Updated

2020-09-22 23:51 UTC, Nana-EC commented on docs/design/hts.md
> +To support HTS the balance CSV adds a version comment to the file, comments the Timestamp and adds a `accountMetadata` column which is a binary representation of `TokenRelationship`.
Updated

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token
Updated as listing

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +        (59, 'TOKENFREEZEACCOUNT'),
Updated

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +        (58, 'TOKENGETINFO'),
Updated

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +        (56, 'TOKENCREATE'),
Updated

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token_account_info
Updated to just list

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +        balance             bigint              not null
Updated

2020-09-22 23:52 UTC, Nana-EC commented on docs/design/hts.md
> +        consensus_timestamp bigint              primary key not null
Updated

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +    create table if not exists token_balance
Updated to just list out

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +5. `crypto_transfer` table updated to persist token transfers and also distinguish between HBAR and other token transfers
Added `token_transfer`

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +![Architecture](./images/mirror-arch.png)
Renamed

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +-   Provide a streaming GRPC API to subscribe to HTS transfers for all accounts and or all tokens
Updated

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +-   Ingest account token balances from balance stream  CSV files from the mainnet and persist to the database
Updated

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +Changes should be applied in order of the following order to support easy 3rd integration.
Updated

2020-09-22 23:53 UTC, Nana-EC commented on docs/design/hts.md
> +The behavior will be similar to that of the native HBAR token and as such the Mirror Node will persist token balances and transfer lists and support the retrieval of information through its API's.
Updated

2020-09-23 04:21 UTC, Nana-EC commented on docs/design/hts.md
> +        private Long  divisibility;
Ended up removing class member details so as not to be over descriptive.
However intiialSupply should be fine as a `long` no? Then `divisibility` can be reduced to an `int`

2020-09-23 04:26 UTC, Nana-EC commented on docs/design/hts.md
> +-   `/api/v1/tokens?adminkey=HJ^&8` - All tokens with matching admin key
The example was a placeholder.
More realistic query is exactly what we have in /api/v1/accounts
```suggestion
-   `/api/v1/tokens?publickey=3c3d546321ff6f63d701d2ec5c277095874e19f4a235bee1e6bb19258bf362be` - All tokens with matching admin key
```

2020-09-23 04:26 UTC, Nana-EC commented on docs/design/hts.md
> +        .proto.TokenID tokenID = 1; // The token ID to retrieve transfers for
Noted locally but removed those details in the section

2020-09-23 04:35 UTC, Nana-EC commented on docs/design/hts.md
> +                "token": "FOOBAR",
This is certainly more succinct.
However, this would be the first section in all of our current REST API responses where there's no label for a value.
So it breaks the format in that sense.

2020-09-23 04:38 UTC, Nana-EC commented on docs/design/hts.md
> +              "token":"FOOBAR",
Yeah, I'm okay with managing duplication if we get more simplicity and matching db structure.
Will update

2020-09-23 05:12 UTC, Nana-EC commented on docs/design/hts.md
> +            "tokenId": "0.15.10",
Updated

2020-09-23 16:25 UTC, Nana-EC commented on docs/design/hts.md
> +            "key": {
I can change it to be clear though since tokens do have many keys

2020-09-23 16:27 UTC, Nana-EC commented on docs/design/hts.md
> +            "key": {
Yep per design request

> A client application can call an API to return all tokens issued 
> Returns token name, symbol, and admin key 
> Can also be specified by admin key(s)

2020-09-23 18:14 UTC, Nana-EC commented on docs/design/hts.md
> +              "token":"FOOBAR",
Yeah looks like `symbol` for now and then the `/api/v1/tokens` can be where we return `symbol` and/or `tokenId`

2020-09-23 19:06 UTC, Nana-EC commented on docs/design/hts.md
> +-   `/api/v1/tokens?adminkey=HJ^&8` - All tokens with matching admin key
The t_entities.key is also from the protobuf `key`, we're currently able to filter on that for the /api/v1/accounts?account.publickey=<key>.
So I believe it's not as complex as we think. It's also the exact same key so the sql query logic is the same and should be doable

2020-09-23 20:38 UTC, Nana-EC commented on docs/design/hts.md
> +              "token":"FOOBAR",
Actually looks like there's still some discussion on this, will circle back

2020-09-24 18:53 UTC, Nana-EC reviewed
Added some corrections based off of checked in schema.
Also note REST API responses should return tokenId not symbol.
We can but support for querying by symbol but we should do that later

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `create_timestamp`
Was changed to 
```suggestion
    -   `created_timestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `modify_timestamp`
Was changed to
```suggestion
    -   `modified_timestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `create_timestamp`
Was changed to
```suggestion
    -   `created_timestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `modify_timestamp`
Was changed to
```suggestion
    -   `modified_timestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `modifyTimestamp`
```suggestion
    -   `modifiedTimestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `createTimestamp`
```suggestion
    -   `createdTimestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `createTimestamp`
```suggestion
    -   `createdTimestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `modifyTimestamp`
```suggestion
    -   `modifiedTimestamp`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +2. Comments out the Timestamp e.g. `TimeStamp:2020-09-22T04:25:00.083212003Z`
```suggestion
2. Comments out the Timestamp e.g. `# TimeStamp:2020-09-22T04:25:00.083212003Z`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +              "symbol": "FOOBAR",
Will be changed to tokenId
```suggestion
              "token_id": "0.1.2",
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +              "symbol": "FOOCOIN",
```suggestion
              "token_id": "0.3.4",
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +-   `/api/v1/tokens/<symbol>/balances?timestamp=1566562500.040961001`
Additionally add publickey to match token adminKey
```suggestion
-   `/api/v1/tokens/<tokenId>/balances?timestamp=1566562500.040961001`
-   `/api/v1/tokens/< tokenId >/balances?publicKey=2b60955bcbf0cf5e9ea880b52e5b63f664b08edf6ed 15e301049517438d61864`
```
Basically we want similar parity with https://docs.hedera.com/guides/docs/mirror-node-api/cryptocurrency-api#additional-examples

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +-   `/api/v1/tokens?account.id=0.0.8` - All tokens for matching account
Add tokenId range
```suggestion
-   `/api/v1/tokens?token.id=0.0.8` - All tokens for matching account
-   `/api/v1/tokens?token.id=gt:0.0.1001`
```

2020-09-24 18:53 UTC, Nana-EC commented on docs/design/hts.md
> +`/api/v1/tokens/<symbol>/balances` this could be the equivalent of `/api/v1/balances?symbol=<symbol>` currently and would return a list of account and the token balances
```suggestion
`/api/v1/tokens/<tokenId>/balances` this could be the equivalent of `/api/v1/balances?account.id=<account.id>` currently and would return a list of account and the token balances
```

2020-09-24 19:08 UTC, steven-sheehy commented on docs/design/hts.md
> +              "transfers": [
Spurious transfers key and extra array

2020-09-24 19:08 UTC, steven-sheehy commented on docs/design/hts.md
> +            "tokenBalances": []
This doesn't seem to have changed.

2020-09-24 19:09 UTC, steven-sheehy commented on docs/design/hts.md
> +          "tokenBalances": [
This doesn't seem to have changed.

2020-09-24 20:40 UTC, steven-sheehy requested changes

2020-09-24 20:40 UTC, steven-sheehy commented on docs/design/hts.md
> +-   Add a `getTokenInfo()` to `tokens.js` to retrieve token info from `token` table
Missing URL format. Can probably remove this code related line.

2020-09-24 20:51 UTC, Nana-EC commented on docs/design/hts.md
> +-   [ ] Should balance returns for `accounts`, `balances` and `transactions` contain `token` or `tokenId` or both?
Returns should be `tokenId`.
Token API would be the place where both can be returned

2020-09-24 20:51 UTC, Nana-EC commented on docs/design/hts.md
> +-   [ ] What filter options should be provided for new Token API's
Provide parity with /accounts and /balances APIs where applicable i.e. filtering on accountId, tokenId and publicKey

2020-09-24 20:53 UTC, Nana-EC commented on docs/design/hts.md
> +              "token":"FOOBAR",
Final call is `tokenId` everywhere

2020-09-24 20:53 UTC, Nana-EC commented on docs/design/hts.md
> +Query parameters should include
Provide parity with /accounts and /balances APIs where applicable i.e. filtering on accountId, tokenId and publicKey

2020-09-24 20:55 UTC, ijungmann commented on docs/design/hts.md
> +-   Add a `CompositeBalanceFileReader` that implements `BalanceFileReader` and reads the first line of the CSV
Do we still want the parser to be lenient on the number of lines before the timestamp/version number?  Looks like right now allow the timestamp to be up to 10 lines deep, so long as the column headers don't come up first.

2020-09-25 03:03 UTC, Nana-EC commented on docs/design/hts.md
> +              "transfers": [
The idea was to have it similar to what was noted in the design doc copied below
```json
{
    transfers: [ 
        {account: 0.0.1234, amount: -1000},  
        {account: 0.0.98, amount: 1000} 
    ], 
    tokenTransfers: [ 
        {
            token: 0.0.1234, 
            transfers: [ 
                {account: 0.0.1234, amount: -1000},  
                {account: 0.0.98, amount: 1000} 
            ]
        
        }
    } 
}
```

However I left out the aggregation of the token. Corrected the `token_transfers` object should look like this
```suggestion
              {
    "token_id": "0.15.3",
    "transfers": [
        {
            "account": "0.0.1111",
            "amount": -10,        
        },
        {
            "account": "0.0.2222",
            "amount": 10
        }
    ]
},
{
    "token_id":"0.2.4"
    "transfers": [
        {
            "account": "0.0.3333",
            "amount": -10
        },
        {
            "account": "0.0.4444",
            "amount": 10
        }
    ]
}
```

2020-09-25 03:17 UTC, Nana-EC commented on docs/design/hts.md
> +-   Add a `CompositeBalanceFileReader` that implements `BalanceFileReader` and reads the first line of the CSV
Yeah I'd see leave that lenience for V1. I'm presuming it's there for padded cases? 
We should verify why.
Given the file is now versioned it would be the best time to dump that logic for V2 if it's no longer needed.

2020-09-25 03:20 UTC, Nana-EC commented on docs/design/hts.md
> +              "transfers": [
Looks like it is possible to transfers span multiple tokens in a transaction, so grouping on a token would be useful

2020-09-25 03:21 UTC, Nana-EC commented on docs/design/hts.md
> +-   Add a `getTokenInfo()` to `tokens.js` to retrieve token info from `token` table
Added and removed

2020-09-25 03:24 UTC, Nana-EC commented on docs/design/hts.md
> +          "tokenBalances": [
Updated

2020-09-25 03:24 UTC, Nana-EC commented on docs/design/hts.md
> +            "tokenBalances": []
Updated

2020-09-25 20:12 UTC, steven-sheehy commented on docs/design/hts.md
> +              "transfers": [
We had said before in a previous [comment](https://github.com/hashgraph/hedera-mirror-node/pull/1061#discussion_r493192465) that we were okay with the duplication since it matches the database and proto structure more.

2020-09-25 23:16 UTC, Nana-EC commented on docs/design/hts.md
> +              "transfers": [
Yep, thanks for circling back. Will change to 
```suggestion
              "token_transfers": [
    {
        "token_id": "0.15.3",
        "account": "0.0.1111",
        "amount": -10
    },
    {
        "token_id": "0.15.3",
        "account": "0.0.2222",
        "amount": -10
    },
    {
        "token_id": "0.2.4",
        "account": "0.0.3333",
        "amount": -10
    },
    {
        "token_id": "0.2.4",
        "account": "0.0.4444",
        "amount": -10
    }
]
```

2020-09-25 23:27 UTC, steven-sheehy approved these changes
LGTM

2020-09-26 00:07 UTC, xin-hedera requested changes
some wording suggestion, not importing but nice to fix.

2020-09-26 01:14 UTC, Nana-EC commented on docs/design/hts.md
> +Changes should be applied in order of the following order to support easy third party integration.
Fixed

2020-09-26 01:14 UTC, Nana-EC commented on docs/design/hts.md
> +-   Add `token_transfer` table table. with the following class members
Fixed

2020-09-26 02:22 UTC, xin-hedera approved these changes

2020-09-28 03:13 UTC, merged