DB Schema Changes to Support HTS
hashgraph/hedera-mirror-node pull request #1073
Opened 2020-09-22 20:05 UTC by Nana-EC

**Detailed description**:
To support HTS the database must be able to 
-   Persist HTS Token transactions from record stream rcd files from the mainnet and persist information to the database
-   Persist account token balances from balance stream  CSV files from the mainnet and persist to the database

This PR  
- Adds `token` entity type to `t_entity_types` table
- Updates `t_transaction_types` with token transaction types and unchecked submit
- Updates `t_transaction_results` with token transaction type results
- Adds`token` table to hold token properties
- Adds `token_account` table to capture token-account info such as frozen, kyc and wipe status
- Adds `token_balance` table to capture token account balances
- Adds `token_transfer` to capture token only transfers

**Which issue(s) this PR fixes**:
Fixes #1048 

**Special notes for your reviewer**:
- The service may see some additional changes on the transaction type, these can be added before sprint end
- These changes are captured in #1061 

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-09-22 21:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +     on token_transfer (token_id desc, account_id desc, consensus_timestamp desc);
Should be on `consensus_timestamp` only
```suggestion
     on token_transfer (consensus_timestamp desc);
```

2020-09-22 21:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/TokenIdConverter.java
> +public class TokenIdConverter extends AbstractEntityIdConverter {
Thought I had removed this to be left for Importer tasks to add.
Will remove

2020-09-22 21:27 UTC, steven-sheehy requested changes

2020-09-22 21:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    create_timestamp    bigint                  not null,
Audit timestamps are usual in past tense, like Spring JPA's Auditable interface. Would prefer `created_timestamp` and `modified_timestamp`

2020-09-22 21:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    modify_timestamp    bigint,
`modified_timestamp` should be not null and default to `created_timestamp` via code. This is pretty standard logic.

2020-09-22 21:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    frozen              boolean             not null,
Can these two have an explicit default? I'm pretty sure since it's a required boolean that it will be defaulted to false implicitly so good to put an explicit.

2020-09-22 21:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_transfer__token_account_timestamp
This index's fields are identical to the one above.

2020-09-22 21:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_account__token_account_timestamp
Are we sure this index is needed? It's a superset of the other index making it pretty wasteful.

2020-09-23 00:03 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    frozen              boolean             not null,
It wouldn't be safe to set a default for kyc and frozen since the token itself defines the default that should be used.
Token.freeze_default determine was the first value of token_account.frozen should take
And the presence of a kyc_key in token implies token_account.kyc defaults to true, its absence implies false.
Also the token details can change, as such frozen and kyc values need to be determined at TokenCreate insert time

2020-09-23 00:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    create_timestamp    bigint                  not null,
Updated

2020-09-23 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    modify_timestamp    bigint,
Good catch

2020-09-23 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_transfer__token_account_timestamp
Yeah caught it in my review also.  Should just be `consensus_timestamp`, updated

2020-09-23 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_account__token_account_timestamp
Yeah good point. Can remove for now.

2020-09-23 15:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    frozen              boolean             not null,
I think you're misunderstanding. It already _is_ setting a default. You have a non-null boolean, it has to have a value by its very definition. It's either setting the default via code (if using primitive type or boxed with a non-null value) or if code is passing null the database will default to false for these fields. My comment is that we should go ahead and set an explicit default

2020-09-23 15:51 UTC, xin-hedera requested changes

2020-09-23 15:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionTypeEnum.java
> +    TOKENDISSOCIATE(41);
Q: are token associate & token dissociate WIP items? I didn't see them in the published proto

2020-09-23 15:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    (197, 'TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT');
Q: same as above, TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT is not in published proto

2020-09-23 16:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionTypeEnum.java
> +    TOKENDISSOCIATE(41);
Yes WIP, PR should be coming out soon. Think I should leave it out till the new proto is pushed out?

2020-09-23 16:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    frozen              boolean             not null,
Gotcha, will set false then

2020-09-23 16:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionTypeEnum.java
> +    TOKENDISSOCIATE(41);
I'll revert it to match what's in master so it matches a version, can update it whenever new proto comes out

2020-09-23 16:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    consensus_timestamp bigint              primary key not null,
You're correct, will add that
```
    alter table if exists token_balance
    add constraint token_balance__pk primary key (consensus_timestamp, token_id, account_id);
```

2020-09-23 16:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    (197, 'TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT');
I'll revert it to match what's in master so it matches a version, can update it whenever new proto comes out

2020-09-23 19:26 UTC, steven-sheehy requested changes

2020-09-23 19:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +     on token_transfer (consensus_timestamp desc);
This index is a subset of the below index. Can you reorder the below index to have consensus_timestamp as first and drop this index?

2020-09-23 19:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    freeze_default      boolean                 not null,
These required booleans can have explicit defaults as well.

2020-09-23 19:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_balance__token_account_timestamp
A constraint also creates an index, otherwise it can't validate the constraint efficiently. This index can be dropped.

2020-09-23 20:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_balance__token_account_timestamp
Yep, problem here is the constraint doesn't give the desired order, makes it `asc` by default where as w want `desc` for this table.
`account_balance` seemed to have the same issues and had to add both the pk and the index to sort `desc`

2020-09-23 21:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_balance__token_account_timestamp
I believe you can [efficiently](https://www.postgresql.org/docs/9.6/indexes-ordering.html) scan a b-tree index defined as ascending backwards using `ORDER BY DESC`. The only reason you would want to define another index explicitly if some fields in the composite key are in different orders like `x ASC, y DESC`. Would be worthwhile to do a quick test to prove it as this can be a very large index in the future.

2020-09-23 21:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_balance__token_account_timestamp
Yeah you're right, it can sill be done efficiently as such.

2020-09-23 21:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +create index if not exists token_balance__token_account_timestamp
Results from a quick test: 2,052 MB account_balance table with 41,236,847 rows, using the `/accounts` query that pulls 1,000 rows.
Your proposed option without the additional index is like 50-100 microseconds faster
Given like you pointed out the index grows with size I'm fine with dropping this additional index

2020-09-23 21:42 UTC, steven-sheehy approved these changes

2020-09-23 22:59 UTC, xin-hedera approved these changes

2020-09-23 23:07 UTC, merged