Add a Redis HCS topic listener
hashgraph/hedera-mirror-node pull request #1075
Opened 2020-09-24 17:34 UTC by steven-sheehy

**Detailed description**:
- Add a `RedisEntityListener` that uses [Redis Pub/Sub](https://redis.io/topics/pubsub) to notify the gRPC component of new topic messages
- Add a `RedisTopicListener` that consumes topic message notifications from Redis Pub/Sub
- Add a `hedera.mirror.subscribers` gauge metric that tracks the current number of active subscribers
- Change `bufferTimeout` from a number to `Duration`

**Which issue(s) this PR fixes**:
Fixes #893 

**Special notes for your reviewer**:
Still needs negative testing and Helm chart updates

**Checklist**
- [x] Documentation added
- [x] Tests updated

2020-09-24 20:37 UTC, Nana-EC requested changes
1st review. Looking good. Some suggestions

2020-09-24 20:37 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/RedisTopicListener.java
> +        log.info("Cancelled shared subscription to {}", topic);
Can the log distinguish between Cancelled and Complete subscriptions.
Or have an `OnCancel()` and `OnComplete()` with appropriate log that call `unsubscribe()`

2020-09-24 20:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/RedisConfiguration.java
> +public class RedisConfiguration {
Same shared configuration note on this one as previously

2020-09-24 20:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/EntityIdDeserializer.java
> +public class EntityIdDeserializer extends JsonDeserializer<EntityId> {
The class notes the general EntityId but is only applicable for AccountID.
This should probably be renamed to `AbstractEntityIdDeserializer`, then have an `AccountIdDeserializer` that extends this and passes in `EntityTypeEnum.ACCOUNT`

Similar to was we do with the EntityIdConverters

2020-09-24 20:37 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.redis.enabled`                 | true                    | Whether to use PostgreSQL Notify to send topic messages to the gRPC process
Currently we support multiple listener options at the same time, should we consider making a list of enabled listeners e.g. 
`hedera.mirror.importer.parser.record.entity.listeners = [REPOSITORY, SQL, PGNOTIFY, REDIS]
That way there's no need to add an enabled configuration every time we add a new entity listener, as is the case with  `hedera.mirror.importer.parser.record.entity.redis.enabled`

2020-09-25 19:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/EntityIdDeserializer.java
> +public class EntityIdDeserializer extends JsonDeserializer<EntityId> {
Renamed to AccountIdDeserializer. We can add an abstract one once we have at least two sub-classes.

2020-09-25 19:05 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/RedisTopicListener.java
> +        log.info("Cancelled shared subscription to {}", topic);
Here it doesn't matter if the flux was cancelled or completed, this log is to denote the subscription status to Redis. As such, I've reworked the log to `Unsubscribing from {}`.

2020-09-25 19:06 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.redis.enabled`                 | true                    | Whether to use PostgreSQL Notify to send topic messages to the gRPC process
Thanks, updated

2020-09-25 23:15 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/config/RedisConfiguration.java
> +public class RedisConfiguration {
Made it entity agnostic by introducing a `StreamMessage` (not sure about the naming) marker interface. So the redis serializers can now serialize anything that implements that interface.

2020-09-25 23:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/RedisConfiguration.java
> +public class RedisConfiguration {
Made it entity agnostic by introducing a `StreamMessage` (not sure about the naming) marker interface. So the redis serializers can now serialize anything that implements that interface.

2020-09-28 15:26 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.redis.enabled`                 | true                    | Whether to use PostgreSQL Notify to send topic messages to the gRPC process
It's a good idea, however the enabled flag is not just used in a centralized `CompositeEntityListener`, but also individually within the concrete EntityListener to see if the batch save should occur. We'd have to inject the EntityProperties to every EntityListener and somehow map the current class to a value within a list.

Also, if we have additional properties associated with a concrete EntityListener like `maxJsonPayloadSize` it makes more sense to have them separate.

2020-09-28 17:41 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.redis.enabled`                 | true                    | Whether to use PostgreSQL Notify to send topic messages to the gRPC process
Sounds good

2020-09-30 19:59 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.grpc.listener.type`                          | REDIS            | The type of listener to use for incoming messages. Accepts either NOTIFY, POLL, REDIS or SHARED_POLL |
Weren't you supposed to leave the default as is so that it could be configured. Then when you add the Helm stuff then change this to REDIS as default?

2020-09-30 20:16 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.grpc.listener.type`                          | REDIS            | The type of listener to use for incoming messages. Accepts either NOTIFY, POLL, REDIS or SHARED_POLL |
Whoops, fixed.

2020-09-30 20:38 UTC, Nana-EC approved these changes
LGTM

2020-09-30 22:17 UTC, merged