add topic messages and stateproof tests to monitor_apis
hashgraph/hedera-mirror-node pull request #1076
Opened 2020-09-25 17:35 UTC by xin-hedera

**Detailed description**:
- Adds topic message tests to monitor_apis
- Adds stateproof tests to monitor_apis
- Adds non-existing topic id and non-topic topic id check to topics rest endpoint

**Which issue(s) this PR fixes**:
Fixes #667 

**Special notes for your reviewer**:

The topic message tests require an existing topic id of the target environment configured before running the backend.

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-09-28 17:14 UTC, steven-sheehy requested changes
How often does the state proof check run? One minute right? Can we decrease how often this one runs? Running once a minute per port per instance might incur unnecessary cost.

2020-09-28 17:14 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/topicmessage_tests.js
> +  tests.push(runTest(getTopicMessagesForNonTopicEntityId));
We don't need to add negative tests to the monitor. Unit tests are sufficient to test those.

2020-09-28 17:14 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/topicmessage_tests.js
> +  tests.push(runTest(getTopicMessagesByConsensusTimestamp));
We should have an optional (controlled via a property) freshness check for messages like we do for the endpoints.

2020-09-28 17:28 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-09-29 15:24 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/topicmessage_tests.js
> +  tests.push(runTest(getTopicMessagesForNonTopicEntityId));
removed

2020-09-29 15:25 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/topicmessage_tests.js
> +  tests.push(runTest(getTopicMessagesByConsensusTimestamp));
freshness check for topic messages and all freshness threshold are now configurable

2020-09-29 16:03 UTC, steven-sheehy requested changes

2020-09-29 16:03 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/README.md
> +-   [ ] An existing topic ID of the target Hedera Mirrornode environment
Can we make it such that this is optional? Either if not provided it doesn't run the applicable tests or it picks the most recent topic in topic_messages. I'm thinking if we ever add monitor to CI or when we run it locally we want it to work out of the box with minimal config.

2020-09-29 19:17 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/topicmessage_tests.js
> +    message: `Successfully retrieved balance from with ${freshnessThreshold} seconds ago`,
fixed. thanks.

2020-09-29 19:25 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/monitor_tests.js
> +    const {intervalMultiplier} = config[testModule.resource];
sure, made the requested update.

2020-09-29 19:26 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/README.md
> +-   [ ] An existing topic ID of the target Hedera Mirrornode environment
make `topic.topicId` optional and skip all topic message tests when it's not configured

2020-09-29 22:15 UTC, steven-sheehy approved these changes

2020-09-29 23:02 UTC, Nana-EC approved these changes

2020-09-30 14:20 UTC, merged