Minor updates to HTS Design and DBSchema
hashgraph/hedera-mirror-node pull request #1086
Opened 2020-09-28 18:35 UTC by Nana-EC

**Detailed description**:
Minor updates to HTS design doc and db schema 

- Updates doc with references for `associated`, token `name`, token `mint` and `burn` transaction handlers
- Updates cleanup.sql to clear token tables after tests
- Adds ed25519 public keys for token table

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-09-28 20:58 UTC, xin-hedera requested changes

2020-09-28 20:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    ed25519_freeze_key  varchar                 null,
should we suffix the new ed25519 public key columns with `_hex` like in `t_entities` table? That way, it's clear the key is hex encoded

2020-09-28 21:43 UTC, ijungmann submitted a review, later dismissed
LGTM

2020-09-28 22:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    ed25519_freeze_key  varchar                 null,
Sure, we can do that. Tried to shorten the name but that's useful specificity to have.

2020-09-28 22:37 UTC, xin-hedera submitted a review, later dismissed
LGTM

2020-09-28 23:43 UTC, steven-sheehy requested changes

2020-09-28 23:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token
Please sync the ResponseCode.proto. You're missing the recent [changes](https://github.com/hashgraph/hedera-protobuf/commit/14177cc7e8a5e7204f7233e08cab1324f6579976) in alpha5.

2020-09-28 23:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    divisibility            bigint                  not null,
This field is no longer and looks to have been replaced by `decimals`. Please do a thorough review of alpha5

2020-09-28 23:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    total_supply            bigint                  not null default 0,
How will this field get populated? It doesn't seem to be on any transaction. I only see it on GetTokenInfo.

2020-09-28 23:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>      kyc                 boolean             not null default false,
We should switch kyc to enum `TokenKycStatus` and freeze to `TokenFreezeStatus` enum

2020-09-28 23:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token_account
I don't see a wipe boolean anymore. How does this get populated?

2020-09-29 00:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    total_supply            bigint                  not null default 0,
Total Supply currently isn't being sent across. I had highlighted this in the doc as an open question as to how they will pass it.
In the interim we can calculate as it defaults to the `intialSupply` at creation. After this every mint increases it by said amount and every burn decreases it.
Also noted in the open question at the bottom of the doc

2020-09-29 00:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token_account
The wiped boolean is still there. It didn't get removed.
It's populated as false by default when a TokenAccount is created. 
On a TokenWipe transaction it would be set to true

2020-09-29 00:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>      kyc                 boolean             not null default false,
Yeah, that's more explicit. Probably have to add 2 new tables to persist the enums also
`token_kyc_statuses` and `token_freeze_statuses`

2020-09-29 01:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>      kyc                 boolean             not null default false,
I don't think the enum tables are necessary. I doubt these will ever change unlike response codes and transaction types.

2020-09-29 13:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token
This PR wasn't meant to cover all the changes in alpha5 as I'm addressing them in a separate PR for importer changes.
I just wanted to add a few minor shared items.
However, it'll make the other PR smaller so I'll make the new alpha5 changes here first

2020-09-29 13:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token_account
Circling back `wipe` isn't really a state as initially thought. Rather an action that essentially burns tokens from a single account and reduces it's amount and total supply.
As such I should remove `wiped`

I believe this is what you may have been referring to.

2020-09-29 14:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    ed25519_freeze_key_hex  varchar                 null,
Updated

2020-09-29 14:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token
Done

2020-09-29 14:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    divisibility            bigint                  not null,
Done

2020-09-29 14:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>      kyc                 boolean             not null default false,
Updated

2020-09-29 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
>  create table if not exists token_account
Indeed, thanks

2020-09-29 16:09 UTC, steven-sheehy requested changes

2020-09-29 17:42 UTC, Nana-EC commented on docs/design/hts.md
> +         (29, 'TOKENCREATION'),
Sounds good, will leave as is to match protobuf and update with alpha6 I guess.
Or are you suggesting leave as is without the change since Michael change will match what is in master right now?

2020-09-29 20:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    total_supply            bigint                  not null default 0,
Removed wiped column. Noted logic to keep `totalSupply` of token up to date

2020-09-29 20:44 UTC, Nana-EC commented on docs/design/hts.md
> +    -   `token_freeze_status` (FreezeNotApplicable = 0, Frozen = 1, Unfrozen = 2)
Updated

2020-09-29 20:45 UTC, Nana-EC commented on docs/design/hts.md
> +         (29, 'TOKENCREATION'),
Thanks. Went with ensuring code matches protobuf versions.
When alpha6 comes out I can change it back to `TOKENCREATE` and `TOKENDELETE`

2020-09-29 21:46 UTC, steven-sheehy approved these changes
LGTM

2020-09-29 21:50 UTC, merged