Token - add related fields balances and transactions rest api endpoints
hashgraph/hedera-mirror-node pull request #1087
Opened 2020-09-28 21:12 UTC by xin-hedera

**Detailed description**:

- Adds `tokens` array to the account object in balances response json for clients to retrieve token balance snapshot
- Adds 'token_transfers' array to the transaction object in transactions response json for token transfer transactions
- Adds integration tests for balances and transactions REST API endpoints

**Which issue(s) this PR fixes**:
Fixes #1047 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-09-29 23:02 UTC, Nana-EC reviewed
Looks good so far. Will circle back for a second take.

2020-09-30 20:30 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-16-specefic-id-tokentransfer.spec.json
> +{
file name is misspelled ~`transactions-16-specefic-id-tokentransfer.spec.json`~. Should be `transactions-16-specific-id-tokentransfer.spec.json`

2020-09-30 20:30 UTC, Nana-EC commented on hedera-mirror-rest/balances.js
> +        string_agg(tb.token_id || '=' || tb.balance, ',' ORDER BY tb.token_id) AS token_balances
nit: You should add a comment highlighting you're formatting the response as an aggregate of comma separated tokenid balance paris e.g. "0.0.2=1000,0.0.5=-333.." so that you can easily split it out later

2020-09-30 20:30 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +       string_agg(
nit: same thing here, add a comment with an example to highlight aggregation logic

2020-10-01 14:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.30.1__hts_support.sql
> +    add constraint token_balance__pk primary key (consensus_timestamp, account_id, token_id);
token balance query is by (consensus_timestamp, account_id), adjust the order of the column in the primary key so the query can utilize the index

2020-10-01 16:05 UTC, steven-sheehy requested changes

2020-10-01 16:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
> +        "token_transfers": [
the array inside array is needed since there are test cases with multiple token transfers in one transaction, renaming `tokentransfers` to `tokentransferstransactions` can make it less confusing.

the various top level account ids are only used to create the crypto transfer list (actually it's just transaction fee and node fee) for the tokentransfers transaction

2020-10-01 16:58 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
> +        "token_transfers": [
Agreed it is just for setup but also agreed a flatter structure would be better.
All account Ids should be created in the "accounts" section. 
Then token_transfers only needs to contain the array of token_ids, accounts and amounts

2020-10-01 17:21 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
> +        "token_transfers": [
the various accounts in either `cryptotransfers` or 'tokentransfers` are not for account creation into `t_entities` table. I see it's repeatedly mentioned otherways, did I miss anything?

2020-10-01 17:53 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
> +        "token_transfers": [
Correct, accounts don't get created via cryptotransfers but via entities array.

If a scenario is needed with multiple token transfers in one transaction, this can be done with a flat structure by simply duplicating the consensus timestamp. The setup json should match the table structure as much as possible to make it easy to insert and understand.

2020-10-01 18:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
> +        "token_transfers": [
I'd prefer the transfer array in transaction array structure. It reflects the layout of the transaction. Splitting entries in the list into multiple flat structure with the same consensus timestamp also makes it hard to correlate the input data and the expected json output.

on the other side, cryptotransfers is flat just because we don't test crypto transfers to multiple accounts and in fact we should, that would make it also a transfer array in transaction array structure.

2020-10-01 20:29 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-16-specific-id-tokentransfer.spec.json
> +            "account": "0.0.400",
changed sorting order of token balance / token transfer to the top level resource

2020-10-01 20:29 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +        string_agg(tb.token_id || '=' || tb.balance, ',' ORDER BY tb.token_id) AS token_balances
switched to `json_agg` with `json_build_object`

2020-10-01 20:29 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +       LEFT JOIN token_transfer ttl
sure, made the change

2020-10-02 02:57 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-10-02 15:50 UTC, steven-sheehy approved these changes

2020-10-02 17:05 UTC, merged