Add HTS Transaction Logic to Importer
hashgraph/hedera-mirror-node pull request #1089
Opened 2020-09-30 00:02 UTC by Nana-EC

**Detailed description**:
To support the new Token HAPI, we should enhance our importer to import the new token transactions.

This change includes 
- Updates to TransactionTypeEnum
- Update EntityTypeEnum and EntityId for new TokenID
- Adds new repository and domain classes
- Adds a TransactionHandler for each new transaction type
- Updates EntityListener and its concrete implementations for the new entities
- Updates EntityRecordItemListener to parse the new transaction types

**Which issue(s) this PR fixes**:
Fixes #1051 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-09-30 21:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                // FreezeNotApplicable = 0, Frozen = 1, Unfrozen = 2
remove and use enum. Here and below

2020-09-30 21:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens = new ArrayList<>();
remove tokens and tokenAccounts lists for now as we save immediately

2020-09-30 21:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        entity.setAutoRenewPeriod(txMessage.getAutoRenewPeriod());
Add conditional check and add expiry set

2020-09-30 21:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
> +        if (txMessage.getExpiry() != 0) {
```suggestion
        if (txMessage.getAutoRenewPeriod() != 0) {
```

2020-09-30 21:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +public interface TokenBalanceRepository extends CrudRepository<TokenBalance, TokenBalance.Id> {
Delete to not conflict with Ian

2020-10-02 16:30 UTC, steven-sheehy requested changes
Review still in progress, but submitting what I have so you can address.

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAssociateTransactionsHandler.java
> +        return null;
This should probably return the account id being associated to allow clients to filter transactions by that entity id and relate it to the transaction.entity_id.

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionsHandler.java
> +        return null;
This should probably return the account id being associated to allow clients to filter transactions by that entity id and relate it to the transaction.entity_id.

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        TokenCreateTransactionBody txMessage = recordItem.getTransactionBody().getTokenCreation();
nit: Would prefer a variable name that represents the thing it's holding. e.g. `tokenCreateTransactionBody`, `transactionBody`, `body`.

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        if (txMessage.getAutoRenewPeriod() != 0) {
Not an issue with your code, but autoRenewPeriod is modeled as a Duration in ConsensusCreateTopic and a uint64 here. Can we ask Michael if this can be switched to Duration?

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        if (txMessage.getExpiry() != 0) {
Should we ask services to model this as a Timestamp?

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFreezeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenFreeze().getToken());
Should this be the token or the account? We're not freezing the token we're freezing the account's use of this token. Or more generically, this action is modifying the account not the token.

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenGrantKycTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenGrantKyc().getToken());
Should this be the token or the account for the same reasons as above?

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRevokeKycTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenRevokeKyc().getToken());
Should this be the token or the account for the same reasons as above?

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUnfreezeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenUnfreeze().getToken());
Should this be the token or the account for the same reasons as above?

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
> +            entity.setAutoRenewAccountId(EntityId.of(txMessage.getAutoRenewAccount()));
Move to `transactionHandler.getAutoRenewAccount()`

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +            entity.setAutoRenewAccountId(EntityId.of(txMessage.getAutoRenewAccount()));
Move to `transactionHandler.getAutoRenewAccount()`

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenWipeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenWipe().getToken());
Should this be the token or the account for the same reasons as above?

2020-10-02 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccount.java
> +    private Long id;
We don't make use of this id, right? To save space and time it might be better to switch to a composite primary key.

2020-10-02 17:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    private int decimals;
This should be a long, schema is right

2020-10-02 17:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    @Column(name = "wipe_key_ed25519_hex")
Yes, that would be cleaner

2020-10-02 17:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAssociateTransactionsHandler.java
> +        return null;
Can't return one account Id since `TokenAssociate` and `TokenDissociate` are used on multiple accounts at a time

2020-10-02 17:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionsHandler.java
> +        return null;
Can't return one account Id since `TokenDissociate` can be applied to multiple accounts at a time

2020-10-02 17:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        if (txMessage.getExpiry() != 0) {
Yeah, probably better for consistency across entities to just do Timestamp.
I also need to change this to pull ns as looks like expiry is in epoch seconds

2020-10-02 17:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAssociateTransactionsHandler.java
> +        return null;
Actually, it's the opposite. 1 Account -> Many tokens.
Will return the Account entity in this case then.

2020-10-02 17:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionsHandler.java
> +        return null;
Actually, it's the opposite. 1 Account -> Many tokens.
Will return the Account entity in this case then.

2020-10-02 17:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFreezeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenFreeze().getToken());
Yeah, I think the confusion comes from the fact that the real thing being modified is the TokenAccount not the Account or the Token in the Freeze/Kyc cases. That's the info that should be extracted on a getEntity.
Neither Account nor Token are modified by these cases and so it's a toss up in terms of which one to return. 
Either ways you'd need the other for full visibility.

I think the right thing in a future refactor would be to return the appropriate entity of TokenAccount.

2020-10-02 17:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccount.java
> +    private Long id;
Yeah, it's unused. Composite would be more appropriate.

2020-10-02 18:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    @Column(name = "wipe_key_ed25519_hex")
`wipe_key_ed_25519_hex` would actually still require a mapping as hibernate translated `wipeKeyEd25519Hex` to `freeze_key_ed25519hex`.
If we want to avoid manual mapping we either set the schema to `wipe_key_ed25519hex` or rename the member to be `wipeKeyHexEd25519` and schema to be `wipe_key_hex_ed25519`

2020-10-02 18:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +        private EntityId tokenId;
Left over logic, meant to change

2020-10-02 22:06 UTC, steven-sheehy requested changes

2020-10-02 22:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                tokenAccount.setKycStatus(TokenKycStatus.Revoked_VALUE);
Account and token should be passed to onEntityId either here or in handler

2020-10-02 22:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (tokenAccount != null) {
Account and token should be passed to onEntityId either here or in handler

2020-10-02 22:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = retrieveTokenAccount(tokenID, tokenFreeze.getAccount());
Account and token should be passed to onEntityId either here or in handler

2020-10-02 22:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                TokenAccount tokenAccount = retrieveTokenAccount(token, accountID);
Account and token should be passed to onEntityId either here or in handler

2020-10-02 22:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                token.setModifiedTimestamp(consensusTimestamp);
Should we also have a delete flag on token?

2020-10-02 22:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                token.setTreasuryAccountId(EntityId.of(tokenCreation.getTreasury()));
Treasury and token should be passed to onEntityId either here or in handler

2020-10-03 00:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenWipeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenWipe().getToken());
This one is honestly both. So not sure.
Wipe will burn the number of tokens an account has but also deplore the totalSupply of the actual Token

2020-10-03 00:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +@ToString(exclude = {"freezeKey", "kycKey", "supplyKey", "wipeKey"})
Done

2020-10-03 00:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +            return Utility.protobufKeyToHexIfEd25519OrNull(key);
Done

2020-10-03 00:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +        private EntityId tokenId;
Remembered now, hit the issue last week where the Converter wasn't getting honored for @Id.
Leaving as is as discussed offline since as you noted it's not possible with JPA spec - https://github.com/eclipse-ee4j/jpa-api/issues/207

2020-10-03 00:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    public int getNewAccountKycStatus() {
Done. Created our own `TokenFreezeStatusEnum` and `TokenKycStatusEnum`

2020-10-03 00:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    private Long initialSupply;
Done

2020-10-03 00:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    private String freezeKeyEd25519Hex;
Done

2020-10-03 00:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    private int decimals;
Done

2020-10-03 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccount.java
> +    private int freezeStatus;
Done

2020-10-03 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (retrieveTokenAccount(token, accountID) == null) {
Can do

2020-10-03 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAssociateTransactionsHandler.java
> +        return null;
Updated

2020-10-03 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionsHandler.java
> +        return null;
Updated

2020-10-03 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        TokenCreateTransactionBody txMessage = recordItem.getTransactionBody().getTokenCreation();
Done

2020-10-03 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFreezeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenFreeze().getToken());
Went ahead and returned Account type

2020-10-03 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenGrantKycTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenGrantKyc().getToken());
Changed to Account

2020-10-03 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRevokeKycTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenRevokeKyc().getToken());
Changed to Account

2020-10-03 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUnfreezeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenUnfreeze().getToken());
Changed to Account

2020-10-03 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
> +            entity.setAutoRenewAccountId(EntityId.of(txMessage.getAutoRenewAccount()));
Done

2020-10-03 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +            entity.setAutoRenewAccountId(EntityId.of(txMessage.getAutoRenewAccount()));
Done

2020-10-03 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccount.java
> +    private Long id;
Done

2020-10-03 00:17 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TokenRepositoryTest.java
> +                () -> assertNotNull(actual),
Actually can just do a isEqualTo without ignoring anything

2020-10-03 00:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokenRepository.save(token);
Agreed. This is best path to get the ball rolling but we definitely need to scale.

Challenge is each update needs to ensure it has the correct information  from current state before updating. 
e.g. A token gets created with a freeze and Kyc settings to default to FROZEN and REVOKED. 
An account then Associates itself with the token, it will be frozen and revoked. 
Say accounts it gets Unfrozen and then soon after gets GrantedKyc. 
We need to make sure the persistence for the KycGrant picks the fact that it was unfrozen and doesn't accidentally revert the freeze state change.
That's why for now I'm just saving immediately, just like Entity updates do.

Currently using Spring cache so this should give us some breathing room to explore the right solution for Accounts and Tokens

2020-10-03 00:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                insertTokenAssociate(consensusNs, body);
Was trying to stick to the best practice of passing only the necessary objects in and not redoing conversion work that was already done e.g consensus time extraction.
RecordItem contains SignatureMap, and not all transactions need the TransactionRecord.
Though making it more uniform does set the ground work for encapsulating these methods in the appropriate classes later on.

How about a shared signature of the below?
```
private void insertTransactionType(long consensusTimestamp, TransactionRecord txRecord, TransactionBody txBody) {
```

2020-10-03 00:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    tokenAccount.setTokenId(EntityId.of(token));
They already are by the OnItem(). That's how the Entity is added to t_entities.
So far as the TransactionHandler implements the getEntity() method then it's covered in that sense

2020-10-03 00:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                tokenAccount.setModifiedTimestamp(consensusTimestamp);
Fair enough. In that case Wipe operations will be a no-op for TokenAccounts

2020-10-03 00:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = retrieveTokenAccount(tokenID, tokenWipeAccountTransactionBody.getAccount());
Token is already passed through in OnItem.
We shouldn't need to repass Account because it will always be a valid already create account and no Token transactions affect the actual Hedera account

2020-10-03 00:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = retrieveTokenAccount(tokenID, tokenUnfreezeAccountTransactionBody
Token is already passed through in OnItem.
We shouldn't need to repass Account because it will always be a valid already create account and no Token transactions affect the actual Hedera account

2020-10-03 01:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                .orElse(null);
Hmm, as is we won't have sufficient information to create an appropriate Token.
Update has the largest amount of info but doesn't have initialSupply, decimals etc.
delete/wipe only have the tokenId.
This would result in unexpected kyc & freeze behavior for accounts onboarded after this shallow creation.

2020-10-03 01:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                .orElse(null);
Hmm, as is we won't have sufficient information to create an appropriate TokenAccount.
freeze/grant/revoke/unfreeze/burn only have the tokenId.
This would result in unexpected kyc & freeze behavior for accounts as initial freeze and kyc statuses after this shallow creation will likely be wrong for many cases.

2020-10-03 01:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    token.setTreasuryAccountId(EntityId.of(tokenUpdateTransactionBody.getTreasury()));
Token is. Treasury will be an already created account.
I'm guessing this is also the Pre OA case that we need to cover

2020-10-03 01:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                token.setModifiedTimestamp(consensusTimestamp);
This already exists on the Entities object.
The assumption is any API call filtering on deleted will do the necessary join to pull that info.
Otherwise it'll be a duplication of data between the tables.

2020-10-03 01:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    tokenAccount.setTokenId(EntityId.of(token));
So with my original configuration all these transaction handlers would have had the Token Entity passed to the OnEntityId in the OnItem().
My guess is you're going off of your previous suggestions to change some of them to return the Account not Token. In which case I would now have to explicitly  can OnEntityId for which ever of the 2 wasn't covered.

2020-10-03 01:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    tokenAccount.setTokenId(EntityId.of(token));
This makes me think `TransactionHandler` interfaces `getEntity(RecordItem recordItem)` should be swapped/updated to either return all applicable entities or return an entity of a requested type for a given RecordItem. i.e.
```
List<EntityId> getEntities(RecordItem recordItem);
```
or
```
EntityId getEntity(RecordItem recordItem, EntityTypeEnum entityTypeEnum);
```

2020-10-03 03:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                insertTokenAssociate(consensusNs, body);
All the methods in RecordItem are already converted at this point as it's an immutable object. There's no penalty to pay for calling any of its getters. The `getConsensusTimestamp()` is a lazy getter and the protos are parsed.

There's a slight difference in that `consensusNs = Utility.timeStampInNanos(txRecord.getConsensusTimestamp())` and `recordItem.getConsensusTimestamp()` is `Utility.timestampInNanosMax(record.getConsensusTimestamp())`, but either approach is equivalent for consensus timestamp in records.

2020-10-03 03:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    tokenAccount.setTokenId(EntityId.of(token));
While the current approach is not ideal, I don't think that is a good approach either since it's a [Ask Don't Tell](https://martinfowler.com/bliki/TellDontAsk.html). What we eventually want is for the transaction handlers to extract the domain objects and call EntityListener for each one.

2020-10-03 23:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                insertTokenAssociate(consensusNs, body);
Works for me. Will update them to all to take in RecordItem.

2020-10-05 02:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                token.setTreasuryAccountId(EntityId.of(tokenCreation.getTreasury()));
Done

2020-10-05 17:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    // if not onboarded create create TokenAccount based off of Token details
```suggestion
                    // if not onboarded create TokenAccount based on Token details
```

2020-10-05 17:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            entityListener.onEntityId(accountEntityId);
Remove a already handled in OnItem()
```suggestion
            
```

2020-10-05 17:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            entityListener.onEntityId(accountEntityId);
Remove since covered by OnItem()
```suggestion
```

2020-10-05 17:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                insertTokenAccountUpdate(recordItem.getConsensusTimestamp(), token, accountID, true, false, false);
Add OnEntityId for every Token
```suggestion
                entityListener.onEntityId(EntityId.of(token));
                insertTokenAccountUpdate(recordItem.getConsensusTimestamp(), token, accountID, true, false, false);
```

2020-10-05 17:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            entityListener.onEntityId(accountEntityId);
Swap to do for Token since Account is covered by OnItem()
```suggestion
TokenID tokenID = tokenFreezeAccountTransactionBody.getToken();
EntityId.of(tokenID)
```

2020-10-05 17:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            entityListener.onEntityId(accountEntityId);
Swap to do token

2020-10-05 17:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    tokenAccount.setTokenId(EntityId.of(token));
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = retrieveTokenAccount(tokenID, tokenWipeAccountTransactionBody.getAccount());
Updating to have all TokenId's/AccountId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = retrieveTokenAccount(tokenID, tokenUnfreezeAccountTransactionBody
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    token.setTreasuryAccountId(EntityId.of(tokenUpdateTransactionBody.getTreasury()));
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                tokenAccount.setKycStatus(TokenKycStatus.Revoked_VALUE);
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (tokenAccount != null) {
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = retrieveTokenAccount(tokenID, tokenFreeze.getAccount());
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                TokenAccount tokenAccount = retrieveTokenAccount(token, accountID);
Updating to have all TokenId's be passed to OnEntityId where the OnItem() method doesn't already handle this

2020-10-05 17:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenWipeTransactionsHandler.java
> +        return EntityId.of(recordItem.getTransactionBody().getTokenWipe().getToken());
Left this as token

2020-10-05 18:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    entityListener.onTokenTransfer(new TokenTransfer(consensusTimestamp, accountAmount
Will add for token, missed on last commit

2020-10-05 21:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                tokenAccount.setModifiedTimestamp(consensusTimestamp);
Actually wipe has an amount which currently needs to be deducted from the token totalSupply. Updating that.
The above will likely be the case for TokenDelete

2020-10-05 21:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                .orElse(null);
Per internal discussions we'll go with logging in these cases to avoid unexpected issues. Expectation is 3rd party should have a mirror node start time that covers the creation of desired tokens.

2020-10-05 21:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                .orElse(null);
Per internal discussions we'll go with logging in these cases to avoid unexpected issues. Expectation is 3rd party should have a mirror node start time that covers the creation of desired tokens.

2020-10-05 22:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        if (txMessage.getAutoRenewPeriod() != 0) {
Requested

2020-10-05 22:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +        if (txMessage.getExpiry() != 0) {
Requested

2020-10-06 16:02 UTC, steven-sheehy requested changes

2020-10-06 16:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (transactionTypeEnum == TransactionTypeEnum.TOKENASSOCIATE || transactionTypeEnum == TransactionTypeEnum.TOKENDISSOCIATE) {
Yeah my hope was this would leave mostly boiler plate code to copy and paste into the transaction handlers when we made that move

2020-10-06 16:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccount.java
> +        associated = !associated;
That's a good point. Can change it back to simple sets

2020-10-06 17:04 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (transactionTypeEnum == TransactionTypeEnum.TOKENASSOCIATE || transactionTypeEnum == TransactionTypeEnum.TOKENDISSOCIATE) {
Changing now

2020-10-06 17:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenKycStatusEnum.java
> +    NOTAPPLICABLE(0),
Changing to NOT_APPLICABLE

2020-10-06 17:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (transactionTypeEnum == TransactionTypeEnum.TOKENASSOCIATE || transactionTypeEnum == TransactionTypeEnum.TOKENDISSOCIATE) {
Moved logic back into insertToken...
Moved missing Token or TokenAccount to retrieveMethod, but had to pass current transactionType and timestamp to make long informational

2020-10-06 20:41 UTC, steven-sheehy approved these changes
LGTM

2020-10-06 20:50 UTC, merged