Importer: Support new balance file version
hashgraph/hedera-mirror-node pull request #1090
Opened 2020-09-30 14:40 UTC by ijungmann

**Detailed description**:
Add support for new balance file which contains token balances as part of HTS.

**Which issue(s) this PR fixes**:
Fixes #1049 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-10-01 08:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AccountBalance.java
> +    })
The FileLoader test seems to show these aren't actually being picked up by the repository, despite them being in the DB.  Need to investigate

2020-10-01 08:31 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +    private static final String VERSION_010_HEADER_PREFIX = "# 0.1.0";
Add a test for this class

2020-10-01 18:26 UTC, Nana-EC requested changes
1st review, left some comments. Will circle back for a 2nd review

2020-10-01 18:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +    private static final int MAX_HEADER_ROWS = 10;
Not needed. I think we had discussed being strict on this version of the file, so we expect line 1 to have the version

2020-10-01 18:48 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoaderTest.java
> +import com.hedera.mirror.importer.repository.TokenBalanceRepository;
The source file `TokenBalanceRepository.java` is missing

2020-10-01 21:11 UTC, xin-hedera requested changes

2020-10-01 21:11 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoaderTest.java
> +        balanceFile = new BalanceFile(1600748700083212003L, 106, "2020-09-22T04_25_00.083212003Z_Balances.csv");
should test both v1 and v2 balance files

2020-10-01 21:11 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2Test.java
> +                    "0;123;700;CggKAxjsBxCEBwoHCgMY7QcQGQoKCgMY7gcQwKilBAoICgMY8gcQhAcKBwoDGPMHEBkKCgoDGPQHEMCopQQ",
the expected token balance list should be something like "," separated tokenid=balance string, not the base64 encoded protobuf

2020-10-02 05:02 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +    private void tryInsertBatchAccountBalanceAndTokenBalance(PreparedStatement insertBalanceStatement,
Yes, I was a little worried about that, I wasn't sure if it was worth it to always insert TokenBalances at the same time as AccountBalances or to save them separately when the batch size is hit..  I can put it back to having them be separate methods.

2020-10-02 16:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenBalance.java
> +//import com.hedera.mirror.importer.converter.TokenIdConverter;
Removed

2020-10-02 16:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenBalance.java
> +        private static final long serialVersionUID = -8547332015249955424L;
Added

2020-10-02 16:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +        tryExecuteBatchStatement(insertBalanceStatement, "Some account balance insert statement in the " +
Fixed

2020-10-02 16:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +    private static final String VERSION_010_HEADER_PREFIX = "# 0.1.0";
Corrected

2020-10-02 16:26 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +    private static final int MAX_HEADER_ROWS = 10;
Sure thing, fixed to only check line 2

2020-10-02 16:26 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoaderTest.java
> +import com.hedera.mirror.importer.repository.TokenBalanceRepository;
Added

2020-10-02 16:32 UTC, xin-hedera requested changes

2020-10-02 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +            String line = Optional.of(reader.readLine()).get().trim();
should handle NPE

2020-10-02 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2.java
> +            return new AccountBalance(balance, tokenBalances, new AccountBalance.Id(consensusTimestamp, EntityId
`accountId` created twice

2020-10-02 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/resources/data/accountBalances/v2/2020-09-22T04_25_00.083212003Z_Balances.csv
> +# 0.1.0
the first line does not match `CompositeBalanceFileReader.VERSION_2_HEADER_PREFIX`

2020-10-02 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +                throw new InvalidDatasetException("Timestamp / column header not found in account balance file");
```suggestion
                throw new InvalidDatasetException("Timestamp header not found in account balance file");
```

2020-10-02 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +                throw new InvalidDatasetException("Timestamp / column header not found in account balance file");
should read the column header after the timestamp line. otherwise the column header line is fed to the parser although the reader would just swallow the InvalidDataSetException and return a null which is then filtered in the streams pipeline.

2020-10-02 16:35 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +    private void tryInsertBatchAccountBalanceAndTokenBalance(PreparedStatement insertBalanceStatement,
I've put it back to being separate calls, each looking at their respective list size.

2020-10-02 20:02 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AccountBalanceRepositoryTest.java
>          assertThat(accountBalanceRepository.findByIdConsensusTimestamp(1L))
The test failure is caused by actual `tokenBalances` not equal to expected `tokenBalances`

In addition, since AccountBalance has oneToMany field `List<TokenBalance>`, we should test with token balance data instead instead

2020-10-02 21:37 UTC, steven-sheehy requested changes

2020-10-02 21:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +
Missing copyright. Please scan the other new files for the same.

2020-10-02 21:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +            line = Optional.of(reader.readLine()).get().trim();
NPE. There's no point in using Optional here. `StringUtils.defaultString(reader.readLine())` might be appropriate if you don't want to have to check for null.

2020-10-02 21:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +    private static final String VERSION_2_HEADER_PREFIX = "# version:2";
This constant belongs in `BalanceFileReaderImplV2`. `BalanceFileReaderImplV2` should also probably be verifying this line so it can be encapsulated.

2020-10-02 21:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +    private static final String COLUMN_HEADER_PREFIX = "shard";
Unused?

2020-10-02 21:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +                throw new InvalidDatasetException("Timestamp / column header not found in account balance file");
What he said.

2020-10-02 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2Test.java
> +                    "0;123;700;CggKAxjsBxCEBwoHCgMY7QcQGQoKCgMY7gcQwKilBAoICgMY8gcQhAcKBwoDGPMHEBkKCgoDGPQHEMCopQQ",
Converted test to use comma separated list of values.

2020-10-02 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java
> +                    tryInsertBatchTokenBalance(insertTokenBalanceStatement, accountBalanceList, insertBatchSize);
Fixed.

2020-10-02 22:03 UTC, ijungmann commented on hedera-mirror-importer/src/test/resources/data/accountBalances/v2/2020-09-22T04_25_00.083212003Z_Balances.csv
> +# 0.1.0
Fixed.

2020-10-03 03:14 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +package com.hedera.mirror.importer.parser.balance;
All four Reader classes have been moved to that package

2020-10-03 03:14 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +        this.fileBufferSize = balanceParserProperties.getFileBufferSize();
Removed

2020-10-03 03:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file)),
Wrapped in try with resources, also wrapped the two other Readers in a try with resources

2020-10-03 03:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file)),
Knocked the buffer size down to 16, the smallest power of 2 to fit the Version 2 header in.  Since we're also only looking for those first characters, not even the entire first line, I added a BoundedInputStream so we're not reading the entire first line, and I added a test to confirm this works.

2020-10-03 03:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +            String line = Optional.of(reader.readLine()).get().trim();
NPE now being handled

2020-10-03 03:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +            String lineLowered = line.toLowerCase();
Removing all leniency.

2020-10-03 03:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +                return version2Reader.read(file);
Added that method to only call read() once

2020-10-03 03:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +    private static final String COLUMN_HEADER_PREFIX = "shard";
Now being used to confirm column headers exist

2020-10-03 03:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +    private final int fileBufferSize;
Removed from both readers

2020-10-03 04:19 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2Test.java
> +        fileCopier = FileCopier
Refactored this to not use the file copy.  Also refactored the V1Reader test to do the same.  Couple things:

- Had to make it a Spring Boot test to use the @Value, I extended the Integration Test since it seemed appropriate
- Still need the testFile to write temporary lines to so it doesn't destroy the sample file, I just converted this to a temp file
- The mirror properties are being used in a couple places in the tests to get the shard num.

2020-10-03 04:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file)),
Scratch that, I refactored this one to be a try with resource, I see the other two won't work with that because they are returning streams, I have put those back.

2020-10-03 05:40 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +    private static final String VERSION_2_HEADER_PREFIX = "# version:2";
Moved to BalanceFileReaderImplV2

2020-10-03 05:41 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +            line = Optional.of(reader.readLine()).get().trim();
Removed.

2020-10-03 05:49 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +
Added copyright

2020-10-03 05:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceFileReader.java
> +    private static final String VERSION_010_HEADER_PREFIX = "# 0.1.0";
Done

2020-10-03 05:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2.java
> +            return new AccountBalance(balance, tokenBalances, new AccountBalance.Id(consensusTimestamp, EntityId
Fixed

2020-10-03 05:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/BalanceFileReaderImplV2.java
> +                throw new InvalidDatasetException("Timestamp / column header not found in account balance file");
Should be fixed, added a check as well to make sure the next line has the column headers

2020-10-03 06:04 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AccountBalanceRepositoryTest.java
>          assertThat(accountBalanceRepository.findByIdConsensusTimestamp(1L))
I've added the `usingRecursiveFieldByFieldElementComparator` to force the check to look at the tokenBalance fields instead of doing a basic ==.  Will work on adding token balance data.

2020-10-03 06:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2.java
> +public class AccountBalanceLineParserV2 {
Created AccountBalanceLineParser interface

2020-10-03 06:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2.java
> +     * Parses an account balance line to extract shard, realm, account, and balance. If the shard matches
Adjusted comment to mention token balances

2020-10-03 06:28 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/v2/AccountBalanceLineParserV2.java
> +            String[] parts = line.split(",");
Done here and in the v1 parser

2020-10-05 16:17 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoaderTest.java
> +        balanceFile = new BalanceFile(1600748700083212003L, 106, "2020-09-22T04_25_00.083212003Z_Balances.csv");
Redid this test suite to make it easy to test multiple versions, it now tests v1 and v2

2020-10-05 17:00 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AccountBalanceRepositoryTest.java
>          assertThat(accountBalanceRepository.findByIdConsensusTimestamp(1L))
Added Token Balance data to this test, I'm seeing some very odd behavior with the repository that's causing this test to fail so I will continue investigating.

2020-10-05 17:39 UTC, ijungmann commented on hedera-mirror-importer/src/test/resources/data/accountBalances/v2/2020-09-22T04_25_00.083212003Z_Balances.csv
> +shardNum,realmNum,accountNum,balance,tokenBalances
All previous files have been moved to v1, and all tests have been refactored to point to the new dir

2020-10-05 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AccountBalance.java
> +    })
There were flipped in the flyway script, so they weren't joining properly.  This has been fixed and tests confirm.

2020-10-05 20:27 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AccountBalanceRepositoryTest.java
>          assertThat(accountBalanceRepository.findByIdConsensusTimestamp(1L))
The issues with the join have been resolved, this is now fully fixed.

2020-10-05 22:02 UTC, Nana-EC reviewed
Logic looks good. Will circle back in a bit to go through tests

2020-10-05 22:21 UTC, steven-sheehy requested changes

2020-10-05 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/line/AccountBalanceLineParserV2.java
> +        List<com.hederahashgraph.api.proto.java.TokenBalance> tokenBalanceProtoList =
Again, NPE should be avoided. Can simply wrap for loop in check for `StringUtils.isNotBlank(line)` and return empty tokenBalances.

2020-10-05 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +            reader.readLine();
Would prefer version check is repeated here for encapsulation in case this class is ever used outside the composite in the future.

2020-10-05 23:42 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +import com.hedera.mirror.importer.parser.balance.line.AccountBalanceLineParserV2;
moved to `reader.balance.line`

2020-10-05 23:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/line/AccountBalanceLineParserV2.java
> +            List<String> parts = Splitter.on(',').trimResults().omitEmptyStrings().splitToList(line);
I've added the Splitter as a constant to both versions of the FileReader

2020-10-05 23:43 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2Test.java
> +    File balanceFile;
Made the files private here and in a few other places I spotted it

2020-10-05 23:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +            reader.readLine();
Added this check.

2020-10-06 00:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/CompositeBalanceFileReader.java
> +        } catch (IOException | NullPointerException ex) {
- I've switched `isFirstLineFromFileVersion` to use the `StringUtils` to be null safe.  

- I've also added a check to the Composite Reader to see if the first line is null, as the documentation says that a null line would only be returned if the end of the stream is reached, which would mean we got an empty file that no reader would be able to do anything with.  

- Also added null checks for File at the beginning of each reader.

2020-10-06 00:26 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +        } catch (NullPointerException ex) {
Removed NPE checks and added explicit null checks.

2020-10-06 00:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/line/AccountBalanceLineParserV2.java
> +        List<com.hederahashgraph.api.proto.java.TokenBalance> tokenBalanceProtoList =
I think the NPE catch was meant for the line splitter when it was still doing `line.split(",")`.  If it gets to this point in the code it should have a non-null string, which means if it fails it will be because it can't decode the protobuf, from there protobuf should always return a non-null list so we should be safe unless I'm missing something.

I've removed the NPE catch and did an explicit check on the line not being null, if you want to have it swallow/log the InvalidProtocolBufferException and return an empty list I can do that, but I think NPE-wise we're safe.

2020-10-06 15:00 UTC, steven-sheehy approved these changes
LGTM

2020-10-06 15:24 UTC, xin-hedera requested changes

2020-10-06 15:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV1.java
> +                            return parser.parse(line, consensusTimestamp, balanceParserProperties.getMirrorProperties()
`balanceParserProperties.getMirrorProperties().getShard()` is called per account balance line, there can be considerable performance hit. Please move it out of the streams pipeline.

2020-10-06 15:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +                            return parser.parse(line, consensusTimestamp, balanceParserProperties.getMirrorProperties()
same as above

2020-10-06 15:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV1.java
> +                            return parser.parse(line, consensusTimestamp, balanceParserProperties.getMirrorProperties()
True, just meant to remove as class variable in my previous comment but for performance it should be a method scoped variable.

2020-10-06 15:40 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +                        throw new InvalidDatasetException("Column header not found in account balance file");
Sure, that makes sense, I went ahead and fixed that.

2020-10-06 15:40 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV1.java
> +                            return parser.parse(line, consensusTimestamp, balanceParserProperties.getMirrorProperties()
Fixed.

2020-10-06 15:40 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV2.java
> +                            return parser.parse(line, consensusTimestamp, balanceParserProperties.getMirrorProperties()
Fixed.

2020-10-06 15:43 UTC, xin-hedera approved these changes
LGTM

2020-10-06 15:44 UTC, steven-sheehy approved these changes

2020-10-06 16:00 UTC, Nana-EC approved these changes
LGTM

2020-10-06 16:02 UTC, merged