Add redis support to the Helm charts
hashgraph/hedera-mirror-node pull request #1091
Opened 2020-10-01 23:30 UTC by steven-sheehy

**Detailed description**:
- Add a 3 node Redis cluster with Sentinel sidecar to the chart
- Add an importer dashboard
- Add a Redis dashboard
- Change Marketplace to disable Redis and continue to use pgnotify
- Change Pgpool authentication config from a script to a customUsersSecret
- Change code to notify via Redis by default
- Update all dependent chart versions to the latest
- Fix demo network not working by setting startDate to epoch for that network
- Fix use of deprecated CircleCI machine image
- Fix use of deprecated Helm chart repositories

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-10-02 02:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +            return Instant.EPOCH;
nit: add a comment to highlight why this is necessary. I'm guessing cause the timestamps are always in the past.

2020-10-02 04:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +            return Instant.EPOCH;
Done

2020-10-02 22:04 UTC, xin-hedera requested changes

2020-10-02 22:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        filters.put(downloaderProperties.getStreamType(), new DateRangeFilter(filterStartDate, endDate));
prefer not setting the filter if `filterStartDate == null`, so the filter will be null and later in record parser we hit the fast path instead of checking against the all pass filter.

```
if (dateRangeFilter != null && !dateRangeFilter.filter(recordItem.getConsensusTimestamp())) {
    return false;
}
```

2020-10-02 22:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        filters.put(downloaderProperties.getStreamType(), new DateRangeFilter(filterStartDate, endDate));
I looked at that. In general it's better to avoid null conditionals and supply default objects. Can you clarify how this is a slow path? It's just a simple method with two primitive comparisons.

```java
        public boolean filter(long timestamp) {
            return timestamp >= start && timestamp <= end;
        }
```

2020-10-02 22:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        filters.put(downloaderProperties.getStreamType(), new DateRangeFilter(filterStartDate, endDate));
it's slower than `dataRangeFilter != null`. overall it may not have much impact so my comment is a suggestion

2020-10-02 23:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        filters.put(downloaderProperties.getStreamType(), new DateRangeFilter(filterStartDate, endDate));
I didn't change this randomly, I had to change it for another reason to make the tests pass. I needed to differentiate between epoch and unset start date so made `getLastValidDownloadedFileInstant()` return null for latter. Without this change the filter was returning current time despite application status showing epoch.

Also, I'm not sure in what scenarios before my change that filterStartDate could be null, but I don't think it is correct to not put a date range filter even when endDate is populated. That would cause end date to not filter.

Can you clear your review if you're okay with it?

2020-10-02 23:54 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        filters.put(downloaderProperties.getStreamType(), new DateRangeFilter(filterStartDate, endDate));
A `[null start date i.e. EPOCH, MAX_INSTANT_LONG]` has the same effect as a `null` filter since they both allow all timestamp values.

There are cases that filterStartDate is null when endDate is MAX_INSTANT_LONG (either not set or set to MAX_INSTANT_LONG):

1. startDate is set to <= lastFileInstant, so effectively we don't need a filter
1. startDate is not set and lastFileInstant is after EPOCH (i.e., there are stream files downloaded), we don't need a filter

That said, using a filter which will let all items in the downloaded stream file pass have no difference than a `null` filter.

btw, there is a corner case for DEMO network, when startDate is not set and there are already some files downloaded, the filter will be `[EPOCH, MAX_INSTANT_LONG or the configured endDate]`. This won't cause missing of items but it's just looser than what it needs to be.

Also, in `getEffectiveStartDate`, the change for `DEMO` network seems problematic, I'll detail it in a separate comment.

2020-10-03 01:36 UTC, xin-hedera requested changes

2020-10-03 01:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
>              return max(startDate.minus(adjustment), lastFileInstant);
nit: since `lastFileInstant` can be `null`, startDate after adjustment may be before EPOCH and it becomes the effective start date, previous logic would cap effective startdate to >= EPOCH

2020-10-03 01:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +            return Instant.EPOCH; // Demo network contains only data in the past, so don't default to now
this will always set application status file name to EPOCH even there is a previous run which has downloaded some files. In that case, when startDate is not set, we should honor the timestamped file name in application status repository

2020-10-05 16:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +            return Instant.EPOCH; // Demo network contains only data in the past, so don't default to now
Thanks, should be fixed.

2020-10-05 16:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
>              return max(startDate.minus(adjustment), lastFileInstant);
Fixed

2020-10-05 18:03 UTC, xin-hedera approved these changes
LGTM

2020-10-05 18:57 UTC, merged