HTS: token supply distribution REST API
hashgraph/hedera-mirror-node pull request #1113
Opened 2020-10-08 21:15 UTC by xin-hedera

**Detailed description**:

- Implements HTS token supply distribution REST API
- Updates HTS design doc wrt token supply distribution REST API optional filters
- Adds unit tests and integration tests for token supply distribution REST API
- Fixes the issue mockpool returns entity ID as Number instead of string

**Which issue(s) this PR fixes**:
Fixes #1104 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2020-10-08 21:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__token_balance_index.sql
> +    on token_balance (consensus_timestamp desc, token_id desc, account_id desc);
sorting `desc` because by default the token supply distribution response is ordered by `account_id` in `desc` order

2020-10-08 21:21 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/mockpool.js
> +      row.node_account_id = EntityId.of(0, 0, i % this.NUM_NODES).getEncodedId().toString();
mockpool should return encoded entity ID as `string` instead of `Number` to be consistent with `pg` pool

2020-10-08 21:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/mockpool.js
> +        `${Number(accountNum.high) - (accountNum.high === accountNum.low ? 0 : i % (accountNum.high - accountNum.low))}`;
mockpool should return encoded entity ID as `string` instead of `Number` to be consistent with `pg` pool

2020-10-08 21:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/mockpool.js
> +        `${Number(accountNum.high) - (accountNum.high == accountNum.low ? 0 : i % (accountNum.high - accountNum.low))}`;
mockpool should return encoded entity ID as `string` instead of `Number` to be consistent with `pg` pool

2020-10-08 21:27 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +               'token_id', tb.token_id::text,
cast `token_id` from `bigint` to `text` then build json object, otherwise since it's wrapped into a JSON object, the type of column (`bigint`) is lost, `pg` won't be able to present it as `string` as workaround for javascript `Number` precesion issue

2020-10-08 21:27 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +            'token_id', tb.token_id::text,
cast `token_id` from `bigint` to `text` then build json object, otherwise since it's wrapped into a JSON object, the type of column (`bigint`) is lost, `pg` won't be able to present it as `string` as workaround for javascript `Number` precesion issue

2020-10-08 21:28 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +           'account_id', ttl.account_id::text,
cast `token_id` and `account_id` from `bigint` to `text` then build json object, otherwise since it's wrapped into a JSON object, the type of column (`bigint`) is lost, `pg` won't be able to present it as `string` as workaround for javascript `Number` precesion issue

2020-10-12 17:05 UTC, Nana-EC requested changes

2020-10-12 17:05 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const [tsQuery, tsParams] = utils.parseTimestampQueryParam(req.query, 'tb.consensus_timestamp', {
I've been trying to filter out the use of the `utils.parseTimestampQueryParam`, `utils.parseAccountIdQueryParam`, `utils.parseBalanceQueryParam` , `utils.parseLimitAndOrderParams` and `utils.parsePublicKeyQueryParam`.

It's older logic that accounts, balances and transactions endpoints established. Each method ends up puling all the query items form the request then pulling out the desired query and verifying it.

I've been trying to move to
1. Pulling out all query items once using `const filters = utils.buildFilterObject(req.query);`
2. Verifying them all at once using `utils.validateAndParseFilters(filters);`
3. Building the sql query with logic similar to `extractSqlFromTokenRequest`

It would be great if we can conform to that.
I'm hoping in a future backlog PR to rip out the aforementioned ones in favor of this.

2020-10-12 17:37 UTC, Nana-EC requested changes

2020-10-12 17:37 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  await addEntity(
I know having `addToken` and `addAccount` call `addEntity` makes for less code but I think it also results in having the spec objects define objects similar to the proto objects that don't equate to a importer domain object.
I believe the intent on the spec setup objects was to have a 1:1 object representation of a row in an existing table.
In that sense we should keep the current logic and specify an `entity` and a `token` object when adding a token.
As future entities that differ from accounts are added they are likely to be like `token` and require extra properties not found int he `t_entities` table.
Furthermore, this supports testing scenarios where a `token` row exists but say the `entity` row is missing.

2020-10-12 21:35 UTC, xin-hedera commented on docs/design/hts.md
> +-   `/api/v1/tokens/<token_id>/balances?account.publickey=2b60955bcbf0cf5e9ea880b52e5b63f664b08edf6ed15e301049517438d61864`
sure. now it's consistent with token discovery

2020-10-12 21:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  await addEntity(
Just reverted and created a new section 'entities' instead of reusing 'accounts' for the purpose of adding 'tokens' into the entities table.

Data presented at protobuf level has better readability and less error-prone since duplication is reduced. If needed, we can address it later.

2020-10-12 21:44 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  const [tsQuery, tsParams] = utils.parseTimestampQueryParam(req.query, 'tb.consensus_timestamp', {
changed it to the new workflow

2020-10-13 00:56 UTC, Nana-EC requested changes
Discovery API should be returning all the balances for tokens that match the token filters, not the account filters.
We should explore if account filters should be added to this endpoint in a separate ticket

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  if (!fs.existsSync(flywayDataPath)) {
I saw this too.
Ended up doing `fs.mkdirSync(flywayDataPath, {recursive: true});` but this works too

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +    throw InvalidArgumentError.forParams('token.id');
nit: I think we should just have this as tokenId like we have with topicId.
I don't think we want to keep the `x.y` naming convention used by accounts

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +          ON e.fk_entity_type_id = ${utils.ENTITY_TYPE_ACCOUNT}
This should be the publickey of the token entity not the account entity.
If a user wants to filter by the account public key for balances they would just use the `/balances` endpoint currently.
However, this brings up maybe a feature enhancement of adding filtering by publickey for both `token` and `account` entities.
For now we should do token, you can always create a Feature request for account.

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const tokenBalancesFilterColumnMap = {
According to the design doc this should only contain `id`, `balance`, `timestamp` and `publickey`

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +        if (!columnKey) {
You'd want to have this check first to make sure all cases processed are allowed queries.
For instance timestamp is working but is not in the list of `tokenBalancesFilterColumnMap`

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const tokenBalancesFilterColumnMap = {
Where `id` and `publicKey` are those of the `token` entity not the `account` entity

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-06-all-params.spec.json
> +  "url": "/api/v1/tokens/0.20.1/balances?account.id=gte:0.1.18&account.id=lt:0.1.20&account.balance=gt:45&publickey=3c3d546321ff6f63d701d2ec5c277095874e19f4a235bee1e6bb19258bf362be&timestamp=15665600
Should be 
```suggestion
  "url": "/api/v1/tokens/0.20.1/balances?id=gte:0.1.18&id=lt:0.1.20&balance=gt:45&publickey=3c3d546321ff6f63d701d2ec5c277095874e19f4a235bee1e6bb19258bf362be&timestamp=1566560003.000000000&order=asc",
```

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-08-invalid-param-values.spec.json
> +          "message": "Invalid parameter: account.id"
```suggestion
          "message": "Invalid parameter: id"
```

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-08-invalid-param-values.spec.json
> +          "message": "Invalid parameter: account.balance"
```suggestion
          "message": "Invalid parameter: balance"
```

2020-10-13 00:56 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-08-invalid-param-values.spec.json
> +          "message": "Invalid parameter: account.publickey"
```suggestion
          "message": "Invalid parameter: publickey"
```

2020-10-13 01:18 UTC, xin-hedera commented
> Discovery API should be returning all the balances for tokens that match the token filters, not the account filters.
> We should explore if account filters should be added to this endpoint in a separate ticket

I think we need some clarification on the design of 'Token supply distribution' API before diving into the individual comments.

This REST API endpoint path in the design doc:

`/api/v1/tokens/<token_id>/balances`

`token_id` is a path variable, that's why

1. the ID in the query parameter should not refer to a token
1. the public key in the query parameter should probably not refer to a token either

If we agree that filtering token supply distribution of a particular token by an account ID and / or its public key is not a so useful feature, we should remove it from doc & implementation.

2020-10-13 01:22 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +        if (!columnKey) {
this is done intentionally, the map is for generic filter handling while timestamp and public key need can't be done that way, so the two are handled by its own `case` branch;

on the other hand, even the two are in the map, the map & the following `!columnKey` won't get hit

2020-10-13 15:59 UTC, Nana-EC commented
> > Discovery API should be returning all the balances for tokens that match the token filters, not the account filters.
> > We should explore if account filters should be added to this endpoint in a separate ticket
> 
> I think we need some clarification on the design of 'Token supply distribution' API before diving into the individual comments.
> 
> This REST API endpoint path in the design doc:
> 
> `/api/v1/tokens/<token_id>/balances`
> 
> `token_id` is a path variable, that's why
> 
> 1. the ID in the query parameter should not refer to a token
> 2. the public key in the query parameter should probably not refer to a token either
> 
> If we agree that filtering token supply distribution of a particular token by an account ID and / or its public key is not a so useful feature, we should remove it from doc & implementation.

You're correct.
There was some confusion here.
`token_id` is indeed a path that filters down to a given token.
In that case you're right, `id` and `publickey`, would refer to that of an account not a token.
If anything we can drop the `account.` if we feel it's intended.

2020-10-13 16:00 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +          ON e.fk_entity_type_id = ${utils.ENTITY_TYPE_ACCOUNT}
As coded is correct.

2020-10-13 16:02 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const tokenBalancesFilterColumnMap = {
`id` and `publicKey` are defined correctly as for the token. However, this map should contain all the applicable query filters (excluding order and limit) for this endpoint similar to `filterColumnMap`

2020-10-13 16:06 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +        if (!columnKey) {
See `extractSqlFromTokenRequest`, it's able to use `filterColumnMap` to ensure only those filter queries in addition to order and limit are processed.
If the current logic works better for your query that fine, we should just make sure no additional query filters pass through, only those explicitly stated

2020-10-13 17:40 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +        if (!columnKey) {
the implementation does exactly what you described:

> we should just make sure no additional query filters pass through, only those explicitly stated

The difference compared to `extractSqlFromTokenRequest` and `filterColumnMap` is that `timestamp` and `publickey` for token balances need special handling, just like `limit` and `order` so their handling is promoted to individual case branches, not the generic default branch.

So in other words, because the way the filters from the token balances REST GET query go into the SQL query is different than token discovery:

1. `timestamp` needs a subquery and the `eq` query operator (or the ` = ` operator after parsing) needs to be overridden to ` <= `
2. the account's publickey query param is reflected as a condition in the entity join clause, not the top level where clause, for performance consideration

As a result, `timestamp` and `publickey` in token supply distribution indeed are not generic filters which go into the top level where clause by simply appending `AND ${key} ${op} ${value}`, thus they should not appear in `tokenBalancesFilterColumnMap`

2020-10-13 17:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  if (!fs.existsSync(flywayDataPath)) {
Interesting. i think the way the `{recursive: true}` works is because internally it recursively checks if every folder is created from the top level of `path`: if true, it just skips it so no error thrown. which works for our purpose!

2020-10-13 17:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +        if (!columnKey) {
Sounds good

2020-10-13 22:42 UTC, Nana-EC approved these changes

2020-10-14 15:52 UTC, steven-sheehy requested changes

2020-10-14 15:52 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  publickey: tokenBalancesSqlQueryColumns.PUBLIC_KEY,
I thought we said this would be `account.publickey`? Should this be removed since we explicitly have a case statement for publickey below?

2020-10-14 15:52 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  SELECT
We've been standardizing on lower case sql keywords, like the other API in this file.

2020-10-14 16:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__token_balance_index.sql
> +create index if not exists token_balance__timestamp_token_account
in the previous PR which adds token balances to `balances` API, I changed `token_balance__pk` to

`token_balance__pk primary key (consensus_timestamp, account_id, token_id)`

because the queries are all first on `consensus_timestamp` then `account_id`

For token supply distribution, it's first on `consensus_timestamp` then `token_id` so the new index is needed.

2020-10-14 16:10 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  SELECT
sure, will change it to lower case

2020-10-14 16:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__token_balance_index.sql
> +create index if not exists token_balance__timestamp_token_account
I see, but I'm not sure if this index will speed things up much in comparison to just using the `token_balance__pk`. The leading column in a b-tree multi-column index is the only column that reduces the number of index entries that are scanned and accounts for the [majority](https://www.postgresql.org/docs/9.6/indexes-multicolumn.html) of the speed improvements. I'm worried about the memory and write performance impact of this index.

2020-10-14 17:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__token_balance_index.sql
> +create index if not exists token_balance__timestamp_token_account
The index can speed up queries when there are many tokens or some tokens are associated with many accounts. For token balances query, both `consensus_timestamp` and `token_id` are with equality constraints, with the new index, I think both are taken into consideration to limit the index scan range. So when there are many tokens or some tokens are associated with many accounts, the new index should provide better performance.

Perhaps, we can drop it now and consider it when token utilization is high and the read performance improvement outweighs the write performance impact?

2020-10-14 18:40 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +    throw InvalidArgumentError.forParams('token.id');
changed to `tokenId` as suggested

2020-10-14 18:40 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +const tokenBalancesFilterColumnMap = {
clarified how the `tokenBalancesFilterColumnMap` in the other conversation

2020-10-14 18:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/token-balances-06-all-params.spec.json
> +  "url": "/api/v1/tokens/0.20.1/balances?account.id=gte:0.1.18&account.id=lt:0.1.20&account.balance=gt:45&publickey=3c3d546321ff6f63d701d2ec5c277095874e19f4a235bee1e6bb19258bf362be&timestamp=15665600
discussed offline and we all agreed for token balances query filtered by account fields, we keep the `account.` + field name format since it's self-explanatory and no ambiguity.

2020-10-14 18:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/token-balances-08-invalid-param-values.spec.json
> +          "message": "Invalid parameter: account.balance"
discussed offline and we all agreed for token balances query filtered by account fields, we keep the `account.` + field name format since it's self-explanatory and no ambiguity.

2020-10-14 18:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/token-balances-08-invalid-param-values.spec.json
> +          "message": "Invalid parameter: account.publickey"
discussed offline and we all agreed for token balances query filtered by account fields, we keep the `account.` + field name format since it's self-explanatory and no ambiguity.

2020-10-14 19:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/token-balances-08-invalid-param-values.spec.json
> +          "message": "Invalid parameter: account.id"
discussed offline and we all agreed for token balances query filtered by account fields, we keep the account. + field name format since it's self-explanatory and no ambiguity.

2020-10-14 19:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__token_balance_index.sql
> +create index if not exists token_balance__timestamp_token_account
just deleted the db migration file

2020-10-14 19:22 UTC, steven-sheehy approved these changes

2020-10-14 20:10 UTC, Nana-EC approved these changes
LGTM

2020-10-14 20:25 UTC, merged