HTS: REST Token Info
hashgraph/hedera-mirror-node pull request #1125
Opened 2020-10-12 18:47 UTC by Nana-EC

**Detailed description**:
With the addition of HTS customers will need a REST API to query the details of a specific token on the network
Implement a Token Info REST API per the design.

- Add /api/v1/tokens/<tokenId> endpoint to server.js
- Update tokens.js file to hold token retrieval data from database for tables token
- Add spec files to validate token query variations

**Which issue(s) this PR fixes**:
Fixes #1106 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-10-15 15:09 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +    token_id: EntityId.fromString(row.token_id).toString(),
Alphabetic sort of keys, please. Even primary keys.

2020-10-15 15:12 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +      row.auto_renew_account_id === null ? null : EntityId.fromString(row.auto_renew_account_id.toString()).toString(),
This is weird and inefficient. Why do we not have a separate `fromNumber(num)`?

2020-10-15 15:54 UTC, xin-hedera requested changes

2020-10-15 15:54 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +      if (results.rowCount === 1) {
should use `results.rows.length`. `rowCount` is not really `rows.length`, though for this query, they have the same value. https://node-postgres.com/api/result

nit: it's easier to read in this way:
```javascript
if (results.rows.length !== 1) {
  throw new NotFoundError();
}

// normal processing
```

2020-10-15 15:54 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
> +          "message": "Invalid parameter: token.id"
it's changed to `tokenId` in token balances API

2020-10-15 17:12 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-info-01-no-args.spec.json
> +    "accounts": [
Yeah, left over logic missed in merge. Will update.
Looks like not all the token specs are using entities.
So I might update those too

2020-10-15 17:12 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +    token_id: EntityId.fromString(row.token_id).toString(),
Can do

2020-10-15 17:12 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +      row.auto_renew_account_id === null ? null : EntityId.fromString(row.auto_renew_account_id.toString()).toString(),
Yeah, better to move into that function or have one that handles num

2020-10-15 17:12 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +      if (results.rowCount === 1) {
Will take your suggestion

2020-10-15 17:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
> +          "message": "Invalid parameter: token.id"
Will update, missed this as part of merge

2020-10-15 17:14 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +      row.auto_renew_account_id === null ? null : EntityId.fromString(row.auto_renew_account_id.toString()).toString(),
I don't think explicitly `toString()` is needed, since auto_renew_account_id is of type `bigint`, pg pool will auto convert it to a string. So the value is either `null` or a `string`.

2020-10-15 17:28 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
> +          "message": "Invalid parameter: token.id"
Actually, this is referring to the path param not the query param.
The `/tokens` endpoint still uses the token.id noted in `constants.filterKeys.TOKEN_ID` which needs to be updated in a follow up PR I can push out today.

2020-10-15 17:30 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
> +          "message": "Invalid parameter: token.id"
I added a `constants.filterKeys.TOKENID` that can be used and cases where there are multi entity filters would still want to use the `constants.filterKeys.TOKEN_ID`

2020-10-15 17:45 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +      row.auto_renew_account_id === null ? null : EntityId.fromString(row.auto_renew_account_id.toString()).toString(),
We'd still need a conversion to string in the non null case.
I'll configure the `fromInt` and update the `Entity.toString()` to handle nullable for more general usage

2020-10-15 19:54 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +      row.auto_renew_account_id === null ? null : EntityId.fromString(row.auto_renew_account_id.toString()).toString(),
So all the response values are indeed String, hence why Xin updated the fromString method.
I've added a isNullable param for table columns that may be null.
Also added the `fromInt` method that can be used which fromString utilizes

2020-10-16 17:23 UTC, xin-hedera approved these changes
LGTM

2020-10-16 17:47 UTC, steven-sheehy approved these changes

2020-10-16 17:58 UTC, merged