Add performance test for token transfer publish only
hashgraph/hedera-mirror-node pull request #1134
Opened 2020-10-15 22:02 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-10-19 07:01 UTC, ijungmann commented
Need to update documentation, add k8s yml/etc, and do some cleanup, but the tests are functional and test the needed systems.

2020-10-19 18:01 UTC, Nana-EC requested changes
Good progress. Some. comments and suggestion then will take a 2nd look.

2020-10-19 21:44 UTC, steven-sheehy requested changes

2020-10-19 21:44 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishAndRetrieveSampler.java
> +    private final DescriptiveStatistics publishTokenTransferLatencyStats = new DescriptiveStatistics();
Don't use `DescriptiveStatistics` as it keeps all values in memory and has resulted in memory leaks in the past. Use `SummaryStatistics` instead even though we miss out on percentiles. Can you change everywhere else using  `DescriptiveStatistics` including existing classes?

2020-10-19 23:10 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferPublishAndRetrieveClient.java
> +
License info should now be on all new classes thus far, I'll keep it in mind to add it as I refactor some of these into smaller classes.

2020-10-20 00:02 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferPublishClient.java
> +        // read in nodes list, topic id, number of messages, message size
All comments should be up to date now, I looked for anything mentioning messages, topics, or hcs and changed them accordingly

2020-10-20 00:04 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferPublishClient.java
> +    private int messagesPerBatchCount;
I've made this change, however do you want me to update/add the property it pulls from as well?  I tried to reuse the existing hcs publisher properties so that the .properties file doesn't grow out of control, I'm starting to wonder if putting a new .hts.* set of properties would be better because they're going to be entangled otherwise.

2020-10-20 00:04 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferRESTBatchClient.java
> +        // node info expected in comma separated list of <node_IP>:<node_accountId>:<node_port>
Updated

2020-10-20 00:05 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/SDKClientHandler.java
> +        return transactionId;
Good call, I've turned this into a method and moved it into a new Utility class, if it would be better suited elsewhere let me know.

2020-10-20 00:06 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferRESTBatchClient.java
> +            //TODO There has to be a better way to do this
Made the method in a Utility class as noted above.

2020-10-20 00:07 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/SDKClientHandler.java
> +//        AtomicInteger counter = new AtomicInteger(0);
Removed

2020-10-20 00:08 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransferRESTBatchSampler.java
> +        return webClient.get().uri(REST_PATH + transactionId).retrieve()
Cool, didn't know about that, I've made this change

2020-10-20 00:11 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishAndRetrieveSampler.java
> +        int indexOfBadPeriod = transactionId.lastIndexOf(".");
Made the necessary change as noted above.

2020-10-20 00:11 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishSampler.java
> +        // publish MessagesPerBatchCount number of messages to the noted topic id
Comments should now be updated.

2020-10-20 00:21 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishAndRetrieveSampler.java
> +    private final DescriptiveStatistics publishTokenTransferLatencyStats = new DescriptiveStatistics();
Sure, the only other place was the HCS Topic Message Publisher, all instances should now be converted to Summary.

2020-10-20 02:15 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishSampler.java
> +    private void printPublishStats() {
That seems like a good move, I've created a PublishSampler that has that method and allows for a custom message at the front and the three Publish samplers are extending it now

2020-10-20 02:15 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishSampler.java
> +        // publish MessagesPerBatchCount number of messages to the noted topic id
Fixed.

2020-10-20 02:38 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferPublishClient.java
> +    private int messagesPerBatchCount;
Let's reuse. I saw you made it `transactionsPerBatchCount` which makes sense.
If we ever get into a case where we want to publish multiple transaction types at different rates then we can add that property or think of an easier way to do it.

2020-10-20 02:56 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/TokenTransferGetRequest.java
> +public class TokenTransferGetRequest {
I ended up breaking this down even farther, I made a REST Request and then a REST getByIds Request extending that, a Publish Request and a TokenTransferPublishRequest extending that, and finally a composite class of those two to be used for the GetAndRetrieve test.

2020-10-20 02:56 UTC, ijungmann commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/TokenTransferRequest.java
> +public class TokenTransferRequest {
See above note.

2020-10-20 20:50 UTC, Nana-EC approved these changes
LGTM

2020-10-20 22:21 UTC, ijungmann commented
Added a bit of documentation and the k8s files to run the two tests, should be complete pending any further change requests.

2020-10-20 22:37 UTC, steven-sheehy approved these changes

2020-10-21 03:24 UTC, merged