Rosetta Unit Tests: Account, Block, Mempool, Network API Services
hashgraph/hedera-mirror-node pull request #1136
Opened 2020-10-16 14:07 UTC by georgiyazovaliiski

**Changes**

**1. Account Unit Tests**
1.1. TestNewAccountAPIService <- tests whether the constructor for AccountAPIService works correctly
1.2. TestAccountBalance <- straight case test for AccountService's AccountBalance method
1.3. TestAccountBalanceWithBlockIdentifier <- straight case test for AccountService's AccountBalance method with a valid BlockIdentifier
1.4 TestAccountBalanceThrowsWhenRetrieveLatestFails <- AccountBalance test which asserts that the function throws a Rosetta Error when RetrieveLatest() fails
1.5 TestAccountBalanceThrowsWhenRetrieveBlockFails <-AccountBalance test which asserts that the function throws a Rosetta Error when RetrieveBlock() fails
1.6 TestAccountBalanceThrowsWhenRetrieveBalanceAtBlockFails <- AccountBalance test which asserts that the function throws a Rosetta Error when RetrieveBalanceAtBlock() fails after the logic before it passes successfully

**2. Block Unit Tests**
2.1 TestNewBlockAPIService <- tests whether the constructor for BlockAPIService works correctly
2.2 TestBlock <- tests whether the Block() function returns the correct response and no error (straight case)
2.3 TestBlockThrowsWhenFindByIdentifierFails <- asserts that Block() throws a Rosetta error when BlockRepository's FindByIdentifier() fails
2.4 TestBlockThrowsWhenFindBetweenFails <- asserts that Block() throws a Rosetta error when TransactionRepository's FindBetween() fails
2.5 TestBlockTransaction <- tests whether the BlockTransaction() function returns the correct response and no error (straight case)
2.6 TestBlockTransactionThrowsWhenFindByIdentifierFails <- asserts that BlockTransaction() throws a Rosetta error when BlockRepository's FindByIdentifier() fails
2.7 TestBlockTransactionThrowsWhenFindByHashInBlockFails <- asserts that BlockTransaction() throws a Rosetta error when TransactionRepository's FindByHashInBlock() fails

**3. Mempool Unit Tests**
3.1 TestNewMempoolAPIService <- tests whether the constructor for MempoolAPIService works correctly
3.2 TestMempool <- straight case for Mempool() function
3.2 TestMempoolTransaction <- straight case for MempoolTransaction() function

**4. Network Unit Tests**
4.1 TestNewNetworkAPIService <- tests whether the constructor for NetworkAPIService works correctly
4.2 TestNetworkList <- straight case for the NetworkList() function, asserts that it returns the correct list of networks, previously assigned to the NetworkAPIService
4.3 TestNetworkOptions <- straight case for the NetworkOptions() function, asserts that it returns the correct list of options, preciously assigned to the NetworkAPIService
4.4 TestNetworkOptionsThrowsWhenStatusesFails <- asserts that NetworkOptions() throws a Rosetta error when TransactionRepository's Statuses() fails
4.5 TestNetworkOptionsThrowsWhenTypesAsArrayFails <- asserts that NetworkOptions() throws a Rosetta error when TransactionRepository's TypesAsArray() fails
4.6 TestNetworkStatus <- asserts that the NetworkStatus() returns the correct StatusResponse, given dummy genesis block, dummy latest block and entries
4.7 TestNetworkStatusThrowsWhenRetrieveGenesisFails <- asserts that NetworkStatus() throws a Rosetta Error, when BlockRepository's RetrieveGenesis() function fails
4.8 TestNetworkStatusThrowsWhenRetrieveLatestFails <- asserts that NetworkStatus() throws a Rosetta Error, when BlockRepository's RetrieveLatest() function fails
4.9 TestNetworkStatusThrowsWhenEntriesFail <- asserts that NetworkStatus() throws a Rosetta Error, when AddressBookEntryRepository's Entries() function fails

2020-10-19 16:39 UTC, xin-hedera requested changes

2020-10-19 16:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/network/network_service_test.go
> +	assert.Equal(t, len(expectedResult.Allow.Errors), len(res.Allow.Errors))
should check the values in the `Errors` slice equal

2020-10-20 13:58 UTC, georgiyazovaliiski commented on hedera-mirror-rosetta/app/services/network/network_service_test.go
> +	assert.Equal(t, len(expectedResult.Allow.Errors), len(res.Allow.Errors))
Done. I added a new comparing function for the rosetta error arrays, which correctly checks the validity of this assertion.

2020-10-20 14:06 UTC, xin-hedera requested changes

2020-10-20 14:35 UTC, xin-hedera approved these changes
LGTM

2020-10-20 14:44 UTC, merged