CICD:Rosetta Github Workflow (build, test, codecov, cli-validation)
hashgraph/hedera-mirror-node pull request #1149
Opened 2020-10-19 11:35 UTC by Daniel-K-Ivanov

**Detailed Description**:
- Adds new Github Workflow for Rosetta
- Adds Rosetta `build` job
- Adds Rosetta `test` job 
- Uploads Coverage report to `code-cov`
- Rosetta CLI Validation workflow is removed and added as Job in this single Rosetta workflow file
- Rosetta CLI Validation runs against the `All-in-One` docker file and not against docker compose

**Which issue(s) this PR fixes**:
Closes [LimeChain #104](https://github.com/LimeChain/hedera-mirror-node/issues/104)

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-10-19 15:05 UTC, steven-sheehy requested changes

2020-10-19 15:05 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        run: sleep 60
This seems brittle and slow. Can we add a health check to the Dockerfile and wait for it to become ready here? Health check should curl the Rosetta API, I would think.

2020-10-19 15:05 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +      - name: Build hedera-mirror-rosetta
Should have a task that adds go module caching

2020-10-19 15:05 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +      - name: Run Unit Tests with Coverage
Should have a task that adds go module caching

2020-10-19 15:05 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        run: bash <(curl -s https://codecov.io/bash)
Do you have a link to this report?

2020-10-20 14:04 UTC, Daniel-K-Ivanov commented on .github/workflows/rosetta-api.yml
> +        run: sleep 60
new `wait-for-node` script was added

2020-10-20 14:14 UTC, Daniel-K-Ivanov commented on .github/workflows/rosetta-api.yml
> +        run: bash <(curl -s https://codecov.io/bash)
I suppose that you are referring to:
- https://codecov.io/gh/hashgraph/hedera-mirror-node/branch/cicd%2Frosetta
Latest commit:
- https://codecov.io/gh/hashgraph/hedera-mirror-node/tree/cicd%2Frosetta/hedera-mirror-rosetta
Actual uploaded report:
- https://codecov.io/api/gh/hashgraph/hedera-mirror-node/download/build?path=v4/raw/2020-10-20/C22318D8C79BEE934DEC507C38D4B845/05f1a621a291ae81c72a13fb6aac15642944715d/2f77ac08-004b-402e-8376-b13efa4d4ed2.txt

2020-10-20 15:33 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        run: bash <(curl -s https://codecov.io/bash)
Thanks

2020-10-26 11:42 UTC, Daniel-K-Ivanov commented
@steven-sheehy converting this PR to "ready for review" as the problem with the CLI validation was found and resolved in #1195 

The issue with running the `docker all in one file` was resolved as-well. Previously the run was executed against `master` (which is pointless) and now the validation is executed against the current source code. We tried to make the `all in one` docker file "generic" in terms of the target it was building (current source or master) but it resulted in inconvenient and uncommon Dockerfile design.

2020-10-27 14:59 UTC, steven-sheehy requested changes

2020-10-27 14:59 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
Can you add `${{ secrets.CACHE_VERSION }}`? This was a recent addition to the java workflow to workaround GitHub never removing entries from the cache and it growing unbounded. We can clear the cache without a code change periodically with this.

```
key: ${{ runner.os }}-go-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/go.sum') }}

2020-10-27 14:59 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +  cli-validation:
This task is failing. Can you check?

2020-10-27 14:59 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/wait-for-mirror-node.sh
> +
set -eu -o pipefail

2020-10-27 14:59 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/validation/Dockerfile
> +# This Dockerfile configuration is used to build
Validating a different Dockerfile than the one that goes to production defeats the purpose of validation. This file is guaranteed to get out of sync with the other file, especially since they're both so complicated with the all in one nature of it.

I see your comment about `We tried to make the all in one docker file "generic" in terms of the target it was building (current source or master)`. Did you try using build args to make the target branch configurable like below?

```Dockerfile
FROM golang:1.13 as builder
ARG GIT_BRANCH=rosetta
WORKDIR /tmp
RUN git clone https://github.com/hashgraph/hedera-mirror-node.git
WORKDIR /tmp/hedera-mirror-node/hedera-mirror-rosetta
RUN git checkout "${GIT_BRANCH}"
RUN go build -o rosetta-executable ./cmd
```

Then you can run  `docker build --build-arg GIT_BRANCH=$GITHUB_REF .` in the GitHub Action. I tried this locally with the Dockefile and it seems to work fine for this purpose. This approach allows you to use git to test both local code and master and not rely on docker COPY.

2020-10-27 15:46 UTC, failfmi commented on .github/workflows/rosetta-api.yml
> +  cli-validation:
Yes, this will fail until the PR with block updates is merged and then pulled on this branch.

2020-10-27 19:56 UTC, steven-sheehy approved these changes

2020-10-27 20:07 UTC, merged