Optimize AccountBalanceRepository queries
hashgraph/hedera-mirror-node pull request #1163
Opened 2020-10-21 15:01 UTC by xin-hedera

Signed-off-by: Xin Li <xin.li@swirlds.com>

**Detailed description**:
Optimize the queries for the find* methods in `AccountBalanceRepository` so hibernate generate select statement with left join.

**Which issue(s) this PR fixes**:
Fixes #1162 

**Special notes for your reviewer**:
Without the optimization, for example, the findAll method will run N+1 select queries: 1 to select all rows from account_balance table, and N to select token balances from token_balance table for each account.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-10-21 16:51 UTC, steven-sheehy requested changes

2020-10-21 16:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    @EntityGraph(attributePaths = {"tokenBalances"})
It might be better to define this once in `AccountBalance` via a `@NamedEntityGraph` then reference it here. That way if we add more fields it's defined in one spot.

2020-10-21 16:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    @EntityGraph(attributePaths = {"tokenBalances"})
We should probably remove the fetch parameter in the `@OneToMany` so it defaults back to lazy so it's clear we're relying on the repository to eagerly fetch and not the annotation in the domain.

2020-10-21 17:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    @EntityGraph(attributePaths = {"tokenBalances"})
sure will make the change

2020-10-21 20:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    @EntityGraph(attributePaths = {"tokenBalances"})
removed

2020-10-22 14:24 UTC, steven-sheehy approved these changes
LGTM

2020-10-22 14:39 UTC, merged