Support disabling pgpool load balancing in importer
hashgraph/hedera-mirror-node pull request #1166
Opened 2020-10-21 18:58 UTC by xin-hedera

Signed-off-by: Xin Li <xin.li@swirlds.com>

**Detailed description**:
pgpool II will disable load balancing for SQL statements beginning with a comment, this PR does so by prepends a comment to SQL statements generated by hibernate ORM.

- Adds a hibernate interceptor bean to prepend a comment to the generated sql statement
- Adds `HibernateConfiguration` to set the hibernate property so hibernate session factory use the custom interceptor
- Adds a configuration option `noLoadBalancing` to enable / disable the configuration and interceptor
- Sets `noLoadBalancing` to true as default in hedera-common charts

**Which issue(s) this PR fixes**:
Fixes #1154 

**Special notes for your reviewer**:
Verified it works by turning on `pgpool.logPerNodeStatement` and confirming all the sql statements with a leading comment are sent to the primary backend. Note `pgpool.logPerNodeStatement` is only supported in newer bitnami `postgresql-ha` releases, e.g., 5.1.0.

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-10-21 19:44 UTC, steven-sheehy requested changes

2020-10-21 19:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/DBProperties.java
> +    private boolean noLoadBalancing = false;
Would prefer a positively phrased property and in the infinitive form e.g. `loadBalance=true`.

2020-10-21 19:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HibernateConfiguration.java
> +                return "/* NO PGPOOL LOAD BALANCE */\n" + sql;
Add a comment that provides a link to the docs that show why this hack works.

2020-10-21 19:44 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.db.noLoadBalancing`                          | false                   | Whether to disable pgpool load balancing. If true, load balancing is disabled by prepending a commen
Can remove the last statement as it's unnecessary to say how it is implemented. Would add a blurb about what load balancing means in this context (e.g. it sends all reads to the primary instead of balancing them across the primary and replicas).

2020-10-21 19:44 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +            noLoadBalancing: true
This should be populated in `charts/hedera-mirror-importer/values.yaml` instead of here. The others are only here since they are needed by postgresql-ha chart.

2020-10-21 19:44 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-10-21 21:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/DBProperties.java
> +    private boolean noLoadBalancing = false;
sure. the only reason for a negative property name is I wanted to keep the property's value and `postgresql.enabled` the same.

2020-10-21 21:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HibernateConfiguration.java
> +                return "/* NO PGPOOL LOAD BALANCE */\n" + sql;
added

2020-10-21 21:39 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.db.noLoadBalancing`                          | false                   | Whether to disable pgpool load balancing. If true, load balancing is disabled by prepending a commen
sure, updated per suggestion.

2020-10-21 21:39 UTC, xin-hedera commented on charts/hedera-mirror/values.yaml
> +            noLoadBalancing: true
moved it to `hedera-mirror-importer`

2020-10-22 14:34 UTC, steven-sheehy approved these changes

2020-10-22 17:31 UTC, Nana-EC approved these changes

2020-10-22 17:47 UTC, merged