Update acceptance tests with v0.21.0 token rest checks
hashgraph/hedera-mirror-node pull request #1167
Opened 2020-10-22 01:59 UTC by Nana-EC

**Detailed description**:
With v0.21.0 HTS Acceptance Tests should be updated to cover new apis and use more robust checks

- Add Response POJOs to model JSON response
- Add token verification methods in `TokenFeature` class
- Add additional test cases to `hts.feature` to cover dissociate, wipe, burn, update and delete 
- Remove string search in JSON response and replace with POJO property checks

**Which issue(s) this PR fixes**:
Fixes #1152 

**Special notes for your reviewer**:
Would like to port this into v0.21.0 branch also

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-10-23 15:54 UTC, steven-sheehy requested changes

2020-10-23 15:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        URI uri = UriComponentsBuilder
This is more secure than string formatting, but now it's way less readable and maintainable. Why not this?

```java
@Bean
WebClient webClient() {
  return WebClient.create("http://host:8080/api/v1");
}
...
webClient.get().uri("/accounts/{accountId}?order=desc&limit={limit}", "0.0.2", 5);
```

2020-10-23 15:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenResponse.java
> +    @JsonProperty("auto_renew_account")
You should configure ObjectMapper to use snake_case so you don't have to manually map all of these.
```java
new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
```

2020-10-23 15:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenResponse.java
> +    @JsonProperty("auto_renew_period")
Do we really need to model all of the fields? Since we can't share domain classes with JavaScript, we should minimize our coupling with its domain model and only model the minimal set of objects and fields that we actually need.

2020-10-23 15:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Then("the mirror node {string} REST API should return status {int}")
Where is this used?

2020-10-23 20:21 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        URI uri = UriComponentsBuilder
Will add WebClient bean to the ClientConfiguration. Agree with that.

With this I think it addresses the readability.

OPS requested a log with the full absolute URI, which was easy to do this way, I'll add logs for `reactor.netty.http.client`.

2020-10-23 20:21 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenResponse.java
> +    @JsonProperty("auto_renew_account")
Good suggestion, will add to Bean configuration

2020-10-23 20:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenResponse.java
> +    @JsonProperty("auto_renew_period")
That's fair, will keep the ones we need.

2020-10-23 20:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Then("the mirror node {string} REST API should return status {int}")
Leftover, meant to remove.

2020-10-23 20:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        URI uri = UriComponentsBuilder
I really dislike the exploded URI segment building. Logging a URI is a cross cutting concern and more appropriate for an interceptor. See filter [functions](https://www.baeldung.com/spring-webclient-filters).

2020-10-23 22:19 UTC, steven-sheehy requested changes

2020-10-23 22:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAccountBalance.java
> +import lombok.Data;
imports should be below license. Otherwise next time we run the license plugin it will add another license to the top.

2020-10-23 22:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTransfer.java
> +import lombok.Data;
Same

2020-10-23 22:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenBalancesResponse.java
> +import java.util.List;
Same

2020-10-23 22:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public ClientResponse verifyAccountRestEndpoint(String accountId) {
Would prefer these all named as get or retrieve as they don't actual verify the response. The verification is done in the feature.

2020-10-23 22:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    private static final String API_V1 = "/api/v1";
Unused

2020-10-23 22:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public ClientResponse verifyAccountTransactionsRestEndpoint(String accountId, int lastCount) {
I'm not a fan of exposing HTTP specific objects to the caller. Would prefer returning the domain object and throwing an exception if any error. But current approach is fine for now.

2020-10-24 01:32 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public ClientResponse verifyAccountRestEndpoint(String accountId) {
Yeah meant to change this. Will do

2020-10-24 01:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public ClientResponse verifyAccountTransactionsRestEndpoint(String accountId, int lastCount) {
Initially when it was just text checking using the status was useful.
With the POJO mapping checking for null covers non 200 status.

Updated

2020-10-24 01:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    private static final String API_V1 = "/api/v1";
Removed

2020-10-24 01:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenBalancesResponse.java
> +import java.util.List;
Fixed

2020-10-24 01:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTransfer.java
> +import lombok.Data;
Fixed

2020-10-24 01:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAccountBalance.java
> +import lombok.Data;
Fixed

2020-10-24 02:03 UTC, steven-sheehy approved these changes
LGTM

2020-10-24 02:15 UTC, merged