Add support for case insensitive query params to REST API
hashgraph/hedera-mirror-node pull request #1168
Opened 2020-10-22 02:07 UTC by Nana-EC

**Detailed description**:
REST api should support query params regardless of case

- Add a middleware function using Proxy object to support lookup of values regardless of case
- Convert filter query name to lower case on creation
- Update a few test specs with camel case variations of query keys
- Set filter keys to lowercase for easy comparison

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-10-26 14:54 UTC, ijungmann commented on hedera-mirror-rest/constants.js
> +  TRANSACTION_TYPE: 'transactiontype',
Should TOKENID also be swapped to lowercase?

2020-10-26 16:16 UTC, Nana-EC commented on hedera-mirror-rest/constants.js
> +  TRANSACTION_TYPE: 'transactiontype',
Yeah, thanks

2020-10-26 16:44 UTC, ijungmann commented on hedera-mirror-rest/server.js
> +app.use(requestQueryKeyFormatter);
Might make sense to add a comment here so that it's not lumped in as "logging middleware".

2020-10-26 16:44 UTC, ijungmann submitted a review, later dismissed
LGTM

2020-10-27 02:04 UTC, xin-hedera requested changes

2020-10-27 02:04 UTC, xin-hedera commented on hedera-mirror-rest/middleware/requestHandler.js
> +    get: (target, name) => target[Object.keys(target).find((key) => key.toLowerCase() === name.toLowerCase())],
there is performance issue. in utils.js,

```javascript
const buildFilterObject = (filters) => {
  let filterObject = [];
  if (filters === null) {
    return null;
  }

  for (const [key, values] of Object.entries(filters)) {
```

the time complexity is O(n^2). this can be exploited by sending queries with a large number of query params.

2020-10-27 02:15 UTC, xin-hedera commented on hedera-mirror-rest/middleware/requestHandler.js
> +    get: (target, name) => target[Object.keys(target).find((key) => key.toLowerCase() === name.toLowerCase())],
this also does not handle the case where the same param appears in different lower-upper case combinations, e.g.,

```
timestamp=gt:100&Timestamp=lt:200
```

express will parse it into `{timestamp: 'gt:100', Timestamp: 'lt:200'}`

with the middleware, req.query['timestamp'] will always return the first match, which is 'gt:100'

2020-10-27 15:46 UTC, steven-sheehy requested changes

2020-10-27 15:46 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
> +          "message": "Invalid parameter: tokenid"
Not a fan of returning all lowercase to the user when the docs will show the camel case. See my other comment for a possible solution with classes.

2020-10-27 15:46 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestHandler.js
> +  req.query = new Proxy(req.query, {
Creating a proxy seems like a much heavier weight approach than just calling lowercase when validating the parameter. Besides probably being slower as Xin points out, the use of a reflective wrapper object probably has some performance penalty. 

I would suggest moving away from the switch statement and use a more OO approach. We already have filter constants and logic spread around too many classes. It might be time to consolidate them into a class. Pseudo code:

```javascript
// filters.js
var filters = {};

class Filter {
  constructor(name, validator, comparator) {
    this.name = name;
    this.validator = validator;
    this.comparator = comparator;
  }
}

func addFilter(tokenId) {
  filters[tokenId.name.toLowerCase()] = tokenId;
}

func validate(key, value) {
  const filter = filters[param.toLowerCase()];
  if (filter) {
    filter.validator(value);
  }
}

addFilter(new Filter('tokenId', (value) => ...));
...
```

2020-10-27 16:19 UTC, Nana-EC commented on hedera-mirror-rest/middleware/requestHandler.js
> +  req.query = new Proxy(req.query, {
Yeah this is a good approach. I had opened a ticket a while ago to solve this with a 3rd party framework, but this might give us more control over the data flow through the API

2020-10-27 21:17 UTC, Nana-EC commented on hedera-mirror-rest/middleware/requestHandler.js
> +    get: (target, name) => target[Object.keys(target).find((key) => key.toLowerCase() === name.toLowerCase())],
Good points.
I decided to go with a customer query parser.
Also changed for a for in which is more performant than `Object.entries()`

2020-10-27 21:18 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
> +          "message": "Invalid parameter: tokenid"
I agree it'd be nice to maintain camelCase for responses and docs.
However, providing that and case insensitive has additional implementation overhead which I'm not sure is worth it right now. 
For instance we'd have to ensure that someone who typed in `tokenid/TokenId/Tokenid/tokenId` still got the response message using `tokenId`.
When we were case sensitive this was easy, but with case insensitive support the above requires extra mapping back to the camelCase form.

We should  lump it into the eventual refactor though, unless you have a quick suggestion with the existing logic.

2020-10-27 21:20 UTC, Nana-EC commented on hedera-mirror-rest/middleware/requestHandler.js
> +  req.query = new Proxy(req.query, {
I think this should go under #712 
I think we could combine this with the custom query filter I added to optimize the whole flow better.

2020-10-27 21:22 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +app.use(requestQueryKeyFormatter);
Moved up under a different log

2020-10-28 15:47 UTC, ijungmann commented on hedera-mirror-rest/middleware/requestHandler.js
> +      // handle repeated values. Add to array if applicable of convert to array
nit: Think this is a typo.
```suggestion
      // handle repeated values. Add to array if applicable or convert to array
```
```suggestion
      // handle repeated values. Add to array if applicable of convert to array
```

2020-10-28 15:55 UTC, steven-sheehy submitted a review, later dismissed

2020-10-28 16:32 UTC, xin-hedera requested changes

2020-10-28 16:32 UTC, xin-hedera commented on hedera-mirror-rest/middleware/requestHandler.js
> +    }
this does not handle the case:

```
transactiontype=bar&transactionType=xyz&transactionType=ppp
```
expected: `{transactiontype: ['bar', 'xyz', 'ppp']}`
actual: ``{transactiontype: ['bar', ['xyz', 'ppp']]}``

2020-10-28 17:12 UTC, Nana-EC commented on hedera-mirror-rest/middleware/requestHandler.js
> +    }
Good catch. I need to concat int eh case of arrays

2020-10-28 17:20 UTC, Nana-EC commented on hedera-mirror-rest/middleware/requestHandler.js
> +    }
Added above as a test case and added a new test with multi key and case repetitions that verifies the handling of array value

2020-10-28 17:20 UTC, Nana-EC commented on hedera-mirror-rest/middleware/requestHandler.js
> +      // handle repeated values. Add to array if applicable of convert to array
Fixed

2020-10-28 17:22 UTC, ijungmann approved these changes

2020-10-28 17:41 UTC, xin-hedera approved these changes
LGTM

2020-10-28 18:29 UTC, merged