Fix stale accounts REST API
hashgraph/hedera-mirror-node pull request #1181
Opened 2020-10-24 02:03 UTC by Nana-EC

**Detailed description**:
Initial balance inner joins used by account rest api's resulted in info being stale.
In cases there would be no balance and therefore new accounts were accidentally filter out.

- Rearrange join to start with filter to get all accounts then pick up balances
- Add 3 integration spec files to cover cases were accounts had no balance yet

**Which issue(s) this PR fixes**:
Fixes #1177 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-10-26 16:31 UTC, ijungmann reviewed
Looks good to me, just a couple minor things.

2020-10-26 16:31 UTC, ijungmann commented on hedera-mirror-rest/accounts.js
>    // need to look  for the given account.id in both account_balance and t_entities table and combine with an 'or'
I think this comment might be out of date.

2020-10-26 16:31 UTC, ijungmann commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
Would there ever be a scenario where we have an account balance without the entity?  Just want to make sure getting rid of the full outer join doesn't cause side effects.

2020-10-26 16:36 UTC, xin-hedera requested changes

2020-10-26 16:36 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    }) as e
it's easier to read in this way:
```
from t_entities e
```
then move the condition `e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}` to the top level where clause

assume there is no performance difference.

2020-10-26 16:36 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    where ${startWhereCondition} (ab.consensus_timestamp = (select max(consensus_timestamp) from account_balance) or ab.consensus_timestamp is null)
adding `or ab.consensus_timestamp is null` here may have big performance impact, suggest to analyze it with testnet db.

2020-10-26 16:36 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
it was a `full outer join`, which based on my understanding covers the corner case that an account is not in `t_entities` but has balance record in `account_balance` table.

I'm not sure if that's a valid case or if it has happened before though.

2020-10-26 18:42 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
No. All account balances are for existing accounts created on the network.
The worst case scenario is the balance file gets serialized right after account creation, but even then at the most it would be 2 seconds later that the record file with the account creation transaction would be serialized.

2020-10-26 18:45 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
Xin reminded me of partial data.
even in accounts where mirror node was started after the parser has logic to create that entity for any applicable transaction that comes across.
So I take it back it could happen it could happen and that might have been the reasoning for the dual id logic between entity and account_balance

2020-10-26 18:48 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
Yes good point.
The importer does have logic to create entities it comes across when parsing the record file.
However, yes that would miss account with balances who don't have a transaction come across for a while.

I might have to revert back to some of the logic here and simple just reorganize.

2020-10-27 00:40 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
Fixed this by doing an early inner join to get balances from max timestamp. This gives last balance for all accounts know by network.
Then kept the outer join which will add any mismatches from records.
This now picks up all accounts even those without balances

2020-10-27 00:41 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    }) as e
Reverted back to original query with modification so this shouldn't apply anymore

2020-10-27 00:43 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    where ${startWhereCondition} (ab.consensus_timestamp = (select max(consensus_timestamp) from account_balance) or ab.consensus_timestamp is null)
You were right. Had atrocious performance.
Fixed this by doing an early inner join to get balances from max timestamp. This gives last balance for all accounts know by network.
Then kept the outer join which will add any mismatches from records.
This now picks up all accounts even those without balances.

Tested on dev with all testnet data. Change was marginal with an increase of about 30-40ms in query time

2020-10-27 00:43 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    left outer join account_balance ab on ab.account_id = e.id
Fixed, see note above

2020-10-27 00:44 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
>    // need to look  for the given account.id in both account_balance and t_entities table and combine with an 'or'
With revert comment is not still applicable

2020-10-28 16:05 UTC, ijungmann approved these changes

2020-10-28 16:22 UTC, xin-hedera requested changes

2020-10-28 16:22 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +        and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
per the offline discussion, `e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}` intends to include only `account` and `contract` entities but it won't work because of the full outer join. This results in entities of other types, e.g., `topic` being included in the query output.

should also add entities of other types to integration tests

2020-10-28 16:22 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    ` (ab.account_id = ? or (e.id = ? and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}))`
should remove `and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}` after moving the same condition out of the full outer join into where clause

line 115 needs the same update

2020-10-28 18:26 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +        and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
Yes, I'm changing the table that the outer join uses from 
```
full outer join t_entities e
```
to
```
full outer join (select id, exp_time_ns, auto_renew_period, key, deleted, fk_entity_type_id, ed25519_public_key_hex from t_entities where fk_entity_type_id < 3) e
```
This will ensure only account and contracts are considered

Will also update added tests with other entities

2020-10-28 18:28 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    ` (ab.account_id = ? or (e.id = ? and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}))`
Removed along with above noted change

2020-10-28 18:41 UTC, xin-hedera approved these changes

2020-10-28 22:41 UTC, merged