Rosetta: Record files (blocks) retrieval
hashgraph/hedera-mirror-node pull request #1195
Opened 2020-10-26 08:07 UTC by failfmi

**Detailed description**:
* Skip record files before the first account balance file (cache them).
* Update how latest and by hash blocks are found.
* Update all requests to be in `raw` format.
* Add unit tests for `persistence/block`.

**Which issue(s) this PR fixes**:
Fixes #None

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-10-26 21:39 UTC, xin-hedera requested changes
will review the test cases later

2020-10-27 06:28 UTC, failfmi commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +	br.dbClient.Raw(selectSkippedRecordFilesCount).Count(&startingIndex)
It actually works. (Example from docs -> ```db.Table("deleted_users").Select("count(distinct(name))").Count(&count)
// SELECT count(distinct(name)) FROM deleted_users```

2020-10-27 17:25 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +	br.dbClient.Raw(selectSkippedRecordFilesCount).Count(&startingIndex)
thanks for the clarification!

2020-10-27 21:33 UTC, xin-hedera submitted a review, later dismissed
LGTM

2020-10-28 15:44 UTC, xin-hedera approved these changes
LGTM

2020-10-28 15:45 UTC, merged