Add redis sentinel configuration for importer
hashgraph/hedera-mirror-node pull request #1204
Opened 2020-10-30 15:11 UTC by xin-hedera

**Detailed description**:
Add redis sentinel configuration for importer so importer will publish topic messages to the master node.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
By default, hedera-mirror charts configure redis chart to run in master-slave with sentinel enabled. However, hedera-mirror-importer charts configures importer to connect to the redis k8s service directly, which may route the topic messages to a read-only slave so all topic messages pubs are lost. The PR addresses the issue by configuring spring redis sentinel properties when needed. 

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-10-30 16:45 UTC, steven-sheehy requested changes

2020-10-30 16:45 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +      masterSet: mirror
I think we can probably hardcode this in the application.yaml to avoid having to populate the env variable.

2020-10-30 16:45 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +    enabled: false
I think we should default this to true so we don't have to turn it on in parent.

2020-10-30 16:45 UTC, steven-sheehy commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +            {{- if not .Values.redis.sentinel.enabled }}
I think it's safe to always set this variable, so can move sentinel enable check to be just around the sentinel variables. I believe it will construct the URI to sentinel only if the sentinel variables are populated.

2020-10-30 16:52 UTC, steven-sheehy commented
I'm guessing for gRPC API, it doesn't need to talk to sentinel because it can talk to any of the redis nodes via 6379 for read only data. I believe for a particular topic (and all subscribers on that topic) it opens a persistent connection to a random redis node. If the node it is talking to goes down, have you tested if the node it is subscribed to will automatically reconnect to another?

2020-11-02 16:10 UTC, xin-hedera commented on charts/hedera-mirror/values.yaml
> +      masterSet: mirror
unfortunately setting alone masterSet causes issue since spring expects sentinel nodes to be set if masterSet is set.

2020-11-02 16:18 UTC, xin-hedera commented
> I'm guessing for gRPC API, it doesn't need to talk to sentinel because it can talk to any of the redis nodes via 6379 for read only data. I believe for a particular topic (and all subscribers on that topic) it opens a persistent connection to a random redis node. If the node it is talking to goes down, have you tested if the node it is subscribed to will automatically reconnect to another?

The service cluster IP acts like a proxy and will switch over the redis subscription connection to a known good node behind the scene. When the switch happens fast enough that does not create a sequence number gap of topic messages, the gRPC service continues like nothing has happened. Otherwise, gRPC service will detect the gap, throw exception and disconnect all client subscriptions to the topic,  subsequent topic subscriptions from gRPC service will all go to known good redis node without any issue.

2020-11-02 16:19 UTC, xin-hedera commented on charts/hedera-mirror-importer/values.yaml
> +    enabled: false
updated

2020-11-02 16:19 UTC, xin-hedera commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +            {{- if not .Values.redis.sentinel.enabled }}
updated and tested

2020-11-02 16:41 UTC, steven-sheehy commented
> Otherwise, gRPC service will detect the gap, throw exception and disconnect all client subscriptions to the topic, subsequent topic subscriptions from gRPC service will all go to known good redis node without any issue.

It should be retried via the `retryWhen` in `RedisTopicListener`. If it's not, we should open a bug and fix it.

2020-11-02 16:49 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +      masterSet: mirror
True, looks like if any property is set it assumes sentinel. There's no enabled flag or check if nodes empty.

2020-11-02 16:56 UTC, steven-sheehy approved these changes

2020-11-02 18:35 UTC, merged