Cache current address book
hashgraph/hedera-mirror-node pull request #1226
Opened 2020-11-03 23:34 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

Cache the current address book to improve downloader performance

- Cache the address book when retrieving, keyed by the entity id.
- Evict the cache entry when an update occurs.

**Which issue(s) this PR fixes**:
Fixes #996 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-04 17:02 UTC, Nana-EC requested changes

2020-11-04 17:13 UTC, steven-sheehy requested changes

2020-11-04 17:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AddressBookRepository.java
> +    @Cacheable(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
I think we're caching at the wrong layer here. We should not cache the repository but the service layer as caching here can cause problems with `AddressBookServiceImpl.updatePreviousAddressBook()`.

2020-11-04 17:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
>      public AddressBook getCurrent() {
`@Cacheable` should be here.

2020-11-04 17:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
>          } catch (Exception e) {
I believe it was a mistake for us to have this catch here.
The result is an error parsing a valid address book would be caught and we wouldn't retry the whole file.
Can you remove this catch all together.
There shouldn't be any fallout in this minor refactor but let me know if you hit a snag as you address comments that makes it a bigger ask

2020-11-04 20:10 UTC, steven-sheehy requested changes

2020-11-04 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            "#root.target.ADDRESS_BOOK_102_ENTITY_ID.getId()")
Since we're effectively evicting all entries in the cache (one 102 file), we can just do the following and avoid the reflection penalty of using Spel expressions:

```java
@CacheEvict(allEntries = true)
```

2020-11-04 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
Use `@CacheConfig(cacheNames = "current_102_address_book", cacheManager = "cacheManager5m")` at the class level to stay DRY.

2020-11-04 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    public static final String ADDRESS_BOOK_CACHE_NAME = "address_book";
Since there's current and historical and 101 and 102 address books, we should name this to indicate it's only storing the current 102 address book. e.g.  something like`current_102_address_book`

2020-11-04 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @Cacheable(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
Can drop the cacheNames, cacheManager and key with my above recommendations.

2020-11-04 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AddressBookRepositoryTest.java
> +    CacheManager cacheManager;
Undo

2020-11-04 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AddressBookRepository.java
> +
Undo

2020-11-04 20:35 UTC, xin-hedera requested changes

2020-11-04 20:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
the cached address book is built from file 102, here `update()` may be passed either file 101 or 102, so an update from file 101 will unnecessarily evict the cache

2020-11-04 20:36 UTC, xin-hedera commented
should we cache the address book at the repository layer instead of the service layer?

2020-11-04 20:40 UTC, steven-sheehy commented
> should we cache the address book at the repository layer instead of the service layer?

I had a comment to the opposite. It only makes sense at the service layer. The address book service needs uncached repository methods in order to look up the latest address book.

2020-11-04 20:41 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @Cacheable(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
That logic makes sense, I've knocked it down to the 5m manager.

2020-11-04 20:41 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            "#root.target.ADDRESS_BOOK_102_ENTITY_ID.getId()")
Done

2020-11-04 20:42 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
Done

2020-11-04 20:42 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    public static final String ADDRESS_BOOK_CACHE_NAME = "address_book";
Done

2020-11-04 20:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @Cacheable(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
I've removed the cacheNames and cacheManager, letting it use the default key gen is causing issues with my unit test to retrieve it, I'm looking into how to fix that.

2020-11-04 20:44 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AddressBookRepositoryTest.java
> +    CacheManager cacheManager;
Done

2020-11-04 20:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AddressBookRepository.java
> +
Done

2020-11-04 20:48 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
This has been changed to evict the entire cache.
I think 102 is still going to get altered in this case, the updatePreviousAddressBook() method looks for the previous 102 address book and updates it.

2020-11-04 20:49 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    CacheManager cacheManager;
This was removed since the annotation can just be used, but you are correct that this should have been done.

2020-11-04 20:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
>          } catch (Exception e) {
Removed, all seems well with the tests

2020-11-04 20:52 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AddressBookRepository.java
> +            "#encodedFileId", unless = "#result == null")
This was refactored to work on the service layer which changed with the key params, but good point.

2020-11-04 20:54 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void cacheAddressBook() {
Perhaps this test needs to be renamed to `cacheAndEvictAddressBook`, it does do an eviction and confirms that it was removed from the cache.

2020-11-04 21:33 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            "#root.target.ADDRESS_BOOK_102_ENTITY_ID.getId()")
I am slightly concerned that the cache evict annotation, coupled with the removal of the top level catch as suggested by Nana, causes any exception that bubbles up to not evict the cache, as this fires at the resolution of the method.

2020-11-04 21:35 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            cacheManager.getCache(AddressBookRepository.ADDRESS_BOOK_CACHE_NAME)
After refactoring, the evict cache is called at the resolution of the method via an annotation.  That being said, it will not execute if an exception is thrown, I'm trying to evaluate if that is the best way to go or if it needs to switch back to something that fires regardless.

2020-11-04 21:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
gotcha!

2020-11-04 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
You're correct, except that I think that logic is actually a bug. We shouldn't hardcode 102 in updatePreviousAddressBook()

2020-11-04 23:12 UTC, steven-sheehy approved these changes
LGTM

2020-11-04 23:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    @CacheEvict(cacheNames = ADDRESS_BOOK_CACHE_NAME, cacheManager = NEVER_EXPIRE_LARGE, key =
Nana opened https://github.com/hashgraph/hedera-mirror-node/issues/1229

2020-11-04 23:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            cacheManager.getCache(AddressBookRepository.ADDRESS_BOOK_CACHE_NAME)
At 5mins it's probably not a big deal, though if your research shows otherwise you can add it in a follow up PR.

2020-11-04 23:27 UTC, Nana-EC approved these changes
LGTM.

2020-11-05 00:46 UTC, xin-hedera approved these changes
LGTM

2020-11-05 00:50 UTC, merged