Ensure entities are inserted only on create
hashgraph/hedera-mirror-node pull request #1228
Opened 2020-11-04 22:51 UTC by Nana-EC

**Detailed description**:
Currently mirror node will create entities that don't exist even on failed transactions.
We should create entities only on the 5 create transactions and accounts in the record transfer list

- Add `createsEntity()` to transactionHandler interface
- Update crypto account.contract.file/topic/file create handlers to returns true with `createsEntity()`
- Update `EntityRecordItemListener` to create entities only when `transactionHandler.createsEntity()` is true
- Rearrange `EntityRecordItemListener.onItem()` inner calls to be easier to fall and move calls that should be only done on success into if successful statement 

**Which issue(s) this PR fixes**:
Partially addresses #1201

**Special notes for your reviewer**:
This prevents further issues but lacks migration logic, which will be added in a future PR.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-11-05 16:19 UTC, steven-sheehy commented
> We should create entities only on the 5 create transactions and accounts in the record transfer list

I don't agree with the premise of this PR. We should create on all transaction types since we can have creates occur before OA and updates after.

2020-11-05 22:39 UTC, Nana-EC commented
> > We should create entities only on the 5 create transactions and accounts in the record transfer list
> 
> I don't agree with the premise of this PR. We should create on all transaction types since we can have creates occur before OA and updates after.
> 
> Unless we get serious about backfilling entities for mainnet and ensure that all entities that were created pre-OA exist and are correct (as some customers have asked us to do).

Reverted. The createsEntity() transaction handler logic can be used when we cross the bridge of backfilling.

2020-11-06 17:30 UTC, ijungmann submitted a review, later dismissed
LGTM

2020-11-06 18:41 UTC, steven-sheehy requested changes

2020-11-06 18:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                () -> assertEquals(3, entityRepository.count()), // payer, node, treasury
Curious: Why did this previously not include the file entity and be a count of 4?

2020-11-06 18:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                , () -> assertEquals(3, entityRepository.count()) // payer, node, treasury
Why wasn't this previously 4? We should probably look into changing these count asserts into a dedicated method that is more explicit and passes the expected EntityIds. Maybe add the method and put it in a few spots and we can later refactor the other places.
```java
void assertEntities(EntityId... entityIds) {...}
```

2020-11-06 21:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        tx.setType(transactionType);
Previous approach has transaction build logic dispersed, therefore making it harder to follow and maintain.
Aim here was to move all transaction build logic into the buildTransaction method.
True better to just pass RecordItem. My gut had performance concerns but it think we explored that already and it turned out to not be an issue.
Will update this to take in RecordItem

2020-11-06 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        tx.setEntityId(entityId);
Realized this after, might explain some of the issues with the tests.
With the update of `buildTransaction()`  to take RecordItem I can keep the logic in and add the success check for entity creation

2020-11-06 22:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        tx.setEntityId(entityId);
Actually I'm planning on changing `buildTransaction` to `insertTransaction`.
It conforms with the other transaction specific methods as it will be responsible fo rebuilding the object based on recordItem details and calling the `entityListener.onX()` method

2020-11-07 02:58 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                () -> assertEquals(3, entityRepository.count()), // payer, node, treasury
This seems to be a bug and missed coverage on our end.
We don't have logic to pick up the fileID as we presume it to be already created based on network logic.
I'll open a ticket to address this missing coverage

2020-11-07 02:59 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                , () -> assertEquals(3, entityRepository.count()) // payer, node, treasury
Good suggestion, I've implemented it and taken the time to updated these EntityRecordItemListener classes with it so tests are more clear

2020-11-07 03:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        tx.setEntityId(entityId);
Will move this to a separate PR with OnItem refactoring improvements and revert a few of these improvements as they're out of scope

2020-11-07 03:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        tx.setType(transactionType);
Reverted logic and will move out to a separate PR

2020-11-07 03:12 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                () -> assertEquals(3, entityRepository.count()), // payer, node, treasury
Opened #1237

2020-11-09 16:01 UTC, ijungmann approved these changes

2020-11-09 16:31 UTC, steven-sheehy approved these changes

2020-11-09 16:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        assertEquals(entityIds.length, entityRepository.count());
nit: This is a bit inefficient to count and then find each individually. A better approach would be to just `entityRepository.findAll()` then compare the list size and compare it against the expected in memory.

2020-11-09 16:59 UTC, merged

2020-11-09 19:35 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        assertEquals(entityIds.length, entityRepository.count());
Addressing in #1235