Add version migrations to fix entity type mismatches in db
hashgraph/hedera-mirror-node pull request #1235
Opened 2020-11-06 21:44 UTC by Nana-EC

**Detailed description**:
Currently mirror node will create entities that don't exist even on failed transactions.
We should create entities only on the 5 create transactions and accounts in the record transfer list

- Add sql migration v1.31.0 that backups t_entities table and removes all entities above max entity id observed by transactions table
- Add java migration that pulls in subset of a joined table of t_entities with transaction create rows. Check for type mismatch. If found update entity object and update entity row in db
- Add migration test class to verify migration cases
- Updated EntityTypeEnum class with method to retrieve enum given entity type int
- Add FlywayMigrationProperties class that contains configurable values used by java migrations

**Which issue(s) this PR fixes**:
Fixes #1201 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-11-10 20:23 UTC, ijungmann requested changes
Looks good, I like the tests.  Just some really minor things and a couple questions.

2020-11-10 20:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    private final String CREATED_ENTITIES_TRANSACTION_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
Nit: I'm wondering if the variable name could be enhanced a little, I had to read the SQL to really understand the sentiment but I'm failing to come up with something better.

2020-11-10 20:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        return expectedEntityType.getId();
Nit: not sure how you feel about ternary operators, but this method could be replaced with one I believe.
```suggestion
        return expectedEntityType.getId() == currentEntityType ? 0 :  expectedEntityType.getId();
```

2020-11-10 20:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                .get() + 1, flywayMigrationProperties.getEntityMismatchReadPageSize());
I understand incrementing the entity id cap by 1, I'm not sure I understand incrementing the timestamp cap though, if the cap is already set to the current time.

2020-11-10 20:23 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java
> +    void verifyEntityTypeMigrationInValidEntitiesMultiBatch() throws Exception {
Nit:
```suggestion
    void verifyEntityTypeMigrationInvalidEntitiesMultiBatch() throws Exception {
```

2020-11-10 20:23 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java
> +        entityRepository.insertEntityId(entityId(100, EntityTypeEnum.TOPIC));
I'm a little confused on not checking these last two in any of the invalid tests.  I'm sure it's a use case I'm just not understanding.

2020-11-10 21:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                .get() + 1, flywayMigrationProperties.getEntityMismatchReadPageSize());
True, +1 on timestamp is not needed

2020-11-10 21:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        return expectedEntityType.getId();
I like ternary operators and prefer your suggestion. Thanks

2020-11-10 21:12 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java
> +        entityRepository.insertEntityId(entityId(100, EntityTypeEnum.TOPIC));
Left over, will remove.
Originally, these two are added to make it so the max entities in the table isn't actually a valid entity.
I can actually take it out because by this migration any entities above the max valid entityId would have been delete in v1_31_1

Also originally I was going to do the delete after this migration.

Will remove thanks

2020-11-10 21:21 UTC, steven-sheehy requested changes
Some initial feedback, still working through it. Please also ensure the SonarCloud scan shows no bugs and no new code smells.

2020-11-10 21:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql
> +delete from t_entities where id > (select max(entity_id) from transaction where entity_id is not null);
I'm not convinced this is correct. I believe we should be deleting anything above the max for only successful transaction results. Below results for mainnet indicate everything above 58743 should be deleted:
```
select max(entity_id) as max, result from transaction where entity_id is not null group by result order by result asc;
  max   | result
--------+--------
  45009 |      4
  56708 |      7
  51273 |     10
  45009 |     11
  40319 |     15
  58743 |     22
  24586 |     30
  54356 |     33
  22922 |     34
  55762 |     68
  35316 |     72
  40790 |     78
    112 |    105
  15602 |    106
  40941 |    111
 211228 |    150
  40127 |    158
(17 rows)
```

2020-11-10 21:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                stopwatch.elapsed(TimeUnit.SECONDS), entityTransactionCount
Don't need to hardcode to seconds, can just log.info("{}", stopwatch) and it will automatically use the biggest duration unit.

2020-11-10 21:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        Long accountMismatchCount = getMismatchCount(TransactionTypeEnum.CRYPTOCREATEACCOUNT
Each of these is a full table scan since it doesn't use indexes. You can just do a single query with a group by. You can then use having to remove rows equal to zero and have a single throw statement.

2020-11-10 21:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    private void verifyNoEntityMismatchesExist() throws MigrationSQLException {
Why do we need to confirm no entity mismatch unless the database migration has a bug? If it there is a bug in the migration do we really want to block/fail the deployment? We haven't done this in any previous migration

2020-11-10 22:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityTypeEnum.java
> +    public static EntityTypeEnum fromId(int id) {
Initially it was, seems in my refactors I no longer needed it. Will remove

2020-11-10 22:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    private final EntityRepository entityRepository;
Left over, removed

2020-11-10 22:48 UTC, xin-hedera requested changes

2020-11-10 22:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                        ps.setLong(1, entityIdType.correctedEntityTypeId);
```suggestion
                        ps.setInt(1, entityIdType.correctedEntityTypeId);
```

2020-11-10 22:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        private final long transactionType;
```suggestion
        private final int correctedEntityTypeId;
        private final long entityId;
        private final int initialEntityTypeId;
        private final int transactionType;
```

2020-11-10 22:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +            "limit ?";
nit: order by consensus_ns desc is redundant since there won't be duplicate entity IDs in those successful create transactions

2020-11-10 22:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                        timestampCap.set(entityIdType.consensusTimestamp);
these are already updated in `getTypeMismatchedEntity` and it's also possible updating them here would cause some rows to be reprocessed.

2020-11-10 22:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    private void verifyNoEntityMismatchesExist() throws MigrationSQLException {
In migrations where info is deleted/updated I think if there's a way to verify the final state is as expected we should utilize it.
If it's not we certainly should fail and prioritize accuracy, no?

2020-11-11 00:01 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql
> +delete from t_entities where id > (select max(entity_id) from transaction where entity_id is not null);
Yep, good catch. Should be 
```suggestion
delete from t_entities where id > (select max(entity_id) from transaction where entity_id is not null and result = 22);
```

2020-11-11 00:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    @Transactional
Removed

2020-11-11 00:17 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        jdbcTemplate.execute(DROP_TEMP_ENTITIES_SQL);
Will removed, had toyed with the idea of leaving temp table around for a while, then deciding on dropping.
Given migration logic and verification I can remove temp table need.

2020-11-11 00:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        private final long transactionType;
Updating, only the timestamp needs to be long

2020-11-11 01:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +            "limit ?";
the order by is to ensure that the search is done in desc order to support the batching of search

2020-11-11 15:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +            "limit ?";
I got that part, I meant only order by id desc is needed for the reason I provided in the initial comment.

2020-11-11 16:23 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java
> +    void verifyEntityTypeMigrationInValidEntities() throws Exception {
Renamed

2020-11-11 16:23 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java
> +    void verifyEntityTypeMigrationInValidEntitiesMultiBatch() throws Exception {
Renamed

2020-11-11 16:24 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        entitiesIterableAssert
Continued chaining. Intellisense error was misleading but since I didn't need the return chaining works fine.

2020-11-11 16:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +            " on (e.id = t.entity_id and t.result = 22 and t.type = ? and e.fk_entity_type_id <> ?)";
Moved out into where.
Also created a separate where string for easier reading.

2020-11-11 16:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        jdbcTemplate = new JdbcTemplate(dataSource);
Injected `JdbcOperations`

2020-11-11 16:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    private Long getMismatchCount(@Nullable Object... args) {
Removed

2020-11-11 16:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql
> +delete from t_entities where id > (select max(entity_id) from transaction where entity_id is not null);
Updated

2020-11-11 16:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                stopwatch.elapsed(TimeUnit.SECONDS), entityTransactionCount
Updated

2020-11-11 16:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +        Long accountMismatchCount = getMismatchCount(TransactionTypeEnum.CRYPTOCREATEACCOUNT
Adopted single query. With group by letting me log  clearly each entity type that has mismatches whiles till having a single throw for if it's at all above 0

2020-11-11 16:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                        ps.setLong(1, entityIdType.correctedEntityTypeId);
Updated

2020-11-11 16:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +            "limit ?";
Sure, I guess that inherently works because entity id are created in asc id value over time.

2020-11-11 16:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +                        timestampCap.set(entityIdType.consensusTimestamp);
Left over, single update occurs in `getTypeMismatchedEntity()` now

2020-11-11 17:02 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +    private final String CREATED_ENTITIES_TRANSACTION_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
Much better, thanks

2020-11-11 17:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java
> +            "limit ?";
Updated

2020-11-11 17:31 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java
> +        entityRepository.insertEntityId(entityId(100, EntityTypeEnum.TOPIC));
Cool, makes sense, thanks for the details.

2020-11-11 18:08 UTC, ijungmann requested changes
Couple minor things, otherwise looks good.

2020-11-11 18:08 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "t.consensus_ns < ? and t.result = 22 and t.type in (8,11,17,24,29) order by id desc " +
Is there a reason to do the granular type mismatch checks (`(t.type = 8 and e.fk_entity_type_id <> 2)`, etc) in the count SQL but not here?

2020-11-11 19:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "t.consensus_ns < ? and t.result = 22 and t.type in (8,11,17,24,29) order by id desc " +
Yeah, had wanted to share that logic, but if you do that and combine with paging logic on the search the result is that you don't know when you've hit the end.
It's difficult to reliably differentiate between not finding a a mismatch in the last batch search vs there's no more rows left to actually search.
I didn't want to get down to relying on static id or time stamp numbers to determine this as it could be wrong. 
So decided to leave it as is.
Upside is we're ensured to consider every single entity that was said to have been created.

2020-11-11 19:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            return new TypeMismatchSearchResult();
Happy to remove the @NoArgs on the class and be explicit here w the following
```suggestion
            return new TypeMismatchSearchResult(null, false);
```

2020-11-11 19:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "t.consensus_ns < ? and t.result = 22 and t.type in (8,11,17,24,29) order by id desc " +
That makes sense, I'm okay with it then

2020-11-11 19:39 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            return new TypeMismatchSearchResult();
I'd prefer that.

2020-11-11 20:37 UTC, steven-sheehy requested changes
With the change requested to use DB Cursor, this whole Java Migration could really just be simplified to a CTE with an update. This is way easier to understand, maintain and is a lot more efficient to execute.

pseudo-sql:
```sql
with mismatch as (
  select e.fk_entity_type_id, e.id from 
  t_entities e join transaction t on e.id = t.entity_id where 
  t.result = 22 and ((t.type = 11 and 
  e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and 
  e.fk_entity_type_id <> 3) or (t.type = 24 and e.fk_entity_type_id <> 4) or (t.type = 29 and 
  e.fk_entity_type_id <> 5))
)
update t_entities set fk_entity_type_id = mismatch.fk_entity_type_id where id = mismatch.id
```

The test that verifies this scenario can still be used with such a sql.

2020-11-11 20:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
Why are we limiting to these certain types here and in the search SQL? It should be all transaction types that are associated with one of the entity types. For example, a CONSENSUSUPDATETOPIC can certainly return an INVALID_TOPIC_ID.

2020-11-11 20:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    private static final String ENTITY_TYPE_MISMATCH_WHERE_CLAUSE = "t.result = 22 and ((t.type = 11 and " +
If we later add new transaction types but someone runs this migration after that point, it would miss those types. Perhaps we should auto-generate this SQL from the enums? Also, it would be less brittle and hard to understand.

That is, add an optional `EntityTypeEnum` field to `TransactionTypeEnum` that groups transactions types per which entity they are associated with. Then generate the SQL using that info.

2020-11-11 20:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    private static final String ENTITY_TYPE_MISMATCH_SEARCH_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
We should use a DB cursor instead of using this complicated keyset pagination approach with stateful Atomics. The updating can be batched but the querying should not be. 

Besides being harder to understand and making the class stateful, this query will be slower since it's joining an un-indexed field. Keyset pagination only makes sense when using index fields. I ran this query in mainnet and a single page took a few minutes.

This would also allow you to reuse the sql that compares the entity type with the transaction type. It would also make the verification query completely unnecessary as it's the same SQL.

2020-11-11 20:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
True, but the additional transactions types aren't necessary to determine if an entity type is mismatched. 
Every entity noted by a successful transaction create type should have a mapping in the t_entities table.
That's all you need to determine and correct the t_entities table.
Updated and deletes etc will all follow a create transaction, so it's sufficient to look at that.

2020-11-11 21:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
Post offline discussion the tricky part here is the backfill problem. With missing historic data we can't rely on only create transactions as they may not be present.
I see the need for all transactions, which can make the list exhaustive and sql long but will look into that

2020-11-11 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    private static final String ENTITY_TYPE_MISMATCH_WHERE_CLAUSE = "t.result = 22 and ((t.type = 11 and " +
Good point. Such a mapping is useful.
Especially given the exhaustive transactions type discussed.
Will look into this.

2020-11-11 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    private static final String ENTITY_TYPE_MISMATCH_SEARCH_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
Agreed, will look into this.

2020-11-12 05:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            return new TypeMismatchSearchResult();
Made the change but then blew this whole class away in the end.

2020-11-12 05:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    public int[][] batchUpdate(List<TypeMismatchedEntity> typeMismatchedEntities) {
N/A, class removed.

2020-11-12 05:34 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Entity_Type_MismatchTest.java
> +@TestPropertySource(properties = "spring.flyway.target=1.31.1")
Is this still applicable. Should be okay now with the modification to 
```
@TestPropertySource(properties = "spring.flyway.target=1.31.0")
```

2020-11-12 05:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
Went for an exclusive set. in CTE update I ignore system, unknown and freeze transaction - basically those that don't relate to an entity.
This way future entities added can be picked up.

Also update the transaction_types table with the corresponding entity_type

2020-11-12 05:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    private static final String ENTITY_TYPE_MISMATCH_WHERE_CLAUSE = "t.result = 22 and ((t.type = 11 and " +
Mapping now in db as noted

2020-11-12 05:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java
> +    private static final String ENTITY_TYPE_MISMATCH_SEARCH_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
Cursor was a good idea.
With CTE update no longer needed as this class is gone

2020-11-12 19:22 UTC, steven-sheehy reviewed
LGTM. Just need to change the migration number

2020-11-12 19:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Entity_Type_MismatchTest.java
> +class V_1_31_2__Entity_Type_MismatchTest extends IntegrationTest {
This class name no longer matches the sql name

2020-11-12 20:33 UTC, steven-sheehy approved these changes
LGTM. Please also update the PR description with the changes before merging.

2020-11-12 20:34 UTC, ijungmann approved these changes

2020-11-12 21:21 UTC, xin-hedera approved these changes
LGTM

2020-11-12 21:26 UTC, merged