Add monitor charts
hashgraph/hedera-mirror-node pull request #1251
Opened 2020-11-09 21:25 UTC by xin-hedera

**Detailed description**:

- Add helm charts for monitor
- Add monitor to hedera-mirror charts and update values
- Add monitor to docker-compose.yaml

**Which issue(s) this PR fixes**:
Fixes #1216 

**Special notes for your reviewer**:
dashboard for monitor will be addressed in a future ticket.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-09 21:54 UTC, steven-sheehy requested changes

2020-11-09 21:54 UTC, steven-sheehy commented on docker-compose.yml
> +  monitor:
Maybe we should disable this by default since we want to make it easy for people to get up and running without requiring any config? Or can we set replicas=0 to effectively disable?

2020-11-09 21:54 UTC, steven-sheehy commented on charts/hedera-mirror-monitor/values.yaml
> +  initialDelaySeconds: 100
Can you test if we can lower this? It should start up much quicker than grpc which requires redis and postgresql.

2020-11-09 21:54 UTC, steven-sheehy commented on charts/hedera-mirror-monitor/values.yaml
> +  initialDelaySeconds: 100
Can you test if we can lower this? It should start up much quicker than grpc which requires redis and postgresql.

2020-11-09 22:09 UTC, xin-hedera commented on charts/hedera-mirror-monitor/values.yaml
> +  initialDelaySeconds: 100
I don't have the time for gRPC, but this is the number for monitor:

```
2020-11-09 21:05:34,976 INFO  [main ] c.h.m.m.MonitorApplication Started MonitorApplication in 103.402 seconds (JVM running for 117.219)
```

The startup is really slow. If we want to cut the initial delay, we have to either look at why it's slow or increase the cpu limit of the container.

2020-11-09 22:10 UTC, steven-sheehy commented on charts/hedera-mirror-monitor/values.yaml
> +  initialDelaySeconds: 100
Ok, let's leave it as is. Just wanted to make sure these values were accurate and sounds like they are.

2020-11-10 00:30 UTC, Nana-EC requested changes
Should also update charts README.md with overview and instructions on usage

2020-11-10 00:30 UTC, Nana-EC commented on docker-compose.yml
> +  monitor:
replicas=0 is my vote

2020-11-10 01:55 UTC, xin-hedera commented on docker-compose.yml
> +  monitor:
replicas defaults to 0 in deployment.yaml when replicas is not set in values

2020-11-10 02:50 UTC, steven-sheehy commented on docker-compose.yml
> +  monitor:
Eh? I was referring to the docker-compose file. The rule is the docker compose should be runnable as is without any config.

Please undo deployment change.

2020-11-10 04:36 UTC, steven-sheehy commented on charts/hedera-mirror-monitor/templates/deployment.yaml
> +  {{- if .Values.replicas }}
This if/else can be removed. Only reason it's there for gRPC is because it has an HPA and the HPA manages the value of the replicas field.

2020-11-10 15:05 UTC, xin-hedera commented on charts/hedera-mirror-monitor/templates/deployment.yaml
> +  {{- if .Values.replicas }}
sure

2020-11-10 17:12 UTC, steven-sheehy approved these changes
LGTM

2020-11-10 17:23 UTC, ijungmann approved these changes

2020-11-10 18:37 UTC, Nana-EC approved these changes
LGTM

2020-11-10 18:41 UTC, merged