Refactor importer to handle token transfers in crypto transfer
hashgraph/hedera-mirror-node pull request #1254
Opened 2020-11-10 16:22 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:
As a result of [hedera-services 718](https://github.com/hashgraph/hedera-services/pull/718), token transfers no longer exist as their own transaction, and instead are handled in crypto transfers.  These code changes will allow the mirror node to consume token transfers in the new format.

**Which issue(s) this PR fixes**:
Fixes #1176 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-12 00:32 UTC, ijungmann commented
There's an issue with the new protobuf version, the parent pom was not pushed and is causing the build to fail.  I've reached out and the problem is being worked on.  Everything else should be ready to review.

2020-11-12 06:05 UTC, Nana-EC requested changes

2020-11-12 06:05 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
>      {account: tokenTransfer.treasuryAccountId, amount: NETWORK_FEE},
Shouldn't we move the addTokenTransferTransaction() logic into addCryptoTransaction()?

addCryptoTransaction() does a check for 'transfers' so the equivalent would be a check for `tokenTransfers`.

The result would be the json setup would no longer use the tokenTransfers[] and both crypto and token transfers would be under cryptoTransfers[].

Unless I'm missing something as is a single crypto transfer with both crypto and token transfer would end up getting represented as 2 transactions instead of 1.

```
const addCryptoTransaction = async (cryptoTransfer) => {
  if (!('senderAccountId' in cryptoTransfer)) {
    cryptoTransfer.senderAccountId = cryptoTransfer.payerAccountId;
  }

  if (!('transfers' in cryptoTransfer)) {
    cryptoTransfer.transfers = [
      {account: cryptoTransfer.senderAccountId, amount: -NETWORK_FEE - cryptoTransfer.amount},
      {account: cryptoTransfer.recipientAccountId, amount: cryptoTransfer.amount},
      {account: cryptoTransfer.treasuryAccountId, amount: NETWORK_FEE},
    ];
  }
  if (!('tokenTransfers' in cryptoTransfer)) {
    cryptoTransfer.tokenTransfer = [
    {account: tokenTransfer.payerAccountId, amount: -NETWORK_FEE - NODE_FEE},
    {account: tokenTransfer.treasuryAccountId, amount: NETWORK_FEE},
    {account: tokenTransfer.nodeAccountId, amount: NODE_FEE},
    ];
  }
  await addTransaction(cryptoTransfer);
};
```
You'd also have to updated `addTransaction()`
What do you think?

2020-11-12 18:52 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
>      {account: tokenTransfer.treasuryAccountId, amount: NETWORK_FEE},
Yeah, I agree, my first go was basically to minimally affect the tests, but to be fully accurate with the new logic they should be together.  I'll do some refactoring to make that happen.

2020-11-12 20:04 UTC, steven-sheehy commented on pom.xml
> +        <hedera-protobuf.version>0.9.0-alpha.6</hedera-protobuf.version>
Should this be 0.9.0-rc.2?

2020-11-12 21:32 UTC, ijungmann commented on pom.xml
> +        <hedera-protobuf.version>0.9.0-alpha.6</hedera-protobuf.version>
Yep, just updated it.

2020-11-12 21:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/V1.32.0__delete_token_transfers_transaction_type.sql
> +-- delete token transfers transaction type
Renamed to V1.31.3 after you and Xin got yours in.

2020-11-13 00:47 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
>      {account: tokenTransfer.treasuryAccountId, amount: NETWORK_FEE},
I've reworked the setup a fair amount, effectively the addCryptoTransaction already allowed one to add token information, so I ripped out all of the tokenTransfers logic, changed the tests around to make the tokenTransfers merge into the cryptoTransfers, and then reworked the addCryptoTransfer logic to default a couple things that weren't being specified in the tokenTransfers (alternatively, I could just force the tests to have recipientIds and amounts specified).

2020-11-13 17:59 UTC, Nana-EC requested changes
Looks good, minor stuff and then I guess you're waiting on the protobuf compile version fix to get around the circleCI failures

2020-11-13 17:59 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    console.log(row);
remove left over console  log

2020-11-13 17:59 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +         ON t.type = 14
nit. We should have done this previously but could you make this a constant 
`const cryptoTransferTransactionType =14` and use here and below
```suggestion
         ON t.type = ${cryptoTransferTransactionType}
```

2020-11-13 20:36 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    console.log(row);
Removed

2020-11-13 20:38 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +         ON t.type = 14
Took it one step further and used the `const transactionTypes` in `constants.js` since it was already being pulled in.

2020-11-16 03:16 UTC, ijungmann commented
The new protobuf artifact that fixed the target jdk issue also brought with it the breaking changes for expiry, autoRenewal, and tokenID.  Since the fixes for that issue don't require too many code changes, I've added the changes for that issue into this review.

2020-11-16 15:29 UTC, steven-sheehy requested changes

2020-11-16 15:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenUpdateTransactionBody.getExpiry().getSeconds());
Wrong time unit. Use `Utility.timestampInNanosMax()`

2020-11-16 15:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenCreateTransactionBody.getExpiry().getSeconds());
Wrong time unit. Use `Utility.timestampInNanosMax()`

2020-11-16 15:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenUpdateTransactionBody.getExpiry().getSeconds());
Fixed.

2020-11-16 15:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenCreateTransactionBody.getExpiry().getSeconds());
Fixed.

2020-11-16 16:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenCreateTransactionBody.getExpiry().getSeconds());
Wrong method

2020-11-16 16:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenCreateTransactionBody.getExpiry().getSeconds());
Whoops, yep, `timestampInNanosMax` now, fixed.

2020-11-16 16:02 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
> +            entity.setExpiryTimeNs(tokenUpdateTransactionBody.getExpiry().getSeconds());
Whoops, yep, `timestampInNanosMax` now, fixed.

2020-11-16 16:03 UTC, steven-sheehy approved these changes
LGTM

2020-11-16 16:46 UTC, Nana-EC approved these changes
LGTM

2020-11-16 16:53 UTC, merged