Fix state proof check failure on failed transaction check
hashgraph/hedera-mirror-node pull request #1259
Opened 2020-11-12 17:04 UTC by xin-hedera

**Detailed description**:

- Search a non-duplicate failed transaction to check that stateproof API returns 404
- Add config option failedTransactionLimit to limit the number of failed transactions to look for a non-duplicate
 
**Which issue(s) this PR fixes**:
Fixes #1257 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-12 19:33 UTC, steven-sheehy requested changes
I think this check (and the not exist check) is unlike the other checks in that it is a negative test instead of a positive test. I think negative checks are probably more appropriate for unit/functional tests and might not belong in a monitor. 

I think to solve this issue we can just remove these two calls from the monitor.

2020-11-12 19:33 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/stateproof_tests.js
> +  let url = getUrl(server, transactionsPath, {limit: failedTransactionLimit, order: 'desc', result: 'fail'});
It doesn't look like any of these query params are applicable to `/transactions/:transaction_id`.

2020-11-12 19:33 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/README.md
> +- set `failedTransactionLimit` for `stateproof` to limit the number of failed transactions to search for a non
This seems like a hack. When we have more than limit nodes in the future someone might submit to all and this fail again.

2020-11-13 20:37 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/stateproof_tests.js
> +  let url = getUrl(server, transactionsPath, {limit: failedTransactionLimit, order: 'desc', result: 'fail'});
transactionsPath is just `/transactions`, without `/:transactionId`

2020-11-13 20:42 UTC, ijungmann approved these changes
LGTM

2020-11-13 20:55 UTC, steven-sheehy approved these changes

2020-11-13 22:01 UTC, merged