Bump sdk and update token and crypto transfer transactions
hashgraph/hedera-mirror-node pull request #1260
Opened 2020-11-12 17:31 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:
The new sdk version has deprecated CryptoTransferTransaction and TokenTransferTransaction to reflect the new protobuf changes.

- Bump sdk version to 1.3.2
- Update performance tests, acceptance tests, and transaction suppliers to use the TransferTransaction.

**Which issue(s) this PR fixes**:
Fixes #1176 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-12 18:55 UTC, Nana-EC approved these changes
LGTM.

2020-11-12 19:42 UTC, steven-sheehy requested changes

2020-11-12 19:42 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenTransferTransactionSupplier.java
> +public class TokenTransferTransactionSupplier implements TransactionSupplier<TransferTransaction> {
I think each class should map one to one with a HAPI service. So we should remove this class and its entry in `TransactionType`. Then make it an option (off by default) to add token transfers to the cryptotransfer supplier

2020-11-12 22:23 UTC, Nana-EC requested changes
Missed it in my first review but `TokenFeature.verifyTokenTransfers()` needs to be updated.
From 
```
assertThat(mirrorTransaction.getName()).isEqualTo("CRYPTOTRANSFER");
```
to
```java
assertThat(mirrorTransaction.getName()).isEqualTo("TOKENTRANSFERS");
```

2020-11-13 06:42 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenTransferTransactionSupplier.java
> +public class TokenTransferTransactionSupplier implements TransactionSupplier<TransferTransaction> {
Makes sense.  I've removed it and added an optional tokenId to append a token transfer to the `CryptoTransferTransactionSupplier`

2020-11-13 06:48 UTC, ijungmann commented
> Missed it in my first review but `TokenFeature.verifyTokenTransfers()` needs to be updated.
> From
> 
> ```
> assertThat(mirrorTransaction.getName()).isEqualTo("CRYPTOTRANSFER");
> ```
> 
> to
> 
> ```java
> assertThat(mirrorTransaction.getName()).isEqualTo("TOKENTRANSFERS");
> ```

Backwards, right?  This is fixed now

2020-11-13 15:32 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2020-11-13 16:03 UTC, Nana-EC commented
> > Missed it in my first review but `TokenFeature.verifyTokenTransfers()` needs to be updated.
> > From
> > ```
> > assertThat(mirrorTransaction.getName()).isEqualTo("CRYPTOTRANSFER");
> > ```
> > 
> > 
> > to
> > ```java
> > assertThat(mirrorTransaction.getName()).isEqualTo("TOKENTRANSFERS");
> > ```
> 
> Backwards, right? This is fixed now

Yep you got it right.
I think this may still remain broken until your other PR goes in, but this is the right change here.

2020-11-13 16:03 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-11-13 20:25 UTC, xin-hedera submitted a review, later dismissed
LGTM

2020-11-16 17:06 UTC, ijungmann commented
Had to update the pom after merging #1254, no actual changes since last review.

2020-11-16 17:10 UTC, steven-sheehy approved these changes

2020-11-16 17:23 UTC, merged