gRPC service perfermance optimization
hashgraph/hedera-mirror-node pull request #1277
Opened 2020-11-17 16:42 UTC by xin-hedera

**Detailed description**:

- Reimplement timeout mechanism with less impact on normal data path
- Move publishOn from before backpressure buffer to after Flux.merge, ~40% lower CPU usage in high-concurrency high-tps scenario
- Reduce flux operation chaining depth when possible
- Make prefetch for Flux.merge and publishOn configurable and set default to 48 based on benchmark result
- Fix issue that TopicMessage.toResponse does not properly cache the protobuf response
- Increase grpc container cpu and memory limit
- Update integration test
- 
**Which issue(s) this PR fixes**:
Fixes #1227 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-11-17 20:24 UTC, ijungmann submitted a review, later dismissed
LGTM

2020-11-17 20:57 UTC, steven-sheehy requested changes

2020-11-17 20:57 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +        return Flux.merge(listenerProperties.getPrefetch(), topicMessageFlux, timeoutMono)
This is quite a complicated solution for not much gain in functionality. Why do we even care about letting them consume the buffer after they overflow? There's no recovery logic here so we should just fail fast and let the client retry.

2020-11-17 20:57 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
>                  .onBackpressureBuffer(listenerProperties.getMaxBufferSize())
Assuming we keep the timeout logic, have you considered using `onBackpressureBuffer(int maxSize, Consumer<?> onOverflow)` and use the consumer to trigger the wait before error?

2020-11-17 22:02 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +                .doOnCancel(timeoutContext::onCancel)
sure, I'll add some appropriate comment

2020-11-17 22:05 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +        return response.updateAndGet(response -> {
yes you are right, thought `AtomicReference.updateAndGet` performs locking.

2020-11-17 22:05 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +        return unknownError(t);
sure, will update it

2020-11-17 22:05 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +        } else if (t instanceof IllegalArgumentException) {
sure

2020-11-17 22:07 UTC, xin-hedera commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
> +        for (int i = 0; i < 10000; ++i) {
the time cost is roughly the same, around 1 sec, since I also bumped the tps for the two scenarios to 7500.0 and 2500.0

2020-11-17 22:08 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +        return response.updateAndGet(response -> {
It doesn't lock, it just does a compare and set in a loop

2020-11-17 22:12 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +        return Flux.merge(listenerProperties.getPrefetch(), topicMessageFlux, timeoutMono)
it's for the case that the topic TPS is high, the client is slow and can't catch up, since the backpressure buffer is big, letting the client consume the remaining data then terminating it with either the OverflowException or the ClientTimeoutException would end in a rate higher than 500 the client can get by retry.

2020-11-17 22:21 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +        return Flux.merge(listenerProperties.getPrefetch(), topicMessageFlux, timeoutMono)
Regardless if we have a buffer timeout or not, the client has to retry right? They can't keep up and the TPS is high. All we're doing is delaying it slightly and give them a little bit higher TPS on the first run but then still slow on the retry anyway. I don't think an extra 2s window provides any value.

2020-11-19 01:42 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
> +        for (int i = 0; i < 10000; ++i) {
Got it

2020-11-19 15:55 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
>                  .onBackpressureBuffer(listenerProperties.getMaxBufferSize())
yes this simplifies the logic, thanks

2020-11-19 16:36 UTC, steven-sheehy requested changes

2020-11-19 16:36 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +    @Setter(value = AccessLevel.NONE)
Why do we need this on a `@Value` object which has no setters by default?

2020-11-19 16:36 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +                taskDisposer = scheduler.schedule(() -> sink.error(new ClientTimeoutException(
As discussed offline, I think we can remove the buffer timeout and just fail fast. This will simplify the logic.

2020-11-19 16:54 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +        } else if (t instanceof StatusRuntimeException) {
yes, will remove it

2020-11-19 16:56 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +    @Setter(value = AccessLevel.NONE)
the `response` is created lazily by a private method, disable the setter can prevent accidental value change.

2020-11-19 16:56 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
> +                taskDisposer = scheduler.schedule(() -> sink.error(new ClientTimeoutException(
removed, now will fail fast

2020-11-19 17:01 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +    private StatusRuntimeException mapError(Throwable t) {
change return type to `StatusRuntimeException`

2020-11-19 17:07 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +    @Setter(value = AccessLevel.NONE)
I tested this locally just to confirm. There is no setter with or without the annotation because this is a `@Value` class.

2020-11-19 17:11 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +        } else if (t instanceof StatusRuntimeException) {
have to revert it, since `toFilter` which is called at the previous step may throw `StatusRuntimeException`. removing the above code causes test failure

2020-11-19 17:11 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +    @Setter(value = AccessLevel.NONE)
thanks, will remove it then

2020-11-19 18:44 UTC, steven-sheehy approved these changes
LGTM. Please update the PR description before merge since the logic has changed.

2020-11-19 19:52 UTC, merged