Oas doc
hashgraph/hedera-mirror-node pull request #1278
Opened 2020-11-17 21:21 UTC by Nana-EC

**Detailed description**:
Add an Open API spec to the REST API module that can be used for documentation and easier integration with other services

- Add the `express-oas-generator` to create the `openapi.json` and `openapi_v3.json` spec files for V2 and V3 support
- Add the `swagger-ui-express` package to serve the oas file
- Add `hedera.mirror.rest.oasGenerator` to contain configuration properties for the spec generation
- Add support for serving docs for both V2 and V3 
- Update `operations.md` with instructions on viewing and updating the spec file

**Which issue(s) this PR fixes**:
Fixes #306 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-11-18 16:19 UTC, steven-sheehy requested changes
Haven't reviewed the actual spec yet

2020-11-18 16:19 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.rest.oasGenerator.swaggerUIPath`          | '/api-spec'             | Swagger UI path for your REST API                                                                  |
Would prefer Swagger UI at `/api/v1/docs` and spec at `/api/v1/openapi.yaml` or `/api/v1/docs/openapi.yaml`.

2020-11-18 16:19 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +        level: debug
Some extra spaces at end of these two lines

2020-11-18 16:19 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const oasGenerator = require('./oasGenerator');
oasGenerator isn't an ext library

2020-11-18 16:30 UTC, Nana-EC commented on hedera-mirror-rest/oas/v1/openapi.json
> +  "swagger": "2.0",
My understanding is we wanted to support other services that may consume the spec. Not everyone may have migrated yet so this is just a nice to have.
The doc is auto generated also so there's little management overhead.
I can remove it though if we feel there's no value

2020-11-18 16:34 UTC, Nana-EC commented on docs/operations.md
> +- `http://<ip>:<port>/<swaggerUIPath>/v3` - Explicit Open API v3 doc serve location
The doc is actually served at `/api/v1`, I just missed it here, will update.
In the other comment you noted not integrating the generation and just starting from the doc. 
In that case I can  just convert it to yaml and save it

2020-11-18 16:41 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.rest.oasGenerator.swaggerUIPath`          | '/api-spec'             | Swagger UI path for your REST API                                                                  |
'/api-spec' and `api-docs` seemed to be the conventions I'd come across, but we can make our endpoint `docs`.
Should be fine since it's documented

2020-11-18 16:43 UTC, steven-sheehy commented on hedera-mirror-rest/oas/v1/openapi.json
> +  "swagger": "2.0",
I think 3.5+ years is enough time to migrate. It is management overheard if we have to maintain both documents for "API first" development, as noted.

2020-11-18 16:54 UTC, Nana-EC commented on docs/operations.md
> +To update the spec, we utilize the [express-oas-generator](https://github.com/mpashkovskiy/express-oas-generator) package to automatically generate the spec files based off of express routes.
Can do. Will remove the Update Spec section and also pretty much remove the `oasGenerator.js` code since it won't be reused

2020-11-18 16:55 UTC, Nana-EC commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const oasGenerator = require('./oasGenerator');
Will rearrange

2020-11-18 18:11 UTC, ijungmann requested changes
Looks good, just some little nits from me.

2020-11-18 18:11 UTC, ijungmann commented on hedera-mirror-rest/middleware/oasGenerator.js
> + * This must be called after al express middlerwares
Nit, I think:
```suggestion
 * This must be called after all express middlewares
```

2020-11-18 18:11 UTC, ijungmann commented on hedera-mirror-rest/middleware/oasGenerator.js
> + * This must be the first express middle ware called to ensure all responses and url query params are caught
```suggestion
 * This must be the first express middleware called to ensure all responses and url query params are caught
```

2020-11-19 03:09 UTC, Nana-EC commented on hedera-mirror-rest/oas/v1/openapi.json
> +  "swagger": "2.0",
Sounds good

2020-11-19 03:13 UTC, Nana-EC commented on docs/operations.md
> +To update the spec, we utilize the [express-oas-generator](https://github.com/mpashkovskiy/express-oas-generator) package to automatically generate the spec files based off of express routes.
create a replacement `oasHandler.js` file that carries out serving the has specs

2020-11-19 03:14 UTC, Nana-EC commented on docs/operations.md
> +- `http://<ip>:<port>/<swaggerUIPath>/v3` - Explicit Open API v3 doc serve location
Updated the actual doc to be able to hold links to other future versions.
Verified with a fictitious v2 with different endpoints.
All you'd need to do is updated the path

2020-11-19 03:15 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.rest.oasGenerator.swaggerUIPath`          | '/api-spec'             | Swagger UI path for your REST API                                                                  |
Updated as discussed

2020-11-19 03:15 UTC, Nana-EC commented on hedera-mirror-rest/config/application.yml
> +        level: debug
Removed spaces

2020-11-19 03:17 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.rest.oasGenerator.alwaysServeDocs`        | true                    | Whether to always serve the aos doc. Used when you don't want to apply middelwares but still serve existing api-
Ended up removing config

2020-11-19 03:18 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.rest.oasGenerator.specFilePath`           | '/oas/v1/openapi'       | The path to a oas file and file name, if missing module won't write spec to the disc
Update comments no longer has that

2020-11-19 16:33 UTC, steven-sheehy requested changes
In general, the spec needs a lot of work to fill it out with proper descriptions, validation, etc. I only reviewed one operation within it but the same sort of comments apply to all. We can consider doing this in a follow up but it's not something we should wait too long for and forget.

2020-11-19 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - name: "account.id"
Think each query parameter should have a description. You can copy the description from the REST API docs.

2020-11-19 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: "/api/v1/tokens/{id}/balances"
Should we provide an operationId for all operations? Seems like it helps tooling.

2020-11-19 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: "string"
Should set order parameters default value and a pattern or enum to restrict values.

2020-11-19 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: "integer"
Should mention parameter's default value, minimum and max values

2020-11-19 16:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: "array"
Should have a pattern to validate

2020-11-19 18:14 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  version: "0.23.0-rc1"
Yeah we should. Or it can be removed if we don't want the overhead

2020-11-19 18:15 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.rest.oas.swaggerUIPath`                   | '/doc'                  | Swagger UI path for your REST API                                                                  |
Should be /docs

2020-11-19 18:17 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - "balances"
Not true, it also includes the `/api/v1/tokens<tokenId>/balances`

2020-11-19 18:20 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: "/api/v1/tokens/{id}/balances"
Yeah that would be useful, I can add that.

2020-11-19 18:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - "balances"
Yes, but I think the tag is a way to group the top level operations e.g. `/api/v1/*`. Putting balances here also groups it with the top level `/api/v1/balances`, which I'm not sure is what we want.

2020-11-19 18:53 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +serveOASSwaggerUI(app, apiPrefix);
Had fixed locally, will push on next commit

2020-11-19 18:59 UTC, Nana-EC commented on hedera-mirror-rest/middleware/oasHandler.js
> +  return `api/${apiVersionPath}/${config.oas.specFileName}.yml`;
Lol at Organization of American States showing up and not Open API Specification

Notably, I actually preferred `api/ `folder.
Reasoning being, one of our tentative changes is a restructuring of the folder structure and the usage of express routes.
In which case one way to arrange it is with an `/api/v1` folder and if a future v2 comes along `/api/v2` for routes.
In those cases it would be nice to have the openapi.yml file right under the root version folder along with the route code files.

Let me know if you feel strongly and we can have the separate `openapi/v1` folder structure

2020-11-19 19:11 UTC, Nana-EC commented on docs/operations.md
> +- `http://<ip>:<port>/<metricsPath>/ui` - Metrics dashboard
Unfortunately can't hardcode the `ui` part.
Reason being the package actually adds the `/ui`, '/ux', '/stats` and `/metrics` paths.
See https://swaggerstats.io/guide/conf.html#options

If you did you hardcode `ui` it would read `/swagger/ui/ui` and `swagger/ui/metrics` etc.
Notably, I did try hardcoding `swagger/ui` and it causes a fail on startup

2020-11-19 19:20 UTC, Nana-EC commented on docs/operations.md
> +- `/api/v1/doc` - API v1 doc serve path
Will simplify

2020-11-19 19:32 UTC, Nana-EC commented on hedera-mirror-rest/middleware/oasHandler.js
> +  return `api/${apiVersionPath}/${config.oas.specFileName}.yml`;
Will update the `oas` naming under config to `openapi`

2020-11-19 19:52 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  title: "hedera-mirror-rest"
Will update

2020-11-19 19:54 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  description: "Available Versions: [v1](/api/v1/doc). Base url: [/api/v1](/api/v1)\n\nHedera Mirror Node REST API"
Yeah autogeneration. Base url is probably also not needed since you'd need knowledge of it to get here anyway.

2020-11-19 19:58 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  - url: "http://127.0.0.1:5551/api/v1"
Goo suggestion. Will add previewnet and mainnnet also

2020-11-19 20:21 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  - name: "accounts"
Yes, had planned for a later PR but might as well knock this one out here since it's documentation only.

2020-11-19 20:24 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: "/api/v1/tokens/{id}/balances"
Autogenerated, will fill in

2020-11-19 21:59 UTC, steven-sheehy commented on docs/operations.md
> +- `http://<ip>:<port>/<metricsPath>/ui` - Metrics dashboard
Think there's some miscommunication here. I'm suggesting to remove variables when showing URL paths. Whatever the full URL path is, when showing it show it with the defaults and without a `http://<ip>:<port>/` prefix. Then after mention that which parts can be customized via which variables.

2020-11-19 22:00 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/oasHandler.js
> +  return `api/${apiVersionPath}/${config.oas.specFileName}.yml`;
Ok, am fine with `/api` if it serves some future purpose with routes.

2020-11-19 23:45 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - name: "account.id"
Can do

2020-11-20 17:20 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - "balances"
You're right. It does make `/api/v1/tokens<tokenId>/balances` show up in both balances and tokens group.
Which I think is valid but probably cleaner to leave it basic for now

2020-11-20 20:52 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  version: "0.23.0-rc1"
Updated replacer to cover this. matching conflicts with places where we replace the chart version but I got it

2020-11-20 20:53 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  - url: "http://127.0.0.1:5551/api/v1"
Added current and production options

2020-11-20 20:53 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  - name: "accounts"
Added description swell as external docs link. Links don't seem to be showing up but something to look into later

2020-11-20 20:55 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: "/api/v1/tokens/{id}/balances"
Went for a basic summary based on what a few other sites had. Seems like focusing and working it around get/list and returns was the focus.
We can add greater detail in description property if we want in the future but Hedera docs has that for now

2020-11-20 20:55 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: "string"
Set, and moved into schema

2020-11-20 20:55 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: "integer"
Updated

2020-11-20 20:57 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: "array"
Went off your suggestion and utilized a regex pattern to match since openapi can't handle our custom ':' separator as is.
One bug seems to be the ui css gets messed up but that can be an item we open against `swagger-ui-express`

2020-11-20 22:04 UTC, steven-sheehy approved these changes
LGTM. I didn't review the individual operations in too much detail, but what I saw looked good. Will look at when we do the full validation ticket.

2020-11-20 22:04 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        format: ^(\d{1,10}.\d{1,10}.\d{1,10}|gte?:\d{1,10}.\d{1,10}.\d{1,10}|lte?:\d{1,10}.\d{1,10}.\d{1,10}|eq:\d{1,10}.\d{1,10}.\d{1,10}|ne:\d{1,10}.\d{1,10}.\d{1,10})$
Inefficient regex. Can clean it up in a follow up. `^((gte?|lte?|eq|ne)\:)?(\d{1,10}\.\d{1,10}\.)?\d{1,10}$`

2020-11-20 22:05 UTC, ijungmann submitted a review, later dismissed

2020-11-20 22:28 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        format: ^(\d{1,10}.\d{1,10}.\d{1,10}|gte?:\d{1,10}.\d{1,10}.\d{1,10}|lte?:\d{1,10}.\d{1,10}.\d{1,10}|eq:\d{1,10}.\d{1,10}.\d{1,10}|ne:\d{1,10}.\d{1,10}.\d{1,10})$
Was gonna circle back to improve it but happy to take this now.

2020-11-20 22:28 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        format: ^(\d{1,10}|gte?\:\d{1,10}|lte?:\d{1,10}|eq:\d{1,10}|ne:\d{1,10})$
Adopted

2020-11-20 22:38 UTC, steven-sheehy approved these changes

2020-11-20 22:46 UTC, merged