Enable log alerts and normalize log statements
hashgraph/hedera-mirror-node pull request #1279
Opened 2020-11-18 00:09 UTC by steven-sheehy

**Detailed description**:
- Add log alerts using Loki's `PrometheusRule` compatible [alerting](https://grafana.com/docs/loki/latest/alerting/#alerting)
- Add log alerts that match our equivalent alerts in Google Cloud
- Increase Loki storage to 100GiB since it ran out of space in the cluster
- Change Java stacktraces to log as a single line for better compatibility with Loki and Grafana
- Change logging layout to remove unnecessary spacing and square brackets to make it easier for Loki to parse
- Change gRPC and REST APIs to log client errors at warning level and to not print stacktraces
- Change log statements to log at the appropriate level
- Fix Downloader repeatedly logging stacktraces for download race conditions
- Fix `ImporterBalanceParseLatency` alert triggering too often
- Fix kubelet alerts triggering by disabling them
- Fix migration test failing occasionally due to lock issue
- Fix monitor container not starting due to liveness probe
- Bump all chart dependencies

**Which issue(s) this PR fixes**:
Fixes #1218 

**Special notes for your reviewer**:
Note that the log alerts can probably be cleaned up quite a bit but I chose to keep them mostly the same with what we have for now

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-18 22:08 UTC, Nana-EC requested changes

2020-11-18 22:28 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +            != "reactor.core.publisher"
See the note in the description:

> Note that the log alerts can probably be cleaned up quite a bit but I chose to keep them mostly the same with what we have for now

I didn't create these alerts, they are existing and are what we notify off of in production. I'm not even sure how most of these ended up here as they're not logs that we explicitly print. So the argument of brittleness is still there with the existing approach but at least now they'll be checked in with the source code and versioned.

> Is it possible to apply an exception type filter here instead or in addition to some of these?

I'm not sure what you mean. These are error level logs so they're usually the result of an exception already.

I think one of the problems with the existing alerts is that it didn't parse out the log level and java stacktraces are multi-line. So stacktraces might count multiple times towards the log metric for what is actually the same log statement. Hence why some of these strings might not be needed anymore since they might've been an element within the stacktrace.

2020-11-18 22:38 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +        alertmanager_url: http://{{ .Release.Name }}-prometheus-alertmanager:9093
It's the default port within the alertmanager chart. It does have a value within that chart but child values are not available within parent charts. So I'd have to redefine it here and then reference that redefinition.

Technically the `prometheus-alertmanager` part is also customizable. At some point you can't account for every customization and have to assume defaults. Didn't think it's worth the effort.

2020-11-19 03:26 UTC, Nana-EC commented on charts/hedera-mirror-common/values.yaml
> +        alertmanager_url: http://{{ .Release.Name }}-prometheus-alertmanager:9093
That's fine

2020-11-19 03:27 UTC, Nana-EC commented on charts/hedera-mirror-common/values.yaml
> +            != "reactor.core.publisher"
Understood.
Looks like we can do some more customization as needed in the future.

2020-11-19 03:27 UTC, Nana-EC approved these changes
LGTM

2020-11-19 16:09 UTC, ijungmann approved these changes
LGTM

2020-11-19 23:32 UTC, Nana-EC approved these changes
LGTM

2020-11-19 23:35 UTC, merged