Support Default Credentials Provider for AWS
hashgraph/hedera-mirror-node pull request #1281
Opened 2020-11-20 06:09 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:
By utilizing the [AWS Default Credentials Provider Chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html), the mirror node can allow for greater flexibility when it comes to configuring access to S3 buckets, and the chain will actually reduce the amount of code required to support the different configurations.

**Which issue(s) this PR fixes**:
Fixes #1044 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-11-24 19:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CredentialsProviderConfiguration.java
> +        //If the cloud provider is GCP, it must use the static provider.  If the static credentials are both present,
We could go one step further with this and have S3 users only use the Default Credentials Provider and never the static creds provider, it would make this a bit cleaner (if S3, use Default, if GCP use Static), the only caveat would be S3 users would be forced to set up their creds the AWS way and would break any existing users that use the old config.

2020-11-24 21:02 UTC, steven-sheehy requested changes

2020-11-24 21:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CredentialsProviderConfiguration.java
> +    private boolean useStaticCredentialsProvider() {
Keeping in mind encapsulation and to reduce verbosity of their implementation, these helpers might be more appropriate within `CommonDownloaderProperties` as `isStaticCredentials()` and `isAnonymousCredentials()`.

2020-11-24 23:52 UTC, ijungmann commented on docs/configuration.md
> -Importer can be configured to connect to S3 using temporary security credentials via AssumeRole.  This is only available
I've done it in Docker Compose using a volume in the importer that points to my local credentials: `~/.aws/:/root/.aws:ro`.  You could do something similar in Kubernetes with a secret, or you can directly enter the keys as secrets in Kubernetes (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY).  [I like this breakdown](https://github.com/hashgraph/hedera-mirror-node/issues/900).

There are also a host of other ways of doing it, [one of the comments](https://github.com/hashgraph/hedera-mirror-node/issues/900) on the last issue is using [this](https://github.com/aws/amazon-eks-pod-identity-webhook/) as they are running in AWS's Kubernetes solution.

I can add a little documentation for the simplest ways to get it running in Kubernetes and Docker (point to existing credentials file or directly add the keys as environment variables), beyond that it would probably be overkill.

2020-11-24 23:57 UTC, ijungmann commented on docs/configuration.md
> --   `hedera.mirror.importer.downloader.s3.externalId` (An external ID is an optional property attached to the role in AWS to make it more secure)
Removed from the table and the chart schema

2020-11-24 23:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CredentialsProviderConfiguration.java
> +        return StringUtils
Fixed.

2020-11-24 23:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CredentialsProviderConfiguration.java
>      public AwsCredentialsProvider staticCredentialsProvider() {
Renamed

2020-11-25 00:03 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> -        private String externalId;
That makes sense.  The two users I've spoken to/heard from mentioned the existing solution was not enough for what they were looking to do, so I'm hopeful that few are actually using these properties, but definitely need to get the word out.

2020-11-25 00:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CredentialsProviderConfiguration.java
> +    private boolean useStaticCredentialsProvider() {
Good call, moved and renamed

2020-11-25 00:31 UTC, ijungmann commented on docs/configuration.md
> -Importer can be configured to connect to S3 using temporary security credentials via AssumeRole.  This is only available
Added some basic documentation for some of the ways to set up Docker or Kubernetes.

2020-11-25 01:04 UTC, ijungmann commented
I believe the Helm test is failing because the monitor key and accountId are blank, I'm guessing that part of the test was off and is now on.

2020-11-25 02:56 UTC, steven-sheehy approved these changes
LGTM, just some nit picks.

2020-11-25 02:56 UTC, steven-sheehy commented on docs/configuration.md
> +If the mirror node is configured to connect to an S3 bucket that requires authenticaion, and the static credentails are not provided
`credentials`

2020-11-25 02:56 UTC, steven-sheehy commented on docs/configuration.md
> +      - ~/.aws/:/root/.aws:ro
Technically don't think this is valid yaml. Should be 2 spaces indentation.

2020-11-25 02:56 UTC, steven-sheehy commented on docs/configuration.md
> +keys in the config.  This will also allow you to take advantage of alternative authorization modes such as AssumeRole.
Should link keyword `AssumeRole` to assume role docs.

2020-11-30 16:48 UTC, ijungmann commented on docs/configuration.md
> +If the mirror node is configured to connect to an S3 bucket that requires authenticaion, and the static credentails are not provided
Fixed

2020-11-30 16:48 UTC, ijungmann commented on docs/configuration.md
> +      - ~/.aws/:/root/.aws:ro
Fixed

2020-11-30 16:48 UTC, ijungmann commented on docs/configuration.md
> +keys in the config.  This will also allow you to take advantage of alternative authorization modes such as AssumeRole.
Added

2020-11-30 16:50 UTC, xin-hedera submitted a review, later dismissed
LGTM

2020-11-30 17:00 UTC, Nana-EC approved these changes
LGTM

2020-11-30 17:14 UTC, merged