Improve gRPC missing message handling in TopicMessageService
hashgraph/hedera-mirror-node pull request #1282
Opened 2020-11-20 16:19 UTC by xin-hedera

**Detailed description**:

- Add unthrottled mode to topic retriever
- Use unthrottled mode to retrieve missing topic messages at full speed in TopicMessageServiceImpl
- Fix the issue in retriever when topic filter limit is multiple of max page size, more messages will be retrieved than the limit
- Update configuration.md
- Update tests

**Which issue(s) this PR fixes**:
Fixes #1221 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2020-11-20 21:31 UTC, steven-sheehy requested changes

2020-11-20 21:31 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.grpc.retriever.unthrottledMaxPageSize`       | 5000             | The maximum number of messages the retriever can return in a single call to the database when unthrottled |
This equals 250K TPS. Perhaps we should lower the limits a bit. Also, 5K might be a bit high for page size depending upon how large the messages are. At 6K message size a 5K poll would return 30MB+ of data. Perhaps we should keep max page size at 1000 and just increase polling frequency?

2020-11-20 21:31 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                numRepeats = retrieverProperties.getUnthrottledMaxPolls();
What happens when unthrottled max polls is reached but there are still messages? `PollingTopicMessageRetriever` will complete but will `TopicMessageServiceImpl` ever complete? Will it error? We should add a test if possible.

2020-11-20 21:36 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                numRepeats = Long.MAX_VALUE;
Should the throttled have a lower value than `Long.MAX_VALUE`
It's likely in the unthrottled cases the value would be less than that, especially with a default of 12

2020-11-20 21:40 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/RetrieverProperties.java
> +    @NotNull
sure

2020-11-20 21:40 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/RetrieverProperties.java
> +    private int unthrottledMaxPageSize = 5000;
will do

2020-11-20 21:42 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
yes. when tps is low, and the listener misses messages of multiple record files, one poll might get the missing messages of one record file from db, the number of messages might be less than the page size and still we need more polls to fill in the gap

2020-11-20 21:49 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                numRepeats = Long.MAX_VALUE;
when throttled, the repeats of `Long.MAX_VALUE` matches the old behavior.

the old behavior is, the retriever is used to obtain historical messages at a throttled speed, e.g., 500/s

- if there are enough historical messages in db, we should let it repeat forever
- if the polling ends up getting all historical messages in db, a query from the db would return less than max page size rows, the `context.isComplete()` will be true, and the whole repeat will stop & the flux completes, then in TopicMessageService, the flux moves on to `incomingMessages`

2020-11-20 21:54 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.grpc.retriever.unthrottledMaxPageSize`       | 5000             | The maximum number of messages the retriever can return in a single call to the database when unthrottled |
it depends on how fast the db is and how fast our whole flux pipeline is. 20ms is how long we wait after the previous flux sequence is drained, it will not get to 50 db queries when each or some of queries return a lot of data.

The numbers I saw were around 20k/s with importer ingesting at 10k tps.

2020-11-20 21:57 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                numRepeats = retrieverProperties.getUnthrottledMaxPolls();
`TopicMessageServiceImpl` will error with `IllegalStateException` "Encountered out of order messages". I'll add a test for this scenario.

2020-11-20 22:08 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                numRepeats = retrieverProperties.getUnthrottledMaxPolls();
I see, because we always have the current message which triggered the missing message flow and concat that, it should generate that error always. I think we do have a test for that already.

2020-11-20 22:16 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
I don't think that's true in practice as we use transactions to commit the entire record at once and we don't send to redis until that transaction is complete. So there should be an invariant that all messages before the message that triggers the missing messages flow are already in the database. But probably fine to keep this to be extra safe.

2020-11-20 22:38 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
umm, my understanding is we first publish all topic messages to the channel, then commit the db transaction.

SqlEntityListener:

https://github.com/hashgraph/hedera-mirror-node/blob/a7d4932eb9ea4621d184f40c095857f456e7a496/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java#L183-L199

RedisEntityListener:

https://github.com/hashgraph/hedera-mirror-node/blob/a7d4932eb9ea4621d184f40c095857f456e7a496/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java#L83-L92

2020-11-20 22:42 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
No, it's the exact opposite. Invoking `eventPublisher.publishEvent(new EntityBatchSaveEvent(this))` after persisting to db will directly call `RedisEntityListener.onSave()`.

2020-11-20 22:45 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
Also note that `SqlEntityListener` has `@Order(0)` on it, so it will be invoked before `@Order(3) RedisEntityListener` via the `CompositeEntityListener`

2020-11-20 23:03 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
my opinion is the transaction COMMIT happens after all messages are published to redis.

```
2020-11-20 22:58:45,754 INFO  [scheduling-3] c.h.m.i.p.r.e.s.SqlEntityListener Inserted 4 entities in 32.72 ms
2020-11-20 22:58:45,754 INFO  [scheduling-3] c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 40.80 ms
2020-11-20 22:58:45,778 INFO  [scheduling-3] c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 0 messages in 22.80 ms
2020-11-20 22:58:45,781 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Found thread-bound EntityManager [SessionImpl(2014749906<open>)] for JPA transaction
2020-11-20 22:58:45,781 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Participating in existing transaction
2020-11-20 22:58:45,784 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Found thread-bound EntityManager [SessionImpl(2014749906<open>)] for JPA transaction
2020-11-20 22:58:45,784 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Participating in existing transaction
Hibernate: 
    update
        t_application_status 
    set
        status_value=? 
    where
        status_code=?
2020-11-20 22:58:45,788 INFO  [scheduling-3] c.h.m.i.p.r.RecordFileParser Finished parsing 1 transactions from record file /var/lib/hedera-mirror-importer/recordstreams/valid/2019-10-11T13_35_39.807083001Z.rcd in 106ms (9/s). Success: true
2020-11-20 22:58:45,788 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Initiating transaction commit
2020-11-20 22:58:45,789 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Committing JPA transaction on EntityManager [SessionImpl(2014749906<open>)]
2020-11-20 22:58:45,794 DEBUG [scheduling-3] o.s.o.j.JpaTransactionManager Closing JPA EntityManager [SessionImpl(2014749906<open>)] after transaction```

2020-11-20 23:13 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                return pageSize.get() < retrieverProperties.getMaxPageSize() || limitHit;
True, I guess the commit doesn't occur until the outer wrapped `@Transactional` method completes.

2020-11-20 23:17 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
> +                numRepeats = Long.MAX_VALUE;
Yep, I realize the old behavior had this. Just noting that in a throttled case you might expect it to be less than the unthrottled case. That's fine though

2020-11-23 15:22 UTC, steven-sheehy requested changes

2020-11-23 15:22 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/RetrieverProperties.java
> +
`@NotNull`

2020-11-23 15:22 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/RetrieverProperties.java
> +        @DurationMin(millis = 10)
`@NotNull`

2020-11-23 18:54 UTC, steven-sheehy approved these changes

2020-11-23 19:18 UTC, merged