Add gRPC and REST subscriber to monitor
hashgraph/hedera-mirror-node pull request #1302
Opened 2020-11-30 17:54 UTC by steven-sheehy

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1217 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-11-30 21:06 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        return Base64.getEncoder().encodeToString(Longs.toByteArray(System.currentTimeMillis()));
Is this just to avoid creating the Instant object?

2020-12-01 04:56 UTC, Nana-EC requested changes
1st pass, left some suggestions

2020-12-01 04:56 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +        return Flux.<PublishRequest>generate(sink -> sink.next(transactionGenerator.next()))
nit: I think we should start to make it a practice of commenting on multi stage reactive flows.
They tend to be the places where order is important and where logic is swapped in and out.
So it would help for future management to be clear on the choices applied here.

2020-12-01 04:56 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/CompositeTransactionGenerator.java
> +            if (properties.isEnabled() && scenarioProperties.isEnabled()) {
This should be moved outside of the for loop and checked once right?
Since `properties` doesn't change per scenario and if `properties.isEnabled()` is false it doesn't matter whether the scenarios are enabled.

2020-12-01 15:13 UTC, ijungmann requested changes
Looks really good, just a couple things I spotted.

2020-12-01 15:13 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGeneratorTest.java
> +        properties.setRecord(100);
Same thing, is there a reason to set the record to the same value set in the `init?`

2020-12-01 16:23 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        if (decoded.length < Long.BYTES) {
Not quite, but there is a bug here that needs to be addressed. We base64 only the timestamp but decode the entire message which includes timestamp plus random text. Also, we create the message subtracting 8 bytes for the long, but when it's encoded to base64 it's much larger than 8 bytes so the resulting message is over the expected size.

Both acceptance and JMeter tests are also wrong and need to be fixed. JMeter tests incorrectly assume only the first 8 bytes are for the long but as mentioned it's a higher and variable length once base64 encoded. Acceptance tests I'm not sure how they're working at all as they assume the entire message is the timestamp despite publishing with other data in it:

```java
// Publish
byte[] byteArray = Longs.toByteArray(Instant.now().toEpochMilli());
String message = Base64.encodeBase64String(byteArray) + "_" + baseMessage + "_" + i + 1;
...
// Subscribe
Instant publishInstant = Instant.ofEpochMilli(Longs.fromByteArray(Base64.decodeBase64(mirrorConsensusTopicResponse.message)));
```

I will change monitor to not base64 the Long and just convert the Long and message to byte arrays and concat them.

2020-12-01 16:29 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +        return Flux.<PublishRequest>generate(sink -> sink.next(transactionGenerator.next()))
Sure, will add some javadocs

2020-12-01 16:32 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/CompositeTransactionGenerator.java
> +            if (properties.isEnabled() && scenarioProperties.isEnabled()) {
I had it like that but I later put it inside as it avoids an extra level of nesting and if statement and accomplishes the same thing. But I can move it back up if it eases your mind.

2020-12-01 16:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGeneratorTest.java
> +        properties.setReceipt(100);
No, just as a form of documentation when reading the test case in isolation.

2020-12-01 16:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGeneratorTest.java
> +        properties.setRecord(100);
No, just as a form of documentation when reading the test case in isolation.

2020-12-01 16:34 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        if (decoded.length < Long.BYTES) {
Yes, I do believe a few sprints back I made a change around this logic because of some encoding confusion.
I believe the SDK encodes the message also. So when subscribing we have to decode the whole message first.

Let me dig in and confirm.

2020-12-01 17:00 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        if (decoded.length < Long.BYTES) {
The publish and subscribe logic you pasted is correct/similar for both acceptance and performance.

In both cases only the first 8 bytes are read by Longs.fromByteArray() so the rest of the message doesn't really matter and the accuracy of the publish instant being retrieved isn't impacted. Are you seeing cases where this is not the case and publish times are wrong?

The base64 encoding was added to ensure preservation of data during transport. I believe when the byte array had negative numbers the size of the data was getting modified during transport with the sdk and resulting incorrect Instant values when converted.

2020-12-01 17:01 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        if (decoded.length < Long.BYTES) {
I don't think it's a bug (unless you're seeing bad times) so much as an opportunity to improve the efficiency of the logic.
I'm okay with byte array concatenation so far as it works. The point was for the subscribe codes in all our tests to work regardless of where the transactions were published from. Service load testing/ mirror acceptance/performance tests - they should all work.

Try a few runs after your change and check for error cases where erroneous Instants times are created on the subscribe time e.g. EPOCH/max or a time in the future. 
That was the original bug seen that prompted the base64 encoding

2020-12-01 17:16 UTC, xin-hedera requested changes

2020-12-01 17:16 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +        mirrorConsensusTopicQuery.setLimit(Math.min(0, subscriberProperties.getLimit() - counter.get()));
`subscriberProperties.getLimit() - counter.get()` can be negative when `subscriberProperties.getLimit()` is 0 and counter is not 0

limit should be set 0 if `getLimit()` is 0; otherwise it should be set to `getLimit() - counter.get()`

2020-12-01 17:16 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +                endTime = startTime.plus(duration);
endTime should stay the same when it's calculated based on duration; it should not be the current startTime + duration when retrying

2020-12-01 18:02 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        return Longs.fromByteArray(timestampBytes);
That shouldn't be possible since I check if `bytes.length < Long.BYTES` and return right above this.

2020-12-01 18:05 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +        rateLimiter.acquire();
It's intended. The `RateLimiter`'s first acquire always occurs instantaneously since it doesn't have anything to compare against. Discarding that first acquire makes the numbers more accurate but more importantly fixes the issue with setting `Double.MIN_NORMAL` for TPS to never generate a message like I do for inactive scenarios in `CompositeTransactionGenerator`.

2020-12-01 18:07 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +                endTime = startTime.plus(duration);
Correct, which is why I store the `endTime` from the previous run so this code is never reached on retry.

2020-12-01 18:11 UTC, xin-hedera commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        return Longs.fromByteArray(timestampBytes);
yes.

I meant If we catch the exception, we don't need to check the length & copy the buffer before calling `Longs.fromByteArray`

2020-12-01 18:19 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +        rateLimiter.acquire();
I see.

Not related to the conversation above, I do think we need a single global rate limiter instead of one per scenario.

One rate limiter per scenario can cause spikes of transactions. For example, there are two enabled scenarios of 25.0 tps (A) and 75.0 tps (B), the extreme case is for a group of 100 transactions, the distribution is the first 25 are all for A so it takes the whole second and leaves the next 75 for B generated back to back in one shot.

A single global rate limiter will make the transactions evenly spaced time wise.

2020-12-01 18:21 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +        mirrorConsensusTopicQuery.setLimit(Math.min(0, subscriberProperties.getLimit() - counter.get()));
That's why I added the extra call to `java.lang.Math`. Unfortunately I put `Math.min()` and I meant `Math.max()`. Will correct.

2020-12-01 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        return Longs.fromByteArray(timestampBytes);
I'd still have to check if null as `Longs.fromByteArray` doesn't. But in general, it's better to use a conditional as it's an order of magnitude more performant than exception handling, especially during performance testing.

2020-12-01 19:32 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +            return (count % 100) <= percent;
Will change

2020-12-02 22:15 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/TransactionSupplierException.java
> +    public TransactionSupplierException(String message) {
This class was removed as a result of removing the manual bean validation.  Unless we need it back for some other reason.

2020-12-02 22:18 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +     */
Thank you, I think this will really help going forward.

2020-12-02 22:20 UTC, ijungmann submitted a review, later dismissed
LGTM so far

2020-12-03 00:03 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/TransactionSupplierException.java
> +    public TransactionSupplierException(String message) {
Yep, removed.

2020-12-03 15:05 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        if (decoded.length < Long.BYTES) {
Discussed offline. This logic has been changed from base64 to raw bytes and above is no longer applicable.

2020-12-03 15:05 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +        rateLimiter.acquire();
We can consider it in the future once proven via testing

2020-12-03 16:44 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private boolean retry = false;
Should this be marked final if the intent is to make the transaction non-retryable?

2020-12-03 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private boolean retry = false;
If it was final I could just remove the variable and hardcode it. The intent is to make retries configurable. Later we might be able to do this generically for all transaction types in which case we can make this a publisher property.

2020-12-03 16:50 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private boolean retry = false;
That makes sense, just in this instance it being used in a `NonRetryableConsensusMessageSubmitTransaction` implies it would never be configured otherwise.

2020-12-03 17:37 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private boolean retry = false;
Naming things is hard. Counter suggestion?

2020-12-03 17:42 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private boolean retry = false;
Hardest part of coding.  Maybe `RetryConfigurableConsensusMessageSubmitTransaction`?

2020-12-03 18:07 UTC, Nana-EC reviewed
Looks good, some nits, will go over one more time since it's on the longer side.

2020-12-03 18:12 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private boolean retry = false;
Updated

2020-12-03 18:14 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    @Min(8)
Sure, I can add `@Max(6144)` but it won't be truly accurate since 6K is the max including the signatures and other metadata.

2020-12-03 18:14 UTC, ijungmann submitted a review, later dismissed
LGTM

2020-12-03 18:17 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HederaNetwork.java
> +                new NodeProperties("0.0.6", "3.testnet.hedera.com"),
I don't see how that can be done easily. I think the OTHER should suffice for these scenarios.

2020-12-03 18:17 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +        long latency = System.currentTimeMillis() - timestamp;
Will move

2020-12-03 18:35 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HederaNetwork.java
> +                new NodeProperties("0.0.6", "3.testnet.hedera.com"),
Works for me

2020-12-03 19:59 UTC, Nana-EC approved these changes
LGTM

2020-12-03 20:33 UTC, xin-hedera approved these changes
LGTM

2020-12-03 20:34 UTC, merged