Correct Transaction Suppliers having default values overwritten, and add validation
hashgraph/hedera-mirror-node pull request #1304
Opened 2020-12-01 22:52 UTC by ijungmann

**Detailed description**:
The Transaction Suppliers are not being created correctly by the monitor because they are created through the ObjectMapper, which does not make use of the Lombok builder.  This causes the class-defined default values to be overwritten by the primitive default values.  Because these two do not seem to work well together, we are removing the Builder logic from the Transaction Suppliers.  In addition, we are adding validation logic to the monitor so we can detect these issues quicker.

- Remove Lombok `@Builder` support from Transaction Suppliers and add getters/setters to all fields
-  Add validation logic to the monitor and validation annotations to the Transaction Suppliers

**Which issue(s) this PR fixes**:
Fixes #1303

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-01 23:14 UTC, steven-sheehy requested changes

2020-12-01 23:14 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
>      //Required
I think you can remove the Required/Optional comments now and re-sort the required fields into the optional fields. It should be self documenting what's required from the validation annotations

2020-12-01 23:14 UTC, steven-sheehy commented on hedera-mirror-monitor/pom.xml
> +            <artifactId>javax.el-api</artifactId>
You shouldn't need this dependency, just the org.glassfish:javax.el.

2020-12-01 23:14 UTC, steven-sheehy commented on hedera-mirror-monitor/pom.xml
> +            <version>3.0.0</version>
Move to property

2020-12-01 23:14 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
>      private static final List<String> requiredFields = Arrays.asList("accountId");
Should remove this and the manual validation checks.

2020-12-01 23:14 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
> +    private String publicKey;
nit: Would look more consistent if two newlines between all fields.

2020-12-01 23:16 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
> +    private Duration autoRenewPeriod = Duration.ofSeconds(8000000);
Use `@DurationMin/Max` as well for this and other duration fields

2020-12-01 23:21 UTC, ijungmann commented on hedera-mirror-monitor/pom.xml
> +            <version>3.0.0</version>
Should that stay in this pom, or move to the parent pom in case we want to add this elsewhere?

2020-12-01 23:25 UTC, steven-sheehy commented on hedera-mirror-monitor/pom.xml
> +            <version>3.0.0</version>
Only move things to parent pom when it impacts more than one pom.xml

2020-12-02 00:03 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
> +    private String publicKey;
Sure, two newlines everywhere now

2020-12-02 00:03 UTC, ijungmann commented on hedera-mirror-monitor/pom.xml
> +            <artifactId>javax.el-api</artifactId>
Removed

2020-12-02 00:03 UTC, ijungmann commented on hedera-mirror-monitor/pom.xml
> +            <version>3.0.0</version>
Makes sense, moved it into a property now.

2020-12-02 00:08 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
>      private static final List<String> requiredFields = Arrays.asList("accountId");
Removed

2020-12-02 00:14 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
>      private static final List<String> requiredFields = Arrays.asList("accountId");
Is the `TransactionSupplierException` in use anywhere now?

2020-12-02 00:18 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
>      //Required
Removed and re-sorted

2020-12-02 00:46 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
> +    private Duration autoRenewPeriod = Duration.ofSeconds(8000000);
Added `@DurationMin` for all Durations, as well as `@Future` for all Instants

2020-12-02 00:47 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
>      private static final List<String> requiredFields = Arrays.asList("accountId");
Nope, just removed it.

2020-12-02 03:12 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-12-02 04:09 UTC, steven-sheehy requested changes

2020-12-02 04:09 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private String tokenId;
Later, not part of this PR, we can consider creating a custom annotation and validator for these ID fields. Either that or use a wrapper object to validate.

2020-12-02 04:09 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusUpdateTopicTransactionSupplier.java
> +    @DurationMin(seconds = 1)
You need to keep `@NotNull` as `@DurationMin` still allows null.

2020-12-02 04:09 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusUpdateTopicTransactionSupplier.java
> +    @Future
Same for `@Future`

2020-12-02 04:34 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private String tokenId;
I actually started looking into that and decided to hold off for now, but I like the idea.

2020-12-02 04:37 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusUpdateTopicTransactionSupplier.java
> +    @DurationMin(seconds = 1)
Ah, did not see that, corrected now.

2020-12-02 04:37 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusUpdateTopicTransactionSupplier.java
> +    @Future
Corrected

2020-12-02 04:48 UTC, steven-sheehy approved these changes
LGTM

2020-12-02 14:52 UTC, merged