Add retry configuration support to HTS acceptance tests
hashgraph/hedera-mirror-node pull request #1305
Opened 2020-12-02 03:02 UTC by Nana-EC

**Detailed description**:
- Add retry configuration support to HTS REST calls
- Simplify acceptance nd performance publish time write and reads for latency calculations

**Which issue(s) this PR fixes**:
Fixes #1294 
**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-02 18:59 UTC, xin-hedera requested changes

2020-12-02 18:59 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TopicClient.java
> +            byte[] suffixByteArray = ("_" + baseMessage + "_" + i + 1).getBytes();
```suggestion
            byte[] suffixByteArray = ("_" + baseMessage + "_" + (i + 1)).getBytes();
```

I think this is what you want.

2020-12-02 20:05 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TopicClient.java
> +            byte[] suffixByteArray = ("_" + baseMessage + "_" + i + 1).getBytes();
Updated

2020-12-02 20:21 UTC, steven-sheehy requested changes

2020-12-02 21:33 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/TopicMessagePublishRequest.java
> +            new SecureRandom().nextBytes(randomAlphanumeric);
I am caching it so it's created once.
Didn't want the weight of creating each time at high TPS tests

2020-12-02 21:51 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            maxAttemptsExpression = "#{@acceptanceTestProperties.restPollRetries}")
I had thought so too but when I tried it I always got
```
java.lang.IllegalArgumentException: Could not resolve placeholder 'hedera.mirror.test.acceptance.restPollRetries' in value "#{${hedera.mirror.test.acceptance.restPollRetries}}"
```

The current implementation seemed to be the only one where it worked

2020-12-02 21:52 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private int restPollRetries = 60;
Yeah I considered putting it under rest initially. Will do that now

2020-12-02 22:08 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private int restPollRetries = 60;
Adding a `RestPollingProperties` class. Moved the above 2 properties as well as the rest base url there

2020-12-02 22:13 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/TopicMessagePublishRequest.java
> +            randomAlphanumeric = new byte[messageByteSize > 8 ? messageByteSize - Long.BYTES : 0];
Updated

2020-12-02 22:15 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/HCSSamplerResult.java
>      private Instant retrieveInstantFromArray(byte[] message) {
Updating to return Instant.MAX in case of null or bytes of length less than 8

2020-12-02 22:17 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/HCSSamplerResult.java
>              log.debug("response message contains invalid publish millisecond value: {}", message);
Updated

2020-12-02 22:17 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TopicClient.java
> +            byte[] suffixByteArray = ("_" + baseMessage + "_" + i + 1).getBytes();
Updated

2020-12-02 22:18 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TopicClient.java
> +        log.trace("Published message : '{}' to topicId : {} with consensusTimestamp: {}", new String(message), topicId,
Wrapped

2020-12-02 22:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> +                    topicClient.publishMessageToTopic(consensusTopicId, "backgroundMessage".getBytes(), submitKey);
Added

2020-12-02 22:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            maxAttemptsExpression = "#{@acceptanceTestProperties.restPollRetries}")
Updated to `#{@restPollingProperties.maxAttempts}`

2020-12-02 22:25 UTC, Nana-EC commented
@beeradb added you so you can take notice of the breaking change on the yaml properties file.
The rest url location got indented and variable name changed.
Before 
```yaml
hedera:
  mirror:
    test:
      acceptance:
        # REST endpoint
        mirrorRestAddress: http://testnet.mirrornode.hedera.com/api/v1
```
After
```yaml
hedera:
  mirror:
    test:
      acceptance:
        rest:
          # REST endpoint
          baseUrl: http://testnet.mirrornode.hedera.com/api/v1
```

2020-12-02 22:54 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/TopicMessagePublishRequest.java
> +            new SecureRandom().nextBytes(randomAlphanumeric);
Ah, missed that.

2020-12-02 23:04 UTC, steven-sheehy submitted a review, later dismissed
LGTM with one minor nit

2020-12-02 23:04 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/RestPollingProperties.java
> +    @NotNull
Suggest using DurationMin/Max to narrow the allowed values.

2020-12-02 23:18 UTC, ijungmann approved these changes
LGTM

2020-12-02 23:26 UTC, xin-hedera submitted a review, later dismissed
LGTM

2020-12-03 16:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/RestPollingProperties.java
> +    @NotNull
Added

2020-12-03 16:05 UTC, steven-sheehy approved these changes

2020-12-03 16:20 UTC, merged