Publish topic messages to redis in a separate thread
hashgraph/hedera-mirror-node pull request #1311
Opened 2020-12-02 17:25 UTC by xin-hedera

**Detailed description**:
This PR changes `RedisEntityListener` to publish topic messages to redis in a separate thread so as to improve ingestion throughput and latency especially under heavy HCS traffic.

- Publish topic messages to redis in a separate thread
- Ignore duplicate topic messages, e.g., when parsing fails at the middle and the record file is reprocessed later

**Which issue(s) this PR fixes**:
Fixes #1308 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-12-09 19:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    public static final int TASK_QUEUE_SIZE = 8;
leave `TASK_QUEUE_SIZE` as a static non-configurable field due to spring validation penalty on `redisProperties.isEnabled()` which is checked in every `onSave()` invocation.

2020-12-10 00:31 UTC, Nana-EC reviewed
Looks good, just some comment suggestions

2020-12-10 00:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    public static final int TASK_QUEUE_SIZE = 8;
make this a comment since there's an intention behind it

2020-12-10 00:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            // batch save action may run asynchronously, trigger it before other operations can reduce latency
nit:
```suggestion
            // batch save action may run asynchronously, triggering it before other operations can reduce latency
```
or
```suggestion
            // batch save action may run asynchronously, trigger it before other operations to potentially reduce latency
```

2020-12-10 00:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +            // run the flux operations in a different thread
nit: please add a bit more content to this to highlight the intricacies of the flux here. 
If my understanding is correct you're generating topicmessage and adding to the sink, whiles supporting subscription on a single thread with messages in the pipeline converted and published. 

This is something I'm pushing for with all our reactive streams to ensure the intent is clear and make it easier to understand and manage future changes/improvements.

2020-12-10 07:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                sink.complete();
I'm still learning the ins and outs of Flux, if there were a period where no messages were coming in would this cause the `complete()` to close the Flux?  And then what would happen if messages were then to come in later, would it generate a new Flux?  This code looks good, just trying to make sure I understand.

2020-12-10 07:36 UTC, ijungmann requested changes
Looks really good, just a couple variable names.

2020-12-10 07:36 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +        List<TopicMessage> messages = topicMessages;
nit: I would name this something a little clearer, maybe `latestMessageBatch`.

2020-12-10 07:36 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java
> +        Flux<TopicMessage> topicMessages = subscribe(messages.get(0).getTopicNum());
nit: I would prefer either `messages` or `topicMessages` be renamed, having a hard time following which is which at times.

2020-12-10 14:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                sink.complete();
An empty list is only put into the `topicMessagesQueue` in the shutdown hook, which is used as a special value to gracefully complete the flux. btw, `BlockingQueue` by spec throws NPE if the element to add is null, so an empty list is chosen as the special value.

During normal processing, at the beginning of `onSave`, we have

```
if (!isEnabled() || topicMessages.isEmpty()) {
    return;
}
```

so only when there are messages, the list is pushed into the flux.

2020-12-10 15:28 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                sink.complete();
Ah, got it.  I also had some misunderstanding of how `take()` works, after some more reading I get it.  Thanks!

2020-12-10 20:28 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java
> +        Flux<TopicMessage> topicMessages = subscribe(messages.get(0).getTopicNum());
renamed `topicMessages` to `topicMessagesFlux`

2020-12-10 20:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +        List<TopicMessage> messages = topicMessages;
just did so

2020-12-10 20:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            // batch save action may run asynchronously, trigger it before other operations can reduce latency
took the first suggestion

2020-12-10 20:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    public static final int TASK_QUEUE_SIZE = 8;
added some comment

2020-12-10 20:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +            // run the flux operations in a different thread
added comment to describe the flow

2020-12-10 20:43 UTC, ijungmann approved these changes
LGTM

2020-12-10 21:49 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-12-10 21:51 UTC, steven-sheehy requested changes

2020-12-10 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    private Disposable subscription;
When I said we should consider Flux I meant replace things entirely with it. We shouldn't mix and match non-blocking Flux with blocking queues and regular array lists. We should either use all flux or all `BlockingQueue` with a regular thread. For latter can just have a method like below:

```java
@Async
@EventListener
public void onStartup(ApplicationReadyEvent event) {
  while (true) {
    publish(topicMessagesQueue.take());
  }
}
```

For Flux only approach, can actually remove queue and list and just create a flux on startup like below (exact processor, overflow strategy and values would need to be investigated):

```java
void init() {
  DirectProcessor<TopicMessage> directProcessor = DirectProcessor.create();
  topicMessageSink = directProcessor.sink();
  directProcessor.filter(last timestamp)
    .bufferTimeout(1000, Duration.ofSeconds(1))
    .subscribeOn(Schedulers.single())
    .subscribe(this::publish);
}

public void onTopicMessage(TopicMessage topicMessage) {
  topicMessageSink.next(topicMessage);
}
```

Flux only approach would have the added benefit of allowing us to remove batch `onSave()` and make the class stateless.

2020-12-10 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    private long lastConsensusTimestamp;
Should be made volatile or AtomicLong. Sonar seems to complain about volatile even when used properly, so maybe AtomicLong.

2020-12-10 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +            public Object execute(RedisOperations operations) {
Shouldn't remove generics. Sonar will most likely complain

2020-12-10 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                    .doOnError(t -> log.error("Unexpected error during redis publish flow", t))
Should probably `onErrorContinue` since we never want to stop publishing and not know about it or keep trying.

2020-12-10 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +            messages.clear();
There's not really any point in clearing this anymore, right?

2020-12-10 22:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +            public Object execute(RedisOperations operations) {
I recall I removed it because of sonar complaint on K, V not being used

2020-12-11 02:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    private Disposable subscription;
Looks like there isn't a way to achieve the following at the same time:

* use Flux only approach
* run the redis publish in a different thread
* block the parser thread when downstream redis publish is blocked / slow
* not rely on non-flux mechanism for example `BlockingQueue`

The `DirectProcessor` and `subscribeOn` approach does not work as expected, it turns out to be the whole flux pipeline runs in the same thread sink.next/error/complete is called.

`UnicastProcessor` may honor `subscribeOn`, and when created with a `BlockingQueue`, we can achieve the first 3 goals but not the last.

So sounds like using `@Async` with `BlockingQueue` is the way to go.

2020-12-11 03:50 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    private Disposable subscription;
`@Async` and `@EventListener` cause `BeanNotOfRequiredTypeException`, so instead, use Executor to run the publish task.

2020-12-11 03:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +    private Disposable subscription;
> block the parser thread when downstream redis publish is blocked / slow

Technically the requirement is don't increase memory unbounded. Blocking is just one approach to do that. Other is to throw an error and retry in the next poll. But am fine with Async if that accomplishes our goals.

2020-12-11 16:17 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2020-12-11 16:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                //
nit
```suggestion

```

2020-12-11 17:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                //
I think this is probably to fix sonar complaining of empty block. Probably safe to just `Thread.currentThread().interrupt()` instead even though the thread is already closing since it's out of the while.

2020-12-11 18:53 UTC, Nana-EC submitted a review, later dismissed
LGTM

2020-12-11 20:25 UTC, steven-sheehy approved these changes

2020-12-11 20:51 UTC, Nana-EC approved these changes
LGTM

2020-12-11 21:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
> +                //
Got it.

2020-12-11 21:45 UTC, ijungmann approved these changes

2020-12-11 22:42 UTC, merged