TimescaleDB : Add Flyway v2 migrations in support of new schema
hashgraph/hedera-mirror-node pull request #1319
Opened 2020-12-04 17:58 UTC by Nana-EC

**Detailed description**:
In support of timescale db the current db schema and migration would need to be updated w v2 files.
Also given all the migrations in v1 we can start afresh with a cleaner schema

- Add v2.0.0 migration sql file that creates the tables
- Add v2.0.1 migration sql file to create hyper tables
- Add v2.0.2 migration sql file to create necessary indexes
- Add v2.0.3 migration java file to bootstrap address book 
- Add FlywayProperties class to hold configs for flyway migration. Also add to DbProperties
- Add FlywayConfiguration class as a workaround to baselineVersion set not working. This will handle migration and insert configs. With this remove flyway config in yaml properties file
- Update test bootstrap yaml to set `embedded.postgres.docker-image` file as this needs to be set before application context is populated

**Which issue(s) this PR fixes**:
Fixes #1306 

**Special notes for your reviewer**:
- Verified switching between v1 and v2 swell as container only switch works with simple yaml updates

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-05 10:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V2_0_3__Address_Book.java
> +        FileData bootStrapFileData = new FileData(0L, addressBookBytes,
Probably don't need to ingest FileData entries as the db environment is new and `file_data` should be empty.

2020-12-05 10:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- \set default_chunk_time_interval 604800000000000;
nit: If possible get variable to work. If not remove these lines

2020-12-08 16:03 UTC, steven-sheehy requested changes

2020-12-08 16:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('token_account', 'id', chunk_time_interval => 10000,
Should probably use `created_timestamp` instead as it's the consensus timestamp.

2020-12-08 16:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('token', 'token_id', chunk_time_interval => 10000, if_not_exists => true);
Should probably use `created_timestamp` instead as it's the consensus timestamp.

2020-12-08 16:13 UTC, steven-sheehy reviewed
I'm not a fan of the v1 and v2 folders. I can try to see if I can figure out how to get baselineVersion working.

Can you provide the instructions on how you switch from default v1 to v2 with the current approach?

2020-12-08 16:48 UTC, Nana-EC commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
In circle CI this config is used by both importer and grpc runs.
The location is the same but the file path to it is different in each case.
SO had to populate the locations with both or else one module can't find the folder

2020-12-08 16:50 UTC, Nana-EC commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
Depends how Github Actions looks for the migrations to specify it. Either ways the grpc test setup as well as rest need references to the migrations under the importer module to setup the db.

2020-12-08 16:52 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescale/timescaledb:latest-pg11 for v2 db schema. Eventually we'll want to use latest-pg12
We can, 9.6 is just what was being used so didn't want to change that here.
I can if we feel it's okay to do for v1

2020-12-08 16:53 UTC, steven-sheehy commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
I understand that the path varies for each and if they're both using this external config then it needs to have both. What I don't understand is why we need external config at all for this? The config looks identical to the one that's in the classpath. We should only have config for this in the classpath application.yml or boostrap.yml.

2020-12-08 16:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +    public static boolean skipMigrationVersion(MigrationVersion current, Configuration migrationConfiguration) {
Yeah I did consider the Abstract class, forgot why I switched to this option. Will revert and go the agreed way

2020-12-08 16:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V2_0_3__Address_Book.java
> +public class V2_0_3__Address_Book extends BaseJavaMigration {
Yep, already left a comment regarding this. Will move it to AddressBookServiceImpl

2020-12-08 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V2_0_3__Address_Book.java
> +            addressBookService.getCurrent();
Yep, agreed with lazy approach

2020-12-08 16:56 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescale/timescaledb:latest-pg11 for v2 db schema. Eventually we'll want to use latest-pg12
I'm not saying to switch the postgres image, but the comment that states to use latest-pg11.

2020-12-08 16:59 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +     GROUP BY t.consensus_ns, ctl_entity_id, ctl.amount, ttr.result, ttt.name, t.payer_account_id, t.memo, t.valid_start_ns, t.node_account_id, t.charged_tx_fee, t.valid_duration_seconds, t.max_fee,
In v2 timescaledb doesn't like existing transactions query in getTransactionsOuterQuery() and getOneTransaction().
The migrations error out on all the added columns with
```
ERROR:  column "t.charged_tx_fee" must appear in the GROUP BY clause or be used in an aggregate function
``` 
I can circle back to see if there are other options. Also once it's setup the performance testing task can verify the impact on the transactions query

2020-12-08 17:01 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +create domain hbar_tinybars as bigint;
Great, tried to maintain the domains from v1 unless it was necessary to change like the case of the timestamps and entity ids.
If you're also onboard I'll happily remove them. 
Additionally, we're not even really using them as domains were intended, most of them don't have any additional constraints to warrant a domain vs the base type

2020-12-08 17:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add constraint account_balance__pk primary key (consensus_timestamp, account_id);
Intention was to have all constraints and indexes added in this one file, I must have missed a few with he newer tables. 

It's cleaner to add the index and constraints after hyper table creation. 
I'm okay with moving constrains only along with table creation since it highlights the intended primary key there and then.

2020-12-08 17:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists account_balance__account_timestamp
Cleaner and yes helps with migration, by immensely speeding it up.
Db to DB migration would only needs to create the tables as done in 2v.0.0 and then insert data.
All the v2.0.0 creations are guarded with `if not exists` so it would skip that and 2.0.1 and 2.0.2 would run fine.
This reduces duplication since everything else can be handled by the flyway migrations.

2020-12-08 17:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('record_file', 'id', chunk_time_interval => 1000, if_not_exists => true);
Yeah, was thinking a few tables indexed on serials could benefit from a time series column.
`consensus_start` is a good replacement.

2020-12-08 17:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('account_balance', 'consensus_timestamp', chunk_time_interval => 604800000000000,
Timescaledb needs explicit setting when the data type is an integer
```
For integer types, the chunk_time_interval must be set explicitly, as the database does not otherwise understand the semantics of what each integer value represents (a second, millisecond, nanosecond, etc.)
```
Default is 7 days which is the 604800000000000 above.

2020-12-08 17:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- Use default of 604800000000000 ns (7 days) as chunk time interval
Not yet, I could add this as a task in the performance testing side.
It really comes down to traffic on the tables and how deterministic they are.
We could account for high TPS in a week and configure for that but it doesn't say for instance what type of transactions and how say `file_data` will grow vs `token` 
Those might require more analysis

Given we won't be immediately deploying we should have some time to get it right before we can't modify migrations.
Consequently I could also make `default_chunk_time_interval` and `default_chunk_id_interval` placeholders so the actual sql code doesn't need changing. 

Also it is possible to update the value however it only affects data going forward and not previous data. See https://docs.timescale.com/latest/api#set_chunk_time_interval

2020-12-08 17:35 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +     GROUP BY t.consensus_ns, ctl_entity_id, ctl.amount, ttr.result, ttt.name, t.payer_account_id, t.memo, t.valid_start_ns, t.node_account_id, t.charged_tx_fee, t.valid_duration_seconds, t.max_fee,
The migration shouldn't error out as this is a REST API query not run during migration. You mean that the REST API query errors when invoked by a user, right?

2020-12-08 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists account_balance__account_timestamp
I would disagree with the clearer, but if it helps speeds up migration then we should keep it in separate migrations.

2020-12-08 17:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add constraint account_balance__pk primary key (consensus_timestamp, account_id);
I think it's clearer with create table but since constraints are also indexes and adding them after data import improves performance as noted in the other comment, we should move all constraints to 2.0.2 migration file.

2020-12-08 17:45 UTC, steven-sheehy commented
We should consider adding a GitHub action that runs on PR commit or nightly with v2 + timescaledb configured. Otherwise we're not testing this new db code path in an automated fashion to catch regressions.

2020-12-08 17:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- Use default of 604800000000000 ns (7 days) as chunk time interval
We have that analysis. Can look at the DB graph of mainnet in Kibana to see how different tables grow.

2020-12-08 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +
Will look into which tables warrant this but note the current limitations - https://docs.timescale.com/v2.0/using-timescaledb/limitations#distributed-hypertable-limitations. Also, I believe you can only use 1 additional space to distribute across and achieve multi dimensional splits.

Although, splits across shards and realms may not necessarily be what you want.
To capitalize on the parallel computation you'd want the distribution to match the grouping of your queries e.g. by entityId or transactionType, or timestamp in the case of balances etc.

Since we're not operating in multi shards/realms yet can't say how often you'd be pulling across those and whether their optimization is necessary beyond indexing.

2020-12-08 18:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('account_balance_sets', 'consensus_timestamp',
Can add to this PR. Probably just the larger tables for now i.e. `account_balance`, `crypto_transfer`, `topic_message`, `transaction`. Potentially `token_transfer`
Will require a bit more code as each table will need 

1. An alter by to turn compression on for the table
2. A set of the integer_now_func 
3. A compression policy
I'll also create a shared function that each tables step 2 can use

2020-12-08 18:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('token_account', 'id', chunk_time_interval => 10000,
Agreed

2020-12-08 18:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('token', 'token_id', chunk_time_interval => 10000, if_not_exists => true);
Agreed. With this only the t_entities table will have a non timestamp chunking column.
This is a another reason we should potentially consider a created & modified timestamp columnon the `t_entities`

2020-12-08 18:35 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +    baseline-version: 0
> I'm not a fan of the v1 and v2 folders. I can try to see if I can figure out how to get baselineVersion working.
> 
> Can you provide the instructions on how you switch from default v1 to v2 with the current approach?

Sure. Simply update `baselineVersion`, `locations` and `target` as follows
```yaml
spring:
      flyway:
        baselineVersion: 1.999.999
        locations: "classpath:db/migration/v2"
        target: 2.999.999
```
Importer startup and grpc test configs will pick those up.
For rest tests update the integrationDbOps.js flywayMigrate() with the above changes also

2020-12-08 18:54 UTC, Nana-EC commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
Gotcha. Yeah wasn't sure why it wasn't picking up the application.yml config previously.
Local maven runs seems to pick it up and all tests would pass but circle runs seemed to not do the same without the explicit specification here. It wouldn't honor the target and would try to run v2 migration also.
Can circle back and try again and see what was off

2020-12-08 19:05 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescale/timescaledb:latest-pg11 for v2 db schema. Eventually we'll want to use latest-pg12
Ah understood. 
The latest default value available in the suggested settings was `timescale/timescaledb:latest-pg11`. 
However, we can force it to use latest-pg12 like we're forcing it to use 9.6 which isn't a suggestion  yet.
Will update

2020-12-08 19:08 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +     GROUP BY t.consensus_ns, ctl_entity_id, ctl.amount, ttr.result, ttt.name, t.payer_account_id, t.memo, t.valid_start_ns, t.node_account_id, t.charged_tx_fee, t.valid_duration_seconds, t.max_fee,
Yeah sorry, not the migration, actually REST API queries.

2020-12-09 15:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V2_0_3__Address_Book.java
> +public class V2_0_3__Address_Book extends BaseJavaMigration {
Addressing this in PR #1340 once that's merged I'll rebase and this will go away

2020-12-09 15:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V2_0_3__Address_Book.java
> +    public void migrate(Context context) throws Exception {
Addressing this in PR #1340 once that's merged I'll rebase and this will go away

2020-12-09 15:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V2_0_3__Address_Book.java
> +            addressBookService.getCurrent();
Addressing this in PR #1340 where most of this logic is moved to the service to ensure the mirror can populate the table if need be on `AddressBookServiceImpl.getCurrent()` or `AddressBookServiceImpl.update()` when table is empty

2020-12-09 15:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +    public static boolean skipMigrationVersion(MigrationVersion current, Configuration migrationConfiguration) {
Addressing this in PR #1340 where I added the MirrorBaseJavaMigration class that contains this logic

2020-12-09 15:32 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +    baseline-version: 0
Fixed camel case request

2020-12-09 15:32 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescale/timescaledb:latest-pg11 for v2 db schema. Eventually we'll want to use latest-pg12
Updated

2020-12-09 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +      api-password: ${hedera.mirror.importer.db.restPassword}n
Removed

2020-12-09 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/test/resources/config/bootstrap.yml
> +google:
Fixed accidental indentation  issue

2020-12-09 15:34 UTC, Nana-EC commented
> We should consider adding a GitHub action that runs on PR commit or nightly with v2 + timescaledb configured. Otherwise we're not testing this new db code path in an automated fashion to catch regressions.

Agreed, will fix up psql and AddressBook migration changes and then get this

2020-12-09 17:12 UTC, ijungmann commented
Looked over this a couple times and haven't found anything additional to add, I'll look again after any changes.

2020-12-10 02:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +
There's a bit of a challenge implementing this outside of k8's where multiple pods each with a single timescale-ha container is started up.
Data nodes are required prior to the  `create_distributed_hypertable`  command.
However attempting to add data_nodes results in 
```
 ERROR: add_data_node cannot run inside a transaction block
```
Such nodes can't be added within a transaction of which each flyway migration is.

2020-12-10 06:10 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescale/timescaledb:latest-pg11 for v2 db schema. Eventually we'll want to use latest-pg12
Went with the image tag to match that used in the chart

2020-12-10 06:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add constraint account_balance__pk primary key (consensus_timestamp, account_id);
Moved all constraints, indexes and primary key creations to V2.0.2 migration file

2020-12-10 06:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists account_balance__account_timestamp
Left as is for migration speed purposes

2020-12-10 06:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('record_file', 'id', chunk_time_interval => 1000, if_not_exists => true);
Updated to use `consensus_start`

2020-12-10 06:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('account_balance', 'consensus_timestamp', chunk_time_interval => 604800000000000,
Added a config setting and placeholder for this

2020-12-10 06:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('account_balance_sets', 'consensus_timestamp',
Added above compression logic in a V2.0.3 migration file

2020-12-10 06:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('token_account', 'id', chunk_time_interval => 10000,
Updated

2020-12-10 06:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +select create_hypertable('token', 'token_id', chunk_time_interval => 10000, if_not_exists => true);
Updated

2020-12-10 06:19 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescale/timescaledb:latest-pg12 for v2 db schema.
Update to
```suggestion
    # set to timescaledev/timescaledb-ha:pg12-ts2.0.0-rc3  (same as chart) for v2 db schema.
```

2020-12-10 06:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- Extend the database with TimescaleDB - assumes super user permissions on database
Remove as test images have extension installed and so for containers in upcoming chart.

2020-12-10 22:11 UTC, Nana-EC commented
@steven-sheehy you can ignore the Addressbook related stuff since it's covered in other PR. But I updated the sql migrations.

2020-12-11 04:31 UTC, Nana-EC commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
Seems like the `spring.flyway.target` and `spring.flyway.locations` are not honored from the classpath application.yml. It only gets picked up when explicitly added in circleci.

2020-12-11 05:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +
Added #1346 to address this later

2020-12-11 18:16 UTC, steven-sheehy commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
What about in bootstrap.yml?

2020-12-11 20:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +        chunkIdInterval: 10000
Will remove this and leave it under flyway placeholders

2020-12-11 20:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- Use default of 604800000000000 ns (7 days) as chunk time interval
Looking, will have to weigh different TPS and envs. I'm leaning towards open a ticket for this in conjunction with local perf testing

2020-12-11 20:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +-- The constraint "token_balance_timestamp_ids" cannot be enforced with the given compression configuration.
Looking into this error for compression but the rest is good.

2020-12-11 22:12 UTC, Nana-EC commented on .circleci/config.yml
> +                locations: "filesystem:./src/main/resources/db/migration/v1,filesystem:../hedera-mirror-importer/src/main/resources/db/migration/v1"
Works for main bootstrap but not test bootstrap.
Should want to run the v2 tests in CIrcleCI using the same code base we'd have to update the application.yml in this way through not preferred

2020-12-11 22:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +-- The constraint "token_balance_timestamp_ids" cannot be enforced with the given compression configuration.
Had to add token_id since it's also used in the index creation

2020-12-11 22:52 UTC, steven-sheehy requested changes

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- address_book skipped because we don't expect high traffic inserts
Is there a cost with making them hypertables? What are the pro/cons? Once we go permissionless, I could see address_book/entry having high traffic. I say we make them hypertables unless the cons outweigh the pros for current levels of traffic.

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'created_timestamp desc', timescaledb.compress_segmentby = 'freeze_default');
Why would freeze_default be a good pick? You're supposed to pick a segmentby with a secondary column or columns that are used a lot in queries. It says generally that's primary keys or other columns in indexes. Should this be `token_id` or maybe `treasury_account_id`? We query more on token_id so that is preferable.

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'id desc', timescaledb.compress_segmentby = 'deleted');
`deleted` is a poor choice. I think `fk_entity_type_id` would be best.

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'consensus_timestamp desc');
segmentby = entity_id

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'consensus_timestamp desc', timescaledb.compress_segmentby = 'topic_num');
Should probably be realm num and topic num since we use those in queries

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'consensus_ns desc', timescaledb.compress_segmentby = 'type');
This should be payer_account_id as that is the more frequently accessed field.

2020-12-11 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'created_timestamp desc', timescaledb.compress_segmentby = 'freeze_default');
It looks like the default `timescaledb.compress_orderby` is already set to the timestamp column in descending order. Thus, it would be better to leave off the hardcoded value and let it use the default if possible.

2020-12-12 01:50 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +     GROUP BY t.consensus_ns, ctl_entity_id, ctl.amount, ttr.result, ttt.name, t.payer_account_id, t.memo, t.valid_start_ns, t.node_account_id, t.charged_tx_fee, t.valid_duration_seconds, t.max_fee,
Not sure how these are working with Postgres 9.6 but timescale is enforcing the requirement of select column to be in a `GROUP BY clause or be used in an aggregate function`
I believe as we're using it having them in the group by doesn't change the results, but I'll have to look into any performance hits

2020-12-12 01:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'created_timestamp desc', timescaledb.compress_segmentby = 'freeze_default');
This was a mistake, agreed it should be `token_id`.

2020-12-12 01:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'id desc', timescaledb.compress_segmentby = 'deleted');
Indeed, we'd more often query by entity type that whether the entity was deleted or not.
Will update

2020-12-12 02:01 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'consensus_ns desc', timescaledb.compress_segmentby = 'type');
I anticipate type will become more often used. Especially as we recently added that query. I'll use both

2020-12-12 02:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    set (timescaledb.compress, timescaledb.compress_orderby = 'created_timestamp desc', timescaledb.compress_segmentby = 'freeze_default');
True, will remove

2020-12-12 02:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- address_book skipped because we don't expect high traffic inserts
Comments are mixed up here. We can't do hyper tables since address_book serves as a foreign key for address_book_entry and timescale db doesn't support that - `Hypertables support all standard PostgreSQL constraint types, with the exception of foreign key constraints on other tables that reference values in a hypertable.`
```
error: foreign keys to hypertables are not supported
```
I can however make `address_book_entry` a hyper table if we do expect more traffic this way.

In terms of cons I haven't come across any yet since they've designed the use and management of hyper tables to be as easy as normal tables.

2020-12-12 02:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- address_book skipped because we don't expect high traffic inserts
Another option is to remove the foreign key from address_book_entry like we did with the other tables.
Then I can make `address_book` a hyper table also.

Notably I did skip the table that don't get updated by importer parsing but rather by us e.g. `t_entity_types`,  `t_transaction_results`, `t_transaction_types`

2020-12-12 03:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- address_book skipped because we don't expect high traffic inserts
Yeah, I would say make both hypertables so we don't run into issues in the future and all non reference tables are hypertables

2020-12-14 16:08 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-balances-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000001"
Why did this start showing up?

2020-12-14 16:21 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/resources/bootstrap.yml
> +  flyway:
I believe I mentioned when setting in the test bootstrap circle ci doesn't seem to pick it up. It's either set here or in circle ci config file

2020-12-14 16:37 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000001"
Because of the unique index addition.

```sql
create unique index if not exists token_id_timestamp
    on token (token_id, created_timestamp);
```

In v1 the index is the token_id, however in v2 we made it the timestamp but still want the token id index.
This could be turned into just an index and not unique but distinct token_id and created_timestamp makes sense

2020-12-14 16:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000001"
I'm glad it caught this as it meant all the timestamps were 0 up until now, which isn't accurate

2020-12-14 16:52 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-balances-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000001"
Unique `created_timestamp` index only makes sense, adding `token_id` to it is redundant. We should probably have a separate non-unique index just for `token_id` as we use that in queries more often by itself.

2020-12-14 17:33 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-balances-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000001"
Sounds good. `created_timestamp` is the primary key so that should cover that.
Will adjust this to be just an index on `token_id`

2020-12-14 17:35 UTC, ijungmann requested changes
Couple minor nits

2020-12-14 17:35 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +
nit: since every other statement has a comment above, would make sense to add one here too.

2020-12-14 17:35 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- t_application_status
Was this just a placeholder, or should there be more information here?

2020-12-14 17:35 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +-- t_application_status skipped
nit: new line in between to be in line with other skip comments.

2020-12-14 17:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +
Yes, just added, will push on next commit

2020-12-14 17:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- t_application_status
should have extra info to say it's not going to be a hyper table.
Will add

2020-12-14 17:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +-- t_application_status skipped
Will add.

2020-12-14 17:53 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2020-12-14 18:15 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
> +-- t_application_status
This still needs the additional info

2020-12-14 18:27 UTC, ijungmann approved these changes
LGTM

2020-12-14 18:30 UTC, steven-sheehy approved these changes

2020-12-14 18:32 UTC, xin-hedera approved these changes
LGTM

2020-12-14 18:35 UTC, merged