Another attempt to fix monitor publishing
hashgraph/hedera-mirror-node pull request #1336
Opened 2020-12-08 22:38 UTC by steven-sheehy

**Detailed description**:
- Fix `NullPointerException` halting the publish flow
- Change to throw exceptions in `PublishMetrics` and catch and ignore those errors after sequential merge of parallel flux

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-08 23:12 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .sequential()
q: does the description need to be updated with how you're using sequential here?
When it comes to the overhead/management of the simple but involving steps it's good to note the aim/intent of the reactive flow we intend so we prevent regressions.

2020-12-08 23:18 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .sequential()
q: does the description need to be updated with how you're using sequential here?
When it comes to the overhead/management of the simple but involving steps it's good to note the aim/intent of the reactive flow we intend so we prevent regressions.

2020-12-08 23:46 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .sequential()
Not really. It's not actually sequential as in single threaded, it's just converting from a `ParallelFlux` back to a `Flux`. Each subscriber is still using the publisher threads to do some of its work. But both subscribers actually can have other threads do the work like netty, grpc or retry threads.

2020-12-08 23:56 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .sequential()
Open to suggestions though, but can't think of anything myself.

2020-12-08 23:58 UTC, ijungmann approved these changes
LGTM

2020-12-09 01:00 UTC, xin-hedera requested changes

2020-12-09 01:00 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .onErrorContinue((t, r) -> log.error("Unknown error during publish/subscribe flow: {}", t))
- from IDEA hint: should remove `{}` in the message string
- the second `onErrorContinue` will swallow all `Throwable` other than `PublishException` which is taken care of in the first `onErrorContinue`. Is it intended? I saw in `PublishMetrics.java`, for `LocalValidationException`, the error message "Local error. Halting thread" hints something different.

2020-12-09 01:42 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .sequential()
Gotcha. That's pretty much the intention of the method. Wasn't sure if it was more complex than that or had additional benefits in its use.

2020-12-09 05:49 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .onErrorContinue((t, r) -> log.error("Unknown error during publish/subscribe flow: {}", t))
Removed `{}`. Log4j2 allows it either way and will implicitly print stacktrace if you leave it off.

True, shouldn't continue if `LocalValidationException`. I've adjusted it to continue only for `PublishException` for now as that's the only thing I know for sure we should resume. All others will be logged and terminate the flux.

2020-12-09 15:08 UTC, xin-hedera approved these changes
LGTM

2020-12-09 15:26 UTC, Nana-EC approved these changes

2020-12-09 16:16 UTC, merged