Add rest percentage check to monitor
hashgraph/hedera-mirror-node pull request #1339
Opened 2020-12-09 05:54 UTC by ijungmann

**Detailed description**:
- Add property `validationPercentage` to monitor to only validate certain transactions via REST.

**Which issue(s) this PR fixes**:
Fixes #1315 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-10 22:02 UTC, Nana-EC approved these changes

2020-12-10 22:33 UTC, steven-sheehy requested changes

2020-12-10 22:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriberProperties.java
> +    private double validationPercentage = 1.0;
Percentage is grammatically used for general measurements and not specific values. We should use percent instead.

But really what we're doing here is sampling. Generally that's measured in total sample size or sample rate/frequency. Ours is a sample percentage of the transaction rate. So we should either name it `sampleRate` or `samplePercent` to make clear it's a percentage.

2020-12-10 22:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/subscribe/RestSubscriberTest.java
> +    void zeroValidationPercentage() throws InterruptedException {
We should have tests for 100% and for a percent in between with a large enough sample size. See `ConfigurableTransactionGeneratorTest` for an example.

2020-12-10 22:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +                .filter(publishResponse -> shouldFilter(publishResponse, properties.getValidationPercentage()))
Avoid the property reflection penalty by getting the percent once outside the flux as a primitive.

2020-12-10 22:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +                .compare(RANDOM.nextDouble(), validationPercentage) != -1;
`RANDOM.nextDouble() < validationPercentage)` is much more readable than `Double.compare()` in my opinion.

2020-12-10 22:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +        boolean filterOut = Double
Inverting this logic just for an off by default log statement makes it more verbose and harder to understand. What's wrong with `.filter(r -> RANDOM.nextDouble() < samplePercent)`?

2020-12-10 23:39 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +                .filter(publishResponse -> shouldFilter(publishResponse, properties.getValidationPercentage()))
I was wondering if that would have any effect.  Moved out.

2020-12-10 23:39 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +                .compare(RANDOM.nextDouble(), validationPercentage) != -1;
Changed

2020-12-10 23:41 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +        boolean filterOut = Double
I was debating adding a metric here to count the number skipped and moved it all out, then decided against it.  I've put it back to the one line filter.

2020-12-10 23:47 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriberProperties.java
> +    @PositiveOrZero
Makes sense, I hesitated when I noticed the documentation said doubles aren't supported, but it's working as expected and has been changed.

2020-12-10 23:47 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriberProperties.java
> +    private double validationPercentage = 1.0;
Changed to `samplePercent`

2020-12-11 03:22 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/subscribe/RestSubscriberTest.java
> +    void zeroValidationPercentage() throws InterruptedException {
Added tests for 100% and 75%, and reworked all 3 tests to run 1000 responses.

2020-12-11 16:08 UTC, steven-sheehy approved these changes
LGTM

2020-12-11 16:21 UTC, Nana-EC approved these changes

2020-12-11 16:24 UTC, merged