Addressbook migration
hashgraph/hedera-mirror-node pull request #1340
Opened 2020-12-09 06:42 UTC by Nana-EC

**Detailed description**:
Streamline address book migration logic to increase code sharing, testing but also allow for migration of file_data -> address_book to occur on demand when needed.

- Add a `migrate()` method to the AddressBookService interface
- Move migration logic from `V1_28_1__Address_Book` to `AddressBookServiceImpl`
- Update `V1_28_1__Address_Book` to call `AddressBookServiceImpl.migrate()`
- Add a `MirrorBaseJavaMigration` abstract class to hold shared java migration logic. In this case add a `skipMigrationVersion()` that ensures migrations prior to baseline are not run. This is in anticipation of v2 db schemas where v1 should not be run
- Update `AddressBookServiceImpl.getCurrent()` to handle empty table case and call inner migration logic to bootstrap initial filesystem/classpath address book as well as bring in historic addressBooks
- Update `AddressBookServiceImpl.update()` to ensure address_book` table is populated prior to adding any new address books
- Update tests that allowed for no address book after calling `getCurrent()` or `update()` no initial address book given each test clears the results of migrations

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
This is fallout from comments on PR #1319 and also some desired improvements.
I would like to get this in first to reduce foot print of above PR

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-12-09 19:57 UTC, steven-sheehy requested changes

2020-12-09 19:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        addressBook = addressBookRepository.save(addressBook);
`migrate()` needs to be in a transaction to be functionally equivalent to the flyway approach. What's less clear if it's okay to put `@Transactional` on the public methods of this class and let it join outer transactions or it requires its own inner transaction via `TransactionTemplate`. I'm thinking the latter.

2020-12-09 19:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        addressBook = addressBookRepository.save(addressBook);
Technically `buildAddressBook()` has the potential to return null. Why not reuse `parse()` method?

2020-12-09 19:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    private AddressBook migrateAndRetrieveLatestAddressBook(long consensusTimestamp) {
This method seems unnecessary. You've already retrieved all the data at some point inside the `migrate()` method. Just have it keep track of which is the latest and return that so the signature becomes:
```java
private synchronized AddressBook migrate() {
...
}
```

2020-12-09 20:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_28_1__Address_Book.java
> +        addressBookService.migrate();
Good point
Given Java migration checksums are null and we have `ignoreMissingMigrations` set to true should be fine to remove this.

2020-12-09 20:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_11_6__Missing_Entities.java
> +        if (skipMigrationVersion(getVersion(), context.getConfiguration())) {
Good suggestion. Will make this change

2020-12-09 20:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    private AddressBook migrateAndRetrieveLatestAddressBook(long consensusTimestamp) {
Had considered that, went with the above to be more explicit but I'm okay with this approach.

2020-12-09 22:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (shouldMigrate()) {
Works for me

2020-12-09 22:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    public void migrate() {
Good point. I'll move the synchronized back up here instead of only on the file read method

2020-12-09 22:03 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        addressBook = addressBookRepository.save(addressBook);
Will go with `TransactionTemplate` to be safe

2020-12-09 22:03 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        addressBook = addressBookRepository.save(addressBook);
Yeah `parse` is better. Less code as it does what I need.

2020-12-09 22:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        int pageSize = 1000; //
Nit, unless there's supposed to be a comment here:
```suggestion
        int pageSize = 1000;
```

2020-12-09 22:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_11_6__Missing_Entities.java
> +        if (skipMigrationVersion(getVersion(), context.getConfiguration())) {
Updated

2020-12-09 22:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_28_1__Address_Book.java
> +        addressBookService.migrate();
Removed

2020-12-09 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (shouldMigrate()) {
Modified to call `migrate()` directly and removed `shouldMigrate()`

2020-12-09 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    public void migrate() {
Done

2020-12-09 22:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        addressBook = addressBookRepository.save(addressBook);
Added `TransactionTemplate` execute

2020-12-09 22:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        addressBook = addressBookRepository.save(addressBook);
Updated

2020-12-09 22:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +    private AddressBook migrateAndRetrieveLatestAddressBook(long consensusTimestamp) {
Updated

2020-12-09 22:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +@Named
Removed

2020-12-09 22:35 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        int pageSize = 1000; //
Will remove thanks

2020-12-09 22:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        int pageSize = 1000; //
Updated

2020-12-10 06:14 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    return migrate();
Iis there any risk here of `migrate()` returning null?  I just see that `findLatestAddressBook()` is a more granular search than the one `migrate()` does.

2020-12-10 17:28 UTC, steven-sheehy requested changes

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    log.debug("No address book found in db");
Log can be moved into migrate to produce a more accurate log for race condition and so you can shorten this to `.orElseGet(this::migrate)`. It should also be changed to info log level. In fact, all logs inside migrate can be info (besides the skipping migration log) since it should only occur once and is very important we understand what is going on.

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            return null;
We should never return null. It will NPE during the race condition scenario. Instead of `count()`, can just call `addressBookRepository.findLatestAddressBook(102)` again like in `getCurrent()` and return it if not null. This is effectively double checked locking, so the same check should be done twice.

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +            log.trace("Migration {} will be skipped as it precedes baseline version {}",
This will log as `MirrorBaseJavaMigration` instead of the concrete class. Should remove `@Log4j2` and use `protected final Logger log = LogManager.getLogger(getClass())` instead. You can also remove the annotation from children classes.

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +    public abstract void doMigrate() throws Exception;
protected

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            fileDataList.forEach(fileData -> {
nit: If you just used a normal for loop you could avoid all the atomics. ForEach is useful to be concise, but due to the atomics it actually makes things more verbose in my opinion.

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    fileDataEntries.incrementAndGet();
Codecov says `Added lines #L374 - L375 were not covered by tests`. Is that true? These seem like pretty important lines if not.

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        if (baselineVersion.isNewerThan(current.getVersion()) && migrationConfiguration.isIgnoreMissingMigrations()) {
Is it possible to get coverage for this?

2020-12-10 17:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        if (baselineVersion.isNewerThan(current.getVersion()) && migrationConfiguration.isIgnoreMissingMigrations()) {
Why do we care about ignoreMissingMigrations here? Missing migrations is for files that have been deleted since they've been ran. I don't think that applies here. If you're baselining you're moving up the min version without regard for the presence of the migrations before that.

2020-12-10 19:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    return migrate();
There shouldn't be. 
`migrate()` keeps track of the latest addressBook encountered, so it should return the same value as a `findLatestAddressBook()`
`migrate()` transactionTemplate also checks for empty historical case and ensures at the least the initialAddressBook is passed.
Only way that would fail is with a TransactionException and we'd wanna see those.
Let me know if that covers your question or if I'm missing something

2020-12-10 19:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +            log.trace("Migration {} will be skipped as it precedes baseline version {}",
Good point

2020-12-10 19:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    return migrate();
It can return null on race condition between two threads migrating at same time.

2020-12-10 19:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            return null;
Was siding with going with `count()` as an optimization but the double check is the more correct option

2020-12-10 20:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    fileDataEntries.incrementAndGet();
I had a specific migration test(). It got removed in some refactoring.
Will add back as it definitely covers this

2020-12-10 21:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        if (baselineVersion.isNewerThan(current.getVersion()) && migrationConfiguration.isIgnoreMissingMigrations()) {
Can do

2020-12-10 21:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        if (baselineVersion.isNewerThan(current.getVersion()) && migrationConfiguration.isIgnoreMissingMigrations()) {
Will remove.
Also adding target logic as a nice to have

2020-12-10 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        if (baselineVersion.isNewerThan(current.getVersion()) && migrationConfiguration.isIgnoreMissingMigrations()) {
Done

2020-12-10 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        if (baselineVersion.isNewerThan(current.getVersion()) && migrationConfiguration.isIgnoreMissingMigrations()) {
Done

2020-12-10 21:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            fileDataList.forEach(fileData -> {
Changed to a normal for loop

2020-12-10 21:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +    public abstract void doMigrate() throws Exception;
Updated

2020-12-10 21:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +            log.trace("Migration {} will be skipped as it precedes baseline version {}",
Updated

2020-12-10 21:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            return null;
Updated

2020-12-10 21:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    log.debug("No address book found in db");
Updated

2020-12-10 21:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    return migrate();
Gotcha, with recent updated to check for current and return on non-null I believe that case should now be handled

2020-12-10 23:14 UTC, steven-sheehy requested changes

2020-12-10 23:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V0_0_1__MirrorBaseJavaMigrationTest.java
> +        assertThat(skipMigrationVersion(MigrationVersion.EMPTY, getConfiguration("1", "2"))).isTrue();
This should test migrate's invocation of skipMigrationVersion both to ensure it's correctly invoked and provide coverage to that method.

2020-12-10 23:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V0_0_1__MirrorBaseJavaMigrationTest.java
> +class V0_0_1__MirrorBaseJavaMigrationTest extends MirrorBaseJavaMigration {
Should just be named `MirrorBaseJavaMigrationTest`. You should create a custom private nested class to do the actual testing against.

2020-12-10 23:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_11_6__Missing_Entities.java
> +    public void doMigrate() throws SchemaMigrationException {
You don't need to declare runtime exceptions (as Sonar also attests). Can just do `throws FileNotFoundException, IOException` as the wrapped exception doesn't provide any value since it's bubbled up to a framework we don't control.

2020-12-10 23:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        log.debug("No address book found in db, proceeding with migration");
These two debugs should be info since this is ran once per lifetime.

2020-12-11 01:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        log.debug("No address book found in db, proceeding with migration");
Made info

2020-12-11 01:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_11_6__Missing_Entities.java
> +    public void doMigrate() throws SchemaMigrationException {
Updated it to `IOException` as that's what's thrown and `FileNotFoundException` inherits from `IOException`.
This also requires the abstract class be updated with the throws

2020-12-11 01:11 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V0_0_1__MirrorBaseJavaMigrationTest.java
> +class V0_0_1__MirrorBaseJavaMigrationTest extends MirrorBaseJavaMigration {
Done

2020-12-11 01:11 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V0_0_1__MirrorBaseJavaMigrationTest.java
> +        assertThat(skipMigrationVersion(MigrationVersion.EMPTY, getConfiguration("1", "2"))).isTrue();
Done

2020-12-11 04:01 UTC, steven-sheehy approved these changes
LGTM

2020-12-11 05:03 UTC, merged