Add record to db for stream files in valid folder
hashgraph/hedera-mirror-node pull request #1344
Opened 2020-12-10 20:17 UTC by xin-hedera

**Detailed description**:
- Add java flyway migration to add stream file records to db for files in valid folder without a record

**Which issue(s) this PR fixes**:
Fixes #1325 

**Special notes for your reviewer**:
Tested in local environment using DEMO network, upgrading from 0.16.0 to 0.24.0-rc2, then upgrading to the version with the patch.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-12-10 22:55 UTC, steven-sheehy approved these changes
LGTM

2020-12-10 22:56 UTC, steven-sheehy commented
Just saw Sonar's bug. Should probably throw NotSupportedException for that even though it shouldn't be possible.

2020-12-11 16:32 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2020-12-11 16:42 UTC, ijungmann approved these changes

2020-12-11 17:58 UTC, Nana-EC requested changes
You should rebase with master and utilize the java migration changes.

2020-12-11 17:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +public class V1_32_0__Missing_StreamFile_Record extends BaseJavaMigration {
This should extend the new `MirrorBaseJavaMigration`
```suggestion
public class V1_32_0__Missing_StreamFile_Record extends MirrorBaseJavaMigration {
```

2020-12-11 17:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +    public void migrate(final Context context) {
This would become `doMigrate()`
```suggestion
    public void doMigrate(final Context context) {
```

2020-12-11 18:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +                log.error("ValidPath {} for {} downloader is not a directory", validPath, streamType);
Looks like we're missing a test for this. 
In this case you could have the directory not exist or have the FIleCopier put a file instead of the directory

2020-12-11 20:26 UTC, steven-sheehy approved these changes

2020-12-11 20:50 UTC, Nana-EC approved these changes
LGTM

2020-12-11 21:43 UTC, ijungmann approved these changes

2020-12-11 22:41 UTC, merged