Lazy load transaction types for REST
hashgraph/hedera-mirror-node pull request #1356
Opened 2020-12-14 06:55 UTC by ijungmann

**Detailed description**:
Transaction Types for REST are now loaded from the DB on startup.

**Which issue(s) this PR fixes**:
Fixes #1160 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-14 06:57 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +      transactionType.toUpperCase()
Move this back down.

2020-12-14 06:57 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    LEFT JOIN crypto_transfer ctl ON  ctl.consensus_timestamp = t.consensus_ns
Remove this, was for other PR/task

2020-12-14 06:58 UTC, ijungmann commented
Remove all debug comments.

2020-12-14 22:02 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +const transactionTypesMap = new Map();
Not 100% on this name, I originally just had it as `transactionTypes`, but having `transactionsTypes.transactionTypes.get()` seemed hard to read.

2020-12-14 22:03 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +const constants = require('../constants');
If there's a particular order these need to be in I will shuffle.

2020-12-14 22:16 UTC, ijungmann commented
Unless I'm misreading it the code smells are for the copyright.

2020-12-15 18:00 UTC, Nana-EC requested changes

2020-12-15 18:00 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  return _.isString(transactionType) && transactionTypesMap.get(transactionType.toUpperCase()) !== undefined;
I forget if there's a way to overload the get() function.
If there is or instead of a get expose a separate function that will do the toUpperCase conversion and then call `transactionTypesMap.get()` that would help.

2020-12-15 22:45 UTC, steven-sheehy requested changes

2020-12-15 22:45 UTC, steven-sheehy commented on hedera-mirror-rest/transactionTypes.js
> +const transactionTypesQuery = 'SELECT proto_id, name FROM t_transaction_types';
We've standardized on lowercase SQl statements.

2020-12-15 22:45 UTC, steven-sheehy commented on hedera-mirror-rest/transactionTypes.js
> +const loadTransactionTypes = function () {
Use new style function syntax.

2020-12-15 22:45 UTC, steven-sheehy commented on hedera-mirror-rest/server.js
> +loadTransactionTypes();
Would be less coupled and not slow down startup to lazy load this on-demand. See my note about replacing explicit load with implicit load via `get()`.

2020-12-15 22:45 UTC, steven-sheehy commented on hedera-mirror-rest/transactionTypes.js
> +  transactionTypesMap,
We shouldn't expose a mutable map since people can potentially modify this. Recommend a single method be exposed `get(string)` that lazy loads the internal map.

2020-12-15 22:45 UTC, steven-sheehy commented on hedera-mirror-rest/transactionTypes.js
> +const transactionTypesMap = new Map();
My other recommendation `transactionsTypes.get()` would solve this conundrum.

2020-12-15 23:09 UTC, xin-hedera requested changes

2020-12-15 23:09 UTC, xin-hedera commented on hedera-mirror-rest/transactionTypes.js
> +      }
this is async, though the function is called at process startup, there is no guarantee that when the map is looked up for a transaction type, the data is fully populated.

2020-12-15 23:09 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return _.isString(transactionType) && transactionTypesMap.get(transactionType.toUpperCase()) !== undefined;
```suggestion
  return _.isString(transactionType) && transactionTypesMap.has(transactionType.toUpperCase());
```

2020-12-16 01:39 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +const transactionTypesMap = new Map();
Keeping as transactionTypesMap, reworked to not expose.

2020-12-16 02:54 UTC, xin-hedera requested changes

2020-12-16 02:54 UTC, xin-hedera commented on hedera-mirror-rest/transactionTypes.js
> +};
this will not work as intended:

- `loadTransactionTypes` immediately returns and nodejs engine won't pause and switch to other tasks, so transactionTypesMap.size is still 0 at line 30
- it's possible when db query is slow, multiple calls to `get` will all see `transactionTypesMap.size === 0`, this will cause multiple db queries for the transaction types

we should use a promise to hold the db query

```javascript

let promise;

const get = async (transactionTypeName) => {
  if (!promise) {
    promise = pool.query(transactionTypesQuery);
  }

  try {
    const result = await promise;
    if (transactionTypesMap.size === 0) {
      result.rows.forEach((row) => transactionTypesMap.set(row.name, row.proto_id));
    }

    return transactionTypesMap.get(transactionTypeName.toUpperCase());
  } catch (Error e) {
    // error handling
  }
}
```

2020-12-16 02:58 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +};
Yeah, I half-did this and saw that tests are failing and have been playing with ways to correct it.  I'll give this a go, I was playing with promises myself and was getting something working but it involved an explosion of async/await across many files.

2020-12-16 03:11 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +};
So this is definitely working but I'm seeing the same issue where this leads to a ton of needed async/await statements.  Is there a cleaner way to handle this (I'm still getting the hang of the async/await concepts), or short of a large refactor is that the only way to solve this?

2020-12-16 03:18 UTC, xin-hedera commented on hedera-mirror-rest/transactionTypes.js
> +};
the alternative for not using async/await in places where `get()` is called is promise chain and that may look worse. personally I prefer async / await, the code is easier to read.

2020-12-16 07:15 UTC, ijungmann commented
Still looking at how to fix up some of these tests.

2020-12-16 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/transactionTypes.js
> +};
I don't think get itself needs to be async as once it's loaded once it's from then on synchronous. So it should hide the asynchronicity from the caller by awaiting internally only if needed if map is empty.

2020-12-16 16:47 UTC, xin-hedera commented on hedera-mirror-rest/transactionTypes.js
> +};
javascript doesn't seem to support it. if a part of the flow is async, the whole flow becomes async.

2020-12-17 02:00 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +const transactionTypesMap = new Map();
Comment added

2020-12-17 02:19 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +const constants = require('../constants');
I'm assuming `const {InvalidArgumentError} = require('../errors/invalidArgumentError');` should be third in that second list because of its directory depth, correct?  Otherwise I follow and will do.

2020-12-17 02:21 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +const constants = require('../constants');
Reordered.

2020-12-17 02:27 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +  pool
Added

2020-12-17 02:28 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  return _.isString(transactionType) && transactionTypesMap.get(transactionType.toUpperCase()) !== undefined;
Added toUpperCase inside of the new get() method in transactionTypeName

2020-12-17 02:29 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +      }
Should be fixed now.

2020-12-17 02:30 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  return _.isString(transactionType) && transactionTypesMap.get(transactionType.toUpperCase()) !== undefined;
Good idea, but this was refactored to take advantage of the new get() logic inside TransactionTypes

2020-12-17 02:48 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +};
Used the above code and walked through the async/await chain to make it happy, effectively a good chunk of the `transaction.js` and `utils.js` functions had to become async as a result, as did some tests and validation functions.  Still figuring out how to work around some of the code smells, but it should work as expected now.

2020-12-17 14:36 UTC, xin-hedera requested changes

2020-12-17 14:36 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const isValidTransactionType = async (transactionType) => {
this function can be removed, see my other comment at line 754

2020-12-17 16:06 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +  }
Good idea, added.

2020-12-17 16:09 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +const constants = require('../constants');
Ah, apparently for a while I was importing cloudProviders in one line, and all of constants in another, and did not notice.  Went with`{cloudProviders, filterKeys}` , fixed now

2020-12-17 16:38 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +  });
Fixed these, also reordered the positive tests below a bit to fit this style.

2020-12-17 16:38 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +  });
Corrected.

2020-12-17 17:01 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +  });
Fixed

2020-12-17 17:13 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
> +  }).rejects.toThrowErrorMatchingSnapshot();
Changed

2020-12-17 17:13 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
>      }).not.toThrow();
Fixed.

2020-12-17 17:13 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
>    test('Verify validateAndParseFilters for valid filters does not throw exception', () => {
Added

2020-12-17 17:28 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    return `${constants.transactionColumns.TYPE}${opsMap.eq}${await transactionTypes.get(transactionType)}`;
I agree that looks better, should it still do an `isString()` check?

2020-12-17 17:39 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const isValidTransactionType = async (transactionType) => {
The function is still used by `filterValidityChecks`, I can move the logic into there but considering most of the other validation checks have their own functions (and it would require some test refactoring), I would think it makes sense to keep it as is.

2020-12-17 17:40 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    return `${constants.transactionColumns.TYPE}${opsMap.eq}${await transactionTypes.get(transactionType)}`;
Added as is for now.

2020-12-17 17:41 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    return `${constants.transactionColumns.TYPE}${opsMap.eq}${await transactionTypes.get(transactionType)}`;
nope in my opinion

2020-12-17 19:21 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const isValidTransactionType = async (transactionType) => {
sure

2020-12-17 19:42 UTC, xin-hedera approved these changes
LGTM

2020-12-17 20:30 UTC, steven-sheehy commented
The async virus keeps spreading...

Looks good, but I would like to see those code smells fixed. Some of them seem pretty serious as they indicate expecting functions to return a promise but they're not.

2020-12-17 20:55 UTC, xin-hedera commented
Those code smells about await look more like sonar's issue. Agree we should try to find a way to get around it.

2020-12-17 21:30 UTC, steven-sheehy commented
Ah, didn't realize it's a Sonar false positive. You can just mark them as resolved as false positive in Sonar.

2020-12-17 21:32 UTC, ijungmann commented
Yeah, removing the awaits as it suggested caused major issues, I just tried a couple attempts to explicitly return a promise and it's still not happy about it, looks like false positives.

2020-12-17 21:53 UTC, ijungmann commented
Marked as false positives with comments, reran the scan to confirm nothing new pops up.

2020-12-17 21:55 UTC, steven-sheehy approved these changes

2020-12-17 22:09 UTC, xin-hedera approved these changes

2020-12-17 22:18 UTC, ijungmann commented
Nana's review is blocking a merge, shall we wait until Monday for his input or can someone dismiss the review? I've addressed his comments thus far.

2020-12-17 22:58 UTC, steven-sheehy commented
I dismissed his review. Looks like all of his comments were resolved. If he has further comments on Monday I'm sure we can address it separately then.

2020-12-17 23:00 UTC, ijungmann commented
Awesome, thanks.

2020-12-17 23:06 UTC, merged