Handle transactions without crypto transfers in transaction REST API
hashgraph/hedera-mirror-node pull request #1358
Opened 2020-12-14 19:02 UTC by xin-hedera

**Detailed description**:

- `account.id` can be either the payer account id of a transaction or the entity id in the crypto transfer, if the query does not use credit/debit type filter
- refactor mysql style query to postgre style query so duplicate query param value concat is not needed
- add new transaction table index

**Which issue(s) this PR fixes**:
Fixes #1295 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-12-14 19:13 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  // crypto_transfer table. So concat their params twice here to match the query.
the comment no longer applies, will remove in the next commit

2020-12-14 22:38 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    index += 1;
Showing my JS ignorance a little, I assume `index` is initialized only on the first call and this continues to increment, instead of constantly resetting to 0, correct?

2020-12-15 01:04 UTC, ijungmann requested changes
Still reviewing, here's what I have so far.

2020-12-15 06:08 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    (resultTypeQuery || transactionTypeQuery) && 'JOIN transaction AS t ON ctl.consensus_timestamp = t.consensus_ns';
Interesting, did not know about this.

2020-12-15 07:02 UTC, ijungmann requested changes
Couple more things, mostly smaller questions.  Tests look good.

2020-12-15 15:59 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const convertToNamedQuery = function (query, prefix) {
AFAIK, the mysql style query was written at the beginning when the choice of db was mysql. that's why for account/balance/transaction, the query needs to be translated to pg style.

I intend to limit the scope of "converting mysql style ? placeholder to named parameter" to where it's indeed needed, for instance, the transactions inner query since the same REST query param is used in multiple places so in the previous PR `tsParams` were concat twice.

Eventually, we should remove the translation layer and directly compose pg style query as in topicmessages and tokens.

2020-12-15 16:03 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +        SELECT DISTINCT ctl.consensus_timestamp AS consensus_timestamp
a crypto transfer always has an associated transaction. previously, the reverse is also true that a transaction always has a crypto transfer list.

similarly, a token transfer must belong to a transaction.

2020-12-15 16:04 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  if (splitItem.length === 2) {
this is auto adjusted by IDEA eslint plugin based on some rule.

2020-12-15 16:05 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    if (value === 'debit') {
this is auto adjusted by IDEA eslint plugin based on some rule.

2020-12-15 16:10 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +        SELECT DISTINCT ctl.consensus_timestamp AS consensus_timestamp
That makes sense, but then I'm not understanding why a FULL OUTER JOIN is needed, as opposed to a LEFT OUTER JOIN.

2020-12-15 16:11 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +const convertToNamedQuery = function (query, prefix) {
That makes sense, thanks for the details.

2020-12-15 16:12 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  const pgSqlQuery = utils.convertMySqlStyleQueryToPostgres(sqlQuery);
good catch

2020-12-15 16:20 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +        SELECT DISTINCT ctl.consensus_timestamp AS consensus_timestamp
oh, it's partially because I made it generic for all REST query params.

To be concise, it's because of the `account.id` filter. with the change, it can be either `transaction.payer_account_id` or `crypto_transfer.entity_id`. It's possible that for `account.id` A, the transactions of which A paid fee for and the transactions with A in the crypto transfer have entries not in the other. So we need a full outer join.

2020-12-15 16:27 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +        SELECT DISTINCT ctl.consensus_timestamp AS consensus_timestamp
Ah, got it.  Interesting that that one param causes so much havoc, that makes sense though./

2020-12-15 18:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +        SELECT DISTINCT ctl.consensus_timestamp AS consensus_timestamp
made some changes to the query to split the generic query into two cases, with and without account query. also added comments based on your feedback

2020-12-15 22:11 UTC, Nana-EC requested changes
Looking good.
Just a suggestion on simplifying it where possible

2020-12-15 22:11 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +  if (creditDebitQuery) {
I get the logic but this section is a little hard to follow and I worry that its complexity might contribute to challenges in managing it.
Do you think there's a way to simplify or split it up into clearer functions.

2020-12-15 23:56 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (creditDebitQuery) {
made an attempt, let me know if it's more maintainable

2020-12-16 17:53 UTC, Nana-EC reviewed
Looks good, additional suggestion for a spec for the accounts/<accountId> spec for a transaction with no

2020-12-16 17:53 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/accounts-10-account-transactions.spec.json
> +      {
Can you add another spec for account transaction with no transfers to make sure that's picked up.

2020-12-16 18:16 UTC, ijungmann approved these changes
LGTM

2020-12-16 20:44 UTC, Nana-EC approved these changes
LGTM

2020-12-16 22:16 UTC, ijungmann approved these changes

2020-12-16 22:18 UTC, steven-sheehy approved these changes

2020-12-16 22:56 UTC, merged