Timescaleb helm
hashgraph/hedera-mirror-node pull request #1359
Opened 2020-12-14 19:13 UTC by Nana-EC

**Detailed description**:
To utilize timescale in our helm chart the chart needs to be updated

- Add TimeScaleDB v2 multimode chart to mirror chart dependencies.
- Configure timescaledb default values in chart `values.yml`
- Update chart `values.yml` with address book filepath
- Updated importer StatefulSet to pull in the address book secret and add the addressbook.bin to filesystem
- Add necessary configmaps and secrets to support db init

**Which issue(s) this PR fixes**:
Fixes #1313 
**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-14 19:37 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  extaddressbook:
Hmm, should I move this into the importer chart as a property?

2020-12-14 19:37 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  #    databases: ["postgres", "mirror_node"]
Might remove `timescaledb.postgresql.databases` to ensure that all db and user creation logic is done in some script

2020-12-14 21:10 UTC, steven-sheehy requested changes
We need to request/implement upstream chart priority class and a way to execute custom scripts.

2020-12-14 21:10 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +  extaddressbook:
What is it? How is it used? What's an `ext`?

2020-12-14 21:10 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +  #  postgresql:
Chart mentions some values are not production ready and should be tweaked. We should tweak:

https://github.com/timescale/timescaledb-kubernetes/blob/abec6247e78b685d4dc075ed877ba02d0eac72f8/charts/timescaledb-multinode/values.yaml#L72

2020-12-14 21:38 UTC, xin-hedera commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +                  name: mirror-importer-addressbook
suggestion: it's good to have a comment in importer charts values about explicit addressbook file name if network is OTHER

2020-12-15 06:10 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +    create: false
There was a bug here where the chart failed to install because of a name conflict.
Meant to circle back with a custom name.
Will add in next commit

2020-12-15 06:15 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +                  name: mirror-importer-addressbook
Will add a comment

2020-12-15 06:18 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  extaddressbook:
This is an external address book (i.e. not in class path) that is used for non demo/testnet/mainnet network.
In this scenario the address book is place at the intialAddressBook path for reading
Probably better way to state this would be

```yaml
importer:
  initialAddressBook:
    enabled: true
    path:  ./<somePath>
```

2020-12-15 06:34 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  enabled: false
Adding initial go based on current Postgres constraints

2020-12-15 21:55 UTC, ijungmann commented
Not seeing anything additional to add, will look again after comments addressed.

2020-12-15 22:53 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  extaddressbook:
Went with above for simplicity.

2020-12-15 22:53 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  #    databases: ["postgres", "mirror_node"]
Removed and went with default postgres

2020-12-15 22:55 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +    size: 10Gi
Went with 500Gi to start with. I think like a few other configs the tweaking/tuning can be done later along with testing.

2020-12-15 22:55 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  enabled: false
Added some initial constraints. Further tweaking could be done later

2020-12-15 22:55 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +    create: false
Service account added with custom name to avoid resource name conflict

2020-12-15 22:56 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  #  postgresql:
Tweaked. Likely to have further tweaking in following tasks

2020-12-15 22:56 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +                  name: mirror-importer-addressbook
Added comment

2020-12-15 23:51 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +      shared_buffers: 2GB # recommended to be 25% of available instance memory
But available memory is max 1Gi per your resource constraints. This looks like it is requesting more than is available.

2020-12-15 23:51 UTC, steven-sheehy commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +  {{- end }}
nit: This indentation doesn't match its corresponding if/else

2020-12-15 23:51 UTC, steven-sheehy commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +                  name: mirror-importer-addressbook # if enabled add filesystem path to initial address book for OTHER networks
This doesn't really add the OTHER address book as it still requires you to add a secret manually external to this chart AND configure the path via the values.yaml. I also don't think it's necessary to complicate the config volume by mixing it with the address book. There is a better option:

Add `extraVolumes` and `extraVolumeMounts` as a lot of charts do to add arbitrary secrets, configmaps, etc. to the chart via values.yaml. Then the user would populate the initialAddressBook via the standard config property. The benefit of this approach is pretty widely used by community charts and it is generic and can support adding any arbitrary data in the future that we or users may need.

2020-12-15 23:51 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +    create: false
I don't see how there could've been a name conflict unless a prior install didn't get deleted properly. Hardcoding the name actually makes it more likely there will be a resource name conflict as it doesn't include the namespace or release name in the name this way.

2020-12-16 00:56 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +                  name: mirror-importer-addressbook # if enabled add filesystem path to initial address book for OTHER networks
Sure, will look into the `extraVolume` and `extraVolumeMounts`.

Regarding the extra configs yes, the operator will still have to set the `network: OTHER` and `initialAddressBook` path and deploy the secret manually.
This makes sense since we do expect deployment of that nature to be more detailed.

2020-12-16 00:59 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +      shared_buffers: 2GB # recommended to be 25% of available instance memory
Will tweak to be more consistent with constraint

2020-12-16 01:02 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +  {{- end }}
IntelliJ keeps indenting this. Will try to fix once I've employed the suggested `extraVolume` and `extraVolumeMounts`

2020-12-16 01:18 UTC, steven-sheehy commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +  {{- end }}
Yeah, I don't use intellij to edit helm files. I use vs or vi. Intellij just doesn't understand helm.

2020-12-16 01:19 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +      shared_buffers: 2GB # recommended to be 25% of available instance memory
Or up max memory. 1Gi sounds way too low

2020-12-16 18:01 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +    create: false
I think I may have tracked down the issue. `charts/hedera-mirror/charts` still contained the timescale single chart so that may have been deploying that service account and potentially other resources. Looking into this

2020-12-16 21:49 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +  extaddressbook:
Removed this, so is no longer applicable

2020-12-16 21:50 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +    create: false
Yep, the single chart was the issue. Remove that and there's no longer a conflict

2020-12-16 21:50 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +  {{- end }}
Should be fixed now

2020-12-16 21:50 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +                  name: mirror-importer-addressbook # if enabled add filesystem path to initial address book for OTHER networks
Implemented use of `extraVolumes` and `extraVolumeMounts` configs

2020-12-16 23:00 UTC, steven-sheehy requested changes

2020-12-16 23:00 UTC, steven-sheehy commented on charts/README.md
> +    $ helm repo add hedera https://hashgraph.github.io/hedera-mirror-node/charts
I prefer the TLDR of the previous approach of repo add & install. There are hundreds of potential options to list in between repo add and install that we can't list all. Instead, I think we should add a separate configuration section with this information.

2020-12-16 23:31 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                CREATE EXTENSION IF NOT EXISTS timescaledb;
That was my initial expectation but it seems that the extension is per db.
SO it's there for the postgres db but not the new db created

2020-12-16 23:32 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                alter default privileges in schema public grant select on tables to :grpcuser;
Yes we are. I'll do it in the following PR that's in draft. Wanted to get base case covered since I believe I hit some schema related issues the last time regarding search and access for users.
But yep we'll use a new schema

2020-12-16 23:33 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +
Good idea

2020-12-16 23:37 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                SELECT format('CREATE DATABASE %I', :'dbname')
Yes I had that approach initially and went this was as I was trying to make the approach similar to what timescale does for data nodes db creation, but I agree a secret sql is preferred as it's more secure

2020-12-16 23:59 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +          image: postgres:11-alpine
I was matching the logic of the other timescale jobs but I can set it to `timescaledev/timescaledb-ha:pg12-ts2.0.0-rc3`

2020-12-17 18:28 UTC, xin-hedera requested changes

2020-12-17 18:28 UTC, xin-hedera commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +{{ toYaml .Values.extraVolumeMounts | indent 12 }}
```suggestion
{{- toYaml .Values.extraVolumeMounts | nindent 12 }}
```

2020-12-17 18:28 UTC, xin-hedera commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +{{- end }}
```suggestion
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes | nindent 8 }}
{{- end }}
```

also this block is placed at the wrong place, should be before:

```yaml
{{- if not .Values.persistence.enabled }}
```

2020-12-17 18:33 UTC, steven-sheehy commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +{{- end }}
Good catch. Those collapsed diffs make it hard to see.

2020-12-21 17:18 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                create user :grpcuser with login password :'grpcpassword';
Seems to function without it

2020-12-21 17:33 UTC, Nana-EC commented on charts/README.md
> +    Then update the `values/yaml` file to set the `network`, `initialAddressBook`, `extraVolumes` and `extraVolumeMounts` configs.
The `values.yaml` file already exists though. Or do you mean a separately named files in which they'd also have to be sure to add the necessary properties  like the way `values-prod.yaml` does.

2020-12-21 17:49 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +          image: postgres:11-alpine
Updated

2020-12-21 17:50 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              while ! pg_isready -U postgres -h mirror-timescaledb-data; do sleep 1; done;
Updated

2020-12-21 17:50 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                SELECT format('CREATE DATABASE %I', :'dbname')
Fixed

2020-12-21 17:50 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                create user :dbuser with createrole password :'dbpassword';
Updated

2020-12-21 17:50 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +  dbuser: "{{ .Values.importer.config.hedera.mirror.importer.db.username }}"
Removed

2020-12-21 17:50 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +
Done

2020-12-21 17:51 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                alter default privileges in schema public grant select on tables to :grpcuser;
Used a viewer role

2020-12-21 17:51 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              echo "${CREATE_API_USERS_SQL_COMMAND}" | psql --file=- --echo-queries -d "${ACCESS_SVC_CONNSTR_MAIN_USER}" \
Done

2020-12-21 17:51 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +{{ toYaml .Values.extraVolumeMounts | indent 12 }}
Updated

2020-12-21 17:51 UTC, Nana-EC commented on charts/README.md
> +$ kubectl delete $(kubectl get pvc, ep, service -l release="${RELEASE}" -o name)
Reverted but added the `-l release="${RELEASE}"`

2020-12-21 17:52 UTC, Nana-EC commented on charts/README.md
> +
Removed

2020-12-21 17:52 UTC, Nana-EC commented on charts/README.md
> +    $ kubectl create secret generic mirror-importer-addressbook --from-file=perf.bin=/Downloads/perf.bin --save-config=true
Removed

2020-12-21 17:52 UTC, Nana-EC commented on charts/README.md
> +         - name: addressbook-secret-volume
Removed

2020-12-21 17:52 UTC, Nana-EC commented on charts/README.md
> +    Then update the `values/yaml` file to set the `network`, `initialAddressBook`, `extraVolumes` and `extraVolumeMounts` configs.
Updated

2020-12-21 17:52 UTC, Nana-EC commented on charts/README.md
> +    $ helm repo add hedera https://hashgraph.github.io/hedera-mirror-node/charts
Reverted and added a configuration sub sub section

2020-12-21 17:52 UTC, Nana-EC commented on charts/README.md
> +    When running against a network other than the demo/testnent/mainnet network, the network must be updated and an initialAddressBook file must be provided.
Updated

2020-12-21 17:53 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +{{ toYaml .Values.extraVolumeMounts | indent 12 }}
Updated

2020-12-21 17:53 UTC, Nana-EC commented on charts/hedera-mirror-importer/templates/statefulset.yaml
> +{{- end }}
Updated

2020-12-21 19:11 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +            - >
Hitting issues on the pipe fail option
```
set: Illegal option -o pipefail
```
Will look into it

2020-12-21 19:25 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +            - >
pipefial shouldn't be needed with updated call logic that call the file secret

2020-12-21 19:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              value: host=mirror-timescaledb user=postgres connect_timeout=3 sslmode=disable password={{ .Values.timescaledb.credentials.accessNode.superuser }}
host needs to be templated with release name. Since it's used in multiple places, might be good to move to function in helpers

2020-12-21 19:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +apiVersion: batch/v1
if timescale enabled

2020-12-21 19:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    {{- $importerpassword := .Values.importer.config.hedera.mirror.importer.db.password }}
Some variable names all lower, some camel case. Would be good to standardize on camel case.

2020-12-21 19:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    create extension pg_stat_statements;
if not exists

2020-12-21 19:54 UTC, steven-sheehy commented on charts/README.md
> +1. Set the following config values in `values.yaml` as noted below
This section would make more sense in the configuration section above instead of a random separate section. So you'd have sections that look like:

- Install
- Configure
  - TimescaleDB
  - Custom address book
- Testing

2020-12-21 19:54 UTC, steven-sheehy commented on charts/README.md
> -The above command does not delete any of the underlying persistent volumes. To delete all the data associated with this release:
We should keep the delete chart separate from the delete data like it was. Deleting the chart is recoverable but deleting the data is not and we should warn users sufficiently about the seriousness of the action.

2020-12-21 19:54 UTC, steven-sheehy commented on charts/README.md
> +$ kubectl delete $(kubectl get pvc -l release="${RELEASE}" -o name)
I take that back, release is not a standard label applied to all kubernetes objects, hence why you're having to add an explicit delete for the importer pvc. I think the original `kubectl delete $(kubectl get pvc -o name)` would be simpler and more future-proof.

2020-12-21 19:54 UTC, steven-sheehy commented on charts/README.md
> +    Then update the `values/yaml` file to set the `network`, `initialAddressBook`, `extraVolumes` and `extraVolumeMounts` configs.
I think Xin is saying not to recommend users update the values.yaml but to create their own custom yaml file like `custom.yaml`.

2020-12-21 19:57 UTC, steven-sheehy requested changes

2020-12-21 19:57 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    create database {{ $dbname }};
Does this job run on every helm release? If so, this init.sql needs to be made safe to be re-ran multiple times by adding if not exists or other mechanisms to keep it from failing on subsequent executions.

2020-12-21 23:02 UTC, xin-hedera requested changes

2020-12-22 01:19 UTC, Nana-EC commented on charts/README.md
> +    Then update the `values/yaml` file to set the `network`, `initialAddressBook`, `extraVolumes` and `extraVolumeMounts` configs.
Noting a new file works for me

2020-12-22 02:07 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    create database {{ $dbname }};
No, it runs once. The job won't run again after it's completed unless it's deleted and another release is pushed

2020-12-22 02:47 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    create database {{ $dbname }};
I think adding a `post-install` hook should work. That should ensure 1. it runs after resources are created, 2. It runs only on install

2020-12-22 02:57 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              value: host=mirror-timescaledb user=postgres connect_timeout=3 sslmode=disable password={{ .Values.timescaledb.credentials.accessNode.superuser }}
Updated using a helpers function

2020-12-22 02:57 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +apiVersion: batch/v1
Added

2020-12-22 02:57 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    {{- $importerpassword := .Values.importer.config.hedera.mirror.importer.db.password }}
Standardized

2020-12-22 02:57 UTC, Nana-EC commented on charts/README.md
> +1. Set the following config values in `values.yaml` as noted below
Reorganized

2020-12-22 02:58 UTC, Nana-EC commented on charts/README.md
> -The above command does not delete any of the underlying persistent volumes. To delete all the data associated with this release:
Separated

2020-12-22 02:58 UTC, Nana-EC commented on charts/README.md
> +$ kubectl delete $(kubectl get pvc -l release="${RELEASE}" -o name)
Good catch, updated

2020-12-22 02:58 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    create database {{ $dbname }};
Added post-install and verified upgrades don't call the job again

2020-12-22 02:58 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +      cpu: 2Gi
Updated

2020-12-22 02:59 UTC, Nana-EC commented on charts/README.md
> +    ```
Fixed

2020-12-22 16:34 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    alter default privileges for role {{ $importerUser }} in schema public grant select on tables to viewer;
`alter default privileges in schema public grant select on tables to viewer;`

2020-12-22 16:34 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    grant select on all tables in schema public to viewer;
This does not create a read only user. Because the viewer role inherits from public, he has permissions to create objects. This is also why it works without grant connect currently. 

We need to revisit these permissions completely. We should revoke all permissions from public first. Then we should create readonly and readwrite roles then assign those to users appropriately. Maybe we can do this in a follow up.

2020-12-22 18:02 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    grant select on all tables in schema public to viewer;
I'm my next PR, creating the scripts I'm creating the tables in a new schema.
I can open a ticket to focus on fixing the privileges for the users outside of these PR.
These will also be easier to confirm as they'll follow or be in conjunction with testing.

2020-12-22 18:15 UTC, steven-sheehy approved these changes
LGTM. Can address permissions in follow up.

2020-12-22 19:02 UTC, xin-hedera approved these changes
LGTM

2020-12-22 19:06 UTC, merged