Support additional pg pool config params
hashgraph/hedera-mirror-node pull request #1363
Opened 2020-12-15 21:45 UTC by xin-hedera

**Detailed description**:
Support pg pool configuration params connectionTimeoutMillis, max, and statement_timeout.

**Which issue(s) this PR fixes**:
Relates to #1295 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2020-12-15 23:01 UTC, steven-sheehy requested changes

2020-12-16 00:25 UTC, steven-sheehy approved these changes

2020-12-16 03:38 UTC, steven-sheehy approved these changes

2020-12-16 07:23 UTC, Nana-EC approved these changes
LGTM

2020-12-16 14:29 UTC, merged