TimescaleDB: Add psql to timescaledb migration scripts
hashgraph/hedera-mirror-node pull request #1364
Opened 2020-12-16 07:29 UTC by Nana-EC

**Detailed description**:
Mirror node using existing v1 schema will need to migrate from a postgres db to a new timescaledb.
We should offer some scripts to help operators migrate with ease

- Add a `csvBackupTables.sql` file that backs up v1 tables to separate csv files for future restore
- Add a `createHyperTables.sql` file that updated the table schema differences and create Hyper table prior to restore
- Add a `csvRestoreTables.sql` file that uses COPY to restore back files for each of the tables 
- Add a `updateSchema.sql` file that handles schema difference and runs after data migration to ensure data is in sync 
- Add a `migration.config` file that hold the config values for a script to run all the migration steps
- Add a `migration.sh` main script that orchestrates the migration utilizing all the stages
- Add a `init_v2.sql` file that may be used to initiate a timescale db node by creating the database and users with appropriate permissions
- Rename `init.sql` to `init_v1.sql`
- Update the `installation.md` file with instruction on timescaledb setup
- Update the `operations.md` file with instructions on v1 to v2 migration procedure
- Update importer config with concept of importer user that differs from owner user
- Update helm chart to support deployment of timescaledb with new  custom schema 

**Which issue(s) this PR fixes**:
Fixes #1309 

**Special notes for your reviewer**:
Verified flow in
- local postgres docker instance to local timescaledb instance

To-do:
- GCP cloud sql to GKE - May need additional work to setup secrets, IAM access etc

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-12-29 17:25 UTC, steven-sheehy requested changes

2020-12-29 17:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant select on all tables in schema :schema_name to :importer_user;
I don't see how importer_user and viewer have any different permissions. It looks like to me they both can read/write. You probably need to revoke permissions on the schema first.

2020-12-29 17:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/createHyperTables.sql
> +-- Create hyper tables from v1 schema, inserts from old table, add indexes
This file is a duplicate of `V2.0.1__hyper_tables.sql`. Why can't we simply invoke that?

2020-12-29 17:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/csvBackupTables.sql
> +\copy (select * from account_balance) to account_balance.csv delimiter ',' csv;
Does it speed up things or help TimescaleDB if we order by primary key ascending?

2020-12-29 17:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/timeScaleDbMigration.sh
> +PGPASSWORD=${OLD_PASSWORD} pg_dump -h $OLD_DB_HOST -p $OLD_DB_PORT -U $OLD_DB_USER --table public.flyway_schema_history -f mirror_node_${start_time}.bak mirror_node
Why not simply add flyway_schema_history to backup/restore? I don't see why it needs to be treated special as Flyway is not running at any point during this migration.

2020-12-29 17:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/alterSchema.sql
> +select setval('record_file_id_seq', (select max(id) from record_file));
Should consider removing some of these sequences if possible in the future.

2020-12-29 17:25 UTC, steven-sheehy commented on docs/operations.md
> +    $ ./scripts/time-scale-migration/timeScaleDbMigration.sh
Seems a bit verbose and duplicates TimescaleDB. What about `scripts/timescaledb/migrate.sh`?

2021-01-04 16:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/createHyperTables.sql
> +-- Create hyper tables from v1 schema, inserts from old table, add indexes
Yes, looking at a way to share these. 
Issue is V2.0.1__hyper_tables.sql uses flyway placeholders which I don't think you can tap into outside of flyway.
Currently, either I remove the placeholders and remove the ability to config the chunk sizes or I do this code repetition.

I could have a default value and then potentially pick up the placeholders if they are present. Thoughts?

2021-01-04 16:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/alterSchema.sql
> +select setval('record_file_id_seq', (select max(id) from record_file));
Agreed

2021-01-04 16:35 UTC, Nana-EC commented on docker-compose.override.yml
> +version: "3.3"
Good approach. I prefer this also

2021-01-04 16:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/timeScaleDbMigration.sh
> +    echo "Old db primary user password is not set. Please configure OLD_PASSWORD in migration.config file and rerun './timeScaleDbMigration.sh'"
Will update to stay with just "Old" and "New"

2021-01-04 16:55 UTC, Nana-EC commented on docs/operations.md
> +   It then utilizes the migration sql script used by normal flyway operations to create the new tables and then creates the Timescale hyper tables based on these.
Will update to use `TimescaleDB` and `timescaledb` only

2021-01-04 16:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/createHyperTables.sql
> +-- Create hyper tables from v1 schema, inserts from old table, add indexes
You invoke it from bash, right? Just use sed to replace

2021-01-04 17:34 UTC, Nana-EC commented on docs/operations.md
> +1. Setup a new database container using TimeScale
There's a section in `Installation.md` for PostgreSQL. I can note that as V1 and add a V2 section for `TimescaleDB`.
Will refer to that from here, and with the removal of the override file this should be simpler

2021-01-04 17:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +drop extension if exists timescaledb;
The installed extension is not available to the new schema. 
Trying to install it for the new schema will fail since it's already installed.
Therefore had to uninstall as super user reinstall in needed schema.

2021-01-04 18:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant connect on database :db_name to viewer;
Does this not also need to be done for the `importer_user `?

2021-01-04 20:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +drop extension if exists timescaledb;
Since the timescaledb extension was installed into the public schema it originally wasn't available to the new schema.
I think I can work around this though and not need to delete and create.

2021-01-04 20:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant connect on database :db_name to viewer;
Actually no, create user assumes login so connection is authorized, whereas role doesn't make that assumption so you have to explicitly grant it. 
Good question though, I had to verify documentation at https://www.postgresql.org/docs/9.6/sql-createuser.html

2021-01-04 21:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/timeScaleDbMigration.sh
> +PGPASSWORD=${OLD_PASSWORD} pg_dump -h $OLD_DB_HOST -p $OLD_DB_PORT -U $OLD_DB_USER --table public.flyway_schema_history -f mirror_node_${start_time}.bak mirror_node
So this is simply to avoid having to write a script that explicitly does a create table for the `flyway_schema_history` table.
Since I'm trying to reuse the `V2.0.0__time_scale_init.sql` I have to account for that table not being present as flyway creates it.
So it was either create an additional script file to run before step 5 or add logic to this script file to handle that.

2021-01-04 21:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/csvBackupTables.sql
> +\copy (select * from account_balance) to account_balance.csv delimiter ',' csv;
Let me try, one way to speed up would be to drop indexes on the old db but I'm not sure we want to force that on migrators as they'd then also need to wait on the recreation of those indexes

2021-01-04 21:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/csvBackupTables.sql
> +\copy (select * from account_balance) to account_balance.csv delimiter ',' csv;
Tried it on my smaller data set and it actually made the migration take a few seconds longer, which I did not expect.
Was actually thinking of simplifying this and just using the table name instead of the select statement.

2021-01-04 21:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    id                 serial,
We can but this isn't for the chunk logic.
This was added to maintain consistency between the v1 and v2. Just like we preserve the id in the `address_book_entry` and `record_file` table.
In all 3 cases we'll aim to drop them in a future v2 migration.

2021-01-04 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant connect on database :db_name to viewer;
Cool, I figured it had to work somehow, thanks for the clarification.

2021-01-04 22:33 UTC, Nana-EC commented on docker-compose.yml
> +  tsdb:
Updated

2021-01-04 22:33 UTC, Nana-EC commented on docker-compose.override.yml
> +version: "3.3"
Removed this file

2021-01-04 22:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +-- init the timescale db mirror node db
Updated

2021-01-04 22:33 UTC, Nana-EC commented on docker-compose.yml
> +      - 6432:5432
Updated

2021-01-04 22:33 UTC, Nana-EC commented on docs/operations.md
> -
Reverted

2021-01-04 22:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/timeScaleDbMigration.sh
> +    echo "Old db primary user password is not set. Please configure OLD_PASSWORD in migration.config file and rerun './timeScaleDbMigration.sh'"
Updated

2021-01-04 22:34 UTC, Nana-EC commented on docs/operations.md
> +   It then utilizes the migration sql script used by normal flyway operations to create the new tables and then creates the Timescale hyper tables based on these.
Updated

2021-01-04 22:34 UTC, Nana-EC commented on docs/operations.md
> +1. Setup a new database container using TimeScale
Updated

2021-01-04 22:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +drop extension if exists timescaledb;
Fixed

2021-01-04 22:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +create user :db_owner with login createrole password :'owner_password';
Fixed

2021-01-04 22:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant all privileges on all tables in schema :schema_name to :db_owner;
Not needed, updated.

2021-01-04 22:35 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +create role viewer;
I like this, updated as such

2021-01-04 22:35 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant select on all tables in schema :schema_name to :importer_user;
rewrote this and tested, reader can only select, writer can insert etc

2021-01-04 22:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/createHyperTables.sql
> +-- Create hyper tables from v1 schema, inserts from old table, add indexes
Good idea.
Updated.
Initial did 2 sed's but will update to 
```
sed -e 's/${chunkTimeInterval}/'$CHUNK_INTERVAL_TIME'/g' -e 's/${chunkIdInterval}/'$CHUNK_INTERVAL_ID'/g' migration/v2/V2.0.1__hyper_tables.sql >scripts/timescaledb/createHyperTables.sql
```

2021-01-04 22:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/time-scale-migration/alterSchema.sql
> +select setval('record_file_id_seq', (select max(id) from record_file));
I believe the plan is in a future v2 migration remove the id's from these tables and then remove the sequences

2021-01-04 22:40 UTC, Nana-EC commented on docs/operations.md
> +    $ ./scripts/time-scale-migration/timeScaleDbMigration.sh
Updated

2021-01-05 16:44 UTC, xin-hedera requested changes

2021-01-05 16:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>      on token (token_id);
in v1, `token_id` is the primary key, will changing it to an index in v2 drop the unique constraint?

2021-01-05 17:01 UTC, xin-hedera commented on docker-compose.yml
> +    image: timescaledev/timescaledb-ha:pg12-ts2.0.0-rc3
there is a production release pushed yesterday: timescaledev/timescaledb-ha:pg12.5-ts2.0.0-p0

2021-01-05 17:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists transaction__payer_account_id
I thought I'd already pushed the `if not exists` addition.
But I'll add the index correction also. Thanks

2021-01-05 17:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>      on token (token_id);
Good catch, this should be a unique index to prevent duplicates.
Maybe also unique across `token_id` and `created_timestamp`

2021-01-05 17:17 UTC, Nana-EC commented on docker-compose.yml
> +    image: timescaledev/timescaledb-ha:pg12-ts2.0.0-rc3
Yes will be pushing this shortly, thanks

2021-01-05 17:23 UTC, Nana-EC commented on docker-compose.yml
> +    image: timescaledev/timescaledb-ha:pg12-ts2.0.0-rc3
Updated

2021-01-05 17:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>      on token (token_id);
Updated and added

2021-01-05 17:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>      add constraint account_balance_file_timestamp primary key (consensus_timestamp);
Reorganized

2021-01-05 17:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists transaction__payer_account_id
Added

2021-01-05 17:23 UTC, Nana-EC commented on docker-compose.yml
> +      - ./hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql/:/docker-entrypoint-initdb.d/init_v2.sql
Updated

2021-01-05 17:49 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +          image: timescale/timescaledb:2.0.0-pg12
To keep it dry, please change it to use the templated helm image from the statefulset

2021-01-05 18:29 UTC, steven-sheehy requested changes

2021-01-05 18:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +\set db_port 6432
5432

2021-01-05 18:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant insert, update, delete on all tables in schema :schema_name to readwrite;
I don't think the importer ever deletes rows, right?

2021-01-05 18:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    id                 serial,
I see, this looks to be a mistake in v1. I only checked the domain object which does not have the `id` modeled. Instead it is using an `@EmbeddedId` with a composite primary key. We should add a v1 migration to remove this `id` and undo the v2 change.

2021-01-05 19:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant insert, update, delete on all tables in schema :schema_name to readwrite;
Correct, will remove `delete`

2021-01-05 19:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +\set db_port 6432
Left over from local tests, will revert to `5432`

2021-01-05 23:39 UTC, ijungmann commented on docs/installation.md
> +In both cases the only setup required is to create the initial database, users, schema, extensions and ensure all
nit:
```suggestion
In both cases the only setup required is to create the initial database, users, schema, and extensions, and ensure all
```

2021-01-05 23:43 UTC, ijungmann commented on docs/installation.md
> +        #      replicas: 0
Should these still be commented out?

2021-01-05 23:47 UTC, ijungmann commented on docs/operations.md
> +1. Setup a new TimescaleDB database
```suggestion
1. Set up a new TimescaleDB database
```

2021-01-05 23:49 UTC, ijungmann commented on docs/operations.md
> +   The script uses successive `psql` connections to backup, configure and restore data on the new database nodes.
```suggestion
   The script uses successive `psql` connections to back up, configure and restore data on the new database nodes.
```

2021-01-05 23:53 UTC, ijungmann commented on docs/operations.md
> +   It then utilizes the migration sql script used by normal flyway operations to create the new tables and then creates the Timescale hyper tables based on these.
nit: I believe hypertable is always one word.
'```suggestion
   It then utilizes the migration sql script used by normal flyway operations to create the new tables and then creates the Timescale hypertables based on these.
```

2021-01-05 23:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/migration.sh
> +echo "4. Creating new hyper tables on TimescaleDB($NEW_DB_HOST:$NEW_DB_PORT)..."
nit:
```suggestion
echo "4. Creating new hypertables on TimescaleDB($NEW_DB_HOST:$NEW_DB_PORT)..."
```

2021-01-06 18:40 UTC, Nana-EC commented on docs/installation.md
> +        #      replicas: 0
Yes, I'm suggesting to the user how they might enable timescaledb. 
Maybe I should be more explicit or maybe make this a strikethrough to show they should remove it instead

2021-01-06 20:53 UTC, ijungmann commented on docs/installation.md
> +        #      replicas: 0
I'm okay with it as long as it's valid, just making sure this was correct.

2021-01-06 23:11 UTC, Nana-EC commented on docs/installation.md
> +In both cases the only setup required is to create the initial database, users, schema, extensions and ensure all
This took me on an refreshing grammar clarification tangent.
First, I thought "I'm fine with the Oxford comma but not sure about the additional `and`"
Then post research I thought "the `and` is useful and the Oxford comma isn't necessary since there's only 2 clauses i.e. creating ... and ensuring ..."

Going go with the later, here's a useful link - https://www.grammarly.com/blog/comma/

2021-01-06 23:21 UTC, Nana-EC commented on docs/installation.md
> +In both cases the only setup required is to create the initial database, users, schema, extensions and ensure all
Better yet.
---
For both databases, since [Flyway](https://flywaydb.org) will manage the database schema, the only required setup steps include:
* creating the database, users, schema, and extensions.
* ensuring all permissions are set.

2021-01-06 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    id                 serial,
Fixed this

2021-01-06 23:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +\set db_port 6432
Reverted

2021-01-06 23:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v2.sql
> +grant insert, update, delete on all tables in schema :schema_name to readwrite;
Removed

2021-01-06 23:31 UTC, Nana-EC commented on docs/installation.md
> +        #      replicas: 0
Added comments to be more explicit

2021-01-06 23:31 UTC, Nana-EC commented on docs/operations.md
> +1. Setup a new TimescaleDB database
Updated

2021-01-06 23:31 UTC, Nana-EC commented on docs/operations.md
> +   The script uses successive `psql` connections to backup, configure and restore data on the new database nodes.
Updated

2021-01-06 23:31 UTC, Nana-EC commented on docs/operations.md
> +   It then utilizes the migration sql script used by normal flyway operations to create the new tables and then creates the Timescale hyper tables based on these.
Fixed

2021-01-06 23:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/migration.sh
> +echo "4. Creating new hyper tables on TimescaleDB($NEW_DB_HOST:$NEW_DB_PORT)..."
Fixed

2021-01-07 15:48 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              while ! pg_isready -U postgres -h {{ include "hedera-mirror.dbHost" . }}-data; do sleep 1; done;
duplicate? the readiness test should have passed at line 23.
same on line 33

2021-01-07 16:32 UTC, ijungmann commented on docs/installation.md
> +In both cases the only setup required is to create the initial database, users, schema, extensions and ensure all
Fair point, I can get a little heavy-handed with commas at times.  I like the solution you went with.

2021-01-07 16:57 UTC, steven-sheehy requested changes
Still reviewing

2021-01-07 16:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists transaction_consensus_ns
a) this should be a primary key b) create_hypertable should already create this for us

2021-01-07 16:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on token (token_id, created_timestamp);
This index does not exist in v1. created_timestamp is already unique and should not be added to another field to make a composite key. There should just be an unique index on token_id

2021-01-07 16:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.0__drop_token_account_id.sql
> +    drop constraint token_account_pkey;
Since we're dropping the constraint it might also transitively drop the index. Can we verify that the token_id still has a unique index after this?

2021-01-07 16:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> +        owner: mirror_node
These need to be added to config docs.

2021-01-07 16:57 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                  items:
We don't need to project every file in the secret. Just mount the entire secret as you were doing. This way is brittle and verbose.

2021-01-07 16:57 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +            - name: DB_USERS_FILE
These don't provide any value as env variables since they're only invoked once, they just make it more verbose. If anything, a `initDir=/usr/etc/db-init` variable inline in the script would help to keep it more DRY and readable.

2021-01-07 16:57 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> -    "helm.sh/hook-delete-policy": hook-succeeded
Why are we removing this? Don't we want to remove the job after success?

2021-01-07 16:59 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> -    "helm.sh/hook-delete-policy": hook-succeeded
Was debugging and removed this so I could see the logs from the pod, will restore

2021-01-07 17:07 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              while ! pg_isready -U postgres -h {{ include "hedera-mirror.dbHost" . }}-data; do sleep 1; done;
Intentionally duplicated  due to previous logic I was exploring but will remove as it's no longer needed

2021-01-07 17:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists transaction_consensus_ns
Left over, yes `create_hypertable` will add index for `consensus_ns`

2021-01-07 17:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>      on token_account (token_id, account_id, created_timestamp);
We do not in v1, however in v2 any column that's used for chunking has to be in the indexes of a table due to partitioning requirements.

"To define an index as UNIQUE or PRIMARY KEY, the time column and, if it exists, the partitioning column must be part of the index."
See https://docs.timescale.com/latest/using-timescaledb/schema-management#indexing-best-practices

2021-01-07 18:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> -alter table if exists token_account
The indexes created by TimescaleDB are not primary keys.
The are just basic index.
This means to make it a primary key after the fact we'd have to
1. in `V2.0.2__time_scale_index_init.sql` add a primary key and drop the index created by TimescaleDB
2. set `create_default_indexes` param in `create_hypertable` to false in `V2.0.1__hyper_tables.sql` and just create the primary key here in `V2.0.2__time_scale_index_init.sql`
3.  Update `V2.0.0__time_scale_init.sql` with primary key flags in the table create.

I was trying to keep all constraint creations in file `V2.0.2__time_scale_index_init.sql` but it makes sense to have primary key in the initial table declaration so I'll go with #3

2021-01-07 18:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.0__drop_token_account_id.sql
> +create unique index if not exists token_account__created_timestamp
Yep, will update

2021-01-07 18:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.0__drop_token_account_id.sql
> +alter table token_account
Will add

2021-01-07 18:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> -alter table if exists token_account
Will do for all tables. This will break a few tests add the primary key has moved from id to timestamp in some cases

2021-01-07 18:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on token (token_id, created_timestamp);
Same notion as before, it didn't exist in v1 but needs to in v2 because of partitioning requirements

2021-01-07 20:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.0__drop_token_account_id.sql
> +    drop constraint token_account_pkey;
Verified unique index still remains

2021-01-07 21:38 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              while ! pg_isready -U postgres -h {{ include "hedera-mirror.dbHost" . }}-data; do sleep 1; done;
Removed, along with the sleeps

2021-01-07 21:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.0__drop_token_account_id.sql
> +create unique index if not exists token_account__created_timestamp
Updated

2021-01-07 21:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.0__drop_token_account_id.sql
> +alter table token_account
Added

2021-01-07 21:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> -alter table if exists token_account
Added all missing primary keys and did a comparison to v1 to make sure they were in sync

2021-01-07 21:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists transaction_consensus_ns
Removed and removed `consensus_ns` from `transaction__payer_account_id` index as it's not required to be added

2021-01-07 21:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +        owner: mirror_node
Added to config doc

2021-01-07 21:42 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                  items:
Reverted to what I had before

2021-01-07 21:43 UTC, Nana-EC commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +            - name: DB_USERS_FILE
Added a `DB_INIT_DIR` variable and used inline as recommended

2021-01-07 23:03 UTC, steven-sheehy requested changes

2021-01-08 00:44 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb.yaml
> +    {{- $dbName := .Values.importer.config.hedera.mirror.importer.db.name }}
Good to know, moved them all up under the top file

2021-01-08 00:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +-- live_hash, desc index on consensus_timestamp already created by hypertable
Added this primary key

2021-01-08 00:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +-- file_data, desc index on consensus_timestamp already created by hypertable
Added this primary key

2021-01-08 16:15 UTC, steven-sheehy approved these changes
LGTM

2021-01-08 17:01 UTC, xin-hedera approved these changes
LGTM

2021-01-08 17:02 UTC, ijungmann approved these changes

2021-01-08 17:48 UTC, merged