Add monitor documentation
hashgraph/hedera-mirror-node pull request #1372
Opened 2020-12-17 22:55 UTC by steven-sheehy

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1219

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2020-12-17 23:01 UTC, steven-sheehy commented on README.md
> +Hedera Mirror Node exposes Hedera Hashgraph transactions, transaction records, account balances, and events generated by
Markdown files were auto formatted by Intellij. I only touched a few lines of this file to update list of components to include monitor. I do think the changes it did are an improvement as it properly wrapped lines and reduced extra indentation.

2020-12-18 17:02 UTC, xin-hedera requested changes

2020-12-18 18:22 UTC, steven-sheehy commented on docs/monitor.md
> +The monitor can be configured to publish multiple transaction types concurrently. It does this be specifying a list of
Updated

2020-12-18 18:22 UTC, steven-sheehy commented on docs/monitor.md
> +First, make sure you are configured to talk to the correct Hedera network by setting `hedera.mirror.monitor.network` to
Updated

2020-12-18 18:22 UTC, steven-sheehy commented on docs/monitor.md
> +seconds to it and verifies the messages is received via the mirror node's gRPC and REST APIs.
Updated

2020-12-18 18:51 UTC, ijungmann requested changes
Mostly nits, some are just Oxford commas that may not be the style we use.

2020-12-18 18:51 UTC, ijungmann commented on docs/monitor.md
> +and `hedera.mirror.monitor.nodes` and `hedera.mirror.monitor.mirrorNode` properties should be filled in.
```suggestion
`MAINNET`, `PREVIEWNET` or `TESTNET`. If you are not using one of these public environments, the network can be set to `OTHER`,
and `hedera.mirror.monitor.nodes` and `hedera.mirror.monitor.mirrorNode` properties should be filled in.
```

2020-12-18 18:51 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.publish.connections`                 | 5          | How many total connections to open to the main nodes. Connections will be round robin among available nodes
Something about that last sentence is throwing me off, but I can't figure out a great rephrase.  Maybe
`Connections will be established in a round-robin fashion among available nodes`?

2020-12-18 18:51 UTC, ijungmann commented on docs/monitor.md
> +The monitor can automatically create account, token or topic entities on application startup using a special expression
```suggestion
The monitor can automatically create account, token, and topic entities on application startup using a special expression
```

2020-12-18 18:51 UTC, ijungmann commented on docs/monitor.md
> +The syntax takes the form of `${type.name}` where `type` is one of `account`, `token` or `topic` and `name` is a
```suggestion
The syntax takes the form of `${type.name}` where `type` is one of `account`, `token`, or `topic`, and `name` is a
```

2020-12-18 18:51 UTC, ijungmann commented on docs/monitor.md
> +The monitor can optionally subscribe to either the mirror node gRPC or REST APIs. Each subscription type can have one or
It can do both at the same time if desired, right?

2020-12-18 18:51 UTC, ijungmann commented on docs/monitor.md
> +more scenarios. For the REST API, it can verify a percentage of individual transactions have made it to the mirror node
```suggestion
more scenarios. For the REST API, it can verify that a percentage of individual transactions have made it to the mirror node
```

2020-12-18 18:51 UTC, ijungmann commented on docs/configuration.md
> +The four components of the Hedera Mirror Node (Importer, Monitor, REST API and gRPC API) all support loading
```suggestion
The four components of the Hedera Mirror Node (Importer, Monitor, REST API, and gRPC API) all support loading
```

2020-12-18 18:51 UTC, ijungmann commented on docs/installation.md
> +To run the GRPC API, first populate the configuration at one of the supported
```suggestion
To run the monitor, first populate the configuration at one of the supported
```

2020-12-18 18:51 UTC, ijungmann commented on docs/monitor.md
> +class that it references. From there, you can see that fields `maxTransactionFee`, `message`, `retry`
```suggestion
class that it references. From there, you can see that fields `maxTransactionFee`, `message`, `retry`,
```

2020-12-18 20:22 UTC, steven-sheehy commented on docs/monitor.md
> +and `hedera.mirror.monitor.nodes` and `hedera.mirror.monitor.mirrorNode` properties should be filled in.
Updated

2020-12-18 20:22 UTC, steven-sheehy commented on docs/monitor.md
> +seconds to it and verifies the messages is received via the mirror node's gRPC and REST APIs.
Updated

2020-12-18 20:22 UTC, steven-sheehy commented on docs/monitor.md
> +The monitor can automatically create account, token or topic entities on application startup using a special expression
Updated

2020-12-18 20:23 UTC, steven-sheehy commented on docs/monitor.md
> +The syntax takes the form of `${type.name}` where `type` is one of `account`, `token` or `topic` and `name` is a
Updated

2020-12-18 20:23 UTC, steven-sheehy commented on docs/monitor.md
> +The monitor can optionally subscribe to either the mirror node gRPC or REST APIs. Each subscription type can have one or
Updated to make that clear

2020-12-18 20:24 UTC, steven-sheehy commented on docs/monitor.md
> +more scenarios. For the REST API, it can verify a percentage of individual transactions have made it to the mirror node
Updated

2020-12-18 20:24 UTC, steven-sheehy commented on docs/monitor.md
> +class that it references. From there, you can see that fields `maxTransactionFee`, `message`, `retry`
Updated

2020-12-18 20:25 UTC, steven-sheehy commented on docs/configuration.md
> +The four components of the Hedera Mirror Node (Importer, Monitor, REST API and gRPC API) all support loading
Updated

2020-12-18 20:26 UTC, steven-sheehy commented on docs/configuration.md
> +`hedera.mirror.monitor.publish.connections`                 | 5          | How many total connections to open to the main nodes. Connections will be round robin among available nodes
Updated

2020-12-18 20:26 UTC, steven-sheehy commented on docs/installation.md
> +To run the GRPC API, first populate the configuration at one of the supported
Fixed

2020-12-18 20:38 UTC, ijungmann approved these changes

2020-12-18 20:53 UTC, xin-hedera approved these changes
LGTM

2020-12-18 21:33 UTC, merged