Refactor Record File Reader
hashgraph/hedera-mirror-node pull request #1382
Opened 2020-12-21 22:30 UTC by xin-hedera

**Detailed description**:

- Add interface `RecordFileReader`
- Implement `RecordFileReaderImplV1` and `RecordFileReaderImplV2` for version 1 and version 2 record files
- Implement `CompositeRecordFileReader`

**Which issue(s) this PR fixes**:
Fixes #1369 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2020-12-22 17:26 UTC, ijungmann commented
I'll give it a second look but it seems all good to me.  Couple of code smells though.

2020-12-22 17:48 UTC, Nana-EC reviewed
1st pass. Looking good.
One suggesting on the BufferInputStream.

Also, record file reading and parsing is one of the more hidden and intricate flows so I think we should take the time to comment those heavy methods for easy readability and future management.

2020-12-22 17:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractRecordFileReader.java
> +    private void readHeader(DataInputStream dis, RecordFileDigest digest, RecordFile recordFile) throws IOException {
nit: Add method comments, brief overview of what to expect from the header

2020-12-22 17:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractRecordFileReader.java
> +    private void readBody(DataInputStream dis, RecordFileDigest digest, Consumer<RecordItem> itemConsumer,
nit: Add method comments, brief overview of what to expect from the body

2020-12-22 17:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +    private final BufferedInputStream bufferedInputStream;
q: I see the BufferedInputStream creation repeated in a few places. Do you think it's worth centralizing that here by making this non final and a LazyGetter.
So you'd create a new StreamFileData object passing in a File instead of fileName, it could then set the `fileName` in the constructor and then on demand getting could return `bufferedInputStream`

2020-12-22 18:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +    private final BufferedInputStream bufferedInputStream;
I don't see the benefit doing so.

In all places StreamFileData is used, data is always read from it after `BufferedInputStream` is created so lazygetter just defers the creation.

On the other side, LazyGetter does complicate resource management, currently it's taken care of by the try-with-resources statement.

2020-12-22 18:38 UTC, steven-sheehy requested changes

2020-12-22 18:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractRecordFileReader.java
> +    protected static final byte RECORD_FILE_MARKER_PREV_HASH = 1;
Can drop the `RECORD_FILE_` prefix since it's now within a record file specific class.

2020-12-22 18:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +        return String.format("v%d/record0.0.3", version);
Use Path instead of format for Windows compatability.

2020-12-22 18:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +    private final static String pathPrefix = "data/recordstreams";
Use Path

2020-12-22 18:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/CompositeRecordFileReader.java
> +        try (DataInputStream dis = new DataInputStream(streamFileData.getBufferedInputStream())) {
Since the passed in `InputStream` will be closed already by this `CompositeRecordFileReader `, we can make it part of the `RecordFileReader` contract/documentation that it will be responsible for closing and clients don't need to use a separate try with resources.

2020-12-22 21:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
The reason for enforcing `BufferedInputStream` instead of the generic `InputStream` is `RecordFileReader` (most likely all stream file readers) needs a `InputStream` which supports `mark` and `reset` so the composite reader can peak the version, rewind it back, and then choose which implementation to parse the stream file.

An `InputStream` may or may not support `mark`/`reset` depending on the concrete subclass.

2020-12-22 21:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
Isn't that even more of a reason for `CompositeRecordFileReader` to create the `BufferedInputStream` instead of relying it be passed in? Technically someone could extend `BufferedInputStream` and re-implement mark/reset to be do nothing.

2020-12-22 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
yes exactly!

2020-12-22 21:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloader.java
> +            throw new FileOperationException("Unable to open record file " + file.getPath(), e);
this is definitely better. however, still have to bubble up / catch the IOException thrown during auto-close...

2020-12-22 21:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
I've gone back and forth on this myself, the actual file parsers need the `BufferedInputStream` created by the Composite in order to actually make use of the reset.  That can be passed as just an `InputStream` to respect the Interface method, but then the various implementations need to either know that the Composite has passed a `BufferedInputStream` without stating it, or you're going to end up wrapping a `BufferedInputStream` in another `BufferedInputStream` at some point.

2020-12-22 21:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
I think some coupling between composite and versioned readers is fine. It's coupling between reader and its clients you want to avoid. Double buffering shouldn't really be a concern and should be caught by code reviews.

2020-12-22 21:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloader.java
> +            throw new FileOperationException("Unable to open record file " + file.getPath(), e);
Which is why I noted that we can make reader be responsible for closing and clients shouldn't use try with resources.

2020-12-22 23:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
I'll push the changes and we can review and discuss. I don't feel it's bad for the Composite to pass a `DataInputStream(BufferedInputStream(InputStream))` to the concrete versioned reader. On the other side, if we choose `BufferedInputStream` over `InputStream` for `StreamFileData` the code looks cleaner and the requirement is made explicitly.

2020-12-23 04:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +    private final BufferedInputStream bufferedInputStream;
Sounds good

2020-12-23 17:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
I think `BufferedInputStream` is the better option.

- make it explicit in the contract that the readers need a buffered input stream for two reasons
   - performance, for when the source of the stream is a disk file and small size reads will be much faster
   - `mark`/`reset` support, since the composite reader needs to peek at the version then rewind the read position
- the implementations will not have the chance to make the mistake of not wrapping a `InputStream` with a `BufferedInputStream`

Regarding the concern of a subclass of `BufferedInputStream` being passed which does not support `mark`/`reset`, it's the subclass which violates the contract of `BufferedInputStream`.

2020-12-23 20:24 UTC, Nana-EC submitted a review, later dismissed
LGTM
Still an open discussion on InputSteam vs BufferedInputStream but as is works.

2020-12-28 21:16 UTC, steven-sheehy requested changes

2020-12-28 21:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV1.java
> +            updateHeader(input);
Bit confusing to call `updateHeader()` for an `updateBody()`. Would either replace with `md.update(input)` or create a new method `private void update(byte... input)` that they call.

2020-12-28 21:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/StreamFileDataTest.java
> +        if (createFile) {
nit: A parameterized test with so many if/else and booleans parameters is harder to follow then separate tests in my opinion. Not saying you have to change it, just want to make the observation.

2020-12-29 16:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractRecordFileReader.java
> +        checkField(prevHash.length, HASH_SIZE, "previous hash size", recordFile.getName());
Nevermind, "previous hash size" looks fine after looking at this again.

2021-01-04 15:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractRecordFileReader.java
> +        dis.readFully(bytes);
readNBytes is a best effort to read up to N bytes and what needed here is read exactly `len` bytes and otherwise errors out

2021-01-04 20:37 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-01-04 20:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +            try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
Just as as followup, I ended up going with the InputStream in my related PR and allowing for a little bit of coupling between the readers, as suggested by Steven.

2021-01-04 21:57 UTC, ijungmann approved these changes
LGTM

2021-01-04 22:41 UTC, Nana-EC approved these changes
LGTM

2021-01-05 15:24 UTC, merged