Refactor signature file reader
hashgraph/hedera-mirror-node pull request #1384
Opened 2020-12-22 01:03 UTC by ijungmann

**Detailed description**:
Refactor Signature File Reader logic to be easier to maintain and add new versions to

**Which issue(s) this PR fixes**:
Fixes #1370 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2020-12-22 19:48 UTC, steven-sheehy requested changes

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +    private final CompositeSignatureFileReader signatureFileReader;
Mark `CompositeSignatureFileReader` as `@Primary` and then can just inject `SignatureFileReader` here.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        nodeAccountIDPubKeyMap = currentAddressBook
Move to a `@Get(lazy = true)` transient field in `AddressBook`.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +    Pair<byte[], byte[]> read(BufferedInputStream bufferedInputStream);
Using Pair is a code smell. The above isn't the interface in the related ticket:

```java
public interface SignatureFileReader {
  FileStreamSignature read(InputStream inputStream);
}
```

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +package com.hedera.mirror.importer.reader.signature;/*
Needs some newlines

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +package com.hedera.mirror.importer.reader.signature;/*
newlines

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                switch (typeDelimiter) {
Let's remove the switch statement and parse them in the order they're supposed to show up in the file. Technically the switch would allow invalid files that had signatures and hashes in the wrong order.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +            byte[] fileHash = new byte[48];
Should be a constant for hash size

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                    case FileDelimiter.SIGNATURE_TYPE_FILE_HASH:
These constants should be moved to this class. FileDelimiter needs to be deleted depending on who's PR gets merged first.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +            switch (version) {
The first int from the file is actually a marker with the value 4. We should probably use an if less than equal to 4 then use V2. Otherwise throw an error. There might actually be a v1 floating around somewhere as well but it should use the same format.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +                    return signatureFileReaderV2.read(bufferedInputStream);
Reader invocation should be done once at the bottom generically for all types.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +        try (DataInputStream dataInputStream =
We shouldn't leak details of using BufferedInputStream to clients. Clients should pass InputStream and BufferedInputStream should be opened here. Javadocs on interface should indicate that read() will close the inputstream so try with resources by the client isn't necessary.

2020-12-22 19:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            } catch (FileNotFoundException e) {
On other PR I mentioned a `Utility.openQuietly(File)` that might be useful to add to not cause IOException be handled.

2020-12-22 19:49 UTC, steven-sheehy reviewed
Please delete `Utility.extractHashAndSigFromFile()`

2020-12-22 19:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +        try (DataInputStream dataInputStream =
Yeah, I have that locally and will be pushing that soon.

2020-12-22 22:02 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +    Pair<byte[], byte[]> read(BufferedInputStream bufferedInputStream);
I can remove the Pair, but is `FileStreamSignature` the right object to return here?  The `NodeSignatureVerifier` is already iterating over an existing list of `FileStreamSignatures` before it calls this, the code would either be building a second set of `FileStreamSignature` that it would have to merge with the original, or it would have to pass in the `FileStreamSignature` it needs to add the signature and hash to.

2020-12-22 22:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +    private final CompositeSignatureFileReader signatureFileReader;
Done

2020-12-22 22:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            } catch (FileNotFoundException e) {
Added this method, had to rework the exception handling as `extractHashAndSigFromFile` was swallowing every type of exception and returning null values, which doesn't work as well with the refactoring.

2020-12-22 22:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +                    return signatureFileReaderV2.read(bufferedInputStream);
Done.

2020-12-22 22:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +    Pair<byte[], byte[]> read(BufferedInputStream bufferedInputStream);
I was actually thinking the `SignatureFileReader.read()` would be moved earlier to `Downloader.downloadSigFiles()`.

```java
    InputStream inputStream = FileUtils.openQuietly(pendingDownload.getFile());
    FileStreamSignature fileStreamSignature = signatureFileReader.read(inputStream);
    fileStreamSignature.setFile(sigFile); // Remove as no longer needed and replace with filename without path for sorting
    fileStreamSignature.setNodeAccountId(nodeAccountId);
    sigFilesMap.put(sigFile.getName(), fileStreamSignature);
```

I think sig files are pretty lightweight we can do this earlier even before reaching 1/3.

2020-12-22 22:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        nodeAccountIDPubKeyMap = currentAddressBook
Done.

2020-12-22 22:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        nodeAccountIDPubKeyMap = currentAddressBook.getNodeAccountIDPubKeyMap();
This should be a local variable

2020-12-22 22:52 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +            switch (version) {
I just reread the file format doc for the new format and noticed the version for the sig file (version 5) is actually in a byte instead of an int.  Just to make sure, the marker with the value 4 is also a byte, or that actually is an int?

2020-12-22 23:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                    case FileDelimiter.SIGNATURE_TYPE_FILE_HASH:
Moved, will delete when PRs are synced up.

2020-12-22 23:02 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +            byte[] fileHash = new byte[48];
Done.

2020-12-22 23:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +            switch (version) {
That seems like an oversight. Let's bring it up with Qian.

2020-12-22 23:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +            switch (version) {
Oh, actually the current marker is a byte as well. That's why we're `byte typeDelimiter = dis.readByte()` in `Utility.extractHashAndSigFromFile()`. So no oversight.

2020-12-22 23:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                switch (typeDelimiter) {
Agreed, took a first pass at refactoring that.

2020-12-22 23:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +package com.hedera.mirror.importer.reader.signature;/*
Fixed, I need to mess with some IntelliJ config to make it stop doing this.

2020-12-22 23:19 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +package com.hedera.mirror.importer.reader.signature;/*
Fixed.

2020-12-23 00:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +    Pair<byte[], byte[]> read(BufferedInputStream bufferedInputStream);
Alright, sure, I did some refactoring to make that work.

2020-12-23 00:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        nodeAccountIDPubKeyMap = currentAddressBook.getNodeAccountIDPubKeyMap();
Moved to local variable

2020-12-23 04:52 UTC, steven-sheehy requested changes

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                                    fileStreamSignature.setNodeAccountId(nodeAccountId);
It seems FileStreamSignature.status of PARSED is no longer relevant and can be removed.

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +            if (version <= 4) {
Should be using the constant from SignatureFileReaderV2

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +     * @return Pair of byte arrays, the left holding the file hash and the right the signature
Javadocs need adjusting

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                throw new IllegalArgumentException("Signature file hash not in correct position");
Shouldn't this throw the signature parse exception you added?

Also, the error message is not really accurate nor does it include the actual value. The old string seemed good enough to me: "Unable to read signature file hash". Would just add the actual value received.

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                throw new IllegalArgumentException("Unable to read signature file hash");
Should add the actual size received and use the signature parse exception

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +            typeDelimiter = dis.readByte();
Shouldn't reuse variables

2020-12-23 04:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +            throw new SignatureFileParsingException("Exception occurred reading signature file", e);
Why are we wrapping the exceptions we throw? We should throw SignatureFileParsingException everywhere and probably only catch IOException and rethrow here.

2020-12-23 06:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                                    fileStreamSignature.setNodeAccountId(nodeAccountId);
Removed.

2020-12-23 06:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +            if (version <= 4) {
Fixed.

2020-12-23 06:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReader.java
> +     * @return Pair of byte arrays, the left holding the file hash and the right the signature
Corrected.

2020-12-23 06:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                throw new IllegalArgumentException("Signature file hash not in correct position");
Yeah, changed the exception to use the new one, corrected the messages and added the values to the exception messages.

2020-12-23 06:26 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +                throw new IllegalArgumentException("Unable to read signature file hash");
Done.

2020-12-23 06:27 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +            typeDelimiter = dis.readByte();
Made new variables and renamed the existing ones to be more clear.

2020-12-23 06:27 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +            throw new SignatureFileParsingException("Exception occurred reading signature file", e);
Done.

2020-12-23 16:37 UTC, ijungmann commented
Still working on tests and code smells, but the logic is all there.

2020-12-23 18:58 UTC, Nana-EC reviewed
Looking good on 1st pass.
Just missing a few tests as highlighted by codecov.
Will circle back for a 2nd pass

2020-12-23 21:24 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Just some tests needed but unblocking my review

2021-01-04 04:46 UTC, ijungmann commented
Added tests for the Composite and V2 reader, will look at the remaining code smells tomorrow.

2021-01-04 16:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/exception/SignatureFileParsingException.java
> +public class SignatureFileParsingException extends ParserException {
Shouldn't extend `ParserException` as signature file reading occurs during download phase. Can just extend `ImporterException` and only implement constructors that are used. This will also help address a code smell.

2021-01-04 16:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2Test.java
> +        FileUtils.writeByteArrayToFile(testFile, newFileBytes);
Don't have to write to a file since input can just be a `ByteArrayInputStream`.

2021-01-04 16:10 UTC, xin-hedera approved these changes
LGTM, just a few recommended format changes.

2021-01-04 16:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +                IOException ex) {
format

2021-01-04 16:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +                     new DataInputStream(new BufferedInputStream(inputStream))) {
format, can fit in one line

2021-01-04 16:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/exception/SignatureFileParsingException.java
> +public class SignatureFileParsingException extends ParserException {
Changed

2021-01-04 16:55 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2Test.java
> +        FileUtils.writeByteArrayToFile(testFile, newFileBytes);
Good call, removed file logic from all tests (except the valid file test)

2021-01-04 17:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                                                .getFile());
Fixed.

2021-01-04 17:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        } catch (SignatureFileParsingException | FileOperationException ex) {
Fixed.

2021-01-04 17:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +                IOException ex) {
Fixed.

2021-01-04 17:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
> +                     new DataInputStream(new BufferedInputStream(inputStream))) {
Fixed.

2021-01-04 17:28 UTC, xin-hedera approved these changes

2021-01-04 17:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReaderTest.java
> +        return new BufferedInputStream(new ByteArrayInputStream(bytes));
nit: You don't need to buffer an in memory byte[]. :)

2021-01-04 18:25 UTC, steven-sheehy submitted a review, later dismissed

2021-01-04 20:26 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReaderTest.java
> +        return new BufferedInputStream(new ByteArrayInputStream(bytes));
Fixed.

2021-01-04 20:38 UTC, steven-sheehy approved these changes
LGTM

2021-01-04 20:43 UTC, xin-hedera approved these changes

2021-01-04 21:17 UTC, merged