Add signature file v5 reader and test
hashgraph/hedera-mirror-node pull request #1413
Opened 2021-01-06 18:54 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:
Add signature file reader v5 to support new signature file version.

**Which issue(s) this PR fixes**:
Fixes #1366 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-08 06:27 UTC, ijungmann commented
Tests have been added and refactored.
Still need to fix the sample signature file, quickest way is to alter it myself (just need to change the first int to a byte).
Code smells appear to be [false positives regarding the TestFactory ](https://stackoverflow.com/questions/38764125/sonarqube-issue-add-at-least-one-assertion-to-this-test-case-for-unit-test-wit/38766392)

2021-01-08 18:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    protected void validateIntValue(int expected, int actual, String exceptionMessage) {
May be able to further reduce...

2021-01-08 19:38 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReaderTest.java
> +    }
Not sure if any of this should move out or not.

2021-01-08 19:42 UTC, ijungmann commented
Still looking for any other potential refactoring, but otherwise it's all good for review.

2021-01-08 20:05 UTC, steven-sheehy requested changes
Some initial thoughts

2021-01-08 20:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        validateLongValue(HASH_CLASS_ID, hashClassId,
Can these class IDs and class versions possibly change in the future without a signature file version bump? We should confirm and if there's any chance it might just read this value and not validate it.

2021-01-08 20:41 UTC, xin-hedera requested changes

2021-01-08 20:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
copyright year 2021?

2021-01-08 20:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
metadata hash and its signature are not read. also related:

- metadata signature is not verified
- metadata hash calculated from the corresponding record stream file can't be compared to the hash in the signature file, though the actual comparison will be handled in my PR

2021-01-08 20:41 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +            assertNotNull(answer.getHash());
need to assert the values of signature and hash match those in the file. looks like the test in `SignatureFileReaderV2Test` should be updated too.

2021-01-08 21:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        validateLongValue(HASH_CLASS_ID, hashClassId,
Confirmed that is a possibility, will remove the validation for any class ID or version.

2021-01-08 21:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    protected void validateIntValue(int expected, int actual, String exceptionMessage) {
Good idea, done.

2021-01-08 21:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +package com.hedera.mirror.importer.reader.signature;/*
Fixed.

2021-01-08 21:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReader.java
>              // Version 2 of the signature file begins with a byte of value 4.
Moved.

2021-01-08 21:52 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +        return ByteBuffer.allocate(Long.BYTES).putLong(value).array();
Ah, cool, that will help clean up quite a bit.  Done.

2021-01-08 21:52 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +        return ByteBuffer.allocate(Integer.BYTES).putInt(value).array();
Done.

2021-01-08 21:52 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        validateLongValue(HASH_CLASS_ID, hashClassId,
Removed those validations.

2021-01-08 22:02 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
Alright, yeah, I didn't see we needed the metadata information.  I can add those to the FileStreamSignature and do the same reading/validation on those.

2021-01-08 22:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
I recall in swirlds-common the sample logic does not compare the calculated metadata hash from record file and the metadata hash in the signature file, so better ask for clarification

2021-01-08 22:40 UTC, steven-sheehy requested changes

2021-01-08 22:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            validate(OBJECT_STREAM_SIGNATURE_VERSION, objectStreamSignatureVersion, "objectStreamSignatureVersion");
Same question. Can this vary for the same signature version?

2021-01-08 22:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +                "hashDigestType");
These two lines here and other validates below can be joined as they're under the margin now.

2021-01-08 22:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +        return ByteBuffer.allocate(Integer.BYTES).putInt(value).array();
Still there. Not sure if you've pushed this change yet.

2021-01-08 22:48 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
Fixed.

2021-01-08 22:53 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +        return ByteBuffer.allocate(Integer.BYTES).putInt(value).array();
Oops, removed one and had to clean up the other before removing, pushed halfway through.  Removed now.

2021-01-08 22:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
Added logic to read, validate, and store the metadata hash and signature in the same way.

2021-01-09 00:18 UTC, Nana-EC reviewed
Looking good, still reviewing

2021-01-12 06:36 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +                "hashDigestType");
Fixed.

2021-01-12 23:28 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +    private byte[] readHashObject(DataInputStream dis) throws IOException {
Good idea, spoke to Xin and he has said he will look into doing that.

2021-01-13 01:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
Added logic to the `NodeSignatureVerifier` to verify the metadata signature if present.
Also added tests for the `NodeSignatureVerifier`

2021-01-13 03:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                sig = Signature.getInstance("SHA384withRSA", "SunRsaSign");
It may make sense to have these stored as values in the enum.

2021-01-13 03:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            fileStreamSignature.setSignature(readSignatureObject(dis));
Added an enum to set the signature type and check it in the `NodeSignatureVerifier`.

2021-01-13 03:07 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +    private byte[] entireFileHash;
Not 100% on the names yet.

2021-01-13 03:19 UTC, ijungmann commented
Something is wrong with parsing the v5 file metadata hash, I've tried a couple of the new files provided recently and it is getting off track when starting the metadata parsing.  I don't know yet if it's actually something at the end of the regular signature that's failing or something at the start of the metadata hash, will continue to investigate.

2021-01-13 03:27 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +            assertNotNull(answer.getHash());
Did this for the v2 test, having other issues with the v5 test to fix first but will do similar there soon.

2021-01-13 03:49 UTC, ijungmann commented
> Something is wrong with parsing the v5 file metadata hash, I've tried a couple of the new files provided recently and it is getting off track when starting the metadata parsing. I don't know yet if it's actually something at the end of the regular signature that's failing or something at the start of the metadata hash, will continue to investigate.

After some debugging, it appears between the end of the entire file signature and the metadata hash there is an extra int (or at least 4 extra bytes) of value `1597147947`.  Not sure what this is, haven't matched it up to anything in the doc yet, but reading that extra int from the stream between the two makes it run smoothly.  Will follow up tomorrow.

2021-01-13 05:15 UTC, xin-hedera commented
> > Something is wrong with parsing the v5 file metadata hash, I've tried a couple of the new files provided recently and it is getting off track when starting the metadata parsing. I don't know yet if it's actually something at the end of the regular signature that's failing or something at the start of the metadata hash, will continue to investigate.
> 
> After some debugging, it appears between the end of the entire file signature and the metadata hash there is an extra int (or at least 4 extra bytes) of value `1597147947`. Not sure what this is, haven't matched it up to anything in the doc yet, but reading that extra int from the stream between the two makes it run smoothly. Will follow up tomorrow.

The format doc is incorrect. There is an extra int in the signature object, after `length of signature`, it's a checksum and it's the complement of `length of signature`, below are the links of the chain of functions called to deserialze the signature object.

https://github.com/swirlds/swirlds-platform/blob/637b1f2f1cca95a6c2a6397353193c059072dad2/swirlds-common/src/main/java/com/swirlds/common/stream/LinkedObjectStreamUtilities.java#L315

https://github.com/swirlds/swirlds-platform/blob/637b1f2f1cca95a6c2a6397353193c059072dad2/swirlds-common/src/main/java/com/swirlds/common/crypto/Signature.java#L70

https://github.com/swirlds/swirlds-platform/blob/637b1f2f1cca95a6c2a6397353193c059072dad2/swirlds-common/src/main/java/com/swirlds/common/io/ExtendedDataInputStream.java#L53-L73

2021-01-13 17:27 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        //Read the hashClassId and hashClassVersion, which are not used
There are a few more fields that turn out to be unused that don't fit in the same flow.  I'm not entirely opposed to making methods out of them to clearly define the fields being read, but it would mostly end up being the same logic with different method names.  
I think moving these two for grouping but keeping the others inline would be a weird mix though, so I'd prefer one or the other.

2021-01-13 17:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        //Read the hashClassId and hashClassVersion, which are not used
Actually, take that back, now that I see  that same logic is used in two separate spots and you're abstracting it a bit, it makes more sense to add.

2021-01-13 17:57 UTC, ijungmann commented
> > > Something is wrong with parsing the v5 file metadata hash, I've tried a couple of the new files provided recently and it is getting off track when starting the metadata parsing. I don't know yet if it's actually something at the end of the regular signature that's failing or something at the start of the metadata hash, will continue to investigate.
> > 
> > 
> > After some debugging, it appears between the end of the entire file signature and the metadata hash there is an extra int (or at least 4 extra bytes) of value `1597147947`. Not sure what this is, haven't matched it up to anything in the doc yet, but reading that extra int from the stream between the two makes it run smoothly. Will follow up tomorrow.
> 
> The format doc is incorrect. There is an extra int in the signature object, after `length of signature`, it's a checksum, below are the links of the chain of functions called to deserialze the signature object.
> 
> https://github.com/swirlds/swirlds-platform/blob/637b1f2f1cca95a6c2a6397353193c059072dad2/swirlds-common/src/main/java/com/swirlds/common/stream/LinkedObjectStreamUtilities.java#L315
> 
> https://github.com/swirlds/swirlds-platform/blob/637b1f2f1cca95a6c2a6397353193c059072dad2/swirlds-common/src/main/java/com/swirlds/common/crypto/Signature.java#L70
> 
> https://github.com/swirlds/swirlds-platform/blob/637b1f2f1cca95a6c2a6397353193c059072dad2/swirlds-common/src/main/java/com/swirlds/common/io/ExtendedDataInputStream.java#L53-L73

Thank you for digging that up, I spoke to Qian about what you've mention and that field has now been added to the appropriate doc.

2021-01-13 17:57 UTC, xin-hedera requested changes

2021-01-13 17:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            boolean isMatch = sig.verify(fileStreamSignature.getEntireFilesignature());
fail early when entire file hash signature verification fails

2021-01-13 17:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReaderTest.java
>  abstract class AbstractSignatureFileReaderTest extends IntegrationTest {
why this has to be an integration test?

2021-01-13 17:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +    @Value("classpath:data/signature/v5/2021-01-11T22_16_11.299356001Z.rcd_sig")
the file does not exist

2021-01-13 17:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            validate(OBJECT_STREAM_SIGNATURE_VERSION, objectStreamSignatureVersion, "objectStreamSignatureVersion");
Confirmed this can change, removed the validation.

2021-01-13 17:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +    protected static final int HASH_DIGEST_TYPE = 0x58ff811b; //denotes SHA-384
That makes sense, I have moved it.

2021-01-13 17:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        //Read the hashClassId and hashClassVersion, which are not used
Added this.

2021-01-13 18:00 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +    @Value("classpath:data/signature/v5/2021-01-11T22_16_11.299356001Z.rcd_sig")
Yep, forgot to push.  Just did.

2021-01-13 18:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            boolean isMatch = sig.verify(fileStreamSignature.getEntireFilesignature());
Good call, refactored to fail fast.

2021-01-13 18:35 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReaderTest.java
>  abstract class AbstractSignatureFileReaderTest extends IntegrationTest {
It doesn't have to be, I was using the `@SpringBootTest` to automatically load the file and the signatureFileReader, and I figured I would extend the IntegrationTest as it seems like almost all of our Spring Boot Tests do that, wasn't sure if that was just standard practice.  Honestly it doesn't need the Spring stuff at all, I've refactored it to load the file itself, so I can get rid of all that.

2021-01-13 18:39 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReaderTest.java
>  abstract class AbstractSignatureFileReaderTest extends IntegrationTest {
Just pushed that change.

2021-01-13 18:40 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                return true;
Perhaps a cleaner/better way to reflect this logic.

2021-01-13 18:41 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +            assertNotNull(answer.getHash());
Fixed in both now.

2021-01-13 20:15 UTC, xin-hedera requested changes

2021-01-13 20:15 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +        nodeKeyPair = KeyPairGenerator.getInstance("RSA").generateKeyPair();
generating RSA key is time consuming, should load it

2021-01-13 20:15 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +
need to test reaching consensus with exact 1/3 signatures

2021-01-13 20:15 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    void testNoPublicKey() throws GeneralSecurityException {
test function name does not match

2021-01-13 20:15 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +
need a test case for metadata hash signature verification failure

2021-01-13 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
check `dis.available() == 0`, also add test case

2021-01-13 21:55 UTC, steven-sheehy requested changes

2021-01-13 21:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            if (!sig.verify(fileStreamSignature.getEntireFileSignature())) {
Think this might be easier to understand if you split this 3 conditionals into standalone if statements.

```java
    if (!sig.verify(fileStreamSignature.getEntireFileSignature())) {
        return false;
    }

    if (fileStreamSignature.getMetadataSignature() != null) {
        sig.update(fileStreamSignature.getMetadataHash());
        return sig.verify(fileStreamSignature.getMetadataSignature());
    }

    return true;
```

2021-01-13 21:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        validate(HASH_DIGEST_TYPE, hashType, "hashDigestType:" + hashName);
We shouldn't overload the fieldname to concatenate the hash type. Recommend adding a new field to validate.

2021-01-13 21:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            fileStreamSignature.setSignatureType(SignatureType.SHA_384_WITH_RSA);
I'd have liked to have seen SIGNATURE_TYPE constant be a field on the enum and this dynamically populated based upon that. But since engineering has guaranteed signature algorithm won't vary in V5 hardcoding should be fine for now.

2021-01-14 09:14 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        private final int signatureTypeIndicator;
Maybe a better name

2021-01-14 09:15 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    }
Fix this, there's definitely a clean way to do this, just pushing what I have at the moment

2021-01-14 09:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    }
Fix this, definitely a way to cleanly support both messages, just pushing what I have right now.

2021-01-14 09:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    }
Did not have a good way to do this comparison that would support ints and longs, since I'm only using it for one int value right now it's set to only do ints.
Also will have the same issue as above with sectionName.

2021-01-14 09:23 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    private static final String privateKeyBase64String =
This may need to move to a file or something, it's a little unsightly.

2021-01-14 09:26 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +                "signatureLength");
It may be worthwhile to rework this a little to allow for multiple "corrupt" scenarios, as right now I can't test "length too long" and "length too short".  This is the only place it would be needed for now.

2021-01-14 09:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                sig = Signature.getInstance("SHA384withRSA", "SunRsaSign");
Added those

2021-01-14 09:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +    private byte[] entireFileHash;
Seems right, changed those.

2021-01-14 09:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +    private byte[] entireFileSignature;
Fixed

2021-01-14 09:31 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +    private byte[] metadataSignature;
Fixed.

2021-01-14 09:31 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
Removed.

2021-01-14 09:32 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        int signatureLength = dis.readInt();
Added validation that the length is between 0 and 384 bytes.

2021-01-14 09:32 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/CompositeSignatureFileReaderTest.java
> +    void testValidV2() throws IOException, NoSuchAlgorithmException {
Fixed.

2021-01-14 09:32 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2Test.java
> +    private final File signatureFile = Utility.getResource("data/signature/v2/2019-08-30T18_10_00.419072Z.rcd_sig");
Done

2021-01-14 09:33 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +        nodeKeyPair = KeyPairGenerator.getInstance("RSA").generateKeyPair();
Generated the keys once and added them to the class as base 64 encoded string.

2021-01-14 09:33 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +
Redid my partial consensus test to do 1/3 instead of 1/2.

2021-01-14 09:35 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    void testNoPublicKey() throws GeneralSecurityException {
Fixed.

2021-01-14 09:35 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +
Added one for metadata and file signature verification failure.

2021-01-14 09:36 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +
Done.

2021-01-14 09:36 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                log.error("Signature type not valid: {}", fileStreamSignature);
> This shouldn't be possible. We should already fail in the reader if there's no signature. We can also put a default in the `FileStreamSignature` if we need it for tests.
Removed.

2021-01-14 09:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            if (!sig.verify(fileStreamSignature.getEntireFileSignature())) {
Good idea, done

2021-01-14 09:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            fileStreamSignature.setSignatureType(SignatureType.SHA_384_WITH_RSA);
Added some logic to do that, I'm still only validating against the one since it should not vary, but now it will dynamically populate.

2021-01-14 09:40 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        validate(HASH_DIGEST_TYPE, hashType, "hashDigestType:" + hashName);
Did some initial work on that, need to clean it up.

2021-01-14 09:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            fileStreamSignature.setSignatureType(SignatureType.SHA_384_WITH_RSA);
Also just noticed with that change,`FileStreamSignature` could support having separate file and metadata signature types.  Not sure that would ever be a valid situation.

2021-01-14 16:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    }
`actual < minimumExpected || actual > maximumExpected`

2021-01-14 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        int signatureLength = dis.readInt();
move `MAX_SIGNATURE_LENGTH` to the enum?

2021-01-14 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        private final int signatureTypeIndicator;
`fileMarker`?

2021-01-14 16:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        private final int signatureTypeIndicator;
maybe just `type`...

2021-01-14 17:29 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        int signatureLength = dis.readInt();
Done

2021-01-14 17:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        validate(HASH_DIGEST_TYPE, hashType, "hashDigestType:" + hashName);
Overloaded `validate` with a signature that takes in a section name, only appends to the error message if present.

2021-01-14 17:32 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        private final int signatureTypeIndicator;
I like `fileMarker`, describes the source of the definition simply. Changed to that.

2021-01-14 17:33 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    }
Fixed.

2021-01-14 17:33 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/AbstractSignatureFileReader.java
> +    }
Changed.

2021-01-14 18:51 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5Test.java
> +                "signatureLength");
I think this is going to require a bigger refactoring job than I'm prepared to do right now for a pretty minor test case, it's still worthwhile to look at but maybe too much for this PR.

2021-01-14 19:38 UTC, steven-sheehy requested changes

2021-01-14 19:42 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        public static SignatureType fromSignatureTypeIndicator(int signatureTypeIndicator) {
Oops, good catch, I like `of()`.  Just pushed that.

2021-01-14 19:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +    protected static final int OBJECT_STREAM_SIGNATURE_VERSION = 1; //defines the format for the remainder of the file
Yep.  Removed entirely, the test can just go to the enum for that now.

2021-01-14 19:48 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    private static final String privateKeyBase64String =
I had that previously, yes.  Xin mentioned generating a key every time would be time consuming, so I moved to having a static one.  I can put it back if the tradeoff for a little extra time is worth making the test a little cleaner.

2021-01-14 19:49 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    private static final String privateKeyBase64String =
Correct, I previously had this in the code:
`KeyPairGenerator.getInstance("RSA").generateKeyPair();`
I just ran that once and encoded the results.

2021-01-14 19:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    private static final String privateKeyBase64String =
If we do it once in a BeforeAll how long does that take? Even if tens of seconds it's probably not a big deal.

2021-01-14 20:06 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    private static final String privateKeyBase64String =
It actually seems pretty quick, just did the change and it ran all the tests in about 3 seconds.  I will switch it back.

2021-01-14 20:06 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +    private static final String privateKeyBase64String =
Switched.

2021-01-14 20:15 UTC, steven-sheehy approved these changes
LGTM

2021-01-14 20:17 UTC, xin-hedera approved these changes
LGTM

2021-01-14 20:51 UTC, Nana-EC approved these changes
LGTM

2021-01-14 20:54 UTC, merged