Scheduled Transactions Design
hashgraph/hedera-mirror-node pull request #1414
Opened 2021-01-06 22:13 UTC by steven-sheehy

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1368 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-07 22:27 UTC, Nana-EC requested changes

2021-01-07 22:27 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +```
Potentially `signed` can be left out as a null `signed_timestamp` would signify it wasn't signed.

2021-01-07 22:27 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +- If not present, return both
Wouldn't it be better to default to return the outer/main transaction only and only return Schedule details on explicit request?

2021-01-07 22:27 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +
You should add a JSON example of the response with the inner scheduled transaction info

2021-01-07 22:27 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +Add an optional boolean `scheduled` parameter to `/api/v1/transactions/:id/stateproof` with a default of false
Why is this needed and how does it differ from a regular transaction in terms of stateproof logic?

2021-01-07 23:33 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +);
`executeAtTime` and `executeImmediately` no longer exists in the HAPI proto per my insistence.

2021-01-07 23:37 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +  transaction_body    bytea              not null
Good idea. Was pondering how we could process the schedule sign.

2021-01-07 23:41 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +```
I considered this, but as mentioned on scrum we simply do not have this information available in the mirror node. We have zero way to figure out who the expected/required signers are outside of invoking a HAPI query. We also don't have a way to map public key prefixes to account IDs (will double check with Michael). So the most we could do is keep a list of which public key prefixes/signatures have signed.

2021-01-07 23:47 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +- If not present, return both
That's debatable. My thinking is the current single transaction API returns multiple by default in the case that a duplicate transaction occurs. Thus, I thought we should preserve that behavior for scheduled transactions. It might be easier for a user to get extra data and research a way to filter it out than to never know that extra data existed or the flag existed. But we can discuss as a team.

2021-01-07 23:50 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +Add an optional boolean `scheduled` parameter to `/api/v1/transactions/:id/stateproof` with a default of false
Stateproof has to be on a single transaction. Regular transaction API can return multiple. So we have to have a default for scheduled. What that value should be is debatable.

2021-01-07 23:54 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +  creator_account_id  int                not null,
Fixed

2021-01-08 16:53 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +GET `/api/v1/schedule/{scheduleId}`
As mentioned, we can only get a list of public key prefixes that have signed. If we do add such a table for that info it wouldn't be enough info to warrant a separate REST endpoint. Instead, we should add a list of signatures to each schedule object.

2021-01-08 16:53 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +
Sure

2021-01-09 00:19 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +);
Sounds good

2021-01-09 00:21 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +Add an optional boolean `scheduled` parameter to `/api/v1/transactions/:id/stateproof` with a default of false
Makes sense

2021-01-11 17:43 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +GET `/api/v1/schedule/{scheduleId}`
Add an inner signature list to the current API.

2021-01-11 17:43 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +- For every `ScheduleSign` transaction, insert a `Transaction` and create the `Entities` if it doesn't exist
Added.

2021-01-11 17:43 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +```
Added a `schedule_signature` table with public key prefix and signature bytes.

2021-01-11 20:51 UTC, Nana-EC requested changes

2021-01-11 20:51 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +- Add a new `schedule` table:
nit: highlight which objects provide the info to populate the table i.e which transaction body type(s), record and receipts

2021-01-11 20:51 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +- Add a new `schedule_signature` table:
nit: highlight which objects provide the info to populate the table i.e which transaction body type(s), record and receipts

2021-01-11 20:51 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +- Insert a `ScheduleSignature` for every entry in the `sigMap`.
How does this `ScheduleSignature` differ from the once inserted under the create transaction.
Is it just the timestamp column?

Is it not possible to add a `signed` and/or `signed_timestamp` columns noted before that would provide info on the status of which signatures have been provided and which are yet to be fulfilled?
That is on each `ScheduleSign` transaction you'd match the provided public_key_prefix/signature and update this table.

As is it seems if you were asking for status you'd have to ask based on a time range similar to balance? Is that what you were going for vs being able to get at any time if and when a signature was provided?

2021-01-11 20:51 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +  type                smallint not null
Unclear of the significance and difference in the type column here.
You should highlight the details in the 'Schedule Create' section.

Also should the types require an additional reference table and Java enums?

2021-01-11 20:52 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +- If not present, return both
Now that I see the JSOn this make sense and is okay with me

2021-01-12 16:16 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +- Insert a `ScheduleSignature` for every entry in the `sigMap`.
> How does this ScheduleSignature differ from the once inserted under the create transaction.
Is it just the timestamp column?

Both `ScheduleCreate` and `ScheduleSign` contain a `sigMap` field. This table is a representation of that signature map and represents signatories that have already signed. Multiple accounts can sign on either create or sign so there can be multiple entries per transaction type and per consensus timestamp. So not just the timestamp column, every column can potentially differ except the schedule ID.

2021-01-12 17:06 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +- Add a new `schedule_signature` table:
Updated

2021-01-12 17:06 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +- Add a new `schedule` table:
Updated

2021-01-12 17:18 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +  type                smallint not null
Added text "Set `type` to the protobuf index of `sigPair.signature` `oneof` field" to schedule create section.

```proto
    oneof signature {
        bytes contract = 2; // smart contract virtual signature (always length zero)
        bytes ed25519 = 3; // ed25519 signature
        bytes RSA_3072 = 4; //RSA-3072 signature
        bytes ECDSA_384 = 5; //ECDSA p-384 signature
    }
```

> Also should the types require an additional reference table and Java enums?

Definitely not Java enums as importer/grpc/monitor don't care about the values. A reference table is debatable. I think the list of values is small enough and we're not going to use it to join except maybe for REST display purposes that we don't need one. We can maybe just do an enum for REST instead since whether it's a table or an enum we still have to do a deploy to add a new entry anyway.

If we don't do some sort of mapping, the downside is the client would need to know that `type=3` is `ed25519` from the proto. The upside for us is if a new type is added the mirror node doesn't need to be updated to support it. I don't think this field is important enough to map as anyone who cares about the contents of the signature bytes already knows what type they sent anyway. They would most likely just be comparing public key prefixes to see who signed.

2021-01-12 19:11 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +- Insert a `ScheduleSignature` for every entry in the `sigMap`.
Gotcha, it wasn't clear that the map contained only signed signatures. That clears things up.

Also I wasn't looking for a map of public key to account, just basically whether a signature had been provided or not.
This makes sense, for each `ScheduleCreate`/`ScheduleSign` we'd be looking to inset into the `schedule_signature` table. I'm guessing no updates are applicable so we'd ignore any signatures for a schedule that already exist

2021-01-12 19:13 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +  type                smallint not null
Okay, yeah, we can leave it as is and can add the reference table in the future should we feel it becomes needed

2021-01-12 20:10 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +- Insert a `ScheduleSignature` for every entry in the `sigMap`.
Correct, no updates to `schedule_signature`, only inserts.

2021-01-12 21:07 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-01-13 16:26 UTC, steven-sheehy commented
Removed type field as only ED25519 is implemented by the main nodes.

2021-01-13 16:27 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +  type                smallint not null
Removed field anyway

2021-01-13 17:17 UTC, Nana-EC approved these changes
LGTM

2021-01-14 16:56 UTC, xin-hedera approved these changes
LGTM

2021-01-14 19:16 UTC, ijungmann approved these changes
LGTM

2021-01-14 19:32 UTC, merged