Fix timescaledb init job failure
hashgraph/hedera-mirror-node pull request #1436
Opened 2021-01-11 21:37 UTC by xin-hedera

**Detailed description**:
Fix the failure by first checking the readiness of the access node service, then checking all data nodes have added to the access node.

**Which issue(s) this PR fixes**:
Fixes #1435 

**Special notes for your reviewer**:
The added step to ensure all data nodes have been added to the access node is in consideration of distributed hypertable. Quote from [timescaledb doc](https://docs.timescale.com/latest/getting-started/setup-multi-node-basic):

Once logged in on the access node, it is necessary to add data nodes to the local database before creating distributed hypertables. This will make the data node available for use by distributed hypertables and the access node will also connect to the data node and initialize it. 

However, this increases the time to finish the init job to > 1 minute for a 3 data nodes scenario, and `helm install` blocks until the init job finishes.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-11 23:34 UTC, Nana-EC approved these changes
LGTM

2021-01-11 23:54 UTC, steven-sheehy requested changes

2021-01-11 23:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +            - name: GET_DATA_NODES_COUNT_COMMAND
Why does this need to be an env variable? Can just make it a local variable.

2021-01-11 23:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              while true; do
I'm not a fan of infinite loops with breaks. Can we use `until` here instead? Something like [this](https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/mongodb-replicaset/init/on-start.sh#L55) loop that I did for the MongoDB chart I used to maintain.

2021-01-11 23:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
We should have a log statement in case there's some issue we know where it's stuck.

2021-01-11 23:54 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
Should we have some max amount of time that it can loop before failing the job? `"${SECONDS}" -ge "${timeout}"`

2021-01-12 03:27 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +            - name: GET_DATA_NODES_COUNT_COMMAND
removed

2021-01-12 03:27 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +              while true; do
updated to use `until`

2021-01-12 03:28 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
added logs for every 10s as well as when the check passes

2021-01-12 03:33 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
there isn't a good way to get a reasonable good timeout value: it varies under different conditions and it also depends on how many data nodes there are.

2021-01-12 04:39 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-01-12 04:40 UTC, steven-sheehy commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
Doesn't have to be a good value, could just be a really high value like 30 minutes. Just don't think it's good to wait indefinitely.

2021-01-12 05:27 UTC, Nana-EC approved these changes

2021-01-12 06:28 UTC, ijungmann approved these changes

2021-01-12 15:14 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
sure.

More work is needed for this PR since the "waiting all data nodes to be added to the access node" has to happen before `importer` runs flyway migration in which distributed hypertables are created. To achieve that, we need to move the logic to an init container in the `importer` pod. I'll add the `timeout` as part of the new commits.

2021-01-12 16:36 UTC, xin-hedera commented on charts/hedera-mirror/templates/job-timescaledb-init.yaml
> +                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
end up not adding `timeout` to the init container. init containers will be recreated by k8s if it fails so `timeout` does not make much sense. If we set the pod `restartPolicy` to Never, once the init container fails, k8s treas the Pod as failed, but I don't think that's what we want.

2021-01-12 16:49 UTC, xin-hedera commented
there is still issue in the timescale init job. we create users, schemas, and update search path. helm post-hook does not prevent other resources from running. this means it's possible that other resources depending on the readiness of the schema & search path changes will run before the init job finishes. In reality, this should rarely happen, especially for the importer as it takes quite sometime to start.

another relevant question is should we just remove the `post-install` hook annotation from the timescale init job?

2021-01-12 17:35 UTC, Nana-EC requested changes

2021-01-12 17:35 UTC, Nana-EC commented on charts/hedera-mirror-importer/values.yaml
> +timescaledb:
I don't think we'd want to add a specific timescale config under importer values, plus this serves as a repetition of the Values override.
Would it work to add a ConfigMap with this info that pulls in these details from the  main chart Values and consume it here, so that you only specify it once and it's more DRY

2021-01-12 19:01 UTC, Nana-EC commented
> there is still issue in the timescale init job. we create users, schemas, and update search path. helm post-hook does not prevent other resources from running. this means it's possible that other resources depending on the readiness of the schema & search path changes will run before the init job finishes. In reality, this should rarely happen, especially for the importer as it takes quite sometime to start.
> 
> another relevant question is should we just remove the `post-install` hook annotation from the timescale init job?

I added it to ensure that the dependency charts were first installed before the job attempted to run. Basically to reduce the amount of time the `pg_isready` would need to run.
If that no longer benefits us/ provides the desired value / is needed, then I'm okay removing it.

2021-01-12 19:52 UTC, xin-hedera commented
reverted the changes and created a follow-up ticket https://github.com/hashgraph/hedera-mirror-node/issues/1439

2021-01-12 20:04 UTC, Nana-EC approved these changes
LGTM

2021-01-12 20:16 UTC, steven-sheehy approved these changes

2021-01-12 20:28 UTC, merged