Support record file v5
hashgraph/hedera-mirror-node pull request #1445
Opened 2021-01-14 00:52 UTC by xin-hedera

**Detailed description**:

- Add RecordFileReaderImplV5 to read v5 record file
- Update downloader to handle hash-related logic for v5 record file
- Refactor record file downloader test to support v2 and v5 record files

**Which issue(s) this PR fixes**:
Fixes #1365 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-01-14 00:53 UTC, xin-hedera commented
there will be follow-up changes once signature file v5 is merged

2021-01-14 15:58 UTC, xin-hedera commented
some importer integration tests will still fail because:

- they rely on the old record_file table, new record_file table's constraint on new columns would break it
- in cci, all integration tests share a single db

so the correct target flyway version is not honored in cci environment, thus the failures

2021-01-15 17:30 UTC, xin-hedera commented
there may be other changes to share code between signature file reader & record file reader, but want to open it for review now

2021-01-15 21:04 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/data/db/stateproof/record_file.sql
> +-- SELECT pg_catalog.set_config('search_path', '', false, 0, 0, 2);
accidentally replaced the 0 with 0, 0, 2. will revert it with other changes

2021-01-15 21:05 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/data/db/stateproof/record_file.sql
> -	(804, '2019-10-11T16_04_29.881236Z.rcd', 1596752891, 1596752891, 'e36645e95ab70c0c65d955adc2381d711910b42fdacdcbc988fb9b1a8acd18ea67a98d361c6865bbbca4a94ecd7ec8b5', '0105c84b2350b0a29f8b9a505025407c
the sql file is used to populate the `record_file` table for stateproof integrations tests, since there are new not null columns added, adding the columns here is necessary to not break the tests

2021-01-15 21:59 UTC, ijungmann requested changes
Still looking, just want to get out something.  Looks good, just some thoughts.

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @Enumerated(EnumType.ORDINAL)
This is the default, is it specified here just for clarity?

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        String filename = streamFile.getName();
nit: I prefer `fileName` personally, but if others prefer it this way I won't complain.

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/exception/StreamFileReaderException.java
>      public StreamFileReaderException(final String message, final Throwable throwable) {
Should final be removed here too?

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/domain/RecordFileV1_33_0.java
> +public class RecordFileV1_33_0 implements StreamFile {
Something about this feels very hacky to me.  This is all just to support the one migration, where we expect an  older file version, correct?

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +public class Utility {
I feel like a Utility class is not the best way to go for this, seems like there would be a cleaner way to group this.  The validation I can understand (pretty generic), having the error messages and the reading seems like a stretch.  At the very least I would rename it as we already have a `Utility` class in this module

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        Utility.validate(readerVersion, version, "record file version", filename);
The error messages in the Utility all say "signature file".  Either the messages have to be written more generically or we need to add another field for file type.

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +            if (hasChecksum) {
I think it would be good to mention the checksum in the method name.

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/Constants.java
> +/*
Seems like this file got a little extra formatting for some reason.

2021-01-15 21:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/Constants.java
> +public final class Constants {
Would name this `RecordConstants` or something like that if we're going to limit it to this package, or move it out of this package if it's going to become a more general Constants class.

2021-01-15 22:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        String filename = streamFile.getName();
I'm seeing we use filename pretty much everywhere else, so never mind, a precedent has already been set.

2021-01-15 22:15 UTC, xin-hedera commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/DomainDriver.java
>          log.info("Writing data to db");
sure

2021-01-15 22:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/DigestAlgorithm.java
> +    public static DigestAlgorithm from(Integer ordinal) {
it was in a converter class which later I removed. will remove it

2021-01-15 22:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @Enumerated(EnumType.ORDINAL)
the annotation tells JPA to persist the ordinal value of the enum.

2021-01-15 22:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/Constants.java
> +public final class Constants {
perhaps move them to the interface `RecordFileReader` and remove this class

2021-01-15 22:35 UTC, xin-hedera commented on .circleci/config.yml
> +    MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --show-version -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dgroups=!failincci
cci is probably better as more ppl using cci for CircleCI than circle?

2021-01-15 22:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +public class Utility {
agree and open to suggestions

2021-01-15 22:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        Utility.validate(readerVersion, version, "record file version", filename);
good catch, will clean it.

2021-01-15 22:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +            if (hasChecksum) {
perhaps add a comment for the function is better.

2021-01-16 00:13 UTC, Nana-EC reviewed
1st pass comments and suggestions

2021-01-16 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.1__update_record_file.sql
> +alter table if exists record_file add column if not exists hapi_version_major int;
Would it be overkill to also apply a similar encoding logic to the version number, like we do for entityIds?
That way the space in the db is compressed to a singled encoded integer and we let the repository do the transform from 0.0.1 -> 1

2021-01-16 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    private Integer hapiVersionMajor;
Should these just be a Single `Version` object instead? Then transform back and forth between this and the encodedId I suggested in the db to save space?

2021-01-16 00:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +public class Utility {
that'll work but I feel adding another layer of inheritance does not look nice, besides, these functions are also shared with signature file readers

2021-01-16 00:34 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AbstractRepositoryTest.java
> +    protected RecordFileRepositoryV1_33_0 recordFileRepositoryV1_33_0;
sure

2021-01-16 00:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.1__update_record_file.sql
> +alter table if exists record_file add column if not exists hapi_version_major int;
thought about that too.

what would be a good plan for size of each in the int number? 12-bit, 12-bit, 8-bit?

2021-01-16 01:06 UTC, ijungmann requested changes
Went through the rest, some more thoughts.  Good work thus far.

2021-01-16 01:06 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/UtilityTest.java
> +    void readLengthAdnBytesWithChecksum(int length, int checksum, boolean expectThrown) throws IOException {
nit:
```suggestion
    void readLengthAndBytesWithChecksum(int length, int checksum, boolean expectThrown) throws IOException {
```

2021-01-16 01:10 UTC, ijungmann commented on .circleci/config.yml
> +    MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --show-version -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dgroups=!failincci
That's fair, this more goes back to [this comment](https://github.com/hashgraph/hedera-mirror-node/pull/1448#discussion_r558486766) in that I find the tags hard to read in this format sometimes.  I'm not stuck in about it though, it's rather nit-picky at this point.

2021-01-16 01:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @Enumerated(EnumType.ORDINAL)
Right, but from what I see in the documentation for `@Enumerated`, it defaults to ORDINAL and specifying it is redundant.  I'm okay with it if we just want to make it explicit, but it's not necessary from my understanding.

2021-01-16 01:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/Constants.java
> +public final class Constants {
Moving to interface would be better than having separate constants class

2021-01-16 01:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.1__update_record_file.sql
> +alter table if exists record_file add column if not exists hapi_version_major int;
Design doc say each of them are 4 byte interest i.e 32bit
Also it says it matches the Semantic Version that uses int32
https://github.com/hashgraph/hedera-services/blob/master/hapi-proto/src/main/proto/BasicTypes.proto#L354

2021-01-16 01:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.1__update_record_file.sql
> +alter table if exists record_file add column if not exists hapi_version_major int;
This works fine for entity id since we don't have non zero realms or shards. Also, the tables that have entity ids are huge.

 Record file is small in comparison. We should avoid the complexity and reduction in ease of use that encoding entails until it becomes a performance bottleneck. My vote is no.

2021-01-16 01:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.1__update_record_file.sql
> +alter table if exists record_file add column if not exists hapi_version_major int;
Also we don't join on hapi version like we do on entities or timestamps so it doesn't provide benefits in indexing. Plus once we switch to TimescaleDB compression will make disk savings of separate a moot point.

2021-01-16 18:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            if (classID != RECORD_STREAM_OBJECT_CLASS_ID) {
for record file, it's necessary to look at the class ID since it has a variable number of record stream objects. so yes if there are new class IDs for the hash object / the record stream object, we have to make changes

2021-01-16 18:49 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/record/AbstractRecordFileDownloaderTest.java
> +        Pair<String, String> testFiles = getTestFiles();
we always test two files afaik.

2021-01-19 16:32 UTC, steven-sheehy requested changes
Still reviewing

2021-01-19 16:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +public class Utility {
Yeah, strongly dislike Utility methods in general. I think putting them in an `AbstractFileReader` is fine and at least a better option than a utility. Another option is a custom `InputStream`:

```java
public class ValidatedInputStream extends DataInputStream {

  public int readInt(int expected) {...}

...
}
```

2021-01-19 16:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +    protected interface RecordFileDigest {
It's unfortunate that the abstraction for v1 and v2 can't be used for v5. Is there another abstraction that would allow us to to have a common `AbstractRecordFileReader` for all versions? Maybe in a follow up next sprint.

2021-01-19 16:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +        MessageDigest mdForFile = createMessageDigest(DIGEST_ALGORITHM);
nit: Would prefer md spelled out and no `For`. `messageDigestFile`, `messageDigestMetadata`

2021-01-19 16:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                new BufferedInputStream(new DigestInputStream(streamFileData.getInputStream(), mdForFile)))) {
I wasn't aware of `DigestInputStream`. Very nice find. I think you can streamline this further by using two wrapped `DigestInputStreams`, one for metadata and one for file. There's a `DigestInputStream.on(boolean)` you can use to turn on and off the metadata when when it's applicable.

2021-01-19 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +    public Map<String, RecordFile> getRecordFilesMap() {
this serves as a single source of truth for `RecordFile` objects used by most test cases. before the change they were created all over.

2021-01-19 17:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    private String metadataHash;
with v5, when we implement the smaller size record file payload with all record stream objects (but the one in stateproof request) replaced by its hash, we need to calculate the Metadata hash and compare it against what's in the signature file.

however, the stateproof rest API does not calculate metadata hash, and client reads the metadata hash from the signature file, so the field doesn't have to persist to db.

2021-01-19 17:10 UTC, steven-sheehy requested changes

2021-01-19 17:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            if (classID != RECORD_STREAM_OBJECT_CLASS_ID) {
I think there's a better way that doesn't require checking for hardcoded class IDs that may change. We just need to differentiate between `StreamHash` and `RecordStreamObject` since the former occurs both before and after N `RecordStreamObjects`. Thus we can do something like this:

```java
StreamHash previousHash = StreamHash.read(dis);
long classIdRecordStream = -1;
long classId = -1;

do {
  // Has to be at least one record stream or something's wrong
  RecordStreamObject recordStreamObject = RecordStreamObject.read(dis); 
  classIdRecordStream = recordStreamObject.getClassId();

  dis.mark(Longs.BYTES);
  classId = dis.readLong();
  dis.reset();
} while (classId == classIdRecordStream);

StreamHash currentHash = StreamHash.read(dis);
```

So it basically just breaks the loop when it detects that the next class ID doesn't match the previous record stream class ID. Alternatively, you could compare it against the previous hash class ID.

2021-01-19 17:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +    public Map<String, RecordFile> getRecordFilesMap() {
I think the single source of truth concept is fine, the debate is just about where it should be located.

2021-01-19 17:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +        if (version == 5) {
I don't think we should be changing how the downloader verifies the current hash against the previous hash. We should continue to use the full file hash for both previous and current. If we want to separately verify the start running hash matches the end running hash of the previous record file we could add that, but that would be a separate validation.

- The `file_hash` should store the current record file's full hash. We can consider renaming this to `file_hash_end`
- The `prev_hash` should store the previous record file's full hash. We can consider renaming this to `file_hash_start`
- The `running_hash_start` should store the current record file's start running hash.
- The `running_hash_end` should store the current record file's end running hash.
- `t_application_status` should store the full file hash.

2021-01-19 17:50 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +        if (version == 5) {
the change here is a bit confusing.

The fact is with v5, the hash chain has changed and it's now chained on the object running hash not the file hash.

With v1/v2, the record file has the field "previous file hash", that's what the downloader verifies: previous file hash in the current record file must match the previous record file hash in the application status table.

With v5, the record file has the new field "start object running hash", which is the "end object running hash" of the previous record file, so it's the new chain the downloader needs to verify. there is no "previous file hash" in v5.

2021-01-19 18:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                new BufferedInputStream(new DigestInputStream(streamFileData.getInputStream(), mdForFile)))) {
I considered calculating metadata hash similarly but gave up because the `DigestInputStream` for the metadata hash can't be further wrapped by any inputstream which reads more data than the client has requested (the behavior of `BufferedInputStream`). It's still doable but it may be less readable and error-prone.

there is no such issue for the entire file hash as long as the data of the file is only read once.

2021-01-19 20:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                new BufferedInputStream(new DigestInputStream(streamFileData.getInputStream(), mdForFile)))) {
I didn't mean to further wrap the `BufferedInputStream`, but to put the additional `DigestInputStream` next to the current `DigestInputStream` so it's not being buffered:

```java
try (DigestInputStream digestInputStream = new DigestInputStream(new DigestInputStream(streamFileData.getInputStream(), mdForFile), mdForMetadata); DataInputStream dis = new DataInputStream(new BufferedInputStream(digestInputStream))) {
  // read all the headers using DataInputStream
  digestInputStream.on(false);
 // read all the non-headers using DataInputStream
}
```

Can consider for a follow up.

2021-01-19 20:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +        if (version == 5) {
I see. I thought I saw a previous file hash in v5 hence my comment but was mistaken.

2021-01-19 20:41 UTC, xin-hedera commented on .circleci/config.yml
> +    MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --show-version -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dgroups=!failincci
will switch to `JdbcTemplate`, but it won't cure the issue in CircleCI since the SQL run with `JdbcTemplate` in that migration test would still have to assume the `record_file` table has no "not null" digest_algorithm / version columns

2021-01-19 21:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @Enumerated(EnumType.ORDINAL)
updated as suggested

2021-01-19 21:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/DigestAlgorithm.java
> +    public static DigestAlgorithm from(Integer ordinal) {
removed, as well as the test class

2021-01-19 21:37 UTC, xin-hedera commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/DomainDriver.java
>          log.info("Writing data to db");
updated

2021-01-19 21:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +public class Utility {
renamed it to `ReaderUtility`... tend to leave the bigger refactor into the next sprint

2021-01-19 21:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        Utility.validate(readerVersion, version, "record file version", filename);
changed the error messages. also in order to have signature file name in the formatted error messages, updated SignatireFileReader.read to `FileStreamSignature read(StreamFileData signatureFileData);`

2021-01-19 21:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +                validate(101 - len, checksum, "checksum", section);
good idea. moved it to a static int SIMPLE_SUM.

2021-01-19 21:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AbstractRepositoryTest.java
> +    protected RecordFileRepositoryV1_33_0 recordFileRepositoryV1_33_0;
removed it and actually will remove the entity class and version specific repository and change it to SQL statements in the next commit

2021-01-19 21:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +        Utility.validate(OBJECT_STREAM_VERSION, objectStreamVersion, "object stream version", filename);
removed

2021-01-19 21:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +        Utility.validate(RECORD_STREAM_OBJECT_CLASS_ID, classID, "record stream object class ID");
removed

2021-01-19 21:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            if (classID != RECORD_STREAM_OBJECT_CLASS_ID) {
good idea. did the latter: save the class ID of the start object running hash and use it to check if all record stream objects are read

2021-01-19 21:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            }
updated, also made the same change in `AbstractPreV5RecordFileReader`

2021-01-19 21:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            }
added a method `isHashObject`

2021-01-19 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/DigestAlgorithmTest.java
> +        assertThat(DigestAlgorithm.from(digestAlgorithm.ordinal())).isEqualTo(digestAlgorithm);
yes the test class is removed

2021-01-19 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/record/AbstractRecordFileDownloaderTest.java
> +        Pair<String, String> testFiles = getTestFiles();
changed to `List<String>`

2021-01-19 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/UtilityTest.java
> +    void readLengthAdnBytesWithChecksum(int length, int checksum, boolean expectThrown) throws IOException {
good catch. fixed

2021-01-19 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                log.trace("Verifying signature: {}", fileStreamSignature);
reverted

2021-01-19 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +    private final RecordFileRepositoryV1_33_0 recordFileRepositoryCompat;
will make the change in the next commit

2021-01-19 21:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +        return Utility.readLengthAndBytes(dis, SHA384.getSize(), SHA384.getSize(), false, sectionName, "hash");
moved it to a POJO `HashObject`

2021-01-19 21:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +        MessageDigest mdForFile = createMessageDigest(DIGEST_ALGORITHM);
updated

2021-01-19 21:46 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                new BufferedInputStream(new DigestInputStream(streamFileData.getInputStream(), mdForFile)))) {
it turns out that after I move reading hash object into the POJO `HashObject`, hashing fields to get metadata hash is better done the way as the entire file hash :)

2021-01-19 21:46 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +    private long peakClassID(DataInputStream dis) throws IOException {
the method is removed :)

2021-01-19 23:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.33.1__update_record_file.sql
> +alter table if exists record_file add column if not exists hapi_version_major int;
My main aim here was space saving, especially as the network and TPS grow. But I guess we can resolve that with compression.
If the downside is complexity that makes usability worse then I'm fine with leaving it as is.

We can always circle back for a migration as  noted

2021-01-19 23:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_Record.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
can't inject `JdbcTemplate`, causes circular dependency issue

2021-01-19 23:22 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_32_0__Missing_StreamFile_RecordTest.java
> +        jdbcTemplate = new JdbcTemplate(dataSource);
can't inject `JdbcTemplate`, causes circular dependency issue

2021-01-20 00:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                new BufferedInputStream(new DigestInputStream(streamFileData.getInputStream(), mdForFile)))) {
That's better, but does create extra inputstreams that my suggestion avoids. But works well enough for now.

2021-01-20 00:49 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/Utility.java
> +public class Utility {
Okay with that for the time being.

2021-01-20 00:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            if (classID != RECORD_STREAM_OBJECT_CLASS_ID) {
I like this solution, much safer.

2021-01-20 01:01 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +    public Map<String, RecordFile> getRecordFilesMap() {
Yeah, this seems more like something that would belong in an abstract class for record file tests, or if there's no easy way to achieve that even a more specific `RecordFileTestUtils`

2021-01-20 04:06 UTC, steven-sheehy approved these changes
LGTM. Any remaining items can be handled in a follow up next sprint.

2021-01-20 05:46 UTC, Nana-EC submitted a review, later dismissed
Looks good for the alpha. 
Remaining items can be addressed in future PRs/sprint as agreed

2021-01-20 14:55 UTC, ijungmann submitted a review, later dismissed

2021-01-20 16:23 UTC, steven-sheehy approved these changes

2021-01-20 16:25 UTC, ijungmann approved these changes

2021-01-20 16:26 UTC, merged