V2 schema gitactions
hashgraph/hedera-mirror-node pull request #1448
Opened 2021-01-15 05:01 UTC by Nana-EC

**Detailed description**:
During the transition between v1 and v2 mirror data schema it's important to have a CI process that captures the v2 logic until it is fully utilized.

- Add a GitHub action that runs a separate module tests
- Add a job that runs a separate grpc tests
- Add a job that runs a separate importer tests. 
- Add a job that runs a separate rest tests
- Add test tags to migration tests for v1 that can be skipped in v2 case
- Updated default flyway placeholders in grpc application yaml
- Add debug logs to s3ops in rest module to clarify container properties as they differ when the embedded option is used
- Add a `CI_CONTAINERS` env variable in rest module to allow for easy setting of using containers created by CI or containers created by internal code

**Which issue(s) this PR fixes**:
Fixes #1345 

**Special notes for your reviewer**:
There seems to be an unclear Async related issue causing `integration.test.js` tests to fail when using the GenericContainer. This only happens in CI. However, when utilizing containers created by gtihub action runner there are no issues.
For now I've added both, with the intention of removing one. If necessary a bug can be opened to address the issue as it may involve further test architecture changes.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-01-15 18:19 UTC, ijungmann requested changes
Couple minor things, looks good otherwise.

2021-01-15 18:19 UTC, ijungmann commented on .github/workflows/v2-schema-ci.yml
> +      - name: Upload importer test results
Rest results, right?

2021-01-15 18:19 UTC, ijungmann commented on .github/workflows/v2-schema-ci.yml
> +      - name: Upload importer test results
Rest results here as well.

2021-01-15 18:19 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Remove_Invalid_EntitiesTest.java
> +@Tag("v1data")
Is the standard for this not to use camel case?  I'm not opposed to it, just curious.

2021-01-15 19:50 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Remove_Invalid_EntitiesTest.java
> +@Tag("v1data")
good point. We do have the standard on variable naming and I believe non java file names
Whenever an item may be typed out on the command line I like to defer to lowercase in case someone fat thumbs it but also so I don't have to presume case insensitivity on whatever systems utilize it behind the scenes. 
Let's see what others say

2021-01-15 22:28 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +      - name: Upload importer test results
Yes, correct, will update.

2021-01-15 22:28 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +      - name: Upload importer test results
Yes, correct, will update.

2021-01-15 23:32 UTC, steven-sheehy requested changes

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +  grpc-build:
Why are we splitting grpc and importer? Just for perceived performance gains? This is sub-optimal for the following reasons:

- If we add another module that uses the database we'd have to remember to add another verbose job stanza
- Building grpc without protobuf will probably fail if we change the protobuf
- Both java jobs set environment, checkout code, setup java, and restore cache when these operations could be done once
- If we want test parallelization, we should later investigate maven ways for that

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} ${MAVEN_SPRING_OPTS} install -Djib.skip -Ddocker.skip -DskipTests
Putting the cache after the install means that the cache is not restored when this install runs. Should reverse the order and then combine the install and verify like the dev workflow has it.

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
We shouldn't need a GITHUB_TOKEN just to build

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
We shouldn't need a GITHUB_TOKEN just to test

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} ${MAVEN_SPRING_OPTS} verify -Djib.skip -pl hedera-mirror-importer/ -P v2data
If we're going to pass v2 specific params in MAVEN_SPRING_OPTS, then we should just pass excluded tests specific to v2 in MAVEN_SPRING_OPTS as well and remove the v2data profile. That way there's one location to specify things instead of it being split into two.

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +    branches: [ master, release/** ]
Not sure we need to run this on push to master.

2021-01-15 23:32 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +        if: always()
I didn't confirm, but `if: always()` sounds like it would be unnecessary like `if (true)` in Java.

2021-01-16 02:13 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +  grpc-build:
I'm personally not a fan of running all our tests in one big run. It feels bloated and makes
- CI log files long
- build times longer. Currently 14 mins al together vs 4 mins run in parallel 
- Hides future failures. If there's a CI related issue/flakiness in both importer and grpc, the latter module will get blocked and you won't know of the issue until the former process passes. This way you see both and could address both in a single commit. Also add to this when your changes are only related t the module that didn't get run.

I think it's better practice to run them individually as they are separate modules and allow GitHub to give us the parallelization.
Notably the grpc job does a maven install first to make sure the protobuf is used.
Also I believe each job runs in its own container so there's nothing wrong setting environment, checking out code. I guess there's an argument for the inefficient caching but that can be fixed in this case with a cache for each module.

This is a CI process, so a sub-optimal process that provides more clarity, reliability and reduces troubleshooting time I think is acceptable.

When we add a new module we should add a new job.

2021-01-16 02:19 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} ${MAVEN_SPRING_OPTS} install -Djib.skip -Ddocker.skip -DskipTests
Cache, order got mixed up in changes.
They are separate because the first install ensures the proof dependency is available for use by grpc module. Without that it fails cause that module isn't available

2021-01-16 02:22 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +        if: always()
This was left over from when I had importer and grpc tests as separate steps instead of jobs. It was another way of making sure logs were pushed even if a module failed. 
I preferred separate jobs over separate steps, can remove it now

2021-01-16 02:24 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +    branches: [ master, release/** ]
Will remove the pushes. Pull requests should be enough right

2021-01-16 02:37 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} ${MAVEN_SPRING_OPTS} verify -Djib.skip -pl hedera-mirror-importer/ -P v2data
I can just move this up to the workflow level so it's only specific once

2021-01-16 02:45 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Remove_Invalid_EntitiesTest.java
> +@Tag("v1data")
Will update and skip v1 tests

2021-01-16 03:09 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Will remove

2021-01-16 03:10 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Will remove

2021-01-16 03:19 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +    branches: [ master, release/** ]
Removed push

2021-01-16 03:19 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} ${MAVEN_SPRING_OPTS} install -Djib.skip -Ddocker.skip -DskipTests
Reordered and updated cache logic

2021-01-16 03:20 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Removed

2021-01-16 03:20 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Removed

2021-01-16 03:20 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +      - name: Upload importer test results
Updated

2021-01-16 03:20 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +      - name: Upload importer test results
Updated, though N/A

2021-01-16 03:21 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Remove_Invalid_EntitiesTest.java
> +@Tag("v1data")
Updated

2021-01-19 21:25 UTC, steven-sheehy commented on .github/workflows/v2-schema-ci.yml
> +  grpc-build:
Those are good points. But the `Currently 14 mins all together vs 4 mins run in parallel` is not accurate. Your tests ran in [6m28s](https://github.com/hashgraph/hedera-mirror-node/actions/runs/489431158), not 4m as you have to take the max of the longest running test. [14m](https://github.com/hashgraph/hedera-mirror-node/actions/runs/486409915) is also not correct as the job you're comparing to also pushes docker images in which just the test image push alone takes almost 5m of that.

I created a comparable job that runs all the java tests (not just grpc and importer) and it completes in [6m58s](https://github.com/hashgraph/hedera-mirror-node/actions/runs/497016239). But if you feel strongly about it we can keep it separate, just clarifying things.

2021-01-19 23:09 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +  grpc-build:
Yeah those are fair points on the time comparison.
I do prefer it separated so will leave it as is.
Thanks

2021-01-19 23:10 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +  grpc-build:
Good suggestions, will update

2021-01-19 23:10 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +name: "Module Tests v2 Schema"
Works for me

2021-01-20 05:43 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +      - run: git checkout HEAD^2
Removed

2021-01-20 05:44 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +name: "Module Tests v2 Schema"
Updated

2021-01-20 05:44 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +  grpc-build:
Updated

2021-01-20 05:44 UTC, Nana-EC commented on .github/workflows/v2-schema-ci.yml
> +          fetch-depth: 0
Removed

2021-01-20 14:47 UTC, ijungmann approved these changes
LGTM

2021-01-20 16:10 UTC, steven-sheehy approved these changes
LGTM

2021-01-20 16:11 UTC, merged