Update TimescaleDB migration docs and scripts
hashgraph/hedera-mirror-node pull request #1475
Opened 2021-01-20 22:07 UTC by steven-sheehy

**Detailed description**:
- Add a custom `values-timescaledb.yaml` to make it easier to test TimescaleDB
- Add importer related steps to migration docs
- Add database verification of old and new database to migration.sh
- Add various tweaks and fixes to documentation
- Fix address book logs being too verbose
- Fix migration.sh having to be ran from a certain directory
- Fix a stacktrace on startup related to Google PubSub configuration
- Upgrade timescaledb-multinode chart to 0.8.0

**Which issue(s) this PR fixes**:
Partially addresses #1423

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-20 23:44 UTC, Nana-EC requested changes

2021-01-20 23:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBook.java
> +    @ToString.Exclude
I agree with the exclusion of the `fileData`. The presence of the `nodeAccountIDPubKeyMap` however was useful for troubleshooting address book updates.
Might be worthwhile to see this so it's easy to see form logs the nodes that were added.

2021-01-20 23:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/migration.sh
> +  echo "New database already contains data. The migration might have already been ran or the importer might've initialized it. Please remove the data and rerun the migration"
Is this message correct? I believe this would refer to the old db.
Did you mean to verify when the old db has no data?

2021-01-20 23:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBook.java
> +    @ToString.Exclude
The information in `nodeAccountIDPubKeyMap` is a lazily generated field that is made up other fields already present in the `toString()` output. Also, we exclude the `publicKey` field as well since it's very verbose. Keeping this field would negate the benefits of excluding public key from `AddressBookEntry` and duplicate the node account IDs.

2021-01-20 23:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/migration.sh
> +  echo "New database already contains data. The migration might have already been ran or the importer might've initialized it. Please remove the data and rerun the migration"
Yes, I coincidentally noticed this myself when re-reviewing my PR and pushed a fix.

2021-01-21 00:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBook.java
> +    @ToString.Exclude
Actually this is fine, we still get the nodeId's from the serialization of `AddressBookEntry`.

2021-01-21 02:10 UTC, Nana-EC commented on charts/README.md
> +$ helm upgrade --install mirror charts/hedera-mirror -f charts/hedera-mirror/custom.yaml
nit: since you added `values-timescaledb.yaml` does this command now need to include that also

2021-01-21 04:33 UTC, steven-sheehy commented on charts/README.md
> +$ helm upgrade --install mirror charts/hedera-mirror -f charts/hedera-mirror/custom.yaml
No, this section is for a custom address book. It's not applicable to TimescaleDB.

2021-01-21 16:36 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-01-21 16:36 UTC, Nana-EC commented on charts/README.md
> +$ helm upgrade --install mirror charts/hedera-mirror -f charts/hedera-mirror/custom.yaml
Sounds good

2021-01-21 16:37 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-01-21 17:18 UTC, ijungmann submitted a review, later dismissed

2021-01-22 17:00 UTC, ijungmann approved these changes

2021-01-22 17:01 UTC, merged