Add schema and domain support for scheduled transactions
hashgraph/hedera-mirror-node pull request #1477
Opened 2021-01-21 01:56 UTC by Nana-EC

**Detailed description**:
To support scheduled transactions 

- Add a v1 database migration
- Update v2 database migration
- Add necessary `Schedule` class
- Add necessary `ScheduleSignature` class
- Add necessary `ScheduleRepository` class
- Add necessary `ScheduleSignatureRepository` class
- Update grpc and importer modules `EntityTypeEnum` with `SCHEDULE(6)`
- Add `ScheduleIdConverter` to convert from `ScheduleId` to encodedEntityId long
- Add `AbstractEntityConverterTest` to consolidate ConverterTest logic
- Update existing ConverterTests to extend `AbstractEntityConverterTest`
- Add `ScheduleIdConverterTest` that extends `AbstractEntityConverterTest`
- Add `ScheduleRepositoryTest` and `ScheduleSignatureRepositoryTest`

**Which issue(s) this PR fixes**:
Fixes #1464 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-21 16:50 UTC, steven-sheehy requested changes

2021-01-21 16:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +values (42, 'SCHEDULECREATE', 5),
These should be 6 to match the new entry in t_entity_types, right?

2021-01-21 16:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +values (201, 'INVALID_SCHEDULE_ID');
Looks like there's been more values [added](https://github.com/hashgraph/hedera-services/blob/0d65bad617406a8e8ee49aac2d4a61bec6112d53/hapi-proto/src/main/proto/ResponseCode.proto#L212) since. Can you update this and the doc? Or maybe just remove specific codes from doc.

2021-01-21 16:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +       ('INVALID_SCHEDULE_ID', 201);
Same comments for this file about missing response codes and incorrect entity IDs

2021-01-21 16:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepository.java
> +    @Transactional
Tests were failing without both `@Modifying` and test failures explicitly requested `@Transactional` be added.
I can circle back to the spring log errors .

2021-01-21 16:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
This was copy mistake. Will remove.
Let me know if you think the composite key is required

2021-01-21 17:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepository.java
> +    @Transactional
`@Modifying` definitely needed.

2021-01-21 17:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
It is, how else will the Repository's interface be satisfied requiring both a domain and an ID parameter?

2021-01-21 17:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +@Log4j2
Indeed, will remove `@Log4j2`

2021-01-21 17:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +@Log4j2
Indeed, will remove `@Log4j2`

2021-01-21 17:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
As an entity an Id is required so will do the composite

2021-01-21 17:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +values (42, 'SCHEDULECREATE', 5),
Good catch, you're correct, should be 6.
Will update

2021-01-21 17:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +values (201, 'INVALID_SCHEDULE_ID');
Will add response code 202 to 205

2021-01-21 17:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +       ('INVALID_SCHEDULE_ID', 201);
Will add response code 202 to 205

2021-01-21 17:26 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/converter/AccountIdConverterTest.java
> +        entityTypeEnum = EntityTypeEnum.ACCOUNT;
Good idea

2021-01-21 17:30 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ScheduleSignatureRepositoryTest.java
> +    private static final EntityId SCHEDULE_ID = EntityId.of("0.0.789", EntityTypeEnum.SCHEDULE);
Sure, can move back into `scheduleSignature()`. Future tests can optimize as need be

2021-01-21 18:04 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +@Log4j2
Removed

2021-01-21 18:04 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +@Log4j2
Removed

2021-01-21 18:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
Composite id added

2021-01-21 18:05 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/converter/AccountIdConverterTest.java
> +        entityTypeEnum = EntityTypeEnum.ACCOUNT;
Updated

2021-01-21 18:05 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/converter/AbstractEntityConverterTest.java
> +        assertThat(converter.convertToDatabaseColumn(null)).isNull();
Removed test and consolidate checks

2021-01-21 18:06 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ScheduleRepositoryTest.java
> +    protected ScheduleRepository scheduleRepository;
Updated

2021-01-21 18:08 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ScheduleSignatureRepositoryTest.java
> +    protected ScheduleSignatureRepository scheduleSignatureRepository;
Updated

2021-01-21 18:08 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ScheduleSignatureRepositoryTest.java
> +    private static final EntityId SCHEDULE_ID = EntityId.of("0.0.789", EntityTypeEnum.SCHEDULE);
Updated

2021-01-21 18:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +values (42, 'SCHEDULECREATE', 5),
Updated

2021-01-21 18:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +values (201, 'INVALID_SCHEDULE_ID');
Added

2021-01-21 18:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +       ('INVALID_SCHEDULE_ID', 201);
Added

2021-01-21 18:15 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ScheduleRepositoryTest.java
> +        assertThat(scheduleRepository.findById(schedule.getConsensusTimestamp()).get())
Repositioned

2021-01-21 22:04 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
Curious why the scheduleId is needed as part of the id, I understand the publicKeyPrefix solves multiple signatures in the same transaction.

2021-01-21 22:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
Because a `ScheduleSign` includes a `ScheduleID` in its body and is associated with that specific scheduled transaction.

2021-01-21 22:28 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
Fair, I think I mixed up concepts.

2021-01-21 22:48 UTC, steven-sheehy requested changes

2021-01-21 22:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    memo                bytea              not null,
Sorry, I take it back. This memo field doesn't need to be added after all. We can utilize the existing `t_entities.memo`. We do still need to add it to REST API output in the design.

2021-01-21 22:48 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +      "memo_base64": null,
Just "memo" and it should already be text so we don't need to base64 since it comes from `t_entities.memo` varchar.

2021-01-21 22:51 UTC, ijungmann requested changes
Just one thing, otherwise looks good.

2021-01-21 22:51 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create unique index if not exists schedule__schedule_id
Should these tables also not have hypertables defined in 2.0.1?

2021-01-21 23:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    @Id
Fair point. Every `ScheduleSign` at a given timestamp will only contain one ScheduleId but multiple differing publicKeyPrefixs.
It's fair to say that adding `scheduleId` doesn't vastly reduce the chances of conflict.
I'm wondering whether the `publicKeyPrefix` could serve as a conflict in multiple signatures since it's only the prefix.

2021-01-21 23:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create unique index if not exists schedule__schedule_id
Good catch, create the table and not the hyper tables

2021-01-22 00:56 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +      "memo_base64": null,
Updated

2021-01-22 00:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create unique index if not exists schedule__schedule_id
Updated

2021-01-22 05:00 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-01-22 17:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    memo                bytea              not null,
Reverted

2021-01-22 17:32 UTC, steven-sheehy requested changes

2021-01-22 17:32 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +  memo                bytea              not null,
Remove

2021-01-22 17:32 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +      "memo": null,
Add an example memo "Created per council decision dated 1/21/21"

2021-01-22 17:32 UTC, steven-sheehy commented on docs/design/scheduled-transactions.md
> +  "memo_base64": null,
```
"memo": "Created per council decision dated 1/21/21"
```

2021-01-22 17:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +@ToString(exclude = {"memo", "transactionBody"})
Remove memo and use `@ToString.Exclude`

2021-01-22 17:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    private ScheduleSignature.Id scheduleSignatureId;
Would prefer just `id` as `ScheduleSignature.getScheduleSignatureId()` is redundant.

2021-01-22 17:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    public_key_prefix   bytea  not null,
I think we can now create a unique index on `consensus_timestamp` and `public_key_prefix`. We can do this if we ensure when we're importing any `ScheduleCreate` or `ScheduleSign` signature map to collapse the same public key prefixes either using last one in or first one in wins. We can check with engineering to see how they handle that scenario.

2021-01-22 21:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    public_key_prefix   bytea  not null,
Yes that's true based on earlier discussion.
Should we have an independent index for timestamp also as that will be a filter param when searching

2021-01-22 21:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    public_key_prefix   bytea  not null,
I also think `schedule_id` and `consensus_timestamp` should be `desc` ordered

2021-01-22 21:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ScheduleSignature.java
> +    private ScheduleSignature.Id scheduleSignatureId;
Updated

2021-01-22 21:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +@ToString(exclude = {"memo", "transactionBody"})
Updated

2021-01-22 21:47 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +  "memo_base64": null,
Updated

2021-01-22 21:47 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +      "memo": null,
Updated

2021-01-22 21:47 UTC, Nana-EC commented on docs/design/scheduled-transactions.md
> +  memo                bytea              not null,
Removed

2021-01-22 22:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    public_key_prefix   bytea  not null,
Agreed on desc. I don't think a separate timestamp index is necessary since it would be a subset of the existing (consensus_timestamp, public_key_prefix) and wouldn't provide any value.

2021-01-22 22:21 UTC, steven-sheehy requested changes

2021-01-22 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    on schedule (consensus_timestamp desc);
Why did we add this index? We already have a primary key which gives us an automatic unique index.

2021-01-22 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists schedule__consensus_timestamp
Remove

2021-01-22 22:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +create index if not exists schedule__consensus_timestamp
Removed

2021-01-22 22:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.0__schedule_support.sql
> +    on schedule (consensus_timestamp desc);
Removed

2021-01-22 22:26 UTC, steven-sheehy approved these changes
LGTM

2021-01-22 22:31 UTC, ijungmann submitted a review, later dismissed

2021-01-23 00:10 UTC, steven-sheehy approved these changes

2021-01-23 00:40 UTC, merged

2021-01-23 17:56 UTC, steven-sheehy commented
This task was missed: `Add a scheduled boolean to transaction table with a default of false.`

2021-01-25 06:53 UTC, Nana-EC commented
> This task was missed: `Add a scheduled boolean to transaction table with a default of false.`

Missed this. Will open a PR to add this