Update acceptance tests to use a new treasury account
hashgraph/hedera-mirror-node pull request #1480
Opened 2021-01-22 02:19 UTC by Nana-EC

**Detailed description**:
HTS Acceptance Tests occasionally fail with `TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED`, this is because the payer account is set as the treasury account and eventually hit the limit of associate tokens

- Updated `TokenClient` to take a treasury account to set on creation
- Update `hts.feature` with Background feature to ensure shared treasury account is created before tests
- Update `hts.feature` and `TokenFeature` to create a new sender account and associate for transfer tests.
- Updated `ClientConfiguration` to set no cache on WebClient calls

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-01-22 15:45 UTC, steven-sheehy requested changes
There's a lot of misuse of `@Retryable`. We should consider moving the annotation into the `TokenClient` and annotate all methods. Or we should consider using `RetryTemplate` directly in `TokenClient` around the few execute methods and query methods.

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void setKycStatus(int kycStatus, ExpandedAccountId accountId) throws HederaStatusException {
This looks to be only called internally now so should it be private?

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
>      @Retryable(value = {StatusRuntimeException.class}, exceptionExpression = "#{message.contains('UNAVAILABLE') || " +
Retryable doesn't work on internally called methods.

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> -    public void setFreezeStatus(int freezeStatus) throws HederaStatusException {
Same problem. Should be private and Retryable doesn't work.

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void associateRecipientWithToken() throws HederaStatusException {
This is no longer retrying

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Given("I successfully onboard a new token account with freeze status {int} and kyc status {int}")
I think the old terminology was correct. It is creating a token (that just happens to have an implicit token association to the treasury), not doing an explicit token associate like it sounds.

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void onboardNewTokenAccount(int freezeStatus, int kycStatus) throws HederaStatusException {
private or just collapse the two methods as it's not reused

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void associateSenderWithToken() throws HederaStatusException {
Retryable?

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        transferTokens(tokenId, amount, treasuryAccount, tokenClient.getSdkClient().getOperatorId());
not retrying

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void transferTokensToRecipient(int amount) throws HederaStatusException {
Not retrying

2021-01-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +        Then I fund <amount> tokens to payer
Change to payer is fine but think transfer is more appropriate than fund

2021-01-22 16:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +        Then I fund <amount> tokens to payer
Transfer is more important but we want to have a base case that tests just the funding of a non treasury account that will become a sender for other transfers.

2021-01-22 17:02 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Given("I successfully onboard a new token account with freeze status {int} and kyc status {int}")
The old terminology had an implicit assumption that the sender (also the payer) was set up to transact with the token.
Since the first test covers this there's no need to repeat those steps for future tests that are dependent on it, it's easier to just group it.

Plus onboarding (creating token, associating and funding a sender account will be common practice in HTS usage) so we want that groups coverage.

2021-01-22 19:27 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +        Then I fund <amount> tokens to payer
I can rename it to the below if that's what you meant
```suggestion
        Then I transfer <amount> tokens to payer
```

2021-01-22 19:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void setKycStatus(int kycStatus, ExpandedAccountId accountId) throws HederaStatusException {
Made private and moved down.

2021-01-22 19:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
>      @Retryable(value = {StatusRuntimeException.class}, exceptionExpression = "#{message.contains('UNAVAILABLE') || " +
Removed

2021-01-22 19:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> -    public void setFreezeStatus(int freezeStatus) throws HederaStatusException {
Updated, removed and moved

2021-01-22 19:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void associateRecipientWithToken() throws HederaStatusException {
Updated

2021-01-22 19:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void onboardNewTokenAccount(int freezeStatus, int kycStatus) throws HederaStatusException {
made private and moved down

2021-01-22 19:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void associateSenderWithToken() throws HederaStatusException {
Added

2021-01-22 19:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        transferTokens(tokenId, amount, treasuryAccount, tokenClient.getSdkClient().getOperatorId());
Updated

2021-01-22 19:43 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void transferTokensToRecipient(int amount) throws HederaStatusException {
Updated

2021-01-22 20:59 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +        Then I fund <amount> tokens to payer
Yeah, that format is what I was suggesting.

2021-01-22 21:09 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +        Then I fund <amount> tokens to payer
Will update

2021-01-22 22:12 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-01-22 22:36 UTC, ijungmann approved these changes

2021-01-23 00:09 UTC, steven-sheehy approved these changes

2021-01-23 00:22 UTC, merged