Refactor record file v5
hashgraph/hedera-mirror-node pull request #1499
Opened 2021-01-25 16:30 UTC by xin-hedera

**Detailed description**:

- Add `ValidatedDataInputStream` which extends `DataInputStream` by providing validation on byte, int, and byte array fields
- Add `AbstractStreamObject` and refactor child classes `HashObject`, `RecordStreamObject`, and `SignatureObject`
- Add `RecordFileV2V5DownloaderTest`
- Fix `RecordFileParserPerformanceTest` and add `RecordFileParserV5PerformanceTest`

**Which issue(s) this PR fixes**:
Fixes #1472 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-01-26 04:45 UTC, ijungmann requested changes
Still looking, just a few things I spotted thus far.

2021-01-26 04:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/DownloaderProperties.java
> +    void setBatchSize(int batchSize);
Is this just for testing ease, or is there an expected use for this in source code?

2021-01-26 04:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/AbstractStreamObject.java
> +    public static class Header {
I'm a little skeptical of needing an inner value class to hold two attributes, when the outer class itself only has one attribute, the inner class.  Is there an expectation this will evolve or some particular reason this is needed?

2021-01-26 04:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/ValidatedDataInputStream.java
> +    private final String filename;
nit: I like this class, but I'm a little caught up on the name, only because by requiring a filename it's a DataInputStream that also involves files.  I don't know if that should be reflected in the above comment or how best to reflect that, but if feels like it should be mentioned somewhere.  I know we want to get away from files/the file system, but for the time being it feels appropriate.  I'd like to see if anyone else has feedback here.

2021-01-26 04:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        try (BufferedInputStream bis = new BufferedInputStream(streamFileData.getInputStream());
I'm a little concerned that this is now nesting BufferedInputStreams (created by the Composite)

2021-01-26 15:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/DownloaderProperties.java
> +    void setBatchSize(int batchSize);
this should be in the interface so that we don't duplicate the same code for the test case `maxDownloadItemsReached` in each concrete test class.

there are other methods in this interface which are also only used in the downloader test for the same purpose.

2021-01-26 15:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/AbstractStreamObject.java
> +    public static class Header {
it's for encapsulation, logically we can designate the class ID and class version as the header of the serialized object

2021-01-26 15:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        try (BufferedInputStream bis = new BufferedInputStream(streamFileData.getInputStream());
previously we made the decision to use `InputStream` in `StreamFileData` that's why we need to wrap it. The only concern I can think of is performance penalty which is negligible as memory copy is cheap. we can run the performance  test to check.

2021-01-26 16:50 UTC, ijungmann requested changes
Looks good, couple more tiny things.

2021-01-26 16:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                messageDigestMetadata);
Could you add a small comment here just explaining the need for multiple DIS?  I understand it, but it took me a little bit, and I think for future reference it would be useful.

2021-01-26 16:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +             ValidatedDataInputStream dis = new ValidatedDataInputStream(digestInputStream, filename)) {
I think I'd prefer this variable be named `vdis` or something to reflect the new type (here and elsewhere in the code).

2021-01-26 16:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +        )) {
nit: could go on line above.

2021-01-26 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                messageDigestMetadata);
sure

2021-01-26 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +             ValidatedDataInputStream dis = new ValidatedDataInputStream(digestInputStream, filename)) {
sure

2021-01-26 16:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV2.java
> +        )) {
sure, guess it's IDEA auto format

2021-01-26 18:59 UTC, Nana-EC reviewed
1st pass, will circle back

2021-01-26 18:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/ValidatedDataInputStream.java
> +    private final String filename;
If it's just a case of naming you could try `ValidatedFileDataInputStream`.
Also reflecting that in comments makes sense.

2021-01-26 18:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/AbstractStreamObject.java
> +@Getter
You could use `@Data` and get all these in addition to `@Setter` and `@ToString`, unless your intention is to prevent those additional 2

2021-01-26 18:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/ValidatedDataInputStream.java
> +    private void validate(Object expected, Object actual, String sectionName, String fieldName) {
nit: suggestion if useful. You could have this validate method return the `actual` object.
Then in all the cases where you do
```java
         validate(expected, actual, sectionName, fieldName);
         return actual; 
```
you could do
```java
         return validate(expected, actual, sectionName, fieldName);
```

2021-01-26 20:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/DownloaderProperties.java
> +    void setBatchSize(int batchSize);
Makes sense.

2021-01-26 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        try (BufferedInputStream bis = new BufferedInputStream(streamFileData.getInputStream());
Alright, yeah, my debate was whether reworking it to cast it somehow (which would also couple it more) would be worth the performance hit, but if the performance hit is minimal I'm not worried about it.

2021-01-26 20:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        try (BufferedInputStream bis = new BufferedInputStream(streamFileData.getInputStream());
ran the v5 parser performance test, single BufferedInputStream v.s. double, 10 iterations, parsing 11 large record files per iteration, average tps wise, the result is 21653 vs 21414, single performs 1.1% better

2021-01-26 20:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/ValidatedDataInputStream.java
> +    private final String filename;
renamed it to `resourceName` and changed the comment in the constructor to:

`the name of the resource in is created from`

2021-01-26 20:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/AbstractStreamObject.java
> +@Getter
added `@Data` but still have to keep `@RequiredArgsConstructor`, otherwise lombok won't generate the constructor `AbstractStreamObject(Header header)`

2021-01-26 20:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/ValidatedDataInputStream.java
> +    private void validate(Object expected, Object actual, String sectionName, String fieldName) {
made the change

2021-01-26 20:36 UTC, steven-sheehy requested changes

2021-01-26 20:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +            signatureObject = new SignatureObject(dis, "metadata");
Reusing variables for different objects is confusing and brittle, in my opinion. Prefer `signatureObjectFile` and `signatureObjectMetadata`.

2021-01-26 20:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/signature/SignatureFileReaderV5.java
> +                new BufferedInputStream(signatureFileData.getInputStream()),
Same, no need to rebuffer since composite already does.

2021-01-26 20:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/AbstractStreamObject.java
> +    public static class Header {
I agree with Ian. We should try to match the objects as closely as possible to the ones in the spec document. The header is not a separate object there. Instead, the classId and classVersion are common fields to all stream objects. It provides no value to us to group them and incurs an extra level of nesting when we want to retrieve them: `hashObject.getHeader().getClassId()` vs `hashObject.getClassId()`.

2021-01-26 20:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/HashObject.java
> +    public HashObject(Header header, int digestType, byte[] hash) {
Not sure where this constructor is used. Guessing it's for tests? If so, we should mark it as non-public

2021-01-26 22:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        try (BufferedInputStream bis = new BufferedInputStream(streamFileData.getInputStream());
Agree and removed the extra buffered input stream for all readers except v5 record file reader. The extra buffered input stream in v5 avoid the double read of class ID fields to propagate to the entire file digest input stream.

2021-01-26 22:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        ) {
nit: formatting (can go on previous line)

2021-01-26 23:01 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-01-27 17:24 UTC, steven-sheehy approved these changes
LGTM

2021-01-27 17:25 UTC, ijungmann approved these changes

2021-01-27 17:51 UTC, Nana-EC approved these changes
LGTM

2021-01-27 19:29 UTC, merged