Monitor logging
hashgraph/hedera-mirror-node pull request #1501
Opened 2021-01-25 22:18 UTC by steven-sheehy

**Detailed description**:
- Add a default monitor configuration file and allow a custom monitor configuration to override individual properties
- Add `frontend-maven-plugin` to integrate REST module into Maven lifecycle
- Add incoming request/response logs to monitor
- Add log4js to monitor and replace console logs
- Add logs for failed checks including HTTP status code and URLs
- Add HTTP status code and text to REST API error log
- Change default monitor limit from 1000 to 10 to reduce load
- Change stale resource check to pretty print duration
- Change stateproof API to return bad gateway 502 for file download errors since mirror is acting as a gateway and to differentiate between other 503 errors so we can return a non-generic error message.
- Fix leaking internal database and config error messages to client

**Which issue(s) this PR fixes**:
Fixes #761
Fixes #1463

**Special notes for your reviewer**:

```
2021-01-25T14:56:33.964-0600 INFO Running tests
2021-01-25T14:56:34.001-0600 ERROR Test balance failed for local: Stale balance was 1y 107d 4h 41m 34s old
2021-01-25T14:56:34.017-0600 ERROR Test transaction failed for local: Stale transaction was 1y 107d 4h 17m 3s old
2021-01-25T14:56:34.090-0600 INFO Completed tests run for local with 11/14 tests passed
2021-01-25T14:58:02.551-0600 INFO ::1 GET /api/v1/status returned 200: 11/14 tests passed
```

```
ERROR Test account failed against local: FetchError: request to http://127.0.0.1:5551/api/v1/accounts?limit=10 failed, reason: connect ECONNREFUSED 127.0.0.1:5551
```

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-26 17:38 UTC, ijungmann requested changes
Couple small things.

2021-01-26 17:38 UTC, ijungmann commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> + * @param {Object} server server address in the format of http://ip:port
nit: comment does not reflect new format.

2021-01-26 17:38 UTC, ijungmann commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> + * @param {Object} server server address in the format of http://ip:port
This is also the case for `checkResourceFreshness` below

2021-01-26 17:38 UTC, ijungmann commented on hedera-mirror-rest/monitoring/monitor_apis/monitor_tests.js
>   * @param {String} address server address in the format of http://ip:port
nit: comment needs updating

2021-01-26 17:54 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> + * @param {Object} server server address in the format of http://ip:port
Updated `testRunner`. `checkResourceFreshness` did not need updating.

2021-01-26 17:55 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/monitor_tests.js
>   * @param {String} address server address in the format of http://ip:port
Updated

2021-01-26 20:19 UTC, Nana-EC submitted a review, later dismissed
Looks good, had a nit suggestion.

2021-01-26 20:19 UTC, Nana-EC commented on hedera-mirror-rest/monitoring/monitor_apis/server.js
> +  logger.info(
nit: can move the info log and response set to a shared method since it's duplicated below.

2021-01-26 20:29 UTC, ijungmann submitted a review, later dismissed

2021-01-26 20:38 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/server.js
> +  logger.info(
I considered that. There's too many variables and of different types to warrant that. Note that the status object differs for each as one is an array and the other is a object

2021-01-26 21:54 UTC, xin-hedera requested changes
need to update README.md

2021-01-26 21:54 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
> +  "lockfileVersion": 2,
`lockfileVersion` keeps boucing between 1 and 2, guess it's due to different npm version. dependabot changes it to 1. We need to agree on one, and make changes to dependabot if possible and needed.

2021-01-26 21:54 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/package.json
>    },
missing module `extend`

2021-01-26 22:37 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
> +  "lockfileVersion": 2,
Seems like a [bug](https://github.com/dependabot/dependabot-core/issues/2643) in dependabot? Not sure I can do anything about this.

2021-01-26 22:44 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/package.json
>    },
I left it off since it's already included as a transitive dependency of another module and wanted to avoid having to maintain versions manually. Let me know if you still want to add it explicitly.

2021-01-26 23:13 UTC, Nana-EC commented on hedera-mirror-rest/monitoring/monitor_apis/server.js
> +  logger.info(
Sounds good

2021-01-26 23:19 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
> +  "lockfileVersion": 2,
someone expressed concern about dependabot only supporting version 1 and it most likely will recreate a new version 1 package-lock.json file with a dependency bump

2021-01-26 23:20 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/package.json
>    },
got you. that works!

2021-01-26 23:49 UTC, steven-sheehy commented
Updated README

2021-01-26 23:53 UTC, ijungmann submitted a review, later dismissed

2021-01-26 23:54 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
> +  "lockfileVersion": 2,
I'm not sure how you want me to address this. Nor do I think it is directly related to this ticket and seems a general problem or a dependabot bug.

2021-01-27 04:44 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
> +  "lockfileVersion": 2,
Let's discuss whether this needs to be addressed and how in scrum.

2021-01-27 04:49 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-01-27 17:13 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
> +  "lockfileVersion": 2,
I think I see what you mean now. I've changed the pom.xml to use npm 6 and also added `npm install` for monitor to the pom. That changed it back to `lockfileVersion=1` and greatly reduced the diff size.

2021-01-27 17:42 UTC, xin-hedera approved these changes
LGTM

2021-01-27 17:54 UTC, Nana-EC approved these changes
LGTM

2021-01-27 18:06 UTC, merged