Add schedule transactions parsing logic to importer
hashgraph/hedera-mirror-node pull request #1503
Opened 2021-01-26 03:07 UTC by Nana-EC

**Detailed description**:
Add support to importer to parse scheduled transaction logic

**Which issue(s) this PR fixes**:
Fixes #1465 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-01-26 21:42 UTC, steven-sheehy requested changes

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ScheduleCreateTransactionHandler.java
> +    public void updateEntity(Entities entity, RecordItem recordItem) {
This will need to update the memo as well. Not sure if that's in the proto yet. If not, we should create a follow up task.

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +TRUNCATE TABLE address_book RESTART IDENTITY CASCADE;
nit: If you're taking the time to sort, should point out that address_book should be after account_*

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        scheduleRepository.save(schedule);
Should also update the `RepositoryEntityListener`

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .orElseGet(() -> new Schedule()); // check is schedule form a previous create already exists
This is incorrect. The second `ScheduleCreate` should not override the fields in the original `ScheduleCreate`. Effectively the second `ScheduleCreate` is discarded except for its sigMap which is used to insert schedule signatures. This is why the design states If the `scheduleID` does not exist, insert a `Schedule`. There is no `else`.

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            var scheduleId = EntityId.of(recordItem.getRecord().getReceipt().getScheduleID());
Receipt will only be populated for creates. Use the scheduleID in the body.

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .orElseGet(() -> {
This can be much more succinct if we take advantage of `Optional`:

```java
  scheduleRepository.findByScheduleId(scheduleId).ifPresent(s -> {
    schedule.setExecutedTimestamp(consensusTimestamp);
    entityListener.onSchedule(schedule);
  });

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .findByScheduleId(scheduleId)
Should we use an update statement here like for token supply?

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertScheduleTransaction(RecordItem recordItem) {
Method is not named accurately as it does no inserts. Maybe `handledScheduledTransaction` or `onScheduledTransactionExecuted` or just `onScheduledTransaction`.

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            ScheduleSignature scheduleSignature = new ScheduleSignature();
As we discussed previously, we should collapsed duplicate signatures by public key prefix within a single transaction to avoid violating the unique constraint of the table. It should be first in wins or last one in wins, however engineering handles it. Unless we can confirm with engineering that they already ensure no duplicates.

2021-01-26 21:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            // currently only Ed25519 signature is supported
This is true, but we should add a check that halts parsing if `getSignatureCase() != ED25519` just in case that ever changes.

2021-01-26 21:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            } else if (tx.isScheduled()) {
A scheduled transaction should be handled just like every other transaction. In addition, it should update the execute timestamp. So this check should not be part of any other if/else.

2021-01-26 22:45 UTC, Nana-EC commented on hedera-mirror-importer/pom.xml
> +            <version>v0.11.0-alpha.3</version>
Yeah was gonna update and pull the jit stuff out before removing draft

2021-01-26 22:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean schedules = false;
Will update configuration readme

2021-01-26 22:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ScheduleCreateTransactionHandler.java
> +    public void updateEntity(Entities entity, RecordItem recordItem) {
Memo isn't available yet so will create and add to a follow up task

2021-01-26 22:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +TRUNCATE TABLE address_book RESTART IDENTITY CASCADE;
Haha true

2021-01-26 22:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        scheduleRepository.save(schedule);
Good catch

2021-01-26 22:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .orElseGet(() -> new Schedule()); // check is schedule form a previous create already exists
Will update and only create and insert a Schedule when not already present

2021-01-26 22:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            var scheduleId = EntityId.of(recordItem.getRecord().getReceipt().getScheduleID());
Right, will update

2021-01-26 22:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .orElseGet(() -> {
Actually I had create an update method which I should be using here.

2021-01-26 22:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .findByScheduleId(scheduleId)
Yep, forgot to use it here, will update

2021-01-26 22:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertScheduleTransaction(RecordItem recordItem) {
I like `onScheduledTransaction`

2021-01-26 22:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            // currently only Ed25519 signature is supported
Will add a check and throw appropriately

2021-01-26 23:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            } else if (tx.isScheduled()) {
Right, will move to appropriate location

2021-01-27 00:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            ScheduleSignature scheduleSignature = new ScheduleSignature();
Engineering has quite the complexity behind this right now, some assure an error and some cases will result in a success based on the expanded key - which we don't get.
On our end yeah taking a first in approach work, will update.

2021-01-27 00:17 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean schedules = false;
Documented

2021-01-27 00:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        scheduleRepository.save(schedule);
Updated

2021-01-27 00:30 UTC, Nana-EC commented on hedera-mirror-importer/pom.xml
> +            <version>v0.11.0-alpha.3</version>
Updated

2021-01-27 00:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +TRUNCATE TABLE address_book RESTART IDENTITY CASCADE;
Updated

2021-01-27 00:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .orElseGet(() -> new Schedule()); // check is schedule form a previous create already exists
Updated

2021-01-27 00:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            var scheduleId = EntityId.of(recordItem.getRecord().getReceipt().getScheduleID());
Updated

2021-01-27 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .orElseGet(() -> {
Updated

2021-01-27 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .findByScheduleId(scheduleId)
Updated

2021-01-27 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertScheduleTransaction(RecordItem recordItem) {
Updated

2021-01-27 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            ScheduleSignature scheduleSignature = new ScheduleSignature();
Added logic

2021-01-27 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            // currently only Ed25519 signature is supported
Added check

2021-01-27 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            } else if (tx.isScheduled()) {
Moved out

2021-01-27 16:48 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-01-27 16:54 UTC, steven-sheehy requested changes

2021-01-27 16:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    EntityId.of(body.getTransactionID().getAccountID());
Reuse `creatorAccount` already extracted.

2021-01-27 16:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TransactionBody body = recordItem.getTransactionBody();
Don't need to extract `body`, `creatorAccount` or `payerAccount` unless the `findByScheduleId` is unsuccessful. Thus can push it into inner block.

2021-01-27 17:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TransactionBody body = recordItem.getTransactionBody();
Good point, moved into inner block

2021-01-27 17:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    EntityId.of(body.getTransactionID().getAccountID());
Reused

2021-01-27 17:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ScheduleCreateTransactionHandler.java
> +    public void updateEntity(Entities entity, RecordItem recordItem) {
Captured in #1508

2021-01-27 18:07 UTC, steven-sheehy approved these changes
LGTM

2021-01-27 22:00 UTC, ijungmann approved these changes

2021-01-27 22:11 UTC, xin-hedera approved these changes
LGTM

2021-01-27 22:27 UTC, merged