Support scheduled transactions existing rest apis
hashgraph/hedera-mirror-node pull request #1506
Opened 2021-01-26 18:32 UTC by xin-hedera

**Detailed description**:

- Support `scheduled` in endpoint `/api/v1/transactions/:id`
- Support `scheduled` in endpoint `/api/v1/transactions/:id/stateproof`
- Add `scheduled` query param to `openapi.yml`
- Add test cases

**Which issue(s) this PR fixes**:
Fixes #1468 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-01-26 18:33 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  console.log(`sqlConnection will use postgresql://${dbUser}:${dbPassword}@${config.db.host}:${config.db.port}/${config.db.name}`);
for debug purpose, show the complete postgresql url with username and password

2021-01-26 18:35 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
> +  invalidFilters.forEach((filter) => {
the negative tests should run against individual invalid filter

2021-01-27 16:23 UTC, steven-sheehy requested changes

2021-01-27 16:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-25-specific-id-repeated-valid-params-schedule-true.spec.json
> +  "url": "/api/v1/transactions/0.0.10-1234567890-000000001?scheduled=true&scheduled=false&scheduled=true",
Having it true, false, true makes it impossible to determine whether it was first in wins or last in wins.

2021-01-27 16:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/stateproof-13-success-result-repeated-scheduled-false.spec.json
> +    "record_file": "c3d987c874294eb95b2df9fd36b0656623315769af2ef344c35868780102b5c0",
We should consider adding the record file name and/or timestamp to this output in the future. Makes it hard to verify results or reconstruct the S3 object without that.

2021-01-27 16:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-02-specific-id.spec.json
> +        "scheduled": true
It's really, really confusing that we are setting transaction fields like `scheduled` on a list of `cryptotransfers`. At the same time, we're also maintaining a list of `transactions` objects that don't have fields like `scheduled` but do contain a list of `transfers`. None of that makes any sense and is unnecessarily complicated. If these lists don't match the corresponding tables, it makes it very hard to grok. We should address that in the future.

2021-01-27 16:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-22-specific-id-scheduled-false.spec.json
> +      }
This should also return the duplicate transaction. If they want to filter that out, they should use the `result` query parameter.

2021-01-27 16:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-24-specific-id-repeated-valid-params-schedule-false.spec.json
> +  "url": "/api/v1/transactions/0.0.10-1234567890-000000001?scheduled=false&scheduled=true&scheduled=false",
Having it false, true, false makes it impossible to determine whether it was first in wins or last in wins.

2021-01-27 16:34 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: boolean
sure

2021-01-27 16:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    return `t.type = ${scheduleCreateProtoId}`;
this follows the design doc:

- If false, return only the `ScheduleCreate` transaction

It was implemented to show transactions with `scheduled = false`, but then I changed to follow the design.

2021-01-27 16:37 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-25-specific-id-repeated-valid-params-schedule-true.spec.json
> +  "url": "/api/v1/transactions/0.0.10-1234567890-000000001?scheduled=true&scheduled=false&scheduled=true",
Will change it to `false, false, true`

2021-01-27 16:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-22-specific-id-scheduled-false.spec.json
> +      }
same as my response how to implement `schedule=false`. this is the expected result if `false` should only return the `ScheduleCreate` transation

2021-01-27 16:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-24-specific-id-repeated-valid-params-schedule-false.spec.json
> +  "url": "/api/v1/transactions/0.0.10-1234567890-000000001?scheduled=false&scheduled=true&scheduled=false",
will change it to `true, true, false`

2021-01-27 16:40 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +    return `t.type = ${scheduleCreateProtoId}`;
Yes, that logic in the design is true if that transaction ID is linked to a `ScheduleCreate`. For other regular transactions, we should expect scheduled=false to still return the regular transaction. Perhaps you can update the design to make that a little clearer.

2021-01-27 17:22 UTC, ijungmann requested changes
Looks good, haven't seen anything additional to add, just what Steven has already mentioned.

2021-01-27 17:22 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  console.log(`sqlConnection will use postgresql://${dbUser}:${dbPassword}@${config.db.host}:${config.db.port}/${config.db.name}`);
I agree

2021-01-27 17:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  console.log(`sqlConnection will use postgresql://${dbUser}:${dbPassword}@${config.db.host}:${config.db.port}/${config.db.name}`);
Yeah I saw the code scan complain. If there is an easy way to mark it as FP once and forever I'd want to keep the change.

2021-01-27 18:02 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/stateproof-13-success-result-repeated-scheduled-false.spec.json
> +    "record_file": "c3d987c874294eb95b2df9fd36b0656623315769af2ef344c35868780102b5c0",
Probably all the file names (record & sig).

Also change the address_books to a list of timestamp and content objects.
Address book suggestion is for a future task not this one.

2021-01-27 18:34 UTC, Nana-EC requested changes

2021-01-27 18:34 UTC, Nana-EC commented on hedera-mirror-rest/stateproof.js
> +         AND scheduled = ${scheduled}`; // only the successful transaction
nit: comment now on the wrong line

2021-01-27 18:34 UTC, Nana-EC commented on hedera-mirror-rest/stateproof.js
> +const getScheduledParamValue = (filters) => {
I'm sure this logic is useful for other params where we want last in logic.
We should consider moving this logic into the `utils.buildFilterObject()`
Whereby there's a set of params that don't support repetition. If encounter they don't create an array but just overwrite the previous value

2021-01-27 18:34 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +      ret = Object.values(constants.cryptoTransferType).includes(val.toLowerCase());
nit: convention would be to move this to a `isValidCreditType()`

2021-01-27 18:56 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-01-27 19:30 UTC, xin-hedera commented on hedera-mirror-rest/stateproof.js
> +         AND scheduled = ${scheduled}`; // only the successful transaction
can't have the comment in the template literal, but I can swap `result = 22` and `scheduled = ${scheduled}`

2021-01-27 20:52 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +      ret = Object.values(constants.cryptoTransferType).includes(val.toLowerCase());
added a general function `isValidValueIgnoreCase(value, validValues)`

2021-01-27 22:01 UTC, Nana-EC commented on hedera-mirror-rest/stateproof.js
> +         AND scheduled = ${scheduled}`; // only the successful transaction
Haha you're right. Ignore that then

2021-01-27 22:53 UTC, Nana-EC approved these changes
Looks good.
My comment about moving the single value logic of `getScheduledParamValue()` to a shared utils file can be addressed in a separate PR if it's beyond this scope.

2021-01-27 23:01 UTC, ijungmann approved these changes

2021-01-27 23:02 UTC, steven-sheehy approved these changes

2021-01-27 23:31 UTC, merged