Rosetta 0.27.0 snapshot
hashgraph/hedera-mirror-node pull request #1512
Opened 2021-01-28 05:22 UTC by Nana-EC

**Detailed description**:
In order to work with Rosetta, Hedera needs to implement the [Rosetta Blockchain Standard](https://github.com/coinbase/rosetta-specifications).
Work has been done to create a working api in the `rosetta` branch. 
This should be merged into master to make the api available in future releases

- Merge `rosetta` branch into master - Contains PR's #984 , #1127 , #1128 , #1129, #1136, #1155, #1149, #1169, #1195, #1233
- Add `pom.xml` to rosetta module. Include `docker-maven-plugin` to support image deployment during CI process
- Add rosetta module to main `pom.xml` 
- Updated `docker-compose.yml` with rosetta service

**Which issue(s) this PR fixes**:
Partially addresses #810 

**Special notes for your reviewer**:
This forms the basis. Additional tasks once this is merge in will include
- Utilizing `github.com/hashgraph/hedera-sdk-go` instead of `github.com/limechain/hedera-sdk-go`
- Utilizing `hedera-mirror-node` instead of LimeChain’s forked `hedera-mirror-node` in "all in one" DOckerfile
- Updating db calls with any post V1.31 db schema changes
- Update to `operations.md` with more documentation
- Adding a helm chart
- Add go to license regex
- Update copy rights with go file coverage

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-01-28 23:08 UTC, steven-sheehy requested changes

2021-01-28 23:08 UTC, steven-sheehy commented on hedera-mirror-rosetta/pom.xml
> +    </build>
Should add a task to integrate go into maven lifecycle.

2021-01-28 23:19 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
> +    </build>
Yes, I called this out in #810 . Will create a separate task.
Was hoping to get it in with this PR but didn't want it to become too large.
[mvn-golang](https://github.com/raydac/mvn-golang) seems like a good starting option

2021-01-28 23:20 UTC, steven-sheehy requested changes

2021-01-28 23:20 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +# --------------------------------- REST --------------------------------- #
Please remove. REST API module does not run as part of Rosetta.

2021-01-28 23:20 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +RUN cd hedera-mirror-node && ./mvnw clean package -DskipTests -pl '!hedera-mirror-rest, !hedera-mirror-rosetta'
This shouldn't build grpc, monitor, etc. Should just `-pl hedera-mirror-importer`.

2021-01-28 23:21 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
> +    </build>
Created #1523 to capture it

2021-01-28 23:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init_v1.sql
> +                    createrole
Updated. Looking forward to v2 where we've sorted this out.

2021-01-28 23:32 UTC, Nana-EC commented on pom.xml
> +        <module>hedera-mirror-rosetta</module>
Added

2021-01-28 23:32 UTC, Nana-EC commented on hedera-mirror-rosetta/build/Dockerfile
> +# --------------------------------- REST --------------------------------- #
Removed

2021-01-28 23:33 UTC, Nana-EC commented on hedera-mirror-rosetta/build/Dockerfile
> +RUN cd hedera-mirror-node && ./mvnw clean package -DskipTests -pl '!hedera-mirror-rest, !hedera-mirror-rosetta'
Updated

2021-01-29 00:09 UTC, steven-sheehy approved these changes
LGTM

2021-01-29 15:35 UTC, xin-hedera approved these changes
LGTM

2021-01-29 15:48 UTC, merged