Fix issue with incomplete stubbing on Redis Slow Publish Test
hashgraph/hedera-mirror-node pull request #1520
Opened 2021-01-28 18:55 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1484 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-28 22:09 UTC, steven-sheehy commented
I'm also seeing a similar error in another test in this file: https://github.com/hashgraph/hedera-mirror-node/runs/1786439070

2021-01-29 04:57 UTC, ijungmann commented
> I'm also seeing a similar error in another test in this file: https://github.com/hashgraph/hedera-mirror-node/runs/1786439070

That's pretty wild, if I'm reading the output correctly that other test is failing because it doesn't like the stubbing in the first test, i.e. that test is fine, but it's not happy about other tests in the file.

```
Error:  Tests run: 7, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 9.567 s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest
Error:  com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish  Time elapsed: 0.692 s  <<< FAILURE!
java.lang.AssertionError
	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

Error:  com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onDuplicateTopicMessages  Time elapsed: 0.062 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 ***. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.subscribe(RedisEntityListenerTest.java:71)
	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onDuplicateTopicMessages(RedisEntityListenerTest.java:92)
```

2021-02-01 23:52 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerMockitoTest.java
> +        Mockito.reset(redisOperations);
Technically this does not need to be reset, but I felt it helped readability when it comes to the verify (calls would be 2, 2, 3, as opposed to 2, 0, 1 otherwise)

2021-02-01 23:54 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java
> +@SpringBootTest(properties = {
This is particularly for CircleCI, it seems to fail in that environment specifically without this, I'm assuming because we don't use test containers there.

2021-02-02 16:26 UTC, steven-sheehy requested changes

2021-02-02 16:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java
> +@SpringBootTest(properties = {
I'm worried if this causes yet another application context to start, slowing down tests further. Why is this even needed if we manually `properties.setEnabled(true)` in `BatchEntityListenerTest`?

2021-02-02 17:31 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerMockitoTest.java
> +class RedisEntityListenerMockitoTest {
Sure, makes sense.  Those names are changed now.

2021-02-02 17:42 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java
> +@SpringBootTest(properties = {
I think you're right that it's not needed, yesterday I pulled that line out and it failed in CCI, I put it back and it passed, but I just removed it again and it seems to be passing (3 straight passes in CCI).  I had a config typo in there at some point, so that may have been related.  Anyway, it's removed now.

2021-02-02 17:54 UTC, steven-sheehy approved these changes
LGTM

2021-02-02 18:00 UTC, Nana-EC submitted a review, later dismissed
LGTM.
Had one nit if you do circle back

2021-02-02 19:56 UTC, xin-hedera approved these changes
LGTM

2021-02-02 21:11 UTC, steven-sheehy approved these changes

2021-02-02 21:18 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java
> +        topicMessage.setConsensusTimestamp(consensusTimestamp++);
Sure, I just moved that logic in here.

2021-02-02 21:39 UTC, xin-hedera approved these changes

2021-02-02 22:28 UTC, merged