Add rosetta module to maven cycle
hashgraph/hedera-mirror-node pull request #1527
Opened 2021-01-29 21:44 UTC by Nana-EC

**Detailed description**:
Rosetta module isn't currently included in the mane build cycle

- Add `mvn-golang-wrapper` plugin to add maven cycle support to rosetta module
- Update`rosetta-api.yml` GitHub action to run maven package

**Which issue(s) this PR fixes**:
Fixes #1523 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-29 22:12 UTC, steven-sheehy requested changes

2021-01-29 22:12 UTC, steven-sheehy commented on hedera-mirror-rosetta/pom.xml
> +                            <outLogFile>${project.artifactId}-test.log</outLogFile>
We should log to files. We don't for any other build.

2021-01-29 22:12 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        run: ./mvnw clean package -pl hedera-mirror-rosetta
Surprised this works as I thought Maven required Java to be installed.

2021-01-29 22:12 UTC, steven-sheehy commented on hedera-mirror-rosetta/pom.xml
>      <description>Rosetta REST API for the Hedera Mirror Node</description>
You should disable rosetta in CircleCI.

2021-01-29 23:15 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
>      <description>Rosetta REST API for the Hedera Mirror Node</description>
Skipped for circle ci build

2021-01-29 23:15 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
> +                            <outLogFile>${project.artifactId}-test.log</outLogFile>
Removed

2021-01-30 00:12 UTC, steven-sheehy approved these changes

2021-02-01 15:33 UTC, xin-hedera commented on hedera-mirror-rosetta/pom.xml
> +        <sourceDirectory>${project.basedir}/cmd</sourceDirectory>
```suggestion
        <sourceDirectory>${project.basedir}{file.separator}cmd</sourceDirectory>
```

2021-02-01 15:34 UTC, xin-hedera commented on hedera-mirror-rosetta/pom.xml
> +                                <package>${project.basedir}/...</package>
```suggestion
                                <package>${project.basedir}{file.separator}...</package>
```

2021-02-01 15:34 UTC, xin-hedera commented on hedera-mirror-rosetta/pom.xml
> +                            <sources>${project.basedir}/cmd</sources>
```suggestion
                            <sources>${project.basedir}${file.separator}cmd</sources>
```

2021-02-01 17:11 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
> +                            <sources>${project.basedir}/cmd</sources>
Good suggestion, updated

2021-02-01 17:12 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
> +                                <package>${project.basedir}/...</package>
Good suggestion, updated

2021-02-01 17:12 UTC, Nana-EC commented on hedera-mirror-rosetta/pom.xml
> +        <sourceDirectory>${project.basedir}/cmd</sourceDirectory>
Good suggestion, updated

2021-02-01 17:14 UTC, xin-hedera approved these changes
LGTM

2021-02-01 17:18 UTC, steven-sheehy approved these changes

2021-02-01 17:56 UTC, merged