Rosetta license
hashgraph/hedera-mirror-node pull request #1529
Opened 2021-01-29 22:58 UTC by Nana-EC

**Detailed description**:
Add license support to rosetta module

**Which issue(s) this PR fixes**:
Fixes #1514 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-01-30 00:17 UTC, steven-sheehy requested changes

2021-01-30 00:17 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/domain/repositories/account.go
> + * ​
Just to confirm this is adding the hidden characters, right? Not a space character.

2021-01-30 00:17 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/domain/repositories/account.go
> +    rTypes "github.com/coinbase/rosetta-sdk-go/types"
I'm concerned about all the whitespace changes. The standard way to format go code is with `gofmt`, which will by default use tabs for everything. We should reformat using that. Then update the `.editorconfig` to use the same format for indentation. Maybe also consider adding gofmt to the mvn build or as a post commit hook.

2021-01-30 00:31 UTC, Nana-EC commented on hedera-mirror-rosetta/app/domain/repositories/account.go
> + * ​
Yeah this added the hidden character.
The original files didn't have it so the process actually failed. Had to manually add the character first for 2020 and then run the process to get it to parse and update it to 2021

2021-01-30 00:49 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/repositories/account.go
> +    rTypes "github.com/coinbase/rosetta-sdk-go/types"
agree. can run `gofmt .` in hedera-mirror-rosetta directory to fix all files once.

2021-01-30 04:09 UTC, steven-sheehy requested changes

2021-01-30 04:09 UTC, steven-sheehy commented on hedera-mirror-rosetta/test/mocks/mocks.go
> +	/*-
Whoops

2021-01-30 04:09 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/services/construction/construction_service_test.go
> +	// given:
Please update .editorconfig
```
[*.go]
indent_style = tab
```

2021-02-01 17:05 UTC, Nana-EC commented on hedera-mirror-rosetta/test/mocks/mocks.go
> +	/*-
Lol, fixed

2021-02-01 17:05 UTC, Nana-EC commented on hedera-mirror-rosetta/app/services/construction/construction_service_test.go
> +	// given:
Updated

2021-02-01 17:08 UTC, Nana-EC commented on hedera-mirror-rosetta/app/domain/repositories/account.go
> +    rTypes "github.com/coinbase/rosetta-sdk-go/types"
Ran `gofmt` and updated insert style in `.editorconfig`.
Looked into a shared git recommit hook but would have to make it so that it's shareable since you can't commit the hook file.
Might be worth a separate task as other languages could benefit from some hook logic

2021-02-01 17:19 UTC, steven-sheehy approved these changes
LGTM

2021-02-01 17:32 UTC, xin-hedera approved these changes
LGTM

2021-02-01 18:15 UTC, merged