Update rosetta data schema with post v1.30 support
hashgraph/hedera-mirror-node pull request #1530
Opened 2021-01-30 00:29 UTC by xin-hedera

**Detailed description**:

- Rename record_file table hash columns so `hash` is the chained hash of the file and `prev_hash` is that of the previous file
- Change importer accordingly following the record_file column change
- Update rosetta data schema with post v1.30 support

**Which issue(s) this PR fixes**:
Fixes #1515 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-01 17:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.2__rename_record_file_hash.sql
> +select migrate_record_file_hash();
this takes about 30s for the v5 record files in dev environment as of 1/31/2021.

2021-02-01 19:32 UTC, Nana-EC requested changes
As discussed offline there's a concern the column structure could become confusing for operators.
So it's better to go with data duplication for preV5 and populate the new `hash` column for v5 onwards

2021-02-01 20:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.2__rename_record_file_hash.sql
> + *   - the new file_hash column stores the file hash of record files if the file hash is not used as chained hash,
rename is still there as it implicitly *renames* the index

2021-02-01 20:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
> +        recordFile.setHash(Hex.encodeHexString(digest.digest()));
kept the change and also added back fileHash to `EventFile.java` so it's consistent with the same change from pre v5 record file -> v5 record file

2021-02-01 20:58 UTC, Nana-EC approved these changes
LGTM

2021-02-01 21:30 UTC, steven-sheehy requested changes

2021-02-01 21:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.2__rename_record_file_hash.sql
> +alter table if exists record_file add column if not exists file_hash character varying(96);
This is quite complex and slow as it loops over all rows multiple times. What's wrong with:
```sql
alter table if exists record_file add column if not exists hash character varying(96);
update record_file set hash = coalesce(end_running_hash, file_hash);
alter table if exists record_file drop column if exists end_running_hash;
```

Alternatively, this would also be faster:
```sql
alter table if exists record_file rename column end_running_hash to hash;
update record_file set hash = file_hash where hash is null;
```

2021-02-01 21:50 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.34.2__rename_record_file_hash.sql
> +alter table if exists record_file add column if not exists file_hash character varying(96);
we have a unique index on `file_hash` after the change it'll be on `hash`.

renaming `file_hash` to `hash` preserves the index for pre v5 files and it's huge for mainnet db. so for mainnet, it may be faster.

2021-02-02 15:45 UTC, steven-sheehy approved these changes
LGTM

2021-02-02 16:02 UTC, ijungmann approved these changes

2021-02-02 16:47 UTC, merged