Rosetta operations
hashgraph/hedera-mirror-node pull request #1546
Opened 2021-02-02 01:45 UTC by Nana-EC

**Detailed description**:

- Add a `hedera-mirror-rosetta` systemd service easy run on linux server
- Add a `deploy.sh` script that handles the copying and creation of files needed to run the service
- Update `rosetta-api.yml` GitHub action to package binary file and deployment scripts
- Update `operations.md` with steps to upgrade and monitor

**Which issue(s) this PR fixes**:
Fixes #1517 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-02-02 21:09 UTC, steven-sheehy requested changes

2021-02-02 21:09 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/hedera-mirror-rosetta.service
> +SuccessExitStatus=143
143 is specific to Spring Boot. This should probably just be 0.

2021-02-02 21:09 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/deploy.sh
> +      apiVersion: 1.4.4
Why are we hardcoding all these default values? Do subsequent configuration files overwrite the values from the previous? We should fix it so that it recursively extends like the other modules, if so. Then this config should just be the minimal needed.

2021-02-02 21:09 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/hedera-mirror-rosetta.service
> +ExecStart=/opt/lib/hedera-mirror-rosetta/hedera-mirror-rosetta
Don't need to duplicate working directory here. `ExecStart=hedera-mirror-rosetta`

2021-02-02 21:09 UTC, steven-sheehy commented on README.md
> +```shell
I'm not a fan of all these operations commands that live in the top level README and duplicate the ones in the operations.md. We will need to remove these at some point and just provide links.

2021-02-02 21:09 UTC, steven-sheehy commented on README.md
> +    Successfully connected to Database
This note might be good to have in operations.md too

2021-02-02 21:22 UTC, Nana-EC commented on .github/workflows/rosetta-api.yml
> +          mv ${MODULE}/scripts/${MODULE}.service ${NAME}/scripts/${MODULE}.service
Yeah other modules only have deployment related scripts in their folder. 
Rosetta has a few move so I wanted to only put the ones that have to do with deployment and not include the validation ones

2021-02-02 21:24 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +          mv ${MODULE}/scripts/${MODULE}.service ${NAME}/scripts/${MODULE}.service
Maybe put them in a subfolder `scripts/deploy`?

2021-02-02 21:39 UTC, Nana-EC commented on README.md
> +```shell
Will move them all to Operations and provide links

2021-02-02 22:01 UTC, Nana-EC commented on hedera-mirror-rosetta/cmd/config.go
> +	if "" != extConfigFile {
Figured this was a special case hence putting it outside.
However, looking again it's not like spring where the main config would exist in the classpath so all the files are essentially external configuration

2021-02-02 22:04 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/deploy.sh
> +      apiVersion: 1.4.4
I realized the `GetConfig()` in `config.go` currently fails fast if the file doesn't exist.
Since the 1st two files aren't on the filesystem there's no configs to extend.
Importer and grpc modules executable get the extension logic cause of Spring and the classpath

2021-02-02 22:07 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/hedera-mirror-rosetta.service
> +ExecStart=/opt/lib/hedera-mirror-rosetta/hedera-mirror-rosetta
I thought so to but I was getting the following error
```
/etc/systemd/system/hedera-mirror-rosetta.service:7: Executable path is not absolute: hedera-mirror-rosetta
```

2021-02-02 22:08 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/hedera-mirror-rosetta.service
> +ExecStart=/opt/lib/hedera-mirror-rosetta/hedera-mirror-rosetta
I can remove the working directory also

2021-02-02 22:11 UTC, Nana-EC commented on docs/operations.md
> +- `/opt/hedera-mirror-rosetta/application.yml` - Configuration file
np, had it like that first, can revert to be consistent with importer and grpc.

2021-02-02 22:28 UTC, Nana-EC commented on hedera-mirror-rosetta/cmd/config.go
> +	if "" != extConfigFile {
Will move log into `GetConfig`. There's already an if statement to check if the file exists or not

2021-02-02 22:33 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/deploy.sh
> +      apiVersion: 1.4.4
It should exist as there's a checked in `config/application.yaml`. If it's not finding that when deployed we need to address.

2021-02-02 22:36 UTC, Nana-EC commented on README.md
> +    Successfully connected to Database
Added there too

2021-02-02 22:59 UTC, Nana-EC commented on .github/workflows/rosetta-api.yml
> +          mv ${MODULE}/scripts/${MODULE}.service ${NAME}/scripts/${MODULE}.service
Can do

2021-02-03 00:05 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/deploy.sh
> +      apiVersion: 1.4.4
Go 1.16 will add `embed` which handles this. Other 3rd party options exists which I can be explored.
For now will bundle the default config and ship.
That's actually not a bad idea as when new configs are added there's always a reference that ships with the new code as to how configs should be populated.

2021-02-03 02:04 UTC, Nana-EC commented on README.md
> +```shell
Moved

2021-02-03 02:04 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/hedera-mirror-rosetta.service
> +ExecStart=/opt/lib/hedera-mirror-rosetta/hedera-mirror-rosetta
Remove working directory

2021-02-03 02:07 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/deploy.sh
> +      apiVersion: 1.4.4
Added a `application-deploy.yml` with placeholders. This file is added to the deployment.
When the deploy script is run if no initial config file exists a new file will be configured and copied to the `/usr/etc` location
Embedded file logic can be addressed in a separate ticket since there's some testing to be done and since a more scalable method will be added in a new version of go vs using a 3rd party package

2021-02-03 02:07 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/hedera-mirror-rosetta.service
> +SuccessExitStatus=143
Updated

2021-02-03 02:07 UTC, Nana-EC commented on docs/configuration.md
> +To utilize an external configuration file with customs values the `HEDERA_MIRROR_ROSETTA_API_CONFIG` variable should be set e.g. `HEDERA_MIRROR_ROSETTA_API_CONFIG=/Users/Downloads/hedera-mirror-roset
Moved and updated

2021-02-03 02:07 UTC, Nana-EC commented on docs/operations.md
> +- `/opt/hedera-mirror-rosetta/application.yml` - Configuration file
Moved to `/usr` and tested deployment

2021-02-03 02:08 UTC, Nana-EC commented on hedera-mirror-rosetta/cmd/config.go
> +	if "" != extConfigFile {
Moved

2021-02-03 02:08 UTC, Nana-EC commented on docs/operations.md
> +## ROSETTA API
Updated

2021-02-03 02:08 UTC, Nana-EC commented on docs/configuration.md
> +To utilize an external configuration file with customs values the `HEDERA_MIRROR_ROSETTA_API_CONFIG` variable should be set e.g. `HEDERA_MIRROR_ROSETTA_API_CONFIG=/Users/Downloads/hedera-mirror-roset
Updated

2021-02-03 02:08 UTC, Nana-EC commented on README.md
> +#### ROSETTA API
Updated

2021-02-03 02:08 UTC, Nana-EC commented on README.md
> +### Running Mirror Node (Importer, gRPC API, Monitor, REST API and ROSETTA API)
Removed

2021-02-03 02:08 UTC, Nana-EC commented on .github/workflows/rosetta-api.yml
> +          mv ${MODULE}/scripts/${MODULE}.service ${NAME}/scripts/${MODULE}.service
Moved

2021-02-03 16:40 UTC, steven-sheehy commented on docs/operations.md
> +- `/opt/lib/hedera-mirror-rosetta` - Binaries
Forgot to update these paths.

2021-02-03 16:40 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/deploy.sh
> +      apiVersion: 1.4.4
Thanks. Please open a ticket to track embedded config.

2021-02-03 16:46 UTC, ijungmann submitted a review, later dismissed
Looks good, couple of minor nits if you want to address them.

2021-02-03 16:46 UTC, ijungmann commented on README.md
> +the Mirror Node also provides a [Rosetta API](https://www.rosetta-api.org/docs/welcome.html) complying REST API server.
nit: just a personal preference.
```suggestion
the Mirror Node also provides a [Rosetta API](https://www.rosetta-api.org/docs/welcome.html) compliant REST API server.
```

2021-02-03 16:46 UTC, ijungmann commented on docs/operations.md
> +The Rosetta API runs on [Go](https://golang.org/) and should be able to run on any platform that golang supports.
nit:
```suggestion
The Rosetta API runs on [Go](https://golang.org/) and should be able to run on any platform that Golang supports.
```

2021-02-03 17:19 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-02-03 17:44 UTC, Nana-EC commented on docs/operations.md
> +The Rosetta API runs on [Go](https://golang.org/) and should be able to run on any platform that golang supports.
Updated

2021-02-03 17:44 UTC, Nana-EC commented on README.md
> +the Mirror Node also provides a [Rosetta API](https://www.rosetta-api.org/docs/welcome.html) complying REST API server.
The better choice. :) Updated.

2021-02-03 17:44 UTC, Nana-EC commented on docs/operations.md
> +- `/opt/lib/hedera-mirror-rosetta` - Binaries
Updated

2021-02-03 17:45 UTC, steven-sheehy approved these changes
LGTM

2021-02-03 18:16 UTC, ijungmann approved these changes
LGTM

2021-02-03 20:01 UTC, merged