Remove filesystem dependency
hashgraph/hedera-mirror-node pull request #1554
Opened 2021-02-05 18:55 UTC by steven-sheehy

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #918 

**Special notes for your reviewer**:
Still working on fixing tests, adding properties, v2 schema, removing dead code, etc.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-02-08 20:12 UTC, Nana-EC reviewed
Looking good so far, will circle back

2021-02-08 20:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.0__remove_filesystem.sql
> +delete
nit: add comments either for the deletes or at the top of the file with the intended migration logic reasoning.

2021-02-10 23:54 UTC, ijungmann reviewed
Didn't look at any of the tests.  Looks really good, just a couple things I spotted.

2021-02-10 23:54 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +//        assertThat(Utility.verifyHashChain(actualPrevFileHash, expectedPrevFileHash, verifyHashAfter, fileName))
Commented out code.

2021-02-11 00:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +    private Duration startDateAdjustment = Duration.ofSeconds(30L);
Actually, we explicitly are hiding this property as it's for internal use. But there are other new properties that I need to document that I haven't gotten to yet.

2021-02-11 00:32 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +    private Duration startDateAdjustment = Duration.ofSeconds(30L);
Ah, got it.

2021-02-11 20:45 UTC, steven-sheehy commented
I had to change every line in the `record_file.sql `dump to add the now required file_hash field. This makes the lines added and removed jump up quite a bit.

2021-02-12 18:44 UTC, Nana-EC requested changes
Looking good.
Plus points for all the removed code.
Some recommendations and points of clarification.

2021-02-12 18:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @ToString.Exclude
nit: move string excludes to class level `@ToString` annotation

2021-02-12 18:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setQueueCapacity(40);
Should these be default static variables?

2021-02-12 18:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +    constraint event_file__hash unique (hash)
q: is this not already ensured by the network? Not sure if it will add unnecessary overhead once event stream are supported

2021-02-12 18:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +create table if not exists event_file
missing comment section of general migration intent, with more explicit comments on sql commands where needed

2021-02-12 18:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> -LOCK TABLE t_application_status IN ACCESS EXCLUSIVE MODE;
Integration tests should run a lot smoother now :)

2021-02-12 18:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/IntegrationConfiguration.java
> +        return IntegrationFlows.from(CHANNEL_STREAM)
Design choice question. As TPS goes up and eventually event stream support is added would it be better to have separate channels per stream type?
REST and gRPC API's rely on record data so we'd want to prioritize their processing for HCS and HTS latency prioritization.
This also preemptively addresses scaling for new stream types in the future.

2021-02-12 18:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/IntegrationConfiguration.java
> +        return IntegrationFlows.from(CHANNEL_STREAM)
This is a direct channel in which "the invocation will occur in the sender's thread." So there's no queuing or thread contention. It's basically a direct method call via reflection.

2021-02-12 18:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +create table if not exists event_file
Yeah, you already have a similar comment above that I haven't gotten around to addressing. :)

2021-02-12 18:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +    constraint event_file__hash unique (hash)
It should be. We have a similar constraint/unique index on record file. It's used to speed up queries on the record file hash. I can remove it for now until we actually have those queries for events.

2021-02-12 19:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setQueueCapacity(40);
What benefit does making them static provide? This class is a singleton and only instantiated once by Spring. Making it static increases the variables scope and requires 2 lines instead of 1, one for the static and one for the set invocation. Plus keeping them inside the constructor keeps all the sub-class defaults declared in one place.

2021-02-12 19:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @ToString.Exclude
I prefer the ToString annotations as they're more decentralized and don't depend on magic strings that can change if the field is renamed.

2021-02-12 20:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        DateRangeFilter filter = new DateRangeFilter(filterStartDate, endDate);
It's not the same. Filters don't care about start date adjustments.

2021-02-12 20:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +    public Instant getEffectiveStartDate(DownloaderProperties downloaderProperties) {
See previous comment. It's not quite the same logic.

2021-02-12 20:03 UTC, steven-sheehy commented on README.md
> -- [Database](docs/database.md)
Can open a ticket for db docs.

2021-02-12 21:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        DateRangeFilter filter = new DateRangeFilter(filterStartDate, endDate);
Sounds good

2021-02-12 21:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    @ToString.Exclude
Makes sense. We should probably start being consistent in other classes going forward then

2021-02-12 21:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +    constraint event_file__hash unique (hash)
Okay. You can leave it. Might get missed in adding it back.
Either works for me

2021-02-13 15:54 UTC, steven-sheehy commented
The V2 REST API periodically fails. This seems to be happening for other PRs too. Will open a ticket.
```
  ● DB integration test - transactions.reqToSql - no query string - 3 txn 9 xfers

    error: insert/update/delete not permitted on chunk "_hyper_15_1_chunk"

      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:424:60)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:264:16)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:116:24)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:19:38)
```

The Rosetta CLI validation periodically fails. This seems to be happening for other PRs too. Will open a ticket.
```
Run bash ./wait-for-mirror-node.sh
Waiting for Mirror Node to start syncing
Error: Process completed with exit code 56.
```

2021-02-13 22:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EventFile.java
> +    private Long consensusStart;
I think it would be too tricky since some of them have all args constructors and builders. Also, they don't have all the same fields and balance doesn't have consensus start and end.

2021-02-13 23:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.0__remove_filesystem.sql
> +delete
Added some comments

2021-02-13 23:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/IntegrationConfiguration.java
> +public class IntegrationConfiguration {
Sure, renamed to `MessagingConfiguration`.

2021-02-13 23:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +            effectiveStartDate = lastFileInstant;
Extracted to a boolean.

2021-02-13 23:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +     * Unless startDate or demo network is set, then those take precedence. Since 'foo.rcd' is lexicographically before
Done

2021-02-13 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +//        assertThat(Utility.verifyHashChain(actualPrevFileHash, expectedPrevFileHash, verifyHashAfter, fileName))
Moved test code to Downloader

2021-02-13 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +    @DurationMin(seconds = 0L)
I'm not sure the importance of this exact value, just moved it from stream specific to here.

2021-02-13 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/IntegrationConfiguration.java
> +    public static final String CHANNEL_STREAM = "stream";
Commented added

2021-02-13 23:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +create table if not exists event_file
Commented added

2021-02-16 20:39 UTC, xin-hedera requested changes

2021-02-16 20:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +where load_end is null;
this may take quite some time in production environment. the faster way can be based on the fact that if there are such rows, they are contiguous and at the end of the table.

2021-02-16 21:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/event/EventFileParser.java
> +        }
I agree, but think this ticket is big enough and would prefer to refactor all the file parsers at once in a future sprint.

2021-02-16 21:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
Removed

2021-02-16 22:19 UTC, steven-sheehy commented on README.md
> -- [Database](docs/database.md)
Opened https://github.com/hashgraph/hedera-mirror-node/issues/1583

2021-02-16 22:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/event/EventFileParser.java
> +        }
sure

2021-02-17 19:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        if (lastStreamFile.get().isEmpty()) {
True, working on a fix.

2021-02-17 20:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +where load_end is null;
The delete took 10s against a local record_file backup from mainnet with ~13M rows and the same indexes.

2021-02-17 20:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EventFile.java
> +    private Long consensusStart;
Sounds good, don't want to make the downloader flow any more tricky.

2021-02-17 20:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.1__remove_filesystem.sql
> +where load_end is null;
that's very fast!

2021-02-18 00:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        if (lastStreamFile.get().isEmpty()) {
Took a bit of refactor but should be addressed now. To fix I had to push the stream file loading into the date range processor which is more optimal anyway as it was being loaded twice before.

2021-02-18 05:00 UTC, ijungmann approved these changes
Some little nits here and there in the documentation if you want to go through them, but otherwise looks fantastic.

2021-02-18 14:59 UTC, steven-sheehy commented on docs/operations.md
> +   is empty (e.g. `/var/lib/hedera-mirror-importer/*/valid/`   where `/var/lib/hedera-mirror-importer` is the
Done

2021-02-18 14:59 UTC, steven-sheehy commented on docs/operations.md
> +   If still on a version that still downloads files to the filesystem, ensure the valid directory for each stream type
Done

2021-02-18 14:59 UTC, steven-sheehy commented on docs/installation.md
> +To achieve this the `docker-compose.yml` can be updated to set the postgres `db` service replicas to 0 whiles removing
Done

2021-02-18 15:00 UTC, steven-sheehy commented on docs/installation.md
> +Rosetta default network configuration:
Done

2021-02-18 15:00 UTC, steven-sheehy commented on docs/installation.md
> +change the db user names, passwords and schema as appropriate.
Done

2021-02-18 15:00 UTC, steven-sheehy commented on docs/installation.md
> +change the `db_name`, `db_user`, `db_password` `db_owner`, `grpc_user`, `grpc_password`, `rosetta_user`
Done

2021-02-18 15:00 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.balance.frequency`                    | 100ms                   | How often to poll for new messages. Can accept duration units like `10s`, `2m` etc.            |
Done

2021-02-18 17:11 UTC, xin-hedera requested changes

2021-02-18 17:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +    public <T extends StreamFile> Optional<T> getLastStreamFile(StreamType streamType) {
need to update the comments to reflect the new return type

2021-02-18 17:45 UTC, ijungmann submitted a review, later dismissed

2021-02-18 20:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +    public <T extends StreamFile> Optional<T> getLastStreamFile(StreamType streamType) {
Done

2021-02-18 20:54 UTC, xin-hedera approved these changes

2021-02-18 22:26 UTC, Nana-EC approved these changes
LGTM

2021-02-18 22:38 UTC, merged