Add v5 stream file support to check-state-proof
hashgraph/hedera-mirror-node pull request #1555
Opened 2021-02-05 18:58 UTC by xin-hedera

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-06 19:06 UTC, Nana-EC requested changes
Looking good on 1st pass. Some nits and a request to update README logic section.
Will circle back for a 2nd pass

2021-02-06 19:06 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/transactionValidator.js
> +'use strict';
Can you update the README.md `#Logic` section.
For users of the checker it's important for them to understand the steps we take in processing.

Might need a preV5 and v5 section

2021-02-07 06:47 UTC, steven-sheehy commented on hedera-mirror-rest/check-state-proof/recordFile.js
> +const V5_START_HASH_OFFSET = 4 + (4 + 4 + 4) + 4;
A constants file is an anti pattern in my opinion. Any class you stuff unrelated things into and use it widely should be avoided to reduce coupling.

2021-02-08 17:22 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/transactionValidator.js
> +'use strict';
The only difference w.r.t the high level logic flow is v5 has an extra signature verification step. Looking at the README, the description on signature verification is generic and applies to the v5 signature file.

Instead, I'll add a sub section to highlight the changes made to support v5 files.

2021-02-08 17:22 UTC, ijungmann requested changes
Will give another pass, just a couple small things, looks good.

2021-02-08 17:22 UTC, ijungmann commented on hedera-mirror-rest/check-state-proof/recordFile.js
> +const V5_START_HASH_OFFSET = 4 + (4 + 4 + 4) + 4;
I like the idea of having some constants defined in this file since the same values pop up so many times, but I can see the reasoning for not adding to a generic constants file.

2021-02-08 17:27 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/transactionValidator.js
> +    ) {
`prettier` tells me this is the prettiest :)

2021-02-08 17:58 UTC, steven-sheehy commented on hedera-mirror-rest/check-state-proof/README.md
> +1. Metadata hash signature in signature file version 5 is verified in addition to file hash signature.
Still renders as 2, but would be nice to update to actually be 2 as well.

2021-02-08 17:58 UTC, steven-sheehy commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +const readLengthAndBytes = (buffer, minLength, maxLength, hasChecksum) => {
Is it possible `readLengthAndBytes()` and `readNBytes()` be inherited methods of `StreamObject`? They only seem to be used within a `StreamObject` and that would encapsulate their usage. You could further optimize things by storing the buffer within the StreamObject so you don't have to pass it around.

2021-02-08 18:11 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/README.md
> +the state proof check login remains the same, the following changes are made to support the file version upgrade:
typo in `login`, will fix in next commit

2021-02-08 18:16 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +const readLengthAndBytes = (buffer, minLength, maxLength, hasChecksum) => {
`readNBytes` is also used in v2 signature file parsing to read the standalone 48-byte hash

Ideally, these two methods should go into an `ExtendedBuffer` class which extends `Buffer`. but, it's very complicated to do so as 1. `Buffer` itself is not a class; 2. the `Buffer` implementation does some strict type check, so extending it can't be done by simple prototypical inheritance. After some research, I decided to leave them as is.

2021-02-08 18:17 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/README.md
> +1. Metadata hash signature in signature file version 5 is verified in addition to file hash signature.
sure

2021-02-08 18:19 UTC, steven-sheehy commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +const readLengthAndBytes = (buffer, minLength, maxLength, hasChecksum) => {
Got it, missed its use in v2.

2021-02-08 20:14 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/recordFile.js
> +const V5_START_HASH_OFFSET = 4 + (4 + 4 + 4) + 4;
Agree with the anti-pattern. The constants can stay in the file that it pertains to or originates from

2021-02-09 01:32 UTC, Nana-EC requested changes
Looks good, just missing the use of some of the constants you added and a comment request

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/recordFile.js
> +    while (buffer.readBigInt64BE() !== startHashObject.classId) {
My understanding is since the start and end Running Hash objects share the same classId, you're using the endHashObject.classId as a marker to stop looping.
Therefore ensuring all recordHashObjets in between are processed.
I think a comment on the whole would be useful to highlight that.

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    const {length, bytes} = readLengthAndBytes(buffer.slice(4), 1, SHA_384_WITH_RSA.maxLength, true);
nit:
```suggestion
    const {length, bytes} = readLengthAndBytes(buffer.slice(4), BYTE_SIZE, SHA_384_WITH_RSA.maxLength, true);
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    this.dataLength = 4 + length;
```suggestion
    this.dataLength = INT_SIZE + length;
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    this.fileHash = readNBytes(buffer.slice(1), SHA_384.length);
```suggestion
    this.fileHash = readNBytes(buffer.slice(BYTE_SIZE), SHA_384.length);
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    buffer = buffer.slice(1 + SHA_384.length);
```suggestion
    buffer = buffer.slice(BYTE_SIZE + SHA_384.length);
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    const {length, bytes} = readLengthAndBytes(buffer.slice(1), 1, SHA_384_WITH_RSA.maxLength, false);
```suggestion
    const {length, bytes} = readLengthAndBytes(buffer.slice(BYTE_SIZE), BYTE_SIZE, SHA_384_WITH_RSA.maxLength, false);
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    buffer = buffer.slice(1 + length);
```suggestion
    buffer = buffer.slice(BYTE_SIZE + length);
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +  let offset = 4;
```suggestion
  let offset = INT_SIZE;
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +    offset += 4;
```suggestion
    offset += INT_SIZE;
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +    this.dataLength = 4 + length;
```suggestion
    this.dataLength = INT_SIZE + length;
```

2021-02-09 01:32 UTC, Nana-EC commented on hedera-mirror-rest/check-state-proof/streamObject.js
> +    const {length, bytes} = readLengthAndBytes(buffer.slice(4), hashLength, hashLength, false);
```suggestion
    const {length, bytes} = readLengthAndBytes(buffer.slice(INT_SIZE), hashLength, hashLength, false);
```

2021-02-10 04:10 UTC, ijungmann commented on hedera-mirror-rest/check-state-proof/transactionValidator.js
> +    ) {
Alright, well I won't fight `prettier`

2021-02-10 04:25 UTC, ijungmann requested changes
Couple additional things, but looks good.

2021-02-10 04:25 UTC, ijungmann commented on hedera-mirror-rest/check-state-proof/README.md
> +the state proof check logic remains the same, the following changes are made to support the file version upgrade:
nit: something about this sounds slightly off to me
```suggestion
the state proof check logic remains the same, the following changes were made to support the file version upgrade:
```
or maybe
```suggestion
the state proof check logic remains the same, the following changes have been made to support the file version upgrade:
```

2021-02-10 04:25 UTC, ijungmann commented on hedera-mirror-rest/check-state-proof/recordFile.js
> +const V5_START_HASH_OFFSET = INT_SIZE + (INT_SIZE + INT_SIZE + INT_SIZE) + INT_SIZE;
nit: Perhaps you prefer to leave the types in the comments in to be explicit, but the types could now be inferred by INT_SIZE and BYTE_SIZE now if you want to remove these.

2021-02-10 04:25 UTC, ijungmann commented on hedera-mirror-rest/check-state-proof/signatureFile.js
> +    const {length, bytes} = readLengthAndBytes(buffer.slice(4), 1, SHA_384_WITH_RSA.maxLength, true);
nit: One better
```suggestion
    const {length, bytes} = readLengthAndBytes(buffer.slice(INT_SIZE), BYTE_SIZE, SHA_384_WITH_RSA.maxLength, true);
```

2021-02-10 19:08 UTC, Nana-EC approved these changes
LGTM

2021-02-10 20:00 UTC, ijungmann approved these changes

2021-02-10 20:26 UTC, merged