Add schedule transaction memo field
hashgraph/hedera-mirror-node pull request #1556
Opened 2021-02-07 04:38 UTC by ijungmann

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1508 
**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-02-09 17:00 UTC, Nana-EC requested changes

2021-02-09 17:03 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ConsensusCreateTopicTransactionHandlerTest.java
> +    private final Key adminKey = getKey("4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f");
Working on reorganizing these alphabetically.

2021-02-09 17:03 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ConsensusCreateTopicTransactionHandlerTest.java
> +                        .setAutoRenewPeriod(AUTO_RENEW_PERIOD)
Also reorg these and the method below

2021-02-09 17:04 UTC, ijungmann commented on pom.xml
> +        <hedera-protobuf.version>0.12.0-SNAPSHOT</hedera-protobuf.version>
Still not in Maven yet, but builds locally and runs.

2021-02-09 17:09 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ConsensusCreateTopicTransactionHandlerTest.java
> +    private final Key submitKey = getKey("submitKey");
The admin key was borrowed from another test already using it, I'll change this key to some variation of the above.

2021-02-09 17:23 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ConsensusCreateTopicTransactionHandlerTest.java
> +    private final Key submitKey = getKey("submitKey");
Done

2021-02-09 17:23 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ConsensusCreateTopicTransactionHandlerTest.java
> +    private final Key adminKey = getKey("4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f");
Done

2021-02-09 17:24 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileCreateTransactionHandlerTest.java
> +    private final Key key2 = getKey("4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f");
Yeah, copy paste error.  Fixed now.

2021-02-09 17:25 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java
> +    private final Key adminKey = getKey("4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f");
Good idea, will do that.

2021-02-09 17:41 UTC, steven-sheehy requested changes
This is missing the addition of the new response codes. Please do the diff between what has been added since the original proto implementation and make sure nothing was missed.

2021-02-09 17:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ScheduleCreateTransactionHandler.java
> +        if (scheduleCreateTransactionBody.getMemo() != null && scheduleCreateTransactionBody.getMemo().length() > 0) {
We don't need the `if` check. The default value for protobuf string is [empty string](https://developers.google.com/protocol-buffers/docs/proto3#default). Regardless, it doesn't matter to us if it's null or empty string we should just pass it through to the database.

2021-02-09 17:41 UTC, steven-sheehy commented on pom.xml
> +        <hedera-protobuf.version>0.12.0-SNAPSHOT</hedera-protobuf.version>
This can't be merged until we have the protobuf dependency. We need to push engineering for a alpha tag or revert to jitpack.

2021-02-09 17:46 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java
> +    private final Key adminKey = getKey("4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f");
Moved all mentioned values to the super class, as well as `SUBMIT_KEY` (reused now in the KeyList when needed) and made `MEMO` generic and moved that up

2021-02-09 17:46 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java
> +    private static final Duration AUTO_RENEW_PERIOD = Duration.newBuilder().setSeconds(1).build();
Done

2021-02-09 17:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ScheduleCreateTransactionHandler.java
> +        if (scheduleCreateTransactionBody.getMemo() != null && scheduleCreateTransactionBody.getMemo().length() > 0) {
Got it, just noticed I borrowed from the `ContractTransactionHandlers` which have more requirements.

2021-02-09 17:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ScheduleCreateTransactionHandler.java
> +        if (scheduleCreateTransactionBody.getMemo() != null && scheduleCreateTransactionBody.getMemo().length() > 0) {
Fixed.

2021-02-09 18:47 UTC, ijungmann commented
> This is missing the addition of the new response codes. Please do the diff between what has been added since the original proto implementation and make sure nothing was missed.

Added migrations for the changed/new response codes, looked at the diff and did not see anything else of note.

2021-02-09 22:01 UTC, ijungmann commented on pom.xml
> +        <hedera-protobuf.version>0.12.0-SNAPSHOT</hedera-protobuf.version>
Put the JitPack stuff back to get this unblocked for now.

2021-02-09 22:09 UTC, steven-sheehy requested changes

2021-02-09 22:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.0__update_schedule_response_codes.sql
> +UPDATE t_transaction_results set result = 'NO_NEW_VALID_SIGNATURES' WHERE proto_id = 205;
nit: mix of lower case SQL and uppercase. Should all be lower.

2021-02-09 22:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.0__update_schedule_response_codes.sql
> +update t_transaction_results set result = 'INVALID_SCHEDULE_PAYER_ID' WHERE proto_id = 203;
nit: would prefer update order be 203, 204, 205.

2021-02-09 22:09 UTC, steven-sheehy commented on hedera-mirror-protobuf/pom.xml
> +            <artifactId>hedera-protobufs-java</artifactId>
Should not depend upon `hedera-protobufs-java` as `hedera-protobufs` is the authoritative source of protobufs. `hedera-protobufs-java` is just a manually maintained copy of those protos right now.

2021-02-09 22:09 UTC, steven-sheehy commented on pom.xml
> +        <hedera-protobuf.version>-SNAPSHOT</hedera-protobuf.version>
Why `-SNAPSHOT`? Shouldn't this be `develop` to reflect the branch that has ?

2021-02-09 22:23 UTC, Nana-EC reviewed
Looks good, guess we just wait for the protobuf from maven central

2021-02-09 22:35 UTC, ijungmann commented on hedera-mirror-protobuf/pom.xml
> +            <artifactId>hedera-protobufs-java</artifactId>
JitPack won't work off of `hedera-protobufs` because it doesn't have build information.
https://jitpack.io/com/github/hashgraph/hedera-protobufs/develop-v0.11.0-g9f6ec54-14/build.log

2021-02-09 22:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.0__update_schedule_response_codes.sql
> +update t_transaction_results set result = 'INVALID_SCHEDULE_PAYER_ID' WHERE proto_id = 203;
I added them in this order because it violates the unique constraint of `result` if done in ascending order, it has to overwrite the `INVALID_SCHEDULE_PAYER_ID` on 204 before it can update 203 to be `INVALID_SCHEDULE_PAYER_ID`, etc.

2021-02-09 22:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.0__update_schedule_response_codes.sql
> +UPDATE t_transaction_results set result = 'NO_NEW_VALID_SIGNATURES' WHERE proto_id = 205;
Fixed.

2021-02-09 23:00 UTC, ijungmann commented on pom.xml
> +        <hedera-protobuf.version>-SNAPSHOT</hedera-protobuf.version>
Still getting familiar with the JitPack stuff, didn't notice the dropdown or that the Builds section had some of these branches.  `hedera-protobufs-java` doesn't have a `develop` (as discussed in the previous comment), but I changed it to `master`

2021-02-09 23:02 UTC, steven-sheehy commented on hedera-mirror-protobuf/pom.xml
> +            <artifactId>hedera-protobufs-java</artifactId>
Ah, got it.

2021-02-09 23:03 UTC, steven-sheehy approved these changes
LGTM

2021-02-09 23:18 UTC, ijungmann commented
> Looks good, guess we just wait for the protobuf from maven central

Spoke about this during scrum today and the consensus was we're okay to use JitPack for the time being, just FYI.

2021-02-10 02:21 UTC, Nana-EC approved these changes
LGTM

2021-02-10 02:22 UTC, xin-hedera approved these changes
LGTM

2021-02-10 04:39 UTC, merged