Upgrade Google Marketplace with support for v0.27
hashgraph/hedera-mirror-node pull request #1565
Opened 2021-02-09 01:38 UTC by Nana-EC

**Detailed description**:
Market place solution is still on v0.13. Current deployments will be broken by V5 stream file updates and thus require an upgrade.

- Update docker file to rename folder with charts to allow `mpdev` to pick up chart
- Update README with instructions on handling breaking changes due to Importer and Postgres StatefulSet changes
- Add `redis` and `monitor` to docker image to be deployed
- Update schema with release notes and links. Also add missing default properties for importer and Redis. 
- Update schema with new location of descriptions
- Update `values.yml` with Redis defaults

**Which issue(s) this PR fixes**:
Fixes #1174 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-02-11 17:20 UTC, steven-sheehy requested changes

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/values.yaml
> +    username: mirror_api
These two shouldn't be necessary as they're the default in the hedera-mirror values.yaml

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/values.yaml
> +    schema: mirrornode
I don't see this property implemented anywhere.

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.startDate:
We should keep the marketplace deploy as simple as possible and not present too many options to the user on their install screen. As such, I think we should remove all these new options except maybe `startDate`.

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.endDate:
`endDate` doesn't make much sense in the marketplace context and should be removed. Why would they pay to run all the components when only the REST API and PostgreSQL make sense after the endDate?

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.verifyHashAfter:
`verifyHashAfter` is an internal property that shouldn't be exposed.

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.spring.flyway.baselineVersion:
Tthere's no reason to expose flyway specific properties as those are used internally to switch between TimescaleDB and PostgreSQL. If we ever switch to TimescaleDB, we would just change the defaults in code.

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +      Topic fragmentation support was added to the ingestion process as well as exposed through the appropriate REST and gRPC APIs
Period at end of sentence.

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/README.md
> +    helm upgrade "${APP_NAME}" charts/hedera-mirror --namespace "${NAMESPACE}" --install --reuse-values --set importer.config.hedera.mirror.importer.downloader.record.enabled=false --set importer.con
These need to be updated to work with the marketplace install that doesn't use helm. These two commands can probably be simplified to "ensure your importer is up to date on file processing by inspecting logs before beginning, then delete statefulset."

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/README.md
> +## v0.13 to v0.27+
Just v0.27.0 since that's the version we're deploying to marketplace. If we have a v0.29.0 in marketplace there will be a `v0.27.0 to v0.29.0` section and it's expected that they follow read both sections to upgrade from v0.13.0.

2021-02-11 17:20 UTC, steven-sheehy commented on charts/marketplace/gcp/README.md
> +    helm upgrade "${APP_NAME}" charts/hedera-mirror --namespace "${NAMESPACE}" -f charts/marketplace/gcp/values.yaml -f custom-values.yaml
Why are these two steps necessary? After deleting statefulsets, the marketplace install should run and recreate them using the pre-existing volumes.

2021-02-11 17:24 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +      A Redis service was added to support ~10,000 TPS ingestion while still remaining under 10 seconds from submitting the topic message and receiving it back via the mirror node's streaming API.
Agreed, had changed this locally but yet to push up.

2021-02-11 17:25 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +        description: The Kubernetes service account to assign to the gRPC API
`mpdev` fails complaining the schema is wrong. Must have been a change made after we pushed the 1st version

2021-02-11 17:29 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.initialAddressBook:
They must have updated it. This is now the recommended location.
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md#type-service_account
I verified the hint shows up fine in the preview of the solution

2021-02-11 17:29 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +        description: The Kubernetes service account to assign to the importer
This is now the recommended location.
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md#type-service_account
I verified the hint shows up fine in the preview of the solution

2021-02-11 17:29 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +        description: The Kubernetes service account to assign to the gRPC API
This is now the recommended location.
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md#type-service_account
I verified the hint shows up fine in the preview of the solution

2021-02-11 17:31 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +        description: The Kubernetes service account to assign to the importer
Makes sense.

2021-02-11 17:32 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +        description: The Kubernetes service account to assign to the gRPC API
Makes sense.

2021-02-11 18:19 UTC, Nana-EC commented on charts/marketplace/gcp/values.yaml
> +    schema: mirrornode
This was to bring parity with the v2 data schema layout, but you're correct it's yet to be hooked up. So I can remove it from here for now. When we need it we can add it

2021-02-11 18:23 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.startDate:
Works for me. Simple is good. They can always take advantage of other properties using the helm install approach

2021-02-11 18:24 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.endDate:
Removing it along with other new non `startDate` properties

2021-02-11 18:25 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.verifyHashAfter:
Removing it along with other new non `startDate` properties

2021-02-11 18:25 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.spring.flyway.baselineVersion:
Removing it along with other new non `startDate` properties

2021-02-11 18:25 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +      Topic fragmentation support was added to the ingestion process as well as exposed through the appropriate REST and gRPC APIs
Had added it, yet to be pushed.

2021-02-11 18:27 UTC, Nana-EC commented on charts/marketplace/gcp/README.md
> +## v0.13 to v0.27+
Works for me

2021-02-11 18:29 UTC, Nana-EC commented on charts/marketplace/gcp/README.md
> +    helm upgrade "${APP_NAME}" charts/hedera-mirror --namespace "${NAMESPACE}" -f charts/marketplace/gcp/values.yaml -f custom-values.yaml
You're correct. I think I should rename this section to highlight a helm management of marketplace and have the simpler one for just marketplace UI install

2021-02-11 20:36 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +      A Redis service was added to support ~10,000 TPS ingestion while still remaining under 10 seconds from submitting the topic message and receiving it back via the mirror node's streaming API.
Updated

2021-02-11 20:36 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  global.redis.password:
Removed

2021-02-11 20:37 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.downloader.cloudProvider:
Removed

2021-02-11 20:37 UTC, Nana-EC commented on charts/marketplace/gcp/values.yaml
> +    schema: mirrornode
Removed

2021-02-11 20:38 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.endDate:
Removed

2021-02-11 20:38 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.verifyHashAfter:
Removed

2021-02-11 20:38 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.spring.flyway.baselineVersion:
Removed

2021-02-11 20:49 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +  importer.config.hedera.mirror.importer.initialAddressBook:
Looks like you commented on the wrong item. But shows you removed this property so all good.

2021-02-11 20:57 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +      Topic fragmentation support was added to the ingestion process as well as exposed through the appropriate REST and gRPC APIs
Pushed

2021-02-11 20:58 UTC, Nana-EC commented on charts/marketplace/gcp/README.md
> +    helm upgrade "${APP_NAME}" charts/hedera-mirror --namespace "${NAMESPACE}" --install --reuse-values --set importer.config.hedera.mirror.importer.downloader.record.enabled=false --set importer.con
Removed helm specific logic. 
Simplified to just check logs, delete stateful sets and install

2021-02-11 20:59 UTC, Nana-EC commented on charts/marketplace/gcp/README.md
> +## v0.13 to v0.27+
Updated to just `v0.27`

2021-02-11 21:00 UTC, Nana-EC commented on charts/marketplace/gcp/README.md
> +    helm upgrade "${APP_NAME}" charts/hedera-mirror --namespace "${NAMESPACE}" -f charts/marketplace/gcp/values.yaml -f custom-values.yaml
Simplified

2021-02-11 22:59 UTC, Nana-EC commented on charts/marketplace/gcp/values.yaml
> +    username: mirror_api
Removed

2021-02-11 23:02 UTC, steven-sheehy approved these changes
LGTM

2021-02-12 22:10 UTC, xin-hedera approved these changes
LGTM

2021-02-13 20:52 UTC, merged