Support new entity memo fields
hashgraph/hedera-mirror-node pull request #1567
Opened 2021-02-10 17:42 UTC by xin-hedera

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1553 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-10 22:11 UTC, steven-sheehy requested changes

2021-02-10 22:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractUpdatesEntityTransactionHandlerTest.java
>   * Hedera Mirror Node
For each of the update handlers with a memo, we should add a common test case that clears the memo to empty string and one that doesn't set either. The purpose of the `StringValue` wrapper is to differentiate between unset, set and clear.

2021-02-10 23:58 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractUpdatesEntityTransactionHandlerTest.java
> +/*-
Isn't that dash on all the licenses?

2021-02-11 16:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        entity.setMemo(txMessage.getMemo());
fix bug in `ContractCreateTransactionHandler`, when the memo `String` is either not set or set to empty string, the memo in the entity should be set to empty string

2021-02-11 17:58 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java
> +    Stream<DynamicTest> testUpdateEntity() {
Clever test.

2021-02-11 18:00 UTC, ijungmann approved these changes
LGTM

2021-02-11 18:56 UTC, Nana-EC approved these changes
LGTM

2021-02-11 20:38 UTC, steven-sheehy approved these changes
LGTM

2021-02-12 00:45 UTC, merged