Rest get schedule api
hashgraph/hedera-mirror-node pull request #1576
Opened 2021-02-12 22:05 UTC by xin-hedera

**Detailed description**:

- Implement GET /schedules/{scheduleId}
- Update openapi.yml

**Which issue(s) this PR fixes**:
Fixes #1471 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-02-12 22:13 UTC, xin-hedera commented on hedera-mirror-rest/schedules.js
> +      'public_key_prefix', encode(ss.public_key_prefix, 'base64'),
by default, `json_build_object` encodes `bytea` as hex string with "\x" prefix, so explicitly encoding it into "base64" to save some bytes

2021-02-16 22:02 UTC, steven-sheehy requested changes

2021-02-16 22:43 UTC, Nana-EC reviewed
Looking good, will circle back when it's warm :)

2021-02-16 23:06 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/schedules-02-specific-id-not-executed-yet.spec.json
> +    "executed_timestamp": "0.000000000",
yes. I did this because in token-info-01-no-args `modified_timestamp` is '0.000000000'. but I was wrong about that in db `modified_timestamp` of the test spec is null.

i'll also fix the token related tests too since `modified_timestamp` for a token should not be 0

2021-02-16 23:07 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: object
nope. I'll add one

2021-02-16 23:10 UTC, xin-hedera commented on hedera-mirror-rest/schedules.js
> +      'public_key_prefix', encode(ss.public_key_prefix, 'base64'),
sure. so we will keep `admin_key.key` in hex and have `public_key_prefix`, `signature`, and `transaction_body` in base64

2021-02-17 18:18 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
can use optional modifier `format` with value `byte`

2021-02-17 21:55 UTC, ijungmann approved these changes
LGTM

2021-02-17 22:22 UTC, steven-sheehy requested changes

2021-02-17 22:22 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
This should be an enum with `ED25519` or `ProtobufEncoded`. Or at least these should be mentioned in a description as the possible values.

2021-02-17 22:22 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/schedules-02-specific-id-not-executed-yet.spec.json
> +  "url": "/api/v1/schedules/0.0.2000",
In light of #1586, let's change one of these tests to not include shard and realm in the URL.

2021-02-18 16:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/schedules-02-specific-id-not-executed-yet.spec.json
> +  "url": "/api/v1/schedules/0.0.2000",
good suggestion.

done with `schedules-02-specific-id-encoded-id-not-executed-yet.spec.json`

`"url": "/api/v1/schedules/2000"`

2021-02-18 16:45 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
added the `enum` modifier with all the valid values

2021-02-18 16:46 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/schedules-02-specific-id-encoded-id-not-executed-yet.spec.json
> +  "description": "Schedule api calls for a specific schedule using encoded schedule id, no admin key, not executed yet",
Technically it's not encoded, it's just drops the shard and realm. Coincidentally it matches the encoded id when shard and realm are zero.

2021-02-18 16:47 UTC, steven-sheehy approved these changes
LGTM

2021-02-18 18:05 UTC, Nana-EC approved these changes
LGTM

2021-02-18 18:21 UTC, merged