Fix failure when building hedera-mirror-rest docker image
hashgraph/hedera-mirror-node pull request #1591
Opened 2021-02-19 16:17 UTC by xin-hedera

**Detailed description**:
In our github action `build` job (https://github.com/hashgraph/hedera-mirror-node/actions/runs/579279458), `npm -ci --only=production` is used. The command skips dev dependencies, so the `postinstall` script fails because `husky` does not exist, which then fails the whole job. To fix it, in `postinstall`, `huksy install` will only run when --only=(prod|production) is not specified.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-02-19 16:51 UTC, steven-sheehy requested changes

2021-02-19 16:51 UTC, steven-sheehy commented on hedera-mirror-rest/package.json
> +    "postinstall": "[ \"${npm_config_only}\" = prod -o \"${npm_config_only}\" = production ] || (cd .. && husky install hedera-mirror-rest/.husky)",
This seems *nix specific. What about using [`prepare`](https://stackoverflow.com/questions/23076968/npm-postinstall-only-on-development) instead of `postinstall`?

2021-02-19 18:46 UTC, xin-hedera commented on hedera-mirror-rest/package.json
> +    "postinstall": "[ \"${npm_config_only}\" = prod -o \"${npm_config_only}\" = production ] || (cd .. && husky install hedera-mirror-rest/.husky)",
I tried prepare as mentioned in the stackflow post but it appears not to work with --only=production. I'll see if there is another way to use `prepare` so it can also work with windows cmd.exe.

2021-02-19 20:40 UTC, xin-hedera commented on hedera-mirror-rest/package.json
> +    "postinstall": "[ \"${npm_config_only}\" = prod -o \"${npm_config_only}\" = production ] || (cd .. && husky install hedera-mirror-rest/.husky)",
moved it to a nodejs script

2021-02-19 21:46 UTC, steven-sheehy commented on hedera-mirror-rest/npm_scripts/postinstall.js
> + * ​
Still looks to be missing and now it's missing on even more files...

2021-02-19 21:58 UTC, xin-hedera commented on hedera-mirror-rest/npm_scripts/postinstall.js
> + * ​
aha, interesting.

I actually removed the header from those files then ran `license:update-file-header`

2021-02-20 02:21 UTC, Nana-EC approved these changes
LGTM

2021-02-20 18:18 UTC, steven-sheehy commented on hedera-mirror-rest/npm_scripts/postinstall.js
> + * ​
I downloaded the file and viewed in vi. It looks good now. GitHub diff just made it appear as wrong.

2021-02-20 18:19 UTC, steven-sheehy approved these changes
LGTM

2021-02-22 16:33 UTC, ijungmann approved these changes

2021-02-22 16:38 UTC, merged