Add block index to record file
hashgraph/hedera-mirror-node pull request #1595
Opened 2021-02-19 23:23 UTC by xin-hedera

**Detailed description**:

- Add `block_index` to `record_file` that starts at 0 for the first timestamp and increase sequentially
- Remove `id` field from `record_file`
- Remove `id` sequence
- Change `consensus_end` to be the primary key
- Change v2 migration accordingly
- Change rosetta persistence layer block.go to use `block_index`

**Which issue(s) this PR fixes**:
Fixes #1548

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-20 05:12 UTC, Nana-EC requested changes

2021-02-20 05:12 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                    LIMIT 1`
You removed the `version` column.
Was this not used?

2021-02-20 05:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/AbstractRecordStreamFileListener.java
> +        Optional<RecordFile> latest = recordFileRepository.findLatest();
yes good idea

2021-02-20 05:17 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                    LIMIT 1`
it was not used & accidentally placed in the select fields lisst

2021-02-20 15:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/AbstractRecordStreamFileListener.java
> +        Optional<RecordFile> latest = recordFileRepository.findLatest();
We already have the last file stored in the downloader. We should just use that. We'd just need to handle what the index would be for when the start date greater than last entry in db inside the date range processor.

Or we can possibly use a trigger to auto increment on insert.

2021-02-20 16:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/AbstractRecordStreamFileListener.java
> +        Optional<RecordFile> latest = recordFileRepository.findLatest();
can't use the last file in downloader since normally the `last` in downloader is ahead of the `last` in parser.

don't like db trigger... I made the change to cache so as to avoid calling findLatest.

2021-02-20 16:56 UTC, steven-sheehy requested changes

2021-02-20 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    private Long blockIndex;
After doing a lot of work in the filesystem PR to pull up methods into the `StreamFile` interface, I'm wondering if we should make this field/concept useable for the other stream types. With that in mind, would it make more sense to name it `index` or do you think `block_index` is also a good name for the other types?

Note that I'm not suggesting we add this field to the other types at this time, just ensuring the name is flexible for use by each type.

2021-02-20 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.2__record_file_block_id.sql
> +create unique index if not exists record_file__block_index on record_file (block_index);
This should probably be created after the backfill.

2021-02-20 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.2__record_file_block_id.sql
> +create or replace function backfill_block_index() returns void as
Would prefer CTEs which would be much more succinct and just as efficient for this purpose. I'm not a fan of these giant temporary functions with cursors.
```sql
with block as (
  select consensus_end as ce, row_number() over (order by consensus_end)
  from record_file
  order by consensus_end asc
)
update record_file set block_index = block.row_number from block where consensus_end = block.ce;
```

2021-02-20 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>  create unique index if not exists record_file__name
Do we still need the name index for any queries? I think the uniqueness will be guaranteed by the consensus fields.

2021-02-20 16:56 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                           WHERE block_index = $1`
There's no index on block_index, so the previous query would actually be faster.

2021-02-20 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/AbstractRecordStreamFileListener.java
> +        Optional<RecordFile> latest = recordFileRepository.findLatest();
What do you mean? It doesn't matter that downloader is ahead of parser. The downloader would be responsible for storing the last file and setting the block index. The parser would not be involved at all.

2021-02-20 17:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/AbstractRecordStreamFileListener.java
> +        Optional<RecordFile> latest = recordFileRepository.findLatest();
aha now I see what you mean. I wan't on the same page about setting block index in downloader.

2021-02-20 17:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.2__record_file_block_id.sql
> +create or replace function backfill_block_index() returns void as
sure and agree!

2021-02-20 17:02 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                           WHERE block_index = $1`
there is. so if the old query is as fast and doesn't need the index on block_index, we can remove it.

2021-02-20 17:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.2__record_file_block_id.sql
> +create unique index if not exists record_file__block_index on record_file (block_index);
in consideration of performance when building the index on the go v.s. in one shot?

2021-02-20 17:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.2__record_file_block_id.sql
> +create unique index if not exists record_file__block_index on record_file (block_index);
For performance of the backfill. Can build the index after backfill and build it in the background.

2021-02-20 17:34 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                           WHERE block_index = $1`
Ok, forgot you added an index. I guess we should check with BRD. They might need the index.

2021-02-20 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/RecordFile.java
> +    private Long blockIndex;
yes, on the same page. `index` is better as our record files just behave like blocks.

2021-02-22 16:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>  create unique index if not exists record_file__name
not needed anymore, I'll remove the index

2021-02-22 20:48 UTC, steven-sheehy requested changes

2021-02-22 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFile.java
> +    default boolean hasIndex() {
Can be removed with my other suggestion.

2021-02-22 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +//    protected RecordParserProperties parserProperties;
Commented out code

2021-02-22 20:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.35.3__record_file_block_index.sql
> +update record_file set index = block.row_number from block where consensus_end = block.ce;
oh sure. thanks

2021-02-22 20:52 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +//    protected RecordParserProperties parserProperties;
forgot to remove

2021-02-22 21:33 UTC, steven-sheehy approved these changes
LGTM

2021-02-22 21:34 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                           WHERE block_index = $1`
Customer indicated the index is needed.

2021-02-22 22:36 UTC, Nana-EC approved these changes
LGTM

2021-02-22 23:04 UTC, ijungmann approved these changes

2021-02-22 23:15 UTC, merged