REST Add ability to query by multiple account ids
hashgraph/hedera-mirror-node pull request #1607
Opened 2021-02-22 08:28 UTC by ijungmann

**Detailed description**:

- Add ability to query REST API by multiple account ids

**Which issue(s) this PR fixes**:
Fixes #1526 

**Special notes for your reviewer**:
- Current logic will not support mixing ops (cannot query account id > 12 OR = 3)

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-02-22 08:29 UTC, ijungmann commented
Need to do some cleanup on the actual logic, it's messy right now, but the ideas are in place and the tests seem to pass.  Also need to add a couple tests for multiple account ids.

2021-02-22 08:30 UTC, ijungmann commented on hedera-mirror-rest/__tests__/testutils.js
> +    let eqParams = sql.match(/(\w+?)\s*(IN)\s*?\(\s*((?:\$\d+,?\s*?)+)\)/g);
I did manage to create a regex that merged this with the other params regex, but it's a bit messy and the logic would get cluttered, figured splitting this one out was the right move.

2021-02-23 03:28 UTC, ijungmann commented on hedera-mirror-rest/__tests__/__snapshots__/utilsFilters.test.js.snap
> +  "Invalid parameter: undefined",
Have to see where this is coming from, tests got messed up after merge.

2021-02-23 03:31 UTC, ijungmann commented
Still doing some cleanup/refactoring, but the logic is in and stable enough to be looked at.

2021-02-23 06:54 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
> +      ? `${JSON.stringify(filter[0])} ${filter.length} times`
When testing the multiple params filter the test name output is incredibly long, this will reduce it.

2021-02-23 07:16 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> + * @param {Boolean} allowMultiple whether the sql clause should build multiple = ops as an IN() clause
Better name for this

2021-02-23 07:42 UTC, ijungmann commented on hedera-mirror-rest/config/application.yml
> +          name: account.id
Not sure if this is the best way to do the config, originally I had it as a defined account.id section with just the max as a value under that (see some of my early commits here), thought that might get a little messy with documentation, but this list structure is also a bit gross.

2021-02-23 15:19 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +          name: account.id
As we discussed on the call, it should just be a generic property that applies to all query parameters. Maybe `maxRepeatedParameters`.

2021-02-23 16:43 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/__snapshots__/utilsFilters.test.js.snap
> +  "Invalid parameter: undefined",
Jest uses a snapshot of the string produced for object comparison, as such if you add a test that uses that it'll add the above.
If you modified existing tests the previous snaps might be outdated.
you can run `npm test -- -u` or `jest -u` to set a new baseline reference of a snap. Just make sure the results returned by the methods are correct and what you want to compare against going forward

For more info https://jestjs.io/docs/en/snapshot-testing

2021-02-23 17:19 UTC, ijungmann commented on hedera-mirror-rest/config/application.yml
> +          name: account.id
Got it, and I like that name.  Changed.

2021-02-23 17:22 UTC, ijungmann commented on hedera-mirror-rest/__tests__/__snapshots__/utilsFilters.test.js.snap
> +  "Invalid parameter: undefined",
Got it, that's good info, the issue in particular I was looking for was why my new tests were coming back with "undefined", but after looking at the tests more closely they were not testing the functionality I needed (just luck that they came back passing), so I removed them and added a separate test suite to test my chunk of code.

2021-02-23 17:58 UTC, Nana-EC reviewed
Looks good a nit or two, will circle back for a 2nd pass

2021-02-23 17:58 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/accounts.test.js
> +      {field: 'account_id', operator: 'in', value: '3333'},
Weird that pretty made one object stay on a line and another get distributed across lines.
Maybe you can standardize it here

2021-02-23 17:58 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> + * @param {Function} processValue function to sql params using comparator and value
```suggestion
 * @param {Function} processValue function to extract sql params using comparator and value
```
Reads like there's a missing work here

2021-02-23 18:30 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +      {field: 'account_id', operator: 'in', value: '3333'},
It is pretty bizarre, but it appears to be allowing it today, looks like I may have needed to update something.  Anyway, it's fixed now.

2021-02-23 18:32 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> + * @param {Function} processValue function to sql params using comparator and value
Good catch, fixed

2021-02-23 20:36 UTC, steven-sheehy requested changes
Needs multiple param scenario added to JSON specs for each of the APIs impacted.

2021-02-23 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +const isRepeatedQueryParameerValidLength = (values => {
Misspelled

2021-02-23 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +        badParams.push(key);
This doesn't really indicate to the user why the param is invalid and what the max allowed is. Is there a way to put a more informative error message?

2021-02-23 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +      equalValues.push(processedValue);
Can we use a set to collapse duplicate values? Probably applies to all of these arrays in this method.

2021-02-23 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
>  const parseAccountIdQueryParam = (parsedQueryParams, columnName) => {
We should have unit tests for this method and all other `parse*QueryParam` methods you touched.

2021-02-23 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
>   * Parse the query filer parameter
`filter`

2021-02-23 21:35 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +        badParams.push(key);
Yeah, almost done with that.  If there are multiple errors (some params have too many values, some are just invalid), do you want the error message to reflect all of the errors?
```
{"_status":{"messages":[{"message":"Parameter values count exceeds maximum number allowed: account.id count: 3 max: 2"},{"message":"Invalid parameter: account.publickey"}]}}
```
Or should one error take precedence over the other?

2021-02-23 22:12 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +        badParams.push(key);
It should show all like it does now.

2021-02-23 22:50 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const isRepeatedQueryParameerValidLength = (values => {
Fixed, `isRepeatedQueryParameterValidLength`

2021-02-23 22:52 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +        badParams.push(key);
Added logic for `InvalidArgumentError` to support a new error message in addition to the original one to better convey the error.

2021-02-23 23:45 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +      equalValues.push(processedValue);
Made `equalValues` a set.  The others would not work well as sets without refactoring (one is for clauses, the other for values, either could have a dupe without the other and it would technically be valid), instead I converted the incoming `paramValues` to a Set which should solve the dupe issue.

2021-02-23 23:46 UTC, ijungmann commented on hedera-mirror-rest/utils.js
>   * Parse the query filer parameter
Fixed.

2021-02-24 01:10 UTC, ijungmann commented on hedera-mirror-rest/utils.js
>  const parseAccountIdQueryParam = (parsedQueryParams, columnName) => {
Added some unit tests for `parseAccountIdQueryParam`, will add the same tests for others (sans the IN() tests)

2021-02-24 03:57 UTC, ijungmann commented on hedera-mirror-rest/utils.js
>  const parseAccountIdQueryParam = (parsedQueryParams, columnName) => {
Added unit tests for all 5 of these methods, will move on to Spec tests

2021-02-24 04:23 UTC, ijungmann commented
Added 3 spec tests for multiple account ids, one for each API (accounts, balances, transactions)

2021-02-24 08:53 UTC, ijungmann commented on docs/testing.md
> +-   `queries` is the number of unique queries to put in the query set when `multipleFilters` is true
Probably better names to represent some of this.

2021-02-24 08:56 UTC, ijungmann commented
Added some logic to do perf testing, numbers look reasonable from what I've tested.

2021-02-24 09:02 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      name: "Basic",
Rename some of these to be more descriptive.

2021-02-24 19:08 UTC, xin-hedera requested changes

2021-02-24 19:08 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    },
nit, oneliner

```suggestion
    (value) => EntityId.fromString(value).getEncodedId(),
```

2021-02-24 19:08 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    },
nit, oneliner
```suggestion
    (value) => return parseTimestampParam(value),
    (op, value) => [`${columnName}${op in opOverride ? opOverride[op] : op}?`, [value]],
```

2021-02-24 19:08 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    },
oneliner
```suggestion
    (value) => value,
```

2021-02-24 20:10 UTC, ijungmann commented on docs/testing.md
> +-   `count`: Number of values to sample for the param which will be set based on `filterAxis`. If `multiple` is false or not set, this also represents
Fixed.

2021-02-24 20:10 UTC, ijungmann commented on docs/testing.md
> +-   `queries` is the number of unique queries to put in the query set when `multipleFilters` is true
Added another test example for multiple, also renamed `queries` to `numberOfQueries` to be clearer.

2021-02-24 20:14 UTC, ijungmann commented on hedera-mirror-rest/__performancetests__/generateQuerySets.js
> +      });
Good idea, made that change.

2021-02-24 20:21 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
> +  test(`utils isRepeatedQueryParameterValidLength verify account.id with valid amount ${config.maxRepeatedQueryParameters - 1} `, () => {
Added a test that has exactly `config.maxRepeatedQueryParameters` number of params

2021-02-24 20:27 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    },
Fixed.

2021-02-24 20:27 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    },
Fixed.

2021-02-24 20:27 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    },
Fixed.

2021-02-24 20:28 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +})
Fixed.

2021-02-24 22:29 UTC, ijungmann commented on hedera-mirror-rest/__tests__/mockpool.js
>          pVar.high = param.value;
Added logic to make `in` use a list of values instead of a range, and adjusted the tests accordingly to make that work.

2021-02-24 23:06 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-02-24 23:36 UTC, Nana-EC requested changes
A few nits.
Also `/api/v1/tokens/`, `/api/v1/tokens/{id}/balances` and `/api/v1/tokens/` endpoint also take `account.id` so we should add specs for that

2021-02-24 23:36 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/accounts.test.js
> +    console.log(`validateAccNumRange check failed: ${offender} is not in ${potentialValues}`);
```suggestion
    console.log(`validateAccNumInArray check failed: ${offender} is not in ${potentialValues}`);
```

2021-02-24 23:36 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/balances.test.js
> +    console.log(`validateAccNumRange check failed: ${offender} is not between ${low} and  ${high}`);
```suggestion
    console.log(`validateAccNumInArray check failed: ${offender} is not in ${potentialValues}`);
```

2021-02-24 23:36 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/balances.test.js
> +const validateAccNumInArray = function (balances, potentialValues) {
Isn't this a dupe of the one in the `accounts.test.js` also?
Probably okay , just wondering if there's an easy sharing solution

2021-02-24 23:36 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/mockpool.js
> +      row.entity_id = ((accountNum, i) => {
nit: duped code, could just make it a function

2021-02-24 23:36 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        `validateAccNumRange check failed: No transfer with account in ${potentialValues} was found in transaction : ${JSON.stringify(
```suggestion
        `validateAccNumInArray check failed: No transfer with account in ${potentialValues} was found in transaction : ${JSON.stringify(
```

2021-02-24 23:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/balances.test.js
> +const validateAccNumInArray = function (balances, potentialValues) {
It's okay to no-op this if it requires to much more work as it's for separate test files and we're not in the habit of having classes implement inheritance on the js side

2021-02-25 05:52 UTC, ijungmann commented on hedera-mirror-rest/__tests__/balances.test.js
> +const validateAccNumInArray = function (balances, potentialValues) {
Yeah, it's a dupe.  I could move it over to `testUtils.js` if we're okay adding bulk there.

2021-02-25 06:08 UTC, ijungmann commented on hedera-mirror-rest/__tests__/mockpool.js
> +      row.entity_id = ((accountNum, i) => {
Made this block a function.

2021-02-25 06:08 UTC, ijungmann commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        `validateAccNumRange check failed: No transfer with account in ${potentialValues} was found in transaction : ${JSON.stringify(
Fixed.

2021-02-25 06:08 UTC, ijungmann commented on hedera-mirror-rest/__tests__/balances.test.js
> +    console.log(`validateAccNumRange check failed: ${offender} is not between ${low} and  ${high}`);
Fixed.

2021-02-25 06:08 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +    console.log(`validateAccNumRange check failed: ${offender} is not in ${potentialValues}`);
Fixed.

2021-02-25 06:18 UTC, ijungmann commented
> A few nits.
> Also `/api/v1/tokens/`, `/api/v1/tokens/{id}/balances` and `/api/v1/tokens/` endpoint also take `account.id` so we should add specs for that

I actually did not notice the tokens endpoints took `account.id` because it bypasses `parseAccountIdQueryParam` entirely and relies on separate logic to parse the filters and build the query.  I think it may be better to open a separate ticket to tackle the endpoints that rely on that logic, it looks like they will need some more refactoring and the original client request was limited to `/api/v1/transactions`.  If it's worth the extra time to get it in this PR, I can look into it more.

2021-02-25 16:52 UTC, Nana-EC approved these changes
LGTM
You can open the separate ticket for the account.id in the the other API endpoints noted

2021-02-25 16:52 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/balances.test.js
> +const validateAccNumInArray = function (balances, potentialValues) {
Nah it's okay for now.

2021-02-25 17:15 UTC, xin-hedera approved these changes

2021-02-25 17:22 UTC, steven-sheehy requested changes

2021-02-25 17:22 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "account.id IN (?)",
I don't see any tests that cover the InvalidArgumentError scenarios.

2021-02-25 17:22 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      parsedQueryParams: {"account.id": ["0.0.5", "5", "eq:0.0.5", "lte:0.0.3", "lte:0.0.3", "gte:0.0.3", "gte:0.0.4"]},
We should also probably throw an error if there's an eq/IN and a range operator since the eq/IN is more strict and would take precedence anyway in the query. Accepting both would only confuse people that this is not an OR. Throwing an error during client development time is better than production bugs caused by mismatched expectations. Probably applies to all query parameters.

2021-02-25 17:22 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "timestamp = ? and timestamp = ?",
This would return 0 rows. We should throw an error or convert to an IN. If neither is trivial we can create a ticket to capture all these other params with multiple values.

2021-02-25 17:22 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      name: singleParamTestName,
Should have a generic parseParam test that tests null, not array and empty array inputs.

2021-02-25 17:22 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +
We should throw an error if the query replacement parameters doesn't equal the number of values.

2021-02-25 18:10 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/accounts-20-multiple-ids.spec.json
> +  "description": "Account api calls for specific account using query param",
Fixed.

2021-02-25 18:10 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/balances-12-multiple-ids.spec.json
> +  "description": "Balance api calls for a specific account",
Fixed.

2021-02-25 18:10 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-27-multiple-account-ids.spec.json
> +  "description": "Transaction api calls for transactions via account id query filter",
Fixed.

2021-02-25 18:17 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utilsFilters.test.js
> +describe('utils isRepeatedQueryParameterValidLength', () => {
Moved.

2021-02-25 22:16 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      parsedQueryParams: {"account.id": ["0.0.5", "5", "eq:0.0.5", "lte:0.0.3", "lte:0.0.3", "gte:0.0.3", "gte:0.0.4"]},
I can see that, would just need to keep a map of ops seen during the parsing to check that.  The other potential valid confusion would be`account.id=lt:5&account.id=gt:10`, which would be a check for things outside of a given range, but would return no values because of the same issue (an AND, not an OR).

2021-02-26 16:50 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      parsedQueryParams: {"account.id": ["0.0.5", "5", "eq:0.0.5", "lte:0.0.3", "lte:0.0.3", "gte:0.0.3", "gte:0.0.4"]},
Did `account.id=lt:5&account.id=gt:10` use to be an OR and now it's an AND? If so, that's a breaking change for clients. We should consider making some operators an OR and some operators an AND and probably disallow mixing the two types.

2021-02-26 16:59 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      parsedQueryParams: {"account.id": ["0.0.5", "5", "eq:0.0.5", "lte:0.0.3", "lte:0.0.3", "gte:0.0.3", "gte:0.0.4"]},
No, all of the params that pass through `parseParams` before were parsed out individually and then joined together at the end with `return [partialQueries.join(' and '), values];`.  That was the cause of the original issue, where multiple = were ANDed together as literally "equals this AND that". This would just be another edge case that was never handled.

2021-02-26 17:02 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "account.id <= ? and account.id >= ? and account.id >= ? and account.id IN (?)",
Sure, I can do some refactoring in the validation code to clean that up, this was just an existing issue that I wrote a test case for.

2021-02-26 17:48 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expect(val[1]).toEqual(testSpec.expectedValues);
Added that check

2021-02-26 17:56 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      name: singleParamTestName,
As in a test suite for the `parseParams()` function to check those, or a test suite for all the `parse*QueryParam` function with those to reduce the amount of duplicate specs?

2021-02-26 18:02 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      parsedQueryParams: {"account.id": ["0.0.5", "5", "eq:0.0.5", "lte:0.0.3", "lte:0.0.3", "gte:0.0.3", "gte:0.0.4"]},
Will create a ticket to address this, it's an existing issue and probably deserves some attention on its own.

2021-02-26 18:05 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "timestamp = ? and timestamp = ?",
Will create a ticket for this.  It should be easy to return IN for balance and public key, and credit/debit doesn't have this issue because everything converts to > 0 or < 0, the one I worry about is timestamp because we allow for opOverrides (and in one case we actually do override =), it may require a bigger effort to address that.

2021-02-26 18:06 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      name: singleParamTestName,
I think you can just do some basic tests for `parseParams()` directly. Adding to all `parse*QueryParams` would duplicate tests.

2021-02-26 18:10 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "account.id <= ? and account.id >= ? and account.id >= ? and account.id IN (?)",
Will open ticket for this, existing issue and the validation logic could use some attention in general.  I can remove this test since it's technically a bug, or I can leave it in as an example for that ticket to address.

2021-02-26 21:42 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      name: singleParamTestName,
Added tests for parseParam with undefined, not array, and empty array.  If we want to check `null` I'll need to knock `if (paramValues === undefined)` down to `==`, since the only functions that use this pull the values from an object it would be expected to strictly equal undefined.  Easily done if desired.

2021-02-26 22:13 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +
Done, had to make changes to the way credit/debit parsing returns as it never returned a ?.  Also added some tests for this.

2021-02-28 21:12 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "account.id IN (?)",
I added a few negative test cases for `validateReq` that should cover those.  A lot of the validation logic is missing unit tests and could use some attention (I can throw that in a ticket), some of it is covered by the integration/spec tests but needs more granular testing.

2021-02-28 23:15 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "account.id IN (?)",
Yeah, I just meant for the new validation you added. Not expecting you to fill out the tests for the things you didn't change.

2021-03-01 21:06 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-03-01 22:10 UTC, xin-hedera requested changes

2021-03-01 22:26 UTC, ijungmann commented
> LGTM
> You can open the separate ticket for the account.id in the the other API endpoints noted

Opened ticket #1652 to address this

2021-03-01 22:28 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      expectedClause: "timestamp = ? and timestamp = ?",
Opened ticket #1653 to address supporting multiple parameters for all others

2021-03-01 22:29 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +      parsedQueryParams: {"account.id": ["0.0.5", "5", "eq:0.0.5", "lte:0.0.3", "lte:0.0.3", "gte:0.0.3", "gte:0.0.4"]},
Created ticket #1654 to do validation on the query parameters as a group so that we can deal with these scenarios and few others I identified.

2021-03-01 22:41 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +const validateAccNumInArray = function (accounts, potentialValues) {
Cool!  Made this change here, as well as in balances and transactions.

2021-03-01 22:41 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +      {func: validateAccNumInArray, args: [[3333]]},
Fixed.

2021-03-01 22:42 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +      {func: validateAccNumInArray, args: [[3333, 3334]]},
Fixed.

2021-03-01 23:02 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +const validateAccNumInArray = function (accounts, potentialValues) {
Yeah, Nana and I were discussing whether this should go in `testutils`, with that refactoring I can move it in there.

2021-03-01 23:08 UTC, steven-sheehy approved these changes
LGTM

2021-03-01 23:13 UTC, Nana-EC approved these changes
LGTM

2021-03-01 23:20 UTC, ijungmann commented on hedera-mirror-rest/__tests__/accounts.test.js
> +const validateAccNumInArray = function (accounts, potentialValues) {
Moved this to `testutils`, and altered to confirm every account id is valid, not just one.

2021-03-02 02:24 UTC, xin-hedera approved these changes
LGTM

2021-03-02 04:05 UTC, steven-sheehy approved these changes

2021-03-02 04:54 UTC, Nana-EC approved these changes
LGTM

2021-03-02 15:15 UTC, merged