Bump Spring Boot to 2.4.3
hashgraph/hedera-mirror-node pull request #1609
Opened 2021-02-22 18:58 UTC by steven-sheehy

**Detailed description**:
- Bump Spring Boot to 2.4.3
- Bump Spring Cloud to 2020.0.1
- Bump Flyway to 7.1.1
- Add `queueCapacity` property to Redis publisher
- ...

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Still need to do some manual testing but PR is complete.

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-02-23 18:33 UTC, Nana-EC commented on .github/workflows/v2-schema.yml
> +    #    services:
Did you get this working using embedded containers?
If so you can delete this instead of commenting out right?

2021-02-23 18:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +    locations: "classpath:db/migration/v1"
By moving it here do you still need it in the bootstrap.
I remember circle wouldn't work without it in the bootstrap wondering if the version increase has fixed that

2021-02-23 18:33 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerIntegrationTest.java
> +                sink.tryEmitNext(serializer.deserialize(message.getBody()));
Should we be checking the EmitResult to distinguish between the results e.g. OK, vs  cancelled/overflow/terminated/zero subscriber?

2021-02-23 18:36 UTC, steven-sheehy commented on .github/workflows/v2-schema.yml
> +    #    services:
I'm trying anything I can at this point to see if I can get these V2 rest tests to pass.

2021-02-24 20:40 UTC, steven-sheehy commented on .github/workflows/v2-schema.yml
> +    #    services:
These have been removed

2021-02-24 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> +    locations: "classpath:db/migration/v1"
Removed this change

2021-02-24 21:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerIntegrationTest.java
> +                sink.tryEmitNext(serializer.deserialize(message.getBody()));
True, changed to emitNext with a fail fast handler. This replicates the previous behavior when using the Processors.

2021-02-24 21:34 UTC, steven-sheehy commented
All tests pass now. Ready for review

2021-02-24 23:39 UTC, Nana-EC commented on .github/workflows/v2-schema.yml
> +    #    services:
Nice, was a pain before, glad this work around can be removed

2021-02-24 23:50 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-02-25 16:51 UTC, ijungmann requested changes
Couple small questions, otherwise looks good.

2021-02-25 16:51 UTC, ijungmann commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +    username: "" # Redis 5 does not support authentication with a username and will fail if provided
Is it required to provide an empty username, as opposed to just removing it altogether?

2021-02-25 16:51 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +                .filter(r -> RANDOM.nextDouble() < properties.getSamplePercent())
Originally the samplePercent was retrieved outside the flux to prevent a performance reflection penalty, is that no longer a concern here?

2021-02-25 17:13 UTC, xin-hedera approved these changes
LGTM

2021-02-25 17:26 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/RestSubscriber.java
> +                .filter(r -> RANDOM.nextDouble() < properties.getSamplePercent())
Added this note to the description:

> Spring Boot 2.4 no longer creates CGLIB proxies for `@ConfigurationProperties` classes. Hence why some of the changes push property retrieval back into the "hot path" as it's not longer a performance concern.

2021-02-25 17:30 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +    username: "" # Redis 5 does not support authentication with a username and will fail if provided
I think Spring Data Redis defaults to null. But putting an empty string gives me something to add a comment to :)

2021-02-25 17:32 UTC, ijungmann commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +    username: "" # Redis 5 does not support authentication with a username and will fail if provided
Fair point, doesn't hurt to explicitly state it.

2021-02-25 17:32 UTC, ijungmann approved these changes

2021-02-25 17:35 UTC, merged