Fix get tokens query by account ID filter with shard and realm
hashgraph/hedera-mirror-node pull request #1619
Opened 2021-02-23 21:37 UTC by xin-hedera

**Detailed description**:
Support get tokens query by account ID of the format shard.realm.num

**Which issue(s) this PR fixes**:
Fixes #1586 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-23 22:32 UTC, Nana-EC requested changes

2021-02-23 22:32 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const getEncodedTokenId = (tokenIdStr) => {
This should be in utils as `getEncodedEntityId()` with `constants.filterKeys.TOKENID` passed in as a param.
Then it can be used for all entity id query params requests

2021-02-23 22:32 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
>    if (accountId) {
We should be using the `getEncodedEntityId()` method noted below

2021-02-23 22:35 UTC, steven-sheehy requested changes
Can we do a sweep of all APIs to see if any other request entity IDs have the same issue?

2021-02-23 22:35 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  return EntityId.fromString(tokenIdStr).getEncodedId();
Does this allow input in the form `x.y.z`, `y.z` and `z`? Can we add a test for shard + num?

2021-02-23 22:46 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +const getEncodedTokenId = (tokenIdStr) => {
agree, but prefer to add it to entityid.js. we all don't like a bloated utils module :)

2021-02-23 22:46 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  return EntityId.fromString(tokenIdStr).getEncodedId();
I'll check and also add test cases.

2021-02-23 22:57 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  return EntityId.fromString(tokenIdStr).getEncodedId();
`EntityId.fromString` only does `x.y.z` and encoded `x.y.z`
 I think there's another ticket for what you're noting right?

2021-02-23 23:11 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  return EntityId.fromString(tokenIdStr).getEncodedId();
Not that I'm aware of.

2021-02-24 15:28 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  return EntityId.fromString(tokenIdStr).getEncodedId();
changed `EntityId.fromString` to support `shard.realm.num`, `realm.num`, and `num`; also note it no longer supports encoded entity ID

renamed `EntityId.fromInt` to `EntityId.fromEncodedId` and now it supports encoded ID of type string, BigInt, and int.

2021-02-24 16:34 UTC, ijungmann approved these changes
LGTM, just one Oxford comma missing if you want to go clean that up.

2021-02-24 16:34 UTC, ijungmann commented on hedera-mirror-rest/entityId.js
> + * Converts encoded entity ID (BigInt, int or string) to EntityId object.
nit:
```suggestion
 * Converts encoded entity ID (BigInt, int, or string) to EntityId object.
```

2021-02-24 19:01 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const getEncodedTokenId = (tokenIdStr) => {
yes agreed

2021-02-24 20:23 UTC, steven-sheehy approved these changes
LGTM

2021-02-24 22:21 UTC, Nana-EC approved these changes
LGTM

2021-02-24 22:39 UTC, merged