Fix rest API test timeout
hashgraph/hedera-mirror-node pull request #1635
Opened 2021-02-25 22:45 UTC by xin-hedera

**Detailed description**:
- Set default jest timeout to 2000ms
- Move `jest.setTimeout` out of before* hook in `integration.test.js` as it does not work with `jest-circus` test runner
- Change jest `testEnvironment` to `node`
- Disable `metrics` during test as it causes open handle with `node` testEnvironment
- Use awaitjs express `useAsync` for async middleware

**Which issue(s) this PR fixes**:
Fixes #1510 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-25 23:30 UTC, steven-sheehy requested changes

2021-02-25 23:30 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/httpErrorHandler.js
> +    logger.warn(`${statusCode} processing ${req.originalUrl}: `, err);
This change was intentional. We don't need to print a full stack trace for user caused errors like invalid input. Stacktraces are for things we need to potentially investigate.

2021-02-26 00:20 UTC, xin-hedera commented on hedera-mirror-rest/middleware/httpErrorHandler.js
> +    logger.warn(`${statusCode} processing ${req.originalUrl}: `, err);
will revert. It was changed to check where the `NotFound` error was from for the issue with 0.28.0-beta1

2021-02-26 00:29 UTC, steven-sheehy approved these changes
LGTM

2021-02-26 15:39 UTC, Nana-EC approved these changes
LGTM

2021-02-26 16:33 UTC, merged