Scheduled acceptance
hashgraph/hedera-mirror-node pull request #1636
Opened 2021-02-26 05:23 UTC by Nana-EC

**Detailed description**:

Add acceptance tests support for Scheduled transactions

**Which issue(s) this PR fixes**:
Fixes #1473 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-01 22:56 UTC, steven-sheehy requested changes
I left comments for one scenario but the same comments apply to the others.

2021-03-01 22:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        When the scheduled transaction is signed by the additionalAccount
This scenario and the others should say something about that it's the last signature expected which will cause its execution

2021-03-01 22:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the schedule transaction
Why is this executing twice, once before `the network confirms the schedule is not present` and once after? The one in between is just a query so shouldn't generate any new transaction.

2021-03-01 22:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the schedule transaction
This doesn't indicate we are checking for the schedulesign vs the executed transaction. It should check for both and there should be one line here for each that clearly states that.

2021-03-01 23:21 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private ExpandedAccountId additionalAccount;
I had some logic in the AccountClient initially but it became a question of how many additional accounts should be made available and in what configuration?
Since it came down to needing only 1 extra account per test this was easier and allows configurability per tests

2021-03-01 23:23 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    public ExpandedAccountId getReceiverSigNotRequiredAccount(int index) throws ReceiptStatusException,
Haha I had this exact thought. I coded out Alice, Bob and Carol and thought that was random and not indicative of the property the account had.

2021-03-01 23:25 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    public ExpandedAccountId getReceiverSigNotRequiredAccount(int index) throws ReceiptStatusException,
map over list works

2021-03-01 23:26 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>                  .uri(uri, uriVariables)
Good to know. Will take a look, if not an easy fix will open a ticket since this PR got larger than intended

2021-03-01 23:29 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                .setTransactionMemo(memo);
Meant to circle back to this.Schedule memo isn't exposed yet, so this is only the transaction memo. Will highlight this with sdk team.

2021-03-01 23:33 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        When the scheduled transaction is signed by the additionalAccount
Yeah thought about it, in practice people may not know they are the last signers, but in this case it makes it easier to follow. Will update

2021-03-01 23:35 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the schedule transaction
Labelling isn't clear I guess but easy REST API check confirms the transaction was what was expected and desired entity changes are found.
In the above case it confirms the `ScheduleSign` transaction and then that the Schedule has the expected number of current signatures

2021-03-01 23:35 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the schedule transaction
yeah concluded the same above, will update

2021-03-02 17:01 UTC, xin-hedera requested changes

2021-03-02 17:01 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws TimeoutException,
`List<PrivateKey>` fits the purpose better since it makes `PrivateKey` explicit and we don't really use `threshold` and the recursive key structure provided by `KeyList`

2021-03-02 18:26 UTC, ijungmann requested changes
Looks good, most of my feedback already covered by others, just a couple nits I happened to see.

2021-03-02 18:26 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +        log.debug("Sign schedule {}", scheduleId);
nit:
```suggestion
        log.debug("Delete schedule {}", scheduleId);
```

2021-03-02 18:26 UTC, ijungmann commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +#    @Acceptance - sdk bug exists where signatures for scedulecreate are not being mapped to Schedule
nit:
```suggestion
#    @Acceptance - sdk bug exists where signatures for schedulecreate are not being mapped to Schedule
```

2021-03-03 02:54 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    private final static int MAX_ACCOUNTS_PER_SIG_REQUIRED = 3;
Removing this

2021-03-03 02:55 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                .setKey(KeyList.of(publicKey))
Will update

2021-03-03 03:06 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +    private static Hbar MAX_TRANSACTION_FEE = Hbar.fromTinybars(1_000_000_000);
I can make it a param

2021-03-03 03:07 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                .setTransactionMemo(memo);
Update this with new sdk version

2021-03-03 03:10 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                        key.signTransaction(transaction));
Not really, signing the inner signature would imply the payer has multiple peoples private keys.
I'm trying to simulate accounts coordinating together and sharing signatures for use.

2021-03-03 15:02 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                        key.signTransaction(transaction));
my understanding of line 72 is: the private key is used to sign the scheduled transaction, and the public key / signature pair is added to the signedTransaction for the schedulecreatetransaction, will services not reject this schedule create transaction because the signatures are wrong?

2021-03-03 15:27 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws TimeoutException,
I kind of like KeyList since it provides us the flexibility for using threshold and complex keys in the future.

2021-03-03 22:23 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private ExpandedAccountId additionalAccount;
Dropped, everything pulls from AccountClient

2021-03-03 22:24 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    public ExpandedAccountId getReceiverSigNotRequiredAccount(int index) throws ReceiptStatusException,
Updated to use map with Enum keys

2021-03-03 22:24 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +            receiverSigRequiredAccounts = new ArrayList<>();
Fixed

2021-03-03 22:28 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +    private static Hbar MAX_TRANSACTION_FEE = Hbar.fromTinybars(1_000_000_000);
Updated to param

2021-03-03 22:29 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                PrivateKey key = ((PrivateKey) k);
Updated to List.
In accountClient I maintained KeyList as that is what's consumed by transaction

2021-03-03 22:31 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        When the scheduled transaction is signed by the additionalAccount
For flexibility reasons the accounts can change so I didn't want to to add the words last signature to it. In most cases the number of signatories is implied.
I did updated the next step to show that the schedule is expected to have been executed which further implies the last signer was the last signatory

2021-03-03 22:46 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the schedule transaction
Fixed this

2021-03-03 22:46 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the schedule transaction
Should be more clear now

2021-03-03 22:47 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                .setKey(KeyList.of(publicKey))
Updated logic here. In some cases I may want to pass a KeyList not just a single key

2021-03-03 22:50 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                        key.signTransaction(transaction));
To confirm.
Yes private keys are used to create signatures to be added to the outer transaction i.e ScheduledCreate.
Public keys are added to the Entity create transaction or the inner transaction i.e. transaction to be scheduled.
Schedule does reject additional keys that are not required.
I had some issues previously since keys are added to the CryptoCreate but are required during the token transfer, but have fixed it

2021-03-03 22:52 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws TimeoutException,
Yeah, I added it for the flexibility reasons. 
Where we only need private keys such as in ScheduleClient I updated method calls to just use that

2021-03-03 22:52 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +        log.debug("Sign schedule {}", scheduleId);
Updated

2021-03-03 22:52 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +#    @Acceptance - sdk bug exists where signatures for scedulecreate are not being mapped to Schedule
Fixed

2021-03-04 16:37 UTC, steven-sheehy requested changes

2021-03-04 16:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    private Map<AccountNameEnum, ExpandedAccountId> receiverSigRequiredAccounts = new HashMap<>();
Even though our use of Cucumber isn't multi-threaded currently, we should use ConcurrentHashMap just to be safe.

2021-03-04 16:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        Map<AccountNameEnum, ExpandedAccountId> accountMap = accountNameEnum.receiverSigRequired ?
Since the pair <name, receiverSigRequired> can't appear multiple times as `AccountNameEnum` guarantees the name alone is unique, we should just have a single map to store all accounts. Splitting it into two doesn't provide any benefit.

2021-03-04 16:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                        return createNewAccount(DEFAULT_INITIAL_BALANCE,
nit: Might be useful to pass the enum name as the entity and transaction memo

2021-03-04 16:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    public void E2ESigOnScheduleCreateAndScheduleSign() throws Exception {
This seems to be unused. And it seems to be too complex and not broken up into steps. Should probably remove.

2021-03-04 18:32 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    private Map<AccountNameEnum, ExpandedAccountId> receiverSigRequiredAccounts = new HashMap<>();
Agreed, can update

2021-03-04 18:33 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        Map<AccountNameEnum, ExpandedAccountId> accountMap = accountNameEnum.receiverSigRequired ?
Good point, that's logic left over from before I added the boolean

2021-03-04 18:33 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                        return createNewAccount(DEFAULT_INITIAL_BALANCE,
Good idea, will update

2021-03-04 18:34 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    public void E2ESigOnScheduleCreateAndScheduleSign() throws Exception {
Left over dev code I was using to  help sdk team debug. Wasn't supposed to have been committed. Will remove

2021-03-04 19:10 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>                  .uri(uri, uriVariables)
This breaks a few things and PR is larger than I had intended so I'll leave this one off and open a ticket

2021-03-04 20:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    private Map<AccountNameEnum, ExpandedAccountId> receiverSigRequiredAccounts = new HashMap<>();
Updated

2021-03-04 20:43 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        Map<AccountNameEnum, ExpandedAccountId> accountMap = accountNameEnum.receiverSigRequired ?
Updated

2021-03-04 20:43 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                        return createNewAccount(DEFAULT_INITIAL_BALANCE,
Updated

2021-03-04 20:43 UTC, xin-hedera requested changes

2021-03-04 20:43 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    public void E2ESigOnScheduleCreateAndScheduleSign() throws Exception {
Removed

2021-03-04 20:53 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +            ReceiptStatusException {
IntelliJ, I've improved it

2021-03-04 20:54 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        receiverSigNotRequiredAccounts = new HashMap<>();
duplicate removed

2021-03-04 21:11 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-03-04 21:14 UTC, xin-hedera submitted a review, later dismissed

2021-03-04 21:55 UTC, ijungmann submitted a review, later dismissed

2021-03-04 23:25 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>                  .uri(uri, uriVariables)
Opened #1665

2021-03-05 15:21 UTC, steven-sheehy submitted a review, later dismissed

2021-03-05 16:05 UTC, steven-sheehy approved these changes

2021-03-05 16:11 UTC, merged