Fix V2 test failures related with timescaledb compression
hashgraph/hedera-mirror-node pull request #1637
Opened 2021-02-26 15:12 UTC by xin-hedera

**Detailed description**:
Disable timescaledb hypertable compression for now. Will revisit the options when timescaledb 2.1 and docker images become GA.

**Which issue(s) this PR fixes**:
Fixes #1584 

**Special notes for your reviewer**:
timescaledb 2.0 does not support insert/update/delete on compressed chunks. Per our hypertable compression configuration, we use time_now in precision of nanos as the current time, any data inserted during tests is far older than 7 days (the compression policy) and will be compressed when the timescaledb compression job runs.

The compression jobs by default are schedule daily. In local environment, they tend to all fail at timescaledb startup due to out of background workers so the error rarely happens. In CI environment, the compression job has a higher possibility to succeed at startup and if there is still data to insert into the chunk which is already compressed, we will see the error.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-02-26 15:38 UTC, Nana-EC approved these changes
LGTM

2021-02-26 19:29 UTC, steven-sheehy requested changes

2021-02-26 19:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +-- to avoid inert/update on compressed chunks in catch-up mode
insert

2021-02-26 19:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +select add_compression_policy('schedule_signature', bigint '${compressionAge}');
Should sort before token_balance

2021-02-26 20:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +    select consensus_end into consensusEnd from record_file order by consensus_end desc limit 1;
`select coalesce(consensus_end, 0) from record_file group by consensus_end order by consensus_end desc limit 1;` doesn't work. When `record_file` is empty, the statement returns nothing.

2021-02-26 20:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> +-- to avoid inert/update on compressed chunks in catch-up mode
fixed

2021-02-26 20:07 UTC, steven-sheehy approved these changes
LGTM

2021-02-26 21:09 UTC, Nana-EC approved these changes
LGTM

2021-02-26 21:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> -alter table address_book
nit: if we're removing these tables because there's something about them then we should comment why so similar tables in future are left out and we know why these tables are missing

2021-02-26 22:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
> -alter table address_book
just added comments for the 5 tables

2021-02-26 22:58 UTC, steven-sheehy approved these changes
SLGTM

2021-03-01 15:17 UTC, Nana-EC approved these changes
LGTM

2021-03-01 15:19 UTC, merged