Update acceptance test to leave closure to sdk
hashgraph/hedera-mirror-node pull request #1655
Opened 2021-03-02 22:44 UTC by Nana-EC

**Detailed description**:
Acceptance tests are occasionally hanging on runs.
Currently the client is being closed after each feature, given the sdk progression it's probably okay to leave this closure to the sdk itself at the end of complete run

- Remove client close in `AccountClient` and `TopicClient`
- Bump release to v0.28.1 and 0.15.1

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-02 23:44 UTC, ijungmann approved these changes

2021-03-02 23:56 UTC, steven-sheehy requested changes

2021-03-02 23:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -            topicClient.getSdkClient().close();
Since we're not using `AutoCloseable` around our use of the `SDKClient.client`, this is effectively never closing the `Client`. So the only way that the connection is being shut down is when the JVM shuts down. I don't think this is a good practice especially since it may result in server connections staying idle until some timeout. Instead, how about using `@AfterAll`?

2021-03-03 00:57 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -            topicClient.getSdkClient().close();
Yeah was thinking on this a bit more. I think the contributing factor is we're creating too many instances of the clients. Reducing that should help

2021-03-03 01:39 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -            topicClient.getSdkClient().close();
Also cucumber doesn't have an `AfterAll` only an `After`.
The junit `AfterAll` isn't honored.

2021-03-03 01:55 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -            topicClient.getSdkClient().close();
You [can](https://www.metamorphant.de/blog/posts/2020-03-10-beforeall-afterall-cucumber-jvm-junit/) use AfterAll, but it's not honored in some IDEs. That link also has some other options and the cucumber ticket mentions ConcurrentEventListener as the best route.

2021-03-03 02:50 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -            topicClient.getSdkClient().close();
Lol, just saw this after pushing a ConcurrentEventListener solution. Looks like we we came to the same conclusion.
That ticket had been open for years

2021-03-03 04:27 UTC, steven-sheehy requested changes

2021-03-03 04:27 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/CucumberHooks.java
> +    @Autowired
Would prefer constructor injection be used with final fields and `@RequiredArgsConstructor`

2021-03-03 04:27 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/CucumberHooks.java
> +    private TopicClient topicClient;
This is missing `AccountClient`. A better way to make this future proof is:

```java
    private final Collection<AbstractNetworkClient> clients;

    @Override
    public void setEventPublisher(EventPublisher eventPublisher) {
        eventPublisher.registerHandlerFor(TestRunFinished.class, this::afterAll);
    }

    private void afterAll(TestRunFinished event) {
        clients.forEach(AbstractNetworkClient::close)
    }
```

2021-03-03 04:27 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> -        client.close();
Believe this is still necessary to close the `WebClient` in child while calling also calling `super.close()`.

2021-03-03 19:07 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/CucumberHooks.java
> +    private TopicClient topicClient;
Adopted this approach

2021-03-03 20:20 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/CucumberHooks.java
> +    @Autowired
Updated

2021-03-03 20:20 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> -        client.close();
Per offline chat this is NA

2021-03-03 20:52 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Please update the PR title and description as the approach has changed

2021-03-03 20:59 UTC, xin-hedera approved these changes

2021-03-03 21:01 UTC, ijungmann approved these changes

2021-03-04 15:51 UTC, steven-sheehy approved these changes
LGTM

2021-03-04 16:47 UTC, ijungmann approved these changes

2021-03-04 18:30 UTC, merged