Backfill pre-OA account entities
hashgraph/hedera-mirror-node pull request #1656
Opened 2021-03-02 23:10 UTC by steven-sheehy

**Detailed description**:
- Add a property to enable importing account info
- Add a repeatable migration `AccountInfoMigration`
- Change repository tests to not store injected repositories in the abstract class
- Change repository tests to not create a transaction for consensus timestamps since we don't have foreign keys
- Change migrations to not extend from `BaseJavaMigration` so class names aren't forced to have a format that causes code smells
- Delete `V1_11_6__Missing_Entities`
- Enable schedule transaction parsing by default

**Which issue(s) this PR fixes**:
Fixes #426
Fixes #1582 

**Special notes for your reviewer**:
`AccountInfoMigration` is repeatable so it can be ran again if needed by changing the checksum. But more importantly, it is ran after all other migrations thus allowing us to safely use repositories, avoid custom a `cleanup.sql`, avoid starting a new `ApplicationContext`, etc.

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-03-03 18:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        if (exists && hasCreateTransaction(accountEntityId)) {
Querying the transaction table by entity_id and type is extremely slow. I think I can just use the presence of a key or not to determine if it's created post OA.

2021-03-03 18:37 UTC, ijungmann requested changes
Couple minor things, looks good otherwise.

2021-03-03 18:37 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.importer.importAccountInfo`                           | true                    | Import historical account information that occurred before the last stream reset               |
Would prefer `importHistoricalAccountInfo` or something that clearly defines that this is historical data.

2021-03-03 18:37 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.importer.importAccountInfo`                           | true                    | Import historical account information that occurred before the last stream reset               |
Also, I'm a bit concerned having this set to true by default plays weird with `startDate`.  Considering a fresh mirror node defaults to the current time when no startDate is set, you would now have a db where you have pre-OA data and then a big jump to current data.

2021-03-03 18:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return 1; // Change this if this migration should be re-ran
nit, [had to look this up to be sure](https://english.stackexchange.com/a/251447)
```suggestion
        return 1; // Change this if this migration should be rerun
```

2021-03-03 18:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return "Backfill pre-OA account information";
nit: could move this to a static final attribute.

2021-03-03 18:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +            log.info("Account info importing is disabled");
nit: would also have this mention it being historical/pre-OA account info.

2021-03-03 22:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return "Backfill pre-OA account information";
Could but it provides no benefit as this file and method is only ever called once at startup by Flyway. Unless it provides a performance benefit when invoked more than once I'm not in favor of increasing a variables scope.

2021-03-03 22:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return 1; // Change this if this migration should be re-ran
Updated

2021-03-03 22:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +            log.info("Account info importing is disabled");
Done

2021-03-04 16:48 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return 1; // Change this if this migration should be re-ran
Did you push?  Still seeing re-ran.

2021-03-04 16:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return 1; // Change this if this migration should be re-ran
No push

2021-03-04 17:01 UTC, Nana-EC requested changes
Looking good.
Some improvements and nits suggested

2021-03-04 17:01 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AccountInfoMigrationTest.java
> +    void noChanges() throws Exception {
nit: this is more of an import only flow than noChanges. The accounts to get migrated/imported in.
Just a nit on the naming

2021-03-04 17:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AccountInfoMigrationTest.java
> +    void noChanges() throws Exception {
No, this is to simulate if this migration gets ran again like it would on our production instance. In that scenario there should be no updates to the entities. I simulate that by running the migration twice.

2021-03-04 17:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        EntityId accountEntityId = EntityId.of(accountInfo.getAccountID());
But it's not just the historical account ID, it's also the account ID of the entity loaded from the database. So it doesn't make sense to name as if it's different.

2021-03-04 17:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        Entities entity = entityExists.orElseGet(accountEntityId::toEntity);
Current entity is a confusing terminology. Current implies that it is the one loaded from the database whereas this is either the one from the db or an entity being constructed from historical data.

2021-03-04 17:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        if (entity.isDeleted() != accountInfo.getDeleted() && accountInfo.getDeleted()) {
It could but would cause an unnecessary updating of the entity object for deleted accounts.

2021-03-04 17:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +            entityRepository.save(entity);
~15K rows. Don't think it is worth optimizing.

2021-03-04 20:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        EntityId accountEntityId = EntityId.of(accountInfo.getAccountID());
I get they both share the same accountId, it's just you do two similar object comparisons following. The historic one and the current one and you went to get a merged object that preserves the current details but adds the historic where not specified.
Just reads better in comparisons when it's clear which object is which

2021-03-04 20:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        if (entity.isDeleted() != accountInfo.getDeleted() && accountInfo.getDeleted()) {
Ah, correct. Ignore

2021-03-04 20:59 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AccountInfoMigrationTest.java
> +    void noChanges() throws Exception {
Gotcha, no comments so I missed the 2nd migration :)

2021-03-04 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AccountInfoMigrationTest.java
> +    private Transaction transaction(Entities entity) {
Method has been deleted during refactoring.

2021-03-04 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AccountInfoMigrationTest.java
> +    private Entities entity(long num) {
Updated to `createEntity`

2021-03-04 23:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +            log.trace("Skipping entity {} that was created after the stream reset",
An entity can exist not just because of a create transaction but if it is referenced in another transaction like proxyAccountId, sender, receiver, etc. When that occurs we insert a dummy entity in the table with no info outside its ID and type.

2021-03-04 23:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        Optional<Entities> entityExists = entityRepository.findById(accountEntityId.getId());
Renamed to `currentEntity`

2021-03-04 23:09 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.importAccountInfo`                           | true                    | Import historical account information that occurred before the last stream reset               |
Renamed to `importHistoricalAccountInfo`. Still considering start date

2021-03-04 23:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return 1; // Change this if this migration should be re-ran
Pushed

2021-03-04 23:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AccountInfoMigrationTest.java
> +        Entities entity1 = entity(2977);
Moved to constants

2021-03-04 23:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        Entities entity = entityExists.orElseGet(accountEntityId::toEntity);
Fixed

2021-03-04 23:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        if (exists && hasCreateTransaction(accountEntityId)) {
Removed transaction query

2021-03-05 16:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +            log.trace("Skipping entity {} that was created after the stream reset",
The latter part is what I was referring to other than of course the create scenario.
Makes sense now. I realize the code below is what I wanted to make sure was accounted for.

2021-03-05 16:33 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        return "Backfill pre-OA account information";
Fair point.

2021-03-05 18:35 UTC, steven-sheehy commented
Migration when ran against mainnet data:
```
2021-03-05T12:30:35.149-0600 INFO main c.h.m.i.m.HistoricalAccountInfoMigration Importing historical account information
2021-03-05T12:31:19.990-0600 INFO main c.h.m.i.m.HistoricalAccountInfoMigration Successfully updated 0 accounts in 44.84 s
2021-03-05T12:31:20.014-0600 INFO main o.f.c.i.c.DbMigrate Successfully applied 1 migration to schema "public" (execution time 00:44.901s)
```

2021-03-05 18:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        if (!mirrorProperties.isImportAccountInfo()) {
startDate check added

2021-03-05 18:48 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.importAccountInfo`                           | true                    | Import historical account information that occurred before the last stream reset               |
startDate check added

2021-03-05 18:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AccountInfoMigration.java
> +        Entities entity = entityExists.orElseGet(accountEntityId::toEntity);
Had to undo this logic as there's no contract specific data in the `AccountInfo` export.

2021-03-05 19:43 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-03-05 21:00 UTC, ijungmann requested changes
One thought about the documentation, everything else looks good.

2021-03-05 21:00 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.importer.importHistoricalAccountInfo`                 | true                    | Import historical account information that occurred before the last stream reset               |
I think it would be worth mentioning here or somewhere in the docs that this is affected by `startDate`

2021-03-05 21:12 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.importHistoricalAccountInfo`                 | true                    | Import historical account information that occurred before the last stream reset               |
Sure, added

2021-03-05 21:14 UTC, ijungmann submitted a review, later dismissed

2021-03-05 21:25 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-03-05 22:52 UTC, ijungmann approved these changes

2021-03-05 23:19 UTC, merged