Stateproof alpha compact response design
hashgraph/hedera-mirror-node pull request #1659
Opened 2021-03-03 20:45 UTC by xin-hedera

**Detailed description**:
Revise the stateproof alpha design to add a compact format response based on the mechanisms provided by v5 record file & signature file. 

**Which issue(s) this PR fixes**:
Fixes #1442 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-03-03 21:00 UTC, steven-sheehy requested changes
We should also probably update the design in the check-state-proof README

2021-03-03 21:00 UTC, steven-sheehy commented on docs/design/stateproofalpha.md
> +    "compact": false,
Don't think it makes sense to have a compact key anymore. How about we put a `version` flag instead?

2021-03-03 21:00 UTC, steven-sheehy commented on docs/design/stateproofalpha.md
> +Depending on the format of the record file the transaction of interest is in, the REST API returns either the full
Perhaps instead of muddying the waters with compact vs full, we should just mention version 5 vs pre-V5. Should mention the benefits of the V5 format allow us to return a much more compact payload that doesn't need to contain the full file bytes but still provides verification.

2021-03-03 21:08 UTC, xin-hedera commented on docs/design/stateproofalpha.md
> +    "compact": false,
sure

2021-03-03 21:11 UTC, xin-hedera commented on docs/design/stateproofalpha.md
> +Depending on the format of the record file the transaction of interest is in, the REST API returns either the full
Will add `version`, the value will be what's in record_file.version for consistency and it will be always a number.

2021-03-08 21:52 UTC, Nana-EC reviewed
1st pass. Will circle back shortly

2021-03-08 22:41 UTC, ijungmann reviewed
Will give a second look, didn't see anything major the first pass.

2021-03-08 22:53 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/stateproof-16-compact-success-result.spec.json
> +    "sqlfuncs": ["./data/db/stateproof/addRecordFileWithBytes"],
I can add an optional `pathPrefix` in `setup`

2021-03-08 23:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/stateproof-17-compact-success-result-file-in-db.spec.json
> +      "hashes_after": [
added stateproof-18

2021-03-09 16:45 UTC, steven-sheehy approved these changes
LGTM

2021-03-09 17:28 UTC, ijungmann submitted a review, later dismissed

2021-03-09 18:14 UTC, Nana-EC reviewed
Looks good, minor nits for your verification

2021-03-09 18:28 UTC, xin-hedera commented on hedera-mirror-rest/stream/utils.js
> + * Converts a proto.TransactionID object to a string in the format of "shard.realm.num-sss-nnn"
will add toProtoTransactionId to `TransactionId` class, also change RecordFile classes and check-state-proof

2021-03-09 18:28 UTC, Nana-EC submitted a review, later dismissed
LGTM
You can open tickets for any improvements

2021-03-09 20:43 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-03-10 03:57 UTC, steven-sheehy approved these changes

2021-03-10 15:31 UTC, Nana-EC approved these changes
LGTM

2021-03-10 15:41 UTC, merged