Update Monitor and Data-Generator to use SDK v2
hashgraph/hedera-mirror-node pull request #1663
Opened 2021-03-04 06:30 UTC by Nana-EC

**Detailed description**:
Update monitor to use sdk v2

**Which issue(s) this PR fixes**:
Fixes #1540 
**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-04 23:58 UTC, steven-sheehy requested changes

2021-03-04 23:58 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
> +                .setAccountId(AccountId.fromString(accountId)).setExpirationTime(expirationTime)
nit: would prefer to keep each setter on its own line

2021-03-04 23:58 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenFreezeTransactionSupplier.java
> +                .setMaxTransactionFee(Hbar.fromTinybars(maxTransactionFee)).setTokenId(TokenId.fromString(tokenId))
nit: separate lines

2021-03-04 23:58 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +            log.debug("Hedera error for {} transaction {}: {}", type, e.transactionId, e.getMessage());
status is not updated so will mistakenly shows as successful

2021-03-04 23:58 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +            status = sre.status.name();
I'm not sure why `Status` duplicates `ResponseCodeEnum`, but we should probably use the inner proto generated  enum just in case. Think you can get it with `Status.toString()`.

2021-03-04 23:58 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +                            }
Sonar bug needs to be handled here. Would also prefer this catch be pushed into the constructor itself.

2021-03-05 00:27 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountUpdateTransactionSupplier.java
> +                .setAccountId(AccountId.fromString(accountId)).setExpirationTime(expirationTime)
This was a formatting issue from visual studio. Already fixed this but you were probably already reviewing.

2021-03-05 00:28 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenFreezeTransactionSupplier.java
> +                .setMaxTransactionFee(Hbar.fromTinybars(maxTransactionFee)).setTokenId(TokenId.fromString(tokenId))
Visual studio. Will fix.

2021-03-05 15:30 UTC, steven-sheehy requested changes

2021-03-05 15:30 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +        privateKey.getPublicKey();
unused

2021-03-05 15:30 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +            status = rse.getClass().getSimpleName();
Should use `status = rse.receipt.status.toString()`

2021-03-05 15:30 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +                        .filter(Objects::nonNull),
A constructor can't return null. Please remove filter.

2021-03-05 15:30 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +                    .getMirrorNode().getGrpc().getEndpoint());
Need to `Thread.currentThread().interrupt()`

2021-03-05 15:56 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +                            }
Moved this to constructor

2021-03-05 15:57 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +            status = sre.status.name();
Fixed

2021-03-05 15:57 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +            log.debug("Hedera error for {} transaction {}: {}", type, e.transactionId, e.getMessage());
Updated

2021-03-05 15:59 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +                        .filter(Objects::nonNull),
Left over from previous logic outside of constructor. Will remove.

2021-03-05 16:09 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +        privateKey.getPublicKey();
Removed

2021-03-05 16:09 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +            status = rse.getClass().getSimpleName();
Updated

2021-03-05 16:09 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +                        .filter(Objects::nonNull),
Removed

2021-03-05 16:09 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/GrpcSubscriber.java
> +                    .getMirrorNode().getGrpc().getEndpoint());
Added

2021-03-05 16:17 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-03-05 16:31 UTC, ijungmann requested changes
Couple small things.

2021-03-05 16:31 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private int maxRetryCount = 3;
Do we want it to retry here by default?  Would think for general purpose we're more worried about performance than getting every message through, and thus would set it to 0.

2021-03-05 16:31 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +@Log4j2
Is this used?

2021-03-05 16:32 UTC, ijungmann commented
Extremely tiny nit, you have "beta" misspelled in your description.

2021-03-05 16:49 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private int maxRetryCount = 3;
True, that's what the previous behavior was.

2021-03-05 17:00 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private int maxRetryCount = 3;
I was thinking that might be a good idea too, move it up into the Publisher properties or something.

2021-03-05 17:04 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishRequest.java
> +    private final Transaction<?> transactionBuilder;
Should rename field as well

2021-03-05 18:42 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private int maxRetryCount = 3;
Makes sense. Conferred and makes sense to specify it at a scenario level so will add it to `ScenarioProperties` so each scenario transaction can be appropriately configured with maxRetry

2021-03-05 18:42 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/CompositeSubscriber.java
> +@Log4j2
It no longer is, will remove

2021-03-05 18:43 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishRequest.java
> +    private final Transaction<?> transactionBuilder;
Renamed

2021-03-05 18:43 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +    private int maxRetryCount = 3;
Updated

2021-03-05 18:43 UTC, Nana-EC commented
> Extremely tiny nit, you have "beta" misspelled in your description.

Thanks. Fixed

2021-03-05 19:00 UTC, steven-sheehy approved these changes

2021-03-05 21:11 UTC, ijungmann approved these changes
Looks good.

2021-03-05 21:12 UTC, merged