Acceptance test miscellaneous  improvements
hashgraph/hedera-mirror-node pull request #1666
Opened 2021-03-05 19:36 UTC by Nana-EC

**Detailed description**:
A few improvements to acceptances tests

- Update `MirrorNodeClient` webclient to use `retrieve()` instead of `exchange()`
- Updated feature files to use lower case tags. Leave Initial `@Aceptance`, `@TokenBase` and `@SubscribeOnly` references to not immediately break OPS
- Pull in new 2.0.5-beta.4
- Uncomment schedule hcs message submit test 
- Update entity clients create methods to set both entity memo and transaction memo

**Which issue(s) this PR fixes**:
Fixes #1665 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-05 22:54 UTC, steven-sheehy requested changes

2021-03-05 22:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public Object callRestEndpoint(String uri, Class<?> classType, Object... uriVariables) {
Use generics to avoid casting in callee.

`public <T> T callRestEndpoint(String uri, Class<T> classType, Object... uriVariables) {`

2021-03-08 20:52 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-03-08 22:25 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        return (MirrorTransactionsResponse) callRestEndpoint("/{endpoint}/{transactionId}",
You're still casting everywhere.

2021-03-08 22:28 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        return (MirrorTransactionsResponse) callRestEndpoint("/{endpoint}/{transactionId}",
Yeah realized after I pushed. Pushed fix.

2021-03-08 22:28 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public Object callRestEndpoint(String uri, Class<?> classType, Object... uriVariables) {
Fixed

2021-03-08 22:32 UTC, steven-sheehy approved these changes
LGTM

2021-03-08 22:33 UTC, ijungmann approved these changes

2021-03-08 22:35 UTC, xin-hedera approved these changes

2021-03-08 22:36 UTC, merged