Add schedule transactions support to monitor
hashgraph/hedera-mirror-node pull request #1688
Opened 2021-03-10 05:54 UTC by Nana-EC

**Detailed description**:
Add schedule transaction support to monitor
- Add `ScheduleCreateTransaction`, `ScheduleSignTransactionSupplier` and `ScheduleDeleteTransactionSupplier` suppliers 
- Updated `TransactionType` with `SCHEDULE_CREATE`, `SCHEDULE_SIGN` and `SCHEDULE_DELETE` types
- Update `monitor.md` with context and example of config
- Updated data generator and monitor modules with `2.0.5-beta.4` of SDK
- Ad `getTransactionToSign()` and `getSignatoryKeys()` to `TransactionSupplier` interface to support retrieving scheduled transaction and keys for signing in generator
- Updated `ConfigurableTransactionGenerator` to set `PublishRequest .scheduledTransaction` and `PublishRequest .signatoryKeys` from transaction supplier
- Add memo fields to all suppliers
- Update `ExpressionConverterImpl` with support for `schedule` entity
- Update `PublishRequest` with fields `scheduledTransaction` and `signatoryKeys` to be used in generator 
- Updated `TransactionPublisher` to handled schedule case by extracting scheduled transaction, freezing with client, signing with keys and setting in `ScheduleCreate` transaction

**Which issue(s) this PR fixes**:
Fixes #1469 

**Special notes for your reviewer**:
Not all transactions are supported yet. Additionally, most scenario required creating and configuring an entity ahead of time.
Since we don't wait on records for performance reasons `CryptoCreate` scenario was the most applicable default scheduled transaction

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-03-11 16:35 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/TransactionSupplier.java
> + * Unless reTransactionPublisherquired by applicable law or agreed to in writing, software
Lol, will revert this. Funny find and replace effect

2021-03-11 16:35 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +public class ScheduleCreateTransactionSupplier implements TransactionSupplier<ScheduleCreateTransaction> {
Will delete this file, as the intention is to add schedule logic to individual transaction so they encompass their key logic. SDK transaction.schedule() makes this easy, only updates of payer and admin are optional

2021-03-11 16:35 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleSignTransactionSupplier.java
> +public class ScheduleSignTransactionSupplier implements TransactionSupplier<ScheduleSignTransaction> {
Might be worth similar logic here of having transaction handle schedule case.

May turn ScheduleProperties.scheduled into `ScheduledProperties.scheduleType` = (None|Create|Sign)
The the `transactionSupplier.get()` can return either the transaction, `ScheduleCreate` or `ScheduleSign`.

This can probably be done in a future ticket.

2021-03-11 16:35 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +            // if ScheduleCreate set the properties to the inner scheduledTransactionProperties
Will remove this as the flow isn't applied where I thought it was and properties are provided in ScheduleProperties.properties
Eventually it would be nice to just say `${operator.id}` and `${node.id}` in `application.yml`. 
However, it currently only really lends itself to entityId replacements and would require some refactoring of the `ExpressionType` and `ExpressionConverter` classes to get it working and be clean.

2021-03-11 16:35 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +        validateSupplier(supplier);
As part of some refactoring I pulled this into its own method to make it clear it did a single job.
Even though I removed the additional code this is still nice to have, let me know if you're opposed to it though

2021-03-11 18:28 UTC, steven-sheehy requested changes

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +        TransactionId transactionId = TransactionId.generate(sdkClient.getOperatorId()).setScheduled(true);
A client can't set scheduled=true, it is only set by the server when it is executed. Perhaps it works fine since either the SDK or server is clearing/ignoring it but it is misleading if set here.

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
> +                .setTransactionMemo(getMemo());
Why are we caching the memo? The point of the memo was to have the current time in it so we can calculate latencies. This negates that.

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenCreateTransactionSupplier.java
> +                .setTransactionMemo(getMemo())
Shouldn't cache memo

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleSignTransactionSupplier.java
> +    private final ScheduleId scheduleEntityId = ScheduleId.fromString(scheduleId);
Not sure it's worth caching this unless we're planning to performance test this transaction, which I don't think is possible at the moment due to its one time use.

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleDeleteTransactionSupplier.java
> +    private final ScheduleId scheduleEntityId = ScheduleId.fromString(scheduleId);
Not worth caching

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusUpdateTopicTransactionSupplier.java
> +    private final String memo = Utility.getMemo("Mirror node updated test topic");
Shouldn't cache

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusCreateTopicTransactionSupplier.java
> +    private final String memo = Utility.getMemo("Mirror node created test topic");
Shouldn't cache

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +public class AccountCreateTransactionSupplier extends AbstractSchedulableTransactionSupplier<AccountCreateTransaction> {
We definitely shouldn't couple every class to be forced to extend `AbstractSchedulableTransactionSupplier`. Prefer [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance). The `ScheduleCreateTransactionSupplier` should decorate an inner `TransactionSupplier`.

For now though, since the design of scheduled transactions is in a state of flux, I would suggest your remove `AbstractSchedulableTransactionSupplier` and just hardcode an inner `new AccountCreateTransaction()` inside `ScheduleCreateTransactionSupplier`. We can revisit this once the design and SDK support is finalized. It's even more coupled but it gets us to a MVP until things solidify.

2021-03-11 18:28 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +public class ScheduleCreateTransactionSupplier implements TransactionSupplier<ScheduleCreateTransaction> {
Think it should be kept. See previous comment.

2021-03-11 19:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +        TransactionId transactionId = TransactionId.generate(sdkClient.getOperatorId()).setScheduled(true);
This was the recommended logic form SDK. In an upcoming refactor I believe they will be setting and ensuring the transactionId is shared and set to true for the inner transaction

2021-03-11 19:04 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
> +                .setTransactionMemo(getMemo());
I forgot the Utility method pulls in a new time. Will revert the caching

2021-03-11 19:06 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleSignTransactionSupplier.java
> +    private final ScheduleId scheduleEntityId = ScheduleId.fromString(scheduleId);
Sounds good, will uncache

2021-03-11 19:09 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +public class AccountCreateTransactionSupplier extends AbstractSchedulableTransactionSupplier<AccountCreateTransaction> {
So revert back to my original commit which did what you described. Sounds good.
Notably as is not every class is forced to extend `AbstractSchedulableTransactionSupplier`. It's optional if you want to make it schedulable.

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
> +                .setTransactionMemo(getMemo());
Fixed

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenCreateTransactionSupplier.java
> +                .setTransactionMemo(getMemo())
Fixed

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleSignTransactionSupplier.java
> +    private final ScheduleId scheduleEntityId = ScheduleId.fromString(scheduleId);
Fixed

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleDeleteTransactionSupplier.java
> +    private final ScheduleId scheduleEntityId = ScheduleId.fromString(scheduleId);
Fixed

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusUpdateTopicTransactionSupplier.java
> +    private final String memo = Utility.getMemo("Mirror node updated test topic");
Fixed

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusCreateTopicTransactionSupplier.java
> +    private final String memo = Utility.getMemo("Mirror node created test topic");
Fixed

2021-03-11 23:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +public class AccountCreateTransactionSupplier extends AbstractSchedulableTransactionSupplier<AccountCreateTransaction> {
Reverted

2021-03-12 16:46 UTC, steven-sheehy requested changes

2021-03-12 16:46 UTC, steven-sheehy commented on docs/monitor.md
> +Scheduled transactions require unique configuration as they encompass 2 transactions during the entity creation.
nit: Spell out numbers when less than 10. 2 -> two

2021-03-12 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private Integer signatoryCount;
Should probably validate that signatoryCount <= total

2021-03-12 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +        return signatoryCount == null ? totalSignatoryCount : signatoryCount;
Would prefer both be required to avoid null checking and use primitive types. Default could be 1 of 1.

2021-03-12 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +            getPrivateKeyList().forEach(k -> scheduleCreateTransaction.addScheduleSignature(
Would prefer `getSigningKeys().forEach` and rename current `getSigningKeys()` to `createSigningKeys()` to match `createSignatoryKeys()` since they're both one-time construction.

2021-03-12 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    protected KeyList getPublicKeys() {
`private` and can remove the javadocs on these self-explanatory private getter/create methods. Docs should be non-obvious otherwise they just clutter the code and become a maintenance burden.

2021-03-12 17:17 UTC, ijungmann commented on docs/monitor.md
> +      maxRetries: 2
This is now maxAttempts

2021-03-12 17:26 UTC, ijungmann commented on docs/monitor.md
> +The syntax takes the form of `${type.name}` where `type` is one of `account`, `schedule`, `token`, or `topic` and `name` is a
nit: I find this sentence a little hard to read, I keep reading it as type = [account, schedule, token, topic and name].  I feel like this might be all that's needed
```suggestion
The syntax takes the form of `${type.name}` where `type` is one of `account`, `schedule`, `token`, or `topic`, and `name` is a
```
Or maybe break the sentence into a few sentences.

2021-03-12 17:28 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +        String memo = Utility.getMemo("Mirror node updated test account");
Think this is copy-paste from the update supplier below.
```suggestion
        String memo = Utility.getMemo("Mirror node created test account");
```

2021-03-12 17:32 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +        AccountCreateTransaction scheduledTransaction = new AccountCreateTransaction()
nit: since you refer to this transaction as the inner transaction in the later comment, maybe it makes sense to just continue calling this `innerTransaction
```suggestion
        AccountCreateTransaction innerTransaction = new AccountCreateTransaction()
```

2021-03-12 17:38 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleDeleteTransactionSupplier.java
> +                .setScheduleId(ScheduleId.fromString(scheduleId));
Add a memo to this.

2021-03-12 17:40 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleSignTransactionSupplier.java
> +                .setScheduleId(ScheduleId.fromString(scheduleId));
Add a memo here.

2021-03-12 17:40 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
> +        String memo = Utility.getMemo("Mirror node created test token");
```suggestion
        String memo = Utility.getMemo("Mirror node updated test token");
```

2021-03-12 19:21 UTC, Nana-EC commented on docs/monitor.md
> +      maxRetries: 2
Right. Ian mentioned it too. Will leave it to the schedule related.

2021-03-12 19:22 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            log.info("Received response: {} for {}", response, transactionId);
Will revert

2021-03-12 19:55 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +                scheduleCreateTransactionSupplier.setAdminKey(adminKey.toString());
Correct, `adminKey` and `payerAccount` are indeed not required. However the `nodeAccountId` and `operatorAccountId` values are required for the `ScheduleCreateTransactionSupplier` to be able to freeze transactions.
Without is the `ExpressionConverterImplTest.schedule()` test fails.

I can minimize the code by removing the optional fields but I'm not sure I can removed it all

2021-03-12 20:19 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private Integer signatoryCount;
I could use a `ConstraintValidator` on the class or I could just have `getNumberOfSignatories()` return the min of `signatoryCount` and `totalSignatoryCount` thus capping the number to `totalSignatoryCount`

2021-03-12 20:22 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +            getPrivateKeyList().forEach(k -> scheduleCreateTransaction.addScheduleSignature(
Good suggestion, will do

2021-03-12 20:23 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    protected KeyList getPublicKeys() {
Left over logic from Abstract class. Glad it's self-explanatory. Will remove java docs then

2021-03-12 20:24 UTC, Nana-EC commented on docs/monitor.md
> +```
Yeah, will reduce to just
```yaml
publish:
  scenarios:
    - name: Scheduled Crypto Create
      properties:
        nodeAccountId: 0.0.3
        operatorAccountId: 0.0.1018
        receiverSignatureRequired: true
        signatoryCount: 4
        totalSignatoryCount: 5
      type: SCHEDULE_CREATE
```

2021-03-12 20:25 UTC, Nana-EC commented on docs/monitor.md
> +The syntax takes the form of `${type.name}` where `type` is one of `account`, `schedule`, `token`, or `topic` and `name` is a
Sounds good, will update

2021-03-12 20:25 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +        String memo = Utility.getMemo("Mirror node updated test account");
Yep

2021-03-12 20:31 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +                scheduleCreateTransactionSupplier.setAdminKey(adminKey.toString());
Right, the ask only was for adminKey and payer.

2021-03-12 20:33 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private Integer signatoryCount;
min approach works for me. Or throwing an error within get()

2021-03-12 20:35 UTC, Nana-EC commented on docs/monitor.md
> +      maxRetries: 2
Fixed

2021-03-12 20:35 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            log.info("Received response: {} for {}", response, transactionId);
Fixed

2021-03-12 20:35 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private final Integer totalSignatoryCount = 1;
Fixed

2021-03-12 20:35 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private Integer signatoryCount;
Fixed

2021-03-12 20:36 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private String payerAccount;
Fixed

2021-03-12 20:36 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +                scheduleCreateTransactionSupplier.setAdminKey(adminKey.toString());
Removed optional

2021-03-12 20:36 UTC, Nana-EC commented on docs/monitor.md
> +Scheduled transactions require unique configuration as they encompass 2 transactions during the entity creation.
Fixed

2021-03-12 20:37 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    private Integer signatoryCount;
Went with min approach. Let me know if that's fine

2021-03-12 20:37 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +        return signatoryCount == null ? totalSignatoryCount : signatoryCount;
Both are now ints and have a 1 default

2021-03-12 20:38 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +            getPrivateKeyList().forEach(k -> scheduleCreateTransaction.addScheduleSignature(
Fixed

2021-03-12 20:38 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +    protected KeyList getPublicKeys() {
Fixed

2021-03-12 20:38 UTC, Nana-EC commented on docs/monitor.md
> +      maxRetries: 2
Removed

2021-03-12 20:38 UTC, Nana-EC commented on docs/monitor.md
> +```
Fixed

2021-03-12 20:38 UTC, Nana-EC commented on docs/monitor.md
> +The syntax takes the form of `${type.name}` where `type` is one of `account`, `schedule`, `token`, or `topic` and `name` is a
Fixed

2021-03-12 20:38 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/AccountCreateTransactionSupplier.java
> +        String memo = Utility.getMemo("Mirror node updated test account");
Fixed

2021-03-12 20:39 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +        AccountCreateTransaction scheduledTransaction = new AccountCreateTransaction()
Fixed

2021-03-12 20:39 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleDeleteTransactionSupplier.java
> +                .setScheduleId(ScheduleId.fromString(scheduleId));
Fixed

2021-03-12 20:39 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleSignTransactionSupplier.java
> +                .setScheduleId(ScheduleId.fromString(scheduleId));
Fixed

2021-03-12 20:39 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
> +        String memo = Utility.getMemo("Mirror node created test token");
Fixed

2021-03-12 20:44 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +        TransactionId transactionId = TransactionId.generate(sdkClient.getOperatorId()).setScheduled(true);
Still doesn't make sense. `TransactionId.scheduled` is not something the client can set, it is purely a server side value.

2021-03-12 20:49 UTC, steven-sheehy approved these changes
LGTM

2021-03-12 23:23 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +        TransactionId transactionId = TransactionId.generate(sdkClient.getOperatorId()).setScheduled(true);
In fact, there's a `TRANSACTION_ID_FIELD_NOT_ALLOWED` error for this very scenario.

2021-03-15 15:22 UTC, ijungmann approved these changes

2021-03-15 15:40 UTC, merged

2021-03-15 15:42 UTC, xin-hedera commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +        innerTransaction.setTransactionId(transactionId.setScheduled(true));
nit: setScheduled to true on the same line the id is generated

2021-03-15 15:46 UTC, xin-hedera approved these changes
LGTM.

just a question regarding if transactionId schedule = true is allowed / needed for schedulecreate.