Correct REST transaction endpoints to include token_transfer_list on token wipes
hashgraph/hedera-mirror-node pull request #1703
Opened 2021-03-10 22:15 UTC by ijungmann

**Detailed description**:
The REST endpoints for transactions previously only populated the token_transfers list when the transaction was of type CRYPTOTRANSFER.  However, TOKENWIPE transactions also cause tokens to be transferred out of accounts, and should cause the token_transfer_list to populate.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-10 22:20 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +           OR t.type = ${await transactionTypes.get('TOKENWIPE')}
Perhaps this should be an IN() clause.

2021-03-10 22:33 UTC, Nana-EC requested changes
Looks good. Will wait on the `IN()` vs `OR` change

2021-03-10 22:33 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +           OR t.type = ${await transactionTypes.get('TOKENWIPE')}
Yeah was gonna suggest `IN()` in this case

2021-03-10 22:44 UTC, ijungmann commented
> Looks good. Will wait on the `IN()` vs `OR` change

Done.

2021-03-10 22:55 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-29-tokenwipe.spec.json
> +            "amount": -20
should the amount be negative? The protobuf amount type is uint64.

2021-03-10 23:08 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +           ${await transactionTypes.get('TOKENWIPE')}
better move the two lines to a function

also just noticed in case sth wrong, e.g., the string is misspelled, transactionTypes.get (map.get) returns undefined. we should fix tranasctionType.get to throw an exception in that case

2021-03-10 23:11 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-29-tokenwipe.spec.json
> +            "amount": -20
When actually submitting a wipe, the amount is positive, but services negates it internally and the mirror node gets the negative result.  [Found the logic here](https://github.com/hashgraph/hedera-services/blob/ba9245706eaa458cc9e206301bee2085e71db177/hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java#L331)

2021-03-10 23:35 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-03-10 23:40 UTC, steven-sheehy requested changes

2021-03-10 23:40 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      ON t.type IN (
Wait, why are we even joining conditionally based upon transaction type? Shouldn't we just join on consensus timestamp and be done with it? If we find out in the future transaction type X should also have token transfers we won't have to change.

2021-03-10 23:54 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +      ON t.type IN (
yup this looks weird. there might be performance gain, otherwise we can completely remove it.

2021-03-11 01:32 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +           ${await transactionTypes.get('TOKENWIPE')}
Removed the two lines per Steven's comment.  Also reworked `transactionTypes.get` to be safer, and added test cases for it.

2021-03-11 01:33 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +      ON t.type IN (
Removed it.

2021-03-11 02:02 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      ON t.type IN (
Is it still performant?

2021-03-11 02:08 UTC, Nana-EC approved these changes
LGTM

2021-03-11 04:07 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +      ON t.type IN (
I'll do some more testing in the morning, but I've used the transaction perf tests to hammer a local service connected to the dev/testnet database several times with the new vs old query, I have not noticed any significant performance hit.

2021-03-11 18:04 UTC, steven-sheehy requested changes

2021-03-11 18:04 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Invalid transactionType value '${transactionType}'`);
Would prefer to directly throw `InvalidArgumentError` from `transactionTypes.get()`

2021-03-11 18:38 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Invalid transactionType value '${transactionType}'`);
The only caveat to that is `transactionTypes.get()` previously was/could someday also be used internally for building queries, so in theory the error could be caused by bad code on our part and not actually user error (400 error vs 500).  Not that we should be releasing code with such a major bug.  I'll make the change as for now it's not an issue, just something to keep in mind.

2021-03-11 20:28 UTC, xin-hedera requested changes

2021-03-11 20:28 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration.test.js
> +describe('DB integration test - transactionTypes.get', async () => {
```suggestion
describe('DB integration test - transactionTypes.get', () => {
```

this causes error
```
Returning a Promise from "describe" is not supported. Tests must be defined synchronously.
Returning a value from "describe" will fail the test in a future version of Jest.
```

2021-03-11 20:28 UTC, xin-hedera commented on hedera-mirror-rest/transactionTypes.js
> +    return type;
these lines should be moved out of this try block, so the error thrown here won't be caught and rethrown as `DbError`

2021-03-11 20:28 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +       LEFT OUTER JOIN token_transfer ttl ON tlist.consensus_timestamp = ttl.consensus_timestamp
since `transactionTypes` is no longer neede, remove the `require`:

```
const transactionTypes = require('./transactionTypes');
```

2021-03-11 21:09 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +      throw new Error(`Transaction type ${transactionTypeName.toUpperCase()} not found in db`);
Do you want the catch statement after this changed then to also throw an `InvalidArgumentError`?  Right now this error turns into a DbError

2021-03-11 21:10 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +      throw new Error(`Transaction type ${transactionTypeName.toUpperCase()} not found in db`);
Never mind, this won't be a concern after taking Xin's approach.

2021-03-11 21:26 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +describe('DB integration test - transactionTypes.get', async () => {
Fixed

2021-03-11 21:33 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +       LEFT OUTER JOIN token_transfer ttl ON tlist.consensus_timestamp = ttl.consensus_timestamp
Removed

2021-03-11 21:33 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +    return type;
Moved.

2021-03-11 21:34 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +    throw new InvalidParameterTypeError(`Invalid parameter ${transactionTypeName} is not a string`);
Changed to InvalidArgumentError

2021-03-11 21:34 UTC, ijungmann commented on hedera-mirror-rest/transactionTypes.js
> +      throw new Error(`Transaction type ${transactionTypeName.toUpperCase()} not found in db`);
Fixed.

2021-03-11 21:34 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Invalid transactionType value '${transactionType}'`);
Done.

2021-03-11 21:58 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Invalid transactionType value '${transactionType}'`);
This catch is still here

2021-03-11 22:06 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Invalid transactionType value '${transactionType}'`);
Ah, whoops, I added a catch in two locations and removed the wrong one.  This one has been removed now, `isValidTransactionType()` catch has been put back as it does its own error logic later on.

2021-03-11 22:47 UTC, ijungmann commented
Found a bug in accounts.js, fixed that as well now as that was causing tests to fail.

2021-03-11 22:51 UTC, steven-sheehy approved these changes
LGTM

2021-03-11 23:29 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +      ON t.type IN (
Ran EXPLAIN ANALYZE against testnet replica with and without the IN() statement on the most basic query (no params, just a raw get transactions), difference was about 6 ms, so not a noticeable difference.

2021-03-12 00:27 UTC, xin-hedera approved these changes
LGTM

2021-03-12 16:38 UTC, merged