Proto based balance file parser
hashgraph/hedera-mirror-node pull request #1713
Opened 2021-03-15 15:10 UTC by xin-hedera

**Detailed description**:

- Add `ProtoBalanceFileReader` to read gzipped proto-based balance file
- Add multiple extension support to `StreamType`
- Add `StreamFilename` to handle stream filename related operations
- Update downloader to list from the signature file with alphabetically last extension
- Update downloader to support stream type with multiple extensions

**Which issue(s) this PR fixes**:
Fixes #1679 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-03-15 18:58 UTC, Nana-EC requested changes
1st pass, will circle back

2021-03-15 19:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +            throw new InvalidStreamFileException("Unable to open gzipped file " + filename, ex);
only new `GZIPInputStream` can throw the `IOException`

2021-03-15 19:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
> +                    .name(streamFileData.getFilename())
it's intentional. `loadEnd` should be set in the parser. So I also removed the `setLoadEnd` in `CsvBalanceFileReader`

2021-03-16 15:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
> +                    .name(streamFileData.getFilename())
Gotcha

2021-03-16 15:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +            throw new InvalidStreamFileException("Unable to open gzipped file " + filename, ex);
Makes sense then

2021-03-16 16:07 UTC, steven-sheehy requested changes

2021-03-16 16:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                            .collect(Collectors.toList());
Can avoid the `fileStreamSignatures` list construction if you just `forEach` at the end instead of collect. Count can be incremented within that `forEach`.

2021-03-16 16:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReaderTest.java
> +    private static final String FILEPATH = "data/accountBalances/proto/" + TIMESTAMP + "_Balances.pb.gz";
Use Path.of for windows compatability.

2021-03-16 16:12 UTC, steven-sheehy commented
We can even consider not storing the gz extension in the stream file tables and just add a compressed column. Reason is ops might later want to re-compress past files in the buckets to save costs and improve performance. Technically, only the filename without the gz is approved and generated by the node software itself.

2021-03-16 16:21 UTC, ijungmann reviewed
Looks good.

2021-03-16 16:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return new StreamFilename(filename).getInstant();
I agree.

2021-03-16 20:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return new StreamFilename(filename).getInstant();
If you parse and store the `StreamFilename` once per `StreamFileSignature` and `StreamFile` as I suggest, this method won't be needed.

2021-03-17 20:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> -    private final String filename;
will add them back

2021-03-19 14:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +            if (filename.endsWith("." + StreamType.GZ_EXTENSION)) {
removed `GZ_EXTENSION`, the logic became if the second last the extension matches one of the data / signature extensions, the last extension is for compression

2021-03-19 14:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +                .map(StreamFilename::getInstantFromStreamFilename)
changed to get the file instant from `StreamFile.getConsensusStart()`

2021-03-19 14:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        this.filename = filename;
added

2021-03-19 14:58 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReaderTest.java
> +    private static final String FILEPATH = "data/accountBalances/proto/" + TIMESTAMP + "_Balances.pb.gz";
changed

2021-03-19 23:19 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-03-22 22:52 UTC, ijungmann approved these changes

2021-03-22 23:19 UTC, Nana-EC requested changes
Looks good. 2 minor suggestions

2021-03-22 23:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/PendingDownload.java
> +        this.streamFilename = streamFilename;
If this is only stored to allow for the getFilename() later on then maybe we should consider a minimalistic approach and store the strong rather. Set 
```suggestion
        private final String streamFilename;
        ...
        this.streamFilename = streamFilename.getFilename();
```

2021-03-23 14:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/PendingDownload.java
> +        this.streamFilename = streamFilename;
`getStreamFilename` is called in `parseSignatureFile`

2021-03-23 16:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/PendingDownload.java
> +        this.streamFilename = streamFilename;
Sounds good

2021-03-23 16:28 UTC, Nana-EC approved these changes
LGTM

2021-03-23 16:48 UTC, steven-sheehy requested changes

2021-03-23 16:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    streamFilenamePairs.add(pair.get());
This changes `Downloader` to now have to wait for at least 1/3 of all signatures and data files to be uploaded before verifying signatures. This will increase latency and decrease throughput of the Downloader since data files take quite a bit longer to upload. Since we're not downloading and verifying all data files, this inefficient. In addition, it greatly increases the complexity and maintenance burden.

I think we should revert to the previous logic of only waiting for enough signatures to be present before reaching consensus. For now, we can assume that the signature filename is the same as the data file besides the `_sig` (since it is). If that changes in the future, we can revisit the logic and have it try gz first, then non-gz and possibly save that order for the next invocation to optimize.

2021-03-23 17:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +    public StreamFilename(String filename) {
will change as suggested

2021-03-23 17:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamType.java
> +        this.lastSignatureExtension = this.signatureExtensions.stream().max(Comparator.naturalOrder()).orElseThrow();
agree this is unnecessary.

clarification, here the intention is just the lexically last extension, not necessarily the highest priority. it's just a choice of which extension to use when compose filename in `StreamFilename.getFilename`

2021-03-23 17:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    streamFilenamePairs.add(pair.get());
sure. with that assumption the logic will be simpler.

2021-03-24 00:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        this.instant = extractInstant(filename, this.fullExtension, this.streamType.getSuffix());
tried to move logic of extract* into constructor, got some not easy to handle sonar code smells, and the constructor looks rather big and not easy to understand, so reverted it back

2021-03-24 21:33 UTC, steven-sheehy requested changes

2021-03-24 21:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                .collect(Multimaps.toMultimap(
Constructing a map to later iterate over is a bit inefficient. Can we use `Collectors.groupingBy()` to directly construct the map and dropping the lower priority signatures? Something like this:

```java
.filter(s -> s != null && s.getFileType() == SIGNATURE)
.collect(groupBy(StreamFilename::getInstant, maxBy(Comparator.comparing(StreamFilename::getExtension))));
return signatureFilenamesByInstant.values();
```

The above is an example, in reality we need a comparator for extensions by priority not lexographically.

2021-03-25 00:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                                        count.incrementAndGet();
it keeps the original logic. I'll add another counter `totalDownloaded` which is the sum of `count`, then calculate the rate as `totalDownloaded / elapsed` and change the log message to reflect `totalDownloaded` signatures of `totalDownloads`

2021-03-25 00:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                                        count.incrementAndGet();
I think it was just wrong before. Don't think we need the distinction of expected vs actual downloads. That would just clutter the logs

2021-03-25 00:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                                        count.incrementAndGet();
sure

2021-03-25 16:12 UTC, steven-sheehy requested changes

2021-03-25 16:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                .collect(Collectors.toList());
Would prefer to directly return the `signatureFilenamesByInstant.values()` and convert to `PendingDownload` in `downloadAndParseSigFiles()`. Since it has to loop over the list anyway it might as well do the transformation there avoid the list construction here. Also, we can potentially optimize it by doing it in parallel there.

2021-03-25 16:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        maxBy(StreamFilename.EXTENSION_COMPARATOR)
I don't think we need to explicitly reference the `EXTENSION_COMPARATOR` and we can use `Comparator.naturalOrder()` since it implements `Comparable`.

2021-03-25 16:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        LinkedHashMap::new,
Why is insertion order helpful? We're downloading all signatures before moving on to the next step, so the download order doesn't matter. `HashMap` (the default) should be sufficient and less overhead.

2021-03-25 16:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                            parseSignatureFile(pendingDownload, nodeAccountId)
We can potentially use `pendingDownloads.parallelStream().forEach()` to download signatures in parallel.

2021-03-25 16:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +    public static final Comparator<StreamFilename> EXTENSION_COMPARATOR = Comparator
We shouldn't expose this unless it differs from the implementation of `Comparable`.

2021-03-25 16:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +            .comparing(StreamFilename::getExtension);
It doesn't seem to matter at the moment for our purposes, but for future proofing we should include `getInstant()`.

2021-03-25 16:34 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        maxBy(StreamFilename.EXTENSION_COMPARATOR)
yeah it's a bit confusing, natural order would use `StreamFilename`'s comparator which is ordered by `filename`

2021-03-25 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        LinkedHashMap::new,
just a preference and agree the end result is the same as long as downloading of the files are kicked off in parallel

2021-03-25 16:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        maxBy(StreamFilename.EXTENSION_COMPARATOR)
Oh, I missed the extra comparator. We could combine them if we switch to use instant + streamType + extension. But it's probably fine as is.

2021-03-25 16:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        LinkedHashMap::new,
Even if not in parallel, we block for all signature downloads to complete before signature verification so order doesn't matter.

2021-03-25 16:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                            parseSignatureFile(pendingDownload, nodeAccountId)
`parallelStream` may not kick off downloading all at once because the underlying threads used can be less than the number of files to download, so I'd prefer to keep the overhead of constructing `List<PendingDownload>`.

2021-03-25 17:13 UTC, steven-sheehy approved these changes
LGTM

2021-03-25 18:26 UTC, Nana-EC approved these changes
LGTM

2021-03-25 18:52 UTC, ijungmann approved these changes

2021-03-25 19:00 UTC, merged