Add ability for REST transaction queries with credit/debit parameter to retrieve token only transfers
hashgraph/hedera-mirror-node pull request #1714
Opened 2021-03-15 17:32 UTC by ijungmann

**Detailed description**:
PR #1662 added the ability to get token only transfers when querying the transactions REST endpoint with an account id, but this did not extend to a credit/debit query, which has different logic.  This PR corrects that.

**Which issue(s) this PR fixes**:
Fixes #1686

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-16 17:40 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +  // if (logger.isTraceEnabled()) {
Undo

2021-03-16 18:56 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    // account filter applies to transaction.payer_account_id, crypto_transfer.entity_id, and token_transfer.account_id, a full outer join
Move this

2021-03-16 19:24 UTC, ijungmann commented
After the changes to the credit/debit query, it looked very similar to the account query (only differences being the credit/debit where clause and account query does an additional outer join on transaction), so I did some refactoring to reduce the complexity and dupe code.

2021-03-16 19:42 UTC, ijungmann commented
Performance results of new credit/debit query against testnet replica:
With no other filters:
```
 Planning time: 0.180 ms
 Execution time: 0.558 ms
 ```
 With SUCCESS result filter (join on transaction table)
 ```
 Planning time: 0.487 ms
 Execution time: 1.445 ms
 ```

2021-03-16 21:29 UTC, steven-sheehy requested changes

2021-03-17 15:43 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
> +        "transfers": [],
Nope, I can add that.

2021-03-17 15:43 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
> +        "transfers": [],
Nope, I can add that.

2021-03-17 16:19 UTC, Nana-EC requested changes
Looking good.
Request a clarification, provided a suggestion and agree with the test expansion suggestions so will wait on those also.

2021-03-17 16:19 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    if (creditDebitQuery) {
There's nothing stopping people from doing both a creditDebitQuery and a namedAccountQuery right?
Is the else condition here handling that case or is something to cover in this PR or another ticket?

2021-03-17 16:19 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +  const transactionAccountQuery = namedAccountQuery.replace(/ctl\.entity_id/g, 't.payer_account_id');
I'm wondering whether another layout for this is easier readability and maintainability.  Maybe add a `getTransactionCreditDebitQuery()` and a `getTransactionNameAccountQuery()` to contain the appropriate logic below.

Then `getTransactionsInnerQuery()` is shorter

2021-03-17 17:07 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
> +        "transfers": [],
Added a test with a crypto transfer, a token transfer, and one with both.

2021-03-17 17:07 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
> +        "transfers": [],
Added a test with a crypto transfer, a token transfer, and one with both.

2021-03-17 18:11 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    if (creditDebitQuery) {
Someone can filter on both credit/debit and account, and the credit/debit query can handle the account filter (in fact, the specs I added have an account filter because that would be the most general use case).  The creditDebitQuery and the namedAccountQuery are mostly identical, the only major difference is in the accountQuery there has to be a full outer join on transaction in case the payer_account_id is the given account, whereas in the creditDebitQuery if you have the account filter you still don't want to full outer join the transaction table, since you only care about transactions where the account actually sent or received something.
So the if technically handles creditDebitQuery and (creditDebitQuery && namedAccountQuery), and the else is ONLY namedAccountQuery

2021-03-17 18:31 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +  const transactionAccountQuery = namedAccountQuery.replace(/ctl\.entity_id/g, 't.payer_account_id');
Previously they were partially split out, my concern with splitting them out is that the two queries are more similar than they are different, and there ends up being some code duplication that has to be updated in both places when things change.  I'm wondering if changing some of the variable names would help with readability, we're using query to mean both "an entire SQL query" and "a query param turned into  a WHERE clause".  I'll look for ways to clean it up, if others want it split back out I can rework it to do that.

2021-03-17 18:43 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-33-credit-type-crypyo-and-token-transfers.spec.json
> +  "description": "Transaction api calls for transactions via credit type query filter where account only receives token transfer",
Rename this and other new spec

2021-03-17 18:58 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
> +            "amount": -1200
Added a test for that.

2021-03-17 18:58 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
> +            "amount": 200
Added a test for that.

2021-03-17 20:02 UTC, xin-hedera requested changes

2021-03-17 20:13 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +  const transactionAccountQuery = namedAccountQuery.replace(/ctl\.entity_id/g, 't.payer_account_id');
That makes sense. Some renaming might help but understood on the maintenance side

2021-03-17 20:20 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +        SELECT DISTINCT COALESCE(ctl.consensus_timestamp, ttl.consensus_timestamp) AS consensus_timestamp
Good call, that checks out to me.  Removed.

2021-03-17 20:25 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    if (creditDebitQuery) {
Gotcha, so far as the different permutations are covered I'm good

2021-03-17 20:48 UTC, Nana-EC approved these changes
LGTM

2021-03-17 21:13 UTC, xin-hedera approved these changes
LGTM

2021-03-17 21:46 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
> +            "amount": -1200
I didn't mean a whole new spec. Just add the transaction to this file. Adding extra rows that don't show up just helps verify intended output.

2021-03-17 21:47 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
> +            "amount": 200
I didn't mean a whole new spec. Just add the transaction to this file. Adding extra rows that don't show up just helps verify intended output.

2021-03-17 21:56 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
> +            "amount": -1200
Ah, got it.  Removed the new specs and added a second transaction to each of these specs where the transfers are flipped (credit for debit).

2021-03-17 21:57 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
> +            "amount": 200
Got it, corrected.

2021-03-17 22:00 UTC, steven-sheehy approved these changes
LGTM

2021-03-17 22:10 UTC, merged