Replace null character on insert
hashgraph/hedera-mirror-node pull request #1716
Opened 2021-03-15 22:32 UTC by steven-sheehy

**Detailed description**:
- Fix failing on insert of tokens with null character (0x0000) in symbol or name

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Will backport to 0.29 and tag rc2 to unblock previewnet. I don't unescape replacement character in REST API as this is just a temporary fix until services blocks null char in strings in v0.13

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-15 22:52 UTC, Nana-EC requested changes
Looks good.
Repository tests should be broken out into domain and repository though.

2021-03-15 22:52 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityRepositoryTest.java
> +        assertThat(entityRepository.findById(entities.getId())).get().isEqualTo(entities);
This and the `TokenRespositoryTest` are really 2 sets of tests - domain and repository combined.
These tests are covering both that the setter utilizes the replace logic for the null char and that the repository can persist the replacement char and read it back as expected.

You should probably add domain tests for entity and token that verify the setter logic specifically.
Then update these tests to use the `NULL_REPLACEMENT` where you are using `(char) 0`.

2021-03-15 23:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityRepositoryTest.java
> +        assertThat(entityRepository.findById(entities.getId())).get().isEqualTo(entities);
Done

2021-03-15 23:27 UTC, Nana-EC approved these changes
LGTM

2021-03-16 00:52 UTC, xin-hedera approved these changes
LGTM

2021-03-16 02:49 UTC, merged