Fix npm run lint
hashgraph/hedera-mirror-node pull request #1718
Opened 2021-03-16 19:34 UTC by steven-sheehy

**Detailed description**:
- Add `--fix` to lint to automatically fix some problems and include those fixes
- Fix `npm run lint` not working
- Fix `.prettierignore` not ignoring all non-JavaScript modules
- Remove duplicate `.prettierrc` since `prettier` block in `package.json` takes precedence

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

First commit contains my manual code changes. Second commit contains eslint automated fixes. Before adding `--fix`:
```
✖ 1413 problems (1133 errors, 280 warnings)
  344 errors and 0 warnings potentially fixable with the `--fix` option.
```

After adding `--fix`:
```
✖ 1053 problems (773 errors, 280 warnings)
```

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-16 19:35 UTC, steven-sheehy commented
Draft since I will wait until #1714 to merge before pushing the automated lint fixes in the 2nd commit.

2021-03-18 15:53 UTC, ijungmann commented on hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
> +      `${'<tr>' + '<tr>' + '<tr>' + '<td>' + '<span class="dot" style="background-color:'}${
Is this first ${} needed?  Maybe I'm reading it wrong but it looks odd.

2021-03-18 15:57 UTC, ijungmann requested changes
Looks good, just the one question mentioned above.

2021-03-18 16:08 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
> +      `${'<tr>' + '<tr>' + '<tr>' + '<td>' + '<span class="dot" style="background-color:'}${
Probably not, this looks to be just eslint's best attempt at converting the previous string concats to templated string. I can tweak it further.

2021-03-18 16:44 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
> +      `${'<tr>' + '<tr>' + '<tr>' + '<td>' + '<span class="dot" style="background-color:'}${
Fixed along with some other minor improvements to that file.

2021-03-18 16:55 UTC, Nana-EC approved these changes
LGTM

2021-03-18 17:20 UTC, ijungmann commented on hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
> +      `${'<tr>' + '<tr>' + '<tr>' + '<td>' + '<span class="dot" style="background-color:'}${
Much better

2021-03-18 17:21 UTC, ijungmann approved these changes
LGTM

2021-03-18 17:23 UTC, merged