Provide one time migration to fix incorrect keys in t_entities
hashgraph/hedera-mirror-node pull request #1721
Opened 2021-03-17 21:48 UTC by Nana-EC

**Detailed description**:
Some of the data in the account export was bad or out of date, causing incorrect keys to be inserted into the database in [#273](https://github.com/hashgraph/hedera-mirror-node/pull/273).
We needed a way to correct stale keys at once against network values 

- Add entity-info-update npm package for reuse
- Add `networkEntityService.js` with logic to pull accountInfo information from network using configure js-sdk
- Add `dbEntityService.js` with logic to get and update entity info from mirror db
- Add `entityUpdateHandler.js` to compare db and network entities to determine stale entities and create entities that will be used to update the db
- Add `index.js` to orchestrate logic of pulling entities from csv, validated them, creating new entities and persisting them
- Add a `config.yml` to contain mirror node customizable details for migration
- Add `config.js` to load `application.yml` at load for use by other files
- Add `utils.js` with shared util info for file IO and proto methods

**Which issue(s) this PR fixes**:
Fixes #509 

**Special notes for your reviewer**:
- Script has been verified against a local copy of mainnet data ingested
- js-sdk is missing memo fields which should be part of the comparison
The PR will not be checked in. Rather the PR after approval and following migration run will be closed and the branch maintained should it be of use later

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-18 20:57 UTC, steven-sheehy requested changes

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  const ed25519Hex = key._keys.toString().split(',')[0];
It shouldn't just take the first. It should only return an ed25519Hex if there's exactly one key in the list.

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/index.js
> +  if (config.dryRun === false) {
Could've pushed dryRun to be around db save so it could print out changed entity. But not a big deal.

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/config/application.yml
> +        entitiesTableName: t_entities_bkup
I'm not sure this needs to be a config option as the entities table should always be `t_entities`. We're not going to update some other table then swap them. A backup should be done beforehand and the update run on the actual table.

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +    entity.proxy_account_id,
Still awaiting memo support from SDK

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (!networkEntity.key || networkEntity.key._keys === undefined) {
Is this even possible? It looks like SDK throws an error for this.

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.ed25519_public_key_hex !== ed25519Hex) {
This should compare the raw bytes to see if it should be updated. Not all keys are simple type and ed25519Hex is an optional field that is null for those.

2021-03-18 20:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    updateEntity.auto_renew_period = networkEntity.autoRenewPeriod.seconds.toString();
Why are we comparing as string and update to string when the underlying column is long?

2021-03-18 21:44 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/index.js
> +  if (config.dryRun === false) {
Had it there initially, I can move it back.
Notably the changed entity is given by the elements in the updateList. 
There's a trace log that prints out the entity at the end of `entityUpdateHandler.getUpdatedEntity()`

2021-03-18 21:45 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/config/application.yml
> +        entitiesTableName: t_entities_bkup
Honestly this was for flexibility during the actual migration.
If you wanted to do a test run or want to update a backup of the table and do the switching etc.

The `t_entities_bkup` reference is left over from testing, changed it locally but yet to push

2021-03-18 21:46 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +    entity.proxy_account_id,
Yep, as noted in the PR description still waiting on a new version of the js-sdk to expose that

2021-03-18 21:47 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.ed25519_public_key_hex !== ed25519Hex) {
This was an optimization. You raise a good point, will compare the raw bytes

2021-03-18 21:48 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    updateEntity.auto_renew_period = networkEntity.autoRenewPeriod.seconds.toString();
Will fix. I think the `dbEntity.auto_renew_period` was coming out as a string somehow, will circle back

2021-03-18 21:53 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  protoBuffer = proto.Key.encode(protoKey, protoBuffer).finish();
Didn't realize that was exposed. I can use that and scrap all the extra code :)

2021-03-18 22:40 UTC, ijungmann requested changes
Only grammar notes so far, most of these are suggestions (except the typos).

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +The Mirror Node Entity Info Updater provides the ability to verify if a list of entities present in the mirror db are correct and update them if they don't match the up to date network vlaues.
```suggestion
The Mirror Node Entity Info Updater provides the ability to verify if a list of entities present in the mirror db are correct and update them if they don't match the up-to-date network values.
```

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +2. For each entity it pulls entity info from the mirror db (using a pg connection) and the network (using the js-sdk)
```suggestion
2. Pulls entity info for each entity from the mirror db (using a pg connection) and the network (using the js-sdk)
```

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +3. For each entity it compares multiple value from the db entity to verify if they match the network values.
```suggestion
3. Compares each entity's db values to its network values to verify if they are equal.
```

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +    If there's a mismatch a new entity object based on teh db copy but with values updated from network is returned.
```suggestion
    If there's a mismatch, a new entity object based on the db copy but with values updated from the network is returned.
```

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +    If no mismatch the entity is skipped.
```suggestion
    If there is no mismatch, the entity is skipped.
```

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +4. For each entity in the list of entities to update the tool update the db with the new values.
```suggestion
4. Updates each entity returned in step 3 in the db.
```

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +## Run Check-State-Proof CLI
Copy paste error?

2021-03-18 22:40 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/README.md
> +The tool can be run against any DB host and database as long as it's reachable. To achieve this configure the
```suggestion
The tool can be run against any DB host and database as long as it's reachable. To achieve this configure the following
```

2021-03-18 22:48 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (!networkEntity.key || networkEntity.key._keys === undefined) {
You're likely referring to `networkEntity.key`. It is possible for `networkEntity.key._keys` to be undefined. This check is likely no longer needed with my newer changes on the protobuf side.

2021-03-18 23:02 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    updateEntity.auto_renew_period = networkEntity.autoRenewPeriod.seconds.toString();
isn't it because javascript Number can't handle the precision so have to use either js long package or a string?

2021-03-18 23:36 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  const ed25519Hex = key._keys.toString().split(',')[0];
Will update

2021-03-18 23:37 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +From command line run
Will add

2021-03-18 23:44 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    updateEntity.auto_renew_period = networkEntity.autoRenewPeriod.seconds.toString();
Yeah verified `dbEntity.auto_renew_period` comes out of the pg query as a string.
It's either I do it this way or convert it to an int to compare to `networkEntity.autoRenewPeriod.seconds`.
Either ways one of them needs a data type change

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +The tool can be run against any DB host and database as long as it's reachable. To achieve this configure the
Update

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +## Run Check-State-Proof CLI
Haha yeah, fixed

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +4. For each entity in the list of entities to update the tool update the db with the new values.
Updated

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +    If no mismatch the entity is skipped.
Updated

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +    If there's a mismatch a new entity object based on teh db copy but with values updated from network is returned.
Updated

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +3. For each entity it compares multiple value from the db entity to verify if they match the network values.
Updated

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +2. For each entity it pulls entity info from the mirror db (using a pg connection) and the network (using the js-sdk)
Fixed

2021-03-19 00:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +The Mirror Node Entity Info Updater provides the ability to verify if a list of entities present in the mirror db are correct and update them if they don't match the up to date network vlaues.
Fixed

2021-03-19 00:13 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.ed25519_public_key_hex !== ed25519Hex) {
Fixed

2021-03-19 00:13 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (!networkEntity.key || networkEntity.key._keys === undefined) {
Updated

2021-03-19 00:13 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/config/application.yml
> +        entitiesTableName: t_entities_bkup
Fixed

2021-03-19 00:14 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/index.js
> +  if (config.dryRun === false) {
Moved

2021-03-19 00:14 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  const ed25519Hex = key._keys.toString().split(',')[0];
Updated

2021-03-19 00:14 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +From command line run
Updated

2021-03-19 00:16 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +      `update t_entities_bkup
Ignore, will fix 
```suggestion
      `update t_entities
```

2021-03-19 00:16 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +       from t_entities_bkup
Ignore will fix
```suggestion
       from t_entities
```

2021-03-19 04:12 UTC, ijungmann requested changes
Will look at the update from my first review, a few more small things I noticed.

2021-03-19 04:12 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> + * Retrieve list of objects to update mirror db with. List represent correct information for out of date entities
```suggestion
 * Retrieve list of objects to update mirror db with. List represents correct information for out-of-date entities
```

2021-03-19 04:12 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  // ensure 1st column is entity num of expected format
nit
```suggestion
  // ensure first column is entity num of expected format
```

2021-03-19 04:12 UTC, ijungmann commented on hedera-mirror-rest/entity-info-updater/utils.js
> +    throw Error("CSV must have a header column with 1st column being 'entity'");
nit
```suggestion
    throw Error("CSV must have a header column with first column being 'entity'");
```

2021-03-19 15:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  protoBuffer = proto.Key.encode(protoKey, protoBuffer).finish();
sdk isn't and doesn't have plans to expose that logic, so we'll have to leave it as is.

2021-03-19 16:33 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +  // logger.info(`Retrieve entity info ${JSON.stringify(entityFromDb.rows[0])} for ${id}`);
I removed this in a recent push.

2021-03-19 16:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +    throw Error("CSV must have a header column with 1st column being 'entity'");
Updated

2021-03-19 16:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  // ensure 1st column is entity num of expected format
Updated

2021-03-19 16:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> + * Retrieve list of objects to update mirror db with. List represent correct information for out of date entities
Updated

2021-03-19 16:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> + * Create merge entity object that takes the based db entity and updates it with more recent network retrieved values
Updated

2021-03-19 16:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> + * @param id
Updated

2021-03-19 19:28 UTC, xin-hedera requested changes

2021-03-19 19:28 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const secNsToNs = (secNs, ns) => {
```suggestion
const secNsToNs = (sec, ns) => {
```

a better name can be `timestampToNs` indicates it's from SDK `Timestamp` to ns

2021-03-19 19:28 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/utils.js
> +    .toString();
this may produce the scientific notation

2021-03-19 20:32 UTC, steven-sheehy requested changes

2021-03-19 20:32 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  const ed25519Hex = ed25519HexParts.length === 1 ? ed25519HexParts[0] : null;
This is brittle to rely upon string splitting. Would suggest using the KeyList structure:
```javascript
let ed25519Hex = null;
if (key._keys.length === 1) {
  ed25519Hex = key._keys[0].toString();
}
```

2021-03-19 20:32 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.fk_entity_type_id !== 1) {
This should be relaxed to support contracts as well. The csv file only contains accounts and contracts, so if this is not the case might want to error and stop.

2021-03-19 20:32 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (!utils.isEd25519PublicHexMatch(dbEntity.ed25519_public_key_hex, ed25519Hex)) {
This is unnecessary and differs from how we handle this field in Java. As a result, it may cause unknown issues. `ed25519_public_key_hex` is constructed from a raw key so we only need to check the key bytes and if it differs update both.

2021-03-19 20:32 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/utils.js
> +    .toString();
Perhaps instead of using strings we should use BigInt to safely hold large values?

2021-03-19 20:32 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const longMinValue = -9223372036854775808;
This is silently truncating these numbers to the max Number. You need to use BigInt by adding `n`

2021-03-19 22:12 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/config.js
> +    logger.info(err);
Good point, will throw

2021-03-19 22:13 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.fk_entity_type_id !== 1) {
Can relax, thought it was accounts only. Will just do a < 3 check

2021-03-19 22:15 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const longMinValue = -9223372036854775808;
This was meant to match the java logic that handles the overflow. Will revisit

2021-03-20 00:24 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const longMinValue = -9223372036854775808;
Gotcha. Will use Bigint here also

2021-03-20 00:28 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  const ed25519Hex = ed25519HexParts.length === 1 ? ed25519HexParts[0] : null;
Good suggestion, will adopt

2021-03-20 00:37 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.fk_entity_type_id !== 1) {
This will require an extra log to get ContractInfo. Will update the `networkEntityService` also

2021-03-22 14:50 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +  const ed25519Hex = ed25519HexParts.length === 1 ? ed25519HexParts[0] : null;
Adopted

2021-03-22 14:51 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.fk_entity_type_id !== 1) {
Relaxed and added contract support

2021-03-22 14:51 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (!utils.isEd25519PublicHexMatch(dbEntity.ed25519_public_key_hex, ed25519Hex)) {
Fixed by reducing to key check only

2021-03-22 14:51 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const longMinValue = -9223372036854775808;
BigInt used

2021-03-22 14:59 UTC, ijungmann submitted a review, later dismissed
Still one minor grammar thing, but otherwise LGTM.

2021-03-22 16:43 UTC, xin-hedera requested changes

2021-03-22 16:43 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +        logger.debug(`Currently only account and contract entities are supported, skipping`);
looks like should `return null` if it's neither account nor contract

2021-03-22 16:43 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +const updateEntity = async (entity) => {
suggestion: should batch update instead of one a time, can be handled later

2021-03-22 17:22 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +const updateEntity = async (entity) => {
Yeah was working on this. Adding, it just means you keep running it till we don't hit any network errors

2021-03-22 17:22 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +        logger.debug(`Currently only account and contract entities are supported, skipping`);
Added

2021-03-22 17:50 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/README.md
> +The Mirror Node Entity Info Updater provides the ability to verify if a list of entities present in the mirror db are correct and update them if they don't match the up to date network vlaues.
Fixed

2021-03-22 17:51 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +const updateEntity = async (entity) => {
Why do we need to optimize the performance of this if it's not going to be committed and only takes 126s to run? Let's not make the code more complex by batching for little/no gain.

2021-03-22 19:49 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +const updateEntity = async (entity) => {
Ah actually realized this was around the db and not the network calls.
Yeah, agreed with Steven here since it's such a a basic flow and perf isn't a need I decided to make it simple

2021-03-22 20:00 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-03-22 20:12 UTC, steven-sheehy requested changes

2021-03-22 20:12 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +        networkEntity = await networkEntityService.getContractInfo(csvEntity.entity);
These two network entities differ in fields returned. Since you verified there's no contracts in csv, can just throw unsupported error or return null.

2021-03-22 20:12 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.memo !== networkEntity.accountMemo && dbEntity.memo !== null && networkEntity.accountMemo === '') {
`networkEntity.accountMemo === ''` This will only update our memo to empty string

2021-03-22 20:12 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +    entity.proxy_account_id,
You added memo to updater but forgot it here.

2021-03-22 20:57 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.memo !== networkEntity.accountMemo && dbEntity.memo !== null && networkEntity.accountMemo === '') {
Meant to be `networkEntity.accountMemo !== ''`. B
asically update if they are different and they actually have non null/empty values. Most memos are empty and without the check it'll update every entity that is null to empty.

2021-03-22 21:23 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +        networkEntity = await networkEntityService.getContractInfo(csvEntity.entity);
Will revert to what I previously had and just return null for now.

2021-03-22 21:24 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const isEd25519PublicHexMatch = (dbHex, networkHex) => {
Left over from public key comparison. Will remove

2021-03-22 21:25 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +    entity.proxy_account_id,
Will update

2021-03-22 22:14 UTC, ijungmann approved these changes

2021-03-22 23:22 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.memo !== networkEntity.accountMemo && dbEntity.memo !== null && networkEntity.accountMemo === '') {
Fixed. Also updated for where either memo is actually updating a non null value or the network is non empty

2021-03-22 23:22 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +        networkEntity = await networkEntityService.getContractInfo(csvEntity.entity);
Reverted to simpler case

2021-03-22 23:22 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const isEd25519PublicHexMatch = (dbHex, networkHex) => {
Removed

2021-03-23 00:57 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const isEd25519PublicHexMatch = (dbHex, networkHex) => {
Not removed

2021-03-23 03:55 UTC, steven-sheehy requested changes

2021-03-23 03:55 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (networkEntity.proxyAccountId !== null && dbEntity.proxy_account_id !== networkEntity.proxyAccountId) {
Why do we care if proxyAccountId is not null? If we have null in the db and main nodes have non null they would be the canonical source and we should update. If we're just worried about that scenario where db is 0 and network is null then we should ignore those explicitly.

2021-03-23 03:55 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.memo !== networkEntity.accountMemo && (dbEntity.memo !== null || networkEntity.accountMemo !== '')) {
This doesn't allow the scenario where someone had a memo but cleared it to empty string, which is now allowed with our update operations using StringValue.

2021-03-23 04:26 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const isEd25519PublicHexMatch = (dbHex, networkHex) => {
`git add`-ed for real this time.
Should be removed now

2021-03-23 15:58 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.exp_time_ns !== null && BigInt(dbEntity.exp_time_ns) !== ns) {
Fixed

2021-03-23 15:58 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (dbEntity.memo !== networkEntity.accountMemo && (dbEntity.memo !== null || networkEntity.accountMemo !== '')) {
Fixed

2021-03-23 15:59 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (networkEntity.proxyAccountId !== null && dbEntity.proxy_account_id !== networkEntity.proxyAccountId) {
Fixed. With allowance for #1740 to do it's job

2021-03-23 16:14 UTC, steven-sheehy approved these changes
LGTM

2021-03-23 16:14 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  const dbMemo = dbEntity.memo === null ? '' : dbEntity.memo;
Perhaps we should also update memo from null to '' in #1740 ?

2021-03-23 16:16 UTC, steven-sheehy requested changes
Approved, but requesting changes so it doesn't accidentally get merged 👍🏻

2021-03-23 17:07 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  const dbMemo = dbEntity.memo === null ? '' : dbEntity.memo;
Yeah we could do that. Looks like there's quite a mixture of NULL and `` in the db, will update the ticket

2021-04-05 16:50 UTC, Nana-EC commented
Closing PR. As noted we didn't intend to check in but rather preserve the branch for future use.
Verified with a couple of runs, only caveat is when running point to a single node instead of using network name when configuring js sdk

2021-04-05 16:50 UTC, closed without merging

2021-04-05 17:01 UTC, steven-sheehy commented
This will need to be updated with the t_entities renaming