Helm v3
hashgraph/hedera-mirror-node pull request #1752
Opened 2021-03-24 17:23 UTC by Nana-EC

**Detailed description**:
Update chart config and marketplace to Helm 3

- Update `Chart.yaml` files to `apiVersion: v2`
- Remove `requirements` files and move dependencies to `Chart.yaml`
- Update multimode pom replace logic to handle recommended quotation of v3 `appVersion` label

**Which issue(s) this PR fixes**:
Fixes #1502 

**Special notes for your reviewer**:
Next step to update marketplace

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-24 20:02 UTC, xin-hedera requested changes

2021-03-24 20:02 UTC, xin-hedera commented on charts/hedera-mirror/Chart.lock
> +generated: "2021-03-24T11:55:13.398028-05:00"
missing `Chart.lock` for other charts

2021-03-24 20:11 UTC, xin-hedera commented on charts/hedera-mirror-common/Chart.yaml
> +appVersion: "0.30.0-rc1"
Just saw from helm v3.5.0, `helm create` wraps the default `appVersion` field in quotes.

2021-03-24 20:27 UTC, Nana-EC commented on charts/hedera-mirror-common/Chart.yaml
> +appVersion: "0.30.0-rc1"
So it's not necessary but recommended in v3, apparently "Leaving it unquoted can lead to parsing issues in some cases." - See https://helm.sh/docs/topics/charts/#the-appversion-field

2021-03-24 20:28 UTC, Nana-EC commented on charts/hedera-mirror/Chart.yaml
> +  - dtl
Will update

2021-03-24 20:31 UTC, Nana-EC commented on charts/hedera-mirror/Chart.lock
> +generated: "2021-03-24T11:55:13.398028-05:00"
Thanks will add

2021-03-24 20:32 UTC, Nana-EC commented on charts/hedera-mirror/Chart.yaml
> +  - dtl
Actually all of the tags seem to be lowercase by design. Unless I'm incorrect @steven-sheehy

2021-03-24 20:34 UTC, xin-hedera commented on charts/hedera-mirror/Chart.yaml
> +  - dtl
in that case, it should be `dlt`, right?

2021-03-24 20:49 UTC, Nana-EC commented on charts/hedera-mirror/Chart.lock
> +generated: "2021-03-24T11:55:13.398028-05:00"
Added

2021-03-24 20:57 UTC, Nana-EC commented on charts/hedera-mirror/Chart.yaml
> +  - dtl
Haha yes you're right. Missed that

2021-03-24 21:01 UTC, steven-sheehy approved these changes
LGTM

2021-03-24 21:03 UTC, Nana-EC commented on charts/hedera-mirror/Chart.yaml
> +  - dtl
Fixed

2021-03-24 21:50 UTC, steven-sheehy approved these changes

2021-03-24 22:13 UTC, xin-hedera approved these changes
LGTM

2021-03-25 16:00 UTC, ijungmann approved these changes

2021-03-25 17:10 UTC, merged