Add postInit to timescaledb chart
hashgraph/hedera-mirror-node pull request #1764
Opened 2021-03-25 00:40 UTC by ijungmann

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1439 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-25 00:46 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +            ssl: 'off'
Add comment for this: disables all ssl connections (lets us not have to provide Patroni certificate)

2021-03-25 00:47 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +      - hostnossl all,replication all                all                md5
Add comment for this: Override default pg_hba in chart to allow non-ssl connections and remove ssl connections.

2021-03-25 00:47 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +        name: timescaledb-init-job
I've been trying to make something work with `helplers.tpl` or something to make this dynamic, but so far no go.

2021-03-25 00:48 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +  name: timescaledb-init-job
See comment on `values.yaml`, trying to make this dynamic but no luck so far.

2021-03-25 00:50 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    echo "local   {{ $dbName }}     {{ $dbOwner }}               trust" >> /var/lib/postgresql/data/pg_hba.conf
During postInit, the pg_hba.conf is very locked down, and upon exiting postInit it is replaced with a less strict version.  Without this line (and `select pg_reload_conf();` below), we cannot log in as the dbOwner in the next step.

2021-03-25 00:50 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +  1_users_v2.sh: |-
These appear to be executed alphabetically, so I have to have something at the front to make sure they execute in order.

2021-03-25 00:52 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3" --set ON_ERROR_STOP=1 <<__SQL__
Tried doing something similar to the old job where some of this was replaced by a variable, wasn't able to get it to work though.

2021-03-25 00:55 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3" --set ON_ERROR_STOP=1 <<__SQL__
Password is not needed because the pg_hba.conf is set to trust (only during postInit)
Host is using the Unix socket (`/var/run/postgresql` is the default in the chart)
sslmode isn't needed because we are turning off ssl in the config (though it can be added back if need be, just redundant)

2021-03-25 00:56 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    CREATE user {{ $dbOwner }} with login password '{{ $dbOwnerPassword }}';
Do a sweep to undo the all-caps in the SQL.

2021-03-25 00:57 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-certificate.yaml
> +  {{- end -}}
I tried various things to see if these could be entirely removed since we have ssl turned off, but so far I haven't found any config that would force the chart not to check for them and error out.

2021-03-25 00:58 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-credential.yaml
> +  PATRONI_admin_PASSWORD: "base_64_encoded_password"
Maybe just "mirror_node_pass" as the defaults and leave a comment saying they should be base64 encoded.

2021-03-25 20:24 UTC, steven-sheehy requested changes
haven't reviewied postinit script yet

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-credential.yaml
> +  PATRONI_admin_PASSWORD: "bWlycm9yX25vZGVfcGFzcwo="
These don't [seem](https://github.com/timescale/timescaledb-kubernetes/blob/88d1bb40521c93feed3b17785d7d1d5c1f56669e/charts/timescaledb-single/generate_kustomization.sh#L46) to be base64 as you commented. The entire secret itself will be base64 when applied since you're using `stringData`.

```suggestion
  {{- $password := .Values.importer.config.hedera.mirror.importer.db.password | quote }}
  PATRONI_SUPERUSER_PASSWORD: {{ $password }}
  PATRONI_REPLICATION_PASSWORD: {{ $password }}
  PATRONI_admin_PASSWORD: {{ $password }}
```

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Change here and everywhere else to non-HA version since we're no longer using HA chart: `timescale/timescaledb:2.1.0-pg13`

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>    persistentVolume:
It should be `persistentVolumes` and the fields [within](https://github.com/timescale/timescaledb-kubernetes/blob/88d1bb40521c93feed3b17785d7d1d5c1f56669e/charts/timescaledb-single/values.yaml#L299) it have changed. Please review all volumes and make sure they are the appropriate size.

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +      cpu: 250m
These defaults are too low. We should consider increasing to 1/1Gi and 4/16Gi

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>    postgresql:
This config no longer seems to apply here

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +      - local     all             postgres                              peer # allow local connections
Two spaces before comments to pass linting

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>    enabled: false
We should set podManagementPolicy=Parallel as [recommended](https://github.com/timescale/timescaledb-kubernetes/blob/88d1bb40521c93feed3b17785d7d1d5c1f56669e/charts/timescaledb-single/values.yaml#L485).

Please review all other values in values.yaml to see if we should tweak others.

2021-03-25 20:24 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +        name: timescaledb-init-job
The upstream chart would need to be modified to template the volume name.

2021-03-26 04:25 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-certificate.yaml
> +  labels:
Fixed

2021-03-26 05:37 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
I ran some tests with that chart just now and I don't think it's going to work for us, the non-HA version doesn't come bundled with Patroni, which is [how the postInit script runs](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml#L145).  Right now with working config and only that change the container doesn't even start up right now.  The alternative is I can set the replicaCount to 1.

2021-03-26 18:50 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-credential.yaml
> +  PATRONI_admin_PASSWORD: "bWlycm9yX25vZGVfcGFzcwo="
Yeah, I misunderstood their admin guide to mean what was going into the secret instead of what was coming out.  Added this change.

2021-03-26 18:50 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +      - local     all             postgres                              peer # allow local connections
Fixed here.

2021-03-26 21:10 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Sure, should bump to the latest then: `timescaledev/timescaledb-ha:pg12.6-ts2.1.0-p1`.

2021-03-29 17:43 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +      cpu: 250m
Agreed, that tracks with what I see in mainnet.  Updated those.

2021-03-29 17:46 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>    persistentVolume:
Updated `persistentVolumes` and the size field to match the changes.  500Gi lines up with what we have for the postgres default.  I'll look at the other fields, some of the now-defunct `postgresql` section will move into here it looks like.

2021-03-29 17:46 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Done, and set the replicaCount to 1

2021-03-29 17:47 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>    enabled: false
Set that, will look for others.

2021-03-29 17:53 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +  initialDelaySeconds: 240
Remove this, was testing

2021-03-29 17:55 UTC, ijungmann commented on charts/hedera-mirror/templates/networkpolicy.yaml
> +      app.kubernetes.io/component: {{ printf "%s" .Release.Name }}
Remove.

2021-03-29 22:13 UTC, steven-sheehy requested changes

2021-03-29 22:13 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql dbname={{ .Values.importer.config.hedera.mirror.importer.db.name }} user={{ .Values.importer.config.hedera.mirror.importer.db.owner }} connect_tim
```suggestion
    psql --echo-queries -d "host=/var/run/postgresql dbname={{ $dbName }} user={{ $dbOwner }} connect_timeout=3" --set ON_ERROR_STOP=1 <<__SQL__
```

2021-03-29 22:13 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3 dbname={{ .Values.importer.config.hedera.mirror.importer.db.name }}" --set ON_ERROR_STOP=1 <<__SQL__
```suggestion
    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3 dbname={{ $dbName }}" --set ON_ERROR_STOP=1 <<__SQL__
```

2021-03-29 22:23 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>    postgresql:
Removed, moved the parameters into the bootstrap section.  Kept the values the same.

2021-03-29 22:25 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>        min_wal_size: 2GB  # 80% of the WAL Volume Size
Just pushed a change to move it to the Patroni bootstrap.  I agree on the rest, will make those changes shortly.

2021-03-29 22:25 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +  resources:
Done.

2021-03-29 22:28 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +  resources:
I also disabled `timescaledbTune`, don't know that we want something auto-adjusting settings.

2021-03-29 22:28 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +    enabled: false
Why disabled? Doesn't it help auto-tune postgres for timescale?

2021-03-29 22:31 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Or I guess replicaCount should be 1 here but 2 in values-prod.yaml

2021-03-29 22:31 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +    enabled: false
Yeah, I wasn't sure if we wanted something automatically adjusting settings.  I can put it back, was going back and forth on that.

2021-03-29 22:33 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>        - postgres
Or we should do all the above but only enable it in values-prod.yaml

2021-03-29 22:40 UTC, ijungmann commented on charts/hedera-mirror/values-timescaledb.yaml
> +    host: RELEASE-NAME
I think I have a fix for this, testing.

2021-03-29 22:44 UTC, ijungmann commented on charts/hedera-mirror/values-timescaledb.yaml
> +    host: RELEASE-NAME
The chart defaults to the clusterName being just the release name unfortunately.  The other option here is to override the clusterName with something static (will also affect the names of the secrets).

2021-03-29 22:46 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-credential.yaml
> +    PATRONI_SUPERUSER_PASSWORD: {{ $password }}
Fixed.

2021-03-29 23:39 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +  1_users_v2.sh: |-
Yeah, that makes sense.  Merged them all together under `init.sh`

2021-03-29 23:39 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql dbname={{ .Values.importer.config.hedera.mirror.importer.db.name }} user={{ .Values.importer.config.hedera.mirror.importer.db.owner }} connect_tim
Fixed.

2021-03-29 23:40 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3 dbname={{ .Values.importer.config.hedera.mirror.importer.db.name }}" --set ON_ERROR_STOP=1 <<__SQL__
Fixed.

2021-03-30 00:46 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>        min_wal_size: 2GB  # 80% of the WAL Volume Size
Made all the mentioned resource changes.  I also had to set `timescaledb.max_background_workers` and `max_worker_processes` in that section, as the compression continuously failed with the defaults.

2021-03-30 00:46 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +    enabled: false
Removed this, default is true.

2021-03-30 00:46 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +    enabled: false
In fact, I think this sets wal size, shared buffers, etc. If we can confirm that, we can avoid manually setting those.

2021-03-30 00:48 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +            timescaledb.max_background_workers: 20
These two are specifically because the compression section in the flyway migrations constantly failed, the defaults were too low.  I tested this with many different values, the lowest I got was 18 background workers, figured a little breathing room would be good in case of future tables.

2021-03-30 00:51 UTC, xin-hedera requested changes

2021-03-30 00:51 UTC, xin-hedera commented on charts/hedera-mirror/templates/secret-timescaledb-certificate.yaml
> +  {{- end -}}
indentation:
```suggestion
{{- end -}}
```

2021-03-30 00:51 UTC, xin-hedera commented on charts/hedera-mirror/Chart.yaml
>      version: ^0.8.0
```suggestion
    version: ^0.8.2
```

2021-03-30 00:51 UTC, xin-hedera commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    -- add row to pg_hba.conf so that dbOwner can access table
will `--` cause shell to report error?

2021-03-30 00:58 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Done.

2021-03-30 01:02 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Added `replicaCount: 2` in `values-prod.yaml`

2021-03-30 01:15 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Bumped to `pg12.6-ts2.1.0-p1` in every location.

2021-03-30 01:17 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>        - postgres
Set the image pull to IfNotPresent and bumped the image to latest (`pg12.6-ts2.1.0-p1`) everywhere.
For the prometheus, you're saying only enable it in prod, right?

2021-03-30 01:18 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +    enabled: false
I'll look into doing some checks on if/what it's setting and if those are reasonable.

2021-03-30 01:18 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-certificate.yaml
> +  {{- end -}}
Fixed.

2021-03-30 01:18 UTC, ijungmann commented on charts/hedera-mirror/Chart.yaml
>      version: ^0.8.0
Fixed.

2021-03-30 01:29 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>        - postgres
Enabled prometheus in prod.

2021-03-30 01:29 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    -- add row to pg_hba.conf so that dbOwner can access table
Good catch, was too used to the SQL blocks and the error was very short.  Fixed to a proper comment.

2021-03-30 02:32 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +    enabled: false
Running on my local minikube setup, this appears to be what it set those values to, based on psql SHOW ALL:
`max_wal_size: 1216MB`
`shared_buffers: 256MB`
`work_mem: 6553kB`

So `max_wal_size` is pretty close, the other two are significantly smaller.

2021-03-30 03:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/resources/config/bootstrap.yml
> +    # set to timescaledev/timescaledb-ha:pg12.6-ts2.1.0-p1 (same as chart) for v2 db schema.
I think this comment should be removed now that we have a bootstrap-v2.yml. That way we don't have to maintain the version in the comment in the future.

2021-03-30 03:30 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescaledev/timescaledb-ha:pg12.6-ts2.1.0-p1 (same as chart) for v2 db schema.
I think this comment should be removed now that we have a bootstrap-v2.yml. That way we don't have to maintain the version in the comment in the future.

2021-03-30 03:30 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
>        - postgres
The comments above were purely about prometheus. So you need to set `timescaledb.prometheus.image.pullPolicy/tag` in `values.yaml`. Yes, only enable in prod though.

2021-03-30 04:49 UTC, ijungmann commented on hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
> +    # set to timescaledev/timescaledb-ha:pg12.6-ts2.1.0-p1 (same as chart) for v2 db schema.
Removed.

2021-03-30 04:49 UTC, ijungmann commented on hedera-mirror-importer/src/test/resources/config/bootstrap.yml
> +    # set to timescaledev/timescaledb-ha:pg12.6-ts2.1.0-p1 (same as chart) for v2 db schema.
Removed.

2021-03-30 04:50 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>        - postgres
Got it.  Added the pull policy and set it to pull the latest, `0.9.0-debian-10-r23`.  Also changed the repository as it appears that has moved.

2021-03-30 15:53 UTC, Nana-EC requested changes
Looking good. Nit and a verification.
Also, you're missing a description of the changes

2021-03-30 15:53 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3" --set ON_ERROR_STOP=1 <<__SQL__
nit: add the part about it being only during postInit to the comment.
Also who removes the trust after postInit? Is it postgres/patroni or is it something we need to manually do later?

2021-03-30 17:32 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3" --set ON_ERROR_STOP=1 <<__SQL__
Added clarification that it's only during postInit.  It's manually handled, I believe by patroni, I did a lot of verification to make sure it was setting the pg_hba to what's in `values.yaml` afterwards.

2021-03-30 17:54 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +            max_wal_size: 1GB
Yeah, they're getting set.  The values.yaml for that chart is a little vague, the [values.schema.yaml](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.schema.yaml#L269) makes it a little clearer, you can pretty much pass any postgres parameter in.

2021-03-30 17:55 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +    enabled: false
Are you comfortable with those values or shall we stick with our own static values?  They seem a little small to me.

2021-03-30 17:58 UTC, ijungmann commented on charts/hedera-mirror/values-timescaledb.yaml
> +    host: RELEASE-NAME
Sure, I will open a ticket and note that.

2021-03-30 20:23 UTC, ijungmann commented
> Looking good. Nit and a verification.
> Also, you're missing a description of the changes

Added a description.

2021-03-30 21:58 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    psql --echo-queries -d "host=/var/run/postgresql user=postgres connect_timeout=3" --set ON_ERROR_STOP=1 <<__SQL__
Makes sense, removed.

2021-03-30 21:58 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
>      repository: timescaledev/timescaledb-ha
Sure, put it back.

2021-03-30 22:07 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +            max_wal_size: 1GB
Sounds good

2021-03-31 03:09 UTC, Nana-EC approved these changes
LGTM, pending Steven's potential locally tested suggestions

2021-03-31 16:40 UTC, steven-sheehy requested changes

2021-03-31 16:40 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +    #!/bin/bash
Was able to streamline this a bit. Fixed some unnecessary extension creates and reduced importer permission: https://gist.github.com/steven-sheehy/587b5bcd812200de01061fe106fc5bbc

2021-03-31 16:51 UTC, steven-sheehy requested changes

2021-03-31 16:51 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-credential.yaml
> +  name: {{ printf "%s-credentials" .Release.Name }}
```suggestion
  name: {{ printf "%s-timescaledb-credentials" .Release.Name }}
```

2021-03-31 16:51 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-certificate.yaml
> +  name: {{ printf "%s-certificate" .Release.Name }}
```suggestion
  name: {{ printf "%s-timescaledb-certificate" .Release.Name }}
```

2021-03-31 16:51 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-postInit.yaml
> +  name: timescaledb-init-job
Nevermind about the release name. Forgot about the templating issue. But we should rename the file.

2021-03-31 17:47 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-credential.yaml
> +  name: {{ printf "%s-credentials" .Release.Name }}
Unfortunately those credentials and certificate names are [also default values](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/_helpers.tpl#L106), making any changes would force us to specify them in values.yaml and make them static.

2021-03-31 17:58 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-timescaledb-init.yaml
> +    -- Add extensions
nit: I think having the newline between sections helps readability. Probably a copy paste error from my gist

2021-03-31 18:11 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-init.yaml
> +    -- Add extensions
Sure, added newlines.

2021-03-31 18:18 UTC, Nana-EC requested changes
On more item on oder of actions

2021-03-31 18:18 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-timescaledb-init.yaml
> +    -- Alter search path
nit: we should probably set the schema search path after we create it.
I'm presuming it's working now but probably better to avoid hard to find bugs because postgres missed something because the schema wasn't present on this command

2021-03-31 18:33 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-03-31 18:39 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-03-31 18:47 UTC, ijungmann commented on charts/hedera-mirror/templates/secret-timescaledb-init.yaml
> +    -- Alter search path
Sure, I moved that block back down to the end, just had to add one more connect line.

2021-03-31 19:04 UTC, steven-sheehy approved these changes

2021-03-31 19:26 UTC, xin-hedera approved these changes

2021-03-31 19:32 UTC, merged