Backport monitor multi scenario
hashgraph/hedera-mirror-node pull request #1778
Opened 2021-03-29 23:52 UTC by xin-hedera

**Detailed description**:

- Backport multi-scenario fix to release 0.28
- Retain transaction generator state when rebuilding

**Which issue(s) this PR fixes**:
Relates to #1777 

**Special notes for your reviewer**:
Will port the fix to master.

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-03-30 17:22 UTC, Nana-EC requested changes
Looks good, don't you need to bump the versions?

2021-03-30 17:31 UTC, steven-sheehy requested changes
In the future, would prefer that we do new change in master first then cherry-pick it unless it's an urgent hotfix. Mixing new changes (excluding bumps) with old changes makes it harder to review.

2021-03-30 17:31 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +    private long lastElapsed = 0;
These should be volatile or AtomicLongs since this is a shared class. Volatiles are safe when use only for assignment, but Sonar might complain when they are used.

2021-03-30 17:31 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +@Getter
We should avoid publicly exposing every field and only expose the minimal set of fields. I think it's just properties that needs the getter.

2021-03-30 17:46 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +@Getter
sure. will limit the getter to properties.

2021-03-30 17:59 UTC, xin-hedera commented
> Looks good, don't you need to bump the versions?

yes, will bump it

2021-03-31 15:47 UTC, steven-sheehy approved these changes
LGTM

2021-03-31 16:03 UTC, ijungmann approved these changes

2021-03-31 17:51 UTC, Nana-EC approved these changes
LGTM

2021-04-01 17:42 UTC, merged