Migrate and update t_entities to entity table
hashgraph/hedera-mirror-node pull request #1779
Opened 2021-03-30 18:35 UTC by Nana-EC

**Detailed description**:
Some entity objects in mirror node db have some issues with their default empty values.
Additionally, to improve convention we want to drop the `t_` table prefix and standardize some column names

- Add a migration to rename `t_entties` table to `entity`
- Update indexes on new `entity` table accordingly
- Add `created_timestamp`, `modified_timestamp` to `entity` table 
- Rename `entity_num` to `num`, `entity_realm` to `realm`, `entity_shard` to `shard`, `fk_entity_type_id` to `type`, `exp_time_ns` to `expiration_time`, `ed25519_public_key_hex` to `public_key`
- Update `proxy_account_id` to set to null as default.
- Update `auto_renew_account_id` to set null as default.
- Update `memo` default to '' and required
- Update `deleted` column to be made required
- Add migration logic to pick up the new timestamp values on the table
- Update docs, comments and classes to reference `entity` instead of `t_entities`

**Which issue(s) this PR fixes**:
Fixes #1740 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-31 18:36 UTC, steven-sheehy requested changes
Still need to review migration

2021-03-31 20:40 UTC, Nana-EC commented on README.md
> +In addition to the REST API which exposes the persisted network entities (accounts, balances, schedules, transactions, topics and
Yeah considered it. Had the same feedback for services. Will just remove

2021-03-31 20:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepository.java
>      @Cacheable(cacheNames = "entities", cacheManager = EXPIRE_AFTER_30M, key = "{#p0}")
Thought the cache name was just the plural of the entity but yeah if it's the table then I'll update

2021-03-31 20:53 UTC, Nana-EC commented on README.md
> +In addition to the REST API which exposes the persisted network entities (accounts, balances, schedules, transactions, topics and
Updated

2021-03-31 20:53 UTC, Nana-EC commented on docs/design/parser.md
> +Note that there are no function for `onEntity`. Updating `entity` table in batches is not possible right now since
Updated

2021-03-31 20:54 UTC, Nana-EC commented on docs/monitor.md
> +The monitor can automatically create account, token, and topic entity on application startup using a special
Updated

2021-03-31 20:54 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/Entity.java
> +@javax.persistence.Entity(name = "entity")
Removed

2021-03-31 20:54 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/cleanup.sql
> +TRUNCATE TABLE entity RESTART IDENTITY CASCADE;
Sorted

2021-03-31 20:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    private String publicKey;
Reordered

2021-03-31 20:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityId.java
> +        entity.setMemo("");
Removed

2021-03-31 20:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java
> +        if (entity.getMemo().equalsIgnoreCase("") && accountInfo.getMemo() != null) {
Duhh, Fixed

2021-03-31 20:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepository.java
>      @Cacheable(cacheNames = "entities", cacheManager = EXPIRE_AFTER_30M, key = "{#p0}")
Updated

2021-03-31 21:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    public_key            character varying,
Actually meant public_key goes after proxy_account_id. But good catch on the table sort :D

2021-03-31 21:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
>  create unique index if not exists entities_unq
Updated

2021-03-31 21:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +TRUNCATE TABLE entity RESTART IDENTITY CASCADE;
Sorted

2021-03-31 21:25 UTC, ijungmann reviewed
Still looking through, so far looks good, just one thing.

2021-03-31 21:25 UTC, ijungmann commented on docs/design/parser.md
> +Note that there are is function for `onEntity`. Updating the `entity` table in batches is not possible right now since
This first sentence needs to be revised.

2021-04-01 00:36 UTC, Nana-EC commented on docs/design/parser.md
> +Note that there are is function for `onEntity`. Updating the `entity` table in batches is not possible right now since
Lol right, was trying not to change the original writers phrase to much, need to remove that `are` and put that `no` back in
```suggestion
Note that there is no function for `onEntity`. Updating the `entity` table in batches is not possible right now since
```

2021-04-01 00:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    public_key            character varying,
Right. Will update

2021-04-01 00:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    public_key            character varying,
Updated

2021-04-01 00:42 UTC, Nana-EC commented on docs/design/parser.md
> +Note that there are is function for `onEntity`. Updating the `entity` table in batches is not possible right now since
Fixed

2021-04-01 01:47 UTC, xin-hedera requested changes

2021-04-01 01:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteTransactionHandler.java
> +import com.hedera.mirror.importer.domain.Entity;
nit: optimize imports

2021-04-01 01:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepository.java
>      void insertEntityId(long id, long shard, long realm, long num, long type);
`type` should be `int`

2021-04-01 01:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
don't think the index will help

1. building the index needs a full scan of the table
2. later on when the index is used, actual rows are still visited since there are filters on `result` and `entity_id`, and `consensus_ns` is visited

also need to delete this temporary index.

2021-04-01 01:47 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +  // need to look  for the given account.id in both account_balance and e table and combine with an 'or'
```suggestion
  // need to look for the given account.id in both account_balance and entity table and combine with an 'or'
```

2021-04-01 02:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
```sql
with entity_update_map as (
  select entity_id, consensus_ns
  from transaction
  where result = 22 and entity_id is not null
  order by consensus_ns
)
update entity
set created_timestamp = coalesce(created_timestamp, entity_update_map.consensus_ns),
    modified_timestamp = entity_update_map.consensus_ns
from entity_update_map
where id = entity_update_map.entity_id;
```

this should work and does not need the extra index

2021-04-01 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
I agree. It's also safer since you're replaying all successful transactions in order.

2021-04-01 15:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
Good point, only need to worry about successful. Will adopt this.

On the index topic meant to bring this up as given we have transaction type filtering on the REST side it might be useful to have this index anyway.

2021-04-01 16:16 UTC, ijungmann commented on docs/design/parser.md
> +Note that there are is function for `onEntity`. Updating the `entity` table in batches is not possible right now since
Yeah, much better.

2021-04-01 16:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
I thought you meant the above suggestion as a replacement for both CTE's.
After testing I realized it works as a replacement of the 2nd CTE.
Even with it working I slightly prefer adding the type where clause to avoid unnecessary transactions consideration.

Again on the index, I actually would like to keep that index for The REST API optimization point.
I can move it to the end if preferred.

What say you guys?

2021-04-01 17:39 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +  // need to look  for the given account.id in both account_balance and e table and combine with an 'or'
Updated

2021-04-01 17:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
Updated update CTE and added a further test. 
I don't believe the table modifications are maintained so the coalesce doesn't work since `created_timestamp` always ends up being null. Hence having to maintain the `entity__creation_map` CTE
Let me know about the index

2021-04-01 17:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepository.java
>      void insertEntityId(long id, long shard, long realm, long num, long type);
Updated

2021-04-02 22:58 UTC, steven-sheehy approved these changes
LGTM

2021-04-03 04:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.36.2__entities_update.sql
> +create index if not exists transaction_type
Updated and added index.

2021-04-05 14:38 UTC, xin-hedera approved these changes
LGTM

2021-04-05 15:23 UTC, ijungmann submitted a review, later dismissed

2021-04-05 16:23 UTC, xin-hedera approved these changes

2021-04-05 17:43 UTC, steven-sheehy approved these changes

2021-04-05 17:55 UTC, ijungmann approved these changes

2021-04-05 17:59 UTC, merged