Fix release artifact & bump version to v0.30.0-rc2
hashgraph/hedera-mirror-node pull request #1785
Opened 2021-03-30 21:48 UTC by steven-sheehy

**Detailed description**:
- Fix release artifacts missing v prefix that devops scripts require
- Bump version to v0.30.0-rc2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-03-30 21:49 UTC, ijungmann submitted a review, later dismissed

2021-03-30 21:49 UTC, xin-hedera approved these changes

2021-03-30 22:07 UTC, steven-sheehy commented
Holding off on this until I can get a successful 0.31 deploy first

2021-03-30 22:30 UTC, Nana-EC requested changes
Add the new fixes for the jar files and the rosetta fix

2021-03-31 15:39 UTC, ijungmann approved these changes

2021-03-31 15:41 UTC, Nana-EC approved these changes
LGTM

2021-03-31 15:43 UTC, merged