Expose entity_id in transactions REST API
hashgraph/hedera-mirror-node pull request #1791
Opened 2021-03-31 16:35 UTC by Nana-EC

**Detailed description**:
Currently there's no way to know from an entity impacting transaction what the entity_id is e.g. a transaction that creates a crypto account doesn't say what the entityId is

- Add `entity_id` from transaction into select statement for transactions
- Update spec test files with new column
- Update mock pool file to support new column

**Which issue(s) this PR fixes**:
Fixes #1639 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-31 21:48 UTC, steven-sheehy requested changes

2021-03-31 21:48 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
> +        "entity_id": null,
Token wipe transaction has an `entity_id` populated with a token ID. Instead of returning null for this and others like it, we should update the  database setup to populate an `entity_id` for transactions that return a non-null `TransactionHandler::getEntity`. This will make the results more accurately represent a production environment. It would also cause less confusion when people look at the test in isolation in the future and wonder why these are null.

2021-03-31 23:29 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
> +        "entity_id": null,
I see what you're going for which is why I added support to the `addTranaction()` in `integrationDomainOps.js` so transactions would specific the entity_id just like a record would in production.
The challenge with auto populating a non-null value isn the setup vs letting the test logic specify it is that that the transaction itself is the source of the new or existing entity_id that the transaction works on.
You can't be sure what value it is and therefore have to specify it in the transaction input.

2021-04-01 00:20 UTC, xin-hedera requested changes

2021-04-01 00:20 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const entityAccount = EntityId.fromString(transaction.entity_id, 'entity_id', true);
the entity ID of a transaction can be of different type depending on the transaction type, so better name it `entityId`

2021-04-01 00:34 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
> +        "entity_id": null,
Yeah, I'm doing this for some tests, you can see the changes in this PR.
Might take a while to go through all the specs to do it everywhere but the capability is added as part of this PR.

I'll work on that

2021-04-01 00:35 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const entityAccount = EntityId.fromString(transaction.entity_id, 'entity_id', true);
good point, will update

2021-04-01 16:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
> +        "entity_id": null,
Updated

2021-04-01 16:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const entityAccount = EntityId.fromString(transaction.entity_id, 'entity_id', true);
Updated

2021-04-01 17:10 UTC, steven-sheehy approved these changes
LGTM

2021-04-01 17:40 UTC, ijungmann approved these changes

2021-04-01 22:29 UTC, xin-hedera approved these changes

2021-04-03 04:12 UTC, merged