Improve monitor performance
hashgraph/hedera-mirror-node pull request #1816
Opened 2021-04-05 21:33 UTC by xin-hedera

**Detailed description**:

- Use SDK v2 asynchronous transaction exeuction
- Switch to `grpc-okhttp`
- Add transaction timeout to scenario properties
- Randomly pick one node for each transaction to workaround SDK issues

**Which issue(s) this PR fixes**:
Fixes #1814 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-04-06 16:21 UTC, Nana-EC approved these changes
Looks good, minor suggestions

2021-04-06 16:21 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                .thenCompose(transactionResponse -> {
nit: same here. Might be nice to move these larger lambdas functions to methods.

2021-04-06 16:55 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.publish.scenarios[].timeout`         | 60s        | How long to wait for the transaction result
This seems a bit high for the default value considering the monitor is mostly used as a performance testing tool.

2021-04-06 16:58 UTC, ijungmann approved these changes
Looks good, just the one nit that could be looked at.

2021-04-07 16:34 UTC, xin-hedera commented
`ExpressionConverterImpl` fails to create the corresponding entities, it looks like the completable future resolving is blocked due to the way the chained completable futures are run. Need to fix it.

2021-04-07 17:46 UTC, xin-hedera commented on docs/configuration.md
> +`hedera.mirror.monitor.publish.scenarios[].timeout`         | 60s        | How long to wait for the transaction result
reduced it to 10s

2021-04-07 17:46 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +                    .thenApply(response -> {
updated

2021-04-07 17:46 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                .thenCompose(transactionResponse -> {
updated

2021-04-07 19:57 UTC, steven-sheehy requested changes

2021-04-07 19:57 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        List<NodeProperties> nodes = new ArrayList<>(new HashSet<>(monitorProperties.getNodes()));
This seems inefficient to convert from a `Set` to a `HashSet`. I also don't think it needs to convert from a `HashSet` to a `List` when we can just adjust the methods to accept/return `Collection` instead.

2021-04-07 20:52 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +        if (publishProperties.getClients() == 1) {
makes sense. only concern is the performance difference since parallelizing then serializing involves more operations. but can image the impact should be negligible.

will remove the if / else.

2021-04-07 21:01 UTC, xin-hedera commented on docs/configuration.md
> +`hedera.mirror.monitor.publish.threads`                     | 5          | How many threads to use to resolve the asynchronous responses
sure, will add an example with explanation.

To reach 10k tps, we'll need around 4-5 threads for publisher mainly due to each thread can only handle that many private key signing. For the resolver threads, perhaps around 100, at most 200. I'll run a test to get the numbers.

2021-04-07 21:01 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        List<NodeProperties> nodes = new ArrayList<>(new HashSet<>(monitorProperties.getNodes()));
sure

2021-04-07 21:03 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    public CompletableFuture<PublishResponse> publish(PublishRequest request) {
agree and will switch to `Mono`

2021-04-07 23:10 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +                    .timeout(properties.getTimeout())
Spent some time moving `ScenarioProperties` to `PublishRequest` and I do feel it's better to keep it as is:

1. whether a `PublishRequest` needs record / receipt should be computed at its construction, so it makes sense to keep `shouldGenerate` in `ConfigurableTransactionGenerator`
2. in `ExpressionConverter`, `PublishRequest` is created without a real scenario, though a scenario name is still set, it's better than creating a whole `ScenarioProperties` object in order to create the request

2021-04-08 03:23 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +                    .timeout(properties.getTimeout())
> 1. whether a `PublishRequest` needs record / receipt should be computed at its construction

This is not strictly the case. Whether to generate a record/receipt varies for every transaction since it's based upon a random number. It's never a static value that can be computed once at startup. We also don't check its value in the publisher multiple times. Thus it consumes the exact same amount of cycles to generate it in the `ConfigurableTransactionGenerator` or elsewhere. 

2) Fair point. We can keep it as is for now and revisit when we add our 4th-6th duplicated property. 😄

2021-04-08 14:49 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +                    .timeout(properties.getTimeout())
> > 1. whether a `PublishRequest` needs record / receipt should be computed at its construction
> 
> This is not strictly the case. Whether to generate a record/receipt varies for every transaction since it's based upon a random number. It's never a static value that can be computed once at startup. We also don't check its value in the publisher multiple times. Thus it consumes the exact same amount of cycles to generate it in the `ConfigurableTransactionGenerator` or elsewhere.
> 
What I meant was when we create a `PublishRequest` it's also the time to determine whether this request needs record / receipt. So it's natural to have `shouldGenerate` in the transaction generator to compute and set the values.

2021-04-08 16:52 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +            PublishResponse publishResponse = transactionPublisher.publish(request).toFuture().join();
can't just do `Mono.block` as it violates spec:

`block()/blockFirst()/blockLast() are blocking, which is not supported in thread single-1`

2021-04-08 17:09 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
>          return publishMetrics.record(request, this::doPublish);
We could rework `PublishMetrics` so that instead of wrapping `TransactionPublisher`, `TransactionPublisher` invokes `PublishMetrics`:

```java
doPublish(request)
  .doOnSuccess(response -> publishMetrics.onSuccess(publishRequest, response))
  .doOnError(throwable -> publishMetrics.onError(publishRequest, throwable))
  .onErrorMap(PublishException::new)
```

We can avoid passing the startTime by using the timestamp in the request. It's accurate enough.

2021-04-08 17:23 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
>          R apply(T t) throws Exception;
sure

2021-04-08 17:28 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +        } catch (Exception ex) {
It was here to catch the `ConcurrentModificationException` exception due to concurrent list sorting in SDK, before I implemented the workaround.

If we don't catch such surprises here and wrap it into a `PublisherException`, the whole flux flow will stop. what do you think?

2021-04-08 17:37 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +        } catch (Exception ex) {
I would suggest to remove it. Shouldn't have two different approaches to error handling. You can accomplish the same thing by widening the `onErrorContinue` at the top level to all exceptions or chaining `.onErrorMap(PublishException::new)` in `TransactionPublisher::doPublish` (my preference).

2021-04-08 17:44 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +        } catch (Exception ex) {
this should do it, in `TransactionPublisher::doPublish`:

```Mono.fromFuture(() -> request.getTransaction().setNodeAccountIds(nodeAccountId).executeAsync(client))```

so exceptions thrown from `executeAsync` will be caught and passed down to `.onErrorMap`

2021-04-08 17:47 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        return timeout != null ? publishResponse.timeout(timeout) : publishResponse;
there shouldn't be much performance impact. the 10ktps hcs test was run with the default 10s timeout

2021-04-08 18:04 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +                .onErrorContinue(PublishException.class, (t, r) -> {})
`onErrorContinue()` and `doOnError()` are there before the changes and for different purposes imo:

1. `onErrorContinue` filters out `PublishException` so the flux flow won't stop
2. `doOnError` chains after `onErrorContinue` so in case there is an exception other than `PublishException` which causes the flux flow to stop, we get a chance to log it

2021-04-08 18:52 UTC, steven-sheehy approved these changes
LGTM

2021-04-08 22:19 UTC, ijungmann approved these changes

2021-04-08 22:25 UTC, Nana-EC approved these changes
Looks good, just 1 non-blocking note

2021-04-08 22:25 UTC, Nana-EC commented on docs/monitor.md
> +`hedera.mirror.monitor.publish.threads` properties will need to be increased. For example, to achieve 10K TPS we set the
Math isn't clear now.
Before 1000 connections gave 10,000 TPS, there seemed to be a 10x indication. 
Now, 4 clients and 40 threads on each gives 10,000 TPS. 
It's not clear how you might determine getting say 3kTPS, or 8kTPS with trial and error.

Maybe an improvement for a future PR, just a thought.

2021-04-08 22:34 UTC, steven-sheehy commented on docs/monitor.md
> +`hedera.mirror.monitor.publish.threads` properties will need to be increased. For example, to achieve 10K TPS we set the
I think you can just always leave it a 4/40 if you're doing performance testing. TPS property will give us the exact TPS expected. No need for math.

2021-04-08 23:21 UTC, xin-hedera commented on docs/monitor.md
> +`hedera.mirror.monitor.publish.threads` properties will need to be increased. For example, to achieve 10K TPS we set the
Each `clients` thread can publish transactions at a very high rate because now we use SDK client's `executeSync`, the deciding factor is how many private key signing a single core can handle.

The `resolver` threads are there to wait for the transaction response.

The numbers are based on testing. And in fact the 4/40 configuration does have some headroom. The reason is the CPU I ran the test on is @4GHz, supposed to be faster than most cloud VM offerings.

2021-04-08 23:25 UTC, merged