Autovacuum crypto_transfer and token_transfer
hashgraph/hedera-mirror-node pull request #1825
Opened 2021-04-07 14:49 UTC by xin-hedera

**Detailed description**:
Configure more frequent anti-wraparound autovacuum for `crypto_transfer` and `token_transfer` to keep the visibility map up-to-date so pg planner will choose index-only scan.

**Which issue(s) this PR fixes**:
Fixes #1780 

**Special notes for your reviewer**:
Reference doc: https://www.postgresql.org/docs/9.6/routine-vacuuming.html section 24.1.5

- `autovacuum_freeze_max_age` can't be set lower than 100,000, mainnet postgresql tx id grows at around 60,000/day
- setting `autovacuum_freeze_table_age` is needed otherwise postgresql will use the global parameter `vacuum_freeze_table_age` which is 150,000,000. then the autovacuum ends up not freezing any pages and running forever since the table age won't change
- `autovacuum_freeze_min_age = 0` is aggressive, freezes all rows at the time of acutovacuum scan
- `log_autovacuum_min_duration = 0` turns on logging of autovacuum of the table

Criteria for the tables to enable more frequent anti-wraparound autovacuum:

- insert-only
- there are sql queries on the table which can benefit from index-only scan

Concerns:

- anti-wraparound autovacuum scan will lock the table for DDL, so this will be a problem for ops doing upgrades

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-09 20:07 UTC, steven-sheehy reviewed
Looks good. Do we need to consider doing account_balance as well?

2021-04-09 20:48 UTC, xin-hedera commented
> Looks good. Do we need to consider doing account_balance as well?

Checked `account_balance` table and `token_balance` table, the queries on the two tables either just select the consensus_timestamp (look for the latest consensus_timestamp or the latest at certain time in the past) or select the full row.

The consensus_timestamp query will not benefit much from index only scan since we just look for one consensus_timestamp and at most pg just has to spend an extra trip to make sure the corresponding index's data in the page is not stale.

The other queries always select the balance and balance is not in any indexes, so they are not index-only scans.

So vacuuming these tables more frequently won't speed up our queries thus we shouldn't do it.

2021-04-10 01:27 UTC, Nana-EC reviewed
Looks good, nit suggestion based on your preference.
Also is transactions not a huge insert only table.
Would some queries such as account and time range benefit from a vacuum more often?

2021-04-10 01:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.5__autovacuum_insert_only_tables.sql
> +
nit: 
```sql
\set autovacuum_freeze_max_age '100000'
\set autovacuum_freeze_table_age '100000'
```

Or if there's value to configurability you can add it as property in the `application.yaml` under `spring.flyway.placeholders`

2021-04-10 04:06 UTC, steven-sheehy approved these changes

2021-04-12 14:27 UTC, steven-sheehy commented
We'll be bumping our TimescaleDB chart to use PostgreSQL 13 [soon](https://github.com/timescale/timescaledb-kubernetes/pull/283) and our timescale.com SaaS uses PostgreSQL 13. Can you update the schema v2 stuff to use the newer pg13 approach you mention?

2021-04-12 15:26 UTC, xin-hedera commented
> We'll be bumping our TimescaleDB chart to use PostgreSQL 13 [soon](https://github.com/timescale/timescaledb-kubernetes/pull/283) and our timescale.com SaaS uses PostgreSQL 13. Can you update the schema v2 stuff to use the newer pg13 approach you mention?

definitely. the pg13 new insert-only table autovacuum mechanism will be more efficient.

2021-04-12 16:57 UTC, ijungmann approved these changes

2021-04-14 21:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.5__autovacuum_insert_only_tables.sql
> +
changed both to repeatable migrations and added properties to spring.flyway.placeholders

2021-04-14 22:26 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-04-15 14:55 UTC, steven-sheehy requested changes

2021-04-15 14:55 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +      insertOnlyAutovacuumFreezeMaxAge: 100000
Does it work if we remove these placeholders in test config? Would prefer to not duplicate them if possible.

2021-04-15 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> +      insertOnlyAutovacuumFreezeMaxAge: 100000
Would prefer all variables start with `autovacuum` so we can group them. The name should match the underlying postgres property prefix but in camel case form. Also sorted would be nice.

2021-04-15 16:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> +      insertOnlyAutovacuumFreezeMaxAge: 100000
sure

2021-04-16 15:20 UTC, ijungmann submitted a review, later dismissed

2021-04-16 15:23 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +      insertOnlyAutovacuumFreezeMaxAge: 100000
That's fine, let's keep as is.

2021-04-16 18:26 UTC, steven-sheehy approved these changes
LGTM

2021-04-19 15:15 UTC, Nana-EC approved these changes
LGTM

2021-04-19 15:17 UTC, merged