Update traefik service type
hashgraph/hedera-mirror-node pull request #1844
Opened 2021-04-12 22:07 UTC by Nana-EC

**Detailed description**:
We have insecure ports 80 and 5600 and a secure port 443 that uses a self-signed certificate. 
We want to support wildcard certs with DNS over TLS, however Traefik does not support Let's Encrypt with the community edition when there's more than one replica.
As such, as part of our HA story we want to to consolidate the ports so that we can deprecate 5600 and only expose 443 (with 80 redirecting to 443). 

As part of a simplified HA strategy we will move the cert management to the cloud service level, in place of Traefik self-signed cert.
Additionally, we will employ a cloud service loadBalancer in place of Traefik load balancing.

- Update Traefik sac type to NodePort 
- Update import values template for address book as mountPath should be dir not file

**Which issue(s) this PR fixes**:
Fixes #702 

**Special notes for your reviewer**:
The cloud service employed will implement
- Load Balancing that utilize the Traefik ports exposed 
- Cert management for wildcard certs for multi domains

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-15 15:42 UTC, steven-sheehy requested changes

2021-04-15 15:42 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> -    - "--entrypoints.grpc.address=:5600"
We should also remove the below traefik config:
```yaml
  ports:
    grpc:
      port: 5600
      expose: true
```

2021-04-15 15:42 UTC, steven-sheehy commented on charts/hedera-mirror-common/values-prod.yaml
> +      expose: false
Not needed if you remove the port

2021-04-15 15:42 UTC, steven-sheehy commented on charts/hedera-mirror-common/values-prod.yaml
> +      nodePort: 32080
We shouldn't hardcode node ports. These are not guaranteed to be unused.

2021-04-15 16:12 UTC, Nana-EC commented on charts/hedera-mirror-common/values.yaml
> -    - "--entrypoints.grpc.address=:5600"
I had removed this initially but reverted to leave it as we decide how to deprecate the port.
However, this might be fine since other deployment won't use the shared common chart and have control over the port used by the grpc service

2021-04-15 16:13 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +      expose: false
As noted above wanted to stay flexible until we had ironed out the deprecation details.
I can remove it though since we're starting down this track

2021-04-15 16:16 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +      nodePort: 32080
OPS needed a predictable static port to forward to as they can change between deployments, and would then require updating the load balancer. Do you have suggestions on a different approach.
@beeradb

2021-04-15 22:53 UTC, Nana-EC commented on charts/hedera-mirror-common/values.yaml
> -    - "--entrypoints.grpc.address=:5600"
Removed

2021-04-15 22:53 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +      expose: false
Removed

2021-04-15 22:54 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +      nodePort: 32080
Removed in favor of ClusterIp approach

2021-04-16 15:44 UTC, ijungmann approved these changes
LGTM

2021-04-16 17:07 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +    type: ClusterIP
I'm potentially missing the following annotation. Once tested will add
```yaml
annotations:
      # default load balancer is GCP container-native load balancer. Modify for other cloud providers
      cloud.google.com/neg: '{"ingress": true}'
```

2021-04-23 02:38 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +    type: ClusterIP
Went with standalone option

2021-04-23 02:41 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +                "80":{"name": "common-mirror-traefik-neg"},
Weighing whether this should take its form from the release and namespace.
Initially I would have said yes, however the NEG sits above the mirror application and could be used to point to pods across applications.
In that case this should be left to be configured as desired by the operator

2021-04-23 17:14 UTC, steven-sheehy commented on charts/hedera-mirror-common/values-prod.yaml
> +                "80":{"name": "common-mirror-traefik-neg"},
Note that neg name will vary per cluster as well. For this reason, we should not commit it and leave it to be configured per cluster by the operator.

2021-04-23 17:19 UTC, steven-sheehy commented on charts/hedera-mirror-common/values-prod.yaml
> +    type: ClusterIP
In some environments that have multiple clusters associated with them, we'd use this approach. In others like pre-prod we might continue to use a regular loadbalancer for its ease of use.

2021-04-23 20:43 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +                "80":{"name": "common-mirror-traefik-neg"},
Yep that was my thinking, will remove and leave it with an `<insert_name_here>` like tag

2021-04-23 21:04 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +    type: ClusterIP
Right in which case just using the `values.yaml` should suffice right?

2021-04-23 21:04 UTC, steven-sheehy commented on charts/hedera-mirror-common/values-prod.yaml
> +           }'
This needs to be completely removed. You can't put fake data in here as it will have side effects when actually deployed. If you want, you can add a commented annotation to `values.yaml` as an example. Please collapse it to one line if you do. Or you can add it to the README with steps on how to setup a global load balancer with NEGs.

2021-04-23 21:09 UTC, steven-sheehy commented on charts/hedera-mirror-common/values-prod.yaml
> +    type: ClusterIP
I think a values-prod.yaml with just two values is not worth having. We should just manually config the few environments that need it as clusterip. Again, this might be just worth documenting in a readme our approach in GKE.

2021-04-24 01:31 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +    type: ClusterIP
Yeah, with removing the NEG config it's better to have it in the README

2021-04-24 01:31 UTC, Nana-EC commented on charts/hedera-mirror-common/values-prod.yaml
> +           }'
Will move to README

2021-04-26 23:25 UTC, steven-sheehy approved these changes
LGTM

2021-04-27 19:22 UTC, xin-hedera commented on charts/README.md
> +In non production environments, the mirror node chart uses the [Traefik subchart](https://github.com/traefik/traefik-helm-chart) to manage access to cluster services through an [Ingress](https://doc.
nit: line too long

2021-04-27 19:24 UTC, rbair23 approved these changes

2021-04-27 19:26 UTC, xin-hedera approved these changes
LGTM

2021-04-27 19:41 UTC, merged