Add NFT Design Doc
hashgraph/hedera-mirror-node pull request #1845
Opened 2021-04-13 04:36 UTC by ijungmann

**Detailed description**:
Extremely rough draft of the NFT Design Doc.  Still questions to be answered, formatting to clean, etc.

**Which issue(s) this PR fixes**:
Fixes #1809 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-15 23:46 UTC, ijungmann commented on docs/design/nft.md
> +- Update `t_entity_types` to add`NFT`
Questioning whether it is wise to make NFT an entity or keep everything in an `nft` table.  It's very dependent on the Token entity to get data, the only independent things would be the serial number/id itself, the memo, and the deleted flag (for burn/wipe cases).

2021-04-15 23:46 UTC, ijungmann commented on docs/design/nft.md
> +  memo
Remove, part of entity

2021-04-15 23:48 UTC, ijungmann commented on docs/design/nft.md
> +  sender_account_id     bigint  not null,
Debating if this is wise.  An NFT shouldn't show up twice in any transfer list, so we should be able to guarantee a sender and a receiver for each transfer.  It goes against the convention we have for crypto/token, but it would cut the rows in the table in half.

2021-04-15 23:50 UTC, ijungmann commented on docs/design/nft.md
> +- Add an `NftHolder` domain object with the same fields as the schema.
Not set on this name.  The convention says we stick with `NftBalance`, it's just a little odd since the balance of an NFT is either "has the one" or "has none"

2021-04-15 23:50 UTC, ijungmann commented on docs/design/nft.md
> +);
Not set on a name. The convention says we stick with NftBalance, it's just a little odd since the balance of an NFT is either "has the one" or "has none"

2021-04-15 23:51 UTC, ijungmann commented on docs/design/nft.md
> +);
Also, need to check how we do the balance/account query.  If an NFT is burned/wiped, we may still pick it up since the account balance file likely will not overwrite this in any way.

2021-04-15 23:53 UTC, ijungmann commented on docs/design/nft.md
> +- `insertTokenBurn` must be updated to mark the NFT entities as deleted.
Still not 100% clear on the inheritance logic for expiration, etc., but we can't inherit a deleted flag, because an NFT can be burned without the Token being deleted.

2021-04-15 23:53 UTC, ijungmann commented on docs/design/nft.md
> +### List NFTTypes
Remove.

2021-04-16 17:22 UTC, ijungmann commented on docs/design/nft.md
> +          "receiverAccount": "0.0.121",
Based on the comment earlier about how this table should be structured.

2021-04-16 17:27 UTC, ijungmann commented on docs/design/nft.md
> +GET `/api/v1/nfts/{serialNumber}`
Should this show the current holder of the token?  Since an NFT can only be held in one account at a time, it might make sense to represent that here.

2021-04-16 17:39 UTC, ijungmann commented on docs/design/nft.md
> +    },
If NFTs are able to be updated (other than deleting one) this query might get tricky.  We can fetch the transfer list from nft_transfers and use that timestamp to get any transaction data we want.  Same goes for create, because we have a `created_timestamp`.  The `modified_timestamp` should line up with the transaction where it was deleted, if that did occur.  But we don't currently have a table that would note the times an NFT got updated.

2021-04-16 20:44 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft_transfer
It would make sense to rename `token_transfer` to `ft_transfer` (or something similar) to make this less blurry.

2021-04-16 20:48 UTC, ijungmann commented on docs/design/nft.md
> +              "memo": "NFT1"
Maybe change to hash.  Or just remove entirely, I was just looking for something else to identify with other than strictly the serial number.

2021-04-16 20:48 UTC, ijungmann commented on docs/design/nft.md
> +                "memo": "NFT1"
Maybe change to hash. Or just remove entirely, I was just looking for something else to identify with other than strictly the serial number.

2021-04-16 20:48 UTC, ijungmann commented on docs/design/nft.md
> +              "memo": "NFT1"
Maybe change to hash. Or just remove entirely, I was just looking for something else to identify with other than strictly the serial number.

2021-04-19 04:26 UTC, ijungmann commented on docs/design/nft.md
> +        }
After confirming NFTs and FTs should show together in one list, this is the only place where I have them separate, mostly because of the way I designed the table to hold fewer rows.  I'm thinking it's better to stick to the convention though and follow the way `token_transfers` is structured, regardless of the extra rows.

2021-04-19 04:27 UTC, ijungmann commented on docs/design/nft.md
> +#### Get Balances
Need to alphabetize the rest of the APIs tomorrow.

2021-04-19 04:27 UTC, ijungmann commented on docs/design/nft.md
> +1. General protobuf questions.
Clean this up to be less vague.

2021-04-19 17:57 UTC, Nana-EC requested changes
First pass, will circle back

2021-04-19 17:57 UTC, Nana-EC commented on docs/design/nft.md
> +- Update `t_entity_types` to add`NFT`
I'm leaning to using the `TOKEN` entity for now and capturing fungibility maybe as a column

2021-04-19 17:57 UTC, Nana-EC commented on docs/design/nft.md
> +      "nftTransfers": [
nit: Naming style inconsistent with other keys
```suggestion
      "nft_transfers": [
```

2021-04-19 17:57 UTC, Nana-EC commented on docs/design/nft.md
> +          "serialNumber": "0.0.124"
We should probably also capture the `nft_id` / `token_id`

2021-04-19 17:57 UTC, Nana-EC commented on docs/design/nft.md
> +);
Add the `nft_id`.
Let's reduce the need for additional joins to get that later and make it easier where we do need a join

2021-04-19 20:24 UTC, ijungmann commented on docs/design/nft.md
> +- Update `t_entity_types` to add`NFT`
That's fair, I have a `fungible` field already in the `token` table, I can add a `memo` and `deleted` field into the `nft` table and we won't have to deal with entities for NFTs at all.

2021-04-19 20:38 UTC, ijungmann commented on docs/design/nft.md
> +- Update `t_entity_types` to add`NFT`
Made that change.

2021-04-19 20:53 UTC, ijungmann commented on docs/design/nft.md
> +);
Done.  I renamed `nft_id` and `nft_type_id` everywhere to just `token_id` as well, I didn't realize I was mixing all those terms together, really it should just be `token_id` and `serial_number` everywhere now. Also added this to the `nft_balance`.

2021-04-19 20:53 UTC, ijungmann commented on docs/design/nft.md
> +      "nftTransfers": [
Good catch, had a few of those.  They should all be fixed now.

2021-04-19 20:55 UTC, ijungmann commented on docs/design/nft.md
> +          "serialNumber": "0.0.124"
Added `token_id`

2021-04-23 03:06 UTC, Nana-EC commented on docs/design/nft.md
> +  sender_account_id     bigint  not null,
I'm actually not against this.
I think not having the other account on all our transfer tables makes things hard, hence the `non_fee_transfer` table.
This might be a change we should consider making eventually or starting here to help paint a more complete question when it comes to our transfer story.

2021-04-28 16:18 UTC, steven-sheehy requested changes

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +              "0.2.11"
Serial numbers are int64 not entity ids. So this should not be a string. Change everywhere else too.

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +          "serial_number": "0.0.124",
number

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +          "sender_account": "0.0.122",
Add `_id` to these

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +          "token_id": "0.2.9",
We should add fungible flag to all to differentiate

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +- cryptoTransfer with an NFT
This is too generic. We should have an acceptance test for concrete flows that users will invoke. Flows like create, mint, transfer.

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +  ],
An NFT is more than just its serial number. We should have a list of nfts documents that exposes data from nft table. Or if we think there will be too many to list in a sub document it should be a `/api/v1/tokens/{id}/nfts` API

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +- `/api/v1/nfts?serialNumber.id=gt:0.0.1001` - All serial numbers in range
drop `.id`

2021-04-28 16:18 UTC, steven-sheehy commented on docs/design/nft.md
> +- GET `/api/v1/nfts/{serialNumber}` will show more detailed information about an individual NFT.
Is a serial number globally unique or only unique within its token? If the latter does it start at 0 and increment by one or is it random?

2021-04-29 04:43 UTC, ijungmann commented on docs/design/nft.md
> +Add an `NftIdConverter`.
Yep, previously it was to be a new entity, looks like that has changed.  There's quite a difference between the HIP and the design docs I built this off of, will need to do a refresh.

2021-04-29 04:48 UTC, ijungmann commented on docs/design/nft.md
> +- GET `/api/v1/nfts/{serialNumber}` will show more detailed information about an individual NFT.
The original design documents had it as a globally unique id, but that was when it was to be its own entity.  I will enquire about how the serial number is now being handled, I had the same question when reading the HIP.

2021-04-29 04:59 UTC, ijungmann commented on docs/design/nft.md
> +  ],
I debated this, I will look at it again after seeing what new fields we need based on the HIP.
I originally decided to make the separate `/nfts` endpoint instead because I could envision a scenario where someone only has the serial number and not the token_id, which would not be possible with this format, and at that point having all the nft data in this list as well seemed excessive, similar to how we don't pull full token data for `/tokens`, only for `/tokens/{id}`

2021-04-29 05:06 UTC, ijungmann commented on docs/design/nft.md
> +# Nonfungible Tokens (NFT)
Good catch.  This seems to be a common issue, even the HIP title is "HTS Non Fungible support".

2021-05-03 05:31 UTC, ijungmann commented on docs/design/nft.md
> +  created_timestamp     bigint  primary key not null,
I thought about this, but I figure A. that could always be pulled from the latest `nft_balance` entry and B. that field could be updated frequently, whereas the rest of the table I don't expect to see a lot of updates.  I'm not against adding it, but that was my logic.

2021-05-03 05:50 UTC, ijungmann commented on docs/design/nft.md
> +  hash                  bytea               not null,
Yes, was added before that was concrete.  It looks like `metadata` is now `memo` for an NFT, so I will keep `memo` and remove this.

2021-05-03 05:52 UTC, ijungmann commented on docs/design/nft.md
> +  memo                  text    default ''  not null,
Originally I think this was leftover from when I wasn't sure if NFT was to be an entity or not.  The HIP now appears to show `memo` will represent the metadata of the NFT.

2021-05-03 05:56 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft_transfer
Sure.  It does appear `token_transfer` is now a catchall in the HIP for both, a fungible token transfer is now an `AccountAmount`.

2021-05-03 07:08 UTC, ijungmann commented on docs/design/nft.md
> +# Nonfungible Tokens (NFT)
Fixed.

2021-05-03 07:20 UTC, ijungmann commented on docs/design/nft.md
> +  - Either deprecate use of the csv file or also add support for new CSV `BalanceFileReader` based on new format
Makes sense.  I rewrote it to mention to update it if the csv is updated, with a link to the questions section (with that question added).

2021-05-03 07:20 UTC, ijungmann commented on docs/design/nft.md
> +  - TBA
Sure, removed.

2021-05-03 07:21 UTC, ijungmann commented on docs/design/nft.md
> +    https: //hedera.zoom.us/j/8826097631?pwd=VUxmeW13Y0luREJuWmwxRFpHZzQvUT09
Fixed.

2021-05-03 07:21 UTC, ijungmann commented on docs/design/nft.md
> +- Add to `token` table fields `maxSupply` (long) and `fungible` (boolean)
Added bullet for default values.

2021-05-03 07:22 UTC, ijungmann commented on docs/design/nft.md
> +  hash                  bytea               not null,
Removed.

2021-05-03 07:22 UTC, ijungmann commented on docs/design/nft.md
> +  token_id            bigint    not null,
Should all be removed now.

2021-05-03 07:22 UTC, ijungmann commented on docs/design/nft.md
> +- Add a unique constraint to `nft_transfer` for `serial_number` and `consensus_timestamp`, desc
Yep, copy/paste error, added the correct constaint.

2021-05-03 07:22 UTC, ijungmann commented on docs/design/nft.md
> +Add an `NftIdConverter`.
Removed.

2021-05-03 23:56 UTC, ijungmann commented on docs/design/nft.md
> +              "0.2.11"
Fixed.

2021-05-03 23:57 UTC, ijungmann commented on docs/design/nft.md
> +          "sender_account": "0.0.122",
Fixed.

2021-05-03 23:58 UTC, ijungmann commented on docs/design/nft.md
> +          "token_id": "0.2.9",
Added here, as well as `/transactions`.

2021-05-03 23:59 UTC, ijungmann commented on docs/design/nft.md
> +- cryptoTransfer with an NFT
Added details here, two new test suites to test the additional NFT logic, the rest should already be covered in HTS tests.

2021-05-04 00:10 UTC, ijungmann commented on docs/design/nft.md
> +  ],
I think it would be bulky to add the memo/metadata to `/tokens`, but I've added the data to `/tokens/{id}` and all endpoints that branch from there.  Now that serial numbers aren't unique I've moved `/nfts` to `/tokens/{id}/nfts` as suggested, and added serialNumber as a possible filter on `/tokens`.

2021-05-04 00:11 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/nfts?serialNumber.id=gt:0.0.1001` - All serial numbers in range
Removed.

2021-05-04 00:11 UTC, ijungmann commented on docs/design/nft.md
> +- GET `/api/v1/nfts/{serialNumber}` will show more detailed information about an individual NFT.
Confirmed they are incremented and only unique per token, adjusted to account for that.

2021-05-04 15:58 UTC, xin-hedera requested changes

2021-05-04 15:58 UTC, xin-hedera commented on docs/design/nft.md
> +      "name": "TOKENTRANSFER",
```suggestion
      "name": "CRYPTOTRANSFER",
```

2021-05-04 15:58 UTC, xin-hedera commented on docs/design/nft.md
> +          "fungible": true,
```suggestion
          "fungible": false,
```

2021-05-04 15:58 UTC, xin-hedera commented on docs/design/nft.md
> +    {
nit: indentation

2021-05-04 15:58 UTC, xin-hedera commented on docs/design/nft.md
> +    {
nit: indentation

2021-05-04 15:58 UTC, xin-hedera commented on docs/design/nft.md
> +    {
nit: indentation

2021-05-04 15:58 UTC, xin-hedera commented on docs/design/nft.md
> +      "transaction_type": "TOKENBURN"
should we not add the `transaction` prefix?

2021-05-06 07:09 UTC, ijungmann commented on docs/design/nft.md
> +      "transaction_type": "TOKENBURN"
You mean just have `id` and `type`?  I'd be okay with that.

2021-05-06 07:09 UTC, ijungmann commented on docs/design/nft.md
> +    {
Fixed.

2021-05-06 07:09 UTC, ijungmann commented on docs/design/nft.md
> +    {
Fixed.

2021-05-06 07:10 UTC, ijungmann commented on docs/design/nft.md
> +          "fungible": true,
Good catch, fixed

2021-05-06 07:10 UTC, ijungmann commented on docs/design/nft.md
> +    {
Fixed.

2021-05-06 07:10 UTC, ijungmann commented on docs/design/nft.md
> +      "name": "TOKENTRANSFER",
Fixed.

2021-05-06 15:26 UTC, xin-hedera commented on docs/design/nft.md
> +      "transaction_type": "TOKENBURN"
yes. we had a discussion sometime back in our scrum about the redundant prefix. I think the conclusion is for new fields we should not have such redundant prefix.

2021-05-06 17:37 UTC, ijungmann commented on docs/design/nft.md
> +      "transaction_type": "TOKENBURN"
My only concern is that our regular `/transactions` endpoint has the prefixes.  But I'm okay with making that change here.

2021-05-06 17:39 UTC, ijungmann commented on docs/design/nft.md
> +      "transaction_type": "TOKENBURN"
Fixed.

2021-05-07 21:35 UTC, steven-sheehy commented on docs/design/nft.md
> +  memo                  text    default ''  not null,
Yes, they renamed `metadata` to `memo` in the doc so it's clear now the source.

2021-05-07 21:44 UTC, steven-sheehy commented on docs/design/nft.md
> +  - Default values will be `true` and `null` (null `maxSupply` will represent an infinite amount of tokens are possible)
It sounds like the default value for `maxSupply` should be max long per the doc's matrix and this comment:

> By default, if maxSupply is not provided, the token will be defined as having Infinite supply. (backwards compatible)

2021-05-07 21:44 UTC, steven-sheehy commented on docs/design/nft.md
> +  created_timestamp     bigint  primary key not null,
I believe a token associate must still occur. So guess that would be the canonical source of the linkage.

2021-05-10 17:41 UTC, steven-sheehy requested changes

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +- Add a unique constraint to `nft_balance` for `token_id`, `serial_number`, `account_id`, and `consensus_timestamp`,
Again, we can maybe add nft timestamp. We can also consider keeping serial_number and token_id in addition.

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +- `insertTokenBurn` must be updated to handle the new field `amountOrSerialNumbers` and mark the `NFTs` as deleted if
And update modified timestamp

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +            "serial_numbers": [
nft balances also quite differ from fungible and we should consider a separate array. The current structure would be very hard for clients with strongly typed domain mapping tools to parse different fields depending upon a flag.

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +create table if not exists nft_balance
We should also consider pushing back against NFTs being added to balances file. There's no actual balance being changed, it's just a list of serial numbers associated with a token. That info is already fully contained in the other tables unless someone has a start date before the token create. It's just duplication of information for us. If someone creates 10M NFTs for one token, it doesn't make sense to send 10M serial numbers every 15 min.

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +      "serial_numbers": [
Remove

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +- Add to `token` table fields `fungible` (boolean) and `maxSupply` (long)
Should we have an enum instead of a boolean to match the proto? Do we know if there ever could be a 3rd type?

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +      "serial_number": 124
Should add `modified_timestamp` and maybe `deleted` here and nfts/{id}

2021-05-10 17:41 UTC, steven-sheehy commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` will return minimal transaction information for each
I'm not sure the need/value of this API. Would prefer we not add this quite different API until there's a custom ask.

2021-05-11 00:39 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/nfts?serial.number=gt:0.0.1001` - All serial numbers in range
Got it, fixed.

2021-05-11 00:51 UTC, ijungmann commented on docs/design/nft.md
> +  "nfts": [
So remove this (and in `/tokens`  as well), keep `tokens/{id}/nfts` as is?  Should I add a link to the `tokens/{id}/nfts` for applicable tokens, or is that just creating clutter?

2021-05-11 02:19 UTC, ijungmann commented on docs/design/nft.md
> +      "serial_numbers": [
Removed.  I assume I should also remove the `serialNumber` filter for this API?

2021-05-11 05:06 UTC, ijungmann commented on docs/design/nft.md
> +- Add to `token` table fields `fungible` (boolean) and `maxSupply` (long)
Sure, it could be possible considering they've talked about NFTs inside fungible tokens and vice-versa.  I've changed it.

2021-05-11 05:10 UTC, ijungmann commented on docs/design/nft.md
> +  - Default values will be `true` and `null` (null `maxSupply` will represent an infinite amount of tokens are possible)
Got it, yeah, the infinite concept threw me.  Changed it.

2021-05-11 05:14 UTC, ijungmann commented on docs/design/nft.md
> +  deleted               boolean             not null,
Fixed.

2021-05-11 05:17 UTC, ijungmann commented on docs/design/nft.md
> +- Add a unique constraint to `nft` for `token_id`, `serial_number`, and `created_timestamp`, desc
Makes sense, fixed.

2021-05-11 05:24 UTC, ijungmann commented on docs/design/nft.md
> +- Add a unique constraint to `nft_transfer` for `token_id`, `serial_number` and `consensus_timestamp`, desc
Yeah, it's a bit hairy.  That's a clever idea, I've swapped those two fields out for `nft_created_consensus_timestamp`.  We could also do that for nft_transfer if want to further save space.

2021-05-11 05:31 UTC, ijungmann commented on docs/design/nft.md
> +- `insertTokenBurn` must be updated to handle the new field `amountOrSerialNumbers` and mark the `NFTs` as deleted if
Good catch, added here and for delete and wipe.

2021-05-11 05:37 UTC, ijungmann commented
I'll fix the DCO at the end so I'm not flooding a bunch of commits, but I am aware of it.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +  - Default values will be `true` and max long.
```suggestion
  - Default values will be `FUNGIBLE` and max long, respectively.
```

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +- `/api/v1/tokens?serial.number=1001` - All tokens that contain a serial number `1001` (implied that `type` will
```suggestion
- `/api/v1/tokens?serialNumber=1001` - All tokens that contain a serial number `1001` (implied that `type` will
```

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +      "tokenType": FUNGIBLE,
JSON errors here and elsewhere for this enum. Should have double quotes.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +  nft_created_consensus_timestamp   bigint  not null
I think this can be shortened to just `nft_id` or `nft_timestamp`.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +create table if not exists nft_balance
I would suggest we remove it, once it's confirmed it won't show up in the balance proto.

We don't need a `nft_owner` table as the `nft_transfer` provides the exact same information. It provides both the current and historical ownership of NFTs.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +  nft_created_consensus_timestamp   bigint  not null
Same `nft_id` or `nft_timestamp`.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` will return minimal transaction information for each
I see. Does a "history of the nft" mean its full transaction history or just a history of transfers? It would be more efficient for the latter to just show nft 1 was transferred from bob to carol to Dave. Then it could be `../transfers`.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +- `/api/v1/nfts?deleted=false` - All serial numbers that have not been deleted.
Querying on just a boolean would be slow, hence why we don't support it for others. Let's remove for now.

2021-05-14 15:34 UTC, steven-sheehy commented on docs/design/nft.md
> +      "serial_numbers": [
Correct

2021-05-14 16:07 UTC, steven-sheehy commented on docs/design/nft.md
> +  "nfts": [
Yep, keep `tokens/{id}/nfts`. No, we shouldn't add links as we only have `links.next` and haven't thought through how other links would look like. Would've been better to support HATEOAS from the beginning.

2021-05-14 16:38 UTC, ijungmann commented on docs/design/nft.md
> +  "nfts": [
Alright, that should be done now then.  Makes sense.

2021-05-14 16:42 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft_balance
Only concern would be an NFT with no transfers, i.e. an NFT that was just minted would be in the treasury balance, so would have to check for that, and check the `deleted` flag(s) and timestamps.  But that's doable, so yes, I will remove this.

2021-05-14 16:57 UTC, ijungmann commented on docs/design/nft.md
> +      "tokenType": FUNGIBLE,
Whoops, apparently I did not push the fix for that the other day.  That should be fixed everywhere now, also changed it to `token_type`.

2021-05-14 16:59 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/tokens?serial.number=1001` - All tokens that contain a serial number `1001` (implied that `type` will
Fixed.

2021-05-14 16:59 UTC, ijungmann commented on docs/design/nft.md
> +  - Default values will be `true` and max long.
Good call, added.

2021-05-14 16:59 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft_balance
Removed this table

2021-05-14 17:01 UTC, ijungmann commented on docs/design/nft.md
> +  nft_created_consensus_timestamp   bigint  not null
I like `nft_timestamp`, changed.

2021-05-14 17:03 UTC, ijungmann commented on docs/design/nft.md
> +  nft_created_consensus_timestamp   bigint  not null
Removed the table as per earlier discussion.

2021-05-14 17:05 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/nfts?deleted=false` - All serial numbers that have not been deleted.
Makes sense, removed.

2021-05-14 17:27 UTC, ijungmann commented on docs/design/nft.md
> +- Add to `token` table fields `tokenType` (enum, values FUNGIBLE and NON_FUNGIBLE) and `maxSupply` (long)
Went with `token_type` as we already have `token_id` in this table, and it matches the protobuf.  I'm okay with shortening to `type` though, since we've discussed making columns less verbose.
The other suggestions here are fixed.

2021-05-14 17:30 UTC, ijungmann commented on docs/design/nft.md
> +      "tokenType": FUNGIBLE,
`token_type` now just `type` since it's in `token` context

2021-05-14 17:30 UTC, ijungmann commented on docs/design/nft.md
> +- Add to `token` table fields `tokenType` (enum, values FUNGIBLE and NON_FUNGIBLE) and `maxSupply` (long)
Changed it to `type`

2021-05-14 17:39 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/tokens?serial.number=1001` - All tokens that contain a serial number `1001` (implied that `type` will
Sure.  I was envisioning a scenario where someone has the serial number but not the token id and needed the token data.  But that was not a requirement.  Removed.

2021-05-14 17:39 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/tokens?type=fungible` - All fungible tokens (other values are `non_fungible` and `both` (default))
Fixed and fixed.

2021-05-14 17:41 UTC, ijungmann commented on docs/design/nft.md
> +- `insertTokenWipe` must be must be updated to handle the new field `amountOrSerialNumbers`, mark the `NFTs` as deletedm
Fixed.

2021-05-14 17:43 UTC, ijungmann commented on docs/design/nft.md
> +- `insertTokenDelete` must be added to mark the `NFTs` as deleted and update `modifiedTimestamp` if the `tokenType`
You're correct that that was my plan, I was a bit worried about how that would affect the performance.  I like your idea, I'll remove this line and add a note in the REST API sections to do this logic.

2021-05-14 17:54 UTC, Nana-EC requested changes
Some thoughts. Will circle back for a second take on the latter sections

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +- Ingest NFT transactions and persist to the database
we should maybe explicitly call out the type of NFT's we're looking to support first(whole, fractional, singleton) and in the no goals the ones we're not

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +create table if not exists nft
Do we view this as a subset of the token table? similar to token_account?
In that case should we also have a column for `account_id` to capture who the nft belongs to?

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
What timestamp is this? The nft `created_timestamp`?

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Looking at info from this table would tell me stuff is being transferred, from and to whom. However, it doesn't tell me what. I would have expected the `token_id` and `serial_number`, is this an optimization on space?

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +- Add an `NftBalance` domain object with the same fields as the schema.
I don't see an `nft_balance` table. Is that missing?

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +- `insertTokenDelete` must be added to mark the `NFTs` as deleted and update `modifiedTimestamp` if the `tokenType`
I'm thinking we might want to give some thought to offloading some logic to the db layer for scenarios like this, that way we don't hold up the parser. e.g. triggers or some repeatable migrations that can be scheduled, I'm sure other efficient options exist.

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +        "nfts": [
Yeah, as we grow having it at the base level will become problematic cause the response size will bloat.
Might be a breaking change but worth it to move balances to the single account level.

If we limit the amount we also have to provide logic to page the entries to get the total list eventually or notify that this is a partial list and they have to go to `/api/v1/tokens/{tokenId}/balances?account.id=<accountId>` to get the full list.
Either ways requires some more planning

Notably we don't have a single balance resource endpoint

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +- Update `/api/v1/balances` and `/api/v1/balances/{id}` response to add nfts list
Do you mean to create a new `/api/v1/balances/{id}`, we should call that out explicitly ?

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts` will list basic information of all NFTs for a given token.
You should call out the response if this is called on a fungible token. Probably 404 as an empty list could mean serials have not been minted or the ones that were got deleted and future ones could still be minted

2021-05-14 17:54 UTC, Nana-EC commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` will return minimal transaction information for each
Yeah I was gonna say in terms of history I would imagine it would refer to ownership transfer in which case it should be under the `/api/v1/transfers` API I suggested.

I don't think we should load history under the `/api/v1/tokens/{id}/nfts/{serialNumber}` we already have problems with cases where API responses have information that doesn't really need to be there.
If they want history it should be an explicit API resource

2021-05-14 17:55 UTC, ijungmann commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` will return minimal transaction information for each
Per discussion with Atul just now
`The history endpoint should have a cradle-to-grave history of the NFT ( == <token_type + serial_number>)`
So it would involve minting and burning/deleting/etc.

2021-05-14 20:09 UTC, Nana-EC commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` will return minimal transaction information for each
In that case it maps across transaction types (CRYPTOTRANSFER, TOKENCREATION, TOKENFREEZE, TOKENUNFREEZE, TOKENGRANTKYC, TOKENREVOKEKYC, TOKENDELETION, TOKENUPDATE, TOKENMINT, TOKENBURN, TOKENWIPE, TOKENASSOCIATE, TOKENDISSOCIATE) which justifies `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions`.

Also even though it's at the `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` endpoint we should design it in a way that supports a potential `/api/v1/tokens/{id}/transactions` for the FUNGIBLE case. Out of scope for this design but worth considering during the implementation phase.

2021-05-14 20:41 UTC, Nana-EC requested changes
Added some suggestions

2021-05-14 20:41 UTC, Nana-EC commented on docs/design/nft.md
> +  - `TokenBurnTransactionSupplier` and `TokenWipeTransactionSupplier` will need a enum `tokenType` attribute, and it
nit:
```suggestion
  - `TokenBurnTransactionSupplier` and `TokenWipeTransactionSupplier` will need an enum `tokenType` attribute, and it
```

2021-05-14 20:41 UTC, Nana-EC commented on docs/design/nft.md
> +  - Add a new `tokenType` enun attribute to be used when doing a TOKEN or BOTH transfer, that determines whether to use
```suggestion
  - Add a new `tokenType` enum attribute to be used when doing a TOKEN or BOTH transfer, that determines whether to use
```

2021-05-14 20:41 UTC, Nana-EC commented on docs/design/nft.md
> +  `/tokens/{id}/nfts/{serialNumber}/transactions`, `/balances`, and `/transactions`,
Can't rely on balances because of the 15 min balance stream file frequency.
```suggestion
  `/tokens/{id}/nfts/{serialNumber}/transactions`, and `/transactions`,
```

2021-05-14 20:41 UTC, Nana-EC commented on docs/design/nft.md
> +  `/tokens/{id}/nfts/{serialNumber}/transactions`, `/balances`, and `/transactions`,
Same below

2021-05-14 20:41 UTC, Nana-EC commented on docs/design/nft.md
> +Add acceptance tests that verify all transactions are handled appropriately. This includes tests for
You'll wanna add a test case for scheduled nft transfer

- Create a token with type `NON-FUNGIBLE`
 - Mint a serial number
 - Create an account with receiverSigRequired=true
 - Associate the token to an account
 - Create a schedule of CRYTOTRANSFER to transfer the nft
 - Submit a ScheduleSign from the receiving account
 - Verify response codes and data from `/tokens`, `/tokens/{id}/nfts`,
   `/tokens/{id}/nfts/{serialNumber}/transactions`, `/schedules/{id}`, and `/transactions`

2021-05-14 21:44 UTC, ijungmann commented on docs/design/nft.md
> +        "nfts": [
Been pondering this for a while now.  All of `/balances`, `/accounts`, and `/token/{id}/balances` could have this problem.  `/api/v1/accounts/{id}/nfts` could also have the same issue, if one token in the account has 10000 serial numbers and another has 10000 then splitting that up gets tricky.  It's really the combination of account_id and token_id that helps.

Nana's idea for `/api/v1/tokens/{tokenId}/balances?account.id=<accountId>` would work if we're comfortable with only showing serial information when a filter is applied.  Or we could do any of `/tokens/{tokenId}/balances/{accountId}`, or either of the two going from `/accounts` instead.  `/balances` would get messy, since we'd need both filters to do this, unless we do as Nana suggested and move it entirely under `/accounts`, which is a much bigger change.

I think still having the `nft` list with the token_ids would be good in these other places, but I will remove the serial_numbers list.

2021-05-14 22:00 UTC, ijungmann commented on docs/design/nft.md
> +        "nfts": [
I've removed the serial number list from the 3 endpoints for the time being and left a note about that, still debating how/where to show the list.

2021-05-14 22:03 UTC, ijungmann commented on docs/design/nft.md
> +- Ingest NFT transactions and persist to the database
I'll take a look at documenting that, but there's still some debate about which types services will support or even can support, so that's a little fluid at the moment.  Here's the [document that breaks that down a little](https://www.notion.so/hedera/IWA-Compatibility-41648a9fb56b4bdeb28ceb8b5f088d89)

2021-05-14 22:08 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft
Yes, this would hold the data for the individual nfts that can't be represented in the `token` table (pretty much memo, the deleted flag, and some timestamps).  By `account_id` you mean the current holder?  Steven and I have been discussing that above, my original thought was that could be a frequently changing column in an otherwise mostly static table, and would better be left to `nft_balances`.  That table has since been removed per a suggestion we rely solely on the `nft_transfer` table to find that.

2021-05-14 22:11 UTC, ijungmann commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Yes, Steven suggested we remove `token_id` and `serial_number` because they are only unique in combination, it was making the index more complex, and replacing it with the timestamp of the nft's creation.  He also requested I shorten the name to that from what it was (`nft_created_consensus_timestamp`).  Willing to discuss this again, but that's how this came to be.

2021-05-14 22:13 UTC, ijungmann commented on docs/design/nft.md
> +- Add an `NftBalance` domain object with the same fields as the schema.
It was removed earlier, just forgot to get rid of these.  They've been removed now.

2021-05-14 22:17 UTC, ijungmann commented on docs/design/nft.md
> +- Update `/api/v1/balances` and `/api/v1/balances/{id}` response to add nfts list
No, just me mixing up the endpoints, I sometimes forget the details in `/accounts` vs `/balances`.  I've corrected this now.

2021-05-14 22:20 UTC, ijungmann commented on docs/design/nft.md
> +- GET `/api/v1/tokens/{id}/nfts` will list basic information of all NFTs for a given token.
Good call, added notes what to do for `FUNGIBLE` tokens as well as deleted tokens

2021-05-14 22:25 UTC, ijungmann commented on docs/design/nft.md
> +  - `TokenBurnTransactionSupplier` and `TokenWipeTransactionSupplier` will need a enum `tokenType` attribute, and it
Fixed.

2021-05-14 22:25 UTC, ijungmann commented on docs/design/nft.md
> +  - Add a new `tokenType` enun attribute to be used when doing a TOKEN or BOTH transfer, that determines whether to use
Fixed.

2021-05-14 22:25 UTC, ijungmann commented on docs/design/nft.md
> +  `/tokens/{id}/nfts/{serialNumber}/transactions`, `/balances`, and `/transactions`,
Removed in both.

2021-05-14 22:25 UTC, ijungmann commented on docs/design/nft.md
> +Add acceptance tests that verify all transactions are handled appropriately. This includes tests for
Thanks for writing it out for me, saved me a few minutes!  Added.

2021-05-14 22:40 UTC, Nana-EC commented on docs/design/nft.md
> +- Ingest NFT transactions and persist to the database
Yep, thought we could just mention Whole, Singleton and Fraction and say Hybrid wasn't supported. But you're right if it's in flux let's leave it as is and out

2021-05-14 22:49 UTC, Nana-EC commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Hmmm, this now requires a forced join to figure out which nft details.
I think we can get away with this as is but once we iron out and expose a transfers story we'll realize this adds overhead.
Personally would prefer to have kept `token_id` and `serial_number`columns and make the index the complex (`consensus_timestamp, token_id, serial_number`) or (`consensus_timestamp, token_id, receiver_account_id, sender_account_id`) I prefer the former.

If we have to leave it as is I'd go with `nft_created_timestamp` over `nft_timestamp`, since there also exists a modified_timestamp for an nft

2021-05-14 23:00 UTC, Nana-EC commented on docs/design/nft.md
> +create table if not exists nft
Yes `account_id` would be the current holder/owner. 
Right having that would mean every time a transfer happens we would have to update this table!

If we rely solely on `nft_transfer` then we'd always be searching the `nft_transfer` table to find the latest account that received the nft (by token_id & serial_number).

I guess it comes down to how individual nfts are traded. 
If it's rarely then having it here makes sense, if it's often then not having to update this table every time is a benefit. Really comes down to the application. In a collectors application trades are rare once acquired. In say a DEX application with high trading the swaps can get crazy.

Hmmm

2021-05-17 16:30 UTC, ijungmann commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
I'll swap it to nft_created_timestamp for now, since I think all sides would agree to that at least.  You are correct that it forces a join on the `nft` table which is unfortunate.  It's a tradeoff of query complexity vs. index complexity. 
@steven-sheehy would be interested for your thoughts since you brought up the index concerns initially.

2021-05-17 16:44 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft
I've asked Donald for some clarity on the general expectations of NFT transfer rates.
The field would help solve the issue of initial ownership, we would set the `nft` account_id to the treasury account on create and would not have to do a search for an `nft` with no transfers.  Since you and Steven have both mentioned it, and it does help with a variety of issues, I think I'm okay with adding it, just want to see if I can get any specs that push the issue one way or the other.

2021-05-17 16:54 UTC, steven-sheehy requested changes

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +    - Serial numbers are auto-incremented per token, so minting a hardcoded or configured (one universal value) number
I prefer this approach over the more complex `nft.1.serialNo.1` approach. If you're using the expression created serial numbers in a token transfer or associate you're not going to need too many of them. You'll only need a lot if you're performance testing token create or token mint, which don't require the serial number.

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
After checking again, perhaps it might be better to just use `consensus_timestamp, token_id, serial_number`. We at least won't have receiver and sender in the index so it won't be every field. And our rest api shows token and serial so we'll need to join if we don't have it.

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +  "created_timestamp": "1610682445.003266000",
Even if it's not stored in the table, should we show who currently owns the nft?

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +  - Balances should only display if the token have not been deleted (`token.delted` == false)
```suggestion
  - Balances should only display if the token has not been deleted (e.g. `token.deleted` is false).
```

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +- Update `/api/v1/tokens/{id}/balances` response to only show `account` when the token is an NftType token.\
`\` at end

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +      deleted. (`nft.deleted` == false)
```suggestion
    - An account balance should only be listed if the account has at least one NFT that has not been
      deleted (e.g. `nft.deleted` is false).
```

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +        "nft_token_ids": [
I don't think this is useful. Nor do I think it is possible as this endpoint is populated from balance tables but we removed the `nft_balance` table. Instead, we should utilize an account ID filter for `/api/v1/tokens` and `/api/v1/tokens/{id}/nfts`

2021-05-17 16:54 UTC, steven-sheehy commented on docs/design/nft.md
> +      "nft_token_ids": [
I don't think this is useful. Nor do I think it is possible as this endpoint is populated from balance tables but we removed the `nft_balance` table. Instead, we should utilize an account ID filter for `/api/v1/tokens` and `/api/v1/tokens/{id}/nfts`

2021-05-17 17:06 UTC, ijungmann commented on docs/design/nft.md
> +  created_timestamp     bigint  primary key not null,
Spoke to Donald about expected transfer rates for NFTs after Nana brought up adding the same field, we are expecting a relatively low volume of transfers overall, and this would solve the issue of showing the owner of a newly minted NFT (no transfers), so I have added this field.

2021-05-17 17:07 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft
Donald confirmed we're expecting low volumes of transfers.  I will add an `account_id` field.

2021-05-17 17:09 UTC, ijungmann commented on docs/design/nft.md
> +create table if not exists nft
Added

2021-05-17 17:11 UTC, ijungmann commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Sure, sounds good, I'll swap it back.  This was a bigger issue with the `nft_balance` table because that was every field, but now that table is gone.

2021-05-17 17:11 UTC, ijungmann commented on docs/design/nft.md
> +  memo                  text    default ''      not null,++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Yeah, just saw that, something was hitting that key on my keyboard.  Removed.

2021-05-17 20:56 UTC, Nana-EC commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Great, I think this is the right approach and the easier one to manage.

2021-05-17 21:12 UTC, Nana-EC requested changes

2021-05-17 21:12 UTC, Nana-EC commented on docs/design/nft.md
> +- Add a unique constraint to `nft_transfer` for `consensus_timestamp` and `nft_timestamp`, desc
Unique id could be the other other mentioned `consensus_timestamp, token_id, receiver_account_id, sender_account_id`

2021-05-17 21:12 UTC, Nana-EC commented on docs/design/nft.md
> +  - NFTs should only display if the token have not been deleted (`token.delted` == false). Otherwise, display empty list
```suggestion
  - NFTs should only display if the token have not been deleted (`token.deleted` == false). Otherwise, display empty list
```

2021-05-17 21:12 UTC, Nana-EC commented on docs/design/nft.md
> +  "created_timestamp": "1610682445.003266000",
Yes

2021-05-17 21:16 UTC, steven-sheehy commented on docs/design/nft.md
> +  - NFTs should only display if the token have not been deleted (`token.delted` == false). Otherwise, display empty list
Dupe

2021-05-17 21:17 UTC, steven-sheehy commented on docs/design/nft.md
> +- Add a unique constraint to `nft_transfer` for `consensus_timestamp` and `nft_timestamp`, desc
We don't want an index that covers all fields. Large indexes was the reason I was proposing a nft_timestamp.

2021-05-17 22:59 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/nfts?serialNumber=gt:0.0.1001` - All serial numbers in range
Fixed.  Also added `accountId` filter.

2021-05-17 23:00 UTC, ijungmann commented on docs/design/nft.md
> +  "created_timestamp": "1610682445.003266000",
Added this, also added it to the table after discussing with Donald the expected transfer volume.

2021-05-17 23:03 UTC, ijungmann commented on docs/design/nft.md
> +  - Balances should only display if the token have not been deleted (`token.delted` == false)
Fixed.

2021-05-17 23:03 UTC, ijungmann commented on docs/design/nft.md
> +- Update `/api/v1/tokens/{id}/balances` response to only show `account` when the token is an NftType token.\
Fixed.

2021-05-17 23:03 UTC, ijungmann commented on docs/design/nft.md
> +      deleted. (`nft.deleted` == false)
Fixed.

2021-05-17 23:05 UTC, ijungmann commented on docs/design/nft.md
> +    - Serial numbers are auto-incremented per token, so minting a hardcoded or configured (one universal value) number
Sure, I agree, I figured the added customization wasn't worth the complexity but wanted to write it down in case others thought differently.  I will go ahead and remove the mentions of it.

2021-05-17 23:09 UTC, ijungmann commented on docs/design/nft.md
> +    - Serial numbers are auto-incremented per token, so minting a hardcoded or configured (one universal value) number
Removed this `alternatively` section.

2021-05-17 23:19 UTC, ijungmann commented on docs/design/nft.md
> +        "nft_token_ids": [
Agreed, didn't think about how tough this would be to construct without the `nft_balance` table.  The only thing I can think we're going to miss with this approach is there's not a great way to see historical "NFT balances" without hitting the `/nfts/transactions` endpoint for every NFT.  I don't think there's an actual ask for that, but it's the only thing we're missing for parity with existing HTS and accounts.

2021-05-17 23:32 UTC, ijungmann commented on docs/design/nft.md
> +        "nft_token_ids": [
Right now we have an account ID filter on `/tokens`, but it queries for tokens that are associated to the account.  For `/tokens/{id}/nfts?account.id` it will have to check the actual `nft` table to see which NFTs are currently owned by the account.  It might be slightly confusing that `/tokens` shows tokens, and then going to `/tokens/{id}/nfts` shows an empty list, but I don't know that we want to change the behavior of `/tokens`, would affect fungible tokens too.  I doubt associating TokenTypes and then not actually holding an NFT is going to be a common scenario anyway.

2021-05-17 23:35 UTC, ijungmann commented on docs/design/nft.md
> +        "nft_token_ids": [
Removed

2021-05-17 23:35 UTC, ijungmann commented on docs/design/nft.md
> +      "nft_token_ids": [
Removed

2021-05-17 23:40 UTC, ijungmann commented on docs/design/nft.md
> +  - NFTs should only display if the token have not been deleted (`token.delted` == false). Otherwise, display empty list
Fixed.

2021-05-17 23:48 UTC, ijungmann commented on docs/design/nft.md
> +- Add a unique constraint to `nft_transfer` for `consensus_timestamp` and `nft_timestamp`, desc
Agreed, I've put it back to `consensus_timestamp`, `token_id`, and `serial_number`

2021-05-17 23:49 UTC, ijungmann commented on docs/design/nft.md
> +      "nft_token_ids": [
I also updated the `tokens/{id}/balances` section, as we'll have the same issue there.  Instead, we'll through an error there pointing to `/nfts`

2021-05-17 23:51 UTC, ijungmann commented on docs/design/nft.md
> +
Updated this after discussing the fact that `/accounts` and `/balances` have issues now that we don't have the `nft_balance` table.  Effectively `tokens/{id}/nfts` is the balance endpoint for NFTs anyway.

2021-05-17 23:55 UTC, ijungmann commented on docs/design/nft.md
> +        "nfts": [
From all the discussion downstream, the direction seems to be having users go to `/tokens` with an account id and the fungible flag `false`, and then going to each `/tokens/{id}/nfts` to get the detailed breakdown.  This should cover us for everything except historical balances, which I don't think is a major priority.

2021-05-18 17:41 UTC, ijungmann commented on docs/design/nft.md
> +- Ingest NFT transactions and persist to the database
Added some comments in the goals for this.

2021-05-18 18:28 UTC, steven-sheehy commented on docs/design/nft.md
> +  memo                  text    default ''      not null,++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Must've been a ferret

2021-05-18 18:32 UTC, steven-sheehy requested changes

2021-05-18 18:32 UTC, steven-sheehy commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Think you forgot to remove this field?

2021-05-18 18:32 UTC, steven-sheehy commented on docs/design/nft.md
> +  - This endpoint should return a 404 if the token is not of type `NON-FUNGIBLE` with a message that indicates users
Perhaps a 409 is more appropriate

2021-05-18 18:48 UTC, ijungmann commented on docs/design/nft.md
> +  - This endpoint should return a 404 if the token is not of type `NON-FUNGIBLE` with a message that indicates users
That would line up a bit better, sure.  Changed to that here (and the token balance endpoint).

2021-05-18 18:48 UTC, ijungmann commented on docs/design/nft.md
> +  nft_timestamp         bigint  not null,
Yep, removed now.

2021-05-18 18:59 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-05-18 19:09 UTC, xin-hedera requested changes

2021-05-18 19:09 UTC, xin-hedera commented on docs/design/nft.md
> +- `/api/v1/tokens/{id}/nfts?accountId=gt:0.0.111` - All NFTs belonging to a given account id.
```suggestion
- `/api/v1/tokens/{id}/nfts?accountId=0.0.111` - All NFTs belonging to a given account id.
```

Not sure using `accountId` here is previously discussed or not, want to point out in other places it's `account.id`

2021-05-18 19:43 UTC, ijungmann commented on docs/design/nft.md
> +  "modified_timestamp": null,
Good catch, removed the not null constraint.

2021-05-18 19:51 UTC, ijungmann commented on docs/design/nft.md
> +      "deleted": true,
That's fair, I hadn't considered how to handle that.  The two ways I can think are:
1. Add logic to the REST APIs to not show `account_id` when `deleted` is true (or show as null).
2. Have the importer mark `account_id` as null when deleted.

The first approach seems like the better one because the latter forces `account_id` in the DB to allow nulls, and we get back to the problem of `TokenDelete` having to do updates on every `nft` entry for it.  I've added some notes to the REST APIs for this, but I'm swapping the flag in this example to `false` just for simplicity.

2021-05-18 19:53 UTC, xin-hedera commented on docs/design/nft.md
> +  "modified_timestamp": null,
umm, don't think we should drop `not null`

`modifed_timestamp` should have the same value as `created_timestamp` initially, then get updated whenever there's a change. this is aligned with `token.modified_timestamp`

2021-05-18 19:53 UTC, ijungmann commented on docs/design/nft.md
> +- `/api/v1/tokens/{id}/nfts?accountId=gt:0.0.111` - All NFTs belonging to a given account id.
Removed the `gt` and fixed to `account.id`.

2021-05-18 19:57 UTC, ijungmann commented on docs/design/nft.md
> +  "modified_timestamp": null,
Oops, right, that makes sense.  Fixed, just added a timestamp to the REST example.

2021-05-18 20:00 UTC, xin-hedera commented on docs/design/nft.md
> +      "deleted": true,
flipping to `"deleted": false` should have addressed it.

The description above the example says:

"NFTs should only display if the token has not been deleted (e.g. token.deleted is false) Otherwise, display empty list.
account_id should not display when the NFT has been deleted."

Thus it's unnecessary to mark `account_id` as `null`

2021-05-18 20:02 UTC, ijungmann commented on docs/design/nft.md
> +      "deleted": true,
Right, I meant that as an either-or situation.  I went with the first, just wanted to document my thoughts.

2021-05-19 15:49 UTC, steven-sheehy approved these changes

2021-05-19 15:54 UTC, Nana-EC approved these changes
LGTM

2021-05-19 16:47 UTC, merged