Updated scheduled tests
hashgraph/hedera-mirror-node pull request #1846
Opened 2021-04-13 05:16 UTC by Nana-EC

**Detailed description**:
Scheduled transactions were updated in accordance with the [redesign](https://github.com/hashgraph/hedera-services/blob/master/docs/scheduled-transactions/revised-spec.md). This resulted in a new protobuf and a new sdk version

- Pull in sdk version `2.0.5-beta.7` which uses new protobuf into data-generator, monitor and test modules
- Update ScheduleClient to no longer sign inner transaction but outer
- Update ScheduleScenario to handle verifications, including additional signatures that aren't required
- Update monitor Schedule transaction logic
- Update monitor publish logic to handle transctions with nodes set
- Add HCS massage publish in background to reduce likelihood of stale data for mirror 

**Which issue(s) this PR fixes**:
Fixes #1822 and #1821 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-13 21:18 UTC, xin-hedera requested changes

2021-04-13 21:18 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        log.info("Schedule {} was confirmed to be executed by network state", scheduleId);
log message does not match context

2021-04-13 21:18 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        log.debug("Executed transaction {}.", scheduledTransactionId);
1. `scheduledTransactionId` won't be null
2. should get `scheduledTransactionID` from the receipt of `ScheduleCreate` or `ScheduleSign` transaction

2021-04-13 21:18 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        assertThat(scheduleInfo.signatories).isNotEmpty();
redundant as line 436 is a superset of this assert

2021-04-13 21:18 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                                                     String memo, KeyList innerSignatureKeyList) throws ReceiptStatusException,
nit: with the new design, we always sign `ScheduleCreate` or `ScheduleSign` transaction, so better rename `innerSignatureKeyList`

2021-04-14 03:15 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +            scheduleCreateTransaction.setPayerAccountId(getOperatorId());
Yeah that's a better approach.

2021-04-14 03:25 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                                                     String memo, KeyList innerSignatureKeyList) throws ReceiptStatusException,
Will change to `signatureKeyList`

2021-04-14 03:36 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        log.info("Schedule {} was confirmed to be executed by network state", scheduleId);
Will update

2021-04-14 03:37 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        log.debug("Executed transaction {}.", scheduledTransactionId);
Missed this, will update

2021-04-14 03:38 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        assertThat(scheduleInfo.signatories).isNotEmpty();
Will remove the `isNotEmpty()` check

2021-04-14 03:41 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +            scheduleCreateTransaction.setPayerAccountId(getOperatorId());
Actually, not sure why I changed this.
The network handles setting payer of transaction to payer account of Schedule if not provided.
I should be able to just revert.

2021-04-14 16:25 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
> +            scheduleCreateTransaction.setPayerAccountId(getOperatorId());
Updated

2021-04-14 16:25 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        log.debug("Executed transaction {} w {} signatures.", transactionId, keyList == null ? 0 : keyList.size());
Fixed

2021-04-14 16:25 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        log.info("Schedule {} was confirmed to be executed by network state", scheduleId);
Updated

2021-04-14 16:26 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        log.debug("Executed transaction {}.", scheduledTransactionId);
Fixed here and throughout the class

2021-04-14 16:26 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        assertThat(scheduleInfo.signatories).isNotEmpty();
Removed

2021-04-14 16:26 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
> +                                                     String memo, KeyList innerSignatureKeyList) throws ReceiptStatusException,
Renamed

2021-04-14 16:47 UTC, ijungmann requested changes
Looks good, one small nit.

2021-04-14 16:47 UTC, ijungmann commented on hedera-mirror-datagenerator/pom.xml
> +            <version>2.0.5-beta.7</version>
It seems like we should move this into a variable at this point,

2021-04-14 17:41 UTC, Nana-EC commented on hedera-mirror-datagenerator/pom.xml
> +            <version>2.0.5-beta.7</version>
There is a variable. I had to move away from that temporarily since the performance tests in the test module also use the sdk but haven't been updated.
Eventually we'll rip the performance tests out in favor of the monitor.
I believe it's missing multiple subscribe user support and then we should be good

2021-04-14 20:48 UTC, steven-sheehy approved these changes
LGTM

2021-04-14 20:51 UTC, xin-hedera approved these changes
LGTM

2021-04-14 23:58 UTC, ijungmann approved these changes

2021-04-15 02:04 UTC, merged