Optimize resources for kubernetes deployment
hashgraph/hedera-mirror-node pull request #1853
Opened 2021-04-16 15:19 UTC by xin-hedera

**Detailed description**:

- Adjust importer resources limit to reach 10k tps ingestion
- Increase MaxRAMPercentage for grpc, importer, and monitor containers
- Fix OOM in PgCopy and adjust default buffer size for PGCopyOutputStream
- Reduce default queueCapacity to 10

**Which issue(s) this PR fixes**:
Relates to #1312 
Fixes #1830 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-04-16 16:30 UTC, Nana-EC submitted a review, later dismissed
Looks good.
Though I'm wondering if we should incorporate the rcd files from your tests into the importer performance tests

2021-04-16 18:36 UTC, steven-sheehy requested changes

2021-04-16 18:36 UTC, steven-sheehy commented on charts/hedera-mirror/values-prod.yaml
> +    JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=70
This shouldn't just be for values-prod, it should be the default in regular deployments. In fact, I would suggest we add this default to the docker image itself as it also would be needed via docker-compose or docker standalone. You can do so via jib's `jvmFlags` property.

2021-04-16 18:36 UTC, steven-sheehy commented on charts/hedera-mirror-grpc/templates/deployment.yaml
> +            {{- range $name, $value := .Values.envs }}
With my suggestion to push the flags into the image, I think we can remove this. My upcoming PR will add a way to add extra env variables so in case we need to change the default in the image we can do so.

2021-04-16 18:38 UTC, steven-sheehy commented on charts/hedera-mirror/values-prod.yaml
> +    JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50
Why 50%? Does monitor have more non-heap allocations than the other processes? I would think they'd all be around 70%

2021-04-16 18:47 UTC, xin-hedera commented on charts/hedera-mirror/values-prod.yaml
> +    JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50
monitor's default memory limit is 512M, 70% heap may cause OOM as what's left for nonheap is small

2021-04-16 18:52 UTC, xin-hedera commented on charts/hedera-mirror-grpc/templates/deployment.yaml
> +            {{- range $name, $value := .Values.envs }}
sure, I'll revert these changes since we will set `MaxRAMPercentage` in the docker images.

2021-04-16 19:07 UTC, steven-sheehy commented on charts/hedera-mirror/values-prod.yaml
> +    JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50
We probably haven't tested monitor in containers to know if the resources limits are good.

2021-04-16 19:50 UTC, xin-hedera commented on charts/hedera-mirror/values-prod.yaml
> +    JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50
I did saw OOM with monitor when memory limit is low and MaxRAMPercentage is high.

For network monitoring, 512M and 50% should be good enough.

For performance testing at high TPS (~2k), Tom usually sets monitor memory limit to 4-5G. We can test to find the optimal configuration, perhaps about 2G memory limit with MaxRAMPercentage of 70%.

2021-04-19 16:38 UTC, ijungmann approved these changes

2021-04-20 18:34 UTC, steven-sheehy approved these changes
LGTM

2021-04-20 19:51 UTC, Nana-EC approved these changes
LGTM

2021-04-20 19:52 UTC, merged