Automate release process
hashgraph/hedera-mirror-node pull request #1870
Opened 2021-04-21 16:15 UTC by xin-hedera

**Detailed description**:
This PR adds a github actions workflow to automatically start the release process when a milestone is closed. It implements the steps described in #344.

In addition, the workflow creates a PR to merge the changes of the release branch to master. If there are patch milestones,  the PR will be updated when the patch milestones close.

**Which issue(s) this PR fixes**:
Fixes #344 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-21 16:22 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
chart version is inferred from the current chart version in pom based on whether it's a patch release:

1. for a minor release, increase the minor of the chart version in master pom.xml by 1
2. for a patch release, replace the minor version of the chart version in pom.xml in the release branch

This relies on master having an up-to-date chart version in pom, and won't work for a major release.

Alternatively, we can set both `release.version` and `release.chartVersion` to the version in the milestone title.

2021-04-21 16:23 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          git reset --hard ${RELEASE_BRANCH}
this keeps the current branch name as `master` and resets its HEAD to `RELEASE_BRANCH`'s head, it's required for the `create-pull-request` action to work.

2021-04-21 20:53 UTC, Nana-EC commented on .github/workflows/auto-release.yml
> +        description: 'Version'
nit: highlight here and for chart version that it should be semantic version e.g. `<major>.<minor>.<patch>`

2021-04-21 20:53 UTC, Nana-EC commented on .github/workflows/auto-release.yml
> +        description: 'PreRelease Identifier, e.g., alpha1, rc1'
q: Since required, what value should this take for full release e.g. `0.68.0`?
Is this denoted by the no white space after 'e.g.' and before the ','

2021-04-21 20:53 UTC, Nana-EC commented on .github/workflows/auto-release.yml
> +      - name: Reset Master to Release Branch
Q: How does this handle release version updates? e.g. `0.68.0` to `0.68.1`

2021-04-21 20:53 UTC, Nana-EC commented on .github/workflows/auto-release.yml
> +        run: ./mvnw clean package -N -P=release
Q: In the example PR, this stage seemed to update the sub chart versions also.
Is that a regression or an issue that could happen in our current branch?

2021-04-21 20:53 UTC, Nana-EC commented on .github/workflows/auto-release.yml
> +          git reset --hard ${RELEASE_BRANCH}
Is that to say if the current branch is `release/0.68` that it'll work and won't try to create a PR into master instead?

2021-04-21 20:57 UTC, Nana-EC requested changes
A nit and some request clarification on release branches case

2021-04-21 21:39 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          git reset --hard ${RELEASE_BRANCH}
the current branch will be switched to `master` in this step; suppose the release branch is `release/0.68`, the second line will change the branch to point to `HEAD` of `release/0.68`.

By doing this, the `create-pull-request` actions detects there are differences between the local `master` and the remote `master`, so it'll create a new branch `create-pull-request/release/0.68` off the HEAD and create a pull request to merge `create-pull-request/release/0.68` to `master.

2021-04-21 21:41 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        description: 'PreRelease Identifier, e.g., alpha1, rc1'
full release is triggered by closing the milestone. The manual triggering is for prerelease so the field is marked as `required`.

2021-04-21 21:45 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +      - name: Reset Master to Release Branch
1. Create a milestone for the patch release, e.g., `0.68.1`
2. Work on PRs of the milestone, and of course merge those PRs to branch `release/0.68`
3. Manually trigger the workflow for prerelease, e.g., `version=0.68.1`, `chartVersion=0.25.1`, `preReleaseIdentifier=rc1`
4. When everything looks good, close the milestone to trigger the workflow to do the full release.

2021-04-21 21:58 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        run: ./mvnw clean package -N -P=release
it's a regression in our master.

https://github.com/hashgraph/hedera-mirror-node/blob/0a16907c0ba55b35ece10a7628ce31199e8d8c00/charts/hedera-mirror/Chart.yaml#L21-L29

versions like these match the regex in the pom and will be accidentally replaced.

2021-04-22 17:30 UTC, steven-sheehy requested changes

2021-04-22 17:30 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          cat $RELEASE_NOTES_FULLNAME $TMPFILE >> $CHANGELOG
The Changelog header should always stay at the top. Maybe change it to `# Hedera Mirror Node Changelog`. The subsequent entries should be h2 in the format `## x.y.x (2021-04-22)`.

2021-04-22 17:30 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          commit_message: Bump version to ${{ env.RELEASE_VERSION }}
Should include the `v`, so maybe use `RELEASE_TAG`

2021-04-22 17:30 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +      - name: Reset Master to Release Branch
We don't generally do pre releases for patch versions. Does it still work if you directly go from 0.68.0 to 0.68.1?

2021-04-22 17:30 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          draft: ${{ github.event_name == 'milestone' }}
We should always do draft releases as we need to upload the artifacts manually (for now) before publishing.

2021-04-22 17:30 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          title: Merge version bump for ${{ env.RELEASE_VERSION }}
We don't always want to merge version bumps into master. For example, if a customer need an emergency fix v0.16.1 we shouldn't merge that into master that's on 0.32.x. It should only ever create a PR when you initially create that release branch.

In fact, I think the version bump PR for master shouldn't bump it to the same version as the newly created release branch but to the next minor version snapshot: `0.33.0-SNAPSHOT`

2021-04-22 17:30 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          bodyFile: ${{ env.RELEASE_NOTES_FULLNAME }}
As noted in the issue, this should also prepend the milestone body which should contain descriptive text about the release. This same text should also go into the changelog. Later, once we remove artifacts and directly publish non-draft releases this would fully automate the release.

2021-04-23 14:46 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +      - name: Reset Master to Release Branch
yes 0.68.0 -> 0.68.1 without pre releases should work.

2021-04-23 14:47 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +      preReleaseIdentifier:
sure for the flexibility of different prerelease identifiers

2021-04-23 14:52 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +      - name: Cache Maven packages
it probably downloads way more than just the replacer plugin and its dependencies.

Running the command with empty ~/.m2/repository shows > 200 downloads

2021-04-23 14:56 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +            "milestone" )
one benefit of a single step with the bash script is it detects unsupported events.

separating it will have more steps and even more if we support additional events in the future. also the separated steps's order matters.

2021-04-23 14:56 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          draft: ${{ github.event_name == 'milestone' }}
sure

2021-04-23 15:02 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          title: Merge version bump for ${{ env.RELEASE_VERSION }}
agree on the version should be the next minor version snapshot

If we only create a PR when the release branch is created, we will miss the changelog update which only happens when a milestone is closed

The workaround for the example of PR trying to merge emergent v0.16.1 into master at 0.32.x is we can close the PR.

2021-04-23 20:32 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +      - name: Cache Maven packages
Perhaps then just adjust the cache key to be just the top level pom.xml then since it's a non-recursive command.

2021-04-23 20:54 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +            "milestone" )
We don't need to detect unsupported events as the list of events is hardcoded at the top. We should use github conditionals since they are more appropriate in a github actions workflow. They should also result in less lines of code.

2021-04-26 15:58 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +        run: exit 1
Add an echo that workflow dispatch not supported for GA release and that the milestone should be closed instead.

2021-04-26 16:31 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          omitBody: ${{ github.event_name == 'workflow_dispatch' }}
Don't think this is necessary since GITHUB_RELEASE_NOTES will be empty regardless. In the future, we might want milestones for a long running pre-release.

2021-04-26 16:33 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        run: exit 1
sure

2021-04-26 16:38 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          omitBody: ${{ github.event_name == 'workflow_dispatch' }}
true. `bodyFile` will be empty when triggered by `workflow_dispatch` and won't cause file not found error.

2021-04-26 16:56 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          title: Merge version bump for ${{ env.RELEASE_VERSION }}
There shouldn't be a changelog for pre-release just like our github release body is empty for pre-releases. Thus, a PR should only be created if event is milestone closing. Since we associate issues and PRs to milestones, only for closing that milestone do we need a changelog updated. So there needs to be an if statement for creating a PR, maybe not for creating release branch but for closing milestone.

2021-04-26 17:24 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          title: Merge version bump for ${{ env.RELEASE_VERSION }}
It's needed if we want the version bump to the next snapshot when we kick off the prerelease. Otherwise, we should only create the PR when closing the milestone.

2021-04-26 20:52 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          title: Merge version bump for ${{ env.RELEASE_VERSION }}
It looks to have the intelligence that if the release branch is not ahead of master (`git rev-list --right-only --count origin/master...create-pull-request/release/0.33`), the PR will not be created.

However, we always do squash and merge for PRs, the previous check will most likely report the release branch is ahead of master even though there is no code change in the release branch in case a previous PR with the same minor snapshot version is merged.

I can test it, if it doesn't work as we hope, I'll change it to create PR only when milestone closes.

2021-04-26 22:19 UTC, steven-sheehy requested changes

2021-04-26 22:19 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          echo "GITHUB_RELEASE_NOTES=${GITHUB_RELEASE_NOTES}" >> $GITHUB_ENV
This is quite verbose and hard to grok. Can't we just sed remove the old header first then use a template string. Something like this:
```bash
$ cat > CHANGELOG.md <<EOF
# Hedera Mirror Node Changelog

## ${RELEASE_VERSION} (${RELEASE_DATE})

${DESCRIPTION}
${RELEASE_NOTES}

${CHANGELOG_PREVIOUS}
EOF
```

Same concept for release notes.

2021-04-26 22:19 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +        if: ${{ steps.release_semver.outputs.patch != 0 && steps.chart_semver.outputs.prerelease == '' }}
I'm not sure why we're doing this if check. The inputs for the chart version should always come from user input. We shouldn't need to auto-bump if `0.32.1`.

2021-04-27 13:54 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        if: ${{ steps.release_semver.outputs.patch != 0 && steps.chart_semver.outputs.prerelease == '' }}
For when a patch release milestone is closed which is immediately after the previous GA release in the branch.

Since the milestone title does not have the chart version, this step is needed to get the chart version for the patch release.

As I'm moving to milestone_dispatch only, this will be no longer needed.

2021-04-28 17:52 UTC, xin-hedera commented on pom.xml
> +                            </execution>
execution to replace versions when the properties are defined in maven command line

2021-04-28 17:54 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          bump: preminor
bumping `preminor` generates a `next-version` of `0.34.0-0` from either `0.33.0-rc1` (with prerelease) or `0.33.0`

2021-04-28 17:55 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        if: ${{ contains(steps.version_parser.outputs.version, '-') }}
`semver-action` does not have `prerelease` as output

2021-04-28 17:58 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +              exit 0
extract milestone number and description when the title matches the version from input

2021-04-28 17:59 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +            echo "CREATE_PULL_REQUEST=true" >> $GITHUB_ENV
when a release branch is created, set `CREATE_PULL_REQUEST`

note the workflow creates a PR when either a release branch is created or it's a GA release

2021-04-28 18:01 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        uses: xin-hedera/release-notes-generator-action@v3.1.5-rc1
it's a fork to enable providing milestone number from environment variable `MILESTONE_NUMBER`

2021-04-28 18:01 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          CHANGELOG_PREVIOUS=$(sed 'N; N; 0,/^'"${CHANGELOG_TITLE}"'\n.*\n/s///' $CHANGELOG)
multiline sed to remove the title and the empty line after it

2021-04-28 18:03 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          title: ${{ fromJSON(format('["Merge changes from {0}", "Bump versions for v{1}"]', env.RELEASE_BRANCH, env.NEXT_VERSION_SNAPSHOT))[env.PRERELEASE == 'true'] }}
it's tricky, github actions do not support ternary. What this does is set the PR title to

1. Bump versions for v0.34.0-SNAPSHOT, if the input version is a prerelease version, e.g., 0.33.0-rc1
2. Merge changes from release/0.33, if the input version is a GA release, e.g., 0.33.0

2021-04-28 20:16 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          response=$(curl -s -H "$GITHUB_HEADER" $MILESTONE_BASE_URL)
by default, github only returns the open milestones

2021-04-28 20:16 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +              MILESTONE_DESCRIPTION=$(curl -s -H "$GITHUB_HEADER" $MILESTONE_BASE_URL/$MILESTONE_NUMBER | jq -r '.description')
need to re-get description in a separate call to support multi-line description

2021-04-28 21:49 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          echo | cat $MILESTONE_DESCRIPTION_FILE - $RELEASE_NOTES_FULLNAME > $GITHUB_RELEASE_NOTES
add an empty line after the milestone description

2021-04-28 21:50 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +              curl -s -H "$GITHUB_HEADER" $MILESTONE_BASE_URL/$MILESTONE_NUMBER | jq -r '.description' | sed 's/\r$//' > $MILESTONE_DESCRIPTION_FILE
updated to save milestone description to a temporary file to better support multiline string

also use sed to remove `\r\n` in the description

2021-04-29 15:55 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          passphrase: ${{ secrets.GPG_PASSPHRASE }}
Enable gpg signing for two purposes:

1. Comply with our commit signing policy
2. Give exemption to the user of the gpg key so the workflow can directly push to release branched

2021-04-30 17:00 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          title: ${{ fromJSON(format('["Merge changes from {0}", "Bump versions for v{1}"]', env.RELEASE_BRANCH, env.NEXT_VERSION_SNAPSHOT))[env.PRERELEASE == 'true'] }}
It might be clearer to set a `PR_TITLE` env variable in previous steps that set the `CREATE_PULL_REQUEST` variable.

2021-04-30 17:07 UTC, steven-sheehy requested changes

2021-04-30 17:07 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +        if: ${{ env.CREATE_PULL_REQUEST == 'true' }}
I think we should move all CREATE_PULL_REQUEST==true steps to a separate job that depends upon the previous. Then we can have a single if at the top of that job.

2021-04-30 17:07 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +        if: ${{ env.PRERELEASE != 'true' }}
Would be clearer to just check MILESTONE_NUMBER is populated. Reason is we may want to have a pre-release milestone in the future.

2021-04-30 17:13 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        if: ${{ env.PRERELEASE != 'true' }}
sure

2021-04-30 17:14 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        if: ${{ env.CREATE_PULL_REQUEST == 'true' }}
good idea. that'll make the logic clearer.

2021-04-30 17:24 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        if: ${{ env.CREATE_PULL_REQUEST == 'true' }}
may have to duplicate some steps though (checkout, import gpg, switch branch), reason is jobs don't share workspace. not sure if that also apply to jobs in the same workflow or not, will test it.

2021-05-03 03:58 UTC, ijungmann commented on .github/workflows/auto-release.yml
> +              curl -s -H "$GITHUB_HEADER" $MILESTONE_BASE_URL/$MILESTONE_NUMBER | jq -r '.description' | sed 's/\r$//' > $MILESTONE_DESCRIPTION_FILE
I agree, this seems overly complex

2021-05-03 03:59 UTC, ijungmann requested changes
Looks really good to me, the one complex step I'd agree should be simplified, but otherwise really good work.

2021-05-03 15:17 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +        if: ${{ env.PRERELEASE != 'true' }}
changed to check `steps.milestone.outputs.number`.

However, support of pre-release milestone is incomplete. In the future, if we change the process to have optional pre-release milestone, we have to get support from the milestone actions to just check if a milestone matching the title exists or not. Otherwise, for pre-releases without milestones, the action will create a new PR for it and then the job will close it later.

2021-05-03 15:20 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          git fetch origin $RELEASE_BRANCH:$RELEASE_BRANCH
need this step to fetch remote branch and have it in local .git/refs/heads/$RELEASE_BRANCH

2021-05-03 15:36 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +        if: ${{ env.PRERELEASE != 'true' }}
The assumption is that we would have milestones for such pre-releases.

2021-05-03 16:42 UTC, ijungmann approved these changes
LGTM

2021-05-03 21:23 UTC, Nana-EC approved these changes
LGTM

2021-05-03 21:48 UTC, steven-sheehy approved these changes
LGTM. One possible optimization

2021-05-03 21:48 UTC, steven-sheehy commented on .github/workflows/auto-release.yml
> +          git reset --hard $RELEASE_BRANCH
Believe this can be omitted if you pass `ref` to checkout action.

2021-05-03 21:59 UTC, ijungmann approved these changes

2021-05-03 22:04 UTC, xin-hedera commented on .github/workflows/auto-release.yml
> +          git reset --hard $RELEASE_BRANCH
yup.

then the first line will be `git checkout master`. agree it'll be easier to read.

2021-05-03 22:07 UTC, merged