Bump hedera-protobuf-java-api to 0.13.0-rc-1
hashgraph/hedera-mirror-node pull request #1871
Opened 2021-04-21 17:12 UTC by Nana-EC

**Detailed description**:
hedera-protobuf-java-api has released 0.13.0-rc-1, mirror node is on 0.13.0-alpha.2

- Updates transaction response codes for scheduled scenarios
- Adds `description` and `stake` columns to `address_book_entry` table and domain class
- Updates `AddressBookServiceImpl` to handled `NodeAddresses` proto with and without `ServiceEndpoint`s. In the case with service endpoints we flatten the map and create an `AddressBookEntry` for each `ServiceEndpoint`
- Updated `AddressBookServiceImplTest` with new coverage

**Which issue(s) this PR fixes**:
Fixes #1854 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-04-21 17:50 UTC, steven-sheehy commented
To reduce duplication in our tables, we will need to create an addressbookentryendpoint. Then migrate existing data by merging by node id.

2021-04-23 03:01 UTC, Nana-EC commented
> To reduce duplication in our tables, we will need to create an `address_book_entry_endpoint` table. Then migrate existing data by merging by node id.

Just seeing this. Came to the same conclusion and have been in the thick of getting the address_book_entry to service_endpoint mapping working with Hibernate.

Next commit will include this and the migration once I get around a serialization bug I'm seeing.

2021-04-27 16:55 UTC, steven-sheehy requested changes

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_account_id     bigint      null
Should be `node_id`

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    on address_book_service_endpoint (consensus_timestamp, node_account_id);
Redundant indexes already covered by primary key.

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +
We need to be collapsing duplicates by node id from address_book_entry for older entries.

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_account_id     bigint      null
nit: sort

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    ipAddressByteString.toStringUtf8(),
This is parsing wrong. The old IP field was a UTF-8 string like "127.0.0.1" (including the periods) that was mistakenly encoded as a byte array. The new IP field is an actual byte array (no periods) encoded in octets in left to right (network byte) order. You should be able to parse it using `InetAddress.getByAddress(ip)`.

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            builder.add(parseNodeAddressEntries(nodeAddressProto, consensusTimestamp));
We need to be collapsing duplicates by node id to normalize the data. This should apply to both entries populated with service endpoints and without. It's possible the address book is received with the following data permutations:

1) Only deprecated ip/port populated with multiple entries per node
2) Both deprecated ip/port populated and service endpoints populated (with a list of one) and multiple entries per node
3) Only service endpoints populated and only one entry per node

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    add primary key (consensus_timestamp, node_account_id, ip_address_v4);
Primary key should include port as we have both TLS and plaintext ports exposed on node proxies.

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookEntry.java
>      private Long id;
We should remove ID and the primary key should become (consensus_timestamp, node_id) after we migrate to collapse duplicates.

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookEntry.java
> +    private Long stake;
nit: sort

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                parseNodeAddressWithServiceEndpoints(nodeAddressProto, consensusTimestamp);
We should consolidate to one parse method as Hedera might populate both endpoints and deprecated for awhile so people can transition to the new fields.

2021-04-27 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookServiceEndpoint.java
> +    private int port;
Port becomes part of `Id`. Not sure if there's a way to tell JPA that every field in the class is part of the key and to skip the nested Id.

2021-04-28 16:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    ip_address_v4       varchar(20) not null,
I wanted to capture the space the actual inet type in postgres uses - currently 19 chars (so I rounded up) in case we ever decided to capture the subnet in addition to the host - https://www.postgresql.org/docs/9.1/datatype-net-types.html
I actually wanted to use inet type here but hadn't figured out an easy way to handle the conversion to and from db in hibernate.

2021-04-28 16:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            builder.add(parseNodeAddressEntries(nodeAddressProto, consensusTimestamp));
Gotcha. Yeah I missed this.
Will collapse so each address book only adds a single row to the `address_book_entry` table for a a nodeId but captures all the unique endpoints for that timestamp in the `address_book_service_endpoint` table

2021-04-28 16:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            builder.add(parseNodeAddressEntries(nodeAddressProto, consensusTimestamp));
Notably the assumption is any nodeId duplicates on differ in the IP addresses. If there's inconsistencies on things like `publicKey`, nodeCertHash` there's no way for us to resolve this with information.

2021-04-28 16:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            builder.add(parseNodeAddressEntries(nodeAddressProto, consensusTimestamp));
If a single node has multiple public keys, that would be a huge problem outside the scope of mirror node.

2021-04-28 16:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    ip_address_v4       varchar(20) not null,
But we're not storing subnets. The information we have is just a single 32 bit IP. There's no netmask in the protobuf so it's implicitly netmask 32 and we don't need that info. If we want to use inet that's fine, but if we're using varchar it should be exactly the max size of the data without padding for a subnet that we will never have.

2021-04-28 20:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    ip_address_v4       varchar(20) not null,
Can change to `varchar(15)` for now, will circle back if I get the inet type working.

2021-04-28 23:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add primary key (consensus_timestamp, node_account_id);
Can update it. 
`node_id` so far has always ben set in files 101 and 102, so shouldn't be a need for a default. 
`node_account_id` is what has been missing for file 102, since the value is in the `memo` field.

2021-04-28 23:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on address_book_entry (consensus_timestamp, node_account_id);
Left over, will remove

2021-04-28 23:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on address_book_service_endpoint (consensus_timestamp, node_account_id);
Copied and modified `address_book_entry` indexes, will update those also.

2021-04-29 00:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add primary key (consensus_timestamp, node_account_id);
Node id is a somewhat recent addition. The mainnet initial address book doesn't have it, for example. So we need to take this scenario into account.

2021-04-29 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add primary key (consensus_timestamp, node_account_id);
Yeah, realized that also. I've updated the migration logic to capture this also.
Verified against a mainnet copy that it populates things but there might be a reverse approach.
I sided with relying on `node_id` over `memo` parsing where possible

2021-04-29 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on address_book_entry (consensus_timestamp, node_account_id);
Removed

2021-04-29 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on address_book_service_endpoint (consensus_timestamp, node_account_id);
Removed

2021-04-29 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    ip_address_v4       varchar(20) not null,
Updated

2021-04-29 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_account_id     bigint      null
Updated

2021-04-29 16:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    on address_book_service_endpoint (consensus_timestamp, node_account_id);
Removed

2021-04-29 16:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +
Adding a a collapsing query. Verified against mainnet addressBook copy

2021-04-29 16:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    ipAddressByteString.toStringUtf8(),
Updated. Mixed this up in testing.

2021-04-29 17:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            builder.add(parseNodeAddressEntries(nodeAddressProto, consensusTimestamp));
Updated logic to parse for all scenarios.
Also added migration cases for each.
Need to move this case scenario logic breakout to `AddressBookServiceImplTest` also so it's cleaner

2021-04-29 17:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    add primary key (consensus_timestamp, node_account_id, ip_address_v4);
Updated

2021-04-29 17:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                parseNodeAddressWithServiceEndpoints(nodeAddressProto, consensusTimestamp);
Updated

2021-04-29 17:17 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookServiceEndpoint.java
> +    private int port;
Moved port to Id
Probably best to be explicit so someone doesn't accidentally add a new column to the Id and we miss it

2021-04-30 06:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_account_id     bigint      null
Sorted

2021-04-30 06:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookEntry.java
>      private Long id;
Removed id and updated primary key

2021-04-30 06:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookEntry.java
> +    private Long stake;
Sorted

2021-04-30 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (nodeId == 0 && nodeEntityId.getEntityNum() != INITIAL_NODE_ID_ACCOUNT_ID_OFFSET) {
This probably needs to be more precise. The relationship holds true for early and current address books but might not remain.
Scale it down to entities below 100 maybe, or maybe only for `consensusTimestamp == 1` since that's the initial address book. Some tests would be broken but can fix those

2021-04-30 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        String ip = nodeAddressProto.getIpAddress().toStringUtf8();
nit: used to be more logic here. I can move this into the method call instead of storing the variables

2021-04-30 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (StringUtils.isNotBlank(nodeAddressProto.getIpAddress().toStringUtf8())) {
nit: could move this check into the `getAddressBookServiceEndpoint` that takes a `NodeAddress`.
Have ti return a null in the blank case and only add to `serviceEndpoints` if not null

2021-04-30 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    ip_address_v4       varchar(15) not null,
nit: tried to make this an `inet` type but it then required an extra conversion which seems to add more complexity.
Can always circle back to this in a future migration or not.

2021-04-30 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +-- Support proto updates in 0.13.0-rc.1 with respect to address book end points
This is a long migration, I like to keep each file short and easy to follow its purpose, sort of like a class. 
I'm open to splitting it out into 2 files if it's challenging to follow.
One that create the `address_book_service_endpoint` and populates it.
The other that modifies, collapses the `address_book_entry` table.
This would cause the Migration tests to require some refactoring also

2021-04-30 15:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    add primary key (consensus_timestamp, node_id, ip_address_v4);
nit: I'm missing the `port` column here. Will add it

2021-04-30 15:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +-- Support proto updates in 0.13.0-rc.1 with respect to address book end points
I would keep it as is. More important than single responsibility principle is that they be grouped together for transaction atomicity.

2021-04-30 15:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (nodeId == 0 && nodeEntityId.getEntityNum() != INITIAL_NODE_ID_ACCOUNT_ID_OFFSET) {
There might have been an update after initial but still without nodeId. Safest to just say less than 20 since we know that to be the case now. We don't know what will happen beyond 20.

2021-04-30 19:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +-- Support proto updates in 0.13.0-rc.1 with respect to address book end points
Works for me

2021-04-30 20:04 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (nodeId == 0 && nodeEntityId.getEntityNum() != INITIAL_NODE_ID_ACCOUNT_ID_OFFSET) {
Adopted the < 20 rule

2021-04-30 20:59 UTC, steven-sheehy requested changes

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookServiceEndpoint.java
> +@Builder(toBuilder = true)
Builder not useful here, especially as Id doesn't have it. Would omit.

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    drop column if exists id;
Does this auto-drop the sequence?

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    drop column if exists id;
Please update `alterSchema.sql` to remove sequence

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .synchronizedSetMultimap(HashMultimap.create());
Synchronization wrapper not necessary as it's only used within this method.

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                nodeAddressProto.getIpAddress().toStringUtf8(),
```suggestion
                ip,
```

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            serviceEndpoints.add(deprecatedServiceEndpoint);
We should not add both deprecated endpoints and service endpoints, especially if we're not using a set to collapse duplicate ip/port pairs. This fails the scenario I mentioned in a previous comment `Both deprecated ip/port populated and service endpoints populated (with a list of one) and multiple entries per node`. Changing to a `LinkedHashSet` (return Collection) and adding a test to verify collapsing should suffice.

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        // create an AddressBookServiceEndpoint for every ServiceEndpoint found, ignore IP duplicates
> ignore IP duplicates

Not sure what this alludes to as there's no duplicate check here. Nor should there be as we can have the same IP multiple times as long as each has a distinct port.

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var nodeEntityId = nodeAddressProto.getNodeAccountId() == AccountID.getDefaultInstance() ?
Use `hasNodeAccountId()`. Would also suggest inverting logic:
```java
EntityId nodeAccountId = nodeAddressProto.hasNodeAccountId() ? EntityId.of(nodeAddressProto.getNodeAccountId()) : memoNodeEntityId;

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var nodeEntityId = nodeAddressProto.getNodeAccountId() == AccountID.getDefaultInstance() ?
`var nodeAccountId`

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        EntityId memoNodeEntityId = StringUtils.isEmpty(memo) ? EntityId.EMPTY : EntityId
`memoNodeAccountId`

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            }
```suggestion
            nodeAddressBookEntryMap.putAll(addressBookEntry, addressBookServiceEndpoints);
```

2021-04-30 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        });
This collapsing logic is a bit complex and error prone. For example, what happens if for some reason two address book entries have the same `node_id`, `ip` and `port`, but another field varies like `description`? A duplicate entry will be created since you're comparing by the entire entry. I would suggest changing `AddressBookEntry.serviceEndpoints` to a `Set`, then:

```java
Map<Long, AddressBookEntry> addressBookEntries = new LinkedHashMap<>(); // node id to entry

for (NodeAddress nodeAddressProto : nodeAddressBook.getNodeAddressList()) {
  long nodeId = getNodeId(nodeAddressProto);
  AddressBookEntry addressBookEntry = addressBookEntries.computeIfAbsent(nodeId, k -> getAddressBookEntry(nodeAddressProto, consensusTimestamp));

  List<AddressBookServiceEndpoint> serviceEndpoints = getAddressBookServiceEndpoints(nodeAddressProto, consensusTimestamp);
  addressBookEntry.getServiceEndpoints().addAll(serviceEndpoints);
}
```

2021-04-30 21:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_id             bigint      null,
Removing it was just a thought. We can keep it. It should be not null though.

2021-04-30 21:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +set node_account_id = node_id + 3
We control the timestamp of 1 for the initial addressBook. So shouldn't matter the environment.
Though your recommendation is fair, I was trying to avoid parsing the memo field too often.
Will look into this

2021-04-30 21:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +alter table if exists address_book_entry
Had decided to opt for clear small steps given there were so many moving parts.
However, I can begin to combine them. Will use comments to capture anything unclear

2021-04-30 21:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        });
Good point on the `description` scenario.
I initially started off with `Map<Long, AddressBookEntry>` but was hoping to catch the duplicate serviceEndpoints also.
Will circle back on this

2021-04-30 21:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        });
Although if there are duplicate `NodeAddress` with differing values other than the IP isn't that a larger issue. 
In that case we still have no way of collapsing that into a single AddressBookEntry.
In fact I would expect that to be a requirement of the addressBook - other than IP and service endpoints all value should be the same no?

2021-04-30 22:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            }
Unfortunately this does not work how you think it would. I had this as my regional version, however the map will not preserve the addition of a key with an empty collection and it remains unchanged.
I believe this is related to the underlying MultiMap logic that allows you to not have to create an empty list first ensure that `map.get(addressBookEntry).add()` near produces a NullException

2021-04-30 22:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        // create an AddressBookServiceEndpoint for every ServiceEndpoint found, ignore IP duplicates
Left over comment prior to using a `SetMultimap` which handles ensuring all the values are distinct

2021-04-30 22:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_id             bigint      null,
Agreed, will add the `not null`

2021-04-30 22:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    drop column if exists id;
Yes

2021-04-30 22:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        });
In practice, it may never happen and if it does it is a bigger problem. But the point still stands that we can simplify much of this logic in this method down to the few lines above, making it more maintainable.

2021-04-30 22:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    node_id             bigint      null
Fixed

2021-04-30 22:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
>      node_id             bigint        null,
Fixed

2021-04-30 22:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
>      node_account_id     bigint        null,
Fixed

2021-04-30 22:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    node_id             bigint      null,
Fixed

2021-04-30 22:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AddressBookServiceEndpoint.java
> +@Builder(toBuilder = true)
Removed

2021-04-30 22:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +    drop column if exists id;
Removed

2021-04-30 22:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .synchronizedSetMultimap(HashMultimap.create());
Removed

2021-04-30 22:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                nodeAddressProto.getIpAddress().toStringUtf8(),
Had fixed this in a prior iteration but moved it out again because for the case of an empty IP I return null.

2021-04-30 22:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            serviceEndpoints.add(deprecatedServiceEndpoint);
This doesn't fail the scenario noted.
Added another test to explicitly verify as the other one I thought focused on the deduplication of AddressBookEntry domains.
See the `AddressBookServiceImplTestverifyDuplicateEndpointsPerNodeAddressAreCollapsed()`

2021-04-30 22:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        // create an AddressBookServiceEndpoint for every ServiceEndpoint found, ignore IP duplicates
Removed comment

2021-04-30 22:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var nodeEntityId = nodeAddressProto.getNodeAccountId() == AccountID.getDefaultInstance() ?
Updated

2021-04-30 22:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var nodeEntityId = nodeAddressProto.getNodeAccountId() == AccountID.getDefaultInstance() ?
Adopted

2021-04-30 22:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        EntityId memoNodeEntityId = StringUtils.isEmpty(memo) ? EntityId.EMPTY : EntityId
Adopted

2021-05-03 04:29 UTC, ijungmann requested changes
Looks good to me, I just have one question about the use of `var` everywhere in one class.

2021-05-03 04:29 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var fileDataEntries = 0;
I'm not clear what the need is for so many variables to be swapped to `var` in this file.

2021-05-03 05:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        });
Took a little refactoring but updated to adopt your suggestion.
`getNodeId` on it's own required getting `memo` and nodeAccountId` to ensure information was correct. To avoid redoing that logic I shared the logic in `getNodeIds` instead

2021-05-03 05:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +  and consensus_timestamp > 1;
Moved normalization to beginning

2021-05-03 05:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +set node_account_id = node_id + 3
Updated

2021-05-03 05:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
> +alter table if exists address_book_entry
Grouped into a supple alter at the end

2021-05-03 05:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var fileDataEntries = 0;
Made this change back when Sonos was reporting all the places it wanted var as Code smells. Only made the change to reduce those smells numbers.

2021-05-03 16:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var fileDataEntries = 0;
Ah, alright.  I'm generally against `var` in Java unless there's a major need for it, I've seen it abused to the point of being unmaintainable, but I won't hold it up if I'm the only dissenter. It seems like it's mostly contained in this class, which is less concerning.

2021-05-03 16:13 UTC, ijungmann submitted a review, later dismissed

2021-05-03 16:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var fileDataEntries = 0;
I'm not a big fan of it either, hence why I removed it as a source of code smells. But don't think we need to revert any of these.

2021-05-03 17:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        var fileDataEntries = 0;
Yep, we're all agreed al disliking var. Always felt like it was suspiciously hiding stuff from me 🤣 
In these cases it's not bad or I'd have reverted after Steven's fix

2021-05-03 17:56 UTC, steven-sheehy requested changes

2021-05-03 17:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                nodeAddressProto.getIpAddress().toStringUtf8(),
Still not fixed. It's just code duplication that should be fixed.

2021-05-03 17:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            Pair<Long, EntityId> nodeIds = getNodeIds(nodeAddressProto);
An alternative to this `getNodeIds()` is to just parse the duplicate address book entries regardless then use their extracted nodeID for the map and override with the one in the map if present. Am ok with current approach as well, just noting as I'm not a fan of `Pair`.

2021-05-03 17:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .memo(nodeIds.getRight().entityIdToString())
We should just directly copy the memo instead of assuming it is a node account ID. In the future, it will not be populated and we should just have an empty string.
```suggestion
                .memo(nodeAddressProto.getMemo().toStringUtf8())
```

2021-05-03 17:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .memo(nodeIds.getRight().entityIdToString())
Also double check what happens if it is empty. Can we still call toStringUtf8()?

2021-05-03 18:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .memo(nodeIds.getRight().entityIdToString())
True, at this stage we don't need to parse the memo so we can take as is.
When it's empty we just get an empty string. So we're all good

2021-05-03 19:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            Pair<Long, EntityId> nodeIds = getNodeIds(nodeAddressProto);
Yeah, the whole `getLeft()` , `getRight()` makes it illusive.
I'd prefer to return a single object actually.

In that case I could add the following inner class to AddressBookEntry which can serve the purpose

```java
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class NodeIds {
        private EntityId nodeAccountId;
        private Long nodeId;
    }
```

Then above becomes
```suggestion
            AddressBookEntry.NodeIds nodeIds = getNodeIds(nodeAddressProto);
```
`getLeft()` is replaced with `getNodeAccountId()` and `getRight()` is replaced with `getNodeId()`

2021-05-03 19:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .memo(nodeIds.getRight().entityIdToString())
Note that the field is `bytes` not a `string`. So it's not guaranteed to be empty string in the future. I would add some extra validation around null/empty.

2021-05-03 20:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            Pair<Long, EntityId> nodeIds = getNodeIds(nodeAddressProto);
Decided to leave as it to not add any more churn. It's also something that can be revisited is it comes up again

2021-05-03 20:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                .memo(nodeIds.getRight().entityIdToString())
Actually proto default is `ByteString.EMPTY`. Did add a test to surface this for when it's not set.
However, will add a check for if it's explicitly set to null

2021-05-03 20:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
>      id                  serial,
Removed

2021-05-03 21:01 UTC, steven-sheehy approved these changes
LGTM

2021-05-03 21:24 UTC, merged