Quote chart dependency version
hashgraph/hedera-mirror-node pull request #1872
Opened 2021-04-21 22:08 UTC by xin-hedera

**Detailed description**:
Quote chart dependency version so the release replacer will not update it.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-21 23:50 UTC, Nana-EC requested changes
Pondering if this workaround is best.
Might not need this change

2021-04-21 23:50 UTC, Nana-EC commented on charts/hedera-mirror-common/Chart.yaml
> +    version: "2.5.0"
I see the workaround but then it makes me wonder why in our regular replaces these versions aren't affected?
How does you other PR modify things to make these eligible for replacement?
If we get that down then maybe this workaround isn't needed

2021-04-22 00:00 UTC, Nana-EC commented on charts/hedera-mirror-common/Chart.yaml
> +    version: "2.5.0"
I see the context noted in the other PR now. We regressed by removing the quotations that we had around the range.

I believe Steven said he removed the version ranges to ensure `helm dep build` worked in CI/CD.
I'm presuming the quotation marks don't break that flow and it was just the version range.
In that case this is good.
Just verify that

2021-04-22 00:01 UTC, Nana-EC submitted a review, later dismissed
LGTM
Just verify that the quotes don't break the CI/CD flow noted in the PR that removed the quotes initially.

2021-04-22 04:20 UTC, ijungmann submitted a review, later dismissed

2021-04-22 15:06 UTC, steven-sheehy requested changes

2021-04-22 15:06 UTC, steven-sheehy commented on charts/hedera-mirror-common/Chart.yaml
> +    version: "2.12.1"
This is a bit of a hack that's will probably break in the future when someone forgets that quotes means don't replace version. We should tweak the replacer to look only for `version` and `appVersion` at the beginning of the line (e.g. no spaces) so it doesn't replace for dependencies. This should solve the problem more future proof fashion.

2021-04-22 17:34 UTC, Nana-EC commented on charts/hedera-mirror-common/Chart.yaml
> +    version: "2.12.1"
I pondered this also but I'm not sure it also scales.
See the recent bump - https://github.com/hashgraph/hedera-mirror-node/pull/1867/files
Open api and rosetta files all have version not at the beginning of the line. So they may be missed in the replacer.

Agreed regex is a preferred way as it's central. Hopefully there's a regex that works that isn't also brittle

2021-04-22 17:46 UTC, xin-hedera commented on charts/hedera-mirror-common/Chart.yaml
> +    version: "2.12.1"
there is another surprise:
```xml
<replacement>
    <token><![CDATA[(?<=\sversion: )[0-9a-zA-Z.-]+]]></token>
    <value>${release.chartVersion}</value>
</replacement>
<replacement>
    <token><![CDATA[(?<=(\s{3})version: )[0-9a-zA-Z.-]+]]></token>
    <value>${release.version}</value>
</replacement>
```

The two both update the unquoted dependency versions in `Chart.yaml`.

I end up using a separate execution for charts.yaml and restrict the regex to match start of line.

2021-04-22 17:56 UTC, steven-sheehy commented on pom.xml
> +                                        <regexFlag>MULTILINE</regexFlag>
It doesn't match across lines, does it?

2021-04-22 18:41 UTC, steven-sheehy commented on pom.xml
> +                                        <regexFlag>MULTILINE</regexFlag>
Ah, true. Forgot about that.

2021-04-22 18:41 UTC, steven-sheehy approved these changes

2021-04-22 19:51 UTC, ijungmann submitted a review, later dismissed

2021-04-22 20:51 UTC, ijungmann approved these changes

2021-04-22 20:53 UTC, Nana-EC approved these changes

2021-04-22 21:05 UTC, steven-sheehy approved these changes

2021-04-22 21:10 UTC, merged