Acceptance valid nodes
hashgraph/hedera-mirror-node pull request #1900
Opened 2021-04-27 21:48 UTC by Nana-EC

**Detailed description**:
Occasionally a node IP may change or go down.
In test environment this can be cumbersome with the current limitation of only 1 node in the acceptance test.

- Updated application yaml to accept list of nodes and value for network 
- Update SDKClient class to validate nodes. In prod cases also pull address book and validate those nodes

**Which issue(s) this PR fixes**:
Fixes #1852 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-30 15:13 UTC, steven-sheehy requested changes

2021-04-30 15:13 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                            "%d.%d.%d",
Think it would be less hacky to not use string conversion and just use `AccountId.newBuilder().setShardNum(nodeAccountId.getShardNum()...`.

2021-04-30 15:13 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                    nodeAddressProto.getIpAddress().toStringUtf8() + ":50211",
Use `nodeAddressProto.getPortno()`.

2021-04-30 15:35 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/application-default.yml
> +            host:
Sounds good

2021-04-30 15:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        var network = acceptanceTestProperties.getNetwork();
Not sure about this, I see both sides. I thought this approach might be more clear.
If you want to use custom nodes you just set network to OTHER
If it's not OTHER then we use default values based not eh network. 

Reason I went with this is because it's more clear looking at the config. 
With your suggested way (which is how it was before) in making nodes precede the network you could have network set to TESTNET but be using custom nodes.
This could be confusing or someone could easily miss when reading the config file.
Hmmm

2021-04-30 15:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                    nodeAddressProto.getIpAddress().toStringUtf8() + ":50211",
Yep, meant to circle back to this.

2021-04-30 15:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                            "%d.%d.%d",
Agreed

2021-04-30 15:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                    nodeAddressProto.getIpAddress().toStringUtf8() + ":50211",
Missed this. Will update

2021-04-30 15:43 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        if (network != AcceptanceTestProperties.HederaNetwork.OTHER) {
Was going back and forth on this. I think I'll make pulling address book a config value. Since in testing non prod environments the IPs are not always up to date and I hit some issues using those

2021-04-30 15:44 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        var network = acceptanceTestProperties.getNetwork();
I think it's less clear to specify OTHER for the TESTNET network. The network flag could potentially be used for auto populating other variables like mirror node address or other things in the future (we use it for bucket in importer, for example).

Also, the monitor already does it the way I recommend, so by doing it a different way for acceptance tests makes it inconsistent.

2021-04-30 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        if (network != AcceptanceTestProperties.HederaNetwork.OTHER) {
Optional property is a good idea. But that still leaves what the default should be. I think the fact that you found issues with the address book not being up to date is a good thing. That means we're testing more things and ops can then fix. That to me means the default should be to test more things, so pull the address book for all envs by default with an option to disable if you run into issues.

2021-04-30 16:17 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        this.client = getValidatedClient(networkMapToValidate, client);
should we just let the SDK validate the nodes in case testing against a specific node is not a requirement of the acceptance tests?

If so, we can remove the code which sets the node account ID for each transaction.

2021-04-30 16:53 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        singletonNodeId = Collections.singletonList(this.client.getNetwork().values().iterator().next());
This is just a nice to have for the SDK calls where you need a single node. Just optimizing to have one read in and ready to be used. Randomized could work

2021-04-30 16:55 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        var network = acceptanceTestProperties.getNetwork();
Sounds good. This was the initial way after all. Will make this change

2021-04-30 19:02 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/application-default.yml
> +            host:
Removed

2021-04-30 19:02 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> -    private String nodeId;
Updated

2021-04-30 19:02 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        var network = acceptanceTestProperties.getNetwork();
Updated

2021-04-30 19:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                    nodeAddressProto.getIpAddress().toStringUtf8() + ":50211",
Actually I remember now, SDK doesn't yet support this even in `2.0.5-beta.9`. There's supposed to be a new version coming out so when it does we can circle back

2021-04-30 19:04 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                    nodeAddressProto.getIpAddress().toStringUtf8() + ":50211",
Updated

2021-04-30 19:05 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        if (network != AcceptanceTestProperties.HederaNetwork.OTHER) {
Added property and now addressBook pull is by default for all envs

2021-04-30 19:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        singletonNodeId = Collections.singletonList(this.client.getNetwork().values().iterator().next());
Updated to return a random node in the list

2021-05-01 03:41 UTC, steven-sheehy requested changes

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/pom.xml
> +            <version>2.0.5-beta.9</version>
We should use 2.0.5 if we're upgrading. Can we now consolidate the other places that use a hardcoded version to use `${hedera-sdk.version}`? Might need to hardcode jmeter stuff to use 1.33.

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +                .setNodeAccountIds(scheduleClient.getSdkClient().getRandomSingleNodeAccountIdList())
That's quite the confusing oxymoron of a method name. Would prefer `List.of(scheduleClient.getSdkClient().getRandomNodeAccountId())`.

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/README.md
> +These values will always take precedence over the default network map used by teh SDK for an environment.
```suggestion
These values will always take precedence over the default network map used by the SDK for an environment.
```

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        // if prod environment, get current address book and use those nodes
Comment is out of date

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                                      Set<NodeProperties> customNetworkMap) {
This variable does not contain a map nor is it a network. Just `nodes` or `customNodes`.

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        Map<String, AccountId> validNodes = new HashMap<>();
Use `LinkedHashMap` to have a deterministic order.

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        NodeAddressBook addressBook = getAddressBookFromNetwork(client);
If this fails to download or parse should we fallback to using bootstrap with a warning or stop the program?

2021-05-01 03:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private boolean pullAddressBookNodes = true;
Pull seems the wrong term when talking about invoking an API as it's usually used to denote the direction of data flow and not an action. And it's implied the address book has nodes, so can leave that term off. Would suggest just `retrieveAddressBook` or `dynamicAddressBook`.

2021-05-03 04:54 UTC, ijungmann requested changes
Looks good, minor nits

2021-05-03 04:54 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +                .setNodeAccountIds(scheduleClient.getSdkClient().getRandomSingleNodeAccountIdList())
I agree.

2021-05-03 04:54 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private boolean pullAddressBookNodes = true;
I can see that.  Would also throw out `fetchAddressBook` just to add to the mix.

2021-05-03 04:54 UTC, ijungmann commented on hedera-mirror-test/README.md
> +-   Test run Config Properties: Configuration properties are set in the `application-default.yml` file located under `/src/test/resources` utilizing the spring boot application context for DI logic.
It feels like this word should also be capitalized.
```suggestion
-   Test Run Config Properties: Configuration properties are set in the `application-default.yml` file located under `/src/test/resources` utilizing the spring boot application context for DI logic. Properties include
```

2021-05-03 04:54 UTC, ijungmann commented on hedera-mirror-test/README.md
> +    -   existingTopicNum - a pre existing default topic number that can be used when no topicId is specified in a test. Used initially by @SubscribeOnly test
Pre-existing would also be valid.
```suggestion
    -   existingTopicNum - a preexisting default topic number that can be used when no topicId is specified in a test. Used initially by @SubscribeOnly test
```

2021-05-03 04:54 UTC, ijungmann commented on hedera-mirror-test/README.md
> +    -   network - The desired Hedera network environment to point to. Options currently include MAINNET, OTHER, PREVIEWNET and TESTNET (default). Set to OTHER to point to a custom environment.
This is entirely personal preference, I feel `OTHER` should be at the end of a list, similar to `None of the above`
```suggestion
    -   network - The desired Hedera network environment to point to. Options currently include MAINNET, PREVIEWNET, TESTNET (default), and OTHER. Set to OTHER to point to a custom environment.
```

2021-05-03 04:54 UTC, ijungmann commented on hedera-mirror-test/README.md
> +In some scenarios you may want to point to nodes not yet captured by the SDK, a subset of published nodes or custom nodes for a test environment.
```suggestion
In some scenarios you may want to point to nodes not yet captured by the SDK, a subset of published nodes, or custom nodes for a test environment.
```

2021-05-03 05:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +                .setNodeAccountIds(scheduleClient.getSdkClient().getRandomSingleNodeAccountIdList())
Yeah agreed. Will update

2021-05-03 05:23 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        NodeAddressBook addressBook = getAddressBookFromNetwork(client);
Fallback to bootstrap with warning makes sense. If bootstrap nodes are unreachable we'll stop on that error

2021-05-03 05:27 UTC, Nana-EC commented on hedera-mirror-test/pom.xml
> +            <version>2.0.5-beta.9</version>
`2.0.5` wasn't available when I updated. Can use that. Agree with sharing the value now and having JMeter use the current version

2021-05-03 05:42 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    -   network - The desired Hedera network environment to point to. Options currently include MAINNET, OTHER, PREVIEWNET and TESTNET (default). Set to OTHER to point to a custom environment.
Yeah I can see that in terms of the relevance.

2021-05-03 06:03 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +These values will always take precedence over the default network map used by teh SDK for an environment.
Fixed

2021-05-03 06:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        // if prod environment, get current address book and use those nodes
Removed as flag is self explanatory

2021-05-03 06:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                                      Set<NodeProperties> customNetworkMap) {
Updated

2021-05-03 06:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        Map<String, AccountId> validNodes = new HashMap<>();
Updated

2021-05-03 06:03 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private boolean pullAddressBookNodes = true;
Updated

2021-05-03 06:03 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +-   Test run Config Properties: Configuration properties are set in the `application-default.yml` file located under `/src/test/resources` utilizing the spring boot application context for DI logic.
Updated

2021-05-03 06:04 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    -   existingTopicNum - a pre existing default topic number that can be used when no topicId is specified in a test. Used initially by @SubscribeOnly test
Updated

2021-05-03 06:04 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +In some scenarios you may want to point to nodes not yet captured by the SDK, a subset of published nodes or custom nodes for a test environment.
Updated

2021-05-03 16:15 UTC, ijungmann commented on hedera-mirror-test/README.md
> +    -   network - The desired Hedera network environment to point to. Options currently include MAINNET, PREVIEWNET, TESTNET(default) and OTHER. Set to OTHER to point to a custom environment.
nit:
```suggestion
    -   network - The desired Hedera network environment to point to. Options currently include MAINNET, PREVIEWNET, TESTNET (default) and OTHER. Set to OTHER to point to a custom environment.
```

2021-05-03 16:19 UTC, ijungmann approved these changes
One very small nit you might want to address, otherwise LGTM

2021-05-03 16:23 UTC, steven-sheehy requested changes

2021-05-03 16:23 UTC, steven-sheehy commented on hedera-mirror-test/README.md
> +    -   retrieveAddressBook - Whether to download the address book from the network and use those nodes over the default nodes. Populating `hedera.mirror.test.acceptancenodes` will take priority over
```suggestion
    -   retrieveAddressBook - Whether to download the address book from the network and use those nodes over the default nodes. Populating `hedera.mirror.test.acceptance.nodes` will take priority over this.
```

2021-05-03 16:23 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                //
We should log the failure of downloading the address book.

2021-05-03 17:31 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +                //
Logged

2021-05-03 17:31 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    -   retrieveAddressBook - Whether to download the address book from the network and use those nodes over the default nodes. Populating `hedera.mirror.test.acceptancenodes` will take priority over
Updated

2021-05-03 17:31 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    -   network - The desired Hedera network environment to point to. Options currently include MAINNET, PREVIEWNET, TESTNET(default) and OTHER. Set to OTHER to point to a custom environment.
Updated

2021-05-03 17:40 UTC, ijungmann approved these changes

2021-05-03 17:51 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +    private static final FileId ADDRESS_BOOK_IPS = new FileId(0L, 0L, 101L);
nit: is `ADDRESS_BOOK_IPS` a typo?

2021-05-03 17:54 UTC, xin-hedera approved these changes
LGTM

2021-05-03 17:55 UTC, steven-sheehy approved these changes
LGTM

2021-05-03 18:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +    private static final FileId ADDRESS_BOOK_IPS = new FileId(0L, 0L, 101L);
File 101 was the one with IPs at this stage. When we update this to use the service address endpoints I can update this if it's no longer applicable

2021-05-03 18:20 UTC, merged