Add alertmanager inhibit rules
hashgraph/hedera-mirror-node pull request #1925
Opened 2021-05-04 08:34 UTC by ijungmann

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1813 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-05-06 06:57 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +    memory: 64Mi
Remove these, was doing testing.

2021-05-06 06:58 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +            value: GrpcErrors
Fix titles and alphabetize.

2021-05-06 06:58 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  GrpcNoPodsReady:
Alphabetize this (in all other charts too).

2021-05-06 06:59 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  StopGrpcAlertsWhenResourcesHigh:
These titles are not used anywhere in the template/config, they're just for documentation purposes.  Could be replaced with a comment if desired.  Not firm on the titles either, they're rather wordy.

2021-05-07 19:17 UTC, steven-sheehy requested changes

2021-05-07 19:17 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +            value: ImporterNoConsensus
ImporterNoConsensus deals with signature verification rate while ImporterFileVerificationErrors deals with stream files. So the relationship is inverted as the latter occurs before the former.

2021-05-07 21:20 UTC, ijungmann commented on charts/hedera-mirror-grpc/templates/alertmanagerconfig.yaml
> +    alertmanagerConfig: hedera
Yep, was my original test and got left in.  Just  deleted it in all templates.

2021-05-10 02:34 UTC, ijungmann commented on charts/hedera-mirror-grpc/templates/alertmanagerconfig.yaml
> +        {{- $rule.matches | toYaml | nindent 4}}
I think `enabled` is skipped because it's on the same level as `matches`, I intentionally made the `matches` label to group all the rule logic together and not have to add `omit` here in this template.

2021-05-10 02:38 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  enabled: true
Done and done.

2021-05-10 03:37 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  StopGrpcAlertsWhenResourcesHigh:
That's fair.  I originally had the `PodsDown` alerts at the highest level, with resources a level down (`PodsDown` inhibits everything else, `HighResources` inhibits everything except `PodsDown`), but they ended up blending together as I was messing with the labels.  I'll merge them for all services.

2021-05-10 03:38 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  StopGrpcLogAlertOnHighErrors:
I agree, was in the process of switching over to `Inhibit`, was still debating `on` vs `when`.  I'll make the switch for all.

2021-05-10 04:21 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  StopGrpcAlertsWhenResourcesHigh:
Actually, I had one other particular reason for splitting them: should the `NoPodsReady` alerts (and inhibit rules) be a per-pod, or a per-deployment?  This really only applies to `rest` for the moment, but if we to add replicas to any service, it could either be "my pod isn't ready" or "no pods in the replicaset are ready" (which I would imagine would be mostly during helm installs).  Or we could have one for each.

2021-05-10 04:30 UTC, ijungmann commented on charts/hedera-mirror-monitor/values.yaml
> +      description: "No monitor instances are currently running in {{ $labels.namespace }}"
Added.  As mentioned in another comment, this depends a little on if this should be per-pod or per-deployment.

2021-05-10 04:31 UTC, ijungmann commented on charts/hedera-mirror-rest/values.yaml
> +      description: "No rest instances are currently running.  "
Fixed.

2021-05-10 04:32 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +            value: grpc
Sure, I like that.

2021-05-10 04:38 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +            value: grpc
Done for all components

2021-05-10 04:54 UTC, ijungmann commented on charts/hedera-mirror-rest/values.yaml
> +            value: rest
You are correct, did not swap out the name.  You have a point, I was not considering the severity and was just creating an explicit set of rules.  I'm mixed on bumping it up to critical, I think the time should be extended past a minute if we do go that route.

2021-05-10 04:55 UTC, ijungmann commented on charts/hedera-mirror-rest/values.yaml
> +            value: RestHighCPU
Done

2021-05-10 05:02 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +  StopGrpcLogAlertOnHighErrors:
Everything should be `Inhibit` and `When` now.

2021-05-10 05:04 UTC, ijungmann commented on charts/hedera-mirror-monitor/values.yaml
> +  StopP2HAlertOnHighPublishLatency:
Fixed, but changed `On` to `When` for consistency.

2021-05-10 05:04 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +          - pod
Yep, just missed that.  Added.

2021-05-10 05:05 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +          - name: alertType
Yep, was an old label.  Changed to `application` as per other comments

2021-05-10 05:05 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +            value: (ImporterHighCPU|ImporterHighMemory|ImporterHighFileDescriptors|ImporterHighDBConnections)
Done.

2021-05-10 05:16 UTC, ijungmann commented on charts/hedera-mirror-monitor/values.yaml
> +
Good idea, added.

2021-05-10 05:17 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +            value: ImporterNoConsensus
Ah, got it.  Flipped them and fixed the name to reflect that.

2021-05-10 05:18 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +    InhibitImporterAlertsWhenPodIssues:
Need to alphabetize all rules (in all components)

2021-05-11 16:09 UTC, xin-hedera requested changes
looks good, just some minor suggested changes

2021-05-11 16:33 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +    memory: 64Mi
Thanks, yeah, I accidentally swapped the rest and importer resources when I was putting them back.  Fixed now.

2021-05-11 16:33 UTC, ijungmann commented on charts/hedera-mirror/values-prod.yaml
> +  inhibitRules:
Moved.

2021-05-11 16:36 UTC, ijungmann commented on charts/hedera-mirror-grpc/templates/alertmanagerconfig.yaml
> +        {{- $rule.matches | toYaml | nindent 4}}
Fixed in all templates.

2021-05-11 16:36 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +            -
Removed

2021-05-11 16:43 UTC, steven-sheehy requested changes

2021-05-11 17:11 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +      description: "No grpc instances are currently running in {{ $labels.namespace }}//{{ $labels.pod }}"
Removed.

2021-05-11 17:11 UTC, ijungmann commented on charts/hedera-mirror-monitor/values.yaml
> +    InhibitMonitorAlertsWhenPodIssues:
Shortened for all

2021-05-11 17:11 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +            -
Removed.

2021-05-11 17:11 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterBalanceStreamFallenBehind)
Removed.

2021-05-12 15:27 UTC, steven-sheehy requested changes

2021-05-12 15:27 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +    InhibitConsensusAlertsWhenCloudErrors:
This rule can be removed with my suggestion for inhibiting all areas for cloud alerts

2021-05-12 15:27 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +    InhibitRecordStreamAlertsWhenCloudErrors:
This rule can be removed with my suggestion for inhibiting all areas for cloud alerts

2021-05-12 15:27 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterParseErrors|ImporterNoConsensus)
Can remove `ImporterNoConsensus` since it will already be inhibited transitively via ImporterNoConsensus -> ImporterFileVerificationErrors -> ImporterParseErrors

2021-05-12 15:27 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterParseErrors|ImporterNoConsensus)
Can remove `ImporterNoConsensus` since it will already be inhibited transitively via ImporterNoConsensus -> ImporterFileVerificationErrors -> ImporterParseErrors

2021-05-12 22:25 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +    enabled: false
Added a couple of inhibit rules to the wrapper chart, mostly related to latency/no transactions in GRPC/the monitor when the importer reports latency or down pods.

2021-05-12 22:52 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterParseErrors|ImporterNoConsensus)
Removed.

2021-05-13 05:53 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +    InhibitNoTransactionsWhenStreamCloseInterval:
Removed.

2021-05-13 05:53 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterParseErrors|ImporterNoConsensus)
Removed.

2021-05-13 05:55 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +            value: ImporterRecordeParseLatency
Removed.

2021-05-13 15:05 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +  inhibitRules:
I don't see a alertmanagerconfig.yaml in the wrapper chart

2021-05-13 17:01 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +  inhibitRules:
Yep, forgot to push.  Fixed.

2021-05-13 17:58 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterCloudStorageErrors|ImporterCloudStorageLatency)
Yeah, I misunderstood how labels worked initially coming from the metrics to the alerts vs. made on the rules.  I added a `type` label to some of the alerts that allowed me to remove a few rules.  I'll work on adding another set of tags just to make it easier to read.

2021-05-14 06:31 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterCloudStorageErrors|ImporterCloudStorageLatency)
This may be overkill, but I added a two different labels to break it down further.  For instance, I don't think cloud latency/errors should inhibit parser errors or parser latency, just e2e latency and consensus alerts.  So I added the `area` label as mentioned, and then for some I also added a `metric` label of `error`, `consensus`, `parseLatency`, and `e2eLatency`.  With those two I was able to majorly trim down the number of rules, and also make it much more readable.

2021-05-14 06:31 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +    InhibitConsensusAlertsWhenCloudErrors:
Removed

2021-05-14 06:32 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterParseErrors)
Fixed

2021-05-14 07:06 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +      area: resource
I've only added `area` to rules that need it to facilitate better inhibit rules grouping.

2021-05-14 07:11 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +      metric: parseLatency
Not in love with `metric` as a label, but need something to differential `errors`, `parseLatency`, `e2eLatency`, and the one `consensus`.

2021-05-14 07:12 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +      type: BALANCE
Added `type` to a few of the rules where it can technically be inferred, but needs to be present to group in the inhibit rules without defining a separate rule.

2021-05-14 07:13 UTC, ijungmann commented on charts/hedera-mirror-monitor/values.yaml
> +      area: publisher
Renamed `mode: publish` to `area: publisher` to fit other naming convention in the importer.

2021-05-14 15:53 UTC, ijungmann commented on charts/hedera-mirror-grpc/values.yaml
> +              value: resource
resource = any of `HighCPU`, `HighDBConnections`, `HighFileDescriptors`, `HighMemory`, or `NoPodsReady` for all charts.

2021-05-14 16:07 UTC, ijungmann commented on charts/hedera-mirror-monitor/values.yaml
> +      area: publisher
Swapped back

2021-05-14 16:08 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +      metric: parseLatency
Removed, no longer relevant

2021-05-14 16:17 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +              value: (ImporterCloudStorageErrors|ImporterCloudStorageLatency)
Reworked to just use `area` where appropriate.  Added a regex here or there to make things more readable without adding more labels.  Also made some rules a little broader, like having cloud alerts inhibit all downloader and parser alerts, as suggested.  These can always be fine-tuned later.

2021-05-14 16:17 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +    InhibitRecordStreamAlertsWhenCloudErrors:
Removed.

2021-05-14 22:32 UTC, Nana-EC approved these changes
LGTM

2021-05-17 15:30 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-05-17 16:23 UTC, ijungmann commented
Fixed DCO issue

2021-05-17 16:27 UTC, xin-hedera approved these changes

2021-05-17 16:30 UTC, steven-sheehy approved these changes

2021-05-17 17:32 UTC, merged