Transaction support entity updater
hashgraph/hedera-mirror-node pull request #1938
Opened 2021-05-05 17:13 UTC by Nana-EC

**Detailed description**:
During an attempted migration using the entity-updater package we encountered a error: index row size 2792 exceeds maximum 2712 for index "entity__public_key_natural_id" when addressing https://github.com/hashgraph/hedera-mirror-node/issues/509

This was the result of a larger than expected key being attempted to be written since a non simple public_key was used.
This was an oversight in the package but a corner case handled by the importer.
Similarly the package did not utilize a transaction approach and so changes had to be manually rolled back

- Update package to ensure 1st element of KeyList contains data and not another key
- Wrap queries in transactions to ensure failures rollback any changes
- Add cache cases for database and network call to aid testing
- Add test cases to verify processing logic

**Which issue(s) this PR fixes**:
Fixes #1905 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-05-06 17:27 UTC, steven-sheehy requested changes
1.2M rows added!? Please remove the cache files from the commit. They're too large, they're already out of date, they should not be checked in and there's too large of a risk they're accidentally ran in production.

Even if you force remove them by squashing/rebasing, they are forever included in our git history and now git clones will take longer unfortunately. :(

2021-05-06 17:27 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/config.js
> +    const configPath = process.env.CONFIG_PATH || `${__dirname}/config`;
Probably doesn't matter for this one off, but should use `path.join`

2021-05-06 17:27 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const entityCachePath = process.env.ENTITY_CACHE_PATH || `${__dirname}/sample`;
path.join

2021-05-06 17:27 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/index.js
> +console.log(runUpdater());
Use logger

2021-05-06 17:27 UTC, steven-sheehy commented on hedera-mirror-rest/entity-info-updater/sample/keys.csv
> +0.0.1000, 32240a2212200aa8e21064c61eab86e2a9c164565b4e7a9a4146106e0a6cd03a8c395a110e92, 32240a221220f9c9016c24f98132ca4a78f34d98f0393bda9431f5921367e4f834dfd2bfa4a3
This is a large file to have checked in. Is the reference input file that is used to loop over which entities to retrieve and update? If so, then it shouldn't be in a sample folder and it should be specified as the default config in `application.yaml`. I would also suggest it be gzipped.

If not, it should be removed.

2021-05-06 17:38 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/index.js
> +console.log(runUpdater());
Solely for test purposes as a file run output. I think if I use logger I now have to parse the logger format etc

2021-05-06 17:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/sample/keys.csv
> +0.0.1000, 32240a2212200aa8e21064c61eab86e2a9c164565b4e7a9a4146106e0a6cd03a8c395a110e92, 32240a221220f9c9016c24f98132ca4a78f34d98f0393bda9431f5921367e4f834dfd2bfa4a3
Yeah the json files map to this cdv's entity rows.
I didn't want to set this as the default as future runs might use different entity sets, so I want to ensure ether user explicitly sets the location of the csv.

I can look into gzipping and unzipping for tests

2021-05-06 17:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const entityCachePath = process.env.ENTITY_CACHE_PATH || `${__dirname}/sample`;
Will update

2021-05-06 17:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/config.js
> +    const configPath = process.env.CONFIG_PATH || `${__dirname}/config`;
Will update

2021-05-06 17:50 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/index.js
> +console.log(runUpdater());
Actually I don't even need this log line anymore as I'm calling the function directly.

2021-05-06 19:20 UTC, xin-hedera requested changes

2021-05-06 19:20 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (Buffer.compare(dbKey, protoBuffer) !== 0) {
nit:

```suggestion
  const dbKey = dbEntity.key;
  if (dbKey === null || Buffer.compare(dbKey, protoBuffer) !== 0) {
```

2021-05-06 19:20 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    const elapsedTime = process.hrtime(updateStart);
nit, `hrtime` is deprecated

https://nodejs.org/api/process.html#process_process_hrtime_time

2021-05-06 19:20 UTC, xin-hedera commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    updateCount = -1;
nit, can skip setting `updateCount`, since the error is rethrown

2021-05-06 19:21 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +if (config.db.useCache === true && dbEntityCache !== {}) {
lodash is my friend :)

2021-05-07 04:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/config.js
> +    const configPath = process.env.CONFIG_PATH || `${__dirname}/config`;
Updated

2021-05-07 04:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/utils.js
> +const entityCachePath = process.env.ENTITY_CACHE_PATH || `${__dirname}/sample`;
Updated

2021-05-07 04:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/index.js
> +console.log(runUpdater());
Updated

2021-05-07 04:42 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/sample/keys.csv
> +0.0.1000, 32240a2212200aa8e21064c61eab86e2a9c164565b4e7a9a4146106e0a6cd03a8c395a110e92, 32240a221220f9c9016c24f98132ca4a78f34d98f0393bda9431f5921367e4f834dfd2bfa4a3
Added files added gzips and added logic to gunzip all files on test run if needed

2021-05-07 04:43 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +  if (config.db.useCache === false) {
Updated

2021-05-07 04:43 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/dbEntityService.js
> +if (config.db.useCache === true && dbEntityCache !== {}) {
Updated

2021-05-07 04:43 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +  if (Buffer.compare(dbKey, protoBuffer) !== 0) {
Updated

2021-05-07 04:43 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    const elapsedTime = process.hrtime(updateStart);
Thanks, updated to use `process.hrtime.bigint()` instead

2021-05-07 04:44 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
> +    updateCount = -1;
Removed

2021-05-07 04:44 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/networkEntityService.js
> +  if (config.sdkClient.useCache === true && networkEntityCache !== {}) {
Updated

2021-05-07 04:44 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/networkEntityService.js
> +    if (config.sdkClient.useCache && networkEntityCache[accountId.toString()] !== undefined) {
Updated

2021-05-07 04:44 UTC, Nana-EC commented on hedera-mirror-rest/entity-info-updater/networkEntityService.js
> +      logger.trace(`Retrieved ${accountId.toString()} from cache`);
Updated

2021-05-07 06:12 UTC, ijungmann approved these changes

2021-05-07 14:48 UTC, xin-hedera approved these changes
LGTM

2021-05-07 15:29 UTC, steven-sheehy commented
already reviewed...

2021-05-07 17:05 UTC, merged