Signature consensus ratio config
hashgraph/hedera-mirror-node pull request #1950
Opened 2021-05-07 18:34 UTC by Nana-EC

**Detailed description**:
OPS and customers would benefit from the ability to customize the consensusRatio used by the importer to validate signature files.

- Add a `consensusRatio` filed to the `DownloaderProperties`
- Add a `missingNodeSignatureFileMetric` metric to capture nodes whose signature files were missing from the downloaded list 

**Which issue(s) this PR fixes**:
Fixes #1869 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-05-08 21:20 UTC, steven-sheehy requested changes

2021-05-08 21:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        fileStreamSignature.setStreamType(pendingDownload.getStreamFilename().getStreamType());
```suggestion
        fileStreamSignature.setStreamType(streamType);
```

2021-05-08 21:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +    private static boolean canReachConsensus(long actualNodes, long expectedNodes, double consensusRatio) {
To stay DRY can make this method non-static and avoid passing in consensusRatio and directly use `commonDownloaderProperties.getConsensusRatio()`.

2021-05-08 21:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +        when(commonDownloaderProperties.getConsensusRatio()).thenReturn(0.333);
We should have additional tests that test both 0% and 100%

2021-05-08 21:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodes.forEach(nodeAccountId -> missingNodeSignatureFileMetric.tag("nodeAccount", nodeAccountId)
As metric registering is expensive and we're adding additional metrics, we should consider caching this creation using a map `Map<EntityId, Counter> missing Metric = new ConcurrentHashMap<>()` and using `computeIfAbsent`. Same for other metric.

2021-05-10 17:22 UTC, ijungmann requested changes
Looks good, couple small things.  You also have `field` misspelled in the description.

2021-05-10 17:22 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.consensusRatio`                   | 0.333                   | The ratio of verified nodes to total number of nodes available used to come to consensus on the sign
Nit: This sounds out of order to me.  Maybe
```suggestion
| `hedera.mirror.importer.downloader.consensusRatio`                   | 0.333                   | The ratio of verified nodes (nodes used to come to consensus on the signature file hash) to total number of nodes available |
```

2021-05-10 17:22 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +    private double consensusRatio = 0.333;
Could this possibly just be a float?

2021-05-10 18:32 UTC, xin-hedera requested changes

2021-05-10 18:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
>              throw new SignatureVerificationException("Require at least 1/3 signature files to reach consensus, got " +
need to update the exception message

2021-05-10 18:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    .tag("shard", nodeAccountId.getShardNum().toString())
should we just collapse these into a single `nodeAccountId` tag?

2021-05-10 18:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodes.forEach(nodeAccountId -> missingNodeSignatureFileMetric.tag("nodeAccount", nodeAccountId)
inconsistency of `nodeAccount`

- here it's `nodeAccountId` 
- for `signatureVerificationMetric` it's the entity number

2021-05-10 19:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    .tag("shard", nodeAccountId.getShardNum().toString())
My thinking was that when we had multiple shards or realms we could filter down by those. Though one could argue we should really be using the node ID for these metrics as the node account ID can change.

2021-05-12 20:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    .tag("shard", nodeAccountId.getShardNum().toString())
Yeah future support for shard, realm is good.
Though I do agree we should use nodeId instead. Will see if this is an easy fix or if a ticket and a future PR is better

2021-05-12 20:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodes.forEach(nodeAccountId -> missingNodeSignatureFileMetric.tag("nodeAccount", nodeAccountId)
Will expand to support shard and realm based on a previous comment

2021-05-12 20:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    .tag("shard", nodeAccountId.getShardNum().toString())
Mostly for the fact that it's a metric you would want the ability to break out charts for separate realms and shards. If we collapse it that makes it more challenging

2021-05-12 22:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        fileStreamSignature.setStreamType(pendingDownload.getStreamFilename().getStreamType());
Updated

2021-05-12 22:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +    private static boolean canReachConsensus(long actualNodes, long expectedNodes, double consensusRatio) {
Good idea, done

2021-05-12 22:05 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
> +        when(commonDownloaderProperties.getConsensusRatio()).thenReturn(0.333);
Added

2021-05-12 22:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodes.forEach(nodeAccountId -> missingNodeSignatureFileMetric.tag("nodeAccount", nodeAccountId)
Added

2021-05-12 22:07 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.consensusRatio`                   | 0.333                   | The ratio of verified nodes to total number of nodes available used to come to consensus on the sign
Updated

2021-05-12 22:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +    private double consensusRatio = 0.333;
Good thought, could be, to be more efficient on space. Updated

2021-05-12 22:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
>              throw new SignatureVerificationException("Require at least 1/3 signature files to reach consensus, got " +
Updated

2021-05-12 22:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodes.forEach(nodeAccountId -> missingNodeSignatureFileMetric.tag("nodeAccount", nodeAccountId)
Conformed to use nodeAccountId full string

2021-05-12 22:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    .tag("shard", nodeAccountId.getShardNum().toString())
So turns out we store nodeId as an integer and not an EntityId in the db which supports the conversion.
I'll open a ticket that captures this and asks for using NodeId instead of NodeAccountId as the unique id in the node verification flow

2021-05-12 22:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    .tag("shard", nodeAccountId.getShardNum().toString())
Captured in #1976

2021-05-13 15:00 UTC, steven-sheehy requested changes

2021-05-13 15:08 UTC, xin-hedera requested changes

2021-05-13 15:08 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            return;
this will pass when even no signature file is verified, i.e., `signatureHashMap` is empty

the possible effect is an illegitimate stream file can pass verification and get ingested

2021-05-13 16:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            return;
Good point. You're highlighting the fact that even if consensusRatio is set to 0 we should still only proceed with no error if there are some valid signature stream files.
Makes sense, I'll update it as I don't see a scenario where we'd want to pass with no verified signature.

2021-05-13 16:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
Wanted to ensure there were no more than 3 decimal points for readability

2021-05-13 17:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
I don't think this changes anything in the current [TroubleShooting.md](https://github.com/hashgraph/hedera-mirror-node/blob/master/docs/troubleshooting.md#log-based-alerts)
It references the "Signature verification failed for file" log in the alert based table, but I don't believe there's any alert based on the one I'm modified. 
Will circle back with OPS to see if this needs updating on their end

2021-05-13 17:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
Looks like that file and the alert based on it has been out of date for ages. It's still looking for logs in the form “File could not be verified by at least 2/3 of nodes”

2021-05-13 17:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
Gonna modify this to start with "Insufficient downloaded signature file count, requires at least..." to make ti easier to alert on and understand.

2021-05-13 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
How about "Unable to reach consensus"?

2021-05-13 21:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodes.forEach(nodeAccountId -> metricMap
Combined into one counter needing only one map

2021-05-13 21:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +        missingNodeSignatureFileMetric = Counter.builder("hedera.mirror.download.signature.missing")
Combined into one counter

2021-05-13 21:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +    private final Counter.Builder signatureVerificationMetric;
Adopted similar logic

2021-05-13 21:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
Didn't see this before my last push.
However, I do want to call out the lack of downloaded files because we do the `canReachConsensus` before verification and again after. So it would be nice to distinguish.

2021-05-13 21:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +                    "Requires at least %s of signature files to reach consensus, got %d out of %d for file %s: %s",
Fixed

2021-05-13 21:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            return;
Updated

2021-05-13 21:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            return;
we probably should not log it at all unless it's important.

the updated if block is dead code, since when `signatureHashMap.size() > 0`, `consensusCount` will be > 0, and the the block above it with condition `if (consensusCount > 0)` will run instead

2021-05-13 21:59 UTC, steven-sheehy requested changes

2021-05-13 21:59 UTC, steven-sheehy commented on docs/troubleshooting.md
> +| `Insufficient downloaded signature file count, requires at least`                           | NONE             | HIGH (if 30 entries in 1 min)   |
There's another string `File could not be verified by at least 1/3 of nodes` that needs to be updated.

2021-05-13 22:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            return;
You're right, I thought this was the scenario you highlighted in your original comment, no.
Initially the plan was to not fail when number of verified signature files was = 0 and commonDownloaderProperties.getConsensusRatio() == 0.
However, per you comment we probably only want to allow this with verified files.

Probably better to move this check up to after verification but before consensus calculation

2021-05-13 23:11 UTC, Nana-EC commented on docs/troubleshooting.md
> +| `Insufficient downloaded signature file count, requires at least`                           | NONE             | HIGH (if 30 entries in 1 min)   |
Updated

2021-05-13 23:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
> +            return;
Fixed

2021-05-13 23:13 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-05-13 23:23 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-05-14 07:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        CONSENSUS_REACHED,  // At least 1/3 of all nodes have been verified
nit: still makes reference to the 1/3, should probably mention the new config value instead.

2021-05-14 07:18 UTC, ijungmann approved these changes
One small nit, otherwise LGTM, won't hold up approval for it.

2021-05-14 18:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
> +        CONSENSUS_REACHED,  // At least 1/3 of all nodes have been verified
Good catch, updated. Let me know if the wording works for you or you have a better suggestion

2021-05-14 18:36 UTC, steven-sheehy approved these changes

2021-05-14 18:48 UTC, xin-hedera approved these changes

2021-05-14 19:40 UTC, ijungmann approved these changes

2021-05-14 19:45 UTC, merged