Upgrade to latest rosetta sdk
hashgraph/hedera-mirror-node pull request #1975
Opened 2021-05-12 20:23 UTC by xin-hedera

**Detailed description**:

- Upgrade to rosetta-sdk-go v0.6.10 with support of rosetta-specifications@v1.4.10
- Add construction validation configuration file and test scenario DSL file
- Build transaction balance-changing operations from both non-fee transfers and crypto transfers
- Fix /network/options returning all transaction results as successful
- Fix /construction/preprocess not returning required public keys
- Fix /construction/parse returning account pubic key instead of account ID
- Fix /construction/payloads not returning signature type
- Enable persisting NonFeeTransfers for importer in the all-in-one Dockerfile
- Add construction API validation job to rosetta-api workflow
- Refactor rosetta-api workflow to share the all-in-one docker image

**Which issue(s) this PR fixes**:
Fixes #1918 

**Special notes for your reviewer**:
The `validate_construction` job needs new github secrets to work, before that, it'll fail. The new secrets are:

- base64 encoded application.yml file with testnet cloud storage credentials
- base64 encoded json file with two prefunded testnet accounts (account id, private key, and etc)

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-05-13 20:21 UTC, steven-sheehy requested changes

2021-05-13 21:18 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +          docker image ls -a
yes, copy & paste from an example. should remove it.

2021-05-13 21:23 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/construction_service.go
> +		sender, err = hedera.AccountIDFromString(operation.Account.Address)
our implementation only supports one signer, thus there should always just have one sender.

If there is a requirement for multiple-sender thus multiple-sig transactions, we should remove the restriction.

2021-05-13 21:44 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/common/common.go
> +type NonFeeTransfer struct {
balance reconcilation can work without non-fee transfers, which means we can still provide rosetta Data API on mainnet db.

What'll break is the construction API since it requires an exact match between non-fee transfers (the transfers in the transaction body) and the transfers parsed from the executed transaction provided by the Data API.

2021-05-14 03:34 UTC, Nana-EC reviewed
Looking good on 1st pass, will circle back

2021-05-14 22:27 UTC, Nana-EC requested changes
Some thoughts

2021-05-14 22:27 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	for _, nonFeeTransfer := range nonFeeTransfers {
nit: might be cleaner to move the big for statements into their own functions that return the objects they build

```go
nonFeeTransferMap := createNonFeeTransferMap(nonFeeTransfers, transactionTypes, transactionMap)
cryptoTransferMap := createCryptoTransferMap(...)
operations := getOperations(nonFeeTransferMap, cryptoTransferMap, ...)

```

2021-05-14 22:27 UTC, Nana-EC commented on hedera-mirror-rosetta/app/domain/types/operation.go
> +		Status:            &t.Status,
Is the status changed after transform?

2021-05-14 22:27 UTC, Nana-EC commented on hedera-mirror-rosetta/app/services/account/account_service.go
> +func (a *AccountAPIService) AccountCoins(
Q: is this non-implemented function needed to ensure the service has the functions needed from the AccountAPIService? If not should we just leave it out?

2021-05-14 22:27 UTC, Nana-EC commented on hedera-mirror-rosetta/app/services/account/account_service.go
> +func (a *AccountAPIService) AccountCoins(
[/account/coins](https://www.rosetta-api.org/docs/AccountApi.html#accountcoins) says you don't need to implement it if we're account-based

2021-05-18 14:48 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/operation.go
> +		Status:            &t.Status,
struct defined by rosetta-sdk-go. it's a breaking change, somewhere in their changelog should have it highlighted as well as the motivation :)

2021-05-18 14:48 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/account/account_service.go
> +func (a *AccountAPIService) AccountCoins(
this is the recommended way to unimplement a method, as shown in coinbase's rosetta-ethereum repo

2021-05-18 15:03 UTC, Nana-EC commented on hedera-mirror-rosetta/app/domain/types/operation.go
> +		Status:            &t.Status,
Gotcha, yeah a minor highlight might be useful, thanks

2021-05-18 16:37 UTC, xin-hedera commented on hedera-mirror-rosetta/test/mocks/mocks.go
> +
gorm v2 no longer supports postgresql index style param placeholder as the input SQL query. All the raw queries are converted to gorm v2's named param style (starts with `@`).

gorm v2 translates the SQL query's named param to index style placeholder (since gorm is configured with postgresql dialect) before it's captured by the mock.

the  `queryMatcher` does the same translation so in our tests we can pass the SQL query and its param values match.

we really should test against really db instead.

2021-05-18 16:41 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/run-validation.sh
> +if (./rosetta-cli 2>&1 | grep 'CLI for the Rosetta API' > /dev/null); then
`grep -q` with the pipe and `set -o pipefail` will cause error code 141 since `grep -q` exits once a match is found, without consuming all the data from the pipe, thus `rosetta-cli` is always being installed.

2021-05-18 16:44 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +from genesis_balance
the query selects up to 20 accounts' genesis balance. the accounts are ordered by their first crypto transfer after the genesis balance timestamp

needs the CTE otherwise the json_agg will repeat every account & balance pair for the number of occurencies as if there is no `group by`

2021-05-18 16:45 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
> +ENV HEDERA_MIRROR_IMPORTER_PARSER_RECORD_ENTITY_REDIS_ENABLED=false
this is moved from `run_supervisord.sh`

2021-05-18 16:50 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                            LIMIT 1`
The query finds the genesis record file and adjusts its consensus start to make sure that consensus start > first ingested account balance file consensus timestamp

2021-05-18 16:52 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +	} else if err := br.dbClient.Raw(selectRecordFileByIndex, sql.Named("index", index)).First(rf).Error; err != nil {
gorm v2's breaking change: only `First`, `Last`, and `Take` return `ErrRecordNotFound`

2021-05-18 16:55 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +          curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s -- -b .
install `rosetta-cli` before running the scripts otherwise the two processes may run into race condition

2021-05-18 17:07 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	for _, nonFeeTransfer := range nonFeeTransfers {
refactored

2021-05-18 20:44 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/run-validation.sh
> +  until [ $count -gt 60 ]
the "Wait for balance sync" logic is moved to `get-genesis-balance.sh`

2021-05-18 20:44 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/run-validation.sh
> +    count=$((count+1))
the logic is is moved to `get-genesis-balance.sh`

2021-05-18 20:45 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +          docker image ls -a
these steps are removed

2021-05-18 20:45 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +          docker image ls -a
this step is removed

2021-05-18 20:45 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/common/common.go
> +	EntityID           int64 `gorm:"type:bigint"`
sorted

2021-05-18 21:00 UTC, Nana-EC requested changes
Looks good, one nit suggestion

2021-05-18 21:00 UTC, Nana-EC commented on docs/configuration.md
> +`hedera.mirror.rosetta.db.pool.maxIdleConns`            | 20                      | The maximum number of idle database connections
nit: would prefer the full `Connections` vs `Conns` here and below

2021-05-18 21:09 UTC, xin-hedera commented on docs/configuration.md
> +`hedera.mirror.rosetta.db.pool.maxIdleConns`            | 20                      | The maximum number of idle database connections
sure

2021-05-19 16:23 UTC, Nana-EC approved these changes
LGTM

2021-05-19 20:45 UTC, steven-sheehy approved these changes
LGTM

2021-05-19 21:35 UTC, merged