Streamfile parsing health check
hashgraph/hedera-mirror-node pull request #1993
Opened 2021-05-17 15:14 UTC by Nana-EC

**Detailed description**:
The importer is unable to recover itself if it stops processing new stream files for some reason.

- Add a `streamFileActivity` Spring Boot HealthIndicator that checks if new stream files are processing. Use `hedera.mirror.parse.duration` timer metric to ensure the counts for each of the stream type are increasing at least every within 2.5 times the expected stream upload rate.
- Add new `streamFileActivity` health check to `management.endpoint.health.group.liveness.include`
- Add new `streamFileActivity` health check to `management.endpoint.health.group.readiness.include`

**Which issue(s) this PR fixes**:
Fixes #1892 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-05-17 17:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    @DurationMax(minutes = 35L)
Open to suggestions on max.
Was thinking of changing this to 45 / 60 mins

2021-05-17 17:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    protected Duration streamFileStatusCheckWindow;
open to suggestions on naming.
Duration is the allowable window after the last check that we won't report down if no stream files have yet been parsed

2021-05-17 17:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +                            searchTimer.tag("type", StreamType.BALANCE.toString()).timer(),
Update these with the success tag

2021-05-18 17:10 UTC, steven-sheehy requested changes

2021-05-18 17:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            if (endDate.isBefore(currentInstant)) {
This should be moved to be the first check in the method so that it fails fast. This check shouldn't depend upon the metric counts.

2021-05-18 17:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +    private Health lastHealthStatus = Health.unknown().build(); // unknown until at least 1 stream file is parsed
These are not thread safe. Use AtomicReference. You can also potentially move last count and check into the last health details then only health needs to be atomic.

2021-05-18 17:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +                            mirrorProperties.getEndDate()));
Had it this way first time around but testing was a bit harder. Can revert and just increase the mocking

2021-05-18 17:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    protected Duration streamFileStatusCheckWindow;
Good points

2021-05-18 17:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            if (endDate.isBefore(currentInstant)) {
With relying on the probe to try a few times this makes sense. Can fail fast and leave it to probe to configure retry

2021-05-18 20:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                return HEALTH_UP;
Will add

2021-05-18 22:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    protected Duration streamFileStatusCheckWindow;
Makes sense.

I'll change the window to a buffer and leave it configurable.
Will also add the mean.

2021-05-18 22:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +    private Health lastHealthStatus = Health.unknown().build(); // unknown until at least 1 stream file is parsed
Good suggestion, might as well load the Health details map up instead.

2021-05-18 23:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    protected Duration streamFileStatusCheckWindow;
Updated

2021-05-18 23:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +        Search searchTimer = meterRegistry.find("hedera.mirror.parse.duration");
Moved back into health check

2021-05-18 23:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +                            mirrorProperties.getEndDate()));
Reverted and improved

2021-05-18 23:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                return HEALTH_UP;
Added

2021-05-19 00:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            if (endDate.isBefore(currentInstant)) {
Updated

2021-05-19 00:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +    private Health lastHealthStatus = Health.unknown().build(); // unknown until at least 1 stream file is parsed
Updated

2021-05-19 15:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Health health = currentCount > lastCount.getAndSet(currentCount) ? HEALTH_UP : HEALTH_DOWN;
Removed and updated

2021-05-19 16:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setStreamFileStatusCheckBuffer(Duration.ofSeconds(10));
Are these actually making use of the config values in the yml?

2021-05-19 16:23 UTC, ijungmann requested changes
Couple small things, looks good.

2021-05-19 16:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                            String.format("EndDate: %s has passed, no stream files are no longer expected", endDate))
```suggestion
                            String.format("EndDate: %s has passed, stream files are no longer expected", endDate))
```

2021-05-19 16:23 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/StreamFileHealthIndicatorTest.java
> +        assertThat(health.getStatus()).isEqualTo(Status.UP); // cache should not be returned
Should also check the `reason` here just for completion.

2021-05-19 16:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setStreamFileStatusCheckBuffer(Duration.ofSeconds(10));
Yep, these set the default on instantiation I believe, like the maxAttempts above. 
The yaml values should be applied by spring boot after.
Setting it in the `BalanceParserProperties` and `RecordParserProperties` respectfully because the `EventParserProperties` case is null by default.
In the future when that's no longer null we can move it to `AbstractParserProperties` like the others.

2021-05-19 16:37 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/StreamFileHealthIndicatorTest.java
> +        assertThat(health.getStatus()).isEqualTo(Status.UP); // cache should not be returned
Good point, added

2021-05-19 16:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                            String.format("EndDate: %s has passed, no stream files are no longer expected", endDate))
Updated

2021-05-19 16:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setStreamFileStatusCheckBuffer(Duration.ofSeconds(10));
Got it, I figured I was forgetting something about config creation.  Cool

2021-05-19 16:44 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-05-19 17:03 UTC, xin-hedera requested changes

2021-05-19 17:03 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.event.streamFileStatusCheckBuffer`    |                         | The additional duration to allow after the last event stream file health check to verify that files
should set a default for event too. In the health indicator, if the event parser we should check if the parser is enabled instead of checking if `streamFileStatusCheckBuffer != null`

2021-05-19 17:38 UTC, steven-sheehy requested changes

2021-05-19 17:38 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.event.streamFileStatusCheckBuffer`    |                         | The additional duration to allow after the last event stream file health check to verify that files
I agree

2021-05-19 17:38 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.balance.streamFileStatusCheckBuffer`  | 10s                     | The additional duration to allow after the last balance stream file health check to verify that file
Naming is hard. But here this property is really a timeout since it is "a cancellation or cessation that automatically occurs when a predefined interval of time has passed without a certain event occurring." So we can replace `Buffer` with `Timeout`. I don't think `streamFile` is necessary since this check is not specifically for the stream file being available but the parser processing activity. Thus, since it's already under parser property, we can drop the `streamFile` prefix. So would prefer something like `activityTimeout`, `statusTimeout`, `processingTimeout`, etc.

2021-05-19 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
I agree. Although maybe we want to inject MirrorProperties separately instead of relying on it through ParserProperties as that might go away.

2021-05-19 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +    private final StreamType streamType;
Same principle applies here. Please don't cache variables that are encapsulated in another class. There's no performance penalty for using the property getter. Also we may want to support these changing during runtime.
```suggestion
    private final MeterRegistry meterRegistry;
    private final ParserProperties parserProperties;
```

2021-05-19 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                    .withDetail(REASON_KEY, String.format("%s parsing is disabled", streamType))
We don't need to string format with stream type since it's within the stream specific health indicator already. That stream type will show up in the list of components.

2021-05-19 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                .timer();
```suggestion
        Timer streamFileParseDurationTimer = meterRegistry.find("hedera.mirror.stream.close.latency")
                .tag("type", streamType.toString())
                .tag("success", "true")
                .timer();
```

2021-05-19 17:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setStreamFileStatusCheckBuffer(Duration.ofSeconds(10));
Since we should set a value for events and mark the field as `@NotNull`, we can set all fields to 10s by default and move default value to parent field.

2021-05-19 17:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Timer streamFileParseDurationTimer = searchTimer
We should return unknown if timer is not found

2021-05-19 17:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        long currentCount = streamFileParseDurationTimer.count();
This is not the `streamFileParseDurationTimer`, it is the stream close latency timer. The stream close timer is calculated in the downloader and is not related to whether the parser is processing. You need to get both timers. Use the average from the stream close to calculate last check but use the count from the parse timer.

2021-05-19 18:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +    }
Ah forgot you could have spring to the collection for you and just inject it. Thanks

2021-05-19 18:34 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.balance.streamFileStatusCheckBuffer`  | 10s                     | The additional duration to allow after the last balance stream file health check to verify that file
Thanks, I like the `processingTimeout` as parser is also already intended in the properties breadcrumb trail

2021-05-19 21:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
Considered moving the `getMirrorProperties()`, but looks like there's some funny business going on there with lombok.
Will inject it separately so it's easier

2021-05-19 21:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +        }
Utilized Steven's suggestions to get dependency injection doing the most work

2021-05-19 21:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
Updated

2021-05-19 21:53 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Search searchTimer = meterRegistry.find("hedera.mirror.stream.close.latency");
Adopted suggestion

2021-05-19 21:54 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.event.streamFileStatusCheckBuffer`    |                         | The additional duration to allow after the last event stream file health check to verify that files
Updated

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +        if (balanceParserProperties.getStreamFileStatusCheckBuffer() != null) {
Updated

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/HealthCheckConfiguration.java
> +    }
Updated

2021-05-19 21:54 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.balance.streamFileStatusCheckBuffer`  | 10s                     | The additional duration to allow after the last balance stream file health check to verify that file
Updated

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +    private final StreamType streamType;
Updated

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                    .withDetail(REASON_KEY, String.format("%s parsing is disabled", streamType))
True, updated

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                .timer();
Shortened. Also realized `find` could return null so I'll check for this case. Updated

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
> +        setStreamFileStatusCheckBuffer(Duration.ofSeconds(10));
Done

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Timer streamFileParseDurationTimer = searchTimer
Added check

2021-05-19 21:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        long currentCount = streamFileParseDurationTimer.count();
Good callout.. Updated and expanded tests for for missing metrics

2021-05-19 22:43 UTC, xin-hedera requested changes

2021-05-19 22:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordParserProperties.java
> +
looks like temporary changes

2021-05-19 22:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                    .build();
cache it

2021-05-19 22:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                    .build();
cache it

2021-05-19 22:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Search streamSearch = meterRegistry.find(metricName);
`streamSearch` will not be null

2021-05-19 22:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            streamSearch = meterRegistry.find(metricName).tag("type", parserProperty.getStreamType().toString());
there is `tags(Iterable<Tag> tags)` which adds all the tag name and value pairs to the search in one call

2021-05-19 22:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
don't think there can be an exception

looks like can remove the function `getTimer` and just do

`
timer = meterRegistry.find(metricName).tags(tags).timer();
`

2021-05-19 22:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
`find` can return null if the metric isn't present, but let me see about the other improvements suggested

2021-05-19 23:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordParserProperties.java
> +
More like I can revert since the extra property specification is no longer needed

2021-05-19 23:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
I think what the doc says is the terminal methods can return `null` if no matching result is found.

`meterRegistry.find` constructs a `Search` and the `Search` itself will not be null

2021-05-19 23:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
I believe Xin is right. Can easily test with `meterRegistry.find("foobar")`.

2021-05-19 23:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            streamSearch = meterRegistry.find(metricName).tag("type", parserProperty.getStreamType().toString());
Thanks, will use that

2021-05-19 23:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Search streamSearch = meterRegistry.find(metricName);
Left over logic

2021-05-19 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
Kept function as I can catch multiple NPE's and return the null instead of checking where called

2021-05-19 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            streamSearch = meterRegistry.find(metricName).tag("type", parserProperty.getStreamType().toString());
Updated

2021-05-19 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        Search streamSearch = meterRegistry.find(metricName);
Updated

2021-05-19 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                    .build();
Cached

2021-05-19 23:35 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                    .build();
Cached

2021-05-19 23:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +        }
Missed this comment. Working to update it further, broken tests so need to fix that too

2021-05-20 15:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> +          include: db, diskSpace, ping, redis, streamFileActivity
won't this cause adverse effect because specifically for balance `streamFileActivity` the first `UP` may take quite some time?

Perhaps we should default balance `streamFileActivity` to `UP`

2021-05-20 15:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +            .build();
Should be static and can shorten with a helper method. Can also collapse the the two missing timers that way:
```suggestion
    private static final Health HEALTH_DISABLED = unknownHealth("Parsing is disabled");
    private static final Health HEALTH_MISSING_PARSE_TIMER = unknownHealth(STREAM_PARSE_DURATION_METRIC_NAME + " timer is missing");
    private static final Health HEALTH_MISSING_CLOSE_TIMER = unknownHealth(STREAM_CLOSE_LATENCY_METRIC_NAME + " timer is missing");

    private static Health unknownHealth(String reason) {
    ...
    }
```

2021-05-20 15:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/StreamFileHealthIndicator.java
> +                .build();
Would rather omit the actual end date if it allows us to move it to a static variable. The actual end date will be known from the application config. It's not strictly necessary to be viewed. Also, these details won't actually be shown unless someone flips the management endpoints with-details property to true.

2021-05-20 16:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +          include: db, diskSpace, ping, redis, streamFileActivity
I think if we forced the default as `UP` it would be misleading.
However, it is true that at startup for balance it'll go from `UNKNOWN` to `DOWN` until the first file is parsed.
It's tough since the frequency is outside of the parser control and the lack of a count within the window isn't a bad thing.

My hesitation with the mean approach was that on the first counter the mean would be 0.

Thinking on this a bit more as I think the right course which is the intention here is to have it `UNKWOWN` until a file has been parsed

2021-05-20 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> +          include: db, diskSpace, ping, redis, streamFileActivity
my concern is the pod might get restarted if it takes up to 15 minutes for the balance `streamFileActivity` to be `UP`

2021-05-20 19:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +          include: db, diskSpace, ping, redis, streamFileActivity
I addressed the edge case by adding logic to continue to return the cached result  between startTime + first fileClose interval.

Good point on the pod restart, @steven-sheehy what do you think?

2021-05-21 15:31 UTC, steven-sheehy requested changes

2021-05-21 17:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamType.java
> +    EVENT(EventFile.class, "eventsStreams", "events_", "", List.of("evts"), Duration.ZERO),
Will update, thanks

2021-05-21 17:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamType.java
> +    EVENT(EventFile.class, "eventsStreams", "events_", "", List.of("evts"), Duration.ZERO),
Added

2021-05-21 18:46 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-05-21 18:49 UTC, steven-sheehy approved these changes
LGTM

2021-05-21 19:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +          include: db, diskSpace, ping, redis, streamFileActivity
Based off of offline discussion this should be good, will do some local verification before merging

2021-05-24 16:58 UTC, ijungmann approved these changes

2021-05-24 22:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/application.yml
> +          include: db, diskSpace, ping, redis, streamFileActivity
Verified locally, highlighted a missing case which I updated in the recent commit. Should be all set now

2021-05-25 15:16 UTC, steven-sheehy approved these changes

2021-05-25 16:03 UTC, ijungmann approved these changes

2021-05-25 16:26 UTC, merged