Workaround lack of TLS support in SDK & acceptance test cleanup
hashgraph/hedera-mirror-node pull request #2000
Opened 2021-05-19 21:06 UTC by steven-sheehy

**Detailed description**:
- Change acceptance tests to component scanning
- Fix acceptance tests loading address book and validating nodes multiple times by switching to singleton
- Remove dead code in acceptance tests
- Workaround https://github.com/hashgraph/hedera-sdk-java/issues/494 by hacking SDK's `ManagedNode` to not use plaintext for ports 443 or 50212

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-05-19 21:09 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
> +            builder.usePlaintext();
These are the only changed lines from upstream. This isn't a good permanent solution but works for our use case for now.

2021-05-20 00:55 UTC, Nana-EC requested changes

2021-05-20 00:55 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
> +
missing licensing info

2021-05-20 00:55 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
> +    String address;
nit: final

2021-05-20 00:55 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/hashgraph/sdk/ManagedNode.java
> +import io.grpc.ManagedChannel;
Same comments on this file as the one in monitor

2021-05-20 00:55 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -    public void recover(PrecheckStatusException t) throws PrecheckStatusException {
Where's the recover method after this. 
This was being used and printed statements like e.g.
```shell
2021-05-19T16:42:33.138-0600 ERROR main c.h.m.t.e.a.s.TopicFeature Transaction submissions for message publish failed after retries w: Hedera transaction `0.0.1261@1621464140.669984337` failed pre-check with the status `INSUFFICIENT_TX_FEE`
```

2021-05-20 01:18 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
> +
Erm, this is not a mirror node file. It's the SDK file. As such I won't be modifying it to our usual standard and just doing the minimal changes to make it work with TLS.

2021-05-20 01:20 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -    public void recover(PrecheckStatusException t) throws PrecheckStatusException {
Think I accidentally deleted this. Only the ones inside the clients should be deleted since they no longer had `@Retryable`.

2021-05-20 14:12 UTC, ijungmann approved these changes
LGTM

2021-05-20 14:17 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> -    public void recover(PrecheckStatusException t) throws PrecheckStatusException {
Done

2021-05-20 19:09 UTC, Nana-EC approved these changes
LGTM

2021-05-20 19:12 UTC, ijungmann approved these changes

2021-05-20 19:22 UTC, xin-hedera approved these changes

2021-05-20 19:27 UTC, merged