Helm acceptance tests
hashgraph/hedera-mirror-node pull request #2002
Opened 2021-05-19 23:21 UTC by ijungmann

**Detailed description**:
Add the ability to run acceptance tests to the Helm chart.

**Which issue(s) this PR fixes**:
Fixes #1917 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-05-19 23:22 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/pod.yaml
> +        - ./mvnw clean integration-test -pl hedera-mirror-test -P="acceptance-tests" -Dcucumber.filter.tags=@Acceptance -e
Can add tag filter as a config option

2021-05-19 23:22 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/secret.yaml
> +  HEDERA_MIRROR_TEST_ACCEPTANCE_MIRRORNODEADDRESS: {{ printf "%s-grpc:5600" .Release.Name | quote}}
Need to confirm this is the correct way of doing this, GRPC tests have not passed locally but could also be an unrelated issue.

2021-05-19 23:23 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/secret.yaml
> +  HEDERA_MIRROR_TEST_ACCEPTANCE_MIRRORNODEADDRESS: {{ printf "%s-grpc:5600" .Release.Name | quote}}
Tried to move this into a config option in values.yaml, wasn't able to get the Release Name replacement working (done in sub-charts?)

2021-05-21 06:57 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/pod.yaml
> +          value: "@acceptance"
Swap with actual yaml value

2021-05-21 06:58 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/pod.yaml
> +          value: "@acceptance"
Was having issues earlier getting the tests to use this when it was in the Secret.  Need to test more, seems to work here though.

2021-05-21 06:58 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/pod.yaml
> +        - name: cucumberflags
See if all caps works

2021-05-21 07:00 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/secret.yaml
> +  HEDERA_MIRROR_TEST_ACCEPTANCE_REST_BASEURL: {{- tpl (toYaml .Values.test.endpoints.restBaseUrl) $ | nindent 4 }}
May be a way to make this cleaner, but I need the `tpl` to make use of the Release Name (or so I understand it, maybe a better way)

2021-05-21 07:00 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +    operatorKey:
Not sure what to do about some of these defaults.

2021-05-24 21:59 UTC, Nana-EC requested changes
Looking good, some nits and suggestions

2021-05-24 21:59 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +            restBaseUrl: "http://{{ .Release.Name }}-rest/api/v1"
This should be `rest.baseUrl`.
Are the rest checks working with this?

2021-05-24 21:59 UTC, Nana-EC commented on charts/hedera-mirror/values.yaml
> +            operatorKey:
May want to add `retrieveAddressBook: ` with default of `false`,  as some pre-prod envs address books aren't updated as regularly as they should be yet.

2021-05-24 21:59 UTC, Nana-EC commented on charts/hedera-mirror/templates/tests/pod.yaml
> +        - |
nit: you could add a `#` comment here to cover your copy intent prior to the run command

2021-05-25 07:09 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +            restBaseUrl: "http://{{ .Release.Name }}-rest/api/v1"
Good catch, I just got lucky that the default was testnet.  I tested with this corrected and it works, also tested with a bad endpoint and it failed so I know it's using it now.

2021-05-25 07:09 UTC, ijungmann commented on charts/hedera-mirror/values.yaml
> +            operatorKey:
Sure, added

2021-05-25 07:09 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/pod.yaml
> +        - |
Added a comment here, as well as in the secret to explain using `application-default`

2021-05-25 14:40 UTC, steven-sheehy requested changes

2021-05-25 14:40 UTC, steven-sheehy commented on charts/hedera-mirror/templates/tests/pod.yaml
> +      image: "{{ .Values.test.image.repository }}:{{ .Values.test.image.tag | default .Chart.AppVersion }}"
This should also use the `global.image.tag`. You'll need to add a `global.image: {}` to the values.yaml.
```suggestion
      image: "{{ .Values.test.image.repository }}:{{ .Values.global.image.tag | default .Values.test.image.tag | default .Chart.AppVersion }}"
```

2021-05-25 14:40 UTC, steven-sheehy commented on charts/hedera-mirror/templates/tests/secret.yaml
> +
nit: extra line

2021-05-25 15:59 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/secret.yaml
> +
Removed.

2021-05-25 15:59 UTC, ijungmann commented on charts/hedera-mirror/templates/tests/pod.yaml
> +      image: "{{ .Values.test.image.repository }}:{{ .Values.test.image.tag | default .Chart.AppVersion }}"
Sure, added that.

2021-05-25 16:07 UTC, steven-sheehy approved these changes
LGTM

2021-05-25 16:22 UTC, Nana-EC approved these changes
LGTM

2021-05-25 17:20 UTC, merged