Fix slow domain object ingestion
hashgraph/hedera-mirror-node pull request #2006
Opened 2021-05-22 01:53 UTC by Nana-EC

**Detailed description**:
Slow entity ingestions flows exists. This is mainly because we do multiple db reference calls to check for existing entities to get the up to date info.
Insert only flows are fast with PgCopy. Taking inspiration from this update scenarios could utilize PgCopy to copy domain objects over to db server, then follow up with an upsert query to manage the insert vs update scenarios.

- Remove repository saves from `EntityRecordItemListener`
- Update `EntityRecordItemListener` to pass all entities, tokens and schedules domain objects with available info to `EntityListener` `onX()`
- Create a `UpsertPgCopy` class that creates a temp table for an entity, copies into this, and then runs an upsert query to manage inserts and updates to main table
- Update broken tests
- Update domain objects with serialization support
- Add temp table and Upsert sql query to domain objects
 

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
Inserting 6000 entities took 78 s previously now 223.7 ms
Inserting 6000 entities with 3000 being updates took 34 s now takes 400 ms

Still need to 
- [ ] Add micro meter tests
- [ ] Fix broken tests
- [ ] Resolve transaction test affects
- [ ] Verify intricate upsert sql queries

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-05-28 20:20 UTC, steven-sheehy requested changes

2021-05-28 20:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +    public static final String TEMP_TO_MAIN_UPDATE_SQL = "update schedule set " +
For maintainability, I'd prefer a single upsert statement instead of insert and update.

2021-06-01 18:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
Yep, the location of the sql isn't final, part of why the PR is still in draft. 
I was having issues where repository sql calls where not being observed by the db connection used by PgCopy. So the repository would create the temp table but the PgCopy queries wouldn't be able to see the table.
Likely some under the hood connection context I need to figure out.

2021-06-01 18:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +            sql = String.format("COPY %s(%s) FROM STDIN WITH CSV", tableName, columnsCsv);
Code in flux, I made some modification that needed this but I should be able to revert this back now.

2021-06-01 18:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    @JsonSerialize(using = EntityIdSerializer.class)
Agreed

2021-06-01 18:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    @JsonSerialize(using = NullableStringSerializer.class)
I was hesitant to do this because String fields could contain varied content. 
Also the logic is dependent on if the db column isn't marked as not null. 
Due do that disconnect and ability to change one and miss the other I felt more comfortable making this one an explicit statement.

2021-06-01 18:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
Yep, maintainability was one of my larger concerns, this just allowed for quicker testing so I planned to resolve this before taking the PR out of draft.

I mainly wanted to get thoughts on the actual sql logic as it differs for some entities, and there were some edge cases that could be missed. 
Will look into getting it nicely wrapped up.

2021-06-01 18:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +    public static final String TEMP_TO_MAIN_UPDATE_SQL = "update schedule set " +
I had it as upsert when I started but some queries became complex so for maintainability I split it up to make it easy to follow.
The performance numbers seemed to be similar so I can revert it to upsert and redo testing.

2021-06-02 00:30 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
need to check if the fields are updated before calling the setters.

it looks less error-prone if `EntityListener` provides methods for example `getForUpdate` to retrieve cached or create a new entity/token/schedule/etc and in the `EntityRecorditemListener` and transaction handlers the individual fields are set. since then we only have to set it once for optional fields.

2021-06-02 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Good point. Each of the non delete cases could be done individually in separate transactions.
I was trying to find the right balance of where to manage the cache.
I intended to move the cache management into the `EntityRecordItemListener` then both `RepositoryEntityListener` and `SqlEntityListener` won't have to worry about it and can focus on just the persistence.
So I'm in agreement and will look into the `getForUpdate` suggestion

2021-06-02 18:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +@ToString(exclude = {"freezeKey", "kycKey", "supplyKey", "wipeKey"})
Will do

2021-06-02 18:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            "case when " + TEMP_TABLE + ".memo = ' ' then '' else coalesce(memo, '') end, " +
That's the tricky part. Because the are nullable strings you can't differentiate between the field not being updated and when it's actually being cleared in an update.
To work around I reserved the use of ' ' when it's missing and rely on the upsert to catch this case.

I noted this in `NullableStringSerializer`

2021-06-02 20:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            "case when " + TEMP_TABLE + ".memo = ' ' then '' else coalesce(memo, '') end, " +
what about removing not null for `memo`, in rest we replace it with empty string when it's null.

2021-06-03 15:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
JPA Criteria and JPQL don't support insert let alone upsert from what I'm seeing. 
Their design shines mostly around select querying and simple joins and wheres.
JPQL makes room for everything with the nativeQuery and gives you type safety, but that's essentially what I have right now building the sql string manually.

Since we're not inserting values but rather comparing already persisted column values and inserting or updating based on the comparison, the type safety benefits here are minimal.

Even with all of this I'll still need to do a string concatenation since it doesn't seem to be possible to create the upsert/insert statement using the Criteria. 

Tied in with passing this through to the PgCopy flow for run it seems like a lot more overhead than necessary, but I'll see if I can make it work without unnecessary complications.

I can at least utilize the entity Metamodel Generator  regardless to at least ensure the column names are captured correctly and no longer hardcoded.

2021-06-03 16:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
I'd also be okay with using the metamodel to auto generate the sql without the use of jpql. That is, pass in a domain class, it loops through all the fields and automatically determine how to upsert based upon type. Just not sure how easy that is.

2021-06-03 17:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
Yeah that will be complex because of how many variations of property updates there are but also because you don't know what's different until first comparing against the existing entity table.
I want to concentrate all comparison logic to be done on the db server.

Unless there's performance gains I think limiting it to a single upsert or sequenced insert-update query that manages all scenarios with the use of things like coalesce between the tables would be the best of both worlds (simplicity and manageability).

2021-06-03 17:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
I don't think we're understanding each other. Everything I said would be server side. I'm advocating if jpql doesn't work out to use reflection to generate the sql one time on startup from the domain metamodel via reflection.

2021-06-07 16:04 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            " on conflict (id) do nothing";
Yep that's my mindset also and what I've been implementing. 
I was just highlighting the intricacies of the generated sql to ensure it captures all the nuances of our various domain object when run on the db.
I have this working already, mostly just cleaning up and it should be part of the next commit

2021-06-07 18:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +            "case when " + TEMP_TABLE + ".memo = ' ' then '' else coalesce(memo, '') end, " +
Yep, making memo nullable was something I considered/suggested also but it doesn't actually fix the main issue.
The challenge is since we get a partial update from the protobuf memo will be null when the domain object is serialized in both the case where it wasn't being set and when it's an empty string.

2021-06-07 19:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
I agree with parts of this, just wondering if this is better in a separate ticket/PR. 
It will add more refactoring cause essentially the right thing to do would be to move all the cache logic into `EntityRecorditemListener`.
This would mean additionally moving the entity/domain logic updates into the transaction handlers where possible.
Also even if we did that `OnX()` would still be called on entities that might need updating. If `OnX()` took a list instead of individual items we could pull the cache logic totally out of `SqlEntityListener`  and `RepositoryEntityListener`.

But again more code churn for this already unintendedly large PR

2021-06-07 19:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
sounds good to me to leave it in a separate ticket. better focus on what's already complicated :)

2021-06-07 20:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +@ToString(exclude = {"freezeKey", "kycKey", "supplyKey", "wipeKey"})
Done

2021-06-07 20:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java
> +    public static final String TEMP_TO_MAIN_UPDATE_SQL = "update schedule set " +
Right. So this was my initial aim but each time I got it working it became glaringly clear the upsert query was doing a lot and introducing some complications.
The last straw though was this.

```sql
insert into token_account (account_id, associated, created_timestamp, freeze_status, kyc_status, modified_timestamp, token_id) select coalesce(token_account_temp.account_id, 1) as account_id,  coalesce(token_account_temp.associated, FALSE), coalesce(token_account_temp.created_timestamp, 0) as created_timestamp, coalesce(token_account_temp.freeze_status, getNewAccountFreezeStatus (token_account_temp.token_id)) as freeze_status, coalesce(token_account_temp.kyc_status,  getNewAccountKycStatus(token_account_temp.token_id)) as kyc_status, token_account_temp.modified_timestamp, coalesce(token_account_temp.token_id, 1) as token_id from token_account_temp on conflict (token_id, account_id) do update set associated = coalesce(excluded.associated, token_account.associated), freeze_status = coalesce(excluded.freeze_status, token_account.freeze_status), kyc_status = coalesce(excluded.kyc_status, token_account.kyc_status), modified_timestamp = coalesce(excluded.modified_timestamp, token_account.modified_timestamp);
```

Due to the constraints on the tables the select query has to ensure that that all fields that are not nullable have their value transformed. This is applicable when creating the domain object but not when updating. The result is that the update portion ends up having that non null value always, even in the case where the updating query should be setting it to null.

Since the select gets run first there's no way of getting the original value from the temp table. Even if there was it makes the query more complex.

The cleanest solution I believe is to do insert and update from the temp table using where conditions.

2021-06-07 23:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +            sql = String.format("COPY %s(%s) FROM STDIN WITH CSV", tableName, columnsCsv);
Fixed

2021-06-07 23:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    @JsonSerialize(using = EntityIdSerializer.class)
Fixed

2021-06-08 20:25 UTC, ijungmann requested changes
Some really good work here, just a few things.

2021-06-08 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenId.java
> +    private EntityId tokenId;
I noticed later this leads to `token.getTokenId().getTokenId().getId()`, which is a little rough.  I wonder if we want to call this just `id` since it's the only EntityId in this class, the `token` is implied by the class name?

2021-06-08 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        // entity could experience multiple updates in a single record file, handle updates in memory for this case
I'm thinking this comment was copied from `onEntity` since none of the other `on`s have it.  I'm not opposed to having the comment multiple places, but I would put it on the others as well (and change to specify the specific entity type) or remove this here.

2021-06-08 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedEntity.setMemo(newEntity.getMemo());
Don't think this belongs here.

2021-06-08 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        cachedToken.setModifiedTimestamp(newToken.getModifiedTimestamp());
Think I would prefer this outside of the chain of ifs, either before or after.

2021-06-08 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityIdRepositoryCustomImplTest.java
> +                " do nothing";
These might prove difficult to maintain, though I don't have a better option.

2021-06-08 23:34 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +
Will revert. Left over from a previous refactor when I started coding the performance test in here for easy access to existing methods

2021-06-08 23:40 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityIdRepositoryCustomImplTest.java
> +                " do nothing";
Yeah, the maintenance challenge is the whole inspiration for the generated sql.
In this case any tests failure produce by updating the domain or custom repositories list of selected/update fields will resort in a sort of snapshot failure in this test where the change in sql will be easy to see.
Will think on it also

2021-06-08 23:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedEntity.setMemo(newEntity.getMemo());
Good catch, will remove

2021-06-08 23:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        cachedToken.setModifiedTimestamp(newToken.getModifiedTimestamp());
Yeah easier to read in that way. Will move to end

2021-06-08 23:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Opened ticket [2098](https://github.com/hashgraph/hedera-mirror-node/issues/2098)

2021-06-09 15:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java
> +public class TokenAccountId implements Serializable {
We could also consider making subpackages based on the service, like we have for the `TransactionSuppliers` in the data generator, but I think that would be better left to a different PR if we do that.

2021-06-09 15:39 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenId.java
> +    private EntityId tokenId;
Makes sense, it's only worth so much effort to try to improve.

2021-06-09 22:58 UTC, steven-sheehy requested changes
Still need to look at the sql generation more

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        cachedEntity.setAutoRenewPeriod(newEntity.getAutoRenewPeriod());
Shouldn't we check if null so it doesn't get cleared?

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedEntity.setMemo(newEntity.getMemo());
What about all the other fields that can be updated by update transactions like autorenewaccount, submitkey, etc.?

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AbstractUpdatableDomainRepositoryCustom.java
> +import software.amazon.awssdk.utils.CollectionUtils;
Wrong collection util

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +                return ""; // Key.getDefaultInstance() case
Why would we differentiate between null and Key.getDefaultInstance()? Most getters return `Key.getDefaultInstance()` so this will be updating key fields from null before to empty string.

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +
This seems to be unused as it doesn't have a `@BeforeAll`. It shouldn't be necessary as the cache is already cleared before each test via `ResetCacheTestExecutionListener`.

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java
> +                entity.setCreatedTimestamp(DEFAULT_CREATED_TIMESTAMP);
This would be slightly less hacky and more future proof if you do:
```java
if (dataCase.name().contains("Create")) {
  entity.set...
} else if (dataCase.name().contains("Delete")) {
  entity.set...
}
```

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepositoryCustomImpl.java
> +    public static final String TEMP_TABLE = "schedule_temp";
We don't need to hardcode this. It can just be `TABLE + "_temp"`.

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAccountRepositoryCustomImpl.java
> +                getTableColumnName(getTemporaryTableName(), TokenAccountId_.TOKEN_ID),
I'm starting to miss the giant raw sql...This is quite a bit more code. We'll have to look into adding annotations to the domain in the future that we can use to consolidate this to one SQL generating class.

2021-06-09 22:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java
> +public interface UpdatableDomainRepositoryCustom {
These are not repositories, they are basically sql generator classes. We should use custom repository methods that hide all this complicated logic. Custom repository interfaces would be added to the existing repository interface so you can inject a `TokenRepository` and call both the CRUD methods and the upsert methods.

```java
public interface UpsertableRepository<T> {
    void createTemp();
    void insertFromTemp();
    void updateFromTemp();
}
```

Or we should rename these to something else and move them to a sub-package. Something like `com.hedera.mirror.importer.repository.upsert.UpsertQueryGenerator`.

2021-06-09 23:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? " " : value);
If we do that there will never be a case where we set a NullableString to null. All nulls and "" will get written as empty.
That's problematic since in the update case values not being set are null.
The Update sql when reading from the temp file will then set potential existing valid value int he main table to "" when it shouldn't.

The logic here is
null -> null
"" -> " " for temp table to then be mapped to "" when writing to main table. This allows us to differentiate between unset cases and empty string cases

2021-06-09 23:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? " " : value);
Good point. Will replace the reserve character

2021-06-09 23:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    private String publicKey;
Agreed. Sql was doing some weirdness early on and put publicKey first. This was before I explicitly listed out the columns being inserted. I can revert this

2021-06-09 23:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +        module.addSerializer(EntityId.class, new EntityIdSerializer());
Will adopt this

2021-06-09 23:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +        log.info("Inserted {} rows from {} table to {} table in {}", insertCount, tableName, finalTableName,
That's fair. Will remove the others leaving the single since metrics capture the more fine grained items

2021-06-09 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepositoryCustomImpl.java
> +@Named
Will adopt

2021-06-09 23:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        cachedEntity.setAutoRenewPeriod(newEntity.getAutoRenewPeriod());
Yeah, missed this check. Will add

2021-06-09 23:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? " " : value);
Could even be some static UUID we generate. That would be even safer.

2021-06-09 23:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedEntity.setMemo(newEntity.getMemo());
Will add those 2 and will check if I'm missing anything else

2021-06-09 23:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +                return ""; // Key.getDefaultInstance() case
Mixed up logic here since public key is a nullable String.
We never actually utilize the getter when the value is `Key.getDefaultInstance()` so we'll only ever be setting keys to null or a valid string. "" doesn't map to a valid public key so I shouldn't have it here.

2021-06-09 23:50 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +
Yeah left over from some earlier testing.
Will remove

2021-06-09 23:50 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java
> +                entity.setCreatedTimestamp(DEFAULT_CREATED_TIMESTAMP);
Will adopt

2021-06-10 00:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAccountRepositoryCustomImpl.java
> +                getTableColumnName(getTemporaryTableName(), TokenAccountId_.TOKEN_ID),
Yep, I noted it would be complex because of the varied data types and meanings our domain type fields take.
Upsert was even worse.
It'd be simple if we were just inserting but sometimes you need to do a join (e.g. in the token case) and when you do that there are columns that are ambiguous and require clarification by postgres. Since the code needs to be generalized you don't want to add cases by fields but rather by data types.
Which is the cause of the verbosity

2021-06-10 00:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java
> +public interface UpdatableDomainRepositoryCustom {
Agreed, it is more of a generator now than a repository.

From my previous testing the connections used by Repository classes weren't able to observe the temp table created by the `PgCopy` class. In the above case I'm guessing the reverse would be the same.

Essentially in `SqlEntityListener` I'd then have to call `UpsertableRepository<T>.createTemp()`, then `UpsertPgCopy.copy()` and then `UpsertableRepository<T>.insertFromTemp()` and then `UpsertableRepository<T>.updateFromTemp()`.
I had this in a previous iteration but sided with moving all sql query run logic as part of the upsert embedded in the `UpsertPgCopy.copy()` so that `SqlEntityListener` didn't see any difference between an Upsertable and Insert only repository.

I'll side with renaming them and moving them to their own package as I think it's a more modularized approach than calling JPA Repository logic and PgCopy ObjectWriter logic from `SqlEntityListener`.

2021-06-10 02:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedEntity.setMemo(newEntity.getMemo());
This was a placeholder for publicKey. Updated

2021-06-10 02:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +    protected final String tableName;
Updated

2021-06-10 02:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +        return insertDurationMetric;
Updated to ternary. Either works for me

2021-06-10 02:47 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +@Log4j2
Removed

2021-06-10 02:47 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +
Removed

2021-06-10 02:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        entityIdEntities.clear();
Reorganized

2021-06-10 02:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        // entity could experience multiple updates in a single record file, handle updates in memory for this case
Added comments

2021-06-10 02:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        cachedToken.setModifiedTimestamp(newToken.getModifiedTimestamp());
Moved

2021-06-10 04:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? " " : value);
Like the UUID idea. Hopefully the larger String size doesn't impact performance much. I'll take a look

2021-06-10 08:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? " " : value);
Implemented UUID replacer

2021-06-10 08:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    private String publicKey;
Reverted

2021-06-10 08:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +        module.addSerializer(EntityId.class, new EntityIdSerializer());
Adopted

2021-06-10 08:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +        log.info("Inserted {} rows from {} table to {} table in {}", insertCount, tableName, finalTableName,
Removed extra stopwatch and moved all but one 1 log to trace

2021-06-10 08:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +        Stopwatch stopwatch = Stopwatch.createStarted();
Removed extra

2021-06-10 08:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepositoryCustomImpl.java
> +@Named
Went with `@Named`

2021-06-10 08:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        entities.put(entity.getId(), entity);
Adopted merge for this and others

2021-06-10 08:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        entityIdEntities.put(entityId.getId(), entityId.toEntity());
Consolidated and removed `OnEntityId()`

2021-06-10 08:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        cachedEntity.setAutoRenewPeriod(newEntity.getAutoRenewPeriod());
Captured missing items

2021-06-10 08:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedEntity.setMemo(newEntity.getMemo());
Captured missing items

2021-06-10 08:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AbstractUpdatableDomainRepositoryCustom.java
> +import software.amazon.awssdk.utils.CollectionUtils;
Fixed

2021-06-10 08:57 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +
Removed

2021-06-10 08:58 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java
> +                entity.setCreatedTimestamp(DEFAULT_CREATED_TIMESTAMP);
This was a bit trickier than it should have been. Cases were an issue and then naming convention, but got it working

2021-06-10 08:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepositoryCustomImpl.java
> +    public static final String TEMP_TABLE = "schedule_temp";
Fixed

2021-06-10 09:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +                return ""; // Key.getDefaultInstance() case
Actually circling back I recall.
If a user wanted to clear the key we'd again need to differentiate between the lack of setting and the actual setting.
For any nullable object null should imply if was left out. Otherwise we should adopt a zero value.
In this case an empty array should really map to an empty string. 

Need to look more into the key clearing scenario but seems it would map to an empty byte array key which I'm capturing here and with another adaptation to an existing Utility method

2021-06-10 09:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java
> +public interface UpdatableDomainRepositoryCustom {
Moved to it's own package

2021-06-10 17:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +public class UpsertPgCopy<T> extends PgCopy<T> {
Add a test class for this to cover Entities, Token, TokenAccount and Schedules

2021-06-10 17:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? " " : value);
Regardless of the above `value.equals("")` is exactly equivalent to `StringUtils.EMPTY.equals(value)` except the latter can never throw a `NullPointerException`. It doesn't change the logic at all.

2021-06-10 19:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +        gen.writeString(value.equals("") ? String.valueOf(NULLABLE_STRING_REPLACEMENT) : value);
Meant to change, was a special char previously. Will update

2021-06-10 19:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java
> +public class TokenAccountId implements Serializable {
Based not his will leave it here. Also right now it'd be just `TokenAccountId` and eventually we want to remove that embeddedId

2021-06-10 23:20 UTC, steven-sheehy requested changes

2021-06-10 23:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
As discussed offline, duplicating merge logic in application (for same ID within file) and again in upsert (for temp to regular table) could become error prone or a maintenance burden in the future. It also keeps us from dropping the cache/batching here and streaming inserts to the db using pgcopy, reducing memory usage and potentially improving latency. Most likely we won't see any create -> update or update -> update for the same ID within the same file anyway, so it's probably premature optimization.

2021-06-10 23:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
A more maintainable approach might be to use the metamodel exclude non-updatable columns instead of whitelisting like we're doing: `Sets.difference(getSingularAttributes(), notUpdatableColumns)`.

2021-06-11 01:06 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java
> +        }
The IDE forced me to change to this on a previous item but I can revert this

2021-06-11 01:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +public class UpsertPgCopy<T> extends PgCopy<T> {
Added, but can expand

2021-06-11 01:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +        insertDurationMetric = insertDurationMetric == null ? Timer.builder("hedera.mirror.importer.parse.insert")
Unintentionally left over from previous logic. There should be a code change here from what's in master

2021-06-11 05:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            log.debug("Inserted {} and updated from a total of {} rows to {}", insertCount, items
Will put them back and modify the name to encompass upsert. Will be good to track over time the performance and see the time spent doing the upsert stages at scale

2021-06-11 05:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> -                             @Qualifier(CacheConfiguration.NEVER_EXPIRE_LARGE) CacheManager cacheManager,
I think this comment was from an old iteration, already removed.

2021-06-11 22:12 UTC, xin-hedera requested changes

2021-06-11 22:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +}
can have two methods to:

1. given a column name, get `<current final table>.<snake case column name>`
2. given a column name, get `<current temp table>.<snake case column name>`

then in each generator class, can just pass the column name for either case, less error prone.

2021-06-11 22:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +        insertDurationMetric = insertDurationMetric == null ? Timer.builder("hedera.mirror.importer.parse.insert")
Fixed

2021-06-11 22:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +    public void persistItems(Collection<T> items, Connection connection) {
Updated

2021-06-11 22:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            log.debug("Inserted {} and updated from a total of {} rows to {}", insertCount, items
No logging on the metrics, just metrics unless you think trace logs are worthwhile

2021-06-11 22:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +    private final Set<Long> entityIds;
Removed

2021-06-11 22:39 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java
> +        }
Reverted

2021-06-11 22:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
Update most use cases to use a Set

2021-06-11 22:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
I have my reservations on this since the deduplication allowed us to avoid ordering concerns, but I thought about it and will adopt this approach instead. 
Fundamentally I agree with shifting some of the work to the db, simplifying things and giving ourselves room for future improvements. 

Long term I think there will be some challenges with a large db and index bloat over time but we can optimize those later.

2021-06-11 23:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
I'll work on adopting this and testing to make sure there's no ordering concerns.

2021-06-11 23:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
Not sure that's always the case. 
In some cases the not updatable fields are more than the update e.g. Schedule and TokenAccount.
Also being explicit as to what should be updated seemed safer than leaving it open to filtering non updatable columns out. 
Currently adding a new column that that isn't updatable will have no effect on the logic to generate the update sql. With your suggestion adding a new column that that isn't updatable and forgetting to add it to the `notUpdatableColumns` could result in a bug.

2021-06-11 23:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +}
Ah good suggestion, will adopt that

2021-06-12 04:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +}
Added `getFullTempTableColumnName(String camelCaseColumnName)` and `getFullTempTableColumnName(String camelCaseColumnName)`
Had to keep initial method since in the case of a join the class may need to specify a table name that is neither it's final or temp table e.g. in TokenAccount case it needs to join with Token

2021-06-12 04:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                getTableColumnName(TokenUpsertQueryGenerator.TABLE, TokenAccountId_.TOKEN_ID)));
Updated

2021-06-12 04:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java
> +                (entity.getMemo().isEmpty() && accountInfo.getMemo() != null)) {
Adopted

2021-06-12 04:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java
> +@Log4j2
Removed debugging logic

2021-06-12 13:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
To avoid churn on the PR we can defer this and get the current approach in. Just noting as a concern.

2021-06-14 13:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
Circling back, with the coalesce logic it may be fine in most cases. 
Will circle back on this so see if there are any edge cases and if I agree with the suggestion

2021-06-14 14:09 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
Yeah this probably gives more coverage also. 
As it is an update, any new column will be automatically be considered and if it passes the valid entry it'll take on the new value.
Just have to be careful about the nullable list. Will work to adopt this

2021-06-14 14:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
Lol already implemented but there was an edge case around how the sql should be updated as I was seeing some interesting behavior in tests. Would feel more comfortable doing this in a separate simpler PR.
Will revert and add a ticket.

2021-06-14 16:49 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +    }
I don't see this used.

2021-06-14 16:56 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +    }
Doesn't look like this is used.

2021-06-14 17:09 UTC, ijungmann reviewed
Will give another pass, other than the mentioned unused code I haven't seen anything.

2021-06-14 17:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +    protected Timer insertDurationMetric;
final

2021-06-14 17:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> -                             @Qualifier(CacheConfiguration.NEVER_EXPIRE_LARGE) CacheManager cacheManager,
Seems like it's still not removed

2021-06-14 21:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> -                             @Qualifier(CacheConfiguration.NEVER_EXPIRE_LARGE) CacheManager cacheManager,
Should be gone now. Just pushed again

2021-06-14 22:42 UTC, steven-sheehy requested changes

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            stopwatch = Stopwatch.createStarted();
Since you're creating new stopwatches regardless you should push the creation of them and metric recording into the individual methods.

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final List<String> conflictTargetColumns = List.of(Schedule_.SCHEDULE_ID);
We can determine this dynamically by looking at `SingularAttribute.isId()`. For complex keys, we can expand to all nested fields in id object. Let's consider for a follow up.

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final Set<String> nullableColumns = Set.of(Schedule_.EXECUTED_TIMESTAMP);
We can determine this dynamically by looking at `SingularAttribute.isOptional()`. Let's consider for a follow up.

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    public static final String TEMP_TABLE = TABLE + "_temp";
We can lookup both of these dynamically via `EntityType.getName()`. Let's consider for a follow up.

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final Set<SingularAttribute> updatableColumns = Set.of(Schedule_.executedTimestamp);
We can determine this dynamically from attributes on `SingularAttribute` and potentially adding custom annotations to the domain fields. Let's consider for a follow up.

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java
> +    String getAttributeSelectQuery(String attributeName);
This interface seems to be a blend of two distinct use cases: sub-class method enforcement and final query generation. The former methods should be moved to protected abstract methods in `AbstractQueryUpsertGenerator`. What remains here should only be methods that are used by `PgCopyUpsert`: `getTemporaryTableName()`, `getCreateTempTableQuery()`, `getTableName()`, `getInsertQuery()`, and `getUpdateQuery()`.

2021-06-14 22:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final Set<SingularAttribute> updatableColumns = Set.of(Entity_.autoRenewAccountId,
If we add `@Value`, remove static modifiers and rename to camel case we can omit almost all of the getters. Since these are singleton being static doesn't matter.

2021-06-14 22:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
Updated logic, implementation looks a bit different as this helped me refactor a bit

2021-06-14 22:44 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +    }
Correct, removed now.

2021-06-14 22:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
> +    protected Timer insertDurationMetric;
Updated

2021-06-14 22:52 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java
> -        assertThat(accountBalanceFileRepository.count()).isEqualTo(accountBalanceFiles.size());
Will revert

2021-06-14 23:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java
> +    String getAttributeSelectQuery(String attributeName);
Yeah meant to move these out, thanks.

2021-06-14 23:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            stopwatch = Stopwatch.createStarted();
Added shared private methods to run logic and record

2021-06-14 23:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java
> +    String getAttributeSelectQuery(String attributeName);
Refactored

2021-06-14 23:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java
> +    private static final Set<SingularAttribute> updatableColumns = Set.of(Entity_.autoRenewAccountId,
Added and updated to utilize

2021-06-14 23:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> -                             @Qualifier(CacheConfiguration.NEVER_EXPIRE_LARGE) CacheManager cacheManager,
Missed the ask here. Got it this time around.

2021-06-15 01:03 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            cachedToken.setFreezeKey(newToken.getFreezeKey());
In the process of adding more SqlEntityListener tests

2021-06-15 09:45 UTC, Nana-EC reviewed
Might be worth using `@ConditionalOnProperty` on `AbstractUpsertQueryGenerator` extensions and removing FlywayDBPropoerties

2021-06-15 09:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +        if (flywayProperties.getLocations().contains(FlywayProperties.V1)) {
Maybe a better approach would be create child v2 classes and adding a @ConditionalOnProperty on the classes to note which runs in v1 and which in v2
e.g for v1
```
@ConditionalOnProperty(prefix = "spring.flyway", name = "locations", havingValue = "classpath:db/migration/v1",
        matchIfMissing = true)
```

2021-06-15 14:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final List<String> conflictTargetColumns = List.of(Schedule_.SCHEDULE_ID);
Yeah, got the reflective logic working for this but agreed on not adding more code churn here so I'll leave it for later.

2021-06-15 15:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            stopwatch = Stopwatch.createStarted();
Ok, now there's 2 methods per action instead of one. That's not very encapsulated. But don't want code to churn anymore. Consider using `metric.record(() -> someAction(foo))` in a follow up.

2021-06-15 15:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +        if (flywayProperties.getLocations().contains(FlywayProperties.V1)) {
Let's not create even more classes for these upserters. Would prefer just normalizing the logic to always append created_timestamp if v2.

2021-06-15 16:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/FlywayProperties.java
> +public class FlywayProperties {
There's already a `org.springframework.boot.autoconfigure.flyway.FlywayProperties` bean created by Spring Boot. Please use that instead of duplicating parts of that class.

Alternatively, it might be appropriate to just autowire in a single property directly into `AbstractUpsertQueryGenerator` to avoid leaking it to all children:

```java
@Value("${spring.flyway.locations:v1}"
private String version;
```

2021-06-15 16:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +        if (flywayProperties.getLocations().contains(FlywayProperties.V1)) {
This would require some domain, and table schema (column renaming and index update) modification. 
Also it still doesn't cover all cases e.g. entity doesn't use `created_timestamp` for it's primary index even though it has it.
This makes sense especially with the upserting of partial data. 
There will be cases where you may have everything but the timestamp.
In that case you would still want to hit a conflict and not insert but rather update.

2021-06-15 16:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java
> +        if (flywayProperties.getLocations().contains(FlywayProperties.V1)) {
Thinking on this more but agreed on not adding more classes

2021-06-15 19:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/FlywayProperties.java
> +public class FlywayProperties {
Thanks, adopted `@Values` approach to reduce leaking as you noted.

2021-06-15 20:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            stopwatch = Stopwatch.createStarted();
Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

2021-06-15 20:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final List<String> conflictTargetColumns = List.of(Schedule_.SCHEDULE_ID);
Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

2021-06-15 20:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final Set<String> nullableColumns = Set.of(Schedule_.EXECUTED_TIMESTAMP);
Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

2021-06-15 20:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    public static final String TEMP_TABLE = TABLE + "_temp";
Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

2021-06-15 20:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private static final Set<SingularAttribute> updatableColumns = Set.of(Schedule_.executedTimestamp);
Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

2021-06-15 20:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
Captured in [Issue 2123)(https://github.com/hashgraph/hedera-mirror-node/issues/2123)

2021-06-15 20:40 UTC, steven-sheehy approved these changes
LGTM

2021-06-15 20:50 UTC, steven-sheehy approved these changes

2021-06-15 20:50 UTC, ijungmann approved these changes

2021-06-16 14:38 UTC, merged