Add a monitor REST API
hashgraph/hedera-mirror-node pull request #2017
Opened 2021-05-24 20:49 UTC by steven-sheehy

**Detailed description**:
- Add a `/api/v1/subscriber` endpoint that lists all subscriber scenarios and if they're healthy
- Add a `/api/v1/subscriber/{name}` endpoint that gets all subscriber scenarios with that name and if they're healthy
- Add a `/api/v1/subscriber/{name}/{index}` endpoint that gets a subscriber scenario by name and index and if it's healthy
- Add an OpenAPI spec at `/api/v1/docs/openapi` and `/api/v1/docs/openapi.yaml`
- Add a Swagger UI at `/api/v1/docs`
- Add `protocol=GRPC|REST` tag to subscriber metrics
- Add validation that publish and subscribe scenario names are unique
- Add validation that there's at least one subscribe scenario if enabled
- Change default schema in chart to `public`
- Fix monitor subscriber alerts description
- Fix incorrect publish timestamp due to publishing as String but receiving as bytes
- Fix handling of invalid publish timestamp by checking if its within an acceptable range
- Refactor `RestSubscriber` to newer `MirrorSubscriber` interface that decouples subscription from metrics collection
- Refactor `TransactionPublisher` to decouple publishing from metrics collection
- Remove transaction `type` tag from subscriber metrics since it's not applicable to some REST APIs like `/api/v1/transactions/{id}`

**Which issue(s) this PR fixes**:
Fixes #1937 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-05-26 03:44 UTC, ijungmann reviewed
I'll do a second pass, but it looks good to me so far.

2021-05-26 04:37 UTC, Nana-EC requested changes
Looks good on 1st pass, some nits

2021-05-26 04:37 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/LoggingFilter.java
> +    private void onSuccess(ServerWebExchange exchange, long startTime) {
I keep looking at these 2 methods and how to share the content. The only difference is the log level.

2021-05-26 04:37 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/LoggingFilter.java
> +        } else {
nit: else not necessary, just return after `if`

2021-05-26 16:34 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-passwords.yaml
> +  HEDERA_MIRROR_IMPORTER_DB_SCHEMA: "{{ ternary "mirrornode" .Values.db.schema .Values.timescaledb.enabled }}"
Documented in the description as `Change default schema in chart to public`. If timescaledb is enabled, use `mirrornode`. Otherwise use `public`. This was missed in switch back to postgres and required manual correction in flux.

2021-05-26 16:45 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/LoggingFilter.java
> +        } else {
Not worth the effort to save 3 lines. You can use `log.log(level, ...)` but then you'd have to add a line for selecting log level based upon presence of throwable and another line to conditionally get message from throwable.

2021-05-26 16:45 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/LoggingFilter.java
> +    private void onSuccess(ServerWebExchange exchange, long startTime) {
Not worth the effort to save 3 lines. You can use log.log(level, ...) but then you'd have to add a line for selecting log level based upon presence of throwable and another line to conditionally get message from throwable.

2021-05-26 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +            String message = new String(bytes, StandardCharsets.US_ASCII);
Added comment

2021-05-26 16:46 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/Utility.java
> +        if (messageSize > message.length()) {
Changed to `requestedMessageSize` and flipped order of operands to make it clearer

2021-05-26 18:38 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/LoggingFilter.java
> +    private void onSuccess(ServerWebExchange exchange, long startTime) {
Right that was my thought.

2021-05-26 22:46 UTC, Nana-EC approved these changes
Looks good, some minor style nits if you get around to it.

2021-05-26 22:46 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
> +                .setMessage(!message.isEmpty() ? message.getBytes(StandardCharsets.UTF_8) : Utility
nit: for readability better to do 
```suggestion
                .setMessage(message.isEmpty() ? Utility.generateMessage(messageSize) : message.getBytes(StandardCharsets.UTF_8)
```

2021-05-26 22:46 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
> +        Throwable throwable = publishException.getCause() != null ? publishException.getCause() : publishException;
nit: same here, better to go for positive scenario first
```suggestion
        Throwable throwable = publishException.getCause() == null ? publishException : publishException.getCause();
```

2021-05-27 15:09 UTC, ijungmann approved these changes

2021-05-27 15:27 UTC, xin-hedera approved these changes
LGTM

2021-05-27 15:36 UTC, merged