Various production improvements
hashgraph/hedera-mirror-node pull request #2029
Opened 2021-05-28 16:08 UTC by steven-sheehy

**Detailed description**:
- Add consensus to cloud latency graph to importer dashboard
- Add consensus to download latency graph to importer dashboard
- Add Spring configuration properties metadata for autocomplete & documentation when editing `application.yml`
- Bump chart dependencies
- Bump image tags for Prometheus, PostgreSQL, Redis, TimescaleDB
- Change monitor and importer alert thresholds to reflect mainnet
- Change monitor auto-creation of entities to always set `adminKey` to operator
- Change monitor timeouts and switch from records to receipts to reduce errors in mainnet
- Change REST API page limits from 1000 to 500 to improve performance
- Disable kube proxy monitoring since it doesn't work
- Enable kube API server monitoring
- Fix cAdvisor metrics missing by re-enabling kubelet monitoring
- Fix Grafana not working with multiple clusters and a single domain name
- Fix Grafana not working with port forwarding
- Fix monitor dashboard showing zero for subscriber rate
- Fix REST API dashboard showing the sum of resources for all pods
- Fix REST API database connection pool not shutting down gracefully
- Fix TimescaleDB PodMonitor always being created
- Improve REST API performance at higher load by bumping resource limits & max replicas
- Improve Traefik performance at higher load by bumping resource limits

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Sorry for the hodgepodge of changes.

IDE autocomplete in action:

![Screen Shot 2021-05-27 at 22 08 05](https://user-images.githubusercontent.com/17552371/119923821-15380a00-bf38-11eb-8f20-194552901614.png)

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-05-28 21:50 UTC, xin-hedera requested changes

2021-05-28 21:50 UTC, xin-hedera commented on hedera-mirror-rest/health.js
> +};
I don't think we need the delay by `setTimeout` at all. `terminus` doc highlighted the use case that for  load-balancers (like the nginx ingress controller)  other than the k8s services, the load balancer may not remove the pod even though it's signaled to shutdown, so the delay here (longer than the readiness probes interval) is needed for the load balancer to mark the pod as not ready.

The reason I bring it up is, the promise chaining won't work for the purpose that after the pool ends, delay `config.shutdown.timeout`.

So if we don't need the delay, we can simply do `return pool.end()` here.

on the other hand, to make the delay work, we have to sth like

```javascript
return pool.end().then(
  () => new Promise((resolve) => setTimeout(resolve, config.shutdown.timeout)),
  () => new Promise((resolve) => setTimeout(resolve, config.shutdown.timeout))
);
```

2021-05-28 22:00 UTC, steven-sheehy commented on hedera-mirror-rest/health.js
> +};
I'm not 100% sure, but I think Traefik just uses the kubernetes services to get the endpoints and then route directly to pods. It has its own internal load balancing schemes.

2021-05-28 22:06 UTC, steven-sheehy commented on hedera-mirror-rest/health.js
> +};
But then if that pod does go unready then the endpoints will be updated and Traefik should see that and stop routing new connections to it. So think you're right and we can remove the timeout.

2021-05-28 22:35 UTC, steven-sheehy commented on hedera-mirror-rest/health.js
> +};
Done

2021-05-29 00:36 UTC, xin-hedera approved these changes
LGTM

2021-06-01 15:35 UTC, ijungmann approved these changes

2021-06-01 15:46 UTC, merged