Support liveness probe delay flyway
hashgraph/hedera-mirror-node pull request #2051
Opened 2021-05-31 20:23 UTC by ijungmann

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1898 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-06-01 03:46 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +  timeoutSeconds: 2
It may be beneficial to also add a startup probe to allow for some more delay initially.

2021-06-01 03:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayProperties.java
> +@ConfigurationProperties("spring.flyway")
Properties not being autowired now that flyway is not automatically running, however I think it still makes sense to keep the properties in this section.

2021-06-01 03:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayProperties.java
> +    private String locations = "classpath:db/migration/v1";
Make singular, or change to a list.

2021-06-01 03:59 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FlywayMigrationsCommandLineRunnerTest.java
> +    void verifyMigrationCompleteAndEventReceived() {
I have not figured out a great way to test this beyond "did it run?"   The migration is ran before the test starts, I wanted to see if I could write something to hit the health endpoint as the migrations ran, but considering how the tests start up I'm not sure there's a great way to prove it.  I have manually tested in K8s to confirm however.

2021-06-02 16:39 UTC, steven-sheehy requested changes

2021-06-02 16:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        dbMigrationsFinished = true;
I found out how the embedded web servers are started. It's via `SmartLifecycle` and the `LifecycleProcessor`. So the web server is created pretty early in the startup but not started until the very end. The approach you use here is reasonable but it has some drawbacks:

- Duplicates Spring Boot's Flyway logic and classes and as a result might have subtle regressions
- Couples Flyway to Downloader
- Breaks things if we add another entrypoint to the system besides Downloader

Instead, I would suggest we use a less obtrusive hack. We can get the `WebServerStartStopLifecycle` bean that starts the web server and start it manually ourselves before Flyway:

```java
    FlywayConfigurationCustomizer flywayConfigurationCustomizer(ApplicationContext applicationContext) {
        SmartLifecycle smartLifecycle = applicationContext.getBean("webServerStartStop", SmartLifecycle.class);
        smartLifecycle.start();
  }}
```

2021-06-02 17:06 UTC, Nana-EC requested changes
Looking good some thoughts. Also I see some other comment will probably result in some refactoring so I'll wait on those

2021-06-02 17:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        dbMigrationsFinished = true;
Or can use dependency injection to get the smart lifecycle:
```java
@Resource("webServerStartStop")
private SmartLifeCycle webServerStartStop;
```

2021-06-02 17:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        dbMigrationsFinished = true;
I agree, the CommandLineRunner always felt sort of hacky and was just the only way I could find to get control without moving the migrations elsewhere.  Good find, I don't think I would've ever found that bean, that appears to be working (testing in minikube right now) and will pretty much nix all of this code save the chart change.

We already had a `FlywayConfigurationCustomizer` bean for other reasons, I will just put that back and add this logic to that with a comment.

2021-06-02 17:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayProperties.java
> +@ConfigurationProperties("spring.flyway")
Removed this entirely due to bigger changes.

2021-06-02 17:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayProperties.java
> +package com.hedera.mirror.importer.migration;/*
Removed this entirely due to bigger changes.

2021-06-02 17:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayMigrationsCommandLineRunner.java
> +/*
Removed this entirely due to bigger changes.

2021-06-02 17:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +    Flyway flyway() {
Agreed, this was fixed by bigger changes and is now back to being automatically set.

2021-06-02 17:46 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +    protected boolean dbMigrationsFinished = false;
Removed this entirely due to other changes.

2021-06-02 17:46 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayProperties.java
> +    private Map<String, String> placeholders;
Removed this entirely due to bigger changes.

2021-06-02 17:46 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FlywayProperties.java
> +    private String user;
Removed this entirely due to bigger changes.

2021-06-02 17:47 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/application.yml
> +    enabled: false
Removed this, however I added a comment to the new code to highlight what we are doing.
And you are correct, this means Spring won't run the Flyway migrations, but they can still be run manually if you set the code up to do so.

2021-06-02 17:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        dbMigrationsFinished = true;
Adding it to FlywayConfigurationCustomizer is not really important. It can be anywhere in that configuration file really.

2021-06-02 18:13 UTC, ijungmann commented
@steven-sheehy Put in a migration with a massive delay, Spring liveness probe showed as `UP` for the entire duration.

2021-06-02 18:45 UTC, steven-sheehy requested changes
Think we should probably remove streamFileActivity from liveness probe. I believe it will fail if we're doing a long running migration.

2021-06-02 18:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +        smartLifecycle.start();
Thinking on this more, this probably would be clearer with dependency injection and using a `@PostConstruct` in the same class, assuming it still works:

```java
@Resource("webServerStartStop")
private SmartLifecycle webServerStartStop;

@PostConstruct
void init() {
  webServerStartStop.start();
}
```

2021-06-02 18:45 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +  timeoutSeconds: 2
Don't think it's necessary since our liveness probe should be healthy pretty early now with this change.

2021-06-02 20:31 UTC, ijungmann commented
> Think we should probably remove streamFileActivity from liveness probe. I believe it will fail if we're doing a long running migration.

I did some testing on this, it appears the timer isn't even registered with the meterRegistry until after the migrations finish, and we return UNKNOWN if that is true before doing any other checks.  So it appears we are safe here.

2021-06-02 20:32 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +        smartLifecycle.start();
Tested, looks like it works, added.

2021-06-02 20:33 UTC, ijungmann commented on charts/hedera-mirror-importer/values.yaml
> +  timeoutSeconds: 2
Sure, should be fine for now, was just pondering for the future if we ever ran into other issues that caused a slower startup.

2021-06-02 20:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +    FlywayConfigurationCustomizer flywayConfigurationCustomizer(ApplicationContext applicationContext) {
Unused parameter

2021-06-02 20:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +    FlywayConfigurationCustomizer flywayConfigurationCustomizer(ApplicationContext applicationContext) {
Whoops, removed.

2021-06-02 20:38 UTC, steven-sheehy approved these changes
LGTM

2021-06-02 20:46 UTC, xin-hedera approved these changes
LGTM

2021-06-02 22:25 UTC, steven-sheehy commented
Need to update your PR description

2021-06-02 22:27 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-06-02 23:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +    @Qualifier("webServerStartStop")
Tests do not generate this bean in time and fail out (and apparently cancel instead of actually finishing)...  Thus this is here.

2021-06-02 23:22 UTC, steven-sheehy approved these changes

2021-06-02 23:27 UTC, Nana-EC requested changes
Looks good. Wondering if an additional running check is needed though

2021-06-02 23:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +        if (webServerStartStop != null) {
Should this include a running check?
```suggestion
        if (webServerStartStop != null && !webServerStartStop.isRunning()) {
```

2021-06-02 23:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +        if (webServerStartStop != null) {
Based on offline discussion this doesn't seem to be needed

2021-06-02 23:29 UTC, Nana-EC approved these changes
LGTM

2021-06-02 23:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +        if (webServerStartStop != null) {
I don't think this would come up, the `start()` comes later in the lifecycle, after bean instantiation (and postInit).

2021-06-02 23:31 UTC, merged