NFT Design Doc V2
hashgraph/hedera-mirror-node pull request #2061
Opened 2021-06-01 21:40 UTC by ijungmann

**Detailed description**:

Update NFT design with new information
- Change `memo` to `metadata` 
- Update token types
- Add `tokenSupplyType`
- Remove `/balance` info.

**Which issue(s) this PR fixes**:
Fixes #2057 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-06-01 22:00 UTC, ijungmann commented on docs/design/nft.md
> -
Have not gotten 100% confirmation on this, but it's likely we will get `NFT balance` as just a token balance, where the balance is really "number of NFTs of this token type owned".  This wouldn't require any changes from us and should just work inside the existing logic, so I've removed this entirely.

2021-06-01 22:03 UTC, ijungmann commented on docs/design/nft.md
>  - GET `/api/v1/tokens/{id}/nfts` will list basic information of all NFTs for a given token.
There was some discussion around changing this because we may eventually have `FUNGIBLE_UNIQUE` tokens as well that could go under here.  However, since we want to follow HAPI in our naming convention, and the indication is now that `FUNGIBLE_UNIQUE` tokens will have their own queries (and possibly their own data structures), I've decided to leave this as is.

2021-06-02 17:16 UTC, Nana-EC commented on docs/design/nft.md
> +- Add to `token` table fields `type` (enum, values `FUNGIBLE_COMMON` and `NON_FUNGIBLE_UNIQUE`), `token_supply_type` (
Yeah in future, the max_supply could be less than max long but represent the finite number of tokens desired.
I'd include it as intended

2021-06-02 17:39 UTC, Nana-EC requested changes
Minor suggestion, updates look inline with expected proto updates

2021-06-02 17:39 UTC, Nana-EC commented on docs/design/nft.md
> +- `insertTokenMint()` must be updated to handle the new field `metadata` and create and persist the `NFTs` if type
Additionally, it should be able to handle a list of NFT's since the receipt now has `serialNumbers` and not a single `serialNumber`

2021-06-02 17:52 UTC, ijungmann commented on docs/design/nft.md
> +- `insertTokenMint()` must be updated to handle the new field `metadata` and create and persist the `NFTs` if type
Sure, added line `Multiple `NFTs` can be minted in one transaction.` to this section to highlight this.

2021-06-02 19:37 UTC, steven-sheehy requested changes

2021-06-02 19:37 UTC, steven-sheehy commented on docs/design/nft.md
> +  confirmed if the balance file (specifically `TokenUnitBalance`) will also be updated.
They did update the comment to note that it will.

2021-06-02 19:37 UTC, steven-sheehy commented on docs/design/nft.md
> +2. Will NFT balances be added to the csv version of the balance file, or just the proto version? If so, will this be
CSV will be deprecated in the July release. NFTs won't be available until the July or later release. I think we can safely say it won't be updated and remove/answer this.

2021-06-02 19:50 UTC, xin-hedera requested changes

2021-06-02 19:50 UTC, xin-hedera commented on docs/design/nft.md
> +  metadata              text    default ''      not null,
the type of `metadata` is `bytes` in protobuf

2021-06-02 19:50 UTC, xin-hedera commented on docs/design/nft.md
> +      "metadata": "This is a test NFT",
need to change it to hex or other encoding as it's `bytes` now

2021-06-02 20:39 UTC, ijungmann commented on docs/design/nft.md
> +  confirmed if the balance file (specifically `TokenUnitBalance`) will also be updated.
Great, I will remove this question, no changes needed for this.

2021-06-02 20:40 UTC, ijungmann commented on docs/design/nft.md
> +2. Will NFT balances be added to the csv version of the balance file, or just the proto version? If so, will this be
Makes sense, I will remove the question.

2021-06-02 20:51 UTC, ijungmann commented on docs/design/nft.md
> +  metadata              text    default ''      not null,
Good catch, fixed.

2021-06-02 20:51 UTC, ijungmann commented on docs/design/nft.md
> +      "metadata": "This is a test NFT",
Changed it to `metadata_base64` to match `transaction.memo_base64` and added a note that it needs to be encoded.

2021-06-02 21:45 UTC, xin-hedera requested changes
just a small issue

2021-06-02 21:45 UTC, xin-hedera commented on docs/design/nft.md
> +  metadata              bytea   default ''      not null,
```suggestion
  metadata              bytea ,
```

2021-06-02 21:59 UTC, xin-hedera commented on docs/design/nft.md
> +  metadata              bytea   default ''      not null,
not quite sure about if we should keep `not null`.

the nft proto changes:

```
message TokenMintTransactionBody {
    TokenID token = 1; // The token for which to mint tokens. If token does not exist, transaction results in INVALID_TOKEN_ID
    uint64 amount = 2; // Applicable to tokens of type FUNGIBLE_COMMON. The amount to mint to the Treasury Account. Amount must be a positive non-zero number represented in the lowest denomination of the token. The new supply must be lower than 2^63.
    repeated bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. A list of metadata that are being created. Maximum allowed size of each metadata is 100 bytes
}
```

so the number of `metadata` determines the number of ntfs to mint. so the real question is whether a metadata entry can be set to null in the above protobuf.

2021-06-02 22:22 UTC, steven-sheehy commented on docs/design/nft.md
> +      "metadata": "This is a test NFT",
I'm not a fan of appending the encoding format to the field name. I think `transaction.memo_base64` is our only example of that and every other bytea field we return it without that suffix. I think it should match the proto name. So just `metadata`.

2021-06-03 15:34 UTC, ijungmann commented on docs/design/nft.md
> +  metadata              bytea   default ''      not null,
That's a good question, I will ask in the protobuf PR about that.

2021-06-03 16:17 UTC, xin-hedera commented on docs/design/nft.md
> +  metadata              bytea   default ''      not null,
checked existing protobuf and the generated java code, null is not allowed and java code will throw NPE, so we should keep `not null`

2021-06-03 16:34 UTC, ijungmann commented on docs/design/nft.md
> +- Add to `token` table fields `type` (enum, values `FUNGIBLE_COMMON` and `NON_FUNGIBLE_UNIQUE`), `token_supply_type` (
Makes sense, now that I'm doing the SQL I think it should just be `supply_type` though, like `type` we can already infer from the `token` table.

2021-06-03 16:37 UTC, ijungmann commented on docs/design/nft.md
> +  metadata              bytea   default ''      not null,
Sure.  I'm still curious if the default (empty bytes) is allowed, but that won't have any effect here.

2021-06-04 15:28 UTC, ijungmann commented on docs/design/nft.md
> +  metadata              bytea   default ''      not null,
From discussion, "It seems that having empty metadata is pointless".  So we should be fine.  Would you like me to remove the default still, or just keep this as is?

2021-06-04 15:35 UTC, ijungmann commented on docs/design/nft.md
> +      "metadata": "This is a test NFT",
Alright, sure, swapped the name back.

2021-06-04 18:06 UTC, xin-hedera approved these changes
LGTM

2021-06-04 18:40 UTC, steven-sheehy approved these changes
LGTM

2021-06-04 18:44 UTC, Nana-EC approved these changes
LGTM

2021-06-04 21:20 UTC, merged