NFT Database Schema
hashgraph/hedera-mirror-node pull request #2070
Opened 2021-06-03 23:28 UTC by ijungmann

**Detailed description**:
Add Flyway migrations to support NFTs (based on NFT design doc)

- Update `token` table with new values
- Add `nft` and `nft_transfer`  tables, indexes, etc.
- Add new Response Codes

**Which issue(s) this PR fixes**:
Fixes #2056 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-06-07 15:06 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column max_supply bigint not null default 9223372036854775807,
Max long

2021-06-07 15:10 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +
Remove

2021-06-07 15:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +values ('ACCOUNT_EXPIRED_AND_PENDING_REMOVAL', 223),
This one isn't part of the NFT protobufs change, but I noticed we were missing it.

2021-06-08 04:57 UTC, Nana-EC requested changes
Some discrepancies on the `type`. Also left some nits.

2021-06-08 04:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
I believe the default should be `FUNGIBLE_COMMON`
```suggestion
    add column type character varying(20) not null default 'FUNGIBLE_COMMON';
```

2021-06-08 04:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +comment on table nft is 'NFT';
nit: Something more suggestive. Template suggestions below that you can modify.
```suggestion
comment on table nft is 'Non Fungible Tokens (NFTs) minted on network';
```

2021-06-08 04:57 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    type                   character varying(20) not null default 'NON_FUNGIBLE_UNIQUE',
Same thing above, this should be `FUNGIBLE_COMMON` right?
```suggestion
    type                   character varying(20) not null default 'FUNGIBLE_COMMON',
```

2021-06-08 15:33 UTC, steven-sheehy requested changes

2021-06-08 15:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    on nft_transfer (consensus_timestamp, token_id, serial_number);
Should be descending. Same for v2

2021-06-08 17:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
I vote smallint type to be conformant with other enum types we have right now.
If we ever go enumerated we should do it for all.

2021-06-08 17:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
I disagree. If we wait for perfection we'll never get anything done. Better to improve things while we can.

2021-06-08 22:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
Correct, not sure why I got that swapped.  Fixed.

2021-06-08 22:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +comment on table nft is 'NFT';
I like that, just made `Non Fungible` into `Non-Fungible`

2021-06-08 22:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    type                   character varying(20) not null default 'NON_FUNGIBLE_UNIQUE',
Yep, fixed.

2021-06-08 22:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
Sure, I agree, I like the enumarated type.  Added those, looks like it's working

2021-06-08 22:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column supply_type character varying(10) not null default 'INFINITE',
Fixed.

2021-06-08 22:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    on nft (token_id, serial_number);
Added

2021-06-08 22:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    on nft_transfer (consensus_timestamp, token_id, serial_number);
Added

2021-06-08 22:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
Sure, it's a note for consistency. 
I'm open to enumerated if possible. 
If we do then let's open a ticket to transform the rest over in a future sprint or do it in v2 of the schema.

2021-06-08 23:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +
Any opinions on creating all enums at the top vs. creating them in their corresponding table sections?

2021-06-08 23:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +    add column type character varying(20) not null default 'NON_FUNGIBLE_UNIQUE';
Sure, I can create a ticket for that.

2021-06-09 02:12 UTC, merged