Add workflow for building on windows
hashgraph/hedera-mirror-node pull request #2089
Opened 2021-06-08 04:02 UTC by si618

**Detailed description**:
Add workflow to build mirror node on Windows Server 2019 virtual environment for pull requests to master.

Tests are skipped as they are not supported in windows-2019 virtual environment.

**Which issue(s) this PR fixes**:
Fixes #2072

2021-06-08 15:42 UTC, steven-sheehy requested changes

2021-06-08 15:42 UTC, steven-sheehy commented on .github/workflows/windows.yml
> +  publish:
```suggestion
  build:
```

2021-06-08 15:42 UTC, steven-sheehy commented on .github/workflows/windows.yml
> +      - name: Build
```suggestion
      - name: Maven package
```

2021-06-08 15:42 UTC, steven-sheehy commented on .github/workflows/windows.yml
> +          path: ~/.m2
Re-ran this check and I still see:

`Cache not found for input keys: Windows-m2-658d1cb73799c8a7daa2214b7ce1642bd1f4a294eda9cd4c510b68c77119e76e, Windows-m2`

This is causing the build to take a long time pulling the dependencies. Should this path be a Windows path? Or is this just because it's a fork? Does it cache in your project?

2021-06-08 15:42 UTC, steven-sheehy commented on .github/workflows/windows.yml
> +          check-latest: true
Can omit. I prefer a faster test at the expense of a potentially slightly dated JDK.

2021-06-09 00:27 UTC, si618 commented on .github/workflows/windows.yml
> +          path: ~/.m2
Yes, the cache appeared to be restored on my fork on subsequent builds. Output from [Cache Maven packages](https://github.com/si618/hedera-mirror-node/runs/2770179701?check_suite_focus=true) step. 
```
Run actions/cache@v2
  with:
    key: Windows-m2-658d1cb73799c8a7daa2214b7ce1642bd1f4a294eda9cd4c510b68c77119e76e
    path: ~/.m2
    restore-keys: Windows-m2
  env:
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\11.0.11-9\x64
Received 134217728 of 438196083 (30.6%), 126.4 MBs/sec
Received 331350016 of 438196083 (75.6%), 156.7 MBs/sec
Received 438196083 of 438196083 (100.0%), 90.1 MBs/sec
Cache Size: ~418 MB (438196083 B)
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/e28afba9-4cc2-4b34-8a4a-08eca5a95769/cache.tgz -P -C D:/a/hedera-mirror-node/hedera-mirror-node
Cache restored successfully
Cache restored from key: Windows-m2-1d62deeffc804faadc061e2e1f2709c84e2d7b1eb3ecf7a46b4c46c8c0107b0b
```
However, I'm not sure why the action key `Windows-m2-658d1c...` differs from restored key `Windows-m2-1d62de...`? 

Looking back at the [first build](https://github.com/si618/hedera-mirror-node/runs/2742462612?check_suite_focus=true), the action cache key is `Windows-m2-1d62de...`

```
Run actions/cache@v2
  with:
    key: Windows-m2-1d62deeffc804faadc061e2e1f2709c84e2d7b1eb3ecf7a46b4c46c8c0107b0b
    path: ~/.m2
    restore-keys: Windows-m2
  env:
    MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\11.0.11-9\x64
Cache not found for input keys: Windows-m2-1d62deeffc804faadc061e2e1f2709c84e2d7b1eb3ecf7a46b4c46c8c0107b0b, Windows-m2
```

I wonder if it's because I renamed the workflow (for consistency) and that confused things?  We should be able to verfiy on next push.

2021-06-09 03:41 UTC, si618 commented
@steven-sheehy removing JDK version [broke ](https://github.com/hashgraph/hedera-mirror-node/pull/2089/checks?check_run_id=2780014642) the build
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) 
on project hedera-mirror-importer: Fatal error compiling: invalid target release: 11 -> [Help 1]
```
Windows-2019 virtual environment [states](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#java) JDK v8 is the default with v11 and v13 being other options pre-installed, unless we want to install a more recent version?

2021-06-09 03:45 UTC, si618 commented on .github/workflows/windows.yml
> +          check-latest: true
Removing JDK version [broke](https://github.com/hashgraph/hedera-mirror-node/pull/2089/checks?check_run_id=2780014642#step:4:81) the build
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) 
on project hedera-mirror-importer: Fatal error compiling: invalid target release: 11 -> [Help 1]
```
Windows-2019 virtual environment [states](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#java) JDK v8 is the default with v11 and v13 being other options pre-installed, so will need to be 11 or 13 unless we want to install a more recent version?

2021-06-09 03:45 UTC, si618 commented on .github/workflows/windows.yml
> +          path: ~/.m2
[Cache appears ok](https://github.com/hashgraph/hedera-mirror-node/pull/2089/checks?check_run_id=2780014642#step:4:81) now?

2021-06-09 03:47 UTC, steven-sheehy commented on .github/workflows/windows.yml
> +          check-latest: true
I just meant you can omit `check-latest: true`. The rest should stay.

2021-06-09 04:02 UTC, si618 commented on .github/workflows/windows.yml
> +          check-latest: true
Sorry, took you too literally :) Fix pushed and build working again.

2021-06-09 14:57 UTC, steven-sheehy approved these changes
LGTM. Thanks!

2021-06-09 15:11 UTC, xin-hedera approved these changes
LGTM

2021-06-09 15:16 UTC, merged