Dissociate accounts from tokens post run
hashgraph/hedera-mirror-node pull request #2090
Opened 2021-06-08 06:07 UTC by Nana-EC

**Detailed description**:
Many of the HTS acceptance tests associate the payer account with the newly created token.
Overtime this may build up and the account may hit the TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED error.

Full `@acceptance` runs are also expensive and it might be worth being a bit more selective on tests included for every post deployment run

- Dissociate accounts from tokens post run
- Add `@extended` flag for acceptance tests and move some tests there

**Which issue(s) this PR fixes**:
Fixes #2069 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-06-08 16:18 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +                tokenClient.disssociate(accountId, tokenId);
protobuf doc says:

` If the provided account has a nonzero balance with any of the provided tokens, the transaction will resolve to TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES.`

So looks like without wiping the account or transferring all the tokens out, the dissociate will fail.

2021-06-09 00:53 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +                tokenClient.disssociate(accountId, tokenId);
Yeah you're right. Looking into this

2021-06-09 01:00 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +                tokenClient.disssociate(accountId, tokenId);
Deleting the token first allows for dissociation after. I could do that or I could get the token balance and wipe that amount before dissociating

2021-06-09 15:31 UTC, xin-hedera requested changes
just some minor issues

2021-06-09 15:31 UTC, xin-hedera commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
```suggestion
    ./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@critical"
```

2021-06-09 15:31 UTC, xin-hedera commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
```suggestion
    ./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@release"
```

2021-06-09 16:12 UTC, steven-sheehy requested changes

2021-06-09 16:12 UTC, steven-sheehy commented on hedera-mirror-test/README.md
> +Search for @? tags within the .feature files for other applicable tags.
I always see this and am too lazy to search. It would be really nice to explicitly list all tags and rough description of what they contain here.

2021-06-09 16:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/hcs/hcs.feature
> -    @sanity @basicsubscribe @acceptance @Acceptance
Should update description to include removing camel case tag variants

2021-06-09 17:33 UTC, ijungmann requested changes
Looks good, couple small things.

2021-06-09 17:33 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Given("I successfully create a new token account with freeze status {int} and kyc status {int}")
Should this just be `create a new token`?  Or is it meant to imply that it's also creating the association as the treasury?

2021-06-09 17:33 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        if (tokenId != null) {
Should this set tokenId to null as well, as it does in `TokenFeature`?

2021-06-09 17:34 UTC, ijungmann commented
Should we set the default Dockerfile command to use `@critical` or `@release` instead of `@balancecheck`?

2021-06-09 20:15 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
Good suggestion, will adopt this

2021-06-09 20:16 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +`@release` - Test cases to verify a new deployed version satisfies core scenarios and is release worthy.
They'll likely change with new test cases or fee schedule changes though

2021-06-09 20:17 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +Search for @? tags within the .feature files for other applicable tags.
Haha true, I was hesitant to note the others as they don't get much transaction and would be used for more local development checks

2021-06-09 20:17 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hcs/hcs.feature
> -    @sanity @basicsubscribe @acceptance @Acceptance
Will do

2021-06-09 20:18 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Given("I successfully create a new token account with freeze status {int} and kyc status {int}")
Initially onboard implied you created and associated an account to a new token. However, with reverting back to using the paying account as the treasury it automatically gets associated.

2021-06-09 20:18 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        if (tokenId != null) {
Ah yes, it should for consistency

2021-06-09 20:19 UTC, Nana-EC commented
> Should we set the default Dockerfile command to use `@critical` or `@release` instead of `@balancecheck`?

Should be `@critical` thought I fixed that

2021-06-09 20:21 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
Ugh, I liked the formatting that you get with the indentation. I can take the backtick off since the indentation call it out enough

2021-06-09 20:21 UTC, steven-sheehy commented on hedera-mirror-test/README.md
> +`@release` - Test cases to verify a new deployed version satisfies core scenarios and is release worthy.
Yep, but they give a ballpark so that we don't have to hunt through old PRs or slacks for the same estimate. Can add a note about pricing fluctuations.

2021-06-09 20:29 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +Search for @? tags within the .feature files for other applicable tags.
I'll call out the feature based tags only

2021-06-09 20:35 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        if (tokenId != null) {
Updated

2021-06-09 20:36 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hcs/hcs.feature
> -    @sanity @basicsubscribe @acceptance @Acceptance
Updated

2021-06-09 20:36 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +Search for @? tags within the .feature files for other applicable tags.
Updated

2021-06-09 20:36 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
Adopted.

2021-06-09 20:37 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
Updated. Removed the backpacks since the indentation gives it the emphasis and horizontal scrolling I was looking for with a command line input

2021-06-09 20:37 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
Modified

2021-06-09 20:37 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +    `./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`
Modified

2021-06-09 21:00 UTC, xin-hedera requested changes

2021-06-09 21:00 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +                tokenId = null;
this should go to the last line of the block

2021-06-09 21:06 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +`@release` - Test cases to verify a new deployed version satisfies core scenarios and is release worthy.
Okay, will add with note

2021-06-09 21:20 UTC, Nana-EC commented on hedera-mirror-test/README.md
> +`@release` - Test cases to verify a new deployed version satisfies core scenarios and is release worthy.
Added

2021-06-09 22:10 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +                tokenId = null;
Fixed

2021-06-09 22:55 UTC, xin-hedera approved these changes
LGTM

2021-06-09 23:05 UTC, steven-sheehy approved these changes
LGTM

2021-06-10 15:57 UTC, ijungmann approved these changes

2021-06-10 17:59 UTC, merged