Add Rosetta HTS support
hashgraph/hedera-mirror-node pull request #2093
Opened 2021-06-08 14:40 UTC by xin-hedera

**Detailed description**:
Add HTS support to Rosetta

**Which issue(s) this PR fixes**:
Fixes #1920

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-06-09 17:00 UTC, ijungmann reviewed
I'll give it a second pass, didn't see anything concerning, looks good.

2021-06-09 20:14 UTC, Nana-EC requested changes
Looking good. Reviewed up the error subpath. Will circle back to continue from persistence

2021-06-09 22:56 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/services/encoding/entityid_test.go
> +}
Temporary code, will remove

2021-06-09 23:16 UTC, Nana-EC requested changes

2021-06-10 15:15 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/construction_service.go
> +	case *hedera.TokenAssociateTransaction:
we can't do the case + multiple cases, the compiler will error out.

specifically, this is go's type switch (https://tour.golang.org/methods/16).

though in each case block, we use the same variable `tx`, they actually have different types.

more on why I have to do this instead of putting the `AddSignature` method in the `ITransaction` interaface
so these bloated lines can be just `transaction.AddSignature(pubKey, signature)`: Our go sdk is designed with
the fluent API principle, so for each transaction struct, if a method returns the transaction object itself, it's
of the concrete transaction pointer type, instead of a generic interface.

2021-06-10 15:21 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/construction_service.go
> +	case hedera.TokenAssociateTransaction:
this is a bit tricker, but it's also a constraint from the sdk.

sdk `TransactionFromBytes`:

`func TransactionFromBytes(data []byte) (interface{}, error)`

What it returns is a concrete transaction object, instead of a pointer of the transaction object.

Only a pointer of a transaction object can be implicitly converted to interface `ITransaction`, so I have to do a type switch and return the pointer.

2021-06-10 15:25 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/common.go
> +	return accountId.Shard == 0 && accountId.Realm == 0 && accountId.Account == 0
we have to check all fields.

This is a historic issue from the sdk.

SDK transaction getters in most cases return struct objects instead of pointers. In case a field of a transaction is not set, the getter will return the zero value of that field.

For `hedera.AccountID` the zero value `hedera.AccountID{}` is `hederaAccountID{Shard: 0, real:0, Account: 0}`

2021-06-10 15:32 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	AdminKey            string `gorm:"public_key"`
`public_key` matches the sql query column name. by default, with no tag, gorm will do snake case from the field name, but in the tag, we should use the column name.

2021-06-10 16:58 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +                                                                  ORDER BY tt.consensus_timestamp`
gosec somehow these lines leak credential info, most likely because of the keyword `token`

2021-06-10 17:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account/account.go
> +                                        join token t on t.token_id = tt.token_id
updated

2021-06-10 17:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/services/encoding/entityid_test.go
> +				ShardNum:  0,
added test cases

2021-06-10 17:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/token/token.go
> +// NewTokenRepository creates an instance of a TransactionRepository struct
fixed

2021-06-10 17:30 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/types/crypto_transfer.go
> +	EntityID           int64
updated

2021-06-10 17:30 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/types/token.go
> +	TokenID             int64 `gorm:"type:primaryKey"`
updated

2021-06-10 17:30 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_transfer_transaction_constructor.go
> +			log.Errorf("Transfer sum for symbo %s is not 0", symbol)
fixed

2021-06-10 18:49 UTC, xin-hedera commented on hedera-mirror-rosetta/test/db/db.go
> +	pool.MaxWait = 5 * time.Minute
default is 60 seconds. bumping it up to 5 minutes should fix the github CI test failure in case it's because the postgresql container takes really that long to initialize and begin to accept connections

2021-06-10 20:58 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/persistence/account/account.go
> +	amounts := make([]types.Amount, 0, 1+len(tokenAmounts))
Not recommendation per se, but auto format. And there's no tweaking. Everyone uses gofmt. Just Go with the flow. :)

2021-06-10 21:15 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/types/transaction.go
> +	ValidStartNS         int64
fixed

2021-06-10 23:46 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/services/construction/token_update_transaction_constructor.go
> +	if tokenUpdate.AdminKey.isEmpty() &&
Why do we need to check if every field is empty? If they want to send an empty tx, let them. The server will validate it. We should be careful about doing too much client side validation especially as this is quite brittle.

2021-06-12 00:04 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	AdminKey            string `gorm:"public_key"`
Gotcha

2021-06-12 00:06 UTC, Nana-EC commented on hedera-mirror-rosetta/app/services/construction/common.go
> +	return accountId.Shard == 0 && accountId.Realm == 0 && accountId.Account == 0
Gotcha

2021-06-12 00:11 UTC, Nana-EC commented on hedera-mirror-rosetta/app/services/construction/construction_service.go
> +	case *hedera.TokenAssociateTransaction:
Thanks for breaking that down.

2021-06-12 00:24 UTC, Nana-EC commented on hedera-mirror-rosetta/app/services/construction/construction_service.go
> +	case hedera.TokenAssociateTransaction:
Hmm there's a lot of tricky constraints, seems like a lot of it is a result of the sdk.
I'm just concerned the reasoning can get lost.
Either some of these things should result in bug to be opened to be fixed, or comments so the reasoning doesn't get lost and can be weighed when improvements are made.

2021-06-12 04:00 UTC, Nana-EC reviewed
Looks mostly good.
My only concern is there's a lot of gotchas around limitations we have to workaround due to SDK or inferred logic that isn't captured.
In this case the more comments and more granular we can make classes/methods the better for management.
I think beyond this we'll capture items in integration testing.

Will give one final pass after the other feedback is addressed/commented on.

2021-06-14 15:22 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	}
optimize the query to batch retrieve all data required to construct operations for transactions in one roundtrip

2021-06-14 15:33 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/token_update_transaction_constructor.go
> +	if tokenUpdate.AdminKey.isEmpty() &&
removed

2021-06-14 15:35 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/types/token.go
> +	TokenID             int64 `gorm:"type:primaryKey"`
should be good now

2021-06-14 15:36 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +		operationStatus := transactionResults[transactionsMap[timestamp].Result]
refactored the logic and made sure the comment is updated accordingly

2021-06-14 17:10 UTC, ijungmann approved these changes
LGTM

2021-06-14 20:59 UTC, steven-sheehy approved these changes
LGTM

2021-06-14 21:15 UTC, Nana-EC approved these changes
LGTM

2021-06-16 14:17 UTC, merged