Automate deploy to integration
hashgraph/hedera-mirror-node pull request #2102
Opened 2021-06-09 03:45 UTC by steven-sheehy

**Detailed description**:
- Add a new `master` image tag that's pushed on every commit to master
- Add ingress and middleware to monitor chart
- Add new mainnet nodes to monitor
- Bump common chart dependencies
- Bump PostgreSQL version in `docker-compose.yml` to 13.3
- Change coverage report to always upload so coverage report is accurate in PRs when one test fails
- Change minimum Docker compose format to 3.7 to support `pull_policy=always`
- Change release development workflow to update git commit to trigger rollout to integration
- Fix `docker-compose.yml` and Helm charts on master by using new `master` tag
- Fix `docker-compose.yml` not working due to init script
- Fix `Pods Memory Utilization` graph in `Kubernetes / Pods / USE` dashboard
- Fix Rosetta validate job failing for forks and Dependabot
- Merge `init_v1.sql` and `init_v2.sql` into `init.sh`
- Merge `db` and `timescaledb` container into a single `db` container
- Remove cleanup workflow since `master-<git-sha>` images are no longer produced

**Which issue(s) this PR fixes**:
Fixes #1811 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-06-09 18:47 UTC, ijungmann requested changes
Some minor notes.

2021-06-09 20:59 UTC, Nana-EC requested changes
Looking good, some suggestions

2021-06-09 20:59 UTC, Nana-EC commented on .github/workflows/release-development.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} deploy -DskipTests -Ddocker.tag.version=master
Should manually cleanup (or open a ticket) all the `master-<git-sha>` images since they'll no longer be removed after the PR goes in

2021-06-09 20:59 UTC, Nana-EC commented on .github/workflows/release-development.yml
> +      - name: Update integration deployment configuration
should we also rename the file since this is now focused on integration, especially if we plan to have one per env

2021-06-09 20:59 UTC, Nana-EC commented on charts/README.md
> +kubectl logs -f "${POD_NAME}"
+1 this

2021-06-09 20:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  USER_SQL="create user :restUsername with login password :'restPassword' in role readonly;"
Add a comment for why in the timescale case the rest user is created vs in v1 postgres the owner is altered

2021-06-09 20:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +USER_SQL="alter user :ownerUsername with createrole;"
nit: maybe a more descriptive variable Name here
```suggestion
USER_CREATE_OR_ALTER_SQL="alter user :ownerUsername with createrole;"
```

2021-06-09 23:17 UTC, steven-sheehy commented on charts/README.md
> +When running against a network other than a public network (e.g., demo/previewnet/testnet/mainnet), the network must be
My IDE and the Internet tells me otherwise.

2021-06-09 23:18 UTC, steven-sheehy commented on .github/workflows/release-development.yml
> +          commit_message: Upgrade integration to master ${{ github.sha }}
It is redundant, in my opinion. The GIT SHA will provide us an accurate message.

2021-06-09 23:19 UTC, steven-sheehy commented on charts/README.md
> +export SERVICE_IP=$(kubectl get service -n common "${RELEASE}-traefik" -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
True, I'll revert

2021-06-09 23:20 UTC, steven-sheehy commented on .github/workflows/release-development.yml
> +        run: ./mvnw ${MAVEN_CLI_OPTS} deploy -DskipTests -Ddocker.tag.version=master
Yes, was planning to cleanup after merge

2021-06-09 23:24 UTC, steven-sheehy commented on .github/workflows/release-development.yml
> +      - name: Update integration deployment configuration
Sure, but once Flux adds support for auto updating from git source we won't even need the deploy job. So in the future we should rename this to just `master`.

2021-06-09 23:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  USER_SQL="create user :restUsername with login password :'restPassword' in role readonly;"
Done

2021-06-09 23:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +USER_SQL="alter user :ownerUsername with createrole;"
Didn't like that name either. Changed it to `DB_SPECIFIC_SQL` to leave it open for future db specific statements added to it.

2021-06-10 00:31 UTC, Nana-EC approved these changes
LGTM

2021-06-10 00:48 UTC, xin-hedera approved these changes
LGTM

2021-06-10 03:57 UTC, ijungmann commented on charts/README.md
> +When running against a network other than a public network (e.g., demo/previewnet/testnet/mainnet), the network must be
Interesting, I guess I've just never noticed the comma before.

2021-06-10 03:58 UTC, ijungmann approved these changes

2021-06-10 14:48 UTC, merged