Optimize importer memory footprint
hashgraph/hedera-mirror-node pull request #2103
Opened 2021-06-10 01:40 UTC by xin-hedera

**Detailed description**:

- Replace `persistBytes` with `keepBytes` logic in downloader
- Clear `StreamFile` `bytes` and `items` in post parse
 
**Which issue(s) this PR fixes**:
Relates to #2087 

**Special notes for your reviewer**:
`DirectChannel` doesn't fit the requirement:

1. no concept of `queueCapacity`
2. subscriber of a `DirectChannel` is called in the publisher's thread

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-06-10 14:23 UTC, steven-sheehy commented
> DirectChannel doesn't fit the requirement:
> no concept of queueCapacity
> subscriber of a DirectChannel is called in the publisher's thread

But that's exactly what I stated in the call and it's what we want for balances to reduce memory usage by 66% or more. My suggestion is this:

```java
    @Bean(CHANNEL_BALANCE)
    MessageChannel channelBalance(BalanceParserProperties properties) {
        if (properties.getQueueCapacity() <= 0) {
            return MessageChannels.direct().get();
        else {
            return MessageChannels.queue(properties.getQueueCapacity()).get();
        }
    }
```

2021-06-10 14:32 UTC, xin-hedera commented
> > DirectChannel doesn't fit the requirement:
> > no concept of queueCapacity
> > subscriber of a DirectChannel is called in the publisher's thread
> 
> But that's exactly what I stated in the call and it's what we want for balances to reduce memory usage by 66% or more. My suggestion is this:
> 
> ```java
>     @Bean(CHANNEL_BALANCE)
>     MessageChannel channelBalance(BalanceParserProperties properties) {
>         if (properties.getQueueCapacity() <= 0) {
>             return MessageChannels.direct().get();
>         else {
>             return MessageChannels.queue(properties.getQueueCapacity()).get();
>         }
>     }
> ```

Then `RendezvousChannel` (https://docs.spring.io/spring-integration/api/org/springframework/integration/channel/RendezvousChannel.html) is a better fit.

2021-06-10 14:35 UTC, steven-sheehy commented
Sure, RendezvousChannel might do the trick.

2021-06-10 14:37 UTC, xin-hedera commented
Yes, 2 is the best we can get. One held in downloader and one is being processed in parser.

2021-06-10 15:54 UTC, Nana-EC requested changes
Looking good asides MessageChannel discussion. One suggestion and thinking on if the test coverage can be expanded

2021-06-10 15:54 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java
> +    private void assertPostParseState(RecordFile recordFile, boolean success,
Could move this method into an abstract class for the 3 test classes to share since they are exactly the same

2021-06-10 15:54 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
> +    void keepBytes() throws Exception {
This test really only checks that download is successful when `streamFile.bytes != null`.
Not sure if there's a way to verify the logic that's unique to it bytes being set or if there's a mock to verify.

2021-06-10 16:02 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
> +    void keepBytes() throws Exception {
umm I had a hard time to understand what you are suggesting.

The test spec of this test case is:
Given `keepBytes` is `true` and the prerequisites of downloading the stream files are met,

When downloader.download is called,

Then the files should be successfully downloaded and read into the `StreamFile` objects with `bytes != null`

There is a line of change in `verifyStreamFiles`

`.allMatch(s -> downloaderProperties.isKeepBytes() ^ (s.getBytes() == null));`

2021-06-10 16:10 UTC, steven-sheehy requested changes

2021-06-10 16:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
> +        if (parserProperties.isEnabled() && parserProperties.isKeepFiles() && bytes != null) {
Before, when we used the filesystem for state it was critical that we only archive the file after it was ingested. Now that we use the database, we don't care if we archive the file in the downloader or parser. With your logic change, the `keepFiles` property won't work if the downloader `keepBytes` is not also true, which is most likely a confusing dependency that users won't be aware of since it's an implementation quirk.

For these reasons, I would like to see the `keepFiles` moved to the downloader with the other keep properties. In the future, I would like to see the disk structure exactly match the bucket structure. This would open up possibilities like backing up S3 or serving it to other mirror nodes.

2021-06-10 16:10 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.record.keepBytes`                 | false                   | Whether to keep the record file bytes so later the parser can persist it to the database.      |
Would prefer it stay named as `persistBytes` as ultimately it controls whether the bytes are persisted to the database.

2021-06-10 16:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
> +            parseStreamFile(streamFile);
sure that's a better name

2021-06-10 16:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
> +        if (parserProperties.isEnabled() && parserProperties.isKeepFiles() && bytes != null) {
sure that's a better approach. I realized the implicit confusing dependency but went with minimal change...

2021-06-10 16:26 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.record.keepBytes`                 | false                   | Whether to keep the record file bytes so later the parser can persist it to the database.      |
sure

2021-06-10 16:28 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java
> +    private void assertPostParseState(RecordFile recordFile, boolean success,
will do. potentially can combine if not all at least most test cases for *event* and *record*. note the *balance* parser test is an integration test while the other two are mocked tests. perhaps I should unify the three.

2021-06-10 20:33 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
> +    void keepBytes() throws Exception {
Gotcha, I see that now. Thanks

2021-06-11 17:34 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MessagingConfiguration.java
> +        return integrationFlow(parser);
have to repeat so the bean names are different.

didn't want to move the channel bean and integration flow bean to StreamFileParser classes because I prefer separating configuration from those classes as much as I can.

2021-06-11 17:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MessagingConfiguration.java
> +    @ConditionalOnRecordParser
not sure why we only have `ConditionalOnRecordParser` on `RecordFileParser` but not the other two parsers. anyway to avoid autowire error when `parser.record.enabled` is false, I also added the annotation here

2021-06-11 22:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MessagingConfiguration.java
> +    @ConditionalOnRecordParser
I believe `@ConditionalOnRecordParser` was added more so to help out the pubs flow which should only check whether to run when record parser is enabled.
Balance and event parser don't have a sub flow so it didn't apply.
Although I do believe we wanted to check thee annotations at some point for easier coordination.

2021-06-12 00:02 UTC, Nana-EC submitted a review, later dismissed
LGTM.
A debug log recommendation if anything

2021-06-14 15:01 UTC, steven-sheehy requested changes

2021-06-14 15:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
>  @ConditionalOnRecordParser
Remove both `@MessageEndpoint` and `@ConditionalOnRecordParser` since we're using java config.

2021-06-14 15:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/event/EventFileParser.java
>  @MessageEndpoint
Remove

2021-06-14 15:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/CompositeBalanceFileReader.java
> +        log.info("Loading account balance file: {}", streamFileData.getFilename());
Yes it's for consistency and also fills in the missing info regarding when the downloader started to load the file

2021-06-14 15:58 UTC, xin-hedera commented on docs/configuration.md
>  | `hedera.mirror.importer.parser.balance.queueCapacity`                | 10                      | How many balance files to queue in memory while waiting to be persisted by the parser          |
sounds good as it doesn't seem to be necessary to increase the `queueCapacity` for account balance files even in the near future we switch to streamline the balance file parsing.

2021-06-14 15:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
>  @MessageEndpoint
will change it to `@Component`

2021-06-14 16:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
>  @MessageEndpoint
Mixed up parser and flow. You're right it should be replaced not removed. Prefer `@Named` over `@Component` as it's standard.

2021-06-14 16:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
>  @MessageEndpoint
sure

2021-06-14 17:34 UTC, steven-sheehy approved these changes
LGTM

2021-06-14 20:26 UTC, ijungmann approved these changes
One small question, but LGTM

2021-06-14 20:54 UTC, Nana-EC approved these changes
LGTM

2021-06-14 20:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MessagingConfiguration.java
> +        if (properties.getQueueCapacity() <= 0) {
Because we should write code defensively in case that other class changes in the future and it's the same number of characters either way.

2021-06-14 21:14 UTC, steven-sheehy approved these changes

2021-06-14 21:42 UTC, ijungmann approved these changes

2021-06-15 06:01 UTC, Nana-EC approved these changes
LGTM

2021-06-15 18:15 UTC, merged