Nft importer
hashgraph/hedera-mirror-node pull request #2109
Opened 2021-06-11 20:50 UTC by ijungmann

**Detailed description**:
Add support for NFTs to the importer

**Which issue(s) this PR fixes**:
Fixes #1996 

**Special notes for your reviewer**:
Some of the code is still pretty rough and needs cleaning.
Cannot finish until:
1. Better understanding of NFT transfers for mint, burn, etc.
2. Confirm serial numbers in receipt of mint are in same order as metadata in transaction.
3. Confirm how we want to handle partial history for missing NFTs.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-06-11 20:51 UTC, ijungmann commented on hedera-mirror-importer/pom.xml
> +
Jitpack until merged.

2021-06-11 20:52 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +)
Used to support Java enum to Postgres enum conversion.  See [here](https://vladmihalcea.com/the-best-way-to-map-an-enum-type-with-jpa-and-hibernate/)

2021-06-11 20:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenSupplyTypeEnum.java
> +                .orElseThrow();
Look at adding proper exception.

2021-06-11 20:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (optionalNFT.isPresent()) {
Need to confirm how this should work.

2021-06-11 20:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.0__support_nfts.sql
> +  created_timestamp     bigint                  not null,
Can't do anymore because we can mint multiple NFTs per transaction now.

2021-06-11 20:57 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/NftRepositoryTest.java
> +    void findByTokenIdAndSerialNumber() {
Remove, no longer needed.

2021-06-14 23:46 UTC, ijungmann commented on hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
> +{"consensusTimestamp":1567188600419072000,"entity":{"shardNum":0,"realmNum":0,"entityNum":51520,"type":1},"transactionType":11,"transaction":{"body":{"transactionID":{"transactionValidStart":{"second
Just added `serialNumber:[]` to these

2021-06-15 05:33 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
>  import static org.assertj.core.api.Assertions.from;
Do another pass on this, the tests should all be there now but there is some sloppy/copied code, needs to be cleaned once more.

2021-06-15 05:34 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            "transaction type {} with timestamp {}";
Remove entirely, no longer used.

2021-06-15 16:26 UTC, ijungmann commented
Confirmed that mint, burn, etc. transfers will have missing account ids.  Adding tests and changing schema accordingly

2021-06-15 21:57 UTC, steven-sheehy requested changes

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenTypeEnum.java
> +    }
Since this is used in a hotspot, let's optimize by switching to a static map:
```suggestion
    private static final Map<Integer, TokenTypeEnum> ID_MAP = Arrays.stream(values()).collect(Collectors
            .toUnmodifiableMap(EntityTypeEnum::getId, Function.identity()));

    public static TokenTypeEnum fromId(int id) {
        return ID_MAP.getOrDefault(id, FUNGIBLE_COMMON);
    }
```

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenSupplyTypeEnum.java
> +    public static TokenSupplyTypeEnum fromId(int id) {
Needs optimizing.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    @Min(0)
We don't do annotation validation on domain objects as the values come from main nodes.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/NftTransfer.java
> +        this.senderAccountId = senderAccountId;
Would prefer no long arg constructor as they are unwieldy to maintain. No arg constructor should suffice.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Nft.java
> +@NoArgsConstructor
Not necessary

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    nftRepository.updateDeleted(new Nft.Id(serialNumber, EntityId.of(tokenID)), consensusTimeStamp)
Move EntityId construction out of the loop.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    //TODO should we set accountId to null or just leave it since deleted is already set?
I think the info of who had it last even for deleted might be useful. Plus it's less steps. So my vote is leave it.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenID tokenID = tokenBurnTransactionBody.getToken();
Move these up so you can pass to `updateTokenSupply()` as well. Change `updateTokenSupply()` to take in an `EntityId`.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (!nftTransfer.getReceiverAccountID().equals(AccountID.getDefaultInstance())) {
This check isn't necessary. EntityId.of() already handles this and will return `EntityId.EMPTY` if it's default instance which `onEntityId()` will ignore. So remove if here and change if around repository to check for EMPTY.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (!nftTransfer.getSenderAccountID().equals(AccountID.getDefaultInstance())) {
Remove

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    nftRepository.updateDeleted(new Nft.Id(serialNumber, EntityId.of(tokenID)), consensusTimeStamp));
Same comments here. Move EntityId up and share with `updateTokenSupply()`.

2021-06-15 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                .updateAccountId(new Nft.Id(serialNumber, tokenId), receiverId, consensusTimeStamp);
I'm re-debating whether we should just join with nft transfer to get current owner instead of duplicating it in nft.

2021-06-15 22:05 UTC, Nana-EC requested changes
Nice work, some initial suggestions.
As promised also highlighted some places for the upsert logic might go, to make merging easier if I go in before you

2021-06-15 22:05 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    void onNft() throws Exception {
Add a test to verify contend update after transfer and delete of the nft

2021-06-15 22:39 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NftTransferRepository.java
> +package com.hedera.mirror.importer.repository;/*
Yeah, it's my auto-license thing acting up again.  I'll take a look at that, in the meantime I believe that's fixed everywhere now,.

2021-06-15 22:42 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/NftTransferRepositoryTest.java
> +        assertThat(saved).isEqualTo(repository.findById(saved.getId()).get());
Fixed in both the repository tests, will look out for others.

2021-06-15 22:46 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/NftTransferRepositoryTest.java
> +public class NftTransferRepositoryTest extends AbstractRepositoryTest {
Fixed for two tests, didn't see any others.

2021-06-15 22:46 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/NftRepositoryTest.java
> +                .isEqualTo(repository.findById(savedNft.getId()).get());
Fixed.

2021-06-15 23:08 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenTypeEnum.java
> +    }
Good idea, did this here and to TokenSupplyTypeEnum.

2021-06-15 23:08 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenSupplyTypeEnum.java
> +    public static TokenSupplyTypeEnum fromId(int id) {
Optimized in the same way as above.

2021-06-15 23:09 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    @Min(0)
Makes sense, removed.

2021-06-15 23:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/NftTransfer.java
> +        this.senderAccountId = senderAccountId;
Makes sense, it was only used in one spot anyway.  Removed.

2021-06-15 23:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Nft.java
> +@NoArgsConstructor
Removed.

2021-06-15 23:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    nftRepository.updateDeleted(new Nft.Id(serialNumber, EntityId.of(tokenID)), consensusTimeStamp)
Moved.

2021-06-15 23:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    //TODO should we set accountId to null or just leave it since deleted is already set?
Agreed, I've removed the TODO and left as is.

2021-06-15 23:26 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenID tokenID = tokenBurnTransactionBody.getToken();
Done.

2021-06-15 23:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (!nftTransfer.getReceiverAccountID().equals(AccountID.getDefaultInstance())) {
Got it, removed.

2021-06-15 23:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (!nftTransfer.getSenderAccountID().equals(AccountID.getDefaultInstance())) {
Removed.

2021-06-15 23:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    nftRepository.updateDeleted(new Nft.Id(serialNumber, EntityId.of(tokenID)), consensusTimeStamp));
Done

2021-06-15 23:42 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                .updateAccountId(new Nft.Id(serialNumber, tokenId), receiverId, consensusTimeStamp);
I agree.  The accountId on NFT mint is messy because we insert transfers before the actual NFT, so there has to be logic just for that.  And then there is this bit here.  It's a nice idea in concept, but it may not be worth the added code and potential performance hit.

2021-06-15 23:52 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    //TODO should we set accountId to null or just leave it since deleted is already set?
Removed the TODO and kept as is.

2021-06-15 23:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            //TODO should we set accountId to null or just leave it since deleted is already set?
Done, removed TODO

2021-06-16 02:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Nft.java
> +    private boolean deleted;
Would it?  I would think the only time an NFT would be deleted would be after a burn, wipe, or delete (which is handled at the token level instead), and after that the NFT shouldn't appear in any more transactions, so effectively `deleted` would always be false unless the partial data leads to the NFT being created by one of those delete operations, where it would be created as true.  I can't think of a situation where the `deleted` status would be unknown, but I'm willing to make this change, just trying to see the scenario.

2021-06-16 02:08 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Nft.java
> +    private long createdTimestamp;
Sure, also updated the DB tables to allow for that.  Just a heads up, our PRs are going to collide on the migration version, I'll update my version assuming yours gets in first.

2021-06-16 02:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenSupplyTypeEnum.java
> +    }
This adds a little bit of awkwardness with the `fromId()` method after refactoring.  I added a second method, `getIdAsInt`, to get around that bit, the alternative would be to just call String.valueOf(id) to the incoming id, but that seemed like unneeded overhead.  Anyway, this is done, just pointing that out.

2021-06-16 02:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (!nftTransfer.getReceiverAccountID().equals(AccountID.getDefaultInstance())) {
Solved with some of Steven's suggestions, my primary concern with this was not saving a transfer with the default entity id (0.0.0) as the sender or receiver, instead I thought it should be null.

2021-06-16 02:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NftRepository.java
> +    void updateAccountId(@Param("id") Nft.Id nftId, @Param("accountId") EntityId newAccountId,
Good name, switched to this.

2021-06-16 02:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NftRepository.java
> +    void updateDeleted(@Param("id") Nft.Id nftId, @Param("timestamp") long modifiedTimestamp);
Yep, switched.

2021-06-16 02:31 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    void onNft() throws Exception {
Added a test here to simulate that.  There are also tests in `EntityRecordItemListenerTokenTest` that check that logic.

2021-06-16 02:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Nft.java
> +    public static class Id implements Serializable {
Cool, moved for Nft and NftTransfer

2021-06-16 03:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Nft.java
> +    private boolean deleted;
I think you're correct. I was thinking around an update or transfer scenario, however, in both cases you can safely assume the nft is not deleted if the transaction is successful.
I was indeed concerned about the partial cases but it seems even in that case you can assume deleted = false.
It's fine as is.

2021-06-16 15:05 UTC, xin-hedera requested changes

2021-06-16 15:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/NftId.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
Fixed, did a search for 2019 - 2020

2021-06-16 15:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            long consensusTimeStamp = recordItem.getConsensusTimestamp();
Good call, rearranged here and elsewhere to only call once

2021-06-16 15:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    nft.setId(new NftId(serialNumbers.get(i), EntityId.of(tokenID)));
Yep, moved things around to not do this.

2021-06-16 15:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    nftRepository.save(nft);
Good idea, done.

2021-06-16 15:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                            .onNftTransfer(nftTransferDomain);
Fixed.

2021-06-16 16:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    EntityId receiverId = EntityId.of(nftTransfer.getReceiverAccountID());
From the NFT proto PR: `...for minting there will be no sender and for burning wiping there will be no receiver`.  So I expect we will receive the default instance, `0.0.0`, which turns into EMPTY and is ignored in `onEntityId` and converted to `null` during PgCopy.

2021-06-16 16:42 UTC, ijungmann commented
Working on these merge conflicts

2021-06-16 16:48 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        token.setSupplyType(TokenSupplyTypeEnum.INFINITE);
Move these

2021-06-16 16:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    EntityId receiverId = EntityId.of(nftTransfer.getReceiverAccountID());
better to be defensive, since `no sender` / `no receiver` can be the corresponding fields in protobuf not set, then here we'll hit NPE.

2021-06-16 16:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (receiverId != EntityId.EMPTY) {
```suggestion
                    if (EntityId.isEmpty(receiverId)) {
```

2021-06-16 16:51 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                    if (tokenTransferLists != null && tokenTransferLists.length != 0) {
Double-check this

2021-06-16 16:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.39.1__nft_changes_for_importer.sql
> +-------------------
Up version number

2021-06-16 17:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    if (receiverId != EntityId.EMPTY) {
Done.

2021-06-16 17:34 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenSupplyTypeEnum.java
> +    }
After merging with latest master this causes some issues.  Since we're now storing the new enums as Strings, with `PostgreSQLEnumType` providing the translation from Java to Postgres, this seems to work just fine without this, so I've removed it.  If there's another concern that this still needs to be in for, I can look at how to merge the two.

2021-06-16 20:23 UTC, ijungmann commented
Addressed all relevant code smells, the rest are all existing in unrelated classes and files, don't want to add more to this PR.

2021-06-16 22:25 UTC, steven-sheehy requested changes

2021-06-16 22:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            insertTokenTransfers(recordItem);
Why was the move necessary?

2021-06-16 22:53 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/NftTransferRepositoryTest.java
> +        assertThat(repository.findById(saved.getId()).get()).isEqualTo(saved);
Taken care of for both repository tests, Sonarcloud wanted it swapped with `.contains()`

2021-06-16 23:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            insertTokenTransfers(recordItem);
Based on the call this afternoon, moving here allows the initial `TokenMint` to set the accountId after saving the NFT, as opposed to having to fetch it from the Token.  However, if we do the `saveAll` approach this would be an issue again, so I would move things back and add back that logic.

2021-06-16 23:01 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        nftRepository.save(nft);
Not against that, but it does cause the below issue with the initial tokenMint accountId to pop back up.

2021-06-17 04:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenSupplyTypeEnum.java
> +    }
That's fine. If Postgres handles the serialization then we're good.

2021-06-17 04:48 UTC, Nana-EC requested changes
Looking good.
Some clarification needed on the coordination of the nft persistence and transfers.

Will circle back for a final pass of this along with added tests

2021-06-17 04:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            nftTransferPgCopy.copy(nftTransfers, connection);
I thought we were gonna move this and all the transfers to the end to be the last copies.
That way all entities noted in the transfers would already be present in DB?

2021-06-17 04:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            nftTransferPgCopy.copy(nftTransfers, connection);
Something like
```suggestion
            persistNfts();
            ...
            nftTransferPgCopy.copy(nftTransfers, connection);
```

Which would call
```
private void persistNfts() {
        Stopwatch stopwatch = Stopwatch.createStarted();
        nftRepositorysaveAll(nfts);
        log.info("Inserted {} nfts in {}", nfts.size(), stopwatch);
}
```

2021-06-17 04:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        nftRepository.save(nft);
Isn't that solved by the the above noted placement of all transfers at the end?
Then you should be able to do a saveAll for all NFts similar to how we did for entities.

2021-06-17 14:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            nftTransferPgCopy.copy(nftTransfers, connection);
I realize the save occurs in EntityRecordListener instead so the placement here doesn't really matter

2021-06-17 14:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        nftRepository.save(nft);
Circling back, the placement solves this issues.
Also given the next item is to apply upsert logic to this I think the simpler approach Ian has is fine.
Just save on each NFT to ensure Mints populate the initial owner early on as treasury prior to any transfers

2021-06-17 14:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            insertTokenTransfers(recordItem);
This is what we discussed. Probably the simplest => save Nft upon receipt and allow for a follow up transfer to act on most up to date info.
Nft is the only immediate save now so performance wise we can handle it until we apply the upsert logic

2021-06-17 14:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    EntityId receiverId = EntityId.of(nftTransfer.getReceiverAccountID());
Just checked protobuf generated code, I probably missed the previous discussion. I thought getReceiverAccountID / getSenderAccountID may return null, it actually returns the default instance if the field is not set. So no problem!

2021-06-17 16:37 UTC, steven-sheehy approved these changes
LGTM

2021-06-17 17:10 UTC, Nana-EC approved these changes
LGTM
Let's create that ticket to apply Upsert logic to Nfts and note it here for context.

2021-06-17 17:11 UTC, xin-hedera approved these changes
LGTM

2021-06-17 17:18 UTC, ijungmann commented
> LGTM
> Let's create that ticket to apply Upsert logic to Nfts and note it here for context.

Created #2133 for that.

2021-06-17 18:38 UTC, merged