Add NFT support to existing REST APIs
hashgraph/hedera-mirror-node pull request #2129
Opened 2021-06-17 01:46 UTC by Nana-EC

**Detailed description**:
With importer support for nfts the REST API should be updated to expose appropriate information in existing API's

- Add logic to `transactions.js` to create `nft_transfer_list` and populate transaction response when applicable
- Add new column `supply_type`, `max_supply` and `type` to token response
- Add spec test files to cover `/api/v1/transactions`, `/api/v1/transactions/id`, `/api/v1/tokens`, `/api/v1/tokens/<tokenId>` in nft scenario
- Update `transactions.test.js` and `tokens.test.js` with coverage for `NON_FUNGIBLE_UNIQUE`

**Which issue(s) this PR fixes**:
Fixes #2058 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-06-17 15:14 UTC, steven-sheehy requested changes
The nullable receiver/sender will require you waiting for Ian's PR or adding a temporary migration that allows them to be null.

2021-06-17 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions-36-nft-transfers.spec.json
> +            "sender_account_id": "0.0.3",
Should have one item with null `receiver_account_id` and another with null `sender_account_id`.

2021-06-17 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                type: string
We don't have a specific type for entity IDs? If not, can we create one to denote the shard realm num format?

2021-06-17 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +              - sender_account_id
These two not required

2021-06-17 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
enum

2021-06-17 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
enum. Should make it a reusable type since it is used as query param too

2021-06-17 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      sender_account_id: EntityId.fromEncodedId(senderAccountId).toString(),
allows nullable

2021-06-17 16:07 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-08-fungible-common-token-types.spec.json
> +  "urls": ["/api/v1/tokens?tokentype=FUNGIBLE_COMMON", "/api/v1/tokens?tokentype=fungible_common"],
Yeah, meant to change this.
I realized the `transationtype` was such because it conflicted with `type` used for credit and debit filtering. Since this is the first type for token there's no conflict

2021-06-17 16:14 UTC, xin-hedera requested changes

2021-06-17 16:14 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    ORDER BY ${tableAlias}.consensus_timestamp ${order} ${namedLimitQuery}`;
prefer the old format with joinClause, whereClause, and etc beginning on its own line. when we set log level to trace to debug, it's more readable

2021-06-17 16:14 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +                             ON coalesce(t.consensus_timestamp, ctl.consensus_timestamp) = ntl.consensus_timestamp
unfortunately have to coalesce the previous three timestamps:

```suggestion
                             ON coalesce(t.consensus_timestamp, ctl.consensus_timestamp, ttl.consensus_timestamp) = ntl.consensus_timestamp
```

should also update `transactions-35-` spec to have a nft transfer whose receiver account id is the account.id in the query filter to make sure we don't see duplicate nft trasnfers

2021-06-17 16:14 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        ctl_entity_id: 98,
if the entity id from crypto transfer table is not null, there should be an amount, and accordingly, the amount in the expected can't be NaN.

2021-06-17 16:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-10-all-token-types.spec.json
> +        "created_timestamp": "1234567890000000001"
That's already covered in `tokens-08-fungible-common-token-types.spec.json`.
Did you mean something else

2021-06-17 16:16 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-10-all-token-types.spec.json
> +  "urls": ["/api/v1/tokens?tokentype=ALL", "/api/v1/tokens?tokentype=all"],
Sure can add here to show equivalence. We do get this coverage from most of the other tokens- spec files

2021-06-17 16:22 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    ORDER BY ${tableAlias}.consensus_timestamp ${order} ${namedLimitQuery}`;
Yeah my IDE did this on save. Will revert

2021-06-17 16:41 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        ctl_entity_id: 98,
Sure, the dependency objects are large so I wasn't going for fully valid objects, more of the necessary so the test could focus on the nft_transfer sql generation verification.
Will add amount though

2021-06-17 16:44 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/tokens-10-all-token-types.spec.json
> +        "created_timestamp": "1234567890000000001"
I think he means not using the default type for creating the token and explicitly stating `type: FUNGIBLE_COMMON` here.

2021-06-17 16:59 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    // account filter applies to transaction.payer_account_id, crypto_transfer.entity_id, and nft_transfer.account_id,
nit:
```suggestion
    // account filter applies to transaction.payer_account_id, crypto_transfer.entity_id, nft_transfer.account_id,
```

2021-06-17 16:59 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    // and token_transfer.account_id, a full outer join between the three tables is needed to get rows that may only exist in one.
```suggestion
    // and token_transfer.account_id, a full outer join between the four tables is needed to get rows that may only exist in one.
```

2021-06-17 17:08 UTC, ijungmann requested changes
Looks really good, just a couple things.

2021-06-17 17:08 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
>      }
I think the `nftTrQuery` should be incorporated here as well, as I understand it the credit/debit query is for anything moving in or out of an account.

2021-06-17 17:28 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-08-fungible-common-token-types.spec.json
> +  "urls": ["/api/v1/tokens?tokentype=FUNGIBLE_COMMON", "/api/v1/tokens?tokentype=fungible_common"],
Yeah will need some refactoring for this, as right now are query params need to be unique across resources.
Will work on this

2021-06-17 18:11 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
>      }
Also not opposed to doing this in a different ticket if it requires too much additional work.

2021-06-17 20:30 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
>      }
So I had it in here but didn't want to complicate the concept. 
I wanted to open a separate ticket to address credit/debit in nfts. Since it's not a balance it's more of is the filtered account the sender or receiver.
The logic that handles credit /debit is old and complicated so I didn't want to shoehorn it in there at the end of sprint

2021-06-17 21:11 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
>      }
Understood, glad it was considered, we can address later.

2021-06-17 23:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-01-no-args.spec.json
> +        "type": "FUNGIBLE_COMMON"
This is the response. Not the input. I think we're being explicit in the response

2021-06-17 23:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-10-all-token-types.spec.json
> +        "created_timestamp": "1234567890000000001"
Ahh, gotcha. Can do.

2021-06-17 23:38 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +      EntityId.fromString(transfer.sender_account_id).getEncodedId().toString(),
Fixed

2021-06-17 23:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-10-all-token-types.spec.json
> +  "urls": ["/api/v1/tokens?tokentype=ALL", "/api/v1/tokens?tokentype=all"],
Added

2021-06-17 23:41 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-08-fungible-common-token-types.spec.json
> +  "urls": ["/api/v1/tokens?tokentype=FUNGIBLE_COMMON", "/api/v1/tokens?tokentype=fungible_common"],
Fixed. I didn't want to create too much church here so I opted for splitting the utility function so it works as is but tokens and other files can utilize the shared format logic but implement their own validity checks.
We should look to refactor a lot of the utility classes for clarity and easier usage.

2021-06-17 23:41 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-36-nft-transfers.spec.json
> +            "sender_account_id": "0.0.3",
Updated

2021-06-17 23:42 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +                type: string
Nah we don't .
Added one and updated for others to reuse it

2021-06-17 23:47 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +      sender_account_id: EntityId.fromEncodedId(senderAccountId).toString(),
Updated

2021-06-17 23:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/transactions.test.js
> +
Removed

2021-06-17 23:47 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    ORDER BY ${tableAlias}.consensus_timestamp ${order} ${namedLimitQuery}`;
Reverted

2021-06-17 23:47 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +                             ON coalesce(t.consensus_timestamp, ctl.consensus_timestamp) = ntl.consensus_timestamp
Updated but seem to be hitting the bug.

2021-06-17 23:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        ctl_entity_id: 98,
Updated

2021-06-17 23:47 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    // account filter applies to transaction.payer_account_id, crypto_transfer.entity_id, and nft_transfer.account_id,
Fixed

2021-06-17 23:48 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    // and token_transfer.account_id, a full outer join between the three tables is needed to get rows that may only exist in one.
Fixed

2021-06-17 23:49 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Updated

2021-06-17 23:49 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Fixed and applied to type also

2021-06-17 23:49 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +              - sender_account_id
Fixed

2021-06-17 23:50 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-10-all-token-types.spec.json
> +        "created_timestamp": "1234567890000000001"
Done

2021-06-18 03:21 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +                             ON coalesce(t.consensus_timestamp, ctl.consensus_timestamp) = ntl.consensus_timestamp
Capturing this issue in [2139](https://github.com/hashgraph/hedera-mirror-node/issues/2139) in case we want to cut a tag and allow for release before I can get to resolving it

2021-06-18 03:27 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
>      }
Captured this in [2140](https://github.com/hashgraph/hedera-mirror-node/issues/2140)

2021-06-18 03:29 UTC, steven-sheehy approved these changes
LGTM

2021-06-18 14:38 UTC, ijungmann approved these changes

2021-06-21 13:47 UTC, xin-hedera approved these changes
LGTM

2021-06-21 14:50 UTC, merged