Set entity createdTimestamp and modifiedTimestamp in transaction handlers
hashgraph/hedera-mirror-node pull request #2159
Opened 2021-06-21 19:26 UTC by xin-hedera

**Detailed description**:

- Add abstract base class AbstractEntityCrudTransactionHandler
- Make entity CRUD transaction handlers extend the base to set entity created / modified timestamp

**Which issue(s) this PR fixes**:
Fixes #2131 

**Special notes for your reviewer**:

**Checklist**

- [ ] Documentation added
- [x] Tests updated

2021-06-22 00:41 UTC, Nana-EC requested changes
Looks good.

I think you're missing a new migration file that would run the logic to set createdTimestamp and ModifiedTimestamps for those entities that were missed.
Unlike the initial run in V1.36.2 it can work on a subset of data

```sql
-- set created and modified timestamp based on entity creating or modifying transaction types
with entity__timestamp_map as (
    select entity_id, min(consensus_ns) as created_timestamp, max(consensus_ns) as modified_timestamp
    from transaction
    where result = 22
      and entity_id is not null
    group by entity_id
    order by entity_id, created_timestamp
)
update entity
set created_timestamp  = coalesce(created_timestamp, entity__timestamp_map.created_timestamp),
    modified_timestamp = entity__timestamp_map.modified_timestamp
from entity__timestamp_map
where id = entity__timestamp_map.entity_id and modified_timestamp is null;
```

2021-06-24 00:15 UTC, Nana-EC requested changes
Looks good. 
Had an enum suggestion and a request for a migration test class

2021-06-24 00:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractEntityCrudTransactionHandler.java
> +    private final boolean createEntity;
Should we make this an enum instead - `NONE`, `CREATE`, `UPDATE`, `DELETE`.
That might help in scaling and capturing intent

2021-06-24 00:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractEntityCrudTransactionHandler.java
> +        if (createEntity) {
If you adopt an enum then you could make this when `enum == Enum.CREATE`
And you'd also have a scenario for delete where you can set deleted to false.

2021-06-24 00:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.0__entity_timestamp.sql
> +    and consensus_ns > coalesce((
We really need to figure out an efficient way to run these migration tests. Right now every new migration test loads up a new application context, which is very slow. Seems like there should be a way to run flyway migrations ourselves one at a time and run its corresponding test before moving on to the next.

2021-06-24 16:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.0__entity_timestamp.sql
> +    and consensus_ns > coalesce((
sure. will add the migration test, also look into how to share the test application context between all the migration tests

2021-06-24 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractEntityCrudTransactionHandler.java
> +        if (createEntity) {
good suggestion will do.

2021-06-24 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            entityListener.onEntity(entity.getAutoRenewAccountId().toEntity());
sure

2021-06-24 16:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractEntityCrudTransactionHandler.java
> +    private final boolean createEntity;
I like that idea, a `DELETE` option would further reduce some code.

2021-06-24 16:59 UTC, ijungmann reviewed
No additional feedback from what's already added, looks good.

2021-06-24 23:39 UTC, steven-sheehy approved these changes
LGTM

2021-06-25 00:34 UTC, ijungmann approved these changes

2021-06-25 04:37 UTC, Nana-EC approved these changes
LGTM

2021-06-25 14:24 UTC, merged