Increase rosetta integration test docker pool timeout
hashgraph/hedera-mirror-node pull request #2161
Opened 2021-06-22 00:41 UTC by xin-hedera

Signed-off-by: Xin Li <xin.li@hedera.com>

**Detailed description**:

- Increase rosetta integration test docker pool timeout to 10m
- Increase rosetta github workflow test job timeout to 20m
- Switch to upstream hedera-sdk-go v2.1.7

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
The rosetta db integration tests still fail periodically, looks like it's the same cause that downloading the postgres db container can sometimes take much longer.

The hedera-sdk-go module was replaced by a fork with various fixes, now the upstream v2.1.7 has incorporated them, it's time to switch back.

**Checklist**

- [ ] Documentation added
- [ ] Tests updated

2021-06-22 00:44 UTC, Nana-EC requested changes
Looks good, just 1 minor related nit

2021-06-22 00:44 UTC, Nana-EC commented on hedera-mirror-rosetta/test/db/db.go
>  	// set max wait to 5 minutes, used in pool.Retry to timeout
nit: update comment. Maybe remove mention of value so it's not outdated on change

2021-06-22 00:47 UTC, xin-hedera commented on hedera-mirror-rosetta/test/db/db.go
>  	// set max wait to 5 minutes, used in pool.Retry to timeout
sure. good catch!

2021-06-23 13:37 UTC, xin-hedera commented on hedera-mirror-rosetta/test/db/db.go
>  	// set max wait to 5 minutes, used in pool.Retry to timeout
updated

2021-06-23 14:37 UTC, steven-sheehy approved these changes
LGTM. But why are there two postgres containers?

2021-06-23 14:49 UTC, Nana-EC approved these changes
LGTM

2021-06-23 15:11 UTC, xin-hedera commented
> LGTM. But why are there two postgres containers?

there isn't a testing framework to support context share as in Spring, so every db integration test suite spins up its own containers. In github CI, we use `go test -race ./...' so the *_test.go tests are run concurrently.

2021-06-23 16:08 UTC, ijungmann approved these changes

2021-06-23 16:40 UTC, merged