Improve acceptance accountId and retry logic
hashgraph/hedera-mirror-node pull request #2162
Opened 2021-06-22 05:03 UTC by Nana-EC

**Detailed description**:
Acceptance tests saw a bug where it encoutedred a busy network with valid GO AWAY errors. During this flow the tests were unable to created dependency accounts needed for tests. However, it didn't fail early and resulted in NullPointerExceptions.

- Add `NetworkExpection` class to capture exceptions when hitting network during dependency items setup
- Fail fast where any early issues are encountered
- Move retry logic around network interactions to network clients
- Move retry logic around mirror REST API calls to Mirror node client

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**

- [ ] Documentation added
- [ ] Tests updated

2021-06-22 15:47 UTC, steven-sheehy requested changes

2021-06-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
Why does this need to be prototype? It doesn't have any state

2021-06-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +            maxAttemptsExpression = "#{@restPollingProperties.maxAttempts}")
Since we have a reactive web client, we should consolidate retry logic inside `callRestEndpoint()` using `retryWhen()`. See `RestSubscriber` for an example.

2021-06-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
>      RetryTemplate retryTemplate() {
Where is this retry template even used? If you're using `@Retryable` it won't use this since they each have their own config. I think it can be removed unless you take my other advice to move away from verbose `@Retryable`.

2021-06-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
>      public NetworkTransactionResponse asssociate(ExpandedAccountId accountId, TokenId token) throws ReceiptStatusException, PrecheckStatusException, TimeoutException {
```suggestion
    public NetworkTransactionResponse associate(ExpandedAccountId accountId, TokenId token) throws ReceiptStatusException, PrecheckStatusException, TimeoutException {
```

2021-06-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
Since we have a central spot that executes transaction, we should stay DRY and programmatically retry via `RetryTemplate.execute()` inside `AbstractNetworkClient.executeTransaction()`.

2021-06-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
We should investigate what enhancements/fixes are necessary to make the SDK more resilient so these application retries aren't necessary. For example in the SDK mirror client, I exposed a `retryHandler` predicate that can customize which errors should retry.

2021-06-22 18:48 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
>      RetryTemplate retryTemplate() {
It's not, I realized, lol.
Cause we use the annotated form this never gets used.
I looked into using it but it gets messy so left it out of this.
We can either look to use it in a future PR around the actually transaction submission or we can delete this and just stay with the annotated form

2021-06-22 18:49 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
>      RetryTemplate retryTemplate() {
Will remove.
The other advise covers the Rest calls, but the annotations will still be needed for the network calls

2021-06-22 18:49 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
>      public NetworkTransactionResponse asssociate(ExpandedAccountId accountId, TokenId token) throws ReceiptStatusException, PrecheckStatusException, TimeoutException {
Will rename this and the others

2021-06-22 18:51 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
Yeah tried this exact approach, ended up getting messy with Exception management so I opted to stay as is since I wanna cherry pick this PR

2021-06-22 19:15 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
Yeah we probably want a a similar `retryHandler` for transaction Executable class.
Will open a ticket

2021-06-22 19:24 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
I think the current approach is messy. This seems a lot cleaner:

```java
    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) {
        ...
        TransactionResponse transactionResponse = retryTemplate.execute(r -> executeTransaction(t));
        TransactionId transactionId = transactionResponse.transactionId;
        log.debug("Executed transaction {} with {} signatures.", transactionId, keyList == null ? 0 : keyList.size());
        return transactionId;
    }

    @SneakyThrows
    private TransactionResponse executeTransaction(Transaction transaction) {
        return (TransactionResponse) transaction.execute(client);
    }
```

2021-06-22 21:28 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +            maxAttemptsExpression = "#{@restPollingProperties.maxAttempts}")
Will adopt

2021-06-22 21:28 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
>      RetryTemplate retryTemplate() {
On 2nd thoughts I can simplify this and use the template for now. 
When SDK does more handling it'll be an easier refactor to remove it's use

2021-06-22 21:29 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
Retried, just lots of exception replacements

2021-06-23 15:20 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
>      RetryTemplate retryTemplate() {
Reworked to utilize the retryTemplate over the annotations

2021-06-23 15:20 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
>      public NetworkTransactionResponse asssociate(ExpandedAccountId accountId, TokenId token) throws ReceiptStatusException, PrecheckStatusException, TimeoutException {
Renamed

2021-06-23 15:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    @Retryable(value = {PrecheckStatusException.class, TimeoutException.class},
Did see your above code till now but that's pretty much what I did, reverted and redid and pushed.
Didn't do the separate `@SneakyThrows` method though.

2021-06-23 16:35 UTC, ijungmann reviewed
Couple questions

2021-06-23 16:35 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> +            maxAttemptsExpression = "#{@acceptanceTestProperties.maxRetries}")
Is it intentional to have this above the `When` but below the `Then`?

2021-06-23 16:35 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        Transaction finalTransaction = transaction;
This is just to feed into the lambda?

2021-06-23 16:36 UTC, steven-sheehy requested changes

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws Exception {
Adding a generic `Exception` to the throws clause adds no value and forces every caller to do checked exception handling. I don't find throws clauses useful in general, but if you do use it should be to document specific exceptions that can be thrown. Would prefer this use `@SneakyThrows` or wrap in a `RuntimeException`. But to reduce churn we can consider for a follow up down the road, if needed.

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
So now there's two levels of retries with each doing a high number of attempts. If `retryTemplate.maxAttempts` is 10 and sdk `maxAttempts` is 20 then that means if something is wrong it could potentially wait for `10 * 20 * 31.75s = 1.7 hours`! The `31.75s` is how long the SDK can wait using exponential backoff. This is way too high.

We should only have one level of retries. Since we don't trust the SDK to retry every error we need right now, we should disable it by setting `transaction.setMaxAttempts(0)`. Then we don't need `SdkProperties` either.

If we only have `RetryTemplate`, it will do `10 * 5s = 50s`. This is more reasonable, but we should switch to exponential backoff to improve responsiveness of tests. Should we also set a maxInterval lower than 50s like 30s?

Or, conversely we can just lower both max attempts and backoffs so that overall it waits a much more reasonable amount of time.

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AtomicReference<Exception> encounteredException = null;
This needs to be initialized otherwise you'll have a NPE below.

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x -> topicMessageQuery
This also has two levels of retrying. As we've improved the reliability of the `TopicMessageQuery` retry capability, we should depend on it and not use `retryTemplate` here. You should adjust the `TopicMessageQuery` to increase attempts, retry for more errors, set max backoff, etc as needed though.

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x ->
Same comment

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>                  .doOnError(x -> log.debug("Endpoint failed, returning: {}", x.getMessage()))
As this should now only be called when attempts are exhausted, we should move it to warn or error level.

2021-06-23 16:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                .doBeforeRetry(r -> log.debug("Retry attempt #{} after failure: {}",
info or warn level might be fine here

2021-06-23 17:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
Will reduce the SDK retry attempts.
Eventually I want to move more properties into SDKProperties such as operator, network and retry configs.

2021-06-23 17:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws Exception {
Will use the `@SneakyThrows` you noted

2021-06-23 17:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        Transaction finalTransaction = transaction;
Yep, complains without it

2021-06-23 17:50 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws Exception {
Those lines have already been touched so shouldn't create any new lines for review. Things will just see `throws Exception` removed

2021-06-23 18:11 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
> +            maxAttemptsExpression = "#{@acceptanceTestProperties.maxRetries}")
Not all, let me change it to be consistently below

2021-06-23 18:38 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x -> topicMessageQuery
In hindsight the topic subscribes don't use the transaction execute, so the default retry handler should be sufficient.
will see if there are any exceptions I'm seeing that require a custom retryHandler

2021-06-23 20:09 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AtomicReference<Exception> encounteredException = null;
also `encounteredException` is not needed if `createNewAccount` does not throw `Exception`

2021-06-23 20:14 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList) throws Exception {
Updated

2021-06-23 20:15 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
Brought sdk retry down to current default of 10, and our overall down to 3, since it controls some of the feature logic that applies when a state change may yet have occurred or all HCS messages have yet to make it's way to mirror node

2021-06-23 20:17 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AtomicReference<Exception> encounteredException = null;
Ah missed this before pushing, will add optimization

2021-06-23 20:18 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x -> topicMessageQuery
Didn't find any extra exceptions that needed to be added. 
Interesting cause currently if you you provide a new retryHandler you lose coverage of the sdk internal `RST_STREAM` error.

2021-06-23 20:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x ->
Reverted

2021-06-23 20:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>                  .doOnError(x -> log.debug("Endpoint failed, returning: {}", x.getMessage()))
Set to error

2021-06-23 20:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                .doBeforeRetry(r -> log.debug("Retry attempt #{} after failure: {}",
Set to warn

2021-06-23 20:22 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
That's still 15 minutes per transaction. The total time should not go past 30-60s.

2021-06-23 20:24 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
Actually my math is wrong. 3 * 31.75s = 95s. So adjusting to 2 max attempts should suffice unless you see a strong need for 90s.

2021-06-23 20:33 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x -> topicMessageQuery
Yes, `retryHandler` overrides the internal logic completely.

2021-06-23 20:39 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AtomicReference<Exception> encounteredException = null;
Updated

2021-06-23 20:54 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        }
believe this won't get hit since when `createNewAccount` throws, it'll bubble up. so need to try catch around computeIfAbsent

2021-06-23 21:09 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        }
Ahh I over reverted. Will restore that part

2021-06-23 21:10 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
Can do 2. Really depends on network load. Will test 2 out

2021-06-23 21:14 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +        transaction.setMaxAttempts(sdkClient.getAcceptanceTestProperties().getSdkProperties().getMaxAttempts());
Set to 2, updated max to 5 to allow for some on demand configuration

2021-06-23 21:14 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        }
Fixed

2021-06-23 21:36 UTC, xin-hedera approved these changes
LGTM

2021-06-23 21:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        SubscriptionHandle subscription = retryTemplate.execute(x -> topicMessageQuery
For acceptance, you could make it even more permissive and just have a `i -> true` retryHandler.

2021-06-23 21:44 UTC, steven-sheehy approved these changes
LGTM

2021-06-23 22:31 UTC, ijungmann approved these changes

2021-06-23 22:46 UTC, merged