NFTs list and get REST API
hashgraph/hedera-mirror-node pull request #2171
Opened 2021-06-24 02:16 UTC by Nana-EC

**Detailed description**:
We need REST resource endpoints to expose a list of nfts and a single nfts

- Add a `/api/v1/tokens/{id}/nfts/{serialnumber}` to `server.js`  to return a single NFT
- Add a `/api/v1/tokens/{id}/nfts`  to `server.js` to return a list of NFTs

**Which issue(s) this PR fixes**:
Fixes #2135 

**Special notes for your reviewer**:

**Checklist**

- [ ] Documentation added
- [x] Tests updated

2021-06-24 23:55 UTC, steven-sheehy requested changes

2021-06-24 23:55 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-01-no-args.spec.json
> +        },
This should just be base64 encoded content of the metadata bytea, as the design indicates.

2021-06-24 23:55 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000005",
This doesn't include the dot notation to separate nanoseconds. Same for modified timestamp.

2021-06-24 23:55 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-05-all-params.spec.json
> +        "serial_number": 4
We should at minimum also sort by serialnumber.

We should also discuss if it should only sort by serialnumber as that field is unique within the token id and is part of the index.

2021-06-24 23:55 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-04-account-id.spec.json
> +        "serial_number": 2
Even though it's part of the user input, to be complete we should also add `token_id` to all nft objects similar to how we add `topic_id` to all topic messages.

2021-06-25 06:57 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-04-account-id.spec.json
> +        "serial_number": 2
Will add to design doc

2021-06-25 06:59 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-05-all-params.spec.json
> +        "serial_number": 4
currently sorting by account.id at the minimum.
Can add serialNumber within that

2021-06-25 07:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-01-no-args.spec.json
> +        "created_timestamp": "1234567890000000005",
Updated

2021-06-25 07:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-01-no-args.spec.json
> +        },
Updated

2021-06-25 07:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-04-account-id.spec.json
> +        "serial_number": 2
Updated

2021-06-25 07:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-05-all-params.spec.json
> +        "serial_number": 4
Updated

2021-06-25 13:35 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-05-all-params.spec.json
> +        "serial_number": 4
I'd prefer only sorting by serial as it's more performant and won't change output order as ownership changes.

2021-06-25 15:33 UTC, xin-hedera commented on docs/design/nft.md
> +  account_id            bigint                  not null,
since you made update here. can you change the primary key, this is what's in db:

```
mirror_node=> \d nft;
                        Table "public.nft"
       Column       |  Type   | Collation | Nullable |   Default
--------------------+---------+-----------+----------+-------------
 account_id         | bigint  |           |          |
 created_timestamp  | bigint  |           |          |
 deleted            | boolean |           | not null | false
 modified_timestamp | bigint  |           | not null |
 metadata           | bytea   |           | not null | '\x'::bytea
 serial_number      | bigint  |           | not null |
 token_id           | bigint  |           | not null |
Indexes:
    "nft_pkey" PRIMARY KEY, btree (token_id, serial_number)
```

2021-06-25 15:42 UTC, steven-sheehy requested changes

2021-06-25 15:42 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  const orderQuery = `order by ${nftQueryColumns.SERIAL_NUMBER} ${order}`;
Order not needed since there can only be one due to the unique index.

2021-06-25 15:42 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  const anchorAccountId = response.nfts.length > 0 ? response.nfts[response.nfts.length - 1].account_id : 0;
Should anchor by serial number for same reasons as before.

2021-06-25 16:19 UTC, xin-hedera requested changes

2021-06-25 16:19 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    utils.buildComparatorFilter(key, '0'),
q: just wanna confirm 0 is an invalid serial number.

2021-06-25 16:19 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateSerialNumberParam for invalid ${serialNum}`, async () => {
```suggestion
    test(`Verify validateSerialNumberParam for invalid ${serialNum}`, () => {
```

2021-06-25 16:19 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateSerialNumberParam for valid ${serialNum}`, async () => {
```suggestion
    test(`Verify validateSerialNumberParam for valid ${serialNum}`, () => {
```

2021-06-25 16:19 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateTokenIdParam for invalid ${tokenId}`, async () => {
```suggestion
    test(`Verify validateTokenIdParam for invalid ${tokenId}`, () => {
```

2021-06-25 16:19 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateTokenIdParam for valid ${tokenId}`, async () => {
```suggestion
    test(`Verify validateTokenIdParam for valid ${tokenId}`, () => {
```

2021-06-25 16:21 UTC, ijungmann commented on hedera-mirror-rest/tokens.js
> +  const anchorAccountId = response.nfts.length > 0 ? response.nfts[response.nfts.length - 1].account_id : 0;
I agree

2021-06-25 17:00 UTC, Nana-EC commented on docs/design/nft.md
> +  account_id            bigint                  not null,
Can do

2021-06-25 17:11 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    utils.buildComparatorFilter(key, '0'),
I believe so but let me check. It is CS after all :)

2021-06-25 17:15 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    utils.buildComparatorFilter(key, '0'),
Verified, does indeed start at 1

2021-06-25 17:25 UTC, ijungmann commented on hedera-mirror-rest/tokens.js
> +  const conditions = [`${nftQueryColumns.TOKEN_ID} = $1`, `${nftQueryColumns.DELETED} = false`];
We also need to look at the `entity.deleted` flag for the token, as it was decided we did not want to set every `nft.deleted` flag on a TokenDelete.

2021-06-25 17:25 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-05-all-params.spec.json
> +        "serial_number": 4
Fixed

2021-06-25 17:25 UTC, Nana-EC commented on docs/design/nft.md
> +  account_id            bigint                  not null,
Updated

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const orderQuery = `order by ${nftQueryColumns.SERIAL_NUMBER} ${order}`;
Reverted

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const anchorAccountId = response.nfts.length > 0 ? response.nfts[response.nfts.length - 1].account_id : 0;
Updated

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +const verifyValidAndAInvalidTokensFilters = (invalidFilters, validFilters) => {
Renamed

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateAndParseFilters for invalid ${filterString}`, async () => {
Removed unnecessary asyncs

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateAndParseFilters for valid ${filterString}`, async () => {
Removed unnecessary asyncs

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    const initialQuery = [tokens.nftSelectQuery].join('\n');
Simplified

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    // invalid format
Reordered

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateSerialNumberParam for invalid ${serialNum}`, async () => {
Removed unnecessary asyncs

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateSerialNumberParam for valid ${serialNum}`, async () => {
Removed unnecessary asyncs

2021-06-25 17:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateTokenIdParam for invalid ${tokenId}`, async () => {
Removed unnecessary asyncs

2021-06-25 17:27 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +    test(`Verify validateTokenIdParam for valid ${tokenId}`, async () => {
Removed unnecessary asyncs

2021-06-25 17:28 UTC, ijungmann requested changes
Mentioned above about `entity.deleted` for tokens

2021-06-25 17:28 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const conditions = [`${nftQueryColumns.TOKEN_ID} = $1`, `${nftQueryColumns.DELETED} = false`];
Ahh the edge case. Thanks, will add

2021-06-25 17:58 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const conditions = [`${nftQueryColumns.TOKEN_ID} = $1`, `${nftQueryColumns.DELETED} = false`];
Added.
I wish we didn't have to do the join, tokens and entities are just gonna keep getting bigger. 
I'm wondering if we should consider  duplicating the deleted field for child entity tables such as `Token` and `Schedule` to optimize the read performance.
Future consideration maybe

2021-06-25 18:52 UTC, steven-sheehy approved these changes
LGTM

2021-06-25 19:05 UTC, xin-hedera approved these changes
LGTM

2021-06-25 19:57 UTC, ijungmann commented on hedera-mirror-rest/tokens.js
> +  const conditions = [`${nftQueryColumns.TOKEN_ID} = $1`, `${nftQueryColumns.DELETED} = false`];
I agree, it's an unfortunate situation, we can consider ways to make it cleaner at some point.

2021-06-25 19:58 UTC, ijungmann approved these changes

2021-06-26 02:06 UTC, merged