Custom fees support importer
hashgraph/hedera-mirror-node pull request #2173
Opened 2021-06-24 16:16 UTC by xin-hedera

**Detailed description**:

This is just for the draft design review.

**Which issue(s) this PR fixes**:
Relates to #2166 

**Special notes for your reviewer**:

This is the hedera-protobufs custom fees PR (https://github.com/hashgraph/hedera-protobufs/pull/42).

**Checklist**

- [x] Documentation added
- [ ] Tests updated

2021-06-25 04:31 UTC, ijungmann requested changes

2021-06-25 04:31 UTC, ijungmann commented on docs/design/custom-fees.md
> +);
I think this should have the fee collector account id as well.  I'm not actually clear if one can have multiple fees of the same token with different collectors, that may affect the primary key.

2021-06-25 04:31 UTC, ijungmann commented on docs/design/custom-fees.md
> +);
Is it possible to delete all custom fees for a token?  Seems like we may have an issue querying for a token that had custom fees at one point, but has since had them all deleted.

2021-06-25 04:31 UTC, ijungmann commented on docs/design/custom-fees.md
> +- Update `/api/v1/transactions` response to add assessed custom fees. Note if a assessed custom fee doesn't have a
nit
```suggestion
- Update `/api/v1/transactions` response to add assessed custom fees. Note if an assessed custom fee doesn't have a
```

2021-06-25 04:31 UTC, ijungmann commented on docs/design/custom-fees.md
> +            }
My understanding is these are already going to be present in the `transfer_list` and `token_transfer_list`, similar to how non_fee_transfers are, and the `assessed_custom_fees` field is only to document what would be required.  So these transfers would be duplicated, I'm not sure it's necessary.

2021-06-25 14:27 UTC, xin-hedera commented on docs/design/custom-fees.md
> +- Update `/api/v1/transactions` response to add assessed custom fees. Note if a assessed custom fee doesn't have a
sure

2021-06-25 14:30 UTC, xin-hedera commented on docs/design/custom-fees.md
> +);
fee collector account is in individual fixed_fee / fractional_fee.

a row in this table corresponds to the full custom fees in a TokenCreate/TokenUpdate transaction, I think you mapped it to the protobuf `CustomFee`, it is actually the protobuf `CustomFees` + the token the custom fees is attached to + consensus timestamp.

2021-06-25 14:32 UTC, xin-hedera commented on docs/design/custom-fees.md
> +);
For the second question, my interpretation of the services protobuf is yes the custom fees for a token can be deleted.

In that case, the row will have empty json array for both fixed_fees and fractional_fees.

2021-06-25 14:54 UTC, xin-hedera commented on docs/design/custom-fees.md
> +            }
rechecked the conversation you had with Michael, saw he confirmed the actual balance changes are in `transfer_list` and `token_transfer_list`. so yes this can be optional as `non_fee_transfers`. I'll adjust the sample json output, but am still debating if we should mandatorily ingest the assessed fees and show them in the response. Open to any suggestions.

2021-06-25 14:58 UTC, ijungmann commented on docs/design/custom-fees.md
> +);
Okay, yes, I missed the actual types and read this as being 1 row = 1 custom fee, not the entirety.  Looks good then.

2021-06-25 16:15 UTC, ijungmann commented on docs/design/custom-fees.md
> +            }
I was originally for having no new logic and just saying "the fees are in the transfers list", but considering we do keep a separate list of non_fee_transfers (behind a feature flag), it seems logical to at least ingest them into a separate table.

2021-06-26 05:38 UTC, steven-sheehy requested changes

2021-06-26 05:38 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
We've never used jsonb. We should normalize this out a bit more. The proto design is a bit complex, but effectively there's a list of custom fees associated with each token. Here you have two levels of lists: that token's fees over time and the list of fees. I think we should collapse these two so that `custom_fee` represents both of those things. I also think it's fine if we denormalize fixed vs fractional so we don't have to break those out separately. Here's my suggested schema:

```sql
create table if not exists custom_fee
(
    amount                bigint not null,
    amount_denominator    bigint,
    collector_account_id  bigint not null,
    consensus_timestamp   bigint not null,
    denominating_token_id bigint,
    maximum_amount        bigint,
    minimum_amount        bigint,
    token_id              bigint not null
);
alter table custom_fee add primary key (token_id, consensus_timestamp, collector_account_id);
```

Not sure on exact names of `amount` and `amount_denominator`, but `amount` would be the numerator for fractional and whole number for fixed. We could also store `amount_fixed` and `amount_fractional` if we're okay with storing the divided value.

2021-06-26 05:38 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    default void onAssessedCustomFee(AssessedCustomFee assessedCustomFee) throws ImporterException {
We'd need an `onCustomFee()` as well.

2021-06-26 05:38 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +- Update `/api/v1/transactions` response to add assessed custom fees. Note if a assessed custom fee doesn't have a
Update to only do for `/transactions/id`

2021-06-26 05:38 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +Add `/api/v1/tokens/<token_id>/customfees` to return the historical custom fees of a token
Is this a requirement from the business? Want to make sure there's demand for this before we develop.

2021-06-26 05:38 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +Add `/api/v1/tokens/<token_id>/customfees` to return the historical custom fees of a token
Instead of a custom fees specific endpoint, really what we need is the ability to see a snapshot of a token at a certain timestamp that already includes the custom fees. e.g. `/api/v1/tokens/:id?timestamp:1234`

2021-06-26 05:38 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +        "fixed_fees": [
Wondering if we should normalize fixed vs fractional. Especially since a double and long are both just number in js it makes it easier.

2021-06-28 15:51 UTC, Nana-EC requested changes

2021-06-28 15:51 UTC, Nana-EC commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
Do we want to take the opportunity to capture the payer account in this table?
I know it's possible to do so with a join eventually.
Actually is that always the case? Where the transaction payer is the custom fee payer?

One issue that we had with crypto transfer was customers not being able to clearly see the exact 1:1 of sender and receiver.
We have this with `nft_transfer`, maybe we should start to standardize capturing this going forward where we can and leave bar transfer as the exception due to network limitation.

2021-06-28 15:51 UTC, Nana-EC commented on docs/design/custom-fees.md
> +- Update `/api/v1/transactions` response to add assessed custom fees. Note if a assessed custom fee doesn't have a
Yeah, leave out of transactions list

2021-06-28 15:51 UTC, Nana-EC commented on docs/design/custom-fees.md
> +  "custom_fees": [
This history is missing the fee payers and is therefore incomplete.
Maybe we should capture the fee payer in the table also for completeness

2021-06-28 16:03 UTC, xin-hedera commented on docs/design/custom-fees.md
> +  "custom_fees": [
oh this is the history of the custom fees schedule for a specific token, so there won't be payers.

2021-06-28 16:04 UTC, xin-hedera commented on docs/design/custom-fees.md
> +Add `/api/v1/tokens/<token_id>/customfees` to return the historical custom fees of a token
I'll ask if this is a required from a business perspective.

2021-06-28 16:18 UTC, xin-hedera commented on docs/design/custom-fees.md
> +Add `/api/v1/tokens/<token_id>/customfees` to return the historical custom fees of a token
this creates confusion since we don't support the snapshot of other token fields in the past.

2021-06-28 16:21 UTC, xin-hedera commented on docs/design/custom-fees.md
> +  on assessed_custom_fee (collector_account_id, consensus_timestamp);
yes I'll remove it. Since we decided not to show assessed custom fees in `/api/v1/transactions` , the index isn't needed anymore.

2021-06-28 16:22 UTC, xin-hedera commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
Michael confirmed it's always the payer of the transactions who pays the custom fees.

2021-06-28 16:44 UTC, xin-hedera commented on docs/design/custom-fees.md
> +- Add to `token` table a new column `can_update_custom_fees_with_admin_key` (boolean not null)
inherited from HAPI protobuf and I do see the frustration. However it precisely describes what this field is and how it works.

2021-06-28 17:03 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
the primary motivation of using jsonb is to simply the tables. The advantages here is only one row for a custom fees schedule of a token at the `consensus_timestamp` plus `fixed_fees` and `fractional_fees` are good candidates for further compression.

We also have a special case to handle with the new schema: the custom fees schedule is deleted. We can make `collector_account_id` nullable to indicate that the change at the `consensus_timestamp` is a deletion when it's `null`.

2021-06-28 19:07 UTC, xin-hedera commented on docs/design/custom-fees.md
> +Add `/api/v1/tokens/<token_id>/customfees` to return the historical custom fees of a token
Confirmed that historical custom fees schedule is a must-have feature.

2021-06-28 19:18 UTC, Nana-EC commented on docs/design/custom-fees.md
> +  "custom_fees": [
Ahh that clarifies things. Thanks

2021-06-28 19:25 UTC, Nana-EC commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
Yeah, but a history of custom fees will likely require a join on the transactions table to get the payer account right?
I'm suggesting we add it here to paint a more complete story.
In general I think it's better that we always have to and from when it comes to transfer tables

2021-06-28 19:25 UTC, Nana-EC commented on docs/design/custom-fees.md
> +- Add to `token` table a new column `can_update_custom_fees_with_admin_key` (boolean not null)
Gotcha

2021-06-28 19:34 UTC, xin-hedera commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
we don't have to join on payer in `/transactions/{id}` since the assessed fees are looked up by joining on the consensus timestamp.

since it's guaranteed the payer of the transaction is always the payer of the assessed custom, adding payer to the table doesn't add value and is really a duplicate.

2021-06-28 19:38 UTC, xin-hedera commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
perhaps adding payer account id to the transaction json output's individual assessed custom fee? that way, it's more consistent with other transfers.

2021-06-28 20:11 UTC, Nana-EC commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
Ahh good point in the transaction endpoint case, you're right then we get it with the transaction id lookup.
My concern is more for a future custom fee REST API that lists all the transfers made that are custom fees, or pulls from this to get a full list of all transfers.
In that case we'd have to join again with transactions to get payer id.
I'd just prefer to have that data in the table now vs need to do a migration to go add it.

2021-06-29 03:27 UTC, ijungmann commented on docs/design/custom-fees.md
> +Add `/api/v1/tokens/<token_id>/customfees` to return the historical custom fees of a token
Yes, I believe our current handling of `TokenUpdate` would not support the historical viewing of a token.

2021-06-29 14:58 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
There is another issue about the primary key. a custom fees schedule may have multiple entries for the same collector, e.g., pay certain hbar to account X, pay certain token A to account X, pay certain token B to account X...

2021-06-29 16:59 UTC, xin-hedera commented on docs/design/custom-fees.md
> +  - `denominator`
will remove these domain classes once we decide to go with the normalized schema

2021-06-29 17:45 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
We could go without a primary key and just have an index on token_id/consensus_timestamp.

2021-06-29 17:48 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +            }
Any guidance on this from product management?

2021-06-29 20:31 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
> 
> We also have a special case to handle with the new schema: the custom fees schedule is deleted. We can make `collector_account_id` nullable to indicate that the change at the `consensus_timestamp` is a deletion when it's `null`.

Just realized can't rely on token entity `modified_timestamp` to tell if the custom fees schedule was deleted at or before `modified_timestamp` cause TokenUpdate can change many fields without touching custom fees schedule. So we have two options:

1. The trick in the above quoted comment
2. Add a column `custom_fees_modified_timestamp` to `token` and keep `custom_fee.collector_account_id` `not null`.

2021-06-29 20:41 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    created_timestamp     bigint not null,
renamed it from `consensus_timestamp`, created better describes the field and also in the token info json response, `created_timestamp` is easier to understand and more distinguishable when it's mixed with the token's created and modified timestamp.

2021-06-29 20:44 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
more on it. the only viable way is the trick: make `collector_account_id` nullable, and a single row for a `created_timestamp` and a null `created_account_id` means the custom fees schedule for the token is deleted at the `created_timestamp`. All because we need to support historical custom fees schedule lookup.

2021-06-29 22:20 UTC, Nana-EC commented on docs/design/custom-fees.md
> +create table if not exists assessed_custom_fee (
Based of off offline discussion adding payer to REST API result but leaving it out of table is fine by me since we have to do the join anyway

2021-06-30 17:01 UTC, xin-hedera commented
moved it back to draft since there will be incompatible changes in protobufs for HIP-18.

2021-07-01 14:35 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    fractional_fees     jsonb,
added a boolean column `has_custom_fee` per Steven's suggestion

2021-07-02 15:18 UTC, Nana-EC requested changes

2021-07-02 15:18 UTC, Nana-EC commented on docs/design/custom-fees.md
> +### Custom Fee Parsing
Can you add a description here to note which domains are insert only and which will have updates.
Therefore which ones can utilize PgCopy for inserts and which will use Upsert.

2021-07-02 15:18 UTC, Nana-EC commented on docs/design/custom-fees.md
> +
You should add a PgCopy section to highlight those new classes
For the Upsert one please note any custom logic for the insert that requires extraction or comparison with other tables.
For the insert and update note if there are any special clauses that should be in the sql e.g. `where created_timestamp is not null` for update

2021-07-02 15:18 UTC, Nana-EC commented on docs/design/custom-fees.md
> +            "payer_account_id": "0.0.10"
for consistency `token_id` should be here.
Maybe we set it to null for the HBAR case

2021-07-02 15:18 UTC, Nana-EC commented on docs/design/custom-fees.md
> +    created_timestamp         bigint not null,
this table is updatable right? You should not that or if it's insert only.
Assuming updatable we should have a `modified_timestamp` also

2021-07-02 15:24 UTC, xin-hedera commented on docs/design/custom-fees.md
> +            "payer_account_id": "0.0.10"
was going to update it for consistency since we use null to represent non-existent entity id in other rest responses.

2021-07-02 15:25 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    created_timestamp         bigint not null,
both new tables are insert only.

2021-07-02 15:57 UTC, xin-hedera commented on docs/design/custom-fees.md
> +insert into t_transaction_types (proto_id, name) values (45, 'TOKENFEESCHEDULEUPDATE');
```suggestion
insert into t_transaction_types (proto_id, name, entity_type) values (45, 'TOKENFEESCHEDULEUPDATE', 5);
```

2021-07-02 21:35 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    maximum_amount            bigint,
remvoed `has_custom_fee`

2021-07-02 21:36 UTC, xin-hedera commented on docs/design/custom-fees.md
> +### Custom Fee Parsing
added, both are insert-only

2021-07-02 21:36 UTC, xin-hedera commented on docs/design/custom-fees.md
> +
added

2021-07-02 21:37 UTC, xin-hedera commented on docs/design/custom-fees.md
> +            "payer_account_id": "0.0.10"
updated here as well as `denominating_token_id` in `custom_fees` in token info response to be `null` deemed necessary.

2021-07-02 21:51 UTC, steven-sheehy approved these changes

2021-07-02 21:53 UTC, Nana-EC commented on docs/design/custom-fees.md
> +    created_timestamp         bigint not null,
Got it, thanks

2021-07-02 21:54 UTC, Nana-EC approved these changes
LGTM

2021-07-02 22:00 UTC, ijungmann approved these changes

2021-07-02 22:01 UTC, merged