Add IP metrics to REST
hashgraph/hedera-mirror-node pull request #2174
Opened 2021-06-24 17:47 UTC by ijungmann

**Detailed description**:
Add a metric to track which IPs hit which endpoints.

**Which issue(s) this PR fixes**:
Fixes #2130 

**Special notes for your reviewer**:

**Checklist**

- [ ] Documentation added
- [ ] Tests updated

2021-06-24 18:28 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +  recordIpAndEndpoint('/accounts/{id}', req.ip);
This is a cross cutting concern and shouldn't be interspersed throughout every business class. Should use a middleware to capture this.

2021-06-24 20:40 UTC, ijungmann commented on hedera-mirror-rest/accounts.js
> +  recordIpAndEndpoint('/accounts/{id}', req.ip);
Tweaking the placement a bit, but now that I see how to get the route out of the req object, I can move this entirely into the `metricsHandler` (or a separate middleware).

2021-06-25 04:48 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +  help: 'test',
TODO: rename

2021-06-25 04:49 UTC, ijungmann commented
A sample of what the metrics will look like (tested locally).
`ip_count_bucket{le="0.1",endpoint="/api/v1/transactions/:id",ip="::1"} 0
ip_count_bucket{le="5",endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_bucket{le="15",endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_bucket{le="50",endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_bucket{le="100",endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_bucket{le="500",endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_bucket{le="+Inf",endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_sum{endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_count{endpoint="/api/v1/transactions/:id",ip="::1"} 1
ip_count_bucket{le="0.1",endpoint="/api/v1/accounts",ip="::1"} 0
ip_count_bucket{le="5",endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_bucket{le="15",endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_bucket{le="50",endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_bucket{le="100",endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_bucket{le="500",endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_bucket{le="+Inf",endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_sum{endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_count{endpoint="/api/v1/accounts",ip="::1"} 1
ip_count_bucket{le="0.1",endpoint="/api/v1/accounts/:id",ip="::1"} 0
ip_count_bucket{le="5",endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_bucket{le="15",endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_bucket{le="50",endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_bucket{le="100",endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_bucket{le="500",endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_bucket{le="+Inf",endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_sum{endpoint="/api/v1/accounts/:id",ip="::1"} 1
ip_count_count{endpoint="/api/v1/accounts/:id",ip="::1"} 1
`

2021-06-25 18:54 UTC, Nana-EC requested changes
Clarification requests

2021-06-25 18:54 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +  app.useAsync(recordIpAndEndpoint);
Q: Where are the analytics from this consumed or sent to?
I don't see a register usage or a Pushgateway, maybe I'm missing something or it integrates with swagger metrics already

2021-06-25 18:54 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +  app.useAsync(recordIpAndEndpoint);
Also is the communication aggregated out so it's not sending for every ping

2021-06-25 19:22 UTC, ijungmann commented on hedera-mirror-rest/server.js
> +  app.useAsync(recordIpAndEndpoint);
[This ticket](https://github.com/swirlds/infrastructure/issues/867) is being worked on and will take care of exporting the data to elastic.

2021-06-25 19:31 UTC, steven-sheehy requested changes

2021-06-25 19:31 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const ipEndpointHistogram = new client.Histogram({
A histogram tracks values that vary in size like request/response times or payload sizes so you can view them in percentile buckets. We're just tracking counts so we should use a counter.

2021-06-25 19:31 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> -
nit: undo

2021-06-25 19:31 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +  name: 'mirror_ip_endpoints_histogram',
We should follow the naming standard we use for all of our custom metrics. We should also follow Prometheus metric naming standards. So this should be `hedera_mirror_rest_request_count`.

2021-06-25 19:31 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +    ipEndpointHistogram.labels(req.route.path, req.ip).observe(1);
We should consider hashing the IP and storing it so we don't run into problems with storing PII data.

2021-06-25 21:05 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const ipEndpointHistogram = new client.Histogram({
Sure, wasn't sure if we wanted something over time.  Switched to a counter, makes it much easier to read.

2021-06-25 21:05 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> -
Done.

2021-06-25 21:06 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +  name: 'mirror_ip_endpoints_histogram',
Sure, replaced with that name

2021-06-25 21:06 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +    ipEndpointHistogram.labels(req.route.path, req.ip).observe(1);
Makes sense, added some logic to hash it.

2021-06-25 21:07 UTC, ijungmann commented
After changes, this is the look:
`hedera_mirror_rest_request_count{endpoint="/api/v1/transactions",ip="eff8e7ca506627fe15dda5e0e512fcaad70b6d520f37cc76597fdb4f2d83a1a3"} 2
hedera_mirror_rest_request_count{endpoint="/api/v1/transactions/:id",ip="eff8e7ca506627fe15dda5e0e512fcaad70b6d520f37cc76597fdb4f2d83a1a3"} 2
hedera_mirror_rest_request_count{endpoint="/api/v1/tokens",ip="eff8e7ca506627fe15dda5e0e512fcaad70b6d520f37cc76597fdb4f2d83a1a3"} 1
hedera_mirror_rest_request_count{endpoint="/api/v1/tokens/:id/balances",ip="eff8e7ca506627fe15dda5e0e512fcaad70b6d520f37cc76597fdb4f2d83a1a3"} 1
`

2021-06-25 21:23 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const ipEndpointHistogram = new client.Histogram({
Counters are over time once they are ingested into the tsdb. A histogram tracks percentiles.

2021-06-25 21:24 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const ipEndpointHistogram = new client.Histogram({
Got it, good to know

2021-06-25 21:31 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +      .labels(req.route.path, crypto.createHash('sha256').update(req.ip).digest().toString('hex'))
On second thought, hashing is not the best approach to anonymizing IP addresses. Since there are limited IP addresses in the world you can use a rainbow table to map them back pretty easily. I suggest we use IP address [masking](https://support.google.com/analytics/answer/2763052?hl=en) like Google Analytics does.

2021-06-25 21:41 UTC, xin-hedera requested changes

2021-06-25 21:41 UTC, xin-hedera commented on hedera-mirror-rest/middleware/metricsHandler.js
> +      .labels(req.route.path, crypto.createHash('sha256').update(req.ip).digest().toString('hex'))
can we use `sha1` and `base64`?  it's faster and the output is smaller. also can just do `digest('base64')`

https://medium.com/@chris_72272/what-is-the-fastest-node-js-hashing-algorithm-c15c1a0e164e

2021-06-26 02:04 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +      .labels(req.route.path, crypto.createHash('sha256').update(req.ip).digest().toString('hex'))
See my note above

2021-06-28 17:29 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +      .labels(req.route.path, crypto.createHash('sha256').update(req.ip).digest().toString('hex'))
Found a library that does basic IP masking, used that and wrote some tests to ensure it does what we want.

2021-06-28 17:38 UTC, ijungmann commented on hedera-mirror-rest/package-lock.json
> +  "lockfileVersion": 2,
Fix

2021-06-28 17:50 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const maskIp = (ip) => {};
What's this for?

2021-06-28 17:52 UTC, ijungmann commented on hedera-mirror-rest/middleware/metricsHandler.js
> +const maskIp = (ip) => {};
Got left over when I moved the code into `utils.js`, removed now.

2021-06-28 17:55 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +  });
These IPs were taken from examples for the library, some made up, none are sensitive.

2021-06-28 18:04 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-06-28 18:50 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-06-28 19:28 UTC, Nana-EC approved these changes
LGTM

2021-06-28 20:59 UTC, xin-hedera submitted a review, later dismissed
LGTM

2021-06-28 21:00 UTC, steven-sheehy approved these changes

2021-06-28 21:58 UTC, Nana-EC submitted a review, later dismissed

2021-06-28 22:39 UTC, steven-sheehy approved these changes

2021-06-28 22:46 UTC, merged