Update README with min versions for tools
hashgraph/hedera-mirror-node pull request #2175
Opened 2021-06-24 18:17 UTC by Nana-EC

**Detailed description**:
Questions around min versions for tools occasionally come up, we should explicitly note it

- Update README.md with minimum versions of used tools

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
Feel free to recommend any extras

**Checklist**

- [x] Documentation added
- [ ] Tests updated

2021-06-24 18:38 UTC, steven-sheehy requested changes

2021-06-24 18:38 UTC, steven-sheehy commented on README.md
> +- Java - JDK 11 (minimum), [OpenJDK 11](https://openjdk.java.net/projects/jdk/11/) (recommended)
We actually use AdoptOpenJDK everywhere and should recommend that.

2021-06-24 18:38 UTC, steven-sheehy commented on README.md
> +- Java - JDK 11 (minimum), [OpenJDK 11](https://openjdk.java.net/projects/jdk/11/) (recommended)
Specifying JDK 11 and OpenJDK 11 is redundant.

2021-06-24 18:38 UTC, steven-sheehy commented on README.md
> +- [Go](https://golang.org/dl/) - v1.13+ (minimum)
Specifying `v1.13+` and `(minimum)` is redundant. Recommend `(minimum)` be removed from all and just add the plus to everything.

2021-06-24 18:43 UTC, xin-hedera commented on README.md
> +- [Go](https://golang.org/dl/) - v1.13+ (minimum)
```suggestion
- [Go](https://golang.org/dl/) - v1.16+
```

2021-06-24 18:43 UTC, Nana-EC commented on README.md
> +- Java - JDK 11 (minimum), [OpenJDK 11](https://openjdk.java.net/projects/jdk/11/) (recommended)
Ahh then we should update the Installation.md also.
Will do that

2021-06-24 18:44 UTC, Nana-EC commented on README.md
> +- [Go](https://golang.org/dl/) - v1.13+ (minimum)
Works for me

2021-06-24 18:53 UTC, SimiHunjan submitted a review, later dismissed
👍

2021-06-25 05:46 UTC, Nana-EC commented on README.md
> +- Java - JDK 11 (minimum), [OpenJDK 11](https://openjdk.java.net/projects/jdk/11/) (recommended)
Updated

2021-06-25 05:46 UTC, Nana-EC commented on README.md
> +- Java - JDK 11 (minimum), [OpenJDK 11](https://openjdk.java.net/projects/jdk/11/) (recommended)
Updated

2021-06-25 05:46 UTC, Nana-EC commented on README.md
> +- [Go](https://golang.org/dl/) - v1.13+ (minimum)
Updated

2021-06-25 14:12 UTC, steven-sheehy approved these changes
LGTM

2021-06-25 14:25 UTC, xin-hedera approved these changes
LGTM

2021-06-25 17:30 UTC, ijungmann approved these changes

2021-06-26 03:06 UTC, merged