Mitigate the impact of pgcopy timeout
hashgraph/hedera-mirror-node pull request #2176
Opened 2021-06-24 18:53 UTC by xin-hedera

**Detailed description**:
Add timeout to `Transactional` annotation to timeout problematic pgcopy. 

**Which issue(s) this PR fixes**:
Fixes #2088 

**Special notes for your reviewer**:
we should adjust down the account balance parser `transactionTimeout` from 300s when the balance parsing is optimized.

**Checklist**

- [x] Documentation added
- [ ] Tests updated

2021-06-24 20:12 UTC, steven-sheehy requested changes

2021-06-24 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    protected int transactionTimeout = 30;
We should use Duration like we do everywhere else. Can use `@DurationUnit(SECONDS)` to change default if no unit specified from ms to s.

2021-06-24 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +    @Transactional(timeoutString = "#{@balanceParserProperties.getTransactionTimeout()}")
With my other suggestion:
```suggestion
    @Transactional(timeoutString = "#{@balanceParserProperties.getTransactionTimeout().toSeconds()}")
```

2021-06-24 20:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +    @Transactional(timeoutString = "#{@balanceParserProperties.getTransactionTimeout()}")
updated

2021-06-24 20:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    protected int transactionTimeout = 30;
updated

2021-06-24 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
> +    @DurationMin(seconds = 30)
Add `@NotNull`

2021-06-24 21:55 UTC, steven-sheehy approved these changes
LGTM

2021-06-25 04:28 UTC, Nana-EC approved these changes
LGTM

2021-06-25 04:33 UTC, ijungmann approved these changes

2021-06-25 14:24 UTC, merged