NFT transaction history REST API
hashgraph/hedera-mirror-node pull request #2177
Opened 2021-06-25 06:46 UTC by Nana-EC

**Detailed description**:
With the addition of native NFTs and the ability transfer them it will be important to should the transaction history for a particular NFT.

- Add a `/api/v1/tokens/{id}/nfts/{serialNumber}/transactions` endpoint to `server.js`
- Update `token.js` with logic to pull transfer details from `nft_transfer` and delete detail from `nft` joined with `transaction` table info
- Add spec files to cover integration testing

Additionally in an effort to have more manageable REST code, adopt a model oriented approach
- Add a `models` and `controllers` directory
- Add an `nft.js` model 
- Add an `nft_transfer.js` model
- Add a `transaction.js` model
- Add a `transactionType` model
- Add a `trnasactionTypes` controller to pull types from db
- Update `server.js` to make db call on startup. This doubly servers as a db connection validation on startup prior to any requests being serviced. Assign result to global param to avoid asynchronous logic of getting types

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
With modification of `transactionType` logic, the join with `transaction_types` table as part of the transactions call is no longer needed and can be optimized.

**Checklist**

- [ ] Documentation added
- [ ] Tests updated

2021-06-28 21:19 UTC, xin-hedera requested changes

2021-06-28 21:19 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  const deleteWhereCondition = `where ${conditions.join('\nand ')}`;
Q: will there not be nft transfers in the transaction record of a `TokenWipe` transaction?

2021-06-28 21:19 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    global.transactionTypes.getId(transactionType);
nit:

```suggestion
   transactionTypes.getId(transactionType);
```

2021-06-28 21:19 UTC, xin-hedera commented on hedera-mirror-rest/server.js
> +  verifyDbConnection().then(() => {
for completeness, add an error handler to the thenable.

2021-06-28 21:19 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration.test.js
> +      `type = ${global.transactionTypes.getId('TOKENCREATION')}`
nit:

```suggestion
      `type = ${transactionTypes.getId('TOKENCREATION')}`
```

2021-06-28 21:55 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const deleteWhereCondition = `where ${conditions.join('\nand ')}`;
For `TOKENBURN` and `TOKENWIPE` the receiver is empty and the sender is the current owner.
So everything other than TOKENDELETE for nfts should have an accompanying transfer

2021-06-28 21:57 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +    global.transactionTypes.getId(transactionType);
I guess in general I could remove the global.
Wanted to be explicit it was a global variable but removing it is okay with me as we don't do `global.logger`

2021-06-28 22:47 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  const deleteWhereCondition = `where ${conditions.join('\nand ')}`;
the follow-up question is does tokendelete for a nft type implicitly mean all the nfts are deleted? if not, we should not make such a transfer.

2021-06-29 03:35 UTC, ijungmann commented on hedera-mirror-rest/tokens.js
> +  const deleteWhereCondition = `where ${conditions.join('\nand ')}`;
I'm not 100% sure on that, I know in the existing TokenDelete it [renders the tokens effectively useless](https://github.com/hashgraph/hedera-docs/blob/master/docs/hedera-api/token-service/tokendelete.md), you cannot transfer or do any operations on the tokens, but I don't know for a fact that it is viewed as "deleted" in the same way a burn or wipe would be.  I'll check on that.

2021-06-29 16:37 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integration.test.js
> +      `type = ${global.transactionTypes.getId('TOKENCREATION')}`
Removed

2021-06-29 16:37 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +  verifyDbConnection().then(() => {
Added

2021-06-29 16:38 UTC, ijungmann requested changes
Looks good, some feedback.
Also happy to see the `async/await` virus is starting to get contained again.

2021-06-29 16:38 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-01-no-args.spec.json
> +        "deleted": true,
With current logic the `TokenDelete` will not mark the NFT as deleted, only the `Token Entity`.  The rest of this is well set up for a `TokenBurn` or `TokenWipe` scenario, but would also prefer one with a `TokenDelete` where only the Entity is deleted

2021-06-29 16:38 UTC, ijungmann commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft_tr.consensus_timestamp = t.consensus_ns
I think this should be a `right outer join` (or some rearranging), only because in the case of incomplete data, it's possible the db would not have the NFT from a `TokenMint`, but we could still see transfers/transactions from a `CryptoTransfer`, `TokenBurn`, etc.  Would also like to see an integration test for that.

2021-06-29 16:38 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: List nft tokens
nit: "nft tokens" is redundant, would prefer just "nft" or "non-fungible tokens".  That's true for the rest of this doc as well.

2021-06-29 16:38 UTC, ijungmann commented on hedera-mirror-rest/server.js
> +const getTransactionTypes = async () => {
nit: Would this be better as `loadTransactionTypes` or something to indicate we're pulling these from the database?

2021-06-29 16:38 UTC, ijungmann commented on hedera-mirror-rest/tokens.js
> +  const deleteWhereCondition = `where ${conditions.join('\nand ')}`;
Leemon's position is that it should be included.

> I would certainly consider a TokenDelete to be an NFT operation, if the TokenType is an NFT. Because it affects the NFT.

2021-06-29 16:38 UTC, ijungmann commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Needs to be the Entity table here.  For `TokenBurn` or `TokenWipe` we should see transfers, so those should be covered without looking at the NFT table.  For a `TokenDelete` the `Entity` will be marked as deleted, but not the affected `NFTs`, so we need to look at the `entity` table for this.
There's also a potential edge case with this where the `NFT` is burned/wiped, and then the Token is deleted (this cannot happen in reverse order), and we'd get both transactions even though the `TokenDelete` technically wouldn't affect it in this case.  We could have it to where it only goes to the `entity` table if `nft.deleted == false`, though I'm not sure the extra logic/code is worth stopping one extra transaction from getting in.

2021-06-29 16:38 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +    global.transactionTypes.getId(transactionType);
Updated

2021-06-29 16:44 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft_tr.consensus_timestamp = t.consensus_ns
Good point, will look into it

2021-06-29 16:52 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Correct, it should be entity. Will update.
In that case I'd imagine both `receiver_account_id` and `sender_account_id` would be null.
I like the edge case. Although, I'd say it's a valid and is fine to be in the list.
The transaction types will be different so it won't be a duplicate.
I can also just filter out `TOKENDELETE` in the where

2021-06-29 16:55 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +const getTransactionTypes = async () => {
Yeah, I like `loadTransactionTypes`

2021-06-29 17:04 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Actually, I don't think we even need `entity` here. 
We already know the tokenId and only need the `TOKENDELETE` transaction details for a matching token `entity_id`, so transaction table should actually be enough.
Will double check this

2021-06-29 17:23 UTC, steven-sheehy requested changes

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +    consensus_timestamp: utils.nsToSecNs(row.consensus_timestamp),
Why are we not using the `NftTransfer` class here? As it stands, the models serve no purpose outside of grouping static column names.

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/models/nft.js
> +  constructor(accountId, createdTimestamp, deleted, metadata, modifiedTimestamp, serialNumber, tokenId) {
This constructor and other model constructors are never called. We should not add dead code even if the intent is to use it in the future. Use it now or remove it. It's fine to keep the static columns here.

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/models/nftTransfer.js
> +    this.receiver_account_id = EntityId.fromEncodedId(receiverAccountId).toString();
If we are to use this class, we have to decide whether this is an internal class that matches the DB or a display (DTO) class. Right now it's a mismash of both since some fields are converted from db type to REST API format (`receiver_account_id`) while others are not (`consensus_timestamp`).

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/models/transactionTypes.js
> +    this.transactionTypeProtoToNameMap = transactionTypeProtoToNameMap;
This class isn't a model as it is doesn't represent a single row but contains a collection of many rows stored into maps. Instead, it should just have proto_id, name and entity_type. The grouping logic should go in the transaction type service.

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/server.js
> +  global.transactionTypes = new TransactionTypesModel(transactionTypeToProtoMap, transactionTypeProtoToNameMap);
It's bad practice to use globals. Would prefer `transactionTypeService.loadTransactionTypes()` and everyone just interact with the `transactionTypeService` to get a particular type.

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  const tokenId = getAndValidateTokenIdRequestPathParam(req);
Should validate token and nft exists first. Can probably do that just by looking up nft. In which case you can avoid the join later on.

2021-06-29 17:23 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  Transaction.transactionQueryColumns.PAYER_ACCOUNT_ID,
This is quite verbose and hard to read. For readability would prefer `NftTransfer.CONSENSUS_TIMESTAMP`.

2021-06-29 17:29 UTC, Nana-EC commented on hedera-mirror-rest/controllers/transactionTypes.js
> +const transactionTypeToProtoMap = new Map();
Agreed, that's more appropriate. There will be a controllers or routes folder but this can be the start of the services

2021-06-29 17:32 UTC, Nana-EC commented on hedera-mirror-rest/models/nftTransfer.js
> +    this.receiver_account_id = EntityId.fromEncodedId(receiverAccountId).toString();
This should be a DTO from which a DB query row result could be provided in the constructor and the resultant object would have the columns formatted for display.
Will add the missing format logic or in the case I kill the constructor will leave it for future addition.
The idea would be the simple list endpoints would be able to use this instead of the `formatRow` functions we have

2021-06-29 17:33 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const tokenId = getAndValidateTokenIdRequestPathParam(req);
Yeah, I realized we didn't have a valid 404 case.
Will add

2021-06-29 17:35 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  Transaction.transactionQueryColumns.PAYER_ACCOUNT_ID,
I might have to make these all static methods then with the option to add the table alias name on demand

2021-06-29 18:17 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: List nft tokens
Agreed, will update

2021-06-30 03:09 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-01-no-args.spec.json
> +        "deleted": true,
It's a union so updating the logic to use entity table should have it show up here and shouldn't need to have a separate spec just for delete.

2021-06-30 04:24 UTC, Nana-EC commented on hedera-mirror-rest/models/nftTransfer.js
> +    this.receiver_account_id = EntityId.fromEncodedId(receiverAccountId).toString();
Adding models and view models to capture the separate logic

2021-06-30 04:57 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const tokenId = getAndValidateTokenIdRequestPathParam(req);
Hmm, I'm not sure that the extra 2 roundtrips are worth it.
Since even if they are both missing we'd still want make a call to cover the `TOKENDELETION` case.

2021-06-30 04:59 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-info-05-invalid-serialnumber-path-param.spec.json
> +          "message": "Invalid parameter: serialnumber"
There's an edge case here as we have to consider partial data also. 
For the transaction history case so far as the tokenId and serialNumber are of the right format we wanna make the calls and not error out.
Shouldn't matter if token and nft are missing form the db. 
If there's `nft_transfer` info or even just a `TOKENDELETION` transaction case we'd wanna show that instead of an error.

2021-06-30 05:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-01-no-args.spec.json
> +        "deleted": true,
Fixed and updated test coverage

2021-06-30 05:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft_tr.consensus_timestamp = t.consensus_ns
Adopted

2021-06-30 05:40 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      summary: List nft tokens
Updated

2021-06-30 05:40 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +const getTransactionTypes = async () => {
Updated

2021-06-30 05:40 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Relying on transaction table. Let me know if that works for you or if I missed something

2021-06-30 05:44 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-info-04-invalid-tokenid-path-param.spec.json
> +          "message": "Invalid parameter: tokenid"
Agreed it's an issue with the path, which is why the file is named appropriately. 
Regarding the message error this is the convention we've done so far see `TopicMessageServiceTest-06-invalid-topic-id.spec.json`
If we're gonna change it we should standardize for all.
In which case I can open a ticket to ensure they're all addressed.

2021-06-30 05:53 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +                    - message: "Invalid parameter: order"
Added for `/api/v1/tokens/{id}/nfts` not convinced yet there is a valid case of 404 for `/api/v1/tokens/{id}/nfts/{serialnumber}/transactions` given partial data scenario

2021-06-30 05:57 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: integer
There's a `format: int64` that I'll add

2021-06-30 05:58 UTC, Nana-EC commented on hedera-mirror-rest/controllers/transactionTypes.js
> +const transactionTypeToProtoMap = new Map();
Broke this out into a Service

2021-06-30 06:18 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +  global.transactionTypes = new TransactionTypesModel(transactionTypeToProtoMap, transactionTypeProtoToNameMap);
Removed global variable logic

2021-06-30 07:39 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +    consensus_timestamp: utils.nsToSecNs(row.consensus_timestamp),
`NftTransfer` isn't the right class to use here since the fields differ slightly.
I've added some viewModels and use the appropriate class here

2021-06-30 07:39 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +  /api/v1/tokens/{id}/nfts/{serialnumber}:
Added `serialNumberPathParam` and `tokenIdPathParam`

2021-06-30 07:40 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Added

2021-06-30 07:40 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: integer
Added

2021-06-30 07:40 UTC, Nana-EC commented on hedera-mirror-rest/models/nft.js
> +  constructor(accountId, createdTimestamp, deleted, metadata, modifiedTimestamp, serialNumber, tokenId) {
Now used with the breakout between model and viewmodel and usage in `tokens` and `transactions`

2021-06-30 07:41 UTC, Nana-EC commented on hedera-mirror-rest/models/transactionTypes.js
> +    this.transactionTypeProtoToNameMap = transactionTypeProtoToNameMap;
Moved

2021-06-30 21:43 UTC, xin-hedera requested changes

2021-06-30 21:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
don't see why we need the `nft` table, it's a right outer join between `nft` and `nft_transfer`, and no nft table column is in the select fields.

2021-06-30 22:14 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
Yeah I had to change it to this to capture the partial data case where an NFT doesn't exist in db but there are `nft_transfers` or a `TOKENDELETION`.
Originally I used the `nft` table in the join but that will result in no values when there's no NFT.
This allows for optionally pulling in `nft` rows if they are present

2021-06-30 22:16 UTC, steven-sheehy requested changes

2021-06-30 22:16 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/Nfts'
Add 204 for token exists but no nft returned with filter criteria.

2021-06-30 22:16 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Don't we have an enum for this?

2021-06-30 22:16 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodels/nftViewModel.js
> +    this.serial_number = Number(nftModel.serial_number);
BigInt, but shouldn't the model already be BigInt. Or if not, it should be set within its constructor.

2021-06-30 22:16 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.charged_tx_fee = Number(transactionModel.charged_tx_fee);
Shouldn't the model already be a number?

2021-06-30 22:16 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  const nftTransactionHistoryViewModel = new NftTransactionHistoryViewModel(row);
Just return the viewmodel, no need to remap from the viewmodel.

2021-06-30 22:16 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +const NftViewModel = require('./viewmodels/nftViewModel');
Singular package names.

```suggestion
const NftViewModel = require('./viewmodel/nftViewModel');
```

2021-06-30 22:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
in case:

1. return the nft transfers when nft instance doesn't exist in `nft` table (partial data)
2. no column of `nft` is selected in the query

the more straightforward query is just don't use `nft` table at all. Am I missing sth?

2021-06-30 22:26 UTC, xin-hedera commented on hedera-mirror-rest/viewmodels/nftViewModel.js
> +    this.serial_number = Number(nftModel.serial_number);
node-pg returns bigint as string

2021-06-30 22:28 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodels/nftViewModel.js
> +    this.serial_number = Number(nftModel.serial_number);
So we should correct it to BigInt in the model

2021-06-30 22:33 UTC, ijungmann commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Yes, I would say both sender and receiver are null.
Good call on looking at the Transaction type, I had not considered that, I believe that should work just fine.  One edge case there though, I believe we could receive multiple `TokenDelete` transactions (only one successful, but potentially some failed attempts), so we should probably filter on `SUCCESS` as well

2021-06-30 22:37 UTC, ijungmann commented on hedera-mirror-rest/server.js
> +const getTransactionTypes = async () => {
I would say to update the const here too, but based on Steven's feedback below I wouldn't bother.

2021-06-30 22:49 UTC, Nana-EC commented on hedera-mirror-rest/models/transactionModel.js
> +  static CHARGED_TX_FEE_FULL_NAME = `${this.tableAlias}.${this.CHARGED_TX_FEE}`;
non-FULL_NAME fields would be used in the sql generation functions.
May not be used yet since I didn't want to refactor `transactions.js` as part of this PR.
If I remove it, someone will have to add it right back to use this as part of the eventual refactor.

2021-06-30 22:51 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-02-none.spec.json
> +  "responseStatus": 200,
That's not true in all cases. For example in the partial db case. 
An empty list just suggests the mirror node has no record of transactions for it, though they may exist in network.
I don't think this should be conflated with non existence which is covered in the `/api/v1/tokens/:id/nfts/:serialnumber` case

2021-06-30 22:51 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-02-none.spec.json
> +  "responseStatus": 200,
I'd be okay with returning a 204 in this case instead

2021-06-30 23:13 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-02-none.spec.json
> +  "responseStatus": 200,
I disagree. The mirror node doesn't make a distinction between exists in the network vs exists in the mirror node. We only care about what exists in our db. If we set startDate=now and lookup a `/api/v1/tokens/0.0.1500/nfts/2` that was created yesterday it will return 404 despite existing in the network. Why would this work differently for `/api/v1/tokens/0.0.1500/nfts/2/transactions`?

2021-06-30 23:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-02-none.spec.json
> +  "responseStatus": 200,
I guess this goes both ways.
Currently a mirror node with partial data would return a 404 for a missing transaction, account  etc if an item was missing from the db, even if the item was valid on the network.

2021-07-01 00:49 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +                    - message: "Invalid parameter: order"
I'm stuck in the middle on this one, I understand the `transactions` table is independent of the `nft` and `token` table and thus we'd still have this data, but it is definitely unorthodox to have `/api/v1/tokens/{id}/nft` give 404 and `/api/v1/tokens/{id}/nfts/{serialnumber}/transactions` give data.

2021-07-01 00:56 UTC, ijungmann commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
I believe originally `nft` was in here because it was just a `join`, we wanted to ensure that the `nft` was present in the DB before displaying the transactions.  Now that it's a `right outer join` we're not doing that check and it can be removed, however I know from other comments there's a debate whether or not we should allow `/tokens/{id}/nfts/{serialNumber}` to return a 404 and `/tokens/{id}/nfts/{serialNumber}/transactions` to return data.

2021-07-01 01:00 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +      name: id
I agree it should be `serialnumber` or something to that effect.

2021-07-01 01:16 UTC, xin-hedera requested changes
can you add `index.js` to `model`, `viewmodel`, and `service` packages? the `index.js` exports the corresponding public fields.

so we can import like:

```javascript
const {NftModel} = require('./model');
```

2021-07-01 02:38 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Good call, will add on success

2021-07-01 07:06 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
Yeah. Initially it was for the join.
Now it's for the optimization of sending 1 request to the db.
I could split it out but that would be multiple back and forth calls.
This gets me everything I need in 1 call

2021-07-01 14:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
I meant the following query is equivalent in getting the data and is also 1 call:

```sql
select nft_tr.consensus_timestamp,
       t.payer_account_id,
       t.valid_start_ns,
       nft_tr.receiver_account_id,
       nft_tr.sender_account_id,
       t.type
from nft_transfer nft_tr
join transaction t on nft_tr.consensus_timestamp = t.consensus_ns
where nft_tr.token_id = $1
  and nft_tr.serial_number = $2
union
select t.consensus_ns as consensus_timestamp,
       t.payer_account_id,
       t.valid_start_ns,
       null           as receiver_account_id,
       null           as sender_account_id,
       t.type
from transaction t
where t.entity_id = $1
  and t.type = 35
  and t.result = 22
order by consensus_timestamp desc
limit $3
```

2021-07-01 15:21 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  // get deleted case, use modifiedTimestamp where deleted = true
the comment does not match the delete query.

the delete query doesn't need an order clause since there will be at most 1 match (a specific entity, transaction type TOKENDELETION, result SUCCESS).

there is performance concern in the future when there are many TOKENDELETION transactions. we have an index on type, not on (type, entity_id)

2021-07-01 17:11 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const successTransactionResult = 'SUCCESS';
Yeah, working on it. Had to add a transactionResultService which now uses it. Coming in the next commit

2021-07-02 00:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-info-04-invalid-tokenid-path-param.spec.json
> +          "message": "Invalid parameter: tokenid"
This seems more an issue with the `InvalidArgumentError`. I can add a `forPath()`

2021-07-02 00:14 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.transfers = [];
Didn't want to add to much in this PR. But yes eventually the `transaction.js` should use this and when it does all of that can be moved over

2021-07-02 00:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
We don't but I'll add on

2021-07-02 00:33 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.charged_tx_fee = Number(transactionModel.charged_tx_fee);
Everything from the db is a string. The models currently only extract data. I can add conversions for numbers

2021-07-02 01:37 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  // get deleted case, use modifiedTimestamp where deleted = true
I believe the order affects the result of the union not the deleteQuery.
This is verified in the spec tests I believe.

Fair point on the index.

2021-07-02 02:42 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
You're correct, will adopt

2021-07-02 03:36 UTC, ijungmann reviewed
Will give a longer look tomorrow, don't see anything glaring at this point.

2021-07-02 03:51 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/nftViewModel.js
> +    this.serial_number = Number(nftModel.serial_number);
This is the current logic just copied over and I would like to reduce more churn as doing this requires a few changes since things are used to all data from db being strings.

2021-07-02 03:52 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                                  join transaction t on nft.modified_timestamp = t.consensus_ns and nft.deleted = true
Added

2021-07-02 03:54 UTC, Nana-EC commented on hedera-mirror-rest/models/nftModel.js
> +    this.account_id = dbRow.account_id;
Updated

2021-07-02 03:54 UTC, Nana-EC commented on hedera-mirror-rest/services/tokenService.js
> +    }
Updated

2021-07-02 03:55 UTC, Nana-EC commented on hedera-mirror-rest/services/transactionTypesService.js
> +    }
Deduped

2021-07-02 03:55 UTC, Nana-EC commented on hedera-mirror-rest/models/transactionTypeModel.js
> +    this.entity_type = dbRow.entity_type;
Updated

2021-07-02 03:56 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    return NftTransferViewModel.fromDb(transfer);
Had to remove `fromDb` , now from DB to model to viewmodel

2021-07-02 03:56 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.id = EntityId.fromEncodedId(transactionModel.id).toString();
removed

2021-07-02 03:56 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.memo_base64 = utils.encodeKey(transactionModel.memo); // base64 encode
Updated

2021-07-02 03:56 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.node = transactionModel.node_account_id;
Updated

2021-07-02 03:57 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.transfers = [];
Might remove this viewmodel since it's not yet used. Can be added in a future PR

2021-07-02 03:59 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +                           from nft
Updated

2021-07-02 03:59 UTC, Nana-EC commented on hedera-mirror-rest/models/nftModel.js
> +class NftModel {
Updated

2021-07-02 03:59 UTC, Nana-EC commented on hedera-mirror-rest/models/nftModel.js
> +  constructor(dbRow) {
Updated

2021-07-02 03:59 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +const TransactionTypesService = require('./services/transactionTypesService');
Updated for consistency with Java

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +const getTransactionTypes = async () => {
Updated

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/services/tokenService.js
> +const TokenModel = require('../models/tokenModel');
Updated require

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      name: id
Updated this and all of them

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    return NftTransferViewModel.fromDb(transfer);
Removed fromDb

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/models/nftModel.js
> +    this.created_timestamp = dbRow.created_timestamp;
Updated

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-02-none.spec.json
> +  "responseStatus": 200,
Updated

2021-07-02 04:00 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  and ${NftModel.tableAlias}.${NftModel.SERIAL_NUMBER} = ${NftTransferModel.tableAlias}.${NftTransferModel.SERIAL_NUMBER}`;
Updated

2021-07-02 04:01 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/Nfts'
Added

2021-07-02 04:01 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Added

2021-07-02 04:02 UTC, Nana-EC commented on hedera-mirror-rest/viewmodels/transactionViewModel.js
> +    this.charged_tx_fee = Number(transactionModel.charged_tx_fee);
Removed this view model since it's not used right now and creating churn.

2021-07-02 04:02 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const nftTransactionHistoryViewModel = new NftTransactionHistoryViewModel(row);
Updated

2021-07-02 04:02 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const NftViewModel = require('./viewmodels/nftViewModel');
Not my preference, but  consistency is the name of the game so I'm okay with matching the Java project.

2021-07-02 04:02 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> + * @param {string} query initial pg SQL query string
Updated

2021-07-02 04:03 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const successTransactionResult = 'SUCCESS';
Added

2021-07-02 04:10 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +                    - message: "Invalid parameter: order"
Added

2021-07-02 14:51 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  // get deleted case, use modifiedTimestamp where deleted = true
Also removed comment

2021-07-02 16:16 UTC, steven-sheehy requested changes

2021-07-02 19:08 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-04-timestamp-out-of-range.spec.json
> +  "responseJson": {}
Agreed. Unfortunately seems in the 204 case the content doesn't come through.
Might be a bug or maybe there's extra logic I need to do.
I confirmed the response handler seems the set content you noted about but it doesn't seem to make it to the client.
Will look into it

2021-07-02 19:08 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-10-missing-nft-filter.spec.json
> +  "responseJson": {}
Same comment above. Response is set as expected, just not making it to client. Will look into it again

2021-07-02 19:08 UTC, Nana-EC commented on hedera-mirror-rest/middleware/httpStatusHandler.js
> +  NoContentError: httpStatusCodes.NO_CONTENT,
Agreed, see other comments

2021-07-02 19:11 UTC, Nana-EC commented on hedera-mirror-rest/middleware/httpStatusHandler.js
>    if (shouldReturnMessage(statusCode)) {
No it doesn't based on the logic from `shouldReturnMessage()` since it's not an error or 502 status code

2021-07-02 19:13 UTC, Nana-EC commented on hedera-mirror-rest/model/entity.js
> +class Nft {
File wasn't supposed to be checked in, will remove as it's unused. Will be need in future though with the correct class name

2021-07-02 19:23 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/httpStatusHandler.js
>    if (shouldReturnMessage(statusCode)) {
It shouldn't print either a error or a warning since it's a successful 2xx.

2021-07-02 20:02 UTC, ijungmann reviewed
LGTM, just the 204 issue already being discussed, would be okay making a separate ticket for that if need be.

2021-07-02 20:50 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/nftService.test.js
> +const NFTModel = require('../../model/nft');
nit, should switch to import from the new package exports:

```suggestion
const {NFTModel} = require('../../model');
```

2021-07-02 20:52 UTC, xin-hedera approved these changes
LGTM

2021-07-06 14:56 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionResultService.js
> +    }
`this.promise` is never used.

since after the refactor, load becomes a one-shot effort at startup, we should just fail without retry so imo the `promise` is no longer needed, then we can simplify it to:

```suggestion
    const {rows} = await utils.queryQuitely(TransactionResultService.transactionResultsQuery);
```

2021-07-06 14:59 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionResultService.js
> +    }
this is redundant, when there is no result, rows will be an empty array

2021-07-06 15:59 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionResultService.js
> +    }
Yeah that was the intention, forgot to simplify. Will update, thanks

2021-07-06 16:01 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionResultService.js
> +    }
Should probably throw an error in this case since we should always have results

2021-07-06 16:32 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionResultService.js
> +    }
Actually, there's a circular dependency which is why I don't use the `utils.queryQuietly`.
Will remove the promise though

2021-07-06 16:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-04-timestamp-out-of-range.spec.json
> +  "responseJson": {}
So it seems though it's non standard for us it's actually standard for 204's to have empty body responses - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
In fact it seems some clients reject the body content and we can't rely on them processing it. See noted discussion in link

2021-07-06 16:41 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionResultService.js
> +    }
I see. can leave circular dependency issue to a different ticket

2021-07-06 17:57 UTC, ijungmann submitted a review, later dismissed

2021-07-06 19:30 UTC, Nana-EC commented
Having db integration coordination issue in running integration.test file and new service tests files. Removing new files to unblock PRs needed for this sprint. Should be fine as we have E2E coverage with integration tests.
Will work to add these back in separate PR

2021-07-06 19:58 UTC, ijungmann submitted a review, later dismissed

2021-07-06 20:02 UTC, xin-hedera approved these changes
LGTM

2021-07-06 20:23 UTC, ijungmann approved these changes

2021-07-06 20:28 UTC, xin-hedera approved these changes

2021-07-06 20:37 UTC, Nana-EC commented on hedera-mirror-rest/middleware/httpStatusHandler.js
>    if (shouldReturnMessage(statusCode)) {
It doesn't. Only thrown error class cases pass through this logic.
Have reverted the map name and the export of the map

2021-07-06 20:38 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-04-timestamp-out-of-range.spec.json
> +  "responseJson": {}
Per team discussion will update to not set content on this so response maps to 204 meaning

2021-07-06 20:38 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-10-missing-nft-filter.spec.json
> +  "responseJson": {}
Per team discussion will update to not set content on this so response maps to 204 meaning

2021-07-06 20:38 UTC, Nana-EC commented on hedera-mirror-rest/middleware/httpStatusHandler.js
> +  NoContentError: httpStatusCodes.NO_CONTENT,
Removed as not really an error

2021-07-06 21:30 UTC, Nana-EC commented on hedera-mirror-rest/middleware/httpStatusHandler.js
>    if (shouldReturnMessage(statusCode)) {
Also reverted most changes and moves status code out to `constants` file

2021-07-06 21:34 UTC, steven-sheehy approved these changes
LGTM

2021-07-06 21:35 UTC, ijungmann approved these changes

2021-07-06 21:39 UTC, xin-hedera approved these changes

2021-07-06 21:39 UTC, merged