Change balance file processing to stream account balances to database
hashgraph/hedera-mirror-node pull request #2182
Opened 2021-06-25 23:35 UTC by steven-sheehy

**Detailed description**:
- Change `ProtoBalanceFileReader` to calculate hash using raw input stream instead of proto parsing
- Change `ProtoBalanceFileReader` to return a lazy, streaming `Flux` of `AccountBalance` items to reduce memory usage
- Remove unused reader item consumer

**Which issue(s) this PR fixes**:
Fixes #1927 

**Special notes for your reviewer**:
Improves reading `2021-05-04T14_00_00.844472Z_Balances.pb.gz` on my machine from infinity (due to not having enough memory) to 3s
Improves parsing `2021-05-04T14_00_00.844472Z_Balances.pb.gz` on my machine to 1.8m
It took `9.937 min` in perf for the same file

**Checklist**

- [x] Documentation added
- [x] Tests updated

2021-06-25 23:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/CompositeBalanceFileReader.java
> +            log.info("Read account balance file {} {}successfully in {}",
Since we no longer parse the proto account balance items until the parsing phase, we can't print out the count anymore.

2021-06-25 23:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
> +                .blockFirst();
Calculating the hash directly via the bytes, but separately parsing just the first part of the proto to get the consensus timestamp is faster than parsing everything via proto.

2021-06-26 02:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserTest.java
> -    @Disabled("Fails in CI")
Re-ran the tests in CI a number of times and these never failed, so marking the associated ticket as fixed.

2021-06-26 02:40 UTC, xin-hedera requested changes

2021-06-26 03:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
> +        InputStream inputStream = new DigestInputStream(streamFileData.getInputStream(), messageDigest);
Whoops, fixed.

2021-06-28 15:45 UTC, xin-hedera requested changes

2021-06-28 15:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
> +            accountBalanceFile.setFileHash(DigestUtils.sha384Hex(streamFileData.getInputStream()));
unfortunately `sha384Hex` does not close the input stream.

2021-06-28 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
> +            accountBalanceFile.setFileHash(DigestUtils.sha384Hex(streamFileData.getInputStream()));
Fixed again 😅

2021-06-28 15:54 UTC, xin-hedera approved these changes
LGTM

2021-06-28 16:38 UTC, Nana-EC approved these changes

2021-06-28 18:32 UTC, ijungmann approved these changes

2021-06-28 18:34 UTC, merged