First draft of monitor changes for NFT
hashgraph/hedera-mirror-node pull request #2217
Opened 2021-07-02 03:58 UTC by ijungmann

**Description**:
<!--
Add NFT support to the mirror node monitor

* Add new fields to the TransactionSuppliers to allow for NFT transactions.
* Add support for nft expression that creates a token and mints a serial number

**Related issue(s)**:

Fixes #2132 

**Notes for reviewer**:
Waiting on services to update integration to confirm working.
Waiting on SDK to merge the NFT logic into a stable branch with an artifact, or at least something to JitPack.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-07-13 03:10 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/resources/application.yml
> +          host: 34.74.191.8
We shouldn't be exposing internal network IPs and private keys in temporary commits

2021-07-13 03:54 UTC, ijungmann commented on hedera-mirror-monitor/src/main/resources/application.yml
> +          host: 34.74.191.8
Weird, not sure how that got added to my commit, was not intending to push that file at all.  Removed.

2021-07-14 16:35 UTC, ijungmann commented on docs/design/nft.md
>    - Add a new `nft` expression
Simplified this section now that we have a clearer picture.

2021-07-14 16:38 UTC, ijungmann commented on docs/design/nft.md
> -      created for the transaction suppliers.
Decided to remove the logic that made `nft` expressions mint a serial number as well, it made the ExpressionConverter messy and with the existing transfer/burn/wipe logic where we just continuously increment the serial number, one would already need to mint a huge amount of serial numbers to make those run at any scale, so this wasn't adding a lot of value.

2021-07-14 16:41 UTC, ijungmann commented on docs/design/nft.md
> -      require a longer startup time to generate all the serial nunmbers.
As mentioned in the sub-bullet here, swapping the accounts back and forth would have required having multiple signatures and swapping those out somewhere else.  As long as one runs a `MINT` scenario beforehand for a sufficient amount of time, the auto-increment seems to work well enough.

2021-07-14 16:42 UTC, ijungmann commented on docs/design/nft.md
> +    to `CRYTPO_AND_TOKEN`.
Almost certainly a better name for this.

2021-07-14 16:44 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +        CRYPTO, TOKEN, NFT, CRYPTO_AND_TOKEN
I could also add a `CRYPTO_AND_NFT` (or something to that effect) if it seems useful.  Doing all 3 would require multiple token ids, could be done but would require a bit more configuring.

2021-07-14 16:46 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenBurnTransactionSupplier.java
> +    private final AtomicLong serialNumber = new AtomicLong(1); // The serial number to transfer.  Increments over time.
Comment may be excessive, but I wanted to note that the initial value is the starting serial number to burn/wipe/transfer, and it increments from there.

2021-07-14 19:06 UTC, Nana-EC requested changes
Looks good, one nit and will do a final pass

2021-07-14 19:06 UTC, Nana-EC commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private TransferType transferType = TransferType.NFT;
q: just curious of the choice NFT vs CRYPTO which doesn't require coordination of a token to first exist or an additional mint operation?

2021-07-14 20:31 UTC, steven-sheehy requested changes
Would be good to also update monitor.md with an example NFT flow since it seems like you need a mint operation at a sufficient tps for the other operations to also work. This dependency should be called out there.

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +        CRYPTO, TOKEN, NFT, CRYPTO_AND_TOKEN
My suggestion is only have CRYPTO, TOKEN and NFT in the enum then use a `Set<TransferType> transferTypes = new EnumSet<>()`.

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/resources/application.yml
> +          - name: HCS Pinger
Please undo changes to this file.

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +            boolean isNft = type == ExpressionType.NFT;
Since there's no need for reuse, remove variable and move to if statement

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenWipeTransactionSupplier.java
> +    TokenType type = TokenType.FUNGIBLE_COMMON;
private and not null

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenMintTransactionSupplier.java
> +    TokenType type = TokenType.FUNGIBLE_COMMON;
private and not null

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenCreateTransactionSupplier.java
> +    long maxSupply = 100000000000L;
private

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenCreateTransactionSupplier.java
> +    TokenSupplyType supplyType = TokenSupplyType.INFINITE;
private and not null this and `type`

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenBurnTransactionSupplier.java
> +    @NotNull
Not necessary on final fields. Same for other files.

2021-07-14 20:31 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenBurnTransactionSupplier.java
> +    TokenType type = TokenType.FUNGIBLE_COMMON;
private and not null

2021-07-14 20:58 UTC, ijungmann commented on hedera-mirror-monitor/src/main/resources/application.yml
> +          - name: HCS Pinger
Undone, apparently I reverted to a previous commit at some point.

2021-07-14 20:58 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenBurnTransactionSupplier.java
> +    TokenType type = TokenType.FUNGIBLE_COMMON;
Fixed.

2021-07-14 21:27 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenCreateTransactionSupplier.java
> +    TokenSupplyType supplyType = TokenSupplyType.INFINITE;
Fixed.

2021-07-14 21:28 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenCreateTransactionSupplier.java
> +    long maxSupply = 100000000000L;
Fixed.

2021-07-14 21:28 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenMintTransactionSupplier.java
> +    TokenType type = TokenType.FUNGIBLE_COMMON;
Fixed.

2021-07-14 21:28 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenWipeTransactionSupplier.java
> +    TokenType type = TokenType.FUNGIBLE_COMMON;
Fixed.

2021-07-14 21:34 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
> +            boolean isNft = type == ExpressionType.NFT;
Good point, was leftover.  Fixed.

2021-07-14 21:48 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenBurnTransactionSupplier.java
> +    @NotNull
Fixed.  I'm now realizing a lot of the fields could be marked as final, I think in an earlier version of the monitor that was causing problems with loading the properties, but it seems to work now.

2021-07-14 21:50 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private TransferType transferType = TransferType.NFT;
That was leftover, just wanted to automatically have it do NFT transfers for a while and forgot to put it back.  Fixed now.

2021-07-14 21:52 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +        CRYPTO, TOKEN, NFT, CRYPTO_AND_TOKEN
The set is a good idea.  The only thing about doing a TOKEN and an NFT transfer in one (on doing "ALL"), we would then require separate `nftTokenId` and `tokenId` (or something like that) so we know which goes in which list.  Otherwise it's pretty easy to add that option.

2021-07-15 14:29 UTC, xin-hedera reviewed
No issue found. Will sign off once the existing feedback is addressed.

2021-07-15 15:47 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private final String recipientAccountId;
This forces `recipientAccountId` and `senderAccountId` to be set via a constructor now, which I'm not sure will work with spring boot properties or be properly validated via the annotations that way. Let's just keep setters for everything that is settable by the user. Use final only for internal things that shouldn't be exposed.

2021-07-20 00:42 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +        CRYPTO, TOKEN, NFT, CRYPTO_AND_TOKEN
I've added support for different combos via the `EnumSet`.  I had to add a `PropertiesCorrector` class that takes the list properties `transferTypes.0, transfersTypes.1` and puts them into a list, as they don't load correctly and thus don't get mapped to the supplier correctly.  Working on adding a test and some cleanup.

2021-07-20 03:02 UTC, ijungmann commented
> Would be good to also update monitor.md with an example NFT flow since it seems like you need a mint operation at a sufficient tps for the other operations to also work. This dependency should be called out there.

Added a section for NFTs calling out the need to mint, also added a small blurb about List properties.

2021-07-20 03:08 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private final String recipientAccountId;
I did confirm that it is setting properly and validating when it is missing, so it can be done, but I'm fine with the standard you mentioned, especially since I didn't add `final` anywhere else so it's inconsistent.  I've removed it from these two fields.

2021-07-20 03:09 UTC, ijungmann commented on docs/design/nft.md
> +  - `TokenBurnTransactionSupplier` and `TokenWipeTransactionSupplier` will need an enum `type` attribute, and it will
Removed.

2021-07-20 16:17 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrector.java
> +public interface PropertiesCorrector {
Suggestions for names are welcome.

2021-07-20 16:19 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrectorImpl.java
> +                            ((List) existingList).addAll((List) newList);
The casting here is a little gross, the alternative I had at one point was to have a separate Map of Lists and merge them into the `correctedProperties` map at the end, figured it was nicer to just have one map.

2021-07-20 16:42 UTC, steven-sheehy requested changes

2021-07-20 16:42 UTC, steven-sheehy commented on docs/monitor.md
> +
Add a nftTransfer to go with the mint and show tps for both. I'm interested in how the two TPS relate to each other. If I want to do 100 TPS nftTransfer how many TPS mints do I need?

You can probably move the `transferTypes` example in the previous section to here as the nftTransfer to combine both and simplify.

2021-07-20 16:42 UTC, steven-sheehy commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private EnumSet<TransferType> transferTypes = EnumSet.of(CRYPTO);
```suggestion
    private Set<TransferType> transferTypes = EnumSet.of(CRYPTO);
```

2021-07-20 16:42 UTC, steven-sheehy commented on pom.xml
> +
nit: undo

2021-07-20 16:42 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrectorImpl.java
> +    public Map<String, Object> correctProperties(Map<String, String> properties) {
The correct way to attach custom deserialization logic to a field is to use `@JsonDeserialize(using = StringToSetDeserializer.class)`. This class becomes the `StringToSetDeserializer`. Then you're not leaking it into the generators and don't need to process the entire map, just a particular field.

2021-07-20 16:42 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrector.java
> +public interface PropertiesCorrector {
Remove it

2021-07-20 16:50 UTC, Nana-EC reviewed
Looks good, added naming suggestion. Will wait on other required signoff

2021-07-20 16:50 UTC, Nana-EC commented on docs/monitor.md
> +the `TransactionSupplier`will start with serial number 1, which may have already been deleted or transferred elsewhere.
nit: 
```suggestion
the `TransactionSupplier` will start with serial number 1, which may have already been deleted or transferred elsewhere.
```

2021-07-20 16:50 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrector.java
> +public interface PropertiesCorrector {
Hmm, based on the logic in `PropertiesCorrectorImpl` it's more of an aggregator than it is a corrector right.
It's just generating a list value for list properties.

Maybe `ScenarioPropertiesAggregator` or `ScenarioPropertiesFormatter`.

2021-07-20 16:50 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +        Map<String, Object> correctedProperties = propertiesCorrector.correctProperties(convertedProperties);
Adding on to my aggregator/formatter naming comment below, I wonder if the `convert()` call should be moved into this new method call so it's a single aggregate/format call.

Not required as part of this PR. Just thinking out loud

2021-07-20 19:08 UTC, ijungmann commented on pom.xml
> +
Forgot to push that, done.

2021-07-20 19:35 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrectorImpl.java
> +    public Map<String, Object> correctProperties(Map<String, String> properties) {
Maybe I'm missing something elsewhere, I commented out the `PropertiesCorrector`, added a simple `JsonDeserializer` and added it to the top of `transactionTypes`, and hit it with the debugger, but it never got into it, got the same issue:  `Unrecognized field "transferTypes.0"`.  It doesn't make the connection that the different elements belong to the same property, and instead create separate properties for each which then don't exactly match the property `transactionTypes`

2021-07-20 19:36 UTC, ijungmann commented on hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
> +    private EnumSet<TransferType> transferTypes = EnumSet.of(CRYPTO);
Fixed.

2021-07-20 19:37 UTC, ijungmann commented on docs/monitor.md
> +the `TransactionSupplier`will start with serial number 1, which may have already been deleted or transferred elsewhere.
Fixed.

2021-07-20 20:22 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrectorImpl.java
> +    public Map<String, Object> correctProperties(Map<String, String> properties) {
True. You'd have to change the `ScenarioProperties.properties` to a `Map<String, Object>`. Then it shows up as a `transferTypes` with a map as the field with "0" -> "CRYPTO". This would cause further refactoring of ExpressionConverter though. We can defer this as a follow up task.

2021-07-20 23:08 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrectorImpl.java
> +    public Map<String, Object> correctProperties(Map<String, String> properties) {
Got it, that makes sense.  Sure, I'll leave it and create a followup ticket for it.

2021-07-20 23:13 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/properties/PropertiesCorrector.java
> +public interface PropertiesCorrector {
Yeah, it's a `corrector` in the sense that it comes in as a list but Jackson insists on serializing as individual properties, so this is "correcting" that, but I like `ScenarioPropertiesAggregator` as that's what it's really doing.  This will be removed at some point in a followup using the Deserializer Steven mentioned, but for now it will be `ScenarioPropertiesAggregator`

2021-07-20 23:15 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
> +        Map<String, Object> correctedProperties = propertiesCorrector.correctProperties(convertedProperties);
I thought about that, it would be a bit too much refactoring this late in the PR, and now from what Steven has shown we can remove that new class with some other refactoring, but I agree if this logic ever does get bigger it should move out of this class.

2021-07-21 17:11 UTC, steven-sheehy approved these changes

2021-07-21 17:13 UTC, ijungmann commented on docs/monitor.md
> +
Sure, I did some testing with both MINT and NFT_TRANSFER running at once.  To do 100 TPS on NFT_TRANSFER transferring one at a time, if you're also minting 1 NFT at a time, 105 TPS seems to be the stable minimum for MINT.  I added the TRANSFER to this example to show that, though it should be noted one could not run the example without some adjustments  (doesn't include TOKEN_ASSOCIATE, etc).

I also tested with transferring 1 NFT at 100 tps but minting 10 at a time, at around 12 TPS that looks stable after a few hiccups right at startup, so there are multiple ways to accomplish this.

2021-07-21 18:38 UTC, Nana-EC approved these changes
LGTM

2021-07-21 18:39 UTC, xin-hedera approved these changes

2021-07-21 18:47 UTC, steven-sheehy approved these changes

2021-07-21 19:54 UTC, merged