Custom fees importer
hashgraph/hedera-mirror-node pull request #2236
Opened 2021-07-06 14:13 UTC by xin-hedera

**Description**:

This PR adds HTS custom fees support to the mirror node parser.

- Adds / updates custom fees related database tables
- Adds fee schedule key and custom fees schedule ingestion
- Adds assessed custom fees ingestion
- Updates token upsert generator to include the new columns
- Updates transaction protobuf transactionBody field handling

**Related issue(s)**:

Fixes #2166 

**Notes for reviewer**:

1. hedera-protobufs 0.16.0 adds back the previously deleted deprecated fields back to [Transaction.proto](https://github.com/hashgraph/hedera-protobufs-java/blob/release/0.16/src/main/proto/Transaction.proto), so `TransactionBody body =1;` will no longer fall into unknown fields.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-07-06 19:46 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +            String symbol,
format

2021-07-06 19:46 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +            String symbol) {
format

2021-07-06 19:46 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +            AccountID accountID) {
format

2021-07-06 19:52 UTC, Nana-EC requested changes
Looking good, some suggestions.

2021-07-06 19:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                case FIXED_FEE:
Would personally prefer `getCustomFixedFee(id, protoCustomFee)` and `getCustomFractionFee(id, protoCustomFee)` methods be created and called in switch options.

That way each method encompasses the logic and `insertCustomFees()` is cleaner. 
Code duplication is minimal.

2021-07-06 19:57 UTC, ijungmann requested changes
Couple minor things, looks really good otherwise.

2021-07-06 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AssessedCustomFee.java
> +    @Convert(converter = TokenIdConverter.class)
we should actually do the opposite: remove the `@JsonSerialize(using = EntityIdSerializer.class)` annotation, since in PgCopy we have:

```java
  module.addSerializer(EntityId.class, EntityIdSerializer.INSTANCE);
```

2021-07-06 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java
> +import org.assertj.core.util.Lists;
yup will remove

2021-07-06 21:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                insertTokenFeeScheduleUpdate(recordItem);
updated

2021-07-06 21:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                case FIXED_FEE:
updated

2021-07-07 02:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AssessedCustomFee.java
> +    @Convert(converter = TokenIdConverter.class)
AH you're right, I did add that to the module last time around.
Carry on.

2021-07-07 15:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/CustomFee.java
> +    private EntityId collectorAccountId;
Ignore

2021-07-07 17:34 UTC, steven-sheehy requested changes

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFeeScheduleUpdateTransactionHandler.java
> +public class TokenFeeScheduleUpdateTransactionHandler extends AbstractEntityCrudTransactionHandler {
This is not a token CRUD operation and should not update the entity table, similar to the other token handlers like kyc, freeze, etc.
```suggestion
public class TokenFeeScheduleUpdateTransactionHandler implements TransactionHandler {
```

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +       ('CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES', 244);
I also [see](https://github.com/hashgraph/hedera-protobufs/blob/develop/services/ResponseCode.proto) 245-247

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    on custom_fee (token_id, created_timestamp desc);
```suggestion
    on custom_fee (token_id desc, created_timestamp desc);
```

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
> +    on custom_fee (token_id, created_timestamp desc);
```suggestion
    on custom_fee (token_id desc, created_timestamp desc);
```

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +TRUNCATE TABLE assessed_custom_fee RESTART IDENTITY CASCADE;
Also update grpc cleanup.sql

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +create table if not exists assessed_custom_fee (
Also update timescaledb migration scripts

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +        var actual = jdbcTemplate.query(AssessedCustomFeeWrapper.SELECT_QUERY, AssessedCustomFeeWrapper.ROW_MAPPER);
Why are we using these wrappers and `JdbcTemplate` to verify database results instead of the repositories and domain?

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            updateToken(Token.of(tokenId), consensusTimestamp);
We should not update token table when a different table changes and nothing changes on token. We don't do this for KYC, freeze, etc. When we change to have historical tokens, then `modified_timestamp` will go away anyway.

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                }
This shouldn't be needed. Empty entity IDs are automatically substituted with null by `EntityIdConverter` and `EntityIdSerializer`.

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (!EntityId.isEmpty(denominatingTokenId)) {
Shouldn't be needed

2021-07-07 17:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (minimumAmount != 0) {
Minimum amount of zero should be a valid value that we should probably populate.

2021-07-07 17:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AssessedCustomFee.java
> +        private long consensusTimestamp;
In the custom fees schedule, the same account can collect hbar, fixed fee in a token, and fractional fee in the token the custom fees schedule is attached to. So this can't be a primary key.

2021-07-07 17:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AssessedCustomFee.java
> +        private long consensusTimestamp;
thanks, will update

2021-07-07 17:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +       ('CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES', 244);
thanks, will update. those are added recently.

2021-07-07 17:47 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +        var actual = jdbcTemplate.query(AssessedCustomFeeWrapper.SELECT_QUERY, AssessedCustomFeeWrapper.ROW_MAPPER);
we can't, since the `Id` we use for the domain classes are not unique/primary key

2021-07-07 17:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +        var actual = jdbcTemplate.query(AssessedCustomFeeWrapper.SELECT_QUERY, AssessedCustomFeeWrapper.ROW_MAPPER);
Just use findAll and filter in memory then

2021-07-07 18:11 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +        var actual = jdbcTemplate.query(AssessedCustomFeeWrapper.SELECT_QUERY, AssessedCustomFeeWrapper.ROW_MAPPER);
findAll was able to figure out how many rows, but in case the `Id` is the same for those rows, the entity objects are all the same.

2021-07-07 19:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +        var actual = jdbcTemplate.query(AssessedCustomFeeWrapper.SELECT_QUERY, AssessedCustomFeeWrapper.ROW_MAPPER);
I think you can forgo an ID class and just use the entity itself as the ID.

2021-07-07 20:46 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    minimum_amount            bigint not null default 0,
since we changed to also ingest '0' for minimum, add `not null` constraint.

2021-07-07 20:47 UTC, xin-hedera commented on docs/design/custom-fees.md
> +        "denominating_token_id": "0.0.1135",
add `demonimating_token_id` for fracitonal fee to make it explicit. it's implied that for franction_fee, the denominating token is all ways the token the fee is attached to

2021-07-07 20:48 UTC, xin-hedera commented on pom.xml
> +        <hedera-protobuf.version>8699be4</hedera-protobuf.version>
updated to the git commit hash with the new response codes

2021-07-07 20:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +create table if not exists assessed_custom_fee (
will update

2021-07-07 21:20 UTC, steven-sheehy approved these changes
LGTM

2021-07-07 22:59 UTC, Nana-EC approved these changes
LGTM

2021-07-07 23:17 UTC, ijungmann approved these changes

2021-07-07 23:21 UTC, merged