Custom fees REST api
hashgraph/hedera-mirror-node pull request #2247
Opened 2021-07-08 13:56 UTC by xin-hedera

**Description**:

This PR adds HTS custom fees support to the mirror node REST API.

- Add assessed custom fees to `/api/v1/transactions/:transactionId` endpoint
- Add custom fees schedule to`/api/v1/tokens/:tokenId` endpoint
- Add model/viewmodel for assessed custom fees and custom fees schedule
- Add integration domain support for assessed custom fees and custom fees schedule
- Update openapi spec
- Fix EntityId throwing exception with nullable `undefined` value
- Move `queryQuitly` to pool class prototype
- Add/Update integration tests

**Related issue(s)**:

Fixes #2199

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-07-08 14:05 UTC, xin-hedera commented on hedera-mirror-rest/stateproof.js
> +  const filters = await utils.buildAndValidateFilters(req.query);
```suggestion
  const filters = utils.buildAndValidateFilters(req.query);
```

2021-07-08 14:07 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +      ret = false;
```suggestion
      ret = false;
      break;
```

2021-07-08 15:35 UTC, xin-hedera commented on hedera-mirror-rest/server.js
> +      process.exit(1);
rethrow will cause `unhandled rejection` warning and the nodejs process hanging there.

2021-07-08 16:56 UTC, Nana-EC requested changes

2021-07-08 16:56 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +    tokenInfoTimestampQueryParam:
Why the need to duplicate `timestampQueryParam`?

2021-07-08 16:56 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        custom_fees:
Might be nice to break this out as it's own component and reference it here

2021-07-08 16:56 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +  const conditions = ['token_id = $1'];
Use Model so we can avoid rewriting column names be hand. 
```suggestion
  const conditions = [`${Token.TOKEN_ID = $1`];
```

2021-07-08 16:56 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    where ${NftTransfer.CONSENSUS_TIMESTAMP_FULL_NAME} = t.consensus_ns
```suggestion
    where ${NftTransfer.CONSENSUS_TIMESTAMP_FULL_NAME} = ${Transaction.CONSENSUS_NS_FULL_NAME}
```

2021-07-08 16:56 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    where ${AssessedCustomFee.CONSENSUS_TIMESTAMP_FULL_NAME} = t.consensus_ns
```suggestion
    where ${AssessedCustomFee.CONSENSUS_TIMESTAMP_FULL_NAME} = ${Transaction.CONSENSUS_NS_FULL_NAME}
```

2021-07-08 16:56 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +const getPoolClass = (mock = false) => {
Interesting, was separately working on something similar.
Decided instead to add a DbService class to contain all of this as well as setting the Pool/sqlConnection.
Just a suggestion if you think it's cleaner

2021-07-08 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    await addCustomFee({
sure

2021-07-08 16:58 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +    tokenInfoTimestampQueryParam:
because the tokenInfo endpoint does not accept the operator `gt`, `gte`, and `ne` for the timestamp parameter

2021-07-08 17:06 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const getPoolClass = (mock = false) => {
I'll leave it to you to improve 😃

2021-07-08 18:56 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +const getPoolClass = (mock = false) => {
Sounds good  😃

2021-07-08 19:57 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +    ) order by ${CustomFee.AMOUNT}, ${CustomFee.COLLECTOR_ACCOUNT_ID}, ${CustomFee.DENOMINATING_TOKEN_ID})
order the custom fees so integration tests can pass. it's interesting that the same data inserted in the same order, vanilla pg and timescaledb return them in opposite orders.

2021-07-08 20:08 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +    ) order by ${CustomFee.AMOUNT}, ${CustomFee.COLLECTOR_ACCOUNT_ID}, ${CustomFee.DENOMINATING_TOKEN_ID})
Probably cause of the extra index in the timescale case

2021-07-08 20:21 UTC, steven-sheehy requested changes

2021-07-08 20:21 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-info-05-custom-fees.spec.json
> +          "minimum": "79"
Should be numbers

2021-07-08 20:21 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-info-05-custom-fees.spec.json
> +            "numerator": "11"
should be numbers

2021-07-08 20:21 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-info-05-custom-fees.spec.json
> +          "amount": "12",
Number

2021-07-08 20:21 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: "0.1.2"
This string example doesn't match the EntityId's definition of being an object. We should change one or the other to match.

2021-07-08 22:23 UTC, steven-sheehy approved these changes
LGTM

2021-07-09 15:40 UTC, ijungmann approved these changes

2021-07-09 15:44 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +    tokenInfoTimestampQueryParam:
Gotcha

2021-07-09 15:46 UTC, Nana-EC approved these changes
LGTM

2021-07-09 15:48 UTC, merged