Custom fees acceptance tests
hashgraph/hedera-mirror-node pull request #2272
Opened 2021-07-13 22:20 UTC by xin-hedera

**Description**:

**Related issue(s)**:
This PR adds custom fees acceptance tests.

- Add domain classes for custom fees
- Support multiple tokens, token senders, and token recipients
- Add HTS scenarios for custom fees
- Fix transactions always paid by configured SDK client operator
- Remove unused token key
 
Fixes #2244

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-07-13 22:21 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +            transaction.setTransactionId(TransactionId.generate(payer.getAccountId()));
set payer and sign the transaction with the payer's key

2021-07-13 22:25 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> -        log.trace("Token creation PrivateKey : {}, PublicKey : {}", tokenKey, tokenPublicKey);
the generated key was not set in the token create transaction, so remove it as well as when doing kyc/(un)freeze.

2021-07-13 22:26 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> -            networkTransactionResponse = tokenClient.freeze(tokenId, accountId.getAccountId(), tokenKey);
as mentioned above, remove the unnecessary key. the signature by the key is not needed.

2021-07-14 00:12 UTC, Nana-EC requested changes
Looks good, some suggestions to simplify the example arguments

2021-07-14 00:12 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    Scenario Outline: Validate Base Token Flow with Custom Fees Schedule - Create, Associate, Fund, Transfer
Can you break the custom fees tests out into its own feature file?
`customfees/customfees.feature`

2021-07-14 00:12 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +            | 3000       | 200            | 100,0,;10,1,0;1/10,2,, | 200            | 100,0,0,;10,1,0,0;20,2,0,1 |
We should consider using [Table Types](https://github.com/cucumber/common/tree/main/datatable#table-types). This would make it easier to read but should make it easier to parse since you'd get a `Map<String, Map<String, Object>>`  and you can create a prop/domain class for the customFeeSchedule.
Feature methods would then be simplified too

2021-07-14 14:25 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    Scenario Outline: Validate Base Token Flow with Custom Fees Schedule - Create, Associate, Fund, Transfer
sure, will move the two scenarios to `hts/customfees/customfees.feature`

2021-07-14 15:01 UTC, steven-sheehy requested changes

2021-07-14 15:03 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public TransactionId executeTransaction(Transaction transaction, KeyList keyList, ExpandedAccountId payer) {
sure

2021-07-14 15:21 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +            | 3000       | 200            | 100,0,;10,1,0;1/10,2,, | 200            | 100,0,0,;10,1,0,0;20,2,0,1 |
I'll see how much effort it takes. I'd assume the tables are loaded at when the scenario runs, pretty much static, so we still need a converter at feature step runtime to resolve the account index / token index to the actual account/token strings.

2021-07-14 15:33 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorFraction.java
> +    private String denominator;
yes. will fix other fields which should be long but modeled as String.

2021-07-14 17:59 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +            | 3000       | 200            | 100,0,;10,1,0;1/10,2,, | 200            | 100,0,0,;10,1,0,0;20,2,0,1 |
Yeah, if it's an exhaustive amount of work let's create a ticket to capture that.
Hopefully a simple model for the customFee allows for auto conversion.
As is it's just hard to read and see what's being tested and how it might need to be modified in the future - it's pretty much CSV without the headers :)

2021-07-14 20:33 UTC, ijungmann requested changes
Looks good, only saw one small thing.

2021-07-14 20:33 UTC, ijungmann commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    @acceptance
An `@customfees` tag or something to that effect would help just to be able to pinpoint feature tests, I'm doing the same with `@nft`

2021-07-14 20:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        tokenCustomFees.clear();;
```suggestion
        tokenCustomFees.clear();
```

2021-07-14 20:43 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    @acceptance
the tag should have been added to the `customfees.feature` file during the refactoring.

2021-07-14 20:44 UTC, steven-sheehy approved these changes

2021-07-14 21:02 UTC, Nana-EC approved these changes
LGTM

2021-07-14 22:59 UTC, ijungmann commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    @acceptance
Ah, I see, added to the top of the file.  Yep, looks good then.

2021-07-14 23:00 UTC, ijungmann approved these changes

2021-07-14 23:07 UTC, steven-sheehy approved these changes

2021-07-15 00:02 UTC, merged