Upgrade GCP marketplace solution to v0.37
hashgraph/hedera-mirror-node pull request #2274
Opened 2021-07-13 23:50 UTC by Nana-EC

**Description**:
The current marketplace solution is behind on v0.27.
As such it lack Scheduled transactions and NFT support as well as many performance improvements.

- Modify chart test hooks to use Helm v2 backwards compatible format
- Update `secret-passwords.yaml ` to set appropriate password based on presence on use of pgpool
- Update GCP README with upgrade instructions and improved deletion steps
- Expose `db.owner.password` in `schema.yaml` 
- Expose `importer.db.username` in `schema.yaml` to allow for backwards compatibility when owner and importer were the same user
- Add `postgresql.serviceAccount.name` to `schema.yaml` to ensure service account is created by market place and not postgres chart

**Related issue(s)**:

Fixes #2246 

**Notes for reviewer**:
- `mpdev` verification works
- Successful ran v27, encountered HASHMismatch scenario and resolved it by upgrading to v0.37

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-07-14 14:46 UTC, steven-sheehy requested changes

2021-07-14 14:46 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +                verbs: [ 'get', 'list','watch', 'create', 'update' ]
Where did you come up with this list of roles? I don't see any roles defined in the postgres chart. You can probably omit the roles array.

2021-07-14 14:46 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +    description: The db user used by the importer to persist parsed stream files to the database. This is needed to support backwards compatability.
Won't people upgrading from 0.27 need to set this to mirror_node to make it work? If so, should we not default to that? Or we should provide sql instructions to tweak their schema.

2021-07-14 14:46 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-passwords.yaml
> +  HEDERA_MIRROR_IMPORTER_DB_HOST: "{{ tpl .Values.db.host . }}{{ if and .Values.postgresql.enabled (gt (.Values.postgresql.pgpool.replicaCount | int) 0) }}-postgres-pgpool{{ else if and .Values.postg
```suggestion
  HEDERA_MIRROR_IMPORTER_DB_HOST: "{{ tpl .Values.db.host . }}{{ if .Values.postgresql.enabled }}{{ ternary "-postgres-pgpool" "-postgres-postgresql" (gt (.Values.postgresql.pgpool.replicaCount | int) 0) }}{{ end }}"
```

2021-07-14 15:13 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +    description: The db user used by the importer to persist parsed stream files to the database. This is needed to support backwards compatability.
Yes people upgrading will. People not should use `mirror_importer`.
Initially I had no default so users would be forced to take the step to consider which.
I can update the title with `set to 'mirror_node' on upgrades`

2021-07-14 15:17 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-passwords.yaml
> +  HEDERA_MIRROR_IMPORTER_DB_HOST: "{{ tpl .Values.db.host . }}{{ if and .Values.postgresql.enabled (gt (.Values.postgresql.pgpool.replicaCount | int) 0) }}-postgres-pgpool{{ else if and .Values.postg
Thanks, meant to simplify. Will adopt and test this out

2021-07-14 16:11 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +                verbs: [ 'get', 'list','watch', 'create', 'update' ]
Removed roles array and verified functionality

2021-07-14 16:21 UTC, Nana-EC commented on charts/hedera-mirror/templates/secret-passwords.yaml
> +  HEDERA_MIRROR_IMPORTER_DB_HOST: "{{ tpl .Values.db.host . }}{{ if and .Values.postgresql.enabled (gt (.Values.postgresql.pgpool.replicaCount | int) 0) }}-postgres-pgpool{{ else if and .Values.postg
Updated

2021-07-14 16:42 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +    description: The db user used by the importer to persist parsed stream files to the database. This is needed to support backwards compatability.
Can do 1 of the following options
1. Set default to 'mirror_importer', call out in description (user has to hover over ? in marketplace to see)
2. Set default to 'mirror_importer', call out in title (immediately visible to user above text field)
3. Leave default empty to require setting, call out in description (user has to hover over ? in marketplace to see)
4. Leave default empty to require setting, call out in title (immediately visible to user above empty text field)

Call out will be the text 'Set to 'mirror_node' when upgrading from versions before v0.37.'

Note I just realized I have to do the exact same thing for the rest user as we went from 'mirror_api' to 'mirror_rest'

2021-07-14 17:13 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +    description: The db user used by the importer to persist parsed stream files to the database. This is needed to support backwards compatability.
Also I'm deprecating v0.27 so new installs post this release won't have to worry about the install coordination.
Due to this I'm leaning towards option 3 to avoid a click through without reading. We could also do option 4 if we want it front and center

2021-07-14 20:39 UTC, ijungmann reviewed
One small nit, otherwise I don't see anything concerning.

2021-07-14 20:39 UTC, ijungmann commented on charts/marketplace/gcp/README.md
> +4. Post successful install and confirmed importer operation, delete the leftover `data-${APP_NAME}-importer-0` persistent volume claim (Importer is no longer stateful)
nit: just an idea, `confirmed` threw me for a bit.
```suggestion
4. Post successful install and importer operation confirmation, delete the leftover `data-${APP_NAME}-importer-0` persistent volume claim (Importer is no longer stateful)
```

2021-07-15 03:58 UTC, Nana-EC commented on charts/marketplace/gcp/schema.yaml
> +    description: The db user used by the importer to persist parsed stream files to the database. This is needed to support backwards compatability.
Marketplace doesn't have a great upgrade flow from the UI. As such anyone upgrading is gonna have to touch the command line.
I've updated the README with the steps to modify the correct secret post install to unblock upgrades.
New installs won't see any difference

2021-07-15 03:59 UTC, Nana-EC commented on charts/marketplace/gcp/README.md
> +4. Post successful install and confirmed importer operation, delete the leftover `data-${APP_NAME}-importer-0` persistent volume claim (Importer is no longer stateful)
Updated

2021-07-15 14:30 UTC, xin-hedera approved these changes
LGTM

2021-07-15 15:22 UTC, ijungmann approved these changes

2021-07-15 15:37 UTC, steven-sheehy approved these changes

2021-07-15 15:52 UTC, merged