Add HTTPS support to Monitor API
hashgraph/hedera-mirror-node pull request #2279
Opened 2021-07-15 18:37 UTC by xin-hedera

**Description**:

This PR adds https support to the js monitor API

- Replace `servers[].ip` and `servers[].port` with `servers[].baseUrl` in config
- Add configurable retry on 429 HTTP response code

**Related issue(s)**:

Fixes #2243 

**Notes for reviewer**:

This is the log with retry when running w/ mainnet-public:

```
2021-07-15T13:31:32.676-0500 INFO Running tests
2021-07-15T13:31:32.755-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?order=asc&limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.756-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.758-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.759-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=1&order=desc, response status: 429, retry in 50ms
2021-07-15T13:31:32.759-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.760-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts?account.balance=gte%3A0&limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.760-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.761-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.761-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=1&order=desc, response status: 429, retry in 50ms
2021-07-15T13:31:32.762-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=10&type=credit, response status: 429, retry in 50ms
2021-07-15T13:31:32.815-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.9, response status: 429, retry in 50ms
2021-07-15T13:31:32.864-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts?account.balance=gte%3A0&limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.864-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.865-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?order=asc&limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.866-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=10&type=credit, response status: 429, retry in 50ms
2021-07-15T13:31:32.867-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.868-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=1&order=desc, response status: 429, retry in 50ms
2021-07-15T13:31:32.869-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:32.924-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts?account.id=0.0.9&type=credit&limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.965-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?order=asc&limit=10, response status: 429, retry in 55ms
2021-07-15T13:31:32.968-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=10&type=credit, response status: 429, retry in 52ms
2021-07-15T13:31:32.969-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=1, response status: 429, retry in 50ms
2021-07-15T13:31:32.979-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=1&order=desc, response status: 429, retry in 50ms
2021-07-15T13:31:32.985-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:33.078-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=10&type=credit, response status: 429, retry in 50ms
2021-07-15T13:31:33.081-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=1&order=desc, response status: 429, retry in 50ms
2021-07-15T13:31:33.083-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?limit=10, response status: 429, retry in 50ms
2021-07-15T13:31:33.243-0500 WARN url: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.319008, response status: 429, retry in 50ms
2021-07-15T13:31:33.349-0500 INFO Completed tests run for mainnet-public with 14/14 tests passed
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-07-15 19:30 UTC, steven-sheehy requested changes

2021-07-15 19:30 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/config/default.serverlist.json
> +    "max": 10,
Would prefer `maxAttempts` and `minBackoff` like we have these named in other components.

2021-07-15 20:12 UTC, Nana-EC requested changes
Looks good, one request to make testing and management easier

2021-07-15 20:44 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/config/default.serverlist.json
> +    "max": 10,
sure

2021-07-15 20:45 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> +    const secondsToWait = Number(response.headers.get('retry-after'));
will do that

2021-07-16 14:41 UTC, steven-sheehy approved these changes

2021-07-16 16:29 UTC, Nana-EC approved these changes
LGTM.
Notably, in my request for the `getBackOff` I was expecting a test file to verify varied inputs.
I realize now we don't have that on the `monitor_apis` side.
Adding one would be nice but with the push to move to java monitor I'm okay not putting much more effort since you've already verified operation E2E

2021-07-16 16:58 UTC, ijungmann approved these changes

2021-07-16 17:02 UTC, merged