Add NFT acceptance tests
hashgraph/hedera-mirror-node pull request #2284
Opened 2021-07-16 15:33 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

Add NFT acceptance tests
- Add new acceptance tests for NFT feature

**Related issue(s)**:

Fixes #2134 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-07-16 15:38 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Verify nft '{}' for token '{}' is returned by Mirror Node", serialNumber, tokenId);
Fix.

2021-07-16 15:38 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            tokenCreateTransaction.setDecimals(10).setInitialSupply(initialSupply);
Add newline

2021-07-16 15:39 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        log.debug("Updated token {}.", tokenId);
Better log

2021-07-16 15:40 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private final static int DEFAULT_MAX = 10_000;
Remove, not used

2021-07-16 15:41 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
>                  .addHbarTransfer(tokenTreasuryAccount.getAccountId(), hbarAmount.negated());
Can remove, only really need to prove NFT transfer.

2021-07-16 15:42 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            "(:?(.*) )?fund flow$")
Need a better descriptor for this, effectively verifying both transactions endpoint and NFT transactions endpoint.

2021-07-16 15:43 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Then("^the mirror node REST API should return status (.*) for nft (:?(.*) )?serial number (:?(.*) )?fund flow$")
Same here, this is verifying all endpoints for NFT, needs a clearer description.

2021-07-16 15:44 UTC, ijungmann commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    Scenario Outline: Validate Update Treasury NFT Flow - Create, Associate, Mint, Update Treasury
This test is temporarily a negative path test until services enables treasury updates for NFTs, not sure if we want to leave it so that we'll know to update it after or just remove it since we don't want to do a lot of negative path testing in here.

2021-07-16 17:07 UTC, Nana-EC requested changes
Looking good on 1st pass, some suggestions.
I see you have some of your own comments to will swing back after those commits

2021-07-16 17:07 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            "(:?(.*) )?fund flow$")
```suggestion
    @Then("^the mirror node REST APIs should return status (.*) for nft (:?(.*) )?serial number " +
            "(:?(.*) )?fund transaction flow$")
```
or
```suggestion
    @Then("^the mirror node REST APIs should return status (.*) for nft (:?(.*) )?serial number " +
            "(:?(.*) )?fund flow$")
```
or
```suggestion
    @Then("^the mirror node REST APIs should return status (.*) for nft (:?(.*) )?(:?(.*) )?transaction flow$")
```

2021-07-16 19:06 UTC, xin-hedera requested changes

2021-07-16 19:06 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertTrue(serialNumberFound);
```suggestion
        assertThat(mirrorTransaction.getNftTransfers())
                .map(MirrorNftTransfer::getSerialNumber)
                .containsExactly(serialNumber);
```

2021-07-16 20:37 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            tokenCreateTransaction.setDecimals(10).setInitialSupply(initialSupply);
Not necessarily, both FUNGIBLE and NON_FUNGIBLE can be either INFINITE or FINITE.  You bring up a good point that we should probably test both cases though, I just have it default everything to INFINITE for simplicity, but for completeness it would be good to ensure we can handle both.  I'm about to push a test to add that check.

2021-07-16 20:48 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Verify nft '{}' for token '{}' is returned by Mirror Node", serialNumber, tokenId);
Fixed.

2021-07-16 20:48 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            tokenCreateTransaction.setDecimals(10).setInitialSupply(initialSupply);
Added checks for that test.

2021-07-16 21:43 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private final static int DEFAULT_MAX = 10_000;
Done

2021-07-16 21:43 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        log.debug("Updated token {}.", tokenId);
Done

2021-07-16 21:44 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
>                  .addHbarTransfer(tokenTreasuryAccount.getAccountId(), hbarAmount.negated());
Done

2021-07-19 15:32 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        log.debug("Transferred serial numbers {} of token {} from {} to {}", serialNumbers, tokenId, sender, recipient);
I can differentiate it more, but it's `Transfer` vs `Transferred` to show before and after, similar to how regular token transfer does it.

2021-07-19 16:27 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/hts/hts.feature
> +    Scenario Outline: Validate Update Treasury NFT Flow - Create, Associate, Mint, Update Treasury
We should not have negative tests as we're not testing HAPI.

2021-07-19 16:31 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            "(:?(.*) )?fund flow$")
Good ideas, fixed both up based on these.

2021-07-19 16:31 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        NetworkTransactionResponse response = transferToken(tokenId, sender, recipient, 0, serialNumbers);
Done

2021-07-19 16:32 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        return callRestEndpoint("/tokens/{transactionId}/nfts/{serialNumber}/transactions",
Good catch, fixed.

2021-07-19 16:32 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        keyList.add(newTreasuryId.getPrivateKey());
Done

2021-07-19 16:32 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private final Map<TokenId, List<Long>> tokenSerialNumbers = new HashMap<>();
Added

2021-07-19 16:32 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void transferTokensToSender(int amount, Integer tokenIndex, Integer recipientIndex) {
Yep, not sure what that was about, reverted.

2021-07-19 16:33 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        TokenId tokenId = tokenIds.get(getIndexOrDefault(tokenIndex));
Fixed.

2021-07-19 16:33 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorNftTransfer.java
> +    private String serialNumber;
Fixed.

2021-07-19 16:33 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertNotNull(receipt.serials.get(0));
Done.

2021-07-19 16:33 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        verifyTransactions(status, Collections.emptyList());
Removed.

2021-07-19 16:34 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    }
Added back.

2021-07-19 16:34 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        verifyTransactions(status, Collections.emptyList());
Removed.

2021-07-19 16:34 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            maxAttemptsExpression = "#{@acceptanceTestProperties.maxRetries}")
Removed the retry from both.

2021-07-19 16:35 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertTrue(serialNumberFound);
Done, added an extra filter to check the token id as well, but much cleaner code now.

2021-07-19 17:30 UTC, Nana-EC requested changes
Looks good, some suggestions on TokenClient methods

2021-07-19 17:30 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                                                           long amount, List<Long> serialNumbers) {
I'd say overload instead of using if statement, it's more modular and avoid others having to pass in unused defaults.

Another option instead of overloading is just be explicit  in the naming of the 2 functions `getFungibleTokenTransferTransaction` and `getNonFungibleTokenTransferTransaction`

2021-07-19 17:30 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                                                           long amount, List<Long> serialNumbers) {
You can pull out the TransferTransaction into a `private getTransferTransaction()` if you wanna share that part

2021-07-19 17:30 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse burn(TokenId tokenId, long amount, long serialNumber) {
Similar thought here.
Make a `getTokenBurn(TokenId tokenId)` that returns a base `TokenBurnTransaction`
Then overload `burn()` for the particular scenario i.e. `burn(TokenId tokenId, long amount)` and `burn(TokenId tokenId, long serialNumber)`

2021-07-19 17:30 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse wipe(TokenId tokenId, long amount, ExpandedAccountId expandedAccountId,
Same comment on `wipe()` as I noted for `burn()`

2021-07-19 17:30 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        if (tokenType == TokenType.FUNGIBLE_COMMON) {
I'm similarly wondering if we should move the shared logic into a `getTokenCreateTransaction()` and pull this branch logic into separate `createFungibleToken(...)` and `createNonFungibleToken(...)` with each modifying the result of `getTokenCreateTransaction()`

2021-07-20 16:53 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> -                .setAutoRenewPeriod(Duration.ofSeconds(6_999_999L))
Nope, I think I did that when we were getting bugs about `AUTORENEW` from the sdk.  Added back.

2021-07-20 16:54 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                                                           long amount, List<Long> serialNumbers) {
Removed the overloading and did separate method names to make it clear.

2021-07-20 17:13 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                                                           long amount, List<Long> serialNumbers) {
Considering you mentioned something similar for burn and wipe, I put back the overloading, just removed this method.  Will do for the others as well.

2021-07-20 17:17 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse burn(TokenId tokenId, long amount, long serialNumber) {
I agree with the idea, but the two methods here would have the same signature and thus can't be overloaded.  I can give them separate names however and split them out.

2021-07-20 17:26 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse wipe(TokenId tokenId, long amount, ExpandedAccountId expandedAccountId,
Same here, have to create separate names as the signatures will be the same otherwise, but will do.

2021-07-20 17:40 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        if (tokenType == TokenType.FUNGIBLE_COMMON) {
That can be done, but these are also used by the `createAndAssociateToken` method in the `ScheduleFeature` which is supposed to be a bit more generic, so this if statement will move elsewhere to keep that, unless we want to break that up as well, but that seems excessive to me.

2021-07-20 17:41 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        if (tokenType == TokenType.FUNGIBLE_COMMON) {
Nevermind, it does make some sense to break those up too.

2021-07-20 18:00 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse burn(TokenId tokenId, long amount, long serialNumber) {
Done.

2021-07-20 18:00 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse wipe(TokenId tokenId, long amount, ExpandedAccountId expandedAccountId,
Done.

2021-07-20 18:04 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        if (tokenType == TokenType.FUNGIBLE_COMMON) {
I did some refactoring for this, let me know what you think.  It may need more cleaning, we have a lot of overloaded `createToken` methods to forgo certain parameters that makes this one a little messier.

2021-07-20 19:22 UTC, Nana-EC approved these changes
LGTM

2021-07-20 21:03 UTC, xin-hedera approved these changes

2021-07-20 21:17 UTC, steven-sheehy approved these changes

2021-07-21 04:05 UTC, merged