Improve AddressBookService flow support for multi fileData transactions in single record file
hashgraph/hedera-mirror-node pull request #2317
Opened 2021-07-23 20:28 UTC by Nana-EC

**Description**:
When new nodes are added to the address book the mirror node processes the transactions and updates the db with the new nodes.
This will often come through as a FileCreate/FileUpdate followed by 1 or more FileAppend transactions.
The byte contents of each fileData object are combined to create the new addressBook.

There seems to be a regression where FileData bytes for addressbook were not being saved immediately and were being added to the cache for bulk inserts.
For most transactions this is desired, however, for the addressBook case not saving it immediately means future transactions from the same record file do not have access to the need information.

- Update `EntityRecordItemListener` to save address book file data immediately 
- Update address book csvBackup and restore sqls
- Add tests to capture issue
- Update `AddresBookService.migrate()` logic to check for missing fileData after current addressBook

**Related issue(s)**:

Addresses #2316 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-07-26 18:28 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.addressBooks`          | true                    | Persist addressBook data to the database
added for consistency and testability

2021-07-26 20:50 UTC, steven-sheehy requested changes

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookService.java
> +import java.time.Instant;
nit: unused?

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            fileDataRepository.save(fileData);
Can merge the two address book if statements to one:
```suggestion
        if (addressBookService.isAddressBook(entityId)) {
            fileDataRepository.save(fileData);
            addressBookService.update(fileData);
        } else if (entityProperties.getPersist().isFiles() ||
```

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +        return addressBookServiceEndpointsMigration.isNewerThan(baselineVersion.getVersion());
This looks like it will skip it for v2 schema? It should run regardless of schema. Please add a test for this.

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +        log.info("Successfully migrated address book file data in {}. Latest addressBook is {}", stopwatch, addressBook);
The logs in this method seem to be redundant with logs in `AddressBookService.migrate()` and Flyway itself and can probably be removed.

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +import com.hedera.mirror.importer.parser.record.entity.EntityProperties;
Unused?

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                if (log.isTraceEnabled()) {
If statement is not needed as log message construction is not heavyweight.

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    .findAddressBooksAfter(currentAddressBook.getStartConsensusTimestamp(), 1);
Does this handle scenario where fileupdate occurs in RCD file T1, importer restarted, and fileappend in occurs in RCD file T2? At the time of this migration the file data will have an incomplete address book.

2021-07-26 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigrationTest.java
> +    private final EntityId addressBookEntityId102 = EntityId.of("0.0.102", EntityTypeEnum.FILE);
Use `AddressBookServiceImpl.ADDRESS_BOOK_10*_ENTITY_ID`

2021-07-26 20:53 UTC, steven-sheehy commented
Also some code smells

2021-07-27 05:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    .findAddressBooksAfter(currentAddressBook.getStartConsensusTimestamp(), 1);
In that case even though an applicable file_data row exists the migration will be attempted but will fail to create a new addressBook - which is expected.
When T2 is being processed it will see T1 and create the combined fileData for the new addressBook.
I believe this scenario is covered in a few tests already such as `appendCompleteFileAcrossFileIds()`.

2021-07-27 05:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookService.java
> +import java.time.Instant;
Removed

2021-07-27 05:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            fileDataRepository.save(fileData);
Merged

2021-07-27 05:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +        return addressBookServiceEndpointsMigration.isNewerThan(baselineVersion.getVersion());
It won't, I added tests - see `skipMigrationPreAddressBookService()`. 
Unfortunately, without more logic to handle version of schema we can't have this migration run regardless. The `addressBookRepository` will fail since newer properties exists that aren't in the db.
Also it seems flyway doesn't update the baseline will after everything is run

The migrate logic has a few opportunities to be run, so if the parsing is necessary it should get called. 
1. In this java migration, where version >= 1.37.1
2. In `AddressBookServiceImpl.getCurrent()` in case where `address_book` db is empty
3. In `AddressBookServiceImpl.update()` on every addressBook `file_data` call

On a new mirror node the baseline may be null. In which case the java migration would be skipped but the call to `AddressBookServiceImpl.getCurrent()` will kickoff migration.
Post a migration where baselIne is set the skipMigration logic will apply and it will only skip if the version is prior to 1.37.1. The reason being the data schema form the newer proto will fail when being persisted to the db.


I could do this or have it run of every run but catch exceptions on this migration to handle the schema mismatch.
Other ideas?

2021-07-27 05:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +        log.info("Successfully migrated address book file data in {}. Latest addressBook is {}", stopwatch, addressBook);
Nice to have so you're not looking at log timestamps to calculate how long each java migration took.
Moved to base class

2021-07-27 05:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +import com.hedera.mirror.importer.parser.record.entity.EntityProperties;
Removed

2021-07-27 05:42 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                if (log.isTraceEnabled()) {
Removed

2021-07-27 05:42 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigrationTest.java
> +    private final EntityId addressBookEntityId102 = EntityId.of("0.0.102", EntityTypeEnum.FILE);
Updated

2021-07-27 15:28 UTC, xin-hedera requested changes
looks good

2021-07-27 15:28 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigrationTest.java
> +import org.junit.jupiter.params.provider.CsvSource;
nit: reorder the imports

2021-07-27 15:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +        return addressBookServiceEndpointsMigration.isNewerThan(baselineVersion.getVersion());
I just was saying it should run regardless of schema (v1 or v2). Not that it should run regardless of flyway migration version. So looks like that is captured.

2021-07-27 15:54 UTC, steven-sheehy approved these changes
LGTM

2021-07-27 16:01 UTC, ijungmann approved these changes

2021-07-27 18:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                    .getStartConsensusTimestamp() - 1);
Sure
1. It's dynamic in that sense and the old logic should be preserved for a new mirror node. For the initial case the value logic still be > 0 as the initial addressBook has a startTimestamp of 1.
2. To clarify when there are addressBook file_data rows after the current addressBook then yes the logic will look for all the file_data rows from start consensus timestamp - 1. This won't include file_data rows for the current addressBook since the `parseHistoricAddressBooks` actually uses `fileDataRepository.findAddressBooksAfter(long consensusTimestamp, ...)`

Good point though, this made me consider another edge case scenario which I'll tackle on the next commit

2021-07-28 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
>          // starting from consensusTimeStamp = 0 retrieve pages of fileData entries for historic address books
Updated

2021-07-28 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigrationTest.java
> +import org.junit.jupiter.params.provider.CsvSource;
Weird IDE behavior. Fixed

2021-07-29 17:20 UTC, steven-sheehy requested changes

2021-07-29 17:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                List.of(TransactionTypeEnum.FILECREATE.getProtoId(), TransactionTypeEnum.FILEUPDATE.getProtoId())
This is basically to ensure that all incomplete address books that couldn't be processed by the migration on startup get processed on the next file append? But I don't understand why this check is necessary. It seems like it loads the same data that parseHistoricAddressBooks() will load and parseHistoricAddressBooks() will already properly handle all unprocessed file data regardless of whether it's a create, update, or append.

2021-07-29 17:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                List.of(TransactionTypeEnum.FILECREATE.getProtoId(), TransactionTypeEnum.FILEUPDATE.getProtoId())
I should add more logging. 
The previous commit resulted in the migrate() flow processing the new addressBook and rendering the `update()` flow useless.
I wanted to ensure each situation was handled intentionally and not merge the lines.
So migrate() does all file_data -> address_book. Whereas validateAndCompleteAddressBookList() will do file_data -> address_book for file data prior to the current fileData being processed.
So update() flows would verify a smaller subset whereas migrate on startup would get everything.
There's a bit of decoupling that could be done but I didn't want to increase the churn and risk by refactoring in this PR.

2021-07-29 17:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +            log.error("Error checking service endpoints: {}", ex);
Will update

2021-07-29 18:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/FileDataRepository.java
>      List<FileData> findAddressBooksAfter(long consensusTimestamp, long limit);
Updated

2021-07-29 18:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +            log.error("Error checking service endpoints: {}", ex);
Updated

2021-07-29 18:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                List.of(TransactionTypeEnum.FILECREATE.getProtoId(), TransactionTypeEnum.FILEUPDATE.getProtoId())
Got the context now.
The extra call to get latest file was to give us an early exit, but if the call is gonna be made we can just do it for the range and the empty list will be an equivalent early exit.
Verifying now

2021-07-29 18:37 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                List.of(TransactionTypeEnum.FILECREATE.getProtoId(), TransactionTypeEnum.FILEUPDATE.getProtoId())
Updated

2021-07-29 18:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +            log.info("Error checking service endpoints", ex);
Think this might still log a stacktrace.
```suggestion
            log.info("Error checking service endpoints: {}", ex.getMessage());
```

2021-07-29 19:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigration.java
> +            log.info("Error checking service endpoints", ex);
Fixed

2021-07-29 19:34 UTC, steven-sheehy approved these changes
LGTM

2021-07-29 19:57 UTC, ijungmann approved these changes

2021-08-02 13:40 UTC, xin-hedera approved these changes
LGTM

2021-08-02 14:36 UTC, merged