Remove data generator
hashgraph/hedera-mirror-node pull request #2387
Opened 2021-08-10 16:33 UTC by ijungmann

**Description**:
Remove data generator module and add test cases for TransactionSuppliers

* Remove the data generator module and all references to it.
* Move TransactionSuppliers and anything else needed by the monitor into the monitor module
* Add unit tests for the TransactionSuppliers

**Related issue(s)**:

Fixes #2312 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-08-10 16:37 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java
> +                () -> assertThat(actual).usingRecursiveComparison().isEqualTo(expected)
Do a pass for alphabetical order on checks and sets.

2021-08-10 16:37 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +        Hbar transferAmount = ONE_TINYBAR;
Remove

2021-08-10 16:38 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +    void createWithMinimumData() {
Should probably be `Minimal`, no `Minimum`

2021-08-10 16:59 UTC, ijungmann commented
Will address code smells

2021-08-10 17:40 UTC, steven-sheehy commented
> Merging #2387 (88d4072) into main (10cbbb0) will increase coverage by 7.44%.

92% coverage now. Nice!

2021-08-10 17:40 UTC, ijungmann commented
> > Merging #2387 ([88d4072](https://github.com/hashgraph/hedera-mirror-node/commit/88d407288dbc43835a10ea6dc2781efd195824a2)) into main ([10cbbb0](https://github.com/hashgraph/hedera-mirror-node/commit/10cbbb0ccd5fd512022d77bc07de83b07bd7a298)) will increase coverage by 7.44%.
> 
> 92% coverage now. Nice!

Yeah!  Much nicer number.

2021-08-10 19:56 UTC, Nana-EC requested changes
Seems there were merge issue with copyrights details.

2021-08-10 19:56 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/util/Utility.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
Fix year

2021-08-10 19:56 UTC, Nana-EC commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/AbstractTransactionSupplierTest.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
Copy right repeated. Should also be 2021

2021-08-10 21:46 UTC, steven-sheehy requested changes

2021-08-10 21:46 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +        );
I don't like creating a temporary object just do do equality on it. I'm also not a fan of `assertAll`. It would be simpler to do a single chaining assert to verify results:

```java
assertThat(actual)
    .returns(key, AccountCreateTransaction::getKey)
    .returns(ONE_TINYBAR, AccountCreateTransaction::getMaxTransactionFee)
...
```

You can chain non-equality assertions like contains using `satisfies(a -> assertThat(a.get...())` or using `extracting()` at the end.

2021-08-10 23:30 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/util/Utility.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
Fixed.  I've removed the setup I had to add this automatically as it had all sorts of issues so this doesn't crop up again.

2021-08-10 23:30 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/util/UtilityTest.java
> + * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
Fixed, and removed my setup for doing this automatically as it was causing other issues randomly.

2021-08-10 23:31 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/AbstractTransactionSupplierTest.java
> +
Sure, removed.

2021-08-11 00:43 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +        );
The thing I like about creating the temporary object and doing equality on it is it forces someone to set every field, it protects against future fields or some of the fields that aren't as explicit (like setting `adminKey` in a supplier also gets used for `submitKey`, `freezeKey`, etc.). The other thing I'm running into as I've tried to convert over, `TokenNftTransfer` is not a public class so I don't know of a great way to go field-by-field for that.

I do see the value in the chaining you mentioned, that can be done.

2021-08-11 14:28 UTC, xin-hedera requested changes

2021-08-11 14:28 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java
> +
nit: reorder imports

2021-08-11 14:28 UTC, xin-hedera commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getAccountMemo()).contains("Mirror node created test account"))
can set the expected object's `accountMemo` and `transactionMemo` to the strings directly and assert the objects equal here

2021-08-11 16:09 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +        );
That's fair, I did have a to do something different with `ScheduleCreate` for that reason, too many internal fields that I could not get a hold of to even set the `expected` and all of the extra fields you mentioned.  I'll work on swapping things over to just checking fields and will keep an eye out for other bugs.

2021-08-12 00:32 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +        );
2.0.11 of sdk was released with my fix for public class.

2021-08-17 22:05 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a).usingRecursiveComparison().isEqualTo(expected));
Removed this line.

2021-08-17 22:08 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getAccountMemo()).contains("Mirror node created test account"))
Removed the logic to compare against `expected` as per Steven's suggestion.  I also wanted to make sure that the memo contained the correct message, just setting the `expected` to what was in the `actual` and then doing an object equals means I just have to trust that the `actual` has what I want.

2021-08-17 22:08 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java
> +        );
Reworked the tests to use the chaining suggested.

2021-08-17 22:09 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java
> +
Fixed.

2021-08-18 05:41 UTC, steven-sheehy requested changes

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java
> +
Extra new line

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node deleted test account"));
For the last chain, you can use extract to make this cleaner.
```suggestion
                .extracting(AccountDeleteTransaction::getTransactionMemo)
                .contains("Mirror node deleted test account");
```

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node updated test account"))
We can remove the transaction memos in all suppliers since we override it in TransactionPublisher anyway. But we can defer this to avoid churn.

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +                        .returns(10L, map -> map.get(ACCOUNT_ID_2)));
```suggestion
                .hasSize(1)
                .extractingByKey(TOKEN_ID, InstanceOfAssertFactories.MAP)
                .containsEntry(ACCOUNT_ID, -10L)
                .containsEntry(ACCOUNT_ID_2, 10L);
```

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +                .returns(2, List::size)
```suggestion
                .hasSize(1)
                .extractingByKey(TOKEN_ID, InstanceOfAssertFactories.LIST)
                .hasSize(2)
```

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +                .satisfies(transferList -> assertThat(transferList.get(1))
```suggestion
                .last()
```

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +//
```suggestion
```

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getMessage().size()).isEqualTo(14));
```suggestion
                .extracting(TopicMessageSubmitTransaction::getMessage)
                .hasSize(14);
```

2021-08-18 05:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java
> +                        .toByteArray()))
Why wouldn't this work?
```suggestion
                .returns(ByteString.copyFromUtf8(message), TopicMessageSubmitTransaction::getMessage)
```

2021-08-18 15:36 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node deleted test account"));
I've had some issues with `extracting`, I get build errors on this unless I have `toString()` after extracting, it doesn't recognize `contains` otherwise.

2021-08-18 15:38 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java
> +
Removed.

2021-08-18 15:39 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node updated test account"))
I've removed the checks in the tests for this, I'll make a separate PR to address removing them from the `Suppliers` so that this PR doesn't continue to morph.

2021-08-18 15:45 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node deleted test account"));
I guess it assumes ObjectAssert unless you tell it otherwise:
```java
    .extracting(AccountDeleteTransaction::getTransactionMemo, InstanceOfAssertFactories.STRING)
    .contains("Mirror node deleted test account");
```

2021-08-18 17:25 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node deleted test account"));
Did that here and in other places where there is a memo (removed transaction memo checks)

2021-08-18 17:25 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +                        .returns(10L, map -> map.get(ACCOUNT_ID_2)));
Refactored all tests to follow this format

2021-08-18 17:25 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +                .returns(2, List::size)
Refactored all tests to follow this format

2021-08-18 17:26 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +                .satisfies(transferList -> assertThat(transferList.get(1))
Ended up extracting the fields into tuples and using `containsExactlyInAnyOrder`, but good to know about `last`

2021-08-18 17:27 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java
> +//
Removed.

2021-08-18 17:28 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java
> +                .satisfies(a -> assertThat(a.getMessage().size()).isEqualTo(14));
Had to add `toStringUtf8()` because AssertJ wanted it cast to a String, but otherwise this is done.

2021-08-18 17:28 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java
> +                        .toByteArray()))
Done.

2021-08-18 17:31 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/token/TokenMintTransactionSupplierTest.java
> +                .returns(14, metadataList -> metadataList.get(1).length);
Haven't found a good chain to check this yet, if I cast it to a list in the `extracting` it won't let me use `returns`, which then I didn't see a great way to extract the length of each the byte array cleanly.  Suggestions are welcome, this is the only test that hasn't been refactored.

2021-08-18 17:35 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/transaction/token/TokenUpdateTransactionSupplier.java
> -                .setExpirationTime(expirationTime)
`expirationTime` is coerced by the `autoRenewPeriod`, if `setExpirationTime` is called it also sets `autoRenewPeriod` to null, so setting both does nothing.  I'll have a separate PR to address this in a couple other spots I saw in other modules.

2021-08-18 19:28 UTC, steven-sheehy approved these changes
LGTM

2021-08-18 19:32 UTC, xin-hedera approved these changes
LGTM

2021-08-18 19:58 UTC, Nana-EC approved these changes
LGTM

2021-08-18 20:21 UTC, merged