Add missing default transfers to REST spec tests
hashgraph/hedera-mirror-node pull request #2400
Opened 2021-08-13 15:32 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
REST spec tests in many cases were missing default transfers to node and treasury that exist for every transaction.
This could result in incorrect results being returned that relied on the presence of crypto transfers for every transaction.

- Add default transfers to db if a spec specifies a transaction with no transfers
- Update specs to reflect default transfers

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-08-13 16:51 UTC, xin-hedera requested changes

2021-08-13 16:51 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-19-timestamp-no-transfers.spec.json
> +        "transfers": [
this spec is added as a regression test so transactions endpoint will also pick up transactions without crypto transfers. check PR log for details: 9a4121a03077747d0426aef1265dd42ee5ec54c2

2021-08-13 16:51 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions-18-specific-id-no-transfers.spec.json
> +        "transfers": [
same comment. check PR log for details: 9a4121a03077747d0426aef1265dd42ee5ec54c2

2021-08-13 16:51 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  if (transfers.length === 0 && payerAccountId) {
the better logic would be:

if there are no transfers and charged_tx_fee is not 0, add

1. a transfer of node fee X to the node if exists or the default node
2. a transfer of service fee Y to the treasury if exists or the default treasury

where X + Y = charged_tx_fee

2021-08-13 18:50 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-19-timestamp-no-transfers.spec.json
> +        "transfers": [
Sure, so in this case I can make the payer different from the accounts in the transfers.
There needs to be a transfer set though

2021-08-13 19:42 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  if (transfers.length === 0 && payerAccountId) {
Fair points.
Notably charged_tx_fee = NODE_FEE + NETWORK_FEE + SERVICE_FEE
This covers just node and network fees
Will adopt a modified form of your suggestion

2021-08-13 23:24 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-19-timestamp-no-transfers.spec.json
> +        "transfers": [
Fixed

2021-08-13 23:24 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions-18-specific-id-no-transfers.spec.json
> +        "transfers": [
Fixed

2021-08-13 23:24 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  if (transfers.length === 0 && payerAccountId) {
Applied your suggestion

2021-08-16 15:55 UTC, steven-sheehy approved these changes
LGTM

2021-08-16 16:51 UTC, xin-hedera approved these changes
LGTM

2021-08-16 17:55 UTC, merged