HIP-18 enhancement
hashgraph/hedera-mirror-node pull request #2419
Opened 2021-08-17 18:57 UTC by xin-hedera

**Description**:

This PR adds support for several HIP-18 enhancement.

- support effective payer accounts in assessed custom fee
- support netOfTransfers in fractional fee
- support royalty fee

**Related issue(s)**:

Fixes #2377
Fixes #2378 
Fixes #2379

**Notes for reviewer**:

protobuf response code changes:

```bash
$ git diff v0.16.0 v0.17.1 src/main/proto/ResponseCode.proto
diff --git a/src/main/proto/ResponseCode.proto b/src/main/proto/ResponseCode.proto
index ae05c3b..2c4f980 100644
--- a/src/main/proto/ResponseCode.proto
+++ b/src/main/proto/ResponseCode.proto
@@ -240,7 +240,7 @@ enum ResponseCodeEnum {
   BATCH_SIZE_LIMIT_EXCEEDED = 228; // Repeated operations count exceeds the limit
   INVALID_QUERY_RANGE = 229; // The range of data to be gathered is out of the set boundaries
   FRACTION_DIVIDES_BY_ZERO = 230; // A custom fractional fee set a denominator of zero
-  INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE = 231; // The transaction payer could not afford a custom fee
+  INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE = 231 [deprecated = true]; // The transaction payer could not afford a custom fee
   CUSTOM_FEES_LIST_TOO_LONG = 232; // More than 10 custom fees were specified
   INVALID_CUSTOM_FEE_COLLECTOR = 233; // Any of the feeCollector accounts for customFees is invalid
   INVALID_TOKEN_ID_IN_CUSTOM_FEES = 234; // Any of the token Ids in customFees is invalid
@@ -251,7 +251,7 @@ enum ResponseCodeEnum {
   CUSTOM_FEE_MUST_BE_POSITIVE = 239; // Only positive fees may be assessed at this time
   TOKEN_HAS_NO_FEE_SCHEDULE_KEY = 240; // Fee schedule key is not set on token
   CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE = 241; // A fractional custom fee exceeded the range of a 64-bit signed integer
-  INVALID_CUSTOM_FRACTIONAL_FEES_SUM = 242; // The sum of all custom fractional fees must be strictly less than 1
+  ROYALTY_FRACTION_CANNOT_EXCEED_ONE = 242; // A royalty cannot exceed the total fungible value exchanged for an NFT
   FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT = 243; // Each fractional custom fee must have its maximum_amount, if specified, at least its minimum_amount
   CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES = 244; // A fee schedule update tried to clear the custom fees from a token whose fee schedule was already empty
   CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON = 245; // Only tokens of type FUNGIBLE_COMMON can be used to as fee schedule denominations
@@ -268,4 +268,7 @@ enum ResponseCodeEnum {
   PAYER_ACCOUNT_DELETED = 256; // The payer account has been marked as deleted
   CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH = 257; // The reference chain of custom fees for a transferred token exceeded the maximum length of 2
   CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS = 258; // More than 20 balance adjustments were to satisfy a CryptoTransfer and its implied custom fee payments
+  INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE = 259; // The sender account in the token transfer transaction could not afford a custom fee
+  SERIAL_NUMBER_LIMIT_REACHED = 260; // Currently no more than 4,294,967,295 NFTs may be minted for a given unique token type
+  CUSTOM_ROYALTY_FEE_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE = 261; // Only tokens of type NON_FUNGIBLE_UNIQUE can have royalty fees
 }
```

Note: still have to update rest service openapi spec

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-08-17 19:03 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +      order by ${AssessedCustomFee.AMOUNT}, ${AssessedCustomFee.COLLECTOR_ACCOUNT_ID}, ${AssessedCustomFee.TOKEN_ID}
add order clause so the order of the entries will be the same for v1 and v2 schemas.

2021-08-17 19:04 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/assessedCustomFeeViewModel.js
> +      .filter((payer) => payer !== null)
prior to v0.17.1, the `effective_payer_account_id` in db is `null`, filter it.

2021-08-17 19:07 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/token-info-04-non-fungible-unique-token-types.spec.json
> +      "royalty_fees": []
this is indeed a bug: `nft` token type won't have `fractional_fees`

2021-08-17 20:47 UTC, Nana-EC requested changes
1st pass, moving onto OpenAPI with newly pushed commit

2021-08-17 20:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                } else {
Is this for backwards compatibility or can we not rely on there always being at least 1 effective payer in an AssessedCustomFee going forward?

2021-08-17 20:50 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                } else {
yes it's for backward compatibility. it has to also pass transaction records with assessed custom fee priori to 0.17.1, which will have a empty effective payer account id list.

2021-08-17 20:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private boolean parseFixedFee(CustomFee customFee, FixedFee fixedFee, EntityId tokenId) {
made the change to encapsulate the logic: the function `parseFixedFee` does the parsing and so it surely knows whether the fixed fee's denominating token is the attached token.

For the other two types of fees the answer to the question 'do you charge in the attached token' is rather obvious, so doesn't need to follow the pattern.

2021-08-17 20:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  }
NFTs must have decimals = 0 and initial_supply = 0 according to HAPI spec

2021-08-17 21:05 UTC, xin-hedera commented on docs/design/custom-fees.md
> +  "decimals": "1000",
```suggestion
  "decimals": "0",
```

2021-08-17 21:05 UTC, xin-hedera commented on docs/design/custom-fees.md
> +  "initial_supply": "1000000",
```suggestion
  "initial_supply": "0",
```

2021-08-17 21:57 UTC, steven-sheehy requested changes

2021-08-17 21:57 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    royalty_numerator         bigint,
We've been using amount/amount_denominator as the main amounts of the table. Perhaps we should use those for royalty numerator and denominator and add a fallback_fee bigint. This would be one less bigint overall. We should probably add an enum type to easily select which oneof it is, unless you think that's not worth it.

2021-08-17 21:57 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    effective_payer_account_id bigint,
This duplicates all info for each effective payer account. We should normalize this out into another table `assessed_custom_fee_payer` to reduce the duplication.

2021-08-17 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                } else {
This isn't needed with my suggestion to normalize into another table.

2021-08-17 22:07 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    effective_payer_account_id bigint,
that'll actually more duplication since that table will be the same as the new `assessed_custom_fee` table: only (amount, collector_account_id, consensus_timestamp, token_id) uniquely identifies one assessed custom fee in a single transaction paid by a list of payers to the same collector in the same denominating token (or hbar)...

2021-08-17 22:08 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    effective_payer_account_id bigint,
postgresql supports arrays, we can alternatively have such a single column `effective_payer_account_ids`

2021-08-17 22:11 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    royalty_numerator         bigint,
the choice is made so that for the fallback fee (type is also FixedFee) in royalty fee, we can use the same fields in domain class `CustomFee` as well as the `parseFixedFee` function..

2021-08-17 23:04 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    effective_payer_account_id bigint,
I like the array idea

2021-08-17 23:06 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    effective_payer_account_id bigint,
If we don't use the array, the idea would be to add a generated ID (UUID preferrably) as primary key to assessed_custom_fee and have a foreign key. Then the other table only needs foreign ID and payer account. We kind of need a primary key anyway as there's none now and distributed sqls need one.

2021-08-18 00:21 UTC, steven-sheehy commented on docs/design/custom-fees.md
> +    royalty_numerator         bigint,
Cleaner code when parsing is probably less important than reduced data size and having a better choice for primary key. But I think we'll probably have to rethink this table in the near future anyway and either normalize it into other tables per fee type or go back to the original JSON fields. So we can go with it as is for now.

2021-08-18 14:33 UTC, xin-hedera commented on docs/design/custom-fees.md
> +    effective_payer_account_id bigint,
changed to `bigint[]` array, had to workaround the entityid -> long conversion though.

2021-08-18 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AssessedCustomFee.java
> +    private List<Long> effectivePayerAccountIds = Collections.emptyList();
can't use `AccountIdConverter` with hibernate-types `ListArrayType`

2021-08-18 14:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/LongListToStringSerializer.java
> +            gen.writeString("{" + StringUtils.join(longs, ",") + "}");
the encoding to insert array to postgresql

2021-08-18 15:34 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                } else {
no more special handling for empty effective payer account ids list with the `effective_payer_account_ids bigint[]` db column change

2021-08-18 16:05 UTC, steven-sheehy requested changes

2021-08-18 16:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .collect(Collectors.toList());
Shouldn't we also pass these to `EntityListener.onEntityId()`?

2021-08-18 16:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    effective_payer_account_ids bigint[] not null,
Missing equivalent default?

2021-08-18 16:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AssessedCustomFee.java
> +    private static final AccountIdConverter CONVERTER = new AccountIdConverter();
sure

2021-08-18 16:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .collect(Collectors.toList());
yup thanks. will add it.

2021-08-18 16:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    effective_payer_account_ids bigint[] not null,
in v1 the default is also dropped since it's only there to set the default to an empty array for historical data.

for v2, the importer will always ingest non-null arrays since there's no historical data without the new column.

2021-08-18 16:30 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/LongListToStringSerializer.java
> +            gen.writeString("{" + StringUtils.join(longs, ",") + "}");
pubsub doesn't use the domain class `AssessedCustomFee` so it should be fine now. We can look at the issue later in case we change the format of pubsub messages to include the domain object.

2021-08-18 16:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .collect(Collectors.toList());
actually no, since these effective payers must also appear in the *transfer lists of the same transaction, so it's safe to not add them.

Can still add the call in case we prefer to make it explicit.

2021-08-18 16:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .collect(Collectors.toList());
How about an explicit comment so we don't wonder why in the future?

2021-08-18 17:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .collect(Collectors.toList());
sure

2021-08-18 17:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/LongListToStringSerializer.java
> +            gen.writeString("{" + StringUtils.join(longs, ",") + "}");
added a separate integration test for assessed custom fee pgcopy `AssessedCustomFeePgCopyTest.java`

2021-08-18 17:44 UTC, steven-sheehy approved these changes

2021-08-18 18:32 UTC, steven-sheehy approved these changes

2021-08-18 18:55 UTC, Nana-EC approved these changes
LGTM
Had some suggestions around CustomFee types and dependent logic but no need for additional code churn right now

2021-08-18 18:55 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private boolean parseFixedFee(CustomFee customFee, FixedFee fixedFee, EntityId tokenId) {
I see the change here. 
Not fully what I was suggesting as I was suggesting move the logic to the CustomFee domain class so that this method returned void. Then in the FIXED FEE case above you'd update the call flow.
Highlighted the example below.

```java
parseFixedFee(customFee, protoCustomFee.getFixedFee(), tokenId);
chargedInAttachedToken = customFee.isChargedInToken(tokenId);
```

In fact if we passed along the `protoCustomFee.getFeeCase()` to the CustomFee domain it would further simplify and centralize the `chargedInAttachedToken` logic.

No need to change it here though

2021-08-18 18:55 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/token-info-09-nft-custom-fees.spec.json
> +    "1234567899999999001, and a 4 custom fees schedule at 1234567899999999007. Without the timestamp filter, the query",
nit:
```suggestion
    "1234567899999999001, and a 5 custom fees schedule at 1234567899999999007. Without the timestamp filter, the query",
```

2021-08-18 18:55 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +  isFixedFee() {
nit: connected to my other comment if we passed along the type these checks would be simpler.
Although it would require persistence with an additional `type` column in `custom_fee table

2021-08-18 18:59 UTC, ijungmann approved these changes

2021-08-18 19:00 UTC, merged