Add missing token account association migration
hashgraph/hedera-mirror-node pull request #2424
Opened 2021-08-19 20:26 UTC by xin-hedera

**Description**:

This PR adds a db migration script to add the missing token account associations.

**Related issue(s)**:

Fixes #2356 
Fixes #2393 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-08-19 20:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +    execute procedure add_missing_token_account_association();
pg 9.6 syntax, newer pg versions added `execute function`

2021-08-19 20:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +    on account_balance_file
usually for `inserts`, it's recommended to add
`for each row`
so the function is run for each inserted row and inside the function the predefined `NEW` record is the inserted row.

However, `for each row` causes `AccountBalanceFileRepositoryTest.findLatest` to fail since in that test, three rows were batch inserted to `account_balance_file`, pg will
 1.  queue three invocations of the trigger function, one for each row 
 2. the first run of the function drops tables, the function itself, and the trigger

then when it's time to run the function the second time, pg fails to locate it.

The workaround here is: use the default `for each statement`, then in the function, I can't use `NEW` since with `for each statement`, `NEW` may be `null`.

2021-08-19 20:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +create trigger missing_token_account_trigger after insert
trigger runs synchronously along the triggering event. So this trigger is run right after the insert into account_balance_file statement issued in `AccountBalanceFileParser`

2021-08-19 23:46 UTC, Nana-EC requested changes
Some clarification requested

2021-08-19 23:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        case when t.kyc_key is null then 0
I think setting the state contains a few unintended edge cases.
If an accounts state is set to something other than the default case we may be setting this wrong
e.g. Account A is in good standing (Associated, unfrozen and kyc granted) when it's originally associated on network.
Later on the admin decides to freeze/revoke kyc for that account for some reason.
This migration would open it up by setting it to UNFROZEN & GRANTED.

2021-08-19 23:46 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        return null;
WHat's the significance here, that is why is it important?
Isn't it implicit that the account_balance_file insert after this migration would occur after the latest transaction  as of this migration running?

Wondering if the temp table and or calculation is needed.

2021-08-20 00:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        case when t.freeze_key is null then 0
yes. the freeze and kyc status are set the same way as for the initial token treasury

2021-08-20 00:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        case when t.kyc_key is null then 0
yes. This is some edge case we discussed in the context of the previous PR. The migration script is a best effort and unfortunately there is no way to accurately apply all the changes from the token's created timestamp to now. token freeze/unfreeze, kyc grant / revoke all relate to <token, account> pair / pairs of info, however in our transaction table, there is only one entityid.

2021-08-20 00:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        return null;
there is no guarantee that when importer is stopped and this new version is deployed that the first account balance file processed after the migration will have its consensus timestamp >= the last transaction's timestamp when the migration is run.

For example, when we stop the importer around 11:00 AM, that's most likely when a new account balance file is generated. It's very likely the importer stops amid processing the account balance file for timestamp 11:00AM and the transaction is cancelled.

Then the db state can end up with the last transaction's consensus timestamp at 11:00:01.

On the next run, the first account balance file to process will be before the last transaction's consensus timestamp, and we should not use it to add missing token account associations, because there may be token create transactions after the account balance file which are already processed using the old version importer.

2021-08-20 17:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        case when t.kyc_key is null then 0
Yeah. I also thought about this a bit more. If there was a Kyc or Freeze change then the table should contain the token_account. So there would be a conflict and no write would happen.
So it should be okay

2021-08-20 18:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        case when t.kyc_key is null then 0
There won't be an entry for those <token_id, account> in the table since we missed the initial association. all the following updates other than token associate will do nothing to the db table for that association per our upsert pgcopy logic.

I forgot what the logic was before the upsert optimization though.

2021-08-20 20:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddMissingTokenAccountAssociationMigrationTest.java
> +    private File undoSql;
Should be able to use `@Sql(executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD, scripts = "classpath:db/scripts/undo_v1.43.2.sql")`

2021-08-20 20:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +create trigger missing_token_account_trigger after insert
It only runs after the account_balance_file transaction commits, right?

2021-08-20 20:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddMissingTokenAccountAssociationMigrationTest.java
> +    private File undoSql;
as far as I can recall, the `@Sql` annotation on the child class will purge away every `@Sql` on the parent. There seems to be other tricks too which may make it bit complicated. So I'l rather go with `@AfterEach`

2021-08-20 20:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +create trigger missing_token_account_trigger after insert
It runs right after the `insert into account_balance_file` statement, and becomes part of the transaction.

2021-08-20 20:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +create trigger missing_token_account_trigger after insert
Ok, so if an error occurs during the migration it will rollback the balance file. Sounds good.

2021-08-20 20:31 UTC, steven-sheehy approved these changes
LGTM

2021-08-20 23:17 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.43.2__add_missing_token_account_association.sql
> +        case when t.kyc_key is null then 0
Correct.

2021-08-20 23:18 UTC, Nana-EC approved these changes
LGTM

2021-08-21 00:51 UTC, merged