Expose account memo and receiverSigRequired files in API response
hashgraph/hedera-mirror-node pull request #2460
Opened 2021-08-27 18:37 UTC by Nana-EC

**Description**:
`receiverSigRequired` value is missing for crypto account API responses since we currently don't persist it in create and update transactions.

- Add `receiverSigRequired` to `Entity` domain
- Update`CryptoCreateTransactionHandler` and `CryptoUpdateTransactionHandler` to persist `receiverSigRequired`
- Add migration to add nullable `receiver_sig_required` column to `entity` table
- Update `integrationDOmainOPs.js` with default `receiver_sig_required` column value
- Update `accounts.js` to expose `memo` and `receiver_sig_required` in response
- Update `openapi.yaml`

**Related issue(s)**:

Fixes #2428 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-08-28 00:21 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
>            type: boolean
Good catch. It's nullable until we fill in past then we can drop it in v2 sometime

2021-08-28 00:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        }
Earliest published version seems to have the wrapper.
https://github.com/hashgraph/hedera-protobufs-java/blob/0.3.0/src/main/proto/CryptoUpdate.proto

Might not hurt to have it in case though

2021-08-28 00:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        }
Added

2021-08-28 00:45 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +  );
Removed

2021-08-28 00:45 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
>            type: boolean
Added

2021-08-28 01:04 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        }
Adds a code smell - [java:S1874"@Deprecated" code should not be used](https://sonarcloud.io/organizations/hashgraph/rules?open=java%3AS1874&rule_key=java%3AS1874)
I can add a suppression to the pom

2021-08-28 01:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvRestoreTables.sql
> +\copy entity (auto_renew_account_id, auto_renew_period, created_timestamp, deleted, expiration_timestamp, id, key, memo, modified_timestamp, num, public_key, proxy_account_id, realm, receiver_sig_req
receiver_sig_required should add to the end of the columns because the way we copy it to the csv file makes a newly added column appear at the end

2021-08-28 01:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CleanupEntityMigrationTest.java
> +                        "submit_key, type from entity where id = ?",
can you just do
```sql
select * from entity where id = ?
```

2021-08-28 01:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        }
Deprecated warnings are very useful and we shouldn't suppress globally. Recommend using `@SuppressWarning("java:S1874")`.

2021-08-28 01:54 UTC, xin-hedera requested changes
looks good. some suggestions

2021-08-28 01:54 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
>    accRecord.balance.tokens = utils.parseTokenBalances(row.token_balances);
nit:

```suggestion
  accRecord.balance = {
    balance:  row.account_balance === null ? null : Number(row.account_balance),
    timestamp: row.consensus_timestamp === null ? null : utils.nsToSecNs(row.consensus_timestamp),
    tokens: utils.parseTokenBalances(row.token_balances),
  };
```

2021-08-28 01:54 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts-01-no-args.spec.json
> +        "receiver_sig_required": false
need one showing

```json
  "receiver_sig_required": null
```

2021-08-28 02:33 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
>    accRecord.balance.tokens = utils.parseTokenBalances(row.token_balances);
Updated

2021-08-28 02:33 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/accounts-01-no-args.spec.json
> +        "receiver_sig_required": false
Added for null and true

2021-08-28 02:33 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CleanupEntityMigrationTest.java
> +                        "submit_key, type from entity where id = ?",
True I can always just ignore the new column. Updated

2021-08-28 02:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvRestoreTables.sql
> +\copy entity (auto_renew_account_id, auto_renew_period, created_timestamp, deleted, expiration_timestamp, id, key, memo, modified_timestamp, num, public_key, proxy_account_id, realm, receiver_sig_req
Moved to end

2021-08-30 14:05 UTC, xin-hedera approved these changes
LGTM

2021-08-30 14:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        }
Not sure if you saw above. Would like to see it added so we don't introduce new code smells.

2021-08-30 15:11 UTC, xin-hedera approved these changes

2021-08-30 15:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        }
Added the `@SuppressWarnings`

2021-08-30 15:46 UTC, steven-sheehy approved these changes

2021-08-30 15:59 UTC, ijungmann approved these changes

2021-08-30 16:07 UTC, merged