Support automatic token associations
hashgraph/hedera-mirror-node pull request #2478
Opened 2021-08-31 14:50 UTC by xin-hedera

**Description**:

**Related issue(s)**:

This PR adds support of automatic token associations in hedera services 0.18.0

- ingest the automatic token associations list in transaction record
- support new field `max_automatic_token_associations` for crypto account in crypto create and crypto update transactions
- update `accounts` rest api to show `max_automatic_token_associations`
- simplify token account query in tokens by account rest api
- fix incorrect token account association in SqlEntityListener and token account upsert

Fixes #2420 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-08-31 14:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    private Long maxAutomaticTokenAssociations;
protobuf type of the field is `uint32`, and it's presented as `int` in java. In importer, the value from protobuf message is converted to a long by an unsigned conversion.

2021-08-31 15:04 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> -
these overloaded methods are too difficult to understand and set unrelated fields in the receipt for some transactions

2021-08-31 15:06 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> -    conditions.push('ta.associated is true');
`associated` will be always true. This also makes the query faster since it's now index-only scan

2021-08-31 15:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            tokenAccounts.put(tokenAccount.getId(), tokenAccount);
dissociate should remove the row from the db and associate should create a new row in the db, so both should purge the previous entry in the `tokenAccount` map.

2021-08-31 15:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListener.java
> +            tokenAccountRepository.findById(tokenAccount.getId()).ifPresent(tokenAccountRepository::delete);
only delete when the <token, account> row exists to avoid exception when no such record found in db

2021-08-31 15:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
this reduces cognitive complexity and makes sona happy

2021-08-31 16:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +delete from token_account where associated is false;
although we can also rely on the latest token balance snapshot to try to add associated <token, account> relationships back, for the same reason we discussed for the previous migration script, plus

- no way to figure out when the re-association happened
- no way to figure out the association's freeze & kyc status

I chose to leave it as is.

2021-08-31 21:58 UTC, ijungmann requested changes
Looks good, a couple little nits and questions.

2021-08-31 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +        //   where token_account_temp.associated is not null
Thank you for the detailed comment.  Minor nit:
```suggestion
        // where token_account_temp.associated is not null
```

2021-08-31 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +where type = 1;
This is a bigger effort than this ticket entails, but this seems like a good reason to have a separate `account` table at some point.

2021-08-31 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListener.java
> +        }
Is there a scenario where having the previous associations would be useful?  I think we're clear (the only one I can imagine is historical token balances, which is handled by the balance file), just want to make sure since this is a destructive operation.

2021-08-31 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                consensusTimestamp, true, tokenId);
I think there should be a comment (or maybe a mention in the method name) that makes it clear that `insertCustomFees` also returns the set of auto-associated accounts.

2021-08-31 21:58 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorV2Test.java
>  class TokenAccountUpsertQueryGeneratorV2Test extends TokenAccountUpsertQueryGeneratorTest {
Should this class just be removed and remove `EnabledIfV1` on `TokenAccountUpsertQueryGeneratorTest`?  We have a similar setup for `EntityUpsertQueryGeneratorTest`.

2021-08-31 22:12 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorV2Test.java
>  class TokenAccountUpsertQueryGeneratorV2Test extends TokenAccountUpsertQueryGeneratorTest {
we should keep it though for v2 it generates identical SQL statements.

This can prevent uncaught issues due to future changes which make v1 & v2 generate different SQL statements

2021-08-31 22:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListener.java
> +        }
I'm not sure about why we wanted to have the `assigned` column in our HTS design.

Put aside the `assigned` flag, the table really only represents the up-to-date state of the token account associations.

Thus we should just design after HAPI `message TokenRelationship`: 

```
message TokenRelationship {
    TokenID tokenId = 1; // The ID of the token
    string symbol = 2; // The Symbol of the token
    uint64 balance = 3; // For token of type FUNGIBLE_COMMON - the balance that the Account holds in the smallest denomination. For token of type NON_FUNGIBLE_UNIQUE - the number of NFTs held by the account
    TokenKycStatus kycStatus = 4; // The KYC status of the account (KycNotApplicable, Granted or Revoked). If the token does not have KYC key, KycNotApplicable is returned
    TokenFreezeStatus freezeStatus = 5; // The Freeze status of the account (FreezeNotApplicable, Frozen or Unfrozen). If the token does not have Freeze key, FreezeNotApplicable is returned
    uint32 decimals = 6; // Tokens divide into <tt>10<sup>decimals</sup></tt> pieces
}
```

2021-08-31 22:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +        //   where token_account_temp.associated is not null
it's done intentionally to emphasis the where clause

2021-08-31 22:26 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorV2Test.java
>  class TokenAccountUpsertQueryGeneratorV2Test extends TokenAccountUpsertQueryGeneratorTest {
checked the abstract generator logic again, yes agree we can remove the v2 test class and the `EnabledIfV1` annotation on this test class

2021-09-01 16:09 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +        //   where token_account_temp.associated is not null
Got it.  I guess an alternative could be capitalizing the `WHERE` in this case, but I'm fine with this.

2021-09-01 16:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListener.java
> +        }
Got it.  Just wanted to make sure, we've mentioned other tables should move to "no update, just insert the latest data" eventually, but it makes sense this table be an exception.

2021-09-01 22:21 UTC, steven-sheehy requested changes

2021-09-01 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityListener.java
>          }
Should add auto associated here with true overriding false and non-null overriding null.

2021-09-01 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .forEach(autoAssociatedAccounts::add);
I think it might be cleaner to remove this and the check in `insertAutomaticTokenAssociations()` and just let the token accounts merge.

2021-09-01 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = associatedTokenAccount(account, false, consensusTimestamp, freezeStatus,
I think these are still considered auto associated so this should be true. Another reason to use merging so that the record auto associated is last one in.

2021-09-01 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +       ('EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT', 263);
There's [now](https://github.com/hashgraph/hedera-protobufs/pull/86) a REQUESTED_NUM_AUTOMATIC_ASSOCIATIONS_EXCEEDS_ASSOCIATION_LIMIT=264

2021-09-01 22:21 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        max_automatic_token_associations:
We don't show token_account fields on any REST API to include the new `automatic_associations` field?

2021-09-01 22:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +        return String.format("where %s is not null and %s = %s and %s = %s",
Again, how does this handle kyc and freeze updates?

2021-09-01 23:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java
> +            int deleteCount = deleteItems(connection);
I see the value of supporting full token account relationship state snapshot. this is a bigger effort and should go into a separate PR.

Regardless of that, the privilege issue means for a <token, account> re-association we can't delete the row and instead should do `on conflict update` in its pgcopy upsert.

2021-09-01 23:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    .forEach(autoAssociatedAccounts::add);
the freeze status and kyc status of these token account associations are set differently than the associations in a crypto transfer transaction;

if we move it to  `insertAutomaticTokenAssociations()` we have to extract freeze key & kyc key of the new token in the token create transaction body again.

2021-09-01 23:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            tokenAccounts.put(tokenAccount.getId(), tokenAccount);
Sorry, meant in separate transactions same record file.

2021-09-01 23:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            TokenAccount tokenAccount = associatedTokenAccount(account, false, consensusTimestamp, freezeStatus,
we should keep it consistent with services state. In services, the auto enabled associations in token create transaction are not counted towards the automatic token associations quota.

Ideally, if we had exposed the flag in our `/tokens?account.id={account}`, it should tell how many automatic associations out of the max.

2021-09-01 23:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +        return String.format("where %s is not null and %s = %s and %s = %s",
the logic to handle kyc and freeze stay as is:

if freezeStatus / kycStatus is set to the new value if it's set, otherwise it stays the same.

This is the part of the corresponding update sql statement:

```
set freeze_status = coalesce(token_account_temp.freeze_status, token_account.freeze_status),
      kyc_status = coalesce(token_account_temp.kyc_status, token_account.kyc_status)
```

The initial freezeStatus / kycStatus is set in the insert sql which depends on the token's freezeDefault, freezeKey, and  kycKey in db.

2021-09-01 23:29 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        max_automatic_token_associations:
right...

do we want to show it? if so, I should add freeze status & kyc status too.

2021-09-02 00:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            tokenAccounts.put(tokenAccount.getId(), tokenAccount);
I see. For the series operations freeze -> dissociate -> associate in the same record file, the token account object will end up with created / modified timestamp set and associated = true. 

The insert sql in the TokenAccountUpsertGenetator will set freeze status and kyc status accordingly per the token’s freezeKey, freezeDefault, and kycKey.

2021-09-02 00:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java
> +    private Long maxAutomaticTokenAssociations;
sure I’ll talk to services to propose the change.

2021-09-03 16:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add primary key (account_id, token_id, modified_timestamp);
made the table insert only, so the primary key needs to be (account_id, token_id, modified_timestamp)

2021-09-03 16:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvRestoreTables.sql
> +\copy token_account (account_id, associated, created_timestamp, freeze_status, kyc_status, modified_timestamp, token_id, auto_associated) from token_account.csv csv;
`automatic_association`

2021-09-03 16:34 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
@ijungmann I'm not sure about if the assertion I added is correct. However, the test case apparently missed the `isEqualTo`

2021-09-03 16:34 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
@ijungmann I'm not sure about if the assertion I added is correct. However, the test case apparently missed the `isEqualTo`

2021-09-03 16:46 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        max_automatic_token_associations:
changed `/tokens?account.id={id}` to show `automatic_association`, `kyc_status`, and `freeze_status`.

The reverted the changes since this is not the correct endpoint to add such info.

I'd propose we implement a `/accounts/{accountId}/tokenRelationship` endpoint and deprecate `/tokens?account.id={id}`.

2021-09-03 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountKey.java
> +public class TokenAccountKey {
used in `SqlEntityListener`'s token account map to track the state of a <account, token> pair

2021-09-07 17:34 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        max_automatic_token_associations:
We don't need to add it, just wanted to confirm my suspicions.

2021-09-07 17:49 UTC, Nana-EC requested changes
Some suggestions

2021-09-07 17:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertAutomaticTokenAssociations(RecordItem recordItem) {
I think it would be better to have this method applicable to both. So there's a single central place for automatic token associations.

Maybe update this method to be
```suggestion
    private void insertAutomaticTokenAssociations(TokenAssociationsList tokenAssociationsList, TokenFreezeStatusEnum freezeStatus, TokenKycStatusEnum kycStatus) {
```

For create you can pass the status in, for others it will be null

2021-09-07 17:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private TokenAccount associatedTokenAccount(EntityId accountId, boolean automaticAssociation,
Same for above

2021-09-07 17:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +where type = 1;
Yep. 
I've pondered on this and this is another reason to consider it.

A suggested breakout might be
`entity - created_timestamp, modified_timestamp, id, key, type`
`account - created_timestamp, modified_timestamp, auto_renew_account_id, auto_renew_period, deleted, expiration_timestamp, account_id, memo, public_key, proxy_account_id ... etc`

2021-09-07 17:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add primary key (account_id, token_id, modified_timestamp);
To appropriately make this insert only wouldn't you have to parse the transactions table for all Associate, Dissociate, Freeze and Kyc related transactions.
Otherwise we'll end up with an aggregated form for entries prior to the time run of the migration.

2021-09-07 17:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +where type = 1;
Of course I think the breakout should be a separate ticket since it will be extremely invasive.
The plus side is it will bring performance benefits in API calls

2021-09-07 17:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add primary key (account_id, token_id, modified_timestamp);
that's right. The PR can only assure once it's deployed, the token account relationship changes from that time on have all the changes.

There isn't just the aggregation issue. The past data is wrong in case token associate, dissociate, then re-associate ever happened for a <token, account> relationship.

2021-09-07 17:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountKey.java
> +public class TokenAccountKey {
`TokenAccountId` now is the new primary key (account_id, token_id, modified_timestamp)

2021-09-07 18:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertAutomaticTokenAssociations(RecordItem recordItem) {
this doesn't really help.

the automatic token associations of a token create transaction is handled in `insertTokenCreate` because

- the freeze status & kyc status are set differently
- there is backwards compatibility that before 0.18.0 there is no automatic_token_associations in transaction record

The best if we want is re-parse the tokencreate transaction for its freeze key & kyc key in `insertAutomaticTokenAssociations`, still in `insertTokenCreate` we need to skip the prior-to-0.18.0 logic if the list is not empty

2021-09-08 15:09 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
Looks right to me.  @steven-sheehy added this check and the one below, so I'll let him confirm this.

2021-09-08 16:35 UTC, steven-sheehy requested changes

2021-09-08 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorTest.java
> +                "    coalesce(token_account_temp.automatic_association, last.automatic_association)," +
Since you're always setting automatic associations in `SqlEntityListener`, you can have a token associate in one record file set it to true and a freeze in another record file set it to false. But in that scenario it should stay true. However, if you get a token disassociate it is valid to go from true to false.

Perhaps consider allowing auto association to be nullable and not setting except for token associate/disassociate and when present in the record autoAssociations. As a special case, if `transactionRecord.hasAutomaticTokenAssociations()` is false we know that it doesn't support that field and can insert with false.

2021-09-08 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityListener.java
> +        newTokenAccount.setAutomaticAssociation(lastTokenAccount.getAutomaticAssociation());
I don't think an auto association can ever go from true to false. Since you're always setting automatic associations in `SqlEntityListener`, you can have a token associate within a record file set it to true and a freeze in the same record file override it to false.

2021-09-08 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add column automatic_association boolean not null default false;
We should have an update statement that sets to true if a tokenassociate transaction is present.

2021-09-08 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (recordItem.getRecord().getAutomaticTokenAssociationsCount() > 0) {
I'm not sure if there's a scenario where there's no auto associated on a token create per the main nodes but it's probably better to not differentiate between empty list and missing from protobuf. This is a more accurate check for pre-0.18 proto.

```suggestion
        if (recordItem.getRecord().transactionRecord.hasAutomaticTokenAssociations()) {
```

2021-09-08 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountKey.java
> +@Data
Map keys should be immutable.

```suggestion
@Value
```

2021-09-08 16:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    drop constraint token_account_pkey,
I think you meant the primary key? If so it's dropped and a new primary key is created.

As of v1.43.2 on testnet db, I only see the primary key, no other unique index.

2021-09-08 16:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    drop constraint token_account_pkey,
Nevermind, my local db must not be correct.

2021-09-08 16:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorTest.java
> +                "  where token_account_temp.created_timestamp is not null or last.created_timestamp is not null" +
for partial mirror nodes the new sql works in a similar way as the old upsert:

1. if the token account associate transaction was missed and there is no previous `associated = true` relationship (could be no previous relationship at all, or the last relationship in db has associated=false), all the updates in the lifespan of the relationship will be discarded
2. if the token account associate transaction was missed and there is a previous `associated=true`, unfortunately the updates will merge with the wrong previous state.

2021-09-08 16:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java
> +    private long modifiedTimestamp;
sure, will make the change!

2021-09-08 17:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
On main, it looks like it was missing a call to `nftMinimallyUpdated.setModifiedTimestamp(someUniqueNum)`.

On your branch, you shouldn't be ignoring accountId since it's part of the id and should be the same in both calls to `onNft()`.

2021-09-08 17:04 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorTest.java
> +                "    coalesce(token_account_temp.automatic_association, last.automatic_association)," +
`automatic_association` is immutable in a lifespan of a token-account relationship.

it's only set in `EntityRecordItemListener` when we handle a token associate, namely, in `TokenCreate` transaction due to auto enabled (borrow services term since it doesn't count towards the quota) associations, in `TokenAssociate` transactions, and in the `automatic_token_associations` list in `CryptoTransfer` transaction's transaction record. It's set to `false` for the first two and `true` for the last.

All other `TokenAccount` objects should have `automaticAssociation = null`.

In `SqlEntityListener`, it's always set from the last state when `createdTimestamp != null`. It won't flip from true to false or vice versa. In case the token associate with `automaticAssociation = true` is in a record file and a token freeze in the context of the same relationship is in the next, it should have `automaticAssociation = null`. Then in pgcopy, the insert statement will coalesce and fill the value from `last`.

2021-09-08 17:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add column automatic_association boolean not null default false;
Token account associations happened in token create are not automatic and there's no tokenassociate transaction.

2021-09-08 17:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
Looks like there's a bug in `AbstractEntityListener::mergeNft` that probably only manifests for `RepositoryEntityListener`. It should be changed to:

```java
        if (newNft.getAccountId() != null) { // only domains generated by NftTransfers should set account
            cachedNft.setAccountId(newNft.getAccountId());
        }
```

2021-09-08 17:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
Looks good.

2021-09-08 17:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (recordItem.getRecord().getAutomaticTokenAssociationsCount() > 0) {
it's a repeated field so it doesn't have a `has` method. If the field is missing, i.e., a pre-0.18 message, the default is an empty list created in the message constructor.

2021-09-08 18:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java
> +    private long modifiedTimestamp;
per the offline discussion, will defer the rename until the asynchronous db function of a previous migration is removed.

2021-09-08 18:30 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityListener.java
> +            return newTokenAccount;
this can happen when in the same record file, there are some token account relationship updates (ends with a dissociate) for a token account relationship before time T, followed by a token account associate for the same <account, token>. `lastTokenAccount` should then have `associated = false`, and `newTokenAccount` has `associated=true` and a non-null `createdTimestamp`.

The merge effectively becomes a replace.

2021-09-08 18:58 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
> +                .isEqualTo(nft);
thanks, made the change

2021-09-08 19:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add column automatic_association boolean not null default false;
Then we should also look by timestamp to see if it occurred for a tokencreate as well.

2021-09-08 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorTest.java
> +                "  where token_account_temp.created_timestamp is not null or last.created_timestamp is not null" +
I don't think discarding data is what we want to do. Partial data is better than no data.

2021-09-08 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.44.1__automatic_token_associations.sql
> +    add column automatic_association boolean not null default false;
looks like we are trapped in a check-egg problem?

there won't be token association deemed `automatic_associated = true` marked as `false` without this PR because importer will simply miss those associations at all.

2021-09-08 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGeneratorTest.java
> +                "  where token_account_temp.created_timestamp is not null or last.created_timestamp is not null" +
It'll end up with every entry for the <token, account> relationship in the same batch in a very disconnected way. basically each of such entry only reflects its own change.

For example, without the token associate, token freeze, token unfreeze, token kyc grant, token kyc revoke will insert the following rows

| associated | automatic_association | created_timestmap  | freeze_status | kyc_status   | modified_timestamp |
| ----------- | ----------- |----------- | ----------- |----------- |----------- |
| true      | false       | 10 | frozen | not_applicable | 10 |
| true      | false       | 11 | unfrozen | not_applicable | 11 |
| true      | false       | 12 | not_applicable | granted | 12 |
| true      | false       | 13 | not_applicable | revoked | 13 |

from the next batch on, the updates before the next token associate will merge with the row with `modified_timestamp = 13`

there doesn't seem to be a way to make it better and I don't think it's better than no data.

2021-09-08 21:39 UTC, steven-sheehy approved these changes
LGTM

2021-09-08 22:59 UTC, Nana-EC approved these changes

2021-09-08 23:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private TokenAccount associatedTokenAccount(EntityId accountId, boolean automaticAssociation,
You missed this btw

2021-09-09 00:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private TokenAccount associatedTokenAccount(EntityId accountId, boolean automaticAssociation,
it's updated in the last two or three commits

2021-09-09 14:17 UTC, ijungmann approved these changes
LGTM

2021-09-09 14:25 UTC, merged