Change dashboards to be Grafana Cloud compatible
hashgraph/hedera-mirror-node pull request #2485
Opened 2021-09-05 00:46 UTC by steven-sheehy

**Description**:
- Add cluster drop down to relevant dashboards with a default of all
- Add a datasource drop down to relevant dashboards
- Add an alerts graph by name over time to AlertManager graph
- Bump chart dependencies and image tags
- Change deprecated `policy/v1beta1` to `policy/v1`
- Fix chart install directions in README
- Fix monitor status logs not showing the same errors as metrics
- Fix various issues with the dashboards
- Remove `InhibitLogAlertWhenHighPublishErrors` alert

**Related issue(s)**:

Fixes #2427 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-09-05 22:27 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> -    - "--metrics.prometheus=true"
It's now enabled by default

2021-09-07 19:19 UTC, Nana-EC requested changes
Clarification requested on `helm upgrade` instruction update

2021-09-07 19:59 UTC, steven-sheehy commented on charts/README.md
> +$ helm upgrade --install "${RELEASE}" hedera/hedera-mirror
This change was intended. See the [complaint](https://github.com/hashgraph/hedera-mirror-node/issues/1907#issuecomment-910418409) from a community member.

Both approaches work, if you have the code checked out locally. The former does a local folder deploy while the latter does a deploy from the helm repo. Since we're adding the repo right before and not git cloning, we should use the latter.

2021-09-07 20:01 UTC, steven-sheehy commented on charts/README.md
> +$ helm upgrade --install "${RELEASE}" hedera/hedera-mirror
`hedera-mirror` is both the name of the chart and the name of the folder. It won't work for either approach if we just use `mirror`.

2021-09-07 20:27 UTC, Nana-EC commented on charts/README.md
> +$ helm upgrade --install "${RELEASE}" hedera/hedera-mirror
Sounds good

2021-09-07 20:28 UTC, Nana-EC approved these changes
LGTM

2021-09-07 21:14 UTC, ijungmann approved these changes

2021-09-07 22:08 UTC, merged