Handle inner ReadTimeoutException during acceptance tests
hashgraph/hedera-mirror-node pull request #2509
Opened 2021-09-08 05:28 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
Occasionally during runs of the acceptance tests the `@nft` tagged tests would fail with a `ReadTimeoutException`

Upon investigation this seems to be related to load on the server from multiple calls and should have presented itself for retry.

- Add logic to `shouldRetryRestCall()` to check if inner exception is `ReadTimeoutException`
- Add a simple crypto transfer test to `Account` flow
- Clean up `AccountClient` and `AccountFeature`
- Add `WebClientProperties` to capture configurable timeout properties for webClient.
- Update WebClient configuration removing deprecated items and swapping `TcpClient` for `HttpClient`
- Update `account.feature` threshold check value to be `10 Hbar`

**Related issue(s)**:

Fixes #2477 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-09-08 16:02 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    private boolean wiretap = false;
Should we add these to the README under the `Test Configuration` section?

2021-09-08 16:14 UTC, ijungmann requested changes
Looks good, a couple minor things.

2021-09-08 16:14 UTC, ijungmann commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
Considering this method only verifies the crypto transfer of a transaction, I think the method name should reflect that, unless the plan is to add more verification here at some point.  Something like `verifyMirrorAPICryptoTransferResponse`

2021-09-08 19:12 UTC, steven-sheehy requested changes

2021-09-08 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    private int connectionReadTimeoutMillis = 10000;
The initial connection setup is different than reading and writing over that connection during its lifetime. Even though they're all related to a connection, we generally just include `connect` in the name of the initial setup property and not the socket read/writes. Therefore these are normally called `connectionTimeout`, `readTimeout`, and `writeTimeout`.

2021-09-08 19:45 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
Can do

2021-09-08 19:46 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>          return t instanceof PrematureCloseException ||
Agreed, I considered this and had an initial iteration with this, but was borderline. 
With this it gets 2 votes so I can modify it to rerun on everything except 200's

2021-09-08 19:48 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    private int connectionReadTimeoutMillis = 10000;
Can do, added the connect to be explicit but if it's convention I can simplify it

2021-09-08 20:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    private int connectionReadTimeoutMillis = 10000;
Done

2021-09-08 20:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    private int connectionReadTimeoutMillis = 10000;
Updated

2021-09-08 20:44 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>          return t instanceof PrematureCloseException ||
Better yet non custom `WebClientResponseException` instance are of the 400 and 500's so we can retry on those.

2021-09-08 20:44 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
Updated

2021-09-08 21:54 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    private boolean wiretap = false;
Yes, will add

2021-09-09 14:19 UTC, ijungmann approved these changes
LGTM

2021-09-09 14:30 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    @DurationMin(millis = 5000L)
nit: better just use seconds for all DurationMin / Max

2021-09-09 14:35 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>          return t instanceof PrematureCloseException ||
Still looks brittle. I meant it should really retry all exception types, not just all `WebClientResponseException`. Basically, is there even a need for this method? Or we can remove all but allow it to be customized if we find out that we need to do only certain exceptions:

```java
    private Set<? extends Throwable> retryableExceptions = Collections.emptySet();

    protected boolean shouldRetryRestCall(Throwable t) {
        return restPollingProperties.getRetryableExceptions()
                .stream()
                .anyMatch(retry -> retry.isInstance(t) || retry.isInstance(Throwables.getRootCause(t)));
    }
```

2021-09-09 14:43 UTC, xin-hedera approved these changes
LGTM

2021-09-09 16:56 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>          return t instanceof PrematureCloseException ||
Sure, can do. Can set default of just Exception class

2021-09-09 17:05 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>          return t instanceof PrematureCloseException ||
Updated

2021-09-09 17:06 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/WebClientProperties.java
> +    @DurationMin(millis = 5000L)
Updated

2021-09-09 17:24 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/RestPollingProperties.java
> +    private Set<Class> retryableExceptions = Set.of(Exception.class);
```suggestion
    @NotNull
    private Set<Class> retryableExceptions = Set.of(Exception.class);
```

2021-09-09 17:27 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/RestPollingProperties.java
> +    private Set<Class> retryableExceptions = Set.of(Exception.class);
Added

2021-09-09 17:28 UTC, steven-sheehy approved these changes

2021-09-09 17:52 UTC, merged