Add revalidation logic to the monitor
hashgraph/hedera-mirror-node pull request #2510
Opened 2021-09-08 17:29 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Description**:
This PR adds logic to the monitor that occasionally revalidates the nodes in the network (without interrupting publishing), to ensure that it does not continue publishing to a node that is unhealthy.

* Add logic to revalidate nodes and replace the existing nodes list with the latest set of valid nodes
* Add a scheduled task to occasionally trigger the revalidation
* Add a config value to set how long to go in between validation times.
* Disable `TransactionReceiptQuery` by default, as it gets very noisy at high TPS

**Related issue(s)**:

Fixes #2444 

**Notes for reviewer**:
I have run the monitor (publishing side) multiple times with different configurations, this logic does not appear to negatively affect the TPS or cause any significant bump in errors.  This has not been tested against actual unhealthy nodes, but I did add some test logic to occasionally remove a node from the pool.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-09-08 17:30 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        log.fatal("Revalidating network");
Reduce

2021-09-08 17:34 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +@EnableScheduling
Not sure this is needed

2021-09-08 17:34 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +     * validate whether that transaction was received by the @mirror node APIs. Finally, metrics will be collected for
Fix

2021-09-08 17:38 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +            ".mirror.monitor.revalidationRate:600000}")
1. I'm struggling for a good name for this config value.  It also feels like it belongs under a `network` set along with the actual `network` value.
2. I set the initial delay to the same as the fixed delay, as we don't want this kicking off immediately, and I don't see a value in customizing the first time it runs.

2021-09-08 17:39 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +        scheduler.setPoolSize(2);
This could be set to 3 since there are 2 metrics loggers, but they have been working off of one thread up to this point.  I set this mainly because the metrics were not being logged while the revalidation was happening, and it causes some of the numbers to be a little weird.

2021-09-08 17:41 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        client.setMaxAttempts(15);
If the transaction does not have these set, it looks to the client, so this will handle both the request and the receipt.  Max attempts defaults to 10, set it a bit higher than the default.

2021-09-09 01:55 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +    @Scheduled(fixedDelayString = "${hedera.mirror.monitor.revalidationFrequency:600000}", initialDelayString = "$" +
We should just stick with one scheduling paradigm. Also by using reactor we don't need to expose the method. Can just make an internal class variable:

```java
Flux.interval(revalidationFrequency, revalidationFrequency)
  .subscribeOn(Schedulers.parallel())
  .subscribe(i -> revalidate())
```

Need to dispose of it in `close()`

2021-09-09 02:04 UTC, steven-sheehy commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidationFrequency`                   | 600000     | The amount of time (in milliseconds) between validations of the network.
We have `hedera.mirror.monitor.validateNodes` so we can just make it `hedera.mirror.monitor.validateFrequency` or maybe `hedera.mirror.monitor.validateNodesFrequency`. Should model as Duration so it can be `5m` here.

2021-09-09 02:05 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        clients.doOnNext(client -> {
Combine this logic with the aforementioned nodeValidator flux.

2021-09-09 16:41 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +    @Scheduled(fixedDelayString = "${hedera.mirror.monitor.revalidationFrequency:600000}", initialDelayString = "$" +
Good idea, didn't know about interval.  Swapped to that.

2021-09-09 16:42 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidationFrequency`                   | 600000     | The amount of time (in milliseconds) between validations of the network.
Yeah, now with the Flux I can do the duration.  I like `validateFrequency`, swapped to that.

2021-09-09 17:40 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +    @Scheduled(fixedDelayString = "${hedera.mirror.monitor.revalidationFrequency:600000}", initialDelayString = "$" +
I did this in a constructor since it's going to `mirrorProperties` to get the frequency.

2021-09-09 17:40 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        clients.doOnNext(client -> {
Combined.

2021-09-09 18:56 UTC, ijungmann commented
Trying to add a unit test for the revalidation, otherwise the code should be good for review.

2021-09-09 20:24 UTC, steven-sheehy requested changes

2021-09-09 20:24 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
>          validNodes.forEach(n -> nodeAccountIds.add(AccountId.fromString(n.getAccountId())));
I don't like having a period of time with zero nodeAccountIds. Let's change it to use `AtomicReference` so that doesn't occur. We can also get away with just using a regular `ArrayList` that way:

```suggestion
        List<AccountId> newNodeAccountIds = new ArrayList<>();
        validNodes.forEach(n -> newNodeAccountIds.add(AccountId.fromString(n.getAccountId())));
        nodeAccountIds.set(newNodeAccountIds);
```

2021-09-09 20:24 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                client.setNetwork(temp);
There's still a period in time where the list of node account ids can differ from what's in the client network. If that happens and nodeAccountIds has elements that aren't in the network, requests can fail briefly. But probably not worth adding synchronization around as it's okay if a few transactions fail here and there during revalidation.

2021-09-09 20:59 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/MonitorProperties.java
> +    private Duration validateFrequency = Duration.ofMinutes(5);
Fixed

2021-09-09 21:00 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +@EnableScheduling
Removed

2021-09-09 21:01 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
> +        scheduler.setPoolSize(2);
Looks alright without it after changing to Flux, removed this.

2021-09-09 21:05 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            if (nodeValidator != null) {
Sure, moved out.  I did make the Flux creation contingent on `publishProperties.isEnabled()` being true, because if nothing is ever published the clients don't get created in the first place from the initial validation.

2021-09-09 21:05 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
>          validNodes.forEach(n -> nodeAccountIds.add(AccountId.fromString(n.getAccountId())));
Good idea, implemented this.

2021-09-09 22:17 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                client.setNetwork(temp);
I agree, I can't think of a way to update both without halting every publishing thread first (which is what the TTL cache did), and that guarantees worse performance because it will stop regardless of if anything changes.  The errors should be pretty minor, so this seems like the better option.

2021-09-10 15:18 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                client.setNetwork(temp);
As discussed in chat, I redid the logic so that the client network is set at the beginning to have every node listed in the config, regardless of health, and is never updated.  Because we use `nodeAccountIds` to manually set the node for each transaction, we can just update that during revalidation.  This should fix the issue with trying to update two separate lists while transactions are running, and it should perform a little better, with fewer potential exceptions.

2021-09-10 15:40 UTC, steven-sheehy requested changes
Still needs some tests

2021-09-10 15:40 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    private Disposable nodeValidator;
```suggestion
    private final Optional<Disposable> nodeValidator;
```

2021-09-10 15:40 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        }
```suggestion
        nodeValidator.ifPresent(Disposable::dispose);
```

2021-09-10 15:40 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        log.info("Revalidating network");
This method is now redundant and can be replaced with a call to `validateNodes()`. Showing "revalidating" vs "validating" in the logs doesn't provide any value.

2021-09-10 16:53 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            throw new IllegalArgumentException("No valid nodes found");
nit: is `MissingResourceException` a better fit?

`Signals that a resource is missing.`

2021-09-10 17:18 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            throw new IllegalArgumentException("No valid nodes found");
No valid nodes can also signal invalid input as well

2021-09-10 17:27 UTC, xin-hedera requested changes

2021-09-10 17:27 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            List<AccountId> nodeAccountId = List.of(nodeAccountIds.get().get(nodeIndex));
should hold a reference to the list of nodes as local variable as between the two lines, nodeAccountIds.get() may return different lists.

2021-09-10 17:27 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .subscribe(i -> revalidateNodes());
nit: subscribe to the flux after the initial call of `validateNodes()` in `getClients()`

2021-09-10 19:22 UTC, Nana-EC reviewed
Single suggestion, will wait on resolutions to other requests

2021-09-10 19:22 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        client.setMinBackoff(Duration.ofMillis(500));
nit: make these configs

2021-09-13 15:50 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    }
Have to flip this logic, or else we will continue to try to publish to unhealthy nodes.

2021-09-13 22:11 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    private Disposable nodeValidator;
Made it optional.  Didn't make it final based on Xin's suggestion below about only subscribing after completing the initial validation.

2021-09-13 22:11 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        }
Done.

2021-09-13 22:11 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        log.info("Revalidating network");
Removed.

2021-09-13 22:11 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            List<AccountId> nodeAccountId = List.of(nodeAccountIds.get().get(nodeIndex));
Good idea, done.

2021-09-13 22:11 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .subscribe(i -> revalidateNodes());
Done.

2021-09-13 22:12 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .onErrorContinue((e, i) -> log.error("Exception revalidating nodes: {}", e))
Added an exception handler because the thrown exception was causing it to stop processing, this way if the network temporarily goes down it may be able to recover.

2021-09-13 23:12 UTC, xin-hedera requested changes

2021-09-14 00:42 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        client.setMinBackoff(Duration.ofMillis(500));
Done.

2021-09-14 00:49 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            List<AccountId> nodes = nodeAccountIds.get();
Fixed.

2021-09-14 04:23 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            throw new IllegalArgumentException("No valid nodes found");
I could see doing that for revalidation.  However, I think an exception should still be thrown on initial validation, probably in `getClients()`, as it has previously been.  Having no healthy nodes available on startup would make the `ExpressionConverter` fail.

2021-09-14 15:07 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            throw new IllegalArgumentException("No valid nodes found");
Done.

2021-09-14 17:56 UTC, steven-sheehy requested changes

2021-09-14 17:56 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        if (nodeAccountIds.get().isEmpty()) {
I think it makes sense to validate non-empty nodes both for initial and subsequent validations. So recommend moving to `validateNodes()`.

2021-09-14 17:56 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        Thread.sleep(1200L);
These sleeps indicate it could be a brittle test. And it looks like this test is failing in CI.

2021-09-14 21:11 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.maxBackoff`                 | 1000ms     | The maximum amount of time to wait in between attempts when trying to validate a node
Fixed.

2021-09-14 21:13 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.frequency`                  | 5m         | The amount of time between validations of the network.
That's fair.  Considering we're moving `validateNodes` into this as well, I like both of your suggestions, will go with `nodeValidation`.

2021-09-14 21:58 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        if (nodeAccountIds.get().isEmpty()) {
Sure.  @xin-hedera was saying throwing the exception might be excessive on the revalidation since the result is already logged, and to handle the error I just have the flux do another log anyway.  Do you think the exception throwing should be put back to, or do you suggest doing something else here?

2021-09-14 22:11 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        Thread.sleep(1200L);
You might try: setting the frequency even lower, use a CountdownLatch before moving on, or exposing the ability to set a `VirtualTimeScheduler` on the flux interval.

2021-09-14 22:25 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/MonitorProperties.java
> +    private RevalidationProperties revalidationProperties;
Note the field name should be named `nodeValidation` as it is also the config path.

2021-09-14 22:26 UTC, steven-sheehy commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.maxAttempts`                | 15         | The number of times the monitor should attempt to receive a healthy response from a node before marking it as unhealthy.
Note the new field name `enabled`

2021-09-14 22:52 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.maxAttempts`                | 15         | The number of times the monitor should attempt to receive a healthy response from a node before marking it as unhealthy.
Yep, added as `enabled` now

2021-09-14 22:53 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.frequency`                  | 5m         | The amount of time between validations of the network.
Renamed.

2021-09-14 22:53 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/MonitorProperties.java
> +    private RevalidationProperties revalidationProperties;
Fixed.

2021-09-14 22:53 UTC, ijungmann commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.maxAttempts`                | 15         | The number of times the monitor should attempt to receive a healthy response from a node before marking it as unhealthy.
Fixed.

2021-09-14 22:53 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    private final AtomicReference<List<AccountId>> nodeAccountIds = new AtomicReference<>();
Oops, fixed.

2021-09-14 22:53 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    public TransactionPublisher(MonitorProperties monitorProperties, PublishProperties publishProperties) {
Done.

2021-09-14 23:43 UTC, Nana-EC requested changes
Looking good. One clarification and one nit as part of the `validation` instead of `revalidation debate.

2021-09-14 23:43 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            nodeValidator = Optional.of(Flux.interval(validationProperties.getFrequency(),
This will mean on start up there won't be a a validation until the set frequency duration e.g. 5 mins
If not intended then you can reduce to a single param

2021-09-14 23:43 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .onErrorContinue((e, i) -> log.error("Exception revalidating nodes: {}", e))
```suggestion
                    .onErrorContinue((e, i) -> log.error("Exception validating nodes: {}", e))
```

2021-09-15 00:45 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        Thread.sleep(1200L);
Yeah, I've been looking for ways to make the tests better, trying the CountdownLatch at the moment.

2021-09-15 03:33 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            nodeValidator = Optional.of(Flux.interval(validationProperties.getFrequency(),
There's a manual call to `validateNodes()` a few lines before this.

2021-09-15 03:41 UTC, steven-sheehy commented on docs/configuration.md
> +`hedera.mirror.monitor.revalidation.maxAttempts`                | 20         | The number of times the monitor should attempt to receive a healthy response from a node before marking it as unhealthy.
Docs still reference old property path name and missing renaming of `validateNodes`.

2021-09-15 03:41 UTC, steven-sheehy commented on hedera-mirror-monitor/pom.xml
> +            <scope>test</scope>
Should be moved to test section at bottom of dependencies and sorted by group then artifact.

2021-09-15 03:41 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        if (nodeAccountIds.get().isEmpty()) {
Having zero nodes validate is an exceptional situation that is worthy of an error level log and a stacktrace. Printing `INFO 0 of 20 nodes validated` doesn't raise many flags until closer inspection. The exception in the publish flow will get caught and captured as metrics and never logged.

2021-09-15 05:20 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        Thread.sleep(1200L);
Will do cleanup/refactoring on test tomorrow, exposed the nodes list with a getter so that the test can actually see the effects of the validation and worked off of that.  I did get somewhere with CountdownLatches, but it was a lot of extra code for effectively the same result, stil had to expose the Flux or something to make it work.

2021-09-15 05:59 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            nodeValidator = Optional.of(Flux.interval(validationProperties.getFrequency(),
Ah, makes sense. Thus ensuring validation is done at least once. All set then

2021-09-15 16:28 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                            validationProperties.getFrequency())
nit: don't need separate initial delay and subsequent period, since they are the same
```suggestion
            nodeValidator = Optional.of(Flux.interval(validationProperties.getFrequency())
```

2021-09-15 16:41 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .onErrorContinue((e, i) -> log.error("Exception revalidating nodes: {}", e))
should remove the curly braces in the log message

2021-09-15 19:48 UTC, ijungmann commented on hedera-mirror-monitor/pom.xml
> +            <scope>test</scope>
Removed, wasn't working well with the test anyway.

2021-09-15 19:50 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                            validationProperties.getFrequency())
Ah, misread the documentation on that, yeah, I'll change it and make sure it still plays well.

2021-09-15 19:56 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .onErrorContinue((e, i) -> log.error("Exception revalidating nodes: {}", e))
Both fixed.

2021-09-15 19:56 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        if (nodeAccountIds.get().isEmpty()) {
Makes sense, put it back.

2021-09-15 19:57 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        Thread.sleep(1200L);
Wasn't able to get a test to work properly in CI relying on multithreading, the validation would always hang at some point.  Reworked to allow for manual revalidation, that seems to work.

2021-09-15 20:05 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                            validationProperties.getFrequency())
Done.

2021-09-15 21:17 UTC, steven-sheehy requested changes

2021-09-15 21:17 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        log.info("Executing first step for revalidate test");
Can remove logs in test

2021-09-15 21:17 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    private Optional<Disposable> nodeValidator = Optional.empty();
```suggestion
    private volatile Optional<Disposable> nodeValidator = Optional.empty();
```
Or we can swap it to use AtomicReference instead of Optional.

2021-09-15 21:17 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        monitorProperties.setNodeValidation(nodeValidationProperties);
These and the class member aren't really needed. You can just use `monitorProperties.getNodeValidation()` since it already creates an instance.

2021-09-15 22:06 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        assertThat(exceptionThrown).isTrue();
Ah, that's what I was trying to come up with earlier.  Added.

2021-09-15 22:06 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        log.info("Executing first step for revalidate test");
Removed.

2021-09-15 22:06 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    private Optional<Disposable> nodeValidator = Optional.empty();
Added

2021-09-15 22:07 UTC, ijungmann commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/TransactionPublisherTest.java
> +        monitorProperties.setNodeValidation(nodeValidationProperties);
Done, also did that for the `operatorProperties`

2021-09-15 22:16 UTC, steven-sheehy approved these changes
LGTM

2021-09-15 22:25 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +    private Optional<Disposable> nodeValidator = Optional.empty();
Swapped to `AtomicReference` to make Sonarcloud happy, no bugs now.

2021-09-15 22:29 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            nodeValidator = new AtomicReference<>(Flux.interval(validationProperties.getFrequency())
The way you're using it is not atomic. Need to make the field final then:

```suggestion
            nodeValidator.compareAndSet(null, Flux.interval(validationProperties.getFrequency())
```

2021-09-16 04:46 UTC, ijungmann commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +            nodeValidator = new AtomicReference<>(Flux.interval(validationProperties.getFrequency())
Got it, fixed.

2021-09-16 13:39 UTC, xin-hedera approved these changes
LGTM

2021-09-16 15:04 UTC, Nana-EC approved these changes
LGTM

2021-09-16 15:08 UTC, steven-sheehy approved these changes

2021-09-16 15:25 UTC, merged