Rosetta token balance reconciliation
hashgraph/hedera-mirror-node pull request #2517
Opened 2021-09-10 14:51 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #2504

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-09-10 20:30 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +										   (index + 1) latest_index
will fix the format

2021-09-10 20:34 UTC, xin-hedera commented on hedera-mirror-rosetta/test/db/db.go
> +func (d dbParams) toConfig() types.Db {
will add empty line between the functions

2021-09-13 19:03 UTC, Nana-EC reviewed
1st pass, still making my way through

2021-09-13 19:18 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +	selectSecondLatestWithIndex string = `select consensus_start,
yes it's required and we have to hide the latest block from being exposed. There is no place in rosetta we need the full info of the latest block other than its `index`.

2021-09-13 19:19 UTC, xin-hedera commented on hedera-mirror-rosetta/test/db/db.go
> +		Pool: types.Pool{
`gofmt` prefers it

2021-09-13 21:43 UTC, steven-sheehy requested changes

2021-09-13 21:43 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/persistence/block/block.go
>  type recordFile struct {
Why do we have two recordFile structs now? Is this one like a DTO of record files that's block specific? If so, we should name it something block related.

2021-09-13 21:43 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/services/base/base_service.go
> +func (c *BaseService) RetrieveSecondLatest() (*types.Block, *rTypes.Error) {
I'm not a really a fan of leaking first vs second block across all layers, especially if we have to change it back in the future. Perhaps we should rename it to something more generic like `RetrieveLatestValid()`? Or keep it as `RetrieveLatest` but just note the difference in its documentation.

2021-09-13 22:36 UTC, xin-hedera commented on hedera-mirror-rosetta/cmd/main.go
> +	loggedRouter := loggerMiddleware(router)
yes. meant to merge after your PR is merged. so will leave it as is for now

2021-09-13 22:38 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/base/base_service.go
> +func (c *BaseService) RetrieveSecondLatest() (*types.Block, *rTypes.Error) {
`RetrieveLatest` seems the better name, I'll change it back then.

2021-09-13 23:06 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +	selectSecondLatestWithIndex string = `select consensus_start,
Sounds good

2021-09-14 01:11 UTC, Nana-EC commented on hedera-mirror-rosetta/test/db/db.go
> +		Pool: types.Pool{
Defer to `gofmt` we shall

2021-09-14 14:49 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
>  type recordFile struct {
renamed it to `recordBlock`. `LatestIndex` is added to the struct so account service know if this is not the last block and then decide to show account balances or not.

2021-09-14 16:40 UTC, ijungmann reviewed
First pass, couple nits.

2021-09-14 16:40 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/repositories/block.go
> +	RetrieveGenesis() (*types.Block, *rTypes.Error)
I think these need to be flipped back after the rename.

2021-09-14 16:40 UTC, ijungmann commented on hedera-mirror-rosetta/test/mocks/repository/block_mock.go
>  }
Flip back

2021-09-14 17:46 UTC, Nana-EC requested changes
Looking good. A sql improvement suggestion

2021-09-14 18:07 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account/account.go
> +	selectDissociatedTokensAtTimestamp = `with latest as (
the trick is we can't have `ta.associated is false` there. it will select the latest row with `associated = false`

the sql statement is supposed to select the current account token relationship at time `t` then pick the ones with `associated = false`

2021-09-14 19:23 UTC, steven-sheehy submitted a review, later dismissed

2021-09-14 19:59 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/repositories/block.go
> +	RetrieveGenesis() (*types.Block, *rTypes.Error)
done

2021-09-14 19:59 UTC, xin-hedera commented on hedera-mirror-rosetta/test/mocks/repository/block_mock.go
>  }
done

2021-09-14 21:18 UTC, steven-sheehy approved these changes

2021-09-14 23:17 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/account/account.go
> +	selectDissociatedTokensAtTimestamp = `with latest as (
Understood

2021-09-14 23:18 UTC, Nana-EC approved these changes
LGTM

2021-09-14 23:42 UTC, merged