Add a Rosetta API chart
hashgraph/hedera-mirror-node pull request #2537
Opened 2021-09-13 16:59 UTC by steven-sheehy

**Description**:
- Add a Rosetta API Helm chart
- Add a Rosetta API Grafana dashboard
- Add a Prometheus metrics endpoint to Rosetta
- Add a tracing middleware so it uses standard log library and provides more details
- Add liveness and readiness endpoints to Rosetta
- Add log, alerts, metric alerts, and inhibit rules to Rosetta
- Bump Golang version to 1.17
- Change Rosetta docker image to [scratch](https://hub.docker.com/_/scratch) base image for improved security and reduced image size (~19MB)
- Change Rosetta logs to [logfmt](https://brandur.org/logfmt) for easier parsing by Loki
- Remove deprecated monitor REST API from ingress

**Related issue(s)**:

Fixes #1513 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-09-13 20:52 UTC, xin-hedera requested changes
looks good, some nits

2021-09-13 20:52 UTC, xin-hedera commented on hedera-mirror-rosetta/app/middleware/health.go
> +type HealthController struct {
```suggestion
type healthController struct {
```

don't have to export the struct

2021-09-13 20:52 UTC, xin-hedera commented on hedera-mirror-rosetta/app/middleware/metrics.go
> +type MetricsController struct {
```suggestion
type metricsController struct {
```

2021-09-13 20:52 UTC, xin-hedera commented on hedera-mirror-rosetta/app/middleware/trace.go
> +	return path == metricsPath || path == livenessPath || path == readinessPath
since it's a frequently called function, worth putting the known internal paths into a map then check `path` against it?

2021-09-13 23:00 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/middleware/trace.go
> +	return path == metricsPath || path == livenessPath || path == readinessPath
Sure, done

2021-09-13 23:01 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/middleware/health.go
> +type HealthController struct {
done

2021-09-13 23:01 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/middleware/metrics.go
> +type MetricsController struct {
Done

2021-09-13 23:05 UTC, Nana-EC approved these changes
LGTM

2021-09-13 23:24 UTC, xin-hedera approved these changes
LGTM

2021-09-14 00:56 UTC, ijungmann approved these changes

2021-09-14 01:14 UTC, merged