Rosetta integration tests
hashgraph/hedera-mirror-node pull request #2547
Opened 2021-09-15 19:07 UTC by Nana-EC

**Description**:
Rosetta module currently has unit tests and validations tests that run locally and in CI
However, these do not cover all E2E flows on a deployed instance and only hit the /block and /account/balance endpoints

- Add postman collection of API calls and tests against missing data API endpoints
- Add an environment configuration so support run against multiple envs
- Update `rosetta-api.yml` GitHub flow to run in CI

**Related issue(s)**:

Fixes #1518 

**Notes for reviewer**:
newman CLI is node based and requires installation

Remaining items
- [ ] Add documentation for runs
- [ ] Add test for `/account/coins`

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-09-16 16:23 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-09-16 21:13 UTC, steven-sheehy requested changes

2021-09-16 21:13 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/validation/postman/mirror-rosetta-api-tests.postman_collection.json
> +                  "    console.log(\"Set network_identifier: \" + pm.globals.get(\"network_identifier\"));",
`'Set network_identifier: [object Object]'`

Should fix or can probably just omit.

2021-09-16 22:50 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/postman/mirror-rosetta-api-tests.postman_collection.json
> +      "value": "https://previewnet.mirrornode.hedera.com",
Unintended change due to testing. Thought I had removed this

2021-09-16 22:52 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/postman/hedera_network.postman_environment.json
> +      "key": "network_domain",
It's very likely we'll expand this and need more variables so figured go with the structure to support that.
It's an easy change though so I can drop the file in favor of the single param

2021-09-17 07:11 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/postman/mirror-rosetta-api-tests.postman_collection.json
> +      "value": "https://previewnet.mirrornode.hedera.com",
Updated

2021-09-17 07:11 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/postman/hedera_network.postman_environment.json
> +      "key": "network_domain",
Removed config file

2021-09-17 07:11 UTC, Nana-EC commented on .github/workflows/rosetta-api.yml
> +        run: newman run mirror-rosetta-api-tests.postman_collection.json -e hedera_network.postman_environment.json
Updated

2021-09-17 07:11 UTC, Nana-EC commented on docs/rosetta-server.md
> +newman run mirror-rosetta-api-tests.postman_collection.json -e hedera_network.postman_environment.json
Updated

2021-09-17 07:11 UTC, Nana-EC commented on docs/rosetta-server.md
> +The Rosetta module supports integration tests that can be run against deployed instances
Updated

2021-09-17 07:11 UTC, Nana-EC commented on docs/rosetta-server.md
> +#### Install Postman newman CLI
Updated

2021-09-17 07:12 UTC, Nana-EC commented on docs/rosetta-server.md
> +#### Run Rosetta Postman API Tests
Updated

2021-09-17 07:12 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/postman/mirror-rosetta-api-tests.postman_collection.json
> +              "raw": "{{network_domain}}/network/list",
Updated

2021-09-17 07:13 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/postman/mirror-rosetta-api-tests.postman_collection.json
> +                  "    console.log(\"Set network_identifier: \" + pm.globals.get(\"network_identifier\"));",
Omitted

2021-09-17 13:24 UTC, xin-hedera commented on docs/rosetta-server.md
> +[Postmans](https://www.postman.com/) [Newman](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/)
should be `Postman's Newman` or simply `Postman Newman`?

2021-09-17 13:25 UTC, xin-hedera approved these changes
LGTM

2021-09-17 14:42 UTC, steven-sheehy requested changes

2021-09-17 14:42 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        run: newman run rosetta-api-postman.json --env-var base_url=http://localhost:5700
nit: Can omit since it's the default
```suggestion
        run: newman run rosetta-api-postman.json
```

2021-09-17 14:42 UTC, steven-sheehy commented on docs/rosetta-server.md
> +newman run rosetta-api-postman.json --env-var base_url=http://localhost:5700
Since the intended audience of this doc might be ops, better to show a public env url. Also good to show the public one since it varies significantly from the local one.
```suggestion
newman run rosetta-api-postman.json --env-var base_url=https://previewnet.mirrornode.hedera.com/rosetta
```

2021-09-17 14:42 UTC, steven-sheehy commented on docs/rosetta-server.md
> +- `base_url` - The network https domain url e.g. `http://localhost:5700`
```suggestion
- `base_url` - The base URL of the target Rosetta API e.g. `http://localhost:5700`
```

2021-09-17 16:19 UTC, Nana-EC commented on docs/rosetta-server.md
> +newman run rosetta-api-postman.json --env-var base_url=http://localhost:5700
Agreed.
Will update

2021-09-17 17:19 UTC, Nana-EC commented on docs/rosetta-server.md
> +- `base_url` - The network https domain url e.g. `http://localhost:5700`
Updated

2021-09-17 17:19 UTC, Nana-EC commented on docs/rosetta-server.md
> +newman run rosetta-api-postman.json --env-var base_url=http://localhost:5700
Updated

2021-09-17 17:19 UTC, Nana-EC commented on .github/workflows/rosetta-api.yml
> +        run: newman run rosetta-api-postman.json --env-var base_url=http://localhost:5700
Omitted

2021-09-17 17:35 UTC, steven-sheehy approved these changes
LGTM

2021-09-17 18:49 UTC, Nana-EC commented on docs/rosetta-server.md
> +[Postmans](https://www.postman.com/) [Newman](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/)
Fixed

2021-09-17 18:50 UTC, xin-hedera approved these changes
LGTM

2021-09-17 19:00 UTC, steven-sheehy approved these changes

2021-09-17 20:20 UTC, merged