Add memo to token endpoints
hashgraph/hedera-mirror-node pull request #2570
Opened 2021-09-22 04:19 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Description**:
Add token memo to `/tokens` and `/tokens/{id}`

* Add memo to token endpoints
* Update tests
* Update OpenApi, etc.

**Related issue(s)**:

Fixes #2522 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-09-22 04:20 UTC, ijungmann commented on V1.45.0__hip_24_pause_token.sql
> +-------------------
Remove, was stashed from other issue

2021-09-22 04:26 UTC, ijungmann commented
Do a second pass on openApi to make sure everything was updated.

2021-09-22 04:26 UTC, ijungmann commented
Question for tomorrow: should memo be part of NFT APIs?

2021-09-22 14:23 UTC, steven-sheehy requested changes

2021-09-22 16:17 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/token-info-01-no-args.spec.json
> +    "memo": "token.0.0.1135",
Sure, `deleted` makes sense, I will add it.  I don't see anything else particularly useful for `token`

2021-09-22 20:32 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/tokens-04-token-range.spec.json
> +        "memo": "token.0.7.25301",
Removed here, only added to token info now.

2021-09-23 15:17 UTC, xin-hedera approved these changes
LGTM

2021-09-23 16:07 UTC, steven-sheehy approved these changes
LGTM

2021-09-23 17:57 UTC, merged