Rosetta NFT support
hashgraph/hedera-mirror-node pull request #2574
Opened 2021-09-23 15:46 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #2250 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-09-23 16:27 UTC, xin-hedera commented on hedera-mirror-rosetta/app/errors/errors.go
> +	TransactionDecodeFailed        string = "Transaction DecodeEntityId failed"
will revert, changed accidentally

2021-09-23 16:28 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                                      serial_number <> -1
serial_number = -1 indicates a nft treasury update

2021-09-27 21:36 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                                      serial_number <> -1
will remove `serial_number <> -1` once the token dissociate of deleted token PR is merged

2021-09-29 22:43 UTC, steven-sheehy requested changes
This PR was way too big. The context change and the package refactoring should've been two separate PRs. Please ensure large, distinct changes are done separately in the future.

2021-09-29 22:43 UTC, steven-sheehy commented on hedera-mirror-rosetta/cmd/config.go
> -					Version:     "0.42.0-SNAPSHOT",
You'll need to update the replacer logic

2021-09-29 23:10 UTC, xin-hedera commented on hedera-mirror-rosetta/cmd/config.go
> +	if err := v.ReadConfig(bytes.NewBuffer([]byte(defaultConfig))); err != nil {
`SetConfigFile(envConfigFile)` doesn't read the file. the function `MergeInConfig` will discover / read external configuration files and apply it on top of the default

2021-09-29 23:12 UTC, xin-hedera commented on hedera-mirror-rosetta/cmd/default_config.go
> +const defaultConfig = `
just so when only default values are changed for instance bumping versions only this file is changed not the file with logic to read and parse the configuration.

2021-09-29 23:17 UTC, xin-hedera commented on hedera-mirror-rosetta/cmd/config.go
> -					Version:     "0.42.0-SNAPSHOT",
perhaps I have to remove this one `<![CDATA[(?<=\sVersion:     ")[0-9a-zA-Z.-]+]]>`. there is already a replacer can handle the new yaml format. Let me double check.

2021-10-01 16:28 UTC, ijungmann requested changes
I agree with the above comments, just a couple additional things.  Looks good.

2021-10-01 16:28 UTC, ijungmann commented on hedera-mirror-rosetta/app/persistence/account.go
> +	types2 "github.com/hashgraph/hedera-mirror-node/hedera-mirror-rosetta/types"
Could this be called `hederaTypes` (or `hTypes`), or something a little more descriptive than `types2`?  This pops up in a few files

2021-10-01 16:28 UTC, ijungmann commented on hedera-mirror-rosetta/app/persistence/token_test.go
> +var (
Test is commented out.

2021-10-01 17:47 UTC, steven-sheehy commented on hedera-mirror-rosetta/cmd/default_config.go
> +const defaultConfig = `
I don't think that provides value. If instead we can find a way for the version info to be stored separately and to be set by the build from the value in the pom.xml that would be ideal.

2021-10-01 19:10 UTC, xin-hedera commented on hedera-mirror-rosetta/cmd/default_config.go
> +const defaultConfig = `
that's possible.

to make sure we are on the same page, this is what we want:

1. remove version from the config yaml
2. update the build command in pom.xml to pass the version and save it in the executable
3. make the executable log the version on start up, and perhaps in addition, add a `-v` switch to just show the version and quit

2021-10-01 19:15 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	types2 "github.com/hashgraph/hedera-mirror-node/hedera-mirror-rosetta/types"
removed the `types2` alias. believe it's the goland IDE auto-format choice.

2021-10-01 19:23 UTC, steven-sheehy commented on hedera-mirror-rosetta/cmd/default_config.go
> +const defaultConfig = `
That's correct. Though I think in addition the Rosetta API serves the application version so it would need to show up there as well.

2021-10-01 21:45 UTC, xin-hedera commented on hedera-mirror-rosetta/main.go
> +	log.Infof("%s version %s, rosetta api version %s", moduleName, Version, rosettaConfig.ApiVersion)
logs the version

2021-10-01 21:47 UTC, xin-hedera commented on hedera-mirror-rosetta/pom.xml
> -                                <flag>-i</flag>
the `-i` flag is deprecated

2021-10-01 21:47 UTC, xin-hedera commented on hedera-mirror-rosetta/pom.xml
> +                            </ldFlags>
override the version

2021-10-04 21:10 UTC, steven-sheehy approved these changes
LGTM except some small tweaks

2021-10-04 21:13 UTC, ijungmann submitted a review, later dismissed

2021-10-05 16:04 UTC, xin-hedera commented on hedera-mirror-rosetta/app/config/types.go
> +	NodeVersion string `yaml:"nodeVersion"`
golang yaml default is snake case, so use tag to override it. not these tags are only used for test support

2021-10-05 16:23 UTC, xin-hedera commented on hedera-mirror-rosetta/app/config/config.go
> +		// only set config name and config paths when no config file env variable is set
added support for the logic in `configuration.md`

2021-10-05 16:28 UTC, steven-sheehy approved these changes

2021-10-05 16:41 UTC, ijungmann approved these changes

2021-10-05 17:38 UTC, merged