HIP 24 Token Pause Support (awaiting protobuf)
hashgraph/hedera-mirror-node pull request #2602
Opened 2021-09-27 03:19 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Description**:
Adds support for token pausing based on HIP 24

* Add support for token pause and unpause transactions
* Add pause key and status to Token
* Add pause key to REST API

**Related issue(s)**:

Fixes #2566 

**Notes for reviewer**:
Not complete, waiting for Protobuf to complete.

Open questions:
1. Does Token Pause have a default like freeze, kyc, or just always defaults to unpaused?
2. Should pause status be shown in token info API?

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-10-04 07:41 UTC, ijungmann commented
Questions: Should we show `pause_status` on Tokens List, and if so, should we also allow a filter on that?

2021-10-04 22:10 UTC, steven-sheehy requested changes

2021-10-04 22:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SupportDeletedTokenDissociateMigrationTest.java
> +//        tokenRepository.saveAll(List.of(ftClass1, ftClass2, nftClass1, nftClass2, nftClass3));
Remove

2021-10-04 22:10 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/token-info-06-historical-custom-fees.spec.json
> +    "pause_status": "UNPAUSED",
Would be good for one test to have PAUSED and another to have NOT_APPLICABLE.

2021-10-05 04:15 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.45.1__token_pause.sql
> +-- TODO verify these two
Removed.

2021-10-05 04:15 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SupportDeletedTokenDissociateMigrationTest.java
> +//        tokenRepository.saveAll(List.of(ftClass1, ftClass2, nftClass1, nftClass2, nftClass3));
Removed.

2021-10-05 04:42 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/token-info-06-historical-custom-fees.spec.json
> +    "pause_status": "UNPAUSED",
Sure, makes sense, added one for each.  Also added a `pause_key` example for coverage.

2021-10-05 04:47 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +    private String pauseKeyEd25519Hex;
Makes sense to me, removed.

2021-10-05 04:49 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    pause_status                 token_pause_status     not null default 'NOT_APPLICABLE',
Good catch, updated.

2021-10-05 13:47 UTC, xin-hedera requested changes

2021-10-05 13:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +        "kycKey", "kycKeyEd25519Hex", "pauseKey25519Hex", "pauseKey", "supplyKey", "supplyKeyEd25519Hex", "wipeKey",
no more `pauseKey25519Hex`

2021-10-05 13:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.45.1__token_pause.sql
> +-- Add support for automatic token associations
comment

2021-10-05 13:47 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                    pauseKey ? "has pauseKey" : "no pauseKey"
can you revert?

freezeDefault / freezeKey / kycKey are needed since the values will affect the defaults of a token relationship in case of an automatic association.

pauseKey doesn't have such effect so it shouldn't matter.

2021-10-05 13:47 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenUpsertQueryGeneratorTest.java
> +                "initial_supply, kyc_key, kyc_key_ed25519_hex, max_supply, modified_timestamp, name, pause_key, " +
can you reformat the sql query?

2021-10-05 13:47 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    pause_status: 'UNPAUSED',
shouldn't the default be `NOT_APPLICABLE` when there is no pause key?

2021-10-05 15:44 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    pause_status: 'UNPAUSED',
Yeah, it made sense when the hex key was still there.  Swapped to `NOT_APPLICABLE` and fixed tests accordingly.

2021-10-05 15:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
> +        "kycKey", "kycKeyEd25519Hex", "pauseKey25519Hex", "pauseKey", "supplyKey", "supplyKeyEd25519Hex", "wipeKey",
Removed.

2021-10-05 15:44 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.45.1__token_pause.sql
> +-- Add support for automatic token associations
Fixed.

2021-10-05 15:47 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                    pauseKey ? "has pauseKey" : "no pauseKey"
You're saying revert just the name here, or revert the entire `pause_key` test for this suite?

2021-10-05 15:52 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenUpsertQueryGeneratorTest.java
> +                "initial_supply, kyc_key, kyc_key_ed25519_hex, max_supply, modified_timestamp, name, pause_key, " +
Reformatted.

2021-10-05 16:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenPauseStatusEnum.java
> +package com.hedera.mirror.importer.domain;
missing license

2021-10-05 16:31 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                    pauseKey ? "has pauseKey" : "no pauseKey"
Removed the name addition here, though there will be two tests with the same name in this suite.

2021-10-05 16:31 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenPauseStatusEnum.java
> +package com.hedera.mirror.importer.domain;
Fixed.

2021-10-05 16:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.45.1__token_pause.sql
> +CREATE TYPE token_pause_status AS ENUM ('NOT_APPLICABLE', 'PAUSED', 'UNPAUSED');
nit: Use lower case

2021-10-05 16:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
>  CREATE TYPE token_type AS ENUM ('FUNGIBLE_COMMON', 'NON_FUNGIBLE_UNIQUE');
nit: Use lowercase for new and existing create type statements

2021-10-05 16:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    pause_key                    bytea,
Use an explicit `null`

2021-10-05 16:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.45.1__token_pause.sql
> +CREATE TYPE token_pause_status AS ENUM ('NOT_APPLICABLE', 'PAUSED', 'UNPAUSED');
Fixed.

2021-10-05 16:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
>  CREATE TYPE token_type AS ENUM ('FUNGIBLE_COMMON', 'NON_FUNGIBLE_UNIQUE');
Fixed for all 3.

2021-10-05 16:38 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +    pause_key                    bytea,
Added.

2021-10-05 16:41 UTC, steven-sheehy approved these changes
LGTM

2021-10-05 17:35 UTC, xin-hedera approved these changes
LGTM

2021-10-05 17:46 UTC, merged