Support token transfer in token dissociate transactions
hashgraph/hedera-mirror-node pull request #2603
Opened 2021-09-27 17:44 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #2548 
Fixes #2578 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-09-29 21:04 UTC, steven-sheehy reviewed
Looks good overall

2021-09-29 22:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenDissociateTransferUpsertQueryGenerator.java
> +            "where tdt.token_id not in (select distinct token_id from updated_nft)";
we don't know if a token is fungible or non-fungible in the `SqlEntityListener` path, unless we add a cache and read that info from `token` table in case of cache miss.

or we change token transfer PgCopy to do a join, that'll be much less performant.

2021-09-29 23:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenDissociateTransferUpsertQueryGenerator.java
> +            "where tdt.token_id not in (select distinct token_id from updated_nft)";
Ok

2021-09-30 15:24 UTC, steven-sheehy approved these changes
LGTM

2021-09-30 19:57 UTC, ijungmann requested changes
One nit, one question, otherwise all looks good.

2021-09-30 19:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityListener.java
> +                cachedToken.setTotalSupply(cachedToken.getTotalSupply() + newTotalSupply);
Could probably use a short comment here, `for token dissociate`.  I see the larger comment in the Record Item Listener, just a little mention here as well.

2021-09-30 19:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                  });
Could we just set the total supply to 0 once outside of this loop?

2021-09-30 20:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                  });
don't quite understand the question.

however, we can't set it to 0 since the 0 balance mentioned in the comment is in the scope of the individual account's token balance. the token's total balance should only reduce by the amount wiped from the individual account, it may or may not go to 0.

2021-09-30 20:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                  });
Ah, yes, got it.  I misunderstood `deleted tokens` as the Token itself was being deleted.

2021-09-30 20:24 UTC, ijungmann approved these changes

2021-09-30 21:10 UTC, steven-sheehy approved these changes

2021-09-30 22:05 UTC, merged