Upgrade rosetta PostgreSQL
hashgraph/hedera-mirror-node pull request #2643
Opened 2021-10-06 22:10 UTC by xin-hedera

**Description**:
This PR upgrades PostgreSQL to release 13 in the all-in-one rosetta docker image.

- Upgrade to PostgreSQL 13
- Use scram-sha-256 password encryption for PostgreSQL
- Tune some PostgreSQL parameters for better performance
- Make the Dockerfile "build from anywhere" per rosetta requirement
- Adjust importer JVM heap settings
- Run importer and rosetta in the docker image under separate non-root users

**Related issue(s)**:

Fixes #2576

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-10-07 16:07 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +          GIT_REF=${GITHUB_HEAD_REF:-$GITHUB_REF}
`GITHUB_HEAD_REF` is the source branch in case of a pull request, e.g., `refs/heads/upgrade-rosetta-postgresql`. if the workflow is not triggered by a PR, `GITHUB_HEAD_REF` is empty.

`GITHUB_REF` somehow points to a temporary ref created by github for PRs, e.g., `refs/pull/2643/merge`. in case of tags, it'll be `refs/tags/<tag>`.

`${GIT_REF#refs/*/}` removes the shortest prefix matching the pattern `refs/*/`

2021-10-07 21:32 UTC, steven-sheehy requested changes

2021-10-07 21:32 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +RUN git clone https://github.com/hashgraph/hedera-mirror-node && cd hedera-mirror-node && git checkout ${GIT_REF}
Do a shallow clone to improve performance
```suggestion
RUN git clone -–depth 1 https://github.com/hashgraph/hedera-mirror-node && cd hedera-mirror-node && git checkout ${GIT_REF}
```
```suggestion
RUN git clone https://github.com/hashgraph/hedera-mirror-node && cd hedera-mirror-node && git checkout ${GIT_REF}
```

2021-10-07 21:32 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
>  # It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
Remove outdated comments

2021-10-07 21:32 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +WORKDIR /app/build
I think it makes more sense for the app to not run out of a build directory
```suggestion
WORKDIR /app
```

2021-10-07 21:32 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
>  USER root
Supervisor needs to run as root?

2021-10-07 21:32 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/supervisord.conf
> +command=/usr/lib/postgresql/%(ENV_PG_VERSION)s/bin/postgres -c config_file=%(ENV_PGCONF)s/postgresql.conf
You shouldn't need to use an absolute path since you put this location on the $PATH. And the postgresql.conf should get read automatically if it's placed within the data directory. Maybe try putting it there in the standard location.

```suggestion
command=postgres
```

2021-10-07 21:32 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +ENV PGDATA="/var/lib/postgresql/${PG_VERSION}/main"
Does this need to be set? I think it's the default data dir already.

2021-10-07 22:24 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
>  USER root
Suppose so since it our configure have different processes under different users. Don’t expect users without such privilege to su. I’ll try it out though.

2021-10-07 22:33 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
> +WORKDIR /app/build
I can copy the entrypoint script and the supervisor config files out to /app then.

2021-10-07 22:58 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
>  # It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
it explains the `apt-key` step.

2021-10-07 23:00 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
>  # It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
Key hash no longer matches. And the comment is not even near the apt-key step now

2021-10-07 23:02 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/supervisord.conf
> +command=/usr/lib/postgresql/%(ENV_PG_VERSION)s/bin/postgres -c config_file=%(ENV_PGCONF)s/postgresql.conf
I meant instead of putting it in etc you can just put it data dir and it should automatically be picked up, avoiding manual configuration.

2021-10-07 23:15 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
>  # It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
not quite sure about the key hash not match part, since the key file in the comment and the apt-key command is there and this PR didn't change them. I can verify though.

2021-10-07 23:27 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
> +ENV PGDATA="/var/lib/postgresql/${PG_VERSION}/main"
`PGDATA` is not needed.

2021-10-08 00:19 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
>  # It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
Can disregard

2021-10-08 18:56 UTC, xin-hedera commented on hedera-mirror-rosetta/build/Dockerfile
>  USER root
nah, unprivileged processes can't seteuid

2021-10-08 19:07 UTC, xin-hedera commented on hedera-mirror-rosetta/build/supervisord.conf
> +command=/usr/lib/postgresql/%(ENV_PG_VERSION)s/bin/postgres -c config_file=%(ENV_PGCONF)s/postgresql.conf
moved the db configuration files to `/var/lib/postgresql/13/main` and symlink it back to where `/etc/init.d/postgresql` wants it to be.

now the command in supervisord.conf is simplified to just `postgres`.

p.s. $PATH set in the Dockerfile isn't available to non-root users with su for instance `su postgres`, but it's available with supervisor running the process under `postgres` user

2021-10-08 22:43 UTC, Nana-EC approved these changes
LGTM

2021-10-11 14:06 UTC, merged