Improve transaction REST API query performance
hashgraph/hedera-mirror-node pull request #2693
Opened 2021-10-15 02:11 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
The `transactions.js` logic utilizes heavy inner and outer queries to provide results to the `api/v1/accounts` and `api/v1/transactions` endpoints.
These queries are inefficient with multiple joins and don't lend themselves to distributed querying.

In #2273 it was possible to modify the queries to improve performance, this change adopts those improvements

- Move constant inner query from sub query to CTE, with support for an inner query when transactions need to be further filtered
- Break out transfer tables into separate CTEs to support distribution
- Utilize CTE result for base of transactions and avoid extra join on transaction table again

**Related issue(s)**:

Fixes #2676 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-10-18 20:05 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +const getCte = (cteName, select, from, join, where) => {
This function actually makes the SQL harder to read and doesn't reduce duplicate code (only reduces duplication of the words `as` and `select`). Would prefer a nicely formatted CTE clause string instead.

2021-10-18 21:04 UTC, ijungmann reviewed
Still looking at the transaction query, couple of nits to consider, looks good though.

2021-10-18 21:12 UTC, ijungmann commented on hedera-mirror-rest/model/tokenTransfer.js
> +  static tableAlias = 'ttr';
This is also currently the alias of `TransactionResult`, not sure we want to reuse.

2021-10-19 01:28 UTC, Nana-EC commented on hedera-mirror-rest/model/tokenTransfer.js
> +  static tableAlias = 'ttr';
Good catch. Will change to `tk_tr`

2021-10-19 01:32 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/tokens.test.js
> +        from nft_transfer nft_tr
Haven't seen us use `tr` for transaction, but I do see your point.
`tf` isn't bad either.
Let me see what the churn looks like

2021-10-19 01:37 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const getCte = (cteName, select, from, join, where) => {
Yeah, similar to what I did in transactions. Can do

2021-10-19 02:11 UTC, Nana-EC commented on hedera-mirror-rest/accounts.js
> +    with ab_tb as (
Updated

2021-10-19 02:11 UTC, Nana-EC commented on hedera-mirror-rest/tokens.js
> +const getCte = (cteName, select, from, join, where) => {
Updated

2021-10-19 02:11 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RemoveInvalidEntityMigrationTest.java
>                                  " (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
Updated

2021-10-19 02:11 UTC, Nana-EC commented on hedera-mirror-rest/model/tokenTransfer.js
> +  static tableAlias = 'ttr';
Updated

2021-10-19 03:19 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-10-19 14:02 UTC, xin-hedera requested changes
Just one small change.

2021-10-19 14:02 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +        .map((tokenBalance) => {
should do `Array.filter` first instead of filtering in `.map`, returning `null` on empty `token_id`, and then `.filter` the `null` from the `map` step

2021-10-19 15:21 UTC, ijungmann submitted a review, later dismissed

2021-10-19 16:57 UTC, steven-sheehy approved these changes

2021-10-19 17:19 UTC, merged