Optimize REST transactions API
hashgraph/hedera-mirror-node pull request #2763
Opened 2021-10-28 14:27 UTC by xin-hedera

**Description**:

This PR optimizes the REST API performance.

- Add an entityId cache
- Combine `EntityId.fromEncodedId` and `EntityId.fromString` as `EntityId.parse`
- Make response compression configurable and default to true
- Make `utils.randomString` async
- Lower default `limit.max` to 100 and add a `limit.default` of 25
- Remove unused `valid_start_ns` from `transaction` consensus_timestamp select statement

**Related issue(s)**:

Relates to #2718 

**Notes for reviewer**:

Set maxAge=1800 (30 minutes) and maxSize= 100, 000 for the entityId cache. Only writes set the expiry of cache entries, reads don't refresh the expiry so every entry stays in the cache for 30 minutes or shorter when the cache is full and the entry gets evicted.

Did a comparison against v0.42. Both with nodejs http response compression disabled, for an accounts query with `limit=100`. The QPS is 352/s v.s. 246/s or 43% higher. There are ~280 EntityId objects added to the cache. Note the overhead of v0.42 is not just 280 more EntityId parsing / encoding, because a single EntityId (mainly tokens) may appear multiple times in the response.

[memoizee](https://github.com/medikoo/memoizee) has an unpleasant performance issue that when the `max` (bound the cache size) is set, it performs no better than without a cache, even though the EntityId objects are cached and the cache is hit when it should. Without the `max` bound, it's ~10% slower than `mem` + `quick-lru` for our use case.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-11-01 13:33 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
> +    if (!isNullable) {
swapped

2021-11-01 21:17 UTC, steven-sheehy requested changes

2021-11-01 22:04 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return /^\d{1,4}$/.test(limit) && limit > 0 && limit <= responseLimit.max;
looks like the behavior isn't documented so I'll take the opportunity to cap the limit at max.

2021-11-01 22:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/entityId.test.js
> +describe('EntityId parse from entityId string', () => {
expect.toBe checks if two object references refer to the same object so added cache hit test cases using it.

2021-11-01 23:07 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return /^\d{1,4}$/.test(limit) && limit > 0 && limit <= responseLimit.max;
I'm surprised there's not a spec test that captured invalid high limit. Can we add one with limit=9999 that's successful? I'm also wondering if instead of a regex we should just check if `Number.isNaN()` and positive?

2021-11-02 15:24 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return /^\d{1,4}$/.test(limit) && limit > 0 && limit <= responseLimit.max;
relaxed the constraint and consolidated `isValidLimitNum` and `isValidNum` to `isValidPositiveInt`

2021-11-02 19:09 UTC, Nana-EC approved these changes
LGTM

2021-11-02 19:57 UTC, steven-sheehy requested changes

2021-11-02 19:57 UTC, steven-sheehy commented on hedera-mirror-rest/topicmessage.js
> +  if (!utils.isValidPositiveInt(seqNum)) {
Technically `serial_number` and `sequence_number` are bigints, not integers. So we should adjust this to `isPositiveNumber()` and adjust its definition to handle big numbers.

2021-11-02 19:57 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return `${num}` === `${parsed}` && parsed > 0 && Number.isSafeInteger(parsed);
Why do we convert both to string instead of just checking `NaN`?

2021-11-02 20:01 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return `${num}` === `${parsed}` && parsed > 0 && Number.isSafeInteger(parsed);
need to handle float

2021-11-02 20:17 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return `${num}` === `${parsed}` && parsed > 0 && Number.isSafeInteger(parsed);
Perhaps a precompiled regex would be the strictest. Something like:
`const numberRegex = new Regexp('^[1-9]\d*$');`

2021-11-02 20:34 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  if (!utils.isValidPositiveInt(seqNum)) {
then I'll add a separate `isValidPositiveLong`

2021-11-02 20:42 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.rest.response.includeHostInLink`          | false                   | Whether to include the hostname and port in the next link in the response                      |
I feel `response.includeHostInLink` is more concise: developers familiar with REST most likely get what it means without looking into the description. `response.includeHost` on the other side isn't straightforward.

2021-11-02 20:46 UTC, steven-sheehy commented on hedera-mirror-rest/topicmessage.js
> +  if (!utils.isValidPositiveInt(seqNum)) {
Why? Valid is redundant and we should also accept longs for limit since we just set it to max limit regardless

2021-11-02 20:59 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  if (!utils.isValidPositiveInt(seqNum)) {
then make it `isPositiveLong`, long tells us it's a fixed 64-bit signed number. Also we should use `long`, not `BigInt` since `BigInt` can support many more number of bits than `long`, and may perform worse than `long`.

2021-11-02 22:09 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const isPositiveLong = (num, allowZero = false) => {
optionally allows 0 since `account.balance` can be 0

2021-11-02 22:11 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    ret = parsed.greaterThan(responseLimit.max) ? responseLimit.max : parsed.toNumber();
convert `long` back to `number`, it's safe since we'll not have a `responseLimit.max` < than js Number.MAX_SAFE_INTEGER.

2021-11-02 22:22 UTC, ijungmann approved these changes
LGTM

2021-11-02 22:26 UTC, steven-sheehy approved these changes
LGTM

2021-11-03 01:38 UTC, merged