Add NotifyingTopicListener Support for Citus w PG 14
hashgraph/hedera-mirror-node pull request #2771
Opened 2021-10-29 23:14 UTC by Nana-EC

**Description**:
When updating to citus for the v2 database the `NotifyingTopicListener` flow seemed to not be supported when using PG 14 as the underlying db.
It continuously hit an exception unable to find the `ScramException.class` in the classPath.

Vertx provides integration with the [SASL SCRAM-SHA-256 authentication mechanism](https://vertx.io/docs/4.1.5/vertx-pg-client/java/#_sasl_scram_sha_256_authentication_mechanism) that we were not utilizing.

- Add `com.ongres.scram: client` dependency to grpc `pom.xml` to ensure `ScramException.class` can be found in the classPath
- Update `DbProperties` with `sslMode` config, default to `SslMode.DISABLE`
- Update `NotifyingTopicListener` with support to set SslMode configuration.
- Update `vertx` dependency to `4.2.0` from `4.1.5`
- Replace deprecated reactor `EmitterProcessor` with `Sinks.many().multicast()`
- Update citus images from `10.2.2-alpine` to `10.2.2-alpine`
- Replace deprecated jackson `PropertyNamingStrategy` with `PropertyNamingStrategies` in `NotifyingTopicListener` 

**Related issue(s)**:

Partially addresses #2769 

**Notes for reviewer**:
`SslMode` support remains off. Future tickets around production deployment will need to explore additional logic for other modes

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-10-30 22:01 UTC, steven-sheehy requested changes

2021-10-30 22:01 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +                .doOnTerminate(this::unListen);
unListen never gets called on last unsubscribe

2021-11-01 01:10 UTC, steven-sheehy commented
Based upon the description of #2769 it seems to fully address it but it's marked as partially addressing. What else is missing to fully address?

2021-11-01 15:36 UTC, xin-hedera requested changes

2021-11-01 15:36 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.grpc.db.sslMode`                             | DISABLE          | The ssl level of protection against Eavesdropping, Man-in-the-middle (MITM) and Impersonation on the db connection.
need to update `spring.datasource.url` in application.yml with `sslmode=` if we intend to add the configuration.

2021-11-05 04:58 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.grpc.db.sslMode`                             | DISABLE          | The ssl level of protection against Eavesdropping, Man-in-the-middle (MITM) and Impersonation on the db connection.
Added.

2021-11-05 04:58 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +                .doOnTerminate(this::unListen);
Moved up

2021-11-05 04:58 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +        Sinks.Many<Object> sink = Sinks.many().multicast().onBackpressureBuffer();
Reverted

2021-11-05 16:59 UTC, Nana-EC commented
> Based upon the description of #2769 it seems to fully address it but it's marked as partially addressing. What else is missing to fully address?

Updated, I was thinking around charts but those will be handled by other tickets.

2021-11-05 17:04 UTC, xin-hedera requested changes

2021-11-05 17:04 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +        Sinks.Many<String> sink = Sinks.many().multicast().onBackpressureBuffer();
```suggestion
        Sinks.Many<String> sink = Sinks.many().unicast().onBackpressureBuffer();
```

in the constructor, at the end, it's turned into a shared flux by `share()`, so `multicast()` here is redundant.

2021-11-05 21:46 UTC, steven-sheehy requested changes

2021-11-05 21:46 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +        sslMode: DISABLE
Shouldn't need to duplicate this as it should be inherited from the main application.yml

2021-11-05 21:46 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +                .doOnTerminate(this::unListen)
Still doesn't work. It should be in listen():

```java
return sink.asFlux().doFinally(s -> unlisten());
```

2021-11-05 21:48 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +        Sinks.Many<String> sink = Sinks.many().multicast().onBackpressureBuffer();
Agreed

2021-11-05 22:44 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +        Sinks.Many<String> sink = Sinks.many().multicast().onBackpressureBuffer();
Good call

2021-11-05 22:44 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/resources/config/application.yml
> +        sslMode: DISABLE
Removed

2021-11-05 22:44 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
> +                .doOnTerminate(this::unListen)
Updated

2021-11-05 22:49 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2021-11-08 20:29 UTC, steven-sheehy approved these changes

2021-11-08 21:07 UTC, xin-hedera approved these changes
LGTM

2021-11-08 21:10 UTC, merged