Fix entity query in accounts and balances REST apis
hashgraph/hedera-mirror-node pull request #2780
Opened 2021-11-01 13:32 UTC by xin-hedera

**Description**:

This PR fixes the entity query in accounts and balances REST apis.

- Union the results from `entity` table and `contract` table
- Add the public key index for the `contract` table

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-11-01 16:47 UTC, steven-sheehy requested changes

2021-11-01 16:47 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +const accountFields = ['max_automatic_token_associations', 'receiver_sig_required'];
For reuse and code simplification, we can create a union view to query both. To overcome the fact that you need fields that are only in entity, we can specify null for those fields in the contract query.

```sql
create or replace view entity_view as
select <common_columns>, max_automatic_token_associations, receiver_sig_required from entity
union all
select <common_columns>, null as max_automatic_token_associations, null as receiver_sig_required from contract
```

We'd have to maintain the view whenever adding or removing columns from those tables, but it would allow us to simplify the two queries here, the future query in #2770 and potentially simplify tests in the importer.

2021-11-01 22:13 UTC, steven-sheehy requested changes

2021-11-01 22:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.12__account_contract_view_and_index.sql
> +    max_automatic_token_associations,
For maximal reuse, let's add all the common fields

2021-11-01 22:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.12__account_contract_view_and_index.sql
> +    max_automatic_token_associations,
no problem!

2021-11-02 00:12 UTC, steven-sheehy approved these changes
LGTM

2021-11-02 14:45 UTC, Nana-EC approved these changes
LGTM

2021-11-02 15:01 UTC, merged