Contract acceptance tests
hashgraph/hedera-mirror-node pull request #2790
Opened 2021-11-03 04:05 UTC by Nana-EC

**Description**:
With the addition of contract REST APIs we can validate contracts end to end

**Related issue(s)**:

Fixes #2729 

**Notes for reviewer**:
Remaining tasks
- [ ] Fix call logic
- [ ] Verify call result
- [ ] Add contract REST API endpoint checks

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-11-04 16:41 UTC, Nana-EC reviewed
Self feedback

2021-11-04 16:50 UTC, steven-sheehy requested changes
Still working my through it. Some partial feedback.

2021-11-04 16:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +                CompiledSolidityArtifact compiledMirrorNodeArtifact = mapper.readValue(
I don't see the purpose of the `CompiledSolidityArtifact` object and its corresponding JSON files since we're only extracting the bytecode from it. To reduce maintenance burden and simplify things can't we just store the sol file and a corresponding bin file with the bytecode like how services does?

2021-11-04 16:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    constructor() {}
We need to also test a payable constructor somewhere so we can test contract create with an initial balance.

2021-11-04 16:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    receive() external payable {}
We should emit a child event

2021-11-04 16:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    event ParentActivityLog(string message);
Event should include some topics:
```suggestion
    event Transfer(address indexed _from, address indexed _to, uint64 amount);
```

2021-11-04 17:57 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +                CompiledSolidityArtifact compiledMirrorNodeArtifact = mapper.readValue(
I wouldn't recommend that for the development and maintenance process.
Having the full file allows for easy maintenance and for the acceptance tests to pull the updated byte code.
It's something our customers will be doing so it's an added benefit to stay close to that flow.
Also it ensures within our project we have a clear sense of the function options and signatures

2021-11-04 17:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    constructor() {}
Agreed, I'll revert. As part of my testing I changed it but it was originally that.

2021-11-04 17:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    receive() external payable {}
Other contract has them. Figured that update could come when we add tests for logs

2021-11-04 18:00 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    event ParentActivityLog(string message);
Similar to logs. PR was bigger than intended so was leaving that for a future PR that covers logs etc.
These modifications over time is why it's important to have the actual contract code and easily pick up the compiled byteCodes

2021-11-04 18:04 UTC, xin-hedera requested changes
looks good, just some nits

2021-11-04 18:04 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/solidity/contracts/MirrorNode.sol
> +     * A few edge cases remain, such as duplicate transction handling, ensuring timestampt increase with time etc
just typos
```suggestion
     * A few edge cases remain, such as duplicate transaction handling, ensuring timestamp increase with time etc
```

2021-11-04 18:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +    @critical @release @acceptance @contract
Actually left over from local dev. Will drop that. Thanks

2021-11-04 19:20 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +            ContractCallQuery contractCallQuery = new ContractCallQuery()
This is fair.
Although I disagree that a crypto transfer for the Query shouldn't be tested for.
I'll remove a lot of the Query checks but maybe we should add the transfer check since it sounds like a valid mirror node use case.
Maybe next PR

2021-11-04 19:53 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +            ContractCallQuery contractCallQuery = new ContractCallQuery()
My point is we already test crypto transfers elsewhere so there's no need to test them for queries. A regular transfer and a query-associated transfer appear exactly the same in the stream files.

2021-11-04 19:56 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/FileClient.java
> +        String memo = String.format("Update file %s", Instant.now());
Will update

2021-11-04 19:59 UTC, Nana-EC commented on pom.xml
> +        <hedera-sdk.version>2.3.0</hedera-sdk.version>
Might revert.
It's nice to share the version but acceptance tests and monitor test updates rarely end up being small PR's.
Maybe we should split off again so it's easier to keep each updated as needed and not add extra overhead

2021-11-04 19:59 UTC, Nana-EC commented on pom.xml
> +        <hedera-sdk.version>2.3.0</hedera-sdk.version>
A monitor update ticket should cover that testing when adding contract support

2021-11-04 20:02 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyNetworkFileCreateResponse() {
The benefit of the network checks is we can pull info to ensure NetworkNode and MirrorNode values are in sync.
It's not just to verify transaction is successful.
I'll remove those that aren't adding value now. However, the goal was to have these available to compare against the number of results and logs Mirror Node has, so they might just end up getting added back

2021-11-04 20:12 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +        MirrorTransaction mirrorTransaction = transactions.get(0);
There aren't 4. At most the update test does 3 separate file transactions.
After every `FileCreate/FileUpdae/FileAppend` there's a check for the expected transaction.

There are 4 file content strings that are used but not all at the same time, maybe you're mixing it up with that.
- `FileCreate` will use `originalFileContents`
- `FileUpdate` will use `updateBaseFileContents` or `updatedFileContents` based off of the test description of `PARTIAL` or `FULL` respectively.
- `FileAppend` only uses `appendFileContents`

2021-11-04 20:16 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyNetworkFileCreateResponse() {
That also isn't necessary for our acceptance tests. With acceptance tests, we have the original transaction payload along with the receipt that guarantee that main nodes have that payload. This guarantees that when we compare the transaction with the REST API output they should match. There's no need to query the main nodes for something we have local knowledge of.

2021-11-04 20:44 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    receive() external payable {}
Will add one since I'm simplifying tests

2021-11-04 20:46 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    event ParentActivityLog(string message);
Also note events always have at least one topic.
The hash of the hash of the function signature. I was able to confirm this in the network responses and we'll add coverage for that when we add results and log support.
Will update this event though

2021-11-04 22:34 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +@Log4j2
Done

2021-11-04 22:34 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +                KeyList.of(sdkClient.getExpandedOperatorAccountId().getPrivateKey()));
Updated

2021-11-04 22:34 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +            ContractCallQuery contractCallQuery = new ContractCallQuery()
Updated

2021-11-04 22:38 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +    public ContractInfo getContractInfo(ContractId contractId) {
See my response on having a base case to compare against.
With a simple base check here we have a reference point in case a mirror node regression or misstep occurs.
We've done this for all the other services and I think it's a good idea with minimal overhead but good value when troubleshooting.
I removed the extra Queries that were overkill for contract results on queries.

2021-11-04 22:39 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/FileClient.java
> +        String memo = String.format("Update file %s", Instant.now());
Updated

2021-11-04 22:39 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorContractResponse.java
> +    private String creatorAccountId;
Sorted

2021-11-04 22:39 UTC, Nana-EC commented on pom.xml
> +        <hedera-sdk.version>2.3.0</hedera-sdk.version>
Reverted and split

2021-11-04 22:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +                CompiledSolidityArtifact compiledMirrorNodeArtifact = mapper.readValue(
Simplified

2021-11-04 22:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    constructor() {}
Reverted. And made constructor payable

2021-11-04 22:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    receive() external payable {}
Updated

2021-11-04 22:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +    @critical @release @acceptance @contract
Dropped

2021-11-04 22:42 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/MirrorNode.sol
> +     * A few edge cases remain, such as duplicate transction handling, ensuring timestampt increase with time etc
Updated

2021-11-04 22:44 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyNetworkFileCreateResponse() {
Sure, will remove

2021-11-04 22:44 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +    public ContractInfo getContractInfo(ContractId contractId) {
Sure, will remove

2021-11-05 17:31 UTC, steven-sheehy requested changes

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
This same code seems to repeat itself in each feature. We should consider in the future creating an `AbstractFeature` that contains it or push the logic into a shared dependent class.

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    @Value("classpath:solidity/artifacts/contracts/Parent.sol/Parent.json")
File not present in latest commit.

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/contracts/MirrorNode.sol
> +// SPDX-License-Identifier: Apache-2.0
Is this folder structure dictated by hardhat? It seems like it would be better to have the folder name without `.sol` and have the solidity source within that folder.

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        executeTransferToChild(1234);
To simplify things (and reduce the costs I mentioned), we can combine create child and transfer to child into a single createChild that also transfers some initial funds to it.

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        while (byteIndex <= contractBytes.length) {
The SDK supports chunking automatically via `FileAppend`. Since we're testing the contract service and not the file service we should just filecreate with empty contents and let the SDK chunk the file. 

Either that or this chunking logic belongs in the `FileClient`.

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.isDeleted()).isEqualTo(isDeleted);
We need to try to verify as many fields as we can like bytecode, obtainer_id for deleted, timestamp range, memo, etc.

2021-11-05 17:31 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +    Scenario Outline: Validate Contract Flow - ContractCreate and ContractUpdate
Again, due to costs I think we can consolidate to ContractCreate, ContractUpdate, ContractCall, ContractDelete.

2021-11-05 18:38 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        executeCreateChildTransaction();
Looks like SDK isn't exposing `createdContractIds` in `ContractFunctionResult` will open a ticket

2021-11-05 18:52 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        executeCreateChildTransaction();
Opened [Expose CreatedContractIDs in ContractFunctionResult](https://github.com/hashgraph/hedera-sdk-java/issues/758)

2021-11-05 19:04 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
I have a few times, the current layout of cucumber test run logic doesn't allow for Feature class inheritance.
Although it seems like composition might be the better approach to get around this.
Would do it in this PR though as it'll be an invasive refactoring on most StepDefinition classes

2021-11-05 19:05 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/MirrorNode.sol
> +// SPDX-License-Identifier: Apache-2.0
Yes dictated by hardhat, that's the build structure it uses

2021-11-05 19:07 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        executeTransferToChild(1234);
Sure, wanted to make each feature clear since we'll want to verify the results and logs for each of these .
On the mirror node side it shouldn't matter that it's all done in once

2021-11-05 19:15 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +                .setTransactionMemo(memo);
Agreed, was leaving it for acceptance tests for contract results since it can't be verified now.
Will add it though

2021-11-05 19:17 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/file/file.feature
> +    Scenario Outline: Validate File Flow - FileCreate and FileUpdate
Yeah the cost around running it does force us to break with good test methodology in which you'd want scenarios to be more atomic.
Will consolidate here and on contract side

2021-11-05 19:17 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        executeCreateChildTransaction();
That's unfortunate. I really wish the SDKs exposed the raw proto doc as an escape value in case they've not fully implemented every method.

2021-11-05 19:19 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        createContract(compiledParentArtifact.getBytecode());
Same comment as executeCreateChildTransaction()

2021-11-05 19:20 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
I can see why cucumber steps might not be visible in parent but just plain protected helper methods should still work though.

2021-11-05 19:21 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    @Value("classpath:solidity/artifacts/contracts/Parent.sol/Parent.json")
Missed on commit, will add along with Child

2021-11-05 20:39 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
Yeah that works, will add

2021-11-05 21:30 UTC, xin-hedera requested changes

2021-11-05 21:30 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/FileClient.java
> +    public NetworkTransactionResponse createFile(byte[] byteCode) {
nit, need a name different than `byteCode`

```suggestion
    public NetworkTransactionResponse createFile(byte[] content) {
```

2021-11-05 21:30 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        byte[] contractBytes = contractContents.getBytes(StandardCharsets.UTF_8);
Should we decode the hex string?

2021-11-05 21:56 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +                .setTransactionMemo(memo);
Updated to provide initial balance for main flow

2021-11-05 21:56 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
> +    function createChild() public {
Updated

2021-11-05 21:56 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/file/file.feature
> +    Scenario Outline: Validate File Flow - FileCreate and FileUpdate
Updated

2021-11-05 21:57 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/FileFeature.java
> +    public void verifyMirrorAPIResponses(int status) {
Updated

2021-11-05 21:57 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    @Value("classpath:solidity/artifacts/contracts/Parent.sol/Parent.json")
Added

2021-11-05 21:57 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        executeTransferToChild(1234);
Got rid of donate execute and added transfer logic to create

2021-11-05 21:58 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        while (byteIndex <= contractBytes.length) {
Updated

2021-11-05 22:23 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.isDeleted()).isEqualTo(isDeleted);
Added most that could be verified except for missing `obtainerId` case

2021-11-05 22:23 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +    Scenario Outline: Validate Contract Flow - ContractCreate and ContractUpdate
Simplified

2021-11-05 22:25 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        byte[] contractBytes = contractContents.getBytes(StandardCharsets.UTF_8);
No, this is the expected format

2021-11-05 22:28 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/FileClient.java
> +    public NetworkTransactionResponse createFile(byte[] byteCode) {
Updated

2021-11-06 01:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.isDeleted()).isEqualTo(isDeleted);
If you get around to it you can merge should be able to add `obtainerId`.

2021-11-06 02:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.isDeleted()).isEqualTo(isDeleted);
Sure rebased. Will fail until integrated but we should be good

2021-11-08 16:56 UTC, steven-sheehy requested changes

2021-11-08 16:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(address).isNotEqualTo("0x0000000000000000000000000000000000000000");
Should chain assertions to the same object:
```suggestion
        assertThat(address).isNotBlank().isNotEqualTo("0x").isNotEqualTo("0x0000000000000000000000000000000000000000");
```

2021-11-08 16:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.getBytecode()).isNotBlank();
If you store the `CompiledSolidityArtifact` you can assert its bytecode is equal here.

2021-11-08 16:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.getAdminKey()).isNotNull();
Could compare against SDK operator key.

2021-11-08 16:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/file/file.feature
> +            | 200            | "PARTIAL"   |
The parameter is named `bytesLength` but the value is not a number

2021-11-08 20:24 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(address).isNotEqualTo("0x0000000000000000000000000000000000000000");
Updated

2021-11-08 20:24 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.getBytecode()).isNotBlank();
Updated

2021-11-08 20:24 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.getAdminKey()).isNotNull();
Updated

2021-11-08 20:24 UTC, Nana-EC commented on hedera-mirror-test/src/test/resources/features/file/file.feature
> +            | 200            | "PARTIAL"   |
Removed

2021-11-08 20:26 UTC, steven-sheehy approved these changes
LGTM

2021-11-08 22:05 UTC, xin-hedera approved these changes
LGTM

2021-11-08 22:26 UTC, merged