Remove transaction types table
hashgraph/hedera-mirror-node pull request #2791
Opened 2021-11-03 16:21 UTC by ijungmann

**Description**:
Remove `t_transaction_types` reference table, add enums/constants.

* Remove `t_transaction_types` table
* Add constants to REST and Rosetta to have a lookup between transaction type protobuf id and names
* Update REST and Rosetta to use new constants

**Related issue(s)**:

Fixes #1968 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-03 16:49 UTC, ijungmann commented on hedera-mirror-rosetta/app/services/base_service.go
> +		blockRepo interfaces.BlockRepository,
Format

2021-11-03 21:47 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +
Need to discuss this.  `HederaFunctionality` has the transaction types, but it includes types we wouldn't expect to see and haven't had in the DB.  We could also have a similar issue to result types where we are ahead of the Go/Javascript proto, so that check is a no go for now.  It may be worth adding the extra values to the constants.

2021-11-03 22:11 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    memo                 text        default ''         not null,
Undo formatting

2021-11-03 22:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +select auto_renew_period,
Formatting

2021-11-03 22:13 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> -describe('DB integration test -  utils.isValidTransactionType', () => {
Add tests for this to model

2021-11-03 22:13 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +  expect(extractNameAndResultFromTransactionResults(res.rows)).toEqual(['undefined, -1']);
Handled later now

2021-11-03 22:14 UTC, ijungmann commented on hedera-mirror-rest/__tests__/tokens.test.js
> +      select nft_tr.consensus_timestamp,
Formatting

2021-11-04 21:03 UTC, steven-sheehy requested changes

2021-11-04 21:03 UTC, steven-sheehy commented on hedera-mirror-rest/model/transactionType.js
> +  getTransactionTypeProtoId,
It's a bit redundant to have the words `TransactionType` in the method names when it's used with the `TransactionType` import prefix. Should we simplify the name or is necessary for export collisions?

2021-11-04 21:03 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/model/transactionType.test.js
> +describe('getTransactionResultName', () => {
Similar to results, we need a test that loops over the proto transactionbody datacase enum to verify we have them all.

2021-11-04 21:32 UTC, ijungmann commented on hedera-mirror-rest/__tests__/model/transactionType.test.js
> +describe('getTransactionResultName', () => {
Will look into this, I don't see that transactionbody has an enum in the same way as ResponseCode, the ints are the actual field values in this case.

2021-11-04 21:33 UTC, ijungmann commented on hedera-mirror-rest/model/transactionType.js
> +  return transactionTypeProtoToName.hasOwnProperty(protoId) ? transactionTypeProtoToName[protoId] : 'UNKNOWN';
Done for both.

2021-11-04 21:35 UTC, ijungmann commented on hedera-mirror-rest/model/transactionType.js
> +  getTransactionTypeProtoId,
Seems to work just fine simplified, and I agree.  I've fixed both `transactionTypes` and `transactionResults` to have simpler method names

2021-11-05 05:20 UTC, Nana-EC requested changes
Looking good, just minor suggestions

2021-11-05 05:20 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/model/transactionType.test.js
> +describe('getName', () => {
nit: add `null` and `undefined` to the test cases

2021-11-05 05:20 UTC, Nana-EC commented on hedera-mirror-rest/transactions.js
> +    FROM ${tableName} AS ${tableAlias} ${joinClause} ${whereClause}
nit: can you revert the squashes in this file. IntelliJ does the same thing for me occasionally
Personally it's nicer when the `select, from, join, where` are each on new lines

2021-11-05 14:42 UTC, xin-hedera requested changes

2021-11-05 14:42 UTC, xin-hedera commented on hedera-mirror-rest/model/transactionType.js
> +    throw new InvalidArgumentError(`Transaction type ${transactionTypeName.toUpperCase()} not found in db`);
nit
```suggestion
    throw new InvalidArgumentError(`Invalid transaction type ${transactionTypeName.toUpperCase()}`);
```

2021-11-05 14:42 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration.test.js
> +  expect(extractNameAndResultFromTransactionResults(res.rows)).toEqual(['undefined, -1']);
remove this test case as well as the function `extractNameAndResultFromTransactionResults`

the test case no longer applies since there's no more joining t* types to get transaction type / transaction result.

2021-11-08 19:39 UTC, ijungmann commented on hedera-mirror-rest/__tests__/model/transactionType.test.js
> +describe('getTransactionResultName', () => {
I do see that in the Java build, unfortunately I don't see anything similar for Golang or Javascript.  The closest thing I can find in the Javascript library is this, but I've found no way of actually accessing it in a test:
```public data?: ("contractCall"|"contractCreateInstance"|...");```
Similar issues with Go.  I added tests that just check the last entry in `HederaFunctionality` for both (which is somewhat connected to `TransactionBody` types) that would alert us if a newer entry was added, but it's not directly testing this.

2021-11-08 20:06 UTC, steven-sheehy requested changes

2021-11-08 20:06 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), 67)
What's the difference between this test and the one in transactionType.test.js and why do the a different number of expected entries?
```
    //Last entry is TokenFeeScheduleUpdate: 77
    expect(Object.keys(proto.HederaFunctionality).length).toEqual(hederaFunctionalityLength);
```

2021-11-08 20:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionType.java
> -public class TransactionType {
Yep!  Will do.

2021-11-08 20:36 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), 67)
Same test, just using a different library (Go vs Javascript).  The Javascript protobuf is currently behind and does't have `NetworkGetExecutionTime`, `TokenPause`, and `TokenUnpause`.

2021-11-08 20:39 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), 67)
Ah, complete missed the fact that it's go not js 😅

2021-11-08 20:45 UTC, ijungmann commented on hedera-mirror-rest/__tests__/model/transactionType.test.js
> +    expect(TransactionType.getName(9999999)).toEqual('UNKNOWN');
Added constants for all ints

2021-11-08 20:46 UTC, ijungmann commented on hedera-mirror-rest/model/transactionType.js
> +    throw new InvalidArgumentError(`Transaction type ${transactionTypeName.toUpperCase()} not found in db`);
Good catch, fixed

2021-11-08 20:47 UTC, ijungmann commented on hedera-mirror-rest/transactions.js
> +    FROM ${tableName} AS ${tableAlias} ${joinClause} ${whereClause}
Yeah, IntelliJ is really fighting me on this.  I believe I've put it back (again...).

2021-11-08 20:47 UTC, ijungmann commented on hedera-mirror-rest/__tests__/model/transactionType.test.js
> +describe('getName', () => {
Added

2021-11-08 20:57 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integration.test.js
> +  expect(extractNameAndResultFromTransactionResults(res.rows)).toEqual(['undefined, -1']);
Removed

2021-11-08 20:58 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), 67)
proto.HederaFunctionality can't serve as the data structure to rely on for cross checking the supported transaction types as shown in `transaction_body.proto`. searching the protobuf repo shows it's only used in `throttle_definitions.proto` for message `ThrottleGroup`

there should be another way to extra the info we need from sdk's `proto` package

2021-11-08 21:14 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-11-08 21:15 UTC, steven-sheehy submitted a review, later dismissed

2021-11-08 21:43 UTC, xin-hedera requested changes

2021-11-08 21:43 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +var hederaFunctionalityLength = 67
shouldn't hard code the actual length of `TransactionTypes`

2021-11-08 21:43 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
this limits us to be only able to change the go constants after sdk release has added the new transaction types.

instead we should do

```suggestion
	assert.LessOrEqual(t, len(proto.HederaFunctionality_name), len(TransactionTypes))
```

2021-11-08 21:45 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
I think I missed the fact `proto.HederaFunctionality_name` is a superset of the transaction types.

However, the suggestion still stands and there is a way to get the list of `TransactionBody.Data` data cases.

2021-11-08 22:04 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
tested and it works:

```go
func TestTransactionTypesUpToDate(t *testing.T) {
	sdkTransactionTypes := getSdkTransactionTypes()
	for protoId, name := range sdkTransactionTypes {
		assert.Equal(t, name, TransactionTypes[protoId])
	}
}

func getSdkTransactionTypes() map[int32]string {
	body := proto.TransactionBody{}
	dataFields := body.ProtoReflect().Descriptor().Oneofs().ByName("data").Fields()
	transactionTypes := make(map[int32]string)
	for i := 0; i < dataFields.Len(); i++ {
		dataField := dataFields.Get(i)
		name := strings.ToUpper(string(dataField.Name()))
		transactionTypes[int32(dataField.Number())] = strings.ReplaceAll(name, "_", "")
	}

	return transactionTypes
}
```

2021-11-08 22:12 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
I don't think that test would work, since `HederaFunctionality` is a superset of `TransactionTypes`, including values such as `NetworkGetExecutionTime` and things that we don't care about.  This test isn't really about `TransactionType`, it's just a warning test that says "Hey, if this fails it means new values were added to `HederaFunctionality`, so there are probably new Transaction Types as well.  I can add a comment saying as much.

2021-11-08 22:13 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +var hederaFunctionalityLength = 67
Stated below the rational for this, it's a bit of a weird test case, but this isn't the length of `TransactionTypes`.

2021-11-08 22:26 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
Didn't refresh the page to see the second comment...  Will test this out.  Anything similar for the Javascript version?

2021-11-08 22:27 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
the code snippet does exactly what we want and it's stricter. In addition, we don't have the burden of updating the constant `67` in the test file everytime we update the `TransactionTypes` in `constants.go`:

1. `getSdkTransactionTypes` extracts the protoId to transaction type map from the sdk by the reflection mechanism provided by the `protobuf` package.
2. The test case then checks that the `sdkTransactionTypes` is a subset of `TransactionTypes`

So we are allowed to be ahead of SDK, but not the vise versa.

2021-11-08 22:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
> Didn't refresh the page to see the second comment... Will test this out. Anything similar for the Javascript version?

Nah, checked the js code, it's very raw, basically the generated js code directly write the encoded data base value...

2021-11-08 22:33 UTC, ijungmann commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> +	assert.Equal(t, len(proto.HederaFunctionality_name), hederaFunctionalityLength)
Cool, I've replaced the Go test then with your test, appreciate the help, that is much cleaner.  Unfortunate that the JS is much more restrictive.

2021-11-08 22:38 UTC, xin-hedera approved these changes
LGTM

2021-11-08 22:46 UTC, merged