Update smart contract design w support for additional APIs
hashgraph/hedera-mirror-node pull request #2838
Opened 2021-11-12 07:19 UTC by Nana-EC

**Description**:
The current smart contract design was partial by design and lacks a recommendation for APIs that provide Dapp developers a minimal viable API experience for Ethereum smart contract development.

To address this , the updated design
- Add additional REST API endpoints suggestion under the `api/v1/conracts` resource that provide more complete transaction receipt information
- Add a suggestion for a starting point for an Ethereum JSON-RPC API spec

**Related issue(s)**:

Fixes #2721 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-15 18:33 UTC, ijungmann reviewed
Still looking.

2021-11-15 18:33 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
Should this be an array?  Noticing the name is plural.

2021-11-15 20:13 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
It's just a count

2021-11-15 20:15 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  record_index        int         not null,
Need to circle back on this. It's addition supports the logic for `getblocktransactioncountbynumber`

2021-11-15 21:39 UTC, xin-hedera requested changes
will circle back

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
>    amount               bigint             null,
not really part of this PR: can you update line 52 to

`type integer default 'CONTRACT' not null`

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  record_index        int         not null,
if this is `record_file.index`, it's a `bigint`

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, gin(storage_keys))
the primary key causes syntax error

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, slot)
how big is `slot`? if it's big, the index'll be big too

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  ],
is `internal_transfers` more accurate? also it can be hbar transfer, fungible token transfer, and non-fungible token transfer, so should the value be an object instead of an array?

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +}
missing `links.next`?

2021-11-15 21:39 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +}
missing `links.next`

2021-11-15 22:42 UTC, Nana-EC commented on docs/design/smart-contracts.md
>    amount               bigint             null,
Can do

2021-11-15 22:44 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, slot)
Up to 32 bytes

2021-11-15 22:56 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, slot)
Also should make index on a hash of the `bytea`

2021-11-15 23:05 UTC, steven-sheehy requested changes
Still reviewing

2021-11-15 23:05 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  "child_transactions": null,
I don't think this should be null. We should migrate existing rows to zero and new rows will be accurate.

```suggestion
  "child_transactions": 0,
```

2021-11-15 23:05 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +      "amount": "",
Should have example values or make it empty array if unsure.

2021-11-15 23:21 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
Need to also add `account_access` bigint array

2021-11-15 23:46 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, gin(storage_keys))
Will updating, was exploring if a `gin` index was useful but might sufficient to stay b-tree

2021-11-15 23:48 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  ],
Yes, in Hedera terms transfers makes sense.
However, Eth terms calls all the transfers transactions.
This is an example of all the mixed terms I noted.
Eventually this may also have a `type` field etc

2021-11-15 23:52 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
That's fine, just wanted to make sure I wasn't missing something.

2021-11-15 23:52 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
Can even go smallest in that case

2021-11-15 23:53 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  storage_keys        bytea array not null,
Yeah I realized I missed, coming through on next commit.

2021-11-15 23:54 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  storage_keys        bytea array not null,
Yep I have `account_access` as a `bigint array`, doesn't need to be broken off

2021-11-15 23:56 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +create table if not exists contract_access_list
Works for me.
REST response should still be `access_list` though

2021-11-15 23:59 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- `to`
Both statements are true. It's the contractId that receives the transfer.
However, you're right the `To` is implicit and doesn't need to be a filter

2021-11-16 00:17 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  record_index        int         not null,
Updated

2021-11-16 00:17 UTC, Nana-EC commented on docs/design/smart-contracts.md
>    amount               bigint             null,
Updated

2021-11-16 00:18 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, gin(storage_keys))
Updated

2021-11-16 00:18 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +}
Added

2021-11-16 00:18 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +}
Added

2021-11-16 00:18 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
Updated

2021-11-16 00:19 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  storage_keys        bytea array not null,
Pushed

2021-11-16 00:19 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +create table if not exists contract_access_list
Updated

2021-11-16 00:19 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Add a `ContractAccessList` domain object with fields that match the schema.
Updated

2021-11-16 00:19 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- `to`
Updated

2021-11-16 00:19 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  "blockNumber": "50",
Updated

2021-11-16 00:19 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  "child_transactions": null,
Updated. Made 0 -> "0"

2021-11-16 00:20 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "amount": "",
Updated

2021-11-16 00:20 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   bigint             null,
Added

2021-11-16 00:24 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  record_index        bigint      not null,
Options here include
- Populate in insert by pulling value from `RecordFile`
- Join on queries - consult `record_file` to file the file that has the consensus_timestamp in its range and get its index
Wanted to to avoid a join but might be worth starting with join case and migrating later if performance is a big issue

2021-11-16 03:23 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  type                 integer default 'CONTRACT' not null
nit: was an existing issue, but since we're fixing it.
```suggestion
  type                 entity_type default 'CONTRACT' not null
```

2021-11-16 16:08 UTC, ijungmann reviewed
A few more nits

2021-11-16 16:08 UTC, ijungmann commented on docs/design/smart-contracts.md
> +The Mirror Node should implement a subset of the standard calls using to
nit: I think this is what you were going for.
```suggestion
The Mirror Node should implement a subset of the standard calls used to
```

2021-11-16 16:08 UTC, ijungmann commented on docs/design/smart-contracts.md
> +- to encompass Hedera EVM translation logic that can be wrapped by potential web3 modules.
```suggestion
- encompass Hedera EVM translation logic that can be wrapped by potential web3 modules.
```

2021-11-16 16:08 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  `account_balance`, `contract`, `record_file` and `transaction` tables returning data in expected schema formats.
nit
```suggestion
  `account_balance`, `contract`, `record_file`, and `transaction` tables returning data in expected schema formats.
```

2021-11-16 16:14 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  `account_balance`, `contract`, `record_file` and `transaction` tables returning data in expected schema formats.
Fixed

2021-11-16 16:14 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- to encompass Hedera EVM translation logic that can be wrapped by potential web3 modules.
Fixed

2021-11-16 16:14 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +The Mirror Node should implement a subset of the standard calls using to
Fixed

2021-11-16 16:14 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  type                 integer default 'CONTRACT' not null
Updated

2021-11-16 18:10 UTC, steven-sheehy requested changes

2021-11-16 18:10 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +   Ans: Yes, as we can easily extract from transaction and record tables.
I don't think we should have answered questions in the "Open Questions" section

2021-11-16 18:10 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  private Object[] params;
From what I can tell the params are always strings.
```suggestion
  private String[] params;
```

2021-11-16 19:50 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, storage_keys)
It's possible and works. Did local testing on table creation and insertion with above

2021-11-16 19:51 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, storage_keys)
Checking that `storage_keys` can be pulled out. Index would look the same though

2021-11-16 20:04 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, index)
Logs will be retrieved by contract_id sometimes without timestamp, and then with timestamp but without index.
Will add a separate index for timestamp and id

2021-11-16 20:29 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Create a new Maven module `hedera-mirror-eth` or `hedera-mirror-json-rpc` or `hedera-mirror-web3`
Going with `web3`

2021-11-16 20:30 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Create a Systemd unit file `hedera-mirror-evm.sevice` and add to deployment script
Works for me

2021-11-16 20:36 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +    private String result;
Yeah I had this as an `abstract class` first with suggested implementation for the different types.
Then went with this shared one as the object to be returned for response.
Serialization of the dynamic format would be behind this e.g each internal dynamic object could have a `toJSONRpcRsponse()`

2021-11-16 20:49 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  private String id;
True. Will update, and in response also

2021-11-16 20:50 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  private Object[] params;
Not the case always. Sometimes booleans and objects e.g. https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_getlogs & https://api.besu.hyperledger.org/#f439903b-1a62-4b73-81de-0dc6927f0589
Though I wish it was

2021-11-16 21:35 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "to": "0.0.1003"
Here's an example with [internal transactions](https://etherscan.io/tx/0x74ad7da9a438bb278cea875012bca75edd7e3b74e915b9be6f7722bf7eea54e2/advanced#internal)
Our challenge is we'll eventually have both Hedera and EVM internal/child transactions.
This current structure was suited more for EVM child transactions.
Thinking on the best way for the Hedera transactions as there's more info and parsing of transferLists is not straight forward

2021-11-16 22:17 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +`GET /api/v1/contracts/{id}/results/state-changes`
We'd noted `/api/v1/contracts/{id}/results/access-list/{timestamp}` and `/api/v1/contracts/{id}/results/state-changes/{timestamp}` should be dropped.
These are valid but potentially but maybe yet needed endpoints.
I'll drop them for now and we can always carve them out later if needed by customers.

2021-11-16 22:38 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   smallint           null,
Gotcha, so drop and pull when joining with transaction table

2021-11-16 23:08 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  private String id;
Updated to `Long` in Response as it's nullable

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +    private String method;
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      transactionHash: '0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238',
Fixed

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +   Ans: Yes, as we can easily extract from transaction and record tables.
Removed

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +Existing domain and repositories can be utilized from the `hedera-mirror-common` dependencies to extract information
Updated.

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Create a Systemd unit file `hedera-mirror-evm.sevice` and add to deployment script
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Create a new Maven module `hedera-mirror-eth` or `hedera-mirror-json-rpc` or `hedera-mirror-web3`
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +The HyperLedger Besu EVM supports the methods capture
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- `topic ([topic0,topic1,topic2,topic3])`
Reverted

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "address": "0x0000000000000000000000000000000000001234",
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "to": "0.0.1003"
Added `type` and renamed `amount` to `value`.
Also renamed list from `internal_trnasactions` to `evm_internal_transactions` to not confuse with hedera internal transactions

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, storage_keys)
Simplified

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Add `EntityListener.onContractAccessList(ContractAccessList)`
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- Add logic to create a `ContractAccessList`, `ContractLog`, `ContractResult` and `ContractStateChange` domain objects
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  child_transactions   smallint           null,
Dropped

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  "block_number": "50",
Updated

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  "child_transactions": "0",
Switched back.

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +create index if not exists contract_result__to_from
Fixed

2021-11-16 23:09 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +    // 1207
Fixed

2021-11-16 23:21 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +`GET /api/v1/contracts/{id}/results/access-list`
Dropped

2021-11-16 23:21 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +`GET /api/v1/contracts/{id}/results/state-changes`
Dropped

2021-11-17 05:55 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  record_index        bigint      not null,
Removed, leaving for later

2021-11-17 05:58 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +    "hedera_child_transactions": [
An alternative embracing [JSON:API Specification v1.0](https://jsonapi.org/format/#document-links) could be 
```suggestion
    "related": {
    "hedera_child_transactions": [
      {
        "timestamp": "12345.10001",
        "endpoint": "api/v1/transactions/0.0.11943-1637100159-861284000"
      }
    ]
  }
```

2021-11-17 22:55 UTC, steven-sheehy requested changes

2021-11-17 22:55 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  "hash": "0x5b2e3c1a49352f1ca9fb5dfe74b7ffbbb6d70e23a12693444e26058d8a8e6296",
Can you clarify the source of block_hash and hash?

2021-11-17 22:55 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  with [JSON-RPC 2.0 specification] (https://www.jsonrpc.org/specification) support to service rpc calls
Link rendering is broken
```suggestion
  with [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification) support to service rpc calls
```

2021-11-17 22:55 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +- `EthRpcService` interface that describes the supported rpc methods
I'm not sure `EthRpc` prefix still works with the module being named web3. Perhaps rename all the `EthRpc` and `JSONRpc` to `Web3` prefix? Or we can always just revisit during implementation phase.

2021-11-17 22:55 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  "result": "SUCCESS"
I don't think it can be both an error and a success.

2021-11-17 22:55 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +- getBalance *
It's not clear what the `*` denotes next to some methods.

2021-11-18 06:28 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  primary key (consensus_timestamp, contract_id, index)
Updated

2021-11-18 06:28 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +    "hedera_child_transactions": [
Moved to `Open Questions` section

2021-11-18 06:29 UTC, Nana-EC commented on docs/design/smart-contracts.md
>  ## Open Questions
Went with "Answered Questions"

2021-11-18 06:29 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- `state-changes` should be retrieved by a join between the `contract_result` and `contract-state-change` tables.
Updated

2021-11-18 06:29 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +        "af846d22986843e3d25981b94ce181adc556b334ccfdd8225762d7f709841df0",
Added

2021-11-18 06:30 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "after": "0x000000000000000000000000000000000000000000c2a8c80ee5fda74d69c302",
They were different, but I made it more clear

2021-11-18 06:31 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "slot": "0x0000000000000000000000000000000000000000000000000000000000000002",
Yeah, in the former API that was implicit, here it needs to be explicit.
Not sure if we should go for `contract_id` or `solidity_address`. 


Should we present all contracts as ids or addresses? Either ways we should be consistent
We could also add a query filter to present all contract ids as hedera ids or evm addresses.
Going with address for now

2021-11-18 06:31 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "address": "0xbb9bc244d798123fde783fcc1c72d3bb8c189413",
`address` it is

2021-11-18 06:39 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  "hash": "0x5b2e3c1a49352f1ca9fb5dfe74b7ffbbb6d70e23a12693444e26058d8a8e6296",
`block_hash` is record_file. file_hash ` and hash is `transaction.hash`. Will add notes

2021-11-18 06:39 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "solidity_address": "0x0000000000000000000000000000000000001234",
Updated

2021-11-18 06:39 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  with [JSON-RPC 2.0 specification] (https://www.jsonrpc.org/specification) support to service rpc calls
Updated

2021-11-18 06:39 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- `EthRpcService` interface that describes the supported rpc methods
Will rename to `JSONRpc` as more applicable (similar to Besu) to the service and we can revisit in implementation.

2021-11-18 06:39 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  ```
Updated

2021-11-18 06:39 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  "result": "SUCCESS"
Removed `result`

2021-11-18 06:43 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- getBalance *
Left over from prior to priority labels. Removed

2021-11-18 07:47 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "slot": "0x0000000000000000000000000000000000000000000000000000000000000002",
Looks like we already have it as `solidity_address` under `/api/v1/contracts` and `/api/v1/contracts/{id}` though

2021-11-18 20:46 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +      "after": "0x000000000000000000000000000000000000000000c2a8c80ee5fda74d69c302",
No I meant add a `difference` field like how etherscan has.

2021-11-18 21:08 UTC, ijungmann commented on docs/design/smart-contracts.md
>  ```
Not requesting it here, but it would make sense to note the table type (distributed, reference, local) and any distribution column and colocation info going forward.

2021-11-18 21:36 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "after": "0x000000000000000000000000000000000000000000c2a8c80ee5fda74d69c302",
The difference refers to the contract balance change I believe. 
I don't see the change in the protobuf draft and don't think we should do the work to calculate it here if not needed.
Makes sense in a dashboard or web explorer to take the input and calculate that and we can look into it later if needed.

2021-11-18 21:42 UTC, Nana-EC commented on docs/design/smart-contracts.md
>  ```
Good point and I agree going forward.
I would add it here but since there's still some discussion on that I'll leave it our for the ticket to address it.

2021-11-18 21:44 UTC, ijungmann requested changes
Looks good.  A few questions, observations, and nits.

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Not sure if it's worth noting, bloom appears to have some risk of false positives

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +      "solidity_address": "0x0000000000000000000000000000000000001893",
I think this is supposed to be `address` now based on above conversation in `/results`

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +the [Ethereum JSON-RPC Specification](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView
Would `https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json` suffice, just for simplicity, or is there something in that view that the shorter one lacks?

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +- support existing ethereum developers who may call the JSON-RPC endpoints directly
nit: is there a difference in lower-case `ethereum` vs `Ethereum`?

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +- encompass Hedera EVM translation logic that can be wrapped by potential web3 modules.
nit: Seeing it capitalized mostly.
```suggestion
- encompass Hedera EVM translation logic that can be wrapped by potential Web3 modules.
```

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +### JSON RPC Service
nit:
```suggestion
### JSON-RPC Service
```

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +[Jackson](https://github.com/FasterXML/jackson) library to create a `JSONRpcRequest` object that each method can parse
nit:
```suggestion
[Jackson](https://github.com/FasterXML/jackson) library to create a `JSONRpcRequest` object that each method can parse.
```

2021-11-18 21:44 UTC, ijungmann commented on docs/design/smart-contracts.md
> +added. The value can range from regular data types (String, int, array) or defined Ethereum objects such as
nit: range from ... to.
```suggestion
added. The value can range from regular data types (String, int, array) to defined Ethereum objects such as
```

2021-11-18 22:08 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Yeah, was thinking on this.
I don't think it's worth increasing the signature length since that doesn't avoid the probability of false positives.
We can either just go the normal tree index route or add additional indexes on the individual topic columns.

I'm leaning towards just being right with btree and optimizing for performance later.

2021-11-18 22:08 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "solidity_address": "0x0000000000000000000000000000000000001893",
Updated

2021-11-18 22:10 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +the [Ethereum JSON-RPC Specification](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView
I like yours better. The longer one just hides the playground until needed and other view configurations

2021-11-18 22:11 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- support existing ethereum developers who may call the JSON-RPC endpoints directly
no, should just all be `Ethereum`

2021-11-18 22:24 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Decided to go with btree for now. There are as many columns so 4 might be manageable and we can always revisit it

2021-11-18 22:24 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +the [Ethereum JSON-RPC Specification](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView
Updated

2021-11-18 22:25 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +- encompass Hedera EVM translation logic that can be wrapped by potential web3 modules.
Updated

2021-11-18 22:25 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +### JSON RPC Service
Updated

2021-11-18 22:25 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +added. The value can range from regular data types (String, int, array) or defined Ethereum objects such as
Updated

2021-11-18 22:35 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
false positive is not an issue when querying by a bloom index.

false positive just means when pg runs a query on a bloom index, pg has to do an additional field by field comparison to rule out the false positives. It won't return the false positives in the query result iirc.

So we should change back to bloom index.

2021-11-18 22:50 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Thanks for the explanation Xin, I wasn't very familiar with a bloom index and just noticed that in the documentation.  It sounds like it's what we need, and if it handles the false positives then I have no concerns.

2021-11-18 23:29 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Will revert back to what I originally thought then :) 
Good to get clarification though as I want sure if the additional field by field comparison was a extra effort on our end of automatically done by postgres

2021-11-18 23:29 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Reverted

2021-11-18 23:37 UTC, xin-hedera requested changes
note I think we should switch back to bloom index

2021-11-18 23:37 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +Create a new table to store the stage changes of a contract execution
```suggestion
Create a new table to store the state changes of a contract execution
```

2021-11-18 23:37 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +);
have we considered follow the design of `entity` and `entity_history` tables? i.e., having a `contract_state` table which reflects the current storage state of each contract, then a `contract_state_history` table for the past?

doing so, we only have to save the value of the slot current to the timestamp range

```sql
create table if not exists contract_state
(
  contract_id         bigint not null,
  slot                bytea  not null,
  timestamp_range     int8range not null,
  value               bytea  not null,
);
```

2021-11-19 15:40 UTC, steven-sheehy requested changes

2021-11-19 15:40 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
I'm not sure this is the correct syntax for a bloom index. I don't think it should have contract_id and probably needs to specify options like length and cols. But we can leave it as is and finalize during implementation.

2021-11-19 15:40 UTC, steven-sheehy approved these changes
Meant to approve with comment.

2021-11-19 15:52 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
agree we should not include contract_id in the index. For the index size (number of bits) and number of bits for each column, we have to run come tests with synthetic data, basically to find a balance between the size and hash collisions (which cause false positives).

2021-11-19 16:20 UTC, ijungmann approved these changes
LGTM

2021-11-19 16:23 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  on contract_log using bloom (contract_id, topic0, topic1, topic2, topic3);
Correct, id should be out, I'm leaving the size as defaults for now until testing like Xin mentioned

2021-11-19 16:25 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +);
It's a good idea. 
I think it'd be really valuable in the scenario where we'd want to pull the current state, however, the use case is always looking at before and after per instance.
In this case though the context is to understand what the contract transaction did and what changes it caused at a given timestamp. 

I think lets keep it like this and consider if a history form gives us more value when the proto comes through

2021-11-19 16:44 UTC, ijungmann approved these changes

2021-11-19 16:46 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +);
no problem with that approach. if there is a strong need that we often need to provide the current state, or even the state in the past, the two table solution may work better.

2021-11-19 16:46 UTC, xin-hedera approved these changes
LGTM

2021-11-19 17:08 UTC, merged