Entity table distribution columns
hashgraph/hedera-mirror-node pull request #2839
Opened 2021-11-12 17:54 UTC by ijungmann

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-12 17:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/AccountBalance.java
> +            @JoinColumn(name = "accountId", updatable = false),
Add the comments for these

2021-11-12 20:25 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract', 'id');
Swap

2021-11-12 20:44 UTC, ijungmann commented
Looking into Rosetta failures

2021-11-12 21:37 UTC, xin-hedera requested changes

2021-11-12 21:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('record_file', 'node_account_id', colocate_with => 'entity');
don't think we should distribute record_file; also distributing it by `node_account_id` would almost have all rows in one shard since node_account_id is the same from most rows

The question then is should it be a reference table or a normal pg table which only exists in the coordinator

2021-11-12 21:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
>  -------------------
shouldn't remove the `Create reference tables` comment, since the `reference table` here is a citus term, not the `t_transaction*` tables we had

2021-11-12 21:46 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'contract');
Was discussing this with Nana, he was of the opinion it should still be under `contract`, but I see why it would be under `entity` as well.

2021-11-12 21:48 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint account_balance__pk primary key (consensus_timestamp, account_id);
I got the following error when trying to do that: `ERROR: cannot create constraint without a name on a distributed table`.

2021-11-12 21:53 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
>  -------------------
Sure, you have a point.  I didn't have any reference tables at the time so I removed it, but it looks like it will be used again.

2021-11-12 22:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'contract');
because the majority of contract call tx payer accounts are contracts? if so, then it makes sense to colocate with `contract` on `payer_account_id`

2021-11-15 16:39 UTC, Nana-EC requested changes
Looking good, check for left over timescale logic and comments on distributions questions

2021-11-15 16:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('account_balance_file', 'node_account_id', colocate_with => 'entity');
Isn't this dependent on whether bytes are stored for the file. If they are the table isn't always as small and varies and will likely grow over time.

2021-11-15 16:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'contract');
I think it's correct as is.
`entity` and `contract` have no conflicts so colocating any contract metadata table with `entity` will provide no value.
Also the joins and filters on contract metadata will mostly be done by the contract id/address.

2021-11-15 16:39 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('record_file', 'node_account_id', colocate_with => 'entity');
Is this more so highlighting tech debt on our side. Should we rather be fixing it so that `node_account_id` is not always the same?

Agreed though, until there is variation in that value we can have it as a normal table to only exist not eh coordinator. This will be good for the importer process as no extra db node calls but also avoids duplication.

However, this could change for the upcoming contract REST APIs where there will likely be more joins with record. Just depends how we write the queries.

For now maybe stay simple and leave as a normal table and we can iterate on this

2021-11-15 16:43 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('record_file', 'node_account_id', colocate_with => 'entity');
I see the logic in not distributing it.  As for reference table vs local table, we use it in `stateproof` on the REST side, and in `account` and `block` on the Rosetta side.  We only join on that table once, in `selectGenesis` on the `block` API.  The table is 25 GB in mainnet already.  My instinct is to make it a local table.

2021-11-15 19:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('account_balance_file', 'node_account_id', colocate_with => 'entity');
I don't think we'll store the bytes of account balance files, at least for quite some time.

Making it a reference table and duplicate it on every worker nodes makes finding a particular account balance file timestamp fast imo. For instance, we have the following query in `accounts.js`:

```sql
select ...
from (
  select ...
  from (
    (
      select ...
      from entity
      where type = 'ACCOUNT'
      order by id asc
    )
    union all
    (
      select ...
      from contract
      order by id asc
    )
  ) e
  order by id asc
  limit 25
) e
full outer join (
  select *
  from account_balance ab
  where ab.consensus_timestamp = (select max(consensus_timestamp) from account_balance)
  order by account_id asc
  limit 25
) ab
  on ab.account_id = e.id
order by coalesce(ab.account_id, e.id) asc
limit 25
````

In the account_balance subquery, we get the max account balance consensus_timestamp by `select max(consensus_timestamp) from account_balance`. Will this not be a performance issue with citus when `account_balance` is sharded?

On the other side, if `account_balance_file` is a reference table, and we instead use `select max(consensus_timestamp) from account_balance_file`, I do see the subquery can run just on each worker node.

2021-11-15 21:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('account_balance_file', 'node_account_id', colocate_with => 'entity');
It wasn't a problem for the 10k and 15kTPS, however, it's definitely a flow that can be optimized.
Since the balance file is stale/valid for 15 mins another option that I've considered is to add a view that re-runs every balance file parse. That way some stats on the file could be preserved e.g. max_consensus_timestamp.
Another option is to explore _history flow on the `account_balance_file` table. In which case this query would always be quick and less impacted by age of the ledge

Notably, I'm agreed on the benefits as a reference table. 
I'm just wondering about us or runners of the mirror node  storing the bytes and how that impacts the assumption.
I think moving from reference table to distributed table isn't a big deal though, so we can start there and move to distributed when/if we're more certain.

2021-11-15 22:03 UTC, steven-sheehy requested changes

2021-11-15 22:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'contract');
I think it should be entity as well. Every contract call I see on mainnet has an account for its payer_account_id, not a contract. So hash(contract.id) and hash(contract_*.payer_account_id) will not have much hash range overlap and related rows will cross network boundaries.

2021-11-15 22:49 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> -    on account_balance_file (name, consensus_timestamp desc);
Put back now that reference table

2021-11-15 22:52 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +-- Keep record_file as a local table.
Undo

2021-11-15 22:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('account_balance_file', 'node_account_id', colocate_with => 'entity');
Made it a reference table for the time being.

2021-11-15 22:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'contract');
Changed both back to `entity`, it was my initial thought as well.

2021-11-15 22:59 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('record_file', 'node_account_id', colocate_with => 'entity');
Put it back to a distributed table, distributed column to be fixed in above ticket.

2021-11-15 23:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
>  -------------------
Put the comment back.

2021-11-15 23:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  alter table if exists contract
All checks should be combined with each other and constraints now.

2021-11-15 23:06 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java
> +    private final List<String> v2ConflictIdColumns = List.of(Schedule_.CONSENSUS_TIMESTAMP, Schedule_.SCHEDULE_ID);
Confirmed it can be removed, removed it and put this back.

2021-11-15 23:07 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on account_balance_file (name, consensus_timestamp desc, node_account_id);
Removed here, double-checking all constraints.

2021-11-15 23:08 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create unique index if not exists transaction_signature__timestamp_public_key_prefix
Sure, makes sense.  Removed.

2021-11-15 23:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on record_file (index, node_account_id, consensus_end); -- have to add consensus_end due to partitioning
Removed

2021-11-15 23:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on record_file (hash, node_account_id, consensus_end); -- have to add consensus_end due to partitioning
Removed

2021-11-15 23:12 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on file_data (entity_id, consensus_timestamp, entity_id);
Removed

2021-11-15 23:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on event_file (hash, consensus_end, node_account_id);
Sure, removed the unique constraint and put this back.

2021-11-15 23:13 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint schedule__pk primary key (consensus_timestamp, schedule_id);
Removed

2021-11-15 23:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create index if not exists topic_message__topic_id_timestamp
Yeah, this is where my index knowledge is a little rusty, I thought there may be some benefit to the fact that `topic_id` and `consensus_timestamp` were reversed here.  Anyway, removed.

2021-11-15 23:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create unique index if not exists topic_message__topic_id_seqnum_timestamp
Removed.  Need to rename index and others.

2021-11-15 23:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint token__pk primary key (created_timestamp, token_id);
Removed timestamp.  It also makes sense to remove the index `token__id_timestamp` now that the primary key is `token_id`, right?

2021-11-15 23:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
>  -- Create reference tables for tables used only to describe with rare insert/updates
Add period.

2021-11-15 23:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create index if not exists topic_message__topic_id_timestamp
Oh, yeah order does matter. I misread their order initially, I guess.

2021-11-15 23:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>      on file_data (entity_id, consensus_timestamp);
Now a dupe, remove.

2021-11-15 23:49 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>      on file_data (entity_id, consensus_timestamp);
Undo, not a dupe.

2021-11-16 00:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'contract');
Note, past contract calls are not indicative of Smart Contract 2.0  usage. 
The past excluded DEX and other Defi scenarios where contracts do a lot of the work.
Nonetheless, I'm okay with this for now, especially since `ContractFunctionResult` is limited to 1 for each `ContractCall/ContractCreate`. 

If internal transactions ever show up as `ContractFunctionResult` the above will need to be revisited.

2021-11-16 01:02 UTC, Nana-EC approved these changes
Looks good.

I think we should think on the contract metadata table distributions, especially given actual query usage based on REST API and allow Citus to redistribute shards as needed

2021-11-16 01:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'entity');
I won't block this PR as the change is a 2 liner that can be done in the follow up PR's for the REST APIs whiles we think on it

2021-11-16 03:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'entity');
If we distribute on `contract_id` I could see it, some of my confusion was distributing on `payer_account_id` and then colocating with `contract`.  I can add a TODO comment if we want to flag it for further investigation, or we can just have it as part of a different ticket to look into more.

2021-11-16 03:19 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_reference_table('account_balance_file');
Sure, done.

2021-11-16 03:19 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create unique index if not exists topic_message__topic_id_seqnum_timestamp
Renamed index

2021-11-16 04:00 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  alter table if exists contract
Actually, should have tested this before, this doesn't work.  Results in the following error (an example):
```
ERROR: cannot execute ADD CONSTRAINT command with other subcommands 
...
alter table if exists entity_history
    add constraint entity_history__pk primary key (id, timestamp_range),
    add constraint entity_history__type_check
        check (type <> 'CONTRACT')
```

2021-11-16 16:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'entity');
Yeah, lots of options to get confused over. This PR has #3 highlighted below.
The distribution on `payer_account_id` is mostly for the fact that there are cases where we want to join with transaction table. It helps if they are usually equal but is not a requirement.

We have some flexibility.
1. distribute on `payer_account_id`, colocate with `transaction` since `contract_result` and company are more related to transactions/transfers than the entity `contract`. Db nodes will now have contract executions and the transaction rows on the same nodes. On joins do where `transaction.entity_id` = `contract_result.conract_id`. Groupings
2. distribute on `contract_id` and colocate with `contract`. Db nodes will now have contract executions and the contract row on the same nodes. On joins do where `transaction.entity_id` = `contract_result.conract_id`. This is useful when pulling entity info for a transfer which we won't do much under the contract metadata APIs 
3. distribute on `payer_account_id` and colocate with `entity`. Db nodes will now have contract executions funded by a payer on the same nodes as the payers entity row. I honestly still don't see this one much because there's no scenario where we need to pull more info about the payer which isn't an CONTRACT type. 

My preference is in the above order honestly. I'll create a ticket to revisit this the next sprint. The REST API's will build on this per description in the design doc.

2021-11-16 16:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('contract_result', 'payer_account_id', colocate_with => 'entity');
Recaptured above in #2867 so you don't have to worry about it here.

2021-11-16 17:20 UTC, Nana-EC approved these changes
Looks good

2021-11-16 17:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +set local citus.multi_shard_modify_mode to 'parallel';
We probably don't want to do this since it means every migration that adds an index will do this workaround.
Not noting as an item to fix but just something we can think of

2021-11-16 17:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create unique index if not exists topic_message__topic_id_seqnum_timestamp
timestamp is still in the index name `topic_message__topic_id_seqnum_timestamp`

2021-11-16 17:30 UTC, xin-hedera submitted a review, later dismissed
LGTM

just the inconsistent index name `topic_message__topic_id_seqnum_timestamp` and its columns (topic_id, sequence_number)

2021-11-16 17:53 UTC, ijungmann commented
> LGTM
> 
> just the inconsistent index name `topic_message__topic_id_seqnum_timestamp` and its columns (topic_id, sequence_number)

Went ahead and fixed, good catch.

2021-11-16 18:06 UTC, xin-hedera approved these changes
LGTM

2021-11-16 18:19 UTC, Nana-EC approved these changes

2021-11-16 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on account_balance_file (name, consensus_timestamp desc, node_account_id);
We should still remove `consensus_timestamp` from this index even if a reference table. That's the way it is in v1.

2021-11-16 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint token__pk primary key (created_timestamp, token_id);
Right

2021-11-16 22:00 UTC, ijungmann commented
The tests seem to run significantly slower now, I'm running the importer tests locally and they're running up on 30 minutes...

2021-11-16 22:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on event_file (hash, consensus_end, node_account_id);
It still contains consensus_end, which is leftover from timescaledb

2021-11-16 23:06 UTC, steven-sheehy requested changes

2021-11-16 23:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create index if not exists transaction__payer_account_id
Drop consensus_timestamp from transaction_type index as leftover

2021-11-16 23:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +create unique index if not exists record_file__hash_node
Think we can remove unique from this and the index above it and drop node_account_id

2021-11-16 23:17 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenUpsertQueryGeneratorV2Test.java
> +@ActiveProfiles(profiles = "v2")
Right, had this on locally and didn't mean to push.  Still think the tests are much slower, it's the v2 tests that are timing out, but I've removed these tests and will see how the timing looks now.

2021-11-16 23:17 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/NftUpsertQueryGeneratorV2Test.java
> +                "on conflict (token_id, serial_number) do nothing";
Yeah, removed.

2021-11-16 23:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint schedule__pk primary key (schedule_id);
Removed.

2021-11-16 23:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/NftUpsertQueryGenerator.java
> +    private final List<String> v2ConflictIdColumns = v1ConflictIdColumns;
Removed.

2021-11-16 23:21 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>      on account_balance_file (name, consensus_timestamp desc);
Dropped

2021-11-16 23:22 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>  create index if not exists transaction__payer_account_id
Dropped

2021-11-16 23:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +create unique index if not exists record_file__hash_node
Done for both.  Also removed from `event_file` as that was also a leftover

2021-11-17 15:57 UTC, ijungmann commented
Looking into the REST v2 tests now that they actually finish, looks like `/accounts` has some query issues.

2021-11-17 19:09 UTC, xin-hedera requested changes

2021-11-17 19:09 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    select ${entityIdField} id, ${entityAndBalanceFields}
can you undo these reformatting? it's difficult to review

2021-11-18 04:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +execute format(''delete from address_book_entry'');
Looking for better ways to do this, but this is the only foreign key that has to be handled first

2021-11-18 04:30 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +declare
Formatting..

2021-11-18 04:31 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +    execute format(''delete from %s'', t.table_name);
Truncate right now is really slow on distributed tables in Citus 
https://github.com/citusdata/citus/issues/2630

2021-11-18 04:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +execute format(''delete from address_book_entry'');
Can probably just drop the foreign key on v2. Maybe also on v1. Not like we use foreign keys anywhere else.

2021-11-18 04:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +where table_schema = ''public'' and table_name !~ ''.*(flyway|transaction_type|transaction_result|citus_|_\d+).*'' and table_type <> ''VIEW''
We forgot to remove transaction_type and transaction_result here

2021-11-18 16:24 UTC, ijungmann commented on hedera-mirror-rest/accounts.js
> +    select ${entityIdField} id, ${entityAndBalanceFields}
Should be fixed, I will go through and try to fix my formatting settings today.

2021-11-18 16:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +where table_schema = ''public'' and table_name !~ ''.*(flyway|transaction_type|transaction_result|citus_|_\d+).*'' and table_type <> ''VIEW''
Fixed in both

2021-11-18 16:26 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +execute format(''delete from address_book_entry'');
I'll check that after the tests run, I think the only real issue was a migration test that was running a pretty old migration (1.37), I altered that test to drop the fk.

2021-11-18 19:36 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +where table_schema = ''public'' and table_name !~ ''.*(flyway|transaction_type|transaction_result|citus_|_\d+).*'' and table_type <> ''VIEW''
In GRPC we should be fine, the Importer cleanup I think we're going to be stuck with at least `transaction_type` because we have a migration test that needs it (`RemoveInvalidEntityMigrationTest`)

2021-11-18 19:55 UTC, ijungmann commented on hedera-mirror-rest/accounts.js
> -        (select jsonb_agg(
The spec tests all failed with something like `Subqueries without a FROM clause can only do basic operations`.  Didn't notice any issues with tests after removing it.

2021-11-18 19:56 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +                 where table_schema = ''public'' and table_name !~ ''.*(flyway|transaction_type|citus_|_\d+).*'' and table_type <> ''VIEW''
`t_transaction_types` is used in multiple tests under `RemoveInvalidEntityMigrationTest`, so if we delete them those tests fail.

2021-11-18 19:58 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
> +                        "address_book_entry_consensus_timestamp_fkey");
We have a foreign key here which causes havoc in this test (and only this test) when trying to cleanup, so manually removing the foreign key here.

2021-11-18 20:11 UTC, ijungmann commented
Rosetta also fails from the foreign key constraint.  Adding a migration to drop it.

2021-11-18 20:27 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
> +                        "address_book_entry_consensus_timestamp_fkey");
Still need this even with the migration, as this test stops migrating before the drop.

2021-11-18 20:49 UTC, ijungmann commented on hedera-mirror-rest/accounts.js
> +        (jsonb_agg(
Remove extra set of ()

2021-11-18 21:15 UTC, steven-sheehy approved these changes

2021-11-19 16:21 UTC, Nana-EC approved these changes

2021-11-19 16:47 UTC, xin-hedera approved these changes
LGTM

2021-11-19 17:07 UTC, merged