Support CryptoCreateTransaction in Rosetta
hashgraph/hedera-mirror-node pull request #2875
Opened 2021-11-17 16:17 UTC by xin-hedera

**Description**:

This PR adds support of CryptoCreateTransaction to rosetta Construction API

- Add new cryptocreate transaction constructor handler
- Limit go test coverage report generation to packages in /app

**Related issue(s)**:

Fixes #2860 

**Notes for reviewer**:

Passed end to end test for cryptocreate transaction with the new bdd test client.

Note in `/construction/submit`, the implementation does not try to get transaction receipt so as to return any new entity / confirmation to the client. This means for CryptoCreate, a client has to query rosetta DATA api to find the executed transaction and the new account ID in it. Getting transaction receipt will block the rosetta `/construction/submit` and it's against the rosetta spec:

```
/construction/submit
Submit a Signed Transaction

Submit a pre-signed transaction to the node. This call should not block on the transaction being included in a block. Rather, it should return immediately with an indication of whether or not the transaction was included in the mempool. The transaction submission response should only return a 200 status if the submitted transaction could be included in the mempool. Otherwise, it should return an error.
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-11-17 16:20 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/transaction.go
> +		metadata = map[string]interface{}{"entity_id": t.EntityId.String()}
shows the entity id of a transaction in the `metadata` map. Doing so allows a client to find the newly created account ID.

2021-11-17 16:26 UTC, xin-hedera commented on hedera-mirror-rosetta/main.go
> +			return "", fmt.Sprintf("%s:%d", relativeFilepath, frame.Line)
add caller filepath:lineno to the log:

```
time="2021-11-17T10:18:11-06:00" level=info msg="hedera-mirror-rosetta version development, rosetta api version 1.4.10" file="/main.go:165"
time="2021-11-17T10:18:11-06:00" level=info msg="Successfully connected to database" file="/app/db/db.go:40"
time="2021-11-17T10:18:11-06:00" level=info msg="Use testnet instead of demo" file="/app/services/construction_service.go:292"
time="2021-11-17T10:18:11-06:00" level=info msg="Serving Rosetta API in ONLINE mode" file="/main.go:205"
time="2021-11-17T10:18:11-06:00" level=info msg="Listening on port 5700" file="/main.go:218"
```

2021-11-18 23:36 UTC, steven-sheehy requested changes

2021-11-18 23:36 UTC, steven-sheehy commented on hedera-mirror-rosetta/main.go
> +			return "", fmt.Sprintf("%s:%d", relativeFilepath, frame.Line)
Is there a reflection penalty for this information like there is in Java? From the docs `Note that this does add measurable overhead - the cost will depend on the version of Go, but is between 20 and 40% in recent tests with 1.6 and 1.7. You can validate this in your environment via benchmarks:`. I would say make it an option that's turned off by default.

2021-11-19 15:25 UTC, xin-hedera commented on hedera-mirror-rosetta/main.go
> +			return "", fmt.Sprintf("%s:%d", relativeFilepath, frame.Line)
seems to have ~50% overhead with go1.17, so will conditionally turn in on when logLevel >= DEBUG

2021-11-19 15:42 UTC, steven-sheehy approved these changes
LGTM

2021-11-19 16:17 UTC, ijungmann requested changes
Giving a quick second pass to the `crypto_create_transaction_constructor.go`, everything looks good except for one nit.

2021-11-19 16:17 UTC, ijungmann commented on hedera-mirror-rosetta/app/services/construction/token_update_transaction_constructor_test.go
> +	adminKeyStr           = "302a300506032b6570032100d619a3a22d6bd2a9e4b08f3d999df757e5a9ef0364c13b4b3356bc065b34fa01"
nit: Out of order

2021-11-19 16:18 UTC, ijungmann approved these changes
Won't hold up the PR for a nit.

2021-11-19 16:20 UTC, Nana-EC approved these changes
LGTM.
Minor non blocking organizational nit if you pass back

2021-11-19 16:22 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/token_update_transaction_constructor_test.go
> +	adminKeyStr           = "302a300506032b6570032100d619a3a22d6bd2a9e4b08f3d999df757e5a9ef0364c13b4b3356bc065b34fa01"
will address it in the bdd-client PR

2021-11-19 16:22 UTC, xin-hedera commented on hedera-mirror-rosetta/app/interfaces/transaction.go
> +	IsFrozen() bool
will address it in the bdd-client PR

2021-11-19 16:22 UTC, merged