Rosetta bdd client
hashgraph/hedera-mirror-node pull request #2878
Opened 2021-11-19 21:46 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Relates to #2872

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-22 23:20 UTC, Nana-EC requested changes
1st pass, will circle back.
Missing documentation of bdd tests runs and configurations

2021-11-29 17:21 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction_service.go
> +	online             bool
sure

2021-11-29 17:27 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +          OFFLINE_CONTAINER_ID=$(docker run -d -e MODE=offline -e NETWORK=testnet \
yes we should. the bigger change is I need to extract the all-in-one docker image steps into its own job, upload it as an artifact so as to share it with the validation job which now has a matrix.

2021-11-30 18:29 UTC, ijungmann submitted a review, later dismissed
LGTM

2021-11-30 21:00 UTC, Nana-EC submitted a review, later dismissed
LGTM

2021-11-30 21:45 UTC, xin-hedera commented on hedera-mirror-rosetta/test/bdd-client/scenario/crypto.go
> +	ctx.Step("I send a CryptoCreate transaction to network", crypto.iSendCryptoCreateTransaction)
they don't have to. i just followed the naming scheme of the examples in `godog` repo

2021-12-01 02:19 UTC, steven-sheehy requested changes

2021-12-01 02:19 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        online-only: ['true', 'false']
```suggestion
        mode: ['online', 'offline']
```

Then you can pass this to docker run with `-e MODE=${{ matrix.mode }}`

2021-12-01 02:19 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +          ONLINE_CONTAINER_ID=$(docker run -d -e HEDERA_MIRROR_IMPORTER_STARTDATE=$STARTDATE \
This isn't making good use of the job matrix. It should only have a single docker run step and no if conditionals.

2021-12-01 15:12 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +        online-only: ['true', 'false']
rosetta-cli validation requires at least the online rosetta server. rosetta-cli validation also support interacting with an additional offline mode rosetta server mainly for Construction API endpoints which do not require online interactions.

so the testing matrix is correct:

- online-only 'true', there is a single online mode rosetta server, and we use the online server URL as the `offline_url` for rosetta-cli validation
- online-only 'false', one online mode rosetta server and one offline mode rosetta server, the urls for rosetta-cli are configured correspondently

if we only spin up an offline mode rosetta server, there is no way to validate either DATA or Construction APIs.

2021-12-01 15:16 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +        if: steps.changed-files-module.outputs.any_changed == 'true'
the concern here is the bdd tests may cost a lot more once we add the token tests. and if it runs in every PR, we may exhaust the fund of the two accounts.

the rosetta-cli DSL based crypto transfer won't cause such issue because it's just crypto transfers between the two accounts and every time the sender chosen for a crypto transfer is the account with higher balance.

2021-12-01 17:10 UTC, xin-hedera commented
importer github workflow jobs are failing because the 0.21.0-SNAPSHOT hedera-protobuf-java-api  aritifact is just updated with the new `nonce` field in `TransactionID`. will create a separate PR to fix it.

2021-12-01 19:26 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        online-only: ['true', 'false']
I still don't think this is an appropriate approach. Tests should model how the server will be used in production. No one will be running both an online and offline server simultaneously in production. The rosetta-cli supports testing just construction, just data, or both. Why can't we always run the construction tests and conditionally run data if online?

2021-12-01 20:06 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> +        online-only: ['true', 'false']
agree that we should model what's being used in production. and in fact, a paired online mode and offline mode servers are closer to what exchanges will use in production. According to [rosetta spec](https://www.rosetta-api.org/docs/construction_api_introduction.html#flow-of-operations), for construction API, only `/construction/metadata` and `/construction/submit` are marked with `online`.

on the other hand, we also need to test with online only mode so as to make sure the APIs which are supposed to work in both modes meet the expectations.

2021-12-02 16:05 UTC, steven-sheehy commented on .github/workflows/rosetta-api.yml
> +        online-only: ['true', 'false']
Ok, I wish the rosetta-cli could test the online and offline modes in isolation but seems that's not the case. So I'm fine with the approach.

2021-12-02 16:05 UTC, steven-sheehy approved these changes

2021-12-02 16:43 UTC, ijungmann approved these changes

2021-12-02 16:45 UTC, merged