Add List contract results REST API
hashgraph/hedera-mirror-node pull request #2880
Opened 2021-11-20 02:44 UTC by Nana-EC

**Description**:
As a user I would like to query the mirror node to see the results of my contract call.

- Add `services` dir to contain services
- Add `baseService` with shared service loigc
- Add `routes` dir to contain url routing logic from server to controller
- Add `contractRoute` to handle contracts mapping
- Add `controllers` dir to contain all controller logic to handle requests and call service
- Add `contractController.js` to replace `contract.js`
- Add server support for `api/v1/contracts.:contractId/results` endpoint
- Add spec tests

**Related issue(s)**:

Fixes #2868 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-22 21:46 UTC, ijungmann reviewed
Will give a second pass, didn't see anything notable.  I like the new Controllers

2021-11-22 23:47 UTC, ijungmann approved these changes

2021-11-22 23:48 UTC, ijungmann commented
Tests are failing however

2021-11-23 16:54 UTC, steven-sheehy requested changes

2021-11-23 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "to": null
I believe `to` should always be populated with the contract ID

2021-11-23 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "gas_used": "10",
Should be numbers

2021-11-23 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "amount": "50",
number

2021-11-23 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "function_parameters": "0x34613561643531346630393537666131373061363736323130633962646264646633626339353139373032636639313566613637363761343034363362393666",
Maybe either provide as input or choose a smaller default hardcoded string.

2021-11-23 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-01-specific-id.spec.json
> +        "bloom": null,
We should populate all fields with non-null values for at least one test case. If the field can't be populated because it isn't implemented it should be removed from the code.

2021-11-23 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
> +    "/api/v1/contracts/5001/results?from=9001"
Should we support an optional hex encoded `from` address when it has a `0x` prefix?

2021-11-23 17:49 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +  async getContractResultsByIdAndFilters(whereConditions = [], whereParams = [], order = 'desc', limit = defaultLimit) {
Yes, this is the intermediate flow I mentioned as a compromise for now.
Exactly as you said, didn't want to create too much more code churn and wanted to get this in so the other PR's can utilize the new structure

2021-11-23 17:50 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (displayAdditionalInfo) {
Will remove

2021-11-23 17:52 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
> +    "/api/v1/contracts/5001/results?from=9001"
Yeah was thinking on this. Otherwise there's a mismatch of input and output format.
Will add

2021-11-23 22:24 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    logger.trace(`getContractResultsByIdAndFilters query: ${query}, params: ${params}`);
Considered that but wanted to preserve the method name.
I usually shy way from passing calling function names but we can do it in this case

2021-11-24 01:28 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    logger.trace(`getContractResultsByIdAndFilters query: ${query}, params: ${params}`);
Pulled up :) 
Let me know if you want to drop the function name also

2021-11-24 01:29 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (displayAdditionalInfo) {
Removed

2021-11-24 01:29 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      child_transactions: null,
Omitted

2021-11-24 01:29 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> + * Contract view model
Updated

2021-11-24 01:29 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  let order = constants.orderFilterValues.ASC;
Flipped to `DESC`

2021-11-24 01:30 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +    throw new NotFoundError();
Updated

2021-11-24 01:31 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  const conditions = [`${ContractResult.getFullName(ContractResult.CONTRACT_ID)} = $1`];
Migration with index added

2021-11-24 01:31 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "to": null
Updated, was mapping to `contract_id` hence it didn't pick up

2021-11-24 01:31 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "gas_used": "10",
Updated

2021-11-24 01:31 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "amount": "50",
Updated

2021-11-24 01:34 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
> +        "function_parameters": "0x34613561643531346630393537666131373061363736323130633962646264646633626339353139373032636639313566613637363761343034363362393666",
Updated to smaller default hardcoded string

2021-11-24 01:35 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-01-specific-id.spec.json
> +        "bloom": null,
Updated

2021-11-24 01:35 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
> +    "/api/v1/contracts/5001/results?from=9001"
Updated OpenAPI spec for this and will add the actual logic shortly

2021-11-24 04:04 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
> +    "/api/v1/contracts/5001/results?from=9001"
Added

2021-11-24 15:50 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +    logger.trace(`getContractResultsByIdAndFilters query: ${query}, params: ${params}`);
`log4js` does have the `enableCallStack` option so you can add the filename and line to the logs, but it will be very slow due to generating an `Error` and inspecting its call stack for every log event.

2021-11-24 18:25 UTC, steven-sheehy requested changes

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-03-timestamp.spec.json
> +    "/api/v1/contracts/5001/results?timestamp=987654.000123456"
We don't need to vary the URL for different entity ID formats. It makes it hard to understand what change we are testing. We only need to do that in one test case (the first). Same comment for other specs.

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-03-timestamp.spec.json
> +    "/api/v1/contracts/0.0.5001/results?timestamp=987654.000123456",
Add extra URLs for gt, gte, lt, lte, eq, ne

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-01-specific-id.spec.json
> +        "created_contract_ids": ["0.0.7001"],
We had discussed it at one point but guess it never made its way into the design. Should we add a non-solidity `contract_id: "0.0.x"`?

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +            value: '1000',
Should add solidity format

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: number
We should add `nullable: true` to most of these

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The
Missing description. Should mention hex-encoded

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "0x2b048531b38d2882e86044bc972e940ee0a01938"
Mention hex-encoding in description for this and other relevant fields

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "3999999999999999949"
Put a useful example error message

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: number
Number includes floating point
```suggestion
          type: int64
```

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: integer
`gas_limit` and `gas_used` are modeled as bigints so we should set them similarly
```suggestion
          type: int64
```

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        $ref: '#/components/schemas/EvmAccount'
Can we use a `oneOf` instead with the existing `SolidityAddress` and `EntityId`? Would need to add pattern to `SolidityAddress`

2021-11-24 18:25 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      amount: Number(contractResult.amount),
```suggestion
      amount: BigInt(contractResult.amount),
```

2021-11-24 18:31 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
> +    "/api/v1/contracts/5001/results?from=9001"
Added a separate spec, missed pushing it

2021-11-24 18:32 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
> +    "/api/v1/contracts/5001/results?from=9001"
Pushed this time

2021-11-25 05:03 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +    Number.parseInt(account.slice(10, 26), 16), // realm
Added tests for this and more

2021-11-25 05:33 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +            value: '1000',
The main E2E controller call is covered by the integration.test.js.
The query params to filters object is covered by the `utils` and `utilsFilters` tests
This flow adds coverage for the logic post query formatting but before service call, so by this stage the solidity address is already an entityId

2021-11-25 06:09 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        $ref: '#/components/schemas/EvmAccount'
Updated

2021-11-25 06:09 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: integer
Updated with
```         
          format: int64
          type: integer
```

2021-11-25 06:09 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: number
Updated

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "3999999999999999949"
Updated

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "0x2b048531b38d2882e86044bc972e940ee0a01938"
Added to `call_result` and `function_parameters`

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The
Updated

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: number
Added

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-01-specific-id.spec.json
> +        "created_contract_ids": ["0.0.7001"],
Do you mean just restating the contractId specified in the url?
Yeah we can add that.

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-01-specific-id.spec.json
> +        "created_contract_ids": ["0.0.7001"],
Added and updated design doc

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-03-timestamp.spec.json
> +    "/api/v1/contracts/0.0.5001/results?timestamp=987654.000123456",
Added

2021-11-25 06:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-03-timestamp.spec.json
> +    "/api/v1/contracts/5001/results?timestamp=987654.000123456"
Simplified

2021-11-25 06:11 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +      ret = EntityId.isValidContractAccount(val);
Updated

2021-11-25 06:11 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +    if (isValidSolidityAddress(id)) {
Updated and simplified to throw on no match

2021-11-25 06:11 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +  // Accepted forms: shard.realm.num, realm.num, or encodedId
Updated

2021-11-25 06:11 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +  return typeof address === 'string' && /^0x[A-Fa-f0-9]{40}$/.test(address);
Moved to class constants

2021-11-25 06:11 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      created_contract_ids: contractResult.createdContractIds,
Updated

2021-11-25 06:11 UTC, Nana-EC commented on hedera-mirror-rest/service/baseService.js
> +  async getRows(query, params, functionName = '') {
Updated

2021-11-25 06:17 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      amount: Number(contractResult.amount),
We actually currently don't do this anywhere and we've discussed a bit offline the issue around this for number that are beyond the integer max.
The only reliable way to represent those would be as Strings.
Will circle back though

2021-11-25 06:23 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      amount: Number(contractResult.amount),
Notably JSON stringily will throw an error for Bigints - [Bigint within json](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json)
Express response handler uses this flow and results in the said issue.
Again, workaround is to represent large int as string  in those cases.

2021-11-29 16:42 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    "version": "8.1.0",
Why are we upgrading to 8.10 while the java components are still on 7.7.3?

2021-11-29 16:42 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    const flywayConfigPath = path.join(flywayDataPath, `config_${dbconfig.dbSessionConfig.port}.json`);
We should use a tmp file that gets auto cleaned up.

2021-11-29 17:53 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    "version": "8.1.0",
Initially I thought it was the flyway version contributing to the CI issues so tried this.
Will revert to 7.7.3 for consistency

2021-11-29 18:20 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    const flywayConfigPath = path.join(flywayDataPath, `config_${dbconfig.dbSessionConfig.port}.json`);
Can do.
Will leave the flyway db download though so that it saves time between runs and isn't downloading for every integration class

2021-11-29 21:38 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> -    if (num > maxNum || realm > maxRealm || shard > maxShard) {
Could always go back to this layout and just do an annoying BigInt cast on `shard`, `realm` and `num`

2021-11-29 21:40 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> -    if (num > maxNum || realm > maxRealm || shard > maxShard) {
i.e.
```javascript
if (isValidEntityId(id)) {
      [shard, realm, num] = id.includes('.') ? parseFromString(id) : parseFromEncodedId(id, error);
      if (BigInt(num) > maxNum || BigInt(realm) > maxRealm || BigInt(shard) > maxShard) {

      }
    } else if (isValidSolidityAddress(id)) {
      [shard, realm, num] = parseFromSolidityAddress(id);
      if (BigInt(num) > maxSolidityRealmNum || BigInt(realm) > maxSolidityRealmNum || BigInt(shard) > maxSolidityShard) {
        throw error();
      }
    } else {
      throw error();
    }
```

2021-11-29 21:44 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    "version": "8.1.0",
Reverted

2021-11-29 21:44 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    const flywayConfigPath = path.join(flywayDataPath, `config_${dbconfig.dbSessionConfig.port}.json`);
Updated

2021-11-29 22:25 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
> -    if (num > maxNum || realm > maxRealm || shard > maxShard) {
do you mean without the casting sona also reports code smell on `num > maxNum`?

2021-11-29 22:41 UTC, steven-sheehy approved these changes
Only outstanding item is question of sorting contract list API

2021-11-29 22:50 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> -    if (num > maxNum || realm > maxRealm || shard > maxShard) {
Yes without the casting. That's what I ended up doing

2021-11-29 22:51 UTC, Nana-EC commented
> Only outstanding item is question of sorting contract list API

I can try and address that in the next 2 PRs. If it causes lots of refactoring it'll go in a separate PR.
I'll open a ticket

2021-11-29 23:05 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: listContractResultss
nit:
```suggestion
      operationId: listContractResults
```

2021-11-29 23:12 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: listContractResultss
Updated

2021-11-30 16:29 UTC, xin-hedera requested changes

2021-11-30 16:29 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: Returns a list of all contract results for a contracts function executions.
```suggestion
      description: Returns a list of all contract results for a contract function executions.
```

2021-11-30 16:29 UTC, xin-hedera commented on hedera-mirror-rest/service/baseService.js
> +    });
better not mix async / await and thenable:

```suggestion
   const {rows} = await pool.queryQuietly(query, params);
   logger.trace(`${functionName} ${rows.length} entries`);
   return result.rows;
```

2021-11-30 17:42 UTC, ijungmann requested changes
A couple openApi notes

2021-11-30 17:42 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        created_contract_ids:
Missing the `contract_id` field that was recently added.

2021-11-30 17:42 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: true
Would we have a null value or just an empty list?

2021-11-30 19:06 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: true
Not a blocker, just curious.

2021-11-30 19:19 UTC, Nana-EC commented on hedera-mirror-rest/routes/contractRoute.js
> +const path = '/api/v1/contracts';
So that's how I had it initially however that results in the controller not being aware of the path `api/v1` when it creates the `next` links value in the response.
Hence this approach and the comment.
I didn't want to hardcode api version path into the controllers since they shouldn't be aware of that internally.

2021-11-30 19:19 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integration.test.js
> +
Can update and change it to `.spec.json`

2021-11-30 19:34 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +const closeConnection = async (dbconfig) => {
Wanted to make it different from the class variable. Will just give it a different name to avoid the confusion

2021-11-30 19:55 UTC, xin-hedera commented on hedera-mirror-rest/routes/contractRoute.js
> +const path = '/api/v1/contracts';
combining `req.baseUrl` and `req.path` should give us the full request path from the root. we can address it later.

2021-11-30 20:07 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: true
Good point. It started as nullable. In the response it's not an empty array of none. Will update

2021-11-30 20:16 UTC, Nana-EC commented on hedera-mirror-rest/service/baseService.js
> +    });
I believe I had this initially as you stated and addressed feedback to make it thenable.
Can revert

2021-11-30 20:30 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: true
Updated

2021-11-30 20:30 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        created_contract_ids:
Added

2021-11-30 20:30 UTC, Nana-EC commented on hedera-mirror-rest/service/baseService.js
> +    });
Reverted

2021-11-30 20:31 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    return _.isEmpty(rows) ? null : rows.map((cr) => new ContractResult(cr));
Updated but now to an isEmpty check to avoid running the links.next logic unnecessarily

2021-11-30 20:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: Returns a list of all contract results for a contracts function executions.
Modified

2021-11-30 20:32 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-04-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id with a timestamp filter with no matching results",
Updated

2021-11-30 20:32 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    await integrationDomainOps.addContractResult({
Updated

2021-11-30 20:32 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +// set timeout for beforeAll to 2 minutes as downloading docker image if not exists can take quite some time
Updated

2021-11-30 20:32 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +const closeConnection = async (dbconfig) => {
Updated

2021-11-30 20:33 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integration.test.js
> +
Updated

2021-11-30 20:33 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +  return typeof address === 'string' && solidityAddressRegex.test(address);
Updated

2021-11-30 20:33 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +const maxSolidityRealmNum = 18446744073709551616n; // ffffffffffffffff in hex
Updated

2021-11-30 20:37 UTC, xin-hedera commented on hedera-mirror-rest/service/baseService.js
> +    });
yup. it still returns a promise. from a caller's pointer of view, there's no difference. however `await` makes the code more readable since it just looks like sync code.

2021-11-30 20:38 UTC, Nana-EC commented on hedera-mirror-rest/entityId.js
> +const {typeOf} = require('mathjs');
Removed

2021-11-30 20:38 UTC, ijungmann submitted a review, later dismissed

2021-11-30 20:41 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: true
It can be null as the database definition makes clear. There are null rows in production.

2021-11-30 20:49 UTC, Nana-EC commented on hedera-mirror-rest/routes/contractRoute.js
> +const path = '/api/v1/contracts';
This is already the logic used. Unfortunately I believe the express route truncates those details.
Will revisit in the next PR as you noted in case things have changed across my iterations

2021-11-30 21:30 UTC, steven-sheehy requested changes

2021-11-30 21:59 UTC, xin-hedera approved these changes
LGTM

2021-11-30 22:24 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/SolidityAddress'
Correction `from` is the payer, which will never be null actually.
`contract_id` and therefore `to` can be null.
Will update that

2021-11-30 22:32 UTC, steven-sheehy approved these changes

2021-11-30 22:42 UTC, merged