Add ECDSA (secp256k1) support
hashgraph/hedera-mirror-node pull request #2892
Opened 2021-11-22 22:27 UTC by steven-sheehy

**Description**:
- Add support for ECDSA (secp256k1) keys and signatures
- Add a `RecordItemBuilder` for reusable protobuf construction in tests
- Add a `type` column to the transaction signature table and schedule REST API
- Add support for an optional `0x` prefix when searching REST API by public key
- Change Rosetta API to fail if a non-ED25519 signature is provided
- Change transaction signature parsing to not fail on unsupported or unknown types
- Fix REST API not searching by key lists or threshold keys with one primitive key
- Remove unused shard/realm/num entity index
- Remove unused token `key_ed25519_hex` columns

**Related issue(s)**:

Fixes #2876 

**Notes for reviewer**:
We should add ECDSA (secp256k1) signature support to Rosetta once the Go SDK supports it

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-11-23 21:49 UTC, Nana-EC reviewed
Initial thoughts, need to circle back to cover some of the longer files

2021-11-23 22:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .returns(logInfo.getBloom().toByteArray(), ContractLog::getBloom)
I fixed a bug here. It was comparing against the result bloom and not the log bloom. It only happened to work before since we hardcoded them to the same array, but that can no longer be relied upon since I switched some to use DomainBuilder with random values.

2021-11-23 22:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            int type = signaturePair.getSignatureCase().getNumber();
Done

2021-11-23 22:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    for (Map.Entry<Integer, UnknownFieldSet.Field> entry : unknownFields.entrySet()) {
Can do. I tested it against a ECDSA generated key hex bytes with an earlier protobuf that didn't support ECDSA key and it works.

2021-11-24 16:46 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .returns(logInfo.getBloom().toByteArray(), ContractLog::getBloom)
Sounds good

2021-11-24 18:25 UTC, Nana-EC requested changes
Looks good on 1st full pass. Some nits and clarifications

2021-11-24 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +            var contractFunctionResult = recordBuilder.getContractCallResultBuilder();
`contractFunctionResult` isn't exposed and I wasn't intended to expose sub-TransactionBody protos. The intent here is to remove this `callRecord` and replace it entirely with `RecordItemBuilder` in the future.

2021-11-24 20:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/DomainBuilder.java
> +                .name("Hbars")
Done. Also added pauseStatus

2021-11-24 20:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +            transactionBody.setMemo(type.name());
Done

2021-11-24 20:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.49.1__ecdsa_secp256k1.sql
> +-- Support new primitive key type ECDSA_SECP256K1
Done

2021-11-24 22:47 UTC, Nana-EC requested changes
Looks good. Some final test suggestions and nits.
Also you should update the description with the protobuf version update and any other improvements not mentioned

2021-11-24 22:47 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private static final RealmID REALM_ID = RealmID.newBuilder().setShardNum(0).setRealmNum(0).build();
Realm and shard are `long` so default to 0. Can set them similar to how you do for Treasury
```suggestion
    private static final RealmID REALM_ID = RealmID.newBuilder().build();
```

2021-11-24 22:47 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private static final ShardID SHARD_ID = ShardID.newBuilder().setShardNum(0).build();
```suggestion
    private static final ShardID SHARD_ID = ShardID.newBuilder().build();
```

2021-11-24 22:47 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return Key.newBuilder().setEd25519(bytes(64)).build();
I see the key byte lengths explicitly stated here and in DomainBuilder, instead of referred to.
Might be good to have it specified once and referenced.
Something like the below. The ByteString formats can do the division by 2 where necessary
```java
private final int Ed25519ByteLength = 64;
private final int ED25519DerByteLength = 88;
private final int ECDSAByteLength = 66;
```

2021-11-24 22:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/model/signatureType.test.js
> +    expect(SignatureType.getName(3)).toEqual('ED25519');
Might as well get the full coverage
```suggestion
    expect(SignatureType.getName(2)).toEqual('CONTRACT');
    expect(SignatureType.getName(3)).toEqual('ED25519');
    expect(SignatureType.getName(4)).toEqual('RSA_3072');
    expect(SignatureType.getName(5)).toEqual('ECDSA_384');
    expect(SignatureType.getName(6)).toEqual('ECDSA_SECP256K1');
```

2021-11-24 22:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/model/signatureType.test.js
> +    expect(SignatureType.getName(9999999)).toEqual('UNKNOWN');
Add below value and maybe non integer cases e.g. 
```suggestion
    expect(SignatureType.getName(1)).toEqual('UNKNOWN');
    expect(SignatureType.getName(9999999)).toEqual('UNKNOWN');
    expect(SignatureType.getName('sig')).toEqual('UNKNOWN');
```

2021-11-24 23:01 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/model/signatureType.test.js
> +    expect(SignatureType.getName(9999999)).toEqual('UNKNOWN');
Added those and more

2021-11-24 23:01 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/model/signatureType.test.js
> +    expect(SignatureType.getName(3)).toEqual('ED25519');
Added

2021-11-24 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return Key.newBuilder().setEd25519(bytes(64)).build();
Made a constant. Also corrected this from 64 to 32.

2021-11-24 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private static final ShardID SHARD_ID = ShardID.newBuilder().setShardNum(0).build();
Was being explicit, but switched it to `Shard.getDefaultInstance()`

2021-11-24 23:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private static final RealmID REALM_ID = RealmID.newBuilder().setShardNum(0).setRealmNum(0).build();
Switched it to `RealmID.getDefaultInstance()`

2021-11-24 23:30 UTC, Nana-EC approved these changes
LGTM

2021-11-25 00:21 UTC, merged