OpenApi fixes based on test validation
hashgraph/hedera-mirror-node pull request #2894
Opened 2021-11-22 23:25 UTC by ijungmann

**Description**:
This PR contains OpenApi and test corrections based on the results of the specs tests run with the [openapi-express-validator](https://www.npmjs.com/package/express-openapi-validator)

**Related issue(s)**:

Fixes #2783 

**Notes for reviewer**:
Holding off on pushing the actual validator and logic until I can get it to accept the tests that hit unknown endpoints, for now this is to correct our existing endpoints.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-22 23:27 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +    EntityIdNullable:
OpenApi 3.0 doesn't play well with combining refs and nullable, and the validator ignores nullable and fails the tests.  Putting `nullable` in the base object works, so for now I added a separate object for the nullable.

2021-11-22 23:28 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> -        - nullable: true
Saw some comments about this, but the validator would not accept this either.

2021-11-22 23:29 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> -          format: byte
We allow for utf-8 encoding, so we can't say this is strictly base64.

2021-11-23 03:00 UTC, Nana-EC submitted a review, later dismissed
Looks good.
Suggestion on examples, but non blocking

2021-11-23 04:20 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: "0.1.2"
I don't think this applies. `EntityIdNullable` would only be used in a response and would always return full format.

2021-11-23 17:48 UTC, steven-sheehy requested changes
The ticket was intended to integrate the open api validator permanently into the test framework. So this ticket should either include that work or if you're going to have a follow up to not mark the ticket as being fixed.

2021-11-23 17:48 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> -        - balance
We should probably fix the actual payload to include `balance: null` when `balance=false` instead of omitting the field. Our API always sends all fields everywhere else.

2021-11-23 17:48 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/EntityIdNullable'
I think we should invert this logic. `EntityId` should represent the value in any response and can be nullable. We should add an `EntityIdParam` if it's needed to represent and validate input.

2021-11-23 17:55 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: "0.1.2"
True

2021-11-29 16:24 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/EntityIdNullable'
There are some cases where we know `EntityId` shouldn't be null, such as `token_id` in `/tokens`, which is why I added the distinction, but I can loosen it to make all `EntityIds` nullable. 
Right now I'm only validating the responses with the validator, if we want to validate input I think it will require a lot of refactoring, the validator converts the query params into their proper types (like int) instead of all String as Express does it, and a lot of our utils rely on them all being Strings.  Best left to a new PR if desired.

2021-11-29 16:40 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> -        - balance
Fixed this to show a null `balance` field on false flag.  We could also build the entire object (balance object with balance, timestamp, and empty token_balances array), but went with option 1 for now.

2021-11-29 17:16 UTC, steven-sheehy approved these changes
Looks good, just a nit about naming.

2021-11-29 17:16 UTC, steven-sheehy commented on hedera-mirror-rest/server.js
> +  validateSwaggerDocs(app);
It's not really related to Swagger or docs:

```suggestion
  openApiValidator(app);
```

2021-11-29 17:16 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/EntityIdNullable'
Sure, if we can only validate responses now easily that works for me.

2021-11-29 17:35 UTC, ijungmann commented on hedera-mirror-rest/server.js
> +  validateSwaggerDocs(app);
Yeah, I like that better, fixed.

2021-11-29 17:45 UTC, steven-sheehy approved these changes

2021-11-29 18:28 UTC, Nana-EC approved these changes
LGTM

2021-11-29 23:47 UTC, merged