Add Contract Results by timestamp and transactionId REST API
hashgraph/hedera-mirror-node pull request #2923
Opened 2021-12-02 00:36 UTC by Nana-EC

**Description**:
Smart contract executors need to be able to see their results base don the timestamp and transactionId identifiers.

- Add a `recordFileService.js` to handle recordFile business logic
- Update `contractService.js` to handle contract results identified by timestamp and transactionId business logic. Employ2 calls. One for recordFile (Block) details and a separate but single call for contractResults joined with transaction info
- Update `contractResultsViewModel` to handle additional recordFile and transaction information when supplied
- Update `contractRoute` with 2 new endpoints - `/api/v1/:contractId/results/:consensusTimestamp` and `/api/v1/results/:transactionId`
- Update `contractCOntroller` to support new endpoints and extract `consensusTimestamp` and `transaction` from request
- Update `integrationDomainOps` with support for recordFiles
- Update `contractService.test.js`, `contactController.test.js` with support for new endpoints
- Add new specs files for matching and not found scenarios

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-02 20:26 UTC, xin-hedera requested changes

2021-12-02 20:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    await expect(ContractService.getContractResultsByIdAndTimestamp()).resolves.toEqual(null);
```suggestion
    await expect(ContractService.getContractResultsByIdAndTimestamp(contractId, timestamp)).resolves.toBeNull();
```

2021-12-02 20:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    await expect(ContractService.getContractResultsByIdAndTimestamp(2, 2)).resolves.toMatchObject(
```suggestion
    await expect(ContractService.getContractResultsByIdAndTimestamp(2, 2)).resolves.toEqual(
```

toMatchObject allows the `actual` to be a superset of the `expected`

2021-12-02 20:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +        "hash": "contractRecordHash"
hash should be a hex string since that's what we store in db

2021-12-02 20:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-results-11-transactionid-path.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId",
```suggestion
  "description": "Contract results api call using transactionId",
```

2021-12-02 20:26 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-results-12-transactionid-path-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
```suggestion
  "description": "Contract results api call using transactionId with no file match",
```

2021-12-02 20:26 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      this.block_hash = utils.toHexString(recordFile.hash, true);
`record_file.hash` is in hex, so just need to add the `0x` prefix

2021-12-02 20:28 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +    limit 1`;
don't have to use full column name / table alias

2021-12-02 20:35 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  return EntityId.parse(contractIdString, constants.filterKeys.CONTRACTID).getEncodedId();
No, for the path we've maintained the Hedera styled entityId

2021-12-02 20:37 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  if (!_.isEmpty(response.results)) {
I know. I just wanted to avoid the variable creations and method call if not applicable

2021-12-02 20:40 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  const row = await ContractService.getContractResultsByTransactionId(
I was thinking about this and whether the service code should be aware of anything but model objects.
Initially I had the full object but wanted Service code to just take in basic data types used in the query.
If we position transactionId and entityId as model adjacent objects then I guess we could allow it in.

2021-12-02 20:51 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +    limit 1`;
I know but I like to to ensure future proof of unique column names across tables

2021-12-02 20:59 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    if (_.isEmpty(rows) || rows.length > 1) {
Updated

2021-12-02 20:59 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +      'getRecordIndexFromTimestamp'
Updated

2021-12-02 20:59 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    };
Duh, updated

2021-12-02 20:59 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    const rows = await super.getRows(query, whereParams, 'getContractResultsByIdAndTimestamp');
Updated

2021-12-02 20:59 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    await expect(ContractService.getContractResultsByIdAndTimestamp()).resolves.toEqual(null);
Updated with values, I was going for the undefined case to ensure no match but this is more clear

2021-12-02 21:00 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +        "hash": "contractRecordHash"
Updated

2021-12-02 21:00 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-11-transactionid-path.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId",
Updated

2021-12-02 21:00 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-12-transactionid-path-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
Updated

2021-12-02 21:00 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      this.block_hash = utils.toHexString(recordFile.hash, true);
Updated

2021-12-02 21:02 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    await expect(ContractService.getContractResultsByIdAndTimestamp(2, 2)).resolves.toMatchObject(
Yes, that's the intention. So you don't have to check every field but can verify on the uniquely identifiable and appropriate columns for the test.
Some fields are left out of input for brevity

2021-12-02 21:08 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  const row = await ContractService.getContractResultsByTransactionId(
How do people feel about it?
In future refactors I can see moving `transactionId` and `entityId` into a dir under or 1 level deeper than model.
Not sure how heavily that should influence what falls within the Service files area of concern

2021-12-02 21:32 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +    limit 1`;
the query is unlikely to involve other tables. if so in the future, we can change it to full column / table alias. personally I do prefer simplicity.

2021-12-02 21:34 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      this.block_hash = utils.toHexString(recordFile.hash, true);
it doesn't seem to be fixed?

2021-12-02 21:34 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      this.hash = utils.addHexPrefix(transaction.transactionHash);
umm, fixed the wrong hash?

2021-12-02 21:53 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-11-transactionid-path.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId",
Mix up, updated now

2021-12-02 21:55 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      this.block_hash = utils.toHexString(recordFile.hash, true);
Updated for realz this time

2021-12-02 22:17 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      this.hash = utils.addHexPrefix(transaction.transactionHash);
Fixed

2021-12-02 23:01 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +const {logger} = require('../stream/utils');
do we have to import it from `../stream/utils`? logger is in global scope and in other sources files we use it directly.

The reason there is one in stream/utils.js is the stream module is shared by check-state-proof.

2021-12-03 05:16 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +    limit 1`;
Can't disagree with simplicity :)
Updated and added tests

2021-12-03 05:16 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +const {logger} = require('../stream/utils');
Shouldn't be there. Removed

2021-12-03 22:28 UTC, steven-sheehy requested changes

2021-12-03 22:28 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +        "index": 17,
Should add some more record files before and after to verify correct one returned.

2021-12-03 22:28 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-12-transactionid-path-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
Should add test cases for when no contract ID found too

2021-12-03 23:40 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +        "index": 17,
Added

2021-12-03 23:40 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +    "block_number": 17,
I'm okay holding out on exposing it for now but I don't think we can long term not expose it.

2021-12-06 16:28 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +    "block_number": 17,
Perhaps we just add some caveats to the OpenAPI field description and the public docs. Something to the effect of `Counts the number of record files seen since the mirror node's configured start date. This can vary between mirror nodes that use different start dates.`

2021-12-06 16:50 UTC, steven-sheehy requested changes

2021-12-06 16:50 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-12-transactionid-path.spec.json
> +  "description": "Contract results api call using transactionId",
Should have a test case with invalid transactionid and contract id

2021-12-06 16:50 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  const row = await ContractService.getContractResultsByTransactionId(
I agree with Xin. TransactionID and EntityID are models, they're just field models instead of table models. We have them directly in the domain directory in other modules.

2021-12-06 16:50 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +    const transaction = new Transaction(result);
I'm not a fan of joining two tables then using the combined query results to parse into separate models. This could cause issues if they have the same field name that is not a join field like if in the future we added a `contract_result.type`.

Why can't we concurrently query transaction and contract result tables and return a single model for each query? Then we can have concrete methods for get transaction by transaction id and get by timestamp.

2021-12-06 20:56 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +    "block_number": 17,
Added to OpenAPI

2021-12-06 20:56 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  const row = await ContractService.getContractResultsByTransactionId(
Works for me. Added

2021-12-06 20:59 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-12-transactionid-path.spec.json
> +  "description": "Contract results api call using transactionId",
Added

2021-12-06 21:00 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    const transaction = new Transaction(result);
Looking into this

2021-12-06 21:10 UTC, steven-sheehy requested changes

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    timestampPathParam:
Can we retrofit `/api/v1/topics/messages/{consensusTimestamp}` to use this as well?

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: The correlating transaction consensus timesampt
```suggestion
      description: The timestamp at which the associated transaction reached consensus
```

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        amount:
Is there a way to extend the existing `ContractResult` and add the new fields to keep this DRY?

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: string
Can we use `EntityId` here instead of string?

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    ContractResultExpanded:
Maybe `ContractResultDetails`?

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: getContracResulttByIdAndTimestamp
```suggestion
      operationId: getContracResultByIdAndTimestamp
```

2021-12-06 21:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/contractIdPathParam'
I wonder why we have entity specific path params? Can't we just have an `entityIdPathParam`?

2021-12-06 21:25 UTC, ijungmann requested changes
Just need to look at the specs still.  Couple minor things

2021-12-06 21:25 UTC, ijungmann commented on hedera-mirror-rest/service/contractService.js
> +  )} and
What is the need for matching `payer_account_id` and not just `consensus_timestamp`?  Not a change request, just forgetting why it's not unique.

2021-12-06 21:25 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/recordFileService.test.js
> +  test('RecordFileService.getRecordFileBlockDetailsFromTimestam - No match', async () => {
nit:
```suggestion
describe('RecordFileService.getRecordFileBlockDetailsFromTimestamp tests', () => {
  test('RecordFileService.getRecordFileBlockDetailsFromTimestamp - No match', async () => {
```

2021-12-06 21:26 UTC, ijungmann commented on hedera-mirror-rest/service/contractService.js
> +  )} and
Nevermind, pretty sure I figured it out.

2021-12-06 21:43 UTC, ijungmann requested changes
Couple nits on the names of the specs

2021-12-06 21:43 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +  "description": "Contract results api call using timestamp",
nit: should be contract id and timestamp, right?

2021-12-06 21:43 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-results-14-transactionid-path-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
nit: should not have contract id

2021-12-06 21:43 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-results-15-transactionid-path-contract-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
nit: I think this name does not reflect the file name/test

2021-12-06 22:33 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +  )} and
This is a citus requirement.
We have to join on the distribution column

2021-12-06 23:03 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        amount:
Yes, will be pushing it out next commit

2021-12-06 23:13 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/contractIdPathParam'
Likely for the explicit description

2021-12-06 23:35 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/contractIdPathParam'
Can update

2021-12-07 00:05 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
I'm okay not exposing it for now until we're clear on the use case value. Can remove till the dust settles.

2021-12-07 01:41 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: getContracResultByIdAndTimestamp
```suggestion
      operationId: getContractResultByIdAndTimestamp
```

2021-12-07 02:31 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: getContracResultByIdAndTimestamp
Fixed

2021-12-07 02:31 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-09-timestamp-path.spec.json
> +  "description": "Contract results api call using timestamp",
Updated

2021-12-07 02:31 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/recordFileService.test.js
> +  test('RecordFileService.getRecordFileBlockDetailsFromTimestam - No match', async () => {
Updated

2021-12-07 02:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: getContracResulttByIdAndTimestamp
Fixed

2021-12-07 02:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +    ContractResultExpanded:
Updated

2021-12-07 02:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +            type: string
Updated

2021-12-07 02:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: The correlating transaction consensus timesampt
Updated

2021-12-07 02:32 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +    timestampPathParam:
Done

2021-12-07 05:52 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-14-transactionid-path-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
Updated

2021-12-07 05:54 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-15-transactionid-path-contract-not-found.spec.json
> +  "description": "Contract results api call for a specific contract using contract id and transactionId with no file match",
Updated

2021-12-07 05:54 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: getContracResultByIdAndTimestamp
Fixed

2021-12-07 19:06 UTC, xin-hedera approved these changes
LGTM

2021-12-07 19:51 UTC, ijungmann approved these changes

2021-12-07 21:35 UTC, merged