Contract logs api
hashgraph/hedera-mirror-node pull request #2930
Opened 2021-12-03 02:38 UTC by ijungmann

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-05 20:30 UTC, ijungmann commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> -        limit $2`,
Unformat

2021-12-05 20:31 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +                                                              null))::jsonb as topics
Check formatting here

2021-12-09 17:31 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +                         and ${FileData.getFullName(FileData.CONSENSUS_TIMESTAMP)} <= ${Contract.getFullName(
Undo formatting

2021-12-14 17:45 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.2__convert_topics.sql
> +    alter column topic3 type bytea using decode(topic3, 'hex');
Will remove this after merging other PR

2021-12-14 22:38 UTC, ijungmann commented on docs/design/smart-contracts.md
> -- `address`
Removed because this endpoint will only show logs for the given contract_id, there's nothing to filter on.

2021-12-14 22:41 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^0x[0-9A-Fa-f]{64}$/; // 0x followed by 64 hex digits
The examples of topics I've seen are all 64 characters long, but maybe that's not always correct or there are other reasons to not be so strict on this check.

2021-12-14 23:12 UTC, ijungmann commented
The importer and rest CI should fix as soon as #3002 gets merged

2021-12-15 01:09 UTC, Nana-EC requested changes
Some missed items and suggestions.
Will circle back for a 2nd pass

2021-12-15 01:09 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    const rows = await super.getRows(query, params, 'getContractLogsByIdAndFilters');
Another option is
```suggestion
    const row = await super.getSingleRow(query, params, 'getContractLogsByIdAndFilters');
    return _.isNull(row) ? [] : new ContractLog(row);
```

2021-12-15 01:09 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +      logger.trace(`getAccounts query: ${query} ${JSON.stringify(params)}`);
No need for this as baseService will handle this logging.
Although you could more the traceEnabled check there as it's missing

2021-12-15 01:09 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractLogViewModel.js
> +   * Constructs contractResult view model
```suggestion
   * Constructs contractLog view model
```

2021-12-15 01:43 UTC, ijungmann commented on hedera-mirror-rest/service/contractService.js
> +    const rows = await super.getRows(query, params, 'getContractLogsByIdAndFilters');
In this case we don't want that, right?  For any given contract_id we will potentially have many contract_logs. `getSingleRow` is for searching based on a unique id.

2021-12-15 01:46 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs        |
Added to the description as default 1 year (description already mentions it's in milliseconds)

2021-12-15 01:46 UTC, ijungmann commented on hedera-mirror-rest/__tests__/application.yml
> +      maxTimestampRange: 31536000000
Added as comment to both main and test config

2021-12-15 01:47 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  contractLog.bloom = contractLogInput.bloom != null ? Buffer.from(contractLogInput.bloom) : contractLog.bloom;
Good call, added as a method to `testUtils`.  I'm only going to use it for my tests for now so I don't blow up the PR with refactoring, but I can make a separate PR to replace elsewhere.

2021-12-15 01:48 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-01-no-params.spec.json
> +  "description": "Contract logf api calls with no params",
Fixed.

2021-12-15 01:48 UTC, ijungmann commented on hedera-mirror-rest/service/contractService.js
> +      logger.trace(`getAccounts query: ${query} ${JSON.stringify(params)}`);
Removed here, added traceEnabled check to baseService

2021-12-15 01:49 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractLogViewModel.js
> +   * Constructs contractResult view model
Fixed.

2021-12-15 15:27 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    const rows = await super.getRows(query, params, 'getContractLogsByIdAndFilters');
Read this wrong. You're correct. Ignore

2021-12-15 20:23 UTC, steven-sheehy requested changes
Still reviewing. Here's the comments so far.

2021-12-15 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +        //Multiple greater than operators detected, not permitted
Is there a way to return these comments as validation error messages on the response? Perhaps instead of returning boolean we can throw an error with the message. We can catch the error higher up to support returning multiple validation errors. Otherwise the user will have a difficult time figuring out what's wrong with their input.

2021-12-15 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^0x[0-9A-Fa-f]{64}$
Need to relax this pattern here as well. Perhaps create a `TopicQueryParam` reusable type to stay DRY.

2021-12-15 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-logs-13-topics-timestamp-range-invalid-backwards.spec.json
> +    "/api/v1/contracts/1000/results/logs?topic0=0x97c1fc0a6ed5551bc831571325e9bdb365d06803100dc20648640ba24ce69750&topic3=0xe8d47b56e8cdfa95f871b19d4f50a857217c44a95502b0811a350fec1500dd67&timestamp=
Don't test each form of contract ID in every spec. You can test it in one spec, usually the first positive test case. Instead the URLs should only vary if it's testing variations of the scenario in the description/filename. So here you could add `lt` and `gt` variations to your current `lte` and `gte`.

2021-12-15 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-logs-13-topics-timestamp-range-invalid-backwards.spec.json
> +          "message": "Cannot search topics without timestamp range within 31536000000 milliseconds"
The error message is a bit unclear. Perhaps:

`Invalid timestamp range: Lower and upper bounds must be within X s`

2021-12-15 20:23 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs. Default is 1 year.
Is there a `Duration` equivalent in javascript that would allow us to use more human readable values like `7d` or 24h`? That would be useful for validation errors as well.

2021-12-15 20:56 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +      ret = isNumeric(val) && val > 0;
Fixed

2021-12-15 20:57 UTC, ijungmann commented on hedera-mirror-rest/entityId.js
> +  parseFromSolidityAddress,
Removed, was used when we had `address` as searchable

2021-12-15 20:58 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  isNumeric,
Removed, originally had some custom validation checks in `contractController`, those were taken out.

2021-12-15 21:54 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/ContractResultsResponse'
Fixed

2021-12-15 21:54 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +      case constants.filterKeys.TOPIC0:
Altered the regex to remove `0x` to also remove leading zeros.

2021-12-15 21:54 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +            pattern: ^0x[0-9A-Fa-f]{64}$
Omitted

2021-12-15 21:55 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^0x[0-9A-Fa-f]{64}$/; // 0x followed by 64 hex digits
Relaxed

2021-12-15 21:55 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^0x[0-9A-Fa-f]{64}$/; // 0x followed by 64 hex digits
Also relaxed in openapi

2021-12-15 21:55 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs. Default is 1 year.
I could see one week or one month.  I agree one year is very high.

2021-12-15 22:02 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^0x[0-9A-Fa-f]{64}$
Relaxed, also made the `TopicQueryParam`

2021-12-15 22:50 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-03-timestamp-not-equal.spec.json
> +          "message": "Invalid parameter: timestamp"
This actually made me realize this test was wrong, I'd removed the really messy stuff to check for ne and this was failing because the timestamp was actually invalid.
I added a check when passing through the filters to check for ne and throw a much clearer error than the validation logic, and I updated this test accordingly.

2021-12-15 22:50 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    if (filter.operator === 'eq') {
Added constants

2021-12-15 23:23 UTC, xin-hedera requested changes

2021-12-15 23:23 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  const difference = math.subtract(latest, earliest);
nodejs `Number` precision issue. timestamp is 8-byte long.

I do think we can just calculate at `millis` precision, that'll allow us to use js number without the precision concern. Also it should be more performant than using `long` or `bigint`.

2021-12-15 23:23 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const maxTimestampRange = math.multiply(config.maxTimestampRange, 1e6);
`Number` precision issue

2021-12-15 23:23 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^(0x)?[0-9A-Fa-f]{1,64}$/; // optional 0x followed by up to 64 hex digits
this would allow odd number of chars.

2021-12-15 23:47 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +        //Multiple greater than operators detected, not permitted
Rewrote this to throw clear error instead of returning booleans

2021-12-15 23:50 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-13-topics-timestamp-range-invalid-backwards.spec.json
> +          "message": "Cannot search topics without timestamp range within 31536000000 milliseconds"
Added that.  Also broke down the error messages in general to be clearer.

2021-12-15 23:54 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractLogTimestampInValues = [];
I could see limiting topic and index to one per query.  Don't think we should do that on timestamp though, enforcing the range is how we get away from adding the topic indexes.  Any other opinions?

2021-12-15 23:57 UTC, Nana-EC requested changes
Some improvement suggestions

2021-12-15 23:57 UTC, Nana-EC commented on hedera-mirror-rest/model/contractLog.js
> +   * Parses contract table columns into object
```suggestion
   * Parses contract_log table columns into object
```

2021-12-15 23:57 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractId = EntityId.parse(req.params.contractId, constants.filterKeys.CONTRACTID).getEncodedId();
nit: move contractId param check to after the `req` validity check

2021-12-15 23:57 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +    indexQueryParam:
nit: just to be clear
```suggestion
    logIndexQueryParam:
```

2021-12-15 23:57 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        $ref: '#/components/schemas/ContractResult'
```suggestion
        $ref: '#/components/schemas/ContractLog'
```

2021-12-15 23:57 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ContractResults'
```suggestion
          $ref: '#/components/schemas/ContractLogs'
```

2021-12-16 00:08 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractLogTimestampInValues = [];
right, I added the comment to the wrong line. It's for index/topic*.

2021-12-16 00:43 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +    if (!utils.checkTimestampRange(timestamps)) {
So you're saying still pass in the topics from the req, but pass in the build `filters` from earlier and just filter through those to get the timestamp filters?

2021-12-16 00:52 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    if (!utils.checkTimestampRange(timestamps)) {
yes. like

```javascript
const checkTimestampsForTopics = (query, filters) => {
```

`query` is just `req.query`. looks a bit weird though.

Or even better, we just need `filters`, since to find the list of `TIMESTAMP` filters we'll iterate the array, we can just test if any topic filter is there as well.

2021-12-16 01:11 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^(0x)?[0-9A-Fa-f]{1,64}$/; // optional 0x followed by up to 64 hex digits
So it could be `^(0x)?([0-9A-Fa-f][0-9A-Fa-f]){1,32}$`

2021-12-16 01:12 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +    .map((position) => `decode($${position}, 'hex')`);
Changed to using the buffer, made things cleaner

2021-12-16 01:14 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +        return false;
I don't really see a reason to support multiple greater than or less than operators, one will always win over the other and make it useless.  If we want to support multiple then yes, that could be done.

2021-12-16 03:17 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +  utils.validateReq(req);
Removed validateReq

2021-12-16 03:25 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs. Default is 1 year.
Swapped to one week

2021-12-16 03:27 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs. Default is 1 year.
Didn't find anything in the standard lib, but found a few packages, went with [to-time](https://www.npmjs.com/package/to-time)

2021-12-16 03:28 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +  checkTimestampsForTopics(req.query.timestamp, req.query.topic0, req.query.topic1, req.query.topic2, req.query.topic3);
Fixed by passing in filters

2021-12-16 03:28 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +    if (!utils.checkTimestampRange(timestamps)) {
Yep, did that, iterator over all filters, check for a topic filter, build the timestamp array, pass that instead.  I need to fix tests in the Controller still, but fixed the Util tests and it works

2021-12-16 03:30 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  const difference = math.subtract(latest, earliest);
Added logic to turn the nanos string into milliseconds and turned the max into millis as well.

2021-12-16 03:30 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const maxTimestampRange = math.multiply(config.maxTimestampRange, 1e6);
Fixed, now in millis

2021-12-16 03:42 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs. Default is 1 year.
https://www.npmjs.com/package/parse-duration seems to have more recent updates and has more weekly downloads than to-time.

2021-12-16 16:29 UTC, ijungmann commented on docs/configuration.md
> +| `hedera.mirror.rest.maxTimestampRange         `          | 31536000000             | The maximum number of milliseconds a timestamp range query param can span for some APIs. Default is 1 year.
Switched to that

2021-12-16 16:29 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^(0x)?[0-9A-Fa-f]{1,64}$/; // optional 0x followed by up to 64 hex digits
Switched to that as it prevents odd number of chars

2021-12-16 17:04 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +        break;
Reduced this code with a JS object to make it cleaner

2021-12-16 17:18 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        $ref: '#/components/schemas/ContractResult'
Fixed

2021-12-16 17:18 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ContractResults'
Fixed

2021-12-16 17:19 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +    indexQueryParam:
Fixed

2021-12-16 17:20 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractId = EntityId.parse(req.params.contractId, constants.filterKeys.CONTRACTID).getEncodedId();
Moved

2021-12-16 17:21 UTC, ijungmann commented on hedera-mirror-rest/model/contractLog.js
> +   * Parses contract table columns into object
Fixed

2021-12-16 17:35 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ContractResults'
Is it though?

2021-12-16 17:36 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        $ref: '#/components/schemas/ContractResult'
Is it?

2021-12-16 17:49 UTC, xin-hedera requested changes

2021-12-16 17:49 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  let latest = undefined;
nit

```suggestion
  let latest;
```
initialize it to `undefined` is the same as uninitialized

2021-12-16 17:49 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Lower and upper bounds must be positive and within ${config.maxTimestampRange} ns`);
```suggestion
    throw new InvalidArgumentError(`Lower and upper bounds must be positive and within ${maxTimestampRange} ms`);
```

2021-12-16 17:49 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const maxTimestampRange = parseDuration(config.maxTimestampRange);
should parse the config in `config.js` and fail early if the provided value is invalid.

2021-12-16 17:49 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +        filter.value = filter.value.replace(/^(0x)?0*/, '');
this may remove odd number of 0s, Buffer.from will discard the last single char and the data thus is incorrect.

```
> Buffer.from('1ab', 'hex');
<Buffer 1a>
```

2021-12-16 17:55 UTC, ijungmann commented on hedera-mirror-rest/service/contractService.js
> +  static contractLogsByIdQuery = `select ${ContractLog.getFullName(ContractLog.CONTRACT_ID)},
Removed

2021-12-16 18:00 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^(0x)?[0-9A-Fa-f]{1,64}$/; // optional 0x followed by up to 64 hex digits
So? We should accept odd numbers and zero pad it as necessary to get to 64 chars or 32 bytes. We should be more permissive in input. Please change back to `/^(0x)?[0-9A-Fa-f]{1,64}$/`.

2021-12-16 18:01 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ContractResults'
Yep, just trying to address a batch of comments before pushing to reduce the number of actions run.

2021-12-16 18:04 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Lower and upper bounds must be positive and within ${config.maxTimestampRange} ns`);
It does, just forgot to remove the ns at the end

2021-12-16 18:09 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +      //An equals operator removes the need for a range
Well probably multiple equals okay but we would need to validate that the min and max of all of them fall within max range. Perhaps also `eq` and other range operators are ok as well if we also check they are all within max range.

2021-12-16 18:27 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    throw new InvalidArgumentError(`Lower and upper bounds must be positive and within ${config.maxTimestampRange} ns`);
Removed altogether, just going to print the config value

2021-12-16 18:30 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +        filter.value = filter.value.replace(/^(0x)?0*/, '');
Added a line to pad the front with a 0 if the string has an odd number of chars

2021-12-16 18:32 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const contractTopicPattern = /^(0x)?[0-9A-Fa-f]{1,64}$/; // optional 0x followed by up to 64 hex digits
Put it back, added logic later that strips leading 0s and then if the result is an odd number of chars, put a leading 0 in front.

2021-12-16 19:45 UTC, ijungmann commented on docs/design/smart-contracts.md
> +      "address": "0x0000000000000000000000000000000000001234",
Sure, added

2021-12-16 19:50 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  let latest = undefined;
Fixed

2021-12-16 20:30 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractLogTimestampInValues = [];
Will add logic to throw error for multiple topic or index search

2021-12-16 21:15 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const maxTimestampRange = parseDuration(config.maxTimestampRange);
Changed to parse in config

2021-12-16 21:27 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        contract_logs:
Changed to just `logs`

2021-12-16 21:35 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +      //An equals operator removes the need for a range
So when searching on topics:

1. A single eq operator is okay as is, does not require a range at all.
2. Multiple eq operators requires that a range (gt/gte and lt/lte) is also specified, and that all eq fall inside of that range.

This is what you have in mind?

2021-12-16 21:43 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +      //An equals operator removes the need for a range
Correction:
1. A singe eq operator, if no other operators are present, is okay.
2. Multiple eq operators, or a single eq operator with any other operator (gt, gte, etc) needs to be checked

2021-12-17 17:00 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +      //An equals operator removes the need for a range
Reworked this chunk of code to be easier to read.

2021-12-17 17:00 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +        throw new InvalidArgumentError('Multiple greater than operators not permitted');
Rewrote the error messages

2021-12-17 18:12 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-13-topics-timestamp-range-invalid-backwards.spec.json
> +    "/api/v1/contracts/1000/results/logs?topic0=0x97c1fc0a6ed5551bc831571325e9bdb365d06803100dc20648640ba24ce69750&topic3=0xe8d47b56e8cdfa95f871b19d4f50a857217c44a95502b0811a350fec1500dd67&timestamp=
Fixed to not test each form

2021-12-17 20:24 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +      "address": "0x0000000000000000000000000000000000001234",
I think `contract_id` is still missing no?
With the addition of root_contract_id I wonder if that needs the solidity address stated also.
I'm fine with not adding that 2nd part till needed though

2021-12-17 20:59 UTC, ijungmann commented
Will look at the code smells when I get back in, looks like mostly existing issues with utils

2021-12-17 21:05 UTC, Nana-EC reviewed
Lots of good stuff. Some clarifications and suggestions for consideration

2021-12-17 21:05 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/viewmodel/contractLogViewModel.test.js
> +  test('ContractLogViewModel- no root contract id', () => {
nit:
```suggestion
  test('ContractLogViewModel - no root contract id', () => {
```

2021-12-17 21:22 UTC, xin-hedera requested changes

2021-12-17 21:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +  });
should there be a test case with multiple logs in the response?

if so, you can take a look at what's needed to extend jest with `toIncludeSameMembers` in my transaction ID nonce branch.

https://github.com/hashgraph/hedera-mirror-node/blob/420c46293e1b64226fa3b772e561d61b3046cab6/hedera-mirror-rest/__tests__/service/contractService.test.js#L293

You also need the package `jest-extended` and load it in `__tests__/jest.setup.js`, you can check the changes in my branch.

2021-12-17 21:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/utils.test.js
> +  test('Utils test - utils.checkTimestampRange - no params', () => {
can we not duplicate the name in the `test`? I made the change in the transaction ID nonce branch for most test files it touches.

jest will print the names in a hierarchy, so the above when simplified will be

```
Utils test - utils.checkTimestampRange
  no params
  one param gt
  ...
```

2021-12-17 21:22 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    ltFilters: ltFilters.sort(),
don't sort these filters

2021-12-17 21:22 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  }
opinion, better break out these into separate `if`s

```
if (neLength > 0) {
  throw
}

if (gtLenght > 1) {
  throw
}

if (ltLength > 1) {
  throw
}

...
```

2021-12-17 22:19 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ContractResults'
I do this sometimes also. I've found success drafting the comment replied, then pushing, then presssing "Comment" :)

2021-12-17 22:24 UTC, steven-sheehy requested changes

2021-12-17 23:52 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-16-index-multiple-params.spec.json
> +  "description": "Contract logs api calls with topic params and timestamp param",
Fixed

2021-12-17 23:52 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-15-topics-with-timestamp-multiple-params.spec.json
> +  "description": "Contract logs api calls with topic params and timestamp param",
Fixed.

2021-12-17 23:55 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: Returns a list of all ContractLogs for a contract's function executions.
Added

2021-12-17 23:55 UTC, ijungmann commented on hedera-mirror-rest/__tests__/viewmodel/contractLogViewModel.test.js
> +  test('ContractLogViewModel- no root contract id', () => {
Fixed

2021-12-17 23:56 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +
I'm having some issues getting that to work with `res.send()`, but it might make sense to look into

2021-12-18 02:02 UTC, ijungmann commented on hedera-mirror-rest/__tests__/application.yml
> +      maxTimestampRange: 7d
Removed

2021-12-18 02:02 UTC, ijungmann commented on hedera-mirror-rest/__tests__/config.test.js
> +    process.env = {HEDERA_MIRROR_REST_MAX_TIMESTAMP_RANGE: '7d'};
Swapped to 3

2021-12-18 02:02 UTC, ijungmann commented on hedera-mirror-rest/config.js
> +};
Fixed

2021-12-18 02:03 UTC, ijungmann commented on hedera-mirror-rest/__tests__/config.test.js
> +  test('Max Timestamp Range', () => {
Added tests for 3x and null value

2021-12-18 02:06 UTC, ijungmann commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +      },
Unless I'm missing something else, that causes the test to fail (since it puts the defaultExpected{} wrapper in it

2021-12-18 02:07 UTC, ijungmann commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +      expect(error).toThrowError(spec.errorMessage);
Added

2021-12-18 02:10 UTC, ijungmann commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +describe('checkTimestampsForTopics', () => {
Added

2021-12-18 02:16 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +  });
I have a test that returns multiple logs.  `ContractService.getContractLogsByIdAndFilters - Id match` above it matches 3 logs.  This particular test only does 1 because with that many filters it wouldn't be possible to return more than one.

2021-12-18 02:20 UTC, ijungmann commented on hedera-mirror-rest/__tests__/utils.test.js
> +  test('Utils test - utils.checkTimestampRange - no params', () => {
Sure.  I fixed this particular set of tests, I'll do a pass for other tests I need to put back.

2021-12-18 02:21 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +    ltFilters: ltFilters.sort(),
Good catch, was leftover.  Removed.

2021-12-18 02:22 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-logs-16-index-multiple-params.spec.json
> +  "description": "Contract logs api calls with topic params and timestamp param",
Fixed

2021-12-18 02:27 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const parseDuration = require('parse-duration');
Fixed.

2021-12-18 02:31 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +    TopicQueryParam:
All `Topic` items should now be `LogTopic`, etc.

2021-12-18 02:31 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        data:
Added

2021-12-18 02:31 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        contract_logs:
Fixed

2021-12-18 02:35 UTC, ijungmann commented on docs/design/smart-contracts.md
>        "data": "0x8f705727c88764031b98fc32c314f8f9e463fb62",
Added

2021-12-19 01:22 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +
Gotcha.
I may have hit similar but they seemed to be occasionally and only on local integration runs not CI or browser.
Look at the `/tokens/:tokenId/nfts` flow and you should be good.

2021-12-19 02:30 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +                              and cl.contract_id in ($5)
Fixed, these tests were taking input based on an old query structure, rewrote them to fit the new query.

2021-12-19 02:32 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +                                     cl.index asc
I can make that change, that would mean the logs always come in reverse by default.

2021-12-19 02:59 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractLogViewModel.js
> +    return topics.filter((topic) => topic !== null).map((topic) => utils.toHexString(topic, true));
Zero padded the start of the topics before adding 0x to the front

2021-12-19 02:59 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractLogViewModel.js
> +    return topics.filter((topic) => topic !== null).map((topic) => utils.toHexString(topic, true));
Added unit and specs test for that

2021-12-19 03:07 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +                                     cl.index asc
Reversed

2021-12-19 03:09 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  }
Broken out

2021-12-20 04:20 UTC, ijungmann commented
I believe I've addressed everything in the comments other than sending 204 for empty results, locally in the browser I was getting mixed results so I took it out.

2021-12-20 20:17 UTC, steven-sheehy requested changes

2021-12-20 20:34 UTC, xin-hedera requested changes

2021-12-20 20:34 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +      },
sounded like you changed it to?
```javascript
      expected: {
        defaultExpected,
      },
```

then you should remove the curly braces.

2021-12-20 20:57 UTC, xin-hedera requested changes

2021-12-20 20:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +      expect(error).toThrowErrorMatchingSnapshot();
need to add & commit the snapshot file (`*.js.snap`) in `__test__/controller/__snapshots__`

2021-12-21 15:00 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/application.yml
> +        level: trace
intend to keep it.

1. the trace level is only on during testing
2. it shows the sql query and params, useful when some integration tests fail
3. slightly increases code coverage, since now the statements in `if (logger.isTraceEnabled())` have test coverage

2021-12-21 15:02 UTC, xin-hedera commented on hedera-mirror-rest/routes/contractRoute.js
> +  `${path}/:contractId/results/:consensusTimestamp([0-9.]\+)`,
`/:contractId/results/:consensusTimestamp` clashes with `/:contractId/results/logs`, caused some issue in tests and the issue was hidden because in contractController.js `getContractLogs` we used `res.send`

2021-12-21 15:04 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  // to prevent false negative
the intention is to avoid bigint arithmetic. however, with the validation logic, if it's a range, there can be exactly one gt/gte and lt/lte, we should consider just using bigint to make the logic simple and the range check accurate.

2021-12-21 15:05 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-logs-02-timestamp.spec.json
> +        "index": 1,
fixed

2021-12-21 15:05 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-logs-01-no-params.spec.json
> +        "index": 1,
fixed

2021-12-21 15:05 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractLogViewModel.js
> +        const paddedTopic = `${'0'.repeat(64)}${topicString}`.slice(-64);
fixed

2021-12-21 15:05 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +    indexOrder = orderFilterValues.ASC,
fixed

2021-12-21 15:05 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-logs-17-short-topic.spec.json
> +  "description": "Contract logs api calls with a topic shorter that 64 chars that gets zero padded",
removed, and updated contracts-logs-01

2021-12-21 15:09 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  };
response was directly sent using `res.send`

once I changed it, integration tests began to fail, since requests hit both /contracts/:id/results/logs and /contracts/:id/results/:consensusTimestamp

2021-12-21 16:05 UTC, steven-sheehy requested changes

2021-12-21 16:05 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  // to prevent false negative
I'm just noticing that we're only comparing range at millisecond granularity. That might be okay if the server is implicitly adding the range, but will be unexpected for users if they explicitly added a range down to nanoseconds. They would then get results that don't match their precise filter.

I think we should use nanoseconds everywhere and use long arithmetic to provide accurate results. Performance for using long/bigint arithmetic should not be a concern for validating user input once per request. It only becomes a concern if used on many response rows.

2021-12-21 16:12 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  // to prevent false negative
No problem and the changes should be small. Will also add more test cases

2021-12-21 19:28 UTC, steven-sheehy approved these changes
LGTM

2021-12-21 19:37 UTC, xin-hedera approved these changes

2021-12-21 19:40 UTC, merged