Add support for HTS precompiles
hashgraph/hedera-mirror-node pull request #2931
Opened 2021-12-03 17:51 UTC by steven-sheehy

**Description**:
- Add new `transaction.nonce` and populate it
- Add new `transaction.parent_consensus_timestamp` and populate it
- Rename `scripts/timescaledb` to `scripts/v2`

**Related issue(s)**:

Fixes #2925 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-12-03 20:16 UTC, Nana-EC requested changes
I don't think you should add the timescaledb -> citus migration file moves?
`migration.config`, `migration.sh` are not applicable to citus and with the current changes it would make the documentation misleading as running migration files won't work or produce the original working intent.

There's a ticket that deals with this so we should leave it for that.

2021-12-03 20:16 UTC, Nana-EC commented on docs/operations.md
> +   located at `hedera-mirror-importer/src/main/resources/db/scripts/v2`. For binaries, the migration directory
Q: Why just these 2 lines when the whole section referencing timescale.
We could just remove the section or update it to show it's in transition from Timescale to Citus

Also following these steps will no longer provide the desired outcome as the migration files under v2 are no longer applicable to these steps

2021-12-03 20:43 UTC, steven-sheehy commented on docs/operations.md
> +   located at `hedera-mirror-importer/src/main/resources/db/scripts/v2`. For binaries, the migration directory
I think you're missing the point. I wasn't converting the migrations from TimescaleDB to CitusDB. I was just renaming the scripts folder to be a more generic name that still works with both TimescaleDB and/or CitusDB. I'm also not adjusting the entire docs for CitusDB just making sure the references to the scripts path is correct.

2021-12-03 23:08 UTC, Nana-EC commented on docs/operations.md
> +   located at `hedera-mirror-importer/src/main/resources/db/scripts/v2`. For binaries, the migration directory
Understood, I get that you're renaming stuff and updating the docs that reference that path.
Just pointing out the result for someone without context may mislead them.
It's fine, the script migration flow is already broken so we'll address it and the v2 documentation later in the appropriate tickets.

2021-12-03 23:12 UTC, Nana-EC approved these changes

2021-12-03 23:12 UTC, Nana-EC commented on hedera-mirror-rest/model/transaction.js
> +  static PARENT_CONSENSUS_TIMESTAMP_FULL_NAME = `${this.tableAlias}.${this.PARENT_CONSENSUS_TIMESTAMP}`;
nit: another option is to add the getFullName() we've started using.
However, this is consistent with current usage.

```javascript
  static getFullName(columnName) {
    return `${this.tableAlias}.${columnName}`;
  }
```

2021-12-06 04:12 UTC, ijungmann reviewed
LGTM

2021-12-06 04:13 UTC, ijungmann approved these changes

2021-12-06 20:28 UTC, xin-hedera approved these changes
LGTM

2021-12-06 20:36 UTC, merged