Add parent_contract_id to contract_log migration
hashgraph/hedera-mirror-node pull request #2944
Opened 2021-12-06 02:17 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Description**:

Add a parent_contract_id column to contract_log table.

Currently to fetch a list of all contract_logs related to a contract result (including child contracts)
we have to first query for a list of consensus_timestamps for a given contract_id in the contract_log, 
and then do an outer query to find all contract_logs with that timestamp, as different contracts in the logs are linked by the same timestamp.  This limits our ability to filter based on topic, address, etc. because we have to
remove the limit on the timestamp query in case the first 25 timestamps don't match in the outer query, but
26 on does., so we have to do a full scan on the table for each query.  By adding a parent_contract_id
we can reduce this into a single query: where (contract_id = ${id} or parent_contract_id = ${id}) and ...

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-06 02:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.2__contract_logs_parent_id.sql
> +update contract_log child
Add newline

2021-12-06 02:18 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.2__contract_logs_parent_id.sql
> +  and parent.index = 0
Need to verify if it's possible index 0 is NOT the parent (for instance, is it possible the parent contract does not create a log).

2021-12-06 02:19 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.2__contract_logs_parent_id.sql
> +set parent_contract_id = parent.contract_id
add alias to left side

2021-12-06 18:20 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.2__contract_logs_parent_id.sql
> +  and parent.index = 0
Confirmed index 0 does NOT always represent parent.  HIP-260 is proposed to increase traceability, for now we don't have a clear way to backfill.

2021-12-06 22:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/csvRestoreTables.sql
> +\copy contract_log (bloom, consensus_timestamp, contract_id, data, index, topic0, topic1, topic2, topic3, parent_contract_id) from contract_log.csv csv;
Fix

2021-12-06 22:55 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +where contract_log.consensus_timestamp = contract_result.consensus_timestamp;
Should a `contract_log` have a `root_contract_id` that points to itself (same as `contract_id`)?  It would reduce the contract_log endpoint query from (contract_id = $1 or root_contract_id = $1) to just (root_contract_id = $1).  Thoughts?

2021-12-07 06:18 UTC, Nana-EC requested changes
A few items.
Will circle back

2021-12-07 06:18 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +
Add verifyRootContractIdMigrationEmpty() case to ensure no issues on startup with no applicable data

2021-12-07 06:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +-- Backfill root_contract_id based on index
Did you mean timestamp instead of index?

2021-12-07 06:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +where contract_log.consensus_timestamp = contract_result.consensus_timestamp;
My initial thoughts are leave it null.
However, given we'll use a separate flow to determine the hierarchy of calls it may be fine to have root_contract_id point to itself since there shouldn't be anyone doing checks on this table for depth of calls. 
Will circle back on this

2021-12-07 06:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +
Q: Will you be adding the index for topics to this PR or the other?

2021-12-07 16:08 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +-- Backfill root_contract_id based on index
Yep, used to be index.  Fixed.

2021-12-07 22:37 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +
Will leave those, with bloom not working there are questions on if we need them (we already have to filter by contract_id regardless), we could also look into limiting timestamp.

2021-12-08 15:40 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +
Added

2021-12-08 16:42 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +where contract_log.consensus_timestamp = contract_result.consensus_timestamp;
Now that we're not directly using it in a query, I'm fine with leaving it as null.  The only weakness with this is if an account called itself at some point, we could not show that, but we'll have that problem either way.  I've swapped all the logic to not set that if CR and CL contract id are equal.

2021-12-11 00:04 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +create index if not exists contract_log__root_contract_id_timestamp_index
I have index because it's the name of the third field.  Unless you're saying we don't need to list the final field here.

2021-12-11 00:17 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.0__contract_logs_root_id.sql
> +  and contract_log.contract_id <> contract_result.contract_id;
That would make the code simpler on all ends.

2021-12-11 00:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.3__contract_logs_root_id.sql
> +create index if not exists contract_log__root_contract_id_timestamp_index
Ah, missed that

2021-12-13 14:55 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +            assertThat(contractLogRepository.findAll())
Done.

2021-12-13 14:56 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +//        ContractLoginfo logInfo = result.getLogInfo(0);
Done

2021-12-13 14:56 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +        assertThat(results.get(4).getRootContractId()).isNull();
Done.

2021-12-13 14:56 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +                contractResult(2, Long.valueOf(2)),
Done

2021-12-13 14:57 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +create index if not exists contract_log__root_contract_id_timestamp_index
Just removed it here as well, it's no longer needed as we don't need to search on it with current APIs.

2021-12-13 14:59 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.0__contract_logs_root_id.sql
> +  and contract_log.contract_id <> contract_result.contract_id;
agree we should set `root_contract_id` to itself for the root as well. we should make the db column `not null` at the same time.

2021-12-13 15:05 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.0__contract_logs_root_id.sql
> +  and contract_log.contract_id <> contract_result.contract_id;
Put logic back to have `root_contract_id` always set.

2021-12-13 15:15 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.0__contract_logs_root_id.sql
> +  and contract_log.contract_id <> contract_result.contract_id;
I don't know that we can make `root_contract_id` not null, the column it's pulling from `contract_results.contract_id` is nullable.

2021-12-13 16:55 UTC, steven-sheehy requested changes
LGTM. Just a testing change requested

2021-12-13 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +                .containsExactlyInAnyOrder(1L, 1L, 1L, 2L, 3L);
Order is important since the query has ordering
```suggestion
                .containsExactly(1L, 1L, 1L, 2L, 3L);
```

2021-12-13 18:09 UTC, Nana-EC reviewed
Looking good. One non-blocking nit and waiting on the ordered test fix

2021-12-13 18:09 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +                                    "payer_account_id) " +
nit: bump up to join index on a single line. Either each column on it's own or word-wrap for line limit.

2021-12-13 18:41 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +                .containsExactlyInAnyOrder(1L, 1L, 1L, 2L, 3L);
Yep, that actually caught an error in the test.  Fixed both.

2021-12-13 18:41 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
> +                                    "payer_account_id) " +
Fixed.

2021-12-13 18:47 UTC, steven-sheehy approved these changes

2021-12-13 20:54 UTC, steven-sheehy approved these changes

2021-12-13 21:10 UTC, xin-hedera approved these changes
LGTM

2021-12-14 16:23 UTC, Nana-EC approved these changes
LGTM

2021-12-14 16:27 UTC, merged