Convert contract_log topics from string to bytea
hashgraph/hedera-mirror-node pull request #3002
Opened 2021-12-13 22:30 UTC by ijungmann

**Description**:
After discovering that the postgres bloom filter is an extension not supported by CloudSQL, it was decided to convert the topic strings back to bytea in the database to save space.

* Add migration to convert `contract_log` topics to bytea
* Update importer to insert the topic data as byte arrays

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-13 22:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ContractResultMigration.java
> +
Remove

2021-12-13 22:54 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
>       */
Fix comment

2021-12-14 18:12 UTC, steven-sheehy requested changes

2021-12-14 18:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +    void bytesToHexString() {
I don't think `DomainUtils.bytesToHex()` has a test so can move this there instead of discarding.

2021-12-14 20:07 UTC, xin-hedera requested changes
just some nits

2021-12-14 20:07 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +    void setup() {
```suggestion
    void cleanup() {
```

2021-12-14 20:07 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +    void verifyRootContractIdMigrationEmpty() throws Exception {
need to rename the method, it's not `RootContractIdMigration`

2021-12-14 20:09 UTC, Nana-EC requested changes
Looking good. I clarification and one non blocking suggestion.

2021-12-14 20:09 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("00", DomainUtils.bytesToHex(contractLogs.get(0).getTopic0Bytes())),
This is fine but since you did add both `topicn` & `topicnBytes` to the `MigrationContractLog`, another way to do this that avoids hardcoding in the assert would have been to cache the 2 contractLogs you used for insert & then do a 
```
                MigrationContractLog contractLog1 = contractLog(1, 1, 0, "00", "aa", "bb", "cc");
                ... 
                () -> assertEquals(contractLog1.getTopic0(), DomainUtils.bytesToHex(contractLogs.get(0).getTopic0Bytes())),
```

2021-12-14 20:16 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +    void bytesToHexString() {
Moved.

2021-12-14 20:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.2__contract_logs_convert_topics_to_bytes.sql
> +    alter column topic3 type bytea using decode(topic3, 'hex');
Fixed.

2021-12-14 20:16 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +    public static String bytesToHexString(byte[] bytes) {
Good catch, removed here

2021-12-14 20:33 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("cc", DomainUtils.bytesToHex(contractLogs.get(0).getTopic3Bytes())),
You're saying line 81 is the same as line 85, or the same as lines 82-84?  I wanted to check that 1. all 4 topics were converted, and 2. all 4 topics were converted correctly by converting back to original values.  Since I know the hex byte values I could see the value in removing lines 85-88 if that's what you meant, that was mostly debugging for my sanity.

2021-12-14 20:34 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +    void setup() {
Fixed

2021-12-14 20:34 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +    void verifyRootContractIdMigrationEmpty() throws Exception {
Good catch, fixed for both tests

2021-12-14 20:34 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("00", DomainUtils.bytesToHex(contractLogs.get(0).getTopic0Bytes())),
Good idea, fixed.

2021-12-14 20:40 UTC, ijungmann commented on docs/design/smart-contracts.md
> -create index if not exists contract_log__topics_bloom
We had a discussion about this while you were out.  The options were:
1. Add an index for each topic combined with contract_id.
2. Add a hidden timestamp range to requests when searching by topic to help limit how long the query ran.
3. Same number two, but force the user to specify a range/equals operator and return an error if not specified.

We decided that 1 meant adding 4 potentially large indexes, and 2 was preferred overall by meant doing work to make our spec tests dynamic in both the domain ops and the result checker, so we agree to 3 for the `/logs` for now, as it's the easier to implement.

2021-12-14 20:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("cc", DomainUtils.bytesToHex(contractLogs.get(0).getTopic3Bytes())),
I don't think we should check the correctness of `DomainUtils.bytesToHex` here. Instead we should assume it's correct, that's why I treat 81-84 / 85-88 (or precisely, 81/85, 82/86.. etc) as duplicate.

2021-12-14 20:58 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("cc", DomainUtils.bytesToHex(contractLogs.get(0).getTopic3Bytes())),
Sure, I can remove the 4 lines.

2021-12-14 21:01 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("cc", DomainUtils.bytesToHex(contractLogs.get(0).getTopic3Bytes())),
Removed

2021-12-14 21:17 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
> +                () -> assertEquals("00", DomainUtils.bytesToHex(contractLogs.get(0).getTopic0Bytes())),
Actually, removed due to Xin's mention that the check is redundant.

2021-12-14 22:11 UTC, steven-sheehy approved these changes
LGTM

2021-12-14 22:46 UTC, xin-hedera approved these changes
LGTM

2021-12-14 23:16 UTC, Nana-EC commented on docs/design/smart-contracts.md
> -create index if not exists contract_log__topics_bloom
Gotcha, thanks

2021-12-14 23:16 UTC, Nana-EC approved these changes
LGTM

2021-12-14 23:22 UTC, merged