Support Transaction ID nonce
hashgraph/hedera-mirror-node pull request #3041
Opened 2021-12-20 15:22 UTC by xin-hedera

**Description**:

This PR adds transaction ID nonce support to rest API:

- Add `nonce` query param to `/transactions/:transactionId`, default to matching all transactions regardless of nonce
- Add `nonce` query param to `/transactions/:transactionId/stateproof`, default to 0
- Add `nonce` query param to `/contracts/results/:transactionId`, default to 0
- Add `nonce` to nft transaction history response
- Add `-n` option for `nonce` with default `0` to `check-state-proof` cli tool
- Update js monitor transactions test logic to support multiple successful transactions

**Related issue(s)**:

Fixes #2952 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-12-20 16:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/application.yml
> +        level: trace
turn on sql query & param logs during test

2021-12-20 16:38 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/package.json
> +    "boxen": "^5.1.2",
downgrade to latest CJS compatible version

2021-12-20 17:34 UTC, xin-hedera commented on hedera-mirror-rest/check-state-proof/package.json
> +    "protobufjs": "^6.11.2",
will remove, added since it's needed to use the embedded proto package before sdk released the new `@hashgraph/proto` package

2021-12-20 17:34 UTC, xin-hedera commented on hedera-mirror-rest/package.json
> +    "protobufjs": "^6.11.2",
will remove, added since it's needed to use the embedded proto package before sdk released the new `@hashgraph/proto` package

2021-12-20 19:34 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    next = urlPrefix + req.baseUrl + path + next;
expressjs doc:

```
req.baseUrl

The URL path on which a router instance was mounted.
```

2021-12-20 19:34 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +      ret = op === 'eq' && isNonNegativeInt32(val);
will switch to constant from the contract logs PR.

2021-12-20 23:08 UTC, steven-sheehy requested changes

2021-12-20 23:08 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  const transactions = await TransactionService.getTransactionDetailsFromTransactionIdAndNonce(transactionId, nonce);
Can't we just have a transaction result filter added to this query so that it filters out duplicate transaction results? Otherwise this query could potentially return up to X rows where X is the number of nodes.

2021-12-20 23:08 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      'Contract result invariance breached: there should be at most one contract result for contract ' +
If you filter the previous transaction id query so that it can only return at most one row then you shouldn't need to search by multiple timestamps or check for more than one rows here.

2021-12-21 15:07 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/application.yml
> +        level: trace
intend to keep it, explained in the contract logs PR.

2021-12-21 15:07 UTC, xin-hedera commented on hedera-mirror-rest/model/transactionResult.js
> +  282: 'INVALID_ALIAS_KEY',
need to check if there's a new hedera-protobufs-go release / snapshot

2021-12-21 15:08 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  const transactions = await TransactionService.getTransactionDetailsFromTransactionIdAndNonce(transactionId, nonce);
sure

2021-12-21 16:07 UTC, steven-sheehy commented on hedera-mirror-rest/model/transactionResult.js
> +  282: 'INVALID_ALIAS_KEY',
Can't we add a constant without updating the dependency?

2021-12-21 16:10 UTC, xin-hedera commented on hedera-mirror-rest/model/transactionResult.js
> +  282: 'INVALID_ALIAS_KEY',
Should be fine, I probably had the wrong impression about the test case.  In case the test case fails because of the new response code here we should fix the test case.

2021-12-21 20:53 UTC, xin-hedera commented on hedera-mirror-rest/model/transactionResult.js
> +  282: 'INVALID_ALIAS_KEY',
updated `hedera-mirror-rosetta/app/domain/types/constants.go`

2021-12-21 20:54 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  const transactions = await TransactionService.getTransactionDetailsFromTransactionIdAndNonce(transactionId, nonce);
made the change

2021-12-21 21:27 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Just one nit about a duplicate constant

2021-12-21 21:27 UTC, steven-sheehy commented on hedera-mirror-rest/constants.js
> +const TRANSACTION_RESULT_SUCCESS = 22;
nit: Remove in favor of `const resultSuccess = transactionResult.getSuccessProtoId()` directly in utils.

2021-12-21 21:54 UTC, steven-sheehy approved these changes

2021-12-21 21:56 UTC, merged