Add contract logs to contract results
hashgraph/hedera-mirror-node pull request #3086
Opened 2021-12-29 22:34 UTC by ijungmann

Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-30 16:29 UTC, ijungmann commented on hedera-mirror-rest/service/contractService.js
> +  static contractLogsQuery = `select ${ContractLog.CONTRACT_ID},
I originally had a separate query for getting by timestamp, because we don't want to show the timestamp in the ContractLogs when they are returned with a ContractResult that already has the timestamp, but I figured it's a lot of code duplication to not fetch one extra field, so I left it up to the view model to remove it.

2021-12-30 16:31 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        delete logViewModel.timestamp;
Similar thought here, I could see having a separate class/constructor if we think `/logs` and the logs in `/results` will diverge at some point, but for now it felt wasteful to duplicate just to not map the timestamp.

2022-01-03 17:06 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-11-empty-logs.spec.json
> +  "description": "Contract results api call using contract id and timestamp",
Fix

2022-01-03 17:18 UTC, xin-hedera requested changes

2022-01-03 17:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected);
```suggestion
    expect(results).toIncludeSameMembers(expected);
```

2022-01-03 17:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected.slice(0, 1));
```suggestion
    expect(results).toIncludeSameMembers(expected.slice(0, 2));
```

2022-01-03 17:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected.slice(2));
```suggestion
    expect(results).toIncludeSameMembers(expected.slice(2));
```

2022-01-03 17:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected.slice(0, 1));
the `end` in `Array.slice` is exclusive and `toIncludeAllMembers` allows the `actual` has more elements than the `expected.

2022-01-03 17:18 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    ContractService.getContractLogsByTimestamps(timestamp),
in `/contracts/{contractId}/results/logs` the logs are by default ordered by consensus timestamp desc, and index desc. we should do the same for `getContractLogsByTimestamps`. and specifically for getting contract logs inside getting contract results by consensus timestamp / transaction ID, since the consensus timestamp is the same, it should effectively order by index desc by default.

2022-01-03 17:26 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +    ContractService.getContractLogsByTimestamps(timestamp),
I'm not sure I agree. Top level APIs return results ordered by timestamp in descending order both because users care more about recent data and it's more efficient to return newer data since it's more likely to be in memory.

For an individual contract result the user is attempting to understand what occurred during his contract call. It might make more sense to display it from beginning to end since it's logically harder to walk through your program from end to beginning. Also, from low to high is how the protobuf record shows it as.

2022-01-03 17:37 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    ContractService.getContractLogsByTimestamps(timestamp),
makes sense to me. then it's non-issue.

2022-01-03 17:39 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +    ContractService.getContractLogsByTimestamps(timestamp),
I agree with Steven here, I think it make sense to show the logs in ascending order to easily read through them.

2022-01-03 17:40 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected);
Fixed

2022-01-03 17:40 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected.slice(0, 1));
Fixed

2022-01-03 17:40 UTC, ijungmann commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +    expect(results).toIncludeAllMembers(expected.slice(2));
Fixed

2022-01-03 22:45 UTC, xin-hedera requested changes

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +        "consensus_timestamp": 167654000123456,
```suggestion
        "consensus_timestamp": "167654000123456",
```
consensus_timestamp can be larger than js Number MAX_SAFE_INTEGER, so we usually use a string everywhere in the json spec files.

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +        "contract_id": 5002,
```suggestion
        "contract_id": 5001,
```

I don't think it's possible under `/api/v1/5001/results/167654.000123456`, we have a log entry with a contract_id of `5002`

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-04-transactionid.spec.json
> +        "contract_id": 5002,
same issue here

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-05-transactionid-multiple-single-result.spec.json
> +        "contract_id": 5002,
same issue

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-11-empty-logs.spec.json
> +        "contract_id": 5002,
same contract_id issue here.

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: array
this is repeated in a couple of places. Should add it to `schema` and reference here.

2022-01-03 22:45 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +    ContractResultLog:
Can you try to use ContractResultLog as the base, and update `ContractLog` to be:

```yaml
ContractLog:
  allOf:
    - $ref: '#/components/schemas/ContractResultLog'
    - type: object
      properties:
        root_contract_id:
          description: The executed contract that created this contract log
          $ref: '#/components/schemas/EntityId'
        timestamp:
          $ref: '#/components/schemas/Timestamp'
```

2022-01-03 22:56 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +        "contract_id": 5002,
I believe we can.  If we want to show all logs for a given contract execution, that should include logs from any contracts called by that contract, so in this case contract 5001 would call contract 5002 and we would see the logs for both.  The rest of the details would be pertaining exclusively to 5001, but we want to include the full trace of the logs.

2022-01-03 23:09 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +        "contract_id": 5002,
Thanks for the clarification. Now I see the root contract id is 5001.

2022-01-04 00:33 UTC, steven-sheehy requested changes

2022-01-04 00:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded Ethereum topics
I don't think it's accurate to say ethereum.
```suggestion
          description: A list of hex encoded topics associated with this log event
```

2022-01-04 00:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded ethereum address of the contract
```suggestion
          description: The hex encoded Solidity address of the contract
```

2022-01-04 00:33 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (!_.isNil(contractLogs)) {
I'm not a fan of having the same viewmodel class represent different views. View models don't represent the database model so they shouldn't map one to one with it. Instead they should vary per view. We should split a `ContractResultDetailsViewModel` out of `ContractResultViewModel`. The former can inherit from the latter.

2022-01-04 00:33 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        delete logViewModel.timestamp;
Same comment. We should have a `ContractLogViewModel` that inherits from `ContractLogResultsViewModel`.

2022-01-04 03:04 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (!_.isNil(contractLogs)) {
If inheritance isn't possible, would probably prefer duplication.

2022-01-04 17:03 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +    ContractResultLog:
Done

2022-01-04 17:03 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: array
Done

2022-01-04 18:30 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (!_.isNil(contractLogs)) {
Sure, done.

2022-01-04 18:30 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded ethereum address of the contract
Done

2022-01-04 18:30 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded Ethereum topics
Done

2022-01-04 18:34 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        delete logViewModel.timestamp;
Sure, done

2022-01-04 19:55 UTC, xin-hedera requested changes

2022-01-04 19:55 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    }
```suggestion
  this.logs = contractLogs.map((contractLog) => new  ContractLogResultsViewModel(contractLog));
```

2022-01-04 19:55 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractLogResultsViewModel.js
> +class ContractLogResultsViewModel {
```suggestion
class ContractResultLogViewModel {
```

also update the comment

2022-01-04 20:41 UTC, steven-sheehy submitted a review, later dismissed
LGTM besides Xin's comments

2022-01-04 20:43 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractLogResultsViewModel.js
> +class ContractLogResultsViewModel {
Updated comments and name

2022-01-04 20:46 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    }
Fixed.

2022-01-04 21:26 UTC, xin-hedera approved these changes
LGTM

2022-01-04 21:52 UTC, steven-sheehy approved these changes

2022-01-04 22:47 UTC, merged