Support account alias in rest API
hashgraph/hedera-mirror-node pull request #3087
Opened 2021-12-30 00:20 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #2964 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-12-30 02:10 UTC, xin-hedera commented on hedera-mirror-rest/base32.js
> +  return data && base32Encode(data, variant, {padding: false});
The format is describe in the HIP, i.e., rfc4648 base32 encoding without padding.

2021-12-30 22:15 UTC, ijungmann requested changes
Looking at some of the tests still, just a couple nits and grammar things.

2021-12-30 22:15 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/accounts-08-invalid-param-values.spec.json
> +    "/api/v1/accounts?account.id=lte:0.1.2.3&account.balance=gt:9223372036854775808&account.publickey=-2&timestamp=-1.2&order=any&balance=1&account.alias=x"
Would suggest checking `0.0.x` in this second url, just to confirm the long version fails and to have something different.

2021-12-30 22:55 UTC, xin-hedera commented on hedera-mirror-rest/base32.js
> +const base32Regex = /^(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8})$/;
with that the regex can match a base32 string with a single full group of characters, i.e., 8 characters.

2021-12-30 22:55 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> + * @param balanceAccountQuery account balance account id query
because they are not optional

2022-01-03 21:18 UTC, ijungmann approved these changes

2022-01-04 17:53 UTC, steven-sheehy requested changes

2022-01-04 17:53 UTC, steven-sheehy commented on hedera-mirror-rest/base32.js
> +const isValidBase32Str = (str) => {
Since it's used within the `base32` context, it would be cleaner to just name it as `base32.isValid()`.

```suggestion
const isValid = (str) => {
```

2022-01-04 17:53 UTC, steven-sheehy commented on hedera-mirror-rest/package.json
> +    "base32-encode": "^1.2.0",
I'm concerned about having to use two libraries to encode and decode. It would be preferable to reduce dependencies. Also, base32-decode was last published 4 years ago.

What about using https://www.npmjs.com/package/rfc4648 which handles both and seems to be better maintained and more popular?

2022-01-04 17:53 UTC, steven-sheehy commented on hedera-mirror-rest/base32.js
> +const base32Regex = /^(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8})$/;
I think it would be preferable if the library would tell us if there's an error during decoding instead of re-implementing validation ourselves. Not sure if `base32-decode` supports that but looks like rfc4648 library will throw errors if invalid.

2022-01-04 17:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/accountAliasQueryParam'
We should also probably support `/api/v1/accounts/0.0.alias`. Perhaps in a follow up though.

2022-01-04 18:46 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/accountAliasQueryParam'
we should do one of the two not both imo. I actually wandered  between  `/accounts/0.0.alias` and `/accounts?account.alias=` at the beginning.

I don't really like the `account.alias` filter since it adds complexity, has greater risk of introducing performance issues, not so maintainable.

`/accounts/0.0.alias` is cleaner and can serve the same purpose. however, there's also performance cost since `/accounts/{accountId}` has to return a list of transactions of the account. For account alias, the two queries can't be  executed in parallel because the account id is needed to get the transactions.

2022-01-04 18:47 UTC, xin-hedera commented on hedera-mirror-rest/package.json
> +    "base32-encode": "^1.2.0",
that sounds a better library and should have all the features we need.

2022-01-07 00:27 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/config.test.js
> +  fs.rmSync(tempDir, {recursive: true});
`fs.rmdirSync` is marked as deprecated.

2022-01-07 00:41 UTC, xin-hedera commented on hedera-mirror-rest/base32.js
> +const base32Regex = /^(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8})$/;
removed

2022-01-07 00:41 UTC, xin-hedera commented on hedera-mirror-rest/base32.js
> +const isValidBase32Str = (str) => {
removed it completely

2022-01-07 00:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts-07-not-found.spec.json
> +    "/api/v1/accounts/AAAAAA5L3ZGSRVUCSPDR7TONZSRY3D5OMEBKQMVTD2AC6JL72HMQ",
non-existing alias, expect 404

2022-01-07 00:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts-07-not-found.spec.json
> +    "/api/v1/accounts/0.0.KGNABD5L3ZGSRVUCSPDR7TONZSRY3D5OMEBKQMVTD2AC6JL72HMQ"
alias maps to a deleted account, also expect 404

2022-01-07 00:45 UTC, xin-hedera commented on hedera-mirror-rest/accountAlias.js
> +const accountAliasRegex = /^(\d{1,5}\.){0,2}[A-Z2-7]+$/;
as explained in the comment, the regex and the base32.decode together would only allow valid base32 non-padding string from the RFC4648 alphabet.

2022-01-07 15:41 UTC, closed without merging