Remove rosetta token balance workaround
hashgraph/hedera-mirror-node pull request #3088
Opened 2021-12-30 17:31 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #2997

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-12-30 19:23 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/run-validation.sh
> +ROSETTA_CLI_VERSION=${ROSETTA_CLI_VERSION:-}
ran it locally without the default, got variable not bound error

2021-12-30 20:09 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account_test.go
> +
dedup the code so sonar check passes

2022-01-03 16:52 UTC, ijungmann requested changes
Looks good, one commented out line of code.

2022-01-03 16:52 UTC, ijungmann commented on hedera-mirror-rosetta/app/persistence/block_test.go
> +	// db.CreateDbRecords(dbClient, thirdRecordFile)
Remove

2022-01-03 18:07 UTC, ijungmann approved these changes
LGTM

2022-01-04 00:04 UTC, steven-sheehy approved these changes
LGTM

2022-01-04 02:02 UTC, merged