Add topic_message payer_account_id and chunk info
hashgraph/hedera-mirror-node pull request #3105
Opened 2022-01-06 03:14 UTC by ijungmann

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-06 17:49 UTC, steven-sheehy requested changes

2022-01-06 17:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                payerAccountId = EntityId.of(transactionID.getAccountID());
This isn't needed since chunk initial payer has to match subsequent chunk payers

2022-01-06 17:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/v1.52.0__topic_message_add_payer_account_id.sql
> +and tm.payer_account_id is null;
Need to mark it as not null here too.

2022-01-06 17:49 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/topicmessages-01-no-args.spec.json
> +        "chunk_total": 3,
HIP-171 has the format as:
```json
  "chunk_info": {
    "initial_transaction_id": "0.0.1000-1234567890-000000006",
    "number": 2,
    "total": 5
  },
```

Though how we should display the scheduled and nonce flag is not clear.

2022-01-06 17:49 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/topicmessages-01-no-args.spec.json
> +        "valid_start_timestamp": "1234567890000000010"
This timestamp is only applicable to the initial chunk, not every subsequent message. So it should be in the initial_transaction_id.

2022-01-06 18:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                  TransactionID transactionID = chunkInfo.getInitialTransactionID();
We have a bug in that we're not storing the `scheduled` and `nonce` fields so that when our gRPC API reconstitutes this field those are left off. We have a few options:

1. Add denormalized `initial_transaction_id` field that's bytea or jsonb
2. Add normalized `chunk_nonce` and `chunk_scheduled`
3. Send full `initial_transaction_id` on Redis message but do not persist. For historical messages would have to join with transaction table.

For 1 & 2 would have to decide whether to migrate past data as this table is huge and the migration would take a long time.

2022-01-14 03:09 UTC, ijungmann commented
Need to update openAPI, everything else should be good to go.

2022-01-14 03:12 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchInserterTest.java
> +        topicMessage.setPayerAccountId(EntityId.of("0.0.10", ACCOUNT));
Remove

2022-01-14 03:15 UTC, ijungmann commented on hedera-mirror-rest/model/topicMessage.js
> +  static CONSENSUS_TIMESTAMP = 'consensus_timestamp';
Add initial_transaction_id

2022-01-14 18:00 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/topicmessage-10-no-chunk-data.spec.json
> +        "chunk_total": null,
Right now I have it to where if we don't have a `chunk_num`, we don't return a `chunk_info` object at all.  Other option is to display it with null data.  Same goes for `nonce` and `scheduled` when we're missing the protobuf `initial_transaction_id`

2022-01-14 18:00 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/topicmessages-01-no-args.spec.json
> +        "chunk_total": 3,
Fixed it to this format.  Right now I just have the scheduled and nonce as separate fields in this object.

2022-01-14 18:00 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/topicmessages-01-no-args.spec.json
> +        "valid_start_timestamp": "1234567890000000010"
Done

2022-01-14 18:12 UTC, ijungmann commented on hedera-mirror-rest/__tests__/viewmodel/topicMessageViewModel.test.js
> +'use strict';
License

2022-01-14 18:23 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                  TransactionID transactionID = chunkInfo.getInitialTransactionID();
From last PR, went with option 1 in bytea.

2022-01-14 20:34 UTC, xin-hedera requested changes

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - initial_transaction_id
remove the required section.

```suggestion
      required:
        - number
        - total
        - initial_transaction_id
```

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  return new TopicMessageViewModel(topicMessage, messageEncoding);
can remove this function and move the corresponding tests to topicMessageViewModel.test.js

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/topicMessageViewModel.js
> +    }
might be better to set it to `null` or `{}` if it's not a chunked message.

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const createTransactionIdFromProto = (protoAccountId, protoTimestamp) => {
can just pass in the protobuf TransactionID, instead of two params.

can also move the code in `protobufTimestampToSecNsWithHyphen` here since this is the only place that function is used.

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +const {TopicMessageViewModel} = require('./viewmodel/index');
```suggestion
const {TopicMessageViewModel} = require('./viewmodel');
```

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  if (messages.length !== 1) {
validate length before creating the model objects

2022-01-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/topicmessage-09-with-initial-transaction-proto.spec.json
> +      "scheduled": true
having `nonce` and `schedule` here are very misleading, perhaps change it to a nested object:

```json
"chunk_info": {
   ...
   "initial_transaction": {
     "transactioin_id": "0.0.3-1234567890-000000321",
     "nonce": 1,
     "scheduled": true
   }
}
```

The other question is should we set `nonce` and `scheduled` for historical data where the info is missing?

2022-01-14 21:56 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    chunk_total: 1,
Done, and fixed spec tests

2022-01-14 21:56 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    valid_start_timestamp: '1628751573995691000',
Done

2022-01-15 01:10 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - initial_transaction_id
Removed

2022-01-15 01:11 UTC, ijungmann commented on hedera-mirror-rest/topicmessage.js
> +  return new TopicMessageViewModel(topicMessage, messageEncoding);
Removed, I went ahead and removed the test as the tests already in the view model should cover everything.

2022-01-15 01:16 UTC, ijungmann commented on hedera-mirror-rest/topicmessage.js
> +  if (messages.length !== 1) {
Done

2022-01-15 01:27 UTC, ijungmann commented on hedera-mirror-rest/topicmessage.js
> +const {TopicMessageViewModel} = require('./viewmodel/index');
Fixed

2022-01-16 16:56 UTC, steven-sheehy requested changes

2022-01-16 16:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        initial_transaction_id:
nit: sort keys here and in the two examples below

2022-01-16 16:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: boolean
`nonce` and `scheduled` should be marked nullable

2022-01-16 16:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ChunkInfo'
nullable

2022-01-16 17:00 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/topicmessage-09-with-initial-transaction-proto.spec.json
> +      "scheduled": true
I'm not a fan of the above. Either keep it as is or normalize everything into a nested object:
```json
"chunk_info": {
   ...
   "initial_transaction_id": {
     "account_id": "0.0.3",
     "nonce": 1,
     "scheduled": true,
     "transaction_valid_start": "1234567890-000000321"
   }
}

2022-01-18 17:34 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/topicmessages-13-with-chunk-data.spec.json
> +          "initial_transaction_id": "0.0.3-1234567890-000000321",
such chucked messages will fail with `INVALID_CHUNK_TRANSACTION_ID`

2022-01-18 17:49 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/topicMessageViewModel.js
> +    }
Done

2022-01-18 17:49 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/topicmessage-09-with-initial-transaction-proto.spec.json
> +      "scheduled": true
As is with it not broken out fits the HIP.  I've left it as is for now, but reordered things alphabetically.

2022-01-18 17:49 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/topicMessageViewModel.js
> +    Object.assign(this, {
Removed.

2022-01-18 17:49 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/topicMessageViewModel.js
> +      topic_id: EntityId.parse(topicMessage.topicId).toString(),
Done

2022-01-18 17:50 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/topicMessageViewModel.js
> +      this.scheduled = transactionId.scheduled;
Done, made them null if not present.

2022-01-18 17:50 UTC, ijungmann commented on hedera-mirror-rest/viewmodel/topicMessageViewModel.js
> +    Object.assign(this, {
Removed and reordered

2022-01-18 17:50 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: boolean
Done.

2022-01-18 17:51 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/ChunkInfo'
Added in the object definition.

2022-01-18 17:55 UTC, ijungmann commented on hedera-mirror-rest/api/v1/openapi.yml
> +        initial_transaction_id:
Done

2022-01-18 18:09 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/topicmessages-13-with-chunk-data.spec.json
> +          "initial_transaction_id": "0.0.3-1234567890-000000321",
Yeah, see [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/txns/consensus/SubmitMessageTransitionLogic.java#L101)

2022-01-18 18:12 UTC, ijungmann commented on hedera-mirror-rest/__tests__/specs/topicmessage-09-with-chunk-initial-transaction-proto.spec.json
> +      "initial_transaction_id": "0.0.3-1234567890-000000321",
Yeah, good catch.  Should be fixed now.

2022-01-18 20:09 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +const createTransactionIdFromProto = (protoAccountId, protoTimestamp) => {
Done

2022-01-18 20:50 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/topicmessages-13-with-chunk-data.spec.json
> +          "initial_transaction_id": "0.0.3-1234567890-000000321",
Okay

2022-01-19 00:20 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-01-19 17:30 UTC, Nana-EC approved these changes
LGTM

2022-01-19 17:37 UTC, steven-sheehy approved these changes

2022-01-19 17:47 UTC, xin-hedera requested changes

2022-01-19 17:47 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/viewmodel/topicMessageViewModel.test.js
> +    const actual = new TopicMessageViewModel(input, '');
need one test case with explicit `base64` encoding

```suggestion
    const actual = new TopicMessageViewModel(input, 'base64');
```

2022-01-19 17:47 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  const entityStr = EntityId.of(
nit, can extract the two properties from protoTransactionId and then most lines should be within the width limit, just to avoid the ugly pretty formatting.

```javascript
  const {accountID, transactionValidStart} = protoTransactionId;
```

2022-01-19 18:25 UTC, ijungmann commented on hedera-mirror-rest/__tests__/viewmodel/topicMessageViewModel.test.js
> +    const actual = new TopicMessageViewModel(input, '');
Done

2022-01-19 18:25 UTC, ijungmann commented on hedera-mirror-rest/utils.js
> +  const entityStr = EntityId.of(
Done

2022-01-19 18:38 UTC, xin-hedera approved these changes
LGTM

2022-01-19 21:09 UTC, Nana-EC approved these changes

2022-01-19 21:20 UTC, merged