updates
hashgraph/hedera-mirror-node pull request #3108
Opened 2022-01-07 05:56 UTC by SimiHunjan

Signed-off-by: SimiHunjan <simi.hunjan.k@gmail.com>

**Description**:

Updated content

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-07 19:33 UTC, steven-sheehy requested changes

2022-01-07 19:33 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: 0.0.10 or 10
We also support the `realm.num` format for this and others.

2022-01-07 19:37 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: 0.0.10 or 10
second that. And this is actually among the failures reported in the github workflow run.

2022-01-07 19:38 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    tokpicIdPathParam:
Also, where is this used?

2022-01-07 19:43 UTC, xin-hedera requested changes

2022-01-07 19:43 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      in: path
need to add `required: true`

github workflow failed:

```
-attribute components.parameters.For path parameter contractIdPathParam the required value should be true
```

2022-01-07 19:43 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
>          entityNumNoOperator:
```suggestion
        contractNumNoOperator:
```
applies to every `entityNum` in this examples section

2022-01-12 08:53 UTC, SimiHunjan commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: 0.0.10 or 10
removed the places where I example and examples existed

2022-01-12 08:56 UTC, SimiHunjan commented on hedera-mirror-rest/api/v1/openapi.yml
> +      name: serial.number
aw darn I thought there was maybe a patten to follow for query params vs. path params in the naming convention. Reverted back.

2022-01-12 08:58 UTC, SimiHunjan commented on hedera-mirror-rest/api/v1/openapi.yml
> +    tokpicIdPathParam:
![Screen Shot 2022-01-12 at 12 58 11 AM](https://user-images.githubusercontent.com/21989138/149096109-ddefc2cf-774d-49cf-a2bd-3cf86fd703fe.png)

2022-01-12 09:00 UTC, SimiHunjan commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: 0.0.10 or 10
updated

2022-01-12 09:24 UTC, SimiHunjan commented on hedera-mirror-rest/api/v1/openapi.yml
> +      name: contractId
fixed

2022-01-12 20:20 UTC, SimiHunjan commented
reference: https://github.com/hashgraph/hedera-mirror-node/pull/3132

2022-01-12 20:20 UTC, closed without merging