Add initial transaction
hashgraph/hedera-mirror-node pull request #3128
Opened 2022-01-10 18:44 UTC by ijungmann

**Description**:
Add initial transaction id bytes to topic message, and set payer account id on topic message for unchunked messages.

* Add initial transaction id bytes to topic message
* Alter logic to set payer account id on all topic messages
* Add migration to add payer account id to existing messages

**Related issue(s)**:

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-11 02:19 UTC, xin-hedera requested changes

2022-01-11 02:19 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessagePayerAccountIdMigrationTest.java
> +                                    " " +
nit:
```suggestion
```

2022-01-11 02:19 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessagePayerAccountIdMigrationTest.java
> +                                    " (?, ?, ?, ?, ?, ?, ?)",
nit:
```suggestion
                                    " values (?, ?, ?, ?, ?, ?, ?)",
```

2022-01-11 02:19 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
>          // given
the test case assumes the payer account id if `initialTransactionID` is not set, the changes made don't match the scenario. Need to check if services validate `initialTransactionID`. If indeed this is possible, we can't constraint `payer_account_id` to be `not null`.

update: there is `INVALID_CHUNK_TRANSACTION_ID` error code. so the test case itself looks invalid.

2022-01-11 02:19 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
> +            if (initialTransactionID != null) {
is it possible when chunkNum != null, initialTransactionID is not set in the protobuf message `chunkInfo`? need to check with services

2022-01-11 04:15 UTC, steven-sheehy requested changes

2022-01-11 04:15 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/topic/TopicMessage.java
> +    private byte[] initialTransactionId;
You also need to update grpc's separate copy of `TopicMessage` to add it. We haven't deduped the grpc module yet.

Most importantly, you need to change `TopicMessage::toResponse` to properly set the initial transaction ID from the byte[] and fallback to payer account plus valid start if not present. This change was the real reason for this PR.

2022-01-11 04:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.52.1__topic_message_add_payer_account_id_and_initial_transaction_id.sql
> +alter column payer_account_id set not null;
I would like to see how long this statement takes to run against a mainnet dump of topic_message before seeing if it's worthwhile to include. If it's hours we can probably skip it and just do in v2.

2022-01-11 04:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.52.1__topic_message_add_payer_account_id_and_initial_transaction_id.sql
> +add column initial_transaction_id bytea null;
If we keep both alters, combine them into a single alter.

2022-01-11 05:11 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.52.1__topic_message_add_payer_account_id_and_initial_transaction_id.sql
> +-------------------
Fixed

2022-01-11 05:11 UTC, ijungmann commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +     VALUES ($1, $2, $3, $4, $5, $6, $7);`,
Had to update the specs to use the correct field names, but it's all fixed now.

2022-01-11 05:14 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessagePayerAccountIdMigrationTest.java
> +                                    " " +
Fixed

2022-01-11 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
> +        TransactionID initialTransactionId = createTransactionID(PAYER_ACCOUNT_ID.getEntityNum(),
should leave payerAccountID in initialTransactionID not set, the test case should then assert the payerAccountId is that of the transaction as well as the initialTransactionID protobuf bytes matches although payerAccountId is 0.

2022-01-11 16:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                          DomainUtils.timestampInNanosMax(transactionID.getTransactionValidStart()));
I don't think we need to `validStartTimestamp` anymore since the info is in `initialTransactionId` bytes

2022-01-12 01:34 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
> +            if (initialTransactionID != null) {
I haven't seen anything to suggest it's possible, but we've had a check [here](https://github.com/hashgraph/hedera-mirror-node/pull/3128/files#diff-8572a9f51d2cec66fffa0f2436ff0c0977a696b48a62a5168fe1b23a91f59e83R330-R335) for this scenario.

2022-01-12 17:38 UTC, ijungmann commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/topic/TopicMessage.java
> +    private byte[] initialTransactionId;
Added

2022-01-12 17:48 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessagePayerAccountIdMigrationTest.java
> +                                    " (?, ?, ?, ?, ?, ?, ?)",
Fixed

2022-01-12 17:50 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    initial_transaction_id  bytea,
Added to `Restore`, the backup file doesn't list fields

2022-01-12 18:24 UTC, ijungmann commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>                          DomainUtils.timestampInNanosMax(transactionID.getTransactionValidStart()));
Sure, removed

2022-01-12 18:25 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
> +        TransactionID initialTransactionId = createTransactionID(PAYER_ACCOUNT_ID.getEntityNum(),
Done

2022-01-12 18:25 UTC, ijungmann commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
>          // given
Fixed this test

2022-01-12 20:42 UTC, steven-sheehy requested changes

2022-01-12 20:42 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/domain/DomainBuilder.java
> +                .payerAccountId(10L)
Duplicate

2022-01-12 20:42 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/domain/DomainBuilder.java
>                  .consensusTimestamp(now.plus(sequenceNumber, ChronoUnit.NANOS))
Should probably add an initialTransactionID since we generally want to populate all fields for tests.

2022-01-12 20:42 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +    private TransactionID initialTransactionIdObject = parseTransactionID(initialTransactionId);
I don't think we need this lazy getter since this field is only ever needed once inside `toResponse()` unlike the other lazy fields. Can just push into `toResponse()`.

2022-01-12 20:42 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  console.log(`Start is ${message.toString()}`);
Think the two console logs here are temporary for local debugging?

2022-01-12 22:08 UTC, xin-hedera commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
> +        }
code coverage dropped a lot, should add a test class for it.

2022-01-12 23:54 UTC, steven-sheehy approved these changes
LGTM

2022-01-12 23:58 UTC, xin-hedera approved these changes
LGTM

2022-01-13 01:37 UTC, steven-sheehy commented
Need to merge from main to resolve the security check

2022-01-13 03:07 UTC, merged