Fixes after contract API review
hashgraph/hedera-mirror-node pull request #3130
Opened 2022-01-11 15:44 UTC by steven-sheehy

**Description**:
* Add an empty value as default example in OpenAPI `examples` list
* Change `/api/v1/contracts/:id/results` to make `0x` prefix optional for `from` parameter
* Change `/api/v1/contracts/:id/results/logs` to return 200 instead of 204 for no data
* Change `/api/v1/tokens/:id/nfts` to return 200 instead of 204 for no data
* Change `/api/v1/tokens/:id/nfts/:serial/transactions` to return 200 instead of 204 for no data
* Fix various OpenAPI bugs and docs
* Fix Web3 API max header size too low
* Workaround #2914 by disabling re-validation of nodes

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-01-11 17:50 UTC, xin-hedera requested changes

2022-01-11 17:50 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  res.locals.statusCode = httpStatusCodes.OK.code;
default is 200 so can remove this line.

2022-01-11 17:50 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +    throw new NotFoundError(); // 404 if no transactions are present
probably either

1) always return 200 no matter whether there's data from db or not
1) return 404 when there's no data from db, 200 otherwise

2022-01-11 17:50 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +                    )`;
the auto formatting looks weird...

2022-01-11 18:11 UTC, ijungmann reviewed
One nit

2022-01-11 18:11 UTC, ijungmann commented on hedera-mirror-rest/controllers/contractController.js
> +                    )`;
nit: formatting

2022-01-11 19:24 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +                    )`;
Reverted

2022-01-11 19:24 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +                    )`;
Reverted

2022-01-11 19:25 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  res.locals.statusCode = httpStatusCodes.OK.code;
Removed

2022-01-11 19:25 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +    throw new NotFoundError(); // 404 if no transactions are present
I removed it.

2022-01-11 20:06 UTC, xin-hedera approved these changes
LGTM

2022-01-12 01:05 UTC, ijungmann approved these changes

2022-01-12 01:06 UTC, merged