Add a get address book nodes gRPC API
hashgraph/hedera-mirror-node pull request #3141
Opened 2022-01-15 01:38 UTC by steven-sheehy

**Description**:
* Add a `NetworkService.getNodes()` gRPC API
* Change `AddressBookEntry` and `AddressBookServiceEndpoint` to use `@IdClass`
* Change `TopicMessageFilter` to use `EntityId` instead of long
* Fix `AddressBookServiceEndpoint` incorrectly modeling `nodeId` as `EntityId`
* Move `DomainBuilder` to common module

**Related issue(s)**:

Fixes #3098 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-01-15 01:50 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java
> +                .setTopicID(TopicID.newBuilder().setRealmNum(0).setTopicNum(100).build())
`0.0.0` now throws an error so had to change default topic everywhere from that to `0.0.100`.

2022-01-15 01:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AddressBookServiceEndpointRepositoryTest.java
> -                .containsSequence(80, 443, 8000, 8443);
Not sure how this test didn't fail half the time due to non-deterministic order.

2022-01-18 20:48 UTC, Nana-EC requested changes
1st pass

2022-01-18 20:48 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/ProtoUtil.java
> +        log.warn("Client error {}: {}", t.getClass().getSimpleName(), t.getMessage());
```suggestion
        log.error("Client error {}: {}", t.getClass().getSimpleName(), t.getMessage());
```

2022-01-18 20:48 UTC, Nana-EC commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java
> +                .setTopicID(TopicID.newBuilder().setRealmNum(0).setTopicNum(100).build())
nit: create a private reusable default topic id for all updated places.

2022-01-18 20:52 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/ProtoUtil.java
> +        log.warn("Client error {}: {}", t.getClass().getSimpleName(), t.getMessage());
User input is not appropriate for an error level log. This warning log is what we already do for our subscribe topic API.

2022-01-18 21:11 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java
> +                .setTopicID(TopicID.newBuilder().setRealmNum(0).setTopicNum(100).build())
I'd rather not as I prefer to switch out the gRPC `DomainBuilder` with the common `DomainBuilder` in the future in which case each test will have potentially different topics instead of all the same hardcoded one.

2022-01-19 00:09 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/ProtoUtil.java
> +        log.warn("Client error {}: {}", t.getClass().getSimpleName(), t.getMessage());
Okay

2022-01-19 17:36 UTC, ijungmann reviewed
Will give second pass, didn't see anything not mentioned by Nana already.

2022-01-19 18:26 UTC, xin-hedera approved these changes
LGTM

2022-01-19 20:49 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/config/CacheConfiguration.java
> +                .maximumSize(50L));
It will be a long time before we need more than 50 since each cache entry is the number of pages in the cache. Since we have two address book files that means they each can have 25 pages in the cache or 250 nodes worth of data. But added anyway.

2022-01-19 20:49 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.grpc.addressbook.pageSize`                   | 10               | The maximum amount of address book entries to return in a single page
Updated

2022-01-19 20:49 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/NetworkServiceImpl.java
> +        long getNodeId() {
Updated to `getNextNodeId()`

2022-01-19 21:08 UTC, Nana-EC submitted a review, later dismissed
LGTM

2022-01-19 21:10 UTC, ijungmann approved these changes

2022-01-19 22:37 UTC, xin-hedera approved these changes
LGTM

2022-01-19 22:56 UTC, merged