Add k6 tests
hashgraph/hedera-mirror-node pull request #3174
Opened 2022-01-19 02:40 UTC by xin-hedera

**Description**:

This PR adds k6 tests for mirrornode rest, rosetta, and web3 APIs.

**Related issue(s)**:

Fixes #3173

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-01-19 02:41 UTC, xin-hedera commented on hedera-mirror-test/k6/README.md
> +To run a test suite, for example, for rosetta, use the following command.
picked rosetta as the example just because it has a good amount of scenarios, not too many like rest (33), not too few as web3 (just 1).

2022-01-19 02:43 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/common.js
> +  executor: 'constant-vus',
k6 doc:

A fixed number of VUs execute as many iterations as possible for a specified amount of time. This executor is equivalent to the global vus and duration options.

2022-01-19 02:45 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/common.js
> +  exec: 'run',
this limits every js test file to export the same `run` function. it also limits to one scenario per js test file. we can extend it later to support multiple scenarios per js test file if needed.

2022-01-19 02:46 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/common.js
> +      scenario.startTime = getNextStartTime(startTime, duration, gracefulStop);
this scenario will begin at the previous scenario's startTime + the configured scenario duration + the configured graceful stop, so scenarios never step on each other's toes.

2022-01-19 02:48 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/apis.js
> +import exec from 'k6/execution';
the test suite's entrance js file, it's mostly the same for each suite.

2022-01-19 02:48 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_ACCOUNT="0.0.2085134"
need to find values for mainnet for most of this env file

2022-01-19 02:49 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/accounts.js
> +
this is a single test js file. It's the same template and usually what differs include the url, the params, and any API specific handling.

2022-01-19 02:50 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/apis.js
> +import {markdownReport} from '../lib/common.js';
can't do

```javascript
import {markdownReport} from '../lib/common';
```

The js engine in k6 doesn't support it.

2022-01-19 02:51 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/apis.js
> +import {funcs, options, scenarioDurationGauge} from './test/index.js';
can't do

```javascript
import {funcs, options, scenarioDurationGauge} from './test';
```

Not supported by the js engine in k6.

2022-01-19 02:53 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/apis.js
> +  funcs[scenario.name]();
run the actual scenario handler defined in the corresponding test js file.

2022-01-19 02:54 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/apis.js
> +  scenarioDurationGauge.add(Date.now() - scenario.startTime, {scenario: scenario.name});
record the duration of the scenario with the scenario duration gauge so later in markdownReport we can correctly calculate the scenario RPS.

2022-01-19 03:12 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/common.js
> +      const scenario = Object.assign({}, testScenarios[scenarioName]);
the ... (spread operator) is not supported by the js engine in k6.

So to merge / shallow clone an object, we have to use `Object.assign`

2022-01-19 16:31 UTC, Nana-EC requested changes
Looking good on 1st pass. Left some comments

2022-01-19 16:31 UTC, Nana-EC commented on hedera-mirror-test/k6/src/rest/k6.env
> +# 0.0.1550443 0.0.1549551
Is this comment leftover or does it signify related accounts or entities?

2022-01-19 16:31 UTC, Nana-EC commented on hedera-mirror-test/k6/src/rest/k6.env
> +# 1640313900.458681000 0.0.1530472
q: leftover or useful info?

2022-01-19 16:31 UTC, Nana-EC commented on hedera-mirror-test/k6/src/rest/test/accounts.js
> +const urlTag = '/accounts';
With the similar templates should we just move the main method logic to one file that each of these test js files can utilize?

The method logic I think it would be 
- the http call to get the response
- the response check with a provided text
- the status return  

```suggestion
function getAndValidateResponse(url, message) {
  const response = http.get(url);
  return check(response, {
    message: (r) => r.status === 200,
  });
}
```

2022-01-19 17:20 UTC, xin-hedera commented on hedera-mirror-test/k6/README.md
> +The test suite will run the tests sequentially with a configurable graceful stop time in between, so they don't
`graceful stop time` is the term in k6; don't want to add the `runs` since it's in between the tests.

2022-01-19 17:22 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/k6.env
> +# 0.0.1550443 0.0.1549551
need to clean up and update the values for mainnet, these are literally copied from the hedera-testing repo

2022-01-19 17:34 UTC, Nana-EC commented on hedera-mirror-test/k6/README.md
> +The test suite will run the tests sequentially with a configurable graceful stop time in between, so they don't
Works for me

2022-01-20 17:12 UTC, xin-hedera commented on hedera-mirror-test/k6/README.md
> +This module covers the [k6](https://k6.io/) based performance tests for mirrornode APIs including rest, rosetta,
updated

2022-01-20 17:13 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/common.js
> +const timeRegex = /^[0-9]+s$/;
prefer to leave them close to where they are used

2022-01-20 17:14 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/accounts.js
> +const urlTag = '/accounts';
added `TestScenarioBuilder` in common.js, had to do it in the old js function way due to some weird js compatibility issue that js class doesn't work. still have to update all the rest test cases to use the builder.

2022-01-20 22:10 UTC, ijungmann reviewed
A couple of nits, nothing else really that hasn't already been noted by Nana.

2022-01-21 16:59 UTC, ijungmann approved these changes
LGTM

2022-01-21 18:06 UTC, Nana-EC approved these changes
LGTM

2022-01-21 18:07 UTC, Nana-EC commented on hedera-mirror-test/k6/src/lib/common.js
> +const timeRegex = /^[0-9]+s$/;
That's fine

2022-01-21 20:25 UTC, steven-sheehy requested changes

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_TRANSACTION=0.0.41105-1639588975-970321494
All of these hardcoded, environment specific defaults (besides limit) need to be removed in favor of dynamically retrieving them from the environment. A bootstrap process could query the list APIs to get some sample values and use those for the duration of the test. Even better, it could list 100 then use all 100 in a round robin fashion for the test.

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/apis.js
> +import {textSummary} from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';
Can we define this as a constant in one file so in case the version changes we don't have to update multiple places? k6 doesn't support package management?

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/index.js
> +import {getSequentialTestScenarios} from '../../lib/common.js';
Any way to use non-relative paths? module aliasing?

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/ethBlockNumber.js
> +  .check('eth_blockNumber', (r) => r.status === 200)
JSON-RPC always return 200. Need to check payload code

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rosetta/k6.env
> +export ROSETTA_ACCOUNT_NUM=98
Same comment. Any value that is environment specific should be looked up dynamically if it all possible. Data that's guaranteed to be in the env like 0.0.98 might be fine. But others like block and even rosetta network can be looked up.

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contracts.js
> +const url = `${__ENV.BASE_URL}${urlPrefix}${urlTag}?limit=${__ENV.DEFAULT_LIMIT}`;
Could add `${__ENV.BASE_URL}` to `urlPrefix` in constant to stay DRY

2022-01-21 20:25 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/transactions.js
> +  .check('Transactions OK', (r) => r.status === 200)
For all list APIs we should also check that list is non-empty or matches limit

2022-01-21 20:34 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/apis.js
> +import {textSummary} from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';
can't do it, would result in SyntaxError: Unexpected token, likely reported by the k6 js source code parser.

there can be package management, but the particular k6-summary module isn't registered anywhere :(

2022-01-21 20:37 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/contracts.js
> +const url = `${__ENV.BASE_URL}${urlPrefix}${urlTag}?limit=${__ENV.DEFAULT_LIMIT}`;
can do that. it's actually from the change to support composing url from baseUrl + nextLink in one single test.

2022-01-21 21:08 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/index.js
> +import {getSequentialTestScenarios} from '../../lib/common.js';
possible with webpack as the bundler which provides more versatile module search support than the k6 `import`. However, don't think it's worth the effort atm

2022-01-24 16:21 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/index.js
> +import * as balances from './balances.js';
Can we add a `balances?account.id=` test?

2022-02-11 18:51 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/index.js
> +import {getSequentialTestScenarios} from '../../lib/common.js';
Also, as the time passes we would increase a lot our coupling to webpack.

2022-02-15 03:22 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_TRANSACTION=0.0.41105-1639588975-970321494
Done.

2022-02-15 03:40 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rosetta/k6.env
> +export ROSETTA_ACCOUNT_NUM=98
Already addressed by the comment above. See read me and `bootstrapEnvParameters`.

2022-02-15 14:19 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/ethBlockNumber.js
> +  .check('eth_blockNumber', (r) => r.status === 200)
You are right. The test has been fixed.

2022-02-15 20:26 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/index.js
> +import * as balances from './balances.js';
Done.

2022-02-16 22:58 UTC, steven-sheehy requested changes

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  const envParametersFile = fs.openSync(`${__dirname}/${configuration.env}.env`, 'w', 0o700);
Not portable to Windows

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/config/mainnet.env
> +export DEFAULT_ACCOUNT=0.0.699411
I don't think this file should be checked in.

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_ACCOUNT=0.0.41105
We shouldn't have hardcoded values checked in as they give a false impression that we can use these values for any network.

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/transactionsAccountId.js
> +  .check('Transactions by account id OK', (r) => responseHasListWithValidSize(r, "transactions"))
Use a constant for `"transactions"` and every other file that checks things per request.

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsBalanceFalsePubkey.js
> +  .check('Accounts balance false with publickey OK', (r) => responseHasListWithSize(r, "accounts", 1))
It's possible more than one account can have the same public key. So we shouldn't assume an expected upper bound of the list.

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  if(response.status !== 200){
Some APIs return other 2xx response codes

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/common.js
> +export { responseHasListWithValidSize, responseHasNonEmptyList, responseHasListWithSize };
I think we can get in trouble if we check the payloads too strictly. I think we should just have a single `isValidListResponse(response, listName)` instead of these 3 similar ones.

```javascript
function isValidListResponse(response, listName) {
  if (response.status < 200 || response.status >= 300) {
    return false;
  }

  const body = JSON.parse(response.body);
  const list = body[listName];

  if (!Array.isArray(list)) {
    return false;
  }

  return list.length > 0;
}
```

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsId.js
> +  .check('Accounts Id OK', (r) => r.status === 200)
We should add a `isSuccess(r)` and also check 200-299

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  if(configuration.env === null){
I don't think this property is useful as it only controls the output name.

2022-02-16 22:58 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +export DEFAULT_TOKEN=${testParameters.token}
The naming is inconsistent. Some have `_ID` and others do not. We should probably add `_ID` or `Id` to the relevant ones.

2022-02-18 15:28 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +const http = require('http');
Fixed.

2022-02-18 15:28 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +function isNonErrorResponse(response){
Fixed.

2022-02-18 15:29 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/README.md
> +The k6 test engine ris needed to run the tests. Please follow
Fixed.

2022-02-18 15:35 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    return body["error"] === undefined && body["error_code"] === undefined;
This function was created to verify if a response if a non error response. The fields "error" or "error_code" are used. I have tested this code. Also, I prefer to do `object[property] === undefined` instead of doing `object.hasOwnProperty`, since I don't know how the `object` was built, and because of that I don't know if the `property` belongs to the `object` itself or some parent in the prototype chain.

2022-02-18 15:48 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    return body["error"] === undefined && body["error_code"] === undefined;
Done.

2022-02-18 16:57 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    console.log(e);
I'm not sure what you mean. I'm saying delete `console.log(e)`
```suggestion
```

2022-02-18 17:02 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    return body["error"] === undefined && body["error_code"] === undefined;
Your logic is wrong. There is no `error_code` field generated in any JSON-RPC response. So of course `body["error_code"] === undefined` will pass because the field never exists in successful or unsuccessful responses. Please adjust it to my logic above that checks both `result` and `error`.

I prefer `hasOwnProperty` because `object[property]` checks the value of at the key whereas we need to check that the actual key is present or not. JSON-RPC is weird in that it omits keys depending upon success or not, unlike normal JSON payloads where the key is always present.

2022-02-21 19:16 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    console.log(e);
I was saying that the time wasted on the `console.log` call would not be taken into consideration when calculating the total time to execute the test. So there was no need to remove the call, but I removed. Done.

2022-02-21 19:22 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +export DEFAULT_TOKEN=${testParameters.token}
I just followed the current names for the env variables. If I rename them here, I am gonna have to rename their usage in all the current tests. Is that ok for you?

2022-02-21 19:42 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    return body["error"] === undefined && body["error_code"] === undefined;
The `error_code` was inside the response object, and not inside the `body`. I have fixed the code. Done.

2022-02-21 19:54 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  return 0 < list.length;
Done.

2022-02-21 20:01 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/mainnet.env
> +export DEFAULT_ACCOUNT=0.0.699411
Removed.

2022-02-21 20:06 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +export { responseHasListWithValidSize, responseHasNonEmptyList, responseHasListWithSize };
What kind of trouble? It took me a lot of time to pass through every test and check which function should be used. If we want to change, we must be aware that the same time will be spent, because I need to verify that the tests are still working.

2022-02-21 20:07 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_ACCOUNT=0.0.41105
What do you suggest we do?

2022-02-21 20:09 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  const envParametersFile = fs.openSync(`${__dirname}/${configuration.env}.env`, 'w', 0o700);
I did not know about this requirement. Instead of preparing the entire code to handle windows and linux, I am thinking about asking the user to redirect the output from stdout to a `.env` file. Is that ok for you?

2022-02-21 20:23 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_ACCOUNT=0.0.41105
I've already suggested previously. The tests should dynamically bootstrap itself with environment data. This environment specific configuration should only be used to override the dynamic values if it they're populated.

2022-02-21 20:29 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/common.js
> +export { responseHasListWithValidSize, responseHasNonEmptyList, responseHasListWithSize };
I've mentioned some examples in the other comments. You've assumed that an account by public key only has one result, which is not always the case. The responses highly vary per environment and per request input.

We're not trying to write functional tests, we just want to do the minimal amount of work to verify it's a success response. Thus I don't think we should be verifying the exact bounds of lists being returned, only that it's non-empty.

2022-02-22 13:10 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  if(response.status !== 200){
Done.

2022-02-22 13:11 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/accountsBalanceFalsePubkey.js
> +  .check('Accounts balance false with publickey OK', (r) => responseHasListWithSize(r, "accounts", 1))
Fixed. Only checking for non empty list now.

2022-02-22 13:29 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/balancesAccount.js
> +const url = `${__ENV.BASE_URL}${urlPrefix}${urlTag}?account.id=eq:${__ENV.DEFAULT_ACCOUNT}`;
Done.

2022-02-22 13:37 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/transactionsAccountId.js
> +  .check('Transactions by account id OK', (r) => responseHasListWithValidSize(r, "transactions"))
I don't think this is needed, V8 should be smart enough to optimize this. See https://stackoverflow.com/questions/41742970/const-vs-inline-string-literal-compilation-optimisation

2022-02-22 13:46 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/accountsId.js
> +  .check('Accounts Id OK', (r) => r.status === 200)
Done.

2022-02-22 14:02 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/k6.env
> +export DEFAULT_ACCOUNT=0.0.41105
ok. I removed the .env files.

2022-02-22 15:38 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/transactionsAccountId.js
> +  .check('Transactions by account id OK', (r) => responseHasListWithValidSize(r, "transactions"))
Except k6 doesn't use V8, it uses a Golang-based interpreter called [Goja](https://github.com/dop251/goja).

2022-02-22 15:45 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  if(!response.hasOwnProperty(statusField)){
There's only one API that has a `status` field, I believe (contract result details). That means this check will show responses as failures if applied to any other API. This should be removed.

BTW, Contract results still show up even if the transaction fails, so from the point of view of the performance test a `status=0x0` is still successful since it returns 2xx.

2022-02-22 15:47 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +export DEFAULT_TOKEN=${testParameters.token}
Yes, we should standardize now before people start depending upon the inconsistent naming. Regardless, my other suggestion says we should move away from using environment variables directly in the tests and inject a config class that abstracts dynamic vs user-configured variables.

2022-02-22 15:49 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +=======
Merge conflicts in this class.

2022-02-22 15:56 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contracts.js
> +const url = `${__ENV.BASE_URL}${urlPrefix}${urlTag}?limit=${__ENV.DEFAULT_LIMIT}`;
I'm not sure that's a compelling argument. We're not going to have a v2 for a long time and if we did the same fix you suggested above could be applied to using `getUrl()`: for those v2 APIs just don't call `getUrl` and hardcode it directly in the test. Or create a `getV2Url()`, `getUrl(path, version='v1')` overload, etc. But we can revisit this later so will resolve.

2022-02-22 15:59 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  const envParametersFile = fs.openSync(`${__dirname}/${configuration.env}.env`, 'w', 0o700);
The requirement isn't necessarily to ensure the entire code base can handle Windows, just to fix the portability issues as they arise. But as noted in another comment, I don't think we should be writing files but dynamically populating the environment specific variables in memory. So this line may go away.

2022-02-22 17:13 UTC, matheus-dallrosa commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +=======
Yes, I had to wait people get online to fix it. Done.

2022-02-22 17:14 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  if(!response.hasOwnProperty(statusField)){
This `status` field is the one from the response object, no from the body that is written by the route. I believe that each HTTP response should have the `status` field. I don't think we are talking about the same `status` field.

2022-02-22 17:38 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  const envParametersFile = fs.openSync(`${__dirname}/${configuration.env}.env`, 'w', 0o700);
Ok.

2022-02-22 17:59 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +export { responseHasListWithValidSize, responseHasNonEmptyList, responseHasListWithSize };
Done.

2022-02-22 18:42 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/transactionsAccountId.js
> +  .check('Transactions by account id OK', (r) => responseHasListWithValidSize(r, "transactions"))
Done.

2022-02-22 19:19 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +  try{
I have installed husky, and reformatted the files. Done.

2022-02-22 19:30 UTC, Nana-EC requested changes
Looking good.
A few suggestions around
- formatting of methods
- code reuse
- spacing conventions

2022-02-22 19:30 UTC, Nana-EC commented on hedera-mirror-test/k6/src/rest/test/common.js
> +const statusField = "status";
Missing header

2022-02-22 19:30 UTC, Nana-EC commented on hedera-mirror-test/k6/src/rest/test/constants.js
> +export const transactionListName = "transactions";
nit: order list Names alphabetically for readability

2022-02-22 19:30 UTC, Nana-EC commented on hedera-mirror-test/k6/src/web3/test/common.js
> +  //instead of doing multiple type checks,
nit: spacing on comments here and other places
```suggestion
  // instead of doing multiple type checks,
```

2022-02-22 19:39 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  if(!response.hasOwnProperty(statusField)){
I see. You mean the k6 [Response](https://k6.io/docs/javascript-api/k6-http/response/) object. Wouldn't that always have a status field? At least nothing in the docs indicate it will ever be null or not present.

2022-02-22 23:46 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/web3/test/common.js
> +  //instead of doing multiple type checks,
I was told in another comment to use the auto-format from the idea. Maybe we can talk someday about having an IDE settings file.

2022-02-22 23:49 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/constants.js
> +export const transactionListName = "transactions";
Done.

2022-02-22 23:49 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +const statusField = "status";
Added.

2022-02-22 23:49 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +function validateConfiguration(configuration){
Ok, I believe I have changed most of the functions to arrow functions. Done.

2022-02-23 00:00 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  if(response.accounts.length === 0){
Done.

2022-02-23 13:39 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +  if(!response.hasOwnProperty(statusField)){
Yes, it does say. I am gonna remove the if. Maybe  I was a little bit paranoid there.

2022-02-24 15:01 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/constants.js
> +export const transactionListName = "transactions";
Done.

2022-02-24 15:01 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/common.js
> +const statusField = "status";
Done.

2022-02-24 15:02 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/config/bootstrapEnvParameters.js
> +  if(response.accounts.length === 0){
Done.

2022-03-01 18:16 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/README.md
> +- DEFAULT_TOPIC_TIMESTAMP
We haven't found a way to find this information in the rest API.

2022-03-01 18:27 UTC, steven-sheehy commented on hedera-mirror-test/k6/README.md
> +- DEFAULT_TOPIC_TIMESTAMP
https://mainnet.mirrornode.hedera.com/api/v1/transactions?transactiontype=CONSENSUSSUBMITMESSAGE&limit=1&order=desc

2022-03-01 18:31 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/README.md
> +- LIST_LENGTH_LIMIT
Done.

2022-03-01 18:32 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/README.md
> +LIST_LENGTH_LIMIT=100 \
Done.

2022-03-01 18:41 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/README.md
> +
Done.

2022-03-01 19:11 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/lib/parameters.js
> +  const body = JSON.parse(response.body);
Done.

2022-03-01 19:11 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/accounts.js
> +      nextLink = res.links.next;
@xin-hedera can you answer this one ?

2022-03-01 19:12 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/bootstrapEnvParameters.js
> +  return buildConfigObject(testParameters);
I am sorry Steven, but when we spoke about the requirements before you never all the restrictions.

2022-03-01 19:14 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/bootstrapEnvParameters.js
> +  DEFAULT_CONTRACT_TIMESTAMP: testParameters.DEFAULT_CONTRACT_TIMESTAMP,
Done.

2022-03-01 19:16 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/bootstrapEnvParameters.js
> +  DEFAULT_ACCOUNT_ID: testParameters.account,
I did this to not keep all the bootstrap code coupled with the naming of the parameters used by the tests.

2022-03-01 19:24 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rosetta/test/constants.js
> +const networkIdentifier = {
Done.

2022-03-01 19:28 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rosetta/test/bootstrapEnvParameters.js
> +  __ENV['NETWORK'] = __ENV['NETWORK'] || 'mainnet';
Should I be able to find it via GET `localhost:5551/api/v1/network/list` ?

2022-03-01 19:41 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rosetta/test/bootstrapEnvParameters.js
> +          address: '0.0.10000',
I haven't seen this hard-coded value, I only checked the usages of `__ENV` and fix them. I will see what needs to be done for this one.

2022-03-01 19:54 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rosetta/test/bootstrapEnvParameters.js
> +  __ENV['NETWORK'] = __ENV['NETWORK'] || 'mainnet';
It's a POST. See the postman file or the Rosetta [spec](https://www.rosetta-api.org/docs/NetworkApi.html#networklist) for the format

2022-03-01 20:03 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/bootstrapEnvParameters.js
> +  DEFAULT_ACCOUNT_ID: testParameters.account,
Done.

2022-03-02 01:30 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rosetta/test/bootstrapEnvParameters.js
> +  __ENV['NETWORK'] = __ENV['NETWORK'] || 'mainnet';
Done.

2022-03-02 01:30 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rosetta/test/bootstrapEnvParameters.js
> +          address: '0.0.10000',
Done.

2022-03-02 02:39 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/accounts.js
> +      nextLink = res.links.next;
no strong opinion. This was in one of the original k6 test case versions. We should remove the next url so the query always hit the same accounts.

2022-03-02 03:04 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/accounts.js
> +      nextLink = res.links.next;
I removed it.

2022-03-02 16:27 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/rest/test/bootstrapEnvParameters.js
> +  return buildConfigObject(testParameters);
Done.

2022-03-02 18:38 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/lib/parameters.js
> +    key: ''
This looks to still be there?

2022-03-02 18:39 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/lib/common.js
> +    checks: ['rate>=0.95'], // at least 95% should pass the checks,
Done.

2022-03-02 18:48 UTC, steven-sheehy commented on hedera-mirror-test/k6/report.md
> +| /rosetta/construction/parse | 1 | 100.00 | 2.05/s | 161.84ms | |
Is this file intended to be checked in? Are we missing a .gitignore entry?

2022-03-02 18:56 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/common.js
> +    checks: ['rate>=0.95'], // at least 95% should pass the checks,
The primary goal of the thresholds here is to make k6 include those metrics to the summary output as well as the output `data` our report generator depends on. It's not intended to determine whether a test succeeds or fails.

I'm not against the idea of making it configurable, just want to clarify why it's needed.

2022-03-02 20:01 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/report.md
> +| /rosetta/construction/parse | 1 | 100.00 | 2.05/s | 161.84ms | |
Yes, we were missing an entry. I have deleted the file and ignored it.

2022-03-02 20:04 UTC, matheus-dallrosa commented on hedera-mirror-test/k6/src/lib/parameters.js
> +    key: ''
Removed again.

2022-03-02 20:05 UTC, steven-sheehy approved these changes
LGTM

2022-03-02 20:16 UTC, Nana-EC approved these changes
LGTM

2022-03-02 22:02 UTC, merged