Add data migration guide to database.md
hashgraph/hedera-mirror-node pull request #3175
Opened 2022-01-19 03:04 UTC by xin-hedera

**Description**:

This PR adds a data migration guide to `database.md`. 

**Related issue(s)**:

Fixes #3097

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-01-19 17:29 UTC, Nana-EC requested changes
Looks good, some suggestions

2022-01-19 17:29 UTC, Nana-EC commented on docs/database.md
> +- An ubuntu virtual machine with fast network speed to both PostgreSQL database instances. The instance should also have
```suggestion
- An ubuntu virtual machine with fast network speed connections to both PostgreSQL database instances. The instance should also have
```

2022-01-19 17:29 UTC, Nana-EC commented on docs/database.md
> +  enough free disk space for the database dump
You could add a simple query to get the db size so people could verify
e.g. `select pg_size_pretty(pg_database_size('mirror_node'));`

2022-01-19 17:29 UTC, Nana-EC commented on docs/database.md
> +- The new PostgreSQL database instance at the same schema version
Can provide a query to verify this e.g. `select version from flyway_schema_history order by installed_rank desc limit 1 ;`

2022-01-19 17:55 UTC, steven-sheehy requested changes

2022-01-19 17:55 UTC, steven-sheehy commented on docs/database.md
> +## Data Migration Between PostgreSQL Major Releases
Can simplify since we're within the `Database` docs context.

```suggestion
## Upgrading
```

2022-01-19 17:55 UTC, steven-sheehy commented on docs/database.md
> +- The new PostgreSQL database instance at the same schema version
Instead of querying, should document the steps to run the same importer against the new database to create the schema but with downloading disabled. Or see my comment about dumping schema.

2022-01-19 17:55 UTC, steven-sheehy commented on docs/database.md
> +- No data in the new PostgreSQL database instance, if not sure, run the
Why can't we also dump the database schema when we pg_dump? These two separate steps effectively do that anyway.

2022-01-19 17:55 UTC, steven-sheehy commented on docs/database.md
> +The following configuration needs to be applied to the new PostgreSQL database instance to improve the write speed.
Clarify if this is a permanent change or temporary for restoration.

2022-01-19 17:55 UTC, steven-sheehy commented on docs/database.md
> +### Dump Data
```suggestion
### Backup
```

2022-01-19 17:55 UTC, steven-sheehy commented on docs/database.md
> +  -T 'flyway*' \
I think we should probably compress with `--compress=1` since it makes a huge difference in the amount of disk used.

2022-01-19 18:29 UTC, xin-hedera commented on docs/database.md
> +  enough free disk space for the database dump
pg_dump directory mode will compress the data so there isn't a way to estimate the required free disk size from the db instance disk usage. just for the record, testnet's 8TB data ended up to be a ~350 GB dump.

2022-01-19 18:30 UTC, xin-hedera commented on docs/database.md
> +- The new PostgreSQL database instance at the same schema version
sure

2022-01-19 18:36 UTC, steven-sheehy commented on docs/database.md
> +  -T 'flyway*' \
I wasn't aware directory mode compressed. Should be fine then.

2022-01-19 19:54 UTC, Nana-EC commented on docs/database.md
> +  enough free disk space for the database dump
Fair point. There's a huge disparity between the actual and compressed.

2022-01-19 22:25 UTC, xin-hedera commented on docs/database.md
> +- An ubuntu virtual machine with fast network speed to both PostgreSQL database instances. The instance should also have
done

2022-01-19 22:31 UTC, xin-hedera commented on docs/database.md
> +- No data in the new PostgreSQL database instance, if not sure, run the
that'll require the new db instance having the `mirror_node` database created and no migration is run. but then

- if the dump has the `flyway_schema_history` table and the new instance doesn't have the `mirror_api` user, after restoring the data, ops has to create the user
- if the dump doesn't have the `flyway_schema_history` table, once importer runs, it'll rerun all migrations, though it shouldn't fail, some time consuming migrations may take a very long time to finish

2022-01-19 22:58 UTC, ijungmann commented on docs/database.md
> +  -T 'flyway*' \
If we're going to dump the schema as well to avoid having to run the importer for the flyway migrations, we'd want to not skip the flyway tables now, right?

2022-01-19 23:06 UTC, ijungmann commented on docs/database.md
> +Note once the data is restored, revert the values back for normal operation.
nit
```suggestion
Note: once the data is restored, revert the values back for normal operation.
```

2022-01-19 23:07 UTC, ijungmann commented on docs/database.md
> +Note once the data is restored, revert the values back for normal operation.
I would also put this above the config values as part of the previous paragraph.

2022-01-19 23:16 UTC, xin-hedera commented on docs/database.md
> +Note once the data is restored, revert the values back for normal operation.
both work for me. the reason they are split is the initialization brings the new database instance to the state ready for data restoration; the config params are needed to speed up the write, also the configs should be reverted once data is restored.

2022-01-19 23:17 UTC, steven-sheehy commented on docs/database.md
> +- No data in the new PostgreSQL database instance, if not sure, run the
The dump should have the `flyway_schema_history` to avoid re-running migrations. We should also add to the prerequisites that the new PostgreSQL already has the `mirror_node` database and the database users created including the `mirror_api` user. Preferably if we can point them to a script to do so.

2022-01-20 00:03 UTC, steven-sheehy approved these changes
LGTM

2022-01-20 00:34 UTC, ijungmann approved these changes

2022-01-20 15:39 UTC, Nana-EC approved these changes
LGTM

2022-01-20 15:40 UTC, merged