Return partial response for contract calls without a result
hashgraph/hedera-mirror-node pull request #3182
Opened 2022-01-20 18:11 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
We currently return not found when a contract call or create returns certain type of errors. 

- Return a partial result with a 206 HTTP response code when `contract_result` model is missing
- Update contract detailed view model to set default `null` or `[]` values in partial case Populate all fields that have data:
- Update spec files
- Add spec test files for missing coverage
- Update OpenAPI spec with 206
- Pick up entityId in transaction service calls as fall back for contractid value

**Related issue(s)**:

Fixes #3158 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-01-21 16:58 UTC, xin-hedera requested changes

2022-01-21 16:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/transactionService.test.js
> +
these two test cases are already in the `describe` block on line 66. so revert all changes to this file?

2022-01-21 16:58 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      const contractId = EntityId.parse(transaction.entityId, true);
duplicated on line 57
the lines setting `this.contract_id`, `this.from`, `this.to`, and `timestamp` are also duplicated

2022-01-21 16:58 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        contract_id: contractId === null ? null : contractId.toString(),
```suggestion
        contract_id: contractId.toString(),
```

2022-01-21 16:58 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        to: contractId === null ? null : contractId.toSolidityAddress(),
```suggestion
        to: contractId.toSolidityAddress(),
```

2022-01-21 16:58 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    transaction.entityId = contractId;
what if someone sends a query `/api/v1/contracts/1000/results/123456789` and the consensus timestamp `123456789` corresponds to a failed contract create transaction (since it's failed, obviously it's not for contract `1000`)?

2022-01-21 16:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-result-not-found.spec.json
> +    "status": "0x01",
result & status shouldn't be success

2022-01-21 17:26 UTC, steven-sheehy requested changes

2022-01-21 17:26 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +    // set contractId as it would be missing in empty contratResult case
```suggestion
    // set contractId as it would be missing in empty contractResult case
```

2022-01-21 17:26 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-result-not-found.spec.json
> +    "amount": null,
We should be populating `amount`, `function_parameters`, `gas_limit` and anything else that comes from the transaction body. We need to update importer to create a `contract_result` regardless of if there's a `ContractFunctionResult` or not. This will provide a more complete picture while also reducing the need to conditionally get payer, timestamp, contract_id from transaction.

2022-01-21 17:26 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +  constructor(contractResult, transaction) {
This is confusing. The `contractResultViewModel` should only be used by `/api/v1/contract/{id}/results` and will never join with the `transaction` table. Hence this class should not have any knowledge of the `transaction` table.

With my suggestion to update importer to always create a result this need for `transaction` should go away and this class should go back to pretty much how it was.

2022-01-21 17:26 UTC, steven-sheehy commented on hedera-mirror-rest/service/transactionService.js
> +    ${Transaction.CONSENSUS_TIMESTAMP}, ${Transaction.ENTITY_ID}, ${Transaction.PAYER_ACCOUNT_ID}, ${Transaction.RESULT}, ${Transaction.TRANSACTION_HASH}
Can undo with my other suggestion.

2022-01-21 17:26 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  if (contractResult === null) {
We'll have to detect partial results based upon some value within the contract result with my other suggestion.

2022-01-21 18:25 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/transactionService.test.js
> +
Missed this, will revert

2022-01-21 18:31 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      const contractId = EntityId.parse(transaction.entityId, true);
`this.contract_id` is a duplicate but the rest aren't as simple.
Doing some refactoring that will probably simplify this also

2022-01-21 18:41 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +    transaction.entityId = contractId;
Fair point, can include success logic but will think a bit more on this to clarify other edge cases since we always want to return a contractId when its valid

2022-01-21 19:49 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-result-not-found.spec.json
> +    "amount": null,
Agreed, will drop the `transactionRecord.hasContractCallResult()` in `ContractCallTransactionHandler` so that there's always a partial `ContractResult` created with all the non call result related values.

2022-01-22 02:16 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-result-not-found.spec.json
> +    "amount": null,
Need to handle it similarly for `ContractCreateTransactionHandler`

2022-01-24 18:50 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/transactionService.test.js
> +
Reverted

2022-01-24 18:51 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      const contractId = EntityId.parse(transaction.entityId, true);
Should be resolved. Default is set and only updated with valid result

2022-01-24 18:51 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        contract_id: contractId === null ? null : contractId.toString(),
Fixed

2022-01-24 18:52 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +        to: contractId === null ? null : contractId.toSolidityAddress(),
Fixed

2022-01-24 18:52 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +    transaction.entityId = contractId;
Removed. With Partial case contractId will always be present

2022-01-24 18:55 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-result-not-found.spec.json
> +    "status": "0x01",
Fixed

2022-01-24 18:55 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +      Object.assign(this, {
Removed

2022-01-24 18:56 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +    // set contractId as it would be missing in empty contratResult case
Reverted

2022-01-24 19:08 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-result-not-found.spec.json
> +    "amount": null,
Will update `ContractCreateTransactionHandler` also

2022-01-24 19:09 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +  constructor(contractResult, transaction) {
Reverted and updated with new logic based on suggestion

2022-01-24 19:13 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  if (contractResult === null) {
Updated to be based on `contractResult.callResult`, since this is only set when importer encounters a valid `ContractFunctionResult` i.e. `transactionRecord.hasContractCreateResult()` or `transactionRecord.hasContractCallResult()` is true

2022-01-24 20:11 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionService.js
> +    ${Transaction.CONSENSUS_TIMESTAMP}, ${Transaction.ENTITY_ID}, ${Transaction.PAYER_ACCOUNT_ID}, ${Transaction.RESULT}, ${Transaction.TRANSACTION_HASH}
Reverted

2022-01-25 15:51 UTC, xin-hedera requested changes

2022-01-25 15:53 UTC, steven-sheehy requested changes

2022-01-25 15:53 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (!_.isNil(contractResult.callResult)) {
This check isn't necessary and duplicates assignments. Since `utils.toHexString()` and `_.toArray()` properly handle `null` you can omit it except for `gas_used` where you'll have to check if it's null before using `Number`.

2022-01-25 15:53 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
>      const contractId = EntityId.parse(contractResult.contractId, true);
nit: Move helper variable before assignments.

2022-01-25 15:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/ContractResultResponse'
I think we need to update more fields in the schema response to be nullable like `gas_used` and `function_parameters`. Double check others.

2022-01-25 15:53 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-13-timestamp-partial-result-match.spec.json
> +    "status": "0x1",
Shouldn't be success if partial match

2022-01-26 00:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCallTransactionHandler.java
> +                    transactionRecord.getContractCallResult() : ContractFunctionResult.getDefaultInstance();
Updated. Went with inbuilt `getContractCallResult()` which does the conditional logic

2022-01-26 00:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance()) {
After changing higher calls I left this this as is

2022-01-26 00:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                    transactionRecord.getContractCreateResult() : ContractFunctionResult.getDefaultInstance());
Updated. Went with inbuilt `getContractCreateResult()` which does the conditional logic

2022-01-26 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            contractResult.setContractId(transaction.getEntityId());
Updated

2022-01-26 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                    transactionRecord.getContractCreateResult() : ContractFunctionResult.getDefaultInstance());
Reverted

2022-01-26 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCallTransactionHandler.java
> +                    transactionRecord.getContractCallResult() : ContractFunctionResult.getDefaultInstance();
Reverted

2022-01-26 00:23 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    if (!_.isNil(contractResult.callResult)) {
Removed and did inline checks for those needed

2022-01-26 00:23 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
>      const contractId = EntityId.parse(contractResult.contractId, true);
Moved up

2022-01-26 00:23 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/ContractResultResponse'
Updated - should be `amount, bloom, call_result, contract_id,  created_contract_ids, error_message, function_parameters, gas_used`

2022-01-26 00:23 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-13-timestamp-partial-result-match.spec.json
> +    "status": "0x1",
Updated

2022-01-26 00:25 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
>                  () -> assertFailedContractCreate(transactionBody, record)
Added asserts to check partial case

2022-01-26 01:24 UTC, xin-hedera approved these changes
LGTM

2022-01-26 01:37 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-01-26 16:48 UTC, steven-sheehy approved these changes

2022-01-26 16:54 UTC, merged