Add contract state change support to common and importer modules
hashgraph/hedera-mirror-node pull request #3189
Opened 2022-01-21 18:20 UTC by Nana-EC

**Description**:
[HIP-260](https://hips.hedera.com/HIP/hip-260.html) Smart Contract Traceability adds new information to the transaction record to track contract state changes.

- Add v1 db migration to create `contract_state_change` table
- Update V2.0.x migrations files with `contract_state_change` table logic
- Add `ContractStateChange` domain to common module
- Update `EntityListener` interface and implementations with `onContractStateChange()` logic
- Update `AbstractContractCallTransactionHandler` with `ContractStateChange` population logic

**Related issue(s)**:

Partially addresses #3160 

**Notes for reviewer**:
Yet to 
- [ ] Update v2 migration scripts with new table
- [ ] Rebase with main for newly pushed changes

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-25 16:25 UTC, steven-sheehy requested changes

2022-01-25 16:25 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> +    @NoArgsConstructor
These aren't needed and can be removed.
```suggestion
```

2022-01-25 16:25 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> +    private EntityId payerAccountId;
Need to update design with new field.

2022-01-25 16:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                    .getStateChanges(index);
```suggestion
            var contractStateChangeInfo = functionResult.getStateChanges(index);
```

2022-01-25 16:25 UTC, steven-sheehy commented on pom.xml
> +        <hedera-sdk.version>2.2.0-beta.2</hedera-sdk.version>
Merge residue
```suggestion
```

2022-01-25 16:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                if (storageChange.isInitialized()) {
I don't think this does what you want it to do. Regardless, it's more complex than it needs to be. The reason for using a wrapper object for `valueWritten` was to allow for a simple check.

```suggestion
                if (storageChange.hasValueWritten()) {
```

2022-01-25 16:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        assertContractResult(consensusTimestamp, result, result.getLogInfoList(), contractResult,
I'm missing where we actually populate any `ContractStateChange` rows in the db.

2022-01-25 17:31 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> +    @NoArgsConstructor
Use it on the test side similar to `ContractLog.Id(...)`

2022-01-25 17:37 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> +    @NoArgsConstructor
Nah, with `@IdClass` you don't need to construct an ID in tests. You just set fields directly on `ContractStateChange`.

2022-01-25 19:37 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> + * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
Updated

2022-01-25 19:53 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> +    @NoArgsConstructor
Updated

2022-01-25 19:54 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractStateChange.java
> +    private EntityId payerAccountId;
Updated design doc

2022-01-25 19:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                    .getStateChanges(index);
Updated

2022-01-25 19:54 UTC, Nana-EC commented on pom.xml
> +        <hedera-sdk.version>2.2.0-beta.2</hedera-sdk.version>
Removed

2022-01-25 19:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                if (storageChange.isInitialized()) {
Simplified

2022-01-25 19:55 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        assertContractResult(consensusTimestamp, result, result.getLogInfoList(), contractResult,
Updated file with population logic

2022-01-25 20:39 UTC, xin-hedera requested changes

2022-01-25 20:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                            .setValueWritten(DomainUtils.toBytes(storageChange.getValueWritten().getValue()));
shouldn't we set the value to new byte[1]{0} `if a value of zero is written`? Since the value will be absent in the protobuf, `DomainUtils.toBytes` actually returns `new byte[0]`.

2022-01-25 20:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                        .build().getId()))
nit, use ContractStateChange.Id constructor to create the id instead of making a ContractStageChange object just to get its id.

2022-01-25 20:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    private void buildContractFunctionResult(ContractFunctionResult.Builder builder) throws InvalidProtocolBufferException {
SneakyThrows?

2022-01-25 20:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                        .setValueWritten(BytesValue.of(ByteString.copyFromUtf8("0")))
the proto spec says if the value written is `0`, the inner value will be absent

2022-01-25 21:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                            .setValueWritten(DomainUtils.toBytes(storageChange.getValueWritten().getValue()));
I don't think we need to be in the business of interpreting values from the nodes. Empty byte array is what the [tuweni library](https://github.com/apache/incubator-tuweni/blob/e8fa2ebcaffed7c71f4f7b851e218dc842acf062/bytes/src/main/java/org/apache/tuweni/bytes/Bytes.java#L1439) they use outputs. If empty byte array is what is in the proto, that is what we put in the db.

On display, we need to convert all formats to a zero padded hex string regardless. So if we see `byte[]{}`, `byte[]{0}`, or `byte[]{0, 0, 0, ..., 0}` the output should be the same.

2022-01-25 21:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                            .setValueWritten(DomainUtils.toBytes(storageChange.getValueWritten().getValue()));
makes sense to me. so in rest we should interpret it and pad it to the all-zero hex string.

2022-01-25 21:24 UTC, steven-sheehy approved these changes

2022-01-25 21:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        builder.addStateChanges(com.hederahashgraph.api.proto.java.ContractStateChange.newBuilder()
nit: Would suggest adding some state changes to `RecordItemBuilder.contractFunctionResult()` in addition or in lieu of this.

2022-01-25 21:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                        .build().getId()))
Or you can use `assertThat(contractStateChangeRepository.findAll()).filteredOn(...).hasSize(1).first()` like in `assertContractCallResult()`

2022-01-26 02:04 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    private void buildContractFunctionResult(ContractFunctionResult.Builder builder) throws InvalidProtocolBufferException {
Added

2022-01-26 02:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
> +                            .setValueWritten(DomainUtils.toBytes(storageChange.getValueWritten().getValue()));
Seems like as is is fine. Setting to above noted actually results in a `InvalidProtocolBufferException`

2022-01-26 02:09 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                        .build().getId()))
Went with `ContractStateChange.Id` for least churn

2022-01-26 02:09 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +        builder.addStateChanges(com.hederahashgraph.api.proto.java.ContractStateChange.newBuilder()
Added in addition

2022-01-26 03:51 UTC, steven-sheehy approved these changes

2022-01-26 15:48 UTC, xin-hedera approved these changes
LGTM

2022-01-26 15:49 UTC, merged