Add contract state change support to contract REST API endpoints
hashgraph/hedera-mirror-node pull request #3219
Opened 2022-01-26 20:32 UTC by Nana-EC

**Description**:
[HIP-260](https://hips.hedera.com/HIP/hip-260.html) Smart Contract Traceability adds new information to the transaction record to track contract state changes.
Importer logic was added to store state changes, REST API must be updated to expose these state changes in the contract result details

- Add a `ContractStateChange` model. Update index.js for easy import access
- Add a `COntractResultStateChangeViewModel.js` view model to display changes. Update index.js for easy import access
- Add `state_changes` to `contractResultDetailsViewModel.js`
- Update `contractController.js` to handle `contract_state_change` rows returned from service
- Update `contractService.js` with logic to pull `contract_state_change` rows 
- Update `integrationDomainOps.js` with db `contract_state_change` population logic
- Update test spec files contract results response with `state_change`

**Related issue(s)**:

Fixes #3160 

**Notes for reviewer**:
Yet to
- Update OpenAPI spec

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-01-27 03:58 UTC, steven-sheehy requested changes

2022-01-27 03:58 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +    const orderClause = `order by ${ContractStateChange.CONSENSUS_TIMESTAMP}, ${ContractStateChange.CONTRACT_ID}`;
We also need to sort by slot to provide deterministic output.

2022-01-27 15:30 UTC, xin-hedera requested changes

2022-01-27 15:30 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    .join(',');
not needed with the helper function

2022-01-27 15:30 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultStateChangeViewModel.js
> +      value_read: utils.toHexString(contractStateChange.valueRead, true),
just want to add that `toHexString` supports padding

2022-01-27 17:29 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-16-timestamp-no-state-change.spec.json
> +        "value_written": null
Had a spec file for this and deleted. Will revert delete

2022-01-27 18:06 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-16-timestamp-no-state-change.spec.json
> +        "value_written": null
Spec files are heavyweight and have a cost to running them. I only need one value in an existing test to be in this format.

2022-01-27 22:20 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultStateChangeViewModel.js
> +    Object.assign(this, {
Removed

2022-01-27 22:21 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: true
Removed

2022-01-27 22:21 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded Solidity address of the contract
Updated

2022-01-27 22:21 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Added here and for `slot` and `value_written` also

2022-01-27 22:23 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultStateChangeViewModel.js
> +      value_read: utils.toHexString(contractStateChange.valueRead, true),
Used `toHexString()` padding support

2022-01-27 22:24 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    const orderClause = `order by ${ContractStateChange.CONSENSUS_TIMESTAMP}, ${ContractStateChange.CONTRACT_ID}`;
Added `slot` ordering

2022-01-27 22:25 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  );
Used `insertDomainObject()`

2022-01-27 22:25 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    .join(',');
Removed

2022-01-27 22:54 UTC, xin-hedera requested changes
looks good, just some minor issues.

2022-01-27 22:54 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-16-timestamp-no-state-change.spec.json
> +  "description": "Contract results api call using contract id and timestamp where contract state was read but not written or a zero value was written",
both state changes are read-only, so the description is inaccurate? Or should just combine the other spec?

2022-01-27 22:54 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded value written to the slot.
clarify null means no value written?

2022-01-28 17:16 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          pattern: ^0x[0-9A-Fa-f]{40}$
ref SolidityAddress

2022-01-28 17:16 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-16-timestamp-no-state-change.spec.json
> +        "value_written": null
There's still not one with empty byte array. There's now one with `[0]` technically can't come across record files since they strip leading zeros. Again, no need for whole separate test case when single value in this spec will suffice.

2022-01-28 18:14 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-16-timestamp-no-state-change.spec.json
> +        "value_written": null
Updated

2022-01-28 18:14 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-16-timestamp-no-state-change.spec.json
> +  "description": "Contract results api call using contract id and timestamp where contract state was read but not written or a zero value was written",
Updated to contain a zero write with empty array

2022-01-28 18:14 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The hex encoded value written to the slot.
Updated

2022-01-28 18:14 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          pattern: ^0x[0-9A-Fa-f]{40}$
Updated

2022-01-28 18:16 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-01-28 18:27 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-01-31 18:55 UTC, steven-sheehy approved these changes

2022-01-31 19:06 UTC, merged