Increase default gas limit used by acceptance tests
hashgraph/hedera-mirror-node pull request #3227
Opened 2022-01-27 22:32 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
In recent service version releases the gas cost has increased.
In cases where a system account is used this gas limit has exceeded the default gas limit used by acceptance tests

- Increase default gas limit to support gas cost for system accounts with far off expiration

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-27 23:47 UTC, steven-sheehy requested changes

2022-01-27 23:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    private final static long maxFunctionGas = 3_000_000;
Can we make this a property in case we need to have ops adjust in the future?

2022-01-28 19:07 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    private final static long maxFunctionGas = 3_000_000;
Agreed, will add

2022-01-28 20:16 UTC, steven-sheehy approved these changes

2022-01-28 21:14 UTC, xin-hedera submitted a review, later dismissed

2022-01-31 20:11 UTC, steven-sheehy approved these changes

2022-01-31 20:12 UTC, merged