Parser support for HIP-336 allowance APIs
hashgraph/hedera-mirror-node pull request #3252
Opened 2022-01-31 22:59 UTC by steven-sheehy

**Description**:

**Related issue(s)**:

Fixes #3163

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-02-01 22:26 UTC, Nana-EC requested changes
1st pass, some questions and suggestions on potential edge case with accountIds

2022-02-01 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        previous.setTimestampUpper(current.getTimestampLower());
SHouldn't the merge function update amount and other properties than just the time range? e.g. `amount`, `serial_numbers` or `allowedForAll`

2022-02-01 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/csvBackupTables.sql
> +\copy crypto_allowance to crypto_allowance.csv delimiter ',' csv;
Add the history tables

2022-02-01 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/csvRestoreTables.sql
> +\copy crypto_allowance (amount, payer_account_id, spender, timestamp_range) from crypto_allowance.csv csv;
Add history tables

2022-02-01 23:27 UTC, steven-sheehy commented on docs/design/allowances.md
> +  spender          bigint    not null,
The field in the proto is `spender`, so we should stay consistent with that.

2022-02-01 23:28 UTC, steven-sheehy commented on docs/design/allowances.md
> +  primary key (payer_account_id, spender)
There is no `owner` field in the proto as it implicitly uses the payer account. We discussed possibly having a separate `owner` field in the future who wouldn't necessarily pay for the transaction. If we got that route in a future release we can add that field then.

2022-02-01 23:29 UTC, steven-sheehy commented on docs/design/allowances.md
> +  payer_account_id bigint    not null,
Right now it is the same.

2022-02-01 23:31 UTC, steven-sheehy commented on docs/design/allowances.md
> +Update all APIs that show transfers to return `is_approval` in its response. Including `/api/v1/accounts/:id` and all
I don't follow the question. We should add `is_approval` to anything that shows transfers, which includes account id and all transactions APIs. This document doesn't discuss priority of changes and we can choose to break them into separate tasks as necessary.

2022-02-03 18:53 UTC, Nana-EC commented on docs/design/allowances.md
> +Update all APIs that show transfers to return `is_approval` in its response. Including `/api/v1/accounts/:id` and all
Right, was suggesting we consider doing this for the single transaction api `api/v1/transactions/<transactionId>` response, and leave it out of the `/api/v1/accounts/:id` & `api/v1/transactions/` responses for now.

2022-02-04 06:25 UTC, steven-sheehy commented on docs/design/allowances.md
> +account. An allowance grants a spender the right to transfer a predetermined amount of the payer's hbars or tokens to
Updated

2022-02-04 06:25 UTC, steven-sheehy commented on docs/design/allowances.md
> +  primary key (payer_account_id, spender)
Of course as soon as I said that they adjusted the design. Added new `owner` field to match the proto.

2022-02-04 06:26 UTC, steven-sheehy commented on docs/design/allowances.md
> +  payer_account_id bigint    not null,
Added owner

2022-02-04 06:26 UTC, steven-sheehy commented on docs/design/allowances.md
> +      "payer_account_id": "0.0.1000",
Added both

2022-02-04 06:28 UTC, steven-sheehy commented on docs/design/allowances.md
> +Update all APIs that show transfers to return `is_approval` in its response. Including `/api/v1/accounts/:id` and all
We should have a common transfer view model and show the same information on all endpoints that use it. It won't improve performance to not show one extra field and makes our API inconsistent.

2022-02-04 06:28 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/History.java
> + * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
Fixed

2022-02-04 06:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        previous.setTimestampUpper(current.getTimestampLower());
`merge` functions are only necessary to merge in non-null values from previous entries in the state when the current entry has null values. In this case, the current entry will never have null for any fields since we always populate every field.

2022-02-04 06:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/csvBackupTables.sql
> +\copy crypto_allowance to crypto_allowance.csv delimiter ',' csv;
Added

2022-02-04 06:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/csvRestoreTables.sql
> +\copy crypto_allowance (amount, payer_account_id, spender, timestamp_range) from crypto_allowance.csv csv;
Added

2022-02-07 23:08 UTC, Nana-EC submitted a review, later dismissed
Looks good.

2022-02-08 07:54 UTC, Nana-EC approved these changes

2022-02-08 15:31 UTC, merged