Add auto restore functionality to Rosetta unified image
hashgraph/hedera-mirror-node pull request #3253
Opened 2022-02-02 06:19 UTC by steven-sheehy

**Description**:
* Add auto restore functionality to Rosetta unified image
* Add documentation for running unified image
* Change Rosetta default start date to epoch
* Fix documentation bug with wrong units for `checkpoint_timeout`

**Related issue(s)**:

**Notes for reviewer**:
Need to test against a large db dump

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-02-02 18:45 UTC, Nana-EC requested changes
Looking good, minor clarification and suggestion

2022-02-02 18:45 UTC, Nana-EC commented on docs/rosetta/README.md
> +-p 5432:5432 -p 5700:5700 hedera-mirror-rosetta:0.45.0
Did you wanna use the more recent version
```suggestion
-p 5432:5432 -p 5700:5700 hedera-mirror-rosetta:0.49.1
```

2022-02-02 18:45 UTC, Nana-EC commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +  cd /app
nit: Add debug echo to say successfully cleared temp files

2022-02-02 18:57 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +  cd /app
Done

2022-02-02 18:57 UTC, steven-sheehy commented on docs/rosetta/README.md
> +-p 5432:5432 -p 5700:5700 hedera-mirror-rosetta:0.45.0
Fixed

2022-02-02 19:10 UTC, Nana-EC approved these changes
LGTM

2022-02-02 20:02 UTC, xin-hedera requested changes

2022-02-02 20:02 UTC, xin-hedera commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +  restore
only restore in online mode. offline mode just runs the rosetta server, without importer / db.

2022-02-02 20:06 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +  restore
Moved

2022-02-02 20:07 UTC, xin-hedera approved these changes
LGTM

2022-02-02 20:16 UTC, Nana-EC submitted a review, later dismissed

2022-02-02 21:05 UTC, xin-hedera approved these changes
LGTM

2022-02-03 18:45 UTC, Nana-EC submitted a review, later dismissed

2022-02-03 22:15 UTC, Nana-EC approved these changes

2022-02-03 22:20 UTC, xin-hedera approved these changes

2022-02-03 22:35 UTC, merged