Improve perf of Rosetta get genesis balance script
hashgraph/hedera-mirror-node pull request #3256
Opened 2022-02-04 18:12 UTC by Nana-EC

**Description**:
The `hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh` script performs heavy lifting logic to get a genesis script. This sometimes runs slow in large environments and needs streamlining.

- Update `genesis_timestamp_query` to 
  - use order and limit instead of `min()`
  - pull the 2 earliest balance file timestamps to allow for timestamp boundaries
- Add `recent_crypto_accounts` CTE to pull the recent account used in a crypto transfer since balance file
- Update `genesis_balance` to use result of `recent_crypto_accounts`

**Related issue(s)**:

Fixes #

**Notes for reviewer**:
Before: 121 s
After: 24 s

Table size 

table_name | row_estimate | index | toast | table | total
-- | -- | -- | -- | -- | --
crypto_transfer | 2.3496112e+07 | 1767 MB | NULL | 2510 MB | 4277 MB
account_balance | 2.624885e+07 | 1926 MB | 8192 bytes | 1412 MB | 3338 MB
transaction | 6.438296e+06 | 691 MB | 8192 bytes | 1571 MB | 2262 MB
token_balance | 8.535088e+06 | 356 MB | NULL | 529 MB | 886 MB
token_transfer | 1.620688e+06 | 199 MB | NULL | 180 MB | 379 MB
account_balance_file | 362 | 64 kB | 8192 bytes | 112 kB | 184 kB
nft | 9 | 32 kB | 8192 bytes | 8192 bytes | 48 kB
token | 0 | 16 kB | 8192 bytes | 8192 bytes | 32 kB

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-02-04 18:57 UTC, steven-sheehy commented
Has this been tested against a full mainnet dump (or on failover)? Need to know the full runtime and optimize it if it's still too slow.

2022-02-09 20:13 UTC, steven-sheehy commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +if [[ "$account_limit" == "0" ]]; then
Shouldn't this be in an `if`/`else` with the above creation of `applicable_accounts_query` so only one of those occur?

2022-02-10 16:55 UTC, xin-hedera requested changes

2022-02-10 16:55 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +starting_timestamp=${3:-0}
don't think we should have `starting_timestamp`. The first account balance file in db determines the genesis timestamp. If we set `starting_timestamp` to a value, rosetta-cli will report error almost immediately when blocks are synced due to account balance mismatch

2022-02-10 16:55 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +limit 1
revert this

2022-02-10 16:55 UTC, xin-hedera commented on docs/rosetta/README.md
> +with the associated
the script doesn't need the `validation.json` file

2022-02-17 20:00 UTC, Nana-EC commented on docs/rosetta/README.md
> +#### balance validation json
Updated

2022-02-17 20:00 UTC, Nana-EC commented on docs/rosetta/README.md
> +- `network` - The Hedera network to validate against. Option include `demo, testnet` with default of `demo`
Updated

2022-02-17 20:00 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +starting_timestamp=${3:-0}
Removed

2022-02-17 20:00 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +limit 1
Reverted optimization due to undesired side effects

2022-02-17 20:00 UTC, Nana-EC commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> +      group by account_id, balance
Removed

2022-02-17 20:00 UTC, Nana-EC commented on docs/rosetta/README.md
> +with the associated
Reworded

2022-02-17 22:15 UTC, steven-sheehy approved these changes

2022-02-17 22:48 UTC, xin-hedera approved these changes
LGTM

2022-02-17 23:54 UTC, merged