Add ContractResults support for all transaction types
hashgraph/hedera-mirror-node pull request #3285
Opened 2022-02-10 00:13 UTC by Nana-EC

**Description**:
Previously the mirror node only parsed `ContractFunctionResult` objects for the `ContractCreate` and `ContractCall` transactions.
With the support for precompile contracts non Contract transaction types will now be represented as child records with `ContractFunctionResult` objects.

- Add `ContractResultsService` with method signatures for `processContractResult(...)`
- Add `ContractResultsServiceImpl` with implementation logic taken from `EntityRecordItemListener`
- Update `TransactionHandler` with `ContractResult updateContractResult(...)` and implement in `ContractCall` and `ContractCreate` transaction handlers
- Update transaction handler test classes
- Move contractResultLogic domain related logic from `EntityRecordItemListenerContract` and `AbstractContractCallTransactionHandler` to `ContractResultsService`
- Remove `AbstractContractCallTransactionHandler`
- Update `EntityRecordItemListenerContractTest` with coverage for precompiled tests 
- Add `ContractServiceImplTests` and `ContractServiceImplIntegrationTests` to cover contract result scenarios

**Related issue(s)**:

Fixes #3243 

**Notes for reviewer**:

COntext
- `FunctionParameters`, `Amount` and `GasLimit`  are missing from `ContractFunctionResult` proto and therefore result in incomplete `ContractResult` for precompile case. This will be addressed once traceability is addressed

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-02-11 17:15 UTC, steven-sheehy requested changes

2022-02-11 17:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private long getPrecompileAmount(TransferList transferList, ContractID contractID) {
For what precompiles is this logic necessary? For all the token precompiles it shouldn't have any transfers referencing a contract ID. For crypto transfer I think we relaxed the constraint that the receiving account couldn't be a contract ID, right? So does this just apply to crypto transfers?

2022-02-11 17:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAssociateTransactionHandler.java
> +                contractResult.setPayerAccountId(transaction.getPayerAccountId());
Missing function parameters population for this and others.

2022-02-11 17:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                        .toBytes("mintToken")
Use static constant

2022-02-11 17:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                contractResult.setPayerAccountId(transaction.getPayerAccountId());
This logic seems common to every precompile transaction and should be moved to the `ContractResultService`. The rest of the logic is really just extracting the function parameters. Perhaps instead of `ContractResult getContractResult()` we can have `byte[] resolveFunctionParameters(RecordItem)` and move all other logic to `EntityRecordItemListener` or `ContractResultService`.

2022-02-11 17:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                contractResult.setAmount(0L); // precompile Mint amount is always 0
I'm not sure this is correct. You could argue for fungible it can be the amount minted. You could also argue that we should just not populate amount for precompiles since it doesn't apply and the necessary information is already in the function parameters.

2022-02-11 17:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private long getPrecompileAmount(TransferList transferList, ContractID contractID) {
This would be for any precompile function that is payable.
After confirming this can be removed since I was being overly defensive.
For now no precompile is payable but I didn't want the mirror node hitting a bug should that change on future precompiles.
YAGNI I guess

2022-02-11 17:27 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                contractResult.setAmount(0L); // precompile Mint amount is always 0
`Amount` is not the number of fungible or non-fungible tokens transferred.
It the number of hbar paid to the contract call.
For the precompile `tokenMint` it is 0 since it's not a payable function.
So I think the comment is correct and the `getPrecompileAmount()` can be removed

2022-02-11 17:30 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
`functionResult.contractID` will always be the precompile ContractID

2022-02-14 19:23 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionParameters.java
> +public final class ContractFunctionParameters {
So found 2 solutions. 
Went with web3j initially but based on offline reservations I shared we'll hold off on encoding functionParameters.

If you're curious this is what CryptoTransfer inference and encoding for the 5 applicable mappings would have looked like

```java
    private static final String CRYPTO_TRANSFER_FUNCTION_NAME = "cryptoTransfer";
    private static final String TRANSFER_TOKEN_FUNCTION_NAME = "transferToken";
    private static final String TRANSFER_TOKENS_FUNCTION_NAME = "transferTokens";
    private static final String TRANSFER_NFT_FUNCTION_NAME = "transferNFT";
    private static final String TRANSFER_NFTS_FUNCTION_NAME = "transferNFTs";
    
    ...
    
    ContractResult contractResult = new ContractResult();
    
    ...
    
                var transactionBody = recordItem.getTransactionBody().getCryptoTransfer();

                // Multiple precompile methods map to a CryptoTransfer transaction.
                Function function = null;

                List<TokenTransferList> tokenTransferList = transactionBody.getTokenTransfersList();
                if (tokenTransferList.size() > 1) {
                    // cryptoTransfer(IHederaTokenService.TokenTransferList[] memory tokenTransfers)
                    function = getCryptoTransferFunction(tokenTransferList);
                } else {
                    TokenTransferList tokenTransferListItem = tokenTransferList.get(0);
                    EntityId tokenEntityId = EntityId.of(tokenTransferListItem.getToken());
                    if (tokenTransferListItem.getTransfersCount() == 1) {
                        // transferToken(address token, address sender, address receiver, int64 amount)
                        AccountAmount accountAmount = tokenTransferListItem.getTransfers(0);
                        function = new Function(
                                TRANSFER_TOKEN_FUNCTION_NAME,
                                Arrays.asList(
                                        getAddress(tokenEntityId),
                                        getAddress(recordItem.getPayerAccountId()),
                                        getAddress(EntityId.of(accountAmount.getAccountID())),
                                        new Int64(accountAmount.getAmount())),
                                Collections.emptyList()
                        );
                    } else if (tokenTransferListItem.getTransfersCount() > 1) {
                        // transferTokens(address token, address[] memory accountIds, int64[] memory amounts)
                        List<Address> addresses = new ArrayList<>();
                        List<Int64> amounts = new ArrayList<>();
                        tokenTransferListItem.getTransfersList().forEach(x -> {
                            addresses.add(getAddress(EntityId.of(x.getAccountID())));
                            amounts.add(new Int64(x.getAmount()));
                        });
                        function = new Function(
                                TRANSFER_TOKENS_FUNCTION_NAME,
                                Arrays.asList(
                                        getAddress(tokenEntityId),
                                        new DynamicArray<>(Address.class, addresses),
                                        new DynamicArray<>(Int64.class, amounts)),
                                Collections.emptyList()
                        );
                    } else if (tokenTransferListItem.getNftTransfersCount() == 0) {
                        // transferNFT(address token, address sender, address receiver, int64 serialNumber)
                        NftTransfer nftTransfer = tokenTransferListItem.getNftTransfers(0);
                        function = new Function(
                                TRANSFER_NFT_FUNCTION_NAME,
                                Arrays.asList(
                                        getAddress(tokenEntityId),
                                        getAddress(EntityId.of(nftTransfer.getSenderAccountID())),
                                        getAddress(EntityId.of(nftTransfer.getReceiverAccountID())),
                                        new Int64(nftTransfer.getSerialNumber())),
                                Collections.emptyList()
                        );
                    } else if (tokenTransferListItem.getNftTransfersCount() > 1) {
                        // transferNFTs(address token, address[] memory sender, address[] memory receiver, int64[]
                        // memory serialNumber)
                        List<Address> addresses = new ArrayList<>();
                        List<Int64> amounts = new ArrayList<>();
                        tokenTransferListItem.getNftTransfersList().forEach(x -> {
                            addresses.add(getAddress(EntityId.of(x.getReceiverAccountID())));
                            amounts.add(new Int64(x.getSerialNumber()));
                        });
                        function = new Function(
                                TRANSFER_NFTS_FUNCTION_NAME,
                                Arrays.asList(
                                        getAddress(tokenEntityId),
                                        new DynamicArray<>(Address.class, addresses),
                                        new DynamicArray<>(Int64.class, amounts)),
                                Collections.emptyList()
                        );
                    } else {
                        throw new InvalidDatasetException(String
                                .format("Unknown cryptoTransfer/tokenTransfer scenario"));
                    }
                }

                contractResult.setFunctionResult(FunctionEncoder.encode(function).getBytes(StandardCharsets.UTF_8));
```

2022-02-14 21:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                contractResult.setPayerAccountId(transaction.getPayerAccountId());
Makes sense to move it into an eventual `ContractResultService`

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                        .toBytes("mintToken")
made this change but also removed with recent changes

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAssociateTransactionHandler.java
> +                contractResult.setPayerAccountId(transaction.getPayerAccountId());
Yeah had left it out since was thinking on the workaround approach.
Will leave as is since we're feature gating this until we have the proper data from proto

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private long getPrecompileAmount(TransferList transferList, ContractID contractID) {
Logic removed, as workaround is no longer needed

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.0__precompile_no_gas_limit.sql
> +    alter column gas_limit drop not null;
Removed this so no design doc update needed

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoAddLiveHashTransactionHandler.java
> +    public ContractResult getContractResult(Transaction transaction, RecordItem recordItem) {
Good idea. Will add

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        for (int i = 0; i < transferList.getAccountAmountsCount(); ++i) {
Logic removed

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (contractId == accountId && accountAmount.getAmount() > 0) {
Agreed. This was a workaround, thankfully no longer needed so removing this logic.

2022-02-14 21:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            var accountId = entityIdService.lookup(accountAmount.getAccountID()).getId();
This statement was true with this block.
However, this block is now removed and the general `ContractResult` logic was brought in which does store the `ContractID`.
Will leave `EntityIdService.lookup` in since we're trying to move away from using the deprecated `EntityId.of(ContractID contractId)`

2022-02-14 21:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                // get amount by checking transferList for +ve amount to contractID
Also a preference of mine. Left over from early draft review request.
This was removed

2022-02-14 21:34 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    StorageChange storageChange = contractStateChangeInfo.getStorageChanges(storageIndex);
This was existing code but will update.

2022-02-17 00:17 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertContractResult(RecordItem recordItem, ContractResult contractResult) {
Added

2022-02-17 00:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    StorageChange storageChange = contractStateChangeInfo.getStorageChanges(storageIndex);
Updated

2022-02-17 00:18 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoAddLiveHashTransactionHandler.java
> +    public ContractResult getContractResult(Transaction transaction, RecordItem recordItem) {
Added

2022-02-17 00:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                contractResult.setPayerAccountId(transaction.getPayerAccountId());
Moved

2022-02-18 18:52 UTC, steven-sheehy requested changes

2022-02-18 18:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertContractResult(RecordItem recordItem, ContractResult contractResult) {
All of this logic should be in `ContractResultService`.

2022-02-18 18:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        insertContractResult(recordItem, transactionHandler.getContractResult(transaction, recordItem));
Would suggest adding a `TransactionHandler::onContractResult` that can be passed to the `ContractResultService` to customize the created `ContractResult` for different transaction types.

```suggestion
        contractResultService.process(recordItem, transactionHandler::onContractResult);
```

2022-02-18 19:09 UTC, xin-hedera submitted a review, later dismissed

2022-02-18 19:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setCreatedContractIds(getCreatedContractIds(functionResult));
perhaps add a transient `List<EntityId> createdContractEntityIds` to avoid later on decoding the id into `EntityId` objects

2022-02-18 19:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean contractsPrecompileResults = false;
Non-precompile flow seems fine. 
I don't think we should revert its availability right now in production.
We should gate them separately to allow for separate testing since we don't know which protobuf version traceability and therefore precompile inputs will be made available.

2022-02-18 19:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean contractsPrecompileResults = false;
That's true. How about we keep the name as `contractResults` but make it only apply to precompile results for now. Later, we can expand its use?

2022-02-22 15:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultService.java
> +                                                      ContractResult contractResult);
Yeah, was weighing how we wanted to approach the use of the service when the TransactionHandler existed.
Would definitely prefer a most stateful service approach than mixing it as I currently have.
Will make this change and revert the TransactionHandler changes

2022-02-22 15:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        List<ContractLog> contractLogs = new ArrayList<>();
This was only present due to a desire to separate ownership, where the service was stateless and the transactionHandlers or the EntityItemListener was handling the OnItem() call.
Will drop this split in moving everything to the service

2022-02-22 15:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
Contract create/call will always have ContractID on success. On failure we pull it from the transaction.
What logic is currently in the transaction Handler but i'll be moving it in here also

2022-02-22 16:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
if you look at the code in `main` branch, there's no check on `functionResult.hasContractID()`

again, the problem is as I can recall, services doesn't set contractId for child contract call / create. perhaps we should check if it's changed in services, or if we think it's a bug, we should ask services to make the change.

2022-02-23 14:12 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionHandler.java
> +    }
The downside to moving it to the `EntityRecordItemListener` is that we lose certainty of the type of transaction.
This will result in the `ContractResultService` code having a few checks for the type of transaction to handle the ContractResult scenarios right

2022-02-23 20:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionHandler.java
> +    }
This is why I suggested a `TransactionHandler.onContractResult(ContractResult)` that you could pass to the `ContractResultService` to customize the contract result. But checking the transaction type and populating amount, etc. might be fine too.

2022-02-23 20:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean contractsPrecompileResults = false;
Updated

2022-02-23 23:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
Checked w services and a few things to clarify
- There are no child `ContractCall` transactions
- `ContractCreate` transactions can be both parent and child
- `ContractCreate` transactions may not have `ContractID` set since the newly created `ContractID` should be picked up form receipt
- Precompile cases will always have `ContractID` set
- `ContractResult` and `GasUsed` seem to be the parameters always set on `ContractFunctionResult` creation

Will update these checks accordingly.

2022-02-24 00:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
This was removed

2022-02-24 00:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
I can revert to the initial non-default check. Or I can swap the `ContractFunctionResult.ContractID` check out for the `ContractFunctionResult.ContractResult` check

2022-02-24 00:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    private void insertContractResult(RecordItem recordItem, ContractResult contractResult) {
Moved there

2022-02-24 00:06 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        List<ContractLog> contractLogs = new ArrayList<>();
Removed

2022-02-24 00:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    protected final EntityProperties entityProperties;
Updated

2022-02-24 00:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenDissociateTransactionHandler.java
> +    }
Added this.
Feel like there should be a `TransactionHandler.UpdateEntity` outside of just the `AbstractEntityCrudTransactionHandler`. Still pondering on this

2022-03-04 00:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultService.java
> +                                                      ContractResult contractResult);
Updated

2022-03-04 00:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            var contractStateChangeInfo = functionResult.getStateChanges(stateIndex);
Updated

2022-03-04 00:11 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenWipeTransactionHandler.java
> +@AllArgsConstructor
Reverted

2022-03-04 00:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    protected Contract getContract(EntityId contractId, long consensusTimestamp) {
Removed

2022-03-04 00:16 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        insertContractResult(recordItem, transactionHandler.getContractResult(transaction, recordItem));
Updated logic to pass transactionHandler through and use in Service

2022-03-04 00:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult != ContractFunctionResult.getDefaultInstance() && functionResult.hasContractID()) {
Moved into a method using default instance and checking for `CallResult` which is assured to be nonNull on a valid result.
If the `CallResult` feels like overkill I can drop it

2022-03-07 19:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (recordItem == null) {
Fixed

2022-03-07 19:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setCreatedContractIds(getCreatedContractIds(functionResult));
NO longer decoding so should be good

2022-03-08 22:07 UTC, steven-sheehy requested changes

2022-03-09 02:20 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        insertContractResult(recordItem, transactionHandler.getEntity(recordItem), transactionHandler);
Updated

2022-03-09 02:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (entityProperties.getPersist().isContracts() && recordItem.isSuccessful()) {
Updated

2022-03-09 02:22 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    private TransactionHandlerFactory transactionHandlerFactory;
Updated

2022-03-09 02:22 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultService.java
> +    void process(RecordItem recordItem, EntityId entityId, TransactionHandler transactionHandler);
Agreed, this is the missing part I think.
Should be good now

2022-03-09 02:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
Hmm, this shouldn't be the case.
All Service code paths (unless I missed one) set it.
Let me circle back

2022-03-09 02:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (isPrecompileCall(recordItem.getTransactionBody()) && !entityProperties.getPersist().isContractResults()) {
Updated

2022-03-09 02:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setContractId(lookup(contractEntityId, functionResult.getContractID()));
Updated

2022-03-09 02:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractLog.setRootContractId(rootContractId);
Updated

2022-03-09 02:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult == null || contractResult == null) {
Moved

2022-03-09 02:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        processContractStateChanges(functionResult, contractResult, entityId);
Updated

2022-03-09 02:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (functionResult == null || contractResult == null) {
Updated

2022-03-09 02:27 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
Well, doesn't really matter what current services code paths do. It matters what current and previous services code paths have done. Production data shows it can be null or empty now or at some point in the past.

2022-03-09 18:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
Still present. What did you discover?

2022-03-09 19:40 UTC, steven-sheehy requested changes

2022-03-09 20:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
Yeah, you're correct, there are cases `call_result` is null.
Looked though and there's no case of a null `gas_used` which is the other column I thought was never null.
This is a safer property to check since any called contract should report gas_used even if 0.
Will use that instead since the object comparison in some case doesn't always pick up the defaultInstance. I think Xin noticed this in some of his tests also.

2022-03-09 20:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
`gasUsed` in the protobuf is a `uint64`. As a result, it can't be null and is pointless to check as that is the default value returned from the getter, even for the default instance.

2022-03-09 21:03 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
It was the object comparison.
Will update to use `contractFunctionResult.equals(ContractFunctionResult.getDefaultInstance())`

2022-03-09 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplTest.java
> +//        when(transactionHandlerFactory.get(TransactionType.CONTRACTCALL)).thenReturn(resolvedId);
Removed

2022-03-09 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractStateChange.setContractId(lookup(contractResult.getContractId(), stateChange.getContractID()));
Done

2022-03-09 21:25 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                contractFunctionResult.getContractCallResult() != ByteString.EMPTY;
Updated

2022-03-09 22:26 UTC, steven-sheehy approved these changes
LGTM

2022-03-09 22:36 UTC, merged