Workaround the missing disappearing token transfer issue
hashgraph/hedera-mirror-node pull request #3289
Opened 2022-02-11 21:03 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-02-11 21:04 UTC, xin-hedera commented on .github/workflows/rosetta-api.yml
> -
applied the logic to `check:data` from block 1 so no longer needs the genesis balance JSON file

2022-02-11 21:05 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                              ) as token_associations`
get the latest state of the token associations for an account X <= consensus timestamp T

2022-02-11 21:07 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> +	}
don't even run the SQL query if there's no successful token dissociate.

2022-02-11 21:09 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/demo/validation.json
> +    "start_index": 1,
with this config, `check:data` no longer needs the bootstrap genesis balances JSON file, nor the made up genesis block.

2022-02-11 21:09 UTC, xin-hedera commented on hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
> -)
there won't be token balances at genesis with the changes in go code

2022-02-15 18:32 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> +	}
updated

2022-02-15 18:32 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> +	transactionTypeTokenDissociate int16 = 41
updated

2022-02-16 15:58 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> +		amount := aggregated.Amount - nonFeeTransferMap[accountId]
make the crypto transfers in a consistent order

2022-02-16 16:01 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/account_service.go
> -// getAdditionalTokenBalances get the additional token balances with 0 amount for tokens the account has ever owned by
no longer needed since now AccountRepository.RetrieveBalanceAtBlock also handles the ever owned tokens and returns 0 amount for those tokens in a single call

2022-02-16 16:02 UTC, xin-hedera commented on hedera-mirror-rosetta/build/postgresql.conf
> +max_connections = 200
the default max connections in rosetta config is 100, the default of pg server is 100. under load, quite some queries can fail since the db server refuses to open connections for rosetta server

2022-02-16 16:05 UTC, xin-hedera commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +  exec supervisord --configuration /app/supervisord-offline.conf
with `exec`, the supervisord process can receive signals, so we can do `docker stop -t 90 <container_id>` to gracefully shutdown the services

2022-02-16 16:06 UTC, xin-hedera commented on hedera-mirror-rosetta/build/supervisord-offline.conf
> +
complete the config to enable supervisorctl which works similarly as systemctl

2022-02-16 16:18 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/supervisord.conf
> -user=dummy
Why this change? By default supervisor runs processes as root. We should run all processes with a non-root user like dummy if possible, including the new ones below.

2022-02-16 16:29 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/supervisord.conf
> -user=dummy
Well I don't mean to run supervisord itself as non-root, just its child processes that it kicks off. But perhaps I misunderstood that it's only the `program` block that runs as root by default unless you specify `user`.

2022-02-16 16:34 UTC, xin-hedera commented on hedera-mirror-rosetta/build/supervisord.conf
> -user=dummy
should use `chown` then, just control who can access the unix socket

2022-02-16 17:16 UTC, Nana-EC requested changes
Nice work, some q's and suggestions on 1st
Still digging into test side

2022-02-16 17:16 UTC, Nana-EC commented on docs/rosetta/README.md
> +You can run the rosetta-cli `check:data` command as is. The data configuration section is set with `"start_index": 1`
nit: Give reference to the applicable configurations, so people aren't looking for the definitions in our repo
- https://docs.cloud.coinbase.com/rosetta/docs/configuration-file

2022-02-16 17:16 UTC, Nana-EC commented on docs/rosetta/README.md
> +-v ${PWD}/application.yml:/app/importer/application.yml \
Q: Should we be adding a mount for `/app/rosetta` also?

2022-02-16 17:16 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/account.go
>                                        select max(consensus_timestamp)
nit: `order by desc` and `limit 1` to get the max consensus_timestamp

2022-02-16 17:16 UTC, Nana-EC commented on hedera-mirror-rosetta/app/persistence/transaction.go
> +              select max(abf.consensus_timestamp) as timestamp
`order by abf.consensus_timestamp desc limit 1` instead of `max(abf.consensus_timestamp)`

2022-02-16 17:23 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/domain/entity_test.go
> +	assert.Equal(t, int64(100), entity.GetModifiedTimestamp())
fixed

2022-02-16 17:23 UTC, xin-hedera commented on hedera-mirror-rosetta/build/supervisord.conf
> -user=dummy
changed it to `chown=dummy`

2022-02-16 17:28 UTC, steven-sheehy approved these changes
LGTM! Great work on this

2022-02-16 17:30 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/domain/entity.go
> +	EntityTypeContract = "CONTRACT"
will remove

2022-02-16 18:02 UTC, xin-hedera commented on docs/rosetta/README.md
> +You can run the rosetta-cli `check:data` command as is. The data configuration section is set with `"start_index": 1`
added the reference to the official doc

2022-02-16 18:04 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
>                                        select max(consensus_timestamp)
updated

2022-02-16 18:11 UTC, steven-sheehy approved these changes

2022-02-16 18:33 UTC, Nana-EC commented on docs/rosetta/README.md
> +-v ${PWD}/application.yml:/app/importer/application.yml \
Sounds good

2022-02-16 18:40 UTC, Nana-EC submitted a review, later dismissed
LGTM

2022-02-16 19:14 UTC, Nana-EC approved these changes

2022-02-16 19:26 UTC, merged