Add HIP-331 Account NFT REST API support
hashgraph/hedera-mirror-node pull request #3331
Opened 2022-02-25 00:59 UTC by Nana-EC

**Description**:
Currently there's no simple way to query the mirror node REST API for the nfts associated with a specific account.
HIP-331 describes a design to achieve this

- Add an `AccountController` to manage the HTTP request logic 
- Update `NftService` to query db for nfts given an account Id and some filters
- Update `utils` logic to manage multiple query filters for the next link

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-02-26 00:12 UTC, steven-sheehy reviewed
Still reviewing

2022-02-26 05:44 UTC, xin-hedera requested changes

2022-02-26 05:44 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
I don't think the query built in the current design can return the nfts the user wants.

For example, for the query `/accounts/0.0.X/nfts?token.id=gte:100&serialnumber=gt:3`, suppose the account `X` owns nfts `100-2, 100-4, 100-5, 101-1, 101-3, 101-4`, the response should include the nfts `100-4, 100-5, 101-1, 101-3, 101-4`. But the query will return `100-4, 100-5, 101-4` instead.

The idea is that we should treat nfts (token id plus serialnumber) as a uint128 number with the higher 64-bit as the token id and the lower 64-bit as the serialnumber and order accordingly. this is also why originally I suggested we should use a single paging param `nftId` instead of two.

There's also performance concern with the current indexes on `nft` table, because the primary key doesn't have account info while the `nft__account_token` index doesn't have serialnumber (it'll be slow when sorting the serialnumbers of a specific account, token pair when there are many matching tuples).

2022-02-26 16:41 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +    nftOrder = orderFilterValues.ASC,
Works for me

2022-02-26 16:41 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/tokenIdPathParam'
Updated

2022-02-26 16:41 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParam'
Updated

2022-02-26 16:42 UTC, Nana-EC commented on hedera-mirror-rest/topicmessage.js
> +    [utils.getLastObject(constants.filterKeys.TIMESTAMP, lastTimeStamp)],
Yes, currently part of my local revisions. Wanted to get current version out for review.
Will update

2022-02-26 16:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
Currently not supporting range filtering on token when serial number is also filtered on.
Might be good to start here and iterate on the performance impacts.
Will look into this though.

Also updated the index to cover variations of filter columns

2022-02-28 15:32 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
Then how can the new API support the HIP? I can't figure out how the API can be used to show nfts owned by an account with pagination.

2022-02-28 19:14 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
Will relax the restrictions. I realize this allowed the initial call but for future complex next links I'd be blocking.
Will open it up but restrict on a single `lt(e)` and `gt(e)` combo

2022-02-28 19:15 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +    nftOrder = orderFilterValues.ASC,
Updated

2022-02-28 20:32 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +const updateConditionsAndParamsWithInValues = (filter, invalues, existingParams, existingConditions, fullName) => {
Note a few of these methods are pulled in from `accounts.js`.
To avoid too much churn late in the sprint I didn't replace the whole file

2022-02-28 20:53 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
Also added test to cover range

2022-03-01 00:07 UTC, xin-hedera requested changes

2022-03-01 00:07 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    response.links.next = utils.getPaginationLink(req, response.results.length !== limit, last, order);
I don't think `getPaginationLink` can work as expected.

For instance, suppose an account owns nfts `100-2`, `100-3, `100-4`, 100-5`, for the query `/nfts?token.id=gte:100&serialnumber=gte:2&limit=2&order=asc`, we get nfts `100-2` and `100-3` in the response and `/nfts?token.id=gt:100&serialnumber=gt:3&limit=2&order=asc` as the next url.

2022-03-01 02:04 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +    }
Removed

2022-03-01 02:04 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +};
Removed

2022-03-01 02:04 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +    const lastNftTimestamp = lastRow !== undefined ? lastRow.created_timestamp : null;
Updated

2022-03-01 18:05 UTC, matheus-dallrosa approved these changes
Overall looks good to me.

2022-03-01 18:08 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/accountController.js
> +    switch (filter.key) {
Nit: Have you tried to use polymorphism instead of the switch? I have seen that this logic is duplicated in other controllers. We have a framework that converts http queries / parameters to SQL queries, but the code is spread in a way that is hard to get a good grasp of the logic.

2022-03-01 18:57 UTC, steven-sheehy requested changes

2022-03-01 20:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.0__hip331_nfts_by_account.sql
> +drop index if exists nft__account_token;
do the same for v2.

2022-03-02 00:57 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
This is a good basis.
I'm working on a 3 pronged approach to reduce the complexity of the needed query to get all the data without duplication

2022-03-02 00:58 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +        updateConditionsAndParamsWithInValues(filter, serialNumberInValues, params, conditions, serialNumberFullName);
Will be dropping multi `eq` and any `ne`

2022-03-02 16:06 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const query = `select id from entity where ${conditions.join(' and ')}`;
Simplified

2022-03-02 16:07 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const conditions = ['deleted <> true'];
Adopted

2022-03-02 17:07 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +};
the function in accounts.js builds query depending on the path param format: `shard.ream.alias`, `realm.alias`, and `alias`. The reason it's done so is because that's the list of accepted formats in the ticket of the rest alias.

2022-03-02 17:34 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +const getAccountIdFromAccountAlias = async (accountAlias) => {
Some of this should actually really be in a new `EntityService` but i wanted to get a working solution out first.
Adding shortly

2022-03-02 17:45 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +if (utils.isTestEnv()) {
This avoids having to mock the Request object but also the database calls.
We leave the E2E testing for the `integration.test.js` which does as you noted

2022-03-02 21:00 UTC, steven-sheehy requested changes

2022-03-02 21:08 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +    response.links.next = utils.getPaginationLink(req, response.results.length !== limit, last, order);
Should be fixed now with added approach

2022-03-02 21:10 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +};
Reverting to approach that captures `shard` and `realm`

2022-03-02 21:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/entityService.test.js
> +  // test('EntityService.getAccountFromAlias - Duplicate alias', async () => {
Yes, intentional so i could rebase and push and come back.
Fixed now and pushing shortly

2022-03-02 21:38 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        | serialnumber  | eq                  | Y       | Single occurence only | ?serialnumber=lt:Y |
Updated and added an ordering section to explain the layout

2022-03-02 21:39 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +  const {conditions, params, order, limit} = extractNftsQuery(filters, accountId, nftsByAccountIdParamSupportMap);
Fixed

2022-03-02 21:40 UTC, xin-hedera requested changes

2022-03-02 21:40 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +        }
what about `lt` and `gt`? are the two operators not supported?

2022-03-02 21:40 UTC, xin-hedera commented on hedera-mirror-rest/service/nftService.js
> +    let unionQuery = allQueries.filter((x) => !!x).join('\nunion\n');
should be able to do `union all`

2022-03-02 21:40 UTC, xin-hedera commented on hedera-mirror-rest/service/nftService.js
> +  getNftsFiltersQuery(whereConditions, whereParams, nftOrder, limit, paramsLength = whereParams.length) {
nit: it should be better to have startingParamIndex as the last argument of the function, default is 0.
then just need to pass in the existing params length.

2022-03-02 21:40 UTC, xin-hedera commented on hedera-mirror-rest/service/nftService.js
> +    }
nit: don't think it's necessary there shouldn't be performance difference.

2022-03-02 21:40 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    const lastSerial = lastRow !== undefined ? lastRow.serial_number : null;
serialNumber is `bigint`, we convert it to `Number` in `NftViewModel` which may hit the js number issue. Can create a ticket and address it later.

2022-03-02 21:40 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +      [constants.filterKeys.SERIAL_NUMBER]: lastSerial + 1, // offset by 1 to support inclusve gte|lte comparison
shouldn't it be `lastSerial - 1` if `order=desc`?

need to check if `lastSerial  - 1` results in -1 or the better way is set inclusive = false just for `serialnumber` so don't have to do +/- 1 for lastSerial.

2022-03-02 21:41 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +const getAccountIdFromAccountAlias = async (accountAlias) => {
Moved out to service

2022-03-02 21:49 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +      [constants.filterKeys.SERIAL_NUMBER]: lastSerial + 1, // offset by 1 to support inclusve gte|lte comparison
umm, the minimum nft serial is 1, then no issue with `lastSerial - 1`

2022-03-02 21:50 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +        }
They are.
You can do `lt` or `gt` on `token.id` alone.
You can also use it on `serialnumber` but then that requires `toke.id` filter
See spec file 13 & 14 tests.
I'll add one for token also

2022-03-02 21:51 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    const lastSerial = lastRow !== undefined ? lastRow.serial_number : null;
can remove the redundant `lastRow !== undefined` check

2022-03-02 21:53 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +    }
had this before i had an outer order. Will remove

2022-03-02 21:58 UTC, xin-hedera commented on hedera-mirror-rest/service/nftService.js
> +      const [innerQuery, innerParams] = this.getNftsFiltersQuery(
the inner query may have some performance issue

```sql
select * from nft where account_id = $1 and token_id >= $2 order by token_id, serial_number limit 25
```

pg planner may pick the primary key (token_id, serial_number) for such query.

If we change it to

```sql
select token_id,serial_number from nft where account_id = $1 and token_id >= $2 order by token_id, serial_number limit 25
```

it qualifies as a index only scan, and there should be a better change pg uses the new index nft__account_token_serial.

Can leave it to a later PR.

2022-03-02 22:02 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +    let unionQuery = allQueries.filter((x) => !!x).join('\nunion\n');
Initially I was concerned `union all` would bring in duplicates that we'd have to filter out.
After refining my approach though there shouldn't be any duplicates.
Will add `all`

2022-03-02 22:03 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +        }
problem is the two operators are not handled here for `token.id`?

2022-03-02 22:20 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/accountController.js
> +const getAccountIdFromAccountAlias = async (accountAlias) => {
Shouldn't it be `AccountService` I think `EntityService` is too general.

2022-03-02 23:08 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +      const [innerQuery, innerParams] = this.getNftsFiltersQuery(
Should be fine actually.
This flow uses the full explicit query - `NftService.nftQuery` .
`/api/v1/tokens/{tokenId}/nfts/{serialNumber}/transactions` is the one that uses `NftService.nftByIdQuery` which uses `select * ...`

2022-03-02 23:35 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +const getAccountIdFromAccountAlias = async (accountAlias) => {
Yes in preference. For now given the table is still Entity I didn't want to add any confusion.
When we finally add the `account` table and pull from there then we can also rename this.

2022-03-02 23:36 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +const getAccountIdFromAccountAlias = async (accountAlias) => {
If others feel strongly though i'm open minded

2022-03-02 23:36 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +};
Reverted

2022-03-02 23:36 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/entityService.test.js
> +  // test('EntityService.getAccountFromAlias - Duplicate alias', async () => {
Fixed

2022-03-02 23:48 UTC, xin-hedera commented on hedera-mirror-rest/service/nftService.js
> +      const [innerQuery, innerParams] = this.getNftsFiltersQuery(
Not really, I used select * just because don’t want to be so explicit. Anyways we can revisit it and improve the perf with the potential index only scan query later if needed.

2022-03-03 00:09 UTC, steven-sheehy submitted a review, later dismissed
LGTM besides what others have said

2022-03-03 00:18 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +        }
Yes, I tried to keep it simple by allowing queries that didn't fit the `lower, inner, upper` model just fall through to the single query case and use `lower`.
However, so it's not confusing it might be better to allocate it appropriately.

2022-03-03 00:48 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/accountController.js
> +const getAccountIdFromAccountAlias = async (accountAlias) => {
My suggestion was my brain on auto pilot trying to not couple the name of the service with storage, but since the entire project is defined as an API to access the database, I am ok with it.

2022-03-03 00:49 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/accountController.js
> +if (utils.isTestEnv()) {
If this is the testing pattern the team have been using, I am ok with it.

2022-03-03 00:49 UTC, matheus-dallrosa approved these changes

2022-03-03 01:03 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +      [constants.filterKeys.SERIAL_NUMBER]: lastSerial + 1, // offset by 1 to support inclusve gte|lte comparison
Add a map of inclusive keys that avoids the +1/-1 need

2022-03-03 01:07 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +    }
Removed

2022-03-03 01:07 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +    let unionQuery = allQueries.filter((x) => !!x).join('\nunion\n');
Added

2022-03-03 01:10 UTC, Nana-EC commented on hedera-mirror-rest/service/nftService.js
> +  getNftsFiltersQuery(whereConditions, whereParams, nftOrder, limit, paramsLength = whereParams.length) {
This is sort of what's being done.
By doing this instead it saves you having to pass in the params length in the default case since it'll be calculated by the function. With the option to override when doing multi

2022-03-03 01:43 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +        }
Fixed

2022-03-03 01:44 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +    const lastSerial = lastRow !== undefined ? lastRow.serial_number : null;
Removed

2022-03-03 04:55 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^((eq|gt|gte|lt|lte):)?\d{1,19}?$
why it's changed from `int64` to `string`? wouldn't this break whoever uses tools to generate code from our openapi spec?

2022-03-03 04:56 UTC, xin-hedera approved these changes
LGTM except the concern of type change for `serialnumber` in openapi spec

2022-03-03 14:34 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^((eq|gt|gte|lt|lte):)?\d{1,19}?$
Due to the presence of the comparison operators. In the former unused case there was no support for those

2022-03-03 14:37 UTC, merged