Workaround alias not found issue
hashgraph/hedera-mirror-node pull request #3339
Opened 2022-02-26 05:05 UTC by xin-hedera

**Description**:

This PR addresses the alias not found issue in non fee transfer handling for partial mirror node.

- log the exception instead of halting parser

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

This happened with the rosetta image since nonFeeTransfer for importer is enabled:

```
2022-02-25T15:20:53.775-0600 ERROR scheduling-2 c.h.m.i.p.r.RecordFileParser Error parsing file 2022-02-25T17_55_58.092793000Z.rcd after 1.020 ms com.hedera.mirror.importer.exception.InvalidDatasetException: AccountID not present for alias: 1220fe64efa67fbbe9e0c2937de1a0e1e1b8ca74fcef2133c06af5be486dc4ec4064
  at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.lambda$getAccountId$1(EntityRecordItemListener.java:313)
 at java.base/java.util.Optional.orElseThrow(Optional.java:408)
 at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.getAccountId(EntityRecordItemListener.java:313)
  at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.processNonFeeTransfers(EntityRecordItemListener.java:293)
  at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.onItem(EntityRecordItemListener.java:188)
  at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.onItem(EntityRecordItemListener.java:105)
  at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196)
  at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.tryOnNext(FluxFilterFuseable.java:148)
 at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.fastPath(FluxIterable.java:644)
 at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:529)
  at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
 at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
 at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
 at reactor.core.publisher.MonoCount$CountSubscriber.onSubscribe(MonoCount.java:81)
 at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
 at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
 at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87)
...
``` 

The account whose alias is involved in a crypto transfer transaction does have its cryptocreate transaction ingested by the importer because that transaction happened before the importer's `startDate`.

When `nonFeeTransfer` is enabled, parser tries to map the alias to its account id by looking up the repository, when not found, parser throws `InvalidDatasetException` and gets stuck.

Unfortunately, without additional info, there's no way to reliably figure out the alias -> account mapping just from the crypto transfer tx body and record.

Some examples

1.
```json
{
  "body": [
      ...,
      ["0.0.xxx", 10],
      ["0.0.xxx", 20],
      ["0.0.yyy", 12],
      ["0.0.yyy", 18],
    ],
   "record": [
     ...,
      ["0.0.300", 30],
      ["0.0.400", 30],    
   ]
}
```
We can't tell whether `0.0.xxx` maps to `0.0.300` or `0.0.400`

2. For a crypto transfer tx with both hbar transfers and token transfers with custom fee involved. Since custom fee can be paid in HBAR, and [AssessedCustomFee](https://github.com/hashgraph/hedera-protobufs/blob/975a0e0fdcbfe81fe7f8ff66e5278ed754040a78/services/custom_fees.proto#L128) can only tell the amount the fee collector receives but not the exact amount each payer pays, it's impossible to establish the alias -> account id mapping even when the hbar transfer amounts in the transaction record are unqiue.

The side effect of the workaround is it may cause rosetta `check:construction` to fail since rosetta server can't reconstruct the balance changing operations to be a superset of the original balance changing operations the transaction is built from. nevertheless, it won't cause `check:data` issue.

This may be a short-term workaround but we need it so as to unblock rosetta validation.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-02-26 16:40 UTC, Nana-EC submitted a review, later dismissed
Looks good.
Single non-blocking suggestion on exception and message naming

2022-02-26 16:40 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/exception/AliasNotFoundException.java
> +        return String.format("Alias '%s' not found", alias);
nit: This is more of an AccountByAliasNotFoundException.
If you keep the current file name you could make the message
```suggestion
        return String.format("No account found with alias '%s'", alias);
```

2022-02-26 19:54 UTC, steven-sheehy requested changes

2022-02-26 19:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .orElseThrow(() -> new AliasNotFoundException(Hex.encodeHexString(alias)));
For Hedera managed mirror nodes we probably want to fail fast on bad data so we can catch errors early. We should have some property that controls whether to fail fast on partial data issues. We should make it generic so it works for EVM address and any other fields that have problems with partial mirror nodes. 

It should be an enum so it can support different actions. Something like `hedera.mirror.importer.parser.record.partialDataAction=DEFAULT|ERROR|SKIP`. Where `DEFAULT` will replace the unknown values with defaults appropriate for its data type like `EntityId.EMPTY`, 0, etc. `ERROR` is the current action of throwing an exception and halting processing. `SKIP` would omit the entire transaction.

2022-02-28 17:18 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        .orElseThrow(() -> new AliasNotFoundException(Hex.encodeHexString(alias)));
We could even dynamically detect if it's a partial mirror node by checking if first record item entry is the zero hash or not, then set this to DEFAULT or SKIP automatically.

2022-03-01 16:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/exception/AliasNotFoundException.java
> +        return String.format("Alias '%s' not found", alias);
updated

2022-03-01 16:18 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java
> +    private List<SharedTransfer> findNonFeeTransfersAsSharedTransfers() {
name clash with the function in `IntegrationTest`

2022-03-01 16:19 UTC, xin-hedera commented on hedera-mirror-rosetta/build/supervisord.conf
> +  --spring.config.additional-location=file:/app/importer/
change it to the multi-line format

2022-03-01 17:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__non_fee_transfer_allow_null_entity_id.sql
> +-- allow entity_id to be null
will rename version to `V1.55.1`

2022-03-01 20:34 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/NonFeeTransfer.java
> +public class NonFeeTransfer implements Persistable<Long> {
Why this change? The primary key is definitely not just the consensus timestamp.

2022-03-01 20:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__non_fee_transfer_allow_null_entity_id.sql
> +-- allow entity_id to be null
I would guess that this PR is more likely to get in before the NFT REST API PR, so would be better to be v1.55.0

2022-03-01 20:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                            log.warn(ex.getMessage() + ", action " + partialDataAction);
nit: Would a regular English sentence here and for skip:
```suggestion
                            log.warn("Setting non-fee transfer account to default value due to partial data issue: {}", ex.getMessage());
```

2022-03-01 21:19 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/NonFeeTransfer.java
> +public class NonFeeTransfer implements Persistable<Long> {
There is no primary key even without the change since it's legitimate to have the same (account, amount) multiple times in the tx body.

The change is because `entity_id` now can be null.

2022-03-01 22:05 UTC, steven-sheehy approved these changes
LGTM

2022-03-01 23:26 UTC, Nana-EC approved these changes
LGTM

2022-03-02 01:57 UTC, merged