Add an errata migration
hashgraph/hedera-mirror-node pull request #3353
Opened 2022-03-02 23:14 UTC by steven-sheehy

**Description**:
* Fix invalid `Optional` tag in `hedera.mirror.download.signature.verification` metric
* Add an `errata` enum field to `transaction` and `crypto_transfer`
* Add a `time_offset` to `account_balance_file`
* Insert missing rows as `errata=INSERT`
* Mark affected balances files with `time_offset=-1`
* Mark spurious rows as `errata=DELETE`

**Related issue(s)**:

Fixes #3352 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-03-02 23:28 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/balance/AccountBalanceFile.java
> +    private int timeOffset;
Technically all balance files with the issue are off by one nanosecond. Instead of a `time_offset=-1` I could have an `errata=MODIFIED` column to standardize the field across tables. We would just have to assume if so it's `-1` offset. We should never have this issue again so it might be ok.

2022-03-03 21:19 UTC, Nana-EC requested changes
Some suggestions.
In favour of a MODIFIED but need clarification on use of current `-1.
Also missing documentation on the errata process

2022-03-03 21:19 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/balance/AccountBalanceFile.java
> +    private int timeOffset;
In this case -1 informs the vector action to take right? Its benefit is mostly for balance validation no?
For consistency having the `errata=MODIFIED` column and correcting the value might be valuable so there's an argument for that.

2022-03-03 21:19 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +public class ErrataMigration extends MirrorBaseJavaMigration implements BalanceStreamFileListener {
I think there should be a README update that explains the overall errata process.
It should include these 2 flows
1. Balance offset fix
2. Spurious timestamp fix

2022-03-03 23:18 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +            if (!timestamps.isEmpty()) {
Yes, it's the classic [lazy initialization](https://en.wikipedia.org/wiki/Lazy_initialization#Java) via double-checked locking pattern. `timestamps` is lazily loaded by the parser thread in `onEnd()` and we want to ensure it's done exactly once and protect the otherwise not thread-safe collection.

2022-03-03 23:18 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__errata_schema.sql
> +create type errata_type as enum ('INSERT', 'DELETE');
That's overkill considering we're not touching the row other than adding the `errata=DELETE`. No other columns are touched.

2022-03-03 23:30 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/balance/AccountBalanceFile.java
> +    private int timeOffset;
To clarify `-1` is not an action per se but an adjustment to the balance file's consensus timestamp for use when querying transfers. I don't think we can adjust the `account_balance_file.consensus_timestamp` directly because then the time in the filename would not match and we'd have to adjust the timestamps of all the `account_balance` entries. It'd also be a lot harder to undo if we need to.

My suggestion was just to add the offset in code implicitly when `errata = 'MODIFIED'` is present.

2022-03-03 23:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +                    byte[] recordBytes = in.readLengthAndBytes(1, MAX_TRANSACTION_LENGTH, false, "record");
Tried your suggestion. The `RecordStreamObject` inherits from `AbstractStreamObject` which does an additional `in.readLong()` and `in.readInt()` which are not applicable to my use case and cause it to error.

2022-03-03 23:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +        jdbcOperations.update("update crypto_transfer set errata = 'INSERT' where consensus_timestamp in (:ids)", ids);
Also, the log statement would be wrong since we insert more transfers than transactions.

2022-03-03 23:53 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/balance/AccountBalanceFile.java
> +    private int timeOffset;
Gotcha.
In that case leave as is.
Instead of checking for `errata = 'MODIFIED'` and then pulling the offSet, just check for nonzero offSet or just add it always and avoid the check

2022-03-03 23:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +            if (!timestamps.isEmpty()) {
Gotcha.

2022-03-03 23:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__errata_schema.sql
> +create type errata_type as enum ('INSERT', 'DELETE');
When I said correcting I meant the potential `MODIFIED` option in which we'd actually change a value.
In this case no need so it's necessary.

2022-03-04 00:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +public class ErrataMigration extends MirrorBaseJavaMigration implements BalanceStreamFileListener {
Sure, will scribble something down.

2022-03-04 00:03 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +                    byte[] recordBytes = in.readLengthAndBytes(1, MAX_TRANSACTION_LENGTH, false, "record");
That's fine, not worth the overhead to separate it

2022-03-04 18:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +public class ErrataMigration extends MirrorBaseJavaMigration implements BalanceStreamFileListener {
Done

2022-03-04 21:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +        String sql = "update account_balance_file set time_offset = -1 where consensus_timestamp in (:timestamps)";
```suggestion
        String sql = "update account_balance_file set time_offset = -1 where consensus_timestamp in (:timestamps) and time_offset <> -1";
```
nit: avoid uncessary updates?

2022-03-04 21:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +                "  and amount > 0 and ct.entity_id <> 98 and (ct.entity_id < 3 or ct.entity_id > 27) " +
nit: same here, add condition errata <> 'DELETE' to avoid unnecessary update

2022-03-04 21:25 UTC, xin-hedera commented on docs/database.md
> +Some tables may contain errata information to workaround known issues with the stream files. The state of the consensus
nit, clarify the issues only exist in mainnet stream files.

2022-03-04 21:25 UTC, xin-hedera approved these changes
LGTM, just some nits.

2022-03-04 21:27 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/CryptoTransfer.java
> +    @Convert(converter = AccountIdConverter.class)
is the converter still needed?

2022-03-04 22:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +                "  and amount > 0 and ct.entity_id <> 98 and (ct.entity_id < 3 or ct.entity_id > 27) " +
Prefer not to for two reasons. Have to check both null case and `<> 'DELETE'`, making it more complex. Also, if for some reason the CTE row was marked as `DELETE` but the the outer query was not it would not be fixed in a subsequent run. So it could cause correctness issues.

2022-03-04 22:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +        String sql = "update account_balance_file set time_offset = -1 where consensus_timestamp in (:timestamps)";
Added

2022-03-04 22:16 UTC, steven-sheehy commented on docs/database.md
> +Some tables may contain errata information to workaround known issues with the stream files. The state of the consensus
Added

2022-03-04 22:16 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/CryptoTransfer.java
> +    @Convert(converter = AccountIdConverter.class)
Removed

2022-03-04 22:26 UTC, xin-hedera approved these changes
SLGTM

2022-03-07 16:35 UTC, Nana-EC submitted a review, later dismissed
LGTM

2022-03-09 04:31 UTC, xin-hedera approved these changes
LGTM

2022-03-09 15:35 UTC, Nana-EC requested changes
Minor documentation request, then it's all good

2022-03-09 15:35 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +        String sql = "with spurious_transfer as (" +
nit: if not here then in the README but it might be worthwhile highlighting the logic of this complicated query.
Especially the significance of the integer values and their cases.
Since the errata file doesn't come through the record stream I think it's important to document everything clearly.

2022-03-09 15:35 UTC, Nana-EC commented on docs/database.md
> +Some tables may contain errata information to workaround known issues with the stream files. The state of the consensus
If there's any high level errata structure logic we should note it here. If not then no-op

2022-03-09 18:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +        String sql = "with spurious_transfer as (" +
Added some comments.

2022-03-09 18:04 UTC, steven-sheehy commented on docs/database.md
> +Some tables may contain errata information to workaround known issues with the stream files. The state of the consensus
no-op

2022-03-09 19:25 UTC, Nana-EC requested changes
LGTM

2022-03-09 19:26 UTC, Nana-EC approved these changes
LGTM

2022-03-09 19:42 UTC, merged