Remove crypto transfer for initial balance
hashgraph/hedera-mirror-node pull request #3358
Opened 2022-03-03 21:56 UTC by matheus-dallrosa

**Description**:
Removes the the creation of crypto transfers that were being made specifically for the initial balance of a crypto account.
Only adds a crypto transfer per account amount in `TransferList`.

**Related issue(s)**:
Removes the creation of crypto transfer for the initial balance.
Fixes unit tests that were taking the previous rules into consideration.
Create unit test specifically for the new rule.

Fixes #770 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-03-03 22:49 UTC, xin-hedera submitted a review, later dismissed

2022-03-03 23:50 UTC, Nana-EC requested changes
Some suggestions on more performant sql query and verification check for amount.

2022-03-03 23:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__remove_crypto_transfer_with_zero_amount.sql
> +delete from crypto_transfer where amount = 0
You could do something like
```sql
crypto_creates as (
    select consensus_timestamp
    from transaction
    where type = 11
)
delete
from crypto_transfer ct using crypto_creates cc
where ct.consensus_timestamp = cs.consensus_timestamp
  and amount = 0;
```

2022-03-03 23:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                 insertCryptoCreateTransferList(consensusTimestamp, recordItem);
In the eventual method you can add logic to check for a zero amount.
Then decide what to do with it based on `parserProperties.getPartialDataAction()`

2022-03-03 23:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                 insertCryptoCreateTransferList(consensusTimestamp, recordItem);
What do you mean? There's no zero amount in the record.

2022-03-07 18:38 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__remove_crypto_transfer_with_zero_amount.sql
> +delete from crypto_transfer where amount = 0
Nice strategy. I updated the migration script.

2022-03-07 18:38 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> -                insertCryptoCreateTransferList(consensusTimestamp, recordItem);
Good catch, I hadn't looked at the implementation of `insertTransferList`. Removed.

2022-03-07 18:38 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        final Transaction transaction = cryptoCreateTransaction();
Even though the method `cryptoCreateTransaction` is creating a transaction with an initial balance, there is no transfers for it, and because of that there is no transfer in the transfer list for the initial balance. I set the initial balance to `0`. Done.

2022-03-07 18:38 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                () -> assertEquals(3, cryptoTransferRepository.count()),
Done. I hadn't done the `doesNotHaveDuplicates` validation, because I would have to refactor many tests, but I did it now.

2022-03-07 18:39 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                () -> assertEquals(6, cryptoTransferRepository.count()), // 3 + 3 fee transfers + 2 for initial balance
Forgot this one. Removed.

2022-03-07 20:48 UTC, steven-sheehy requested changes

2022-03-07 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__remove_crypto_transfer_with_zero_amount.sql
> +	where type = 11
Should also check if `success = 22` as Xin mentioned since that's what was around the initial balance code. That will greatly reduce the number of rows returned.

2022-03-07 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +import org.jclouds.openstack.swift.v1.domain.Account;
Bad import

2022-03-07 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +@Tag("entity-record-item-listener")
Is this needed?

2022-03-07 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +    protected IterableAssert<CryptoTransfer> assertCryptoTransfers(
Helper methods like this and `groupCryptoTransfersByAccountId` should be below `@Test`'s and sorted alphabetically within the other helpers.

2022-03-07 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +    private void groupCryptoTransfersByAccountId(final TransactionRecord.Builder recordBuilder,
Is this really needed? This is grouping transfers by account, but that shouldn't be necessary if the test is set up properly. It could in fact cause unexpected issues by covering up those incorrect expectations.

2022-03-07 21:45 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +@Tag("entity-record-item-listener")
Removed.

2022-03-07 21:45 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +import org.jclouds.openstack.swift.v1.domain.Account;
Removed.

2022-03-07 21:52 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +    private void groupCryptoTransfersByAccountId(final TransactionRecord.Builder recordBuilder,
Some tests want to add some transfers to the builder, but they can't rely on the fact that there will be no other transfer inside the builder for the same account. Imagine if later someone adds a new transaction to the builder at the `buildTransactionRecord` method, and some tests break, it is gonna take some time to check what is going on. What I agree is that the construction of the data being used should be more separate from  test to test.

2022-03-07 22:04 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +    protected IterableAssert<CryptoTransfer> assertCryptoTransfers(
Ok. I tried to see some pattern in the organization of the methods, but the one you mentioned was not present, I am gonna move the methods. Done.

2022-03-07 22:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__remove_crypto_transfer_with_zero_amount.sql
> +	where type = 11
Done.

2022-03-07 22:51 UTC, steven-sheehy requested changes

2022-03-07 22:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.55.2__remove_crypto_transfer_with_zero_amount.sql
> +where ct.consensus_timestamp = cs.consensus_timestamp
Tests are failing

```suggestion
where ct.consensus_timestamp = cc.consensus_timestamp
```

2022-03-08 17:09 UTC, steven-sheehy approved these changes
LGTM

2022-03-08 18:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                 insertCryptoCreateTransferList(consensusTimestamp, recordItem);
Hmm, must mixed up the details here. All good here.

2022-03-08 18:29 UTC, Nana-EC approved these changes
LGTM

2022-03-08 18:42 UTC, merged