Add a balance reconciliation job
hashgraph/hedera-mirror-node pull request #3387
Opened 2022-03-10 21:32 UTC by steven-sheehy

**Description**:

**Related issue(s)**:

Fixes #3296 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-03-11 22:45 UTC, steven-sheehy commented
Will look into NFT reconciliation in a follow up.

2022-03-14 16:21 UTC, Nana-EC requested changes
Some nits and suggestions

2022-03-14 16:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/ReconciliationProperties.java
> + * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2019 - 2022 Hedera Hashgraph, LLC
```

2022-03-14 16:21 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/ReconciliationProperties.java
> +            String message = String.format("Start date %s must not be after end date %s", startDate, endDate);
nit
```suggestion
            String message = String.format("Start date %s must not be valid and after end date %s", startDate, endDate);
```
or
```suggestion
            String message = String.format("Start date %s must not be set and after end date %s", startDate, endDate);
```

2022-03-14 16:21 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationServiceTest.java
> + * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2019 - 2022 Hedera Hashgraph, LLC
```

2022-03-14 16:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/ReconciliationProperties.java
> +            String message = String.format("Start date %s must not be after end date %s", startDate, endDate);
Neither of those make any sense. I assume you didn't mean to negate those two additions. Technically the `@NotNull` will check validity from user input and the extra null check is for internal assignments.

2022-03-14 16:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +    @Scheduled(cron = "${hedera.mirror.importer.reconciliation.cron:0 0 0 * * *}")
I'll just provide a link to the Spring [docs](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#scheduling-cron-expression) then.

2022-03-14 17:23 UTC, xin-hedera requested changes
just one nit

2022-03-14 17:32 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +        Throwable t = null;
It looks like this one is never used.

2022-03-14 17:50 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +        Sets.difference(previous.keySet(), current.keySet()).forEach(k -> current.put(k, 0L));
Nit: I don't know how many entities we usually have, but this can be improved. We don't need to compute the differences, also we don't need the `Map.difference`. Again, this is a Nit I don't know if the optimization is needed.

2022-03-14 18:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> + * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
Done

2022-03-14 18:46 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.reconciliation.cron`                                | 0 0 0 * * *             | When to run the balance reconciliation job. Defaults to once a day at midnight.
Added link to spring docs

2022-03-14 18:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/ReconciliationException.java
> +
Added

2022-03-14 18:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +        Throwable t = null;
Removed

2022-03-14 19:21 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +        long toTimestamp = DomainUtils.convertToNanosMax(reconciliationProperties.getEndDate());
I think this one can be computed at the constructor and kept as a field.

2022-03-14 19:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +        long toTimestamp = DomainUtils.convertToNanosMax(reconciliationProperties.getEndDate());
Spring has a mechanism to update properties while the application is running, so would prefer not to make it static on startup. Duplicating the property outside the `ReconciliationProperties` also doesn't seem very encapsulated. Since this occurs once per balance file I don't think it's worth optimizing in this manner.

2022-03-14 19:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/BalanceReconciliationService.java
> +        Sets.difference(previous.keySet(), current.keySet()).forEach(k -> current.put(k, 0L));
You're right, I originally used some of the other methods on `Difference` but no longer do so. I changed it to use `Map.equal()` and only construct the difference if it's not equals for logging purposes.

2022-03-14 20:20 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-03-14 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reconciliation/ReconciliationProperties.java
> +            String message = String.format("Start date %s must not be after end date %s", startDate, endDate);
I modified it with some different verbiage since yours didn't account for equals.

2022-03-15 00:11 UTC, Nana-EC submitted a review, later dismissed
LGTM

2022-03-15 01:35 UTC, matheus-dallrosa approved these changes

2022-03-15 14:49 UTC, xin-hedera approved these changes
LGTM

2022-03-15 14:49 UTC, merged