Add Crypto allowance REST API support
hashgraph/hedera-mirror-node pull request #3388
Opened 2022-03-10 23:10 UTC by Nana-EC

**Description**:
Expose crypto allowances

- Update `accountController`

**Related issue(s)**:

Fixes #3244 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-03-14 20:36 UTC, steven-sheehy requested changes

2022-03-14 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts-crypto-allowances-03-not-found.spec.json
> +  "responseStatus": 200,
We should have a spec for when account ID not found

2022-03-14 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/accountController.js
> +      response.links.next = utils.getPaginationLink(req, response.allowances.length !== limit, last, order);
This is already check above.

```suggestion
      response.links.next = utils.getPaginationLink(req, false, last, order);
```

2022-03-14 20:36 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/accountController.js
> +      spenderFilter.length === 1 && constants.queryParamOperatorPatterns.eq.test(spenderFilter[0].operator);
Why do we need to explicitly check this scenario? There should only be one row for owner + spender so this check would only be useful for a rare corner case if they put a limit of `limit=1&spender=eq:100`.

2022-03-14 20:42 UTC, matheus-dallrosa submitted a review, later dismissed

2022-03-15 16:18 UTC, Nana-EC commented on hedera-mirror-rest/service/cryptoAllowanceService.js
> +class CryptoAllowanceService extends BaseService {
I considered this but they're all different tables and I preferred a 1:1 of service to db table where possible.
Also the parts that are reuse are better candidates to be pushed in the BaseService as methods.
It's a valid approach if we want all allowance calls to be in one file so i'm open minded to it.

2022-03-15 17:25 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +      spenderFilter.length === 1 && constants.queryParamOperatorPatterns.eq.test(spenderFilter[0].operator);
Yep, the rare case is the only reason it's there.
I came across it when testing

2022-03-15 20:44 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/accounts-crypto-allowances-03-not-found.spec.json
> +  "responseStatus": 200,
As with the accounts nft case i can add one that makes sure alias is points to a valid account.
Though, I think you're alluding to one that requires we always make a DB call to check an accountId (i.e. `x.y.z`) is valid.
I'm not sure the additional db call is necessary for this API, although there's an argument for it's addition to differentiate between no allowances and a non valid accountId.

2022-03-15 21:07 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/accounts-crypto-allowances-03-not-found.spec.json
> +  "responseStatus": 200,
Though an extra db call i think it's the right addition to make so i'll add a db call for an account existence check

2022-03-16 00:17 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: ne:300
Reduced and updated

2022-03-16 00:17 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Updated to number

2022-03-16 00:18 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      name: spender.id
Updated

2022-03-16 00:18 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +const extractCryptoAllowancesQuery = (filters, accountId, startPosition = 1) => {
Moved to `AllowanceController`

2022-03-16 00:18 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/accounts-crypto-allowances-03-not-found.spec.json
> +  "responseStatus": 200,
Added

2022-03-16 00:18 UTC, Nana-EC commented on hedera-mirror-rest/controllers/accountController.js
> +      response.links.next = utils.getPaginationLink(req, response.allowances.length !== limit, last, order);
Updated

2022-03-16 14:57 UTC, xin-hedera requested changes

2022-03-16 14:57 UTC, xin-hedera commented on hedera-mirror-rest/service/entityService.js
> +    let entity = null;
better rename it to `encodedId` or `id` to avoid confusion.
```suggestion
    let encodedId = null;
```

2022-03-16 14:57 UTC, xin-hedera commented on hedera-mirror-rest/service/entityService.js
> +      }
will this be an issue for a partial mirror node? Do we check account existence before?

2022-03-16 14:57 UTC, xin-hedera commented on hedera-mirror-rest/controllers/allowanceController.js
> +    if (!_.isEmpty(response.allowances) && response.allowances.length === limit) {
nit, `response.allowances.length === limit` implies `response.allowances` isn't an empty array

```suggestion
    if (response.allowances.length === limit) {
```

2022-03-16 14:57 UTC, xin-hedera commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
why are we using regex to match it? the filters are formatted so the operators will be one of the following in `opsMap`:

```
const opsMap = {
  lt: ' < ',
  lte: ' <= ',
  gt: ' > ',
  gte: ' >= ',
  eq: ' = ',
  ne: ' != ',
};
```

2022-03-16 16:13 UTC, steven-sheehy requested changes

2022-03-16 16:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsCryptoAllowanceSpender.js
> +  .check('Account crypto allowances for spender results OK', (r) => isValidListResponse(r, resultListName))
Until we can figure out a way to dynamically find any account with allowances we might not want to check list is non-empty

2022-03-16 16:13 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: listNftCryptoAllowancesByAccountId
```suggestion
      operationId: listCryptoAllowancesByAccountId
```

2022-03-16 16:13 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/allowanceController.js
> +    const allowances = await CryptoAllowanceService.getAccountCrytoAllowances(conditions, params, order, limit);
```suggestion
    const allowances = await CryptoAllowanceService.getAccountCryptoAllowances(conditions, params, order, limit);
```

2022-03-16 16:25 UTC, Nana-EC commented on hedera-mirror-rest/service/entityService.js
> +      }
We didn't but Steven had suggested we add this check.
Makes sense since without it you can't differentiate between an empty list and a non-existent accountId.
I think in a partial mirror node it makes sense still since we're saying the account is missing from the db, not that the account is non-existent on the network.

2022-03-16 16:35 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
In some cases a single regex test was better than multiple string comparisons.
This isn't one of those cases so I can use opsMap check

2022-03-16 17:01 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +    const allowances = await CryptoAllowanceService.getAccountCrytoAllowances(conditions, params, order, limit);
Corrected

2022-03-16 17:01 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      operationId: listNftCryptoAllowancesByAccountId
Updated

2022-03-16 17:02 UTC, Nana-EC commented on hedera-mirror-test/k6/src/rest/test/accountsCryptoAllowanceSpender.js
> +  .check('Account crypto allowances for spender results OK', (r) => isValidListResponse(r, resultListName))
Updated to just `isSuccess`

2022-03-16 17:02 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
Updated cases where we do a single check

2022-03-16 17:02 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +    if (!_.isEmpty(response.allowances) && response.allowances.length === limit) {
Updated

2022-03-16 17:02 UTC, Nana-EC commented on hedera-mirror-rest/service/entityService.js
> +      entity = EntityId.parse(alias, constants.filterKeys.ACCOUNT_ID).getEncodedId();
Yeah also just picked up this and removed

2022-03-16 17:02 UTC, Nana-EC commented on hedera-mirror-rest/service/entityService.js
> +    let entity = null;
Updated

2022-03-16 17:02 UTC, Nana-EC commented on hedera-mirror-rest/service/entityService.js
> +      const alias = await this.getAccountIdFromAlias(AccountAlias.fromString(accountIdString));
Updated

2022-03-16 18:31 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
We support `eq` only but multiple of it.
That's why i'm checking for anything other than `eq` and support

2022-03-16 18:37 UTC, xin-hedera commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
right. so we don't have to check it here again. if for the spender id query filter, the operator is not `eq`, we'd have already failed fast with invalid parameter error.

2022-03-16 19:13 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
Ah yes. Was looking at the wrong block of code. Correct, will simplify

2022-03-16 19:24 UTC, Nana-EC commented on hedera-mirror-rest/controllers/allowanceController.js
> +        utils.isRegexMatch(constants.queryParamOperatorPatterns.eq, spenderFilter[0].operator);
Simplified

2022-03-16 19:43 UTC, steven-sheehy approved these changes
LGTM

2022-03-16 19:56 UTC, xin-hedera approved these changes
LGTM

2022-03-16 20:08 UTC, merged