Add support to create2
hashgraph/hedera-mirror-node pull request #3403
Opened 2022-03-14 14:23 UTC by matheus-dallrosa

**Description**:
This PR modifies all the routes with `/contracts` to support Create2 Ids.
When receiving a Create2 id as a path or query param, the contract id with the respective Create2 id will be found in the database and the contract id of the contract will be used instead of the Create2 id.

**Related issue(s)**:

Fixes #3271 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-03-14 21:07 UTC, steven-sheehy requested changes
Please rename references to create2 to evm address.

2022-03-14 21:07 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +    return createEntityId(BigInt(contractId.shard), BigInt(contractId.realm), BigInt(contractId.id)).getEncodedId();
This logic is wrong. The returned id is already an encoded ID that contains shard, realm and num encoded within it. Can adjust the query as well.

```suggestion
    return contractId.id;
```

2022-03-14 21:07 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  if (ContractService.isValidCreate2Id(contractId)) {
There's already a `EntityId.isValidEvmAddress()`

2022-03-14 22:58 UTC, steven-sheehy requested changes

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-01-specific-id.spec.json
> +    "/api/v1/contracts/0x62cf9068fed962cf9aaabbb962cf9068fed9dddd"
I'm not sure we should support `0x` prefix for EVM address. We don't for alias and it starts to get messy when you include shard and realm.

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-01-specific-id.spec.json
> +    "/api/v1/contracts/0x62cf9068fed962cf9aaabbb962cf9068fed9dddd"
Add URLs for EVM address with shard and realm
```suggestion
    "/api/v1/contracts/62cf9068fed962cf9aaabbb962cf9068fed9dddd",
    "/api/v1/contracts/0.62cf9068fed962cf9aaabbb962cf9068fed9dddd",
    "/api/v1/contracts/0.0.62cf9068fed962cf9aaabbb962cf9068fed9dddd"
```

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-02-specific-id-timestamp.spec.json
> +        "evm_address": "62cf9068fed962cf9068fed962cf9068fed9dddd"
nit: Rest of fields are sorted except new one her. Same in other specs

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-03-specific-id-timestamp-historical-missing-file.spec.json
> -    "/api/v1/contracts/8001?timestamp=ne:997654.000123460&timestamp=lte:997654.000123480"
I'm not sure we need to adjust every contract spec to duplicate the tests with EVM address. This test is mainly checking if the timestamp filter works. There is a execution cost to each URL we add so maybe just add EVM address variants to one spec for every endpoint, but not every query query param within an endpoint.

Same comment for other specs.

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-12-contract-id.spec.json
> +    "/api/v1/contracts?contract.id=0x70f2b2914a2a4b783faefb75f459a580616fcb5e"
Drop 0x and add shard and realm variants

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +    "/api/v1/contracts/0x70f2b2914a2a4b783faefb75f459a580616fcb5e/results/167654.000123456"
Drop 0x and add shard an realm variants

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractIdValue = req.query[constants.filterKeys.CONTRACT_ID];
I don't think this handles the case when there's multiple query param values for the same param. We should leverage the common utils for validation.

2022-03-14 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  req.query[constants.filterKeys.CONTRACT_ID] = contractId.value;
I don't think it's a good practice to modify the request params that come from express. We should extract them into a variable instead.

2022-03-15 17:45 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
>        name: contractId
Done.

2022-03-15 17:55 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: Contract id. Can also be a create2 id that matches the regex ^(0x)[A-Fa-f0-9]{40}$
Done.

2022-03-15 17:56 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A network entity encoded as an EVM address in hex. Can also be a Create2 id which will also match the mentioned regex.
Done.

2022-03-15 17:57 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A network entity encoded as an EVM address in hex. Can also be a Create2 id which will also match the mentioned regex.
Done.

2022-03-15 17:58 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: '0x70f2b2914a2a4b783faefb75f459a580616fcb5e'
It is not being tested against the regex you mentioned, because I am only using it to query the actual id of the contract.

2022-03-15 18:14 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          summary: A create2 id that matches the regular expression ^(0x)[A-Fa-f0-9]{40}$. Example of create2 id equals with no operator
Done.

2022-03-15 18:30 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: Contract id. Can also be a create2 id that matches the regex ^(0x)[A-Fa-f0-9]{40}$
Just to clarify, the CREATE2 address is also called the EVM address. There are two forms of the EVM address:

* 20 byte shard realm num format
* 20 byte CREATE2 hash

The mirror node doesn't need to differentiate between the two, it just treats them as a random 20 byte arrays. Hence why we shouldn't use create2 terminology anywhere and just use EVM address.

2022-03-15 18:34 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +    return createEntityId(BigInt(contractId.shard), BigInt(contractId.realm), BigInt(contractId.id)).getEncodedId();
Would even just return `contractId.id` and allow the viewModels to handle formatting

2022-03-15 18:49 UTC, Nana-EC requested changes
Good start.
I'm okay with the logic to treat query and path values as if they were filter objects.
I don't think we should modify the req on process though.
Will wait for other feedback to be addressed also.

2022-03-15 18:49 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  return {timestamp: utils.parseTimestampParam(consensusTimestamp)};
If changing the return then update the method name or add a description.
It's actually weird to validate both but only return one so maybe consider using the separate method if you go this route

2022-03-15 19:02 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/contractService.js
> +    return createEntityId(BigInt(contractId.shard), BigInt(contractId.realm), BigInt(contractId.id)).getEncodedId();
Done.

2022-03-15 19:07 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: '0x70f2b2914a2a4b783faefb75f459a580616fcb5e'
We don't use the OpenAPI spec at all to serve our API. However, the OpenAPI spec is used by clients to generate code or do validation so we should ensure the regex covers all acceptable input.

2022-03-15 19:11 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  if (ContractService.isValidCreate2Id(contractId)) {
Done.

2022-03-15 19:14 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-01-specific-id.spec.json
> +    "/api/v1/contracts/0x62cf9068fed962cf9aaabbb962cf9068fed9dddd"
You need a different regex anyway since you need to support optional shard and realm.

2022-03-15 19:48 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-02-specific-id-timestamp.spec.json
> +        "evm_address": "62cf9068fed962cf9068fed962cf9068fed9dddd"
Fixed.

2022-03-15 19:52 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  req.query[constants.filterKeys.CONTRACT_ID] = contractId.value;
I think it is a common thing to do, specially in a middleware. In this case I did not want to create a middleware, because I thought it would an overkill.

2022-03-15 21:46 UTC, xin-hedera requested changes

2022-03-15 21:46 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  });
this won't work if the evm address is converted from `shard.realm.num` and

- the contract is created before services 0.23.0 since the evm_address column for that contract in db is `null`
- or the contract is created with the create2 opcode since what's in db is the create2 evm address

so the correct way to handle evm address is if it's of encoded `shard.realm.num` format, we should decode it, do some sanity check, then encode the `shard.realm.num` to get the `id` for the subsequent queries. Otherwise, it should be a create2 evm address, and we can query the db to get the corresponding contract id.

2022-03-16 14:43 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: '0x70f2b2914a2a4b783faefb75f459a580616fcb5e'
The create2IdNoOperator was removed, then I think this comment can be resolved.

2022-03-16 15:20 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-03-specific-id-timestamp-historical-missing-file.spec.json
> -    "/api/v1/contracts/8001?timestamp=ne:997654.000123460&timestamp=lte:997654.000123480"
Done. I also removed URLs from other tests.

2022-03-16 15:25 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-12-contract-id.spec.json
> +    "/api/v1/contracts?contract.id=0x70f2b2914a2a4b783faefb75f459a580616fcb5e"
Done.

2022-03-16 17:11 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  logger.info('1: ' + JSON.stringify(req.query));
Yes sir. It was removed already.

2022-03-16 17:12 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +const getContractByIdQuery = ({timestampConditions, columnName = Contract.ID}) => {
This is a very respected pattern between javascript users. The object construction destruction is way better than the raw parameters.

2022-03-16 17:54 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +const getContractByIdQuery = ({timestampConditions, columnName = Contract.ID}) => {
I do think code style consistency is more important here, unless we agree we will adopt a different pattern and update existing code over time, put aside whether object construction then destruction is better.

2022-03-16 21:10 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  const contractIdValue = req.query[constants.filterKeys.CONTRACT_ID];
I removed this and used the utils for validation

2022-03-16 21:11 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  req.query[constants.filterKeys.CONTRACT_ID] = contractId.value;
I removed this and used the utils for validation.

2022-03-16 21:19 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +const computeContractIdFromContractIdPathParam = async ({req, avoidEvmAddress = true}) => {
It was removed. Please, take another look at the `contractController` and its interaction with the `contractService`. I have made some refactoring and removed some duplications.

2022-03-16 21:19 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  });
This code does not exist anymore. See my answer to the comment above.

2022-03-16 21:21 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +const getContractByIdQuery = ({timestampConditions, columnName = Contract.ID}) => {
I think it would be better to use this pattern. The last few days I had to change parameters and default values for function parameters, and because we were not using this pattern I had a bad time.

2022-03-16 21:23 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  return {timestamp: utils.parseTimestampParam(consensusTimestamp)};
Can we just ignore the contract id for this case? It is not being used.

2022-03-16 22:25 UTC, Nana-EC reviewed
Commenting instead of Requesting Changes so as not to block whiles i'm out.

I think the current aim of handling CREATE2 format is similar to what we do for accountAlias.
In that case the logic could/should be similar to what we do in the accounts endpoint to format and check from DB when an alias is used.
Get the filter from the req, use filters to produce sql, if conversion is needed then do so.
If service calls needs to use an id on other DB calls then convert evmAddress to id. Otherwise it should be fine to filter with evmAddress.

We shouldn't make the utils function of filter object creation query the DB as it messes up separations of concern.
Eventually we want to get the flow to a point where req.query items are formatted into object that can be passed directly to the Services and then their conversion to db queries occurs.

I think you should look at the `accounts/<accountIdOrAlias>/nfts` and newly added `accounts/<accountIdOrAlias>/allowances/crypto` to see a model you can refer to

2022-03-16 22:25 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +const getContractByIdQuery = ({timestampConditions, columnName = Contract.ID}) => {
I see the benefit of the object creation but we shouldn't use it randomly.
The OO approach makes sense for a valid object.
If there are parameters that make sense grouped together then they should be a valid object created in a predictable manner.
We shouldn't just group things for the sole purpose of easy update. They should be correlated in some manner to justify grouping

2022-03-16 22:25 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  const {conditions, params, timestampOrder, indexOrder, limit} = extractContractLogsByIdQuery(
I think the Query build might be the better place to do the async db calls.
When a filter value is a contract.id column but an evmAddress then you can do the conversion.
Maybe even do it collectively

2022-03-17 15:29 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  return {timestamp: utils.parseTimestampParam(consensusTimestamp)};
I agree with you, I also think we should remove it from the route.

2022-03-17 15:49 UTC, xin-hedera requested changes

2022-03-17 15:49 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  const query = getContractByIdQuery({timestampConditions, columnName: contractId.columnName});
if the evm address is encoded from `shard.realm.num`, we should get the encoded 64-bit id and use column name `id` to build the query.

if the evm address is in the create2 form, use the `evm_address` column plus the optional `shard` / `realm` columns if they are present in the path param. can't just query by the create2 evm address itself without verifiying shard / realm

2022-03-17 15:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/contractService.test.js
> +        expiration_timestamp: null,
nit, most fields should have a default in integrationDomainOps so don't have to set value here unless it's used in the test.

2022-03-17 15:53 UTC, matheus-dallrosa commented on hedera-mirror-rest/utils.js
> +const buildAndValidateFilters = async (query, filterValidator = filterValidityChecks) => {
What if the formatting process needs a DB call? What if to format a value we need a value from the database?

2022-03-17 15:54 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  const {conditions, params, timestampOrder, indexOrder, limit} = extractContractLogsByIdQuery(
Understood, I will follow your suggestion.

2022-03-17 18:50 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +const buildAndValidateFilters = async (query, filterValidator = filterValidityChecks) => {
There should be no DB requirement to format. HTTP req params should just be validated and simple conversions in app can be done prior to the service level.
The issue here isn't formatting but rather conversion.
I'm just highlighting that we should do the conversion closer to the service call or in where it makes sense.
Not sure what others think

And yes we have a bit more documentation to right.
Things like the architecture and separations practices we want to maintain.

2022-03-17 20:04 UTC, steven-sheehy requested changes

2022-03-17 20:04 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +const CREATE_2_ID = /^(0x)[A-Fa-f0-9]{40}$/;
Unused

2022-03-18 17:05 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: '0x70f2b2914a2a4b783faefb75f459a580616fcb5e'
The `contractIdQueryParam` already has the schema for the `EvmAddress`. The `contractIdPathParam` did not have it, but now I have added it.

2022-03-18 17:07 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +const computeContractIdFromEvmAddress = async ({contractIdValue, avoidEvmAddress}) => {
Removed.

2022-03-18 20:00 UTC, matheus-dallrosa commented on hedera-mirror-rest/utils.js
> +const buildAndValidateFilters = async (query, filterValidator = filterValidityChecks) => {
I removed the DB call from the `buildAndValidateFilters` method. Done.

2022-03-18 20:00 UTC, matheus-dallrosa commented on hedera-mirror-rest/utils.js
> +        comparator.value = (
Done.

2022-03-18 22:35 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  const {conditions, params, timestampOrder, indexOrder, limit} = extractContractLogsByIdQuery(
Done.

2022-03-18 22:37 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/contractService.js
> +const CREATE_2_ID = /^(0x)[A-Fa-f0-9]{40}$/;
Done.

2022-03-18 23:22 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-logs-01-no-params.spec.json
> +    "/api/v1/contracts/abbcccddddeeeeeefffffff000000068fed9dddd/results/logs"
Done.

2022-03-18 23:22 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-logs-12-topics-timestamp-range-invalid-too-big.spec.json
> +    "contracts": [
Done.

2022-03-18 23:22 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-logs-13-topics-timestamp-range-invalid-backwards.spec.json
> +    "contracts": [
Done.

2022-03-18 23:23 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
>          $ref: '#/components/schemas/EntityId'
Apparently I already add it. I also added some examples.

2022-03-18 23:36 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +const evmAddressRegex = /^(\d{0,9}\.){0,2}[A-Fa-f0-9]{40}$/;
I changed the method to only parse from the evm address.

2022-03-23 17:00 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  const query = getContractByIdQuery({timestampConditions, columnName: contractId.columnName});
Done.

2022-03-23 18:08 UTC, xin-hedera requested changes

2022-03-23 18:08 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  }
the logic here has some duplication with what's in `ContractService.computeContractIdPartsFromContractIdValue`, also it's making an extra db query to just find the contract id from its create2 evm address.

The cleaner way is we first try to parse it using `EntityId.parse`, assuming it's either in the `shard.realm.num` form or the evm address is encoded from `shard.realm.num`; otherwise and if the address matches the evm adddress regex, we should generate the query necessary to find the contract by its create2 evm address.

2022-03-23 18:08 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +      columnName: Contract.getFullName(Contract.EVM_ADDRESS),
we shouldn't use the `num` part for `evm_address`, should just do `evm_address`

2022-03-23 19:30 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +const deprecatedEvmAddressInputRegex = /^(0x)?[A-Fa-f0-9]{40}$/;
No, they are different, and have different goals.

2022-03-23 19:56 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +  const evmAddress = _.last(address.split('.'));
Done.

2022-03-23 20:09 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  const {filters, contractId: contractIdParam} = await extractContractIdAndFiltersFromValidatedRequest(req);
Removed. Intellij should have told me that. Thanks.

2022-03-23 20:11 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  const {contractId: contractIdParam, filters} = await extractContractIdAndFiltersFromValidatedRequest(req);
Removed.

2022-03-23 20:15 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +    getContractByIdQuery: getContractByIdOrAddressQuery,
Renamed.

2022-03-23 20:19 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +        const contractIdValue = await ContractService.computeContractIdFromString(filter.value);
We are already doing the operator validation. It happens before this code is executed.
I did this lookup here because we talked about it during scrum, and decided that we should support all types of id in the query parameter.
I think it will be a performance problem only if we allow each request to use the contract id parameter more than like 20 times. @steven-sheehy what do you think?

2022-03-23 20:20 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/contractService.js
> +      columnName: Contract.getFullName(Contract.EVM_ADDRESS),
I did it this way, because in multiple places in the code we say that the address can have the: `shard.realm.num` format, and in this case the `num` can have an `evm_address`. I think it is easier for others to understand.

2022-03-23 20:23 UTC, steven-sheehy requested changes
Please also look at the 20 code smells

2022-03-23 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    DeprecatedEvmAddress:
This format is not deprecated, it's just an EVM address without an operator. But it can be deleted with my request to revert change to `from` query param.

2022-03-23 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: "0000000000000000000000000000000000001f41"
Revert change to `EvmAddress`. Instead create a new `EvmAddressShardRealm` for use only in `contractIdPathParam` and `contractIdQueryParam`:

```yaml
    EvmAddressShardRealm:
      type: string
      description: A network entity encoded as an EVM address in hex
      format: binary
      pattern: '^(\d{1,10}\.){0,2}[A-Fa-f0-9]{40}$'
      example: "0000000000000000000000000000000000001f41"
```

Also note your regex was wrong with `{0,9}` should be `{1,10}`.

2022-03-23 20:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
>        minLength: 42
Just noticed this was wrong before, if you can adjust.
```suggestion
      minLength: 40
```

2022-03-23 20:31 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  }
I checked the code you mentioned and it is using `computeContractIdPartsFromContractIdValue`, but they don't look to be doing the same thing. Also, the code is not finding the contract id from its create2 evm address, it is finding the contract itself by the evm address, and only the conditions / params are being made here.

2022-03-23 20:38 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
> +const deprecatedEvmAddressInputRegex = /^(0x)?[A-Fa-f0-9]{40}$/;
why? the ticket expands the evm address format we support so we should be able to have both the create1 evm address with optional `0x` prefix and the new format with optional shard / realm and either a create1 or create2 evm address.  I don't see why they need to be separate.

2022-03-23 20:40 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +      columnName: Contract.getFullName(Contract.EVM_ADDRESS),
i'd say the opposite, the contract id should have shard and realm, with either a num or evm_address, we shouldn't overload num for evm_address.

2022-03-23 20:45 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +        const contractIdValue = await ContractService.computeContractIdFromString(filter.value);
this will be a performance problem at even a single-digit number of such create2 evm addresses in a query. multiple db queries will be more expensive and way less scalable if the same result can get with just one db query.

2022-03-23 21:27 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-01-find-by-create1-evm-address.json
> +  "description": "Find a contract by the its create1 evm address",
Done.

2022-03-23 21:36 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +      pattern: '^(\d{0,9}\.){0,2}[A-Fa-f0-9]{40}$'
I asked about this during scrum and explicitly said what was the format of the output being used. The `0x` is added used by the view model. Do you want me to change the code?

2022-03-23 21:41 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      pattern: '^(\d{0,9}\.){0,2}[A-Fa-f0-9]{40}$'
`^0x[A-Fa-f0-9]{40}$` is always the response format. You shouldn't change code to strip `0x`.

2022-03-23 22:06 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +const deprecatedEvmAddressInputRegex = /^(0x)?[A-Fa-f0-9]{40}$/;
There are places where we want to keep supporting the `0x` and there are places that we don't want to.

2022-03-24 21:55 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/contractService.js
> +      columnName: Contract.getFullName(Contract.EVM_ADDRESS),
Ok. I renamed it.

2022-03-24 21:56 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/EvmAddressOutput'
Done.

2022-03-24 21:56 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +      pattern: '^(\d{0,9}\.){0,2}[A-Fa-f0-9]{40}$'
Done.

2022-03-24 21:57 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: eq:0.1d8bfdc5d46dc4f61d6b6115972536ebe6a8854c
Removed.

2022-03-24 21:57 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/DeprecatedEvmAddress'
Fixed.

2022-03-24 21:57 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +    DeprecatedEvmAddress:
Done.

2022-03-24 21:58 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +      example: "0000000000000000000000000000000000001f41"
Done.

2022-03-24 21:58 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
>        minLength: 42
Done.

2022-03-24 22:36 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +        const contractIdValue = await ContractService.computeContractIdFromString(filter.value);
I think it's fine to be a separate query for mapping address to ID if it allows for reuse of existing code and separations of concern. We should definitely change it to an `IN` clause lookup though in case there are multiple such EVM addresses and avoid looking up N times.

2022-03-25 22:19 UTC, steven-sheehy requested changes

2022-03-25 22:19 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +const computeContractIdPartsFromContractIdValue = (contractId) => {
I think this logic can be combined into `parseFromEvmAddress` so that that method checks for the optional `shard.realm.`. Doing it that way is more OO since you can return an `EntityId` object. We can just add an optional `evmAddress` field to `EntityId`. Then you don't have to check `contractIdParts.hasOwnProperty('create2_evm_address')`, you can just check `entityId.evmAddress` is not nil.

2022-03-25 22:19 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +  isCreate2EvmAddress,
I don't think this needs to be exported

2022-03-25 22:19 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +const isValidDeprecatedEvmAddressInputRegex = (entityId) => {
I think this should be combined into `isValidEvmAddress()` as an optional `shardRealm = false` parameter. Reason is because they both validate evm address and neither are considered deprecated.

2022-03-25 22:19 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +const deprecatedEvmAddressInputRegex = /^(0x)?[A-Fa-f0-9]{40}$/;
It's not deprecated, so suggest alternate naming.

```suggestion
const evmAddressRegex = /^(0x)?[A-Fa-f0-9]{40}$/;
const evmAddressShardRealmRegex = /^(\d{1,10}\.){0,2}[A-Fa-f0-9]{40}$/;
```

2022-03-25 22:19 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +    logger.info(contractIdParam + ' <<<<<<<<<<');
Leftover debug statement?

2022-03-28 15:08 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +const deprecatedEvmAddressInputRegex = /^(0x)?[A-Fa-f0-9]{40}$/;
renamed.

2022-03-28 15:08 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +    logger.info(contractIdParam + ' <<<<<<<<<<');
Removed.

2022-03-28 15:08 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +  isCreate2EvmAddress,
Removed.

2022-03-28 15:19 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +const computeContractIdPartsFromContractIdValue = (contractId) => {
That would require multiple changes into the `parseMemoized` method that depends on the return of `parseFromEvmAddress` to do validations and build the entity id.

2022-03-28 16:20 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +  const {lower, inner, upper, order, limit} = await extractNftMultiUnionQuery(filters, accountId);
revert?

2022-03-28 16:35 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
>      Number.parseInt(hexDigits.slice(8, 24), 16), // realm
looks to be a bug using `Number.parseInt` for realm/num which is 64-bit

2022-03-28 16:47 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
>      Number.parseInt(hexDigits.slice(8, 24), 16), // realm
It was always like that. I did not change this code.

2022-03-28 16:52 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/accountController.js
> +  const {lower, inner, upper, order, limit} = await extractNftMultiUnionQuery(filters, accountId);
Done.

2022-03-28 18:05 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
>      Number.parseInt(hexDigits.slice(8, 24), 16), // realm
right it's a bug and it's been there for quite some time

2022-03-28 18:08 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
>      Number.parseInt(hexDigits.slice(8, 24), 16), // realm
can create a ticket and fix it separately if you prefer

2022-03-28 19:54 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
>      Number.parseInt(hexDigits.slice(8, 24), 16), // realm
No, I can do it.

2022-03-29 16:31 UTC, xin-hedera approved these changes
LGTM

2022-03-29 17:04 UTC, steven-sheehy approved these changes
Making `EntityId` parameter-aware is not very encapsulated. I still think we should have a single `parseEvmAddress()` and `isValidEvmAddress(str, type = (ANY|NO_SHARD_REALM|SHARD_REALM)`. But we can address at some point in the future.

2022-03-29 19:13 UTC, Nana-EC approved these changes

2022-03-30 00:34 UTC, steven-sheehy approved these changes

2022-03-30 01:43 UTC, merged