Crypto Allowance acceptance tests
hashgraph/hedera-mirror-node pull request #3411
Opened 2022-03-17 01:15 UTC by Nana-EC

**Description**:
The current acceptance tests are yet to provide coverage for allowance test cases

- Update `AccountClient`
  -  `approveCryptoAllowance` and `adjustCryptoAllowance` for crypto cases
  -  `getAccountAllowanceApproveTransaction` and `getAccountAllowanceAdjustTransaction` for general scenarios
- Update `AccountFeature` with scenarios to approve and adjust crypto allowance
- Add `MirrorTransferAllowance` base prop for all allowance objects
- Add `MirrorCryptoAllowance` object
- Add `cryptoAllowance.feature` scenarios

**Related issue(s)**:

Fixes #

**Notes for reviewer**:
- Run scenarios against previewnet
- Provides a base for future allowance acceptance tests

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-03-17 19:28 UTC, steven-sheehy requested changes

2022-03-17 19:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        assertThat(timestampRange.getTo()).isBlank();
Use chaining to reduce overall lines of code and to return multiple errors at the same time.

```suggestion
        assertThat(mirrorCryptoAllowanceResponse.getAllowances())
            .isNotEmpty()
            .first()
            .isNotNull()
            .returns(approvedAmount, MirrorCryptoAllowance::getAmount)
            ...
            .extracting(MirrorCryptoAllowance::getTimestamp)
            .isNotNull()
            .satisfies(t -> assertThat(t.getFrom()).isNotBlank())
            .satisfies(t -> assertThat(t.getTo()).isBlank());
```

2022-03-17 19:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                spender,
What's with the weird formatting in this class that puts every parameter on a new line? Should fix.

2022-03-17 19:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    public AccountAllowanceAdjustTransaction getAccountAllowanceAdjustTransaction(Map<AccountId, Hbar> cryptoAllowances,
I don't think we should have these omnibus methods (e.g. `getAccountAllowanceApproveTransaction` and `getAccountAllowanceAdjustTransaction`) that handle all types of allowances. They're not used externally and have a complicated set of parameters that include code smells like use of `Triple`. It actually increases code complexity:

```java
 AccountAllowanceApproveTransaction cryptoAllowanceApproveTransaction = getAccountAllowanceApproveTransaction(
                Map.of(spender, hbarAmount),
                null,
                null);
```

vs

```java
var transaction = new AccountAllowanceAdjustTransaction()
    .addHbarAllowance(spender, hbarAmount);

2022-03-21 16:31 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AccountAllowanceApproveTransaction allowanceApproveTransaction = new AccountAllowanceApproveTransaction();
Ah yes, missed the pom.xml push.
Went to `2.10.0-beta.1` but since then looks like we bumped the whole multi module up to `2.9.0`

2022-03-21 17:01 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    public void transferFromAllowance(String senderAccountName, long amount, String receiverAccountName) {
seems `senderAccountName` is only used in the description not in the code, also the description should clarify this is a transfer using crypto allowance

2022-03-21 17:09 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +                .getAccount(AccountClient.AccountNameEnum.valueOf(accountName));
nit, strange format

2022-03-21 18:11 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AccountAllowanceApproveTransaction allowanceApproveTransaction = new AccountAllowanceApproveTransaction();
2.9.0 works so I can just rebase.

2022-03-21 18:22 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    public AccountAllowanceAdjustTransaction getAccountAllowanceAdjustTransaction(Map<AccountId, Hbar> cryptoAllowances,
Was aiming to support the final test in this sprint where all 3 allowance should be in the Approval or Adjustment.
Will leave it out since Services tests should cover the combination

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        log.debug("Retrieved Account: {}, {} w balance {}", accountId, accountNameEnum, balance);
Done

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                                                                                    List<Triple<TokenId, AccountId,
Fixed

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        AccountAllowanceApproveTransaction allowanceApproveTransaction = new AccountAllowanceApproveTransaction();
Rebased

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        assertThat(nonZeroCount.get()).isZero();
Simplified

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        assertThat(timestampRange.getTo()).isBlank();
Chained

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                spender,
Fixed

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +    public AccountAllowanceAdjustTransaction getAccountAllowanceAdjustTransaction(Map<AccountId, Hbar> cryptoAllowances,
Simplified

2022-03-21 19:40 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        }
Updated, left over from a separate intended flow breakout

2022-03-21 19:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    public void transferFromAllowance(String senderAccountName, long amount, String receiverAccountName) {
Added sender back in.
This should be there to allow people to write different tests

2022-03-21 19:41 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +                .getAccount(AccountClient.AccountNameEnum.valueOf(accountName));
Fixed

2022-03-22 01:42 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        log.debug("Retrieved Account: {}, {} w balance {}", accountId, accountNameEnum, balance);
Not done

2022-03-22 03:21 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        assertThat(mirrorCryptoAllowanceResponse.getAllowances())
```suggestion
        assertThat(mirrorCryptoAllowanceResponse.getAllowances())
```

2022-03-22 20:45 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        assertThat(mirrorCryptoAllowanceResponse.getAllowances())
Fixed

2022-03-22 20:45 UTC, Nana-EC commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                spender,
Fixed

2022-03-22 21:47 UTC, steven-sheehy approved these changes
LGTM

2022-03-23 17:32 UTC, xin-hedera approved these changes
LGTM

2022-03-23 20:27 UTC, merged