Container security improvements
hashgraph/hedera-mirror-node pull request #3432
Opened 2022-03-22 16:45 UTC by steven-sheehy

**Description**:
* Bump chart dependencies
* Bump Go to 1.18
* Change charts to conform to Kubernetes [restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) pod security standard
* Change docker images to set a user and group so it doesn't run as root in docker-compose
* Fix `MonitorPublishStopped` & `MonitorSubscribeStopped` not alerting when rate dropped to zero
* Fix jib warning `does not use a specific image digest - build may not be reproducible`
* Remove unused and brittle `rest.test.checkRecent` chart test

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-03-22 16:47 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> -      pspEnabled: false
Pod security policies have been deprecated by Kubernetes and removed from upstream charts. They are being replaced by [pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards).

2022-03-22 16:50 UTC, steven-sheehy commented on charts/hedera-mirror-monitor/values.yaml
> +    expr: (sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_sum{application="hedera-mirror-monitor"}[2m])) by (namespace, pod, subscriber, scenario) / sum(rate(hedera_mirror_monitor_subscribe_e2e
When the denominator drops to zero, Prometheus returns `NaN` which is not comparable with `<= 0`. To workaround, we return a zero vector for `NaN` using ` > 0 or on() vector(0)`.

2022-03-22 17:39 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +    tag: 13.6.0-debian-10-r37
PostgreSQL 14 doesn't work with `postgresql-ha` chart yet.

2022-03-23 14:29 UTC, Nana-EC approved these changes
LGTM

2022-03-23 16:28 UTC, xin-hedera requested changes

2022-03-23 16:39 UTC, steven-sheehy commented on hedera-mirror-rosetta/pom.xml
> +                    <goVersion>1.18</goVersion>
Bumped

2022-03-23 17:03 UTC, xin-hedera approved these changes

2022-03-23 19:18 UTC, Nana-EC approved these changes
LGTM

2022-03-23 20:25 UTC, merged