Support missing precompile contract function parameter details
hashgraph/hedera-mirror-node pull request #3473
Opened 2022-03-28 23:50 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
Initially the `ContractFunctionResult` was missing the `Amount`, `GasLimit` and `FunctionParameters` details  for precompile transactions.
In the v0.25.0 protobuf version these params were added 

- Updated the `ContractCreate` and `ContractCall` transaction handlers `updatedCOntractResult` to update if the `Amount`, `GasLimit` and `FunctionParameters` are not set
- Update the `ContractServiceImpl` logic to set the `Amount`, `GasLimit` and `FunctionParameters` values

**Related issue(s)**:

Fixes #3427 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-03-31 15:07 UTC, steven-sheehy commented
Need to change default of precompile property

2022-03-31 18:14 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                entityIdService.lookup(functionResult.getContractID());
No, cause we had all parsing of precompile cases turned off.
This PR is supposed to enable that.

Removing that feature flag logic also

2022-03-31 18:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setFunctionParameters(DomainUtils.toBytes(functionResult.getFunctionParameters()));
Updated to set only if Create/Call.
Actually prefer the new location, reads better since it's doing an update.
You create and set the `ContractResult` and then where applicable you update it

2022-03-31 18:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (contractResult.getAmount() == null) {
Right. Will revert transaction handler items

2022-04-01 01:03 UTC, steven-sheehy requested changes

2022-04-01 01:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setFunctionParameters(DomainUtils.toBytes(functionResult.getFunctionParameters()));
IF there's cause for concern I'll move it back to how I originally had it

2022-04-01 01:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoAdjustAllowanceTransactionHandler.java
> +        return recordItem.getTransactionBody().getCryptoAdjustAllowance().getNftAllowancesList();
Yeah, it got removed from the record, so transactionBody seemed to be the available location for retrieval

2022-04-01 14:29 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> -            if (!entityProperties.getPersist().isContractResults()) {
Will revert and set to true.
The test I re-enabled were the new added tests for coverage.
Should be fine

2022-04-01 15:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> -                // feature gate precompile scenarios for now. When complete feature gate all contractResults together
Will reorder and have the check after child creation

2022-04-01 18:08 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setFunctionParameters(DomainUtils.toBytes(functionResult.getFunctionParameters()));
Moved back

2022-04-01 20:02 UTC, steven-sheehy requested changes

2022-04-01 20:15 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                        .setFunctionParameters(functionParameters)));
Had this in before the extra check in `ContractResultsServiceImpl`.
With that sorted no longer needed in here.

2022-04-01 20:15 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                        .setFunctionParameters(functionParameters)));
Reverted

2022-04-01 20:15 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean contractResults = true;
Updated

2022-04-01 20:29 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-04-04 20:50 UTC, xin-hedera approved these changes
LGTM. just a nit, can leave it.

2022-04-04 20:50 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        }
nit, move the check up to the beginning of the function

2022-04-05 18:35 UTC, steven-sheehy approved these changes

2022-04-05 18:37 UTC, xin-hedera approved these changes

2022-04-05 18:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        }
got it

2022-04-05 18:43 UTC, merged