Fix REST API contracts bytecode double 0x prefix
hashgraph/hedera-mirror-node pull request #3487
Opened 2022-03-31 19:46 UTC by ewlghedera

**Description**:
This fixes the double 0x prefix that can be returned for the contracts bytecode.

**Related issue(s)**:

Fixes #3486 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-01 20:06 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/utils.test.js
> +  });
This test is replicated (with one additional test case to handle 0x) from the work for 3442 here: 
https://github.com/hashgraph/hedera-mirror-node/pull/3442/files#diff-1cfbb0d321938673fb2a3226d2fb2ec4905794e68d4c09aff51fd1b7de2e749a

2022-04-01 20:26 UTC, steven-sheehy requested changes

2022-04-01 20:26 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  hexString = `${hexString}`;
Shouldn't reassign method parameters in the method body. Here, maybe it's better to rename the method parameter since it might not be string.

```suggestion
  const hexString = `${hexData}`;
```

2022-04-01 20:26 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
`substring()` allocates a new string. Instead we should use `hexString.startsWith(hexPrefix)` to avoid the unnecessary allocation.

2022-04-01 20:26 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +        expected: '0x4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f',
We should also test with `Buffer` as input

2022-04-01 20:26 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-17-contract-bytecode.spec.json
> +        "file_data": "00160a01b0381168114607557600080fd5b9392505050565b603f8060896000396000f3fe6080604052600080fdfea2646970667358221220cef90c1de1bfe76c35095b7f0d6a94d1ca71f144f8da70eb9816329ab76eda35
As we're not testing to ensure multiple file_data get concatenated together in this scenario, we can delete all `file_data` in list but one.

2022-04-01 20:26 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-17-contract-bytecode.spec.json
> +        "file_data": "0x6080604052348015600f57600080fd5b5060405160c838038060c8833981016040819052602a91604e565b600080546001600160a01b0319166001600160a01b0392909216919091179055607c565b60006020828403121
I'm not sure if the test framework is stripping the `0x` `Buffer.from()`. We should probably use the binary array form of input to ensure the actual `0x` gets saved in the db.

2022-04-01 21:42 UTC, Nana-EC requested changes
Use `indexOf` instead as I believe it's more performant

2022-04-01 21:42 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
Actually in benchmarking i think the best candidate here would be `indexOf`
```suggestion
  return str.indexOf(hexPrefix) === 0 ? hexString : `${hexPrefix}${hexString}`;
```

2022-04-01 22:01 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
I don't see any benchmarks with proof of that. Even if there were a difference it would be so minute that it's not worth sacrificing the readability of using `startsWith`.

2022-04-03 17:10 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
Did a benchmark on measurethat.net/Benchmarks, `indexOf` is almost twice as fast as substring.
Not sure how it substantially reads worse. Also that can be addressed with a comment.

With high contract result usage expected with more Smart Contract scenarios as well as Staking in the future this function will see more traction.
I'd still advise we go with `indexOf`

2022-04-03 18:07 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
> `indexOf` is almost twice as fast as substring.

Umm, but that wasn't the debate. It was `indexOf` vs `startsWith`.

2022-04-04 16:16 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
`StartsWith` is a little better than `Regex` but worse than `substring`
From the bench mark i tried `indexOf` is roughly an order of magnitude faster than `startsWith`
[js-regex-vs-startswith-vs-indexof-vs-endswith-vs-charat](https://www.measurethat.net/Benchmarks/Show/12312/0/js-regex-vs-startswith-vs-indexof-vs-endswith-vs-charat)

2022-04-05 17:55 UTC, ewlghedera commented on hedera-mirror-rest/utils.js
> +  hexString = `${hexString}`;
This is now changed so as not to reassign the parameter variable.

2022-04-05 17:57 UTC, ewlghedera commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
This is now changed to the suggestion to use `indexOf` as it may have a performance benefit over `startsWith`. I can change it to `startsWith` if we want, either way seems good.

2022-04-05 17:57 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/utils.test.js
> +        expected: '0x4a5ad514f0957fa170a676210c9bdbddf3bc9519702cf915fa6767a40463b96f',
I have added some `Buffer` tests.

2022-04-05 17:58 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/contracts-17-contract-bytecode.spec.json
> +        "file_data": "00160a01b0381168114607557600080fd5b9392505050565b603f8060896000396000f3fe6080604052600080fdfea2646970667358221220cef90c1de1bfe76c35095b7f0d6a94d1ca71f144f8da70eb9816329ab76eda35
I have removed the unnecessary `file_data`.

2022-04-05 17:59 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/contracts-17-contract-bytecode.spec.json
> +        "file_data": "0x6080604052348015600f57600080fd5b5060405160c838038060c8833981016040819052602a91604e565b600080546001600160a01b0319166001600160a01b0392909216919091179055607c565b60006020828403121
I have changed the test to use `file_data` with the value `[48, 120, 97, 98]`

2022-04-05 17:59 UTC, ewlghedera commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
I have updated it to use `indexOf`.

2022-04-05 19:11 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
a bit late... it looks to me `indexOf` definitely has perf penalty on large strings without `0x` at all. 

also the benchmark linked is run on browser, we use nodejs, the numbers can be completely different.

2022-04-05 19:36 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
I ran a different benchmark locally that I customized based upon a [gist](https://gist.github.com/tabarra/d03dbcb78ce5db4c1cf02b659be688bb). It does show that `indexOf` is a lot faster than `startsWith`. For whatever reason, nodejs or v8's implementation of `startsWith` is not optimal as one would expect. But it also shows that `substring` is faster than `indexOf`. 😆  I say it's fine as `indexOf`.

```
$ node startswith.js
indexOf x 931,496,738 ops/sec ±0.92% (95 runs sampled)
startsWith x 76,676,989 ops/sec ±0.45% (94 runs sampled)
lastIndexOf x 40,956,896 ops/sec ±0.91% (94 runs sampled)
substring x 938,148,086 ops/sec ±0.52% (96 runs sampled)
slice x 930,841,502 ops/sec ±0.87% (94 runs sampled)
regex x 48,709,553 ops/sec ±1.28% (93 runs sampled)
compiled regex x 59,707,114 ops/sec ±0.27% (98 runs sampled)
>Fastest is substring,indexOf,slice
```

2022-04-05 19:40 UTC, steven-sheehy approved these changes
LGTM

2022-04-05 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
Haha, you edited your comment later with almost the same comment as me using the same benchmark.

2022-04-05 19:43 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
Haha wow. Let's go with the performant option for our code base.
I'm fine with `substring` in that case :)

2022-04-05 19:46 UTC, xin-hedera approved these changes
LGTM

2022-04-05 19:47 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  return hexString.substring(0, 2) === hexPrefix ? hexString : `${hexPrefix}${hexString}`;
It's okay as is. We'll cross any performance issues later and we got a good discussion going.

2022-04-05 19:47 UTC, Nana-EC approved these changes
LGTM

2022-04-05 19:57 UTC, merged