Track NFT allowances at transfer granularity
hashgraph/hedera-mirror-node pull request #3529
Opened 2022-04-06 17:44 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #3445

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-04-06 22:10 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                Arguments.of("no assessed custom fees", Collections.emptyList(), Collections.emptyList()),
`Lists.emptyList` is deprecated

2022-04-08 23:13 UTC, steven-sheehy requested changes

2022-04-08 23:13 UTC, steven-sheehy commented on docs/design/allowances.md
> +      "serial_number": 2,
I'm wondering if it's better to show serial information on the existing nft APIs and keep this as just for approved for all? We can perhaps add a `spender` parameter to nft APIs and response.

2022-04-08 23:13 UTC, steven-sheehy commented on docs/design/allowances.md
> +* `approval.type`: Filter by the nft allowance approval type. Accepts `approved_for_all` or `serialnumber` with a
I'm not a fan of this parameter. Perhaps we can support a `serialnumber=null` to show the same?

2022-04-11 15:14 UTC, xin-hedera commented on docs/design/allowances.md
> +      "serial_number": 2,
yup. that's another approach. the pros is we don't have to add the `approval.type` filter or use `serialnumber=null`. The cons is it's a bit inconsistent w/ the other two allowance rest APIs. btw, it should be the `/:accountIdOrAlias/nfts` endpoint, not the `/tokens/:tokenId/nfts` since the latter is limited to a specific nft token class. p.s., we don't need an `owner` parameter since it's in the path.

2022-04-11 16:26 UTC, xin-hedera commented on docs/design/allowances.md
> +      "serial_number": 2,
update: services will also wipe allowance in case of a normal nft trasnfer: https://github.com/hashgraph/hedera-services/issues/3167

2022-04-11 16:27 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/NftUpsertQueryGeneratorTest.java
> +                "delegating_spender = nft_temp.delegating_spender, " +
update: services will also wipe / revoke allowance in case of a normal nft trasnfer: https://github.com/hashgraph/hedera-services/issues/3167

2022-04-11 19:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    allowance_granted_timestamp bigint default null,
updated `csvRestoreTables.sql`

2022-04-11 19:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.57.0__update_nft_allowance.sql
> +create index if not exists nft__allowance on nft (account_id, spender, token_id, serial_number)
updated the doc

2022-04-11 19:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityListener.java
> +        onNft(nft);
removed

2022-04-11 19:34 UTC, xin-hedera commented on docs/design/allowances.md
> +      "serial_number": 2,
updated design doc

2022-04-11 19:39 UTC, xin-hedera commented on docs/design/allowances.md
> +  and `serial_number`. Accepts `asc` or `desc` with a default of `desc`.
the default for `/accounts/:accountIdOrAlias/nfts` is `desc`, just want to keep it the same. downside is it's different than crypto and fungible token allowances REST api.

2022-04-11 20:19 UTC, matheus-dallrosa commented on docs/design/allowances.md
> +create index if not exists nft__allowance on nft (account_id, spender, token_id, serial_number)
Why you are using two underscores in `nft__allowance` ?

2022-04-11 20:33 UTC, matheus-dallrosa commented on docs/design/allowances.md
> +      "account_id": "0.0.1000",
Can't we just group allowance related fields into an `allowance` object?

2022-04-11 20:45 UTC, Nana-EC commented on docs/design/allowances.md
> +  and `serial_number`. Accepts `asc` or `desc` with a default of `desc`.
Should we make a point to standardize to `desc` for all.
Can always create a ticket to address later.

2022-04-11 21:08 UTC, xin-hedera commented on docs/design/allowances.md
> +create index if not exists nft__allowance on nft (account_id, spender, token_id, serial_number)
it's just our de facto index naming standard.

2022-04-11 21:10 UTC, Nana-EC approved these changes
LG

2022-04-11 21:10 UTC, xin-hedera commented on docs/design/allowances.md
> +      "account_id": "0.0.1000",
yup we can. perhaps it's better to group them. however, iirc, we've never done it for other view models.

2022-04-11 21:26 UTC, matheus-dallrosa commented on docs/design/allowances.md
> +      "account_id": "0.0.1000",
Yes, I think we have nesting only when one of the fields is a list.

2022-04-11 22:50 UTC, steven-sheehy commented on docs/design/allowances.md
> +* `order`: Order by `spender`, `toke_id`, and `serial_number` if `spender.id` is specified, otherwise order by `token_id`
```suggestion
* `order`: Order by `spender`, `token_id`, and `serial_number` if `spender.id` is specified, otherwise order by `token_id`
```

2022-04-11 22:50 UTC, steven-sheehy commented on docs/design/allowances.md
> +* `order`: Order by `spender`, `toke_id`, and `serial_number` if `spender.id` is specified, otherwise order by `token_id`
The sort order should only be for the unique keys used for pagination. So I think order would stay as token_id and serial_number.

2022-04-12 15:40 UTC, merged