Add is_approval to transfer responses
hashgraph/hedera-mirror-node pull request #3537
Opened 2022-04-07 14:02 UTC by ewlghedera

**Description**:
HIP-336 added `is_approval` to transfers. This PR adds the `is_approval` field to the REST API. 

`is_approval` will now be returned with these responses:

- CryptoTransfers
- NftTransfers
- TokenTransfers 

**Related issue(s)**:

Fixes #3444

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-12 19:46 UTC, steven-sheehy commented on docs/design/allowances.md
> +###Accounts Endpoint
Need a space after hashes

2022-04-12 19:46 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/nftTransferViewModel.js
> +    this.is_approval = _.isNil(nftTransferModel.isApproval) ? false : nftTransferModel.isApproval;
We should put the new field in sorted order. Here and other models. If the fields are not already sorted you don't have to correct it, just put it as sorted as you can.

2022-04-12 19:46 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  is_approval:
Sort field in this file as well

2022-04-12 21:39 UTC, Nana-EC requested changes
Some suggestions.
Namely defaulting to `false` should reduce a lot of changes

2022-04-12 21:39 UTC, Nana-EC commented on docs/design/allowances.md
> +  "transactions": [
This sample response is missing a field, I think it's `assessed_custom_fees`.
See the `TransactionDetails` object in the `openapi.yml` file.
Also sort the parameter order

2022-04-12 21:39 UTC, Nana-EC commented on docs/design/allowances.md
> +  "account": "0.1.2",
nit: You're missing other items in the response.
Maybe you could highlight the change by using `...` in all the non changed parts

2022-04-12 21:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integration.test.js
> +      {account: '0.15.8', amount: -31, is_approval: true},
I think the default in this file should be `false` with spec files updating the field when they need it set to true for allowance cases

2022-04-12 21:39 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-01-no-args.spec.json
> +        "is_approval": false
Note, you only need to specify the param where it's overriding the default value from `domainOps`.
I'd go with `false` as the default and in this file where you set `"is_approval": true` would be the valid additions

2022-04-13 14:51 UTC, xin-hedera requested changes

2022-04-13 14:51 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +      [consensusTimestamp.toString(), -(NODE_FEE + NETWORK_FEE), payerAccountId, payerAccountId, true]
these transfers should have `is_approval = false`. they are fee debit from the transaction payer and fee credit to the node and the fee collector account of the network. they can never be approved transfers.

2022-04-13 14:51 UTC, xin-hedera commented on hedera-mirror-rest/model/cryptoTransfer.js
> +    this.isApproval = cryptoTransfer.isApproval;
```suggestion
    this.isApproval = cryptoTransfer.is_approval;
```

2022-04-13 17:43 UTC, ewlghedera commented on docs/design/allowances.md
> +  "account": "0.1.2",
Thanks. I think I've added all the other items now.

2022-04-13 17:45 UTC, ewlghedera commented on docs/design/allowances.md
> +  "transactions": [
I've added `assessed_custom_fees` and I've sorted the order of `is_approved` is some places. I was wondering if token_id take precedence since it was already the first item:

```
        {
          "token_id": "0.0.90000",
          "account": "0.0.9",
          "amount": 1200,
          "is_approval": true
        }
```

2022-04-13 17:52 UTC, ewlghedera commented on docs/design/allowances.md
> +###Accounts Endpoint
Thanks, I've added the spaces.

2022-04-13 17:57 UTC, ewlghedera commented on hedera-mirror-rest/viewmodel/nftTransferViewModel.js
> +    this.is_approval = _.isNil(nftTransferModel.isApproval) ? false : nftTransferModel.isApproval;
Thanks I've updated the ordering in the models and viewmodels.

2022-04-13 17:58 UTC, ewlghedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  is_approval:
Got it I've updated the ordering in the openapi.

2022-04-13 17:59 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-01-no-args.spec.json
> +        "is_approval": false
Got it I've switched it to false.

2022-04-13 17:59 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +      [consensusTimestamp.toString(), -(NODE_FEE + NETWORK_FEE), payerAccountId, payerAccountId, true]
Great ok, I have fixed these to false.

2022-04-13 18:00 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +      {account: cryptoTransfer.treasuryAccountId, amount: NETWORK_FEE, is_approval: true},
I've switched them to false.

2022-04-13 18:00 UTC, ewlghedera commented on hedera-mirror-rest/model/cryptoTransfer.js
> +    this.isApproval = cryptoTransfer.isApproval;
Great find! Fixed.

2022-04-13 18:50 UTC, ewlghedera commented on docs/design/allowances.md
> +  "transactions": [
Great ok, I've changed the ordering in those cases as well.

2022-04-13 19:28 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/tokens-nft-history-01-no-args.spec.json
> +        "is_approval": false
I thought I removed all of the `false` settings from the `setup` section of the spec files. The remaining ones should be the ones in the `responseJson` section. When I remove them from the `responseJson` section the tests fail, but maybe there is a way to make it ignore the extra field there?

2022-04-13 19:31 UTC, Nana-EC approved these changes
Approving to dismiss my hold.
Agree with remaining requests from other reviewers

2022-04-13 19:31 UTC, steven-sheehy approved these changes
LGTM

2022-04-13 20:57 UTC, xin-hedera approved these changes
LGTM

2022-04-13 21:24 UTC, merged