03446 fix is approval value from transactions
hashgraph/hedera-mirror-node pull request #3563
Opened 2022-04-11 16:44 UTC by matheus-dallrosa

**Description**:
The new `is_approval` flag on transfers is not being populated correctly. The flag is always being populating from the record transfer list (besides `non_fee_transfer`), but these entries will always have `is_approval` set to false.
This PR fixes the value for the `is_approval` flag value in the NFT, token, and crypto transfers.

**Related issue(s)**:
https://github.com/hashgraph/hedera-mirror-node/issues/3446

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-11 22:26 UTC, Nana-EC requested changes
Some nits and readability suggestions

2022-04-11 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if(accountAmount.getAmount() < 0){
nit: add comments to make clear the conditional pathways you're building here

2022-04-11 22:26 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            tokenTransferList.getTransfersList().forEach(accountAmount -> {
nit: since you're somewhat rearranging anyway might be worth breaking this large method out i.e an `insertFungibleTokenTransfer(...)` and `insertNonFungibleTokenTransfers(...)`
Should help readability

2022-04-12 14:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            return ;
Done.

2022-04-12 14:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            EntityId tokenId = EntityId.of(tokenTransferList.getToken());
Done.

2022-04-12 14:22 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if(accountAmount.getAmount() < 0){
I added a comment above all ifs explaining what are the rules, and also added a comment to explain what each query is about.

2022-04-12 17:18 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    }
I thought about the performance in this case. We are already doing a search inside the body for a particular crypto transaction to decide the errata value to be set, and this is the reason why I followed the same approach.

2022-04-13 14:23 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        return body.getCryptoTransfer()
Done.

2022-04-13 14:23 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if(isAccountAmountInsideBody.isPresent()){
Done.

2022-04-13 14:23 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            this.insertFungibleTokenTransfers(
Done.

2022-04-13 14:38 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    }
Please, see https://github.com/hashgraph/hedera-mirror-node/pull/3563#discussion_r847837841

2022-04-13 19:04 UTC, Nana-EC reviewed
My initial feedback was addressed, was waiting on feedback from other to be addressed.
Commenting so as to remove my block

2022-04-13 19:31 UTC, Nana-EC approved these changes
Approving to dismiss my hold.
Agree with remaining requests from other reviewers

2022-04-13 19:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                .stream()
I don't think it's worth the complexity or extra memory at this time. Let's measure it at 15K and see how it performs then optimize. We could also later optimize to just insert is_approval=true in the hash map and default to false if not found. We can open a ticket to address in a follow up if we think it's worthwhile to purse.

2022-04-13 21:15 UTC, xin-hedera requested changes

2022-04-13 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            tokenTransfer.setIsApproval(accountAmount.getIsApproval());
```suggestion
            tokenTransfer.setIsApproval(false);
```

2022-04-13 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmountInsideTransferList == null) {
`accountAmountInsideTransferList` is ignored if it's not null

2022-04-13 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (nftTransferInsideBody != null){
nit
```suggestion
            if (nftTransferInsideBody != null) {
```

2022-04-13 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            AccountAmount accountAmountInsideBody = findAccountAmountInTransferListInsideBody(aa, body);
should only search `AccountAmount` from transaction record with `amount < 0`

2022-04-13 21:55 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmountInsideTransferList == null) {
Yes, I did that to reuse the `findAccountAmountInTokenTransferListInsideBody` method.

2022-04-13 22:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (nftTransferInsideBody != null){
Done.

2022-04-13 22:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            AccountAmount accountAmountInsideBody = findAccountAmountInTransferListInsideBody(aa, body);
You're right. Done.

2022-04-13 22:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmountInsideTransferList == null) {
If there’s an exact match and it’s an approved transfer you should set approved to true, right?

2022-04-13 22:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            tokenTransfer.setIsApproval(accountAmount.getIsApproval());
Done.

2022-04-14 17:13 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            tokenTransfer.setIsApproval(accountAmount.getIsApproval());
Done.

2022-04-14 17:27 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmountInsideTransferList == null) {
No, is there is not an exact match i.e `accountAmountInsideTransferList` is `null`, and there is an account amount inside the body with the same account id as the account amount inside the record. I thought about doing both in one search, but later if they change something in the grouping and there is more than one account amount for a given account id, the code would break.

2022-04-14 19:01 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmountInsideTransferList == null) {
You're right. I added the normal case to the fungible token transfers, and covered it in the unit test.

2022-04-14 20:20 UTC, xin-hedera requested changes

2022-04-14 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                }
It doesn't make sense for some account's transfer in tx body but not in a successful transaction's record.

2022-04-14 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        TransactionRecord record = buildTransactionRecord(r -> {
`buildTransactionRecord` will copy the crypto transfers in the tx body to the record if the tx is `CryptoTransferTransaction`. So the transaction record built here ends up with duplicate crypto transfers, for example, for account `6`, there will be two entries of `credit 210 to account 6`.

2022-04-14 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .addTransfers(AccountAmount.newBuilder().setAccountID(PAYER2).setAmount(-100).setIsApproval(true).build())
these go into the transaction record so shouldn't set `is_approval = true`

2022-04-14 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +    @MethodSource("nftTransfersHaveCorrectIsApprovalValueArgumentProvider")
don't need a parameterized test, with nft1 transfer `approved = true` and nft2 transfer `approved = false` should suffice.

2022-04-14 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +            builder.addAllTokenTransferLists(List.of(transferList1, transferList2));
the transfers in transaction record should always have `is_approval = false`

2022-04-14 22:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +            builder.addAllTokenTransferLists(List.of(transferList1, transferList2));
Yes, I had left it this way to not have to build more transfers and lists, but I did the change. Done.

2022-04-14 22:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +    @MethodSource("nftTransfersHaveCorrectIsApprovalValueArgumentProvider")
I would like to leave it like that, because I think with all the combinations we are testing the for loop iteration.

2022-04-14 22:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .addTransfers(AccountAmount.newBuilder().setAccountID(PAYER2).setAmount(-100).setIsApproval(true).build())
Yes, removed.

2022-04-14 22:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        TransactionRecord record = buildTransactionRecord(r -> {
Yes, but it would not remove the correctness of the test. The tokens transfers were fixed, I did not check the crypto ones. I removed the duplication of the crypto transfers.

2022-04-14 22:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                }
Fixed.

2022-04-14 22:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        final long[] accountNums = {6,7,8};
Ok, I used the ones from constants.

2022-04-14 22:38 UTC, steven-sheehy requested changes

2022-04-14 22:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (accountAmount.getAmount() < 0) {
```suggestion
            if (amount < 0) {
```

2022-04-14 22:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                    aa -> aa.getAccountID().equals(accountAmount.getAccountID()) && aa.getIsApproval(),
Declare as a private method so you can use a method reference instead of allocating a lambda every invocation.

2022-04-14 22:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                    tokenId, body);
Perhaps shorten these method and variable names so one line doesn't take up 4. Can use overloaded `findAccountAmount` for both. Can do the same in some other places.

```suggestion
                    AccountAmount accountAmountBody = findAccountAmount(this::isApprovedAccountAmount, tokenId, body);
```

2022-04-14 22:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    findNftTransferInsideBody(nftTransfer, tokenId, body);
Use var to hide the explicit import here and elsewhere.
```suggestion
            var nftTransferInsideBody = findNftTransferInsideBody(nftTransfer, tokenId, body);
```

2022-04-18 13:33 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                    aa -> aa.getAccountID().equals(accountAmount.getAccountID()) && aa.getIsApproval(),
The private method would not have access to the `accountAmount` reference.

2022-04-18 14:03 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (accountAmount.getAmount() < 0) {
Done.

2022-04-18 14:03 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                    tokenId, body);
Done.

2022-04-18 14:03 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    findNftTransferInsideBody(nftTransfer, tokenId, body);
Done.

2022-04-18 19:02 UTC, xin-hedera approved these changes
LGTM

2022-04-18 19:29 UTC, steven-sheehy approved these changes
LGTM

2022-04-18 19:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                    aa -> aa.getAccountID().equals(accountAmount.getAccountID()) && aa.getIsApproval(),
Yeah, you can use `BiPredicate<AccountAmount, AccountAmount>` and pass the account amount to `findAccountAmount`. But we can also consider in a follow up.

2022-04-18 20:46 UTC, Nana-EC approved these changes
LGTM

2022-04-18 21:05 UTC, merged