Support CryptoDeleteAllowance transaction
hashgraph/hedera-mirror-node pull request #3571
Opened 2022-04-13 14:31 UTC by xin-hedera

**Description**:

This PR adds support of CryptoDeleteAllowance transaction.

- Support CryptoDeleteAllowance transaction
- Drop `allowance_granted_timestamp` from `nft` table and set `modified_timestamp` for allowance change
- Switch non fee transfer and CryptoApproveAllowance transaction handling to using `entityIdService`
- Fix minor issue in design doc

**Related issue(s)**:

Fixes #3431 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-13 15:41 UTC, steven-sheehy commented on hedera-mirror-rest/model/transactionType.js
> +  49: 'CRYPTODELETEALLOWANCE',
Need to also update openapi.yml

2022-04-13 15:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractAllowanceTransactionHandler.java
> +abstract class AbstractAllowanceTransactionHandler implements TransactionHandler {
I don't think this class provides enough value to be warranted. Especially since we don't even need `getOwnerAccountId` if we use the `EntityIdService` instead, which I think we should use. Better to start using `EntityIdService` now for new work to reduce the work later for alias for all transaction types.

2022-04-13 15:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setAccountId(ownerAccountId);
We should probably rename `allowanceGrantedTimestamp` to `allowanceTimestamp` so it can capture both grants and revokes.

2022-04-13 17:08 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setAccountId(ownerAccountId);
the end result should be the same since from the services code snippet, ownership of the nft is verified before clearing spender.

since the owner of the nft in db is the same as the owner set here, setting it or not will not cause ownership change.

2022-04-13 17:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setAccountId(ownerAccountId);
Regardless, no point in setting it if it's not changing then. We still need to clear the spender and update the timestamp.

2022-04-13 17:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setAccountId(ownerAccountId);
Actually, I'm in favor of dropping `allowanceGrantedTimestamp` altogether and just using `modifiedTimestamp` for everything.

2022-04-13 18:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setAccountId(ownerAccountId);
not setting `Nft.accountId` actually makes it easier if we want to switch to `EntityIdService` since for CryptoDeleteAllowance we no longer need it. I'll still change `CryptoApproveAllowance` to use `EntityIdService` as well as the non fee transfer handling in `EntityRecordItemListener`

2022-04-13 21:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setAccountId(ownerAccountId);
`modifiedTimestamp` is simpler to maintain than `allowanceTimestamp`, so prefer it too.

2022-04-14 20:02 UTC, steven-sheehy approved these changes
LGTM

2022-04-14 20:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +        }
This code is starting to repeat from other areas. We need to re-think this in the future and perhaps push it into the `EntityIdService`. I think we should make those partial data actions apply to the transaction as a whole and not elements within it as it would become much simpler to implement. Then `DEFAULT` returns `EntityId.EMPTY`, `ERROR` throws an exception and `SKIP` throws an exception that causes the transaction to be skipped. We can revisit this later though.

2022-04-14 20:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +        }
it's needed. `lookup` returns `EntityId.EMPTY` when either it's the default instance or alias lookup failed.

we have to treat the two cases differently here:

1. `owner` is the default instance, i.e., not set, fallback to payer
2. alias lookup failed, partial data action

2022-04-14 20:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +        }
agree.

2022-04-14 22:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +        }
> EntityId.EMPTY when either it's the default instance or alias lookup failed

This is true.

> we have to treat the two cases differently here:

This part is not true. In fact, now that I look at this again we have to do my suggestion since payer account can have alias and is not even going through `EntityIdService`.

2022-04-18 20:36 UTC, Nana-EC requested changes
Looking good, question and a suggestion.
Also observing discussion on `getOwnerAccountId()`

2022-04-18 20:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setModifiedTimestamp(recordItem.getConsensusTimestamp());
Should we be clearing `delegating_spender` and  `spender` here also?

2022-04-18 20:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +            if (ownerAccountId == EntityId.EMPTY) {
nit: please add comment as to significance of empty `ownerAccountId` and why it warrants a skip instead of a default value

2022-04-18 20:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +                nft.setModifiedTimestamp(recordItem.getConsensusTimestamp());
they are not set = being cleared

2022-04-18 20:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +            if (ownerAccountId == EntityId.EMPTY) {
added comment

2022-04-18 20:49 UTC, Nana-EC approved these changes
LGTM

2022-04-18 20:50 UTC, steven-sheehy approved these changes

2022-04-18 21:52 UTC, merged