Parse long term scheduled transactions
hashgraph/hedera-mirror-node pull request #3616
Opened 2022-04-19 22:13 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #3590 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-20 21:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/template/upsert.vm
>  do update set $updateColumns
due to the limit of citus that the outer part of a outer join with distributed table can't be complex subqueries / CTEs / local tables, had to resort to use a inner join to get `existing` and then do `schedule_temp` left outer join `existing`

2022-04-21 00:09 UTC, Nana-EC reviewed
LG on first pass.
Will circle back for template and tests

2022-04-21 17:44 UTC, steven-sheehy requested changes

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGeneratorFactory.java
> +            updatable = historyTable ? (column == null || column.updatable()) : (column != null && column.updatable());
I don't think history vs non-history should behave any differently. This is counter to how these JPA annotations work. `@Column` is an optional annotation that if not present should behave as though it is implicitly present with defaults.

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/schedule/Schedule.java
> +    @Column
Remove as per previous comment. You might need to add `@Column(updatable = false)` to some other columns.

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/schedule/Schedule.java
> +    private boolean waitForExpiry;
Should this be `Boolean` so it doesn't get accidentally set to false for schedule execute? Or doesn't matter due to updatable flags?

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGeneratorFactory.java
> +            upsertColumns.add(createUpsertColumn(schema, attribute, upsertable.history(), id));
Probably better to pass the `Upsertable` annotation as a whole to better support future enhancements.

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/GenericUpsertQueryGenerator.java
> +                upsertEntity.column(c -> !c.isNullable() && !c.isId(), "coalesce(t.{0}, e.{0})"));
I imagine in the future we could have multiple not nullable columns. It might be good to use `columns()` instead here.

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                        .addAccountAmounts(AccountAmount.newBuilder().setAccountID(accountId()).setAmount(100)));
nit: Maybe create a standalone `cryptoTransfer()` that you can reuse here.

2022-04-21 17:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/template/upsert.vm
> +where $notNullableColumn is not null
Move `is not null` into `GenericUpsertQueryGenerator` so you can support multiple nullable columns.

2022-04-21 18:50 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/schedule/Schedule.java
> +    private boolean waitForExpiry;
right it doesn't matter since it's not updatable and the value then is ignored on schedule execute

the upsert sql may create the impression that it can be overridden due to the coalesce. however, for a full mirrornode, the insert will cause an conflict and we end up with the update part which only sets executed_timestamp. For a partial mirrornode which doesn't have the schedule row, no data will be written to the table.

2022-04-21 19:37 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/schedule/Schedule.java
> +    @Column
removed

2022-04-21 19:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGeneratorFactory.java
> +            updatable = historyTable ? (column == null || column.updatable()) : (column != null && column.updatable());
reverted

2022-04-21 19:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGeneratorFactory.java
> +            upsertColumns.add(createUpsertColumn(schema, attribute, upsertable.history(), id));
no longer needed since with other changes the method doesn't need to know if the table has history or not.

2022-04-21 19:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/GenericUpsertQueryGenerator.java
> +                upsertEntity.column(c -> !c.isNullable() && !c.isId(), "coalesce(t.{0}, e.{0})"));
changed to get column nullable from information schema so want to keep it to be the first not null column here.

2022-04-21 19:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/template/upsert.vm
> +where $notNullableColumn is not null
done

2022-04-21 21:27 UTC, steven-sheehy approved these changes
LGTM

2022-04-21 23:00 UTC, Nana-EC approved these changes
LGTM

2022-04-22 00:27 UTC, merged