Fix monitor not publishing if error on startup
hashgraph/hedera-mirror-node pull request #3618
Opened 2022-04-20 00:44 UTC by steven-sheehy

**Description**:

* Change expression converter to use SDK retry instead of `Flux` retry
* Fix error modifying frozen transaction by not updating memo every retry

**Related issue(s)**:

Fixes #3617

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-28 19:05 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> -            var currentNodes = this.nodes; // Save a reference in case a COW occurs
Not sure why I thought this was necessary before. Must've had a different implementation initially.

2022-04-28 23:38 UTC, Nana-EC requested changes
Looks good.
Minor suggestion to move some hard coded run values to the Properties for easy exposure and configuration

2022-04-28 23:38 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        client.setNodeMaxBackoff(Duration.ofMinutes(1L));
Add to `PublishProperties`

2022-04-28 23:38 UTC, Nana-EC commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .setMaxAttempts(10);
Add to `PublishProperties`

2022-04-29 15:50 UTC, xin-hedera approved these changes
LGTM once existing feedback is addressed

2022-04-29 16:10 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +                    .setMaxAttempts(10);
Actually didn't mean to commit this so removed.

2022-04-29 16:10 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
> +        client.setNodeMaxBackoff(Duration.ofMinutes(1L));
Added

2022-04-29 19:12 UTC, Nana-EC approved these changes
LGTM

2022-04-29 19:12 UTC, xin-hedera approved these changes

2022-04-29 19:46 UTC, merged