fix record files block numbers
hashgraph/hedera-mirror-node pull request #3621
Opened 2022-04-20 16:25 UTC by matheus-dallrosa

Signed-off-by: Matheus DallRosa <matheus.dallrosa@swirlds.com>

**Description**:
This PR fixes the block number from record files.

**Related issue(s)**: #3543

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-21 18:53 UTC, steven-sheehy requested changes

2022-04-21 18:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java
> +        }
Use repositories and assertj. I think you should reduce the number of record files to the bare minimum for your scenario so it's easier to understand and test. There shouldn't really be more than 3 record files at a time to test the various cases. Replace with something like:

```java
assertThat(recordFileRepository.findAll())
  .hasSize(expected)
  .extracting(RecordFile::getConsensusEnd, RecordFile::getIndex)
  .containsExactlyInAnyOrder(...);
```

2022-04-21 18:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +
Should implement `getChecksum()` like `ErrataMigration`.

2022-04-21 18:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +        updateRecordFilesBlockNumber(migrationProperties.getCorrectBlockNumber(), recordFileBlockNumber);
```suggestion
        recordFileRepository.findById(timestamp)
            .map(RecordFile::getConsensusEnd)
            .filter(n -> n == expectedBlockNumber)
            .ifPresent(this::updateBlockNumber);
```

2022-04-22 13:27 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> -                .orElse(0L);
This code was changed before you review, but I did not pushed it to avoid too much github notifications. Instead I mark the PR as draft. Can you review it again?

2022-04-22 13:40 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RemoveInvalidEntityMigrationTest.java
> +                "hedera.mirror.importer.blocks.enabled=false"
Yes, it does not touch record file table. But if we keep the migration enabled when executing this test, the migration will try to query a schema that does not have the column `index` yet.

2022-04-22 13:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> -                .orElse(0L);
Almost, the startblocknumer should be after the increment

2022-04-22 13:56 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java
> +    private BlockNumberMigration blockNumberMigration;
done.

2022-04-22 13:56 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +        if(!migrationProperties.isEnabled()){
done.

2022-04-22 13:58 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +        if(!migrationProperties.isEnabled()){
Done.

2022-04-22 14:11 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> -                .orElse(0L);
Oh, ok.

2022-04-22 14:36 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +
Done.

2022-04-22 14:41 UTC, xin-hedera requested changes

2022-04-22 14:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        if (hasStreamFile) {
revert the change. `effectiveStartDate` should be the configured `startDate` if it's valid

2022-04-22 14:41 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessorTest.java
> +        Instant expectedDate = mirrorProperties.getStartDate();
change it to

```java
var startDate = STARTUP_TIME.plusSeconds(10L);
mirrorProperties.setStartDate(startDate);
```

with expectation
```
assertThat(mirrorProperties.getVerifyHashAfter()).isEqualTo(startupDate);
```

The test will fail. need to revert some changes in MirrorDateRangePropertiesProcessor.

2022-04-22 19:02 UTC, Nana-EC requested changes
Looking good.
Had pending feedback which echoed existing feedback so waiting on those items

2022-04-22 21:54 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +        Long recordFileBlockNumber = getRecordFileByConsensusEnd(migrationProperties.getCorrectConsensusEnd());
Done.

2022-04-25 16:17 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java
> +        }
Done.

2022-04-25 16:18 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java
> +                "values (?,?,?,?,?,?,?,3,?,0,?,?,?);";
Done.

2022-04-25 16:18 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/resources/blocks/record_files.json
> +    "hash": "495dc50d6323d4d5263d34dbefe7c20a0657a2fa5fe0d8c011a01f4a27757a259987dad210fb9596bc5a8cc7fbdbba33",
Done.

2022-04-25 19:52 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/resources/config/application.yml
> +        correctBlockNumber: 420
Done.

2022-04-25 19:52 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/application.yml
> +        correctBlockNumber: 420
Done.

2022-04-25 19:52 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigrationProperties.java
> +public class BlockNumberMigrationProperties {
Done.

2022-04-25 20:07 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +    private Long startBlockNumber;
Done.

2022-04-26 00:09 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessorTest.java
> +        Instant expectedDate = mirrorProperties.getStartDate();
What `startupDate` ? Are you asking me to do this changes just to verify that I need to revert some changes or to show me what is the correct changes for the test?

2022-04-26 00:11 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        if (hasStreamFile) {
The cases that involve the `hasStreamFile` should be completely ignored?

2022-04-26 13:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        if (hasStreamFile) {
no. just revert it. you shouldn't remove lines 135-136.

the only change needed in the method is remove the reference of `startDateAdjustment`

2022-04-26 15:33 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        if (hasStreamFile) {
Yes, I believe I did it already. I just had to remove the `minus(adjustment)`, because the `adjustment` was depending on the `startDateAdjustment`.

2022-04-26 15:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> +        if (hasStreamFile) {
looks good then

2022-04-26 15:50 UTC, steven-sheehy requested changes

2022-04-26 15:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        MigrationVersion highestVersion = getHighestVersionFromNonRepeatableMigrations(configuration.getJavaMigrations());
It looks like `configuration.getJavaMigrations()` will only return java migrations, not SQL migrations. There doesn't seem to be a way to return SQL migrations. We only have 4 Java migrations and only one of them is not repeatable. I don't think comparing against just that one java migration does want we want.

Instead, we can just compare minimum version against target version inside `skipMigration`. Something like this:

```java
    protected boolean skipMigration(Configuration configuration) {
        MigrationVersion current = getVersion();
        MigrationVersion baselineVersion = configuration.getBaselineVersion();

        if (current == null) {
            MigrationVersion minimumVersion = getMinimumVersion();
            MigrationVersion targetVersion = configuration.getTarget();
            return minimumVersion != null && targetVersion != null && minimumVersion.compareTo(targetVersion) > 0;
        }
...
```

2022-04-26 16:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +        updateRecordFilesBlockNumber(migrationProperties.getCorrectBlockNumber(), recordFileBlockNumber);
The other reason for my suggestion is that we should not be using manual SQL queries when we have an existing repository method to return the same thing. So after updating it to use the repository the code becomes cleaner if you chain the optional.

2022-04-26 21:24 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +    private static final long CORRECT_BLOCK_NUMBER = 420L;
Yes, sure. I just used some values to test. I will update them before merge, we can leave this comment open to make sure everybody knows that.

2022-04-27 14:57 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +                !currentNetwork.equals(MirrorProperties.HederaNetwork.MAINNET);
Done.

2022-04-27 14:58 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        MigrationVersion highestVersion = getHighestVersionFromNonRepeatableMigrations(configuration.getJavaMigrations());
Done.

2022-04-27 20:00 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +        updateRecordFilesBlockNumber(migrationProperties.getCorrectBlockNumber(), recordFileBlockNumber);
Done.

2022-04-29 21:32 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.0__remove_record_files_index_unique_constraint.sql
> +-- remove the unique index on the record_file.index column
I updated it to 1.57.1

2022-04-29 21:33 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BlockNumberMigration.java
> +            throw new RuntimeException("There is no consensus block number and consensus end for the network: "
Removed.

2022-04-29 21:41 UTC, Nana-EC requested changes

2022-04-29 21:41 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.startBlockNumber`                            | null                  | The block number that will be set as the block number for downloaded stream files. |
nit: 
```suggestion
| `hedera.mirror.importer.startBlockNumber`                            | null                  | The block number that will be set as the downloaded stream files starting index. |
```

2022-04-29 21:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.0__remove_record_files_index_unique_constraint.sql
> +-- remove the unique index on the record_file.index column
`V1.58.5` should be the next on as of this time

2022-04-29 21:41 UTC, Nana-EC commented on docs/configuration.md
> +| `hedera.mirror.importer.startBlockNumber`                            | null                  | The block number that will be set as the block number for downloaded stream files. |
Still some conflicts on this file

2022-04-29 22:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.0__remove_record_files_index_unique_constraint.sql
> +-- remove the unique index on the record_file.index column
1.57.1 is old. Needs to be V1.58.5

2022-05-02 14:09 UTC, matheus-dallrosa commented on docs/configuration.md
> +| `hedera.mirror.importer.startBlockNumber`                            | null                  | The block number that will be set as the block number for downloaded stream files. |
Done.

2022-05-02 14:16 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.0__remove_record_files_index_unique_constraint.sql
> +-- remove the unique index on the record_file.index column
Version upgraded.

2022-05-02 20:09 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +            return false;
Done.

2022-05-02 20:40 UTC, steven-sheehy approved these changes
LGTM

2022-05-02 20:41 UTC, Nana-EC requested changes
Looking good. Minor nit and a repeated test case

2022-05-02 20:41 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
> +        // is when we the target migration is not greater or equal to the required one.
```suggestion
        // is when the target migration is not greater or equal to the required one.
```

2022-05-02 20:41 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigrationTest.java
> +                Arguments.of(new JavaMigration(MigrationVersion.fromVersion("1.58.5"), MigrationVersion.fromVersion("1.57.1")), getConfiguration("1.55.0","1.58.0"), true),
Duplicate lines.
I believe your intention is to show 1. where baseline > version, 2. where version > target

2022-05-02 21:35 UTC, steven-sheehy approved these changes

2022-05-02 22:55 UTC, Nana-EC approved these changes
LGTM

2022-05-03 01:23 UTC, xin-hedera approved these changes

2022-05-03 02:19 UTC, merged