03611 hip 336 add spender id parameter to rest api
hashgraph/hedera-mirror-node pull request #3623
Opened 2022-04-20 19:54 UTC by ewlghedera

**Description**:
Add Spender Id parameter to /api/v1/accounts/{accountId}/nfts as specified by HIP-336.

**Related issue(s)**:

Fixes #3611 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-20 20:38 UTC, ewlghedera commented on hedera-mirror-rest/api/v1/openapi.yml
Not sure if this is correct or if it should require the token.id.

2022-04-20 20:38 UTC, ewlghedera commented on hedera-mirror-rest/api/v1/openapi.yml
Not sure if this is correct or if it should require the token.id.

2022-04-20 20:40 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-23-token-serial-spenderid-upper-bound.spec.json
> +      },
I'm unsure if this item should be returned, as the url specified `spender.id=lt:3007` and this item has a spender id of 3008.

2022-04-20 20:40 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-23-token-serial-spenderid-upper-bound.spec.json
> +      },
I'm unsure if this item should be returned, as the url specified `spender.id=lt:3007` and this item has a spender id of 3008.

2022-04-20 20:44 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-info-01-no-args.spec.json
>  }
This update is for the test case that was not added in the last issue.

2022-04-20 20:44 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/tokens-nfts-info-01-no-args.spec.json
>  }
This update is for the test case that was not added in the last issue.

2022-04-20 20:47 UTC, ewlghedera commented on hedera-mirror-rest/controllers/accountController.js
>        case constants.filterKeys.LIMIT:
I'm unsure if the spender id should behave like the token id and have inclusive bounds, or if it should behave like serial number and not have the inclusive bounds. From the spec tests, it seemed like the inclusive bounds yielded the results that I would have expected from the api.

2022-04-20 20:47 UTC, ewlghedera commented on hedera-mirror-rest/controllers/accountController.js
>        case constants.filterKeys.LIMIT:
I'm unsure if the spender id should behave like the token id and have inclusive bounds, or if it should behave like serial number and not have the inclusive bounds. From the spec tests, it seemed like the inclusive bounds yielded the results that I would have expected from the api.

2022-04-21 19:40 UTC, steven-sheehy requested changes

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        When considering NFTs, their order is governed by a combination of their numerical **token.Id**, **serialnumber** and **spender.Id** values, with **token.id** being the parent column.
Remove `spender.id` since it's not part of the unique key and thus doesn't affect ordering.

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
It doesn't need token.id. The index is (account_id, spender, ...) so it should be performant.

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        | spender.id    | eq                  | Y       | Single occurence only. | ?spender.id=Z |
eq, lt(e), gt(e) should allow multiple occurrences.

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        | spender.id    | eq                  | Y       | Single occurence only. | ?spender.id=Z |
Can you fix the spelling of occurrence in this table while you're updating it?

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-19-spenderid.spec.json
> +  "urls": ["/api/v1/accounts/0.0.1001/nfts?spender.id=gte:2000"],
Add `eq:2000`, `2000`, `lte:2000`, `lt:2001`, `gt:1999`

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-22-spenderid-upper-bound.spec.json
> +  "url": "/api/v1/accounts/0.0.1001/nfts?spender.id=lt:2000",
Add one lte upper bound and maybe return a couple items

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/accountController.js
> +    }
Remove as spender is not part of the unique key for pagination

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/accountController.js
> +  const inclusiveUpperSpenderIdBound = {};
Remove all the spender bounds. Spender is not part of the unique key and should just be used as an additional filtering of the results.

2022-04-21 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-23-token-serial-spenderid-upper-bound.spec.json
> +      },
Yeah, it's incorrect since spender should not be part of the unique key.

2022-04-22 15:05 UTC, xin-hedera requested changes

2022-04-22 15:05 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
>        case constants.filterKeys.LIMIT:
the spender id should be less restrictive. It should support range (both open and closed) and equal.

2022-04-22 15:06 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-23-token-serial-spenderid-upper-bound.spec.json
> +      },
Great, the updated version no longer returns `3008`.

2022-04-22 15:06 UTC, ewlghedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        When considering NFTs, their order is governed by a combination of their numerical **token.Id**, **serialnumber** and **spender.Id** values, with **token.id** being the parent column.
I've removed it.

2022-04-22 15:08 UTC, ewlghedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        | spender.id    | eq                  | Y       | Single occurence only. | ?spender.id=Z |
I've removed the text `Single occurrence only`.

2022-04-22 15:08 UTC, ewlghedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        | spender.id    | eq                  | Y       | Single occurence only. | ?spender.id=Z |
Got it, fixed.

2022-04-22 15:08 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-22-spenderid-upper-bound.spec.json
> +  "url": "/api/v1/accounts/0.0.1001/nfts?spender.id=lt:2000",
Got it. I've made those additions.

2022-04-22 15:09 UTC, ewlghedera commented on hedera-mirror-rest/controllers/accountController.js
> +    }
Ok I have removed this change.

2022-04-22 15:09 UTC, ewlghedera commented on hedera-mirror-rest/controllers/accountController.js
> +  const inclusiveUpperSpenderIdBound = {};
I've removed all the bounds and inserted a simple `spenderFilter` instead.

2022-04-22 15:49 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-20-spenderid-range.spec.json
> +        "delegating_spender": "0.0.5",
Ok I've made that change.

2022-04-22 15:50 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-19-spenderid.spec.json
> +      "next": null
Great thanks, I've added a new test for this: `accounts-nfts-26-spenderid-pagination.spec.json`

2022-04-22 16:47 UTC, steven-sheehy requested changes

2022-04-22 16:47 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-20-spenderid-range.spec.json
> +        "spender": "0.0.1999",
This entry does not match `spender.id=gte:2000`

2022-04-22 16:47 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-25-multiple-spenderid-range-filters.spec.json
> +    "/api/v1/accounts/0.0.1001/nfts?spender.id=2&spender.id=3",
This isn't a range param. We should support multiple equals and it should convert it to an IN clause.

2022-04-23 03:26 UTC, Nana-EC requested changes
Looking good, one suggestion and waiting on other suggestions.

2022-04-23 03:26 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-21-spenderid-lower-bound.spec.json
> +  "url": "/api/v1/accounts/0.0.1001/nfts?spender.id=gt:2000",
Can add a `gte` url

2022-04-25 15:23 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-25-multiple-spenderid-range-filters.spec.json
> +    "/api/v1/accounts/0.0.1001/nfts?spender.id=2&spender.id=3",
I've fixed this problem and added the `in` clause and a new test spec for it: `accounts-nfts-27-spenderid-in-clause.spec`

2022-04-25 15:23 UTC, ewlghedera commented on hedera-mirror-rest/__tests__/specs/accounts-nfts-20-spenderid-range.spec.json
> +        "spender": "0.0.1999",
Thanks, I've fixed this now.

2022-04-25 15:34 UTC, steven-sheehy approved these changes
LGTM

2022-04-25 17:19 UTC, Nana-EC approved these changes
LGTM

2022-04-26 13:53 UTC, xin-hedera approved these changes
LGTM

2022-04-26 14:00 UTC, merged