03615 support evm address in cryptotransfertransactionbody
hashgraph/hedera-mirror-node pull request #3656
Opened 2022-04-25 21:17 UTC by ewlghedera

**Description**:
HIP 329 Add support for EVM addresses in CryptoTransferTransactionBody.

**Related issue(s)**:

Fixes #3615 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-25 21:35 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +
I'm not sure if this a good enough test for the new functionality. Should I add more tests here or elsewhere?

2022-04-25 23:45 UTC, Nana-EC requested changes
Looks good.
Some simplification and test suggestions

2022-04-25 23:45 UTC, Nana-EC commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        return UnsafeByteOperations.unsafeWrap(create2EvmAddress());
Use the already present logic
```suggestion
        return DomainUtils.fromBytes(create2EvmAddress());
```

2022-04-25 23:45 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        entityProperties.getPersist().setCryptoTransferAmounts(true);
nit: can remove as already in `before()`

2022-04-25 23:45 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .extracting(EntityId::getEntityNum)
Can switch this to a `satisfies` and verify entity contains both `accountId1` and `EVM_ADDRESS`

2022-04-26 01:03 UTC, steven-sheehy requested changes

2022-04-26 01:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        Contract contract = domainBuilder.contract().customize(c -> c.evmAddress(EVM_ADDRESS.toByteArray())).persist();
There's no need to hardcode a static EVM_ADDRESS since the DomainBuilder will generate one for you. You can just use `contract.getEvmAddress()` in subsequent asserts. 

In general, I prefer reducing the scope of test data so it doesn't become hard to change later when everyone depends on the same value.

2022-04-26 01:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        assertThat(entityRepository.findByAlias(EVM_ADDRESS.toByteArray())).isNotPresent();
This assert doesn't really make much sense as you've never modified that table.

2022-04-26 01:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/EntityIdServiceImplTest.java
> +    void lookupCreate2EvmAddress() {
Perhaps something more specific to the fact that the account has the EVM address

```suggestion
    void lookupAccountWithEvmAddress() {
```

2022-04-26 16:55 UTC, xin-hedera requested changes

2022-04-26 16:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                ResponseCodeEnum.SUCCESS.getNumber());
why does the test case create a crypto account using the 20-byte create2 EVM address as the new account's alias? I don't think this is what services does for a create2 contract.

2022-04-26 16:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        var transfer2 = accountAliasAmount(ByteString.copyFrom(contract.getEvmAddress()), 1004).build();
this is confusing. If my other comment is correct, we better have only one such transfer from an account id using the 20-byte create2 evm address as the account alias.

2022-04-26 16:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .areAtMost(1, isAccountAmountReceiverAccountAmount(transfer2)),
the `isAccountAmountReceiverAccountAmount` would return no match since the actual params `transfer1` and `transfer2` have the evm address as alias form account IDs, while the domain `CryptoTrasnfer`s have the `shard.realm.num` form.

so the result is the `areAtMost` assert does nothing here.

2022-04-26 16:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                () -> assertEquals(additionalTransfers.length * 2 + 2, nonFeeTransferRepository.count()),
`additionalTransfers` is not used in the test case, so perhaps the number of non fee transfers should be 4 but definitely not the way expressed here.

2022-04-26 16:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .contains(accountId1.getAccountNum(), contract.getNum())
the transactions created for the tests end up with incorrect data in db:

```
test_db=# select * from non_fee_transfer order by consensus_timestamp ;
 entity_id | consensus_timestamp | amount | payer_account_id | is_approval
-----------+---------------------+--------+------------------+-------------
      1001 | 1650991717466943000 |   1000 |             2002 | f
      2002 | 1650991717466943000 |  -1000 |             2002 | f
         1 | 1650991717478093000 |   1004 |             2002 | f
         1 | 1650991717478093000 |   1003 |             2002 | f
(4 rows)

test_db=# select * from crypto_transfer  order by consensus_timestamp;
 entity_id | consensus_timestamp | amount | payer_account_id | is_approval | errata
-----------+---------------------+--------+------------------+-------------+--------
         3 | 1650991717466943000 |   1000 |             2002 | f           |
        98 | 1650991717466943000 |   1000 |             2002 | f           |
      2002 | 1650991717466943000 |  -2000 |             2002 | f           |
        98 | 1650991717478093000 |   1000 |             2002 | f           |
      2002 | 1650991717478093000 |  -2000 |             2002 | f           |
         3 | 1650991717478093000 |   1000 |             2002 | f           |
(6 rows)
```

The two non fee transfers using the same evm address as the alias are both resolved to contrac id `1`. the reason the assert still passes is because there happen to be another non fee transfer from `accountId` in a different transaction. However, it's wrong because the non fee transfer doesn't appear in the transaction's record at all.

2022-04-26 17:04 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .extracting(EntityId::getEntityNum)
Well instead you should add an explicit check for the entity containing the EVM_ADDRESS
Add something like the below used at the end of `cryptoCreateAccountAlias()`
```suggestion                        
                () -> assertThat(entityRepository.findByAlias(EVM_ADDRESS.toByteArray())).get()
                        .isEqualTo(accountId1.getId())
```

2022-04-26 21:08 UTC, ewlghedera commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        return UnsafeByteOperations.unsafeWrap(create2EvmAddress());
Thanks, I have removed the method entirely.

2022-04-26 21:08 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        entityProperties.getPersist().setCryptoTransferAmounts(true);
Got it, that line has been removed.

2022-04-26 21:09 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .extracting(EntityId::getEntityNum)
I've added an allSatisfies condition that should check the contract and the payerAccountId (as I removed anything to do with accountId1).

2022-04-26 21:09 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/EntityIdServiceImplTest.java
> +                .setAccountNum(100)
Critical feedback. I have fixed the test.

2022-04-26 21:10 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        Contract contract = domainBuilder.contract().customize(c -> c.evmAddress(EVM_ADDRESS.toByteArray())).persist();
I've removed the constant and instead relied on `contract.getEvmAddress`.

2022-04-26 21:10 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        assertThat(entityRepository.findByAlias(EVM_ADDRESS.toByteArray())).isNotPresent();
I've removed that line.

2022-04-26 21:10 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/EntityIdServiceImplTest.java
> +    void lookupCreate2EvmAddress() {
Sounds good, I have renamed the method.

2022-04-26 21:11 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                ResponseCodeEnum.SUCCESS.getNumber());
I've refactored the test case; it should have the superfluous items removed now.

2022-04-26 21:11 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +        var transfer2 = accountAliasAmount(ByteString.copyFrom(contract.getEvmAddress()), 1004).build();
I've removed `transfer2`.

2022-04-26 21:12 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .areAtMost(1, isAccountAmountReceiverAccountAmount(transfer2)),
I've removed the `areAtMost` assertions.

2022-04-26 21:12 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                () -> assertEquals(additionalTransfers.length * 2 + 2, nonFeeTransferRepository.count()),
I've removed that assertion.

2022-04-26 21:15 UTC, ewlghedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
> +                        .contains(accountId1.getAccountNum(), contract.getNum())
I've refactored the test case; it conducts assertions on the `transactionRepository` and the `nonFeeTransferRepository`. Should it also include an assertion on the `cryptoTransferRepository`? I found that the `cryptoTransferRepository` was not effected by the test, so if it should have been changed perhaps I have more test constructs to setup.

2022-04-26 21:43 UTC, steven-sheehy approved these changes
LGTM

2022-04-26 22:41 UTC, xin-hedera approved these changes
LGTM

2022-04-27 01:33 UTC, Nana-EC approved these changes
LGTM

2022-04-27 14:11 UTC, merged