Persist block transaction index
hashgraph/hedera-mirror-node pull request #3657
Opened 2022-04-26 15:10 UTC by Nana-EC

**Description**:
The JSON RPC flow includes a transaction block index value, the mirror node therefore needs to persist this value.

- Update `Transaction` domain with an `index` column to capture the transaction index
- Add a db migration to add column to `transaction` table
- Update `SqlEntityListener` logic to keep track of index and populate it in incoming transactions

**Related issue(s)**:

Fixes #3588 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-26 19:10 UTC, steven-sheehy requested changes

2022-04-26 19:10 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +    public int transactionIndex() {
Why does this need to public?

2022-04-26 19:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        transaction.setIndex(transactionIndex.incrementAndGet());
Transaction index should start at zero.

```suggestion
        transaction.setIndex(transactionIndex.getAndIncrement());
```

2022-04-26 19:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    index                      integer,
Need to add to migration script

2022-04-26 19:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .containsExactlyInAnyOrder(firstTransaction, secondTransaction, thirdTransaction)
It should verify the exact order, both here and below.

2022-04-26 22:57 UTC, xin-hedera requested changes

2022-04-26 22:57 UTC, xin-hedera commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        return transactionIndex.incrementAndGet();
nit, since the index starts from 0 should do:

```suggestion
        return transactionIndex.getAndIncrement();
```

2022-04-26 22:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            transactionIndex.set(0); // reset block transaction index
shouldn't we add the transaction index in the pipeline where we are handling the record file?

one obvious issue is if the importer is configured to filter out certain transaction types, those transactions will not reach `EntityListener`, so importers with different transfer filters show different transaction index.

For that reason, I'd suggest we add the index in `RecordItem` and set it in RecordFileReader.

2022-04-27 14:47 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .containsExactlyInAnyOrder(firstTransaction, secondTransaction, thirdTransaction)
Well the `findAll()` isn't ordered by `index` so not sure we can assure that.
Actually see failures otherwise

2022-04-27 14:48 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            transactionIndex.set(0); // reset block transaction index
I see what you mean, I also prefer this since it sits above the listener.
My current concern was we are only getting the index for the `SqlEntityListener` flow and others Listeners would have to sort themselves out

2022-04-27 14:49 UTC, Nana-EC commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        return transactionIndex.incrementAndGet();
Fixed

2022-04-27 14:50 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        transaction.setIndex(transactionIndex.incrementAndGet());
Updated

2022-04-27 14:50 UTC, Nana-EC commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +    public int transactionIndex() {
Initially had a an outside use case for it but was not needed. Scaled down to private

2022-04-27 15:37 UTC, steven-sheehy requested changes

2022-04-27 15:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var thirdTransaction = domainBuilder.transaction().get();
We should clear the index so the test actually verifies it is set.

2022-04-27 15:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .containsExactlyInAnyOrder(firstTransaction, secondTransaction, thirdTransaction)
Nevertheless, the point stands that we're not verifying that `firstTransaction` has `index` set to `0`, etc. You can upgrade `TransactionRepository` to `PagingAndSortingRepository` and do that. Or you can verify somehow that `firstTransaction.index=0`, etc. some other way.

2022-04-27 17:16 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var thirdTransaction = domainBuilder.transaction().get();
Set incorrect default so change is clear

2022-04-27 19:05 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var thirdTransaction = domainBuilder.transaction().get();
Reverting as the logic gets moved to fileReader level

2022-04-27 20:08 UTC, steven-sheehy requested changes

2022-04-27 20:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(timestamps).doesNotHaveDuplicates().isSorted();
Duplicated from above. Did you intend to check indexes instead?

2022-04-27 20:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(timestamps).doesNotHaveDuplicates().isSorted();
```suggestion
                    assertThat(transactionBlockIndexes).isEqualTo(IntStream.range(0, recordFile.getCount()));
```

2022-04-27 20:15 UTC, xin-hedera reviewed
LG, just some nits

2022-04-27 20:15 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(transactionBlockIndexes).first().isEqualTo(0);
can create the expected list of indices using `IntStream.range(0, transactionBlockIndexes.size()).boxed().collect(Collectors.toList())`

2022-04-27 20:54 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(timestamps).doesNotHaveDuplicates().isSorted();
Yes

2022-04-27 21:01 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(transactionBlockIndexes).first().isEqualTo(0);
Thanks. Used another suggestion similar to this

2022-04-27 21:20 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(transactionBlockIndexes).first().isEqualTo(0);
Actually this was the better one.
Adopting

2022-04-27 21:28 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    private final Integer transactionBlockIndex;
Updated

2022-04-27 21:28 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        this(RecordFile.HAPI_VERSION_NOT_SET, transaction, record, null);
Updated in a similar place since data types aren't exact here

2022-04-27 21:29 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(timestamps).doesNotHaveDuplicates().isSorted();
Adopted

2022-04-27 21:29 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/record/RecordFileReaderTest.java
> +                    assertThat(timestamps).doesNotHaveDuplicates().isSorted();
Updated

2022-04-27 21:29 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    public RecordItem(Version hapiVersion, byte[] transactionBytes, byte[] recordBytes, Integer transactionBlockIndex) {
Added and used

2022-04-27 21:36 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        this(RecordFile.HAPI_VERSION_NOT_SET, transaction, record, null);
Actually seems like more needs to be done here. Expect another commit for this scope creep

2022-04-27 22:28 UTC, steven-sheehy approved these changes
LGTM

2022-04-27 23:31 UTC, xin-hedera approved these changes
LGTM

2022-04-28 14:05 UTC, merged