Fix Internal error with shard.realm.evmAddress in entityId parsing
hashgraph/hedera-mirror-node pull request #3668
Opened 2022-04-28 13:05 UTC by ewlghedera

**Description**:
Fix the internal error with parsing an evmAddress that includes `0.0.` at the beginning of the address.

**Related issue(s)**:

Fixes #3658

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-28 14:51 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +  const hexDigits = evmAddress.replace('0x', '').replace('0.0.', '');
We can't assume that shard or realm is always zero as that will break in the future once we have non-zero values.

2022-04-28 14:51 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-period-including-address.spec.json
> +  ],
Can you open a P1 ticket for it then?

2022-04-28 18:50 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-period-including-address.spec.json
> +  ],
I think we can do it all here on this PR. I will push the fix soon.

2022-04-28 20:38 UTC, matheus-dallrosa commented on hedera-mirror-rest/entityId.js
> +  const hexDigits = evmAddress.replace('0x', '').replace('0.0.', '');
Fixed.

2022-04-28 23:42 UTC, Nana-EC requested changes
Looking good, minor test update suggestions on 1st pass

2022-04-28 23:42 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json
> +  "description": "Contract results api call for a specific contract using contract id",
Update description

2022-04-28 23:42 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json
> +    "/api/v1/contracts/000000000000000000000000000000000186Fb1b/results",
nit: add the single `0.` option also

2022-04-29 00:36 UTC, steven-sheehy approved these changes
LGTM

2022-04-29 01:44 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-04-29 03:33 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json
> +    "/api/v1/contracts/000000000000000000000000000000000186Fb1b/results",
I'd presume `0.000000000000000000000000000000000186Fb1b` is a supported format since we usually support `0.0.x/0.x/x`

2022-04-29 21:52 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json
> +    "/api/v1/contracts/000000000000000000000000000000000186Fb1b/results",
Done.

2022-04-29 21:52 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json
> +  "description": "Contract results api call for a specific contract using contract id",
Done.

2022-04-29 22:00 UTC, steven-sheehy submitted a review, later dismissed

2022-04-29 22:07 UTC, Nana-EC requested changes
Minor test missing then it'll be good to go

2022-04-29 22:07 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/entityId.test.js
> +    {
Nit: Add the `0.000000000000000000000000000000000186Fb1b` test

2022-04-29 22:11 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/entityId.test.js
> +    {
Done.

2022-04-29 22:11 UTC, Nana-EC approved these changes
LGTM

2022-04-29 22:32 UTC, merged