WIP: Feature/List blocks rest api
hashgraph/hedera-mirror-node pull request #3669
Opened 2022-04-28 13:48 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #
- https://github.com/hashgraph/hedera-mirror-node/issues/1933

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-04-28 13:57 UTC, Daniel-K-Ivanov approved these changes
LGTM! Lets wait for the full e2e test coverage

2022-04-29 15:08 UTC, matheus-dallrosa commented
This is just a reminder for next tasks. We have a pattern the for branch names which is `0{number of the ticket}-{description of the changes}`
The description of the changes must have the words separated by a `-`.

2022-04-29 17:03 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/blockService.js
> +  buildWhereSqlStatement(whereQuery) {
Does this function need to be accessible from outside?

2022-04-29 17:11 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/blockService.js
> +    for (const i in whereQuery) {
is `whereQuery` an array? I believe if we know the length of `whereQuery`, we can avoid the parsing.

2022-04-29 18:58 UTC, xin-hedera requested changes
need more test spec coverage:

- more than 1 occurrence of params
- all params togeter
- invalid param values

2022-04-29 18:58 UTC, xin-hedera commented on hedera-mirror-rest/server.js
> +app.useAsync(`${apiPrefix}/${BlockRoutes.resource}`, BlockRoutes.router);
please add the spec of the block endpoint to openapi.yml

2022-04-29 18:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +        "count": "7",
not sure how `count` and `number` are of type string, should be just number.

2022-04-29 18:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/blocks-04-block.number-param.spec.json
> +  "urls": ["/api/v1/blocks?block.number=lt:18"],
also test url "/api/v1/blocks?block.number=lte:17"

2022-04-29 18:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/blocks-04-block.number-param.spec.json
> +        "hapi_version_patch": "3",
```suggestion
        "hapi_version_major": 0,
        "hapi_version_minor": 22,
        "hapi_version_patch": 3,
```

2022-04-29 18:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +        "consensus_end": 1676540001234700000,
wrap the timestamps as string since they are larger than nodejs MAX_SAFE_INTEGER, may cause issue
```suggestion
        "consensus_start": "1676540001234610000",
        "consensus_end": "1676540001234700000",
```

2022-04-29 19:17 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/blocks-06-timestamp-param-no-records.spec.json
> +    "recordFiles": [
I believe the setup could be empty? ( not 100% sure ).

2022-04-29 22:36 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/blockViewModel.js
> +    this.gas_used = 50000000;
Should probably set it to null if incorrect or we usually leave it out altogether so as not to provide false information until we're sure it's right

2022-04-29 22:42 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +      },
Most of this output does not match the requirements in https://github.com/hashgraph/hedera-mirror-node/issues/1933. Please revisit the ticket and check the response format intended.

2022-04-29 22:42 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/blockViewModel.js
> +    this.gas_used = 50000000;
Leave out until it's implemented.

2022-04-29 23:03 UTC, steven-sheehy requested changes

2022-04-29 23:03 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/blocks-04-block.number-param.spec.json
> +  "urls": ["/api/v1/blocks?block.number=lt:18"],
We should also test `gt`, `gte`, `eq`, and '' in the specs.

2022-04-29 23:05 UTC, Nana-EC requested changes
Looking good on 1st pass.
Lots of hard coded items.
Also need to updated `openapi.yml`

2022-04-29 23:05 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +    if (filters.hasOwnProperty('block.number')) {
```suggestion
    if (filters.hasOwnProperty(constants.filterKeys.BLOCK_NUMBER)) {
```

2022-04-29 23:05 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +          filters['block.number'],
```suggestion
          filters[constants.filterKeys.BLOCK_NUMBER],
```

2022-04-29 23:05 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +    if (filters.hasOwnProperty('timestamp')) {
```suggestion
    if (filters.hasOwnProperty(constants.filterKeys.TIMESTAMP)) {
```

2022-04-29 23:05 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +          filters['timestamp'],
```suggestion
          filters[constants.filterKeys.TIMESTAMP],
```

2022-04-29 23:05 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +          (op, value) => [`consensus_end ${op} ?`, [value]],
```suggestion
          (op, value) => [`${RecordFile.CONSENSUS_END} ${op} ?`, [value]],
```

2022-05-03 09:01 UTC, natanasow commented on hedera-mirror-rest/service/blockService.js
> +  buildWhereSqlStatement(whereQuery) {
Nope, but wrapped it in the class to be able to unit test it

2022-05-03 12:40 UTC, natanasow commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +        "count": "7",
`count` and `number` are int8 in db, and they are parsed as strings because JS doesn't have support for 64-bit integers

2022-05-03 13:32 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +        "count": "7",
I see. We'll address the bigint issue in a separate ticket.

2022-05-03 13:37 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +        "count": "7",
They still need to be converted from string to Number. Block count and number will probably never exceed 2^53 - 1. And if they do, we are adding a json-bigint parser soon.

2022-05-03 13:45 UTC, natanasow commented on hedera-mirror-rest/__tests__/specs/blocks-01-no-args.spec.json
> +        "count": "7",
Okay

2022-05-03 14:37 UTC, natanasow commented on hedera-mirror-rest/service/blockService.js
> +    for (const i in whereQuery) {
Yeah, it's an array. Is there a function that makes an array of queries to parametric query?
```typescript
const queries = [
    {query:  'index <', param: 20},
    {query:  'index >', param: 10}
];
```
to become
```typescript
const {query, params} = someFunction(queries);
// query => 'where index < $1 and index > $2';
// params = [20, 10];
```
Searched in utils but didn't find :confused:

2022-05-03 14:38 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/blockService.js
> +  buildWhereSqlStatement(whereQuery) {
I think you can unit test the class, and in a transitive way test the code from this function without exposing it. From what I have seen so far, it won't be a lot of change.

2022-05-03 19:28 UTC, Nana-EC requested changes
Almost there. Some minor improvement suggestions to aid reusability

2022-05-03 19:28 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/blockViewModel.js
> +   * Constructs contract view model
```suggestion
   * Constructs block view model
```

2022-05-03 19:28 UTC, Nana-EC commented on hedera-mirror-rest/service/blockService.js
> +    let where = 'where true=true';
Would prefer a cleaner sql statement without `where true=true` when no conditions are applicable
Maybe something like this
```suggestion
    let where = '';
    const params = [];
    if (whereQuery.length > 0) {
      for (let i = 1; i <= whereQuery.length; i++) {
        where += ` and ${whereQuery[i - 1].query} $${i} `;
        params.push(whereQuery[i - 1].param);
      }
    }
```

2022-05-03 19:28 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +            return {
I like this.
Just move logic to a shared method so it's not repeated and easy to reuse
```suggestion
            return getFilterWhereCondition(RecordFile.INDEX, f);
```

With added method
```js
getFilterWhereCondition = (key, filter) => {
    return {
      query: `${key} ${filter.operator}`,
      param: filter.value,
    };
  }
```

Eventually we could move it somewhere better but no need to worry about placement right now

2022-05-03 19:28 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +  extractOrderFromFilters = (filters) => {
nit: `extractOrderFromFilters` and `extractLimitFromFilters` are candidates for placement in the `BaseController`.
My guess is we'll use it again in the getBlock endpoint and others.
No need to move now it it will create too much code churn

2022-05-03 21:26 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/blockService.js
> +    for (const i in whereQuery) {
Sorry, I think I should have been more clear. The parsing I mentioned was about the `parseInt` call. Since we know the length of the array we can  make `i` an integer and just increment its value.

2022-05-03 21:29 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/specs/blocks-06-timestamp-param-no-records.spec.json
> +    "recordFiles": [
@natanasow Unless there is a good reason to not leave it empty, make it empty.

2022-05-04 15:43 UTC, steven-sheehy approved these changes
LGTM. Some OpenAPI and naming requests but those can be completed in the get block PR if you like.

2022-05-04 15:43 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        hapi_version:
Would like descriptions be added to these fields.

2022-05-04 15:43 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +              $ref: '#/components/schemas/Timestamp'
Use `TimestampRange`

2022-05-04 15:43 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        serialNumNoOperator:
Remove `serial` from these operators as it's a copy and paste from elsewhere. Can just be `noOperator`, etc.

2022-05-04 15:43 UTC, steven-sheehy commented on hedera-mirror-rest/service/blockService.js
> +class BlockService extends BaseService {
A block is synonymous with a record file. This code should be moved to the existing `RecordFileService`. Naming the controller as `BlockController` makes sense since that's the endpoint's name.

2022-05-04 16:00 UTC, xin-hedera submitted a review, later dismissed
LGTM. just some minor items

2022-05-04 16:14 UTC, Nana-EC submitted a review, later dismissed
Signing off to unblock Get Block PR.
My comments were also on OpenAPI so you can merge, rebase and address them in that PR

2022-05-04 18:07 UTC, matheus-dallrosa approved these changes
LGTM. Just fix this minor comment: https://github.com/hashgraph/hedera-mirror-node/pull/3669#discussion_r862083115

2022-05-05 05:42 UTC, natanasow commented on hedera-mirror-rest/__tests__/specs/blocks-06-timestamp-param-no-records.spec.json
> +    "recordFiles": [
Done.

2022-05-05 08:28 UTC, natanasow commented on hedera-mirror-rest/api/v1/openapi.yml
> +        hapi_version:
Like a `description` property? Could you provide me with an example, because I couldn't find an existing one in the current `openapi.yml`?

2022-05-05 14:26 UTC, Nana-EC approved these changes
Looking good.
Go ahead an merge since you got some sign offs and you can address the outstanding comments in the Get Block PR so you're not jumping between 2 PRs

2022-05-05 14:30 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        hapi_version:
Yes, the `description` property can be used on property schema. You can see an example [here](https://github.com/hashgraph/hedera-mirror-node/blob/5557d6452d77cb49f4844e1bf69b76e44d1ecbb8/hedera-mirror-rest/api/v1/openapi.yml#L1639).

You're right in that we don't populate it as often as I'd like.

2022-05-05 14:32 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +              $ref: '#/components/schemas/Timestamp'
I see you updated it, but I meant the entire block should be a TimestampRange, not each individual timestamp.

```yaml
        timestamp:
          $ref: '#/components/schemas/TimestampRange'
```

2022-05-05 14:54 UTC, natanasow commented on hedera-mirror-rest/api/v1/openapi.yml
> +              $ref: '#/components/schemas/Timestamp'
Got it, will fix it in https://github.com/hashgraph/hedera-mirror-node/pull/3718

2022-05-05 14:54 UTC, merged