feat: add support for repeated topics
hashgraph/hedera-mirror-node pull request #3673
Opened 2022-04-29 11:44 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #3505 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-04-29 14:13 UTC, natanasow submitted a review, later dismissed
LGTM

2022-04-29 14:46 UTC, Daniel-K-Ivanov requested changes

2022-04-30 01:44 UTC, Nana-EC requested changes
Simplification suggestion.
Also need to update `openapi.yml` to highlight repetition support. Noting that repetitions within topics are `OR` and across remain `AND`

2022-04-30 01:44 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  updateQueryFiltersWithInValues(
COuld simplify this section with something like
```suggestion
  Object.keys(keyFullNames).forEach((key) => {
    updateQueryFiltersWithInValues(
      params,
      conditions,
      inValues[key],
      keyFullNames[key]
    );
  });
```

2022-05-02 19:43 UTC, edwin-greene submitted a review, later dismissed
Looks good, just a few things to change from the other review.

2022-05-03 06:42 UTC, ar-conmit commented on hedera-mirror-rest/__tests__/specs/contracts-logs-15-repeated-topics-with-timestamp.spec.json
> +{
I think there is a mistake in the expected result of the 3rd case based on the provided input data

```logs?topic0=P&topic2=Z``` -> should return an empty array because there is no matching topic between ```Log B``` and ```Log C```. The matching condition between non-repeatable topics is considered as ```AND```

2022-05-03 13:28 UTC, Daniel-K-Ivanov commented on hedera-mirror-rest/__tests__/specs/contracts-logs-15-repeated-topics-with-timestamp.spec.json
> +{
You are right. My bad

2022-05-03 16:43 UTC, steven-sheehy approved these changes
LGTM

2022-05-03 16:43 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +            value: '0000150',
nit: Redundant to say topic3=150 OR topic3=150

2022-05-03 18:25 UTC, xin-hedera approved these changes
LGTM

2022-05-03 18:58 UTC, Nana-EC approved these changes
LGTM

2022-05-03 18:59 UTC, merged