WIP: Feature/list contract results rest api
hashgraph/hedera-mirror-node pull request #3674
Opened 2022-04-29 13:53 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-03 22:05 UTC, matheus-dallrosa commented on hedera-mirror-rest/constants.js
> +  TRANSACTION_INDEX: 'transaction.index',
Put `TRASACTION_INDEX` together with the other `TRANSACTION*` constants.

2022-05-03 22:20 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
Have you checked if it is possible to change the `/results` suffix for something else?
In reality, I had this problem in the past, and I remember the solution being something very simple. I believe that moving the `/contracts/results` route above the `/contracts/:contractId` would fix it.

2022-05-03 22:32 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +        else {
So we are going to execute the query anyway? 
I believe the logic to get the block details should be done in another place. After you know if the block exists you can call this function.

2022-05-03 22:34 UTC, matheus-dallrosa commented on hedera-mirror-rest/routes/contractRoute.js
> +router.getAsync('/results', ContractController.getContractResults);
Try moving the routes with suffix `/results` before the routes with substring `/:contractId`. I believe it will fix the conflict.

2022-05-04 03:46 UTC, Nana-EC requested changes
Good start, some suggestions to improve flow and simplify approach

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +  join ${Transaction.tableName} ${Transaction.tableAlias}
Why the join on `ContractResult` and then the left join on `EthereumTransaction`?
Are you trying to filter something out?

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +  left join ${EthereumTransaction.tableName} ${EthereumTransaction.tableAlias}
Also probably no need for the join on `transaction` table. The `CONSENSUS_TIMESTAMP` will be the same for all so just join `ContractResult to `EthereumTransaction`.
Also update the select if you mean to pull something from `EthereumTransaction`

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +            {key: constants.filterKeys.TIMESTAMP, operator: '>=', value: blockData[conStartColName]},
```suggestion
            {key: constants.filterKeys.TIMESTAMP, operator: utils.opsMap.gte, value: blockData[conStartColName]},
```

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +            {key: constants.filterKeys.TIMESTAMP, operator: '<=', value: blockData[conEndColName]},
```suggestion
            {key: constants.filterKeys.TIMESTAMP, operator: utils.opsMap.lte, value: blockData[conEndColName]},
```

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +        else {
Agreed. Don't proceed here if you know it's not applicable.
Make the `RecordFileService.getRecordFileBlockDetailsFromIndex` in the main method. If present pass it to `extractContractResultsByIdQuery`. If not present then fail fail and return the empty response.

See `getContractResultsByTimestamp` and `getContractResultsByTransactionId` as examples where we do similar checks and return `NotFoundError`

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
Please check this suggestion. As it would be better to not have the `utils.conflictingPathParam` logic

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/constants.js
> +  BLOCK_NUMBER: 'block.number',
This list is alphabetized, so you should insert them into their sorted locations.

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const ethTx = Object.assign({}, localDefaults, ethereumTransaction);
Use spread in this case instead of `Object.assign` like all the other methods in this file..
Since the first item is an empty object I believe spread is more performant in this case.

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +        "skipTransaction": true
What's the use of `skipTransaction`?
I don't think we should be passing in a flag to not create a separate domain object.
This case should see no change in the file.

Other cases should see you add `Transaction` domain objects you explicitly.

2022-05-04 03:46 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  if (!skipTransaction) {
This should be dropped. Just add the desired `transactions` n the spec files

2022-05-04 08:51 UTC, Ivo-Yankov commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
I tried this approach. In order for it to work the request needs to stop at the first route that matches it and not be passed to the next middleware with `next()`, but that is done by default by `@awaitjs/express`. It would also mean that `responseHandler` and `handleError` have to be applied to every route seperately, or have some kind of wrapper function that appends those middlewares to every route handler. 

I think that using `utils.conflictingPathParam` is the simpler solution here, as it will be applied very rarely and does not add the need to do any refactorring to the existing middleware structure.

2022-05-04 15:02 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  if (num.startsWith('0x')) {
We should probably check if typeof num === 'string' first

2022-05-04 15:03 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +  if (num.startsWith('0x')) {
```suggestion
  if (num.startsWith(hexPrefix)) {
```

2022-05-04 15:04 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +  left join ${EthereumTransaction.tableName} ${EthereumTransaction.tableAlias}
I think it was just meant to filter on ethereum hash, but it should really be filtering on block hash so this join probably not needed.

2022-05-04 15:08 UTC, Ivo-Yankov commented on hedera-mirror-rest/service/contractService.js
> +  left join ${EthereumTransaction.tableName} ${EthereumTransaction.tableAlias}
The joins are only used for filtering the results by `transaction.index`, `transaction.nonce` and `ethereum_transaction.hash`. There is no need to select any fields from `transaction` or `ethereum_transaction`.

2022-05-04 15:09 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-05-internal-false.spec.json
> +  "urls": ["/api/v1/contracts/results?internal=false", "/api/v1/contracts/results"],
There's two contract results in the test setup but only one shows up in the response despite there being no filters. Why?

2022-05-04 15:11 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-04-internal-true.spec.json
> +        "consensus_timestamp": "987654000123456",
Since this is explicitly testing the inclusion of internal transactions we should have at least one with nonce > 0.

2022-05-04 15:12 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +  left join ${EthereumTransaction.tableName} ${EthereumTransaction.tableAlias}
Ah I see. It looks unnecessary here since the where filtering is added elsewhere.
Makes sense.

However, we should explore using this only where there are filters applied.
If the query is bare or doesn't use these noted items we should pick up the previous query to avoid the unnecessary joins

2022-05-04 15:17 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-01-no-params.spec.json
> +        "contract_id": "0.0.5001",
Since the point of the `/api/v1/contracts/results` is that it returns results across contract IDs, we should update some of the specs to have results that aren't all for contract `0.0.5001`.

2022-05-04 15:19 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-03-block-number.spec.json
> +  "urls": ["/api/v1/contracts/results?block.number=10", "/api/v1/contracts/results?block.number=0xa"],
It would be good to include at least two results in the response for block.number and block.hash parameters to confirm that it is returning all transactions within that block.

2022-05-04 15:21 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      case constants.filterKeys.BLOCK_HASH:
When querying the `block.hash` against the `record_file.hash` you'll need to take into account whether it's 32 or 48 bytes. You can probably just do `LIKE` or `substring` to treat them both the same.

2022-05-04 18:20 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
Maybe this is an integration problem between the libs. But it does not make much sense for this to happen, since matching the route should have not much to do with the handlers or `next` calls.

2022-05-05 01:10 UTC, xin-hedera requested changes

2022-05-05 01:10 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  utils.validateReq(req);
```suggestion
```
either `utils.validateReq` or `utils.buildAndValidateFilters`, not both

2022-05-05 01:10 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    const lastContractResultTimestamp = lastRow !== undefined ? lastRow.timestamp : null;
```suggestion
```
lastRow won't be `undefined` since you have a check `!_.isEmpty(response.results)`

2022-05-05 15:25 UTC, Ivo-Yankov commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-05-internal-false.spec.json
> +  "urls": ["/api/v1/contracts/results?internal=false", "/api/v1/contracts/results"],
By default all transactions with `nonce: 1` are filtered out. They are only included in the result if `internal=true`

2022-05-05 16:45 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
need to do 2 things if we don't want to check for conflict in the controller function:

1. register the handler for `/contracts/results` before `/contracts/:contractId`
2. pull the logic which handles the response header & json stringify in `responseHandler` to a utility function and make every handler calls it instead of setting `constants.responseDataLabel`

2022-05-05 17:00 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
Let's leave as is for now. Don't want to make any sweeping changes here.

2022-05-05 17:20 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
agreed. we should take care of it in a separate PR.

2022-05-05 17:22 UTC, Ivo-Yankov commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
When a request is made to `/contracts/results` it is matched by both routes: `/contracts/results` and `/contracts/:contractId`, regardles of which is declared first. Since the latter matches any string after the last slash and it tries to handle `result` as an id and that causes it to throw an error.

There is no other such case in the mirror node as of now. But for example if it is decided to add a route `/tokens/something` it would conflict with `/tokens/:tokenId` in the same way.

The other solutions I can find are: 
- Rename the route to something else that does not conflict with any of the existing routes.
- Refactor `/contracts/results` so that it is declared first and not use `getAsync`. But that would have to look something like this:

```
router.get('/results', (req, res, next) => {
// logic from ContractController.getContractResults
// handleError
// responseHandler
// make sure to end the request here and not call next();
});
```

2022-05-05 22:28 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
I created a ticket #3732 with a proposed solution there

2022-05-05 22:56 UTC, steven-sheehy requested changes

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  if (utils.conflictingPathParam(req, 'contractId', 'results')) return;
We created a separate [ticket](https://github.com/hashgraph/hedera-mirror-node/issues/3732) to address. Resolving this item.

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +          blockData = await RecordFileService.getRecordFileBlockDetailsFromIndex(filter.value);
This looks like it would query for each repeated block number or hash parameter, which would be slow. Instead, we should pick the last `block.number` or `block.hash` then query the database once outside the loop.

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      case constants.filterKeys.BLOCK_HASH:
If both `block.number` and `block.hash` are provided it should throw an error.

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/routes/contractRoute.js
> +router.getAsync('/results', ContractController.getContractResults);
Need to update openapi

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-09-transaction-index.spec.json
> +        "index": 2,
Can we have another transaction with the same index=2 in a different block to verify it doesn't return all entries with that index? And also have another transaction within the same block=17 with index=1?

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-10-transaction-index-isolated.spec.json
> +          "message": "Invalid parameter: transaction.index"
It would be better if it told you why it was invalid since here it is not the parameter format but the fact that it's missing block.number or block.hash.

2022-05-05 22:56 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-08-all-params.spec.json
> +    "/api/v1/contracts/results?timestamp=1676540001.234390005&block.number=10&internal=false&transaction.index=1&block.hash=fbd921184e229e2051280d827ba3b31599117af7eafba65dc0e5a998b70c48c0492bf793a15
We should have another spec that shows various invalid parameter formats. Here's an [example](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-rest/__tests__/specs/accounts-08-invalid-param-values.spec.json).

Specifically, I would like to validate that it fails for:
* `block.number=(gte?|lte?|ne)`
* `block.hash=(gte?|lte?|ne)`
* `transaction.index=(gte?|lte?|ne)`

2022-05-09 16:21 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    num = parseInt(num, 16);
This is an input from user. I do think we need to make it correct.

2022-05-09 16:31 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    num = parseInt(num, 16);
or can leave it to a follow-up PR.

2022-05-09 19:04 UTC, Ivo-Yankov commented on hedera-mirror-rest/service/contractService.js
> +  static joinTransactionTable = `left join ${Transaction.tableName} ${Transaction.tableAlias}
It seems that the CI `rest api v2` is failing for spec tests that add `join transaction` statement to  `detailedContractResultsQuery`. Can someone please give me a hint as to why this is happaning and if there is a way to fix it?

2022-05-09 22:05 UTC, xin-hedera requested changes

2022-05-09 22:05 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  });
this can be done with just one loop.

1. loop the params and determine if transaction index / block hash / block number param exists
2. apply the rule to throw error

what's better is you can pass in `req.query` dictionary instead of the flat `filters` array.

2022-05-10 03:13 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^((eq):)?(\d{1,19}|0x([a-fA-f0-9])+?)$
nit: Some unnecessary grouping
```suggestion
        pattern: ^(eq:)?(\d{1,19}|0x[a-fA-f0-9]+)$
```

2022-05-10 03:13 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +  static joinTransactionTable = `left join ${Transaction.tableName} ${Transaction.tableAlias}
With CitusDB, it usually complains that it can't distribute the query with joins. Try to use a CTE instead.

2022-05-10 03:19 UTC, steven-sheehy approved these changes
LGTM besides the broken v2 tests and some nits

2022-05-10 14:38 UTC, xin-hedera approved these changes
LGTM

2022-05-10 15:37 UTC, Nana-EC approved these changes
LGTM

2022-05-10 15:37 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +      select * from ${Transaction.tableName}
nit: personally don't like pulling every column, especially from an adjacent table. 
If there's knowledge of the columns needed we should stick to that.

2022-05-10 15:58 UTC, merged