Add Parent RecordItem link for easy consolidation
hashgraph/hedera-mirror-node pull request #3676
Opened 2022-04-29 16:31 UTC by Nana-EC

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>

**Description**:
Add logic to refer to a parent transaction in the parser
- Add RecordItem parent link in `RecordItem`
- Update FIleReader to populate this where the recordItem is a child.
- Updated `ContractCreateTransactionHandler` to handle when initCode or FileID is in parent transaction, either ContractCreate or `EthereumTransactionHandler`

**Related issue(s)**:

Fixes #3670 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-04-29 21:17 UTC, steven-sheehy requested changes

2022-04-29 21:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                                        .longValue()) {
Can be simplified and avoid the unnecessary timestamp conversion:

```suggestion
            if (recordItem.isChild() && parentRecordItem != null && recordItem.getParentConsensusTimestamp().equals(parentRecordItem.getConsensusTimestamp()) {
```

2022-04-29 21:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            }
Move this to an else above so we don't check `isChild()` twice.

2022-04-29 21:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var parentRecordItem = recordItem.getParentRecordItem();
Check if parent is null and return. We can have pre-0.26 case where child and parent are in different record files.

2022-04-29 21:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            default:
So if parent is contract call and child is contract create we'll never have the data?

2022-04-29 21:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var ethereumDataBytes = DomainUtils.toBytes(body.getEthereumData());
As an optimization, we should skip extracting bytes and parsing data if the `EthereumTransactionBody.callData` is present.

2022-04-29 21:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (ethereumTransaction.getCallData() != null) {
It's not clear if call data will be null or an empty byte array if the FileID is not present. Regardless, we should definitely check FileID first then we can always set this as the fallback behavior and don't have to worry about null vs empty.

2022-04-29 21:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var parentRecordItem = recordItem.getParentRecordItem();
Should never happen as the timestamp check ensure they are both in the same file and therefore avoids pre v0.26
Can add it here for defensiveness though

2022-04-29 21:47 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            default:
Yep.
That flow needs a migration to look up contract.file and set it.

2022-04-29 21:49 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var ethereumDataBytes = DomainUtils.toBytes(body.getEthereumData());
Good point

2022-04-29 21:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var parentRecordItem = recordItem.getParentRecordItem();
It can definitely happen. If parent is last item in RF1 and child is first item in RF2, then any timestamp check in record item reader won't occur and `recordItem.isChild()` will return true. NPE occurs

2022-05-02 15:56 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (ethereumTransaction.getCallData() != null) {
Had actually locally changed this to set based on `contract` fields being null

2022-05-02 18:05 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    private RecordItem parentRecordItem = null;
Changed

2022-05-02 18:05 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +        RecordItem lastRecordItem = null;
Updated

2022-05-02 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                    recordItem.setParentRecordItem(lastRecordItem);
Problem is we need to parse the recordBytes first and create the child recordItem.
Then using that determine if setting a parentRecordItem is applicable.
Thats why I added the setter

2022-05-02 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                                        .longValue()) {
Updated

2022-05-02 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            }
Moved

2022-05-02 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var parentRecordItem = recordItem.getParentRecordItem();
Updated

2022-05-02 18:07 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var ethereumDataBytes = DomainUtils.toBytes(body.getEthereumData());
Added, also added a test to verify

2022-05-02 18:10 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (ethereumTransaction.getCallData() != null) {
Updated

2022-05-02 20:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var parentRecordItem = recordItem.getParentRecordItem();
Still don't see this check. Not sure if you've pushed the change.

2022-05-02 20:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                parentRecordItem = recordItem;
This would mark a child that's the first entry in a record file as being a parent.

2022-05-02 20:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                    recordItem.setParentRecordItem(lastRecordItem);
Provided an alternative algorithm via slack

2022-05-02 21:00 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                parentRecordItem = recordItem;
Meant to nest iniital if.
Should be
```java
            if (recordItem.isChild()) {
                if (parentRecordItem != null &&
                        recordItem.getRecord().getParentConsensusTimestamp()
                                .equals(parentRecordItem.getRecord().getConsensusTimestamp())) {
                    recordItem.setParent(parentRecordItem);
                }
            } else {
                // update last recordItem reference for next item. Preserve parent until all children have been
                // processed since they are assured to exist in sequential order of [Parent, Child1,...,ChildN]
                parentRecordItem = recordItem;
            }
```

2022-05-03 00:24 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                    recordItem.setParentRecordItem(lastRecordItem);
Implemented, with tests

2022-05-03 00:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var parentRecordItem = recordItem.getParentRecordItem();
Missed it, added now

2022-05-03 00:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                parentRecordItem = recordItem;
Updated

2022-05-03 01:03 UTC, steven-sheehy requested changes

2022-05-03 01:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                    .previous(lastRecordItem)
Since now we're setting previous in addition to parent, we could set it on v1 and v2 readers since otherwise our future selves might try to use `RecordItem.getPrevious()` and get a NPE on historical data.

2022-05-03 01:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
We should add a test in `RecordFileReaderTest`.

2022-05-03 01:17 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
I looked into that and it's quite heavy since this method and others aren't easily exposed. Seems like there would be multiple levels of mocking to get to this depth.
Also with the new logic there's not much change to this file in terms of logic so the existing tests should suffice.
We now just create and cache the RecordItem that was done in the streamObject directly instead of calling StreatObject.getRecordItem multiple times.

Actually i should remove `getRecordItem()` since that's dead code now

Let me know if there's a flow in here that you think was changed that is of concern

2022-05-03 01:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
I'm not sure we're talking about the same thing. I meant add a test to `RecordFileReaderImplV5Test` that verifies that previous is not null and is the expected item and that parent is not null. If you add it to V1 and V2 then you can pull up to `RecordFileReaderTest`

2022-05-03 02:40 UTC, xin-hedera requested changes

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (!entityProperties.getPersist().isContracts() || !recordItem.isChild() || recordItem.getParent() == null) {
can be simplified to 
```suggestion
        if (recordItem.getParent() == null) {
```

`isContracts()` is checked in the caller

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        }
can remove, this is dead code, `etheremTransaction.callDataId` is always `null`

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                .satisfies(c -> assertThat(c.getInitcode()).isNotNull())
```suggestion
                .satisfies(c -> assertThat(c.getInitcode()).isNotEmpty())
```

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +    public void updateChildFromParent(Contract contract, RecordItem recordItem) {
```suggestion
    private void updateChildFromParent(Contract contract, RecordItem recordItem) {
```

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                .build();
why would a recordItem with a transaction record (parentConsensusTimestamp = null) have a parentRecordItem?

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +        doReturn(domainBuilder.ethereumTransaction(true).get()).when(ethereumTransactionParser).decode(any());
```suggestion
```

`decode()` isn't called

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +        doReturn(domainBuilder.ethereumTransaction(false).get()).when(ethereumTransactionParser).decode(any());
the stubbed return doesn't match the implementation since `EtherumTransactionParser` never sets `callDataId`

2022-05-03 02:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
remove `transactionBlockIndex` from `RecordStreamObject`, remove `RecordStreamObject.getRecordItem`

2022-05-03 06:28 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
Yep, removed locally, coming in next commit

2022-05-03 07:13 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (!entityProperties.getPersist().isContracts() || !recordItem.isChild() || recordItem.getParent() == null) {
Yeah, I dropped one of the tests after realizing this.
Conceptually I see why it can be reduced further, however `recordItem.isChild()` is set as a result of transactionRecordBytes parsing, whereas `recordItem.getParent()` is set as a result of comparison logic between current and previous.
Because the logic exists in different flows I think it's fair to have the explicit checks.
Let me know if you disagree

2022-05-03 07:17 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                .build();
Similar comment to other. Just exhaustive testing given the unique nature contributing to each items set.
In practice it shouldn't happen but if an inconsistency did occur we have coverage for it's behaviour

2022-05-03 07:17 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +        doReturn(domainBuilder.ethereumTransaction(true).get()).when(ethereumTransactionParser).decode(any());
`decode` is always called if of `EthereumTransaction`.
Let me know if i'm missing something

2022-05-03 07:31 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    private RecordItem previous;
Updated

2022-05-03 07:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +                    .previous(lastRecordItem)
Added

2022-05-03 07:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
Added tests.
I don't believe there was a parent-child relationship preV5 so the tests for parent had to be in v5 but the tests for previous is shared

2022-05-03 07:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        }
Removed

2022-05-03 07:33 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                .satisfies(c -> assertThat(c.getInitcode()).isNotNull())
Updated

2022-05-03 07:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +    public void updateChildFromParent(Contract contract, RecordItem recordItem) {
Updated

2022-05-03 07:33 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +        doReturn(domainBuilder.ethereumTransaction(false).get()).when(ethereumTransactionParser).decode(any());
That's correct. It's set in the `upTransaction()` formerly `getEntity`.
The stub is to ensure the parser call result is successful.
I can explicitly set the `callDataId` to null although as you said it's not picked up there.
Rather `callDataId` is always pulled from the `transactionBody`

2022-05-03 07:33 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
> +            var recordItem = RecordItem.builder()
Removed

2022-05-03 13:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (!entityProperties.getPersist().isContracts() || !recordItem.isChild() || recordItem.getParent() == null) {
I'd say checking parent set or not is enough, since if it's not a child there definitely shouldn't be parent set. if in any chance the parent is set, that's a bug in `RecordItem`, not here.

2022-05-03 13:13 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +        doReturn(domainBuilder.ethereumTransaction(true).get()).when(ethereumTransactionParser).decode(any());
the problem is `decode` isn't always called. the fast path in the implementation is if the call data is stored in a file, the transaction handler just gets the file id from the tx body, so ethereum tx parsing is skipped.

2022-05-03 14:21 UTC, steven-sheehy approved these changes
LGTM

2022-05-03 17:32 UTC, xin-hedera approved these changes
LGTM

2022-05-03 17:59 UTC, merged