HIP-16 Support contract expiry
hashgraph/hedera-mirror-node pull request #3701
Opened 2022-05-02 13:00 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #3606

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-02 18:32 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
> +  return new EntityId(toNumber(shard), toNumber(realm), toNumber(num));
`shard`, `realm`, and `num` can fit into a js `Number` since per the encoding their values won't be > js Number.MAX_SAFE_INTEGER.

The change is needed so EntityId.isAllZero can just compare the three parts to `0` instead of conditionally checking against `0` or `0n`.

2022-05-02 18:33 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        auto_renew_account:
keep it consistent with `TokenInfo`

2022-05-02 19:24 UTC, edwin-greene approved these changes
Looks good!

2022-05-03 19:07 UTC, steven-sheehy requested changes

2022-05-03 19:08 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +  return new EntityId(toNumber(shard), toNumber(realm), toNumber(num));
I'm not a fan of having invalid data in the db. We'll have to clean this up when we add an `@UpsertColumn`.

2022-05-03 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.5__contract_expiry.sql
> +alter table if exists contract
V1.58.7?

2022-05-03 19:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.5__contract_expiry.sql
> +alter table if exists contract
There's a Java migration as well

2022-05-03 21:19 UTC, steven-sheehy approved these changes

2022-05-03 21:21 UTC, merged