Add a list contracts logs REST API
hashgraph/hedera-mirror-node pull request #3717
Opened 2022-05-04 08:36 UTC by ar-conmit

**Description**:
Add a new endpoint ```/contracts/results/logs```
Add regex filter ```[0-9.-]*``` to an existing endpoint ```/contracts/results/:transactionId``` to prevent route collisions with ```/contracts/results/logs```

**Related issue(s)**:

Fixes #3582 

**Notes for reviewer**:
Changed test case for endpoint ```"/api/v1/contracts/results/x"``` to return 404 instead of 400. If ```:transactionId``` starts with a letter(eg. "x") it will conflict with the newly created endpoint.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-04 14:12 UTC, Nana-EC requested changes
Looking good.
Some suggestion and please make sure you've rebased off of latest main

2022-05-05 03:41 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-logs-22-no-address-with-reach-max-limit.spec.json
> +  "description": "Contracts logs api calls across many contracts with 25 results out of 27 in total",
Recommended using the config option in the json to reduce max limit to something lower like 3.

2022-05-05 12:20 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +  const filters = utils.buildAndValidateFilters(req.query);
No real reason, my negligence.
It returns just the filters now.

2022-05-05 15:02 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> -const getContractResultsByTimestamp = async (req, res) => {
It's impossible to review this file with all the unnecessary changes. Did you reorder every method for some reason? Large scale refactoring/reordering is fine but should be done in a separate PR from feature/bug PRs.

2022-05-05 16:11 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> -const getContractResultsByTimestamp = async (req, res) => {
Ok, perhaps Nana didn't realize it wasn't already extending BaseController and would require this much change. But since you've already done the work, no need to undo the work. I thought your IDE was just reordering things unnecessarily.

2022-05-05 21:11 UTC, xin-hedera requested changes

2022-05-05 21:11 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    const rows = await ContractService.getContractLogsByIdAndFilters(
nit, remove `Id` from the function name,
```suggestion
    const rows = await ContractService.getContractLogs(
```

2022-05-05 21:11 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-17-not-found.spec.json
> +  }
this is weird. we should fix it in a separate PR, that the handler for `/api/v1/contracts/results/:transactionId` is invoked and the previous error message is returned.

2022-05-06 05:07 UTC, steven-sheehy submitted a review, later dismissed
LGTM besides what others have said.

2022-05-06 16:10 UTC, Nana-EC approved these changes
Looks good.
Please address any blocking comments here but pull over other items into the next PR to free up other tickets.

2022-05-09 08:30 UTC, ar-conmit commented on hedera-mirror-rest/routes/contractRoute.js
> +router.getAsync('/results/:transactionId([0-9.-]*)', ContractController.getContractResultsByTransactionId);
Thanks for the hint. I will sync with Ivo(who will pick the mentioned ticket) about this change

2022-05-09 09:47 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +      throw new InvalidArgumentError(`Cannot search topics without timestamp range: ${e.message}`);
Things we should keep in mind for the next PR:
- change regex in ```/results/:transactionId([0-9.-]*)``` to support transactionHash(issue #3585)
- update spec file ```contracts-result-details-17-not-found.spec.json``` to return 400 instead of 404

2022-05-09 14:48 UTC, Nana-EC approved these changes

2022-05-09 15:07 UTC, merged