Get block REST API
hashgraph/hedera-mirror-node pull request #3718
Opened 2022-05-04 14:10 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #

- https://github.com/hashgraph/hedera-mirror-node/issues/3577

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-05-05 09:53 UTC, natanasow commented
@steven-sheehy Do we need some kind of validation for the input param /blocks/:hashOrNumber, and what's the expected behavior? If the user passes an invalid hash (different length) or invalid number (/api/v1/blocks/testinput), what should we return, an empty object or an error like that :point_down: 
```
{
    "_status": {
        "messages": [
            {
                "message": "Invalid parameter: hashOrNumber"
            }
        ]
    }
}
```

2022-05-05 14:17 UTC, Nana-EC commented
> @steven-sheehy Do we need some kind of validation for the input param /blocks/:hashOrNumber, and what's the expected behavior? If the user passes an invalid hash (different length) or invalid number (/api/v1/blocks/testinput), what should we return, an empty object or an error like that 👇
> 
> ```
> {
>     "_status": {
>         "messages": [
>             {
>                 "message": "Invalid parameter: hashOrNumber"
>             }
>         ]
>     }
> }
> ```

@natanasow  Yes, you'll definitely want to validate it. Failure should throw an `InvalidArgumentError.forParams(constants.filterKeys.HASHORNUMBER)` like you've noted with 
See `validateContractIdParam` & `validateContractIdAndConsensusTimestampParam` in the `contractController.js` as an example.
You'll wanna add a utils.isValidEthereumHashOrNumber(hashOrNumber) that can be utilized here and in the `utility.filterValidityChecks()`

2022-05-10 15:09 UTC, steven-sheehy requested changes

2022-05-10 15:09 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +  /api/v1/blocks:
This block duplicates the one above

2022-05-10 15:38 UTC, xin-hedera requested changes

2022-05-10 15:38 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/blocks-get-by-hash-or-number-01-number.json
> +        "count": 3,
can you change `index` and `count` in this spec to be > js Number.MAX_SAFE_INTEGER? need to verify now we can correctly handle large numbers.

2022-05-10 15:38 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A hedera hash format.
incorrect description

2022-05-10 15:38 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A hedera hash format.
incorrect description

2022-05-10 15:38 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +
duplicate
```suggestion
```

2022-05-11 06:54 UTC, Nana-EC requested changes
One item, will circle back for 2nd review.
Agree with most comments

2022-05-11 06:54 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +const {BlockViewModel} = require('../viewmodel');
Remove as not being used. Plus viewmodel should only be called in controller. @

2022-05-11 13:41 UTC, xin-hedera approved these changes
LGTM

2022-05-11 14:35 UTC, Nana-EC requested changes
Looking good, just one more push with some items around hash format handling

2022-05-11 14:35 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +      const hashWithoutPrefix = hashWithPrefix.substring(2);
Is `hash` a string already? If so this line isn't needed and you can just use `hash` below

2022-05-11 14:35 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +    if (hash) {
Move this data type conversion to the controller after param validation.

2022-05-11 14:35 UTC, Nana-EC commented on hedera-mirror-rest/service/recordFileService.js
> +      const hashWithPrefix = utils.addHexPrefix(hash);
Why add prefix just to remove it again?
If the goal is just to remove the `0x` if it exists then we can do this with 
```suggestion
      const hashWithoutPrefix = hash.replace('0x', '');
```

2022-05-11 14:35 UTC, Nana-EC commented on hedera-mirror-rest/controllers/blockController.js
> +const validateHashOrNumber = (hashOrNumber) => {
conversion pruning of `0x` in hash should be done in here so service gets it as a useable param

2022-05-11 14:35 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A ethereum hash format.
```suggestion
      description: A hex encoded ethereum transaction hash.
```

2022-05-11 16:07 UTC, steven-sheehy requested changes

2022-05-11 16:07 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/blockViewModel.js
> +    this.number = BigInt(recordFile.index);
The fields are already BigInt when returned by the database.
```suggestion
    this.number =recordFile.index;
```

2022-05-11 16:15 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/BlockResponse'
Can remove useless `BlockResponse` wrapper and directly use '#/components/schemas/Block'

2022-05-11 20:38 UTC, Nana-EC approved these changes
LGTM.
Agree with Steven's last comments then we can merge

2022-05-12 03:35 UTC, xin-hedera submitted a review, later dismissed

2022-05-12 13:30 UTC, steven-sheehy approved these changes

2022-05-12 14:26 UTC, merged