Search contract result details by eth hash
hashgraph/hedera-mirror-node pull request #3764
Opened 2022-05-11 14:29 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-05-12 20:18 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +        nonce,
`nonce` doesn't apply when searching transaction by hash

2022-05-12 20:20 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
>      const nonce = getLastNonceParamValue(req.query);
move this line to the `else` part where the path param is a transaction id.

2022-05-12 20:24 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: string
add a schema for transaction id string if there isn't one, then change this to
```suggestion
      schema:
        oneOf:
          - $ref: '#/components/schemas/EthereumHash'
          - $ref: '#/components/schemas/TransactionIdStr'
```

2022-05-12 20:32 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionService.js
> +      select ${EthereumTransaction.CONSENSUS_TIMESTAMP}, ${EthereumTransaction.HASH} from ${
```suggestion
      select ${EthereumTransaction.CONSENSUS_TIMESTAMP} from ${
```

2022-05-12 20:32 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionService.js
> +    left join ${EthereumTransaction.tableAlias}
```suggestion
    join ${EthereumTransaction.tableAlias}
```

2022-05-12 20:33 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionService.js
> +    where ${EthereumTransaction.tableAlias}.${EthereumTransaction.HASH} = $1`;
```suggestion
  )}`;
```

2022-05-12 20:33 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionService.js
> +  async getTransactionDetailsFromEthHash(ethHash, nonce = undefined, excludeTransactionResults = []) {
`nonce` doesn't apply

2022-05-13 00:34 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: string
One exists already `$ref: '#/components/schemas/TransactionId'`

2022-05-13 00:38 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: string
That's of type object not the string format we need here

2022-05-13 00:48 UTC, Nana-EC requested changes
Test request.
Other items already called out by other reviewers so will wait on that

2022-05-13 00:48 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +const isValidEthHash = (hash) => {
Add tests for this method

2022-05-13 14:49 UTC, xin-hedera approved these changes
LGTM. just one nit

2022-05-13 18:10 UTC, Nana-EC approved these changes
LGTM

2022-05-13 21:10 UTC, merged