Populate ethereum nonce
hashgraph/hedera-mirror-node pull request #3798
Opened 2022-05-16 23:08 UTC by steven-sheehy

**Description**:

**Related issue(s)**:

Fixes #3678

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-16 23:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            list.remove(previous);
This logic is not ideal. Open to ideas how to clean it up. I think long term we need some generic state class that encapsulates the changes from the record per domain type.

2022-05-16 23:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ColumnMetadata.java
> -class UpsertColumn implements Comparable<UpsertColumn> {
This rename and `UpsertEntity` rename is to support a future `@UpsertColumn` annotation that didn't make it into this PR.

2022-05-16 23:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGeneratorFactory.java
> -    UpsertEntity createEntity(Class<?> domainClass) {
This logic was moved to `EntityMetadataRegistry` so the metadata can be used by other code like a future coalesce operator to dynamically merge domain objects in memory.

2022-05-17 01:05 UTC, steven-sheehy commented
Still trying to figure out why v2 importer tests fail, but otherwise ready for review.

2022-05-17 17:59 UTC, Nana-EC requested changes
Looks good, minor suggestion on test side.
Will think on any improvement on entity map in entitylistener

2022-05-17 17:59 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(contractRepository.count()).isZero();
nit: can remove since all entities are type `ACCOUNT` right?

2022-05-17 19:01 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +            entity.setEthereumNonce(ethereumTransaction.getNonce());
The default is null and nonce=0 is the first transaction. If we add a check for `nonce > 0` it will skip the first valid entry. But this did help me to realize we should only update nonce for successful transactions, per the HIP.

2022-05-17 19:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(contractRepository.count()).isZero();
This was there when we split entity and contract and wanted to make sure they went to the right table. But we probably don't need it for all tests, just one or two. Will remove

2022-05-17 19:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(entityRepository.findAll()).containsExactlyInAnyOrder(existingEntity);
Just doing a `findById` won't verify the overall count is correct. So you'd have to do a separate count query as well, which is efficient. I think this is the optimal verification.

2022-05-17 20:23 UTC, xin-hedera requested changes

2022-05-17 20:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +            entity.setEthereumNonce(ethereumTransaction.getNonce());
my interpretation of the HIP is that we should set account's nonce to successful ethereum transaction's nonce + 1. we may also want to update the default to 0 in our db schema or translate `null` ethereum nonce to 0 for account entities in rest api.

2022-05-17 21:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +            entity.setEthereumNonce(ethereumTransaction.getNonce());
Good catch on the plus one.

But actually turns out the success vs unsuccessful was more nuanced. So you're only supposed to update nonce for successful transactions OR failed transactions that were executed in the EVM. There are some checks before EVM like nonce correctness, then the nonce is updated in state before EVM per Danno.

2022-05-17 21:47 UTC, steven-sheehy commented on .github/workflows/importer.yml
> -        schema: [ v1, v2 ]
Citus is failing with `Complex subqueries, CTEs and local tables cannot be in the outer part of an outer join with a distributed table`. Tried rewriting the upsert query but it's non-trivial. Due to the deadline, will open a ticket with the fix and address later.

2022-05-17 22:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        var senderId = EntityId.of(functionResult.getSenderId());
is it possible that an successful ethereum transaction does not have contract create/call result in tx record? if so, senderId will be `EntityId.EMPTY` and we'll miss the nonce update.

2022-05-17 23:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        var senderId = EntityId.of(functionResult.getSenderId());
No, that is not possible. All Ethereum tx have a contract result.

2022-05-17 23:42 UTC, Nana-EC approved these changes
LGTM

2022-05-18 00:16 UTC, xin-hedera approved these changes
LGTM

2022-05-18 00:41 UTC, merged