3586 add fields to contract result details
hashgraph/hedera-mirror-node pull request #3800
Opened 2022-05-17 13:10 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2022-05-17 16:22 UTC, Nana-EC requested changes
Looking good, a couple of improvement items.
Let's see which items from here and other comments should be address here and which can be done in a future iteration that allows 0.57.0 release to be cut

2022-05-17 18:12 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    this.chain_id = transaction.chain_id ? utils.addHexPrefix(transaction.chain_id) : null;
Some of these items are only applicable when the contract call was initiated by `ETHEREUMTRANSACTION`.
In that case i'm wondering if we should leave those fields out of the response.
Basically move the population of them into the if `ETHEREUMTRANSACTION` check

2022-05-17 19:06 UTC, Nana-EC approved these changes
Looks good other than hash comment.
Also `record_file.gas_used` and `record_file.logs_bloom` are now available, with a rebase these can can be added to this PR and merged

2022-05-17 19:43 UTC, Nana-EC commented
I'm working on rebasing and adding `record_file.gas_used` to response

2022-05-17 21:06 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.access_list = null;
Actually I meant to omit this so the fields aren't defined at all.
Will pull this out into a `EthereumTransactionResultViewModel.js`

2022-05-17 21:14 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    if (`${transaction.type}` === TransactionType.getProtoId('ETHEREUMTRANSACTION')) {
With this added logic the `integrationDomainOps` needs to be updated to set the `transaction.type = 50`.
Will add

2022-05-17 21:18 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +    "access_list": null,
These null additions aren't needed if you drop these fields for non ethereum initiated contract results

2022-05-17 21:20 UTC, Nana-EC requested changes
Seeing a few issues after another review and working on adding `gas_used` changes.
Will address and push

2022-05-17 21:21 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +    "access_list": null,
probably we want to discuss which approach to use. the `null` fields for non ethereum transactions is a requirement in the ticket, plus we've never done this before (hide fields which don't apply based on the resource type)

2022-05-17 21:49 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.access_list = null;
Scracth this

2022-05-17 21:50 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +              example: 1
all should be `nullable` in case we decide to make the response schema static.

2022-05-17 21:50 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +
it's worth adding a `coalesce` or `pickFirst` utility function here.

2022-05-17 21:50 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
> +    "access_list": null,
Yeah, ignore this. We've used both in the past but I believe we're standardizing on having a static set of fields per endpoint.
Some viewModels may be reused across endpoint in which they can differ

2022-05-17 22:27 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +        this.amount = long.fromValue(Buffer.from(transaction.value, 'utf8').toString()).toNumber();
Will change to
```suggestion
        this.amount = parseInt(Buffer.from(transaction.value, 'utf8').toString(), 16);
```

2022-05-17 22:28 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      txHash = _.isNil(transaction.ethHash) ? transaction.transactionHash : transaction.ethHash;
Will change to 
```suggestion
      txHash = _.isNil(transaction.ethHash) ? transaction.transactionHash : Buffer.from(transaction.ethHash, 'utf8').toString();
```

2022-05-17 22:43 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +        this.amount = long.fromValue(Buffer.from(transaction.value, 'utf8').toString()).toNumber();
in our ethereum transaction parser, `value` is saved as `rlpItems.get(?).asBigInt().toByteArray())`

why treat it as a hex string and use parseInt?

in addition, why didn't we create the schema with `value` of type `bigint` directly?

2022-05-17 22:46 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      txHash = _.isNil(transaction.ethHash) ? transaction.transactionHash : transaction.ethHash;
both transactionHash and ethHash are `bytea` in db, not sure why we want to treat `ethHash` as string here.

2022-05-18 01:06 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +              example: 1
Will add and rearrange

2022-05-18 01:09 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      txHash = _.isNil(transaction.ethHash) ? transaction.transactionHash : transaction.ethHash;
Simplified, but for reference ethHash is persisted as utf-8 encoded bytes.
So need to go back to same sting provided

2022-05-18 01:17 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    if (`${transaction.type}` === TransactionType.getProtoId('ETHEREUMTRANSACTION')) {
no-op

2022-05-18 01:41 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +        this.amount = long.fromValue(Buffer.from(transaction.value, 'utf8').toString()).toNumber();
Eth developers expect most values in the [transaction receipt](https://eth.wiki/json-rpc/API#eth_gettransactionbyhash) in the same hex string format provided so we should return it as such.
Bigint was used by services and us to not lose precision.
Let me know if you're suggesting something simpler than what i just pushed

2022-05-18 01:42 UTC, Nana-EC submitted a review, later dismissed
Unblocking my previous requests as I addressed them in the last commits.
Let's wait on 1 more signoff and response to any open comments

2022-05-18 02:32 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +        this.amount = long.fromValue(Buffer.from(transaction.value, 'utf8').toString()).toNumber();
Quite confused. I believe the issue I pointed out still exists and for `value` what's even worse is we save a bigint as a bytearray so java big-endian byteorder is involved.

The integration tests are passing I believe just because the way in integrationDomainOps the data is load is wrong.

There are many other fields with the same issue. Let's pick `chain_id` as the example, in the test specs we normally set it in the `setup` section to the value `0x0127`, in integrationDomainOps, it should decode the hex string into nodejs `Buffer`, however instead, we directly save the hex string as if it's a `bytea` array, so we end up with this in db

```
mirror_node_integration=# select chain_id from ethereum_transaction ;
    chain_id
----------------
 \x307830313237
(1 row)
```

obviously the value in db is double hex encoded. In importer, this is what we have in Eip1559EthereumTransactionParserTest

```
                .satisfies(t -> assertThat(Hex.encodeHexString(t.getChainId())).isEqualTo("012a"))
```

so importer saves the byte array, not the double hex encoded string as byte array.

The conclusion here is many fields are encoded incorrectly.

2022-05-18 05:31 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +        this.amount = long.fromValue(Buffer.from(transaction.value, 'utf8').toString()).toNumber();
Ah yes, you're correct. Let's try to resolve this ASAP as I think it should be the final item blocking

2022-05-18 06:15 UTC, steven-sheehy requested changes

2022-05-18 06:15 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.hash = utils.addHexPrefix(Buffer.from(transaction.ethHash, 'utf8').toString());
After you coalesce in the query, you can simplify this and remove the hash assignment below.
```suggestion
      this.hash = utils.toHexString(transaction.hash, true);
```

2022-05-18 06:15 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.gas_limit = !_.isNil(transaction.gasLimit) ? transaction.gasLimit : null;
This should coalesce with the gas_limit set in the super.
```suggestion
      if (!_.isNil(transaction.gasLimit) {
        this.gas_limit = transaction.gasLimit;
      }
```

2022-05-18 06:15 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.from = !_.isNil(contractResult.senderId) ? EntityId.parse(contractResult.senderId).toEvmAddress() : null;
This should coalesce with the contract_result.payer_account_id that's set in the super
```suggestion
      if (!_.isNil(contractResult.senderId) {
        this.from = EntityId.parse(contractResult.senderId).toEvmAddress();
      }
```

2022-05-18 06:15 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +        if (!contractResult.functionParameters.length && !_.isNil(fileData)) {
```suggestion
      } else if (!contractResult.functionParameters.length && !_.isNil(fileData)) {
```

2022-05-18 15:09 UTC, Ivo-Yankov commented on hedera-mirror-rest/api/v1/openapi.yml
> +              type: integer
Done.

2022-05-18 15:09 UTC, Ivo-Yankov commented on hedera-mirror-rest/api/v1/openapi.yml
> +            chain_id:
Done.

2022-05-18 15:10 UTC, Ivo-Yankov commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.access_list = transaction.accessList ? utils.addHexPrefix(transaction.accessList) : null;
Done.

2022-05-18 15:13 UTC, Ivo-Yankov commented on hedera-mirror-rest/service/transactionService.js
> +      ${Transaction.getFullName(Transaction.NONCE)},
Done.

2022-05-18 15:22 UTC, Ivo-Yankov commented on hedera-mirror-rest/service/transactionService.js
> +    ${Transaction.getFullName(Transaction.TYPE)},
Done.

2022-05-18 15:27 UTC, Ivo-Yankov commented on hedera-mirror-rest/service/transactionService.js
> +      ${this.ethTransactionSelectedFields}
Done.

2022-05-18 15:34 UTC, Ivo-Yankov commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.gas_limit = !_.isNil(transaction.gasLimit) ? transaction.gasLimit : null;
Done.

2022-05-18 19:53 UTC, steven-sheehy requested changes

2022-05-18 19:53 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.block_gas_used = recordFile.gasUsed;
This should always be set as it's not a field from `ethereum_transaction`.

2022-05-18 19:55 UTC, matheus-dallrosa commented on hedera-mirror-rest/controllers/contractController.js
> +    if (!_.isNil(transaction.callDataId)) {
Make this check inside the implementation of the method `getLatestFileDataContests` there is no need to duplicate this if.

2022-05-18 20:06 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      this.block_gas_used = recordFile.gasUsed;
Can move to line 53 and then remove the null set above

2022-05-18 20:32 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    if (!_.isNil(transaction.callDataId)) {
prefer not to do so since it makes sense for the method in services to assume the passed in fileId is not null.

2022-05-18 20:51 UTC, steven-sheehy approved these changes
LGTM

2022-05-18 21:00 UTC, xin-hedera commented on hedera-mirror-rest/model/transactionWithEthData.js
> +   * Parses ethereumTransaction table columns into the transaction object
done

2022-05-18 21:05 UTC, xin-hedera approved these changes
approve to unblock

2022-05-18 21:12 UTC, matheus-dallrosa approved these changes

2022-05-18 21:14 UTC, steven-sheehy approved these changes

2022-05-18 21:21 UTC, Nana-EC approved these changes
Ship it :)

2022-05-18 21:22 UTC, merged