Persist node staking information
hashgraph/hedera-mirror-node pull request #3840
Opened 2022-05-23 18:05 UTC by steven-sheehy

**Description**:
* Add new `node_stake` table
* Add processing of new `NodeStakeUpdateTransaction`
* Cleanup `SqlEntityListenerTest`

**Related issue(s)**:

Fixes #3792

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-23 18:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +                rewardSum = previousRewardSum + rewardRate * (double) stake / stakeTotal / TINYBARS_IN_HBARS;
I implemented this differently than the HIP and services. Instead of using stakeStart and stakeTotalStart (e.g. previous values) I use the current values. I believe the HIP is incorrect and waiting on feedback on my [discussion](https://github.com/hashgraph/hedera-services/pull/3432#discussion_r878706046) item.

2022-05-26 02:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        return LocalDate.ofInstant(instant, ZONE_UTC).toEpochDay();
Should be `atStartOfDay().toEpochSecond(ZoneOffset.UTC)` to account for leap seconds, per Michael. Or we can remove epoch_day in favor of staking_period since the latter is now the time at midnight.

2022-05-26 03:54 UTC, Nana-EC requested changes
Suggestions and questions

2022-05-26 03:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        long stakeTotal = getStakeTotal(transactionBody);
Q: Why calculate here and iterate over `transactionBody.getNodeStakeList()` here only to do it again a few lines down?
Then in the for look we can sum the stake

```suggestion
        var stakeTotal = new AtomicLong(0L);
```

2022-05-26 03:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        return nodeStakeRepository.findByEpochDay(epochDay - 1L)
Q: As a defensive mechanism should we instead get the latest rows via sql query logic instead of passing in a time and being exposed to an off by 1 edge case?

i.e. add a `nodeStakeRepository.getPreviousStake()` that essentially gets all the nodes stakes from the maximum epochDay in the table?

2022-05-26 03:54 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    stake_rewarded bigint null,
Q: should we consider defaulting to `0` or does null imply non participation?

2022-05-26 13:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        long stakeTotal = getStakeTotal(transactionBody);
Because you have to have the total stake to calculate the reward sum inside the loop. It requires you to loop twice

2022-05-26 13:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        return nodeStakeRepository.findByEpochDay(epochDay - 1L)
If you did that you'd run the risk of not getting yesterday's stake but some stake before that. That would mean an incorrect calculation unless you verified it again locally. Verifying it locally would be a similar check as comparing epoch day so might as well do that check in the db.

2022-05-26 13:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    stake_rewarded bigint null,
This should probably be not null since it's in the proto. Default is unnecessary

2022-05-26 17:43 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        long stakeTotal = getStakeTotal(transactionBody);
Understood

2022-05-26 22:35 UTC, xin-hedera commented
no idea why the test case `EntityRecordItemListenerCryptoTest.cryptoTransferWithAlias` fails in CI but passes in local env.

2022-05-26 22:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +            }
this implements the same algorithm in the HIP, using a node's stake rewarded / the total stake rewarded as the ratio to get the reward of the period for the node.

However, as I mentioned, a node has a `minStake` and `maxStake`.

If the node's stake is less than `minStake`, it doesn't contribute to consensus, so there should be reward for the period.

If the node's stake i s more than `maxStake`, the weight of the node for consensus is as if the node only had `maxStake` stake. So the reward for the node shouldn't use the stake rewarded / total stake rewarded ratio. Both stake rewarded of the node and the total. stake rewarded for the period should be calculated taking into account every node's `minStake` and `maxStake`.

2022-05-27 00:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +            }
Umm, the main node will send us the actual stake after taking into account minstake and maxstake

2022-05-27 00:08 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +            }
We don’t have the other part stake not rewarded. Besides the HIP itself missed what I mentioned in the comment. We’ll have a discussion tmo

2022-05-28 02:57 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/addressbook/NodeStake.java
> +    private long stakingPeriod;
Added comment to clarify which staking period the values of the variables are in.

Note the above reflect what services current implementation passes out in the tx body. The comment in the protobuf is inaccurate.

2022-05-28 02:59 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +            nodeStakeRepository.setReward(epochDay - 1, nodeId, rewardRate, (long) rewardSum);
the node stake update tx has the reward rate for the previous staking period relative to epochDay (based on the consensus timestamp of the tx). that's why the reward rate and calculated reward sum are saved to the previous staking period.

2022-06-01 17:44 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public static final long NANOS_IN_DAY = 60 * 60 * 24 * 1_000_000_000L;
Maybe `Duration.ofDays(1L).toNanos()` would be a little bit better.

2022-06-01 21:16 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/addressbook/NodeStake.java
> +    public static class Id implements Serializable {
Hibernate requires a no arg constructor and setters.

2022-06-01 21:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public static final long NANOS_IN_DAY = 60 * 60 * 24 * 1_000_000_000L;
Adopted

2022-06-01 21:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +    public void updateTransaction(Transaction transaction, RecordItem recordItem) {
Adjusted primitives to not use var

2022-06-02 20:18 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2022-06-02 20:20 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +    private long getEpochDay(long timestamp) {
This needs to be removed

2022-06-03 00:30 UTC, steven-sheehy commented
I messed this up trying to re-sign old commits with my new swirlds labs GPG key. Will open a new PR.

2022-06-03 00:30 UTC, closed without merging