03772 handle stacking fields crud
hashgraph/hedera-mirror-node pull request #3845
Opened 2022-05-24 15:19 UTC by matheus-dallrosa

**Description**:
This PR adds the staking fields to the Contract and Entity tables, creates the mapping between protobuff classes and domain classes.

**Related issue(s)**:

Fixes #3772 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-25 18:08 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                        .satisfies(c -> assertThat(c.getStakePeriodStart()).isNotNull()),
I was thinking about also verifying if the `stakePeriodStart` is less than `now` and greater than `now - epsilon`.

2022-05-27 14:39 UTC, xin-hedera requested changes

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.59.3__add_staking_fields.sql
> +alter table contract add column decline_reward boolean not null default false;
version should be `V1.60.3`

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.59.3__add_staking_fields.sql
> +alter table entity_history add column stake_period_start bigint null;
also update v2 schema

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +        stakePeriodStart = null;
set stakePeriodStart to `-1` to indicate there is no stake period start here and other places for `clear`

the upsert sql will do a `coalesce(new, existing, default value if apply)`, so setting any such field to `null`  in domain object will end up having the previous value saved in db

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    }
remove, can't use mirrornode local time to determine staking period, we should always use the consensus timestamp of the tx instead.

also use the `getEpochDay` function I added to `Utility.java` in pr #3840

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    public void updateAccountId(EntityId accountId) {
change to override the setter `setStakedAccountId`

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        contract.setDeclineReward(transactionBody.getDeclineReward());
should set declineReward regardless of stakeId case

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        }
please use switch case. it's always possible to expand an oneof in the future to include more fields

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        contract.startNewStakingPeriod();
as commended in the domain class, always use transaction consensus timestamp to calc staking period

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        }
use switch case to make it easier to read.

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                        .setDeclineReward(false)
nit, in protobuf it's a primitive `boolean`, not necessary to set the default value for primitives
```suggestion
```

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                .transactionBody(b -> b.clearAutoRenewAccountId()
did you mean to clear staked account id? it's actually not necessary to clear it, since for oneof setting one field will change the case.

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +
need a test case with declineReward == true, can modify existing ones

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +    @EnumSource(value = PartialDataAction.class, names = { "DEFAULT", "ERROR" })
perhaps change your IDEA java format to not add spaces before and after `{ "DEFAULT", "ERROR" }`

2022-05-27 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                        .satisfies(c -> assertThat(c.getStakePeriodStart()).isNotNull()),
can customize consensus timestamp in the test case with a known consensus timestamp and epoch day pair, and pull the stakePeriodStart check into the `extraAssert`

2022-05-27 14:42 UTC, xin-hedera commented
please add / update integration test to verify correct values are persisted into db

2022-05-28 01:11 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.59.3__add_staking_fields.sql
> +alter table contract add column decline_reward boolean not null default false;
Done.

2022-05-28 01:15 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.59.3__add_staking_fields.sql
> +alter table entity_history add column stake_period_start bigint null;
Done.

2022-05-28 01:20 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +        stakePeriodStart = null;
Right, forgot about the upsert. Thanks.

2022-05-28 01:22 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    }
How can I add the function we haven't merged yet? 
Also, I literally got this line of code from the HIP.

2022-05-28 01:22 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    public void updateAccountId(EntityId accountId) {
Done.

2022-05-28 01:43 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    }
copy the function from the other PR. and resolve conflict if there's any when you merge yours to main.

there's no problem to use that in the HIP since the context is the main node. mirrornode can ingest such a transaction which reached consensus on day T at a very different time, for example, if a mirrornode is catching up, the time mirrornode ingests that transaction may be several days later.

2022-05-28 03:04 UTC, xin-hedera approved these changes
Approve to unblock since I'll be ooo.

2022-05-28 04:21 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        contract.setDeclineReward(transactionBody.getDeclineReward());
I did the change, but I believe it does not make a difference, since in the case that there is no staking it will be false.

2022-05-28 04:23 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        }
I really don't like switch statements. I changed imported the enums to make it easier to read.

2022-05-28 04:23 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        contract.startNewStakingPeriod();
Please, answer my question about that comment. Can you resolve this one so we can talk about this just on one comment?

2022-05-28 04:24 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                        .setDeclineReward(false)
Done.

2022-05-28 04:44 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +                .transactionBody(b -> b.clearAutoRenewAccountId()
No, I did not. I cleared the auto renew account id. If I leave the default from the builder `transactionBody.hasAutoRenewAccountId()` will return true, and I will get a NPE.

2022-05-28 05:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        contract.setDeclineReward(transactionBody.getDeclineReward());
DeclinedReward is orthogonal from staked account id / staked node id.

An account can be created with declineReward = true and no staked node id / staked account id set.

later a crypto update can just set staked account id without updating declineReward.

As a result the way the flag is handled here will end up with declineReward = false in db, instead of true

2022-05-28 05:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        }
I disagree

2022-05-31 13:04 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        }
I used static import to make it shorter, but I don't really like switches.

2022-05-31 13:18 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +
Done.

2022-05-31 13:37 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java
> +        setupForContractUpdateTransactionTest(withStakedNodeIdSet, t -> assertThat(t)
I never liked long function names

2022-05-31 19:23 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +            entity.setStakedNodeId(transactionBody.getStakedNodeId());
set the account back to null

2022-05-31 22:52 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    }
Done.

2022-06-01 19:28 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +        stakedAccountId = AccountIdConverter.INSTANCE.convertToDatabaseColumn(accountId);
Xin asked me to use the converter. I think depending on JPA is not a big deal, but I don't mind using `EntityId.of`.

2022-06-01 19:31 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.60.3__add_staking_fields.sql
> +alter table contract add column stake_period_start bigint null;
Done.

2022-06-01 19:31 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/GenericUpsertQueryGeneratorTest.java
> +                "  select\n" +
Removed. They were added by intellij.

2022-06-02 00:46 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    }
The logic was moved to the handlers. Done.

2022-06-02 00:47 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public AccountID accountId(long accountNum) {
I added this method, because you added a very similar  method in the same class. This method is only being used for testing purposes.

2022-06-02 01:04 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setReceiverSigRequired(false);
I added a few fields in the `RecordItemBuilder`. I haven't data to the `DomainBuilder`, because it is inside the commons module ( which I think it is wrong ), and because of that I would have to duplicate the logic to calculate the number of days since epoch.

2022-06-02 03:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public AccountID accountId(long accountNum) {
`RecordItemBuilder.accountId()` is useful because it automatically generates an ID whose sequence is managed by `RecordItemBuilder`. Not having to manage the uniqueness of IDs in tests is useful to have centralized. 

`RecordItemBuilder.accountId(long accountNum)` doesn't use `id()` so is just a wrapper around the proto builder. It doesn't make any sense in `RecordItemBuilder` as it's more of a static utility method. It's better to just use `AccountID.newBuilder().setAccountNum(id()).build()` or if you really want the util then make it a true utility in `TestUtils`.

2022-06-02 13:40 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +
The logic was moved to the handlers. Done.

2022-06-02 17:40 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.60.3__add_staking_fields.sql
> +alter table contract add column stake_period_start bigint null;
Done.

2022-06-02 17:44 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public AccountID accountId(long accountNum) {
Removed.

2022-06-02 18:02 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        if (isStakedNodeIdSet || transactionBody.hasDeclineReward()) {
Done.

2022-06-02 18:02 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandler.java
> +        if (isStakedNodeIdSet || transactionBody.hasDeclineReward()) {
Done.

2022-06-02 18:45 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        }
Done.

2022-06-02 19:46 UTC, steven-sheehy requested changes
You have a test failure

2022-06-02 19:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.60.3__add_staking_fields.sql
> +alter table if exists contract
It looks like we'll get this PR in first, so please bump this to V1.60.2 and I'll change the other PRs

2022-06-02 19:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +
These lines are unnecessary since we update stakePeriodStart after anyway. Same comment for other handlers.
```suggestion
```

2022-06-03 03:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
>  class ContractCreateTransactionHandler extends AbstractEntityCrudTransactionHandler<Contract> {
Completely missed updating CryptoCreateTransactionHandler

2022-06-03 03:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
>  class ContractCreateTransactionHandler extends AbstractEntityCrudTransactionHandler<Contract> {
Pushed a commit to resolve

2022-06-03 04:15 UTC, steven-sheehy approved these changes
LGTM

2022-06-03 14:47 UTC, merged