Add logs_bloom and gas_used to Blocks API
hashgraph/hedera-mirror-node pull request #3852
Opened 2022-05-25 13:56 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

- https://github.com/hashgraph/hedera-mirror-node/issues/3750

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-05-26 15:00 UTC, Nana-EC requested changes
Looking good.
Some minor suggestions

2022-05-26 15:00 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/viewmodel/blockViewModel.test.js
> +    logs_bloom: Buffer.from(new Array(256).fill(0)),
Code smell suggests
```suggestion
    logs_bloom: Buffer.from(Array.from({length: 256}).fill(0)),
```

2022-05-26 18:29 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    logs_bloom: Buffer.from(new Array(256).fill(0)),
alternatively, can be just `Buffer.alloc(256)`

2022-05-26 18:37 UTC, xin-hedera requested changes

2022-05-26 18:37 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - name: sequenceNumber
revert, `sequencenumber` is what we use for the query param name.

2022-05-26 18:37 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        logs_bloom:
add `nullable: true`, also add a regex to show the format is hex encoded 256-byte array with `0x` prefix

2022-05-26 18:37 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/blockViewModel.js
> +    this.logs_bloom = utils.toHexStringNonQuantity(recordFile.logsBloom);
logs_bloom in db can be:

- 256-byte array, hex encoded it and add `0x` prefix
- empty bytea, hex encode it as if it's a 256 byte 0s and add `0x` prefix
- null, return null

2022-05-27 15:54 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        logs_bloom:
You're missing the regex Xin noted. See `Alias` as an example

2022-05-27 15:54 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        logs_bloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Still all zeroes

2022-05-27 16:58 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/blockViewModel.js
> +    this.gas_used = recordFile.gasUsed;
for past blocks that importer hasn't backfilled gas and logs bloom, gasUsed will be the default value -1, so need to check if it's -1, show `null` instead

2022-05-28 03:03 UTC, xin-hedera submitted a review, later dismissed
just approve to unblock sine I'm off next week.

There are still unresolved comments.

2022-05-28 18:32 UTC, Nana-EC submitted a review, later dismissed

2022-05-30 00:21 UTC, steven-sheehy requested changes

2022-05-30 00:21 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/viewmodel/blockViewModel.test.js
> +    logs_bloom: Buffer.from(
Should have tests for `null` and empty byte array

2022-05-30 00:21 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/viewmodel/blockViewModel.test.js
> +    gas_used: 300000,
Should have a test for `-1`

2022-05-31 04:14 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/viewmodel/blockViewModel.test.js
> +    expect(new BlockViewModel(new RecordFile({logs_bloom: Buffer.alloc(0)})).logs_bloom).toStrictEqual('0x');
I'm honestly not sure if an empty bytea should be `0x` or `0x00000...`. In general, empty non-quantities should be `0x`. Also, padding zeros for `[]` would mean we could not differentiate it from `[0]`. But perhaps that's fine for bloom since it's just parity bits. However, in practice I don't think it matters since I checked production and `contract_log.bloom` is never null or empty, always having exactly 256 bytes. So the current approach should suffice.

2022-05-31 05:07 UTC, steven-sheehy approved these changes

2022-05-31 05:49 UTC, Nana-EC approved these changes

2022-05-31 06:44 UTC, merged