Add contract logs pagination
hashgraph/hedera-mirror-node pull request #3853
Opened 2022-05-25 14:30 UTC by ar-conmit

**Description**:
This PR adds pagination to contract logs
- Affected endpoints:
    - `contracts/{id}/results/logs`
    - `contracts/results/logs` 

**Related issue(s)**:

Fixes #3581 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-25 16:31 UTC, Nana-EC reviewed
1st re-review pass to address test issue highlighted

2022-05-25 16:33 UTC, Nana-EC commented
> > There is an edge case that makes an endless loop:
> > if we have a dataset of `timestamp=A` with `index=0,1,2,3,4,5` and query `logs?index=gt:2&timestamp=gte:A&index=lt:3&timestamp:lte:A&limit=3`
> > Result: order `ASC` -> `timestamp=A` & `Index=0,1,2` order `DESC` -> `timestmap=A` & `Index=5,4,3`
> > The generated `next` link for both results would be the same(as the query) `index=gt:2&timestamp=gte:A&index=lt:3&timestamp:lte:A&limit=3`
> > the union query looks like:
> > `lower` - index > 2 & timestamp = A `inner` - timestamp > A & timestamp < A `upper` - index < 3 & timestamp = A
> > so, the `lower` part matches `index=3,4,5` and the `upper` part matches `index=2,1,0`. It always finds the same match.
> 
> ~I don't think it can cause endless loop.~
> 
> ~1. when ordering `ASC`, the next link will return `timestamp=A, index=3,4,5`, then the next link will return empty response~ ~2. when ordering `DESC`, the next link will return `timestamp=A, index=2,1,0`, then the next link will return empty response~
> 
> I see the problem now, then we should convert the condition of `timestamp=gte:A` and `timestamp=lte:A` to `timestamp=A`

I think we should be rejecting such a query for now and suggesting the user simplify it
`logs?index=gt:2&timestamp=gte:A&index=lt:3&timestamp:lte:A&limit=3` should be `logs?index=gt:2&timestamp=gte:A&index=lt:3&limit=3`

2022-05-25 17:40 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  };
works for me

2022-05-26 08:58 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +  };
If there are more records to be fetched, the `next` link sometimes will include 2x timestamps with the same value and the above check will reject it which is not the best user experience.

I think the easiest way of preventing this endless loop is just to not sending a `next` link.
We will generate the `next` link and if its query params are identical to the requested ones, we should not return the next link

2022-05-27 02:16 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +  };
oh good catch. Then I'd suggest what I proposed at first, if we end up with `timestamp=lte:A&timestamp=gte:A`, update the `bound` object as if it was `timestamp=A`

2022-05-27 02:48 UTC, xin-hedera requested changes
looks good. just the open item regarding how to handle `timestamp=gte:A&timestamp=lte:A`

2022-05-27 02:48 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-logs-24-pagination-index-timestamp-range.spec copy.json
> +{
rename file remove the `copy` in the filename

2022-05-27 15:48 UTC, Nana-EC approved these changes
Looks good.
I'm unblocking the PR but would like a follow up ticket opened up to investigate the desired response over all since this can happen in other places.

I think we should reject and leave it on the user for now where there's no applicable subset.
We can internally resolve where the values match as done here and apply the logic to more endpoints.

2022-05-27 15:51 UTC, ar-conmit commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +      name: 'timestamp => 34 & timestamp < 34',
Agree, I am just testing the new function of overwriting the timestamp query params, not the whole flow.

2022-05-27 18:35 UTC, xin-hedera approved these changes
LGTM

2022-05-31 16:48 UTC, matheus-dallrosa approved these changes

2022-05-31 20:10 UTC, steven-sheehy approved these changes
LGTM. Just some leftovers in the openapi that you can address via your fee schedule PR or another followup.

2022-05-31 20:11 UTC, merged