Expose the ethereum hash in /api/v1/contracts/results
hashgraph/hedera-mirror-node pull request #3870
Opened 2022-05-30 15:57 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

- https://github.com/hashgraph/hedera-mirror-node/issues/3820

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-05-31 18:10 UTC, Nana-EC requested changes
Looking good.
Needs OpenAPI spec update but also can improve model exchange

2022-05-31 18:10 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +          hash: row.hash ? utils.toHexString(row.hash, true) : null,
Move this into the `ContractResultsViewModel`.
It can take a `ContractResult` model and a hash or a `EthereumTransaction` model

2022-05-31 18:10 UTC, Nana-EC commented on hedera-mirror-rest/service/contractService.js
> +        hash: cr.hash,
This is fine or you can return the `EthereumTransaction` model for scalability

2022-05-31 18:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-results-list-01-no-params.spec.json
> +        "hash": "0xfebbaa29c513d124a6377246ea3506ad917d740c21a88f61a1c55ba338fc2bb1",
Add to OpenAPI spec.
Note that is a hex encoded hash of x size and is only populated for Ethereum transaction case

2022-06-01 13:59 UTC, Nana-EC reviewed
LG. Waiting on a test failure in CI to be fixed then can signoff

2022-06-01 15:09 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Add `nullable: true`

2022-06-01 15:10 UTC, steven-sheehy commented
Test failure needs to be fixed

2022-06-01 18:29 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Will address

2022-06-01 18:29 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    this.hash = hash ? utils.toHexString(hash, true) : null;
Will address

2022-06-01 18:40 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    this.hash = hash ? utils.toHexString(hash, true) : null;
Fixed

2022-06-01 18:57 UTC, Nana-EC approved these changes

2022-06-01 19:01 UTC, steven-sheehy approved these changes
LGTM

2022-06-01 19:07 UTC, merged