Changing contract Id function getContractByIdOrAddressQuery to accept…
hashgraph/hedera-mirror-node pull request #3882
Opened 2022-06-02 14:23 UTC by mgoelswirlds

… entire contract id in the format shard.realm.num

Also adding integration tests for it.

**Description**:

**Related issue(s)**:
#3809

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-06 16:55 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +    },
Not sure what that means?

2022-06-06 16:55 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/contracts-19-contract-id-non-zero-realm-and-shard-not-found.spec.json
> +{
ok will change this.

2022-06-06 16:59 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/contracts-19-contract-id-non-zero-realm-and-shard-not-found.spec.json
> +{
ohh i think I get it.

2022-06-06 17:10 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +    },
`1.1.924569` is a valid entity id however adding it doesn't change the coverage of the test case and the function to be tested is not related to the ticket.

2022-06-06 18:12 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +    },
Got it. I was wondering what ```Instead, should add a test case to getContractByIdOrAddressQuery tests in this file``` meant.

2022-06-06 18:17 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +    },
i c. The test case for `getContractByIdOrAddressQuery` verifies the generated sql query matches the expectation. In case of querying by contract id, when there are non-zero shard/realm in the contract id, the encoded id should differ from the value if shard/realm were ignored. that way we can verify the bug is fixed.

2022-06-06 22:11 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/contracts-19-contract-id-non-zero-realm-and-shard-not-found.spec.json
> +{
Done.

2022-06-07 13:46 UTC, xin-hedera requested changes

2022-06-07 13:46 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-06-specific-id-not-found.spec.json
> +        "timestamp_range": "[987654000123456,]"
```suggestion
        "timestamp_range": "[987654000123456,)"
```

in integrationDomainOps.js we insert a left closed right open range `[)` contract into `contract` table. Otherwise, we insert it into the `contract_history` table.

2022-06-07 13:46 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/contractController.test.js
> +describe('getEncodedId', () => {
there is a test block for `getContractByIdOrAddressQuery` at line 288, should just add a spec with a nonzero shard/realm contractIdParam there.

2022-06-07 18:55 UTC, steven-sheehy submitted a review, later dismissed

2022-06-07 19:09 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-06-07 21:08 UTC, closed without merging