Add 0x prefix to Rosetta Account Alias
hashgraph/hedera-mirror-node pull request #3883
Opened 2022-06-02 17:02 UTC by edwin-greene

**Description**:
Add the 0x prefix to the Account Alias ed25519 public key string.

**Related issue(s)**:

Fixes #3855

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-06 21:04 UTC, edwin-greene commented on hedera-mirror-rosetta/app/domain/types/account_id.go
> +		return tools.SafeAddHexPrefix(hex.EncodeToString(a.alias))
I've added a change that will remove it.

2022-06-06 21:07 UTC, xin-hedera requested changes

2022-06-06 21:07 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/account_id.go
> +	alias, err := hex.DecodeString(tools.SafeRemoveHexPrefix(address))
I meant we should enforce the alias string passed in has the `0x` prefix. If there's no prefix we should return error.

2022-06-07 17:19 UTC, xin-hedera approved these changes
LGTM

2022-06-07 18:29 UTC, steven-sheehy approved these changes
LGTM

2022-06-08 14:08 UTC, merged