Support consistent block number in rosetta
hashgraph/hedera-mirror-node pull request #3915
Opened 2022-06-08 15:22 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #3819

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-09 21:40 UTC, steven-sheehy commented on charts/hedera-mirror-rosetta/templates/tests/pod.yaml
> +        - https://raw.githubusercontent.com/hashgraph/hedera-mirror-node/{{ .Values.test.githubRef }}/hedera-mirror-rosetta/scripts/validation/postman/rosetta-api-postman.json
This syntax won't work without templating. Instead revert and do something like

`regexReplaceAll "(\\d+\\.\\d+\\.\\d+(-\\w+)?)" (default .Values.test.githubRef  .Chart.AppVersion "v${1}"`

2022-06-09 22:43 UTC, steven-sheehy requested changes

2022-06-09 22:43 UTC, steven-sheehy commented on charts/hedera-mirror-rosetta/values.yaml
> +  githubRef:
```suggestion
  githubRef: ""
```

2022-06-09 23:41 UTC, xin-hedera commented on charts/hedera-mirror-rosetta/templates/tests/pod.yaml
> +        - https://raw.githubusercontent.com/hashgraph/hedera-mirror-node/{{ .Values.test.githubRef }}/hedera-mirror-rosetta/scripts/validation/postman/rosetta-api-postman.json
fixed

2022-06-09 23:41 UTC, xin-hedera commented on .github/workflows/charts.yml
> +          fi
moved to a separate step

2022-06-10 15:43 UTC, steven-sheehy commented on .github/workflows/charts.yml
> +            --helm-extra-set-args="${HELM_EXTRA_SET_ARGS}"
```suggestion
        run: ct install --config .github/ct.yaml --charts=charts/hedera-mirror --helm-extra-set-args="--set=global.image.registry=registry:5000 --set=global.image.tag=${IMAGE_TAG} --set=rosetta.test.githubRef=${GIT_REF}"
```

2022-06-10 16:28 UTC, steven-sheehy approved these changes

2022-06-10 16:35 UTC, merged