Add the Pulsar Client (dependency) to hedera-mirror-importer/pom.xml,…
hashgraph/hedera-mirror-node pull request #3926
Opened 2022-06-12 21:20 UTC by MarcKriguerAtHedera

… and use it to write a unit test for
publishing and reading new messages on two channels.

**Description**:

**Related issue(s)**:

Fixes #3925 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-13 03:00 UTC, steven-sheehy requested changes

2022-06-13 03:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +    private Producer producer2;
Producers should be scoped to a specific test and probably not a class variable.

2022-06-13 03:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +        client.close();
Use try-with-resources to close producers/consumers. Move client close to `@AfterEach`.

2022-06-14 00:16 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +            System.out.println("Message 2 received: " + data2);
Ah -- different repositories have different criteria.  (printlns were OK for test code in `swirds-platform`, just not for the main code.). I converted the two "useful" printf lines to "log.info" and eliminated the ones like the above.

2022-06-14 00:16 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +        }
Done.

2022-06-14 00:19 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +    private static final String PULSAR_BROKER_ROOT_URL = "pulsar://localhost:6650";
This was the one suggestion I could not get working (today).  I agree that having the test spin up a containerized pulsar instance (rather than passing/failing on whether or not the system is available) makes far more sense.  I will get back to this (and get the pulsar `testcontainers` to work) before merging this to the new destination branch.

2022-06-14 00:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +            assertTrue("bad message 1", data1.startsWith("Message on consistent topic"));
I had been thinking of using @Order (if needed) to guarantee the order, but I fully agree with you that it should be a single test for both producing and reading the messages, rather than two.  I have removed the producer-only test entirely.

2022-06-14 00:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +    private static final String TEMPORARY_TOPIC_NAME = "persistent://public/default/test-topic-temp-" + NOW.toString();
Done.

2022-06-14 00:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/pom.xml
> +            <version>${pulsar.version}</version>
Done.

2022-06-14 00:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +        }
Done.

2022-06-14 00:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +class PulsarTopicsTest {
I have created a new (long-term) [Issue](https://github.com/hashgraph/hedera-mirror-node/issues/3949) and a branch for it. (and this PR now uses that branch for its base).   @jasperpotts , @mgoelswirlds , and I will commit our work to that branch (until the proof of concept is complete and "deemed worthy" of getting merged into `main` .

2022-06-14 00:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +    private Producer producer2;
Done.

2022-06-14 00:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/pulsar/PulsarTopicsTest.java
> +        client.close();
Done (and done).

2022-06-14 00:36 UTC, steven-sheehy commented
Need to fix DCO

2022-07-11 21:36 UTC, closed without merging