Update staking field ingestion and show account staking fields in rest api
hashgraph/hedera-mirror-node pull request #3956
Opened 2022-06-15 21:41 UTC by xin-hedera

**Description**:

- Fix clearing staked account id
- Fix not merging declineReward, stakedAccountId, and stakedNodeId in importer
- Add maxStake, minStake, and stakeNotRewarded ingestion
- Add account staking fields to accounts rest api 

**Related issue(s)**:

Fixes #3774
Fixes #3955 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-15 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> -                contract.setStakedNodeId(-1L);
don't have to reset the other in create transaction handlers

2022-06-15 21:50 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.61.2__update_staking_tables.sql
> +  add column stake_not_rewarded bigint not null default -1;
need a default since we are adding not null columns to the table. so in rest we should show `-1` as `null` in response.

2022-06-15 22:00 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - evm_address
we need to have all fields in the `required` list because

`An object instance is valid against this keyword if every item in the [required] array is the name of a property in the instance.`

2022-06-17 14:54 UTC, steven-sheehy requested changes

2022-06-17 14:54 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +            is not currently staked to a node, then the value is -1
We should not expose internal sentinel values. CryptoGetInfo just doesn't set this field if not staked to a node so we should do similar and return null.

2022-06-17 15:15 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +            is not currently staked to a node, then the value is -1
will fix

2022-06-17 20:09 UTC, xin-hedera commented on hedera-mirror-rest/nodemon.json
> +  "ext": "js,json,mjs,yml"
add `yml` files so if the config or the openapi.yml changes when running with `npm run dev`, nodemon will reload, handy for visually looking at `http://localhost:5551/api/v1/docs` to validate the openapi spec changes

2022-06-18 15:10 UTC, steven-sheehy requested changes

2022-06-18 15:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
Sorry, looking again at HAPI I am realizing they return a timestamp for `stake_period_start` and we're returning a day number. I think to be consistent we should return a timestamp as well that has seconds but no nanos like "1652464579.000000000".

2022-06-18 16:28 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
Let me check HIP to make sure we don’t have the one period off issue. The current stake period start in db is actually the period before the one the account starts to get reward.

2022-06-18 20:17 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
Right, the timestamp should be the same as what HAPI query returns.

2022-06-20 15:34 UTC, steven-sheehy approved these changes
LGTM

2022-06-21 13:42 UTC, merged