Add a retention period
hashgraph/hedera-mirror-node pull request #3957
Opened 2022-06-15 22:52 UTC by steven-sheehy

**Description**:

* Add a retention job that periodically prunes historical data
* Add a `RetentionRepository.prune(long consensusTimestamp)` to most insert only tables
* Add delete permission to the `mirror_importer` database user for new installs
* Add missing history domain and repository classes
* Add missing repository tests and domain builders

**Related issue(s)**:

Fixes #3821

**Notes for reviewer**:
Still need to test against a mainnet copy.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-16 01:45 UTC, steven-sheehy commented on docs/database.md
> +`2147483647kB`.
Add a note about adding delete permission to `mirror_importer` for existing deployments.

2022-06-16 22:30 UTC, matheus-dallrosa commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/AbstractContract.java
> +@Data
are we going to need setters for everything?

2022-06-16 23:02 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/AbstractContract.java
> +@Data
It's a domain model, so setters are required for JPA and Jackson.

2022-06-16 23:31 UTC, matheus-dallrosa commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceFileRepository.java
> +    @Query("delete from AccountBalanceFile where consensusTimestamp <= ?1")
I believe this can be a native query as well.

2022-06-16 23:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceFileRepository.java
> +    @Query("delete from AccountBalanceFile where consensusTimestamp <= ?1")
Everything can be a native query. I went with hibernate query if it was possible as it's less characters.

2022-06-23 18:29 UTC, edwin-greene submitted a review, later dismissed
Comprehensive solution; looks great.

2022-06-23 23:06 UTC, xin-hedera requested changes
Looking good. just one nit and one nice to have improvement

2022-06-24 00:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/retention/RetentionJob.java
> +            log.warn("Skipping since database is empty");
Adjusted

2022-06-24 00:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/retention/RetentionJob.java
> +        public boolean hasNext() {
I don't think that's possible to do with the invariant that `hasNext()` should always be called before `next()` and we don't know if there's next until we've ran a database query.  I think the current logic is pretty clear and well-tested I'd rather not change it at this point.

2022-06-24 00:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/retention/RetentionJob.java
> +        public boolean hasNext() {
sounds good especially it has good test coverage

2022-06-24 00:39 UTC, xin-hedera approved these changes
LGTM

2022-06-24 00:56 UTC, merged