Fix exchange rate & fee schedule APIs
hashgraph/hedera-mirror-node pull request #3960
Opened 2022-06-19 15:13 UTC by steven-sheehy

**Description**:
* Fix exchange rate & fee schedule APIs by returning raw buffer
* Fix fee schedule & throttles persistence by treating partial success response codes as success
* Fix `s3client.test.js` `valid config with endpointOverride` always failing locally

**Related issue(s)**:

Fixes #3958

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-19 15:47 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/network-fees-02-order.spec.json
> +        "file_data": "0a280a0a08541a061a0440a8953a0a0a08061a061a0440a8aa330a0a",
Two odd length file chunks couldn't be properly loaded as hex. The fix is to shift one character on one to the other so they're both even length again.

2022-06-20 00:41 UTC, Nana-EC requested changes
LG.
Suggestion and potential missing migration

2022-06-20 00:41 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        var status = record.getReceipt().getStatus();
Does this need a migration?
Presumably there are some transactions that were incorrectly marked as a failure that we may have to go back and update.

2022-06-20 00:41 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/fileDataService.test.js
> +    file_data: Buffer.from('0a1008b0ea0110cac1181a0608a0a1d09306121008b0ea0110e18e191a0608b0bdd09306', 'hex'),
nit: use a shared method to 
```
const decode = (contents) => {
  return Buffer.from(contents, 'hex');
}
```

then

```suggestion
    file_data: decode('0a1008b0ea0110cac1181a0608a0a1d09306121008b0ea0110e18e191a0608b0bdd09306'),
```

2022-06-20 00:45 UTC, Nana-EC commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        var status = record.getReceipt().getStatus();
Scratch that. I was mixing this up with the status value used to set Result

2022-06-20 00:45 UTC, Nana-EC requested changes
Unblocking my previous change request

2022-06-20 00:46 UTC, Nana-EC approved these changes
Actually unblocking my previous change request

2022-06-20 00:56 UTC, xin-hedera approved these changes
LGTM

2022-06-20 15:06 UTC, merged