Internal error when retrieving contract result by ethereum transaction hash
hashgraph/hedera-mirror-node pull request #3971
Opened 2022-06-21 10:45 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #3952 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-21 18:58 UTC, steven-sheehy requested changes

2022-06-21 18:58 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> -      throw new Error('Transaction invariance breached');
We shouldn't remove this check since there are other scenarios like lookup by transaction ID that can fail. We only want to change the lookup by ethereum hash flow.

Instead, we should modify the ethereum transaction join to filter out transactions with status of WRONG_NONCE, order by consensus timestamp and limit by 1. That way this invariance can never be reached with ethereum hash flow since we're moving the check to the query.

2022-06-22 04:31 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> -      throw new Error('Transaction invariance breached');
What if there are transactions with WRONG_NONCE only and we filter them out, so we should return no transaction found for the given ethereum hash?

2022-06-22 19:04 UTC, Nana-EC requested changes
LG.
2 nits for improvement and a test improvement.

2022-06-22 19:04 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-17-transaction-hash-match-multiple-tx.spec.json
> +        "result": 22
To confirm that the 1st transaction is always taken you'd want to add a duplicate with a success result since that would not be filtered out

2022-06-23 05:44 UTC, steven-sheehy commented on hedera-mirror-rest/service/transactionService.js
> -      excludeTransactionResults
Please add some unit tests to transactionService.test.js for `getTransactionDetailsFromEthHash`.

2022-06-23 14:59 UTC, Nana-EC approved these changes
LGTM

2022-06-23 15:07 UTC, merged