Remove range restrictions on Parameters for Accounts Nfts
hashgraph/hedera-mirror-node pull request #3976
Opened 2022-06-22 20:28 UTC by edwin-greene

**Description**:
- Remove the restriction on range boundaries to allow parameters such as `primary=x&secondary<y` for Account Nfts, Contract Logs and Token Allowance endpoints.
- Refactor the AccountController to follow the design of the Token Allowance Controller.
- Refactor NftService to accept filters and generate the nft query rather than having the query generated by the AccountController.
- Update and add unit tests to AccountController test and NftService test.

**Related issue(s)**:

Fixes #3950

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-24 16:14 UTC, xin-hedera commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
>      }
is there a reason that you made the validation into three separate functions instead of just `validateBounds(primary, secondary)` into `baseController`?

also why the following validation is removed?

```
    for (const bound of [spenderBound, tokenIdBound]) {
      if (bound.hasBound() && bound.hasEqual()) {
        throw new InvalidArgumentError(`Can't support both range and equal`);
      }
    }
```

We shouldn't allow both `=` and any non-equal query filter for the same bound at all.

2022-06-24 16:30 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/tokenAllowanceController.test.js
> -    },
revert, it's not allowed to have both equal and non-equal filters

2022-06-24 17:46 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
>      }
Thanks for the clarification. I will restore the `Can't support both range and equal` check.

For having three separate functions instead of one, they had different error messages associated with the different types of validation. Do the granular details of the error messages matter or would "Unsupported Combination" work for all the validation errors?

If the details matter, for instance this message:
```
   if (!this.validateSecondaryBound(spenderBound, tokenIdBound)) {
       throw new InvalidArgumentError(
         `${constants.filterKeys.TOKEN_ID} without a ${constants.filterKeys.SPENDER_ID} parameter filter`
       );
    }
  ```
  
I could add the name of the bound (`SPENDER_ID` for example) to the Bounds class, and then the baseController could get the name of the Bound to be able to reference it in the message. How does that sound?

2022-06-27 14:46 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/controllers/tokenAllowanceController.test.js
> -    },
Thanks, I have reverted this change.

2022-06-27 14:47 UTC, edwin-greene commented on hedera-mirror-rest/controllers/accountController.js
> +          filter.operator === utils.opsMap.eq ? spenderIdInFilters.push(filter) : spenderIdFilters.push(filter);
Got it. I've added the break.

2022-06-27 14:47 UTC, edwin-greene commented on hedera-mirror-rest/controllers/accountController.js
> +    let upper = this.getAccountsUpperFilters(tokenIdBound, serialNumberBound);
Cool, I've changed them to const.

2022-06-27 14:52 UTC, edwin-greene commented on hedera-mirror-rest/controllers/accountController.js
> +  getPaginationLink(req, nftViewModels, bounds, limit, order) {
Thanks, I have added `getPaginationLink` to `baseController` and changed `accountController`, `tokenAllowanceController` and `contractController` to all use the new `getPaginationLink` method.

2022-06-27 14:52 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
>    }
Awesome, thanks. I have made this change.

2022-06-27 14:53 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
>      }
Got it. I've added the filterKey to the Bounds and in the event of a validation failure the filterKey name is now referenced in the error message.

2022-06-27 14:54 UTC, edwin-greene commented on hedera-mirror-rest/service/nftService.js
> +    }
I made this change, equals will now always be placed in an `in` clause.

2022-06-28 15:00 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/nftService.test.js
> +        params: [1, 20, 10, 30],
as mentioned in `nftService.js`, we should generate such a SQL query
```suggestion
            and spender in ($5,$6,$7)
            order by token_id desc,serial_number desc
            limit $2`,
        params: [1, 20, 10, 30, 15, 17, 22],
```

2022-06-29 15:45 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
>      };
Thanks, I have added the keys `primary` and `secondary`, which via a ripple effect simplified many functions.

2022-06-29 15:45 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +      primaryDbColumn: 'spender',
I have added `viewModelKey` and removed `boundKeys`.

2022-06-29 15:46 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |               | lt(e)               | Y       | Single occurrence only. Requires the presence of an **lt(e)** or **eq** **token.id** query | ?token.id=lte:X&serialnumber=lt:Y |
Fixed.

2022-06-29 15:46 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |               | gt(e)               | Y       | Single occurrence only. Requires the presence of an **gt(e)** or **eq** **token.id** query | ?token.id=gte:X&serialnumber=gt:Y |
Fixed.

2022-06-29 15:46 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |               | lt(e)               | Y       | Single occurrence only. Requires the presence of an **lt(e)** or **eq** **spender.id** query | ?spender.id=lte:X&token.id=lt:Y |
Fixed.

2022-06-29 15:46 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |               | gt(e)               | Y       | Single occurrence only. Requires the presence of an **gt(e)** or **eq** **spender.id** query | ?spender.id=gte:X&token.id=gt:Y |
Fixed.

2022-06-29 15:47 UTC, edwin-greene commented on hedera-mirror-rest/controllers/accountController.js
> +            throw new InvalidArgumentError(`Multiple range params not allowed for ${filter.key}`);
Good idea, I have used Bound.parse and removed this try/catch.

2022-06-29 15:47 UTC, edwin-greene commented on hedera-mirror-rest/service/nftService.js
> +    const spenderInCondition = !_.isEmpty(spenderIdInFilters) ? spenderIdInFilters.map((f) => f.value).join(',') : null;
Thanks, I have updated the query and the params.

2022-06-29 15:48 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/service/nftService.test.js
> +        params: [1, 20, 10, 30],
I have updated the tests to reflect the inclusion of the values in the params.

2022-06-29 17:36 UTC, xin-hedera requested changes
looking good. most are nits

2022-06-29 17:36 UTC, xin-hedera commented on hedera-mirror-rest/controllers/baseController.js
> +    if (!bounds.secondary.hasBound()) {
nit, should do

`const {primary, secondary} = bounds;`

and use `primary` / `secondary` everywhere

2022-06-29 20:31 UTC, edwin-greene commented on hedera-mirror-rest/controllers/baseController.js
> +      const viewModelKey = !_.isNil(primaryBound.viewModelKey) ? primaryBound.viewModelKey : primaryBound.filterKey;
Got it, I have made this update.

2022-06-29 20:31 UTC, edwin-greene commented on hedera-mirror-rest/controllers/baseController.js
> +      const viewModelKey = !_.isNil(secondaryBound.viewModelKey)
Fixed.

2022-06-29 20:32 UTC, edwin-greene commented on hedera-mirror-rest/controllers/baseController.js
> +    if (!bounds.secondary.hasBound()) {
Good idea, I have implemented this change.

2022-07-01 15:38 UTC, xin-hedera requested changes

2022-07-01 15:46 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      secondary: new Bound(constants.filterKeys.INDEX),
i see, that makes sense!

2022-07-01 15:47 UTC, xin-hedera approved these changes
LGTM!

2022-07-01 19:19 UTC, steven-sheehy approved these changes
LGTM

2022-07-01 20:06 UTC, merged