Add Reward Rate Start to Rest Api
hashgraph/hedera-mirror-node pull request #3980
Opened 2022-06-23 18:23 UTC by edwin-greene

**Description**:
Add the Node Staking `reward_rate_start` to the REST API 

**Related issue(s)**:

Fixes #3973 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-23 19:07 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
>          service_endpoints:
Does this sound like the best description?

2022-06-23 20:33 UTC, steven-sheehy approved these changes
LGTM

2022-06-23 23:22 UTC, xin-hedera requested changes

2022-06-23 23:22 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
>          service_endpoints:
need to clarify it's the total earned for the just ended staking period. Otherwise the description reads as the cumulative total for the node at the start of the current staking period.

2022-06-24 14:17 UTC, xin-hedera approved these changes

2022-06-24 14:34 UTC, steven-sheehy approved these changes

2022-06-24 16:36 UTC, merged