Run transaction via EvmTxProcessor
hashgraph/hedera-mirror-node pull request #3986
Opened 2022-06-24 14:34 UTC by IvanKavaldzhiev

Signed-off-by: Ivan Kavaldzhiev <ivankavaldzhiev@Ivans-MacBook-Pro-4.local>

**Description**:
A base branch for a PoC that will proove we can run transaction simulations via `EvmTxProcessor` that will serve as an entry point. Initially a mocked data will be used.

After the PoC is done, an EVM module encapsulating all of the needed logic, would be extracted. This module will be reused both in `hedera-node` and `mirror-node` projects.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-24 15:00 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/transaction/properties/SimulatedBlockMetaSource.java
> +package com.hedera.mirror.web3.transaction.properties;
We intend to have future REST APIs in this module so let's move all packages in this PR into `com.hedera.mirror.web3.evm` package.

```suggestion
package com.hedera.mirror.web3.evm.transaction.properties;
```

2022-06-27 14:30 UTC, shemnon reviewed
nice and small.

I wish there was a way to say where files are "sourced" from so we can see a diff from how it changed in the hedera branch.  However the only way I can think of is to have a first commit that is the original code, and that won't compile, so we would have to put broken steps in the compile chain.

2022-06-27 14:30 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigurationProperties.java
> +    public AccountID fundingAccount() {
This appears unused, and really only applies to consensus transactions. Consider removing it.

2022-06-27 14:30 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigurationProperties.java
> +    public boolean shouldEnableTraceability() {
Similarly this field is a consensus node feature flag, which I expect would trigger sidecar generation.  I don't think we will need this on mirror node side since the contents of the sidecar are meant to be the output of the call.

2022-06-27 14:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigurationProperties.java
> +    public AccountID fundingAccount() {
This property is used [here](https://github.com/hashgraph/hedera-services/blob/7ef6749d12c7de1e97f7f88be2e845dec45dc47c/hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java#L245) . It's used to determine the `miningBeneficiary`, but I believe it won't be essential property for the txn simulations indeed.

2022-06-29 03:13 UTC, steven-sheehy requested changes

2022-06-29 03:13 UTC, steven-sheehy commented on hedera-mirror-web3/pom.xml
> +            <version>22.4.1</version>
```suggestion
            <version>${besu.version}</version>
```

2022-06-29 03:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedPricesSource.java
> +public class SimulatedPricesSource {
Shouldn't this class and `OracleSimulator` have some interface that it implements that comes from services?

2022-06-29 03:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigurationProperties.java
> +public class ConfigurationProperties {
What will be the source of this data? If it's application config it should use Spring boot `@ConfigurationProperties` and use JSR 303 bean validation. Also, we should use Lombok `@Data` to reduce boilerplate and that would mean using standard getters and setters instead of a getter without a `get` prefix.

Or we can have it as an interface with services having one implementation and mirror node another. But I'd still like to use standard java bean syntax for the interface getters so we can generate that from fields.

2022-06-29 12:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedPricesSource.java
> +public class SimulatedPricesSource {
Ideally they will implement interfaces coming from the `evm-module` (which is not completely defined yet). I think we can start with concrete implementations on `mirror-node` side and then seeing what the similarities between these classes and the implementations in `hedera-node` are, will define easily the common interface contract inside the `evm-module`.

2022-06-29 12:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigurationProperties.java
> +public class ConfigurationProperties {
The source on mirror-node side would be a `*.properties` file, indeed. I think there will be an interface defined in the `evm-module`, which on `mirror-node` side would be implemented by this class and on `hedera-node` side by `GlobalDynamicProperties`.

2022-06-29 17:29 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedPricesSource.java
> +public class SimulatedPricesSource {
Looks like the practice from the platform team is `// FUTURE WORK This should move to an interface when evm-module is complete`

2022-06-29 23:12 UTC, steven-sheehy requested changes

2022-06-29 23:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/EvmConfigProperties.java
> +@ConfigurationPropertiesScan
Remove this line, we configure this elsewhere

2022-06-29 23:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/EvmConfigProperties.java
> +@ConfigurationProperties(prefix = "evm")
The standard mirror node properties share common prefixes
```suggestion
@ConfigurationProperties("hedera.mirror.web3.evm")
```

2022-06-29 23:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/EvmConfigProperties.java
> +    int maxGasRefundPercentage;
private scope for both fields and set defaults in code. That ensures unit tests work and doesn't require a Spring context loaded.

2022-06-29 23:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/resources/evm.properties
> +evm.maxGasRefundPercentage=20
We use yaml for our properties in mirror node. And this file is in the wrong location to be picked up by Spring Boot. There's already an existing `src/main/resources/application.yml` for this. But here I recommend you delete this file and move defaults into the `EvmConfigProperties`

2022-06-29 23:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/EvmConfigProperties.java
> +public class EvmConfigProperties {
Config and properties are a bit redundant. We usually just name it as prefix + "properties".
```suggestion
public class EvmProperties {
```

2022-06-29 23:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/EvmConfigProperties.java
> +@ConfigurationProperties(prefix = "evm")
Eventually, we'll need this added to `docs/configuration.md` but we can probably save that for later.

2022-06-30 07:04 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/TransactionProcessingResult.java
> +//    public ContractFunctionResult toGrpc() {
I think we won't need EvmFnResult at all, that's why I had it commented, but now it's deleted.

2022-06-30 13:24 UTC, steven-sheehy approved these changes
LGTM

2022-07-01 16:36 UTC, Nana-EC approved these changes
LG. 
License years are off but non blocking and can be addressed in future PR

2022-07-01 16:36 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/execution/HederaTracer.java
> + * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2018 - 2022 Hedera Hashgraph, LLC
```

2022-07-01 16:36 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/execution/EvmTxProcessor.java
> + * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2018 - 2022 Hedera Hashgraph, LLC
```

2022-07-01 16:36 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/exception/ValidationUtils.java
> + * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2018 - 2022 Hedera Hashgraph, LLC
```

2022-07-01 16:36 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/exception/InvalidTransactionException.java
> + * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2018 - 2022 Hedera Hashgraph, LLC
```

2022-07-01 16:36 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/ethereum/EthTxSigs.java
> + * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2018 - 2022 Hedera Hashgraph, LLC
```

2022-07-02 00:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/HederaMessageCallProcessor.java
> + * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
I noticed too but they're from services so no point in changing here. Better to be in sync with services.

2022-07-11 21:36 UTC, merged