Add a dev Kubernetes deployment
hashgraph/hedera-mirror-node pull request #4012
Opened 2022-06-27 20:00 UTC by tolorukooba

**Description**: This PR adds Kubernetes deployment for mirror-node dev. The PR does the following;

- Adds a Dev namespace to the cluster.
- Adds a helm release for dev deployment.
- Adds a git repository for deployment.
- Adds a sealed secret for dev.

2022-06-27 22:01 UTC, steven-sheehy requested changes

2022-06-28 18:49 UTC, tolorukooba commented on clusters/preprod/dev/helmrelease.yaml
> +      version: '0.57.2'
fixed

2022-06-28 18:50 UTC, tolorukooba commented on clusters/preprod/dev/helmrelease.yaml
> +        HEDERA_MIRROR_MONITOR_PUBLISH_SCENARIOS_PINGER_TPS: "1"
Brad suggested a TPS of 0.5

2022-06-28 18:50 UTC, tolorukooba commented on clusters/preprod/dev/gitrepository.yaml
> +kind: GitRepository
Removed

2022-06-28 18:50 UTC, tolorukooba commented on clusters/preprod/dev/helmrelease.yaml
> +        kind: GitRepository
switched!

2022-06-28 18:50 UTC, tolorukooba commented on clusters/preprod/dev/helmrelease.yaml
> +    rest:
done!

2022-06-28 18:51 UTC, tolorukooba commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgBCpluoc9CQJ4iYv7LRAm8rlzDPaNhd767d4o2MvNdwdj6A6Bbz9OfShM1BEGAL+N1bKBtd2IlFjABZzyxL+Hfdky/d11JpkKNjUuMV65lDiAeTnYXosA03omiMs1TfHHnAk4z2gQw038b8FCC8M8H8Rw5UlUOs4YD/0mI0ztMJzRzfGkflmQ
fixed!

2022-06-29 01:01 UTC, steven-sheehy commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgBCpluoc9CQJ4iYv7LRAm8rlzDPaNhd767d4o2MvNdwdj6A6Bbz9OfShM1BEGAL+N1bKBtd2IlFjABZzyxL+Hfdky/d11JpkKNjUuMV65lDiAeTnYXosA03omiMs1TfHHnAk4z2gQw038b8FCC8M8H8Rw5UlUOs4YD/0mI0ztMJzRzfGkflmQ
When `redis.enabled=true` it means to use the Kubernetes based Redis statefulset. Since you've provisioned Google Memorystore you should set `redis.enabled=false` but still populate the auth and host like you have.

2022-06-29 01:08 UTC, steven-sheehy commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgBCpluoc9CQJ4iYv7LRAm8rlzDPaNhd767d4o2MvNdwdj6A6Bbz9OfShM1BEGAL+N1bKBtd2IlFjABZzyxL+Hfdky/d11JpkKNjUuMV65lDiAeTnYXosA03omiMs1TfHHnAk4z2gQw038b8FCC8M8H8Rw5UlUOs4YD/0mI0ztMJzRzfGkflmQ
In the acceptance tests I just see the below now:
```yaml
                nodes:
                - accountId: 0.0.3
                - accountId: 0.0.4
                - accountId: 0.0.5
                - accountId: 0.0.6
                - accountId: 0.0.7
```
This is not valid config. You should just remove the nodes section entirely so it uses the address book.

2022-06-29 01:09 UTC, steven-sheehy commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgBCpluoc9CQJ4iYv7LRAm8rlzDPaNhd767d4o2MvNdwdj6A6Bbz9OfShM1BEGAL+N1bKBtd2IlFjABZzyxL+Hfdky/d11JpkKNjUuMV65lDiAeTnYXosA03omiMs1TfHHnAk4z2gQw038b8FCC8M8H8Rw5UlUOs4YD/0mI0ztMJzRzfGkflmQ
In the acceptance tests I just see the below now:
```yaml
                nodes:
                - accountId: 0.0.3
                - accountId: 0.0.4
                - accountId: 0.0.5
                - accountId: 0.0.6
                - accountId: 0.0.7
```
This is not valid config. You should just remove the nodes section entirely so it uses the address book.

2022-06-29 01:10 UTC, steven-sheehy commented on clusters/preprod/dev/helmrelease.yaml
> +    rest:
Forgot to remove it from the secret so now it's duplicated in both.

2022-06-29 16:40 UTC, tolorukooba commented on clusters/preprod/dev/helmrelease.yaml
> +    rest:
done!

2022-06-29 16:41 UTC, tolorukooba commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgBCpluoc9CQJ4iYv7LRAm8rlzDPaNhd767d4o2MvNdwdj6A6Bbz9OfShM1BEGAL+N1bKBtd2IlFjABZzyxL+Hfdky/d11JpkKNjUuMV65lDiAeTnYXosA03omiMs1TfHHnAk4z2gQw038b8FCC8M8H8Rw5UlUOs4YD/0mI0ztMJzRzfGkflmQ
fixed!

2022-06-29 16:41 UTC, tolorukooba commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgBCpluoc9CQJ4iYv7LRAm8rlzDPaNhd767d4o2MvNdwdj6A6Bbz9OfShM1BEGAL+N1bKBtd2IlFjABZzyxL+Hfdky/d11JpkKNjUuMV65lDiAeTnYXosA03omiMs1TfHHnAk4z2gQw038b8FCC8M8H8Rw5UlUOs4YD/0mI0ztMJzRzfGkflmQ
done!

2022-06-29 16:41 UTC, tolorukooba commented on clusters/preprod/dev/helmrepository.yaml
> +apiVersion: source.toolkit.fluxcd.io/v1beta1
fixed!

2022-06-29 16:44 UTC, steven-sheehy commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgAXW3jnQdInYk3jFkISw4es8I1jtYITEC39k05DS3FlO0aWGJlsgQxCAaAkBQ2oCTVtx8DsWkFliVofGevhkpcG4oqosNO6ZtMDOkSJXW15E6IiDGxuuVE04dQENJeRpQWsqBuft36WKyMIIqBt6VjwHZIU64UsgyyXvLJg2BigYzFx43Vvg3
You accidentally deleted the acceptance operatorId

2022-06-29 21:05 UTC, tolorukooba commented on clusters/preprod/dev/sealed-secret.yaml
> +    values.yaml: AgAXW3jnQdInYk3jFkISw4es8I1jtYITEC39k05DS3FlO0aWGJlsgQxCAaAkBQ2oCTVtx8DsWkFliVofGevhkpcG4oqosNO6ZtMDOkSJXW15E6IiDGxuuVE04dQENJeRpQWsqBuft36WKyMIIqBt6VjwHZIU64UsgyyXvLJg2BigYzFx43Vvg3
resolved!

2022-06-29 21:59 UTC, steven-sheehy approved these changes
LGTM

2022-06-29 22:00 UTC, merged