BlockMetaSource implementation
hashgraph/hedera-mirror-node pull request #4018
Opened 2022-06-28 07:29 UTC by IvanKavaldzhiev

Signed-off-by: Ivan Kavaldzhiev <ivankavaldzhiev@Ivans-MacBook-Pro-4.local>

**Description**:
Provide mirror-node specific BlockMetaSource implementation that loads correct block meta data based on the Postgre DB latest state.

**Related issue(s)**: #4128 

Fixes #4008 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-29 03:52 UTC, steven-sheehy requested changes

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/BlockMetaSourceProvider.java
> +    }
Use constructor injection and Lombok
```suggestion
@Singleton
@RequiredArgsConstructor
public class BlockMetaSourceProvider {

    private final RecordFileRepository recordFileRepository;
```

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/BlockMetaSourceProvider.java
> +        return recordFile.map(file -> Hash.fromHexString(file.getFileHash())).orElseThrow(
Believe you want the running hash, not the file hash.

```suggestion
        return recordFile.map(file -> Hash.fromHexString(file.getHash())).orElseThrow(
```

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/BlockMetaSourceProvider.java
> +                () -> new InvalidParametersException(String.format("No record file with index: %d", blockNo)));
This exception was intended for json-rpc parameters and should probably not be used outside that context. Recommend we create an abstract `EvmException` (here or in evm module) and create a standard invalid exception that extends that for use everywhere.

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/BlockMetaSourceProvider.java
> +        final var latestRecordFile = recordFileRepository.findLatest().orElseThrow(() -> new RuntimeException("No record file available."));
Should use a custom exception that is within an `EvmException` hierarchy.

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/BlockMetaSourceProvider.java
> +        return new SimulatedBlockMetaSource(gasLimit, latestRecordFile.getIndex(), Instant.ofEpochSecond(latestRecordFile.getConsensusStart()));
We store consensus timestamps as a special bigint encoding of seconds + nanos.

```suggestion
        return new SimulatedBlockMetaSource(gasLimit, latestRecordFile.getIndex(), Instant.ofEpochSecond(0, latestRecordFile.getConsensusStart()));
```

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +    protected final Instant consTimestamp;
Why protected? Are we expecting classes to inherit? If not, use private.

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +    }
All the constructors and getters can be removed if we use lombok `@Value` as is our standard.

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +        return Optional.of(Wei.ZERO);
Move to static to avoid the `Optional` allocation.

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findByIndex(@Param("index") long index);
```suggestion
    @Query("select r from RecordFile r where r.index = ?1")
    Optional<RecordFile> findByIndex(long index);
```

2022-06-29 03:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findLatest();
Not sure if you're implementing things to this level yet, but both of these repositories should leverage `@Cacheable` backed by caffeine for now and potentially Redis, if needed. 

This method could be cache for 1 second while findByIndex can be cache much longer since it's static data.

2022-06-29 11:11 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +        return Optional.of(Wei.ZERO);
I think we should keep the `Optional` type, so that we are compatible with the `BlockValues` interface return type for this method:

```
default Optional<Wei> getBaseFee() {
    return Optional.empty();
  }
```

2022-06-29 11:14 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findLatest();
I liked the idea with `Caffeine` cache and I implemented it. I think we can also use this approach for the `CodeCache` implementation that will keep the runtime bytecode of contracts.

However, I used this approach only for `findByIndex`. I have a concern about `findLatest`. If we set a cache there for 1 second, what guarantees us that during this 1 second a new record file might not get ingested by the mirror-node and the cache doesn't contain stale data?

2022-06-29 23:33 UTC, steven-sheehy requested changes

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +@EntityScan("com.hedera.mirror.web3.evm")
Remove this line since there are no JPA entities within that folder and we configure entity scanning elsewhere already.

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public Caffeine caffeineConfig() {
Use package access for class and methods in configuration classes as is mirror node standard.
```suggestion
   Caffeine caffeineConfig() {
```

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findLatest();
Depends on how much tolerance for stale block data there is. There's always going to be some risk of stale data due to the asynchronous nature of importer writing data and web3 reading data. Thus part way through an EVM execution the block could change. Hence why not sure if it matters that the findLatest is exact since it can never be atomic due to the above. 

If we're concerned about 1s then we could do 500ms, etc. Point is we probably need to cache these common queries so they can scale to higher number of requests

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/exception/InvalidException.java
> +public class InvalidException extends EvmException {
InvalidException sounds like the exception itself is invalid. Perhaps `ProviderException`?

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    @Cacheable(value = "record_file", key = "record_index")
This is putting all cache entries under the same key. By default it will use all args as cache key.
```suggestion
    @Cacheable(cacheNames = "record_file.index", cacheManager = EvmConfiguration.CACHE_MANAGER_10M, unless = "#result == null")
```

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    @Bean
Since we'll probably have multiple different caches, recommend you provide it a distinct name and reference that name in the `@Cacheable`.
```suggestion
    @Bean(CACHE_MANAGER_10M)
```

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        return Caffeine.newBuilder().expireAfterAccess(10, TimeUnit.MINUTES);
Move this into cacheManager since each cache manager will have a different caffeine config.

Also, need to limit the max size of this cache to avoid blowing up memory.

2022-06-29 23:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findByIndex(long index);
We should add tests for all new functionality, unless the plan is to do that at a later time after the PoC period?

2022-06-29 23:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +        return Optional.of(Wei.ZERO);
I meant keep the `Optional` but move `Optional.of(Wei.ZERO)` to a static variable since it's immutable and repeated in each instance. Just an optional performance optimization (no pun intended).

2022-06-30 02:32 UTC, Nana-EC reviewed
Add licenses to the new files.
Agree with Steven on the caching and testing items.

2022-06-30 02:32 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +import com.github.benmanes.caffeine.cache.Caffeine;
nit: Missing license header

2022-06-30 02:32 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +    Bytes difficultyBytes = UInt256.ZERO;
nit: order
```
    Optional<Wei> baseFee = Optional.of(Wei.ZERO);
    final Instant consTimestamp;
    Bytes difficultyBytes = UInt256.ZERO;
    final long gasLimit;
    final long number;
    long timestamp = consTimestamp.getEpochSecond();
```

2022-07-02 00:47 UTC, steven-sheehy requested changes

2022-07-02 00:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public Caffeine caffeineConfig() {
I meant for every method and the class itself, not just the one above.

2022-07-02 00:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        caffeine.expireAfterAccess(500, TimeUnit.NANOSECONDS).maximumSize(1);
nanoseconds!? I think you meant milliseconds since 500ns is too small to have any effect and probably more overhead in invoking the cache methods.

2022-07-02 00:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        caffeineCacheManager.setCaffeine(caffeine);
You can't share the `Caffeine` instance between two different managers. Right now both will have the same config.

```suggestion
   CacheManager cacheManager10M() {
        var caffeine = Caffeine.newBuilder().expireAfterAccess(10, TimeUnit.MINUTES).maximumSize(10000);
        CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
        caffeineCacheManager.setCaffeine(caffeine);
```

2022-07-02 00:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public static final String CACHE_MANAGER_500NS = "500NS";
These are global spring bean names so should name them with a better prefix.

```suggestion
    public static final String CACHE_MANAGER_10MIN = "cacheManager10min";
    public static final String CACHE_MANAGER_500MS = "cacheManager500ms";
```

2022-07-02 00:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/SimulatedBlockMetaSource.java
> +@RequiredArgsConstructor
nit: `@RequiredArgsConstructor` redundant when used with `@Value`

2022-07-02 00:47 UTC, steven-sheehy commented on pom.xml
> +        <swirlds.version>0.26.2</swirlds.version>
Duplicates

2022-07-26 14:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findByIndex(long index);
As we agreed let's make tests after we have a more finished version of the PoC.

2022-07-26 14:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public Caffeine caffeineConfig() {
We can't make the class having package access since we refer to the `CACHE_MANAGER_10MIN` and `CACHE_MANAGER_500MS` constants in the `RecordFileRepository`

2022-07-26 19:44 UTC, steven-sheehy requested changes

2022-07-26 19:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +
Unused bean
```suggestion
```

2022-07-26 19:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +                Caffeine.newBuilder().expireAfterAccess(500, TimeUnit.MILLISECONDS).maximumSize(1);
This cache will never get updated and return stale data if we have at least one request per 500ms. Same for `cacheManager10MIN`.
```suggestion
                Caffeine.newBuilder().expireAfterWrite(500, TimeUnit.MILLISECONDS).maximumSize(1);
```

2022-07-26 21:43 UTC, shemnon approved these changes

2022-07-27 16:01 UTC, steven-sheehy approved these changes

2022-07-27 16:02 UTC, merged