Light-weight updater implementation
hashgraph/hedera-mirror-node pull request #4019
Opened 2022-06-28 12:55 UTC by IvanKavaldzhiev

**Description**:
Provide light-weight `mirror-node` `HederaWorldUpdater` implementation, that does not use `TransactionalLedgers` nor `SigImpactHistorian`

**Related issue(s)**:

Fixes #4005 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-29 19:53 UTC, shemnon reviewed
I have mixed feelings about including the AccountID, ContractID, and TokenID regime in the library, since the EVM only addresses them as `Address`es and doesn't distinguish the types. But at some level we will need to separate them, as seen in WorldStateTokenAccount.

Can it be done with just `Address` reasonably?

2022-06-29 19:53 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/AliasesResolver.java
> +    //TODO implementation to be provided in separate PR
```suggestion
    // FUTURE WORK implementation to be provided in separate PR
```

2022-06-29 19:53 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedEntityAccess.java
> +    public boolean isExtant(AccountID id) {
Should we used `Address` instead of `AccountID`s and put the conversion task on the consensus node?  That may remove the need for the AliasResolver in the evm-module.

(also, are the protobufs already loaded into Mirror node? I'm assuming so.  If not we should definitely use Address).

2022-06-29 19:53 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +        final var address = aliasesResolver.resolveForEvm(addressOrAlias);
Why do we need to resolve the alias?  I thought we settled on one and only one address for each account? eg if it's not deleting the one and only address it's not operating on a hedera account?

This would then mean we could remove aliasResolver too.

2022-06-29 19:53 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +        return null;
If this is a stub that will be improved later I think a FUTURE WORK comment would be warranted.

2022-06-30 00:41 UTC, steven-sheehy requested changes

2022-06-30 00:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/AddressUtils.java
> +
Add license header to all files

2022-06-30 00:41 UTC, steven-sheehy commented on pom.xml
> +        <swirlds.version>0.26.2</swirlds.version>
Duplicate with other properties in file

2022-06-30 00:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +    private SimulatedEntityAccess entityAccess;
This has injected dependencies but is not a bean annotated with `@Named` or `@Singleton`. If it is to be a singleton bean how would the non-thread safe data structures fields be protected? Regardless, please use Lombok generated constructors to set required, non-defaulted fields.

2022-06-30 00:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +    protected Map<Address, UpdateTrackingLedgerAccount<Account>> updatedAccounts = new HashMap<>();
Until now, mirror node has been almost completely stateless with no mutable fields inside business services and all state stored within the database. In services, there have been issues with not clearing state between requests in some in corner cases. Is it possible to refactor so that mirror-node specific business logic classes are stateless and all state is passed along in a request/context object?

2022-06-30 15:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +        final var address = aliasesResolver.resolveForEvm(addressOrAlias);
An account can have both a `mirror` address and an `alias` address. If we pass the `mirror` address of an account, we should check if the account has an `alias` address to use instead. We use this method to delete self-destructs [here](https://github.com/hashgraph/hedera-services/blob/a3c16b2f5796a8b8dae8b2b6c8fa9fe217778351/hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java#L313) . 

If we already have resolved address in consensus nodes as self-destructs we might get rid of the AliasResolver inside the module. As far as I saw we only add self-destruct addresses [here](https://github.com/hashgraph/besu/blob/bc172b285bd49e45d54918bfd091a22595f3128c/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/SelfDestructOperation.java#L64) and it is the recipient address that is added. In `buildInitialFrame()` inside `CreateEvmTxProcessor`/`CallEvmTxProcessor`/`CallLocalEvmTxProcessor` we can resolve the `final Address to` argument and pass a valid address before we reach the module. My assumption is we won't include these 3 classes inside the evm module, so this idea might work. What do you think?

2022-07-01 06:47 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +        final var address = aliasesResolver.resolveForEvm(addressOrAlias);
It seems this `recipient` address is set also in a couple of places internally in `Besu` and so it won't be always possible to resolve it to `alias` in advance.

2022-07-01 14:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +    protected Map<Address, UpdateTrackingLedgerAccount<Account>> updatedAccounts = new HashMap<>();
We should keep track of these current state changes (even though they won't commit and change the original state) somehow. It should be either on `mirror-node` side in a way similar to `hedera-node`, or it could be done internally in the `evm-module` itself. We can't get these changes from the `PostgreDB` nor reuse `hedera-node` functionality, since they are current and specific for the transaction simulation. 

So we should come up with a common approach for handling these changes. Probably keeping track of these state changes inside the module with some default implementation classes might be the best approach? If we need a specific data from the original state we could provide it with a Supplier that fetches data from the PostgreDB.

2022-07-26 10:58 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +        newContractNumId = contractRepository.findLatestNum().get() + 1;
This number seems to be affected only by new contract creations. I use current `hedera-node` implementations as a reference point (in this case [HederaWorldState](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java).

We need to see the max ContractID currently stored in the state (Postgre DB), so that we can construct a new available ContractID that is sequential.

2022-07-26 11:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/AddressUtils.java
> +public final class AddressUtils {
As we agreed with @steven-sheehy , we first would build a working prototype that looks like a whole connected working module and then we can build some tests on top of it. 

Writing tests in each small PR that implements a small part of the module might introduce some double work and unneeded effort, since we can change a given implementation or modify it entirely and this would need rewriting a lot or all of the tests.

2022-07-26 21:45 UTC, steven-sheehy approved these changes

2022-07-26 21:45 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +    private CodeCache codeCache;
nit: Mark as final and use constructor to set via `@RequiredArgsConstructor`. I'm not sure if this is a service bean or constructed per request.

2022-07-26 21:45 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +        }
Can't you just do subtraction to calculate?

```suggestion
        newContractNumId = newContractNumId - numAllocatedContractIds;
        numAllocatedContractIds = 0;
```

2022-07-26 22:17 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/store/contracts/WorldStateTokenAccount.java
> +    public static final long TOKEN_PROXY_ACCOUNT_NONCE = -1;
I think it should be zero.  _currently_ there is no easy way to poll the nonce, and there are no ways a call to the token will consume the nonce.  But those could evolve to be made visible.  On the consensus nodes it defaults to zero.

2022-07-26 22:17 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/store/contracts/WorldStateAccount.java
> +        return Hash.EMPTY;
This should be the calculated value (keccak256).  It may never be used (as it was designed for ethereum's patricia tries) but we should honor the contract in case it does become relevant.

2022-07-26 22:17 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/store/contracts/WorldStateAccount.java
> +        return 0;
We should query and populate this.

2022-07-27 06:09 UTC, Nana-EC approved these changes

2022-07-27 06:12 UTC, Nana-EC approved these changes
LG, pending addressing nonce items Danno called out.
If not easy mods or this blocks other items maybe we can address those in a follow up

2022-07-27 07:19 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/store/contracts/WorldStateTokenAccount.java
> +    public static final long TOKEN_PROXY_ACCOUNT_NONCE = -1;
This is artificially introduced nonce, since token accounts don't have nonce. On consensus nodes we use this -1 value to distinguish between a regular account and a token account (e.g. [KeyActivationUtils.isToken](https://github.com/hashgraph/hedera-services/blob/881a84a2df76260d2e95bcb9d00af6dbe38ff0f7/hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtils.java#L83) If we set here the default value as 0 we will loose the possibility to distinguish between the two type of accounts.

2022-07-28 00:27 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/store/contracts/WorldStateAccount.java
> - * Copyright (C) 2018 - 2022 Hedera Hashgraph, LLC
Shouldn't remove header.

2022-07-28 21:48 UTC, steven-sheehy approved these changes
Approving in case you want to address issues in follow up PRs since this PR has been up for awhile.

2022-07-28 21:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +@Singleton
Actually looking at service's world updaters, this is not a global singleton but an ephemeral helper for a particular contract execution. I don't think it should be a bean as a result. If it was a bean, all of the mutable fields would need to be made thread safe.

2022-07-28 21:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +                entityRepository.findAccountNonceByAddress(address.toArray()).orElseThrow();
It would be very inefficient to get the balance from the db, then get the nonce, then get the deleted status, etc. In my opinion, the `SimulatedEntityAccess` should be backed by an `Entity` domain loaded from the db to respond to any getter without loading from the db multiple times.

2022-07-28 21:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +    @Query(value = "select ethereumNonce from entity where evmAddress = ?1 and deleted <> true", nativeQuery = true)
As this is a native query and not JPQL, you need to use native column names.
```suggestion
    @Query(value = "select ethereum_nonce from entity where evm_address = ?1 and deleted <> true", nativeQuery = true)
```

2022-07-29 08:09 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/SimulatedUpdater.java
> +                entityRepository.findAccountNonceByAddress(address.toArray()).orElseThrow();
I agree with you. There would be a separate task to provide EntityAccess implementations (static and mutable) and we can address this optimisation there.

2022-07-29 08:10 UTC, merged