Add Random Generate Transaction
hashgraph/hedera-mirror-node pull request #4023
Opened 2022-06-28 17:50 UTC by edwin-greene

**Description**:
HIP 351 Add Random Generate Transaction persistence.

**Related issue(s)**:

Fixes #3969 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-28 21:52 UTC, steven-sheehy requested changes

2022-06-28 21:52 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/UtilRandomGenerate.java
> +    private Long consensusTimestamp;
Should use primitive type

2022-06-28 21:52 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/UtilRandomGenerate.java
> +    private int pseudorandomNumber;
This can be nullable.

```suggestion
    private Integer pseudorandomNumber;
```

2022-06-28 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +        utilRandomGenerate.setPseudorandomBytes(DomainUtils.toBytes(transactionRecord.getPseudorandomBytes()));
Only one of these two will be populated. Need to check entropy enum to see which and only set the one populated while the other stays as null.

2022-06-28 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    consensus_timestamp bigint primary key not null,
Should not set indexes in create. There should be a separate pk addition in the create index sql.

2022-06-28 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var utilRandomGenerate = domainBuilder.utilRandomGenerate().get();
Should probably add a few here.

2022-06-28 21:56 UTC, xin-hedera requested changes
need a `EntityRecordItemListener` test

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionType.java
> +    UTILRANDOMGENERATE(52,  EntityOperation.NONE);
```suggestion
    RANDOMGENERATE(52,  EntityOperation.NONE);
```

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .pseudorandomNumber(random.nextInt());
```suggestion
                .pseudorandomNumber(random.nextInt(Integer.MAX_VALUE));
```
when range > 0, the main nodes should generate a random integer in `[0, range)`

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +
license

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +        utilRandomGenerate.setPseudorandomBytes(DomainUtils.toBytes(transactionRecord.getPseudorandomBytes()));
need to check the oneof and set the fields correspondently, refer to  https://github.com/hashgraph/hedera-mirror-node/blob/692e66cf1ef6d3f3cc8877dd850033713a3aeabb/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java#L91-L101

should log a warning if `entropyCase` is `ENTROPY_NOT_SET`

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.62.0__util_random_generate.sql
> +    pseudorandom_number integer null
nit, fix alignment like other sql files

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return new Builder<>(TransactionType.UTILRANDOMGENERATE, builder);
set the entropy oneof in transaction record, can refer to `contractCreate` in this file.

2022-06-28 21:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(utilRandomGenerateRepository.findAll()).contains(utilRandomGenerate);
```suggestion
        assertThat(utilRandomGenerateRepository.findAll()).containsOnly(utilRandomGenerate);
```

2022-06-28 22:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +class UtilRandomGenerateTransactionHandler implements TransactionHandler {
Should be named after the HAPI transaction not the domain:

```suggestion
class RandomGenerateTransactionHandler implements TransactionHandler {
```

2022-06-29 14:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +        long consensusTimestamp = recordItem.getConsensusTimestamp();
should only process successful transactions

2022-06-29 21:10 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return new Builder<>(TransactionType.UTILRANDOMGENERATE, builder);
I tried to set the `entropyCase` but I found that there was no direct mutator method for it in `TransactionRecord`, rather it seems to be set alongside the pseudoRandom value:

```
        public Builder setPseudorandomBytes(ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            } else {
                this.entropyCase_ = 19;
                this.entropy_ = value;
                this.onChanged();
                return this;
            }
        }
 ```

2022-06-29 21:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return new Builder<>(TransactionType.UTILRANDOMGENERATE, builder);
Right, just set the pseudorandomNumber of pseudorandomBytes and it will get set automatically.

2022-06-29 21:43 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/UtilRandomGenerate.java
> +    private Long consensusTimestamp;
Thanks! I have fixed this.

2022-06-29 21:43 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/UtilRandomGenerate.java
> +    private int pseudorandomNumber;
I see, I have fixed it.

2022-06-29 21:44 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +        utilRandomGenerate.setPseudorandomBytes(DomainUtils.toBytes(transactionRecord.getPseudorandomBytes()));
I have added functionality around the entropyCase enum. Now one of the values (random number or random bytes) will stay null.

2022-06-29 21:45 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    consensus_timestamp bigint primary key not null,
Thanks. I changed this file and the v.2.0.3 index file, please double check that I have them correct.

2022-06-29 21:49 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var utilRandomGenerate = domainBuilder.utilRandomGenerate().get();
I added another randomGenerate here. In other areas I have the invalid randomGenerate (where the transaction was unsuccessful), but here it seems that there are only two possible cases, the random number and the random bytes.

2022-06-29 21:50 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionType.java
> +    UTILRANDOMGENERATE(52,  EntityOperation.NONE);
Thanks, I have fixed this naming here and in other places.

2022-06-29 21:50 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +
Good catch! I've added the license.

2022-06-29 21:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +        utilRandomGenerate.setPseudorandomBytes(DomainUtils.toBytes(transactionRecord.getPseudorandomBytes()));
Ok, I see now. I have added functionality to examine the `entropyCase`.

2022-06-29 21:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.62.0__util_random_generate.sql
> +    pseudorandom_number integer null
Thanks, I have fixed the alignment.

2022-06-29 21:53 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return new Builder<>(TransactionType.UTILRANDOMGENERATE, builder);
Great thanks. I have updated this to invoke setPseudorandomNumber or setPseudorandomBytes.

2022-06-29 21:53 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(utilRandomGenerateRepository.findAll()).contains(utilRandomGenerate);
I have changed it to containsOnly.

2022-06-29 21:53 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandlerTest.java
> +import static org.mockito.Mockito.verify;
Thanks for spotting this, I have fixed the formatting.

2022-06-29 21:54 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandlerTest.java
> +        int randomNumber = new SecureRandom().nextInt(range);
I removed the random.

2022-06-29 21:54 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/UtilRandomGenerateTransactionHandler.java
> +class UtilRandomGenerateTransactionHandler implements TransactionHandler {
I see ok, I have renamed this and other classes/methods.

2022-06-29 22:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +                    record.getReceipt().getStatus());
we don't want to log such failed transactions which are not an indicator of network problem. For example, a user can submit a transaction with the same transaction id to multiple nodes around the same time. Ideally, only once such will succeed, and all others will fail with `DUPLICATE_TRANSACTION`, and this is the expected behavior of the main network.

2022-06-29 22:25 UTC, xin-hedera requested changes

2022-06-29 22:25 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return range < 0 ?
if `range < 0`, the transaction should fail with ` INVALID_RANDOM_GENERATE_RANGE = 324` and you need to set  `TransactionReceipt.status`.

2022-06-29 22:25 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandlerTest.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
```suggestion
```

2022-06-29 22:25 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandlerTest.java
> +        var recordItem = recordItemBuilder.randomGenerate(-1).build();
as commented in `RecordItemBuilder`, a `-1` range should cause the transaction to fail. to test `entropy not set`, customize the record using `.record(r -> r.clearEntropy())`

2022-06-29 22:25 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandlerTest.java
> +                .receipt(r -> r.setStatus(ResponseCodeEnum.ERROR_DECODING_BYTESTRING))
with the changes recommended in `RecordItemBuilder`, customize `status` in receipt will be no longer needed.

2022-07-01 15:27 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +                    record.getReceipt().getStatus());
I have adjusted this to not log any messages if the transaction failed with a status of `DUPLICAT_TRANSACTION`. I still have it logging a warning if the transaction fails with any other status. Does that sound good?

2022-07-01 15:28 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return range < 0 ?
I added some new tests, one for a negative range and one for `INVALID_RANDOM_GENERATE_RANGE`. I made the setting of the receipt status in the handler test; but I see that it could also be set in the `RecordItemBuilder`, and there may be precedents for setting the status in either place. Let me know if it looks good as is, or if I should fine tune it some more.

2022-07-01 15:29 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandlerTest.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
Thanks, I have removed this.

2022-07-01 15:29 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandlerTest.java
> +        var recordItem = recordItemBuilder.randomGenerate(-1).build();
I have added new tests for -1 and for clearEntropy.

2022-07-01 15:30 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandlerTest.java
> +                .receipt(r -> r.setStatus(ResponseCodeEnum.ERROR_DECODING_BYTESTRING))
Cool ok, I have removed this test and added others in its place.

2022-07-01 15:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +
As coded here, it will not log a warning for a negative range. But, should it log for negative range?

2022-07-01 15:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +                    record.getReceipt().getStatus());
no, we shouldn't log it at all

2022-07-01 15:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return range < 0 ?
I mean in in `RecordItemBuilder`, you should do:

```java
    return range < 0 ? transactionBodyBuilder.status(ResponseCodeEnum. INVALID_RANDOM_GENERATE_RANGE) : ...
```

2022-07-01 15:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return range < 0 ?
Up until now, we haven't put error scenarios in `RecordItemBuilder`. Can't we just do this in the one test that needs to test this?

2022-07-01 16:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +                    record.getReceipt().getStatus());
Got it I have removed the log statement.

2022-07-01 16:44 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +
Got it, I have removed this log statement.

2022-07-01 16:44 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +                log.warn("Transaction Record missing entropy case at consensus timestamp {}", consensusTimestamp);
Thanks, I have revised the warning message.

2022-07-01 16:45 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +)
Got it I have added the comment line.

2022-07-01 16:45 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerRandomGenerateTest.java
> +class EntityRecordItemListenerRandomGenerateTest extends AbstractEntityRecordItemListenerTest {
Thanks, I have renamed the class.

2022-07-01 17:12 UTC, steven-sheehy requested changes

2022-07-01 17:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/RandomGenerateTransactionHandler.java
> +        if (!recordItem.isSuccessful() || range < 0) {
Remove range check. Only consensus nodes should validate input. There's already a `INVALID_RANDOM_GENERATE_RANGE` response code so this would be dead code in production.

```suggestion
        if (!recordItem.isSuccessful()) {
```

2022-07-01 19:05 UTC, xin-hedera approved these changes
LGTM

2022-07-01 19:11 UTC, steven-sheehy approved these changes
LGTM 🥂

2022-07-01 19:13 UTC, merged