Add max memo length property for Monitor transactions
hashgraph/hedera-mirror-node pull request #4080
Opened 2022-07-08 17:20 UTC by edwin-greene

Added maxMemoLength property to reduce the size of memo fields in the monitor test transactions.

**Related issue(s)**:

Fixes #3659

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-08 22:08 UTC, xin-hedera requested changes

2022-07-08 22:08 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java
> +    @Min(13) // 13 is the length of the memo timestamp
```suggestion
    @Min(13) // 13 is the length of the memo timestamp
    @Max(100)
```

services limit transaction memo to be 100 bytes, longer memo will cause failure.

2022-07-08 22:08 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenario.java
> +                memoMessage.substring(0, maxMemoLength - TIMESTAMP_LENGTH) : memoMessage;
revert

2022-07-08 22:08 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenario.java
> +        return System.currentTimeMillis() + memo;
```suggestion
        var memo = System.currentTimeMillis() + " " + this.memo;
        return StringUtils.truncate(memo, properties.getMaxMemoLength());
```

2022-07-08 22:08 UTC, xin-hedera commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/generator/ConfigurableTransactionGeneratorTest.java
> +                                .hasSize(MAX_MEMO_SIZE))
should also test `memo` is intact when it's less than `maxMemoSize`

2022-07-11 19:47 UTC, edwin-greene commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenario.java
> +                memoMessage.substring(0, maxMemoLength - TIMESTAMP_LENGTH) : memoMessage;
I have reverted this change.

2022-07-11 19:47 UTC, edwin-greene commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenario.java
> +        return System.currentTimeMillis() + memo;
Great simplification, I have made this change.

2022-07-11 19:48 UTC, edwin-greene commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java
> +    @Min(13) // 13 is the length of the memo timestamp
Got it, I have added the `@Max(100)`

2022-07-11 19:48 UTC, edwin-greene commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/generator/ConfigurableTransactionGeneratorTest.java
> +                                .hasSize(MAX_MEMO_SIZE))
Good idea, I have added a new test where the memo will not be truncated.

2022-07-11 19:53 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenario.java
> +    private static final int TIMESTAMP_LENGTH = 13;
Hah, Xin beat me to it.

2022-07-11 20:17 UTC, steven-sheehy approved these changes
LGTM

2022-07-11 20:45 UTC, xin-hedera approved these changes
LGTM

2022-07-11 20:46 UTC, merged