HIP-513 download sidecar files
hashgraph/hedera-mirror-node pull request #4106
Opened 2022-07-14 16:05 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #3970 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-14 20:42 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +
Is this needed? As it is set to `Collections.emptyList()` on line 72. 

Will it potentially get set to null somewhere?

2022-07-14 21:01 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +
It will be null if using buildInternal() generated by Lombok and there is no .sidecar() to set it.

2022-07-14 21:22 UTC, edwin-greene submitted a review, later dismissed
Looks good to me!

2022-07-14 22:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +//        contractStateChanges.hasSize(count);
thanks. changed it to assert the table is empty. Believe your PR will change it back to check the state changes are persisted.

2022-07-15 13:31 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.retry.multiplier`                     | 2                              | Used to generate the next delay for backoff
thanks, will fix

2022-07-15 17:56 UTC, steven-sheehy requested changes

2022-07-15 17:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloader.java
> +                .doOnNext(recordItem -> recordItem.setSidecarRecords(records.get(recordItem.getConsensusTimestamp())))
This will create an `ArrayList` for every record item regardless if it's associated with a sidecar, due to how multimaps work.

2022-07-15 18:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloader.java
> +        var pendingSidecarDownloads = new ArrayList<PendingSidecarDownload>();
prefer using the wrapper with the list to preserve the order of sidecar files

2022-07-15 19:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/sidecar/SidecarProperties.java
> +
added

2022-07-15 19:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/sidecar/SidecarProperties.java
> +    private boolean enabled = true;
changed to `false`

2022-07-15 19:41 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/SidecarFile.java
> +    @javax.persistence.Id
fixed

2022-07-15 19:41 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/SidecarFile.java
> +    }
adopted

2022-07-15 19:41 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordFile.java
> +    }
adopted

2022-07-15 20:16 UTC, steven-sheehy approved these changes
LGTM

2022-07-15 20:31 UTC, edwin-greene approved these changes
Looks good!

2022-07-15 21:02 UTC, Nana-EC approved these changes
LG. 
Non blocking consideration for not null in `count` and `size` for db table

2022-07-15 21:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.63.0__sidecar.sql
> +  count          int null,
Why `null` vs `not null default 0`?

2022-07-15 21:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.63.0__sidecar.sql
> +  size           int null,
Same question above for size.

2022-07-15 21:07 UTC, merged