HIP-513 Add Persistence for Sidecar Data
hashgraph/hedera-mirror-node pull request #4107
Opened 2022-07-14 16:25 UTC by edwin-greene

**Description**:
HIP-513 Add persistence for Sidecar records.

- Add runtime bytecode to Contract and Contract History.
- Set Contract initcode and runtime bytecode from Sidecar records.
- Add ContractActions persistence.
- Populate Contract State Changes from Sidecar instead of Transaction/Contract Function Result.

**Related issue(s)**:

Fixes #3972

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-14 22:09 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityListener.java
> +
Missing a test for this, I will add.

2022-07-14 22:16 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (transactionBody.getInitcodeSourceCase().equals(FILEID)) {
It is strange that the transactionBody is determining the initcodeSourceCase, should the Sidecar record have something that is determining this?

2022-07-18 23:19 UTC, steven-sheehy requested changes

2022-07-18 23:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                    }
Revert. With sidecar the child record should have a bytecode sidecar directly associated with its timestamp, so no need to fill in from parent.

2022-07-18 23:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                .toList();
Avoid use of streams in the hot path. Use an enhanced for loop or forEach.

2022-07-18 23:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            contract.setRuntimeBytecode(runtimeBytecodes.get(0).toByteArray());
```suggestion
            contract.setRuntimeBytecode(DomainUtils.toBytes(runtimeBytecodes.get(0)));
```

2022-07-19 00:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                .filter(b -> contract.getId() == b.getContractId().getContractNum()).toList();
There should be exactly one bytecode sidecar per contract create and the contract ID should always match. The contract ID is only necessary in case it's a migration since migrations are attached to a random transaction en masse. So think a warning log might be appropriate instead of dropping the entry.

2022-07-19 15:20 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return TransactionSidecarRecord.newBuilder();
Thanks for the clarification. I am working through these changes. I've ran into a case where the Contract Id for the StateChange is different than the Contract Id for the ContractAction. Such that there may be a need for those methods to be public. Or, maybe the StateChange and ContractAction settings in this test aren't pertinent to the test case? 

Here is the test in question: 
`ContractResultServiceImplTest`:
```
void create2ContractIdWorkaroundCall(long shard, long realm, long num, long resolvedNum, long expectedNum) {
        var invalidContractId = ContractID.newBuilder()
                .setShardNum(shard)
                .setRealmNum(realm)
                .setContractNum(num)
                .build();
        var evmAddress = ContractID.newBuilder().setEvmAddress(fromBytes(toEvmAddress(invalidContractId))).build();
        var expectedId = EntityId.of(expectedNum, CONTRACT);
        var resolvedId = EntityId.of(resolvedNum, CONTRACT);

        var transaction = domainBuilder.transaction().customize(t -> t.entityId(expectedId)).get();
        var contractActions = ContractActions.newBuilder()
                .addContractActions(recordItemBuilder.contractAction(evmAddress));
        var contractStateChanges = recordItemBuilder.contractStateChanges(invalidContractId).build();
        var recordItem = recordItemBuilder.contractCall()
                .record(r -> {
                    r.getContractCallResultBuilder().getLogInfoBuilder(0).setContractID(invalidContractId);
                    r.getContractCallResultBuilder().removeLogInfo(1);
                })
                .sidecarRecord(s -> {
                    s.get(0).setStateChanges(contractStateChanges);
                    s.get(1).setActions(contractActions);
                })
                .build();
```

2022-07-19 15:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return TransactionSidecarRecord.newBuilder();
It's not necessary to add contract actions to this test. This test validates the workaround for a service bug that only impacts contract logs on testnet. See the [javadoc](https://github.com/hashgraph/hedera-mirror-node/blob/dc77621a3e15ac9102f68f0db29c4ddc9fb0ebe8/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L234) for more details.

2022-07-19 21:24 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        if (transactionBody.getInitcodeSourceCase().equals(FILEID)) {
Thanks. I have implemented a failback solution. As a part of removing the .stream() I have also combined the iteration to gather the runtime bytecode and the initcode at the same time.

2022-07-19 21:26 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return TransactionSidecarRecord.newBuilder();
Got it, I have altered this class to remove the public methods and I have altered the tests to no longer need them.

2022-07-19 21:26 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +//        }
Thanks for catching this. I have removed it.

2022-07-19 21:29 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        return sidecarRecords.stream()
Awesome thanks. I have removed the usage of the streams, and in trying to reduce looping through the sidecar data multiple times I combined the lists returned to the `ContractResultServiceImpl` into a tuple.

2022-07-19 21:29 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .caller(entityId(ACCOUNT))
Thanks I have fixed this.

2022-07-19 21:29 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .recipientContract(entityId(CONTRACT))
I have switched it to account and removed the other recipient settings.

2022-07-19 21:30 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .resultDataType(1)
Thanks I have changed it to use the enum.

2022-07-19 21:30 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    contractAction.setCaller(entityIdService.lookup(action.getCallingContract()));
Got it, I have changed these to use `Entity.of`

2022-07-19 21:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractAction.setConsensusTimestamp(recordItem.getConsensusTimestamp());
Cool I have moved the getConsensusTimestamp call to outside of the loop.

2022-07-19 21:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractAction.setResultData(DomainUtils.toBytes(action.getOutput()));
Thanks for figuring this out. I have added some handling to conditionally set the `ResultData` based on those three values.

2022-07-19 21:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    log.warn("Invalid recipient case for contract action: {}", action.getRecipientCase());
I have changed it to throw to match the throw above it.

2022-07-19 21:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                    }
Got it, I have reverted this change.

2022-07-19 21:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                .toList();
I have removed the streams.

2022-07-19 21:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            contract.setRuntimeBytecode(runtimeBytecodes.get(0).toByteArray());
Thanks for spotting this, I have switched it to DomainUtils.

2022-07-19 21:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +                .filter(b -> contract.getId() == b.getContractId().getContractNum()).toList();
Got it, I have implemented it as you described.

2022-07-19 21:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityListener.java
> +
Looks like I will need to figure out how to add tests back for this.

2022-07-19 21:47 UTC, xin-hedera requested changes

2022-07-19 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +
add `runtime_bytecode` to `contract` and `contract_history`

2022-07-19 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            if(!action.getError().isEmpty()) {
prefer `switch (action.getResultDataCase()) ...` for protobuf oneof

2022-07-19 21:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +
Thanks for spotting that. I have added it.

2022-07-19 21:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            if(!action.getError().isEmpty()) {
Sounds good, I have implemented the switch.

2022-07-20 17:22 UTC, steven-sheehy requested changes

2022-07-20 17:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var sidecarInitCodes = new ArrayList<ByteString>();
We should also avoid allocations as much as possible in the hot path. Here you're allocating 3 lists just to get the single init code and single runtime bytecode associated with this contract create. 

The helper methods in `RecordItem` like `getContractBytecode()` should be removed in favor of just iterating over the sidecars inline here as my [example](https://github.com/hashgraph/hedera-mirror-node/pull/4107#discussion_r923922648) did. The helpers don't improve CPU performance since you're still iterating over the items the same number of times, but they incur increased memory usage. Inline you can short circuit the loop if you trust that consensus nodes won't send more than one bytecode entry with migration=false per timestamp.

2022-07-20 17:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                com.hedera.mirror.common.domain.contract.ContractStateChange contractStateChange =
Use var to partially hide the ugliness of the similar type.
```suggestion
                var contractStateChange = new com.hedera.mirror.common.domain.contract.ContractStateChange();
```

2022-07-20 17:22 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        return Pair.of(contractActions, contractStateChanges);
`Pair` is almost always a code smell and should be avoided. Avoid list allocations in the hot path and move iteration logic to `ContractResultServiceImpl`. This `RecordItem` helper method shouldn't be necessary.

2022-07-20 17:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            processContractStateChanges(contractStateChanges, contractResult);
Should process state changes outside of `processContractResult()` like actions since state changes are not contained within the contract result. Can return the `ContractResult` object from this method for use in populating state change fields.

2022-07-20 17:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +            transactionSidecarRecords = defaultTransactionSidecarRecords();
We shouldn't have default sidecar records since only 3 transaction types will have them in reality. Better to opt in, then opt out.

2022-07-20 17:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                    r.get(1).setActions(contractActions(contractId));
Should just add to the sidecar list instead of assuming a certain sized list is already present.

```suggestion
                .sidecarRecord(contractStateChanges(contractId))
                .sidecarRecord(contractActions(contractId));
```

2022-07-20 20:59 UTC, xin-hedera requested changes

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +            if (sidecarRecord.hasBytecode() && contractId == sidecarRecord.getBytecode().getContractId().getContractNum()) {
`contractId` is a long which encodes `shard`, `realm`, and `num`, we can't compare it with just the `ContractNum` from protobuf `ContractID`.

can add an `equals(ContractID)` method to AbstractContract, in which it compares shard, realm, and num.

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +
still need to add `runtime_bytecode` to `contract_history`

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        if (contractActions.size() > 0) {
should remove the `size() > 0` condition so here it also asserts the `contract_action` table is empty when it should be.

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +            listAssert.extracting(ContractAction::getValue).containsOnly(contractActions.get(0).getValue());
It's always better if you can customize the contract action in the protobuf with hardcoded value, then just construct the expected list of domain `ContractAction`s and pass it to `assertContractActions`.

If infeasible, the suggestion is move this block before the `assertThat` line. also instead of building individual lists, just build the list of expected domain `ContractAction`s, then the `assertThat` can be chained with the last assertion to be `.containsExactlyInAnyOrderElementsOf(expectedContractActions)`

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        }
same comments for `assertContractActions` apply

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .sidecarRecord(s -> s.get(0).clearSidecarRecords())
shouldn't the method in `RecordItemBuilder.java` be named `sidecarRecords` instead of `sidecarRecord`?

Also the customizer here clears the protobuf field `sidecar_records` of the `TransactionSidecarRecord` object while leave the `TransactionSidecarRecord` object in the `sidecarRecords` list, is it intended?

2022-07-20 20:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ContractActionRepositoryTest.java
> +        assertThat(contractActionRepository.findAll()).contains(contractAction);
```suggestion
        assertThat(contractActionRepository.findAll()).containsOnly(contractAction);
```

2022-07-20 21:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +
It should already be handled since we create contract_history like contract

2022-07-21 21:02 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            contract.setRuntimeBytecode(runtimeBytecodes.get(0).toByteArray());
I see, it should really be fixed now.

2022-07-21 21:03 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        for(int i = 0; i < contractBytecodes.size(); i++) {
Thanks, I have changed my Intellij so the spacing should all be correct now.

2022-07-21 21:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    contractAction.setCallerType(EntityType.ACCOUNT);
Thanks I have added the `setCaller` method and simplified the switch statement.

2022-07-21 21:06 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        var sidecarInitCodes = new ArrayList<ByteString>();
I see. I have removed the helper methods inside `RecordItem` and have implemented the suggestion to trust the consensus nodes and not iterate through all the ContractBytecodes after a matching bytecode has been found.

2022-07-21 21:07 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                com.hedera.mirror.common.domain.contract.ContractStateChange contractStateChange =
Thanks I have switched it to a var.

2022-07-21 21:07 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        return Pair.of(contractActions, contractStateChanges);
I've removed this method from `RecordItem` and moved the iteration to `ContractResultServiceImpl`

2022-07-21 21:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            processContractStateChanges(contractStateChanges, contractResult);
Thanks. I've moved this outside of `processContractResult()`.

2022-07-21 21:08 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +            transactionSidecarRecords = defaultTransactionSidecarRecords();
Sounds good, I have removed the default sidecar records.

2022-07-21 21:09 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                    r.get(1).setActions(contractActions(contractId));
That makes sense. Thanks, I have changed it to add to the sidecar list rather than editing a default list.

2022-07-21 21:10 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +            if (sidecarRecord.hasBytecode() && contractId == sidecarRecord.getBytecode().getContractId().getContractNum()) {
Thanks, I have added a `equalsContractID` method to `AbstractContract`.

2022-07-21 21:11 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        if (contractActions.size() > 0) {
I've placed the list assert outside of the if statement for if the contract actions exist.

2022-07-21 21:13 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +            listAssert.extracting(ContractAction::getValue).containsOnly(contractActions.get(0).getValue());
I think I understand, I've refactored this test to take an expected contract action from what is known from the RecordFileBuilder.contractAction and then use those values in the assertion. Please double check this new version and let me know if I got it similar to what you intended.

2022-07-21 21:15 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        }
This one was a little different, as it was a test case taken from when ContractStateChanges were a part of the ContractResult. The values for the slots are randomized from the RecordFileBuilder; so creating an expected state change object (similar to the expected contract actions object) seemed to not save much complexity. Let me know, and I can take another look at this after getting your feedback on the changes I made to `assertContractActions`.

2022-07-21 21:17 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .sidecarRecord(s -> s.get(0).clearSidecarRecords())
Thanks, I have changed this to `sidecarRecords` and instead of clearing the sidecar records within the `TransactionSidecarRecord` I have changed it to just remove that element of the list.

2022-07-21 21:18 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/ContractActionRepositoryTest.java
> +        assertThat(contractActionRepository.findAll()).contains(contractAction);
Thanks I have changed this to `containsOnly`

2022-07-22 15:41 UTC, steven-sheehy requested changes

2022-07-22 15:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
For migrated state changes, they won't have an associated contract result. Also, not sure if it's possible to get state changes and no contract result. I believe it's not possible, but either way we should actually change state changes to get info from `RecordItem` and not `ContractFunctionResult`. We don't need the special `lookup(contractResult.getContractId(), stateChange.getContractId())` logic and can just use `stateChange.getContractId()`.
```suggestion
        processContractStateChanges(contractStateChanges, recordItem);
```

2022-07-22 15:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var contractStateChanges = new ArrayList<ContractStateChange>();
There's still list allocations here. Why can't we just have a `processContractStateChange(contractStateChange, recordItem)` inside the loop that processes a single state change? Same thing for action. Can just pass an action counter for index. The usually standard is to notify EntityListener one by one and let it do the batching.

2022-07-22 15:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            var sidecarRecord = sidecarRecords.get(i);
Use enhanced for loops everywhere unless there's a need to track the index like inner actions loop.

2022-07-22 15:41 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    public RecordItem(Transaction transaction, TransactionRecord transactionRecord, List<TransactionSidecarRecord> sidecarRecords) {
Remove new constructor in favor of using builder pattern.

2022-07-22 15:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            if (sidecarRecord.hasStateChanges() && contractResult != null) {
Remove the ` && contractResult != null`

2022-07-22 15:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            var sidecar = sidecarRecords.get(i);
Favor enhanced for loops since it reduces the lines of code and avoids the extra get(i).
```suggestion
        for (var sidecar : recordItem.getSidecarRecords()) {
```

2022-07-22 15:54 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            var sidecarRecord = sidecarRecords.get(i);
I'm not sure how applicable these performance numbers are to the Mirror Node, but this benchmark put the enhanced for loop as having a near equivalent performance as streams, while the simple for loop was faster: 

https://howtodoinjava.com/java/collections/performance-comparison-looping-a-list/

2022-07-22 17:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            var sidecarRecord = sidecarRecords.get(i);
Interesting. It's not quite apples since the simple loop doesn't call `list.get(i)` since it's a corner case where the list is an increasing set of integers where they can use the loop counter directly. Would be interesting to see with get.

2022-07-22 17:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            var sidecarRecord = sidecarRecords.get(i);
But am okay with counter style loops if you prefer that.

2022-07-22 18:50 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
Awesome, with that input I have removed the lookup and no longer use the `ContractFunctionResult`.

2022-07-22 18:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var contractStateChanges = new ArrayList<ContractStateChange>();
Thanks for the tips. Excellent! I have removed the lists.

2022-07-22 18:52 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            var sidecarRecord = sidecarRecords.get(i);
Got it ok. I like the readability of the other types of loops, so if the performance is good I have switched them to the for-each.

2022-07-22 18:53 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    public RecordItem(Transaction transaction, TransactionRecord transactionRecord, List<TransactionSidecarRecord> sidecarRecords) {
I've removed this constructor.

2022-07-22 18:53 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            if (sidecarRecord.hasStateChanges() && contractResult != null) {
Thanks it is no longer needed. I have removed it.

2022-07-22 18:53 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            var sidecar = sidecarRecords.get(i);
Thanks I have changed the loop.

2022-07-22 20:48 UTC, steven-sheehy approved these changes
LGTM. Just some nitpicks that can be addressed in the traceability migration follow up if you like.

2022-07-22 20:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    contractAction.setRecipientAddress(action.getInvalidSolidityAddress().toByteArray());
```suggestion
                    contractAction.setRecipientAddress(DomainUtils.toBytes(action.getInvalidSolidityAddress()));
```

2022-07-22 20:48 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    public RecordItem(Version hapiVersion, Transaction transaction, TransactionRecord transactionRecord,
From what I can tell, this constructor might be unused outside this class. So think it could be reverted to the previous list of constructors.

2022-07-22 20:59 UTC, xin-hedera approved these changes
LGTM!

2022-07-22 21:01 UTC, merged