Update Get Blocks Order By Clause
hashgraph/hedera-mirror-node pull request #4135
Opened 2022-07-18 20:08 UTC by edwin-greene

**Description**:
Update the Get Blocks query to Order By consensus_end. 

**Related issue(s)**:4105

Fixes #

**Notes for reviewer**:

**Checklist**

## Rest API

- [ ] `openapi.yml`
  - [ ] Transaction type
  - [ ] Request/response
- [ ] Model
- [ ] View model
- [ ] Route
- [ ] Controller
- [x] Service
- [ ] Tests for each of the above
- [ ] `integrationDomainOps`
- [ ] Spec tests
- [ ] Monitor API test

2022-07-22 20:19 UTC, steven-sheehy submitted a review, later dismissed

2022-07-22 20:22 UTC, xin-hedera requested changes

2022-07-22 20:22 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +      order by ${RecordFile.CONSENSUS_END} ${filters.order}
per the discussion we have in scrum, we can't always use `consensus_end` as the `order by` column since the design of the `/blocks` rest api also accepts `block.number` as a query param.

So the query `/blocks?block.number=gt:10000` will cause the same performance issue.

We can instead pick the first of `block.number` and `timestamp` from filters.whereQuery and use the corresponding column to order.

2022-07-25 15:18 UTC, edwin-greene commented on hedera-mirror-rest/service/recordFileService.js
> +      order by ${RecordFile.CONSENSUS_END} ${filters.order}
Thanks Xin, I have updated the orderBy to be either `consensus_end` or `index` depending on the query.

2022-07-26 14:23 UTC, xin-hedera approved these changes
LGTM

2022-07-26 15:13 UTC, steven-sheehy approved these changes
LGTM

2022-07-26 15:15 UTC, merged