Use a single db container for the rest API test suite
hashgraph/hedera-mirror-node pull request #4143
Opened 2022-07-20 14:07 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-07-20 23:46 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  console.info(`Starting PostgreSQL docker container with image ${image}`);
for some reason, `log4js` doesn't really log messages to console in the global setup script, so just use `console` in this file.

2022-07-20 23:50 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const dbAdminPassword = crypto.randomBytes(16).toString('hex');
we used to pick up the values from env variables POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD if available. I have never used it personally so just hardcode the db name and username, use random string as password here.

2022-07-20 23:51 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  process.env.INTEGRATION_DATABASE_URL = `postgresql://${dbAdminUser}:${dbAdminPassword}@${host}:${port}`;
the env variables set in the global setup will be available in every jest worker process.

2022-07-20 23:53 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +      execSync(`node ${exePath} -c ${flywayConfigPath} info`, {stdio: 'ignore'});
changed to `flyway info` so as not to clean the schema then the next integration file in the same worker will have to rerun the whole migration.

also changed stdio to `ignore` so the output from `flyway info` will not show up

2022-07-21 14:59 UTC, steven-sheehy requested changes

2022-07-21 14:59 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const dbAdminPassword = crypto.randomBytes(16).toString('hex');
I think it was used once upon a time in CircleCI when it didn't support Docker in Docker. Fine to remove.

2022-07-21 14:59 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/globalSetup.js
> +
I wonder why we separate these two here only to re-combine them when we use them. Would be simpler to just have:
```suggestion
const v1DatabaseImage = 'postgres:14-alpine';
const v2DatabaseImage = 'citusdata/citus:11-alpine';
```

2022-07-21 14:59 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  const dbName = `${DEFAULT_DB_NAME}_${process.env.JEST_WORKER_ID}`;
Prefer a function in globalSetup that hides the details of how to construct the db name instead of exporting `DEFAULT_DB_NAME`.

2022-07-21 14:59 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const dockerDb = await new GenericContainer(image)
What occurs for s3 container? Does it still get started for every file or just the s3 focused tests now? If the former, can we move it to global?

2022-07-21 15:08 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +
probably for the convenience of only having to update the tag.

will make the suggested changed

2022-07-21 15:08 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  const dbName = `${DEFAULT_DB_NAME}_${process.env.JEST_WORKER_ID}`;
sure

2022-07-21 15:11 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const dockerDb = await new GenericContainer(image)
s3 is only used in the spec based integration test for the stateproof test cases, moving it to globalSetup will not reduce the total run time.

2022-07-21 15:36 UTC, steven-sheehy approved these changes
LGTM

2022-07-21 15:53 UTC, steven-sheehy approved these changes

2022-07-21 16:04 UTC, edwin-greene approved these changes
Looks good!

2022-07-21 16:49 UTC, merged