HIP 513 Add Bytecode Migration
hashgraph/hedera-mirror-node pull request #4172
Opened 2022-07-25 20:39 UTC by edwin-greene

**Description**:
Adds runtimeBytecode migration for Sidecar ContractBytecode.

**Related issue(s)**:

Fixes #3982

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-25 20:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
Should there be more values populated? Also I'm not sure if this is the correct timestamp range.

2022-07-25 21:06 UTC, steven-sheehy requested changes

2022-07-25 21:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                .build();
```suggestion
        var contract = contractId.toEntity();
        contract.setRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()));
        contract.setTimestampRange(null);
```

2022-07-25 21:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                .sidecarRecords(r -> r.get(2).setMigration(true))
We should revert changes to this test and add a separate test for migration explicitly. The migration test should have multiple state changes and bytecodes spread across multiple contract IDs. The migration record item will not be a contract create but a non-contract transaction like a crypto transfer. And it should not have a contract function result in the record.

2022-07-25 21:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            if (sidecar.hasBytecode() && !sidecar.getMigration()) {
Add a test to the handler unit test.

2022-07-25 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                assertThat(contractRepository.findAll()).hasSizeGreaterThanOrEqualTo(bytecodeMigrations.size());
Also verify with an existing contract gets updated and that contract history does not contain any entries for it to verify that null timestamp worked.

2022-08-03 14:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            if (sidecar.hasBytecode() && !sidecar.getMigration()) {
Thanks, I have added a test.

2022-08-03 14:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    }
With the change to the contract and entity tables, do we still need to change the `timestamp_range` to null for the entity?

2022-08-03 14:52 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                .sidecarRecords(r -> r.get(2).setMigration(true))
Got it. I have added a separate test with a `cryptoTransfer`.

2022-08-04 20:34 UTC, edwin-greene commented
This PR has been refactored after the work from https://github.com/hashgraph/hedera-mirror-node/issues/4150.

2022-08-05 00:15 UTC, steven-sheehy requested changes

2022-08-05 00:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractRepository.updateRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()),
Were you able to confirm via hibernate/jpa logs that this is [bulk updated](https://thorben-janssen.com/implementing-bulk-updates-with-spring-data-jpa/)?

2022-08-05 00:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        domainBuilder.contract().customize(c -> c.id(entity1.getId())).persist();
Perhaps set one of these `contract.runtime_bytecode` to `null`.

2022-08-05 00:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/EntityContractTypeMigration.java
> +@RequiredArgsConstructor(onConstructor_ = {@Lazy})
Lazy not needed here since there's no potential for circular beans. There might be a reflection penalty for keeping `@Lazy` that we don't want to pay.

```suggestion
@RequiredArgsConstructor
```

2022-08-05 00:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/EntityContractTypeMigration.java
> +    public void doMigrate(final Collection<Long> contractIds) {
The `do<Action>` naming is usually reserved for when a parent does some work then delegates the rest to a more specific child method that adds behavior. Like how `MirrorBaseJavaMigration.migrate()` calls `doMigrate()`.

```suggestion
    public void migrate(final Collection<Long> contractIds) {
```

2022-08-05 17:05 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        domainBuilder.contract().customize(c -> c.id(entity1.getId())).persist();
I tried setting the runtime bytecode to null on the `ContractBytecode`, but it looks like it cannot be set to null without throwing an exception: 

```
java.lang.NullPointerException
	at com.hedera.services.stream.proto.ContractBytecode$Builder.setRuntimeBytecode(ContractBytecode.java:749)
```

I was able to add a `.setRuntimeBytecode(ByteString.EMPTY)` to the `SidecarContractMigrationTest.migrateRuntimeBytecode` test.

2022-08-05 17:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    private final Collection<Long> sidecarMigrationContractIds = new ArrayList<>();
Thanks, I have moved the list into the `SidecarContractMigration` class.

2022-08-05 17:06 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                entity.getId());
Got it, I have moved this to the other migration class, `SidecarContractMigration`.

2022-08-05 17:14 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/EntityContractTypeMigrationTest.java
> +    private Entity entityCreator() {
Since the test is trying to exercise the db `in` clause batch limit by partitioning a large list into the batch size it is generating 66000 entities. I did some comparisons of creating and saving that many entities with the various methods:

`domainBuilder.entity().persist()`: 1.693 min
`entityCreator` and `persistEntities`: 610.9 ms
`domainBuilder.entity().get()` and `persistEntities`: 844.1 ms

So to save time on testing, and to remove as much boilerplate code as possible, I've deleted `entityCreator` but retained `persistEntities` to have to test run at around 844.1 ms.

2022-08-05 17:14 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityRepositoryTest.java
> +                .extracting(Entity::getType).isEqualTo(CONTRACT);
Thanks I have fixed it.

2022-08-05 17:16 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractRepository.updateRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()),
Yes I think so... this is the output of the test with the hibernate logging turned on: 

```
2022-08-05T10:20:55.024-0600 INFO main c.h.m.i.m.SidecarContractMigrationTest Executing: migrateEntityTypeToContract() 
        Hibernate: update entity set type = 'CONTRACT' where id in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  [...]

2022-08-05 17:16 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/EntityContractTypeMigration.java
> +@RequiredArgsConstructor(onConstructor_ = {@Lazy})
Got it I have removed `@Lazy`

2022-08-05 17:17 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/EntityContractTypeMigration.java
> +    public void doMigrate(final Collection<Long> contractIds) {
Sounds good I have renamed it.

2022-08-05 17:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        domainBuilder.contract().customize(c -> c.id(entity1.getId())).persist();
You're trying to set it on RecordItemBuilder/RecordItem. I was saying for the DomainBuilder above.

2022-08-05 17:29 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        domainBuilder.contract().customize(c -> c.id(entity1.getId())).persist();
Oh I see. Got it thanks. I have set the runtimeBytecode to null for one of the test contracts.

2022-08-05 17:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    }
No

2022-08-05 18:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractRepository.updateRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()),
That just looks like 3 separate updates. Can you enable `StatisticalLoggingSessionEventListener` logs so that it prints out `X nanoseconds spent executing 1 JDBC batches`?

2022-08-05 18:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/EntityContractTypeMigrationTest.java
> +    private Entity entityCreator() {
Sounds reasonable

2022-08-05 18:51 UTC, steven-sheehy approved these changes
LGTM besides confirmation of batching updates

2022-08-05 19:37 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractRepository.updateRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()),
Thanks for double checking. I'm not sure if this is correct or not. Here's the stats as it does three statements, one for the first 32767, a second for the next 32767 and a third for the remainder: 

```
2022-08-05T12:58:39.256-0600 INFO main c.h.m.i.m.SidecarContractMigrationTest Executing: migrateEntityTypeToContract() 
2022-08-05T12:58:41.832-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    4669541 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    18727625 nanoseconds spent preparing 1 JDBC statements;
    194395083 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    3708 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-05T12:58:42.059-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    12875 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    41084 nanoseconds spent preparing 1 JDBC statements;
    185933083 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    3542 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-05T12:58:42.070-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    15208 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    241708 nanoseconds spent preparing 1 JDBC statements;
    6089791 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    3291 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-05T12:58:42.070-0600 INFO main c.h.m.i.m.SidecarContractMigration Migrated 66000 sidecar contract entities in 1.598 s 
```

Following along with the [bulk update](https://thorben-janssen.com/implementing-bulk-updates-with-spring-data-jpa/) post, he seems to suggest at the end that when using `@Query` and `@Modifying` that the `JDBC batches` will be 0. I looked through some other posts and added the property `jpa.properties.hibernate.batch_versioned_data: true` and was still unable to get it to batch.

2022-08-05 20:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractRepository.updateRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()),
Sorry, think my recommendation might've been bad. Looks like that will probably only batch if you're using managed hibernate objects: e.g. find then update in bulk.

We'll probably have to pivot to use `JdbcOperations.batchUpdate(sql, contractBytecodes, 100, new ParameterizedPreparedStatementSetter() {...})`. See https://mkyong.com/spring/spring-jdbctemplate-batchupdate-example.

2022-08-05 20:22 UTC, xin-hedera approved these changes
LGTM. Most feedback are nits, can do a follow-up PR if some changes are indeed required.

2022-08-05 20:22 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SidecarContractMigrationTest.java
> +                });
this should also verify the runtime byte code is persisted to the correct contract. It's more readable to build an `expectedContracts` list with just the contract id and runtimeBytecode set. Then do

```java
  assertThat(contractRepository.findAll())
    .usingRecursiveFieldByFieldElementComparatorOnFields("id", "runtimeBytecode")
    .containsExactlyInAnyOrderElementsOf(expectedContracts);
```

2022-08-05 20:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SidecarContractMigration.java
> +            count += entityRepository.updateContractType(partition);
also fix entity type in `entity_history` table?

2022-08-05 20:22 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SidecarContractMigrationTest.java
> +        persistEntities(entities);
can just do `entityRepository.saveAll`

2022-08-05 20:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepository.java
> +    @Query(value = "update entity set type = 'CONTRACT' where id in (:ids)", nativeQuery = true)
nit, can be a bit faster if we fix entity type for a lot of mis-labeled contract entities since we have an index on (id, type):

```suggestion
    @Query(value = "update entity set type = 'CONTRACT' where id in (:ids) and type <> 'CONTRACT'", nativeQuery = true)
```

2022-08-08 17:06 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SidecarContractMigration.java
> +            count += entityRepository.updateContractType(partition);
Awesome thanks. I have added the update to `entity_history`.

2022-08-08 17:06 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SidecarContractMigrationTest.java
> +        persistEntities(entities);
I tried using `entityRepository.saveAll` but it made the test take over a minute.

2022-08-08 17:07 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepository.java
> +    @Query(value = "update entity set type = 'CONTRACT' where id in (:ids)", nativeQuery = true)
Great idea, I have updated the statements.

2022-08-08 17:07 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SidecarContractMigrationTest.java
> +                });
I tried implementing this, but for some reason it made the test take a few extra minutes.

2022-08-08 17:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractRepository.updateRuntimeBytecode(DomainUtils.toBytes(contractBytecode.getRuntimeBytecode()),
Sounds good. I have changed it to use `jdbcOperations` for the contract runtimebytecode update.

2022-08-08 17:10 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SidecarContractMigration.java
> +        }
The statistics for this are still not indicating JDBC Batching. I did debug into the `batchUpdate` method and was able to verify that it is batching the updates. I'm not sure why the statistics count this as a statement.

```
2022-08-08T10:59:45.823-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    20375 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    4051792 nanoseconds spent preparing 1 JDBC statements;
    187115125 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    3209 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-08T10:59:46.147-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    10125 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    2185292 nanoseconds spent preparing 1 JDBC statements;
    288496125 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    3292 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-08T10:59:46.343-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    11792 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    21292 nanoseconds spent preparing 1 JDBC statements;
    178381917 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    3666 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-08T10:59:46.572-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    8833 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    18167 nanoseconds spent preparing 1 JDBC statements;
    215063125 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    2875 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-08T10:59:46.582-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    13042 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    89125 nanoseconds spent preparing 1 JDBC statements;
    5150083 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    1667 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-08T10:59:46.596-0600 INFO main o.h.e.i.StatisticalLoggingSessionEventListener Session Metrics {
    8917 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    75166 nanoseconds spent preparing 1 JDBC statements;
    11676334 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    2083 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)
} 
2022-08-08T10:59:46.596-0600 INFO main c.h.m.i.m.SidecarContractMigration Migrated 66000 sidecar contract entities in 3.624 s 
```

2022-08-08 17:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SidecarContractMigration.java
> +        }
That's expected. Those logs are from hibernate, but you switched it to use jdbc operations. The repository for type change uses a native query so probably won't use batching either.

2022-08-08 20:20 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SidecarContractMigrationTest.java
> +        persistEntities(entities);
`saveAll` being slow is because we don't override`Persistable.isNew` in `Entity.java` to always return `true`. so when saving that many entities, hibernates generate runs a select sql statement per entity, then batches the updates. just want to note it, no need to make any change.

2022-08-08 20:21 UTC, xin-hedera approved these changes
LGTM

2022-08-08 21:00 UTC, steven-sheehy approved these changes
LGTM

2022-08-08 21:02 UTC, merged