Hedera transaction not found by eth hash
hashgraph/hedera-mirror-node pull request #4176
Opened 2022-07-26 14:03 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:
Change transaction details by ethereum hash query to match the first 32 bytes of transaction's hash in `transaction` table instead of `ethereum_transaction` table.

**Related issue(s)**:

Fixes #4175 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-07-26 15:48 UTC, ar-conmit commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
If the transaction modifies a contract state, I think the relay should be able to fetch the transaction even if it is not an Ethereum transaction.

2022-07-26 19:44 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
Should we instead be supporting both?
From Eth tools side an `EthereumTransaction` will be submitted and they'll expect an ethereum hash.
However, since places like HashScan offer the Hedera transaction hash a person might take that hash and search.

2022-07-27 06:33 UTC, ar-conmit commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
We can support both hashes.
But should we support search by eth hash for a non-ethereum transaction? Otherwise, the relay should return different hash lengths for a different types of transaction(32bytes for Ethereum tx and 48bytes for Hedera tx).

With the current query change, both hashes will be matched no matter what type of transaction is.

2022-07-27 14:20 UTC, xin-hedera commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
the current change breaks looking up by eth transaction hash since for the same transaction the eth transaction hash and the hedera transaction hash are different.

2022-07-27 18:41 UTC, Nana-EC requested changes
We don't want to lose ethereumTransaction coverage.
If possible we want both.
Maybe we can update the `ethereum_transaction` table schema and ingestion flow to allow for this.
If we do this we may have to break this PR up and schedule it appropriately.

2022-07-27 18:41 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
We should revert this and consider expanding the `ethereum_transaction` table to cover all ethereum related transactions i.e. all EVM processed transactions `ETHEREUMTRANSACTION`, `CONTRACT_CALL` and `CONTRACT_CREATE`.

The point being for SDK submitted transactions a user may expect similar behaviour in hash searches as they do modify contract and ledger state.

In this case we might consider the following

1. Insert into `ethereum_transaction` table an entry for `CONTRACT_CALL` and `CONTRACT_CREATE` transactions
2. Add a new column `transactionType` to `ethereum_transaction` capturing the Hedera transaction type for easy filtering

This could potentially allow for dropping the join with the transaction table, if no other columns are needed.

2022-07-28 21:26 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
Sure. I think the `short_hash` is a short to mid term solution.
When there's more traffic I think the above should be considered, maybe there's a better form.
At some point transactions and ethereum_transactions will be large and getting away from a join will be valuable.
Table can be renamed to `evm_transactions` or something.

Just adding the above for reference. 
Extra 32-byte prefix on every EthereumTransaction is fine

2022-07-28 21:28 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
Actually it might be possible to not add a whole column and just have an index based on the 32-byte prefix right? 
That might address the space concern but could also have performance concerns.

2022-07-29 07:58 UTC, ar-conmit commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
@steven-sheehy What do you think? Let's try to get a final decision on how we should proceed

2022-07-31 01:14 UTC, Nana-EC commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
The relay will comply with expected ethereum schema apis so we won't be able to modify response length.
Mirror node should support search for both. The two types should look the same to consumers of this endpoint.

Your initial change only looks at hedera transaction hashes. Technically it does work for any type of transaction but it's not the expected ethereum transaction.

The right solution should comply with whichever transaction hash is returned (hedera or ethereum)

2022-08-03 03:48 UTC, steven-sheehy commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
Ethereum hash and transaction hash (or its prefix) are completely different. When this was originally designed it was assumed the relay would return the full 48 byte transaction hash for non-ethereum transactions. Allowing lookup of a transaction or results by its 32 byte ethereum hash or its 48 byte transaction hash sounds reasonable. I'm not convinced of the validity of allowing lookup of a 32 byte prefix of a transaction hash as that implicit mapping of a transaction hash to ethereum-style hash has not been discussed before or documented in a HIP.

So first step would be to do some analysis to see if there are any collisions if using just the 32 byte prefix. We would also need to discuss internally with cryptography experts to make sure it's sound. 

So assuming its okay to search by the 32 byte transaction hash prefix, how would we address? I don't think it's a good idea to modify `ethereum_transaction` since it's for non-ethereum transactions. It would not be performant to take as input a 32 byte hash and search _both_ the 32 byte `ethereum_transaction.hash` and the 32 byte prefix of `transaction.transaction_hash`. Instead, we should add a `contract_result.hash` that is populated with the `ethereum_transaction.hash` if present or the prefix of `transaction.transaction_hash`. This table is much smaller than `transaction` and would be more performant to add data to it. Also we could potentially remove the join on transaction if we duplicate a few other fields.

2022-08-03 14:28 UTC, Kalina-Todorova commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
@steven-sheehy Thanks for the detailed description, so to move this forward who should we involve here regarding the analysis of possible collisions and the cryptography assessment?

2022-08-05 19:15 UTC, steven-sheehy commented on hedera-mirror-rest/service/transactionService.js
> +    where position($1 in ${Transaction.TRANSACTION_HASH}) = 1`;
As agreed on the call, we will add a new `contract_result.hash` that contains the `ethereum_transaction.hash` if present or the prefix of `transaction.transaction_hash`. The first 32 bytes of the transaction hash are still unique, but only for successful transactions. It's possible and indeed the case that there could be multiple transactions and thus contract results for a given hash if the user submitted the same transaction to the same node within the 3 minute window. To account for this, we will return the first such result by time matching a given hash since that will always be the successful one (if at least one are successful).

2022-08-19 03:34 UTC, steven-sheehy commented
@ar-conmit `contract_result.hash` was added in #4310. This PR can be updated to use the new field. I also added `transaction_index` and `transaction_result`. This data should allow you to remove the join on transaction in the query in some scenarios like below:

```sql
10|6560  |       select *
10|6560  |       from ethereum_transaction
10|6560  |       where payer_account_id = $1
10|6560  |   )
10|6560  |     select
10|6560  |       t.payer_account_id,
10|6560  |       t.result,
10|6560  |       coalesce(
10|6560  |         etht.hash,
10|6560  |         t.transaction_hash
10|6560  |       ) as transaction_hash,
10|6560  |       t.index,
10|6560  |       etht.*
10|6560  |     from transaction t
10|6560  |     left join etht
10|6560  |     on t.consensus_timestamp = ethConsensus
10|6560  |     where t.consensus_timestamp = $1
```

`contract_result` already has a `payer_account_id`. Other scenarios also use `type` and `nonce` that might not be necessary. `type` isn't returned in the JSON response, `nonce=0` can be substituted for `length(bloom)==0` since children never have a bloom filter.

2022-08-29 20:11 UTC, steven-sheehy commented
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/pull/4381

2022-08-29 20:11 UTC, closed without merging