04006 custom op codes
hashgraph/hedera-mirror-node pull request #4181
Opened 2022-07-27 13:09 UTC by ivanparnarev

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-07-28 08:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSLoadOperation.java
> +//                }
Delete this block 72-74, it won't be needed on `mirror-node` side.

2022-07-28 08:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSLoadOperation.java
> +//        this.dynamicProperties = dynamicProperties;
Delete this line.

2022-07-28 08:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSLoadOperation.java
> +//            final GlobalDynamicProperties dynamicProperties
Delete this line.

2022-07-28 08:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSLoadOperation.java
> +//    private final GlobalDynamicProperties dynamicProperties;
Delete this field.

2022-07-28 08:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSStoreOperation.java
> +//    private final GlobalDynamicProperties dynamicProperties;
Delete this field.

2022-07-28 08:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSStoreOperation.java
> +//        }
Delete this block. It won't be needed.

2022-07-28 08:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSStoreOperation.java
> +//        checkSuperCost = !(gasCalculator instanceof GasCalculatorHederaV18);
Uncomment this line and create empty `GasCalculatorHederaV18` stub with `//FUTURE WORK to be implemented` comment.

2022-07-28 08:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSelfDestructOperation.java
> +//        final var updater = (HederaStackedWorldStateUpdater) frame.getWorldUpdater();
Uncomment this line and create `HederaStackedWorldStateUpdater` stub with the needed methods and `//FUTURE WORK to be implemented` comment.

2022-07-28 08:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSelfDestructOperation.java
> +//        txnCtx.recordBeneficiaryOfDeleted(tbdNum, beneficiaryNum);
Uncomment this block. If anything is missing create empty stub for it.

2022-07-28 08:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSelfDestructOperation.java
> +//            final HederaStackedWorldStateUpdater updater
Uncomment

2022-07-28 08:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateSelfDestructOperation.java
> +//        }
Uncomment

2022-07-28 08:54 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/context/EvmSigsVerifier.java
> +public interface EvmSigsVerifier {}
Add license header and `//FUTURE WORK to be implemented` comment.

2022-07-28 08:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/context/TransactionContext.java
> +public interface TransactionContext {
Add license header and `//FUTURE WORK to be implemented` comment.

2022-07-28 09:45 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/helpers/MerkleAccount.java
> +public class MerkleAccount extends PartialNaryMerkleInternal implements MerkleInternal, Keyed<EntityNum> {
We won't use Merkle types on mirror-node side. Instead we would load the needed properties from the PostgreDB. You can remove this class.

2022-07-28 09:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/helpers/StorageExpiry.java
> +    private final Supplier<MerkleMap<EntityNum, MerkleAccount>> contracts;
We would use a different approach here. We would load a Supplier cache from the PostgreDB or directly make queries to the DB. Remove this `Supplier` and the implementation details in this class and leave the needed function signatures with the bodies empty. This would be sufficient for the code to compile. Add` //FUTURE WORK to be implemented` comment.

2022-07-28 09:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateLogOperation.java
> +//        }
Uncomment this block. Add stubs if needed.

2022-07-28 09:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateLogOperation.java
> +//        frame.addLog(new Log(address, data, builder.build()));
Uncomment

2022-07-28 09:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateOperationUtil.java
> +//        final var account = updater.get(address);
Uncomment block

2022-07-28 09:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateOperationUtil.java
> +//        boolean sigReqIsMet;
Uncomment

2022-07-28 09:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateOperationUtil.java
> +//                            updater.trackingLedgers());
Uncomment block. Add stubs

2022-07-28 09:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulateOperationUtil.java
> +    public static void cacheExistingValue(
Delete this method.

2022-07-28 09:54 UTC, IvanKavaldzhiev requested changes
Rename all `Simulate*` classes to start with `Simulated*` prefix, e.g `SimulateCallCodeOperation` -> `SimulatedCallCodeOperation`

2022-07-28 14:47 UTC, IvanKavaldzhiev reviewed
There are missing alternatives for `HederaCreateOperation` and `HederaCreate2Operation`.

2022-07-29 07:14 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulatedLogOperation.java
> +        //FUTURE WORK finish implementation when we introduce StackedUpdaters
Delete comment

2022-07-29 07:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulatedOperationUtil.java
> +        //FUTURE WORK finish implementation when we introduce StackedUpdaters
Delete comment

2022-07-29 07:28 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulatedOperationUtil.java
> +            //FUTURE WORK implement logic about the EvmSigsVerifier
Delete comment. We tend to put these //FUTURE WORK comments over the interfaces/classes definitions themselves, not over their usage place.

2022-07-29 07:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulatedSStoreOperation.java
> +            //FUTURE WORK finish implementation when we introduce WorldUpdater
Delete comment

2022-07-29 07:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulatedSelfDestructOperation.java
> +        //FUTURE WORK finish implementation when we introduce StackedUpdaters
Delete comment

2022-07-29 07:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/SimulatedSelfDestructOperation.java
> +            //FUTURE WORK finish implementation when we introduce StackedUpdaters
Delete comment

2022-07-29 07:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/context/HederaWorldState.java
> +public class HederaWorldState {
This class would be replaced with SimulatedUpdater after we merge this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/4019)

2022-07-29 07:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/gascalculator/StorageGasCalculator.java
> +public class StorageGasCalculator {
A implementation will be provided with this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/4182)

2022-07-29 07:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/helpers/StorageExpiry.java
> +@Singleton
You can add //FUTURE WORK comment. There is a [task](https://github.com/hashgraph/hedera-mirror-node/issues/4183) for this implementation.

2022-07-29 07:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/helpers/AliasManager.java
> +public class AliasManager {
You can add //FUTURE WORK comment. There is a [task](https://github.com/hashgraph/hedera-mirror-node/issues/4185) for this implementation.

2022-07-29 15:26 UTC, IvanKavaldzhiev approved these changes
LG

2022-08-01 22:19 UTC, shemnon commented
PR description is basically blank.  Pleas fix with a description of what is being done and what the aims/scope of this PR are.

2022-08-03 14:12 UTC, Nana-EC approved these changes
LG
2 questions based on standard approach.

Also a lot of this is code from services from the current implementation.
Feel free to note these in description later on, maybe even with a path to the folder in github, as this make it easier for reviewers to see what new and what's already working logic.

2022-08-04 06:03 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/AbstractRecordingCreateOperation.java
> +    public Operation.OperationResult execute(final MessageFrame frame, final EVM evm) {
No, the EVM handler code runs that.

2022-08-04 06:05 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/AbstractRecordingCreateOperation.java
> +    private void fail(final MessageFrame frame) {
That's what's mandated by the EVM.  No space for failure message.  For that there is `revert`.
EVM spec specifys two ways to fail (a) not enough ether whent he opcode specified a value transafer and (b) stack depth too deep.

2022-08-04 16:07 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/operation/AbstractRecordingCreateOperation.java
> +    public Operation.OperationResult execute(final MessageFrame frame, final EVM evm) {
Thanks

2022-08-23 17:04 UTC, closed without merging