PricesSource + Gas Calculators implementations
hashgraph/hedera-mirror-node pull request #4182
Opened 2022-07-28 11:45 UTC by IvanKavaldzhiev

**Description**:
This PR provides `SimulatedPricesSource` implementation which is mirror-node's equivalent of Hedera's [LivePricesSource](https://github.com/hashgraph/hedera-services/blob/3e79be41a095ec7264c878edb02b1664ed911db4/hedera-node/src/main/java/com/hedera/services/contracts/execution/LivePricesSource.java) class + all `GasCalculator` implementations, which are adapted to the mirror-node approaches.

These classes load `FeeSchedules` and `ExchangeRates` configurations from the `PostgreSQL DB` from `FileIDs 111 & 112`. There is a mechanism to load the most recent configuration based on a given `consensus timestamp` in the past, so that `historical` price calculations can also be made.

**Related issue(s)**: #4128 

Fixes #4007 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-01 15:16 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +        return DEFAULT_RESOURCE_PRICES;
Is `Objects.requireNonNull` the only source of the exception caught on line 101? If so, this could be simplified:

```
        var functionUsagePrices = applicableUsagePrices(at);
        var usagePrices = functionUsagePrices.get(function);
        if (usagePrices == null) {
            log.debug(
                    "Default usage price will be used, no specific usage prices available for function {} @ {}!",
                    function, Instant.ofEpochSecond(at.getSeconds(), at.getNanos()));
            return DEFAULT_RESOURCE_PRICES;
        }

        return usagePrices;
```

2022-08-01 15:21 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/hederahashgraph/fee/FeeBuilder.java
> +        return BigInteger.valueOf(bAmount).multiply(aMultiplier).divide(bDivisor).longValueExact();
It would be good to have a divide by zero check.

2022-08-01 15:24 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +    EnumMap<HederaFunctionality, Map<SubType, FeeData>> functionUsagePricesFrom(final FeeSchedule feeSchedule) {
Looks like it may be able to be `private`

2022-08-01 21:44 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/contracts/gascalculator/GasCalculatorHederaUtil.java
> +    @SuppressWarnings("unused")
If they are unused why are we bringing them in?  It deserves a comment with `// FUTURE WORK` or deleting the code.

2022-08-01 21:44 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/contracts/gascalculator/GasCalculatorHederaV18.java
> +public class GasCalculatorHederaV18 extends PetersburgGasCalculator {
Will we support historical tracing prior to sidecar support?  I'm skeptical we will so I don't think we need this class.

2022-08-01 21:44 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/contracts/gascalculator/GasCalculatorHederaV19.java
> +public class GasCalculatorHederaV19 extends LondonGasCalculator {
we should consider mergin this with `v22`,  but then we lose copy-paste fidelity with services code.

2022-08-01 21:44 UTC, shemnon commented on hedera-mirror-web3/src/main/java/com/hedera/services/transaction/fees/calculation/UsagePricesProvider.java
> +    void loadPriceSchedules();
Is there a world where we would use this object without calling this init method?  Or is it called multiple times (hence updatePriceSchedules may be a better name).  Do we need the provider prior to a lazy instantiation of the object?  What would change between construction and calling the other methods?  Would this be better handled in the impls doing a lazy initialization?

2022-08-02 04:21 UTC, steven-sheehy requested changes

2022-08-02 04:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +    public void setFeeSchedules(final CurrentAndNextFeeSchedule feeSchedules) {
private

2022-08-02 04:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +    private FileDataRepository fileDataRepository;
Won't be injected unless part of the constructor.

```suggestion
    private final FileDataRepository fileDataRepository;
```

2022-08-02 04:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +                    fileDataRepository.findFileByEntityIdAndClosestPreviousTimestamp(
Caching for 30 days means in the worst case it could be out of day for ~29 days after a fee schedule update. We should lower the cache to something like one hour.

2022-08-02 04:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +        loadPriceSchedules(at.getSeconds());
This would reload the fee schedule from the cache and update the class variables for every request. Since those class variables are not thread safe that would cause consistency problems. It would also mean the current fee schedule would arbitrarily get replaced with historical fee schedules while midway processing since there's only a single fee schedule loaded.

2022-08-02 04:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/fees/calculation/SimulatedFcfsUsagePrices.java
> +        for (var pricingData : feeSchedule.getTransactionFeeScheduleList()) {
There's still quite a bit of logic in this mirror node specific class that duplicates what's in services. I think we should rethink what classes get moved into the mirror node and split classes like this into further specific interfaces that deal with interacting with state. Here, we could keep most of this logic in services and create a new interface:

```java
public interface FeeScheduleProvider {
  CurrentAndNextFeeSchedule getFeeSchedule(Instant timestamp);
}
```

We could also wrap `CurrentAndNextFeeSchedule` into a `FeeSchedule` wrapper that lives in services that contains the Timestamp and enum maps if that makes it easier.

2022-08-09 19:54 UTC, Nana-EC requested changes
Waiting on PR updates addressing others feedback to re-review

2022-08-23 17:04 UTC, closed without merging