Optimize token balances in Rest API
hashgraph/hedera-mirror-node pull request #4184
Opened 2022-07-28 14:29 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #4131 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-28 14:29 UTC, xin-hedera commented on hedera-mirror-rest/config/application.yml
> +            single: 2000
open to better config names

2022-07-29 15:59 UTC, steven-sheehy requested changes
Also curious about the k6 test run to verify no performance regression.

2022-07-29 15:59 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +            single: 2000
```suggestion
            multiple: 50
            single: 1000
```

2022-07-29 15:59 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +            single: 2000
Maybe just add `Accounts`/`Account` to the end so it clarifies it's no the tokenBalance that is multiple/single?

2022-07-29 15:59 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts/limit-capped-at-max.json
>        },
Why does this spec have a next link if the number of accounts in the response (6) is less than limit (10)?

2022-07-29 16:08 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/limit-capped-at-max.json
>        },
the config is overridden in the spec:

```json
  "setup": {
    "config": {
      "response": {
        "limit": {
          "default": 3,
          "max": 6,
          "tokenBalance": {
            "multiple": 2
          }
        }
      }
    }
```

the `max` is set to 6.

2022-07-29 16:08 UTC, xin-hedera commented on hedera-mirror-rest/config/application.yml
> +            single: 2000
sure

2022-07-29 16:40 UTC, steven-sheehy approved these changes
LGTM pending performance numbers

2022-07-29 17:17 UTC, edwin-greene approved these changes
Looks good

2022-07-29 17:36 UTC, merged