HIP-513 Add runtime bytecode to get contract REST API
hashgraph/hedera-mirror-node pull request #4186
Opened 2022-07-28 14:46 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:
- Add new contract field `runtime_bytecode`

**Related issue(s)**:

Fixes #3580 

**Notes for reviewer**:
The change is done with mocked data only since the [HIP-513](https://hips.hedera.com/hip/hip-513) is not implemented yet.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-28 22:10 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +      this.runtime_bytecode = utils.addHexPrefix(contract.runtimeBytecode, true);
seems like we should have pass the extra `true` to `addHexPrefix`. can you remove it here and from line 56?

2022-07-28 22:23 UTC, xin-hedera requested changes

2022-07-28 22:23 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    `encode(${Contract.getFullName(Contract.RUNTIME_BYTECODE)}, 'hex')::bytea as ${Contract.RUNTIME_BYTECODE}`,
should just get the bytea `runtime_bytecode` column and hex encode it in the js code. The reason we hex encode `initcode` in SQL is because the contract file content is always hex encoded.

2022-07-28 22:43 UTC, steven-sheehy requested changes

2022-07-28 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +    }
We should never conditionally show fields in the response. If the bytecode is not present it should return null instead of omit the key entirely.

```suggestion
    this.bytecode = contract.bytecode !== undefined utils.addHexPrefix(contract.bytecode) : null;
    this.runtime_bytecode = contract.runtimeBytecode !== undefined ? utils.addHexPrefix(contract.runtimeBytecode) : null;
```

2022-07-28 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +const contractWithInitAndRuntimeBytecodeSelectFields = [
nit
```suggestion
const contractWithBytecodeSelectFields = [
```

2022-07-28 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +      this.runtime_bytecode = utils.addHexPrefix(contract.runtimeBytecode, true);
Sort both bytecode fields inline with the rest of the fields.

2022-07-28 22:45 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +    }
believe it's because in getContracts (for `/api/v1/contracts`) we don't select the contract's bytecode from db

2022-07-28 22:54 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +    }
Oh, didn't realize we were using the same viewmodel for both. We should have different viewmodels with the list being a subset of the by ID, similar to how we handle contract results.

2022-07-29 13:13 UTC, ar-conmit commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +    }
The view models are separated now.

2022-07-29 13:15 UTC, ar-conmit commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +      this.runtime_bytecode = utils.addHexPrefix(contract.runtimeBytecode, true);
Since the view models are separated, the byte code fields are always at the end of the json response

2022-07-29 13:15 UTC, ar-conmit commented on hedera-mirror-rest/viewmodel/contractViewModel.js
> +      this.runtime_bytecode = utils.addHexPrefix(contract.runtimeBytecode, true);
Done

2022-07-29 13:16 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +    `encode(${Contract.getFullName(Contract.RUNTIME_BYTECODE)}, 'hex')::bytea as ${Contract.RUNTIME_BYTECODE}`,
Done

2022-07-29 14:47 UTC, xin-hedera requested changes

2022-07-29 14:47 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractBytecodeViewModel.js
> +    this.runtime_bytecode = utils.addHexPrefix(contract.runtimeBytecode);
```suggestion
    this.runtime_bytecode = utils.toHexString(contract.runtimeBytecode, true);
```

2022-07-29 14:47 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/contract-initcode.json
> +    "runtime_bytecode": "0x60806040",
should be:
```suggestion
    "runtime_bytecode": "0x3630383036303430",
```

once the ViewModel is fixed, the response will show the above value

2022-07-29 16:01 UTC, steven-sheehy approved these changes
LGTM

2022-07-29 16:50 UTC, xin-hedera approved these changes
LGTM

2022-07-29 16:58 UTC, steven-sheehy approved these changes

2022-07-29 16:58 UTC, merged