Add Network Stake REST API
hashgraph/hedera-mirror-node pull request #4188
Opened 2022-07-28 15:23 UTC by edwin-greene

**Description**:
HIP 406: Add Network Stake REST API.

**Related issue(s)**:

Fixes #4133

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

## Rest API

- [ ] `openapi.yml`
  - [ ] Transaction type
  - [ ] Request/response
- [x] Model
- [x] View model
- [x] Route
- [x] Controller
- [x] Service
- [x] Tests for each of the above
- [x] `integrationDomainOps`
- [x] Spec tests
- [x] Monitor API test

2022-07-29 16:57 UTC, steven-sheehy requested changes

2022-07-29 16:57 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
number does not [support](https://swagger.io/docs/specification/data-models/data-types/#numbers) a format of int64. Use integer everywhere instead.
```suggestion
          type: integer
          format: int64
```

2022-07-29 16:57 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
Change both fractions to:
```suggestion
          format: float
```

2022-07-29 16:57 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: The fraction of the network and service fees paid to the staking reward account 0.0.800
Same for other

```suggestion
          description: The fraction between zero and one of the network and service fees paid to the staking reward account 0.0.800
```

2022-07-29 16:57 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/lib/parameters.js
> +        DEFAULT_PUBLIC_KEY: firstAccount.key
Revert. I thought this originally and had to revert it in #3437.

2022-07-29 16:57 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/networkStakeViewModel.js
> +    }
Move to a shared function for reuse with `networkNodeViewModel`.

2022-07-29 20:22 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
Thanks I have changed it to integer for all the new fields.

2022-07-29 20:24 UTC, edwin-greene commented on hedera-mirror-test/k6/src/lib/parameters.js
> +        DEFAULT_PUBLIC_KEY: firstAccount.key
I see, I have now reverted it.

2022-07-29 20:24 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/networkStakeViewModel.js
> +    }
I have moved this to utils.js.

2022-08-01 17:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
These should stay as type=number. See swagger docs https://swagger.io/docs/specification/data-models/data-types/#numbers

2022-08-01 18:14 UTC, steven-sheehy requested changes

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorNetworkStake.java
> +    private int nodeRewardFeeNumerator;
This should match the REST API, not the domain model. Same for other fields. I don't think anything is an int32.
```suggestion
    private int nodeRewardFee;
```

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/network/networkstake.feature
> +            | 17808                       | 1                        | 1                      | 35000000000000000  |               | 1440                  |  365                 | 1
These values are unused. Can just remove since it would be brittle to verify specific values.

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/network/networkstake.feature
> +    @critical @release @acceptance
Add `@networkstake` in case we need to omit it specifically.

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +        assertThat(networkStake.getStakeTotal()).isNotNull();
Can check if >= 0

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +@Log4j2
Unused
```suggestion
```

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +        networkStake = mirrorClient.getNetworkStake();
We should test this against integration first. You can deploy your custom REST API to an unused port then point acceptance tests to it.

2022-08-01 18:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.getRuntimeBytecode()).isNotNull();
Unfortunately this will still be null until sidecars is enabled. We should add a property that's off by default to enable this extra check.

2022-08-01 19:58 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/network/networkstake.feature
> +        | 200            |
This param is unused in any step. Can just omit since it would be hard to test any negative scenario with this API.

2022-08-02 17:05 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorNetworkStake.java
> +    private int nodeRewardFeeNumerator;
Thanks I have changed these to match the REST API. The denominators and numerators have been removed.

2022-08-02 17:05 UTC, edwin-greene commented on hedera-mirror-test/src/test/resources/features/network/networkstake.feature
> +            | 17808                       | 1                        | 1                      | 35000000000000000  |               | 1440                  |  365                 | 1
Ok sounds good I have removed the Example section.

2022-08-02 17:06 UTC, edwin-greene commented on hedera-mirror-test/src/test/resources/features/network/networkstake.feature
> +    @critical @release @acceptance
I've added `@networkstake`.

2022-08-02 17:07 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +        assertThat(networkStake.getStakeTotal()).isNotNull();
I've updated the fractions and the stake total to have the greater than or equal to 0 check.

2022-08-02 17:07 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +@Log4j2
Thanks I have removed it.

2022-08-02 17:09 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(mirrorContract.getRuntimeBytecode()).isNotNull();
I see, I have added the sidecar property and changed this to conditionally assert if the sidecar property is enabled. By default the sidecar property is disabled.

2022-08-02 17:09 UTC, edwin-greene commented on hedera-mirror-test/src/test/resources/features/network/networkstake.feature
> +        | 200            |
Sounds good I have removed the Examples section.

2022-08-02 17:20 UTC, steven-sheehy requested changes

2022-08-02 17:20 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorNetworkStake.java
> +    private int stakingPeriodsStored;
```suggestion
    private long stakingPeriodDuration;
    private long stakingPeriodsStored;
```

2022-08-02 17:20 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +        assertThat(networkStake.getNodeRewardFeeFraction()).isGreaterThanOrEqualTo(0);
Same for other fraction:
```suggestion
        assertThat(networkStake.getNodeRewardFeeFraction()).isBetween(0.0, 1.0);
```

2022-08-02 17:30 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorNetworkStake.java
> +    private int stakingPeriodsStored;
Thanks, I have changed them to longs.

2022-08-02 17:31 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NetworkFeature.java
> +        assertThat(networkStake.getNodeRewardFeeFraction()).isGreaterThanOrEqualTo(0);
Sounds good, I have switched the fraction assertions to `isBetween`.

2022-08-02 17:33 UTC, steven-sheehy approved these changes
LGTM. I know it was more work to do so but nice work on hooking the new API into the other test/monitoring components.

2022-08-02 17:59 UTC, steven-sheehy approved these changes

2022-08-02 18:11 UTC, merged