adding new cluster for previewnet
hashgraph/hedera-mirror-node pull request #4202
Opened 2022-07-31 20:44 UTC by tolorukooba

**Adding new cluster for previewnet**:

This PR creates an initial structure for previewnet kube based deployment. The PR creates a repo for previewnet with some common files. following this PR, we shall install flux in the previewnet cluster via a Bootstrap command. This PR paves the way for the flux installation. 

The following files have been added

* Add Previewnet cluster repo
* Add a common folder as a sub directory of previewnet repo
* Add helrelease  and kustomization yaml files

2022-08-01 18:32 UTC, steven-sheehy requested changes

2022-08-01 18:32 UTC, steven-sheehy commented on clusters/previewnet/common/kustomization.yaml
> +- sealed-secret.yaml
This file is missing

2022-08-01 18:32 UTC, steven-sheehy commented on clusters/previewnet/common/helmrelease.yaml
> +      version: '0.60.0'
Since it has its own cluster now we should use the same versioning strategy:
```suggestion
      version: '>0.0.0-0' # Update to the latest pre-release
```

2022-08-01 18:32 UTC, steven-sheehy commented on clusters/previewnet/common/sealed-secret-grafana-cloud.yaml
> +    data: null
Missing actual contents. We should actually create the cluster, install sealed secrets, flux, etc. first as the README indicates before we try to reconcile charts.

2022-08-08 22:03 UTC, tolorukooba commented on clusters/previewnet/common/kustomization.yaml
> +- sealed-secret.yaml
added

2022-08-08 22:04 UTC, tolorukooba commented on clusters/previewnet/common/helmrelease.yaml
> +      version: '0.60.0'
Fixed!

2022-08-08 22:05 UTC, tolorukooba commented on clusters/previewnet/common/sealed-secret-grafana-cloud.yaml
> +    data: null
secrets have been created

2022-08-09 14:28 UTC, steven-sheehy requested changes

2022-08-09 15:14 UTC, tolorukooba commented on clusters/preprod/previewnet/helmrelease.yaml
> -      chart: hedera-mirror
The code is now checked in to the previewnet cluster

2022-08-09 15:57 UTC, tolorukooba commented on clusters/previewnet/common/helmrelease.yaml
> +  chart:
all commits should be good now

2022-08-09 20:14 UTC, steven-sheehy commented on clusters/previewnet/common/sealed-secret.yaml
> +    values.yaml: AgBxNrYRYlt+X3u3nJ1qLr/4xwFJIQjbQPZ0bdJAW926dGU+Gt06K5XT9s2D261BH7wYMYSXEr4Lg8Ln4W/ZJEmDfuwO+ks1/Mus+b1LNU2u4EAOVejdw1uxQJmtYir8bgnsUGrUKBoZMs4ME7m8APimEoKKZm059W5cftq624PJqruSp6jrMJ
This file is missing the lokiAddress

2022-08-12 20:47 UTC, merged