Store current account balance
hashgraph/hedera-mirror-node pull request #4235
Opened 2022-08-05 22:10 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #4030

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-08-05 22:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> -            default -> {}
Added to make sonar happy

2022-08-05 22:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> -            default -> {}
finally found the IDEA config to not move the closing brace to a new line and fixed it :)

2022-08-05 22:39 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    @UpsertColumn(coalesce = """
need `''ACCOUNT''` so MessageFormat.format outputs `'ACCOUNT'`

2022-08-05 22:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +            entityProperties.getPersist().setTrackBalance(false);
disable balance tracking so crypto transfers added from the missing transactions won't change the corresponding entities balance

2022-08-08 20:15 UTC, edwin-greene submitted a review, later dismissed
Looks good.

2022-08-08 21:38 UTC, steven-sheehy requested changes

2022-08-08 21:38 UTC, steven-sheehy commented on docs/operations.md
> +### Initialize Entity Balance
Move to `docs/importer/README.md`

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        this.migrationProperties = mirrorProperties.getMigration().get(propertiesKey);
Should handle missing scenario

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +              from crypto_transfer
Add ` and (errata is null or errata <> 'DELETE')`

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +              select consensus_timestamp as from_timestamp, consensus_end as to_timestamp
Should take into account account_balance_file.offset

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
This and the checksum would benefit moving to `MirrorBaseJavaMigration`, as long as you handle the null case since the property should be optional.

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> +
Remove and move to defaults in `MirrorBaseJavaMigration`

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__entity_balance.sql
> +where type in ('ACCOUNT', 'CONTRACT');
Need v2 changes

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__entity_balance.sql
> +set balance = 0
Since a default in add column can be an expression, should we move the type check to there so future creates benefit?

2022-08-08 21:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MigrationProperties.java
> +    private Integer checksum;
If it's not null then use primitive.

```suggestion
    private int checksum = 1;
```

2022-08-08 21:38 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.migration.initializeEntityBalanceMigration.enabled`  | true                           | Whether to enable `InitializeEntityBalanceMigration`
Wondering if we really want to document every migration that can be customized. Should maybe not mention `initializeEntityBalanceMigration` here but some placeholder like `<migrationName>`.

2022-08-09 21:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
I'm moving them to a new `RepeatableMigration` abstract base class, reason is for versioned java migrations, we should not: 1) make it skippable 2) change its checksum

2022-08-10 15:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__entity_balance.sql
> +set balance = 0
unfortunately the default expression can't reference columns in the current table

2022-08-10 16:05 UTC, xin-hedera commented on docs/operations.md
> +### Initialize Entity Balance
updated

2022-08-10 16:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        this.migrationProperties = mirrorProperties.getMigration().get(propertiesKey);
move the logic to the abstract base `RepeatableMigration` and it handles the missing scenario with the default

2022-08-10 16:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +              from crypto_transfer
added

2022-08-10 16:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +              select consensus_timestamp as from_timestamp, consensus_end as to_timestamp
added

2022-08-10 16:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> +
removed it, now it only has those repeatable migrations with non-default checksum

2022-08-10 16:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MigrationProperties.java
> +    private Integer checksum;
done

2022-08-10 16:07 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.migration.initializeEntityBalanceMigration.enabled`  | true                           | Whether to enable `InitializeEntityBalanceMigration`
changed to `<migrationName>`

2022-08-10 21:09 UTC, steven-sheehy approved these changes
LGTM

2022-08-10 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ErrataMigration.java
> +    public ErrataMigration(@Value("classpath:errata/mainnet/balance-offsets.txt") Resource balanceOffsets,
nit: `@Value` still works on the field even with constructor injection

2022-08-11 02:07 UTC, merged