Search transaction by hash Rest API
hashgraph/hedera-mirror-node pull request #4254
Opened 2022-08-09 16:05 UTC by xin-hedera

**Description**:

- Add database index on the 32-byte prefix of transaction hash
- Extend `/api/v1/transactions/:transactionIdOrHash` to support search transaction by hash

**Related issue(s)**:

Fixes #4253 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

**Rest API**

- [x] `openapi.yml`
  - [ ] Transaction type
  - [x] Request/response
- [x] Model
- [ ] View model
- [ ] Route
- [x] Controller
- [ ] Service
- [x] Tests for each of the above
- [x] `integrationDomainOps`
- [x] Spec tests
- [ ] Monitor API test

**Documentation**

- [ ] [Configuration Properties](/docs/configuration.md)
- [x] [Database Indexes Table](/docs/database.md#indexes)
- [x] [REST Database Table](/docs/rest/README.md#database)

2022-08-09 16:21 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> -                      order by ${Transaction.CONSENSUS_TIMESTAMP} desc`;
the ordering here is unnecessary, what's worse is it makes the query plan by hash prefix to be bitmap index scan + bitmap heap scan instead of a simple index scan which is much faster.

2022-08-09 16:23 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const transactionHashRegex = /^([\dA-Za-z+\-\/_=]{64}|(0x)?[\dA-Fa-f]{96})$/;
the first part of the regex is for the base64url alphabet. the difference from the base64 alphabet is "+" -> "-", and "/" -> "_"

2022-08-09 20:10 UTC, Nana-EC requested changes
Looking good.
I believe we're missing support for the search via the prefix of the hash.
Clients who are returned the prefix will search by this as they don't have the full hash

2022-08-09 20:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions/{idOrHash}/no-params.json
> +        "/api/v1/transactions/0xae8bebf1c9fa0f309356e48057f6047af7cde63037d0509d16ddc3b20e085158bfdf14d15345c1b18b199b72fed4ac6f"
Shouldn't we be supporting search by the prefix also?
```suggestion
        "/api/v1/transactions/0xae8bebf1c9fa0f309356e48057f6047af7cde63037d0509d16ddc3b20e085158bfdf14d15345c1b18b199b72fed4ac6f",
          "/api/v1/transactions/ae8bebf1c9fa0f309356e48057f6047af7cde63037d0509d16ddc3b20e085158",
  "/api/v1/transactions/0xae8bebf1c9fa0f309356e48057f6047af7cde63037d0509d16ddc3b20e085158"
```

2022-08-09 20:10 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        '0xab4af784ae69ca3e1d17fef8491f7f89a0e8a3b80ad3748b841110f0345ada53456bc14bbe9ee6f441829c2849933ac4',
Should also support `ab4af784ae69ca3e1d17fef8491f7f89a0e8a3b80ad3748b841110f0345ada53` and `0xab4af784ae69ca3e1d17fef8491f7f89a0e8a3b80ad3748b841110f0345ada53`

2022-08-09 20:25 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        '0xab4af784ae69ca3e1d17fef8491f7f89a0e8a3b80ad3748b841110f0345ada53456bc14bbe9ee6f441829c2849933ac4',
Seems i mixed up tickets. This would come in another PR.
Ignore

2022-08-09 20:25 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/transactions/{idOrHash}/no-params.json
> +        "/api/v1/transactions/0xae8bebf1c9fa0f309356e48057f6047af7cde63037d0509d16ddc3b20e085158bfdf14d15345c1b18b199b72fed4ac6f"
Seems i mixed up tickets. This would come in another PR.
Ignore

2022-08-09 20:26 UTC, Nana-EC submitted a review, later dismissed
LG
Signing off to unblock previous requests

2022-08-09 20:42 UTC, edwin-greene approved these changes
Looks good.

2022-08-09 21:23 UTC, steven-sheehy requested changes

2022-08-09 21:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/TransactionIdStr'
While this is reusable from a yaml perspective, it does not generate actual working code since there are three types. The generator doesn't know how to create an API client for this and will end up generating a wrapper type that doesn't exist.

Going forward, we need to have a single schema definition for any parameter. That single schema can still be reused elsewhere. So here this would be of type string with a single regex with an OR like `^(...|...|...)$`.

```suggestion
      schema:
        $ref: '#/components/schemas/TransactionIdOrHash'
```

2022-08-09 21:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    HederaHashInBase64url:
```suggestion
    HederaHashBase64Url:
```

2022-08-09 21:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    HederaHashInHex:
nit:
```suggestion
    HederaHashHex:
```

2022-08-09 21:23 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +  if (isValidTransactionHash(transactionIdOrHash)) {
As per checklist, we should add a new monitor JS check and acceptance test for the new path parameter format. For acceptance test can reuse an existing scenario and just add another lookup by hash `Then` check.

2022-08-09 21:24 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/{idOrHash}/duplicate-transactions.json
>  {
sure

2022-08-09 21:24 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A base64url encoded hedera transaction hash.
prefer `base64url` since this is what's in the RFC: https://www.rfc-editor.org/rfc/rfc4648

2022-08-09 21:36 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: A base64url encoded hedera transaction hash.
Sure, didn't realize that was an official name

2022-08-09 22:01 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/TransactionIdStr'
I don't see the issue of non-existing wrapper type. Using the `oneOf` here, the openapi generator will generates `GetTransactionByIdOrHashTransactionIdOrHashParameter.java` which indicates it's an `oneOf` and the accepted schema is `String`. That makes sense since all of 3 possible schemas are strings.

2022-08-09 22:09 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/TransactionIdStr'
Except it doesn't generate an actual `GetTransactionByIdOrHashTransactionIdOrHashParameter.java`

2022-08-09 22:14 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/TransactionIdStr'
It does. btw, I made local changes to add `or hash` to the openapi where it applies so my generated class name will be:

```shell
$ find -type f -name 'GetTransactionByIdOrHash*.java'
./model/GetTransactionByIdOrHashTransactionIdOrHashParameter.java

$ grep -n 'GetTransactionByIdOrHashTransactionIdOrHashParameter' api/TransactionsApi.java
252:    public okhttp3.Call getTransactionByIdOrHashCall(GetTransactionByIdOrHashTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled, final ApiCallback _callback) throws ApiException {
307:    private okhttp3.Call getTransactionByIdOrHashValidateBeforeCall(GetTransactionByIdOrHashTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled, final ApiCallback _callback) throws ApiException {
336:    public TransactionByIdResponse getTransactionByIdOrHash(GetTransactionByIdOrHashTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled) throws ApiException {
357:    public ApiResponse<TransactionByIdResponse> getTransactionByIdOrHashWithHttpInfo(GetTransactionByIdOrHashTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled) throws ApiException {
380:    public okhttp3.Call getTransactionByIdOrHashAsync(GetTransactionByIdOrHashTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled, final ApiCallback<TransactionByIdResponse> _callback) throws ApiException {
```

2022-08-10 15:51 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/TransactionIdStr'
Well, I wasn't sure of the exact error since I didn't want to have to dig up my gradle branch. But since you're inquiring, I re-ran it against your `openapi.yml`. This is the error while attempting to compile the API:

```java
/Users/steven/projects/hedera/hedera-mirror-node/hedera-mirror-monitor/build/generate-resources/main/src/main/java/com/hedera/mirror/rest/api/TransactionsApi.java:7: error: cannot find symbol
import com.hedera.mirror.rest.model.OneOfstringstringstring;
                                   ^
  symbol:   class OneOfstringstringstring
  location: package com.hedera.mirror.rest.model
/Users/steven/projects/hedera/hedera-mirror-node/hedera-mirror-monitor/build/generate-resources/main/src/main/java/com/hedera/mirror/rest/api/TransactionsApi.java:133: error: cannot find symbol
    private ResponseSpec getTransactionByIdRequestCreation(GetTransactionByIdTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled) throws WebClientResponseException {
                                                           ^
  symbol:   class GetTransactionByIdTransactionIdOrHashParameter
  location: class TransactionsApi
/Users/steven/projects/hedera/hedera-mirror-node/hedera-mirror-monitor/build/generate-resources/main/src/main/java/com/hedera/mirror/rest/api/TransactionsApi.java:177: error: cannot find symbol
    public Mono<TransactionByIdResponse> getTransactionById(GetTransactionByIdTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled) throws WebClientResponseException {
                                                            ^
  symbol:   class GetTransactionByIdTransactionIdOrHashParameter
  location: class TransactionsApi
/Users/steven/projects/hedera/hedera-mirror-node/hedera-mirror-monitor/build/generate-resources/main/src/main/java/com/hedera/mirror/rest/api/TransactionsApi.java:182: error: cannot find symbol
    public Mono<ResponseEntity<TransactionByIdResponse>> getTransactionByIdWithHttpInfo(GetTransactionByIdTransactionIdOrHashParameter transactionIdOrHash, Integer nonce, Boolean scheduled) throws WebClientResponseException {
                                                                                        ^
  symbol:   class GetTransactionByIdTransactionIdOrHashParameter
  location: class TransactionsApi
```

So it's true the `GetTransactionByIdTransactionIdOrHashParameter` class exists, but it's missing an import to it. But it does have an import to `OneOfstringstringstring`, which doesn't exist. So I think it's confusing the two and can't generate a valid API when using oneof.

Even if you were to somehow correct the missing import and remove the bad one, the actual contents of `GetTransactionByIdTransactionIdOrHashParameter` are empty and are useless:

```java
@JsonPropertyOrder({
})
@JsonTypeName("getTransactionById_transactionIdOrHash_parameter")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-10T10:36:50.387417-05:00[America/Chicago]")
public class GetTransactionByIdTransactionIdOrHashParameter {
  public GetTransactionByIdTransactionIdOrHashParameter() {
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTransactionByIdTransactionIdOrHashParameter {\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
```

I also ran it against the maven plugin and the same error resulted.

2022-08-10 15:52 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          - $ref: '#/components/schemas/TransactionIdStr'
In summary, using oneof results in generating code that won't compile and even if it did the wrapper object is useless. Please remove the oneof.

2022-08-11 20:42 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2022-08-11 22:45 UTC, steven-sheehy requested changes

2022-08-11 22:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +            var record = getTransactionRecord(transactionId);
Undo this change. This will greatly slow down and increase the costs of the acceptance tests since a receipt is free and quick but a record is paid and slower. And this will be executed for all transactions and not just for the couple transfers you need the hash.

You can get the transaction hash from the SDK transaction input: `Transaction.getTransactionHash()`.

2022-08-11 22:47 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +            var record = getTransactionRecord(transactionId);
Only that the SDK getTransactionHash didn’t work. I didn’t spend much time to figure out what’s wrong though

2022-08-11 22:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +            var record = getTransactionRecord(transactionId);
Alternatively, revert changes to original method and add a new one that gets record just for the few places you need the hash.

2022-08-12 00:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +            var record = getTransactionRecord(transactionId);
made it work using SDK. so SDK's `Transaction.getTransactionHash` is quite a surprise that it doesn't return the hash of the just executed copy, though I'm still not sure which copy's hash it returns...

2022-08-12 01:36 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +            var record = getTransactionRecord(transactionId);
Probably have to get hash before execution. After execution it probably is generating it for the next node.

2022-08-12 01:38 UTC, steven-sheehy approved these changes
LGTM

2022-08-12 13:58 UTC, edwin-greene approved these changes

2022-08-12 14:34 UTC, merged