04216 slow apiv1blocksblockhash api
hashgraph/hedera-mirror-node pull request #4255
Opened 2022-08-09 19:46 UTC by edwin-greene

**Description**:
Update the blocks REST API to query with prefix of the first 32 bytes of the block hash. 

**Related issue(s)**:

Fixes #4216

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-08-10 13:41 UTC, xin-hedera requested changes

2022-08-10 13:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__record_file_hash_index.sql
> +create index if not exists record_file__hash_prefix
drop the existing hash, and do 
```suggestion
create unique index if not exists record_file__hash on record_file (hash collate "C");
```
for historical reason, record_file.hash is the 96-character hash string so there is no storage overhead when making it full text search capable using `collate "C"`

2022-08-10 13:41 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +      params.push(hash.substring(0, RecordFileService.BASE64_HASH_SIZE));
conditionally query

- full hash, `where hash = $1 collate "C"`
- 64-char hash, `where hash like $1 collate "C"`, $1 is the 64-char hash + %

another issue we need to fix is we should lowercase the hash string

2022-08-10 13:41 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +  static BASE64_HASH_SIZE = 64;
```suggestion
  static HEX_HASH_PREFIX_SIZE = 64;
```

2022-08-10 14:29 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__record_file_hash_index.sql
> +create index if not exists record_file__hash_prefix
Great thanks, I have changed the index.

2022-08-10 14:30 UTC, edwin-greene commented on hedera-mirror-rest/service/recordFileService.js
> +      params.push(hash.substring(0, RecordFileService.BASE64_HASH_SIZE));
Thanks, I have changed it to conditionally change the where statement to those values and I've added the lowercase.

2022-08-10 14:30 UTC, edwin-greene commented on hedera-mirror-rest/service/recordFileService.js
> +  static BASE64_HASH_SIZE = 64;
Renamed.

2022-08-10 15:13 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +      params.push(hash.substring(0, RecordFileService.BASE64_HASH_SIZE));
need to add upper case hash string in spec based tests hash-64.json and hash-96.json

2022-08-10 15:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__record_file_hash_index.sql
> +create index if not exists record_file__hash_prefix
old index `idx_file_data_hash_unq` is not dropped

2022-08-10 15:42 UTC, edwin-greene commented on hedera-mirror-rest/service/recordFileService.js
> +      params.push(hash.substring(0, RecordFileService.BASE64_HASH_SIZE));
Good idea, I have added them.

2022-08-10 15:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.65.0__record_file_hash_index.sql
> +create index if not exists record_file__hash_prefix
I see, I have dropped it.

2022-08-10 19:01 UTC, xin-hedera approved these changes
LGTM

2022-08-10 21:54 UTC, steven-sheehy requested changes

2022-08-10 21:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on record_file (prev_hash collate "C");
This index does not need to be changed to use prefix. In fact, I think we should remove it both in v1 and v2 since it's not used anymore from what I can tell.

2022-08-11 13:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on record_file (prev_hash collate "C");
Sounds good, I have removed it.

2022-08-11 14:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.66.0__record_file_hash_index.sql
> +drop index if exists idx_file_data_hash_unq;
Thanks got it.

2022-08-11 14:14 UTC, xin-hedera approved these changes

2022-08-11 15:03 UTC, merged