Add failed initcode to Contract Result
hashgraph/hedera-mirror-node pull request #4273
Opened 2022-08-11 20:24 UTC by edwin-greene

**Description**:
Add Failed Initcode to Contract Result in Importer and REST API.

**Related issue(s)**:

Fixes #4191

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-08-12 17:56 UTC, steven-sheehy requested changes

2022-08-12 21:28 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +            if (!recordItem.isSuccessful() && !transactionBody.getInitcode().isEmpty()) {
Thanks I have implemented this change.

2022-08-12 21:28 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        if (!recordItem.isSuccessful()) {
Great idea! I have made this change.

2022-08-13 00:11 UTC, xin-hedera requested changes

2022-08-13 00:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    private Optional<ByteString> processSidecarRecords(RecordItem recordItem) {
I don't see the benefit of using `Optional` here. should just return `ByteString`, in addition, `DomainUtils.toBytes(byteString)` returns null when `byteString` is null.

2022-08-13 03:39 UTC, steven-sheehy approved these changes
LGTM

2022-08-13 03:39 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    }
nit: Could maybe simplify the conditionals:

```suggestion
    if (!_.isEmpty(contractResult.failedInitcode)) {
      this.failed_initcode = utils.toHexStringNonQuantity(contractResult.failedInitcode);
    } else if (this.status === ContractResultDetailsViewModel._FAIL_RESULT && !_.isEmpty(transaction.callData)) {
      this.failed_initcode = utils.toHexStringNonQuantity(transaction.callData);
    }
```

2022-08-15 14:17 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    }
Thanks I have updated the conditional, though I still had one part at the end to set the failed_initcode to null.

2022-08-15 14:17 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    private Optional<ByteString> processSidecarRecords(RecordItem recordItem) {
Sounds good I have removed the Optional.

2022-08-15 14:26 UTC, xin-hedera approved these changes
LGTM

2022-08-15 14:55 UTC, steven-sheehy approved these changes

2022-08-15 14:56 UTC, merged