HIP 406 pending reward persistence
hashgraph/hedera-mirror-node pull request #4334
Opened 2022-08-22 22:21 UTC by xin-hedera

**Description**:

This PR implements pending reward and entity stake state persistence

- Add domain class `EntityStake` and db table for entity stake state
- Add materialized view `entity_state_start` to capture the entity state at the start of a staking period
- Change `EntityListener.onNodeStake` to `EntityListener.onNodeStakes`
- Add `EntityStakeCalculatorImpl` as the central point of entity stake persistence
- Add link to importer README in project root README file
- Fix incorrect composite id in `NodeStake`

**Related issue(s)**:

Fixes #4130

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

**Common**

- [x] Domain class
  - [x] `@AllArgsConstructor(access = AccessLevel.PRIVATE)`, `@Builder(toBuilder = true)` for builder
  - [ ] `@IdClass` for composite keys
- [ ] `TransactionType`
- [x] `DomainBuilder`

**Importer**

- [x] V1 migration
- [x] `V2.0.0__create_tables.sql`
- [ ] `V2.0.1__distribution.sql`
- [x] `V2.0.3__index_init.sql`
- [x] Repository
  - [ ] `RetentionRepository` if insert-only
- [ ] `EntityListener`
- [ ] `CompositeEntityListener`
- [x] `SqlEntityListener`
  - [ ] Merge method added if not insert-only and all fields properly merged
- [x] `TransactionHandler`
- [x] Tests for each of the above
- [x] `RecordItemBuilder`
- [x] `EntityRecordItemListener*Test`
- [ ] `PubSubMessageTest` updated for `TransactionRecord` changes
- [ ] `pubsub-messages.txt`

2022-08-22 22:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculator.java
> +    @TransactionalEventListener(classes = NodeStakeUpdateEvent.class)
The default `phase` is `TransactionPhase.AFTER_COMMIT`: Handle the event after the commit has completed successfully. So in case there's such an event published in a db transaction and the transaction ends up rolled back, the handler will not be trigerred.

2022-08-22 22:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
> +    @Async
make it async, so it will run in a new db transaction instead of the transaction in which the event is published.

2022-08-22 22:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              from entity_state_start ess
Use `entity_state_start` as the main table for left outer joins since there can be newly created accounts / contracts not in the `entity_stake` table.

2022-08-23 13:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +                  end) as pending_reward,
Algorithm to update pending reward

1. IF the entity is deleted, OR there is no such row in entity_stake, OR its decline_reward_start is true (decline reward for the ending staking period), OR it didn't stake to a node for the ending staking period, the new pending reward is 0
2. IF the current stake_period_start >= the last epochDay from node stake update (either its staking metadata or balance changed in the ending staking period), calculate the the reward it has earned in the ending staking period as its pending reward
3. Otherwise, there's no staking metadata or balance change for the entity since the start of the ending staking period, add the reward eared in the ending period to the current, as the new pending reward

2022-08-24 14:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +                  end) as pending_reward,
added the algorithm as code comment

2022-08-24 20:41 UTC, steven-sheehy requested changes

2022-08-24 20:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
> +    @Async
Does it work if we put the `@Async` on the interface so as to leverage the faster proxy-based interception?

2022-08-24 20:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +    @Query(value = UPDATE_ENTITY_STAKE_SQL, nativeQuery = true)
nit: It might be better to put the docs and the SQL inline so docs show up when using the method and so future repository methods to this class don't separate the SQL from the method.
```suggestion
    /**
     * Algorithm to update pending reward: ...
     */
    @Modifying
    @Query(nativeQuery = true, value = """
        with ending_period_node_stake as (...
    """)
```

2022-08-24 20:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              where consensus_timestamp = (select max(consensus_timestamp) from node_stake)
Move `select max(consensus_timestamp), max(epoch_day) from node_stake` to a separate CTE then can avoid the duplicate `(select epoch_day from ending_period_node_stake limit 1)` sub-queries below.

2022-08-24 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        entityListener.onNodeStakes(nodeStakes);
We can't inline `entityStakeCalculator.update` here since we only do that asynchronously when the db transaction of the corresponding record file commits successfully.

We can still revert it back to `EntityListener.onNodeStake` by making `EntityStakeCalculatorImpl` also implementing RecordFileStreamListener, basically make it stateful. since we need to know if there's `NodeStake` in this session, if so, refresh the materialized view and publish the event; we do need to reset the flag to false in the `onStart` method.

2022-08-24 21:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +where type in ('ACCOUNT', 'CONTRACT');
we can and it'll be faster when we have many deleted accounts / contracts, since then the materialized view is smaller, and there'll be less number of rows to update in that large upsert sql.

2022-08-24 21:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    id                   bigint  primary key,
think I have already made the change to add the primary key in V2.0.3

2022-08-24 21:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +    @Query(value = UPDATE_ENTITY_STAKE_SQL, nativeQuery = true)
sure

2022-08-24 21:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    id                   bigint  primary key,
Ok, guess this comment was for an older changeset.

2022-08-24 21:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        entityListener.onNodeStakes(nodeStakes);
Right, was not saying to inline `entityStakeCalculator.update`. Instead, we would just call `entityStakeCalculator.calculate(List<NodeStake> nodeStakes)` (renamed from `onNodeStakes()`) and that would call `RecordStreamFileListener.flush()` like it does now. So no need for stateful classes.

Alternatively, we could add avoid exposing `RecordStreamFileListener.flush()` if we add a transient field to `NodeStake` that indicates it's the last `NodeStake` so we can trigger a flush internally within `SqlEntityListener`.

2022-08-24 21:46 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        entityListener.onNodeStakes(nodeStakes);
oh ok, now I get the idea. I think it's better to just add `calculate(List<NodeStake> nodeStakes)` to the interface `EntityStakeCalculator`, the implementation now no longer needs to implement `EntityListener`. Both approaches make NodeStakeUpdateTransactionHandler aware of the logic in EntityStakeCalculator, I'll vote for the more explicit one.

2022-08-25 14:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +create index if not exists entity_state_start__id on entity_state_start (id);
materialized views can't have primary key, I'll change it to a unique index here and in v1 will keep the index name.

2022-08-25 17:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +                  end) as pending_reward,
added one more case when there is no node stake info for the node an entity staked to in the ending staking period. Though I'm not sure if that's possible (e.g., community nodes come and go), having that logic can avoid potential bug in the future.

2022-08-25 20:33 UTC, steven-sheehy approved these changes
LGTM

2022-08-25 21:17 UTC, edwin-greene approved these changes
Looks good!

2022-08-25 22:24 UTC, steven-sheehy requested changes

2022-08-25 22:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.66.0__pending_reward.sql
> +create materialized view if not exists entity_state_start as
Need to fix migration version

2022-08-26 14:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.66.0__pending_reward.sql
> +create materialized view if not exists entity_state_start as
umm, look like we use 1.65.x for both 0.63 and 0.64 releases. nvm, I'll rename it to 1.65.x

2022-08-26 15:03 UTC, steven-sheehy approved these changes

2022-08-26 15:33 UTC, edwin-greene approved these changes

2022-08-26 15:51 UTC, merged