Add Node Stake Consensus
hashgraph/hedera-mirror-node pull request #4344
Opened 2022-08-23 19:49 UTC by edwin-greene

**Description**:
HIP 406 Add Consensus calculation via Node Stake. If the Node Stake Repository is empty, consensus will failover to signature consensus. 

**Related issue(s)**:

Fixes #3793

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-08-24 22:32 UTC, xin-hedera requested changes

2022-08-24 22:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        var staked = 0L;
```suggestion
        long stake = 0L;
```

2022-08-24 22:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        }
The `signatureHashMap` is a multimap of data file hash -> the corresponding list of signature files.

the logic here sum the node stake of all VERIFIED signature file regardless of the actual data file hash, this is not how it's done.

we should only sum the node stake of the VERIFIED signature file with the same `key`, if with this `key`, canReachConsensus is false, we move to the next `key`; otherwise, we shortcut and verification is successful

2022-08-24 22:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +    private CacheManager cacheManager;
can we not mock the cacheManager?

2022-08-24 22:46 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            var nodeAccountId = validatedSignatures.iterator().next().getNodeAccountId().getId();
`NodeStake.nodeId` is different than `NodeAccountId` in `validatedSignature`. We need to add the nodeAccountId to nodeId, or nodeId to nodeAccountId mapping into `AddressBook`

2022-08-25 19:35 UTC, steven-sheehy requested changes

2022-08-25 19:46 UTC, steven-sheehy requested changes

2022-08-25 19:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +                        .nodeId(EntityId.of(0L, 0L, 3L, EntityType.ACCOUNT).getId())
Not an account ID.
```suggestion
                        .nodeId(0)
```

2022-08-25 19:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +                .persist();
Consider moving to a helper method that takes in N stake values and generates the nodeStake since this logic is repeated in a few places:

```java
private void nodeStakes(long... stakes) {...}
```

2022-08-25 19:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +    private CacheManager cacheManager;
Agreed, we shouldn't convert this to an integration test since all other handler tests are unit tests. My suggestion above is to not use `CacheManager` directly anyway.

2022-08-26 21:29 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                    .orElse("unknown");
Thanks for spotting that, I have removed it and used `sigFilename` instead.

2022-08-26 21:29 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                            "next group: {}", message);
I've changed the message, it should not contain the same wording multiple times now.

2022-08-26 21:29 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        var staked = 0L;
Fixed.

2022-08-26 21:30 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        }
I've changed this section. Please double check that it is performing the calculation correctly.

2022-08-26 21:30 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +    private CacheManager cacheManager;
I've removed the usage of CacheManager.

2022-08-26 21:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            var nodeAccountId = validatedSignatures.iterator().next().getNodeAccountId().getId();
I've added some lines to get the `NodeAccountId` according to the `NodeId` from the `AddressBookEntry`.

2022-08-26 21:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +    }
Thanks I have made this change.

2022-08-26 21:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NodeStakeRepository.java
> +    @CacheEvict(allEntries = true, cacheManager = EXPIRE_AFTER_5M, cacheNames = NODE_STAKE_CACHE)
Sounds good, I have removed it.

2022-08-26 21:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        if (!nodeStakes.isEmpty()) {
I have made this change.

2022-08-26 21:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +            }
Thanks I have added a method to `NodeStakeRepository` instead of using `cacheManager`.

2022-08-26 21:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NodeStakeRepository.java
> +    @Cacheable(cacheManager = EXPIRE_AFTER_5M, cacheNames = NODE_STAKE_CACHE,
Sounds good, I have added a new `cacheManager` with a 24 hour expiration.

2022-08-26 21:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
>      public NodeSignatureVerifier(AddressBookService addressBookService,
Got it, I have updated it.

2022-08-26 21:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            signatureConsensus(signatures.size(), signatureHashMap, filename);
I have reworked this for the different verification versions to more closely follow the same code path.

2022-08-26 21:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        var nodeStakeMap = new HashMap<Long, Long>();
I haven't implemented this yet; with the change to using the Address Book Entries to obtain the NodeAccountIds, there could be a few different approaches. Can you look at the most recent version of this section and then provide a recommendation as to which way to go.

2022-08-26 21:35 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +                        .nodeId(EntityId.of(0L, 0L, 3L, EntityType.ACCOUNT).getId())
Fixed.

2022-08-26 21:35 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +                .persist();
Thanks I have added that helper method.

2022-08-29 19:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +                .persist();
I meant the helper method should have a for loop and generate the instances within the loop. But not a big deal and at least it's reduced the lines of code.

2022-08-29 21:27 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +                .persist();
I see, I have simplified it by adding a loop.

2022-08-29 22:44 UTC, steven-sheehy requested changes

2022-08-30 13:59 UTC, xin-hedera requested changes

2022-08-30 13:59 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +    private final NodeStakeRepository nodeStakeRepository;
nit, order field and remove extra empty line

2022-08-30 13:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +        assertTrue(e.getMessage().contains("Consensus not reached for file"));
assert FileStreamSignature.status is `VERIFIED` here. also assert accordingly in all test cases.

2022-08-30 13:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +    void evictNodeStakeCache() {
remove this test case, instead, do

- verify nodeStakeRepository.evictNodeStakecache() is called in all happy path with non-empty node stakes
- verify nodeStakeRepository.evictNodeStakecache()  is not called in all negative test cases + the one with empty node stakes

2022-08-30 20:37 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            if (!canReachConsensus(verifiedSignatureCount, totalStake)) {
Thanks I have removed it.

2022-08-30 20:37 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                    .forEach(entry -> nodeIdToNodeAccountIdMap.put(entry.getNodeId(), entry.getNodeAccountId()));
Awesome thanks, I have made this change.

2022-08-30 20:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            }
Got it, I have moved the `nodeAccountIds` construction to a single event outside of the validatedSignatures loop.

2022-08-30 20:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            if (canReachConsensus(staked, totalStake)) {
Thanks I have renamed them.

2022-08-30 20:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +    private final NodeStakeRepository nodeStakeRepository;
Thanks I have fixed it.

2022-08-30 20:39 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +        assertTrue(e.getMessage().contains("Consensus not reached for file"));
Great idea. I've added assertions for the different signature status'.

2022-08-30 20:39 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +    void evictNodeStakeCache() {
Thanks, I have removed that test case and added assertions into the existing cases.

2022-08-30 20:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            }
I don't think either approach is logically correct. You're summing the stake of all node account IDs even if they were for different file hashes. You should only sum the stake associated with that particular key (file hash).

2022-08-30 21:30 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +    }
this test case should fail since:

- there are 1 signature file from node3, and 1 signature file from node5
- the two signature files have different data file hashes
- the node stakes are 3 (node3), 4 (node4), 3 (node5)

So the signature files from node3 and node5 both only have a consensus ratio of 3/10, less than the required ratio 1/3. both status should be `VERIFIED`, not `CONSENSUS_REACHED`

2022-08-30 22:06 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +    }
Thanks I see, it is a side effect of the wrong node stake/file hash calculation. I have fixed this and added another test that goes more in depth.

2022-08-30 22:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +            }
Thanks Steven. I misunderstood Xin's first comment and broke this section. I have now fixed it and it should calculate correctly via filehash and also be optimized according to a proper understanding of Xin's comment.

2022-08-31 13:59 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +    void testFailedVerificationWithLessThanOneThirdNodeStakeConsensus() {
test case name doesn't match the actual scenario

2022-08-31 14:00 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-08-31 14:24 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-08-31 20:14 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +    void testFailedVerificationWithLessThanOneThirdNodeStakeConsensus() {
Thanks I have removed it since it seemed to be a duplicate of another test.

2022-08-31 22:35 UTC, steven-sheehy requested changes

2022-08-31 22:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +    private double consensusRatio = 0.33333333333d;
We should be exact like before and not approximate. You should be able to use BigDecimal in properties:

```suggestion
    private BigDecimal consensusRatio = BigDecimal.valueOf(1).divide(BigDecimal.valueOf(3));
```

2022-08-31 22:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +        long nodeThreeStake = 16_666_666_667L;
Should multiply hbars by 10^8 to convert to tinybars. Eithere here or in `nodeStakes()`

2022-08-31 22:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                .setScale(0, RoundingMode.CEILING);
Why do we need to round? Can't we just compare the two BigDecimals without scaling?

2022-09-01 14:28 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +    private double consensusRatio = 0.33333333333d;
`BigDecimal.ONE.divide(BigDecimal.valueOf(3))` causes an exception: 
                  `java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.` 
                  
But I can make it a BigDecimal like so: 
```
    private MathContext consensusRatioMathContext = new MathContext(11, RoundingMode.CEILING);
    @Max(1)
    @Min(0)
    private BigDecimal consensusRatio = BigDecimal.ONE.divide(BigDecimal.valueOf(3), consensusRatioMathContext);
    ```
    
 The scale of 11 may need to be increased, I will do some testing to get the exact precision needed.

2022-09-01 15:27 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                .setScale(0, RoundingMode.CEILING);
I've done some testing, without any rounding there are is a precision problem: 

```
var stakeRequiredForConsensus = BigDecimal.valueOf(totalStake)
                .multiply(commonDownloaderProperties.getConsensusRatio());
```

Yields: 
```
2022-09-01T09:19:41.352-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake: 3, Total Stake: 9 
2022-09-01T09:19:41.352-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Consensus Ratio: 0.3333333333333333334 
2022-09-01T09:19:41.352-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake required for consensus: 3.0000000000000000006 
2022-09-01T09:19:41.352-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Result: false 
```

This scaling setting has worked to get all the unit tests to pass: 
```
var stakeRequiredForConsensus = BigDecimal.valueOf(totalStake)
                .multiply(commonDownloaderProperties.getConsensusRatio())
                .setScale(1, RoundingMode.DOWN);
```

Correctly passing this test:
```
2022-09-01T09:22:40.715-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake: 3, Total Stake: 9 
2022-09-01T09:22:40.716-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Consensus Ratio: 0.3333333333333333334 
2022-09-01T09:22:40.716-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake required for consensus: 3.0 
2022-09-01T09:22:40.716-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Result: true
```                

And correctly failing this test: 
```
2022-09-01T09:22:40.326-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake: 1666666666666666666, Total Stake: 5000000000000000000 
2022-09-01T09:22:40.326-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Consensus Ratio: 0.3333333333333333334 
2022-09-01T09:22:40.327-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake required for consensus: 1666666666666666667.0 
2022-09-01T09:22:40.327-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Result: false 
```

2022-09-01 15:49 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImplTest.java
> +        long nodeThreeStake = 16_666_666_667L;
Sounds good, I converted them to tinybars for the tests.

2022-09-01 16:32 UTC, xin-hedera requested changes

2022-09-01 16:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                .setScale(1, RoundingMode.DOWN);
think we should set scale to 0 with round up.

`stake` won't have any decimals so doesn't make sense to set scale to 1 for `stakeRequiredForConsensus`. In addition if the required stake per the ratio is, e.g., 100.02, instead of scale 1 round down to 100.0, we should scale 0 and round up to get 101, so if `stake` is 100, it'll fail the check

2022-09-01 16:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                .setScale(1, RoundingMode.DOWN);
That setting fails one of the tests. If I have it right: 

```
        log.info("Stake: {}, Total Stake: {}", stake, totalStake);
        log.info("Consensus Ratio: {}", commonDownloaderProperties.getConsensusRatio());

        var stakeRequiredForConsensus = BigDecimal.valueOf(totalStake)
                .multiply(commonDownloaderProperties.getConsensusRatio())
                .setScale(0, RoundingMode.CEILING); // or RoundingMode.UP
                
        log.info("Stake Required For Consensus: {}", stakeRequiredForConsensus);
        log.info("Result: {}", BigDecimal.valueOf(stake).compareTo(stakeRequiredForConsensus) >= 0);
```        

Results in: 

```
2022-09-01T10:37:56.979-0600 INFO main c.h.m.i.d.ConsensusValidatorImplTest Executing: testVerifiedWithOneThirdNodeStakeConsensusNonVerifiedSignatures() 
2022-09-01T10:37:56.990-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake: 3, Total Stake: 9 
2022-09-01T10:37:56.990-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Consensus Ratio: 0.3333333333333333334 
2022-09-01T10:37:56.990-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Stake Required For Consensus: 4 
2022-09-01T10:37:56.990-0600 INFO main c.h.m.i.d.ConsensusValidatorImpl Result: false 
```

2022-09-02 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                .setScale(1, RoundingMode.DOWN);
i c.

we should then

- round down the ratio, i.e., `var consensusRatio = BigDecimal.ONE.divide(BigDecimal.valueOf(3), 19, RoundingMode.DOWN);`
- round up the required stake, i.e., `var required = stakeTotal.multiply(consensusRatio).setScale(0, RoundingMode.CEILING);`

2022-09-02 17:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                .setScale(1, RoundingMode.DOWN);
Sounds good, I have made those changes.

2022-09-02 17:50 UTC, xin-hedera approved these changes
LGTM

2022-09-02 18:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
>      @Min(0)
Add a `@NotNull` since now it's not a primitive.

2022-09-02 18:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        if (BigDecimal.ZERO.compareTo(commonDownloaderProperties.getConsensusRatio()) == 0
nit: Believe it can be simplified to equals
```suggestion
        if (BigDecimal.ZERO.equals(commonDownloaderProperties.getConsensusRatio())
```

2022-09-02 19:34 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
>      @Min(0)
Thanks I've added it.

2022-09-02 19:34 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +        if (BigDecimal.ZERO.compareTo(commonDownloaderProperties.getConsensusRatio()) == 0
Good idea, I've made this change.

2022-09-02 19:41 UTC, steven-sheehy approved these changes
LGTM

2022-09-02 19:42 UTC, xin-hedera approved these changes

2022-09-02 19:43 UTC, merged