add CallOperationType field to ContractAction
hashgraph/hedera-mirror-node pull request #4352
Opened 2022-08-24 20:14 UTC by lukelee-sl

Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>

**Description**:

Add column and field in relevant classes to support the addition of the CallOperationType to ContactActions.

**Related issue(s)**:

Fixes #4345 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-24 20:38 UTC, Nana-EC requested changes
Looking good.
migration column update and extra coverage opportunity

2022-08-24 20:38 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    call_operation_type smallint                       null,
There should always be an operation type. Add from services side at worst it'll be unknown iirc
```suggestion
    call_operation_type smallint                       not null,
```

2022-08-24 20:38 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                            .returns(contractAction.getCallOperationTypeValue(), ContractAction::getCallOperationType)
Please add 3 contractAction side car records to migrateContractSidecar() test.
One for CAL, one for CREATE and a 3rd one of your choice.
This will confirm coverage of parse for that flow also

Will need to use
```
TransactionSidecarRecord.newBuilder()
                .setActions(...)
```

2022-08-24 21:12 UTC, Nana-EC reviewed
Failing test fix suggestion

2022-08-24 21:12 UTC, Nana-EC commented on pom.xml
> +        <hedera-protobuf.version>0.30.0-alias-SNAPSHOT</hedera-protobuf.version>
In the `pubsub-messages.txt` file
do a search for
`,"declineReward":false}`
and replace with
`,"declineReward":false,"alias":""}`

That should fix the failing test in `PubSubRecordParserTest.java`

2022-08-24 21:20 UTC, lukelee-sl commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    call_operation_type smallint                       null,
will this work for existing rows?

2022-08-24 21:21 UTC, lukelee-sl commented on pom.xml
> +        <hedera-protobuf.version>0.30.0-alias-SNAPSHOT</hedera-protobuf.version>
that fixed the issue. thanks

2022-08-24 21:51 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractAction.java
> +    private int callOperationType;
Nit: Here and in many areas in the Mirror Node, variables are declared alphabetically and the values are assigned alphabetically in places like `DomainBuilder` and `ContractResultServiceImpl`.

2022-08-24 21:55 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +
Nit, can rearrange/optimize imports so that this import is listed beside the others from the same package.

2022-08-24 22:11 UTC, steven-sheehy requested changes
Tests are failing

2022-08-24 22:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    call_operation_type smallint                       null,
There are no existing rows at this time, so it's safe.

2022-08-24 22:13 UTC, xin-hedera requested changes

2022-08-24 22:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    call_operation_type smallint                       null,
make it int to match the type from protobuf
```suggestion
    call_operation_type integer                       null,
```

2022-08-24 22:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    call_operation_type smallint                       null,
you'll have to first set a default value and not null in the create, then drop the default value. clarification: only needed for V1 migration files. V2 always starts with an empty db or good data.

2022-08-25 16:34 UTC, lukelee-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        var contractActionRecord = TransactionSidecarRecord.newBuilder()
I tried creating this as 3 separate TransactionSidecarRecords but was getting a primary key collision error.

2022-08-25 17:18 UTC, lukelee-sl commented
Apparently, the issue with the Charts / install check is a known issue?

2022-08-25 17:29 UTC, steven-sheehy approved these changes
LGTM. Yes, the chart workflow needs to be fixed to work with forks.

2022-08-25 17:44 UTC, xin-hedera approved these changes
LGTM

2022-08-25 17:52 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        var contractActionRecord = TransactionSidecarRecord.newBuilder()
yeah this is fine. Thanks

2022-08-25 17:56 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        var contractActionRecord = TransactionSidecarRecord.newBuilder()
I forget the standard we were going for here. @steven-sheehy can clarify if this class method is okay or if RecordItemBuilder or something else needs to be updated and used

2022-08-25 17:57 UTC, Nana-EC approved these changes
LGTM
Unblocking and will leave further reviews to Mirror Node code owners

2022-08-25 17:58 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        var contractActionRecord = TransactionSidecarRecord.newBuilder()
Looks like you already got signs off. CLosing

2022-08-25 18:42 UTC, merged