Find ethereum and hedera transactions by eth hash
hashgraph/hedera-mirror-node pull request #4381
Opened 2022-08-29 10:55 UTC by dimitrovmaksim

**Description**:

Allows fetching Ethereum and Hedera transaction by eth hash using the `contract_result` tablen as discussed here https://github.com/hashgraph/hedera-mirror-node/pull/4176. Opened a new PR to start on a clean base.

**Related issue(s)**:

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/4175

**Notes for reviewer**:
Couple potential Issues:

1. Getting the transaction by `ID` still requires fetching the transaction from the `transaction` table, because `contract_result` does not have `valid_start_ns` column, which is required for that query. This results in queries by ID returning the full hedera hash, instead of the short eth hash, compared to fetching the transaction by hash, which will always return the short hash.
2. Fetching the transaction by `contract_id` and `consensus_timestamp` still uses the transaction table query. Looking into the tests i'm not sure if making that query use the `contract_result` table won't cause issues ([example test](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-rest/__tests__/specs/contracts/%7Bid%7D/results/%7Bid%7D/timestamp-result-not-found.json))
3. Also it seems that `contract_id` is completely ignored when querying transactions by contract_id/address and timestamp, and the contract_id/address are just format validated. More info here: https://github.com/hashgraph/hedera-mirror-node/issues/4380

 
**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-30 10:42 UTC, dimitrovmaksim commented
> LGTM. not sure why some of the tests are failing

The chart check fails because it tries to fetch https://raw.githubusercontent.com/**_hashgraph_**/hedera-mirror-node/4176-find-eth-and-hedera-tx-by-hash/hedera-mirror-rosetta/scripts/validation/postman/rosetta-api-postman.json ,but the correct url is https://raw.githubusercontent.com/**_dimitrovmaksim_**/hedera-mirror-node/4176-find-eth-and-hedera-tx-by-hash/hedera-mirror-rosetta/scripts/validation/postman/rosetta-api-postman.json

2022-08-30 20:52 UTC, steven-sheehy commented
> Not sure if this is because I'm opening the PR from a fork (I don't think i can push directly to the repo)

Right, we've been aware of it but hadn't gotten around to addressing it. There's a PR up now to fix it: https://github.com/hashgraph/hedera-mirror-node/pull/4387

2022-08-31 08:21 UTC, dimitrovmaksim commented
> Right, we've been aware of it but hadn't gotten around to addressing it. There's a PR up now to fix it: #4387

Looks like it's working now 👍🏻

2022-08-31 15:05 UTC, dimitrovmaksim commented
Hm, now that we can find non-ethereum transactions by the eth hash, we should somehow return nonce for the non-eth transactions as well

2022-09-01 01:29 UTC, Nana-EC requested changes
Looks good.
Just need to fix transaction type in test for non `ETHEREUMTRANSACTION` case

2022-09-01 01:29 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/by-hash-no-eth-tx.json
> +        "type": 50,
Type shouldn't be `50: 'ETHEREUMTRANSACTION'`
Try `7: 'CONTRACTCALL'` or ` 8: 'CONTRACTCREATEINSTANCE'`

2022-09-01 05:02 UTC, steven-sheehy requested changes

2022-09-01 05:14 UTC, steven-sheehy commented
> Fetching the transaction by contract_id and consensus_timestamp still uses the transaction table query. Looking into the tests i'm not sure if making that query use the contract_result table won't cause issues ([example test](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-rest/__tests__/specs/contracts/%7Bid%7D/results/%7Bid%7D/timestamp-result-not-found.json))

I do think we should also make `/api/v1/contracts/{id}/results/{timestamp}` and ``/api/v1/contracts/results/{timestamp}` not use the transaction table. I'm not sure the referenced test is valid anymore since we now create contract_result even for failures after https://github.com/hashgraph/hedera-mirror-node/pull/3182

2022-09-01 11:39 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/transactionService.js
>          `${EthereumTransaction.PAYER_ACCOUNT_ID} = $1`
Well, then doesn't this also apply for the timestamp query?

2022-09-05 11:24 UTC, dimitrovmaksim commented
Hey @steven-sheehy @Nana-EC I've pushed some changes, hopefully I understood and addressed the comments correctly.
Also I think this comments still remains as an issue https://github.com/hashgraph/hedera-mirror-node/pull/4381#issuecomment-1233061413

2022-09-07 15:22 UTC, Nana-EC approved these changes

2022-09-07 22:35 UTC, steven-sheehy requested changes
Looking good, just some nit picks and need to fix merge conflicts

2022-09-08 07:15 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +  static detailedContractResultsWithEthereumTransactionQuery = `select ${ContractResult.tableAlias}.*,
Hm, strange, maybe I have triggered a linter, because I'm pretty sure I did not format it like this 🤔

2022-09-08 12:32 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +                                                                ) as ${ContractResult.CONSENSUS_TIMESTAMP},
Hm i think I'll have to explicitly select both columns from the ContractResult table and set an alias, otherwise I think the columns will be prefixed with the tables aliases, because both columns exist in both tables.

2022-09-08 13:30 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +    return [rows.map((row) => new TransactionWithEthData(row)), rows.map((row) => new ContractResult(row))];
Technically the data represents a transaction, even if it's not fetched from the transaction table, also wouldn't it be more misleading if the contract result is not actually for an ethereum transaction, but is called EthereumTransaction?

2022-09-08 13:37 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +                                                                ) as ${ContractResult.CONSENSUS_TIMESTAMP},
Why? The consensus timestamp is a join column so it will be the same value in each column. So you just need to show one, no coalescing.

2022-09-08 13:37 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +  static detailedContractResultsWithEthereumTransactionQuery = `select ${ContractResult.tableAlias}.*,
Right, a linter does it automatically. But I believe if you put a newline after the ` you can force it to start earlier on the line.

2022-09-08 13:45 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +    return [rows.map((row) => new TransactionWithEthData(row)), rows.map((row) => new ContractResult(row))];
I think I get the idea, and if we want to make this change and EthereumTransaction to represent only ethereum transactions, and non-eth transactions to be represented by contractResult, we have to probably make changes to `ContractResultDetailsViewModel` to fetch some of the shared columns from contractResult, instead of transaction.

2022-09-08 14:33 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +                                                                ) as ${ContractResult.CONSENSUS_TIMESTAMP},
What i meant is that i'll have to select consensus_timestamp and gas_limit from the contract_result table explicitly, but i think re-arranging the query also fixed it

2022-09-08 18:36 UTC, steven-sheehy requested changes

2022-09-08 18:36 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      [ethTransactions, contractResults] = await ContractService.getContractResultsByTimestamps(
We should still do this operation in parallel with logs, state changes and block retrieval. We don't need to use `ethTransaction.consensusTimestamp` and can use the `transaction.consensusTimestamp` for all.

2022-09-08 19:40 UTC, dimitrovmaksim commented on hedera-mirror-rest/controllers/contractController.js
> +      [ethTransactions, contractResults] = await ContractService.getContractResultsByTimestamps(
This will work when fetching the transaction by Id, but what about when we try to fetch the transaction by hash?

2022-09-08 21:38 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      [ethTransactions, contractResults] = await ContractService.getContractResultsByTimestamps(
Actually, this highlights the fact that we're doing duplicate calls to get contract results for search by hash, right? Once for lookup by hash then again for lookup by timestamp. So you're right that we can't do in parallel for search by hash but we should fix the duplicate calls.

2022-09-09 04:15 UTC, dimitrovmaksim commented on hedera-mirror-rest/controllers/contractController.js
> +      [ethTransactions, contractResults] = await ContractService.getContractResultsByTimestamps(
That was the reason I moved the ContractResult queries to not be done in parallel, because previously it was doing duplicate calls. Currently for hash it does the same query as for timestamp, but it's filtering by hash instead.

2022-09-09 04:42 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      [ethTransactions, contractResults] = await ContractService.getContractResultsByTimestamps(
Nevermind, with the diff and the large else statement I couldn't tell that it wasn't duplicated. It looks good to me now on a second look.

2022-09-09 08:07 UTC, dimitrovmaksim commented on hedera-mirror-rest/controllers/contractController.js
> +    }
We should at least check that the consensusTimestamp is not undefined before doing the RecordFile, ContractLog and StateChange queries, maybe move the other check here and use the contractResult's consesusTimestamp for those queries?

2022-09-09 10:25 UTC, dimitrovmaksim commented on hedera-mirror-rest/controllers/contractController.js
> +      isFailedContractResult = ethTransaction.transactionType.toString() === ethereumTransactionType;
Is it even possible now to have an EthereumTransaction without a ContractResult?

2022-09-09 23:57 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      isFailedContractResult = ethTransaction.transactionType.toString() === ethereumTransactionType;
It is still possible. I believe we always create a result for contract call and contract create, but not for EthereumTransaction. It can occur when the ethereum transaction has an invalid payload and doesn't invoke the EVM.

2022-09-10 00:00 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +    }
If there is at least one contract result row or transaction row then the consensus timestamp within those is guaranteed to be present since it's a primary key of those.

2022-09-10 05:17 UTC, dimitrovmaksim commented on hedera-mirror-rest/controllers/contractController.js
> +      isFailedContractResult = ethTransaction.transactionType.toString() === ethereumTransactionType;
We currently do a left join, which if I'm not wrong won't return a row if a ContractResult with a specified hash/timestamp does not exists, but there's a matching record in the EthereumTransaction table

2022-09-10 14:13 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      isFailedContractResult = ethTransaction.transactionType.toString() === ethereumTransactionType;
If you think you see a bug, let's open a ticket. Meanwhile can we address the feedback so we can merge this?

2022-09-11 03:02 UTC, xin-hedera requested changes

2022-09-12 08:58 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +    ].join('\n');
Yeah, we discussed this here https://github.com/hashgraph/hedera-mirror-node/pull/4381#discussion_r967597201.

If I understand correctly:
1. If we leave it as it is, we will introduce a bug with this PR.
2. If we separate the queries, we will have once again to join `ethereum_transaction` and `transaction` in order to filter on the `transaction.result` until this `we can consider make another importer change to also persist transaction.result in ethereum_transaction table.` is eventually resolved
3. Can we leave it as it is atm, but if `contractResults` array is empty, we do an additional `ethereum_transation` query filtering on the hash/timestamp and see if there’s an `ethereum_transaction`, and if there’s one, create a default contract result, again until `result` is brought to the `ethereum_transaction` table and the queries can be separated?

Also one more thing worth bringing attention to, now that we query the `contract_result` table, we return `null` as `nonce` for the regular transactions, which is a problem. I can temporarily set it to return 0, instead of `null`, if this is okay

cc: @steven-sheehy @xin-hedera

2022-09-12 13:44 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +    ].join('\n');
approach 3 won't work, because with `contract_result cr left join etherem_transaciton ... where cr.hash = $1`, for when f ethereum transactions fail with certain codes, there won't be a corresponding row in `contract_result`.

Then for the rest API query with a transaction hash resulting in no rows returned from the left join, we can't tell if it's one of the two:

- No transaction (either normal SC or ethereum transaction) exists with the queried hash
- An ethereum transaction with those no-contract-result-row failures

2022-09-12 14:39 UTC, dimitrovmaksim commented on hedera-mirror-rest/service/contractService.js
> +    ].join('\n');
So approach 2? Move back the `ethereum_transaction` join on `transaction` to the TransactionService, query transactions and contract_results in parallel then check if contract results exists?

2022-09-12 15:01 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +    ].join('\n');
we can do that, and we can remove the join between `ethereum_transaction` and `transaction` when we make the importer change.

2022-09-16 15:00 UTC, steven-sheehy approved these changes

2022-09-16 15:02 UTC, xin-hedera approved these changes

2022-09-16 15:02 UTC, merged