Add transaction and block data to ContractLogs REST API
hashgraph/hedera-mirror-node pull request #4439
Opened 2022-09-09 14:13 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-09-12 14:23 UTC, xin-hedera requested changes

2022-09-12 15:34 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-09-12 21:35 UTC, steven-sheehy requested changes

2022-09-12 21:35 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        block_number:
Sort inline

2022-09-12 21:35 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/results/{id}/timestamp.json
> +        "block_number": 17
We should not add these fields to the contract result details APIs (`/api/v1/contracts/results/{idOrHash}` &
`/api/v1/contracts/{contractId}/results/{idOrHash}`) because it duplicates fields on the parent contract result response and because it incurs a performance penalty to load it from the DB.

2022-09-13 23:01 UTC, steven-sheehy approved these changes
LGTM

2022-09-14 00:14 UTC, xin-hedera approved these changes

2022-09-14 03:51 UTC, merged