feat: adding implementaion for BlockMetaSource and HederaEvmProperties
hashgraph/hedera-mirror-node pull request #4518
Opened 2022-09-20 09:57 UTC by nikolovyanko

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-17 12:17 UTC, IvanKavaldzhiev commented
GPG sign all of the commits.

2022-11-08 14:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/resources/application.yml
> +        evm-version: 298
I believe a correct evm-version would be `v0.30`

2022-11-08 14:54 UTC, IvanKavaldzhiev approved these changes
LGTM

2022-11-15 14:58 UTC, steven-sheehy requested changes

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/resources/application.yml
> +        max-gas-refund-percentage: 20
Move defaults to POJO. Also a reminder to use camelCase in yaml.

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +    RecordFileRepository repository;
```suggestion
    private RecordFileRepository repository;
```

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +        assertEquals(Hash.EMPTY, subject.getBlockHash(0));
Use assertj `assertThat()` for all assertions.

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +    private RecordFile recordFile(long timestamp) {
Replace with `DomainBuilder.recordItem().build()`

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +//    void blockValuesAreForCurrentBlockAfterSync() {
Remove or uncomment.

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +    RecordFile recordFile;
Don't mock domain objects.

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage;
```suggestion
    @Min(1)
    private int maxGasRefundPercentage = 20;
```

2022-11-15 14:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private Address fundingAccount;
Have you tested this with a Spring ApplicationContext? I don't think Spring will know how to convert this type. Either register a converter or use String and do the conversion yourself.
```suggestion
    @NotBlank
    private String fundingAccount = "";
```

2022-11-17 22:16 UTC, steven-sheehy requested changes

2022-11-17 22:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesTest.java
> +class MirrorNodeEvmPropertiesTest {
```suggestion
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
class MirrorNodeEvmPropertiesTest extends Web3IntegrationTest {
```

Then make MirrorNodeEvmProperties final and remove `@Autowired`

2022-11-17 22:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private boolean directTokenCall = false;
nit: Sort and put newlines between fields.

2022-11-18 07:49 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    public String evmVersion() {
We use only  `@setter`  lombok because the getters are actually matching the implemented  `EvmProperties` interface methods, using `@data` will produce additional methods duplicating the implemented ones.

2022-11-18 16:52 UTC, steven-sheehy requested changes

2022-11-18 16:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/RecordFileRepositoryTest.java
> +    private final DomainBuilder domainBuilder = new DomainBuilder();
Remove since now in `main` there's a `DomainBuilder` injected in `Web3IntegrationTest` that you can use. Plus that instance allows you to do persistence.

2022-11-18 16:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/RecordFileRepositoryTest.java
> +        recordFileRepository.save(recordFile2);
```suggestion
        domainBuilder.recordFile().persist();
        var latest = domainBuilder.recordFile().persist();
```

2022-11-18 16:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/resources/application.yml
> +        max-gas-refund-percentage: 20
Defaults still duplicated in application.yml

2022-11-18 16:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesTest.java
> +
License header. We'll work on the spotless automation soon so you won't get these license comments all the time. :)

2022-11-18 16:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +
License

2022-11-18 16:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +
License

2022-11-22 13:18 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/exception/EvmException.java
> +public abstract class EvmException extends RuntimeException {
Sonar smell `This class has 6 parents which is greater than 5 authorized.` is caused by the change, can we suppress it with `@SuppressWarnings("java:xxxx")`?

2022-11-22 20:28 UTC, steven-sheehy approved these changes
LGTM

2022-11-22 20:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/resources/application.yml
> +        directTokenCall: true
As mentioned 3 times, defaults should be specified in the POJO not application.yml. Especially not duplicated in two `application.yml`. But won't block merge if you want to address in a follow up.

2022-11-22 20:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/exception/EvmException.java
> +public abstract class EvmException extends RuntimeException {
Sure, I think having an exception hierarchy is a valid use of deep inheritance.

2022-11-23 15:52 UTC, steven-sheehy approved these changes
LGTM

2022-11-23 15:53 UTC, merged