Move the importer configuration section to new file, and add examples.
hashgraph/hedera-mirror-node pull request #4525
Opened 2022-09-21 03:29 UTC by MarcKriguerAtHedera

Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:

**Related issue(s)**:

Fixes #4097

**Notes for reviewer**:

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [N/A] Tested (unit, integration, etc.)

2022-09-21 17:10 UTC, steven-sheehy commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
This is confusing since you mention adding the below to your YAML file but then don't show the properties in YAML format. Change to multi-line YAML format.

2022-09-21 17:15 UTC, steven-sheehy commented on docs/importer/configuration.md
> +## Examples on how to configure the Mirror Node to only record transactions certain entities and transaction types
Too long

```suggestion
## Transaction Filtering
```

2022-09-21 17:24 UTC, steven-sheehy commented on docs/importer/configuration.md
> +
We should discuss how include and exclude impact each other when both are used.

2022-09-21 17:26 UTC, steven-sheehy commented on docs/importer/configuration.md
> +
We can probably combine these two examples to show a scenario that includes all contract transactions plus all cryptotransfers involving account X.

2022-09-21 17:27 UTC, steven-sheehy commented on docs/importer/configuration.md
> +### Example 1: only two particular entities, all transaction types
Too long. We should describe the use case in a sentence or two preceding the config, instead of in a header.

2022-09-21 17:28 UTC, steven-sheehy commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
I'm actually curious if it's possible to configure this list within a list via `.properties` files and as environment variables and what the syntax would be for that. Can you check?

2022-09-21 17:32 UTC, steven-sheehy commented on docs/importer/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.files`                 | true                           | Persist all file data to the database
We missed mentioning these various persist properties that can also be used for filtering. We don't necessarily have to duplicate their description below but we should point them out as another filtering mechanism and provide an example.

2022-09-21 20:54 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> -The Importer component uses [Spring Boot](https://spring.io/projects/spring-boot) properties to configure the
OK, I put the importer properties back into the table in `docs/configuration.md` (and reverted the small change to `docs/importer/README.md` that simply pointed at the new file in that directory where the subtable and discussion had been.  The two examples have been rolled into one, and that discussion is also in `docs/confiration.md` (but if you really wanted it moved into `docs/importer/README.md`. I can move it there.

2022-09-21 20:55 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
Actually, no -- is there a way to test without running the importer for days?  (Maybe we can discuss this outside the PR.)

2022-09-21 20:56 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +## Examples on how to configure the Mirror Node to only record transactions certain entities and transaction types
Done.

2022-09-21 20:57 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +
Done - this is now leading test (before the sample configuration).

2022-09-21 20:59 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +
Done -- I'm not sure (unless maybe with the use of wildcards) we would ever have an entity or contract type appearing in both the `exclude` and `include` lists, though.

2022-09-21 21:05 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +
As indicated above, I now have one example with 2 included entities, 4 included transaction types, and 1 excluded entities.  Wouldn't specifying account X in the :included entity" list also limits the results to only the contract transactions involving that account?

2022-09-21 21:05 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +### Example 1: only two particular entities, all transaction types
Done.

2022-09-21 21:08 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
As mentioned before, I am not really sure how to test this; even for the simple filter of just one included account number, even with a startTime specified to just before that account was created, wouldn't it take a few days to import just the transactions involving that account?

2022-09-21 21:09 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.files`                 | true                           | Persist all file data to the database
I have mentioned those properties (and included one in my example filter).

2022-09-21 21:13 UTC, MarcKriguerAtHedera commented
All of Steven's comments (except for the one about. testing with environment variables).  I still think I need a little background information (especially on how to test this meaningfully); until now, all I have done is test against previewnet and running for just a few hours against mainnet.

2022-09-23 17:30 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
I successfully tested the updated configurations (as  .yml, .properries, and environment variables) last night, and all three worked successfully.

2022-09-23 17:35 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
Now has an entity-only inclusion, an entity-and-transaction type inclusion, a transaction-type-only inclusion, and a single entity exclusion.

2022-09-23 17:37 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +
I think the newer version (with one "OR" specifying just entities, one just transaction type, and a third with both) makes it much clearer.

2022-09-23 17:38 UTC, MarcKriguerAtHedera commented on docs/importer/configuration.md
> +    `hedera.mirror.importer.parser.include.entity`:`[0.0.3,0.0.950]`
I now have the same configuration in all 3 formats (we decided against the command-line arguments, as the program is rarely invoked that way).  The environment vars *do* work (I did check).

2022-09-27 14:34 UTC, steven-sheehy requested changes

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +## Export transactions to PubSub
This and the header change below should be under `## Importer`
```suggestion
### Export transactions to PubSub
```

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +### Event and Entity Filtering
Event has a different meaning in hashgraph. We should use the `transaction` terminology here and in paragraph below.

```suggestion
### Transaction and Entity Filtering
```

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +In addition, the various boolean `hedera.mirror.importer.record.entity.persist` properties may be specified to control which fields get stored (you can think of this as which columns of the matching
The persist properties don't filter down columns/fields but whole tables.

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +* We are interested in all **CRYPTOTRANSFER** transactions, for all other accounts than **0.0.98**.
```suggestion
* We are interested in all **CRYPTOTRANSFER** transactions, for all accounts other than **0.0.98**.
```

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +## Connect to S3 with the Default Credentials Provider
```suggestion
### Connect to S3 with the Default Credentials Provider
```

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +            transaction: [FILECREATE, FILEDELETE, FILEUPDATE]
These account numbers are hard to remember to compare with the above scenario. Recommend using nice round numbers like `0.0.1000` and `0.0.1001` for one group and maybe a well known system files for the other.
```suggestion
          - entity: [0.0.1000, 0.0.1001]
          - entity: [0.0.101, 0.0.102]
            transaction: [FILEAPPEND, FILECREATE, FILEDELETE, FILEUPDATE]
```

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +will store only the transactions for the given scenario.
This is an incomplete sentence. Delete it or combine it with the intro statement. Perhaps something like this:

> To configure the above scenario via `application.yml`:

2022-09-27 14:34 UTC, steven-sheehy commented on docs/configuration.md
> +hedera.mirror.importer.parser.include[2].transaction[0]=CRYPTOTRANSFER
Order doesn't functionally matter, but perhaps we should keep everything in the same order for each example to reduce confusion. Here, the include CRYPTOTRANSFER should be the first

2022-09-27 18:24 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +#./hedera-mirror-importer/target/test-classes/config/application.yml Configuration
It was; it has also been reverted.

2022-09-27 18:24 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +## Export transactions to PubSub
Done.

2022-09-27 18:24 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +### Event and Entity Filtering
Done.

2022-09-27 18:25 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +In addition, the various boolean `hedera.mirror.importer.record.entity.persist` properties may be specified to control which fields get stored (you can think of this as which columns of the matching
Thanks for the clarification; I have changed the description.

2022-09-27 18:25 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +* We are interested in all **CRYPTOTRANSFER** transactions, for all other accounts than **0.0.98**.
Done.

2022-09-27 18:26 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +## Connect to S3 with the Default Credentials Provider
Done.

2022-09-27 18:30 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +            transaction: [FILECREATE, FILEDELETE, FILEUPDATE]
I have implemented your suggestions (but I am not aware of any "well known system files" -- will using 101/102 for one list and 1000/1001 for the other suffice?

2022-09-27 18:42 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +will store only the transactions for the given scenario.
I had originally thought the preliminary text and the subsequent text together formed a complete sentence, but I agree that it's easier to parse if that sentence isn't split by the example.  All three sample configurations now have the complete sentence before the example text.

2022-09-27 18:42 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +hedera.mirror.importer.parser.include[2].transaction[0]=CRYPTOTRANSFER
Good point.  All 3 examples are now ordered the same way,

2022-09-27 19:32 UTC, steven-sheehy commented on docs/configuration.md
> +          - entity: [0.0.1000, 0.0.1001]
Reverse these two. 0.0.101 and 102 are important system files that store the network address book. It makes sense that they are filtered by file transaction types.

2022-09-28 17:27 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +          - entity: [0.0.1000, 0.0.1001]
I hadn't been aware I had switched them -- sorry about that!   I will make the above change now.

2022-09-28 17:37 UTC, steven-sheehy approved these changes
LGTM

2022-09-28 20:47 UTC, merged