Use db owner in java migration when needed
hashgraph/hedera-mirror-node pull request #4528
Opened 2022-09-21 13:43 UTC by xin-hedera

**Description**:

This PR improves the importer integration test to use different db users for migration and regular processing

- Create db owner `mirror_node` and importer user `mirror_importer` in postgres test container
- Create a separate `JdbcTemplate` bean with db owner credentials
- Use the db owner `JdbcTemplate` bean in java migrations when needed

**Related issue(s)**:

Fixes #4474
Fixes #4475

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-09-21 13:45 UTC, xin-hedera commented on hedera-mirror-importer/src/test/resources/db/migration/v1/V1.10.0.1__fix_regular_db_user_privileges.sql
> +alter default privileges in schema public revoke all on tables from ${db-user};
the migration only runs in importer integration test. it's used to revert the excessive privilege granted to `db-user` in migration V1.10.0

```
alter default privileges in schema public
    grant all on tables to ${db-user};
```

2022-09-21 20:01 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2022-09-22 03:35 UTC, steven-sheehy requested changes

2022-09-22 03:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/JdbcTemplateConfiguration.java
> +public class JdbcTemplateConfiguration {
nit: With custom qualifier can make package private and final. Also make methods package private.
```suggestion
final class JdbcTemplateConfiguration {
```

2022-09-22 03:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
> +                                            @Qualifier(JDBC_TEMPLATE_OWNER) JdbcTemplate jdbcTemplate,
Would prefer a custom qualifier that can provide reuse in the future for non-JdbcTemplate use cases:

```java
@Qualifier
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.PARAMETER})
public @interface Owner {
}
```

2022-09-22 03:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/JdbcTemplateConfiguration.java
> +    }
Maybe we should duplicate the current `JdbcTemplateConfiguration` that we're replacing so it respects the existing properties. Can pull into a helper method.
```suggestion
	JdbcTemplate jdbcTemplate(DataSource dataSource, JdbcProperties properties) {
		JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
		JdbcProperties.Template template = properties.getTemplate();
		jdbcTemplate.setFetchSize(template.getFetchSize());
		jdbcTemplate.setMaxRows(template.getMaxRows());
		if (template.getQueryTimeout() != null) {
			jdbcTemplate.setQueryTimeout((int) template.getQueryTimeout().getSeconds());
		}
		return jdbcTemplate;
	}
```

2022-09-22 03:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/resources/db/scripts/init.sql
> +alter default privileges in schema public grant select on sequences to readonly;
nit: We can probably skip all the statements involving sequences considering we don't use sequences...

2022-09-22 15:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
> +                                            @Qualifier(JDBC_TEMPLATE_OWNER) JdbcTemplate jdbcTemplate,
added

2022-09-22 15:35 UTC, xin-hedera commented on hedera-mirror-importer/src/test/resources/db/scripts/init.sql
> +alter default privileges in schema public grant select on sequences to readonly;
removed those

2022-09-22 15:37 UTC, steven-sheehy approved these changes
LGTM

2022-09-22 15:58 UTC, merged