HIP-573 Custom fees blanket exemptions persistence code and test changes
hashgraph/hedera-mirror-node pull request #4537
Opened 2022-09-23 20:29 UTC by mgoelswirlds

**Description**:

This PR adds all_collectors_are_exempt to CustomFees in order to support [HIP-573 Custom fees blanket exemptions persistence]
* Added a new boolean all_collectors_are_exempt not null default false field to custom_fee in V1 and V2 migrations
* Updated protobuf version
* Added a field to CustomFee domain
* Populated field in DomainBuilder
* Populated proto field in RecordItemBuilder
* Updated EntityRecordItemListener.insertCustomFees() to persist the new field
* Updated relevant tests

**Related issue(s)**:

[Fixes #](https://github.com/hashgraph/hedera-mirror-node/issues/4508)

**Notes for reviewer**:
I have update existing tests which were breaking because of adding the new column. Also change the ReadMe to correctly show the custom_fees table contents.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-09-26 18:17 UTC, MarcKriguerAtHedera approved these changes
One single question about "Boolean" (versus "boolean") -- everything else looks good to me.

2022-09-26 18:17 UTC, MarcKriguerAtHedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/CustomFee.java
> +    private Boolean allCollectorsAreExempt;
Since you are declaring the value not null, wouldn't "boolean" (the primitive) better capture that?  The capitalized class could be null.

2022-09-26 19:17 UTC, edwin-greene commented on docs/design/custom-fees.md
> +    all_collectors_are_exempt   boolean not null default false
Nit: Keep columns in alphabetical order by putting `all_collectors_are_exempt` towards the top.

2022-09-26 19:18 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/CustomFee.java
> +
Same nit, in most places within the Mirror Node the variables tend to be placed alphabetically.

2022-09-26 19:20 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
Rather than updating the database as it was in V1.40.2, you can add a new file, in the same file pattern as the others, and that file will just have the addition of the new column. A good example to follow is: V1.65.7__contract_state_change_migration.sql

2022-09-26 19:21 UTC, xin-hedera requested changes

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
we generally can't change a released v1 migration. Instead, a new migration after the latest version in `main` is needed, which just alters the table `custom_fee` to add the new column

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    all_collectors_are_exempt   boolean not null default false
nit, order the columns

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/CustomFeeWrapper.java
> +        if(allCollectorsAreExempt!=null) {
format:

```suggestion
        if(allCollectorsAreExempt != null) {
```

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private FractionalFee.Builder fractionalFees() {
plural vs singular

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private FixedFee.Builder fixedFees() {
plural vs singular

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                                .setNumerator(0L)
nit, it makes more sense to have a non-0 numerator

2022-09-26 19:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +@lombok.RequiredArgsConstructor(onConstructor = @__(@org.springframework.beans.factory.annotation.Autowired))
nit:

```suggestion
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
```

2022-09-26 19:24 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +@lombok.RequiredArgsConstructor(onConstructor = @__(@org.springframework.beans.factory.annotation.Autowired))
`@RequiredArgsConstructor(onConstructor = @__(@Autowired))`

2022-09-26 19:52 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
Understood.

2022-09-26 19:52 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
Will change.

2022-09-26 20:03 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
@xin-hedera What about v2. I should add a separate file for that too?

2022-09-26 20:14 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                                .setNumerator(0L)
These were the defaults from DomainBuilder, so I just used them, but Mathematically it does make sense.

2022-09-26 20:18 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            customFee.setAllCollectorsAreExempt(false);
Is it just the spacing?

2022-09-26 20:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
Done.

2022-09-26 20:19 UTC, mgoelswirlds commented on docs/design/custom-fees.md
> +    all_collectors_are_exempt   boolean not null default false
Addressed.

2022-09-26 20:19 UTC, mgoelswirlds commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/CustomFee.java
> +    private Boolean allCollectorsAreExempt;
Addressed.

2022-09-26 20:19 UTC, mgoelswirlds commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .allCollectorsAreExempt(false);
Addressed.

2022-09-26 20:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private FractionalFee.Builder fractionalFees() {
Addressed.

2022-09-26 20:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private RoyaltyFee.Builder royaltyFees() {
Addressed.

2022-09-26 20:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    private FixedFee.Builder fixedFees() {
Addressed.

2022-09-26 20:20 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                                .setNumerator(0L)
Changed to non-zero.

2022-09-26 20:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    all_collectors_are_exempt   boolean not null default false
v2 is fine. we don't have a env with v2 schema db, so there is no concern of breaking history

2022-09-26 20:35 UTC, xin-hedera requested changes

2022-09-26 20:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.66.1__custom_fee_blanket_exemption_enhancement.sql
> +-- net_of_transfer, and royalty fraction
unrelated comment
```suggestion
```

2022-09-26 20:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.66.1__custom_fee_blanket_exemption_enhancement.sql
> +update custom_fee set all_collectors_are_exempt = false;
remove, since the column is added with `default false`, all existing rows with have `false` for `all_collectors_are_exempt`
```suggestion
```

2022-09-26 20:35 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    }
overlooked in last round of review.

the `fee` in `CustomFee` proto message is a `oneof`: https://github.com/hashgraph/hedera-protobufs/blob/6c3e6d37d9652bdb57600587d0218c9245eb513e/services/custom_fees.proto#L102-L118

it doesn't make sense to set all of the possibilities here since it ends up only honor the fractional fee as it's the last one set.

2022-09-26 20:35 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                  .receipt(r -> r.setTokenID(TokenID.newBuilder().setTokenNum(2).build()));
```suggestion
                  .receipt(r -> r.setTokenID(tokenId()));
```

2022-09-26 20:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            customFee.setAllCollectorsAreExempt(false);
no, since the column has default `false`, plus you changed it to the primitive `boolean`, it's redundant to set the default value here. but it's fine to leave it as is.

2022-09-26 21:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        fixedFee1.setAllCollectorsAreExempt(false);
change at least one custom fee with `allCollectorsAreExempt = true`

2022-09-26 22:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.40.2__custom_fees.sql
> +    token_id                    bigint not null
please revert any changes to this migration file

flyway calculates checksum on db migration file, even though the changes do not effectively alter the schema, flyway would still think it's different and running the artifact built with this change against any existing db with version > 1.42.0 will fail

2022-09-26 22:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.66.1__custom_fee_blanket_exemption_enhancement.sql
> +-------------------
change version to `V1.66.0` since this PR will likely get in before Edwin's.

2022-09-26 22:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/CustomFeeWrapper.java
> +        if(allCollectorsAreExempt!=null) {
bump this one

2022-09-26 23:51 UTC, MarcKriguerAtHedera approved these changes
requested changes look good to me.

2022-09-26 23:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    //This custom fee is for testing purpose and therefore we are just setting the fixed fee.
nit: Can probably remove this comment since everything in this file is for testing purposes and it's assumed we always just pick one example approach.

2022-09-26 23:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/CustomFeeWrapper.java
> +        if(allCollectorsAreExempt!=null) {
Various spacing issues in the PR. Make sure you configure IDEA actions on save to reformat code, optimize imports, rearrange code, and run code cleanup.

2022-09-28 14:48 UTC, steven-sheehy approved these changes
LGTM

2022-09-28 15:17 UTC, merged