Contract state REST API
hashgraph/hedera-mirror-node pull request #4548
Opened 2022-09-26 11:17 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #4484

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-09-26 11:20 UTC, natanasow commented
Still in progress as [this](https://github.com/hashgraph/hedera-mirror-node/issues/4476) should be implemented and [this conversation](https://github.com/hashgraph/hedera-mirror-node/issues/4484#issuecomment-1253467554) should be resolved.

2022-10-12 03:41 UTC, steven-sheehy requested changes

2022-10-12 03:41 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/state/no-params.json
> +  "urls": ["/api/v1/contracts/5001/state"],
We should test multiple path params:
```suggestion
  "urls": [
    "/api/v1/contracts/0.0.5001/state",
    "/api/v1/contracts/0.5001/state",
    "/api/v1/contracts/5001/state",
    "/api/v1/contracts/62cf9068fed962cf9aaabbb962cf9068fed9dddd/state",
    "/api/v1/contracts/0.62cf9068fed962cf9aaabbb962cf9068fed9dddd/state",
    "/api/v1/contracts/0.0.62cf9068fed962cf9aaabbb962cf9068fed9dddd/state",
    "/api/v1/contracts/0x62cf9068fed962cf9aaabbb962cf9068fed9dddd/state"
  ],
```

2022-10-12 03:41 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultStateViewModel.js
> +    this.slot = toHexString(contractState.slot, true, 64);
I think we should also add a `timestamp` field that maps to `contract_state.modified_timestamp`.

2022-10-12 03:41 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/state/invalid-contract.json
> +  "description": "Contract state api call for a contract with invalid contract",
We should have a spec for 404 not found when evm address lookup fails.

2022-10-12 03:41 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/state/slot-param-lt-lte-eq.json
> +    "/api/v1/contracts/5001/state?slot=eq:1"
Also add `slot=1` for when there's no operator.

2022-10-12 04:14 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +    select ${ContractState.CREATED_TIMESTAMP},
We don't use created_timestamp so can omit.

2022-10-13 15:14 UTC, natanasow commented
@steven-sheehy 
Most of the comments are resolved, so could you take another look? Only the apidoc is left over and should be ready by the end of tomorrow.

2022-10-13 15:14 UTC, natanasow commented
@steven-sheehy 
Most of the comments are resolved, so could you take another look? Only the apidoc is left over and should be ready by the end of tomorrow.

2022-10-13 18:40 UTC, MarcKriguerAtHedera approved these changes
Looks good (once everything already mentioned by @steven-sheehy  is taken care of).

2022-10-14 03:17 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      const lastSlot = parseInt(lastRow.slot);
Still needs to be addressed.

2022-10-14 03:17 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/state/invalid-contract.json
> +  "description": "Contract state api call for a contract with invalid contract",
Still missing

2022-10-14 03:31 UTC, steven-sheehy requested changes

2022-10-14 03:31 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +      ret = isHexPositiveInt(val, true) && _.includes(basicOperators, op);
We also need to check that it's length without 0x prefix is between 1 and 64 characters.

2022-10-14 03:31 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +              value: Buffer.from(filter.value.replace('0x', ''), 'hex'),
We should accept less than 64 characters then pad it to 64 characters so the user can avoid having to type `0x000000...1` and just have `0x1`. The database value will always be zero padded so that it sorts properly.

2022-10-14 03:31 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/no-params.json
> +    "/api/v1/contracts/0000000000000000000000000000000000001389/state",
We should have a spec where it looks up by non-zero form of EVM address. This does a separate lookup in entity table for the contract that we're not testing. We should also have a spec that returns 404 when this EVM address lookup fails.

2022-10-14 03:31 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/slot-param-gt-gte-eq.json
> +        "value": "0000000000000000000000000000000000000000000000000000000000000001"
The value will not be zero-padded in the database so should remove the zeros in all specs. Slots will be zero-padded to sort properly.

2022-10-14 03:31 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/slot-param-gt-gte-eq.json
> +    "/api/v1/contracts/5001/state?slot=0x0000000000000000000000000000000000000000000000000000000000000002"
Add one or more URLs where the slot is in the short form and with and without `0x` prefix. e.g. `slot=0xab`, `slot=ab`, `slot=0000000000000000000000000000000000000000000000000000000000000002`

2022-10-14 03:31 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/invalid-contract.json
> +        "value": "0000000000000000000000000000000000000000000000000000000000000001"
Should have an `invalid-params.json` that checks slot greater than 64 chars, invalid chars, invalid limit, invalid order, etc.

2022-10-14 13:17 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +      ret = isHexPositiveInt(val, true) && _.includes(basicOperators, op);
Unless we think we might support small decimal slot values. Then we can accept numbers without 0x and assume it doesn't need hex conversion.

2022-10-14 14:45 UTC, xin-hedera requested changes

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      required: true
these two path params are duplicate and the only difference is `contractIdOrAddressPathParam` allows `0x` prefix for the evm address, which is correct. So we should remove `contractIdPathParam` and change all references to `contractIdOrAddressPathParam`.

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +
move this block out of the function to be a module scope const.

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +      ret = hasLengthBetween(val, 1, 64, true) && isNumeric(val) && _.includes(basicOperators, op);
slot should be a hex string with optional `0x` prefix

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/service/baseService.js
>      }
believe the code before the change has a bug on `$${i + params.length}`, we should change it and also make it easier to read

```javascript
    for (let i = 0; i < whereQuery.length; i++) {
      const query = whereQuery[i];
      params.push(query.param);
      where += `${i === 0 ? '' : 'and'} ${query.query} $${params.length}`;
    }
```

with the recommended change, we shouldn't need the additional `incrementWithParamsLength = true` function param

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +    const {where, params} = this.buildWhereSqlStatement(whereConditions, [], false);
don't see anywhere multiple `slot eq` query params are handled, e.g., when we have `slot=0x...&slot=0x...` in the URL, we should transform it to the SQL expression `slot in ($1, $2)`

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/slot-param-eq.json
> +    "/api/v1/contracts/5001/state?slot=eq:0x0000000000000000000000000000000000000000000000000000000000000002",
need at least one integration test with a slot value containing characters in `a-f`

2022-10-14 14:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  value: 1,
should use either hex string or `Buffer` as default value

2022-10-17 13:57 UTC, xin-hedera requested changes

2022-10-17 14:50 UTC, natanasow commented on hedera-mirror-rest/service/baseService.js
> +  }
So what's the end goal here? Remove the current implementation and implement only `slot in ($1, $2...)` for operator `eq` and allow multiple slot fields with operators different than `eq` wrapped in `and` statement? 

Alternatively, we can create a new task and I could fix it there and release/merge this PR, including the current implementation in `0.67.0` if you think it's not a critical issue.

2022-10-17 15:17 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/invalid-contract.json
> +        "value": "0000000000000000000000000000000000000000000000000000000000000001"
We should add additional URLs to `invalid-params.json` to check the above scenarios.

2022-10-18 00:33 UTC, MarcKriguerAtHedera submitted a review, later dismissed
I think that (once the comments that Xin and Steven already raised) are handled, it will be ready to merge (Sorry, my view does show the files as Outdated; perhaps all these changes were already made.)

2022-10-18 02:43 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-10-18 02:46 UTC, xin-hedera approved these changes
LGTM

2022-10-18 02:52 UTC, steven-sheehy approved these changes

2022-10-18 03:01 UTC, xin-hedera approved these changes

2022-10-18 03:12 UTC, merged