Add support for S3 failover
hashgraph/hedera-mirror-node pull request #4553
Opened 2022-09-26 16:47 UTC by steven-sheehy

**Description**:

* Add a `ConsensusNode` abstraction and use it everywhere instead of node account IDs or calling the address book multiple times per file
* Add a connection timeout property and increase it to 5s to avoid occasional connection errors.
* Add `hedera.mirror.importer.downloader.sources` properties that grandfathers legacy `hedera.mirror.importer.downloader` properties as the primary source in list
* Change stream file persistence to write files to a node ID based path
* Increase downloader batch size to 100 to improve historical sync speed
* Refactor `Downloader` to push S3 logic into `StreamFileProvider` abstraction
* Replace `hedera.mirror.importer.downloader.*.batchSize` with generic `hedera.mirror.importer.downloader.batchSize`
* Replace `hedera.mirror.importer.downloader.*.threads` with generic `hedera.mirror.importer.downloader.threads`
* Remove `hedera.mirror.importer.downloader.*.prefix` in favor of existing `StreamType` properties

**Related issue(s)**:

Fixes #54

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-09-26 21:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/S3StreamFileProvider.java
> +
Need license

2022-09-26 21:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/S3StreamFileProvider.java
> +
Fixed, thanks

2022-09-27 03:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> -                .collect(groupingBy(StreamFilename::getInstant, maxBy(StreamFilename.EXTENSION_COMPARATOR)));
I removed the grouping by instant functionality. This would only occur when the account balance csv and pg.gz file were uploaded simultaneously for a short period of time. It's fine to download either one as they're both equally valid so we can simplify our logic to just rely on the single layer of grouping by `StreamFilename` via the multimap.

2022-09-27 19:16 UTC, edwin-greene approved these changes
Looks good to me.

2022-09-29 15:58 UTC, xin-hedera requested changes
looks good!

2022-09-29 15:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                filename = signature.getFilename();
can set `totalStake = signature.getNode().getTotalStake()` here to avoid the same pattern used to calculate `stakeRequiredForConsensus`

2022-09-29 15:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/DownloaderProperties.java
> +    default Path getNodeStreamPath(Long nodeId) {
```suggestion
    default Path getNodeStreamPath(long nodeId) {
```

2022-09-29 15:58 UTC, xin-hedera commented on pom.xml
> +        <version>2.7.3</version>
should revert? I see you approved and merged the version bump PR to 2.7.4

2022-09-29 18:24 UTC, steven-sheehy commented on pom.xml
> +        <version>2.7.3</version>
Thanks, meant to revert that.

2022-09-29 18:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/DownloaderProperties.java
> +    default Path getNodeStreamPath(Long nodeId) {
Changed

2022-09-29 18:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/ConsensusValidatorImpl.java
> +                filename = signature.getFilename();
Moved both of them up.

2022-09-29 18:27 UTC, xin-hedera approved these changes
LGTM

2022-09-29 19:33 UTC, edwin-greene approved these changes
Looks good

2022-09-29 20:32 UTC, mgoelswirlds approved these changes
lgtm

2022-09-29 20:35 UTC, merged