Add Token Account History Table 2
hashgraph/hedera-mirror-node pull request #4557
Opened 2022-09-26 20:27 UTC by edwin-greene

2022-09-27 17:09 UTC, MarcKriguerAtHedera submitted a review, later dismissed
Looks good to me/

2022-09-27 19:49 UTC, xin-hedera requested changes

2022-09-27 19:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration.test.js
> +      .filter((f) => f.endsWith('account-id.json'))
revert temporary change

```suggestion
      .filter((f) => f.endsWith('account-id.json'))
```

2022-09-27 19:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/tokens/account-id.json
> +        "account_id": "0.0.3",
revert, since it makes `account_id` the same as `token_id`

2022-09-27 19:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/tokens/account-id.json
> +        "kyc_status": 1
need to set correct timestamp range, `created_timestamp = 1234567890000000006` and `timestamp_range = [0,)` don't match

instead, we can change `integrationDomainOps` to have `timestamp_range: null` as default, and after the merge, set it to `[${created_timestamp}, )` if it's still `null`

2022-09-27 22:52 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TokenAccountMigrationTest.java
> +@TestPropertySource(properties = "spring.flyway.target=1.65.12")
just a note, we need to change it to `1.66.0` once Mugdha's PR merges.

2022-09-28 14:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      last.token_id = existing.token_id and last.associated is true
remove
```suggestion
```

2022-09-28 14:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    coalesce(kyc_status, e_kyc_status, 0),
have to use the same `case when ... when ... else ... end` in the main query

2022-09-28 14:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      else coalesce(existing.freeze_status, e_freeze_status, 0)
```suggestion
                      else e_freeze_status
```

2022-09-28 14:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                        else coalesce(existing.kyc_status, e_kyc_status, 0)
```suggestion
                        else e_kyc_status
```

2022-09-28 14:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      last.token_id = existing.token_id and last.associated is true
remove
```suggestion
```

2022-09-28 14:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                  ) on conflict (account_id, token_id) do
```suggestion
                where upper(existing.timestamp_range) is null
                on conflict (account_id, token_id) do
```

2022-09-28 19:57 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .timestampRange(Range.closedOpen(timestamp, timestamp()))
Thanks I have changed this to `Range.atLeast`

2022-09-28 19:57 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .accountId(entityId(ACCOUNT).getId())
Fixed.

2022-09-28 19:57 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .tokenId(entityId(TOKEN).getId());
Fixed

2022-09-28 20:00 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Thanks, I have reworked this so that it returns `lastTokenAccount`. It should be tested by `SqlEntityListenerTest.onTokenAccountDissociate()` where it sends a duplicate: 

```
        // when
        sqlEntityListener.onTokenAccount(associate);
        sqlEntityListener.onTokenAccount(dissociate);
        sqlEntityListener.onTokenAccount(dissociate);
        completeFileAndCommit();
```

2022-09-28 20:01 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Thanks ok. I have reworked it so that the tests meet those criterion and I have removed this if statement.

2022-09-28 20:01 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchUpserterTest.java
> +        }
Got it I have removed these statements and now the callers will provide the timestampRange.

2022-09-28 20:01 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchUpserterTest.java
> +                .extracting(ta -> ta.getCreatedTimestamp(), TokenAccount::getFreezeStatus)
Thanks I have made this change.

2022-09-28 20:02 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchUpserterTest.java
> +                );
Thanks I have added the timestampLower to the test.

2022-09-28 20:02 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integration.test.js
> +      .filter((f) => f.endsWith('account-id.json'))
Thanks for spotting this, I have reverted it.

2022-09-28 20:03 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/tokens/account-id.json
> +        "account_id": "0.0.3",
I see, I have fixed it to a new account id. If it was reverted then the test fails as there a duplicate token accounts (via the new primary key) sent to the integration db ops.

2022-09-28 20:04 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/tokens/account-id.json
> +        "kyc_status": 1
I see, I have fixed this.

2022-09-28 20:04 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TokenAccountMigrationTest.java
> +@TestPropertySource(properties = "spring.flyway.target=1.65.12")
Got it I have merged in the new main and updated the version.

2022-09-28 20:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    distinct coalesce(existing.account_id, e_account_id, null),
I have removed the distinct.

2022-09-28 20:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                ),
Thanks I have changed the CTE.

2022-09-28 20:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    coalesce(kyc_status, e_kyc_status, 0),
Thanks I have updated it to include the same `case when...`.

2022-09-28 20:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      else coalesce(existing.freeze_status, e_freeze_status, 0)
Got it I have made this change.

2022-09-28 20:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                        else coalesce(existing.kyc_status, e_kyc_status, 0)
Got it.

2022-09-28 20:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                        TokenKycStatusEnum.NOT_APPLICABLE, Range.atLeast(6L))
I have added this test, but to get the history table correct, I needed to add back in a where clause that I had previously removed: 

```
temp_history
...
where
(existing.created_timestamp is not null or last.created_timestamp is not null) and
upper(timestamp_range) is not null
```

2022-09-28 20:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(tokenAccountRepository.findAll()).containsExactly(tokenAccountMerged);
I have added the test for the history table.

2022-09-28 21:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      last.token_id = existing.token_id and last.associated is true
I have removed this.

2022-09-28 21:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                last as (
Thanks I have simplified the sql and removed the `last` CTE.

2022-09-28 21:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      last.token_id = existing.token_id and last.associated is true
I have removed this.

2022-09-28 21:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                      last.token_id = existing.token_id and last.associated is true
Thanks I have removed this.

2022-09-28 21:44 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
My IntelliJ optimize imports has somehow changed the order; I will need to fix this.

2022-09-29 14:56 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
I have fixed this.

2022-09-29 14:56 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                  ) on conflict (account_id, token_id) do
Thanks I have updated this.

2022-09-29 14:59 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    (timestamp_range is not null and upper(timestamp_range) is not null)
I have updated this.

2022-09-30 14:28 UTC, steven-sheehy requested changes

2022-09-30 14:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        var merged = mergeTokenAccount(tokenAccountState.get(tokenAccount.getId()), tokenAccount);
The merge methods are intended for use with `map.merge`. This avoids a separate get and a put.

2022-09-30 14:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (lastTokenAccount.getTimestampRange().equals(newTokenAccount.getTimestampRange())) {
Can we remove this? This should never occur.

2022-09-30 14:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                  created_timestamp = excluded.created_timestamp,
Immutable fields should not be updatable. This should be removed.

2022-09-30 14:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                with existing as (
Please open a ticket to convert token account to use `GenericUpsertQueryGenerator`.

2022-09-30 14:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        var merged = mergeTokenAccount(tokenAccountState.get(tokenAccount.getId()), tokenAccount);
Xin already fixed.

2022-09-30 14:46 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                  created_timestamp = excluded.created_timestamp,
There are some tests that have the created timestamp updated with a token lifecycle dissociate/reassociate: 

https://github.com/hashgraph/hedera-mirror-node/blob/bac304262e2fa651724190230ea850b783aade84/hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java#L1412

2022-09-30 14:55 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAccount.java
> +@Upsertable
Fixed.

2022-09-30 14:55 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/TokenAccount.java
> +@javax.persistence.Entity
Thanks I have removed the explicit package.

2022-09-30 14:56 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .tokenId(entityId(TOKEN).getId());
I have updated them to be consistent.

2022-09-30 14:56 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/tokens/account-id.json
> +        "account_id": "0.0.4",
Ah I see. I have updated it to 5.

2022-09-30 14:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (lastTokenAccount.getTimestampRange().equals(newTokenAccount.getTimestampRange())) {
The lastToken == null check has been removed.

2022-09-30 15:09 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                with existing as (
Sounds good. I have opened a ticket: 
https://github.com/hashgraph/hedera-mirror-node/issues/4576

2022-09-30 15:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (lastTokenAccount.getTimestampRange().equals(newTokenAccount.getTimestampRange())) {
Re-add the `log.warn("Skipping duplicate token account association: {}", tokenAccount);` here since this is an abnormal flow. Also, add a comment that this is to workaround services bug https://github.com/hashgraph/hedera-services/issues/3240 so we know why we have this weird hack is here.

2022-09-30 16:45 UTC, xin-hedera approved these changes
LGTM, not on the part I changed

- v1 migration and migration test
- rosetta

2022-09-30 17:36 UTC, steven-sheehy approved these changes
LGTM

2022-09-30 17:37 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (lastTokenAccount.getTimestampRange().equals(newTokenAccount.getTimestampRange())) {
Sounds good I have added the log like so: 

```
       if (lastTokenAccount.getTimestampRange().equals(newTokenAccount.getTimestampRange())) {
            // The token accounts are for the same range, accept the previous one
            // This is a workaround for https://github.com/hashgraph/hedera-services/issues/3240
            log.warn("Skipping duplicate token account association: {}", newTokenAccount);
            return lastTokenAccount;
        }
```

2022-09-30 17:42 UTC, xin-hedera approved these changes

2022-09-30 17:51 UTC, merged