04478 expand entity filtering
hashgraph/hedera-mirror-node pull request #4566
Opened 2022-09-28 17:57 UTC by MarcKriguerAtHedera

**Description**:

**Related issue(s)**:

Fixes #4478

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (existing + new unit tests in CommonParserPropertiesTest.java)

2022-09-29 20:18 UTC, steven-sheehy requested changes

2022-09-29 20:18 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
The above is too verbose and has a high cognitive complexity. We should:
* Encapsulate the building of this filter in a separate method. 
* Conditionalize the construction of this `TransactionFilterFields` based upon whether there are any filters for performance reasons
* Construct a static object `TransactionFilterFields.EMPTY` for the common no-filter path
* Check token ID
* Remove null since HashSet allows null and some entityIds can be null (probably only `transaction.entityId`)

```java
    private TransactionFilterFields getTransactionFilterFields(EntityId entityId, RecordItem recordItem) {
        if (!commonParserProperties.hasFilter()) {
            return TransactionFilterFields.EMPTY;
        } else if (!commonParserProperties.hasEntityFilter()) {
            return new TransactionFilterFields(Set.of(), type);
        }

        var entities = new HashSet<EntityId>();
        entities.add(entityId);
        entities.add(recordItem.getPayerAccountId());

        recordItem.getRecord().getTransferList().getAccountAmountsList().forEach(accountAmount ->
                entities.add(EntityId.of(accountAmount.getAccountID()))
        );

        recordItem.getRecord().getTokenTransferListsList().forEach(transfer -> {
            entities.add(EntityId.of(transfer.getToken()));

            transfer.getTransfersList().forEach(accountAmount ->
                    entities.add(EntityId.of(accountAmount.getAccountID()))
            );

            transfer.getNftTransfersList().forEach(nftTransfer -> {
                entities.add(EntityId.of(nftTransfer.getReceiverAccountID()));
                entities.add(EntityId.of(nftTransfer.getSenderAccountID()));
            });
        });

        entities.remove(null);
        return new TransactionFilterFields(entities, recordItem.getTransactionType());
    }

```

2022-09-29 23:01 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionFilterFields.java
> +    public TransactionFilterFields(EntityId entityId, TransactionType transactionType) {
Done.  Why I was in the process of editing CommonParserPropertiesTest, it was possible to create an instance of TransactionFilterFields with either a single EntityId or a Collection of them.  That test now always uses a Collection (generating it via Collections.singleton if there's just one entity).  So I can safely delete this constructor (and just did).

2022-09-29 23:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +        private boolean matches(Collection<EntityId> e) {
Done.

2022-09-29 23:03 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        // Issue 4478: regardless of transaction type, we always filter on payer account and transfer receivers/senders
Ok, I kept the rest of the comment (just above the new `getTransactionFilterFields()` method), but without the issue number.

2022-09-29 23:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (entityId != null) {
I originally was going to suggest `removeAll`, but since it's a `Set`, there can only be one to remove (and `removeAll(null)` throws an NPE).  Perfect -- that very much simplifies the logic!

2022-09-29 23:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Done.  Previously, there was a single test in `EntityRecordItemListenerNonFeeTransferTest` that created an invalid EntityId (it was a 1 followed by a whole lot of 0's), but that test is no longer changing in this PR.

2022-09-29 23:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            List<AccountAmount> accountAmountsList = body.getCryptoTransfer().getTransfers().getAccountAmountsList();
Done.  I wasn't quite sure which lists to iterate on -- thank you for the clarification.

2022-09-29 23:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (body.hasCryptoTransfer()) {
Done.

2022-09-29 23:12 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Thank you.  I have implemented all your suggestions (using the new method you defined above), except for the second and fourth lines (neither `commonParserProperries.hasFilter()` nor `commonParserProperties.hasEntityFilter()` would compile.  I believe my replacement line for `hasFilter()` is efficient and easy to understand, but I am not so sure about my 15-line implementation of `hasEntityFilter()` -- I expect these 15 lines may be the one part of this PR that needs additional tweaking (but please let me know).

2022-09-30 15:59 UTC, steven-sheehy requested changes

2022-09-30 15:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionFilterFields.java
> +    public static final TransactionFilterFields EMPTY = new TransactionFilterFields(Set.of(), TransactionType.UNKNOWN);
Believe this would only match transactions of type UNKNOWN (a special type for when we don't understand how to parse it yet) instead of all transactions. It should probably be null then you handle the null case explicitly in the filter.

2022-09-30 15:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (!filter.getEntity().isEmpty()) {
GitHub indicates at least 4 areas where codecov denotes lack of test coverage. Please address so that there's no codecov warnings in the PR diff.

2022-09-30 15:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (commonParserProperties.getInclude().isEmpty() && commonParserProperties.getExclude().isEmpty()) {
When I said `commonParserProperties.hasFilter()` I meant add a function called that and push this logic into that. We should use the [Tell Don't Ask](https://martinfowler.com/bliki/TellDontAsk.html) principle to encapsulate logic with the data where possible. Same comment for the else statement.

2022-09-30 15:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    entities.add(EntityId.of(accountAmount.getAccountID()))
nit: Inconsistent spacing in this method with extra indentation on some lines. Please ensure 4 spaces per indentation level. Please ensure your save actions in intellij are set.

2022-09-30 15:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Perhaps this `hasEntityFilter?` optimization is not worth the extra lines of code and processing. We can do without this one and just keep the other `hasFilter`.

2022-09-30 18:19 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (!filter.getEntity().isEmpty()) {
All but one of the missing coverage ares were in the "getEntityFilter" method, now removed.  Added test for the one other missed coverage area.

2022-09-30 18:19 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        if (commonParserProperties.getInclude().isEmpty() && commonParserProperties.getExclude().isEmpty()) {
Ah, I hadn't originally understood, but makes perfect sense.  "hasFilter()" moved; other method removed as per later suggestion.

2022-09-30 18:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    entities.add(EntityId.of(accountAmount.getAccountID()))
It was a tab-vs-space issue, now fixed.

2022-09-30 18:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Agreed.  Removed now.

2022-09-30 22:16 UTC, steven-sheehy approved these changes
LGTM

2022-09-30 22:17 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-09-30 23:04 UTC, steven-sheehy approved these changes

2022-09-30 23:16 UTC, merged