HIP-573 Adding all_collectors_are_exempt to the rest api and respective tests.
hashgraph/hedera-mirror-node pull request #4567
Opened 2022-09-28 19:47 UTC by mgoelswirlds

**Description**:
[HIP-573 Custom fees blanket exemptions API](https://github.com/hashgraph/hedera-mirror-node/issues/4509)

This PR modifies the following:
* Add all_collectors_are_exempt to the openapi.yaml
* Change respective tests

**Related issue(s)**:

Fixes # https://github.com/hashgraph/hedera-mirror-node/issues/4509

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-09-28 22:09 UTC, steven-sheehy requested changes
Please also update the acceptance tests (as noted in the feature checklist) to populate and verify in response of MirrorCustomFees

2022-09-28 22:09 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +    this.all_collectors_are_exempt = customFee.all_collectors_are_exempt;
nit: Move before amount so it's sorted in the response.

2022-09-29 14:27 UTC, mgoelswirlds commented
> Details

Will add them.

2022-09-29 18:02 UTC, xin-hedera requested changes

2022-09-29 18:02 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: false
add `nullable: false`

2022-09-29 20:44 UTC, xin-hedera approved these changes
LGTM

2022-09-29 21:02 UTC, merged