04142 token relationships rest api
hashgraph/hedera-mirror-node pull request #4593
Opened 2022-10-03 17:40 UTC by mgoelswirlds

**Description**:
Token relationships REST API

This PR modifies the following  in order to support listing the tokens associated with a particular account including token relationship info like automaticAssociation, balance, etc.
* Add token relationships API
* Add needed classes
* Add api on the dashboard
* Add acceptance tests

**Related issue(s)**:

Fixes # https://github.com/hashgraph/hedera-mirror-node/issues/4142

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-10 20:49 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/controllers/tokenController.test.js
> +import {getResponseLimit} from '../../config';
Looks like this import may be removed.

2022-10-10 20:55 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/all-params.json
> +  }
Can you add a test that populates the pagination links?

2022-10-10 20:59 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenController.js
> +const {default: defaultLimit} = getResponseLimit();
Is this const used?

2022-10-10 21:03 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +    console.log('Query: ' + query);
Can remove debug log.

2022-10-10 21:11 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +      '.token_id = tb.token_id';
Rather that a string, would be be feasible to use the constant table column names to generate the join statement? Something similar to this example from Contract Service: 

```
  static joinTransactionTable = `join ${Transaction.tableAlias}
  on ${ContractResult.getFullName(ContractResult.CONSENSUS_TIMESTAMP)} = ${Transaction.getFullName(
    Transaction.CONSENSUS_TIMESTAMP
  )}`;
  ```

2022-10-10 22:04 UTC, steven-sheehy requested changes

2022-10-10 22:04 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParamDesc'
```suggestion
        - $ref: '#/components/parameters/orderQueryParam'
```

2022-10-10 22:04 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                $ref: '#/components/schemas/TokenRelationship'
There should be a `TokenRelationshipResponse` that contains a `tokens` and `links` fields.

2022-10-10 22:04 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/token-range.json
> +  "url": "/api/v1/accounts/0.0.1001/tokens?token.id=gt:1000&token.id=lte:2500&order=asc",
We should have different URLs for each `token.id` supported operator that returns the same info.

2022-10-11 16:28 UTC, mgoelswirlds commented on hedera-mirror-rest/service/tokenService.js
> +    where ${tableAlias}.${TokenRelationship.ACCOUNT_ID} = $1`;
@steven-sheehy Do you mean while querying? We need a new filter other than token.id?

2022-10-11 16:29 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +    where ${tableAlias}.${TokenRelationship.ACCOUNT_ID} = $1`;
Yes

2022-10-11 20:26 UTC, mgoelswirlds commented on hedera-mirror-rest/controllers/tokenController.js
> +const {default: defaultLimit} = getResponseLimit();
Ended up using it.

2022-10-12 04:56 UTC, steven-sheehy requested changes

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/model/tokenAccount.js
> +  static TOKEN_ID = `token_id`;
Defined twice. Should move all statics together and above constructor so this is more obvious.

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/model/tokenRelationship.js
> +  static tableName = 'token_account';
`token_id` is still defined twice. And still should move all statics together and above constructor so this is more obvious.

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +    where ${tableAlias}.${TokenRelationship.ACCOUNT_ID} = $1`;
Remove `accountBalanceQuery` and `tokenBalanceJoin` and push them into this const as noted previously. It's harder to read queries that are separate.

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/model/tokenBalance.js
> +class TokenBalance {
Unused?

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/model/accountBalanceFile.js
> +class AccountBalanceFile {
Unused?

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +    where ${tableAlias}.${TokenRelationship.ACCOUNT_ID} = $1`;
Hmm, it seems the term `querying` and `filter` are ambiguous. I thought you meant SQL querying and filtering in the where clause, but you meant HTTP query params. We should not have an `associated` query parameter, just a hardcoded `associated is true` SQL where clause.

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/TokenRelationship'
```suggestion
          type: array
          items:
            $ref: '#/components/schemas/TokenRelationship'
```

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Did not remove everywhere

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    associatedQueryParam:
Remove here and above

2022-10-12 04:56 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +  getQuery(query) {
Since this class will eventually be used for more than just relationships

```suggestion
  getTokenRelationshipsQuery(query) {
```

2022-10-12 13:31 UTC, mgoelswirlds commented on hedera-mirror-rest/model/tokenBalance.js
> +class TokenBalance {
It is used for the constants .  Since, I am using these table names and aliases , I did not want to add all these constants in tokenAccount for readability and in future if we need to reuse these for the specific tables.

2022-10-12 14:29 UTC, mgoelswirlds commented on hedera-mirror-rest/service/tokenService.js
> +import {TokenAccount, TokenBalance, AccountBalanceFile} from '../model';
@steven-sheehy AccountBalanceFile and TokenBalance are used here.

2022-10-12 15:19 UTC, xin-hedera requested changes

2022-10-12 15:19 UTC, xin-hedera commented on hedera-mirror-rest/service/tokenService.js
> +    let conditionsClause;
Can assume conditions is always a valid array, or can do `const conditions = query.conditions || [];` to make the code more readable.

Also `conditionClause` only honors the last from the array, need to join all the expressions.

```javascript
  const conditionClause = conditions
    .map((condition) => {
      params.push(condition.value);
      return `${TokenAccount.getFullName(condition.key)} ${condition.operator} $${params.length}`;
    })
    .join(' and ');
```

In addition, we need to filter the `=` filters and transform it into `ta.token_id IN (...)`, for example, if there are two such filters, `[{key: 'token_id', operator: '=', value: 1001}, {key: 'token_id', operator: '=', value: 1002}]`, the generated SQL expression should be sth like `ta.token_id in ($1, $2)` with the params array `[1001, 1002]`.

2022-10-12 15:19 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/schemas/TimestampNullable'
```suggestion
          $ref: '#/components/schemas/Timestamp'
```

2022-10-12 16:55 UTC, mgoelswirlds commented on hedera-mirror-rest/service/tokenService.js
> +    let conditionsClause;
It will loop through all conditions and join them right.
```
for (const index in conditions) {
        params.push(conditions[index].value);
        conditionsClause = `
      and ${TokenAccount.tableAlias}.${conditions[index].key} ${conditions[index].operator} $${params.length}`;
      }
```
Since it will loop through all conditions?

2022-10-12 19:39 UTC, xin-hedera requested changes

2022-10-12 19:39 UTC, xin-hedera commented on hedera-mirror-rest/service/tokenService.js
> +               ${TokenBalance.getFullName(TokenBalance.BALANCE)}
an account may associate itself with a token after the latest balance snapshot at time `T1`, then the `balance` f rom `token_balance` table can be `null`, since later we will track live token balance and no longer need the left join with `token_balance` table, we should set it to 0

Also need a test case

```suggestion
               coalesce(${TokenBalance.getFullName(TokenBalance.BALANCE)}, 0) balance
```

2022-10-12 19:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/tokenController.test.js
> +        conditions: [],
nit, can remove since the empty array is the default value in `defaultExpected`

```suggestion
```

2022-10-12 19:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/tokenController.test.js
> +  ];
need a test spec with multiple `token.id` filters

2022-10-12 19:39 UTC, xin-hedera commented on hedera-mirror-rest/model/index.js
> +  TokenBalance,
import `TokenType` and export it here

2022-10-12 19:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/tokenService.test.js
> +      query: {...defaultQuery, conditions: [{key: 'TOKEN_ID', operator: '=', value: 2}]},
all `TOKEN_ID` should be in lower case

2022-10-12 20:57 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/controllers/tokenController.test.js
> +  ];
Added

2022-10-12 21:03 UTC, mgoelswirlds commented on hedera-mirror-rest/service/tokenService.js
> +               ${TokenBalance.getFullName(TokenBalance.BALANCE)}
This is a test for that scenario. token-created-after-last-balance.json

2022-10-13 02:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/controllers/tokenController.test.js
> +  ];
I don't see such a test spec added in this file. btw can you leave required changes to the reviewer to resolve / close? It's our practice and easier for the reviewer to track. You can add a comment to indicate you've made the required changes in case not all of them are addressed.

2022-10-13 13:13 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/token-range.json
> +    "/api/v1/accounts/0.0.1001/tokens?token.id=1500&token.id=2500"
@xin-hedera Sorry about that. This is where I added multiple token.if filters. But I can add to the controller test as well.

2022-10-13 13:14 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/controllers/tokenController.test.js
> +  ];
Sorry about that. Will keep that in mind.
I did add multiple token.id filters case to token-range integration test. I can add it here as well

2022-10-14 03:12 UTC, steven-sheehy approved these changes
LGTM

2022-10-14 03:12 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +    ].join('\n');
We can use `BaseService.buildSelectQuery()` to simplify this

2022-10-14 13:53 UTC, xin-hedera approved these changes
LGTM

2022-10-14 14:48 UTC, merged