Add Contract State table
hashgraph/hedera-mirror-node pull request #4611
Opened 2022-10-04 20:57 UTC by edwin-greene

- Add the Contract State table
- Migrate the the most current Contract State Changes to the Contract State table.

**Related issue(s)**:

Fixes #4476

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-10-05 14:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +    end,
Any thoughts? Maybe there is a better way to left pad?

2022-10-05 15:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +    end,
`decode(lpad(encode(slot, 'hex'), 64, '0'), 'hex')` ? Also, your zero string seems to be longer than 64 characters.

2022-10-06 16:39 UTC, steven-sheehy requested changes

2022-10-06 16:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .customize(c -> c.consensusTimestamp(createdTimestamp).slot(domainBuilder.bytes(10))).get();
Should just use `domainBuilder.contractStatChange().customize(c -> c.valueWritten(null))` as your `contractStateChangeNoValue` instead of creating a separate contractstatechange just to throw it away. In fact, should take advantage of the builder to generate multiple copies from the same base with the variations needed. See `onCryptoAllowanceHistory` for an example.

```java
var builder = domainBuilder.contractStateChange();
var contractStateChangeCreate = builder.get();
var contractStateChangeUpdate = builder.customize(c -> c.modifiedTimestamp(contractStateChangeCreate.getModifiedTimestamp() + 1).valueWritten(domainBuilder.bytes(10))).get();

2022-10-06 16:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +    where csc.migration is true
This would mean any contracts created after the traceability sidecar migration would not be populated in contract_state. Think you need to do something like `where csc.migration is true or (csc.migration is false and csc.value_written is not null)`.

2022-10-06 19:04 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .value(bytes(30));
Fixed.

2022-10-06 19:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            contractStates.add(contractState);
Thanks I have added the map and the merge method.

2022-10-06 19:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +    where csc.migration is true
Thanks I have updated the where clause.

2022-10-06 19:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +
I've removed the extra line.

2022-10-06 19:05 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .customize(c -> c.consensusTimestamp(createdTimestamp).slot(domainBuilder.bytes(10))).get();
Got it I have updated the test to better use the builder.

2022-10-07 16:55 UTC, steven-sheehy requested changes

2022-10-07 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        domainBuilder.contractStateChange().customize(c -> c.valueWritten(null)).persist();
We should also have a row where `migrate is false and value_written is not null` then verify its value is the one written to `contract_state`.

2022-10-07 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +                .customize(c -> c.migration(true).consensusTimestamp(createdTimestamp)).persist();
Need to set `value_written=null` for `migration=true` rows. They will only have `value_read` populated. Also, right now all `migration=true` entries have the same consensus timestamp (unless it's re-ran).

2022-10-07 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        contractStateChange1.setValueWritten(domainBuilder.bytes(100));
We should expand the set of test rows to test different scenarios like multiple contract IDs, multiple slots, multiple sidecar migrations (in case it exports twice):

ts | contract_id | slot | migration | value_read | value_written
-|-|-|-|-|-
1 | 0.0.1000 | 1 | true | a | null
2 | 0.0.1000 | 1 | true | b | null
2 | 0.0.1000 | 2 | true | c | null
2 | 0.0.1001 | 1 | true | d | null
3 | 0.0.1000 | 2 | false | c | e
4 | 0.0.1001 | 1 | false | f | null

This should result in the following `contract_state` rows:

contract_id | slot | value
-|-|-
0.0.1000 | 1 | b
0.0.1000 | 2 | e
0.0.1001 | 1 | d

2022-10-07 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (contractStateChange.getValueWritten() != null) {
Need to also handle if `migration=true and value_read is not null` and treat it similarly. This is for when the SQL migration runs on an empty table but a sidecar migration later occurs.

2022-10-07 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (current.getValue() != null) {
Based upon the checks in `onContractStateChange` I'm not sure this is possible. But probably safe to keep.

2022-10-07 16:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
Should have a couple `completeFileAndCommit` to test a few scenarios (or separate tests):

Block | contract_id | slot | value_written
-|-|-|-
1 | 0.0.1000 | 1 | a
1 | 0.0.1000 | 1 | b
1 | 0.0.1001 | 1 | c
1 | 0.0.1001 | 1 | null
2 | 0.0.1000 | 1 | d
2 | 0.0.1001 | 1 | e

Should have a separate test for migration=true.

2022-10-07 17:39 UTC, xin-hedera requested changes

2022-10-07 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +  primary key (contract_id, slot)
nit, create the primary key after backfilling the data. it'll be faster if there's a lot of data

2022-10-07 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        contractStateChange1.setValueWritten(domainBuilder.bytes(100));
```suggestion
        contractStateChange1.setValueWritten(domainBuilder.bytes(32));
```

2022-10-07 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        contractStateChange1.setValueWritten(domainBuilder.bytes(100));
```suggestion
        contractStateChange1.setValueWritten(domainBuilder.bytes(32));
```

2022-10-07 17:43 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java
> +        return leftPaddedBytes;
Believe that right pads zeros

2022-10-07 17:49 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java
> +        return leftPaddedBytes;
correct 😃

2022-10-10 19:54 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        contractStateChange1.setValueWritten(domainBuilder.bytes(100));
I have updated the migration test to test this example.

2022-10-10 19:55 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        domainBuilder.contractStateChange().customize(c -> c.valueWritten(null)).persist();
This scenario has been added to the test.

2022-10-10 19:55 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +                .customize(c -> c.migration(true).consensusTimestamp(createdTimestamp)).persist();
Thanks I have updated the test.

2022-10-10 19:56 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (contractStateChange.getValueWritten() != null) {
Thanks I have updated this to handle different migration/value read circumstances.

2022-10-10 19:57 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
Thanks I have added this to the test scenarios and added a migration = true test.

2022-10-10 19:57 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractState.java
> +    @Convert(converter = ContractIdConverter.class)
Thanks I have removed it.

2022-10-10 19:58 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java
> +            return EMPTY_BYTE_ARRAY;
Thanks I have added an empty byte array constant to use in place of the Internal one.

2022-10-10 19:58 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .contractId(entityId(CONTRACT).getId())
Fixed.

2022-10-10 19:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Thanks I have removed the conditional.

2022-10-10 19:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.67.0__contract_state.sql
> +  primary key (contract_id, slot)
Thanks I have updated the migration sql.

2022-10-10 19:58 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        contractStateChange1.setValueWritten(domainBuilder.bytes(100));
Updated.

2022-10-10 19:59 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractStateMigrationTest.java
> +        contractStateChange1.setValueWritten(domainBuilder.bytes(100));
This section of the test is no longer present.

2022-10-10 19:59 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .valueWritten(domainBuilder.bytes(120))
Updated.

2022-10-11 21:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        assertThat(contractStateRepository.findAll()).containsExactlyInAnyOrderElementsOf(expected);
We should do a similar assert after each commit with what you expect. Same for `onContractStateMigrateTrue`

2022-10-11 21:24 UTC, steven-sheehy approved these changes
LGTM. Just a test improvement

2022-10-12 13:23 UTC, xin-hedera approved these changes
LGTM

2022-10-12 21:51 UTC, merged

2022-10-12 21:51 UTC, steven-sheehy commented
Merging to unblock #4548