* Create a startup probe for the Acceptance Test suite
hashgraph/hedera-mirror-node pull request #4617
Opened 2022-10-07 18:16 UTC by MarcKriguerAtHedera

Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:
This PR creates a StartupProbe (class) as part of the SDKClient constructor.

* Create a StartupProbe class, call it from inside the SDKClient constructor.
* Add a hedera.mirror.test.acceptance.startupTimeout=30m property.
* Reduce hedera.mirror.test.acceptance.rest.maxAttempts to 10.
* Reduce hedera.mirror.test.acceptance.rest.maxBackoff to 4s.
* Increase hedera.mirror.test.acceptance.rest.minBackoff to 500ms.
* 

**Related issue(s)**:

Fixes #4579 

**Notes for reviewer**:
When running the acceptance tests (e.g.
`./mvnw clean integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags=@acceptance`), you will see one new log message:
`INFO ForkJoinPool-2-worker-3 c.h.m.t.e.a.c.StartupProbe successful for all stages - HAPI, REST API, and gRPC API.` output to stdout.  This occurs within the first page of output of the acceptance tests, ahead of the acceptance tests obtaining the address book and validating each node/
**Checklist**

- [x] Documented (Code comments)
- [x] Tested (integration) via running the acceptance tests for both `testnet` and `previewnet`

2022-10-07 18:58 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +@Log4j2
Can change to `@CustomLog`

2022-10-07 20:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +@Log4j2
Done, thanks!

2022-10-10 20:06 UTC, steven-sheehy requested changes

2022-10-10 20:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            mirrorTransactionsResponse = mirrorNodeClient.getTransactions(restTransactionId);
By default `MirrorNodeClient` only retries a limited number of times (10) due to its configured `RetryBackoffSpec`. Should use `WebClient` directly so you can customize its retry spec and add a `.timeout(timeout.minus(stopwatch.elapsed()))` to it.

2022-10-10 20:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                if (mirrorTransaction.getResult().equalsIgnoreCase("SUCCESS")) {
No need to check this. It will return 404 if not found and thus throw an exception.

2022-10-10 20:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                new TopicMessageQuery()
Use `setRetryHandler` and `setMaxAttempts` instead of a loop.

2022-10-10 20:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        if (!subscribedWithGrpc) {
Remove all these `if (didSomethingPreviously) throw Exception` checks since they're not necessary if you retry indefinitely until timeout.

2022-10-10 20:10 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        log.info("successful for all stages - HAPI, REST API, and gRPC API."); // ideally, the only line logged.
Don't need to call out all steps as that leaks implementation. Can just state:
```suggestion
        log.info("Startup probe successful");
```

2022-10-11 21:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +            log.error("Startup probe unsuccessful: {}", e.getMessage(), e);
As you and I discussed, I am removing the `catch (TimeoutException)` and letting Junit/Cucumber do the only logging.

2022-10-13 00:00 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +    private final Instant startInstant;
Done.

2022-10-13 00:00 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +    private final int maxRetries;
Removed.

2022-10-13 00:01 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +	for ( ; retries <= maxRetries; retries++) {
I found the IntelliJ settings to convert tabs to spaces -- that was the cause of the incorrect formatting.

2022-10-13 00:08 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        Client client = Client.forName(acceptanceTestProperties.getNetwork().toString().toLowerCase());
Done.

2022-10-13 00:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        Client client = Client.forName(acceptanceTestProperties.getNetwork().toString().toLowerCase());
As discussed yesterday, copied some routines (at the bottom of this file) from SDKClient.java, and now the custom nodes list is looked at.

2022-10-13 00:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        }
Done.

2022-10-13 00:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            mirrorTransactionsResponse = mirrorNodeClient.getTransactions(restTransactionId);
Done.

2022-10-13 00:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                if (mirrorTransaction.getResult().equalsIgnoreCase("SUCCESS")) {
Removed.

2022-10-13 00:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                new TopicMessageQuery()
Done.

2022-10-13 00:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        if (!subscribedWithGrpc) {
All removed.

2022-10-13 00:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        log.info("successful for all stages - HAPI, REST API, and gRPC API."); // ideally, the only line logged.
Done.

2022-10-13 00:50 UTC, MarcKriguerAtHedera commented
Very sorry this took more than a day, but all of Steven's comments/suggestions have been implemented.

2022-10-14 16:43 UTC, steven-sheehy requested changes

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                .setGrpcDeadline(Duration.ofSeconds(10L))
Use the newer acceptanceTestProperties.getSdkProperties().getGrpcDeadline()

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        Client client = Client.forName(acceptanceTestProperties.getNetwork().toString().toLowerCase());
Still doesn't look at custom nodes list

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                new TopicMessageQuery()
Still not using the above

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            TransactionReceipt transactionReceipt = response.getReceipt(client,
Need to use the standalone `TransactionReceiptQuery` with same grpcdeadline, max attempts, retrytemplate, etc. as other HAPI calls.

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                    .doOnError(x -> log.error("Endpoint failed, returning: {}", x.getMessage()))
Switch to warn and add URL info to message

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            if (messageReceived.get()) {
Use a CountDownLatch(1) and await it here instead of AtomicBoolean

2022-10-14 16:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +    private boolean shouldRetryRestCall(Throwable t) {
Push this method into a new `RestPollingProperties.shouldRetry(Throwable t)` for reuse and deduplication.

2022-10-15 01:54 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                            .getReceipt(client);
Done.

2022-10-15 01:54 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                while (!(messageReceived.get()) && startupTimeout.minus(stopwatch.elapsed()).toMillis() > 0) {
Done.

2022-10-15 01:54 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                .setGrpcDeadline(Duration.ofSeconds(10L))
Done.

2022-10-15 01:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            TransactionReceipt transactionReceipt = response.getReceipt(client,
Latest version does look at the custome nodes list (and doesn't have loops counting up to `maxRetries` any more).  It dpes call the standalone `TransactionReceiptQuery` (twice).

2022-10-15 01:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                    .doOnError(x -> log.error("Endpoint failed, returning: {}", x.getMessage()))
Done.

2022-10-15 01:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            if (messageReceived.get()) {
Done.

2022-10-15 01:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +    private boolean shouldRetryRestCall(Throwable t) {
Done.

2022-10-15 01:58 UTC, MarcKriguerAtHedera commented
All suggestions have been implemented.  The "try" loop seems to be running into a problem on it's (auto)closing of the Client -- I will try to figure this out on Monday morning.

2022-10-16 03:43 UTC, steven-sheehy requested changes

2022-10-16 03:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                    }));
```suggestion
            subscription = retryTemplate.execute(x -> new TopicMessageQuery()
                    .setMaxAttempts(Integer.MAX_VALUE)
                    .setRetryHandler(t -> true)
                    .setStartTime(Instant.EPOCH)
                    .setTopicId(topicId)
                    .subscribe(client, resp -> {
                        messageLatch.countDown();
                    }));
```

2022-10-16 03:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        Client client = Client.forName(network.toString().toLowerCase());
This is a resource leak. Just noticed it's also present in the other code. Here, you can just return the `Client` instead of a map to avoid.

2022-10-16 03:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                    .subscribe(client, resp -> {
Not closing this subscription before `Client.close()` is the result of your timeout errors. I opened https://github.com/hashgraph/hedera-sdk-java/issues/1182 to improve that flow but you should manually unsubscribe at the end for now.

2022-10-16 03:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                .setTopicId(topicId)
```suggestion
                .setTopicId(topicId)
               
 .setGrpcDeadline(acceptanceTestProperties.getSdkProperties().getGrpcDeadline())
                .setMaxAttempts(Integer.MAX_VALUE)
```

2022-10-16 03:43 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        try (Client client = toClient(network)) {
On further thought, I've asked ops previously to remove hardcoded nodes for preprod environments. That means this startup probe will fail for preprod environments without custom nodes. So we do need the address book lookup even for the probe and thus the client will be identical for both `SDKClient` and `StartupProbe` except validation.

So instead of creating a separate Client here I think we should create a temporary, unvalidated Client in `SDKClient`, retry the address book retrieval indefinitely (for both flows), pass that unvalided client to `StartupProbe` for use and remove all client creation in StartupProbe.

2022-10-16 19:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                    }));
Done.  And the call to subscription.unsubscribe() added just before the end of step 4.

2022-10-16 19:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        Client client = Client.forName(network.toString().toLowerCase());
As per your later comment, I have moved the logic of creating the temporary Client (and closing it) back to the SDKClient constructor, and out of the Startup Probe code.

2022-10-16 19:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                    .subscribe(client, resp -> {
Done (just after the messageLatch.await(...) call).

2022-10-16 19:35 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                .setTopicId(topicId)
Done.

2022-10-16 19:38 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +        try (Client client = toClient(network)) {
Done -- I was leaning towards trying this approach on Monday (and then, when I saw this comment from you, decided on doing it today).  Glad we're in alignment on this!

2022-10-16 19:39 UTC, MarcKriguerAtHedera commented
Addressed all of Steven's comments from yesterday (most notably, moving the creation and closing of the temporary unvalidated Client to the SDKClient constructor and outside the Startup Probe.  It now runs to completion (and all tests are passing again).

2022-10-16 20:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +                new TopicMessageQuery()
Done (again) two days ago.

2022-10-16 20:05 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            TransactionReceipt transactionReceipt = response.getReceipt(client,
Very latest version now does the Client setup in the SDKClient constructor, and just passes it to the StartupProbe.

2022-10-16 22:20 UTC, steven-sheehy requested changes

2022-10-16 22:20 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        }
Remove catch otherwise startup probe will just continue after failure, negating its benefit.

2022-10-16 22:20 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            subscription.unsubscribe();
This should be closed in a finally block if not null so that it closes gracefully on timeout.

2022-10-17 00:39 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
> +        }
Done.

2022-10-17 00:39 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
> +            subscription.unsubscribe();
Done.

2022-10-17 14:35 UTC, steven-sheehy approved these changes

2022-10-17 14:45 UTC, merged