feat: adding impl for EntityAccess
hashgraph/hedera-mirror-node pull request #4632
Opened 2022-10-10 08:44 UTC by nikolovyanko

Signed-off-by: Yanko Nikolov <nikolovqnko@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-17 12:16 UTC, IvanKavaldzhiev commented
GPG sign all of the commits.

2022-11-09 08:07 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/util/EntityUtils.java
> +    public static long numFromEvmAddress(final byte[] bytes) {
I believe only this method is used currently. Probably we can delete the other methods?

2022-11-09 08:09 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    byte[] getStorage(final Long accountNum, final byte[] key);
Probably we can also return `Optional` here?

2022-11-09 08:09 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    byte[] getAlias(final Long accountNum);
Probably we can also return `Optional` here?

2022-11-10 22:20 UTC, steven-sheehy requested changes

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +
Missing license header. Please check other files too.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/pom.xml
> +            <artifactId>besu-datatypes</artifactId>
This seems to be a transitive dependency of hedera-evm-api and can be removed, I believe.

If it's necessary, should remove compile scope, moved outside of test section, and also add to build.gradle.kts.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/util/EntityUtils.java
> +    public static long numFromEvmAddress(final byte[] bytes) {
See my other comment, but this might not be necessary. If it is, move to `DomainUtils` and use `ByteBuffer` like `fromEvmAddress()` does.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        final var entityNum = numFromEvmAddress(address.toArrayUnsafe());
Multiple things wrong here. This won't always work as we can't always assume the address is a zero-form hedera account ID. We should adjust the queries to search for `entity.evm_address` with a possible fallback to convert to search by zero form.

If you do fallback to decoding shard, realm and num out of address, you should not discard realm and shard. Instead decode them into a single bigint using `EntityId.of()`.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    @Query(value = "select balance from entity where num = ?1 and deleted <> true",
`num` is not indexed and will be slow to search. You should also always include shard and realm so better to use `id` since it's a primary key encoded using all three.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    @Query(value = "select type from entity where num = ?1 and deleted <> true"
For maintenance, I think a single `findByIdAndNotDeleted` should be sufficient to replace `getBalance`, `getType`, and `getAlias`. Spring data should auto-generate it from the name.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    Optional<byte[]> fetchContractCode(final Long accountNum);
Repositories should be isolated to just the table it is querying. So separate these into `ContractRepository`, `ContractStateRepository`, etc.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    @Query(value = "select value_written from contract_state_change where contract_id = ?1 and slot =?2",
You need to query `contract_state`

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +public interface EntityAccessRepository extends CrudRepository<Entity, Long> {
Add repository tests against the containerized postgres for each method.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/UtilityClassesConstructorTest.java
> +class UtilityClassesConstructorTest {
I don't think this reflection based test is worthwhile. We don't need to test that lombok works.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +    void getBalance() {
Need negative test cases for optional.orElse for some of these methods.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +        assertFalse(mirrorEntityAccess.isTokenAccount(ADDRESS));
The standard in mirror node is to not use JUnit assertions in favor of purely using assertj `assertThat()` and related.

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        final var balance = entityRepository.getBalance(entityNum);
We will probably have to cache a lot of these queries. Should that be handled at a later time based upon performance testing?

2022-11-10 22:20 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +    Optional<byte[]> fetchContractCode(final Long accountNum);
Use `find` prefix for repository methods to be consistent.

2022-11-11 22:38 UTC, steven-sheehy requested changes

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return EntityIdEndec.encode(id.getShardNum(), id.getRealmNum(), id.getEntityNum());
```suggestion
        final var id = DomainUtils.fromEvmAddress(address.toArrayUnsafe());
        return id.getId();
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/util/EntityUtils.java
> +public class EntityUtils {
Class is now unused and can be deleted.

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityAccessRepository.java
> +public interface EntityAccessRepository extends CrudRepository<Entity, Long> {
```suggestion
public interface EntityRepository extends CrudRepository<Entity, Long> {
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractStateRepository.java
> +    @Query(value = "select value_written from contract_state where contract_id = ?1 and slot =?2",
Why you need tests:
```suggestion
    @Query(value = "select value from contract_state where contract_id = ?1 and slot =?2",
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractRepository.java
> +    Optional<byte[]> findContractCode(final Long accountNum);
One could argue
```suggestion
    Optional<byte[]> findRuntimeBytecode(final Long id);
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return entity.map(value -> ByteString.copyFrom(value.getAlias())).orElse(ByteString.EMPTY);
Bit strange to return proto back. But we should use the util to avoid an allocation.
```suggestion
        return entity.map(value -> DomainUtils.fromBytes(value.getAlias())).orElse(ByteString.EMPTY);
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return entity.isPresent() ? entity.get().getBalance() : 0L;
```suggestion
        return entity.map(Entity::getBalance).orElse(0L);
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +            return null;
Can copy from `EntityRepository.findByEvmAddress` in importer. 
```suggestion
            return entityRepository.findByEvmAddress(addressBytes);
```

2022-11-11 22:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (isMirror(address.toArrayUnsafe())) {
Not all implementations necessarily avoid allocating bytes, so should save this to a variable and pass to all 3 methods.
```suggestion
        final var addressBytes = address.toArrayUnsafe();
        if (isMirror(addressBytes)) {
```

2022-11-14 12:03 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +            return null;
Hey Steven, thanks for the detailed comments and suggestions so far. The received address field contains a bytes representation of the account alias.And since the `alias` field in the entity table is also indexed, I introduced a method `findByAliasAndDeletedFalse` querying the entity by it  instead of the `evmAddress` to avoid additional parsing.

2022-11-14 12:07 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        final var balance = entityRepository.getBalance(entityNum);
We discussed that and totally agree to add caching, however we plan it to add it simultaneously for all the evm-module lib implementations in later PR.

2022-11-15 15:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +            return null;
Ok, was not aware that address can also be an alias. It's weird that it can be a 20 byte EVM address (shard/realm/num format) but not a regular 20 byte EVM address. Are you sure it can't be all 3 and we should have a findByEvmAddress lookup as well?

2022-11-16 15:59 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +            return null;
Actually, for contract creates there might be evm_address fields with CREATE1 (keccak256 calculated address using nonces) or CREATE2 addreses, both 20-bytes, so we should be also able to search results by evm_address. We will take into account also these cases.

2022-11-16 18:57 UTC, steven-sheehy requested changes

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return entity.isPresent() && entity.get().getBalance() > 0;
```suggestion
        return findEntity(address).filter(e -> e.getBalance() > 0).isPresent();
```

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return entity.isPresent() && entity.get().getType().equals(TOKEN);
```suggestion
        return findEntity(address).filter(e -> e.getType() == TOKEN).isPresent();
```

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +    private EntityRepository entityRepository;
Use constructor injection in tests. And can remove boilerplate fields if using DomainBuilder. Can inject `DomainBuilder` in `Web3IntegrationTest` to reduce setup across tests. Same comment for other tests.

```suggestion
@RequiredArgsConstructor(@__(@Autowired))
class EntityRepositoryTest extends Web3IntegrationTest {

    private final EntityRepository entityRepository;
```

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +        final var result = entityRepository.findByAliasAndDeletedIsFalse(KEY);
Mirror node standard is to use `DomainBuilder` everywhere to generate default objects and customize it only as necessary for the scenario. This avoids hardcoding fields and boilerplate setup.

```suggestion
        var entity = domainBuilder.entity().persist();
        final var result = entityRepository.findByAliasAndDeletedIsFalse(entity.getAlias());
```

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +        final var result = entityRepository.findByAliasAndDeletedIsFalse(KEY);
We should have tests for:
* alias not found
* alias present but deleted=true

Use `customize()` chaining method in `DomainBuilder` to set `deleted(true)`.

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +        assertThat(result).get().isEqualTo(entity);
Use `DomainBuilder` and add tests for id not found and id present but deleted=true

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +
License headers missing again in various files.

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/ContractStateRepositoryTest.java
> +        assertThat(result).get().isEqualTo(KEY_VALUE);
Use DomainBuilder and addtest for contract not found and contract found but key not

2022-11-16 18:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/ContractRepositoryTest.java
> +        assertThat(result).get().isEqualTo(RUNTIME_CODE);
Use DomainBuilder and add test for not found.

2022-11-18 04:30 UTC, steven-sheehy requested changes

2022-11-18 04:30 UTC, steven-sheehy commented on hedera-mirror-web3/pom.xml
> +            <version>${release.version}</version>
This is already included above. I assume you meant to add the below?
```
            <type>test-jar</type>
            <scope>test</scope>
```

2022-11-18 15:37 UTC, steven-sheehy approved these changes
LGTM

2022-11-18 15:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +    Entity entity;
We should never mock domain objects. They're simple to create and we have the `DomainBuilder` to avoid boilerplate setup with sane auto-generated defaults.

2022-11-18 15:41 UTC, merged