04618 token relationship monitor dashboard
hashgraph/hedera-mirror-node pull request #4657
Opened 2022-10-14 19:32 UTC by mgoelswirlds

**Description**:
This PR is to add the new rest endpoint /api/v1/accounts/${accountId}/tokens to the js monitor dashboard

This PR modifies account_tests to 
* Add the /tokens endpoint

**Related issue(s)**:

Fixes #https://github.com/hashgraph/hedera-mirror-node/issues/4618

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-14 21:45 UTC, steven-sheehy requested changes

2022-10-14 21:45 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const token_url = getUrl(server, tokensPath, {limit: resourceLimit, order: 'asc'});
We should only get one since we only need one.

2022-10-14 21:45 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const tokenMandatoryParams = ['token_id', 'symbol', 'admin_key'];
We don't need the other fields for this test.
```suggestion
  const tokenMandatoryParams = ['token_id'];
```

2022-10-14 21:45 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  if (!token_result.passed) {
If tokens.length === 0 we should skip the rest of the checks.

2022-10-14 21:45 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    .withCheckSpec(checkRespArrayLength, {
If there aren't any balances for the token then we should just return instead of error.

2022-10-14 21:45 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const accountsTokenPath = `/accounts/${accountId}/tokens`;
We should have a property to control then enablement of this `getSingleAccountTokenRelationships` to control the rollout and in case there's issues and we need to disable it.

2022-10-14 21:45 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    .run(tokenRelationships);
We should check the response has at least one relationship

2022-10-17 13:05 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    .run(tokenRelationships);
@steven-sheehy so if there are no relationships should we error out?

2022-10-17 13:43 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    .run(tokenRelationships);
I have errored out for now.

2022-10-17 14:48 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    .run(tokenRelationships);
Correct

2022-10-17 15:31 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  if (!token_result.passed) {
I believe the approach you take will still cause the overall check to fail. I think we should not fail the check if some transitive dependency is not passing since it might just be a lack of data issue and we're already checking these APIs elsewhere. So we probably just need to:

```
  if (!result.passed) {
    result.passed = true;
    return {url, ...result};
  }
```

Ideally, we'd have an enum for `passed` that indicates it's more of a warning about transitive dependency failure but that would be a big rework.

2022-10-17 15:31 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    .withCheckSpec(checkRespArrayLength, {
Same comment as above

2022-10-17 19:26 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    tokenRelationshipEnabled ? runTest(getSingleAccountTokenRelationships) : '',
nit, should conditionally add `runTest(getSingleAccountTokenRelationships`)` to the promise array instead of adding a `''` when `tokenRelationshipEnabled` is false.

checked the code, it shouldn't cause any alert issue so won't block the PR.

2022-10-17 19:27 UTC, xin-hedera approved these changes
LGTM

2022-10-17 19:30 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    tokenRelationshipEnabled ? runTest(getSingleAccountTokenRelationships) : '',
Will update this in the next PR.Thanks.

2022-10-17 19:31 UTC, merged