Token relationship acceptance test
hashgraph/hedera-mirror-node pull request #4675
Opened 2022-10-17 21:30 UTC by mgoelswirlds

**Description**:
Adding acceptance tests for the token relationships API

This PR does the following
* Add new test to the token.feature for token relationship
* Change existing tests from using enum number to enum Names.

**Related issue(s)**:

Fixes #4656

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-10-19 18:37 UTC, MarcKriguerAtHedera approved these changes
Looks good to me -- I just found two very small nits,

2022-10-19 18:37 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAccount.java
> +@lombok.Data
Nit: I think that (nearly) every other class in the .../acceptance hierarchy imports lombok.Data and then just declares this as @Data.

2022-10-19 18:37 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +import com.hedera.mirror.test.e2e.acceptance.props.MirrorTokenAccount;
Nit: the two imports under acceptance.props should (still) come before those inacceptance.response.  (It looks like you are moving them too far down.)

2022-10-19 19:30 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +import com.hedera.mirror.test.e2e.acceptance.props.MirrorTokenAccount;
Yes . I missed that. I wanted to order it alphabetically and missed that.

2022-10-19 20:13 UTC, mgoelswirlds commented
@MarcKriguerAtHedera I have addressed your comments but lost your approval with the change?

2022-10-19 22:53 UTC, xin-hedera requested changes

2022-10-19 22:53 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorFreezeStatus.java
> +}
```suggestion
public enum MirrorFreezeStatus {
    NOT_APPLICABLE,
    FROZEN,
    UNFROZEN
}
```

same for the other enum

2022-10-19 23:09 UTC, MarcKriguerAtHedera approved these changes
Please make the changes requested by Xin (at which point this approval will disappear again), but then it will be good to go.

2022-10-20 12:29 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        if (tokenType.equals(TokenType.FUNGIBLE_COMMON.name())) {
There are 2 different tests, fo rFungible and non fungible token, so thats why I added the type.

2022-10-20 12:49 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        if (tokenType.equals(TokenType.FUNGIBLE_COMMON.name())) {
@xin-hedera  Is this not the practice?  I did this to avoid having multiple tests one for FUNGIBLE and NON-FUNGIBLE.

2022-10-20 13:16 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        if (tokenType.equals(TokenType.FUNGIBLE_COMMON.name())) {
two issues:

- the scenario outline says `Validate Token Flow - ...` (it's actually fungible token since later there's a step to mint certain amount), yet the token type is configurable
- kyc status / freeze status are orthogonal to token type, thus I asked why the expected kyc status /  freeze status are dependent on token type

2022-10-20 13:35 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        if (tokenType.equals(TokenType.FUNGIBLE_COMMON.name())) {
@xin-hedera  They aren't dependent on the token type but in the scenarios:
1. For Fungible - We are explicitly setting the freeze status and kyc status which sets it to their respective values/ defaults.
2. For NFT - Since we are not explicitly setting the freeze status and kyc status, they are not-applicable there. 

To be able to test out the scenarios, I added that type. If there is a different way to do that I am open to making the changes.
Would you rather have the different cases based on scenario and not token type? Token type was my way to differentiate between the scenarios.

2022-10-20 14:07 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        if (tokenType.equals(TokenType.FUNGIBLE_COMMON.name())) {
Ok I will remove the condition and dependency.

2022-10-20 14:29 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        if (tokenType.equals(TokenType.FUNGIBLE_COMMON.name())) {
@xin-hedera I have separated the methods out to avoid confusion.

2022-10-20 15:46 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
>  import com.hedera.mirror.test.e2e.acceptance.response.MirrorTransactionsResponse;
Can optimize imports, it looks like `com.google.common.base.Throwables` may no longer be used.

2022-10-20 15:49 UTC, edwin-greene approved these changes
Looks good!

2022-10-20 17:00 UTC, edwin-greene approved these changes

2022-10-21 14:20 UTC, merged