Add Balance to Token Account
hashgraph/hedera-mirror-node pull request #4693
Opened 2022-10-19 20:50 UTC by edwin-greene

**Description**:

- Add Balance to Token Account table.
- Add migration that updates Token Account table with token balances from the latest Account Balance File.

**Related issue(s)**:

Fixes #4402

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-10-20 19:07 UTC, xin-hedera requested changes

2022-10-20 19:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (newTokenAccount.getTimestampRange() == null || lastTokenAccount.getTimestampRange() == null) {
we probably want to remove the logic in `getTokenAccount` which checks the existence of the token account in the cached state.

there are 4 cases we need to handle w.r.t. balance:


| last timestamp range      | new timestamp range | action |
| ----------- | ----------- | ----|
| null      | null       | set accumulated balance to last, return last |
| null   | non null        | set accumulated balance to last, copy value of every other field from new to last,  return last |
| non null      | null       | set accumulated balance to last, return last |
| non null      | non null       | in addition to the existing logic, copy balance from last to new, return new |

2022-10-20 19:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
feel we need to remove this block

2022-10-24 17:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +            "where account_id = ? and token_id = ?";
Excellent thanks. I have updated it to a single SQL -> It should also capture the changes between the time of the balance file and the last transaction in the db. Please double check.

2022-10-24 17:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.68.0__token_account_balance.sql
> +alter table if exists token_account_history add column if not exists balance bigint null;
I have updated these.

2022-10-24 17:40 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +
Thanks I have placed all the balance setting in the merge logic. I have added a test that should perform the operations you described: `onTokenAccountFreezeBalance`

2022-10-24 17:41 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                10, TokenFreezeStatusEnum.NOT_APPLICABLE, TokenKycStatusEnum.NOT_APPLICABLE, Range.atLeast(5L));
Thanks, I have made almost all of the initial token accounts have a balance of 0. I have one left that is there just to test it.

2022-10-24 17:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        TokenAccount dissociate = getTokenAccount(tokenId1, accountId1, null, false, null, 10, null, null,
Thanks I have set these onTokenAccount events to all be a 0 balance.

2022-10-24 17:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        TokenAccount tokenAccountAssociate = getTokenAccount(tokenId1, accountId1, 5L, true, false, 10, null, null,
Fixed.

2022-10-24 17:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        TokenAccount tokenAccountKyc = getTokenAccount(tokenId1, accountId1, null, null, null, 20, null,
Fixed.

2022-10-24 17:43 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        Token token1 = getToken(tokenId1, EntityId.of("0.0.500", ACCOUNT), 1L, 1L);
I started to create a test using `domainBuilder`, but the number of customizations in `getToken` seemed to reduce its utility, so far I haven't continued down that line of thought.

2022-10-24 17:44 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        TokenTransfer tokenTransfer3 = domainBuilder.tokenTransfer().customize(t -> t.id(tokenTransferId).amount(-50L)).get();
Thanks I have fixed this.

2022-10-24 17:45 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        tokenAccount.setBalance(160);
Thanks I have made the balance a reference to the token transfers involved.

2022-10-24 17:45 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        EntityId tokenId1 = EntityId.of("0.0.3", TOKEN);
I have switched it to a parameterized test.

2022-10-24 17:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (newTokenAccount.getTimestampRange() == null || lastTokenAccount.getTimestampRange() == null) {
Thanks I have made this change and I have added tests for it. 

With one exception. I found that for the balance setting for this case: 

last timestamp range | new timestamp range | action
-- | -- | --
null | non null | **set accumulated balance to last**, copy value of every other field from new to last, return last


The token transfer balance would be altered by the freeze/kyc/disassociate token account balance. Which shouldn't be present, but if it was present then the balance looks like it would be incorrectly altered. I have a test case for this scenario, `tokenTransferTokenAccountNewTokenAccountNotNull`. Let me know if this looks correct or if I need to reevaluate.

2022-10-24 17:52 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Thanks I have removed it and consolidated the logic in the mergeTokenAccount method.

2022-10-25 13:25 UTC, xin-hedera requested changes

2022-10-25 19:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +            "where account_id = ? and token_id = ?";
It still is missing latest token transfers. `token_balance` is only accurate at 15 minutes granularity. You need to replay any `token_transfer` that occurred after last balance file`.

2022-10-25 20:03 UTC, steven-sheehy requested changes

2022-10-26 15:19 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        TokenAccount freeze = getTokenAccount(tokenId1, accountId1, null, null, null, -9999, TokenFreezeStatusEnum.FROZEN, null, Range.atLeast(tokenAccount.getTimestampLower() + 1));
Thanks. I believe I understand. In real terms the token freeze should never have a balance. This test is to make sure that the balance of the token freeze is discarded and not used. Just a test case that I wanted to have to make sure that the logic was working correctly and not gathering balances from sources that it should not gather them from.

2022-10-26 20:28 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        TokenAccount freeze = getTokenAccount(tokenId1, accountId1, null, null, null, -9999, TokenFreezeStatusEnum.FROZEN, null, Range.atLeast(tokenAccount.getTimestampLower() + 1));
After doing more testing, I discovered that depending on the commitIndex of the parameterized test I could not correctly distinguish the balance if the onTokenAccount was triggered by a non-token-transfer event. So I have removed this test and the negative balance token freeze.

2022-10-26 20:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +            "where account_id = ? and token_id = ?";
Thanks I have added the token transfers to the migration sql.

2022-10-26 20:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (newTokenAccount.getTimestampRange() == null || lastTokenAccount.getTimestampRange() == null) {
I think I see. I have removed the invalid test cases.

2022-10-26 20:40 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                )
Thanks I have made this change and I have updated the migration to include the token transfers.

2022-10-26 20:41 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    void tokenTransferTokenAccountNewTokenAccountNotNull() {
Thanks I have updated the testing and simplified all the tests into a single parameterized test.

2022-10-26 20:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        newTokenAccount.setBalance(lastTokenAccount.getBalance());
Sounds good I have move the set balance down.

2022-10-26 20:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                update token_account t set balance = token_balance.balance
Thanks I have added this functionality to the migration sql, it should not insert balances for NON_FUNGIBLE_UNIQUE tokens.

2022-10-26 20:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        Token token1 = getToken(tokenId1, EntityId.of("0.0.500", ACCOUNT), 1L, 1L);
Thanks I have implemented `domainBuilder.token()` in the test case.

2022-10-26 20:43 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.68.0__token_account_balance.sql
> +alter table if exists token_account add column if not exists balance bigint not null default 0;
Sounds good I have updated the migration sql to set the value to -1 for the non-fungible tokens.

2022-10-26 20:43 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (lastTokenAccount.getTimestampRange() != null && newTokenAccount.getTimestampRange() == null) {
Great, I have switched the merge method to employ this helper method.

2022-10-27 15:54 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.68.0__token_account_balance.sql
> +alter table if exists token_account add column if not exists balance bigint not null default 0;
I've reverted that change; the value for NON_FUNGIBLE_UNIQUE will be inserted (not set to -1), it may be set to null in the REST API.

2022-10-27 16:22 UTC, steven-sheehy requested changes

2022-10-27 16:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                    where consensus_timestamp = (select max(consensus_timestamp) from account_balance_file)
Move `select max(consensus_timestamp) from account_balance_file` to a separate CTE so it's consistent between its two uses. Also, you need to select the latest account balance file nearest to the latest record file in case the importer is catching up. Should be able to copy most logic from `InitializeEntityBalanceMigration`. Need to also take into account offset like that class.

2022-10-27 16:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                where t.account_id = token_balance.account_id and t.token_id = token_balance.token_id
I'm not sure if we need to also check if account is deleted or associated=true?

2022-10-27 16:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                where t.account_id = token_balance.account_id and t.token_id = token_balance.token_id
we should, and under that circumstance, we should set the balance to 0 for fungible tokens

2022-10-28 14:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                where t.account_id = token_balance.account_id and t.token_id = token_balance.token_id
Thanks I have added those criterion to the migration and the test.

2022-10-28 14:59 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                    where consensus_timestamp = (select max(consensus_timestamp) from account_balance_file)
Sounds good I have implemented a solution very similar to the one used by `InitializeEntityBalanceMigration`

2022-10-28 16:18 UTC, MarcKriguerAtHedera submitted a review, later dismissed
LGTM

2022-10-28 17:49 UTC, steven-sheehy approved these changes
LGTM

2022-10-28 17:53 UTC, xin-hedera requested changes
just 1 change and 1 nit

2022-10-28 20:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                  coalesce(e_balance, 0) + coalesce(existing.balance, 0),
Thanks I have made this change.

2022-10-28 20:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    upper(existing.timestamp_range) is null)
Fixed.

2022-10-28 21:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    upper(existing.timestamp_range) is null)
I reverted this change for now as it broke some tests.

2022-10-28 21:42 UTC, xin-hedera approved these changes
LGTM

2022-10-28 21:51 UTC, steven-sheehy approved these changes

2022-10-28 22:17 UTC, MarcKriguerAtHedera approved these changes
LGTM.

2022-11-01 13:39 UTC, xin-hedera requested changes

2022-11-01 13:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    coalesce(e_balance, 0) + coalesce(existing.balance, 0),
this needs to be the same as in the part to insert rows to `token_account` table, otherwise it'll add the balance of the previous association and the new association.

2022-11-01 17:12 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java
> +                    coalesce(e_balance, 0) + coalesce(existing.balance, 0),
Thanks for finding this, I have updated it.

2022-11-01 17:54 UTC, xin-hedera approved these changes

2022-11-01 20:43 UTC, merged