Fix v2 importer tests
hashgraph/hedera-mirror-node pull request #4695
Opened 2022-10-20 15:25 UTC by xin-hedera

**Description**:

This PR fixes v2 importer tests

- Change upsert.vm and upsert_hisitory.vm to not outer join on a distributed table
- Change `InitializeEntityBalanceMigration` to not outer join on a distributed table
- Change token account upsert query to not outer join on a distributed table
- Change `account_balance_file` to a reference table
- Change `transaction_hash` to a distributed table
- Fix integration tests which assert db rows assuming a certain order
- Remove the fixed offset workaround in `entity_state_start` materialize view which also fixes failure with citus
- Bump up citus image version

**Related issue(s)**:

Fixes #3810
Relates to #4660 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-10-21 03:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_reference_table('account_balance_file');
Why is this necessary? It makes more sense for `account_balance_file` to be distributed since it is the aggregate root in the balance hierarchy. `account_balance` and `token_balance` can't exist without it so it makes more sense that they are all sharded the same and colocated together. This table is 100K rows now which is small, but not tiny and is destined to grow infinitely.

2022-10-21 13:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_reference_table('account_balance_file');
it's not necessary but it's better. main reason is it's a very small table, even at 100 years at the current rate, it's ~3.5 million rows.

there's no way to co-locate `account_balance_file` and the actual data tables: `account_balance` and `token_balance` are sharded on `account_id` and colocated with `entity`, there is no entity id column in `account_balance_file`.

2022-10-24 19:21 UTC, steven-sheehy requested changes

2022-10-24 19:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/retention/RetentionJobTest.java
> +        assertThat(recordFileRepository.findAll()).containsExactlyInAnyOrder(recordFile1, recordFile2, recordFile3);
This change was done on main, not sure you need to merge.

2022-10-24 19:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.68.0__entity_state_start_remove_fixed_offset.sql
> +create materialized view entity_state_start as
We've already had to change this view a number of times. I think we should make it a repeatable SQL migration. That way when we change it again its checksum will differ and it will automatically re-applied. We have to change it anyway whenever the schema within the select changes anyway.

2022-10-24 19:21 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
> +    docker-image: citusdata/citus:11.1.3-pg14
nit: 11.1.4 released today :)

2022-10-24 20:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.68.0__entity_state_start_remove_fixed_offset.sql
> +create materialized view entity_state_start as
oh perhaps just make it a normal table and move the SQL to a repository method, no more migration change needed...

2022-10-24 20:29 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/retention/RetentionJobTest.java
> +        assertThat(recordFileRepository.findAll()).containsExactlyInAnyOrder(recordFile1, recordFile2, recordFile3);
just because it's not in main when I created the PR

2022-10-25 20:50 UTC, steven-sheehy approved these changes
LGTM

2022-10-25 20:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/DisableRepeatableSqlMigration.java
> +public @interface DisableRepeatableSqlMigration {
Perhaps we can consider renaming this to `@MigrationV1` and adding `@EnabledIfV1` and `@Tag("migration")` to it?

2022-10-25 20:58 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/DisableRepeatableSqlMigration.java
> +public @interface DisableRepeatableSqlMigration {
we may need the same annotation in V2, it's actually whenever we have a migration integration test set to  a certain version, some repeatable sql migrations may not work.

2022-10-25 21:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/DisableRepeatableSqlMigration.java
> +public @interface DisableRepeatableSqlMigration {
Ok, can ignore

2022-10-25 21:37 UTC, merged