Fix web3 build error
hashgraph/hedera-mirror-node pull request #4705
Opened 2022-10-21 21:26 UTC by xin-hedera

Signed-off-by: Xin Li <xin.li@swirldslabs.com>

**Description**:

This PR fixes the web3 module build error.

- force using swirlds-common:0.31.0

**Related issue(s)**:

Relates to #4704 

**Notes for reviewer**:

Workaround, once the dependency issue is solved in hedera-evm-api artifact, we should remove the hardcoded version

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-10-21 21:30 UTC, edwin-greene approved these changes
Looks good

2022-10-21 21:48 UTC, steven-sheehy requested changes

2022-10-21 21:48 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +        exclude("com.swirlds", "swirlds-common")
Remove the exclude, it's not necessary.

2022-10-21 21:49 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("com.swirlds:swirlds-common:0.31.0")
Can move this to root build.gradle.kts.

2022-10-21 21:50 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("com.swirlds:swirlds-common:0.31.0")
Add a comment to both dependencies that this is a temporary transient dependency

2022-10-21 22:22 UTC, steven-sheehy commented
Also please bump SDK to 2.18.0 in gradle to fix build.

2022-10-22 01:50 UTC, steven-sheehy approved these changes

2022-10-22 02:27 UTC, merged