Rework NFT treasury transfers as specified by Xin.
hashgraph/hedera-mirror-node pull request #4743
Opened 2022-10-25 19:02 UTC by MarcKriguerAtHedera

Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:
This PR changes the way that NFT treasury transfers are processed by the mirror node code.
  * Remove early-exit code for WILDCARD_SERIAL_NUMBER in `insertNonFungibleTokenTransfers()`
  * Add calls to flush nft state to db and to `nftRepository.updateTreasury` (for WILDCARD_SERIAL_NUMBER) in `SqlEntityListener::onNftTransfer`
  * Remove call to `updateTreasury` from `TokenUpdateTransactionhandler::doUpdateEntity`

(and make sure those changes are covered by integration tests)

**Related issue(s)**:

Fixes #4659

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments)
- [x] Tested (integration)

2022-10-25 20:56 UTC, xin-hedera requested changes

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
nit, can remove the empty line

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            eventPublisher.publishEvent(new EntityBatchSaveEvent(this));
```suggestion
```

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            batchPersister.persist(nftTransferState.values());
don't have to flush nft transfers
```suggestion
```

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +                // tokenTransfers.clear();
```suggestion
```

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            try {
remove `try`

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> -        updateTreasury(recordItem);
also remove the function `updateTreasury`

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java
> -        TransactionBody body = recordItem.getTransactionBody();
remove the whole test case since `TokenUpdateTransactionHandler` no longer handles nft treasury update

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        EntityId tokenId = EntityId.of("0.0.1", TOKEN);
can use `var` for non-primitive types in the new test cases

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        sqlEntityListener.onNft(getNft(tokenId, 1L, null, 3L, false, metadata1, 3L)); // mint
this doesn't represent a mint. an nft, when mint, the owner (accountId) should be the treasury

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        Nft treasuryNft = getNft(tokenId, -1L, accountId2, 7L, false, metadata5, 7L); // transfer treasury
this doesn't really test the treasury change. note the nft treasury change is indicated by such a nft transfer in transaction record `(token_id = Nft Token, serial_number = -1, sender = old treasury, receiver = new treasury)`

2022-10-25 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        EntityId tokenId = EntityId.of("0.0.1", TOKEN);
same issue as the other test case, there's no `WILDCARD_SERIAL_NUMBER` nft transfer from the old treasury to the new treasury

2022-10-26 22:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
Done.

2022-10-26 22:58 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            eventPublisher.publishEvent(new EntityBatchSaveEvent(this));
Done (also removed the commented-out lines as well).

2022-10-26 22:58 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            batchPersister.persist(nftTransferState.values());
Done.

2022-10-26 22:59 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +                // tokenTransfers.clear();
Done.

2022-10-26 23:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            try {
Done.

2022-10-26 23:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> -        updateTreasury(recordItem);
Done.

2022-10-26 23:03 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java
> -        TransactionBody body = recordItem.getTransactionBody();
Done.

2022-10-26 23:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        EntityId tokenId = EntityId.of("0.0.1", TOKEN);
Done.

2022-10-26 23:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        sqlEntityListener.onNft(getNft(tokenId, 1L, null, 3L, false, metadata1, 3L)); // mint
Changed accordingly.

2022-10-26 23:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        Nft treasuryNft = getNft(tokenId, -1L, accountId2, 7L, false, metadata5, 7L); // transfer treasury
Adding "onNftTransfer(...) caused the code to error out unexpected (until this morning's chat during the scrum, when you gave me the hint that [another] call to `completeFileAndCommit()` was needed -- that fixed it.

2022-10-26 23:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        EntityId tokenId = EntityId.of("0.0.1", TOKEN);
Same changes made to this test.

2022-10-26 23:22 UTC, edwin-greene reviewed
Nit: Can remove the unused imports to address the code smells.

2022-10-26 23:55 UTC, MarcKriguerAtHedera commented
Unused code imports are now removed.  Thank you, @edwin-greene !

2022-10-28 17:52 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +
I'm not sure if this would work, but it may be that the nftTransfers could be added to a new list, and then the overall logic of SqlEntityListener could be preserved -> Items added to lists, lists all batch persisted in a specific order, lists all cleared, repositories updated in the `onEnd` method. 

But perhaps there is a reason to do a batch persistence call and a repository call in the middle of the whole flow?

2022-10-28 18:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +
for the `WILDCARD_SERIAL_NUMBER` nft transfer which signifies the treasury change at consensus timestamp `T` to work, the corresponding SQL `nftRepository.updateTreasury` runs needs the `nft` state to be exactly at timestamp `T-1`

this is the correct way and least performance disruptive way.

2022-10-28 18:16 UTC, xin-hedera requested changes

2022-10-28 18:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        batchPersister.persist(nfts.values()); // persist nft after token entity
was there a `try... catch...` before like in `flush()`? we should add it back

2022-10-28 18:16 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
this doesn't really test the scenario described in the ticket #4659

there is just one nft transfer in this whole `completeFileAndCommit`

2022-10-28 18:16 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
same issue pointed in the other test case

2022-10-28 18:22 UTC, edwin-greene approved these changes
Looks good.

2022-10-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +
(see @xin-hedera 's response to your question)

2022-10-28 18:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        batchPersister.persist(nfts.values()); // persist nft after token entity
There **was**, but I had thought you had asked me to remove it. Now I see that it was the `try` within the `finally` section that you wanted removed, so I have restored the outer `try`.

2022-10-28 18:34 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        batchPersister.persist(nfts.values()); // persist nft after token entity
If you go back to my comment, I asked you to remove the

`try {
  }`

block with catch or finally which make the code to fail compilation.

2022-10-28 18:45 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
I will replace the "onNft()" calls inside the test (lines 1268 and 1272, not within the block you quoted) with the "// transfer" comment -- which I had understood to be Nft transfers -- with actual calls to onNftTransfer() to transfer the non-wildcard NFTs.  This will not make much of a change to the `onNftTransferTreasuryWithUntransferredNfts` test, but more of a change to the `onNftTransferTreasuryAfterTransferredNfts` test.

2022-10-28 18:46 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
See comment about replacing the "onNft()" lines (with the "// transfer" comment) to "onNftTransfer()" calls.

2022-10-28 22:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        batchPersister.persist(nfts.values()); // persist nft after token entity
I believe I had already fixed it (in the `finally` block), so when I saw your comment to remove the `try`, the only `try` was the outer one.  Anyway, the outer one is still there, but the one inside the `finally` block is gone (now).

2022-10-28 22:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
The above is done now.

2022-10-28 23:02 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
still not fixed.

A `completeFileAndCommit` in the integration test marks a record file. In the test case, the only domain object to flush to the db is the `WILDCARD_SERIAL_NUMBER` nft transfer which signifies the change of old treasury to new treasury.  

What we should test is the issue described in the ticket #4659, that in the same record file, before the  `WILDCARD_SERIAL_NUMBER` nft transfer, the NFTs owned by the old treasury has changed, the change can be minting, transferring out from the old treasury, or transferring to the old treasury.

2022-10-29 00:19 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
I have remove all but what I believe are the "critical" calls to `completeFileAndCommit` -- each unit test has just two.
One that is done just before the call to `onNftTransfer()` that actually does the treasury transfer -- if that one is removed, the test blows up with an exception when it tries to call the second one.   In both cases, the test will pass if (just) the second call is removed, but that doesn't feel "right" (but if you want me to remove them, I will do so).

2022-11-01 13:58 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        completeFileAndCommit();
still doesn't test the scenario described in the bug ticket.

To repro the issue, we need to set up a single record file with nft state change w.r.t. the old treasury account before the nft token treasury change. For example, when the following series of transactions happen in the same record file

- an nft mint transaction, which mints some new nfts of NFT token `T` and the old treasury account should own them
- an token update transaction to change the treasury to the new treasury account

what we want to verify at the end are

- all nfts of token `T` owned by the new treasury account
- for each such nft, there is a nft transfer row in table `nft_transfer` to transfer the nft from the old treasury account to the new treasury account at consensus timestamp of the token update transaction

We also want to test (can be in the same test case or a separate one) that any nfts of token `T` transferred from the old treasury to another account `C` before the token update transaction will still have  `C` as the owner and there shouldn't be any generated `nft_tranfser` for those nfts.

2022-11-01 14:02 UTC, xin-hedera requested changes

2022-11-01 14:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> -            if (serialNumber == NftTransferId.WILDCARD_SERIAL_NUMBER) {
need a test case to verify `EntityListener` will get the `WILDCARD_SERIAL_NUMBER` nft transfer

2022-11-02 22:22 UTC, steven-sheehy commented
Importer tests failing

2022-11-02 23:41 UTC, MarcKriguerAtHedera commented
That same test runs perfectly, locally.  Adding one more assertion to try to determine why the test fails on the build machine.

2022-11-03 04:52 UTC, steven-sheehy commented
You need to test locally using the v2 schema via `-Dspring.profiles.active=v2`.

2022-11-03 12:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                        .withComparatorForType(EntityId::compareTo, EntityId.class)
```suggestion
                        .withComparatorForType(Comparator.nullsFirst(EntityId::compareTo), EntityId.class)
```

I don't know why this doesn't cause NPE consistently.  The problem is there is a `NftTransfer` with `null` `receiverAccountId`, with the EntityId comparator set the original way, it should always trigger an NPE.

2022-11-03 19:06 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-11-03 19:18 UTC, edwin-greene approved these changes
Looks good

2022-11-03 20:03 UTC, edwin-greene approved these changes

2022-11-03 20:17 UTC, steven-sheehy requested changes

2022-11-03 20:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            log.info("Completed nft-only batch inserts in {}", stopwatch);
This log and stopwatch should be removed. The batch persister already logs a similar line.

2022-11-03 20:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            // 2. nftRepository.updateTreasury
The comments just duplicate the self descriptive method names and can be removed.
```suggestion
            flushNftState();
```

2022-11-03 22:11 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            log.info("Completed nft-only batch inserts in {}", stopwatch);
Done.

2022-11-03 22:11 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            // 2. nftRepository.updateTreasury
Done.

2022-11-03 23:50 UTC, steven-sheehy approved these changes
LGTM

2022-11-03 23:57 UTC, xin-hedera approved these changes
LGTM

2022-11-04 00:21 UTC, merged