Adding citus time based partitioning.
hashgraph/hedera-mirror-node pull request #4799
Opened 2022-11-01 16:22 UTC by mgoelswirlds

Signed-off-by: mgoelswirlds <mugdha.goel@swirldslabs.com>

Description: 

Partitioning large tables within the mirror node database on timestamp or ids.
This PR modifies V2 schema table creation and partitioning
* Add partitioning columns to large tables
* Add pg_partman extension provided by citus for timestamp based partitioning
* Use pg_partman to create partitions.
* Remove unused scripts from v2 - R__autovacuum_insert_only_tables.sql and R__entity_state_start.sql

**Related issue(s)**:

Fixes #https://github.com/hashgraph/hedera-mirror-node/issues/2682

**Notes for reviewer**:
This code has been verified by running the importer locally using SPRING_PROFILES_ACTIVE=v2 ./mvnw spring-boot:run -pl hedera-mirror-importer

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-11-01 17:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
> -alter table if exists crypto_transfer set (
what's the issue with these auto vacuum settings?

2022-11-01 17:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__entity_state_start.sql
> -create or replace function change_access_privilege(grant_or_revoke boolean) returns void as
we can remove it, if the SQL fails after timestamp partition, we have to fix it.

2022-11-01 17:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +                                 grant temporary on database :dbName to :ownerUsername;"
perhaps merge all these SQL statements into a single `DB_SPECIFIC_EXTENSION_SQL`

2022-11-01 23:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__entity_state_start.sql
> -create or replace function change_access_privilege(grant_or_revoke boolean) returns void as
I have added it back.

2022-11-01 23:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
> -alter table if exists crypto_transfer set (
The importer wouldn't run because it did not find the configs for these.

2022-11-01 23:20 UTC, mgoelswirlds commented on docker-compose.yml
> +     image: citusdata/citus:11.1.4
I have created my own image and added it to docker hub and am using that as of now.

2022-11-01 23:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
> -alter table if exists crypto_transfer set (
That’s strange. The values are set in the application.yml file as flyway placeholders. They ran fine before for both v1 and v2. Unless it fails due to v2 timestamp partition, it should still work. So probably you were running it as a stand-alone SQL file instead of running its with importer Java application?

2022-11-02 02:25 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
> -alter table if exists crypto_transfer set (
I have messaged you offline with the error while running the importer.

2022-11-03 01:51 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
> -alter table if exists crypto_transfer set (
Also, if this is not relevant right now, I suggest we remove it.

2022-11-03 16:16 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
> -alter table if exists crypto_transfer set (
I have created a bug https://github.com/hashgraph/hedera-mirror-node/issues/4814

2022-11-08 23:03 UTC, steven-sheehy requested changes

2022-11-09 13:22 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__static_partitioning.sql
> +select partman.create_parent('public.contract_state_change', 'contract_id', 'native', '100000');
@steven-sheehy I have contract_state and state_change listed as id.
So we want those by consensus_timestamp as well?

2022-11-09 13:52 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/globalSetup.js
> +      const query =
Yes I was going to use everything from one place but missed it. Thanks.

2022-11-09 14:02 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                     $$select partman.create_parent('public.transaction', 'consensus_timestamp', 'native', 'yearly', '{"type"}', p_epoch := 'nanoseconds' , p_premake := 2,
I am matching all  of them to be daily, So do we want transaction ones to still be monthly?

2022-11-09 14:06 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                     $$select partman.create_parent('public.transaction', 'consensus_timestamp', 'native', 'yearly', '{"type"}', p_epoch := 'nanoseconds' , p_premake := 2,
It is `p_type - one of the following values to set the partitioning type that will be used:
native
Use the native partitioning methods that are built into PostgreSQL 10+.
For PG11+, it is highly recommended that native partitioning be used over trigger-based partitioning. PG10 is still lacking significant features for native partitioning, so please see notes above for more info.
Provides significantly better write & read performance than "partman" partitioning.
Child table creation is kept up to date by running run_maintenance(_proc). There is no trigger maintenance.
partman
Create a trigger-based partition set using pg_partman's method of partitioning.
Whether it is time or serial based is determined by the control column's data type and if the p_epoch flag is set.
The number of partitions most efficiently managed behind and ahead of the current one is determined by the optimize_trigger config value in the part_config table (default of 4 means data for 4 previous and 4 future partitions are handled best).
Beware setting the optimize_trigger value too high as that will lessen the efficiency boost.
Inserts to the parent table outside the optimize_trigger window will go to the proper child table if it exists, but performance will be degraded due to the higher overhead of handling that condition.
If the child table does not exist for the value given, the row will go to the parent.
Child table creation & trigger function is kept up to date by the run_maintenance() function.`

But I don't think this is needed here.

2022-11-09 14:07 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                     $$select partman.create_parent('public.transaction', 'consensus_timestamp', 'native', 'yearly', '{"type"}', p_epoch := 'nanoseconds' , p_premake := 2,
Cleaning it up.

2022-11-09 14:45 UTC, mgoelswirlds commented on hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
> +    initScriptPath: db/scripts/init-v2.sql
I can't really do this. I had tried to aggregate this but src/test/resources is not accessible by other folders.
https://stackoverflow.com/questions/57508449/are-files-in-src-test-resources-on-classpath-while-application-src-main-is-run

Unless I add the script  to main, it will not work, I think.

2022-11-09 15:31 UTC, mgoelswirlds commented on docker-compose.yml
> +  citus:
Need to debug further but looks like atleast running the distribution sql needs the postgres container. Something in the citus one is missing what is available in postgres. Need to debug further to see what that extension is.

2022-11-09 16:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +SELECT cron.unschedule(jobid) FROM cron.job;
Ok, thanks for clarifying.

2022-11-09 16:31 UTC, mgoelswirlds commented on hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
> +    initScriptPath: db/scripts/init-v2.sql
yes. I used filesystem.

2022-11-09 16:54 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                      p_start_partition := to_char(CURRENT_TIMESTAMP-'3 years'::interval, 'YYYY-MM-DD HH24:MI:SS')) $$);
This is a valid concern. I will test out the default behaviour.

2022-11-09 18:40 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                     $$select partman.create_parent('public.entity_stake', 'id', 'native', '100000') $$);
What schema are you exactly talking about? The partitioning column?

2022-11-09 20:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                     $$select partman.create_parent('public.entity_stake', 'id', 'native', '100000') $$);
The PostgreSQL [schema](https://www.postgresql.org/docs/current/ddl-schemas.html) which is by default `public` but users can set to something else.

2022-11-09 20:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                     $$select partman.create_parent('public.transaction', 'consensus_timestamp', 'native', 'yearly', '{"type"}', p_epoch := 'nanoseconds' , p_premake := 2,
I think the cron schedule should all run `@daily` for all tables.

2022-11-09 20:09 UTC, xin-hedera requested changes

2022-11-09 20:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/Dockerfile
> +COPY 001-create-citus-extension.sql /docker-entrypoint-initdb.d/
this file should be already there as we use `citusdata/citus:11.1.4-pg14` as the base image

2022-11-09 20:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/Dockerfile
> +    && make install
this builds and installs pg_cron and pg_partman from the HEAD commit of the default branches. We should build from a GA release instead.

this is what I added to the [file](https://github.com/citusdata/docker/blob/master/alpine/Dockerfile) 

```
ARG PG_CRON_VERSION=1.4.2
ARG PG_PARTMAN_VERSION=4.7.1

# Install pg_cron and pg_partman
RUN apk add --no-cache --virtual .fetch-deps build-base ca-certificates clang-dev llvm13 openssl tar \
    && wget -O /pg_cron.tar.gz https://github.com/citusdata/pg_cron/archive/v$PG_CRON_VERSION.tar.gz \
    && mkdir -p pg_cron \
    && tar xvzf pg_cron.tar.gz \
    && cd pg_cron-$PG_CRON_VERSION \
    && sed -i.bak -e 's/-Werror//g' Makefile \
    && sed -i.bak -e 's/-Wno-implicit-fallthrough//g' Makefile \
    && make && make install \
    && cd .. && rm -rf pg_cron.tgz && rm -rf pg_cron-*

RUN apk add --no-cache --virtual .build-deps \
    && wget -O pg_partman.tar.gz "https://github.com/pgpartman/pg_partman/archive/v$PG_PARTMAN_VERSION.tar.gz" \
    && tar xvzf pg_partman.tar.gz \
    && cd pg_partman-$PG_PARTMAN_VERSION \
    && make \
    && make install \
    && cd .. \
    && rm -rf pg_partman.tar.gz  pg_partman-* \
    && apk del .fetch-deps .build-deps
```

you need to make some changes for the apt package system.

2022-11-09 20:16 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
> +    initScriptPath: db/scripts/init-v2.sql
I tested against main and set `spring.flyway.locations: "filesystem:../hedera-mirror-importer/src/test/resources/db/migration/v1"` in grpc test bootstrap.yml and moved the migrations to test and everything worked. Pretty sure this will work for you.

2022-11-09 21:10 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/Dockerfile
> +COPY 001-create-citus-extension.sql /docker-entrypoint-initdb.d/
Yes but my file has new commands to install extensions. I kept it even for postgres DB.

2022-11-09 21:11 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__partitioning.sql
> +                      p_start_partition := to_char(CURRENT_TIMESTAMP-'3 years'::interval, 'YYYY-MM-DD HH24:MI:SS')) $$);
We can't use default behaviour but I will make if customizable.

2022-11-09 21:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/Dockerfile
> +COPY 001-create-citus-extension.sql /docker-entrypoint-initdb.d/
I see the sql file in the PR now. Then we add our own `002-*.sql` for partman

2022-11-09 21:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/Dockerfile
> +COPY 001-create-citus-extension.sql /docker-entrypoint-initdb.d/
checked it again. aren't we doing partman extension and schema in the init.sh / init.sql? If so, we don't have to add or modify any init sql in the docker image at all.

2022-11-09 23:13 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/Dockerfile
> +COPY 001-create-citus-extension.sql /docker-entrypoint-initdb.d/
Will get rid of it.

2022-11-11 19:35 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/resources/db/scripts/init-v2.sql
> +create user mirror_importer with login password 'mirror_importer_pass' in role readwrite;
I am not doing this for now. Since I am leaving in the init-v2 files.

2022-11-28 19:53 UTC, mgoelswirlds commented on hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
> +    initScriptPath: db/scripts/init-v2.sql
I have created a separate ticket for this https://github.com/hashgraph/hedera-mirror-node/issues/4963

2022-12-02 05:34 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  // extract amount of time caused by trying to delete from partitions. The cleanup sql for v2 is generated once for
```suggestion
  // exact amount of time caused by trying to delete from partitions. The cleanup sql for v2 is generated once for
```

2022-12-02 05:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/IntegrationTestConfiguration.java
> +        return tables.stream().map((t) -> String.format("delete from %s;", t)).collect(Collectors.joining("\n"));
Prefer this moved to a `scripts/cleanup-v2.sql` or `scripts/v2/cleanup.sql`. Then it can also be reused elsewhere. Though renaming the v1 path to be consistent might break ops' scripts. Then two conditional beans are not needed and can just have one resource loading where the path is conditional based upon an injected `ConfigurableEnvironment.getActiveProfiles()`.

2022-12-02 14:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/IntegrationTestConfiguration.java
> +        return tables.stream().map((t) -> String.format("delete from %s;", t)).collect(Collectors.joining("\n"));
The query is split into two:

- first find the tables without partitions and the parent tables of the partitioned tables, and the second
- generate a clean up sql to delete those tables

The reason is the first part is slow so doing it this way we only run the first part once for one integration test application context. As a result, we can't move it to a sql script file in the classpath.

2022-12-02 14:59 UTC, xin-hedera commented on docs/importer/README.md
> +Depending on whether you need an alpine or debian image , the Docker files are located in the named folders respectively.
the alpine based image isn't compatible with our charts, so we need the debian image.

however, we can only build multi-arch image with the alpine based Dockerfile, in order to make running integration tests and debugging on M1 easier, we need to keep the alpine Dockerfile as well.

2022-12-02 15:05 UTC, xin-hedera commented on docs/importer/README.md
> +Depending on whether you need an alpine or debian image , the Docker files are located in the named folders respectively.
once citus releases arm deb packages, we will be able to build a mutli-arch debian image. Or we can spend effort to do either of

- compile citus from the source code in the debian Dockerfile
- figure out how to make the alpine based image to work with the bitnami postgresql chart

I just don't want to further extend the scope of the PR and it's probably not worth the effort either.

2022-12-02 18:31 UTC, steven-sheehy approved these changes
LGTM

2022-12-02 19:08 UTC, xin-hedera approved these changes
LGTM

2022-12-02 19:57 UTC, steven-sheehy approved these changes

2022-12-02 20:02 UTC, merged