Fix incorrect staking info and pending reward
hashgraph/hedera-mirror-node pull request #4838
Opened 2022-11-07 22:32 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #4815 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-11-07 22:38 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java
> -    void noTreasuryUpdate() {
remove test case which no longer applies

2022-11-07 22:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +            select account_id is null or epoch_day = -1 or epoch_day = end_stake_period
account `0.0.800` missing in some preprod envs, so pretend to be `always update` and pending reward calculation will be skipped in those envs.

2022-11-09 21:04 UTC, edwin-greene approved these changes
Looks good to me!

2022-11-09 21:53 UTC, MarcKriguerAtHedera submitted a review, later dismissed
**Huge** PR, but otherwise LGTM.

2022-11-10 23:47 UTC, steven-sheehy requested changes

2022-11-10 23:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    });
I think instead of modifying TransactionHandler we can just do this simple change in SqlEntityListener. It should be equivalent to the current approach and don't need to worry about nodestakeupdate.
```java
    public void onStakingRewardTransfer(StakingRewardTransfer stakingRewardTransfer) {
        stakingRewardTransfers.add(stakingRewardTransfer);

        var entity = entityState.get(stakingRewardTransfer.getAccountId());
        long consensusTimestamp = stakingRewardTransfer.getConsensusTimestamp();

        if (entity != null && entity.getTimestampLower() == consensusTimestamp && entity.getStakePeriodStart() == null) {
            entity.setStakePeriodStart(Utility.getEpochDay(consensusTimestamp) - 1);
        } else if (entity == null) {
            // The staking reward may be paid to either an account or a contract. Create non-history
            // updates with the new stake period start and set the type to account, the upsert sql will
            // get the correct entity type from what's in db
            var account = accountId.toEntity();
            account.setStakePeriodStart(stakePeriodStart);
            account.setTimestampRange(null); // Don't trigger a history row
            onEntity(account);
        }
    }
```

2022-11-10 23:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql
> +with mainnet_last_26_file as (
Move to Java migration so we can target mainnet only.

2022-11-10 23:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql
> +with mainnet_last_26_file as (
Why does this SQL need to be repeatable considering it has hardcoded timestamps? And if it can be versioned than can we combine it with other java migration?

2022-11-11 19:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    });
sure. will implement and test it

2022-11-11 19:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql
> +with mainnet_last_26_file as (
just in case for some mirrornode deployment which run the migration before ingesting the transactions which config account/contract to stake to a node as of services < 0.27.0. so later can do some trick to rerun the migration.

2022-11-11 21:08 UTC, mgoelswirlds commented
Still reviewing.

2022-11-14 04:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql
> +with mainnet_last_26_file as (
I don't think that's a concern. 0.26.0 is really old and any mirror node running should have already processed them or have upgraded to a version with this fix.

2022-11-14 04:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java
> +              where consensus_timestamp > 1666310400447390002
Can't we calculate this from network_stake where staking_reward_rate <> 0 and thus make this sql not specific to any environment? Then can move to .sql file.

2022-11-14 17:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java
> +              where consensus_timestamp > 1666310400447390002
suspect there will be huge performance penalty that an index scan on crypto transfer changes to sequential scan, then the migration will run for a couple of hours

2022-11-14 17:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +            from staked_before_alive, mainnet_last_26_file
used to produce no output when there is no such record file in the db

2022-11-14 17:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java
> +              where consensus_timestamp > 1666310400447390002
for the same reason, we can't make it generic to any environment per the suggestion.

however, we can probably parameterize the timestamp and hardcode it with values for mainnet and testnet. I just don't see much value of fixing testnet

2022-11-14 17:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +              select index from record_file where consensus_end = 1658419200981687000
it's really slow. not sure how long it'll take since I stopped at 30 minutes. As responded in the other thread, we can hard code the values for mainnet and testnet and keep it as a java migration.

2022-11-15 03:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql
> +with mainnet_last_26_file as (
changed it to a versioned non-repeatable Java migration

2022-11-15 03:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +              select index from record_file where consensus_end = 1658419200981687000
added support for testnet with hardcoded consensus end.

2022-11-15 03:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +              where coalesce(lower(h.timestamp_range), lower(p.timestamp_range)) <= 1658419200981687000
changed it to a named parameter

2022-11-15 03:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +              where stake_period_start <= 19194 and stake_period_start <> -1 and staked_node_id <> -1 and type in ('ACCOUNT', 'CONTRACT')
changed it to a named parameter and the value is calculated in application code from the corresponding consensus timestamp

2022-11-15 03:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +              select id,deleted,decline_reward,staked_node_id,stake_period_start,timestamp_range
removed

2022-11-15 03:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java
> +            update entity
added CTE to also fix `entity_history`

2022-11-15 15:35 UTC, edwin-greene approved these changes
Looks good to me.

2022-11-15 16:46 UTC, steven-sheehy approved these changes
LGTM

2022-11-15 16:50 UTC, merged