Add Staking Reward Transfers to REST API
hashgraph/hedera-mirror-node pull request #4842
Opened 2022-11-09 16:29 UTC by edwin-greene

**Description**:
The REST API will now show Staking Reward Transfers.

**Related issue(s)**:

Fixes #4703 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-11-09 18:43 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/no-params.json
> +        ],
It is unusual, but after checking with Xin this is expected behavior. The staking reward for `0.0.123` appears in the transaction for account `0.0.8` even though the url queried is `/api/v1/transactions?account.id=8`.

2022-11-09 21:47 UTC, MarcKriguerAtHedera approved these changes
As mentioned directly to you in chat, I am concerted about future merge conflicts between this PR and the one I am working on for Issue 4744, but I'll deal with that when it happens.  Those conflicts (which really, honestly, are more duplicates than conflicts, per se) are just for __tests__/integrationDomainOps.js and api/v1/openapi.yml; the rest of the changes are to different files in your PR and mine.

Yours looks good to me!

2022-11-09 23:32 UTC, xin-hedera requested changes

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const STAKING_REWARD_ACCOUNT = '0.0.800';
change it the value to `800`, and move the constant to `model/stakingRewardTransfer.js`

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +import StakingRewardTransfer from './model/stakingRewardTransfer.js';
```suggestion
import {StakingRewardTransfer} from './model';
```

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const addStakingRewardTransfers = async (transferList) => {
call it before `createTransferLists` so we don't have to convert values (timestamp, account id) back

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +};
if we use the data returned from SQL query, i.e., before calling `createTransfersLists`, we can just do

```javascript
transactions
  .filter((transaction) => transaction.crypto_transfer_list.some((cryptoTransfer) => cryptoTransfer.entity_id === STAKING_REWARD_ACCOUNT))
  .map((transaction) => transaction.consensus_timestamp);
```
we should also replace the function with the 3-line code snippet.

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +                    ${whereClause}`;
also need to add `order by consensus_timestamp asc, account_id asc`, the order for consensus_timestamp should be the same as in the query param, the default is `desc` I believe

```suggestion
  const query = `select ${StakingRewardTransfer.ACCOUNT_ID},
                        ${StakingRewardTransfer.AMOUNT},
                        ${StakingRewardTransfer.CONSENSUS_TIMESTAMP}
                    from ${StakingRewardTransfer.tableName}
                    where ${StakingRewardTransfer.CONSENSUS_TIMESTAMP} in (${positions})`;
```

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +};
should move the logic of adding staking reward transfer to `createTransferLists`

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    const stakingTransactions = transferList.transactions.filter((t) => t.consensus_timestamp === consensusTimestamp);
this is a worst-scenario O(n^2) complexity, since there are two loops, the outer for loop and this `transferList.transactions.filter`

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +                    ${whereClause}`;
we should change the staking reward transfer query to return a json array which groups by the consensus timestamp, it'll reduce the complexity when merging the staking reward transfers into the transaction rows

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    }
this can be simplified after we change the SQL query to return json strings grouped by consensus timestamp

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/model/stakingRewardTransfer.js
> +class StakingRewardTransfer {
import and export it in `index.js`

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +                type: integer
add `nullable: false` and add a description

2022-11-09 23:32 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +              - amount
move it into its own schema `stakingRewardTransfer` for reuse

2022-11-16 20:53 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +                type: integer
Sounds good I have made this change.

2022-11-16 20:53 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +              - amount
I've updated it.

2022-11-16 20:54 UTC, edwin-greene commented on hedera-mirror-rest/model/stakingRewardTransfer.js
> +class StakingRewardTransfer {
Thanks I have fixed it.

2022-11-16 20:54 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +const STAKING_REWARD_ACCOUNT = '0.0.800';
I have changed the value and moved it to the model class.

2022-11-16 20:55 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  );
Sounds good I have removed this section.

2022-11-16 20:55 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    consensus_timestamp: 0,
Thanks I have updated it.

2022-11-16 20:57 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +import StakingRewardTransfer from './model/stakingRewardTransfer.js';
Fixed.

2022-11-16 20:57 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +const addStakingRewardTransfers = async (transferList) => {
Great idea, I have made this change.

2022-11-16 20:58 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +};
Thanks I have updated the method as suggested.

2022-11-16 20:59 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +                    ${whereClause}`;
Awesome thanks. I have made those changes, but I have placed the query results in a map with the consensus timestamp as the key, so there may not be a need to `order by`.

2022-11-16 20:59 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +};
Sounds good. This method has been deleted.

2022-11-16 21:00 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +    const stakingTransactions = transferList.transactions.filter((t) => t.consensus_timestamp === consensusTimestamp);
I have updated it to use a map on consensus timestamp, so the lookup will now be O(1) within `createTransferLists`.

2022-11-16 21:01 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +    }
Great, I have updated it to use `json_agg`.

2022-11-17 19:46 UTC, xin-hedera requested changes

2022-11-17 19:46 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    ? []
remove the `isNil` check, if the sql returns no result, the `transactions` will be an empty array, so `isNil` will be always false

2022-11-17 19:46 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (_.isNil(stakingRewardTimestamps) || stakingRewardTimestamps.length === 0) {
remove the redundant `isNil` check since it will never be nil.

2022-11-17 19:46 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +             '${StakingRewardTransfer.AMOUNT}', ${StakingRewardTransfer.AMOUNT}))
nit
```suggestion
           json_agg(json_build_object(
             'account', ${StakingRewardTransfer.ACCOUNT_ID},
             '${StakingRewardTransfer.AMOUNT}', ${StakingRewardTransfer.AMOUNT})) as staking_reward_transfers
```

also change `t.json_agg` to `t.staking_reward_transfers` on line 372

2022-11-17 19:46 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  rows.map((t) => rewardsMap.set(t.consensus_timestamp, t.json_agg));
need to convert the encoded `account` to `shard.realm.number` format.

To be consistent, add a function `createStakingRewardTransferList` add call it in `createTransferList`. Also the `createStakingRewardTransferList` should return an empty array if there is no staking reward transfers at a specific timestamp so that in the transactions response json, we will always have the `staking_reward_transfers` field.

2022-11-17 19:46 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: false
account's type is `EntityId`

2022-11-18 18:58 UTC, MarcKriguerAtHedera approved these changes
LGTM

2022-11-21 19:35 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +    ? []
Thanks I have removed it.

2022-11-21 19:35 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  if (_.isNil(stakingRewardTimestamps) || stakingRewardTimestamps.length === 0) {
Fixed.

2022-11-21 19:35 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +             '${StakingRewardTransfer.AMOUNT}', ${StakingRewardTransfer.AMOUNT}))
Thanks for the input. I have made these changes.

2022-11-21 19:36 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  rows.map((t) => rewardsMap.set(t.consensus_timestamp, t.json_agg));
Sounds good. I have updated the methods so that `createStakingRewardTransferList` is called by `createTransferList`.

2022-11-21 19:36 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: false
Thanks for spotting that. I have fixed it.

2022-11-21 19:40 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
>        },
Precedence in the spec files for specifying cryptotransfers has `accountId` and `payerAccountId`, so I changed these to match.

2022-11-21 19:41 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/no-params.json
>        }
After speaking with Xin, account 800 has no signing key so it can never be the payerAccount. With staking rewards the payerAccount can be considered to be the account itself.

2022-11-23 01:22 UTC, steven-sheehy requested changes

2022-11-23 15:50 UTC, xin-hedera requested changes

2022-11-23 15:50 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const STAKING_REWARD_ACCOUNT = '0.0.800';
still here, need to remove
```suggestion
```

2022-11-23 15:50 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  });
```suggestion
  rows.forEach((t) => {
    t.staking_reward_transfers.forEach((transfer) => {
      transfer.account = EntityId.parse(transfer.account).toString();
    });
    rewardsMap.set(t.consensus_timestamp, t.staking_reward_transfers);
  });
```

Array.prototype.map() `creates a new array populated with the results of calling a provided function on every element in the calling array.`

2022-11-23 16:17 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  return rows;
The result of `await pool.queryQuietly(query, stakingRewardTimestamps)` is an object containing a property of `rows`. `{rows}` is the rows object from the query, rather than the entire result object from the `pool.queryQuietly` function. So changing this would return non-needed properties to the calling method.

2022-11-23 16:33 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  });
Thanks, this is now fixed.

2022-11-23 16:33 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +const STAKING_REWARD_ACCOUNT = '0.0.800';
Thanks I have removed this line.

2022-11-23 17:43 UTC, xin-hedera requested changes

2022-11-23 18:37 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "accountId": "0.0.1001",
Sounds good I have reverted those changes.

2022-11-23 19:07 UTC, xin-hedera approved these changes

2022-11-23 20:21 UTC, steven-sheehy approved these changes
LGTM

2022-11-23 20:34 UTC, merged