Contract results endpoint should include evm_address field for created contracts
hashgraph/hedera-mirror-node pull request #4849
Opened 2022-11-10 12:45 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #4841

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-11-11 03:03 UTC, Nana-EC reviewed
Mostly good.
Curious about the null case though

2022-11-11 18:55 UTC, xin-hedera requested changes

2022-11-11 18:55 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +              nullable: true
don't think it's actually `nullable`, the field is either in the response with a non null value or not in the response. In addition, I'm not sure I agree that the field is populated conditionally depending on the endpoints.

2022-11-11 18:55 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/no-evm-address.json
> +    "error_message": null,
the response should show `"evm_address": "0x"`

2022-11-13 23:05 UTC, steven-sheehy requested changes

2022-11-14 23:51 UTC, steven-sheehy approved these changes
LGTM

2022-11-15 01:01 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-11-15 06:15 UTC, Nana-EC approved these changes
LG

2022-11-15 14:20 UTC, steven-sheehy approved these changes

2022-11-15 14:21 UTC, merged