Implement API method /api/v1/accounts/{id}/rewards .
hashgraph/hedera-mirror-node pull request #4852
Opened 2022-11-11 02:16 UTC by MarcKriguerAtHedera

Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:
This PR adds the REST API method /api/v1/accounts/{id}/rewards and many tests,
but the monitor_api tests for this new method are still to be written.

**Related issue(s)**:

Fixes #4744

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (spec, integration, etc.)

2022-11-11 04:19 UTC, MarcKriguerAtHedera commented
20 spec tests (all related to this new new API method) are failing at the moment... still trying to fix those up.

2022-11-14 00:00 UTC, steven-sheehy requested changes

2022-11-14 00:00 UTC, steven-sheehy commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    conditions.unshift(`${StakingRewardTransfer.getFullName(StakingRewardTransfer.ACCOUNT_ID)}` + ' = $1');
This logic is comple, uses a lot of concatenation, doesn't support collapsing multiple equality operators into a single IN clause. Should probably be removed. See `extractNetworkNodesQuery` for an example of an alternative.

2022-11-14 11:17 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "timestamp": "0.000022222"
Done; replaced this with 123456789.0000xxxxx in all tests.

2022-11-14 11:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  };
I moved the defaults into a const, but when I try to set `insertFields` to `Object.keys(stakingRewardsTramsfer)`, 23 of the spec tests fail with the error message `column "accountid" of relation "staking_reward_transfer" does not exist`; only setting this manually seems to work for me.

2022-11-14 11:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParam'
Done.

2022-11-14 11:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/model/stakingRewardTransfer.js
> +  static CONSENSUS_TIMESTAMP = 'consensus_timestamp';
Done.

2022-11-14 11:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/viewmodel/stakingRewardTransferViewModel.js
> +    this.account_id = EntityId.parse(stakingRewardTransferModel.accountId, {isNullable: true}).toString();
Done.

2022-11-14 11:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +      super.getLimitQuery(2),
I changed it to `super.getLimitQuery(params.length)`, but the parameter here is the condition number and not the actual limit value.

2022-11-14 11:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +          whereQuery.push('srt.' + FileData.CONSENSUS_TIMESTAMP + ' ' + `${filter.operator}` + ' ' + filter.value);
Done.

2022-11-14 11:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/invalid-params.json
> +  },
Done.

2022-11-14 11:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/invalid-params.json
> +  "url": "/api/v1/accounts/0.0.1001/rewards?timestamp=ne:1234567890.000011111&order=12&limit=a",
Moved to a separate test.

2022-11-14 11:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/invalid-path.json
> +  },
Done.

2022-11-14 11:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +    "nfts": [],
Done.

2022-11-14 11:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/invalid-path.json
> +    "/api/v1/accounts/KGNABD5L3ZGSRVUCSPDR7TONZSRY3D5OMEBKQMVTD2AC6JL/rewards",
Done (except for the 8-9 numbers, which didn't generate he expected errors).

2022-11-14 11:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/not-found.json
> +  "description": "Account staking reward payouts api call for an account with no rewards",
Done.

2022-11-14 11:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/specific-timestamp.json
> +    "/api/v1/accounts/0.0.ebb9a1be370150759408cd7af48e9eda2b8ead57/rewards?timestamp=0.000022222"
Done.

2022-11-14 11:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    conditions.unshift(`${StakingRewardTransfer.getFullName(StakingRewardTransfer.ACCOUNT_ID)}` + ' = $1');
I cleaned it up somewhat (moved into a separate method without the ternary operator/. I hope it's easier to understand now.

2022-11-14 16:57 UTC, xin-hedera requested changes

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const insertFields = ['account_id', 'amount', 'consensus_timestamp', 'payer_account_id'];
convert `account_id` and `payer_account_id` so in spec we can support `0.0.X` entity ID strings

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    payer_account_id: 800,
nit, payer account id can't be 800 in our network, can set the default to 1001

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  // const insertFields = Object.keys(stakingRewardTransfer).sort();
remove the comment

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "accountId": "0.0.1001",
use snake case since that's the naming convention of the db column names

```suggestion
        "account_id": "0.0.1001",
```

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "payerAccountId": "0.0.800"
```suggestion
        "payer_account_id": "0.0.800"
```

In addition, I don't think payer account id matters in any of your test cases, so can just remove it

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +  "url": "/api/v1/accounts/0.0.1001/rewards?timestamp=gte:0&order=asc&limit=2",
add urls:

- /api/v1/accounts/1001/rewards?timestamp=gte:0&order=asc&limit=2
- /api/v1/accounts/0.1001/rewards?timestamp=gte:0&order=asc&limit=2

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/server-error.json
> +  "description": "Account staking reward payouts api call with all applicable params *should* work, but throws an internal error",
why is there a 500 server error?

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: 0.0.1000
```suggestion
```

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: false
```suggestion
```

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: integer
add `nullable: false`

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    let whereQuery = [];
```suggestion
    const whereQuery = [];
```

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    from ${StakingRewardTransfer.tableName} ${StakingRewardTransfer.tableAlias}`;
remove all `StakingRewardTransfer.getFullName`, remove `${StakingRewardTransfer.tableAlias}`

also add

`where ${StakingRewardTransfer.ACCOUNT_ID} = $1`

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +            }`
I'm against constructing SQL expression in both the controller and the service. we should do that in the service.

put that aside, we should add the filter value into the params array and refer to it using postgres positional param

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    const params = [accountId];
why add `accountId` to params array and then also pass it explicitly to `StakingRewardTransferService.getRewards`? Only one way or the other.

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    }
why the conditional here? as in the other comment, we should either pass accountId explicitly or just assume it's the first element in the params array, not both.

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    //  Otherwise, just take the where condition's string value as a pre-parsed "where"-like clause.
why would there be a `key` element in the condition? the only consumer of the service is the controller, and the controller just adds SQL expressions to the `whereQuery` and pass it as `whereConditions`

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    conditions.unshift(`${StakingRewardTransfer.getFullName(StakingRewardTransfer.ACCOUNT_ID)}` + ' = $1');
the condition should be hardcoded into the query
```suggestion
```

2022-11-14 16:57 UTC, xin-hedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +        OrderSpec.from(`${StakingRewardTransfer.getFullName(StakingRewardTransfer.CONSENSUS_TIMESTAMP)}`, order)
```suggestion
        OrderSpec.from(`${StakingRewardTransfer.CONSENSUS_TIMESTAMP}`, order)
```

2022-11-14 21:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const insertFields = ['account_id', 'amount', 'consensus_timestamp', 'payer_account_id'];
I'm not sure I understand -- convert `account_id` and `payer_account_id` to what?

2022-11-14 21:50 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    payer_account_id: 800,
`account_id` is set to `1001`, so I updated `payer_account_id` to `950` since you say it can't be `800`.

2022-11-14 21:51 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  // const insertFields = Object.keys(stakingRewardTransfer).sort();
Done.

2022-11-14 21:53 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "accountId": "0.0.1001",
Done.

2022-11-14 21:55 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "payerAccountId": "0.0.800"
Done.

2022-11-14 22:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +  "url": "/api/v1/accounts/0.0.1001/rewards?timestamp=gte:0&order=asc&limit=2",
Done.

2022-11-14 22:03 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/server-error.json
> +  "description": "Account staking reward payouts api call with all applicable params *should* work, but throws an internal error",
"server-error.json" was accidentally checked in; removing the file.  But I am trying to debug the 500.  That's what the URL currently serves, but it should be a 200.

2022-11-14 22:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: 0.0.1000
Done.

2022-11-14 22:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          nullable: false
Done.

2022-11-14 22:18 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    from ${StakingRewardTransfer.tableName} ${StakingRewardTransfer.tableAlias}`;
Done.

2022-11-14 22:20 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const insertFields = ['account_id', 'amount', 'consensus_timestamp', 'payer_account_id'];
in your spec files, most places the account_id is set as `"accountId": "0.0.1001"`, once you fix it by changing the field name, a.k.a, `"account_id": "0.0.1001"`, all your test cases will fail, since the db column `account_id` is of type `bigint`, the string `0.0.1001` obviously is an invalid value

so what I meant is, convert `0.0.1001` to `1001` by `EntityId.parse(...).getEncodedId()`

2022-11-14 22:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +            }`
Per Steven's request, I redid this method to match the style/technique of  `extractNetworkNodesQuery` -- but that's also a controller writing SQL, isn't it?

2022-11-14 22:23 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +    const params = [accountId];
Now initialized to [].  The `updateConditionsAndParamsWithInValues` method from the BaseController how adjusts the params.

2022-11-14 22:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    }
(Already) Done.

2022-11-14 22:27 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    payer_account_id: 800,
just want to note it's not changed. most likely the changes are local and haven't been pushed to the repo.

2022-11-14 22:30 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    //  Otherwise, just take the where condition's string value as a pre-parsed "where"-like clause.
The earlier version of the controller was adding key / operator / value `key`s.  .

2022-11-14 22:33 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    conditions.unshift(`${StakingRewardTransfer.getFullName(StakingRewardTransfer.ACCOUNT_ID)}` + ' = $1');
Already Done.

2022-11-14 22:38 UTC, MarcKriguerAtHedera commented
Implemented all of Xin's suggestions.

2022-11-14 23:09 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const table = getTableName('staking_reward_transfer', stakingRewardTransfer);
nit, remove 
```suggestion
```

only have to call `getTableName` for a table if it has history table.

2022-11-14 23:15 UTC, xin-hedera requested changes

2022-11-14 23:15 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    params.unshift(accountId, limit);
again, duplicate info in two places

- `accountId` and `limit` are passed as explicit function args in `StakingRewardTransferService.getRewards`
- they are also pushed into the `params` array

2022-11-14 23:15 UTC, xin-hedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    params.push(limit); // always $2
two issues

- `accountId` and `limit` are already the first and the second elements in the array as done in the controller
- Array.push appends so the comment of `always $1 / $2` is incorrect

2022-11-14 23:20 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +            }`
correct. that requires more effort so we can leave it as is, address it later when we switch to Java. The correct flow of constructing sql expressions / statements in both controller and service is confusing and difficult to understand.

2022-11-15 00:42 UTC, rahuljaguste commented
@xin-hedera Is it possible to add the staked_to field to StakingReward object which returns the node id or the account id for which the stake rewards was received?

2022-11-15 01:11 UTC, steven-sheehy requested changes

2022-11-15 01:11 UTC, steven-sheehy commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +      super.getOrderByQuery(OrderSpec.from(`${StakingRewardTransfer.CONSENSUS_TIMESTAMP}`, order)),
nit: No need for string templating with single value
```suggestion
      super.getOrderByQuery(OrderSpec.from(StakingRewardTransfer.CONSENSUS_TIMESTAMP, order)),
```

2022-11-15 01:18 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const table = getTableName('staking_reward_transfer', stakingRewardTransfer);
Done.

2022-11-15 01:38 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +    params.unshift(accountId, limit);
But those two methods don't call each other; should they?  (It seems there are _some_ examples of controllers calling into services, but not the other way around.  But right now, even though `listStakingRewardsByAccoiuntId()` in the controller *dpes* call `StakingRewardTransferService.getRewards()` directly, it still doesn't feel like they are working hand in hand.  I will go ahead and remove the two calls to `params.push` (of `accountId` and `limit` in `StakingRewardsTransferService.getRewardsQuery()`, since I agree we shouldn't be doing it twice -- but will that suffice?

2022-11-15 01:40 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    params.push(limit); // always $2
The controller is still assigning `accountId` and `limit` as before, but I removed those two lines from the `getRewardsQuery` code.

2022-11-15 01:44 UTC, xin-hedera commented on hedera-mirror-rest/controllers/accountController.js
> +    params.unshift(accountId, limit);
this is what I suggest:

- remove the `params.unshift(accountId, limit)` from the controller, and keep the `params` array for the timestamp values
- keep `StakingRewardTransferService.getRewards()` definition as is, i.e., explicitly pass `accountId` and `limit`
- In the service, add `params.unshift(accountId, limit)`

The confusion is largely because we build SQL and the value params array in both the controller and the service.

2022-11-15 02:03 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +        "timestamp": "1234567890000011111"
They are now restored.

2022-11-15 02:19 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/viewmodel/stakingRewardTransferViewModel.js
> +    this.consensus_timestamp = nsToSecNs(stakingRewardTransferModel.consensusTimestamp);
Just to confirm: the `staking_reward_transfer` table does have its column named *consensus_timestamp*; it's just the API that calls its column that (and wants its input fields called that).

If so, then I think openapi had it right, it's only the viewmodel that got this mixed up.  Fixed now.

2022-11-15 02:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +      super.getOrderByQuery(OrderSpec.from(`${StakingRewardTransfer.CONSENSUS_TIMESTAMP}`, order)),
I think I figured out how to do the "class consts" thing (please let me know if it's still not right.  But I could not find a place where Object.keys(...) seems to work with a parameter named "account_id" -- and yet plenty of other camel-cased parameters all do seem to work.

Appliied your sugestion for stakingRewardTransferService.js.

2022-11-15 15:55 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/stakingRewardTransferViewModel.js
> +    this.consensus_timestamp = nsToSecNs(stakingRewardTransferModel.consensusTimestamp);
Right, but you need to update all specs to use `timestamp`.

2022-11-15 16:35 UTC, xin-hedera commented
> @xin-hedera Is it possible to add the staked_to field to StakingReward object which returns the node id or the account id for which the stake rewards was received?

The StakingReward object has the `account_id` who receives the staking reward. For the node id, did you mean the node the account staked to thus received the reward as an incentive of the account's stake? The API is primarily designed for tax purpose of an account, and adding the node as of when the reward was received has performance penalty depending on how the data is retrieved / saved. It'll be great if you can create a ticket in our repo with the requirement.

2022-11-15 19:00 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/viewmodel/stakingRewardTransferViewModel.js
> +    this.consensus_timestamp = nsToSecNs(stakingRewardTransferModel.consensusTimestamp);
The specs use "consensus_timestamp" only within the `setup/stakingRewardTransfers` sections (matching the schema of the actual `staking_reward_transfers` table).  They use "timestamp" within the `urls` and `responseJson` sections.  Isn't that correct?   (All but 2 of the files had already been fixed before yesterday, but I noticed that just two -- "no-params" and "specific-timestamp" -- had the wrong ones in the responseJson section.  Fixed!

2022-11-15 22:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const insertFields = ['account_id', 'amount', 'consensus_timestamp', 'payer_account_id'];
spec files have been fixed.  `account_id` and `payer_account_id` (in the `setup` sections) are ow set to `1001` (etc).

2022-11-16 00:03 UTC, steven-sheehy requested changes

2022-11-16 00:36 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +          "next": "/api/v1/accounts/0.0.1001/rewards?order=asc&limit=2&timestamp=gt:undefined"
Fixed (by the one-line change you indicated in `accountController.js`)

2022-11-16 06:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/service/stakingRewardTransferService.js
> +    const conditions = conditionsArray.map((condition) => this.conditionToWhereClause(condition));
Done.  Since we are no longer passing in the accountId, then the `pamas.unshift(accountId, limit);` line gets moved to `listStakingRewardsByAccountId` (so that now the test of `extractStakingRewardsQuery` is missing the accountId and limit at the start of the params array.

2022-11-16 06:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +    const query = this.extractStakingRewardsQuery(filters, accountId);
Done.

2022-11-16 06:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +      3 // $1: accountId, $2: limit. $3 onwards: "in" values.
Done.

2022-11-16 06:44 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/specific-timestamp.json
> +    "/api/v1/accounts/KGNABD5L3ZGSRVUCSPDR7TONZSRY3D5OMEBKQMVTD2AC6JL72HMQ/rewards?timestamp=eq:1234567890.000022222"
Done; it's in the new ".../rewards/in-param-with-multple-timestamps.spec" test.

2022-11-16 06:44 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +    const startPosition = 3; // 1st index is reserved for account id; 2nd index is reservered for index.
That last "index" should have been "limit" -- so startPosition is correct at 3.

2022-11-16 06:45 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +        [filterKeys.TIMESTAMP]: lastRow.consensus_timestamp,
Done.  Nice catch!

2022-11-16 19:18 UTC, mgoelswirlds approved these changes
LGTM

2022-11-16 23:38 UTC, steven-sheehy requested changes

2022-11-16 23:38 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +      "url": "/api/v1/accounts/1001/rewards?timestamp=gte:0&order=asc&limit=2",
The 3 tests can be combined into one test with 3 URLs
```suggestion
      "urls": [
        "/api/v1/accounts/1001/rewards?timestamp=gte:0&order=asc&limit=2",
        "/api/v1/accounts/0.1001/rewards?timestamp=gte:0&order=asc&limit=2",
        "/api/v1/accounts/0.0.1001/rewards?timestamp=gte:0&order=asc&limit=2"
      ],
```

2022-11-16 23:38 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/accountController.js
> +      accountId,
accountId is both a parameter and in query.params. The former is unused.

2022-11-17 00:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/all-params.json
> +      "url": "/api/v1/accounts/1001/rewards?timestamp=gte:0&order=asc&limit=2",
When I try this, 2 of the 3 tests fail.  While all 3 have the same "rewards" (with the account_id in the X.Y.Z format), they have a different "next" link (matching the three different input URL's specification of the account_id).  I'm just calling `utils.getPaginationLink(req, false, last, query.order);` to generate the "next" link; I don't' see a variant that lets me replace the account_id in the input URL with the decoded one.

2022-11-17 00:39 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/controllers/accountController.js
> +      accountId,
Removed (from here and from the specs inside the test for stakingRewardsTransferService).

2022-11-17 01:01 UTC, steven-sheehy approved these changes
LGTM

2022-11-17 14:26 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2022-11-17 14:38 UTC, mgoelswirlds approved these changes

2022-11-17 15:53 UTC, xin-hedera requested changes

2022-11-17 15:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.70.0__add_staking-reward-transfer_index.sql
> +-------------------
change the file name to `V1.70.0__add_staking_reward_transfer_index.sql`, all underscores

2022-11-17 17:31 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.70.0__add_staking-reward-transfer_index.sql
> +-------------------
Done.   (Oops, hadn't realized that all the other filenames used underscores).

2022-11-17 17:47 UTC, edwin-greene approved these changes

2022-11-17 17:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.70.0__add_staking-reward-transfer_index.sql
> +-------------------
Done.

2022-11-17 18:56 UTC, xin-hedera approved these changes
LGTM

2022-11-17 19:51 UTC, merged