Empty and null uint256 values show up as 0x
hashgraph/hedera-mirror-node pull request #4881
Opened 2022-11-15 10:17 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #4769

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-11-15 14:31 UTC, steven-sheehy requested changes
Looks good, just requesting some additional test coverage:

* Modify an existing /results/{id} spec to have an unpadded zero slot and unpadded zero value_read
* Modify an existing /state spec to have an unpadded zero value (slot can't be null and will be zero padded already).

2022-11-15 15:58 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +  if (val == null) {
Could switch to `_.isNil` to catch null/undefined.

2022-11-15 17:14 UTC, xin-hedera requested changes

2022-11-15 17:14 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  val = val.length ? val : Buffer.alloc(1);
just return a constant `0x0000000000000000000000000000000000000000000000000000000000000000` if val is an empty array so can avoid allocating a 1 byte buffer and calling `toHexString`

2022-11-16 15:48 UTC, xin-hedera approved these changes

2022-11-16 15:51 UTC, steven-sheehy approved these changes
LGTM

2022-11-16 15:52 UTC, merged