Add acceptance tests for contract call REST API
hashgraph/hedera-mirror-node pull request #4882
Opened 2022-11-15 10:32 UTC by mustafauzunn

**Description**:

Provide E2E Cucumber tests for `eth_call` covering base scenarios, without token precompile calls. The PR setups the infrastructure needed to perform Cucumber scenarios for `eth_call`.

**Related issue(s)**:

Fixes #4873 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-01-24 01:48 UTC, steven-sheehy requested changes

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private final Web3RestProperties web3RestProperties;
Revert

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    private <T> T callWeb3RestEndpointPost(String uri, Class<T> classType, ContractCallRequest contractCallRequest) {
Revert

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/JsonRpcSuccessResponse.java
> +    private T result;
It's not using JSON-RPC.
```suggestion
public class ContractCallResponse {
    private String result;
```

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    public JsonRpcSuccessResponse contractsCallSimulation(String data, String to, String from) {
Not sure why you're using the simulation terminology, but it should just be named like the URI path.
```suggestion
    public ContractCallResponse contractsCall(String data, String to, String from) {
```

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        JsonRpcSuccessResponse identifierResponse = mirrorClient.contractsCallSimulation("7998a1c4", contractId.toSolidityAddress(), contractClient.getClientAddress());
We should give these magic strings a name either as a static constant or an enum so it's clear which contract method we're calling.

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(getAccountBalanceResponse.getResult()).isNotNull();
We should validate the response value is equal to an expected value, not just not null. Especially since I believe the result will always be `0x` or an error instead of null. Should add a helper to `ContractCallResponse` to convert from string hex to the target type.

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        assertThat(identifierResponse.getResult()).isNotNull();
Should add one negative test like unknown contract method.

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        verifyContractCallSimulations();
Not sure the value of a `verifyContractSimulations()` calling a similarly named `verifyContractCallSimulations()`. Can just directly put the logic in this `verifyContractSimulations()`.

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    public void verifyContractSimulations() {
Again, not sure why using simulations terminology. Let's use "contract call" to be consistent with the API endpoint.
```suggestion
    @Then("I call the contract via the mirror node REST API")
    public void restContractCall() {
```

2023-01-24 01:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +        And the mirror node Web3 REST API should execute simulations
```suggestion
        And I call the contract via the mirror node REST API
```

2023-01-24 12:16 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    private <T> T callWeb3RestEndpointPost(String uri, Class<T> classType, ContractCallRequest contractCallRequest) {
I added a separate method and separate properties for the Web3 REST API for the following reasons:

1. In the `Java Web3 REST` points we would be executing `POST` requests vs the `GET` for the `Javascript rest module`
2. When testing in a local environment using `local-node`, the `web3` and `rest` containers have different ports, hence you can't use the same url and port for the two containers. Having the same url would make it harder to adapt for local tests - you should setup a different web3 client manually every time, which should make POST requests and use a different url.

2023-01-24 19:35 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    private <T> T callWeb3RestEndpointPost(String uri, Class<T> classType, ContractCallRequest contractCallRequest) {
1. My concern was mainly for having a separate method for calling Web3 REST endpoints, which I renamed to `callPostRestEndpoint`. It has to construct a different `webClient`, that makes `POST` requests and sends request body. So, I believe we should keep this separate method.
2. I like option 2a, we should investigate whether it would work. It would be the cleanest solution. As for now, I have deleted the duplicated Web3 REST URL as we had it as an additional property.

2023-01-24 20:13 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +    private <T> T callWeb3RestEndpointPost(String uri, Class<T> classType, ContractCallRequest contractCallRequest) {
Oh, for 1) you meant specifically for having a method for POST. Yes, that's fine. I thought we were talking more about the separate URLs.

2023-01-25 15:50 UTC, steven-sheehy requested changes

2023-01-25 15:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +    private T result;
Remove unused generic. The result is always a String. Leaving it could result in code smells.

```suggestion
public class ContractCallResponse {
    private String result;
```

2023-01-25 15:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        }
This doesn't fail if no exception.
```suggestion
        assertThatThrownBy(() -> mirrorClient.contractsCall(WRONG_SELECTOR, contractId.toSolidityAddress(), contractClient.getClientAddress())).getCause().isInstanceOf(SomeException.class).hasMessageContaining("400 Bad Request from POST");
```

2023-01-25 15:50 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    }
Move these to `ContractCallResponse` as helpers like `contractCallResponse.getResultAsBigInteger()`, etc.

2023-01-26 16:11 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +    }
Not sure why you moved it but kept it as static. That negates the benefit of moving it and avoid having to pass in an object. But let's just keep it for now to avoid churn.

2023-01-26 16:11 UTC, steven-sheehy approved these changes
LGTM

2023-01-26 16:12 UTC, merged