Аdd evm entry point on mirror-node side
hashgraph/hedera-mirror-node pull request #4895
Opened 2022-11-16 12:51 UTC by IvanKavaldzhiev

**Description**:

Define `MirrorEvmTxProcessor` class that will be used by the ethereum services for transaction simulations. It would be used as an entry point to the `hedera-evm-api` library.

**Related issue(s)**: #4894 

Fixes #4894 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-11-16 13:01 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/models/MirrorEvmAccount.java
> +}
Default `EvmAccount` implementation could be placed inside the `hedera-evm-api` library.

2022-11-16 13:01 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorOperationTracer.java
> +public class MirrorOperationTracer implements HederaEvmOperationTracer {
Default `HederaEvmOperationTracer` implementation could be placed inside the `hedera-evm-api` library.

2022-11-16 22:01 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessor.java
> +
Needs license.

2022-11-16 22:02 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorOperationTracer.java
> +
License

2022-11-16 22:03 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/models/MirrorEvmAccount.java
> +
Needs license.

2022-11-16 22:03 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/exception/EvmException.java
> +
Needs license.

2022-11-16 22:03 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/exception/InvalidTransactionException.java
> +
Needs license.

2022-11-16 22:04 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessorTest.java
> +
Needs license.

2022-11-17 04:37 UTC, steven-sheehy requested changes

2022-11-17 04:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessor.java
> +public class MirrorEvmTxProcessor extends HederaEvmTxProcessor {
q: How will this class eventually get constructed? Will it be a Spring bean or it needs to be created manually through some EVM hook? It has a lot of dependencies to provide.

2022-11-17 04:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessorTest.java
> +        assertEquals(receiver.getAddress(), result.getRecipient().get());
In general, we prefer chaining assertj assertions on mirror node.
```suggestion
        assertThat(result)
            .isNotNull()
            .returns(true, HederaEvmTransactionProcessingResult::isSuccessful)
            .returns(receiver.getAddress(), r -> r.getRecipient().get());
```

2022-11-17 04:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessorTest.java
> +                                gasCalculator, evm30, true, List.of(), 1));
If any of these are the production values that will be duplicated during construction of `MirrorEvmTxProcessor` outside of tests then it might make sense to move inside MirrorEvmTxProcessor's constructor.

2022-11-17 04:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessor.java
> +        validateTrue(code != null || value > 0, ResponseCodeEnum.INVALID_ETHEREUM_TRANSACTION);
Not sure why the error message should be specific to ethereum transaction? Perhaps `CONTRACT_BYTECODE_EMPTY` or some other error?

2022-11-17 04:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorEvmTxProcessor.java
> +                .code(code == null ? Code.EMPTY : code)
Why can't `codeCache.getIfPresent` just always return `Code.EMPTY` instead of handling nulls in multiple places?

2022-11-24 22:06 UTC, steven-sheehy requested changes

2022-11-24 22:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/MirrorOperationTracer.java
> +public class MirrorOperationTracer implements HederaEvmOperationTracer {
It says done but this class is still present. Should it be deleted?

2022-11-24 22:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/models/MirrorEvmAccount.java
> +}
It says done but this class is still present. Should it be deleted?

2022-11-25 15:05 UTC, steven-sheehy approved these changes
LGTM

2022-11-25 15:07 UTC, merged