adding flux config for staging-lg mirrornode deployment
hashgraph/hedera-mirror-node pull request #4897
Opened 2022-11-16 19:40 UTC by tolorukooba

Signed-off-by: tolorukooba <teslim.olorukooba@swirldslabs.com>

This PR adds flux config for staging-lg mirrornode kube deployment.

2022-11-16 21:22 UTC, edwin-greene approved these changes
Looks good to me.

2022-11-16 23:27 UTC, steven-sheehy requested changes

2022-11-16 23:27 UTC, steven-sheehy commented on clusters/preprod/staging-lg/sealed-secret.yaml
> +    values.yaml: AgCYjhdo1ae33nTbCwlhfCMG0a9Ad0xaUPINa6mIIHruF8T80WvKzlLXfbbBJEgOEZRzQrrsS7Do/34eROwU5oSqDtzozuPciGSAcUGLiGOS6UVi83pqoNVMQog4tVhmffGMoDGCiLx+pSA+nV/i+KmDjNxvYG/SGXshCDVbmk9O389j1BLNpo
The bucket name should have an `s` at the end.

2022-11-16 23:27 UTC, steven-sheehy commented on clusters/preprod/staging-lg/sealed-secret.yaml
> +    values.yaml: AgCYjhdo1ae33nTbCwlhfCMG0a9Ad0xaUPINa6mIIHruF8T80WvKzlLXfbbBJEgOEZRzQrrsS7Do/34eROwU5oSqDtzozuPciGSAcUGLiGOS6UVi83pqoNVMQog4tVhmffGMoDGCiLx+pSA+nV/i+KmDjNxvYG/SGXshCDVbmk9O389j1BLNpo
Need to run init SQL and create users and updated secret.

2022-11-17 14:35 UTC, mgoelswirlds approved these changes

2022-11-17 20:27 UTC, tolorukooba commented on clusters/preprod/staging-lg/sealed-secret.yaml
> +    values.yaml: AgCYjhdo1ae33nTbCwlhfCMG0a9Ad0xaUPINa6mIIHruF8T80WvKzlLXfbbBJEgOEZRzQrrsS7Do/34eROwU5oSqDtzozuPciGSAcUGLiGOS6UVi83pqoNVMQog4tVhmffGMoDGCiLx+pSA+nV/i+KmDjNxvYG/SGXshCDVbmk9O389j1BLNpo
@steven-sheehy fixed!

2022-11-17 20:27 UTC, tolorukooba commented on clusters/preprod/staging-lg/sealed-secret.yaml
> +    values.yaml: AgCYjhdo1ae33nTbCwlhfCMG0a9Ad0xaUPINa6mIIHruF8T80WvKzlLXfbbBJEgOEZRzQrrsS7Do/34eROwU5oSqDtzozuPciGSAcUGLiGOS6UVi83pqoNVMQog4tVhmffGMoDGCiLx+pSA+nV/i+KmDjNxvYG/SGXshCDVbmk9O389j1BLNpo
done!

2022-11-17 20:49 UTC, steven-sheehy approved these changes
LGTM

2022-11-17 21:47 UTC, merged