Add AccountStakingRewardsTransfer to Monitor dashboard
hashgraph/hedera-mirror-node pull request #4913
Opened 2022-11-18 19:57 UTC by MarcKriguerAtHedera

Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:
* Add (account) staking rewards transfer API to monitor dashboard
* Add propertiy to control which account id is used for the above test

**Related issue(s)**:

Fixes #4853

**Notes for reviewer**:
You will need to set the property `account.stakingTokenRewardAccountId` to specify the accountId to use; unless you have a local database with a "staking_reward_transfer` table specified, expect a 404 HTTP result (and a red test circle).  Or just wait until testnet (or your network of choice) has [PR 4852](https://github.com/hashgraph/hedera-mirror-node/pull/4852) (Milestone 0.70.0) deployed to it.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (api monitoring)

2022-11-18 20:57 UTC, xin-hedera requested changes

2022-11-18 20:57 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +const stakingTokenRewardAccountId = config[resource].stakingTokenRewardAccountId;
```suggestion
const stakingRewardAccountId = config[resource].stakingRewardAccountId;
```

2022-11-18 20:57 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  }
should check if `stakingRewardAccountId` is set in runTests instead here. only add `runTests(getAccountStakingRewards)` to the promise array when it's configured.

2022-11-18 20:57 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    return {url, ...result};
should not set `passed = true` if there's no reward transfers for the configured account.

also should combine all the checks

2022-11-18 20:57 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +const stakingTokenRewardAccountId = config[resource].stakingTokenRewardAccountId;
add `"stakingRewardAccountId": null` to `default.serverlist.json`, under `"account"`

2022-11-19 00:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +const stakingTokenRewardAccountId = config[resource].stakingTokenRewardAccountId;
Done.  (Renamed throughout the file.)

2022-11-19 00:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  }
Done.  Copied the existing style of the other "conditional" test.

2022-11-19 00:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +    return {url, ...result};
Done.  Makes sense; the API call returns a 200 (not a 404) and an empty array, but the test definitely can call it a failure if the configured account has no previous reward.

2022-11-19 00:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +const stakingTokenRewardAccountId = config[resource].stakingTokenRewardAccountId;
Done.

2022-11-19 00:53 UTC, xin-hedera requested changes

2022-11-19 00:53 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const stakingRewardsPath = (tokenId) => `${accountsPath}/${stakingRewardAccountId}/rewards`;
this should be just a string instead of an arrow function
```suggestion
  const stakingRewardsPath = `${accountsPath}/${stakingRewardAccountId}/rewards`;
```

2022-11-19 01:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const stakingRewardsPath = (tokenId) => `${accountsPath}/${stakingRewardAccountId}/rewards`;
Done.

2022-11-19 02:11 UTC, xin-hedera approved these changes
LGTM

2022-11-21 18:03 UTC, edwin-greene approved these changes
Looks good

2022-11-21 19:54 UTC, steven-sheehy approved these changes

2022-11-21 19:55 UTC, merged