Set ExpiryTimestamp based on CreatedTimestamp and AutoRenewPeriod
hashgraph/hedera-mirror-node pull request #4914
Opened 2022-11-18 20:41 UTC by edwin-greene

Signed-off-by: Edwin Greene <edwin.greene@swirldslabs.com>

**Description**:
If the `expiry_timestamp`/`expiration_timestamp` is null, set it based off of the `createdTimestamp` and the `autoRenewPeriod`.

**Related issue(s)**:

Fixes #4888

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-11-18 21:12 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/tokens.test.js
> -    expiry_timestamp: 1594431063696143000,
The `expiry_timestamp` here was represented as a number, while the `expiry_timestamp` in other tests was represented as a String. The new method always returns a String.

2022-11-18 22:43 UTC, steven-sheehy requested changes

2022-11-18 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
I don't like the mixing of string `createdTimestamp` with numeric `autoRenewPeriod`. I think we should pass in `createdTimestamp` as bigint from db, multiply autoRenewPeriod by 10^9 and add `consensusTimestamp` to it. Then use nsToSecNs to convert that to string.

2022-11-18 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/utils.test.js
> +    [autoRenewPeriod, '1668785933012', undefined, '1676785934012'],
We should use more real values for these tests like your `autoRenewPeriod` const. The createdTimestamp should always bet at least 10 digits since 9 are for nanos. The result should always have a `nanos.seconds`.

2022-11-18 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/tokens.test.js
> -    expiry_timestamp: 1594431063696143000,
We should update at least one existing token/{id} spec to populate a calculated expiry.

2022-11-18 22:43 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/all-params.json
> +        "expiration_timestamp": "2487654.111123456",
Once you fix your calculation it should be `989154.111123456`

2022-11-21 22:09 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/tokens.test.js
> -    expiry_timestamp: 1594431063696143000,
Great idea. I modified `__tests__/specs/tokens/{id}/no-params.json` to include a calculated expiry timestamp

2022-11-21 22:09 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +
Thanks for spotting this, I have removed it.

2022-11-21 22:10 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/utils.test.js
> +  const autoRenewPeriod = 8000001; // ~92 days as seconds
Thanks I have renamed it.

2022-11-21 22:10 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
Sounds great. I have made those changes.

2022-11-21 22:11 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/utils.test.js
> +    [autoRenewPeriod, '1668785933012', undefined, '1676785934012'],
I have added another real value test and removed an unnecessary one.

2022-11-21 22:11 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/contracts/all-params.json
> +        "expiration_timestamp": "2487654.111123456",
Thanks for doing the math, I have found the mistake and fixed it.

2022-11-21 22:17 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +    ? nsToSecNs(BigInt(createdTimestamp) + BigInt(autoRenewPeriod * constants.AUTO_RENEW_PERIOD_MULTIPLE))
The database values are already bigint so just need to store the constant as BigInt as well and can avoid the extra conversion.
```suggestion
    ? nsToSecNs(createdTimestamp + autoRenewPeriod * constants.AUTO_RENEW_PERIOD_MULTIPLE)
```

2022-11-22 15:03 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +    ? nsToSecNs(BigInt(createdTimestamp) + BigInt(autoRenewPeriod * constants.AUTO_RENEW_PERIOD_MULTIPLE))
- I found that this part throws an error (even with the constant being a `BigInt`):  
   `autoRenewPeriod * constants.AUTO_RENEW_PERIOD_MULTIPLE` -> `Cannot mix BigInt and other types, use explicit conversions`
    The error can be resolved by casting `autoRenewPeriod` as a `BigInt`. 

- There are many spec tests that have a created timestamp of `987654111123456`, which doesn't enter the function as a BigInt, so it seems that some created timestamps need to be converted to `BigInt`. I've added this timestamp to the unit test.

2022-11-22 15:32 UTC, steven-sheehy approved these changes

2022-11-22 16:16 UTC, merged

2022-12-19 12:32 UTC, RAMTO commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
Guys, this is a breaking change for us (Heliswap DEX)
We are relying on a specific response format, and by changing the type of this property is causing an error on our side.
I guess the mirror node is used by a lot of users and apps, and this kind of changes need to be backward compatible and communicated very well before deploying...

2022-12-19 15:32 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
@RAMTO It's not clear what breaking change you're referring to. This particular comment is not a breaking change but an internal implementation detail that is discussing at what layer to convert from DB bigint to string for the REST JSON response. The REST response did not change nor did the database schema (not that we provide any guarantee on schema changes).

The only change that might be construed as "breaking" is that we don't return `null` in more cases now and populate it with the calculation above. Can you clarify?

2022-12-19 15:39 UTC, RAMTO commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
@steven-sheehy 
I am talking about `expiry_timestamp` property going from `number` to `string` format.
At Heliswap DEX, we are getting token data from the mirror node and parsing the responce.
Currently expecting this prop to be `number` as is at `https://mainnet-public.mirrornode.hedera.com/`
Although I noticed that `https://testnet.mirrornode.hedera.com/` is returning this props as `string`.
I understand that for the sake of consistency it's good to be a `string`, although this could cause a lot issues for dapps using the mirror node and expecting the prop to be a `number`.

2022-12-19 19:19 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
Ah, you meant specifically for `/api/v1/tokens/{id}`. The other APIs with expiration timestamp were always string. That was not an intentional change and thanks for bringing it to our attention before it made it to mainnet. We will revert the change from string to number for this API via https://github.com/hashgraph/hedera-mirror-node/issues/5080.

2022-12-20 05:59 UTC, RAMTO commented on hedera-mirror-rest/utils.js
> +    ? math.add(createdTimestamp, math.multiply(autoRenewPeriod, 1000)).toString()
@steven-sheehy Thanks, appreciate it!