Add Java service implementation for eth_call request
hashgraph/hedera-mirror-node pull request #4946
Opened 2022-11-25 11:38 UTC by nikolovyanko

Signed-off-by: Yanko Nikolov <nikolovqnko@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #4463 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-11-25 15:09 UTC, steven-sheehy commented
Can we close https://github.com/hashgraph/hedera-mirror-node/pull/4633 and delete its branch in favor of this PR?

2022-12-07 16:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +    public MirrorEvmTxProcessorFacadeImpl(
Probably we can make all arguments `final`

2022-12-07 16:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/PricesAndFeesImpl.java
> +        return 1000L;
We can add comment like:
`//FEATURE WORK - precise gas price calculation to be provided with eth_estimateGas implementation`

2022-12-07 16:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/PricesAndFeesImpl.java
> +    public long currentGasPrice(Instant now, HederaFunctionality function) {
We can make arguments `final`

2022-12-07 16:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        final var status = getStatusOrDefault(processingResult);
I think we can get rid of `ResponseCodeUtil` to reduce `mirror-node` complexity and we can directly check whether the `result.isSuccessful` - if not - we throw an `InvalidTransactionException`, without the need of matching specific error response code.

2022-12-08 06:32 UTC, Nana-EC reviewed
Some suggestions

2022-12-08 06:32 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        if (request.getValue() > 0 && request.getFrom() == null) {
Can we move these lines into `ContractCallRequest.isValidValueTransfer()`
```suggestion
        if (!request.isValidValueTransfer())
```

2022-12-08 06:32 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        return processResult.getOutput().toHexString();
Q: is there a chance for `processResult.getOutput()` to be null?
Is output always in hex form?
If so move that casting into the `getOutput()` setting.

2022-12-08 17:47 UTC, steven-sheehy requested changes

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +    }
Use validation [groups](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_requesting_groups) for conditional validations. This avoid having to write conditional validation logic and continue to depend upon annotations. It also provides better error messages to clients since it does all validation at once and returns all errors instead of requiring separate requests to discover the conditional logic.

```java
    @Hex(minLength = ADDRESS_LENGTH, maxLength = ADDRESS_LENGTH)
    @NotNull(groups = TransferCheck.class)
    private String from;

    @Min(0)
    @Min(value = 1, groups = TransferCheck.class)
    private long value;
```
```java
public interface TransferCheck {
}
```

Have to switch controller from `@Valid` to the below to make it work:
```java
@Validated({Default.class, TransferCheck.class})
```

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallResponse.java
> +    }
I don't think this method provides any value over just calling the record-generated constructor.

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int expirationCacheTime = 600;
It might be a change upstream, but can we use `Duration` to model time-based properties`? It allows our config to accept variable units like `5m` or `600s`. It also makes it clear what unit this integer is in. Internally you can convert to integer to send to the library.

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/PricesAndFeesImpl.java
> +@NoArgsConstructor
nit: Can remove since Java provides a no-arg constructor by default.

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +        return Address.wrap(Bytes.wrap(entity.map(Entity::getEvmAddress).orElse(new byte[0])));
Should use a constant with a readable name.

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            throw new InvalidTransactionException(INVALID_TRANSACTION);
Can we not provide more detail as to why the transaction is invalid?

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                mirrorEvmTxProcessor.execute(
Does this processor catch all exceptions and return a processingResult regardless or should this be wrapped in a try/catch?

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +                .isEqualTo(OK);
estimateGas=true should return NOT_IMPLEMENTED, right?

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +    void callSuccess(){
Need a test for invalid value transfer parameters like value > 0 and value = null.

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    private StaticBlockMetaSource blockMetaSource;
We need at least one integration test that invokes the actual EVM and doesn't mock anything out.

2022-12-08 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    void processCallSuccess() {
Needs negative tests.

2022-12-15 00:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
>          return errorResponse(parseValidationError(e));
Not completed. Need separate error items in the list.

2022-12-15 01:56 UTC, steven-sheehy requested changes
There's still outstanding from my previous round of feedback. I will be on vacation soon so if we'd like this in and have my sign off changes need to be implemented soon.

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/exception/ResponseCodeUtil.java
> +            } else if (HederaExceptionalHaltReason.INVALID_SOLIDITY_ADDRESS == haltReason) {
As codecov suggests, we're missing code coverage for these branches. Preferably in the service layer and not just util tests. But I'll take what I can get.

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        } catch (Exception e) {
This swallows the exception. Shouldn't this return some response to the user or at minimum log the error?

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    private ContractCallService contractCallService;
Take advantage of the existing `@RequiredArgsConstructor`:

```suggestion
    private final ContractCallService contractCallService;
```

2022-12-15 01:56 UTC, steven-sheehy commented on buildSrc/src/main/resources/suppressions.xml
> +        <cve>CVE-2021-37533</cve>
This is too broad of a suppression. If this is a false positive you should add the package and a note explaining why it's a false positive. If it's not a false positive and we are relying on a vulnerable Apache Commons Net library then we should not suppress it.

2022-12-15 01:56 UTC, steven-sheehy commented on buildSrc/src/main/resources/suppressions.xml
> +        <notes>hedera-evm-lib</notes>
Add a note about why we are suppressing this. Believe it's a false positive to due to confusing another library with the hedera evm library.

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    api("com.hedera.evm:hedera-evm") {
Why are we using api here? We should use `implementation` since web3 is not a library and shouldn't need to leak this dependency elsewhere.

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/pom.xml
> -            <artifactId>hedera-evm-api</artifactId>
Need to rebase as we've removed Maven.

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +                request.getData() != null
Need test for empty

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        log.warn("Generic error: {}", e.getMessage());
We should log at error for internal errors and print the stacktrace.
```suggestion
        log.error("Generic error: ", e);
```

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/exception/InvalidTransactionException.java
> +        return Bytes.of(detail.getBytes());
```suggestion
        return Bytes.of(detail.getBytes(StandardCharsets.UTF8));
```

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            throw new InvalidTransactionException(getStatusOrDefault(txnResult));
Needs a test case

2022-12-15 01:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            return emptyFailProcessingResponse();
Needs a test case

2022-12-15 11:22 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +@GroupSequenceProvider(TransferValidation.class)
I took this approach because with the suggested, otherwise valid case of a call with non-mandatory fields `from=null` and `value=0` fails validation `value field must be greater than or equal to 1`.

2022-12-15 11:51 UTC, nikolovyanko commented
> There's still outstanding items from my previous round of feedback. I will be on vacation soon so if we'd like this in and have my sign-off changes need to be implemented soon.

The implementation here was delayed due to a missing logic from the evm-module lib, that will be introduced with this [PR](https://github.com/hashgraph/hedera-services/pull/4477). Some of the  tests in `ContractCallServiceTest` fails as they expect these changes.

2022-12-15 11:59 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        } catch (Exception e) {
Not sure whether to wrap a potential NullPointer/InvalidArgument.. exceptions returned by the TxnProcessor in `InvalidTransactionException` or to just leave them to be catched by the `ContractController`'s `genericError`?

2022-12-15 12:32 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
>          return errorResponse(parseValidationError(e));
Doesn't `parseValidationError(WebExchangeBindException )` fit the requirements?

2022-12-15 14:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
>          return errorResponse(parseValidationError(e));
No, it returns a String. It should either return a `Collection<String>`, `List<ErrorMessage>` or the `GenericErrorResponse` with its internal list populated with multiple items.

2022-12-20 09:44 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        } catch (Exception e) {
The other 2 possibility  indicating: wrong input, insufficient account balance etc. are `IllegalStateException` and `IllegalArgumentException` everything else I think can be consider as a internal server error and can be be handled by:
https://github.com/hashgraph/hedera-mirror-node/blob/b786289a99fa9d38a65f370f74073035a177cb6e/hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java#L122

2022-12-21 04:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        } catch (Exception e) {
Then we should probably catch `IllegalStateException | IllegalArgumentException` and rethrow as `InvalidTransactionException` and not catch others.

2022-12-22 08:07 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
>      Mono<ContractCallResponse> call(@RequestBody @Valid ContractCallRequest request) {
Wondering whether a feature flag for the endpoint is needed? And if yes is an approach with different spring profiles suitable?

2022-12-22 17:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
>      Mono<ContractCallResponse> call(@RequestBody @Valid ContractCallRequest request) {
I'm not sure a feature flag is necessary since this module does nothing else besides the contract call at this point, especially after #5099. And we can disable this route via the kubernetes ingress, if needed.

2022-12-23 08:35 UTC, IvanKavaldzhiev approved these changes
LGTM! Once we get the latest `hedera-evm` artifact version providing some enhancements, `eth_call` should be working.

2023-01-10 01:18 UTC, steven-sheehy approved these changes
LGTM

2023-01-10 17:00 UTC, steven-sheehy approved these changes

2023-01-10 17:37 UTC, merged