04801 updating gcp marketplace version
hashgraph/hedera-mirror-node pull request #4962
Opened 2022-11-28 18:32 UTC by mgoelswirlds

**Description**:

Adding extra steps and workflow to perform GCP marketplace upgrade.

This PR does the following:
* Adds a new step to perform automatic GCP marketplace verification.
* Change documentation.
* Change release.sh

**Related issue(s)**:

Fixes # https://github.com/hashgraph/hedera-mirror-node/issues/4801

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-11-28 19:16 UTC, MarcKriguerAtHedera approved these changes
Looks but, except for what may or or may not be a conflict in timeout in release-production.yml file.

2022-11-28 19:16 UTC, MarcKriguerAtHedera commented on .github/workflows/release-production.yml
> +        timeout-minutes: 3
Not really sure if this matters, but line 113 indicates a 5 minute timeout, but line 114 indicates 3 minutes.  Should these be in alignment?

2022-11-28 19:43 UTC, steven-sheehy requested changes

2022-11-28 19:43 UTC, steven-sheehy commented on charts/marketplace/gcp/README.md
> +[Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) is used to manage the rest
REST is an acronym
```suggestion
[Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) is used to manage the REST
```

2022-11-28 19:43 UTC, steven-sheehy commented on charts/marketplace/gcp/schema.yaml
> +    title: gRPC Service type
```suggestion
    description: The REST API service type
    title: REST API Service type
```

2022-11-28 19:43 UTC, steven-sheehy commented on charts/hedera-mirror/Chart.yaml
> +    version: 10.0.3
Why this change? This will bump PostgreSQL to 15 which we have not tested against. I hope we didn't submit to marketplace with this.

2022-11-28 19:43 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +  install:
```suggestion
  marketplace:
    name: GCP Marketplace release & verification
```

2022-11-28 19:43 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +          fetch-depth: 0
A shallow clone should work the same here.
```suggestion
```

2022-11-28 19:43 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +
Since we're not doing a multi-arch build we don't need qemu or buildx. See release-integration.yml.

```suggestion
```

2022-11-28 19:43 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +        run:  cd ${HOME} && mkdir "bin" && export PATH=${HOME}/bin:$PATH && echo "Path is ${PATH}"
The path setup and echo is not really needed since we're executing mpdev via an absolute path, right? Also, if we're using absolute path we also don't need the bin folder so this entire step can be omitted and no mkdir is required. Change MPDEV="${HOME}/mpdev"

2022-11-28 19:43 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +        run: ${MPDEV} verify --deployer=gcr.io/mirror-node-public/hedera-mirror-node/deployer:${TAG} --parameters='{"rest.service.type":"ClusterIP", "grpc.service.type":"ClusterIP"}'
You should be able to omit the parameters since you set them as default in schema-test.yml, right?
```suggestion
        run: ${MPDEV} verify --deployer=gcr.io/mirror-node-public/hedera-mirror-node/deployer:${TAG}
```

2022-11-28 19:43 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +        run:  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl"
Darwin? You mean linux

2022-11-28 20:12 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +
I checked with Nathan, he just provided an example that happened to contain those lines. Those lines are not necessary and can be removed.

2022-11-28 20:12 UTC, mgoelswirlds commented on charts/hedera-mirror/Chart.yaml
> +    version: 10.0.3
I believe this was something, I changed initially to update to latest postgres,changing it now.
I believe we did not submit this to marketplace since we explicitly built only deployer and the postgres version we used was 14.5.0-debian-11-r34

2022-11-28 20:31 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +        timeout-minutes: 3
The timeout- minutes is for the task specifically. and the flag timeout is for cluster creation, which technically would amount to the same thing.

2022-11-28 20:33 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +        timeout-minutes: 3
I have changed both to be 3

2022-11-28 22:25 UTC, xin-hedera requested changes

2022-11-28 22:25 UTC, xin-hedera commented on .github/workflows/release-production.yml
> +        timeout-minutes: 3
prefer a job wide timeout instead putting it on a step. it's also possible the k3d doesn't hit the `--timeout 3m` while the step still takes more than 3 minutes.

2022-11-28 22:25 UTC, xin-hedera commented on charts/marketplace/gcp/release.sh
> +sed "-i .bak" "s/version: .*/version: ${target_tag}/" values.yaml
This would create backup file `values.yaml .bak`, note the space before the `.bak` suffix

```suggestion
sed -i.bak "s/version: .*/version: ${target_tag}/" values.yaml
```

2022-11-28 22:25 UTC, xin-hedera commented on charts/marketplace/gcp/schema-test.yaml
> +    default: "ClusterIP"
nit, can remove the quotes `""`, the other file `schema.yaml` doesn't have quotes btw.

2022-11-28 22:27 UTC, steven-sheehy requested changes

2022-11-28 22:27 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +        run:  MPDEV="${HOME}/mpdev"
I don't think this does anything. I meant set the env variable above in `env:`

2022-11-28 22:27 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +    name: GCP Marketplace release
Did you re-test this workflow with the recent changes made?

2022-11-29 00:19 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +        run:  MPDEV="${HOME}/mpdev"
Had to add back this step `      - name: Create bin
        run:  cd ${HOME} && mkdir "bin" && export PATH=${HOME}/bin:$PATH` since it is a needed step.

2022-11-29 00:20 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +        run:  MPDEV="${HOME}/mpdev"
I had to add back Had to add back this step :
```
    - name: Create bin
        run:  cd ${HOME} && mkdir "bin" && export PATH=${HOME}/bin:$PATH` 
```
since it is a needed step to have docker install mpdev at the right location and for us to use it later.

2022-11-29 00:21 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +    name: GCP Marketplace release
I have tested with these latest changes in a separate workflow file with hardcoding tag to 0.69.0
Since we are not checking in a tag ${GITHUB_REF#refs/*/v} does not give the correct result in this build.
So the flow works.

2022-11-29 00:27 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +        timeout-minutes: 3
This is the same thing in charts.yml. We might need to fix it both places. 
Also I agree that timeout flag doesn't work properly. I have experienced that during testing.

2022-11-29 04:18 UTC, steven-sheehy commented on .github/workflows/release-production.yml
> +        run:  MPDEV="${HOME}/mpdev"
It's only needed because you didn't set `MPDEV: "/home/runner/mpdev"` in `env` block like I had suggested in the original comment. But we can keep for now to avoid churn.

2022-11-29 16:16 UTC, mgoelswirlds commented on .github/workflows/release-production.yml
> +        timeout-minutes: 3
I have added job wide timeout.

2022-11-29 16:35 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-11-29 18:07 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-11-29 18:45 UTC, mgoelswirlds commented
@steven-sheehy and @xin-hedera  I had some unverified commits and hence it wouldn't let me merge. Could you please re-approve the PR.

2022-11-29 18:52 UTC, steven-sheehy approved these changes

2022-11-29 18:53 UTC, xin-hedera approved these changes

2022-11-29 19:02 UTC, merged