04776 use real time token balance in balances api
hashgraph/hedera-mirror-node pull request #4976
Opened 2022-11-30 18:29 UTC by edwin-greene

**Description**:
The Balances API will now use the token account table to obtain real time token balances when no timestamp parameter is present. 

**Related issue(s)**:

Fixes #4776 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-12-01 18:14 UTC, steven-sheehy submitted a review, later dismissed

2022-12-01 19:48 UTC, xin-hedera requested changes

2022-12-01 19:48 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +      limit ${tokenBalanceLimit.multipleAccounts}
should not show balance for those dissociated token account associations. this is to align with the token balance info from the account balance file. if an account dissociates itself from a token, in the next account balance file, the <account, token> entry will disappear.

2022-12-06 17:18 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +      limit ${tokenBalanceLimit.multipleAccounts}
Great input. I have updated the query to only get associated token accounts.

2022-12-08 15:37 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/balances/no-params.json
> +        "account_id": "0.15.01",
nit, here and every other place the account is in the form of `x.y.0z`

```suggestion
        "account_id": "0.15.1",
```

2022-12-08 15:38 UTC, xin-hedera approved these changes
LGTM

2022-12-08 17:49 UTC, steven-sheehy approved these changes

2022-12-08 18:28 UTC, merged