Add Alias support for HIP-583 CryptoCreate Transactions
hashgraph/hedera-mirror-node pull request #5007
Opened 2022-12-05 17:28 UTC by edwin-greene

Signed-off-by: Edwin Greene <edwin.greene@swirldslabs.com>

**Description**:

- Adds Alias support for CryptoCreate transactions per HIP-583.
- Replaces `InvalidSolidityAddress` with HIP-583's `TargetedAddress`.

**Related issue(s)**:

Fixes #4800 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-12-06 03:59 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +        if (key != null && key.length > 0) {
It shouldn't happen but defensively might be good to make sure the length is greater than a 20byte hex evmAddress

2022-12-06 04:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +        if (key != null && key.length > 0) {
This line is for a key and checking for 20 bytes length doesn't make sense.

2022-12-06 17:31 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +        if (key != null && key.length > 0) {
Hmm, the comment was for the `entity.setKey(aliasBytes);`
Not sure how it ended up a few lines down.

2022-12-06 17:32 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +        if (key != null && key.length > 0) {
There fixed it

2022-12-06 21:45 UTC, MarcKriguerAtHedera submitted a review, later dismissed
LGTM, but some changes (which appear to be autogenerated) have a few nits.

2022-12-06 21:45 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            // if transaction is neither a create/call and has no valid ContractFunctionResult then
nit: I would keep lines 86-87 as a single line.

2022-12-06 23:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            // if transaction is neither a create/call and has no valid ContractFunctionResult then
this looks like spotless auto format

2022-12-06 23:33 UTC, steven-sheehy requested changes

2022-12-06 23:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +                        ? transactionBody.getEvmAddress()
Prefer record

2022-12-06 23:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +            if (key == null || key.length == 0) {
I don't think we have to check key length here or below. If we have a `Key`, services would've validated it and we should use it.

2022-12-06 23:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                CryptoCreateTransactionBody.newBuilder()
We should set alias and evm record here since our general rule is to populate all fields by default. If we populate, we should omit from record though.

2022-12-06 23:35 UTC, xin-hedera requested changes

2022-12-06 23:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> -            entity.setEvmAddress(Utility.aliasToEvmAddress(alias));
shouldn't drop the alias to evm address logic. we need it to be backward compatible so accounts created with EC key alias via HIP-32 before services externalize it in the record get evm address populated

2022-12-06 23:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +            if (key == null || key.length == 0) {
use `ArrayUtils.isEmpty` / `ArrayUtils.isNotEmpty`

2022-12-08 18:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            // if transaction is neither a create/call and has no valid ContractFunctionResult then
I've removed the spotless formatting, so this change has been reverted.

2022-12-08 18:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            // will be
I've removed the spotless formatting, so this change has been reverted.

2022-12-08 18:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        log.warn(
I've removed the spotless formatting. As well, in the meantime main was updated to remove the Invalid Solidity case that was the cause of this change, so there are no changes to this file.

2022-12-08 18:43 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> -            entity.setEvmAddress(Utility.aliasToEvmAddress(alias));
Thanks I have added `Utility.aliasToEvmAddress(alias)` back on line 88.

2022-12-08 18:43 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +                        ? transactionBody.getEvmAddress()
Fixed.

2022-12-08 18:44 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                CryptoCreateTransactionBody.newBuilder()
Sounds good I have added them to `cryptoCreate()` in RecordItemBuilder.

2022-12-08 18:44 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> -            entity.setEvmAddress(Utility.aliasToEvmAddress(alias));
Thanks I have added it back in on line 88.

2022-12-08 18:45 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +            if (key == null || key.length == 0) {
Great thanks, I have switched to using ArrayUtils.

2022-12-08 18:52 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +            if (key == null || key.length == 0) {
I am working under the assumption that a key could possibly be an empty bytestring, and in that circumstance a non-empty alias would be set as the key. Are those assumptions correct? 

In testing, `transactionBody.hasKey()` returns true for an empty ByteString; then when attempting to simulate a key not present, I am unable to set the key to null without throwing an exception. `Key.getDefaultInstance()` returns an empty ByteString, so it seemed like the best way to test if a key was present and not empty. 

At the moment, I've change it like so to determine if a key is present and not empty: 

```
        var key = transactionBody.hasKey() ? transactionBody.getKey().toByteArray() : null;
        boolean emptyKey = ArrayUtils.isEmpty(key);
```

But, maybe in real practice `transactionBody.hasKey()` can be trusted to always have a key that is not empty, or the empty key should be used in place of the non-empty alias?

2022-12-09 20:04 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java
> -                .satisfies(c -> assertThat(c.getKey()).isNotEmpty())
Note: It's now possible for the key to be null.(if a key is empty and an alias is less than 20 bytes in length).

2022-12-09 20:06 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +                entity.setKey(aliasBytes);
Thanks I have added this check, if the alias is not greater than 20 bytes the key will not be set.

2022-12-09 21:06 UTC, steven-sheehy approved these changes

2022-12-09 21:16 UTC, xin-hedera approved these changes
LGTM

2022-12-09 21:24 UTC, merged