Add a helm release health indicator to monitor
hashgraph/hedera-mirror-node pull request #5008
Opened 2022-12-05 21:31 UTC by xin-hedera

**Description**:

This PR adds a helm release health indicator to monitor

- Add a conditional health indicator bean to report helmrelease health
- Cache the health info for 30s by default
- Only include the helmrelease health indicator in health/cluster group when `kubernetes` profile is active

**Related issue(s)**:

Fixes #4770 

**Notes for reviewer**:

Tested with a helm release installed by FluxCD

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-12-05 21:34 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HelmReleaseHealthIndicator.java
> +                .cacheInvalidateIf(v -> false)
cache the release name once `onNext`, can't use the `cache()` method since it caches `next`, `error`, and `completion` signals

2022-12-06 00:32 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HelmReleaseHealthIndicator.java
> +        var labels = client.pods().withName(hostname).get().getMetadata().getLabels();
logic borrowed from `Fabric8PodUtils.currentPod()`. Don't want to use the utility method since it depends on many other prerequisites, which make the mock test cases brittle to set up.

2022-12-06 00:34 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HelmReleaseHealthProperties.java
> +    private Duration cacheExpiry = Duration.ofSeconds(30);
main purpose of the expiry property is we can set it to a small value in test cases

2022-12-06 05:01 UTC, steven-sheehy requested changes

2022-12-06 16:35 UTC, steven-sheehy approved these changes
LGTM

2022-12-06 17:01 UTC, edwin-greene approved these changes
Looks good!

2022-12-06 17:06 UTC, merged