Add testkube and test resources to integration and mainnet-staging
hashgraph/hedera-mirror-node pull request #5054
Opened 2022-12-15 20:21 UTC by xin-hedera

**Description**:

This PR adds support of testkube to our flux CD deployment

- Add common testkube kustomization
- Add testkube helm repository and helm release
- Add a k6 custom testkube executor to support test artifact upload
- Add rest k6 testkube test and testsuite
- Enable testkube for preprod integration and mainnet-staging
- Set preprod integration k6 rest test suite to run daily 6AM UTC  

**Related issue(s)**:

Relates to #3099 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-12-15 20:23 UTC, xin-hedera commented on clusters/mainnet-staging-na/testkube/sealed-secret.yaml
> +    values.yaml: AgCUEOqy696dgbXlxPeaTP2c5CW4LnUn1qQYmIDj/NL5qY2qfqZq83W9UxZQtMkl1k3edk62VSPmCWasTgthP5REeeP3NnCYB+B8NC81YlIyOlknd6xl9hLDOxkkWN/wfkYGml11hv+RmQQkQvDQ5klL71Scf6ggjVPQLMV+VbxAYYPEePpjFc
the values.yaml sets `testkube-api.minio.minioRootPassword` and `testkube-api.storage.accessKey`

2022-12-15 20:25 UTC, xin-hedera commented on clusters/testkube/k6-test-suite.yaml
> +        value: http://{release}-rest.{namespace}.svc.cluster.local
just a template, the testkube kustomization for a specific cluster and helmrelease needs to patch it

2022-12-15 20:26 UTC, xin-hedera commented on clusters/testkube/k6-test-suite.yaml
> +        name: BASE_URL
the name repeats it self, this is just the testkube schema...

2022-12-15 20:26 UTC, xin-hedera commented on clusters/testkube/k6-test-suite.yaml
> +        duration: 600000
in `millis`

2022-12-15 20:27 UTC, xin-hedera commented on clusters/testkube/sealed-secret.yaml
> +    values.yaml: ""
actual encrypted data gets patched in cluster's kustomization config

2022-12-15 20:37 UTC, xin-hedera commented on clusters/testkube/helmrelease.yaml
> +      namespace: previewnet
perhaps should remove it or if we want to depend on the hedera-mirror helmrelease, need to patch the namespace accordingly

2022-12-15 23:53 UTC, xin-hedera commented on clusters/testkube/k6-test.yaml
> +      - /data/repo/hedera-mirror-test/k6/src/rest/apis.js
testkube convention, git repo is cloned to `/data/repo`

2022-12-15 23:54 UTC, xin-hedera commented on clusters/testkube/k6-test.yaml
> +  type: k6-custom/script
the type matches the one registered in our `k6-custom-executor`

2022-12-15 23:58 UTC, steven-sheehy requested changes

2022-12-15 23:58 UTC, steven-sheehy commented on clusters/testkube/helmrelease.yaml
> +      namespace: previewnet
Remove the dependsOn. The installation of testkube does not depend upon any particular namespace, only the execution of the test suites.

2022-12-15 23:58 UTC, steven-sheehy commented on clusters/testkube/helmrelease.yaml
> +      name: mirror
Would be better to name the secret after its corresponding helmrelease so `testkube`. Have to re-generate the secret though since name changed.

2022-12-15 23:58 UTC, steven-sheehy commented on clusters/testkube/sealed-secret.yaml
> +    values.yaml: ""
Why do we even need this file then? Just omit it in base and only apply the cluster specific sealed-secret. Basically delete this then move from patchesStrategicMerge to resources.

2022-12-16 14:51 UTC, steven-sheehy commented on clusters/testkube/sealed-secret.yaml
> +    values.yaml: ""
The base and the namespace specific get merged together by kustomize before applying to cluster.

2022-12-19 16:31 UTC, xin-hedera commented on clusters/base/testkube/base/helmrelease.yaml
> +          tag: RELEASE.2022-12-07T00-56-37Z
the `latest` minio image doesn't work, simply can't login. was lucky that when I started testing testkube, the `latest` tag is the one above which works flawlessly

2022-12-19 16:32 UTC, xin-hedera commented on clusters/base/testkube/base/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
need the `kustomization.yaml` file in both `testkube/base` and `testkube/extras` per kustomize requirement to include a directory in the resources section

2022-12-19 16:33 UTC, xin-hedera commented on clusters/base/testkube/extras/test-suite-rest.yaml
> +        value: "500"
reduce it from 1500 to 500 until #5019 is closed

2022-12-19 16:36 UTC, xin-hedera commented on clusters/preprod/testkube/base.yaml
> +  wait: true
`wait=true` and `timeout` to enable health checking for all the reconciled resources, per fluxcd kustomization doc

2023-01-06 22:03 UTC, xin-hedera commented on clusters/mainnet-staging-na/common/helmrelease.yaml
> +          namespace: mainnet
once mainnet-staging upgrade to chart version 0.72, the testkube resources will get created

2023-01-06 22:09 UTC, edwin-greene approved these changes
Looks good to me.

2023-01-09 20:27 UTC, merged