Changing the type for expiry_timestamp back to a number
hashgraph/hedera-mirror-node pull request #5083
Opened 2022-12-19 21:20 UTC by mgoelswirlds

**Description**:

Fixing accidental changes from the  PR https://github.com/hashgraph/hedera-mirror-node/pull/4914
Fixing a bug that the actual type in the response mismatches what's defined in our our openapi spec prior to 0.70.0.

This PR modifies 
* Changes the type expiry_timestamp back to a number
* Fixes the openapi spec to change the return type to a number for expiry_timestamp.

**Related issue(s)**:
Fixes #5080

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-12-19 22:35 UTC, xin-hedera approved these changes
LGTM

2022-12-19 22:36 UTC, steven-sheehy requested changes

2022-12-19 22:36 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/no-params.json
> +    "expiry_timestamp": 1241567889000000002,
Let's also update another spec to have a non-calculated `expiry_timestamp`

2022-12-19 22:36 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: null
Should provide a valid populated example

2022-12-19 23:18 UTC, steven-sheehy approved these changes
LGTM

2022-12-20 00:04 UTC, xin-hedera approved these changes

2022-12-20 00:15 UTC, merged