**Description**:
hashgraph/hedera-mirror-node pull request #5099
Opened 2022-12-20 20:51 UTC by jnels124

remove JsonRPC controller logic from web3 module

**Related issue(s)**:

Fixes #4966

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-12-21 04:34 UTC, steven-sheehy commented on hedera-mirror-web3/postman.json
> -                {
Chart workflow is failing since it's using `main` to pull `postman.json` to run. Need to enhance web3 chart to be similar to rosetta chart and take in a custom `test.git.repository` and `test.git.branch`.

2022-12-21 15:18 UTC, jnels124 commented on hedera-mirror-web3/postman.json
> -                {
thank you. Saved me some digging time.

2022-12-21 16:23 UTC, xin-hedera commented on hedera-mirror-web3/postman.json
> -                {
there are other changes needed to chart install pass. can check these out in the rosetta chart for reference

- https://github.com/hashgraph/hedera-mirror-node/blob/3df2fce36a15c0aea19450229caa1eb9ddac279b/charts/hedera-mirror-rosetta/values.yaml#L234-L236
- https://github.com/hashgraph/hedera-mirror-node/blob/3df2fce36a15c0aea19450229caa1eb9ddac279b/charts/hedera-mirror-rosetta/templates/tests/pod.yaml#L16-L20

2022-12-21 21:24 UTC, steven-sheehy requested changes

2022-12-21 21:24 UTC, steven-sheehy commented on charts/hedera-mirror/templates/NOTES.txt
> -  curl -sL -H "Content-Type: application/json" -X POST -d '{"id": 1, "jsonrpc": "2.0", "method": "eth_blockNumber"}' "http://${WEB3_IP:-127.0.0.1}:{{.Values.web3.service.port}}/web3/v1"
Should keep this and convert it to show contract call example.

2022-12-21 21:24 UTC, steven-sheehy commented on charts/README.md
> -To access the Web3 API:
Should keep this section and convert to show contract call example.

2022-12-21 21:24 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/Web3ServiceFactory.java
> -    private final Map<String, Web3Service<?, ?>> services;
Also delete `com.hedera.mirror.web3.service.eth` package

2022-12-21 21:26 UTC, xin-hedera submitted a review, later dismissed
LGTM. just a nit

2022-12-21 21:26 UTC, xin-hedera commented on docs/installation.md
> +c.h.m.w.config.LoggingFilter /10.0.0.43 POST http://localhost:8545/api/v1/contracts/call in 8 ms: 200 OK
nit, contracts call is not yet implemented, perhaps just remove this line

2022-12-22 16:23 UTC, xin-hedera commented on docs/installation.md
> +c.h.m.w.config.LoggingFilter /10.0.0.43 POST http://localhost:8545/api/v1/contracts/call in 8 ms: 200 OK
nvm, let's add contracts/call everywhere per Steven's suggestion so it's consistent.

2022-12-22 18:03 UTC, steven-sheehy commented on charts/hedera-mirror/templates/NOTES.txt
> +To access the Web3 API(Currently unimplemented and will return 501 status):
No need for this as it will be implemented soon and we will forget to remove it. Technically the curl command will fail anyway since the input will vary per environment.

2022-12-22 18:34 UTC, jnels124 commented on charts/hedera-mirror/templates/NOTES.txt
> +To access the Web3 API(Currently unimplemented and will return 501 status):
fixed

2022-12-22 18:35 UTC, jnels124 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/Web3ServiceFactory.java
> -    private final Map<String, Web3Service<?, ?>> services;
done

2022-12-22 18:35 UTC, jnels124 commented on charts/README.md
> -To access the Web3 API:
done

2022-12-22 18:36 UTC, steven-sheehy commented on charts/README.md
> -To access the Web3 API:
Are you sure?

2022-12-22 18:39 UTC, jnels124 commented on charts/README.md
> -To access the Web3 API:
now I am :)

2022-12-22 18:40 UTC, jnels124 commented on charts/hedera-mirror/templates/NOTES.txt
> -  curl -sL -H "Content-Type: application/json" -X POST -d '{"id": 1, "jsonrpc": "2.0", "method": "eth_blockNumber"}' "http://${WEB3_IP:-127.0.0.1}:{{.Values.web3.service.port}}/web3/v1"
done

2022-12-22 18:40 UTC, jnels124 commented on hedera-mirror-web3/postman.json
> -                {
done

2022-12-22 18:41 UTC, steven-sheehy approved these changes
LGTM

2022-12-22 18:47 UTC, xin-hedera approved these changes

2022-12-22 19:43 UTC, merged