Adding a few missing rest endpoints to k6 tests.
hashgraph/hedera-mirror-node pull request #5103
Opened 2022-12-20 21:58 UTC by mgoelswirlds

**Description**:
Adding the following missing rest endpoints to k6 performance tests.

/accounts/{id}/allowances/tokens
/accounts/{id}/nfts
/accounts/{id}/tokens
/blocks
/blocks/{id}
/contracts/result

**Related issue(s)**:

Fixes #4961

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-12-21 15:57 UTC, xin-hedera requested changes

2022-12-21 15:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/lib/parameters.js
> +      entityIdResponseKey: 'blocks',
```suggestion
      queryParamMap: {limit: 1},
```
Override limit to 1 since we just need one block.

`entityIdResponseKey` won't work for blocks endpoint because the response and query parameters are structured differently from e.g. `/accounts`. `getPropertiesForEntity` will still work just because only 1 block is needed.

2022-12-21 15:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/accountsNfts.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/accounts/${testParameters['DEFAULT_ACCOUNT_ID']}/nfts`;
this may not provide much insight into performance since `DEFAULT_ACCOUNT_ID` may own very few nfts. should add another parameter discover function to find an account with at least 100 nfts.

2022-12-21 15:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/accountsTokenAllowance.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/accounts/${testParameters['DEFAULT_ACCOUNT_ID']}/allowances/tokens`;
same issue, the account may have very few token allowances

2022-12-21 15:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/accountsTokens.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/accounts/${testParameters['DEFAULT_ACCOUNT_ID']}/tokens`;
same issue

2022-12-21 15:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/blocksNumber.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/blocks/${testParameters['DEFAULT_BLOCK_HASH']}`;
rename the file to `blocksHash.js` and add another `blocksNumber.js` using  `${testParameters['DEFAULT_BLOCK_NUMBER']}`

2022-12-21 15:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/rest/test/blocksNumber.js
> +const urlTag = '/blocks/{hashOrNumber}';
```suggestion
const urlTag = '/blocks/{hash}';
```

2022-12-21 18:41 UTC, MarcKriguerAtHedera reviewed
Looks good to me, except for that issue (raised in multiple locations) by Xin, where the DEFAULT_ACCOUNT_ID may need to be environment-specific, and may vary from use to use.

2023-01-04 22:26 UTC, mgoelswirlds commented on hedera-mirror-test/k6/README.md
> +export DEFAULT_START_ACCOUNT=0.0.34196600
I have added this as an example on testnet , because this does return account which has multiple token allowances.

2023-01-04 22:27 UTC, mgoelswirlds commented on hedera-mirror-test/k6/src/lib/parameters.js
> +      `It was not possible to find an account with with significant number of nfts.`
If an account with significant nfts is not found, we want to quit the test so that it does not keep looking for the account.

2023-01-04 22:28 UTC, mgoelswirlds commented on hedera-mirror-test/k6/src/lib/parameters.js
> +      `It was not possible to find an account with with significant number of allowance tokens.`
Same as nfts.

2023-01-04 22:28 UTC, mgoelswirlds commented on hedera-mirror-test/k6/src/lib/parameters.js
> +      `It was not possible to find an account with with significant number of tokens.`
Same as nfts.

2023-01-05 00:33 UTC, MarcKriguerAtHedera submitted a review, later dismissed
Looks good to me, except fpr that comment about the DEFAULT_START_ACCOUNT being used for all networks.

2023-01-05 00:33 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/README.md
> +export DEFAULT_START_ACCOUNT=0.0.34196600
Is there a way to specify different default accounts for different start accounts for different networks?  It looks to me like it would use that account number regardless of testnet/previewnet/mainnet.

2023-01-05 14:28 UTC, mgoelswirlds commented on hedera-mirror-test/k6/README.md
> +export DEFAULT_START_ACCOUNT=0.0.34196600
This is just an example in the readMe. That is why I commented above saying this value can be changed per environment since I have provided it as an env variable.

2023-01-05 16:53 UTC, steven-sheehy requested changes

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsTokens.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/accounts/${testParameters['DEFAULT_ACCOUNT_ID_TOKEN']}/tokens`;
Should specify DEFAULT_LIMIT

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsTokenAllowance.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/accounts/${testParameters['DEFAULT_ACCOUNT_ID_TOKEN_ALLOWANCE']}/allowances/tokens`;
Should specify DEFAULT_LIMIT

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsNfts.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/accounts/${testParameters['DEFAULT_ACCOUNT_ID_NFTS']}/nfts`;
Should specify DEFAULT_LIMIT

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsNfts.js
> +  .check('Account nfts results OK', (r) => isSuccess(r, resultListName))
Should check isValidListResponse

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/accountsTokenAllowance.js
> +  .check('Account token allowances results OK', (r) => isSuccess(r, resultListName))
Should check isValidListResponse

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contractsResult.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/${testParameters['DEFAULT_CONTRACT_ID']}/results`;
Use DEFAULT_LIMIT

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/blocksNumber.js
> +import {isSuccess, isValidListResponse} from "./common.js";
```suggestion
import {isSuccess} from "./common.js";
```

2023-01-05 16:53 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/blocksHash.js
> +import {isSuccess, isValidListResponse} from "./common.js";
```suggestion
import {isSuccess} from "./common.js";
```

2023-01-05 21:52 UTC, steven-sheehy approved these changes
LGTM

2023-01-06 15:57 UTC, edwin-greene approved these changes
Looks good

2023-01-06 16:15 UTC, xin-hedera approved these changes

2023-01-06 16:19 UTC, merged