Add 8 new k6 unit tests
hashgraph/hedera-mirror-node pull request #5140
Opened 2022-12-30 22:05 UTC by MarcKriguerAtHedera

(those not already covered in recent previous k6 work).

**Description**:

This PR adds 8 k6 tests to cover API methods not yet covered.

**Related issue(s)**:

Fixes #5104

**Notes for reviewer**:
6 of the new tests were successful for 100% of the k6 runs, one for 93%, but the "Contracts Results id Actions" test was not able to get a non-empty list of actions.  See details as a comment on the ticket.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (k6)

2023-01-05 17:13 UTC, steven-sheehy requested changes

2023-01-05 17:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/networkNodes.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}${urlTag}`;
Add limit=25 to increase to max allowed

2023-01-05 17:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contractsResultsLogs.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/results/logs`;
Add DEFAULT_LIMIT

2023-01-05 17:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contractsResultsIdActions.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/results/${testParameters['DEFAULT_CONTRACT_RESULT_HASH']}/actions`;
Add DEFAULT_LIMIT

2023-01-05 17:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contractsResultsId.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/results/${testParameters['DEFAULT_CONTRACT_RESULT_HASH']}`;
Add DEFAULT_LIMIT

2023-01-05 17:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/rest/test/contractsIdState.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/${testParameters['DEFAULT_CONTRACT_EVM_ADDRESS']}/state`;
Add DEFAULT_LIMIT

2023-01-05 17:13 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/lib/parameters.js
> +      DEFAULT_CONTRACT_EVM_ADDRESS: contract.evm_address,
We don't need DEFAULT_CONTRACT_EVM_ADDRESS, can just use DEFAULT_CONTRACT_ID for contract state retrieval

2023-01-06 01:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/src/rest/test/networkNodes.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}${urlTag}`;
Done.

2023-01-06 01:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/src/rest/test/contractsResultsLogs.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/results/logs`;
Done.

2023-01-06 01:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/src/rest/test/contractsResultsIdActions.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/results/${testParameters['DEFAULT_CONTRACT_RESULT_HASH']}/actions`;
Done.

2023-01-06 01:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/src/rest/test/contractsResultsId.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/results/${testParameters['DEFAULT_CONTRACT_RESULT_HASH']}`;
Done.

2023-01-06 01:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/src/rest/test/contractsIdState.js
> +    const url = `${testParameters['BASE_URL']}${urlPrefix}/contracts/${testParameters['DEFAULT_CONTRACT_EVM_ADDRESS']}/state`;
Done.

2023-01-06 01:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/k6/src/lib/parameters.js
> +      DEFAULT_CONTRACT_EVM_ADDRESS: contract.evm_address,
Done.  (Removed.)

2023-01-06 15:35 UTC, steven-sheehy approved these changes
LGTM

2023-01-06 15:36 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2023-01-06 18:38 UTC, MarcKriguerAtHedera commented
I was able to fix the merge conflicts and get all the tests running again.

2023-01-06 18:39 UTC, xin-hedera approved these changes
LGTM

2023-01-06 18:46 UTC, merged