Use virtual time scheduler where possible
hashgraph/hedera-mirror-node pull request #5168
Opened 2023-01-05 20:45 UTC by jnels124

Signed-off-by: Jesse Nelson <jesse@swirldslabs.com>

**Description**:
Use virtual time scheduler where possible for publisher step verification

**Related issue(s)**:

Fixes #5087

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-01-05 22:52 UTC, steven-sheehy requested changes

2023-01-05 22:52 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java
>                  .expectNext(topicMessage1.getResponse())
Should probably add an await before expectNext

2023-01-05 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/CompositeStreamFileProvider.java
> +    public boolean isHealthy() {
```suggestion
   @VisibleForTesting
   boolean isHealthy() {
```

2023-01-05 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/CompositeStreamFileProviderTest.java
> +                .thenAwait(Duration.ofSeconds(10))
Could make this a constant like in other tests

2023-01-05 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/CompositeStreamFileProviderTest.java
> +                .pollDelay(Duration.ofSeconds(1))
Should poll faster to improve test runtime like 100ms

2023-01-06 13:46 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/CompositeStreamFileProviderTest.java
> +                .pollDelay(Duration.ofSeconds(1))
Forget to change that back after playing with things. Fixed

2023-01-06 13:46 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/CompositeStreamFileProviderTest.java
> +                .thenAwait(Duration.ofSeconds(10))
fixed

2023-01-06 13:47 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/CompositeStreamFileProvider.java
> +    public boolean isHealthy() {
fixed

2023-01-06 13:48 UTC, jnels124 commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java
>                  .expectNext(topicMessage1.getResponse())
good catch. fixed

2023-01-06 15:38 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-01-06 19:01 UTC, xin-hedera approved these changes
LGTM

2023-01-06 19:42 UTC, merged