Add acceptance test for auto account creation
hashgraph/hedera-mirror-node pull request #5188
Opened 2023-01-09 17:33 UTC by jnels124

Signed-off-by: Jesse Nelson <jesse@swirldslabs.com>

**Description**:
Add acceptance test for auto account creation

* Add acceptance test to ensure account is created when a transfer is sent to ED alias
* Add acceptance test to ensure account is created when a transfer is sent to ECDSA alias

**Related issue(s)**:

Fixes #4983 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-01-09 21:01 UTC, steven-sheehy requested changes

2023-01-09 21:39 UTC, xin-hedera requested changes

2023-01-09 21:39 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    @Given("I send {long} tℏ from {string} to {string} alias not present in the network")
should just send fund from the client operator to the new alias account, this will reduce the complexity of the test

```suggestion
    @Given("I send {long} tℏ to {string} alias not present in the network")
```

2023-01-09 21:39 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        startingBalance = accountClient.getBalance(senderAccountId);
not needed if change the test case to send fund from the client operator
```suggestion
        senderAccountId = accountClient.getAccount(AccountClient.AccountNameEnum.valueOf(senderAccount));
        startingBalance = accountClient.getBalance(senderAccountId);
```

2023-01-09 21:39 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        networkTransactionResponse = accountClient.sendApprovedCryptoTransfer(senderAccountId, receiverAccountId, Hbar.fromTinybars(amount));
once we change the test case to send from the client operator

```suggestion
        networkTransactionResponse = accountClient.sendCryptoTransfer(receiverAccountId, Hbar.fromTinybars(amount));
```

2023-01-09 21:39 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    }
perhaps just verify the balance in  `verifyAccountCreated`

2023-01-11 16:15 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        networkTransactionResponse = accountClient.sendApprovedCryptoTransfer(senderAccountId, receiverAccountId, Hbar.fromTinybars(amount));
fixed

2023-01-11 16:15 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        startingBalance = accountClient.getBalance(senderAccountId);
fixed

2023-01-11 16:15 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +    @Given("I send {long} tℏ from {string} to {string} alias not present in the network")
fixed

2023-01-11 16:15 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
> +    public AccountInfo getAccountInfo(AccountId accountId) {
fixed

2023-01-11 16:16 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        accountInfo = accountClient.getAccountInfo(receiverAccountId);
fixed

2023-01-11 16:23 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/TestUtil.java
> +        if (key.isECDSA()) {
there is `PublicKey.toProtobufKey` from SDK. perhaps can remove the utility class completely, since what's left is base32 encode it to get the format mirrornode REST API accepts

2023-01-11 16:34 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/TestUtil.java
> +        if (key.isECDSA()) {
I saw that method but it is package private. Ideally I could use that but this seemed better than having a wrapper object that shadows the package

2023-01-11 16:42 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/TestUtil.java
> +        if (key.isECDSA()) {
missed that. it might be a good idea to ask SDK change it to public.

2023-01-11 16:43 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-01-11 23:17 UTC, steven-sheehy approved these changes
LGTM

2023-01-12 15:36 UTC, steven-sheehy approved these changes

2023-01-12 15:42 UTC, xin-hedera approved these changes

2023-01-12 15:57 UTC, mgoelswirlds approved these changes

2023-01-12 16:08 UTC, merged