adding testnet-na & testnet-eu deployment
hashgraph/hedera-mirror-node pull request #5191
Opened 2023-01-09 22:50 UTC by tolorukooba

Signed-off-by: tolorukooba <teslim.olorukooba@swirldslabs.com>

This PR adds flux config for testnet-na and testnet-eu mirrornode deployment

2023-01-09 23:14 UTC, xin-hedera commented on clusters/testnet-eu/common/sealed-secret-grafana-cloud.yaml
> +    username:
empty value? same in `sealed-secret.yaml`

2023-01-09 23:14 UTC, xin-hedera commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_ENTITY_PERSIST_TRANSACTIONHASH: "true"
no transaction hash for testnet please
```suggestion
```

2023-01-09 23:22 UTC, tolorukooba commented on clusters/testnet-eu/common/sealed-secret-grafana-cloud.yaml
> +    username:
I need inputs from Steven for these

2023-01-09 23:34 UTC, steven-sheehy requested changes

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +apiVersion: helm.toolkit.fluxcd.io/v2beta1
Missing flux-system namespace yamls in both clusters

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +          cpu: 400m
This is a workaround specific to mainnet. Can remove.

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +        HEDERA_MIRROR_MONITOR_SUBSCRIBE_GRPC_HCS_TOPICID: "0.0.368908"
These topics won't exist until after creation. Since it's testnet, it's probably fine to create a new topic on every start of monitor. Better to delete these lines in favor of auto-create.
```suggestion
```

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/sealed-secret.yaml
> +  namespace: tesnet
It's a bit presumptuous to name it after yourself, no? 😉 

```suggestion
  namespace: testnet
```

But as a result, it doesn't decrypt and I can't verify contents.

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/sealed-secret.yaml
> +      namespace: tesnet
```suggestion
      namespace: testnet
```

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-eu/common/sealed-secret-grafana-cloud.yaml
> +    username:
They will be the same decrypted contents as mainnet. Their encrypted contents varies, of course.

2023-01-09 23:34 UTC, steven-sheehy commented on clusters/testnet-na/testnet/sealed-secret.yaml
> +    values.yaml: AgCp2rm5/Mb4pWvwINVlf8RVDWRlsXptGUREVV8rwhZ4xe7G2Vr8p/9iW5ujnAOZ89ttjxT6Alf2cnnxWgBel+fNyKKLDBGL6VY+/mEp4XKriyAXkEEhDWUCbT1aNjhHS2g77iPsYVvUEx5qV7nUvdtpEvQfFbHWNsHQfKkhFUtFowWlLh7U2D
This fails to decrypt on testnet-na

2023-01-10 19:34 UTC, tolorukooba commented on clusters/testnet-eu/common/sealed-secret-grafana-cloud.yaml
> +    username:
fixed!

2023-01-10 19:34 UTC, tolorukooba commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +apiVersion: helm.toolkit.fluxcd.io/v2beta1
added!

2023-01-10 19:34 UTC, tolorukooba commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +          cpu: 400m
removed!

2023-01-10 19:34 UTC, tolorukooba commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +        HEDERA_MIRROR_MONITOR_SUBSCRIBE_GRPC_HCS_TOPICID: "0.0.368908"
removed!

2023-01-10 19:34 UTC, tolorukooba commented on clusters/testnet-eu/testnet/sealed-secret.yaml
> +  namespace: tesnet
lol. rectified

2023-01-10 19:40 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +apiVersion: helm.toolkit.fluxcd.io/v2beta1
Still missing. I'm talking about alert.yaml, provider.yaml, etc.

2023-01-10 20:08 UTC, steven-sheehy requested changes

2023-01-10 20:08 UTC, steven-sheehy commented on clusters/testnet-eu/testnet/sealed-secret.yaml
> +    values.yaml: AgCnmMMIWr/kWBRgxmzWI1HmcSGh0W/TL2hMd2VrfY480vBK5FnhVOG+9VXlyhtCVnqv+u70sJUuBZLkBNPcScHFqXmG1xBZcNrxQqG1G7Jx6L/UQPwMPQsnkl68kLehYTb07qkY4IU0xtmNYihSkVsRHoEMIPYVDENSWT+fgkPylh5lyYuQI3
Same problems as testnet-na

2023-01-11 14:50 UTC, tolorukooba commented on clusters/testnet-na/testnet/sealed-secret.yaml
> +    values.yaml: AgCvgtD6j9miGI0nL19oRG229tQyVTSpGujjSwsecfSwGvIN+pW5o03JjIgaL+wDJwM1bpyWyDRkQVZliabyKzPQZ+V+aPvD+6Q0ez/qPR83X2O9h/jhKCgQUdUHyKhUD0fYdmfsvFQVxXwb6UBE4y916o948PKEOfP06+kqhci/guYhjU29X9
removed!

2023-01-11 14:50 UTC, tolorukooba commented on clusters/testnet-na/testnet/sealed-secret.yaml
> +    values.yaml: AgCvgtD6j9miGI0nL19oRG229tQyVTSpGujjSwsecfSwGvIN+pW5o03JjIgaL+wDJwM1bpyWyDRkQVZliabyKzPQZ+V+aPvD+6Q0ez/qPR83X2O9h/jhKCgQUdUHyKhUD0fYdmfsvFQVxXwb6UBE4y916o948PKEOfP06+kqhci/guYhjU29X9
added a place holder bucket

2023-01-11 14:51 UTC, tolorukooba commented on clusters/testnet-na/testnet/sealed-secret.yaml
> +    values.yaml: AgCvgtD6j9miGI0nL19oRG229tQyVTSpGujjSwsecfSwGvIN+pW5o03JjIgaL+wDJwM1bpyWyDRkQVZliabyKzPQZ+V+aPvD+6Q0ez/qPR83X2O9h/jhKCgQUdUHyKhUD0fYdmfsvFQVxXwb6UBE4y916o948PKEOfP06+kqhci/guYhjU29X9
monitor account id and key values are blank with replicas=0

2023-01-11 14:52 UTC, tolorukooba commented on clusters/testnet-eu/testnet/sealed-secret.yaml
> +    values.yaml: AgCnmMMIWr/kWBRgxmzWI1HmcSGh0W/TL2hMd2VrfY480vBK5FnhVOG+9VXlyhtCVnqv+u70sJUuBZLkBNPcScHFqXmG1xBZcNrxQqG1G7Jx6L/UQPwMPQsnkl68kLehYTb07qkY4IU0xtmNYihSkVsRHoEMIPYVDENSWT+fgkPylh5lyYuQI3
fixed!

2023-01-11 17:29 UTC, tolorukooba commented on clusters/testnet-eu/testnet/helmrelease.yaml
> +apiVersion: helm.toolkit.fluxcd.io/v2beta1
fixed!

2023-01-11 20:49 UTC, steven-sheehy requested changes

2023-01-11 20:49 UTC, steven-sheehy commented on clusters/testnet-eu/flux-system/sealed-secret.yaml
> +kind: SealedSecret
Still missing `flux-system/kustomization.yaml`

2023-01-11 20:49 UTC, steven-sheehy commented on clusters/testnet-na/testnet/helmrelease.yaml
> +      version: '0.70.2'
Should update to v0.71.0 now

2023-01-11 21:46 UTC, steven-sheehy approved these changes
LGTM

2023-01-11 21:47 UTC, merged