05152 hip 631 virtual addresses design doc
hashgraph/hedera-mirror-node pull request #5193
Opened 2023-01-10 18:44 UTC by MarcKriguerAtHedera

**Description**:
A design document for the mirror-node part of HIP 631.

**Related issue(s)**:

Fixes #5152

**Notes for reviewer**:
This is just a .md document.  Once approved, I will create a task list containing the tasks described within.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [n/a] Tested (unit, integration, etc.)

2023-01-10 21:25 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +  create type virtual_address_status as enum ('ACTIVE', 'DISABLED');
Our upsert framework can't delete rows, on the other side, there will be performance issue if we use spring repository to delete the row, so I think we still need the `DELETED` status

```suggestion
  create type virtual_address_status as enum ('ACTIVE', 'DELETED', DISABLED');
```

2023-01-10 21:25 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +     evm_address         bytea null,
```suggestion
     evm_address         bytea not null,
```

2023-01-10 21:25 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    - removeVirtualAddress: Do not allow if primary virtual address is getting removed, and other non-primary default addresses present.
hard to read the description of each operation.

for any of the operations, whenever it involves `the list`, we won't be able to either check or enforce any limit, because `SqlEntityListener` only has a view of the virtual addresses CRUD inside one record file.

besides, a lot of those checks are not supposed to be done at mirrornode, for example, for disableVirtualAddress, "Do not allow if primary virtual address is getting disabled...". At best we can log a warning, we can't disallow it since if the changes from a transaction violate the spec (here it refers to the HIP), it's a bug in services.

2023-01-10 21:25 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +     primary key (account_id, evm_address)
we'll need another index on `(account_id, evm_address)` with condition `status <> 'DELETED'` to speed up read

2023-01-10 21:25 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0...1', // evm_address (default virtual address) in `long-zero` format
this is not `default virtual address`

2023-01-10 21:25 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +Optional: Only include up to ten virtual addresses in the output, and log a warning if more than ten virtual addresses are found for the given id / alias / evm address.
why do we want to check if there are more than 10 virtual addresses in REST API and log a warning? there is a cost for a db query to return more rows and the benefit we get is just a warning.

2023-01-10 22:38 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +     account_id          entity_id not null,
we have moved away from using the custom type `entity_id`

```suggestion
     account_id          bigint not null,
```

2023-01-11 00:44 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +  create type virtual_address_status as enum ('ACTIVE', 'DISABLED');
Done.

2023-01-11 00:46 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +     evm_address         bytea null,
Done.  The `evm_address` field in the `entity` object can be `null`, but you are right that in **this** table, it should not be null.

2023-01-11 00:48 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    - removeVirtualAddress: Do not allow if primary virtual address is getting removed, and other non-primary default addresses present.
Ah, I have eliminated the "No not allow" text; agreed that if any of the things I had previously marked as "Do not allow" happened, it would be a bug in the services layer.

2023-01-11 00:48 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +     primary key (account_id, evm_address)
Added that, thank you!

2023-01-11 00:49 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0...1', // evm_address (default virtual address) in `long-zero` format
But it should be; this was part of the discussion with Miroslav, who okayed the use of the existing `evm_address` field to hold the `default virtual address` (instead of adding a second field to do that).

2023-01-11 00:52 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +Optional: Only include up to ten virtual addresses in the output, and log a warning if more than ten virtual addresses are found for the given id / alias / evm address.
The number of virtual addresses per account is supposed to be limited to 10 (for HIP-631) but might be increased in the future.  This was an attempt to catch a bug (if introduced) that would exceed 10 before we add a new endpoint to page through the larger list of (unlimited) virtual accounts, if they decide to increase the limit in the future.

2023-01-11 00:52 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +     account_id          entity_id not null,
Thanks; I had not been aware of that change.

2023-01-11 00:55 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +Optional: Only include up to ten virtual addresses in the output, and log a warning if more than ten virtual addresses are found for the given id / alias / evm address.
That’s quite a cost to catch a bug. We can instead query the db periodically if we really want to catch it

2023-01-11 00:57 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0...1', // evm_address (default virtual address) in `long-zero` format
You seem to talk about sth else. The hederaAddress, from the HIP and part of the comment here, is the long form address directly encoded from shard.realm.num, so it’s not the default virtual address IMO

2023-01-12 20:42 UTC, steven-sheehy requested changes

2023-01-12 20:42 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +        evm_address: '0x2...3',
It's a bit strange to mix terms `virtual_addresses` and `evm_address`. Shouldn't a list of `virtual_addresses` contain one or more `virtual_address`? We should clarify with Nana or Ali if we want to move away from the term `evm_address` in favor of `virtual_address`.

2023-01-12 20:42 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +In addition, add an additional parameter to that API address call, `includeDisabledVirtualAddresses`, defaulting to `false`.  If set to `true`,
YAGNI. Don't think we should add this until there's a strong customer need for it.

2023-01-12 20:42 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +    - removeVirtualAddress: Do not allow if primary virtual address is getting removed, and other non-primary default addresses present.
Agree, none of this logic is possible in mirror node since we don't do find then updates. This check logic should be removed and instead upsert language should be used to specify what occurs.

2023-01-12 22:33 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +     primary key (account_id, evm_address)
the additional index is in consideration that although we have a cap of `active` + `disabled` virtual addresses per entity, we can't cap `deleted` addresses and the deleted addresses will also stay in `entity_virtual_address` table.

2023-01-12 22:38 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +We are choosing to use the existing `evm_address` field of the `entity` table to hold the default virtual address, rather than adding a new column for this purpose.
we may want to keep `entity.evm_address` and at the same time duplicate the default evm address + extra info to `entity_virtual_address` table. that way, the endpoint `/api/v1/accounts` only have to query `entity` table to get the default.

2023-01-17 05:43 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    - removeVirtualAddress: Do not allow if primary virtual address is getting removed, and other non-primary default addresses present.
I revamped this section and removed the "find then update" language.

2023-01-17 05:44 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +     primary key (account_id, evm_address)
I left the additional index sentence in place, but I can delete it on Tuesday if there is still any controversy over it.

2023-01-17 05:44 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0...1', // evm_address (default virtual address) in `long-zero` format
Updated (and hopefully made clearer).

2023-01-17 05:44 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +Optional: Only include up to ten virtual addresses in the output, and log a warning if more than ten virtual addresses are found for the given id / alias / evm address.
Done.

2023-01-17 05:45 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +Note: The HIP proposes incremental capacity limits as 1, then 3, then 10, then possibly an umbounded number.  For now, the Mirror Node
Fixed.

2023-01-17 05:45 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +for users creating a new Hedera account through a Ethereum Smart Contract mechanism)) by allowing a Hedera Account to have
Fixed.

2023-01-17 05:45 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +Note: The HIP proposes incremental capacity limits as 1, then 3, then 10, then possibly an umbounded number.  For now, the Mirror Node
Done.

2023-01-17 05:46 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +The third value, 'DELETED', is needed because our Upsert framework can't delete rows (and attempting to delete rows using a Spring Framework call could be slow).
Done.

2023-01-17 05:46 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +The third value, 'DELETED', is needed because our Upsert framework can't delete rows (and attempting to delete rows using a Spring Framework call could be slow).
ok, "irrelevant" sentence removed.

2023-01-17 05:50 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0...1', // evm_address (default virtual address) in `long-zero` format
Elsewhere, @xin-hedera indicated that it's actually not the `evm_address` (default virtual address) that's reflected here, but the account's entity id (in shard.realm.num format, but in `long-zero` form).  But this is not a new field; it's just a newly-calculated line of output).

2023-01-17 05:51 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +        evm_address: '0x2...3',
We can run that idea past @Nana-EC this coming week.

2023-01-17 05:51 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +In addition, add an additional parameter to that API address call, `includeDisabledVirtualAddresses`, defaulting to `false`.  If set to `true`,
Removed.

2023-01-17 05:52 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +   - In general it *may not be possible to delete/disable* a virtual address that is the default one *unless before that* we update the default virtual address to be another one.
"find-then-update" text removed.

2023-01-17 05:55 UTC, MarcKriguerAtHedera commented
I made these changes on Friday, but then my power went out late Friday afternoon, and I couldn't merge the changes in later that evening.  (My laptop was working, but not my router, so I could not connect to github.)

I was away for the weekend, and am now committing the changes to the file made that day.

2023-01-17 21:56 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +We are choosing to use the existing `evm_address` field of the `entity` table to hold the default virtual address, rather than adding a new column for this purpose.
Ok, let's keep both for now and see how the implementation goes.

2023-01-17 22:04 UTC, xin-hedera requested changes

2023-01-17 22:04 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +* Heed new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
typo?

```suggestion
* Need new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
```

2023-01-17 22:04 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +The HIP-631 document indicates that whenever a virtual address gets deleted, it cannot be the default virtual address getting deleted.<F12>, so we only need to update
remove the `.<F12>`

```suggestion
The HIP-631 document indicates that whenever a virtual address gets deleted, it cannot be the default virtual address getting deleted, so we only need to update
```

2023-01-17 22:04 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +any other way (than adding a new address) to update the default virtual address of an account.
we should really try to rewrite the long sentences so it's easier to read & understand

2023-01-17 22:15 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +        evm_address: '0x2...3',
@Nana-EC said (today) that he's OK with using the label "virtual_address" for each address in the array.

2023-01-17 22:15 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +We will have an index that only holds the non-'DELETED' values, so skipping over the DELETED rows will be fast.  A row in 'DELETED' status will just be ignored.
Done.

2023-01-17 22:17 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +* Heed new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
I did mean "heed" as in "we need to add functionality for these new types of `CryptoAction`, but I changed it from "Heed" to "Support" now.

2023-01-17 22:17 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +The HIP-631 document indicates that whenever a virtual address gets deleted, it cannot be the default virtual address getting deleted.<F12>, so we only need to update
Done.  I must have accidentally hit that key (and not noticed).

2023-01-17 22:19 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +any other way (than adding a new address) to update the default virtual address of an account.
I am merging in all the other changes you and Steven suggested, ahead of a meeting starting iin just a few minutes.  I will rewrite this sentence after the meeting.

2023-01-17 23:49 UTC, xin-hedera requested changes

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +The existing mirror node database, supporting one alias per entity, stores it in a column named `evm_address` in the `entity` table.
in `supporting one alias per entity`, alias is NOT the same as evm address

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +With HIP-631, We now support multiple aliases per entity, with one being labelled the default virtual address for that entity.  We
not `aliases`

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +
changes to `/api/v1/accounts`? we do show `evm_address` in the list accounts REST API endpoint.

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +* `api/v1/accounts/{idOrAliasOrEvmAddress}` changes:
```suggestion
* `/api/v1/accounts/{idOrAliasOrEvmAddress}` changes:
```

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    - start by checking the `entity_virtual_address table for an `evm_address` matching the `{idOrAliasOrEvmAddress}` value; if so, the entity to look up is the `entity_id` of that row.
format, backticks put in wrong place

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0000000000000000000000000000000000001001',    // we calculate this field by expressing the account's entity_id shard.realm.num in "long-zero" format.  This is *not* a new colum
json doesn't accept single quotes, use double quotes instead

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +     is_default          boolean default false not null,
need to explain how to show the true default virtual address in rest api, e.g., an entity's default virtual address is set by a `CryptoUpdateTransaction`, and later a new default is added by another `CryptoUpdateTransaction`, both rows in the table will have `is_default = true`

On the other hand, I still think keeping the default in `entity.evm_address`, removing the `is_default` column, and duplicating the default evm address in both `entity` table and `entity_virtual_address` table have advantages:

- very simple to find entity's default virtual address
- performant `/api/v1/accounts` query since we don't have to join `entity_virtual_address` table

2023-01-17 23:49 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +* Adding `api/v1/accounts/{idOrAliasOrEvmAddress}/virtualAddresses endpoint (for paging through a large number of virtual addresses), but we will reserve that endpoint
missing closing backtick

2023-01-18 00:42 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +any other way (than adding a new address) to update the default virtual address of an account.
Turns out I had already eliminated that long sentence.

2023-01-18 00:43 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +The existing mirror node database, supporting one alias per entity, stores it in a column named `evm_address` in the `entity` table.
Fixed -- just referring to `evm_address` and not `alias` here.

2023-01-18 00:43 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +With HIP-631, We now support multiple aliases per entity, with one being labelled the default virtual address for that entity.  We
Fixed.

2023-01-18 00:44 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +
I don't believe that that endpoint needs to be changed.

2023-01-18 00:44 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +* `api/v1/accounts/{idOrAliasOrEvmAddress}` changes:
Fixed.

2023-01-18 00:45 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    - start by checking the `entity_virtual_address table for an `evm_address` matching the `{idOrAliasOrEvmAddress}` value; if so, the entity to look up is the `entity_id` of that row.
Added leading leading **/** and missing backtick before "table".

2023-01-18 00:45 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0000000000000000000000000000000000001001',    // we calculate this field by expressing the account's entity_id shard.realm.num in "long-zero" format.  This is *not* a new colum
Done.

2023-01-18 00:46 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +
It needs change based on the current revision that we’ll migrate entity.evm_address and it’ll no longer hold the up-to-date default virtual address

2023-01-18 00:47 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +     is_default          boolean default false not null,
Eliminated the *is_default* column entirely.  Keeping to default virtual address in the `evm_address` field.

2023-01-18 00:47 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +* Adding `api/v1/accounts/{idOrAliasOrEvmAddress}/virtualAddresses endpoint (for paging through a large number of virtual addresses), but we will reserve that endpoint
Fixed.

2023-01-18 16:06 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: "0x0000000000000000000000000000000000001001",    // we calculate this field by expressing the account's entity_id shard.realm.num in "long-zero" format.  This is *not* a new colum
quote the keys as well

2023-01-18 17:53 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    - We are not going to delete the `evm_address` column from the `entity` table at this time, but that may be a later migration.
Fixed.

2023-01-18 17:54 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: "0x0000000000000000000000000000000000001001",    // we calculate this field by expressing the account's entity_id shard.realm.num in "long-zero" format.  This is *not* a new colum
Done.

2023-01-18 17:56 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +* We will need to perform a database migration to:
nit, I don't think this line should be in a itemized list:

```suggestion
We will need to perform a database migration to:
```

2023-01-18 17:57 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +* Support new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
same here, this line should be continuation after `When parsing CryptoUpdate transactions`

2023-01-21 00:20 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +* Support new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
Can this section be expanded to highlight the entityListener and other class logic you tend to employ e.g. an domain object is created. On add the db logic is to insert, on the other it's an update to an existing enity to modify the status column

2023-01-21 00:20 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +1) How far in advance will we know about needing to support very large (e.g. ore than 10) virtual addresses for one account? (That is, to implement the
```suggestion
1) How far in advance will we know about needing to support very large (e.g. more than 10) virtual addresses for one account? (That is, to implement the
```

2023-01-21 00:20 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +1) How far in advance will we know about needing to support very large (e.g. ore than 10) virtual addresses for one account? (That is, to implement the
Uncertain. Depends on community usage

2023-01-21 00:20 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +   yes, I think that we intend to externalize those CryptoUpdate transactions. I am not sure about the "batch" part, is this the way we currently externalize similar transactions?
The current services migration logic attempts to do this dispersed across many transactions so I don't believe it will be back to back batches.

2023-01-21 00:20 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +2) What happens if we attempt to delete or disable the current default virtual address?  Does a different virtual address takeover as default?
No replacement to default unless it's explictly done by the user.
Ian an ECDSA account disables it's only address it would then behave like a default ED account without a virtual address.

2023-02-01 18:52 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +We will continue to use the `evm_address` column of the `entity` table, but now this value is used for the *default* virtual address.
Agreed.

2023-02-01 18:53 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +* Support new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
Updated; let me know if this needs further expansion.

2023-02-01 18:54 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +* We will need to perform a database migration to:
This part of the document has been removed.

2023-02-01 18:54 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +* Support new `CryptoUpdate` operations (`addVirtualAddress`, `disableVirtualAddress`, `removeVirtualAddress`, `setDefaultVirtualAddress`).
Also obsolete; this part of the document has been rewritten.

2023-02-01 18:56 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +1) How far in advance will we know about needing to support very large (e.g. ore than 10) virtual addresses for one account? (That is, to implement the
Moved from "Open" to "Answered," thank you!

2023-02-01 18:57 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +   yes, I think that we intend to externalize those CryptoUpdate transactions. I am not sure about the "batch" part, is this the way we currently externalize similar transactions?
The question is mostly about how the mirror node will determine that these migrations were performed.

2023-02-01 18:57 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +2) What happens if we attempt to delete or disable the current default virtual address?  Does a different virtual address takeover as default?
Makes sense.

2023-02-02 18:22 UTC, xin-hedera requested changes

2023-02-02 18:22 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +     nonce               bigint not null,
for consistency, the existing nonce column is `entity.ethereum_nonce`

```suggestion
     ethereum_nonce               bigint not null,
```

2023-02-02 18:22 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +in case a future extension to this HIP decides to implement that.
missing closing backtick

2023-02-02 18:22 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +        "is_default": false
missing the ethereum nonce

2023-02-02 18:22 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +#### CryptoFunctionResult Parsing
```suggestion
#### ContractFunctionResult Parsing
```

2023-02-02 18:22 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +When parsing CryptoFunctionResult transactions,
it's not `CryptoFunctionResult transactions`, it's either the `contractCallResult` or `contractCreateResult` in the transaction record

2023-02-02 18:22 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    - For now, we are not including the nonce values in the REST API changes to `/api/v1/accounts/{idOrAliasOrEvmAddress}` endpoint, but we could add the "nonce" field for each "virtual_address" elem
we already have `ethereum_nonce` in the rest api response. so I do think we have to track & show it, as well as add the `ethereum_nonce` to the `virtual_address` element

2023-02-02 20:08 UTC, jnels124 commented on docs/design/hip-631-virtual-address.md
> + When a virtual address is disabled, it is still locked to the Hedera Account it had been actuve with.
actuve should be active

2023-02-02 23:17 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +    - For now, we are not including the nonce values in the REST API changes to `/api/v1/accounts/{idOrAliasOrEvmAddress}` endpoint, but we could add the "nonce" field for each "virtual_address" elem
yeah. main account response should only display the overall account nonce.

2023-02-02 23:17 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +   yes, I think that we intend to externalize those CryptoUpdate transactions. I am not sure about the "batch" part, is this the way we currently externalize similar transactions?
There's no item to say migration is occurring. 
The only way you could figure out would be for a hollow account, whereby the alias is cleared and the virtual address is set

2023-02-02 23:34 UTC, xin-hedera commented on docs/design/hip-631-virtual-address.md
> +    - For now, we are not including the nonce values in the REST API changes to `/api/v1/accounts/{idOrAliasOrEvmAddress}` endpoint, but we could add the "nonce" field for each "virtual_address" elem
disagree. you may have missed that we don't intent to add `/api/v1/accounts/{id}/virtualAddresses`. So if we don't show all the virtual address nonces here, users can only get the default nonce from mirrornode

2023-02-03 15:02 UTC, Nana-EC requested changes
We should add an acceptance tests section

2023-02-03 15:02 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +
We should add a section for Acceptance tests for cover the high level E2E scenarios we wanna capture
e.g.Submit CryptoCreate w ECDSA public key to network, confirm transaction and check `api/v1/accounts/{idOrAliasOrEvmAddress}` contains a valid and expected Hedera address and virtual address values

2023-02-03 15:30 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +
Yes, I [requested](https://github.com/hashgraph/hedera-mirror-node/pull/5193#discussion_r1068495915) the same 3 weeks ago.

2023-02-04 02:17 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +   yes, I think that we intend to externalize those CryptoUpdate transactions. I am not sure about the "batch" part, is this the way we currently externalize similar transactions?
The question is:  Will the mirror node be able to see `CryptoUpdate` messages (whether they are in batches or one at a time doesn't matter) to observe what used to be an ECDSA alias become a virtual address (in `evm_address` format, and update the `evm_address` field accordingly, or will it need to perform essentially exactly the same migration on its own?

2023-02-04 02:23 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +     nonce               bigint not null,
I agree that `nonce` would be preferable (in the abstract), but having the two `entity` tables using the same column name is more important.

2023-02-04 02:24 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +in case a future extension to this HIP decides to implement that.
Fixed.

2023-02-04 02:25 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +        "is_default": false
That's the last "Non-goal" before the "Open Questions" section.  Or are you basically saying that we definitely **do** need to output it here?  I'll make the change if so.

2023-02-04 02:26 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +#### CryptoFunctionResult Parsing
Fixed.

2023-02-04 02:28 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +When parsing CryptoFunctionResult transactions,
Updated the text.

2023-02-04 02:30 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +    - For now, we are not including the nonce values in the REST API changes to `/api/v1/accounts/{idOrAliasOrEvmAddress}` endpoint, but we could add the "nonce" field for each "virtual_address" elem
This convinced me.  I'll change the output to include the ethereum nonces.

2023-02-04 02:33 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> + When a virtual address is disabled, it is still locked to the Hedera Account it had been actuve with.
Fixed, thank you!

2023-02-04 02:34 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +It is not until that virtual address is deleted than it can be added to another Hedera account.
ok, deleted.

2023-02-04 02:35 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +any other way (than adding a new address) to update the default virtual address of an account.
I think `add` for adding a new one and `set` for changing the default make more sense than having one operation that does both.

2023-02-04 02:53 UTC, MarcKriguerAtHedera commented on docs/design/hip-631-virtual-address.md
> +
Added that section (and @Nana-EC 's example as the first acceptance test).  Other tests can be added on Monday.

2023-02-06 13:22 UTC, Nana-EC commented on docs/design/hip-631-virtual-address.md
> +   yes, I think that we intend to externalize those CryptoUpdate transactions. I am not sure about the "batch" part, is this the way we currently externalize similar transactions?
Ah. Yes there will be a CryptoUpdate in which the [virtual_address_update](https://github.com/hashgraph/hedera-protobufs/blob/main/services/crypto_update.proto#L159) will be populated with `add` value set.

2023-02-06 14:53 UTC, MiroslavGatsanoga commented on docs/design/hip-631-virtual-address.md
> +   yes, I think that we intend to externalize those CryptoUpdate transactions. I am not sure about the "batch" part, is this the way we currently externalize similar transactions?
As per the latest version of the HIP we will be externalizing through `CryptoUpdate`s for accounts, but will not do it for Contracts because all needed information (the contract.alias) should be already available, it should be only an update to the internal state representations for Services and Mirror Node.

2023-02-07 04:33 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +    hedera_address: '0x0...1', // evm_address (default virtual address) in `long-zero` format
Still does not render. Please remove any comments from JSON text. Can add as a note after JSON.

2023-02-07 04:33 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +this table name is more in line with existing mirror node naming.
Still not updated

2023-02-07 04:33 UTC, steven-sheehy commented on docs/design/hip-631-virtual-address.md
> +Note: The HIP proposes incremental capacity limits as 1, then 3, then 10, then possibly an umbounded number.  For now, the Mirror Node
Now there is no non-functional requirements section.

2023-02-14 16:41 UTC, closed without merging