Small tweaks to suppress the 'blocker' and 'critical' code smells that really are OK.
hashgraph/hedera-mirror-node pull request #5194
Opened 2023-01-11 00:12 UTC by MarcKriguerAtHedera

Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:
Fixes one "blocker" code smell (by adding an assert) and suppresses 14 "critical" code smell (8 for oo-high Cognitive Complexity; 6 for where a  generic type is being returned (changing it to a common base class type did not work).

**Related issue(s)**:

Fixes #5189 

**Notes for reviewer**:
Except for the one "blocker" with 4 new lines of code, all this does is @SuppressWarning of the two smells indicated above.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-01-11 15:27 UTC, edwin-greene submitted a review, later dismissed
Looks good to me.

2023-01-11 16:02 UTC, mgoelswirlds submitted a review, later dismissed

2023-01-11 16:36 UTC, xin-hedera requested changes

2023-01-11 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java
> +            workDone.getAndIncrement();
remove this line then we can change `workDone` to a primitive long. also add a comment to why the dummy variable and the `assert` at the end is needed

2023-01-11 17:36 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java
> +            workDone.getAndIncrement();
Done.  I realized that I really didn't need a count, per se; just "is it still 0 or more?" -- so I made it a primitive boolean, instead.   But I did add a couple of comments.

2023-01-11 17:39 UTC, xin-hedera approved these changes
LGTM

2023-01-11 18:39 UTC, edwin-greene approved these changes
Looks good.

2023-01-11 23:38 UTC, steven-sheehy requested changes

2023-01-11 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java
> +    @SuppressWarnings({"java:S1874", "java:S3776"})
This one is probably fine to keep

2023-01-11 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    @SuppressWarnings("java:S3776")
We can move the `if (body.has...)` section to a separate method like `processTransaction(RecordItem recordItem)`.

2023-01-11 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>          if (entityProperties.getPersist().isTokens()) {
```suggestion
    private void insertTokenUpdate(RecordItem recordItem) {
        if (!entityProperties.getPersist().isTokens()) {
            return;
        }
```

2023-01-11 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +    @SuppressWarnings("java:S3776")
Don't think we can refactor anything here.

2023-01-11 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
>      private static TypeInfo extractTypeInfo(String filename) {
The `TypeInfo` is a bit useless. Perhaps we can turn `StreamFilename` itself into a builder and use that to clean this up.

2023-01-11 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    @SuppressWarnings("java:S3776")
We can move `++migrationCount;` to the other `if (migration)` block.

2023-01-12 23:40 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +    @SuppressWarnings({"java:S135","java:S3776"})
Done; this eventually ended up with 3 submethods, but all are within the complexity limit.

2023-01-12 23:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java
>          return mirrorSubscriber.getSubscriptions()
Done.  (Nice!)

2023-01-12 23:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java
>          return subscriptions(Optional.empty(), status)
Done.

2023-01-12 23:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java
>                  .filter(s -> s.getId() == id)
Done.

2023-01-12 23:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java
> +    @SuppressWarnings({"java:S1874", "java:S3776"})
OK with me.

2023-01-12 23:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    @SuppressWarnings("java:S3776")
Done.  That nicely split the 28 into the 2 methods!

2023-01-12 23:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>          if (entityProperties.getPersist().isTokens()) {
Done.

2023-01-12 23:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +    @SuppressWarnings("java:S3776")
Agreed.

2023-01-12 23:43 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
>      private static TypeInfo extractTypeInfo(String filename) {
This started getting sloppy/ugly very quickly.  I gave myself a time bound of 2 hours, but I wasn't able to accomplish this change in that time.  I am leaving it with suppressing the warning (for now), but this can be revisited later.

2023-01-12 23:44 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    @SuppressWarnings("java:S3776")
I did that, and it brought the complexity down from 18 to 16.  I'm keeping the change, but still suppressing the warning (which is down to 1 over the limit).

2023-01-17 21:47 UTC, xin-hedera requested changes

2023-01-17 21:47 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SubscriptionResponse.java
> +    private boolean responseEncountered = false;
revert changes in this file and just verify `subscriptionResponse.getMirrorHCSResponses().size() > 0` in `MirrorNodeClient.subscribeToTopic`

2023-01-17 21:47 UTC, xin-hedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java
> +    }
use lombok `@Value` on the class to generate `equals` and `hashCode`

2023-01-17 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                verifySigsAndDownloadDataFiles(sigFilesMap, nodeIds, sigFilenameIter);
this becomes a dead loop since it recursively calls itself and will go all the way blow up the stack

due to the complexity of the function, I strongly recommend we revert the changes and just suppress it on the original `verifySigsAndDownloadDataFiles` method

2023-01-17 22:03 UTC, steven-sheehy approved these changes

2023-01-17 22:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                verifySigsAndDownloadDataFiles(sigFilesMap, nodeIds, sigFilenameIter);
If there's a risk we got the refactor wrong then I agree we should revert and suppress.

2023-01-17 22:04 UTC, steven-sheehy requested changes
Meant to request changes, not approve...

2023-01-17 22:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                verifySigsAndDownloadDataFiles(sigFilesMap, nodeIds, sigFilenameIter);
it's not as bad as I thought (endless recursive call): we advance the `sigFilenameIter` at the beginning of the new function, so even though it calls itself, the signature files to verify would be the next group.

however, this is still not the way we want to refactor the function because

- it makes it more difficult to understand and most likely more error-prone
- the same cognitive complexity smell still exists, just moved to the new function

2023-01-17 23:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SubscriptionResponse.java
> +    private boolean responseEncountered = false;
Done.

2023-01-17 23:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java
> +    }
Done.

2023-01-17 23:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                verifySigsAndDownloadDataFiles(sigFilesMap, nodeIds, sigFilenameIter);
Done.

2023-01-17 23:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        @SuppressWarnings("java:S6213")
Removing the suppression, so we can do this later.

2023-01-17 23:09 UTC, MarcKriguerAtHedera commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java
> +    public boolean equals(Object o) {
Undid the count move.  The equals and hashcode methods were newly-created code smells since this class inherited from an abstract class.  But Xin's suggestion to just use @Value worked even better.

2023-01-17 23:10 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                                    TransactionRecord txRecord) {
Done.  The additional 3 variables just get generated in this method (in the exact same way they are generated in the calling method).

2023-01-17 23:13 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                .until(subscriptionResponse::getMirrorHCSResponses().size() > 0);
this won't compile

```suggestion
                .until(subscriptionResponse::getMirrorHCSResponses().size() > 0);
```

2023-01-17 23:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                .until(subscriptionResponse::getMirrorHCSResponses().size() > 0);
I had accidentally deleted the leading "() ->" just after `until(` -- fixed.

2023-01-18 00:02 UTC, steven-sheehy approved these changes

2023-01-18 00:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        long consensusTimestamp = DomainUtils.timeStampInNanos(txRecord.getConsensusTimestamp());
It's already parsed.

```suggestion
        long consensusTimestamp = recordItem.getConsensusTimestamp());
```

2023-01-18 00:08 UTC, xin-hedera approved these changes
LGTM

2023-01-18 00:11 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        long consensusTimestamp = DomainUtils.timeStampInNanos(txRecord.getConsensusTimestamp());
Done.

2023-01-18 00:14 UTC, xin-hedera approved these changes

2023-01-18 00:28 UTC, merged