REST API Throw Error for invalid parameters
hashgraph/hedera-mirror-node pull request #5197
Opened 2023-01-11 18:29 UTC by edwin-greene

Signed-off-by: Edwin Greene <edwin.greene@swirldslabs.com>

**Description**:
Update the REST API to throw an error if it receives an unsupported parameter.

**Related issue(s)**:

Fixes #4607 #4575

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-01-13 17:40 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/invalid-params.json
> +      "url": "/api/v1/contracts/5001/state?order=test",
Why are we replacing limit with order here?

2023-01-17 17:49 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/contracts/{id}/state/invalid-params.json
> +      "url": "/api/v1/contracts/5001/state?order=test",
Limit is now tested on line 25; none of the old tests have been removed, but the slot tests have been condensed and a new test has been added for the invalid parameter `nonce`.

2023-01-17 23:27 UTC, steven-sheehy requested changes

2023-01-17 23:27 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  filterKeys.ENTITY_PUBLICKEY,
two public keys?

2023-01-17 23:27 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  filterKeys.TOKEN_ID,
path param

2023-01-17 23:27 UTC, steven-sheehy commented on hedera-mirror-rest/schedules.js
>  const getSchedules = async (req, res) => {
Isn't this PR missing validation of APIs without any query parameters? Shouldn't we call `utils.buildAndValidateFilters(req.query, []);` so it throws an error?

2023-01-17 23:27 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +  filterKeys.ID_OR_ALIAS_OR_EVM_ADDRESS,
path param

2023-01-17 23:27 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/cryptoAllowanceController.js
> +  filterKeys.ID_OR_ALIAS_OR_EVM_ADDRESS,
path param

2023-01-17 23:27 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +  filterKeys.TRANSACTION_TYPE
I don't think one contract result APIs have any params.

2023-01-17 23:30 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/blocks/invalid-params.json
> +          "message": "Invalid parameter: index"
We should have a separate error message to differentiate from invalid value for valid parameter and unexpected parameter. Suggest `Unknown query parameter: index`.

2023-01-18 00:13 UTC, xin-hedera requested changes

2023-01-18 00:13 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +        if (!validParameters.includes(key) || !paramValidityChecks(key, val)) {
move the `validParamters.includes(key)` check to the very beginning in the loop body so you don't have to repeat it.

2023-01-18 00:13 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +];
we need to make it a `Set` for performance, otherwise the `Array.includes` is called on every request against every query params, it may have noticeable performance impact

2023-01-18 20:52 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  constants.filterKeys.TOKEN_TYPE,
They don't all appear in the OpenApi (except for `ORDER`), but the other ones, `TIMESTAMP`, `RESULT` and `TOKEN_TYPE/type` are found in `__tests__/specs/transactions/all-params.json`:

`"url": "/api/v1/transactions?timestamp=1565779209.711927001&account.id=0.0.9&type=credit&result=success"`

I'm not sure if this test is for backward compatibility, or if the OpenApi should be updated to include those query parameters?

2023-01-18 20:55 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +  constants.filterKeys.TOKEN_TYPE,
TOKEN_TYPE should be CREDIT_TYPE, which maps to the same string.

2023-01-18 21:20 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +  filterKeys.TOKEN_ID,
There are a few tests that include `account.id` and `serialnumber`.

`__tests__/specs/tokens/{id}/nfts/all-params.json`:
`"urls": ["/api/v1/tokens/1500/nfts?serialnumber=gt:1&account.id=1001&order=desc&limit=2"]`

2023-01-18 21:54 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +  filterKeys.TRANSACTION_TYPE
It looks like just one is needed, `NONCE`. It appears in a few tests, such as: 

`__tests__/specs/contracts/results/{id}/transactionid-or-hash.json`:
`/api/v1/contracts/results/0.0.8001-167654-000123400?nonce=0`

2023-01-19 19:46 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
>    getContractResults = async (req, res) => {
Thanks I have added it.

2023-01-19 19:47 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  constants.filterKeys.TOKEN_TYPE,
Sounds good I have made this change.

2023-01-19 19:47 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +  filterKeys.TOKEN_ID,
Fixed.

2023-01-19 19:47 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +  filterKeys.TOKEN_ID,
Fixed.

2023-01-19 19:48 UTC, edwin-greene commented on hedera-mirror-rest/schedules.js
>  const getSchedules = async (req, res) => {
Great idea, I have added a call to `utils.validateReq` on all endpoints that lacked parameters, it will throw an error if a query parameter is present.

2023-01-19 19:49 UTC, edwin-greene commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +  filterKeys.ID_OR_ALIAS_OR_EVM_ADDRESS,
Fixed.

2023-01-19 19:49 UTC, edwin-greene commented on hedera-mirror-rest/controllers/cryptoAllowanceController.js
> +  filterKeys.ID_OR_ALIAS_OR_EVM_ADDRESS,
Fixed.

2023-01-19 19:49 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/blocks/invalid-params.json
> +          "message": "Invalid parameter: index"
Thanks I have made this change.

2023-01-19 19:49 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +        if (!validParameters.includes(key) || !paramValidityChecks(key, val)) {
Great idea, I have moved it.

2023-01-19 19:49 UTC, edwin-greene commented on hedera-mirror-rest/accounts.js
> +];
Thanks I have changed them to Sets.

2023-01-19 22:35 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  badParams.push(...unknownParams);
looks to me it's better to rename function param name from `validParameters` to `acceptedParameters`. since it's weird that `validateAndParseFilters` returns `invalidParams` and `unknownParams`, and `unknownParams` is determined as the params not in the `validParameters` set...

2023-01-20 15:16 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +  badParams.push(...unknownParams);
That makes sense. Thanks, I have updated the name to `acceptedParameters` here and in the various files that call these methods.

2023-01-20 17:42 UTC, xin-hedera submitted a review, later dismissed

2023-01-24 17:43 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +const validateReq = (req, acceptedParameters = new Set()) => {
Great idea, I have implemented this change.

2023-01-24 17:45 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +  filterKeys.ENTITY_PUBLICKEY,
Sounds good, I have removed `publickey`.

2023-01-24 18:23 UTC, steven-sheehy approved these changes
LGTM

2023-01-24 18:49 UTC, xin-hedera approved these changes

2023-01-24 19:04 UTC, merged