Throw correct error when multiple contract type transactions are found
hashgraph/hedera-mirror-node pull request #5242
Opened 2023-01-17 18:34 UTC by edwin-greene

Signed-off-by: Edwin Greene <edwin.greene@swirldslabs.com>

**Description**:
Instead of throwing a 500 error, throw the correct 404 error if more than one transaction is found for specific contract related transaction types.

**Related issue(s)**:

Fixes #4740 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-01-17 20:49 UTC, MarcKriguerAtHedera submitted a review, later dismissed
LGTM

2023-01-17 21:08 UTC, steven-sheehy requested changes

2023-01-17 21:08 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> -const ethereumTransactionType = TransactionType.getProtoId('ETHEREUMTRANSACTION');
Should also check for ETHEREUMTRANSACTION

2023-01-17 21:08 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +          if (transaction.type === contractCallType || transaction.type === contractCreateType) {
The logic should be inverted. The [example](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.706113-1666377820-433121761) transaction in the ticket is a SCHEDULECREATE and CRYPTOTRANSFER. So probably the best option is to find the user submitted transaction in `transactions` and throw a not found error it it's not a contract call, contract create, or ethereum transaction. A user initiated transaction should have both `nonce=0` and `scheduled=false`.

2023-01-17 21:08 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/multiple-transactions-not-found.json
> +        "type": 7
Test case should reflect the types in the ticket.

2023-01-19 21:06 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +          if (transaction.type === contractCallType || transaction.type === contractCreateType) {
Thanks I have fixed this logic.

2023-01-19 21:06 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/multiple-transactions-not-found.json
> +        "type": 7
Got it, the test case has been updated to be correct.

2023-01-19 21:07 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> -const ethereumTransactionType = TransactionType.getProtoId('ETHEREUMTRANSACTION');
Thanks I have added a check for Ethereum transactions.

2023-01-20 18:51 UTC, xin-hedera requested changes

2023-01-20 18:51 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +          if (isUserInitiatedTransaction(transaction) && !isContractTransaction(transaction)) {
I don't think we should do `isUserInitiatedTransaction`,

- contract transactions can't be scheduled -> so if transaction id + nonce = 0 maps to multiple transactions, none can be contract transactions
- the get transaction by transaction id query in the function always has a `nonce = ?` condition and defaults to 0 if not provided in the query param

We only need to check if any transaction is not a contract related transaction here.

In addition, if contract transactions ever become schedulable, additional logic is needed here to find the scheduled contract transaction and retrieve contract result,  instead of returning 404 or 500

2023-01-20 19:40 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +};
Thanks, according to the suggestion below I have removed this method.

2023-01-20 19:40 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +    true : false;
Thanks for spotting that, I have simplified it.

2023-01-20 19:41 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +          const two = !isContractTransaction(transaction);
Removed!

2023-01-20 19:41 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +          if (isUserInitiatedTransaction(transaction) && !isContractTransaction(transaction)) {
Sounds good, I have fixed it to only use `isContractTransaction`.

2023-01-23 18:21 UTC, steven-sheehy approved these changes
LGTM

2023-01-23 19:10 UTC, xin-hedera approved these changes
LGTM

2023-01-23 19:17 UTC, merged