Fixing repeatable partitions to use a case-insensitive map
hashgraph/hedera-mirror-node pull request #5247
Opened 2023-01-18 17:54 UTC by mgoelswirlds

**Description**:

This PR allows repeatable java migrations to support case insensitive keys for its  generic property map.

This PR modifies:
* Change property map to TreeMap to allow case insensitivity.

**Related issue(s)**:

Fixes #4984

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-01-18 21:47 UTC, xin-hedera requested changes

2023-01-18 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java
> +        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
should revert the above changes, instead, change `MirrorProperties.migration` to the case insensitive map.

2023-01-18 22:02 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java
> +        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
So do we want to do it for all migration and not just repeatable?

2023-01-18 22:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java
> +        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
`MirrorProperties.migration` is only used by repeatable migrations

2023-01-19 17:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java
> +        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
Should we consider having both case insensitive?

2023-01-19 18:55 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java
> +        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
So TreeMap doesn't work as is for MirrorProperties.migration, since spring is overwriting it, with its own TreeMap without the CASE_INSENSITIVE comparator. So I am working on using another type of map there. I think it might become redundant if we do it in both places right? though I am not sure why RepeatableMigration wouldn't suffice.

2023-01-19 19:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java
> +        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
I don't think it's redundant, they are both `Map<String, *>` at different levels.

One is at `hedera.mirror.importer.migration`, the other is at `hedera.mirror.importer.migration.someMigration.params`

2023-01-19 22:26 UTC, xin-hedera requested changes

2023-01-19 22:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +    private CaseInsensitiveMap<String, MigrationProperties> migration = new CaseInsensitiveMap<>();
this and the other place can be just
```suggestion
    private Map<String, MigrationProperties> migration = new CaseInsensitiveMap<>();
```

2023-01-19 22:26 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java
> +        assertThat(blockNumberMigration.getChecksum()).isEqualTo(5);
shouldn't test it here since the purposes of `checksum` test is to verify that we bump up the checksum for the `BlockNumberMigration` in the main `application.yaml` whenever we change the migration

instead, you should add this to the test `application.yaml`:

```yaml
hedera:
  mirror:
    importer:
      migration:
        DUMMYMIGRATION:
          checksum: 2 
```

and have a new integration test class in which you have an inner class `class DummyMigration extends RepeatableMigrationextends RepeatableMigration`, then have a `checksum` test to verify the checksum is correct

2023-01-19 22:29 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RepeatableMigrationTest.java
> +        CaseInsensitiveMap<String, MigrationProperties> migrationMap = new CaseInsensitiveMap<>();
need also test `MigrationProperties.params` can do case insensitive lookup

2023-01-20 20:07 UTC, xin-hedera approved these changes
LGTM

2023-01-20 20:30 UTC, edwin-greene approved these changes
Looks good to me.

2023-01-20 21:05 UTC, merged