Update PubSub RecordItemListener Configuration
hashgraph/hedera-mirror-node pull request #5276
Opened 2023-01-26 18:29 UTC by edwin-greene

Signed-off-by: Edwin Greene <edwin.greene@swirldslabs.com>

**Description**:
Update the PubSub configuration to be asynchronous which allows `PubSubRecordItemListener:sendPubSubMessage()` too easily meet a 1K tps requirement.  

**Related issue(s)**:

Fixes #2059 

**Notes for reviewer**:
This setting was performance tested with `RecordFileParserPerformanceTest` and found to support 1K transactions per second to a PubSub topic: 

![Screen Shot 2023-01-26 at 1 06 22 PM](https://user-images.githubusercontent.com/102530967/214917765-13bba8e3-2810-4d94-800b-1277f92727c3.png)

For comparison here is the current Mainnet PubSub topic performance: 

![Screen Shot 2023-01-26 at 1 07 00 PM](https://user-images.githubusercontent.com/102530967/214917893-78ff806a-38df-49b6-bab2-831ff00ceb03.png)

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-02-11 04:08 UTC, steven-sheehy requested changes

2023-02-11 04:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordParserTest.java
> +        }
We should use awaitility for this sort of wait for condition logic in tests.

2023-02-11 04:08 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +                if (retry < pubSubProperties.getMaxSendAttempts()) {
It seems like it was this way before, but this means if there's a networking issue or pubsub is down we'll just try 5 times then start discarding each message. I'm wondering if there's some other mechanism to block or if we should just retry indefinitely to avoid data loss. If we do retry indefinitely we'll need to rewrite this to not be recursive.

2023-02-13 20:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/PubSubAutoConfiguration.java
>          pubSubTemplate.setMessageConverter(new JacksonPubSubMessageConverter(new ObjectMapper()));
Thanks I have removed the `PubSubTemplate` bean and added the `JacksonPubSubMessageConverter` bean.

2023-02-13 20:33 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordParserTest.java
> +        }
Sounds good I have implemented this type of waiting with awaitility.

2023-02-13 20:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +                if (retry < pubSubProperties.getMaxSendAttempts()) {
That makes sense. For additional info with the performance testing, with loads over 10K tps for over an hour, there was never a failure and a retry.

2023-02-13 22:07 UTC, xin-hedera requested changes
just a warning log when retry fails

2023-02-13 22:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +                }
add a loud warning if retry exceeds the configured max

2023-02-13 22:20 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/pubsub/PubSubRecordItemListener.java
> +                }
Sounds good, I have updated it to log an error if it exhausts the number of retries.

2023-02-13 22:39 UTC, steven-sheehy approved these changes

2023-02-13 22:43 UTC, xin-hedera approved these changes
LGTM

2023-02-13 22:46 UTC, merged