Change the distribution column of 3 contract tables…
hashgraph/hedera-mirror-node pull request #5285
Opened 2023-01-28 04:20 UTC by MarcKriguerAtHedera

…(and primary key constraint, where appropriate).
Signed-off-by: Marc Kriguer <marc.kriguer@swirldslabs.com>

**Description**:
Change the distribution column of `contract_log`, `contract_result`, and `contract_state_change`
from `payer_account_id` to `contract_id`.  The query is unchanged, but runs ~100 times faster.

**Related issue(s)**:

Fixes #5232

**Notes for reviewer**:
Tested with EXPLAIN ANALYZE inside a `psql` session.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-02-08 23:05 UTC, xin-hedera requested changes

2023-02-08 23:05 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .record(r -> r.setContractCreateResult(r.getContractCreateResultBuilder()
revert changes in this file

2023-02-08 23:05 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-reach-max-limit.json
> +        "contract_id": 1003,
I believe you should also revert changes to this file

2023-02-08 23:05 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
not sure why the changes in this file are needed

2023-02-09 06:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                .record(r -> r.setContractCallResult(r.getContractCallResultBuilder()
Done.

2023-02-09 06:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .record(r -> r.setContractCreateResult(r.getContractCreateResultBuilder()
Done.

2023-02-09 06:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-reach-max-limit.json
> +        "contract_id": 1003,
Done.

2023-02-09 06:05 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
Changes reverted; without them (or the proper changes as you spelled out in your comments in `hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FillMissingContractInitsourceMigrationTest.java`, the tests were not passing.

2023-02-09 14:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractLog.setContractId(lookup(EntityId.of(contractResult.getContractId(), EntityType.CONTRACT), contractLoginfo.getContractID()));
stay DRY, `EntityId.of(contractResult.getContractId(), CONTRACT)` called twice in this function

2023-02-09 14:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                .record(r -> r.setContractCallResult(r.getContractCallResultBuilder()
need to revert changes in this file

2023-02-09 14:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .record(r -> r.setContractCreateResult(r.getContractCreateResultBuilder()
not reverted

2023-02-09 14:55 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-reach-max-limit.json
> +        "contract_id": 1003,
looks like none of the files with such changes are reverted

2023-02-09 14:59 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
if the changes to the rest integration test json specs are necessary, you should provide an explanation. It's difficult to review so many changes and a lot of them seem to be unnecessary at a glance, for instance, changing contract id from 1000 to 1001, changing consensus timestamp, etc.

2023-02-09 20:08 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                .record(r -> r.setContractCreateResult(r.getContractCreateResultBuilder()
The only changes to this file (now) are 4 lines where the ".returns(...)" lines have been changed to reflect that `ContractResult::getContactId` now returns a `long` instead of an `EntityId`.  All the `.record(...)` lines have been reverted.

2023-02-09 21:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractLog.setContractId(lookup(EntityId.of(contractResult.getContractId(), EntityType.CONTRACT), contractLoginfo.getContractID()));
Done.

2023-02-09 21:08 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
The explanation:  the "contractresults" now need the "contract_id" explicitly added.  In a few cases, multiple contract_ids were implicitly used for the same timestamp -- here, additional contractresults for each such timestamp needs an entry.  Any other changes were made (as little as necessary) in order to get the tests to pass again.

2023-02-10 00:54 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
The above explanation pretty much is the reason behind **all** the spec file changes.

2023-02-10 16:39 UTC, xin-hedera requested changes

2023-02-10 16:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/failed-contractcreate-eth-calldata.json
> +    "address": "0x0000000000000000000000000000000000000000",
same as the `failed-contractcreate` spec, once EntityId.toEvmAddress is fixed, revert the changes to `address` and `to`

2023-02-10 16:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-index-timestamp-range.json
> +        "logs": [],
why is the `logs` array empty?

2023-02-10 16:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1000,
I don't think the `contract_id` in the response entries have to be the same, so please check if it's possible to have `0.0.1001` as contract id in the first entry, and `0.0.1000` in the other two entries

2023-02-10 16:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-multi-params.json
> +        "contract_id": 1003,
similarly here, why do we have to change the contract id?

2023-02-10 20:09 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/failed-contractcreate.json
> +    "address": "0x0000000000000000000000000000000000000000",
Done.   Small change to entityId.test.hs to accompany the change to entityId.js.

2023-02-10 20:15 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-index-timestamp-range.json
> -      {
I had messed up the way this particular test was getting restructured.  That has been fixed, and that section is back.

2023-02-10 20:16 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-index-timestamp-range.json
> +        "logs": [],
Same reason as above -- error on how I restructured this test.  Fixed, and now the logs are back.

2023-02-10 20:30 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1000,
It's currently that way (1001 for the first entry, 1000 for second and third).  Just want to confirm that you do mean the "contractresults" entries here, and not that you want "0.0.1000" and "0.0.1001" as the contract_id values, and not the integer form without the shard number or realm number.

2023-02-10 20:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
I may not have fully understood the reason. however, the spec description says `Contracts logs api calls across many contracts with limit`. The changes here make all response entries for a single contract, as a minimum, test coverage is reduced and it may also create regression.

this is a functioinality issue we need to fix.

2023-02-10 23:33 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-multi-params.json
> +        "contract_id": 1003,
i've reverted this change.  Both v1 and v2 are consistent that each of the queries now has the following as part of the results, which does not seem correct:
```
            "transaction_hash": "0x",
            "transaction_index": null,
```
replacing what used to read:
```
            "transaction_hash": "0x9db63968721fc76815d11b0b97734669bf88ae3810e07c199924553f0548eb99",
            "transaction_index": 2,
```
which at least seems more consistent.

2023-02-11 01:05 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/no-address-with-repeated-topics.json
> +        "contract_id": 1001,
I have changed the query to specify timestamp in a range, and thus pick up both contract 1000 and contract 1001 in the results.  The v1 primary key constraint on contract_result is to only allow one contract id per timestamp value.

2023-02-11 02:00 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-multi-params.json
> +        "contract_id": 1003,
Now changed the test by the smallest feaisble amount to gete the transaction_hash and transaction_index to be valid, on both v1 and v2.

2023-02-13 15:26 UTC, xin-hedera requested changes

2023-02-13 15:26 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +        ${ContractResult.getFullName(ContractResult.CONTRACT_ID)}
we should revert it.

The contract logs query has `contract_log` table joining on `contract_result` in order to find the transaction hash and transaction index. Changing the join column to `contract_id` breaks the logic because `contract_log.contract_id` isn't always `contract_result.contract_id`, instead, it should be `contract_log.root_contract_id` pointing to the corresponding `contract_result.contract_id`.

I'm not confident that we should instead join on `contract_log.root_contract_id` = `contract_result.contract_id`.  Besides, since now we distribute these tables on column `contract_id`. The change would still cause performance issue thus require further optimization.

The ticket is about get contract result of a specific contract ID and it doesn't run this query at all. So please revert the change and re-evaluate the changes to the integration test specs. That should greatly reduce the amount of the changes in the PR.

2023-02-17 04:43 UTC, steven-sheehy commented
Closing. As discussed, please create a new PR with the reworked changes.

2023-02-17 04:43 UTC, closed without merging

2023-02-18 00:34 UTC, MarcKriguerAtHedera commented
New branch (and new PR) created.