Fix issue for handling `api/v1/contracts/call` requests from different users
hashgraph/hedera-mirror-node pull request #5311
Opened 2023-02-01 09:47 UTC by IvanKavaldzhiev

**Description**:

There is an issue that `MirrorEvmTxProcessorFacadeImpl` is created as a `Singleton` bean which causes issues when we invoke `api/v1/contracts/call` from multiple users asynchronously. The issue was reproduced by running K6 tests with multiple VUs.

The fix now creates this bean following the `Factory` scope and we get a completely new object on each separate call, thus each request now executes on its own, without disturbance.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-01 10:28 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> -import com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorFacade;
I think we can remove `MirrorEvmTxProcessorFacade` interface entirely and rename the 
`MirrorEvmTxProcessorFacadeImpl` to it.

2023-02-01 17:12 UTC, steven-sheehy requested changes

2023-02-01 17:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessFactory.java
> +                blockMetaSource, aliasManager, pricesAndFees, accountAccessor);
As discussed offline, I think `MirrorEvmTxProcessorFacadeImpl` and its dependents `AbstractCodeCache` and `HederaEvmMutableWorldState` are stateless and don't need to be recreated for every request. We only need to create a new stateful `MirrorEvmTxProcessor` on each request.

My recommendation is to remove `MirrorEvmTxProcessFactory` since it leaks Spring details and move `new MirrorEvmTxProcessor(...)` into `MirrorEvmTxProcessorFacadeImpl.execute()`

2023-02-01 21:44 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        return txnResult != null ? Optional.of(txnResult) : Optional.empty();
don't think `txResult` should ever be `null` so the optional is unnecessary. if there's bug in the controller the NPE will be caught by the exception handler and logged

2023-02-02 08:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessFactory.java
> +                blockMetaSource, aliasManager, pricesAndFees, accountAccessor);
Actually `AbstractCodeCache` is stateful, because it keeps a map for Code - `Cache<BytesKey, Code> cache;`

2023-02-02 15:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessFactory.java
> +                blockMetaSource, aliasManager, pricesAndFees, accountAccessor);
It's okay if `AbstractCodeCache` is stateful as long as it's thread safe and can be shared. Is that the case?

2023-02-02 19:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessFactory.java
> +                blockMetaSource, aliasManager, pricesAndFees, accountAccessor);
It seems it is, I changed the implementation to use a single instance of `AbstractCodeCache`

2023-02-02 22:41 UTC, steven-sheehy approved these changes
LGTM

2023-02-02 22:46 UTC, xin-hedera approved these changes
LGTM

2023-02-02 23:13 UTC, merged