remove extra spotless config
hashgraph/hedera-mirror-node pull request #5312
Opened 2023-02-01 16:58 UTC by jnels124

Signed-off-by: Jesse Nelson <jesse@swirldslabs.com>

**Description**:

Remove spotless plugin hacks fixed in latest version

**Related issue(s)**:

Fixes #5079 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-01 18:15 UTC, edwin-greene approved these changes
Looks good.

2023-02-01 20:55 UTC, steven-sheehy requested changes

2023-02-01 20:55 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +    val npmExec = when(System.getProperty("os.name".toLowerCase()).contains("windows")) {
The string is already lowercase. I think you mean to lowercase the result of getProperty():
```suggestion
    val npmExec = when(System.getProperty("os.name").toLowerCase().contains("windows")) {
```

2023-02-01 20:55 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +        true -> "/npm.cmd"
Should we use the Kotlin equivalent of Path.join() to make it path.separator agnostic?

2023-02-01 21:15 UTC, xin-hedera commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> -    }
don't think we need anything in `tasks.nodeSetup` here, so should completely remove it

2023-02-02 15:45 UTC, jnels124 commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +    val npmExec = when(System.getProperty("os.name".toLowerCase()).contains("windows")) {
oof good catch

2023-02-02 15:46 UTC, jnels124 commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> -    }
we want to skip this task if that directory already exists.

2023-02-02 15:55 UTC, jnels124 commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +        true -> "/npm.cmd"
we could do something like that but really we only have to worry about unix based and windows. Since we already have to specify the command, it doesn't really buy us much.

2023-02-02 16:01 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +        true -> "/npm.cmd"
Right, but windows uses `\` not `/` like in the PR so will it even work as is on windows? Or will `/` work on windows with the linux compatibility layer?

2023-02-02 16:03 UTC, jnels124 commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +        true -> "/npm.cmd"
/ is also a valid path on windows

2023-02-02 16:04 UTC, jnels124 commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> +        true -> "/npm.cmd"
On second thought. It is very plausible that may cause confusion. I will change this.

2023-02-02 16:05 UTC, xin-hedera commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> -    }
I think the node gradle plugin already does it

2023-02-02 16:36 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-02-02 16:37 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-02-02 16:38 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> -    }
I think it didn't do a good job and was quite slow during configuration phase, hence why I originally added the check. If I was mistaken or the performance has improved then we can remove.

2023-02-02 16:43 UTC, steven-sheehy approved these changes

2023-02-02 16:46 UTC, xin-hedera approved these changes

2023-02-02 17:04 UTC, jnels124 commented on buildSrc/src/main/kotlin/common-conventions.gradle.kts
> -    }
I did test before had to see if I could remove it, but I was not seeing the log output for the task say UP-TO-DATE. This led me to believe it wasn't caching that correctly. Verified in the code that keeping this prevents it from deleting the existing directory and unarchiving the downloaded tar/zip again. It doesn't need to redownload every time because it is in the dependency cache but will have to unarchive again.

2023-02-02 22:22 UTC, edwin-greene approved these changes

2023-02-02 22:24 UTC, mgoelswirlds approved these changes

2023-02-02 22:45 UTC, merged