Fix multiple monitor API bugs
hashgraph/hedera-mirror-node pull request #5317
Opened 2023-02-01 23:02 UTC by steven-sheehy

**Description**:

* Fix race condition in environments with multiple clusters by retrying 404
* Fix race condition in environments with multiple clusters by retrying successful calls with empty lists
* Fix `TypeError: Cannot read properties of undefined (reading 'localeCompare')` in dashboard
* Fix `ReferenceError: blockUrl is not defined`
* Increase retry maxAttempts from 2 to 4
* Remove adhoc stateproof retry in favor of centralized 404 retry

**Related issue(s)**:

Fixes #5316

**Notes for reviewer**:

Will cherry pick to `release/0.74`.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-02-01 23:52 UTC, xin-hedera requested changes

2023-02-01 23:52 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> +const getAPIResponse = async (url, key = undefined, retryPredicate = undefined) => {
can add a default noRetry predicate `const noRetry = () => false;`, then set as the default value here

```suggestion
const getAPIResponse = async (url, key = undefined, retryPredicate = noRetry) => {
```

then in `fetchWithRetry` can change to

```
      if (!retryPredicate(json)) {
        return json;
      }
```

2023-02-01 23:52 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> +const hasListItems = (jsonRespKey) => (res) => !res.hasOwnProperty(jsonRespKey) || res[jsonRespKey].length < 1;
believe the function name should be either `hasEmptyList` or `hasNoListItems`

2023-02-01 23:52 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const tokenRelationships = await getAPIResponse(url, tokensJsonRespKey, hasListItems(jsonRespKey));
```suggestion
  const tokenRelationships = await getAPIResponse(url, tokensJsonRespKey, hasListItems(tokensJsonRespKey));
```

2023-02-01 23:52 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/monitor_apis/token_tests.js
> +  let balances = await getAPIResponse(url, tokenBalancesJsonRespKey, hasListItems(jsonRespKey));
```suggestion
  let balances = await getAPIResponse(url, tokenBalancesJsonRespKey, hasListItems(tokenBalancesJsonRespKey));
```

2023-02-02 01:41 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
> +  const tokenRelationships = await getAPIResponse(url, tokensJsonRespKey, hasListItems(jsonRespKey));
Thanks. That's what I get for doing last minute refactoring.

2023-02-02 01:41 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> +const hasListItems = (jsonRespKey) => (res) => !res.hasOwnProperty(jsonRespKey) || res[jsonRespKey].length < 1;
Renamed to hasEmptyList

2023-02-02 01:41 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/utils.js
> +const getAPIResponse = async (url, key = undefined, retryPredicate = undefined) => {
Done

2023-02-02 01:41 UTC, steven-sheehy commented on hedera-mirror-rest/monitoring/monitor_apis/token_tests.js
> +  let balances = await getAPIResponse(url, tokenBalancesJsonRespKey, hasListItems(jsonRespKey));
Fixed

2023-02-02 01:50 UTC, xin-hedera approved these changes
LGTM

2023-02-02 14:59 UTC, edwin-greene approved these changes
Looks good

2023-02-02 15:34 UTC, merged