Add contract call performance tests
hashgraph/hedera-mirror-node pull request #5326
Opened 2023-02-02 18:26 UTC by mustafauzunn

**Description**:

K6 performance tests for api/v1/contracts/call REST API invoking different types of pure/view solidity functions.

**Related issue(s)**:

Fixes #5320 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-02 22:51 UTC, steven-sheehy requested changes

2023-02-02 22:51 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/index.js
> -const tests = {ethBlockNumber};
Please remove the now unused `ethBlockNumber.js` and `common.js`

2023-02-02 22:51 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/index.js
> +import * as ethCallIdentifier from './ethCallIdentifier.js';
Name these all as `contractCall...js` to match the endpoint name. Same thing for scenario name and other strings in PR. `s/eth/contract/g`

2023-02-02 22:51 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/ethCallSender.js
> +  "to":String(contract),
Should we have one with `from` populate to a payable?

2023-02-03 16:57 UTC, xin-hedera requested changes

2023-02-03 16:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/contractCallBalance.js
> +const contract = __ENV.DEFAULT_CONTRACT_ADDRESS
nit

```suggestion
const contract = __ENV.DEFAULT_CONTRACT_ADDRESS;
```

2023-02-03 16:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/contractCallBalance.js
> +});
```suggestion
const payload = JSON.stringify({
  to: `${contract}`,
  data: '0x6896fabf',
});
```
can run `./gradlew test:spotlessJavascriptApply` to fix most format issues

2023-02-03 16:57 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/contractCallBalance.js
> +};
this is required for every web3 test, so we should have a function in `common.js`

```
const jsonPost = (url, payload) => http.post(url, payload, {
  headers: {
    'Content-Type': 'application/json',
  }
});
}
```

2023-02-03 17:20 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/index.js
> -const tests = {ethBlockNumber};
I don't see `ethBlockNumber.js` deleted. Did you push this change?

For `common.js`, you're right we should keep except we need to change its implementation to not look at jsonrpc fields.

2023-02-06 11:28 UTC, IvanKavaldzhiev approved these changes
LGTM! I agree with the existing comments.

2023-02-06 16:43 UTC, xin-hedera approved these changes
LGTM

2023-02-06 16:54 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/common.js
> +const errorField = 'error';
Remove json-rpc `error` field and check since it's no longer applicable.

2023-02-07 15:41 UTC, merged