05231 optimize contract by
hashgraph/hedera-mirror-node pull request #5327
Opened 2023-02-02 18:46 UTC by mgoelswirlds

**Description**:
Citus (V2) optimize get contract by id query.

This PR modifies:
- Splits the original contract by ID to separately query the contracts and the file data table.

**Related issue(s)**:

Fixes #[5231](https://github.com/hashgraph/hedera-mirror-node/issues/5231)

**Notes for reviewer**:

This PR splits the original query to remove existing ctes and query the contracts table. Then get the results from the first query and further query the file_data table.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-02 23:53 UTC, xin-hedera requested changes

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +import {encode} from "qs/lib/utils.js";
what's this import for?

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
>      ].join('\n'),
the whole query here should be just:

`query: tableUnionQueries.join('\n'),`

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +const getFileBytecodeQuery = (timestampParam, fileIdParam) => {
the whole function should go to `FileDataService` and generalize it as `FileDataService.getFileData(fileId, timestamp)`. The function should return the query and params to get the active file content for the `fileId` at the provided consensus timestamp.

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +         ${FileData.getFullName(FileData.ENTITY_ID)} = ${fileIdParam}
should not directly reference the param here, instead, use positional parameter, and pass the values in a params array

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    const contractRows = rows;
```suggestion
    const contract = rows[0];
```

and use it hereafter.

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      console.log(`The fileRows is ${rows}`);
remove the debug log

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +        throw new NotFoundError();
don't throw error, partial mirror node may not have the file data at all.

instead, if no file data exists, just return empty bytecode in the response

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      getContractByIdOrAddressQuery: getContractByIdOrAddressContractEntityQuery,
```suggestion
     getContractByIdOrAddressContractEntityQuery,
```

and change references in other modules

2023-02-02 23:53 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      }).join('');
```suggestion
      contract.bytecode = contract.bytecode.toString('hex');
```

2023-02-02 23:53 UTC, xin-hedera commented
what's the k6 perf test result?

2023-02-03 04:24 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      }).join('');
or just do `encode(initcode, 'hex')` in SQL

2023-02-03 14:23 UTC, mgoelswirlds commented
k6 perf has highly improved.
This is the old v2 results.
<img width="1454" alt="oldV2" src="https://user-images.githubusercontent.com/106084778/216626868-aead94f7-dd86-43ad-be32-ec5365a47766.png">

The new v2 results:
<img width="1060" alt="New Image with V2" src="https://user-images.githubusercontent.com/106084778/216626997-cdee788a-32a1-48f4-a25b-0bbc81bd7b24.png">

2023-02-03 17:00 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +      ].join('\n'),
move the whole query into a const string, and it really doesn't need the `[].join()` since it's just a single string

2023-02-03 17:08 UTC, xin-hedera requested changes

2023-02-03 17:08 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    if(_.first(rows).file_id !== null) {
```suggestion
    if(contract.file_id !== null) {
```

2023-02-03 17:08 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +           ) bytecode
```suggestion
           ) data
```

since the function now is not just for contract bytecode, change the `bytecode` reference in `contractController` as well

2023-02-03 21:10 UTC, xin-hedera requested changes

2023-02-03 21:10 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +      ].join('\n'),
a couple of things are still missed / misunderstood

- there is still `[].join()`
- move it to a const string outside the function
- I mentioned removing `FileData.getFullName` and `FileData.tableAlias`, but not that you removed all `FileData.{columnName}` references

2023-02-03 21:10 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +
revert the extra new line

2023-02-03 21:12 UTC, mgoelswirlds commented on hedera-mirror-rest/service/fileDataService.js
> +      ].join('\n'),
Ughh I had removed it . and it got added back. sorry about that. will remove it.

2023-02-03 21:25 UTC, mgoelswirlds commented on hedera-mirror-rest/service/fileDataService.js
> +      ].join('\n'),
Corrected it.

2023-02-06 17:07 UTC, xin-hedera requested changes

2023-02-06 17:07 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      contract.bytecode = contract.initcode.toString('hex');
`file_id` and `initcode` can both be null. we also need a integration test

```suggestion
      contract.bytecode = contract.initcode?.toString('hex');
```

2023-02-06 18:23 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      contract.bytecode = contract.initcode.toString('hex');
Please let the reviewer resolve their own conversations. As Xin notes not all items were addressed so it's important they double check things before resolving.

2023-02-06 18:30 UTC, mgoelswirlds commented on hedera-mirror-rest/controllers/contractController.js
> +      contract.bytecode = contract.initcode.toString('hex');
I did not resolve it. I did commit the suggestion which auto resolved it. And I am adding an integration test now.

2023-02-06 19:32 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      contract.bytecode = contract.initcode.toString('hex');
learned a new trick 🤣

2023-02-06 23:38 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-02-07 04:24 UTC, steven-sheehy requested changes

2023-02-07 04:24 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      }
Push this logic into `FileDataService.getFileData()` so that it can use `super.getRows()` and so that `getFileData()` can be true to its name and return file data and not just a SQL query. Return the bytes instead of a rows array.

2023-02-07 04:24 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +    if(contract.file_id !== null) {
nit: Formatting

2023-02-07 19:05 UTC, steven-sheehy approved these changes
LGTM

2023-02-07 19:16 UTC, xin-hedera approved these changes
LGTM

2023-02-07 19:18 UTC, merged