Add gas per second metrics support
hashgraph/hedera-mirror-node pull request #5360
Opened 2023-02-09 09:52 UTC by IvanKavaldzhiev

**Description**:

Add custom metrics for gas per second inside web3 module. The metric is exposed to `MetricRegistry` under this name - `hedera_mirror_web3_call_gas`

**Related issue(s)**: #5052 

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-09 17:28 UTC, steven-sheehy requested changes

2023-02-09 17:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/GasPerSecondMetrics.java
> +        Gauge.builder("hedera.mirror.web3.call.gas", gasPerSecond, GasPerSecond::getAccumulatedGas) //
Are there any tags we should add to differentiate different types of EVM calls? At least we should have estimate vs not estimate calls. Anything else?

Note that if we have dynamic tags we have to use a concurrent map to lazy create them. See `Downloader.nodeSignatureStatusMetricMap` for an example.

2023-02-09 17:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/GasMetricsHederaTracer.java
> +}
But the above is probably too slow to do per operation. Instead, we should move the above counter to `ContractCallService` and `counter.increment(hederaEvmTransactionProcessingResult.getGasUsed())`.

2023-02-10 14:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/GasPerSecondMetrics.java
> +        Gauge.builder("hedera.mirror.web3.call.gas", gasPerSecond, GasPerSecond::getAccumulatedGas) //
Changed to Counter.

2023-02-10 14:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/GasPerSecondMetrics.java
> +        Gauge.builder("hedera.mirror.web3.call.gas", gasPerSecond, GasPerSecond::getAccumulatedGas) //
That's a great idea! Due to the limited time-frame, I suggest enhancing the custom metric with these dynamic tags next sprint.

2023-02-10 15:19 UTC, steven-sheehy requested changes
LGTM

2023-02-10 21:31 UTC, david-bakin-sl approved these changes
LGTM! (have to look at this micrometer library later, it's not used in hedera-services, looks easy though!)

2023-02-10 21:36 UTC, steven-sheehy approved these changes
LGTM

2023-02-10 21:41 UTC, merged