Misc fixes
hashgraph/hedera-mirror-node pull request #5361
Opened 2023-02-09 10:04 UTC by IvanKavaldzhiev

**Description**:

Several issues were indentified in the custom evm related logic in web3 module. This PR fixes:
1. Fix order of binding custom op codes - currently the custom op codes were not taken into account and the besu internal implementations were used instead
2. Change EVM version from `0.32` to `0.34`
3. Fix `MirrorEntityAccess.isUsable` implementation. In the corresponding services implementation we check whether a given account is expired. We don't keep this information on mirror-node side, so we should always return `true`.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-09 16:18 UTC, steven-sheehy requested changes

2023-02-09 16:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +    //in mirror-node side, so we should always return true.
We actually mimic the behaviour [here](https://github.com/hashgraph/hedera-services/blob/ac9d19c615dfbbd9d3876cfe1fcb017373fb6ae6/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/StaticEntityAccess.java#L130). But still probably we can keep the 1. and 2. checks. I think 3. makes sense in combination with 4. Since one of the bugs was that trying to use an entity with no balance resulted in NPE later in the execution, which don't seem correct.

2023-02-09 16:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +    //in mirror-node side, so we should always return true.
Almost all of the above fields can be null. Check the database schema to confirm and handle nulls. Keep in mind mirror nodes can be partial mirror nodes and may have missed the create or update transaction that would've set some of these.

2023-02-09 16:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private String evmVersion = "v0.34";
It's a property pointing to the dynamically chosen EVM version (usually the latest version). In the future we would continue changing it with accordance to our needs. For `eth_call` and `eth_estimateGas` I believe it would be the latest, but for the `eth_debug` RPC requests we may need to replay a transaction using a specific older evm version, aligned with the transaction's timestamp.

2023-02-10 01:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private String evmVersion = "v0.34";
So seems like we should do as I recommend until such time that we implement an `eth_debug` in order to avoid bugs with forgetting to update two places and to not repeat ourselves? Won't hold up the PR for this though.

2023-02-10 02:13 UTC, steven-sheehy requested changes

2023-02-10 02:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +            if((expirationTimestamp != null && expirationTimestamp <= currentTime) ||
It'd probably be cleaner to separate expiration timestamp check and createdTimestamp + autorenewperiod into separate if statements.

2023-02-10 02:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/AccountAccessorImpl.java
> +            final var entityFoundByAlias = entityRepository.findByEvmAddressAndDeletedIsFalse(addressOrAlias.toArray());
Avoid the extra allocation.

```suggestion
        var addressBytes = addressOrAlias.toArrayUnsafe();
        if (!isMirror(addressBytes)) {
            final var entityFoundByAlias = entityRepository.findByEvmAddressAndDeletedIsFalse(addressBytes);
```

2023-02-10 15:42 UTC, steven-sheehy approved these changes
LGTM

2023-02-10 15:45 UTC, merged