Addинг rate limit capabilities for eth_call
hashgraph/hedera-mirror-node pull request #5363
Opened 2023-02-09 15:38 UTC by nikolovyanko

Adding `Bucket4J` rate limit capabilities to `ContractController` using `100` requests per second as initial value. The property is configurable and could be customized additionally.

**Related issue(s)**: #5051

2023-02-10 15:03 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        if(bucketProvider.getBucket().tryConsume(1)) {
disclaimer: not familiar with bucket4j, but I don't think the bucket limit will work. here for every `/call` request, a new bucket is created by `getBucket`. The test case however returns the same bucket object so  `exceedingRateLimit` can pass.

2023-02-10 15:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        if(bucketProvider.getBucket().tryConsume(1)) {
have you checked this example? https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/blob/master/bucket4j-spring-boot-starter-example-webflux/src/main/resources/application.yml

it requires a third party spring integration, however, with that, we should be able to apply limit by configuration only

2023-02-12 11:16 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        if(bucketProvider.getBucket().tryConsume(1)) {
Using this `application.yml` approach sounds like a great idea. We can try it out.

Regarding your first concern, I believe we can create a common single bucket in the Controller constructor and in this way we won't create new bucket for each request. So it seems we have at leas 2 solutions.

2023-02-13 15:59 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        if(bucketProvider.getBucket().tryConsume(1)) {
Took the second approach.

2023-02-13 17:07 UTC, xin-hedera requested changes

2023-02-13 17:07 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/BucketProvider.java
> +        }
it's not multi-thread safe that two concurrent requests can still get different `Bucket` objects. Instead, since we only have a global bucket limit, this should go to a `@Configuration` class and we can create a singleton bucket bean there.

2023-02-14 17:12 UTC, steven-sheehy requested changes

2023-02-14 17:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int rateLimitPerSecond = 100;
In mirror node we use higher level types that allow flexibility for different units.
```suggestion
    @NotNull
    @DurationMin(seconds = 100)
    private Duration rateLimit = Duration.ofSeconds(100L);
```

2023-02-14 17:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int rateLimitPerSecond = 100;
Add to `docs/configuration.md`. Also double check any other props in this file are present.

2023-02-14 17:43 UTC, xin-hedera requested changes

2023-02-14 17:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/RateLimitConfiguration.java
> +        final var limit = Bandwidth.classic(rateLimitPerSecond, Refill.greedy(10, Duration.ofSeconds(1)));
Does this actually limit the rate to 10 rps and allow a burst of rateLimitPerSecond in case rateLimitPerSecond > 10?

My understanding is, if we want to have a rate limit per the configure, it should be:

```suggestion
        final var limit = Bandwidth.classic(rateLimitPerSecond, Refill.greedy(rateLimitPerSecond, Duration.ofSeconds(1)));
```

2023-02-15 10:10 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/RateLimitConfiguration.java
> +        final var limit = Bandwidth.classic(rateLimitPerSecond, Refill.greedy(10, Duration.ofSeconds(1)));
Hey, At first the refill rate of tokens was with the `rateLimitPerSecond`(100), but when measuring the performance we noticed that the RPS is often above 100 (there were values of 258+ RPS). With the change from 100 to 10 the RPS measure never gets above 99. The measure is done thru the existing k6 tests.

2023-02-15 14:59 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/RateLimitConfiguration.java
> +        final var limit = Bandwidth.classic(rateLimitPerSecond, Refill.greedy(10, Duration.ofSeconds(1)));
no idea why perf tests show the numbers you mentioned. however, this is [the official doc](https://bucket4j.com/7.6.0/toc.html#limiting-the-rate-of-access-to-rest-api). in the example

```java
    private Bucket createNewBucket() {
         long overdraft = 50;
         Refill refill = Refill.greedy(10, Duration.ofSeconds(1));
         Bandwidth limit = Bandwidth.classic(overdraft, refill);
         return Bucket.builder().addLimit(limit).build();
    }
```

This is for a throttle of 10 calls/sec with a short period burst controlled by the `overdraft`

2023-02-15 17:44 UTC, steven-sheehy approved these changes
LGTM outside of Xin's concerns

2023-02-15 17:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/RateLimitConfiguration.java
> +        final var limit = Bandwidth.classic(rateLimitPerSecond, Refill.greedy(10, Duration.ofSeconds(1)));
Perhaps just switch to `Bandwidth.simple()` if we don't understand the harder to use classic mode?

2023-02-15 17:54 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/RateLimitConfiguration.java
> +        final var limit = Bandwidth.classic(rateLimitPerSecond, Refill.greedy(10, Duration.ofSeconds(1)));
agree, especially if we don't think burst / overdraft is required, `simple()` is just

```
    public static Bandwidth simple(long capacity, Duration period) {
        Refill refill = Refill.greedy(capacity, period);
        return classic(capacity, refill);
    }
```

2023-02-16 14:26 UTC, xin-hedera approved these changes
LGTM

2023-02-16 15:08 UTC, merged