05328 rosetta show general operation status
hashgraph/hedera-mirror-node pull request #5364
Opened 2023-02-09 18:52 UTC by mgoelswirlds

**Description**:
Adding a general operational status to accomodate HAPI response codes not handled.

This PR modifies ... in order to support ...
* Add GENERAL_ERROR status to support HAPI response codes not handles in TransactionResults.

**Related issue(s)**:

Fixes #5328

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-10 15:41 UTC, xin-hedera requested changes

2023-02-10 15:41 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants.go
> +	GeneralStatus   = "GENERAL_ERROR"
```suggestion
	generalErrorStatus   = "GENERAL_ERROR"
```

symbols starting with uppercase letter is public in go, we don't want to make `generalStatus` public

also change `TransactionResults` to private,  i.e., `transactionResults`. then add the function `GetTransactionResult` here instead in `persistence/transaction.go`

2023-02-10 15:41 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> +func getTransactionResult(transaction *transaction) interface{} {
this function should move to types/constants.go, and the prototype should be
```suggestion
func GetTransactionResult(int32 code) string {
```

we know it always returns a `string`, so shouldn't use the generic empty `interface{}`

2023-02-10 15:42 UTC, xin-hedera commented
please merge changes from `main` for the hedera-protobufs-go bump and new response codes

2023-02-11 03:55 UTC, steven-sheehy approved these changes
LGTM

2023-02-13 15:47 UTC, xin-hedera approved these changes
LGTM

2023-02-13 16:24 UTC, merged