Add graphql helm chart
hashgraph/hedera-mirror-node pull request #5380
Opened 2023-02-10 21:10 UTC by jnels124

**Description**:

This PR adds a graphql helm chart
* Add postman.json for smoke test
* Update chart docs to include graphql example

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-14 15:07 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +    expr: sum(rate(graphql_datafetcher_seconds_count{application="hedera-mirror-graphql", outcome="ERROR"}[5m])) by (namespace, pod, path) / sum(rate(graphql_datafetcher_seconds_count{application="he
Broke this down by path but maybe we don't want this grouping?

2023-02-14 15:08 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +    enabled: false
not in prod use so disabled

2023-02-14 15:10 UTC, jnels124 commented on charts/hedera-mirror/ci/default-values.yaml
> +
remove

2023-02-14 15:10 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    echo "I am executing this script"
remove

2023-02-14 15:10 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    echo "I finished executing the script"
remove

2023-02-14 15:12 UTC, jnels124 commented on gradle.properties
> +dockerRegistry=docker.io/jesseswirldslabs
fix

2023-02-14 15:13 UTC, jnels124 commented on hedera-mirror-graphql/src/main/resources/graphql/.graphqlconfig
> +{
remove file

2023-02-14 15:13 UTC, jnels124 commented on hedera-mirror-test/k6/src/rest/test/index.js
>    accountsBalanceGt0,
revert

2023-02-16 05:21 UTC, steven-sheehy requested changes

2023-02-16 05:21 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/values.yaml
> +        requestHost: true
Let's remove this middleware for now

2023-02-16 05:21 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/values.yaml
> +    expr: sum(rate(graphql_datafetcher_seconds_count{application="hedera-mirror-graphql", outcome="ERROR"}[5m])) by (namespace, pod, path) / sum(rate(graphql_datafetcher_seconds_count{application="he
Think we want to catch errors common to all data fetchers faster instead of requiring one path to reach 5% before alerting. So probably better to remove path.

2023-02-16 05:21 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/values.yaml
> +      summary: "Mirror graphql API memory usage exceeds 80%"
nit: Name it as `GraphQL` in all descriptions and summaries.

2023-02-16 05:21 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/values.yaml
> +    enabled: false
I think we can keep it enabled since it's just a warning and will not trigger any alerts that wake anyone up.

2023-02-16 05:21 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/values.yaml
> +  defaultAccount: 98
This seems to be unused. Not sure we need to customize this often.

2023-02-16 17:29 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +    expr: sum(rate(graphql_datafetcher_seconds_count{application="hedera-mirror-graphql", outcome="ERROR"}[5m])) by (namespace, pod, path) / sum(rate(graphql_datafetcher_seconds_count{application="he
makes sense. Done

2023-02-16 17:30 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +    enabled: false
done

2023-02-16 17:30 UTC, jnels124 commented on charts/README.md
> +- [Hedera Mirror GRAPHQL API](hedera-mirror-graphql)
done

2023-02-16 17:30 UTC, jnels124 commented on charts/README.md
> +To access the GraphQL API:
done

2023-02-16 17:30 UTC, jnels124 commented on charts/hedera-mirror-graphql/postman.json
> +                "query": "{\n  account(input: \n    {id: \"azAZ0123456789+/=\"}) {\n    alias\n    autoRenewPeriod\n    autoRenewAccount {\n        alias\n        deleted\n        entityId {\n
done

2023-02-16 17:30 UTC, jnels124 commented on charts/hedera-mirror-graphql/templates/hpa.yaml
> +apiVersion: autoscaling/v2beta2
done

2023-02-16 17:31 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +        requestHost: true
done. Assuming you only wanted the rate limit removed

2023-02-16 17:33 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +      summary: "Mirror graphql API memory usage exceeds 80%"
done

2023-02-16 17:34 UTC, jnels124 commented on charts/hedera-mirror-graphql/values.yaml
> +  defaultAccount: 98
It is used now. It is needed for the CI environment because that account doesn't exist.

2023-02-16 20:20 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/values.yaml
> +  defaultAccount: 98
No, I missed that it was passed in the pod args. Looks fine.

2023-02-16 20:23 UTC, steven-sheehy approved these changes
LGTM just some sorting nitpicks

2023-02-16 20:23 UTC, steven-sheehy commented on charts/marketplace/gcp/values.yaml
> +graphql:
nit: sort inline

2023-02-16 20:23 UTC, steven-sheehy commented on charts/hedera-mirror/ci/citus-values.yaml
> +graphql:
nit: Sort inline

2023-02-16 20:23 UTC, steven-sheehy commented on charts/hedera-mirror/ci/default-values.yaml
> +graphql:
nit: Sort inline

2023-02-17 01:33 UTC, jnels124 commented on charts/marketplace/gcp/values.yaml
> +graphql:
fixed

2023-02-17 01:33 UTC, jnels124 commented on charts/hedera-mirror/ci/citus-values.yaml
> +graphql:
fixed

2023-02-17 01:33 UTC, jnels124 commented on charts/hedera-mirror/ci/default-values.yaml
> +graphql:
fixed

2023-02-17 01:34 UTC, steven-sheehy submitted a review, later dismissed

2023-02-17 17:04 UTC, xin-hedera reviewed
just one typo

2023-02-17 17:11 UTC, jnels124 commented on charts/hedera-mirror/templates/application.yaml
> +      {{- if .Values.rest.enabled -}}
fixed

2023-02-17 17:26 UTC, steven-sheehy approved these changes

2023-02-17 17:26 UTC, xin-hedera approved these changes

2023-02-20 00:43 UTC, steven-sheehy commented
Can just disable graphql helm tests in CI

2023-02-22 13:40 UTC, xin-hedera approved these changes

2023-02-22 16:40 UTC, steven-sheehy approved these changes

2023-02-22 17:05 UTC, merged