Add dynamic tag for the custom gas per second metrics
hashgraph/hedera-mirror-node pull request #5398
Opened 2023-02-13 11:25 UTC by IvanKavaldzhiev

**Description**:

Enhance `hedera_mirror_web3_call_gas` custom metrics to have dynamic tag differentiating different gas usage for the different calls. Currently we have 3 type of calls:

- ETH_CALL
- ETH_ESTIMATE_GAS
- ERROR

**Related issue(s)**:

Fixes #5397 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-13 15:03 UTC, steven-sheehy requested changes

2023-02-13 15:03 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                gasPerSecondCounter.increment(txnResult.getGasUsed());
Can move to a more generic listener method to stay DRY:

```suggestion
            if (!txnResult.isSuccessful()) {
                onCompleted(body, txnResult);
```

```java
private void onCompleted(CallServiceParameters body, HederaEvmTransactionProcessingResult result) {
    var counter = gasPerSecondMetricMap.get(body.getCallType());
    counter.increment(result.getGasUsed());
}
```

2023-02-13 15:53 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        metricTypes.forEach(t -> gasPerSecondMetricMap.put(t, newGasPerSecondMetric(t)));
except for `ERROR` enum - though it probably doesn't hurt to have an extra unused metric hanging around?  Unless it is serialized as a bunch of zeros on every sample ...

2023-02-14 15:33 UTC, steven-sheehy requested changes

2023-02-14 15:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        final var callType = request.isEstimate() ? ETH_ESTIMATE_GAS : ETH_CALL;
nit: Seems like this logic should go into `constructServiceParameters`

2023-02-14 15:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        assertThat(contractCallService.processCall(serviceParameters)).isEqualTo(successfulReadResponse);
For each test, we need to verify the metric exists and is incremented. See `PublishMetricsTest` for an example. Use `meterRegistry.find(name).counters()` then assert on it. Use `meterRegistry.clear()` between tests to reset counts.

2023-02-14 15:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
>  @RequiredArgsConstructor(onConstructor = @__(@Autowired))
We need to add a simple in memory registry to test in integration tests. Add the below to `IntegrationTestConfiguration`:

```java
    @Bean
    MeterRegistry meterRegistry() {
        return new SimpleMeterRegistry();
    }
```

2023-02-14 15:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/CallServiceParameters.java
> +@Data
I think we should revert this change so it stays immutable. Better to just change `onComplete()` to check `result.isSuccessful()` or pass `CallType` instead of body.

2023-02-14 15:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        gasPerSecondMetricMap = new EnumMap<>(CallType.class);
`EnumMap` is nice, but can we wrap it in `Collections.unmodifiableMap()` at the end before assigning to `gasPerSecondMetricMap`?

2023-02-14 18:51 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        Arrays.stream(CallType.values()).toList().forEach(type ->
nit:
```suggestion
        Arrays.stream(CallType.values()).forEach(type ->
```

2023-02-14 18:55 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                onComplete(body, txnResult);
nit, can fold the `CallType.ERROR` logic into `onComplete` and simplify the flow here.

2023-02-15 16:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        assertThat(contractCallService.processCall(serviceParameters)).isEqualTo(successfulReadResponse);
To do assert on the concrete value we should expose a getter method in `ContractCallService` that returns the `gasUsed` field from `HederaEvmTransactionProcessingResult`. This method would be used only for testing purposes and we can put `@VisibleForTest` or similar annotation. If you are OK with adding this getter method, we can enhance additionally the tests.

2023-02-15 16:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        assertThat(contractCallService.processCall(serviceParameters)).isEqualTo(successfulReadResponse);
Currently I have added checks for positive value only.

2023-02-15 20:31 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        assertThat(contractCallService.processCall(serviceParameters)).isEqualTo(successfulReadResponse);
Just that it was incremented should be sufficient. I don't like making things visible for testing.

2023-02-15 20:31 UTC, steven-sheehy approved these changes
LGTM

2023-02-15 20:33 UTC, xin-hedera approved these changes
LGTM

2023-02-15 20:34 UTC, merged