Implement creating of synth events for HAPI transactions
hashgraph/hedera-mirror-node pull request #5402
Opened 2023-02-13 16:01 UTC by georgi-l95

**Description**:
Adds SynthEventService, which handles event logging for token transfers, token mint, token burn, token wipe and approvals. Only support fungible token transfers with no more than one sender.
All token transfers (fungible and non fungible) are handled with one method.
Mint/Wipe/Burn are handled each one in separate methods.
ApprovalForAll and Approval are handled each one in separate methods.

**Related issue(s)**:

Fixes #4738 

**Notes for reviewer**:
Main goal for my changes was performance. Therefore I've added some logic in the `EntityRecordItemListener`, to avoid adding any additional loops.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-14 01:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> + * Copyright (C) 2019 - 2022 Hedera Hashgraph, LLC
nit: here and in any new file
```suggestion
 * Copyright (C) 2019 - 2023 Hedera Hashgraph, LLC
```

2023-02-14 01:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        boolean isContract = recordItem.getTransactionRecord().hasContractCallResult() || recordItem.getTransactionRecord().hasContractCreateResult();
Pull the `isContract` check out as it's done multiple times.

2023-02-14 01:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +    private final String transferSigniture = "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";
nit: here and below
```suggestion
    private final String transferSignature = "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";
```

2023-02-14 01:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        byte[] data = hexToByte(padLeftZeros(Long.toHexString(amount)));
Logic for transforming the inputs to create `data`, `topic0`, `topic1` and `topic2` seems similar.
Why not update `processLog` or create a `processHTSEvent()` that takes in the string forms and defines the logic once to perform all the `hexByte` and `padLeftZeros`.

Should reduce the file size and make it easier to read

2023-02-14 01:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +    private byte[] hexToByte(String hex) {
`hexToByte()` and `padLeftZeros()` seem like utility function that should be pulled out (maybe into Utility.java`) and tested

2023-02-14 01:36 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (serialNumbersCount <= 0) {
nit: add a comment here for this scenario of a negative serialNumber Count

2023-02-15 09:30 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> + * Copyright (C) 2019 - 2022 Hedera Hashgraph, LLC
Fixed.

2023-02-15 09:30 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        boolean isContract = recordItem.getTransactionRecord().hasContractCallResult() || recordItem.getTransactionRecord().hasContractCreateResult();
Fixed.

2023-02-15 09:31 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        byte[] data = hexToByte(padLeftZeros(Long.toHexString(amount)));
Fixed.

2023-02-15 09:31 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +    private byte[] hexToByte(String hex) {
Fixed.

2023-02-15 09:31 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (serialNumbersCount <= 0) {
Fixed.

2023-02-17 01:31 UTC, Nana-EC reviewed
LG, will circle back again.

2023-02-17 18:52 UTC, david-bakin-sl reviewed
I've left a lot of comments - but, for now, withhold approval.  I don't request _any_ changes (no obvious bugs found: that's my bar for requesting changes) but suggest that you look through my comments and say aye or nay, according to your own (personal) coding standard and engineering ideas.  _Then_ I'll approve.

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            logIndex = insertFungibleTokenTransfers(
This business in this method of piping the `logIndex` around so it can get incremented makes me think that it should be encapsulated _within_ `SynthEventServiceImpl`.  That class can increment it appropriately.  And if it did that, it wouldn't be crufting up the method signatures either, passing the thing around all the time.  And after all, who'd know better what the index was than that class which is actually emitting all the logs?

Looking over this entire PR it seems like each new instance of `SynthEventServiceImpl` is associated with the `logIndex` starting over at 0.

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                synthEventService.processTokenWipe(recordItem, tokenId, tokenWipeAccountTransactionBody.getAmount(), 0);
Here we are again where sometimes the wipe method takes an amount and sometimes a serial number ...

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +        int logIndex = recordItem.getTransactionBody().getCryptoApproveAllowance().getNftAllowancesCount() + 1;
This is the only place I see where the `logIndex` starts at something other than `0` - and I also don't know why.  Why?

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            synthEventService.processApproveForAllAllowance(recordItem, ownerId.getId(), 0, tokenId, 0, i);
One more nice thing about encapsulating the `logIndex` inside of the `synthEventServiceImpl` is that we wouldn't have to pass bare `i` variables in to the methods.  And then you have to go look and see what the `i` is all about...

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        while (sb.length() < length - inputString.length()) {
I myself prefer to initialize the `StringBuilder` with a string of the full-width of '0' and then chop it down to size with `setLength` but really it doesn't matter.  (At which point you might as well use `String.substring()` on a string literal of the right number of '0' and then `+` it with the input, the compiler will do everything else for you.)

But, seriously, it doesn't matter.

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +    public static byte[] hexToByte(String input) {
How can it possibly be that these methods don't exist somewhere else (with their tests)?

In fact, how about replacing this with a reasonable use of [`HexFormat.parseHex()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/HexFormat.html#parseHex(java.lang.CharSequence))?

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/TransactionSignatureTest.java
> +    private SynthEventService synthEventService;
I don't actually see any changes in any of these tests that actually test that the syntheventserviceimpl is working right.  

_In particular_ there are no tests for `logIndex`.  Yet _another_ reason that should be encapsulated in the class itself!

Plus I guess no tests that the _right_ thing is being logged, serial number or amount or whatever ...

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        assertThat(Utility.hexToByte(address3)).isEqualTo(new byte [] { -116, 91, -31, -27, -21, -20, 125, 91, -47, 79, 113, 66, 125, 30, -124, -13, -35, 3, 20, -64, -9, -78, 41, 30, 91, 32, 10, -56,
As tests go this is somewhat unsatisfying.  But I guess it will never break, so nobody will ever have to look at it.  

(Imagine code just like this in 1000000 codebases around the world, and now try to figure out why it took Java 20+ years to come up with the `HexFormat` class? Jeez.)

2023-02-17 18:52 UTC, david-bakin-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SynthEventServiceImplIntegrationTest.java
> +package com.hedera.mirror.importer.domain;
A lot of testing effort here ... but I'm not looking at it.  Sorry!  But I can't then assess whether it is complete or not, as you realize.

But after one glance: It sure seems like a _lot_ of work to set things up for tests though.  Normally I really dislike tests with mocks, but maybe this test is the exception ...?  Surely all this setup isn't needed for just the few fields that the HAPI transactions look at?

Perhaps a different approach would be to provide a _spy_ implementation for `SynthEventServiceImpl` that would record the method calls - with their args! - in a list in order and then that list could be validated in the already-existing tests for all the different transaction handlers and things that are _creating_ synth events?

(And that would also answer the _completeness_ question: it would be exactly as complete as the already existing tests.)

2023-02-17 21:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        for (int i = 0; i < recordItem.getTransactionRecord().getTokenTransferListsCount(); i++) {
Some benchmarks suggest that this type of loop is the fastest in Java: 
https://howtodoinjava.com/java/collections/performance-comparison-looping-a-list/

2023-02-17 21:38 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        for (int i = 0; i < recordItem.getTransactionRecord().getTokenTransferListsCount(); i++) {
that's good to know.  though in this case it's hard to believe loop iteration overhead counts for anything, considering the body of the loop.  anyway, I was mainly ~~complaining~~mentioning that there's a _very_ often needed language feature missing from nearly every language ... leading to ugly workaround in 1000000s of instances of code ...

2023-02-17 22:11 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        contractLog.setBloom(bloom);
We have it the same way [here](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L205-L223). 
I wanted to keep it the same for consistency.

2023-02-17 22:14 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +                                 int logIndex);
I agree with encapsulating `logIndex` within the class and not exposing it to other classes. But If we do that, we'd need to add some additional loops in this new SynthEventService class. And I wanted to avoid that for the sake of performance.

2023-02-17 22:25 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        contractLog.setBloom(bloom);
ok

2023-02-20 10:43 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +import com.hederahashgraph.api.proto.java.TokenID;
I need to construct a EntityId object, which accepts only TokenID, not TokenId.

2023-02-20 10:53 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +    void processTokenTransfer(RecordItem recordItem, EntityId senderId, EntityId receiverId,
Yeah, I agree with custom class wrapper for those values, let's what others think and I'll change it, if necessary.

2023-02-20 11:01 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +    void processApproveAllowance(RecordItem recordItem, long ownerId, long spenderId, EntityId tokenId, long amount,
I agree with you. Changed them to `createSyntetic...`

2023-02-20 11:03 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +    private static final String TRANSFER_SIGNATURE = "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";
Yes, those are keccak256 hashes of the events. You can find more info here. https://limechain.notion.site/Research-Explore-possible-ways-to-create-synth-events-for-HAPI-transactions-f0737ff2c5e84ddeb70321fa13dcb232

2023-02-20 11:04 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        processLog(recordItem, logIndex, tokenId, data, APPROVAL_SIGNATURE, topic1, topic2);
You can find more info [here](https://limechain.notion.site/Research-Explore-possible-ways-to-create-synth-events-for-HAPI-transactions-f0737ff2c5e84ddeb70321fa13dcb232) on how logs are constructed, what and why is data, topic0, topic1 etc..

2023-02-20 11:16 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (serialNumbersCount <= 0) {
I agree, created a method for this condition.

2023-02-20 11:23 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (serialNumbersCount <= 0) {
Did it like this, although there won't be any performance improvements, more like readability improvement, which is also a win. I've pushed the if up, if condition is true, do you thing and don't continue with the rest of the code, without a else.

2023-02-20 11:24 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (serialNumbersCount <= 0) {
Fixed.

2023-02-20 12:18 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                synthEventService.processTokenBurn(recordItem, tokenId, tokenBurnTransactionBody.getAmount(), 0);
Yes, you're right. I've made this change. Now we have interface for both with the same impl.

2023-02-20 12:22 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        Predicate<AccountAmount> byNegativeAmount = amount -> amount.getAmount() < 0;
Yes, thank you.

2023-02-20 12:23 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                synthEventService.processTokenWipe(recordItem, tokenId, tokenWipeAccountTransactionBody.getAmount(), 0);
Yep, made separate interfaces for different types of tokens. Thank you.

2023-02-20 12:24 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            logIndex = insertFungibleTokenTransfers(
So basically, that was my idea at first, didn’t want to couple those two classes(`EntityRecordItemListener` and `SynthEventService`), more than necessary, but also I didn’t wanted to hurt performance. If we move logIndex counting in the `SynthEventService`, we won’t know how many transfer, which of them are valid and how many to count and add, so we would need to pass the whole transferList. To go through it we’d need to loop all the item (this is already being done in EntityRecordItemListener). So instead of this, I’m adding the counting logic in `EntityRecordItemListener` as it’s already looping through all the items.

2023-02-20 12:27 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +        int logIndex = recordItem.getTransactionBody().getCryptoApproveAllowance().getNftAllowancesCount() + 1;
Because, we can have allowances for nft and ft in one transaction. We are making logs for the nft in the previous method on between line 115-175 . So in this we are saying, okay we have made `recordItem.getTransactionBody().getCryptoApproveAllowance().getNftAllowancesCount()` event logs, for fungible start from the next index.

2023-02-20 12:28 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            synthEventService.processApproveForAllAllowance(recordItem, ownerId.getId(), 0, tokenId, 0, i);
Explained in one of the previous comments.

2023-02-20 12:50 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +    public static byte[] hexToByte(String input) {
True, I don't know why I'm trying to reinvent the wheel :D

2023-02-20 12:51 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/TransactionSignatureTest.java
> +    private SynthEventService synthEventService;
Sadly, `logIndex` encapsulation won't be possible without performance degradation.

2023-02-20 12:53 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        assertThat(Utility.hexToByte(address3)).isEqualTo(new byte [] { -116, 91, -31, -27, -21, -20, 125, 91, -47, 79, 113, 66, 125, 30, -124, -13, -35, 3, 20, -64, -9, -78, 41, 30, 91, 32, 10, -56,
True, I've changed my implementation to use the HexFormat class from java, but I've not removed the tests. Should I ?

2023-02-20 12:54 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SynthEventServiceImplIntegrationTest.java
> +package com.hedera.mirror.importer.domain;
Yes, this setup is too big in my opinion, but can't think of a better way. I've copied most of the setup from other tests that already exists.

2023-02-21 01:41 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +import com.hederahashgraph.api.proto.java.TokenID;
OK.  Seems ... odd, but whoever wrote EntityId must have had a reason ...

2023-02-21 01:45 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +    private static final String TRANSFER_SIGNATURE = "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";
Maybe transfer the relevant parts of that (private) doc here into the repo?  Either as a separate doc or as a comment here explaining the "how" and hopefully the "why".  ("why" as in: is this keccak256 hash something arbitrary or - more likely - does some other part of the system depend on it (perhaps it's in an HIP somewhere ...))

2023-02-21 01:48 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        processLog(recordItem, logIndex, tokenId, data, APPROVAL_SIGNATURE, topic1, topic2);
Oh _this_ is the answer as to why topic1 is keccac hash, etc.   I would just link that article - or even better, a "permanent" link to it [at the wayback machine](https://web.archive.org/web/20220403181337/https://medium.com/mycrypto/understanding-event-logs-on-the-ethereum-blockchain-f4ae7ba50378).  (Or an official ethereum document itself if you happen to know of one.)

2023-02-21 02:31 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean logEvents = tokenTransfers.size() > 1 && negativeAccountAmounts.size() == 1;
This entire "synthetic event" thing is both non-obvious and intricate, being as it is a bridge between the Hedera and Ethereum worlds, and with lots of nit-picky details to get right as well as general expectations.  I really thing large parts of that Notions doc you linked above should be placed in this repo as a design doc.  Otherwise ... how will anyone know the details of what's going on here, later?

2023-02-21 02:32 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            logIndex = insertFungibleTokenTransfers(
I'm still considering this ....

2023-02-21 02:33 UTC, david-bakin-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/TransactionSignatureTest.java
> +    private SynthEventService synthEventService;
well maybe w.r.t. perf + encapsulation (though I'm still considering that) ... but, are there tests against it somewhere?

2023-02-21 02:35 UTC, david-bakin-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        assertThat(Utility.hexToByte(address3)).isEqualTo(new byte [] { -116, 91, -31, -27, -21, -20, 125, 91, -47, 79, 113, 66, 125, 30, -124, -13, -35, 3, 20, -64, -9, -78, 41, 30, 91, 32, 10, -56,
Um. Dunno.  I guess my complaint is more about how opaque these particular tests are with their byte arrays that have ungodly _negative_ numbers in them because Java byte arrays, for some (surely inadequate) reason, are _signed_.

2023-02-21 02:39 UTC, david-bakin-sl commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SynthEventServiceImplIntegrationTest.java
> +package com.hedera.mirror.importer.domain;
well ... not to overly promote the idea I proposed ... but why not a spy for SynthEventServiceImpl?  And TBH I don't really get Mockito's "spy" functionality - I'm talking about a true "spy" where you implement the interface passing though _all_ calls to the underlying real object, but meanwhile recording those calls in a List<some record for the purpose>, so that at the end of the operations being tested you ask the spy for its record and then verify _that_.  Then you just have to add those verifications to those tests _already existing_ that exercise these operations (taking care of course to set up the spy too).  (Ask me offline if I'm not being clear here.)

2023-02-21 02:43 UTC, david-bakin-sl commented
I thought there'd be a way to "resolve conversation" for individual comments made in a PR.  But I don't get that option, so it apparently doesn't exist.  I marked "resolved" comments with a "thumbs up" emoji.  Thanks!

I consider the following still open:

1. Adding a design doc on this stuff to explain the intricacies
1. Can the test setup be simplified while still testing everything properly (incluidng the "log index" counting)
1. What's going on with the "log index" and the performance impact of encapsulating it?

And for the latter two points, I have more thinking to do before I comment further.

2023-02-21 03:04 UTC, david-bakin-sl commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
>      private static String padLeftZeros(String inputString) {
Not to beat a dead horse here - no change is necessary since this works - but I'd consider something like
```
return String.format("%64s", inputString).replace(' ','0');
```

2023-02-23 06:05 UTC, steven-sheehy requested changes

2023-02-23 06:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        contractLog.setTopic2(Utility.hexToByte(topic2));
For data and topics we should not be inefficiently converting from primitive to hex string then to bytes. Instead we should just convert directly from primitive to bytes. Use tuweni `Bytes.of()` methods to convert them. 

Not only is it inefficient in terms of CPU and memory, but also database storage. We explicitly store fixed field bytea like topics without zero padding to reduce the storage consumption. These fields will get left zero padded on the REST API.

2023-02-23 06:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        byte[] bloom = { 0 };
Every row currently in the database has this populated with a real bloom with an exact length of 256 bytes. Even if we may not use this now, why can't we populate it to be consistent with the other rows?

2023-02-23 16:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                synthEventService.createSyntheticTokenTransfer(recordItem, senderId, receiverId, tokenId, amount, logIndex);
Need to have assertions in the relevant tests in `EntityRecordItemListener*Test` that verifies these logs are present and populated correctly.

2023-02-23 23:52 UTC, xin-hedera requested changes

2023-02-23 23:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +                logIndex++;
move it inside the dedup check on line 149

assume this always create an approve for all event? then suggest the following change:

In the interface
```java
void createSyntheticApproveForAllAllowance(RecordItem recordItem, long ownerId, long spenderId, EntityId tokenId, boolean approved, int logIndex);
```

and here

```java
  synthEventService.createSyntheticApproveForAllAllowance(recordItem, ownerAccountId.getId(), spender.getId(), tokenId, approvedForAll, logIndex);
```

2023-02-23 23:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +                }
move it inside the dedup check on line 166

also I don't think `hasApprovedForAll` and nft serial numbers are exclusive.

2023-02-23 23:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +            logIndex++;
move it into the dedup check on line 206

2023-02-23 23:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            synthEventService.createSyntheticApproveForAllAllowance(recordItem, ownerId.getId(), 0, tokenId, 0, i);
this is individual nft serial allowance removal, not approve for all removal

2023-03-07 15:18 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            synthEventService.createSyntheticApproveForAllAllowance(recordItem, ownerId.getId(), 0, tokenId, 0, i);
Ah, yes, you're right. Fixed.

2023-03-07 15:18 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +            logIndex++;
Done.

2023-03-07 15:18 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +                logIndex++;
Done.

2023-03-07 15:20 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +                              TokenID tokenId, long amount, int logIndex);
I've implemented it the way you suggested, also added a AtomicInteger in the Record Item. Can you check the implementation to see, if it's fine by you, so that I can proceed with tests ?

2023-03-07 15:20 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventService.java
> +public interface SynthEventService {
Done.

2023-03-07 15:20 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        //if serial number count is zero, that means that we are burning fungible tokens
Done.

2023-03-07 15:20 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        processLog(recordItem, logIndex, tokenId, amountHex, TRANSFER_SIGNATURE, "0", accountId);
Done.

2023-03-07 15:22 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +    public static byte[] hexToByte(String input) {
Thanks for this suggestions. Removed the utility method.

2023-03-07 15:23 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SynthEventServiceImpl.java
> +        contractLog.setTopic2(Utility.hexToByte(topic2));
Makes sense. Didn't know that, removed it.

2023-03-13 23:12 UTC, steven-sheehy requested changes

2023-03-13 23:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SyntheticContractLogServiceImplIntegrationTest.java
> +class SyntheticContractLogServiceImplIntegrationTest extends AbstractEntityRecordItemListenerTest {
```suggestion
class SyntheticContractLogServiceImplTest extends AbstractEntityRecordItemListenerTest {
```

2023-03-13 23:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SyntheticContractLogServiceImplIntegrationTest.java
> +    private NftTransferRepository nftTransferRepository;
Make final and remove `@Resource` to use constructor injection.

2023-03-13 23:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId receiverId = EntityId.of(accountAmount.getAccountID());
For sender and receiver, we don't necessarily have to convert it to EntityId just to convert it get the account num out of it if we can extract the account num directly from the proto AccountID. Same comment for others.

2023-03-21 14:29 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId receiverId = EntityId.of(accountAmount.getAccountID());
Yes, you're right. I did it like this for two reasons: one is consistency between classes and second reason, because there were already converted to EntityId in most of the places so I've just cached them and used them. Basically this is the only place where this is being converted only for the synthetic event logic, on all other places is needed for something else as well. But if you think this will have some performance hits, I can think of something.

2023-03-21 14:42 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SyntheticContractLog.java
> +
Added.

2023-03-21 14:42 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/SyntheticContractLogService.java
> +package com.hedera.mirror.importer.domain;
Moved.

2023-03-21 14:42 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/syntheticloghandler/SyntheticApproveContractLog.java
> +public interface SyntheticApproveContractLog extends SyntheticContractLog {
You're right, deleted it.

2023-03-21 14:42 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/syntheticloghandler/SyntheticTransferContractLog.java
> +    default byte[] getTopic0() { return Bytes.fromHexString("ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef").toArray(); }
Added.

2023-03-21 14:44 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/syntheticloghandler/NonFungibleTokenWipeContractLog.java
> +    private final RecordItem recordItem;
Done.

2023-03-21 14:44 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/syntheticloghandler/TransferContractLog.java
> +        data = Bytes.ofUnsignedLong(amount).toArray();
Done.

2023-03-21 14:44 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SyntheticContractLogServiceImplIntegrationTest.java
> +class SyntheticContractLogServiceImplIntegrationTest extends AbstractEntityRecordItemListenerTest {
Renamed.

2023-03-21 14:44 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SyntheticContractLogServiceImplIntegrationTest.java
> +    private NftTransferRepository nftTransferRepository;
Done.

2023-03-22 18:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/syntheticloghandler/NonFungibleTokenWipeContractLog.java
> +    private final RecordItem recordItem;
You're right that `@Value` can't be used on abstract because it also includes final on the class. You can replicate `@Value` with other annotations though to get the same effect. The use of `@Getter` on the field is not important, I'm more concerned with the fields not being final. So we should find a way to keep it that way. Here's my suggestion as long as you don't mind setting everything via calls to super:

```java
@Data
public abstract class AbstractSyntheticContractLog {

    private final byte[] data;
    private final EntityId entityId;
    private final RecordItem recordItem;
    private final byte[] topic0;
    private final byte[] topic1;
    private final byte[] topic2;
...
}
```

So by using `@Data` and marking the fields as final you get mostly the same effect. Then can omit the constructor.

2023-03-22 20:19 UTC, steven-sheehy requested changes

2023-03-22 20:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractlog/AbstractSyntheticContractLog.java
> +    static final byte[] APPROVE_SIGNATURE = Bytes.fromHexString("8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925").toArray();
There's really only 3 events, so we should only have 3 implementations of `SyntheticContractLog`. The population of the receiver, sender and value should be handled by the class that creates the log as he has specific knowledge of the transaction body.

2023-03-22 20:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                syntheticContractLogService.create(new NonFungibleTokenBurnContractLog(recordItem, tokenId, serialNumber));
This and most of the changes to this class are wrong because they're using data from the transaction body and not the transaction record. As a result, they are using inaccurate sender/receiver like payer account. Should revert all changes to this class and simply generate logs for all token transfers and nft transfers in the record in those two spots.

2023-03-22 20:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean shouldLogEvent = !(body.hasTokenMint() || body.hasTokenWipe() || body.hasTokenBurn());
mints, wipes, burns all show up in the transfers anyway so we should remove this check and do this log for all transactions.

2023-03-22 20:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SyntheticContractLogServiceImplTest.java
> +    void TokenTransfer() {
Start with lowercase letters for all method names.

2023-03-22 20:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/SyntheticContractLogServiceImplTest.java
> +class SyntheticContractLogServiceImplTest extends AbstractEntityRecordItemListenerTest {
Wow, this is a huge test that you spent some serious time on. But unfortunately I'm going to have to ask you to delete most of it. 😢 We already have all of these scenarios in the `EntityRecordItemListener*Test` classes. You simply need to add an extra assertion to the applicable ones that verifies the contract log entry is created and is the format you expect (verify data, topic0, topic1, etc. map correctly from input). This is what I had [suggested](https://github.com/hashgraph/hedera-mirror-node/pull/5402#discussion_r1115942832) previously so not sure why you took this approach. Having duplicate tests for the same scenarios is a maintenance burden.

2023-03-22 20:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java
> +public class SyntheticContractLogServiceImpl implements SyntheticContractLogService {
Add a unit test for this class that just tests all code paths init it for one type of log.

2023-03-29 13:07 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java
> +        contractLog.setBloom(Bytes.of(0).toArray());
I'm not sure how we can populate it really. We are receiving it from the record item for normal contract logs. But for synthetic we have to somehow calculate it and i'm not sure not only how, but how will it hit performance and if it's worth it.

2023-04-04 04:28 UTC, steven-sheehy requested changes

2023-04-04 04:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java
> +public class SyntheticContractLogServiceImpl implements SyntheticContractLogService {
Still missing a simple mock test to verify feature flag and isContract check.

2023-04-04 04:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        List<AccountAmount> negativeAccountAmounts = tokenTransfers.stream().filter(amount -> amount.getAmount() < 0).toList();
We should avoid the use of streams in the hot path as it generates a ton of objects on the heap. 10K TPS transaction types use this code path.

2023-04-04 04:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractlog/TransferContractLog.java
> +        super(longToBytes(amount) ,tokenId, TRANSFER_SIGNATURE, entityIdToBytes(senderId), entityIdToBytes(receiverId), recordItem);
It's confusing to me that the order of parameters varies in parent and children. It's also confusing to me that that last parameters are not `(..., topic0, topic1, topic2, data)`. I keep thinking that tokenId is one of the topics.

2023-04-04 04:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                Nft nft = new Nft(serialNumber, tokenId);
A lot of whitespace and refactoring changes to this file that makes it hard to review. Also will make it harder to merge from main after I refactored this class to move out transaction specific logic. Should try to undo it.

2023-04-04 13:29 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                Nft nft = new Nft(serialNumber, tokenId);
Yeah, sorry about that, i've made the mistake to open this file in vs code 😄 Reverted the changes

2023-04-04 13:30 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractlog/SyntheticContractLog.java
> +
Added.

2023-04-04 14:52 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        List<AccountAmount> negativeAccountAmounts = tokenTransfers.stream().filter(amount -> amount.getAmount() < 0).toList();
Agree. I've removed it and added alternative check.

2023-04-04 18:06 UTC, steven-sheehy requested changes

2023-04-04 18:06 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
I'm not sure that you can rely upon transfer list order. Even if you can now, that may not be the case in the future and is brittle to use. Why can't you just do:
```suggestion
        boolean isNotMultiTransfer = tokenTransfers.size() <= 2 && !isMint && !isWipeOrBurn;
```

Or even just:

```suggestion
        boolean isSingleTransfer = tokenTransfers.size() == 2;
```

2023-04-04 18:53 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                    syntheticContractLogService.create(new TransferContractLog(recordItem, tokenEntityId, accountId, receiverId, -amount));
Done.

2023-04-04 18:53 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            RecordItem recordItem, TokenID tokenId, EntityId entityTokenId,
Thank you. Done.

2023-04-04 18:54 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                syntheticContractLogService.create(new TransferContractLog(recordItem, tokenEntityId, senderId, accountId, amount));
Done.

2023-04-04 18:54 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean isMint = tokenTransfers.get(0).getAmount() > 0 && tokenTransfers.get(tokenTransferCount-1).getAmount() > 0;
Thank you, you're right.

2023-04-04 18:54 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean isWipeOrBurn = tokenTransfers.get(0).getAmount() < 0 && tokenTransfers.get(tokenTransferCount-1).getAmount() < 0;
Thank you, you're right.

2023-04-04 18:56 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
This one is a little trickier. If we do it like you're proposing, we are losing support for one sender with multiple receivers. I agree that's not good to rely on transfer order.

2023-04-04 19:36 UTC, steven-sheehy requested changes

2023-04-04 19:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean isWipeOrBurn = recordItem.getTransactionType() == TransactionType.TOKENBURN.getProtoId() || recordItem.getTransactionType() == TransactionType.TOKENWIPE.getProtoId();        // If the
nit: Can remove comment since it's no longer applicable.

2023-04-04 19:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
Believe mint also meets these requirements so will generate two logs for mint.

2023-04-04 19:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Please let's make sure we have test coverage for each of these scenarios. What about counting positive transfers up front, then only generate logs if the positive count is one and not wipe or burn?

2023-04-04 19:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        listAssert.extracting(ContractLog::getTopic0).containsExactlyInAnyOrder(TRANSFER_SIGNATURE, TRANSFER_SIGNATURE);
For all tests, we should be verifying the data, topic1, and topic2 fields.

2023-04-04 19:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .hasSize(2);
To simplify and make it clear what we're testing, we should only lookup and verify the mint contract log. You can verify the overall counts of logs, but should just verify fields for the transaction under test. Same comment for other tests.
```suggestion
        assertThat(contractLogRepository.findById(...))
            .returns(foo, ContractLog::bar)
            ...
```

2023-04-04 19:43 UTC, steven-sheehy commented
There's 3 code smells to address, as well.

2023-04-04 20:26 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Not sure it would work, because to be a single transfer it needs one negative and one or more positive. So checking for only positive counts is not covering this. I'm maybe leaning towards your suggestion for checking, if transfer list count == 2. This way we cover single transfers with one receiver and one sender. And for the other two cases - one sender -> multiple receivers and multiple senders -> multiple receivers - we are not supporting them for now, until we find a proper way. What do you think ?

2023-04-04 22:07 UTC, xin-hedera requested changes

2023-04-04 22:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            }
if the decision is to log token transfers for token create, mint, burn, wipe, and those with a single sender. we can have a flag `shouldLogTransfers`

```java
  boolean isSingleSenderTransfer = tokenTransferCount > 1 && tokenTransfers.stream().filter(aa -> aa.getAmount() < 0).count() == 1;
  boolean shouldLogTransfers = !isDeletedTokenDissociate && (tokenTransferCount == 1 || isSingleSenderTransfer);
```

then in the for loop, do

```java
            if (shouldLogTransfers) {
                var senderId = amount < 0 ? accountId : EntityId.EMPTY;
                var receiverId = amount > 0 ? accountId : EntityId.EMPTY;
                syntheticContractLogService.create(new TransferContractLog(recordItem, tokenId, senderId, receiverId, Math.abs(amount)));
            }
```

Note please don't log token transfers in the record of token dissociate transaction of a deleted token, since

1. it's a edge case to have such wipe from account token transfer to reduce the account's token balance to 0
2. if it's a deleted non-fungible token, the transfer will also show up in fungible token transfer list `AccountAmount`, very confusing and incorrect if you log it as if it were a fungible token

2023-04-05 02:18 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Probably safest for now.

2023-04-05 02:19 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    @Getter(PRIVATE)
I think we don't want to expose the getter for the atomic so as to not leak implementation details.

2023-04-05 10:20 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
Events are using uint for amount, so we can't pass negative. We only log positive, this is intentional and the same as how it is in ethereum world.

2023-04-05 12:36 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean isWipeOrBurn = recordItem.getTransactionType() == TransactionType.TOKENBURN.getProtoId() || recordItem.getTransactionType() == TransactionType.TOKENWIPE.getProtoId();        // If the
Removed.

2023-04-05 12:37 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
You're right. I've separated them, now should be fine.

2023-04-05 12:38 UTC, georgi-l95 commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        return currentValue;
Thank you, fixed it.

2023-04-05 12:38 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoApproveAllowanceTransactionHandler.java
> +                    syntheticContractLogService.create(new ApproveForAllAllowanceContractLog(recordItem, tokenId, ownerAccountId, spender, true));
Done.

2023-04-05 12:38 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            var ownerId = EntityId.of(nftRemoveAllowance.getOwner());
Added a check.

2023-04-05 12:41 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        listAssert.extracting(ContractLog::getTopic0).containsExactlyInAnyOrder(TRANSFER_SIGNATURE, TRANSFER_SIGNATURE);
You're right. Added.

2023-04-05 14:27 UTC, xin-hedera requested changes

2023-04-05 14:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            NftRemoveAllowance nftRemoveAllowance = nftAllowances.get(i);
nit, can revert these lines. I think previously you made the change because `i` was used as the log index

```suggestion
        for (var nftAllowance : recordItem.getTransactionBody().getCryptoDeleteAllowance().getNftAllowancesList()) {
```

2023-04-05 14:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
right. I didn't mean to log the transfer with negative amount. For instance, we log token wipe / burn with positive amount, why don't we also log the sender's transfer in the single sender transfers scenario?

2023-04-05 14:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            }
i see. however there's still concern that the single sender transfer detection is based on services implementation details and may break if the order ever changes.

did you look at my other suggestions to simplify the logic? looking at transaction types and blending the logic into multiple places is harder to read and maintain

2023-04-05 14:47 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
Not sure how the event would look like, for example we have 
0x1 sender
0x2 receiver
10 amount
event transfer(0x1, 0x2, 10); -> we will log this.

2023-04-05 14:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
Since I see for token mint, the log is

`0x0` sender
`0x1` receiver
`10` amount

and for token burn, the log is

`0x1` sender
`0x0` receiver
`10` amount

I assume for the simplest two-party token transfer of amount `10` from account `0x1` to `0x2`, we can have the following two logs:

`0x1` sender
`0x0` reciever
`10` amount

and 

`0x0` sender
`0x2` receiver
`10` amount

2023-04-05 14:58 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        }
Okay, let's settle for single transfer -> one sender, one receiver. After this PR we can open a issue to capture multi transfers (research if there is a way currently to do them correctly).

2023-04-05 15:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (isSingleSenderTransfer && amount > 0) {
I see, now it makes sense to me. thanks for the clarification.

2023-04-05 15:15 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +            NftRemoveAllowance nftRemoveAllowance = nftAllowances.get(i);
You're right. Reverted.

2023-04-05 15:35 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-04-05 19:50 UTC, steven-sheehy requested changes

2023-04-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .returns(Bytes.ofUnsignedLong(PAYER.getAccountNum()).toArray(), from(ContractLog::getTopic2))
The receiver for mints should be the treasury account, which is not always the payer account. We should change all the tests you modified that send/receive to treasury (mint, wipe and burn to FT and NFT) so that payer != sender/receiver so it's clear that we're not accidentally mapping the payer of the transaction to that like we were in an earlier version of this PR.

2023-04-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        assertThat(contractLogRepository.findById(new ContractLog.Id(mintTimestamp, 0))).get()
This should be the wipeTimestamp that we're testing.

2023-04-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoDeleteAllowanceTransactionHandler.java
> +import java.util.List;
Two unused imports here are causing 2 of the 3 code smells. Please address all code smells.

2023-04-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean isMint = recordItem.getTransactionType() == TransactionType.TOKENMINT.getProtoId() && !isDeletedTokenDissociate;
This is misleading and unnecessary. If the type is burn or wipe transaction, it can't also be a dissociate transaction. You can just remove all dissociate logic for now since we're checking transfer size is 2 for single transfer.
```suggestion
        boolean isWipeOrBurn = recordItem.getTransactionType() == TransactionType.TOKENBURN.getProtoId() || recordItem.getTransactionType() == TransactionType.TOKENWIPE.getProtoId();
        boolean isMint = recordItem.getTransactionType() == TransactionType.TOKENMINT.getProtoId();
```

2023-04-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId senderId = EntityId.of(tokenTransfers.get(0).getAccountID());
This still assumes the sender is the first in the transfer list, which is brittle.

2023-04-05 20:37 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId senderId = EntityId.of(tokenTransfers.get(0).getAccountID());
Agree that it's not ideal, but we somehow need to get the negative accountAmount as a sender, while we are in the positive accountAmount.

2023-04-05 21:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId senderId = EntityId.of(tokenTransfers.get(0).getAccountID());
Since it’s always 2 token transfers, the sender’s transfer index is 1 - the receiver’s

2023-04-05 21:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId senderId = EntityId.of(tokenTransfers.get(0).getAccountID());
Still need to address before merging. The solution is pretty simple. The for loop should track the index and we've already verified that the list is size 2. If we see positive amount on index=0, we get sender from index=1. If we see positive amount on index=1, we get sender from index=0.

2023-04-06 13:48 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .returns(Bytes.ofUnsignedLong(0).toArray(), from(ContractLog::getTopic1))
I was wrongly asserting the mint, not the transfer. Thanks for noting.

2023-04-06 14:52 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        boolean isMint = recordItem.getTransactionType() == TransactionType.TOKENMINT.getProtoId() && !isDeletedTokenDissociate;
Done.

2023-04-06 14:53 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                EntityId senderId = EntityId.of(tokenTransfers.get(0).getAccountID());
Changed to the proposed way.

2023-04-06 14:53 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .returns(Bytes.ofUnsignedLong(PAYER.getAccountNum()).toArray(), from(ContractLog::getTopic2))
Changed them to PAYER2 which is the treasury

2023-04-06 16:32 UTC, steven-sheehy approved these changes
LGTM

2023-04-06 18:20 UTC, xin-hedera approved these changes
LGTM

2023-04-06 18:23 UTC, merged