K6 performance tests for eth_call with token precompiles
hashgraph/hedera-mirror-node pull request #5417
Opened 2023-02-14 15:50 UTC by mustafauzunn

**Description**:

K6 performance tests for api/v1/contracts/call REST API invoking precompiles

**Related issue(s)**:

Fixes #5301 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-22 16:35 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/contractCallAllowance.js
> +const {options, run} = new TestScenarioBuilder()
it's worth abstract the common code to a `ContractCallTestScenarioBuilder`:

```javascript
  new ContractCallTestScenarioBuilder()
    .name(...)
    .selector(...)
    .args(...)
    .build();
```

2023-02-22 20:28 UTC, steven-sheehy requested changes

2023-02-22 20:28 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/index.js
> +  contractCallTokenExpiryInfo,
nit: Sort this list

2023-02-22 20:28 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/test/contractCallSymbol.js
> +const token = __ENV.TOKEN_ADDRESS;
Need to document any new variables in the k6 README and what they should be populated with.

2023-02-24 18:28 UTC, xin-hedera requested changes

2023-02-24 18:28 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    this._url = 'http://localhost:8545/api/v1/contracts/call';
should get base url from env variable

2023-02-24 23:57 UTC, steven-sheehy requested changes

2023-02-24 23:57 UTC, steven-sheehy commented on hedera-mirror-test/k6/README.md
> +- TOKEN_ADDRESS - 32bytes token address
Sort these variables and instead of bytes use character count (since it's a string) and binary encoding (hex) and whether it has `0x` prefix or not. Basically:
```suggestion
- TOKEN_ADDRESS - 64 character hex encoded token address without `0x` prefix
```

2023-02-24 23:57 UTC, steven-sheehy commented on hedera-mirror-test/k6/src/web3/reference/ERCTestContract.sol
> +contract ERCTestContract {
How do these test contracts get created in order for the k6 tests to be ran? We should document the steps in the README so others can run these tests just by following the docs. We should also perhaps commit the initcode so other tools are not required outside the Hedera SDK.

2023-02-27 16:35 UTC, xin-hedera commented on hedera-mirror-test/k6/src/web3/test/common.js
> +    this._url = 'http://localhost:8545/api/v1/contracts/call';
it should be

```
`${__ENV.BASE_URL}/api/v1/contracts/call`
```

2023-02-28 15:47 UTC, steven-sheehy approved these changes
LGTM

2023-02-28 20:17 UTC, merged