Adding TokenAccessor implementation
hashgraph/hedera-mirror-node pull request #5424
Opened 2023-02-15 09:41 UTC by nikolovyanko

Adds implementation for the evm-module-lib's TokenAccessor interface. And attaching the EvmContractPrecompile to the besu's precompile configuration in [utilclass].

Fixes #4502

2023-02-21 11:47 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var isPaused = tokenEntity.getPauseStatus().ordinal() == 1;
We can swipe lines 312 and 313, so that `isPaused` is declared right before its usage.

2023-02-21 11:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        evmTokenInfo.setIsPaused(isPaused);
We can add new line separation.

2023-02-21 11:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +
Probably remove this empty line.

2023-02-21 11:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        //evm-lib CustomFee POJO
Do we need this comment?

2023-02-21 11:58 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ERCTokenCallServiceTest.java
> +
We can make the formatting of all constants equal -> add spaces for all constants below `TOTAL_SUPPLY`

2023-02-22 13:42 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +
I'm not sure about that since the tests do create token without `customFee` and no null pointer observed. Provide more details here.

2023-02-23 07:30 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +
What does "No" answers to? I want to see if including `all_collectors_are_exempt`  in the query for filtering will resolve this. However, I need to know whether the value of it differ between fully existing `custom_fee` records and semi one.

2023-02-23 08:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +
`all_collectors_are_exempt` is set on token creation transaction. It's a property set on the protobuf message for the `CustomFee` property, so it's a user choice what value to be set.

I believe the solution for the risk of NPE or returning custom fees that are empty is to check if for the given custom fee record from DB we have a collector account that is set. If we have, we can proceed with populating the custom fee record. If not, we can skip this custom fee.

In addition, in the case of a `Fixed` or a `Royalty` fee, we should also check if the denominating tokenId is null, since `toAddress` might get NPE. In both cases denominating tokenId is not mandatory.

For `FixedFee` we have 2 options:

1. Fee paid with hbars (denominating tokenId is null)
2. Fee paid with a fungible token pointed by the denominating tokenId

For 'RoyaltyFee' we have also 2 options:

1. Fee paid via a fraction of a fungible token used during the NFT transfer (denominating tokenId is null)
2. Fee paid via a fallback fee used in the case 1. does not apply. In this case we pay with a nested `FixedFee` using a fungible token pointed by the denominating tokenId

We should distinguish between all these scenarios and properly populate each custom fee case, so that we don't get NPE or return meaningless custom fee to the end user. In addition, there is no such thing as a semi custom_fee. In the case of an empty `custom_fee` the `mirror-node-importer` set a row with only timestamp and tokenId populated as can be seen [here](https://github.com/hashgraph/hedera-mirror-node/blob/6f9bcb0cb4ba07abd801308282b0427628ffd044/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java#L1137)

2023-02-23 13:05 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +            if (amount == null) {
In the case of `FractionalFee` the amount would not be set, so we will miss this type of fees.

As suggested, checking if the `fee account collector` is set would be the most suitable check. If it's set we should populate the given field, if not - continue with the next DB row. In addition we should check if `denominatingTokenId` is null or not.

2023-02-23 13:31 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +            if (amount == null) {
Yes, thanks for the previous detailed comment, this should be resolved now.

2023-02-23 13:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                return customFees;
I think we should use `continue`, since the other fees from this list might have a `collector` and could be valid fees.

2023-02-23 13:36 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                return customFees;
Agree, valid point.

2023-02-23 13:46 UTC, IvanKavaldzhiev approved these changes
LGTM!

2023-02-28 21:50 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var ledgerId = properties.getNetwork().getLedgerId();
Sonar found bugs on these lines, can you fix those? 

Also, it would be very good to have a `TokenAccessorImplTest` that goes through the use cases for this class specifically, isolated from everything else.

2023-03-01 11:40 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var ledgerId = properties.getNetwork().getLedgerId();
Hey, thanks for the inputs, the sonar issues are fixed except for the "More than 5 children" hierarchy one which I don't think is a problem since is for exception inheritance.  

As for the `TokenAccessorImplTest ` I can do that if it will make the `TokenAccessorImpl` usage clearer and more readable. However, please note that there are 2 integration tests covering the `TokenAccessorImpl` methods:

- `ERCTokenCallServiceTest`
- `PrecompileCallServiceTest`

2023-03-01 23:49 UTC, steven-sheehy requested changes
Still making my way through

2023-03-01 23:49 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +            return Optional.empty();
Codecov counts 6 branches missing code coverage including this one. Would like to see the coverage increased closer to 100%.

2023-03-01 23:49 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var nftOptional = nftRepository.findById(new NftId(serialNo, fromEvmAddress(nft.toArray())));
```suggestion
        final var nftOptional = nftRepository.findById(new NftId(serialNo, fromEvmAddress(nft.toArrayUnsafe())));
```

2023-03-02 18:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var ledgerId = properties.getNetwork().getLedgerId();
I agree that the "More than 5 parents" code smell is OK to bypass (for an exception class).  But rather than introducing this as the one code smell in the repository (we recently cleaned them all up), could you please add the line:
`@SuppressWarnings("java:S110")
`
just before the class declaration?

2023-03-06 12:28 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var ledgerId = properties.getNetwork().getLedgerId();
Got it, thanks for the suggestion.

2023-03-13 08:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtilsTest.java
> +        assertThat(result.getEd25519()).isNotEmpty();
We can check the exact value of the ED25519 key.

2023-03-13 08:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtilsTest.java
> +        assertThat(result.getECDSASecp256K1()).isNotEmpty();
We can check the exact value of the ECDSA key.

2023-03-13 08:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/PrecompileCallServiceTest.java
> +    private void customFeesPersist(EntityId senderEntityId, EntityId tokenEntityId){
We can rename senderEntityId -> collectorAccountId

2023-03-13 16:56 UTC, xin-hedera requested changes

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CustomFeeRepository.java
> +    @Query(value = "select * from custom_fee where token_id = ?1",
the query returns all custom fee rows for a token, including the current and any past fee schedules. please change the query to

```
select * from custom_fee where token_id = ?1 and consensus_timestamp = (select consensus_timestamp from custom_fee where token_id = ?1 order by consensus_timestamp desc limit 1)
```

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +    Boolean isSpenderAnOperator(final Long tokenId, final Long ownerId, final Long spenderId);
```suggestion
    Optional<Boolean> isSpenderAnOperator(final Long tokenId, final Long ownerId, final Long spenderId);
```

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return isSpenderAnOperator != null && isSpenderAnOperator;
after changing the return type to an optional, this can be
```suggestion
        return isSpenderAnOperator.oElse(false);
```

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/NftAllowanceRepositoryTest.java
> +    @Test
parameterize this test case to also test `approvedForAll = false`.

also add a test case for when there is no matching row in db

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    public boolean staticIsOperator(final Address owner, final Address operator,
shouldn't this function named `staticIsSpender`, which check if the `operator` has approvedForAll for the nft `token` owned by `owner`?

if so, please change the repository method name accordingly.

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +    Boolean findFreezeDefault(final Long tokenId);
```suggestion
    Optional<Boolean> findFreezeDefault(final Long tokenId);
```

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +    Optional<byte[]> findKycDefault(final Long tokenId);
```suggestion
    Optional<byte[]> findKycKey(final Long tokenId);
```

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    }
what does this function do? If there is no kyc key, the kyc status should be `KycNotApplicable` (in protobuf). on the other hand, if there is kyc key, the default kyc status should be `revoked`.

2023-03-13 16:56 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        if (tokenInfoOptional.isPresent()) {
can do `return tokenInfoOptional.map(tokenInfo -> {...}).orElse(EMPTY_EVM_KEY);`

2023-03-13 18:30 UTC, steven-sheehy requested changes

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ERCTokenCallServiceTest.java
> +class ERCTokenCallServiceTest extends Web3IntegrationTest {
`ContractCallServiceERCTokenTest`

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ERCTokenCallServiceTest.java
> +    private static final Bytes ERC_CONTRACT_BYTES = Bytes.fromHexString("608060405234801561001057600080fd5b50600436106100cf5760003560e01c8063d5d03e211161008c578063e7092b4111610066578063e7092b41146102
My other comments from `PrecompileCallServiceTest` about the bytecode loading and magic strings also apply to this class.

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityOptional = entityRepository.findById(entityIdFromEvmAddress(token));
```suggestion
        final var entityOptional = entityRepository.findByIdAndDeletedIsFalse(entityIdFromEvmAddress(token));
```

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                entity.getExpirationTimestamp() / 1000000000;
If expirationTimestamp is null, use similar logic to `utils.js` `calculateExpiryTimestamp()`. Unless the EVM library already does this logic separately.

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var isPaused = tokenEntity.getPauseStatus().ordinal() == 1;
Use `TokenPauseStatusEnum` instead of ordinals and hardcoded integers.

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                        new EntityId(a.getShard(), a.getRealm(), a.getNum(), EntityType.ACCOUNT))));
We should only do this logic if autoRenewAccountId is not null. And we don't need to do a database lookup.

```suggestion
        if (entity.getAutoRenewAccountId() != null) {
            var autoRenewAddress = toAddress(EntityId.of(entity.getAutoRenewAccountId(), EntityType.ACCOUNT));
            evmTokenInfo.setAutoRenewAccount(autoRenewAddress);
        }
```

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        evmTokenInfo.setAutoRenewPeriod(entity.getAutoRenewPeriod() != null ? entity.getAutoRenewPeriod() : 0);
Weird that `EvmTokenInfo` has a large constructor for some fields and setters for the others. Should maybe add setters for all or use a builder pattern. But outside the scope of this PR.

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var ownerEntity = EntityIdEndec.decode(ownerNum.get(), ACCOUNT);
Don't use EntityIdEndec directly.
```suggestion
        final var ownerEntity = EntityId.of(ownerNum.get(), ACCOUNT);
```

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return Address.wrap(Bytes.wrap(toEvmAddress(ownerEntity)));
Use `EvmTokenUtils.toAddress`

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return Address.wrap(Bytes.wrap(toEvmAddress(spenderEntity)));
Use EntityId.of and EvmTokenUtils.toAddress

2023-03-13 18:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return status.filter(e -> e == 1).isPresent();
Use enum, not ordinals. Use findById

2023-03-13 19:08 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    public boolean isTokenAddress(final Address address) {
What we did was, to extract some methods from `WorldLedgers`, that are used in `hedera-services` for reading token info and have a common interface that makes facade over them. This solution was not ideal performance wise, but we used incremental approach to implement `eth_call` and save us time to fit in the milestone.

With the introduction of `eth_estimateGas`, we are now going to have a special `State` inside `mirror-node` where we would operate over whole entities (accounts, contracts, tokens). It would be used also via `eth_call` eventually and there we can utilize fetching whole entities from the DB and caching them in the `State`. Then we can keep `TokenAccessor` as a concept but instead of reading each single field from DB we can first try to fetch an entity from the `State` and then read the specific field required by each method. This would greatly reduce DB layer usage. After `eth_estimateGas` efforts are finished we would refactor `TokenAccessor` implementation and address these performance concerns.

So, I don't think we should change anything in services, but start using the `State` and refactor `TokenAccessorImpl`.

2023-03-15 10:04 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return defaultFreezeStatus != null && defaultFreezeStatus;
Native queries are removed from the repository interfaces. I think the caching can be address in the related[PR](https://github.com/hashgraph/hedera-mirror-node/pull/5581) as it already handles some of the cases.

2023-03-15 12:27 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityAddress = toAddress(nftEntity.getAccountId());
`entityIdFromAccountAddress()` accepts `Address` type and `nftEntity.getAccountId()` returns `EntityId`.  Can we tell by the returned `EntityId` whether it's been derived from evm address or ECDSA key? If not should we query the `entity.evm_address` for such cases like so? 

```suggestion
        final var entityAddress = entityRepository
                            .findByIdAndDeletedIsFalse(nftEntity.getAccountId())
                            .map(entity -> Address.wrap(Bytes.wrap(entity.getEvmAddress())));
```

2023-03-15 15:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityAddress = toAddress(nftEntity.getAccountId());
Right, but EVM address can be null. Also, with HIP-583 alias can now also be an EVM address. So we should add some helper method that searches for the entity by ID and uses `evm_address` if present, otherwise use `alias` if present and 20 bytes, otherwise converts `entity.num` to an EVM address.

2023-03-15 16:19 UTC, steven-sheehy requested changes

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtils.java
> +        final var ed25519 = key.hasEd25519() ? toBytes(key.getEd25519()) : new byte[0];
Can move `new byte[0]` as a static constant since it's immutable.

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/PrecompileCallServiceTest.java
> +class PrecompileCallServiceTest extends Web3IntegrationTest {
```suggestion
class ContractCallServicePrecompileTest extends Web3IntegrationTest {
```

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenRepositoryTest.java
> +    }
Can combine all these separate tests into one that asserts many fields. Same comment for other repository tests.
```suggestion
    void findById() {
        var token = domainBuilder.token()
                .customize(t -> t.type(NON_FUNGIBLE_UNIQUE).freezeDefault(true)).persist();
        assertThat(tokenRepository.findById(tokenId))
            get()
            .returns(token.getDecimals(), Token::getDecimals)
            .returns(token.getKycKey(), Token::getKycKey)
            ...;
    }
```

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/NftRepositoryTest.java
> +    private static final EntityId spender = new EntityId(0L, 0L, 56L, EntityType.TOKEN);
Why is there a need for a specific spender ID versus the auto-generated one set via `DomainBuilder::nft`? Think you can remove this constant and the other non-final variables and consolidate to one `findById()` test.

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/CustomFeeRepositoryTest.java
> +        final var customFee = domainBuilder.customFee().persist();
We should add a few custom fees with different created timestamps but same token to ensure the right ones are returned. Also some with different token id.

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtilsTest.java
> +@ExtendWith(MockitoExtension.class)
nit: Not used

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtilsTest.java
> +import org.bouncycastle.util.encoders.Hex;
Prefer Apache commons since it's a direct dependency.

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtilsTest.java
> +    void entityIdFromAddress(){
Add some negative tests

2023-03-15 16:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +            final var denominatingTokenId = customFee.getDenominatingTokenId();
Most of this `getCustomFees` is missing code coverage.

2023-03-22 10:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        for (final var customFee : customFeesCollection) {
Having a look at the `CustomFee` entity it seems `amount`, `amountDenominator`, `collectorAccountId`, `denominatingTokenId`, `maximumAmount`, `royaltyDenominator`, `royaltyNumerator`, `netOfTransfers` could be `null` since they all have a type that is an Object and not a primitive one. If we use them in the logic below we should make a null check for each of them.

2023-03-27 10:50 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityAddress = toAddress(nftEntity.getAccountId());
Done, added `evmAddressFromId` method.

2023-03-28 04:21 UTC, steven-sheehy requested changes

2023-03-28 12:37 UTC, nikolovyanko commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/FunctionEncodeDecoder.java
> +    private static final String RESOURCE_PATH = "build/resources/test/contracts/%1$s.%2$s";
Used ` @Value("classpath:...)` annotation instead from your previous suggestion.

2023-03-28 21:07 UTC, IvanKavaldzhiev approved these changes
LGTM!

2023-03-28 22:01 UTC, xin-hedera approved these changes
LGTM!

2023-03-28 22:07 UTC, merged