Enhance web3 error response with detail message
hashgraph/hedera-mirror-node pull request #5425
Opened 2023-02-15 11:01 UTC by IvanKavaldzhiev

**Description**:

This PR enhances the GenericResponse used by web3 module with a human readable detail revert message (when applicable). This message is then used by the json-relay to be propagated to the end user. 

**Related issue(s)**:

Fixes #5399 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-15 11:31 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        //Utility class
You can remove the private constructor and use the `@UtilityClass` lombok annotation instead.

2023-02-15 14:39 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +}
Would be good to have a `BytesDecoderTest.java` that tests inputs and expected outputs (and exceptions if there are any), similar to this type of test: 

```
    @ParameterizedTest(name = "Convert {0} to snake case")
    @CsvSource({
            ",",
            "\"\",\"\"",
            "Foo,foo",
            "FooBar,foo_bar",
            "foo_bar,foo_bar"
    })
    void toSnakeCase(String input, String output) {
        assertThat(Utility.toSnakeCase(input)).isEqualTo(output);
    }
    ```

2023-02-15 17:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +}
Agreed but please use the newer `@CsvSource(textBlock = """` as seen in `GraphQlUtilsTest`.

2023-02-16 05:35 UTC, steven-sheehy requested changes

2023-02-16 05:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/GenericErrorResponse.java
> +        private String detail;
Would prefer this mutable subclass of an immutable parent also be made immutable via `@Value` and final fields.

2023-02-16 05:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        if(revertReason.isEmpty()) {
Is there any chance it can be null?

2023-02-16 05:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        if(ERROR_SIGNATURE_BYTES.equals(revertReason.slice(0, SIGNATURE_BYTES_LENGTH))) {
Need to do bounds checking first to see if bytes is > SIGNATURE_BYTES_LENGTH (to see if at least one byte past signature)

2023-02-16 05:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        return STRING_DECODER.decode(encodedMessage.toArray()).get(0);
I'm not sure on the headlong API, but we should probably do bounds checking before accessing the first element.

2023-02-17 15:33 UTC, steven-sheehy approved these changes
LGTM

2023-02-17 16:53 UTC, edwin-greene approved these changes
Looks good

2023-02-17 17:03 UTC, merged