05232 optimize contract log query take 2
hashgraph/hedera-mirror-node pull request #5441
Opened 2023-02-18 01:06 UTC by MarcKriguerAtHedera

**Description**:
Modify the `contractLogsExtendedQuery` by copying the transaction_hash and transaction_index columns
(from the `contract_result` table) into `contract_log`, and then removing the `join contract_result` part of the query.

**Related issue(s)**:

Fixes #5232 

**Notes for reviewer**:
See details on the issue (link above) for improved performance numbers.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-02-23 18:09 UTC, MarcKriguerAtHedera commented
After getting all tests to pass (for both v1 and v2), and running K6, I see a small (2-3%) improvement (beyond just the improvement from having a better distribution column on `contract_log` / `contract_result` / `contract_state_change` tables, which (in general) did already boost performance on the "contract" API calls.

Before:
```
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|---------|
| contractsIdResults | /contracts/{id}/results | 1000 | 100.00 | 2285.05/s | 2285.05/s | 261.19ms | |
```

After:
```
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|---------|
| contractsIdResults | /contracts/{id}/results | 1000 | 100.00 | 2429.04/s | 2429.04/s | 255.00ms | |
```

We may also want to consider additional improvements at a later time; also, perhaps additional tables should also switch from using `payer_account_id` to `contract_id` as their distribution column.

2023-02-23 23:39 UTC, xin-hedera requested changes

2023-02-23 23:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        assertContractResult(recordItem, false);
```suggestion
        assertContractLogs(recordItem, false);
```

2023-02-23 23:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    private void assertContractLogs(RecordItem recordItem, boolean ethereum) {
we should remove the `boolean ethereum` function parameter from both `assertContractResults` and `assertContractLogs`. `recordItem` already provides  whether the transaction is ethereum tx or not. No need to change it in this PR.

2023-02-24 00:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.76.2__copy_transaction_hash_and_index_to_contract_log.sql
> +and r.payer_account_id = contract_log.payer_account_id;
Nice!   Done.

2023-02-24 00:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.76.3__contract_result_contract_id_not_null.sql
> +    alter column contract_id set default 0,
Done.

2023-02-24 00:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    transaction_index   integer not null default 0
Done.

2023-02-24 00:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +    contract_id          bigint       not null default 0,
Done.

2023-02-24 00:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        assertContractResult(recordItem, false);
Oops!  Nice catch.  Fixed, thanks.

2023-02-24 00:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    private void assertContractLogs(RecordItem recordItem, boolean ethereum) {
I created https://github.com/hashgraph/hedera-mirror-node/issues/5471 to track this; I could do the work, or it might be an initial issue for @jascks to handle.

2023-02-24 18:18 UTC, xin-hedera requested changes

2023-02-24 18:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +        on contract_result using hash (transaction_hash);
please revert format changes in this file, that's too much noise

2023-02-24 18:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +        add constraint contract_state_change__pk primary key (consensus_timestamp, contract_id, slot, payer_account_id);
```suggestion
    -- contract_state_change
    alter table if exists contract_state_change
        add constraint contract_state_change__pk primary key (consensus_timestamp, contract_id, slot);
```

2023-02-24 18:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  transaction_index: 1,
nit, better to default it to 0

2023-02-24 19:13 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +        on contract_result using hash (transaction_hash);
That change was not intended, and has been reverted.

2023-02-24 19:13 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +        add constraint contract_state_change__pk primary key (consensus_timestamp, contract_id, slot, payer_account_id);
Done.

2023-02-24 19:14 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  transaction_index: 1,
Done.

2023-02-24 19:41 UTC, xin-hedera requested changes

2023-02-24 19:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> -create index if not exists ethereum_transaction__hash on ethereum_transaction using hash (hash);
revert, obviously auto merge handled it worng

2023-02-24 19:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> -    on event_file using hash (hash);
revert, obviously auto merge handled it worng

2023-02-24 19:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> -create index if not exists ethereum_transaction__hash on ethereum_transaction using hash (hash);
Reverted; only 3 lines different from latest `main` version of this file are the 3 intended distribution columns for the 3 intended tables.

2023-02-24 19:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> -    on event_file using hash (hash);
See previous comment.

2023-02-24 20:17 UTC, xin-hedera approved these changes
LGTM

2023-02-24 20:18 UTC, xin-hedera commented
should update the PR title and description so as to help reviewers understand the major changes and why they are needed

2023-02-24 23:47 UTC, steven-sheehy requested changes

2023-02-24 23:47 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractResult.java
> +    private long contractId;
Why did this need to change? Was this from a previous iteration of the work and can be reverted?

2023-02-24 23:47 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.76.3__contract_result_contract_id_not_null.sql
> +update contract_result set contract_id = 0 where contract_id is null;
Why is this a separate migration? Can merge the two files into one. Over time, more migrations slows things down.

2023-02-24 23:53 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractResult.java
> +    private long contractId;
Citus requirement, distribution column has to be not null

2023-02-24 23:55 UTC, MarcKriguerAtHedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractResult.java
> +    private long contractId;
Without the change, the default value for the failed contracts (where the constructor is calling `clearContractID()` on the receipt/record) is a cxontract_id with null value.  This change has it have a value of 0 (which Citus requires, as @xin-hedera just indicated).

2023-02-25 00:00 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractResult.java
> +    private long contractId;
I see, makes sense.

2023-02-25 00:01 UTC, steven-sheehy approved these changes
LGTM

2023-02-25 00:01 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.76.3__contract_result_contract_id_not_null.sql
> +update contract_result set contract_id = 0 where contract_id is null;
I had not realized the processing of 2 files would be significant (compared to the actual migration time).  I've added this migration to the 1.76.2 .sql file (and removed the 1.76.3 file).

2023-02-25 00:03 UTC, xin-hedera approved these changes

2023-02-25 00:22 UTC, merged