HIP-584: Add acceptance tests for eth_call with token precompile logic
hashgraph/hedera-mirror-node pull request #5527
Opened 2023-03-02 15:11 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-13 08:48 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +    public void checkIfNonFungibleTokenIsToken() {
We can also add negative cases, where we check if a `regular account` is token or if an `empty address` is token.

2023-03-13 11:06 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertThat(delegatableContractId).isNotBlank();
It seems we try to fetch the KYC key of the NFT created in this test but the KYC key is both of type `ContractID` and `DelegatableContractID` at the same time. Isn't that strange?

2023-03-13 15:22 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/features/precompilecontract/precompilecontract.feature
> +#    @release @acceptance
Probably unnecessary comment?

2023-03-13 15:29 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertThatThrownBy(() -> mirrorClient.contractsCall(
I believe we should return `false` in this case. Having `Bad request` might suggest having a bug in executing the IsToken precompile.

2023-03-13 20:48 UTC, xin-hedera requested changes

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/build.gradle.kts
> +    implementation("com.esaulpaugh:headlong")
```suggestion
    testImplementation("com.esaulpaugh:headlong")
```

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +@Log4j2
```suggestion
@CustomLog
```

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +    private final long firstNftSerialNumber = 1;
make it static

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        networkTransactionResponse = fileClient.createFile(new byte[] {});
why not create the file with its content so we only need one transaction?

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +    @Then("Check if fungible token is frozen")
should the description be `Verify fungible token isn't frozen`?

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertThat(ledgerId).isEqualTo("0x01");
ledgerId is different per network

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertThat(ledgerId).isEqualTo("0x01");
pull the common code to a function that both test cases call

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertFalse(token.isEmpty());
should assert token address match

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertThat(expiryInfo.size()).isEqualTo(3);
make the two `getExpiryTokenInfo` test cases call a common function.

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +
need an `@After` method to clean up the resources (delete account, contract, tokens...)

2023-03-13 20:48 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/precompilecontract/precompilecontract.feature
> +@contractbase @fullsuite
perhaps placing the feature file to the `features/contract` folder is a better choice, also rename the file to just `precompile.feature` since it's put under the `contract` folder

2023-03-14 10:13 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/Parent.sol/Parent.json
> +  "deployedBytecode": "0x60806040526004361061005e5760003560e01c80636896fabf116100435780636896fabf146100ba5780637998a1c4146100e35780638070450f1461012257600080fd5b80630419eca51461006a5780635e01eb5a1461
Were there any changes required to Parent.sol?

2023-03-14 12:33 UTC, natanasow commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/Parent.sol/Parent.json
> +  "deployedBytecode": "0x60806040526004361061005e5760003560e01c80636896fabf116100435780636896fabf146100ba5780637998a1c4146100e35780638070450f1461012257600080fd5b80630419eca51461006a5780635e01eb5a1461
There are no changes in the Parent and Child contracts. The different bytecode might be due to the changed hardhat's optimizer value.

2023-03-14 12:45 UTC, natanasow commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertFalse(token.isEmpty());
Precompile method returns [`struct TokenInfo`](https://github.com/hashgraph/hedera-mirror-node/blob/eb4a870d2b8a1d807806f3c4a4c9868146bc9816/hedera-mirror-test/src/test/resources/solidity/contracts/IHederaTokenService.sol#L173) that doesn't contain token's address.

2023-03-16 19:23 UTC, xin-hedera requested changes

2023-03-17 03:45 UTC, steven-sheehy requested changes

2023-03-17 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +    }
Let's keep it OO.

```suggestion
    public boolean getResultAsBoolean() {
        return Long.parseUnsignedLong(result.replace("0x", ""), 16) > 0;
    }
```

2023-03-17 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/package-lock.json
Usually it's a good practice to check in the package-lock.json. But here this is just a test project used to generate bytecode so I don't think it's worth the 13K lines. Please add to .gitignore.

2023-03-17 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/IHederaTokenService.sol/IHederaTokenService.json
I don't think we should copy these common contracts `HederaTokenService`, `IHederaTokenServide`, `HederaResponseCodes`into this repo. They are already present at https://github.com/hashgraph/hedera-smart-contracts/tree/main. Copying them increases the lines of code and increases the chance that they will get out of sync. We just need the raw bytecode and some docs on how to re-generate our custom contracts. I think we should just document it in the solidity README where to get these boilerplate contracts and produce the custom contract.

In the future, we should publish the `@hashgraph/smart-contracts` to NPM so we can share them via package registry.

2023-03-17 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/contracts/PrecompileTestContract.sol
> +contract PrecompileTestContract is HederaTokenService {
This looks to mostly duplicate the test contract in the k6 module. Can we consolidate the two and provide a link in k6 to this solidity package.

2023-03-17 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/precompilecontract/precompilecontract.feature
We should put in `feature/contract/precompile.feature`

2023-03-17 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/precompilecontract/precompilecontract.feature
> +        Then I mint and verify a nft
The cost to create tokens, contracts, NFTs, etc is quite high and the existing acceptance tests cost 260 hbars and take awhile to run. Can we optimize the costs/time by reusing the tokens, etc. for [ERC](https://github.com/hashgraph/hedera-mirror-node/pull/5559/files) and precompile tests?

2023-03-20 10:37 UTC, natanasow commented on hedera-mirror-test/src/test/resources/features/precompilecontract/precompilecontract.feature
> +        Then I mint and verify a nft
We can apply several options, but I think none is a good solution :confused: 
- we can put all the suites (erc and precompiles) in one class
- if we use separate suites, we can not create deterministic token ids, so we have to find a way to share them between suites (create the mappings public, not cool)
- we can create an extra suite only for token creation, but this will tightly couple the erc and precompile suite, and we will be not able to run them separately

I'm open to suggestions and implementations, but right now I don't know a good solution that will not tightly couple erc and precompile suites.

2023-03-31 07:44 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        ContractCallResponse response = mirrorClient.contractsCall(
On each place we make a contract call, we should add a check like [this](https://github.com/hashgraph/hedera-mirror-node/blob/9381ef88af3135918df3702111f213bea21a5019/hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java#L146). This will protect us from failing tests, in case a given environment or a mirror-node instance itself, does not have sidecars enabled.

2023-04-07 03:07 UTC, steven-sheehy requested changes

2023-04-07 03:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +        Then Get token default freeze of fungible token
It's not clear from reading this what a `Get` does. Is it a HAPI query? Mirror node JS REST API? Web3 API? All invocations of contract call should mention that it's calling the mirror node contract call REST API.

```suggestion
        Then the contract call REST API should return the token default freeze for a fungible token
```

2023-04-07 03:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +        Then Check if fungible token is kyc granted
Any subsequent checks after a `Then` should be an `And`.

```suggestion
        Given I unfreeze token for evm address
        Then Check if token is unfrozen for evm address
        And Check if fungible token is kyc granted
```

2023-04-07 03:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +            | 200            |
Unused

```suggestion
```

2023-04-07 03:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +    private Tuple baseGetInformationForTokenChecks(ContractCallResponse response) throws Exception {
We should move all private helper methods to the bottom after the `@Given/Then/And` public methods.

2023-04-07 03:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assumeTrue(acceptanceTestProperties.isContractTraceability());
This would fail the entire acceptance tests.

2023-04-07 03:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +    @release @acceptance
```suggestion
@contractbase @fullsuite @acceptance
Feature: Precompile Contract Feature

    @precompile @web3
```

2023-04-10 14:52 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +    @contractbase @fullsuite @acceptance @precompile @web3
You can delete `@contractbase @fullsuite @acceptance` -> the first two are inherited from the declaration above and we may not want these tests to run at acceptance level every time.

2023-04-10 15:04 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +        Given I unfreeze a non fungible token
We should verify here using mirror-node's REST API that this transactions has been imported successfully, as we did [here](https://github.com/hashgraph/hedera-mirror-node/pull/5780) for the mint transaction. Otherwise the unfreeze HAPI transaction might not have been yet imported in the mirror-node, while we check the token's frozen status.

2023-04-10 15:05 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/features/contract/precompile.feature
> +        Given I freeze a non fungible token
We should verify here using mirror-node's REST API that this transactions has been imported successfully, as we did https://github.com/hashgraph/hedera-mirror-node/pull/5780 for the mint transaction. Otherwise the freeze HAPI transaction might not have been yet imported in the mirror-node, while we check the token's frozen status.

2023-04-10 21:46 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        log.info("Created file {} to hold contract init code", fileId);
nit: Can remove since in my PR https://github.com/hashgraph/hedera-mirror-node/pull/5796 moves create file logs into the `FileClient.

2023-04-10 21:47 UTC, steven-sheehy commented
Looks good besides Ivan's comments

2023-04-11 14:28 UTC, steven-sheehy approved these changes
LGTM

2023-04-11 14:43 UTC, xin-hedera approved these changes
LGTM

2023-04-11 14:51 UTC, merged