5318 graphql account alias query
hashgraph/hedera-mirror-node pull request #5553
Opened 2023-03-06 07:13 UTC by syed-bcw

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-03-14 14:30 UTC, edwin-greene commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/controller/AccountControllerTest.java
> +import java.util.concurrent.TimeUnit;
Looks like TimeUnit isn't used. Can you optimize imports? It should place the Hex import below the license as well.

2023-03-14 14:31 UTC, edwin-greene commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/controller/AccountControllerTest.java
> +
Can remove or add an invalid evm address test.

2023-03-14 14:41 UTC, edwin-greene commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/util/GraphQlUtilsTest.java
Can you add a test that documents what happens when `decodeEvmAddress` is called with an empty string and null?

2023-03-14 14:53 UTC, edwin-greene commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/util/GraphQlUtilsTest.java
> +        String evmAddress = "0000000000000000000000000000000000000001";
Should this also work with `0x` prefixed addresses? If so, we should have a test with an input like  `0x00000000000000000000000000000000000000001`.

2023-03-14 23:18 UTC, steven-sheehy requested changes

2023-03-14 23:18 UTC, steven-sheehy commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/controller/AccountController.java
> +            byte[] evmBytes = decodeEvmAddress(evmAddress);
One new special case for [HIP-583](https://github.com/hashgraph/hedera-improvement-proposal/blob/1cb3c7ce6c19874caa80c667ad33fd9c8129dd38/HIP/hip-583.md) that we're tackling concurrently in #5507 is that we should check if the EVM address is an entity ID encoded into an EVM address. This occurs when the leftmost 12 bytes are zero. If so, we can directly convert to EntityID and skip the EVM address lookup.

2023-03-14 23:18 UTC, steven-sheehy commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/controller/AccountController.java
> +            return Mono.justOrEmpty(account);
Remove the fallback behavior.
```suggestion
            return Mono.justOrEmpty(entityService.getByEvmAddress(evmBytes, EntityType.ACCOUNT)
                            .map(accountMapper::map));
```

2023-03-14 23:18 UTC, steven-sheehy commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/controller/AccountControllerTest.java
> +    void missingEvmAddress() {
Recommend making `missing()` a parameterized test and test each input format.

2023-03-14 23:18 UTC, steven-sheehy commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/controller/AccountControllerTest.java
> +    void successByEvmAddress() {
Should make parameterized with two booleans: one to control 0x prefix and another to control lowercase vs uppercase.

2023-03-14 23:18 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/postman.json
> +					"",
Think all this logic is removed if fallback alias to entity ID goes away.

2023-03-15 16:23 UTC, steven-sheehy commented on charts/hedera-mirror-graphql/postman.json
> +			"value": "0000000000000000000000000000000000000062"
These new EVM address and alias tests will fail in CI since they won't exist in the demo bucket. We should default these variables to empty and only verify the results if they are non-empty. See https://medium.com/apis-with-valentine/how-to-reuse-tests-and-skip-collection-tests-in-postman-da47c50444c8

2023-03-15 19:34 UTC, syed-bcw commented
@edwin-greene , @steven-sheehy - Addressed all changes, need rereview 😊

2023-03-16 00:36 UTC, steven-sheehy commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/util/GraphQlUtils.java
> +                    "provided");
nit: could simplify
```suggestion
            throw new IllegalArgumentException("Unable to decode evmAddress: " + evmAddress);
```

2023-03-16 00:36 UTC, steven-sheehy commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/controller/AccountController.java
> +            byte[] evmBytes = decodeEvmAddress(evmAddress);
This logic was missed. Should be done in service layer.

2023-03-16 02:01 UTC, syed-bcw commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/controller/AccountController.java
> +            byte[] evmBytes = decodeEvmAddress(evmAddress);
I thought that I can skip this logic check since this will be handled by HIP-583, let me add that check back in service layer

2023-03-16 02:01 UTC, syed-bcw commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/controller/AccountController.java
> +            byte[] evmBytes = decodeEvmAddress(evmAddress);
I thought that I can skip this logic check since this will be handled by HIP-583, let me add that check back in service layer

2023-03-16 04:00 UTC, syed-bcw commented on hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/controller/AccountController.java
> +            byte[] evmBytes = decodeEvmAddress(evmAddress);
@steven-sheehy - made recommended changes 😊

2023-03-16 04:02 UTC, syed-bcw commented on hedera-mirror-graphql/src/test/java/com/hedera/mirror/graphql/util/GraphQlUtilsTest.java
@edwin-greene - Done 😊

2023-03-16 17:32 UTC, steven-sheehy submitted a review, later dismissed
LGTM! Thanks for your contribution 🙏🏻

2023-03-16 17:34 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2023-03-16 17:36 UTC, steven-sheehy commented
@syed-bcw Whoops, just noticed that all of the commits aren't GPG [signed](https://docs.github.com/articles/about-gpg/). Do you mind fixing that? You're welcome to squash commits beforehand if it makes it easier.

2023-03-16 18:23 UTC, syed-bcw commented
> @syed-bcw Whoops, just noticed that all of the commits aren't GPG [signed](https://docs.github.com/articles/about-gpg/). Do you mind fixing that? You're welcome to squash commits beforehand if it makes it easier.

@steven-sheehy - verified all commits, see if in good state 😊

2023-03-16 19:25 UTC, steven-sheehy approved these changes

2023-03-16 19:27 UTC, merged