add Snyk to Security CI
hashgraph/hedera-mirror-node pull request #5554
Opened 2023-03-06 11:40 UTC by isavov

**Description**:
This PR integrates and extends the Snyk gradle plugin to add Snyk scanning task to the gradle setup and integrate it in CI.
Snyk Open Source and Snyk Code scanning are implemented for pull requests and the monitored snapshot is updated on merge to main.

* Add gradle plugin
* Add jobs to the Security action

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-03-14 16:56 UTC, nathanklick commented on .github/workflows/security.yml
> +        if: ${{ !cancelled() }}
```suggestion
        if: ${{ !cancelled() && always() }}
```

2023-03-14 16:56 UTC, nathanklick commented on .github/workflows/security.yml
> +        if: ${{ !cancelled() }}
```suggestion
        if: ${{ !cancelled() && always() }}
```

2023-03-14 20:14 UTC, steven-sheehy requested changes
Verified the workflow ran: https://github.com/hashgraph/hedera-mirror-node/actions/runs/4419597443

2023-03-15 14:03 UTC, isavov commented on .github/workflows/security.yml
> +        run: npm install -g snyk snyk-to-html @wcj/html-to-markdown-cli
I think it shouldn't be too different, as the gradle plugin checks for the presence of a system wide install of snyk and if there isn't one it downloads it in the project's dir. Anyways this is a legacy step from a previous version of the implementation where I tried to run a separate snyk scan and generate a separate report for each project within mirror-node (where a separate snyk binary would be downloaded for each) and is not needed anymore, so I'm removing it.

2023-03-15 14:54 UTC, steven-sheehy commented
DCO check failing

2023-03-15 16:29 UTC, isavov commented
> DCO check failing

Fixed and reviews addressed

2023-03-16 03:45 UTC, steven-sheehy approved these changes
LGTM

2023-03-16 15:20 UTC, xin-hedera approved these changes
LGTM

2023-03-16 15:23 UTC, merged