Properly populate EVM address on "/accounts" API calls
hashgraph/hedera-mirror-node pull request #5556
Opened 2023-03-08 06:09 UTC by MarcKriguerAtHedera

**Description**:
This PR modifies the `/api/v1/accounts` APIs in order to property populate the evm addresses field.
* Convert `{id}` to usual x.y.z format (and look up the converted entity id( for all `/api/v1/accounts/{id}/*` APIs,  where the `{id}` is a hexadecimally encoded 20-byte entity id.
* Populate the `evm_address` field with the `alias` value in the response of `/api/v1/accounts` and `/api/v1/accounts/{id}` APIs, if the `alias` field is a 40 character (20 bytes) EVM address and `evm_address` field is `null,`
* Populate the `evm_address` field with the account num alias (i.e. long zero entity id) if it's `null` and not the scenario from above.

**Related issue(s)**:

Fixes #5507

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (integration/spec tests)

2023-03-09 19:23 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/token-balance-limit-with-alias-into-evm-address.json
> +      "responseStatus": 200,
Can you add the non-0x form of the address to the test? 
`/api/v1/accounts/0000000000000000000000000000000000000008`

2023-03-09 19:59 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/token-balance-limit-with-alias-into-evm-address.json
> +      "responseStatus": 200,
Done.  (For consistency, I did this for both sets of URLs in this file.)

2023-03-10 16:04 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/alias-into-evm-address.json
> +{
To simplify this test case, can you remove the setup components that do not demonstrate the new functionality? (Things not related to alias and evm addresses that are not needed to prove that the new functionality is working correctly.)

2023-03-10 16:07 UTC, edwin-greene commented on hedera-mirror-rest/accounts.js
> +  let alias = base32.encode(row.alias);
Looks like `alias` can be `const`

2023-03-10 16:10 UTC, edwin-greene commented on hedera-mirror-rest/accounts.js
> +    if (alias && row.alias.length == 20) {
Might be nice to have a const `ethereum_address_length = 20` or something like that to underscore what the 20 signifies.

2023-03-13 17:39 UTC, xin-hedera requested changes

2023-03-13 17:39 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    if (alias && row.alias.length == 20) {
should set evm_address to hex format alias when the alias length is 20 bytes and evm_address is null regardless if the entity is an `ACCOUNT` or `CONTRACT

2023-03-14 17:53 UTC, jnels124 commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/nfts/specific-token.id.json
> +    "/api/v1/accounts/0.0.1001/nfts?token.id=gte:2500"
did you forget to add the long zero version for the second url?

2023-03-14 17:53 UTC, jnels124 commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/nfts/spenderid-lower-bound.json
> +    "/api/v1/accounts/0.0.1001/nfts?spender.id=gte:2001"
forget the long zero version?

2023-03-16 00:05 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/alias-into-evm-address.json
> +{
Done.

2023-03-16 00:05 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/accounts.js
> +  let alias = base32.encode(row.alias);
Done.

2023-03-16 00:05 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/accounts.js
> +    alias: alias,
Done.

2023-03-16 00:06 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/accounts.js
> +    if (alias && row.alias.length == 20) {
Done.

2023-03-16 00:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/accounts.js
> +    if (alias && row.alias.length == 20) {
Done (I just removed the tow.type check; let me know if I should restrict this behavior to just those two types of entities, but I don't think the call to `/accounts` woud return any other types than accounts/contracts).

2023-03-16 00:09 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/nfts/specific-token.id.json
> +    "/api/v1/accounts/0.0.1001/nfts?token.id=gte:2500"
It wasn't so much "forgetting" as just adding one call with the long zero version for every type of API call (and not necessarily every single API call being tested).   But I went ahead and added it for the URLs in this file (and the next), since you asked.

2023-03-16 00:09 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/nfts/spenderid-lower-bound.json
> +    "/api/v1/accounts/0.0.1001/nfts?spender.id=gte:2001"
See previous comment.

2023-03-16 15:12 UTC, edwin-greene submitted a review, later dismissed
Looks good to me.

2023-03-16 15:38 UTC, xin-hedera requested changes

2023-03-16 18:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/accounts.js
> +  const ethereum_address_length = 20;
Done.

2023-03-16 19:20 UTC, xin-hedera approved these changes
LGTM

2023-03-16 21:27 UTC, edwin-greene approved these changes

2023-03-17 02:39 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/no-relationships.json
> +    "/api/v1/accounts/0x00000000000000000000000000000000000003e9/tokens?token.id=0.1.1135"
I'm not sure it's necessary to add an EVM address URL to every spec. Just one per distinct endpoint should be sufficient as there is an increased cost in test runtime without any gain in test coverage. But if it's too much work to undo can keep.

2023-03-17 02:39 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
One change that we still need as part of HIP-583 that unfortunately wasn't called out in the ticket is to decouple the shard and realm from the `account-num alias` AKA `long zero alias`. We need to modify `entityId.js` to not parse out the shard and realm but just verify that the first 12 bytes (or first 24 chars) are zero. We can also consider for a follow up.

2023-03-17 17:17 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/accounts.js
Follow-up sounds goods to me.

2023-03-17 21:13 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/no-relationships.json
> +    "/api/v1/accounts/0x00000000000000000000000000000000000003e9/tokens?token.id=0.1.1135"
As we discussed at today's scrum, I will remove most of the EVM address URLs, except for one in the "no-params.json" (for each directory).   Those retained:

- hedera-mirror-rest/__tests__/specs/accounts/no-params.json (no input URL, but just output from `/api/v1/accounts`
- ./hedera-mirror-rest/__tests__/specs/accounts/{id}/allowances/crypto/no-params.json
- ./hedera-mirror-rest/__tests__/specs/accounts/{id}/allowances/tokens/no-params.json
- ./hedera-mirror-rest/__tests__/specs/accounts/{id}/nfts/no-params.json
- ./hedera-mirror-rest/__tests__/specs/accounts/{id}/no-params.json
- ./hedera-mirror-rest/__tests__/specs/accounts/{id}/rewards/no-params.json
- ./hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/no-params.json

2023-03-17 22:42 UTC, steven-sheehy approved these changes
LGTM

2023-03-17 22:44 UTC, xin-hedera approved these changes

2023-03-20 03:38 UTC, merged