05498 estimate gas service
hashgraph/hedera-mirror-node pull request #5557
Opened 2023-03-10 12:46 UTC by nikolovyanko

**Description**:

**Related issue(s)**:

Fixes #5498 5497

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-07 12:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> -    private Mono<GenericErrorResponse> unsupportedOpResponse(final UnsupportedOperationException e) {
We shouldn't delete this handling until we provide support for precompiles. We throw such an exception also there. The JSON-RPC relay use this Unsupported error to provide fallback logic for eth_call and potentially eth_estimateGas

2023-04-07 14:00 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            long gasUsed = err ? providedGasLimit : txnResult.getGasUsed();
We should update the custom metric for gasPerSecond at each binary search iteration, so that we show adequately the actual gas that is used. We can call the `onComplete` method here, but it makes sense to rename it to something like `updateGasMetric`.

If we have an error we should pass the `CallType.ERROR`

2023-04-10 14:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        validateTxnResult(txnResult, params.getCallType());
Here we would update the `gasMetrics` for a second time (the first being the update in the last do-while cycle). We can mitigate this by extracting the actual validation that throws an exception in a separate method (probably called  `validateTxnResult`) and call that method here. We can also change the naming of the current `validateTxnResult` -> `onComplete` since it makes more than a validation.

2023-04-11 14:18 UTC, david-bakin-sl reviewed
I don't see any tests that test the _binary search_ aspect of things: that it converges, that it converges to something close to the right value, that it stops when the min-diff is reached.  It's not clear from these tests, as written, how you even know that the binary search _did anything_.

2023-04-11 14:18 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        int minDiffBetweenIterations = 1200;
This should be a constant.  Preferably a static constant named MIN_DIFF... etc so it stands out as a constant?  Alternatively, it should be a dynamic property you can set when the mirror node starts.  (Services repo has these things in a file called `bootstrap.properties` and they're also overridable per-environment (like mainnet vs testnet) - don't know if the mirror node has this sort of thing too.)

2023-04-11 14:18 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        } while (lo + 1 < hi);
Is there any value in _counting_ the number of iterations and emitting that as a metric of some kind too?  (A gauge?)  Or maybe just _logging_ it (so that it isn't _sampled_)?  Sounds like something we'd like to look at, especially at first ...

2023-04-11 14:18 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            txnResult = processEthTxn(params);
This is certainly the way a binary search is typically written.  But can the structure be improved here for us?  Can the binary search part be abstracted away from the `processEthTxn` (+ metrics) part?  Maybe the `processEthTxn`(+ metrics) part is a lambda you _pass_ to a binary search routine?  Or vice versa - maybe the binary search is a _generator_ of "low,mid,hi" that is called in a loop that just does `processEthTxn` (+ metrics) until convergence?  In other words, some structuring/software engineering so that the `processEthTxn` isn't "lost" in the middle of this binary search and the binary search itself isn't obfuscated by it.

2023-04-11 14:18 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            txnResult = processEthTxn(params);
For example, that would make it easier to test the _binary search_ algorithm without having to stub/mock/whatever `processEthTxn` ...

2023-04-11 14:18 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var expectedGasUsed = "543a";
it's not clear to me where, in these several tests, the `expectedGasUsed` comes from.  Maybe explain that?  (It's also not clear to me why these `expectedGasUsed` values are _strings_ and not _numbers_.

2023-04-12 03:38 UTC, steven-sheehy requested changes

2023-04-12 03:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            boolean err = !txnResult.isSuccessful() || txnResult.getGasUsed() < 0;
Why would we keep retrying if the transaction is unsuccessful for any reason besides insufficient gas? If the payload had invalid input or if an entity/state is missing corrupt, or any other unrecoverable error we should fail fast and exit the loop. Or do these type of errors bubble up as uncaught exceptions?

2023-04-12 03:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        final var providedGasLimit = params.getGas();
What happens if I supply `Long.MAX_VALUE` as a parameter? Will that be rejected? If not, how many loop iterations will occur? The default value of gas is 120M, which already seems high to me as it is a lot higher than consensus nodes. I think we should add `@Max` to the parameter and set it to a lower number more inline with consensus nodes.

2023-04-12 03:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            txnResult = processEthTxn(params);
Executing an expensive EVM operation in a loop scares me, especially with unbounded gas input. This seems like an attack vector. Why can't we just execute the transaction with a bit higher gas then return the gasUsed? Seems less expensive than executing it many times.

2023-04-12 14:25 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        final var providedGasLimit = params.getGas();
Also where does this `@Max` come from?

2023-04-12 14:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        final var providedGasLimit = params.getGas();
[JSR-303 bean validation spec](https://beanvalidation.org/1.0/spec/)

2023-04-13 21:15 UTC, steven-sheehy requested changes

2023-04-13 21:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                        gas -> doProcessCall(params, gas),
```suggestion
                        callProcessor,
```

2023-04-13 21:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                        properties.getDiffBetweenIterations());
It's a class property, no need to pass it around via methods.
```suggestion
```

2023-04-13 21:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    private long binarySearch(LongFunction<HederaEvmTransactionProcessingResult> CallProcessor, long lo, long hi,
```suggestion
    private long binarySearch(LongFunction<HederaEvmTransactionProcessingResult> callProcessor, long lo, long hi,
```

2023-04-13 21:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        LongFunction<HederaEvmTransactionProcessingResult> callProcessor = gas -> doProcessCall(params, gas);
Does this callProcessor really buy us anything? The only benefit is it allows us to not pass around `params`, but then we now have to pass around the `callProcessor`. Better to just invoke doProcessCall directly where it's needed and pass around params.

2023-04-13 21:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +                .isEqualTo(OK);
Add a test for gas=Long.MAX_VALUE

2023-04-13 21:17 UTC, steven-sheehy commented
There's a code smell as well

2023-04-19 03:47 UTC, steven-sheehy requested changes

2023-04-19 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    @Getter
```suggestion
    @Getter
    @Positive
```

2023-04-19 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    /**Feature work: move to another class and compare performance with interpolation algo.
Feature -> Future

2023-04-19 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        HederaEvmTransactionProcessingResult initialCallResult = doProcessCall(params, params.getGas());
I think we said the first simulation would be at max gas 15M?

2023-04-19 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>          counter.increment(result.getGasUsed());
We should add an iterations label to the metric in constructor. Then for eth_call iterations=1 but eth_estimateGas it would be the number of total calls to estimate.

2023-04-19 18:11 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage = 100;
`maxGasRefundPercentage` change from 20% to 100 % in order to get the actual gasUsed by the transaction not the the refunded one calculated in `HederaEvmTxProcessor.calculateGasUsedByTX`.

2023-04-20 02:57 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage = 100;
I was under the impression that this is _global_ to the mirror node, is that the case?  If so, it may affect things _besides_ `eth_estimateGas`.

2023-04-20 08:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage = 100;
`maxGasRefundPercentage` - this property is used only in `web3` module and does not affect anything else. It was copied from services so that we can dynamically adjust the refund percentage.

2023-04-20 12:44 UTC, nikolovyanko commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var expectedGasUsed = "543a";
The `ContractCallService` returns the gasUsed hexed encoded, indeed, switching at least the `expectedGasUsed` to numeric will be more verbose. As for the value of `expectedGasUsed` TBH there's no straight way(or I can't think of one) to obtain appropriate value, so it's hardcoded based on previous estimate of the function. This for sure needs to be improved in following PR for example, which refactors the whole test class.

2023-04-20 12:45 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        } while (lo + 1 < hi);
Added iteration count metric.

2023-04-20 12:45 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>          counter.increment(result.getGasUsed());
Added.

2023-04-20 13:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var expectedGasUsed = "543a";
Usually "more verbose" isn't considered the most important issue for tests (or for code for that matter, or we wouldn't be using Java): more _understandable_ is.  And gas used is traditionally a decimal number, not a hex encoded string.  

The conversion to hex isn't that bad anyway, IMO: - `stripStart(HexFormat.of().toHexDigits(21555), '0')` - which can be encapsulated in a small one-line function.  (`stripStart` is from `org.apache.commons.lang3.StringUtils`)

But it's up to you.

2023-04-20 13:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage = 100;
But `eth_call` is in the web3 module.  Is the gas refund percentage not used there?

If we can use it here I strongly suggest adding a work item to _not_ use it in the future: seems fragile, also non-local (to eth_estimateGas).  I'd really prefer to see the actual gas returned in the transaction result from the evm module, or some other "legitimate" approach to getting the actual gas used, rather than this technique (which I guess is fine just now when we have a timing limitation between deployment of the evm module from over in the services repo).

2023-04-20 14:13 UTC, nikolovyanko commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var expectedGasUsed = "543a";
I added the suggested conversion. Regarding the other concern with the hard coded values, you have any idea for more suitable way to do it?(The main challenge is that we cannot estimate the `gasUsed` accurately, as the `ContractCallService` does not expose the whole `HederaEvmTransactionProcessingResult` object, so we can't  make an informed guess of the gas).

2023-04-20 14:43 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var expectedGasUsed = "543a";
No, can't think of any other way.  The suggestion was simply to leave a comment "expected gaslimit comes from executing this same contract on testnet" or whatever.

2023-04-20 21:50 UTC, steven-sheehy requested changes

2023-04-20 21:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    private static final LongFunction<String> hexValueOf = value -> stripStart(HexFormat.of().toHexDigits(value), "0");
nit: We should stick to tuweni if we can for such byte manipulation `Bytes.ofUnsignedLong(val).toUnprefixedHexString()`

2023-04-20 21:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        iterationCounter.increment(iterationsDone);
This iteration counter is inaccurate as it doesn't allow us to differentiate between different iteration buckets. So a 10 RPS with one iteration each will appear the same as a 1 RPS with 10 iterations each. This is why I said to add an iteration label to the existing metric. This could cause a cardinality explosion but we know that the number of iterations is between 1-10 so it will be fine.

To do this, you have to change the counter be able to create dynamic tags. Remove the metric map and do the following:

```java
    private final Counter.Builder gasCounter = Counter.builder("hedera.mirror.web3.call.gas")
        .description("The amount of gas consumed by the EVM");
```

Then in `updateGasMetric` do:
```java
    gasCounter.tag("type", callType.toString())
              .tag("iteration", String.valueOf(iterations))
              .register(meterRegistry);
```

register will internally keep a map of metric name + tags and reuse existing.

2023-04-21 13:28 UTC, steven-sheehy commented
Looks like postman.json in web3 chart needs to be fixed after tightened gas validation. This is why chart workflow is failing.
```
❏ Negative tests
↳ Invalid request for contracts/call
  POST http://hedera-mirror-zeb7uj0vcp-web3:80/api/v1/contracts/call [400 Bad Request, 507B, 583ms]
  1. Invalid request

┌─────────────────────────┬────────────────────┬───────────────────┐
│                         │           executed │            failed │
├─────────────────────────┼────────────────────┼───────────────────┤
│              iterations │                  1 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│                requests │                  1 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│            test-scripts │                  1 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│      prerequest-scripts │                  0 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│              assertions │                  1 │                 1 │
├─────────────────────────┴────────────────────┴───────────────────┤
│ total run duration: 687ms                                        │
├──────────────────────────────────────────────────────────────────┤
│ total data received: 426B (approx)                               │
├──────────────────────────────────────────────────────────────────┤
│ average response time: 583ms [min: 583ms, max: 583ms, s.d.: 0µs] │
└──────────────────────────────────────────────────────────────────┘

  #  failure         detail                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                  
 1.  AssertionError  Invalid request                                                                                                                                                                                                                                                                              
                     expected 'from field invalid hexadecimal stringto field invalid hexadecimal stringvalue field must be greater than or equal to 0gasPrice field must be greater than or equal to 0gas field must be greater than or equal to 21000' to include 'gas field must be greater than or equal to 0' 
                     at assertion:0 in test-script                                                                                                                                                                                                                                                                
                     inside "Negative tests / Invalid request for contracts/call"       
```

2023-04-25 16:59 UTC, david-bakin-sl reviewed
Going to wait for the new search class/method you showed me this morning to review this class and its tests.

2023-04-25 16:59 UTC, david-bakin-sl commented on docs/configuration.md
> +`hedera.mirror.web3.evm.diffBetweenIterations`              | 1200                                               | The gas value difference between consecutive iterations in the binary search perform
Can this name be improved?  I'm bad at names, but it should include at least the word "gas"? And maybe something like "threshold" or "maxThreshold" instead of "diff"?  Maybe something about "stopping"?  

Ok, this is not what you want, but something on the way there: "estimateGasIterationThreshold"?

The comment field might include something about getting within the 20% refund limit.

2023-04-25 16:59 UTC, david-bakin-sl commented on docs/configuration.md
> +`hedera.mirror.web3.evm.expirationCacheTime`                | 10m                                                | Maximum time for contract bytecode's caching
Name should include units.

2023-04-25 16:59 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage = 100;
I get this now but still suggest leaving a comment here, e.g., "used by eth_estimateGas only"

2023-04-25 16:59 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> +                .gas(120000000L)
no longer the right limit?

2023-04-25 16:59 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                .gas(120000000L)
no longer the right limit?

2023-04-25 19:50 UTC, david-bakin-sl commented on docs/configuration.md
> +`hedera.mirror.web3.evm.expirationCacheTime`                | 10m                                                | Maximum time for contract bytecode's caching
Ah, TY, I don't think services works that way

2023-04-26 11:46 UTC, nikolovyanko commented on docs/configuration.md
> +`hedera.mirror.web3.evm.diffBetweenIterations`              | 1200                                               | The gas value difference between consecutive iterations in the binary search perform
`estimateGasIterationThreshold` sounds good to me :D

2023-04-26 11:47 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxGasRefundPercentage = 100;
Done.

2023-04-26 22:17 UTC, steven-sheehy requested changes

2023-04-26 22:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                params.getGas());
It's possible that gas param is greater than gasUsedByInitialCall, right? We should have some sanity checks in estimator to ensure that lo <= hi and to either throw an error, swamp them, or clamp it.

2023-04-26 22:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +            metricUpdater.accept(transactionResult, ++iterationsMade);
I don't think this provides an accurate metric this way since you'd have one entry for every iteration. We should have one metric recording at the end of the loop that has the accumulated gas and total iterations.

2023-04-26 22:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +            final BiConsumer<HederaEvmTransactionProcessingResult, Integer> metricUpdater,
There's a code smell here you need to fix.

2023-04-26 22:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +        } while (lo + 1 < hi);
Possibility for infinite loop here if hi never changes and lo keeps halving. We should put some fail safe on this while that stops after X iterations regardless.

2023-04-27 09:38 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +        } while (lo + 1 < hi);
I've set 20 as an iteration breaker, although the maximum  iterations I've notice while testing is 15.

2023-04-27 09:45 UTC, nikolovyanko commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                params.getGas());
TBH I couldn't reproduce a case where `params.GetGas > initialGasUsed` , as the very first call fails with `INSUFFICIENT_GAS`. However, just in any case I set sanity check before entering the search algorithm:
 `if (initialGasUsed >= params.getGas)  return the initialGasUsed.`

2023-04-27 14:40 UTC, david-bakin-sl reviewed
This is what I've got so far.  I want to build it and run the tests myself before finishing this review - so more coming later.

2023-04-27 14:40 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimatorTest.java
> +    private HederaEvmTransactionProcessingResult createTxnResult(final long gasUsed, final boolean randomize) {
It's not good practice to have randomization in unit tests.  Especially as here when the seed isn't set _and_ each test case is only run _once_; end result is you never know what you're testing.

Though the basic idea is a good one!  Instead, replace this with some kind of deterministic sequencing and expand the test cases to cover the different sequences you want to test.   ???

2023-04-27 15:19 UTC, steven-sheehy approved these changes
LGTM

2023-04-28 15:50 UTC, david-bakin-sl approved these changes
Very nice now.  Left a few comments for a subsequent cleanup, if you agree.  LGTM.

2023-04-28 15:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        if (gasUsedByInitialCall >= params.getGas()) {
We might have to look at this again in the near future (after this PR).  There's a difference between _gas used_ (as reported by the EVM, even with 100% rebate) and the gas you have to _supply_ as an _estimate_ when submitting a transaction.  That difference being mainly what you have to supply in excess if you're making nested contract calls and are subject to the 63/64th rule.

The amount returned by estimateGas to the user is the "amount needed to complete the transaction".  Not the amount that's going to actually be used.  So that can be _higher_.

I'm sorry I didn't catch this earlier.  I think we can begin with this result and refine it quickly.  (Your ideas?)

2023-04-28 15:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            throw new InvalidTransactionException(e.getMessage(), EMPTY, EMPTY);
I was wondering why this exception being thrown doesn't wrap the exception caught here (`e`) as is frequently done.  But `InvalidTransactionException` doesn't have a `cause` argument.  Is it just not needed?  (Or should it have one?)

2023-04-28 15:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var expectedGasUsed = 22693L;
I would still like to see a comment, at the top of the class probably, that explains to the future reader where these `expectedGasUsed` values come from.  In case something changes elsewhere and they need to be recomputed by some future developer.

2023-04-28 15:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    void estimateGasWithExactValue() {
name could be expanded to be some like `estimateGasWithExactValueProvidedAtCall` or something

2023-04-28 15:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimatorTest.java
> +     * @link BinaryGasEstimator is using slightly modified binary algorithm which is coupled to some exttend with the
This test is well done and the comment too is well done, TY.

2023-04-28 16:22 UTC, merged

2023-04-28 16:23 UTC, steven-sheehy commented
Let's get this in and @nikolovyanko please open tickets for any follow up items that need to be addressed.