HIP-584: Acceptance tests for eth_call with precompile logic
hashgraph/hedera-mirror-node pull request #5559
Opened 2023-03-10 15:07 UTC by mustafauzunn

**Description**:

 Acceptance tests using Cucumber, validating that eth_call with token precompile support works as expected

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-13 15:57 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        log.debug("Sent Account Allowance Approval");
Probably we can be more specific for the type of approval.

`log.debug("Sent Account Allowance Approval")` -> `log.debug("Sent Account Allowance Approval for Nft with id: { } and serialNumber: { }", nftId.getId(), nftId.getSerialNumber())`

2023-03-13 15:58 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        log.debug("Sent Account Allowance Approval");
`log.debug("Sent Account Allowance Approval") -> log.debug("Sent Account Allowance Approval for Token with id: { } and amount: { }", tokenId, amount))`

2023-03-13 15:59 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        log.debug("Sent Account Allowance Approval");
`log.debug("Sent Account Allowance Approval") -> log.debug("Sent Account Allowance Approval for all serial numbers for Nft with id: { }, tokenId)`

2023-03-14 11:24 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +    public void createNewToken(String symbol, int freezeStatus, int kycStatus) {
Probably rename to `createNewFungibleToken`

2023-03-14 15:32 UTC, xin-hedera requested changes

2023-03-14 15:32 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        createNewFungibleToken("TEST", TokenFreezeStatus.FreezeNotApplicable_VALUE, TokenKycStatus.KycNotApplicable_VALUE);
remove these methods

- `public void createNewFungibleToken(String symbol, int freezeStatus, int kycStatus)`
- `private void createNewFungibleToken(String symbol, int freezeStatus, int kycStatus, TokenType tokenType,
            TokenSupplyType tokenSupplyType, List<CustomFee> customFees)`

and just implement the logic in  this method.

2023-03-14 15:32 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        return createNewToken(symbol, freezeStatus, kycStatus, TokenType.FUNGIBLE_COMMON, TokenSupplyType.INFINITE, Collections
revert

2023-03-14 15:32 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public TokenId createNewNft(String symbol, int freezeStatus, int kycStatus, TokenSupplyType tokenSupplyType) {
common code should go to TokenClient, it's bad practice to provide it as a public method and call it in another feature class

2023-03-14 15:32 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +
need an `@After` method to clean up resources

2023-03-17 02:48 UTC, steven-sheehy requested changes

2023-03-17 02:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +    public static String hexToASCII(String str) throws DecoderException {
Would prefer these two new methods as non-static methods.

```suggestion
    public String getResultAsText() throws DecoderException {
```

2023-03-24 20:34 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +
just noticed all methods in this class (including the static methods) have the response itself as the parameter. we should make static methods non static and just access the `result` field inside without passing anything in

2023-03-24 20:54 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +
sounds good then, can leave it to a separate PR

2023-03-27 13:57 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-03-29 03:55 UTC, steven-sheehy commented
Testing this against integration which has the token precompile code and getting a contract revert for token owner. Can you please check?
```
Then I mint a serial number                                                                            # com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.mintNftToken()
2023-03-28T21:41:40.031-0600 INFO reactor-http-nio-3 c.h.m.t.e.a.c.MirrorNodeClient POST https://localhost/api/v1/contracts/call: 200 OK
And I call the erc contract via the mirror node REST API for token name                                # com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.nameContractCall()
2023-03-28T21:41:40.072-0600 INFO reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient GET https://localhost/api/v1/transactions/0.0.1353-1680061287-395724708: 200 OK
Then the mirror node REST API should return status 200 for the crypto transfer transaction   # com.hedera.mirror.test.e2e.acceptance.steps.AccountFeature.verifyMirrorAPICryptoTransferResponse(int)
2023-03-28T21:41:40.095-0600 INFO reactor-http-nio-4 c.h.m.t.e.a.c.MirrorNodeClient POST https://localhost/api/v1/contracts/call: 200 OK
And I call the erc contract via the mirror node REST API for token symbol                              # com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.symbolContractCall()
2023-03-28T21:41:40.136-0600 WARN ForkJoinPool-3-worker-3 c.h.h.s.TransactionReceiptQuery Retrying in 250 ms after failure with node 0.0.3 during attempt #1: OK
2023-03-28T21:41:40.235-0600 INFO reactor-http-nio-3 c.h.m.t.e.a.c.MirrorNodeClient POST https://localhost/api/v1/contracts/call: 200 OK
And I call the erc contract via the mirror node REST API for token decimals                            # com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.decimalsContractCall()
2023-03-28T21:41:40.291-0600 INFO reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient POST https://localhost/api/v1/contracts/call: 200 OK
And I call the erc contract via the mirror node REST API for token totalSupply                         # com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.totalSupplyContractCall()
2023-03-28T21:41:40.317-0600 INFO reactor-http-nio-4 c.h.m.t.e.a.c.MirrorNodeClient GET https://localhost/api/v1/accounts/CIQM5HVLXY5BGAVCNJS3CWS4DJ62VVL2NYXHWHVVJEHXQRZBF45ZTSQ: 404 NOT_FOUND
2023-03-28T21:41:40.341-0600 WARN ForkJoinPool-3-worker-1 c.h.h.s.TransactionReceiptQuery Retrying in 250 ms after failure with node 0.0.6 during attempt #1: RECEIPT_NOT_FOUND
2023-03-28T21:41:40.414-0600 WARN ForkJoinPool-3-worker-3 c.h.h.s.TransactionReceiptQuery Retrying in 500 ms after failure with node 0.0.5 during attempt #2: RECEIPT_NOT_FOUND
2023-03-28T21:41:40.423-0600 INFO reactor-http-nio-3 c.h.m.t.e.a.c.MirrorNodeClient POST https://localhost/api/v1/contracts/call: 400 BAD_REQUEST
2023-03-28T21:41:40.425-0600 ERROR reactor-http-nio-3 c.h.m.t.e.a.c.MirrorNodeClient Endpoint failed, returning: 400 Bad Request from POST https://localhost/api/v1/contracts/call
And I call the erc contract via the mirror node REST API for token ownerOf                             # com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.ownerOfContractCall()
org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest: 400 Bad Request from POST https://localhost/api/v1/contracts/call
at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:217)
at ✽.I call the erc contract via the mirror node REST API for token ownerOf(classpath:features/contract/erc.feature:14)
Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below:
Error has been observed at the following site(s):
*__checkpoint ⇢ 400 from POST https://localhost/api/v1/contracts/call [DefaultWebClient]
Original Stack Trace:
at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:217)
at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:207)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:478)
at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1245)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at io.netty.handler.codec.ByteToMessageDecode [...]

2023-03-29 20:23 UTC, xin-hedera approved these changes
LGTM

2023-03-29 21:02 UTC, merged