5404 Shard Transaction Hash v1
hashgraph/hedera-mirror-node pull request #5560
Opened 2023-03-10 16:49 UTC by jnels124

**Description**:
shard transaction hash
* migration to create 32 shard tables
* create batch persister for transaction hash
* add integration tests for new persister
* update rest api to search shards correctly

**Related issue(s)**:

Fixes #5404 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-13 22:37 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    log.error("Errors occurred processing sharded table {}. parent status {} successful shards {} " +
We should alert on this log

2023-03-13 22:39 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                            .persist(data.getValue());
calling persist here instead of persistItems will cause a new metric to be created for the insert on each shard table. It will also generate a new log entry for each shard insert. If we want just one metric for the overall insert that is easy to change.

2023-03-13 22:50 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +    private final Map<String, ThreadState> threadConnections = new ConcurrentHashMap<>();
Obviously, this implies only one thread can call persist on this inserter. If multiple threads call, then there is the potential for items not ready to be committed from the second run are committed with the first. The way the code is designed (from what I see), is we will only begin processing the next file once we the parse method for the current one is finished. If preferred, can attach a run id (a uuid) to the key for the running of a particular thread

2023-03-14 14:57 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .collect(Collectors.groupingBy(item -> Math.abs(item.getHash()[0] % 32)));
Should we check and throw a specific error if the hash isn't present?

2023-03-14 16:37 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerUtilTest.java
> +                .transactionRecord(TransactionRecord.newBuilder().setTransactionHash(ByteString.copyFrom("bytes".getBytes())).build())
Should there be a transaction hash for an invalid transaction like this?

2023-03-14 16:58 UTC, jnels124 commented
The k6 results for post execution are here. I do not have before results because a fresh database was populated and there are no results in Tom's test for transaction hash because it is only turned on in prod. However, the queries for the two are almost identical. The difference being the transaction_hash lookup.

| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|---------|
| transactionsHash | /transactions/{hash} | 500 | 99.80 | 1551.92/s | 1548.82/s | 276.00ms | |
| transactionsId | /transactions/{id} | 500 | 99.99 | 2034.02/s | 2033.82/s | 204.91ms | |

2023-03-14 18:09 UTC, xin-hedera requested changes

2023-03-14 18:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .orElse(0);
this is quite expensive to just find the min and max consensus timestamp and log it, instead can just log the first or the last consensus timestamp in the collection.

2023-03-14 18:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                            .map(shard -> this.processShard(shard).subscribeOn(scheduler))
the transaction management is quiet explicit. have you looked at spring data `TransactionTemplate`? we should be able to do it in `processShard` using:
```java
    var transactionHashes = data.getValue();
    try {
        transactionTemplate.executeWithoutResult(status -> {
            shardPersister.persist(transactionHashes);
        });
        // success log
    } catch (Exception ex) {
        // failure log
    }
```

2023-03-14 19:33 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +                 where table_schema = ''public'' and table_name !~ ''^(?:(?!transaction_hash_sharded_[0-9]{2})).*(flyway|transaction_type|citus_|_\d+).*'' and table_type <> ''VIEW''
they were NOT cleaned before because it matches the .*\d+.* regex. I added the negative lookahead to make sure they were included in the clean while all other tables containing digits were not.

2023-03-14 19:37 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                            .map(shard -> this.processShard(shard).subscribeOn(scheduler))
I did look at creating a transaction template briefly. I use the autoconfigured one in my tests. We can do the same thing there if you prefer. I did it this way to be more explicit about what was happening and it also was more obvious how to synchronize it with the "parent" transaction.

2023-03-14 19:37 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .orElse(0);
guess should have looked to see if the items were sorted already. Will change.

2023-03-14 19:40 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +        } catch (SQLException e) {
will use sneaky throws here ....

2023-03-14 20:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
> +                 where table_schema = ''public'' and table_name !~ ''^(?:(?!transaction_hash_sharded_[0-9]{2})).*(flyway|transaction_type|citus_|_\d+).*'' and table_type <> ''VIEW''
thanks for the clarification!

2023-03-14 20:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .orElse(0);
it can be any one timestamp from the collection, since we know the timestamp range of the transactions in the record file. logging the min and the max timestamp here doesn't really provide much more information

2023-03-14 21:21 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .collect(Collectors.groupingBy(item -> Math.abs(item.getHash()[0] % 32)));
The TransactionHashBatchInserterTest does ensure that items are read from the correct shard

2023-03-15 14:38 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +
done

2023-03-15 14:42 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.78.0__partition_transaction_hash.sql
> +        := concat('transaction_hash_sharded_', to_char(abs(get_byte($1, 0)) % 32, 'fm00'));
fixed

2023-03-15 14:43 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.78.0__partition_transaction_hash.sql
> +    RETURN QUERY EXECUTE 'SELECT consensus_timestamp, payer_account_id from transaction_hash where hash = $1 ' ||
fixed

2023-03-15 14:43 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.78.0__partition_transaction_hash.sql
> +create table if not exists transaction_hash_sharded_00
fixed (for now)

2023-03-15 14:44 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .orElse(0);
Yes of course. Any single timestamp within this collection pinpoints a single record file which of course was the intent of the log. Fixed

2023-03-15 20:30 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +            log.error("Got this exception cuttty", e);
will remove

2023-03-16 15:28 UTC, xin-hedera requested changes

2023-03-16 15:28 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +            expectedTransactionHashes.stream()
nit, can just get transaction hashes from all the shards

2023-03-16 15:28 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/testutils.js
> +  }
can just do `transactionHash[0] % 32` since `Buffer` is a subclass of `Uint8Array`

2023-03-16 18:08 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                });
I used compute to make sure every change to the value happened atomically. I could be mistaken but wouldn't this be unsafe given there is the potential for multiple threads to be writing to that list at the same time?

2023-03-17 04:08 UTC, jnels124 commented on hedera-mirror-rest/__tests__/integration/transactionHashV1Matrix.js
> +    )))
I kind of prefer it this way so each shard table doesn't have to explicitly be listed

2023-03-17 04:10 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration/transactionHashV1Matrix.js
> +    )))
No problem!

2023-03-17 04:16 UTC, jnels124 commented on hedera-mirror-rest/transactions.js
> +
fixed

2023-03-17 04:17 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                });
I had that thought as well but I kept questioning whether different threads modifying different values would still cause visibility issues in the "main" thread when it came time to reading the shards. Going to leave as is just to be safe.

2023-03-17 04:18 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        transactionTemplate.execute(status -> {
done

2023-03-17 04:18 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +                .forEach(shard -> assertThat(getShardTransactionHashes(shard)).containsExactlyInAnyOrderElementsOf(shardMap.get(shard)));
done

2023-03-17 04:18 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        }
done

2023-03-17 04:18 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +    private final Set<TransactionHash> transactionHashes = transactionHash(25);
done

2023-03-17 04:18 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        assertThat(hashBatchInserter.getThreadConnections()).isEmpty();
done

2023-03-17 04:19 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        }
done

2023-03-17 04:20 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +            transactionTemplate.execute(status -> {
done

2023-03-17 04:20 UTC, jnels124 commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionHash.java
> +    public int calculateV1Shard() {
done

2023-03-17 04:20 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigrationTest.java
> +        }
makes sense. done

2023-03-17 04:20 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        for (int i = 0; i < count; i++) {
done

2023-03-17 04:20 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +            expectedTransactionHashes.stream()
done

2023-03-17 04:21 UTC, jnels124 commented on hedera-mirror-rest/__tests__/testutils.js
> +  }
done

2023-03-17 15:21 UTC, xin-hedera requested changes

2023-03-17 20:12 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/TransactionHashTest.java
> +
license header

2023-03-17 20:51 UTC, steven-sheehy requested changes

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
> +SELECT * FROM transaction_hash_old UNION ALL SELECT * FROM transaction_hash_sharded;
Should open a ticket to do an async migration.

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +        var sql = "SELECT * from get_transaction_info_by_hash(?)";
This function was removed.

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
Need to update migration number

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        }
With the parent table this should just work with the repo find all, right? True it won't search from the old table but we shouldn't have that populated in most tests.

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TransactionHashRepositoryTest.java
> +@EnabledIfV2
Is this still needed?

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerUtilTest.java
> +                .transactionRecord(TransactionRecord.newBuilder().setTransactionHash(ByteString.copyFrom("bytes".getBytes())).build())
We should revert as this was a specific empty transaction body scenario we were testing.

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +    private DataSource datasource;
Use final fields with `@RequiredArgsConstructor(onConstructor = @__(@Autowired))`

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        transactions = transactions(10);
These are assigned twice with the first throw away sets. Can just move this up to the declaration and make them final.

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigrationTest.java
> +        }
With parent table can we revert this to just use repository?

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java
> +    @Profile("!v2")
I think you can just put this directly on the TransactionHashBatchInserter instead of inside a configuration class.

2023-03-17 20:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/CompositeBatchPersister.java
> +                                   @Qualifier(TRANSACTION_HASH_BATCH_PERSISTER) Optional<BatchPersister> transactionHashV1BatchPersister) {
If we have to couple to a transaction hash specific bean name we might as well couple directly to the class name and avoid the qualifier.
```suggestion
Optional<TransactionHashBatchInserter> transactionHashV1BatchPersister) {
```

2023-03-17 21:31 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TransactionHashRepositoryTest.java
> +@EnabledIfV2
Yes because the test does a save and transaction_hash is now a view in v1

2023-03-17 21:46 UTC, steven-sheehy requested changes

2023-03-17 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +        TransactionSynchronizationManager.clear();
Is this safe to do even if other threads like `AccountBalanceFileParser`, reconciliation, etc are using a separate `@Transactional`?

2023-03-17 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +        threadConnections.clear();
Shouldn't this be done in a finally instead so it always occurs after instead of next record file?

2023-03-17 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                            .persist(data.getValue());
Preferably we should just have one log entry and one metric for all shards. If that's not possible, we should not have duplicate logs and metrics for both overall and per shard.

2023-03-17 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                                    key -> new BatchInserter(TransactionHash.class,
I would prefer eager inserter initialization in constructor and keep this focused on insert logic. Then we can make the map an immutable, regular map.

2023-03-17 21:46 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .block();
Think you can simplify by combining shardItems and this to use grouped flux.

```suggestion
            // After parser transaction completes, process all transactions for shards
            addTransactionSynchronization(items);

            Flux.fromIterable(items)
                .groupBy(TransactionHash::calculateV1Shard)                
                .subscribeOn(Schedulers.parallel())
                .flatMap(Flux::collectList)
                .doOnNext(this::processShard)
                .subscribeOn(scheduler)
                .block();
```

Or can do collectList inside processShard.

2023-03-17 22:06 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigrationTest.java
> +        }
yes the repository points to the view now

2023-03-17 22:08 UTC, xin-hedera requested changes

2023-03-17 22:08 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  await insertDomainObject('transaction_hash_sharded', Object.keys(transactionHash), transactionHash);
looks like you accidentally removed
```javascript
  transactionHash.hash = valueToBuffer(transactionHash.hash);
```

2023-03-17 22:08 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
> +CREATE TABLE public.transaction_hash_sharded
only because `transaction_hash` is reserved for the view so minimum change is needed in rest api

2023-03-17 22:11 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
> +CREATE TABLE public.transaction_hash_sharded
that is difficult to do because we are trying to avoid migration for the time being. transaction_hash is now a view so we are able to read the old way and new way without updates to the rest api.

2023-03-17 22:12 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +        TransactionSynchronizationManager.clear();
Yes. We are only clearing the thread transaction state for the scheduler thread. this method is only called within .doOnNext which will be the schedulers thread.

2023-03-17 22:21 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +        threadConnections.clear();
We can't clear them at the end because they are still used by the TransactionSynchronization. Ideally, I would have this in a finally of the afterCommit hook. However, doing that makes the code fairly hard to test outside of making sure data is present where it should be. We wouldn't be able to test the failure of connections etc in the integration tests.

2023-03-17 22:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
> +CREATE TABLE public.transaction_hash_sharded
Ok, missed the view was named that.

2023-03-17 22:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +        TransactionSynchronizationManager.clear();
Thanks for clarifying

2023-03-20 12:34 UTC, jnels124 commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  await insertDomainObject('transaction_hash_sharded', Object.keys(transactionHash), transactionHash);
yes I fixed that. Will push with other changes shortly. My apologies. This was pushed too soon.

2023-03-20 15:03 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .block();
Doing it this way doesn't parallelize the work across the scheduler correctly. I did some playing around and I couldn't get a grouped flux to execute how we would want.

2023-03-20 15:05 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                    .block();
We would have to process the grouped flux returned by groupBy by first calling a collect list on each of the fluxes so we can get the items for the shards. I attempted to do this and return a mono from that with subscribing on the scheduler but it doesn't seem to parallelize correctly.

2023-03-20 15:37 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +        transactions = transactions(10);
These functions use the domain builder which will not be created yet if these are moved to class var init.

2023-03-20 16:17 UTC, xin-hedera reviewed
LGTM. will sign off once all open change requests are resolved

2023-03-20 16:33 UTC, jnels124 commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionHash.java
> +        return Math.floorMod(hash[0], 32);
done

2023-03-20 16:38 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
> +SELECT * FROM transaction_hash_old UNION ALL SELECT * FROM transaction_hash_sharded;
done https://github.com/hashgraph/hedera-mirror-node/issues/5625

2023-03-20 16:39 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +        var sql = "SELECT * from get_transaction_info_by_hash(?)";
fixed

2023-03-20 16:39 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.77.1__partition_transaction_hash.sql
done

2023-03-20 17:33 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserter.java
> +                                    key -> new BatchInserter(TransactionHash.class,
done

2023-03-20 17:41 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/TransactionHashBatchInserterTest.java
> +    private DataSource datasource;
done

2023-03-20 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    private final JdbcTemplate jdbcTemplate;
Now unused field and import.

2023-03-20 19:34 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    private final JdbcTemplate jdbcTemplate;
missed the whole diff on this file. Fixed

2023-03-20 19:43 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
> +import java.util.stream.IntStream;
will axe

2023-03-20 20:17 UTC, merged