Optimize list transactions API method …
hashgraph/hedera-mirror-node pull request #5593
Opened 2023-03-16 00:27 UTC by MarcKriguerAtHedera

…by adding additional WHERE clauses.

**Description**:
Optimize the API code for the `/api/v1/transactions` REST call by adding additional `WHERE` clauses for each `JOIN`.

**Related issue(s)**:

Fixes #5429 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-16 19:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
> +        WHERE t.consensus_timestamp >= tr.min and t.consensus_timestamp <= tr.max`;
Done.

2023-03-20 14:43 UTC, xin-hedera requested changes

2023-03-20 21:32 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
> +    }
Done.

2023-03-20 21:34 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
> +    cryptoTransferListCte = cryptoTransferListCte_select + '\n' + cryptoTransferListCte_from_default + '\n'
Did it in the original style (template string, no concatenating the parts together).

New variables (one overall, plus one where clause for each Cte) are all camel case now.

2023-03-21 14:38 UTC, jnels124 submitted a review, later dismissed
LGTM

2023-03-21 15:26 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    from ${additionalFromTable} tlist t
`tlist` is a CTE, thus it's not partitioned, and the query for `tlist` (main table is `transaction`) already has the timestamp range min and max clamping, so adding another timestamp clamping for `select ... from tlist` IMO is redundant and unnecessary. since it's pretty late in the cycle, we can create a follow-up ticket and do the necessary verification and change later.

2023-03-21 15:26 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  let fromTables = `FROM transfer_list t`;
same as `tlist` CTE, `transfer_list` CTE is not partitioned thus shouldn't clamp it again by `[min, max]`

2023-03-21 17:07 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
> +    from ${additionalFromTable} tlist t
OK, I have reverted the changes to the `transfersListCte` computation (removing `transfersListCteWhereClause` in the process).  Leaving the changes in place for `c_list` and `t_list`.

2023-03-21 17:08 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
> +  let fromTables = `FROM transfer_list t`;
Reverted all changes to `getTransactionsOuterQuery` method.

2023-03-21 17:42 UTC, merged