MirrorEvmContractAliases refactor to handle calls to token
hashgraph/hedera-mirror-node pull request #5602
Opened 2023-03-16 15:49 UTC by mustafauzunn

**Description**:

Refactor MirrorEvmContractAliases  to handle calls to token and handle exception

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-03-17 03:07 UTC, steven-sheehy requested changes

2023-03-17 03:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +            final var entityId = new EntityId(entity.getShard(), entity.getRealm(), entity.getNum(), EntityType.TOKEN);
```suggestion
            final var entityId = entity.toEntityId();
```

2023-03-17 03:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +            return Address.wrap(Bytes.wrap(entity.getEvmAddress()));
evm_address can be null. You need the fallback logic that converts entity ID to EVM address if null.

2023-03-17 03:07 UTC, steven-sheehy requested changes

2023-03-17 03:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +    private Mono<GenericErrorResponse> addressValidationError(final InvalidParametersException e) {
test?

2023-03-17 03:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +        if (entity.getType() == EntityType.TOKEN) {
Test coverage?

2023-03-17 12:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +            return Address.wrap(Bytes.wrap(entity.getEvmAddress()));
Maybe in state but not in the database. Especially since it wasn't until a later release that evm address was added to the transaction record.

2023-03-20 15:02 UTC, steven-sheehy approved these changes
LGTM

2023-03-20 15:49 UTC, xin-hedera approved these changes
LGTM

2023-03-20 15:52 UTC, merged