04007 gas calculator
hashgraph/hedera-mirror-node pull request #5668
Opened 2023-03-23 12:28 UTC by stoyan-lime

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-03-23 13:57 UTC, IvanKavaldzhiev reviewed
Great initial efforts! We can enhance the logic with a cache approach for the FeeSchedules/ExchangeRates data.

2023-03-23 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/contracts/gascalculator/GasCalculatorHederaV19.java
> +    private final MirrorNodeEvmProperties dynamicProperties;
We can rename `dynamicProperties` to `mirrorNodeEvmProperties`

2023-03-23 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/contracts/gascalculator/GasCalculatorHederaV22.java
> +            final MirrorNodeEvmProperties dynamicProperties,
We can rename `dynamicProperties` to `mirrorNodeEvmProperties`

2023-03-23 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/MirrorBasicHbarCentExchange.java
> +    MirrorBasicHbarCentExchange(final PricesAndFeesRepository pricesAndFeesRepository) {
Make constructor public

2023-03-23 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/MirrorBasicHbarCentExchange.java
> +        updateExchangeRates(now.getSeconds());
We can think of storing the constructed `ExchangeRateSet` in a field and refresh it at a given interval of time like 2 min. So, instead of fetching the `ExchangeRate` data each time we simulate a transaction, check if the given time limit has passed and only then update the protobuf.

2023-03-23 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/MirrorBasicFcfsUsagePrices.java
> +        byte[] feeScheduleFile = new byte[0];
We can utilize a similar caching approach for `FeeSchedules` as discussed for `ExchangeRates`.

2023-03-24 13:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/MirrorBasicHbarCentExchange.java
> +        final var ratesFile = pricesAndFeesRepository.getExchangeRate(now);
We can move this logic in a class outside of `com.hedera.services` package, since it would be needed in the future and is logic which is not directly copied from `hedera-services`. It might be in a common class that loads exchangeRates and feeSchedules from DB, e.g. `RatesAndFeesLoader`.

2023-03-24 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/MirrorBasicFcfsUsagePrices.java
> +        byte[] feeScheduleFile = new byte[0];
We can move this loading logic out of `com.hedera.services` package.

2023-03-29 09:47 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/contracts/gascalculator/GasCalculatorHederaV19.java
> +    private static long getTinybarsFromTinyCents(final ExchangeRate exchangeRate, final long tinyCentsFee) {
Introduce a `FeeBuilder` version in an appropriate package inside `hedera-mirror-web3`, where you extract these static utility methods. They will be needed in other places like `PrecompilePricingUtils`, which extraction would be part of a separate PR.

2023-04-03 19:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/MirrorBasicHbarCentExchange.java
> +        updateExchangeRates(now.getSeconds());
We should not modify files copied from services as much as possible. You can just use repository with a static string to ensure it doesn't use the default behavior of taking the hash of all method parameters: `@Cacheable(keys = "'some constant'", ...)`.

2023-04-04 09:58 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/services/contracts/gascalculator/GasCalculatorHederaV22Test.java
> +        //        assertEquals(200 * 37, subject.codeDepositGasCost(37));
Probably we can delete?

2023-04-04 10:01 UTC, IvanKavaldzhiev approved these changes
LGTM! 🥳

2023-04-04 14:37 UTC, xin-hedera requested changes

2023-04-04 14:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +                      and ?1 >= l.consensus_timestamp
not sure if the design/requirement is to return exchange rate at any time, if so the query actually returns nothing when `now` is before the latest 112 file create or file update tx consensus timestamp. same issue in `getFeeSchedule` query

also the cache here doesn't provide much value because `now` is different across calls.

2023-04-04 14:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        final var ratesFile = pricesAndFeesRepository.getExchangeRate(now);
`now` is epoch seconds, however the repository method expect timestamp in nanosecond

2023-04-04 14:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +                      order by consensus_timestamp desc
```suggestion
```

2023-04-04 14:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +                      order by consensus_timestamp desc
```suggestion
```

2023-04-04 14:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/BasicHbarCentExchange.java
> +        exchangeRates = ratesAndFeesLoader.loadExchangeRates(now.getSeconds());
not multi-thread safe because `exchangeRates` can be read/write by multiple threads at the same time

2023-04-05 14:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/BasicHbarCentExchange.java
> +        exchangeRates = ratesAndFeesLoader.loadExchangeRates(now.getSeconds());
@xin-hedera , can you elaborate more on how we can write to exchangeRates/feeSchedule files at the same time? Do you mean the manual update of Files 111 & 112? If so, how this would impact estimateGas workflow? Currently we're interested in only reading the most recent data from these files.

2023-04-05 14:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/BasicHbarCentExchange.java
> +        exchangeRates = ratesAndFeesLoader.loadExchangeRates(now.getSeconds());
You probably mean the case where `threadA` reads a newly updated File for `exchangeRates` for example, a `threadB` reads a stale data just before the update, but `threadB` updates `exchangeRates` field after threadA and thus masks the new updated values from DB?

2023-04-06 07:58 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/BasicHbarCentExchange.java
> +        exchangeRates = ratesAndFeesLoader.loadExchangeRates(now.getSeconds());
I believe we can just delete the `exchangeRates` field as singleton Spring Beans shouldn't keep state in a field. Every time we need `exchangeRates` we can call `loadExchangeRates`

2023-04-07 03:42 UTC, steven-sheehy requested changes
This is marked as fixing #4007, but #4007 is a sub-epic with 4 individual tasks. Does this also fix the sub-tasks? If so, please mark as fixing all 5 tickets. If not, please remove this as fixing #4007 and mark it as fixing the appropriate ticket(s).

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        final CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
Instead of a hardcoded 1 hr, we have been using a string cache specification for the ones above. We should stick with that here so we can adjust all aspects of the cache via a property. Please also update docs/configuration.md.
```suggestion
    @Bean(CACHE_MANAGER_FEE)
    CacheManager cacheManagerFee() {
        final CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
        caffeineCacheManager.setCacheSpecification(cacheProperties.getFees());
```

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +    private static final Logger log = LogManager.getLogger(RatesAndFeesLoader.class);
Remove log definition in favor of `@CustomLog`.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            throw new IllegalStateException(String.format("Rates %s are corrupt!", EXCHANGE_RATE_ENTITY_ID));
We should have a test case for partial or invalid exchangerate and fee schedule proto bytes.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        byte[] feeScheduleFile = new byte[0];
Use a static final to avoid unnecessary allocation or `ArrayUtils.EMPTY_BYTE_ARRAY`.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return 180;
This doesn't need to be customized via a property?

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +    private final GasCalculatorHederaV22 gasCalculator;
How is this been being created if the class does not have `@Named` or `@Component` on it and I don't see the bean manually created anywhere outside of tests?

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/IntegrationTestConfiguration.java
> +    }
Have you ran `./gradlew :web3:bootRun` and done any manual testing? I don't think these beans exist at runtime. You should probably move the above code to `EvmConfiguration`. That's probably why the chart workflow fails.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +            unless = "#result == null")
I think parsing large proto bytes could also be slow so we should probably move this `@Cacheable` to `RateAndFeesLoader`.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +    byte[] getExchangeRate(final long now);
This is strange because we cache for one hour to a static key, but the query uses the `now` parameter. So if the first user of the API requests an exchange rate for 2019, the next user that requests the latest timestamp will have a wildly inaccurate exchange rate from the past.

Instead, we should smooth out the now values to round them to the nearest hour and then use the hourly `now` as the cache key.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +                    group by file_data.entity_id""",
This is the same query as `getExchangeRate` except for the file ID. So we should consolidate to a single `byte[] getFileAtTimestamp(long fileId, long timestamp)`.

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +public interface PricesAndFeesRepository extends CrudRepository<Entity, Long> {
There is no such PricesAndFees table
```suggestion
public interface FileDataRepository extends CrudRepository<FileData, Long> {
```

2023-04-07 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +        final var processor = new MirrorEvmTxProcessor(
Please address the sonar code smells. You can suppress the constructor complexity warning, if you like.

2023-04-07 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +            cacheManager = CACHE_MANAGER_1H,
While it's true that exchange rate updates every hour, if we cache the old exchange rate 1s before it's updated that means it will be inaccurate for users for a whole hour. So we should probably consider reducing this to say 10 minutes to provide more accurate values.

2023-04-12 04:05 UTC, steven-sheehy requested changes
There are still unaddressed review items from mine and Xin's previous round of feedback. It's the mirror node's process to add a comment to any unresolved discussion items noting that they are done or why they cannot be.

2023-04-12 04:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderTest.java
> +    void loadFeeSchedules() {
Need tests for both fee schedules and exchange rates when:
* nanoSeconds=0
* no data returned from repo
* Unable to parse data from repo

2023-04-12 14:34 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        final var ratesFile = pricesAndFeesRepository.getExchangeRate(now);
Done!

2023-04-12 14:39 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +                fileDataRepository.getFileAtTimestamp(EXCHANGE_RATE_ENTITY_ID.getEntityNum(), nanoSeconds);
Done!

2023-04-12 14:39 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            feeScheduleFile = fileDataRepository.getFileAtTimestamp(FEE_SCHEDULE_ENTITY_ID.getEntityNum(), nanoSeconds);
Done!

2023-04-12 14:41 UTC, stoyan-lime commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderTest.java
> +    }
Done!

2023-04-12 14:41 UTC, stoyan-lime commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderTest.java
> +        assertEquals(exchangeRates, actual);
Done!

2023-04-12 15:10 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +                      and ?1 >= l.consensus_timestamp
We decided to implement the functionality only for the latest/current rates, so we can use it for estimate gas. It will be improved to work with any timestamp in a future PR. I will document this in this PR.

2023-04-12 15:10 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/PricesAndFeesRepository.java
> +    byte[] getExchangeRate(final long now);
We decided to implement the functionality only for the latest/current rates, so we can use it for estimate gas. It will be improved to work with any timestamp in a future PR. I will document this in this PR.

2023-04-12 15:42 UTC, stoyan-lime commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderTest.java
> +    void loadFeeSchedules() {
What should the test for nanoSeconds=0 assert?
Added the other 2 tests.

2023-04-12 15:42 UTC, xin-hedera requested changes

2023-04-12 15:42 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            key = "'now'",
there's no argument named `now`

per Steven's suggestion, the cache key should be round up to the next hour, otherwise, any different `nanoSecond` would cause the method to get the file data from `fileDataRepository`

2023-04-12 15:42 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        if (nanoSeconds > 0) {
q: why do we need to check `nanoSeconds > 0`?

2023-04-12 15:42 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +                      order by consensus_timestamp desc
these are unnecessary, since the where clause restricts it to a specific file entity id and we do `max` aggregation in select
```suggestion
```

2023-04-12 15:42 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +                    group by file_data.entity_id""",
similarly, unnecessary group since the where clause restricts it to a specific file entity id
```suggestion
                      and ?2 >= l.consensus_timestamp""",
```

2023-04-12 15:42 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/FileDataRepositoryTest.java
> +    private FileDataRepository fileDataRepository;
nit
```suggestion
    private final FileDataRepository fileDataRepository;
```

2023-04-12 15:44 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            throw new IllegalStateException(String.format("Rates %s are corrupt!", EXCHANGE_RATE_ENTITY_ID));
Done!

2023-04-12 15:49 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            key = "'now'",
"'now'" is used as a static key, so we can have only 1 cached value as we only work with the current timestamp. This will be changed in future PR, which will add functionality for different timestamps.

2023-04-12 15:53 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +                    group by file_data.entity_id""",
Removed!

2023-04-12 15:53 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +                      order by consensus_timestamp desc
Removed!

2023-04-12 15:53 UTC, stoyan-lime commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/FileDataRepositoryTest.java
> +    private FileDataRepository fileDataRepository;
Done!

2023-04-12 15:59 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        if (nanoSeconds > 0) {
This was copied from an old implementation of another colleague, but does seem to be unnecessary.
I have removed it, but will ask my colleagues for clarification.

2023-04-13 01:07 UTC, steven-sheehy approved these changes
LGTM

2023-04-13 01:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderTest.java
> +    void loadFeeSchedules() {
Well, you removed the `if (nanoSeconds > 0)` statement in your last commit, so that test case is no longer applicable.

2023-04-13 01:20 UTC, xin-hedera approved these changes
LGTM

2023-04-13 02:57 UTC, merged