Add /api/v1/contracts/call to open API spec
hashgraph/hedera-mirror-node pull request #5670
Opened 2023-03-23 15:08 UTC by mustafauzunn

**Description**:

Add /api/v1/contracts/call to open API spec

**Related issue(s)**:

Fixes #5584 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-03-23 15:28 UTC, steven-sheehy requested changes

2023-03-23 15:28 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        description: Returns a result from execution of eth_call and eth_estimateGas. If `estimate` field set to true eth_estimateGas is executed
Let's not use eth_call or eth_estimateGas terminology. This is not a JSON-RPC API, it is a REST API that calls a contract. So just generic Hedera terms focused on contract calls or EVM execution.

2023-03-23 15:28 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  data:
nit: sort

2023-03-23 15:28 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                    type: string
Missing description for all request and response fields.

2023-03-23 15:28 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                properties:
Missing many fields

2023-03-23 15:28 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          200:
Add error response codes and format. need to add detail and data to generic error response structure.

2023-03-27 13:21 UTC, IvanKavaldzhiev commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  $ref: '#/components/schemas/Web3Error'
We have also `501 Not Implemented` exception. We can also sort the http errors in ascending order.

2023-03-27 15:09 UTC, xin-hedera requested changes

2023-03-27 15:09 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  - to
is `to` the only required property?

2023-03-27 15:54 UTC, steven-sheehy requested changes

2023-03-27 15:54 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                    maxLength: 6144 * 2
No, the code has 6144x2.

2023-03-27 15:54 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  from:
Add nullable: true

2023-03-27 15:54 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  gas:
Add nullable: true. Add default of 120000000 to description.

2023-03-27 15:54 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                  $ref: '#/components/schemas/Web3Error'
Yes, put all current response codes and adjust them later.

2023-03-27 15:54 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +                    type: string
These are missing description, example, pattern, nullable: false, format. Also should sort.

2023-03-28 16:35 UTC, steven-sheehy submitted a review, later dismissed

2023-03-28 19:22 UTC, xin-hedera approved these changes
LGTM

2023-03-28 19:22 UTC, steven-sheehy approved these changes

2023-03-28 19:47 UTC, merged