Citus optimize list schedules query
hashgraph/hedera-mirror-node pull request #5673
Opened 2023-03-23 21:36 UTC by xin-hedera

**Description**:

This PR optimizes the list schedules REST API for citus

**Related issue(s)**:

Fixes #5235 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-24 14:34 UTC, xin-hedera commented on hedera-mirror-rest/schedules.js
> +    logger.trace(`getSchedules query: ${schedulesQuery}, params: ${params}`);
we should move such logs into `pool.queryQuietly` then won't be bothered by low code coverage warnings

2023-03-24 17:49 UTC, mgoelswirlds approved these changes

2023-03-27 18:21 UTC, steven-sheehy requested changes

2023-03-27 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/schedules.js
> +    order by entity_id ${order}`;
There's a risk the sort order for signatures within an entity is non-deterministic. We should add a sort on consensus_timestamp asc

2023-03-27 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/schedules.js
> +    s.consensus_timestamp,
I think we should just add the table prefix to `scheduleFields` and `entityFields` and join the two here so we don't repeat the fields for list and by ID.

2023-03-27 18:27 UTC, xin-hedera commented on hedera-mirror-rest/schedules.js
> +    order by entity_id ${order}`;
the order is done in `transactionSignatureJsonAgg`

2023-03-27 19:26 UTC, steven-sheehy approved these changes

2023-03-27 22:45 UTC, merged