5423 acceptance hollow account to contract
hashgraph/hedera-mirror-node pull request #5688
Opened 2023-03-24 22:10 UTC by jascks

**Description**:
Enhance contract acceptance test with the finalizing hollow account to contract scenario as mentioned in [HIP-583](https://github.com/hashgraph/hedera-improvement-proposal/pull/673).

Please refer to `contract.feature` as its description and the defined steps are pretty explicit on what it took to incorporate the ask of #5423 with the existing contract acceptance test scenario.

This PR modifies several files within `hedera-mirror-test/src/test` only. Okay and also `.gitignore`. There are no changes to any other parts of Mirror Node itself.

**Related issue(s)**:

Fixes #5423 

**Notes for reviewer**:

**NOTE:** I am on PTO from March 27 - April 7, 2023. However, I will still be around home on both March 27 and 28 and I may be able to address any review comments and perhaps even get this merged into `main` before I depart.

The parent contract, `Parent.sol`, was enhanced with elements from `hedera-services` `Create2Factory.sol`, namely functions around returning child contract bytecode, computing the EVM address given bytecode and salt, as well as deploying the contract using the same bytecode and salt via the EVM CREATE2 opcode.

I added `getContractInfoWithNotFound()` to `MirrorNodeClient.java` so that 404 `NOT_FOUND` could be properly detected rather than just fail after 20 retries. This was required to determine that the newly created hollow account is not recognized as a contract via its EVM address.

`MirrorAccountResponse.java` was updated so that I could tell whether or not an account has a public key. This is important for determining hollow-ness.

Yes, there is one giant 28 step scenario defined in `contract.feature`. I originally had three separate interdependent scenarios and they always ran top to bottom in IDEA, but not with gradle on the command line. Thus, at the last minute, I combined all the steps together in order to ensure order.

`ContractFeature.java` is where all of those gherkin steps are implemented and there is a lot of code changed there.

You might find the blog [The CREATE2 Opcode on Hedera: An Introduction](https://hedera.com/blog/the-create2-opcode-on-hedera-an-introduction) is also helpful.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (ran against integration and testnet)

2023-03-29 16:27 UTC, jnels124 requested changes

2023-03-29 16:27 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        create2ChildContractAccountId = AccountId.fromString(String.format("0.0.%s", create2ChildContractEvmAddress));
Can we not use `AccountId.fromEvmAddress(create2ChildContractEvmAddress)` and `ContractId.fromEvmAddress(create2ChildContractEvmAddress)`?

2023-03-29 16:27 UTC, jnels124 commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the account transaction
You can delete this line. The following line does a better verification of the correct transactions

2023-03-29 16:27 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        var transactions = mirrorClient.getTransactions(networkTransactionResponse.getTransactionIdStringNoCheckSum()).getTransactions();
this is unused

2023-04-04 16:13 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Retrieve contract '{}' is from Mirror Node, may not be found", contractId);
Looking through it, it seems that this is the intent is for the contract not to be found, so I have changed this log message to `Verify contract is not found` and I have changed the retry spec to log.debug instead of log.error upon the not found. This results in output similar to this when the acceptance test is ran: 

```
    And the mirror node REST API should verify the account receiving 1000 is hollow                         # com.hedera.mirror.test.e2e.acceptance.steps.ContractFeature.verifyMirrorAPIHollowAccountResponse(int)
    2023-04-04T09:59:15.893-0600 INFO ForkJoinPool-3-worker-4 c.h.m.t.e.a.s.ContractFeature Verify contract at the hollow account evm address does not exist
    2023-04-04T09:59:15.893-0600 DEBUG ForkJoinPool-3-worker-4 c.h.m.t.e.a.c.MirrorNodeClient Verify contract '927839ee97e4dad6cb894c83368b16f8ae996657' is not found
    2023-04-04T09:59:15.944-0600 INFO reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient GET api/v1/contracts/927839ee97e4dad6cb894c83368b16f8ae996657: 404 NOT_FOUND

2023-04-04 16:14 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        create2ChildContractAccountId = AccountId.fromString(String.format("0.0.%s", create2ChildContractEvmAddress));
Got it, it now uses those methods.

2023-04-04 16:14 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
> +        var transactions = mirrorClient.getTransactions(networkTransactionResponse.getTransactionIdStringNoCheckSum()).getTransactions();
Got it, I have removed it.

2023-04-04 16:16 UTC, edwin-greene commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +        Then the mirror node REST API should return status <httpStatusCode> for the account transaction
It looks like the call to `verifyMirrorTransactionsResponse` is verifying some specifics not related to hollow account, such as non-null timestamps/names/results. It does check that the transactions are not null, but otherwise it doesn't assert anything about the transactions themselves. 

Then the specific hollow account verifications occur in `verifyMirrorAPIHollowAccountResponse`. In that method there was a duplicate assert from `verifyMirrorTransactionsResponse` where it verified not null a second time on line 259. So I have removed the duplicate assertion.

2023-04-04 16:17 UTC, edwin-greene commented on hedera-mirror-test/src/test/resources/features/contract/contract.feature
> +        verify proper operation. Use that same parent contract to create a second child contract using
I've left it so far, the additional documentation looked ok to me.

2023-04-05 16:45 UTC, jnels124 approved these changes

2023-04-06 18:45 UTC, xin-hedera approved these changes
LGTM. just some nits

2023-04-06 20:39 UTC, steven-sheehy approved these changes
LGTM

2023-04-06 20:39 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ContractClient.java
> +    }
I think a more generic `class NetworkTransactionRecordResponse extends NetworkTransactionResponse` that just adds the `TransactionRecord` would be more reusable here.

2023-04-06 20:40 UTC, merged