Add 3 "consensus modes" to AddressBookServiceImpl::getNodes
hashgraph/hedera-mirror-node pull request #5689
Opened 2023-03-24 23:48 UTC by MarcKriguerAtHedera

Fix issue 5604 by adding three consensus modes

**Description**:
This PR adds a new property, `consensusMode`, to MirrorProperty.  This enum has 3 values:
- EQUAL: add nodes equally weighted (1 for each node)
- STAKE : current behavior : all nodes specify their node stake
- STAKE_IN_ADDRESS_BOOK: new default : only nodes in the address book count their node stake.
* modify AddressBookServiceImpl::getNodes() to take into account the consensus mode,
* modify tests in AddressBookServiceImplTest to test all 3 consensus modes,

One or two line summary of what this PR does and why it is needed, followed by a list
of changes in imperative, present tense for use in the commit message or changelog. Example:

**Related issue(s)**:

Fixes #5604 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-28 02:41 UTC, steven-sheehy requested changes

2023-03-28 02:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                addressBook.getNodeCount(), nodeStakes.size(), newTotalStake, oldTotalStake);
I think it would be better and simpler to just warn if the size differs. Also, would be better for researching to print the timestamps of each. Just pick one timestamp from nodestakes.

```suggestion
          if (addressBook.getNodeCount() != nodeStakes.size()) {
            log.warn("Using address book {} with {} nodes and node stake {} with {} nodes",
                addressBook.getConsensusTimestamp(), addressBook.getNodeCount(), nodeStakeTimestamp, nodeStakes.size());
```

2023-03-28 02:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +                fileDataRepository, otherMirrorProperties, nodeStakeRepository, transactionTemplate);
We should not be recreating the class under test. Especially since it's a Spring bean and we're creating it manually. To test different consensusModes, simply set that mode on the already injected `mirrorProperties`.

2023-03-28 02:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +                .containsExactly(0L, 1L, 2L, 3L);
Revert changes to existing tests. It makes it hard to verify no regression and we should have different test for different consensus modes.

2023-03-28 02:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +        // consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK (the default)
Remove this comment and explicitly set it so it's self documenting and protects against changes to default properties in any config.

2023-03-28 02:41 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodesNotInAddressBook() {
We should be able to consolidate the logic to one parameterized test.
```suggestion
    @CsvSource(textBlock = """
    EQUAL, 6, 6
    ...
    """)
    @ParameterizedTest
    void getNodes(ConsensusMode mode, long stake, int nodeCount) {
```

2023-03-28 02:41 UTC, steven-sheehy commented
Should also have on test in `AbstractDownloaderTest` that verifies stuck scenario in ticket.

2023-03-29 09:00 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +    private ConsensusMode consensusMode = ConsensusMode.STAKE_IN_ADDRESS_BOOK; // see options at bottom of file
Done.

2023-03-29 09:01 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
>              totalStake.addAndGet(nodeStake.getStake());
Done.

2023-03-29 09:01 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +                addressBook.getNodeCount(), nodeStakes.size(), newTotalStake, oldTotalStake);
Done.

2023-03-29 09:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +                .containsExactly(0L, 1L, 2L, 3L);
Done.

2023-03-29 09:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +        // consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK (the default)
Done.

2023-03-29 09:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodesNotInAddressBook() {
Done.

2023-03-29 09:06 UTC, MarcKriguerAtHedera commented
I couldn't access the address book from `AbstractDownloaderTest` (to create a parameterized test with different ConsensusModes, and have it be successful only from STAKE_IN_ADDRESS_BOOK), so instead I added a test to that suite that simply has stakes at 1/4 the total and fails to validate.  Let me know if you had something else in mind for `AbstractDownloaderTest.`

2023-03-29 20:56 UTC, xin-hedera requested changes

2023-03-29 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        if (consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK && addressBook.getNodeCount() != nodeStakes.size()) {
don't warn when node stake is empty

```suggestion
        if (consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK && addressBook.getNodeCount() != nodeStakes.size() && !nodeStakes.isEmpty()) {
```

2023-03-29 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            nodeStakeMaxTimestamp.getAndAccumulate(nodeStake.getConsensusTimestamp(), Math::max);
node stakes from `findLatest` all have the same consensus timestamp

2023-03-29 20:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    STAKE_IN_ADDRESS_BOOK, 0, 5, 4
why the stake is set to 0?

should hard code it to 2 without parameterize it, then the expected total stake should be 10 and 8

2023-03-29 23:23 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        // if only including address book nodes in stake count, reset and readd only address book nodes' stakes.
The original code (that this comment went along with) set totalStake back to 0, and looped over the address book's entries, re-adding the value back to totalStaek.  Steven had me change the code to only loop/add once, but this comment (now updated) was stale.  And "re-add" or "readd" was (originally) accurate, but now it's moot.

2023-03-29 23:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            nodeStakeMaxTimestamp.getAndAccumulate(nodeStake.getConsensusTimestamp(), Math::max);
ok, got rid of the `getAndAccumulate` and `Math::max` -- now it only sets `nodeStakeTimestamp` once.  (Since all the timestamps are the same, I dropped the "Max" from the variable name.)

2023-03-29 23:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    """)
Done.

2023-03-29 23:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    EQUAL, 10000, 6, 6, 1
Done.

2023-03-30 15:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            // rather than calling getAndUpdate with Math.max, this just sets the variable a single time.
it's better to just say, all the node stake rows have the consensus timestamp, in case a comment is really needed

2023-03-30 15:13 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-03-30 15:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            } else if (consensusMode != ConsensusMode.STAKE_IN_ADDRESS_BOOK ||
Looks like this should be a separate if so it runs for all consensus modes, including EQUAL. Right now, totalStake is not being accumulated for EQUAL. I think it happens to work because of the `totalStake > 0 ? totalStake : nodeCount` logic in `ConsensusNodeWrapper`, but that's brittle to rely on that.
```suggestion
            }

            if (consensusMode != ConsensusMode.STAKE_IN_ADDRESS_BOOK ||
```

2023-03-30 15:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +                .nodeId(nodeId.getAndIncrement()).stake(expectedNodeStake)).persist();
We should hardcode this to 10000 and not pass the expectedNodeStake otherwise we're not testing the new logic.

2023-03-30 15:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodeStateCountMoreThanAddressBook(ConsensusMode mode, int nodeCount, long expectedTotalStake) {
This test seems to duplicate what `getNodesWithNodesNotInAddressBook` but without as much coverage. And strange that it has a nodeCount parameter that doesn't vary. Recommend it be removed.

2023-03-30 15:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodesNotInAddressBook(ConsensusMode mode, long expectedTotalStake, long expectedNodeStake) {
Swap the order of the params to be consistent with the order from the other tests. Also can revert to the previous method name for clarity.
```suggestion
    void getNodesWithNodeStakeCountMoreThanAddressBook(ConsensusMode mode, long expectedNodeStake, long expectedTotalStake) {
```

2023-03-30 15:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    STAKE_IN_ADDRESS_BOOK, 10000, 40000
Should add a STAKE test

2023-03-30 17:05 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    @ParameterizedTest
Might be good to have tests with 0 for the staked value for `STAKE` and `STAKE_IN_ADDRESS_BOOK`.

2023-03-30 18:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +            // rather than calling getAndUpdate with Math.max, this just sets the variable a single time.
Done.

2023-03-30 18:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +                .nodeId(nodeId.getAndIncrement()).stake(expectedNodeStake)).persist();
Done.

2023-03-30 18:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodeStateCountMoreThanAddressBook(ConsensusMode mode, int nodeCount, long expectedTotalStake) {
Done (and then renamed the latter to this name, as the later comment suggested).

2023-03-30 18:55 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodesNotInAddressBook(ConsensusMode mode, long expectedTotalStake, long expectedNodeStake) {
Done/

2023-03-30 18:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    STAKE_IN_ADDRESS_BOOK, 10000, 40000
Done.  (Per Edwin's later comment, ended up adding two).

2023-03-30 18:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
> +        ConsensusMode consensusMode = mirrorProperties.getConsensusMode();
Done.

2023-03-30 18:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    @ParameterizedTest
Done.  Also added one for EQUAL (to make sure when specifying the stake as 0, that it (also) comes back as 1)

2023-03-30 20:02 UTC, steven-sheehy requested changes

2023-03-31 05:37 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    void getNodesWithNodeStateCountMoreThanAddressBook(ConsensusMode mode, long expectedNodeStake, long expectedTotalStake) {
Done.  (Thanks for catching that typo.)

2023-03-31 05:37 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
> +    EQUAL, 1, 1, 4
Done.

2023-03-31 15:42 UTC, xin-hedera approved these changes
LGTM

2023-03-31 16:38 UTC, merged