Move all transaction specific logic to transaction handlers
hashgraph/hedera-mirror-node pull request #5734
Opened 2023-03-30 18:20 UTC by steven-sheehy

**Description**:

* Add missing `FreezeTransactionHandler`
* Add missing `TokenPauseTransactionHandler`
* Add missing `TokenUnpauseTransactionHandler`
* Add missing `UncheckedSubmitTransactionHandler`
* Add missing transaction types to `RecordItemBuilder`
* Add missing test coverage for transaction handlers
* Change `AddressBookService` to persist the `FileData` internally
* Fix NPE on bad entity ID due to re-parsing the main entity outside `TransactionHandler.getEntity()`
* Gracefully handle token mint metadata and serial number mismatch
* Refactor `EntityRecordItemListener` to move transaction specific processing to the appropriate `TransactionHandler`

**Related issue(s)**:

Fixes #1374

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-03-30 20:28 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .transactionBody(b -> b.clearMetadata().setToken(protoTokenId).clearMetadata()
Does it need `clearMetadata()` twice? It looks like the test still passes with the second one removed.

2023-03-30 20:42 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileCreateTransactionHandlerTest.java
> +import static org.mockito.Mockito.*;
Nit, can optimize imports.

2023-03-30 20:43 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileUpdateTransactionHandlerTest.java
> +import static org.mockito.Mockito.*;
Nit, can optimize imports.

2023-03-30 20:48 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFreezeTransactionHandlerTest.java
> +import static org.mockito.Mockito.verifyNoInteractions;
Nit, can optimize imports

2023-03-30 20:51 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRevokeKycTransactionHandlerTest.java
> +import static org.mockito.Mockito.verifyNoInteractions;
Nit, can optimize imports.

2023-03-30 20:51 UTC, MarcKriguerAtHedera approved these changes
Looks good!

2023-03-30 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRevokeKycTransactionHandlerTest.java
> +import static org.mockito.Mockito.verifyNoInteractions;
Done

2023-03-30 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFreezeTransactionHandlerTest.java
> +import static org.mockito.Mockito.verifyNoInteractions;
Done

2023-03-30 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileUpdateTransactionHandlerTest.java
> +import static org.mockito.Mockito.*;
Done

2023-03-30 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                .transactionBody(b -> b.clearMetadata().setToken(protoTokenId).clearMetadata()
Removed

2023-03-31 14:00 UTC, edwin-greene submitted a review, later dismissed
Looks good!

2023-04-03 17:18 UTC, xin-hedera requested changes

2023-04-03 17:18 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileAppendTransactionHandlerTest.java
> +    @Test
also test when persist.files or persist.systemFiles is false

2023-04-03 19:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileAppendTransactionHandlerTest.java
> +    @Test
I have tests for when they are both false and when only one of them are false.

2023-04-03 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/FileAppendTransactionHandlerTest.java
> +    @Test
Set these to false for address book update.

2023-04-03 19:18 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenMintTransactionHandler.java
> +                continue;
Thanks, I changed it to a break statement.

Yes, I meant to explicitly log the serial numbers. This is a scenario that should never occur so it would be helpful to have the handful of actual serial numbers in the log.

2023-04-03 19:36 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-04-03 19:50 UTC, xin-hedera approved these changes

2023-04-03 20:11 UTC, merged