Refactor custom fee for contract call
hashgraph/hedera-mirror-node pull request #5762
Opened 2023-04-05 10:02 UTC by mustafauzunn

**Description**:

Refactor custom fee for contract call

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-05 14:15 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM!

2023-04-05 14:56 UTC, steven-sheehy requested changes

2023-04-05 14:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    public static final String SELECT_QUERY ="select * from custom_fee  where token_id = :tokenId and created_timestamp = (select created_timestamp from custom_fee  where token_id = :tokenId order by
Where is the test that verifies that duplicate custom fees by it's JPA ID are returned?

2023-04-06 15:29 UTC, steven-sheehy requested changes

2023-04-06 15:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    private final CustomFeeRepositoryImpl customFeeRepositoryimpl;
Revert
```suggestion
    private final CustomFeeRepository customFeeRepository;
```

2023-04-07 15:21 UTC, steven-sheehy approved these changes
LGTM

2023-04-07 15:22 UTC, merged