Initial design doc for graphql contract log subscriptions
hashgraph/hedera-mirror-node pull request #5764
Opened 2023-04-05 14:59 UTC by jnels124

**Description**:
Add design doc for contract log subscriptions

**Related issue(s)**:

Fixes #5411 

**Notes for reviewer**:

**Checklist**

- [x ] Documented (Code comments, README, etc.)
- [x ] Tested (unit, integration, etc.)

2023-04-05 15:02 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +          maxActiveSubscriptions: 1000
Do we also want to configure a ttl on subscriptions?

2023-04-05 15:36 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +          maxActiveSubscriptions: 1000
An additional by ip limit?

2023-04-05 22:26 UTC, steven-sheehy requested changes

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +1. Update RedisEntityListener to send contract logs to contract_logs.{CONTRACT_ID} topic
We need to document the payload structure between importer and graphql modules. We use msgpack for topic messages and might consider using the same here. Or if we think we can directly generate the JSON in the importer that we can send on to clients without modification via GraphQL can use JSON instead of msgpack.

Also, note that it will be a batch send to redis on record file boundary or max transactions limit.

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +4. Create a Redis Subscriber to listen for contract_logs.{CONTRACT_ID}
Why would contract ID be in the redis topic name since it's not an input to the API?

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +public class ContractLogController {
Think it should just go in the general contract controller since it's the higher level grouping.
```suggestion
public class ContractController {
```

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  public Publisher<ContractLogEvent> subscribe(@Argument @Valid ContractLogFilter filter);
The input doesn't match the schema. Same problem elsewhere.
```suggestion
  public Publisher<ContractLogEvent> subscribe(@Argument @Valid ContractLogSubscription subscription);
```

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  public Publisher<ContractLogEvent> subscribe(@Argument @Valid ContractLogFilter filter);
```suggestion
  @SubscriptionMapping
  public Publisher<ContractLogEvent> contractLogs(@Argument @Valid ContractLogFilter filter);
```

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  contractLog(input: ContractLogSubscriptionInput): ContractLogEvent
```suggestion
  contractLogs(subscription: ContractLogSubscription!): ContractLogEvent
```

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +}
GraphQL request is usually nested in some wrapper JSON that indicates the subscription type.

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +Address is required and topics is an optional filter
Addresses are also optional

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +{
GraphQL responses are wrapped in a `"data": {...}`.

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  address: String @Pattern(regexp: "^(0x)?[a-fA-F0-9]{40}$")
On the importer, we will only have the `account-num alias` form for the addresses when we push to Redis. On subscription, we should mention that we detect if this address input is `account-num alias` or `evm address alias` and query the entity table for the latter to map it to its `account-num alias`.

See https://github.com/hashgraph/hedera-improvement-proposal/pull/673/files for a description of the different address and alias formats.

2023-04-05 22:26 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  Map<String, Flux<ContractLogEvent>> subscribedTopics;
I'm not sure if we can pick a proper Redis channel name that can be used for both topics or address or both. I don't think we want to send data duplicately to an address based channel and a topic based channel. We might have to just listen for all logs via a shared, lazy subscription and filter locally. Please give this some thought.

2023-04-05 22:29 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +          maxActiveSubscriptions: 1000
Not sure we can currently get the real client IP. If you don't, then you risk throttling the Kubernetes node IP.

2023-04-06 00:36 UTC, steven-sheehy requested changes

2023-04-06 00:36 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +- Use Bucket4J for rate limiting
Rate limiting what? Requests or responses? I don't think we want to throttle responses since it's what the network can handle so we should be able to handle. Requests should be throttle but we should probably do this at the load balancer level and not use bucket4j.

2023-04-06 00:36 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +          maxActiveSubscriptions: 1000
We should definitely have at minimum a keepalive.

2023-04-06 12:28 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  address: String @Pattern(regexp: "^(0x)?[a-fA-F0-9]{40}$")
For the log event, it appears it only supports address and not addresses. I was questioning whether that was an error in the document though.

2023-04-06 12:32 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +Address is required and topics is an optional filter
for the log event, it seems only address is supported. That may have been an error in the hip though

2023-04-06 12:39 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  for reactive applications)
We can use websockets. RSocket provides on wire backpressure, heart beats, ability to pause/resume, and a few other things but we can implement without.

2023-04-06 15:04 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  address: String @Pattern(regexp: "^(0x)?[a-fA-F0-9]{40}$")
You mean in the HIP or in the ethereum spec? It doesn't matter what the HIP states, we should follow the ethereum spec and support an array. We should bring up the HIP problem with Nana and team.

2023-04-06 15:11 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  for reactive applications)
But Redis and the importer don't support most of those things and we're not implementing any querying or large buffering on the graphql side to take advantage of some of those.

2023-04-06 16:42 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +4. Create a Redis Subscriber to listen for contract_logs.{CONTRACT_ID}
I believe all ContractLogEvent fields should be available in memory on the importer.

2023-04-06 17:36 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  Map<String, Flux<ContractLogEvent>> subscribedTopics;
What you described is the plan. There will be a channel for each contract and each subscription will filter for relevant topics.

2023-04-06 17:37 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +- Use Bucket4J for rate limiting
This is to rate limit active subscriptions at a global level. So each time someone subscribes, we take a token. Unsubscribe, we supply a token.

2023-04-06 17:44 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  Map<String, Flux<ContractLogEvent>> subscribedTopics;
Don't think that's possible. Addresses are not required so they can just search for topics by itself. And vice versa.

2023-04-10 16:07 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  Map<String, Flux<ContractLogEvent>> subscribedTopics;
You are right. I misread and was thinking at least one address was required

2023-04-10 17:36 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  data: String
done

2023-04-10 17:36 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  blockNumber: String
done

2023-04-13 03:47 UTC, steven-sheehy requested changes

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  "The addresses we want to stream logs for (Pattern may not work this way)"
I tested the pattern and it seems to work this way. Also, it seems GraphQL supports a non-list string as input even when modeled as an array, which is pretty cool.

```suggestion
  "Only logs created from one of these EVM addresses will be emitted."
```

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  topics: [[String]] @Pattern(regexp: "^(0x)?[a-fA-F0-9]{64}$")
It doesn't seem like the pattern works with this double list and in fact will make it fail. You're welcome to double check via a quick test.

What if instead of a double list we model it as `topic0: [String!] @Pattern(regexp: "^(0x)?[a-fA-F0-9]{64}$"), topic1...`? This is clearer, in my opinion, still supports the same boolean logic, and it allows us to disallow nulls and use the pattern.

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +type ContractLogEvent {
You added it to the fields, but not the types.

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  contractId: EntityId!
nit: sort and add new lines between fields for readability and to match current schema.

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  topics: [String]!
I'm not sure what you mean by that. These are actual contract events, not filters, that can't have null for their values.
```suggestion
  """
  topics: [String!]!
```

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +type ContractLogSubscriptionInput {
It's still `type`, not `input`.

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  rsocket:
Mentions rsocket

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +#### GraphQL Schema
nit: I think the schema should be the first item under architecture as it's the highest level API (still nested under graphql)

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +
We should have an architectural diagram of the flow. See the HCS doc for an example. Can use draw.io or Lucid.

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +    "transactionIndex": "0x0"
The numeric types still show as hex string

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +- Use Bucket4J for rate limiting
How would we enforce a global active subscriptions? It would just be within a single process, not globally unless you're writing the value to redis.

I don't think we need bucket4j just to track active subscriptions. We do so already in gRPC API for metrics via a AtomicLong. We can do the same here and use the same subscriber count for both metrics and to throw an exception if it exceeds some property.

2023-04-13 03:47 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +- Messages received (From redis topic) rate
Don't need to change anything here, but noting we might get some of these for free with the libraries we use.

2023-04-13 12:33 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +- Messages received (From redis topic) rate
Globally may have been a bad word to use. Just want to ensure that the max subscriptions within this API don't exceed a particular threshold. Of course AtomicLong will handle this though

2023-04-13 15:12 UTC, xin-hedera commented on docs/design/contract-log-subscription.md
> +  topic3: [String!] @Pattern(regexp: "^(0x)?[a-fA-F0-9]{64}$")
the `eth_subscribe` spec is more flexible that it only has a `topics` array to match any topic in topic0-4, any reason we require users to use individual topicX arrays here?

2023-04-13 15:12 UTC, xin-hedera commented on docs/design/contract-log-subscription.md
> +| topics           | [contract_log.topic0, contract_log.topic1, contract_log.topic2, contract_log.topic3, contract_log.topic4] |
```suggestion
| topics           | [contract_log.topic0, contract_log.topic1, contract_log.topic2, contract_log.topic3] |
```

2023-04-13 15:23 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  topic3: [String!] @Pattern(regexp: "^(0x)?[a-fA-F0-9]{64}$")
The above should be equivalent to [eth_subscribe](https://docs.alchemy.com/reference/logs), just formatted differently. Eth supports a double array `[[String]]` so we're just flattening that outer array as fields.

2023-04-13 15:28 UTC, xin-hedera commented on docs/design/contract-log-subscription.md
> +  topic3: [String!] @Pattern(regexp: "^(0x)?[a-fA-F0-9]{64}$")
i c,  the alchemy link has the detailed spec.

2023-04-14 15:19 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  address: String!
The evm address is not known because we are adding this log to a batch holder in `EntityListener.onContractLog` and we would have to query the contract entity to obtain it. Since no other queries need to be performed to satisfy the needed fields for the `ContractLogEvent`, it makes sense to just use the account-num alias.

2023-04-14 15:25 UTC, jnels124 commented on docs/design/contract-log-subscription.md
> +  """
I was speaking of the array itself. Will make this field non null and require an empty array to indicate any value is allowed for the position.

2023-04-14 15:28 UTC, xin-hedera commented on docs/design/contract-log-subscription.md
> +  address: String!
It's cheap to get the EVM address in the graphql module, when we receive a subscription query, we can query the db for the contract id <-> evm address mapping, then in the flux pipeline, we can map the entity id to its evm address if available.

2023-04-14 15:28 UTC, steven-sheehy commented on docs/design/contract-log-subscription.md
> +  address: String!
The exception is if they provide an evm address as input, we map it to account num alias for filtering, then we should map it back to the matched evm address in the response

2023-04-14 16:06 UTC, xin-hedera commented on docs/design/contract-log-subscription.md
> +    ]
doesn't match the design of topic0...3

2023-04-14 21:10 UTC, steven-sheehy approved these changes
LGTM

2023-04-17 20:40 UTC, xin-hedera approved these changes
LGTM

2023-04-17 21:08 UTC, merged