Move updaters from services
hashgraph/hedera-mirror-node pull request #5765
Opened 2023-04-05 15:20 UTC by stoyan-lime

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-05 15:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +            return null;
We need a way to construct a new address based on the sequential logic in services. This might be - get the latest reserved contract id from the database, increment it by one and convert it to besu address.

2023-04-05 16:58 UTC, jnels124 commented on build.gradle.kts
> +        api("com.hedera.evm:hedera-evm:0.37.0-SNAPSHOT")
-SNAPSHOT intended to be merged?

2023-04-06 07:00 UTC, IvanKavaldzhiev commented on build.gradle.kts
> +        api("com.hedera.evm:hedera-evm:0.37.0-SNAPSHOT")
Yes, we should use the SNAPSHOT version for the current sprint development. Before releasing 79 mirror-node tag, we can change it to a final cut version.

2023-04-19 03:30 UTC, steven-sheehy requested changes

2023-04-19 03:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return null;
Don't we need to provide a value for this that differs per environment? If so, we should create a network enum and property to contain it.

2023-04-19 03:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +public class HederaEvmWorldState implements HederaEvmMutableWorldState {
If this is intended to temporarily be copied from services it should be in services package, right?

Same comment for other copied files in this package.

2023-04-19 13:39 UTC, IvanKavaldzhiev commented on build.gradle.kts
> +        api("com.hedera.evm:hedera-evm:0.37.0-SNAPSHOT")
Now that we have it, yes.

2023-04-19 13:47 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +        return ++latestEntityId;
We should cover more complex scenarios like creating several contracts in child transactions. We need to keep track of the next possible free `ContractID`. Probably we can keep a track of how much contracts we have created, e.g. `numAllocatedIds` and then add this value on top of the latest ID from DB.

2023-04-19 13:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +public class HederaEvmWorldState implements HederaEvmMutableWorldState {
This and the other updater classes are not directly copied from services but tailored versions for mirror-node. They should be kept permanently in the mirror-node, since we need `mirror-node` specific `Updaters` that communicate with the DB. Once the `EVM Journaling` mechanism is adapter and ready, we might get rid of the `Updaters` and have adapted `Journal` related components, but that would be further in the timeline, I guess.

2023-04-19 20:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +        return ++latestEntityId;
What about using the stackedstate to store the created contracts for the session? That would provide a more accurate contract ID and be more inline with how we store other session data.

2023-04-20 08:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +        return ++latestEntityId;
Seems reasonable. The reason why we chose the `Sequencer approach` is to have `eth_estimateGas` without precompiles support ready in the scope of this release. Since we don't have the stacked state changes merged yet, this would delay adding the support for keeping track of new ContractIDs and we won't be able to handle transactions that make nested contract creates with the first `eth_estimateGas` iteration. Unless we throw `OperationNotSupported` exception and add this logic after the stacked state is ready.

2023-04-20 13:12 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +                .setShardNum(newContractSponsor.getShardNum())
We mimic the logic from [here](https://github.com/hashgraph/hedera-services/blob/cca9daa719b12a195466f860fe148fb43e289a31/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/ids/SeqNoEntityIdSource.java#L79), where shards and realms are still used and taken from the sponsor account.

2023-04-20 13:19 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return true;
`isCreate2Enabled` is needed in `HederaEvmCreate2Operation` inside the `hedera-evm` library and we should provide a value for it.

`isLazyCreationEnabled` seems to be not used inside the library and we can delete it.

2023-04-20 14:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    public long getNextEntityId() {
Done

2023-04-20 14:11 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +        return ++latestEntityId;
I adapted the `Sequencer` logic following the `numAllocatedIds` idea so that we can fit the time frames.

2023-04-20 14:11 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return null;
Done

2023-04-20 21:04 UTC, steven-sheehy requested changes

2023-04-20 21:04 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    }
There's a lot wrong here:
- Using AtomicLong for `currentMaxIdFromDB` is unnecessary.
- `latestMaxIdFromDB` and `latestEntityId` duplicate each other. They're both always set to max from db on every call to `getNextEntityId`
- There's a race condition here that will reset `numAllocatedIds` if 500ms has elapsed and the same user request is still being handled. Thus there's a risk of entity ID overlap.
- `latestEntityId.addAndGet(numAllocatedIds.get() + 1L)` means next ID will increase non-sequentially after the first and mean that `if(currentMaxIdFromDB.get() != latestMaxIdFromDB.get())` will almost always return true.

What is the requirement here? No overlap of next entity IDs or accurate next entity IDs like consensus nodes would provide? The code doesn't really provide either. If it's just no overlap, can do something simple like use some fake higher level allocation range. I don't think these allocated IDs are the output of web3 module anywhere so we can go with purely fake range that guarantees no overlap, I believe.

```suggestion
    private final AtomicLong ENTITY_IDS = new AtomicLong(1_000_000_000);

    private long getNextEntityId() {
        return ENTITY_IDS.getAndIncrement();
    }
```

2023-04-21 13:16 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private HederaChainId chainId = HederaChainId.TESTNET;
Done

2023-04-21 13:16 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +        final EntityAddressSequencer entityAddressSequencer = new EntityAddressSequencer(entityRepository);
Done

2023-04-21 13:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    }
Actually the result we get from `getNextEntityId` is propagated through the EVM inside the Create op codes. A given user could implement a method which returns the address of a newly created contract via a factory method. So they could use `eth_call` to read such a value and we should provide correct results.

I simplified the algorithm for determining the correct next id.

The key point is here:

```
if(currentMaxIdFromDB > latestEntityId.get()) {
            latestEntityId.set(currentMaxIdFromDB);
}

```

The idea is that if the latest entityID was recently updated and the DB returns higher value than what was last allocated, we should increment the actual value returned by DB.

If the entity IDs are not being updated while we allocate new contractIDs, then we continue incrementing the lastly allocated contractID and leave `latestEntityId` as it is before incrementing.

2023-04-21 13:46 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    }
Thinking of this more, I think the users can't rely on an address for a newly created account returned during execution of `eth_call` calling a dynamic function, since calling this method again and again would return a different result and most importantly this newly created contract won't be persisted at all, so this address would be just a temporary valid address with no meaning after the execution.

What would be important is that we have a valid and not used address for the speculative creation of a new contract, so let's stick with your approach of having very large ranges. I'll update the PR.

2023-04-21 13:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +        latestEntityId.set(nextId);
This call is redundant.

2023-04-21 14:14 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    }
Adapted the logic to use very high synthetic ids.

2023-04-21 14:43 UTC, steven-sheehy approved these changes
LGTM

2023-04-21 14:48 UTC, merged