Copy unique token store model into hedera mirror web3
hashgraph/hedera-mirror-node pull request #5770
Opened 2023-04-06 07:36 UTC by ivan-02

**Description**:

We need to copy the `UniqueToken` store model into mirror-node, so that we use it as a value in the Stacked State Frame design. This would also mean the model should be immutable. It will both hold data for the `UniqueToken` and also perform some business logic internally.

**Related issue(s)**:

Fixes #5757

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-06 11:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +    private Id tokenId;
You can add also an `Address` field that is initialized by `id.asEvmAddress()` in the constructor.

2023-04-06 11:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java
> +//    }
If not used - delete all comments

2023-04-06 11:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +@AllArgsConstructor
You can delete `@Getter` and `@AllArgsConstructor` and use `@Value` instead.

2023-04-06 11:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + */
We can enhance the javadoc with information that we explicitly make this class immutable and explain why.

2023-04-06 14:07 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +    private Id tokenId;
Done

2023-04-06 14:07 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java
> +//    }
Done

2023-04-06 14:09 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +@AllArgsConstructor
The `@Builder` requires all args constructor if we are using custom constructor - in this case the one with `Address` field initialization.

2023-04-06 14:09 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + */
Done

2023-04-07 11:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +@AllArgsConstructor
I think we can delete the custom constructor and use the one provided by the @Value annotation.

2023-04-07 12:15 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + */
We can adapt the last sentence like this:

This model is used as a value in a special state, used for speculative write operations.

2023-04-07 12:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java
> +public class EntityNum implements Comparable<EntityNum> {
Do we need this class?

2023-04-07 16:01 UTC, steven-sheehy requested changes

2023-04-10 09:03 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java
> +public class EntityNum implements Comparable<EntityNum> {
Removed

2023-04-10 09:04 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + */
Done

2023-04-10 09:04 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +@AllArgsConstructor
Done

2023-04-10 09:05 UTC, ivan-02 commented on hedera-mirror-web3/build.gradle.kts
> +    testImplementation("org.mockito:mockito-inline:2.7.21")
Done

2023-04-10 14:31 UTC, steven-sheehy approved these changes
LGTM

2023-04-10 14:45 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + */
I don't think we should be using Lombok in services copied code. We should try to keep this files as exact copies or as close as we can to its upstream services code so we can easily update it in the future.

2023-04-11 07:03 UTC, ivan-02 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + */
In order to make the object immutable and keep the code as close as we can to services, I've removed the setters and made the fields final.

2023-04-11 14:25 UTC, steven-sheehy approved these changes

2023-04-11 14:26 UTC, merged