Add synthetic token account migration
hashgraph/hedera-mirror-node pull request #5776
Opened 2023-04-06 22:28 UTC by edwin-greene

**Description**:
Add a migration to update the owners of synthetic token allowances to the correct contract result spender id.

**Related issue(s)**:

Fixes #5715  

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-04-10 15:32 UTC, xin-hedera requested changes

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +    public SyntheticTokenAllowanceOwnerMigration(JdbcOperations jdbcOperations,
the SQL delete rows so need owner which has delete permission

```suggestion
    public SyntheticTokenAllowanceOwnerMigration(@Owner JdbcOperations jdbcOperations,
```

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +        }
all database operations need to be in a single db transaction, not just sqlEntityListener. otherwise if we fail at the middle, we may lose data because the SQL delete rows.

you need to

- change to jdbcTemplate
- construct a `DataSourceTransactionManager` using the datasource from `jdbcTemplate.getDataSource`
- construct a new `TransactionTemplate` using the `DataSourceTransactionManager`
- run all database operations in `transactionTemplate.execute`

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +    private final @Owner JdbcTemplate jdbcTemplate;
```suggestion
```

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +    }
this is already done by IntegrationTest using the cleanup.sql
```suggestion
```

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +        return Pair.of(tokenAllowanceExpected, tokenAllowanceHistoryExpected);
should just use `domainBuilder` to construct and persist tokenAllowance (history) and the corresponding contractResult

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +
add a test case for idempotency: run the migration twice, and get the same result as if it only ran once

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +                .containsExactlyInAnyOrderElementsOf(affectedTokenAllowancePair.getRight());
don't think it's necessary to verify the test case is set up properly

2023-04-10 15:32 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +
assume there is an incorrect row with `(owner=A, payer=A, token=T)` in `token_allowance`,
there should be at least one correct row `(owner=C, payer=A, token=T)`

same applies to `token_allowance_history`

such setup verifies the migration can fix the owner as well as stitching the bad rows and good rows

2023-04-11 16:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +    public SyntheticTokenAllowanceOwnerMigration(JdbcOperations jdbcOperations,
Thanks I have updated it.

2023-04-11 16:09 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +    private final @Owner JdbcTemplate jdbcTemplate;
Removed.

2023-04-11 16:10 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +        return Pair.of(tokenAllowanceExpected, tokenAllowanceHistoryExpected);
Sounds good. I have updated the setup methods for the test to no longer use sqlEntityListener to generate the history.

2023-04-11 16:10 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +
Got it, I have added that test case.

2023-04-11 16:11 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +
Great idea. I have added that scenario into the test cases.

2023-04-12 14:30 UTC, xin-hedera requested changes

2023-04-12 18:01 UTC, xin-hedera approved these changes
LGTM

2023-04-13 20:34 UTC, steven-sheehy approved these changes

2023-04-14 18:34 UTC, merged