HIP-584: Fix failing ERC acceptance tests
hashgraph/hedera-mirror-node pull request #5780
Opened 2023-04-08 19:24 UTC by IvanKavaldzhiev

**Description**:

This PR fixes flaky behaviour of ERC precompile acceptance tests. The flaky behaviour was introduced, since we don't await the last HAPI call was properly imported into the mirror-node and there were cases where the created tokens via HAPI were not processed and presented in the DB.

In addition, the exception handling logic was enhanced to catch exceptions triggered via missing entities in the DB and now we return `404 NOT FOUND` instead of `400 BAD REQUEST`.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-08 19:58 UTC, steven-sheehy requested changes
Tests seem to be failing.

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +            throw new EntityNotFoundException("No such contract or token");
We should print out the hex address so users know which address is missing. Same comment for the other throw statement but change it to `"Not a contract or token: " + addressOrAlias`.
```suggestion
            throw new EntityNotFoundException("No such contract or token: " + addressOrAlias);
```

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends MirrorNodeException {
```suggestion
public class EntityNotFoundException extends EvmException {
```

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +    private Mono<GenericErrorResponse> tokeOrContractMissingError(final EntityNotFoundException e) {
```suggestion
    private Mono<GenericErrorResponse> notFound(final EntityNotFoundException e) {
```

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        log.warn("Missing entity error: {}", e.getMessage());
May expand to other things besides entities.
```suggestion
        log.warn("Not found: {}", e.getMessage());
```

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +        given(service.processCall(any())).willThrow(new EntityNotFoundException("No such contract or token"));
nit: Store message as a variable so it can be reused below

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/erc.feature
> +            | "INFINITE" | 200            | "BOB"       | "ALICE"                   | "ALICE"               | 2          |
I know we do this elsewhere, but I'm not sure why we do as it's only ever 200. Can just hardcode in the string above.

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        log.info("Verify mint transaction");
Remove log as we may reuse this to verify other transactions in the future. Cucumber will print the step name anyway.

2023-04-08 19:58 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        assertThat(mirrorTransaction.getEntityId()).isEqualTo(tokenIds.get(1).toString());
Can omit this line since the above will verify things.

2023-04-10 06:22 UTC, georgi-l95 approved these changes
LGTM

2023-04-10 06:22 UTC, georgi-l95 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliasesTest.java
> +                .hasMessage("Not a contract or token: 0x00000000000000000000000000000000000004e4");
nit: could use already allocated variable at the top of this class for this address, instead of hardcoding.

2023-04-10 06:22 UTC, georgi-l95 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliasesTest.java
> +                .hasMessage("No such contract or token: 0x00000000000000000000000000000000000004e5");
nit: could use already allocated variable at the top of this class for this address, instead of hardcoding.

2023-04-10 14:23 UTC, steven-sheehy approved these changes
LGTM

2023-04-10 14:23 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        MirrorTransaction mirrorTransaction = verifyMirrorTransactionsResponse(mirrorClient, status);
nit: Unused variable

2023-04-10 14:50 UTC, georgi-l95 approved these changes

2023-04-10 14:53 UTC, jascks commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        log.warn("Not found: {}", e.getMessage());
Does this need to be at warning level given the contract address or alias is client supplied? Perhaps debug level?

2023-04-10 15:08 UTC, xin-hedera approved these changes

2023-04-10 15:08 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        log.warn("Not found: {}", e.getMessage());
We use `warn` for other type of errors except `INTERNAL_SERVER_ERROR`. I think we should stick to a common approach and make all logs having `WARN` or `DEBUG` level. @steven-sheehy what are your thoughts?

2023-04-10 15:17 UTC, jascks commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        log.warn("Not found: {}", e.getMessage());
My concern is that a client, willfully or accidentally, could generate a lot of warnings by providing bogus contract IDs.  But, perhaps things are dealt with sufficiently within the system. I'm. still pretty new here. :)

2023-04-10 15:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        log.warn("Not found: {}", e.getMessage());
I agree with Jeff in general that user errors should not generate extra logs. But we still want to have at least one log for each request, which the `LoggingFilter` currently gives us. If we could combine this message with the log from there it would be ideal. But that's out of scope and I think this module is still very new so it's okay to keep at warn for now as we gain experience with it. We can adjust the levels later once we start getting any traffic.

2023-04-10 15:34 UTC, jascks approved these changes
LGTM

2023-04-10 15:35 UTC, merged