HIP-584: `StackedStateFrames` - 5of5 - `StackedStateFrames` itself - component complete
hashgraph/hedera-mirror-node pull request #5805
Opened 2023-04-12 01:53 UTC by david-bakin-sl

**Description**:

`StackedStateFrames` is a component to support `eth_call` and `eth_estimateGas`.

This provides a layer-based (or _frame_-based) cache that corresponds to the need to read and _update_ Hedera entities (accounts, contracts, tokenrels, etc) during execution of `eth_call` and `eth_estimateGas`, accounting for both success and _revert_ (failure) of nested contracts.

Also fulfills the goals of:

* allowing extension if other Hedera entities (than originally envisioned) need to be cached
* ensures that _all_ contract executions of the same contract, as performed by `eth_estimateGas` during its search for proper gas requirement, access the _same_ Hedera account state
* full type-safety when accessing Hedera entities via the cache

This component has been divided into 5 PRs for ease of understanding and review:

1. #5801 - Design documentation - suitable for a design review
2. #5802 - `UpdatableReferenceCache` and tests  - a cache of untyped (any type) items (K->V pairs) that records cache "line" state relative to upstream caches
3. #5803 - `CachingStateFrame` and subclasses and tests  - one level of the stacked state - holds entities of multiple types (with K->V pairs) and fully type-safe access; with subclasses for a read-only cache level and a read-write cache level
4. #5804 - `DatabaseBackedStateFrame`  - most-upstream-cache level, this is where you go to the database for requested entities - parameterized by an interface that is the actual accessor to the database (or whatever is the source of ground truth)
5. #5805 - `StackedStateFrames` and test -  ⬅ **you are here** - this is where the actual stacking/unstacking of the stack frames happens, including maintaining a "base" of a RO-cache on top of a database-backed-cache, to support the need for _multiple_ contract executions to operate against the _same_ Hedera initial values.

**Related issue(s)**:

Fixes #5562

**Checklist**

- [x ] Documented (design documentation including diagrams, javadoc)
- [x ] Tested (unit)
    - 100% unit test coverage, except for `DatabaseBackedStackFrame` which is 0% coverage - should be tested when accessors to the database are provided

2023-04-19 04:12 UTC, steven-sheehy requested changes

2023-04-19 04:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +        // alternatively, maybe that's hidden inside the GroundTruthAccessors.
```suggestion
        // alternatively, maybe that's hidden inside the DatabaseAccessor.
```

2023-04-19 04:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +        }
I believe each call will create a `StackedStateFrames`. If so, we should optimize its creation so that shared, immutable objects are only created once on startup (or once lazily). I believe most of these checks and data structures here can be extracted out and performed once.

2023-04-19 04:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +            throw new IllegalArgumentException("Frame argument must have current TOS as its upstream");
It's an illegal argument to this method, but how will this bubble up to the user? Illegal arguments from the API perspective look as though they entered some bad input. We may want to throw some custom exception here and elsewhere in these PRs for validations keeping that in mind. Please consult with Ivan on this.

2023-04-24 12:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +     * hits the database (via the ground truth accessors), all subsequent executions will fetch the same values
ground truth accessors -> database accessors

2023-04-25 03:24 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +        // alternatively, maybe that's hidden inside the GroundTruthAccessors.
Fixed.  (And also another one later.)

2023-04-25 03:24 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +        }
Leaving this for a subsequent issue/PR as this is a desirable optimization we don't need right now. (I'll call it 05562.6-stacked-hedera-state and the issue will be filed soon.)

2023-04-25 03:28 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StackedStateFrames.java
> +            throw new IllegalArgumentException("Frame argument must have current TOS as its upstream");
This method and `replaceEntireStack` changed to package-private visibility to make them _not_ part of the API.  In fact, they're only useful for testing, so I'll annotate it with `@VisibleForTesting` too.  (Which, IMO, means that `IllegalArgumentException` is acceptable.)

2023-04-25 19:53 UTC, steven-sheehy submitted a review, later dismissed

2023-04-26 02:50 UTC, Nana-EC approved these changes

2023-04-26 22:22 UTC, steven-sheehy commented
It would be nice if you also could address the one lonely code smell on the repo introduced by your last PR. Think a deep exception hierarchy is fine so can suppress. https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=hedera-mirror-node&open=AYekyQBMamtxMmHdvVmA

2023-04-27 00:36 UTC, david-bakin-sl commented
> Think a deep exception hierarchy is fine so can suppress.

Sorry, I meant to do that.  Sonar rule isn't precise enough to realize that a deep exception hierarchy is an exception to the hierarchy rule.

2023-04-29 01:13 UTC, steven-sheehy commented
Haven't reviewed yet, but noticed there's a code smell. We shouldn't have todo or fixme comments. Think you can just remove this one.

2023-04-29 02:22 UTC, david-bakin-sl commented
> And the previous code smell i mentioned...

The previous one was the exception class hierarchy right?  I nuked that in the sonar dashboard.

2023-04-29 23:51 UTC, steven-sheehy approved these changes
LGTM

2023-04-29 23:51 UTC, steven-sheehy commented
> The previous one was the exception class hierarchy right? I nuked that in the sonar dashboard.

For future reference, in general we should not manually suppress things in sonar UI so it doesn't show up again if we re-import the project or touch that code again.

2023-04-30 05:22 UTC, merged