5799 create a runbook to document local stream file verification
hashgraph/hedera-mirror-node pull request #5873
Opened 2023-04-20 00:28 UTC by jnels124

Add document to describe how to verify stream files locally

**Related issue(s)**:

Fixes #5799

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-04-20 16:55 UTC, steven-sheehy requested changes

2023-04-20 16:55 UTC, steven-sheehy commented on docs/runbook/stream-verification.md
> +1. cd {HEDERA_REPO}
Could remove HEDERA_REPO everywhere and just put a note at the top like:

> Note: All commands assumed to be ran from the git repository root

2023-04-20 16:55 UTC, steven-sheehy commented on docs/runbook/stream-verification.md
> +2. password is located in docker-compose.yml in this repo and defaulted to `mirror_node_pass`
Should add additional verifications like verifying logs for no errors and verify new account balance and record files are showing up in their tables.

2023-04-20 16:55 UTC, steven-sheehy commented on docs/runbook/stream-verification.md
> +          dataPath: {PATH_TO_RECORD_STREAMS} # will create sub dirs /streams/accountBalances/record{NODE1...NODEn} /streams/recordstreams/record{NODE1...NODEn}. Must have the signature file and the r
Maybe add this comment to the paragraph above.

2023-04-20 16:55 UTC, steven-sheehy commented on docs/runbook/stream-verification.md
> +3. docker-compose up db
There might be errors if you don't also run redis. Should either run it or disable it via importer config.

2023-04-20 18:29 UTC, steven-sheehy submitted a review, later dismissed

2023-04-20 19:10 UTC, MarcKriguerAtHedera approved these changes
LGTM

2023-04-20 19:25 UTC, xin-hedera requested changes

2023-04-20 19:25 UTC, xin-hedera commented on docs/runbook/stream-verification.md
> +1. `psql -U mirror_node`
without it, psql tries to connect through unix socket

```suggestion
1. `psql -h localhost -U mirror_node`
```

2023-04-20 19:25 UTC, xin-hedera commented on docs/runbook/stream-verification.md
> +          dataPath: { PATH_TO_RECORD_STREAMS }
I believe `dataPath` should be at `hedera.mirror.importer.dataPath`

2023-04-20 19:25 UTC, xin-hedera commented on docs/runbook/stream-verification.md
> +When starting the application, the following subdirectories will be created under `${hedera.mirror.importer.downloader.mirrorProperties.dataPath}`
```suggestion
When starting the application, the following subdirectories will be created under `${hedera.mirror.importer.dataPath}`
```

2023-04-20 19:25 UTC, xin-hedera commented on docs/runbook/stream-verification.md
> +`/streams/accountBalances/record{NODE1...NODEn}` `/streams/recordstreams/record{NODE1...NODEn}` where n is the number of nodes in the address book.
```suggestion
`/streams/accountBalances/balance{NODE1...NODEn}` `/streams/recordstreams/record{NODE1...NODEn}` where n is the number of nodes in the address book.
```

2023-04-20 21:58 UTC, jnels124 commented on docs/runbook/stream-verification.md
> +          dataPath: { PATH_TO_RECORD_STREAMS }
This sets it specifically for the CommonDownloaderProperties. I can look at the higher level prop to make sure it works set there.

2023-04-20 22:00 UTC, xin-hedera commented on docs/runbook/stream-verification.md
> +          dataPath: { PATH_TO_RECORD_STREAMS }
It should work and in fact it’s the same bean. Although setting is here also works but we should follow what’s in our configuration.md

2023-04-21 15:21 UTC, xin-hedera approved these changes
LGTM

2023-04-21 16:10 UTC, merged