Importer Log and Alert Fixes
hashgraph/hedera-mirror-node pull request #5902
Opened 2023-04-25 15:53 UTC by jnels124

* fix alerts

**Description**:

This PR modifies ... in order to support ...
* Change importer restart required and recoverable error alerts to fire on single occurrence
* Remove logging empty entity id when looking up entity
* Only log recoverable error for empty contractId if lookup is not expected to be empty

**Related issue(s)**:

Fixes #5820

**Notes for reviewer**:
* Ran common chart in minikube and fired several different logs on scheduled. Asserted alerts appeared in alertmanager.
* Verified `ContractResultServiceImpl` by loading the record file for the [transaction](https://hashscan.io/testnet/transaction/1681491693.022293003) contained in #5820. 
* Removed logging of empty entity id in lookup service

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-04-25 16:07 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityIdServiceImpl.java
> -            log.warn("Skipping entity ID {}", entityIdProto);
I removed this log as it is common for one or may ids to be passed to this method to be empty. Considered adding a log at the end if all is empty and including all attempted ids. Will leave that to the reviewers to request

2023-04-25 16:52 UTC, jnels124 commented
Will address code cov but wanted a review first

2023-04-25 20:14 UTC, steven-sheehy requested changes

2023-04-25 20:14 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
>                | message =~ ".*(Error starting watch service|Unable to fetch entity types|Unable to fetch transaction types|environment variable not set|Cannot load configuration from).*"
Not related to your PR, but literally none of these log statements are still around or applicable. We should actually remove this `ImporterRequiresRestart` alert since it's impossible to occur.

2023-04-25 20:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var contractCallOrCreate = isContractCreateOrCall(transactionBody);
nit: Might move this up to reuse it for prior invocation.

2023-04-25 20:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                && ((contractCallOrCreate && !EntityId.isEmpty(transaction.getEntityId()))
A contract create can fail and thus would not have an allocated contract ID. We don't want to log for that common scenario. If it was invalid for that, that should be logged by `EntityRecordItemListener`. So think we should remove all logging for transaction.getEntityId() scenario.

2023-04-26 17:15 UTC, steven-sheehy approved these changes

2023-04-26 17:42 UTC, xin-hedera approved these changes
LGTM

2023-04-26 20:50 UTC, edwin-greene approved these changes
Looks good

2023-04-26 21:39 UTC, MarcKriguerAtHedera approved these changes
Looks goof to me.

2023-04-26 21:39 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityIdServiceImpl.java
> -            log.warn("Skipping entity ID {}", entityIdProto);
I (for one) don't really think that's needed.

2023-04-27 15:13 UTC, merged