Implement first 4 steps of the suggested fix for Issue 5849:
hashgraph/hedera-mirror-node pull request #5903
Opened 2023-04-25 17:17 UTC by MarcKriguerAtHedera

* Remove all token* constructors in services.constructor package
* Remove HTS related table (token, token_transfer, nft_transfer) query and processing in persistence.TransactionRepository
* Remove fungible / non fungible token account balance support in persistence.AccountRepository
* Remove HTS BDD test case

Also, for the first three bullets, fix the tests broken by removing that code.

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-26 00:34 UTC, xin-hedera requested changes

2023-04-26 00:34 UTC, xin-hedera commented on charts/hedera-mirror-rosetta/postman.json
> -    {
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/common_test.go
> -		},
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -	Memo                          string            `json:"memo"`
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -	AutoRenewPeriod               int64             `json:"auto_renew_period"`
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			SetAutoRenewPeriod(time.Second * time.Duration(autoRenewPeriod)).
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetAutoRenewPeriod(time.Second * time.Duration(autoRenewPeriod)).
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetAutoRenewPeriod(time.Second * time.Duration(autoRenewPeriod)).
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -		},
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -		},
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	assert.Equal(t, operation.Metadata["auto_renew_period"], int64(tx.GetAutoRenewPeriod().Seconds()))
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	assert.Equal(t, operation.Metadata["memo"], tx.GetAccountMemo())
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			"auto_renew_period":                autoRenewPeriod,
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			"memo":                             memo,
revert

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                                      coalesce(ab.balance, 0) balance
there are many places in this file referencing token related tables including `token`, `token_transfer`, and `nft_transfer`. there are also more fields, data structures, and code in methods to remove

2023-04-26 00:34 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> -	NftTransfers         string
also remove any comment related to token, token transfer, nft transfer in this file

2023-04-26 20:27 UTC, MarcKriguerAtHedera commented on charts/hedera-mirror-rosetta/postman.json
> -    {
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/common_test.go
> -		},
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -	Memo                          string            `json:"memo"`
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -	AutoRenewPeriod               int64             `json:"auto_renew_period"`
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor.go
> -
Done.

2023-04-26 20:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			SetAutoRenewPeriod(time.Second * time.Duration(autoRenewPeriod)).
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetAutoRenewPeriod(time.Second * time.Duration(autoRenewPeriod)).
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetAutoRenewPeriod(time.Second * time.Duration(autoRenewPeriod)).
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -		},
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -		},
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	assert.Equal(t, operation.Metadata["auto_renew_period"], int64(tx.GetAutoRenewPeriod().Seconds()))
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	assert.Equal(t, operation.Metadata["memo"], tx.GetAccountMemo())
Done.

2023-04-26 20:29 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			"auto_renew_period":                autoRenewPeriod,
Done.

2023-04-26 20:31 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                                      coalesce(ab.balance, 0) balance
Done.  There are no more references to "token" (or "nft") in the file.  I think I got everything, but please let me know if there's anything else that also should go away.

2023-04-26 20:31 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/transaction.go
> -	NftTransfers         string
Done (same as previous comment -- I think I have deleted everything that's related).

2023-04-27 00:50 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                                      coalesce(ab.balance, 0) balance
- remove `accountBalanceChange.TokenAssociations`, `accountBalanceChange.TokenValues`, `combinedAccountBalance.TokenBalances`
- rename `combinedAccountBalance` to `accountBalance`

2023-04-27 01:09 UTC, xin-hedera commented
remove these files

- /app/domain/types
  - token.go
  - token_test.go
- /app/persistence/domain
  - nft*.go
  - token*.go

2023-04-27 01:09 UTC, xin-hedera requested changes

2023-04-27 01:09 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> +	symbolA  = "foobar"
remove

2023-04-27 01:09 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> +	}
remove

2023-04-27 01:09 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> +	tokenEntityIdA = domain.MustDecodeEntityId(212)
remove. also remove any test cases with token, tokenAmount, and etc

we should also remove `TokenAmount` in domain/types/amount.go

2023-04-27 01:09 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_transfer_transaction_constructor_test.go
there are still token related references in this test file

2023-04-28 00:46 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/transaction_test.go
> +	expected := suite.setupDb()
Done.

2023-04-28 00:46 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/transaction_test.go
> +	expected := suite.setupDb()
Done.

2023-04-28 00:47 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/transaction_test.go
> +func (suite *transactionRepositorySuite) setupDb() []*types.Transaction {
Done (and done).

2023-04-28 00:47 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> +	symbolA  = "foobar"
Done -- this was only needed for dbTokenA (below, also removed).

2023-04-28 00:47 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> +	}
Done.

2023-04-28 00:48 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> +	tokenEntityIdA = domain.MustDecodeEntityId(212)
Done (and done).

2023-04-28 00:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_transfer_transaction_constructor_test.go
Done.

2023-04-28 14:54 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +                                      coalesce(ab.balance, 0) balance
I missed this pair of suggestions (yesterday).  I had already done the first (before seeing it), but I did just (now) do the suggested rename.  I also renamed the variable (containing the result) from `cb` to `ab` to reflect the new name.

2023-04-28 15:39 UTC, xin-hedera requested changes

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/amount_test.go
> -func TestNewAmountSuccess(t *testing.T) {
revert, and the test case now only needs to test `NewAmount` with hbar amount

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/amount_test.go
>  	metadatasBase64   = []interface{}{"Zm9v", "YmFy"}
remove `tokenId`, `tokenIdStr`, `metadatasBytes`, `metadatasBase64`

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/common.go
> -	accountId, err := types.NewAccountIdFromSdkAccountId(account)
just delete the function `parseTokenFreezeKyc` and `preprocessTokenFreezeKyc`

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	maxAutomaticTokenAssociations uint32 = 10
revert

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			SetMaxAutomaticTokenAssociations(maxAutomaticTokenAssociations).
revert

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetMaxAutomaticTokenAssociations(maxAutomaticTokenAssociations).
revert

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetMaxAutomaticTokenAssociations(maxAutomaticTokenAssociations).
revert

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	assert.Equal(t, operation.Metadata["max_automatic_token_associations"], tx.GetMaxAutomaticTokenAssociations())
revert

2023-04-28 15:39 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			"max_automatic_token_associations": maxAutomaticTokenAssociations,
revert

2023-04-28 18:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/domain/types/amount_test.go
> -
Done.

2023-04-28 18:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/domain/types/amount_test.go
> -func TestNewAmountSuccess(t *testing.T) {
Done.

2023-04-28 18:26 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/domain/types/amount_test.go
> -func TestNewAmountFailure(t *testing.T) {
Done.

2023-04-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/domain/types/amount_test.go
>  	metadatasBase64   = []interface{}{"Zm9v", "YmFy"}
Done.

2023-04-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/common.go
> -	accountId, err := types.NewAccountIdFromSdkAccountId(account)
Done.

2023-04-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	maxAutomaticTokenAssociations uint32 = 10
Done.

2023-04-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			SetMaxAutomaticTokenAssociations(maxAutomaticTokenAssociations).
Done.

2023-04-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetMaxAutomaticTokenAssociations(maxAutomaticTokenAssociations).
Done.

2023-04-28 18:27 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -					SetMaxAutomaticTokenAssociations(maxAutomaticTokenAssociations).
Done.  I was a little too eager deleting everything about TokenAssociations.

2023-04-28 18:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -	assert.Equal(t, operation.Metadata["max_automatic_token_associations"], tx.GetMaxAutomaticTokenAssociations())
Done.

2023-04-28 18:28 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/crypto_create_transaction_constructor_test.go
> -			"max_automatic_token_associations": maxAutomaticTokenAssociations,
Done.

2023-04-28 20:06 UTC, xin-hedera requested changes

2023-04-28 20:06 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	return ab.ConsensusTimestamp, &hbarAmount, nil
there looks to be lost test coverage, Codecov resports this line is not covered

2023-04-28 20:59 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/domain/types/amount.go
>  	}
Done.

2023-04-28 21:01 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	return ab.ConsensusTimestamp, &hbarAmount, nil
I think that the (remaining) tests all return earlier in the method; I am going to let `codecov` run against the current version of the files (just updated) and confirm that.  We may need to devise a new test (or new tests) that still use Hbar currency to try to trigger the other `return` lines.

2023-04-28 21:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	return change.Value, nil
Same comment as above -- we have deleted many tests, some of which triggered the errors that we are no longer seeing.

2023-04-28 21:03 UTC, MarcKriguerAtHedera commented
I ran `gofmt -v` as requested -- a couple of files did get changed (whitespace only) as a result.

2023-04-28 21:38 UTC, MarcKriguerAtHedera commented
I don't codecov is finding **new** lines that aren't covered; I think most of these were previously not covered, and the tool is just labelling every line where there was any sort of change (e.g. removing one of the return types of a method so the "return" line has one fewer parameter) as a line with no coverage.

2023-04-28 22:16 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	return ab.ConsensusTimestamp, &hbarAmount, nil
no, I just ran `account_test.go` from the PR branch and main, there's definitely good amount of test coverage loss. Please review the changes to the test cases.

2023-04-28 22:17 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	return change.Value, nil
disagree. the above line and many others are on the happy path. they no longer have test coverage, most likely because in `account_test.go` the data was set up incorrectly

2023-05-01 14:25 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/account.go
> +	return ab.ConsensusTimestamp, &hbarAmount, nil
I did that on Friday (but did not comment here).  It's down to just 2 lines.  Is that OK with you, or do I need to add additional tests to bring it down to 0?

2023-05-01 15:10 UTC, xin-hedera requested changes

2023-05-01 18:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/services/construction/common.go
>  }
Done.

2023-05-01 18:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/persistence/account_test.go
>  	token3SentSerials     = []int64{5}
Done.

2023-05-01 19:27 UTC, xin-hedera approved these changes
LGTM

2023-05-01 19:28 UTC, steven-sheehy approved these changes
LGTM

2023-05-01 19:45 UTC, merged