Implement topic message lookup
hashgraph/hedera-mirror-node pull request #5954
Opened 2023-05-04 18:37 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #5798 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-05-04 21:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessorTest.java
> -    void notSetAndDemoNetworkAndDatabaseNotEmpty() {
this test case is identical to `notSetAndDatabaseNotEmpty` with only difference in network set to `DEMO`, so I just removed it

2023-05-12 18:24 UTC, steven-sheehy requested changes
Still reviewing

2023-05-12 18:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TopicMessageLookupRepository.java
> +            order by topic_id, consensus_timestamp desc
Some of these might actually be the last since it doesn't include the ones from the current file, but I guess that will be corrected by the upserter?

2023-05-12 18:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +        if (!isEnabled() || recordFile == null) {
that's a side effect from `ErrataMigration`

2023-05-12 18:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +        }
sort of, but it won't work for partitions with range

`FOR VALUES FROM ('2') TO ...`
`FOR VALUES FROM ('100') TO ...`

2023-05-12 18:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +    private final Map<Long, TopicMessageLookup> lastTopicMessageLookups;
not sure I understand it, but `lastTopicMessageLookups` keeps the last topic message of topics with messages in a record file

2023-05-12 18:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +        }
usually the last partition would be at least one month ahead of the current month so. The first partition wouldn't work either since we do keep the just closed partition since the record file closing the partition may get reprocessed.

We can instead prune partitions before the month prior to the current partition though

2023-05-12 18:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                lastStreamFile.get().filter(s -> s.getConsensusEnd() != null).ifPresent(streamFile::setPrevious);
I'd need to keep filtering by `s.getConsensusEnd() != null` since I don't think we should chain a made-up stream file. Will add the chained check

2023-05-12 19:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TopicMessageLookupRepository.java
> +            order by topic_id, consensus_timestamp desc
`update` inserts the last topic message for topics in the partition [from, to), the last in a partition may not be the last message of a topic though, so `last` of the rows is set to `false` in the SQL

2023-05-12 19:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/CompositeRecordStreamFileListener.java
> +        }
that would need a `onEach(BiConsumer)`

2023-05-12 19:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +        return topicMessagePartitions.isPresent();
sure

2023-05-12 19:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +    private final Map<Long, TopicMessageLookup> lastTopicMessageLookups;
I meant singleton beans should not be stateful. We discussed putting this state into the `RecordFile` into some temporary context object.

2023-05-12 19:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/CompositeRecordStreamFileListener.java
> +        }
Ok, nevermind then.

2023-05-12 19:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TopicMessageLookupRepository.java
> +            order by topic_id, consensus_timestamp desc
>  last in a partition may not be the last message of a topic

Right, but you say may note be. So isn't the opposite also true? That the last in a partition may be the last message of a topic?

2023-05-12 20:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TopicMessageLookupRepository.java
> +            order by topic_id, consensus_timestamp desc
yes

2023-05-15 22:23 UTC, steven-sheehy requested changes

2023-05-15 22:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +            where sequence_number = 1;
This isn't really intended to be repeatable, right? Just doing so we can use repository.

2023-05-15 22:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var partitions = timePartitionService.getTimePartitions("topic_message");
Use the constant

2023-05-15 22:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +                    return Optional.empty();
The service returns empty when the table is not partitioned at all, so there’s no concern to cache it for 1d since we’d need a schema change to partition it which definitely requires importer upgrade / restart

2023-05-15 22:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +            last.setPrevious(null);
It’s a bit tricky. The cached last is a copy of the streamFile object passed to parser, so though the link is cleared here, it only breaks the link for precious’s previous

2023-05-15 22:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/topic/TopicMessageLookupEntityListener.java
> +        if (!isEnabled() || recordFile == null) {
Line 254 of ErrataMigration, null is passed to onEnd

2023-05-15 22:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +            last.setPrevious(null);
It’s probably better to add a Long preciousConsensusEnd to StreamFile instead

2023-05-15 22:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +            where sequence_number = 1;
Repeatable so if we somehow build the table wrong, we can fix any issue in importer and / or the migration, then rerun

2023-05-16 04:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +            last.setPrevious(null);
Right, so we copy it before sending to parser including `previous`. So that means it's not a race condition but actually a separate memory leak in parser since we store last there too, right?

2023-05-16 14:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +            last.setPrevious(null);
there's no memory leak.

The StreamFile object passed to parser has a previous link pointing to the cloned & cached last in downloader. The cached last in downloader's previous is set to null when the next StreamFile is downloaded and verified. As a result, there is no infinite previous link back to the verify first cached last.

Anyways, I have removed the previous link and switched to `Long previousConsensusEnd` instead.

2023-05-18 18:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CacheConfiguration.java
> +        caffeineCacheManager.setCacheSpecification("maximumSize=50,expireAfterWrite=1d");
don't want to set max too big since the same config is also used for the overlapping time partitions and its cache for a record file should only be useful for ~2 seconds

2023-05-18 18:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.80.1__topic_message_lookup.sql
> +-- create extension if not exists btree_gist;
the new extension is created in the init.sql/sh script. To avoid failure and manual intervention during importer upgrade, we may have to add it to this migration in order to successfully create the gist index

or we can choose to not create the extension & index at all and defer it when we enable topic message partitioning.

2023-05-18 19:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.80.1__topic_message_lookup.sql
> +-- create extension if not exists btree_gist;
decided to skip the extension and gist index in v1

2023-05-22 23:24 UTC, steven-sheehy requested changes

2023-05-22 23:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionService.java
> +    Optional<List<TimePartition>> getTimePartitions(String tableName);
I might be mistaken, but it seems like clients to this method no longer care if the response is `Optional.empty()` or not anymore. So might be able to simplify.
```suggestion
    List<TimePartition> getTimePartitions(String tableName);
```

2023-05-22 23:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var stopwatch = Stopwatch.createStarted();
We should probably do a similar check as in `TopicMessageLookupEntityListener.isEnabled()`.

2023-05-22 23:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +public class TopicMessageLookupMigration extends RepeatableMigration {
Should we skip this migration if not v2?

2023-05-23 15:05 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  DB_SPECIFIC_EXTENSION_SQL="create extension if not exists btree_gist;
so it comes with the official postgresql docker image, and it must be the docker image is built with target including the `btree_gist` extension

2023-05-23 15:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionService.java
> +    Optional<List<TimePartition>> getTimePartitions(String tableName);
sure, can remove the optional

2023-05-23 15:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +public class TopicMessageLookupMigration extends RepeatableMigration {
we still need it for v2

- if we re-ingest the data, this is a repeatable sync migration, it doesn't do anything when it runs
- if we dump v1 data (with an empty `topic_message_lookup` table) and load into v2, we definitely need to run the migration to backfill

2023-05-23 15:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var stopwatch = Stopwatch.createStarted();
oh sure

2023-05-23 16:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +public class TopicMessageLookupMigration extends RepeatableMigration {
My question was about needing it for v1.

2023-05-23 16:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +public class TopicMessageLookupMigration extends RepeatableMigration {
umm, no harm to keep it for v1. in any case we need to time partition topic_message v1, we can then change the checksum in config and run it.

2023-05-23 17:42 UTC, jnels124 approved these changes
LGTM

2023-05-23 18:31 UTC, merged