HIP-584: Add MirrorOperationTracer that logs message frame data
hashgraph/hedera-mirror-node pull request #5961
Opened 2023-05-05 18:18 UTC by IvanKavaldzhiev

**Description**:

**Related issue(s)**:

Fixes #5951 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-09 13:22 UTC, david-bakin-sl requested changes
Especially needs a test and please don't forget to test the _logging_ statement actually logs the data you think it logs, in the correct formats.

2023-05-09 13:22 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                            .contains(currentFrame.getState().name())) {
my suggestion: pull this condition out into a predicate with a name and then make the predicate _positive_, i.e., instead of `!this && !that` make it `this || that` and do the `!` in the if-statement when called.  IMO expressing complex conditions like this in a "positive" way is easier to understand.

2023-05-09 13:22 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                    && !tracingProperties.getContract().contains(recipientNum)) {
Same comment for this one.

2023-05-09 13:22 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +            log.debug(
Do you want to make this one of those logging things where you first test to see if level debug is enabled before you start formatting strings?

2023-05-09 13:22 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                    "MessageFrame {} has input data {}, call depth {}, remaining gas {}, sender address {}, recipient address {}, contract address {} and revert reason {}",
I don't know if this is the practice in the mirror node, but for a logging statement like this where multiple fields are logged I suggest using a more "standardized" format like "topic: k1=v1 k2=v2 k3=v3` that logging services have an easier time extracting data from.

2023-05-09 13:22 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +}
This new class designed for the purpose would be a good place to put those two predicates I suggested above.

2023-05-11 14:21 UTC, david-bakin-sl reviewed
Well.  I misled (*) you in a previous comment.  Sorry about that!

----
(*) Was flat out wrong.

2023-05-11 14:21 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +        return getStatus().isEmpty() || getStatus().contains(state);
Oh darn. oops! _now_ I get what you were talking about in slack.  The null check.  Yeah, you were right, this doesn't work as now written, sorry!  But it's good that it got pulled out as a one-line predicate - still makes it easier to read.  (And below too.)

2023-05-11 14:21 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                return;
IMO one thing language designers could learn from Perl - possibly the _only_ thing - is the suffix-conditional.  (Don't know what it is really called.)

`return if <some condition>;`

`log "this string" if <some condition>;`

Many times that would read more naturally.

2023-05-11 16:55 UTC, steven-sheehy requested changes

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +            final TracingProperties tracingProperties,
`MirrorOperationTracer` is a bean, so inject it directly and don't leak its dependencies. It's probably the only `HederaEvmOperationTracer` bean so you can also inject the higher level interface.

```suggestion
            final MirrorOperationTracer operationTracer,
```

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +        if (tracingProperties.isEnabled()) {
Fail fast to reduce cognitive complexity and nested conditionals.

```suggestion
        if (!tracingProperties.isEnabled()) {
            return;
        }
```

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +    boolean enabled = false;
Remove `@Getter` and `@Setter` everywhere and just use `@Data`.

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +            final var recipientNum = entityIdNumFromEvmAddress(recipientAddress);
Will all recipient addresses be the long zero form and are safe to convert to shard/realm/num? I would've guessed some would be the full random 20 byte evm address. If not, we should make the properties take in a validated collection of 20 byte string with optional 0x prefix.

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +    Set<Long> contract = new HashSet<>();
Unless we need to support EVM address (see other comment), we should change this to `Set<EntityId>` as is our standard in properties elsewhere.

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +    Set<String> status = new HashSet<>();
Both sets need to be marked non-null.
```suggestion
    @NotNull
    private Set<String> status = new HashSet<>();
```

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                            : new byte[0]);
Can it always be converted to string? I think we should convert any binary fields to hex instead

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                    "contractCall: messageFrame={} inputData={}, callDepth={}, remainingGas={}, senderAddress {}, recipientAddress={}, contractAddress={}, revertReason={}",
messageFrame is missing `,` and senderAddress is missing `=` like the others

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                    "contractCall: messageFrame={} inputData={}, callDepth={}, remainingGas={}, senderAddress {}, recipientAddress={}, contractAddress={}, revertReason={}",
Can omit `contractCall: `

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                    "contractCall: messageFrame={} inputData={}, callDepth={}, remainingGas={}, senderAddress {}, recipientAddress={}, contractAddress={}, revertReason={}",
We should have call index as well. Ideally we'd just have a `0.0.1.3` type call depth and index string at the beginning like hashscan.

2023-05-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                    "contractCall: messageFrame={} inputData={}, callDepth={}, remainingGas={}, senderAddress {}, recipientAddress={}, contractAddress={}, revertReason={}",
Omit `Address` everywhere since it's redundant.

2023-05-15 20:44 UTC, steven-sheehy commented
Please let us know when this ready for another round of reviews by marking it as ready.

2023-05-16 20:55 UTC, steven-sheehy requested changes

2023-05-16 20:55 UTC, steven-sheehy commented on docs/configuration.md
> +`hedera.mirror.web3.evm.tracing.status`                     |                                                    | A set with frame statuses to filter
```suggestion
`hedera.mirror.web3.evm.tracing.contract`                   | []                                                 | A set with contract addresses to filter. By default it is empty to indicate it will trace all contract addresses.
`hedera.mirror.web3.evm.tracing.status`                     | []                                                 | A set with frame statuses to filter. By default it is empty to indicate it will trace all frames regardless of status.
```

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +    private Set<Address> contract = new HashSet<>();
Have you tested this at runtime by populating the address in an `application.yml`? I don't think this will work without some custom converter. Instead, model as a String that supports and validates hex. Please test the below works as you would expect.

```suggestion
    private Set<@Hex(minLength = ADDRESS_LENGTH, maxLength = ADDRESS_LENGTH) String> contract = new HashSet<>();
```

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +public class TracingProperties {
Think we should not use a gerund form of the verb. Adjust other places as well.

```suggestion
@ConfigurationProperties(prefix = "hedera.mirror.web3.evm.trace")
public class TraceProperties {
```

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +    private Set<String> status = new HashSet<>();
Is there any reason to not use the Besu enum?

```suggestion
    private Set<State> status = new HashSet<>();
```

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +            return;
Need separate tests for all the return statements in this method.

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                : "0x";
I don't think this is necessary. Can just directly log `currentFrame.getInputData()` and it will either log null or implicitly call toString which calls toHexString.

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                        currentFrame.getRevertReason().orElse(Bytes.EMPTY).toArray(), StandardCharsets.UTF_16),
Is it more likely to be human readable ascii or unreadable binary? Should we just always use hex since it can sometimes be binary?

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +            final String childIndex = "0.0.1." + currentFrame.getMessageStackDepth() + " " + currentFrame.getType();
The index seems to always start with `0.0.1`, which doesn't really make sense. I was wanting a [hashscan](https://hashscan.io/testnet/transaction/1684266514.414639003) style 1_2_1 call depth plus index prefix that varies for every log written. Not sure if it's possible without tracking prior frames.

2023-05-16 20:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +                currentFrame.getMessageStackDepth(),
Call depth is duplicate in the prefix.

2023-05-17 13:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/TracingProperties.java
> +    private Set<Address> contract = new HashSet<>();
It is [valid](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#container-element-constraints) for use there. You need to add `ElementType.TYPE_USE` to the annotation.

2023-05-17 13:57 UTC, steven-sheehy requested changes

2023-05-17 13:57 UTC, steven-sheehy commented on docs/configuration.md
> +`hedera.mirror.web3.evm.tracing.enabled`                    | false                                              | Flag enabling tracer
These should be `trace`

2023-05-17 13:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracerTest.java
> +        given(traceProperties.contractFilterCheck(any())).willReturn(false);
Change TraceProperties to not be a mock to provide test coverage

2023-05-17 13:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracerTest.java
> +        mirrorOperationTracer = new MirrorOperationTracer(traceProperties, mirrorEvmContractAliases);
Move to a `@BeforeEach` or `@InjectMocks`.

2023-05-17 13:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracerTest.java
> +        final var topLevelMessageFrame = mock(MessageFrame.class);
Move to a `@Mock` or a `@BeforeEach`

2023-05-17 13:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracerTest.java
> +
Need tests for:

* Tracing not enabled.
* state property not empty and passes
* state property not empty and not passes
* contract property not empty and passes
* contract property not empty and not passes
* All checks pass but not frame suspended

Consider using parameterized tests for some of these.

2023-05-17 13:57 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/MirrorOperationTracer.java
> +        final var recipientNum = mirrorEvmContractAliases.resolveForEvm(recipientAddress);
Why do we need to resolve this address and can't use it directly?

2023-05-19 16:36 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-05-19 20:30 UTC, xin-hedera approved these changes
LGTM

2023-05-23 16:33 UTC, steven-sheehy approved these changes

2023-05-23 16:41 UTC, xin-hedera approved these changes

2023-05-23 16:41 UTC, merged