Add Runbook Restore Document
hashgraph/hedera-mirror-node pull request #5962
Opened 2023-05-05 18:24 UTC by edwin-greene

**Description**:
Add the runbook restore document.

**Related issue(s)**:

Fixes #4805 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-05-08 13:35 UTC, edwin-greene commented on docs/runbook/restore.md
> +5. In the Google Console, restore the database from the backup.
Not sure if there should be more detail for this step. There are command line commands to restore the database, but clicking through the Google Console worked as well.

2023-05-08 16:07 UTC, steven-sheehy requested changes

2023-05-08 16:07 UTC, steven-sheehy commented on docs/runbook/restore.md
> +7. Restart the Importer Pod(s) using the number of replicas from step 1.
We're missing a step to restart all pods to clear their cache. This should be done before restart importer and monitor since it would be inefficient to restart them after just starting them.

`kubectl delete pods $(kubectl get pod -o name)`

Once we run statefulsets like citus in the namespace, we should revisit this command and maybe add specific labels to pods we want to restart.

2023-05-08 16:07 UTC, steven-sheehy commented on docs/runbook/restore.md
> +5. In the Google Console, restore the database from the backup.
We should provide some guidance on which backup to choose as there can be multiple.

2023-05-09 14:10 UTC, xin-hedera commented on docs/runbook/restore.md
> +
Add a step before 10 which verifies that traffic is being routed to the cluster, can run rest queries a couple of times and check the query appears in the rest pod's log.

2023-05-10 19:36 UTC, edwin-greene commented on docs/runbook/restore.md
> +5. In the Google Console, restore the database from the backup.
Thanks I've added the images.

2023-05-10 19:36 UTC, edwin-greene commented on docs/runbook/restore.md
> +1. Determine the number of Importer replicas. This is number of replicas that will be restored in step 7.
I've removed it.

2023-05-10 19:37 UTC, edwin-greene commented on docs/runbook/restore.md
> +2. Shut down the Monitor.
Good idea, I have added that.

2023-05-10 19:37 UTC, edwin-greene commented on docs/runbook/restore.md
> +    1683300839955833003      --> Friday, May 5, 2023 15:33:59.955
Sounds good, I have substituted the rest api query in place of the db query.

2023-05-10 19:40 UTC, edwin-greene commented on docs/runbook/restore.md
> +7. Restart the Importer Pod(s) using the number of replicas from step 1.
I tried that command but got an error: 

```
kubectl delete pods $(kubectl get pod -o name)
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'
```

The command I ended up putting the document was able to delete all pods in the namespace: 
`kubectl delete --all pods`

2023-05-10 19:40 UTC, edwin-greene commented on docs/runbook/restore.md
> +5. In the Google Console, restore the database from the backup.
With the added images there is some more information about which backup to choose. I'm not sure if we need more details or if it will be something to query Ops about.

2023-05-10 19:42 UTC, edwin-greene commented on docs/runbook/restore.md
> +
I added this step, but I found that the REST query returned the new information from the DB. Are the results from the query itself sufficient, or should we also check the rest api log statements?

2023-05-10 19:43 UTC, edwin-greene commented on docs/runbook/restore.md
> +   ```
With testing I found that the blocks rest api was able to confirm that the database had been reverted, so it may be that that command could be used here as well.

2023-05-11 15:08 UTC, xin-hedera commented on docs/runbook/restore.md
> +
in a multi-cluster setup, we need to check the rest pod's log to confirm traffic is being routed correctly. you also need to run a the query a couple of times since it can be routed to the other cluster

2023-05-11 15:47 UTC, steven-sheehy requested changes

2023-05-11 15:47 UTC, steven-sheehy commented on docs/runbook/restore.md
> +    curl "https://<mirror-rest-ingress>/api/v1/blocks?limit=1" | json_pp | grep -E "name|number"
json_pp is not one of our standard tools. We should prefer jq which can also do it one command. I think just name is sufficient to check.

```suggestion
    curl -sL "https://<hostname>/api/v1/blocks?limit=1&order=desc" | jq -r '.blocks[0].name'
```

2023-05-11 15:47 UTC, steven-sheehy commented on docs/runbook/restore.md
> +   ```
Yes, use the REST API for both to simplify. Can even say re-run step 3 to verify recent blocks are showing up instead of repeating it.

2023-05-11 15:47 UTC, steven-sheehy commented on docs/runbook/restore.md
> +4. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
You need to test this scenario for a db with a replica. GCP does not allow restore to instances with a replica and you first have to delete the replica. Please add these steps since any scenario where we execute this runbook would be a production env with replicas. Show images for these steps.

2023-05-11 17:26 UTC, steven-sheehy commented on docs/runbook/restore.md
> +4. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
Don't forget re-adding the replica with the same config as previous and updating any app db config with the new IP

2023-05-11 17:29 UTC, edwin-greene commented on docs/runbook/restore.md
> +    curl "https://<mirror-rest-ingress>/api/v1/blocks?limit=1" | json_pp | grep -E "name|number"
Thanks I have changed it to use `jq`

2023-05-11 17:30 UTC, edwin-greene commented on docs/runbook/restore.md
> +
Thanks I have changed the last steps and added details about checking the rest pod logs.

2023-05-12 21:50 UTC, edwin-greene commented on docs/runbook/restore.md
> +4. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
I've updated the steps with info about the replicas, but I still need to research the part about updating any app db configs with a new IP.

2023-05-12 22:53 UTC, steven-sheehy requested changes

2023-05-12 22:53 UTC, steven-sheehy commented on docs/runbook/restore.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<img src="replicaConfig.png" width="100" height="150"/>](replicaConfig.png "Google Cloud Replica Config")
All the images are really small when rendered. Perhaps let them each fill up the space horizontally by just omitting width and height. If it is too big, then maybe just set a width that's close to the 120 char limit.

2023-05-12 22:53 UTC, steven-sheehy commented on docs/runbook/restore.md
> +6. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
The 6 shows as on the same line as the previous image.

2023-05-12 22:53 UTC, steven-sheehy commented on docs/runbook/restore.md
> +13. Get the names of the REST pods for use in step 14.
Omit this step and just use `kubectl logs -f --prefix -l app.kubernetes.io/name=rest` in the next step.

2023-05-12 22:53 UTC, steven-sheehy commented on docs/runbook/restore.md
> +   ```
This doesn't quite always work. The load balancer routes based upon region so if you're in the NA region and try to test this against the EU cluster you'll always be routed to NA. You can always just verify against a port-forwarded rest service.

2023-05-12 22:53 UTC, steven-sheehy commented on docs/runbook/restore.md
> +4. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
It might be a bit tricky to show since it's within a sealed secret encrypted file and flux is used to roll it out. Perhaps just state that if the IP changed to update any config using the old IP and leave the details out of scope.

2023-05-15 13:54 UTC, edwin-greene commented on docs/runbook/restore.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<img src="replicaConfig.png" width="100" height="150"/>](replicaConfig.png "Google Cloud Replica Config")
Sounds good I have removed the size limitations. The images seem to automatically shift to a new line depending on the size of the window.

2023-05-15 13:55 UTC, edwin-greene commented on docs/runbook/restore.md
> +6. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
I've added a space.

2023-05-15 13:55 UTC, edwin-greene commented on docs/runbook/restore.md
> +13. Get the names of the REST pods for use in step 14.
Thanks I have updated it with that kubectl command.

2023-05-15 13:56 UTC, edwin-greene commented on docs/runbook/restore.md
> +4. In the Google Console, restore the database from the backup. Restore to a backup that was created before the invalid data was persisted.
Sounds good I have added some details to note the IP address value and check if it has changed and then to update other configs.

2023-05-15 15:16 UTC, edwin-greene commented on docs/runbook/restore.md
> +   ```
Thanks I have updated the documentation with instructions to use the port forward.

2023-05-15 17:02 UTC, jnels124 approved these changes
LGTM

2023-05-15 18:54 UTC, steven-sheehy approved these changes
LGTM

2023-05-15 19:24 UTC, xin-hedera approved these changes
LGTM

2023-05-15 19:34 UTC, merged