HIP-584: eth estimate gas w/o precompiles tests
hashgraph/hedera-mirror-node pull request #5974
Opened 2023-05-09 07:41 UTC by yiliev0

**Description**:

The PR is about adding tests related to eth_estimateGas. [Here](https://www.notion.so/limechain/eth_estimateGas-Test-Plan-Specification-34475cb5aec740d7a9b1a974e15a9167) is the test plan.

**Related issue(s)**:

Fixes #5973

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-05-11 12:41 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static final int DEPLOY_CONTRACT_VIA_CREATE_OPCODE_ESTIMATED_GAS = 11111; //tbd
Can you leave more descriptive comment why this gas estimation is tbd.

2023-05-11 12:43 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        //TBD what to clean
Do we still need to have a cleanup method?

2023-05-11 12:46 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        deployedContract = createContract(compiledSolidityArtifact, 10000000);
@natanasow What is the final decision about the initial balance, do we need to keep it 10000000?

2023-05-11 13:17 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static final String MULTIPLY_SIMPLE_NUMBERS_SELECTOR = "0ec1551d";
I think we can extract the constants in something like DataProvider. Since the DataProvider is available only for TestNG, probably is a good idea to add an `Example` in the estimate.feature cucumber file as in the account.feature file:
    Examples:
       ```
     | selector | estimatedGas  |
            | "0ec1551d"      | "0x000000000000567d"    |
            | d737d0c7      | "0x00000000000056bc" |
```

2023-05-11 13:40 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    public static int extractAndConvertHex(String responseBody) {
This `extractAndConvertHex` and the following `generateRandomHex` methods are very useful. Can we extract them in an utils or helpers file so we can use them in other tests too?

2023-05-12 07:02 UTC, natanasow commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        deployedContract = createContract(compiledSolidityArtifact, 10000000);
The `EstimateGasContract.sol` doesn't have a payable constructor, so we can completely remove the initial balance parameter from the `createContract` method.

2023-05-12 10:56 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private ContractId verifyCreateContractNetworkResponse() {
Just following the same way it is used in ContractFeature, ERCContractFeature, PrecompileContractFeature.

2023-05-12 11:52 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static final int DEPLOY_CONTRACT_VIA_CREATE_OPCODE_ESTIMATED_GAS = 11111; //tbd
Added extra comment.

2023-05-12 11:52 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        //TBD what to clean
Removed, if we need it In the future, we will add it again.

2023-05-12 11:52 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        ContractCallResponse multiplySimpleNumbersResponse =
Implemented.

2023-05-12 11:53 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    public static int extractAndConvertHex(String responseBody) {
Moved the methods to util.Testutil.

2023-05-15 06:56 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    String newAccountPublicKey;
We can make this field private probably?

2023-05-15 07:01 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        validateGasEstimation(UPDATE_COUNTER_SELECTOR + "0000000000000000000000000000000000000000000000000000000000005642", UPDATE_COUNTER_ESTIMATED_GAS);
We can extract a field with this passed hex value and the name of the field might give us a clue about what is the hex encoded value.

2023-05-15 07:08 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        int estimatedGas = extractAndConvertHex(msgSignerResponse.toString());
Instead of `extractAndConvertHex` you can use directly this utility [method](https://github.com/hashgraph/hedera-mirror-node/blob/540857dc290867f76947cbbc517e00ca3e2f68d3/hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java#L33).

2023-05-17 07:22 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    public static boolean isWithinDeviation(int actualValue, int expectedValue, int deviationPercent) {
Done

2023-05-17 07:23 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        int estimatedGas = extractAndConvertHex(msgSignerResponse.toString());
Done

2023-05-19 11:19 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    public void set_deviations(int lower, int upper) {
We usually follow camel case namings:

set_deviations -> setDeviations

2023-05-19 11:21 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        //we will execute with 500, 750 and 1000, and it should return the same estimatedGas
I think currently the limit for nested calls is 1024, so we may add also tests covering 1024 and 1025 values, too see how the REST API behaves.

2023-05-22 07:04 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        //we will execute with 500, 750 and 1000, and it should return the same estimatedGas
Done

2023-05-30 20:21 UTC, steven-sheehy requested changes

2023-05-30 20:21 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/artifacts/@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol/IERC721Enumerable.dbg.json
Do we really need to commit these standard openzeppelin contracts to git? Can we get away with just committing our contracts and have these pulled as part of the build system?

2023-05-30 20:21 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static DeployedContract deployedContract;
Why does this need to be static?

2023-05-31 21:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    @And("lower deviation is {int} and upper deviation is {int}")
```suggestion
    @And("lower deviation is {int}% and upper deviation is {int}%")
```

2023-05-31 21:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        newAccountPublicKey = PrivateKey.generateECDSA().getPublicKey().toEvmAddress().toString();
should this be `newAccountEvmAddress` instead?

2023-05-31 21:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private FileId persistContractBytes(String contractContents) {
this function and `createContract` have been duplicated in all the contract related feature classes, should move them to a base class instead

2023-06-01 09:45 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/solidity/contracts/EstimateGasContract.sol
> +    function staticCallToContract() public view returns (address) {
We can extend `staticCallToContract`, `delegateCallToContract`, `callCodeToContract` to accept a parameter for the address to be called and then we can reuse these methods for the negative scenarios using invalid addresses.

2023-06-02 16:03 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        newAccountPublicKey = PrivateKey.generateECDSA().getPublicKey().toEvmAddress().toString();
I've changed it to newAccountEvmAddress

2023-06-02 16:07 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private FileId persistContractBytes(String contractContents) {
Hi @xin-hedera! I agree that we can move them in a base class! However, as it affects many unrelated files, I suggest we handle this as a separate task/issue to maintain the clarity and purpose of the current PR. I can create a new issue for this to ensure it's appropriately addressed and pick it up from there.

2023-06-02 16:28 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private FileId persistContractBytes(String contractContents) {
that's fair

2023-06-02 16:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static DeployedContract deployedContract;
I just followed the same logic it was used in the other classes. Removed the static as it's not necessary.

2023-06-02 16:43 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +
Implemented. Added builder to the ContractCallRequest and refactored the places where it is used - ContractFeature, ERCContractFeature, PrecompileFeature.

2023-06-02 16:43 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/TestUtil.java
> +    }
Removed generateRandomHex and replaced with RandomStringUtils.random(count, Hex.DIGITS_LOWER) whenever necessary.

2023-06-05 03:09 UTC, steven-sheehy requested changes

2023-06-05 03:09 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        validateGasEstimation(DELEGATE_CALL_TO_INVALID_CONTRACT_SELECTOR + to32BytesString(RandomStringUtils.random(40, HEX_DIGITS)),
Could move `to32BytesString(RandomStringUtils.random(40, HEX_DIGITS))` used everywhereh to a static constant since I don't think it has to be uniquely invalid, just globally invalid.

2023-06-05 03:09 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private Path estimateGasTestContract;
This will fail to be loaded when the acceptance tests are ran in a container. Need to use as a `Resource` and get it as an InputStream. See `ERCContractFeature`.

```suggestion
    private Resource estimateGasTestContract;
```

2023-06-05 03:09 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static final int ADDRESS_BALANCE_ACTUAL_GAS = 24030;
Ideally, we'd use a solidity to Java compiler to output an interface for these methods that we could call directly. Next best option would be to store these in an enum like the `ContractFunctions` enum in web3 module.

2023-06-05 08:09 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private static final int ADDRESS_BALANCE_ACTUAL_GAS = 24030;
Changed to enum similar to the ContractFunctions mentioned above.

2023-06-05 08:09 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        validateGasEstimation(DELEGATE_CALL_TO_INVALID_CONTRACT_SELECTOR + to32BytesString(RandomStringUtils.random(40, HEX_DIGITS)),
Done

2023-06-05 17:39 UTC, steven-sheehy requested changes
Need to merge from main as well

2023-06-05 17:39 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        ADDRESS_BALANCE("3ec4de35", 24030),
Add a `List<String> functionParameters` field to centralize all method specific data in one spot.

```suggestion
        ADDRESS_BALANCE("3ec4de35", List.of(RANDOM_ADDRESS), 24030),
```

2023-06-07 14:21 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +                        "10000000000"), ContractMethods.REENTRANCY_TRANSFER_ATTACK.getActualGas());
Hey @steven-sheehy! I like the idea, but I have encountered a problem where we need to initialize the enum along with dynamic parameters. You can check the example below:
```
    public void callCodeToContractEstimateCall() {
        var contractCallGetMockAddress = ContractCallRequest.builder()
                .data(ContractMethods.GET_MOCK_ADDRESS.getSelector())
                .to(contractSolidityAddress)
                .estimate(false)
                .build();
        var getMockAddressResponse = mirrorClient.contractsCall(contractCallGetMockAddress).getResultAsAddress();
        validateGasEstimation(ContractMethods.CALL_CODE_TO_CONTRACT.getSelector()
                + **to32BytesString(getMockAddressResponse)**
                + to32BytesStringRightPad(ContractMethods.GET_ADDRESS.getSelector()), ContractMethods.CALL_CODE_TO_CONTRACT.getActualGas());
    }
```
  In this example one of the parameters we are passing is coming out from an ETH_CALL request and thus making it hard to initiliaze it together with enum, as enum values are static by nature. For now I have kept the original form of the enum.
 Moreover, we might get rid of the mapping and the actualGas values once there is an `actualGasUsed` field implemented in the consensus node. Ideally, it will be changed once `actualGasUsed` field is added to the protobufs.

2023-06-07 14:21 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        DEPLOY_CONTRACT_VIA_CREATE_OPCODE("6e6662b9", 53477),
Sorted!

2023-06-07 14:21 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private String randomAddress;
Done!

2023-06-08 03:30 UTC, steven-sheehy approved these changes

2023-06-08 03:31 UTC, merged