Implement Account Accessor using Stacked State
hashgraph/hedera-mirror-node pull request #5975
Opened 2023-05-09 10:46 UTC by stoyan-lime

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-09 13:14 UTC, david-bakin-sl reviewed
I like this account "aggregator" thing - hides the complexity of the actual schema to provide a single unified "account".

(Still trying to understand how the underlying cache + database works - that's just me, I'm unfamiliar with it.)

(This review doesn't include tests. I'll come back later for those and add an official checkmark.)

2023-05-09 13:14 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +    List<TokenAllowance> findBySpender(long spender);
I'm not sure what's going on here but given the pattern in this file and the other repositories, why doesn't this method need a sql or cache annotation?

(I'm working on files going _upward_ again so this is the first one I saw.  I see it's peers are similar.  But don't know why.)

2023-05-09 13:14 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +import org.jetbrains.annotations.NotNull;
Not lombok's notnull?

2023-05-09 13:14 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +            return entityRepository.findByIdAndDeletedIsFalse(entityId);
This method name `findByIdAndDeletedIsFalse` is trying to tell you what it really does (which is nice!) but it returns an optional not a boolean ... so kind of misnamed?  Or is it just understood that Optional.empty means false?  (Which sounds reasonable.)

2023-05-09 13:23 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +            return entityRepository.findByIdAndDeletedIsFalse(entityId);
The method is a standard auto-generated query. It queries the database finding matches where ID matches the parameter, and where "deleted is false". So it returns the first object matching the query, which is optional and not a boolean.
You can read more here:
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods

2023-05-09 13:32 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +import org.jetbrains.annotations.NotNull;
Updated

2023-05-09 20:37 UTC, steven-sheehy requested changes

2023-05-09 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +    @Query("SELECT COUNT(ta) FROM TokenAccount ta WHERE ta.accountId=?1 AND balance > 0")
For efficiency, you can combine these two with a group by:

`select count(*), balance > 0 from TokenAccount where accountId = ?1 and associated is true group by balance > 0`

Note the mirror node SQL standard is to use lowercase and spaces around operators. `ta` alias is also not needed here.

2023-05-09 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/NftRepositoryTest.java
> +    void count() {
Should match repo method.
```suggestion
    void countByAccountId() {
```

2023-05-09 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAccountRepositoryTest.java
> +    void countByAccountIdAndAssocaition() {
```suggestion
    void countByAccountIdAndAssociatedIsTrue() {
```

2023-05-09 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAccountRepositoryTest.java
> +    void countByAccountIdAndBalance() {
```suggestion
    void countByAccountIdAndPositiveBalance() {
```

2023-05-09 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                        EntityNum.fromLong(nftAllowance.getTokenId()), EntityNum.fromLong(nftAllowance.getSpender())))
Use EntityId

2023-05-10 12:27 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                entity.getExpirationTimestamp(),
Added fallback.

2023-05-10 12:27 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                entity.getDeleted(),
Added fallback.

2023-05-10 12:27 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                idFromEntityId(entityId),
Updated.

2023-05-10 12:28 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                getOwnedNfts(entityId),
Updated.

2023-05-10 12:41 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +public class AccountDatabaseAccessor extends DatabaseAccessor<Address, Account> {
Updated.

2023-05-10 12:42 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        return cryptoAllowanceRepository.findBySpender(spenderId).stream()
Fixed.

2023-05-10 12:49 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                        EntityNum.fromLong(nftAllowance.getTokenId()), EntityNum.fromLong(nftAllowance.getSpender())))
Updated.

2023-05-10 12:49 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                        cryptoAllowance -> EntityNum.fromLong(cryptoAllowance.getOwner()),
Updated.

2023-05-10 13:39 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +    int countByAccountIdAndPositiveBalance(long accountId);
Updated.

2023-05-10 14:56 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +    long countByAccountId(EntityId accountId);
How important is it to check for the entity.deleted property?
To check for it we either have to define a relation between the Nft and Entity table
or create a native query, which is problematic as converters are used for account ids.

2023-05-10 15:25 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +    @Query("SELECT COUNT(ta) FROM TokenAccount ta WHERE ta.accountId=?1 AND balance > 0")
You should switch to native query and adjust table/columns appropriately

2023-05-10 15:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +    long countByAccountId(EntityId accountId);
Very important. Just use long parameters and define native query

2023-05-11 11:46 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +    long countByAccountId(EntityId accountId);
Updated.

2023-05-11 16:28 UTC, steven-sheehy requested changes

2023-05-11 17:17 UTC, steven-sheehy commented
2 code smells to address

2023-05-11 17:59 UTC, xin-hedera requested changes

2023-05-11 17:59 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        return DEFAULT_EXPIRY_TIMESTAMP;
the timestamps are in different resolution

- nanosecond: entity.createdTimestamp and entity.expirationTimestamp
- second: entity.autoRenewPeriod
- microsecond: DEFAULT_EXPIRY_TIMESTAMP

2023-05-12 09:32 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                Optional.ofNullable(entity.getAutoRenewPeriod()).orElse(Long.MAX_VALUE),
Updated.

2023-05-12 09:32 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                entity.getMaxAutomaticTokenAssociations(),
Updated.

2023-05-12 09:32 UTC, stoyan-lime commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAllowanceRepositoryTest.java
> +    void findBySpender() {
Updated.

2023-05-12 10:56 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +    @Query("SELECT COUNT(ta) FROM TokenAccount ta WHERE ta.accountId=?1 AND balance > 0")
Updated.

2023-05-12 13:09 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        return DEFAULT_EXPIRY_TIMESTAMP;
Updated.
For future reference where can I see the resolutions of different timestamps?

2023-05-12 15:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        return DEFAULT_EXPIRY_TIMESTAMP;
there's no document in code for these fields. You can check what values are saved to the fields in CryptoCreateTransactionHandler/CryptoUpdateTransactionHandler.

2023-05-12 16:01 UTC, steven-sheehy approved these changes
LGTM

2023-05-12 16:05 UTC, merged