Add support for evmaddress to balances endpoint
hashgraph/hedera-mirror-node pull request #5979
Opened 2023-05-09 19:35 UTC by edwin-greene

**Description**:
The balances endpoint now supports a single account.id value in the form of an evm address or an alias.

**Related issue(s)**:

Fixes #5863

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-05-09 19:43 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
>    utils.validateReq(req, acceptedBalancesParameters);
utils.validateReq will not allow an alias value for `account-id`, so rather than open up the validation on all endpoints to allow an alias, this switches the query parameter property name and then does validation for `ID_OR_ALIAS_OR_EVM_ADDRESS` and the `eq` operator. 

An alternative would be to change the endpoint to no longer support a query parameter named `account-id` and introduce a new query parameter, but this would be a breaking change to consumers of the balances api.

2023-05-09 20:47 UTC, Nana-EC reviewed
Nice change.
Left some suggestions and questions for consideratuion

2023-05-09 20:47 UTC, Nana-EC commented on hedera-mirror-rest/balances.js
> +  if (req.query[constants.filterKeys.ACCOUNT_ID] !== undefined) {
Q: I forget the logic but why do a remaping of the query object here vs consider the value as either format and decide based on validation?

2023-05-09 20:47 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      schema:
You could capture at least type and schema as a `AccountIdOrAliasOrEvmAddress` API object and reuse it in `accountIdOrAliasOrEvmAddressQueryParam` and `accountIdOrAliasOrEvmAddressPathParam`

You can refer to `EntityIdQuery` as an example

2023-05-09 20:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +        "evm_address": "ac384c53f03855fa1b3616052f8ba32c6c2a2fec",
Q: should these have `0x` prefixes. Not sure if that is removed for db performance

2023-05-09 20:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +        "/api/v1/balances?account.id=gte:ac384c53f03855fa1b3616052f8ba32c6c2a2fec",
For inputs you should expect `0x` prefixes on evm addresses

2023-05-09 20:47 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +        "/api/v1/balances?account.id=lt:ac384c53f03855fa1b3616052f8ba32c6c2a2fff",
Please add long zero examples for consideration here and below as users may input either a long zero or evm address alias format. Both are valid 20byte hex addresses in this scenario

2023-05-10 15:06 UTC, steven-sheehy requested changes

2023-05-10 15:06 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +              "message": "Invalid parameter: idOrAliasOrEvmAddress"
The parameter name must be the query parameter name the customer supplied so they can properly react to the bad input. It would be even better if it told you why it was invalid like unsupported lte operator for EVM address.

```suggestion
              "message": "Invalid parameter: account.id"
```

2023-05-10 15:06 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^(\d{1,10}\.){0,2}(\d{1,10}|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))$
I don't think we should support the weird and complicated `shard.realm.(alias|evmAddress)` format. Let's just support `alias` or `(0x)?evmAddress`.

2023-05-11 18:10 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
>    utils.validateReq(req, acceptedBalancesParameters);
Good idea. I ended up using `utils.validateReq` but passing in a custom validator.

2023-05-11 18:12 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +      schema:
Thanks I have updated the openapi spec, it now references a schema and reuses it for both of the account/alias/evm address objects.

2023-05-11 18:12 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +        "/api/v1/balances?account.id=gte:ac384c53f03855fa1b3616052f8ba32c6c2a2fec",
Thanks I have added `0x` to the tests.

2023-05-11 18:12 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +        "/api/v1/balances?account.id=lt:ac384c53f03855fa1b3616052f8ba32c6c2a2fff",
Good idea, I have added the long zero evm addresses to the test cases.

2023-05-11 18:13 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +              "message": "Invalid parameter: idOrAliasOrEvmAddress"
Thanks I have fixed this.

2023-05-11 18:13 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^(\d{1,10}\.){0,2}(\d{1,10}|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))$
Thanks I have updated the openapi spec to simplify the schema.

2023-05-11 19:08 UTC, xin-hedera requested changes

2023-05-11 20:09 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +      required: true
Good catch. I have removed it.

2023-05-11 20:09 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +};
Excellent thanks. I have made these simplifications.

2023-05-11 21:30 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +      }
we should do this check in `balanceFilterValidator` without the penalty of querying the db in `EntityService.getEncodedId`, can do it a follow-up ticket

2023-05-11 21:37 UTC, xin-hedera approved these changes
LGTM

2023-05-11 23:05 UTC, steven-sheehy requested changes

2023-05-11 23:05 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: "#/components/schemas/EvmAddress"
Revert this type and places the reference it. We can't use oneof this way for reuse as it causes problems with openapi code generation that I had to previously fix to duplicate patterns in places. Just duplicate the patterns so we don't cause regressions.

2023-05-11 23:05 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          value: 0.0.ac384c53f03855fa1b3616052f8ba32c6c2a2fec
Still examples with shard and realm for address and alias

2023-05-11 23:05 UTC, steven-sheehy commented on hedera-mirror-rest/balances.js
> +        ? [`${columnName} IN (?`.concat(', ?'.repeat(value.length - 1)).concat(')'), value]
In the ticket I state we should only support exactly one EVM address or alias.

2023-05-12 17:14 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: "#/components/schemas/EvmAddress"
Sounds good I have removed it.

2023-05-12 17:16 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +      }
I have updated the validation, it now has reduced the number of db queries.

2023-05-12 17:17 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +              "message": "Invalid operator. Evm address or alias only supports equals operator."
Sounds good I have added the details to the error messages that do not arise from the `utils.validateReq`, for those error messages it may be that a new issue could tackle refactoring to add details for other errors.

2023-05-12 17:20 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +        ? [`${columnName} IN (?`.concat(', ?'.repeat(value.length - 1)).concat(')'), value]
There is an error that will account for more than one evm address or alias; this line allows for multiple uses of the shard realm num account id.

2023-05-12 17:21 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^(\d{1,10}\.){0,2}(\d{1,10}|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))$
I understand now, support for them has been removed.

2023-05-12 17:56 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
> +            {
For performance, the account.id parameter is now validated upon parsing the account while these other parameters are validated prior to account parsing. Because of this the test for account id's validity has been removed from this test and a new test has been added for it on lines 86-101.

2023-05-12 18:28 UTC, steven-sheehy commented on hedera-mirror-rest/balances.js
> +        ? [`${columnName} IN (?`.concat(', ?'.repeat(value.length - 1)).concat(')'), value]
Got it. Thanks for clarifying.

2023-05-12 19:46 UTC, steven-sheehy approved these changes
LGTM

2023-05-12 19:47 UTC, xin-hedera approved these changes
LGTM

2023-05-12 22:05 UTC, merged