5751 citus volume compression
hashgraph/hedera-mirror-node pull request #5989
Opened 2023-05-12 14:24 UTC by jnels124

**Description**:
add support for zfs in gke
* update common chart to install openebs zfs driver
* add init containers as daemon set to install zfs utils and configure pool on nodes
* add document describing how to deploy citus with zfs using helm chart

**Related issue(s)**:

Fixes #5751 

**Notes for reviewer**:
There will be an additional ticket on tuning/automating the GKE upgrade process

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-12 17:20 UTC, jnels124 commented on docs/gke/zfs-on-gke.md
> +### GKE Cluster Upgrade
There will be another ticket to update this process to be less manual

2023-05-12 17:25 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +---
There is a separate daemon set for the coordinator and worker. This is done because they require different config. Should have iterated over a dictionary in config instead but this wasn't done initially. There is a follow up ticket to update automating node upgrades. Part of the suggestion of that ticket will be to add labels to the disk when it is created and that will require a move to a different config mechanism that will be suggested in that ticket

2023-05-12 17:35 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +              value: {{ .Values.zfs.worker.diskSize }}
The follow up ticket will indicate this being updated to create and bind a specific service account

2023-05-12 20:32 UTC, steven-sheehy requested changes

2023-05-12 20:32 UTC, steven-sheehy commented on docs/gke/zfs-on-gke.md
Prefer this in a `database/zfs.md` to group database related docs. We can also move `database.md` to `docs/README.md` and fix any references to it. Then add a link from the latter to the former.

2023-05-12 20:32 UTC, steven-sheehy commented on docs/gke/zfs-on-gke.md
> +| Citus Worker      | 8   | 32GB   | 1.25TB                           |
Remove since we document recommended Citus node pools elsewhere.

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
Prefer each yaml in a separate file. Can create a `zfs` sub folder to put them all in.

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +    if ! gcloud compute disks list --filter="name:$DISK_NAME" | grep "$DISK_NAME" > /dev/null; then
nit: Use `(( command ))` bash syntax everywhere instead of sh syntax.

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +      apt-get install -y zfsutils-linux
Shouldn't need to apt-get update twice in the same script. Can also probably combine the two apt-get install commands into one.

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +      volumes:
nit: Sort all yaml so it's consistent with the rest of the files in the charts.

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +        - image: ubuntu:18.04
```suggestion
        - image: ubuntu:22.04
```

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +          args: []
can omit

2023-05-12 20:32 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +              value: {{ .Values.zfs.primary.diskSize }}
If the only difference between the two daemonsets is how big a disk is created, we workaround that by creating one daemonset that:

* Has two DISK_SIZE_COORDINATOR and DISK_SIZE_WORKER variables
* Uses the downward API to inject the nodename
* Uses kubectl image to extract the node labels using the nodename

2023-05-12 20:32 UTC, steven-sheehy commented on docs/gke/zfs-on-gke.md
> +1. all the nodes must have zfs utils installed (handled by installing the common helm chart with zfs enabled)
nit: Casing of ZFS everywhere.
```suggestion
1. All the nodes must have ZFS utils installed (handled by installing the common helm chart with ZFS enabled)
```

2023-05-15 11:04 UTC, jnels124 commented on docs/gke/zfs-on-gke.md
> +  enabled: false
These were shown this way to show how to deploy only the zfs components. I will remove the extra config

2023-05-15 11:05 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +      apt-get install -y zfsutils-linux
This apt-get update is inside the chroot environment and is still required

2023-05-15 14:17 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +  parameters:
fixed

2023-05-15 14:17 UTC, jnels124 commented on charts/hedera-mirror-common/templates/storageclass.yaml
> +  compression: "{{ .Values.zfs.parameters.compression }}"
fixed

2023-05-15 14:17 UTC, jnels124 commented on charts/hedera-mirror-common/templates/storageclass.yaml
> +  name: openebs-zfspv
fixed

2023-05-15 14:17 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +  primary:
fixed

2023-05-15 14:18 UTC, jnels124 commented on docs/gke/zfs-on-gke.md
> +4. Update the openebs CRDs (You can skip this step if you plan to not use zstd compression)
fixed

2023-05-15 14:19 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +    if ! gcloud compute disks list --filter="name:$DISK_NAME" | grep "$DISK_NAME" > /dev/null; then
still looking at this a bit as initial attempt failed. Will try to get this in here or will update in the follow up ticket.

2023-05-15 14:19 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +        - image: ubuntu:18.04
done.

2023-05-15 14:19 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs-configmap-init.yaml
> +          args: []
removed

2023-05-15 14:20 UTC, jnels124 commented on docs/gke/zfs-on-gke.md
> +1. all the nodes must have zfs utils installed (handled by installing the common helm chart with zfs enabled)
done

2023-05-15 16:15 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +     tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
will make this easier to read... will wait for review first.

2023-05-15 19:59 UTC, steven-sheehy approved these changes
LGTM. Nice work!

2023-05-15 20:59 UTC, edwin-greene approved these changes
Looks good!

2023-05-15 21:02 UTC, xin-hedera approved these changes
LGTM

2023-05-15 21:15 UTC, merged