Fix missing transaction_index in contract result by hash response
hashgraph/hedera-mirror-node pull request #6007
Opened 2023-05-15 17:10 UTC by xin-hedera

**Description**:

This PR fixes the missing transaction index in contract response bug

- Persist default contract result with sensible value for certain failed ethereum transactions
- Add a db migration to back fill failed ethereum transaction contract results
- Remove the default contract result for ethereum transaction logic in REST API
- Return 404 and log error if no contract result found for an ethereum transaction

**Related issue(s)**:

Fixes #4893 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-05-15 20:40 UTC, steven-sheehy requested changes

2023-05-15 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    && transactionBody.hasEthereumTransaction()) {
Are we sure that contract call/create can't also be missing a contract result?

2023-05-15 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillFailedEthereumTransactionContractResultMigrationTest.java
> +    private final File sql;
Prefer Spring's `Resource` and treat it as an InputStream.
```suggestion
    private final Resource sql;
```

2023-05-15 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillFailedEthereumTransactionContractResultMigrationTest.java
> +    private static final byte[] EMPTY = new byte[] {};
Use `DomainUtils.EMPTY_BYTE_ARRAY`

2023-05-15 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    private static final byte[] EMPTY = new byte[0];
Use `DomainUtils.EMPTY_BYTE_ARRAY`

2023-05-15 20:54 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.79.1__backfill_ethereum_transaction_contract_result.sql
> +where cr.consensus_timestamp is null and t.result not in (11, 22, 104, 220, 312);
22, 104, 220 are the three response codes we check in RecordItem.checkSuccess

2023-05-16 16:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    && transactionBody.hasEthereumTransaction()) {
In `ContractResultServiceImpl`, a minimal `ContractResult` is created for contract call / create without contract result in transaction record.

there are 9 such contract call / create TXs without contract result in db for mainnet, that's before we had the above minimal `ContractResult` logic in place

2023-05-16 20:17 UTC, steven-sheehy approved these changes

2023-05-16 20:37 UTC, edwin-greene approved these changes
Looks good to me.

2023-05-16 21:31 UTC, merged