HIP-584: Create Unique Token and Token Relationship Database Accessors
hashgraph/hedera-mirror-node pull request #6020
Opened 2023-05-17 12:18 UTC by stoyan-lime

**Description**:
Create new accessors, that given details, aggregates data from relevant repositories and returns a UniqueToken and TokenRelationship.

**Related issue(s)**:

Fixes #6014

2023-05-17 15:11 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2023-05-17 16:29 UTC, david-bakin-sl requested changes
IMO the field/argumenet ordering to `TokenRelationshipKey` needs to be swapped, thus "request changes".  Otherwise, just comments and requests for information as usual.

2023-05-17 16:29 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/model/TokenRelationshipKey.java
> +public record TokenRelationshipKey(Address accountAddress, Address tokenAddress) {}
Note that in `com.hedera.services.store.models.TokenRelationship` the constructor takes `accountAddress` and `tokenAddress` in the _other order_ - given the _types_ are identical the compiler & IDE can't warn you if you get this wrong - suggest switching the order to be consistent!!

And `com.hedera.mirror.web3.evm.store.accessor.TokenRelationshipDatabaseAccessor` right here in this same PR is in the other order too.  Seems that "token addr, account addr" is the expected order.

2023-05-17 16:29 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                .flatMap(account -> findToken(key.tokenAddress()).flatMap(token -> findTokenAccount(token, account)
I almost think the expression `findToken(key.tokenAddress()).flatMap(token -> findTokenAccount(token, account)` deserves to be pulled out into its own named method.  I know it's only calling two _other_ methods defined _right here_ a few lines down, but unfortunately the syntax of using `Optional` is kind of obscuring it.  (IMO.)

2023-05-17 16:29 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                TokenFreezeStatusEnum.FROZEN.equals(tokenAccount.getFreezeStatus()),
I've asked this before in this codebase and gotten no answer:  Why do we use `equals` comparison instead of the easier-to-read `==` when dealing with enums?

2023-05-17 16:29 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                account.getId().num()));
This is a lot of work.  Why isn't this either a) encapsulated in a constructor for `AbstractTokenAccount.Id` or b) some utility class (the new `AccessorUtils` for example?) in methods like `toEntityId(Token)` and `toEntityId(Account)` that hide this grody stuff?

2023-05-18 17:32 UTC, steven-sheehy requested changes

2023-05-18 17:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +        }
It's a primary key, so it can never be null.

2023-05-18 17:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
You can omit this onConstructor hack outside of tests. Spring will by default autowire it if only one constructor. Same comment elsewhere in main code.

```suggestion
@RequiredArgsConstructor
```

2023-05-18 17:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                TokenFreezeStatusEnum.FROZEN.equals(tokenAccount.getFreezeStatus()),
Mirror node standard is generally to not use equals for enums, but it's not strictly enforced.

2023-05-18 17:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                token.getId().shard(), token.getId().realm(), token.getId().num()));
Don't use `EntityIdEndec` directly. Always prefer `EntityId.of()`.

2023-05-18 17:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                account.getId().num()));
I agree. Create some new util in `EntityIdUtils` to convert to/from services `Id` class to mirror `EntityId` class.

2023-05-19 10:52 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/model/TokenRelationshipKey.java
> +public record TokenRelationshipKey(Address accountAddress, Address tokenAddress) {}
Fixed.

2023-05-19 10:56 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                TokenFreezeStatusEnum.FROZEN.equals(tokenAccount.getFreezeStatus()),
Updated.

2023-05-19 11:17 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                account.getId().num()));
Done.

2023-05-19 11:17 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                token.getId().shard(), token.getId().realm(), token.getId().num()));
Done.

2023-05-19 11:17 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +        }
Updated.

2023-05-19 11:25 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                .flatMap(account -> findToken(key.tokenAddress()).flatMap(token -> findTokenAccount(token, account)
Adding a method we would lose the reference to "token", which we use in the following map method.

2023-05-21 00:17 UTC, steven-sheehy requested changes

2023-05-21 00:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +        return nftRepository.findById(nftId).map(this::mapNftToUniqueToken);
Should this only return non-deleted NFTs? If so, need to add a new repository method that joins on token.

2023-05-21 00:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +    }
Use `EntityIdUtils.entityIdFromId()` directly in `mapNftToUniqueToken`

2023-05-21 00:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    }
Might need to check for null. Also you can omit the `EntityType` parameter if you like to simplify it. It's not really used. Can just put UNKNOWN internally.
```suggestion
    public static EntityId entityIdFromId(Id id) {
        if (id == null) {
            return null;
        }
        return new EntityId(id.shard(), id.realm(), id.num(), EntityType.UNKNOWN);
    }
```

2023-05-21 00:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessorTest.java
> +        nft.setMetadata(metadata);
Use `DomainBuilder.nft().get()` and remove hardcoded values.

2023-05-22 15:42 UTC, xin-hedera requested changes

2023-05-22 22:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +import javax.inject.Named;
Need to merge main and switch javax to jakarta

2023-05-23 11:40 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +    }
This is the other way around.

2023-05-23 11:47 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +    }
Extracted the method to the util class

2023-05-23 11:52 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    }
Updated.

2023-05-23 12:21 UTC, stoyan-lime commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessorTest.java
> +        nft.setMetadata(metadata);
Updated.

2023-05-23 12:23 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +import javax.inject.Named;
Updated.

2023-05-23 13:05 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +        return nftRepository.findById(nftId).map(this::mapNftToUniqueToken);
Updated.

2023-05-23 16:09 UTC, xin-hedera approved these changes

2023-05-24 03:56 UTC, steven-sheehy requested changes

2023-05-24 03:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "join Entity e on e.id = n.token_id "
It's possible for partial mirror nodes that the NFT exists but the entity does not. We should use a left join to cover that scenario and coalesce e.deleted. Needs a test for that.

2023-05-25 16:59 UTC, steven-sheehy approved these changes
LGTM

2023-05-25 18:14 UTC, xin-hedera approved these changes
LGTM

2023-05-26 16:12 UTC, david-bakin-sl approved these changes
LGTM

2023-05-26 16:16 UTC, merged