HIP-584: Add Custom Fees to Token
hashgraph/hedera-mirror-node pull request #6021
Opened 2023-05-17 15:04 UTC by stoyan-lime

**Description**:
When building tokens in TokenDatabaseAccessor, add custom fees as well.

**Related issue(s)**:

Fixes #5977 
Contains not merged changes #6006

2023-05-17 16:12 UTC, david-bakin-sl requested changes
I think something's really wrong in `Token` w.r.t. the factories.  Marking `request changes` to ensure that either it gets fixed or the javadoc is updated to explain about the "current token" (`this`) vs `oldToken`.

2023-05-17 16:12 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                customFees);
I don't get these methods.  They aren't `static` even though they're factories.  So they have access to both `oldToken` and the _current token_.  So why for example, in this method, `totalSupply` and now `customFees` come from the _current_ token, and everything else comes from `oldToken` (and there's nothing in the javadoc to explain this)?????? 

Note that in `createNewTokenWithNewLastUsedSerialNumber` - also not `static` - only the new `customFees` comes from the _current_ token.  All else including `totalSupply` comes from `oldToken`.

I bet these are all supposed to be `static` factories that take a prototype and modify one or two fields. (And if they were: These errors - if they are errors - would be caught.)

2023-05-17 16:12 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +                .collect(Collectors.toList());
`.collect(Collectors.toList())` -> `toList()`

2023-05-17 17:14 UTC, xin-hedera requested changes

2023-05-17 17:14 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +    private CustomFee mapCustomFee(com.hedera.mirror.common.domain.transaction.CustomFee customFee) {
same code also in `TokenAccessorImpl.getCustomFees`

2023-05-18 06:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                customFees);
We won't to keep this code base similar to that in services but also achieve immutability - that's why we use several constructors with different arguments. However, in all of the cases I think we should load the `customFees` from the `oldToken`, indeed.

2023-05-18 13:25 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                customFees);
Similar is fine to since they start as copies and you'd like to be able to refer to the originals over in services as they change - but you can _add_ without trouble.  E.g., on top of the existing constructors or methods add _new_ ones that use the old, and then just consistently use the _new_ ones.  To provide better abstraction, better readability, etc.  It would still be clear when doing diffs what's going on, and new mirror node code built on the new stuff would be easier to understand.  (Note: I'm not suggesting wrapper classes - just putting a new version of a constructor/method next to the old one in the same class. With, of course, a comment explaining what's going on.)

2023-05-19 11:42 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +    private CustomFee mapCustomFee(com.hedera.mirror.common.domain.transaction.CustomFee customFee) {
Removed duplication.

2023-05-21 22:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +    public Address evmAddressFromId(EntityId entityId) {
Duplicates logic in TokenAccessorImpl and needs a test.

2023-05-25 16:50 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-05-25 16:53 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-05-26 15:23 UTC, david-bakin-sl approved these changes
LGTM

2023-05-26 15:40 UTC, merged