HIP-584: Adapt MirrorHTSPrecompiledContract to accept precompile calls
hashgraph/hedera-mirror-node pull request #6022
Opened 2023-05-17 15:38 UTC by IvanKavaldzhiev

**Description**:

This PR does the following:

- Allow `MirrorHTSPrecompiledContract` to accept precompile calls
- Throw `UnsupportedOperationException` when we try to access a precompile via non-static frame. This is a temporary measure, until we implement a given precompile and add a support for it. We will add precompile support one by one.
- Allows `eth_call` to invoke a dynamic function (non-view) which makes a read only precompile call. These calls would be redirected to the `ViewExecutor` and `RedirectViewExecutor` components and behave the same way like calling these precompiles via a view function. Currently this behaviour was blocked by a previous [PR](https://github.com/hashgraph/hedera-mirror-node/pull/5941). Note: if `eth_call` invokes a dynamic function which makes a call to a modification precompile - `UnsupportedOperationException` would be thrown

Most of the logic is copied from services but obsolete logic was removed to keep the class simpler.

**Related issue(s)**: 

Fixes #6005 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-19 05:41 UTC, steven-sheehy requested changes

2023-05-19 05:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contracts/precompile/MirrorHTSPrecompiledContract.java
> +                final var nestedFunctionSelector = target.descriptor();
I hope we're not planning on implementing all of these inline in this giant switch. Instead, we should have some precompile interface that auto-register themselves via some factory.

```java
public interface Precompile {
    Foo invoke(byte[] input);
    PrecompileName getName();
}

public enum PrecompileName {
...
}

@Named
public class PrecompileFactory {

    private final Map<PrecompileName, Precompile> precompiles;

    public PrecompileFactory(Collection<Precompile> precompiles) {
        this.precompiles = precompiles.stream().collect(toMap(Precompile::getName, Function.identity());
    }

    public Precompile lookup(PrecompileName name) {
       return precompiles.getOrDefault(name, UNSUPPORTED);
    }
}

2023-05-19 06:59 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +public class EntityDatabaseAccessor extends DatabaseAccessor<Object, Entity> {
We plan to use 4 type of models inside the state. Those are:

- Token
- Account
- UniqueToken
- TokenRelationship

For these models we plan to use the following keys in the same order:

- Address
- Address
- Address, Long (for the serial number)
- Address, Address

So, we have 3 different types of keys that we plan to use inside the state, but the state is designed around a single key type. In order to mitigate this issue, we decided to use Object ignoring the type safety. Another way would be to try to remove and decouple the whole state from the generic key type, but this would be more time-consuming.

2023-05-19 07:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contracts/precompile/AbiConstants.java
> +public class AbiConstants {
It contains constants, that are not present in the AbiConstants inside `hedera-evm`. There is another AbiConstants, which is in services repo (outside `hedera-evm`) with all of the rest constants. This class here, copies the values from it. I will move the fields in `com.hedera.services`.

2023-05-19 16:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contracts/precompile/MirrorHTSPrecompiledContract.java
> +                final var nestedFunctionSelector = target.descriptor();
Since this is new code, I don't think we should write it all the wrong way to then just refactor it right after. That's wasted effort that in particular causes a lot of headache in tests. 

The specifics aren't as important, my main point is that precompiles should not be implemented inline in this class and moved to some separate class that can be tested in isolation. Any precompiles that aren't supported don't need to be explicitly listed and can just be a default statement of the switch that throws not supported exception.

2023-05-22 06:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/exception/ResourceLimitException.java
> +public class ResourceLimitException extends InvalidTransactionException {
Done

2023-05-22 22:24 UTC, steven-sheehy requested changes

2023-05-22 22:24 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long htsDefaultGasCost = 10000;
Need to add to `docs/configuration.md`. Please also sort field inline.

2023-05-22 22:24 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileFactory.java
> +import javax.inject.Named;
Need to switch javax to jakarta everywhere after Spring Boot 3 PR.
```suggestion
import jakarta.inject.Named;
```

2023-05-22 22:24 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +public class EntityDatabaseAccessor extends DatabaseAccessor<Object, Entity> {
I'd like @david-bakin-sl to weigh in here as he designed it. Aren't the database accessors almost entirely used internally within the stacked state classes? I don't see where in the diff that they would be used directly and would have difficulty with using different key types. The only place is where you let Spring collection them into a list but using a wildcard for the generic works there.

2023-05-23 07:04 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileFactory.java
> +import javax.inject.Named;
@steven-sheehy Unfortunately, for the moment, the switch can't happen everywhere, since the `hedera-evm` library relies on the `javax.inject` package and on `mirror-node` side we initialize objects from the library using `javax.inject` arguments in their constructor, so if we switch mirror-node's usage to `jakarta` on these files, it's a breaking change.

I'm not sure what the consequences of this mix between javax.inject and jakarta might be.

2023-05-23 13:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +public class EntityDatabaseAccessor extends DatabaseAccessor<Object, Entity> {
The difficulty of using different key types comes with the initialization of `StackedStateFrames<K>` which is bound to a single K type. When we pass the list of DbAccessors, they should have the same key type, so that they follow this rule.

2023-05-23 16:02 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileFactory.java
> +import javax.inject.Named;
It's fine to have both javax and jakarta in web3 at the same time as long as Spring only loads beans via jakarta. You can keep hedera-evm with javax since we don't use component scanning to load any beans within evm library. It's okay to keep `EvmOperationConstructionUtil` returning `javax.inject.Provider`. But every Spring bean we create inside web3 module should be jakarta.

2023-05-23 16:03 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileFactory.java
> +import javax.inject.Named;
It's working fine now on main with mixing javax and jakarta. I'm only asking that within your diff to change any places from `javax` to `jakarta`.

2023-05-23 17:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long htsDefaultGasCost = 10000;
Done

2023-05-24 18:46 UTC, david-bakin-sl requested changes
Many of these comments are style comments - don't impact acceptance.  But there are some questions that need addressing - thus "request changes".

1. No stacked state `pop` call found.
2. The type `extends` in `AbstractEvmStackedLedgerUpdater`
3. Question about `unqualifiedDelegateDetected` matching the services repo
4. Catching `Exception` in several places where it appears overly broad.
5. No non-mock implementations of `Precompile`, is that ok at this point?

I'd really like to see the documentation updated as I suggest below, though if not part of this PR I would expect it to come quickly.

Also I haven't looked at the tests at all yet.

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        return Pair.of(gasRequirement, result.getOutput());
Things would be clearer IMO if `gasRequirement` wasn't a field but was just passed around.  For example `computePrecompile` could just return this `Pair`.  For example, right now `prepareComputation` sets the field to `0`.  Why?  `computePrecompile` sets it to `defaultGas` before doing real work.  But it might fail earlier (L121) so it must be `0` to be valid globally.  But if L121 just returned `Pair.of(0L, ...)` that would be fine.  Etc.

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        // Temporary workaround allowing eth_call to execute precompile methods in a dynamic context (non pure/view).
IMO this would be a valid place for "TODO" regardless of Sonar.

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            frame.setExceptionalHaltReason(Optional.of(ExceptionalHaltReason.PRECOMPILE_ERROR));
Besu's `ExceptionalHaltReason` is extensible.  The services repo does it with `HederaExceptionalHaltReason`.  And they really should have added a new exceptional halt reason for this "unqualified delegate detected" error over there.  (I'll file an [issue](https://github.com/hashgraph/hedera-services/issues/6757).)

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            final var haltReason = HederaExceptionalHaltReason.ERROR_DECODING_PRECOMPILE_INPUT;
Yep, and right here we see a proper use of `HederaExceptionalHaltReason`.

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        }
Can't this be merged with L117 above?  Maybe if `prepareComputation` or even `decodeInput` just threw a `InvalidTransactionException` (or something similar) in the case of `transactionBody == null`

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        gasRequirement = precompile.getGasRequirement(now);
Why is `gasRequirement` set at L124?

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +                ? PrecompiledContract.PrecompileContractResult.halt(null, Optional.of(ExceptionalHaltReason.NONE))
Here, what does it mean (to the user) that the result will have `MessageFrame.State.EXCEPTIONAL_HALT` with reason `ExceptionalHaltReason.NONE`?

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        return isDelegateCall(frames.next());
This no longer matches `unqualifiedDelegateDetected` in the services repo - [see here](https://github.com/hashgraph/hedera-services/blob/dad10e18e8bb0305ac99a9d9862407da505fa43c/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java#LL261C27-L261C27) - is this intentional, and if so, why don't we care about the `isToken` qualification at least?  And maybe the `permittedDelegateCallers` condition, do we have to replicate that for the mirror node?

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            stackedStateFrames.top().commit();
woohoo!  the `commit` I've been waiting to see!

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            log.warn("Internal precompile failure", e);
Do the state things need to be set in this case, as at L178-179 above?

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        stackedStateFrames.push();
And here's the `push`, woohoo again! But I don't see any `pop` around - there's gotta be one somewhere ....!!??

(No `resetToBase` either but maybe that only comes with `eth_estimateGas`)

2023-05-24 18:46 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +                ? PrecompiledContract.PrecompileContractResult.halt(null, Optional.of(ExceptionalHaltReason.NONE))
(same question as above w.r.t. no result case ... probably same answer ...)

2023-05-24 20:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        stackedStateFrames.push();
Actually, the main logic regarding push/pop operations with the stack should happen in the Updater components, since their tied to the specific EVM frames. We have a separate [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6066/files) for this logic.

I even think the `push()` in `MirrorHTSPrecompiledContract` is obsolete, since it will cause adding an extra `RWCachingStateFrame` that is not needed and would break the commit logic. The `push()` should happen in the `Updaters` and they should prepare the StackedStateFrames in advance, before entering the precompile execution. We should accept that the `StackedUpdater` and the `StackedStateFrames` inside, that are received in the `MirrorHTSPrecompiledContract` are ready to be used and only commit() should happen. When the `StackedUpdater` commits afterwards, it would pop the stacked frame that was used for the given precompile execution. I assume this is the correct logic 🤔

2023-05-24 20:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        return isDelegateCall(frames.next());
The `isToken` qualification seems missed, indeed. Good catch!

I was wondering `permittedDelegateCallers` and I'm not sure mirror-node should keep the same white list of callers, but instead permit more loosely the execution of delegate precompiles. In the worst case, a caller which is not whitelisted would receive an estimate gas value, but afterwards the consensus node transaction would fail, since they would be blocked to execute a delegate call. But this might happen in a variety of other cases like intermediate change of state between the two calls (estimateGas to Archive Node and then EthereumTransaction to Consensus Node).

2023-05-24 20:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            log.warn("Internal precompile failure", e);
I don't think so. Here we finish the execution of the precompile with a failing result, which is different from reverting the frame. We would keep this failure result in the EVM and use it for consequent nested calls.

2023-05-24 20:44 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +        final var stackedStateFrames = new StackedStateFrames<>(databaseAccessors);
I aligned the signatures to be the same.

2023-05-24 20:45 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
>      private final MirrorNodeEvmProperties evmProperties;
Done

2023-05-25 09:44 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        stackedStateFrames.push();
I removed this push()

2023-05-25 09:45 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        return isDelegateCall(frames.next());
Added missing logic for isToken

2023-05-25 12:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/exception/ResourceLimitException.java
> +public class ResourceLimitException extends InvalidTransactionException {
It would be thrown in the future when we implement the Logic types. It's not needed currently. I decided to add it now, so that we don't forget it in the future.

2023-05-25 12:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java
> +    Set<Integer> getFunctionSelectors();
Next sprint.

2023-05-25 17:37 UTC, steven-sheehy requested changes

2023-05-25 17:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    @NotNull
nit: Not needed since it's a primitive.

2023-05-25 17:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    Instant.now(),
Should adjust the field to use `MirrorEvmTxProcessor mirrorEvmTxProcessor` now that the interfaces are aligned.

2023-05-25 17:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            }
There's a lot of complicated logic in this class copied from services that is sure to be hard to keep in sync. Is the plan in the future after modularization to push this logic back into the hedera-evm library? If so, let's add a class comment noting the source of this logic and future direction.

2023-05-25 17:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +    private Address senderAddress;
Please check the code smells

2023-05-25 19:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    Instant.now(),
We can't directly call `MirrorEvmTxProcessor`, since it's constructed in the Facade which hides this logic.

2023-05-25 19:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +    private Address senderAddress;
Done

2023-05-25 19:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            }
I believe this logic might be pushed back in `smart-contract-service`, but there may still be the need of this class, serving as an adapter. I'm not sure how the design would evolve.

2023-05-25 19:58 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileFactory.java
> +    public PrecompileFactory(final Set<Precompile> precompiles) {
Renamed

2023-05-25 19:59 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileFactory.java
> +    public Precompile lookup(int functionSelector) {
Refactored

2023-05-31 03:42 UTC, steven-sheehy requested changes

2023-05-31 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/EvmOperationConstructionUtil.java
> +        final var precompileFactory = new PrecompileMapper(new HashSet<>(), getPrecompileFunctionSelectors());
PrecompileMapper is a singleton Spring bean yet here you're instantiating it. We should keep as a bean.

2023-05-31 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/EvmOperationConstructionUtil.java
> +    public static Set<Integer> getPrecompileFunctionSelectors() {
Hopefully this set is just temporary until there's implementations for each of these precompiles? Either way, I think this mapping belongs inside `PrecompileMapper` and that will help with its instantiation by Spring.

2023-05-31 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileMapperTest.java
> +    void nonExistingAbiReturnsEmpty() {
Needs a test for found and for unsupported

2023-05-31 03:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContractTest.java
> +    private Iterator<MessageFrame> messageFrameIterator;
I don't think we should mock simple objects like collections, iterators and MirrorNodeEvmProperties

2023-05-31 21:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContractTest.java
> +    private Iterator<MessageFrame> messageFrameIterator;
Removed unnecessary mocks

2023-05-31 21:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/precompile/PrecompileMapperTest.java
> +    void nonExistingAbiReturnsEmpty() {
Done

2023-05-31 21:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/EvmOperationConstructionUtil.java
> +    public static Set<Integer> getPrecompileFunctionSelectors() {
Yes, this is a temporary solution. I moved the Set to PrecompileMapper.

2023-05-31 21:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/EvmOperationConstructionUtil.java
> +        final var precompileFactory = new PrecompileMapper(new HashSet<>(), getPrecompileFunctionSelectors());
Done

2023-05-31 21:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long htsDefaultGasCost = 10000;
Done, vim helped to prevent showing extra whitespaces as changes.

2023-05-31 21:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/EvmOperationConstructionUtil.java
> +        final var mirrorNodeEvmProperties = new MirrorNodeEvmProperties();
Done

2023-06-01 14:14 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/EvmOperationConstructionUtil.java
> +    public static Map<String, Provider<MessageCallProcessor>> mcps(
We could refactor them in a future PR

2023-06-01 14:17 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +        var addressBytes = ((Address) address).toArrayUnsafe();
Currently the type is reverted back to Address

2023-06-01 14:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        } catch (final ResourceLimitException e) {
I removed ResourceLimitException

2023-06-01 14:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        // Temporary workaround allowing eth_call to execute precompile methods in a dynamic context (non pure/view).
Added TODO

2023-06-01 14:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +        }
I merged the statements

2023-06-01 14:46 UTC, steven-sheehy approved these changes
LGTM

2023-06-02 11:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAllowanceDatabaseAccessor.java
> +    public @NonNull Optional<TokenAllowance> get(@NonNull Object key) {
Changed to `AbstractTokenAllowance.Id`.

2023-06-02 11:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAccountDatabaseAccessor.java
> +    public @NonNull Optional<TokenAccount> get(@NonNull Object key) {
Changed.

2023-06-02 11:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (!addressOrAlias.equals(tokenAccessor.canonicalAddress(addressOrAlias))) {
I updated the javadoc.

2023-06-02 11:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
> +/*
I added a comment, but we usually copy corresponding services resources in the same package names inside web3 under `com.hedera.services`, so that we know where to find their original sources.

2023-06-02 11:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +    void decodeInput(final Bytes input, final UnaryOperator<byte[]> aliasResolver) {
I simplified the class logic and removed `decodeInput`

2023-06-02 11:54 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +            transactionBody = null;
Removed the Exception handler since there is no use of it currently. We might add a suitable exception handler if we add specific logic.

2023-06-02 12:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +                ? PrecompiledContract.PrecompileContractResult.halt(null, Optional.of(ExceptionalHaltReason.NONE))
I'm not sure. Probably this is a default value. It very unlikely to get `null result` from a precompile execution. If we have an error, we would set the corresponding failure result. The only way, IMO, to get a `null result` is to have `null` returned from the `getSuccessResultFor` precompile method, which means something suspicious happened and we haven't thrown an error so we'd better halt the frame.

2023-06-05 02:49 UTC, steven-sheehy commented
Need to merge main and fix code smells.

2023-06-05 13:33 UTC, IvanKavaldzhiev commented
@steven-sheehy I merged the conflicts. The code smells are intentional since some temporary changes were marked with TODO, as suggested by David.

2023-06-05 14:58 UTC, steven-sheehy commented
DCO problem

2023-06-06 14:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/precompile/MirrorHTSPrecompiledContract.java
> +    private static final Bytes STATIC_CALL_REVERT_REASON = Bytes.of("HTS precompiles are not static".getBytes());
ok, though I thought we were moving to the new terms

2023-06-06 15:09 UTC, david-bakin-sl approved these changes
LMGTM (looks _mostly_ good to me) - for outstanding issues to be addressed (IMO) I'll list them separately and we'll work on them shortly

2023-06-06 15:11 UTC, steven-sheehy approved these changes
LGTM. Please address the comments in a follow up

2023-06-06 15:12 UTC, merged