HIP-584: Refactor accessors to use StackedStateFrames
hashgraph/hedera-mirror-node pull request #6032
Opened 2023-05-19 13:06 UTC by 0xivanov

**Description**:

We need to modify TokenAccessorImpl, AccountAccessorImpl and MirrorEntityAccess classes to use StackedStateFrames instead of repositories, so that we read most up-to-date information from the state.

**Related issue(s)**:

Fixes #5959

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-05 03:18 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/AccountAccessorImpl.java
> +    }
This class is a singleton bean shared by all requests. We cannot set stateful objects on it and need to keep it stateless.

2023-06-05 03:18 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +    }
Remove stateful setter on singleton bean.

2023-06-05 03:25 UTC, steven-sheehy requested changes

2023-06-05 03:25 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    }
Remove

2023-06-05 03:25 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +            return entityRepository.findByIdAndDeletedIsFalse(((EntityId) key).getId());
```suggestion
        if (key instanceof EntityId entityId) {
            return entityRepository.findByIdAndDeletedIsFalse(entityId.getId());
```

2023-06-05 03:25 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +                final TokenAccessorImpl tokenAccessor,
Shouldn't leak implementation class. Especially since we should not be setting state on stateless beans.

2023-06-05 10:31 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/AccountAccessorImpl.java
> +    }
I agree that we should not have a bean and stateful object inside. We need to create new `StackedStateFrames` for every transaction and assign it to the accessors and the updaters. One option is to convert the accessors to not be singleton beans and create them manually in every `execute` method. Another option is to make the `StackedStateFrames` bean and `invalidate` after every transaction, but this probably would break when executing multiple transaction at the same time.

2023-06-05 18:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/AccountAccessorImpl.java
> +    }
I want to clarify the usage of these accessors. I know it's confusing but we have different types of accessors. We have several types related to the stacked state design which are:

- AccountDatabaseAccessor
- TokenDatabaseAccessor
- UniqueTokenDatabaseAccessor
- TokenRelationshipDatabaseAccessor

They are stateless and serve as a repository layer.

We have a different kind of accessors, that were introduces a while ago inside the `hedera-evm` design. Those are [AccountAccessor](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AccountAccessorImpl.java) and [TokenAccessor](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/TokenAccessorImpl.java). Their intent was to serve as a facade for accessing in-memory states and hide the services ledger logic. As it can be seen in the codebase they wrap a `WorldLedgers` instance that hold all type of ledgers which are keeping state. On `mirror-node` side we have `StackedStateFrames` that substitute the Ledger design. That's why here we want to wrap a `StackedStateFrames` instance and perform read related operations. We have interfaces defined in `hedera-evm` and we should provide an implementation for them in order to integrate with the library.

2023-06-09 07:29 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +    }
Fixed

2023-06-09 07:29 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    }
Fixed

2023-06-09 07:30 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +                final TokenAccessorImpl tokenAccessor,
Fixed

2023-06-13 03:43 UTC, steven-sheehy requested changes

2023-06-13 03:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +    private final StackedStateFrames<Object> stackedStateFrames;
This stateful stacked state class is infecting every other stateless class and making them in turn become stateful. This increases overall memory and causes concurrency issues (see incorrect changes to `MirrorEvmTxProcessorFacadeImpl` in this PR, for an example).

Ideally, every service class is stateless and state is stored in some object that is passed around. If that's not possible, but we can guarantee that any particular request executes on the same request for the entirety of its lifetime then we take another approach. Even though I'm not a fan of them usually, how about using `ThreadLocal` in `StackedStateFrames` and making it stateless?

2023-06-13 03:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +    private EntityRepository entityRepository = mock(EntityRepository.class);
Why?

2023-06-13 03:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldStateTest.java
> +    TokenAccessorImpl tokenAccessor;
Should use the interfaces so we can use proxies instead of cglib.

2023-06-13 03:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/AccountAccessorImplTest.java
> +    private EntityRepository entityRepository = mock(EntityRepository.class);
Revert

2023-06-13 03:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    private Address evmAddressFromId(EntityId entityId) {
Missing some test coverage in this method

2023-06-13 13:05 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +    private Address evmAddressFromId(EntityId entityId) {
Fixed

2023-06-13 13:05 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/AccountAccessorImplTest.java
> +    private EntityRepository entityRepository = mock(EntityRepository.class);
Fixed

2023-06-13 13:06 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldStateTest.java
> +    TokenAccessorImpl tokenAccessor;
Fixed

2023-06-13 13:08 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +    private MirrorEvmContractAliases aliasManager;
Fixed

2023-06-13 18:06 UTC, IvanKavaldzhiev commented
Consider removing `MirrrorEntityAccess`, `TokenAccessorImpl` and `AccountAccessorImpl` in favour of the `StateImpl` class introduced in this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6173) by making it implement all of the needed 3 interfaces.

2023-06-16 12:05 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +    private final StackedStateFrames<Object> stackedStateFrames;
@steven-sheehy I think the two types of nodes differ in nature. The consensus node handles transactions one by one and it's not a problem to have stateful components there, while on the Archive Node we would handle multiple transactions at once.

What about creating new `TokenAccessor`, `AccountAccessor`, `MirrorEntityAccess` for each new transaction? It would increase the memory footprint but it's an easy way to avoid the concurrency issues.

2023-06-16 12:10 UTC, IvanKavaldzhiev commented
> Consider removing `MirrrorEntityAccess`, `TokenAccessorImpl` and `AccountAccessorImpl` in favour of the `StateImpl` class introduced in this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6173) by making it implement all of the needed 3 interfaces.

It seems it can't be achieved without changes in `hedera-evm`, since `AbstractLedgerEvmWorldUpdater` requires 3 concrete different implementations for the 3 interfaces. We can postpone this idea for now.

2023-06-22 18:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(Entity.class).get(entityId);
`EntityDatabaseAccessor` works with Address as a key. You have to convert the `EntityId` to `Address`.

2023-06-22 18:28 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(List.class).get(entityIdNum);
We would most probably update given Token's list of CustomFees, not keeping standalone CustomFees in the state, so if we want to fetch updated CustomFees info, we should first fetch a given Token from the state and then return it's list of CustomFees. Use TokenDatabaseAccessor instead.

2023-06-22 18:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(TokenAllowance.class).get(id);
I think we should fetch an `Account` model and use its `SortedMap<FcTokenAllowanceId, Long>`

2023-06-22 18:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + *  3. Added equals() and hashCode()
Document added method `isEmptyUniqueToken`

2023-06-23 10:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(NftAllowance.class).get(id);
Fetch an `Account` model and read its set of `approveForAllNfts`

2023-06-23 10:13 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).hasFreezeKey();
Use `isFrozenByDefault`

2023-06-23 10:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getType();
This call would always return `FUNGIBLE` type. We should take into account both fungible and non-fungible cases. I suggest using both `getFungibleToken` and `getUniqueToken` and return type based on which of the two methods actually returns a result.

2023-06-23 10:33 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getName();
Again use both `getFungibleToken` and `getUniqueToken` methods

2023-06-23 10:33 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getSymbol();
Again use both `getFungibleToken` and `getUniqueToken` methods

2023-06-23 10:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getTotalSupply();
Again use both `getFungibleToken` and `getUniqueToken` methods

2023-06-23 10:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getTokenAllowance(tokenAllowanceId, OnMissing.DONT_THROW)
Make sure `getTokenAllowance` internally calls `getAccount` and uses its allowance map.

2023-06-23 10:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                new NftId(entityId.getShardNum(), entityId.getRealmNum(), entityId.getEntityNum(), serialNo),
Consider extracting a utility method that constructs `NftId` based on `EntityId` and `serial number`.

2023-06-23 10:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getTotalSupply();
Update: Based on the changes from this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6239/files#diff-0b44d84d46804689d917a7efa810b48531856c99e62e4840c1a98ff4ca319c7b) you should just invoke `getToken()` method.

2023-06-23 10:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getSymbol();
Update: Based on the changes from this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6239/files#diff-0b44d84d46804689d917a7efa810b48531856c99e62e4840c1a98ff4ca319c7b) you should just invoke getToken() method and actually keep the rest of your logic.

2023-06-23 10:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getName();
Update: Based on the changes from this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6239/files#diff-0b44d84d46804689d917a7efa810b48531856c99e62e4840c1a98ff4ca319c7b) you should just invoke getToken() method and actually keep the rest of your logic.

2023-06-23 10:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).getType();
Update: Based on the changes from this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6239/files#diff-0b44d84d46804689d917a7efa810b48531856c99e62e4840c1a98ff4ca319c7b) you should just invoke getToken() method and actually keep the rest of your logic.

2023-06-23 10:43 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        evmTokenInfo.setDefaultFreezeStatus(tokenEntity.hasFreezeKey());
Use getFreezeDefault

2023-06-23 10:44 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getCustomFee(entityIdNumFromEvmAddress(address), OnMissing.DONT_THROW)
Rework `getCustomFees` to internally use `getToken`

2023-06-23 10:46 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return HashCodeBuilder.reflectionHashCode(this);
Why we need `equals` and `hashCode`? Is `UniqueToken` part of a collection?

2023-06-23 12:09 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(TokenAllowance.class).get(id);
Fixed

2023-06-23 12:09 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> + *  3. Added equals() and hashCode()
Fixed

2023-06-23 12:10 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(List.class).get(entityIdNum);
Fixed

2023-06-23 12:10 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(NftAllowance.class).get(id);
Fixed

2023-06-23 12:10 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return stackedStateFrames.top().getAccessor(Entity.class).get(entityId);
Fixed

2023-06-23 12:11 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getFungibleToken(address, OnMissing.DONT_THROW).hasFreezeKey();
Fixed

2023-06-23 12:13 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getTokenAllowance(tokenAllowanceId, OnMissing.DONT_THROW)
Fixed

2023-06-23 13:02 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return HashCodeBuilder.reflectionHashCode(this);
I use them in `isEmptyUniqueToken` because some of the `Store` methods do not support `Optional` and there is a need for check if store returned default value or not.

2023-06-23 13:52 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                new NftId(entityId.getShardNum(), entityId.getRealmNum(), entityId.getEntityNum(), serialNo),
Fixed

2023-06-23 13:52 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        evmTokenInfo.setDefaultFreezeStatus(tokenEntity.hasFreezeKey());
Fixed

2023-06-23 13:52 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getCustomFee(entityIdNumFromEvmAddress(address), OnMissing.DONT_THROW)
Fixed

2023-06-24 03:40 UTC, steven-sheehy requested changes

2023-06-24 03:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/Store.java
> +    Token getToken(Address address, OnMissing throwIfMissing);
Up until this, the `Store` was returning services models. Now it returns both mirror node models and services models. This is confusing. I think it makes more sense for it to only return services models as it's used mainly within services code. We don't want to start leaking mirror node internals into copied services code if we can help it.

2023-06-24 03:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return EqualsBuilder.reflectionEquals(this, obj);
We should never use reflection for equals and hashCode

2023-06-26 09:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return EqualsBuilder.reflectionEquals(this, obj);
Fixed

2023-06-26 10:00 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/Store.java
> +    Token getToken(Address address, OnMissing throwIfMissing);
Removed the methods, returning mirror node models

2023-06-26 12:05 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +        final AccountAccessor accountAccessor = new AccountAccessorImpl(mirrorEntityAccess);
You can use `var` for all fields

2023-06-26 12:16 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return account.getFungibleTokenAllowances().get(fcTokenAllowanceId);
You can remove line 170 and use directly:

`account.getFungibleTokenAllowances().getOrDefault(0L)`

2023-06-26 13:02 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityOptional = mirrorEntityAccess.findEntity(address);
I think that we should entirely use the `token` model from the store. The first time it's fetched we use `tokenRepository` + `entityRepository`. From then on, we read or update the existing token inside the state. If we want to create a new token, a token model is created and saved in the store and again we should read its fields.

2023-06-27 07:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return account.getFungibleTokenAllowances().get(fcTokenAllowanceId);
Fixed

2023-06-27 12:45 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityAddress = nft.getOwner() != null ? nft.getOwner().asEvmAddress() : Address.ZERO;
Fixed

2023-06-27 12:45 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +        final AccountAccessor accountAccessor = new AccountAccessorImpl(mirrorEntityAccess);
Fixed

2023-06-27 14:31 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        final var entityOptional = mirrorEntityAccess.findEntity(address);
Fixed

2023-06-27 14:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +     */
We can define an `Entity` DTO model that `MirrorEntityAccess` could use. It can be defined in `com.hedera.services` package, even though it won't be copied from services repo.

Then, in `findEntity` we can first search for an account via `store.getAccount`:
- if we find it, map it to the `Entity` model and return it
- if not, try to find a token via `store.getToken`
- if we find a token, again map it to the `Entity` model
- if nothing is found - return `Optional.empty()`

@steven-sheehy I'll be happy to see your opinion as well.

2023-06-28 03:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +     */
I think `MirrorEntityAccess.findEntity()` should never have really been exposed since it's implementing a services interface but also exposing mirror node domain classes for `MirrorEvmContractAliases`. Shouldn't we transition all of `MirrorEntityAccess` to use the Store and remove its reliance on mirror node domain as much as possible? Thus `findEntity` should go away.

2023-06-28 08:56 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +     */
Removed `MirrorEntityAccess.findEntity()` . Using the store to fetch `Token` or `Account` in place of `Entity`.

2023-06-28 09:43 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +        final var resolvedAddress = Address.wrap(Bytes.wrap(toEvmAddress(entityId)));
Instead of constructing `entityId`, you can directly fetch the address from an `account` or if it's a `token`, you can get it's `id` and use i`d.toEvmAddress`

2023-06-28 09:54 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +        } else { // if token is present - get id
You can place all comments above the lines, not sideways, to increase readibility.

2023-06-28 12:57 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +        return store.getToken(address, OnMissing.DONT_THROW).getName();
Nice catch! Changed `Token` to return empty strings and added tests for this case.

2023-06-28 12:57 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +        } else { // if token is present - get id
Fixed

2023-06-28 12:57 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +        final var resolvedAddress = Address.wrap(Bytes.wrap(toEvmAddress(entityId)));
Fixed

2023-06-29 04:49 UTC, steven-sheehy approved these changes
LGTM

2023-06-29 12:27 UTC, merged