5862 add support for real time account details on account api endpoint
hashgraph/hedera-mirror-node pull request #6034
Opened 2023-05-19 18:15 UTC by jnels124

**Description**:
modify the data returned by the `/api/v1/accounts/{ID}`  endpoint when passing the timestamp query parameter
* union entity query with entity_history for specified timestamp
* return balance by querying the `account_balance` table for matching timestamp query
* filter token balances from `token_account` by matching `created_timestamp` against timestamp query
-->

**Related issue(s)**:

Fixes #5862 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-19 18:24 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +      entityBalanceQuery.params,
will fix order

2023-05-19 18:40 UTC, jnels124 commented
Generated Query

```sql
(with latest_token_balance as (select account_id, balance, token_id, created_timestamp
                                    from token_account
                                    where associated is true)
       select e.alias,
e.auto_renew_period,
e.created_timestamp,
e.decline_reward,
e.deleted,
e.ethereum_nonce,
e.evm_address,
e.expiration_timestamp,
e.id,
e.key,
e.max_automatic_token_associations,
e.memo,
e.receiver_sig_required,
e.staked_account_id,
e.staked_node_id,
e.stake_period_start,
e.type,
e.timestamp_range,
(case when es.pending_reward is null then 0
         when e.decline_reward is true or coalesce(e.staked_node_id, -1) = -1 then 0
         when e.stake_period_start >= es.end_stake_period then 0
         else es.pending_reward
    end) as pending_reward,
                       (select max(consensus_end) from record_file)  as consensus_timestamp,
                       balance,
                       (select json_agg(jsonb_build_object('token_id', token_id, 'balance', balance)) ::jsonb
                        from (select token_id, balance
                              from latest_token_balance
                              where account_id = ? and created_timestamp = ?
                              order by token_id asc
        limit 1000) as account_token_balance) as token_balances
                from entity e
                         left join entity_stake es on es.id = e.id

                where e.type in ('ACCOUNT', 'CONTRACT') and e.id = ? and (es.id = ? OR es.id IS NULL) and e.timestamp_range && ? order by id asc)

          UNION ALL

      (with latest_token_balance as (select account_id, balance, token_id, created_timestamp
                                    from token_account
                                    where associated is true)
       select e.alias,
e.auto_renew_period,
e.created_timestamp,
e.decline_reward,
e.deleted,
e.ethereum_nonce,
e.evm_address,
e.expiration_timestamp,
e.id,
e.key,
e.max_automatic_token_associations,
e.memo,
e.receiver_sig_required,
e.staked_account_id,
e.staked_node_id,
e.stake_period_start,
e.type,
e.timestamp_range,
(case when es.pending_reward is null then 0
         when e.decline_reward is true or coalesce(e.staked_node_id, -1) = -1 then 0
         when e.stake_period_start >= es.end_stake_period then 0
         else es.pending_reward
    end) as pending_reward,
                       ab.consensus_timestamp as consensus_timestamp,
                       ab.balance as balance,
                       (select json_agg(jsonb_build_object('token_id', token_id, 'balance', balance)) ::jsonb
                        from (select token_id, balance
                              from latest_token_balance
                              where account_id = ? and created_timestamp = ?
                              order by token_id asc
        limit 1000) as account_token_balance) as token_balances
                from entity_history e
                         left join entity_stake es on es.id = e.id
                         left join (select account_id, balance, consensus_timestamp
                    from account_balance
                    where account_id = ? and consensus_timestamp = ?
                    order by consensus_timestamp desc
                    limit 1) ab on ab.account_id = e.id
                where e.type in ('ACCOUNT', 'CONTRACT') and e.id = ? and (es.id = ? OR es.id IS NULL) and e.timestamp_range && ? order by timestamp_range desc limit 1)
          order by timestamp_range desc limit 1;
```

2023-05-19 19:01 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +    tokenBalanceQuery.query += ` and ${transactionTsQuery.replace('t.consensus_timestamp', 'created_timestamp')} `;
do we want to use the timestamp_range instead?

2023-05-19 19:13 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +    accountBalanceQuery.params = [encodedId, accountBalanceTs ?? null];
in some cases `accountBalanceTs ` can be undefined. In this case, we can't find balance information. Should the response indicate null/zero balance in this case, or should we grab the  balance, timestamp_range end  from the entity`? The only ways I can see this happening are, on a new account that doesn't have a balance file (possibly an account create creates an entry there but didn't verify), or if multiple timestamp parameters are supplied that don't include the range of a balance file.

2023-05-19 19:59 UTC, jnels124 commented on hedera-mirror-test/k6/src/rest/test/accountsIdTimestampLte.js
> +  .check('Accounts Id OK', isSuccess)
will fix label

2023-05-24 12:47 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +    const balanceSelect = 'ab.balance as balance';
should we coalesce with the entity_history.balance ?

2023-05-24 17:22 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Historical stake and reward information is not available so these fields contain current data.
Thanks for this line as I was going to ask for it.
According to @steven-sheehy the `ethereum_nonce` value may also not be valid when it's historical. 
Can we note its limited details also and open a ticket for that similar to what you did for staking? 
If it is indeed accurate then great as that was one of the main driving factors behind the ticket.

2023-05-24 17:22 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  logger.debug('The req query is ');
SHould this be similar to the below example to be in line with other logging of queries?
```
if (logger.isTraceEnabled()) {
      logger.trace(`? query: ${req.query}, params: ${acceptedParameters}`);
    }
```

2023-05-24 17:35 UTC, jnels124 commented on hedera-mirror-rest/controllers/contractController.js
> +  logger.debug('The req query is ');
intended to remove that. thanks

2023-05-24 17:36 UTC, jnels124 commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Historical stake and reward information is not available so these fields contain current data.
Yes will do.

2023-05-26 18:21 UTC, steven-sheehy requested changes

2023-05-26 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +          ${getEntitySql(
I think this is the wrong way to go about things. Here you're doing two separate queries (one history and one main) where each of those has separate joins on tables whose information would not vary. We should do one sub query for entity union entity_history then join the results of that query on other tables.

2023-05-26 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +    utils.mergeParams(
Per your comment in the ticket, there are a lot of duplicate parameters:

```
[111146,"1684921798808550755",111146,1570810500024187000,111146,111146,"(,1684921798808550755]",111146,"1684921798808550755",111146,1570810500024187000,111146,111146,"(,1684921798808550755]"]
```
We should clean that up so that there's only one `$N` parameter for each distinct value.

2023-05-26 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +                              order by token_id ${order}
It's strange that this uses a CTE when it's not necessary here. Can we push the CTE down into the sub-query and remove the CTE?

2023-05-26 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +          ${getEntitySql(
For the union, we can use wildcards for the fields within the sub-queries and only explicitly select the fields outside it. Something like `select e.id, e.balance from (select * from entity union all select * from entity_history) as e`.

2023-05-26 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +                    where ${accountBalanceQuery.query}
We should first search account_balance_file to get timestamp then use that for account_balance since the former is much smaller.

2023-05-26 18:31 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    accountBalanceQuery.params = [encodedId, accountBalanceTs ?? null];
I don't think we have a good solution. What's missing and very important in the `timestamp` query param handling is we don't have application side logic to calculate a single effective range from all the `timestamp` values in the request url.

Without that , when `balances.getAccountBalanceTimestamp` returns `undefined`, we don't know if it's because there is no account balance file's timestamp satisfying the `timestamp` range or the effective `timestamp` range is empty.

The main obstacle is we support the weird `ne` not equal operator, e.g., with `timestamp=ne:100`, the range becomes `timestamp in (,100) or timestamp in (100,)`.

Assume we drop `ne` operator support, we can then

- calculate the effective timestamp range
- if the range is empty, return 400
- if the range has upper bound, disregard the lower bound, and find the last account balance file satisfying the upper bound
- if the range has lower bound and no upper bound, find the first account balance file satisfying the lower bound
- if account balance file is found but the account balance is not in it, use balance from entity / entity_history
- if no account balance file found, use balance from entity / entity_history
- if no row found from entity / entity_history satisfying the timestamp range, return 404

2023-05-26 21:43 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +    utils.mergeParams(
Not sure the best way to go about this without using named parameters which isn't available. I will look for additional examples in the code base but so far what i have seen is duplicated parameters.

2023-05-26 21:46 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +                    where ${accountBalanceQuery.query}
this is done in the calling method when populating the accountBalanceQuery

2023-05-26 22:54 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +          ${getEntitySql(
That was a big miss on my part. I will update the query to be more similar to 

```sql
with entity_data as (select *
                     from entity e
                     where e.type in ('ACCOUNT', 'CONTRACT')
                       and e.id = 45385
                       and e.timestamp_range && '(,1680288435601059000]'
                     UNION ALL
                     select *
                     from entity_history e
                     where e.type in ('ACCOUNT', 'CONTRACT')
                       and e.id = 45385
                       and e.timestamp_range && '(,1680288435601059000]'
                     ORDER BY timestamp_range desc
                     LIMIT 1),
     latest_token_balance as (select account_id, balance, token_id, created_timestamp
                              from token_account
                              where associated is true)
SELECT e.alias,
       e.auto_renew_period,
       e.created_timestamp,
       e.decline_reward,
       e.deleted,
       e.ethereum_nonce,
       e.evm_address,
       e.expiration_timestamp,
       e.id,
       e.key,
       e.max_automatic_token_associations,
       e.memo,
       e.receiver_sig_required,
       e.staked_account_id,
       e.staked_node_id,
       e.stake_period_start,
       e.type,
       e.timestamp_range,
       (case
            when es.pending_reward is null then 0
            when e.decline_reward is true or coalesce(e.staked_node_id, -1) = -1 then 0
            when e.stake_period_start >= es.end_stake_period then 0
            else es.pending_reward
           end)                                                                       as pending_reward,
       COALESCE(ab.consensus_timestamp, (select max(consensus_end) from record_file)) as consensus_timestamp,
       COALESCE(ab.balance, e.balance)                                                as balance,
       (select json_agg(jsonb_build_object('token_id', token_id, 'balance', balance)) ::jsonb
        from (select token_id, balance
              from latest_token_balance
              where account_id = 45385
                and created_timestamp <= 1680288435601059000
              order by token_id asc
              limit 1000) as account_token_balance)                                   as token_balances
from entity_data e
         left join entity_stake es on es.id = e.id
         left join account_balance ab on ab.account_id = e.id and consensus_timestamp = 1680288301107978238;
```

2023-05-27 02:03 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +                    where ${accountBalanceQuery.query}
Ok, didn't see it in your example query above.

2023-06-08 15:39 UTC, steven-sheehy requested changes

2023-06-08 15:39 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp-notfound.json
> +    "/api/v1/accounts/0.0.8?timestamp=lte:1234567890.000000007&timestamp=ne:1234567890.000000004",
not equals should result in an invalid param error

2023-06-08 17:14 UTC, xin-hedera requested changes

2023-06-08 17:14 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +      (prev, curr) => prev || parseInteger(curr.value) === accountBalanceTs,
it should be cheaper to just do `==` with auto type coercion, for timestamp, filter.value is a string, `accountBalanceTs` is either a number or a BigInt
 
```suggestion
      (prev, curr) => prev || curr.value == accountBalanceTs,
```

2023-06-08 17:14 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp-notfound.json
> +    "/api/v1/accounts/0.0.8?timestamp=lte:1234567890.000000007&timestamp=ne:1234567890.000000004",
I think the consensus is don't break it by invalid param error, query the database with `ne` ignored, and apply the `ne` filters on the result

2023-06-14 23:35 UTC, xin-hedera requested changes

2023-06-14 23:35 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  const difference = latest && earliest ? latest - earliest + 1n : undefined;
if latest or earliest is 0n, `latest && earliest` is 0n, same as boolean false. so need to check strictly `latest !== undefined && earliest !== undefined`

2023-06-14 23:35 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    }
isn't this dead code? range always has a left bound (open or closed) and right bound

2023-06-14 23:35 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +      conditions.push(`${column}${boundToOp[bounds[0]]} ?`);
nit
```suggestion
      conditions.push(`${column} ${boundToOp[bounds[0]]} ?`);
```

2023-06-14 23:35 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +      params.push(Range(value, value, '[]'));
can just use the value
```suggestion
      params.push(value);
```

2023-06-14 23:35 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  logger.info(tsParams);
```suggestion
```

2023-06-15 00:50 UTC, jnels124 commented on hedera-mirror-rest/utils.js
> +  const difference = latest && earliest ? latest - earliest + 1n : undefined;
That is true but in the case of 0n 0n, the difference becomes 1n due to the + 1n. In that case, it will neither be > maxTimestampRangeNs and will not be <= 0n so this will not trigger the invalidArgumentError. I will update it to explicitly check for undefined though because that is more clear.

2023-06-15 00:51 UTC, jnels124 commented on hedera-mirror-rest/utils.js
> +    }
yes this could probably be removed.

2023-06-15 12:34 UTC, jnels124 commented on hedera-mirror-rest/utils.js
> +      params.push(Range(value, value, '[]'));
This would have to be a range because it is using the range operator `@>`

2023-06-15 17:29 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +    const timestampExcluded = neValues.reduce((prev, curr) => prev || curr === accountBalanceTs, false);
I see the neValues is an array of `BigInt` now, however, `accountBalanceTs` can be either a `Number` or a `BigInt`, so we'll end up with `10n === 10` evaluated to false, we can do either of the two

- use `utils.parseInteger` instead of `BigInt` in `checkTimestampRange`
- use `curr == accountBalanceTs` here and let js do the coercion

in addition, we should do `Array.prototype.some` instead of reduce
```suggestion
    const timestampExcluded = neValues.some((value) => value == accountBalanceTs);
```

2023-06-16 15:44 UTC, xin-hedera approved these changes
LGTM

2023-06-16 16:04 UTC, steven-sheehy approved these changes
LGTM

2023-06-16 17:09 UTC, merged