fix: estimations for contract create
hashgraph/hedera-mirror-node pull request #6056
Opened 2023-05-22 10:30 UTC by nikolovyanko

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-23 14:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessor.java
> +        // in cases where the receiver is the zero address, we now it's estimate gas call for contract create
We can change the comment like this:

`we now it's estimate gas call for contract create -> we know it's a contract create scenario`

In future cases this might be an eth_debug<> operation, so we'd better not mention estimate gas in the comment.

2023-05-24 03:59 UTC, steven-sheehy requested changes
Need to merge from main

2023-05-24 03:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long estimateGasIterationThreshold = 4200L;
Adjust `docs/configuration.md` as well

2023-05-24 19:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long estimateGasIterationThreshold = 4200L;
Done

2023-05-24 20:02 UTC, steven-sheehy approved these changes
LGTM

2023-05-24 20:03 UTC, merged