Add support for node ID based bucket paths in MetricsExecutionInterce…
hashgraph/hedera-mirror-node pull request #6060
Opened 2023-05-22 17:25 UTC by jascks

**Description**:
Update `MetricsExecutionInterceptor` to recognize and process node ID based format in S3 URI in addition to current node account ID format.

This PR
* `MetricsExecutionInterceptor` refactoring and natural incorporation of pattern matching and parsing of both the legacy and new bucket structures. Also, allowed for introduction of mock builders for testing.
* Create `MetricsExecutionInterceptorTest` to test the new functionality and verify the old.

**Related issue(s)**:

Fixes # 6023

**Notes for reviewer**:
The new test class is specific to the problem this PR resolves and is not a general test class for all `MetricsExecutionInterceptor` functionality. Perhaps it will grow into one in the future.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-22 21:36 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +class MetricsExecutionInterceptorTest {
When I saw there was no unit test class for `MetricsExecutionInterceptor`, my first inclination was to maybe settle for manual testing by looking at the metrics produced in actuator. But I wanted to have a unit test for both for the automation benefits as well as easily throwing a lot of different scenarios at it. And, it helps with test coverage. :)

In my opinion, there is nothing wrong with modifying a class in order to make it more testable, particularly since the class under test and the test class are in the same package, and that can be taken advantage of while leaving existing public access un-impacted.

We're basically only doing string pattern matching on S3 URIs to determine the values to assign to the tags, and then verify the proper values. I can see why there was not a preexisting unit test class, given it was kind of painful to get access to the generated tags. But, I've got it, and it works great!

For this level of testing, is there a need for S3 proxy, s3 client, and hosting actual files etc? I admit, I was unaware of `SimpleMeterRegistry`, and perhaps it can be helpful within the unit test and allow me to eliminate some mocks and revert some of the changes to `MetricsExecutionInterceptor`.

2023-05-22 21:52 UTC, steven-sheehy requested changes

2023-05-22 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +                "realm", uriAttributes.realm().toString(),
I think we should drop realm now that we can't capture it. We will probably never have a non-zero realm anyway.

2023-05-22 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var streamType = getType(t -> decodedUri.contains(t.getPath()));
If you change the `ENTITY_ID_PATTERN` to `\/(balance|event|record)(s_)?(\d{1,10})\.\d{1,10}\.(\d{1,10})` then you can extract the type, shard and num directly  from the single regex and don't need `EntityId` or `getType()`.

2023-05-22 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +        var decodedUri = URLDecoder.decode(uri.toString(), StandardCharsets.UTF_8);
Perhaps instead of decoding the URI or treating as a string we just pass parts of the URI to various matchers/contains. For example, for `ENTITY_ID_PATTERN` and `NODE_ID_PATTERN ` we should only need to pass `uri.getPath()`.

2023-05-22 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var streamType = getType(t -> decodedUri.contains(t.getNodeIdBasedSuffix()));
We can extract the type from the URI path instead of a separate contains.

2023-05-22 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +    private record UriAttributes(Long shard, Long realm, Long nodeId, String streamType, String action) {}
```suggestion
    private record UriAttributes(String action, long node, long, shard, String type) {}
```

2023-05-22 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +class MetricsExecutionInterceptorTest {
I don't think we have to go the full s3proxy route, but we definitely should not mock the `MeterRegistry` or any Micrometer related classes. So let's change to use `SimpleMeterRegistry` so that we can properly verify the metrics are populated. You can see `SubscribeMetricsTest` for an example.

2023-05-22 22:05 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +class MetricsExecutionInterceptorTest {
Ok, thanks!

2023-05-23 00:08 UTC, steven-sheehy commented
Need to update the Grafana dashboards as well to remove references to realm or nodeAccount

2023-05-23 12:47 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +                "realm", uriAttributes.realm().toString(),
I wonder if we should drop `method` as well:
```
hedera_mirror_download_response_bytes_sum{action="list",application="hedera-mirror-importer",method="GET",node="3",realm="0",shard="0",status="200",type="BALANCE",} 6284.0
hedera_mirror_download_response_bytes_count{action="signature",application="hedera-mirror-importer",method="GET",node="1",realm="0",shard="0",status="200",type="RECORD",} 1.0
```
It appears list and object get are both http GETs, and those are the only S3 operations we make.

2023-05-23 12:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var streamType = getType(t -> decodedUri.contains(t.getPath()));
Cool, I like it. `NODE_ID_PATTERN` already provides the HIP-679 suffix of same values as well.

2023-05-23 15:02 UTC, xin-hedera requested changes

2023-05-23 15:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +                "realm", uriAttributes.realm().toString(),
It's fine to drop. Just double check Grafana visualizations to see if it's used.

2023-05-23 16:47 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var streamType = getType(t -> decodedUri.contains(t.getNodeIdBasedSuffix()));
Done

2023-05-23 16:47 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +        var decodedUri = URLDecoder.decode(uri.toString(), StandardCharsets.UTF_8);
Done.

2023-05-23 16:47 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var streamType = getType(t -> decodedUri.contains(t.getPath()));
Done

2023-05-23 16:48 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +                "realm", uriAttributes.realm().toString(),
Dropped `realm`, still looking into `method`...

2023-05-23 18:41 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +class MetricsExecutionInterceptorTest {
Okay, this is done. Using `SimpleMeterRegistry` I can access the tags for verification, and I was able to return the `MetricsExecutionInterceptor` constructor and metrics builders to their original state.

2023-05-23 18:43 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +    @ValueSource(strings = {"ACCOUNT_ID", "NODE_ID"})
Done. Note that `PathType` as a string must still be used for `s3GetObjectExecution()` given the `@CsvSource`.

2023-05-23 18:55 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +        openMocksCloseable = MockitoAnnotations.openMocks(this);
Done

2023-05-23 19:11 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +    @ValueSource(strings = {"ACCOUNT_ID", "NODE_ID"})
Well,  never mind, per your later suggestion, those strings can be converted to enum instances automatically. Nice.

2023-05-23 19:13 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +    @ValueSource(strings = {"ACCOUNT_ID", "NODE_ID"})
that's not true. I just reconfirmed with the following change

```java
void s3GetObjectExecution(CommonDownloaderProperties.PathType pathType, String streamTypeName, String fileName, String expectedAction) {
```

and 
```java
        var prefix = pathType == PathType.ACCOUNT_ID
                ? accountIdPrefix(streamType, SHARD, REALM, ACCOUNT_NUM)
                : nodeIdPrefix(streamType, NETWORK_NAME, SHARD, NODE_ID);
```

2023-05-23 19:28 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +    @ValueSource(strings = {"ACCOUNT_ID", "NODE_ID"})
Yes, you are correct. :). This has been done.

2023-05-23 19:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var shard = Long.parseLong(accountIdMatcher.group(3));
nit, can change the type of `shard` to String in the record, then don't have to parse the string to long here

2023-05-23 19:57 UTC, xin-hedera approved these changes
LGTM

2023-05-23 20:37 UTC, steven-sheehy requested changes

2023-05-23 20:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +        assertEquals(expectedStreamType.name(), providedTags.get(5).getValue());
We prefer using assertThat() over JUnit asserts and chaining multiple together.

```suggestion
        assertThat(meterRegistry.find("hedera.mirror.download.request").timers())
            .hasSize(1)
            .first()
            .returns(1L, t -> t.count())
            .returns(?, t -> t.mean(TimeUnit.SECONDS))
            .returns(?, t -> t.max(TimeUnit.SECONDS))
            .returns(expectedAction, t -> t.getId().getTag(TAG_ACTION))
            ...
```

2023-05-23 20:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +                meterRegistry.find("hedera.mirror.download.request").timers();
Move the string to a protected class constant for sharing. Same with other uses of metric names.

2023-05-23 20:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +        assertEquals(expectedAction, providedTags.get(0).getValue());
We should lookup via the string so it's clear. Move the tag names to static constants in interceptor.

2023-05-23 22:08 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
> +            var shard = Long.parseLong(accountIdMatcher.group(3));
Done

2023-05-23 22:09 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +                meterRegistry.find("hedera.mirror.download.request").timers();
Done

2023-05-23 22:09 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptorTest.java
> +        assertEquals(expectedAction, providedTags.get(0).getValue());
Done

2023-05-23 22:44 UTC, steven-sheehy approved these changes
LGTM. Thanks for leaving it cleaner than you found it 👍🏻

2023-05-23 23:22 UTC, xin-hedera approved these changes

2023-05-24 01:31 UTC, merged

2023-05-24 01:36 UTC, jascks commented
Thank you Steven and Xin for all your helpful comments and suggestions!