Bump: Update `hedera-evm` to `0.38.0`
hashgraph/hedera-mirror-node pull request #6067
Opened 2023-05-23 12:45 UTC by IvanKavaldzhiev

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-23 16:11 UTC, xin-hedera approved these changes

2023-05-23 16:56 UTC, steven-sheehy requested changes

2023-05-24 17:50 UTC, IvanKavaldzhiev commented on build.gradle.kts
> +        api("tech.pegasys:jc-kzg-4844:0.4.0")
I removed the extra dependency. The problem turned out to be not having the additional repository url needed for the dependency to be downloaded. It's already registered in `hedera-evm`, but mirror-node did not include the needed maven repository, so that it could be downloaded properly.

2023-05-24 18:30 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/java-conventions.gradle.kts
> +    }
Would prefer this moved to `hedera-mirror-web3/build.gradle.kts` since it's only applicable there. We should also probably move the other evm specific repositories like swirlds-registry and hyperledger. We should remove the snapshot repos until they're needed again.

2023-05-24 19:29 UTC, steven-sheehy approved these changes
LGTM

2023-05-24 19:32 UTC, xin-hedera approved these changes

2023-05-24 19:51 UTC, merged