Synced with main. Resolve conflicts.
hashgraph/hedera-mirror-node pull request #6072
Opened 2023-05-24 02:37 UTC by jascks

**Description**:

Avoid publicly introducing the new `networkPrefix` property and instead utilize the existing `network` property to achieve the same objective. See #4388 [PR comment](https://github.com/hashgraph/hedera-mirror-node/pull/5753#discussion_r1191694395).

- Remove `networkPrefix` from `MirrorProperties`.
- Also remove from `docs/configuration.md`.
- Update usage of `network` within the codebase to achieve the same functionality..

**Related issue(s)**:

Fixes #6024

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-30 20:40 UTC, steven-sheehy requested changes

2023-05-30 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
>      private String networkPrefix;
This is currently only used by tests. When we add resettable support, even then it would be called rarely when we detect a potential stream reset and may not be worth caching here and might be fine re-calculating in a `getNetworkPrefix()`. If we really think it's worth caching, can simplify:
```suggestion
    @Getter(lazy = true)
    private String networkPrefix = StringUtils.substringBefore(network, '-');
```

2023-05-30 20:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +        private static final Map<String, String> CANONICAL_REFERENCES = Map.of(
Can just use `NETWORK_DEFAULT_BUCKETS.keySet()` instead.

2023-05-30 21:22 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +        this.network = HederaNetwork.getCanonicalizedNetwork(networkName.toLowerCase());
A quick look in IDEA for result of `getNetwork()` being compared (`==` or `!=`) it looks like there are seven places in non-test code.

2023-05-30 21:43 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +        private static final Map<String, String> CANONICAL_REFERENCES = Map.of(
I'm not sure how the resultant `Set<String>` of canonical network names helps me. I could call `contains()` perhaps, but is a `true` because the reference is equal or that the two Strings just have the same hash code? Java does intern String literals by default, so perhaps my worries are unfounded?

2023-05-30 22:22 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
>      private String networkPrefix;
Taking a closer look at lombok lazy getter, it fires off only the first time it's called and then caches that result. Thus if `setNetwork()` is called again this getter will not reflect any changed network prefix. But in the normal course of reading properties from `application.yml` or elsewhere, this won't be an issue.

You're right though, #5713 is where any network prefix would be utilized. This PR just provided some basic String manipulation to accommodate and makes available any prefix specification; presently only utilized in the tests.

2023-05-31 03:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
>      private String networkPrefix;
It's probably easiest to just compute on read via a `getNetworkPrefix()` and no field.

2023-05-31 14:04 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
>      private String networkPrefix;
I concur. It's shaping up to be something like the following, using a single `network` field with a lombok generated setter.
```
    public String getNetwork() {
        return StringUtils.substringBefore(this.network, NETWORK_PREFIX_DELIMITER).toLowerCase();
    }

    public String getNetworkPrefix() {
        var networkPrefix = StringUtils.substringAfter(this.network, NETWORK_PREFIX_DELIMITER);
        return StringUtils.isEmpty(networkPrefix) ? null : networkPrefix;
    }
```
`StringUtils.substringAfter()` returns an empty string if the delimiter is not found. I prefer a `null` to that, or perhaps `getNetworkPrefix()` could return `Optional<String>`?

2023-05-31 17:27 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
>      private String networkPrefix;
Done

2023-05-31 17:27 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
> +        private static final Map<String, String> CANONICAL_REFERENCES = Map.of(
Done. Removed canonicalization stuff, so this is no longer a thing.

2023-05-31 18:28 UTC, steven-sheehy approved these changes
LGTM

2023-05-31 18:41 UTC, xin-hedera approved these changes
LGTM

2023-05-31 19:07 UTC, merged