HIP-584: Add FeeDistribution
hashgraph/hedera-mirror-node pull request #6078
Opened 2023-05-25 12:31 UTC by dikel

**Description**:

Copied FeeDistribution from services for TransferLogic

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-25 16:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/services/fees/charging/FeeDistributionTest.java
> +
Missing license header. Please ensure spotlessApply is ran automatically via git hook or run it manually if it's not. Ivan found that git-gui does not respect `core.hookspath`.

2023-05-25 16:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/context/properties/PropertySource.java
> +public interface PropertySource {
I'm not sure how you're planning on using this in the future, but we cannot add a new way to load properties from disk even temporarily. This PR is fine but in any future PR that implements PropertySource might have an issue. We can use services interfaces but we would need a custom implementation that can load via Spring Boot techniques like environment variables, application.yaml, application.properties, etc.

2023-05-26 07:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
> +public class GlobalDynamicProperties implements EvmProperties {
We should use `MirrorNodeEvmProperties` instead. If needed properties are missing - add them there.

2023-05-26 07:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/context/properties/PropertySource.java
> +public interface PropertySource {
Once we delete GlobalDynamicProperties - we can delete also PropertySource. It's not needed in web3.

2023-05-26 08:26 UTC, IvanKavaldzhiev requested changes
Generally, `FeeDistribution` is used for paying fees for staking. I don't think we need such a logic in the Archive Node. I suggest that we close the PR.

2023-05-29 07:50 UTC, closed without merging