When recordFile.hapiVersionMajor is null, …
hashgraph/hedera-mirror-node pull request #6115
Opened 2023-05-30 21:04 UTC by MarcKriguerAtHedera

…have getFullHapiVersion return null (instead of "null.null.null")

**Description**:
Fix recordFile.getFullVersion to return null (instead of "null.null.null") when the first component is null.
* Small tweak (described above) in `recordFile.getFullHapiVersion()`
* New spec file to test that it works.
-->

**Related issue(s)**:

Fixes #6069 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit)

2023-05-30 21:18 UTC, steven-sheehy requested changes

2023-05-30 21:18 UTC, steven-sheehy commented on hedera-mirror-rest/model/recordFile.js
> +    return `${this.hapiVersionMajor}` == `null` ? null
```suggestion
    return hapiVersionMajor === null || hapiVersionMinor === null || hapiVersionPatch === null ? null
```

2023-05-30 21:34 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/model/recordFile.js
> +    return `${this.hapiVersionMajor}` == `null` ? null
Done/

2023-05-30 21:49 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/model/recordFile.js
> +    return `${this.hapiVersionMajor}` == `null` ? null
Redone (the backticks and $ and braces are still gone, but needed to restore the "`this`." for the code to work).

2023-05-31 00:45 UTC, xin-hedera requested changes

2023-05-31 00:45 UTC, xin-hedera commented on hedera-mirror-rest/model/recordFile.js
> +    return (this.hapiVersionMajor === null || this.hapiVersionMinor === null || this.hapiVersionPatch === null) ? null
add `nullable: true` to open api spec for `hapi_version`

2023-05-31 17:23 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/model/recordFile.js
> +    return (this.hapiVersionMajor === null || this.hapiVersionMinor === null || this.hapiVersionPatch === null) ? null
Done.

2023-05-31 19:11 UTC, steven-sheehy approved these changes

2023-05-31 19:18 UTC, merged