Fix nft balance and state tracking with nested nft transfer
hashgraph/hedera-mirror-node pull request #6116
Opened 2023-05-31 14:00 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Relates to #6008 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-05-31 14:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +                domainNftTransfer(PAYER, DEFAULT_ACCOUNT_ID, SERIAL_NUMBER_1, TOKEN_ID),
there are several test cases with nft mint to a non-treasury account, e.g., here it was minted to `PAYER2` instead of the treasury account `PAYER`. I believe this was changed by a limechain PR.

2023-05-31 14:23 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> -        assertThat(allNftTransfers.contains(domainNftTransfer(PAYER, DEFAULT_ACCOUNT_ID, 2, TOKEN_ID)));
these assert nothing, most changes in the file are to fix the incorrect nft transfer assertion

2023-05-31 14:28 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> -        var nftTransfer = domainBuilder.nftTransfer();
since (token_id, serial_number) is the primary key of `nft_transfer` table, we had to flatten nft transfer if in the record, for the same nft when there are more than 1 transfer. e.g., alice -> bob, then bob -> carol, after flattening, there'll be a single nft transfer from alice to carol.

Once nested, it's no long needed, thus the test case is removed

2023-05-31 14:29 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> -    void onNftTransferDuplicates() {
for the same reason that we no longer have the constraint of `(token_id, serial_number)` being the primary key, we no longer dedup nft transfers. I'm also open to add it back

2023-05-31 14:30 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +    }
logic is from `findNftTransferInsideBody`, just made it more intuitive

2023-05-31 19:07 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java
> +
the nft transfers were incorrectly removed by the previous PR

2023-05-31 19:09 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        TokenTransferList mintTransfer1 = nftTransfer(TOKEN_ID, PAYER, DEFAULT_ACCOUNT_ID, List.of(SERIAL_NUMBER_1));
mint to treasury account `PAYER`, instead of `RECEIVER`

2023-05-31 23:29 UTC, MarcKriguerAtHedera approved these changes
LGTM

2023-06-01 16:14 UTC, steven-sheehy requested changes

2023-06-01 16:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/DeletedTokenDissociateTransferUpsertQueryGenerator.java
> +              where nt.consensus_timestamp = t.consensus_timestamp
What's the upper bound on the number of nested nft transfers that could be set on a single transaction here?

2023-06-01 18:27 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java
> +            return sharedTransfer;
can't use row mapper for `SharedTransfer`, since we map db column `serial_number` to SharedTransfer.amount

2023-06-01 22:22 UTC, steven-sheehy approved these changes
LGTM

2023-06-01 23:32 UTC, merged