5759 store streamfile path
hashgraph/hedera-mirror-node pull request #6153
Opened 2023-06-06 12:25 UTC by jascks

**Description**:

Currently we are creating the bucket download path based on the `PathType` enum for download and then recreating it to write back to. We should be able to cache this path to avoid having to recreate it for every node. 

* In `StreamFilename` add a string path to store the path while downloading and then writing it back.
* Modify `LocalStreamFileProvider` to read from the new path where consensus node writes it.
* Change signature and stream file to write back to disk using the same structure, converting paths appropriately.

**Related issue(s)**:

Fixes #5759 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-14 22:16 UTC, xin-hedera requested changes

2023-06-15 14:24 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return from(filePath, File.separator);
This particular method is used in numerous unit tests as well, which are referring to the local file system, either stuff in the tests `data` directory or those copied via `FileCopier`. There is a lot outside of `S3StreamFileProvider` where the platform separator is appropriate.

`S3StreamFileProvider.SEPARATOR` is used explicitly when building the `ListObjectsV2Request` as well as within the `StreamFilename` instance within each `StreamFileData` returned by `list()`. In that case as well, the file prefix is derived using only string manipulation and not via the likes of `Path.of()`, `Path.resolve()` etc.

The goal is for the S3 based `StreamFilename` instance to be used as the basis of the subsequent retrieval of the data files, including sidecars, and then utilizing that bucket relative path to archive the files in the appropriate structure in the local file system. It seems I need to look into that more closely along with your `Utility.java` comment.

I don't know if any of this code has ever been run on Windows. I'm trying to keep it in consideration. :)

2023-06-15 14:30 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return from(filePath, File.separator);
I don't think we should have changes with potential bugs because that's the preferred default in test cases.

2023-06-15 14:48 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return from(filePath, File.separator);
Okay. Just to be clear you want to see:
```
    public static StreamFilename from(String filePath) {
        return from(filePath, S3StreamFileProvider.SEPARATOR);
    }
```
And then where a different path separator character is required, to provide it via one of the other `from()` factory methods.

2023-06-15 14:54 UTC, jnels124 approved these changes
LGTM

2023-06-15 16:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return from(filePath, File.separator);
yup that is it

2023-06-15 17:12 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        Path destination = destinationRoot.resolve(streamFilename.getFilePath());
Done

2023-06-15 17:13 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +
Done

2023-06-15 17:14 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        Path destination = destinationRoot.resolve(streamFilename.getFilePath());
Had to do the same for `StreamFileSignature`.

2023-06-15 17:15 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return from(filePath, File.separator);
Okay, made the above change, and tests run since not on Windows. Looking at test code as to where to add `File.separator` as parameter.

2023-06-15 17:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
> +        return from(filePath, File.separator);
perhaps leave it as is, I don't think we need to support windows.

2023-06-15 17:19 UTC, xin-hedera approved these changes
LGTM

2023-06-16 16:03 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/FileCopier.java
> +                        .findFirst();
Not sure how many times this will be invoked, but wondering if a regex would be faster than a stream/filter and if a slight performance gain would be meaningful.

2023-06-16 16:05 UTC, edwin-greene approved these changes
Looks good

2023-06-16 18:19 UTC, mgoelswirlds submitted a review, later dismissed
The bucket restructure looks so clean and good now. I am glad that the path modularization is done here. 
LGTM

2023-06-16 18:23 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/FileCopier.java
> +                        .findFirst();
only used in test cases, so unless it's awfully slow, not worth the effort to optimize

2023-06-16 21:26 UTC, steven-sheehy requested changes
Still reviewing.

2023-06-16 21:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileSignature.java
> +    public String getFilePath() {
Method seems as an unnecessary wrapper around the StreamFilename.

2023-06-16 21:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                commonDownloaderProperties.getMirrorProperties().getDataPath().resolve(STREAMS);
We should not re-resolve the base path against the filename. The full path should already be populated by the list() and directly used in the get()

2023-06-16 21:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                .flatMapSequential(streamFilename -> get(node, streamFilename))
Why do we need to call get() instead of just doing the previous simpler `.map(StreamFileData::from)`?

2023-06-16 21:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                .map(file -> StreamFilename.from(prefixPathRef.get().toString(), file.getName(), File.separator))
This should not need to use prefixPathRef. The `file` should be the full absolute path of the file to return. Thus we can remove `prefixPathRef` entirely.

2023-06-16 21:40 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                commonDownloaderProperties.getMirrorProperties().getDataPath().resolve(STREAMS);
This path in `StreamFilename` is bucket relative in the case of `S3StreamFileProvider` and relative to a data directory in `LocalStreamFileProvider` so that it can be 're-rooted' when the file is written for archive.

2023-06-16 21:49 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileSignature.java
> +    public String getFilePath() {
No real reason I guess. Perhaps I pushed things a too little far [here](https://github.com/hashgraph/hedera-mirror-node/pull/6153#discussion_r1229986563).

2023-06-20 12:19 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/DownloaderProperties.java
> +        return getMirrorProperties().getDataPath();
Done.

2023-06-20 12:19 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileSignature.java
> +    public String getFilePath() {
Removed.

2023-06-20 13:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +        return readStreamFileData(file, StreamFilename.from(file.getPath(), File.separator));
why do we use `File.separator` here?

2023-06-20 14:22 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +        return readStreamFileData(file, StreamFilename.from(file.getPath(), File.separator));
This was in response to one of Steven's comments. I felt it was good to use here because we are working with a `File` here. I guess we need to draw a line here if this is a problem. @steven-sheehy, will we never support Windows? I was trying to remain agnostic where it made sense to me.

2023-06-20 14:40 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFileData.java
> +        return readStreamFileData(file, StreamFilename.from(file.getPath(), File.separator));
I see. didn't notice it's a static method only used in test cases.

we used to have windows support and dropped it later because not widely used afaict.

2023-06-20 16:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                .flatMapSequential(streamFilename -> get(node, streamFilename))
I guess it felt natural in my mind, similar to `S3StreamFileProvider` implementation. But, it is not necessary to do that. So, I put it back. Well, at least as far as working relative paths.

2023-06-20 17:07 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                commonDownloaderProperties.getMirrorProperties().getDataPath().resolve(STREAMS);
It seems the remaining issue centers around this. My intention is for the path added to `StreamFilename` to be relative to something, not an absolute path in itself. The full bucket structure, relative to the bucket name, is provided, in either legacy account ID or the new HIP-679 node ID format.

The importer cloud storage configuration can be such that the downloader is sourcing stream files from either GCS or S3 via `S3StreamFileProvider` or the local file system using `LocalStreamFileProvider`. Regardless of their source, the downloader may also archive signature and data files to the local file system.

For a given `StreamFilename`, if it was sourced from an S3 bucket (via `S3Proxy` or real life), or if was read from the local file system (a source data path, test directory etc.) the relative path reflecting the 'bucket' structure is the same. And then when that file is archived to a different location in the local file system, that same relative path is used, though relative to a different directory in the file system.

If `S3StreamFileProvider` provides a relative path and `LocalStreamFileProvider` supplies an absolute path, then at archive time this will need to be detected and processed in some manner to yield the same destination for writing the files.

2023-06-20 20:36 UTC, steven-sheehy approved these changes
LGTM

2023-06-20 20:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
> +                commonDownloaderProperties.getMirrorProperties().getDataPath().resolve(STREAMS);
I think we could've stored the absolute path and for archiving removed the well known prefix. The archive operation is disabled by default and no one probably uses it while the local filesystem provider will soon become important for historical synchronization, so makes sense to optimize for the latter. But we can keep as is for now.

2023-06-20 20:50 UTC, xin-hedera approved these changes
LGTM

2023-06-20 21:02 UTC, merged