HIP-584: Alias improvements
hashgraph/hedera-mirror-node pull request #6161
Opened 2023-06-07 16:00 UTC by stoyan-lime

**Description**:
Clean up alias resolution and keep already resolved values in-memory.

**Related issue(s)**:

Fixes #6052

2023-06-08 03:43 UTC, steven-sheehy requested changes

2023-06-08 03:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> -                    Bytes.wrap(entity.getEvmAddress() != null ? entity.getEvmAddress() : toEvmAddress(entityId));
Why are we no longer using the evmAddress if available and always encoding the account ID to an address?

2023-06-08 09:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> -                    Bytes.wrap(entity.getEvmAddress() != null ? entity.getEvmAddress() : toEvmAddress(entityId));
This method should always return the long-zero/mirror address and not the alias one. Currently for contracts we may have an alias address if the create is made via a top-level ethereum transaction and then I think the evm_address would hold the alias format, while we want the regular long-zero address.

2023-06-09 03:39 UTC, steven-sheehy approved these changes
LGTM, but need to merge first

2023-06-13 04:04 UTC, steven-sheehy approved these changes

2023-06-13 04:04 UTC, merged