HIP-584: Copy Associate logic
hashgraph/hedera-mirror-node pull request #6168
Opened 2023-06-08 09:35 UTC by stoyan-lime

**Description**:
Copy associate logic from services.
Unlike in services associateWith method is implemented in the AssociateLogic class instead of Account model.

Added modification builder to keep account immutability, if it is considered a good approach we can implement it in other places in following PR.

**Related issue(s)**:

Fixes #5907

2023-06-08 12:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxTokensPerAccount = 10_000_000;
Sort alphabetically and update `docs/configuration.md`

2023-06-08 12:42 UTC, IvanKavaldzhiev submitted a review, later dismissed
Very clean approach! LGTM 🥂

2023-06-09 03:47 UTC, steven-sheehy requested changes

2023-06-09 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +    @Builder(toBuilder = true)
We should not use mirror node only libraries in copied services code. Let's keep it exactly as services had it since it will soon be replaced.

2023-06-09 03:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/AssociateLogic.java
> +import com.hedera.mirror.web3.exception.InvalidTransactionException;
We should not be importing web3 classes into services code. If the stacked state is intended to be used in services code then it should do so upstream and a new version of the library produced.

2023-06-09 07:47 UTC, stoyan-lime commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +    @Builder(toBuilder = true)
In services Account is mutable and has setter methods. 
Instead of setters we have methods that copy the whole model with 1 property change.
This is just a cleaner way to do that, as we add a new method for each new property we need to change.

2023-06-13 21:37 UTC, david-bakin-sl approved these changes
(I have to come back and look at the unit tests better.)

Lots of suggestions, but as is my practice: approved.  If you make these changes, great!  If you make different changes inspired by my comments, also great! If you choose not to accept a comment, great too, but in that case please leave a counter-comment explaining why so that I can learn.

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                .filter(t -> t.getAssociated() == Boolean.TRUE)
Can't you just use a method reference here?  (like `Token::getAssociated()`?)

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                        TokenFreezeStatusEnum.FROZEN == tokenAccount.getFreezeStatus(),
Constructor has 5 booleans in a row ... sad.  Probably too late to change now since these are "copied" from services, right?

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +        this.store.wrap();
What's the difference (in purpose) between the `wrap()` here and the wrap [over here, above](https://github.com/hashgraph/hedera-mirror-node/pull/6168/files#diff-6f5c154402b6f237d5560c6746ae8377ad75b9d69f34ffbef75fb95634158fedR69)?  IOW, why are there two different places where you need to `wrap()`?

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +            store.commit();
And same question here for `commit`: What's the difference between the one here and the [one here, above](https://github.com/hashgraph/hedera-mirror-node/pull/6168/files#diff-fc0f01c4aa5719cefe1ebdcd828ffbf69c62de089ff9700984ee2affb89a75f9R59)?  Why does it need to be called in two separate places?

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> + * Copied Account model from hedera-services.
Definitely good to have this command and the `differences with original` comment with it, for each of these things copied from services!

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> + *     1. Missing fields like memo, key, isReceiverSigRequired, isSmartContract
Maybe "removed" instead of "missing"?  Describes the action taken, e.g., like "added" in point 2 below.

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/FcTokenAllowanceId.java
>  public class FcTokenAllowanceId implements Comparable<FcTokenAllowanceId> {
So ... what does the prefix `Fc` stand for anyway?

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/NftId.java
> + * Copied Id type from hedera-services.
`Id` -> `NftId`

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/OwnershipTracker.java
> +        return new Change(Id.DEFAULT, treasury, serialNumber);
`Change` has an error-prone API (IMO) but it's too late now.

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                Collections.emptyList(),
is the code coverage bot actually warning me that `Collections.emptyList()` is not covered by our tests?  For this it interrupts my reading flow?  Can't it be a bit smarter about it?

<img width="663" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/117694041/e69ad337-7c93-469f-b86c-f977b7779d82">

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
>              Id id,
This constructor takes
* 2 semantically different lists of `UniqueTokens`, consecutively
* 2 semantically different count values, consecutively
* 7, count'em: **7!!** semantically different _keys_ consecutively - their different uses are rather important, no?
* 2 semantically different `Account`s, consecutively
* now 3 semantically different boolean values, consecutively,
* 3 semantically different strings, consecutively,
* 3 semantically different integral values, consecutively
* and some other longs and booleans stuck in there for fun.

That vibration you're feeling in the seat of your pants is the vibration caused in your location by my teeth grinding over here.

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +        return TokenType.FUNGIBLE_COMMON;
would an explicit `else` help readability?

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/TokenRelationship.java
> +                !token.hasKycKey(),
Not clear to me why `!token.hasKycKey()` means "kycGranted" - is that just the known semantics of KYC keys, that if you've got one then it isn't the case that `kycGranted` and if you _don't_ have one then it _is_ the case that `kycGranted`?

2023-06-13 21:37 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/AssociateLogic.java
> +        final var account = store.getAccount(accountAddress, true);
See, wouldn't this line and line 56 below be easier to understand if they read `... store.getAccount(accountAddress, OnMissing.THROW_EXCEPTION)` ??

2023-06-13 21:37 UTC, david-bakin-sl submitted a review, later dismissed
[**DUPLICATE comment because Github was having issues**]

(I have to come back and look at the unit tests better.)

Lots of suggestions, but as is my practice: approved.  If you make these changes, great!  If you make different changes inspired by my comments, also great! If you choose not to accept a comment, great too, but in that case please leave a counter-comment explaining why so that I can learn.

2023-06-13 21:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                        TokenFreezeStatusEnum.FROZEN == tokenAccount.getFreezeStatus(),
If we agree on that, I can use the `toBuilder` Lombok generator in all models, to get rid of almost all constructors and just update the properties we need to modify. In this way the chance of mistyping an argument in the long constructor is minimised. These changes can be documented in the javadoc.

2023-06-13 23:02 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                        TokenFreezeStatusEnum.FROZEN == tokenAccount.getFreezeStatus(),
I think it is worth doing and would make things clearer - but @steven-sheehy may have other higher-priority ideas about it.

2023-06-14 09:19 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        if (stackedStateFrames.height() > 1) { // commit only to upstream RWCachingStateFrame
You're right. Internally we check whether we already have an upstream frame.

2023-06-14 09:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +        this.store.wrap();
Since the `HederaEvmWorldState` should introduce the first layer of `RWCachingStateFrame`, and then the `StackedUpdater` which is linked to a specific transaction execution (and consequently a message frame) needs also to introduce its own `RWCachingStateFrame`. Having a StackedUpdater basically means we are inside an internal child transaction and we need separate state layer for it, on top of the base main `RWCachingStateFrame` of the top level transaction.

2023-06-14 09:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +            store.commit();
This `commit` handles changes from the top level main transaction.
The `commit` from the `StackedStateUpdater` handles changes from an internal child transaction.

2023-06-14 09:33 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        if (stackedStateFrames.height() > 1) { // commit only to upstream RWCachingStateFrame
We check if there is a `upstreamFrame` , but if this frame happens to be `DatabaseBackedStateFrame` will throw `UnsupportedOperationException` . Maybe it is a good idea to keep this check (or do it internally in the stacked frames).

2023-06-14 09:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/TokenRelationship.java
> +                !token.hasKycKey(),
Yes, it seems this is the logic we have in services.

2023-06-14 14:37 UTC, IvanKavaldzhiev commented on docs/configuration.md
> + `hedera.mirror.web3.evm.tokenAssociationsLimited`      | true                                               | Limits the number of token associations per account when true
Fixed

2023-06-14 14:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/Store.java
> +public interface Store {
1. Added javadoc. I decided to remove the `pop()` operation and thus `addPendingChanges()`, so currently we have only `commit()`. I think poping made the whole logic more complicated, while currently I don't see the benefits. The main idea was each new nested call to start with a new `RWCachingStateFrame`, but currently having one `RWCachingStateFrame` for multiple nested transactions seems to also do the trick. There might be some corner cases with some intermediate reverts but I propose to start simple and add additional logic if needed and to test it with more complicated scenarios.
2. I added it. The reason was this functionality is not used in this PR. The interface would grow and capture more methods in the future.
3. Renamed
4. Added the Enum. It made the API clearer, indeed.

2023-06-14 14:43 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +            return account.orElseThrow(() -> missingEntityException(Account.class.getName(), address));
1. Added factory methods.
2. I think using this approach might make things more complicated.

2023-06-14 14:44 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        if (stackedStateFrames.height() > 1) { // commit only to upstream RWCachingStateFrame
That's correct. I left the check and it's good to be outside of the `commit` operation, since the `commit` is linked to the `CachingStateFrame` instance, which does not know the exact stack height.

2023-06-14 14:45 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +    private InvalidTransactionException missingEntityException(final String type, Object id) {
Done

2023-06-14 14:45 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                .filter(t -> t.getAssociated() == Boolean.TRUE)
Done

2023-06-14 14:46 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +        this.store.wrap();
I decided to leave just only this `wrap()` and have a common `RWCachingState` frame for all internal child transactions. Currently this approach works and simplifies the overall logic.

2023-06-14 14:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
> +            store.commit();
Having only one `wrap()` method, I decided to reduce also the number of commits to the one in the `StackedUpdater`. I removed the commit from the `HederaEvmWorldState`, since there we are at top level and this means we are ending the transaction execution and we don't want to commit anything anymore. Whereas, in services, we definitely want to commit the result of the top-level transaction to the state.

2023-06-14 14:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/NftId.java
> + * Copied Id type from hedera-services.
Fixed

2023-06-14 14:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +        return TokenType.FUNGIBLE_COMMON;
Added

2023-06-14 19:50 UTC, steven-sheehy requested changes

2023-06-14 19:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxTokensPerAccount = 1000;
```suggestion
    @Min(1)
    private int maxTokensPerAccount = 1000;
```

2023-06-14 19:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/CachingStateFrame.java
> +import org.checkerframework.checker.units.qual.K;
I don't think you meant to import this and actually wanted a generic K.

2023-06-14 19:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +                                        TokenFreezeStatusEnum.FROZEN == tokenAccount.getFreezeStatus(),
Again, the guiding principle we use is that we should minimize changes to these copied files. That way if upstream makes a change we can just grab the latest changes. So definitely we should not use Lombok in services code. If you'd like to improve copied code, improve it upstream first.

2023-06-14 19:50 UTC, steven-sheehy commented on docs/configuration.md
> + `hedera.mirror.web3.evm.tokenAssociationsLimited`      | true                                               | Limits the number of token associations per account when true
Is this property necessary? Since we allow `Long.MAX_VALUE` for `maxTokensPerAccount ` won't that one property be sufficient?

2023-06-14 19:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/AssociateLogic.java
> +        this.mirrorNodeEvmProperties = mirrorNodeEvmProperties;
This dependency could be fixed by adding a `EvmProperties.maxTokensPerAccount()` upstream.

2023-06-14 20:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/AssociateLogic.java
> +        this.mirrorNodeEvmProperties = mirrorNodeEvmProperties;
Do you mean adding it in `hedera-smart-contract-service` in services repo?

2023-06-14 20:05 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/CachingStateFrame.java
> +import org.checkerframework.checker.units.qual.K;
Correct, that import is a mistake

2023-06-14 20:18 UTC, IvanKavaldzhiev commented on docs/configuration.md
> + `hedera.mirror.web3.evm.tokenAssociationsLimited`      | true                                               | Limits the number of token associations per account when true
I removed the property, as well as the Lombok usage in the Account model.

2023-06-14 20:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxTokensPerAccount = 1000;
Fixed

2023-06-14 22:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/AssociateLogic.java
> +        this.mirrorNodeEvmProperties = mirrorNodeEvmProperties;
No, EvmProperties class which is in hedera-evm. Seems like a tiny change, but can consider later.

2023-06-14 22:50 UTC, steven-sheehy approved these changes

2023-06-15 03:31 UTC, merged