Add migration for synthetic transfer approvals
hashgraph/hedera-mirror-node pull request #6169
Opened 2023-06-08 14:14 UTC by edwin-greene

**Description**:
Add migration for synthetic transfers that are missing the correct approval flag.

**Related issue(s)**:

Fixes #5939 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-06-08 18:45 UTC, xin-hedera requested changes

2023-06-08 18:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +            });
I'm not sure if the update statements executed in the callback and the top level `TRANSFER_SQL` are all in a single db transaction. Perhaps we should wrap it within a `transactionTemplate`

In addition, instead of using `ResultSet`, can create a domain record class, then create a RowMapper (can refer to `IntegrationTest.rowMapper`), do `jdbcTemplate.query(TRANSFER_SQL, ROW_MAPPER)` or `jdbcTemplate.queryForStream(TRANSFER_SQL, ROW_MAPPER)`

2023-06-08 18:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +        }
we probably should not conclude that the transfer used allowance so we should change `is_approval` to true when either `keyBytes == null` or there's exception parsing the protobuf key bytes

2023-06-12 20:23 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +              (upper(e.timestamp_range) > cr.consensus_timestamp or upper(e.timestamp_range) is null)
I gave this a shot, but it yielded `ERROR:  operator does not exist: int8range @> nanos_timestamp`

2023-06-12 20:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +            with ecr as (
Thanks I have rewritten the sql, please re-review.

2023-06-12 20:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +              ) ct
Thanks I have removed the subquery.

2023-06-12 20:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +              ) t
Thanks I have removed it.

2023-06-12 20:26 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +              ) nft
Thanks I have simplified it by removing the unneeded subquery.

2023-06-12 20:26 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +            });
Sounds good I have made these changes.

2023-06-12 20:29 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +        }
At the moment, it will switch isApproval to true if the `keyBytes` is null, but it will not if there is an exception parsing the key. Should it set isApproval to true if there is an exception parsing the protobuf?

2023-06-13 13:45 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +              (upper(e.timestamp_range) > cr.consensus_timestamp or upper(e.timestamp_range) is null)
Excellent thanks, I have made that change

2023-06-15 13:32 UTC, jnels124 commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/converter/ObjectToStringSerializerTest.java
> +        verify(jsonGenerator).writeString("{\"id\":1,\"type\":\"unknown\"}");
Should maybe test with an object that contains snake case property

2023-06-15 16:22 UTC, closed without merging

2023-06-15 16:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +        }
Thanks, I have added this change to the new PR