HIP-584: Implement `AssociatePrecompile`
hashgraph/hedera-mirror-node pull request #6173
Opened 2023-06-09 12:00 UTC by IvanKavaldzhiev

**Description**:

Implementing `AssociatePrecompile` using `AsssociateLogic` from another PR.

**Related issue(s)**: #5648

Fixes #

**Notes for reviewer**:
Pricing logic is not fully implemented and incorrect. Missing test scenarios.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-14 07:12 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtilsTest.java
> +    private StackedStateFrames<Object> state;
Remove

2023-06-15 02:14 UTC, jnels124 commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/MultiAssociatePrecompile.java
> +        //        return pricingUtils.computeGasRequirement(blockTimestamp, this);
fix/remove

2023-06-15 02:14 UTC, jnels124 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                .isGreaterThanOrEqualTo((long) (expectedGasUsed * 1.05)) // expectedGasUsed value increased by 5%
should this adjustment be configurable?

2023-06-15 03:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +    private static final Logger log = LogManager.getLogger(HTSPrecompiledContract.class);
Shouldn't use lombok inside copied services code

2023-06-15 03:33 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/hapi/utils/contracts/ParsingConstants.java
> +        throw new UnsupportedOperationException("Utility class");
Shouldn't use lombok inside copied services code.

2023-06-16 16:04 UTC, xin-hedera approved these changes

2023-06-16 22:07 UTC, steven-sheehy requested changes

2023-06-19 06:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +        After the Precompile classes are implemented, this workaround won't be needed. */
We have an [epic](https://github.com/hashgraph/hedera-mirror-node/issues/5504).

2023-06-19 06:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/MultiAssociatePrecompile.java
> +        //        return pricingUtils.computeGasRequirement(blockTimestamp, this);
Removed

2023-06-19 06:28 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                .isGreaterThanOrEqualTo((long) (expectedGasUsed * 1.05)) // expectedGasUsed value increased by 5%
I think we have defined this offset between 5% and 20% as a best estimate ratio. Probably it's unlikely to change these values. If we need so, we can add configurable fields in a separate PR.

2023-06-19 06:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    EstimatorFactory estimatorFactory() {
I agree. We can create a new PR for this change.

2023-06-19 06:36 UTC, IvanKavaldzhiev commented on docs/configuration.md
> + `hedera.mirror.web3.evm.tokenAssociationsLimited`      | true                                               | Limits the number of token associations per account when true
Removed. It was previously removed, probably it appeared again after a merge conflict.

2023-06-19 06:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/CachingStateFrame.java
> +import org.checkerframework.checker.units.qual.K;
Removed

2023-06-19 06:50 UTC, 0xivanov reviewed
Looks good!

2023-06-19 06:50 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
> +public abstract class AbstractAssociatePrecompile implements Precompile {
Add `javadoc` and list the differences between this mirror-node vs services version of this class.

2023-06-19 06:50 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
> +    public RunResult run(MessageFrame frame, final Store store, final TransactionBody transactionBody) {
In services we invoke `validateSyntax` method on the `transactionBody` to check it's validity. We might need that validation here as well.

2023-06-19 06:50 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AssociatePrecompile.java
> +public class AssociatePrecompile extends AbstractAssociatePrecompile {
Add `javadoc`

2023-06-19 07:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AssociatePrecompile.java
> +public class AssociatePrecompile extends AbstractAssociatePrecompile {
Added

2023-06-19 07:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
> +    public RunResult run(MessageFrame frame, final Store store, final TransactionBody transactionBody) {
Added

2023-06-19 07:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
> +public abstract class AbstractAssociatePrecompile implements Precompile {
Added

2023-06-19 10:34 UTC, 0xivanov approved these changes
LGTM

2023-06-19 21:54 UTC, steven-sheehy approved these changes
LGTM

2023-06-19 21:55 UTC, merged