HIP-584: Add HederaTokenStore
hashgraph/hedera-mirror-node pull request #6174
Opened 2023-06-09 12:10 UTC by dikel

**Description**:
Copied HederaTokenStore from services for TransferLogic

**Related issue(s)**:

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-09 12:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +    @Inject
Remove this annotation, it's used in services by Dagger, but on mirror-node side this won't be needed

2023-06-09 12:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +        if (o instanceof FileID id) {
We don't need FileIDs in the Archive Node

2023-06-09 12:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +        if (o instanceof TopicID id) {
We don't need TopicIDs in the Archive Node

2023-06-09 12:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +        if (o instanceof ScheduleID id) {
We don't need ScheduleIDs in the Archive Node

2023-06-14 18:46 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
> +    @Inject
We don't need `@Singleton` and `@Inject` annotations in `com.hedera.services` package. If we need to define a bean we should do it in `EvmConfiguration`

2023-06-14 18:47 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
> +    public ResponseCodeEnum expiryStatusGiven(final StackedStateFrames<Object> stackedStateFrames, final AccountID id) {
We should adapt the new `Store` interface and replace each usage of `StackedStateFrames` with it.

2023-06-14 18:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            final var account = accountAccessor.get(id).orElseThrow(); // TODO: Change
When we start using the Store interface, fetching of different models would throw exception internally if we pass a suitable flag - OnMissing.THROW.

Here, however, we wouldn't want to throw an exception but in case the account is missing we can return `INVALID_ACCOUNT_ID`, so that we mimic the services validation workflow. We should aim to return proper `ResponseCodeEnum` values.

This deviation from the original code base, should be documented with a javadoc upon this method.

2023-06-14 19:00 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            var account = accountAccessor.get(aId).orElseThrow(); // TODO: change
I suggest to again return `INVALID_ACCOINT_ID` if the account is not found.

2023-06-14 19:06 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            final var tokenTreasury =
If the token is not found, we can return `INVALID_TOKEN_ID`

2023-06-14 19:08 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +    private void updateLedgers(
Change method name to `updateStore` and document in a javadoc that we are modifying a special in-memory state designed for mirror-node use.

2023-06-14 19:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +        final var toRelation = tokenRelationshipAccessor.get(toRel).orElseThrow(); // TODO: change
On all places where an object might be missing we can use the `Store` methods with a flag - `OnMissing.THROW` and this time throw an exception, since something is starting to get wrong. It's probably unlike to get such a scenario, since we have some validation checks in advance, but we should also handle some corner cases.

2023-06-14 19:11 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +        tokenRelationshipAccessor.set(toRel, newToRelation);
A lot of this logic would be simplified and easier to read, when we adopt the `Store`.

2023-06-14 19:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +        final var account = accountAccessor.get(aId).orElseThrow(); // TODO: change
Return `INVALID_ACCOUNT_ID`

2023-06-14 19:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +                tokenRelationshipAccessor.get(relationship).orElseThrow(); // TODO: change
Since we don't have a suitable `ResponseCode` we can return `INSUFFICIENT_TOKEN_BALANCE` in case the tokenRelationship is missing. All those changes in validation should be documented.

2023-06-14 19:28 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +        final var tokenRelationship =
We can return `TOKEN_NOT_ASSOCIATED_TO_ACCOUNT` in case tokenRel is missing.

2023-06-14 19:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
> +        final var account = accountAccessor.get(id).orElseThrow(); // TODO: change?
We can return INVALID_ACCOUNT_ID if the account is missing.

2023-06-26 11:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                kycKey,
kycKey should be from oldToken

2023-06-27 11:15 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                false);
Should't we use `oldAccount.isSmartContract` ?

2023-06-27 11:19 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/IdUtils.java
> +    public static TokenID asToken(String v) {
We have the same method in `EntityIdUtils` , please remove the `EntityIdUtils` duplicate.

2023-06-27 11:38 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +    public ResponseCodeEnum tryTokenChange(BalanceChange change) {
Unused

2023-06-28 11:35 UTC, dikel commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +    public ResponseCodeEnum tryTokenChange(BalanceChange change) {
`tryTokenChange()` will be used in `TransferLogic`

2023-06-28 12:46 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +                final var newAccount = account.setNumAssociations(numAssociations)
You can create a constructor, that takes `oldAccount`, `numAssociations`, `autoAssociationMetadata` and `alreadyUsedAutomaticAssociations` to avoid chaining multiple setters.

2023-06-28 13:07 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-06-29 03:04 UTC, steven-sheehy requested changes

2023-06-29 03:04 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return HashCodeBuilder.reflectionHashCode(this);
Shouldn't use reflective equals for performance reasons. Also, I'm not sure how you're using but it's usually better to not compare all fields and just compare the primary key.

2023-06-29 03:04 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/StoreImplTest.java
> +import com.hedera.mirror.web3.evm.store.accessor.*;
Please correct your IDE to flatten wildcard imports into explicit imports. Ivan has the Intellij instructions to apply.

2023-06-29 08:05 UTC, dikel commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    public boolean shouldAutoRenewSomeEntityType() {
It is used in services and we might need it in the future so I think it's better to leave it

2023-06-29 16:56 UTC, dikel commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return HashCodeBuilder.reflectionHashCode(this);
I changed the `hashCode` an `equals` methods but I found out that the `Account`, `Token` and `TokenRelationship` use reflective equals as well. Do you want me to change it?

2023-06-29 17:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return HashCodeBuilder.reflectionHashCode(this);
Yes, unless it's that way upstream in services.

2023-06-30 07:22 UTC, dikel commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/UniqueToken.java
> +        return HashCodeBuilder.reflectionHashCode(this);
They use `reflectionHashCode` and `reflectionEquals` in services

2023-06-30 11:42 UTC, 0xivanov submitted a review, later dismissed
LGTM, 
only fix the explicit imports and maybe suppress the sonar warning, as we have been doing this for copied logic from services.

2023-07-01 00:38 UTC, steven-sheehy approved these changes

2023-07-01 00:39 UTC, merged