Add Synthetic Contract Result for HTS operations via HAPI
hashgraph/hedera-mirror-node pull request #6187
Opened 2023-06-12 08:26 UTC by georgi-l95

**Description**:
This PR extends the synthetic event logs when operations on HTS tokens are performed via HAPI.
Add new class SyntheticContractResult which implementation takes care of the logging. 

Some informations is not logged in the contract result, as it's not possible to get it, but it's enough for the needed use cases.

**Related issue(s)**:

Fixes #5909 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-14 04:15 UTC, steven-sheehy requested changes

2023-06-14 04:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        new TransferContractResult(recordItem, entityTokenId, payerAccountId));
The function parameters are not really accurate in regards to ERC20 `transfer(address recipient, uint256 amount)`, right? They only include the signature but not the address or amount in the parameters. Is it not necessary to be 100% accurate since otherwise we'd have to have a 1:1 result to log?

2023-06-14 08:49 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        new TransferContractResult(recordItem, entityTokenId, payerAccountId));
Yes, you're correct, only the signature is correct. However, if we want to populate the other two fields, we'd need to get the necessary info from the `tokenTransferList` after they are done processing, because there can be only one contract result with the same consensus timestamp. So I've left it like this in favor to not burden the methods with additional logic for fetching this info or passing it along until they're completed. Would love to hear you're opinion. Just for more context, for the main use case - The Graph, this field is not so important. The Graph only cares for this contract result to exist and this transaction to have correct transaction hash, which later can be queried and logs can be fetched from the contract logs table.

2023-06-14 08:51 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +
I've possible yes, i think we should populated it, but I didn't find the correct info for it, so I've left it blank, for now. For context this field is not needed for our main use case - the graph, but i 100% think that we should strive to populate as many fields as we can with the correct info, regardless of are they used now by some tools or not.

2023-06-15 03:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +
Don't both transfer and approve just return a boolean? So you can just return `recordItem.isSuccessful()` after encoding it to hex. Which I think would always be true in these scenarios anyway.

2023-06-15 04:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        contractResult.setContractId(result.getEntityId().getId());
It's confusing since this isn't a contract ID, but a token ID. This will cause the REST API to have `/api/v1/contracts/{tokenId}/results/*` populated with this data. Hashscan or others could attempt to then lookup `{tokenId}` via `/api/v1/contracts/{tokenId}` and it won't return anything as it's not a contract and doesn't have bytecode.

Should we instead put the precompile address here since that is the "contract" being invoked? Of course, grouping them on precompile addresses is not ideal either and will cause an index imbalance. Will The Graph/relay will specifically lookup via `/api/v1/contracts/{tokenId}/results/*`?

2023-06-15 10:27 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        contractResult.setContractId(result.getEntityId().getId());
Do you mean 0x167 address? We don't invoke precompiles here, those are pure HAPI operations via the SDK. 
No, the graph or relay will only lookup `/api/v1/contracts/results` and filter by timestamp. Then from the response it gets the all `hash`es of those contract results and search one by one from another endpoint. Basiclly the graph only cares that they exist and have correct hash, nothing else.

2023-06-15 18:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        contractResult.setContractId(result.getEntityId().getId());
Xin pointed out we already have contract results for token precompiles, so no concern.

2023-06-16 17:19 UTC, xin-hedera requested changes

2023-06-16 17:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/AbstractSyntheticContractResult.java
> +@Data
add `@RequiredArgsConstructor` and remove the constructor

2023-06-16 17:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/AbstractSyntheticContractResult.java
> +    static final String APPROVE_SIGNATURE = "095ea7b3";
change these to `byte[]` and use `hexToBytes` to convert from the hex string. use the static byte array in concrete classes to avoid every time creates a new byte array

2023-06-27 11:38 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/AbstractSyntheticContractResult.java
> +@Data
Added.

2023-06-27 11:38 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/AbstractSyntheticContractResult.java
> +    static final String APPROVE_SIGNATURE = "095ea7b3";
Changed.

2023-06-27 11:38 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        contractResult.setTransactionResult(0);
Done.

2023-06-27 11:39 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        long consensusTimestamp = result.getRecordItem().getConsensusTimestamp();
Done.

2023-06-27 11:39 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +
Done.

2023-06-27 11:39 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +
Added.

2023-06-27 11:39 UTC, georgi-l95 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java
> +    protected SyntheticContractResultService syntheticContractResultService;
Done.

2023-06-27 11:39 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +
Done.

2023-06-29 03:24 UTC, steven-sheehy requested changes

2023-06-29 03:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (tokenTransferList.getNftTransfersCount() > 0) {
Remove these two new `if` checks since the guarded methods already have the same check internally.

2023-06-29 03:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        contractResult.setTransactionNonce(transactionBody.getTransactionID().getNonce());
nit: sort setters alphabetically and remove `gasLimit` variable

2023-06-29 14:26 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/contractresult/SyntheticContractResultServiceImpl.java
> +        contractResult.setTransactionNonce(transactionBody.getTransactionID().getNonce());
Sorted and removed.

2023-06-29 14:26 UTC, georgi-l95 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            if (tokenTransferList.getNftTransfersCount() > 0) {
Removed.

2023-06-29 14:41 UTC, steven-sheehy approved these changes
LGTM

2023-06-29 17:14 UTC, xin-hedera submitted a review, later dismissed

2023-06-29 17:27 UTC, steven-sheehy commented
merge conflict

2023-06-30 15:00 UTC, xin-hedera approved these changes

2023-06-30 16:04 UTC, steven-sheehy approved these changes

2023-06-30 16:04 UTC, merged