HIP-584: Provide implementation for transfer precompiles - Part2
hashgraph/hedera-mirror-node pull request #6199
Opened 2023-06-14 11:22 UTC by mustafauzunn

**Description**:

We need default implementations for precompiles related to transfer, so we should copy needed logic from hedera-services into hedera-mirror-web3.

**Related issue(s)**:

Fixes #5650 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-21 17:22 UTC, steven-sheehy requested changes

2023-07-21 17:22 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +    Address senderAddress;
This is a singleton bean so we can't have shared state within it.

2023-07-21 17:22 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +        return new TokenRelationshipKey(asTypedEvmAddress(tokenID), asTypedEvmAddress(accountID));
Nice catch

2023-07-25 13:06 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +    Address senderAddress;
Noted and fixed.

2023-07-26 06:30 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +            if (receiver.hasAlias()) {
Why remove the `!` operator?

2023-07-26 06:39 UTC, 0xivanov commented
While testing I discovered that in `TransferLogic.doZeroSum` we've missed the validation for allowances (`accountsLedger.validate(...)`. We should add them here or in separate PR

2023-07-26 11:31 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +        final var entityAddressSequencer =
Done.

2023-07-26 11:31 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
> +    public TransactionBody.Builder createCryptoTransfer(final List<TokenTransferWrapper> wrappers) {
Test added.

2023-07-26 11:31 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/ImpliedTransfers.java
> +    private final List<BalanceChange> changes;
Removed.

2023-07-26 11:31 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +                if (AbiConstants.ABI_ID_TRANSFER_TOKENS == functionId
Done.

2023-07-26 11:31 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +            if (receiver.hasAlias()) {
Checks are reworked.

2023-07-26 11:33 UTC, stoyanov-st commented
> While testing I discovered that in `TransferLogic.doZeroSum` we've missed the validation for allowances (`accountsLedger.validate(...)`. We should add them here or in separate PR

Allowance validation is added `adjust*Allowance()` methods in `TransferLogic`.

2023-07-26 12:24 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
>  public class TransferPrecompile extends AbstractWritePrecompile {
Add javadoc describing the changes compared to services.

2023-07-26 12:24 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
> +    private static void mergeFungible(final TokenTransferList.Builder from, final TokenTransferList.Builder to) {
codecov shows no coverage for this method

2023-07-27 05:33 UTC, 0xivanov submitted a review, later dismissed
Good Job!
LGTM

2023-07-28 02:04 UTC, steven-sheehy requested changes

2023-07-28 02:04 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +    private HederaTokenStore hederaTokenStore;
The HederaTokenStore is stateful since it's initialized per request and contains a Store.

2023-07-28 10:12 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
> +    private HederaTokenStore hederaTokenStore;
Done.

2023-07-28 20:41 UTC, steven-sheehy approved these changes
LGTM

2023-07-28 20:43 UTC, merged