6106 test eth call
hashgraph/hedera-mirror-node pull request #6200
Opened 2023-06-14 12:20 UTC by attest08

**Description**:

The PR includes the following new scenarios from the [eth_call test specification](https://www.notion.so/limechain/eth_call-Test-Plan-Specification-39d429564cd848bda9f58ba54a2dcb17) :
-Call feature
    I call function with IERC721Metadata token name
    I call function with IERC721Metadata token symbol
    I call function with IERC721Metadata token totalSupply
    I call function with IERC721 token balanceOf owner
    I call function with HederaTokenService isToken token
    I call function with HederaTokenService isFrozen token, account
    I call function with HederaTokenService isKyc token, account
    I call function with HederaTokenService getTokenDefaultFreezeStatus token
    I call function with HederaTokenService getTokenDefaultKycStatus token
-Precompile feature
  I call function with HederaTokenService getTokenCustomFees token - fractional fee and fixed fee - fungible token
  I call function with HederaTokenService getTokenCustomFees token - royalty fee
  I call function with HederaTokenService getTokenCustomFees token - royalty fee + fallback

2023-06-14 12:49 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private Path ercTestContract;
This will fail to be loaded when ran in a container. Need to use `Resource` instead of `Path` and get it as an InputStream in the createNewErcContract(). Check EstimateFeature file for reference.

2023-06-14 12:49 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private Path precompileTestContract;
Same goes for this `Path`, need to use `Resource`. (like the previous comment)

2023-06-14 12:51 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    @And("lower deviation is {int} and upper deviation is {int}")
nit: Add % in the text -> "lower deviation is {int}% and upper deviation is {int}%"

2023-06-14 18:56 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private int upperDeviation;
IDEA reports the above two int variables are assigned, in `setDeviations()`, but are never accessed. The only invocation of that method is in `call.feature`. It looks like fields with the same names are utilized in assertions within `EstimateFeature`. Does `CallFeature` require the same?

2023-06-14 19:15 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private String ERCContractAddress;
This looks like a class name.  Both `ercArtifacts` and `ercTestContract` set a good example. How about `ercContractAddress`?

2023-06-14 21:32 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(response.getResultAsNumber()).isEqualTo(0);
nit: use `.isZero()` instead

2023-06-14 21:32 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(response.getResultAsNumber()).isEqualTo(0);
nit: use .isZero() instead

2023-06-14 21:32 UTC, jnels124 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        assertThat(royaltyFee.get(3).toString()).isEqualTo(ZERO_ADDRESS);
use `assertThat(royaltyFee.get(3)).hasToString(ZERO_ADDRESS);` change 2 lines below as well.

2023-06-15 00:47 UTC, steven-sheehy requested changes

2023-06-15 00:47 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private static final String HTS_GET_TOKEN_DEFAULT_KYC_STATUS_SELECTOR = "fd4d1c26";
Prefer an enum

2023-06-15 16:10 UTC, steven-sheehy commented
Does this PR require any other HIP-584 open PRs be merged first for it to function?

2023-06-15 17:29 UTC, IvanKavaldzhiev commented
@steven-sheehy No, these tests are not dependant on any other open PR, since they require only `eth_call` functionality, which is already in place.

2023-06-15 18:03 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +import com.hedera.mirror.test.e2e.acceptance.client.*;
Still wildcard imports. The concern here is not this particular PR but more that your IDE settings are setup probably so it doesn't occur in the future. There's a `Use single class import` option in Intellij code style that should've been enabled after importing the palantir format XML.

2023-06-15 18:16 UTC, jascks approved these changes
LGTM

2023-06-16 07:09 UTC, yiliev0 approved these changes
LGTM

2023-06-16 08:16 UTC, natanasow approved these changes
LG

2023-06-16 16:05 UTC, merged