Nft transfer changes to read from transactions table.
hashgraph/hedera-mirror-node pull request #6208
Opened 2023-06-15 15:39 UTC by mgoelswirlds

**Description**:
Adding NFT transfers to transactions list API

This PR modifies

Transaction list API to read nft_transfers from transactions table
return token_transfers as empty array even if there are none

**Related issue(s)**:

Fixes #6011 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-15 15:42 UTC, xin-hedera commented
need to rename then fix this file: https://github.com/hashgraph/hedera-mirror-node/blob/6011-Transactions-List-Api-Nft-Transfers/hedera-mirror-rest/__tests__/specs/transactions/duplicate-token-transfers-bug.json_

2023-06-16 18:36 UTC, mgoelswirlds commented on hedera-mirror-rest/api/v1/openapi.yml
> +        nft_transfers:
Added this , since it was missing from the transactions response.

2023-06-16 18:36 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +const getNftTransfers = (nftTransferList) => {
Renaming the method since we are only getting the Nft transfers now, not creating a list.

2023-06-16 19:16 UTC, MarcKriguerAtHedera approved these changes
A huge amount of this looks very familiar -- hope that (now that I merged my PR into the destination branch) this PR will look smaller.

2023-06-16 19:16 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        nft_transfers:
Nice.

2023-06-16 19:23 UTC, xin-hedera requested changes

2023-06-16 19:23 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        nft_transfers:
make sure you remove the `TransactionDetail` and any reference to it since TransactionDetail already has the `nft_transfers` array

2023-06-16 19:23 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const getNftTransfers = (nftTransferList) => {
prefer to revert the changes, keep it consistent with other create*List functions

2023-06-16 19:23 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/account-id.json
> +        "nft_transfer": []
just want to point out these empty arrays (`nft_transfer` and `token-transfers`) in the `setup` section are not needed. ok to keep them as is

2023-06-16 19:23 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/no-transfers.json
> +{
remove, there is already a `timestamp-no-transfers.json`, so should not create a new one

2023-06-16 19:25 UTC, mgoelswirlds commented on hedera-mirror-rest/api/v1/openapi.yml
> +        nft_transfers:
I don't understand what this means.

2023-06-16 19:40 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const getNftTransfers = (nftTransferList) => {
strictly speaking, we can still call it `create`, since we still do db data -> model -> view model conversions

2023-06-16 19:53 UTC, steven-sheehy commented on .cache/act/docker-setup-qemu-action@v2
Remove this file and folder

2023-06-16 20:20 UTC, xin-hedera requested changes

2023-06-16 20:20 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +              - serial_number
every field is required
```suggestion
              - is_approval
              - receiver_account_id
              - sender_account_id
              - token_id
              - serial_number
```

2023-06-16 20:45 UTC, xin-hedera approved these changes
LGTM

2023-06-16 20:46 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/nft-transfers.json
> +          }
these should be reverted, since it's a duplicate. I can clean it up when merge the 4099 branch to `main`

2023-06-16 20:51 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/transactions/nft-transfers.json
> +          }
Ahh merge conflicts. Thanks will merge it for now.

2023-06-16 20:53 UTC, merged