Change /transactions/{id} to use nested NFT transfers
hashgraph/hedera-mirror-node pull request #6212
Opened 2023-06-15 19:02 UTC by MarcKriguerAtHedera

**Description**:
Description:
This PR modifies the `getTransactionQuery` method of `transactions.js` to get the **nft_transfer** list directly from the nested `nft_transfer` column of the `transaction` table, rather than querying the now-obsolete `nft_transfer` table.

* Change `createNftTransferList()` to a return an empty array (instead of **undefined**) on empty input.
* Change `createTokenTransferList()` the same way.

**Related issue(s)**:

Fixes #6009 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-06-15 19:14 UTC, MarcKriguerAtHedera commented
There is currently a rest test failing in the parent branch (@mgoelswirlds is running into it as well) that is not impacted by the files changed in this PR.

2023-06-15 21:24 UTC, xin-hedera requested changes

2023-06-15 21:24 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
the subquery should be removed completely, and replace by just the new jsonb column `${Transaction.NFT_TRANSFER}`

2023-06-15 21:46 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
I originally did this, but now did need to restore a `jsonb_agg` call (and so I don't know if we can remove the "from transaction" from that).

2023-06-15 21:50 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
I don't think that's the type of fix we want

2023-06-15 21:58 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
All the "nonce" tests were failing (and I had to set the number of jest workers to 1 just to see the error message) about "with" needing to return a single value.

2023-06-15 22:03 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
Please make the change Xin suggested. jsonb_agg is not needed nor is a subquery. And remove `nftTransferJsonAgg` and your MYK logs.

2023-06-16 00:33 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
I removed the two logging lines; if I make the change that Xin requested, all of the various "nonce" transaction tests will fail with
```
ERROR:  more than one row returned by a subquery used as an expression
```
when we limit jest to a single worker, or
```
  ● Test suite failed to run

    TypeError: Do not know how to serialize a BigInt
        at stringify (<anonymous>)

      at messageParent (node_modules/jest-worker/build/workers/messageParent.js:29:19)
```
with multiple jest workers.

I certainly can eliminate `nftTransferJsonAgg` and just copy the two lines into the query, but I want to resolve the above error first (I think if we resolve it with something like `limit 1` we will not be returning the proper results).

2023-06-16 00:43 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
I don't think you understand Xin's suggestion. Remove the entire `(.*) as nft_transfer_list`.

2023-06-16 00:51 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
>      ) as nft_transfer_list,
to further clarify

- remove the whole subquery `(.*) as nft_transfer_list`
- add `${Transaction.NFT_TRANSFER}` to the `transactionFields` array
- rename any reference like `row.nft_transfer_list` to `row.nft_transfer`
- fix any errors you see in the spec tests result

2023-06-16 15:40 UTC, xin-hedera requested changes

2023-06-16 15:40 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +      nft_transfers: createNftTransferList(row.nft_transfer),
`createNftTransferList` should return empty array `[]` if `!row.nft_transfer` is true

same for `createTokenTransferList`

2023-06-16 17:43 UTC, MarcKriguerAtHedera commented on hedera-mirror-rest/transactions.js
> +      nft_transfers: createNftTransferList(row.nft_transfer),
I had replaced
```
return undefined;
```
with `return [];` in both those functions; somehow, when I created a new workspace, those changes did not get
copied over.  Those two lines are restored now (and the necessary spec tests tweaked to reflect this).

2023-06-16 17:55 UTC, steven-sheehy approved these changes
LGTM

2023-06-16 17:56 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +      nft_transfers: createNftTransferList(row.nft_transfer),
I seem to have exactly all these changes.

2023-06-16 17:57 UTC, mgoelswirlds commented
I see that we have all common code and we made changes to the exact same files. LGTM, I will pull your code and then send out my PR.

2023-06-16 17:57 UTC, mgoelswirlds approved these changes

2023-06-16 18:25 UTC, xin-hedera approved these changes
LGTM

2023-06-16 18:43 UTC, merged