HIP-584: Charge proper gas for lazy created account
hashgraph/hedera-mirror-node pull request #6213
Opened 2023-06-16 11:05 UTC by 0xivanov

**Description**:  

In order to achieve proper eth_estimateGas in all scenarios, we need to charge the gas needed to lazy create an account.

**Related issue(s)**:

Fixes #5596

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-19 08:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/state/submerkle/SequenceNumber.java
> +public class SequenceNumber {
Use `EntityAddressSequencer` and delete copied services logic related to sequence numbers.

2023-06-19 10:36 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/ledger/ids/SeqNoEntityIdSource.java
> +public class SeqNoEntityIdSource implements EntityIdSource {
Fixed

2023-06-22 21:16 UTC, steven-sheehy requested changes

2023-06-22 21:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessor.java
> +        final EntityAddressSequencer ids = new EntityAddressSequencer();
This object is declared a bean but here you're creating it manually. Using it like this means it will always return the same value for every create inside the same request, instead of properly incrementing.

2023-06-22 21:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    private final AtomicLong accountIds = new AtomicLong(0);
We should not have a separate counter for accountIds since all entities are supposed to share the same counter. This would differ from consensus nodes. Think we should remove this and just use `entityIds` for accounts.

2023-06-23 05:13 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/EntityAddressSequencer.java
> +    private final AtomicLong accountIds = new AtomicLong(0);
Fixed

2023-06-23 05:13 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessor.java
> +        final EntityAddressSequencer ids = new EntityAddressSequencer();
Fixed

2023-06-23 12:19 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessor.java
>  public class MirrorEvmMessageCallProcessor extends HederaEvmMessageCallProcessor {
You can add a javadoc noting that `executeLazyCreate` is copied from `hedera-services`.

We should think of a way to abstract this logic from `hedera.mirror.web3.evm` package. Probably we can introduce an interface that serves as an adapter, as we did for HTSPrecompiledContract. I believe this can be done in a separate PR.

2023-06-23 12:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    private TransactionBody.Builder createHollowAccount(final ByteString alias, final long balance) {
Add javadoc that this method is copied from `SyntheticTxnFactory`. Once we introduce `SyntheticTxnFactory` we can copy all creation methods like this - there.

2023-06-24 03:28 UTC, steven-sheehy commented
Tests are failing

2023-06-26 06:56 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    private TransactionBody.Builder createHollowAccount(final ByteString alias, final long balance) {
Fixed

2023-06-26 06:56 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessor.java
>  public class MirrorEvmMessageCallProcessor extends HederaEvmMessageCallProcessor {
Fixed

2023-06-26 17:15 UTC, xin-hedera approved these changes
LGTM

2023-06-26 18:14 UTC, steven-sheehy approved these changes
LGTM

2023-06-26 18:15 UTC, merged