Make the *prune* SQL from history repositories more efficient.
hashgraph/hedera-mirror-node pull request #6216
Opened 2023-06-16 22:06 UTC by MarcKriguerAtHedera

**Description**:
This PR slightly edits the SQL for the `prune` queries, and alters the existing indices.
* Change the SQL query in each HistoryRepository to use "int8range(?1, null)"
* Add a bew btree index including lower(timestamp_range)
* Add a new GIST index on token_account_history.

**Related issue(s)**:

Fixes #6195 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-06-16 22:51 UTC, steven-sheehy requested changes

2023-06-16 22:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +-- create new btree index on loswer(timestamp_range) for each of the above, and also for token_account_history
```suggestion
-- create new btree index on lower(timestamp_range) for each of the above
```

2023-06-16 22:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on token_allowance_history (owner, spender, lower(timestamp_range));
Don't add any btree indexes for any tables, just update the current _pk indexes to lower the timestamp_range

2023-06-16 22:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +alter table token_allowance_history   drop constraint token_allowance_history_pkey;
It's more direct to just drop the index instead of altering the table.

2023-06-16 22:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +create index if not exists crypto_allowance_history__owner_spender__lower_timestamp
These should be named the same as the previous. Or in fact we should probably make them the same as in v2 with __pk

2023-06-16 22:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +  on token_allowance_history (owner, spender, lower(timestamp_range));
Both missing token_id. Should fix v2 then just copy it here.

2023-06-16 22:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
If this is going in 0.83 it should be a 0.81.something

2023-06-17 00:08 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +-- create new btree index on loswer(timestamp_range) for each of the above, and also for token_account_history
Done.

2023-06-17 00:09 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on token_allowance_history (owner, spender, lower(timestamp_range));
OK, I have removed these.  The second bullet of the ticket requested them, but as I am now adding them as a new constraint, these may no longer be needed.

2023-06-17 00:10 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +alter table token_allowance_history   drop constraint token_allowance_history_pkey;
The ticket specifically requests that it be done this way.  Now each "alter table" has a "drop constraint" and an "add constraint" to go with it.

2023-06-17 00:10 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +create index if not exists crypto_allowance_history__owner_spender__lower_timestamp
Done.

2023-06-17 00:10 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +  on token_allowance_history (owner, spender, lower(timestamp_range));
Done (in v2 first then copied here, as requested).

2023-06-17 00:12 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
ok.  I know they are not in `main` yet (just the `4099-nested-nft-transfers` branch), but I was aware of a couple of V1.81... migration files there, so I thought it made sense to start with V1.82.  But those will probably get renamed to V1.82 in that branch before getting merged back into `main`.

2023-06-17 01:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +alter table token_allowance_history   drop constraint token_allowance_history_pkey;
Latest revision -- drop the constraint (as the ticket requests), then add an index on (among other fields) `lower(timestamp_range)`, which is not allowed as part of the `primary key` constraint.

2023-06-18 03:34 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    on token_allowance_history (owner, spender, lower(timestamp_range));
This is not done. I said don't add **any** btree index for **any** tables. Even worse you're now incorrectly replacing a gist index. V1 and V2 indexes should be identical for these tables.

2023-06-18 03:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +create index if not exists crypto_allowance_history__owner_spender__lower_timestamp
Names still don't match index names in v2.

2023-06-18 03:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
This migration should be named after the ones in 4099-nested-nft-transfers

2023-06-20 14:20 UTC, xin-hedera requested changes

2023-06-20 14:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/CryptoAllowanceHistoryRepository.java
> +    @Query(nativeQuery = true, value = "delete from crypto_allowance_history where timestamp_range << int8range (?1, null)")
nit, remove the extra space

```suggestion
    @Query(nativeQuery = true, value = "delete from crypto_allowance_history where timestamp_range << int8range(?1, null)")
```

2023-06-20 14:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.81.0__make_history_indices_more_efficient.sql
> +
add a gist index on token_account_history (timestamp_range)

2023-06-20 14:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +create index if not exists entity_history__id_lower_timestamp on entity_history (id, lower(timestamp_range));
remove *_history__pk

2023-06-20 14:21 UTC, xin-hedera requested changes

2023-06-20 14:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.81.0__make_history_indices_more_efficient.sql
> +-- drop primary key constraints and replace with new indices based on lower(timetamp_range) which can't be primary key
V1.81.2

2023-06-20 16:39 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
> +create index if not exists crypto_allowance_history__owner_spender__lower_timestamp
The names now should match the names in the v2 file.    (Again, please let me know if you see a difference.)

2023-06-20 16:39 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__make_history_indices_more_efficient.sql
Done.

2023-06-20 16:40 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/CryptoAllowanceHistoryRepository.java
> +    @Query(nativeQuery = true, value = "delete from crypto_allowance_history where timestamp_range << int8range (?1, null)")
Done (for all 5 Java files).

2023-06-20 16:40 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.81.0__make_history_indices_more_efficient.sql
> +
Done.

2023-06-20 16:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +create index if not exists entity_history__id_lower_timestamp on entity_history (id, lower(timestamp_range));
Done.

2023-06-20 16:42 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.81.0__make_history_indices_more_efficient.sql
> +-- drop primary key constraints and replace with new indices based on lower(timetamp_range) which can't be primary key
Renamed.

2023-06-20 16:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.81.0__make_history_indices_more_efficient.sql
> +-- drop primary key constraints and replace with new indices based on lower(timetamp_range) which can't be primary key
did you push commits to remote repo?

2023-06-20 17:04 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.81.0__make_history_indices_more_efficient.sql
> +-- drop primary key constraints and replace with new indices based on lower(timetamp_range) which can't be primary key
Yes, about 2 minutes ago.  Please check again.

2023-06-20 18:37 UTC, xin-hedera approved these changes
LGTM

2023-06-20 19:06 UTC, steven-sheehy approved these changes
LGTM

2023-06-20 19:11 UTC, merged