HIP-584: Add tests for estimateGas with precompiles
hashgraph/hedera-mirror-node pull request #6241
Opened 2023-06-20 13:39 UTC by yiliev0

**Description**: This PR is in early stage and contains tests related to `eth_estimateGas` with precompiles. It covers tests related to `associate`, `dissociate`, `approve`, `transfer` precompiles.

**Related issue(s)**:

Fixes #6109

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-03 07:47 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public static boolean isWithinDeviation(int actualUsedGas, int estimatedGas, int lowerBoundPercent,
We can create a parent class for `EstimateFeature` and `EstimatePrecompileFeature`, called `EstimateAbstractFeature` and extract the common fields and methods like `isWithinDeviation`, `setDeviations`, etc.

2023-08-10 09:16 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public static boolean isWithinDeviation(int actualUsedGas, int estimatedGas, int lowerBoundPercent,
Done! Thanks for the advice.

2023-08-26 03:34 UTC, steven-sheehy requested changes
Still reviewing large file

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimate.feature
> -    Then I call estimateGas with function that executes reentrancy attack with transfer
Should also remove the corresponding `@Then` method if it's no longer used.

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        return response;
Add a log similar to the other methods showing an associate transaction occurred.

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/TestUtil.java
> +    public static byte[][] asHeadlongByteArray(List<String> hexStringList) {
Prefer not to have methods named after specific libraries in use as things may change. Can remove `Headlong` from name.

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
Not used.
```suggestion
```

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
>      private final MirrorNodeClient mirrorClient;
Duplicated from parent.

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +#    Then I call estimateGas with mintToken function for NFT - disabled due to bug
What bug # and is someone working on a fix?

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        createTokenWithCustomFees(1);
Tokens are very expensive to create and we should reuse them across tests. Change all token creates in this PR to use `TokenClient.getToken()` so it creates once and caches it.

2023-08-26 03:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private final List<TokenId> tokenIds = new ArrayList<>();
Tokens aren't being cleaned up properly. Remove this list and use TokenClient.getToken() to create so that it auto cleans up.

2023-08-28 14:31 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimate.feature
> -    Then I call estimateGas with function that executes reentrancy attack with transfer
Done.

2023-08-28 14:34 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/TestUtil.java
> +    public static byte[][] asHeadlongByteArray(List<String> hexStringList) {
Removed headlong from all occurrences.

2023-08-28 14:34 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
Done.

2023-08-28 14:35 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +#    Then I call estimateGas with mintToken function for NFT - disabled due to bug
Added the bug # in the feature file. The #6769 is and currently it's being worked on.

2023-08-28 21:02 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        createTokenWithCustomFees(1);
This sounds reasonable, except that the needed info should just be added to the TokenNameEnum. Then you don't need steps 2 and 3.

```java
public enum TokenNameEnum {
    FUNGIBLE("fungible", TokenType.FUNGIBLE_COMMON, TokenKycStatus.KycNotApplicable),
    NFT("non_fungible", TokenType.NON_FUNGIBLE_UNIQUE, TokenKycStatus.KycNotApplicable),
    FUNGIBLE_KYC("fungible_kyc", TokenType.FUNGIBLE_COMMON, TokenKycStatus.Granted),
    NFT_KYC("nft_kyc", TokenType.NON_FUNGIBLE_UNIQUE, TokenKycStatus.Granted);
}
```

Then call `tokenNameEnum.getKycStatus().getNumber()` instead create token.

2023-08-30 12:18 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private final List<TokenId> tokenIds = new ArrayList<>();
Done.

2023-08-30 12:22 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        createTokenWithCustomFees(1);
@steven-sheehy Implemented. There was also a need to add `TokenFreezeStatus.Unfrozen` for the 'freeze` & `unfreeze` precompile tests. Other than that the tests now fully use the caching mechanism from the TokenClient. Thanks for your input, I appreciate it.

2023-08-30 12:22 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +#    Then I call estimateGas with mintToken function for NFT - disabled due to bug
The bug is now resolved in https://github.com/hashgraph/hedera-mirror-node/pull/6779 and I've enabled the test back again with the needed changes.

2023-08-31 03:45 UTC, steven-sheehy requested changes

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        return response;
Not done

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +            compiledEstimatePrecompileSolidityArtifacts = MAPPER.readValue(in, CompiledSolidityArtifact.class);
Seems like a good candidate to move both the `MAPPER` and the readValue call to a common area for reuse and change every place in the PR that uses it. As noted in another comment, we should pull `createContract` up to AbstractFeature and change it so it takes in an InputStream. Then this mapper logic can be centralized there.

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        deployedEstimatePrecompileContract = createContract(compiledEstimatePrecompileSolidityArtifacts, supply);
This seems to be creating two duplicate contracts.

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        deployedErcTestContract = createContract(compiledErcTestContractSolidityArtifacts, supply);
Created twice

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        deployedPrecompileContract = createContract(compiledPrecompileContractSolidityArtifacts, supply);
Contracts are also expensive to create and we seem to now be creating the same contract in multiple features. We should either combine these into one feature as multiple scenarios (though I can't recall if different scenarios share class instances) or implement a caching mechanism for `ContractClient.createContract`. Can maybe be a follow up.

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Given I successfully non fungible tokens
This is an incomplete sentence. I successfully _do what_ to a non-fungible token?

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimateGas with associate function for fungible token
There's a race condition here where some or all of these HAPI calls might not have made their way to mirror node before the first web3 call. Need to add a wait for transaction REST API for last HAPI transaction (mint) before proceeding to web3 calls.

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private DeployedContract createContract(CompiledSolidityArtifact compiledSolidityArtifact, int initialBalance) {
Some of these methods like `createContract`, `persistContractBytes`, and `verifyCreateContractNetworkResponse ` are duplicated code from other features. We should pull these common methods up to `AbstractFeature` instead of continuing to duplicate them.

2023-08-31 03:45 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        String json = getAbiFunctionAsJsonString(compiledPrecompileContractSolidityArtifacts, functionName);
Prefer these take in a `ContractMethods` enum so they're strongly typed and don't have to call `getFunctionName()` everywhere.

2023-08-31 06:12 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        return response;
Now it should be okay.

2023-08-31 15:09 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        String json = getAbiFunctionAsJsonString(compiledPrecompileContractSolidityArtifacts, functionName);
These are now taking ContractMethods enum and removed getFunctionName() from everywhere else.

2023-08-31 15:10 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private DeployedContract createContract(CompiledSolidityArtifact compiledSolidityArtifact, int initialBalance) {
Moved all of these methods in `AbstractFeature` class . Refactored all of the Feature files that were exposed to the same methods and pointed them to use only the ones from `AbstractFeature`.

2023-08-31 15:12 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimateGas with associate function for fungible token
I've taken out all out of the HAPI transactions -> associate, approve and etc. to a seperate `@AND` clause and verified that they reached the mirror node with a second follow up method that uses `verifyMirrorTransactionsResponse`

2023-08-31 15:15 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        deployedPrecompileContract = createContract(compiledPrecompileContractSolidityArtifacts, supply);
@steven-sheehy I agree. In fact, I've already discussed with @IvanKavaldzhiev and @attest08 that we should do something similar to the Accounts and Tokens and implement a similar mechanism for caching that would be used across all tests. This can be handled in a separate task and I can open an issue/ticket to keep it tracked.

2023-08-31 15:16 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        deployedEstimatePrecompileContract = createContract(compiledEstimatePrecompileSolidityArtifacts, supply);
Removed the duplicated creation.

2023-08-31 15:18 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +            compiledEstimatePrecompileSolidityArtifacts = MAPPER.readValue(in, CompiledSolidityArtifact.class);
I have moved the `MAPPER` into a `MapperConfiguration` class and I have changed the `createContract` in `AbstractFeature` to take InputStream instead. Removed all occurrences of the mapper from the feature files. Thanks for the advise.

2023-08-31 15:19 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                .getToken(TokenClient.TokenNameEnum.valueOf("FUNGIBLE_KYC_UNFROZEN"))
Changed to use the enum directly. Thanks.

2023-08-31 15:20 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +@contractbase @fullsuite @estimateprecompile @web3
Done.

2023-08-31 21:28 UTC, steven-sheehy requested changes

2023-08-31 21:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
>      private final ContractClient contractClient;
Can remove

2023-09-01 10:23 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
>      private final ContractClient contractClient;
Removed.

2023-09-01 10:24 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private final ContractClient contractClient;
Removed.

2023-09-01 10:24 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
>      private final ContractClient contractClient;
Removed.

2023-09-01 10:25 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
>      private final ContractClient contractClient;
Removed.

2023-09-01 10:25 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
>      private final FileClient fileClient;
Removed.

2023-09-01 10:25 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
>          try (var in = ercTestContract.getInputStream()) {
Done.

2023-09-01 10:29 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/MapperConfiguration.java
> +package com.hedera.mirror.test.e2e.acceptance.config;
Now it should be okay, I will watch next commits if it runs automatically. Thanks for the advise!

2023-09-01 12:32 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +    protected ObjectMapper mapper;
Hi @steven-sheehy. After attempting to implement this, I ran into an issue with Lombok. Lombok does not automatically generate the correct constructor with `super(Required args for parent class)` in the child class when using `@RequiredArgsConstructor` . While researching I also found [this](https://stackoverflow.com/a/29771875) answer in stackoverflow. Do you have any ideas or we can keep the `@Autowired` annotations? Thanks in advance!

2023-09-01 16:09 UTC, steven-sheehy approved these changes
LGTM. Thanks for doing the extra cleanup to reduce duplication!

2023-09-01 16:09 UTC, merged