HIP-584: Provide implementation for create token logic
hashgraph/hedera-mirror-node pull request #6242
Opened 2023-06-20 13:59 UTC by mustafauzunn

**Description**:

We need default implementations for precompiles related to creation of a new token, so we should copy needed logic from hedera-services into hedera-mirror-web3.

**Related issue(s)**:

Fixes #6340 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-07-03 07:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int maxCustomFeesAllowed = 10;
Sort alphabetically and add this property in docs/configuration.md

2023-07-03 07:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/CreateLogic.java
> +public class CreateLogic {
We should make the Logic type a stateless bean and add javadoc, documenting what are the differences compared to `hedera-services` repo.

2023-07-05 12:30 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/CreateLogic.java
> +public class CreateLogic {
Done

2023-07-05 18:09 UTC, steven-sheehy requested changes

2023-07-05 18:51 UTC, steven-sheehy commented
Does this fix https://github.com/hashgraph/hedera-mirror-node/issues/5649 ? I marked it as fixing, so please fix to the correct one if not.

2023-07-05 19:30 UTC, IvanKavaldzhiev commented
There wasn't an issue created, so I created a suitable one.

2023-07-06 20:43 UTC, steven-sheehy approved these changes
LGTM just need to merge to fix conflicts

2023-07-07 08:38 UTC, IvanKavaldzhiev approved these changes

2023-07-07 18:15 UTC, merged