Reduce the amount of data persisted for rosetta
hashgraph/hedera-mirror-node pull request #6243
Opened 2023-06-20 19:33 UTC by MarcKriguerAtHedera

**Description**:
This PR reduces the amount of data to be persisted (for rosetta).

* update `supervisord.conf` to disable `contracts`, `contractResults`, `files`, `schedules`, `syntheticContractLogs`, `systemFiles`, `tokens`, and `topicMessageLookups` in importer persist config
* add a custom `application.yml` to `/app/importer` to override `spring.flyway.locations="classpath:db/migration/v1,filesystem:/app/importer/sql"`
* Modify `hedera-mirror-rosetta/container/Dockerfile` to include that `application.yml` file in the `/app/importer` directory.
* Add a `V1.78.99__truncate_tables_for_rosetta.sql ` migration to truncate 23 specified tables.

**Related issue(s)**:

Fixes #6149 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-06-20 20:14 UTC, xin-hedera requested changes

2023-06-20 20:14 UTC, xin-hedera commented on hedera-mirror-rosetta/app/importer/application.yml
> +spring:
move the file to `hedera-mirror-rosetta/container/importer`

2023-06-20 20:14 UTC, xin-hedera commented on hedera-mirror-rosetta/container/Dockerfile
> +    && cp /hedera-mirror-node/hedera-mirror-rosetta/app/importer/application.xml ./importer \
revert

2023-06-20 20:14 UTC, xin-hedera commented on hedera-mirror-rosetta/container/Dockerfile
>      && cp /hedera-mirror-node/hedera-mirror-rosetta/container/* . \
```suggestion
    && cp -r /hedera-mirror-node/hedera-mirror-rosetta/container/* . \
```

2023-06-20 20:14 UTC, xin-hedera commented on hedera-mirror-rosetta/container/supervisord.conf
> +  HEDERA_MIRROR_IMPORTER_PARSER_RECORD_ENTITY_PERSIST_FILES=false,
add `HEDERA_MIRROR_IMPORTER_PARSER_RECORD_ENTITY_PERSIST_ETHEREUM_TRANSACTIONS=false`

2023-06-20 21:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.78.99__truncate_tables_for_rosetta.sql
> +-- truncate tables not needed by rosetta
I had wondered how the importer would (normally) skip over it, but I hadn't seen any sort of equivalent migration files under hedera-mirror-rosetta.  Anyway, I have moved it there, and changed "cp" to "cp -r" inside the Docker file, so that the file will be in the image under `/app/importer/sql/V1.78.99__truncate_tables_for_rosetta.sql` .

2023-06-20 21:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.78.99__truncate_tables_for_rosetta.sql
> +truncate nft_allowance;
Added.

2023-06-20 21:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/app/importer/application.yml
> +spring:
Moved.

2023-06-20 21:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/container/Dockerfile
> +    && cp /hedera-mirror-node/hedera-mirror-rosetta/app/importer/application.xml ./importer \
Yes, with the "cp -r" that line is no longer needed.  Removed.

2023-06-20 21:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/container/Dockerfile
>      && cp /hedera-mirror-node/hedera-mirror-rosetta/container/* . \
Done.

2023-06-20 21:21 UTC, MarcKriguerAtHedera commented on hedera-mirror-rosetta/container/supervisord.conf
> +  HEDERA_MIRROR_IMPORTER_PARSER_RECORD_ENTITY_PERSIST_FILES=false,
Added.

2023-06-21 15:22 UTC, MarcKriguerAtHedera commented
Waiting for a new release before merging, but this can be opened up for the rest of the team to review before then.

2023-06-22 18:43 UTC, steven-sheehy approved these changes

2023-06-22 18:45 UTC, xin-hedera approved these changes
LGTM

2023-06-22 19:24 UTC, merged