Support token history
hashgraph/hedera-mirror-node pull request #6246
Opened 2023-06-21 17:18 UTC by steven-sheehy

**Description**:

* Add `List`, `Range` and `EntityId` types to global setup to avoid per domain annotations
* Add a `token_history` table
* Add an `@Upsertable(skipPartialUpdate)` property to skip updates without an existing row
* Change `token.modified_timestamp` to `token.timestamp_range`
* Change `/api/v1/tokens` to use `timestamp_range`
* Fix not merging `token.fee_schedule_key` properly
* Fix not setting `updatable=false` on `TokenAccount.createdTimestamp`
* Fix not including `nft_history` in pg_partman maintenance

**Related issue(s)**:

Fixes #6111

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-06-22 18:36 UTC, xin-hedera requested changes

2023-06-22 21:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Done

2023-06-22 21:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            batchPersister.persist(tokens);
Done

2023-06-22 21:14 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/package-info.java
> +@ConverterRegistration(converter = UnknownIdConverter.class)
Done

2023-06-22 21:14 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAccount.java
> +    @Column(updatable = false)
Done

2023-06-23 15:16 UTC, xin-hedera approved these changes
LGTM

2023-06-23 17:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchInserterTest.java
> +    private final TransactionRepository transactionRepository;
Removed

2023-06-23 17:48 UTC, jnels124 approved these changes

2023-06-23 17:52 UTC, merged