Limit the number of concurrent signature file downloads
hashgraph/hedera-mirror-node pull request #6254
Opened 2023-06-22 21:47 UTC by MarcKriguerAtHedera

**Description**:
This PR limits the number of concurrent signaturefile downloads.
* Add config property `hedera.mirror.importer.downloader.downloadRatio` property
* Have default value of new property set to `consensusRatio` + 15%
* Add code to `Downloader`enhanced to use the property to limit concurrent signature list operations
* Randomize list of nodes (so that it generates a random list of files to download each time)

**Related issue(s)**:

Fixes #6130 

**Notes for reviewer**:
Performance (on demonet) on grafana before this change:
* "Download Stream Signature Rate" capped at 0.500 requests per second.
* "Download Stream Signature Latency" capped around 0.09 seconds.

Performance after this change:
* being measured

**Checklist**

- [x] Documented (Code comments)
- [x] Tested (unit, integration, etc.)

2023-06-23 13:52 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +
Should the new property be added to `docs/configuration.md`?

2023-06-23 19:24 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +
Yes, done.  Thanks for catching this!

2023-06-26 14:13 UTC, edwin-greene commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.downloadRatio`                           | 0.48333333333                  | The ratio of nodes (or stake) to be concurrently downloaded to verify signatures) to t
nit, typo extra `)`:  `to verify signatures)`

2023-06-26 14:53 UTC, xin-hedera requested changes

2023-06-26 17:17 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.downloadRatio`                           | 0.48333333333                  | The ratio of nodes (or stake) to be concurrently downloaded to verify signatures) to t
Fixed.  Thanks again!

2023-06-26 17:17 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +     * (Note: when the downloadRatio = BigDecimal.ONE, this will just randomly reorder the whole list).
Agreed.  Updated the code to reflect this.  Also removed the comment (no longer necessary).

2023-06-26 17:18 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        if (nodes == null || nodes.size() <= 1) {
It would only be null if someone else was calling this method with a null value.  I agree this isn't needed -- removed.

2023-06-26 17:19 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +    private BigDecimal downloadRatio = BigDecimal.ONE.min(consensusRatio.add(new BigDecimal("0.15"), MATH_CONTEXT));
Done.  All logic to initial `downloadRatio` moved to the `init()` method.

2023-06-26 17:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        if (nodes == null || nodes.size() <= 1) {
fyi, a null `allNodes` would cause NPE in ArrayList constructor

2023-06-26 17:22 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        if (nodes == null || nodes.size() <= 1) {
If someone (explicitly) passes in `null` and causes this NPE, I think the NPE is the correct behavior.  When the code is just being called by the Downloader, this should not occur.

2023-06-26 18:04 UTC, xin-hedera requested changes

2023-06-26 18:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        BigDecimal neededStake = BigDecimal.valueOf(nodes.get(0).getTotalStake()).multiply(downloadRatio);
I think we should get the long value of `neededStake` with `RoundingMode.CEILING` so we can avoid aggregating `BigDecimal` aggreatedStake

 ```suggestion
        long neededStake = BigDecimal.valueOf(nodes.get(0).getTotalStake())
          .multiply(downloadRatio)
          .setScale(0, RoundingMode.CEILING)
          .longValue();
```

2023-06-26 18:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +            downloadRatio = downloadRatio.max(consensusRatio);
prefer to throw an exception instead of capping the value set by user

2023-06-26 20:58 UTC, steven-sheehy requested changes

2023-06-26 21:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        }
Done.

2023-06-26 21:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                aggregateStake, nodes.get(0).getTotalStake());
Done.

2023-06-26 21:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        BigDecimal neededStake = BigDecimal.valueOf(nodes.get(0).getTotalStake()).multiply(downloadRatio);
Done.  Sounds good!

2023-06-26 21:56 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +            downloadRatio = downloadRatio.max(consensusRatio);
Done.

2023-06-26 21:57 UTC, MarcKriguerAtHedera commented on docs/configuration.md
> +| `hedera.mirror.importer.downloader.downloadRatio`                           | 0.48333333333                  | The ratio of nodes (or stake) to be concurrently downloaded to verify signatures) to t
Done.

2023-06-26 21:57 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        // shuffle nodes into a random order
Done.

2023-06-26 22:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +    Collection<ConsensusNode> partialCollection(Collection<ConsensusNode> allNodes) {
I removed the `@VisibleForTesting` line and made it `protected` -- if you prefer, once I can get the new `DownloaderTest` method (that you suggest) to work, I can make it private (and eliminate the new `testPartialCollection()` method in `AbstractDownloaderTest`.  But when I tried to write the new DownloaderTest, I got the error `error: downloadAndParseSigFiles() has private access in Downloader` .  I looked into how to get Mockito to test private methods, and all I got was suggestions to use PowerMock or ReflectorTestUtils.  Can you point me at an existing test (of a private method) that I could model this on? 

[This is the only suggestion that I have not yet been able to implement]

2023-06-26 22:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +            log.debug("partialCollection: Kept all {} nodes", nodes.size());
Done.

2023-06-26 22:02 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        BigDecimal neededStake = BigDecimal.valueOf(nodes.get(0).getTotalStake()).multiply(downloadRatio);
Done.

2023-06-27 15:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +        if (allNodes == null || allNodes.size() <= 1 || downloadRatio.compareTo(BigDecimal.ONE) == 0) {
Done.

2023-06-27 15:20 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
> +    public void validateRatios() {
The reason I had originally made this `public` was so that it could be called on the fly after changing the download ratio (to make sure it is still at least as large as the consensus ratio), but not having to rerun the rest of the init() method.  But this can only happen if they are changing the ratio after it has been validated (which generally only happens in a unit test), so I will go ahead and make this method `private` and not re-validate after it's been set.

2023-06-27 20:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +    Collection<ConsensusNode> partialCollection(Collection<ConsensusNode> allNodes) {
Not sure I understand. Are you trying to mock `Downloader.downloadAndParseSigFiles`? You're not stubbing or mocking any methods in Downloader, you're mocking `StreamFileProvider` and other class dependencies. You can even return an empty list from `StreamFileProvider` to avoid having to mock things after it's invoked.

2023-06-27 22:37 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +    Collection<ConsensusNode> partialCollection(Collection<ConsensusNode> allNodes) {
I wasn't able to get this to work, but I was trying to add another @Test to DownloaderTest.java, where I thought I was going to declare (like the existing @Test does for
```
        when(downloader.getStreamFileSignatureMultiMap()).thenCallRealMethod();
```
the same for
```
        when(downloader.downloadAndParseSigFiles()).thenCallRealMethod();
```
However, since both _that_ method (which is the only one to call `partialCollection()`) is `private` (and `partialCollection()` is **supposed** to become `private` as well), I could not figure out how to have the
new test call into that method (with a mocked `StreamFileProvider` that counts the number of times its
`list()` method gets counted.

2023-06-27 23:41 UTC, MarcKriguerAtHedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +    Collection<ConsensusNode> partialCollection(Collection<ConsensusNode> allNodes) {
I read more about `ReflectorTestUtils` and it turns out to be trivially easy to have the same AbstractDownloadTest.java call into Downloader::partialCollection (even after declaring that method private).  It's literally a 2-line change: 1 to declare the method private, and 1 to call it via ReflectorTestUtils.  (OK, 3 lines -- ReflectorTestUtils needs an import line.).  Making that change now.

2023-06-28 16:39 UTC, steven-sheehy approved these changes
LGTM

2023-06-29 15:07 UTC, xin-hedera approved these changes
LGTM

2023-06-29 17:15 UTC, merged