06120 contract nonce
hashgraph/hedera-mirror-node pull request #6260
Opened 2023-06-25 00:58 UTC by mgoelswirlds

**Description**:

Persisting contract nonces as per [HIP-729](https://hips.hedera.com/hip/hip-729) . Making it available via the contract APIs
`/api/v1/contracts` and `/api/v1/contracts/{id}`

This PR changes
* Persists entity.ethereum_nonce value.
* Changed `/api/v1/contracts` and `/api/v1/contracts/{id}` to return the nonce value

**Related issue(s)**:

Fixes #6120

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-25 00:59 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (entityProperties.getPersist().isTrackNonce()) {
Created a feature flag, since we are creating entity object for all contracts.

2023-06-26 15:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (entityProperties.getPersist().isTrackNonce()) {
we already create entity objects for all contracts, updating the nonce won't count as *new* objects so no need of a feature flag

2023-06-27 22:08 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    @SuppressWarnings("deprecation")
This test case is currently failing. The idea here is to create a parent and child contract and have the nonces set correctly and verify that respective entities with correct nonces are created. This is not currently happening as the processing of the transaction is not creating correct ContractNonceInfo.
I need some guidance on how to proceed with this test.

2023-06-27 22:09 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    protected void process(RecordItem... recordItems) {
This is done so that both records are processed together.

2023-06-28 04:22 UTC, steven-sheehy requested changes

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            nonceInfos.forEach(nonceInfo -> {
nit: Could be more succinct.
```suggestion
        functionResult.getContractNoncesList().forEach(nonceInfo -> {
```

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                        entityIdService.lookup(nonceInfo.getContractId()).orElse(EntityId.EMPTY);
We don't need to use the entity service here as entity IDs in the record are guaranteed to always be in shard.realm.num format.

```suggestion
                var contractId = EntityId.of(nonceInfo.getContractId());
```

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                entity.setBalance(0L);
We should not set a balance since it's not changing.
```suggestion
```

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        if (entityProperties.getPersist().isTrackNonce()) {
Move this if statement into `processContractNonce` so the method is self contained and more reusable.

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    processCreatedContractEntity(recordItem, contractId, functionResult);
Revert this and below changes.

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean trackNonce = true;
Add to docs/configuration.md

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/all-params.json
> +        "ethereum_nonce": 1,
nit: Would be good to set each nonce in this file to a distinct value so it's clear the mapping is correct.

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .addCreatedContractIDs(createdContract)
Seems like this change is no longer really needed.

2023-06-28 04:22 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +            transaction = transactions.get(0);
Storing only a single variable for a multi-transaction test case seems like it would break test cases

2023-06-28 15:50 UTC, xin-hedera requested changes

2023-06-28 15:50 UTC, xin-hedera commented on build.gradle.kts
> +        api("com.hedera.evm:hedera-evm:0.38.0")
revert since this downgrades the dependency

2023-06-28 15:50 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                .build();
The problem is how the contract nonce is set in RecordItemBuilder.contractFunctionResult

`recordItemBuilder.contractCreate()` allocates a contract id `0.0.x` as the new contract created, then in `recordItemBuilder.contractFunctionResult()`, the nonce info is set for a different contract `0.0.y`

2023-06-28 16:19 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                        .setContractId(contractId)
@xin-hedera This is the contractId with which the contract is created. I am not sure how they are different?

2023-06-28 23:30 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    void processContractNonce() {
This test simply creates a contract and verifies the ethereum nonce is set.

2023-06-28 23:30 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +    protected void parseRecordItemAndCommit(RecordItem... recordItems) {
This method is modified to support multiple record items.

2023-06-28 23:32 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                () -> assertThat(entityRepository
Testing contractCall in an existing test.

2023-06-29 02:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +    protected void parseRecordItemAndCommit(RecordItem... recordItems) {
There's a `parseRecordItemsAndCommit(List)` right below it...

2023-06-29 03:07 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +    protected void parseRecordItemAndCommit(RecordItem... recordItems) {
Yup saw that later. Making the changes.

2023-06-29 16:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            functionResult.getContractNoncesList().forEach(nonceInfo -> {
Not sure of the performance ramifications of using `.forEach`. In many places outside of tests we use a basic `for` loop or a `for(item : list)` loop for better performance.

2023-06-29 16:40 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            functionResult.getContractNoncesList().forEach(nonceInfo -> {
`Iterable.forEach` can vary for different collection implementations. For `ArrayList`, which I believe this is using, it uses `for (int i = 0; i < col.size(); ++i)` which is more efficient than `for(item : list)`.

2023-06-29 16:57 UTC, xin-hedera requested changes

2023-06-29 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                Entity entity = contractId.toEntity();
nit
```suggestion
                var entity = contractId.toEntity();
```

2023-06-29 16:57 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.trackNonce`            | true                           | Track nonce changes and persist to the entity database
need to update `EthereumTransactionHandler` to also honor the trackNonce property

2023-06-29 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
should move after the `isContractResults` check

2023-06-29 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                Entity entity = contractId.toEntity();
nit
```suggestion
                var entity = contractId.toEntity();
```

2023-06-29 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +                () -> assertThat(entityRepository.findById(entityId.getEntityNum()))
nit
```suggestion
                () -> assertThat(entityRepository.findById(entityId.getId()))
```

2023-06-29 16:57 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
fine with it, but... we already have test cases like `contractCallToExistingWithChildContractCreate`, can just add nonce info and assert it there

2023-06-29 18:32 UTC, steven-sheehy requested changes

2023-06-29 18:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
Disagree. Nonces should be tracked regardless of if we store results.

2023-06-29 18:32 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    void processContractNonce() {
Need a test case for when trackNonce=false. Can make this one a parameterized test.

2023-06-29 18:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
this looks controversial since nonce info in proto is part of contract result. it'll look weird to reason about it if the whole contract result is skipped while we increase the nonce, users know the called contract has created a new contract however, there is no record of which function it has called to create the new contract.

2023-06-29 19:54 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
It's also strange that we couple the two properties together. I set `contractResults=false` since I don't want that table populated since I'm not using it but I set `trackNonces=true` because I do want that. Then users will be confused that `trackNonces` requires `contractResults=true`.

2023-06-30 14:49 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
The other test case you mentioned is using CreatedChildContract, which is now deprecated. I did not want to add to use a deprecated API.

2023-06-30 14:55 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
did you mean `CreatedContractIDs`?

no. `contractCallToExistingWithChildContractCreate` does not use that array, because in the test case it sets up the correct HAIP version `HAPI_VERSION_0_23_0`

In fact,  `CreatedContractIDs` is marked as deprecated but services still fills in the child contract ids in the parent's record afaik.

2023-06-30 14:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +
yeah that's fair

2023-06-30 15:15 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
Yes I meant CreatedContractIDs. I see [this](https://github.com/hashgraph/hedera-mirror-node/blob/2ea722eb3a0d1d7c3f40922025aa026c44b46b5f/hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java#L832) in the test , which is a CreatedContractID.

2023-06-30 15:30 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
it's being deprecated so consumers of the contract result in record is advised not to use that field. however, it's not a issue that we get the child contract id from it in test since:

- in the setup it's populated
- as I mentioned, services still populates it

2023-06-30 17:53 UTC, xin-hedera requested changes

2023-06-30 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +            if (entityProperties.getPersist().isTrackNonce()) {
move the condition into the outer if so it becomes

`if (!EntityId.isEmpty(senderId) && entityProperties.getPersist().isTrackNonce())`

2023-06-30 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +    void processContractNonce(boolean isTrackNonce) {
add a `@AfterEach` hook to restore persist.trackNone to `true`, the default.

this is causing other test cases failing since they all share the same test application context so when trackNonce is set to `false`, tests ran after it all see the `false` value

2023-06-30 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +                .returns(1L, Entity::getEthereumNonce);
if i'm not mistaken, `domainBuilder.entity().persist()` create the entity with nonce=1, and in the contractResult created by `recordItemBuilder.contractCall` the nonce info is also 1. there is no way to tell if we do track nonce or not regardless of the trackNonce property.

2023-06-30 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        var entity = domainBuilder.entity().persist();
change the entity type to `CONTRACT`

2023-06-30 19:07 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
Ahh, tried changing it , to then realise , I can't do it , since the CreatedContractIDs are obtained later and I need to set the contractID in the builder with the nonce. I tried setting the values with the builder, but doesn't seem to get set.
So I will leave my test case as is and not change the existing test.

2023-06-30 19:56 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    void contractCallChildNonce() {
no problem

2023-06-30 21:00 UTC, steven-sheehy approved these changes
LGTM except for some merge issues

2023-06-30 21:19 UTC, xin-hedera requested changes

2023-06-30 21:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.84.0__set_nonce_for_all_contracts.sql
> +where type='CONTRACT';
version should be `V1.82.0`, and do the same for `entity_history` table

2023-06-30 21:50 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-06-30 22:56 UTC, steven-sheehy commented on docs/configuration.md
> + `hedera.mirror.web3.db.port`                           | 5432                                               | The port used to connect to the database
Duplicate

2023-06-30 23:17 UTC, steven-sheehy approved these changes

2023-07-05 14:28 UTC, xin-hedera approved these changes

2023-07-05 14:41 UTC, merged