5874 contract results api from query param does not support sender address
hashgraph/hedera-mirror-node pull request #6282
Opened 2023-06-27 18:59 UTC by edwin-greene

**Description**:
Add support for sender addresses in the `from` query parameter for the contract result REST API. Add support for the `from` query parameter to be an evm address.

**Related issue(s)**:

Fixes #5874 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-06-29 14:20 UTC, jnels124 commented on hedera-mirror-rest/controllers/contractController.js
> +  extractContractResultsByIdQuery = async (filters, contractId, fromEntity) => {
missing js doc for fromEntity

2023-06-29 21:55 UTC, xin-hedera requested changes

2023-06-29 21:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__add_contract_result_sender_id_index.sql
> +create index if not exists contract_result__sender_timestamp
should research if from should be contract_result.sender when sender is set and otherwise default to the transaction payer account id.

if so, instead of adding a new index, we should replace the existing two

```
"contract_result__id_payer_timestamp" btree (contract_id, payer_account_id, consensus_timestamp)
"contract_result__payer_timestamp" btree (payer_account_id, consensus_timestamp)
```

with

```
"contract_result__id_from_timestamp" btree (contract_id, coalesce(sender_id, payer_account_id), consensus_timestamp)
"contract_result__from_timestamp" btree (coalesce(sender_id, payer_account_id), consensus_timestamp)
```

and change the queries to use coalesce to match the index

2023-07-05 17:50 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__add_contract_result_sender_id_index.sql
> +create index if not exists contract_result__sender_timestamp
I have changed the index to be on the sender_id, with no inclusion of the payer_account_id, after adding the migration for the `coalesce(sender_id, payer_accound_id)`.

2023-07-05 17:58 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +  extractContractResultsByIdQuery = async (filters, contractId, fromEntity) => {
Thanks I have added the doc.

2023-07-05 20:05 UTC, xin-hedera requested changes

2023-07-05 20:05 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +            filter.value = await EntityService.getEncodedId(fromEntity);
we allow multiple `from=`, so we can't use fromEntity as the original value if the parsed value is null. in addition, when there are multiple `from=`, `req.query['from']` is an array

2023-07-07 14:07 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +            filter.value = await EntityService.getEncodedId(fromEntity);
Thanks I have refactored that section to support multiple `from` parameters.

2023-07-07 14:07 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        contractResult.setSenderId(payerAccountId);
Sounds good I have added it.

2023-07-07 14:08 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +  extractContractResultsByIdQuery = async (filters, contractId, fromEntity) => {
This change has been refactored out, so there is no longer an additional parameter to that function.

2023-07-07 16:21 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +const getEncodedEvmAddresses = async (fromQuery, filters) => {
should change `utils.formatComparator` to assign the `EntityId` value to comparater.value for `FROM` filter key. Then in `extractContractResultsByIdQuery` resolve the evm address if needed

2023-07-10 18:11 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__add_contract_result_sender_id_index.sql
> +  on contract_result (sender_id, consensus_timestamp);
Thanks for catching that. I have updated the readme.

2023-07-10 18:12 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +const getEncodedEvmAddresses = async (fromQuery, filters) => {
Sounds good, I have made that change.

2023-07-10 22:04 UTC, steven-sheehy approved these changes
LGTM

2023-07-11 14:38 UTC, xin-hedera reviewed
LGTM

2023-07-11 14:38 UTC, xin-hedera approved these changes

2023-07-11 16:52 UTC, merged