05655 burn precompile2
hashgraph/hedera-mirror-node pull request #6290
Opened 2023-06-28 06:15 UTC by vtronkov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-04 10:25 UTC, 0xivanov reviewed
Fix the code smells, you can use `@SuppressWarnings` where the code is copied from services

2023-07-04 11:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
> +            BurnLogic burnLogic) {
burnLogic could also be `final`

2023-07-04 14:14 UTC, vtronkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
> +        return encoder.encodeBurnSuccess(burnResult.totalSupply());
Done 👍 I saw how you did it in MintPrecompile and did it the same way. I also refactored the code a bit and extracted the main logic into a private method leaving original methods as wrappers(so it won't bother the callers with details).
I also extracted the convertArrayToLong method in the MiscUtils class(not sure if that is the best place, if you have a better place in mind I can move it) so I can reuse it.

2023-07-04 14:14 UTC, vtronkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
> +            BurnLogic burnLogic) {
Done

2023-07-04 19:15 UTC, steven-sheehy requested changes

2023-07-04 19:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
> +    private BurnWrapper burnOp;
It's still stateful. Have to make stateless or create for every request.

2023-07-05 06:27 UTC, vtronkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
> +    private BurnWrapper burnOp;
Fixed 👍

2023-07-05 07:48 UTC, vtronkov commented
> I have the feeling that our formatting is not applied in this PR. Would you mind checking that ?

Fixed

2023-07-06 09:48 UTC, vtronkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
> +                modifiedToken.getTotalSupply(),
Fixed.
I also found that getMinimumFeeInTinybars was not implemented correctly so I fixed that.

2023-07-06 20:42 UTC, steven-sheehy approved these changes
LGTM, just need to merge

2023-07-07 07:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/hapi/utils/contracts/ParsingConstants.java
> +    public static final TupleType burnReturnType = TupleType.parse("(int32,uint64,int64[])");
Having a look at services code, it seems for burn we return only the new total supply, so we should revert this change.

2023-07-07 07:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
> +    public Bytes encodeBurnSuccess(final long totalSupply, final long[] serialNumbers) {
In services we encode only the `totalSupply`

2023-07-07 07:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
> +                .withSerialNumbers(NO_SERIAL_NUMBERS)
We encode only the totalSupply in services

2023-07-10 19:43 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-07-10 19:47 UTC, steven-sheehy approved these changes

2023-07-10 19:57 UTC, merged