Add EntityTransaction
hashgraph/hedera-mirror-node pull request #6303
Opened 2023-06-29 20:41 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Relates to #5274 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-29 20:42 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.trackEntityTransaction`     | true                           | Track transactions for entities and persist to the database
a new persist property

2023-06-29 20:43 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.entityTransactionExclusion` | ["0.0.98", "0.0.800"]          | Entity IDs excluded from transaction tracking
another one

2023-07-06 22:31 UTC, steven-sheehy requested changes
Biggest concern is we missed some EntityId or that we will miss one in the future. Should think on solutions that ensure we can't miss them. Two possibilities:

1. Use `EntityMetadataRegistry` and its MethodHandle based getter to dynamically collect EntityIds.
2. Add an interface to every domain that collects its own Entity IDs.
3. Write a reflection based test that verifies everything is captured. Perhaps a custom test EntityListener that collects all EntityId fields to assert against EntityTransaction.

2023-07-06 22:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.82.0__add_entity_transaction.sql
Need to update the migration number.

2023-07-19 14:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>              entityId = transactionHandler.getEntity(recordItem);
prefer to track it in a different ticket since the current logic can't support it well in terms of both performance and functionality. The fact is we only know the full set of entity transactions for a transaction after the parsing is complete, and by then if we need to skip the transaction per the filter, the domain objects changes have all propagated to `EntityListener`.

2023-07-19 21:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandler.java
> +abstract class AbstractTransactionHandler implements TransactionHandler {
add a new abstract base `TransactionHandler` class with a default `addCommonEntityIds` to add the main entityId, payerAccountId, and nodeAccountId

2023-07-19 21:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCallTransactionHandler.java
> -    public TransactionType getType() {
these are now replaced by the getter in the abstract base class

2023-07-19 21:26 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEntityTransactionTest.java
> +            entities.addAll(getEntities(message, excludeTransfers));
recursively walk through non entity id protobuf message types

2023-07-21 00:13 UTC, steven-sheehy requested changes

2023-07-21 00:13 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/service/contractService.test.js
Need to revert rest changes once https://github.com/hashgraph/hedera-mirror-node/pull/6459 goes in

2023-07-25 23:57 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
>              entityId = transactionHandler.getEntity(recordItem);
Let's create an issue for this. Also need an issue for the migration.

2023-07-26 00:06 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-07-27 16:28 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +@CustomLog
Looks like CustomLog is unused?

2023-07-27 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +@CustomLog
yeah. will remove it when merging changes from main

2023-07-27 17:44 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        entityProperties.getPersist().setNonFeeTransfers(false);
NonFeeTransfers doesn't exist anymore.

2023-07-27 18:05 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        entityProperties.getPersist().setNonFeeTransfers(false);
We should remove this.

2023-07-27 18:06 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        entityProperties.getPersist().setNonFeeTransfers(false);
I think fixing conflicts will fix it.

2023-07-27 18:06 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
> +        entityProperties.getPersist().setNonFeeTransfers(false);
that'll happen when I merge changes from `main`

2023-07-27 18:15 UTC, mgoelswirlds submitted a review, later dismissed
lgtm

2023-07-27 23:35 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEntityTransactionTest.java
> +        }
skip the `SchedulableTransactionBody` inside the schedule create tx when itemizedTransfers is enabled

2023-07-28 01:59 UTC, steven-sheehy approved these changes

2023-07-28 14:27 UTC, jnels124 approved these changes
LGTM

2023-07-28 15:58 UTC, merged