Add transactions flag to /accounts/{idOrHash}
hashgraph/hedera-mirror-node pull request #6330
Opened 2023-07-04 12:43 UTC by Ivo-Yankov

**Description**:
Adds a `transactions` flag to the `/accounts/{idOrHash}` route. If set to `false` no transactions will be included to the response.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-05 14:54 UTC, xin-hedera requested changes

2023-07-05 14:54 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +  const transactionsFilter = filters.find((filter) => filter.key === filterKeys.TRANSACTIONS);
- we honor the last such boolean params in other places
- use `utils.parseBooleanValue` since the validation logic of a boolean param value in `buildAndValidateFilters` is case-insensitive

2023-07-05 14:54 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/transactions-false.json
> +{
can combine the two spec files into one with the `tests` section:

```json
{
  "tests": [
    {
      "urls": [...], // no transactions param / with 'transactions=true' param
      "responseStatus": 200,
      "responseJson": {...}
    },
    {
      "urls": [...], // with 'transactions=false' param
      "responseStatus": 200,
      "responseJson": {...}
    }
   ]
}
```

2023-07-07 16:24 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +  const transactionsFilter = filters.find((filter) => filter.key === filterKeys.TRANSACTIONS);
findLast?

2023-07-07 18:19 UTC, steven-sheehy reviewed
Please update `docs/rest/README.md` to add a new row for when timestamp=true to show that the transaction tables are not used.

2023-07-10 14:44 UTC, xin-hedera commented on docs/rest/README.md
> +| `/api/v1/accounts/:idOrAlias?timestamp=true&transactions=false` | `account_balance`, `account_balance_file`, `crypto_transfer`, `entity`, `entity_history`, `token_balance`, `token_transfer`
```suggestion
| `/api/v1/accounts/:idOrAlias?transactions=false` |  `entity`, `record_file`, `token_account`                | |
```

2023-07-10 16:06 UTC, steven-sheehy commented on docs/rest/README.md
> +| `/api/v1/accounts/:idOrAlias?timestamp=true&transactions=false` | `account_balance`, `account_balance_file`, `crypto_transfer`, `entity`, `entity_history`, `token_balance`, `token_transfer`
We can probably omit this line since it might be tricky to maintain rows for all combinations of params. This is just a union of the other rows.

2023-07-11 16:50 UTC, steven-sheehy approved these changes
LGTM

2023-07-11 16:51 UTC, merged