3576 hip 336 track remaining crypto and fungible token allowances
hashgraph/hedera-mirror-node pull request #6336
Opened 2023-07-05 12:49 UTC by jascks

**Description**:
The mirror node tracks the allowances granted via `CryptoApproveAllowance` and `CryptoDeleteAllowance`, but does not currently track the current allowance that result from actually spending those allowances.

This PR  includes the following changes:
* Rename `crypto_allowance.amount` to `amount_granted`
* Add a `crypto_allowance.amount`
* Add a `crypto_allowance.created_timestamp`
* Rename `token_allowance.amount` to `amount_granted`
* Add a `token_allowance.amount`
* Add a `token_allowance.created_timestamp`
* Add a `@UpsertColumn(coalesce = "case when {0} >= 0 then {0} else coalesce(e_{0}, 0) + coalesce({0}, 0) end")` to `CryptoAllowance.amount` and `TokenAllowance.amount`
* In `CryptoApproveAllowanceTransactionHandler`, in both `parseCryptoAllowances()` and `parseTokenAllowances()`:
  - Set `created_timestamp` to `consensus_timestamp`
  - Also, set `amount_granted` to approval amount
* In `SqlEntityListener`, merge the allowances in the same record file
* In `EntityRecordItemListener`, for every crypto transfer in the body (not `CryptoTransfer` generated from record) with `is_approval=true` create a `CryptoAllowance` with primary keys, amount from transfer, and no timestamp
* In `EntityRecordItemListener`, for every token transfer in the body (not `TokenTransfer` generated from record) with `is_approval=true` create a `TokenAllowance` with primary keys, amount from transfer, and no timestamp
* Write a migration to calculate the current allowance
  * Populate `amount` in main table using the amount granted and the transfers with `is_approval=true`
  * Populate `created_timestamp` in main and history tables with min `timestamp_range` across both tables
* Fix allowance REST APIs to use the renamed `amount_granted`

**Related issue(s)**:

Fixes #3576 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-17 17:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmount.getIsApproval()) {
also check `amount < 0`, I'm not sure if services will reject a crypto transfer transaction with fungible token transfer `amount > 0` and `isApproval = true`, so it's good to be more defensive on our end.

2023-07-17 17:59 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmount.getIsApproval()) {
I read in HIP-336:
```For hbar and fungible transfers the is_approval field must be set on the debiting AccountAmount ```
 
But it does not say must _not_ be set on the crediting AccountAmount. I will add your suggested check! Some extra defense never hurts. :)

2023-07-17 18:03 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                if (accountAmount.getIsApproval()) {
Looking at line 225 as well for crypto transfers.

2023-07-31 14:49 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/FungibleAllowance.java
> +public interface FungibleAllowance extends History {
add an interface and make `AbstractCrytoAllowance` and `AbstractTokenAllowance` both implement it, then in `SqlEntityListener` merge them using the same function to reduce code duplication

2023-07-31 14:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AsyncJavaMigration.java
> +abstract class AsyncJavaMigration<T> extends RepeatableMigration {
make `AsyncJavaMgration` a subclass of `RepeatableMigration` because

1. `AsyncJavaMigration` is repeatable
2. now `AsyncJavaMigration` can be disabled in config like other repeatable migrations, this helps to test `FixCryptoAllowanceAmountMigration` since the migration drops the `crypto_allowance_migration` in a separate thread

2023-07-31 14:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/AsyncJavaMigration.java
> +    protected abstract TransactionOperations getTransactionOperations();
workaround to avoid the complexity of passing in `jdbcTemplate` and `transactionOperations` with the same db credentials.

2023-07-31 14:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/BatchUpserter.java
> +            preparedStatement.execute();
`executeUpdate` can only run a single SQL statement, since `upsert_history.vm` now generates two statements, change to `execute`

2023-07-31 14:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.84.2__allowance_amount.sql
> +                             and tt.consensus_timestamp >= lower(ta.timestamp_range)
use a left join and put all conditions related to table `token_transfer` to the on... clause, otherwise `spent_allowance` will only have values for token allowances with transfers, and then token_allowance.amount will be 0 for those without token transfers

2023-07-31 15:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/template/upsert_history.vm
> +## Updates from non-history rows
The template had problem to upsert the following 3 crypto allowance rows for a (owner, spender) pair

1. non-history update, i.e., null timestamp_range
2. closed timestamp_range update
3. open closed timestamp_range update

The upsert SQL will try to insert both 1 & 3 to the current table

2023-07-31 17:05 UTC, jascks commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/FungibleAllowance.java
> +public interface FungibleAllowance extends History {
Nice!

2023-07-31 17:11 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/BatchUpserter.java
> +                StringUtils.joinWith(";\n", setTempBuffersSql, createTempTableSql, createTempIndexSql, truncateSql);
nit: `var` rather than `String`?

2023-07-31 17:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/BatchUpserter.java
> +                StringUtils.joinWith(";\n", setTempBuffersSql, createTempTableSql, createTempIndexSql, truncateSql);
That is a class variable btw

2023-07-31 17:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/BatchUpserter.java
> +                StringUtils.joinWith(";\n", setTempBuffersSql, createTempTableSql, createTempIndexSql, truncateSql);
I think you meant the lines  before it

2023-07-31 17:29 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/BatchUpserter.java
> +                StringUtils.joinWith(";\n", setTempBuffersSql, createTempTableSql, createTempIndexSql, truncateSql);
Yes, sorry for my lack of clarity there.

2023-07-31 18:19 UTC, steven-sheehy requested changes

2023-07-31 18:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean trackAllowance = true;
Needs to be added to docs/configuration.md

2023-07-31 19:16 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean trackAllowance = true;
Done. Please let me know what you think.

2023-07-31 19:23 UTC, steven-sheehy approved these changes
LGTM

2023-07-31 19:38 UTC, xin-hedera approved these changes
LGTM

2023-07-31 19:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/batch/BatchUpserter.java
> +                StringUtils.joinWith(";\n", setTempBuffersSql, createTempTableSql, createTempIndexSql, truncateSql);
let's address it in a future PR when we touch this part again so as not to dismiss the existing approvals

2023-07-31 20:15 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.84.2__allowance_amount.sql
> +alter table if exists crypto_allowance
Since we are backfilling the same value. Can we not just create a new column amount_granted , rather than renaming the old one?

2023-07-31 20:17 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.84.2__allowance_amount.sql
> +alter table if exists crypto_allowance
there is no difference in the two approaches

- the existing one, rename amount -> amount_granted
- add amount and set amount = amount_granted for current table

v.s.

- add new column amount_granted
- set amount_granted = amount

2023-07-31 20:23 UTC, jnels124 approved these changes
LGTM

2023-07-31 20:24 UTC, edwin-greene approved these changes
Looks good!

2023-07-31 21:00 UTC, merged

2023-07-31 21:09 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.84.2__allowance_amount.sql
> +alter table if exists crypto_allowance
I see that it is merged. But the second approach was one less alter table command.