Use token balance for accounts by id API with timestamp parameter
hashgraph/hedera-mirror-node pull request #6347
Opened 2023-07-07 16:55 UTC by mgoelswirlds

**Description**:

Accounts by id endpoint will now use balance values from the token balance table when timestamp provided 

This PR modifies 
* token balances query in the /accounts/{id} api with timestamp parameter
* In case of no parameter use still uses token_account table

**Related issue(s)**:

Fixes #6304

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-07 17:06 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/no-params.json
> +    "balances": [
This test has been modified for the scenario when a timestamp parameter is not provided, then balances are gottne from the token_accounts table.

2023-07-07 17:07 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp-lte.json
> +        "balance": 555,
Note in these test cases balances are fetched from token_balances table and not token_accounts.

2023-07-10 15:56 UTC, jnels124 reviewed
Are there k6 tests for v1?

2023-07-10 15:56 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +  if (tokenBalanceQuery.params.length === 2) {
This can be changed to check if accountBalanceQuery.query is non empty. This check  is already being done on line 179

2023-07-10 15:56 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +    tokenBalanceQuery.params = tokenBalanceQuery.params.concat(accountBalanceTs);
nit: `balanceFileTs` is a little more clear to me than `accountBalanceTs` rename maybe?

2023-07-10 15:56 UTC, jnels124 commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp-noaccountbalance.json
> +      "tokens": []
This may be misleading to indicate the user has no tokens. There could be cases where the token was active at the time satisfying the timestamp param but didn't yet have an entry for the token in a balance file. Not sure we need to make changes to handle this scenario.

2023-07-10 16:29 UTC, steven-sheehy requested changes

2023-07-10 16:29 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> -      .replaceAll('t.consensus_timestamp', 'created_timestamp')
I don't see how the `token_account.created_timestamp` is used anymore. Is it now retrieving an arbitrary token_account and not the one at the correct timestamp?

2023-07-10 16:29 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +      `with latest_token_balance as (select account_id, balance, token_id, created_timestamp
Should normalize the field names.

```suggestion
      `with latest_token_balance as (select account_id, balance, token_id, created_timestamp as consensus_timestamp
```

2023-07-10 17:29 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> -      .replaceAll('t.consensus_timestamp', 'created_timestamp')
Don't think that logic is needed anymore. That query was added in the last piece of work because I wasn't aware of the token_balance table and I was limiting the token_account based on it being created within the timestamp bounds. 

When we use token_account now, it will only be in cases where we don't provide the timestamp query.

2023-07-10 19:42 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp-noaccountbalance.json
> +      "tokens": []
I believe the idea is to indicate the token balances here. So if they are do not have an entry yet in the balance file , then we should not be showing them here right? And showing a 0 balance will also be misleading I think.

2023-07-10 20:11 UTC, mgoelswirlds commented on hedera-mirror-rest/accounts.js
> -      .replaceAll('t.consensus_timestamp', 'created_timestamp')
Didn't refresh so didn't see your comment there Jesse. But agreed.

2023-07-10 20:17 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> -      .replaceAll('t.consensus_timestamp', 'created_timestamp')
Think we should remove the created_timestamp from the CTE to reduce confusion since it's no longer necessary.

2023-07-10 22:01 UTC, steven-sheehy approved these changes
LGTM

2023-07-10 22:07 UTC, xin-hedera approved these changes
LGTM

2023-07-10 23:05 UTC, jnels124 approved these changes
LGTM

2023-07-10 23:15 UTC, merged