Add entity stake history
hashgraph/hedera-mirror-node pull request #6374
Opened 2023-07-11 22:56 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #6113 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-07-11 23:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__add_unknown_entity_type.sql
> +alter type entity_type add value if not exists 'UNKNOWN' before 'ACCOUNT';
the changes from `alter type` has to be committed before the new enum value can be set as default for `entity.type`, thus splitting them into two versioned migrations.

the other way is wrap the `alter type` into a child db transaction, i.e.,

```sql
begin;
alter type entity_type ...;
commit;

alter table if exists entity ...;
alter table if exists entity_history ...;
```

2023-07-11 23:05 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixStakedBeforeEnabledMigrationTest.java
> +class FixStakedBeforeEnabledMigrationTest extends AbstractStakingMigrationTest {
updated due to `entity_stake` table schema change

2023-07-11 23:05 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigrationTest.java
> +class RecalculatePendingRewardMigrationTest extends AbstractStakingMigrationTest {
updated due to `entity_stake` table schema change

2023-07-11 23:07 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var expectedEntities = Stream.of(transfer1, transfer2, transfer3)
since staking reward transfer now creates a `Entity` update object with non-null `timestampRange`, the upsert SQL will insert a row to `entity` table.

it would violates the `type` column `not null` constraint, so I ended up set `entity.type` default to `'UNKNOWN'`

2023-07-11 23:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              timestamp_range = excluded.timestamp_range;
custom SQL to insert rows to current and history tables.

the history row in the first revision is done by database table trigger on update. It turns out it's tricky to support distributed table trigger with citus and manual maintenance may be needed when the table shards change.

there's also performance concern using trigger when every time we update potentially millions rows.

2023-07-11 23:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculator.java
> +    @TransactionalEventListener(classes = NodeStakeUpdatedEvent.class)
can't have multiple spring `*EventListener` annotations on a single method

2023-07-13 20:29 UTC, steven-sheehy requested changes

2023-07-13 20:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.1__entity_stake_history.sql
> +create index if not exists node_stake__epoch_day on node_stake (epoch_day);
Missed in v2

2023-07-13 20:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__add_unknown_entity_type.sql
> +alter type entity_type add value if not exists 'UNKNOWN' before 'ACCOUNT';
Would prefer all 3 migrations condensed into one with child transaction

2023-07-13 20:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
> +            while (true) {
When would this need to loop? Shouldn't we have some sleep in between so in case there's some query failure it doesn't consume 100% CPU?

2023-07-13 20:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
> +                    Optional<Long> endStakePeriod = entityStakeRepository.getEndStakePeriod();
Can we return this value in the previous update statement?

2023-07-13 20:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
>              running.set(false);
This boolean only works if two threads try to run concurrently. If two processes try to run concurrently or an old query continues when a process dies this won't work. Can we instead take a lock on a table?

2023-07-14 14:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculator.java
> +    @TransactionalEventListener(classes = NodeStakeUpdatedEvent.class)
can try it, no sure what happens since `ApplicationReadyEvent` is not published from a transactional context

2023-07-14 14:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
> +            while (true) {
every iteration only updates entity stake for a staking period. With a loop, we can do catch up if the previous run was interrupted (for example, importer crashed).

if there's a query error, the exception would break the while loop.

2023-07-14 14:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
> +                    Optional<Long> endStakePeriod = entityStakeRepository.getEndStakePeriod();
don't think we can, it's a limit from either hibernate or spring data, with multiple-statement query statement, we can't get a return value.

2023-07-14 17:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculator.java
> +    @TransactionalEventListener(classes = NodeStakeUpdatedEvent.class)
nah, won't trigger on spring boot `ApplicationReadyEvent` if combined into `TransactionalEventListener`

2023-07-14 17:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__add_unknown_entity_type.sql
> +alter type entity_type add value if not exists 'UNKNOWN' before 'ACCOUNT';
made them into one migration

2023-07-14 17:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java
>              running.set(false);
added a `EntityStakeRepository.lockFromConcurrentUpdates` method to lock the `entity_stake` table in `share row exclusive` with option `nowait`

2023-07-17 17:29 UTC, jascks approved these changes
LGTM

2023-07-17 17:35 UTC, steven-sheehy approved these changes
LGTM

2023-07-17 17:40 UTC, edwin-greene approved these changes
Looks good

2023-07-17 18:32 UTC, merged