HIP-584: Copy ApprovePrecompile
hashgraph/hedera-mirror-node pull request #6446
Opened 2023-07-19 12:44 UTC by 0xivanov

**Description**:
We need default implementations for precompiles related to approve logic, so we should copy needed logic from hedera-services into hedera-mirror-web3.

**Related issue(s)**:

Fixes #5652

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-20 22:34 UTC, steven-sheehy requested changes

2023-07-20 22:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return approvedForAll.contains(FcTokenAllowanceId.from(tokenId, operatorId));
Loading all of an accounts NFTs just to check one of them is very inefficient and could crash the service by running out of memory. Can we not just do a query?

2023-07-20 22:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
> +    public TransactionBody.Builder createNonfungibleApproval(
It's weird that it's `createNonfungibleApproval` but has an `if (approveWrapper.isFungible())`. Is that intentional?

2023-07-20 22:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/codec/ApproveParams.java
> +public record ApproveParams(Address tokenAddress, Address senderAddress, Store store, boolean isFungible)
It seems like an abuse to pass around the Store this way. Shouldn't it be retrievable through some other mechanism?

2023-07-21 05:48 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
> +    public TransactionBody.Builder createNonfungibleApproval(
That is how it's written in hedera-services. I could refactor it but maybe it is better to keep the code closer to the original.

2023-07-21 06:14 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/codec/ApproveParams.java
> +public record ApproveParams(Address tokenAddress, Address senderAddress, Store store, boolean isFungible)
In the ApprovePrecompile body method we need to fetch the `ownerId` if we approve NFT. I could pass the `ownerId` instead of `Store` from `HtsPrecompiledContract`, but in order to get the `ownerId` from the store we need to first decode the transaction input (which is internal logic for the precompile). The only optimisation i can think of right now is to pass `null` when the operation is for fungible token and pass the `Store` only when the operation is for NFT.

2023-07-21 10:15 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/codec/ApproveParams.java
> +public record ApproveParams(Address tokenAddress, Address senderAddress, Store store, boolean isFungible)
I see 2 options:

1. Enhance the body() signature with one more argument which is the Store. This would change the signature of all precompiles but would be a clean approach.
2. Add a new utility method inside `ApprovePrecompile`, which would be used only in `web3`, which based on the `Bytes input` retrieves the `tokenId`. Then in `HTSPrecompiledContract` fetch the `ownerId`, using the `tokenId` and pass the ownerId in `ApproveParams`.

Unless we have a second or more precompiles that need the `Store` into the `body()` method I lean towards the second approach.

2023-07-21 11:41 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/codec/ApproveParams.java
> +public record ApproveParams(Address tokenAddress, Address senderAddress, Store store, boolean isFungible)
Implemented the second option

2023-07-21 13:12 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        return approvedForAll.contains(FcTokenAllowanceId.from(tokenId, operatorId));
Currently, we need to read the whole `Account` from the `Store` in order to get the most up to date information. We can create separate PR with optimisations.

2023-07-21 17:25 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Just need to merge main and can merge once Ivan K approves

2023-07-21 18:52 UTC, IvanKavaldzhiev approved these changes
LGTM

Needs thorough testing since there are a lot of cases here, but that would be covered by acceptance tests.

2023-07-21 20:47 UTC, merged