Add Custom fee history table and Aggregate Custom Fees
hashgraph/hedera-mirror-node pull request #6456
Opened 2023-07-20 14:30 UTC by edwin-greene

**Description**:
Update the custom fee table to use jsonb aggregate columns for the different types of fees.
Add the custom fee history table and migrate custom fees to the new format and the history.

**Related issue(s)**:

Fixes #5775 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-07-24 14:35 UTC, steven-sheehy requested changes

2023-07-24 14:35 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private Long royaltyNumerator;
Can name similarly then pull amount to parent.

```suggestion
    private long amountDenominator;

    private long amount;
```

2023-07-24 14:35 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/FractionalFee.java
> +    private Long amount;
We should revisit which fields can be primitive since they can't be null for their specific type. Previously they were all merged into one class so had a lot of nullable objects.

2023-08-01 21:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Thanks I have removed that merge and just closed the timestamp.

2023-08-01 21:04 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/CustomFeesMigration.java
> +              add primary key (token_id, created_timestamp);
Thanks I have added those indexes.

2023-08-01 21:05 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .createdTimestamp(timestamp)
Sounds good, I have updated the domainBuilder to include each type of fee.

2023-08-01 21:05 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private EntityId collectorAccountId;
I have added the AbstractFee class.

2023-08-01 21:06 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private Boolean allCollectorsAreExempt;
Thanks I have updated all the fields that were able to be primitives.

2023-08-01 21:08 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private Long royaltyNumerator;
RoyaltyFee has a FallbackFee property, which itself includes an `amount`, so having `amount` within RoyaltyFee and within FallbackFee seemed confusing, I have left it as `royaltyNumerator` thus far. 

Not all three of the fee types included the `amountDenominator`, so the `AbstractFee` does not include it, and the `royaltyDenominator` remains in the RoyaltyFee class.

2023-08-01 21:08 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/FractionalFee.java
> +    private Long amount;
I have updated it, now all fields that can be primitives should be primitive.

2023-08-01 22:15 UTC, steven-sheehy requested changes

2023-08-01 22:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +  drop column if exists all_collectors_are_exempt,
It's probably easier to:

* Create the temp table
* Insert into it from custom_fee
* Drop custom_fee
* Rename temp to custom_fee
* Add indexes

Then you don't have to do the slower deletes, complicated alter statements, worry about indexes slowing you down, etc.

2023-08-01 22:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>      on custom_fee (token_id desc, created_timestamp desc);
We should drop the secondary index in v1 and v2 since now we don't have created_timestamp but also there's not multiple rows per token_id

2023-08-01 22:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +          'all_collectors_are_exempt', all_collectors_are_exempt) end as royalty_fees
nit: Sort all these json fields here and above.

2023-08-01 22:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +      case when denominating_token_id is not null and royalty_denominator is null then
This should probably be moved last and can just be the default else.

2023-08-01 22:17 UTC, steven-sheehy commented
Have some code smells and failing tests.

2023-08-02 16:49 UTC, xin-hedera requested changes

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> -  } else {
revert, if a token is created with no custom fee, there should be a row with null for all fees, and timestamp_range = `[token.created_timestamp,)`

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/model/fixedFee.js
> +    this.collectorAccountId = fixedFee.collector_account_id;
move `allCollectorsAreExempt` and `collectorAccountId` to a base class as the one in common domain class

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +      'token_id', ${CustomFee.TOKEN_ID}::text,
don't think the conversion is needed

```suggestion
      'token_id', ${CustomFee.TOKEN_ID},
```

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +  const conditions = [`${CustomFee.getFullName(CustomFee.TOKEN_ID)} = $1`];
```suggestion
  const conditions = [`${CustomFee.TOKEN_ID} = $1`];
```

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +        order by ${CustomFee.getFullName(CustomFee.CREATED_TIMESTAMP)} desc`;
remove the table alias and remove `getFullName`

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +    conditions.push(`lower(${CustomFee.FILTER_MAP[filter.key]}) ${op} $2`);
perhaps just remove the `FILTER_MAP` in the model class since there is just one, then change it to
 ```suggestion
    conditions.push(`lower(${CustomFee.TIMESTAMP_RANGE}) ${op} $2`);
```

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +        )
remove table alias, remove `getFullName` or `getHistoryFullName`, remove `historyConditions` and just use `conditions`

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +          order by ${CustomFee.getFullName(CustomFee.CREATED_TIMESTAMP)} desc
remove the order by, there can be at most one row for a token in the current table

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +          order by ${CustomFee.getHistoryFullName(CustomFee.CREATED_TIMESTAMP)} desc
nit, this needs to be `order by lower(timestamp_range) desc` once created_timestamp column is removed

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +    this.fixed_fees = _.isNil(customFee.fixedFees) ? [] : customFee.fixedFees.map((f) => this._parseFixedFee(f));
nit, this is shorter

```suggestion
    this.fixed_fees = customFee.fixedFees?.map((f) => this._parseFixedFee(f)) ?? [];
```

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +      amount: Number(fixedFee.amount),
amount will be parsed into a number if it's safe otherwise a bigint, inside the pg driver with the custom parser we provided. Converting it to Number here is wrong since it'll be wrong for any value larger than js MAX_SAFE_INTEGER

```suggestion
      amount: fixedFee.amount,
```

2023-08-02 16:49 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +    }
this is the old way to check if fallbackFee exists, need to change it to

```javascript
  const fallbackFee = royaltyFee.fallbackFee ? {
    amount: ...,
    denominating_token_id: ...
  } : null;

  const viewModel = {
    ...,
    fallback_fee: fallbackFee,
  };
```

2023-08-03 14:24 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/FractionalFee.java
> +    private long amountDenominator;
Steven had the suggestion to rename `numerator` to `amount` and place it in an `AbstractFee` class which the three fees would extend. With this change included both `amountDenominator` in `FractionalFee` and `royaltyDenominator` in `RoyaltyFee` would be renamed `denominator`. 

There would no longer be any variables named `numerator`. Does that sound good?

`denominator` is not shared by `FixedFee`, so these two would remain in their respective classes and the variable would not be moved into `AbstractFee`.

2023-08-04 17:10 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private Long royaltyNumerator;
Thanks I have made these changes, also `amountDenominator` was renamed `denominator` per Xin's feedback.

2023-08-04 17:10 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/AbstractCustomFee.java
> +    private long createdTimestamp;
Sounds good I have removed `created_timestamp`.

2023-08-04 17:10 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/AbstractCustomFee.java
> +    private Long tokenId;
Thanks it should be sorted now.

2023-08-04 17:11 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
Thanks I have updated it.

2023-08-04 17:11 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        var fractionalFee = FractionalFee.builder()
Sounds good I have added them.

2023-08-04 17:11 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/CustomFeeHistoryRepository.java
> + * Copyright (C) 2019-2023 Hedera Hashgraph, LLC
I have removed the 2019 from the new classes.

2023-08-04 17:12 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
>  ) partition by range (created_timestamp);
Thanks I have updated the partition.

2023-08-04 17:13 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
I have added some items to the other v2 files, please re-review those changes to make sure that they are correct.

2023-08-04 17:14 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +  drop column if exists all_collectors_are_exempt,
Thanks I have updated the migration. There was one part where the history table and the custom fees table are generated from the temp table, so at that point the temp table was not renamed but instead used to generate the other two tables.

2023-08-04 17:14 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
>      on custom_fee (token_id desc, created_timestamp desc);
Right I have removed it.

2023-08-04 17:14 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +          'all_collectors_are_exempt', all_collectors_are_exempt) end as royalty_fees
Thanks it should be sorted now.

2023-08-04 17:15 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +      case when denominating_token_id is not null and royalty_denominator is null then
There are some fees that are empty, so as of yet there is no else statement to automatically add a jsonb fee.

2023-08-04 17:15 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/AbstractCustomFee.java
> +        return (this.fixedFees == null || this.fixedFees.isEmpty())
Sounds good I have made that change.

2023-08-04 17:16 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private long royaltyNumerator;
Thanks I have renamed the fields to `denominator` and `amount` per Steven's feedback about `numerator` being moved to a parent class.

2023-08-04 17:16 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFeeScheduleUpdateTransactionHandler.java
> +        var fixedFee = new com.hedera.mirror.common.domain.transaction.FixedFee();
Thanks the fully classified name for one is now removed.

2023-08-04 17:17 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +begin;
Thanks I have removed them.

2023-08-04 17:17 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RoyaltyFee.java
> +    private FixedFee fallbackFee;
I was unable to get the annotation to work, so I created a `FallbackFee` class, and I removed those two fields.

2023-08-04 17:18 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql
> +          'all_collectors_are_exempt', all_collectors_are_exempt),
Thanks I have updated the migration.

2023-08-04 17:18 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CustomFeesMigrationTest.java
> +    @Value("classpath:db/migration/v1/V1.83.2__custom_fee_aggregate_history.sql")
Good to know! Thanks I have updated it.

2023-08-04 17:18 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CustomFeesMigrationTest.java
> +        try (var is = sql.getInputStream()) {
Sounds good I have made those changes.

2023-08-04 17:19 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFeeScheduleUpdateTransactionHandler.java
> +            RecordItem recordItem) {
Got it, I have made those changes. It would be cleaner if the statements could be applied once at the end of the switch statement rather in the individual cases, but there still seemed to be a need to differentiate based on the fee type.

2023-08-04 17:20 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFeeScheduleUpdateTransactionHandler.java
> +            fixedFee.setCollectorAccountId(collector);
Thanks I have made this change.

2023-08-04 17:20 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/AbstractCustomFee.java
> +
Got it I have moved them.

2023-08-04 17:45 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/CustomFeeConverter.java
Still looking into this. The error is: 
```
Failed to convert property value of type 'org.postgresql.util.PGobject' to required type 'java.util.List' for property 'fixedFees'; Cannot convert value of type 'org.postgresql.util.PGobject' to required type 'com.hedera.mirror.common.domain.token.FixedFee' for property 'fixedFees[0]': no matching editors or conversion strategy found
```

2023-08-04 17:49 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/FractionalFee.java
> +    private long amountDenominator;
I'd disagree. The old schema overloads  `amount`, it can be `fixedFee.amount`, `fractionalFee.numerator`, or `royaltyFee.fallbackFee.amount`, because we don't want to add an additional column.

The new approach is more OO oriented, in addition, when we look at the values in db, it's more intuitive and a direct reflection of what's in the protobuf message.

2023-08-04 18:45 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +                    final var collector = entityDatabaseAccessor.evmAddressFromId(fallbackFee.getCollectorAccountId());
Thanks I have updated this to access the collector from the royalty fee.

2023-08-04 18:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFeeScheduleUpdateTransactionHandler.java
> +                    chargedInAttachedToken = fixedFee.isChargedInToken(tokenId);
add a `AbstractFee fee;` before the switch,

then change this to

```suggestion
                    var fixedFee = parseFixedFee(protoCustomFee.getFixedFee(), tokenId);
                    customFee.addFixedFee(fixedFee);
                    fee = fixedFee;
```

after the `switch` block,

do

```java
  fee.setAllCollectorsAreExempt(allCollectorsAreExempt);
  fee.setCollectorAccountId(collector);
  recordItem.addEntityid(fee.getDenominatingTokenId());
  boolean chargedInAttachedToken = fee.isChargedInToken(tokenId);
```

You'll need to add `getDenominatingTokenId()` to the abstract class, with default returning `EntityId.EMPTY`. For `RoyaltyFee`, the function returns fallbackFee.denominatingTokenId or `EntityId.EMPTY` if there's no fallback fee. You'll have to annotate it properly in the three concrete classes, so only in `FixedFee` the `denominating_token_id` appears in the top level json string.

2023-08-04 19:19 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +                if (fallbackFee != null && fallbackFee.getCollectorAccountId() != null) {
Thanks I have made this change.

2023-08-04 19:29 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +        return customFeeOptional.isEmpty() ? Optional.empty() : Optional.of(mapCustomFee(customFeeOptional.get()));
talked offline, confused by the Optional. Unfortunately the `Optional` is in the interface, otherwise it should just return empty list when there's either no row found or there is no fee at all in the row.

2023-08-07 18:01 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  });
Thanks I have updated it with those changes and added a method to remove duplication.

2023-08-07 18:01 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +      : EntityId.parse(f.collector_account_id).getEncodedId();
Great thanks, I have updated it.

2023-08-07 18:02 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> -  } else {
Thanks I have reverted it. This change caused primary key violations in the spec tests, as the tokens were created and then the custom fees were created afterwards. I have updated the spec tests to have the `custom_fees` property so that the custom fees are elements within the tokens, that avoids the primary key violation.

2023-08-07 18:02 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  customFee.fixed_fees?.forEach((f) => {
Thanks I have added that super class.

2023-08-07 18:03 UTC, edwin-greene commented on hedera-mirror-rest/model/fixedFee.js
> +    this.collectorAccountId = fixedFee.collector_account_id;
Sounds good, this has been done.

2023-08-07 18:03 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +      'token_id', ${CustomFee.TOKEN_ID}::text,
Thanks I have removed them.

2023-08-07 18:03 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +  const conditions = [`${CustomFee.getFullName(CustomFee.TOKEN_ID)} = $1`];
I have removed that method.

2023-08-07 18:03 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +        order by ${CustomFee.getFullName(CustomFee.CREATED_TIMESTAMP)} desc`;
I have updated it and removed the alias and the method.

2023-08-07 18:04 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +        )
Sounds good I have made those changes to the query.

2023-08-07 18:05 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +          order by ${CustomFee.getFullName(CustomFee.CREATED_TIMESTAMP)} desc
Thanks for spotting that, I have removed it.

2023-08-07 18:05 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +          order by ${CustomFee.getHistoryFullName(CustomFee.CREATED_TIMESTAMP)} desc
Got it, I have fixed it.

2023-08-07 18:05 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +    this.fixed_fees = _.isNil(customFee.fixedFees) ? [] : customFee.fixedFees.map((f) => this._parseFixedFee(f));
Thanks I have simplified those lines.

2023-08-07 18:06 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +        denominator: Number(fractionalFee.amountDenominator),
Removed.

2023-08-07 18:06 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +    }
Great, I have updated it to match.

2023-08-07 21:29 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenFeeScheduleUpdateTransactionHandler.java
> +                    chargedInAttachedToken = fixedFee.isChargedInToken(tokenId);
Sounds good I have made this update, there was a slight change to the example as denominatingTokenId is not in Abstract Fee.

2023-08-08 14:36 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/AbstractFee.java
> +    @JsonDeserialize(using = EntityIdDeserializer.class)
Thanks I have removed the serializer and deserializer.

2023-08-08 17:18 UTC, xin-hedera requested changes

2023-08-08 17:18 UTC, xin-hedera commented on hedera-mirror-rest/model/fee.js
> +    this.allCollectorsAreExempt = fee.all_collectors_are_exempt;
if we decide to have a common `amount` property across all types of fees, we should add it here as well.

2023-08-08 17:18 UTC, xin-hedera commented on hedera-mirror-rest/model/fractionalFee.js
> +    this.amountDenominator = fractionalFee.amount_denominator;
```suggestion
    this.denominator = fractionalFee.denominator;
```

2023-08-08 17:18 UTC, xin-hedera commented on hedera-mirror-rest/model/fractionalFee.js
> +  static AMOUNT_DENOMINATOR = `amount_denominator`;
make sure it's consistent when you change the property names in importer domain classes

```suggestion
  static DENOMINATOR = `denominator`;
```

2023-08-08 17:18 UTC, xin-hedera commented on hedera-mirror-rest/model/royaltyFee.js
> +    this.royaltyNumerator = royaltyFee.royalty_numerator;
```suggestion
    this.denominator = royaltyFee.denominator;
```

there's no `royalty_numerator`, it's `amount` if that's the agreed approach

2023-08-08 17:18 UTC, xin-hedera commented on hedera-mirror-rest/model/royaltyFee.js
> +  static ROYALTY_NUMERATOR = `royalty_numerator`;
```suggestion
  static DENOMINATOR = `denominator`;
```

2023-08-08 17:18 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessorTest.java
> +        // RoyaltyFee without fallback fee will not be included in the results from customFeeDatabaseAccessor.
why the above comment?

in the original test, if the custom fee row doesn't have amount / denominatingTokenId, `customFeeDatabaseAccessor.get(tokenId)` will still return the royalty fee

2023-08-08 17:26 UTC, xin-hedera requested changes

2023-08-08 17:26 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +      collector_account_id: EntityId.parse(fixedFee.collectorAccountId, {isNullable: true}).toString(),
`collector_account_id` shouldn't be nullable

2023-08-08 17:26 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +        numerator: royaltyFee.royaltyNumerator,
```suggestion
        denominator: royaltyFee.denominator,
        numerator: royaltyFee.amount,
```

2023-08-08 17:26 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +      all_collectors_are_exempt: royaltyFee.fallbackFee?.allCollectorsAreExempt ?? false,
```suggestion
    return {
      fallback_fee,
      all_collectors_are_exempt: royaltyFee.fallbackFee?.allCollectorsAreExempt ?? false,
```

note please add `fallback_fee` after `collector_account_id`
 
if `fallback_fee` is null we show `"fallback_fee": null` in the json response. so the function shouldn't conditionally show `fallback_fee`.

2023-08-08 17:50 UTC, xin-hedera requested changes

2023-08-08 17:50 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +        limit 1`;
the union all may produce two rows, without `order by`, it'll be random which row we get with the `limit 1`

```suggestion
        select * from cfee
        union all
        select * from custom_fee_history
        order by lower(${CustomFee.TIMESTAMP_RANGE}) desc
        limit 1`;
```

2023-08-08 18:02 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/CustomFeeRepositoryTest.java
> +        List<CustomFee> customFeeHistory = jdbcOperations.query("select * from custom_fee_history", ROW_MAPPER);
just use `customFeeHistoryRepository.findAll()` to verify, instead of plain SQL and `ROW_MAPPER`

I think this is the only place a custom fee RowMapper is needed. then you can remove all related `*Converter` classes and tests.

2023-08-08 20:30 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessorTest.java
> +        // RoyaltyFee without fallback fee will not be included in the results from customFeeDatabaseAccessor.
The `CustomFeeDatabaseAccessor` only returns results with `collectorAccountId`. Without a Fallback fee the Royalty Fee will not include a `collectorAccountId`: 
https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java#L44

2023-08-08 20:33 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessorTest.java
> +        // RoyaltyFee without fallback fee will not be included in the results from customFeeDatabaseAccessor.
That’s not true. The collector of a fallback fee is always the same if the enclosing royalty fee’s collector. The only change is the way they are modeled.

2023-08-08 20:36 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessorTest.java
> +        // RoyaltyFee without fallback fee will not be included in the results from customFeeDatabaseAccessor.
Web3 was implemented that way to use a null collector as the indicator of an empty custom fee schedule for the token in general, not just empty fallback fee / royalty fee.

it could have also used null amount as the indicator but that’s just an implementation choice

2023-08-08 20:37 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessorTest.java
> +        // RoyaltyFee without fallback fee will not be included in the results from customFeeDatabaseAccessor.
Investigating more, I will move the `collectorAccountId` into the RoyaltyFee object, rather than have it solely within the Fallback fee object. That will remove the need for that comment and the `CustomFeeDatabaseAccessor` will then return the royalty fee.

2023-08-08 22:37 UTC, steven-sheehy requested changes

2023-08-08 22:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/CustomFeeConverter.java
One problem is we need to ensure `ObjectToStringSerializer` static initializer is run early enough before this rowMapper is created.

Second problem is we should use a generic converter instead of a per fee converter. Something like this:

```java
    defaultConversionService.addConverter(new FeeConverter());

    public class FeeConverter implements GenericConverter {

        private final ObjectMapper objectMapper = ObjectToStringSerializer.OBJECT_MAPPER;

        @Override
        public Set<ConvertiblePair> getConvertibleTypes() {
            return Collections.singleton(new ConvertiblePair(PGobject.class, List.class));
        }

        @Override
        public Object convert(Object source, TypeDescriptor sourceType, TypeDescriptor targetType) {
            if (source instanceof PGobject pgo) {
                try {
                    var json = pgo.getValue();
                    var type = objectMapper.getTypeFactory()
                            .constructCollectionType(List.class, targetType.getElementTypeDescriptor().getType());
                    return objectMapper.readValue(json, type);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
            return null;
        }
    }
```

2023-08-08 22:37 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractFee.java
> +    private Long amount;
```suggestion
    private long amount;
```

2023-08-08 22:37 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/AbstractFeeConverter.java
Can remove all new converter classes with my other suggestion. Even if we need to keep them, they should be in a test folder.

2023-08-09 20:14 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/FractionalFee.java
> +    private long amountDenominator;
Sounds good, I have updated all of the variables to be `numerator` and `denominator`.

2023-08-09 20:15 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  customFee.fixed_fees?.forEach((f) => {
I see my mistake; it should now be fixed.

2023-08-09 20:15 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/CustomFeeRepository.java
> +public interface CustomFeeRepository extends CrudRepository<CustomFee, Long>, RetentionRepository {
Thanks I have removed the prune.

2023-08-09 20:15 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.85.2__custom_fee_aggregate_history.sql
> +     created_timestamp,
Thanks I have updated the migration sql.

2023-08-09 20:15 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.85.2__custom_fee_aggregate_history.sql
> +drop index if exists custom_fee__token_timestamp;
Great ok, it is now removed.

2023-08-09 20:16 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.85.2__custom_fee_aggregate_history.sql
> +);
Thanks I have updated the migration sql to match these steps.

2023-08-09 20:16 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
> +select create_distributed_table('custom_fee_history', 'token_id', colocate_with => 'entity');
Sounds good I have fixed it.

2023-08-09 20:17 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
> +              }
Sounds good I have added it.

2023-08-09 20:17 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> -                      created_timestamp: "1234567890.000000001"
I see, thanks I have added it back in.

2023-08-09 20:18 UTC, edwin-greene commented on hedera-mirror-rest/model/fee.js
> +    this.allCollectorsAreExempt = fee.all_collectors_are_exempt;
I have changed the amounts to 'numerator`.

2023-08-09 20:18 UTC, edwin-greene commented on hedera-mirror-rest/model/fractionalFee.js
> +    this.amountDenominator = fractionalFee.amount_denominator;
Thanks I have updated the name.

2023-08-09 20:18 UTC, edwin-greene commented on hedera-mirror-rest/model/fractionalFee.js
> +  static AMOUNT_DENOMINATOR = `amount_denominator`;
This is now fixed.

2023-08-09 20:18 UTC, edwin-greene commented on hedera-mirror-rest/model/royaltyFee.js
> +    this.royaltyNumerator = royaltyFee.royalty_numerator;
I have updated it to `numerator` and `denominator`.

2023-08-09 20:19 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessorTest.java
> +        // RoyaltyFee without fallback fee will not be included in the results from customFeeDatabaseAccessor.
This problem should now be fixed.

2023-08-09 20:19 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +      collector_account_id: EntityId.parse(fixedFee.collectorAccountId, {isNullable: true}).toString(),
Thanks I have removed the nullable.

2023-08-09 20:19 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +        denominator: fractionalFee.amountDenominator,
This is now fixed.

2023-08-09 20:20 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +        numerator: royaltyFee.royaltyNumerator,
This is now fixed. (`numerator` and `denominator`).

2023-08-09 20:20 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +      collector_account_id: EntityId.parse(royaltyFee.fallbackFee?.collectorAccountId, {isNullable: true}).toString(),
I have removed the nullable.

2023-08-09 20:20 UTC, edwin-greene commented on hedera-mirror-rest/viewmodel/customFeeViewModel.js
> +      all_collectors_are_exempt: royaltyFee.fallbackFee?.allCollectorsAreExempt ?? false,
Thanks I have added the null for missing fallback fees.

2023-08-09 20:20 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +        limit 1`;
This has now been updated.

2023-08-09 20:21 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/CustomFeeRepositoryTest.java
> +        List<CustomFee> customFeeHistory = jdbcOperations.query("select * from custom_fee_history", ROW_MAPPER);
I have updated it to use the JsonBtoList converter per Steven's suggestion.

2023-08-09 20:21 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/FallbackFee.java
> +    private Long amount;
Thanks I have updated it.

2023-08-09 20:22 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/FallbackFee.java
> +@JsonNaming(value = SnakeCaseStrategy.class)
Got it, it is now removed.

2023-08-09 20:22 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +    }
I see, thanks I have updated them.

2023-08-09 20:22 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .get();
Very good, it is now updated to match.

2023-08-09 20:22 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractFee.java
> +    private Long amount;
This has now been updated.

2023-08-09 20:23 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/AbstractFeeConverter.java
Thanks it looks like they are not necessary, I have removed them.

2023-08-10 14:06 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/CustomFeeConverter.java
Thanks I have added this but I still need to write unit tests for it.

2023-08-10 16:37 UTC, xin-hedera requested changes

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  };
this creates a new object instead of adding / modifying properties to / of the existing object, the end result is then the fees, e.g., `customFee.fixed_fees[0]` is not changed at all.

do this instead

```suggestion
  Object.assign(fee, {
      all_collectors_are_exempt: true,
      collector_account_id: '0.0.300',
    },
    fee,
  };
```

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  fee.collector_account_id = EntityId.parse(fee.collector_account_id, {isNullable: true}).getEncodedId();
```suggestion
  fee.collector_account_id = EntityId.parse(fee.collector_account_id).getEncodedId();
```

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  });
nit, can be shorter

```suggestion
  customFee.fixed_fees?.forEach(parseCustomFeeEntityIds);
```

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-rest/tokens.js
> +};
don't need the function, can always use `'created_timestamp', lower(timestamp_range),` simply because the `union all` subquery returns both `timestamp_range` column and `created_timestamp` column

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +        if (customFee.getFixedFees() == null) {
nit, use `CollectionUtils.isEmpty`

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +        if (customFee.getRoyaltyFees() != null) {
redundant check, it's already checked at the beginning

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +                    if (fallbackFee != null) {
the logic is still wrong, fallback fee in royalty is optional, we shouldn't skip a royalty fee because the lack of fallback

2023-08-10 16:37 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +            if (f.getCollectorAccountId() != null) {
you should remove all `f.getCollectorAccountId() != null` checks

2023-08-11 14:53 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CustomFeesMigrationTest.java
> +@TestPropertySource(properties = {"spring.flyway.target=1.84.2"})
Thanks for spotting that, I have updated it.

2023-08-11 14:53 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CustomFeesMigrationTest.java
> +    private List<CustomFee> getHistory() {
Awesome thanks, it was no longer needed.

2023-08-11 14:55 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  };
Doh, I was having some problems as that method didn't quite work either. I was able to get something similar to work, it should be fixed now.

2023-08-11 14:55 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  fee.collector_account_id = EntityId.parse(fee.collector_account_id, {isNullable: true}).getEncodedId();
Thanks for spotting that one, I have removed it.

2023-08-11 14:56 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    parseCustomFeeEntityIds(f.fallback_fee);
Thanks I have updated it to parse the royalty fee rather than the fallback fee, and then to update the denominating token id from the fallback fee.

2023-08-11 14:56 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  });
This is now fixed.

2023-08-11 14:57 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +        if (customFee.getRoyaltyFees() != null) {
Thanks! Fixed now.

2023-08-11 14:57 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +                    if (fallbackFee != null) {
Got it ok, I have reworked this section and added a new test for the absence of a fallback fee.

2023-08-11 14:58 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +            if (f.getCollectorAccountId() != null) {
Thanks I have removed them.

2023-08-11 16:07 UTC, xin-hedera submitted a review, later dismissed
LGTM!

2023-08-11 17:38 UTC, steven-sheehy requested changes

2023-08-11 17:38 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/FallbackFee.java
> +    @JsonDeserialize(using = EntityIdDeserializer.class)
Can remove

2023-08-11 17:38 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/FixedFee.java
> +    @JsonDeserialize(using = EntityIdDeserializer.class)
Remove

2023-08-11 17:38 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        return new DomainWrapperImpl<>(builder, builder::build);
Only top level domain objects should have a DomainWrapper.
```suggestion
    private FallbackFee fallbackFee() {
        return FallbackFee.builder().amount(id()).denominatingTokenId(entityId(TOKEN));
```

2023-08-11 17:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +        ObjectToStringSerializer.INSTANCE.toString();
Should add a comment about why it's necessary.

2023-08-11 17:38 UTC, steven-sheehy commented on hedera-mirror-rest/model/customFee.js
>    static CREATED_TIMESTAMP = `created_timestamp`;
Should remove this since there's no such field. Just hardcode the string in the query.

2023-08-11 18:20 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/FallbackFee.java
> +    @JsonDeserialize(using = EntityIdDeserializer.class)
Thanks I should have seen those, they are now removed.

2023-08-11 18:20 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/FixedFee.java
> +    @JsonDeserialize(using = EntityIdDeserializer.class)
Got it, they are now removed.

2023-08-11 18:20 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +        return new DomainWrapperImpl<>(builder, builder::build);
I overlooked that one, thanks I have now fixed it.

2023-08-11 18:20 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +        ObjectToStringSerializer.INSTANCE.toString();
Sounds good I have added a comment

2023-08-11 18:23 UTC, steven-sheehy approved these changes
LGTM

2023-08-11 19:48 UTC, xin-hedera approved these changes

2023-08-11 20:21 UTC, merged