HIP-584 ERC read-only precompiles enabler
hashgraph/hedera-mirror-node pull request #6466
Opened 2023-07-21 13:31 UTC by stoyanov-st

**Description**:
To be able to implement the ERC read-only precompiles we need the `AbstractReadOnlyPrecompile` from hedera-services.
Testing will be provided with the specific implementations.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-21 13:49 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
> +        return null;
Done

2023-07-21 18:09 UTC, steven-sheehy requested changes

2023-07-21 18:09 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
> +    protected TokenID tokenId;
Believe this will later become a singleton bean so we can't have shared state.

2023-07-21 18:09 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
Needs a test

2023-07-21 18:09 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
Needs test coverage

2023-07-25 14:30 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
> +    protected TokenID tokenId;
Done.

2023-07-25 14:31 UTC, stoyanov-st commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
Test for this class will be provided with the specific implementations.

2023-07-26 03:05 UTC, steven-sheehy approved these changes
LGTM

2023-07-26 03:05 UTC, merged