Add tests for eth_call functions with alias accounts
hashgraph/hedera-mirror-node pull request #6479
Opened 2023-07-24 11:57 UTC by yiliev0

**Description**: This PR introduces tests to validate the interaction of eth_call with alias accounts, specifically focusing on the isApprovedForAll, allowance, and balanceOf functions. Be advised that these tests won't work until #6454 is merged.

**Related issue(s)**:

Fixes #6465

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-24 17:26 UTC, steven-sheehy requested changes

2023-07-24 17:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        ECDSAAccount = accountClient.createNewECDSAAccount(1_000_000_000);
We already create an ECDSA account elsewhere that we should reuse here since account creation is costly on mainnet. We should add a `Key.KeyCase` parameter to `AccountNameEnum` and set all to `ED25519` except `BOB` who can be ECDSA. Then enhance `AccountClient.createCryptoAccount` to inspect keyType from enum and created appropriately.

Then change places that call `accountClient.createNewECDSAAccount(long)` to call `accountClient.createNewAccount(long, BOB)` and it will cache that account creation everywhere.

2023-07-24 17:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        ECDSAAccount = accountClient.createNewECDSAAccount(1_000_000_000);
Why does this account need 10 hbars? We should transfer the minimal hbars necessary. I think it can just be zero tinybars, right?

2023-07-25 09:19 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        ECDSAAccount = accountClient.createNewECDSAAccount(1_000_000_000);
You're correct. Changed to 0 initial balance.

2023-07-25 09:20 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +    }
Removed `verifyTx` function and changed the wait with the `verifyMirrorTransactionResponse`. Thanks for the advice!

2023-07-25 09:29 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        ECDSAAccount = accountClient.createNewECDSAAccount(1_000_000_000);
I have followed your steps and implemented the following:
* Added `Key.KeyCase` to the `AccountNameEnum` 
* Enchanced `AccountClient.createCryptoAccount` by inspecting the keyType and based on this to generate the privateKey.
* Changed `createNewAccount(long initialBalance, AccountNameEnum accountNameEnum)` to use the new implementation of `CreateCryptoAccount`
* Changed `createNewAccount(long initialBalance)` to use `Alice-ED25519` by default as it was used before in the previous implementation of `CreateCryptoAccount`. Until now `CreateCryptoAccount` was only using ED25519.
* Replaced `accountClient.createNewECDSAAccount(long)` with `accountClient.createNewAccount(long, BOB)`.

I hope I catched everything correctly from your comment. Thanks in advance!

2023-07-26 02:25 UTC, steven-sheehy requested changes

2023-07-26 02:25 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
>      public ExpandedAccountId createNewECDSAAccount(long initialBalance) {
This should now be unused, right? We should remove.

2023-07-26 02:25 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        ecdsaEaId = accountClient.createNewAccount(1_000_000_000, AccountClient.AccountNameEnum.BOB);
```suggestion
        ecdsaEaId = accountClient.getAccount(AccountClient.AccountNameEnum.BOB);
```

2023-07-26 02:25 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        ECDSAAccount = accountClient.createNewAccount(0, BOB);
Sorry, didn't realize we should actually call `getAccount` so the account is created and cached. Calling create explicitly will create multiple accounts.

```suggestion
        ECDSAAccount = accountClient.getAccount(BOB);
```

2023-07-26 02:25 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +    private ExpandedAccountId ECDSAAccount;
```suggestion
    private ExpandedAccountId ecdsaAccount;
```

2023-07-26 14:37 UTC, steven-sheehy approved these changes
LGTM

2023-07-26 20:14 UTC, merged