Add parsing support for EIP 2930 transactions
hashgraph/hedera-mirror-node pull request #6495
Opened 2023-07-26 02:04 UTC by Nana-EC

**Description**:
Add support for EIP 2930 (type 1) transactions

**Related issue(s)**:

Fixes #6494 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-28 21:29 UTC, steven-sheehy requested changes

2023-07-28 21:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip1559EthereumTransactionParser.java
> +    public static final String EIP1559_TYPE_HEX = "0x02";
Seems to be unused so should revert.

2023-07-28 21:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
> +    public static final String EIP2930_TYPE_HEX = "0x01";
This field seems to be unused

2023-07-28 21:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
> +                    String.format("1st byte was %s but should " + "be %s", legacyRlpItemByte, EIP2930_TYPE_BYTE));
```suggestion
                    String.format("First byte was %s but should be %s", legacyRlpItemByte, EIP2930_TYPE_BYTE));
```

2023-07-28 21:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
> +        if (legacyRlpItemByte != EIP2930_TYPE_BYTE) {
Why is this called a legacyRlpItem?

```suggestion
        var type = decoder.next();
        var typeByte = type.asByte();
        if (typeByte != EIP2930_TYPE_BYTE) {
```

2023-07-28 21:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
> +                            "2nd RLPItem list size was " + "%s but should be %s",
```suggestion
                            "RLP list size was %d but expected %d",
```

2023-07-28 21:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParserTest.java
> +                .satisfies(t -> assertThat(Hex.encodeHexString(t.getChainId())).isEqualTo("012a"))
Most if not all can be converted to the simpler returns:

```suggestion
                .returns(EIP2930_TYPE_BYTE, EthereumTransaction::getType)
                .returns("012a", EthereumTransaction::getChainId)
```

2023-07-29 15:44 UTC, Nana-EC reviewed
LG.
One test modification and nits on this I hadn't gotten to.



Additionally, we should have a REST API test that confirms this transactions types response.
Potentially not needed in this PR and can be in a follow up soon after.

2023-07-29 15:44 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParserTest.java
> +                .returns(0L, EthereumTransaction::getNonce)
Preferably we should use a transactions with a valid nonce.
I used available bytes at the time but may craft a transaction with > 0 nonce.

2023-07-29 15:44 UTC, Nana-EC commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParserTest.java
> + * Copyright (C) 2022-2023 Hedera Hashgraph, LLC
Not: I missed this in copying but Should probably be 2023

2023-07-29 15:44 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
> + * Copyright (C) 2022-2023 Hedera Hashgraph, LLC
nit:2023

2023-07-29 15:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip1559EthereumTransactionParser.java
> +    public static final String EIP1559_TYPE_HEX = "0x02";
Yeah left over from an initial approach I considered. Can remove.

2023-07-29 15:45 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
> +    public static final String EIP2930_TYPE_HEX = "0x01";
Yeah left over from an initial approach I considered. Can remove.

2023-07-31 17:01 UTC, xin-hedera approved these changes
LGTM

2023-07-31 17:04 UTC, steven-sheehy approved these changes
LGTM

2023-07-31 17:05 UTC, merged