5990 investigateimplement solution for gke when using zfs
hashgraph/hedera-mirror-node pull request #6512
Opened 2023-07-27 13:52 UTC by jnels124

**Description**:
* wait for node to be labeled with needed labels
* wait for disk to be available for attachment
* automatically label nodes with openebs.io/nodeid 
* detect nodes no longer in the cluster and reuse nodeid for new node
* custom csi driver image

**Related issue(s)**:

Fixes #5990 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-27 13:55 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +            mountPath: /root
should be /node

2023-07-27 14:02 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +      repository: jesseswirldslabs/zfs-driver
will push to gcr.io/mirrornode

2023-07-27 21:31 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +    echo "before print disk check"
remove

2023-07-28 18:55 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/rbac.yaml
> +    verbs: ["get", "list", "delete", "watch"]
can remove pods perms. This account doesn't need this anymore

2023-07-28 18:56 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +  zfsController:
will remove

2023-07-28 19:02 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/serviceaccount.yaml
> +  annotations:
will add common labels

2023-07-28 19:04 UTC, jnels124 commented on docs/database/zfs.md
> -### GKE Cluster Upgrade
There will be a follow up ticket to address this section. With the stackgres deployment, upgrade path is currently unknown.

2023-07-31 14:55 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +          COMMAND_STATUS=$?
will restructure slightly so not waiting 30 seconds in successful cases

2023-07-31 19:44 UTC, steven-sheehy requested changes

2023-07-31 19:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      NODE_LIST="$(kubectl get nodes -o json)"
We should only care about zfs related nodes being drained, right? Can add `-lcsi-type=zfs`.

2023-07-31 19:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +                      '.items | map ( . | select(.metadata.labels["topology.kubernetes.io/zone"] == "\($ZONE)" and
Not sure I understand jq enough and what's going on here to review this. The cognitive complexity of this script is quite high. We definitely need to move this logic to the zfs-controller soon. Let's initiate that conversation soon to see if they're willing.

2023-07-31 20:26 UTC, xin-hedera requested changes

2023-07-31 20:26 UTC, xin-hedera commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      sleep 10
unnecessary 10s sleep when attempt count has reached the max, same for the other loop with attempt count

2023-07-31 20:26 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +                      '.items | map ( . | select(.metadata.labels["topology.kubernetes.io/zone"] == "\($ZONE)" and
I agree the script is complex and very much less than ideal. Once this PR is merged, I will link to the issue i created upstream and see if they would be willing to accept a PR in the plugin code that followed similar logic.

2023-07-31 20:29 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      ZONE_CONFIG="$(echo "${MODIFIED_CONFIG_MAP}" |jq  --arg ZONE "${ZONE}" --arg CITUS_ROLE "${CITUS_ROLE}" '.data["zfs-node-status.json"]["\($CITUS_ROLE)"]["\($ZONE)"] // []')"
jq was giving compilation errors without the quotes added. Let me do a quick test and verify if they are needed.

2023-07-31 20:37 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      NODE_LIST="$(kubectl get nodes -o json)"
I can apply that filter earlier

2023-07-31 21:52 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      ZONE_CONFIG="$(echo "${MODIFIED_CONFIG_MAP}" |jq  --arg ZONE "${ZONE}" --arg CITUS_ROLE "${CITUS_ROLE}" '.data["zfs-node-status.json"]["\($CITUS_ROLE)"]["\($ZONE)"] // []')"
Don't need to escape this any longer. It was a learning issue with jq when I started this. Thanks for pointing this out.

2023-07-31 21:52 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      sleep 10
fixed this by moving some things

2023-08-01 20:06 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      NODE_LIST="$(kubectl get nodes -o json)"
I don't see that this was added?

2023-08-02 04:48 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      NODE_LIST="$(kubectl get nodes -o json)"
Instead, I just moved the citus-role and zone filters up. Technically this would still catch citus nodes that may exist and are not using zfs(i.e csi-type != zfs) however they will not effect the resulting calculations for calculating zone configurations because these nodes will never be included in the config map nor will they have the appropriate labels on the node (generated-node-id)

2023-08-02 18:44 UTC, steven-sheehy requested changes

2023-08-02 18:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/rbac.yaml
> +  name: label-reader
```suggestion
  name: zfs-label-reader
```

2023-08-02 18:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/rbac.yaml
> +  name: label-reader
```suggestion
  name: zfs-label-reader
```

2023-08-02 18:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/rbac.yaml
> +  name: configmap-updater
The namespace level RBAC should include both the release name and `zfs` in the name

```suggestion
  name: {{ include "hedera-mirror-common.fullname" . }}-zfs-configmap-updater
```

2023-08-02 18:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-zfsnodestatus.yaml
> +  name: zfs-node-status
```suggestion
  name: {{ include "hedera-mirror-common.fullname" . }}-zfs-node-status
```

2023-08-03 13:58 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/rbac.yaml
> +  name: configmap-updater
makes sense. Thanks for pointing this out.

2023-08-03 22:39 UTC, steven-sheehy requested changes

2023-08-03 22:39 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      NODE_LIST="$(kubectl get nodes -o json)"
Right, I understand it might logically be the same since you filter in memory, but isn't it more performant and safer to filter out app nodes upfront via the API? It reduces that amount of JSON returned and reduces the likelihood we may accidentally patch an app node or include it in the configmap.

2023-08-03 22:39 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +                                        .metadata.labels[$ROLE_LABEL] == $CITUS_ROLE))')"
We should use kubectl selectors to filter on the server where we can. Also seems like we only need the metadata so can return a subset.

```suggestion
      NODE_LIST="$(kubectl get nodes -lcsi-type=zfs,topology.kubernetes.io/zone=${ZONE},${ROLE_LABEL}=${CITUS_ROLE} -o jsonsonpath='{.items[*].metadata}')"
```

2023-08-03 23:27 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +    kubectl config use-context ctc
I will try again but initially when I tried I was unable to connect.

2023-08-03 23:31 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +                                        .metadata.labels[$ROLE_LABEL] == $CITUS_ROLE))')"
It would result in less data being returned in cases where we have nodes with a citus-role but not csi-type=zfs which isn't really planned to be the case. I can add the csi-type filter as well. Was mainly just left off to not have more jq logic than necessary but since you have provided other input on moving these filters out of the jq script and into kubectl args I will add this one as well.

+1 on jsonpath. Haven't worked with that before and have always just used jq.

2023-08-03 23:47 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +          path: /
I noticed the error in the output but everything installed / worked correctly so assumed it was just due to how it was defined in the default values upstream

2023-08-03 23:55 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +    kubectl config use-context ctc
You are correct it does work without this.

2023-08-04 02:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +    done
Unaddressed?

2023-08-05 03:22 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +          path: /
You changed it to the syntax in this comment that I was just highlighting as the ideal syntax. This syntax will not work though. You need to change to the syntax in the two comments directly above this.

2023-08-05 03:25 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +    done
It seems like we don't have `CITUS_ROLE` here and the syntax supported in the wait command is very limited. It doesn't support `!=""` or using `=` in the jsonpath. So we can leave as is.

2023-08-06 16:35 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
> +      NODE_LIST="$(kubectl get nodes -o json)"
This logic has been updated to use -l csi-type=zfs on the kubectl command

2023-08-06 17:38 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +          path: /
The preferred syntax you mentioned does work correctly. However, the syntax you suggested to change to produces errors. Here is the description of the mounts when using the preferred syntax.
<img width="1721" alt="Screenshot 2023-08-06 at 12 16 03 PM" src="https://github.com/hashgraph/hedera-mirror-node/assets/2379763/5d9f3c51-d80d-4dc3-aa10-938161b4e1e8">

2023-08-07 16:17 UTC, jnels124 commented on docs/database/zfs.md
> -### GKE Cluster Upgrade
This issue will be resolved by #6449 with the removal of pg partman. A small note will be added to that pr to indicate resources to check pre/post upgrade

2023-08-07 16:21 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +          path: /
You're right, it's a map not an array. I expected it to be an array since that's what the `values.yaml` had upstream but as you noted those defaults are wrong. The default upstream should be changed to `{}` and a commented out example added how to supply a value be added.

2023-08-07 16:22 UTC, steven-sheehy approved these changes
LGTM

2023-08-07 21:24 UTC, xin-hedera approved these changes
LGTM

2023-08-07 22:51 UTC, merged