Fix slow contracts results REST API endpoint
hashgraph/hedera-mirror-node pull request #6515
Opened 2023-07-27 20:17 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #6513 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-27 21:50 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/recordFileService.test.js
> +      1676540001234490000: expectedRecordFile1,
seems prettier insists to remove the single quotes `''` I put on the numbers from these two lines...

2023-07-27 21:52 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    const rows = await ContractService.getContractResultsByIdAndFilters(conditions, params, order, limit);
the original query has 3 CTEs: `entity`, `ethereum_transaction`, and `record_file`. I believe all of them are there to work around citus limitations on join between distributed tables without using distribution column, or join between local table (record_file) and distributed table.

The `entity` and `record_file` CTEs end up causing sequential table scan on two tables, that's why it timed out in performance test with mainnet staging database.

2023-07-27 21:55 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/all-params.json
> +        "payer_account_id": 5000,
add these so the payer account id between contract_result and ethereum_transaction are consistent

2023-07-27 21:55 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/internal-true.json
> +        "consensus_timestamp": "187654000123456",
these ethereum transactions consensus timestamp doesn't match contract result's.

2023-07-27 22:49 UTC, steven-sheehy requested changes

2023-07-27 22:49 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      timestampArray.push(consensusTimestamp);
It's inefficient to create a combined `payerAndTimestampArray` then inside `ContractService` split them into separate arrays. It makes more sense to just create a `payerArray` and pass it and the existing `timestampArray` to the `ContractService` as separate parameters.

2023-07-27 22:49 UTC, steven-sheehy commented on hedera-mirror-rest/service/contractService.js
> +      result[`${row.consensus_timestamp}`] = row.ethereum_transaction
Would prefer a Map over an object to avoid the back and forth conversion from number to string for the key. It's also just cleaner and easier to understand.

2023-07-27 22:49 UTC, steven-sheehy commented on hedera-mirror-rest/service/recordFileService.js
> +      result[`${row.timestamp}`] = row.record_file ? new RecordFile(row.record_file) : null;
Ditto prefer Map

2023-07-27 22:49 UTC, steven-sheehy commented on hedera-mirror-rest/service/recordFileService.js
> +        from ${RecordFile.tableName}
This separate query for each timestamp could be slow if all timestamps were in one block. Is there not some way to optimize this so it only returns the distinct blocks for the timestamps?

2023-07-28 05:25 UTC, natanasow approved these changes
LGTM, the three queries are there to work around citus limitations. Approved it to be unblocked for merging after Steven's changes request is done. 

@steven-sheehy Will be included in 0.85, right?

2023-07-28 14:39 UTC, steven-sheehy commented
> @steven-sheehy Will be included in 0.85, right?

Yes, it's a 0.85 release blocker.

2023-07-28 14:50 UTC, xin-hedera commented on hedera-mirror-rest/service/recordFileService.js
> +        from ${RecordFile.tableName}
can group by record file index then array agg the corresponding timestamps covered by a record file, in js we need to reverse the mapping

2023-07-28 17:10 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      timestampArray.push(consensusTimestamp);
the advantage of an array of objects is payers and timestamps are passed in pairs. since it's a internal function and we have good test coverage, so I think we can ignore the concern of mismatching `payers` and `timestamps` array size

2023-07-28 18:13 UTC, steven-sheehy approved these changes
LGTM

2023-07-28 18:31 UTC, jnels124 approved these changes
LGTM

2023-07-28 18:35 UTC, edwin-greene approved these changes
Looks good

2023-07-28 18:39 UTC, merged