Update network stake to be pending plus rewarded stake
hashgraph/hedera-mirror-node pull request #6562
Opened 2023-08-01 17:57 UTC by jnels124

**Description**:
* sum pending stake and rewarded stake to calculate network total stake

**Related issue(s)**:

Fixes #6394 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-08-01 18:49 UTC, steven-sheehy requested changes

2023-08-01 18:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_recalculation.sql
> +UPDATE network_stake ns
nit: Use lowercase like the rest

2023-08-01 18:49 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_recalculation.sql
Should be V1.85.x

2023-08-02 04:42 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_recalculation.sql
I was under the impression the migration versions were modeled after the release version. I will note this for the future

2023-08-02 16:29 UTC, steven-sheehy approved these changes
LGTM

2023-08-02 17:41 UTC, merged