Initial commit to rerun said migrations.
hashgraph/hedera-mirror-node pull request #6565
Opened 2023-08-01 20:42 UTC by mgoelswirlds

**Description**:
This PR is created to address re-running certain time sensitive migrations, for newer mirror nodes.

This PR modifies:
* SyntheticCryptoTransferApprovalMigration to rerun when the HAPI version changes to 0.38.10 or above.
* SyntheticNftAllowanceOwnerMigration and SyntheticTokenAllowanceOwnerMigration to rerun when the HAPI version changes to 0.37.0 or above.
* InitializeEntityBalanceMigration and TokenAccountBalanceMigration to rerun, when the first account balance file comes in.

**Related issue(s)**:

Fixes #6397

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-02 17:53 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +            applicationEventPublisher.publishEvent(new InitializeBalanceEvent(this));
If this is the first account balance file being processed and the DB is empty then publishing InitializeBalanceEvent which will rerun balance migrations.

2023-08-02 17:55 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +    private AccountBalanceFile publishInitializeAccountBalanceEvent() {
Moved this into another function to reduce cognitive complexity.

2023-08-03 14:53 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +        /*if(shouldRerun(streamFile,HAPI_VERSION_0_38_10,recordFileRepository)) {
These comments will be removed once we Merge Xin's changes to have async migration extend repeatable migration.

2023-08-04 00:26 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigration.java
> -    public SyntheticNftAllowanceOwnerMigration(@Owner JdbcTemplate jdbcTemplate, MirrorProperties mirrorProperties) {
This migration took 779 ms on mainnet.So not converting it to Async.

2023-08-04 00:26 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
This migration took 10158 ms on mainnet.So not converting it to Async.

2023-08-04 17:37 UTC, xin-hedera requested changes

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +            if (latestFile != null && latestFile.getHapiVersion().isLessThan(HAPI_VERSION_0_38_10)) {
```suggestion
            var latestFile = recordFileRepository.findLatestWithOffset(1);
            if (latestFile.filter(f -> f.getHapiVersion().isLessThan(HAPI_VERSION_0_38_10)).isPresent()) {
```

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigration.java
> +    // 779
leftover?

```suggestion
```

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/MigrationRecordStreamFileListener.java
> +public interface MigrationRecordStreamFileListener {
where is this interface used?

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +    public void reRunMigration(InitializeBalanceEvent event) {
we don't want to run it when the transaction in which the event is published fails

```suggestion
   @TransactionalEventListener(classes = InitializeBalanceEvent.class)
    public void reRunMigration() {
```

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +                event.getTimestamp());
don't see much value logging the event's created timestamp
```suggestion
        log.info("Re-running the InitializeEntityBalanceMigration on InitializeBalanceEvent");
```

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +        AccountBalanceFile lastBalanceFile = publishInitializeAccountBalanceEvent();
why does the function needs to return the balance file?

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +        var lastBalanceFile = last.get();
make it return void, then the logic is simply

```java
  if (last.get() == null) {
    publish event;
  }
```

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +        last.compareAndSet(lastBalanceFile, accountBalanceFile);
two issues

- why do we need to do `compareAndSet` instead of just `set`?
- this won't work when transaction fails, for instance, when acount_balance_file table is empty
  - the event gets published
  - parse the first account balance file
  - update last
  - transaction fails
  - re-parse the same account balance file
  - no event publish since last.get() <> null

2023-08-04 17:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
> +        return lastBalanceFile;
with the pitfalls, perhaps we should

- revert all `last` related changes here and in `AbstractStreamFileParser`
- change `InitializeEntityBalanceMigration` to implement `BalanceStreamFileListener`
- add a `CompositeBalanceStreamFileListener` as the primary bean
- In `InitializeEntityBalanceMigration.onEnd`, publish the event if `account_balance_file` table is empty
- add a `on***Event` method to `InitializeEntityBalanceMigration` with the `TransactionalEventListener` annotation to trigger the migration

2023-08-04 18:03 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/MigrationRecordStreamFileListener.java
> +public interface MigrationRecordStreamFileListener {
Leftover. will remove it.

2023-08-04 18:06 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +
For point number 2 , that's the reason I had it initially, but while some cleanup removed it. Will add it back.

2023-08-04 18:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
I doubt it can work in environment where we owner and regular user are different, e.g., `mirror_node` and `mirror_importer`.

The migration gets injected the owner `jdbcTemplate` bean because it delete rows. in some environment, `mirror_importer` may not be able to delete rows.

When the migration runs inside `onEnd`, it's in the same database transaction, and the `connection` in the thread local storage uses regular user `mirror_importer`. The migration most likely uses the same connection, and may fail to delete rows.

2023-08-08 16:33 UTC, steven-sheehy requested changes

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +            applicationEventPublisher.publishEvent(new InitializeEntityBalanceEvent(this));
I don't see the point of having the logic split into separate `onEnd()` and a `reRunMigration()`. We don't need the decoupling that Spring events provides if we're invoking it within the same class and it's not async. We should just remove the publisher and `reRunMigration` and execute the migration here in `onEnd()`.

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        if (accountBalanceFileRepository.count() == 0) {
A count query in postgresql is extremely slow and should never be used. You should be able to use the existing repository query to find the earliest row.
```suggestion
        if (accountBalanceFileRepository.findNextInRange(0, Long.MAX_VALUE).isEmpty()) {
```

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        if (accountBalanceFileRepository.count() == 0) {
We should optimize this so the query is only executed for the first stream file it's seen. This is different than just storing an atomic boolean that the migration has executed since it could've executed but rolled back.

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
There's no `0.38.10`. And we should use the lowest patch release the fix was in. It might've been in all `0.38` releases so we should use `0.38.0`, otherwise we pick the exact version.

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    private static final AtomicBoolean reRanMigration = new AtomicBoolean(false);
nit: It's redundant to have the word `migration` in the variable name.

```suggestion
    private static final AtomicBoolean executed = new AtomicBoolean(false);
```

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +        if ((streamFile.getHapiVersion()).isGreaterThanOrEqualTo(HAPI_VERSION_0_38_10) && !reRanMigration.get()) {
There's an extra parenthesis and the boolean check is not atomic, allowing multiple async processes to start.

```suggestion
        if (streamFile.getHapiVersion().isGreaterThanOrEqualTo(HAPI_VERSION_0_38_10) && executed.compareAndSet(false, true)) {
```

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +            if (latestFile != null && latestFile.getHapiVersion().isLessThan(HAPI_VERSION_0_38_10)) {
Use optional chaining for all migrations like Xin [mentioned](https://github.com/hashgraph/hedera-mirror-node/pull/6565#discussion_r1284658561).

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +                reRanMigration.set(true);
Remove after switching to compareAndSet

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
Revert changes to this file if we're using `onEnd` approach

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (var listener : listeners) {
Use indexed based for loop for performance

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        }
```suggestion
        onEach(StreamFileListener::onEnd);
```

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/InitializeEntityBalanceEvent.java
Remove both events after previous suggestions.

2023-08-08 16:33 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
Revert

2023-08-08 16:35 UTC, steven-sheehy commented
Note: Any comments on one migration can apply to all. I didn't duplicate the comments for each.

2023-08-08 17:45 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
I will change it to 38.0, but this was the comment  /`/ This problem was fixed by services release 0.38.10, this is last timestamp before that release`
in the code while writing the migration. But I see that there are releases till 0.38.6.

2023-08-08 17:53 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +            if (latestFile != null && latestFile.getHapiVersion().isLessThan(HAPI_VERSION_0_38_10)) {
Yes I missed that comment.

2023-08-08 17:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
Looking in the DB, I do see a 10 for `hapi_version_patch`. So your logic is correct. But we should check with services cause that version number seems like a bug.

2023-08-08 18:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
I asked Michael, still awaiting a response.

I checked the upstream [fix](https://github.com/hashgraph/hedera-services/commit/5d9009307de098695c44414cb3ca680fd68b5f78) and it was in all 0.38 tags. Thus I think since we have a range check we can safely use `0.38.0`.

2023-08-08 18:11 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +            applicationEventPublisher.publishEvent(new InitializeEntityBalanceEvent(this));
So even with just the onEnd approach we can ensure that the migration will run once and if the transaction is rolled back this will re-run when the file is parsed again right?

2023-08-08 18:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +            applicationEventPublisher.publishEvent(new InitializeEntityBalanceEvent(this));
Right, since it will happen synchronously and inherit the existing `AccountBalanceFileParser` transaction. The two migrations also don't need to run as owner so they're fine to run as mirror_importer user like the current transaction.

2023-08-08 18:20 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        if (accountBalanceFileRepository.count() == 0) {
Other than confirming the DB is empty I don't know of a way to verify that this is the first file.

2023-08-08 18:21 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
So services did not have a 1:1 mapping at that time. protobuf 0.38.10 went in service 0.38.6

2023-08-08 18:22 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
But since i am checking the HAPI version, I should keep it as is.

2023-08-08 18:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        if (accountBalanceFileRepository.count() == 0) {
You're not confirming it's the first file ever, you're confirming if it's the first processed by the application after startup to reduce unnecessary queries. Can store an `AtomicLong firstConsensusTimestamp = new AtomicLong(0L)` that you `compareAndSet` with zero. Then only run query if `firstConsensusTimestamp.get() == streamFile.getConsensusTimestamp()`.

2023-08-08 18:26 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
No, change to `0.38.0`. Again it should map to in which services the fix went in.

2023-08-08 20:59 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_10 = new Version(0, 38, 10);
Ahh ok. Had checked with Neeha and she had mentioned 0.38.6 had the changes but will do 0.38.0

2023-08-09 16:04 UTC, xin-hedera requested changes

2023-08-09 16:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
did you check if running it inside `onEnd` would actually pick a connection with different credentials other than owner?

this is a blocker for both `SyntheticNftAllowanceOwnerMigration` and `SyntheticTokenAllowanceOwnerMigration`

2023-08-09 16:56 UTC, steven-sheehy requested changes

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +    AtomicLong firstConsensusTimestamp = new AtomicLong(0L);
```suggestion
    private final AtomicLong firstConsensusTimestamp = new AtomicLong(0L);
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigration.java
> +    public static final Version HAPI_VERSION_0_37_0 = new Version(0, 37, 0);
```suggestion
    static final Version HAPI_VERSION_0_37_0 = new Version(0, 37, 0);
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +    public static final Version HAPI_VERSION_0_38_0 = new Version(0, 38, 0);
```suggestion
    static final Version HAPI_VERSION_0_38_0 = new Version(0, 38, 0);
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +    public static final Version HAPI_VERSION_0_37_0 = new Version(0, 37, 0);
```suggestion
    static final Version HAPI_VERSION_0_37_0 = new Version(0, 37, 0);
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +    AtomicLong firstConsensusTimestamp = new AtomicLong(0L);
```suggestion
    private final AtomicLong firstConsensusTimestamp = new AtomicLong(0L);
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalsMigrationTest.java
> +    public static final long START_TIMESTAMP = 1568415600193620000L;
```suggestion
    private static final long START_TIMESTAMP = 1568415600193620000L;
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +    void reRunOnEndMigration() {
```suggestion
    void onEnd() {
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigrationTest.java
> +    void reRunMigrate() {
```suggestion
    void onEnd() {
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +    void reRunMigrate() {
```suggestion
    void onEnd() {
```

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +    void reRunMigrate() {
We should have test cases for when database is not empty after startup and when db is empty but not first stream file (i.e. transaction rollback scenario). Same comment for other balance test.

2023-08-09 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +    void reRunOnEndMigration() {
Missing test coverage for when `onEnd()` is invoked but it should not run migration. Same for other record migration tests.

2023-08-09 17:59 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
No I did not. Will need to check this.

2023-08-09 22:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
we can discuss. running with `mirror_importer` may not break ourselves but can break other mirrornode operators in case in their environment `mirror_importer` doesn't have permission to delete rows.

then we may have to turn these two migrations to be async.

2023-08-10 00:30 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
Ok. Lets discuss further offline.

2023-08-10 19:27 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +public class SyntheticTokenAllowanceOwnerMigration extends RepeatableMigration implements RecordStreamFileListener {
I verified that even when migrate is called from with the onEnd it uses the mirror_node user.

2023-08-10 20:25 UTC, xin-hedera requested changes

2023-08-10 20:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
can you explain why it becomes so complicated? I don't think I can fully understand the logic here

2023-08-10 20:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +                var latestFile = recordFileRepository.findLatestWithOffset(1);
`findLatestWithOffset(1)` may or may not get the record file you want.

Issue here is, we do `recordFileRepository.save(recordFile)` in `SqlEntityListener.onEnd()`. So if the bean `sqlEntityListener` is before the bean `syntheticCryptoTransferApprovalMigration` in `compositeRecordStreamFileListener`, the logic is fine.

Otherwise, let say the `streamFile` being processed has index `current`, the repository method is going to return `current - 2`.

Instead, we should find the latest record file whose `consensus_end` is before `streamFile.consensusStart`

2023-08-10 20:25 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigration.java
> +    // 10158
leftover

```suggestion
```

2023-08-10 20:25 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/viewmodel/DummyRequest.java
> +public class DummyRequest {
mixed up with the other ticket

2023-08-10 20:41 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +                var latestFile = recordFileRepository.findLatestWithOffset(1);
'''So if the bean sqlEntityListener is before the bean syntheticCryptoTransferApprovalMigration in compositeRecordStreamFileListener''' - This is what I had observed while manually testing.

2023-08-10 20:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +                var latestFile = recordFileRepository.findLatestWithOffset(1);
what if we move that out of sqlEntityListener.onEnd?

2023-08-10 20:45 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
Yes. That is because the migration update records when there is data in the account_balance_file table.
So while writing some tests i realized that the migration was not updating any records when run on an empty account_balance_file table. Hence we need to run the migration when the second file is being processed, which ensures that the first file has been parsed and committed. I hope that clears it.
And to ensure that the migration is run only when the second file is being parsed and to optimize to not use DB calls everytime, I added a second timestamp.

2023-08-10 20:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
then, we should move the `accountBalanceFileRepository.save(accountBalanceFile)` call into `CompositeAccountBalanceFileListener.onEnd` before calling each `listener.onEnd`, you can change this back to the more straight forward check with just the `firstConsensusTimestamp`

If you do the same to `compositeRecordStreamFileListener.onEnd`, you can keep `recordFileRepository.findLatestWithOffset(1);` in my other comment

2023-08-10 21:10 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
This will not work. I guess I missed mentioning a point earlier. The data needs to be committed for the migration to work. Unless I actually commit and then do this migration in a separate transaction , it might not work.

2023-08-10 21:12 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +                var latestFile = recordFileRepository.findLatestWithOffset(1);
The sqlEntityListener bean is before syntheticCryptoTransferApprovalMigration, but maybe you earlier approach for timestamp might be better.

2023-08-10 21:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        }
yes it'll work.

- inside the same database transaction, changes before a statement are visible just like they were commited
- `InitializeEntityBalanceMigration` is synchronous, so when `doMigrate` is called in `onEnd`, all statements run in the same db transaction started from `BalanceFileParser.parse`

it didn't work because the migration relied on `account_balance_file `table having the correct row and in `AccountBalanceFileParser.doParse`, saving the account balance file is after `streamFileListener.onEnd`.

That's why I ask you to move `accountBalanceFileRepository.save` from inside `AccountBalanceFileParser.doParse` to `CompositeAccountBalanceFileListener.onEnd` and before any other listener.onEnd

2023-08-10 21:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalMigration.java
> +                var latestFile = recordFileRepository.findLatestWithOffset(1);
right I understand what you mean. however depending on implicit condition is error prone.

2023-08-14 19:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                return;
you need to set first to -1, when it's not set and there are account balance files in db before this one. Doing so then it'll shortcut at the beginning.

2023-08-14 19:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +        if (firstConsensusTimestamp.get() == -1 || succeeded.get()) return;
```suggestion
        if (firstConsensusTimestamp.get() == -1 || succeeded.get()) {
          return;
        }
```

2023-08-14 19:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +                >= firstConsensusTimestamp.get()) {
optional chaining: `findLatest().map(getConsensusEnd).filter(timestamp -> timestamp >= first.get()).isPresent()`

2023-08-14 19:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +        succeeded.compareAndSet(false, true);
just set it to true

```suggestion
        succeeded.set(true);
```

2023-08-14 19:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigration.java
> +        if (recordFileRepository.findLatest().map(RecordFile::getConsensusEnd).orElse(-1L)
there should be an empty line in between these `if` blocks

2023-08-14 22:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +    public void onEnd(AccountBalanceFile accountBalanceFile) throws ImporterException {
should try to pull the logic in `onEnd` to an abstract base class, since it's exactly the same in `InitializeEntityBalanceMigration.java` and `TokenAccountBalanceMigration.java`

also add comments to demystify the logic and the values (especially -1).

2023-08-15 14:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
> +abstract class TimeSensitiveBalanceMigration extends RepeatableMigration implements TransactionSynchronization {
the base class should also implement `BalanceStreamFileListener`, so the `onEnd` logic is completely in the base

2023-08-15 15:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java
> +        implements BalanceStreamFileListener {
```suggestion
public class InitializeEntityBalanceMigration extends TimeSensitiveBalanceMigration {
```

same for the other migration

2023-08-15 15:41 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
> +        this.accountBalanceFileRepository = accountBalanceFileRepository;
Will move tests for this class.

2023-08-15 17:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (int i = 0; i < listeners.size(); i++) {
you second part of the response is wrong. That condition of the check is between latest record file in db and the current account balance file in memory, so the migration may end up doing nothing.

2023-08-15 17:53 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (int i = 0; i < listeners.size(); i++) {
Agreed.There is still uncertainty with this.While testing locally it does have account balance file in the DB.

2023-08-15 17:58 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (int i = 0; i < listeners.size(); i++) {
In the case where the migration does not do anything, one might have to manually run it. I have added the link in the ReadMe.

2023-08-15 18:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (int i = 0; i < listeners.size(); i++) {
that's not the resolution, right? if we choose to just ask operators to rerun it manually, what's the point of the updated algorithm?

2023-08-15 18:11 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (int i = 0; i < listeners.size(); i++) {
This could happen in some cases. But what you say is fair. I need to fix it to be more deterministic.

2023-08-16 04:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/RecordFileRepository.java
> +    Optional<RecordFile> findLatestBefore(long offset);
Needs a test

2023-08-16 04:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceFileRepository.java
> +    Optional<AccountBalanceFile> findLatestBefore(long timestamp);
Needs a test

2023-08-16 04:19 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/CompositeBalanceStreamFileListener.java
> +        for (int i = 0; i < listeners.size(); i++) {
> Ahh unfortunately I can't do this. Because errata Migration updates the TimeOffset for this in onEnd.

Just save it twice.

2023-08-16 14:38 UTC, steven-sheehy requested changes

2023-08-16 14:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
> +    private final AtomicBoolean succeeded = new AtomicBoolean(false);
Better to be consistent with the other migrations.

```suggestion
    private final AtomicBoolean executed = new AtomicBoolean(false);
```

2023-08-16 14:55 UTC, steven-sheehy requested changes

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TokenAccountBalanceMigrationTest.java
> +    private AccountBalanceFile accountBalanceFile1, accountBalanceFile2;
Our standard is to always declare on a separate line.

```suggestion
    private AccountBalanceFile accountBalanceFile1;
    private AccountBalanceFile accountBalanceFile2;
```

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalsMigrationTest.java
> +        // given
duplicate given section

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalsMigrationTest.java
> +        // given
duplicate given

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalsMigrationTest.java
> +                .entity()
There's a lot of duplicate setup in different tests. Can they be pulled to a common setup method to reduce duplication and so the test is clear what it's specifically testing? Balance migration tests do this and is much more readable.

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalsMigrationTest.java
> +        assertThat(cryptoTransferRepository.findAll()).containsExactlyInAnyOrderElementsOf(expectedCryptoTransfers);
Use the more succinct `List.of()`. Same comment for other assertions.

```suggestion
assertThat(cryptoTransferRepository.findAll()).containsExactlyInAnyOrderElementsOf(List.of(cryptoTransfersPair.getLeft(), cryptoTransfersPair.getRight()));
```

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticTokenAllowanceOwnerMigrationTest.java
> +        var spender = 39L;
Can we move this to a common setup method shared across all tests?

2023-08-16 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigrationTest.java
> +        // This nft allowance and it's history should be unaffected by the migration
Can we move this to a common setup method shared across all tests?

2023-08-16 15:47 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigrationTest.java
> +        // This nft allowance and it's history should be unaffected by the migration
Not sure what you mean. Setup for nft allowances and token allowances moved to a common place?

2023-08-16 18:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigrationTest.java
> +        // This nft allowance and it's history should be unaffected by the migration
I'm speaking in broader terms, not these couple lines above. I can't highlight in a review discussion all impacted lines. In general, each of these `onEnd*()` tests and even the original `migrate` tests setup the test scenario data (e.g. everything in a `given` block), run the method under test, then verify the results. 

They only vary slightly by setting properties, delete some data, etc. Just like in the balance migration tests, we can move this common setup to a helper method to stay DRY.

2023-08-16 18:11 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
> +            if (firstConsensusTimestamp.get() == -1 || succeeded.get()) {
I see. Well in that case I think we should use static values for 0 and 1 so they're self-descriptive regardless.

```java
private static final int NO_BALANCE_FILE = 0;
private static final int EXECUTED = -1;
```

In which case I think it's much clearer and we can drop the executed/succeeded.

2023-08-16 20:09 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
The code coverage is not accurate, because the tests do cover the branches in the method, but it still shows that as not covered.

2023-08-16 20:27 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigrationTest.java
> +        // This nft allowance and it's history should be unaffected by the migration
I understand. I just wanted to understand if it was for both these tests overall.

2023-08-17 14:37 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticNftAllowanceOwnerMigrationTest.java
> +        // This nft allowance and it's history should be unaffected by the migration
I have refactored within the test to have a setup methods within the tests.

2023-08-17 14:46 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +    void onEndWhenNotFirstFile() {
these test cases don't test what they claim.

The central problem is `initializeEntityBalanceMigration` is a singleton bean, so the `firstConsensusTimestamp` stateful variable once set to -1, it generally doesn't test anything in any test cases which run afterwards.

you may wonder why the `onEnd` test case still passes, that's because the expected balance for the entities is set in `setup` but not in `setupForFirstAccountBalanceFile`.

This also explains why there is missing test coverage and I believe the warnings put by codecov is accurate

2023-08-18 13:26 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +    }
can just create a new `InitializeEntityBalanceMigration` object for each of those test cases which depend on `firstConsensusTimestamp`

2023-08-18 14:30 UTC, steven-sheehy requested changes

2023-08-18 14:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
> +    private final AtomicLong firstConsensusTimestamp = new AtomicLong(0L);
```suggestion
    private final AtomicLong firstConsensusTimestamp = new AtomicLong(NO_BALANCE_FILE);
```

2023-08-18 14:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TimeSensitiveBalanceMigration.java
> +    private static final int EXECUTED = -1;
```suggestion
    private static final long EXECUTED = -1L;
    private static final long NO_BALANCE_FILE = 0L;

```

2023-08-18 14:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SyntheticCryptoTransferApprovalsMigrationTest.java
> +    private static final RecordFile RECORD_FILE = RecordFile.builder()
nit: Move above with other statics

2023-08-18 16:11 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-08-18 16:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +                jdbcOperations, mirrorProperties, accountBalanceFileRepository, recordFileRepository);
This variable hides the injected class bean. We should make the class `migration` non-final and move this creation to a `@BeforeEach`. Same comment for all other test classes.

2023-08-18 16:59 UTC, steven-sheehy approved these changes
LGTM

2023-08-18 17:45 UTC, xin-hedera approved these changes
LGTM

2023-08-18 18:01 UTC, merged