HIP-584: Implement integration tests for token metadata & info functions for estimate_Gas
hashgraph/hedera-mirror-node pull request #6569
Opened 2023-08-02 14:27 UTC by MrValioBg

**Description**:

Adds integration tests for the token metadata and token info readonly functions for estimate gas.

* In `ContractCallServicePrecompileTest` new test case for estimate_Gas is added. It uses the already existing enum `ContractReadFunctions`, thus providing tests for all the metadata token functions.
* New enum values are added for the token information functions.
* `estimateGasIterationThreshold` is increased to 7300, in order to support the test for the `getInformation` functions for NFTs.

**Related issue(s)**:

Fixes #5598
Fixes #5599 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-08-04 07:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        GET_INFORMATION_FOR_TOKEN_NFT("getInformationForToken", new Object[] {NFT_ADDRESS}, new Object[] {});
Just to notify - we should consider refactoring this enum by adding complex return type objects for `getCustomFees` and `getTokenInfo` scenarios and by doing that we could directly use the enum values to validate the test and remove the `exclude` property. Then we could delete the stand-alone tests for `getCustomFees` and `getTokenInfo` and simplify the tests organisation and maintainability. 

I have logged a package in our backlog, covering this.

2023-08-04 07:31 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2023-08-04 07:37 UTC, bilyana-gospodinova approved these changes
LGTM

2023-08-04 07:44 UTC, MrValioBg commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        GET_INFORMATION_FOR_TOKEN_NFT("getInformationForToken", new Object[] {NFT_ADDRESS}, new Object[] {});
Great, thank you for taking care of this :) !

2023-08-05 03:06 UTC, steven-sheehy requested changes
LGTM besides conflict and doc request

2023-08-05 03:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long estimateGasIterationThreshold = 7300L;
Need to document the change in `docs/configuration.md`.

2023-08-07 07:51 UTC, MrValioBg commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long estimateGasIterationThreshold = 7300L;
Done :)

2023-08-07 16:37 UTC, steven-sheehy approved these changes

2023-08-07 16:38 UTC, merged