Acceptance tests for token allowance amounts
hashgraph/hedera-mirror-node pull request #6592
Opened 2023-08-04 22:01 UTC by jascks

**Description**:
With the implementation of #3576 completed, implement acceptance tests around the new functionality provided, namely crypto and token allowance definition and that approved crypto/fungible token transfers are properly reflected in the allowance balances.

- Create fungible token and allowance defining appropriate owner and spender IDs.
- Verify existence and expected configuration via mirror node rest api
- Perform fungible token transfer, both approved utilizing the owner and spender as expected, as well as other scenarios that should not affect the allowance balances.
- Refer to code recently added to clean up and recover HBARs spent

**Related issue(s)**:

Fixes #6553

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-07 16:58 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        FUNGIBLE(
Only defined what I required for this issue. Other token configs can be defined in the future as required.

2023-08-07 17:00 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTransfer.java
> +    @JsonProperty("is_approval")
Apparently Jackson could not figure this out. Even though the API JSON indicated:
```
            "token_transfers": [
                {
                    "account": "0.0.7046",
                    "amount": -100,
                    "is_approval": true,
                    "token_id": "0.0.7047"
                },
```
I was always getting `isApproval` to be false.

2023-08-07 17:06 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +      | "FUNGIBLE" | 10000          | 100            |
p.s., we tend to include additional steps in existing scenarios unless perhaps it becomes too confusing. The reason is we need to make acceptance tests cost effective, here an additional token is created for the scenario, and token creation is quite expensive.

2023-08-08 03:19 UTC, steven-sheehy requested changes

2023-08-08 03:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +    Given I associate a new recipient account with token 0
This creates two new accounts. We should reuse BOB and CAROL like in the crypto allowance test.

2023-08-08 03:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        tokenIds.add(tokenId);
Putting it in tokenIds means it gets cleaned up in the `@After`, but we want this token to stick around to be reused in other features. Hence, why we're caching it in TokenClient.

2023-08-08 03:19 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +    Given I transfer <transferAmount> tokens 0 to recipient 0
I don't think we can use the index based approach since it will delete the shared accounts and tokens after the feature. Any new step we add should not use the index based approach. We can convert the existing steps to support a string for name and check if it's enum or number and use appropriately.

2023-08-08 14:24 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +      | "FUNGIBLE" | 10000          | 100            |
This is similar to `cryptoAllowance.feature`, except that there are additional steps to create a token and associate it with spender and recipient. The story goes:

1. I (owner/operator) create an allowance (crypto or fungible token).
2. I (owner, not spender) transfer crypto/tokens to recipient. The allowance is unchanged (no debit to `amount`)
3. The spender transfers crypto/tokens to recipient. An approved transfer occurred and the allowance`amount` is debited according.
4. I create a new allowance for sender.  The allowance has been essentially re-established.
5. I delete the allowance. The allowance has been deleted.

Of course there are numerous (free) mirror node API calls around that. Let me know what does not need to be tested and I will eliminate it.

2023-08-08 14:27 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +      | "FUNGIBLE" | 10000          | 100            |
Regarding the new feature/merge with existing feature question, I think it is cleaner for the feature to be separate, but the concern for cost is obviously a real one. Based on what we agree actually needs to be tested, perhaps a simpler version of `tokenAllowance.feature` can be integrated into the mentioned `token.feature` scenario.

2023-08-08 14:54 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        private final TokenType tokenType;
Why not hardcode it here in the daylight rather than down in some private method somewhere? As this token re-use mechanism gets adopted, a future test writer can see the options available and if one is not suitable they can define a new one.

2023-08-08 14:59 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        private final TokenType tokenType;
YAGNI. We should push users to not need all that customization and keep it simple with a couple generic tokens for all use cases.

2023-08-08 14:59 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        tokenIds.add(tokenId);
Doh. Yes!

2023-08-08 16:47 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenAllowanceResponse.java
> +    List<MirrorTokenAllowance> allowances;
Done! Extending `MirrorTransferAllowance` serves no purpose. The object contains the deserialized JSON result of the REST API and is used only in one place and the first thing the assert logic does is call `getAllowances()` and go from there. 

The tests still pass. Also fixed this in `MirrorCryptoAllowanceResponse`.

2023-08-08 16:55 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAccountBalance.java
> -    private String tokenId;
Done. Not sure how this happened. This has been restored. This class is referenced only in `MirrorCryptoBalance`, which is then referenced only in `MirrorBalancesResponse`, which then is referenced nowhere, at least according to IDEA.

2023-08-08 19:52 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        tokenIds.add(tokenId);
Done!

2023-08-08 19:53 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAccountBalance.java
> -    private String tokenId;
Done

2023-08-08 20:00 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +      | "FUNGIBLE" | 10000          | 100            |
Okay, please let me know what you think of the update to this file and the related clients and token feature. I've not cleaned up `TokenFeature` yet, but before going too much further this direction and proceeding to implement any other features in this manner, I want to hear your feedback on what you see before you.

The steps are all now utilizing the re-usable tokens (new in this PR) and accounts (existing).  The index based stuff is not used here. Also, you will notice the state (tokenId, spenderId etc.) is being kept in the Ghirkin text rather than fields in the Java feature code. I kind of prefer that, but you may have a different opinion.

2023-08-08 20:09 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +                return createNewAccount(DEFAULT_INITIAL_BALANCE, accountNameEnum);
Looks like token transfer fees are about 835,000 tℏ and `SMALL_INITIAL_BALANCE` is only 500,000, resulting in transaction failure with `INSUFFICIENT_PAYER_BALANCE`.

2023-08-08 21:26 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +      | "FUNGIBLE" | 10000          | 100            |
It's fair to have it in a separate scenario if we intend to change all token creation to use the new method.

For the steps outlined, a couple of things

- shouldn't have the step which checks a direct owner to recipient transfer does not affect the allowance, this is a negative test case and usually we don't do negative test in acceptance test suite
- I don't think spender and token association is needed, after all, the spender transfers the token on behalf of the owner

2023-08-08 21:33 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +    Given I transfer <transferAmount> tokens 0 to recipient 0
Done. Moved on to named tokens and accounts.

2023-08-08 21:33 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +    Given I associate a new recipient account with token 0
Done.

2023-08-08 21:34 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/tokenAllowance.feature
> +      | "FUNGIBLE" | 10000          | 100            |
Done! Awesome, I have removed those steps. It runs noticeable faster now. :)

2023-08-08 21:55 UTC, xin-hedera requested changes

2023-08-08 21:55 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAllowance.java
> +}
`amount` and `amountGranted` are already in the base class.

btw, we should rename the base class `MirrorTransferAllowance` to either `MirrorAllowance` or `MirrorFungibleAllowance` for better clarity.

2023-08-08 21:55 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void verifyMirrorAPIApprovedTokenAllowanceResponse(
add the annotation to retry all these public methods which assert certain value from mirrornode rest api since it takes time for the changes being finalized in consensus nodes then propagated and persisted by mirrornode importer

also check the crypto allowance changes make sure it's not missed there.

```suggestion
    @RetryAsserts
    public void verifyMirrorAPIApprovedTokenAllowanceResponse(
```

2023-08-09 12:23 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAllowance.java
> +}
The base class `MirrorTransferAllowance` defines `owner`, `spender` and `timestamp` only, and does not extend anything else.  It defines no amount related fields.

However, both `MirrorTokenAllowance` and `MirrorCryptoAllowance` extend `MirrorTransferAllowance` and add `amount` and `amountGranted`. We could instead have `MirrorTokenAllowance` extend `MirrorCryptoAllowance` and just add  `tokenId`.

The base class `MirrorTransferAllowance` does not really define an allowance of any kind with only `owner`, `spender` and `timestamp`, and should perhaps be abstract. Or, since there are no other subclasses than the two above, it should go a way and `MirrorCryptoAllowance` encompass its fields and also be the base class of `MirrorTokenAllowance` as described above.

2023-08-09 17:06 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorTokenAllowance.java
> +}
Done! After out of band discussion, changes now committed.

2023-08-09 19:49 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        private final TokenType tokenType;
This has been done.

2023-08-10 20:40 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/contract/call.feature
> +    Given I ensure token <fungibleTokenName> has been created
don't think you need the examples section since I don't see a need even in the future we set `nonFungibleTokenName` to sth other than `NFT`, same for `fungibleTokenName`

2023-08-11 14:21 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/contract/call.feature
> +    Given I ensure token <fungibleTokenName> has been created
Okay, good to know. Done!

2023-08-11 19:39 UTC, steven-sheehy approved these changes
LGTM

2023-08-11 19:39 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        // If just now created, then ensure transaction has been seen by mirror node and receipt was available
This doesn't actually ensure that the transaction has been seen by mirror node, just consensus nodes, right? Does it need to to avoid race conditions?

2023-08-11 19:58 UTC, merged

2023-08-12 16:33 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        // If just now created, then ensure transaction has been seen by mirror node and receipt was available
Oooh... Yes, this is only an interaction with the consensus nodes (HAPI). My comment is a lie! While that did appear to solve the issue, it could become problematic again.

When using the named token mechanism (`TokenClient.getToken()`) the token may or may not be created. So there may or may not be a transaction. Instead, in this step, after calling `getToken()` the mirror node API should be invoked to ensure the token exists (`/api/v1/tokens?token.id=<tokenId>`) with the standard retry template retrying 404.

Does that make sense? I can create a new ticket and PR to address this.

2023-08-12 20:39 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        // If just now created, then ensure transaction has been seen by mirror node and receipt was available
Can just ensure the transaction is present on mirror node

2023-08-14 17:32 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        // If just now created, then ensure transaction has been seen by mirror node and receipt was available
Created issue #6648, opened PR #6649.