Upgrade to Citus 12
hashgraph/hedera-mirror-node pull request #6611
Opened 2023-08-08 02:30 UTC by jnels124

**Description**:
* upgrade to citus 12
* upgrade to postgres 15
* drop debian citus image
* use citus create_time_partitions to create partitions
* remove pg_partman
* remove pg_cron
* add spring scheduled task to create partitions as needed

**Related issue(s)**:

Fixes #6449 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-08 14:02 UTC, jnels124 commented on docs/importer/README.md
> +Github CI workflows (amd64). In production environments, citus is enabled through stackgres SGShardedCluster and doesn't use the custom image.
ci uses stackgres

2023-08-08 16:38 UTC, steven-sheehy requested changes
Some early feedback

2023-08-08 19:50 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +                             '
I am going to look into that. They are here currently because flyway user doesn't have the appropriate permissions to create a cast against bigint and timestamptz. So the plan is to update these superuser scripts to give the db owner permissions to create those casts and then will move these into the static partitions migration

2023-08-08 19:53 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/docker/Dockerfile
Nope  we will be able to remove this one and checkout directly from upstream to build.  That is better than my plan of having the bare image in our repo and just change the import to `FROM citusdata:12.0-alpine`

2023-08-08 19:58 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +                             '
Flyway user should be `mirror_node` who is the database owner. Unless you're doing it as a Java migration then you need to put `@Owner` on the `JdbcTemplate` to force it to be owner.

2023-08-08 21:05 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +                             '
I recall the problem is superuser permission is required to `create cast`

2023-08-10 01:26 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +                             '
Yes creating the casts is the issue. I am still going to try to update the superuser scripts to grant the mirror_node user the permission to create the casts and then move the actual UDF's and casts to the migration but haven't spent much time there yet.

2023-08-11 18:22 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/PartitionMaintenanceService.java
most of this sql will be moved to a udf in migration

2023-08-12 07:19 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/PartitionMaintenance.java
> +    private final Timer maintenanceMetric;
We can probably toss this metric because the infrequency but left it for now.

2023-08-12 17:10 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +                             '
There is no permission that would allow mirror_node user to create the cast unless we give them ownership of the timestamptz type

2023-08-13 00:36 UTC, jnels124 commented on docs/importer/README.md
> +The citus image is built and then pushed to our [Docker Hub repository](https://hub.docker.com/repository/docker/mirrornodeswirldslabs/citus/general).
will update to gcr

2023-08-13 15:24 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__static_partitioning.sql
> +                   when tp.partition_column::varchar ~ timePartitionRegex
Can possibly change this query for this to be a left join against pg_catalog so we can use this function for initial partition creation as well but opted not to do that initially since already had the original definitions

2023-08-15 20:30 UTC, steven-sheehy requested changes
Still reviewing the large SQL

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-graphql/src/test/resources/application.yml
> +      partitionIdInterval: "'.001 seconds'"
```suggestion
      partitionIdInterval: "'1 year'"
```

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
>  flyway.placeholders.partitionStartDate='3 years'
```suggestion
flyway.placeholders.partitionStartDate='4 years'
```

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/resources/config/application.yml
> +      partitionStartDate: "(CURRENT_TIMESTAMP - '1970-01-01 00:00:00.000')"
Why not `0 days` like the other test resources? Or alternatively convert everywhere else to this expression.

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/resources/config/application.yml
> +      partitionTimeInterval: "'10 years'"
```suggestion
      partitionTimeInterval: "'1 year'"
```

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +      "placeholders.partitionStartDate": "(CURRENT_TIMESTAMP - '1970-01-01 00:00:00.000')",
```suggestion
      "placeholders.partitionStartDate": "'0 days'",
```

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/resources/application.yml
> +      partitionTimeInterval: "'10 years'"
```suggestion
      partitionStartDate: "'0 days'"
      partitionTimeInterval: "'1 year'"
```

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> +        connection-init-sql: ${spring.datasource.hikari.connection-init-sql}
Use camel case and this is the opposite dependency as we have for the others. We should invert so hikari uses db properties. Also, we can probably drop separate tempTableBufferSize property

```suggestion
        connectionInitSql: set temp_buffers='256MB'; set timezone TO 'UTC';
```

2023-08-15 20:30 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/JdbcTemplateConfiguration.java
> +        dataSource.setConnectionInitSql(dbProperties.getConnectionInitSql());
Can move this setConnectionInitSql into createDataSource

2023-08-16 20:41 UTC, jnels124 commented on hedera-mirror-importer/src/test/resources/config/application.yml
> +      partitionStartDate: "(CURRENT_TIMESTAMP - '1970-01-01 00:00:00.000')"
I converted the expression everywhere. We need to have partitions that start at timestamp 0 so tests don't fail. Previously, partman was creating a default partitions to put things in.

2023-08-16 21:11 UTC, jnels124 commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +      "placeholders.partitionStartDate": "(CURRENT_TIMESTAMP - '1970-01-01 00:00:00.000')",
this needs to be the expression that it is so that we can create partitions capable of storing data with consensus timestamps that resolve to prior to genesis.

2023-08-17 06:57 UTC, jnels124 commented on hedera-mirror-importer/src/test/resources/config/application.yml
> +      partitionTimeInterval: "'10 years'"
do you still want this to be only a year given i got rid of the 0 days? This will create a partition for every year since 1970 instead of 1 per decade.

2023-08-17 16:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/resources/config/application.yml
> +      partitionTimeInterval: "'10 years'"
I don't care about the exact value for tests as long as it's a) consistent across all modules and b) doesn't cause test slowdown.

2023-08-18 00:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__static_partitioning.sql
> +    timePartitionRegex varchar = '^(.*_timestamp|consensus_end)$';
```suggestion
    timePartitionPattern varchar = '^(.*_timestamp|consensus_end)$';
```

2023-08-18 00:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__static_partitioning.sql
> +            if partitionInfo.time_partition then
There's a lot of if time_partition logic here. It might make be cleaner to just create two separate `mirror_node_create_time_partitions()` and `mirror_node_create_range_partitions()` that can be called separately.

2023-08-18 02:55 UTC, jnels124 commented on charts/hedera-mirror/ci/v2-values.yaml
> +    SPRING_FLYWAY_PLACEHOLDERS_PARTITIONSTARTDATE: "(CURRENT_TIMESTAMP - '1970-01-01 00:00:00.000')"
yes we should set that here for consistency.

2023-08-18 19:10 UTC, xin-hedera requested changes

2023-08-18 20:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> -      connection-init-sql: set temp_buffers='${hedera.mirror.importer.parser.tempTableBufferSize}MB'
Agreed. My recommendation was just to move the `set temp_buffers` from hikari prop to our props and possibly hardcode the size.

2023-08-18 21:11 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/application.yml
> -      connection-init-sql: set temp_buffers='${hedera.mirror.importer.parser.tempTableBufferSize}MB'
If we specify the timezone in the string as `1970-01-01 00:00:00+00::timestamptz` when ran in central time this will create partitions starting in 1969. If ran with UTC as the timezone it correctly starts in 1970

2023-08-18 21:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> -      connection-init-sql: set temp_buffers='${hedera.mirror.importer.parser.tempTableBufferSize}MB'
So it sounds like it’s just the partition name become misleading since there is no time zone info, however the actual range should be correct, right?

2023-08-18 21:15 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/application.yml
> -      connection-init-sql: set temp_buffers='${hedera.mirror.importer.parser.tempTableBufferSize}MB'
@steven-sheehy apologies i must have misread. Thought it said can be removed.

2023-08-18 22:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> -      parser:
since we decided to hardcode `temp_buffers`, should remove it from `CommonParserProperties` and `configuration.md`

2023-08-18 23:14 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/application.yml
> -      connection-init-sql: set temp_buffers='${hedera.mirror.importer.parser.tempTableBufferSize}MB'
Actually the name and values are off. They both represent the value in the timezone of the jdbcdriver

 When running the following with the jdbc driver 
`select create_time_partitions(table_name :='public.transaction',
                              partition_interval := interval ${partitionTimeInterval},
                              start_from := '1970-01-01 00:00:00.000+00'::timestamptz,
                              end_at := '2040-01-01 00:00:00.000+00'::timestamptz);`

you get

`transaction_p1969 FOR VALUES FROM ('-31514400000000000') TO ('284018400000000000'),
            transaction_p1979 FOR VALUES FROM ('284018400000000000') TO ('599637600000000000'),
            transaction_p1989 FOR VALUES FROM ('599637600000000000') TO ('915170400000000000'),
            transaction_p1999 FOR VALUES FROM ('915170400000000000') TO ('1230789600000000000'),
            transaction_p2009 FOR VALUES FROM ('1230789600000000000') TO ('1546322400000000000'),
            transaction_p2019 FOR VALUES FROM ('1546322400000000000') TO ('1861941600000000000'),
            transaction_p2029 FOR VALUES FROM ('1861941600000000000') TO ('2177474400000000000'),
            transaction_p2039 FOR VALUES FROM ('2177474400000000000') TO ('2493093600000000000')`

I can create a ticket upstream and see if they will enforce utc time for partition creation.

2023-08-18 23:18 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/application.yml
> -      parser:
Was accidentally in my test changelist so the commoneparserproperties didnt get committed. It is there now.

2023-08-19 00:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> -      connection-init-sql: set temp_buffers='${hedera.mirror.importer.parser.tempTableBufferSize}MB'
I see.

traced a little bit, unfortunately the issue is here in get_missing_time_partition_ranges:

```sql
    IF current_range_from_value is NULL THEN
        -- Decide on the current_range_from_value of the initial partition according to interval of the table.
        -- Since we will create all other partitions by adding intervals, truncating given start time will provide
        -- more intuitive interval ranges, instead of starting from from_value directly.
        IF partition_interval < INTERVAL '1 hour' THEN
            current_range_from_value = date_trunc('minute', from_value);
        ELSIF partition_interval < INTERVAL '1 day' THEN
            current_range_from_value = date_trunc('hour', from_value);
        ELSIF partition_interval < INTERVAL '1 week' THEN
            current_range_from_value = date_trunc('day', from_value);
        ELSIF partition_interval < INTERVAL '1 month' THEN
            current_range_from_value = date_trunc('week', from_value);
        ELSIF partition_interval = INTERVAL '3 months' THEN
            current_range_from_value = date_trunc('quarter', from_value);
        ELSIF partition_interval < INTERVAL '1 year' THEN
            current_range_from_value = date_trunc('month', from_value);
        ELSE
            current_range_from_value = date_trunc('year', from_value);
        END IF;

        current_range_to_value := current_range_from_value + partition_interval;
```

specifically, when interval is `1 month`, we do

```
        ELSIF partition_interval < INTERVAL '1 year' THEN
            current_range_from_value = date_trunc('month', from_value);
```

the returned value will be 1969/12/01 when the timezone is CST... This can be fixed by `date_trunc('month', from_value, 'UTC')

2023-08-19 01:21 UTC, steven-sheehy requested changes

2023-08-19 01:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/application.yml
> +      autovacuumVacuumInsertThresholdTransaction: 100000
Believe these snuck in from your other PR.

2023-08-21 14:04 UTC, xin-hedera approved these changes
LGTM

2023-08-21 14:34 UTC, steven-sheehy approved these changes
LGTM

2023-08-21 15:12 UTC, merged