HIP-584: Provide implementation for ExchangeRatePrecompiledContract
hashgraph/hedera-mirror-node pull request #6667
Opened 2023-08-17 10:43 UTC by mustafauzunn

**Description**:

Provide implementation for ExchangeRatePrecompiledContract

**Related issue(s)**:

Fixes #6606 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-08-18 03:44 UTC, steven-sheehy requested changes

2023-08-18 03:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/HbarCentExchange.java
>   *  1. Remove unused methods: activeRate, activeRates, updateRates, fcActiveRates
Update javadoc

2023-08-18 03:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/BasicHbarCentExchange.java
> +    public ExchangeRate activeRate(final Instant now) {
Update class javadoc

2023-08-18 03:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long exchangeRateGasReq = 100;
Also add to docs/configuration.md.

```suggestion
    @Min(1)
    private long exchangeRateGasReq = 100;
```

2023-08-21 18:50 UTC, steven-sheehy approved these changes
LGTM. Can merge with another signoff

2023-08-21 18:50 UTC, steven-sheehy commented on docs/configuration.md
> + `hedera.mirror.web3.evm.exchangeRateGasReq`            | 100                                                | Gas requirement for ExchangeRatePrecompile.
nit: sort

2023-08-28 14:43 UTC, 0xivanov approved these changes
LGTM

2023-08-28 20:22 UTC, steven-sheehy approved these changes

2023-08-28 20:22 UTC, merged