HIP-584: aliases are not resolved in web3
hashgraph/hedera-mirror-node pull request #6720
Opened 2023-08-23 10:43 UTC by 0xivanov

**Description**: 

During precompile execution when using alias addresses we convert them to long zero addresses. All of the precompiles should work with long zero addresses, but there are some places where the addresses are not resolved to long zero, which breaks functionalities like approve, transfer, etc .

This PR also addresses some bugs regarding `ApprovePrecompile` and `CreateLogic`

- [ ] ApprovePrecompile has unnecessary check that reverts the transaction not correctly
- [ ] ApprovePrecompile does not set the nftOwnerId correctly
- [ ] Added check for zero address in StoreImpl in case the owner of NFT is the zero address
- [ ] `AssociateLogic` is not used as bean from Spring context

**Related issue(s)**:

Fixes #6707

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-23 14:59 UTC, steven-sheehy requested changes

2023-08-23 14:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        if (Address.ZERO.equals(ownerAddress)) return false;
Standard is to always use braces. Please check your auto format settings.
```suggestion
        if (Address.ZERO.equals(ownerAddress)) {
            return false;
        }

```

2023-08-23 14:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
> +                updater.permissivelyUnaliased(frame.getSenderAddress().toArray())));
We should have a test for this here and in other precompiles.

2023-08-23 14:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
> +        final var senderAddress = Address.wrap(Bytes.wrap(
Perhaps we should add a helper method to `AbstractWritePrecompile` since this logic appears in multiple sub classes?

2023-08-24 06:25 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
> +        final var senderAddress = Address.wrap(Bytes.wrap(
The problem with this approach is that we need access to the `frame`, which is available in the `run` method. `AbstractWritePrecompile` does not have access to the frame as it is implemented now.

2023-08-24 06:53 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
> +        final var senderAddress = Address.wrap(Bytes.wrap(
Added

2023-08-24 06:54 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
> +                updater.permissivelyUnaliased(frame.getSenderAddress().toArray())));
Added `DYNAMIC_ETH_CALLS_CONTRACT_ALIAS` that should cover these scenarios. We will add more tests in this contract.

2023-08-24 06:54 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        if (Address.ZERO.equals(ownerAddress)) return false;
Fixed

2023-08-24 07:07 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
> +                updater.permissivelyUnaliased(frame.getSenderAddress().toArray())));
Also removed some duplicate tests, since we pass only aliases in the calldata

2023-08-24 17:17 UTC, steven-sheehy approved these changes
LGTM

2023-08-24 17:19 UTC, merged