HIP-584: Successfully deploy contract with missing sender
hashgraph/hedera-mirror-node pull request #6776
Opened 2023-08-29 10:37 UTC by IvanKavaldzhiev

**Description**:

This PR fixes an issue where we try to perform `eth_estimateGas` for contract deploy with missing sender.
**Related issue(s)**:

Fixes #6775 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-29 11:50 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +                ETH_CALL_INIT_CONTRACT_BYTES_PATH, ETH_ESTIMATE_GAS, Address.ZERO);
Is it actually possible for the sender address to be the zero address?

2023-08-29 11:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +                ETH_CALL_INIT_CONTRACT_BYTES_PATH, ETH_ESTIMATE_GAS, Address.ZERO);
If we don't explicitly set a `from` account in the request body, we assign `Address.ZERO` as a default value. Here we make tests on service level and skip the controller business logic. That's why I pass directly the potentially resolved ZERO address.

2023-08-29 12:00 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (!account.isEmptyAccount() || Address.ZERO.equals(address)) {
Can the zero address be found as a valid account in the store?

2023-08-29 12:01 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +                ETH_CALL_INIT_CONTRACT_BYTES_PATH, ETH_ESTIMATE_GAS, Address.ZERO);
I get it now, still it is strange to me that it works this way :D

2023-08-29 12:34 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (!account.isEmptyAccount() || Address.ZERO.equals(address)) {
I don't think so, the Address.ZERO cannot be linked to a valid account and is just a default value for the Address type.

2023-08-29 14:16 UTC, 0xivanov approved these changes

2023-08-29 19:11 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>              return balance >= 0L;
Store will return empty account for address zero, which has a zero balance. So with your change to allow zero address `isUsable(Address.ZERO)` will now return true. Perhaps this might fix this issue but maybe cause problems elsewhere?

2023-08-29 19:11 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>          final var account = store.getAccount(address, OnMissing.DONT_THROW);
We should consider optimizing the database accessors to not query and return empty object if it's address zero.

2023-08-30 15:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>      }
I aligned this logic closer to `hedera-services` implementation. We should check usability of regular accounts or smart contracts. We should consider more fields than just the positive balance.

2023-08-30 15:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmContractCreationCallProcessor.java
> +            }
I decided to fix the issue locally in the ContractCreationProcessor by overriding this method. In services it wouldn't be allowed to use zero address or missing address, but here we do simulations and we are interested in the final result, e.g. gas consumption for contract deploys. So, it makes sense to be more permissive and include more use cases, which are usually not valid against the consensus node.

2023-08-31 17:59 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>          final var account = store.getAccount(address, OnMissing.DONT_THROW);
I adapted `Store.getAccount()` this way.

2023-08-31 18:01 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>              return balance >= 0L;
There is a possibility, indeed. I removed this check from `isUsable` and instead applied a fix locally into a `ContractCreationProcessor` extension.

2023-08-31 18:41 UTC, steven-sheehy requested changes

2023-08-31 18:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +    @Getter
Since you have Getter on the class it's redundant to put it on the fields.

2023-08-31 18:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return autoRenewPeriod == 0L || (createdTimestamp + autoRenewPeriod) > currentTime;
The logic here now duplicates what's in `AbstractEntity.getEffectiveTimestamp()`. Since you're populating account.expiry with the effective timestamp and not the underlying raw expiration timestamp this means this logic is now incorrect or effectively unreachable. Can't this just change to `return account.getExpiry() <= Instant.now().getEpochSecond();`?

2023-08-31 18:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmContractCreationCallProcessor.java
> +            }
I'm not a fan of this solution since it requires maintaining a fork of code from Besu. So if upstream ever changes we'll never know unless there's a compilation failure. Instead, can we just proactively insert the missing sender into the world state just for gas estimations before this code runs?

2023-09-01 13:28 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        return autoRenewPeriod == 0L || (createdTimestamp + autoRenewPeriod) > currentTime;
I agree. However I believe it should be the other way around 

`return account.getExpiry() >= Instant.now().getEpochSecond()`

2023-09-01 13:55 UTC, IvanKavaldzhiev commented
I updated the fix to reflect adding a default account in case of `eth_estimateGas`.

2023-09-01 16:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +            store.updateAccount(defaultAccount);
Should this also have some fake balance to cover some costs?

2023-09-01 16:17 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorFacadeImpl.java
> +            store.updateAccount(defaultAccount);
Yes, inside `getDefaultAccount` I load the account with `1_000_000` balance.

2023-09-01 16:23 UTC, steven-sheehy approved these changes
LGTM

2023-09-01 16:24 UTC, merged