Generate balance info from record file
hashgraph/hedera-mirror-node pull request #6786
Opened 2023-08-31 14:02 UTC by xin-hedera

**Description**:

This PR adds support of generating balance info from record file

- Add `HistoricalBalancesService` to generate account balance and token balance
- Trigger `HistoricalBalancesService` on each parsed record file
- Add `synthetic` column to `account_balance_file` table
- Cache `AccountBalanceFileRepository.findLatest()`
- Add `RecordFileRepository.findFirst()` and cache it
- Update `InitializeEntityBalanceMigration` and `TokenAccountBalanceMigration` to skip synthetic account balance file rows
- Limit account balance file downloader to at most 1 account balance file when it's disabled
- Update `StreamFileProvider` to allow overriding default batch size
- Fix `LocalStreamFileProvider.list` returning more files than asked
- Make `MirrorDateRangePropertiesProcessor` independent of whether downloader is enabled
- Disable account balance file downloader by default
- Don't generate token balances in rosetta all-in-one container image

**Related issue(s)**:

Fixes #6700 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-08-31 15:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessor.java
> -        }
this breaks account balance file parser test since by default the downloader is disabled and the filter is empty. Making it independent of wether download is enabled shouldn't break anything

2023-08-31 15:50 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/MirrorDateRangePropertiesProcessorTest.java
> -
will add the test case back. the `empty()` function was removed at first, however added back later since other test cases use it

2023-08-31 16:44 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/S3StreamFileProvider.java
> +                .maxKeys(listBatchSize)
S3 will return a max of 1000 keys. Not sure what happens if this setting is larger than that. Could result in an error, or perhaps it's simply ignored (javadoc is not clear). Either way, it may not be what is expected.

`AbstractStreamFileProvider.getListBatchSize()` utilizes the existing `batchSize` property (when `USE_DEFAULT_BATCH_SIZE`), and then doubles it. That property in `CommonDownloaderProperties` has no validation annotation currently. Perhaps a `@Max(500)` would make sense, which when doubled will top out at 1000.

2023-08-31 17:00 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                        streamFileProvider.get(node, dataFilename).block());
I see, `Mono.block()` returns null when the mono completes empty. Not sure when that might occur, but it _could_, so good call generating an NPE on the spot.

2023-08-31 17:24 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        if (accountBalanceFileRepository.findLatest().isPresent() || verifiedCount.get() > 0) {
Would it be a slight optimization to test `verifiedCount.get() > 0` ahead of the DB query?

From what I've seen so far, for the non-balance file world of the future, `AccountBalancesDownloader` will be disabled in its properties. Then, based on the 'should download' criteria here, and using the new stream file provider batch size when listing files, a single balance file will be listed, downloaded, processed, and results written to the database.  And then this downloader shall not download anything else.

2023-08-31 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        if (accountBalanceFileRepository.findLatest().isPresent() || verifiedCount.get() > 0) {
Not sure. The code path when active, runs by default every 30s, so I don’t think it’s worth considering unless it’s a huge performance difference,

2023-08-31 19:50 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +        boolean shouldGenerate = accountBalanceFileRepository
maybe I am missing from elsewhere but should we record this as metric so we can monitor easier?

2023-08-31 20:23 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        if (accountBalanceFileRepository.findLatest().isPresent() || verifiedCount.get() > 0) {
Is there a reason that `verifiedCount` is a count? It seems that it is may be used as a boolean -> [it may be either 0 or greater than 0] so could it be an AtomicBoolean instead?

2023-08-31 20:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/S3StreamFileProvider.java
> +                .maxKeys(listBatchSize)
The SDK documentation is vague by saying `By default, the action returns up to 1,000 key names.` It's unclear if this also applies to when `maxKeys` is set to more than 1000. In addition, it doesn't mention if it'll throw exception when the value is > 1000. I'd just leave it as is.

2023-08-31 20:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        if (accountBalanceFileRepository.findLatest().isPresent() || verifiedCount.get() > 0) {
can change it to `AtomicBoolean` since `getAndIncrement` should be more expensive and is common code in all downloaders.

2023-08-31 20:27 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +        boolean shouldGenerate = accountBalanceFileRepository
will add metrics

2023-08-31 20:52 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        if (accountBalanceFileRepository.findLatest().isPresent() || verifiedCount.get() > 0) {
Tried `maxKeys(5000)` in my historical downloader PoC in request made via `listObjectsV2Paginator()`, and each page still has 1000 `S3Object`s. Looks like it just quietly trims to 1000.

2023-08-31 21:30 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +
The tests still pass if `synthetic` is false, so it doesn't seem to be exercising the new part of the CTE (```where synthetic is false
                order by consensus_timestamp desc
                limit 1```)

2023-08-31 21:34 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java
> +
good catch, that's because the synthetic account balance file's timestamp is after max(record_file.consensus_end)

2023-09-01 03:53 UTC, steven-sheehy requested changes

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
> +                            .list(node, startAfterFilename, getBatchSize())
It's weird to pass through the batch size except that it's not the batch size by default, it's a sentinel value that indicates the provider should look up the batch size. Prefer a simpler solution that doesn't cascade to the provider classes. It's slightly less efficient since it will retrieve 200 signatures then only use one, but this code will only be called once on the very first start so doesn't need to be optimal. `getMaxSignatures()` returns Long.MAX_VALUE by default.

```suggestion
                            .list(node, startAfterFilename, getBatchSize())
                            .take(getMaxSignatures())
```

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +            order by id
Queries should live in the repository layer and we should avoid the use of JdbcTemplate, if possible. Move both queries into a `AccountBalanceRepository.balanceSnapshot(long)` and `TokenBalanceRepository.balanceSnapshot(long)`. Add a new `BalanceSnapshotRepository` interface to each.

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +        var generateDurationTimerBuilder = Timer.builder("hedera.mirror.historicalbalances.duration")
```suggestion
        var generateDurationTimerBuilder = Timer.builder("hedera.mirror.importer.historicalbalance.duration")
```

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesProperties.java
> +    protected Duration transactionTimeout = Duration.ofSeconds(300);
```suggestion
    private Duration transactionTimeout = Duration.ofMinutes(5);
```

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +        consensusEndSink.next(event.getConsensusEnd());
Why do we need to buffer record file events? We should be able to check if we need to start a balance snapshot within 2s and we should be able to complete the snapshot within 15 minutes. If we don't, then we have other problems.

For catch up mode, a buffer doesn't help because we'd quickly fill it up. We're already in a separate thread than RecordFileParser thanks to `@Async` so we don't need the reactor threading model. Think we should remove the buffer.

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +                        timestamp,
Having timestamp and filename is a bit redundant. Can drop timestamp.

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +                .isPresent();
Move to a separate function to reduce cognitive complexity.

2023-09-01 03:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +                .isPresent();
Think it would be simpler and more performant to lazily `select max(consensus_timestamp) from account_balance` on startup, then store an `AtomicLong lastTimestamp` that we compare the latest record file consensus end against.

2023-09-01 14:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +    }
There's complexity in how we create the first start after filename. For instance, the filename can be created soly from the configured startDate when the set date is after the latest timestamp of the stream file in db.

The correct action here should be disable account balance file downloader, solely base on the fact that `account_balance_file` table is not empty.

While it's still possible to create the start after streamfile object with a flag to indicate there's actually file in db, the complexity is still there and it's harder to maintain.

2023-09-01 14:20 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +        consensusEndSink.next(event.getConsensusEnd());
I think the main reason was to support generate balance snapshots in exactly every 15 minutes in catch up mode but due to other constraint we can't do it.

Without that, the other benefit with reactor and single-threaded scheduler is we don't have to explicitly handle race conditions in the async event listener. btw, the main purpose of `@Async` is to avoid exceptions in the listener getting propagated to the event publisher.

So if we use flux, we need to explicitly set overflow strategy regardless of the buffer size since the default is buffer all.

2023-09-01 14:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesProperties.java
> +    protected Duration transactionTimeout = Duration.ofSeconds(300);
will keep `Duration.ofSeconds(300)` since that's consistent with the unit used in DurationMin and DurationUnit

2023-09-01 14:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesProperties.java
> +    protected Duration transactionTimeout = Duration.ofSeconds(300);
DurationUnit only tells you what unit it uses by default if you omit the character unit. We could just as easily switch it to minutes or omit it entirely. In general, we should use the highest unit that fits the time without loss of precision. This makes it more self documenting in the code and in the configuration docs for users.

2023-09-01 14:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesService.java
> +                .isPresent();
I prefer the approach that is simplest and easiest to understand as that will be easiest to maintain in the long run and avoid bugs. Spring cache is always tricky to get 100% correct. So think we should use the stateful approach.

2023-09-02 03:44 UTC, steven-sheehy requested changes

2023-09-02 03:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesProperties.java
> +public class HistoricalBalancesProperties {
```suggestion
@ConfigurationProperties("hedera.mirror.importer.parser.record.historicalBalance")
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
@Validated
public class HistoricalBalanceProperties {
```

2023-09-02 03:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +                    """
nit: Spotless formatted this and the other one weird. Maybe try moving the nativeQuery param first to see if it formats better.
```suggestion
    @Query(nativeQuery = true, value = """
```

2023-09-02 03:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        this.transactionTemplate.setIsolationLevel(TransactionDefinition.ISOLATION_REPEATABLE_READ);
`@TransactionEventListener` states that `Interactions with the underlying transactional resource will not be committed in this phase`. So this transaction might be able to see some of the committed resources. Just to be safe:

```suggestion
        this.transactionTemplate.setIsolationLevel(TransactionDefinition.ISOLATION_REPEATABLE_READ);
        this.transactionTemplate.setPropagationBehavior(PROPAGATION_REQUIRES_NEW);
```

2023-09-05 22:35 UTC, jascks submitted a review, later dismissed
While I'm not as familiar as others with the broad cross section of functionality this PR encompasses, looking at downloader/parser code, and DB schema and extrapolating a bit in other areas, I am comfortable with this PR.

Using the demo bucket, I can see:
```
2023-09-05T22:24:48.872+0000 INFO scheduling-5 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 62464 items from 2019-10-11T13_45_00.028792Z_Balances.csv in 284.1 ms
```
Followed by several:
```
2023-09-05T22:27:21.696+0000 INFO task-8 c.h.m.i.p.r.h.HistoricalBalanceService Generating historical balances after processing record file with consensusEnd 1570811591052763001
2023-09-05T22:27:21.701+0000 INFO task-8 c.h.m.i.p.r.h.HistoricalBalanceService Generated historical account balance file 2019-10-11T16_33_11.052763001Z_Balances.csv with 555 account balances and 0 token balances in 5.606 ms
```
Resulting in:
```
mirror_node=# select * from account_balance_file;
 consensus_timestamp | count | load_start |  load_end  |                                            file_hash                                             |                    name                     | bytes | time_offset | node_id | synthetic 
---------------------+-------+------------+------------+--------------------------------------------------------------------------------------------------+---------------------------------------------+-------+-------------+---------+-----------
 1570801500028792000 | 62464 | 1693952688 | 1693952688 | 2961b851d18d3917b31210be074012a12c11b098abbb4b86406be4f931be3cfc9ec8defd9cf1597db7483d577ec9ee35 | 2019-10-11T13_45_00.028792Z_Balances.csv    |       |           0 |       0 | f
 1570802423951905001 |     4 | 1693952690 | 1693952690 |                                                                                                  | 2019-10-11T14_00_23.951905001Z_Balances.csv |       |           0 |      -1 | t
 1570803364604288000 |   307 | 1693952702 | 1693952702 |                                                                                                  | 2019-10-11T14_16_04.604288Z_Balances.csv    |       |           0 |      -1 | t
 1570804365577024000 |   522 | 1693952716 | 1693952716 | 
...
```
There are in the end 11 synthetic balance file rows after the first, 'real' balance file processed.

So, at this time, it looks good to me.

2023-09-05 23:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesProperties.java
> +public class HistoricalBalancesProperties {
Missed the property path change

2023-09-05 23:02 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalancesProperties.java
> +public class HistoricalBalancesProperties {
Oh will change. Thought it was just the singular form in class name.

2023-09-06 01:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +    }
will keep the current implementation.

other than the startDate after existing data in db corner case, special care is also needed to handle the situation that there is just no account balances files in cloud bucket and then inside `getStartAfterFilename` we also need the `accountBalanceFileRepository.findLatest()` so downloader gets disabled once the first synthetic account balance file is generated. Otherwise, downloader will be always enabled and try to list files in cloud bucket every 30s.

2023-09-06 01:34 UTC, jascks approved these changes
Reaffirming my original LGTM.

2023-09-06 15:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +    }
the current implementation checks if there's account balance file row in db, so it'll disable the downloader when the first synthetic balance file is generated.

2023-09-06 15:07 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloaderTest.java
> +        verifyStreamFiles(List.of(file1));
it doesn't verify it's downloaded again, since we use a mock, unless we reset the mock, the value captured stays. perhaps it's clearer to reset the mock and verify with empty list?

2023-09-06 15:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloader.java
> +        if (accountBalanceFileRepository.findLatest().isPresent() || verified.get()) {
thanks, I can remove `verified`

2023-09-06 16:07 UTC, steven-sheehy approved these changes
LGTM

2023-09-06 16:19 UTC, merged