HIP-584: Change InvalidTransactionException type in Store
hashgraph/hedera-mirror-node pull request #6788
Opened 2023-09-01 11:58 UTC by bilyana-gospodinova

**Description**:
When the store does not find an object and the OnMissing parameter is set to THROW an InvalidTransactionException is thrown (from the web3 package). In HTSPrecompiledContract#computeInternal we catch InvalidTransactionException from service so in this case the exception is caught in the general Exception block, the frame does not revert and the response is successful although it is not. Junit tests are adapted.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/6787

2023-09-04 07:25 UTC, 0xivanov reviewed
You can add new negative test in ContractCallDynamicCallsTest.java where we pass not persisted address as parameter (the transaction should fail in the store) and assert that the transaction reverts.

2023-09-05 07:52 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/StoreImplTest.java
> -import com.hedera.mirror.web3.exception.InvalidTransactionException;
The exception was renamed to MirrorEvmTransactionException.

2023-09-05 08:53 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/StoreImplTest.java
> -import com.hedera.mirror.web3.exception.InvalidTransactionException;
I vote for `MirrorEvmInvalidTransactionException` :D

2023-09-07 16:50 UTC, steven-sheehy requested changes

2023-09-07 16:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
> +        given(store.getToken(asTypedEvmAddress(misc), OnMissing.THROW)).willThrow(MirrorEvmTransactionException.class);
Believe this should be the services InvalidTransactionException

2023-09-07 16:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/AssociateLogicTest.java
> +import com.hedera.mirror.web3.exception.MirrorEvmTransactionException;
This should be the services InvalidTransactionException

2023-09-08 14:57 UTC, merged