Nullable `to` address for reverted transactions on `/contracts/results/<txHash>` route
hashgraph/hedera-mirror-node pull request #6827
Opened 2023-09-07 13:41 UTC by natanasow

**Description**:

The `/contracts/results/<txHash>` route returns null for `to` field if the ethereum transaction is reverted (no contract function result has been created).

**Solutions**:

Get the actual `to` value from the `EthereumTransaction` table.

**Steps to reproduce**:

Call a non-existing contract, the tx should revert, then execute `/contracts/results/<txHash>` and observe `to` field.

**Related issue(s)**:

Related to https://github.com/hashgraph/hedera-json-rpc-relay/issues/1711
Fixes #6826 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-09-08 20:37 UTC, xin-hedera requested changes
I don't see a new json spec test case for the scenario in the ticket description, did I miss anything?

2023-09-11 07:18 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2023-09-11 17:16 UTC, xin-hedera requested changes

2023-09-11 17:16 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/eth-tx-by-transactionhash.json
> +      }
the ticket says there is no contract call function result since the ethereum transaction is reverted, however we have a matching contract result here. same issue for contract logs and state changes.

2023-09-11 17:38 UTC, steven-sheehy requested changes

2023-09-11 17:38 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/order.json
> +        "to_address": "0x0000000000000000000000000000000000001389"
For all the files with `to_address` added should sort it by key like the rest of the fields.

2023-09-11 17:38 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/order.json
> +        "to_address": "0x0000000000000000000000000000000000001389"
Instead of modifying all these files, you could've just set this as the default in `integrationDomainOps.ethereumTransactionDefaults`.

2023-09-11 17:38 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/eth-tx-by-transactionhash.json
> +      }
Agree with Xin, except that state changes comes from the sidecar so not sure that will or won't be present. Can you confirm @natanasow ?

2023-09-12 06:17 UTC, natanasow commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/eth-tx-by-transactionhash.json
> +      }
The exact flow for reproduction:
- Execute `erc20.transfer` to a non-existing address, ethers code snippet
```typescript
    const NON_EXISTING_CONTRACT_ADDRESS = '0x01d42839A486DaAa853499De763E4908276A39e5';
    const EXISTING_RECEIVER_ADDRESS = '0x2ed4df6ec66f55a5765def0a24bfa3bac29e795e';

    const erc20Mock = await ethers.getContractAt('ERC20_ABI', NON_EXISTING_CONTRACT_ADDRESS);
    await erc20Mock.transfer(EXISTING_RECEIVER_ADDRESS, 10, {gasLimit: 1_000_000});
```
- Testnet txId - `0.0.1064@1694498644.146651309`
- [Link](https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.1064-1694498644-146651309) to mirror node `/transactions/<id>`
- [Link](https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0.0.1064-1694498644-146651309) to mirror node `/contracts/results/<tx-id-or-hash>` - returns `null` for `to` address. It has to be the non-existing address to which the tx had been made (in this case 0x01d42839A486DaAa853499De763E4908276A39e5).

2023-09-12 18:47 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/eth-tx-by-transactionhash.json
> +      }
So the above testnet transaction has a `contract_result`, an `ethereum_transaction` and no logs. So the description in the ticket was incorrect with regards to no result but the test case is correct. Thanks for confirming.

2023-09-12 18:48 UTC, steven-sheehy approved these changes
LGTM

2023-09-12 19:08 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts/results/{id}/eth-tx-by-transactionhash.json
> +      }
believe that contract result isn't from transaction record, it's generated by importer in case an eth tx fails and there's no contract result in record, it's filled with values importer knows for some fields and best effort for other fields...

2023-09-12 19:08 UTC, xin-hedera approved these changes
LGTM

2023-09-13 05:39 UTC, merged