Add balance timestamp to entity and token account
hashgraph/hedera-mirror-node pull request #6852
Opened 2023-09-11 18:13 UTC by edwin-greene

**Description**:
Add `balance_timestamp` to `entity` and `token_account`.

**Related issue(s)**:

Fixes #6683 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-09-13 19:30 UTC, steven-sheehy requested changes

2023-09-13 19:30 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    @UpsertColumn(coalesce = "coalesce({0}, e_{0})")
The default coalesce is `coalesce({0}, e_{0}, {1})` where `{1}` is null here, so we can omit this.

2023-09-13 22:07 UTC, xin-hedera requested changes

2023-09-15 17:56 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +                        tokenAccount.setBalanceTimestamp(consensusTimestamp);
Sounds good I have added that assignment.

2023-09-15 17:56 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            entity.setBalanceTimestamp(cryptoTransfer.getConsensusTimestamp());
Thanks I have updated those to set the balance timestamp as well.

2023-09-15 17:59 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +  set balance_timestamp = coalesce((select consensus_end from record_file order by consensus_end desc limit 1), 0);
Here there is a coalesce to 0 as for `token_account` the timestamp cannot be null (which seems to be implied by the non-nullablitliy of its `balance` field). This could be applied to the `entity` table if we'd like, although thus far I have left that timestamp nullable.

2023-09-15 21:24 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/IntegrationTest.java
> +    protected void persistEntity(Entity entity) {
Thanks I have moved that section to what seemed to be the closest approximate class that was already being used by a number of the tests in question -> `AbstractStakingMigrationTest`. Can move it elsewhere if needed.

2023-09-15 21:24 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.86.1__add_balance_timestamps.sql
> +  add column if not exists balance_timestamp bigint null;
Thanks I have added this backfill to the migration.

2023-09-15 21:25 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    @UpsertColumn(coalesce = "coalesce({0}, e_{0})")
That worked, I have removed it.

2023-09-15 21:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            previous.setBalanceTimestamp(current.getBalanceTimestamp());
Thanks I have added the null check.

2023-09-15 21:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +                lastTokenAccount.setBalanceTimestamp(newTokenAccount.getBalanceTimestamp());
Sounds good, added.

2023-09-15 21:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            lastTokenAccount.setBalanceTimestamp(newTokenAccount.getBalanceTimestamp());
Thanks I have added it.

2023-09-15 21:26 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.86.1__add_balance_timestamps.sql
> +alter table if exists entity
Thanks I have merged main and updated the version.

2023-09-18 14:51 UTC, xin-hedera requested changes

2023-09-18 14:51 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntity.java
> +    @UpsertColumn
nit, I don't think we need the annotation at all

2023-09-18 14:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +begin;
SQL migrations generally don't need the explicit `begin; commit;` since flyway takes care of it by running the script in a db transaction.

The extra `begin; commit;` will cause a warn log in importer log indicating there is already a transaction.

2023-09-18 14:51 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixStakePeriodStartMigrationTest.java
> +    private static final RowMapper<Entity> ENTITY_ROW_MAPPER = rowMapper(Entity.class);
this and `findAllEntities` should go to the abstract base class

2023-09-18 15:19 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixStakePeriodStartMigrationTest.java
> +    private static final RowMapper<Entity> ENTITY_ROW_MAPPER = rowMapper(Entity.class);
Thanks for spotting that, I have moved them.

2023-09-18 15:19 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +begin;
Thanks I have removed them.

2023-09-18 17:29 UTC, steven-sheehy requested changes

2023-09-18 17:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +  where deleted = false;
This needs to be where balance is not null. Don't think we need to check deleted.

2023-09-18 17:29 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +  where deleted = false;
where balance is not null. Don't think we need to check deleted.

2023-09-18 18:01 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +  where deleted = false;
Thanks I have fixed this.

2023-09-18 18:01 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.2__add_balance_timestamps.sql
> +  where deleted = false;
Got it, I have removed the delete and added the balance check.

2023-09-18 18:46 UTC, xin-hedera approved these changes
LGTM

2023-09-18 18:47 UTC, steven-sheehy approved these changes
LGTM

2023-09-18 18:58 UTC, merged