6791 hip 786 persist new staking properties
hashgraph/hedera-mirror-node pull request #6858
Opened 2023-09-12 13:29 UTC by jascks

**Description**:
[HIP-786](https://hips.hedera.com/hip/hip-786) proposes that consensus nodes add 5 new fields and deprecate one field from the `NodeStakeTransactionBody`.

* Add `reserved_staking_rewards`, `unreserved_staking_reward_balance`, `reward_balance_threshold`, `max_stake_rewarded`, `max_total_reward` as bigint columns to `network_stake` table. For existing rows, null values are the default for these new columns.
* Add same fields to `NetworkStake` entity.
* Update `NodeStakeUpdateTransactionHandler` to persist the new fields.
* Update `EntityRecordItemListenerNodeTest` and `NodeStakeUpdateTransactionHandlerTest` to test the new network stake fields.

**Related issue(s)**:

Fixes #6791

**Notes for reviewer**:
* `staking_reward_rate` is deprecated, though will still "continue to be populated for an appropriate time", so `@SuppressWarnings("deprecation")` was added where needed when getting or setting (tests) this field.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-12 16:35 UTC, steven-sheehy requested changes

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/NftId.java
> +        return fromGrpc(nftId.getTokenId(), nftId.getSerialNumber());
This is concerning. Why is the proto snapshot changing the case of this variable? This is a breaking change we should bring up with Michael.

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setMaxStakeRewarded(120_000_000_000L)
nit: sort

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setUnreservedStakingRewardBalance(150_000_000_000L)
We should double check if these values are realistic based upon integration values.

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +                        .returns(body.getStakingStartThreshold(), NetworkStake::getStakingStartThreshold)
nit: sort

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +                .returns(body.getMaxStakeRewarded(), NetworkStake::getMaxStakeRewarded)
nit: sort

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_new_fields.sql
> +alter table if exists network_stake
Combine multiple alter table statements into one.

2023-09-12 16:35 UTC, steven-sheehy commented on build.gradle.kts
> +        api("com.hedera.hashgraph:hedera-protobuf-java-api:0.43.0-HIP-786-SNAPSHOT")
We should check when a permanent release will be available since we can't tag with a snapshot. Snapshots get purged periodically, breaking our release.

2023-09-12 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        networkStake.setReservedStakingRewards(transactionBody.getReservedStakingRewards());
The problem here is when we start up a new mirror node and process old NodeStakeUpdateTransactions then their values will be zero instead of null. This differs from how our migration sets it. So different mirror nodes will return different data in the API depending upon when they started and consensus nodes upgraded.

It's not clear if zero is a valid value for any of these fields, so not sure we can just add `if (value > 0)` before setting. So perhaps we should just default to 0 in the migration instead of null so there's no inconsistency.

2023-09-12 17:50 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setUnreservedStakingRewardBalance(150_000_000_000L)
I was not looking for realistic but rather unique for each field so that the test could pick up and mismatches between set and get etc.

2023-09-12 17:51 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        networkStake.setReservedStakingRewards(transactionBody.getReservedStakingRewards());
Sounds reasonable.

2023-09-12 19:04 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +                        .returns(body.getStakingStartThreshold(), NetworkStake::getStakingStartThreshold)
Done

2023-09-12 19:05 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandlerTest.java
> +                .returns(body.getMaxStakeRewarded(), NetworkStake::getMaxStakeRewarded)
Done

2023-09-12 19:07 UTC, jascks commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_new_fields.sql
> +alter table if exists network_stake
Done

2023-09-12 19:07 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeStakeUpdateTransactionHandler.java
> +        networkStake.setReservedStakingRewards(transactionBody.getReservedStakingRewards());
Done

2023-09-12 19:09 UTC, jascks commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/NftId.java
> +        return fromGrpc(nftId.getTokenId(), nftId.getSerialNumber());
Slacked Michael about it.

2023-09-12 19:28 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setMaxStakeRewarded(120_000_000_000L)
Done

2023-09-12 21:16 UTC, jascks commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/NftId.java
> +        return fromGrpc(nftId.getTokenId(), nftId.getSerialNumber());
He's looking into it. Was OOO for a while.

2023-09-13 01:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_new_fields.sql
> +    add column if not exists unreserved_staking_reward_balance bigint not null default 0;
The defaults in v1 do not match the defaults in v2.

2023-09-13 01:31 UTC, jascks commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.87.0__network_stake_new_fields.sql
> +    add column if not exists unreserved_staking_reward_balance bigint not null default 0;
Arg! Good catch there. Done.

2023-09-13 18:00 UTC, steven-sheehy approved these changes
LGTM except proto issues which could be addressed separately before cutting the release branch.

2023-09-13 19:37 UTC, xin-hedera approved these changes
LGTM

2023-09-14 15:04 UTC, jascks commented
Ignore this comment.

2023-09-14 15:11 UTC, merged