Update web3 module README with contracts/call API support
hashgraph/hedera-mirror-node pull request #6865
Opened 2023-09-15 12:05 UTC by 0xivanov

**Description**:  

Currently the openAPI docs under api/v1/docs give a summary of what the contracts/call POST method supports across call and estimate scenarios. But some of the operations are missing.

**Solution**:
Update the openApi spec with the newest supported precompile calls.

**Related issue(s)**:

Fixes #6724

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-15 12:25 UTC, IvanKavaldzhiev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract ExchangeRatePrecompiledContract                                                          | 0.88+                                   |
ExchangeRatePrecompiledContract is not a HTS contract

2023-09-15 12:26 UTC, IvanKavaldzhiev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract PrngSystemPrecompiledContract                                                            | 0.89+                                   |
PrngSystemPrecompiledContract is not a HTS contract

2023-09-15 12:26 UTC, IvanKavaldzhiev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract UnfreezePrecompile                                                                       | 0.86+                                   |
I believe for all precompiles it's valid that we support `non-static contract state reads and modifications`.

2023-09-15 12:38 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract UnfreezePrecompile                                                                       | 0.86+                                   |
Is this true for read only precompiles? The modification part might not be right

2023-09-15 12:48 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract ExchangeRatePrecompiledContract                                                          | 0.88+                                   |
Removed the HTS part

2023-09-15 12:48 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract PrngSystemPrecompiledContract                                                            | 0.89+                                   |
Removed the HTS part

2023-09-15 12:49 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | HTS system contract UnfreezePrecompile                                                                       | 0.86+                                   |
Added `non-static contract state ...`

2023-09-15 16:38 UTC, steven-sheehy requested changes

2023-09-15 16:38 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract UnfreezePrecompile                 | 0.86+                                   |
Instead of listing everything we do support, is there enough supported now that we can just list what is not supported? Like `non-static contract state reads and modifications except FooPrecompile`

2023-09-15 16:38 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for system contract PrngSystemPrecompiledContract          | 0.89+                                   |
I think we should drop the `Mirror Node Version` column and just have a `Supported` column. It makes the table too complicated to show the history of support. We should just keep this table up to date to show the current level of support. We should try to collapse the table into as few as rows as possible to simplify it.

2023-09-15 16:38 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract GrantKycPrecompile                 | 0.85+                                   |
The ticket mentions splitting out static vs non-static into a separate `Static` column. I think we should do that since every row mentions it.

2023-09-15 16:38 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
>          | true             | non-static contract state reads and modifications for non precompile functions except lazy account creation  | 0.83+                                   |
Maybe switch to `Y` or `N` for boolean columns for brevity like the ticket shows as an example.

2023-09-15 16:38 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract MintPrecompile                     | 0.84+                                   |
The ticket mentions moving this table from the OpenAPI doc to `docs/web3/README.md` and linking to it. Were we not going to do that at this time?

2023-09-18 09:49 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract UnfreezePrecompile                 | 0.86+                                   |
I think that every operation is supported now

2023-09-18 10:21 UTC, IvanKavaldzhiev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract UnfreezePrecompile                 | 0.86+                                   |
Hey @Nana-EC, @steven-sheehy if we want to list the support of functionality only for the current release, I think we should delete the whole table now. We support each case for HIP-584 related to "latest" block in 0.89.0, so no point in keeping the table. The only value would be having support documentation for 87 and 88 release.

2023-09-18 18:01 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract UnfreezePrecompile                 | 0.86+                                   |
I agree with Steven.
We should have enough to say in summary what is supported and in details what is left.
We should be able to say static/non-static HTS/non-HTS  are supported and that historical blocks for these flows are not.

Also better for the open-api to be simple and the README to highlight this detail

2023-09-19 08:05 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract GrantKycPrecompile                 | 0.85+                                   |
Added

2023-09-19 08:05 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
>          | true             | non-static contract state reads and modifications for non precompile functions except lazy account creation  | 0.83+                                   |
Fixed

2023-09-19 08:05 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract MintPrecompile                     | 0.84+                                   |
Added the table in readme.md and linked it

2023-09-19 08:06 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for system contract PrngSystemPrecompiledContract          | 0.89+                                   |
Implemented

2023-09-19 08:06 UTC, 0xivanov commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |                  | non-static contract state reads and modifications for HTS system contract UnfreezePrecompile                 | 0.86+                                   |
Added the updated table in readme.md and linked it

2023-09-19 17:32 UTC, steven-sheehy approved these changes

2023-09-20 15:53 UTC, Nana-EC approved these changes

2023-09-20 16:11 UTC, merged