6860 option to halt importer on recoverable error
hashgraph/hedera-mirror-node pull request #6901
Opened 2023-09-19 19:30 UTC by jascks

**Description**:
Mirror node importer prioritizes availability over finding issues in the record stream. It would be useful to prefer the latter in pre-production environments to catch issues earlier in the lifecycle.

This PR modifies:

* Utilize the `HEDERA_MIRROR_IMPORTER_PARSER_HALTONERROR=false` system property (can't be regular property since we'll use it in a static utility)
* Add a `Utility.handleRecoverableError(String message, String... args)` that either logs the message with the prefix or throws a `ParserException`
* Change everywhere that logs uses `Utility.RECOVERABLE_ERROR` to use the new utility
* In all environments except mainnet and testnet, set the new system property to true

**Related issue(s)**:

Fixes #6860

**Notes for reviewer**:
Issue calls for not documenting this property.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-19 19:58 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY, HALT_ON_ERROR_DEFAULT));
I'm not certain, but I would not think recoverable errors occur real often. Fetching the property value each invocation makes this more easily testable, but also allows for the property to be updated on a running system should that be helpful.

2023-09-20 17:31 UTC, steven-sheehy requested changes

2023-09-20 17:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +                return ((String) source).split("\\s*,\\s*");
```suggestion
            if (source instanceof String str && String[].class.isAssignableFrom(targetType)) {
                return str.split("\\s*,\\s*");
```

2023-09-20 17:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY, HALT_ON_ERROR_DEFAULT));
I don't believe system properties are refreshed after startup, so your latter point is probably not applicable. But I'm not sure how you'd test it if it was static without some nasty reflection.

2023-09-20 17:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +                                {} {} {} {}, a b c d, true, 'a, b, c, d'
It might be cleaner and easier to understand if the exception was moved into the args and the expected message. So that you just have `String format, String[] args, String expected` parameters. The converter could detect the string `exception` and turn it into a RuntimeException.

```suggestion
                                plain message, '', plain message
                                {} arg message, 'one,exception', one arg message: RuntimeException: exception
                                {} {} message, 'a,b', a b message
                                {} {} {} {}, 'a,b,c,d,exception', a b c d: RuntimeException: exception
```

2023-09-20 18:49 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
>      public static final String RECOVERABLE_ERROR = "Recoverable error. ";
That makes sense. However, `com.hedera.mirror.importer.domain.ContractResultServiceImplTest` currently references it and resides outside of the package.

I do like shutting off future use though, so I could define a private constant with the same value in `ContractResultServiceImplTest` itself and use that.

2023-09-20 18:50 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY, HALT_ON_ERROR_DEFAULT));
Yep, okay that makes sense. I could be wrong, but I would not think reporting recoverable errors is a high volume thing?

2023-09-20 18:50 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +                return ((String) source).split("\\s*,\\s*");
Good catch on the old school Java. It's only been seven releases... 😄

2023-09-20 19:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
>      public static final String RECOVERABLE_ERROR = "Recoverable error. ";
Could also switch that test to halt on error.

2023-09-20 19:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        System.setProperty(HALT_ON_ERROR_PROPERTY, "true");
We should probably set this back to false in an AfterEach so it doesn't impact other tests

2023-09-20 20:19 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +                return ((String) source).split("\\s*,\\s*");
Done

2023-09-20 20:20 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +                                {} {} {} {}, a b c d, true, 'a, b, c, d'
Revamped this test case, and the converter significantly. I like it much better. 👍

2023-09-20 20:20 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        System.setProperty(HALT_ON_ERROR_PROPERTY, "true");
Done

2023-09-20 20:26 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
>      public static final String RECOVERABLE_ERROR = "Recoverable error. ";
That test would then have to be cognizant of the new system property setting which I'd like to keep to the `util` package.  `UtilityTest` already does a good job of testing the property and its effects.

`ContractResultServiceImplTest` is all about capturing log output and looking for `RECOVERABLE_ERROR`. I'm thinking defining that constant locally is the way to go for now.

2023-09-20 20:32 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
>      public static final String RECOVERABLE_ERROR = "Recoverable error. ";
Done

2023-09-20 21:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY, HALT_ON_ERROR_DEFAULT));
Correct

2023-09-20 22:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        }
Is it not possible to just put the `RuntimeException: provided cause` into the expected message so that the entire output sans prefix is in the `@CsvSource`?

```suggestion
        assertThat(capturedOutput.getAll()).contains(RECOVERABLE_ERROR + formatted);
```

2023-09-20 22:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        }
Even if you don't pass a `[]` the JVM will generate an empty array regardless. Might as well reduce the conditionals and always pass the args.

```suggestion
        Utility.handleRecoverableError(format, args);
```

2023-09-20 22:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        }
Use assertj and always pass args.

```suggestion
        assertThatThrownBy(() -> Utility.handleRecoverableError(format, args))
            .isInstanceOf(ParserException.class)
            .hasMessage(formatted)
            .hasCause(causeProvided);
```

2023-09-21 13:21 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        }
Done

2023-09-21 13:22 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
> +        }
Indeed. Nice series of refinements. Thank you. Done.

2023-09-21 14:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY, HALT_ON_ERROR_DEFAULT));
nit, can just do the following since `Boolean.parseBoolean(value)` returns false when `value` is null

```suggestion
        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY));
```

2023-09-21 14:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +                    : new ParserException(formattedMessage, throwable);
nit, can just pass in the throwable regardless null or not

```suggestion
            throw new ParserException(formattingTuple.getMessage(), formattingTuple.getThrowable());
```

2023-09-21 14:38 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +        var haltOnError = Boolean.parseBoolean(System.getProperty(HALT_ON_ERROR_PROPERTY, HALT_ON_ERROR_DEFAULT));
Ah, okay, thank you. Done.

2023-09-21 14:39 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
> +                    : new ParserException(formattedMessage, throwable);
Hmm, all the way up to `Throwable` itself I see. Thanks! Done.

2023-09-21 14:44 UTC, steven-sheehy approved these changes

2023-09-21 14:46 UTC, xin-hedera approved these changes
LGTM

2023-09-21 14:57 UTC, merged