Set dynamic value for create token in acceptance tests
hashgraph/hedera-mirror-node pull request #6917
Opened 2023-09-21 06:41 UTC by 0xivanov

**Description**:  

Exchange rates in local / testnet / previewnet envs are different and token create operations cost 1 usd and 2 usd for custom fees.
Currently the value passed in the create token tests are hardcoded and work only in local environment.
This PR implements dynamic setting of the hbars sent to the create token call, so the fee is sufficient.

**Related issue(s)**:

Fixes #6905

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-21 07:18 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Verify contract result '{}' is returned by Mirror Node");
Do we need this log?

2023-09-21 08:32 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Verify contract result '{}' is returned by Mirror Node");
Changed the log to be appropriate

2023-09-21 09:43 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        currentExchangeRate = new ExchangeRate(
Probably we should determine whether to use `currentExchangeRate` or `nextExchangeRate` based on the current timestamp and check exchange rates `expiration` timestamp?

2023-09-21 09:52 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        currentExchangeRate = new ExchangeRate(
Yeah, i guess it could happen if we get the currentExchangeRate when there are few seconds/milliseconds left before the next

2023-09-21 09:53 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        currentExchangeRate = new ExchangeRate(
The question is what is the timeframe between the call that gets the exchange rates and the create token estimate gas call.

2023-09-21 10:21 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        currentExchangeRate = new ExchangeRate(
The simplest/safest option i can think of is to make these tests to retry with `nextExchangeRate` calculations in case the first call fails. And if both fail the whole test is considered failed.

2023-09-21 16:37 UTC, steven-sheehy requested changes

2023-09-21 16:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        createTokenValueWithCustomFees = (usdInCents * 2 / hbarPriceInCents + 1) * 100000000;
We should encapsulate this in a shared method in `AbstractFeature`. Then we should just call this everywhere needed instead of storing `createTokenValue*` as class variables.

```java
protected long calculateFee(double usdFee) {
    final double hbarPriceInCents = (double) currentExchangeRate.centEquivalent() / currentExchangeRate.hbarEquivalent();
    final double rate = hbarPriceInCents / 100.0;
    return (usdFee * rate + 1) * 100_000_000L;
}

2023-09-25 07:38 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        createTokenValueWithCustomFees = (usdInCents * 2 / hbarPriceInCents + 1) * 100000000;
Fixed

2023-09-25 07:38 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private ExchangeRate currentExchangeRate;
Fixed

2023-09-25 07:39 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +    protected record ExchangeRate(int centEquivalent, int hbarEquivalent) {}
Fixed

2023-09-25 07:39 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        currentExchangeRate = new ExchangeRate(
Implemented the retry mechanism

2023-09-25 21:14 UTC, steven-sheehy requested changes

2023-09-25 21:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final long hbarPriceInCents = fee.getCentEquivalent() / fee.getHbarEquivalent();
This should be double arithmetic so we don't lose precision, right? Services uses BigInteger

2023-09-25 21:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final var fee = useCurrentFee ? exchangeRates.getCurrentRate() : exchangeRates.getNextRate();
Can we not just detect which is closest from now?

2023-09-25 21:14 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
>          validateGasEstimationForCreateToken(
Make this a lambda `Consumer<Boolean>` that takes in current flag then move try/catch retry into a helper method

```suggestion
        var estimateFunction = current -> validateGasEstimationForCreateToken(
                    Strings.encode(encodedFunctionCall),
                    ContractMethods.CREATE_FUNGIBLE_TOKEN.getActualGas(),
                    calculateCreateTokenFee(1, current));
        validateGasEstimation(estimateFunction);
```

2023-09-26 06:20 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final var fee = useCurrentFee ? exchangeRates.getCurrentRate() : exchangeRates.getNextRate();
Does this mean getting rid of the boolean `useCurrentFee` . Your suggestions include the usage if this boolean.

2023-09-26 12:40 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final var fee = useCurrentFee ? exchangeRates.getCurrentRate() : exchangeRates.getNextRate();
Asking if it's possible to get rid of and just use a timestamp. Not sure how that works eith your retry logic

2023-09-26 13:08 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final long hbarPriceInCents = fee.getCentEquivalent() / fee.getHbarEquivalent();
changed to using double

2023-09-26 13:09 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
>          validateGasEstimationForCreateToken(
Implemented

2023-09-26 13:12 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final var fee = useCurrentFee ? exchangeRates.getCurrentRate() : exchangeRates.getNextRate();
I added documentation to `executeAndRetryWithNextExchangeRates` explaining why I am doing retry and the problem i see with comparing the currentExchangeRate expiration timestamp with the system timestamp

2023-09-27 02:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final double hbarPriceInCents = fee.getCentEquivalent() / fee.getHbarEquivalent();
This is still integer arithmetic. You need to cast one of the numerator or denominator to double as well.

2023-09-27 14:11 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +        final double hbarPriceInCents = fee.getCentEquivalent() / fee.getHbarEquivalent();
Addressed

2023-09-27 21:06 UTC, steven-sheehy approved these changes

2023-09-27 21:07 UTC, merged