Make `MirrorEntityAccess.isUsable` **not** consider expiry
hashgraph/hedera-mirror-node pull request #6940
Opened 2023-09-22 22:12 UTC by david-bakin-sl

**Description**:

`MirrorEntityAccess` is using expiry as a gate for `isUsable` for accounts, incl contracts

Should be gated on feature flags - but isn't.  Expiry isn't enabled now but this code thought it was.

Solution for now is to simply _not_ check for expiry as that is the network behavior right now.

Also, make sure balance behaves properly: >0 balance means isUsable, <0 balance means _not_ isUsable, and ==0 balance is a special case.

**Related issue(s)**:

Fixes #6928

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit)

2023-09-22 22:22 UTC, Nana-EC reviewed
LG, one test clarification

2023-09-22 22:22 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (account.isEmptyAccount()) {
Q: Is this already covered by an existing test or does it need a new one in `MirrorEntityAccessTest`?

2023-09-22 22:24 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (balance < 0) {
Q: not possible right. Do we need this given the accessor?

2023-09-22 22:26 UTC, steven-sheehy requested changes

2023-09-22 22:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (account.isEmptyAccount()) {
I don't see how this scenario is possible against a real db. The empty account is the zero address and there should never be a `0.0.0` in the db.

2023-09-22 22:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (balance < 0) {
I don't see how this scenario is possible against a real db. There's no negative balance accounts or we'd have a serious problem with the mirror node.

2023-09-22 22:27 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (balance < 0) {
It's not not possible because of the accessor, it's "not possible" because we think that there's no way for an account to be in arrears, given the network behaving properly.  A unit test covers this.  Sort of belt-and-suspenders I guess.

2023-09-22 22:29 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (account.isEmptyAccount()) {
Test `MirrorEntityAccessTest.isNotUsableWithWrongAlias` says this is what happens with a "wrong alias". It's a given to mockito in that test.  Whether it actually happens in the codebase I don't know.

2023-09-22 22:30 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (balance < 0) {
Well I agree with you.  But someone thought it was worth testing at `MirrorEntityAccessTest.isNotUsableWithNegativeBalance'.   I don't have enough information to know what triggered the writing of that test.

2023-09-22 22:31 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (account.isEmptyAccount()) {
Are you referring to new L68?  This condition is tested in `MirrorEntityAccessTest.isNotUsableWithWrongAlias`.  As I mention in a separate comment below, I don't know if this actually happens in real life.

2023-09-22 22:42 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (balance < 0) {
removed the test and the code (per offline discussion)

2023-09-22 22:42 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (account.isEmptyAccount()) {
removed the test and the code (per offline discussion)

2023-09-22 22:42 UTC, david-bakin-sl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +        if (account.isEmptyAccount()) {
removed the test and the code (per offline discussion)

2023-09-22 22:43 UTC, Nana-EC approved these changes
LG, one suggestion on the address.

2023-09-22 22:43 UTC, Nana-EC commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> -        final var address = Address.fromHexString("0x3232134567785444e");
This was wrong due to to bad entry. I had changed it to 
```suggestion
   final var address = Address.fromHexString("0x0");
```

2023-09-22 22:50 UTC, david-bakin-sl commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> -        final var address = Address.fromHexString("0x3232134567785444e");
Accepted (but I did my own push of a new commit to _reinclude_ the test)

2023-09-23 00:26 UTC, steven-sheehy approved these changes

2023-09-23 00:27 UTC, merged