06812: Extend token db query to filter by timestamp, add token balanc…
hashgraph/hedera-mirror-node pull request #6962
Opened 2023-09-26 09:59 UTC by kselveliev

**Description**:
Changes in this PR address task 1 from the following [issue](https://github.com/hashgraph/hedera-mirror-node/issues/6812).

Changes applied:
Added TokenBalanceRepository in web3 module.
Added TokenTransferRepository in web3 module.
Added new db query in TokenRepository that allows for filtering historical data.
Added unit tests for all of the repositories and new methods that were added.

**Related issue(s)**:

Fixes #6812

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-09-26 13:04 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenTransferRepository.java
> +public interface TokenTransferRepository extends CrudRepository<TokenTransfer, TokenTransfer.Id> {}
I believe it's a convention in mirror-node to define new repository instances in the modules where they are needed. That's why we defined several repositories in web3.

2023-09-26 13:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenTransferRepositoryTest.java
> +    void save() {
We shouldn't allow anything in the web3 module to persist entries in DB, so no point in testing save operations.

2023-09-26 15:34 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenTransferRepositoryTest.java
> +    void save() {
Comment addressed

2023-09-27 13:33 UTC, bilyana-gospodinova commented
LGTM

2023-09-27 13:33 UTC, bilyana-gospodinova approved these changes

2023-10-04 03:17 UTC, steven-sheehy requested changes

2023-10-04 03:17 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> -                .timestampRange(Range.closedOpen(timestamp(), timestamp()));
I don't see how this change or any change within the file has any impact. Either way you're calling `timestamp()` separately for lower and upper bound. `timestamp()` is guaranteed to produced a monotonically increasing timestamp. Just putting the lower bound into a variable doesn't change its behavior.

2023-10-04 03:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenTransferRepository.java
> +            value = "SELECT * FROM token_transfer "
In mirror node, we prefer all SQL to be written as lower case. Please adjust any file in the PR.

2023-10-04 03:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenTransferRepository.java
> +                    + "LIMIT 1 ",
It's hard to know if this is an appropriate query without seeing how it's used. But I'm struggling to find how it's useful to select one token transfer before a block's timestamp. What's the use case here? Wouldn't you want to sum all token transfers between two timestamps to calculate the historical balance?

2023-10-04 03:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                    + " AND lower(timestamp_range) < ?2 AND upper(timestamp_range) > ?2 "
We should use range [operators](https://www.postgresql.org/docs/14/functions-range.html) to efficiently utilize the GIST index. Searching the lower and upper bound with AND and ORs is inefficient. Please explain analyze your queries to profile them.

2023-10-04 03:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                    + " AND lower(timestamp_range) < ?2 "
There's only one token in token table for that token_id, so no need to filter on timestamp range in token subquery. The filter on timestamp range should be moved outside the union subquery as I indicated via slack

2023-10-04 03:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +            unless = "#result == null")
Not sure we should cache this until testing proves it's necessary. Also not sure if the 2s expiry for CACHE_MANAGER_TOKEN is appropriate or could be higher for historical queries.

2023-10-04 19:26 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenTransferRepository.java
> +            value = "SELECT * FROM token_transfer "
Comment addressed. All of the SQL in this pr is lowercase.

2023-10-04 19:29 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenTransferRepository.java
> +                    + "LIMIT 1 ",
My mistake. This query cannot be used. I've deleted this repository and created a query in TokenBalanceRepository where the sum of all token transfers between two timestamps is added to the historical token balance.

2023-10-04 19:31 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                    + " AND lower(timestamp_range) < ?2 AND upper(timestamp_range) > ?2 "
I've refactored the query where we would use only "where lower(timestamp_range) < ?" outside of the UNION subquery.
I ran this query with explain and analyze in pgAdmin and the timestamp_range index seems to used with this approach.

2023-10-04 19:33 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                    + " AND lower(timestamp_range) < ?2 "
I've refactored the query. The timestamp_range filtering is simplified and moved outside of the UNION subquery.

2023-10-04 19:33 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +            unless = "#result == null")
Comment addressed. I've removed the caching logic until it is proven that is necessary.

2023-10-04 20:43 UTC, xin-hedera requested changes

2023-10-04 20:43 UTC, xin-hedera commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +    public DomainWrapper<TokenTransfer, TokenTransfer.TokenTransferBuilder> tokenTransferCustom(
prefer a common custom function in the test class or a utility class, not here.

you can do

```java
  domainBuilder.tokenTransfer()
    .customize(t -> t.amount(...).id(...))
    ...

```

2023-10-04 20:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                limit 1
nit, this is slightly better indentation
```suggestion
                select * from token_balance
                where
                  token_id = ?1 and
                  account_id = ?2 and
                  consensus_timestamp < ?3
                order by consensus_timestamp desc
                limit 1
```

2023-10-04 20:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
Two issues in the query

- correctness. It's possible the subquery on table `token_balance` returns nothing because there's no token balance row for the `(account, token, blockTimestamp)`, then the result from the query is incorrect
- performance. We should go back only one token balance snapshot before `blockTimestamp` (from `account_balance_file` table), assume the timestamp is `T1`, then calculate the balance with `coalesce(token balance at T1, 0) + sum(transfer amount in (T1, blockimestamp])`

2023-10-04 20:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +    Optional<Token> findByTokenIdAndTimestampRange(long tokenId, long blockTimestamp);
why is the function named `findByTokenIdAndTimestampRange` while `blockTimestamp` is a point in time not a range?

The query is inefficient since it does not trim unnecessary rows in `token_history` table in the `union all`, should rewrite it to

```sql
(
  select *
  from token
  where token_id = ?1 and lower(timestamp_range) <= ?2
)
union all
(
  select *
  from token_history
  where token_id = ?1 and lower(timestamp_range) <= ?2
  order by lower(timestamp_range) desc
  limit 1
)
```

I'm not sure from the design whether the query should return the latest token info effective at `blockTimestamp` or before `blockTimestamp`. The above query with `<= ?2` is for effective at `blockTimestamp`.

2023-10-05 00:51 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> -                .timestampRange(Range.closedOpen(timestamp(), timestamp()));
Ok, thanks for clarifying.

2023-10-05 13:52 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
follow up, the query should work for both fungible and non fungible tokens, right?

so it will be more complicated, for non fungible token, the transfers are in `transaction.nft_transfer`, it's a json array, e.g.,

```json
[
  {"token_id": 1682826, "is_approval": false, "serial_number": 1161, "sender_account_id": 1518550, "receiver_account_id": 1385889},
  ...
]
```

2023-10-05 19:02 UTC, kselveliev commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +    public DomainWrapper<TokenTransfer, TokenTransfer.TokenTransferBuilder> tokenTransferCustom(
Comment addressed. I removed the tokenTransferCustom method and now using the common custom function as proposed.

2023-10-05 19:03 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                limit 1
Comment addressed.

2023-10-05 19:17 UTC, xin-hedera requested changes

2023-10-05 19:17 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                        )
why use the complicated logic instead of just `order by lower(timestamp_range) desc limit 1`?

there is an index on `token_history (token_id, lower(timestamp_range))` so it should be fast enough.

2023-10-05 19:18 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +    Optional<Token> findByTokenIdAndTimestampRange(long tokenId, long blockTimestamp);
Comment addressed. I've fixed the naming of the method since we are not using the range.

I've refactored the query as proposed.

I've tested and improved it to trim the unnecessary rows in token_history.

Here is some analysis done on the current query and the improved one.

Testing the following queries:

<img width="710" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/cad3822d-c98a-4133-b2f8-9758b431abc0">

In local DB I’ve setup to have **1 million** records that satisfy the condition lower(timestamp_range) < 1795888431263421169 and token_id=1024

Here is the query result.

<img width="716" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/d1a27eea-72d2-4881-a320-a538ce382f12">

Execution plan:

<img width="703" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/57585ff5-5265-4242-8049-2eb33f8713aa">

Usually it takes around 500.000 ms to complete.

I've enhanced the query to trim the history token only to the one closest to the block timestamp.
This way we save time from ordering by millions of records to only one.

Enhanced query:

<img width="694" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/dcc64c03-ee18-492a-8ae4-865dd824532d">

For second part that queries token_history, I’ve created a clause which will trim all of the records that satisfy token_id = 1024 and lower(timestamp_range) <= 1795888431263421169. and will leave only the one record that is closest or equal to 1795888431263421169 which is our filter in this case.

Query result:
<img width="717" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/4a3c3085-7b5f-4964-9334-36b530f26124">

Execution plan:
<img width="959" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/5bb92a4b-b29c-4fb3-83c4-00cb93c6932c">

It usually takes less under 1.000 ms to complete 

So this query performs a few hundred times faster than the first one.
Let me know if you agree with this change

2023-10-05 19:22 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                        )
Could you check https://github.com/hashgraph/hedera-mirror-node/pull/6962#discussion_r1347868412.
I can revert the complicated logic if you believe it is okay. My concern was about the order by since it may do the order by millions of records.

2023-10-05 19:29 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
I've fixed the correctness part as proposed.

In terms of performance I tried to trim to check only the closest token balance snapshot before blockTimestamp.
Something similar to what I did [here](https://github.com/hashgraph/hedera-mirror-node/pull/6962#discussion_r1347868412). But it somehow slowed down the query when I did the analysis. 
So I left it as it is. Let me know if this is okay for you.

As for the question if it is for non fungible token. I was not aware of that json array complexity.
So for now I believe in our business logic in the code we should only use this query when dealing with fungible tokens. We will create a separate query for non fungible in another PR.

2023-10-05 20:00 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +    Optional<Token> findByTokenIdAndTimestampRange(long tokenId, long blockTimestamp);
I've reverted the complex part

2023-10-05 20:35 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
can you test this query?

```sql
select coalesce((
    select balance
    from token_balance
    where
      consensus_timestamp = s.consensus_timestamp and
      account_id = :accountId and
      token_id = :tokenId
  ), 0) + coalesce((
    select sum(amount)
    from token_transfer
    where
      account_id = :accountId and
      token_id = :tokenId and
      consensus_timestamp > s.consensus_timestamp and
      consensus_timestamp <= :blockTimestamp
  ), 0)
from (
  select consensus_timestamp
  from account_balance_file
  where consensus_timestamp <= :blockTimestamp
  order by consensus_timestamp desc
  limit 1
) as s;

```

2023-10-06 13:43 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
One question about this proposal. Is the modified query intended for increased query performace? 

Im am asking this bacause I was not aware of this account balance file table and how is it used.

And also what is the relation with token balance table . Because to test it I need to persist also the data in the account balance file table for the unit test setup. 

So if I understand correctly we should first find a record in account_balance_file.

Then we take its consensus_timestamp based on the filter, and then we should always have a record in token balance table where consensus_timestamp = token_balance_file.consensus_timestamp and also the  token_id and account_id provided.

Is this the correct logic?

2023-10-06 15:02 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
for both performance and some corner cases I mentioned about the original query.

`account_balance_file` has one row for each account balance file, it includes the account balance file name, its consensus timestamp, and etc.

For each row in account balance file, there should be corresponding account balance rows in `account_balance` table with the same consensus timestamp. same applies to `token_balance` table.

However for a timestamp `T1`, a token balance for `(accountId, tokenId)` may not exist since the account wasn't associated with the token at  `T1`, thus we should do a `coalesce`

2023-10-09 10:18 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    @Query(
Understood, I’ve replaced the the previous query with this one.

I’ve setup the tests so that we have account_balance_file record and 

a token balance record with the same consensus_timestamp and tests 

are passing. Let me know if this is sufficient.

2023-10-09 14:34 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                    """,
failed with v2 database schema due to citus limitations, so have to rewrite the query to make citus happy

```sql
with balance_snapshot as (
  select consensus_timestamp
  from account_balance_file
  where consensus_timestamp <= ?3
  order by consensus_timestamp desc
  limit 1
), base as (
    select balance
    from token_balance as tb, balance_snapshot as s
    where
      tb.consensus_timestamp = s.consensus_timestamp and
      token_id = ?1 and
      account_id = ?2
), change as (
    select sum(amount) as amount
    from token_transfer as tt, balance_snapshot as s
    where
      token_id = ?1 and
      account_id = ?2 and
      tt.consensus_timestamp > s.consensus_timestamp and
      tt.consensus_timestamp <= ?3
)
select coalesce((select balance from base), 0) + coalesce((select amount from change), 0)
```

2023-10-09 15:26 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                    """,
comment addressed

2023-10-09 21:54 UTC, xin-hedera commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .timestampRange(Range.closedOpen(timestamp(), timestamp(10)));
I made the change to add the delta to `id` so `timestamp()` will always increase, otherwise it breaks the assumption made in `FixCryptoAllowanceAmountMigrationTest`

2023-10-09 21:55 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-10-10 06:08 UTC, 0xivanov submitted a review, later dismissed

2023-10-11 18:05 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-10-11 18:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                      from account_balance_file
Not sure why Xin recommended using account_balance_file when we're trying to purge its use everywhere. But we can go with it as is and open a ticket to follow up.

2023-10-11 19:36 UTC, kselveliev commented
I will close this and reopen it from a fresh branch since i forgot to verify one of the initial commits and due to that merging is blocked.

2023-10-11 19:36 UTC, closed without merging