HIP-584: Remove unneeded store.wrap() call in ApproveAllowanceLogic
hashgraph/hedera-mirror-node pull request #6964
Opened 2023-09-26 12:24 UTC by bilyana-gospodinova

**Description**:
In ApproveAllowanceLogic#applyNftAllowances() there is an extra store.wrap() call and the stack frames grow unnecessary. This call is now removed.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/6963

2023-09-26 13:32 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-09-27 07:24 UTC, kselveliev submitted a review, later dismissed
LGTM

2023-09-27 14:19 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
> +                accountsChanged.put(approvingAccount.getId().num(), approvingAccount);
I believe you can move this line in line 203 and revert the other changes. This will decrease complexity and might fix the code smell.

2023-09-29 18:05 UTC, steven-sheehy requested changes

2023-10-02 09:38 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
> +                if (!accountWithUpdatedApproveForAllNfts.equals(approvingAccount)) {
Isn't this always true. I mean we either add or remove from the set and then create new account with the updated set.
Isn't this enough? Like without the if statements and stuff:
``` java
approvingAccount = approvingAccount.setApproveForAllNfts(approveForAllNfts);
accountsChanged.put(approvingAccount.getId().num(), approvingAccount);
```

2023-10-02 10:40 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
> +                if (!accountWithUpdatedApproveForAllNfts.equals(approvingAccount)) {
I am not sure. What if the set is empty and we are in the else case and try to remove an element that does not exist? In this case the set is the same and there will be no need to update the account.

2023-10-02 10:41 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
> +                accountsChanged.put(approvingAccount.getId().num(), approvingAccount);
Updated as requested.

2023-10-02 10:41 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
> +        Account modifiedAccount = null;
I made the changes as in Ivan's suggestion.

2023-10-02 12:24 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
> +                if (!accountWithUpdatedApproveForAllNfts.equals(approvingAccount)) {
Yeah I agree on this point.

2023-10-02 12:24 UTC, 0xivanov approved these changes

2023-10-02 15:16 UTC, david-bakin-sl commented
This PR does more than simply remove the `wrap()` call - it's doing some logic.  PR title & comment (and subsequent commit message) should reflect that.

2023-10-02 16:39 UTC, steven-sheehy approved these changes
LGTM

2023-10-02 16:40 UTC, merged