HIP-584: 06812 - Extend entity, account balance and crypto transfer db queries
hashgraph/hedera-mirror-node pull request #6966
Opened 2023-09-27 13:04 UTC by kselveliev

**Description**:
This PR fixes part 2 of the following [issue](https://github.com/hashgraph/hedera-mirror-node/issues/6812) 

This PR modifies the following classes:
Modified **EntityRepository** - added 2 new queries 
1. **findByEvmAddressAndTimestamp** to query historical data
2. **findByIdAndTimestamp** to query historical data
Added new unit tests in **EntityRepositoryTest** to test the new methods

Added **AccountBalanceRepository** interface and unit tests for it.
Added **CryptoTransferRepository** interface and unit tests for it.
Those 2 will be needed in the future to calculate entity balance.

**Related issue(s)**:

Fixes #6812

**Checklist**

- [ X ] Documented (Code comments, README, etc.)
- [ X ] Tested (unit, integration, etc.)

2023-09-27 13:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/CryptoTransferRepositoryTest.java
> +        Assertions.assertThat(cryptoTransferRepository.findAll()).isEqualTo(List.of(cryptoTransfer1, cryptoTransfer2));
This is not relevant for a findById test case or at least to me the placement should not be at the end of the test. It makes more sense to persist the two crypto transfers -> assert that they are persisted correctly (this line here) -> assert that findByIdAndTimestamp returns the correct crypto transfer.

2023-09-28 07:39 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/CryptoTransferRepositoryTest.java
> +        Assertions.assertThat(cryptoTransferRepository.findAll()).isEqualTo(List.of(cryptoTransfer1, cryptoTransfer2));
Comment addressed

2023-10-03 08:43 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +          + ") AS t "
It could be changed to `AS e`

2023-10-03 10:23 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +          + ") AS t "
Comment addressed

2023-10-04 03:31 UTC, steven-sheehy requested changes

2023-10-04 03:31 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +            value = "SELECT * FROM account_balance "
Use lower case for SQL everywhere.

2023-10-04 03:31 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                    + "WHERE "
These queries span too many lines. I think it's better to combine the where clause into a single line and we should use `"""` for multiline strings. Same comment elsewhere.

2023-10-04 03:31 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CryptoTransferRepository.java
> +    Optional<CryptoTransfer> findByIdAndTimestampLessThan(Long entityId, long amount, Long consensusTimestamp);
Again, don't see the value in this query. The notion doc only mentions querying transfer tables to sum their amount between two timestamps. Is that what you intended here? If so, should sum the amounts and return a Long

2023-10-04 03:31 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +          + "  WHERE evm_address = ?1 "
We don't have an index on `entity_history.evm_address` so this would be slow. Since evm_address is immutable we could just query for it against `entity.evm_address`. We don't need to query against the history table. Since it's possible an account could be deleted and a different account assign the same EVM address you'll also need to order by timestamp_range and limit to return the appropriate one.

2023-10-04 03:31 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +           + "  AND deleted = false "
Move the where clauses to the outer query and use range operators

2023-10-09 14:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +            value = "SELECT * FROM account_balance "
Comment addressed

2023-10-09 14:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                    + "WHERE "
Comment addressed

2023-10-09 14:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +          + "  WHERE evm_address = ?1 "
Comment addressed. Modified the query to search only in entity table.

2023-10-09 14:12 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CryptoTransferRepository.java
> +    Optional<CryptoTransfer> findByIdAndTimestampLessThan(Long entityId, long amount, Long consensusTimestamp);
Understood. This repository is removed and its tests. Added the new logic in AccountBalanceRepository where the amount is calculated summing up the crypto transfer. The query is made following the structure proposed [here](https://github.com/hashgraph/hedera-mirror-node/pull/6962#discussion_r1347939728)

2023-10-18 19:43 UTC, xin-hedera requested changes

2023-10-18 19:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
1. The query should union all `entity` and `entity_history`
2. use `delete is not true` since delete is a nullable column. `null is not true` evaluates to be `true` while `null = false` evaluates to `null`

2023-10-18 19:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                        and deleted = false
deleted is not true

2023-10-18 19:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                        and deleted = false
deleted is not true

2023-10-19 07:42 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                        and deleted = false
Commend addressed.

2023-10-19 07:43 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                        and deleted = false
Comment addressed.

2023-10-19 07:45 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
Addressed part 2 of the comment.
However part 1 clashes with Steven's comment [above](https://github.com/hashgraph/hedera-mirror-node/pull/6966#discussion_r1345145298). 
Can you check it and let me know if we should use the entity_history table when making query by evm_address.

2023-10-19 11:17 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +
Suggestion for one more junit test:
- Persist two entries with the same fields in EntityHistory. They will only differ in the timestamp range.
- Assert that the new repository methods return the entry with the latest lower timestamp.

2023-10-19 13:16 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +
Comment addressed

2023-10-20 04:12 UTC, steven-sheehy requested changes

2023-10-20 04:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
My comment was to separate the evm address lookup from the find entity at block lookup. For evm address lookup we can take advantage of the fact that for any given evm_address it will only be active for one account during a particular time range. So we can do this query:

```sql
select * from entity where evm_address = ?1 and created_timestamp <= ?2 order by created_timestamp desc limit 1;
```

For entity lookup we will still need do union with history but just looking at id from previous evm address lookup.

2023-10-20 07:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +    private void assertEntityFields(EntityHistory entityHistory, Optional<Entity> queryResult) {
You can use usingRecursiveComparison() is the assert in order to avoid this large method that does the same.
Example:
```
assertThat(entityRepository.findByIdAndTimestampAndDeletedIsFalse(
                entityHistory.getId(), entityHistory.getTimestampLower()))
.get()
.usingRecursiveComparison()
.isEqualTo(entityHistory)
```

2023-10-24 13:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
Even though the `evm_address` could be active during a particular range, couldn't it be that it was active for a given account in a time range from the past? If that's true, won't this mean we also need the `entity_history` table?

2023-10-24 14:02 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +    private void assertEntityFields(EntityHistory entityHistory, Optional<Entity> queryResult) {
Commend addressed

2023-10-24 16:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
It will be active for a given account at some time in the past, hence why I sort and filter by the immutable created_timestamp field.

2023-10-25 10:28 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                          from account_balance_file
Comment addressed

2023-10-25 10:53 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
I've refactored the find by evm address db query as I understood it from above conversation.
Let me know if it looks good now.

2023-10-25 14:47 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +                    limit 1
It should be sth like

```sql
with contract as (
  select id
  from entity
  where evm_address = ?1 and created_timestamp <= ?2
  order by created_timestamp desc
  limit 1
)
(
  select *
  from entity e
  join contract c on c.id = e.id
  where ...
) union all
(
  select *
  from entity_history e
  join contract c on c.id = e.id
  where ...
  order by lower(timestamp_range) desc
  limit 1
)
order by timestamp_range desc
limit 1
```

2023-10-27 03:40 UTC, xin-hedera approved these changes
LGTM

2023-10-27 22:58 UTC, steven-sheehy approved these changes
LGTM

2023-10-27 23:47 UTC, merged