Update accounts and balances to use entity.balance_timestamp
hashgraph/hedera-mirror-node pull request #6974
Opened 2023-09-28 21:17 UTC by edwin-greene

The accounts and balances endpoints will now utilize the entity.balance_timestamp.

**Related issue(s)**:

Fixes #6701 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-10-02 22:33 UTC, steven-sheehy requested changes

2023-10-02 22:33 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/balances/no-params.json
It's strange that this spec is called no-params yet has a test with the timestamp param.

2023-10-02 22:33 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +    accountBalanceQuery.query = `ab.account_id = e.id and ab.consensus_timestamp = e.balance_timestamp`;
We can't join account_balance timestamp which is generated by 15 minute snapshot process with the balance_timestamp. We should only join on account_balance for when timestamp parameter is passed, in which case we should not change that flow.

2023-10-03 21:18 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp.json
Thanks I have removed them.

2023-10-03 21:20 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/no-params.json
I removed the timestamp param test and the setup related to it except for a few items that demonstrated that the endpoint discerns between entries with older timestamps and entries with more recent ones.

2023-10-03 21:20 UTC, edwin-greene commented on hedera-mirror-rest/accounts.js
> +    accountBalanceQuery.query = `ab.account_id = e.id and ab.consensus_timestamp = e.balance_timestamp`;
Thanks I have removed this change.

2023-10-03 22:58 UTC, steven-sheehy requested changes

2023-10-03 22:58 UTC, steven-sheehy commented on hedera-mirror-rest/accounts.js
> +          timestamp: utils.nsToSecNs(row.balance_timestamp),
I don't see where we're removing the `select max(consensus_end) from record_file` sub-query. There might be multiple.

2023-10-04 14:42 UTC, edwin-greene commented on hedera-mirror-rest/accounts.js
> +          timestamp: utils.nsToSecNs(row.balance_timestamp),
Thanks for spotting those, I have removed them.

2023-10-04 19:02 UTC, xin-hedera requested changes

2023-10-04 20:26 UTC, xin-hedera approved these changes
LGTM

2023-10-04 20:29 UTC, steven-sheehy approved these changes

2023-10-04 21:18 UTC, merged