06969: Enhance ContractController to return error in case of not supported block type
hashgraph/hedera-mirror-node pull request #6975
Opened 2023-09-29 06:50 UTC by bilyana-gospodinova

**Description**:
ContractController is modified so that an error code is returned if block with value "pending", "safe", "finalized" is passed.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/6969

2023-09-29 07:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +    @ResponseStatus(BAD_REQUEST)
I think it would be better to return `NOT_IMPLEMENTED` response status, so that the user knows we don't support these values and it's not a user mistake passing such block values.

2023-09-29 07:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
>          if (StringUtils.isEmpty(value) || BlockType.LATEST.name().equalsIgnoreCase(value)) {
We can put standalone check in the beginning that returns BlockType.LATEST if we don't have block values passed.

Then we can use switch statement for all other types.

2023-10-05 03:29 UTC, steven-sheehy requested changes

2023-10-05 03:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +        return Arrays.stream(UNSUPPORTED_TYPES)
This is incorrect since block can also be a hex number. We should revert to the previous logic. BlockType.of() will be called by BlockTypeDeserializer which is called by spring validation/conversion. Also, streams are slow and we shouldn't use them here.

2023-10-05 03:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +                    return new BlockType(BlockTypeName.EARLIEST.name, 0L);
EARLIEST and LATEST should be static values like before since they're the same for all requests.

2023-10-05 03:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +                case LATEST, PENDING, SAFE, FINALIZED -> {
We should just throw an exception if pending, safe or finalized.

2023-10-05 03:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +            final BlockTypeName blockTypeName = BlockTypeName.valueOf(value.toUpperCase());
valueOf is inefficient since it throws an exception for hex number and exceptions are relatively slow to create to be used for conditional logic. Instead, we can skip the enum and just convert value to lowercase and use switch statement with string.

2023-10-09 07:16 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +    @ResponseStatus(BAD_REQUEST)
As explained in Steven's comment the status will be BAD_REQUEST.

2023-10-09 07:17 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
>          if (StringUtils.isEmpty(value) || BlockType.LATEST.name().equalsIgnoreCase(value)) {
Done

2023-10-09 07:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +        }
If we throw an exception inside BlockType.of() then the returned error will be something like "Malformed JSON" because the deserialization will throw an exception and the message will be misleading. I introduced a placeholder static UNSUPPORTED block type value for "pending", "safe", "finalized" so that we can check for this value in the ContractController and throw the proper exception that will then be caught by the exception handler and return a proper message that the block type value is not supported. What do you think about this approach?

2023-10-09 07:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
> +    private Mono<GenericErrorResponse> invalidBlockType(final InvalidBlockTypeException e) {
Done

2023-10-09 07:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +        return Arrays.stream(UNSUPPORTED_TYPES)
Done

2023-10-09 07:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +                    return new BlockType(BlockTypeName.EARLIEST.name, 0L);
Done

2023-10-09 07:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +                case LATEST, PENDING, SAFE, FINALIZED -> {
Please check my other comment.

2023-10-09 07:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +            final BlockTypeName blockTypeName = BlockTypeName.valueOf(value.toUpperCase());
Done

2023-10-10 01:01 UTC, Nana-EC requested changes
I think we should incorporate finality into the  block considerations

2023-10-10 01:01 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +    public static final BlockType UNSUPPORTED = new BlockType("", 0L);
Q: should the number differ from EARLIEST?
This will avoid misconception should someone ever compare the block number or use it for inference.
```suggestion
    public static final BlockType UNSUPPORTED = new BlockType("", -1L);
```
or if you make number an Integer (not making an argument for it)
```suggestion
    public static final BlockType UNSUPPORTED = new BlockType("", null);
```

2023-10-10 16:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +            case "latest" -> {
That's an interesting perspective.

In the first place, it should be uncommon and wrong a user to send such a block value to the Hedera network, so it would be a bit of a corner case.

The Hedera architecture, indeed embeds finality for each new block/record file and the `safe`/`pending`/`finalized` block behaviour should be already incorporated into the `latest` block we have.

The user shouldn't expect to pass for examples 2 requests with `pending` and `latest` block and to expect different results, so we should be safe of applying the same logic for all these values.

It would be also great to await for @steven-sheehy opinion before finalizing this PR.

2023-10-11 15:27 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +            case "latest" -> {
Sounds reasonable to me. It's better to be more permissive of user input if possible.

2023-10-12 08:47 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +            case "latest" -> {
Changed as requested.

2023-10-12 08:48 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/BlockType.java
> +    public static final BlockType UNSUPPORTED = new BlockType("", 0L);
UNSUPPORTED is now removed as it is no longer needed after the changes from https://github.com/hashgraph/hedera-mirror-node/pull/6975#discussion_r1351090690.

2023-10-12 11:20 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2023-10-12 23:23 UTC, Nana-EC approved these changes
LG

2023-10-13 05:40 UTC, IvanKavaldzhiev commented
We can add default statement to  the switch, which invokes an extracted method for parsing numeric block values, so that we resolve code smells. Then we can merge the PR.

2023-10-13 06:18 UTC, kselveliev approved these changes

2023-10-14 02:36 UTC, Nana-EC approved these changes

2023-10-14 02:37 UTC, merged