5207 support adhoc transaction filters
hashgraph/hedera-mirror-node pull request #6979
Opened 2023-09-29 17:23 UTC by jascks

**Description**:
As a mirror node operator, I might like to filter by something more complex than entity ID or transaction type that the config currently allows.

* Add `hedera.mirror.importer.parser.(exclude|include).expression` properties that accept a [Spring Expression Language](https://www.baeldung.com/spring-expression-language) string that evaluates to a predicate.
* For each non-blank expression, create the expression parser on startup and for each transaction evaluate it against only the `TransactionRecord` and `TransactionBody` objects.
* Update filtering docs with a useful example and link to SPeL docs for further options.
* Double check this doesn't decrease performance at 10K TPS when it's used.

**Related issue(s)**:

Fixes #5207 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-02 22:13 UTC, steven-sheehy requested changes

2023-10-02 22:13 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +            if (target instanceof RecordItem && !ACCESSIBLE_PROPERTIES.contains(name)) {
Is it possible for any other target than `RecordItem` to occur? Probably we should just return false if not RecordItem.

2023-10-03 13:43 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +            if (target instanceof RecordItem && !ACCESSIBLE_PROPERTIES.contains(name)) {
It is possible, as properties are evaluated hierarchically. For example, in evaluating the expression `transactionBody.transactionID.accountID.accountNum > 0` the `canRead()` method is invoked multiple times as the properties are "traversed". Also note that the context is used to cache a lot of the reflective access Spring performs.

![canRead-info](https://github.com/hashgraph/hedera-mirror-node/assets/218465/a29cdd69-7300-491b-9b7a-a03f46f3fe62)

2023-10-03 13:45 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.exclude.expression`                               |                                                  | A Spring Expression Language (SpEL) expression which when evaul
Done.

2023-10-03 13:46 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.include.expression`                               |                                                  | A Spring Expression Language (SpEL) expression which when evaul
Done

2023-10-03 13:49 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +        private Expression parsedExpression;
SonarLint was not happy:

![Screenshot 2023-10-03 at 7 47 05 AM](https://github.com/hashgraph/hedera-mirror-node/assets/218465/286674d5-b216-48dd-bcb1-55d13056510c)

I'm thinking of ditching `@Data` and using an actual constructor which will parse the expression at that time.

2023-10-03 16:51 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +        private Expression parsedExpression;
Currently it's not thread safe. It's okay to create twice but we don't want callers to see incomplete objects and fail so it needs to be thread safe. We can use constructor or we can also use `Getter(lazy = true, access = PRIVATE)`

2023-10-03 21:43 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +        private Expression parsedExpression;
Parsing is now done in the constructor of the now immutable `TransactionFilter`.

2023-10-05 19:36 UTC, steven-sheehy requested changes

2023-10-05 19:36 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/CommonParserPropertiesTest.java
> +        commonParserProperties.getExclude().add(filter(null, "transactionBody.memo.startsWith(\"MyApp\")", null));
We should add a simple expression to filterInclude, filterExclude, and filterBoth that verifies an expression works properly in combination with entitities and types.

2023-10-05 21:01 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.include.expression`                               |                                                  | A Spring Expression Language (SpEL) expression which when evalu
Agreed. Just pushed some changes. Maybe I'm over doing it? But, I want to enlighten the users of this regard pitfalls and fixes. Perhaps a separate document would be in order? Or should I keep going?

2023-10-05 21:02 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +    static class TransactionFilter {
Yes, it does work. The builder/constructor is being found, thus:
```
hedera:
  mirror:
    importer:
      parser:
        exclude:
          - entity: [ 0.0.98 ]
            expression: transactionBody.transactionFee < 0
        include:
          - entity: [ 0.0.1000, 0.0.1001 ]
          - expression: "transactionBody.transactionID.accountID.accountNum >= 0 && transactionBody.nodeAccountID.accountNum >= 0"
 ```
Does get configured correctly.

2023-10-05 21:04 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +@CustomLog
Removed.

2023-10-05 21:04 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/CommonParserProperties.java
> +                        "Transaction filter expression failed to evaluate: %s".formatted(expression), ex);
😄 Done.

2023-10-06 12:53 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/CommonParserPropertiesTest.java
> +        // Disallowed root RecordItem access
Done

2023-10-06 12:53 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/CommonParserPropertiesTest.java
> +        commonParserProperties.getExclude().add(filter(null, "transactionBody.memo.startsWith(\"MyApp\")", null));
Done

2023-10-06 14:20 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.include.expression`                               |                                                  | A Spring Expression Language (SpEL) expression which when evalu
I updated this file to show how I enhanced the **Filter Example** to include an expression. I wanted to propose this story angle and see what you think. I still need to test the configurations will load and do what is described.

2023-10-06 16:40 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.include.expression`                               |                                                  | A Spring Expression Language (SpEL) expression which when evalu
I have verified in IDEA that the configurations do indeed work. The YAML and properties based config were pretty straight forward, but for the environment variables, I was required to reformat them (separate by ;, use = rather than :, boolean not in double quotes etc.). After doing that, it worked fine.

In what way could I directly process the environment variables example existing in this document?

2023-10-06 22:17 UTC, steven-sheehy requested changes

2023-10-06 22:17 UTC, steven-sheehy commented on docs/configuration.md
> +The mirror node Importer fails to start up:
Think we should remove this section. It reads like a debugging session and the errors are pretty self-explanatory. Maybe just add a bullet to above restrictions about single/double quotes.

2023-10-06 22:17 UTC, steven-sheehy commented on docs/configuration.md
> +  (protobufs) defined in the `com.hederahashgraph:hedera-protobuf-java-api` dependency. These are immutable and you can
Drop the maven artifact and just link TransactionBody and TransactionRecord to the github repo where they live.

2023-10-06 22:17 UTC, steven-sheehy commented on docs/configuration.md
> +```
Think we can remove this as well since we note how to configure it below in the other examples.

2023-10-07 15:13 UTC, jascks commented on docs/configuration.md
> +The mirror node Importer fails to start up:
Done

2023-10-07 15:13 UTC, jascks commented on docs/configuration.md
> +  (protobufs) defined in the `com.hederahashgraph:hedera-protobuf-java-api` dependency. These are immutable and you can
Done

2023-10-07 15:13 UTC, jascks commented on docs/configuration.md
> +```
Done

2023-10-07 23:22 UTC, steven-sheehy approved these changes
LGTM

2023-10-09 13:06 UTC, jnels124 approved these changes
LGTM

2023-10-09 13:53 UTC, merged