Remove not cached tokens
hashgraph/hedera-mirror-node pull request #6997
Opened 2023-10-02 11:32 UTC by 0xivanov

**Description**:
Currently there are tokens in the acceptance tests that are not cached and this causes additional unnecessary expense when running them.
Reduce the amount of tokens being created by using and/or adding tokens from the tokenMap cached tokens.

**Related issue(s)**:

Fixes #6996 

**Notes for reviewer**:
Hbars used before the change for all tests: ~258
Hbars used after the change for all tests: ~244

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-11 14:16 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        tokenIds.add(tokenId);
I understand that this isn't within the scope of the current ticket, but I believe it might be better to eliminate the tokenIds list. You can check how tokens are handled within the `estimatePrecompile` feature, where they are stored in variables and accessed as needed.

2023-10-11 14:16 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        tokenIds.add(tokenClient
Same comment applies here for the tokenIds.

2023-10-12 11:14 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        FUNGIBLE_2(
Why we need a second fungible token with the same kyc and freeze status? If there is a particular reason, we can note it in the token naming, so that it's clear what's the different use case for this token.

2023-10-12 11:15 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        NFT_2(
The same comment for `NFT_2`

2023-10-13 08:15 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        FUNGIBLE_2(
The reason is that if we use the same token "FUNGIBLE", for example, one of the suits does operation (delete) that makes operation (transfer) from the other suite fail.
The operations are just for example.

2023-11-16 11:05 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        tokenIds.add(tokenId);
Removed the list

2023-11-16 11:06 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        tokenIds.add(tokenClient
Removed the list

2023-11-16 11:21 UTC, 0xivanov commented
I've ran these test at least 100 times since this PR is open and the current cached configuration is the only one that has worked for me so far.

2023-11-16 13:04 UTC, yiliev0 commented
LGTM, I've also tested it against local/integration env and it ran without a problem. We can remove the `System.out.println` used for logging out stuff, I don't think they are needed anymore

2023-11-16 13:05 UTC, yiliev0 approved these changes
LGTM, I've also tested it against local/integration env and it ran without a problem. We can remove the `System.out.println` used for logging out stuff, I don't think they are needed anymore

2023-11-16 21:00 UTC, steven-sheehy requested changes

2023-11-17 18:10 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCEFUNGIBLE(
The problem is that cucumber cannot cannot detect the enum if it is snake_case.

2023-11-17 18:10 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        FUNGIBLE_2(
Done

2023-11-17 18:10 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        assertThat(getSymbolResponse.getResultAsText()).isEqualTo("fungible_2");
Done

2023-11-17 18:10 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ERCContractFeature.java
> +        assertThat(getNameResponse.getResultAsText()).isEqualTo("fungible_2_name");
Done

2023-11-17 18:11 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public TokenResponse getToken(TokenNameEnum tokenNameEnum, List<CustomFee> customFees) {
Done

2023-11-17 18:11 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
>      private final Map<TokenNameEnum, TokenId> tokenMap = new ConcurrentHashMap<>();
Done

2023-11-17 18:14 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        Thread.sleep(2000);
comment updated

2023-11-17 18:48 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCEFUNGIBLE(
How can that be so if we have other snake case enums like FUNGIBLE_2?

2023-11-17 19:58 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCEFUNGIBLE(
It only happens if we pass it as value to the .feature file, a workaround would be to use the enum in the class itself.
Here is what i am talking about:
<img width="894" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/56980328/f75b2c0f-fce1-46f6-86f7-1801062554c2">

if i use snake case here the feature cannot run, if you know some other trick for this to work feel free to share

2023-11-17 22:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCEFUNGIBLE(
Ok, not a big deal. Can keep as is.

2023-11-17 22:15 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-11-17 22:15 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        tokenMap.clear();
nit: It's redundant since `deleteAll()` also removes from map.

2023-11-17 22:16 UTC, steven-sheehy commented
Seems to be a sign-off problem. DCO check fails. Can you check?

2023-11-20 07:31 UTC, 0xivanov commented
> Seems to be a sign-off problem. DCO check fails. Can you check?

Managed to fix it. Don't know why it failed though, all my commits were verified.

2023-11-20 07:33 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        tokenMap.clear();
Doesn't `deleteAll` remove only the `tokenIds` elements?

2023-11-20 20:09 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        tokenMap.clear();
True, we should actually consolidate the two by doing `deleteAll(tokenMap.values(), ...`. Then we can delete `tokenIds`

2023-11-20 20:19 UTC, steven-sheehy approved these changes

2023-11-20 20:19 UTC, merged