Filtering contract files for big file ids.
hashgraph/hedera-mirror-node pull request #7000
Opened 2023-10-02 21:30 UTC by mgoelswirlds

**Description**:

Improving the efficiency of loading contract initcode.

This PR modifies
* The contracts by id call to filter by some file_ids.

**Related issue(s)**:

Fixes #6980

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-02 23:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/FileDataRepositoryTest.java
> +        assertNull(actualBytes);
Prefer not to hardcode fields unless necessary or increase their scope. Also always use assertj.
```suggestion
        var fileId = EntityId.of(0L, 0L, 151L);
        var file = domainBuilder.fileData().customize(f -> f.entityId(fileId).persist();

        assertThat(fileDataRepository.getFileAtTimestamp(fileId.getId(), file.getConsensusTimestamp()).isNull();
```

2023-10-03 16:47 UTC, steven-sheehy requested changes

2023-10-03 16:47 UTC, steven-sheehy commented on hedera-mirror-rest/service/fileDataService.js
> +        and ${FileData.ENTITY_ID} > 1000 -- < 1000 would be invalid user files
This `getFileData` is currently only used to retrieve initcode, but in theory it could be used elsewhere in the future. We should probably move this check into a util and check it in code.

2023-10-03 16:47 UTC, steven-sheehy commented on hedera-mirror-rest/service/fileDataService.js
>          select ${FileData.CONSENSUS_TIMESTAMP}
There's a couple other places that call `FileDataService.getLatestFileDataContents()` with an callDataId that we also need to cover. But we can't modify this shared query so need to check in code via the util.

2023-10-03 19:56 UTC, mgoelswirlds commented on hedera-mirror-rest/service/fileDataService.js
> +        and ${FileData.ENTITY_ID} > 1000 -- < 1000 would be invalid user files
If we do this check in the code, what should we return for file data when the ids don't match? 0x?

2023-10-03 20:02 UTC, steven-sheehy commented on hedera-mirror-rest/service/fileDataService.js
> +        and ${FileData.ENTITY_ID} > 1000 -- < 1000 would be invalid user files
0x sounds good. Basically just skip query if file id is in bad range

2023-10-04 22:29 UTC, mgoelswirlds commented
Still working on adding test cases for the callDataId case.

2023-10-05 16:31 UTC, xin-hedera requested changes

2023-10-05 16:31 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +import {isValidUserFileId} from '../utils';
duplicate import since the whole `utils` module is imported on line 38

2023-10-05 16:31 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    if (contract.file_id !== null && isValidUserFileId(contract.file_id)) {
change `isValidUserFileId` to first do `_.isNil`, then this line can be simplified to
```suggestion
    if (utils.isValidUserFileId(contract.file_id)) {
```

2023-10-05 16:31 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +    if (ethTransaction && !_.isNil(ethTransaction.callDataId) && isValidUserFileId(ethTransaction.callDataId)) {
simplify this line the other same line to
```suggestion
    if (utils.isValidUserFileId(ethTransaction?.callDataId)) {
```

2023-10-05 16:31 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +           ${FileData.ENTITY_ID} = $1
revert the extra space at the end?

2023-10-05 16:31 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return val > 1000;
do `_.isNil` first, and add unit test

2023-10-05 19:08 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const isValidUserFileId = (val) => {
missing unit test

2023-10-05 20:04 UTC, mgoelswirlds commented on hedera-mirror-rest/utils.js
> +const isValidUserFileId = (val) => {
Ahh yes.

2023-10-05 22:00 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/utils.test.js
> +  test('150', () => expect(utils.isValidUserFileId('150')).toBeFalse());
better test with `Number` or `BigInt` since that's the type passed to the function in the contract controller

```suggestion
  test('1001', () => expect(utils.isValidUserFileId(1001)).toBeTrue());
  test('5001', () => expect(utils.isValidUserFileId(5001)).toBeTrue());
  test('1000', () => expect(utils.isValidUserFileId(1000)).toBeFalse());
  test('150', () => expect(utils.isValidUserFileId(150)).toBeFalse());
```

2023-10-06 14:28 UTC, steven-sheehy approved these changes
LGTM

2023-10-06 14:40 UTC, xin-hedera approved these changes
LGTM

2023-10-06 14:45 UTC, merged