Refactor test suites to use headlong function encoding
hashgraph/hedera-mirror-node pull request #7009
Opened 2023-10-04 15:31 UTC by yiliev0

**Description**: This PR addresses the need to bring better consistency and maintainability to our test suites by refactoring the encoding of function selectors and parameters using the Headlong library.
Changes:
* Refactored CallFeature, EstimateFeature, PrecompileContractFeature, ERCConctractFeature to leverage Headlong framework for function encoding;
* Added a new function `getFunctionFromArtifact` in `AbstractFeature` which facilitates extracting a Function object directly from a compiled artifact;
* Removed redundant resource declarations and centralized all necessary resource paths into the `ContractResource` enum within `AbstractFeature`, ensuring a more organized and maintainable approach to resource management. 

**Related issue(s)**:

Fixes #7006

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-05 00:41 UTC, steven-sheehy requested changes

2023-10-05 00:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +    protected Function getFunctionFromArtifact(SelectorInterface contractMethod, ContractResource resource) {
Prefer ContractResource as the first parameter since it is the primary item and the method is within it. But if it's too much change can keep.

2023-10-05 00:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +                        ContractMethods.IS_TOKEN_FROZEN_SELECTOR, ContractResource.PRECOMPILE_TEST_CONTRACT)
Could reduce a bunch of lines by using static imports, especially for ContractResource.

2023-10-05 15:05 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +    protected Function getFunctionFromArtifact(SelectorInterface contractMethod, ContractResource resource) {
Refactored. In IntelliJ there's right click on the method->Refactor->Change Signature that makes it easy to change.

2023-10-05 15:05 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +                .encodeCallWithArgs(asAddress(tokenId.toSolidityAddress()));
Implemented.

2023-10-05 15:05 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        ByteBuffer encodedFunctionCall = getFunctionFromArtifact(
Implemented.

2023-10-05 15:06 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        ContractCallResponse response = callContract(Strings.encode(encodedFunctionCall), estimateContractAddress);
Changes `callContract` and `validateGasEstimation` to support ByteBuffer.

2023-10-05 15:07 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +                        asAddress(receiverAccountId.getAccountId().toSolidityAddress()), new BigInteger("10000"));
I've added several overloaded `asAddress` methods that reduced some lines. Thanks.

2023-10-05 15:07 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        reentrancyCallWithGas("reentrancyCallWithGas");
Done.

2023-10-05 18:26 UTC, steven-sheehy requested changes

2023-10-05 18:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +                new Function(NAME_SELECTOR.getSelector()).encodeCallWithArgs(),
Maybe we should have an overloaded `encodeData(ContractMethods, Object...)` as well for these cases?

2023-10-05 18:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        ContractCallResponse response = callContract(
nit: Can use `var` for `ContractCallResponse` everywhere to shorten line length.

2023-10-05 18:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +                .data(Strings.encode(data))
Maybe make `encodeData` return a string so you don't have to pass around `ByteBuffer` just to always turn it into a string.

2023-10-05 18:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +                .data(Strings.encode(
Can we not use `validateGasEstimation` in this step? Or create a separate `estimateContract` that sets estimate to true

2023-10-05 18:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +                encodeData(
It would be cleaner if `var data = encodeData(...);` was moved to a separate line, then perhaps `validateGasEstimation` could be on one line. Same comment elsewhere.

2023-10-05 18:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                ESTIMATE_PRECOMPILE_TEST_CONTRACT,
All contracts in `ContractResource` are test contracts, so it's redundant to append `_TEST_CONTRACT`. If we remove unnecessary suffix perhaps some of these multi-line `encodeData()` can revert to single line.

```suggestion
                ESTIMATE_PRECOMPILE,
```

2023-10-06 12:28 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                ESTIMATE_PRECOMPILE_TEST_CONTRACT,
Done. Remove the "_TEST_CONTRACT" suffix.

2023-10-06 12:31 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +                encodeData(
I've applied this change wherever I spotted the opportunity across the tests, there might be a few places I could have missed due to the number of tests. Thanks for suggestion.

2023-10-06 12:32 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +                .data(Strings.encode(
I've created a separate `estimateContract` function that worked for this test. Thanks!

2023-10-06 12:32 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +                .data(Strings.encode(data))
Yes, I've applied this change. Now it looks way better. Thanks!

2023-10-06 12:38 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
>          var contractCallRequestBody = ContractCallRequest.builder()
Replaced with `callContract()`. Thanks.

2023-10-06 12:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
> +        ContractCallResponse response = callContract(
Done!

2023-10-06 14:48 UTC, steven-sheehy approved these changes
LGTM

> +1,328 −2,062

Nice reduction in lines!

2023-10-06 14:57 UTC, merged