Ignore staking fields before staking was enabled
hashgraph/hedera-mirror-node pull request #7019
Opened 2023-10-06 15:10 UTC by mgoelswirlds

**Description**:

Some accounts started to stake to a node before staking feature went alive in mainnet. 
In this PR mirror node will check for the HAPI version to check for the version when services started supporting staking.

This PR  
* Checks for the hapi version to be greater than 0.27.0 to implement staking functionality.

**Related issue(s)**:

Fixes #6973

**Notes for reviewer**:

The tests had hapi version set to 0.0 by default, so in this PR I have set them to a value greater than 0.27.0 , in order for them to pass.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-06 16:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
> +    static final Version HAPI_VERSION_0_27_0 = new Version(0, 27, 0);
also remove all these duplicates

2023-10-06 16:15 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixStakedBeforeEnabledMigrationTest.java
> +    @ValueSource(strings = {HederaNetwork.MAINNET})
change these `ParameterizedTest` test cases to be not parameterized and change `setupForNetwork` to `setupForMainnet`

2023-10-06 16:22 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java
> +    @ValueSource(longs = {0, 100})
don't need to parameterize the nodeId, can just test with one value

2023-10-06 16:23 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java
> +                .recordItem(r -> r.hapiVersion(new Version(0, 28, 0)))
should have at least one with version 0.27.0

2023-10-06 16:23 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandlerTest.java
> +    @ValueSource(longs = {0, 100})
same, don't need to parameterize the `accountId`

2023-10-09 14:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java
> +        }
nit, add an empty line after the if block

2023-10-09 14:52 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java
> +    void updateTransactionStakedAccountId(int majorVersion) {
```suggestion
    void updateTransactionStakedAccountId(int minorVersion) {
```

2023-10-09 14:52 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java
> +    void updateTransactionStakedAccountId(long accountNum, int majorVersion) {
```suggestion
    void updateTransactionStakedAccountId(long accountNum, int minorVersion) {
```

2023-10-09 16:45 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> -                () -> assertEquals(4, contractRepository.count()),
The contract count has changed since I changed the version to be > 0.23.0 after the child contracts weren't created as part of the parent.

2023-10-10 00:40 UTC, xin-hedera requested changes

2023-10-10 00:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    private static final Version HAPI_VERSION_0_28_0 = new Version(0, 28, 0);
will the change not reduce test coverage? Do we still have a test case for HAPI < 0.23.0 and verify the number of contracts include those in the created_contract_ids?

2023-10-10 00:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java
> +    void updateTransactionStakedNodeId(int majorVersion) {
this is still `majorVersion`

2023-10-10 00:40 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandlerTest.java
> +    void updateTransactionStakedNodeId(Long nodeId, int majorVersion) {
same here.

I may not mark all the places with the same issue, so please do a thorough check.

2023-10-10 15:45 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
> +    private static final Version HAPI_VERSION_0_28_0 = new Version(0, 28, 0);
It is restored to check for <0.23  in getExpectedEntityTransactions , other places changing it to 0.28 will not change coverage.

2023-10-12 18:39 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        if (recordItem.getHapiVersion().isLessThan(HAPI_VERSION_0_27_0)) {
In the PR, it says:
```
Checks for the hapi version to be greater than 0.27.0 to implement staking functionality.
```
This statement allows  performing staking functionality only when the HAPI version is _not less than_ `HAPI_VERSION_0_27_0`, or greater than _or equal to_ 0.27.0. Which way does it need to be?

2023-10-12 19:04 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        if (recordItem.getHapiVersion().isLessThan(HAPI_VERSION_0_27_0)) {
Thanks for pointing that out. It should be >= 0.27.0. I have corrected that in the description.

2023-10-12 19:06 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        if (recordItem.getHapiVersion().isLessThan(HAPI_VERSION_0_27_0)) {
Okay, I see `ContractCreateTransactionHandlerTest.updateTransactionStakedAccountId()` treats 0.27.0 and 0.28.0 as the same, so it looks like >= 0.27.0 is the intent.

2023-10-12 19:14 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java
> +        if (recordItem.getHapiVersion().isLessThan(HAPI_VERSION_0_27_0)) {
👍

2023-10-12 19:59 UTC, jascks approved these changes
LGTM

2023-10-13 04:59 UTC, xin-hedera approved these changes
LGTM

2023-10-13 13:32 UTC, merged