Rough draft of account balance deduplication
hashgraph/hedera-mirror-node pull request #7035
Opened 2023-10-09 18:11 UTC by edwin-greene

Duplicate entries will not be placed in the account_balance or token_balance tables when the dedup property is set and when the current partition already has the balance for the account/token.

**Related issue(s)**:

Fixes #3507 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-10-10 01:33 UTC, xin-hedera requested changes

2023-10-10 01:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        }
this is wrong. if `[lastBalanceTimestamp, timestamp]` is within the current partition, `partitions.size()` will be 1.

if it's empty, it's because either the table is not partitioned or sth is seriously wrong.

2023-10-10 01:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        }
should just return true when `partitions.size() > 1`

2023-10-10 01:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    @Transactional
there is performance issue because the CTE part will scan all the time partitions to determine max(consensus_timestamp) for each account.

Instead, to create a new snapshot with deduped info, we should

1. Find the current time partition
2. Find the latest account balance snapshot in the current partition, however, return (account_id, balance) instead of (account_id, consensus_timestamp)
3. insert new row for an account when it's account 2, or its balance has changed

Note, when comparing balance to dedupe, the condition should be `(abs.balance is null or e.balance <> abs.balance)`

2023-10-10 01:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    Optional<AccountBalance> findLatest();
Same performance issue because

1. the query doesn't use the sentinel account id 2
2. the query will go to all time partitions

so similarly, we need to add a partition range, however, we may need to search in two partitions, i.e., the current and the next, instead of just the current.

2023-10-10 01:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint token_balance__pk primary key (token_id, account_id, consensus_timestamp);
shouldn't the index be `(account_id, token_id, consensus_timestamp)`?

2023-10-12 18:48 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                int accountBalancesCount = (properties.isDedupe() && !includeAllBalances(timestamp))
Thanks I have reworked this.

2023-10-12 18:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        }
I see, please review again as I have reworked this area.

2023-10-12 18:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        }
I have updated this, it should now work with no partitions and partitions of variable sizes.

2023-10-12 18:50 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    @Transactional
Thanks I have refactored this query to include the partition key, it should now be more performant on v2.

2023-10-12 18:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    Optional<AccountBalance> findLatest();
Thanks I have refactored things and removed this.

2023-10-12 18:51 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
> +    add constraint token_balance__pk primary key (token_id, account_id, consensus_timestamp);
Got it, I have fixed this.

2023-10-17 22:48 UTC, steven-sheehy requested changes

2023-10-17 22:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                .orElse(Range.closedOpen(LOWER_RANGE, UPPER_RANGE));
Can cache the entire `Range` object instead of the longs.

2023-10-17 22:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    int updateBalanceSnapshot(long lowerRangeTimestamp, long upperRangeTimestamp, long consensusTimestamp);
Add this method to `BalanceSnapshotRepository`

2023-10-17 22:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +        from entity e left join account_balance_snapshot abs on e.id = abs.account_id
We're not even using the `entity.balance_timestamp` which is the main purpose of that column. The ticket states `only insert into balance table if balance_timestamp changed between the consensus timestamp of the last run`.

```sql
insert into account_balance (account_id, balance, consensus_timestamp)
select e.id, e.balance, :consensusTimestamp
from entity e
where e.id = 2 or (e.balance is not null and e.deleted is not true and 
e.balance_timestamp > (select max(consensus_timestamp) from account_balance where account_id = 2))
```

2023-10-17 22:48 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +    private Range<Long> getPartitionRange(long timestamp, String tableName) {
We should not need to do any partition logic here. Instead, modify the partition cron to copy the last balance snapshot from the previous snapshot to the newly created partition.

2023-10-18 14:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +        from entity e left join account_balance_snapshot abs on e.id = abs.account_id
Ideally we should compare balance since balance timestamp was changed <> balance was changed. However, comparing to account 2's max consensus timestamp should be much faster than first finding the all the account's last balance and then comparing by balance, so agree with the approach.

2023-10-18 14:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +        from entity e left join account_balance_snapshot abs on e.id = abs.account_id
We still want to limit the query `select max(consensus_timestamp) from account_balance where account_id = 2` to the current partition with timestamp range `[lowerRangeTimestamp, upperRangeTimestamp)`

2023-10-18 15:18 UTC, xin-hedera requested changes

2023-10-18 15:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +    private static final long UPPER_RANGE = 9223372036854775807L;
nit

```suggestion
    private static final long UPPER_RANGE = Long.MAX_VALUE;
```

2023-10-18 16:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +        order by ta.account_id, ta.token_id\s
interesting this didn't cause any issue

```suggestion
        order by ta.account_id, ta.token_id
```

2023-10-25 18:34 UTC, edwin-greene commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.historicalBalance.dedupe`                  | false                                            | Whether to deduplicate balance information
Thanks I have updated it to `deduplicate`

2023-10-25 18:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                .orElse(Range.closedOpen(LOWER_RANGE, UPPER_RANGE));
Good idea, I have added that.

2023-10-25 18:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +    int updateBalanceSnapshot(long lowerRangeTimestamp, long upperRangeTimestamp, long consensusTimestamp);
Got it, I have updated `BalanceSnapshotRepository`.

2023-10-25 18:36 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +        from entity e left join account_balance_snapshot abs on e.id = abs.account_id
Sounds good, the queries have now been updated to use `balance_timestamp` and they have been simplified to this version.

2023-10-25 18:37 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                    range.lowerEndpoint(), range.upperEndpoint(), timestamp);
The full snapshot is now implemented in the java code.

2023-10-25 18:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                    range.lowerEndpoint(), range.upperEndpoint(), timestamp);
This should now be seen in the java code.

2023-10-25 18:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +    private static final long UPPER_RANGE = 9223372036854775807L;
Thanks I have updated it to the constant.

2023-10-25 18:38 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +        order by ta.account_id, ta.token_id\s
Thanks I have removed that typo.

2023-10-25 20:47 UTC, xin-hedera requested changes

2023-10-25 20:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                            properties.isTokenBalances() ? tokenBalanceRepository.balanceSnapshot(timestamp) : 0;
The logic can be simplified if we first determine if the snapshot should be full or deduped, we'd reduce duplicate code and no longer need  the function `updateBalanceSnapshot()` / `updateTokenBalanceSnapshot()`.

Overall, it should be:

```
   bool fullSnapshot = true;
   if (properties.isDeduplicate()) {
      check if this is not the first balance snapshot in a new partition, if so, set fullSnapshot to false, as well as finding other variables needed by `*BalanceRepository.updateBalanceSnapshot`
   }

  if (fullSnapshot) {
    *BalanceRepository.balanceSnapshot(...);
  } else {
    *BalanceRepository.updateBalanceSnapshot(...);
  }
```

2023-10-25 20:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                    long maxConsensusTimestamp = accountBalanceRepository.getMaxConsensusTimestampInRange(
`accountBalanceRepository.getMaxConsensusTimestampInRange` should return `Optional<Long>` and return an empty optional instead of coalescing to 0 if no value found. That way, we immediately know we need to create a full snapshot, i.e., we no longer need to compare `lastConsensusTimestamp` and `partitionRange.lowerEndPoint`

2023-10-25 20:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        var partitions = timePartitionService.getTimePartitions(tableName);
we really should use `timePartitionService.getOverlappingTimePartitions(tableName, timestamp, timestamp)` since it's a binary search v.s. a linear search of all the partitions returned by `timePartitionService.getTimePartitions`. I'm fine to keep it as is to reduce the churn.

2023-10-25 20:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                .orElse(DEFAULT_RANGE);
If the table is partitioned, and no partition containing `timestamp` found, shouldn't we throw an exception to fail early?

The fact is if this ever happens, when we insert data into `account_balance` table, it'll still fail because the corresponding partition doesn't exist.

2023-10-25 21:04 UTC, xin-hedera requested changes

2023-10-25 21:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +           balance_timestamp < :upperRangeTimestamp)
```suggestion
           balance_timestamp > :maxConsensusTimestamp)
```

Check the upper bound is unnecessary. There is an inherent on the caller to guarantee that when the method is called, the entity table state should be at the time of `consensusTimestamp`.

Since the consensusTimestamp is the new account balance snapshot's timestamp, and it's inside the current partition, it should never happen that any entity's balanceTimestamp >= upperRangeTimestamp.

Instead, we can add a javadoc  to the interface method.

Note, in the historical balance service, we set transaction isolation level to repeatable reads to guarantee it.

2023-10-25 21:16 UTC, steven-sheehy requested changes

2023-10-25 21:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +        select account_id, balance, :consensusTimestamp, token_id
Shouldn't the `consensus_timestamp` of the balance tables be populated with the `balance_timestamp` and not the snapshot's timestamp? This would be more accurate but probably we have to wait until we stop inserting account balance file entries.

2023-10-25 21:16 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/BalanceSnapshotRepository.java
> +    int updateBalanceSnapshot(long maxConsensusTimestamp, long upperRangeTimestamp, long consensusTimestamp);
You're not really updating a previous snapshot since it's only inserting rows. Maybe `balanceSnapshotDeduplicate`, `balanceSnapshotPartition`, etc.

2023-10-26 20:31 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +        select account_id, balance, :consensusTimestamp, token_id
From what I can tell that should be an easy change when we are ready for it.

2023-10-26 20:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                .orElse(0L);
Sounds good I have updated it to `Long.MAX`.

2023-10-26 20:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                            properties.isTokenBalances() ? tokenBalanceRepository.balanceSnapshot(timestamp) : 0;
Thanks I have reworked this section, it is now similar to what you have described.

2023-10-26 20:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                    long maxConsensusTimestamp = accountBalanceRepository.getMaxConsensusTimestampInRange(
Great thanks. I have updated it to return the Optional.

2023-10-26 20:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        var partitions = timePartitionService.getTimePartitions(tableName);
I found that switching to `getOverlappingTimePartitions` could also simplify some other logic so I have updated it to use that method instead.

2023-10-26 20:34 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                .orElse(DEFAULT_RANGE);
I updated it with a comment to throw an exception once v1 is partitioned.

2023-10-26 20:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +           balance_timestamp < :upperRangeTimestamp)
Thanks I have made this change and removed the `upperRangeTimestamp`.

2023-10-26 20:35 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/BalanceSnapshotRepository.java
> +    int updateBalanceSnapshot(long maxConsensusTimestamp, long upperRangeTimestamp, long consensusTimestamp);
Sounds good I have refactored its name.

2023-10-27 04:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        return maxConsensusTimestamp;
let completely remove `lastConsensusTimestamp`.

the logic here should be:

``` java
var partitions = timePartitionService.getOverlappingTimePartitions(ACCOUNT_BALANCE_TABLE_NAME, timestamp, timestamp);
if (partitions.isEmpty()) {
  return Optional.empty(); // once v1 is partitioned, throw exception instead
}

var partitionRange = partitions.get(0).getTimestampRange();
return accountBalanceRepository.getMaxConsensusTimestampInRange(partitionRange.lowerEndpoint(), partitionRange.upperEndpoint);
```

So now we no longer need `lastConsensusTimestamp`, we can revert the changes to `shouldGenerate` and remove the function `getLastConsensusTimestamp()`.

Let me know if you have questions.

2023-10-27 14:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +           deleted is not true and
```suggestion
```

when dedup, we can't skip deleted entities. we need to add the deleted entity's balance into the snapshot (for timestamp at or after the entity is deleted) if balance_timestamp > max. Otherwise, the query to find the deleted entity's balance at or after the entity is deleted will return its balance before deletion.

2023-10-27 14:08 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +        where associated is true and
for the same reason in the comment for AccountBalanceRepository.balanceSnapshotDeduplicate, remove the associated is true check

2023-10-27 17:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        return maxConsensusTimestamp;
Great idea, I have updated it.

2023-10-27 17:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +           deleted is not true and
Thanks I have updated the query.

2023-10-27 17:40 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +        where associated is true and
This is now fixed.

2023-10-29 00:07 UTC, steven-sheehy approved these changes
LGTM

2023-10-31 00:08 UTC, xin-hedera approved these changes
LGTM

2023-10-31 13:56 UTC, merged