6937 several contracts endpoints throw 400 in v2
hashgraph/hedera-mirror-node pull request #7049
Opened 2023-10-12 14:18 UTC by jnels124

**Description**:
* change several contract result endpoints to include v2 partition/distribution keys in queries
* create new table `contract_transaction_hash` 
* create migration to populate  `contract_transaction_hash` 
* update resource requirements for cits worker/coordinator nodes

**Related issue(s)**:

Fixes #6937 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-25 17:25 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +insert into contract_transaction(contract_id,consensus_timestamp,involved_contract_ids,payer_account_id)
Working on collapsing these three queries into a single one

2023-10-26 16:48 UTC, jnels124 commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractTransaction.java
> +    private Long validStartNs;
remove

2023-10-26 17:22 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +              left join contract_state_change csc on csc.payer_account_id = cr.payer_account_id and cr.consensus_timestamp = csc.consensus_timestamp
will drop payer account from these joins..

2023-10-26 17:45 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +    contract_id           bigint       not null, --todo change to entityId
going to change this to entity_id

2023-10-31 21:12 UTC, steven-sheehy requested changes

2023-10-31 21:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            recordItem.addContractTransaction(contractId);
Do we not need involved contracts for contract_action?

2023-10-31 21:12 UTC, steven-sheehy commented on hedera-mirror-rest/model/contractTransaction.js
> + * Copyright (C) 2019-2023 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2023 Hedera Hashgraph, LLC
```

2023-11-01 15:25 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            recordItem.addContractTransaction(contractId);
no because that table is distributed on payerId

2023-11-01 15:26 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            recordItem.addContractTransaction(contractId);
That table partitions on payer account id.

2023-11-01 15:35 UTC, jnels124 commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        contractTransactions.values().forEach(contractTransaction -> contractTransaction.setInvolvedContractIds(ids));
This is only setting the involved contracts for the record item iteself not all in the record file. At least that was the intent. Double checking this.

2023-11-01 15:49 UTC, jnels124 commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractTransactionHash.java
> +import lombok.*;
need to change intellij settings again.

2023-11-01 15:54 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +insert into contract_transaction(entity_id,consensus_timestamp,involved_contract_ids,payer_account_id)
Yes each statement takes about 8 minutes... Once all pr feedback is addressed, I will be cloning staging one more time to rerun migrations, and k6 tests for final numbers

2023-11-01 15:55 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
> +);
this has been addressed already. Unpartitioned transaction_hash

2023-11-01 15:57 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +insert into contract_transaction_hash(consensus_timestamp,hash,payer_account_id,entity_id, transaction_result)
will correct.

2023-11-01 18:17 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +insert into contract_transaction_hash(consensus_timestamp,hash,payer_account_id,entity_id, transaction_result)
Are these actually needed for this table? The only eth transactions without a contract result are for wrong nonce. In the case of contract results by hash, we automatically filter these out. For contract actions, we will only have actions if there was a result.

2023-11-03 22:21 UTC, steven-sheehy requested changes

2023-11-03 22:21 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +        return contractTransactions.values();
We should check if there are contract transactions before allocating any objects.

2023-11-03 22:21 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
> +    private final Map<Long, ContractTransaction> contractTransactions = new HashMap<>();
Vast majority of transactions don't have contract results, so we should lazy create this map. Optimizing for property false is not as important since it defaults to true for us.

2023-11-03 22:21 UTC, steven-sheehy commented on hedera-mirror-rest/service/transactionService.js
The changes to this file seem unrelated to the contract results endpoints

2023-11-04 14:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ContractTransactionRepository.java
> +public interface ContractTransactionRepository extends CrudRepository<ContractTransaction, ContractTransaction.Id> {}
Missing ContractTransactionHashRepository and both should implement RetentionRepository. Both need tests as well

2023-11-07 15:25 UTC, jnels124 commented on hedera-mirror-rest/service/transactionService.js
these changes are needed when looking up a result by transaction id

2023-11-08 17:36 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-11-09 15:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +     group by cr.contract_id, cr.consensus_timestamp, cr.payer_account_id);
aren't these very slow? for mainnet, the query plan includes sequential scan on both contract_result and contract_state_change.

2023-11-09 15:49 UTC, xin-hedera commented on hedera-mirror-rest/service/contractService.js
> +    })[0];
should use `super.singleRow` because consensus_timestamp and emtpty_id are the composite primary key.

in addition, with `getRows` when no result found, empty array is returned and the function would then return undefined

2023-11-09 16:09 UTC, jnels124 commented on hedera-mirror-rest/service/contractService.js
> +    })[0];
will update. With this method Intention was to return undefined if no result found.

2023-11-09 21:25 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_contract_lookup_tables.sql
> +     group by cr.contract_id, cr.consensus_timestamp, cr.payer_account_id);
they were 12 minutes per query. It has been updated and the new query does the same work in ~12 minutes

2023-11-09 21:35 UTC, xin-hedera submitted a review, later dismissed
LGTM

2023-11-09 21:36 UTC, steven-sheehy approved these changes

2023-11-13 17:17 UTC, jnels124 commented
V2 after
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| contractsIdResultsTimestamp | /contracts/{id}/results/{timestamp} | 1500 | 96.99 | 1603.20/s | 1554.94/s | 728.48ms | No | |
| contractsResultsId | /contracts/results/{id} | 1500 | 91.39 | 1385.90/s | 1266.57/s | 713.88ms | No | |

v1 after
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| contractsIdResultsTimestamp | /contracts/{id}/results/{timestamp} | 1500 | 99.53 | 2103.65/s | 2093.76/s | 700.12ms | No | |
| contractsResultsId | /contracts/results/{id} | 1500 | 99.14 | 1890.97/s | 1874.71/s | 755.48ms | No | |

v1 before
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| contractsIdResultsTimestamp | /contracts/{id}/results/{timestamp} | 1500 | 95.77 | 2073.40/s | 1985.70/s | 664.82ms | No | |
| contractsResultsId | /contracts/results/{id} | 1500 | 96.95 | 1821.59/s | 1766.03/s | 697.45ms | No | |

2023-11-13 17:42 UTC, xin-hedera approved these changes
LGTM

2023-11-13 19:13 UTC, steven-sheehy approved these changes

2023-11-13 19:43 UTC, merged