Add nested functions for eth_call & eth_estimateGas tests
hashgraph/hedera-mirror-node pull request #7085
Opened 2023-10-17 10:10 UTC by anastasiya-kovaliova

**Description**:
<!--
Adding the first 4 out of 8 functions. 
For each function add tests for eth_call and estimate_gas for both fungible and NFT tokens.
- add 4 contract nested functions
- add 8 tests for eth_call
- add 8 tests for estimate_gas

**Related issue(s)**:
#7018 
Fixes #

**Notes for reviewer**:
This is part 1 PR for for the first 4 functions. There will be a 2nd PR with the rest 4 functions.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-17 11:39 UTC, yiliev0 requested changes

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        networkTransactionResponse = tokenClient.associate(receiverAccountId, tokenId);
It would be shorter if we use the already existing `fungibleTokenId` and `nonFungibleTokenId`.
```suggestion
        tokenClient.associate(receiverAccountId, fungibleTokenId);
        networkTransactionResponse = tokenClient.associate(receiverAccountId, nonFungibleTokenId);
```

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(results.get(0) + metadata.length).isEqualTo(results.get(1));
metadata.length is always equal to 1, so we can get rid of the `var metadata` and replace it with +1 as above.
If we eliminate `metadata` variable, we can add inline `asByteArray(Arrays.asList("0x02"))` in the `encodeData` and simplify it.

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        totalSupplyOfToken = mirrorClient.getTokenInfo(fungibleTokenId.toString()).getTotalSupply().longValue();
Wouldn't it be better if we take out this into a separate function same as `getBalanceOfToken`?

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(results.get(0) - serialNumbers.length).isEqualTo(results.get(1));
Same as `var metadata` comment from above.

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(results.get(0) - serialNumbers.length).isEqualTo(results.get(1));
Same as `var metadata` comment from above.

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +import static com.hedera.mirror.test.e2e.acceptance.steps.CallFeature.ContractMethods.*;
The same comment from `CallFeature` for the wildcard imports.

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/call.feature
> +@contractbase @fullsuite @acceptance @web3 @call @setupEth_callFeature
We have the `@call` tag already is `@setupEth_callFeature` really needed?

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    @Then("I call estimate gas that mints 1 FUNGIBLE token and returns the total supply and balance of treasury")
nit: it would sound better in my opinion
```suggestion
    @Then("I call estimate gas that mints FUNGIBLE token and returns the total supply and balance of treasury")
```
Same applies for the test names below.

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimate gas that burns 1 NFT token and returns the total supply and balance of treasury
Do we really need to add it here, can we keep at the bottom with the rest of all new test cases?

2023-10-17 11:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/solidity/contracts/PrecompileTestContract.sol
> +        if (responseCode != HederaResponseCodes.SUCCESS) revert("Failed to retrieve token info before wipe");
Consider adding braces `{}` around the `revert` statement for better code readability and consistency with the rest of the functions in the contract. Comment applies for the same places below.

2023-10-24 07:27 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private static DeployedContract deployedPrecompileContract;
What is the difference between `private static DeployedContract deployedContract;` and  `private static DeployedContract deployedPrecompileContract;`

2023-10-24 07:28 UTC, attest08 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
>          deployedContract = getContract(PRECOMPILE);
Why do we need two constants for the same contracts? getContract(PRECOMPILE);

2023-10-24 08:42 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
>          deployedContract = getContract(PRECOMPILE);
great catch, I've commited a change to update it to be used in the way it is in the estimatePrecompile file

2023-10-24 08:43 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    private static DeployedContract deployedPrecompileContract;
just pushed a new commit to update it, good catch!

2023-10-25 02:54 UTC, steven-sheehy requested changes

2023-10-25 02:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(results.get(0) + 1L).isEqualTo(results.get(1));
We should assertThat the array size before accessing array elements to avoid index out of bounds. Same comment elsewhere.

2023-10-25 02:54 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(Integer.valueOf(statusAfterFreeze, 16)).isEqualTo(1);
Use the SDK proto enum then it is self documenting. Same comment elsewhere.

```suggestion
        assertThat(Integer.valueOf(statusAfterFreeze, 16)).isEqualTo(TokenPauseStatus.Paused.getNumber());
```

2023-10-25 09:28 UTC, yiliev0 requested changes

2023-10-25 09:28 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/call.feature
> +    And I associate FUNGIBLE token to receiver account
I receive this when running with the @acceptance tag. Can you check?
```
com.hedera.mirror.test.e2e.acceptance.client.NetworkException: Transaction was unsuccessful: TransactionReceipt{transactionId=0.0.1244@1698225265.463000000, status=TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT, exchangeRate=ExchangeRate{hbars=1, cents=12, expirationTime=2100-01-01T00:00:00Z, exchangeRateInCents=12.0}, accountId=null, fileId=null, contractId=null, topicId=null, tokenId=null, topicSequenceNumber=null, topicRunningHash=null, totalSupply=0, scheduleId=null, scheduledTransactionId=null, serials=[], duplicates=[], children=[]}
	at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.getTransactionReceipt(AbstractNetworkClient.java:152)
	at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:123)
	at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:131)
	at app//com.hedera.mirror.test.e2e.acceptance.client.TokenClient.associate(TokenClient.java:281)
	at app//com.hedera.mirror.test.e2e.acceptance.steps.CallFeature.associateFungibleTokenToReceiver(CallFeature.java:187)
	at ✽.I associate FUNGIBLE token to receiver account(classpath:features/contract/call.feature:30)
```

2023-10-25 09:28 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(asAddress(approvedAddress)).isEqualTo(asAddress(receiverAccountAlias));
`asAddress` usually is used when passing data for headlong encoding. You can achieve the same result by left padding the receiverAccountAlias with 0's using util.to32BytesString. Comment applies for the same places below.
```suggestion
        assertThat(approvedAddress).isEqualTo(to32BytesString(receiverAccountAlias));
```

2023-10-25 09:28 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +import static com.hedera.mirror.test.e2e.acceptance.steps.EstimatePrecompileFeature.ContractMethods.*;
Wildcard imports are not suggested.

2023-10-27 08:49 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(Integer.valueOf(statusAfterFreeze, 16)).isEqualTo(1);
Hey Steven, for most of these enums we have 3 enum values - for the case of pause, those are `PAUSED`, `UNPAUSED`, `NOT_APPLICABLE` with 3 different enum indexes.

The precompile however works with boolean values and we expect one of two values - `true` for `PAUSED` and `false` for `UNPAUSED` and `NOT_APPLICABLE`.

I believe it's better to check the returned values following users perspective and expect only `true` or `false` values.

2023-10-27 23:02 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(Integer.valueOf(statusAfterFreeze, 16)).isEqualTo(1);
Ok, bad assumption on my part.

2023-10-30 08:05 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +    ;
good catch! I've removed it.

2023-10-30 08:06 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/ContractCallResponse.java
> +        return results;
Great idea! I've updated it.

2023-10-30 08:07 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/features/contract/call.feature
> +@contractbase @fullsuite @acceptance @web3 @call @setupEth_callFeature
Removed it

2023-10-30 08:08 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/features/contract/call.feature
> -  Scenario Outline: Validate eth_call
It is being constantly underlined with a warning, that there is no Examples section added, but I've returned it back

2023-10-30 08:11 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +                .getAccountDetailsByAccountId(accountId)
This is an even more easi-to-use function, thank you! Updated and used it!

2023-10-30 15:02 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        var allowedAfter = results.substring(130);
Great idea! I've updated the helper method and added one more in the same file and one util method as well.

2023-10-30 15:02 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    // ETHCALL-072
Good idea, I've removed them!

2023-10-30 15:03 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        assertThat(results.get(0) + 1L).isEqualTo(results.get(1));
Great idea! I've added the check in all places!

2023-10-30 15:03 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        tokenClient.associate(deployedPrecompileContract.contractId(), nonFungibleTokenId);
Good catch! I've added it.

2023-10-30 15:04 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +import static com.hedera.mirror.test.e2e.acceptance.steps.EstimatePrecompileFeature.ContractMethods.*;
Good catch, I've updated them.

2023-10-30 15:05 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    #Then I call estimate gas that associates NFT token dissociates and fails token transfer
yes, this check is failing due to the issue, will uncomment it right after the issue is fixed. Devs are working on it atm.

2023-10-30 15:05 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/contracts/PrecompileTestContract.sol
> +    function approveNftTransferFromGetAllowanceGetBalance(address token, address spender, uint256 serialNumber) external
Great idea! I've updated the names!

2023-10-30 15:05 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/contracts/PrecompileTestContract.sol
> +    function approveFungibleTokenTransferFromGetAllowanceGetBalance(address token, address spender, uint256 amount) external
That's way more readable now! I've updated the names as suggested!

2023-10-30 15:06 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/contracts/PrecompileTestContract.sol
> +    function pauseTokenGetPauseStatusUnpauseGetPauseStatus(address token) external
That's way more readable now! I've updated the names as suggested!

2023-10-30 15:06 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/contracts/PrecompileTestContract.sol
> +    function freezeTokenGetFreezeStatusUnfreezeGetFreezeStatus(address token, address account) external
That's way more readable now! I've updated the names as suggested!

2023-10-30 15:06 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimate gas that approves NFT token gets approved transfer from gets ownership gets approval
That's way more readable now! I've updated the names as suggested!

2023-10-30 21:30 UTC, anastasiya-kovaliova commented
The branch is a mess now, I'm adding a new PR with a clean branch,All comments are addressesd in the new PR.
This is the link for the new PR: https://github.com/hashgraph/hedera-mirror-node/pull/7138

2023-10-30 21:30 UTC, closed without merging

2023-10-30 21:31 UTC, anastasiya-kovaliova commented
This is the link for the new PR: https://github.com/hashgraph/hedera-mirror-node/pull/7138