Update balances consensus timestamp query
hashgraph/hedera-mirror-node pull request #7087
Opened 2023-10-17 14:17 UTC by edwin-greene

Update the balances consensus timestamp query to include an account_id. This increases performance as the account id is the first value of the composite primary key from https://github.com/hashgraph/hedera-mirror-node/issues/3507.

**Related issue(s)**:

Fixes #6936 

**Notes for reviewer**:
K6 test results on Citus: 
```
balances_with_timestamp ↓ [ 100% ] 1500 VUs  1m30s

     ✗ Balances with timestamp OK
      ↳  87% — ✓ 32468 / ✗ 4736

     █ setup

   ✗ checks.........................: 87.27% ✓ 32468      ✗ 4736
     data_received..................: 288 MB 3.1 MB/s
     data_sent......................: 5.4 MB 58 kB/s
     http_req_blocked...............: avg=3.53ms   min=296.31µs med=2.13ms   max=87.9ms  p(90)=6.43ms   p(95)=7.55ms
     http_req_connecting............: avg=3.45ms   min=252.39µs med=2.07ms   max=83.48ms p(90)=6.35ms   p(95)=7.47ms
   ✗ http_req_duration..............: avg=3.69s    min=30.15ms  med=519.22ms max=29.51s  p(90)=12.11s   p(95)=15.44s
       { expected_response:true }...: avg=2.97s    min=30.15ms  med=262.78ms max=29.51s  p(90)=10.97s   p(95)=13.84s
     http_req_failed................: 12.72% ✓ 4736       ✗ 32468
     http_req_receiving.............: avg=121.21µs min=36.63µs  med=106.35µs max=15.75ms p(90)=172.06µs p(95)=195.44µs
     http_req_sending...............: avg=153.76µs min=11.48µs  med=54.88µs  max=69.53ms p(90)=103.36µs p(95)=139.02µs
     http_req_tls_handshaking.......: avg=0s       min=0s       med=0s       max=0s      p(90)=0s       p(95)=0s
     http_req_waiting...............: avg=3.69s    min=29.95ms  med=519.08ms max=29.51s  p(90)=12.11s   p(95)=15.44s
     http_reqs......................: 37204  395.371357/s
     iteration_duration.............: avg=3.7s     min=269.39µs med=524.79ms max=29.51s  p(90)=12.11s   p(95)=15.44s
     iterations.....................: 37204  395.371357/s
     vus............................: 113    min=113      max=1500
     vus_max........................: 1500   min=1500     max=1500

running (1m34.1s), 0000/1500 VUs, 37204 complete and 0 interrupted iterations
balances_with_timestamp ✓ [ 100% ] 1500 VUs  1m30s
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-10-17 17:10 UTC, jnels124 requested changes

2023-10-17 17:10 UTC, jnels124 commented on hedera-mirror-rest/balances.js
> +    tsParams.push('2');
Need to make sure the account id isn't already provided on the request. Maybe best to move logic into the get balance method?

2023-10-17 17:40 UTC, jnels124 commented on hedera-mirror-rest/balances.js
> +    tsParams.push('2');
Actually this may be more of a problem. We may not even be able to add this hint here. Reason is we need to be able to return account balances for all accounts.

2023-10-18 16:20 UTC, xin-hedera requested changes

2023-10-18 16:20 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  }
`tsQuery` built by the caller shouldn't have any `account_id = ` query.
  
```suggestion
  // Add the treasury account to the query as it will always be in the balance snapshot and account_id is the primary key of the table thus it will speed up queries on v2
  tsQuery = tsQuery ? tsQuery.concat(' and account_id = ?') : ' account_id = ?';
  tsParams.push('2');
```

2023-10-18 16:21 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    tsParams.push('2');
`tsQuery` passed in from the caller shouldn't have any `account_id = ` query

2023-10-18 21:47 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +    tsParams.push('2');
Thanks I have updated this and removed the check.

2023-10-18 21:47 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  }
Got it, I have removed the if statement

2023-10-19 15:42 UTC, xin-hedera requested changes

2023-10-19 15:42 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +      tsParams = [lowerPartitionBound, upperBound, lowerPartitionBound, upperBound];
let's not implement queries assuming account balance is deduped before the ingestion side is complete and data is populated.

There is an issue for deleted accounts with full account balance snapshot v.s. with deduped account balance snapshot:

- for full account balance snapshot, once an account is deleted, its balance info disappears from any account balance file after that, so the balances query would simply not return balance info for the account when the timestamp is after the deletion
- for deduped account balance snapshot, the historical balance service should have one last row for the account with 0 balance after its deletion, the modified query would then return 0 balance for the account, that's good

However, the problem arises when we use the modified query with full account balance snapshot, since then the balances API will show the last balance of those deleted accounts.

I don't think there is a way to use the same query for both types of account balance info, besides the `distinct on ... order by ..., ... desc limit 1` also has performance impact. We may end up with two sets of different queries and add a property to rest api configuration to switch between.

2023-10-27 21:25 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +      tsParams = [lowerPartitionBound, upperBound, lowerPartitionBound, upperBound];
Thanks. I have added a configuration for deduplicate and added back the original queries for non-deduplicated data.

2023-10-31 14:26 UTC, jnels124 requested changes
Looks like the schema in the db doesn't match what is in our migration files. Please update the index init migration to update the order of the index.

2023-10-31 14:26 UTC, jnels124 commented on hedera-mirror-rest/balances.js
> +    consensusTsQuery = `ab.consensus_timestamp >= ? and ab.consensus_timestamp <= ?`;
Doesn't this miss if the user was to query for a specific timestamp and not provide an account query? Need to be able to handle gt,lt, etc

2023-10-31 14:29 UTC, jnels124 commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
This still potentially scans multiple partitions. Couldn't we just roll/roll-truncate the input to stay in the correct partition?

2023-10-31 16:47 UTC, jascks commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
Are you saying that since `NS_IN_MONTH` represents 31 days, depending on where `upperBound` falls in the month/partition, subtracting 31 days could involve up to three partitions, if the previous partition represents a month of less than 31 days?

What is the "correct partition"? I realize the fewer partitions accessed the better, but is there some heuristic to develop like if day of month is > 25, then truncate to start of month and involve only a single partition, else generate a query that would access two partitions?

Then for, say, `upperBound` defined somewhere in March 1, subtracting 31 days would hit January, or a three partition query. Truncation here would drop January and just utilize two partitions?

If this is the case, then this code would be useful outside of this file. I know I would use it. 😄

2023-10-31 17:19 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
then we'll need a library to handle natural month, since a month can have 28/29/30/31 days, with that, the boundary should exactly match the partitions in db.

2023-10-31 18:01 UTC, jnels124 commented on hedera-mirror-rest/balances.js
> +      order by ab.account_id ${order}, ab.consensus_timestamp desc
this should use the order passed as a param

2023-10-31 18:30 UTC, jascks commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
Hopefully one without 15 transitive dependencies of its own. 😄 It looks like the built in `Date` can be given a Unix epoch time, and be used to return the month and full year. It's only February that changes between 28 and 29 days, the rest are fixed at either 30 or 31. So, we could just define an array to look things up based on the month number, unless it's 1 (zero based February), in which case if the full year is divisible by 4 then use 29 else 28.

That would tied us over until 2100, which is not a leap year because it's divisible by 100. 😄

2023-10-31 18:45 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
yeah. there's more work if we want to query the partition metadata. fun fact is the partition boundary is stored in `pg_class.relpartbound` and in a (perhaps binary) format internal to postgres. `pg_get_expr(relpartbound, oid)` will resolve it into a human-readable string like `for values from ('xxx') to ('xxx')`

So to retrieve and cache partition metadata in the js rest module, we'll have to re-implement the `TimePartitionService` in importer...

2023-10-31 19:57 UTC, jascks commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
Oh, that's too bad, but good to know. I was trying to find a utility function that would help with this. Something akin to:
```
mirror_node=> SELECT get_shard_id_for_distribution_column('transaction', 1833905);
 get_shard_id_for_distribution_column
--------------------------------------
                               102599
(1 row)
```

Given literal values for the partition key, Citus is able to limit the partitions accessed:

```
                                               ->  Merge Append  (cost=0.85..6778.96 rows=278 width=8) (actual time=1.295..14.744 rows=25 loops=1)
                                                     Sort Key: t_2.consensus_timestamp DESC
                                                     ->  Index Scan Backward using transaction_p2023_03_pkey_112792 on transaction_p2023_03_112792 t_2_1  (cost=0.42..5604.33 rows=275 width=8) (actual time=1.257..11.985 rows=22 loops=1)
                                                           Index Cond: ((consensus_timestamp >= '1678818548505133688'::bigint) AND (consensus_timestamp <= '1680908778141046768'::bigint) AND (payer_account_id = 1833905))
                                                           Filter: ((nonce = 0) OR (parent_consensus_timestamp IS NOT NULL))
                                                     ->  Index Scan Backward using transaction_p2023_04_pkey_112808 on transaction_p2023_04_112808 t_2_2  (cost=0.42..1171.83 rows=3 width=8) (actual time=0.038..2.751 rows=3 loops=1)
                                                           Index Cond: ((consensus_timestamp >= '1678818548505133688'::bigint) AND (consensus_timestamp <= '1680908778141046768'::bigint) AND (payer_account_id = 1833905))
                                                           Filter: ((nonce = 0) OR (parent_consensus_timestamp IS NOT NULL))
```
I'm not sure how those indexes got named (some other shard ID?), but that partition portion comports with the Citus `time_partitions` table:
```
       parent_table       |  partition_column   |             partition             |     from_value      |      to_value       | access_method
--------------------------+---------------------+-----------------------------------+---------------------+---------------------+---------------
 transaction              | consensus_timestamp | transaction_p2023_03              | 1677628800000000000 | 1680307200000000000 | heap
 transaction              | consensus_timestamp | transaction_p2023_04              | 1680307200000000000 | 1682899200000000000 | heap
```
Maybe we can leverage that in some manner?

2023-10-31 20:05 UTC, jascks commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
One last thing before I switch to another PR; In `time_partitions` above, `from_value` and `to_value` are the actual boundary values for the partition, not the current lowest and highest values present.

2023-11-01 15:50 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
`time_partitions` is a view provided by citus so in v1 (vanilla postgresl) we have to craft the query and parse the partition boundary by ourselves.

2023-11-01 20:38 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +    let oneMonthTimestamp = math.subtract(upperBound, NS_IN_MONTH);
Thanks, I have updated this with a utility method to get the first millisecond of a month.

2023-11-01 20:40 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +    consensusTsQuery = `ab.consensus_timestamp >= ? and ab.consensus_timestamp <= ?`;
Thanks, I have added a spec test for this in `deduplicate-balances.json`.

2023-11-01 20:43 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +
This now gets the partition bounds no matter if an accountQuery was received; tests for this have been added to `deduplcate-balances.json` which now has timestamps at the beginning and end of a month and also tests the balances with a timestamp and balances with accounts and timestamp.

2023-11-01 20:46 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/deduplicated-balances.json
> +        "timestamp": 1564617600000000000,
This is the beginning of a month, August 1, 2019 12:00:00 AM

2023-11-01 20:47 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/deduplicated-balances.json
> +        "timestamp": 1564618500000000000,
Fifteen minutes later, August 1, 2019 12:15:00 AM

2023-11-01 20:47 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/deduplicated-balances.json
> +        "timestamp": 1567295999000000000,
The end of the month, August 31, 2019 11:59:59 PM

2023-11-01 20:48 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/deduplicated-balances.json
> +      ],
The beginning of the next month, September 1, 2019 12:00:00 AM

2023-11-02 15:14 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +  return secMsToNs(firstDayMs);
There is some loss of precision here with the conversion of nanoseconds to milliseconds, as to get a Date object in Javascript a timestamp in milliseconds is required.

2023-11-02 16:06 UTC, jnels124 requested changes

2023-11-02 16:06 UTC, jnels124 commented on hedera-mirror-rest/__tests__/specs/balances/deduplicated-balances.json
> +  "description": "Balances api call with deduplicated account balances",
maybe should have a test case where user is providing both bounds?
`/api/v1/balances?account.id=gte:0.1.16&account.id=lt:0.1.21&timestamp=lt:1567295999.000000000&timestamp=gt:1564617600.000000000`

2023-11-02 21:46 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +    consensusTsQuery = `ab.consensus_timestamp >= ? and ab.consensus_timestamp <= ?`;
Further investigation has found that this is still a problem concerning the gt/lt operators. Working on a fix.

2023-11-03 14:39 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  const upperBound = tsParams[0];
Thanks I have added a method to get the partition bounds from the tsQuery.

2023-11-03 14:39 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/balances/deduplicated-balances.json
> +  "description": "Balances api call with deduplicated account balances",
Thanks! I have added this test and a fix so that it should now provide the correct results.

2023-11-06 15:23 UTC, jnels124 commented on hedera-mirror-rest/balances.js
> +      upperBound = upperBound < tsParams[index] ? tsParams[index] : upperBound;
shouldn't this logic be inversed? If we have two lte, shouldn't the upper bound be the minimum of the two?

2023-11-06 17:40 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +      upperBound = upperBound < tsParams[index] ? tsParams[index] : upperBound;
Sounds good, I have implemented the fix. The upperBound will now be the minimum of the lt/lte parameters and the lowerBound will be based off of the greatest of the gt/gte parameters.

2023-11-08 22:40 UTC, xin-hedera requested changes

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  let gteParam = 0;
both need to be `bigint`, timestamp in nanos precision isn't going to be a safe number

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    // eq operator has already been converted to the lte operator
should have a `const paramValue = BigInt(tsParams[index])` to avoid repeating `tsParams[index]`

can also rename the arrow function param name from `(value , index)` to `(query, index)` then can assign `tsParams[index]` to a variable `value` which is more straightfoward

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    }
please convert all the math operations into `BigInt` (not `math.bignumber`)

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  const minTimestamp = gteParam !== 0 ? gteParam : upperBound;
can't use `upperBound` as `minTimestamp` if not provided by user. I can send a query `/balances?timestamp=lte:year 3000`, the api will then return an empty list, because, there is simply no partition for year 3000 at year 2023.

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  if (upperBound === Number.MAX_VALUE) {
unsafe use of `Number`

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return math.divide(math.bignumber(secNs), math.bignumber(1e6)).toString();
prefer `BigInt` over math.bignumber functions

2023-11-08 22:40 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const secMsToNs = (secMs) => {
`seMsToNs` and `secNsToMs` do not seem to really usable as their own functions

They are only used in `getFirstDayOfMonth` and directly multiple / divide in `getFirstDayOfMonth` will be much simpler

2023-11-09 16:11 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  const minTimestamp = gteParam !== 0 ? gteParam : upperBound;
We should use current month as a reference timestamp for the range if no lower / upper bound is provided by the user, with consideration of the `order`.

- if order is `desc`
  - if upper bound's year and month is before the current month, use the begging of the month prior to the upper bound as the lower bound, i.e., suppose upper bound is in month X, the lower bound should be 00:00 of day one in month X - 1
  - otherwise, use the beginning of the month before current month as the lower bound. Reason is, the account balance partition for current month might be empty since the snapshots is generated by default every 15 minutes

- if order is `asc`, since we don't have running information of the first balance snapshot, I can't think of a way to optimize other than use the lower / upper bound provided by user as is

2023-11-09 16:13 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  const minTimestamp = gteParam !== 0 ? gteParam : upperBound;
using current month as reference is going to make it impossible to test certain query parameters in spec based integration test. so have to create a separate integration test without using spec files

2023-11-14 22:55 UTC, edwin-greene commented on docs/configuration.md
> +| `hedera.mirror.rest.query.deduplicateBalances`                     | false                   | Enables REST API queries for deduplicated balances
Sounds good I have removed the property and the areas in balances.js that were not deduplicate queries.

2023-11-14 22:55 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  let gteParam = 0;
Thanks I have updated it to `BigInt`.

2023-11-14 22:55 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +    // eq operator has already been converted to the lte operator
Sounds good I have made these refactorings.

2023-11-14 22:55 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +    }
Got it, I have updated everything to use `BigInt`.

2023-11-14 22:56 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  const minTimestamp = gteParam !== 0 ? gteParam : upperBound;
Thanks I have updated these sections and added a new test that is a non-spec test. The new test also has testcases for future timestamps and their expected behavior.

2023-11-14 22:56 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  if (upperBound === Number.MAX_VALUE) {
Thanks I have fixed this.

2023-11-14 22:57 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +  return math.divide(math.bignumber(secNs), math.bignumber(1e6)).toString();
I have updated it to use `BigInt`.

2023-11-14 22:57 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +const secMsToNs = (secMs) => {
Sounds good I have removed those methods.

2023-11-15 20:29 UTC, xin-hedera requested changes

2023-11-15 20:29 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  }
this is not what we discussed, as follows:

1. If both gt and lt are provided, we do nothing, use it as is
2. If there is only an upper bound, and the upper bound is in a month before the current month, we use `[beginning of the month upper bound is in, upper bound]`;  if upper bound is in the current or later month, we use `[beginning of the month before current month, upper bound]`
3. If there is only a lower bound, we set it to `max(lower bound, the beginning of the month before the current month)`

The major problem is lower bound is adjusted backwards. For instance, in the implementation, when there are both lower and upper bounds, `lowerBound` is set to the beginning of the month of `getParam`. Assume there is a query with `timestamp=gt:tomorrow&timestamp=lt:now`, obviously the effective timestamp range is empty so the api response should be empty. However the implementation will set `lowerBound` to `2023-11-01 00:00`, and return the last balance snapshot if there is one.

Similar issue in adjusting lowerBound when there is only lower bound from the http request. The proposed operation is `max`, however the implementation does `min`. Then the query with `timestamp=gt:tomorrow` will return balances from the latest snapshot, instead of an empty response.

Additional changes:

-  further shrink the timestamp range for case 1
- shortcut and return empty response if user provided lowerBound > upperBound

2023-11-15 20:29 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  const timestampMs = secNs / 1000000n;
make 10n ** 6n a constant

2023-11-15 22:47 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  const lowerBoundString = lowerBound.toString();
Thanks I have removed the strings.

2023-11-15 22:47 UTC, edwin-greene commented on hedera-mirror-rest/utils.js
> +  const timestampMs = secNs / 1000000n;
Got it, I have updated it to a constant.

2023-11-15 22:47 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +import {opsMap} from './utils';
Thanks! I have fixed that.

2023-11-15 22:48 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +const MAX_UPPER_BOUND = BigInt(Number.MAX_VALUE);
Sounds good I have moved it to constants.

2023-11-15 23:24 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  }
Thanks! I have updated this section and it should have those changes with the exception of the `further shrink the timestamp range for case 1`. I will look into that tomorrow.

2023-11-16 18:25 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +};
I have reached out to Nana to discuss.

2023-11-16 19:30 UTC, jnels124 commented on hedera-mirror-rest/accounts.js
> +};
spoke with nana and he is ok with the balance always being the latest within the specified range regardless of order. His only request was to make sure this was documented in the api docs

2023-11-17 00:52 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +};
thanks. let's switch back to use `balances.getAccountBalanceTimestamp`

2023-11-17 01:27 UTC, xin-hedera requested changes

2023-11-17 01:27 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +      if (query.includes(utils.opsMap.lte)) {
add a comment to explain why check `lte` before `lt`. same for `gte` and `gt`

2023-11-17 01:27 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +    throw new InvalidArgumentError('Invalid timestamp ranges: lt value is less than gt value');
wouldn't this break the endpoint's behavior? This is what's returned now

```
$ curl -s 'https://previewnet.mirrornode.hedera.com/api/v1/balances?timestamp=gt:1700183696&timestamp=lt:1700180000' | jq .
{
  "timestamp": null,
  "balances": [],
  "links": {
    "next": null
  }
}
```

2023-11-17 01:27 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +          ? // If the upper bound is in a month prior to the current month, the lower bound is the beginning of the month the upper bound is in
Let's change to: if the upper bound is in a month prior to the current month, the lower bound is the beginning of the month prior to the month the upper bound is in.

It's the same corner case than for instance when the upper bound is merely 1 minute into a month, there's most likely no balance snapshot in that 1 minute range, however, there's no to little chance with no balance snapshot in that 1 month + 1 minute range.

2023-11-17 01:27 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +      return getPartitionedTsQuery(lowerBound, neParams, upperBound);
nit, `getPartitionedTsQuery` is called three times. we can leave the `if ... else ...` block to figure out the upper bound and lower bound, and call `getPartitionedTsQuery` once at the end.

for `upperBound`, if it's not set, it's long max, so it's perfectly fine to just pass it to `getPartitionedTsQuery`, which means `getPartitionedTsQuery` no longer to check if `upperBound` set or not.

2023-11-17 03:54 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  const tokenBalanceSubQuery = getTokenBalanceSubQuery(order, consensusTsQuery);
since we need to change it back to the old 2-step flow, given `T1` is the balance snapshot timestamp found in the first step, for the second step, the timestamp query should be `consensus_timestamp >= T2 and consensus_timestamp <= T1` where `T2 = beginning of the month T1 is in`

2023-11-17 04:00 UTC, xin-hedera requested changes

2023-11-17 04:00 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> -    const balanceFileTs = await balances.getAccountBalanceTimestamp(
both account balance query and token balance query for `/accounts/{id}?timestamp=` are not updated to use the deduped balance table. the queries still get balance info from the table at exactly the balance snapshot timestamp, instead of the latest balance info in`[beginning of partition, balance snapshot timestamp]`

2023-11-17 21:56 UTC, xin-hedera requested changes

2023-11-17 21:56 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  const accountBalanceTimestamp = await getAccountBalanceTimestamp(accountBalanceQuery, [lowerBound, upperBound]);
`neQuery` needs to go into `getAccountBalanceTimestamp` instead of being added to `consensusTsQuery` and then passed to the main query.

Two reasons

- avoid the picked treasury account's balance snapshot timestamp matching any of the `ne` values
- suppose the picked treasury account's balance snapshot timestamp is `T1`, and ne value is `T2` (which is earlier than `T1`), if for an account `X`, the latest balance at or before `T1` is in snapshot at time `T2`, we *should* use it, instead of otherwise when the ne value `T2` is in the main query, account `X`'s balance at an even earlier timestamp `T3` is picked

2023-11-17 21:56 UTC, xin-hedera commented on hedera-mirror-rest/balances.js
> +  // Double the params to account for the query values for account_balance and token_balance together
remove the logic about `neQuery` here

2023-11-20 14:57 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  const accountBalanceTimestamp = await getAccountBalanceTimestamp(accountBalanceQuery, [lowerBound, upperBound]);
Thanks I have updated this.

2023-11-20 14:57 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +  // Double the params to account for the query values for account_balance and token_balance together
Sounds good, I have removed it.

2023-11-20 14:58 UTC, edwin-greene commented on hedera-mirror-rest/balances.js
> +      if (query.includes(utils.opsMap.lte)) {
Thanks I have updated the comment

2023-11-20 19:35 UTC, xin-hedera approved these changes
LGTM

2023-11-20 20:37 UTC, jnels124 approved these changes
LGTM

2023-11-20 20:41 UTC, merged