07045: Fix blockhash exception due to hash value not being sliced
hashgraph/hedera-mirror-node pull request #7091
Opened 2023-10-18 12:41 UTC by bilyana-gospodinova

**Description**:
This PR fixes the IllegalArgumentException ("Hex value is too large: expected at most 32 bytes but got 48") that is thrown when we call the blockhash function in a solidity contract. The exception is thrown in StaticBlockMetaSource#getBlockHash -> org.hyperledger.besu.datatypes.Hash::fromHexString. The cause for this is that the persisted hash values in the record files are of length 48 bytes but org.hyperledger.besu.datatypes.Hash::fromHexString expects the input to be of length 32 bytes. Following HIP-415 (https://hips.hedera.com/hip/hip-415) that was implemented in services the returned hash value from StaticBlockMetaSource#getBlockHash needs to be constructed from the first 32 prefix bytes of the hash.

In this PR some integration tests are added in order to cover some typical scenarios related to HIP-415 such as:
1. The block hash of the genesis block needs to be all zeroes.
2. The block hash of the current block needs to be all zeroes.
3. The block hash of the last 256 blocks (not including the current one) is the 32 byte prefix from the 48 byte hash.

In the integration tests the following changes were made:
- The persisted record file hash values are changed to be numeric in order to be parsable later as a hex.
- Preserve a record file in ContractCallTestSetup that is not in the latest block in order to get its index (block number) and test scenario 3.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/7045

2023-10-25 19:32 UTC, Nana-EC requested changes
Looks mostly good.
Unsure about the all zeros for latest block hash.

2023-10-25 19:32 UTC, Nana-EC commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashReturnsZero() {
Q: why should the latest block hash return 0's?
We have valid hashes for the latest block - https://testnet.mirrornode.hedera.com/api/v1/blocks?order=desc&limit=1

Is there a specific edge case you're going for?

2023-10-25 19:42 UTC, steven-sheehy requested changes

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .fileHash(numeric(96))
Please undo changes to the `DomainBuilder`. The intent of the `DomainBuilder` is to generate random data that matches the format of the real data as much as possible. The real hashes are random byte arrays not numeric. It's also a code smell to depend upon their values being numeric in a test so we really shouldn't rely on such an assumption.

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/BlockHashUtil.java
> +        return org.hyperledger.besu.datatypes.Hash.wrap(Bytes32.wrap(prefixBytes));
Doesn't this work?

```suggestion
        return Hash.fromHexString(StringUtils.substring(hash, 0, 64))
```

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/BlockHashUtil.java
> +    public static org.hyperledger.besu.datatypes.Hash ethHashFrom(final String hash) {
No need to use fully qualified package names.

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +        return BlockHashUtil.ethHashFrom(fileHash.orElseThrow(
Is the change from `map` necessary to not throw a certain exception type? If not, prefer older map approach.

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +        assertThat(subject.getBlockHash(1)).isEqualTo(expected);
```suggestion
        final var expected = Hash.fromHexString("0x37313862636664302d616365352d343861632d396430612d3639303631633765");
        assertThat(subject.getBlockHash(1)).isEqualTo(expected);
```

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +                        .toString());
No need for the util.
```suggestion
                .isEqualTo(recordFileForBlockHash.getHash().substring(0, 64));
```

2023-10-25 19:42 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/BlockHashUtil.java
I don't think one method warrants its own utility class, especially since it's not used outside of `StaticBlockMetaSource` and tests. I have provided suggestions to remove its use in tests while making them simpler.

2023-10-26 09:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashReturnsZero() {
Does the execution fall into this logic?

 // If the current block is the genesis block or the sought block is
    // not within the last 256 completed blocks, zero is returned.
    if (currentBlockNumber == 0
        || soughtBlock < (mostRecentBlockNumber - MAX_RELATIVE_BLOCK)
        || soughtBlock > mostRecentBlockNumber) {
      frame.pushStackItem(Bytes32.ZERO);

2023-10-26 10:52 UTC, bilyana-gospodinova commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .fileHash(numeric(96))
"The intent of the DomainBuilder is to generate random data that matches the format of the real data as much as possible" - I agree with that. However, when we pass in the DomainBuilder a random string, e.g. "xyz" it gets persisted in the DB as "xyz" so when we read this value later and try to parse it to get the Hash we get an exception as this is not a parseable hex string:
> Illegal character 'v' found at index 1 in hex binary representation
> com.hedera.mirror.web3.exception.MirrorEvmTransactionException: Illegal character 'v' found at index 1 in hex binary representation. 

This is why I modified the persisted file hashes to be numeric so that we can parse them later successfully. 

Instead of the numeric() method and in order to be able to generate values as close as possible to the real data I would suggest this method:
public String hash(int characters) {
    return RandomStringUtils.random(characters, "0123456789abcdef");
}

What do you think about that?

2023-10-26 11:13 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashReturnsZero() {
Yes, exactly.

2023-10-26 11:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/BlockHashUtil.java
> +        return org.hyperledger.besu.datatypes.Hash.wrap(Bytes32.wrap(prefixBytes));
It does. The change is addressed.

2023-10-26 11:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/BlockHashUtil.java
> +    public static org.hyperledger.besu.datatypes.Hash ethHashFrom(final String hash) {
The file was removed as suggested.

2023-10-26 11:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +        return BlockHashUtil.ethHashFrom(fileHash.orElseThrow(
The change is reverted.

2023-10-26 11:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSourceTest.java
> +        assertThat(subject.getBlockHash(1)).isEqualTo(expected);
Comment addressed.

2023-10-26 11:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +                        .toString());
Comment addressed.

2023-10-26 11:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/BlockHashUtil.java
The file was removed as suggested.

2023-10-26 12:47 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .fileHash(numeric(96))
That sounds reasonable.

2023-10-26 16:28 UTC, steven-sheehy approved these changes
LGTM

2023-10-26 16:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashReturnsZero() {
This seems like a bug when applied to Hedera then. Mirror nodes can return block hashes beyond the last 256 blocks and can return the block hash for the latest block since it's final. Here because of `long mostRecentBlockNumber = currentBlockNumber - 1` we're explicitly ignoring latest block even when the code loads the same values for `soughtBlock` and `currentBlockNumber`. Can we open a ticket to investigate?

2023-10-26 16:35 UTC, Nana-EC commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashReturnsZero() {
Agreed the 256 blocks is a design choice by EVM specs/Ethereum. Mirror Node is more capable so we may be able to support it or we can just match equivalence and not do the extra work.
Agreed with Steven @IvanKavaldzhiev  can we open a ticket to investigate this and decide

2023-10-26 16:38 UTC, Nana-EC approved these changes
LG
Let's follow up on that ticket around the 256 blocks consideration

2023-10-26 16:43 UTC, merged

2023-10-26 17:01 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashReturnsZero() {
Yes, definitely we should investigate this behaviour. Will open a ticket.