Remove generation of token history row when total supply changes for Mint/Wipe/Burn
hashgraph/hedera-mirror-node pull request #7095
Opened 2023-10-19 18:10 UTC by mgoelswirlds

**Description**:

Remove the creation of history rows when the `token.total_supply` column is adjusted for token mints, burns, or wipes. History rows are added for create, update, or delete operations on the token entity itself.

* Remove setting of timestamp range on above mentioned token operations.
* Add token history row check to existing tests.

**Related issue(s)**:

Fixes #6998

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-10-20 15:41 UTC, jascks submitted a review, later dismissed
LGTM

2023-10-20 19:11 UTC, xin-hedera requested changes

2023-10-24 16:39 UTC, xin-hedera requested changes

2023-10-24 16:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
more than one token updates with the same lower timestamp shouldn't happen

2023-10-24 17:30 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            return previous;
Will add the method. But the idea was to add history rows only for entity updates.As per the ticket` add history rows for create, update or delete operations on the token entity itself.` So did remove creation in other places.

2023-10-24 17:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            return previous;
paused or not is part of token's state, even though it's not done by token update tx. pause / unpause shouldn't be an often operation on tokens so we should change it back with history rows.

2023-10-24 18:02 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
ok.

2023-10-25 13:47 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractToken.java
> +        if (newTotalSupply != null && this.totalSupply != null) {
what if totalSupply is null and newTotalSupply is not null?

2023-10-25 13:48 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        // Create does not have a history row
create definitely has timestamp range set

2023-10-25 13:49 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                        t.tokenId(tokenCreate.getTokenId()).timestampRange(null).totalSupply(-5_000L))
why mint will end up with a negative total supply?

2023-10-25 13:50 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                        .supplyType(TokenSupplyTypeEnum.FINITE)
token's supply type is immutable

2023-10-25 13:51 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    void onTokenMergeWithCreateThenMintThenUpdate() {
this should be a parameterized test, take a look at `onCryptoAllowanceHistory`

2023-10-25 14:00 UTC, xin-hedera commented
There is one more `setTimestampLower` to remove: https://github.com/hashgraph/hedera-mirror-node/blob/5eb770b61265920463508fd39e7aadaff40cee9b/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java#L397C17-L397C30

2023-10-25 15:11 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        // Create does not have a history row
misunderstood the comment, thought it meant token create has not timestamp range set

2023-10-25 16:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
>          }
should replace these with `updateTotalSupply` since now the logic is encapsulated, might be good to also copy the comment here to the new function

2023-10-25 17:34 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
>          }
The logic is a little different. Because the negative balance check is for the destination here where as the equivalent check is for the source. But I think the one in the method needs to match this right?

2023-10-25 18:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
>          }
if you replace these with `dest.updateTotalSupply(src.getTotalSupply())` it's the exact same logic, right?

2023-10-25 18:57 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
>          }
I did replace it , when I realized that the difference is of the totalSupply amount being checked for a negative value.
In the method we are checking for newTotalSupply which is equivalent to srcTotalSupply and in the other case we are checking for destTotalSupply to be negative. So I believe the check should be for src value in both the places and not destination. Does that seem right?

2023-10-26 02:18 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
>          }
to simplify the question in the above method what happens if we have a negative totalSupply?

2023-10-26 18:29 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> -        expected.setTotalSupply(expected.getTotalSupply() - 10);
@xin-hedera This is the case I was talking about. the negative balance is ignored because we don't check for the totalSupply value.

2023-10-27 20:42 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (!previous.hasHistory() && current.hasHistory()) {
There actually is a test case for this but it still complains of partial coverage.

2023-10-28 03:42 UTC, steven-sheehy requested changes

2023-10-28 03:42 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        var dest = previous.hasHistory() ? current : previous;
This is dead code since you've already ruled out previous not having history above. This logic can only run when both previous and current are regular updates. Can remove dest/src in favor of using more straightforward previous/current. Basically revert the bottom part of the original method to how it was before except using updateTotalSupply.

```suggestion
```

2023-10-28 03:42 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractToken.java
> +    public void updateTotalSupply(Long newTotalSupply) {
Would prefer an overloaded `setTotalSupply` unless that causes issues.

2023-10-31 16:22 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (!previous.hasHistory() && current.hasHistory()) {
it's partial coverage because not all 4 combinations were tested. not requesting changes in test cases though, just want to clarify.

2023-10-31 16:36 UTC, xin-hedera requested changes

2023-10-31 16:36 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/token/AbstractTokenTest.java
> +            1200,-500, 700
add one more test data `, -500, -500`

2023-10-31 18:33 UTC, xin-hedera approved these changes
LGTM for all the changes I requested.

2023-10-31 21:19 UTC, jascks approved these changes
Can't speak to any outstanding requested changes/comments, but otherwise this PR looks good based on the description and my own similar experience in the past.

2023-10-31 21:23 UTC, steven-sheehy approved these changes
LGTM

2023-10-31 21:50 UTC, merged