HIP-584: Historical support: Extend nft, nft allowance and token account DB queries to filter by timestamp
hashgraph/hedera-mirror-node pull request #7096
Opened 2023-10-20 08:23 UTC by bilyana-gospodinova

**Description**:
For historical support we need to extend db queries to have a timestamp filter.
Using this filter we can obtain records based on a historical block passed in eth_call.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/7052

**Checklist**
- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-10-24 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
n.deleted is false -> n.deleted is not true

2023-10-24 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
n.deleted is false -> n.deleted is not true

2023-10-24 22:05 UTC, steven-sheehy requested changes

2023-10-24 22:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                            and token_id = :#{#id.tokenId}
Don't use reflection based SPEL.

2023-10-24 22:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                        from token_account
Not sure of the use case, but probably you also want to return it if it's associated at the time since consensus nodes don't really keep dissociated token relationships? Or will you check that in memory?

2023-10-24 22:05 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
It's trickier since you would also need to check entity_history since it might be deleted now, but not at the block timestamp.

2023-10-25 14:28 UTC, xin-hedera requested changes

2023-10-25 14:28 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +            value = "( "
can you change it to use java text block?

2023-10-25 14:28 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
we can change it to `(e.deleted is not true or (lower(e.timestamp_range) > :blockTimestamp)` since lower(e.timestamp_range) is when the nft collection is deleted.

2023-10-25 14:28 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "left join entity_history e on e.id = n.token_id "
remove the `entity_history` join. a nft_history row can only correlate with its entity row by nft_history.timestamp_range, which means, a nft history row can span over multiple nft collection entity rows.

2023-10-25 14:28 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "limit 1 ",
instead of join `entity` / `entity_history` in the subqueries to check if the collection is deleted, we should join in the outer query, sth like

```
select n.*
from (
  (nft table subquery)
  union all
  (nft_history table subquery)
) as n
join entity e on e.id = n.token_id
where e.deleted is not true or lower(e.timestamp_range) > :blockTimestamp
order by n.timestamp_range desc
limit 1
```

2023-10-26 13:24 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "limit 1 ",
Would you please explain this part: "or lower(e.timestamp_range) > :blockTimestamp"? Why do we need that?

2023-10-26 14:46 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "limit 1 ",
if an entity is deleted, only in the `entity` table, `deleted = true`, and `lower(entity.timestamp_range` is when it's deleted, so `e.deleted is not true or lower(e.timestamp_range) > :blockTimestamp`

- if the entity is not deleted
- or (implicitly it's deleted) it's deleted after blockTimestamp

2023-10-27 06:38 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "limit 1 ",
Oh, I get it now. Thank you, I will update the query as suggested.

2023-11-13 09:50 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
Comment addressed

2023-11-13 09:50 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
Comment addressed

2023-11-13 09:51 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +                            and spender = :#{#id.spender}
Comment addressed

2023-11-13 09:51 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                            and token_id = :#{#id.tokenId}
Comment addressed

2023-11-13 09:53 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                        from token_account
Will check dissociated in memory, for current data we are filtering out dissociated in memory.

![image](https://github.com/hashgraph/hedera-mirror-node/assets/138600514/98ebec64-615c-4267-b170-47e23d091347)

2023-11-13 09:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "and n.deleted is false and e.deleted is not true "
Applied the (e.deleted is not true or (lower(e.timestamp_range) > :blockTimestamp) suggestion.

2023-11-13 09:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +            value = "( "
Comment addressed

2023-11-13 09:55 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "left join entity_history e on e.id = n.token_id "
Removed the entity history check and applied what you suggested below.

2023-11-13 09:56 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    + "limit 1 ",
Applied the suggested change above. Please check the refactored query

2023-11-13 11:24 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                        from token_account
Hm now that I think about this.
Considering the scenario where the closest token account to the timestamp is dissociated, while the previous one remains associated, the current in-memory filtering might not be effective for historical data, as it's designed for latest data. Moving the 'associated is true' condition into the SQL query, instead of applying it in memory as in the snippet, would ensure we fetch the nearest associated token account to the block timestamp. What do you think about this?

2023-11-17 17:20 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +     * @return an Optional containing the nft allowance's state at the specified timestamp.
nit, it returns a list

2023-11-20 12:28 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                        from token_account
I agree with the last comment, I believe we should not check association in sql, and simply apply the filter as in the above screenshot. No new changes were added to the code after this comment.

2023-11-20 12:40 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +     * @return an Optional containing the nft allowance's state at the specified timestamp.
Comment addressed

2023-11-20 18:47 UTC, xin-hedera approved these changes
LGTM

2023-11-20 20:31 UTC, steven-sheehy approved these changes
LGTM

2023-11-20 20:32 UTC, merged