Extend tests for estimateGas with contract transaction execution
hashgraph/hedera-mirror-node pull request #7098
Opened 2023-10-20 14:05 UTC by yiliev0

**Description**: This PR introduces additional tests to validate the estimateGas functionality provided by the `/api/v1/call` endpoint. The new tests retrieve the estimated gas for a specified operation, then execute the identical transaction through the consensus node with the acquired gas limit, ensuring accurate gas estimations for successful transaction processing. 

**Related issue(s)**:

Fixes #7086

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-23 22:37 UTC, steven-sheehy requested changes

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private void verifySuccessfulTransaction(ExecuteContractResult contractResult) {
This method seems to duplicate the functionality of the existing `verifyMirrorTransactionsResponse()` and can be deleted since `executeContractTransaction()` already calls `verifyMirrorTransactionsResponse()`.

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +
Getting the below error when running this branch against previewnet. Can you check?

```
    2023-10-23T22:02:47.654Z ERROR ForkJoinPool-1-worker-4 c.h.m.t.e.a.s.CallFeature Scenario failure: 
    I ensure token "NFT" has been created
    I ensure token "FUNGIBLE" has been created
    I successfully create ERC contract
    I successfully create Precompile contract
    I successfully create EstimateGas contract
    the mirror node REST API should return status 200 for the estimate contract transaction <- Cannot invoke "com.hedera.mirror.test.e2e.acceptance.response.NetworkTransactionResponse.getTransactionIdStringNoCheckSum()" because "this.networkTransactionResponse" is null
    I call function with IERC721Metadata token "NFT" name
    I call function with IERC721Metadata token "NFT" symbol
    I call function with IERC721Metadata token "NFT" totalSupply
    I call function with IERC721 token "NFT" balanceOf owner
    I call function with HederaTokenService isToken token "FUNGIBLE"
    I call function with HederaTokenService isFrozen token "FUNGIBLE", account
    I call function with HederaTokenService isKyc token "FUNGIBLE", account
    I call function with HederaTokenService getTokenDefaultFreezeStatus token "FUNGIBLE"
    I call function with HederaTokenService getTokenDefaultKycStatus token "FUNGIBLE"
    I call function with update and I expect return of the updated value
    I call function that makes N times state update
    I call function with nested deploy using create function
    I call function with nested deploy using create2 function
    I call function with transfer that returns the balance
     java.lang.NullPointerException: Cannot invoke "com.hedera.mirror.test.e2e.acceptance.response.NetworkTransactionResponse.getTransactionIdStringNoCheckSum()" because "this.networkTransactionResponse" is null
        at com.hedera.mirror.test.e2e.acceptance.steps.AbstractFeature.verifyMirrorTransactionsResponse(AbstractFeature.java:90)
        at com.hedera.mirror.test.e2e.acceptance.steps.CallFeature.verifyMirrorAPIResponses(CallFeature.java:90)
        at ✽.the mirror node REST API should return status 200 for the estimate contract transaction(classpath:features/contract/call.feature:10)
```

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimate.feature
>      Then I call estimateGas with IERC20 token approve using evm address as receiver
This file does not have `@acceptance` so isn't getting ran in any environment. Can we test and add?

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimateGas with balanceOf function for fungible token and execute it using gas limit
There's no indication that these are executing against HAPI or use `ContractCallTransaction`. Same comment for others.

```suggestion
    Then I call estimateGas with balanceOf function for fungible token and verify the estimated gas against HAPI
```

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimateGas with balanceOf function for NFT and execute it with gas limit
It's inefficient to call mirror contract/call with the same inputs twice. We should move the pre-existing calls from above that these mirror down here so they only get executed once and verify both gas range and against HAPI.

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                .addAddress(receiverAccountAlias);
A form of code duplication in generating contract data.. We should find a way to not have to encode the same data twice just because we're invoking MAPI and HAPI separately. Can we use `ContractFunctionParameters` to generate input to mirror contract/call or vice versa?

2023-10-23 22:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public void updateAccountAndTokenKeys() throws PrecheckStatusException, TimeoutException, ReceiptStatusException {
Why do we need all these updates?

2023-10-24 07:30 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public void executeBalanceOfFunctionNonFungibleWithLimitedGas() {
We can extract the logic inside

I call estimateGas with balanceOf function for fungible token and execute it using gas limit
and
I call estimateGas with balanceOf function for NFT and execute it with gas limit

in a common method, since the only difference is the token address.

2023-10-24 18:05 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public void executeBalanceOfFunctionNonFungibleWithLimitedGas() {
Extracted the logic into a common method as suggested. Thanks.

2023-10-24 18:06 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    private void verifySuccessfulTransaction(ExecuteContractResult contractResult) {
Removed. In fact, we can just use the `verifyMirrorTransactionsResponse()` inside `executeContractTransaction` and it would do the same thing. Thanks!

2023-10-24 18:14 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +
I found the problem. The problem originates when the tests are run parallel. So the `networkTransactionResponse` never gets populated because the singleton method for the contract creation does not invoke the creation itself, but the already stored contract in the mapper, thus leaving us without a transaction and a `networkTransactionResponse`. The solution I found is that we can change the order of the `Given` methods and leave the token creation at last.  In the following method:

```
@Given("I ensure token {token} has been created")
    public void createNamedToken(TokenNameEnum tokenName) {
        var tokenAndResponse = tokenClient.getToken(tokenName);
        if (tokenAndResponse.response() != null) {
            this.networkTransactionResponse = tokenAndResponse.response();
            verifyMirrorTransactionsResponse(mirrorClient, 200);
        }
   }
```
We have the verifyMirrorTransactionsResponse in this method which would be executed after the contract creation. So in both cases -> running it individually or in parallel(@acceptance) we secure that we have networkTransactionResponse and all the transactions are verified.

2023-10-24 18:15 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimate.feature
>      Then I call estimateGas with IERC20 token approve using evm address as receiver
I guess we missed it from the begging. I've added it now and tested running the tests with the @acceptance tag. It seems all are working fine together.

2023-10-24 18:16 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimateGas with balanceOf function for fungible token and execute it using gas limit
I've changed the names of the tests so they are more descriptive. Thanks for suggestion!

2023-10-24 18:18 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
> +    Then I call estimateGas with balanceOf function for NFT and execute it with gas limit
I have moved the identical calls/tests that check the gas within the range at the bottom. So now we make only 1 call against the mirror node for the gas estimation, verify that it's correct and use it afterwards for the `executeContractTransaction`

2023-10-24 18:20 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public void updateAccountAndTokenKeys() throws PrecheckStatusException, TimeoutException, ReceiptStatusException {
These updates are needed for the contract transaction execution when we attempt to do mints&transfers. After the v2 security changes, if we attempt to execute it without the account and token keys update, we get `NVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE`.

2023-10-24 18:26 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                .addAddress(receiverAccountAlias);
I've attempted initially to find a solution to combine these two, however, I couldn't find a way to make it happen. Тhe data that we encode with `headlong` and `ContractFunctionParamets` are the same but these two are working/constructed differently and not interchangeable. I looked for any util methods but I couldn't find any suitable any that would help us for our case.

2023-10-24 21:38 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                .addAddress(receiverAccountAlias);
You can use headlong to construct the data, then use `new ContractExecuteTransaction().setFunctionParameters(ByteString.copyFrom(data))`. `ContractClient.executeContract()` could be overloaded to pass `byte[]` instead of `ContractFunctionParameters`. But this isn't critical for this PR.

2023-10-24 21:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public void executeBalanceOfFunctionWithLimitedGas(String tokenName) {
We should avoid manual conversion to enum.

```suggestion
    @Then("I call estimateGas with balanceOf function for {token} and verify the estimated gas against HAPI")
    public void executeBalanceOfFunctionWithLimitedGas(TokenNameEnum tokenName) {
```

2023-10-25 08:44 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +    public void executeBalanceOfFunctionWithLimitedGas(String tokenName) {
Removed the manual conversion.

2023-10-25 08:44 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                .addAddress(receiverAccountAlias);
Following your steps I've managed to do it. Thanks for the suggestions it was pretty helpful!

2023-10-25 18:51 UTC, steven-sheehy approved these changes
LGTM

2023-10-25 18:52 UTC, merged