Update Besu version to 23.10.0
hashgraph/hedera-mirror-node pull request #7117
Opened 2023-10-25 11:38 UTC by bilyana-gospodinova

**Description**:
This PR updates the Besu EVM library version to 23.10.0 in order to be equivalent with hedera-services.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/7092

2023-10-25 13:07 UTC, lukelee-sl approved these changes
LGTM

2023-10-25 13:26 UTC, Nana-EC requested changes
Looking good.
2 clarifying points to confirm

2023-10-25 13:26 UTC, Nana-EC commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdaterTest.java
> +        updatedHederaEvmAccount.setBalance(Wei.ONE);
Nit: value was changed from 100 to 1.
Not sure if there's a possibility it might change behavior but want to make sure this is an intentional reduction in the value

2023-10-25 13:26 UTC, Nana-EC commented on hedera-mirror-common/build.gradle.kts
> +    api("tech.pegasys:jc-kzg-4844")
Q: why is this needed here and in other places?

2023-10-25 13:28 UTC, lukelee-sl commented on build.gradle.kts
> +        api("tech.pegasys:jc-kzg-4844:0.7.0")
Can you explain this dependency - looks like it should come in with the besu jar.

2023-10-25 14:01 UTC, bilyana-gospodinova commented on build.gradle.kts
> +        api("tech.pegasys:jc-kzg-4844:0.7.0")
There was an error for this dependency at compile time. It seems that only adding this repository is enough (maven { url = uri("https://artifacts.consensys.net/public/maven/maven/")}). I will remove the dependency in the next commit.

2023-10-25 14:02 UTC, bilyana-gospodinova commented on hedera-mirror-common/build.gradle.kts
> +    api("tech.pegasys:jc-kzg-4844")
Answered in https://github.com/hashgraph/hedera-mirror-node/pull/7117#discussion_r1371819723.

2023-10-25 14:07 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdaterTest.java
> +        updatedHederaEvmAccount.setBalance(Wei.ONE);
Thanks for pointing it out. The change in the value was not needed.

2023-10-25 14:13 UTC, kselveliev submitted a review, later dismissed
LGTM

2023-10-25 17:02 UTC, steven-sheehy requested changes

2023-10-25 17:02 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +
Remove this repository everywhere except web3 gradle.

2023-10-25 17:02 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("com.swirlds:swirlds-common")
Do we really need this separate dependency? Shouldn't hedera-evm depend upon it? There's no version for it in root build.gradle.kts so that implies it really is a transitive dependency.

2023-10-26 07:21 UTC, bilyana-gospodinova commented on build.gradle.kts
>          api("org.hyperledger.besu:secp256k1:0.6.1")
org.hyperledger.besu:secp256k1 is now updated to 0.8.0

2023-10-26 07:21 UTC, bilyana-gospodinova commented on hedera-mirror-rest-java/build.gradle.kts
> +
Done

2023-10-26 07:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("com.swirlds:swirlds-common")
com.swirlds:swirlds-common is removed as a dependency from web3.

2023-10-26 07:25 UTC, bilyana-gospodinova commented on hedera-mirror-rest-java/build.gradle.kts
> +
If I remove it the build fails with:

Execution failed for task ':common:test'.
> Could not resolve all files for configuration ':common:testRuntimeClasspath'.
   > Could not find tech.pegasys:jc-kzg-4844:0.7.0.
     Required by:
         project :common > org.hyperledger.besu:evm:23.10.0

2023-10-26 12:51 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +
Ok, then please remove everywhere but add to https://github.com/hashgraph/hedera-mirror-node/blob/bc8f5a34129f0e6b513b625381606a362611f844/buildSrc/src/main/kotlin/java-conventions.gradle.kts#L38

2023-10-26 13:02 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2023-10-26 14:58 UTC, steven-sheehy approved these changes
LGTM

2023-10-26 16:30 UTC, Nana-EC approved these changes
LGTM

2023-10-26 16:31 UTC, merged