HIP-584: 06812 - Added new query for contract state to return historical contract state storage value
hashgraph/hedera-mirror-node pull request #7118
Opened 2023-10-25 13:18 UTC by kselveliev

Description:

This PR fixes part of the following [issue](https://github.com/hashgraph/hedera-mirror-node/issues/6812)

**Description**:
For historical support we need to be able to get historical snapshot of the contract state.
To do this we need to add new method to retrieve a historical contract state storage value based on a timestamp filter.

This PR modifies:
Added new method in **ContractStateRepository** to retrieve historical contract state storage value.
Added new unit tests in **ContractStateRepositoryTest** to test all the possible scenarios for the newly added repository method.

**Related issue(s)**:

Fixes #6812

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-10-26 00:39 UTC, xin-hedera requested changes

2023-10-26 00:39 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractStateRepository.java
> +            ) as combined_result
should just query `contract_state_change`, the union all will run both subqueries and then end up perhaps either throwing away one duplicate copy or no matching result found from `contract_state`

when querying contract_state_change, it should `coalesce(value_written, value_read)`  since value_written can be null, indicating the slot is read but not written to

2023-10-26 14:41 UTC, xin-hedera requested changes

2023-10-26 14:41 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/ContractStateRepositoryTest.java
> +    void findStorageOfContractStateChangeByBlockTimestampSuccessfulCall() {
Need multiple rows contract_state_change for the same (contract_id, slot) so we know the method returns the correct value w.r.t. to the blockTimestamp.

also need a row where `value_written` is null to verify the method returns the value from `value_read`

2023-10-26 15:54 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/ContractStateRepositoryTest.java
> +    void findStorageOfContractStateChangeByBlockTimestampSuccessfulCall() {
Comment addressed.

2023-10-27 03:44 UTC, xin-hedera approved these changes
LGTM

2023-10-27 12:15 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-10-27 22:25 UTC, steven-sheehy approved these changes
LGTM

2023-10-27 22:26 UTC, merged