07114: Token transfer does not fail after dissociate
hashgraph/hedera-mirror-node pull request #7146
Opened 2023-11-01 12:40 UTC by kselveliev

With the introduction of **hasAssociation** flag in **TokenRelationship**

After dissociate operation **hasAssociation** flag is set to **false** in the **TokenRelationship**.

After associate operation **hasAssociation** flag is set to **true** in the **TokenRelationship**.

However after the addition of **HederaTokenStore** in mirror-node during **sanityChecked**

**hedera-services** checks → if (!tokenRelsLedger.exists(tokenRelationShipKey)) { do validation   }

**mirror-node** checks → if (tokenRelationship.getAccount().getId().equals(Id.*DEFAULT*)) { do validation }

In mirror node currently we do NOT check **hasAssociation** flag of the **TokenRelationship** and due to this the validation is skipped and we are not returning status **TOKEN_NOT_ASSOCIATED_TO_ACCOUNT** everytime we expect to.

**This PR modifies**

**HederaTokenStore** **sanityChecked**(), **autoAssociate**() methods 

and modifies the if statements in them where we should check if token relationship has association.

Modified token relationship associations in unit tests in **HederaTokenStoreTest**.

**Related issue(s)**:

Fixes #7114

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2023-11-01 14:14 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-11-01 14:34 UTC, steven-sheehy requested changes

2023-11-01 14:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            if (!tokenRelationship.getAccount().getId().equals(Id.DEFAULT) || tokenRelationship.hasAssociation()) {
Think this is the wrong approach. `store.getTokenRelationship()` is used in a number of places and this only fixes a few of its uses. To fix everywhere we should push this fix into the store. Consensus nodes do the following:

```java
    if (tokenRelsLedger.contains(Pair.of(aId, tId))) {
        return TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT;
    }
```

So inside their store they do not even have dissociated relationships at all. I think we should change the store to be similar so we only query associated relationships from the database and return an empty relationship for dissociated.

2023-11-06 08:13 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            if (!tokenRelationship.getAccount().getId().equals(Id.DEFAULT) || tokenRelationship.hasAssociation()) {
In `TokenRelationshipDatabaseAccessor` we already only query associated relationships.
When we want to get dissociated one, the store will either return default/empty token rel object or throw an error (depending on OnMissing argument).

2023-11-06 18:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            if (!tokenRelationship.getAccount().getId().equals(Id.DEFAULT) || tokenRelationship.hasAssociation()) {
I see, so this is for scenarios where token relationship is associated in db, but dissociated in memory via some operation? Regardless, the point still stands that we should only return associated relationships from the store. Otherwise we probably have other areas that we'd have to check associate flag to match services logic.

2023-11-07 12:59 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +            final var tokenRel = tokenRelationshipAccessor.get(tokenRelationshipKey);
We should search also for a `TokenRelationshipKey` where the account address has an alias (if applicable). We can use - keyFromRelationshipWithAlias(persistedTokenRel);

If we find a record where the account has an alias - we should also delete it. Basically we can have 2 token relationships between a token and an account - one where the account has long zero address and one, where they have an alias.

2023-11-07 22:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +    public void deleteTokenRelationship(TokenRelationship tokenRelationship) {
Missing test coverage in StoreImplTest for all code paths.

2023-11-08 17:13 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +            if (!tokenRelationship.getAccount().getId().equals(Id.DEFAULT) || tokenRelationship.hasAssociation()) {
After the above conversations I've removed the hasAssociation flag in the TokenRelationship model as it does not exist in services. Once we do dissociate, the relationship is marked as destroyed and we now delete the relationship from store. And if when we try to get token relationship from the store if it is deleted we simply return an empty relationship.

2023-11-08 17:14 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +            final var tokenRel = tokenRelationshipAccessor.get(tokenRelationshipKey);
Comment addressed. I added a logic to also check and delete possible alias token relationship.

2023-11-08 17:15 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +    public void deleteTokenRelationship(TokenRelationship tokenRelationship) {
Commentd addressed. Added tests for the delete method in StoreImplTest.

2023-11-08 17:28 UTC, steven-sheehy approved these changes
LGTM

2023-11-09 18:58 UTC, IvanKavaldzhiev approved these changes
LGTM!

2023-11-09 18:59 UTC, merged