07122: Update the blockhash operation to return value for all blocks
hashgraph/hedera-mirror-node pull request #7156
Opened 2023-11-02 12:26 UTC by bilyana-gospodinova

**Description**:
In this PR a custom implementation of the blockhash operation is added. With this change we can get the block hash value of any block up to the latest one.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/7122

2023-11-03 08:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/evm/contracts/operations/HederaBlockHashOperation.java
> +public class HederaBlockHashOperation extends BlockHashOperation {
Since this opcode contains mirror node specific logic, which we would want to keep, we should move this class into `com.hedera.mirror.web3.evm.contracts.operations` package.

After we start deleting the logic from `com.hedera.services` and replacing it with the modularized code from hedera-services repo, we should investigate. the option of keeping this logic. If we don't find a way to add this custom opcode to the EVM configuration, which most probably would be moved inside the new `hedera-smart-contracts` service, we may need to find a different fix for the BLOCKHASH issue, but for the moment, this fix would be sufficient.

2023-11-03 16:32 UTC, steven-sheehy requested changes

2023-11-03 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/evm/contracts/operations/HederaBlockHashOperation.java
> +        frame.pushStackItem(blockHash);
The old logic would return zero if the sought block was greater than latest or negative. This new logic will throw an error. There's also the question does it throw error or return zero if positive & less than latest but not found. I think we need to add back some bounds checking to match the previous behavior.

2023-11-03 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashIsNotEmpty() {
We should have some more tests for negative, beyond latest, below min, etc.

2023-11-06 08:42 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/evm/contracts/operations/HederaBlockHashOperation.java
> +public class HederaBlockHashOperation extends BlockHashOperation {
The class was moved to the suggested package.

2023-11-06 08:42 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void getLatestBlockHashIsNotEmpty() {
Added test for values after latest block.

2023-11-06 08:53 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/evm/contracts/operations/HederaBlockHashOperation.java
> +        frame.pushStackItem(blockHash);
I added some of the previous if-statements. We can't really have negative block values as in Solidity the blockhash function accepts unsigned values. I have added an if-statement for this case anyway and the result will be zero.

In case the block value is positive and less than latest but not found, an error will be thrown and this was the same in the previous logic. Can there be such case at all (other than in the integration tests)?

2023-11-06 18:08 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/evm/contracts/operations/HederaBlockHashOperation.java
> +        frame.pushStackItem(blockHash);
> In case the block value is positive and less than latest but not found, an error will be thrown and this was the same in the previous logic. Can there be such case at all (other than in the integration tests)?

It's a valid scenario for partial mirror nodes who start after block zero by setting a startDate (or leaving it unset to default to now). Since the previous and current logic throw an error for block not found perhaps its fine as it is now.

2023-11-06 18:09 UTC, steven-sheehy submitted a review, later dismissed
LGTM. One code smell plus workflows are stuck. Maybe fix the code smell and that should re-trigger the workflows.

2023-11-06 18:28 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2023-11-09 13:17 UTC, kselveliev approved these changes
LGTM

2023-11-09 17:45 UTC, merged