HIP-584: Make `MirrorEvmTxProcessor` singleton
hashgraph/hedera-mirror-node pull request #7177
Opened 2023-11-07 11:15 UTC by IvanKavaldzhiev

**Description**:

It seems we can save memory footprint additionally by making `MirrorEvmTxProcessor` bean to be Singleton. 

In the current code base we have defined `MirrorEvmTxProcessor` to be with factory scope and have a new instance for each new transaction. Analysis of heap dumps during K6 tests with multiple VUs showed that currently we have 2 dominator objects, which are `ContractCallContext` and `MirrorEvmTxProcessor`. They both retain memory size for the same classes and we have duplication of unnecessary classes in memory.

By making  `MirrorEvmTxProcessor` singleton we have one single instance for all requests and we remove the duplication of these objects.

![factory_bean_dominator_classes_2](https://github.com/hashgraph/hedera-mirror-node/assets/5901140/167d4391-f9c3-40a2-ab69-708dc7566622)
![factory_bean_dominator_classes](https://github.com/hashgraph/hedera-mirror-node/assets/5901140/ec47246e-b2e7-4b55-82d9-745c1d2656f9)
![factory_bean_memory_retained_size](https://github.com/hashgraph/hedera-mirror-node/assets/5901140/aa8ef69d-69ac-4e06-b88f-c6af3aaf845b)
![singleton_bean_dominator_classes_2](https://github.com/hashgraph/hedera-mirror-node/assets/5901140/d4ca1732-dd13-42ed-82e1-8c949001038f)
![singleton_bean_dominator_classes](https://github.com/hashgraph/hedera-mirror-node/assets/5901140/748f18f4-218e-4f69-9915-57e6cc7c5fed)
![singleton_bean_memory_retained_size](https://github.com/hashgraph/hedera-mirror-node/assets/5901140/978f6b7e-1806-48cb-8647-708fb6ea2da7)

**Related issue(s)**: #6612 

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-07 12:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private Address senderAddress;
ContractCallContext has a reset() method that is used in the BinaryGasEstimator. Don't we need to reset these new fields in this method as well?

2023-11-07 12:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private Address senderAddress;
I have already added a reset for these fields there.

2023-11-07 12:33 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private Address senderAddress;
Oh, my bad. I was looking at the wrong method.

2023-11-07 12:39 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +    public synchronized HederaEvmTransactionProcessingResult execute(
Wouldn't this slow down the performance significantly? This way we will basically process only 1 transaction at a time.

2023-11-07 12:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +    public synchronized HederaEvmTransactionProcessingResult execute(
Having the `MirrorEvmTxProcessor` to be singleton, we save a lot of memory footprint but sacrifice some of the TPS handling. My assumption, though, is that while some threads may be blocked to execute the transaction via `execute` method, others may read data from the DB and prepare their own `ContractCallContext` to be ready for the execution, so executions of transactions are not totally blocked and threads have some other tasks to do. Most of transactions are executed below `200ms` I believe, but we can think of internal mechanism inside `MirrorEvmTxProcessor`, that saves us from very heavy malicious transactions and throw exception if certain time period is reached 🤔 

We should decide which factor is more blocking for us - increased memory retained size and web3 K8 pods starting to scale a lot or safe memory size and sacrifice some of the TPS. If we don't have user complaints for getting a lot of HTTP 429 requests, probably its safe to go with the second approach, introduced in this PR.

2023-11-14 14:37 UTC, kselveliev submitted a review, later dismissed
LGTM

2023-11-15 21:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +    public synchronized HederaEvmTransactionProcessingResult execute(
Based on K6 tests and metrics monitored in VisualVM it seems with this PR we have relatively 4 times quicker requests and a lot less CPU spikes and overall CPU consumption, making it possible to even increase our rate limit value.

2023-11-15 21:11 UTC, steven-sheehy requested changes

2023-11-15 23:40 UTC, steven-sheehy requested changes

2023-11-15 23:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +                        gasCalculator, basicHbarCentExchange, mirrorNodeEvmProperties, Instant.now()));
Move this precompile map to be a separate bean then remove `MirrorEvmMessageCallProcessor` bean and used `@Named`.

2023-11-15 23:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +                        new HederaEvmCreateOperation(gasCalculator, createOperationExternalizer),
nit: Can avoid the extra param. Spring is smart enough to only create one.

```suggestion
                                gasCalculator, mirrorNodeEvmProperties, createOperationExternalizer()),
                        new HederaEvmCreateOperation(gasCalculator, createOperationExternalizer()),
```

2023-11-15 23:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +                EVM_VERSION_0_30, () -> messageCallProcessor, EVM_VERSION_0_34, () -> mirrorEvmMessageCallProcessor);
Move these maps to separate beans, then you can make `MirrorEvmTxProcessor` `@Named`.

2023-11-15 23:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/ServicesConfiguration.java
> +        return new EvmInfrastructureFactory(evmEncodingFacade);
```suggestion
    EvmInfrastructureFactory evmInfrastructureFactory() {
        return new EvmInfrastructureFactory(evmEncodingFacade());
```

2023-11-15 23:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
We need to make `HederaEvmTxProcessor` stateless for this to be singleton. Luckily, we don't use many of the stateful fields:

* `coinbase`: Is a property so can move to constructor
* Move `tracer` to a final field populated in constructor
* Move `messageCallProcessor` and `contractCreationProcessor` assignment into constructor and make final since we don't seem to support dynamic evm version at runtime
* Push `intrinsicGas` into `execute()` and calculate it there
* Push `gasUsed` into local variable since it's only used within execute()
* Push `initialFrame` into local variable since it's only used within execute()
* Push `sbhRefund` into local variable since it's only used within execute()
* Remove unused setWorldState() and make field final
* Remove unused setBlockMetaSource() and make field final

2023-11-17 14:02 UTC, closed without merging