HIP-584: Account balance cache delays is reflecting to proper eth_call balance update
hashgraph/hedera-mirror-node pull request #7178
Opened 2023-11-07 12:40 UTC by 0xivanov

**Description**:
We've identified an issue where the caching mechanism for an account balance (in HBARS) is causing a delay in reflecting real-time balance updates. When performing an eth_call operation to retrieve an account balance, followed by a transaction to change the account balance, and then another eth_call operation to retrieve the updated balance, the latter eth_call does not return the updated balance immediately. It retains the old balance from the cache for about 30 seconds before updating to reflect the new balance.

Steps to reproduce: 

1. Perform an eth_call operation to an account to retrieve the current balance.
2. Send funds to the account to change its balance and wait for the transaction to be received in the mirror node.
3. Perform another eth_call operation to the account to retrieve the updated balance.

Additional context:
Upon investigation, it appears that the caching mechanism triggered during the first eth_call operation is holding onto the old balance value for a duration of 30 seconds. This delay in cache update is leading to incorrect balance being returned in the subsequent eth_call operation post the account balance change.

**Related issue(s)**:

Fixes #7043

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-08 07:44 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        receiverAccountId = accountClient.getAccount(AccountNameEnum.ALICE);
Accounts that have `ECDSA_SECP256K1` like BOB fail the `accountClient.sendCryptoTransfer` transaction, so i use ALICE here. Not sure why that happens though.

2023-11-08 10:17 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        receiverAccountId = accountClient.getAccount(AccountNameEnum.ALICE);
This is because BOB account has receiverSigRequired = true and we need to pass his privateKey similar to the tokenClient `transferFungibleToken` function. Maybe you can try modifying the `sendCryptoTransfer` to accept privateKey as well or we can keep it this way if it's too much effort.

2023-11-08 17:24 UTC, steven-sheehy requested changes

2023-11-08 17:24 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/properties/CacheProperties.java
> +    private String contractState = ENTITY_CACHE_CONFIG;
Need to update default in `docs/configuration.md`.

2023-11-08 17:24 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        receiverAccountId = accountClient.getAccount(AccountNameEnum.ALICE);
We can also probably just remove receiverSigRequired=true from BOB if it's easier. Setting it doesn't really test anything related to mirror node functionality.

2023-11-08 17:24 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +                asAddress(receiverAccountId.getAccountId().toSolidityAddress()));
nit: Move to separate line so `encodeData` line can be on a single line.

2023-11-09 10:56 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        receiverAccountId = accountClient.getAccount(AccountNameEnum.ALICE);
@steven-sheehy In my opinion it would be better if we keep BOB for now with receiverSigRequired as he might come in handy in our next in-equivalence tests that are coming up to the mirror node. Secondly, if we decide to get rid of receiverSigRequired we might need to refactor all the places where we use BOB and we do transfers. 
The approach that @0xivanov decided to take(using ALICE) is fine imo.

2023-11-09 15:18 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        receiverAccountId = accountClient.getAccount(AccountNameEnum.ALICE);
Implementing the setting of private key in the transaction is also valid solution...

2023-11-10 07:55 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +                asAddress(receiverAccountId.getAccountId().toSolidityAddress()));
extracted `asAddress(receiverAccountId.getAccountId().toSolidityAddress())` to a variable

2023-11-10 07:55 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/properties/CacheProperties.java
> +    private String contractState = ENTITY_CACHE_CONFIG;
Updated

2023-11-10 15:33 UTC, steven-sheehy approved these changes
LGTM

2023-11-10 15:34 UTC, merged