Time partition and deduplicate existing balance data in v1
hashgraph/hedera-mirror-node pull request #7181
Opened 2023-11-07 18:41 UTC by xin-hedera

**Description**:

This PR time partitions `account_balance` and `token_balance`, and dedups the existing balance data in v1

- Add a versioned SQL migration for helper functions to dedup balance data
- Add a versioned SQL migration to time partition and dedup the last 6-hour account_balance and token_balance data
- Add a repeatable SQL migration for partition maintenance procedures in v1
- Add an async java migration to backfill and deduplicate remaining balance data
- Remove `deduplicate` from `HistoricalBalanceProperties`
- Fix `(Account|Token)BalanceRepository.balanceSnapshot` to also include balance info deleted right at or before a full snapshot
- Fix flyway placeholder `partitionStartDate` to use absolute date
- Change web3 `TokenBalanceRepository` to use `account_balance` instead of `account_balance_file`
- Change rosetta to use deduped account_balance data
 
**Related issue(s)**:

Fixes #7005

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-11-07 19:04 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/PartitionMaintenance.java
> +    @Scheduled(initialDelay = 60, fixedDelay = Long.MAX_VALUE, timeUnit = TimeUnit.SECONDS)
The problem of `@EventListener(ApplicationReadyEvent.class)` is the integration test for V1.89.0 migration will fail when `partitionMaintenance.runMaintenance` is triggered synchronously by application ready event in the spring test context and the SQL procedure raises exceptions since the tables are yet to be partitioned, the spring application fails to start.

Making it `@Async` while keeping `@EventListener(ApplicationReadyEvent.class)` can avoid the exception bubbling up to the main process, however makes testing more difficult.

Perhaps we can just remove `@EventListener(ApplicationReadyEvent.class)` and the new `@Scheduled` workaround above

2023-11-07 19:09 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +    // To simplify the test case, the create_(deduped|full)_*_balance_snapshot functions are not dropped at the end
If we want to drop these no longer needed SQL functions and make the integration test not so complicated, we can split V1.89.0 to two sql migrations

- the first creates the `create*` functions
- the second creates other functions, partitions and deduplicates the balance tables

Then in the integration test, we just need to reapply the first SQL migration in the after each hook

2023-11-07 19:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +            "select balance from account_balance_old where consensus_timestamp = -1 and account_id = -1";
the balance column of the row (account_id, consensus_timestamp) = (-1, -1) keeps the consensus timestamp of the first snapshot processed by migration V1.89.0

2023-11-07 19:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceFileRepository.java
> +public interface AccountBalanceFileRepository extends StreamFileRepository<AccountBalanceFile, Long> {
when `account_balance` and `token_balance` are partitioned, we should drop partitions to remove old data. I can revert the changes to these repositories to make the PR simpler.

2023-11-07 19:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceRepository.java
> +              where account_id = 2 and consensus_timestamp > :consensusTimestamp - 2592000000000000
2592000000000000 is 30 days

2023-11-07 19:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> +      partitionStartDate: "'2019-09-01'"
default value for mainnet

2023-11-07 19:19 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceServiceIntegrationTest.java
> +@Disabled("Disabled WIP")
all test cases fail in this class, it's quite difficult to understand the test cases itself so have it disabled. will fix and re-enable it

2023-11-07 19:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +        long lowerBound = last + 4 * ONE_HOUR_IN_NS;
will replace `4 * ONE_HOUR_IN_NS` with `MIN_INTERVAL`, looks like I made the change then lost it

2023-11-07 20:26 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceFileRepository.java
> +public interface AccountBalanceFileRepository extends StreamFileRepository<AccountBalanceFile, Long> {
update, actually we have to make them not implement `RetentionRepository`

problem is if the repo is pruned with a non partition boundary timestamp, account's balance info can get lost since it's deduped

2023-11-07 20:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.0__add_balance_deduplicate_functions.sql
> +  return count;
return the number of inserted rows, useful info in the async Java migration

2023-11-08 21:37 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +            drop table token_balance_old;
truncating the tables took 35 minutes while directly dropping them took 1 hour

2023-11-08 21:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +        jdbcTemplate.execute("set local work_mem = '512MB'"); // Use higher work_mem to avoid temp files
since it's `set local`, the 512MB work_mem is only effective in the current db transaction

2023-11-08 21:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenBalanceRepository.java
> +              consensus_timestamp < :consensusTimestamp
unlike `AccountBalanceRepository.balanceSnapshot`, there is an additional `consensus_timestamp < :consensusTimestamp` condition, this is to handle the corner case that account_balance snapshot at `:consensusTimestamp` is generated before token_balance snapshot

2023-11-08 21:45 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceServiceIntegrationTest.java
> +        long now = DomainUtils.convertToNanosMax(Instant.now());
main changes in the integration test

- revert the overall test flow to the state before deduplication is implemented
- change `verifyGeneratedBalances` to reduce complexity, let the test case main logic pass in list of updated entities and token accounts which should have new balance info added to the snapshot
- remove conditional testing of dedup, since now it's always deduped and time partitioned

2023-11-08 21:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/application.yml
> +      partitionStartDate: "'2019-09-01'"
The old values is misleading and not easy to config for production environments.

The name indicates it's a date while the value used to be an interval.

When deploying, for instance, for mainnet, one has to override the value so the absolute date in the migration `current_timestamp - ${partitionStartDate}` is not after 2019-09

2023-11-09 04:39 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/PartitionMaintenance.java
> +    @Scheduled(initialDelay = 60, fixedDelay = Long.MAX_VALUE, timeUnit = TimeUnit.SECONDS)
We can listen for Flyway events to determine when baseline is complete, then run this maintenance. See `MigrationHealthIndicator` for an example. Perhaps we can have some other class that adapts flyway events to Spring events to decouple the two.

2023-11-09 16:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/PartitionMaintenance.java
> +    @Scheduled(initialDelay = 60, fixedDelay = Long.MAX_VALUE, timeUnit = TimeUnit.SECONDS)
I think I can use a mock bean in that single integration test, it won't affect others because that integration test has its own test application context due to a specific flyway migration target set.

2023-11-14 21:52 UTC, steven-sheehy requested changes

2023-11-14 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +            "select balance from account_balance_old where consensus_timestamp = -1 and account_id = -1";
I don't see where we remove this sentinel row at the end?

2023-11-14 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +    private static final long MIN_INTERVAL = Duration.ofHours(4).toNanos();
Should probably make this a migration property in case we need to adjust it.

2023-11-14 21:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.2__time_partition_balance_tables.sql
> +        substring(pg_get_expr(child.relpartbound, child.oid) from 'FROM \(''(\d+)''\)')::bigint as from_timestamp
I see this query in a number of places including in go code. Should we create a permanent procedure for this to centralize this pg-specific partition lookup logic? Or even better a view?

2023-11-15 15:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +            "select balance from account_balance_old where consensus_timestamp = -1 and account_id = -1";
the table is dropped at the end of the async migration

2023-11-15 15:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AccountBalanceFileRepository.java
> +public interface AccountBalanceFileRepository extends StreamFileRepository<AccountBalanceFile, Long> {
correct that's the improvement we need for retention, especially for v2

2023-11-15 16:53 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AbstractAsyncJavaMigrationTest.java
> +    protected void waitForCompletion(AsyncJavaMigration<?> migration) {
will add an abstract getter `T getMigration()` in `AbstractAsyncJavaMigrationTest`, don't want to make it a member since then have to add constructors to the concrete migration test classes v.s. generated constructor by lombok `RequiredArgsConstructor`

2023-11-15 17:00 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AbstractAsyncJavaMigrationTest.java
> +                .untilAsserted(() -> assertThat(isMigrationCompleted(migration)).isTrue());
we might want to adopt the methods in `AbstractAsyncJavaMigrationTest`.

I believe it was flaky because we didn't disable  `SyntheticCryptoTransferApprovalsMigration` in test application.yaml so when the test case `onEnd` runs and checks `flyway_schema_history` the checksum might be already 1 before the actual migration completes.

2023-11-16 17:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +    private static final long MIN_INTERVAL = Duration.ofHours(4).toNanos();
made it a migration property

2023-11-16 17:19 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.2__time_partition_balance_tables.sql
> +        substring(pg_get_expr(child.relpartbound, child.oid) from 'FROM \(''(\d+)''\)')::bigint as from_timestamp
made it into a view `mirror_node_time_partitions`

2023-11-16 17:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceProperties.java
> +    @DurationMax(days = 7)
limit it to a max of 7 days, since in the query for full snapshot, we put a lower bound of new snapshot timestamp - 30days to limit the number of time partitions to search for the last balance timestamp of account 2.

2023-11-16 17:21 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +                        "Generated {} historical account balance file {} with {} account balances and {} token balances in {}",
change the log format to show if it's a full or deduped balance snapshot

2023-11-16 20:59 UTC, steven-sheehy requested changes

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartition.java
> +    //    private String range;
We shouldn't have commented out code.

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceProperties.java
> +    @DurationMax(days = 7)
Can we add a javadoc with a similar comment. Also note the max 7 days in configuration.md.

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.1__add_balance_deduplicate_functions.sql
> +create or replace view mirror_node_time_partitions as
Might be better to have a `R__view.sql` to create this in case we need to recreate it. But I guess repeatable get created after versioned?

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java
> +@Import(PartitionMaintenanceDisabledMigrationTestConfiguration.class)
nit: Could simplify name
```suggestion
@Import(DisablePartitionMaintenanceConfiguration.class)
```

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__mirror_node_time_partitions.sql
Prefer `R__view.sql`

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +        minFrequency = DurationStyle.SIMPLE
Does this need to be set here or can we set in constructor?

2023-11-16 20:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AbstractAsyncJavaMigrationTest.java
> +    @AfterEach
It would be safer for future use to use `@BeforeEach` in case it gets ran automatically elsewhere. Or can maybe add both before and after annotations.

2023-11-16 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartition.java
> +    //    private String range;
leftover when changing TimePartitionService to use the new db view, `range` is no longer needed since now we parse the range string in SQL not in java code

2023-11-16 21:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.89.1__add_balance_deduplicate_functions.sql
> +create or replace view mirror_node_time_partitions as
yeah, that's the problem, V1.89.2 depends on the view

2023-11-16 21:16 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__mirror_node_time_partitions.sql
sure

2023-11-16 21:18 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillAndDeduplicateBalanceMigration.java
> +        minFrequency = DurationStyle.SIMPLE
set it here instead of inside the constructor so testing is easier with a stateless bean, or a bean when data / config changes, run it again would apply the new values.

Otherwise, I have to change the integration test pattern to create a new `BackfillAndDeduplicationBalanceMigration` object for each test.

2023-11-16 21:18 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AbstractAsyncJavaMigrationTest.java
> +    @AfterEach
sure

2023-11-16 21:49 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.historicalBalance.minFrequency`            | 15m                                              | How often at least to generate balances information. Can accept
minimum is misspelled.

2023-11-16 21:56 UTC, steven-sheehy submitted a review, later dismissed
LGTM 🥂

2023-11-17 02:59 UTC, jnels124 approved these changes
LGTM

2023-11-17 17:16 UTC, steven-sheehy approved these changes
LGTM

2023-11-17 18:58 UTC, merged