Add Health check on Rest Network Stake
hashgraph/hedera-mirror-node pull request #7182
Opened 2023-11-07 20:46 UTC by edwin-greene

**Description**:
Add a health check on the Rest Network Stake endpoint. If this endpoint is down it may be indicative of a database problem.

**Related issue(s)**:

Fixes #7141 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-11-07 21:46 UTC, steven-sheehy requested changes

2023-11-07 21:46 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ClusterHealthIndicator.java
> +                .onErrorResume(e -> NETWORK_STAKE_UNKNOWN);
For api down or unknown, a non-static health with a descriptive reason would be beneficial. Since errors should be infrequent, just call `health()` here and pass the exception message or exact status code. We should also log the error for those.

2023-11-07 21:46 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
> +        "1.0, 1.0, 500, DOWN", // network stake down
Add test case for 0/0/500, 0/1/500, 1/0/500 for completeness even though they should be equivalent to this.

2023-11-07 22:36 UTC, edwin-greene commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ClusterHealthIndicator.java
> +                .onErrorResume(e -> NETWORK_STAKE_UNKNOWN);
Sounds good I have made those changes.

2023-11-07 22:36 UTC, edwin-greene commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
> +        "1.0, 1.0, 500, DOWN", // network stake down
Got it, I have updated the test with those additions.

2023-11-07 22:43 UTC, steven-sheehy approved these changes
LGTM

2023-11-08 02:40 UTC, xin-hedera approved these changes
LGTM

2023-11-08 13:57 UTC, merged