HIP-584 Historical: Set historical block values
hashgraph/hedera-mirror-node pull request #7185
Opened 2023-11-08 08:59 UTC by 0xivanov

**Description**:

We already have a timestamp field added in `ContractCallContext` class with a default value of -1.
In order to support evm operations we need to set historical block values like: `gasLimit`, `blockNo`, `consTimestamp`.

Based on the timestamp field extract the needed block values data and set in `StaticBlockMetaSource`.

**Related issue(s)**:

Fixes #7184

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-08 17:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +                .findByTimestamp(ContractCallContext.get().getBlockTimestamp())
This is inefficient. We already query for the block timestamp to set `ContractCallContext.blockTimestamp`. We should just set the entire `RecordFile` inside the context so we don't have to re-query it here.

2023-11-09 08:39 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +                .findByTimestamp(ContractCallContext.get().getBlockTimestamp())
I now saw that i am missing logic. If we have non-historical call the timestamp is -1 and the query will fail. So i should have check for that and query latest block if timestamp is -1.
Anyhow, should i set the record file only when we have historical call? Because if not, we would still make 2 identical queries when doing non-historical call: findByIndex returns latest record file and findLatest returns the same.

2023-11-09 08:41 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +                .findByTimestamp(ContractCallContext.get().getBlockTimestamp())
I could set the record file regardless of historical/non-historical type of call, but this would change the logic quite a bit in ContractCallService

2023-11-09 15:15 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +                .findByTimestamp(ContractCallContext.get().getBlockTimestamp())
Implemented the record file setting, i think we could optimise it even more, so feel fee to give suggestions.
@IvanKavaldzhiev 
@steven-sheehy

2023-11-09 15:15 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/RecordFileRepository.java
> +    Optional<RecordFile> findByTimestamp(long timestamp);
Removed

2023-11-09 19:03 UTC, steven-sheehy requested changes

2023-11-10 07:22 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> -    private long blockTimestamp = UNSET_TIMESTAMP;
Removed

2023-11-10 07:25 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/StaticBlockMetaSource.java
> +        if (Objects.isNull(recordFile)) {
Nice catch. We are not guaranteed as far as I know. I ran the acceptance tests to see how this method is handled, but it was not called even once. I reverted the change for this method just to be sure.

2023-11-10 15:51 UTC, steven-sheehy approved these changes
LGTM

2023-11-10 15:55 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-11-10 15:55 UTC, merged