Set correct sender account in `TransferPrecompile`
hashgraph/hedera-mirror-node pull request #7194
Opened 2023-11-10 15:46 UTC by 0xivanov

**Description**:

Sender account is not being set properly in `TransferPrecompile`. The correct account should be `senderAddress` from `HtsPrecompiledContract`.
This causes incorrect behaviour compared to hedera-services.

Affected operations: `transferFrom`

**Related issue(s)**:

Fixes #7192

**Notes for reviewer**:
We have false positive tests in web3 and test modules that will be corrected with this PR.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-10 15:47 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java
> -            HederaEvmContractAliases mirrorEvmContractAliases);
If someone has better alternative for getting the `senderAddress` from `HtsPrecompiledContract` feel free to share

2023-11-13 13:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.sol
> +        IERC20(token).transferFrom(from, address(this), amount);
Here we have a case where the `spender` and `recipient` accounts are the same. It would be good to also have a test where the recipient is a different account, to cover more test cases. This can be achieved by passing the recipient address as an argument.

2023-11-13 14:49 UTC, 0xivanov commented on hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.sol
> +        IERC20(token).transferFrom(from, address(this), amount);
Added `to` argument and now the function is called 4 times. 2 for nft with 2 different `to` addresses and the same for fungible.

2023-11-13 18:34 UTC, steven-sheehy requested changes

2023-11-13 18:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java
> -            HederaEvmContractAliases mirrorEvmContractAliases);
In mono service, it's a class field in `TransferPrecompile` since the class is stateful and constructed for each request. Here, `TransferPrecompile` is stateless so we can't use that approach. Whenever there is per-request state that some previously stateful class needs we should use `ContractCallContext`. This minimizes changes to the copied services code. This is also the approach taken in #7177 which makes `HtsPrecompiledContract` stateless, so you wouldn't be able to use this approach if that PR is merged.

I also think `TransactionBody` should be removed from `getMinimumFeeInTinybars(Timestamp consensusTime, final TransactionBody transactionBody)` for the same reason and moved to `ContractCallContext`. But that can be outside the scope of this PR.

2023-11-13 18:34 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                fungibleTokenId, AccountId.fromSolidityAddress(precompileTestContractSolidityAddress), 10);
nit: Move account ids to separate variables so approveToken fits on one line.

2023-11-14 09:07 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java
> -            HederaEvmContractAliases mirrorEvmContractAliases);
Moved the sender address to `ContractCallContext`.
About #7177 we are not sure yet if it is worth making `HtsPrecompiledContract` bean.
Also i agree with the comment about the `TransactionBody`

2023-11-14 10:31 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                fungibleTokenId, AccountId.fromSolidityAddress(precompileTestContractSolidityAddress), 10);
Fixed

2023-11-14 19:18 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
> +    private ContractCallContext contractCallContext;
Not sure why all these changes are necessary when currently only TransferPrecompile needs the `ContractCallContext`?

2023-11-14 19:42 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
> +    private ContractCallContext contractCallContext;
They call `subject.prepareFields(frame);` so we need to mock the `contractCallContext.get().setSenderAddress(senderAddress);`  method, or it will throw NPE for some tests.

2023-11-14 19:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
> +    private ContractCallContext contractCallContext;
Got it, thanks

2023-11-14 19:52 UTC, steven-sheehy approved these changes
LGTM

2023-11-14 20:45 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-11-14 21:57 UTC, merged