Topic message optimization
hashgraph/hedera-mirror-node pull request #7206
Opened 2023-11-14 15:50 UTC by mgoelswirlds

**Description**:
Optimizing topic message endpoints for V2. This change will be under a feature flag , and can be enabled for v1 if needed.

This PR modifies 
* /topics/{id}/messages endpoint to use topic_message_lookup table based on sequence numbers
* it also handles the case for when sequence numbers are absent.
* Enable hedera.mirror.rest.query.v2.topicMessageLookups for v2.

**Related issue(s)**:

Fixes #6976 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-14 15:53 UTC, mgoelswirlds commented
Work in progress:
- Tests need to be written
- the scenario for returning an empty reponse needs to be handled.

2023-11-14 19:06 UTC, xin-hedera requested changes

2023-11-14 19:06 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  if (!hasSequenceNumber) {
if there is no sequence number in the request URL, we need to query `topic_message_lookup` table for either the min or max sequence number depending on `order`

2023-11-14 19:06 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  const row = await pool.queryQuietly(query, params);
```suggestion
  const {rows} = await pool.queryQuietly(query, params);
```

2023-11-14 19:47 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.rest.query.v2.topicMessageLookups`                  | false                   | Enables topic message lookup querying when enable for v2
talked to Steven offline. Let's keep the feature flag, it's less work than detecting v2 during runtime.

2023-11-16 17:19 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +      }
yes.

2023-11-16 17:45 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +  if (!hasSequenceNumber) {
You mean get the the min or max sequence_number_range from topic_message_lookup right?

2023-11-16 22:21 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +  const bound = new Bound(filterKeys.SERIAL_NUMBER, 'serial_number');
should be SEQUENCE_NUMBER. But not using Bound anymore.

2023-11-20 17:52 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +    pgSqlQuery += ` and  sequence_number_range && '[${lowerLimit},${upperLimit})'::int8range`;
Changed it to be inclusive.

2023-11-20 17:53 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +  let pgSqlQuery = `select numrange(min(lower(timestamp_range)), max(upper(timestamp_range)))
Modified it.

2023-11-21 18:09 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +  if (!hasSequenceNumber) {
I have a follow-up question. When we do get the min/max sequence number, we should still get the limit number of topic messages from a given partition which has the min/max sequence number respectively right? Currently I am getting only one but that doesn't seem right.

2023-11-22 16:50 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/topics/{id}/messages/none.json
>    "url": "/api/v1/topics/7/messages?sequencenumber=2&sequencenumber=gte:3&timestamp=lt:1234567890.000000004",
Need to handle the scenario where a missing range is built. Once that is fixed this test should pass.

2023-11-22 16:52 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/topics/{id}/messages/specific-sequence.json
>    },
For v2 now the code generating a range and it is returning a limit number of topic Messages which is more topic messages than the one eq to indicates.  Need input on handling this case.

2023-11-22 16:53 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +      // need to return an empty response
This branch of code when an empty range is built needs to be handles to return an empty response.

2023-11-22 18:14 UTC, mgoelswirlds commented
There are still unanswered questions which I am waiting for and then the builds would be passing.

2023-11-29 20:05 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  }
can't do this. because the endpoint also supports `timestamp=XXX` filters.

so the response of  `/topics/{id}/messages?sequencenumber=gt:10&timestamp=gt:1234567890.100&limit=2` may include messages with sequence number 15 and 16 because the `gt` timestamp takes precedence.

2023-11-29 20:31 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  pgSqlQuery += ` limit ${limit}`;
this is still not addressed. limit applies to the number of topic messages, not the number of rows from `topic_message_lookup`.

2023-11-29 20:31 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +const extractSqlFromTopicMessagesRequest = async (topicId, filters) => {
format, add a new line in between

2023-11-29 20:37 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +      }
this doesn't optimize stuff.

what we need to do is a three-step process

- get the min or max sequence number of the topic from `topic_message_lookup` table
- depending on order and limit, get the sequence number range `[lower, upper]` and query `topic_message_lookup` to find out the timestamp_range
- finally build the SQL query to get the messages from `topic_message` table with the timestamp range

2023-11-29 20:38 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  const query = pgObject.query;
think this is a common coding style issue.  please space the code blocks properly

2023-11-29 20:47 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +      pgSqlQuery += `)`;
construct the timestamp range conditions using functional programming patteren
```suggestion
  if (rows.length) {
     const condition = rows.map((row) => `(consensus_timestamp >= ${...} and consensus_timestamp < ${...})`).join(' or ');
     pgSqlQuery += ` and (${condition})`;
   }
```

2023-11-29 21:55 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +     const condition = rows.map((row) => `(consensus_timestamp >= ${...} and consensus_timestamp < ${...})`).join(' or ');
i didn't mean to literally copy the `${...}`, you need to replace them with the correct expression.

2023-11-30 16:01 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +      pgSqlQuery += `)`;
I just merged this with git. will fix it.

2023-11-30 18:24 UTC, mgoelswirlds commented on hedera-mirror-rest/topicmessage.js
> +  let upperLimit = undefined;
This is done specifically to be able to shortcut an empty range.

2023-11-30 18:55 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  let upperLimit = undefined;
I don't think so. You'll probably agree with me after reviewing how empty range detection done in the current implementation.

2023-12-05 22:04 UTC, xin-hedera commented on hedera-mirror-rest/model/topicMessageLookup.js
> +class TopicMessageLookup {
nice to have the model.

however my personal opinion is we should avoid using it when constructing SQL queries, it only makes the query less readable.

no changes needed btw. however it's an item we may want to address in general.

2023-12-05 22:12 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +    res.locals[constants.responseDataLabel] = topicMessagesResponse;
move these out of the if block, also remove line 167 since it only needs to set once

2023-12-05 22:13 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +async function getSequenceNumberFromTopicMessageLookup(topicId, order, limit) {
follow the existing coding style
```suggestion
const getSequenceNumberFromTopicMessageLookup = async (topicId, order, limit) {
```

2023-12-05 22:20 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +import TopicMessageLookup from './model/topicMessageLookup.js';
```suggestion
import config from './config';
import {TopicMessageLookup} from './model';
```

You'll need to import and export `TopicMessageLookup` model in `model/index.js`

2023-12-05 22:26 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  return _.isNil(rows) ? null : rows;
rows won't be null or undefined
```suggestion
  return rows;
```

2023-12-05 22:27 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  const rows = await pool.queryQuietly(query, params);
```suggestion
  const {rows} = await pool.queryQuietly(query, params);
```

2023-12-05 22:27 UTC, xin-hedera commented on hedera-mirror-rest/topicmessage.js
> +  return _.isNil(rows) ? null : rows.rows[0].sequence_number;
```suggestion
  return rows[0].sequence_number;
```

2023-12-05 23:13 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/application.yml
> +          topicMessageLookups: false
Agree, except would also drop the s: `hedera.mirror.rest.query.topicMessageLookup`

2023-12-05 23:15 UTC, steven-sheehy commented on hedera-mirror-rest/topicmessage.js
> +  let hasSequenceNumberForV2 = false;
Should not have variables named that are v2 specific

2023-12-06 01:31 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/application.yml
> +          topicMessageLookups: false
I agree. That makes sense.

2023-12-06 18:11 UTC, xin-hedera requested changes

2023-12-06 18:11 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/application.yml
> +        topicMessageLookups: false
partially addressed. I also requested moving this change to config/application.yml

the test application.yml is not where we put configuration default.

In addition, Steven also asked to drop the `s` so it should be `topicMessageLookup`

2023-12-06 18:11 UTC, xin-hedera commented on docs/configuration.md
> +| Name                                                              | Default                 | Description
this make review difficult.

should redo it with intellij markdown autoreformat disabled, or just revert and use a different text editor to add the single line.

2023-12-06 19:35 UTC, mgoelswirlds commented on docs/configuration.md
> +| Name                                                              | Default                 | Description
ok.

2023-12-06 19:56 UTC, mgoelswirlds commented on docs/configuration.md
> +| Name                                                              | Default                 | Description
Working on it. But to make it simpler , we can hide whitespaces , which shows only the changed line for this particular file.

2023-12-06 21:35 UTC, xin-hedera approved these changes
LGTM

2023-12-07 00:53 UTC, merged