HIP-584 Historical: DB queries for historical crypto and token allowances
hashgraph/hedera-mirror-node pull request #7209
Opened 2023-11-17 07:51 UTC by bilyana-gospodinova

**Description**:
For historical support we need to extend db queries to have a timestamp filter.
Using this filter we can obtain records based on a historical block passed in eth_call.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/7053

2023-11-20 17:52 UTC, xin-hedera requested changes

2023-11-22 14:37 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
I checked PR https://github.com/hashgraph/hedera-mirror-node/pull/6722. In `EntityRecordItemListener#insertTokenTransfers` (rows 536-552) it seems that the token allowances are decreased directly by the amount of the token transfers that were made. The `transferSpenderId` could be the payer account id or the contract result sender id but regardless the token allowances should have the correct amount at the end of the record file import. I think that in the query we do not need to subtract the transfers at all as they were already subtracted on import. In summary, the query should return only the latest token allowances for the given owner partitioned by (spender, tokenId) up to the passed block timestamp and having amount_granted <> 0. What do you think about that?

2023-11-22 15:17 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CryptoAllowanceRepository.java
> +    List<CryptoAllowance> findByOwnerAndTimestamp(long owner, long blockTimestamp);
Comment addressed.

2023-11-22 15:18 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CryptoAllowanceRepository.java
> +                        where row_number = 1
Comment addressed.

2023-11-22 16:03 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
If we subtract the tranferred amount from the amountGranted in the query won't that duplicate the logic in `EntityRecordItemListener#insertTokenTransfers` (rows 536-552)?

2023-11-22 16:24 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
no, the importer logic changes `amount` not `amountGranted`

2023-11-22 17:34 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
Perhaps this is a clearer explanation.

Assume there is an old token allowance,

- amountGranted = 100
- amount = 20
- timestamp range = `[t1, t2)`

and when the repo function is called to provide the token allowance as of a certain block timestamp `t3`, where `t1 < t3 < t2`, we need to compute `amount` as `amountGranted - total amount using the allowance in [t1, t3]`.

Suppose the last such token transfer using the above allowance happened at time `t4`, where `t1 < t4 < t2`, the `amount` in db is only accurate for the timestamp range `[t4, t2)`. For the corner case that the allowance is never used, `amount` will be equal to `amountGranted` and be valid for `[t1, t2)`.

2023-11-22 18:41 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CryptoAllowanceRepository.java
> +                        select amount_granted, owner, payer_account_id, spender, timestamp_range, amount_granted - coalesce((select amount from transfers tr where tr.spender = ca.spender), 0) as amou
missed in the previous review, amount should be

`amount_granted + coalesce((select amount from transfers tr where tr.spender = ca.spender), 0)`

Note, the only difference is change `-` to `+`, because the amount of a transfer using allowance is a debit, the amount is negative.

2023-11-22 21:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
For the scope of the historical block support, when we have a given historical `block X` with timestamp `[t1, t2)`, we need to use the state of the block after all transactions inside have been processed. That means we are interested in the correct allowance value at point `t2`, which is the `block_end` timestamp. We don't need any intermediate values.

2023-11-22 21:28 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
Probably this means we should get the closest `token_allowance` record to `t2` timestmap (`block_end`) and use it's `amount` value? That would be the allowance left at this point in time?

2023-11-23 00:54 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
We don’t have such record.

a new token allowance row is only inserted when amount_granted changes, aka, from user submitted crypto approve allowance tx.

when a user spends the allowance, the changes to the remaining amount is accumulated and the result is *updated* to the existing row.

2023-11-23 08:17 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CryptoAllowanceRepository.java
> +     * It takes into account the crypto transfers that happened up to the given block timestamp, sums them up
Тhe transfers included should be up to the end of the block (`block_end`).

2023-11-23 13:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
The query is updated to take into account the token transfers.

2023-11-24 14:47 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, coalesce(amount - coalesce((select amount from transfers tr where tr.token_id = ta.toke
It seems that due to citus distribution limitations I can't make a direct join between the contract_result and token_transfer tables so I divided the subquery for that in two separate subqueries.

2023-11-29 18:44 UTC, xin-hedera requested changes

2023-11-29 18:44 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                        from token_allowances ta
the main issue in the logic is, the token transfer using allowance from `token_transfer` table assuming `payer_account_id` is the `spender` and those with corresponding contract call results so `contract_result.sender_id` is the `spender` are not a one or the other relationship,  which however is assumed in the coalesce:

`coalesce(amount from contract_call_transfers, amount from token_transfer, 0)`

The other obvious issue is for a token transfer `(account_id = a, consensus_timestamp = c, payer_account_id = p, token_id = t, is_approval = true)`, when it's from a contract all with `contract_call.sender_id = s` and `s <> p`, we may end up counting the transfer amount twice

- to the token allowance `(owner = a, spender = p, token = t)`
- and the token allowance `(owner = a, spender = s, token = t)`

With all the complexity in this query as well as potential performance issues,  I think it's worth to add a `spender` column to `token_transfer` and let importer set the correct value, @steven-sheehy ?

2023-12-04 14:30 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                        from token_allowances ta
Comment addressed. I added also another junit test for this case.

2023-12-05 05:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                        from token_allowances ta
Can consider that for a future optimization. We might also consider ways to pre-calculating the per timestamp allowance amount on the token_transfer.

2023-12-05 05:40 UTC, steven-sheehy submitted a review, later dismissed

2023-12-05 09:41 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-12-05 21:38 UTC, xin-hedera requested changes

2023-12-05 21:38 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                        ) as amount
the `coalesce` will fail hard in real environment.

coalesce expects the individual values to be a single column from a single row.

however, here we have `contract_call_transfers` coming from a query with `group by cr.sender_id, tt.token_id, tt.consensus_timestamp`, obviously the subquery in the coalesce can return multiple rows

similarly, the second coalesce has a subquery on CTE `transfers` as a result of a query with `group by tt.token_id, tt.payer_account_id, tt.consensus_timestamp`.

In both places, `sum(amount)` is needed.

2023-12-05 21:38 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            )
remove the `contract_results_filtered` CTE, it's only used in `contract_call_transfers` and the where condition already takes care of `consensus_timestamp < :blockTimestamp and cr.consensus_timestamp = tt.consensus_timestamp`.

It may actually improve performance since in `contract_call_transfers` the timestamp is transitively limited in the range `(lower(ta.timestamp_rangge), blocktimestamp]`

2023-12-05 21:38 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAllowanceRepositoryTest.java
> +                .persist();
it doesn't match the data produced by consensus nodes, there shouldn't be two identical rows in `token_transfer` table. (we used to have `(consensus_timestamp, token_id, account_id)` as the primary key however we relaxed it later). Please change them to be two token transfers using allowance at different consensus timestamp.

this is also why the coalesce issue I pointed out didn't get exposed.

2023-12-05 22:38 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAllowanceRepositoryTest.java
> +                .persist();
update: I obviously put the comment to the wrong test case, it should apply to `findByOwnerAndTimestampWithTransferMultipleEntries`

2023-12-05 23:40 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            )
update: I may have missed the fact that the CTE is due to citus limit. If so, please disregard the change request.

2023-12-06 07:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                            )
Exactly, the CTE is due to the citus limit.

2023-12-06 07:35 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAllowanceRepositoryTest.java
> +                .persist();
Nice catch. Thank you! Comment addressed.

2023-12-06 07:37 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> +                        ) as amount
Comment addressed.

2023-12-06 17:21 UTC, merged