HIP-584: Extract MirrorEvmTxProcessor as a singleton bean
hashgraph/hedera-mirror-node pull request #7211
Opened 2023-11-17 17:17 UTC by IvanKavaldzhiev

**Description**:

This PR reduces greatly the CPU usage utilized by the web3 module and reduces memory footprint as well.
It extracts additional spring singleton beans and makes `MirrorEvmTxProcessor` a singleton as well. That's the most heavy object used by the web3, so it's important to make it performant.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-17 21:59 UTC, steven-sheehy requested changes

2023-11-17 21:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
>      public static class Updater extends AbstractLedgerWorldUpdater<HederaEvmMutableWorldState, Account>
Some of the parent classes have state. Don't think we can make singleton

2023-11-17 21:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
>  public class HederaEvmStackedWorldStateUpdater
Some of the parent classes have state. Don't think we can make singleton

2023-11-17 21:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +                dynamicProperties.fundingAccountAddress());
Don't think this needs to be passed via method params. The parent already has EvmProperties so can call it directly.

2023-11-17 21:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +public class HederaEvmTxProcessor {
Needs javadoc outlining changes from services

2023-11-17 21:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +                contractCallContext.setTransactionBody(precompile.body(
Should move context updating outside the switch so we don't repeat ourselves like other reviewer recommended.

2023-11-17 21:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractWritePrecompile.java
> +    public long getGasRequirement(long blockTimestamp, final TransactionBody.Builder transactionBody) {
In a future PR, we need to revert adding transactionBody to this method and get it from context.

2023-11-17 22:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
>  public class HederaEvmStackedWorldStateUpdater
I think you're right. Then we should declare them as factory beans in the EvmConfiguration.

2023-11-20 16:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldState.java
>      public static class Updater extends AbstractLedgerWorldUpdater<HederaEvmMutableWorldState, Account>
Fixed

2023-11-20 16:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
>  public class HederaEvmStackedWorldStateUpdater
Fixed.

2023-11-20 16:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +                dynamicProperties.fundingAccountAddress());
Fixed

2023-11-20 16:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +public class HederaEvmTxProcessor {
Fixed

2023-11-20 22:42 UTC, steven-sheehy approved these changes
LGTM

2023-11-21 01:14 UTC, merged