HIP-584 Historical: Adapt DB Accessors to work with timestamp filters
hashgraph/hedera-mirror-node pull request #7242
Opened 2023-11-22 10:37 UTC by 0xivanov

**Description**:
Adapt DB Accessors to work with timestamp filters by using the ContractCallContext's record file timestamp if it is set. If not - use the non-historical queries.

**Related issue(s)**:

Fixes #6813

**Notes for reviewer**:
This PR is using https://github.com/hashgraph/hedera-mirror-node/pull/7209 implementation for some of the queries.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-22 10:48 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAllowanceDatabaseAccessor.java
> +                        .findByOwnerAndTimestamp(tokenAllowanceId.getOwner(), timestamp)
We should probably have an alternative query for `findById`

2023-11-22 10:59 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        final var timestamp = (historicalRecordFile != null) ? historicalRecordFile.getConsensusEnd() : -1;
Better if -1 is defined as a constant.

2023-11-22 12:08 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        final var cryptoAllowances = (timestamp != -1)
One suggestion for improved readability

create a boolean method useHistorical() or something like that which will contain this logic timestamp != -1, and use it like that

return useHistorical() ? getHistoricalCryptoAllowancesByOwner() : getCryptoAllowancesByOwner()

getHistoricalCryptoAllowanceByOwner() and getCryptoAllowanceByOwner() will call the respective repository method.

This suggestion can almost everywhere where we use timestamp != -1

2023-11-23 13:48 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +    long countByAccountIdAndTimestampNotDeleted(long accountId, long blockTimestamp);
Note that queries marked with `TODO` are valid, but are not covering the edge cases. I will modify them if when we clarify if they are needed.

2023-11-23 14:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +    private Optional<Entity> getEntityByNonMirrorAddress(byte[] addressBytes, long timestamp) {
getEntityByNonMirrorAddress -> getEntityByEvmAddress

2023-11-23 14:58 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        final var timestamp = (historicalRecordFile != null) ? historicalRecordFile.getConsensusEnd() : -1;
Fixed, check out the abstract db accessor

2023-11-23 14:58 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAllowanceDatabaseAccessor.java
> +        final var timestamp = (historicalRecordFile != null) ? historicalRecordFile.getConsensusEnd() : -1;
Calling `ContractCallContext.get().getRecordFile()` in all database accessors for each separate thread would be redundant and CPU heavy operation.

Move this logic into `ROCachingStateFrame.get()` method and pass the timestamp as an argument in the get() method of each `DatabaseAccessor`. In this way we would call `getRecordFile` only once and have a cleaner and more performant code.

2023-11-23 14:59 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        final var cryptoAllowances = (timestamp != -1)
Moved some logic in the abstract db accessor. Didn't implement it exactly as you suggested, but i think the readability is better now.

2023-11-23 15:15 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAllowanceDatabaseAccessor.java
> +        final var timestamp = (historicalRecordFile != null) ? historicalRecordFile.getConsensusEnd() : -1;
I think we can go this in `DatabaseBackedStateFrame`.
This class is not a bean and can store the timestamp as a field.
I don't think that moving the logic into another method would fix the issue though, because the flow still goes through ROCachingStateFrame.getValue for every DBAccessor if i'm not mistaken

2023-11-24 16:43 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAllowanceDatabaseAccessor.java
> +        final var timestamp = (historicalRecordFile != null) ? historicalRecordFile.getConsensusEnd() : -1;
This would need some modifications to work because we first initialise the stacked frames and THEN we query the record file and timestamp afterwards. I've modified the `ContractCallService` to first query record file if needed and initialise the frames with the timestamp.

2023-11-30 05:17 UTC, steven-sheehy requested changes

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CustomFeeRepository.java
> +                select * from custom_fee_history where token_id = ?1
Need to order desc and limit 1 the history

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CustomFeeRepository.java
> +            where timestamp_range < int8_range(?2, null)
Can use lower and <=. Also need to push this into the sub-queries instead of having in the outer.

```suggestion
            where lower(timestamp_range) <= ?2
```

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +    Optional<NftAllowance> findByIdAndTimestamp(long tokenId, long blockTimestamp);
The primary key for nft_allowance is token_id + owner + spender so need to pass all 3 and filter appropriately if you want to have a deterministic response.

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    join Entity e on e.id = n.token_id
Use all lowercase

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    select count(*) from Nft n
There's a nft_history table that has to be considered to provide accurate numbers.

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                     is true group by balance>0
Bad syntax `is true` present

2023-11-30 05:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                    select count(*) as tokenCount, balance>0 as isPositiveBalance from token_account
Also have to look at token_account_history

2023-11-30 15:03 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/CustomFeeRepository.java
> +                select * from custom_fee_history where token_id = ?1
Will be fixed in https://github.com/hashgraph/hedera-mirror-node/pull/7269/

2023-12-01 00:43 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +                : contractStateRepository.findStorage(entityId, key.toArrayUnsafe());
Well I meant not called explicitly but via store mechanism. Just a possible suggestion for a future PR.

2023-12-01 11:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        // Get the top frame from stackedStateFrames
This operation does more than getting the top frame.

You can define a private method that returns directly the `DatabaseBackedStateFrame` and use it in this method by fetching the timestamp directly from its result.

2023-12-11 11:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +    Optional<NftAllowance> findByIdAndTimestamp(long tokenId, long blockTimestamp);
fixed

2023-12-11 11:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenAllowanceDatabaseAccessor.java
> +                        .get(0))
fixed

2023-12-11 11:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +        return customFeeOptional.map(customFee -> mapCustomFee(customFee, timestamp));
refactored the logic to use Optional

2023-12-11 11:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/CustomFeeDatabaseAccessor.java
> +                : customFeeRepository.findById((Long) tokenId);
Fixed

2023-12-11 11:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        long timestamp = DatabaseAccessor.UNSET_TIMESTAMP;
fixed

2023-12-11 11:36 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +        try (ContractCallContext ctx = init(store.getStackedStateFrames(), timestamp)) {
I decided to split up the stackedState and recordFile setting into 2 different methods

2023-12-11 11:36 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                    select count(*) from Nft n
fixed

2023-12-11 11:36 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                     is true group by balance>0
fixed

2023-12-11 11:37 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAccountRepository.java
> +                    select count(*) as tokenCount, balance>0 as isPositiveBalance from token_account
fixed

2023-12-11 11:37 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java
> +        // Get the top frame from stackedStateFrames
the comment was supposed to be 2 lines below

2023-12-11 11:39 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +                : contractStateRepository.findStorage(entityId, key.toArrayUnsafe());
noted and will implement this in the future (if possible)

2023-12-11 11:56 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/DatabaseAccessor.java
> +    public abstract Optional<V> get(@NonNull final K key, final long timestamp);
I'm uncertain if it's beneficial to pass the entire context, including the ThreadLocal object, to every thread as it might lead to significant memory consumption. Currently, we transmit a small object like Optional<Long>. Instead, extracting the necessary information directly from the thread local might be more efficient. After all, wasn't the purpose of using thread locals to avoid passing large objects around?

2023-12-11 12:24 UTC, 0xivanov commented on hedera-mirror-test/README.md
> -|----------------------------------------------------------------|----------------------------------------------|--------------------------------------------------------------------------------------
spotlessApply modified the files from the test module

2023-12-11 16:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/DatabaseAccessor.java
> +    public abstract Optional<V> get(@NonNull final K key, final long timestamp);
Java is pass by value reference. So passing around an object does not lead to any increase in memory consumption since it is stored in one place on the heap and only a reference is on the stack. A 64-bit long timestamp on the stack is the same size as a 64-bit reference to a `ContractCallContext`. So only when you extract a second field from the context and pass it around with the timestamp are you actually increasing memory.

`ThreadLocal` is in general a very bad practice for application code to use. We should eventually get rid of it once we switch to modularized code which is hopefully mostly stateless. That said, we can keep it as is and refactor once we see the need for a second parameter.

2023-12-12 14:37 UTC, kselveliev submitted a review, later dismissed
LGTM

2023-12-13 01:07 UTC, steven-sheehy requested changes

2023-12-13 01:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +                            () -> nftRepository.findActiveById(nftId.tokenId().getTokenNum(), nftId.serialNo()))
These types differ. Need to use `EntityId.of(shard, realm, tokenNum).getId()` to convert to database type properly. Maybe add another helper to `EntityIdUtils`.

2023-12-13 07:37 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +                            () -> nftRepository.findActiveById(nftId.tokenId().getTokenNum(), nftId.serialNo()))
You mean that there is an error in the original code? Should use             
`EntityId.of(nftId.shard(), nftId.realm(), nftId.num()).getId()` instead of `nftId.num()` for the id?

2023-12-13 09:07 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                ctx.initializeStackFrames(store.getStackedStateFrames());
We could support it even right now. Only the record file would need to be set in the context prior to initializing the stacked frames.

2023-12-13 09:08 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                ctx.initializeStackFrames(store.getStackedStateFrames());
The usefulness of this operation is another question though...

2023-12-13 09:16 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                ctx.initializeStackFrames(store.getStackedStateFrames());
Currently we won't support historical eth_estimateGas. It would be a very rare case a user would execute such an operation. The more practical way of doing things would be invoking the `debug_traceTransactions` operation, which is next on the queue.

2023-12-13 10:54 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessor.java
> +                .orElseGet(() -> entityRepository.findByIdAndDeletedIsFalse(entity.getAutoRenewAccountId()))
done

2023-12-13 10:55 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    recordFileOptional = findRecordFileByBlock(block);
reverted

2023-12-13 10:55 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +        if (stackedStateFrames != null) {
done

2023-12-13 13:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +                            () -> nftRepository.findActiveById(nftId.tokenId().getTokenNum(), nftId.serialNo()))
Right

2023-12-13 13:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static EntityId entityIdFromUftId(NftId id) {
entityIdFromNftId

2023-12-13 15:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +                return getEntityByMirrorAddress(address, timestamp);
getEntityByMirrorAddress -> getEntityByMirrorAddressAndTimestamp

2023-12-13 15:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +                return getEntityByEvmAddress(addressBytes, timestamp);
getEntityByEvmAddress -> getEntityByEvmAddressAndTimestamp

2023-12-13 16:27 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/UniqueTokenDatabaseAccessor.java
> +            final var tokenId = EntityIdUtils.entityIdFromUftId(nftId).getId();
done

2023-12-13 16:27 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +                return getEntityByEvmAddress(addressBytes, timestamp);
done

2023-12-13 16:27 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/EntityDatabaseAccessor.java
> +                return getEntityByMirrorAddress(address, timestamp);
done

2023-12-13 16:27 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static EntityId entityIdFromUftId(NftId id) {
done

2023-12-13 16:51 UTC, steven-sheehy approved these changes
LGTM

2023-12-13 21:23 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-12-13 22:38 UTC, merged