HIP-584 Historical: Load EVM Configuration based on block number
hashgraph/hedera-mirror-node pull request #7314
Opened 2023-12-04 15:27 UTC by kselveliev

**Description**:

This PR implements the following feature:

When a historical call is made:

Based on the block number passed in the request body we need to load 
 proper evm version and proper precompiles that existed during that block snapshot.

In order to do that we the first thing we need to do is to create a yaml config.
Example yaml config:
<img width="599" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/0d8db74c-a3b6-4c0b-aef6-304196449c46">

This yml config will be present only in mainnet
The values from the yaml config should be taken from mainnet this snippet contains example values.

Explanation of yaml:

**system precompiles**: represents a list of precompiles and the block in which they appeared for the first time.
For example HTS precompiles appeared in block 600 (the real values on mainnet will be different).

**evm_version**: represents a list of evm version and in which block they appeared for the first time.
For example evm version 0.34 appeared in block 2000 (the real values on mainnet will be different)

Based on system precompiles and evm version we can create a combination with which we 
can load proper evm config as it was during the historical block a user passes.

For example: A user passed block 750, we then read from our evm versions and precompiles
we see that for that version we need to load lowest evm version 0.30 with support for precompiles ERC, HTS and exchangeRate.

Example 2: A used passed block 2100, we read from our evm versions and precompiles we 
see that for that  version we need to load evm version 0.34 with support for precompiles  
ERC,HTS,exchangeRate and PRNG.

How this works:
A new class is introduced **EvmPropertiesInitializer** which is responsible for reading yaml config
on application startup.

It then creates a map which maps evm with precompiles for every evm version it adds all the precompiles that are supported in this evm version

This map is loaded into **MirrorNodeEvmProperties**. Then based on block number we find the proper evm config we need to load.

Added documentation for **EvmPropertiesInitializer** methods.

Important changes are introduced in **EvmConfiguration.java** 

(messageCallProcessors). There we construct a map of messageCallProcessors

map - evm version to messageCallProcessor

Introduce new **MessageCallProcessor** beans based on precompile combinations.
Each messageCallProcessor contains an evm config and **PrecompileHolder**.

**PrecompileHolder** is a bean which contains the config for which precompiles are supported.
Every custom **MessageCallProcessor** has a custom PrecompileHolder.

**PrecompileHolder** uses a **PrecompiledContract**.
For every custom **PrecompileHolder** we have a corresponding **PrecompiledContract**.

Every custom **PrecompiledContract** has a custom **PrecompiledMapper**.

**PrecompiledMapper** contains the set of precompile selectors available for it.

(**PrecompileMapper** is used for ERC, HTS and HRC)

Exchange rate and Prng are directly put into the **PrecompileHolder**. They do not use **PrecompileMapper**.

**IMPORTANT NOTE:**

During a call with historical block, custom evm loading is triggered in **HederaEvmTxProcessor**.java.

During **HederaEvmTxProcessor.process()** we load the proper evm version config in 

**getMessageProcessor**() method. 

There we pass the evm version which we will be using and we do the following check.

      If ( we are working with historical block) {

      Get the historical block number

      Get all precompiles available at that block number

      Create a key based on evm version and precompiles

      get custom message call processor by key 

      (example key → v0.30-ERC,HTS)

      v0.30-ERC,HTS will load message call processor with evm version 0.30 and supported ERC and HTS precompiles 

      (In case yaml config is not populated and we do not have evm precompile combinations we work with the default evm 
      version in MirrorNodeEvmProperties)

      }

**Classed removed in PR**

Removed **HTSPrecompiledContractAdapter**.java

Removed **MirrorHTSPrecompiledContract**.java

Added unit tests for the newly create classes:

**Related issue(s)**:

Fixes #7051

**Checklist**

- [ x ] Documented (Code comments, README, etc.)
- [ x ] Tested (unit, integration, etc.)

2023-12-04 16:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorErcHts.java
> +public class MirrorEvmMessageCallProcessorErcHts extends HederaEvmMessageCallProcessor {
We can keep only this processor for both `HTS` and `ERC` precompiles and have special checks in the `PrecompileMapper` and `HTSPrecompiledContract` for the ERC mappings.

2023-12-04 16:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorErc.java
> +public class MirrorEvmMessageCallProcessorErc extends HederaEvmMessageCallProcessor {
Probably we can use only `MirrorEvmMessageCallProcessorErcHTS`

2023-12-04 16:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorErcHtsExchangeRate.java
> +public class MirrorEvmMessageCallProcessorErcHtsExchangeRate extends HederaEvmMessageCallProcessor {
We can extract a parent class - `MirrorEvmMessageCallProcessor` that contains the common methods to reduce code duplication. Then the different child invariants would just have different constructors.

2023-12-05 11:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        processorsMap.put(EVM_VERSION_0_45, () -> contractCreationProcessor);
For now we can use only one instance of `contractCreationProcessor` and return it for each evm version type. In this way we can save memory.

We can define only a single bean with `Provider<ContractCreationProcessor>` type and if we need to pass around a Map, we can construct it in `HederaEvmTxProcessor`.

2023-12-05 11:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/PrecompilesHolderErc.java
> +public class PrecompilesHolderErc {
We can remove this class.

2023-12-05 11:59 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/PrecompilesHolderErcHts.java
> +        hederaPrecompiles.put(EVM_HTS_PRECOMPILED_CONTRACT_ADDRESS, ercHtsPrecompiledContract);
We should use directly `HTSPrecompiledContract`.

2023-12-05 12:02 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/ServicesConfiguration.java
> +    ERCPrecompiledContract ercPrecompiledContract(
We should remove this bean.

2023-12-05 12:02 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/ServicesConfiguration.java
> +    ErcHtsPrecompiledContract ercHtsPrecompiledContract(
Use the already existing HTSPrecompiledContract instead.

2023-12-05 12:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private TreeMap<String, Long> evmVersions = new TreeMap<>();
evmVersions -> evmVersionToBlockNumber

2023-12-05 12:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private Map<String, Set<String>> evmPrecompiles;
evmPrecompiles -> evmVersionToPrecompiles

2023-12-05 12:33 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +     *   <li>Set containing ERC and HTS</li>
It would be more correct to switch the order and all list items to start with HTS since this is the first group of precompiles that we have started supporting.

2023-12-05 12:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +            return evmVersion + "-" + ERC;
evmVersion + "-" + HTS

2023-12-05 12:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        if (precompileSet.equals(Set.of(ERC))) {
Set.of(HTS)

2023-12-05 12:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +            evmVersion = MirrorNodeEvmProperties.getEvmWithPrecompiles(evmVersion, precompilesAvailable);
Why do we need the evm version here to be appended with precompiles?

2023-12-05 12:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/ERCPrecompiledContract.java
> +public class ERCPrecompiledContract extends PrecompiledContractBase {
Shouldn't make such deviations in the copied code from services. We can utilize the `HTSPrecompiledContract`.

2023-12-05 12:53 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +public class HTSPrecompiledContract extends PrecompiledContractBase {
Based on my other comments, I believe we should revert all changes in this file.

2023-12-05 12:54 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/PrecompileMapper.java
Should keep this `PrecompileMapper` as it is and reuse it.

2023-12-05 12:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/PrecompiledContractBase.java
> +public abstract class PrecompiledContractBase extends EvmHTSPrecompiledContract {
We can get this code back to `HTSPrecompiledContract`.

2023-12-05 12:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompileMapperUtils.java
> +    public static final Set<Integer> ERC_PRECOMPILE_SELECTORS = Set.of(
We can use this `Set` for excluding ERC precompile execution in `MirrorEvmMessageCallProcessor` if we have a block that does not support them.

2023-12-05 13:02 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorErcHts.java
> +public class MirrorEvmMessageCallProcessorErcHts extends HederaEvmMessageCallProcessor {
We can follow the same logic for inclusion/exclusion for the HRC precompiles.

2023-12-06 14:29 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorErc.java
> +public class MirrorEvmMessageCallProcessorErc extends HederaEvmMessageCallProcessor {
Comment addressed, we use MirrorEvmMessageCallProcessorHtsErc now.

2023-12-06 14:30 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/PrecompilesHolderErc.java
> +public class PrecompilesHolderErc {
Comment addressed. This class is removed.

2023-12-06 14:30 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/PrecompilesHolderErcHts.java
> +        hederaPrecompiles.put(EVM_HTS_PRECOMPILED_CONTRACT_ADDRESS, ercHtsPrecompiledContract);
Comment addressed, we now only use HTSPrecompiledContract

2023-12-06 14:31 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/ServicesConfiguration.java
> +    ERCPrecompiledContract ercPrecompiledContract(
Comment addressed.

2023-12-06 14:35 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private TreeMap<String, Long> evmVersions = new TreeMap<>();
MirrorNodeEvmProperties is bound to the yaml config, if we want to do that name change we will need to change naming in yaml file. system_precompiles in yaml is read as systemPrecompiles in java class.

<img width="644" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/a2a08541-9c43-40ef-8fe1-518b9509c681">

2023-12-06 14:35 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private Map<String, Long> systemPrecompiles = new HashMap<>();
Same as [above](https://github.com/hashgraph/hedera-mirror-node/pull/7314#discussion_r1417425401)

2023-12-06 14:37 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +     *   <li>Set containing only ERC</li>
Comment addressed.

2023-12-06 14:39 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +            return evmVersion + "-" + ERC;
Comment addressed. After the latest refactoring the combinations of ERC and HTS changes are removed since they are both introduced before evm 0.30

2023-12-06 14:40 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/ERCPrecompiledContract.java
> +public class ERCPrecompiledContract extends PrecompiledContractBase {
Comment addressed. We are only using HTSPrecompiledContract now.

2023-12-06 14:40 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/PrecompileMapper.java
Comment addressed, we are keeping the PrecompileMapper.

2023-12-06 14:43 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +     *   <li>Set containing ERC and HTS</li>
Comment addressed. This javadoc is changed after refactoring.

2023-12-06 14:44 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/ServicesConfiguration.java
> +    ErcHtsPrecompiledContract ercHtsPrecompiledContract(
Comment addressed. We are only using HTSPrecompiledContract now.

2023-12-06 14:44 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        if (precompileSet.equals(Set.of(ERC))) {
Comment addressed. This combination is removed after the latest refactoring.

2023-12-06 16:11 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private Map<String, Set<String>> evmPrecompiles;
Comment addressed

2023-12-06 16:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +public class HTSPrecompiledContract extends PrecompiledContractBase {
Comment addressed. I reverted the changes in HTSPrecompiledContract

2023-12-07 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorExchangeRate.java
> +            final PrecompilesHolderHtsErcExchangeRate precompilesHolderHtsErc,
precompilesHolderHtsErc -> precompilesHolderHtsErcExchangeRate

2023-12-07 09:04 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorExchangeRate.java
> +            final PrecompilesHolderHtsErcExchangeRate precompilesHolderHtsErc,
Comment addressed

2023-12-07 14:21 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +            evmVersion = MirrorNodeEvmProperties.getEvmWithPrecompiles(evmVersion, precompilesAvailable);
This code was removed after latest refactoring

2023-12-08 20:44 UTC, steven-sheehy requested changes

2023-12-08 20:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private TreeMap<String, Long> evmVersions = new TreeMap<>();
Invert the key and value then you can use `evmVersions.floorEntry(blockNum)` to efficiently find the value instead of looping.

```suggestion
    private NavigableMap<Long, String> evmVersions = new TreeMap<>();
```

2023-12-08 20:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private TreeMap<String, Long> evmVersions = new TreeMap<>();
Prefer `evmVersions`

2023-12-08 20:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/resources/application.yml
> +          v0.45:
We should omit empty config from yaml. Move mainnet config to java. These are the values for mainnet which we should populate on HederaNetwork:
```
mirror_node=> select hapi_version_minor, min(consensus_end), max(consensus_end) from record_file where hapi_version_major = 0 and hapi_version_minor in (30, 34, 38, 45) group by hapi_version_minor;
 hapi_version_minor |         min         |         max         
--------------------+---------------------+---------------------
                 30 | 1666368347153861003 | 1670605199011072003
                 34 | 1675962001984524003 | 1680282000110196003
                 38 | 1686243920984236003 | 1689091200717666721
(3 rows)
```

2023-12-08 20:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/resources/application.yml
> +          v0.45: 4000
Why do we need these values here? For tests that specifically test it they should set it in `MirrorNodeEvmProperties`.

2023-12-08 20:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
> +public class HTSPrecompiledContract extends EvmHTSPrecompiledContract {
In the future, please put refactoring unrelated to the ticket like this in separate PRs so it's easier to review.

2023-12-11 18:49 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public Provider<ContractCreationProcessor> contractCreationProcessorProvider(
You're right, I've missed that. We don't need to increase scope. I reverted that change

2023-12-11 18:49 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private TreeMap<String, Long> evmVersions = new TreeMap<>();
Comment addressed. Using NavigableMap now.

2023-12-11 18:50 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private TreeMap<String, Long> evmVersions = new TreeMap<>();
Comment addressed. I've inverted the key and value for better search.

2023-12-11 18:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        String closestVersion = evmVersions.firstEntry().getKey(); // Default to the lowest version
If we consider evm version 30 as block 0 and after inverting the key and value as suggested above. Just doing evmVersions.floorEntry(blockNumber); should do the job. I've done that now.

2023-12-11 18:58 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        if (CollectionUtils.isEmpty(evmVersions)) {
I added a hardcoded evm versions map in HederaNetwork for mainnet.
Now it first checks if we have yaml config values - if yes use them.
If not  -> use HederaNetwork hardcoded values 
if HederaNetwork values are empty use default version.

2023-12-11 19:00 UTC, kselveliev commented on hedera-mirror-web3/src/main/resources/application.yml
> +          v0.45:
Comment addressed. I've omited the yaml configs and populated the values in HederaNetwork for mainnet. Since I do no see any result for 45 version I did not add it in the HederaNetwork evm versions map.

2023-12-11 19:01 UTC, kselveliev commented on hedera-mirror-web3/src/test/resources/application.yml
> +          v0.45: 4000
You are right, we don't need that. I've removed this config.

2023-12-11 20:37 UTC, steven-sheehy requested changes

2023-12-11 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private NavigableMap<Long, String> evmVersions = new TreeMap<>();
nit: Sort inline with other fields

2023-12-11 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        }
It would be cleaner to separate getting the map and looking up the value from the map into separate methods. Below I override `getEvmVersions()` so it always has a non-null/non-empty map.

```java
@Override
public NavigableMap<Long, String> getEvmVersions() {
    if (CollectionUtils.isNotEmpty(evmVersions)) {
        return evmVersions;
    }

    if (CollectionUtils.isNotEmpty(network.evmVersions)) {
        return network.evmVersions;
    }

    return Map.of(0L, EVM_VERSION); // Can extract to a constant
}

String getEvmVersionForBlock(long blockNumber) {
    return getEvmVersions().floorEntry(blockNumber);
}
```

2023-12-11 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public static final Long EVM_VERSION_38_START_BLOCK = 49117794L;
Don't think these need to be static class constants or are relevant to this class. Should just embed inline in HederaNetwork. Tests that validate offsets should set a custom evm version map.

2023-12-11 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +            evmVersionsMap.put(EVM_VERSION_38_START_BLOCK, EVM_VERSION_0_38);
Prefer constants inline here for easier readability.

2023-12-11 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesTest.java
> +        properties.setEvmVersions(evmVersions);
I don't think we should test with a repeat of the config for getEvmVersionForBlockFromHederaNetwork. Use a different map that you create to test.

2023-12-11 20:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesTest.java
> +                Arguments.of(EVM_VERSION_38_START_BLOCK + 1000, EVM_VERSION_38));
Instead of this hardcoded approach, we can iterate over map entries and for each value try with key, key - 1, and key + 1. For key-1 we assert value.compareTo(currentValue) < 0.

2023-12-11 20:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        }
Note: getEvmVersionForBlock should be package private instead of public

2023-12-11 20:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +            return EVM_VERSION; // Return default version if no entry matches the block number
Needs test coverage

2023-12-12 14:38 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +            return evmVersionsMap;
Comment addressed. Now returning unmodifiableNavigableMap.

2023-12-12 14:40 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private NavigableMap<Long, String> evmVersions = new TreeMap<>();
Not entirely sure what you meant by this. I just moved the evmVersions map next to evmVersion variable.

2023-12-12 14:43 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        }
Comment addressed. I applied the suggestion. Just did not use the @Override annotation since I encountered problems with lombok if I used it. Also had to add if else logic in getEvmVersionForBlock since getEvmVersions().floorEntry(blockNumber); returns an entry not a string.

2023-12-12 14:45 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        }
Comment addressed. I just did not use override since I had problems with lombok using it. And in getEvmVersionForBlock I had to add if else logic since getEvmVersions().floorEntry(blockNumber); returns an entry and we want the value of the entry.

2023-12-12 14:46 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    public static final Long EVM_VERSION_38_START_BLOCK = 49117794L;
Comment addressed. I removed the constants from EvmConfiguration.

2023-12-12 14:47 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +            return EVM_VERSION; // Return default version if no entry matches the block number
Comment addressed.

2023-12-12 14:57 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesTest.java
> +        properties.setEvmVersions(evmVersions);
I believe here you meant the getEvmVersionForBlockFromConfig method where we can load a custom map.
I added a custom map test for it.
For the HederaNetwork enum I believe it's harder to test with custom map since it is an enum.

2023-12-12 14:58 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesTest.java
> +                Arguments.of(EVM_VERSION_38_START_BLOCK + 1000, EVM_VERSION_38));
I modified the provider so that it test with key-1, key, and key + 1 for all entries in evmVersions

2023-12-12 21:43 UTC, steven-sheehy approved these changes
LGTM

2023-12-12 21:44 UTC, steven-sheehy commented
Just needs @IvanKavaldzhiev approval since he had some comments, then can merge.

2023-12-13 10:39 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-12-13 13:09 UTC, merged