Improve transaction queries in v2
hashgraph/hedera-mirror-node pull request #7336
Opened 2023-12-05 21:50 UTC by jascks

**Description**:
NOTE: This PR is a draft and also very preliminary in development. It's purpose now is to get eyes on the work done thus far and the direction taken. A couple of simple HTTP requests seem to work as expected, but the automated tests are not. yet settled.

This PR improves  V2 performance for the following REST API endpoints:
1. /accounts/{id}
2. /accounts/{id}?timestamp=lte:{timestamp}
3. /transactions
4. /transactions?account.id={accountId}
5. /transactions?transactionType={transactionType} (this one has additional complexities due to the type filter - may warrant a separate issue after the completion of this one)

Note:
the `/accounts/{id}?timestamp=lte:{timestamp}` has additional issues with the timestamp query

**Related issue(s)**:

Fixes #6933

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-12 22:09 UTC, edwin-greene commented on hedera-mirror-rest/transactions.js
> +  if (_.isNil(timestampQueryRows) || timestampQueryRows.length === 0) {
This should work to simplify the undefined and empty check:
```suggestion
  if (_.isEmpty(timestampQueryRows)) {
```

2023-12-14 15:21 UTC, jascks commented on hedera-mirror-rest/transactions.js
> +  if (_.isNil(timestampQueryRows) || timestampQueryRows.length === 0) {
Thanks! That willl be in the next push.

2023-12-14 15:33 UTC, xin-hedera requested changes

2023-12-14 15:33 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const bindTimestampRange = function (tsRange) {
we generally use arrow function

```suggestion
const bindTimestampRange = (tsRange) => {
```

2023-12-14 15:33 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +    }
Isn't the function supposed to limit the range to at most `maxTimestampRangeNs`? Then why would here return the range as is if both `begin` and `end` are not null and not zero?

2023-12-14 15:33 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  }
advancing `begin` or shrinking `end` depends on the order. In addition, you shouldn't change it if the user specified range is less than or equal to `maxTimestampRangeNs`.

2023-12-14 15:33 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/utils.test.js
> +  });
why would you need sinon fake timers? `bindTimestampRange` doesn't rely on Date.now(), right?

2023-12-14 18:18 UTC, jascks commented on hedera-mirror-rest/utils.js
> +const bindTimestampRange = function (tsRange) {
👍

2023-12-14 18:27 UTC, jascks commented on hedera-mirror-rest/utils.js
> +    }
Back when I first wrote this, I was only concerned about the range being bound. In this case it is bound by the client, though the range could be wide and involve numerous partitions. Please see follow up in below comment.

2023-12-14 18:27 UTC, jascks commented on hedera-mirror-rest/utils.js
> +  }
Here the range was not fully bound by the client or else the function would have already returned. So, begin or end or both is not defined. There is no shrinking going on per se. But, in regards to the comment above, where both ends are defined by the client, it sounds like shrinking needs to occur, based on the order and `maxTimestampRangeNs`.

2023-12-14 18:32 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  }
that's not true because

- we should still bound the range even it's a closed range by the user since it can be really large
- there is bug on line 678 - 680 for a range `[begin, end]` when both are not null and at least one is 0, simply because `(0 && any value)` evaluates to false

2023-12-14 20:48 UTC, jascks commented on hedera-mirror-rest/utils.js
> +    }
Limit in place.

2023-12-14 20:48 UTC, jascks commented on hedera-mirror-rest/utils.js
> +  }
Okay, I think I have resolved both bullet points now.

2023-12-14 21:38 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return queryTsRange;
This has become even more complicated due to many nested if.. else.. conditionals.

I still need to review the changes in `transactions.js` to have a full picture. However I believe it can be simplified if we require `tsRange` has both begin and end.

To achieve that, we can default tsRange to `[0, MAX_LONG]` and change the values to reflect what's passed in the request URL.

In the function, the algorithm then becomes:

```
if (end === MAX_LONG) {
  end = NOW;
}

if (end - begin <= maxTimestampRangeNs) {
  return tsRange;
}

if (order == 'desc') {
  begin = end - maxTimestampRangeNs;
} else {
  end = begin + maxTimestampRangeNs;
}

return tsRange;
```

2023-12-14 21:58 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return queryTsRange;
follow-up, there's obvious one-off problem in the algorithm in my comment in case both ends of the range are inclusive, i.e., for a range in the form `[begin, end]` the number of discrete timestamp values should be `end - begin + 1`

2023-12-19 20:08 UTC, jascks commented on hedera-mirror-rest/transactions.js
> +  if (_.isNil(timestampQueryRows) || timestampQueryRows.length === 0) {
Done

2023-12-19 20:09 UTC, jascks commented on hedera-mirror-rest/utils.js
> +const bindTimestampRange = function (tsRange) {
Done

2023-12-19 20:19 UTC, jascks commented on hedera-mirror-rest/__tests__/transactions.test.js
> +        field: 'consensus_timestamp',
Oops. Was trying to cause test to fail which it wouldn't. Ignore for now.

2023-12-19 20:20 UTC, jascks commented on hedera-mirror-rest/__tests__/transactions.test.js
> +    checks1: [{field: 'entity_id', operator: '>=', value: 1111}],
While I created checks1 and checks2, these tests have not yet been modified otherwise.

2024-01-08 22:40 UTC, jascks commented
This PR has been superseded by #7503. The comments in this PR are still relevant, but work continues in the new PR.

2024-01-08 22:40 UTC, closed without merging