Add in-equivalence tests for balance, selfdestruct, ext op codes
hashgraph/hedera-mirror-node pull request #7342
Opened 2023-12-07 12:25 UTC by yiliev0

**Description**: This PR introduces tests related to balance, selfdestruct, extcodesize, extcodecopy and extcodehash op codes testing system accounts behaviour. This is a partial coverage of this ticket -> https://github.com/hashgraph/hedera-mirror-node/issues/7193 as more op code tests will be introduced in seperate PR's.

**Related issue(s)**:

Fixes #7193

**Notes for reviewer**: Be advised the @acceptance tag is not added due to couple of reasons:
* These tests consumes a lot of hbars(551ℏ to run) and it will significantly change the total cost.
* Currently these tests are only verifying consensus node behaviour. Later on, we will introduce more tests that would verify the mirror node evm behaviour once this [change](https://github.com/hashgraph/hedera-services/issues/9459) is added.(we might add acceptance tag only for them as they will verify the mirror node behaviour)

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-07 19:46 UTC, steven-sheehy requested changes
I think this PR (and its related one) are going in the wrong direction. I am against using mirror node acceptance tests to test consensus node functionality. Mirror node acceptance tests are purely for verifying mirror node functionality during mirror node rollouts. It should only interact with HAPI minimally so that transactions flow to mirror node. It wouldn't make sense to fail a mirror node upgrade because HAPI had some regression.

That said, if we can structure the code in such a way that it's the same feature/code that calls both consensus node and mirror node with the same input and the call to HAPI can be disabled via a feature flag, then I am open to considering that. But if we have to have different methods for each then that would not be maintainable.

2024-01-04 18:54 UTC, steven-sheehy commented
It's not clear to me if this PR is ready for re-review or is still in draft. Can we mark it as draft if it is or request re-review if it's not?

2024-01-04 19:28 UTC, yiliev0 commented
Waiting on this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/7443) to get finalized, so we can move on with this one. Converting it to draft until then.

2024-01-26 01:39 UTC, steven-sheehy requested changes

2024-01-26 01:39 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/equivalence.feature
> +      | "MIRROR"    |
Perhaps instead of this being a data table where it's commented out until need we just make it a spring property with a default of mirror?

2024-01-26 11:26 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EncoderDecoderFacade.java
> +@Named
Removed.

2024-01-26 11:27 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EncoderDecoderFacade.java
> + * Copyright (C) 2023 Hedera Hashgraph, LLC
Now it should be okay.

2024-01-26 11:27 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/equivalence.feature
> +      | "0.0.999"   | "MIRROR"    |
I've limited the accounts. They are testing various system account ranges.

2024-01-26 11:29 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/equivalence.feature
> +      | "MIRROR"    |
Done. I've added an additional property in the application.yaml.

2024-01-26 15:40 UTC, steven-sheehy requested changes

2024-01-26 15:40 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private NodeNameEnum nodeType;
Remove default from `application.yml` and move to here. Also document in config table in `hedera-mirror-test/README.md`.

```suggestion
    private NodeNameEnum nodeType = NodeNameEnum.MIRROR;
```

2024-01-27 00:46 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private NodeNameEnum nodeType;
Now it should be okay.

2024-01-27 02:01 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private NodeNameEnum nodeType;
Extra semicolon and didn't update docs

2024-01-29 07:08 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
> +    private NodeNameEnum nodeType;
Removed the extra semicolon and updated the docs.

2024-01-29 15:50 UTC, steven-sheehy approved these changes
LGTM

2024-01-29 15:51 UTC, merged