Update contract state endpoint to support slot parameter in any order
hashgraph/hedera-mirror-node pull request #7346
Opened 2023-12-07 19:59 UTC by edwin-greene

**Description**:
The contract state REST API now supports the slot parameter in any order.

**Related issue(s)**:

Fixes #7240 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-12-07 21:41 UTC, xin-hedera requested changes

2023-12-07 21:41 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      const slot = utils.formatSlot(slotFilter.value, timestampPresent);
believe this will break existing logic.

Put aside that there is bug in how slot was formatted.

The original logic supports when `timestamp` appears first and slot has odd number of digits, e.g., `0x3`, `0x103`.

The change you made is going to break it.

I think you should fix `formatSlot` so when leftPad is `true` it does what's originally done by
```
  formatSlot(formatSlot(slot), true);
```

2023-12-08 20:27 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +      const slot = utils.formatSlot(slotFilter.value, timestampPresent);
Thanks. I updated `utils.formatSlot`, it should now work with odd numbered values.

The original call to formatSlot should be functionally equivalent to the current version, so I haven't changed that. Here is the original: 

```
let slot = utils.formatSlot(filter.value);
if (timestamp) {
    slot = utils.formatSlot(filter.value, true);
}
```

2023-12-08 22:20 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      const slot = utils.formatSlot(slotFilter.value, timestampPresent);
I think you missed my last comment about the `leftPad` flag is inverted. i.e., when `leftPad` is false, the function pads slot to a full 64 character hex string

2023-12-11 15:45 UTC, edwin-greene commented on hedera-mirror-rest/controllers/contractController.js
> +      const slot = utils.formatSlot(slotFilter.value, timestampPresent);
Thanks I see now, I have updated it make more sense :)

2023-12-11 16:34 UTC, xin-hedera approved these changes
LGTM

2023-12-11 22:40 UTC, steven-sheehy approved these changes
LGTM

2023-12-11 22:47 UTC, xin-hedera approved these changes
LGTM

2023-12-11 23:00 UTC, merged