Re-implement temp table parser logic to be v2 compatible
hashgraph/hedera-mirror-node pull request #7382
Opened 2023-12-14 02:15 UTC by jnels124

**Description**:

**Related issue(s)**:

Fixes #7007 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-15 18:12 UTC, edwin-greene submitted a review, later dismissed
Looks good to me

2023-12-15 21:01 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/hedera-mirror-importer.json
> -        "definition": "label_values(hedera_mirror_download_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}, type)",
just a small change to make metrics work when using local stream file provider

2023-12-15 22:05 UTC, steven-sheehy requested changes

2023-12-15 22:05 UTC, steven-sheehy commented on charts/hedera-mirror/templates/secret-passwords.yaml
> +    alter default privileges in schema {{ $dbSchema }}, {{ $tempSchema }} grant insert, update, delete on tables to readwrite;
Believe we should adjust the search path somewhere for Citus. Or is that handled somewhere else?

2023-12-16 15:31 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    alter database :dbName set search_path = :dbSchema, public, :tempSchema;
I will update the doc

2023-12-16 15:32 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__02_temp_table_distribution.sql
> +select create_distributed_table('${tempSchema}.contract_state_temp', 'contract_id', colocate_with => 'contract_state');
it is not idempotent. However, the repeatable migration that runs before this drops the tables and recreates them so this will work.

2023-12-16 15:33 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +---- ${flyway:timestamp} trigger to always run
Yes it will run on every startup. That is a good idea. We can have every versioned migration set a placeholder that is its version number. If it changes, then it will trigger these to run

2023-12-16 15:35 UTC, jnels124 commented on charts/hedera-mirror/templates/secret-passwords.yaml
> +    alter default privileges in schema {{ $dbSchema }}, {{ $tempSchema }} grant insert, update, delete on tables to readwrite;
we set it up above on line 92

2023-12-16 15:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +---- ${flyway:timestamp} trigger to always run
I meant more do a query for latest versioned migration and compare against classpath migrations

2023-12-18 21:12 UTC, xin-hedera requested changes

2023-12-18 21:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +drop table if exists ${tempSchema}.entity_stake_temp;
perhaps skip `entity_stake_temp`

- it's completely unused even created here, since there is no change to the SQLs in EntityStakeRepository, a temp table under schema `public` is still created and used
- normally, entity stake calculation is done once per day, and we have plans to reduce the number of rows to insert / update

Suggestion is create a ticket so we don't forget, we can revisit if it becomes a performance issue.

2023-12-20 20:14 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__02_temp_table_distribution.sql
> +select create_distributed_table('${tempSchema}.crypto_allowance_temp', 'owner', colocate_with => 'crypto_allowance');
we could do that but it doesn't make sense in one case. The dissociate token transfer table is distributed differently than token transfer would be.

2023-12-20 21:55 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +      --set "tempSchemaAdminRole=${HEDERA_MIRROR_IMPORTER_DB_TEMPSCHEMA}_admin" <<__SQL__
in the bash script files, having the variable set this way makes the sql easier. Can't really do something like `create role :tempSchema_admin` there is not syntax i can find that will allow me to reuse the tempSchema var with additional text appended.

2023-12-20 22:26 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +drop table if exists ${tempSchema}.entity_stake_temp;
I have removed the entity_stake_temp table creation for now since you are correct that is not being used as is. Will create a ticket to determine if this logic should be updated to use the temp schema.

2023-12-20 22:36 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +---- ${flyway:timestamp} trigger to always run
created a follow up ticket to handle this.

2023-12-20 22:37 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +  --set "tempSchema=${HEDERA_MIRROR_IMPORTER_DB_TEMPSCHEMA:-temporary}"  <<__SQL__
will correct this name

2023-12-21 18:53 UTC, steven-sheehy requested changes

2023-12-21 18:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__02_temp_table_distribution.sql
> +select create_distributed_table('${tempSchema}.crypto_allowance_temp', 'owner', colocate_with => 'crypto_allowance');
Could just do Xin's suggestion and do that one special case as a one off

2023-12-21 18:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +create or replace function create_temp_schema(tempSchema varchar, dbSchema varchar, dbName varchar,
Why does this need to be a function using execute and formatted sql? It's a shell script so should be able to use `--set` and string templates. Also, the if schema exists check can move outside as a separate psql so you don't need conditional logic in the SQL itself.

2023-12-21 20:46 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +create or replace function create_temp_schema(tempSchema varchar, dbSchema varchar, dbName varchar,
I need to be able to do a query to see if the schema exists first. Originally tried to implement in anonymous block but unfortunately you are not able to access any params passed from the command line within a block

2023-12-21 21:46 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/application.yml
> +        tempSchema: temporary
will do. Put it here mostly to make overriding from charts more consistent with other DB vars

2023-12-21 21:58 UTC, jnels124 commented on docs/database/README.md
> +* For existing operators, upgrading to 0.96.0 requires manual upgrades to be applied to the database. You must execute the script located [here](/hedera-mirror-importer/src/main/resources/db/scripts/
I will be more clear

2023-12-21 22:10 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__02_temp_table_distribution.sql
> +select create_distributed_table('${tempSchema}.crypto_allowance_temp', 'owner', colocate_with => 'crypto_allowance');
will add to be a task to the existing follow up ticket

2023-12-21 22:42 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2023-12-21 23:44 UTC, xin-hedera requested changes

2023-12-21 23:44 UTC, xin-hedera commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    alter default privileges in schema :dbSchema, :tempSchema grant usage on sequences to readwrite;
I don't think these are needed either. The permission to access tempSchema should come from `authorization temporary_admin`, i.e., the temp schema's owner is `temporary_admin`, and `mirror_importer` is member of the role `temporary_admin`.

For that, instead of the current role hierarchy, I think we should do

- create role temporary_admin
- grant role temporary_admin to read_write

2023-12-21 23:44 UTC, xin-hedera commented on docs/database/README.md
> +upgrading to versions greater than 0.96.0 are required to configure this new schema
change it to `upgrading to 0.96.0 or a later version from an earlier version are required and configure and run this ... once`?

2023-12-21 23:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  --set "tempSchema=${HEDERA_MIRROR_IMPORTER_DB_TEMPSCHEMA:-temporary}" <<__SQL__
I think only the init script in charts needs the `HEDERA_MIRROR_IMPORTER_` prefix, right?
 ```suggestion
   --set "tempSchema=${DB_TEMPSCHEMA:-temporary}" <<__SQL__
```

2023-12-21 23:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +TEMP_SCHEMA="${HEDERA_MIRROR_IMPORTER_DB_TEMPSCHEMA:-temporary}"
keep it consistent with init.sh

```suggestion
TEMP_SCHEMA="${DB_TEMPSCHEMA:-temporary}"
```

2023-12-21 23:44 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +                  -c "select exists (select schema_name from information_schema.schemata where schema_name = '$TEMP_SCHEMA')")"
missing dbname=
```suggestion
DB_NAME="${DB_NAME:-mirror_node}"
SCHEMA_EXISTS="$(psql -d "user=postgres connect_timeout=3 dbname=${DB_NAME}" \
                  -XAt \
                  -c "select exists (select schema_name from information_schema.schemata where schema_name = '$TEMP_SCHEMA')")"
```

2023-12-21 23:47 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +                  -c "select exists (select schema_name from information_schema.schemata where schema_name = '$TEMP_SCHEMA')")"
it connects to db below but will move here instead since we dont need to connect to multiple dbs

2023-12-21 23:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +                  -c "select exists (select schema_name from information_schema.schemata where schema_name = '$TEMP_SCHEMA')")"
The problem is the query actually runs in postgres database and thus the information schema info looked up in that db will not contain the temporary schema regardless if that name exists in mirror_node database, right?

2023-12-22 00:13 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  --set "tempSchema=${HEDERA_MIRROR_IMPORTER_DB_TEMPSCHEMA:-temporary}" <<__SQL__
I will make consistent. You are right that only the chart values need to do this.

2023-12-22 00:17 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    alter default privileges in schema :dbSchema, :tempSchema grant usage on sequences to readwrite;
we can do that assuming we want every user now and down the line with readwrite (now it is only mirror_node/mirror_importer) to have the ownership abilities over the temp schema. Not a huge concern there but may not want that for all users with this role down the line

2023-12-22 00:19 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    alter default privileges in schema :dbSchema, :tempSchema grant select on sequences to readonly;
I put them in there just in case it is helpful when running some analyze type querries on upsert statements. Having this allows to safely connect to the pods in various environments with read only to perform such querries

2023-12-22 00:22 UTC, xin-hedera commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    alter default privileges in schema :dbSchema, :tempSchema grant usage on sequences to readwrite;
That makes sense. Perhaps then we don’t need extra permission  grants of the temp schema to readwrite at all, because mirror_importer is a member of temporary_admin role?

2023-12-22 02:05 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/init-temp-schema.sh
> +                  -c "select exists (select schema_name from information_schema.schemata where schema_name = '$TEMP_SCHEMA')")"
Yes you are correct it causes an issue in the case of trying to restart. Restarting from a main version to this works no problem. Restarting from this version to this version doesn't. The schema exist lookup always returns false because we never actually create the schema in that database as you mentioned.

2023-12-22 02:07 UTC, jnels124 commented on charts/hedera-mirror/templates/configmap-init.yaml
> +    alter default privileges in schema :dbSchema, :tempSchema grant usage on sequences to readwrite;
Yes if we keep the temporary_admin role we can still get rid of the extra grants on the readwrite user for the new schema. However, vote to still keep the readonly grants for this schema.

2023-12-22 02:58 UTC, xin-hedera approved these changes
LGTM

2023-12-22 05:10 UTC, steven-sheehy approved these changes

2023-12-30 00:01 UTC, merged