HIP-584: Add tests for nested functions for call and estimate gas
hashgraph/hedera-mirror-node pull request #7383
Opened 2023-12-14 10:53 UTC by anastasiya-kovaliova

**Description:**

Introduces additional tests to validate the in-memory state via estimateGas and ethCall endpoints and nested functions. The new tests are executing newly added functions in the PrecompileTestContract contract. For each function there are tests for eth_call and estimate_gas for both fungible and NFT tokens.

* Add 9 contract nested functions
* Add 16 tests for call (ETHCALL-069 - ETHCALL-084)
* Add 16 tests for estimate gas (ETH_ESTIMATE-101 - ETH_ESTIMATE-116)

**Related issue(s):**

Fixes #7018

Notes for reviewer:

New PR. Old one is: https://github.com/hashgraph/hedera-mirror-node/pull/7085

Checklist

- [ ]  Documented (Code comments, README, etc.)
- [x]  Tested (unit, integration, etc.)

2023-12-14 10:53 UTC, anastasiya-kovaliova commented
This PR is the new and clean one with all commits signed for: https://github.com/hashgraph/hedera-mirror-node/pull/7138

2023-12-14 10:59 UTC, 0xivanov approved these changes

2023-12-14 19:12 UTC, steven-sheehy requested changes

2023-12-14 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/PrecompileTestContract.sol/SpenderContract.json
I believe this file snuck in accidentally.

2023-12-14 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/KeyHelper.sol/KeyHelper.json
I believe this file snuck in accidentally.

2023-12-14 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/KeyHelper.sol/Bits.json
I believe this file snuck in accidentally. Please adjust gitignore

2023-12-14 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            log.debug("Associated account {} with token {} via {}", accountId, token, response.getTransactionId());
nit: Think this particular one could be info level since our standard is to log all HAPI transactions.

2023-12-14 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        associations.clear();
Same comment from last PR about being able to remove this clear statement.

2023-12-14 19:12 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                new ExpandedAccountId(AccountId.fromString(deployedErcTestContract.contractId().toString())),
Add an overloaded method `TokenClient.associate(ContractId contractId, TokenId)` that hides this `new ExpandedAccountId(AccountId.fromString(deployedErcTestContract.contractId().toString()))` conversion.

2023-12-15 21:43 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                new ExpandedAccountId(AccountId.fromString(deployedErcTestContract.contractId().toString())),
Thats a great idea! Now the tests look a lot cleaner and more readable!

2023-12-15 21:43 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        associations.clear();
Thank you for noticing that! I've updated it!

2023-12-15 21:44 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            log.debug("Associated account {} with token {} via {}", accountId, token, response.getTransactionId());
Thank you! Now this is updated!

2023-12-15 21:45 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/KeyHelper.sol/Bits.json
Great catch! File is now deleted!

2023-12-15 21:45 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/KeyHelper.sol/KeyHelper.json
Great catch! File is now deleted!

2023-12-15 21:45 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/PrecompileTestContract.sol/SpenderContract.json
Great catch! File is now deleted!

2023-12-15 22:15 UTC, steven-sheehy requested changes

2023-12-15 22:15 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> -        deleteAll(tokenAccounts, tokenAccount -> dissociate(tokenAccount.accountId, tokenAccount.tokenId));
Just noticed you're not calling deleteAll on associations map even though you were on the old branch.

2023-12-15 22:18 UTC, steven-sheehy commented
Also got this error when running against integration:
```
    2023-12-15T22:15:38.937Z ERROR ForkJoinPool-1-worker-8 c.h.m.t.e.a.s.EstimatePrecompileFeature Scenario failure: 
    I create estimate precompile contract with 0 balance
    I create erc test contract with 0 balance
    I get exchange rates
    I successfully create Precompile contract with 0 balance
    I successfully create fungible tokens
    I successfully create non fungible tokens
    I mint and verify a new nft
    the mirror node REST API should return status 200 for the HAPI transaction
    I set lower deviation at 5% and upper deviation at 20%
    I call estimateGas with associate function for fungible token
    I call estimateGas with associate function for NFT
    I call estimateGas with dissociate token function without association for fungible token
    I call estimateGas with dissociate token function without association for NFT
    I call estimateGas with nested associate function that executes it twice for fungible token
    I call estimateGas with nested associate function that executes it twice for NFT
    I call estimate gas that associates FUNGIBLE token dissociates and fails token transfer
    I call estimate gas that associates NFT token dissociates and fails token transfer
    I associate the receiver account with the fungible token
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with dissociate token function for fungible token
    I associate the receiver account with the NFT
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with dissociate token function for NFT
    I call estimateGas with dissociate and associate nested function for fungible token
    I call estimateGas with dissociate and associate nested function for NFT
    I call estimateGas with approve function without association
    I call estimateGas with approveNFT function without association
    I call estimateGas with setApprovalForAll function without association
    I associate contracts with the tokens and approve all nft serials
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with ERC approve function
    I call estimateGas with setApprovalForAll function
    I call estimateGas with transferFrom function without approval
    I call estimateGas with ERC transferFrom function without approval
    I approve receiver account to use the NFT with id 1
    the mirror node REST API should return status 200 for the HAPI transaction
    I approve the contract to use fungible token
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with transferFrom function with more than the approved allowance
    I call estimateGas with ERC transferFrom function with more than the approved allowance
    I call estimateGas with transferFromNFT with invalid serial number
    I call estimateGas with transferNFT function
    I approve the receiver account to use fungible token and transfer fungible token to the erc contract
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with ERC transferFrom function
    I call estimateGas with ERC transfer function
    I call estimateGas with associateTokens function for fungible tokens <- 400 Bad Request from POST /api/v1/contracts/call
    I call estimateGas with associateTokens function for NFTs
    I associate the fungible_kyc_unfrozen token with the receiver account
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with dissociateTokens function for fungible tokens
    I associate the nft_kyc_unfrozen with the receiver account
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with dissociateTokens function for NFTs
    I associate and approve the second receiver to use the fungible_kyc_unfrozen token
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with transferTokens function
    I mint a new NFT and approve second receiver account to all serial numbers
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with transferNFTs function
    I call estimateGas with cryptoTransfer function for hbars
    I call estimateGas with cryptoTransfer function for nft
    I call estimateGas with cryptoTransfer function for fungible tokens
    I call estimateGas with burnToken function for fungible token
    I call estimateGas with burnToken function for NFT
    I call estimateGas with CreateFungibleToken function
    I call estimateGas with CreateNFT function
    I call estimateGas with CreateFungibleToken function with custom fees
    I call estimateGas with CreateNFT function with custom fees
    I approve and transfer fungible tokens to receiver account
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with WipeTokenAccount function
    I call estimateGas with WipeTokenAccount function with invalid amount
    I transfer NFT to receiver account
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with WipeNFTAccount function
    I call estimateGas with WipeNFTAccount function with invalid serial number
    I call estimateGas with GrantKYC function for fungible token
    I call estimateGas with GrantKYC function for NFT
    I call estimateGas with RevokeTokenKYC function for fungible token
    I call estimateGas with RevokeTokenKYC function for NFT
    I call estimateGas with Grant and Revoke KYC nested function
    I call estimateGas with Freeze function for fungible token
    I call estimateGas with Freeze function for NFT
    I call estimateGas with Unfreeze function for fungible token
    I call estimateGas with Unfreeze function for NFT
    I call estimateGas with nested Freeze and Unfreeze function for fungible token
    I call estimateGas with nested Freeze and Unfreeze function for NFT
    I call estimateGas with delete function for Fungible token
    I call estimateGas with delete function for NFT
    I call estimateGas with delete function for invalid token address
    I call estimateGas with updateTokenExpiryInfo function
    I call estimateGas with updateTokenInfo function
    I call estimateGas with updateTokenKeys function
    I call estimateGas with pause function for fungible token
    I call estimateGas with pause function for NFT
    I call estimateGas with unpause function for fungible token
    I call estimateGas with unpause function for NFT
    I call estimateGas for nested pause and unpause function
    I call estimateGas for nested pause, unpause NFT function
    I call estimateGas with getTokenExpiryInfo function
    I call estimateGas with isToken function
    I call estimateGas with getTokenKey function for supply
    I call estimateGas with getTokenKey function for KYC
    I call estimateGas with getTokenKey function for freeze
    I call estimateGas with getTokenKey function for admin
    I call estimateGas with getTokenKey function for wipe
    I call estimateGas with getTokenKey function for fee
    I call estimateGas with getTokenKey function for pause
    I call estimateGas with ERC allowance function for fungible token
    I call estimateGas with getApproved function for NFT
    I call estimateGas with ERC getApproved function for NFT
    I call estimateGas with isApprovedForAll function
    I call estimateGas with ERC isApprovedForAll function
    I call estimateGas with name function for fungible token
    I call estimateGas with name function for NFT
    I call estimateGas with symbol function for fungible token
    I call estimateGas with symbol function for NFT
    I call estimateGas with decimals function for fungible token
    I call estimateGas with totalSupply function for fungible token
     [...]

2023-12-18 14:47 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> -        deleteAll(tokenAccounts, tokenAccount -> dissociate(tokenAccount.accountId, tokenAccount.tokenId));
Thanks for noticing that! I've added the deletion

2023-12-18 14:49 UTC, anastasiya-kovaliova commented
@steven-sheehy I changed the fungible tokens being used in the eth-call tests and now the associations are not conflicting with the ones in the estimate_gas tests.

2023-12-18 20:02 UTC, steven-sheehy requested changes

2023-12-18 20:02 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
>      public TokenClient(SDKClient sdkClient, RetryTemplate retryTemplate) {
I get this ApplicationContext error when trying to run your branch:

```
    2023-12-18T18:18:43.358Z  WARN ForkJoinPool-1-worker-3 o.s.b.w.r.c.GenericReactiveWebApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenClient' defined in file [/Users/stevensheehy/projects/hedera/hedera-mirror-node/hedera-mirror-test/build/classes/java/test/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.class]: Unsatisfied dependency expressed through constructor parameter 1: No qualifying bean of type 'org.springframework.retry.support.RetryTemplate' available: expected single matching bean but found 2: retryTemplate,rest 
    2023-12-18T18:18:43.382Z ERROR ForkJoinPool-1-worker-3 o.s.b.d.LoggingFailureAnalysisReporter 

    ***************************
    APPLICATION FAILED TO START
    ***************************

    Description:

    Parameter 1 of constructor in com.hedera.mirror.test.e2e.acceptance.client.TokenClient required a single bean, but 2 were found:
        - retryTemplate: defined by method 'retryTemplate' in class path resource [com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.class]
        - rest: defined by method 'restRetryTemplate' in class path resource [com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.class]


    Action:

    Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

Can you delete `ClientConfiguration.restRetryTemplate()` as it seems to be unused now after a recent refactor and is causing this issue.

2023-12-18 20:02 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    @And("I associate FUNGIBLE_KYC_UNFROZEN token to receiver account")
I get an error here in integration:

```
    I dissociate a FUNGIBLE token and fail transfer
    I approve a NFT token and transfer it
    I associate FUNGIBLE_KYC_UNFROZEN token to receiver account <- Transaction was unsuccessful: TransactionReceipt{transactionId=0.0.4271@1702929406.166000000, status=TOKEN_WAS_DELETED, exchangeRate=ExchangeRate{hbars=1, cents=12, expirationTime=2100-01-01T00:00:00Z, exchangeRateInCents=12.0}, accountId=null, fileId=null, contractId=null, topicId=null, tokenId=null, topicSequenceNumber=null, topicRunningHash=null, totalSupply=0, scheduleId=null, scheduledTransactionId=null, serials=[], duplicates=[], children=[]}
    the mirror node should return status 200 for the HAPI transaction
    I grant and revoke KYC
    I approve a FUNGIBLE token and transfer it
    I successfully update the balance of an account and get the updated balance after 2 seconds
     com.hedera.mirror.test.e2e.acceptance.client.NetworkException: Transaction was unsuccessful: TransactionReceipt{transactionId=0.0.4271@1702929406.166000000, status=TOKEN_WAS_DELETED, exchangeRate=ExchangeRate{hbars=1, cents=12, expirationTime=2100-01-01T00:00:00Z, exchangeRateInCents=12.0}, accountId=null, fileId=null, contractId=null, topicId=null, tokenId=null, topicSequenceNumber=null, topicRunningHash=null, totalSupply=0, scheduleId=null, scheduledTransactionId=null, serials=[], duplicates=[], children=[]}
        at com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.getTransactionReceipt(AbstractNetworkClient.java:152)
        at com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:123)
        at com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:131)
        at com.hedera.mirror.test.e2e.acceptance.client.TokenClient.lambda$associate$3(TokenClient.java:290)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at com.hedera.mirror.test.e2e.acceptance.client.TokenClient.associate(TokenClient.java:283)
        at com.hedera.mirror.test.e2e.acceptance.steps.CallFeature.associateReceiverWithFungibleKyc(CallFeature.java:210)
        at ✽.I associate FUNGIBLE_KYC_UNFROZEN token to receiver account(classpath:features/contract/call.feature:57)

    2023-12-18T19:56:48.164Z  INFO ForkJoinPool-1-worker-4 c.h.m.t.e.a.s.CallFeature Executing step: the mirror node should return status 200 for the HAPI transaction 
    2023-12-18T19:56:48.164Z  INFO ForkJoinPool-1-worker-4 c.h.m.t.e.a.s.CallFeature Executing step: I grant and revoke KYC 
    2023-12-18T19:56:48.164Z  INFO ForkJoinPool-1-worker-4 c.h.m.t.e.a.s.CallFeature Executing step: I approve a FUNGIBLE token and transfer it 
    2023-12-18T19:56:48.164Z  INFO ForkJoinPool-1-worker-4 c.h.m.t.e.a.s.CallFeature Executing step: I successfully update the balance of an account and get the updated balance after 2 seconds 

AcceptanceTest > Cucumber > eth_call Contract Base Coverage Feature > com.hedera.mirror.test.e2e.acceptance.AcceptanceTest.Validate eth_call FAILED
    com.hedera.mirror.test.e2e.acceptance.client.NetworkException: Transaction was unsuccessful: TransactionReceipt{transactionId=0.0.4271@1702929406.166000000, status=TOKEN_WAS_DELETED, exchangeRate=ExchangeRate{hbars=1, cents=12, expirationTime=2100-01-01T00:00:00Z, exchangeRateInCents=12.0}, accountId=null, fileId=null, contractId=null, topicId=null, tokenId=null, topicSequenceNumber=null, topicRunningHash=null, totalSupply=0, scheduleId=null, scheduledTransactionId=null, serials=[], duplicates=[], children=[]}
        at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.getTransactionReceipt(AbstractNetworkClient.java:152)
        at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:123)
        at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:131)
        at app//com.hedera.mirror.test.e2e.acceptance.client.TokenClient.lambda$associate$3(TokenClient.java:290)
        at java.base@21/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at app//com.hedera.mirror.test.e2e.acceptance.client.TokenClient.associate(TokenClient.java:283)
        at app//com.hedera.mirror.test.e2e.acceptance.steps.CallFeature.associateReceiverWithFungibleKyc(CallFeature.java:210)
        at ✽.I associate FUNGIBLE_KYC_UNFROZEN token to receiver account(classpath:features/contract/call.feature:57)
```

2023-12-18 22:30 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
>      public TokenClient(SDKClient sdkClient, RetryTemplate retryTemplate) {
Sure! After removing it now this errors seems to not be reproducible.

2023-12-18 22:32 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +        fungibleTokenId = tokenClient.getToken(FUNGIBLE_DELETABLE).tokenId();
Thank you, seems that both FUNGIBLE_DELETABLE and FUNGIBLE_KYC_UNFROZEN_2 cause a race condition. I've replaced them both with dedicated tokens for etc_call tests that are not getting deleted.

2023-12-18 22:35 UTC, anastasiya-kovaliova commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> +    @And("I associate FUNGIBLE_KYC_UNFROZEN token to receiver account")
Thank you! Now with the last changes pushed all the tests are passing from my side on this environment

2023-12-21 20:35 UTC, steven-sheehy approved these changes
LGTM. Will address the regression in a separate PR so we can get this in.

2023-12-21 20:36 UTC, merged