feat: HIP-584 Historical: Sync evm configurations with hedera-services
hashgraph/hedera-mirror-node pull request #7385
Opened 2023-12-14 11:59 UTC by kselveliev

**Description**:
This PR modifies current EVM bean configuration - which defaults to evm 38 

Create 3 versions of **EVM** bean - similar to services
v30 - registerLondonOperations
v34 - registerParisOperations
v38 - registerShanghaiOperations

Changed config for **MessageCallProcessor** that is used for **EVM_VERSION_30** since it was missing to register precompiled contracts -> created **MirrorEvmMessageCallProcessorV30** - which now accepts v30 EVM bean and registers the precompiles provided from **PrecompiledContractProvider**.
Added **ContractCreationProcessorV30** that uses new v30 EVM bean

Added **MirrorEvmMessageCallProcessorV34** that uses v34 EVM bean.
Added **ContractCreationProcessorV34** that uses v34 EVM bean.

Added **MirrorEvmMessageCallProcessorV38** that uses v38 EVM bean.
Added **ContractCreationProcessorV38** that uses v38 EVM bean. (NB: This was the only evm config that was loaded before the changes in the PR)

Modified **EvmConfiguration** registering the 3 versions of evm v30, v34 and v38.
And modified the messageCallProcessors and contractCreationProcessorProvider to map the evm version to
the newly created configs.

<img width="626" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/10a3a9ab-4656-4d96-8bfd-4945bfd727d0">

<img width="651" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/c37bf6db-1cd7-46d4-a618-7fe2507ebcc0">

**Related issue(s)**:

Fixes #7384

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-12-14 22:47 UTC, steven-sheehy requested changes

2023-12-14 22:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        registerParisOperations(
The 3 EVMs duplicate their configuration except for this register method and the EvmSpecVersion. Create a functional interface like 

```java
interface OperationRegistryCallback {
    void register(OperationRegistry registry, GasCalculator gasCalculator, BigInteger chainId);
}
```

Then declare most of the parameters as class variables and create a helper method:

```java
    private EVM evm(HederaPrngSeedOperation prngSeedOperation, EvmSpecVersion evmSpecVersion, OperationRegistryCallback callback) {
...
    }

    @Bean
    EVM evm34(HederaPrngSeedOperation prngSeedOperation) {
        return evm(prngSeedOperation, EvmSpecVersion.PARIS, MainnetEVMs::registerParisOperations);
    }
```

2023-12-14 22:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorV34.java
> +            @Named("v34") EVM v34,
MirrorEvmMessageCallProcessor 34 and 38 are identical except the EVM so can be moved to config for code reuse like ContractCreationProcessor.

2023-12-15 16:57 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +    EVM v38(
Comment addressed. Now using names evm030, evm034, evm038

2023-12-15 16:59 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/ContractCreationProcessorV30.java
> +        super(gasCalculator, v30, true, List.of(), 1);
Comment addressed. Now using Qualifier for evm bean in constructor.

2023-12-15 16:59 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +        registerParisOperations(
Comment addressed

2023-12-15 16:59 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorV34.java
> +            @Named("v34") EVM v34,
Comment addressed. Applied the change similar to ContractCreationProcessor above

2023-12-15 21:36 UTC, steven-sheehy approved these changes
LGTM

2023-12-15 21:37 UTC, merged