HIP-584 Historical: fix slot parameter in `MirrorEntityAccess`
hashgraph/hedera-mirror-node pull request #7415
Opened 2023-12-18 16:36 UTC by 0xivanov

**Description**:

After conducting both manual and integration testing, it was determined that the `contract_state_change table` is capable of storing values for the slot column ranging from 0 bytes to 32 bytes. This is in contrast to the `contract_state table`, where the slot is consistently represented as a 32-byte array.

`contract_state_change`:  

![image](https://github.com/hashgraph/hedera-mirror-node/assets/56980328/fd135078-25a5-4674-90e8-d79b039ac64e)

`contract_state`:  

![image](https://github.com/hashgraph/hedera-mirror-node/assets/56980328/0c1e883b-fe03-4b3b-bc01-4a59f4a71d97)

Solution:
Trim the leading zeros from the key if we are doing historical call.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-18 16:42 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +    void testTrimLeadingZeros() {
Can make this test parametrized

2023-12-18 17:14 UTC, steven-sheehy requested changes

2023-12-18 17:14 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +                        entityId, trimLeadingZeros(key.toArrayUnsafe()), t))
```suggestion
                        entityId, key.trimLeadingZeros().toArrayUnsafe(), t))
```

2023-12-18 17:14 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>                  .map(Bytes::wrap)
The slot values are also not zero prefixed. Does the EVM library already pad them appropriately? Is there a test for this?

2023-12-18 17:14 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +    void testTrimLeadingZeros() {
This test should go away since we can use the tuweni library for it. Instead, we should add a test that uses `getStorage()`.

2023-12-19 07:14 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
> +                        entityId, trimLeadingZeros(key.toArrayUnsafe()), t))
Nice catch, did not notice there is such method

2023-12-19 07:22 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>                  .map(Bytes::wrap)
From what i observed in `contract_state` slots are zero prefixed. We've implemented an acceptance test, which involves modifying the contract state and subsequently retrieving the updated state. Additionally, there is an integration test named `stateChangeWorksWithDynamicEthCall` that performs a similar process. They both read from `contract_state` table and the passed key matches the bytes in the db.

2023-12-19 07:38 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +    void testTrimLeadingZeros() {
Removed

2023-12-19 13:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>                  .map(Bytes::wrap)
Yes, but this `map` runs for both contract_state and contract_state_change. In the latter slot values are not prefixed, hence my question.

2023-12-19 14:51 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java
> +                        ENTITY_ID, BYTES.trimLeadingZeros().toArrayUnsafe(), timestamp.get()))
Fixed

2023-12-19 17:50 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>                  .map(Bytes::wrap)
It seems I may have misinterpreted your message. Both `contract_state_change` and `contract_state` are non-zero prefixed for `value_read`/`value_written` and `value`, respectively. In addressing the question, I believe there's no need to pad historical values. Could you please provide clarification, as I might still be misunderstanding something?

2023-12-19 18:53 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java
>                  .map(Bytes::wrap)
I think you are right, I just wanted to be completely sure. It seems like the EVM must be left padding it somewhere.

2023-12-19 18:53 UTC, steven-sheehy approved these changes
LGTM

2023-12-19 18:54 UTC, merged