Add tests for historical data
hashgraph/hedera-mirror-node pull request #7418
Opened 2023-12-19 07:46 UTC by yiliev0

**Description**: This PR is in development that covers acceptance tests for historical data support.

**Related issue(s)**:

Fixes #7048

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-15 07:11 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    @RetryAsserts
Do we need the retry?

2024-01-15 07:11 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    @RetryAsserts
Do we need the retry?

2024-01-15 07:11 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    private void waitForNextBlock() throws InterruptedException {
add some inline comments explaining the logic here

2024-01-15 10:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    @RetryAsserts
Removed.

2024-01-15 10:39 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    @RetryAsserts
Removed.

2024-01-15 10:40 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    private void waitForNextBlock() throws InterruptedException {
Done.

2024-01-16 08:43 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        FUNGIBLEHISTORICAL(
FUNGIBLEHISTORICAL -> FUNGIBLE_HISTORICAL

2024-01-16 08:44 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        NFTHISTORICAL(
NFTHISTORICAL -> NFT_HISTORICAL

2024-01-16 08:51 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +        deployedPrecompileContract = getContract(PRECOMPILE);
This step might be a bit misleading, since we create 3 accounts apart from creating the precompile contract. Probably the creation of these accounts could be extracted in a new step?

2024-01-16 09:13 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        FUNGIBLEHISTORICAL(
Cucumber detects the enums in .feature files only if the enum is one word, we already have token `ALLOWANCEFUNGIBLE` which is written this way so i thinks it's ok. The other option is to copy a lot of the steps where the change is only the token used, but this would cause a lot of unnecessary code, especially in the historical.feature

2024-01-16 11:21 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +        networkTransactionResponse = tokenClient.unfreeze(tokenId, receiverAccountId.getAccountId());
Could there be a moment where the `freezing` of the token could cause other acceptance tests ran in parallel to fail, if they are executed for the `same` token before the `unfreeze` operation?

2024-01-16 11:26 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +        networkTransactionResponse = tokenClient.unfreeze(tokenId, receiverAccountId.getAccountId());
The tokens in this test suite are used only here and won't mess with other tests running at the same time.

2024-01-16 11:51 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-01-16 12:06 UTC, 0xivanov submitted a review, later dismissed
LGTM

2024-01-16 15:59 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +        deployedPrecompileContract = getContract(PRECOMPILE);
Done.

2024-01-17 15:50 UTC, steven-sheehy requested changes

2024-01-17 20:56 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/historical.feature
> +    Given I successfully create estimate precompile contract
Hey @steven-sheehy ,
Thank you for your suggestion. If I understand correctly, you're proposing that we repurpose the methods in call.feature for both current (latest=true) and historical (latest=false) scenarios, essentially by toggling a latest flag.

While this approach sounds efficient, particularly for scenarios that don't involve state changes (like token and balance updates or deletions), it might not be entirely feasible for our current test scenarios. A significant portion of our tests actively involves state modifications, which is crucial for thoroughly testing of historical support. These tests are designed to "mess up" the state, so to speak, to ensure that the calls return proper historical data. For example, tests that involve actions like wiping or burning tokens have been vital for uncovering issues where the token supply wasn't accurately reflected in historical calls post-modification.

Therefore, while we could integrate the existing historical support implementations into call.feature, it might not substantially reduce costs due to the state-changing nature of most of our tests. This isn't to say that we can't look into optimising our test suite and cost of execution - I would appreciate further suggestions.
However, we need to consider how these changes might affect the depth and quality of our testing.

2024-01-18 13:00 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/features/contract/historical.feature
> +    Given I successfully create estimate precompile contract
I agree with @yiliev0. In these test, we need to deterministically change state and wait for a block, before we validate that historical `eth_call` is working properly. If we re-execute `call.feature` with a historical block after the executions with latest block have passed, there is a chance that nothing has changed for the given token between the two runs and the returned result would be the same for both `latest` and `historical` block. In this way there is a chance that we miss to catch a bug. It would be more obvious to change token's state and validate that we can still fetch the state value before the update with historical `eth_call`.

2024-01-18 13:22 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/resources/features/contract/historical.feature
> +    Given I successfully create estimate precompile contract
What if we integrate at least part of these historical `eth_call` scenarios inside TokenFeature and validate that prior to the operations included in TokenFeature, we read the old state of the token being modified? This could potentially save us a lot of the gas costs in these historical scenarios.

We can leave the most specific cases in the `HistoricalFeature`. Additionally, I think we can test multiple historical `eth_call` operations via one HAPI operation to consensus. For example we can delete a token and check:

- getTokenDefaultFreezeStatus
- getTokenDefaultKYCStatus
- getTokenType
- getTokenExpiryInfo

Otherwise, all 4 operations would recreate and delete a given token while we can do these checks at once. 

There might be other operations that might be grouped together and checked with one HAPI call.

2024-01-18 14:05 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/historical.feature
> +    Given I successfully create estimate precompile contract
Hey @IvanKavaldzhiev,

Thank you for your suggestions. I agree that consolidating operations like `getTokenDefaultFreezeStatus`, `getTokenDefaultKYCStatus`, `getTokenType`, and `getTokenExpiryInfo` into a single test would be a strategic move. By initiating the delete/create token process just once, we could indeed significantly reduce the associated costs. This approach makes it more efficient without compromising the quality of our test results.

Regarding the integration of historical `eth_call` scenarios with the `TokenFeature` tests, I appreciate the thought behind this idea. However, I believe that keeping these as separate entities might be more beneficial in the long run. The primary reason is that they are designed to verify different aspects of our system. Historical feature tests and token feature tests each have distinct objectives and scopes. By merging them, we risk creating tests that could fail for multiple unrelated reasons, potentially complicating the process of pinpointing the exact cause of any issues. Clear separation ensures that each test remains focused and that any failures are easier to diagnose and address.

Perhaps, we can look more into optimising the current behaviour, same as the suggestion you've proposed related to the `getToken` operations?

2024-01-18 18:03 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +            Thread.sleep(waitTime);
Replaced this method with awaitility. Thanks for suggestion!

2024-01-18 18:04 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +    enum ContractMethods implements SelectorInterface {
Removed all duplicated methods.

2024-01-18 18:04 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +        assertEquals(initialResponse, response);
Replaced all occurrences of `assertEquals` with `assertThat`

2024-01-18 18:06 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +        waitForNextBlock();
I think I might have mislead you with this comment. We need to wait for next block, so we can make all the state modifications in the next block, including the executeContract in this test case. After that all HAPI methods are using `verifyMirrorTransactionsResponse`

2024-01-19 05:57 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/historical.feature
> +    Given I successfully create estimate precompile contract
> If we re-execute call.feature with a historical block after the executions with latest block have passed, there is a chance that nothing has changed for the given token between the two runs

My suggestion was to run call feature with latest=true, store the results, then run with latest=false which will change state again, then verify call against stored results. I guess this would only work if you ensured the state change operation differed each time (like transfer a tinybar for get balance).

It's not the hbar costs that concern me since `@acceptance` doesn't run on mainnet. It's more the execution time and maintenance burden costs. Do we know how much time and costs this change adds to the overall tests? Perhaps it's not that bad in practice and we can keep the tests as is.

2024-01-19 14:14 UTC, yiliev0 commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
> +            assertThat(currentResponses.get(keyValue)).isEqualTo(historicalResponse);
Fixed, thanks for heads up.

2024-01-19 14:45 UTC, yiliev0 commented on hedera-mirror-test/src/test/resources/features/contract/historical.feature
> +    Given I successfully create estimate precompile contract
Hey @steven-sheehy, 
After the latest commit where I grouped some tests, it's the following:

- Acceptance tests without Historical feature against the integration env -> 8 min & 337 Hbars
- Acceptance tests with Historical feature against the integration env ->  12 min & 443 Hbars

2024-01-22 19:00 UTC, steven-sheehy approved these changes
LGTM. Still not a fan of everything but let's get it in and iterate. In particular, the waiting for next block causes a lot of unnecessary delay. Even within the historical feature we can structure the tests such that all of the state change operations occur then we wait one time for the next block before comparing initial vs latest response. Would require storing the initial response in a map.

2024-01-22 19:27 UTC, IvanKavaldzhiev approved these changes
LGTM! Agree with Steven that we can further optimise the tests structure and performance in follow up PRs.

2024-01-22 22:13 UTC, yiliev0 commented
Resolved conflicts. Seems reasonable to optimise it in future PRs. We can communicate internally and find a feasible solution.

2024-01-22 22:16 UTC, steven-sheehy approved these changes

2024-01-22 22:22 UTC, merged