HIP-584 Historical: fix historical crypto balance
hashgraph/hedera-mirror-node pull request #7419
Opened 2023-12-19 11:41 UTC by 0xivanov

**Description**:
This PR includes the following fixes:

- get historical entity balance from `AccountBalanceRepository`
- fix `findHistoricalAccountBalanceUpToTimestamp` in edge case where `balance_snapshot` query does not match anything in the db. Currently reproducible in acceptance tests:
1. create account with initial balance 50
2. make crypto transfer +50 
3. make historical call with timestamp before the crypto transfer, expected balance is 50, but returns 0

I have observed that the state in db after these operations is the following:
`account_balance` - no entry for this accountId
`crypto_transfers` - 2 entries for this accountId, one for initial balance (50) and one for the crypto transfer (50)

`balance_snapshot` matches nothing because there is no entry for this accountId in `account_balance` before the given timestamp.
This causes the statement `ct.consensus_timestamp > s.consensus_timestamp` to be false and cannot match any crypto transfers, always returning 0 due to the `coalesce` at the end of the query.
NB. `account_balance` entry  gets persisted ~8 minutes after the account creation

Current solution:
If `balance_snapshot` does not match anything, find crypto transfers that occured after the account creation and before the given timestamp:
```sql
ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), accountCreatedTimestamp)
```
Changed `>` to `>=` in order to match the initial balance transfer (in this case 50) if there is one.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-19 13:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/AccountBalanceRepositoryTest.java
> +                .isEqualTo(TRANSFER_AMOUNT * 2);
If the balance we are searching for is in-between transfers, shouldn't the final amount be `15L + TRANSFER_AMOUNT`?

2023-12-19 13:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/AccountBalanceRepositoryTest.java
> +                .isEqualTo(TRANSFER_AMOUNT);
Shouldn't it be 15L + TRANSFER_AMOUNT?

2023-12-19 13:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/AccountBalanceRepositoryTest.java
> +                .isEqualTo(TRANSFER_AMOUNT * 2);
Actually you are reusing  `timestampBetweenTheTransfers` which is a bit confusing. You can declare a new field - `timestampAfterSecondTransfer`. Then shouldn't the final balance be `15L + TRANSFER_AMOUNT*2`?

2023-12-19 14:07 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/AccountBalanceRepositoryTest.java
> +                .isEqualTo(TRANSFER_AMOUNT);
The setting of balance to the entity is misleading. When we create account with balance 15 ,for example, entry in `account_balance` gets persisted for this initial amount. In real environment when we create account the `entity.balance` should match the first `account_balance` for this account id.

2023-12-19 14:08 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/AccountBalanceRepositoryTest.java
> +                .isEqualTo(TRANSFER_AMOUNT);
notice that `firstTransfer` and `account` have the same timestamp.

2023-12-19 14:30 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/AccountBalanceRepositoryTest.java
> +                .isEqualTo(TRANSFER_AMOUNT * 2);
please check out my comments https://github.com/hashgraph/hedera-mirror-node/pull/7419#discussion_r1431451860
also, changed the tests to be more comprehendable

2023-12-20 15:00 UTC, xin-hedera requested changes

2023-12-20 15:00 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), ?3) and
because the account_balance table is deduped and partitioned monthly, a more performant query is:

1. find the latest balance snapshot timestamp of treasury account `0.0.2` before `blockTimestamp`, it works because the design is we never dedup treasury account's balance info, and there will be a row for the account in every snapshot. Let's call it `balanceSnapshotTimestamp`

3. find `accountId`'s latest balance in the range `(balanceSnapshotTimestamp - 31 days, balanceSnapshotTimestamp]`

the equivalent SQL is

```sql
with balance_timestamp as (
  select consensus_timestamp
  from account_balance
  where account_id = 2 and
    consensus_timestamp > ?1 - 2678400000000000 and
    consensus_timestamp <= ?1
  order by consensus_timestamp desc
  limit 1
), balance_snapshot as (
  select balance
  from account_balance as ab, balance_timestamp as bt
  where account_id = ?1 and
    ab.consensus_timestamp > bt.consensus_timestamp - 2678400000000000 and
    ab.consensus_timestamp < bt.consensus_timestamp
  order by ab.consensus_timestamp desc
  limit 1
), change as (
  select sum(amount) as amount
  from crypto_transfer as ct, balance_timestamp as bt
  where ct.entity_id = ?1 and
      ct.consensus_timestamp > bt.consensus_timestamp and
      ct.consensus_timestamp <= ?2 and
      (ct.errata is null or ct.errata <> 'DELETE')
)
select coalesce((select balance from balance_snapshot), 0) + coalesce((select amount from change), 0)
```

In addition, `accouontCreatedTimestamp` is not needed.

2023-12-21 08:26 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), ?3) and
Can you clarify this scenario?
We have `account_balance` entry with timestamp `1703060978991589711`, id `1136` and balance `50,000,000` (let's call it "myBalance")
We have `account_balance` entry with id `2` with the same timestamp  -`1703060978991589711`
We pass timestamp `1703060978991589711` as parameter.
The first part of the query would match and return timestamp `1703060978991589711` due to `<=`.
The second part won't match "myBalance" at timestamp `1703060978991589711` because we have `ab.consensus_timestamp < bt.consensus_timestamp` and we would go further back in time to search for another entry for id `1136`.
Should't we match "myBalance" in this scenario?
using `ab.consensus_timestamp <= bt.consensus_timestamp`

2023-12-21 10:23 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), ?3) and
So how i think this `account_balance` system works: 
every X minutes, Y number of `account_balance` entries are dumped for the accounts involved in `crypto_transfers`. This process includes entries for those accounts, and it always includes an entry for `0.0.2`. This cycle then repeats, with the timestamp of `0.0.2` marking the beginning of a new cycle and the end of the previous one.
@xin-hedera please correct me if I'm wrong.
If what i'm saying is true then before the first cycle of `account_balance` entries this table is empty. Can we use `coalesce` in the `crypto_transfer` part of the query for this case?

2023-12-21 15:38 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), ?3) and
I was contemplating today and devised the following SQL query (?1 representing accountId, and ?2 representing blockTimestamp):

```sql
with balance_timestamp as (
  select consensus_timestamp
  from account_balance
  where account_id = 2 and
    consensus_timestamp > ?2 - 2678400000000000 and
    consensus_timestamp <= ?2
  order by consensus_timestamp desc
  limit 1
), balance_snapshot as (
  select balance
  from account_balance as ab, balance_timestamp as bt
  where account_id = ?1 and
    ab.consensus_timestamp > bt.consensus_timestamp - 2678400000000000 and
    ab.consensus_timestamp <= bt.consensus_timestamp
  order by ab.consensus_timestamp desc
  limit 1
)
, change as (
  select sum(amount) as amount
  from crypto_transfer as ct
  where ct.entity_id = ?1 and
      ct.consensus_timestamp > coalesce((select consensus_timestamp from balance_snapshot), 0) and
      ct.consensus_timestamp <= ?2 and
      (ct.errata is null or ct.errata <> 'DELETE')
)
select coalesce((select balance from balance_snapshot), 0) + coalesce((select amount from change), 0)
```

2023-12-21 15:42 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), ?3) and
yes you are correct, sorry about the mistakes in the query in my feedback

- ?1 in the first CTE should be ?2
- in `balance_snapshot` CTE, you are right, it should be ab.consensus_timestamp <= bt.consensus_timestamp`

2023-12-21 17:29 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            ct.consensus_timestamp >= coalesce((select consensus_timestamp from balance_snapshot), ?3) and
Modified the query

2023-12-22 08:35 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                .map(t -> accountBalanceRepository.findHistoricalAccountBalanceUpToTimestamp(
Added this check

2023-12-22 08:40 UTC, kselveliev approved these changes
LGTM

2024-01-02 08:14 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/AccountBalanceRepository.java
> +                            consensus_timestamp > ?2 - 2678400000000000 and
Enhance the javadoc

2024-01-02 08:14 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                .map(t -> t >= entity.getCreatedTimestamp()
Add test for this case

2024-01-02 16:48 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-01-03 04:32 UTC, steven-sheehy requested changes

2024-01-03 04:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                .map(t -> t >= entity.getCreatedTimestamp()
Handle the scenario where createdTimestamp can be null. Add a test.

2024-01-03 04:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                        : Optional.of(0L))
Store as a static constant

2024-01-03 08:17 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                        : Optional.of(0L))
added zero balance constant

2024-01-03 08:18 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +                .map(t -> t >= entity.getCreatedTimestamp()
I presume we retrieve the balance from the `accountBalanceRepository `  when the `createdTimestamp` is null. I have implemented the modification as described earlier. Added unit test.

2024-01-03 15:30 UTC, steven-sheehy approved these changes
LGTM

2024-01-03 15:31 UTC, merged