HIP-584 Historical: Fix historical NFT/Fungible token balance
hashgraph/hedera-mirror-node pull request #7430
Opened 2023-12-20 11:40 UTC by 0xivanov

**Description**:

This PR includes the following fixes:
- get historical fungible token balance from `TokenBalanceRepository`
- get historical NFT balance from `NftRepository`. Historical NFT balance should be obtained from `account.getOwnedNfts()`, as explained in the code comments
- fix `findHistoricalTokenBalanceUpToTimestamp` in edge case where `balance_snapshot` and/or `base` queries do not match anything in the db. Currently reproducible in acceptance tests:
1. create account
2. make fungible token transfer +50
3. make fungible token transfer +50
4. make historical call with timestamp between the token transfers, expected balance is 50, but returns 0

I have observed that the state in db after these operations is the following:
`account_balance` - no entry for this accountId
`token_balance` - no entry for this accountId
`token_transfers` - 2 entries for this accountId, one for first transfer (50) and one for the second transfer (50)

`balance_snapshot` and `base` match nothing because there is no entry for this accountId before the given timestamp.
This causes the statement `tt.consensus_timestamp > s.consensus_timestamp` to be false and cannot match any token transfers, always returning 0 due to the coalesce at the end of the query.
NB. `token_balance` and `account_balance` entries get persisted in ~8 minute intervals so it is not certain that there is entry in the db after the first transfer.

Current solution:
If `balance_snapshot` and/or `base` do not match anything, find token transfers that occured after the account creation and before the given timestamp:
```sql
tt.consensus_timestamp >= coalesce((select consensus_timestamp from base), accountCreatedTimestamp)
```
Changed `>` to `>=` ensures the inclusion of the token transfer that occurred when the account was created.

**Optimisation proposals:**
- remove the `balance_snapshot` part of the query as it is not relevant to the token balances

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-12-20 12:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +        if (token.getType().equals(TokenType.NON_FUNGIBLE_UNIQUE)) {
I believe this method is only applicable for fungible token amount and we shouldn't have any logic for nfts.

2023-12-20 12:14 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    //                    with base as (
Probably this commented code from here to the bottom is obsolete?

2023-12-20 12:24 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +        if (token.getType().equals(TokenType.NON_FUNGIBLE_UNIQUE)) {
In `RedirectViewExecutor` we call `tokenAccessor.balanceOf(...)` when we have `ABI_ID_ERC_BALANCE_OF_TOKEN` signature which gets the balance for the token-account from `TokenRelationshipDatabaseAccessor`, regardless of the token type.
Check out
` Then I verify that historical data for "FUNGIBLE_HISTORICAL" is returned via balanceOf`
and
`Then I verify that historical data for "NFT_HISTORICAL" is returned via balanceOf`
from https://github.com/hashgraph/hedera-mirror-node/pull/7418/files
In the acceptance tests we get the historical NFT balance from this method, that is why i changed it

2023-12-20 12:27 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +    //                    with base as (
Wrote the 2 queries there for easier review process. Both versions apply the fixes that i mention in the description, but version 1 is my proposal to remove `account_balance` from the query.

2023-12-20 12:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +        if (token.getType().equals(TokenType.NON_FUNGIBLE_UNIQUE)) {
I see, then it seems OK to return the `owned nfts` from the `owner`, in case of NFT.

2023-12-20 12:39 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-01-02 20:15 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +     * the NFT balance is retrieved from `account.getOwnedNfts()`, previously set in `AccountDatabaseAccessor.getOwnedNfts()`.
this seems to imply that `account` and `timestamp` are correlated?

2024-01-02 20:24 UTC, xin-hedera requested changes

2024-01-02 20:24 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +     * The same principle as NFT applies here, and the balance is obtained from `account.getOwnedNfts()`.
think it should be `tokenAccount.getBalance()` instead of `account.getOwnedNfts()`

2024-01-02 20:24 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                        with base as (
please use the same CTE in the historical crypto balance PR to find the latest balance snapshot timestamp <= blockTimestamp and use the balance snapshot timestamp to get the base token balance

I don't see the value of adding `accountCreatedTimestamp` parameter.

2024-01-02 20:24 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                                tt.consensus_timestamp >= coalesce((select consensus_timestamp from base), ?4) and
```suggestion
                                tt.consensus_timestamp > coalesce((select consensus_timestamp from base), ?4) and
```

2024-01-03 08:50 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +     * the NFT balance is retrieved from `account.getOwnedNfts()`, previously set in `AccountDatabaseAccessor.getOwnedNfts()`.
Not really, instead it implies that this specific `timestamp` was also passed when loading this account in the cache from the db and we got it's historical nft balance from there (with the same timestamp passed here)

2024-01-03 08:51 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +     * The same principle as NFT applies here, and the balance is obtained from `account.getOwnedNfts()`.
Correct

2024-01-03 10:33 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                                tt.consensus_timestamp >= coalesce((select consensus_timestamp from base), ?4) and
fixed

2024-01-03 10:33 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                        with base as (
fixed

2024-01-03 10:34 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +     * The same principle as NFT applies here, and the balance is obtained from `account.getOwnedNfts()`.
Separated the logic for better readability

2024-01-03 19:16 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +        return account.getOwnedNfts();
After further testing, discovered that this method returns the number of all owned nfts and not for this specific nft id. Should change the implementation

2024-01-04 10:54 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +     * the NFT balance is retrieved from `account.getOwnedNfts()`, previously set in `AccountDatabaseAccessor.getOwnedNfts()`.
This logic is now changed, please have a look.

2024-01-04 10:54 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +        return account.getOwnedNfts();
fixed

2024-01-04 10:59 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                                and timestamp_range @> :blockTimestamp
@xin-hedera Can you please explain where this operator `@>` should be used?
Currently we are using combination of `@>` and `lower(timestamp_range) <=` , which one is correct?
From what I have tested in acceptance tests - using `@>` has correct behaviour, in contrast - `lower(timestamp_range) <=` returns incorrect values occasionally.

2024-01-06 00:09 UTC, xin-hedera requested changes

2024-01-06 00:09 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                            select tb.balance, tb.consensus_timestamp
```suggestion
                            select tb.balance
```
Using the token's balance timestamp when token balance info is deduped can increase the timestamp range when querying token_transfer table and it's completely unnecessary.

For example, based on account 2, the balance timestamp is 5000. In the `base` CTE, the latest deduped token balance info at or before timestamp 5000 has `balance = 20, consensus_timestamp = 1000`.

This indicates for all the balance snapshot timestamps in the range `[1000,  5000]`, the token's. balance is always 20. To reconcile and find the token balance change, we should query token_balance table in the timestamp range `(5000,  blockTimestamp]`,  instead of `(1000, blockTimestamp]`, because the deduped balance info implies in the timestamp range `(1000, 5000]`, there is no token transfer for the account and token at all.

2024-01-06 00:09 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                                tt.consensus_timestamp > coalesce((select consensus_timestamp from base), 0) and
```suggestion
                                tt.consensus_timestamp > coalesce((select consensus_timestamp from balance_timestamp), 0) and
```

2024-01-08 13:44 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                                and timestamp_range @> :blockTimestamp
Does this mean we can use `timestamp_range @>` everywhere?

2024-01-08 13:46 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                            select tb.balance, tb.consensus_timestamp
Fixed

2024-01-08 13:46 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenBalanceRepository.java
> +                                tt.consensus_timestamp > coalesce((select consensus_timestamp from base), 0) and
Fixed

2024-01-08 15:03 UTC, 0xivanov commented
Some integration tests need to be adjusted.

2024-01-08 20:52 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
> +                                and timestamp_range @> :blockTimestamp
yes.

In some places, we see the pattern in the query for the history table `where $1 >= lower(timestamp_range) and ... order by lower(timestamp_range) limit 1`, that's a performance optimization because the query can utilize the index, for example, for `token` table, the index on ` (token_id, lower(timestamp_range))`

2024-01-08 20:58 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenRelationshipDatabaseAccessor.java
> +            return getNftBalance(tokenAccount, timestamp, account.getCreatedTimestamp());
thanks!

2024-01-08 21:15 UTC, xin-hedera approved these changes
LGTM

2024-01-09 14:14 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    @Disabled
These 2 should get fixed here https://github.com/hashgraph/hedera-mirror-node/pull/7434

2024-01-09 22:45 UTC, steven-sheehy approved these changes
LGTM besides the question about `@Disabled`

2024-01-09 22:45 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    @Disabled
Now that that PR is merged, these should be removed, right?

2024-01-10 06:55 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    @Disabled
Removed

2024-01-10 19:24 UTC, steven-sheehy approved these changes
LGTM

2024-01-10 19:25 UTC, merged