convert rest java to servlet with virtual threads
hashgraph/hedera-mirror-node pull request #7488
Opened 2024-01-05 23:10 UTC by jnels124

**Description**:
* convert to use spring web instead of webflux
* update logging filter to be compatible with servlet app
* update tests to use mockmvc for controller testing

**Related issue(s)**:

Fixes #7465 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-05 23:57 UTC, jnels124 commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/config/MetricsConfiguration.java
> -
Tomcat doesn't provide an easy to duplicate this functionality. We would have to implement. Although not sure it is worth it. We already have server_http metrics from spring. Uris are slightly different but for our use case we can derive the same information from the server_http metrics.

2024-01-06 02:16 UTC, jnels124 commented on hedera-mirror-rest-java/src/main/resources/application.yml
> +  forward-headers-strategy: framework #Enable spring ForwardedHeaderFilter
This will wrap enable a filter that wraps the request with a request object that utilizes forwarded for headers for common methods like `getRemoteAddr()`

2024-01-07 01:03 UTC, steven-sheehy requested changes

2024-01-07 01:03 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/spring-conventions.gradle.kts
> +        extension.library = "resttemplate"
If we can't use RestClient, would prefer `native` as the next best option.

2024-01-07 01:03 UTC, steven-sheehy commented on build.gradle.kts
> +        api("org.openapitools:jackson-databind-nullable:0.2.6")
How is this used?

2024-01-07 22:54 UTC, jnels124 commented on buildSrc/src/main/kotlin/java-conventions.gradle.kts
> +    options.compilerArgs.addAll(listOf("-Werror", "-Xlint:all", "-Xlint:-removal,-serial,-this-escape"))
they use ClientHttpResponse.getRawStatusCode() in the generated api client which has been marked for removal. If we change to native, may not need this.

2024-01-07 22:56 UTC, jnels124 commented on build.gradle.kts
> +        api("org.openapitools:jackson-databind-nullable:0.2.6")
With the switch to rest template, the generated client code (looks like how converters work) needs this dependency as a wrapper around nullable objects to distinguish between null values sent on a request vs them not being present at all.

2024-01-08 18:10 UTC, jnels124 commented on hedera-mirror-rest-java/src/main/resources/application.yml
> +  forward-headers-strategy: framework #Enable spring ForwardedHeaderFilter
done

2024-01-08 18:10 UTC, jnels124 commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/DummyControllerTest.java
> +                .andExpect(MockMvcResultMatchers.content().string("Hello world"));
done

2024-01-08 18:10 UTC, jnels124 commented on hedera-mirror-rest-java/build.gradle.kts
> +
done

2024-01-08 18:26 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/config/LoggingFilterTest.java
> +        loggingFilter.doFilter(request, response, new MockFilterChain());
nit

```suggestion
        loggingFilter.doFilter(request, response, chain);
```

2024-01-08 18:26 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/config/LoggingFilterTest.java
> +        ;
nit
```suggestion
```

2024-01-08 18:32 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +    testImplementation("org.springframework.boot:spring-boot-starter-test")
This should already be included via java-conventions.gradle.kts

2024-01-08 18:32 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/java-conventions.gradle.kts
> +    options.compilerArgs.addAll(listOf("-Werror", "-Xlint:all", "-Xlint:-deprecation,-serial,-this-escape"))
I assume it's again the openapi gradle plugin using deprecated methods? We should file a bug upstream.

2024-01-08 18:53 UTC, jnels124 commented on buildSrc/src/main/kotlin/java-conventions.gradle.kts
> +    options.compilerArgs.addAll(listOf("-Werror", "-Xlint:all", "-Xlint:-deprecation,-serial,-this-escape"))
Yes will do.. Getting a minimal example put together and will file a bug

2024-01-08 19:03 UTC, steven-sheehy approved these changes
LGTM

2024-01-08 19:10 UTC, jnels124 commented on buildSrc/src/main/kotlin/java-conventions.gradle.kts
> +    options.compilerArgs.addAll(listOf("-Werror", "-Xlint:all", "-Xlint:-deprecation,-serial,-this-escape"))
there is an [existing bug report ](https://github.com/OpenAPITools/openapi-generator/issues/12714)

2024-01-08 19:20 UTC, xin-hedera approved these changes
LGTM

2024-01-08 19:23 UTC, merged