Replace TimePartitionService Cacheable annotation with caches
hashgraph/hedera-mirror-node pull request #7501
Opened 2024-01-08 20:19 UTC by edwin-greene

**Description**:
This replaces the `@Cacheable` annotation in `TimePartitionServiceImpl` with caches. In testing this has shown to improve performance.

**Related issue(s)**:

Fixes #7393 

**Notes for reviewer**:
Multiple runs of a unit test where ran comparing the performance of the unaltered @Cacheable methods and the non-Cacheable methods. The unit test was of a loop that performed 10 million identical requests to the methods. The non-Cacheable methods demonstrated a marked performance improvement, performing roughly 5 times faster: 

@Cacheable measurements:
2024-01-08T19:37:18.006Z  INFO Test worker c.h.m.i.d.TimePartitionServiceTest getOverlappingTimePartitions took 41282 ms for 100,000,000 iterations
2024-01-08T19:40:32.382Z  INFO Test worker c.h.m.i.d.TimePartitionServiceTest getTimePartitions took 33759 ms for 100,000,000 iterations

Non @Cacheable measurements:
2024-01-08T19:15:34.405Z  INFO Test worker c.h.m.i.d.TimePartitionServiceTest getOverlappingTimePartitions took 8275 ms for 100,000,000 iterations
2024-01-08T19:28:26.697Z  INFO Test worker c.h.m.i.d.TimePartitionServiceTest getTimePartitions took 7704 ms for 100,000,000 iterations

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-01-08 20:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +        var overlappingTimePartitions = cacheTimePartitionOverlapLookup(
The cache key should include `tableName`, `fromTimestamp`, and `toTimestamp`.

Remove the function `cacheTimePartitionOverlapLookup` and pull the logic here.

Remove the `Optional` I don't see why it's needed.

2024-01-08 20:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +        var cachedValue = cacheTimePartitionLookup(tableName, () -> Optional.of(queryForTimePartitions(tableName)));
similarly, remove the function `cacheTimePartitionLookup` and pull up the logic here.

2024-01-08 22:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +        var overlappingTimePartitions = cacheTimePartitionOverlapLookup(
Sounds good it is now updated.

2024-01-08 22:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +        var cachedValue = cacheTimePartitionLookup(tableName, () -> Optional.of(queryForTimePartitions(tableName)));
Got it, this has been updated.

2024-01-09 19:15 UTC, xin-hedera requested changes

2024-01-09 19:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
move these so they are after the `private static final` variables

2024-01-09 19:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +        String cacheKey = StringUtils.joinWith("-", tableName, fromTimestamp, toTimestamp);
IntelliJ profiler shows `StringUtils.joinWith` is the hotspot, this should be much faster
```suggestion
        String cacheKey = tableName + "-" +  fromTimestamp + "-" + toTimestamp;
```

2024-01-09 20:17 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Got it, they are now moved.

2024-01-09 20:18 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +        String cacheKey = StringUtils.joinWith("-", tableName, fromTimestamp, toTimestamp);
Thanks! I have updated the concatenation.

2024-01-09 21:03 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +            Utility.handleRecoverableError("Error looking up timePartition {} from cacheTimePartition", tableName, e);
When would this occur? It seems like the both this and get overlapping call `queryForTimePartitions` which already catches any exceptions. So do we need this extra catch here and above?

2024-01-09 21:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/TimePartitionServiceImpl.java
> +            Utility.handleRecoverableError("Error looking up timePartition {} from cacheTimePartition", tableName, e);
Thanks. It should not occur. I have removed both catches.

2024-01-09 22:05 UTC, steven-sheehy approved these changes
LGTM

2024-01-09 22:08 UTC, xin-hedera approved these changes
LGTM

2024-01-09 22:47 UTC, merged