Improve transaction queries in v2 (new)
hashgraph/hedera-mirror-node pull request #7503
Opened 2024-01-08 22:36 UTC by jascks

**Description**:
NOTE: This PR is still preliminary in development. It's purpose now is to get eyes on the work done thus far and the direction taken. Integration tests are failing on the expect fields in the SQL query. I'm looking into that. In addition, tests with `config.query.bindTimestampRange` set to true need to be developed.

This PR significantly changes how transaction results are retrieved from the database. Both the `/accounts` and `/transactions` endpoints utilize common code (in `transactions.js`) to achieve this. The once large query used (including an inner and outer query construction) has been replaced by two separate, serial queries. The first retrieves the relevant consensus timestamps and payer IDs from the `transaction`, `crypto_transfer` and `token_transfer` tables. The second query is built based on these retrieved values.

In the V2/Citus future, those three tables are distributed (sharded) by the payer ID, and partitioned by the consensus timestamp. Identifying the payer IDs and bounding the timestamp range is important to achieve the best performance. Therefore, timestamp bounds are computed based on what has been provided by the client. If an upper and lower bound are not clearly identified, then they are calculated, to limit the number of partitions accessed.

Note that for multiple equals queries, the values are now ORed rather than ANDed. In the latter case, specifying two or more different equals values resulted in zero transactions being returned. Being ORed, transactions may now be returned.

This PR improves  V2 performance for the following REST API endpoints:
1. /accounts/{id}
2. /accounts/{id}?timestamp=lte:{timestamp}
3. /transactions
4. /transactions?account.id={accountId}
5. /transactions?transactionType={transactionType} (this one has additional complexities due to the type filter - may warrant a separate issue after the completion of this one)

Note:
the `/accounts/{id}?timestamp=lte:{timestamp}` has additional issues with the timestamp query

**Related issue(s)**:

Fixes #6933

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-25 16:35 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration/generator.js
> +    const filename = path.join(dirname, `${group}.spec.test.js`);
now the test module generated for the json spec based integration tests have file names with suffix `.spec.test.js`. This is to facilitate moving some integration test modules to the `integration` folder, without having filename conflict.

2024-01-25 16:36 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/multiple-account-ids.json
> -  "description": "Transaction api calls for transactions from specific accounts using multiple account.id query params",
The test cases in this spec have been merged into `account-id.json`

2024-01-25 16:38 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    func.reset = () => (timestamp = undefined);
for testing purpose, so we can reset the `timestamp` variable in the closure

2024-01-25 16:56 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const parseTimestampFilters = (
a lot of changes here:

- parse and analyze all the filters, instead of honoring the last gt / gte (while giving gt higher priority over gte...) and the last lt / lte (same, giving lt higher priority over lte)
- fixing returning `null` range when there are equal values
- return unique equal values, and unique not equal values
- add a flag to skip empty range / larger than `maxTimestampRange` check
- return `Range()` to indicate the effective range is empty

2024-01-25 20:18 UTC, jascks commented on hedera-mirror-rest/transactions.js
> +    func.reset = () => (timestamp = undefined);
That is pretty cool! 😄

2024-01-25 20:20 UTC, jascks commented on hedera-mirror-rest/__tests__/mockPool.js
> -  createMockTransactions(parsedparams) {
Good riddance...

2024-01-26 02:20 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration/transactions.test.js
> +
missing license header, will add

2024-01-26 02:24 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/testutils.js
> +    let eqParams = sql.match(/(\w+?)\s*?(IN|=\s*?ANY)\s*?\(\s*?((?:\$\d+,?\s*?)+)\)/gi);
will revert changes in this file

2024-01-29 19:08 UTC, edwin-greene approved these changes
Looks good!

2024-01-29 20:16 UTC, steven-sheehy requested changes

2024-01-29 20:16 UTC, steven-sheehy commented on docs/configuration.md
>  | `hedera.mirror.rest.query.maxTimestampRange`                       | 7d                      | The maximum amount of time a timestamp range query param can span for some APIs.
This is probably too small for transactions. We should increase it to at least 30 days and check the performance impact on this API and other endpoints that use it. We can open a ticket to track.

2024-01-29 20:48 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions/success-result.json
> -        "token_transfers": [],
I see, that's confusing. We should consider adding an assert list of ordered keys is equal to a set of ordered keys from response to spec test template.

2024-01-30 02:45 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/success-result.json
> -        "token_transfers": [],
not easy to check, since JSON.parse doesn't provide a way to fail on duplicate keys, it simply takes the last.

2024-01-30 02:50 UTC, xin-hedera commented on hedera-mirror-rest/jest.config.js
> +  reporters: [['github-actions', {silent: false}], 'jest-junit', ['summary', {summaryThreshold: 1}]],
change to the build-in github-actions reporter: https://jestjs.io/docs/configuration#github-actions-reporter

add summary reporter with `summaryThreshold: 1` so any failed test cases will cause a summary at the end. it's quite painful with jest-standard-reporter that the failed test cases are only shown right after the test module, not at the end.

2024-01-30 13:42 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.rest.query.bindTimestampRange`                      | false                   | Whether to bind the timestamp range to maxTimestampRange
That and considering `maxTimestampRange` > 7d to increase the odds of returning results without reading too many partitions. 2 or 3 months maybe?

2024-01-30 15:37 UTC, xin-hedera commented on docs/configuration.md
>  | `hedera.mirror.rest.query.maxTimestampRange`                       | 7d                      | The maximum amount of time a timestamp range query param can span for some APIs.
added a new config property `maxTransactionsTimestampRange`, default is 60 days

2024-01-30 15:43 UTC, jnels124 approved these changes
LGTM

2024-01-30 15:55 UTC, steven-sheehy approved these changes
LGTM

2024-01-30 16:38 UTC, merged