HIP-584 Historical: Fix historical total supply
hashgraph/hedera-mirror-node pull request #7505
Opened 2024-01-09 14:06 UTC by 0xivanov

**Description**:

Executing a `getFungibleTokenInfo/getNonFungibleInfo` for a token that had his `tokenSupply` changed via `burn/mint/wipe` does not return proper historical data.
Minting/burning tokens does not trigger the historical data for the `token_history table`. However, it does change the `totalSupply`, which means the "historical" `totalSupply` field might not be valid for `getTokenInfo` operation.

This PR fixes `TokenDatabaseAccessor` to return proper `totalSupply` with added historical queries.

**Related issue(s)**:

Fixes #7497

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-09 14:14 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    @Disabled
These 2 should get fixed here https://github.com/hashgraph/hedera-mirror-node/pull/7434

2024-01-09 14:19 UTC, 0xivanov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessorTest.java
> +                .returns(0L, Token::getTotalSupply)
This case is tested in `getTotalSupplyHistoricalFungible`, so I don't mock the repo here

2024-01-09 22:12 UTC, xin-hedera requested changes

2024-01-09 22:12 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            account_id = ?2 and
token's supply change don't have to cause transfers to / from the treasury account and not all transfers with treasury involved will change total supply.

For the first category, token wipe account transaction changes total supply but in its record there's no transfer to / from the treasury account.

For the second category, an account `a` can transfer its token to the treasury `t`, this will not change token's total supply

2024-01-10 13:56 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            tt.consensus_timestamp > ?3
@xin-hedera Should't we also include the change that happened in the passed timestamp:
`tt.consensus_timestamp >= ?3`

2024-01-10 14:23 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            account_id = ?2 and
For the second category, I came up with this where clause:
```sql
where
    token_id = ?1 and
    s.timestamp_range @> tt.consensus_timestamp and
    tt.consensus_timestamp >= ?3 and
    (tt.account_id = ?2 or tt.payer_account_id = ?2)
    or (amount < 0 and  
    token_id = ?1 and
    s.timestamp_range @> tt.consensus_timestamp and
    tt.consensus_timestamp >= ?3 and
    tt.payer_account_id <> ?2 and
    exists (
       select 1
       from token_transfer as tt2
       where
        tt2.amount = -tt.amount and
        tt2.payer_account_id = tt.payer_account_id
    )
);
```
This matches all of the transfers to/from the treasury. We know that these records are not burns/mints because they have a pair with opposing amount (10,-10). In the end the transfers negate each other and the burns/mints are calculated

2024-01-10 14:23 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            account_id = ?2 and
For the wipe case, we can do something similar (look which entries do not have matching opposite pair), but i am still thinking how to combine the 2. Any insights?

2024-01-10 15:43 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            account_id = ?2 and
I'm fine with just summing the amount of all token transfers in the timestamp range, even though there can be performance issue.

2024-01-10 15:44 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            tt.consensus_timestamp > ?3
yes we should include any supply change happened at `blockTimestamp`, however the correct answer is `tt.consensus_timestamp > :blockTimestamp`, because the total supply from `token` / `token_history` is at a later timestamp so we should exclude supply changes > blockTimestamp, not >=

2024-01-11 12:08 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            account_id = ?2 and
changed

2024-01-11 12:12 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
> +                            tt.consensus_timestamp > ?3
fixed

2024-01-11 16:50 UTC, xin-hedera approved these changes
LGTM

2024-01-11 19:54 UTC, steven-sheehy approved these changes
LGTM

2024-01-11 19:56 UTC, merged