HIP-584 - Update web3 docs to cover historical support
hashgraph/hedera-mirror-node pull request #7525
Opened 2024-01-12 15:31 UTC by kselveliev

**Description**:
This updates web3 documentation to cover the new historical block support implementation for eth call

Modified classes:
docs/web3/README.md
hedera-mirror-rest/api/v1/openapi.yml

**Related issue(s)**:

Fixes #7482

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-16 08:31 UTC, IvanKavaldzhiev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        The endpoint supports `latest` block. Additionally, it can process calls against the `earliest` block and specific historical blocks when a hexadecimal block number is provided in the `block`
We can point out that we support both decimal and hexadecimal block number format.

2024-01-16 15:27 UTC, steven-sheehy requested changes

2024-01-16 15:27 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        For gas estimation indicated by `estimate` set to true, only the `latest` block can be used.
```suggestion
        Returns a result from EVM execution such as cost-free execution of read-only smart contract queries, gas estimation, and transient simulation of read-write operations. If the `estimate` field is set to true gas estimation is executed. However, gas estimation only supports the `latest` block.
        When `estimate` is false, it can process calls against the `earliest` block and specific historical blocks when a hexadecimal block number is provided in the `block` field for `eth_call` operations.
```

2024-01-17 16:33 UTC, kselveliev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        The endpoint supports `latest` block. Additionally, it can process calls against the `earliest` block and specific historical blocks when a hexadecimal block number is provided in the `block`
Comment addressed

2024-01-17 16:33 UTC, kselveliev commented on docs/web3/README.md
> +| Estimate | Static | Operation Type                                                                            | Supported | Historical data support - eth_call| Reads | Modifications |
Comment addressed

2024-01-17 16:34 UTC, kselveliev commented on docs/web3/README.md
> +| Y        | N      | operations for HTS system contract UnfreezePrecompile                                     | Y         | Y                                 | Y     | Y             |
Comment addressed

2024-01-17 16:34 UTC, kselveliev commented on hedera-mirror-rest/api/v1/openapi.yml
> +        For gas estimation indicated by `estimate` set to true, only the `latest` block can be used.
I applied the above suggestion

2024-01-17 19:05 UTC, steven-sheehy approved these changes
LGTM

2024-01-18 14:53 UTC, IvanKavaldzhiev commented on docs/web3/README.md
> +| Y        | N      | operations for GetApprovedPrecompile                                                      | Y         | Y          | Y     | N             |
`IsApprovedForAllPrecompile`, `AllowancePrecompile` and `GetApprovedPrecompile` are read-only operations that could be executed in a static context. I believe we should have `Y` for them.

2024-01-18 14:55 UTC, IvanKavaldzhiev commented on docs/web3/README.md
> +| Y        | N      | operations for HTS system contract                                                        | Y         | Y          | Y     | Y             |
We have modifying and read-only precompile operations in the HTS system contract. For the read-only we can have static access. We can define two separate rows for each category, with the difference being the Static and Modifications values.

2024-01-19 12:07 UTC, kselveliev commented on docs/web3/README.md
> +| Y        | N      | operations for HTS system contract                                                        | Y         | Y          | Y     | Y             |
Comment addressed

2024-01-19 12:07 UTC, kselveliev commented on docs/web3/README.md
> +| Y        | N      | operations for GetApprovedPrecompile                                                      | Y         | Y          | Y     | N             |
Comment addressed

2024-01-19 17:41 UTC, steven-sheehy approved these changes
LGTM

2024-01-19 18:28 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-01-19 18:34 UTC, merged