feat: Historically accurate stake info /api/v1/accounts/{id}?timestamp
hashgraph/hedera-mirror-node pull request #7544
Opened 2024-01-15 17:22 UTC by stefan-stefanooov

Adding support for Historically accurate stake info in `/api/v1/accounts/{id}?timestamp={timestamp}` endpoint

**Description**:
`/api/v1/accounts/{id}?timestamp={timestamp}` endpoint is updated to provide historically accurate staking info

**Related issue(s)**:
Historically accurate stake info /api/v1/accounts/{id}?timestamp endpoint #6074

2024-01-17 18:21 UTC, xin-hedera requested changes

2024-01-17 18:21 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +      ${paramsHasTimestampRange(params) ? ENTIRY_STAKE_HISTORICAL_QUERY : 'entity_stake'}
instead of checking the params array to determine whether to query the history table with timestamp condition, add a boolean parameter `isHistorical` to `getAccountQuery` and `getEntityBalanceQuery`

2024-01-17 23:31 UTC, steven-sheehy requested changes

2024-01-18 16:01 UTC, stefan-stefanooov commented on hedera-mirror-rest/accounts.js
> +      ${paramsHasTimestampRange(params) ? ENTIRY_STAKE_HISTORICAL_QUERY : 'entity_stake'}
@steven-sheehy I added the tests.
Thank you.

2024-01-18 16:20 UTC, xin-hedera requested changes

2024-01-18 16:20 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/accounts.timestamp-lte-with-entity-stake.test.js
> + * Copyright (C) 2023 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2024 Hedera Hashgraph, LLC
```

2024-01-18 16:20 UTC, xin-hedera commented on hedera-mirror-rest/accounts.js
> +const ENTIRY_STAKE_HISTORICAL_QUERY = (filter) => `(
since this is now a function, should change the name to e.g. `const getEntityStakeQuery = (filter, isHistorical)`

Note the proposed change also incorporates the logic of returning either the subquery or the `entity_stake` table.

2024-01-18 17:48 UTC, xin-hedera approved these changes
LGTM

2024-01-18 18:49 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/accounts.timestamp-lte-with-entity-stake.test.js
I'm not sure why you wrote this integration test. I meant spec jsons in `__tests_/specs`.

2024-01-19 10:47 UTC, stefan-stefanooov commented on hedera-mirror-rest/__tests__/accounts.timestamp-lte-with-entity-stake.test.js
I misunderstood you I guess. 
Still I got to know the integration tests part of the project. 
Tests are moved.

2024-01-19 16:58 UTC, xin-hedera approved these changes
LGTM

2024-01-19 16:58 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp-with-entity-stake.json
> +  "description": "Account api calls for specific account using path and transaction timestamp with entity stake",
would prefer making the changes in an existing spec file, e.g., timestamp-lte.json

2024-01-22 15:39 UTC, steven-sheehy approved these changes

2024-01-22 15:40 UTC, merged