Fix `eth_call` with `extcodehash` on system account
hashgraph/hedera-mirror-node pull request #7546
Opened 2024-01-16 13:23 UTC by 0xivanov

**Description**:
This PR fixes null pointer caused by the default `ExtCodeHashOperation` implementation for system accounts.
Some of the system accounts do not exist in the db, so the world updater returns null for them.

WIP: added `SystemAccount` class and more logic to the get method in the WorldUpdater in order to prevent returning null for system accounts. This actually fixes the issue without the code hash override, but I am not sure which one is preferred, considering the fact that we will start consuming the smart contract library in the future. 

**Related issue(s)**:

Fixes #7517

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-01-16 13:26 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/SystemAccount.java
> +public class SystemAccount extends SimpleAccount {
This class be useful in the future for manipulating different operations for system accounts

2024-01-16 13:55 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
Might be useful to prevent null pointers when interacting with system accounts

2024-01-16 14:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/operations/CustomExtCodeHashOperation.java
> +public class CustomExtCodeHashOperation extends ExtCodeHashOperation {
We shouldn't copy classes from the modularized services code base, since the consensus node still run on the regular mono code. What I saw is we have a similar override in the mono code - `HederaExtCodeHashOperationV038` and we can copy it, instead. 

This approach is compliant with the future integration of `hedera-smart-contract-service`, since we will then use an override of this operation out of the box.

2024-01-17 08:55 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/operations/CustomExtCodeHashOperation.java
> +public class CustomExtCodeHashOperation extends ExtCodeHashOperation {
copied HederaExtCodeHashOperationV038

2024-01-17 16:06 UTC, bilyana-gospodinova approved these changes
LGTM

2024-01-17 16:31 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> +                hederaExtCodeHashOperationV038,
We might want to keep this only for v38, but the default impl does not check for system accounts, so the additional logic MUST be kept

2024-01-17 16:31 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractEvmStackedLedgerUpdater.java
> +    public static boolean isSystemAccount(Address address) {
This is implemented as bean in https://github.com/hashgraph/hedera-mirror-node/pull/7558 so we merge it first

2024-01-17 21:50 UTC, steven-sheehy requested changes

2024-01-17 21:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        // some of them are missing in the db
They are not missing per se, they don't exist in either mirror node or consensus nodes. They are reserved for future use but not created. Below is the range of entities not existing in mirror node and I've confirmed with services that it matches their state as well.

350-399
751-799
802-899

2024-01-17 21:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
Disagree with this approach since it differs from services. Using the appropriate extcodehash operation should resolve this issue and this change is unnecessary and could cause a regression. Specifically for pre-0.38 it should throw an error and not return 0. Should revert changes to this class and remove SystemAccount class.

2024-01-17 21:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> -                        new HederaExtCodeHashOperation(gasCalculator, validator),
We need to support the pre-0.38 behavior in HederaExtCodeHashOperation and the post 0.38 hederaExtCodeHashOperationV038.

2024-01-18 10:09 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
For pre-v38 we expect to revert with `INVALID_SOLIDITY_ADDRESS`?
In services we have the following addressValidator for v0.34:
```java
 @Provides
    @Singleton
    @V_0_34
    static BiPredicate<Address, MessageFrame> provideAddressValidator(
            final Map<String, PrecompiledContract> precompiledContractMap) {
        final var precompiles = precompiledContractMap.keySet().stream()
                .map(Address::fromHexString)
                .collect(Collectors.toSet());
        return (address, frame) ->
                precompiles.contains(address) || frame.getWorldUpdater().get(address) != null;
    }
```
With this validator and `HederaExtCodeHashOperation` as bean we have the following behaviour:
This would return `true` if we pass precompile address `0x167` because it's a precompile address. This causes null pointer in `HederaExtCodeHashOperation`.
The setup I think is the same as in services for v0.34...

2024-01-19 04:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
You're right, it's actually a bug with using extcodehash on a precompile that's present in <v0.38 that would result in a FAIL_INVALID. Good catch.

So we have to either add the null check to the operation like the v038 and the besu operation does or ensure we never return null like you're doing. If we modify the operation then we have to copy it. So probably your SystemAccount approach is better.

2024-01-19 04:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
Still think we should register both HederaExtCodeHashOperation or HederaExtCodeHashOperationV038 depending upon the version since the behavior between the two is drifting apart.

2024-01-19 07:57 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
If we want to revert, different addressValidator needs to be injected to the pre-v0.38 operation. The `SystemAccount` approach would result in returning 0.

2024-01-19 08:02 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
> -                        new HederaExtCodeHashOperation(gasCalculator, validator),
HederaExtCodeHashOperation added

2024-01-19 08:02 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/operations/HederaExtCodeHashOperationV038.java
> +public class HederaExtCodeHashOperationV038 extends ExtCodeHashOperation {
Removed

2024-01-19 22:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractLedgerWorldUpdater.java
> +        return address.numberOfLeadingZeroBytes() >= 18 && address.getInt(16) < 1001;
This logic duplicates strictSystemAccountDetector and AbstractEvmStackedLedgerUpdater but differs slightly. This does not compare unsigned and allows 1000, which I believe is incorrect. We should consolidate the two.

2024-01-19 22:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractEvmStackedLedgerUpdater.java
> +        return address.numberOfLeadingZeroBytes() >= 18 && address.getInt(16) < 1001;
This logic duplicates strictSystemAccountDetector and AbstractLedgerUpdater but differs slightly. This does not compare unsigned and allows 1000, which I believe is incorrect. We should consolidate the two.

2024-01-19 22:36 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +        if (isSystemAccount(address)) {
I'm fine with returning zero as that is what we do post 0.38 and pre 0.38 is buggy.

2024-01-22 08:33 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractEvmStackedLedgerUpdater.java
> +        return address.numberOfLeadingZeroBytes() >= 18 && address.getInt(16) < 1001;
This is not used actually, i forgot to delete it.

2024-01-22 08:35 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractEvmStackedLedgerUpdater.java
> +        return address.numberOfLeadingZeroBytes() >= 18 && address.getInt(16) < 1001;
Are you Ok with the usage of `preV38AddressValidator` to fix the pre-v.38 version of the operation? This way .38 is different than the rest and this is the expected behaviour I believe.

2024-01-22 09:00 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractLedgerWorldUpdater.java
> +        return address.numberOfLeadingZeroBytes() >= 18 && address.getInt(16) < 1001;
Removed

2024-01-22 10:41 UTC, IvanKavaldzhiev commented on .github/workflows/rosetta.yml
> +    tags: [v*]
Probably not expected change in this PR

2024-01-22 10:46 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-01-22 12:11 UTC, 0xivanov commented on .github/workflows/rosetta.yml
> +    tags: [v*]
probably spotless, will revert this change

2024-01-22 18:11 UTC, steven-sheehy approved these changes
LGTM

2024-01-22 18:11 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/AbstractEvmStackedLedgerUpdater.java
> +        return address.numberOfLeadingZeroBytes() >= 18 && address.getInt(16) < 1001;
Yes

2024-01-22 18:11 UTC, merged