Improve staking reward calculation performance
hashgraph/hedera-mirror-node pull request #7554
Opened 2024-01-16 22:54 UTC by edwin-greene

**Description**:

**Related issue(s)**:

Fixes #7478 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-17 00:28 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              ((decline_reward is false and (staked_node_id <> -1 or staked_account_id <> 0)) or (decline_reward is true and staked_account_id <> 0))
rewrite the condition so it's more stragithforward
```suggestion
              (staked_account_id <> 0 or (decline_reward is false and staked_node_id <> -1))
```

do the same for the `entity_history` part

2024-01-17 00:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +            where id = 800 or
can't include 800 in both subqueries (`entity` and `entity_history`), we may end up having two rows for 800 since we do a `union all`

change it to
```suggestion
            where id <> 800 and
```

2024-01-17 00:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +            insert into entity_stake_temp (end_stake_period, id, pending_reward,
when inserting into `entity_stake_temp`, skip entities with indirect staking, i.e., whose staked_account_id <> 0

2024-01-17 20:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              ((decline_reward is false and (staked_node_id <> -1 or staked_account_id <> 0)) or (decline_reward is true and staked_account_id <> 0))
Thanks I have updated this.

2024-01-17 20:33 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +            where id = 800 or
Got it thanks!

2024-01-17 20:34 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +            insert into entity_stake_temp (end_stake_period, id, pending_reward,
I have updated this and added a where clause to not include the indirect staking.

2024-01-19 16:53 UTC, xin-hedera requested changes

2024-01-19 16:53 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntityStake.java
> -    private boolean declineRewardStart;
move the comment on line 35 to line 44

2024-01-19 16:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              where ess.staked_account_id = 0;
make it explicit
```suggestion
              where ess.staked_node_id <> -1;
```

2024-01-19 16:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.92.1__update_entity_stake.sql
> +    drop column if exists decline_reward_start;
drop rows `where decline_reward_start is true`
otherwise since the column is dropped, for entities which staked to a node and opted out rewards, if before the next period completes, it changes to opt in rewards, the calculator will accrue rewards in the just completed period while in fact it shouldn't.

2024-01-19 16:53 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/accounts/no-params.json
> -        "decline_reward_start": false,
update one spec file to test the scenario that the entity's `entity_stake` row reflects its pending rewards at least 2 periods ago since the entity has changed staking settings to

- stake to nothing
- stake to an account
- stake to a node and opt out of rewards

The response should show the entity has 0 pending reward even though the row in `entity_stake` has non-zero value.

2024-01-19 21:59 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.92.1__update_entity_stake.sql
> +    drop column if exists decline_reward_start;
Thanks I have updated the migration to drop those rows.

2024-01-19 21:59 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java
> +              where ess.staked_account_id = 0;
Got it, I have updated it.

2024-01-19 22:00 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/accounts/no-params.json
> -        "decline_reward_start": false,
Thanks, I have added those cases to `no-params.json`

2024-01-19 22:00 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractEntityStake.java
> -    private boolean declineRewardStart;
Sounds good I have moved it.

2024-01-19 23:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.92.1__update_entity_stake.sql
> +
Should we do any cleanup of existing rows to reduce unnecessary data?

2024-01-23 15:54 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.92.1__update_entity_stake.sql
> +
Thanks I have updated the migration to remove unnecessary rows from entity_stake and entity_stake_history.

2024-01-23 19:30 UTC, steven-sheehy approved these changes
LGTM

2024-01-23 20:27 UTC, xin-hedera approved these changes
LGTM

2024-01-23 22:26 UTC, merged