Refactor acceptance tests to use OpenAPI generated models
hashgraph/hedera-mirror-node pull request #7565
Opened 2024-01-18 18:00 UTC by jascks

### Problem
**Description**:
**Not yet ready for review. Just want to make sure there are no CI issues with my gradle changes thus far. There will likely be more tweaking and the acceptance tests have not yet been updated to utilize the generated models.**

As with `monitor` and `rest-java`, for the `test` module use the REST API OpenAPI spec to generate the model classes for API requests and response handling. Update tests to use the generated models and delete them manually created POJOs.

* Updated gradle `buildSrc` defined `openapi-conventions` separate from `spring-conventions` for use by any module requiring source code generation based on the OpenAPI spec.
* Configured the `test` module's build to use the OpenAPI generator.
* Changed all code using manually coded POJOs in `com/hedera/mirror/test/e2e/acceptance/(props|response)` to use the generated models.
* Deleted the models in `com/hedera/mirror/test/e2e/acceptance/(props|response)`.

**Related issue(s)**:

Fixes #7377

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-18 18:18 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
>  java.sourceSets["main"].java { srcDir(openApiGenerate.outputDir) }
Move this to openapi-conventions in all files

2024-01-18 18:18 UTC, steven-sheehy commented on buildSrc/src/main/kotlin/openapi-conventions.gradle.kts
> +        extension.apiPackage = "${openApiPackage}.api"
We should no longer export this to extra.

```suggestion
val openApiPackage = "com.hedera.mirror.rest"
openApiGenerate {
    apiPackage = "${openApiPackage}.api"
    ...
```

2024-01-18 18:18 UTC, steven-sheehy commented on hedera-mirror-test/build.gradle.kts
> +import org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension
Remove import

2024-01-18 18:53 UTC, jascks commented on hedera-mirror-rest-java/build.gradle.kts
>  java.sourceSets["main"].java { srcDir(openApiGenerate.outputDir) }
Done

2024-01-18 18:53 UTC, jascks commented on buildSrc/src/main/kotlin/openapi-conventions.gradle.kts
> +        extension.apiPackage = "${openApiPackage}.api"
Done

2024-01-18 18:54 UTC, jascks commented on hedera-mirror-test/build.gradle.kts
> +import org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension
Done

2024-01-24 22:46 UTC, jascks commented
Just ran full command line @acceptance, and I am looking into this one failure:
```
java.lang.AssertionError: 
Expecting actual:
  [class TransactionDetailAllOfAssessedCustomFees {
    amount: 100
    collectorAccountId: 0.0.45699
    effectivePayerAccountIds: [0.0.45725]
    tokenId: null
},
    class TransactionDetailAllOfAssessedCustomFees {
    amount: 20
    collectorAccountId: 0.0.45715
    effectivePayerAccountIds: [0.0.45699]
    tokenId: 0.0.45718
}]
to contain exactly in any order:
  [class TransactionDetailAllOfAssessedCustomFees {
    amount: 100
    collectorAccountId: 0.0.45699
    effectivePayerAccountIds: null
    tokenId: null
},
    class TransactionDetailAllOfAssessedCustomFees {
    amount: 20
    collectorAccountId: 0.0.45715
    effectivePayerAccountIds: null
    tokenId: 0.0.45718
}]
elements not found:
  [class TransactionDetailAllOfAssessedCustomFees {
    amount: 100
    collectorAccountId: 0.0.45699
    effectivePayerAccountIds: null
    tokenId: null
},
    class TransactionDetailAllOfAssessedCustomFees {
    amount: 20
    collectorAccountId: 0.0.45715
    effectivePayerAccountIds: null
    tokenId: 0.0.45718
}]
and elements not expected:
  [class TransactionDetailAllOfAssessedCustomFees {
    amount: 100
    collectorAccountId: 0.0.45699
    effectivePayerAccountIds: [0.0.45725]
    tokenId: null
},
    class TransactionDetailAllOfAssessedCustomFees {
    amount: 20
    collectorAccountId: 0.0.45715
    effectivePayerAccountIds: [0.0.45699]
    tokenId: 0.0.45718
}]

	at com.hedera.mirror.test.e2e.acceptance.steps.TokenFeature.verifyTransactions(TokenFeature.java:609)
	at com.hedera.mirror.test.e2e.acceptance.steps.TokenFeature.verifyMirrorTokenFundFlow(TokenFeature.java:427)
	at ✽.the mirror node REST API should return the transaction for token fund flow with assessed custom fees(classpath:features/token/token.feature:84)
```

2024-01-25 22:08 UTC, steven-sheehy requested changes

2024-01-25 22:08 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        mockAddress = ContractResponseUtil.of(callContract(data, contractSolidityAddress)).getResultAsAddress();
Should just change parent `callContract()` to return `ContractResponseUtil` directly instead of wrapping it everywhere. This greatly reduces the overall number of changes.

2024-01-25 22:08 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        // TODO some kind of domain builder class needed? See how extensive this is
Remove TODO

2024-01-25 22:08 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void verifyMirrorTokenFundFlow(List<TransactionDetailAllOfAssessedCustomFees> assessedCustomFees) {
Is there any way to customize this terrible name? In the spec it's just `TransactionDetail`.

2024-01-26 02:13 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ContractResponseUtil.java
> +package com.hedera.mirror.test.e2e.acceptance.util;
no license header?

2024-01-26 02:13 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ModelBuilder.java
> +
license header

2024-01-26 02:13 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/token/token.feature
> +      | amount | collector | effective | token |
should name it `effectivePayer` instead

2024-01-26 02:13 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/converter/CustomFeesConverter.java
> +        }
there's redundant null check for effective payer, should just check once

2024-01-26 15:25 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +            next = response.getLinks().getNext();
I finally remembered why that changed. After reverting this, IDEA highlighted it immediately. I believe I previously accepted IDEA's hint after moving to the generated model:

![Screenshot 2024-01-26 at 8 21 01 AM](https://github.com/hashgraph/hedera-mirror-node/assets/218465/3b1b7eea-1497-4018-9c93-c2ef1724103b)

But, looking at `NetworkNodesResponse`, the links field returned can certainly be null. Interesting.

2024-01-27 22:15 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/converter/CustomFeesConverter.java
> +        }
That is a little embarrassing. Fixed!

2024-01-27 22:15 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/token.feature
> +      | amount | collector | effective | token |
Done

2024-01-27 22:15 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ModelBuilder.java
> +
Done

2024-01-27 22:15 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ContractResponseUtil.java
> +package com.hedera.mirror.test.e2e.acceptance.util;
Done

2024-01-27 22:17 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void verifyMirrorTokenFundFlow(List<TransactionDetailAllOfAssessedCustomFees> assessedCustomFees) {
Still looking into this one. 😄

2024-01-27 22:18 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +            next = response.getLinks().getNext();
Done

2024-01-27 22:18 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ContractResponseUtil.java
> +public class ContractResponseUtil {
Done

2024-01-27 22:18 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ModelBuilder.java
> +    }
Done

2024-01-27 22:18 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +        var estimateGasValue = Bytes.fromHexString(response.getResult()).toBigInteger().intValue();
Done

2024-01-27 22:19 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        mockAddress = ContractResponseUtil.of(callContract(data, contractSolidityAddress)).getResultAsAddress();
Done, but still no as cleaned as I'd like. Still lots of changes. Looking into it.

2024-01-27 22:19 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> +        // TODO some kind of domain builder class needed? See how extensive this is
Done

2024-01-28 20:03 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void verifyMirrorTokenFundFlow(List<TransactionDetailAllOfAssessedCustomFees> assessedCustomFees) {
There is a `TransactionDetail` model generated. With the spec definition as:
```
    TransactionDetail:
      allOf:
        - $ref: "#/components/schemas/Transaction"
        - type: object
          properties:
            assessed_custom_fees:
              type: array
              items:
                type: object
                properties:
                  amount:
                    format: int64
                    type: integer
                  collector_account_id:
                    $ref: "#/components/schemas/EntityId"
                  effective_payer_account_ids:
                    type: array
                    items:
                      $ref: "#/components/schemas/EntityId"
                  token_id:
                    $ref: "#/components/schemas/EntityId"
```
`TransactionDetail` has all of the properties of `Transaction` as described, but in addition this array `accessed_custom_fees` with elements containing the four custom fee related properties.

```
  private List<TransactionDetailAllOfAssessedCustomFees> assessedCustomFees;
```
So, the generator is getting creative in naming the model for each 'array' element. I've not yet found a solution for overriding this naming, but I'll look a while longer.

2024-01-28 20:47 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void verifyMirrorTokenFundFlow(List<TransactionDetailAllOfAssessedCustomFees> assessedCustomFees) {
I could not find anything definitive on renaming that class at generation time. There was some references to some config possibilities, include tags, but the schema validator did not be to use tags where it made sense.

However, I did learn that in the spec example above, that is an inline schema. And as you can see, the generator just took the component name, `TransactionDetail`, `allOf` and the name of the additional property and stuck on `AllOfAssessedCustomFees`.

So, instead of an inline schema I defined it explicitly:
```
    AssessedCustomFee:
      type: object
      properties:
        amount:
          format: int64
          type: integer
        collector_account_id:
          $ref: "#/components/schemas/EntityId"
        effective_payer_account_ids:
          type: array
          items:
            $ref: "#/components/schemas/EntityId"
        token_id:
          $ref: "#/components/schemas/EntityId"
```
And simply reference that in `TransactionDetail`:
```
    TransactionDetail:
      allOf:
        - $ref: "#/components/schemas/Transaction"
        - type: object
          properties:
            assessed_custom_fees:
              type: array
              items:
                $ref: "#/components/schemas/AssessedCustomFee"
```
The generated `TransactionDetail` model now defines:
```
  private List<AssessedCustomFee> assessedCustomFees;
```
And, `AssessedCustomFee` is a much better name. 😄

2024-01-29 23:24 UTC, steven-sheehy approved these changes
LGTM

2024-01-30 01:36 UTC, xin-hedera approved these changes
LGTM

2024-01-30 13:59 UTC, merged