feat: Support RC5988 next link #5879
hashgraph/hedera-mirror-node pull request #7569
Opened 2024-01-19 11:38 UTC by stefan-stefanooov

**Description**:
Inside a middleware, inspect the payload for a links.next and set it in the Link response header:

Link: ${links.next}; rel="next"

**Related issue(s)**:

Fixes #
Support RC5988 next link
[#5879](https://github.com/hashgraph/hedera-mirror-node/issues/5879)

2024-01-19 18:23 UTC, steven-sheehy requested changes

2024-01-19 18:23 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseHandler.js
> +const linkNextHeaderValue = (linksNext) => `${linksNext}; rel="next"`
Reading the spec again and it looks like we missed the angled brackets. Please double check the RFC.

```suggestion
const linkNextHeaderValue = (linksNext) => `<${linksNext}>; rel="next"`
```

2024-01-19 18:23 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseHandler.js
> +    const linksNext = res.locals.responseData.links?.next;
Please add tests to `responseHandler.test.js` to verify existence and non-existence.

2024-01-19 18:23 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseHandler.js
> +      res.set(LINK_NEXT_HEADER, linkNextHeaderValue(linksNext));
We have a `responseContentType` in some specs to verify that response header. We should convert that field to an optional response headers map to assert in the json like in `responseHeaders: {"Content-Type": "application/json", "Link": "..."}`. Then update `template.js` to assert the new `responseHeaders`. Please update an existing spec in `__tests__/specs/` that has a next link already populated and set it in `responseHeaders`.

2024-01-22 08:11 UTC, stefan-stefanooov commented on hedera-mirror-rest/middleware/responseHandler.js
> +    const linksNext = res.locals.responseData.links?.next;
Sure thing.

2024-01-22 14:33 UTC, stefan-stefanooov commented on hedera-mirror-rest/middleware/responseHandler.js
> +      res.set(LINK_NEXT_HEADER, linkNextHeaderValue(linksNext));
@steven-sheehy (@xin-hedera)
Hello
The above comments are taken care of. 

Regarding this one. 
There is already a functionality, like the one you described, implemented.
You could add 

> "responseHeaders": {
    "Link": "</api/v1/accounts?account.id=lt:0.0.21&account.id=gt:0.0.20&limit=3>; rel=\"next\""
  }

to any `.json` test. And it will be forwarded to the template. [REF](https://github.com/hashgraph/hedera-mirror-node/blob/170b2f86c3a164ddd8ec6d54c7a6d5881238dffe/hedera-mirror-rest/__tests__/integration/template.js#L343)
In here we are matching the passed object to the `headers` property of the `supertest` library response object.

But still we are not getting the headers form `supertest` and I am not sure why.
When doing a real world test and in the unit tests I can see/test the headers.

Could you have a look and advice ? 

PS: 
For example I have added a `responseHeaders` object in `accounts-range.json` and uploaded it here.
The test fails.

2024-01-22 15:37 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseHandler.js
> +      res.set(LINK_NEXT_HEADER, linkNextHeaderValue(linksNext));
change the key to all lowercase in the spec file, i.e., `Link` -> `link`

2024-01-22 16:08 UTC, stefan-stefanooov commented on hedera-mirror-rest/middleware/responseHandler.js
> +      res.set(LINK_NEXT_HEADER, linkNextHeaderValue(linksNext));
Yeah. worked! Thanks @xin-hedera 
It's ready for review

2024-01-22 17:43 UTC, steven-sheehy approved these changes
LGTM

2024-01-22 17:59 UTC, xin-hedera approved these changes
LGTM

2024-01-22 18:01 UTC, merged