Openapi generation for  nft allowance api
hashgraph/hedera-mirror-node pull request #7570
Opened 2024-01-19 19:59 UTC by mgoelswirlds

**Description**:
This PR adds the nft allowance APIs openapi doc. **This API is currently under development and is not supported yet**

This PR modifies 
* Adds NFT allowance API openapi documentation
* Modified allowances doc to reflect latest API design.

**Related issue(s)**:

Fixes #7498

**Notes for reviewer**:

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-19 20:04 UTC, mgoelswirlds commented on docs/web3/README.md
> -_Note:_ Gas estimation only supports the `latest` block
This file is here because of some auto formatting issue. Removing it soon.

2024-01-19 20:53 UTC, steven-sheehy requested changes

2024-01-19 20:53 UTC, steven-sheehy commented on docs/design/allowances.md
>  ```
The filters are not up to date. Should scan the whole doc and make any necessary changes.

2024-01-19 20:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: "#/components/schemas/NftLink"
We usually just link to the common one. You can delete NftLink. This will allow a shared generated model.

```suggestion
          $ref: "#/components/schemas/Links"
```

2024-01-19 20:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +              $ref: "#/components/schemas/TimestampRange"
```suggestion
        timestamp:
          $ref: "#/components/schemas/TimestampRange"
```

2024-01-19 20:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: boolean
Needs a description and example

2024-01-19 20:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        timestamp:
nit: Move timestamp before token_id

2024-01-19 20:53 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: If provided and set to true the accountId path parameter will be treated as the owner.id, else it will be treated as spender.id
There are no owner.id or spender.id. Should drop the .id and describe how the response changes like HIP does

2024-01-25 08:28 UTC, mgoelswirlds commented on docs/design/allowances.md
>  ```
Merging from main undid my changes. But I will update the entire doc.

2024-01-25 08:41 UTC, mgoelswirlds commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: boolean
An example already exists. Not sure where else do I need to add one?

2024-01-25 22:24 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        |               | gt(e)               | Y       | Single occurrence only. Requires the presence of an **gte** or **eq** **spender.id** query | ?account.id=gte:X&token.id=gt:Y |
Might be best to just copy the latest from the HIP for this API description.

```suggestion
        |               | lt(e)               | Y       | Single occurrence only. Requires the presence of an **lte** or **eq** **account.id** query | ?account.id=lte:X&token.id=lt:Y |
        |               | gt(e)               | Y       | Single occurrence only. Requires the presence of an **gte** or **eq** **account.id** query | ?account.id=gte:X&token.id=gt:Y |
```

2024-01-26 02:01 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: When the owner value is true or omitted, the accountId path parameter will specify the ID of the owner, and the API will retrieve the allowances that the owner has granted to diffe
should try to make the description consistent. In the HIP, it mentions the default is `true`. In the design doc `allowances.md`, it's missing. Here it says `when the owner value is true or omitted`

2024-01-26 07:13 UTC, mgoelswirlds commented on docs/design/allowances.md
> +- `owner`: Indicates whether the path parameter `accountId` is the owner or the spender ID. Accepts a boolean value of `true` or `false` with a default value set to `true`.
This is where we do mention that the default value for owner is true.Also the API description on the top explains in detail how the accoundId path parameter changes based on the owner flag.

2024-01-26 07:34 UTC, mgoelswirlds commented on docs/design/allowances.md
> +This API accepts a path parameter that represents either the owner or spender, depending on a boolean flag provided as a query parameter called `owner`. When the `owner` value is true, the `accountId
This description explains the relation between owner and the accountId path parameter which is the main difference in this API. I am adding that the flag can be omitted.

2024-01-26 07:34 UTC, mgoelswirlds commented on docs/design/allowances.md
> +- `account.id`: Filter by the spender account ID or owner account ID, depending on the owner flag. `ne` operator is not supported. Only one occurrence is allowed.
The description above explains that.

2024-01-26 08:07 UTC, mgoelswirlds commented on docs/design/allowances.md
> +- `owner`: Indicates whether the path parameter `accountId` is the owner or the spender ID. Accepts a boolean value of `true` or `false` with a default value set to `true`.
This is where we do mention that the default value for owner is true.Also the API description on the top explains in detail how the accoundId path parameter changes based on the owner flag.

2024-01-26 15:43 UTC, xin-hedera commented on docs/design/allowances.md
> +- `account.id`: Filter by the spender account ID or owner account ID, depending on the owner flag. `ne` operator is not supported. Only one occurrence is allowed.
isn't it vague by exactly how owner flag affects what account.id means?

2024-01-26 15:45 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-01-26 15:50 UTC, mgoelswirlds commented on docs/design/allowances.md
> +- `account.id`: Filter by the spender account ID or owner account ID, depending on the owner flag. `ne` operator is not supported. Only one occurrence is allowed.
Ohh ok you mean explaining the filter in detail. I will add information there.

2024-01-26 16:09 UTC, xin-hedera approved these changes
LGTM

2024-01-26 17:19 UTC, steven-sheehy approved these changes

2024-01-26 20:15 UTC, merged