Enable direct calls to precompile addresses
hashgraph/hedera-mirror-node pull request #7616
Opened 2024-01-25 13:38 UTC by georgi-l95

**Description**:
This PR enables direct calls to ethereum precompile addresses, by bypassing the INVALID_TRANSACTION check, when to address is between 0x01 and 0x09. 
Also adds new method which is responsible for checking whether the passed address is precompile address or not.

**Related issue(s)**:

Fixes #7608 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-25 15:20 UTC, stoqnkpL commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java
> +    void precompileCallSucceds() {
```suggestion
    void precompileCallSucceeds() {
```

2024-01-25 15:24 UTC, stoqnkpL submitted a review, later dismissed
LGTM

2024-01-25 15:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +    public boolean isPrecompileAddress(Address addressOrAlias) {
To avoid confusion with the Hedera specific precompiles, probably we can rename this method to `isNativePrecompileAddress`

2024-01-25 15:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            final var isNotCallingPrecompile = !aliasManager.isPrecompileAddress(resolvedForEvm);
isNotCallingPrecompile -> isNotCallingNativePrecompile

2024-01-25 16:43 UTC, georgi-l95 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java
> +    void precompileCallSucceds() {
fixed 🙏

2024-01-25 16:43 UTC, georgi-l95 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +    public boolean isPrecompileAddress(Address addressOrAlias) {
Corrected 🙏

2024-01-25 16:45 UTC, georgi-l95 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            final var isNotCallingPrecompile = !aliasManager.isPrecompileAddress(resolvedForEvm);
Corrected 🙏

2024-01-25 17:02 UTC, stoqnkpL submitted a review, later dismissed
LGTM

2024-01-25 17:09 UTC, yiliev0 submitted a review, later dismissed
LGTM

2024-01-25 19:39 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-01-25 23:47 UTC, steven-sheehy requested changes

2024-01-25 23:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +    }
This narrowing conversion to Long could result in an exception for high numbered addresses. Safer to do comparison using address itself.

```suggestion
    public boolean isNativePrecompileAddress(Address address) {
        return address != null && address.compareTo(Address.ZERO) > 0 && address.compareTo(TEN) < 0;
    }
```

2024-01-25 23:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliasesTest.java
> +        assertFalse(mirrorEvmContractAliases.isNativePrecompileAddress(Address.fromHexString(HEX)));
Replace junit assertions everywhere with assertj assertThat.

2024-01-25 23:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliasesTest.java
> +    void isPrecompileAddressShouldReturnTrue() {
Seems like a parameterized test might be more appropriate with `@ValueSource(ints={1,2,3,4,5,6,7,8,9}`. Could do similarly for negative with 0, 10, 100

2024-01-26 08:06 UTC, georgi-l95 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliasesTest.java
> +    void isPrecompileAddressShouldReturnTrue() {
Fixed, using paramatized test 👍

2024-01-26 08:07 UTC, georgi-l95 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliasesTest.java
> +        assertFalse(mirrorEvmContractAliases.isNativePrecompileAddress(Address.fromHexString(HEX)));
Replaced.

2024-01-26 14:52 UTC, georgi-l95 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/account/MirrorEvmContractAliases.java
> +    }
You're right, yes. Fixed.

2024-01-26 15:41 UTC, steven-sheehy approved these changes
LGTM

2024-01-26 15:43 UTC, merged