Add support for HIP-844 signature nonce
hashgraph/hedera-mirror-node pull request #7617
Opened 2024-01-25 19:40 UTC by edwin-greene

**Description**:
Protobuf 0.47.0 introduces the signature_nonce. For protobuf versions 0.47.0 and above this PR adds support for updating the Entity `ethereum_nonce` to the signature nonce value if the signature_nonce is present in the protobuf. If it is not present then the `ethereum_nonce` value will be unchanged. 

For backward compatibility if the protobuf version is below 0.47.0, then the `ethereum_nonce` will be incremented as before.

**Related issue(s)**:

Fixes #7547 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-01-29 18:14 UTC, xin-hedera requested changes

2024-01-29 18:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +            var status = recordItem.getTransactionRecord().getReceipt().getStatus();
nit
```suggestion
            var status = transactionRecord.getReceipt().getStatus();
```

2024-01-29 18:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        recordItem.addEntityId(senderId);
this would send an empty entity update when HAPI >= 0.47 and `functionResult.hasSignerNonce() == false`

2024-01-29 18:14 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandlerTest.java
> +        if (status == ResponseCodeEnum.WRONG_NONCE && setPriorHapiVersion) {
In general, it's bad to have conditionals when asserting the expected values. In most cases, we should change to directly provide the input and the expected output. Or we can split it to multiple test cases.

2024-01-29 18:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        } else if (recordItem.getHapiVersion().isLessThan(RecordFile.HAPI_VERSION_0_47_0)) {
not a change request. we need to make sure services set the correct HAPI version, at least I see it's still 0.44 for release 0.46.x...

2024-01-29 21:13 UTC, edwin-greene commented on docs/importer/README.md
> +| v0.43.0+     | v0.89.0+            | False           | [HIP-786](https://hips.hedera.com/hip/hip-786): Enriched staking metadata exports                                   |
Thanks I have removed it

2024-01-29 21:14 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +            var status = recordItem.getTransactionRecord().getReceipt().getStatus();
Thanks I have updated it to reuse the existing variable.

2024-01-29 21:14 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        recordItem.addEntityId(senderId);
Great thanks. I have added a fix to this problem and updated the test case for it.

2024-01-29 21:15 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
>                  .setFunctionParameters(bytes(64))
It is set on line 357, or should it be set in additional places?

2024-01-29 21:15 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEthereumTest.java
> +    void ethereumTransactionSignatureNonce(boolean create, boolean setPriorHapiVersion) {
Thanks I have updated this.

2024-01-29 21:15 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEthereumTest.java
> +    void ethereumTransactionNullSignatureNonce(boolean create) {
Sounds good I have updated it.

2024-01-29 21:16 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandlerTest.java
> +        if (status == ResponseCodeEnum.WRONG_NONCE && setPriorHapiVersion) {
Sounds good, I have updated the tests to pass in an expected nonce value rather than having conditional logic in the test case.

2024-01-29 21:55 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
>                  .setFunctionParameters(bytes(64))
Nevermind, must've missed it

2024-01-29 22:15 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        recordItem.addEntityId(senderId);
It would be slightly more performant to not create the entity unless you're going to update it. Can instead have a `Long nonce = null;` at the beginning and set it in the conditionals and create entity at the bottom.

2024-01-30 17:11 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
> +        recordItem.addEntityId(senderId);
Excellent thanks. I have updated it to not create the entity unless a nonce is present.

2024-01-30 17:14 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Should we wait for the GA protobuf before merging?

2024-01-30 18:28 UTC, xin-hedera approved these changes
LGTM

2024-01-30 18:41 UTC, mgoelswirlds approved these changes

2024-01-30 21:23 UTC, xin-hedera submitted a review, later dismissed

2024-01-31 04:37 UTC, Nana-EC submitted a review, later dismissed

2024-01-31 04:40 UTC, Nana-EC commented
> Member

Should be able to use the 0.47.0-alpha.0 instead of snapshot.
Protobuf won't see any changes between that and the GA version.

2024-02-02 18:36 UTC, steven-sheehy approved these changes

2024-02-02 19:13 UTC, merged