Update rest test docker image to include init.sql
hashgraph/hedera-mirror-node pull request #7651
Opened 2024-01-31 16:11 UTC by edwin-greene

**Description**:
Updates the rest test docker image to include init.sql

**Related issue(s)**:

Fixes #7561 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-01-31 17:21 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const initSqlPath = path.resolve('../../hedera-mirror-node/hedera-mirror-common/src/test/resources/init.sql');
Use path.join for cross platform compatibility

```suggestion
  const initSqlPath = path.join('..', '..', 'hedera-mirror-node', 'hedera-mirror-common', 'src', 'test', 'resources', 'init.sql');
```

2024-01-31 17:22 UTC, xin-hedera requested changes

2024-01-31 17:22 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const initSqlPath = path.resolve('../../hedera-mirror-node/hedera-mirror-common/src/test/resources/init.sql');
umm, doubt we should even have such a ticket.

First of all, the changes here actually don't affect rest api integration tests *much*. The only thing that takes effect when running the integration tests is the username is now `mirror_node`.

The database setup is very different in rest api integration tests than subprojects. In globalSetup.js

- a postgresql container starts
- multiple databases are created, one for each jest worker
- the database connection URL is exported as an env variable

Then, in an integration test module, inside `setupIntegrationTest`, `createPool` will create the global `pool` which points to the database associated with the jest worker.

Doing so, enables us to conserve resources with a single postgresql container while running multiple integration test modules in different jest workers in parallel.

Unless we want to change how it's setup, I don't see the value of using the common init.sql script here.

2024-01-31 17:32 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const initSqlPath = path.resolve('../../hedera-mirror-node/hedera-mirror-common/src/test/resources/init.sql');
Is it possible to configure the test setup to use db owner but change the regular user to use `mirror_rest`?

2024-01-31 17:41 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const initSqlPath = path.resolve('../../hedera-mirror-node/hedera-mirror-common/src/test/resources/init.sql');
that'll require some changes (exporting and using owner user and password in addition when running migrations) because the other optimization is the database migrations are done lazily by `flywayMigrate` called by `setupIntegrationTest`. This way the migrations won't run if for a certain jest worker all it does is just unit tests.

2024-02-05 18:53 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const initSqlPath = path.resolve('../../hedera-mirror-node/hedera-mirror-common/src/test/resources/init.sql');
Thanks I have updated it to use the read only user for the Rest tests.

2024-02-05 19:13 UTC, xin-hedera requested changes

2024-02-05 19:13 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalTeardown.js
> +  await getDatabases().forEach((d) => d.stop());
```suggestion
  await Promise.all(getDatabases().forEach((d) => d.stop()));
```

2024-02-05 19:13 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalSetup.js
> +const getReadOnlyPassword = () => 'mirror_rest_java_pass';
```suggestion
const getReadOnlyUser = () => 'mirror_rest';
const getReadOnlyPassword = () => 'mirror_rest_pass';
```

2024-02-05 19:13 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
>    const apiUsername = `${defaultDbConfig.username}_${workerId}`;
remove the `apiUsername` hack which is needed when we use multiple databases hosted by a single server.

2024-02-05 22:34 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/globalSetup.js
> +  const initSqlPath = path.resolve('../../hedera-mirror-node/hedera-mirror-common/src/test/resources/init.sql');
Thanks I have updated it to use path.join

2024-02-05 22:35 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/globalSetup.js
> +    'hedera-mirror-node',
Thanks for spotting this, I have removed the unnecessary directories

2024-02-05 22:35 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/globalTeardown.js
> +  await getDatabases().forEach((d) => d.stop());
Sounds good I have added the Promise.all

2024-02-05 22:35 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/globalSetup.js
> +const getReadOnlyPassword = () => 'mirror_rest_java_pass';
Thanks I have made this change, I needed to add that user to init.sql as well.

2024-02-05 22:46 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalTeardown.js
> +  await getDatabases().forEach((d) => d.stop());
umm, I missed it's `forEach()`, to use Promise.all to chain all the promises, we need to change to `map()`

2024-02-06 01:30 UTC, xin-hedera approved these changes
LGTM

2024-02-06 03:36 UTC, steven-sheehy approved these changes
LGTM

2024-02-06 14:40 UTC, merged