HIP-859 Add gas consumed field in ContractResult
hashgraph/hedera-mirror-node pull request #7657
Opened 2024-02-01 08:39 UTC by MrValioBg

**Description**:

This is a DRAFT PR and is not yet ready for a review :)

**Related issue(s)**:

Fixes #7543 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-02-01 15:28 UTC, steven-sheehy commented
There's 5 sub-tasks of https://github.com/hashgraph/hedera-mirror-node/issues/7543 but this PR looks like it's targeting to fix the first 3. Thus it should mark this as fixing each one. Also, as I [mentioned](https://github.com/hashgraph/hedera-mirror-node/issues/7586#issuecomment-1904241844) we should have one migration for both DDL and historical migration so it should probably fix the first 4 issues.

2024-02-05 13:16 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +        if (!sidecarProperties.isEnabled()) {
Seeking opinions on this @steven-sheehy  
I am think it makes more sense that we should execute the DDL even if sidecars are disabled.

Otherwise, if we opt to execute the DDL for the gas_consumed field only when sidecars are enabled, it might raise several issues:
- We would need to adjust the REST module to handle this case, and it does not sounds conceptually well to return field as null thats not a column in the database or having it appear only under certain conditions. - Documenting the behaviour would be challenging and would make integration testing harder.

However if we want to do it in one migration as [mentioned ](https://github.com/hashgraph/hedera-mirror-node/issues/7586#issuecomment-1904241844), even if every time we have the DDL for gas_consumed get executed, another issue arises:
If the migration is initially executed with disabled sidecars, it wouldn't execute a second time, thus not altering the historical data in contract_result table.

Possible solutions include: 
- Using two migrations. 
- Making it a repeatable migration.

2024-02-05 13:20 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +        if (!sidecarProperties.isEnabled()) {
Note: Will include integration tests in the PR for the migration after the behaviour is specified.

2024-02-05 18:43 UTC, xin-hedera requested changes

2024-02-05 18:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/GasCalculatorHelper.java
> +    public static long addIntrinsicGas(final long gas, final ByteString initByteCode) {
I don't see why we need to pass `gas` to the function, can remove `gas` and rename the function to `getIntrinsicGas` or `calculateIntrinsicGas`

2024-02-05 18:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +    private static final String ADD_GAS_CONSUMED_COLUMN =
unless I missed some requirements, this should be a pure SQL migration instead of a Java based flyway migration.

The bottom line is the DDL should be a pure SQL migration, otherwise integration tests of non-importer modules (e.g., rest api) will fail since we currently don't have a mechanism to run DDL in java migration there.

2024-02-05 18:43 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +        if (!sidecarProperties.isEnabled()) {
we should add the column regardless of importer config

2024-02-05 18:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  gas_consumed: null,
the failures in rest integration tests for `gas_consumed` does not esit are caused by the fact the DDL adding `gas_consumed` is in a java migration as I pointed out

2024-02-06 04:20 UTC, steven-sheehy requested changes

2024-02-06 04:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/GasCalculatorHelper.java
> +                ++zeros;
This should short circuit the loop on first non-zero byte. Prefer to use a standard util like ArrayUtils.indexOf() or similar.

2024-02-06 04:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/GasCalculatorHelper.java
> +        long costForByteCode = TX_BASE_COST + TX_DATA_ZERO_COST * zeros + ISTANBUL_TX_DATA_NON_ZERO_COST * nonZeros;
Is it possible that any initcode from the past would not use istanbul prices? That is, do we need any different price depending upon timestamp?

2024-02-06 04:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return new SidecarProcessingResult(failedInitcode, totalGasUsed);
Since we don't want a Java migration, it might be more maintainable to not have a separate static util and instead have the intrinsic gas calculation moved to `sidecarProcessingResult.getIntrinsicGas()`.

2024-02-06 04:20 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplIntegrationTest.java
> +        assertThat(contractResult.getGasConsumed()).isEqualTo(21150L);
Take advantage of assertj's chaining. Same comment for other tests.

```suggestion
        assertThat(contractResultRepository.findById(recordItem.getConsensusTimestamp())
            .isNotNull()
            .extracting(ContractResult::getGasConsumed)
            .isNotNull()
            .isEqualTo(21150L);
```

2024-02-06 11:42 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/GasCalculatorHelper.java
> +        long costForByteCode = TX_BASE_COST + TX_DATA_ZERO_COST * zeros + ISTANBUL_TX_DATA_NON_ZERO_COST * nonZeros;
The HIP for sidecars, [HIP-513](https://hips.hedera.com/hip/hip-513), is included in release v36, and even before that, we used Istanbul pricing, so we wouldn't need to factor in different pricing. The class GasCalculatorHederaV22 has been there since 01.2022, while the HIP was proposed in 06.2022.

2024-02-06 11:45 UTC, MrValioBg commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractResult.java
> +    private Long gasConsumed;
Done.

2024-02-06 17:36 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +                    Map.of("consensusTimestamp", consensusTimestamp, "gasConsumed", gasConsumed));
Hmm, how we could test with similar amount of data, from where we could get it?

2024-02-06 17:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +                    Map.of("consensusTimestamp", consensusTimestamp, "gasConsumed", gasConsumed));
Can just generate random data yourself. It doesn't have to be exact, just a good amount of data. Need to time the process and also use explain analyze to confirm the queries are optimal.

2024-02-07 12:58 UTC, MrValioBg commented on hedera-mirror-rest/model/contractResult.js
> +  static GAS_CONSUMED = 'gas_consumed';
Done.

2024-02-07 12:58 UTC, MrValioBg commented on hedera-mirror-rest/api/v1/openapi.yml
> +        gas_consumed:
Done.

2024-02-07 12:58 UTC, MrValioBg commented on hedera-mirror-rest/viewmodel/contractResultViewModel.js
> +    this.gas_consumed = contractResult.gasConsumed;
Done.

2024-02-07 13:03 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/GasCalculatorHelper.java
> +    public static long addIntrinsicGas(final long gas, final ByteString initByteCode) {
Agreed, it would look cleaner to just get the intrinsicgas

2024-02-07 13:05 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/GasCalculatorHelper.java
> +                ++zeros;
I am not sure how it can short circuit, since it gets the byte a the exact index and only tracks zeros, though byteAt seems to not be recommended for iterating, but rather selecting bytes at a random index, so I changed it to a more performant approach.

2024-02-07 16:07 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            return costForByteCode + TX_CREATE_EXTRA;
It seems we would add `TX_CREATE_EXTRA` always, even if we calculate the `gasConsumed` for a contract call?

2024-02-07 18:49 UTC, xin-hedera requested changes

2024-02-07 18:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +     ct.consensus_timestamp, ct.entity_id, c.initcode
this will add gas consumed by contract deployment to all contract transactions for the same contract id

2024-02-07 18:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +   END)
prefer a function `get_intrinsic_gas` which implements the same logic in Java 

```
set gas_consumed = gu.total_gas_used + get_intrinsic_gas(gu.initcode)
```

2024-02-07 18:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +     contract_transaction ct
shouldn't use `contract_transaction`, contract_action.entity_id isn't necessarily a contract (@jnels124, correct me if I'm wrong), use `contract_result` and `contract_result.entity_id` instead

2024-02-07 18:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            return costForByteCode + TX_CREATE_EXTRA;
for contract call, the init byte code is null,  so the function only returns `TX_BASE_COST`

2024-02-08 00:03 UTC, steven-sheehy requested changes

2024-02-08 08:55 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> + ADD COLUMN IF NOT EXISTS gas_consumed bigint NULL;
Got it. Will transform it to lower case.

2024-02-08 08:55 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            contractResult.setFailedInitcode(DomainUtils.toBytes(sidecarProcessingResult.failedInitByteCode()));
Done, adjusted logic for SidecarProcessingResult & gas consumed calculation

2024-02-08 08:56 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        static long getIntrinsicGas(final ByteString initByteCode) {
Got it. I've improved the logic.

2024-02-08 08:56 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +    private record SidecarProcessingResult(ByteString failedInitByteCode, Long gasConsumed) {
Done, we now only do it once in the constructor.

2024-02-08 11:06 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> + CREATE OR REPLACE FUNCTION count_zero_bytes(bytea) RETURNS bigint AS $$
Got it.

2024-02-08 14:32 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +     contract_transaction ct
I've refactored the query and pushed the changes. But we have a possible issue raising up.
The contractbytecodes sidecars seem to not be related to any timestamp but just be in the contract table.

If we use the contract_result table, we should verify that a certain result was made after the sidecars were introduced, otherwise we cannot calculate the gas for it.
To do this, in the updated query I've adjusted the logic so it only changes the gas_consumed field  if a transaction has a contract_action sidecar.

It should be possible to have a transaction that has only ContractBytecode without contract actions, right?
If we have that case then we cannot calculate the gas_consumed for those transactions, because we cannot skip the contract actions check, otherwise it may result in modifying transactions that does not have sidecars.

2024-02-08 14:57 UTC, MrValioBg commented on hedera-mirror-rest/api/v1/openapi.yml
What do you refer to as spec tests?

2024-02-08 15:05 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
The results APIs in `hedera-mirror-rest/__tests__/specs/contracts` should have a gas_consumed field with a non-null value for at least some of the specs for each endpoint.

2024-02-08 15:34 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +     contract_transaction ct
Note: For the cases of contract creates the sum of the contract_action_gas_used is optional and only applicable if the contract perform some additional actions in its constructor.

I think this note in the HIP also concerns this topic.

2024-02-08 21:06 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return new SidecarProcessingResult(DomainUtils.toBytes(initByteCode), totalGasUsed == 0 ? null : totalGasUsed);
We want to populate the gasConsumed field only for the top level (main) transaction. The gasConsumed for its nested transactions would be accumulated in this top level value.

For child contract creates we would have a sidecar action file connected to the top level transaction, which would be of action type `CREATE`/`CREATE2`.

2024-02-08 22:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return new SidecarProcessingResult(DomainUtils.toBytes(initByteCode), totalGasUsed == 0 ? null : totalGasUsed);
That makes sense. Follow up question, does the gas used of the contract action corresponding to the child contract create include the amount consumed by child contract deployment?

2024-02-08 22:57 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return new SidecarProcessingResult(DomainUtils.toBytes(initByteCode), totalGasUsed == 0 ? null : totalGasUsed);
However the example in the HIP seems to match my concern:


```
3. The top-level transaction is a ContractCall to a method that have an inner call to another contract

gas_consumed = intrinsic_gas + cost(contract_init_bytecode_for_top_level_create) + sum(contract_action_gas_used_for_top_level_create) + cost(contract_init_bytecode_for_inner_create) + sum(contract_action_gas_used_for_inner_create)

```

Note the init bytecode of the inner create isn't available to the top level contract creates `RecordItem` inside `ContractResultServiceImpl.process()`

2024-02-08 23:10 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return new SidecarProcessingResult(DomainUtils.toBytes(initByteCode), totalGasUsed == 0 ? null : totalGasUsed);
Yes the `gasUsed ` of the action related to child contract create contains the exact gas that was consumed including initbytecode size calculation. The `gasUsed `field was saved in the `HederaOperationTracer ` after the `CREATE ` operation has taken place and for the internal create calculation the `CustomGasCalculator ` is used, since its invoked by the HederaCreateOperation and HederaCreate2Operation custom opcode overrides.

I think your example from the HIP is mixed. For case 3 we have:
gas_consumed = intrinsic_gas + sum(contract_action_gas_used_for_top_level_call) + sum(contract_action_gas_used_for_inner_call)

2024-02-09 15:55 UTC, steven-sheehy requested changes

2024-02-09 15:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return new SidecarProcessingResult(DomainUtils.toBytes(initByteCode), totalGasUsed == 0 ? null : totalGasUsed);
thanks for the clarification. Yes I mixed the example and the formula, the formula is for example 4 not 3 in the HIP.

2024-02-09 16:07 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +     contract_transaction ct
afaik, child contract create falls into the category of having byte code sidecar while there is no contract action sidecar record. Per the logic in importer `ContractResultServiceImpl`, gas_consumed in its contract result will be `null`, so the SQL migration is correct.

2024-02-14 12:35 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +        (cr.contract_id = any(cr.created_contract_ids)) as is_creation,
Done, I've gone ahead and changes the query to use join with the entity table for finding the relevant create operations.

2024-02-14 18:51 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +     contract_transaction ct
I tried executing an contract create transaction towards the local node, [only with a basic contract]([https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-test/src/t[…]mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java#L214)), that does not have anything in its constructor. 

Also placed a breakpoint in the new logic in the importer's ContractResultServiceImpl.

This resulted in having a contract action, not only contract bytecode sidecar, so we probably wouldn't have a case where we have only contract bytecode sidecar, with 0 contract actions.

2024-02-15 13:53 UTC, MrValioBg commented on hedera-mirror-rest/api/v1/openapi.yml
Done.

2024-02-15 13:56 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +                    Map.of("consensusTimestamp", consensusTimestamp, "gasConsumed", gasConsumed));
Okay, working on this, will let you know, when there is an update.

2024-02-20 21:07 UTC, xin-hedera requested changes

2024-02-20 21:34 UTC, xin-hedera requested changes

2024-02-20 21:34 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +drop function if exists get_intrinsic_gas(bytea);
```suggestion
drop function if exists get_intrinsic_gas(bytea, boolean);
```

2024-02-20 21:34 UTC, xin-hedera commented
The migration took about 30 minutes to complete in mainnet-staging-na.

2024-02-22 15:23 UTC, MrValioBg commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/GasConsumedMigrationTest.java
> +
Done.

2024-02-22 15:23 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +drop function if exists get_intrinsic_gas(bytea);
Done.

2024-02-22 15:24 UTC, MrValioBg commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/GasConsumedMigrationTest.java
> +@TestPropertySource(properties = "spring.flyway.target=1.94.0")
Adjusted.

2024-02-23 12:55 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +    return 21000;
We miss the extra cost of contract call function parameters byte length

2024-02-23 12:56 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            return costForByteCode + TX_CREATE_EXTRA;
For contract calls we also charge for the parameters input size and we should have `costForByteCode` in both scenarios. Only the `TX_CREATE_EXTRA` differs.

2024-02-23 12:58 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +        sum(gas_used) as total_gas_used
We should sum only the `gas_used` of the top level sidecar action. The migration script and all queries should be adapter accordingly - to filter out only the sidecar action with depth 0.

2024-02-26 06:52 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +    return 21000;
Done, its adjusted

2024-02-26 06:52 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                    totalGasUsed = totalGasUsed + action.getGasUsed();
Yes, we can filter using call depth indeed. Its done.

2024-02-26 06:52 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.0__add_gas_consumed_field.sql
> +        sum(gas_used) as total_gas_used
Done, adjusted accordingly.

2024-02-26 11:51 UTC, MrValioBg commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/GasConsumedMigrationTest.java
> +@TestPropertySource(properties = "spring.flyway.target=1.94.0")
After merge from the latest main, had to adjust this back to 1.94.0, as now the script before the one the test class is testing is 1.94.0

2024-02-26 16:23 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/GasConsumedMigration.java
> +                    Map.of("consensusTimestamp", consensusTimestamp, "gasConsumed", gasConsumed));
I managed to populate the database with 1 Million contract_result records and this resulted in the query with the latest updates being completed for aprox 2minutes. 

Maybe we can run again in  mainnet-staging-na, as @xin-hedera did before, so we can have better estimation.

2024-02-26 17:53 UTC, xin-hedera requested changes

2024-02-26 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        long topLevelActionSidecarGasUsed = 0;
nit

```suggestion
        Long topLevelActionSidecarGasUsed = null;
```

then the ternary expression at the end is not needed

2024-02-26 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            payloadBytes = transactionBody.getContractCall().getFunctionParameters();
shouldn't we use function parameters in the transaction record's contract call result? If it's a contract call wrapped in an ethereum transaction, this will return empty string, right?

2024-02-26 17:53 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.95.0__add_gas_consumed_field.sql
> +                   get_intrinsic_gas(gc.payload, gc.is_creation)
sidecar is an optional feature in importer and mirrornode operators can choose to only process certain types of sidecars, so it's possible for a mirronode to process contract action sidecars but not bytecode, then `initcode` can be null.

```suggestion
                   get_intrinsic_gas(coalesce(gc.payload, ''::bytea), gc.is_creation)
```

2024-02-27 12:21 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        long topLevelActionSidecarGasUsed = 0;
Good suggestion. Applied it.

2024-02-27 12:26 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.95.0__add_gas_consumed_field.sql
> +                   get_intrinsic_gas(gc.payload, gc.is_creation)
That's true. I've adjusted it, but in the case where the ContractBytecode sidecar does not exist, do we still want to populate the gas_consumed field for CREATE operations? As this would result in displaying an invalid gas_consumed value?

2024-02-27 13:32 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            return costForByteCode + TX_CREATE_EXTRA;
I've adjusted the logic to factor the calculation for the payload of bytes in the case of contract call

2024-02-27 16:13 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.95.0__add_gas_consumed_field.sql
> +                   get_intrinsic_gas(gc.payload, gc.is_creation)
We can leave it as is. It's the operator's choice to configure importer per the requirement and thus many things are expected to break as a result.

If we decide to convert the backfill part into a Java migration, we can check the importer configuration and skip it if contract action / contract bytecode sidecars are not enabled.

2024-02-27 19:34 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            payloadBytes = transactionBody.getContractCall().getFunctionParameters();
Debugging while calling balanceOf operation the `recordItem.getTransactionRecord().getContractCallResult().getFunctionParameters()` returns empty result, because it is only populated when the paired TransactionBody with the RecordItem is not a contract call or contract create. So for HAPI transactions we have to use the current one.

For ethereum transactions we indeed have to use the `recordItem.getTransactionRecord().getContractCallResult().getFunctionParameters()` 
I've refactored the code accordingly.

2024-02-27 23:24 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            if (transactionBody.hasEthereumTransaction()) {
should we change the logic to be more generic? i.e.

```
if transactionBody.hasContractCall()
  get function parameters from the contract call transaction body
else
  get function parameters from the call result in the transaction record
```

2024-02-27 23:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.95.0__add_gas_consumed_field.sql
> +alter table if exists contract_result
the version should be V1.94.1, because migration V1.94.0 is targeted for the same milestone / release.

2024-02-28 06:57 UTC, MrValioBg commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.95.0__add_gas_consumed_field.sql
> +alter table if exists contract_result
That makes sense. Understood & I've changed the version.

2024-02-28 07:07 UTC, MrValioBg commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +            if (transactionBody.hasEthereumTransaction()) {
Done, I've changed it.

2024-02-28 16:51 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.94.1__add_gas_consumed_field.sql
> +where cr.consensus_timestamp = gc.consensus_timestamp;
now the migration took less than 10 minutes in mainnet-staging:

UPDATE 3492164
Time: 566801.285 ms (09:26.801)

2024-02-28 16:52 UTC, xin-hedera approved these changes
LGTM

2024-02-28 20:13 UTC, steven-sheehy approved these changes
LGTM

2024-02-28 20:15 UTC, merged