HIP 873 Add Decimals to Rest API
hashgraph/hedera-mirror-node pull request #7699
Opened 2024-02-07 22:38 UTC by edwin-greene

**Description**:
Adds  `name` and `decimals` to: 
`/api/v1/tokens`

Adds `decimals` to:
`/api/v1/tokens/{tokenId}/balances`
`/api/v1/accounts/{idOrAliasOrEvmAddress}/tokens`

**Related issue(s)**:

Fixes #7386 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-02-08 22:34 UTC, jnels124 commented on hedera-mirror-rest/service/tokenService.js
> +  maxAge: config.cache.token.decimals.maxAge * 1000, // in millis
The decimal is immutable so shouldn't we only configure max size?

2024-02-08 22:34 UTC, jnels124 commented on hedera-mirror-rest/service/tokenService.js
> +    const rows = await super.getRows(TokenService.tokenDecimalsQuery, tokenId);
Can just use getSingleRow

2024-02-08 22:34 UTC, jnels124 commented on hedera-mirror-rest/tokens.js
> +const tokensSelectQuery = 'select t.token_id, symbol, name, e.key, t.type, decimals from token t';
nit: t.

2024-02-08 23:18 UTC, xin-hedera requested changes

2024-02-08 23:18 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.rest.cache.token.decimals.maxSize`                  | 100000                  | The maximum number of entries in the decimals cache
we'll expand to not just cache token decimals, so to avoid renaming the property, just use `hedera.mirror.rest.cache.token.maxSize` now

2024-02-08 23:18 UTC, xin-hedera commented on hedera-mirror-rest/service/tokenService.js
> +  async getDecimals(tokenId) {
given X tokens returned from a query, here by design, in the worst case, `getDecimals` is called X times and again X db queries are needed to get the info, which is very inefficient.

2024-02-08 23:18 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
it's a unit32 per hedera-protobufs

2024-02-09 19:16 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +  maxAge: config.cache.token.decimals.maxAge * 1000, // in millis
I'm not sure, the entityId cache has a maxAge, so I based this cache off of it.

2024-02-09 20:00 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
Thanks I have updated these to int32.

2024-02-09 20:02 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +  async getDecimals(tokenId) {
Thanks! I have updated it to a `where in clause` in the query, so the query will only occur once rather than multiple times in the loop.

2024-02-09 20:02 UTC, edwin-greene commented on docs/configuration.md
> +| `hedera.mirror.rest.cache.token.decimals.maxSize`                  | 100000                  | The maximum number of entries in the decimals cache
Sounds good I have renamed them.

2024-02-09 20:02 UTC, edwin-greene commented on hedera-mirror-rest/tokens.js
> +const tokensSelectQuery = 'select t.token_id, symbol, name, e.key, t.type, decimals from token t';
Thanks I have added the t

2024-02-09 20:03 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +    const rows = await super.getRows(TokenService.tokenDecimalsQuery, tokenId);
Good idea, but I changed it to accept an array of token ids, so it will now really get back multiple rows.

2024-02-11 00:08 UTC, steven-sheehy requested changes

2024-02-11 00:08 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +    const tokenIds = [];
For performance, may consider a set in case any endpoint can return the same token ID multiple times.

2024-02-11 00:08 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +  maxAge: config.cache.token.decimals.maxAge * 1000, // in millis
Agree, we can probably remove maxAge.

2024-02-11 00:08 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
It can't be int32 since that will make numbers `(2^31, 3^32]` be shown as negative. If there's no uint32 in openapi, revert it back to int64. This is the same reason why we store as bigint in db.

2024-02-12 16:05 UTC, xin-hedera requested changes

2024-02-12 17:25 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +    tokenAccounts.forEach((tokenAccount) => (tokenAccount.decimals = decimalsMap.get(tokenAccount.tokenId)));
Sounds good I have added an undefined check

2024-02-12 17:25 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +  async getDecimals(tokenIds) {
Thanks I have updated the methods.

2024-02-12 17:27 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +    const whereClause = `where ${Token.TOKEN_ID} in (${uncachedTokenIds})`;
I tried a few different approaches, it looks as if the `?` must match the number of parameters, such as `?, ?, ...`. Searching a bit, I wasn't able to find a way to place the where clause in the static query string.

2024-02-12 17:28 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +  maxAge: config.cache.token.decimals.maxAge * 1000, // in millis
Sounds good I have removed it.

2024-02-12 17:29 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +          format: int64
I didn't find an unsigned int in the openApi docs, so I switched this back to int64.

2024-02-12 17:38 UTC, steven-sheehy commented on hedera-mirror-rest/service/tokenService.js
> +    const whereClause = `where ${Token.TOKEN_ID} in (${uncachedTokenIds})`;
Try https://github.com/brianc/node-postgres/issues/1452

2024-02-12 17:59 UTC, edwin-greene commented on hedera-mirror-rest/service/tokenService.js
> +    const whereClause = `where ${Token.TOKEN_ID} in (${uncachedTokenIds})`;
Excellent thanks I have updated it.

2024-02-12 21:01 UTC, steven-sheehy approved these changes
LGTM

2024-02-12 21:05 UTC, xin-hedera approved these changes
LGTM

2024-02-12 21:12 UTC, merged