7500 nft allowances service
hashgraph/hedera-mirror-node pull request #7753
Opened 2024-02-15 19:37 UTC by mgoelswirlds

Adding NFT allowances service layer and tests.

**Description**:
This PR creates the NFT allowances service.

This PR modifies 
- Adds NftAllowanceService to create the service layer

**Related issue(s)**:

Fixes #7500

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2024-02-15 20:28 UTC, xin-hedera requested changes

2024-02-15 20:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private Integer limit = 25;
```suggestion
    private int limit = 25;
```

2024-02-15 20:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private Boolean owner = true;
```suggestion
    private boolean owner = true;
```
believe it's easier to understand by renaming it to `byOwner`, to match the repository function name

2024-02-15 20:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            pageable = PageRequest.of(0, limit, Sort.by(order, "owner").and(Sort.by(order, "token_id")));
isn't the logic of ordering by `owner` column or `spender` column inverted?

when owner=true, we should have `order by spender, token_id`, and when owner=false, it should be `order by owner, token_id`

2024-02-15 20:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private Long spenderId = 0L;
use primitive long and remove `@Builder.Default`

2024-02-15 20:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private Long accountId;
rename it to `owner` or `ownerId` and make it a primitive long.

2024-02-15 20:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        var accountId = request.getAccountId();
with the changes requested for the domain class, this should be `owner` or `ownerId`, easier to understand and consistent with the repository method siguature

2024-02-15 20:35 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            pageable = PageRequest.of(0, limit, Sort.by(order, "owner").and(Sort.by(order, "token_id")));
Yes. You are correct. I should add a test for the order as well.

2024-02-15 23:44 UTC, steven-sheehy requested changes

2024-02-15 23:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            pageable = PageRequest.of(0, limit, Sort.by(order, "spender").and(Sort.by(order, "token_id")));
Can reduce scope if you move it inside if blocks
```suggestion
        // Set the value depending on the owner flag
        if (request.isOwner()) {
            var pageable = PageRequest.of(0, limit, Sort.by(order, "spender").and(Sort.by(order, "token_id")));
```

2024-02-15 23:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            pageable = PageRequest.of(0, limit, Sort.by(order, "spender").and(Sort.by(order, "token_id")));
It seems like we would only ever have 4 possible `Sort` objects. We should create 4 static `Sort` objects as an optimization.

2024-02-15 23:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceService.java
> +    List<NftAllowance> getNftAllowances(NftAllowanceRequest request);
Prefer higher level interfaces.
```suggestion
    Collection<NftAllowance> getNftAllowances(NftAllowanceRequest request);
```

2024-02-15 23:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private long spenderId;
nit: sort fields

2024-02-15 23:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private long ownerId;
This should be accountId and we should drop spenderId, right? Unless you're checking the owner flag in the controller layer and only populating the appropriate fields.

2024-02-16 05:12 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private long ownerId;
Perhaps the latter. I provided the feedback based on that the controller layer will set ownerId / spenderId from the values in the account id path parameter and the account id query parameter depending on the owner flag.

2024-02-16 05:14 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        }
quite some query patterns are not supported, I don't think this is by design. for example:

- `/accounts/{id}/allowances/nfts?account.id=lte:100&token.id=lte:200`
- `/accounts/{id}/allowances/nfts?account.id=100&token.id=200'

Is it out of the scope of the ticket?

2024-02-16 15:50 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        }
Yes we considered just supporting 1 or 2 query patterns for now. Since the repository layer will be change to dynamically support all query patters.

2024-02-16 15:54 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private long ownerId;
I will be populating the appropriate fields in the controller layer. i.e. the accountId from the path will be set to the owner /spender ID  and the account.id will be set to the other ID based on the flag .

2024-02-16 15:59 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            pageable = PageRequest.of(0, limit, Sort.by(order, "spender").and(Sort.by(order, "token_id")));
I believe we will have 6 possible `Sort` objects. Will create static objects.

2024-02-16 16:23 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        }
I would imagine the code at all layers will look very different at the end with full support of the design, so I'm not sure about the approach here...

2024-02-16 16:25 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        }
also want to point out the existing repository method is wrong, for `account.id=gt:X&token.id=gt:Y`, the repository method will only return nft allowances with spender > X and token_id > Y. However, by the design, it should return rows with spender = X + 1 and token_id > Y and any rows with spender > X + 1.

2024-02-16 20:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        // Set the value depending on the owner flag   99
What's 99?

2024-02-16 20:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            Sort.by(Sort.Direction.ASC, OWNER).and(Sort.by(Sort.Direction.ASC, TOKEN_ID));
A helper method and static imports would clean it up.

```suggestion
    private static final Sort OWNER_TOKEN_ASC_ORDER = sort(ASC, OWNER, TOKEN_ID);
```

2024-02-16 20:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        if (accountIdOperator.equals(RangeOperator.GTE)) {
Can use type safe comparison with enums.

```suggestion
        if (accountIdOperator == RangeOperator.GTE) {
```

2024-02-17 19:32 UTC, steven-sheehy submitted a review, later dismissed
Unblocking

2024-02-17 19:32 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +public class Utils {
Nothing in this class seems reusable in any other class. Would be more appropriate back in the service. But can keep it here for now to avoid churn.

2024-02-18 17:25 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +public class Utils {
Addressing it here. Since I need another approval for merging.

2024-02-18 23:53 UTC, xin-hedera commented
Need to DCO sign the commits

2024-02-22 18:49 UTC, mgoelswirlds commented
> Need to DCO sign the commits

Done

2024-02-22 19:03 UTC, steven-sheehy approved these changes

2024-02-23 18:12 UTC, xin-hedera approved these changes
LGTM

2024-02-23 21:29 UTC, merged