feat: Make max gas configurable and increase default value to 50 million
hashgraph/hedera-mirror-node pull request #7783
Opened 2024-02-21 07:46 UTC by kselveliev

**Description**:
This PR add a custom validator for max gas in contract call request 
Also max gas is now configurable and is added to `MirrorNodeEvmProperties` with default value 50M

Example to how to ovverride maxGas in application.yaml of web3:
![image](https://github.com/hashgraph/hedera-mirror-node/assets/138600514/2aa34aca-4b31-4f06-a286-ce94f4e563b5)

Modifications:
Add `MaxGas` annotation
Add `MaxGasValidator` class using `evmProperties.maxGas` to validate the gas
Add `MaxGasValidatorTest`, + modifications in other tests to work with the new max gas
Modified configuration.md and openapi.yaml to note the new default gas.

**Related issue(s)**:

Fixes #7706 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-02-21 09:16 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/validation/MaxGasValidator.java
> +        if (value == null || value <= mirrorNodeEvmProperties.getMaxGas()) {
`value` might be a misleading name, we can rename it to `gasLimit`

2024-02-21 09:17 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxGas = 50_000_000L;
maxGas -> maxGasLimit

2024-02-21 09:17 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/validation/MaxGasValidator.java
> +public class MaxGasValidator implements ConstraintValidator<MaxGas, Long> {
MaxGasValidator -> MaxGasLimitValidator

2024-02-21 14:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/validation/MaxGasValidator.java
> +        if (value == null || value <= mirrorNodeEvmProperties.getMaxGas()) {
Comment addressed

2024-02-21 14:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxGas = 50_000_000L;
Comment addressed

2024-02-22 12:21 UTC, 0xivanov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxGasLimit = 15_000_000L;
I suggest adding `@Min(1_000_000L)` here, as it prevents starting the node with unrealistic `maxGasLimit` value. `1_000_000L` could be up to debate.

2024-02-22 12:33 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxGasLimit = 15_000_000L;
Min value if anything would be intrinsic gas right? 21k

2024-02-22 12:44 UTC, Nana-EC reviewed
Looking good, left minor comments

2024-02-22 12:44 UTC, Nana-EC commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +        final long estimateIterationThreshold = (long) (lo * 0.10);
Q: does the comment need an update?

2024-02-22 14:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +        final long estimateIterationThreshold = (long) (lo * 0.10);
Yes, we can adapt the comment and change the 5% and 8% tolerances which are described and are obsolete now.

2024-02-22 14:37 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-02-22 15:52 UTC, steven-sheehy requested changes

2024-02-22 15:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/validation/GasLimitValidator.java
> +public class GasLimitValidator implements ConstraintValidator<MaxGas, Long> {
A validation annotation should be generic and reusable. Having a `@MaxGas` annotation and validator doesn't make sense as it's very specific to this one field and not reusable. It also probably doesn't even work since `GasLimitValidator` isn't a bean but `MirrorNodeEvmProperties` is and the framework has no way to populate it. For the framework to instantiate the validator it needs a no-arg constructor which is not present.

Please add an integration test in the controller test to prove this. Please remove the annotation and validator and just do the validation in the controller.

2024-02-22 15:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxGasLimit = 15_000_000L;
Yes, let's add `@Min(21_000L)`

2024-02-22 15:52 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> -                Math.max(minimumThreshold, properties.getEstimateGasIterationThreshold());
This property is now unused and should be removed.

2024-02-23 16:45 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxGasLimit = 15_000_000L;
Comment addressed

2024-02-23 16:46 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/validation/GasLimitValidator.java
> +public class GasLimitValidator implements ConstraintValidator<MaxGas, Long> {
Removed the maxGas annotation and added validation in Controller.
The validation is checked by `estimateGasWithInvalidGasParameter` in ContractControllerTest

2024-02-23 16:47 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> -                Math.max(minimumThreshold, properties.getEstimateGasIterationThreshold());
Renamed this property to getEstimateGasIterationThresholdPercent and use it instead of hardcoded 0.1 above, now it is configurable

2024-02-26 14:07 UTC, kselveliev commented on docs/configuration.md
> +| `hedera.mirror.web3.evm.maxDataSize`                          | 24KB (25,576)                                     | Maximum contract data size in bytes, for both contract create and call. Spring Bo
Missed that during merge. Comment addressed.

2024-02-26 14:08 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/utils/BinaryGasEstimator.java
> +        final long estimateIterationThreshold = (long) (lo * 0.10);
Updated the comment.

2024-02-26 16:10 UTC, Nana-EC approved these changes
LG

2024-02-26 16:25 UTC, merged