HIP-646/657/765: Store token metadata and key
hashgraph/hedera-mirror-node pull request #7787
Opened 2024-02-21 21:15 UTC by jascks

**Notice**
This PR is in draft and is the early stages given that the relevant protobufs are not yet available in the form of a accessible artifact. Thus, only the very lowest level mirror node DB work has been committed thus far. As of 20240221, the HIP implementation is scheduled for 0.48 in April 2024. It is currently flagged as "at risk" largely because modular code is at risk. Work is proceeding in the `metadata-hips-646-657-765` branch of both of the services and protobufs repos.

**Description**:
The HIPs introduce the `metadata` and `metadata_key` fields to the existing `TokenCreateTransactionBody` and `TokenUpdateTransactionBody` and are now applicable to both fungible tokens and non-fungible token collections (token level). The existing individual NFT `metadata` (HIP-17) remains separate, though it is now mutable using the same `metadata_key` and the new `TokenUpdateNftsTransactionBody`.

This PR:
* Adds nullable `token.metadata` and `token.metadata_key` fields to the database and domain class
* Updates `TokenCreateTransactionHandler` and `TokenUpdateTransactionHandler` to set the new fields
* Creates `TokenUpdateNftsTransactionHandler` to update `metadata` field already being retained for individual NFTs of the indicated collection
* Updates `SqlEntityListender` to ensure new fields are handled properly.

**Related issue(s)**:

Fixes #6548

**Notes for reviewer**:
Note existing `@Column(updatable = false)` applied to `metadata` in `AbstractNft`. Verify existing code does not inadvertently alter or clear this field, the effects of which have been masked until now.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-03-07 19:55 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/UpdateTokenFreezeKycStatusMigrationTest.java
>              """
Thank you IDEA/spotless. I did not change anything in this DDL.

2024-03-07 19:55 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/UpdateTokenFreezeKycStatusMigrationTest.java
>                  """
No changes here either.

2024-03-07 19:57 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/UpdateTokenFreezeKycStatusMigrationTest.java
> +                .freezeStatus(TokenFreezeStatusEnum.values()[rs.getInt("freeze_status")])
Interesting how some enum values are persisted by ordinal...

2024-03-07 20:12 UTC, steven-sheehy requested changes

2024-03-07 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                .metadata(metadata)
Did we confirm what is intended to happen if metadata wrapper is missing or present with an empty byte array? Does HAPI accept it but do nothing or throw an error?

2024-03-07 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                : EMPTY_BYTE_ARRAY;
Not sure if this clears the field or ignores it. We should definitely not clear it with empty array. Probably we should add `if (transactionBody.hasMetadata())` around setting metadata field in builder.

2024-03-07 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java
>                  .returns(null, Token::getPauseKey)
Different keys differ in null vs [].

2024-03-07 20:12 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            current.setMetadata(null);
I don't think we need to convert [] to null

2024-03-11 14:19 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> +        token.setMetadata(metadata);
Curious what you think here. Unlike token creation, on update `transactionBody.getMetadata()` returns a `BytesValue`, not a `ByteString` as is required by `DomainUtils.toBytes()`. I can first call `toByteString()` to satisfy `toBytes()`, but that involves some serialization and the instantiation of `LiteralByteString` along with a new byte array.

Utilizing `token.setMetadata(transactionBody.getMetadata().toByteArray())` also performs some serialization and creates a new byte array, but is otherwise a little less overhead it seems to me.

2024-03-11 14:25 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        }
Good to know. My original plan was to represent 'no metadata' (token and NFT) as a strictly a null column value, and that has introduced a bit complexity in transaction processing which I can now avoid.

2024-03-11 17:04 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    }
See commentary in your follow up question below.

2024-03-11 17:08 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        }
On token create, the metadata will be that set by the user explicitly in the transaction body, otherwise, I'm told, PBJ sets it to an empty byte array. It is never null. This transaction body does not have a `hasMetadata()` method.

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            current.setMetadata(null);
Done

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java
>                  .returns(null, Token::getPauseKey)
Done

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                : EMPTY_BYTE_ARRAY;
Done (other convo in Slack).

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                .metadata(metadata)
Done

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> +        token.setMetadataKey(metadataKey);
Done

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> +        token.setMetadata(metadata);
Done

2024-03-11 19:53 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        }
Done

2024-03-11 20:06 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    }
Done

2024-03-13 17:15 UTC, xin-hedera requested changes

2024-03-13 17:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        // Never null. Services PBJ sets EMPTY when no metadata defined on create
remove the comment. that's protobuf fundamentals, type `bytes` will never be null, default value is empty byte array.

2024-03-13 17:15 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> +            token.setMetadata(DomainUtils.toBytes(transactionBody.getMetadata().toByteString()));
related question, why would we handle metadata update differently at token class level v.s. nft instance level when the value is empty byte array?

2024-03-13 19:17 UTC, steven-sheehy requested changes

2024-03-13 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        transactionBody.setMetadata(BytesValue.of(bytes(16)));
Prefer a single chained builder like the others and sort.
```suggestion
        var transactionBody = TokenUpdateNftsTransactionBody
            .newBuilder()
            .addSerialNumbers(1L)
            .addSerialNumbers(2L)
            .setMetadata(BytesValue.of(bytes(16)))
            .setToken(tokenId());
```

2024-03-13 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    protected <T> Collection<T> findHistory(String table, Class<T> historyClass) {
An overloaded method should keep the parameters in the same order.

```suggestion
    protected <T> Collection<T> findHistory(Class<T> historyClass, String table) {
```

2024-03-13 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                : EMPTY_BYTE_ARRAY;
I was mistaken here. We do allow it to be cleared by setting to empty array.

2024-03-13 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +            nftBuilder.metadata(toBytes(transactionBody.getMetadata().toByteString()));
```suggestion
            nftBuilder.metadata(toBytes(transactionBody.getMetadata().getValue()));
```

2024-03-13 19:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +        }
```suggestion
        // Since there's only one updatable field, this is a no-op. In the future if there's multiple fields we'll have to rework this logic
        if (!transactionBody.hasMetadata()) {
            return;
        }

        var nftBuilder = Nft.builder()
            .metadata(toBytes(transactionBody.getMetadata().getValue()))
            .timestampRange(Range.atLeast(consensusTimestamp))
            .tokenId(tokenId.getId());
```

2024-03-13 19:34 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                : EMPTY_BYTE_ARRAY;
My original implementation did literally clear the field in the domain object in order to set a null column value. But, that was wrong. Now, if the transaction body `hasMetadata()` then that value is set, be that an empty array ("clear") or something else.

2024-03-13 19:42 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            dest.setMetadata(null);
Oh my, thank your for pointing this out. Apparently I cleaned this up only in `mergeToken()`!

2024-03-13 20:39 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    protected <T> Collection<T> findHistory(String table, Class<T> historyClass) {
There is already `protected <T> Collection<T> findHistory(Class<T> historyClass, String ids)` though, and that makes the compiler unhappy. Looks like I went for the simple solution. 😄 

If that is not acceptable, the new method is only called twice from `UpdateTokenFreezeKycStatusMigrationTest`. I can see the default ID column it's computing for the `PostMigrationToken` "entity" is `token_id` based on the `@Id` annotation on the `tokenId` field.

So, I could call the existing `protected <T> Collection<T> findHistory(Class<T> historyClass, String ids, String table)` knowing that information.

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            dest.setMetadata(null);
Done.

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        // Never null. Services PBJ sets EMPTY when no metadata defined on create
Done. Removed the comment from my tests as well.

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandler.java
> +            token.setMetadata(DomainUtils.toBytes(transactionBody.getMetadata().toByteString()));
Done

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public Builder<TokenUpdateNftsTransactionBody.Builder> tokenNftsUpdate() {
Done

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        transactionBody.setMetadata(BytesValue.of(bytes(16)));
Done

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +            nftBuilder.metadata(toBytes(transactionBody.getMetadata().toByteString()));
Done

2024-03-13 21:54 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +        }
Done

2024-03-13 22:07 UTC, steven-sheehy requested changes

2024-03-13 22:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
> +    void updateTransactionDisabled() {
Add tests for when metadata is empty and when transaction is not successful

2024-03-13 22:07 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/ImporterIntegrationTest.java
> +    protected <T> Collection<T> findHistory(String table, Class<T> historyClass) {
Ok, I didn't see the existing one since it's not in the diff. Can keep.

2024-03-14 03:19 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +@CustomLog
Done

2024-03-14 03:19 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
> +                .tokenId(tokenId.getId());
Oops. Done.

2024-03-14 03:19 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
> +    void updateTransactionDisabled() {
Done.

However, once the metadata is set in `TokenUpdateNftsTransactionBody`, I do not see a way to return the `metadata_` field back to the default null value, which is what `hasMetadata()` needs to see to return false. So, check out the commensurate change I made in `RecordItemBuilder`, which is adding `tokenUpdateNftsEmpty()`. I know you did not like having two related builders in an earlier comment.

The alternative is to modify `tokenUpdateNfts()` and _not_ set the metadata, and then require test cases to set it:
```java
        var recordItem = recordItemBuilder.tokenUpdateNfts()
                .transactionBody(t -> t.setMetadata(BytesValue.of(recordItemBuilder.bytes(16))))
                .build();
```

The empty metadata scenario is the outlier, though, admittedly, currently only three test cases invoke `tokenUpdateNfts()`, so it would not be a big burden.

2024-03-14 03:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
> +    void updateTransactionDisabled() {
There should be a `clearMetadata()` method on the builder.

2024-03-14 03:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        var freezeDefault = transactionBody.getFreezeDefault();
change it back to `boolean`, by our convention, we don't use `var` for primitives

```suggestion
        boolean freezeDefault = transactionBody.getFreezeDefault();
```

2024-03-14 11:35 UTC, jascks commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionHandler.java
> +        var freezeDefault = transactionBody.getFreezeDefault();
Good to know. Done.

2024-03-14 11:36 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
> +    void updateTransactionDisabled() {
I'll look into it further, perhaps create a new `TokenUpdateNftsTransactionBody` and copy the contents of the current one...

2024-03-14 17:24 UTC, jascks commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
> +    void updateTransactionDisabled() {
Sorry about that. I see the light now. 😄   Done!

2024-03-14 18:18 UTC, steven-sheehy approved these changes
LGTM. Just needs a more permanent protobuf artifact

2024-03-14 18:57 UTC, xin-hedera approved these changes
LGTM

2024-03-18 18:04 UTC, steven-sheehy approved these changes

2024-03-18 18:06 UTC, mgoelswirlds approved these changes
LGTM

2024-03-18 18:07 UTC, merged

2024-03-19 17:54 UTC, jascks commented
😀