Update Rest test containers to be created in integration tests
hashgraph/hedera-mirror-node pull request #7827
Opened 2024-02-29 15:31 UTC by edwin-greene

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-02-29 15:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/globalTeardown.js
> +  await integrationDbOps.stopDockerContainers();
i don't think this can work, they are run in different OS processes so every process has its own, different copy of `dockerContainerIds` in module `integrationDbOps`. what you end up doing here in globalTeardown is stop nothing

2024-03-01 16:02 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> -import {getModuleDirname, isV2Schema} from './testutils';
should import and use the function `isV2Schema` from `testutils`

2024-03-01 16:07 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  fs.appendFileSync(containerTempFile, dockerDb.getId() + '\n');
potentially multiple jest workers (OS processes) writing to the same file at the same time?

should change to just touch a file with the container id as its filename using `fs.closeSync(fs.openSync(filepath, 'w')`

2024-03-01 18:37 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +  fs.appendFileSync(containerTempFile, dockerDb.getId() + '\n');
Excellent thanks I have made that update.

2024-03-01 18:38 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> -import {getModuleDirname, isV2Schema} from './testutils';
Got it, fixed.

2024-03-01 18:56 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-03-01 19:17 UTC, steven-sheehy requested changes

2024-03-01 19:17 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/globalTeardown.js
> +    await client.container.remove(container);
Instead of creating a temp dir, writing the container IDs there, then reading those back to remove we could reuse the existing state in docker. Can just generate a global string like `mirror-rest: ${parentProcessId}` and attach it as a label to each container when starting. `parentProcessId` can be the actual parent process ID or some random integer generated by the parent. There doesn't seem to be a way to list by label, but we can do multiple `fetchByLabel()` until it deletes them all.

```suggestion
  const client = await getContainerRuntimeClient();
  while (true) {
    const container = client.container.fetchByLabel("mirror-rest", parentProcessId);
    if (!container) {
      break;
    }
    await client.container.stop(container);
    await client.container.remove(container);
```

2024-03-01 19:17 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    .withLabels({workerId: workerId})
This label seems unused?

2024-03-01 19:39 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    .withLabels({workerId: workerId})
The label seems to fix a problem with `withReuse()`, without the label the Jest workers seem to randomly reuse a container that is already in use by another Jest worker running another integration test.

2024-03-01 19:40 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    .withLabels({workerId: workerId})
Maybe add a comment to that effect

2024-03-01 19:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    .withLabels({workerId: workerId})
testcontainer `withReuse()` says it'll reuse a container with same config when available. Apparently, it's done in a way by querying e.g. docker runtime to determine config equivalence. the labels are part of the config, so without adding the unique worker id as a label, for example, worker 2 will grab worker 1's container if it's already there

2024-03-01 23:06 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/globalTeardown.js
> +    await client.container.remove(container);
Sounds good, I have implemented this.

2024-03-01 23:06 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/integrationDbOps.js
> +    .withLabels({workerId: workerId})
Got it, I have added comments.

2024-03-01 23:35 UTC, steven-sheehy approved these changes
LGTM

2024-03-01 23:37 UTC, xin-hedera approved these changes
LGTM

2024-03-04 14:25 UTC, merged