feat: Sync minAutoRenewDuration and maxAutoRenewDuration default values with services
hashgraph/hedera-mirror-node pull request #7832
Opened 2024-03-01 17:25 UTC by kselveliev

**Description**:
This pr syncs minAutoRenewDuration and maxAutoRenewDuration default values in MirrorNodeEvmProperties with the 
default values in hedera-services.

Modified `MirrorNodeEvmProperties` changed default values minAutoRenewDuration and maxAutoRenewDuration.
Modified acceptance test contract to pass value that is correct with the new default values.
Modified contract bytecode and changed actual gas expectations so that test are passing with new values.
Modifed integration tests in web3 tests to work with the new autoRenew duration properties.

**Related issue(s)**:

Fixes #7826 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-03-05 21:55 UTC, steven-sheehy requested changes

2024-03-05 21:55 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxAutoRenewDuration = 8000001L;
Need to update docs/configuration.md

2024-03-06 15:55 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private long maxAutoRenewDuration = 8000001L;
Comment addressed

2024-03-06 19:11 UTC, steven-sheehy approved these changes
LGTM

2024-03-06 19:12 UTC, merged