7760 nft allowance controller (#7836)
hashgraph/hedera-mirror-node pull request #7837
Opened 2024-03-01 22:20 UTC by mgoelswirlds

**Description**:
This PR has the controller layer for the NFT allowance API in the rest-java module.

This PR modifies 
* Adds Controller for NFT allowance API
* Adds mapstruct config for DTO to mxodel mapping

**Related issue(s)**:

Fixes #7760

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-03-02 04:22 UTC, steven-sheehy commented
I get these failures when ran locally. Seems like it's a flaky test and might not be directly related to this PR.

```
NftAllowanceServiceTest > getNftAllowancesForOrderDesc(boolean) > [1] owner=true FAILED
    org.opentest4j.AssertionFailedError at NftAllowanceServiceTest.java:95

NftAllowanceServiceTest > getNftAllowancesForOrderDesc(boolean) > [2] owner=false FAILED
    org.opentest4j.AssertionFailedError at NftAllowanceServiceTest.java:95
```

2024-03-04 22:57 UTC, steven-sheehy requested changes

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RestUtils.java
> +    }
Remove in favor of annotation validation

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AccountController.java
> +        Long accountPathParam = parseIdFromString(accountId)[2];
These `Filter` and `FilterKey` classes seem to serve no real purpose. They look to be intended for some generic filter use but then we turn around and change them into a non-generic `NftAllowanceRequest`. We should remove these classes in favor of proper validation and type conversion by Spring.

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AccountController.java
> +import org.springframework.web.bind.annotation.*;
We should not use wildcard imports in mirror node

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AccountController.java
> +        response.setAllowances(accountMapper.map(serviceResponse));
There's no next link populated

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AccountController.java
> +        var serviceResponse = service.getNftAllowances(requestBuilder.build());
There's zero `@ExceptionHandler` or error test cases.

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AccountControllerTest.java
> +        }
There's no point in using parameterized tests if the parameterization just causes conditional logic in the test. Better to separate into different tests in that case.

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AccountControllerTest.java
> +                    ownerId, Optional.empty(), Optional.of(owner), Optional.empty(), Optional.of(2), Optional.empty());
This test class is testing at the wrong level. We want the controller to use Spring's `RestClient` to call the HTTP endpoint to ensure all levels of the http stack are verified. Don't extend `RestJavaIntegrationTest` and use `@WebMvcTest` instead

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AccountControllerTest.java
> +class AccountControllerTest extends RestJavaIntegrationTest {
This test class is testing at the wrong level. We want the controller to use Spring's `RestClient` to call the HTTP endpoint to ensure all levels of the http stack are verified. Don't extend `RestJavaIntegrationTest` and use `@WebMvcTest` instead.

```suggestion
@ExtendWith(SpringExtension.class)
@RequiredArgsConstructor
@WebMvcTest(controllers = AccountController.class)
class AccountControllerTest {
```

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/NftAllowanceMapper.java
> +public interface NftAllowanceMapper {
Needs a test that verifies all fields

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/NftAllowanceMapper.java
> + * Copyright (C) 2019-2024 Hedera Hashgraph, LLC
Please check all new files.

```suggestion
 * Copyright (C) 2024 Hedera Hashgraph, LLC
```

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/CommonMapper.java
> +        return source.getShard() + "." + source.getRealm() + "." + source.getNum();
```suggestion
        return source != null ? source.toString() : null;
```

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/CommonMapper.java
> +    default Instant mapInstant(Long source) {
Where is `Instant` used? The conversion should be from `Long` to `String` where `String` is `seconds.nanos`. `Instant.toString()` would not produce `seconds.nanos`.

2024-03-04 22:57 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AccountControllerTest.java
> +    void testWithNoQueryParams(boolean owner) {
There's a huge quantity of test cases missing. We need negative and positive tests for every query parameter. We need negative tests for non-2xx scenarios.

2024-03-19 03:01 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AccountController.java
> +            @RequestParam("token.id") @Valid Optional<String> tokenId,
Changed this to EntityIdRangeParameter

2024-03-19 03:02 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AccountControllerTest.java
> +class AccountControllerTest extends RestJavaIntegrationTest {
Using RestClient with an actual @SpringBootTest which brings up a server.

2024-03-19 03:04 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/mapper/CommonMapperTest.java
> +        // assertNull(commonMapper.mapEntityId((Long) null));
Commenting out this flaky test.

2024-03-19 15:06 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +            @RequestParam(defaultValue = "asc") String order) {
Had to change this to String, since the order case with Sort.Direction was causing an  issue with parameter conversion. SO manually did that in the method.

2024-03-21 14:30 UTC, steven-sheehy requested changes

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdRangeParameter.java
> +        return validateId(splitVal, 1, RangeOperator.valueOf(splitVal[0].toUpperCase()));
`RangeOperator.valueOf()` will return an error like `No enum constant RangeOperator.BLAH`. This leaks class details. It also throws an IllegalArgumentException which currently doesn't have an `@ExceptionHandler`. It would be better if the error said `Invalid range operator blah. Valid values: lt, gt...`. We should encapsulate this in a `RangeOperator.of(String)` that also hides the upper casing.

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +            throw new InvalidParametersException("token.id parameter must have account.id present");
Where do we reject NE range operator?

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +        Pattern partitionedPattern = Pattern.compile(regex);
Should statically compile Pattern

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +        if (isAMatch(ENTITY_ID_REGEX, id) || isAMatch(ENCODED_ENTITY_ID_REGEX, id)) {
We do not support encoded entity id as input to any API. We support a non-encoded `num` without realm or shard.

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +        return isAMatch(EVM_ADDRESS_SHARD_REALM_REGEX, address);
We should not have so many regex invocations. There should be a single pre-compiled regex for path id then we check which group is populated to determine evm address vs alias vs id.

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +    }
It's incorrect to parse a 40 byte evm address into a long array.

2024-03-21 14:30 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +                    throw new InvalidParametersException(" Id '%s' cannot be parsed".formatted(id));
All entity id parsing should go away. We should only have a single regex to extract out shard, realm, num with first two having defaults if not present. Then call EntityId.of().

2024-03-21 19:16 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/EntityMapper.java
> +}
renaming this to RestJavaMapperConfig to avoid confusion with mapstruct MapperConfig

2024-03-22 14:02 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +    private Error inputValidationError(final InvalidInputException e) {
Since this is a GET call HttpMediaTypeNotSupportedException will not be thrown. Instead I think I should handle `HttpRequestMethodNotSupportedException`

2024-03-26 02:51 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Constants.java
> +    public static final String EVM_ADDRESS_REGEX = "^(((0x)?[A-Fa-f0-9]{40})|((\\d{1,10}\\.){0,2}[A-Fa-f0-9]{40}))$";
The regex needed to be split into 2 because of the increased complexity as reported by Sonar.

2024-03-26 14:23 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +                    .ownerId(accountId.value().getId())
This has been moved to the service layer, but we need to get long to send it to the repo.

2024-03-26 14:23 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +        // Currently no scenario is throwing this error
Will be part of the evm address ticket.

2024-03-26 22:06 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +            paginationLink.append(next);
This is all quite brittle and is missing edge cases. For example, if `owner=false` was in the url it would not get propagated to the next link. Add a test to verify that has every possible query param and has a next link.

Instead, we should take the approach were we iterate over the `request.getParameterMap()` and construct the next link from it, swapping out values only for token.id and account.id if applicable.

2024-03-27 01:28 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        return id;
These are the optional query params.  As you mentioned this will need to change with dynamic queries but until then the static queries will return all values with ids > 0 .

2024-03-27 03:09 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        return id;
Yes, but if I omit token.id the query will put `token_id = 0` and return zero results. Better to throw an error if optional param not sent but query currently requires it.

2024-03-27 15:19 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdParameter.java
> +        return new EntityIdParameter(parseId(entityIdParam));
Since we would need the parseId code in near future in a common space , I would prefer to leave it in the utils.

2024-03-28 19:20 UTC, steven-sheehy requested changes

2024-03-28 19:20 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +    }
Can be greatly simplified, I believe. We might be able to get rid of included map if we make it a linked map and assume last item is not inclusive?

```suggestion
        var last = CollectionUtils.lastElement(response.getAllowances());
        String next = null;

        if (last != null && serviceResponse.size() == limit) {
            long accountId = owner ? last.getSpender() : last.getOwner();
            var included = Map.of(ACCOUNT_ID, true, TOKEN_ID, false);
            var lastValues = Map.of(ACCOUNT_ID, accountId, TOKEN_ID, last.getTokenId());
            next = Utils.getPaginationLink(false, lastValues, included, order)
        }
```

2024-03-28 19:20 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +                .uri(uriParams, allowance1.getOwner(), EntityId.of(allowance1.getSpender()))
nit: Could pull `.get()` up to setup.

```suggestion
        var result = restClient.uri(uriParams, allowance1.getOwner(), EntityId.of(allowance1.getSpender()))
```

2024-03-28 19:20 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +                if (count != 0) {
Maintaining the request parameter order here is not very straightforward since the paramMap  is not a LinkedHashMap. I will fix this as part of a follow-up ticket.

2024-03-28 20:15 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +                    shard = 0;
https://github.com/hashgraph/hedera-mirror-node/issues/7858

2024-03-28 21:18 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +                .uri(uriParams, allowance1.getOwner(), EntityId.of(allowance1.getSpender()))
Don't believe this can be done. The client needs a method.

2024-04-01 16:02 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +}
is this needed? the directory is already added to main sources set in openapi-convetions

2024-04-01 16:04 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/CommonMapper.java
> +    default String mapTimestamp(long timestamp) {
```suggestion
    default String mapTimestamp(Long timestamp) {
```

and return `null` if `timestamp` is null, then simplify `mapRange` to remove the `if (source.has???Bound())` check

2024-04-01 16:09 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            var ownerId = verifyAndGetRangeId(ownerOrSpenderId);
nit, should call `verifyAndGetRangeId(ownerOrSpenderId)` just once

2024-04-01 16:16 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/OrderConverter.java
> +        return Sort.Direction.valueOf(order.toUpperCase());
the static method `fromString` is case-insensitive. Also do we really need a custom converter? OK to keep the converter though.

```suggestion
        return Sort.Direction.fromString(order);
```

2024-04-01 16:21 UTC, mgoelswirlds commented on hedera-mirror-rest-java/build.gradle.kts
> +}
Just verified. It is not needed anymore.

2024-04-01 17:53 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/CommonMapper.java
> +    default String mapTimestamp(long timestamp) {
Can't do this because of method ambiguity while mapping using mapstruct.

2024-04-01 17:54 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +            paginationLink.append(generateLinkFromRequestParams(lastValues, order, request));
Agreed missed this in refactoring.

2024-04-01 18:10 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
> +        // add all params from the existing url
Will create a followup.

2024-04-01 18:59 UTC, xin-hedera requested changes

2024-04-01 18:59 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/CommonMapper.java
> +        sb.append(timestampString);
use `StringUtils.leftPad(value, 10, '0')`

2024-04-01 19:27 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/mapper/CommonMapperTest.java
> +    }
still need to test corner cases, e.g., given `[1, 100)`, expect `["0.000000001", "0.000000100")`. the current implementation would certainly fail, because it does right padding instead of left padding.

2024-04-01 20:17 UTC, xin-hedera approved these changes
LGTM

2024-04-01 20:19 UTC, steven-sheehy approved these changes
LGTM

2024-04-01 21:02 UTC, merged