Integrate Jooq into rest-java to support dynamic SQL queries
hashgraph/hedera-mirror-node pull request #7871
Opened 2024-03-05 21:13 UTC by xin-hedera

**Description**:

This PR integrates Jooq into rest-java module

- Add gradle build tasks and flows to make jooq codegen to generate meta classes from tables in a live database
- Customize jooq configuration to not prefix everything with schema
- Add a `JooqRepository` to get entity / entities
- Workaround dependency issue introduced by gradle docker plugin

**Related issue(s)**:

Relates to #7690 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-03-05 21:16 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +abstract class PostgresService : BuildService<PostgresService.Params>, AutoCloseable {
the service make it easy to share the postgresql container, also stops the container at the end

2024-03-05 21:17 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +                            "/hedera-mirror-importer/src/main/resources/db/scripts/init.sh"
this has to be absolute path otherwise running the task from a different location will fail due to file not found when trying to read it

2024-03-05 21:18 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/config/JooqCustomConfiguration.java
> +        return c -> c.settings().withRenderSchema(false);
all our tables are in the same schema, so let jooq know we don't want it to add the `public.` prefix everywhere

2024-03-05 21:19 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/JooqRepositoryTest.java
> +        var actualNftAllowance = jooqRepository.getEntity(query, NftAllowance.class);
this will create a parameterized SQL query, e.g., with `where nft_allowance.ower = ?`

2024-03-05 21:34 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/config/JooqCustomConfiguration.java
> +class JooqCustomConfiguration {
can't name the class `JooqConfiguration` since then the bean will name clash with the one brought in by `spring-boot-starter-jooq`

2024-03-06 22:27 UTC, edwin-greene approved these changes
Looks good to me

2024-03-07 20:15 UTC, jascks commented on hedera-mirror-rest-java/build.gradle.kts
> +    id("org.flywaydb.flyway") version "10.8.1"
It seems `graphql`, `grpc` and `web3` are getting by well enough using Spring Data repositories? Would there be a benefit to dropping this stuff into `jooq-conventions.gradle.kts` so it can be more easily leveraged elsewhere? Perhaps premature optimization at this time.

2024-03-07 20:41 UTC, steven-sheehy requested changes

2024-03-07 20:41 UTC, steven-sheehy commented on buildSrc/build.gradle.kts
> +    // embedded in the plugin being used by testcontainers-postgresql
The order of specifying dependencies is not important, so this can be specified in sorted order. However, these are not direct dependencies but overrides of transitive dependencies. Move these to a [constraints](https://docs.gradle.org/current/userguide/dependency_constraints.html#sec:adding-constraints-transitive-deps) block and add a `because` description.

2024-03-07 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +                    | account_balance_p.*
Instead of explicitly listing partitioned tables we could use a more generic regex like `.*_p\d+_\d+$`

2024-03-07 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +                packageName = "com.hedera.mirror.restjava.model.jooq"
It's probably strange to have the jooq models in a sub directory of the view-model. Maybe move view model to `model/view` and keep jook in `model/jooq` OR to `viewmodel` and make it just `jooq`.

2024-03-07 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +}
Since kotlin can read Java, wondering if there's some way to directly use `CommonTestConfiguration.flywayProperties()` here so we don't repeat ourselves.

2024-03-07 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/build.gradle.kts
> +                start()
Again, this is literally the same java code as `CommonTestConfiguration.postgresql()` so we should find a way to reuse.

2024-03-07 22:09 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +    id("org.flywaydb.flyway") version "10.8.1"
agree. I tend to not make it a convention because at least now the flyway plugin and jooq plugin aren't used by other modules.

If we do see the needs of utilizing jooq in other modules, we still don't have to make it a convention, because the module to host jooq generated meta classes will then be the common module and we only need to have these tasks and configs in common instead.

2024-03-07 22:09 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +                    | account_balance_p.*
sure

2024-03-07 22:11 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +}
I don't think that's possible. We'll create a circular dependency most likely, as then buildSrc will depend on common module, however common module in reverse depends on buildSrc

2024-03-07 22:18 UTC, xin-hedera commented on buildSrc/build.gradle.kts
> +    implementation("com.github.docker-java:docker-java-api:$dockerJavaVersion")
doesn't work that way, I guess the reason is this is not a transitive dependency problem.

2024-03-07 22:21 UTC, xin-hedera commented on buildSrc/build.gradle.kts
> +    // embedded in the plugin being used by testcontainers-postgresql
moving to constraints doesn't work.

The underlying problem is not docker gradle plugin bringing the jars by transitive dependency, instead, the plugin embeds the docker-java jars directly in its distribution without shading. Though I didn't check the jars on the build system classpath after overriding with the above two, it's the magic which makes both testcontainers and docker plugin work.

2024-03-12 18:34 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
> +        return properties.isEnabled()
just spotless reformat

2024-03-12 18:34 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/BatchStreamFileNotifierTest.java
> +                    Uninterruptibles.sleepUninterruptibly(sleep);
just spotless reformat

2024-03-12 18:57 UTC, xin-hedera commented on buildSrc/src/main/kotlin/jooq-conventions.gradle.kts
> +                packageName = "com.hedera.mirror.restjava.jooq.domain"
The package for the generated meta classes is changed

2024-03-12 19:01 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryTest.java
> +    @MethodSource("provideFindAllArguments")
The complexity of building the test case scenarios is in the `provideFindAllArguments` function. There are 3 owners, 3 spenders,  and 3 tokens created in the setup, and thus 27 nft allowances in total.

The test cases utilize indexes of owners / spenders / tokens to create filters and expected result in a relatively readable way.

2024-03-12 19:03 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryTest.java
> +        var emptyFilters = Collections.<Filter<?>>emptyList();
solar complains about possible `RuntimeException` thrown by `Collections.emptyList()` if directly passed to `findAll`, so split it here.

2024-03-12 19:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +    private static Condition makeCondition(Filter<?> filter) {
this function deserves to be in a utility class

2024-03-12 22:46 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +                .fetchInto(NftAllowance.class);
went back to use jooq's fluent API because after all the conditions complexity is not as bad as I thought.


In case the query needs to be more dynamic thus naturally more complicated (e.g., unions, CTEs, and etc), we should use [QueryParts](https://www.jooq.org/doc/3.19/manual/sql-building/queryparts/)

2024-03-14 18:33 UTC, steven-sheehy requested changes
Still reviewing repository

2024-03-14 18:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/jooq/DomainRecordMapper.java
> +            setters = getSetters(fieldNames, type);
The `EntityMetadataRegistry` already does much of this logic and I would like to see it reused here as well since it abstracts the setters behind lambdas. That said, it's late in the cycle so we can open a ticket to follow up.

2024-03-14 18:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/jooq/DomainRecordMapper.java
> +                    continue;
Should this throw an error or are there valid scenarios where it can be missing?

2024-03-14 18:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/jooq/DomainRecordMapper.java
> +            return OBJECT_MAPPER.readValue(((JSONB) source).data(), collectionType);
This hardcoded mapping is a bit brittle. We should replace this with a single call to Spring's `ConversionService` for types that aren't the same on both side. Then we can register custom converters like `LongRangeConverter` and take advantage of the built-in converters. Could be a follow up ticket.

2024-03-14 18:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +@CustomLog
unused

2024-03-14 18:58 UTC, xin-hedera commented on hedera-mirror-rest-java/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-jooq")
will do

2024-03-14 18:59 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Order.java
> +}
will switch to it if no issue found

2024-03-14 19:00 UTC, xin-hedera commented on build.gradle.kts
> +    set("jooq.version", "3.19.6")
the official jooq gradle plugin is only available from 3.19.x, and then I want to keep the version consistent between the plugin and our compile time dependencies. will add a note

2024-03-14 19:00 UTC, xin-hedera commented on buildSrc/build.gradle.kts
> +    implementation("org.postgresql:postgresql:42.7.2")
I don't think so, can give it a try

2024-03-14 19:01 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/exception/MismatchTypeException.java
> +public class MismatchTypeException extends RestException {
sure

2024-03-14 19:09 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/jooq/DomainRecordMapper.java
> +                    continue;
good catch. This should never happen, so I'll remove it. I think I was considering the inverted scenario, that we do have some transient field / some setters without corresponding column in our domain entity class

2024-03-14 20:34 UTC, xin-hedera commented on buildSrc/build.gradle.kts
> +    implementation("org.postgresql:postgresql:42.7.2")
removed

2024-03-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/jooq/DomainRecordMapper.java
> +            setters = getSetters(fieldNames, type);
will create a ticket

2024-03-14 20:34 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +@CustomLog
removed

2024-03-14 20:38 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        Filter<?> approvedForAllFilter = null;
obviously forgot to support approved_for_all, now added.

2024-03-14 22:53 UTC, steven-sheehy requested changes

2024-03-14 22:53 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +            boolean byOwner, @NotNull List<Filter<?>> filters, int limit, @NotNull Direction order) {
There's a bit of inefficiency in that we convert from flattened variables in controller to `NftAllowanceRequest` for service then to this filters list for repository. We might have to revisit this once all the layers are in place and consolidate to one level of mapping.

2024-03-14 22:53 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +    private static Condition makeCondition(Filter<?> filter) {
It might be better and reusable to define this mapping within the `RangeOperator` enum. It could return some lambda to apply to the field and value.

2024-03-14 22:53 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Filter.java
> +    }
Is the extra type parameter really needed? Doesn't the Field and the `T value` have the necessary type info?

```suggestion
public record Filter<T>(Field<?> field, RangeOperator operator, T value) {
```

2024-03-14 22:53 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        var value = (Long) primarySortFilter.value();
It doesn't seem to provide value to have the generics. We should declare the parameters with `Filter<Long>` or consider removing the generics.

2024-03-14 22:53 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +    private Condition getBaseCondition(Condition commonCondition, Filter<?> primarySortFilter, Filter<?> tokenFilter) {
This logic might be good to have in a generic `JooqRepository` in the future.

2024-03-14 23:44 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +            boolean byOwner, @NotNull List<Filter<?>> filters, int limit, @NotNull Direction order) {
I think the NftAllownceServiceRequest will change a lot or go away.

We may need a factory class to provide lookup of http query parameter + endpoint to jooq table fields.

2024-03-14 23:47 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Filter.java
> +    }
Yes. The other way to get the class type during runtime of reflection, of cause we dont want to pay the huge cost as this is frequently instantiated

2024-03-15 00:21 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        var value = (Long) primarySortFilter.value();
the generics in Filter provides the type safety so when initiated, the value for the field has matching type.

We either cast the value to `Long` here, or cast the filter to `Filter<Long>` beforehand (because the method has `List<<Filter<?>>`

2024-03-18 15:39 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +            boolean byOwner, @NotNull List<Filter<?>> filters, int limit, @NotNull Direction order) {
As a follow-up , we would need to change the service layer to integrate the controller and refactor NftAllownceServiceRequest. Will create a followup ticket.

2024-03-18 20:19 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/exception/RestException.java
> +abstract class RestException extends MirrorNodeException {
I have this same class in my PR. So depending on which PR goes in first the other can delete it.

2024-03-19 22:08 UTC, steven-sheehy approved these changes
LGTM

2024-03-20 00:31 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        Filter<?> approvedForAllFilter = null;
I don't believe we would need the approved_for_all filter.

2024-03-20 00:33 UTC, mgoelswirlds approved these changes
LGTM

2024-03-20 03:13 UTC, merged