7761 monitor zfs stats and configure alerts
hashgraph/hedera-mirror-node pull request #7881
Opened 2024-03-08 02:38 UTC by jnels124

**Description**:
* add new ZFS grafana dashboard
* add nodename as label to node exporter metrics
* make stackgres prom exporter sidecar enable flag configurable

**Related issue(s)**:

Fixes #7761

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-03-11 14:59 UTC, jnels124 commented on charts/hedera-mirror-importer/values.yaml
> +  ImporterDbStorageFull:
move to v2-values.yaml?

2024-03-12 19:53 UTC, steven-sheehy requested changes

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +  ImporterDbStorageFullWarning:
I don't think we need two alerts for the same thing. Can just drop this one.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "uid": "prometheus"
Don't hardcode the name as it differs on grafana cloud. Same for other variables.

```suggestion
          "type": "prometheus",
          "uid": "${prometheus}"
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +        "sort": 0,
Sort the values ascending. Same for other variables.
```suggestion
        "sort": 1,
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "value": "P8E80F9AEF21F6940"
Don't hardcode the name.

```suggestion
          "text": "",
          "value": ""
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +        "definition": "label_values(kubelet_volume_stats_used_bytes{node=~\"$node\"},namespace)",
```suggestion
        "definition": "label_values(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\",node=~\"$node\"},namespace)",
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "query": "label_values(node_zfs_arc_size,node)",
Filter by cluster and namespace

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +            }
We can probably remove the custom link. Grafana has added built-in links to explore now in the hamburger menu on the right.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +            "wrapLogMessage": false
The log panel is collapsed by default. I think we can expand it by default.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +            "max"
The standard order in our other dashboards is `min, max, mean`. We should also sort mean by descending. Same comment for all graphs.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "sort": "none"
Change to multi and desc. Same comment for others.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +            "gradientMode": "none",
Same comment for others.

```suggestion
            "gradientMode": "hue",
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "custom": {
Disable grid lines on all graphs per our standard look and feel.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +            "fillOpacity": 0,
Same comment for others.

```suggestion
            "fillOpacity": 10,
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +      "title": "Throughput",
Think this one and iops deserve a legend with min, max, mean. Move both to be full width.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +      "title": "IOPS",
Add a description to all graphs.

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "legendFormat": "{{node}}/{{namespace}}/{{persistentvolumeclaim}}",
A PVC ID is globally unique so we can shorten this to a reasonable length.
```suggestion
          "legendFormat": "{{persistentvolumeclaim}}",
```

2024-03-12 19:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "expr": "irate(node_disk_write_time_seconds_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{node=~\"$node\
We should filter out rows with missing data by adding either >0 or >=0. Same comment for other graphs.

2024-03-22 14:28 UTC, jnels124 commented on charts/hedera-mirror/values.yaml
> +    enableMetricsExporter: false
keeping disabled until we resolve resource allocation

2024-03-25 19:12 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "query": "label_values(node_zfs_arc_size,node)",
filtering just on cluster but namespace is not possible. The namespace on this metric is going to be common because it is a shared resource.

2024-03-25 20:30 UTC, jnels124 commented on charts/hedera-mirror-common/Chart.yaml
> +    version: 2.5.0
bumping zfs version here as very small task

2024-03-25 20:34 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "expr": "irate(node_disk_io_time_weighted_seconds_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) >= 0",
this provides a more accurate representation of tasks that waited between scrape intervals

2024-03-26 16:25 UTC, steven-sheehy commented on charts/hedera-mirror-importer/values.yaml
> +  ImporterDbStorageFull:
This is still in importer chart

2024-03-26 18:08 UTC, steven-sheehy requested changes

2024-03-26 18:08 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "legendFormat": "{{node}}",
This metric doesn't seem to have a node label in preprod so it's showing all labels in legend. Same comment for other `node_*` metrics. Is this just because it needs the prometheus relabeling change below first?

2024-03-26 20:20 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "legendFormat": "{{node}}",
yes it needs the relabeling change first

2024-03-26 20:58 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "expr": "{component=~\".*zfs.*\"}",
will include cluster but this is a common resource so will exclude namespace filter

2024-03-27 18:57 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "expr": "{component=~\".*zfs.*\"}",
ended up not adding a rate panel to logs as there isn't a metric available to capture count of logged events for apps outside of spring

2024-03-27 18:59 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "expr": "{component=~\".*zfs.*\"}",
You can do it with pure logql, but no need to spend more time on it.

2024-03-27 19:10 UTC, steven-sheehy requested changes

2024-03-27 19:10 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "query": "label_values(kube_pod_info{cluster=~\"$cluster\", pod=~\"$zfsComponentsRegex\"},node)",
For Grafana Cloud, you have to pick metrics that are exported there. kube_pod_info is not. Is there another metric you can use? Double check the others

2024-03-27 19:10 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +prometheusRules:
Maybe move under `stackgres.prometheusRules` since they're not enabled unless stackgres is

2024-03-27 22:40 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "query": "label_values(kube_pod_info{cluster=~\"$cluster\", pod=~\"$zfsComponentsRegex\"},node)",
This dashboard is largely non functional in grafana cloud right now under current config. The only thing we send is things coming from job with values `.*(graphql|grpc|importer|monitor|rest|restjava|rosetta|traefik|web3)$`. We don't send any k8s related metrics for nodes or kube state. We can update the remote write to include the kube_pod_info from the kubestatemetrics job as well as zfs metrics if we decide we want them in grafana cloud

2024-03-28 03:44 UTC, steven-sheehy commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "query": "label_values(kube_pod_info{cluster=~\"$cluster\", pod=~\"$zfsComponentsRegex\"},node)",
While that's true, we shouldn't intentionally pick unrelated metrics that aren't needed for the graphs to populate the variables. We don't need to export the potentially large number of `kube_pod_info` time series just so we can populate the list of nodes.

Instead, I think you should use `kubelet_volume_stats_used_bytes` to populate all three cluster, namespace, and node variables since it's already used elsewhere within the dashboard.

2024-03-28 06:14 UTC, jnels124 commented on charts/hedera-mirror-common/dashboards/zfs.json
> +          "query": "label_values(kube_pod_info{cluster=~\"$cluster\", pod=~\"$zfsComponentsRegex\"},node)",
I didn't intentionally pick an unrelated metric. There are going to be no other metrics that are going to provide a clear indication of zfs related pods unless we have a metric that has pod names and we don't have that outside of the mirror components. 

`kubelet_volume_stats_used_bytes `  doesn't indicate any information about what is running all the zfs components and neither does any other metric. The only definitive way to get that information is from pod names and we don't have those available for these components.

We can change back to the zfs  node metric it was using before to populate the node dropdown which will include only the zfs zpool nodes, then change the logs row to have a separate panel for the zfs controller that doesn't apply any of the dropdown filters.

2024-04-01 19:12 UTC, steven-sheehy approved these changes
LGTM

2024-04-01 19:32 UTC, xin-hedera approved these changes
LGTM

2024-04-01 20:10 UTC, merged