Lazy load nested items during contract call
hashgraph/hedera-mirror-node pull request #7953
Opened 2024-03-22 14:05 UTC by IvanKavaldzhiev

**Description**:

This PR enhances db accessors' performance by lazy loading some of the nested fields, which are not always directly used when fetching the models.
**Related issue(s)**:

Fixes #7903 

**Notes for reviewer**:

To be tested with acceptance and K6 tests
**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-03-25 18:54 UTC, steven-sheehy requested changes

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
> +                TreeSet::new,
Prefer zero allocation collections unless needed.
```suggestion
                Collections::emptySortedMap,
                Collections::emptySortedMap,
                Collections::emptySortedSet,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> balance),
```suggestion
                () -> balance,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                () -> Collections.unmodifiableSortedSet(new TreeSet<>()),
```suggestion
                Collections::emptySortedMap,
                Collections::emptySortedMap,
                Collections::emptySortedSet,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> balance),
```suggestion
                () -> balance,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                () -> Collections.unmodifiableSortedSet(new TreeSet<>()),
```suggestion
                Collections::emptySortedMap,
                Collections::emptySortedMap,
                Collections::emptySortedSet,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> ownedNfts),
```suggestion
                () -> ownedNfts,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> numAssociations),
```suggestion
                () -> numAssociations,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> newNumPositiveBalances),
```suggestion
                () -> newNumPositiveBalances,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> newBalance),
```suggestion
                () -> newBalance,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> cryptoAllowances),
```suggestion
                () -> cryptoAllowances,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> fungibleTokenAllowances),
```suggestion
                () -> fungibleTokenAllowances,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                Suppliers.memoize(() -> newApproveForAllNfts),
```suggestion
                () -> newApproveForAllNfts,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +        return cryptoAllowances != null ? cryptoAllowances.get() : Collections.unmodifiableSortedMap(new TreeMap<>());
```suggestion
        return cryptoAllowances != null ? cryptoAllowances.get() : Collections.emptySortedMap();
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +                : Collections.unmodifiableSortedMap(new TreeMap<>());
```suggestion
                : Collections.emptySortedMap();
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +        return approveForAllNfts != null ? approveForAllNfts.get() : Collections.unmodifiableSortedSet(new TreeSet<>());
```suggestion
        return approveForAllNfts != null ? approveForAllNfts.get() : Collections.emptySortedSet();
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/TokenRelationship.java
> +                Suppliers.memoize(() -> balance),
```suggestion
                (() -> balance,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +                () -> Collections.unmodifiableSortedSet(new TreeSet<>()),
```suggestion
                Collections::emptySortedMap,
                Collections::emptySortedMap,
                Collections::emptySortedSet,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/DissociateLogicTest.java
> +                Suppliers.ofInstance(3),
Why are we using this `Suppliers.ofInstance` in tests instead of `() -> 3`?

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                Suppliers.memoize(() -> autoRenewAccount),
```suggestion
                () -> treasury,
                () -> autoRenewAccount,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                () -> Collections.unmodifiableList(new ArrayList<>()));
```suggestion
                Collections::emptyList);
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                Suppliers.memoize(() -> totalSupply),
```suggestion
                () -> totalSupply,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                Suppliers.memoize(() -> treasury),
```suggestion
                () -> treasury,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                Suppliers.memoize(() -> treasury),
```suggestion
                () -> treasury,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                Suppliers.memoize(() -> autoRenewAccount),
```suggestion
                () -> autoRenewAccount,
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                : Collections.unmodifiableList(new ArrayList<>());
```suggestion
                : Collections.emptyList();
```

2024-03-25 18:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessorTest.java
> -                .thenReturn(Optional.of(autorenewEntity));
We should have tests in all the accessor tests that verify a) Not loaded for top level and b) is lazy loaded for all nested items.

2024-03-26 14:11 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +        return cryptoAllowances != null ? cryptoAllowances.get() : Collections.unmodifiableSortedMap(new TreeMap<>());
I believe it would be a good idea to return unmodifiable collections in the getters, so that we don't introduce side effects of changing a model field, which should be immutable as a whole and replaced entirely in the stacked state in case of update.

2024-03-26 14:12 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/DissociateLogicTest.java
> +                Suppliers.ofInstance(3),
Forgot to change it to a lambda.

2024-03-26 15:15 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
> +        return cryptoAllowances != null ? cryptoAllowances.get() : Collections.unmodifiableSortedMap(new TreeMap<>());
But we should also wrap the existing `cryptoAllowances` collection that might have been set, so probably we can have an `unmodifiable` definition over the whole expression, as I refactored the code? If we don't - we can set a normal collection that can remain modifiable.

2024-03-26 18:24 UTC, steven-sheehy requested changes

2024-03-26 18:24 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
> +                customFees != null && customFees.get() != null ? customFees.get() : new ArrayList<>());
`customFees.get()` should never be null per `TokenDatabaseAccessor.getCustomFees()`.

```suggestion
        return customFees != null ? Collections.unmodifiableList(customFees.get()) : Collections.emptyList();
```

2024-03-27 22:04 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldStateTest.java
> +                Suppliers.ofInstance(0L),
I refactored all occurrences

2024-03-31 00:14 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-04-01 14:55 UTC, kselveliev submitted a review, later dismissed
LGTM

2024-04-09 19:14 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/google/common/base/Suppliers.java
> +            }
This is slower than before since it always locks instead of only locking when it's not present. I also don't think we need to guarantee that the delegate only runs once so we can get away with something simpler. Finally, we should not override Guava's class since Guava doesn't sound like they're ever going to change their implementation. I suggest this approach in our own util class like `Web3Utils`:

```java
    public static <T> Supplier<T> memoize(Supplier<T> delegate) {
        final var value = new AtomicReference<T>();
        return () -> {
            final var previousValue = value.get();
            if (previousValue != null) {
                return previousValue;
            }

            final var newValue = delegate.get();
            value.set(newValue);
            return newValue;
        };
    }
```

2024-04-12 16:39 UTC, steven-sheehy requested changes

2024-04-12 16:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/Suppliers.java
> +    private static class SupplierOfInstance<T extends @Nullable Object> implements Supplier<T>, Serializable {
Remove this method and class since they are unused and we should be using the guava version.

2024-04-12 16:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
> +        return Suppliers.memoize(() -> getNumberOfAllAndPositiveBalanceTokenAssociations(accountId, timestamp)
This doesn't share the `getNumberOfAllAndPositiveBalanceTokenAssociations` supplier across these two methods so it's still run twice. We should remove these two methods and do the following in `accountFromEntity`:

```java
var tokenAccountBalances = getNumberOfAllAndPositiveBalanceTokenAssociations(account, timestamp);
var all = () -> tokenAccountBalances.get().all();
var positive = () -> tokenAccountBalances.get().positive();
```

2024-04-12 18:32 UTC, steven-sheehy approved these changes
LGTM 🥂

2024-04-12 18:52 UTC, steven-sheehy approved these changes

2024-04-12 19:00 UTC, merged