fix: Fix address(this) resolution when mirror address is passed in the call
hashgraph/hedera-mirror-node pull request #7984
Opened 2024-03-29 08:32 UTC by kselveliev

There is an inconsistency on call address(this) function depending on the **to** parameter in a contract call request.
Address(this) will return whatever is specified as the 'to' parameter in the http request.
If a contract is created via ethereum transaction on hedera it will have a canonical ethereum address. It will also have the long zero address.
So in our contract call request we can put in the **to** parameter either the canonical evm address or the long zero and it should return the same response.
Currently if we call address(this) of a contract that has a canonical evm address but we pass it's long zero address in the contract call request it will return long zero address in the response. But we actually want the evm address returned.

This **PR** adds a check to see if a long zero address in passed in the request and will make the following verification:
If the address is long zero verify that there might be a canonical evm address.
If there exists a canonical evm address use it instead of the long zero.
Otherwise use the long zero.

 
This PR modifies:
`MirrorEvmTxProcessorImpl` add new method to determine the correct **to** address

**Related issue(s)**:

Fixes #7857 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2024-04-01 18:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +        ADDRESS_THIS("getAddressThis", null, null);
We need more test cases like passing mirror address and alias address and checking the response is correct

2024-04-02 03:53 UTC, steven-sheehy requested changes

2024-04-02 03:53 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            Address canonical = tokenAccessor.canonicalAddress(receiver);
Why are we using `TokenAccessor` to lookup an account's canonical address instead of `AccountAccessor.canonicalAddress()`?

2024-04-02 03:53 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +        if (aliasManager.resolveForEvm(receiver).equals(receiver)) {
Why can't we use the simpler and more efficient `aliasManager.isMirror(receiver)`?

2024-04-02 03:53 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            return receiver;
Invert this logic so we can avoid the extra nesting and return early if it's not a mirror.

```java
if (!aliasManager.isMirror(address)) {
    return reciever;
}

// rest of logic
```

2024-04-02 03:53 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +        }
Should push this check into `aliasManager.isMirror()`

2024-04-02 10:40 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +        ADDRESS_THIS("getAddressThis", null, null);
You are right. I've added a test where we pass a mirror address and we have also and evm address present to verify that we return evm address. I've also added a test where we pass mirror address but we do not have evm address and we verify that we return mirror address.

2024-04-02 11:56 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            if (null == canonical || Address.ZERO.equals(canonical)) {
Comment addressed

2024-04-02 11:57 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            Address canonical = tokenAccessor.canonicalAddress(receiver);
From what i’ve been testing
` accountAccessor.canonicalAddress(0x00000000000000000000000000000000000004e7)` will still
return 0x00000000000000000000000000000000000004e7 even if there is also an evm address.

it will first execute this check internally 
```
if (aliases.isInUse(addressOrAlias)) {
    return addressOrAlias;
} 
```
this will result into true and return 0x00000000000000000000000000000000000004e7 when we 
want the evm address. This is why I avoided it.
 Could be observed in this test -> testGetAddressThisWithLongZeroRecipientThatHasEvmAlias

2024-04-02 11:59 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +            return receiver;
Comment addressed. Added this if in the first check.
```
 if (receiver == null || receiver.equals(Address.ZERO) || !aliasManager.isMirror(receiver)) {
            return receiver;
}
```

2024-04-02 12:01 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +        }
Got a bit scared to do it since we will need to override isMirror method from HederaEvmContractAliases. And I don't know how this might affect other code. I can try to do it if you want.

2024-04-02 12:02 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +        if (aliasManager.resolveForEvm(receiver).equals(receiver)) {
I think we can. If we add `!aliasManager.isMirror(receiver)` in the first if we can even omit this if check.

2024-04-02 15:03 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-04-02 15:03 UTC, merged