Remove exception in TxnResourceUsageEstimator - usageGiven
hashgraph/hedera-mirror-node pull request #8021
Opened 2024-04-04 06:11 UTC by zhpetkov

**Description**:
Remove throws an exception in `TxnResourceUsageEstimator` - `usageGiven` and make needed changes because this affects all classes that implement it. 

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-04 07:57 UTC, bilyana-gospodinova requested changes

2024-04-04 07:57 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimator.java
> -    FeeData usageGiven(TransactionBody txn, SigValueObj sigUsage) throws Exception;
The javadoc that says an `Exception` can be thrown from this method needs to be updated. 

The point for this task was to verify that there are no differences in the exception handling between services and the mirror node - for both checked and unchecked exceptions. What happens if a runtime exception is thrown (it is mentioned that a `NullPointerException` can be thrown)? I don't see a test in the mirror node for that case. Please add accordingly. 

Can you please clarify if you checked for differences in the code flow in case of an exception - in both services and the mirror node? Is there a case when the mirror node returns a different response from the one in services?

FYI - I found this PR in services when this method is modified to not throw an exception - https://github.com/hashgraph/hedera-services/pull/9139. It might help and give some hints from where to start in case you haven't made the above mentioned checks.

2024-04-16 06:26 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculatorTest.java
> +    void failsWithNpeGivenApplicableButUnusableCalculator() {
Please add a test for the case when `UsageBasedFeeCalculator#getTxnUsageEstimator` throws a `NoSuchElementException` and verify that the behavior is the same as in services.

2024-04-18 12:53 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimator.java
> -    FeeData usageGiven(TransactionBody txn, SigValueObj sigUsage) throws Exception;
The last commit update javadoc. I removed exceptions when the txn is malformed, because it is removed in hedera-services. I replaced `IllegalArgumentException` with `NullPointerException`. I checked exception handling in `UsageBasedFeeCalculator`, `TokenAssociateResourceUsage`, `TokenDeleteResourceUsage`, `TokenDissociateResourceUsage` (in mirror node there isn’t `usageGiven` calculate the fee for token associate transaction in modular code), `TokenUpdateResourceUsage`(in mirror node there isn’t `usageGiven` calculate the fee for token associate transaction in modular code).

2024-04-19 21:59 UTC, steven-sheehy approved these changes

2024-04-22 10:47 UTC, bilyana-gospodinova approved these changes
LGTM but there are 2 Sonar issues.

2024-04-22 11:41 UTC, kselveliev approved these changes

2024-04-22 14:25 UTC, merged