7858 controller enhancement
hashgraph/hedera-mirror-node pull request #8026
Opened 2024-04-05 14:50 UTC by mgoelswirlds

**Description**:
This PR add evm address and alias account Id validation.

This PR modifies 
- Add evm address and alias account ID validation
- Account ID existence check in an entityService
- Getting system shard value from properties and validating the input shard value against it.
-  Adding caching to the repository existsById api

**Related issue(s)**:

Fixes #7858

**Notes for reviewer**:
There is some spotless reformatting due to merge from main which can be ignored.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-05 14:51 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdParameter.java
Work to refactor this into 3 separate parameter classes, will be done in parallel, in a separate PR.
Functionality it will be the same.

2024-04-05 14:54 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +    public long lookup(EntityIdParameter accountId) {
Adding this lookup method here to be reused by other APIs in the fuure.

2024-04-05 20:41 UTC, steven-sheehy requested changes

2024-04-05 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +        }
This should be a switch statement by enum. Checking if the num/alias/evmAddress is not null is redundant since that should be guaranteed by `EntityIdParameter.valueOf()`.

2024-04-05 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +        return id;
Instead of returning zero, we should throw an error if one of these three types did not validate.

2024-04-05 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +            }
Move this not found assertion outside each check so it doesn't repeat. Use generic message like "No account found for the given ID".

2024-04-05 20:41 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/EntityRepositoryTest.java
> +                domainBuilder.entity().customize((b) -> b.deleted(true)).persist();
For each existence query, add a test with deleted=null

2024-04-05 20:44 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/EntityRepository.java
> +    Optional<Long> findByEvmAddress(byte[] evmAddress);
Actually, think caffeine doesn't work with arrays. Would have to wrap it in something so maybe can defer.

2024-04-08 15:25 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdParameter.java
> +    public static final String EVM_ADDRESS_REGEX = "^(((0x)?|((\\d{1,5})\\.)?((\\d{1,5})\\.)?)([A-Fa-f0-9]{40}))$";
This wasn't supported. Added a testcase. Handling `0.0xabcdef`, or `0.0.0xabcdef` now.

2024-04-08 19:56 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdParameter.java
> +    }
For arrays SonarLint complains about them not being considered. I am not adding it to a map or set anywhere.I will suppress it.

2024-04-09 14:14 UTC, xin-hedera requested changes

2024-04-09 14:14 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdAliasParameter.java
> +        return new EntityIdAliasParameter(new Base32().decode(aliasMatcher.group(5)), shard, realm);
I don't see how to configure apache commons `Base32` to omit padding, our alias format is rfc4648 without padding (https://hips.hedera.com/hip/hip-32).

can try guava `BaseEncoding.base32().omitPadding()`

2024-04-09 14:14 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/EntityRepository.java
> +    boolean existsById(Long entityId);
we can't cache any of these since in rest java we don't have a way to evict the cache entry when `deleted` becomes `true` from `false`

2024-04-09 14:46 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/EntityRepository.java
> +    boolean existsById(Long entityId);
The cache has an expireAfterWrite=60s to purge older entries so that they're eventually consistent and show the correct deleted flag

2024-04-09 15:18 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/EntityRepository.java
> +    boolean existsById(Long entityId);
Still think 60s is too long, enough for an EVM address to be claimed by a different account id.

2024-04-09 17:35 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/EntityIdParameterTest.java
> +    void entityParseFromString() {
Prefer this test method be split into separate `valueOfId`, `valueOfAlias`, and `valueOfEvmAddress` methods each with parameterized inputs.

2024-04-09 18:06 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +                    case EntityIdNumParameter(EntityId num) -> entityRepository.existsById(num.getId()) ? Optional.of(num.getId()) : Optional.empty();
Since this  just returns a boolean, map wouldn't work and would prefer to leave this as is.

2024-04-09 18:07 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +                    case EntityIdEvmAddressParameter(byte[] evmAddress, Long shard, Long realm) -> entityRepository.findByEvmAddress(evmAddress);
Doesn't work, all params are mandatory for the object.

2024-04-09 18:15 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
> +                    case EntityIdEvmAddressParameter(byte[] evmAddress, Long shard, Long realm) -> entityRepository.findByEvmAddress(evmAddress);
Ok, then just `case EntityIdEvmAddressParameter p -> entityRepository.findByAlias(p.alias()`, etc would be preferable since it doesn't repeat all parameters.

2024-04-09 19:27 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdEvmAddressParameter.java
> +        }
I cannot use this. I am checking for a particular group matching here. Just checking the count wouldn't be accurate.
Count `Returns the number of capturing groups in this matcher's pattern.`, in this case the `groupCount()` will always return 6 (which is the number of groups in the pattern) if the pattern matches overall. So before extracting the value for say realm , I need to ensure that group match exists there.

2024-04-09 19:52 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdEvmAddressParameter.java
> +        }
The point still remains that generating a string just to discard it is inefficient. So instead of check group(3) should check group(4) and store it in a variable for later conversion to long. Or can use `matcher.start(4) >= 0` which does the same check without the string generation.

2024-04-10 04:28 UTC, steven-sheehy requested changes

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/EntityIdParameterTest.java
> +    void valueOfEvmAddress(String givenEvmAddress,String expectedEvmAddress) {
Add expected shard and realm parameters and verify them against actual.

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/EntityIdParameterTest.java
> +    void valueOfAlias(String givenAlias, String expectedAlias) {
Add expected shard and realm parameters and verify them against actual.

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +        assertNull(result.getLinks().getNext());
Always use assertj. Check elsewhere.

```suggestion
        assertThat(result.getLinks().getNext()).isNull();
```

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +                .accept(MediaType.ALL)
Remove accept all header from all tests since in setup we already set an appropriate accept header.

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
>      void successWithNoQueryParamsShardRealmNumAccountId() {
Need a parameterized test for 404 not found with various ids

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
>      void successWithNoQueryParamsShardRealmNumAccountId() {
Since `AllowancesController` can in the future contain other allowances APIs, should prefix all tests with `nftAllowances`. Can also simplify names to not mention things that aren't present.

```suggestion
    void nftAllowancesEntityId() {
```

2024-04-10 04:28 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/EntityServiceTest.java
> +public class EntityServiceTest extends RestJavaIntegrationTest {
Change all test classes to package private.

```suggestion
class EntityServiceTest extends RestJavaIntegrationTest {
```

2024-04-10 04:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdNumParameter.java
> +        long shard = 0;
Actually shard should default to `RestJavaProperties.getShard()` instead of zero. Not sure the best way to do this though. Same comment for other classes.

2024-04-10 15:17 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.restJava.cache.entity`        | maximumSize=100000,expireAfterWrite=10s,recordStats  | The Caffeine cache specification for the entity.                                         |
missing `hedera.mirror.restJava.cache.enabled`

2024-04-10 18:04 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdNumParameter.java
> +        long shard = 0;
Found a way to get the bean in a non spring class.

2024-04-10 19:45 UTC, steven-sheehy requested changes

2024-04-10 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +    }
It's not sufficient to just check response code, we also need to verify error response body follows our expected format. Use assertj to verify additional exception details.

```suggestion
        assertThatThrownBy(() -> restClient.get()
                    .uri(uriParams, 1000)
                    .retrieve()
                    .body(NftAllowancesResponse.class)
                )
                .isInstanceOf(HttpClientErrorException.NotFound.class)
                .hasMessageContaining("some message")
                .asInstanceOf(InstanceOfAssertFactories.type(HttpClientErrorException.NotFound.class))
                .extracting(r -> r.getResponseBodyAs(Error.class).getStatus().getMessages().get(0))
                .returns("foo", ErrorStatusMessagesInner::getData)
                .returns("bar", ErrorStatusMessagesInner::getDetail)
                .returns("baz", ErrorStatusMessagesInner::getMessage);
```

We can put this in a helper method and use it to verify the other error cases.

2024-04-10 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/SpringApplicationContext.java
> +@Component
Missing license header and we prefer to use `@Named`

2024-04-10 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/SpringApplicationContext.java
> +    }
nit: Could use a static final AtomicReference.

```suggestion
       CONTEXT.set(context);
    }
```

2024-04-10 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/EntityRepositoryTest.java
> +public class EntityRepositoryTest extends RestJavaIntegrationTest {
```suggestion
class EntityRepositoryTest extends RestJavaIntegrationTest {
```

2024-04-11 02:28 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +    }
The error message extracted here is not the expected one.It is empty. I am working on getting this to work.

2024-04-11 03:11 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +    }
It may not know how to resolve the type from the exception. Might have to register a `defaultStatusHandler()` on the `RestClientBuilder` with proper message converters.

2024-04-11 13:50 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.restJava.cache.enabled`       | true                                                  | Whether caching should be enabled at all.                                                |
nit, order, this should be before `cache.entity`

2024-04-11 18:30 UTC, steven-sheehy commented
Should suppress the 2 override equals for arrays sonar warning.

2024-04-12 14:43 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +    }
Currently only this method is returning an Error type in the service layer and not through the controller so I am checking for the detailed message only for the EntityNotFound exception.

2024-04-12 16:24 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
> +        assertThatThrownBy(() -> restClient.get().uri(uriParams, accountId).retrieve().body(NftAllowancesResponse.class)
Prefer to decouple test invocation from error validation so it's more reusable.

```suggestion
    private void validateError(ThrowingCallable callable, Class<? extends HttpClientErrorException> clazz, String message, String description) {
        assertThatThrownBy(callable)
```

2024-04-12 16:24 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
Why are we not able to use the validateError helper method for these two to verify the structure of their response?

2024-04-12 17:22 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
That is because these 2 exceptions are generated by the controller either for the method or during parameter conversion and the Exception controller advice doesn't catch them so the Error type is not getting generated.

2024-04-12 17:36 UTC, steven-sheehy requested changes

2024-04-12 17:36 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/ExceptionControllerAdvice.java
> +        return errorResponse(e.getMessage(), SERVICE_UNAVAILABLE);
Revert. We shouldn't expose 5xx error messages to clients.

2024-04-12 17:36 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
>          return errorResponse(e.getMessage(),INTERNAL_SERVER_ERROR);
Revert message change so we don't expose internal details for 5xx.

2024-04-12 17:36 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
So that's a bug. `GenericControllerAdvice` should ensure all error responses use our json format. Can be follow up.

2024-04-12 17:50 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
Will create a follow-up ticket.

2024-04-12 17:57 UTC, steven-sheehy approved these changes
LGTM

2024-04-12 18:53 UTC, xin-hedera approved these changes
LGTM

2024-04-12 19:00 UTC, merged