Apply best practices and standards to remaining workflows
hashgraph/hedera-mirror-node pull request #8047
Opened 2024-04-06 23:46 UTC by nathanklick

## Description

This pull request changes the following:

- Applies best practices and standards to the `rosetta.yml` workflow.

2024-04-22 19:52 UTC, steven-sheehy requested changes

2024-04-22 19:52 UTC, steven-sheehy commented on .github/workflows/charts.yml
This workflow doesn't run by default for PRs. Was this workflow tested?

2024-04-22 19:52 UTC, steven-sheehy commented on .github/workflows/cleanup.yml
This workflow doesn't run by default for PRs. Was this workflow tested?

2024-04-22 19:52 UTC, steven-sheehy commented on .github/workflows/snyk-monitor.yml
> +name: Security
Will there be problems if two workflows have the same name? Probably should make it distinct

2024-04-22 19:52 UTC, steven-sheehy commented on .github/workflows/security.yml
> +
nit: Remove two extra lines

2024-04-22 19:52 UTC, steven-sheehy commented on .github/workflows/rosetta.yml
> +  workflow_dispatch:
Is this needed?

2024-04-22 19:52 UTC, steven-sheehy commented on .github/workflows/release-integration.yml
This workflow, release-production, and release-automation don't run by default for PRs. Not sure how we'd test easily though so let's hope it doesn't break our release.

2024-04-22 21:21 UTC, rbarkerSL commented on .github/workflows/snyk-monitor.yml
> +name: Security
I'll switch the name over to `Monitor`

2024-04-22 21:23 UTC, rbarkerSL commented on .github/workflows/rosetta.yml
> +      - name: Setup Node
when we run `Run Rosetta Postman API Tests` it uses npm.

2024-04-23 19:21 UTC, rbarkerSL commented on .github/workflows/release-integration.yml
Release Engineering will be available during the next release in case errors occur.

@rbarkerSL @nathanklick

2024-04-23 19:38 UTC, steven-sheehy commented on .github/workflows/snyk-monitor.yml
> +name: Security
We have two mirror node components called monitor already. Should call it `Snyk Monitor` so we don't confuse the three names

2024-04-23 19:56 UTC, steven-sheehy commented on .github/workflows/gradle.yml
> +    name: Build
This change breaks the required jobs in the rules.

2024-04-24 14:58 UTC, xin-hedera commented on .github/workflows/cleanup.yml
> +    runs-on: [self-hosted, Linux, large, ephemeral]
nit: is there a small instance? the cleanup job runs a very lightweight script so using large would waste resource.

2024-04-24 15:11 UTC, rbarkerSL commented on .github/workflows/gradle.yml
> +    name: Build
@nathanklick  and I are looking at updating the rules system. The name field here is desired but we aren't able to update the rules until we are ready to merge.

2024-04-24 15:50 UTC, rbarkerSL commented on .github/workflows/charts.yml
Added a workflow-dispatch trigger and manually ran the workflow in gh CLI

[latest run](https://github.com/hashgraph/hedera-mirror-node/actions/runs/8819204952)

2024-04-24 15:51 UTC, rbarkerSL commented on .github/workflows/cleanup.yml
Added a workflow-dispatch trigger and manually ran the workflow in gh CLI

[latest run](https://github.com/hashgraph/hedera-mirror-node/actions/runs/8818891422)

2024-04-24 15:52 UTC, rbarkerSL commented on .github/workflows/snyk-monitor.yml
> +name: Security
Updated name to `Snyk Monitor`

2024-04-24 16:08 UTC, rbarkerSL commented on .github/workflows/cleanup.yml
> +    runs-on: [self-hosted, Linux, large, ephemeral]
We'll add a medium instance, small is typically reserved for scheduled-task executors.

2024-04-24 19:50 UTC, rbarkerSL commented on .github/workflows/cleanup.yml
> +      - name: Checkout Code
Removed this step and tested cleanup workflow again.

2024-04-25 03:54 UTC, steven-sheehy approved these changes
LGTM

2024-04-25 13:35 UTC, xin-hedera approved these changes
LGTM

2024-04-25 18:49 UTC, merged