Expose HIPs-646/657/765 token metadata in REST API
hashgraph/hedera-mirror-node pull request #8059
Opened 2024-04-09 13:37 UTC by jascks

**Description**:
Expose new token metadata being ingested by Importer for services 0.48+.

For this PR:
* Add a base64 encoded `metadata` field to `/api/v1/tokens`.
* Add base64 encoded `metadata` and `metadata_key`, formatted with standard key encoding format, to `/api/v1/tokens/{id}`

**Related issue(s)**:

Fixes #6549

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-10 13:32 UTC, jascks commented on hedera-mirror-rest/model/token.js
> +    this.metadata_key = token.metadata_key;
This does not seem necessary as this file has not been updated recently. It seems in IDEA, the only use of this `Token` class is in `./token.js` line 228 where t he `TYPE` constant is referenced. Not sure the constructor is used anymore...

2024-04-10 15:07 UTC, xin-hedera commented on hedera-mirror-rest/model/token.js
> +    this.metadata_key = token.metadata_key;
should be `metadataKey` since in model the convention is camelCase.

2024-04-10 16:56 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
The description should not just describe the format of the data but also it's business purpose as in HAPI. Same for below metadata and metadata_key

2024-04-10 21:15 UTC, jascks commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
This was lifted from the existing `Nft` schema. As far as the business purpose of `metadata`, what I'm seeing in the HIPs and protobufs is:

- Metadata of the created token definition
- Retrieves the metadata of a token
- If set, the metadata of the updated token definition
- There is a need for a token creator to specify additional “metadata” about the token
- A list of metadata that are being created
- Represents the unique metadata of the NFT

It seems the business purpose is associating metadata with a token/NFT.  [HIP-657](https://hips.hedera.com/hip/hip-657) (Mutable metadata fields for dynamic NFTs) actually suggest uses for metadata in its **MOTIVATION** section:

> With the ability to update the metadata of an NFT, developers can create game pieces that gain new equipment and stats, legal agreements that reflect changing parameters, or even NFTs that update their images based on the time of day. ...

`metadata_key` is a different story:
The key which can change the metadata of a token (token definition, partition definition, and individual NFTs).

Not sure what a _partition_ is in this context.

2024-04-11 13:51 UTC, jascks commented on hedera-mirror-rest/model/token.js
> +    this.metadata_key = token.metadata_key;
Done!

2024-04-11 13:56 UTC, xin-hedera requested changes

2024-04-11 13:56 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/nfts/{id}/deleted-nft.json
> +        "metadata": "token metadata",
revert changes to specs in this folder, since token class metadata and metadata key are irrelevant to this API

2024-04-11 13:56 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
> +    "metadata": null,
change at least one spec in this folder to have non-null metadata and metadata key

2024-04-11 14:11 UTC, jascks commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
In the `TokenInfo` schema, none of the other keys defined has a description, and when I add `description` to `metdata_key` IDEA is unhappy.

![metadata_key_description_error](https://github.com/hashgraph/hedera-mirror-node/assets/218465/e97f2d60-2d1b-49d9-acd3-283903b66ce2)

2024-04-11 14:21 UTC, jascks commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/nfts/{id}/deleted-nft.json
> +        "metadata": "token metadata",
I agree these two new token class level columns are irrelevant to this API, but adding them to one of the tokens in the setup is to verify their presence does not affect the results returned (the metadata for the individual NFTs).

2024-04-11 14:23 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
Have to do something like this:

```
        staked_account_id:
          allOf:
            - $ref: "#/components/schemas/EntityId"
            - description: The account to which this account is staking
```

2024-04-11 14:28 UTC, jascks commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
> +    "metadata": null,
This was done in `no-params.json` below. Will add more.

2024-04-11 14:31 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/nfts/{id}/deleted-nft.json
> +        "metadata": "token metadata",
still strongly against it

2024-04-11 15:25 UTC, jascks commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/nfts/{id}/deleted-nft.json
> +        "metadata": "token metadata",
Okay, will revert.

2024-04-11 15:59 UTC, jascks commented on hedera-mirror-rest/__tests__/specs/tokens/{id}/nfts/{id}/deleted-nft.json
> +        "metadata": "token metadata",
Done!

2024-04-11 21:37 UTC, jascks commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
Updated.

2024-04-11 21:39 UTC, steven-sheehy approved these changes
LGTM

2024-04-11 22:44 UTC, xin-hedera approved these changes
LGTM

2024-04-12 00:52 UTC, merged