updated stackgres config
hashgraph/hedera-mirror-node pull request #8073
Opened 2024-04-12 03:39 UTC by jnels124

**Description**:
* enable postgres prometheus exporter for citus pods
* configure container resources for prometheus  exporter

**Related issue(s)**:

Fixes #8062 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-12 18:12 UTC, steven-sheehy requested changes

2024-04-12 18:12 UTC, steven-sheehy commented on docs/database/citus.md
> +kubectl run -n ${NAMESPACE} psql-util -it --rm --image=bitnami/postgresql:16 --env="PGPASSWORD=${DB_PASSWORD}" --command -- psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME}
The `mirror` secret is flux specific and shouldn't be referenced here. Also, these commands are quite complex. We should strive for one or two lines even if it means hardcoding a few things:

```suggestion
export DB_PASSWORD=$(kubectl get secret ${RELEASE}-passwords -o yaml | ksd | yq '.stringData.HEDERA_MIRROR_IMPORTER_DB_OWNERPASSWORD')
kubectl run psql-util -it --rm --image=bitnami/postgresql:16 --env="PGPASSWORD=${DB_PASSWORD}" --command -- psql -h ${RELEASE}-citus-coord-primary -U mirror_node -d mirror_node
```

2024-04-15 15:58 UTC, steven-sheehy approved these changes
LGTM

2024-04-15 16:16 UTC, edwin-greene approved these changes
Looks good to me

2024-04-15 17:17 UTC, merged