Optimize cache control per endpoint
hashgraph/hedera-mirror-node pull request #8077
Opened 2024-04-12 14:51 UTC by xin-hedera

**Description**:

This PR optimizes cache control per rest api endpoint

- Set appropriate cache control header per endpoint in default config file
- Add a router middleware to record the complete registered request path
- Workaround path conflict between `/contracts/results/:transactionIdOrHash` and `/contracts/results/logs`
- Improve integration test response header validation

**Related issue(s)**:

Fixes #7954 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-12 14:59 UTC, xin-hedera commented on hedera-mirror-rest/routes/index.js
> +const recordRequestPath = async (req, res) => {
In `responseHandler` middleware, if a request's url matches a handler function in a `Router`, `req.baseUrl` is empty, and `req.route.path` is the fragment of the handler in the `Router`. For example, for block by hash or number, in `responseHandler`, `req.route.path` is `/:hashOrNumber`. `req.baseUrl` is correct inside the `Router, i.e., `/api/v1/blocks`

2024-04-15 16:20 UTC, edwin-greene approved these changes
Looks good to me

2024-04-15 19:39 UTC, steven-sheehy requested changes

2024-04-15 19:39 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +              { "cache-control": "public, max-age=300" }
Let's bump all 300s to 600

2024-04-15 19:39 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
>              /api/v1/transactions/:transactionIdOrHash:
Let's bump `/api/v1/transactions` to 2s since it's so heavily used.

2024-04-15 19:39 UTC, steven-sheehy commented on docs/rest/README.md
> +| `/api/v1/accounts/:idOrAlias?timestamp=`                 | `account_balance`, `crypto_transfer`, `entity`, `entity_history`, `entity_stake`, `entity_stake_history`, `token_balance`, `token_transfer
Should we define a higher, dynamic cache-control depending upon whether a timestamp parameter is present for any endpoint (and maybe if time is lte:now)? Could be follow up if you agree.

2024-04-15 19:39 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +            /api/v1/accounts/:idOrAliasOrEvmAddress/rewards:
Let's bump accounts/{id} to 2s since it's heavily used

2024-04-15 19:39 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +            /api/v1/topics/:topicId/messages/:sequenceNumber:
Let's add `/api/v1/tokens/{id}` at 5s since it's heavily used and the data shouldn't be updated often.

2024-04-15 20:27 UTC, xin-hedera commented on docs/rest/README.md
> +| `/api/v1/accounts/:idOrAlias?timestamp=`                 | `account_balance`, `crypto_transfer`, `entity`, `entity_history`, `entity_stake`, `entity_stake_history`, `token_balance`, `token_transfer
sure, it'll based on if the upper bound timestamp is in the past. will create a ticket.

2024-04-15 21:31 UTC, jnels124 approved these changes
LGTM

2024-04-15 21:53 UTC, steven-sheehy approved these changes
LGTM

2024-04-15 21:54 UTC, merged