8105 enable rest java chart by default
hashgraph/hedera-mirror-node pull request #8117
Opened 2024-04-16 18:16 UTC by jascks

**Description**:
Ensure the rest-java pods run by default in all prod and non-prod environments.

This PR:
* Add nft allowances to ingress route
* Change rest-java chart to be enabled by default
* Increase request resources in values.yaml
* Decrease request resources in ci
* Unset override in integration flux config
* Remove placeholder DummyController and related ingress route

**Related issue(s)**:

Fixes #8105

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-17 23:53 UTC, steven-sheehy commented
CI is failing since 0.0.2 doesn't exist in demo bucket. Need to see if there's any row in entity table for demo bucket and customize with that entity in CI.

2024-04-18 21:15 UTC, xin-hedera commented on charts/hedera-mirror-rest-java/postman.json
> +									"    pm.expect(pm.response.text()).to.include(\"\\\"allowances\\\":[]\");",
nit, it's better to do exact match of the JSON response

```
{
  "allowances": [],
  "links": {
    "next": null
  }
}
```

2024-04-18 21:24 UTC, steven-sheehy commented on charts/hedera-mirror/templates/NOTES.txt
> +  curl -s "http://${REST_IP:-127.0.0.1}:{{.Values.restjava.service.port}}/api/v1/accounts/0.0.2/allowances/nfts"
Except other chart users can customize it so we should keep it using the helm property

2024-04-18 22:57 UTC, steven-sheehy requested changes

2024-04-18 22:57 UTC, steven-sheehy commented on charts/hedera-mirror/templates/NOTES.txt
> +  kubectl port-forward "service/{{ .Release.Name }}-restjava" -n {{ include "hedera-mirror.namespace" . }} {{ .Values.rest.service.port }}:80 &
There's a copy/paste error here from when this was initially added. Also, we can utilize the named `http` port as using port 80 will break if we change it. Finally, service.port is port 80 which will fail to bind without sudo. Probably we should use a hardcoded port >= 1024 like 8084. Then we can use Xin's previous suggestion.

```suggestion
  kubectl port-forward "service/{{ .Release.Name }}-restjava" -n {{ include "hedera-mirror.namespace" . }} 8084:http &
```

2024-04-19 13:06 UTC, jascks commented on charts/hedera-mirror/templates/NOTES.txt
> +  kubectl port-forward "service/{{ .Release.Name }}-restjava" -n {{ include "hedera-mirror.namespace" . }} {{ .Values.rest.service.port }}:80 &
That make sense. I changed it manually myself to 9999 when testing it out. 😄 

Questions:

1. The other services (except grpc) forward to local port 80 as well, presenting the same problem. Should I change the all?
2. Only one can bind to 8084 at a time, should each service bind to a unique local port, say starting at 8080 or someothing?

2024-04-19 14:47 UTC, jascks commented on charts/hedera-mirror-rest-java/postman.json
> +									"    pm.expect(pm.response.text()).to.include(\"\\\"allowances\\\":[]\");",
Done. Updated in postman and exported to this file.

![Screenshot 2024-04-19 at 8 46 23 AM](https://github.com/hashgraph/hedera-mirror-node/assets/218465/f3d0490a-4f8b-4cb8-862e-1e3f379a97aa)

2024-04-19 14:59 UTC, steven-sheehy commented on charts/hedera-mirror/templates/NOTES.txt
> +  kubectl port-forward "service/{{ .Release.Name }}-restjava" -n {{ include "hedera-mirror.namespace" . }} {{ .Values.rest.service.port }}:80 &
You can change them all as long as you test each out by running `helm template` and running the rendered commands. Each app should just use its internal port that it actually listens on, e.g. importer uses 8080, etc.

2024-04-19 19:23 UTC, jascks commented on charts/hedera-mirror/templates/NOTES.txt
> +  kubectl port-forward "service/{{ .Release.Name }}-restjava" -n {{ include "hedera-mirror.namespace" . }} {{ .Values.rest.service.port }}:80 &
Okay, I'm taking a more minimalist approach and sticking to the original suggestions.

Deploying to minikube, this section renders as:
```
To access the Java REST API:
  kubectl port-forward "service/mirror-restjava" -n mirror-jeff 8084:80 &
  curl -s "http://${REST_IP:-127.0.0.1}:8084/api/v1/accounts/0.0.2/allowances/nfts"
```

The port forward works.

2024-04-19 19:39 UTC, steven-sheehy approved these changes
LGTM

2024-04-19 22:12 UTC, xin-hedera approved these changes
LGTM

2024-04-20 01:15 UTC, merged