EthereumTransaction acceptance tests
hashgraph/hedera-mirror-node pull request #8123
Opened 2024-04-18 13:10 UTC by JivkoKelchev

**Description**:
This PR adds a scenario to validate ethereum contract create and calls.
It cover all three transaction types.

**Related issue(s)**:

Fixes #7655

**Notes for reviewer**:

2024-04-25 04:52 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ethereum/EthTxData.java
> +                    Integers.toBytesUnsigned(value),
Just FYI, I've fixed a bug related to this: https://github.com/hashgraph/hedera-services/pull/12834/files#r1577479438. Let's see if it gets approved and then we can fix it here as well.

2024-04-25 05:05 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        log.info("Deleting {} contracts", contractIds.size());
Maybe we should update the log to say that we can't delete eth contracts?

2024-04-25 05:08 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +            ContractFunctionParameters contractFunctionParameters) {
Should we delete the `contractFunctionParameters` param? It's currently not used and the one place that this method is called we pass `null`.

2024-04-25 11:56 UTC, vtronkov approved these changes

2024-05-21 13:47 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ethereum/EthTxData.java
> +                    Integers.toBytesUnsigned(value),
When I use `Integers.toBytesUnsigned(value)` here, for `BigInteger.ZERO`, the resulting byte array is [].
If I use `value.toByteArray()`, the resulting byte array is [0] and I'm getting: `com.hedera.hashgraph.sdk.PrecheckStatusException: Hedera transaction 0.0.1069@1716290530.844000000 failed pre-check with the status INVALID_ETHEREUM_TRANSACTION`
So I decided to keep the current implementation.

2024-05-22 00:17 UTC, steven-sheehy requested changes

2024-05-22 00:17 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
> +  When I create a child contract by calling the parent contract function to deploy using CREATE2 with EIP-1559
The purpose of this ticket was to test the 3 types of Ethereum transactions impact on different code paths in mirror node. We don't need to test everything that the contract spec tested like parent/child, CREATE2, etc. as doing so doesn't stress different mirror node code paths. So we should just really have 3 total HAPI transactions: create (EIP-1559), call (EIP-2930), call (legacy). This will save on transaction costs and maintenance burden.

2024-05-22 00:17 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +public class EthCallFeature extends AbstractFeature {
```suggestion
public class EthereumFeature extends AbstractFeature {
```

2024-05-22 00:17 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
ethereum.feature

2024-05-22 00:17 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +    private ContractResponse verifyContractFromMirror(boolean isDeleted) {
This method and others are duplicated in ContractFeature. Please refactor to move them to a new `AbstractContractFeature` parent class. Or we can just combine ethereum and contract features into one as separate scenarios since there's so much overlap.

2024-05-23 07:24 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +    private final HashMap<PrivateKey, Integer> accountNonce = new HashMap<>();
Done

2024-05-23 07:27 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +    protected AccountClient accountClient;
I moved both `ethereumClient` and `accountClient` in to `EthereumFeature`.

2024-05-23 07:27 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +    protected EthereumClient ethereumClient;
I moved both `ethereumClient` and `accountClient` in to `EthereumFeature`.

2024-05-23 07:30 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        byte[] chainId = Integers.toBytes(298);
Done. 
Great suggestion!

2024-05-23 07:36 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +    public enum NodeNameEnum {
Done.

2024-05-23 07:36 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +    protected PrivateKey ethereum_signer_private_key;
Done

2024-05-23 07:40 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
> +  When I create a child contract by calling the parent contract function to deploy using CREATE2 with EIP-1559
Done, I left the creation and the first two calls.
I wasn't sure about the scenarios to use, so I reused everything from the contracts.

2024-05-23 07:40 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +public class EthCallFeature extends AbstractFeature {
Done.

2024-05-23 07:40 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
Done.

2024-05-23 07:49 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +    private ContractResponse verifyContractFromMirror(boolean isDeleted) {
I reduced the duplications, by adding common base class of contract and ethereum features.

2024-05-25 03:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        byte[] chainId = Integers.toBytes(298);
It's not clear: Did you test against previewnet and testnet to ensure it works?

2024-05-25 03:37 UTC, steven-sheehy requested changes
You missed a lot of feedback from my previous review. Please expand the collapsed feedback to see all items...

2024-05-25 03:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthereumFeature.java
> +        assertNotNull(executeContractResult.contractFunctionResult());
Mirror node standard is to always use assertj `assertThat()`. Same comment elsewhere in new files.

2024-05-25 03:37 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthereumFeature.java
> +        mirrorTransaction = finalizeHollowAccount ? transactions.get(1) : transactions.get(0);
```suggestion
        var transactions = mirrorTransactionsResponse.getTransactions();
        assertThat(transactions).isNotEmpty();
        var mirrorTransaction = finalizeHollowAccount ? transactions.get(1) : transactions.get(0);
```

2024-05-27 13:51 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        byte[] chainId = Integers.toBytes(298);
Yes, I tested against previewnet and testnet and it is working as intended.

2024-05-27 13:55 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +                new byte[] {}, // accessList
Done. Thanks for the suggestion.

2024-05-27 13:56 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +    public String getClientAddress() {
Removed

2024-05-27 13:57 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +    public record ExecuteContractResult(
Done

2024-05-27 14:05 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +}
Done. Thanks for the suggestion again.

2024-05-27 14:17 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ethereum/EthTxData.java
> +public record EthTxData(
I didn't think about this. I just assumed that since we already have java-sdk as a dependency, we should only use it. And since there was no proper data structure for all 3 transaction types, I decided to copy the code from services.

Anyway, I tested with web3j to create raw ethereum transactions, and it is working perfectly fine, so I guess we can remove them.
If you prefer, I can do it in this PR, or we can create a new issue to do it afterward?

2024-05-27 14:17 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ethereum/EthTxData.java
> +    public boolean equals(final Object other) {
Removed

2024-05-27 14:23 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +                null,
I removed the raw data.
r,v,s are initially empty, but later are used to hold signature data.

2024-05-27 14:23 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
> +  @critical @release @acceptance
Done

2024-05-27 14:26 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        TransactionRecord transactionRecord = getTransactionRecord(response.getTransactionId());
I get the same error too, but when I tried with MAINNET chain id on integration environment it is working. 
Also I tested against TESTNET and PREVIEWNET and it is passing.

2024-05-27 14:27 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        // FUTURE - construct bytecode with constructor arguments
Removed

2024-05-27 14:27 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +import static org.junit.jupiter.api.Assertions.*;
Done

2024-05-27 16:53 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthereumFeature.java
> +        mirrorTransaction = finalizeHollowAccount ? transactions.get(1) : transactions.get(0);
Done

2024-05-27 23:06 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        TransactionRecord transactionRecord = getTransactionRecord(response.getTransactionId());
Maybe it's an environment issue and integration's chainId is set incorrectly. I will check with ops team tomorrow.

2024-05-28 00:25 UTC, steven-sheehy approved these changes
LGTM

2024-05-28 00:25 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ethereum/EthTxData.java
> +public record EthTxData(
Sure, can do in a follow up if you prefer

2024-05-28 14:06 UTC, JivkoKelchev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/BaseContractFeature.java
> +public class BaseContractFeature extends AbstractFeature {
Fixed

2024-05-28 22:37 UTC, steven-sheehy approved these changes
LGTM

2024-05-28 22:40 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ethereum/EthTxData.java
> +public record EthTxData(
Opened https://github.com/hashgraph/hedera-mirror-node/issues/8392 to track

2024-05-28 22:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/EthereumClient.java
> +        TransactionRecord transactionRecord = getTransactionRecord(response.getTransactionId());
Devops is working on fixing integration. Until then, we can't merge this unfortunately.

2024-05-29 22:41 UTC, merged