Add HIP-904 Frictionless Airdrops design
hashgraph/hedera-mirror-node pull request #8127
Opened 2024-04-18 18:23 UTC by edwin-greene

**Description**:
Adds the design doc for HIP-904 Frictionless Airdrops

**Related issue(s)**:

Fixes #8081 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-18 18:25 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Ingest `TokenCancelAirdrop` and `TokenClaimAirdrop` transactions and remove entries from the database
Instead of deletion, we could follow the model for entity, adding a deleted flag, and then adding a prune method to clean up deleted pending airdrops.

2024-04-18 18:25 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
Since there is no consensus_timestamp, should we order on `token.id`?

2024-04-18 19:39 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Ingest `TokenCancelAirdrop` and `TokenClaimAirdrop` transactions and remove entries from the database
After a conversation with Steven, will update this to not delete. Putting the PR into draft while I'm making those updates.

2024-04-18 21:56 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +
The lifecycle of a pending airdrop always ends in either `cancel` or `claim`. Over time the number of non-pending airdrops will constantly increase.

As the rest api currently has no need for information about non-pending airdrops, the queries involved may eventually have performance problems as the bulk of the table will progressively be dominated by non-pending airdrops. To address this we may want to have a separate table for resolved airdrops, such that when an airdrop is canceled or claimed it is moved from the pending airdrops table to a resolved airdrops table.

2024-04-18 22:23 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +
We can also consider adding deleted=false condition to every airdrop index to reduce the index size.

2024-04-19 14:13 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
This treats the `TokenAirdrop` as a CryptoTransfer, with similar handling - just updating the balance/balanceTimestamp. But the "source" of a transfer, whether it was a normal transfer or a TokenAirdrop, is not persisted. So perhaps we should add a column to the token_transfer table that indicates the source?

2024-04-19 15:04 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +create type airdrop_resolution_state as enum ('PENDING', 'CANCEL', 'CLAIM');
is this directly from HIP / proposed proto files? Shouldn't we use `CANCELLED` / `CLAIMED`  to describe states?

2024-04-19 20:21 UTC, xin-hedera requested changes

2024-04-19 20:21 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +    token_id            bigint                   not null
shouldn't there be a `sender_id`?

2024-04-19 20:21 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +);
How do we update the table when a pending airdrop becomes either cancelled or claimed? We don't have a unique index, it's going to be slow at least.

Example is, account `A` airdrops NFT `N-1` and `N-2` to account `B`, when account `B` claims them, we need an index to update the state efficiently.

This can extend beyond past already finalized airdrops since it's perfectly fine for the same token being airdopped again after the previous one is cancelled / claimed.

2024-04-19 20:21 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
I don't think we need both `onTokenAirdrop` and `onTokenPendingAirdrop`

immediately succeeded  token transfers from a `TokenAirdrop` transaction should be reflected in the transaction record's token transfer list and `EntityRecordItemListener` already handles it, however we may have to check closely if any logic needs to be updated, especially for approved transfers if any.

2024-04-19 20:21 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add `TokenPendingAirdropTransactionHandler`
There is no `TokenPendingAirdropTransaction`

2024-04-22 14:30 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +);
update: aren't we supposed to have a history table as well? For the index, I think we need a unique index to make `on conflict ... do ...` work. There is still issue when updating fungible token airdrops as we don't know the exact amount, at least for `TokenCancelAirdrop` transaction

2024-04-22 14:32 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
update: I don't think we should allow approved token transfers in `TokenAirdrop` transaction, nor did the HIP intend to allow it. However, we need to amend the HIP to call it out explicitly.

2024-04-23 13:06 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +);
these are the changes needed to make upsert work with the table

- rename `account_id` to `receiver_account_id`
- add a not null bigint column `sender_account_id`
- create a unique index on `(sender_account_id, receiver_account_id, token_id, serial_number)`

We'll keep both `amount` and `serial_number`.

For fungible token, `serial_number` will be always `NULL`. That way, when we do update, on conflict ... update ... will work.

In addition, I'm not sure about how useful `pay_acount_id` is, we definitely should not create an index including the column. The payer account of the transactions which updating the same airdrop can change over the time, e.g., obviously, in the simplest use case, `TokenAirdrop` and `TokenClaimAirdrop` should have different payer account id.

2024-04-23 17:03 UTC, jascks commented on docs/design/frictionless-airdrops.md
> +`/api/v1/accounts/{senderIdOrEvmAddress}/airdrops/outstanding`
Should we just use `{idOrAliasOrEvmAddress}` here. We can say it's the sender's ID in the docs. Is an account alias valid for this API?

2024-04-23 17:10 UTC, jascks commented on docs/design/frictionless-airdrops.md
> +`/api/v1/accounts/{senderIdOrEvmAddress}/airdrops/outstanding`
I was a little confused about the difference between _outstanding_ and _pending_, but it looks like it is really used in the URI path to indicate whether the provided account ID path parameter is that of the sender or the receiver.

We just added the NFT allowances API that utilizes the query parameter `ownerQueryParam` to do something similar regarding the owner and spender. I've not done a full survey of the existing API endpoints, but this is inconsistent.

2024-04-23 17:54 UTC, jascks commented on docs/design/frictionless-airdrops.md
> +- Add `TokenPendingAirdropTransactionHandler`
True, but it looks like `TokenAirdropTransactionHandler` is going to have to check the transaction record and process and `PendingAirdropRecord` to add any pending airdrops resulting from the transaction.

In addition, we need to note the comment in `TokenAirdropTransactionBody`:
```
 * If an airdrop would create a pending airdrop for a fungible/common token, and a pending airdrop
 * for the same sender, receiver, and token already exists, the existing pending airdrop
 * SHALL be updated to add the new amount to the existing airdrop, rather than creating a new
 * pending airdrop.
 ```

2024-04-23 18:16 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +create type airdrop_resolution_state as enum ('PENDING', 'CANCEL', 'CLAIM');
Sounds good I have updated them.

2024-04-23 18:16 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +create table if not exists token_pending_airdrop
Got it, fixed.

2024-04-23 18:17 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +    resolution_state    airdrop_resolution_state not null default 'PENDING',
Sounds good I have updated the name to `state`.

2024-04-23 18:17 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +    token_id            bigint                   not null
Thanks, I have updated it to add the `sender_id`.

2024-04-23 18:18 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +);
Thanks I have updated it according to these suggestions. Do we want the index of the history table to be just on timestamp range?

2024-04-23 18:20 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
For immediately successful token transfers, don't we need a way to distinguish them as "airdropped" vs normal token transfers?

2024-04-23 18:25 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +create type airdrop_resolution_state as enum ('PENDING', 'CANCEL', 'CLAIM');
Sounds good, I have updated it to be named `airdrop_state`.

2024-04-23 19:30 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
It may be useful, but the HIP specified the rest api specifics and I think additional changes would need to go through the review process

2024-04-23 20:17 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
I don't see the importance to mark it as being airdropped, it in fact looks more like a normal token transfer as the same can be done by a `CryptoTransfer` transaction when the receiver already has the corresponding token association or available auto token association slot.

2024-04-23 20:21 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +`/api/v1/accounts/{senderIdOrEvmAddress}/airdrops/outstanding`
I believe treating the path variable as receiver account id makes more sense as the most common query would be as a receiver, what my current airdrops are.

I'm sure we'll get requests to show airdrops by sender from users. However, as of now, we can limit it to receiver while leave it open for extension.

2024-04-23 21:47 UTC, jascks commented on docs/design/frictionless-airdrops.md
> +`/api/v1/accounts/{senderIdOrEvmAddress}/airdrops/outstanding`
I see, so later we could add something like, say, `senderQueryParam`, and default to `false`. And when `true`, query by sender.

2024-04-24 14:00 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +);
not sure about the index for the history table. potentially web3 may read the table for historical state.

2024-04-24 14:01 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add an `TokenClaimAirdrop` domain object which contains the fields `receiverAccountId`, `senderAccountId`, `serialNumber` and `tokenId`.
anything updating the `token_airdrop` table should reuse the same `TokenAirdrop` domain class

2024-04-24 14:03 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add an `TokenReject` domain object which contains the fields `receiverAccountId`, `serialNumber` and `tokenId`.
why do we need a `TokenReject` domain object? `TokenReject` transaction's effect is externalized as token transfer list in the transaction record, that is, any such rejected token is sent from the transaction payer to the token treasury.

2024-04-24 14:06 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenReject` which will be similar to `onCryptoTransfer` except the balance will be zero. Does not affect the `token_airdrop` table.
"balance will be zero" is only true for rejected fungible tokens. For NFTs, token reject can only send back 1 serial per `TokenReference` rejection in the transaction body so it would not necessarily drop NFT balance to 0.

2024-04-24 21:47 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenReject` which will be similar to `onCryptoTransfer` except the balance will be zero. Does not affect the `token_airdrop` table.
Thanks I have removed `onTokenReject`

2024-04-24 21:48 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add an `TokenReject` domain object which contains the fields `receiverAccountId`, `serialNumber` and `tokenId`.
I see, I have updated the design and removed the domain object for `TokenReject`

2024-04-24 21:48 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add an `TokenClaimAirdrop` domain object which contains the fields `receiverAccountId`, `senderAccountId`, `serialNumber` and `tokenId`.
Thanks I have updated the design accordingly.

2024-04-24 22:22 UTC, xin-hedera requested changes

2024-04-24 22:22 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- Add an `TokenClaimAirdrop` domain object with the same fields as the schema.
I assume you meant `domain class`, I don't see the benefit of adding different domain classes per transaction type, and it will make implementation to unnecessarily cast / convert a `TokenCancelAirdrop` / `TokenClaimAirdrop` to `TokenAirdrop` domain object, then apply the merge logic, and finally go into the upsert SQL to update `token_airdrop` / `token_airdop_hisitory` table

Instead we should just have a `TokenAirdrop` domain class

- for `TokenCancelAirdrop`, it fills in the fields in the unique index, the lower timestamp, and set the state to `cancelled`, then call `onTokenAirdrop` or `onCancelAirdrop` if you like that approach more
- for `TokenClaimAirdrop`, similar to above, only difference is state is set to `claimed`

2024-04-24 22:29 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- `token.id` - The token ID this airdrop is associated with. Supports `eq`, `gt`, `gte`, `lt`, and `lte` operators. Only one occurrence is allowed.
just a comment, so now we have an endpoint with 3 pagination params? To add to the complexity, for fungible tokens, serial number is `null`...

2024-04-24 22:42 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- `token.id` - The token ID this airdrop is associated with. Supports `eq`, `gt`, `gte`, `lt`, and `lte` operators. Only one occurrence is allowed.
perhaps I misunderstood it if we only want to support `eq` operator for `receiver.id`, if so, need to call it out.

2024-04-24 23:51 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
> update: I don't think we should allow approved token transfers in TokenAirdrop transaction, nor did the HIP intend to allow it.

TokenAirdrop transaction will support the transferring of tokens from allowance.

2024-04-24 23:51 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- Add `onTokenAirdrop` which will be similar to `onCryptoTransfer`.
> For immediately successful token transfers, don't we need a way to distinguish them as "airdropped" vs normal token transfers?

No need for this a the ledger level

2024-04-25 14:36 UTC, mgoelswirlds commented on docs/design/frictionless-airdrops.md
> +- `token.id` - The token ID this airdrop is associated with. Supports `eq`, `gt`, `gte`, `lt`, and `lte` operators. Only one occurrence is allowed.
So depending on the decision of what the path parameter at this stage would be the query param would change to sender right? also would that also support only eq?

2024-04-25 20:30 UTC, steven-sheehy requested changes

2024-04-25 20:30 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- Add `onClaimAirdrop` to handle setting the `state` to `CLAIMED`. Updates the `token_airdrop` table and the `token_airdrop_history` table.
These two should go away. There's just one onTokenAirdrop with different states passed in.

2024-04-26 19:47 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists for a fungible token in the `PENDING` state, an entry should be made in the `token_airdrop_history` table (just as with a change
it should be replaced, like token account association

2024-04-26 20:45 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists for a fungible token in the `PENDING` state, an entry should be made in the `token_airdrop_history` table (just as with a change
The way I understand it thus far for fungible tokens is that when the upsert occurs, if the existing entry is in the `PENDING` state, then the amount of the existing entry and the new airdrop should be summed and a history table row should be generated (with the amount from the first entry and timestamp range close off). 

If the existing entry is in any other state, then the amount should not be summed and a history table row should be generated in the same manner.

2024-04-26 21:42 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add an `TokenClaimAirdrop` domain object with the same fields as the schema.
Thanks I have removed them

2024-04-26 21:43 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `token.id` - The token ID this airdrop is associated with. Supports `eq`, `gt`, `gte`, `lt`, and `lte` operators. Only one occurrence is allowed.
Thanks I have added eq and the other operators, the HIP did not specify so I am unsure if we would like to just support eq or match the others

2024-04-26 21:43 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Update Web3 `CryptoOpsUsage` and `SyntheticTxnFactory` to handle `-1` values for `maxAutomaticTokenAssociations`.
Thanks I have updated it with that specification

2024-04-26 21:44 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add the new endpoints to Java REST.
Got it I have fixed this

2024-04-26 21:44 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add the new endpoints to Java REST.
Thanks I have added a sentence of explanation

2024-04-26 21:45 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +#### List of outstanding airdrops sent by senderIdOrEvmAddress which have not been claimed by recipients
Thanks I have added some more details here.

2024-04-26 21:45 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +### WEB3
Got it, this is fixed.

2024-04-26 21:46 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +create index if not exists token__airdrop on token_airdrop (sender_account_id, receiver_account_id, token_id, serial_number);
Thanks I have added another index, please double check that it looks correct

2024-04-26 21:46 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Add `onClaimAirdrop` to handle setting the `state` to `CLAIMED`. Updates the `token_airdrop` table and the `token_airdrop_history` table.
Got it I have removed them.

2024-04-26 22:10 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists for a fungible token in the `PENDING` state, an entry should be made in the `token_airdrop_history` table (just as with a change
My question was to spur changes to the document, not answering in comments to a PR.

2024-04-27 00:24 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
Each product has some flexibility to improve the design.
The HIP is the first high level design. Design docs like this are certainly where if a param is missing it should be added and yes we can go back and update the HIP based on implementation.
So far as the overall goal and design of the HIP isn't changes there's some wiggle room.

I believe in this case the transaction consensus timestamp would be useful to capture and will likely be one criteria for which wallets and explorer will use to sort the list by.

2024-04-29 18:23 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
Thanks, sounds good I have added `consensus_timestamp` to the returned results.

2024-04-29 18:23 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +
Got it, I have added that section

2024-04-29 18:26 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
Please revert this change. The payload structure is defined in the HIP and agreed upon by the committee and council. The timestamp range allows us the flexibility of adding a timestamp parameter in the future.

2024-04-29 18:29 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
Actually, I spoke too soon. The HIP doesn't have any timestamp. We can add the field but add as `timestamp: {from: 1, to: null}` to be consistent. Need to also update the HIP.

2024-05-06 15:55 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `token_id` in the response. Can be `asc` or `desc` with a default of `asc`.
Thanks I have updated the timestamp part of the response. If it looks good as I have it, I will open a PR to add it to the HIP.

2024-05-06 15:57 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +## Non-Functional Requirements
I have added some detail to the Java Rest section to include consideration of performance on Citus. Do you think that is sufficient, or is there something more we should look into regarding the design of the indexes in consideration of the Citus partitioning?

2024-05-06 19:34 UTC, steven-sheehy requested changes

2024-05-06 19:34 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `consensus_timestamp` in the response. Can be `asc` or `desc` with a default of `asc`.
The sort order is not by timestamp, but by the multi-column index it's using. And this depends upon whether it's pending or outstanding.

2024-05-06 19:34 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- Reject the set of airdrops and verify that the account no longer has a balance of the fungible token and does not own the nft.
You can't reject them since they never went to pending and were directly transferred since they're previously associated. So we should add another scenario where we send an airdrop and sender rejects.

2024-05-06 19:34 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- Claim the airdrops and verify that they are no longer listed in the two REST APIs.
You should also verify they are listed in other APIs like `/accounts/{id}/nfts`, `/accounts/{id}/tokens`, and `/tokens/{id}/nfts/{serial}`.

Same comment for other scenarios where the transfer occurs.

2024-05-06 19:34 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `consensus_timestamp` in the response. Can be `asc` or `desc` with a default of `asc`.
Same comment

2024-05-06 20:30 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `consensus_timestamp` in the response. Can be `asc` or `desc` with a default of `asc`.
Thanks for catching that, I have corrected the sorting details.

2024-05-06 20:30 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- `order` - The direction to sort the items by `consensus_timestamp` in the response. Can be `asc` or `desc` with a default of `asc`.
Got it this is now fixed.

2024-05-06 20:31 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Claim the airdrops and verify that they are no longer listed in the two REST APIs.
Great idea, I have added those endpoints to the verification for each of the different steps.

2024-05-06 20:34 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Reject the set of airdrops and verify that the account no longer has a balance of the fungible token and does not own the nft.
For tokens in `PENDING` state, my current understanding is that the receiver can only claim them and that they cannot reject them from that state. For tokens that the receiver already owns, they may return them to the token treasury with token reject.

2024-05-06 23:04 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- Reject the set of airdrops and verify that the account no longer has a balance of the fungible token and does not own the nft.
> For tokens in PENDING state

For the scenario I commented on, I'm pretty sure it never goes to PENDING state. Since they're already associated it directly gets transferred.

2024-05-07 00:05 UTC, xin-hedera commented on docs/design/frictionless-airdrops.md
> +create index if not exists token_airdrop__sender_id on token_airdrop (sender_account_id, receiver_account_id, token_id, serial_number);
This needs to be a unique index to make upset on conflict work

2024-05-07 01:42 UTC, Nana-EC requested changes
Looking good.
Some suggestions for consideration and clarity.

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- Enhance Web3 APIs with Pending Airdrop information
Note. The HIP calls out smart contract functions that will expose the HAPI logic.
Mirror node will not have to write much code to support it but it will have to add test coverage to ensure contracts/call supports the call and estimation flows.
We can leave that part for a design doc update in the future as HAPI features will be prioritizes before system contract implementation.
Feel free to note this in the design doc if valuable

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the st
```suggestion
- If a `TokenAirdrop` transaction occurs when an entry already exists i.e matching sender, receiver, token_id and serial_number (if an NFT), then the existing entry should be moved into the `token_airdrop_history` table. If the existing entry is a fungible token in the state of `PENDING` then the new entry should be updated with `amount` set to the sum of the existing amount and the new amount. If the existing entry is in any other state, then the `amount` should be set to the amount of the new entry. Updates to NFT tokens that are `PENDING` will update the timestamp range and generate a history row.
```

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the st
Every update other than PENDING for a fungible token should not see an amount change since you either claim or cancel all fungible tokens. So the amount should not change
```suggestion
- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the state of `PENDING` then the new entry should be updated with `amount` set to the sum of the existing amount and the new amount. Updates to NFT tokens that are `PENDING` will update the timestamp range and generate a history row.
```

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the st
Is this not covered by the first sentence? If so remove it. If you want to clarify something else it needs more details since you already established a history row.
```suggestion
- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the state of `PENDING` then the new entry should be updated with `amount` set to the sum of the existing amount and the new amount. If the existing entry is in any other state, then the `amount` should be set to the amount of the new entry. 
```

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +
So I'm not clear that there's a need to ask "Show me the Claimed or Cancelled airdrops".
if there is i'd imagine querying for transactions of those types would be better than hitting the airdrop API.
In which case another consideration might be moving claimed and cancelled airdrops to the history row only. No need to have them in `token_airdrop`, this should reduce the bloat.

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +`/api/v1/accounts/{senderIdOrEvmAddress}/airdrops/outstanding`
The goal of this API is to see for a given address what outstanding (not claimed or cancelled) airdrops they have.
So the `/airdrops/outstanding` path should always be in the context of the sender

2024-05-07 01:42 UTC, Nana-EC commented on docs/design/frictionless-airdrops.md
> +- Cancel the pending airdrops and verify that they are no longer listed by the two REST APIs.
Can add that the sender still owns the tokens and the receiver does not.

2024-05-07 21:42 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- Cancel the pending airdrops and verify that they are no longer listed by the two REST APIs.
Thanks I have added that as a verification step.

2024-05-07 21:43 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the st
I have updated this to separate the behavior between nft and fungible tokens, it should be easier to read and include these clarifications.

2024-05-07 21:43 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the st
Thanks this sentence has been reworked into two.

2024-05-07 21:43 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +- If a `TokenAirdrop` transaction occurs when an entry already exists then the existing entry should be moved in the `token_airdrop_history` table. If the existing entry is a fungible token in the st
Thanks this sentence has been reworked into two.

2024-05-07 21:44 UTC, edwin-greene commented on docs/design/frictionless-airdrops.md
> +create index if not exists token_airdrop__sender_id on token_airdrop (sender_account_id, receiver_account_id, token_id, serial_number);
Got it I have updated it to have the `unique` keyword

2024-05-07 21:48 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- Reject the set of airdrops and verify that the account no longer has a balance of the fungible token and does not own the nft.
That doesn't make sense either. Once they're claimed they are also transferred. The token reject transaction is for the sender to cancel pending airdrops that have not been claimed or transferred.

2024-05-08 14:46 UTC, steven-sheehy commented on docs/design/frictionless-airdrops.md
> +- Reject the tokens that were just claimed and verify that related endpoints for the account (`/accounts/{id}/nfts`, `/accounts/{id}/tokens` and `/tokens/{id}/nfts/{serial}`) do not show the account
You can't reject tokens that are already claimed. So you'll need to do another `Send a fungible and nft airdrop to an account that has not been associated` setup before rejecting.

2024-05-08 18:41 UTC, steven-sheehy approved these changes
LGTM

2024-05-08 18:44 UTC, xin-hedera approved these changes
LGTM

2024-05-09 00:19 UTC, Nana-EC approved these changes
LG

2024-05-09 13:50 UTC, merged