7855 research faster postgresql to citus migration approach
hashgraph/hedera-mirror-node pull request #8134
Opened 2024-04-19 06:00 UTC by jnels124

**Description**:
* add ability to execute migrations in batches
* add ability to restart migration
* use direct pipe instead of download/upload of csv
* add config option to parallelize batch copies

**Related issue(s)**:

Fixes #7855 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-23 18:59 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +  cat >querySource.sh <<EOF
Unable to get the querySource function to be available via call from `FROM program`

2024-04-23 19:01 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +    where="where consensus_timestamp_end \<= ${MAX_TIMESTAMP}"
not indexed but table is small

2024-04-23 19:03 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +  local stats=$(PGPASSWORD="${SOURCE_DB_PASSWORD}" psql -q --csv -t -h "${SOURCE_DB_HOST}" -d "${SOURCE_DB_NAME}" -p "${SOURCE_DB_PORT}" -U "${SOURCE_DB_USER}" -c "${query}")
unable to get `querySource` function to work correctly here. Attempting to asign the result of that call to stats and then redirect to the while doesn't work. It attempts to execute the text as a command. Can use assistance with the 'bashism' here.

2024-04-24 14:56 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +    while (($(echo "${totalPct} >= ${pctPerCursor}" | bc) )); do
correcting this calculation

2024-04-24 22:48 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +  if [[ "${table}" != "topic_message" && "${columns}" =~ $TS_COLUMN_REGEX ]]; then
will remove topic message restriction here before merge

2024-04-24 22:58 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +tablesArray+=("topic_message")
tables query already orders by size and this would be last in the list already. no need to specify here AND add to excluded tables

2024-04-24 23:13 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +export MAX_TIMESTAMP="${MAX_TIMESTAMP:-$(querySource "select max(consensus_end) from record_file;")}"
Should we store this value to a table? If stopped during the synchronous stage of the migration and restarted later we would have tables copying from different points (assuming the source has been ingesting files). Can also document in the readme to set this value if you are restarting the migration. (async tables are un-effected by this as they read from the status table.

2024-04-25 19:21 UTC, steven-sheehy requested changes

2024-04-25 19:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +  local sql="\\copy ${table}(${columns}) FROM PROGRAM 'echo copy \(select ${columns} from ${table} ${where}\) to STDOUT with BINARY|./querySource.sh' WITH BINARY;"
Why the need for querySource.sh? Can we not just run it in psql directly?

2024-04-25 19:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +    the_table                varchar(100),
```suggestion
    table_name                varchar(100),
```

2024-04-25 19:21 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +fi
We should just always create before since we tested that was faster. Plus we'll soon have indexes created in new migrations.

2024-04-25 19:40 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +  local sql="\\copy ${table}(${columns}) FROM PROGRAM 'echo copy \(select ${columns} from ${table} ${where}\) to STDOUT with BINARY|./querySource.sh' WITH BINARY;"
We can probably not have the querySource.sh and instead say from program `psql -h source -c  "copy ... to stdout"`

2024-04-25 19:48 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
> +fi
Left this as an option because it does reduce the active time of the required time of connection between source and target. However not against removing it

2024-04-26 22:24 UTC, steven-sheehy commented on docs/database/README.md
> +   - Disown the process `disown -h %1`. Replace 1 with the correct job id.
Isn't this simpler?

```suggestion
   `./migration.sh 2>&1 > migration.log & disown`
```

2024-04-26 22:24 UTC, steven-sheehy commented on docs/database/README.md
> +   it is recommended to run the script in a way that doesn't require your terminal session to remain open.`:
```suggestion
   it is recommended to run the script in a way that doesn't require your terminal session to remain open: 
```

2024-04-29 14:01 UTC, jnels124 commented on docs/database/README.md
> +   - Disown the process `disown -h %1`. Replace 1 with the correct job id.
Definitely simpler. I will try that out. I am not real familiar with the command and thought this was the simplest way.

2024-04-29 14:09 UTC, jnels124 commented on docs/database/README.md
> +   - Disown the process `disown -h %1`. Replace 1 with the correct job id.
This worked fine. However, I left standard error and standard out as different log files. This version of the migration logs a bit more and it is preferable to make sure any errors are not lost in these logs.

2024-04-29 14:59 UTC, steven-sheehy approved these changes
LGTM

2024-04-29 15:43 UTC, xin-hedera approved these changes
LGTM

2024-04-29 16:50 UTC, merged