7938 integrate rest java layers (#8140)
hashgraph/hedera-mirror-node pull request #8141
Opened 2024-04-19 14:45 UTC by mgoelswirlds

**Description**:
Integrate Nft allowances API with Jooq repository layer

This PR modifies ... in order to support ...
* Calls Jooq findAll() to handle all operators

**Related issue(s)**:

Fixes #7480

**Notes for reviewer**:
Temporarily removes entityId Validation. Will merge changes from main once the [other PR](https://github.com/hashgraph/hedera-mirror-node/pull/8128) is merged.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-19 18:23 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        return repository.findAll(request, id);
Passing the verified Id to the repository layer, since the type has already been verified here. Else there would be another switch in the repository to get the type.

2024-04-19 18:54 UTC, steven-sheehy requested changes

2024-04-19 18:54 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepository.java
> +public interface NftAllowanceRepository {
We should revert this change so that all repositories still extends CrudRepository and custom logic is in a custom repository.

2024-04-19 18:54 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/NftAllowanceServiceTest.java
> +        var accountId = EntityId.of(1000L);
Can move to a static constant

2024-04-19 19:25 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryImpl.java
> +        Direction order = request.getOrder();
nit, for consistency, use `var` for non-primitive types everywhere

2024-04-22 14:26 UTC, xin-hedera commented
can you delete `MismatchedTypeException.java`, it's no long used. believe the reference to the exception class was removed in previous PRs.

2024-04-22 17:51 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomTest.java
> +class NftAllowanceRepositoryCustomTest extends RestJavaIntegrationTest {
perhaps change this to `NftAllowanceRepositoryTest`, then it'll catch the error that `NftAlowanceRepository` doesn't extend `NftAllowanceRepositoryCustom`

2024-04-22 17:52 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomTest.java
> +    private final NftAllowanceRepositoryCustom nftAllowanceRepositoryCustom;
```suggestion
    private final NftAllowanceRepository nftAllowanceRepository;
```

2024-04-22 17:52 UTC, mgoelswirlds commented on .github/workflows/security.yml
> -      - 'main'
Yes merge from main, made many changes. I am reverting them.

2024-04-22 18:11 UTC, jascks commented on .github/workflows/security.yml
> -      - 'main'
Sorry about that. 😄

2024-04-22 19:01 UTC, xin-hedera approved these changes
LGTM

2024-04-22 19:29 UTC, merged