Add missing logics and validations from services p1
hashgraph/hedera-mirror-node pull request #8157
Opened 2024-04-22 11:03 UTC by zhpetkov

**Description**:
AccessorBasedUsages#estimateCryptoTransfer - token multiplier
Add `MirrorNodeEvmProperties` in `AccessorBasedUsages`, `ServiceConfiguration`. Add `feesTransferUsageMultiplier` with default value 380 in `MirrorNodeEvmProperties`. Set token multiplier value from `mirrorNodeEvmProperties` in `AccessorBasedUsages`. Modification in `AccessorBasedUsagesTest`. 

HederaSelfDestructOperationV038 - reasonToHalt missing if statements
Add `contractIsTokenTreasury`, `contractHasAnyBalance`, `contractOwnsNfts` in` HederaEvmStackedWorldStateUpdater`, because they are needed in `reasonToHalt` statements. Add more tests in `HederaSelfDestructOperationV038 `- `rejectsSelfDestructIfTreasury()`, `rejectsSelfDestructIfContractHasAnyTokenBalance()`, `rejectsSelfDestructIfContractHasAnyNfts()`.

AbstractAutoCreationLogic#create - missing analyzeTokenTransferCreations part
Add `tokenAliasMap`, `analyzeTokenTransferCreations` and `reset` in `AbstractAutoCreationLogic`. Add `getTokenAliasMap` in `AutoCreationLogic`. Add needed modifications in `MirrorEvmMessageCallProcessorTest`, `TransferLogicTest`, `SyntheticTxnFactoryTest`, `TransferPrecompileTest`. Add new tests in `AutoCreationLogicTest`. 

**Related issue(s)**:

Fixes #8056 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-04-22 18:21 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +
From what I've seen we probably prefer not to use wildcard imports

2024-04-22 18:23 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    protected final Map<ByteString, Set<Id>> tokenAliasMap = new HashMap<>();
Hmm from what I see this will make the class not stateless, we've have to think if this is super important to be added or we might skip it.

2024-04-23 06:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    protected final Map<ByteString, Set<Id>> tokenAliasMap = new HashMap<>();
Perhaps we can move the map inside `analyzeTokenTransferCreations` and then return it from method. This way it will be local and the class will remain stateless. With this map we can count if we have token transfers or hbar transfers and update the maxAutoAssociations accordingly.

2024-04-23 06:29 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +        final var maxAutoAssociations = tokenAliasMap.getOrDefault(alias, Collections.emptySet()).size();
This value is calculated here but is not used in the `Account` constructor below.

2024-04-23 06:33 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    public void reset() {
We don't need this method. It is used only in tests and the class needs to remain stateless.

2024-04-23 07:13 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +
I replaced them with multiple imports.

2024-04-23 08:10 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +        final var maxAutoAssociations = tokenAliasMap.getOrDefault(alias, Collections.emptySet()).size();
Does `autoAssociationMetadata` correspond to `maxAutoAssociations`?

2024-04-23 08:11 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    public void reset() {
I removed it.

2024-04-23 08:11 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +    protected final Map<ByteString, Set<Id>> tokenAliasMap = new HashMap<>();
I move it to `analyzeTokenTransferCreations`, thanks!

2024-04-24 06:34 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +        final var maxAutoAssociations = tokenAliasMap.getOrDefault(alias, Collections.emptySet()).size();
Not directly - the `autoAssociationMetadata` contains the max automatic associations and the already used automatic associations. You can check in other places in the code how it is defined.

2024-04-24 08:32 UTC, zhpetkov commented
> What is the difference between this pr and #8074

No differences! I merged the main branch into 8056-add-missing-logics-and-validation-part-1 in #8074 and this added 700 new changes and conflicts. I have to close #8074, because after merging the main branch It's difficult to review which are my changes.

2024-04-24 10:09 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +        final var maxAutoAssociations = tokenAliasMap.getOrDefault(alias, Collections.emptySet()).size();
I replaced it!

2024-04-24 12:03 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +                setMaxAutomaticAssociationsTo(0, maxAutoAssociations),
This looks odd. 
```
public static int setMaxAutomaticAssociationsTo(int autoAssociationMetadata, int maxAutomaticAssociations) {
        return (autoAssociationMetadata & ALREADY_USED_AUTOMATIC_ASSOCIATIONS_MASK) | maxAutomaticAssociations;
    }
```
`autoAssociationMetadata` is 0 in this case, so 0 & <whatever> = 0. `maxAutomaticAssociations` will be used in this case so perhaps we can set this value directly in the constructor.
I am surprised that this change did not break any (integration) test which means that probably we don't have one. Could you please check if there is an integration test that makes a transfer of a fungible token or an NFT to a non-existing account?

2024-04-30 16:32 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +                setMaxAutomaticAssociationsTo(0, maxAutoAssociations),
I replaced `setMaxAutomaticAssociationsTo` with `maxAutoAssociations`. The needed integration test is in #8200.

2024-05-03 23:45 UTC, steven-sheehy requested changes
Need to merge and fix DCO

2024-05-03 23:45 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +        final Supplier<Integer> zeroIntegerSupplier = () -> 0;
Could even make them static fields

2024-05-07 10:20 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private int feesTokenTransferUsageMultiplier = 380;
I documented `feesTokenTransferUsageMultiplier` in `docs/configuration.md`.

2024-05-07 10:21 UTC, zhpetkov commented on hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
> +        final Supplier<Integer> zeroIntegerSupplier = () -> 0;
I made suppliers static.

2024-05-07 13:51 UTC, zhpetkov commented
> Need to merge and fix DCO

Merged.

2024-05-07 18:48 UTC, steven-sheehy approved these changes
LGTM

2024-05-07 19:07 UTC, kselveliev approved these changes

2024-05-07 19:08 UTC, merged