HIP-646/657/765: Implement token metadata acceptance tests
hashgraph/hedera-mirror-node pull request #8166
Opened 2024-04-23 21:37 UTC by jascks

**Description**:
This PR is in draft mode and not nearly read for review. 😄 

Acceptance tests and token/mirror client updates to invoke the new HAPI and MAPI functionality recently implement. Test fungible and non-fungible metadata capabilities as well as that "dynamic" NFTs.

**Related issue(s)**:

Fixes #7765

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-26 16:12 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> -    private static final int MAX_SUPPLY = 1;
No used.

2024-04-26 16:12 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private final Map<TokenId, List<IndividualNftInfo>> tokenNftInfoMap = new HashMap<>();
State per NFT is now serial number and metadata last set.

2024-04-26 18:58 UTC, xin-hedera requested changes

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +import static com.esaulpaugh.headlong.util.Strings.EMPTY_BYTE_ARRAY;
better to use `org.apache.commons.lang3.ArrayUtils.EMPTY_BYTE_ARRAY`

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                                EMPTY_BYTE_ARRAY);
```suggestion
                var metadata = tokenNameEnum.createWithMetadata ? initialMetadata : EMTPY_BYTE_ARRAY;
                var metadataKey = tokenNameEnum.createWithMetadata ? initialMetadataKey : null;
                return  new TokenResponse(
                                networkTransactionResponse.getReceipt().tokenId,
                                networkTransactionResponse,
                                metadataKey,
                                metadata);
```

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        log.debug("Create new non-fungible token {}", tokenNameEnum.symbol);
```suggestion
        log.debug("Create new non-fungible token with symbol {}", tokenNameEnum.symbol);
```

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                "Updated NFT metadata on {} NFTs for token {} via {}",
nit, perhaps log all the serial numbers instead of just the number of serials

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                .setAdminKey(publicKey)
why does the transaction updates admin key? Though since it's the same admin key, effectively no-op, still the function is update token metadata key.

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                Hex.encodeHexString(metadataPublicKey.toBytes()),
why does it log the metadataPublicKey object which perhaps already shows the key in one format, then in addition log the key in hex?

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        TokenUpdateTransaction tokenUpdateTransaction = new TokenUpdateTransaction()
nit,
```suggestion
        var tokenUpdateTransaction = new TokenUpdateTransaction()
```

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                .setAdminKey(publicKey)
again, should not `setAdminKey`

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private final Map<TokenId, List<IndividualNftInfo>> tokenNftInfoMap = new HashMap<>();
should name the class just `NftInfo`

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private void assertMetadataKey(TokenInfoMetadataKey tokenInfoMetadataKey, PrivateKey clientMetadataKey) {
we should convert one key to the other then do it with just one `assert` statement

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Given("I update the metadata for serial numbers {int} and {int}")
the values are not serial. numbers, they are indices.

Or perhaps just change `Map<TokenId, List<IndividualNftInfo>> tokenNftInfoMap` to `Map<TokenId, Map<Long, IndividualNftInfo>> tokenNftInfoMap` then the key of the map can be just the serial number

2024-04-26 18:58 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/token/token.feature
> +    And I ensure token has the expected metadata and key
why cant we do `I ensure token has the expected metadata and key` in `I ensure token has the correct properties`?

2024-04-27 15:25 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/token.feature
> +    And I ensure token has the expected metadata and key
`TokenFeature.ensureTokenProperties()` checkouts out token properties via `/tokens/?token.id={tokenId}` and not `/tokens/{tokenId}`. Only in the latter response is the metadata key returned.

2024-04-27 15:27 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Given("I update the metadata for serial numbers {int} and {int}")
I saw your serial number vs indicies comment in the NFT allowances PR. I'll follow whatever phraseology comes from that to be consistent.

2024-04-27 15:41 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +import static com.esaulpaugh.headlong.util.Strings.EMPTY_BYTE_ARRAY;
Done

2024-04-27 15:42 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                                EMPTY_BYTE_ARRAY);
Done

2024-04-27 15:42 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        log.debug("Create new non-fungible token {}", tokenNameEnum.symbol);
Done

2024-04-27 15:42 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                "Updated NFT metadata on {} NFTs for token {} via {}",
Done.  This now looks like:
```
Updated NFT metadata on NFT serial numbers [1] for token 0.0.6400 via 0.0.6399@1714232221.465000000
Updated NFT metadata on NFT serial numbers [1, 2] for token 0.0.6400 via 0.0.6399@1714232229.466000000 
```

2024-04-27 15:42 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                .setAdminKey(publicKey)
Good catch. Bad interpretation of earlier alpha SDK example code I believe. 😄

2024-04-27 15:42 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                .setAdminKey(publicKey)
Done

2024-04-27 15:44 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private final Map<TokenId, List<IndividualNftInfo>> tokenNftInfoMap = new HashMap<>();
Done.

2024-04-27 16:11 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/token.feature
> +    And I ensure token has the expected metadata and key
A couple of reasons. First, there are several times I specifically verify the metadata and key, both in this scenario and the one above. Do I need to check all those other properties as well at those times?

Second, `TokenFeature.ensureTokenProperties()` utilizes `/tokens/?token.id={tokenId}`, which returns the metadata, but not the key, whereas `TokenFeature.ensureTokenInfoProperties()` uses the REST API endpoint `/tokens/{tokenId}` which returns both the metadata in the key. However, decimals is a string rather than a long in, requiring some additional handling (not null, conversion, number format exception?).

This _could_ be combined into a single step, but I'm not sure it is in our best interest.

2024-04-27 18:43 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private void assertMetadataKey(TokenInfoMetadataKey tokenInfoMetadataKey, PrivateKey clientMetadataKey) {
Done

2024-04-29 15:07 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                        metadata);
now realized this class is a bit bizarre, it wraps fields from consensus node transaction record. However the changes here put metadata and metadata key which are not part of the response.

Just raise it up, not a blocker for me

2024-04-29 15:09 UTC, xin-hedera approved these changes
LGTM

2024-05-06 18:07 UTC, jascks commented on .github/workflows/gradle.yml
> +      - "main"
No changes made by me in `workflows`. Spotless...

2024-05-06 18:08 UTC, jascks commented on docs/database/README.md
> +5. Stop the [Importer](/docs/importer/README.md) process.
No changes here. Spotless...

2024-05-07 18:18 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-05-07 23:11 UTC, steven-sheehy commented
Will need another merge from main

2024-05-08 18:50 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-05-20 15:38 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/token.feature
>      Given I successfully create a new unfrozen and granted kyc token
This is a fungible token, and this is to test token metadata functionality of [HIP-646](https://hips.hedera.com/hip/hip-646), which is support for the metadata and metadata key in the existing token create and update transactions.

2024-05-20 15:39 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/token.feature
>      Given I successfully create a new nft with infinite supplyType
This is a non-fungible token (class). Like the fungible token above, [HIP-765](https://hips.hedera.com/hip/hip-765) provides for the same functionality for the non-fungible token class, or collection.

2024-05-20 15:40 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/token/token.feature
>      Then I mint a serial number from the token
Now we have individual NFT serial numbers, and [HIP-657](https://hips.hedera.com/hip/hip-657) adds the new `TokenUpdateNfts` transaction which when signed by the metadata key (same one as defined for the collection above), the individual NFT metadata can be modified. All serials specified in the transaction are updated to the same metadata.

This is done below using a single serial number, and then two serial numbers. The first serial's metadata is updated twice.

2024-05-20 18:19 UTC, steven-sheehy approved these changes
LGTM

2024-05-21 16:54 UTC, xin-hedera approved these changes
LGTM

2024-05-21 16:55 UTC, merged