NFT allowances acceptance tests
hashgraph/hedera-mirror-node pull request #8177
Opened 2024-04-25 19:38 UTC by mgoelswirlds

**Description**:
This PR adds acceptances tests to test out the NFT allowance flow.

This PR modifies
* Adds acceptance tests that creates an allowance and use MAPI to verify the allowance.

**Related issue(s)**:

Fixes #7874

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-04-25 23:31 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        ExpandedAccountId payer = tokenClient.getSdkClient().getExpandedOperatorAccountId();
The understanding here is that the operator will pay for the transfer but the spender will sign the transaction.

2024-04-26 16:24 UTC, mgoelswirlds commented
These acceptance tests take 19hbar to run.

2024-04-26 17:30 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    Then I mint a serial number from the NFT
Yup good point. I guess I missed adding that step.

2024-04-26 17:48 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    private int getIndexOrDefault(Integer index) {
This method is not used according to IDEA.

2024-04-26 18:12 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    private void associateWithToken(ExpandedAccountId accountId, TokenId tokenId) {
Not a request, just an observation:  one day we should consider `AbstractTokenFeature` so that much of this logic can be shared between this class and `TokenFeature`. Or, we could move these ten new public method steps into `TokenFeature`, but that just results in ever growing classes...

The latter is what [I've done](https://github.com/hashgraph/hedera-mirror-node/pull/8166) for token metadata testing. But with the proper foundation, I could break out `TokenMetadataFeature`. 😄

2024-04-26 18:23 UTC, jascks commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        ExpandedAccountId payer = accountClient.getAccount(spenderName);
Given your (github) comment in `transferNfts()`, perhaps name this variable `spender` rather than `payer`, since the spender is not the payer. Also, can use `var` here.

2024-04-26 18:24 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    private void associateWithToken(ExpandedAccountId accountId, TokenId tokenId) {
I agree, I am duplicating methods here, but what to keeps things separate for the future. Creating an Abstract class makes much more sense here.

2024-04-26 19:38 UTC, xin-hedera requested changes

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +        log.info("Deleted allowance for owner {} on {} via {}", owner, tokenId, response.getTransactionId());
also log the spender

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                "/accounts/{accountId}/allowances/nfts?token.id={tokenId}&account.id={ownerId}&owner=false",
```suggestion
                "/accounts/{accountId}/allowances/nfts?token.id={tokenId}&account.id={ownerId}&owner=true",
```

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                "/accounts/{accountId}/allowances/nfts?token.id={tokenId}&account.id={spenderId}&owner=true",
```suggestion
                "/accounts/{accountId}/allowances/nfts?token.id={tokenId}&account.id={spenderId}&owner=false",
```

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCENONFUNGIBLE(
not sure about the problems, but we should try to reuse existing NFTs instead of adding one for a new test case everytime. this is to cut the cost

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +public class NftFeature extends AbstractFeature {
all these should go to `TokenFeature` unless absolutely has to be in a separate class.

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +@nftallowance @allowance @fullsuite
similar comment to the `NftFeature` class, at least this should be placed into `token` folder.

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    Given <spender> transfers serial number 0 to <recipient>
NFT serial starts from 1

```suggestion
    Given <spender> transfers serial number 1 to <recipient>
```

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +      | ALLOWANCENONFUNGIBLE  | BOB  | ALICE     |
can have better alignment here

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        transferNfts(tokenId, tokenSerialNumbers.get(tokenId).get(serialNumberIndex), spender, accountName);
I don't see how this can work, the NFT is owned by the acceptance test operator account (it's the treasury).

Yes spender has a spend all serial allowance, however the `transferNfts` function tries to send the NftId from `spender` to `account` and obviously `spender` doesn't own it at all.

The way it works is construct a crypto transfer transaction to send the NftId from owner (the operator account) to `account`, and set `spender` as the transaction payer as well as sign the transaction using `spender`s private key.

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    @Given("I delete the allowance on NFT {token} for {account}")
for better clarity

```suggestion
    @Given("I delete the allowance on NFT {token} for {spender}")
```

2024-04-26 19:38 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        }
why when `isOwner == true`, we call `getAccountNftAllowanceBySpender` and when it's false, we call `getAccountNftAllowanceByOwner`

2024-04-26 19:44 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    Given <spender> transfers serial number 0 to <recipient>
This is the index in the list of serialNumbers , not the actual serial number.

2024-04-26 19:48 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        }
So the idea was to put the name of the query param in the method name. But that clearly is confusing. So I should just swap the names of the method and keep the path param in the method name.

2024-04-26 19:50 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        }
That is why the log message in the method states that.

2024-04-26 19:57 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    Given <spender> transfers serial number 0 to <recipient>
yes but the wording says it's serial number 0

2024-04-26 20:02 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    @Given("I delete the allowance on NFT {token} for {account}")
This is the parameter type. So If I change it here would need to add separate parameter types for spender , recipient etc. I don't think I should do that here.

2024-04-26 20:07 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCENONFUNGIBLE(
Created this because of the problem similar to `ALLOWANCEFUNGIBLE`. I believe at some point snake case could not be supported and hence creating one without snake case.

2024-04-26 20:13 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +public class NftFeature extends AbstractFeature {
Had created a separate class for clarity purpose and to not overload TokenFeature but can move everything in TokenFeature. Will check the delta.

2024-04-26 20:19 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        transferNfts(tokenId, tokenSerialNumbers.get(tokenId).get(serialNumberIndex), spender, accountName);
checkout `TokenFeature.transferFromAllowance` about how using allowance to transfer a fungible token is done.

2024-04-26 20:20 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    @Given("I delete the allowance on NFT {token} for {account}")
I see.

2024-04-26 20:21 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    Given <spender> transfers serial number 0 to <recipient>
or can just say `transfer a serial number` since it really doesn't matter which serial is transferred

2024-04-26 20:23 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +    @Given("I delete the allowance on NFT {token} for {account}")
then still for clarity, let's say `I delete the allowance on NFT {token} for spender {account}`

2024-04-26 20:24 UTC, jascks commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    Given <spender> transfers serial number 0 to <recipient>
I can update `token.feature` in my PR to use whatever wording is used here to be consistent.

2024-04-26 20:29 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCENONFUNGIBLE(
even `TokenNameEnum.NFT`?

2024-04-26 22:05 UTC, steven-sheehy requested changes

2024-04-26 22:05 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +        assertNotNull(networkTransactionResponse.getTransactionId());
Change to assertj and attempt to chain more assertions together.

2024-04-26 22:05 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/NftFeature.java
> +public class NftFeature extends AbstractFeature {
Agree with Xin, especially since there's so much duplication.

2024-04-26 22:37 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/resources/features/nft/nftAllowance.feature
> +    And the mirror node REST API should return the transaction for token serial number 0
Actually After moving everything to token feature I can reuse a method in TokenFeature which does both.
verifyMirrorNftTransactionsAPIResponses

2024-04-27 00:09 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +                "/accounts/{accountId}/allowances/nfts?token.id={tokenId}&account.id={ownerId}&owner=false",
I have renamed the methods to fix this.

2024-04-27 00:16 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCENONFUNGIBLE(
I had tried using the NFT_DELETABLE , basically something with `TokenFreezeStatus.FreezeNotApplicable` but if its fine to use `TokenFreezeStatus.Unfrozen` TokenNameEnum.NFT works.

2024-04-27 00:16 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        ALLOWANCENONFUNGIBLE(
@steven-sheehy by not using EXAMPLES do you mean hardcoding values in the feature?

2024-04-27 00:21 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
>          // verify initial balance
This is just fixing some SonarLint issues, since I touched this file.

2024-04-27 00:22 UTC, mgoelswirlds commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
> -        assertEquals(Integer.parseInt(balances[1], 16), 990000);
This is just fixing some SonarLint issues, since I touched this file.

2024-04-29 16:01 UTC, steven-sheehy approved these changes
LGTM

2024-04-29 16:04 UTC, xin-hedera approved these changes
LGTM

2024-04-29 22:02 UTC, merged