fix: Add a check so that prng and exchange rate precompiles won't acc…
hashgraph/hedera-mirror-node pull request #8206
Opened 2024-04-30 07:28 UTC by kselveliev

**Description**:
This PR adds check in Prng and Exchange rate precompiles so that they are not able to accept value.
Seems like services added the change only for prng but not for exchange rate so they need to add one more pr 
there for exchange rate.

After this [issue in services ](https://github.com/hashgraph/hedera-services/issues/11218)got fixed, we need to port the changes in mirror node.

Current pitfall of web3 is that even though with the new checks we throw INVALID_FEE_SUBMITED status.
The end result will be CONTRACT_REVERT_EXECUTED. Future work will be a work package to improve error handling logic and return proper statuses.

This PR modifies 
`ExchangeRatePrecompiledContract` added new check to not accept value.
`PrngSystemPrecompiledContract` added new check to not accept value.
 Modified `PrngSystemPrecompiledContractTest` to work with the new changes.
 Modified `ContractCallSystemPrecompileTest`, added new integration tests to check that prng and exchange rate do not 
 accept value, added new functions in solidity files to test that + made a small refactoring of the test class

**Related issue(s)**:

Fixes #7636

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-04-30 08:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/resources/contracts/ExchangeRatePrecompile/ExchangeRatePrecompile.sol
> +    function tinybarsToTinycentsPayable(uint256 tinybars) external returns (uint256 tinycents) {
It is a little confusing that the names of the functions suggest that they are payable, the abi shows that they are not (and the payment is hardcoded) and then the tests suggest again that a payment is made but we pass no value and we need to check the contract in order to understand the flow. Maybe if we pass the payment to the test as value and then the value to the contract function it will be more easier to understand.

2024-04-30 15:45 UTC, kselveliev commented on hedera-mirror-web3/src/test/resources/contracts/ExchangeRatePrecompile/ExchangeRatePrecompile.sol
> +    function tinybarsToTinycentsPayable(uint256 tinybars) external returns (uint256 tinycents) {
Comment addressed. Now in the new cases I'm passing value in the top level call. I've renamed the function names also. Initially I just copied the code from services and did not pay attention to the confusing naming.

2024-05-02 11:31 UTC, bilyana-gospodinova requested changes

2024-05-02 11:31 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java
> +                functionHash, EXCHANGE_RATE_PRECOMPILE_CONTRACT_ADDRESS, ETH_ESTIMATE_GAS, 0L, BlockType.LATEST);
Actually, I meant this 0 value here as well. If in the contract we use `PRECOMPILE_ADDRESS.call{value: msg.value}`, we should not need to pass the value as a parameter to the function (unless we need specifically two different values) and this way we can have only 1 function that will cover the case when we pass value and when we don't. The same can be done for PRNG as well.

2024-05-02 14:00 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java
> +                functionHash, EXCHANGE_RATE_PRECOMPILE_CONTRACT_ADDRESS, ETH_ESTIMATE_GAS, 0L, BlockType.LATEST);
Now I understand. Comment addressed :).

2024-05-02 15:01 UTC, bilyana-gospodinova approved these changes
LGTM

2024-05-03 15:35 UTC, xin-hedera approved these changes
LGTM

2024-05-03 17:18 UTC, merged