test: add gasConsumed tests
hashgraph/hedera-mirror-node pull request #8207
Opened 2024-04-30 11:29 UTC by vtronkov

**Description**:
* Adding gasConsumed tests

**Related issue(s)**:

Fixes https://github.com/hashgraph/hedera-services/issues/12948

**Notes for reviewer**:
* Moving the `verifyGasConsumed` logic into `AbstractEstimateFeature.java` to reuse the logic
* Using the `verifyGasConsumed` to verify the correct gasConsumed

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-05-07 20:41 UTC, steven-sheehy requested changes

2024-05-07 20:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +        verifyGasConsumed(txId, successfulInitByteCode);
Separate out HAPI calls from MAPI calls. So this should step should revert to how it was and a new gas consume step be added.

2024-05-07 20:41 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
> +        var gasConsumed = getGasConsumedByTransactionId(txId);
Instead of passing in the data, you should be able to extract it from the contract result API's `function_parameters`. This would simplify the test cases.

2024-05-09 13:44 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
> +            Optional<String> txId) {}
Done 👍 I'm still getting used to writing those tests.

2024-05-09 13:44 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EthCallFeature.java
> +        verifyGasConsumed(txId, successfulInitByteCode);
Done 👍

2024-05-09 13:45 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
> +        var gasConsumed = getGasConsumedByTransactionId(txId);
I'm not sure if I understand your comment. Are you talking about the data parameter from this method? I'm not sure how can I will be able to extract it if I don't pass it. Sorry, I'm new to the mirror node 😄 

I guess I can move the newly created `gasConsumedSelector` field in `AbstractEstimateFeature` and use that instead of passing it to the method. Is this what you mean?

2024-05-09 16:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
> +        var gasConsumed = getGasConsumedByTransactionId(txId);
The `/api/v1/contracts/results/{transactionId}` [REST API](https://mainnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractResultByTransactionIdOrHash) has the `function_parameters` in its response which is the call selector. You're already calling this API so you could get the gas consumed selector from that instead of storing it and passing it around.

Having the class variable `gasConsumedSelector` is another approach that works as well at the cost of some extra lines to populate for each relevant request. I'm fine with that if you prefer that approach.

2024-05-09 16:29 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
> +  Then the gasConsumed is correct
Should clarify that we're verifying the gas consumed against the mirror node

```suggestion
  Then the mirror node contract results API should return an accurate gas consumed
```

2024-05-10 07:09 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
> +        var gasConsumed = getGasConsumedByTransactionId(txId);
I moved the `gasConsumedSelector` in the abstract class. The `function_parameters` didn't quite worked, not sure why 🤷

2024-05-10 07:10 UTC, vtronkov commented on hedera-mirror-test/src/test/resources/features/contract/eth.feature
> +  Then the gasConsumed is correct
Changed 👍

2024-05-10 20:30 UTC, steven-sheehy approved these changes
LGTM. I'll leave it up to you to merge

2024-05-13 03:09 UTC, vtronkov commented
> LGTM. I'll leave it up to you to merge

Thank you. Since it's branched off `7655-EthereumTransaction-tests` I will wait for it to be merged first and then I will merge this one.

2024-05-29 22:43 UTC, steven-sheehy commented
Needs a merge from main

2024-05-30 14:04 UTC, steven-sheehy requested changes

2024-05-30 14:04 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/contract/ethereum.feature
> +  And the mirror node REST API should return status <httpStatusCode> for the eth contract creation transaction
Think the order should be reversed so that the ethereum transaction is verified first

2024-05-30 14:49 UTC, vtronkov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +        VACATE_ADDRESS("vacateAddress", 0);
Good catch. These were used before the changes from Jivko's PR but not they are not used 👍

2024-05-30 19:48 UTC, steven-sheehy approved these changes
LGTM

2024-05-30 20:18 UTC, merged