Convert AlertManager alerts to Grafana Cloud alerts
hashgraph/hedera-mirror-node pull request #8211
Opened 2024-05-01 17:01 UTC by xin-hedera

**Description**:

This PR converts our custom alert manager alert rules to Grafana Cloud alert rules

- Add the alert rules yaml file exported from Grafana Cloud
- Fix incorrect metric names in custom grpc alert rules

**Related issue(s)**:

Fixes #8109

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-05-02 17:57 UTC, edwin-greene commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +          summary: "{{ $labels.type }} file verification error rate exceeds 5%"
The description says the error rate is above the 10% threshold, but the summary says it exceeds 5%. Should they be the same?

2024-05-02 17:58 UTC, xin-hedera commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +          summary: "{{ $labels.type }} file verification error rate exceeds 5%"
good catch, this is one of the two pre-existing alert rules, I need to work with devops to remove and switch the notification to the new one

2024-05-06 14:44 UTC, edwin-greene approved these changes
Looks good to me

2024-05-07 18:25 UTC, jnels124 submitted a review, later dismissed
LGTM

2024-05-07 19:59 UTC, steven-sheehy requested changes

2024-05-07 19:59 UTC, steven-sheehy commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +            datasourceUid: grafanacloud-prom
Is there a way to templatize the datasource or can we leave it out and let it choose the default? This alert config should potentially be portable to other operators.

2024-05-07 19:59 UTC, steven-sheehy commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +    folder: MirrorNode
We should match the folder structure of the dashboards which has this as `Mirror`.

2024-05-09 14:03 UTC, xin-hedera commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
moved the file

2024-05-09 14:03 UTC, xin-hedera commented on docs/alert-rules/README.md
removed

2024-05-09 14:03 UTC, xin-hedera commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +        title: Preprod - ImporterFileVerificationErrors
these two existing rules are deleted

2024-05-09 14:05 UTC, xin-hedera commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +            datasourceUid: grafanacloud-prom
don't see how to template it. we can try to omit `datasourceUid` and it probably will set to the default data source, however will leave it as is and test it when later we try to figure out how to import

2024-05-09 14:05 UTC, xin-hedera commented on docs/alert-rules/grafana-cloud-alert-rules.yaml
> +    folder: MirrorNode
done

2024-05-09 20:28 UTC, merged