Drafts opcode logger functionality
hashgraph/hedera-mirror-node pull request #8241
Opened 2024-05-07 15:47 UTC by konstantinabl

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-20 08:52 UTC, victor-yanev requested changes
Nice job 🔥, this has been a tough task!

I've left a few suggestions below:

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        ContractCallContext ctx = initialFrame.getContextVariable("ContractCallContext");
Let's use `ContractCallContext.CONTEXT_NAME` here instead of "ContractCallContext"

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +                Optional.of(frame.getCurrentOperation().getName()),
If `frame.getCurrentOperation().getName()` is never going to be `null`, let's just directly use that instead of wrapping it in `Optional`. 

Usually, `Optional<T>` is used in cases where we want to explicitly show that it is possible for this field to be `null` and whoever uses it has is forced to handle the case of an empty optional in order to avoid a `NullPointerException` being thrown. For example, a method that looks up an entity from a database not find a match, in which case it would return `Optional.empty()` instead of `null`.

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        OptionalLong gasCostOptional = operationResult.getGasCost() == 0 ? OptionalLong.empty() : OptionalLong.of(operationResult.getGasCost());
Same for `gasCost`, let's just directly use `long` here instead of wrapping it in `OptionalLong`, unless we have a good reason to (e.g., if we have something special to execute when `gasCost == 0` and we want to force it)

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +                            frame.getWorldUpdater().getAccount(frame.getRecipientAddress()).getUpdatedStorage());
I see that it's possible for `WorldUpdater.getAccount` to return `null` if the account does not exist - let's add a null check here and log a warning in case it happens:

```java
final Address address = frame.getRecipientAddress()
final Account account = frame.getWorldUpdater().getAccount(address);

if (account == null) {
    log.warn("Failed to retrieve storage contents. Account not found in WorldUpdater");
    return Optional.of(new TreeMap<>());
}

return Optional.of(new TreeMap<>(account.getUpdatedStorage()));
```

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +            return Optional.of(new TreeMap<>());
Let's add a warning here for log traceability in case we catch a `ModificationNotAllowedException`:
```java
} catch (final ModificationNotAllowedException e) {
    log.warn(e.getMessage(), e);
    return Optional.of(new TreeMap<>());
}
```

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractActionService.java
> +    List<ContractAction> findContractActionByConsensusTimestamp(Long consensusTimestamp);
We already get enough context that this is called from `ContractActionService`, we can shorten this:
`findContractActionByConsensusTimestamp` -> `findByConsensusTimestamp`.

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractActionServiceImpl.java
> +    }
nit: let's fix the formatting here - add empty lines around the class, field and method declarations.

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +    //TODO: do not import TRACER_TYPE from ProcessorImpl
We can remove this TODO if it's not relevant anymore

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +    }
Let's move this in a separate file `TracerType.java` in the same directory where `OpcodeTracer` and `MirrorOperationTracer` are.

2024-05-20 08:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private List<ContractAction> contractActions;
nit: We can default this to `List.of()`

2024-05-20 08:58 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractActionRepository.java
> +    List<ContractAction> findContractActionByTimestamp(long timestamp);
nit: Same here - we can rename this to `findByConsensusTimestamp` or `findAllByConsensusTimestamp`.

2024-05-30 08:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractActionServiceImpl.java
> +        Assert.isTrue(transactionIdOrHash.isValid(), "Invalid transactionIdOrHash");
Isn't the @Valid annotation doing this check automatically?

2024-05-30 09:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    result = estimateGas(params, ctx);
I think it would be cleaner if we have a dedicated ContractCallDebugService, which would be dedicated only for all existing and future debug related RPC calls. The workflow there is different - we replay an already executed transaction, while in ContractCallService we simulate a hypothetical transaction. So both services would have different responsibilities and needs.

If some components seem to be common for both services, they can be extracted in a parent Service class.

2024-05-30 09:56 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> -                    if (block != BlockType.LATEST) {
In the case of `debug_traceTransaction` we won't have a defined block explicitly. We should find the `record_file` corresponding to the timestamp for the `transactionHash` that is sent as an input, so that the `ContractCallContext` contains proper data.

2024-05-30 09:58 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> -                    if (block != BlockType.LATEST) {
This is already done when constructing the call service parameters, and the block number is passed to the ContractCallService.

2024-05-30 10:00 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    final var ethCallTxnResult = callContract(params, TracerType.OPERATION, ctx);
That's a symptom of why we should split the logic in 2 different services. We shouldn't use any tracing in the case of `eth_call`, `eth_estimateGas`, so that we don't make this operations more CPU and memory intensive.

2024-05-30 10:06 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/TracerType.java
> +    OPERATION
For `OPERATION` we use directly the `json-rpc-relay` implementation, which utilises the /actions endpoint. The REST API in the web3 module should be used only for `OPCODE` tracing. I think we should delete the `OPERATION` type.

2024-05-30 10:10 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    final var ethCallTxnResult = callContract(params, TracerType.OPERATION, ctx);
I agree, but the other operation tracer was used previously as well, we haven’t introduced any changes to the other methods.

Previously, the `MirrorOperationTracer` was injected directly into the processor and now we inject a `Map<TracerType, HederaEvmTracer>` instead, and thats why we need to pass the tracer type here, in order to get the right tracer that we want to use.

If we don’t want to do any tracing in `eth_call` and `eth_estimateGas`, we can create a new `TracerType.NONE` that’s used by default and doesn’t invoke any tracers when processing the call.

What’s your opinion here?

2024-05-30 10:14 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/TracerType.java
> +    OPERATION
https://github.com/hashgraph/hedera-mirror-node/pull/8241#discussion_r1620414264

2024-05-30 10:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/EntityServiceImpl.java
> +    private final EntityRepository entityRepository;
I think we can directly use the `EntityDatabaseAccessor` for the moment and delete this Service definition.

2024-05-30 11:39 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    result = estimateGas(params, ctx);
I agree
Will do.

2024-06-03 13:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                    final var ethCallTxnResult = callContract(params, TracerType.OPERATION, ctx);
We should use `MirrorOperationTracer` for `eth_call` and `eth_estimateGas`, since it enables logging capabilities that can be turned on by a special flag.

I thought that the TRACER type is for the callTracer type that we already have in place. I agree with your approach. 🙌

2024-06-03 13:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractActionServiceImpl.java
> +public class ContractActionServiceImpl implements ContractActionService{
nit: ContractActionService{ -> ContractActionService {

2024-06-03 13:30 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/BaseService.java
> +public class BaseService {
This name is too generic. We should have a given common context for all of its successors.

Probably we can rename it to `BaseService` -> `ContractCallService`
And the existing `ContractCallService` could be renamed to `ContractExecutionService`

2024-06-03 13:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallDebugService.java
> +    private final ContractActionService contractActionService;
If we need `contractActionRepository` only here, I think we can directly use the repository on this service level, instead of wrapping it in a service.

2024-06-04 08:21 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallDebugService.java
> +    private final ContractActionService contractActionService;
Ok, what if another service needs it in the future? I mean its kind of an overkill now, but could be useful in the future

2024-06-04 09:24 UTC, victor-yanev requested changes

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/BaseCallServiceParameters.java
> +    BlockType getBlock();
Let's order these alphabetically (same for the classes that implement this interface).

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/ContractCallDebugServiceParameters.java
> +@Builder
It's used by the `OpcodeController` tests
```suggestion
@Builder(toBuilder = true)
```

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/OpcodesControllerTest.java
> +                                    final ContractDebugService contractExecutionService,
`contractExecutionService` -> `contractDebugService`

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractExecutionServicePrecompileTest.java
> +class ContractExecutionServicePrecompileTest extends ContractCallTestSetup {
No need to rename this (same for the other test files which were renamed). Same reason as above.

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected ContractExecutionService contractExecutionService;
No need to rename this field, it's cluttering the PR with empty changes making it harder to review. 

Just change the type.

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +        }
We can directly update the context inside `OpcodeTracer.finalizeOperation` instead of doing it here. In this way we delegate this to the tracer and we don't need to be doing `instanceof` custom checks.

2024-06-04 09:24 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      public ContractCallService(
```suggestion
    protected ContractCallService(
```

2024-06-04 11:29 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallDebugService.java
> +    private final ContractActionService contractActionService;
changed it.

2024-06-04 12:05 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      }
Won't this create a lot of complexity, since I need some info like _**detail**_ to throw the error or log a warning. I will possibly need to create a method handleError, which should be inherited in each class and pass the details from the parent. While like this, have the callType anyway :?

2024-06-04 12:07 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    protected void updateGasMetric(final ContractCallDebugServiceParameters.CallType callType, final long gasUsed, final int iterations) {
Its a mistake while refactoring

2024-06-04 12:12 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      public ContractCallService(
You suggested it should be abstract
https://github.com/hashgraph/hedera-mirror-node/pull/8241#discussion_r1625623001
So it cannot be abstract and protected at the same time, right. Its a top-level class

2024-06-04 12:14 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      public ContractCallService(
https://github.com/hashgraph/hedera-mirror-node/pull/8241#discussion_r1625623001
You suggested it should be abstract, so it cannot be protected as well, right? Its a top-level class

2024-06-04 18:04 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      public ContractCallService(
An abstract class is a restricted class that cannot be used to create objects (to access it, it must be inherited from another class)

And that’s what we want for our base class, it doesn't make sense to create objects of the base class, we only want to use it as a template for the subclasses.

2024-06-04 19:21 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      public ContractCallService(
my bad, i thought you suggested this change for the class not the constuctor :)

2024-06-05 10:57 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
>      }
```java
    @Override
    protected void validateResult(final HederaEvmTransactionProcessingResult txnResult, final CallServiceParameters.CallType type) {
        try {
            super.validateResult(txnResult, type);
        } catch (MirrorEvmTransactionException e) {
            log.warn("Transaction failed with status: {}, detail: {}, revertReason: {}",
                    getStatusOrDefault(txnResult), e.getDetail(), e.getData());
        }
    }
```

2024-06-05 13:04 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
> +                                                        final ContractCallContext ctx) {
```suggestion
    public HederaEvmTransactionProcessingResult execute(final CallServiceParameters params,
                                                        final long estimatedGas,
                                                        final ContractCallContext ctx) {
```

2024-06-05 13:10 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +import static org.apache.logging.log4j.util.Strings.EMPTY;
Please copy these settings in your IDE to avoid cluttering the PR with changes related to import formatting:

<img width="901" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/161485803/f8da6100-ccc6-49a8-8b85-3bffc8a95f28">

2024-06-05 13:15 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    protected final Store store;
nit: Let's preserve the old order here:

```java
     private final MeterProvider<Counter> gasLimitCounter;
     private final MeterProvider<Counter> gasUsedCounter;
     private final Store store;
     private final MirrorEvmTxProcessor mirrorEvmTxProcessor;
     private final RecordFileService recordFileService;
     private final ThrottleProperties throttleProperties;
     private final Bucket gasLimitBucket;
```

2024-06-05 13:17 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> -    }
nit: same here

2024-06-05 13:17 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            var result = mirrorEvmTxProcessor.execute(params, estimatedGas, params.getTracerType(), ctx);
We already have the tracer type in the params:
```suggestion
            var result = mirrorEvmTxProcessor.execute(params, estimatedGas, ctx);
```

2024-06-05 13:19 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    protected void validateResult(final HederaEvmTransactionProcessingResult txnResult, final ContractExecutionParameters.CallType type) {
nit: use static import for `ContractCallParameters.CallType` and change this to:
```suggestion
    protected void validateResult(final HederaEvmTransactionProcessingResult txnResult, final CallType type) {
```

Same for all other occurrences.

2024-06-05 13:20 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractActionServiceImpl.java
> +public class ContractActionServiceImpl implements ContractActionService {
Remove this

2024-06-05 13:20 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractActionService.java
> +public interface ContractActionService {
Remove this

2024-06-05 13:21 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractExecutionService.java
> +    static final String GAS_USED_METRIC = "hedera.mirror.web3.call.gas.used";
We should have this in our base class already. Please, remove these from here.

2024-06-05 13:39 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +        }
nit: Reminder

2024-06-05 13:40 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected ContractExecutionService contractExecutionService;
nit: reminder

2024-06-10 10:34 UTC, victor-yanev submitted a review, later dismissed

2024-06-10 23:37 UTC, steven-sheehy requested changes

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        return Arrays.asList(stackContents);
Why are we creating an array just to convert it to a list?

```suggestion
        int size = frame.stackSize();
        var stack = new ArrayList<Bytes>(size);

        for (int i = 0; i < size; ++i) {
            stack.add(frame.getStackItem(size - 1 - i));
        }

        return stack;
```

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        return Arrays.asList(memoryContents);
Same comment. Don't use arrays

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +                revertReason.map(Bytes::toString).orElse(null)));
This is brittle and prone to mapping mistakes. Add `@Builder` to Opcode and use builder methods to build. Same for other trace method

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        revertReason.ifPresent(bytes -> log.trace("Revert reason: {}", bytes.toHexString()));
This lines seems pretty pointless

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +                frame.getRevertReason().isPresent() ? frame.getRevertReason() : getRevertReason(contractActions);
See other comment, but another point is even if we somehow need contract actions this doesn't map it to a specific action by index. It returns a random action.

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/ContractExecutionParameters.java
> + * Copyright (C) 2019-2024 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2024 Hedera Hashgraph, LLC
```

2024-06-10 23:37 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/ContractExecutionParameters.java
> +    long value;
nit: Add `private final` even if `@Value` adds it implicitly so it's clear.

2024-06-11 09:32 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractActionRepository.java
> +    List<ContractAction> findAllByConsensusTimestamp(long consensusTimestamp);
IMO findAll makes more sense, since we return a List of ContractActions, not a single one

2024-06-11 10:19 UTC, victor-yanev requested changes
After adding `consensusTimestamp` to the `ContractDebugParameters`, we are not passing it in the `OpcodeService#buildCallServiceParameters` method and as a consequence the `contractActions` list is always empty in the `ContractCallContext`.

Let's add some validations to the `processOpcodeCall` method to catch such issues and any potential bugs in the future.

2024-06-11 10:19 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/ContractDebugParameters.java
> +}
```suggestion
public class ContractDebugParameters implements CallServiceParameters {

     @NotNull
     BlockType block;

     @NotNull
     Bytes callData;

     @NotNull
     CallType callType = CallType.ETH_DEBUG_TRACE_TRANSACTION;

     @Positive
     long consensusTimestamp;

     @PositiveOrZero
     long gas;

     @AssertFalse
     boolean isEstimate = false;

     @AssertFalse
     boolean isStatic = false;

     @NotNull
     Address receiver;

     @NotNull
     HederaEvmAccount sender;

     @NotNull
     TracerType tracerType = TracerType.OPCODE;

     @PositiveOrZero
     long value;
 }
```

2024-06-11 10:19 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractDebugService.java
> +public class ContractDebugService extends ContractCallService {
```suggestion
@CustomLog
@Named
@Validated
public class ContractDebugService extends ContractCallService {
```

2024-06-11 10:19 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractDebugService.java
> +            final ContractDebugParameters params, final OpcodeTracerOptions opcodeTracerOptions) {
```suggestion
            final @Validate ContractDebugParameters params, final OpcodeTracerOptions opcodeTracerOptions) {
```

2024-06-11 10:19 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/OpcodeServiceImpl.java
>                  .callData(getCallData(ethTransaction, contractResult))
```suggestion
                .callData(getCallData(ethTransaction, contractResult))
                .consensusTimestamp(consensusTimestamp)
```

2024-06-11 14:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/ContractDebugParameters.java
> +}
It's quite inefficient and redundant to validate user input twice just because there was a temporary mapping bug in a PR. I think the main problem here is that you are doing integration tests in a separate PR so you're not catching things in this one.

2024-06-11 15:18 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/model/ContractDebugParameters.java
> +}
We are not validating user input here, but it’s more like a validation which checks that the debug service parameters that we have built are valid. 

If the validation fails here, it means that we have a bug in the logic and it’s an early sign that something is not okay. If we remove this validation the bug wont be caught anywhere and the method will silently continue despite receiving invalid input. It’s a good practice to have such checks instead of completely relying on tests to cover all edge cases.

2024-06-17 20:06 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +                frame.getRevertReason().isPresent() ? frame.getRevertReason() : getRevertReason(contractActions);
Fixed this. Since we cannot know on exactly which contract action we are currently just by checking the MessageFrame, I have implemented a counter, similar to actionStack in services, so we know which operation we are executing and can get the correct revertreason from the DB

2024-06-17 20:12 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +    }
Reverted hedera precompile calls are not kept in the message frame, so we are not able to retrieve them. 
Explained how they are retrieved now here -> https://github.com/hashgraph/hedera-mirror-node/pull/8241#discussion_r1643375879

2024-06-18 11:01 UTC, victor-yanev approved these changes
LGTM, left a few nits below:

2024-06-18 11:04 UTC, victor-yanev commented
Please, also make sure that we have covered all of the new logic in the `OpcodeTracerTest` file. (e.g., the logic with the indexing of the contract actions - we can mock several contract actions, with one being a reverting call to HTS -> make sure that we are indexing the correct contract action for the message frame)

2024-06-18 18:24 UTC, steven-sheehy requested changes

2024-06-19 12:23 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        getContext().decrementContractActionsCounter();
I think you migt have been misled by the name of the variable for the counter, namely **_contractActionsCounter_**. We are not counting the contract_actions.index, but as we discussed previously, we need to know the index of the exact contract action that corresponds to our message frame, so we can take the revert reason, since in the frame we don't have revert reason set for Hedera precompiles. Why we can't use the tracePostExecution - because it tracks some additional intermediate frames, which are not added in contract_actions and the counter will not be correct. You can see in services they have a method called pushActionOfIntermediate. In general, we wanted to replicate the behaviour in services, so we have the same counter for the actions and can map one to the current frame. This is the idea of this variable, to track the index we are at currently. 
This is the solution we've come up with, and we have discussed this approach with @IvanKavaldzhiev, as you suggested. I hope my explanation is clear. If you have any further questions, let's discuss them!

2024-06-19 12:23 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private int contractActionsCounter = 0;
Please refer to my comment https://github.com/hashgraph/hedera-mirror-node/pull/8241#discussion_r1646094392

2024-06-19 14:41 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        Optional<Bytes> revertReason = isCallToHederaTokenService(frame) ? getRevertReasonFromContractActions(context.getContractActions()) : frame.getRevertReason();
Addressed this here -> https://github.com/hashgraph/hedera-mirror-node/pull/8241/files#diff-a52bbc27042361685a4dce7f46214370ba30aa442624dd3b6f1fb6063a77efa2R26
Are you okay with this approach?

2024-06-20 10:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        getContext().decrementContractActionsCounter();
`pushActionOfIntermediate` is a concept of the new `EvmActionTracer`, which is part of the `hedera-smart-contract-service` (from mod code). Web3 based its logic on the mono code base and we have copied some code base from there. Even though now services uses the mod code and we are still reusing the mono code - we should align the `OpcodeTracer` logic with the mono code to be consistent.

When we integrate the `hedera-smart-contract-service` into web3, then we can revisit the OpcodeTracer implementation.

2024-06-20 11:15 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        getContext().decrementContractActionsCounter();
I think we should follow the logic for `List<SolidityAction> allActions` inside `HederaTracer`. In this list we always add new sidecars that are then exported to mirror-node. As Steven mentioned, sidecar action's index is always incrementing, so I think we should follow the places where we add new `sidecar` in `allActions` in `HederaTracer` and in mirror-node's `OpcodeTracer` just increment this counter in the same places.

2024-06-20 11:17 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        getContext().decrementContractActionsCounter();
The only time we remove sidecars from `allActions` is removing the so-called `invalid` actions, which I'm not sure if will be applicable for the case of `debug_traceTransaction`, since we skip some business and validation logic for the sake of simulation. This could be further analyzed.

2024-06-21 03:14 UTC, steven-sheehy commented
Some code smells to address

2024-06-21 03:18 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        getContext().decrementContractActionsCounter();
Yes, I was also looking at HederaTracer. Looks like actions are generated in tracePrecompileResult, traceAccountCreationResult, and tracePostExecution. And my other comment was if we have a list of actions (including precompiled actions) we generated then that list provides the counter and we don't need another counter.

2024-06-24 20:27 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        Optional<Bytes> revertReason = isCallToHederaTokenService(frame) ? getRevertReasonFromContractActions(context.getContractActions()) : frame.getRevertReason();
Works for me

2024-06-25 03:18 UTC, steven-sheehy requested changes
Some merge conflicts as well.

2024-06-25 03:18 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessor.java
> +            final CallServiceParameters params, final long estimatedGas, final ContractCallContext context);
Revert the change to this class and its subclass to pass context.

2024-06-25 03:18 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
> +            final ContractCallContext contractCallContext) {
Revert this change. Just call ContractCallContext.get() to retrieve inside execute(). We should try to keep copied service code as similar as possible to upstream.

2024-06-25 11:52 UTC, konstantinabl commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        getContext().decrementContractActionsCounter();
As we discussed we will change this logic in another PR after we merge this PR to main
An issue has been created https://github.com/hashgraph/hedera-mirror-node/issues/8639

2024-06-25 14:46 UTC, steven-sheehy approved these changes
LGTM

2024-06-25 14:49 UTC, merged