Add testnet-citus deployment to testnet-eu cluster
hashgraph/hedera-mirror-node pull request #8257
Opened 2024-05-08 22:09 UTC by xin-hedera

**Description**:

This PR adds testnet-citus deployment to testnet-eu cluster

- Add configs for testnet-citus to testnet-eu cluster
- Temporarily disable testnet-citus ingestion
- Temporarily disable tesnte-citus ingress for grpc, rest, restjava, and web3

**Related issue(s)**:

Relates to #2675 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-08 22:11 UTC, xin-hedera commented on clusters/testnet-eu/testnet-citus/helmrelease.yaml
> +        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_HISTORICALBALANCE_ENABLED: "false"
effectively disable ingestion, `downloader.balance.enabled` defaults to `false`

2024-05-08 22:14 UTC, steven-sheehy reviewed
missing common chart changes and flux-system changes

2024-05-08 22:30 UTC, xin-hedera commented on clusters/testnet-eu/common/sealed-secret.yaml
> +    values.yaml: AgCr4SYx2B0ikUmN7Q2MQ+UKomfk2QZFdUpnFAwv0KY8qlVJb/HlV/m/swYePrny40PIRA70Xr9b5ybjU5Rluo7YkF0HFijh5J70jsLNFpKGIM4tpBCQ97DLukxNvB5dPqpiWYqhO5noK4094iWlTY5CW7xv5KguYMWnznTTgFvfPcn1P5HHAO
add zfs init service account

2024-05-09 00:05 UTC, steven-sheehy requested changes

2024-05-09 00:50 UTC, xin-hedera commented on clusters/testnet-eu/testnet-citus/helmrelease.yaml
> +        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_HISTORICALBALANCE_ENABLED: "false"
I see, will make the change

2024-05-09 14:07 UTC, xin-hedera commented on clusters/testnet-eu/testnet-citus/helmrelease.yaml
> +      version: '0.104.0-rc4'
or we can just apply the migration v1.97.0 on a testnet db clone.

anyways there isn't much data in testnet, so probably just wait till we GA and deploy 0.104.0 to testnet

2024-05-09 14:56 UTC, steven-sheehy approved these changes
LGTM

2024-05-09 15:03 UTC, jnels124 commented on clusters/testnet-eu/common/helmrelease.yaml
> +      init:
we should probably configure the default disk size to be 1000GI and remove the shard override configuration.

2024-05-10 14:59 UTC, jnels124 commented on clusters/testnet-eu/common/helmrelease.yaml
> +      init:
If we go the shard override approach, the correct syntax is below. The staging config is not correct currently.
```
      worker:
        overrides:
          - index: 1
            pods:
              persistentVolume:
                size: 1000Gi
          - index: 2
            pods:
              persistentVolume:
                size: 1000Gi
```

2024-05-10 16:27 UTC, xin-hedera commented on clusters/testnet-eu/common/helmrelease.yaml
> +      init:
switched to set `zfs.worker.initialDiskSize` in the common charts config, and removed the worker override from hedera-mirrorr charts config

2024-05-10 16:39 UTC, jnels124 approved these changes
LGTM

2024-05-13 18:50 UTC, merged