Nft allowances Range additions
hashgraph/hedera-mirror-node pull request #8261
Opened 2024-05-09 15:03 UTC by mgoelswirlds

**Description**:
This PR adds the support for greater and lower bound conditions for query parameters in the request.

This PR modifies 
* The service layer and the repository layer to handle greater and lower bound conditions for query parameters.
* Adds extra parameter validations as per the openapi spec
* Shortcuts invalid ranges

**Related issue(s)**:

Fixes #8176

**Notes for reviewer**:
- This PR will have changes to the next link depending on the Next link PR
- This PR does not add all validations to Controller tests since they are validated in services tests and these take longer to execute.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-09 23:10 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        if (primary == null || token == null || primary.operator() == RangeOperator.EQ) {
Need to have a null check for primary because when we optimize a range for lte == gte , we make it lte, in that case param can be null.

2024-05-09 23:10 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            if (bounds.lower > bounds.upper) {
Returning empty result when range is invalid.

2024-05-09 23:12 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +                request.setOwnerOrSpenderId(List.of(optimizedRangeParam));
When lower bound and upper bound are equal we optimize it to just be lower bound inclusive

2024-05-10 13:38 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +    private Bound getRange(List<EntityIdRangeParameter> ownerOrSpenderIds) {
Should this method, along with `verifyRangeId()`, perhaps `checkOwnerSpenderParamValidity()`, along with the `Bound` record be pushed to the common `Utils` class? They seem generally useful for future API endpoints. The methods are already `static`.

2024-05-10 13:51 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +    private Bound getRange(List<EntityIdRangeParameter> ownerOrSpenderIds) {
You have a good point as to they do not need to be static.I will change that part.
 But since they are very specific to the allowances API , I think it makes sense to keep them local here as they might not be used by any other API.

2024-05-10 14:07 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryTest.java
> +                        .ownerOrSpenderId(
This is a corner case , which does follow the validation rules as per the spec , but eventually it ends up ignoring the `LTE` operator for token.id. 
Is that acceptable?

2024-05-10 14:13 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +    private Bound getRange(List<EntityIdRangeParameter> ownerOrSpenderIds) {
Okay.

2024-05-10 20:14 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceRequest.java
> +    private List<EntityIdRangeParameter> tokenId;
Nit, may be clearer if these were plural now: `ownerOrSpenderIds`, and `tokenIds`

2024-05-10 20:15 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
>          var tokenParam = request.getTokenId();
Nit, these could be clearer as plurals, `primarySortParams` and `tokenParams`

2024-05-10 20:15 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        Bound tokenBounds = getBounds(tokenParam);
Nit these can be `var` instead of `Bound`

2024-05-10 20:16 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +            for (EntityIdRangeParameter param : primarySortParam) {
Nit, can be `var` instead of `EntityIdRangeParameter`

2024-05-10 20:39 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +            for (EntityIdRangeParameter param : primarySortParam) {
Not when setting the value to null though.

2024-05-13 16:12 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +            for (EntityIdRangeParameter param : primarySortParam) {
Sorry @edwin-greene, looking at this again, you are quite correct for the for loop on line 94.

2024-05-13 16:51 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        // No secondary condition if there is no primary parameter bound or no token parameter, or the primary sort
Total nit. Since this was renamed, seems the nomenclature is now middle condition.

```java
// No middle condition if there is no...
```

2024-05-13 17:04 UTC, xin-hedera requested changes

2024-05-13 17:04 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        var accountOperators = verifyRangeId(ownerOrSpenderParams);
make `verifyRangeId` return a record object

`private record Operators(boolean hasEq, boolean hasGtGte, boolean hasLtLte) {};`

then the validations can be easier to read.

2024-05-13 17:08 UTC, xin-hedera commented
How are we going to merge this without the next link fix?

Given the http request from the user, e.g., `/api/v1/200/allowances/nfts?account.id=gt:200&account.id=lt:800&order=asc`, the response may have a next link like `/api/v1/200/allowances/nfts?account.id=gt:200&account.id=lt:800&order=asc&account.id=gt:202`, which violates `max=2` constraint.

Do we ship it and tell users that's a known bug?

2024-05-13 17:15 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +    private static List<RangeOperator> verifyRangeId(List<EntityIdRangeParameter> idParams) {
I'd consider returning `Set<RangeOperator>`  since it does not seem order is important and that `contains()` is invoked on this list of items. This is O(n/2) for a `List` and O(1) for a `Set`. Though, I understand `RangeOperator` has only six possible values and it's unlikely an API client would provide all of those, so the performance difference in reality is not likely to mementous.

2024-05-13 18:55 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +    private Bound getBounds(List<EntityIdRangeParameter> primarySortParam) {
Or create a new data class to pass the query filters from service layer to repo layer, and in the new class, instead of `EntityIdRangeParameters`, use explicit lower / upper bound for ownerOrSpender and tokenId. That can also eliminate the duplicate bound analysis in repository layer.

2024-05-14 01:38 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        var accountOperators = verifyRangeId(ownerOrSpenderParams);
This surely will makes things radable , but I need to know the exact operators and count for certain validations , which would lead me to add all 5 operators to the record.

2024-05-14 14:05 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            }
in addition, for the validation here, there is no difference between lt or lte, same for gt or gte. instead of individual counters, you just need `countLtLte` and `countGtGte`.

2024-05-14 15:04 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            }
I had done that but the place where I face dan issue was for the following validations
`Single occurrence only supported.Requires the presence of an lte or eq account.id query`, here I specifically need to know lte and similarly gte for the other one.

2024-05-14 16:17 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            }
I see. you can add helper functions to the record class

```java
private record Operators(...) {
  public boolean hasGtGte() {
    return hasGt || hasGte;
  }
}
```

2024-05-14 22:00 UTC, steven-sheehy requested changes

2024-05-14 22:00 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        return new Operators(countEq > 0, hasGt, hasGte, hasLt, hasLte);
Again, think this logic would be better served to be encapsulated in `Bound` for reuse and to avoid creating this `Operators`. We should instead calculate an `EnumMap<RangeOperator, Integer>` in the `Bound` constructor that we can add a `boolean hasOperator(RangeOperator.EQ)` helper method to Bound to use for multi-parameter validation.

2024-05-15 00:19 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +            if (bounds.lower > bounds.upper) {
The `/allowances/tokens` API returns an empty response.So keeping it consistent.

2024-05-15 17:45 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        return new Bound(lowerBoundParam, upperBoundParam);
Just to clarify , are you suggesting to change Bound definition to be like
`public record Bound(List<EntityIdRangeParameter> params)`

2024-05-15 17:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        return new Bound(lowerBoundParam, upperBoundParam);
Correct

2024-05-16 14:41 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +        if (ownerOrSpenderId.getLowerBound() != null
To be able to return an empty reponse as in the `allowances/tokens` endpoint , I had to keep this check here. If I move it to Bound I can throw an exception `Invalid range provided` or something, but that will be inconsistent with the other similar API.

2024-05-16 15:13 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +                if (param != null) {
the param will not be null. So adjusted that.

2024-05-20 19:58 UTC, steven-sheehy requested changes

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    }
Don't really need this switch statement or method as a whole. Just put this inline in the for loop:

```java
cardinality.merge(param.operator(), 1, Math::addExact);
```

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        if (params != null) {
switch to fail fast to reduce nesting

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +@Getter
We shouldn't expose cardinality map

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +    }
Can add a generic `Bound.getCardinality(RangeOperator... operators)` or move `getCountLtLte()` to `Bound` and rename to `getLowerCardinality()`.

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
Why does it matter if it's a primary sort field to validate range? It should be for all bounds.

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    private EntityIdRangeParameter upper;
Probably in the future we'll want to make `Bound` work generically for `RangeParameter`

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
> +                && (tokenParams.getLower() != null || tokenParams.getUpper() != null)) {
Add a helper to `Bound` to clean this up:

```java
public boolean isEmpty() {
    return lower == null && upper == null;
}
```

2024-05-20 19:58 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
>      }
These single field validations can be moved into `Bound` helper methods that can be optionally called by various service layers. This allows for reuse and encapsulation.

```java
public void verifyUnsupported(RangeOperator unsupportedOperator) {...}
public void verifySingleOccurrence() {...}
public void verifyEqualOrRange() {...}
```

2024-05-20 21:58 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
This is the scenario for our current API where that is relevant:

```
for a specific owner, given we have (spender, token) pairs

(100, 200)
(100, 201)
(200, 50)


and for the request account.id >= 100 && token.id >= 200 & account.id <=200 & token.id <= 50) 
we should return all 3 rows
if we shortcut on token id, we return nothing, and that is wrong
```

2024-05-21 01:57 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    private EntityIdRangeParameter upper;
Yes. makes sense. Or to have different abstractions of Bound.

2024-05-21 02:46 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
I think you're confusing input validation with rows returned from the db. The scenarios you list are for the latter. For user input, we need to make sure tokenid lower <= upper.

2024-05-21 18:41 UTC, xin-hedera requested changes

2024-05-21 18:41 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        var condition = commonCondition.and(lowerCondition.or(middleCondition).or(upperCondition));
the repository will return incorrect data for such requests

- `/accounts/1001/allowances/nfts?account.id=gte:2001&account.id=lte:2001&token.id=gte:3000`
- `/accounts/1001/allowances/nfts?account.id=gte:2001&account.id=lte:2001&token.id=3000`

For the second, I'm not sure if we should return 400 to indicate for `token.id=` the only allowed operator for `account.id` is =

This also indicates there are missing test coverage.

2024-05-21 18:54 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
for multiple-column pagination, we do concat the values to form a single value to compare and order.

For example, given two `long` columns `A` (primary) and `B`, with values `a` and `b`, concat them `a << 64 | b`.

When we have `A=gt:a1&A=lt:a2&B=gt:b1&B=lt:b2`, where the range`(a1, a2)` contains more than 1 discrete values and `(b1, b2)` is effectively empty, we don't throw an error since for a concatenated value ` (a3 << 64 | b3) > (a1 << 64 | b1`, `b3 > b1` isn't necessarily true.

However, we should add logic to throw error when `(a1, a2)` contains a single value, and `b1 > b2`.

2024-05-23 03:24 UTC, steven-sheehy requested changes

2024-05-23 03:24 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    }
This is an ambiguous error presented to the user. We can refactor it to make it clearer which operator is at fault. We may also consider passing in the query parameter name into the constructor to provide more accurate error messages.

```suggestion
        verifySingleOccurrence(RangeOperator.EQ);
        verifySingleOccurrence(RangeOperator.GT, RangeOperator.GTE);
        verifySingleOccurrence(RangeOperator.LT, RangeOperator.LTE);
    }
    
    private void verifySingleOccurrence(RangeOperator... rangeOperators) {
        if (this.getCardinality(rangeOperators) > 1) {
            throw new IllegalArgumentException("Only one range operator from %s is allowed for the given parameter".formatted(Arrays.toString(rangeOperators));
        }
    }
```

2024-05-23 03:24 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return getLower().value().getId() == getUpper().value().getId();
```suggestion
        return Objects.equals(getLower().value(), getUpper().value());
```

2024-05-23 14:17 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
Xin's scenario still needs to be addressed

2024-05-23 14:58 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
Missed this. WIll add it now.

2024-05-23 15:14 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +                throw new IllegalArgumentException("Invalid range provided");
I would need to add that in the service layer as not everyone is going to have multi column pagination.

2024-05-23 15:19 UTC, xin-hedera requested changes

2024-05-23 15:19 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return Objects.equals(getLower().value(), getUpper().value());
- why `Object.equals` instead of just comparing the primitive long?
- NPE if either lower is null or upper is null
- inconsistency: other places just use instance variable `lower` / `upper`, here it's the getters.

2024-05-23 15:19 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        }
what if there is `account.id=gt:10&account.id=lt:12`? this also means the comment is inaccurate. there seems to be missing test coverage as well.

2024-05-23 15:31 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return Objects.equals(getLower().value(), getUpper().value());
> why Object.equals instead of just comparing the primitive long?

`value()` is `EntityId` so you mean extracting id out of it and comparing? That's violating encapsulation of `EntityId` and doesn't make it compatible if we make `Bound` work with the higher level interface `EntityIdParameter` in the future.

Agree with other points which were the case before switching to `Objects.equals()` as well.

2024-05-23 16:13 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return Objects.equals(getLower().value(), getUpper().value());
Agree however `Bound` is not a generic class,  both `lower` and `upper` are of type `EntityIdRangeParameter`

2024-05-23 16:35 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        }
I have addressed that.

2024-05-23 16:35 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return Objects.equals(getLower().value(), getUpper().value());
Needed to change that part of the code to used adjusted lower and upper bounds

2024-05-23 21:25 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> +        var primaryBounds = request.getOwnerOrSpenderIds();
there are still corner cases for which the logic here would get incorrect nft allowances, I'll see if there's a better way without introducing too much complexity

2024-05-23 21:47 UTC, xin-hedera approved these changes
LGTM. in case of any minor issues, can address in a follow-up PR

2024-05-23 23:58 UTC, steven-sheehy approved these changes
LGTM

2024-05-24 12:27 UTC, merged