Add linkFactory for NftAllowances Java REST API
hashgraph/hedera-mirror-node pull request #8264
Opened 2024-05-09 21:30 UTC by edwin-greene

**Description**:

**Related issue(s)**:

Fixes #7982

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-09 21:38 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +    <T> Links create(T item, ParameterExtractor<T> extractor);
The issue has a `Pageable` parameter here, after going through some iterations I wasn't sure that it was needed.

2024-05-09 21:41 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
> +        assertThat(result.getLinks().getNext()).isEqualTo(next);
When the NFT Allowances Range PR is merged, this test can be expanded to include following the next link. At the moment the next link contains a lower bound and upper bound for the account.id and token.id parameters, which isn't supported by the AllowancesController (until the aforementioned PR is merged).

2024-05-10 00:11 UTC, steven-sheehy requested changes

2024-05-10 00:11 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +            response.links(new Links());
The link factory should handle the if/else internally and return the appropriate links object so that here we just receive the links and set it.

2024-05-10 00:11 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesLinkFactory.java
> +public class AllowancesLinkFactory implements LinkFactory {
I think you misunderstood the intent of the ticket. The ticket was to help make the link generation more generic and reusable so it can be used by topic ID API but this PR actual makes it less generic and reusable. The `LinkFactory` was intending to replace the generic static Utils with a generic bean that could generate links for any endpoint. We should not have endpoint specific link factories.

2024-05-10 00:11 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +    default <T> boolean addQueryParam(
Remove this since it should be in the generic `LinkFactoryImpl`.

2024-05-10 00:11 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +    <T> Links create(T item, ParameterExtractor<T> extractor);
You will need it to make this factory generic for all endpoints.

2024-05-14 17:29 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +    <T> Links create(T item, ParameterExtractor<T> extractor);
Thanks I have updated this to be a generic linkFactory

2024-05-14 17:30 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +            response.links(new Links());
Got it, I have updated the linkFactory to make the determination of empty links rather than the controller

2024-05-14 17:31 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesLinkFactory.java
> +public class AllowancesLinkFactory implements LinkFactory {
Thanks, this has now been updated to be a generic link factory

2024-05-14 17:31 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +    default <T> boolean addQueryParam(
Thanks, this has been moved/refactored.

2024-05-14 23:11 UTC, xin-hedera requested changes

2024-05-14 23:11 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var lastItem = CollectionUtils.lastElement(itemsList);
```suggestion
        var lastItem = Iterables.getLast(items);
```

2024-05-14 23:11 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        if (lastParameterValue == null) {
if it's null (which should not happen at all), all existing values should be added as `k=v` query param to the URL

2024-05-14 23:11 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        }
multiple issues here including the logic I completely can't understand

- why when order=desc, all the existing values from the request URL are added and the value extracted from the last item is just ignored?
- what's special about the string "false" and "true"?
- in the else branch, why the same last value is added multiple times?

I think the idea is for a key `k`,

- if there is value `v` extracted from the last item, when order is descending, the function should remove all `lt` / `lte` values, replace it with `lt` or `lte` `v`, and keep all other existing values; when the order is ascending, apply the opposite logic
- if there is no value extracted, copy all the existing values

2024-05-15 18:26 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var lastItem = CollectionUtils.lastElement(itemsList);
It would be great to remove `StreamSupport`, but the link factory still seems to need a means of getting the size of the items.  If the `limit` is greater than the number of items passed in, the LinkFactory will return an empty link. To get the number of items to compare to the `limit`, it is using `StreamSupport` to convert the iterable to a list.

2024-05-15 18:32 UTC, steven-sheehy requested changes

2024-05-15 18:32 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var lastItem = CollectionUtils.lastElement(itemsList);
Just pass in a List instead of an Iterable

2024-05-16 16:33 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +        Function<T, String> extract(String name);
let's change this to

```suggestion
        String extract(T item, String name);
```

So you don't have to deal with the situation that there is a function to extract parameter `p`, however the extracted value is `null`.

With the new `extract` function, given the item, and parameter name `p`, if it returns `null`, just add all existing values for `p` to the next link.

2024-05-20 21:40 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        if (lastItem == null || limit > itemsList.size() || paramsMap.isEmpty()) {
Thanks I have fixed this.

2024-05-20 21:40 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +                    }
Got it, I have updated this

2024-05-20 21:46 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        addRangeBoundaries(primarySort, secondarySort, extractor, lastItem, builder);
Thanks I have simplified the sorting and the linkFactory no longer has a concept of anything other than a primarySort (to detemine if ASC or DESC) and a lastSort (to determine if inclusive or not). The linkFactory still iterates the sorting to determine if any sorts passed by the `Pageable` have extractable values that were not included in the parameters.

2024-05-20 21:46 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var queryParams = new ArrayList<String>();
Thanks I have updated this.

2024-05-20 21:46 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +    private List<String> addQueryParam(
After some refactoring this method is no longer present.

2024-05-20 21:47 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        if (items == null) {
Thanks I have updated this to check for empty.

2024-05-20 21:47 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var lastItem = CollectionUtils.lastElement(itemsList);
Thanks I have updated this to a List.

2024-05-20 21:50 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        if (lastParameterValue == null) {
This method is no longer present after refactoring, but this should be fixed as indicated in the current version.

2024-05-20 21:50 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        }
Thanks, I have refactored this section to be in line with this feedback.

2024-05-20 21:51 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +    private final HttpServletRequest request;
Got it, I have removed that part.

2024-05-20 21:51 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var lastItem = CollectionUtils.lastElement(itemsList);
Thanks I have made this change.

2024-05-20 21:51 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +        Function<T, String> extract(String name);
Got it I have made this change.

2024-05-20 21:55 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +        }
It seems that the extractor has need of the `paramMap` or at least knowledge of the presence of the `owner=true` query parameter. 

This could be one way of providing the `paramMap` to the extractor and also providing it to the `LinkFactoryImpl`, which could be more performant than calling `RequestContextHolder.getRequestAttributes()` in the LinkFactory.

2024-05-21 00:28 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        if (items == null || items.isEmpty() || pageable.isUnpaged()) {
```suggestion
        if (CollectionUtils.isEmpty(items)) {
```

I don't think we should check `isUnpaged` at all, the contract should be if no next link needed, just don't call `create`

2024-05-21 01:02 UTC, xin-hedera requested changes

2024-05-21 01:02 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +    private record RangeBound(RangeOperator operator, String value) implements RangeParameter<String> {
such logic should reside in the controller

the `isInclusive` flag is used to decide
- if true and order desc, pick `LTE`
- if false and order desc, pick `LT`
- if true and order asc, pick `GTE`
- if false and order asc, pick `GT`

The factory should not further change the value returned by `extractor.extract`

2024-05-21 01:05 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        for (var entry : paramsMap.entrySet()) {
the order of the entries will be random, as a result the order of the `p=v` pairs in the generated next link will be random too.

We may consider sort it, or at least provide an assert utility function in the test cases to ignore the `p=v` order when validating the next url.

2024-05-21 20:11 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
> +        }
This has been removed

2024-05-21 21:21 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        }
Thanks I have made these updates.

2024-05-21 21:23 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        var lastSort = Iterables.getLast(sortOrders, null);
Thanks, I have updated the main logic of the implementation to be similar to this.

2024-05-21 21:27 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +                case ORDER -> builder.queryParam(ORDER, order.name().toLowerCase());
Thanks I have removed this logic.

2024-05-21 21:53 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +    private record RangeBound(RangeOperator operator, String value) implements RangeParameter<String> {
It makes good sense for the extractor alone to be able to determine the value so that nothing else needs to understand the specifics of the value in order to increment or decrement it. 

But it may be that the extractor will need more information to perform the task. Still researching.

2024-05-22 00:35 UTC, xin-hedera requested changes

2024-05-22 00:35 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        builder.queryParam(key, lastValueOperator + ":" + lastValue);
I still have a hard time to understand why we need such complicated logic here. Is there any corner case to handle?

For a pagination param `p`, given

- existing `values` from the request params map
- `order` from `pageable`

All we need to do is,

```
for each value in values
  parse and extract operator from value
  if ((order is asc and operator is gt/gte) or (order is desc and operator is lt/lte)) {
    continue; // essentially skip it since the new bound should come from the extracted value
  }

  add param / value pair to builder
```

So this function should only have `builder`, `entry`, and `order` as the arguments.

2024-05-22 00:35 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +            }
why whether the key exists in `paramsMap` matters?

this part should be just

```
  operator = if order is asc and inclusive then GTE
                     elif order is asc and !inclusive then GT
                     elif order is desc and inclusive then LTE
                     else LT
  add pair (key, operator + ":" +  value) to builder's param map
```

2024-05-22 16:17 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +        boolean isInclusive(String param);
A suggestion Steven had was that we could remove `isInclusive` here. Instead of having it as a method in the interface, we could use the `Sort` inside `Pageable` to determine inclusivity. 

The `Sort` contains a list of sorts, and all but the last sort can be used to indicate `inclusive = true`, while the last sort indicates `inclusive = false`.

2024-05-22 16:43 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +        boolean isInclusive(String param);
That’s feasible however it should be the last is not inclusive and any non-last is inclusive. Special case is if only one, it should be non inclusive.

2024-05-22 18:59 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +        builder.queryParam(key, lastValueOperator + ":" + lastValue);
Got it, I have simplified this logic

2024-05-22 18:59 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java
> +            }
Thanks I have updated this.

2024-05-22 19:51 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
> +                                EntityId.of(allowance2.getTokenId()));
Note: This part of the test verifies that the other issue [#8185](https://github.com/hashgraph/hedera-mirror-node/issues/8185) is fixed by this PR.

2024-05-22 21:20 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeBound.java
> +    }
we should be able to move the common logic to a factory, don't have to make the change in this PR

2024-05-22 21:20 UTC, xin-hedera commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/LinkFactoryTest.java
> +        params.put("limit", new String[] {"1"});
remove `limit` here so we have one test case for when there's no `limit` query param in the request URL

```suggestion
```

2024-05-23 20:43 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactory.java
> +        boolean isInclusive(String param);
At this point, best for a follow up.

2024-05-24 22:09 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-05-24 23:01 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeBound.java
> +    }
still need to address this

2024-05-24 23:09 UTC, steven-sheehy approved these changes

2024-05-25 02:42 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeBound.java
> +    }
changing to factory may affect many other places. however still removed `RangeBound` and just switched to `String.startsWith`

2024-05-25 02:44 UTC, xin-hedera approved these changes
LGTM

2024-05-25 03:19 UTC, steven-sheehy approved these changes

2024-05-25 03:39 UTC, merged