fix slowdown finding token transfers
hashgraph/hedera-mirror-node pull request #8342
Opened 2024-05-21 01:29 UTC by jnels124

**Description**:
* update query to find approved transfers from contract call

**Related issue(s)**:

Fixes #8311

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-21 01:30 UTC, jnels124 commented
Query Plan:
```
QUERY PLAN

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.443..0.444 rows=9 loops=1)
   ->  Distributed Subplan 1523_1
         Subplan Duration: 4.67 ms
         Intermediate Data Size: 939 bytes
         Result destination: Send to 3 nodes, write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=1.580..1.581 rows=9 loops=1)
               Task Count: 1
               Tuple data received from nodes: 633 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 633 bytes
                     Node: host=10.4.6.5 port=7433 dbname=mirror_node
                     ->  Subquery Scan on grouped_token_allowances  (cost=11.21..11.53 rows=1 width=75) (actual time=0.040..0.048 rows=9 loops=1)
                           Filter: ((grouped_token_allowances.amount_granted > 0) AND (grouped_token_allowances.row_number = 1))
                           Rows Removed by Filter: 1
                           ->  WindowAgg  (cost=11.21..11.41 rows=8 width=83) (actual time=0.039..0.046 rows=10 loops=1)
                                 Run Condition: (row_number() OVER (?) <= 1)
                                 ->  Sort  (cost=11.21..11.23 rows=8 width=75) (actual time=0.035..0.036 rows=13 loops=1)
                                       Sort Key: token_allowance.token_id, token_allowance.spender, (lower(token_allowance.timestamp_range)) DESC
                                       Sort Method: quicksort  Memory: 26kB
                                       ->  Result  (cost=0.28..11.09 rows=8 width=75) (actual time=0.015..0.027 rows=13 loops=1)
                                             ->  Append  (cost=0.28..10.99 rows=8 width=67) (actual time=0.014..0.024 rows=13 loops=1)
                                                   ->  Index Scan using token_allowance__pk_102558 on token_allowance_102558 token_allowance  (cost=0.28..6.28 rows=3 width=62) (actual time=0.014..0.017 rows=9 loops=1)
                                                         Index Cond: (owner = 4366156)
                                                         Filter: (lower(timestamp_range) <= '1715894584220147004'::bigint)
                                                         Rows Removed by Filter: 1
                                                   ->  Index Scan using token_allowance_history__owner_spender_token_lo_8aed322d_102574 on token_allowance_history_102574 token_allowance_history  (cost=0.27..4.66 rows=5 width=70) (actual t
ime=0.005..0.006 rows=4 loops=1)
                                                         Index Cond: ((owner = 4366156) AND (lower(timestamp_range) <= '1715894584220147004'::bigint))
                         Planning Time: 0.133 ms
                         Execution Time: 0.075 ms
         Planning Time: 0.000 ms
         Execution Time: 1.595 ms
   ->  Distributed Subplan 1523_2
         Subplan Duration: 24.60 ms
         Intermediate Data Size: 0 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=56) (actual time=24.931..24.932 rows=0 loops=1)
               Task Count: 16
               Tuple data received from nodes: 0 bytes
               Tasks Shown: One of 16
               ->  Task
                     Tuple data received from node: 0 bytes
                     Node: host=10.4.2.5 port=7433 dbname=mirror_node
                     ->  GroupAggregate  (cost=132.33..132.35 rows=1 width=56) (actual time=0.199..0.203 rows=0 loops=1)
                           Group Key: tt.token_id, tt.payer_account_id, tt.consensus_timestamp
                           ->  Sort  (cost=132.33..132.33 rows=1 width=32) (actual time=0.198..0.202 rows=0 loops=1)
                                 Sort Key: tt.token_id, tt.payer_account_id, tt.consensus_timestamp
                                 Sort Method: quicksort  Memory: 25kB
                                 ->  Nested Loop  (cost=0.15..132.32 rows=1 width=32) (actual time=0.178..0.181 rows=0 loops=1)
                                       ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.32 rows=10 width=56) (actual time=0.124..0.125 rows=9 loops=1)
                                       ->  Append  (cost=0.15..12.08 rows=57 width=40) (actual time=0.004..0.004 rows=0 loops=9)
                                             ->  Index Scan using token_transfer_p2019_09_account_id_consensus_ti_7fb121a0_115678 on token_transfer_p2019_09_115678 tt_1  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2019_10_account_id_consensus_ti_353a78ad_115694 on token_transfer_p2019_10_115694 tt_2  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2019_11_account_id_consensus_ti_c669a8ff_115710 on token_transfer_p2019_11_115710 tt_3  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2019_12_account_id_consensus_ti_d7415d17_115726 on token_transfer_p2019_12_115726 tt_4  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_01_account_id_consensus_ti_157566b2_115742 on token_transfer_p2020_01_115742 tt_5  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_02_account_id [...]

2024-05-21 01:38 UTC, jnels124 commented
This is a difficult query to optimize further. We need to find all token_transfers for a given owner on an allowance to determine if the transfer was part of a contract call. Given the low volume of these we could potentially optimize further by writing  a new table to the db `contract_call_approved_transfer(consensus_timestamp, owner, sender, token_id, contract_id)`. Need to determine best way to distribute if we go that route but this lookup table could give us the keys we need to lookup contract results, and token transfers much easier. However not sure the overall gain of doing so when weighing usage and performance gains with the update in this PR.

2024-05-21 16:49 UTC, jnels124 commented
QUERY PLAN

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.750..0.750 rows=9 loops=1)
   ->  Distributed Subplan 1581_1
         Subplan Duration: 1.57 ms
         Intermediate Data Size: 939 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=1.768..1.769 rows=9 loops=1)
               Task Count: 1
               Tuple data received from nodes: 633 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 633 bytes
                     Node: host=10.4.6.5 port=7433 dbname=mirror_node
                     ->  Subquery Scan on grouped_token_allowances  (cost=11.21..11.53 rows=1 width=75) (actual time=0.033..0.041 rows=9 loops=1)
                           Filter: ((grouped_token_allowances.amount_granted > 0) AND (grouped_token_allowances.row_number = 1))
                           Rows Removed by Filter: 1
                           ->  WindowAgg  (cost=11.21..11.41 rows=8 width=83) (actual time=0.032..0.039 rows=10 loops=1)
                                 Run Condition: (row_number() OVER (?) <= 1)
                                 ->  Sort  (cost=11.21..11.23 rows=8 width=75) (actual time=0.029..0.030 rows=13 loops=1)
                                       Sort Key: token_allowance.token_id, token_allowance.spender, (lower(token_allowance.timestamp_range)) DESC
                                       Sort Method: quicksort  Memory: 26kB
                                       ->  Result  (cost=0.28..11.09 rows=8 width=75) (actual time=0.010..0.021 rows=13 loops=1)
                                             ->  Append  (cost=0.28..10.99 rows=8 width=67) (actual time=0.009..0.018 rows=13 loops=1)
                                                   ->  Index Scan using token_allowance__pk_102558 on token_allowance_102558 token_allowance  (cost=0.28..6.28 rows=3 width=62) (actual time=0.009..0.012 rows=9 loops=1)
                                                         Index Cond: (owner = 4366156)
                                                         Filter: (lower(timestamp_range) <= '1715894584220147004'::bigint)
                                                         Rows Removed by Filter: 1
                                                   ->  Index Scan using token_allowance_history__owner_spender_token_lo_8aed322d_102574 on token_allowance_history_102574 token_allowance_history  (cost=0.27..4.66 rows=5 width=70) (actual t
ime=0.004..0.005 rows=4 loops=1)
                                                         Index Cond: ((owner = 4366156) AND (lower(timestamp_range) <= '1715894584220147004'::bigint))
                         Planning Time: 0.118 ms
                         Execution Time: 0.067 ms
         Planning Time: 0.000 ms
         Execution Time: 1.783 ms
   ->  Distributed Subplan 1581_2
         Subplan Duration: 42.64 ms
         Intermediate Data Size: 124 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=40) (actual time=12.530..12.531 rows=2 loops=1)
               ->  Distributed Subplan 1583_1
                     Subplan Duration: 2.33 ms
                     Intermediate Data Size: 14 bytes
                     Result destination: Send to 3 nodes
                     ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.671..0.672 rows=1 loops=1)
                           Task Count: 1
                           Tuple data received from nodes: 8 bytes
                           Tasks Shown: All
                           ->  Task
                                 Tuple data received from node: 8 bytes
                                 Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                                 ->  Aggregate  (cost=0.47..0.48 rows=1 width=8) (actual time=0.057..0.058 rows=1 loops=1)
                                       ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.40 rows=14 width=32) (actual time=0.050..0.051 rows=9 loops=1)
                                     Planning Time: 0.038 ms
                                     Execution Time: 0.083 ms
                     Planning Time: 0.000 ms
                     Execution Time: 0.686 ms
               Task Count: 16
               Tuple data received from nodes: 80 bytes
               Tasks Shown: One of 16
               ->  Task
                     Tuple data received from node: 0 bytes
                     Node: host=10.4.2.5 port=7433 dbname=mirror_node
                     ->  Append  (cost=0.16..136.32 rows=57 width=40) (actual time=0.131..0.134 rows=0 loops=1)
                           InitPlan 1 (returns $0)
                             ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.00 rows=1 width=8) (actual time=0.106..0.107 rows=1 loops=1)
                           ->  Index Scan using token_transfer_p2019_09_account_id_consensus_ti_7fb121a0_115675 on token_transfer_p2019_09_115675 tt_1  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2019_10_account_id_consensus_ti_353a78ad_115691 on token_transfer_p2019_10_115691 tt_2  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2019_11_account_id_consensus_ti_c669a8ff_115707 on token_transfer_p2019_11_115707 tt_3  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2019_12_account_id_consensus_ti_d7415d17_115723 on token_transfer_p2019_12_115723 tt_4  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_01_account_id_consensus_ti_157566b2_115739 on token_transfer_p2020_01_115739 tt_5  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_02_account_id_consensus_ti_fc8c3fcb_115755 on token_transfer_p2020_02_115755 tt_6  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_03_account_id_consensus_ti_dfdf51e1_115771 on token_transfer_p2020_03_115771 tt_7  (cost=0.15..2.38 ro [...]

2024-05-23 20:40 UTC, steven-sheehy approved these changes

2024-05-28 15:50 UTC, xin-hedera requested changes

2024-05-28 15:50 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> -                    ), transfers as (
can you also change the first CTE to

```
with token_allowances as (
  select *
  from token_allowance_history
  where owner = :owner and amount_granted > 0 and timestamp_range @> :blockTimestamp
  union all
  select *
  from token_allowance
  where owner = :owner and amount_granted > 0 and :blockTimestamp >= lower(timestamp_range)
)
```

The current CTE returns too many rows from `token_allowance_history` and make everything slow afterwards.

The proposed change can use the gist index on `token_allowance_history.timestamp_range` plus the `owner = ` filter to remove unnecessary rows.

2024-05-28 19:30 UTC, jnels124 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> -                    ), transfers as (
Looking at this a bit more. But this change causes several test cases to fail.

2024-05-28 19:40 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java
> -                    ), transfers as (
let's address it in a follow-up

2024-05-28 19:40 UTC, xin-hedera approved these changes
LGTM

2024-05-28 19:44 UTC, merged