test: Implement integration and acceptance tests covering opcode tracer
hashgraph/hedera-mirror-node pull request #8344
Opened 2024-05-21 11:32 UTC by victor-yanev

**Description**:

**Related issue(s)**:

Fixes #7341

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-21 14:39 UTC, kselveliev commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("io.vertx:vertx-core")
What is the use case of this library.

2024-05-21 15:16 UTC, victor-yanev commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("io.vertx:vertx-core")
Calling `usingRecursiveComparison()` was throwing a `ClassNotFoundException` for some buffer from this library and adding this fixes the issue.

2024-05-21 15:33 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("io.vertx:vertx-core")
Then it should be added as `testImplementation`.

2024-05-22 14:45 UTC, kselveliev submitted a review, later dismissed

2024-06-06 04:23 UTC, xin-hedera requested changes

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/ContractActionRepositoryTest.java
> +        assertThat(contractActionRepository.findAllByConsensusTimestamp(timestamp))
normally we just do

```suggestion
        var contractAction = domainBuilder.contractAction().persist();
        assertThat(contractActionRepository.findAllByConsensusTimestamp(contractAction.getConsensusTimestamp()))
```

can keep it as is

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/ContractResultRepositoryTest.java
> +        assertThat(result.get()).isEqualTo(contractResult);
```suggestion
        assertThat(contractResultRepository.findById(timestamp)).contains(contractResult);
```

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeTracerCallsTest.java
> +        if (function.getExpectedErrorMessage() != null) {
if the function should verify something thrown, why is there a conditional check? also the conodition is already checked by the caller.

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/RecordFileServiceTest.java
> +
why missing license header? Please make sure spotless is not disabled.

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TransactionRepositoryTest.java
> +
missing license header

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/RecordFileServiceTest.java
> +        assertThat(recordFileService.findByTimestamp(timestamp)).get().isEqualTo(recordFile);
```suggestion
        assertThat(recordFileService.findByTimestamp(timestamp)).contains(recordFile);
```

this applies all other similar places

2024-06-06 04:23 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/RecordFileServiceTest.java
> +        assertThrows(BlockNumberOutOfRangeException.class, () -> recordFileService.findByBlockType(blockTypeToSearch));
we should use assertj `assertThatThrownBy(...).isInstanceOf(...)`

2024-06-06 17:08 UTC, xin-hedera requested changes

2024-06-06 17:08 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractActionRepository.java
> -/*
license header issue still not fixed, and it now even removes license header?

2024-06-06 17:08 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractActionRepository.java
> +
believe spotless will fix the extra empty line

2024-06-06 17:08 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracerTest.java
> +    @DisplayName("given ModificationNotAllowedException thrown when trying to retrieve account through WorldUpdater, " +
nit, use textblock instead

2024-06-06 17:30 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/ContractActionRepository.java
> -/*
IDE screwed up the merge and reverted some changes from the target branch... I just fixed those now manually.

2024-06-07 08:09 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/RecordFileRepositoryTest.java
> +    void findRecordFileByTimeStamp() {
nit -> timestamp

2024-06-07 08:09 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EthereumTransactionRepositoryTest.java
> +package com.hedera.mirror.web3.repository;
Missing license header for all repository tests

2024-06-07 08:13 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected ContractDebugParameters serviceParametersForDebug(
There are ongoing activities for refactoring all integration tests in mirror-node, including ContractCallTestSetup. Make sure the new changes here are aligned with the upcoming refactoring.

2024-06-07 08:23 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM!

It will be also a good idea to manually test the `/opcodes` endpoint results against the evm cli tool from besu and compare the results for the same smart contract execution (for all cases except HTS precompiles, which are not native and not supported for besu). In this way, we will have 2 different sources of the same execution and compare their opcode traces.

2024-06-07 18:47 UTC, mgoelswirlds approved these changes
LGTM

2024-06-10 06:39 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected ContractDebugParameters serviceParametersForDebug(
We are not doing any persisting here, only setting up the `ContractDebugParameters` for the `ContractDebugService`. I've moved this to the base class, because this is common logic which can by other test classes which need to build `ContractDebugParameters`, but if you think that's unnecessary I can move it to the subclass where we are currently using it.

2024-06-10 06:44 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected ContractDebugParameters serviceParametersForDebug(
Btw, I've also extracted some common logic for setting up the integration test data into different methods, based on the contract that's being used in the tests (there are different entities which are being used in the contract functions and need to be persisted for each contract).

Can you give it a look (it's inside `ContractDebugServiceTest`)

2024-06-10 06:49 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected ContractDebugParameters serviceParametersForDebug(
Possibly, it might be of use to the other team which is refactoring the tests @petreze @fchitakova. 

The idea is to use the appropriate method for the contract which is being used in the `@ParameterziedTest`

2024-06-10 08:54 UTC, victor-yanev commented
> LGTM!
> 
> It will be also a good idea to manually test the `/opcodes` endpoint results against the evm cli tool from besu and compare the results for the same smart contract execution (for all cases except HTS precompiles, which are not native and not supported for besu). In this way, we will have 2 different sources of the same execution and compare their opcode traces.

We have automated this in the `hedera-smart-contracts` repo: https://github.com/hashgraph/hedera-smart-contracts/pull/786

2024-06-10 08:57 UTC, natanasow commented
> LGTM!
> 
> It will be also a good idea to manually test the `/opcodes` endpoint results against the evm cli tool from besu and compare the results for the same smart contract execution (for all cases except HTS precompiles, which are not native and not supported for besu). In this way, we will have 2 different sources of the same execution and compare their opcode traces.

There is [a dedicated task/PR](https://github.com/hashgraph/hedera-smart-contracts/pull/786) in the hedera-smart-contracts repo that should cover these cases, I guess.

2024-06-10 14:27 UTC, xin-hedera approved these changes
there still seems to be spotless formatting issue. perhaps at a later time we should run spotless on all web3 files and fix in a separate PR.

2024-06-12 22:13 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    testImplementation("io.vertx:vertx-core")
I don't see where this dependency is used via any import. Can you clarify?

2024-06-13 08:39 UTC, victor-yanev commented on hedera-mirror-web3/build.gradle.kts
> +    testImplementation("io.vertx:vertx-core")
https://github.com/hashgraph/hedera-mirror-node/pull/8344#discussion_r1608512768

2024-06-13 23:42 UTC, steven-sheehy approved these changes

2024-06-26 14:22 UTC, steven-sheehy approved these changes

2024-06-26 14:23 UTC, merged