feat: Initial Idea of refactoring web3 integration tests
hashgraph/hedera-mirror-node pull request #8385
Opened 2024-05-28 12:24 UTC by stefan-stefanooov

**Description**:
This is a Draft PR that showcases an idea of the initial approach for refactoring web3 integration tests.
This approach focuses only on `evmPrecompileReadOnlyTokenFunctionsTestEthCall` test. And more accurately on the `autoRenewAccountAddress`

**Lets outline the following actions taken:** 

1. Identified all of the needed Entries that we need to configure in the DB for the test to run
2. Extracted all these dependencies in a `persistEntities2` function in the test class itself.
3. Added a parameter for the `autoRenewAccountAddress` that is needed for the setup. 

> Currently the `autoRenewAccountAddress` is in a constant variable in the parent class. The plan is to pass it down to each test by using a custom `ArgumentsProvider`. 

4. Created a custom ArgumentsProvider that passes down to the test the existing ENUM for each function call + the new address
5. Pass this new `Address` to the `persistEntities2` function.

> Doing this we have the power to mutate the `Address` for each instance of the Test. If we do this for all parameters we can generate them on demand. And they can be different for each Test.

**Related issue(s)**:
Refactor and reorganize integration tests in hedera-mirror-web3 module
[#8057](https://github.com/hashgraph/hedera-mirror-node/issues/8057)
Refactor ConstractCallServicePrecompile, ConstractCallService and ContractCallSystemPrecompile
[#8381](https://github.com/hashgraph/hedera-mirror-node/issues/8381)

2024-05-31 14:53 UTC, fchitakova submitted a review, later dismissed

2024-05-31 21:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    protected void persistEntities2(Address autoRenewAccountAddress) {
I don't like such large persist methods as they slow down tests and don't make it clear what the test is actually using. For any one test, it may only need a couple of these entities so it's wasteful to create them all each time. From the method name `persistEntities2()` it's not clear what it's persisting or what the test case is.

2024-05-31 21:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
>          switch (contractFunc) {
If we can get web3j-gradle-plugin, ideally the function enums go away and we can have target test cases. For example instead of the above with the following ENUM:

```
IS_FROZEN("isTokenFrozen", new Address[] {FUNGIBLE_TOKEN_ADDRESS, SENDER_ADDRESS}, new Boolean[] {true}),
```

We can have a simple, easy to understand and maintain test:

```java
    @Test
    void isTokenFrozen() {
        var sender = domainBuilder.entity().persist();
        var token = domainBuilder.token().customize(t -> t.frozen(FROZEN)).persist();
        var contract = MyContract.deploy(web3j, ...);
        
        var result = contract.isTokenFrozen(toAddress(token.getId()), toAddress(sender.getId());
        assertThat(result).isTrue();
    }
```

2024-06-10 12:59 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    protected void persistEntities2(Address autoRenewAccountAddress) {
This was never meant as a final approach. Just wanted to make the setup work. Removed.

2024-06-10 12:59 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
>          switch (contractFunc) {
The new version addresses this. Let's discuss it.

2024-06-11 21:01 UTC, steven-sheehy requested changes

2024-06-11 21:01 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        return delegateService.sendBatchAsync(batchRequest);
For these two can either throw unsupported or loop and call send()

2024-06-11 21:01 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
Can add these at the end:
```
tasks.openApiGenerate {
    mustRunAfter(tasks.named("resolveSolidity"))
}

tasks.processTestResources {
    dependsOn(tasks.named("generateTestContractWrappers"))
}
```

2024-06-12 09:03 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +    protected ContractCallService contractCallService;
Yeah ... I don't need it after all ... removed.

2024-06-12 09:40 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +    }
True.
Web3jService has some methods that we need to implement but I made them return null.
Removed.

2024-06-12 09:43 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +public class ContractDeployer extends CommonIntegrationTest {
Yes this was just a way to get some dependencies, witch are now injected by the DI.
Removed

2024-06-12 09:56 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +        domainBuilder.recordFile().customize(f -> f.bytes(contractBytes)).persist();
I had no idea ... I saw this in the existing tests.  So I presumed it's needed.
Removed.

2024-06-12 10:04 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +    }
It was difficult to keep the **switch** type checking quiet. 
So I resulted to this approach. 
The error now is the `EthSyncing` cannot be converted to `T` (our generic type)

2024-06-12 10:06 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        return delegateService.sendAsync(request, responseType);
Added.

2024-06-12 10:09 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        return delegateService.sendBatchAsync(batchRequest);
Noted! Thanks

2024-06-12 10:10 UTC, stefan-stefanooov commented on hedera-mirror-web3/build.gradle.kts
Added

2024-06-12 10:14 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +public class TestWeb3jService implements Web3jService {
Added

2024-06-12 10:16 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        return delegateService.subscribe(request, unsubscribeMethod, responseType);
Noted and added. Thanks!

2024-06-12 10:17 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    private String MOCK_KEY = "0x4e3c5c727f3f4b8f8e8a8fe7e032cf78b8693a2b711e682da1d3a26a6a3b58b6";
Outdated. This is now done in `CommonWeb3TestConfiguration`
Thanks

2024-06-12 10:20 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    ContractGasProvider contractGasProvider;
Done.

2024-06-12 10:22 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +public class ContractDeployer extends CommonIntegrationTest {
Noted! Thanks.

2024-06-12 10:22 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +
Done.

2024-06-12 10:26 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/solidity/PrecompileTestContract.sol
Yes. I will move them all when the approach is solid. And merged.
This is just for testing purposes. We need the old tests running for comparison.
All `.sol` files should be in this folder.

2024-06-12 10:42 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +                                .toArrayUnsafe()))
It was percent in the old test. 
Copy/Paste ...and minimal modification for minimized complexity, approach taken 😄 
Removed.

2024-06-12 11:09 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    }
Added. Thank you.

2024-06-12 11:42 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    public static <T extends Contract> T deploy(Class<T> contractClass, String binary) throws Exception {
@steven-sheehy 

To create an instance of the PrecompileTestContract auto generated class. (for example)
We need to pass in the `address` of the deployed contract. That is why I need to deploy it first in the Mirror node.... and for that I need the Binary...

But ... could we deploy to a mock address (limitation is that it will be the same for all tests) and then we could do it your way ?

2024-06-12 11:48 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        assertThat(mirrorNodeResponse).isEqualTo(successfulResponse);
Discussion below. 
https://github.com/hashgraph/hedera-mirror-node/pull/8385#discussion_r1635470950

2024-06-12 11:54 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        res.setResult("Good");
@steven-sheehy 

To call the `processCall` function in `TestWeb3jService` class, I need to build the `serviceParameters` that it requires.

**BUT** if we get to here .... we have executed the following lines:
> // Function Call signature
>         var result = contract.isTokenFrozen(tokenAddress, senderAddress);
>         result.send();

Then we get to the `TestWeb3jService -> call` function. Which is already in the context of sending the RPC request over http. As parameters of the `call` function we get the row transaction for example:

2024-06-12 14:44 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        res.setResult("Good");
You should have all the data you need in the raw transaction. Just do `RawTransaction transaction = TransactionDecoder.decode(hexTransaction);`

2024-06-12 20:03 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        res.setResult("Good");
Probably for the few blockType=number we can just have those tests call contract call service directly. For estimate=true we can have some switch on `TestWeb3jService.setEstimate(true)` to turn it on globally.

2024-06-13 00:02 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    public static <T extends Contract> T deploy(Class<T> contractClass, String binary) throws Exception {
I see. Can just call `domainBuilder.id()` and pass that into the persistence and use it for the contract address.

2024-06-13 00:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +    }
Not sure what you mean. Just cast it to `T`. Should work with suppress warnings.

```java
case "eth_syncing" -> (T) syncing();
```

2024-06-13 06:55 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    private static long precompileContractPersist(String binary, DomainBuilder domainBuilder) {
Done.

2024-06-13 06:58 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    @Autowired
Done

2024-06-13 06:58 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +        return entity.getNum();
Done

2024-06-13 07:00 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
Done.

2024-06-13 07:18 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/Web3TestConfiguration.java
> +public class Web3TestConfiguration {
Done

2024-06-13 07:19 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/Web3TestConfiguration.java
> +    ContractDeployer contractDeployer(DomainBuilder domainBuilder) {
Done

2024-06-13 07:20 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/Web3TestConfiguration.java
> + * Copyright (C) 2023-2024 Hedera Hashgraph, LLC
Done

2024-06-13 08:29 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/Web3TestConfiguration.java
> +        final var web3j = Web3j.build(new TestWeb3jService());
Done

2024-06-13 08:32 UTC, stefan-stefanooov commented on hedera-mirror-web3/build.gradle.kts
> +sourceSets { test { solidity { setVersion("0.8.24") } } }
Not a final approach. Remember the problem with returning the Bytecode ? This allows me to test different compiler versions. To be removed.
I added a ToDo

2024-06-13 08:39 UTC, stefan-stefanooov commented on build.gradle.kts
> +        api("org.web3j:core:4.12.0")
Done

2024-06-13 08:50 UTC, stefan-stefanooov commented on hedera-mirror-web3/build.gradle.kts
> +    id("org.web3j") version "4.12.0"
I tried to remove the version myself a week ago...
Unfortunately I get : 

> Plugin [id: 'org.web3j'] was not found in any of the following sources:

...if I remove the version specification. 
I am not a Java dev by default ... please bare with me :)

2024-06-13 08:51 UTC, stefan-stefanooov commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("org.web3j:core:4.12.0")
same as the above comment

2024-06-13 08:54 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +    }
Done

2024-06-13 09:35 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/ContractDeployer.java
> +    public static <T extends Contract> T deploy(Class<T> contractClass, String binary) throws Exception {
Got it ! Absolutely valid.
Done.

2024-06-13 13:31 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        res.setResult("Good");
@steven-sheehy 
Let's continue this discussion,

`Status UPDATE:`
As you can see in the new version of the `call` function, we are creating the `serviceParameters` there, but I need the `sender` address to create it. So I used the approach you suggested. Intermediary Bean state. 
 
Unfortunately I am getting some error : `org.web3j.tx.exceptions.TxHashMismatchException`
<img width="833" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/10372129/8441f4c2-ae01-41ab-8b97-8e0f40c6b83b">

2024-06-13 13:31 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/TestWeb3jService.java
> +        res.setResult("Good");
@steven-sheehy All other comments are handled in the new version.

2024-06-18 14:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +            case "eth_sendRawTransaction", "eth_call" -> (T) call(request.getParams(), request);
Unfortunately, the web3j library calls some of these rpcs implicitly when we invoke eth_call

2024-06-25 14:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    @MethodSource("pocWeb3jMethod")
I think we should imply `@CsvSource` as Steven suggested.

2024-06-25 14:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/TransactionReceiptCustom.java
> +public class TransactionReceiptCustom extends TransactionReceipt {
You can use `@Data` Lombok annotation and remove the set and get methods.

2024-06-25 14:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +    private static final String HEX_PREFIX = "0x";
The variable name should be more descriptive, e.g. `EMPTY_BYTES`

2024-06-25 14:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +        return sendEthCall(rawTrxDecoded, trxHex, request);
Call and EthCall are different things. Call is used internally for executing eth_sendRawTransaction that performs an actual transaction execution, while EthCall executes eth_call that performs transient read only simulation.

We should have a more common name like `executeCall`

2024-06-25 14:33 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +        final var mirrorNodeResult = contractCallService.processCall(serviceParameters);
```suggestion
        final var result = contractCallService.processCall(serviceParameters);
```

2024-06-25 14:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +            res.setResult(trxHex);
It's a good practice to declare fields near the place they start to be used. So we can declare
`final var ethSendTransaction = new EthSendTransaction();`
here

2024-06-25 14:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +    private EthSendTransaction sendEthCall(RawTransaction rawTrxDecoded, String trxHex, Request request) {
Java usually follows camelCase spelling, so all variables with `Trx` in them can be renamed to contain `Transaction`

2024-06-25 14:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +        final var mirrorNodeResult = contractCallService.processCall(serviceParameters);
```suggestion
        final var result = contractCallService.processCall(serviceParameters);
```

2024-06-25 14:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +        final var mirrorNodeResult = contractCallService.processCall(serviceParameters);
```suggestion
        final var result = contractCallService.processCall(serviceParameters);
```

2024-06-25 14:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +    private EthSendTransaction sendEthCall(RawTransaction rawTrxDecoded, String trxHex, Request request) {
sendEthCall -> ethSendTransaction

2024-06-25 14:42 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +        precompileContractPersist(binary, id);
```suggestion
        contractPersist(binary, id);
```

2024-06-25 14:46 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/build.gradle.kts
> +sourceSets { test { solidity { setVersion("0.8.24") } } }
Probably we can remove it?

2024-06-25 14:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
>  class ContractCallServiceERCTokenTest extends ContractCallTestSetup {
Obsolete annotations for this class. We can remove them for now.

2024-06-25 14:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TestWeb3jService.java
> +    public ContractCallService contractCallService;
```suggestion
    private ContractCallService contractCallService;
```

2024-06-26 06:40 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    @MethodSource("pocWeb3jMethod")
I am not using this. It was left behind from some testing. 
The focus on this MR should be just the `web3j` setup. So its small and easier to review.
Removing the code.

2024-06-26 06:40 UTC, stefan-stefanooov commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/resources/TransactionReceiptCustom.java
> +public class TransactionReceiptCustom extends TransactionReceipt {
Thank you.

2024-06-26 06:59 UTC, stefan-stefanooov commented on hedera-mirror-web3/build.gradle.kts
> +sourceSets { test { solidity { setVersion("0.8.24") } } }
The `ToDo` yes. We need to configure the solidity version.

2024-08-01 08:32 UTC, bilyana-gospodinova commented
Closing this PR as the functionality is implemented and merged in https://github.com/hashgraph/hedera-mirror-node/pull/8853.

2024-08-01 08:32 UTC, closed without merging