Add system file fallback to Web3
hashgraph/hedera-mirror-node pull request #8418
Opened 2024-05-30 21:18 UTC by edwin-greene

**Description**:

- Updates the feeSchedule and exchangeRate apis to return historical values.
- Adds a fallback mechanism to the feeSchedule and exchangeRate apis. If the timestamp requested version of the file cannot be parsed the api will automatically fall back to the most recent version that can be parsed.

**Related issue(s)**:

Fixes #8348 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-05-31 19:40 UTC, xin-hedera requested changes

2024-05-31 19:40 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            return bos;
data is copied twice, first copied from the list of `byte[]` into `bos`, then outside the function `bos.toByteArray()`. A better solution without copying is guava `ByteSource`, can do `ByteSource.wrap()` individual byte arrays, then `ByteSource.concat(...).openStream()` to get an `InputStream` and do `parseFrom`

Since it's a stream, perhaps do byte array concat and file parsing in the same function is easier for resource management.

2024-05-31 19:40 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +            ) and file_data.consensus_timestamp <= ?2""",
I don't think any of the fully qualified column names are required at all, also missing `order by consensus_timestamp` in the main query

```suggestion
            where entity_id = ?1
              and consensus_timestamp >= (
                select consensus_timestamp
                from file_data
                where entity_id = ?1
                  and consensus_timestamp <= ?2
                  and (transaction_type = 17 or (transaction_type = 19 and length(file_data) <> 0))
              order by consensus_timestamp desc
              limit 1
            ) and consensus_timestamp <= ?2
            order by consensus_timestamp""",
```

2024-05-31 19:50 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderIntegrationTest.java
> +@ExtendWith(MockitoExtension.class)
I don't see any mocks used and this is an integration test class.

```suggestion
```

2024-05-31 19:50 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/FileDataRepositoryTest.java
> +        assertTrue(fileData3.isEmpty());
nit, use assertj `assertThat(fileData3).isEmpty()`

2024-06-03 20:49 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +     * Loads the exchange rates for a given time.
Got it I have reverted it.

2024-06-03 20:50 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +    @Cacheable(cacheNames = CACHE_NAME_EXCHANGE_RATE, unless = "#result == null")
Thanks I have reverted that change.

2024-06-03 20:50 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        int maxRetries = 10;
Thanks I have updated it to use RetryTemplate/RetryListener.

2024-06-03 20:52 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +            ) and file_data.consensus_timestamp <= ?2""",
Thanks I have updated it.

2024-06-03 20:52 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderIntegrationTest.java
> +@ExtendWith(MockitoExtension.class)
Got it I have removed it.

2024-06-03 20:52 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/FileDataRepositoryTest.java
> +        assertTrue(fileData3.isEmpty());
Sounds good I have fixed it.

2024-06-03 20:53 UTC, xin-hedera requested changes

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +    private final RetryListener retryListener = new RetryListener() {
Don't think a `RetryListener` is needed.

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        public <T, E extends Throwable> void onError(
don't think the `onError` handler is needed either

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            return getFileData(EXCHANGE_RATE_ENTITY_ID.getId(), Arrays.asList(nanoSeconds), ExchangeRateSet::parseFrom);
wrap nanoSeconds into an `AtomicLong` and pass it to `getFileData`, instead of a `List`

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +    private <T> T getFileData(long fileId, final List<Long> nanoSeconds, FileDataParser<T> parser)
```suggestion
    private <T> T getFileData(long fileId, final AtomicLong nanoSeconds, FileDataParser<T> parser)
```

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            nanoSeconds.set(0, fileDataList.getFirst().getConsensusTimestamp() - 1);
what if fileDataList returned from `fileDataRepository.getFileAtTimestamp` is empty?

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            retryContext.setAttribute("nanos", nanos);
don't think we need to set these in the context

2024-06-03 20:53 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        return Bytes.concat(fileDataBytesList.toArray(new byte[0][]));
still involves data copy. fine to keep it as is

2024-06-04 08:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/FileDataRepository.java
> +                  and (transaction_type = 17
Will this filter apply for `transaction_type=17 & file_data not empty`? At first glance it seems non empty file data will be applicable for `transaction_type=19` only.

Shouldn't the clause be:

`and (transaction_type = 17 or transaction_type=19) and length(file_data) <>0`

2024-06-04 13:52 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +    private final RetryListener retryListener = new RetryListener() {
Thanks I have removed it and moved its functionality into a try/catch

2024-06-04 13:52 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +        public <T, E extends Throwable> void onError(
Thanks, I have removed it.

2024-06-04 13:52 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +    private <T> T getFileData(long fileId, final List<Long> nanoSeconds, FileDataParser<T> parser)
Great idea, I have updated it to use AtomicLong

2024-06-04 13:55 UTC, edwin-greene commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            nanoSeconds.set(0, fileDataList.getFirst().getConsensusTimestamp() - 1);
I don't believe my changes have effected that. There is a test for it in `RatesAndFeesLoaderTest`, `loadEmptyFeeSchedules()`. It looks like the expected behavior is that an empty protobuf object (`CurrentAndNextFeeSchedule.newBuilder().build()`) is returned.

2024-06-04 14:45 UTC, xin-hedera commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoader.java
> +            nanoSeconds.set(0, fileDataList.getFirst().getConsensusTimestamp() - 1);
that comment was valid for when in the previous iteration `List.getFirst()` was called before parsing the file, without checking if the list is empty or not.

2024-06-04 14:55 UTC, xin-hedera approved these changes
LGTM

2024-06-05 15:33 UTC, mgoelswirlds approved these changes
LGTM

2024-06-05 16:54 UTC, jascks approved these changes
LGTM

2024-06-05 20:21 UTC, merged