test: add integration tests for OpcodeService
hashgraph/hedera-mirror-node pull request #8425
Opened 2024-05-31 14:39 UTC by victor-yanev

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-10 14:48 UTC, xin-hedera requested changes

2024-06-10 14:48 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
> +class OpcodeServiceTest extends ContractCallTestSetup {
```suggestion
@RequiredArgsConstructor
class OpcodeServiceTest extends ContractCallTestSetup {
```

and

- remove `@Autowired` instance properties
- make them `final`

2024-06-10 14:48 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
> +        private final AtomicReference<ContractDebugParameters> expectedServiceParameters = new AtomicReference<>();
no need to use atomic reference

2024-06-10 14:48 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
> +                    .processOpcodeCall(serviceParametersCaptor.capture(), tracerOptionsCaptor.capture());
I'm not sure why spying the contractDebugService (including capturing its input and output) when doing integration testing of opCodeService. We should treat it as a black box.

The obvious issue aside from the methodology is bugs in contractDebugService may have a chance to escape, since instead of verifying the output from outside of opCodeService without even knowing it depends on contractDebugService, the test cases here directly verify the response is the same as captured from contractDebugService.

2024-06-10 15:11 UTC, victor-yanev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
> +                    .processOpcodeCall(serviceParametersCaptor.capture(), tracerOptionsCaptor.capture());
First, we have to keep in mind that those tests are heavy to perform, especially when we are passing `stack=true, memory=true, storage=true`. Thats why we are doing this “capturing” to avoid executing the same contract call twice which could take quite a lot of time if we have to be also capturing the memory and stack contents after the execution in the EVM.

We have another test file with integration tests for `ContractDebugService` which tests things on a lower level and captures the result from the EVM processor, then compares that against the `OpcodesProcessingResult` that is returned from the call. We can also do this here, but we would essentially be duplicating the tests from the `ContractDebugServiceTest` file. 

As far as the `OpcodeService` is concerned, we just want to make sure that we are building and passing the correct `ContractDebugParameters` and `OpcodeTracerOptions` to the `ContractDebugService`. Do you agree?

2024-06-12 15:05 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
> +                    .processOpcodeCall(serviceParametersCaptor.capture(), tracerOptionsCaptor.capture());
discussed offline. seems like it's a tradeoff we have to make.

2024-06-12 22:15 UTC, steven-sheehy approved these changes

2024-06-27 14:13 UTC, steven-sheehy approved these changes

2024-06-28 15:47 UTC, merged