test: 8448-refactor-self-destruct-op-integration-test
hashgraph/hedera-mirror-node pull request #8457
Opened 2024-06-03 08:10 UTC by fchitakova

**Description**:

The idea of this change is to make the test independent of ContractCallTestSetup class and only reuse `serviceParametersForExecution` method from the base class. 

**Related issue(s)**: https://github.com/hashgraph/hedera-mirror-node/issues/8448 

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2024-06-04 14:30 UTC, petreze commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +        persistEntities();
The end goal should be to remove this generic persist method from here. I see you are overriding it in the `SelfDestructOperationTest` class but this means that the same entities will be persisted for all the tests in the class. We want to refactor in a way that every test itself persist only its minimal set of entities

2024-06-04 14:30 UTC, petreze commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        selfDestructContractPersist();
Maybe create persist method for each test with its minimal set of data. For example, `selfDestructContractPersist()` persist method is needed only for one of the tests in this file

2024-06-05 07:19 UTC, petreze reviewed
In general, there are some methods from `ContractCallTestSetup` which we can reuse for most of the tests. For example, `exchangeRatesPersist()` and `feeSchedulesPersist()` are needed for almost every test

2024-06-05 07:19 UTC, petreze commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private void selfDestructContractPersist() {
We might want to use the iherited method from `ContractCallTestSetup`

2024-06-05 08:14 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        selfDestructContractPersist();
Done, thanks

2024-06-05 08:16 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private void selfDestructContractPersist() {
Why ? This contract is called only in this test class, I do not see reason to leave `selfDestructContractPersist` in  `ContractCallTestSetup` and use it from there instead of `SelfDestructOperationTest`

2024-06-05 08:25 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +        persistEntities();
Done, thanks

2024-06-06 06:43 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private void selfDestructContractPersist() {
Suggestion applied. Thanks

2024-06-06 18:39 UTC, xin-hedera requested changes

2024-06-06 18:39 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +public class SelfDestructOperationTest extends Web3IntegrationTest {
```suggestion
@RequiredArgsConstructor
class SelfDestructOperationTest extends Web3IntegrationTest {
```

2024-06-06 18:39 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private ContractCallService contractCallService;
```suggestion
    private final ContractCallService contractCallService;
```

do the same for all `@Autowired` properties

2024-06-06 18:39 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        final var selfDestructContractAddress = toAddress(EntityId.of(0, 0, 1278));
should make `selfDestructContractAddress` a private static final member of the class. do the same for `senderAddress`

2024-06-07 08:19 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +public class SelfDestructOperationTest extends Web3IntegrationTest {
Done, thanks

2024-06-07 08:24 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        final var selfDestructContractAddress = toAddress(EntityId.of(0, 0, 1278));
Done, thanks

2024-06-07 18:00 UTC, jnels124 reviewed
LGTM

2024-06-11 09:13 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private CallServiceParameters serviceParametersForExecution(
This method can be extracted in a utility class as a static method, which can be invoked in all integration tests. This can be done as a separate PR.

2024-06-11 09:15 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-06-12 06:47 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +public class SelfDestructOperationTest extends Web3IntegrationTest {
Fixed, thanks

2024-06-12 06:50 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private CallServiceParameters serviceParametersForExecution(
Thanks @IvanKavaldzhiev , we have opened issue for that final step after making the tests self-sufficient

2024-06-12 06:55 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private final Address SELF_DESTRUCT_CONTRACT_ADDRESS = toAddress(EntityId.of(0, 0, 1278));
Done, thanks

2024-06-12 06:58 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private Path SELF_DESTRUCT_CONTRACT_BYTES_PATH;
Fixed, thanks

2024-06-12 07:11 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private void feeSchedulesPersist() {
We have created another task https://github.com/hashgraph/hedera-mirror-node/issues/8383 for extracting common methods from the refactored tests after the refactoring, so that we can the common methods more easily.

2024-06-12 07:19 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +                .persist();
Thanks, you are right, I just removed it.

2024-06-12 11:04 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        final var evmCodesContractEntityId = fromEvmAddress(SELF_DESTRUCT_CONTRACT_ADDRESS.toArrayUnsafe());
Thanks!
Changed the method to use generated contract Id, instead of an hardcoded constant.

2024-06-12 11:08 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        final var exchangeRateEntityId = EntityId.of(0L, 0L, 112L);
Done, thanks

2024-06-12 11:21 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    }
Thanks! You are right that in this test we could use default values for some of the fields and have lesser number of parameters. 
Following your suggestion, I reduced the number of parameters of `serviceParametersForExecution` method to 3. 
Unfortunately, in this case it is not possible to further minimize this number to 1, as you have suggested, because the tests starts failing.

2024-06-12 22:25 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    }
I meant that the method should only set the defaults and return the builder, then in each caller it can customize other fields. No test cases should fail since you'd be customizing it for each test. Something like this:

```java
    var callServiceParameters = defaultCallServiceParameters()
        .callData(data)
        .sender(sender)
        .receiver(receiver)
        .build();
```

This `defaultCallServiceParameters()` is generic and could be put into a parent class for reuse. However, am fine with the simplification to 3 parameter method for now.

2024-06-12 22:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private void feeSchedulesPersist() {
I see. Can leave it for the follow up. My thinking was we'd just create a fee schedule that covers all cases and do this in one spot. We can just import the services fee schedule.

2024-06-12 22:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        return selfDestructContractEntity.getNum();
Shouldn't use num directly.

```suggestion
        return selfDestructContractEntity.toEntityId();
```

2024-06-13 06:40 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +        return selfDestructContractEntity.getNum();
Thanks, I've applied your suggestion

2024-06-13 07:05 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
> +    private void feeSchedulesPersist() {
There are already fee schedules and exchange rates that covers all cases in `ContractCallTestSetup`.
I have made the `SelfDestructOperationTest` to inherit `ContractCallTestSetup` again, and how exchange rates and fee schedules are created in the base class. Can you please take a look and share your opinion if this approach is ok.

2024-06-13 23:54 UTC, steven-sheehy approved these changes

2024-06-13 23:55 UTC, steven-sheehy commented
Has merge conflicts though

2024-06-14 07:11 UTC, fchitakova commented
@steven-sheehy , I have updated the branch with the `main` branch in order to resolve conflicts and now it is ok, but approves were automatically removed. Can you please re-approve?

2024-06-14 16:44 UTC, steven-sheehy approved these changes

2024-06-14 16:45 UTC, xin-hedera approved these changes
LGTM

2024-06-14 16:58 UTC, merged