test: 8450-refactor-contract-call-evm-codes-integration-test
hashgraph/hedera-mirror-node pull request #8459
Opened 2024-06-03 08:43 UTC by fchitakova

**Description**:

The idea of this change is to make the test independent of ContractCallTestSetup class and only reuse serviceParametersForExecution method from the base class.

**Related issue(s)**: https://github.com/hashgraph/hedera-mirror-node/issues/8450 

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2024-06-06 06:35 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +                .customize(f -> f.bytes(addressThisContractBytes))
Removed, thanks!

2024-06-06 18:47 UTC, xin-hedera requested changes

2024-06-06 18:47 UTC, xin-hedera commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +class ContractCallEvmCodesTest extends Web3IntegrationTest {
```suggestion
@RequiredArgsConstructor
class ContractCallEvmCodesTest extends Web3IntegrationTest {
```

Then remove all `@Autowired` and change the modifier to `private final`.

2024-06-07 08:29 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +class ContractCallEvmCodesTest extends Web3IntegrationTest {
Done, thanks

2024-06-11 08:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
>          // functionEncodeDecoder#functionHashFor.
Probably this comment is no longer applicable

2024-06-11 08:54 UTC, IvanKavaldzhiev approved these changes
LGTM, some methods and components will be common for more tests, but can be extracted as a final stage in a separate PR

2024-06-13 08:23 UTC, fchitakova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
>          // functionEncodeDecoder#functionHashFor.
It is removed, thanks!

2024-07-01 14:24 UTC, steven-sheehy commented
Closing in favor of the approach in #8385

2024-07-01 14:24 UTC, closed without merging