Add fallback to REST API fileService
hashgraph/hedera-mirror-node pull request #8468
Opened 2024-06-04 18:56 UTC by edwin-greene

**Description**:
Adds a fallback mechanism to the REST APIs for `api/v1/network/exchangerate` and `api/v1/network/fees`. If the timestamp requested version of the file cannot be parsed the api will automatically fall back to the most recent version that can be parsed.

**Related issue(s)**:

Fixes #8419 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-06-05 15:00 UTC, xin-hedera requested changes

2024-06-05 15:00 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +import * as utils from '../utils.js';
```suggestion
import * as utils from '../utils';
```

2024-06-05 15:00 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/network/fees/fallbackMaxRetries.json
> +  "responseStatus": 500,
We should return 404, not 500

2024-06-05 15:00 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +        const fallBackTimestamp = row.consensus_timestamp - 1n;
`consensus_timestamp` is the last not the first so this will not work when the file contents are from multiple file related transactions

2024-06-05 15:00 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +          filterQueries.whereQuery[0].param = fallBackTimestamp;
this is a hack and may or may not work depending on what kind of `timestamp=?` is in the request URL.

2024-06-05 19:47 UTC, edwin-greene commented on hedera-mirror-rest/service/fileDataService.js
> +import * as utils from '../utils.js';
Thanks I have updated this.

2024-06-05 19:48 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/specs/network/fees/fallbackMaxRetries.json
> +  "responseStatus": 500,
Got it ok I have fixed this.

2024-06-05 19:49 UTC, edwin-greene commented on hedera-mirror-rest/service/fileDataService.js
> +        const fallBackTimestamp = row.consensus_timestamp - 1n;
Thanks for catching this. I have updated the query to return the minimum timestamp.

2024-06-05 19:49 UTC, edwin-greene commented on hedera-mirror-rest/service/fileDataService.js
> +          filterQueries.whereQuery[0].param = fallBackTimestamp;
Excellent thanks, I have updated this.

2024-06-06 16:06 UTC, xin-hedera requested changes

2024-06-06 16:06 UTC, xin-hedera commented on hedera-mirror-rest/service/fileDataService.js
> +        ];
just realized `filterQueries` is really weird: `{whereQuery: []}`

nevertheless, your change doesn't fully address my previous feedback. it's still replacing the whole `whereQuery` array.

what if the original `whereQuery` is

```js
[
  {
    query: 'consensus_timestamp > ',
    param: 100000,
  },
  {
    query: 'consensus_timestamp < ',
    param: 200000,
  }
]
```

The logic here would throw away the original conditions and it shouldn't, right?

2024-06-07 19:13 UTC, mgoelswirlds approved these changes
LGTM

2024-06-07 19:21 UTC, xin-hedera approved these changes
LGTM

2024-06-07 19:30 UTC, jascks approved these changes
LGTM

2024-06-09 02:51 UTC, merged