Add accounts allowances, accounts nft and the `/contract/call` tests
hashgraph/hedera-mirror-node pull request #8470
Opened 2024-06-04 19:40 UTC by mgoelswirlds

**Description**:
This PR adds remaining accounts allowances, accounts nft and the `/contract/call` endpoints to the rest monitor

This PR adds
* Accounts allowances - `/{idOrAliasOrEvmAddress}/allowances/crypto` , ` /{idOrAliasOrEvmAddress}/allowances/nfts` ,`/{idOrAliasOrEvmAddress}/allowances/tokens`
* Accounts nfts - `/accounts/{idOrAliasOrEvmAddress}/nfts`
* Contract call -  `/contracts/call` - Invoke a smart contract

**Related issue(s)**:

Fixes #8429

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-05 17:04 UTC, jascks submitted a review, later dismissed
LGTM

2024-06-06 14:46 UTC, xin-hedera requested changes

2024-06-06 14:46 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/config/default.serverlist.json
> +    "_comment": "nftAccountId value might not be the same as nftAllowanceOwnerId in different environments",
remove the comment. most configurable entity ids are different across environments

```suggestion
```

2024-06-06 14:46 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/utils.js
> +const postAPICall = async (url, body, retryPredicate = noRetry) => {
this is pretty much duplicate flow of `getAPIResponse`, you can rename `getAPIResponse` to be more generic, e.g., `fetchAPIResponse`, only thing need to add there is pass in an optional `body`, inside `fetchAPIResponse`,  add `{method: 'POST', headers: {'Content-type': 'application/json; charset=UTF-8' }}` if body is not undefined / null.

2024-06-06 14:46 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/utils.js
> +        },
those these are going away, please don't add comments that's obvious by just looking at the code because they don't add value.

2024-06-06 14:46 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/contracts_tests.js
> +    .run(singleContract);
these should be mandatory fields check

2024-06-06 20:50 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/contracts_tests.js
> +    .run(singleContract);
You mean I should check request params mandatory check also?

2024-06-06 21:45 UTC, xin-hedera requested changes

2024-06-06 21:45 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/utils.js
> +    }
No retry for POST?

2024-06-07 00:23 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/utils.js
> +    }
There should be. Will add that.

2024-06-07 19:24 UTC, xin-hedera approved these changes
LGTM

2024-06-07 19:44 UTC, jnels124 approved these changes
LGTM

2024-06-07 21:40 UTC, merged