convert topic message lookup to async migration
hashgraph/hedera-mirror-node pull request #8472
Opened 2024-06-04 20:45 UTC by jnels124

**Description**:
* convert topic message lookup migration to be asynchronous

**Related issue(s)**:

Fixes #8461

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-06 16:31 UTC, xin-hedera requested changes

2024-06-06 16:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +                .filter(p -> p.getTimestampRange().lowerEndpoint() <= lastRecordFile.get()
nit,  a simpler condition is `upper endpoint < consensus start of last record file`

2024-06-06 16:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var activePartition = timePartitions.stream()
there is flow in the last active partition detection: Since the migration is really slow, the active partition can change in between runs. For example, the migration is kicked off with 2024-05 as the last active partition, runs for a couple of days and importer gets restarted. The second time the migration runs, the active partition becomes 2024-06.

2024-06-06 16:31 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        return Objects.requireNonNull(partitions.poll()).getName();
we should run the async part backwards

2024-06-06 17:30 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var activePartition = timePartitions.stream()
Because the active partition is populated synchronously at the start it doesn't matter right? The active partition will always be the partition that we are currently ingesting files for and will always be  populated up to `select max(consensus_end) from record_file` before any record_file processing happens.

So at the start of the migration if we have `consensus_end='2024-05-31 16:00:00' `

We start importer and the migration runs. The synchronous portion of the migration will write all entries for `topic_message` up to that point before record file processing occurs. 

If we do a deploy later say when `consensus_end='2024-06-03 16:00:00'`. Then there is no synchronous work to be performed by the migration because there will be entries for the active partition so it will be skipped.

2024-06-06 18:05 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var activePartition = timePartitions.stream()
There is an issue though if the active record_file spans partitions. will fix that

2024-06-06 21:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var activePartition = timePartitions.stream()
Ah, I think I missed the empty check in `migrationPartition`

2024-06-06 22:20 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        return Objects.requireNonNull(partitions.poll()).getName();
sorted to process in desc order

2024-06-06 22:26 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +        var activePartitions = timePartitions.stream()
This could actually be a single partition. If boundary is crossed, we only care about the portion of the record file that is in the new partition for the synchronous part of the migration. Will make this change.

2024-06-06 22:53 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +                .filter(p -> p.getTimestampRange().lowerEndpoint() <= lastRecordFile.get()
I left this condition as is because it allows us to only process the portion of the record file that is going to be written to by the next one.

2024-06-07 13:52 UTC, xin-hedera requested changes
just some nitpickings

2024-06-07 13:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +    private final LinkedList<String> partitions = new LinkedList<>();
nit
```suggestion
    private final List<String> partitions = new LinkedList<>();
```

2024-06-07 13:52 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +                .sorted(Comparator.comparing(p -> p.getTimestampRange().upperEndpoint()))
`TimePartitionService.getTimePartitions` already returns the partitions sorted by the timestamp range in ascending order.

```suggestion
```

2024-06-07 13:52 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigrationTest.java
> +        await().atMost(Duration.ofSeconds(5))
perhaps increase the wait time to 30s  avoid any weirdness in github CI

2024-06-07 13:52 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigrationTest.java
> +    protected void waitForCompletion() {
private?
```suggestion
    private void waitForCompletion() {
```

2024-06-07 14:53 UTC, jnels124 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigrationTest.java
> +    protected void waitForCompletion() {
oops yes definitely intended to make private

2024-06-07 15:02 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/TopicMessageLookupMigration.java
> +    private final LinkedList<String> partitions = new LinkedList<>();
was using its deque implementation but not really necessary. will change

2024-06-07 18:41 UTC, xin-hedera approved these changes
LGTM

2024-06-07 18:43 UTC, mgoelswirlds approved these changes
LGTM

2024-06-07 19:04 UTC, merged