Adding monitor token tests
hashgraph/hedera-mirror-node pull request #8480
Opened 2024-06-05 21:34 UTC by mgoelswirlds

**Description**:
This PR adds remaining token nft endpoints to the rest monitor

This PR adds 
* Token nfts -  `/api/v1/tokens/{tokenId}/nfts` and `/api/v1/tokens/{tokenId}/nfts/{serialNumber}` and  `/api/v1/tokens/{tokenId}/nfts/{serialNumber}/transactions`

**Related issue(s)**:
Fixes #8423

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-07 17:15 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/token_tests.js
> +const tokenNftsPath = `${tokensPath}/${nftIdFromConfig}/nfts`;
You mean instead of hardcoding it to 1?

2024-06-07 17:18 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/token_tests.js
> +  const url = getUrl(server, tokensPath);
That's a nice suggestion. Will add that.

2024-06-07 17:36 UTC, mgoelswirlds commented on hedera-mirror-rest/monitoring/token_tests.js
> +const tokenNftsPath = `${tokensPath}/${nftIdFromConfig}/nfts`;
There is a limit of 1 used where this path i sused.

2024-06-07 19:29 UTC, jnels124 approved these changes
LGTM

2024-06-10 16:20 UTC, xin-hedera requested changes

2024-06-10 16:20 UTC, xin-hedera commented on hedera-mirror-rest/monitoring/config/default.serverlist.json
> +    "nftId": "",
better name would be `nftTokenId`. the term `nftId` is overloaded and in SDK it means nft token id + serial number.

2024-06-10 18:00 UTC, jascks approved these changes
LGTM

2024-06-10 18:02 UTC, xin-hedera approved these changes
LGTM

2024-06-10 18:16 UTC, steven-sheehy approved these changes

2024-06-10 18:25 UTC, merged