Refactor `ContractCallServiceERCTokenTest` in web3
hashgraph/hedera-mirror-node pull request #8483
Opened 2024-06-06 10:56 UTC by petreze

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-06-10 08:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected void tokenAccountPersist(
Can you try to use `DomainBuilder` to dynamically create the entities you need inside the test itself, instead of relying on a parent class. If we achieve this decoupling, it will be a lot easier to get rid of `ContractCallTestSetup`.

If you plan to use a step by step approach and achieve this in steps - then we should be fine.

2024-06-11 19:17 UTC, petreze commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected void tokenAccountPersist(
In some cases we pass those specific hardcoded addresses as input parameters or expected results to the test enums. Also we have some common logic inside `ContractCallTestSetup` which would be useful to reuse..

2024-06-11 21:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected void tokenAccountPersist(
I don't think this PR or any of the others provide value if we don't do what Ivan suggests. Besides coupling it is also inefficient because every test sets up all data even if it doesn't need it. So it increases test duration and makes it harder to determine what db changes are truly necessary for the specific test case. The problem is the use of enums forces us to use hardcoded values right now. If we can get the solidity gradle plugin to work then each test can create its minimal, dynamic input.

2024-06-12 03:34 UTC, steven-sheehy requested changes

2024-06-12 03:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> +    protected CallServiceParameters serviceParametersForExecution(
Prefer to return the builder and customize in caller. This would avoid needing overloaded server parameter helper methods. See my comment in https://github.com/hashgraph/hedera-mirror-node/pull/8457#discussion_r1635304471

2024-06-12 03:34 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> +    protected void tokenAccountPersist(
> If you plan to use a step by step approach and achieve this in steps - then we should be fine.

Also, agree with Ivan that this could be a stepping stone to push down global variables into sub-classes as a first step.

2024-06-12 07:15 UTC, petreze commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> +    protected CallServiceParameters serviceParametersForExecution(
@steven-sheehy 
I agree entirely on returning the builder itself which will give a lot of flexibility but can we keep `contractAddress` and `callData` parameters as well as they are going to be set dynamically on every test. So after calling `serviceParametersForExecution()` instead of having `builder.callData().receiver()` we can pass those in the method call itself?

2024-06-13 00:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> +    protected CallServiceParameters serviceParametersForExecution(
That's fine. Main purpose is to reduce very large parameter list. 1-3 params are okay if they are required.

2024-07-01 14:24 UTC, steven-sheehy commented
Closing in favor of the approach in #8385

2024-07-01 14:24 UTC, closed without merging