Initial design doc for Dynamic Address Book.
hashgraph/hedera-mirror-node pull request #8532
Opened 2024-06-11 18:54 UTC by mgoelswirlds

**Description**:
This PR has the initial design for the Dynamic Address Book , Mirror Node implementation.

This PR modifies 
* Adds a design doc 

**Related issue(s)**:

Fixes #8531

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-12 20:35 UTC, xin-hedera requested changes

2024-06-12 20:35 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +[HIP-869](https://hips.hedera.com/hip/hip-869) changes the currently manually administered address book for Hedera into an HAPI managed configuration, updatable via signed Hedera transactions on a da
The HIP doesn't support changing address book daily

2024-06-12 20:35 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +- Persist `transaction_bytes` and `transaction_record_bytes` with the binary proto value to the `transaction` table for `NodeUpdate`,`NodeCreate` and `NodeDelete`.
should explain why we need to persist the raw bytes

2024-06-12 20:35 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +Update the `api/v1/network/nodes` endpoint to return `domain_name`
```suggestion
Update the `/api/v1/network/nodes` endpoint to return `domain_name`
```

2024-06-12 21:31 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +
I think we need to update `AddressBookServiceImpl` to persist the new `domain_name` proto field.

2024-06-13 17:52 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +[HIP-869](https://hips.hedera.com/hip/hip-869) changes the currently manually administered address book for Hedera into an HAPI managed configuration, updatable via signed Hedera transactions on a da
It does state that in the abstract `The Dynamic Address Book will change the currently manually administered address book for Hedera into an HAPI managed configuration, updatable via signed Hedera transactions on a daily basis without the need to restart the consensus nodes to apply changes across the network.`

2024-06-13 18:12 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +[HIP-869](https://hips.hedera.com/hip/hip-869) changes the currently manually administered address book for Hedera into an HAPI managed configuration, updatable via signed Hedera transactions on a da
Striking through the above statement this will be through monthly upgrades. Will edit it.

2024-06-13 18:25 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +
Yes.

2024-06-13 20:12 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +[HIP-869](https://hips.hedera.com/hip/hip-869) implements the HAPI endpoints for Address Book management within current Address Book implementation . In this phase HAPI endpoints are used to facilita
and should break this single very long line of text into multiple lines.
```suggestion
[HIP-869](https://hips.hedera.com/hip/hip-869) implements the HAPI endpoints for Address Book management within current Address Book implementation. In this phase HAPI endpoints are used to facilitate changes to the Address Book, however those changes are applied through existing, monthly upgrade process.
```

2024-06-13 20:12 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +
I get that's the purpose of the HIP. However, we still need to give a summary of the purpose of the mirrornode side design doc.

2024-06-14 16:56 UTC, steven-sheehy requested changes

2024-06-14 16:56 UTC, steven-sheehy commented on docs/design/dynamic-addressbook.md
> +- Expose `domain_name` in the `/network/nodes` endpoint
Missing mention of gRPC API.

2024-06-14 16:56 UTC, steven-sheehy commented on docs/design/dynamic-addressbook.md
> +- Expose `domain_name` in the `/network/nodes` endpoint
Please confirm whether `0.0.102` can actually contain a non-empty domain_name in this phase. It might be that the domain_name is only used for gossip endpoints since `ServiceEndpoint` is used by both gossip and service endpoints. If it's never present in 0.0.102 then we should not add it at this time.

2024-06-14 16:56 UTC, steven-sheehy commented on docs/design/dynamic-addressbook.md
> +          "domain_name": "examplenode.com"
nit: sort

2024-06-14 20:10 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +- Expose `domain_name` in the `/network/nodes` endpoint
So far there from the discussion as part of phase 2 Mainnet might not have `domain_name ` available. But it is still an open question. Also, SDK is going to check if they can consume the domain_name field without issues.

2024-06-14 20:11 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +### REST API
Not sure if this will be added.

2024-06-18 17:38 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +- Expose `domain_name` in the `/network/nodes` endpoint
I got a confirmation that `domain_name` will be populated as part of phase 2 in 101/102.

2024-06-20 18:09 UTC, steven-sheehy approved these changes
LGTM. We should still push to answering admin_key question

2024-06-20 18:20 UTC, xin-hedera approved these changes
LGTM

2024-06-20 18:39 UTC, merged