Suppress recoverable error for inactive evm addresses
hashgraph/hedera-mirror-node pull request #8536
Opened 2024-06-12 17:35 UTC by edwin-greene

**Description**:
Suppresses recoverable errors when unable to lookup an entity id for an inactive evm address.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-06-12 19:24 UTC, steven-sheehy requested changes

2024-06-12 19:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        return !(receipt.getStatus().equals(ResponseCodeEnum.SUCCESS)
Use recordItem.isSuccessful()

2024-06-12 19:24 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var isRecoverableError = throwRecoverableError
While probably they're both guaranteed to be set the same, just in case we should separate recoverable error logic. That is, don't call shouldThrowRecoverableError() once and pass it to both but check them separately with the proper field.

```suggestion
        var isRecoverableError = !(recordItem.isSuccessful() && functionResult.getContractID().hasEvmAddress())
```

2024-06-13 13:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                && !transactionRecord.getContractCallResult().getContractID().hasEvmAddress();
Thanks I have updated this.

2024-06-13 13:58 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var isRecoverableError = throwRecoverableError
I tried a few things here and my changes broke the unit tests, will continue to look at this.

2024-06-13 19:10 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var isRecoverableError = throwRecoverableError
Thanks I have now fixed this, please re-review.

2024-06-13 23:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var throwRecoverableError = shouldThrowRecoverableError(functionResult, recordItem, transactionRecord);
When I said separate I meant to do a similar change for the receipt contractId.
```suggestion
        var throwRecoverableError = !(recordItem.isSuccessful() && transactionRecord.getReceipt().getContractID().hasEvmAddress());
```

2024-06-14 14:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +        var throwRecoverableError = shouldThrowRecoverableError(functionResult, recordItem, transactionRecord);
Got it, this has now been updated.

2024-06-18 20:38 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                !(recordItem.isSuccessful() && functionResult.getContractID().hasEvmAddress())
I might've misled you before. Believe `functionResult.getContractID()` should already log above if it had a recoverable error. This check should run for the one in receipt.

Also, we want to ensure we don't log twice like we're doing now on main so we can skip if previously logged. Something like this (please verify):

```suggestion
                !throwRecoverableError &&
                !(recordItem.isSuccessful() && transactionRecord.getReceipt().getContractID().hasEvmAddress())
```

2024-06-21 14:27 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                && (transactionRecord.getReceipt().getContractID().hasEvmAddress()));
Thanks I have updated this.

2024-06-21 14:32 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
> +                !(recordItem.isSuccessful() && functionResult.getContractID().hasEvmAddress())
Thanks. I ran through the recreate scenario and updated this section. 

The first boolean, `throwRecoverableError` wouldn't indicate that an error was thrown, only that it could be thrown. I've changed the name and added a comment.

2024-06-21 14:43 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplTest.java
> +                Arguments.of(withInactiveEvm, EntityId.EMPTY, false));
Can we capture the logs and verify no recoverable errors for these?

2024-06-21 17:06 UTC, steven-sheehy approved these changes
LGTM

2024-06-21 19:53 UTC, jascks approved these changes
LGTM

2024-06-21 21:21 UTC, steven-sheehy approved these changes

2024-06-21 22:36 UTC, merged