allow k6 to run for multiple namespaces
hashgraph/hedera-mirror-node pull request #8538
Opened 2024-06-12 22:40 UTC by jnels124

**Description**:
* update testkube resources to support k6 tests in multiple namespaces

**Related issue(s)**:

Fixes #8515 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-12 22:42 UTC, jnels124 commented on charts/hedera-mirror-common/templates/test-rest.yaml
> +          name: {{ include "hedera-mirror-common.fullname" $ }}-test-rest  # Todo verify sharing the config is ok
Do we want to share k6 config between namespaces?

2024-06-13 23:53 UTC, steven-sheehy requested changes

2024-06-13 23:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +        release: mirror
Probably we should have this as an empty list?
```suggestion
    targets: []
    #  - namespace: ""
    #    release: mirror
```

2024-06-13 23:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/test-trigger-rest.yaml
> +        test-name: {{ $previous := sub $idx 1 | index $.Values.testkube.test.targets }}test-web3-{{ $previous.namespace }}
Confusing that this is all on one line.
```suggestion
        {{ $previous := sub $idx 1 | index $.Values.testkube.test.targets }}
        test-name: test-web3-{{ $previous.namespace }}
```

2024-06-13 23:53 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/test-rest.yaml
> +          name: {{ include "hedera-mirror-common.fullname" $ }}-test-rest  # Todo verify sharing the config is ok
That's probably best for now until we see a need to diverge. Can remove comment.

2024-06-17 13:27 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +        release: mirror
yes it should be empty

2024-06-17 15:44 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-06-17 15:58 UTC, steven-sheehy commented on charts/hedera-mirror-common/values.yaml
> +    targets: []
I think keeping the structure of the target object as a comment would make it easier to configure. This is what I recommended in my previous comment.

2024-06-17 18:55 UTC, xin-hedera approved these changes

2024-06-17 19:29 UTC, steven-sheehy approved these changes
LGTM

2024-06-18 17:39 UTC, merged