Implement cache control support in REST Java
hashgraph/hedera-mirror-node pull request #8551
Opened 2024-06-14 18:16 UTC by jascks

**Description**:

**In draft:** No unit test or documentation updates made yet.

The JS REST API module supports generic `cache-control` header with config based fine tuning per endpoint, we need to implement the same in Rest Java

- Adds `responseHeaders()` method to `GenericControllerAdvice`.
- Adds additional configuration handling to `RestJavaProperties`

**Related issue(s)**:

Fixes #8346

**Notes for reviewer**:
Much like Javascript implementation, this feature is not limited to `cache-control` headers.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-17 14:44 UTC, jascks commented on hedera-mirror-rest-java/src/main/resources/application.yml
> +          defaults:
Curious what you think the appropriate configuration is we ship with. Neither of these endpoints is excessively taxing on the system/DB I believe.

2024-06-17 21:09 UTC, steven-sheehy requested changes

2024-06-17 21:09 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/ControllerTest.java
> +        void headers() {
We should have an assert in TopicControllerTest that verifies maxAge=5 and one in AllowancesControllerTest that verifies maxAge=1

2024-06-17 21:28 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
>          response.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, "*");
If there is a path override though, we need to add the access control header there as well. Defaults are replaced by path specific overrides, not merged.

2024-06-17 21:36 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +            return path == null ? defaults : this.path.getOrDefault(path, defaults);
Done

2024-06-17 21:37 UTC, jascks commented on hedera-mirror-rest-java/src/main/resources/application.yml
> +              "cache-control": "public, max-age=10"
Done

2024-06-17 21:37 UTC, jascks commented on hedera-mirror-rest-java/src/main/resources/application.yml
> +              "cache-control": "public, max-age=20"
Done

2024-06-17 21:39 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
>          response.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, "*");
Anyway, with that caveat, this can be implemented, but mistakes could be made. Still which to proceed?

2024-06-17 21:43 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
>          response.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, "*");
That should be fixed then regardless of cors header. If you override header A you should not also have to override B-Z. We can add a `PostConstruct` on the properties and merge() defaults into path map.

2024-06-18 17:35 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
>          response.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, "*");
Done. Default properties are inherited by each defined path, with the ability to override. Header names are treated in a case insensitive manner so that multiple headers of the same spelling but different case cannot be defined.

2024-06-18 17:43 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/ControllerTest.java
> +        void headers() {
This is not necessary. The properties are injected into `ControllerTest` in addition to the REST Java application. Therefore, given the test subclasses, what they return via `getUrl()` is used to look up the configured header names and values expected for the returned request mapping information. It then asserts those are present within the response headers returned by the API endpoint. Therefore, as `application.yml` is updated over time, existing tests will not break.

2024-06-18 17:48 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/RestJavaPropertiesTest.java
> +class RestJavaPropertiesTest {
Looks like I need to update this...

2024-06-18 18:00 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/ControllerTest.java
> +        void headers() {
The assumes there's no bug in the logic in properties class and that there's no mistype in the application.yml. It's possible this test just asserts empty list equals empty list. We don't have to add it to every API in the future, but we should have an integration test at controller level that verifies both an overridden and a non-overriden property. Hence why I suggested above. A single line assert in one test is a small price to pay for confidence it provides us.

2024-06-18 18:12 UTC, steven-sheehy requested changes

2024-06-18 18:12 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +    private ResponseConfig response = new ResponseConfig();
nit: Sort before shard

2024-06-18 18:12 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +            response.headers.path.put(pathHeaders.getKey(), mergedHeaders);
```suggestion
            pathHeaders.setValue(mergedHeaders);
```

2024-06-18 18:12 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +        }
This method isn't really needed anymore, right? apiPath can just be null and return null from map. Defaults are already merged into this.path. So callers can just invoke .getPath().get(apiPath).

2024-06-18 18:52 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +        }
But not all paths have headers defined (e.g. NFT allowances), in which case `.getPath().get(apiPath)` will return null and then the code will have to know to go with the default headers, and then access those. Something like:
```java
var responseHeaders = properties.getResponse().getHeaders().getPath().getOrDefault(requestMapping, properties.getResponse().getHeaders().getDefaults());
```

2024-06-18 19:02 UTC, mgoelswirlds requested changes

2024-06-18 20:21 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +    private ResponseConfig response = new ResponseConfig();
Done

2024-06-18 20:21 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +            response.headers.path.put(pathHeaders.getKey(), mergedHeaders);
Done

2024-06-18 20:21 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/RestJavaPropertiesTest.java
> +class RestJavaPropertiesTest {
Done

2024-06-18 20:21 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/ControllerTest.java
> +        void headers() {
Done

2024-06-18 20:29 UTC, jascks commented on docs/configuration.md
> +| `hedera.mirror.restJava.shard`                     | 0                     | The default shard number that this mirror node participates in
@mgoelswirlds , do you still see this formatting problem? It looks all nice and aligned now to me.

2024-06-18 20:35 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
> +        }
Admittedly, it is only `GenericControllerAdvice` that invokes this method in the real world. Keeping it somewhat ignorant about. how things operate behind the scene seems like a good idea still to me.

2024-06-18 20:50 UTC, steven-sheehy approved these changes
LGTM

2024-06-20 15:50 UTC, mgoelswirlds approved these changes
LGTM

2024-06-20 15:53 UTC, merged