Refactor the way contract action index is tracked in `OpcodeTracer`
hashgraph/hedera-mirror-node pull request #8650
Opened 2024-06-26 13:10 UTC by victor-yanev

**Description**:

**Problem**

Currently the way that the `contractActionIndexOfCurrentFrame` is tracked inside `OpcodeTracer` is not exactly how it is done in the `HederaTracer`, where the list of contract actions is built and we are still using the mono code in the `web3` module, so we need to refactor this to be identical to what is done in `HederaTracer`. We need to copy the logic from there and increment the `contractActionIndexOfCurrentFrame` in the places where items are pushed to the `allActions` list in `HederaTracer`.

**This PR**

Copies the way contract actions are added to the `allActions` list in [HederaTracer](https://github.com/hashgraph/hedera-services/blob/ce5f07658a088a968ca56a03614d034ca648e3e1/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java)

- Increments the index in `init`, `tracePrecompileResult`, `traceAccountCreationResult`, and `tracePostExecution`
- Adds the [HederaOperationTracer](https://github.com/hashgraph/hedera-services/blob/ce5f07658a088a968ca56a03614d034ca648e3e1/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaOperationTracer.java) interface
- Copies the needed logic from which handles the precompile calls, updates the state of the message frames, sets an exceptional halt reason and also calls the `tracePrecompileResult` method from the `HederaOperationTracer` interface.

**TODO:**
- Test that there are no regressions in the eth_call, eth_estimateGas and debug_traceTransaction methods
- Verify that OpcodeTracer returns the correct revert reason for reverting HTS calls by taking the right contract action with the index that is tracked:
  - try to locally deploy a test contract which does different nested contract calls, some of which are reverting HTS calls
  - hit the `contract/results/{transactionIdOrHash}/opcodes` endpoint to replay the transaction
  - debug the `OpcodeTracer` to verify that the `contractActionIndexOfCurrentFrame` is correct when we hit the `tracePrecompileCall` method for the HTS calls

**Related issue(s)**:

Fixes #8639

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-09 07:09 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-07-09 10:37 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= 4) {
Perhaps this value needs to be defined as a constant so that the code is more readable.

2024-07-09 10:48 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        if (revertReason.toHexString().startsWith(ERROR_SIGNATURE)) {
The "signature" name is a little confusing as the same terminology in services is related to keys, cryptography and verifications. Can you please rename the constant? My suggestion would be something like "REVERT_REASON_PREFIX" or "ERROR_STRING_PREFIX" or something like that.

2024-07-09 10:57 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        if (revertReason.toHexString().startsWith(ERROR_SIGNATURE)) {
I think `ERROR_FUNCTION_SELECTOR` would be most correct since it decodes to `Error(string)`: https://besu.hyperledger.org/23.10.2/private-networks/how-to/send-transactions/revert-reason#revert-reason-format

2024-07-09 10:57 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        return Bytes.concatenate(
It seems to me that too many type transformations are being made. We call `formatRevertReason` in `OpcodeTracer#getRevertReasonFromContractActions`. There we have `action.getResultData()` as byte array. Then we transform it to Bytes, to hex string, to byte array, to String and we return it as Bytes. Can you please think if there is a way to reduce this amount?

2024-07-09 10:57 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= 4) {
Changed it to use `Integer.BYTES`

2024-07-09 13:35 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
> +        return Bytes.concatenate(
Thanks, that's better. However, when the `revertReason` is null the Bytes concatenation in `getAbiEncodedRevertReason` method will produce the same result each time and I think we can simplify that by defining it as a constant and directly returning it. This way we can start with the null check and directly return this value and skip all the null checks after that.

2024-07-10 06:45 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= Integer.BYTES) {
Can you please add a comment what would this int contain?

2024-07-10 12:18 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= Integer.BYTES) {
I thought it's evident enough from the line below:
```java
ResponseCodeEnum responseCode = ResponseCodeEnum.forNumber(trimmedReason.toInt());
```

2024-07-10 13:12 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= Integer.BYTES) {
Yes, but you have to analyze the code in order to understand it. At first glance, it seems that the reason needs to be an int. However, it seems that it is fine if it isn't, because the reason can be formatted successfully on line 243 as well. If the reader clicks on the provided link at line 226, they will understand, but the link can be moved or become invalid at some point so my suggestion was to add a comment describing the reason format.

2024-07-10 15:52 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= Integer.BYTES) {
Yeah, that actually covers an edge case where the revert reason in the contract actions contains a response code number in a plain string and:
1. it’s not in the valid format described in besu’s documentation
2. It contains only a number which doesn’t speak anything to the end user

so we convert this to an ABI-encoded string of the response code name, to give some relevant information, at least, if we hit this edge case.

2024-07-10 15:53 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
> +        if (trimmedReason.size() <= Integer.BYTES) {
You are right, I will add a comment that explains this above those lines. Otherwise, its not really obvious why we are doing this.

2024-07-10 22:06 UTC, steven-sheehy requested changes

2024-07-10 22:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/AbstractEvmMessageCallProcessor.java
> +            hederaOperationTracer.tracePrecompileResult(
What's the advantage of casting tracer and using `tracePrecompileResult()` instead of just implementing `tracePrecompileCall()` which will have the result as a parameter? The logic for the latter is already in the parent class.

2024-07-11 08:29 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/AbstractEvmMessageCallProcessor.java
> +            hederaOperationTracer.tracePrecompileResult(
Because if we call it here, we would modify the behaviour of the processor to call `tracePrecompileCall()` twice in different places instead of once, which we don't want to do.

This code around `tracePrecompileResult()` is copied from the mono code in services in order to replicate 1:1 the flow in which `contractActions` are built and instead of building the contract action, we just increment the `contractActionIndexOfCurrentFrame` in the same exact places to be able to track which contract action we need to get from the list.

2024-07-11 08:30 UTC, victor-yanev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
>          this.contractActionIndexOfCurrentFrame++;
Simply getting the opcodes size doesn't work because we don't have a 1:1 mapping between opcodes and contract actions

2024-07-11 22:31 UTC, steven-sheehy approved these changes
LGTM

2024-07-12 06:20 UTC, bilyana-gospodinova approved these changes
LGTM

2024-07-12 07:45 UTC, merged