Dynamic address book mirror node implementation
hashgraph/hedera-mirror-node pull request #8681
Opened 2024-07-01 17:15 UTC by mgoelswirlds

**Description**:
This PR adds the functionality to mirror node as per [HIP-869](https://hips.hedera.com/hip/hip-869)

This PR modifies the `Importer`,`DB` and the `REST API ` in order to support HIP-869
* Adds `NodeCreateTransactionHandler`,`NodeUpdateTransactionHandler`,`NodeDeleteTransactionHandler`
* Adds `domain_name` column to the `address_book_service_endpoint` table
* Modifies `address_book_service_endpoint` indexes
* Adds `domain_name` to the `/network/nodes` REST API

**Related issue(s)**:

Fixes #8517

**Notes for reviewer**:
- Still WIP on persisting `domain_name` to the `address_book_service_endpoint` table
- Still need to add `domain_name` to the gRPC service
- 
**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-02 12:09 UTC, xin-hedera requested changes

2024-07-02 13:38 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/network/nodes/all-params.json
> +        "port": -1,
Because the default for the port is -1

2024-07-02 13:45 UTC, mgoelswirlds commented on hedera-mirror-rest/api/v1/openapi.yml
> +
yes missed it.

2024-07-02 14:39 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/network/nodes/all-params.json
> +        "port": -1,
then we should drop the default. also in importer in case there is no IP address information, we need to skip setting port because in protobuf port is a primitive int, which defaults to 0.

2024-07-02 14:58 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/network/nodes/all-params.json
> +        "port": -1,
Ok will make that change.

2024-07-11 20:09 UTC, mgoelswirlds commented on hedera-mirror-rest/api/v1/openapi.yml
> +
I added these changes, but since this is going to be behind a persist flag , maybe we shouldn't show this info until the services release.

2024-07-11 22:43 UTC, xin-hedera commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.nodes`                      | false                                                | Persist node transaction data to the database
what's the motivation of such a flag?

2024-07-12 00:54 UTC, mgoelswirlds commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.nodes`                      | false                                                | Persist node transaction data to the database
We wanted to get this feature in this Mirror node release while services will take some more time. This way we do not persist Node transactions data until then.

2024-07-12 15:31 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/network/nodes/all-params.json
> +        "port": -1,
drop the default of the column in the db table

2024-07-12 16:06 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
> +    private static class MigrationAddressBook {
Don't think you need these two classes, since the only schema change is in address_book_service_endpoint

2024-07-12 16:06 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    @SuppressWarnings("deprecation")
is `deprecation` supression really needed for the three functions?

2024-07-12 19:32 UTC, steven-sheehy requested changes

2024-07-15 15:14 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
> +    private static class MigrationAddressBook {
We do need it, since the AdderssBookServiceEndpoint is embedded in these classes.

2024-07-15 15:17 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
> +    private static class MigrationAddressBook {
you can use the domain classes in common with custom SQL

2024-07-15 15:42 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.0__add_domain_name.sql
> +    alter column port drop not null,
yes it will have a port.

2024-07-15 18:37 UTC, mgoelswirlds commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/NetworkControllerTest.java
> +    }
Issue is addressBookEntry persists the entry , so that's not working.

2024-07-16 15:52 UTC, steven-sheehy requested changes

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/NetworkController.java
> +                serviceEndpoint.build();
Weird mix of builder and setters. Also sort.
```suggestion
                var serviceEndpoint = ServiceEndpoint.newBuilder()
                    .setDomainName(s.getDomainName())
                    .setIpAddressV4(ProtoUtil.toByteString(ipAddressV4))
                    .setPort(s.getPort())
                    .build();
```

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/NetworkControllerTest.java
> +    void noLimitServiceEndpointWithDomainName() {
We should have a test where domain_name and ip_address_v4 are null/empty string to ensure no NPE/issues.

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.1__add_domain_name.sql
> +    add column if not exists domain_name varchar(253) default null;
There's inconsistency in the database results if the same proto bytes are processed before and after this PR. The proto defaults domain_name and ip_address_v4 to empty string so the code will set that after this PR, but this will convert existing rows to null. 

Likewise ip_address_v4 will never be null even after so we can keep that constraint. So we should set both string fields to default to empty string and keep not null.

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-rest/model/addressBookServiceEndpoint.js
> +    this.domainName = serviceEndpoint.domain_name;
nit: Sort

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
> +    void nodeCreateTransaction() {
We should have a parameterized test that test nodes persist property is true and false for each of the handlers

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    }
The standard for RecordItemBuilder is to populate every field with the most common configuration. Please set all top level fields in create and update transactions.

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        var builder = NodeDeleteTransactionBody.newBuilder().clearNodeId();
Remove clearNodeId and set it.

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public Builder<NodeCreateTransactionBody.Builder> nodeCreate() {
Set node id in the receipt for all 3 tx

2024-07-16 15:52 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
> +class NodeCreateTransactionHandlerTest extends AbstractTransactionHandlerTest {
We should have new integration tests added to `EntityRecordItemListenerNodeTest`

2024-07-16 18:59 UTC, steven-sheehy requested changes

2024-07-16 18:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.1__add_domain_name.sql
> +    add column if not exists domain_name varchar(253) not null;
We need to default ip address and domain name to empty string, as I said previously

2024-07-16 18:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        return new Builder<>(TransactionType.NODEDELETE, builder).receipt(r -> r.setNodeId(id()));
The id in the receipt and body have to match. Same for others.

2024-07-16 18:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setDescription(StringValue.of("Node update"))
Still missing fields in create and update. Populate **all** fields

2024-07-16 18:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setDomainName("")
Gossip endpoints have to be IP, but service endpoints permit domain name. So we should set ipaddressv4="" and domainName="node1.hedera.com" here to have both types.

2024-07-16 18:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setPort(80)
```suggestion
                .setPort(50211)
```

2024-07-16 18:59 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +        assertAll(() -> assertEquals(0, entityRepository.count()), () -> assertThat(transactionRepository.findAll())
Shouldn't use assertAll for new code. Newer standard is to use assertj soft assertions and `softly` from parent.

2024-07-16 19:47 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setDescription(StringValue.of("Node update"))
The fields are certificates and hashes. not sure of the sizes there.

2024-07-16 20:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                .setDescription(StringValue.of("Node update"))
and you're missing nodeId

2024-07-17 18:48 UTC, steven-sheehy approved these changes
LGTM

2024-07-17 19:55 UTC, xin-hedera approved these changes
LGTM

2024-07-18 00:26 UTC, merged