Add support for TokenReject transaction
hashgraph/hedera-mirror-node pull request #8683
Opened 2024-07-01 19:43 UTC by edwin-greene

**Description**:
Adds support for TokenReject transaction to Importer

**Related issue(s)**:

Fixes #8272 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-07-01 21:00 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +    public TransactionType getType() {
should override `getEntity(RecordItem recordItem)` and return the owner account. Note per the protobuf doc, if owner is not set in the tx body, it defaults to the transaction payer.

2024-07-01 21:05 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        var fungibleTokenReference = tokenReference().clearNft().setFungibleToken(tokenId());
we should have a `tokenReference(TokenTypeEnum tokenType)` function, instead of creating a nft token reference then throwing it away & replacing it with fungible token reference.

2024-07-01 21:05 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        createAndAssociateToken(
should move away from the old ways to write the token related integration tests, instead, use `recordItemBuilder` and `domainBuilder`

2024-07-02 17:50 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +    public TransactionType getType() {
Great thanks, I have updated this and added a test.

2024-07-02 17:50 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        var fungibleTokenReference = tokenReference().clearNft().setFungibleToken(tokenId());
Sounds good I have updated it.

2024-07-03 17:01 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +        return !EntityId.isEmpty(ownerId) ? ownerId : recordItem.getPayerAccountId();
are we sure the owner in the tx body can be an alias / evm address?

If not, we should get rid of `entityidService.lookup`. The problem is entityIdService.lookup returns

- `Optional.of(EntityId.EMPTY)` if it can't find the alias/evm address to entity id mapping
- `Optional.empty()` if there is error

In both cases, it's wrong to fall back to the payer account id.

2024-07-03 17:36 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +        return !EntityId.isEmpty(ownerId) ? ownerId : recordItem.getPayerAccountId();
Thanks, it should support alias'. I have updated the incorrect logic, it will now only do the lookup if the tokenReject has an owner. If the tokenReject does not have an owner it will return the payer account.

2024-07-03 18:59 UTC, steven-sheehy requested changes

2024-07-03 21:42 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionType.java
> +    TOKENREJECT(57, EntityOperation.NONE);
Thanks I have updated these.

2024-07-03 21:43 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
> +        createAndAssociateToken(
Thanks I have updated these tests. The old method had a lot of assertions packed in. When reviewing double check that I didn't miss any important assertions.

2024-07-03 22:14 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionType.java
> +    TOKENREJECT(57, EntityOperation.NONE);
Did you add the response codes? Did you follow the rest of the checklist?

2024-07-08 18:10 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionType.java
> +    TOKENREJECT(57, EntityOperation.NONE);
These should now be correct in `transactionResult.js`

2024-07-08 18:15 UTC, jascks commented on hedera-mirror-rosetta/app/domain/types/constants.go
> -	346: "INVALID_MAX_AUTO_ASSOCIATIONS",
This one (346) is defined in the recently merged dependabot PR #8717. _All_ of these values remained defined in `hedera-mirror-rest/model/transactionResult.js`.  Why remove them here?

2024-07-08 18:15 UTC, jascks commented on hedera-mirror-rosetta/app/domain/types/constants_test.go
> -const maxCode = int32(355)
Seems we need more detailed documentation than `docs/checklist/feature.md`.

2024-07-08 18:18 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants.go
> -	346: "INVALID_MAX_AUTO_ASSOCIATIONS",
because for rosetta we should have opted out of adding new response codes, the logic already supports for any unknown error code, just map it to a generic description `GENERAL_ERROR`

2024-07-08 18:24 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/domain/types/constants.go
> +	56: "NODEDELETE",
There's inconsistency in that for go node transactions were added but not in js or java

2024-07-08 18:30 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants.go
> +	56: "NODEDELETE",
we need to do the same for java & js I guess. I'm not sure if there is a 0.52 js proto package or not. Those new tx types are definitely there in the upstream v0.52 `hedera-protobufs` repo.

2024-07-08 19:02 UTC, steven-sheehy approved these changes
LGTM

2024-07-08 19:31 UTC, xin-hedera approved these changes
LGTM

2024-07-08 19:51 UTC, jnels124 approved these changes
LGTM

2024-07-08 20:54 UTC, jascks approved these changes
LGTM

2024-07-08 21:03 UTC, merged