Modifying dynamic address book design to add admin_key and node table.
hashgraph/hedera-mirror-node pull request #8730
Opened 2024-07-09 00:31 UTC by mgoelswirlds

**Description**:
This PR includes the design for the node and node_history table.

This PR modifies
* Adds the `node` and `node_history` table design.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:
* The `admin_key` addition to the rest API and gRPC API will not be added now.
`Questions:`
* Since we are adding a node table, all node information from address_book_entry should be in that table right?

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-09 13:32 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +create table if not exists node
Need to check with the team, if this design is ok, since most of the fields are present in the `address_book_entry` table.

2024-07-09 13:32 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +- Update the `NetworkController` to add `domain_name` to the service endpoint and `admin_key`.
Returning the `admin_key` in the REST API will not be implemented for the next few releases.

2024-07-09 15:00 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +);
missing `timestamp_range`, that's the standard for tables with history twin

2024-07-09 15:00 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +create index if not exists node_history__timestamp_node_id
what's the purpose of the index?

2024-07-09 15:49 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +create index if not exists node_history__timestamp_node_id
For when we need to query the node_history, since the admin_key could update with every NodeUpdate transaction.

2024-07-09 16:26 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
`public_key` is the same as before , but `admin_key` as per the proto is 
```
  An administrative key controlled by the node operator.
     * This key MUST sign this transaction.
     * This key MUST sign each transaction to update this node.
```
Also this will take effect instantly and not wait for the monthly update as would the `public_key`

2024-07-09 16:46 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +create index if not exists node_history__timestamp_node_id
then we should have an index on `(node_id, lower(timestamp_range))`, similar to other history tables

2024-07-09 16:56 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
The confusion is I don't see a `public_key` in the node create / node update tx, so I assume this comes from the current address book file. When all DAB phases complete, where do we get the public key, at least for new nodes?

2024-07-09 17:06 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
Interesting fact is there is `public_key` field in. node create / update tx in the [HIP](https://hips.hedera.com/hip/hip-869). However there is no such field in 0.52 protobuf files. Is it a decision made in later discussions? If so, how do we get the public key?

2024-07-09 17:16 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    stake                  bigint          null
Node from Node transactions. Removing it.

2024-07-09 17:18 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
`public_key` can be got from `grpc_certificate_hash`. I don't think I need to include it here though.

2024-07-09 17:21 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    node_cert_hash         bytea           null,
Looks like we need to get this from NodeAddress proto , which would not be available during node transactions.
Removing it.

2024-07-09 17:29 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
that's wrong. they are not the same stuff at all.

2024-07-09 17:35 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +    node_cert_hash         bytea           null,
this fall into the same mystery that there is `certificate_hash` field in the protobuf proposed in the HIP however disappeared in 0.52 protobuf files. I think you need to ask the team to clarify.

2024-07-09 21:39 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
It was removed later and the HIP not updated. You are right it is got from the address_book. That is why I think I do not need to include it here.

2024-07-09 23:21 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
Might be fine to not include it in the table now. The bigger question is once DAB is fully implemented, how do we get the node’s public key? Are we going to add at least the public key field to the related transactions in phase 2?

2024-07-09 23:31 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    public_key             varchar(1024)   null,
I will confirm it, but looks like it they will get it from the address book itself as it is gotten now.

2024-07-10 15:02 UTC, mgoelswirlds commented on docs/design/dynamic-addressbook.md
> +    node_cert_hash         bytea           null,
Apparently `certificate_hash` was renamed to `grpc_certificate_hash`.

2024-07-10 17:00 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +create table if not exists node
since it's a new table, the design doc should also cover the new domain class, new `EntityListener.onNode` method, and transaction handler changes to parse and persist the domain objects.

2024-07-12 15:13 UTC, xin-hedera commented on docs/design/dynamic-addressbook.md
> +- Persist `Node` and `NodeHistory` domain objects.
in importer, we don't directly persist history domain objects, they are all created as the non-history objects, and the upsert framework will do its magic to decide which table a row should get persisted to.

2024-07-12 19:36 UTC, steven-sheehy requested changes

2024-07-12 19:36 UTC, steven-sheehy commented on docs/design/dynamic-addressbook.md
> +- Add `AbstractNode`,`Node` and `NodeHistory` domain objects in the common module.
```suggestion
- Add `AbstractNode`, `Node` and `NodeHistory` domain objects in the common module.
```

2024-07-12 19:36 UTC, steven-sheehy commented on docs/design/dynamic-addressbook.md
> +- Send Node create, update and delete transactions and verify that the `admin_key` is updated on the (`/network/nodes`) API.
For sure on public networks we won't have permission to send node transactions. It's doubtful even on preprod we could get it. I don't think we can add acceptance tests for this.

2024-07-16 15:05 UTC, steven-sheehy approved these changes
LGTM

2024-07-16 15:24 UTC, merged