add token name query param
hashgraph/hedera-mirror-node pull request #8789
Opened 2024-07-16 18:21 UTC by jnels124

**Description**:
* add pg_trgm gin index on `token.name`
* add token name parameter support to rest api
* add new k6 test for token name param on /api/v1/tokens
* update open api spec 

**Related issue(s)**:

Fixes #8702
Fixes #8703

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-16 22:26 UTC, jnels124 commented on hedera-mirror-rest/tokens.js
> +      conditions.push(`t.name ILIKE $${params.push('%' + filter.value + '%')}`);
multiple occurrences of the name parameter do a search for tokens that contain substrings from all occurrences

2024-07-16 22:28 UTC, jnels124 commented on hedera-mirror-rest/tokens.js
> +      ret = op === queryParamOperators.eq;
should we limit the length of name param values?

2024-07-16 22:41 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +      ret = op === queryParamOperators.eq;
Yes, token [names](https://github.com/hashgraph/hedera-protobufs/blob/54b258dfa27866d2654bb036112298b5a6693505/services/token_create.proto#L78) can't exceed 100 bytes

2024-07-16 22:56 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
Small adjustment noticed when doing eu migration

2024-07-17 15:10 UTC, xin-hedera requested changes

2024-07-17 15:10 UTC, xin-hedera commented on hedera-mirror-common/src/test/resources/init.sql
> +CREATE extension if not exists pg_trgm;
```suggestion
create extension if not exists pg_trgm;
```

also add it to https://github.com/hashgraph/hedera-mirror-node/blob/ab647eabbbab117f8f99d94fedac6c4519b922e0/hedera-mirror-rosetta/container/entrypoint.sh#L31

2024-07-17 15:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.0__token_name_index.sql
> +create index if not exists token__name on token using gin (name gin_trgm_ops);
`V1.98.1` and it's nice to have a newline at the end of the file.

2024-07-17 15:10 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.4.0__token_name_index.sql
> +create index if not exists token__name on token using gin (name gin_trgm_ops);
`V2.3.1`

2024-07-17 15:10 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +  return new Blob([str]).size <= maxSize;
why can't we use `str.length`?

2024-07-17 15:34 UTC, jnels124 commented on hedera-mirror-rest/utils.js
> +  return new Blob([str]).size <= maxSize;
I wasn't sure if I can guarantee all chars will be utf-8 and single byte.

2024-07-17 18:43 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.0__token_name_index.sql
> +create index if not exists token__name on token using gin (name gin_trgm_ops);
Might have to adjust this depending on which PR goes in first.

2024-07-17 19:10 UTC, steven-sheehy requested changes

2024-07-17 19:10 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.1__token_name_index.sql
Please coordinate with Mugdha as I think you're both utilizing the same migration numbers. Whoever gets in last will need to doublecheck.

2024-07-17 19:10 UTC, steven-sheehy commented on charts/hedera-mirror/values.yaml
> +    - name: pg_trgm
Is there some specific version or `stable` we should use?

2024-07-17 19:10 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: "#/components/parameters/tokenNameQueryParam"
Sort after limit so it shows up alphabetically by name

2024-07-17 19:10 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +    if (filter.key === filterKeys.NAME) {
Should we disallow certain combination of query parameters like token.id+name or publickey+name, etc if they don't make sense or have performance impacts?

2024-07-17 19:10 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  filterKeys.NAME,
Please update the docs/rest/README.md with the new param and docs/database/README.md with the new index.

2024-07-17 20:21 UTC, jnels124 commented on charts/hedera-mirror/values.yaml
> +    - name: pg_trgm
meant to fill this in. Wanted to see what the current default is.

2024-07-17 20:58 UTC, jnels124 commented on hedera-mirror-rest/tokens.js
> +    if (filter.key === filterKeys.NAME) {
in the case of public key, there can be many tokens tied to the same public key. We could exclude, but doesn't seem like much of a performance gain. Not sure how much benefit there is now or in the future to specify a public key that has many tokens and then filter by name. 

with name and public key
```
--------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=3750.43..3750.53 rows=40 width=113) (actual time=5.741..5.745 rows=0 loops=1)
   ->  Sort  (cost=3750.43..3750.53 rows=40 width=113) (actual time=5.740..5.743 rows=0 loops=1)
         Sort Key: t.token_id
         Sort Method: quicksort  Memory: 25kB
         ->  Hash Join  (cost=1531.69..3749.37 rows=40 width=113) (actual time=5.735..5.738 rows=0 loops=1)
               Hash Cond: (e.id = (t.token_id)::bigint)
               ->  Bitmap Heap Scan on entity e  (cost=190.32..2405.99 rows=762 width=44) (actual time=0.058..0.351 rows=765 loops=1)
                     Recheck Cond: ((public_key)::text = '421050820e1485acdd59726088e0e4a2130ebbbb70009f640ad95c78dd5a7b38'::text)
                     Heap Blocks: exact=128
                     ->  Bitmap Index Scan on entity__public_key_type  (cost=0.00..190.13 rows=762 width=0) (actual time=0.037..0.038 rows=765 loops=1)
                           Index Cond: ((public_key)::text = '421050820e1485acdd59726088e0e4a2130ebbbb70009f640ad95c78dd5a7b38'::text)
               ->  Hash  (cost=1308.03..1308.03 rows=2668 width=77) (actual time=5.269..5.270 rows=2410 loops=1)
                     Buckets: 4096  Batches: 1  Memory Usage: 293kB
                     ->  Bitmap Heap Scan on token t  (cost=32.68..1308.03 rows=2668 width=77) (actual time=0.420..4.666 rows=2410 loops=1)
                           Recheck Cond: ((name)::text ~~* '%bar%'::text)
                           Heap Blocks: exact=816
                           ->  Bitmap Index Scan on token__name  (cost=0.00..32.01 rows=2668 width=0) (actual time=0.298..0.298 rows=2410 loops=1)
                                 Index Cond: ((name)::text ~~* '%bar%'::text)
Planning Time: 0.495 ms
 Execution Time: 5.800 ms
```

with just public key
```
Limit  (cost=2443.49..3412.44 rows=100 width=113) (actual time=0.538..0.960 rows=100 loops=1)
   ->  Merge Join  (cost=2443.49..8373.45 rows=612 width=113) (actual time=0.537..0.951 rows=100 loops=1)
         Merge Cond: ((t.token_id)::bigint = e.id)
         ->  Index Scan using token_pkey on token t  (cost=0.29..5819.34 rows=40803 width=77) (actual time=0.012..0.364 rows=742 loops=1)
         ->  Sort  (cost=2442.46..2444.37 rows=762 width=44) (actual time=0.519..0.525 rows=100 loops=1)
               Sort Key: e.id
               Sort Method: quicksort  Memory: 85kB
               ->  Bitmap Heap Scan on entity e  (cost=190.32..2405.99 rows=762 width=44) (actual time=0.067..0.395 rows=765 loops=1)
                     Recheck Cond: ((public_key)::text = '421050820e1485acdd59726088e0e4a2130ebbbb70009f640ad95c78dd5a7b38'::text)
                     Heap Blocks: exact=128
                     ->  Bitmap Index Scan on entity__public_key_type  (cost=0.00..190.13 rows=762 width=0) (actual time=0.047..0.047 rows=765 loops=1)
                           Index Cond: ((public_key)::text = '421050820e1485acdd59726088e0e4a2130ebbbb70009f640ad95c78dd5a7b38'::text)
 Planning Time: 0.382 ms
 Execution Time: 1.017 ms
```

In the case of id, we could exclude it in the case of an `eq` op but not really in others. All that is saved in that case though is small filtering on the name as it will use the pk index `token_id`.

2024-07-17 22:00 UTC, jnels124 commented on hedera-mirror-rest/tokens.js
> +    if (filter.key === filterKeys.NAME) {
on second thought, it may become expensive over time using this param and large range gte token.id queries. Maybe we should disallow this param with token.id queries.

2024-07-18 19:02 UTC, jnels124 commented on hedera-mirror-rest/tokens.js
> +  filterKeys.NAME,
for the rest docs, this param doesn't cause new tables to be accessed so the tables listed under the root endpoint /tokens is correct. Do you want to duplicate the row with the additional param? It appears we only add a separate entry when that param triggers an additional table to be used in the query

2024-07-18 19:14 UTC, steven-sheehy commented on hedera-mirror-rest/tokens.js
> +  filterKeys.NAME,
True, so just the database doc needs updating then.

2024-07-18 22:35 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +const isMaxBytes = (str, maxSize) => {
Should have a test

2024-07-19 14:48 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-07-19 14:55 UTC, jascks submitted a review, later dismissed
LGTM

2024-07-19 15:34 UTC, xin-hedera approved these changes
LGTM

2024-07-19 16:23 UTC, xin-hedera approved these changes
LGTM

2024-07-19 16:26 UTC, jascks approved these changes
LGTM

2024-07-22 17:43 UTC, jnels124 commented
sauce -->  271
sauce-quack --> 1
bar --> 2410 

V1
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| tokensName | /tokens?limit=100&name=bar | 1500 | 100.00 | 1633.80/s | 1633.80/s | 810.77ms | No | |
| tokensName | /tokens?limit=100&name=sauce | 1500 | 100.00 | 1386.62/s | 1386.62/s | 414.89ms | No | |
| tokensName | /tokens?limit=100&name=QUACK | 1500 | 99.97 | 3293.49/s | 3292.50/s | 229.16ms | No | |

V2
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| tokensName | /tokens?limit=100&name=bar | 1500 | 93.23 | 153.19/s | 142.82/s | 8801.91ms | No | |
| tokensName | /tokens?limit=100&name=sauce | 1500 | 99.88 | 337.50/s | 337.10/s | 4393.04ms | No | |
| tokensName | /tokens?limit=100&name=quack | 1500 | 99.88 | 305.27/s | 304.90/s | 4870.99ms | No | |

2024-07-22 18:27 UTC, steven-sheehy requested changes

2024-07-22 18:27 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        maxLength: 100
Add a minLength and enforce it

2024-07-22 21:15 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        minLength: 5
Probably this should be 3

2024-07-22 21:39 UTC, jnels124 commented on hedera-mirror-rest/api/v1/openapi.yml
> +        minLength: 5
I can change that but more characters would be better. Searching for things like bar is not super efficient and will use the token pk index instead. That is why the k6 results are worse for searching with bar.

2024-07-22 21:50 UTC, jnels124 commented on hedera-mirror-rest/api/v1/openapi.yml
> +        minLength: 5
With the other restrictions in place like no pagination and excluding use with other params, 3 should be fine.

2024-07-22 22:37 UTC, steven-sheehy approved these changes
LGTM

2024-07-23 00:55 UTC, jascks approved these changes
LGTM

2024-07-23 14:37 UTC, xin-hedera approved these changes
LGTM

2024-07-23 17:19 UTC, merged