Add additional validations for call against system account
hashgraph/hedera-mirror-node pull request #8797
Opened 2024-07-18 12:05 UTC by zhpetkov

**Description**:
Add validations in `AbstractEvmMessageCallProcessor` which checks the type of the account and value for the transaction - cannot send value to native precompile calls, since there are collisions with the system account and value will be transferred to the system account, which is undesired. The biggest part of the implementation is from Hedera Services. 

**Related issue(s)**: 

Fixes #7621

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-22 06:11 UTC, bilyana-gospodinova requested changes
Please add new tests that cover the changes added in `AbstractEvmMessageCallProcessor`.

2024-07-22 06:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/AbstractEvmMessageCallProcessor.java
> +    private final int RESERVED_HTS_SYSTEM_ACCOUNT = 359;
There is no need to define the constant again. It is available in `EvmHTSPrecompiledContract#EVM_HTS_PRECOMPILED_CONTRACT_ADDRESS`.

2024-07-22 06:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/AbstractEvmMessageCallProcessor.java
> +        if (!isNativePrecompile &&
Please leave a comment why we need this distinction between an HTS and a non-HTS address. I suppose the reason is that an HTS token create call can receive value.

2024-07-24 20:33 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorTest.java
> +        when(messageFrame.getCurrentOperation()).thenReturn(createOperation());
Test seems to pass with line 195 commented out. Can it be removed or is there something more that should be verified?

2024-07-24 20:33 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorTest.java
> +        when(messageFrame.getCurrentOperation()).thenReturn(createOperation());
Test seems to pass with line 178 commented out. Can it be removed or is there something more that should be verified?

2024-07-24 20:34 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorTest.java
> +        when(messageFrame.getCurrentOperation()).thenReturn(createOperation());
This seems to be the only line that uses `createOperation`. To reduce the lines of code, could `createOperation` be removed and replaced with a mock?

2024-07-26 20:22 UTC, steven-sheehy approved these changes
LGTM

2024-07-29 06:40 UTC, bilyana-gospodinova approved these changes
LGTM

2024-07-29 11:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorTest.java
> +    private static Operation createOperation() {
Probably obsolete method

2024-07-29 11:35 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-08-02 17:21 UTC, steven-sheehy approved these changes

2024-08-02 17:50 UTC, merged