Port REST specs to Java, phase 1
hashgraph/hedera-mirror-node pull request #8799
Opened 2024-07-18 15:06 UTC by jascks

**Description**:
To confidently be able to port over existing JavaScript REST APIs to Java, we need to ensure the existing spec tests continue to work against the newly converted API.

* Add a `RestSpecTest` that
  * Injects and uses a `RestClient` similar to `ControllerTest`
  * Can load JSON spec files from `hedera-mirror-rest-java/src/test/resources/specs` with arbitrary depths. For this phase 1 PR, a selected few spec files are choosen.
  * Model the spec JSON as a `RestSpec` POJO
  * For each spec, use `DomainBuilder` to create default and override with data from `setup` section and persist
  * Call the URLs and verify the response JSON and status codes
  * **Temporarily** add a `hedera-mirror-rest` test container to verify all specs pass against it

**Related issue(s)**:

Fixes #6810

**Notes for reviewer**:
This branch/PR is a step back from the branch `6810-port-rest-specs-to-java` which contains additional functionality regarding additional DB entity types for setup. That will be the basis for follow on work to build on this phase 1 PR.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-07-19 12:43 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +
The general flow of these entity builders is based on `integrationDomainOps.js` in the JS REST API. In this case, start with the `addAccount()` function. In order to match the API response body defined in a spec, the same defaults, customizations and post-processing need to occur.

JS can take liberties with JSON and the attribute types that Java cannot. Thus the last 'check and finalize' step may invoke `wrapper.get()` to inspect the entity built thus far, and based on that, but invoke further builder methods to adjust things as needed prior to persisting the final entity.

2024-07-19 12:47 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    private void setupDatabase(RestSpecNormalized normalizedRestSpec) {
This is a phase 1 implementation. Something more general to inspect the `SpectSetup` to determine the required database entities is planned.

2024-07-19 12:50 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/TokenAccountBuilder.java
> +class TokenAccountBuilder extends AbstractEntityBuilder {
Patterned after `integrationDomainUtils.js` function `addTokenAccount()`.

2024-07-19 12:56 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java
> +    PostgreSQLContainer<?> postgresqlOverride(Network postgresqlNetwork) {
For `RestSpecTest`, which sets `spring.main.allow-bean-definition-overriding=true`, this bean overrides that defined in `CommonTestConfiguration`. It is basically the same configuration, except this postgresql container is placed on a network so that the RS REST API container (below) can connect to it.

Doing this directly with the existing container in `CommonTestConfiguration` caused other integration tests to fail.

2024-07-22 19:48 UTC, steven-sheehy requested changes

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecTestNormalized.java
> +        return new SpecTestNormalized(urls, specTest.responseStatus(), specTest.responseJson());
It's possible, but unlikely we might have both url and urls populated. Either way, this solution reduces conditionals:

```suggestion
        return new SpecTestNormalized(specTest.getNormalizedUrls(), specTest.responseStatus(), specTest.responseJson());
```

Where this helper method is added to `SpecTest`:

```java
    public List<String> getNormalizedUrls() {
        var url = Stream.ofNullable(url);
        var urls = Stream.ofNullable(urls).flatMap(ArrayList::stream);
        return Stream.concat(url, urls).filter(StringUtils::hasText).toList();
    }
```

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecSetup.java
> +        List<Map<String, Object>> cryptoallowances,
```suggestion
        List<Map<String, Object>> cryptoAllowances,
```

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainWrapperImpl.java
revert

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    @Autowired
Mixing resource and autowired annotations. Prefer resource

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
There should be an ObjectMapper bean provided by Spring you can use, unless doing so causes issues.

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            new File("../hedera-mirror-rest/__tests__/specs/accounts/specific-id.json")
Use Path to construct for windows compatibility. Move common prefix to a shared static variable.

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    GenericContainer<?> jsRestApi;
private

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        log.info("setup - baseJsRestApiUrl: {}", baseJsRestApiUrl);
Should probably remove as it will get verbose

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            return;
Should either catch and re-throw or use sneaky throws so that we don't stop test without failing.

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        specDomainBuilder.addTokenAccounts(normalizedRestSpec.setup().tokenaccounts());
nit
```suggestion
        var setup = normalizedRestSpec.setup();
        specDomainBuilder.addAccounts(setup.accounts());
        specDomainBuilder.addTokenAccounts(setup.tokenaccounts());
```

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        var normalizedRestSpec = RestSpecNormalized.from(restSpec);
Consolidate logic related to loading specs to a single method.

```suggestion
        var restSpec = loadSpecs();
```

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +                var specResponseJson = specTest.responseJson().toString();
Why do we both loading `responseJson` as a JsonNode if we then convert it to string anyway? Is it possible to load it directly as a string?

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +                    log.warn("Failed to parse expected responseJson within spec file: {}", specFile, e);
Should fail the tests

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +@Component
Use `@Named`

2024-07-22 19:48 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
Why prototype? It doesn't seem to have any state.

2024-07-30 14:19 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/RestSpecNormalized.java
> +    public RestSpecNormalized {
The canonical constructor must have at least the visibility of the record itself, which must be `public` because it is referenced outside of the `model` package, namely `RestSpecTest`.

2024-07-30 17:32 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
Right! Thanks. Done.

2024-07-30 17:46 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +                var specResponseJson = specTest.responseJson().toString();
I was not able to deserialize the nested JSON to a `String` (Jackson `MistmatchedInputException`), and declaring that field as `Object` results in a number of nested lists and maps which is not easily converted to a string. `JsonNode` on the other hand, handles the job since the JSONAssert library is pretty flexible in parsing and doing comparisons.

Doing some more research, I ended up implementing `JsonAsStringDeserializer` and annotating the models to use that deserializer. In the end, that deserializer produces a `TreeNode` and converts it to a `String`, but at least the models don't have to convey a `JsonNode` going forward.

2024-07-30 18:18 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +                    log.warn("Failed to parse expected responseJson within spec file: {}", specFile, e);
Fail at what level though? This phase 1 implementation is hardcoded to run three existing specs, only the last of which has more than one URL, and thus API invocation.  When moving forward with a more real implementation that walks some directory hierarchy of spec files, there will be some number of files read and parsed, and one or more test cases per file. All being run as a single unit test (`@Test`).

In this method, if the object mapper fails to deserialize the spec file, then that needs to be reported, with testing moving on to the next file. Upon successful deserialization, each test case needs to be run and verified. A failure at that level needs to be reported, with testing proceeding to the next test case etc.

The code above required the try/catch because `JSONAssert.assertEquals()` will throw the checked `JSONException` if the provided `specResponseJson` fails to parse. That should not happen since the entire spec file did indeed parse to get to this point.

I can see this code needs to better deal with assertion failures (such as `assertThat()` for the response code, and in the future the response headers) and report such failures and continue testing rather than the JUnit level test method simply returning stopping further testing.

2024-07-30 18:40 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +                .autoRenewAccountId(null)
Gone

2024-07-30 18:40 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +                .createdTimestamp(null)
Done

2024-07-30 18:40 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +@Component
Done.

2024-07-30 18:40 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
Not sure why that's there. Gone.

2024-07-30 18:45 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecTestNormalized.java
> +    public SpecTestNormalized {
A record's canonical constructor must have visibility at least that of the record itself, which is used outside of this package.

2024-07-30 19:40 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        specDomainBuilder.addTokenAccounts(normalizedRestSpec.setup().tokenaccounts());
Good call. This method is destined to only get longer...  Done.

2024-07-30 19:41 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecTestNormalized.java
> +        return new SpecTestNormalized(urls, specTest.responseStatus(), specTest.responseJson());
Cool. I like it. Done with a slight modification.

2024-07-30 19:52 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +                }
I don't see `EntityRegistry`, but I did find `EntityMetadata` and `EntityMetadataRegistry`. They and `ColumnMetadata` are found in `com.hedera.mirror.importer.repository.upsert` which is in `importer`, not `common`.

They aren't referenced in too many places. Do you recommend I relocate the required classes to `common`?

2024-07-30 20:05 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +                }
Looking further, the reflection code above is used to access fluent entity builder methods, not setters on the entities themselves. That's the builder's job.

2024-07-30 21:22 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +        customizeWithSpec(wrapper, account);
Okay, I've undone this.

2024-07-31 21:06 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +    );
Done, at least for for those default converters above. Not yet sure how to incorporate the builder method specific converters since right at the start there are three different cases where `String -> byte[]` conversion needs to occur.

2024-07-31 21:21 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecSetup.java
> +        List<Map<String, Object>> cryptoallowances,
Good catch! Done.

2024-07-31 21:21 UTC, jascks commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainWrapperImpl.java
Done

2024-07-31 21:22 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            new File("../hedera-mirror-rest/__tests__/specs/accounts/specific-id.json")
Done.

2024-07-31 21:22 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    GenericContainer<?> jsRestApi;
Done

2024-07-31 21:22 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        log.info("setup - baseJsRestApiUrl: {}", baseJsRestApiUrl);
Done

2024-07-31 21:23 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            return;
I want to log that there is something funky about the spec file and move on to the next one.

2024-07-31 21:47 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            return;
Given either this phase 1 hardcoded list of three spec files, or a more full featured file system walk with filtering, within a single `@Test` method we are encountering spec JSON files, each of which must be loaded/parsed, DB prepared, and tests/urls run.

2024-08-01 02:23 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        var normalizedRestSpec = RestSpecNormalized.from(restSpec);
Using `@ParameterizedTest`, I have redone this logic.

2024-08-02 18:03 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +                }
Not sure what you mean by `used to access fluent entity builder methods, not setters on the entities themselves`. It is actually setters on the domain model as proven by the test in `EntityMetadataRegistryTest`:

```
                .satisfies(cm -> assertThat(cm.getGetter().apply(entity)).isEqualTo(entity.getAlias()))
                .satisfies(cm -> assertThatCode(() -> cm.getSetter().accept(entity, newValue))
                        .satisfies(d -> assertThat(entity.getAlias()).isEqualTo(newValue)));
```

2024-08-02 18:05 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/RestSpec.java
> +        JsonNode responseJson) {
We should still add it to the spec so we don't forget it. Not everything in the current spec is supported like matrix but it's still present.

2024-08-02 19:33 UTC, steven-sheehy requested changes

2024-08-02 19:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        specDomainBuilder.addTokenAccounts(setup.tokenAccounts());
As more get added, this method and SpecDomainBuilder will each have to change. It would be better to invert this logic so we can add new builders in isolation. Something like the below (though not sure about name `Persistence`):

```java

    public interface DomainPersistence {
        void persist(SpecSetup specSetup);
    }

    @Named
    @Primary
    @RequiredArgsConstructor
    class CompositeDomainPersistence implements DomainPersistence {
        private final Collection<DomainPersistence> persistences;

        public void persist(SpecSetup specSetup) {
            persistences.forEach(p -> p.persist(specSetup));
        }
    }

    @RequiredArgsConstructor
    abstract class AbstractDomainPersistence implements DomainPersistence {

        private final EntityManager entityManager;
        private final Function<SpecSetup, List<Map<String, Object>>> supplier;

        @Override
        public void persist(SpecSetup specSetup) {
            var entities = supplier.apply(specSetup);
            if (entities != null) {
                for (var entity : entities) {
                    entityManager.persist(build(entity));
                }
            }
        }

        abstract Object build(Map<String, Object> entity);
    }

    @Named
    class EntityPersistence extends AbstractDomainPersistence {
        EntityPersistence() {
            super(SpecSetup::accounts);
        }

        Object build(Map<String, Object> entity) {
        }
    }
```

2024-08-02 19:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +    private static final Object IGNORE_ATTRIBUTE_SIGNAL = new Object();
Is this and the IGNORE_CONVERTER used?

2024-08-02 19:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +            : value instanceof String valueStr ? EntityId.of(valueStr) : EntityId.of((Long)value);
We should be able to register a Spring `EntityIdConverter` to handle this and avoid mapping each field to use this.

2024-08-02 19:33 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +            "id", ENTITY_ID_CONVERTER,
id is a Long, not an EntityId. Think the wrong converter is registered

2024-08-02 21:26 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +                }
For example, in `AccountBuilder` I'm. utilizing `Entity.builder()` to set the default values for an account, and then providing that builder to `customizeWithSpec()` to further customize the account based on the spec JSON. This process involves invoking methods on that builder, not an account `Entity` instance.

So, while grok'ing a spec file, given the "num" attribute for an account object in the "accounts" array, I need to invoke `builder.num()`. I'm not currently invoking the Lombok generated `Entity.setNum()`. It looks like you'd prefer I did the latter.

2024-08-02 21:29 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +    private static final Object IGNORE_ATTRIBUTE_SIGNAL = new Object();
I admit it is not in this phase 1 PR. I will remove it.

2024-08-02 21:34 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +@EnableConfigurationProperties(value = RestJavaProperties.class)
Not in phase 1. I'm not even using the injected `RestJavaProperties`. I will remove it.

I don't see it enabled in the parent class, nor its parent class. I do see it enabled also in `ControllerTest`. Perhaps this should be done in the common parent `RestJavaIntegrationTest`, along with the injected field (protected)?

2024-08-02 23:22 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +@EnableConfigurationProperties(value = RestJavaProperties.class)
It shouldn't need to be manually enabled anywhere. Spring Boot will component scan for configuration properties and make them beans thanks to `@ConfigurationPropertiesScan`.

2024-08-02 23:31 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +                }
I understand what you're saying now. So we can change to not use builders and then we can use the registry. I think we can keep it as is for now.

2024-08-05 20:44 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAccountRepository.java
> +package com.hedera.mirror.restjava.repository;
Fixed.

2024-08-05 20:44 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAccountRepository.java
Done.

2024-08-05 20:44 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +@EnableConfigurationProperties(value = RestJavaProperties.class)
Removed, as well as the `properties` field.

2024-08-05 20:44 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    private static final Path REST_BASE_PATH = Path.of("..", "hedera-mirror-rest", "__tests__", "specs");
Fixed.

2024-08-05 20:44 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        baseJsRestApiUrl = "http://%s:%d".formatted(jsRestApi.getHost(), jsRestApi.getMappedPort(JS_REST_API_CONTAINER_PORT));
Done. Explicitly implemented constructor so that I can create immutable `RestClient`.

2024-08-05 20:45 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +@CustomLog
Removed.

2024-08-05 20:45 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/JsonAsStringDeserializer.java
> +public class JsonAsStringDeserializer extends JsonDeserializer<String> {
Done.

2024-08-05 20:45 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/RestSpec.java
> +        int responseStatus,
Done.

2024-08-05 21:27 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            for (var url : specTest.urls()) {
Looks like `@TestFactory` and `DynamicTest` have great potential. Investigating.

2024-08-06 22:02 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +@CustomLog
Deleted.

2024-08-06 22:02 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +        specDomainBuilder.addTokenAccounts(setup.tokenAccounts());
I took a bit of a different approach on the implementation.

2024-08-06 22:03 UTC, jascks commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAccountRepository.java
Test added.

2024-08-06 22:03 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/RestSpec.java
> +        int responseStatus,
Done.

2024-08-06 22:04 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +            for (var url : specTest.urls()) {
See new implementation utilizing `@TestFactory`, `DynamicTest` and `DynamicContainer`.

2024-08-07 14:05 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
> +    private void setupDatabase(RestSpecNormalized normalizedRestSpec) {
Implemented.

2024-08-07 15:20 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +            : value instanceof String valueStr ? EntityId.of(valueStr) : EntityId.of((Long)value);
Done. Note that spec JSON will sometimes specify an ID as a string, other times as a numeric value (being treated as a `Long`). Thus, I have created two converters to support both forms which deals with the logic in the above function.

2024-08-07 15:20 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +            "id", ENTITY_ID_CONVERTER,
True. The Spring converters introduced above handle both situations.

2024-08-07 20:24 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +    protected void customizeAndPersistEntity(Map<String, Object> account) {
I like it. Done!

2024-08-07 20:24 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +            builder.id(EntityId.of(entity.getShard(), entity.getRealm(), entity.getNum()).getId());
Done.

2024-08-08 19:05 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +            "id", ENTITY_ID_CONVERTER,
Done.

2024-08-09 19:00 UTC, steven-sheehy requested changes

2024-08-09 19:53 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromStringConverterTest.java
> +    @CsvSource({"1.2.3, 1.2.3", "0.0.100, 0.0.100"})
None that I can see, though there are a lot using "0.0.1001".

2024-08-09 20:03 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromLongConverterTest.java
> +    @CsvSource({"1, 0.0.1", "100, 0.0.100"})
I wondered about that, but how much do I need to repeat `EntityIdTest` vs. make sure code coverage passes? That class also tests for negative numbers,  values exceeding what's supported for encoding shard, realm etc. Testing for such failures requires dealing with `IllegalArgumentException` etc.

2024-08-09 20:17 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromStringConverterTest.java
> +    @CsvSource({"1.2.3, 1.2.3", "0.0.100, 0.0.100"})
Done.

2024-08-09 20:17 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +    private static final Object IGNORE_ATTRIBUTE_SIGNAL = new Object();
Persistent, isn't it? 😄 Gone finally!

2024-08-09 20:17 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
> +                .declineReward(Boolean.FALSE)
Done.

2024-08-09 20:17 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/TokenAccountBuilder.java
> +                .accountId(0L)
Done.

2024-08-09 20:39 UTC, steven-sheehy commented
Sonar notes some code smells

2024-08-09 21:01 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromLongConverterTest.java
> +    @CsvSource({"1, 0.0.1", "100, 0.0.100"})
Just null and empty string, as I said. It's not duplicating coverage. EntityId.of will throw an exception but this converter should probably just return null.

2024-08-12 15:44 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
> +            specEntities.forEach(specEntity -> transactionOperations.executeWithoutResult(t -> entityManager.persist(customizeEntity(specEntity))));
This is a nice improvement. I have implemented this, well with another step between customization and persistence to allow for final customization by the sub-class, which `integrationDomainOps.js` does a lot of on the REST side.

2024-08-12 15:44 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
> +    public void addSetupEntities(SpecSetup specSetup) {
Indeed. Done!

2024-08-12 15:45 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecEntityBuilder.java
> +public interface SpecEntityBuilder {
Once I implemented the aforementioned composite correctly, this interface is no longer needed. 😄

2024-08-12 15:49 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromLongConverterTest.java
> +    @CsvSource({"1, 0.0.1", "100, 0.0.100"})
Whoops. Should have refreshed sooner. Working on this still...

2024-08-12 16:45 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromLongConverterTest.java
> +    @CsvSource({"1, 0.0.1", "100, 0.0.100"})
Okay, I'm not completely feeling the joy of this regarding the `FromLong` converter, since there is no concept of empty string in this case. I can provide null, but that fails with NPE while unboxing in the converter itself as `EntityId` deals with a primitive `long`.

When such invalid input is encountered in a spec file, I think rather than returning null, an appropriate exception is in order to instruct the developer to fix the spec then and now.

2024-08-12 19:19 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-08-12 19:36 UTC, steven-sheehy approved these changes

2024-08-13 15:34 UTC, jnels124 approved these changes

2024-08-13 16:21 UTC, jascks commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromStringConverterTest.java
I don't think so. These tests are primarily to get code coverage for the converters and not extensively test `EntityId` itself. Also, here we test the possible  boundary conditions around null and empty (for strings anyway) possibly present within the spec JSON, and how the converters handle that differently from `EntityId`.  Any other circumstances where `EntityId` accepts the input or throws an exception are acceptable.

2024-08-13 19:47 UTC, merged