Fix potential exception with TokenRejectHandler tokenIds
hashgraph/hedera-mirror-node pull request #8824
Opened 2024-07-18 19:50 UTC by edwin-greene

**Description**:

- Removes the potential for an invalid TokenReject tokenId to throw an exception in TokenRejectTransactionHandler.
- Fixes RecordItemBuilder tokenReject to now include token transfers.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-07-18 22:28 UTC, steven-sheehy requested changes

2024-07-18 22:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +        tokenReject.getRejectionsList().forEach(rejection -> {
Why do we need this? The token ID is already added to `entity_transaction` in `EntityRecordItemListener.insertFungibleTokenTransfers()` from the transfer list in the record.

2024-07-18 22:28 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        }
Remove this and use `Builder.record(r -> r.addTokenTransferLists())`

2024-07-19 17:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +        tokenReject.getRejectionsList().forEach(rejection -> {
Thanks I double checked and you are right, it is not needed. I have removed it.

2024-07-19 17:49 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +        }
Thanks I have updated this

2024-07-19 17:53 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +    private final EntityProperties entityProperties;
Unused

2024-07-19 17:57 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
> +    private final EntityProperties entityProperties;
Got it, removed

2024-07-19 17:59 UTC, steven-sheehy approved these changes

2024-07-19 20:20 UTC, jascks approved these changes
LGTM

2024-07-19 20:22 UTC, mgoelswirlds approved these changes
LGTM

2024-07-19 20:30 UTC, xin-hedera approved these changes
LGTM

2024-07-19 20:59 UTC, merged