feat: Add TestWeb3jService
hashgraph/hedera-mirror-node pull request #8853
Opened 2024-07-23 11:50 UTC by bilyana-gospodinova

**Description**:
This PR adds the base TestWeb3jService from https://github.com/hashgraph/hedera-mirror-node/pull/8385. It is intended to be used in the refactored version of the integration tests.

2024-07-23 12:01 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        final var sender = new HederaEvmAccount(senderAddress);
This can be renamed as it is considered a code smell by the ci check.

2024-07-23 12:25 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        final var sender = new HederaEvmAccount(senderAddress);
Done

2024-07-23 19:21 UTC, steven-sheehy requested changes

2024-07-23 19:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/Web3jTestConfiguration.java
> +public class Web3jTestConfiguration {
Can also just make a static nested config class on `Web3IntegrationTest` so you don't have to import it anywhere.

2024-07-23 19:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +    private final Map<String, String> trxResMap = new HashMap<>();
```suggestion
    private final Map<String, String> transactionResults = new ConcurrentHashMap<>();
```

2024-07-23 19:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +            default -> throw new UnsupportedOperationException(request.getMethod());
```suggestion
            default -> throw new UnsupportedOperationException(method);
```

2024-07-23 19:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        var trxHex = generateTransactionHashHexEncoded(rawTransaction, credentials);
Rename this `trxHex` everywhere else too.

```suggestion
        var transactionHash = generateTransactionHashHexEncoded(rawTransaction, credentials);
```

2024-07-23 19:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +            RawTransaction rawTrxDecoded, String trxHex, Request request) {
```suggestion
            RawTransaction rawTransaction, String transactionHash, Request request) {
```

2024-07-23 19:21 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        trxReceipt.setContractAddress(trxResMap.get(trxHash));
```suggestion
        final var transactionReceipt = new TransactionReceipt();
        transactionReceipt.setTransactionHash(trxHash);
        transactionReceipt.setContractAddress(trxResMap.get(trxHash));
```

2024-07-24 06:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/Web3jTestConfiguration.java
> +public class Web3jTestConfiguration {
Done

2024-07-24 06:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +    private final Map<String, String> trxResMap = new HashMap<>();
Renamed

2024-07-24 06:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +            default -> throw new UnsupportedOperationException(request.getMethod());
Comment addressed.

2024-07-24 06:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        var trxHex = generateTransactionHashHexEncoded(rawTransaction, credentials);
Renamed

2024-07-24 06:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +            RawTransaction rawTrxDecoded, String trxHex, Request request) {
Renamed

2024-07-24 06:55 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        trxReceipt.setContractAddress(trxResMap.get(trxHash));
Renamed

2024-07-24 17:50 UTC, steven-sheehy approved these changes

2024-07-24 17:51 UTC, merged