HIP-904 Add support for Token Airdrop
hashgraph/hedera-mirror-node pull request #8856
Opened 2024-07-23 18:55 UTC by edwin-greene

**Description**:

- Adds Importer support for Token Airdrop, Token Cancel Airdrop transactions.
- Adds `token_airdrop` and `token_airdrop_history` tables.

**Related issue(s)**:

Fixes #8275 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-07-24 21:00 UTC, edwin-greene commented on hedera-mirror-rosetta/app/domain/types/constants.go
> +	60: "TOKENCLAIMAIRDROP",
Still need to update the protobufs-go version once it is available

2024-07-24 21:09 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +    );
Added the temp table here. If added to `R__1_temp_tables` it caused some migration tests to fail as they would attempt to run the temp tables migration at a point in time prior to the creation of the `token_airdrop` table.

2024-07-29 15:48 UTC, xin-hedera requested changes

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean tokenAirdrops = false;
is there concern to enable it by default?

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (entityProperties.getPersist().isTokenAirdrops()) {
We should implement `PersistProperties.isTokenAirdrops` as `tokens && airdrops`

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateAirdropTransactionHandler.java
> +    protected void doUpdateTransaction(RecordItem recordItem, TokenAirdropStateEnum state) {
should directly pass the pending aidrop list from the tx body, instead of getting the matching transaction body depending on the state

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +    );
add a newline at the end of the file

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +    on token_airdrop_history using gist (timestamp_range);
the index name doesn't match the columns in the index

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +select create_distributed_table('token_airdrop_history', 'token_id', colocate_with => 'token_airdrop');
don't think looking airdops by token id is the most important type of query. looking for tokens airdropped by a sender, or airdrops received by a receiver should be much more common.

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +                    case when coalesce(state, e_state) = ''PENDING'' then coalesce(e_{0}, 0) + coalesce({0}, 0)
don't think we need to accumulate the amount at all

2024-07-29 15:48 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
don't think this is needed

2024-07-29 15:56 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +    private long amount;
```suggestion
    private Long amount;
```

so for NFT airdrop, the value is set to `NULL`

2024-07-29 15:56 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +        private long serialNumber;
```suggestion
        private Long serialNumber;
```

2024-07-29 15:56 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean tokenAirdrops = false;
also document it in configuration.md

2024-07-30 19:39 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> + * Copyright (C) 2019-2024 Hedera Hashgraph, LLC
Thanks I have updated these to only have 2024.

2024-07-30 19:40 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +    private long serialNumber;
Left this as a long for the moment because of a problem with null values for composite ids.

2024-07-30 19:41 UTC, edwin-greene commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +            builder.amount(0L).serialNumber(number());
Got it this has been removed.

2024-07-30 19:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        if (entityProperties.getPersist().isTokenAirdrops()) {
Thanks I have updated this.

2024-07-30 19:41 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateAirdropTransactionHandler.java
> +    protected void doUpdateTransaction(RecordItem recordItem, TokenAirdropStateEnum state) {
Good idea, I have fixed this up.

2024-07-30 19:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +    );
Got it.

2024-07-30 19:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +    on token_airdrop_history using gist (timestamp_range);
Thanks I have corrected it

2024-07-30 19:42 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +select create_distributed_table('token_airdrop_history', 'token_id', colocate_with => 'token_airdrop');
Thanks I have changed it to receiver.

2024-07-30 19:46 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +                    case when coalesce(state, e_state) = ''PENDING'' then coalesce(e_{0}, 0) + coalesce({0}, 0)
I've updated it to remove the summation. I found that a coalesce was still needed as an update in state (from pending to canceled or claimed) will only contain a pendingAirdropId in the record file and not a pendingAirdropAmount. Since the amount is not included the original amount would get updated to null on upsert instead of retaining its original value.

2024-07-30 19:46 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        }
Thanks I have removed the summation.

2024-07-30 19:47 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +    private long amount;
Got it I have changed amount to Long.

2024-07-30 19:47 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +        private long serialNumber;
Because of a problem with composite Ids containing nullable elements I have left this as a long.

2024-07-30 19:50 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean tokenAirdrops = false;
I believe that it is a temporary flag, to coordinate the token airdrops release with services. It should be removed after the full token airdrops solution is released.

2024-07-31 15:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAirdropRepository.java
> +public interface TokenAirdropRepository
`TokenAirdropRepository` shouldn't implement `RetentionRepository` since the rows in the table is always valid from a point in the past to any point in the future (forever). In other words, `upper(timestamp_range) <= ?1` will always be false.

2024-07-31 15:42 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('PENDING', 'CANCELLED', 'CLAIMED');
better to order the same way as in the java enum class

2024-07-31 18:07 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAirdropRepository.java
> +public interface TokenAirdropRepository
Thanks I have removed RetentionRepository.

2024-07-31 18:07 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('PENDING', 'CANCELLED', 'CLAIMED');
Got it I have reordered them.

2024-08-01 16:16 UTC, jnels124 approved these changes
LGTM

2024-08-01 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('CANCELLED', 'CLAIMED', 'PENDING');
version should be 1.99.0

2024-08-01 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('PENDING', 'CANCELLED', 'CLAIMED');
2.4.0

2024-08-01 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    @MethodSource("provideAirdrops")
nit, don't think you need `@MethodSource`
can do @CsvSource, e.g.
```
    @CsvSource(textBlock = """
            CANCELLED, 1
            CANCELLED, 2
            """)
```

2024-08-01 17:39 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TokenAirdropRepositoryTest.java
> +                jdbcOperations.query("select * from token_airdrop_history", ROW_MAPPER);
nit, should be able to just use `findHistory(Class<T> historyClass)`

2024-08-01 19:55 UTC, jnels124 commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('PENDING', 'CANCELLED', 'CLAIMED');
version may depend on #8908

2024-08-01 20:23 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('PENDING', 'CANCELLED', 'CLAIMED');
Yes. Since the PR #8908 would need to go in 0.111.0 to match 0.53.0 release.

2024-08-01 20:28 UTC, mgoelswirlds reviewed
It LGTM but will wait to approve till the outstanding comments are handled.

2024-08-01 21:05 UTC, edwin-greene commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractTokenAirdrop.java
> +    @UpsertColumn(coalesce = "coalesce({0}, e_{0})")
Got it, I have removed it.

2024-08-01 21:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +create index if not exists token_airdrop_history__token_serial_lower_timestamp
Thanks I've updated it.

2024-08-01 21:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('CANCELLED', 'CLAIMED', 'PENDING');
I made it 1.99.1 as a 1.99.0 is in the DAB PR.

2024-08-01 21:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.3__add_token_airdrop.sql
> +create type airdrop_state as enum ('PENDING', 'CANCELLED', 'CLAIMED');
I've updated it to 2.4.1

2024-08-01 21:06 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +    @MethodSource("provideAirdrops")
Thanks I have updated it.

2024-08-01 21:06 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TokenAirdropRepositoryTest.java
> +                jdbcOperations.query("select * from token_airdrop_history", ROW_MAPPER);
Sounds good I have switched it to findHistory.

2024-08-02 21:51 UTC, xin-hedera approved these changes
LGTM

still need to coordinate to either change the sql migration version or merge the PRs in correct order

2024-08-16 22:14 UTC, steven-sheehy requested changes

2024-08-16 22:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public Builder<TokenClaimAirdropTransactionBody.Builder> tokenClaimAirdrop(PendingAirdropId pendingAirdropId) {
We should have zero-arg methods to create each transaction type. It should take care of generating a typical pending airdrop id. Any customization to add/remove/update those airdrops should be done by the caller. These methods are used by `RecordFileBuilder` via reflection.

```suggestion
    public Builder<TokenCancelAirdropTransactionBody.Builder> tokenCancelAirdrop() {
        var transactionBody = ...
        return new Builder<>(TransactionType.TOKENCANCELAIRDROP, transactionBody);
    }

    public Builder<TokenClaimAirdropTransactionBody.Builder> tokenClaimAirdrop() {
```

2024-08-16 22:14 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                        .build());
The account ids placed into the record should correspond to the account IDs in the body, right? Here we're generating new random IDs.

2024-08-19 11:10 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            current.setAmount(previous.getAmount());
Does this mean that if we have:
- previous -> TokenAirdrop - PENDING with value 100 for example

we might have:
- current -> TokenAirdrop - CANCEL/CLAIMED with value 100, so that we know what amount we have cancelled/claimed?

2024-08-19 11:16 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +call create_temp_table_safe('token_airdrop', 'receiver_account_id', 'sender_account_id', 'serial_number', 'token_id');
Isn't the `amount` column  missing?

2024-08-29 15:01 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/constants.go
> +	60: "TOKENCLAIMAIRDROP",
this comment is no longer relevant

2024-08-29 15:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +call create_temp_table_safe('token_airdrop', 'receiver_account_id', 'sender_account_id', 'serial_number', 'token_id');
the columns passed to this function is used to create the unique index the importer upsert logic relies on to detect conflict.

The unique index of the original table doesn't include the `amount` column.

2024-08-29 20:10 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            current.setAmount(previous.getAmount());
A recordFile could contain one recordItem that is the airdrop (it contains the amount), and then a second recordItem that is the claim (or cancel). The second one will only have the pendingAirdropId. It will not contain the pendingAirdropAmount. So that is why the two are merged in this manner at this point.

2024-08-30 13:47 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +                        .build());
Thanks, I have updated this. In the new version there is a single sender and two receivers. One receiver in the transfer, and a second receiver that receives the pending airdrop.

2024-08-30 13:47 UTC, edwin-greene commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
> +    public Builder<TokenClaimAirdropTransactionBody.Builder> tokenClaimAirdrop(PendingAirdropId pendingAirdropId) {
Thanks I have updated these.

2024-08-30 13:48 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.100.0__add_token_airdrop.sql
> +    amount              bigint,
Good idea, I have added tests to the EntityRecordItemListenerToken tests and to the SqlEntityListener test.

2024-08-30 13:48 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAirdropHistoryRepository.java
> +    @Query(value = "delete from token_airdrop_history where upper(timestamp_range) <= ?1", nativeQuery = true)
Thanks I have updated this.

2024-08-30 13:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateAirdropTransactionHandler.java
> +            return entityIdService.lookup(pendingAirdropId.getReceiverId()).orElse(EntityId.EMPTY);
Thanks I have removed this method.

2024-08-30 13:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCancelAirdropTransactionHandler.java
> +        return tokenUpdateAirdropTransactionHandler.getEntity(pendingAirdropIds);
Great idea! I have updated it with these changes.

2024-08-30 13:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCancelAirdropTransactionHandler.java
> +    private final TokenUpdateAirdropTransactionHandler tokenUpdateAirdropTransactionHandler;
Thanks this has been updated.

2024-08-30 13:49 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
> +        private boolean tokenAirdrops = false;
Sounds good I have added the flag there.

2024-08-30 13:50 UTC, edwin-greene commented on docs/checklist/feature.md
> +## GraphQL API
Thanks I have sorted it.

2024-08-30 16:56 UTC, steven-sheehy requested changes

2024-08-30 16:56 UTC, steven-sheehy commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.tokenAirdrops`              | false                                                | Persist token airdrop data to the database
We should adjust the default to true now that we're merging later.

2024-08-30 16:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenClaimAirdropTransactionHandler.java
> +    }
We can avoid needing to override this method if we pass enum and extractor to constructor and store in parent. Or alternatively create abstract methods that return them.

2024-08-30 19:39 UTC, edwin-greene commented on docs/configuration.md
> +| `hedera.mirror.importer.parser.record.entity.persist.tokenAirdrops`              | false                                                | Persist token airdrop data to the database
Sounds good I have updated it to true.

2024-08-30 19:39 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenClaimAirdropTransactionHandler.java
> +    }
Got it, I have updated it and added those items to the constructor.

2024-08-30 19:45 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAirdropTransactionHandler.java
> +                    entityIdService.lookup(pendingAirdropId.getReceiverId()).orElse(EntityId.EMPTY);
Why do we need to run IDs from the record through the lookup service? Did services say there is some exception to the rule that they must be shard.realm.num?

2024-09-02 14:52 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +call create_temp_table_safe('token_airdrop', 'receiver_account_id', 'sender_account_id', 'serial_number', 'token_id');
Thank you for the clarification!

2024-09-02 14:53 UTC, IvanKavaldzhiev commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +            current.setAmount(previous.getAmount());
Thanks for clarifying!

2024-09-03 19:05 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenAirdropTransactionHandler.java
> +                    entityIdService.lookup(pendingAirdropId.getReceiverId()).orElse(EntityId.EMPTY);
Got it, this lookup has been removed.

2024-09-03 19:30 UTC, steven-sheehy approved these changes
LGTM

2024-09-03 20:28 UTC, xin-hedera approved these changes
LGTM

2024-09-03 20:29 UTC, merged