8782 - Add Acceptance tests for tokenReject transasction
hashgraph/hedera-mirror-node pull request #8862
Opened 2024-07-24 12:47 UTC by nickeynikolovv

**Description**:

**Related issue(s)**:

Fixes #8782 

**Notes for reviewer**:
This PR depends on Hedera JAVA SDK version v.2.36.0 which is not yet updated in hedera-mirror-node repo

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-24 19:24 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        TokenRejectTransaction tokenRejectTransaction =
Can replace `TokenRejectTransaction` with `var`.

2024-07-24 19:24 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        TokenRejectTransaction tokenRejectTransaction =
Can replace `TokenRejectTransaction` with `var`.

2024-07-24 19:24 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +import com.hedera.hashgraph.sdk.*;
Revert wildcard

2024-07-24 19:24 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private List<NftId> NonFungibleTokenIds = new ArrayList<>();
Convert names to camelCase and then change the second one to `nftTokenIds` for easier searching for objects related to nfts.

2024-07-24 19:25 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        return null;
Can simplify: 
```suggestion
        return switch (accountId) {
            case ALICE -> accountClient.getAccount(AccountNameEnum.ALICE);
            case BOB -> accountClient.getAccount(AccountNameEnum.BOB);
            case CAROL -> accountClient.getAccount(AccountNameEnum.CAROL);
            case DAVE -> accountClient.getAccount(AccountNameEnum.DAVE);
            case OPERATOR -> accountClient.getAccount(AccountNameEnum.OPERATOR);
            default -> null;
        };
```

2024-07-25 11:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +import com.hedera.hashgraph.sdk.proto.TokenRejectTransactionBodyOrBuilder;
Fixed

2024-07-25 11:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        return null;
Fixed

2024-07-25 11:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +import com.hedera.hashgraph.sdk.*;
Fixed

2024-07-25 11:08 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private List<NftId> NonFungibleTokenIds = new ArrayList<>();
Fixed

2024-07-26 13:29 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private List<NftId> NonFungibleTokenIds = new ArrayList<>();
renamed NonFungibleTokenIds to nftTokenIds as well

2024-07-26 14:13 UTC, edwin-greene commented
Looks good, can you fix the Sonarcloud Issues? Just a variable rename and using .isZero().

2024-07-26 15:10 UTC, steven-sheehy requested changes

2024-07-26 15:10 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse rejectFungibleToken(List<TokenId> tokenIds, AccountId ownerId, PrivateKey privateKey, ExpandedAccountId payer) {
If owner is set, which we do, then it must sign the transaction. Carol is also paying for the transaction so there's no need to pass 3 variables for carol when a single will suffice.

```suggestion
    public NetworkTransactionResponse rejectFungibleToken(List<TokenId> tokenIds, ExpandedAccountId owner) {
```

2024-07-26 15:10 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse rejectNonFungibleToken(List<NftId> nftIds, AccountId ownerId, PrivateKey privateKey, ExpandedAccountId payer) {
```suggestion
    public NetworkTransactionResponse rejectNonFungibleToken(List<NftId> nftIds, ExpandedAccountId owner) {
```

2024-07-26 15:10 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                tokenRejectTransaction, privateKey == null ? null : KeyList.of(privateKey), payer);
I don't think having Carol pay is necessary for our tests. We can make the operator pay which has more funds and simplifies the setup. Same for other.
```suggestion
        var response = executeTransactionAndRetrieveReceipt(
                tokenRejectTransaction, privateKey == null ? null : KeyList.of(privateKey));
```

2024-07-26 15:10 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        var carolPayer = accountClient.getAccount(accountNameEnum);
Same comment as above about getAccount and not flattening

2024-07-26 15:10 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        };
Remove this method as it duplicates `accountClient.getAccount(enum)`. Just call AccountClient directly

2024-07-29 11:42 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        return new TokenRejectTransaction().setNftIds(nftIds).setTransactionMemo(getMemo("Reject NFT"));
Helper method not needed

2024-07-29 14:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        return new TokenRejectTransaction().setNftIds(nftIds).setTransactionMemo(getMemo("Reject NFT"));
Removed

2024-07-29 14:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        };
fixed

2024-07-29 14:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        var carolPayer = accountClient.getAccount(accountNameEnum);
fixed

2024-07-29 14:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                tokenRejectTransaction, privateKey == null ? null : KeyList.of(privateKey), payer);
fixed

2024-07-29 14:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse rejectNonFungibleToken(List<NftId> nftIds, AccountId ownerId, PrivateKey privateKey, ExpandedAccountId payer) {
fixed

2024-07-29 14:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse rejectFungibleToken(List<TokenId> tokenIds, AccountId ownerId, PrivateKey privateKey, ExpandedAccountId payer) {
fixed

2024-07-29 14:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private List<NftId> nftTokenIds = new ArrayList<>();
fixed

2024-07-29 14:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertNotNull(networkTransactionResponse.getReceipt());
fixed

2024-07-29 14:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                getFungibleTokenRejectTransaction(tokenIds).setOwnerId(ownerId).setTransactionMemo(getMemo("Reject Fungible token"));
fixed

2024-07-29 14:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +
fixed

2024-07-29 14:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    }
fixed

2024-07-29 14:06 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                ownerId);
fixed

2024-07-29 14:07 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                ownerId);
fixed

2024-07-29 15:36 UTC, jascks commented
Dependabot PR (#8887) updating us to Java SDK 2.36.0 was just merged.

2024-08-01 20:22 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-08-01 20:30 UTC, edwin-greene approved these changes
Looks good

2024-08-01 21:03 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(getTokenBalance(treasury, tokenId)).isEqualTo(startingBalanceTreasury + amount);
won't the balance checks be flaky without checking against mirrornode using the transaction id, or auto retry?

2024-08-01 21:06 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(getTokenBalance(treasury, tokenId)).isEqualTo(startingBalanceTreasury + amount);
we do check the transaction using mirrornode rest api in getTokenBalance -> verifyTransactions, however I believe we still need the `@RetryAsserts` on the top level function

2024-08-01 23:28 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(getTokenBalance(treasury, tokenId)).isEqualTo(startingBalanceTreasury + amount);
Added retry

2024-08-02 14:26 UTC, jascks approved these changes
Looks good. `token.feature` passed for me in `previewnet`.

2024-08-02 15:03 UTC, edwin-greene approved these changes

2024-08-02 16:29 UTC, merged