Handling timeout exception for monitor UNKNOWN error
hashgraph/hedera-mirror-node pull request #8876
Opened 2024-07-26 15:26 UTC by mgoelswirlds

**Description**:

Handling timeout exception for monitor UNKNOWN error

This PR modifies 
* Looks for timeout exception in ClusterHealthIndicator.

**Related issue(s)**:

Fixes #8762

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-29 17:15 UTC, jascks submitted a review, later dismissed
LGTM

2024-08-01 17:57 UTC, jnels124 approved these changes
LGTM

2024-08-01 18:20 UTC, steven-sheehy requested changes

2024-08-01 18:20 UTC, steven-sheehy commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ClusterHealthIndicator.java
> +                            || ExceptionUtils.getRootCause(e) instanceof TimeoutException) {
```suggestion
                    var rootCause = ExceptionUtils.getRootCause(e);
                    if (rootCause instanceof ConnectException || rootCause instanceof TimeoutException) {
```

2024-08-01 18:20 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
> +        when(restApiClient.getNetworkStakeStatusCode()).thenReturn(Mono.error(exception));
This doesn't actually test the flux `timeout(5)` is hit. Instead it just fakes a different timeout exception. We should use virtual time and have restApiClient take longer than 5 virtual seconds.

2024-08-01 21:36 UTC, xin-hedera commented
was able to reproduce it to it throws a `java.util.concurrent.TimeoutException` exception, though there are changes requested.

2024-08-02 21:06 UTC, jascks commented on hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ClusterHealthIndicator.java
> +                            || ExceptionUtils.getRootCause(e) instanceof TimeoutException) {
Done

2024-08-02 21:06 UTC, jascks commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
> +        when(restApiClient.getNetworkStakeStatusCode()).thenReturn(Mono.error(exception));
Done

2024-08-02 21:12 UTC, steven-sheehy commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
> +    private static final Duration WAIT = Duration.ofSeconds(10L);
Unused

2024-08-02 21:17 UTC, jascks commented on hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
> +    private static final Duration WAIT = Duration.ofSeconds(10L);
So close... Done!

2024-08-02 21:44 UTC, xin-hedera approved these changes
LGTM

2024-08-02 23:17 UTC, steven-sheehy approved these changes

2024-08-02 23:18 UTC, merged