HIP-869 Adding admin_key for the dynamic address book
hashgraph/hedera-mirror-node pull request #8908
Opened 2024-07-30 19:01 UTC by mgoelswirlds

**Description**:

This PR adds a new entity table `NODE` to capture Node transactions.

This PR modifies:

* Adds a `Node` and `NodeHistory` table to capture Node transactions in order to implement HIP-869 for mirror node.

**Related issue(s)**:

Fixes #8680

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-30 20:12 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.0__add_node.sql
> +drop table if exists ${tempSchema}.node_temp;
Adding this and the following lines in temporary , till we decide what to do for entire MON.
Both V1 and V2

2024-08-01 16:29 UTC, xin-hedera requested changes

2024-08-01 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchUpserterTest.java
> +        var node = List.of(node1, node2, node3);
`var` for consistency

and rename the list of node to `nodes` since it's a bit confusing

2024-08-01 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +        var expectedNode = getExpectedNode(recordItem);
need another test case for node update without changing admin key

2024-08-01 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandler.java
> +        var nodeCreate = recordItem.getTransactionBody().getNodeCreate();
check if transaction is successful

2024-08-01 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +        long consensusTimestamp = recordItem.getConsensusTimestamp();
check if transaction is successful

2024-08-01 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandler.java
> +        var nodeUpdate = recordItem.getTransactionBody().getNodeUpdate();
check if transaction is successful

2024-08-01 16:29 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
> +    @Disabled("Since this handler persists data for unsuccessful transactions & has tests for that")
where did it test unsuccessful transaction?

2024-08-01 17:54 UTC, mgoelswirlds commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
> +                .createdTimestamp(timestamp())
changed it.

2024-08-01 18:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
> +call create_temp_table_safe('token_transfer', 'token_id');
remove it, believe this is a oneoff error when merging changes from `main`

```suggestion
```

2024-08-01 18:23 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/R__02_temp_table_distribution.sql
> +call create_distributed_table_safe('node_temp', 'node_id', 'node');
remove this too since we shouldn't distribute it

```suggestion
```

2024-08-01 18:39 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +        long consensusTimestamp = recordItem.getConsensusTimestamp();
I need to still store the transaction information, but will add the check for parseNode.

2024-08-01 18:45 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
> +    @Disabled("Since this handler persists data for unsuccessful transactions & has tests for that")
In the parent test class there was a test.

2024-08-01 20:10 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
> +    @Disabled("Since this handler persists data for unsuccessful transactions & has tests for that")
I'm confused, because this specific test case was disabled by `@Disabled` for no good reason.

2024-08-01 20:17 UTC, mgoelswirlds commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
> +    @Disabled("Since this handler persists data for unsuccessful transactions & has tests for that")
updateTransactionUnsuccessful() would fail in the parent class since we were not returning for a failed transaction earlier. That's why I had to override and disable this particular test. Now that I do fail in the transactionHandler in case of a failed transaction , this is no longer relevant.

2024-08-01 20:30 UTC, xin-hedera requested changes

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractNode.java
> +    @jakarta.persistence.Id
nit, since there is no longer name clash with the deleted `Id` class

```suggestion
    @Id
```

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandler.java
> +        var nodeCreate = recordItem.getTransactionBody().getNodeCreate();
it looks more integrated with the `isSuccessful()` check inside `parseNode`

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractNode.java
> +    private long createdTimestamp;
this needs to be `Long` to make upsert of a partial update object to work

```suggestion
    private Long createdTimestamp;
```

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +        expectedNode.setCreatedTimestamp(0);
remove it after changing the type to `Long`, the non-primitive equivalent
```suggestion
```

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +                recordItem.getTransactionBody().getNodeUpdate().getAdminKey().toByteArray());
test function says without admin key update, and here it expects admin key set

There is a common issue for both `nodeUpdate` and `nodeUpdateWithoutAdminKeyUpdate`, that we should first insert a row for a node to the db using `domainiBuilder.node().persist()`, and then ingest a node update tx for the same node to verify that

- for the update with admin key change, the new admin key is persisted to `node` table, and there is a historical row with the old admin key in `node_history`
- for the update without admin key change, that the admin key in `node` table remains the same, and there is a historical row in `node_history`

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandlerTest.java
> +                .returns(isPersist, Node::isDeleted)));
the logic here is really bizarre. If you don't like the idea of splitting it to two test cases, I'd rather have an explicit if / else to assert the expected result

```java
  if (isPersist) {
    // assert that entityListener.onNode is called once with matching Node object
  } else {
    // assert that entityListener.onNode is not called at all
  }
```

2024-08-01 20:30 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandlerTest.java
> +        verify(entityListener, times(BooleanUtils.toInteger(isPersist))).onNode(assertArg(t -> assertThat(t)
same comment as in the other handler test

2024-08-01 21:00 UTC, steven-sheehy requested changes

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandler.java
> +                .nodeId(recordItem.getTransactionRecord().getReceipt().getNodeId())
Even though it's the default, would be clearer to explicitly set deleted to false here.

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +        }
It would be clearer if the success check is inside the parseNode methods

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +                .nodeId(recordItem.getTransactionRecord().getReceipt().getNodeId())
Double check they will be populating this in the receipt for update and deletes. To be safe, we can get it from body.

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandler.java
> +        node.setNodeId(recordItem.getTransactionRecord().getReceipt().getNodeId());
We should set deleted to false

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractNode.java
> +@Upsertable(history = true, skipPartialUpdate = true)
I think it would be useful to have partial updates. That way mirror nodes that start up now and miss node create can self correct on next node update. We should remove skipPartialUpdate so it reverts to false. Then change schema to allow null for created_timestamp and use `Long`.

Add a partial update test to SqlEntityListenerTest.

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        previous.setTimestampUpper(current.getTimestampLower());
Missing logic here to merge created timestamp and admin key. Also means missing test coverage for updates in single record file.

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +        var nodeCreate2 = domainBuilder.node().get();
Why do we have a second node create? For this history test we should only test a single node ID. We just need a create, update and a delete for a single node ID where each of those occurs at different commit boundaries. You're welcome to add a separate test for multi-node ID scenario that doesn't use the commitIndex concept.

2024-08-01 21:00 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
> +                .deleted(true)
We should not have createdTimestamp populated for updates and deletes, while still verifying they're populated in db.

2024-08-02 02:39 UTC, mgoelswirlds commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +                .nodeId(recordItem.getTransactionRecord().getReceipt().getNodeId())
I have asked Iris about this. Will confirm as soon as I hear back.

2024-08-02 16:31 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +                .nodeId(recordItem.getTransactionRecord().getReceipt().getNodeId())
At least in the proto it says it will be set for delete and update. https://github.com/hashgraph/hedera-protobufs/blob/a644ad4e1bc9c75de92f6d5f9d772100fb8c0ff4/services/transaction_receipt.proto#L175

2024-08-02 16:35 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
> +        }
Now there's duplicate success checks...

2024-08-02 19:59 UTC, jnels124 commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        previous.setTimestampUpper(current.getTimestampLower());
actually I guess a delete coming in shouldn't wipe out admin key nevermind

2024-08-02 20:03 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +        previous.setTimestampUpper(current.getTimestampLower());
We need to merge. e.g.,suppose these happen in the same record file,

- node update set a new admin key
- node update set some field other than admin key

The history row from the first update should be fine with the correct updated admin key.

the row in node table however will end up with the old admin key since the upsert does a coelesce of null and the admin key in the table before ingesting the record file

2024-08-05 16:09 UTC, jascks commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractNode.java
> +@Upsertable(history = true)
I see this convo is resolved, but I don't see that suggested change was adopted. Was there an offline discussion or did this get reverted by accident?

2024-08-05 16:21 UTC, xin-hedera requested changes

2024-08-05 16:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +        var recordItem = recordItemBuilder.nodeUpdate().build();
the transaction body should have admin key cleared.

2024-08-05 16:21 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
> +                .persist();
should either do `domainBuilder.node().customize(...).persist()` or use `recordItemBuilder.key()`

2024-08-05 18:12 UTC, jascks approved these changes
LGTM

2024-08-05 18:21 UTC, xin-hedera approved these changes
LGTM

2024-08-05 18:21 UTC, steven-sheehy approved these changes
LGTM

2024-08-05 19:41 UTC, merged