Refactor ContractCallDynamicCallsTest
hashgraph/hedera-mirror-node pull request #8912
Opened 2024-08-01 08:14 UTC by bilyana-gospodinova

**Description**:
With this PR the `ContractCallDynamicCallsTest` integration test is refactored using the web3j plugin and the big enum is now replaced with multiple junit tests so that it is easier to debug a particular scenario. This way also the number of persisted entities per test is reduced significantly and now we persist only the ones that are needed in the particular test. With this implementation the execution time of the `ContractCallDynamicCallsTest` is reduced 5 times (from about 50 seconds to 9-10 seconds, tested locally).

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/8449

2024-08-01 12:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +        return accountPersist(TREASURY_ADDRESS);
Try to adapt tests to work with dynamic data as much as possible, e.g. not relying on hardcoded addresses. An exclusion might be specific aliases, that are expected as return result for example. I believe a lot of these utility methods can be removed in favour of dynamically creating data via `domainBuilder` inside the tests.

Even if we have repetitions and can extract common `domainBuilder` constructs, they should be again dynamic and we shouldn't pass static constants as `Address` or `EntityId`

2024-08-01 12:44 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +                        .alias(toEvmAddress(accountEntityId))
If we don't expect particular `alias` to be used, we can leave the `domainBuilder` to randomly generate one.

2024-08-01 12:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +                .persist();
In none of the tests in this class we have asserts for concrete values as an output. The tests are mainly testing complex nested precompile calls and the correctness of their execution in combination.

Thus, I think we can remove a lot of the utility methods and especially the parameters that set specific static values to be added into the entities built with the domainBuilder. I don't think we need to rely on hardcoded constants but let most of the fields to be auto generated.

In this concrete example if we don't pass:
```
.spender(spenderEntityId.getId())
.owner(ownerEntityId.getId())
.payerAccountId(ownerEntityId),
```
                        
then the `spender`, `owner` and `payerAccountId` will be automatically generated and populated by the `domainBuilder`.

2024-08-01 13:38 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +            rawTransaction = copyTransactionWithReceiver(transaction, receiver);
The method is removed. It seems that `toString` did not work as expected so the RLP decoding used to fail. We still need to convert the `Transaction` to `RawTransaction` though.

2024-08-01 13:40 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +                        .alias(toEvmAddress(accountEntityId))
Comment addressed. Thanks.

2024-08-01 14:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +                .persist();
I see, if it's because of the needed relations between entities we should be good.

2024-08-01 15:30 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +            rawTransaction = copyTransactionWithReceiver(transaction, receiver);
As pointed out by @IvanKavaldzhiev the conversion is not needed at all. I cleared the implementation that is not needed.

2024-08-01 16:47 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +                "burnTokenGetTotalSupplyAndBalanceOfTreasury",
Can you change the name to something like `burnNft`? It has the same name as `BURN_FUNGIBLE_TOKEN`

2024-08-01 17:00 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +                "burnTokenGetTotalSupplyAndBalanceOfTreasury",
I just moved `DynamicCallsContractFunctions` from `ContractCallDynamicCallsTest` to `ContractDebugServiceTest` as it uses the enum as well. The latter one is not refactored yet, so this enum will probably be removed from there as well when we get to it. The idea behind the same function names is that they will be used for both fungible tokens and NFTs in the same test so that it can be parameterized as the test body is the same.

2024-08-01 17:16 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +                "mintTokenGetTotalSupplyAndBalanceOfTreasury",
Can change name to include nft to differentiate with fungible test.

2024-08-01 17:31 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +                "burnTokenGetTotalSupplyAndBalanceOfTreasury",
Nevermind, I see that these are function names.

2024-08-01 17:52 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +        recordFilePersist();
Looks like this can just be replaced with `domainBuilder.recordFile().persist();` and then the method can be removed.

2024-08-01 18:21 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +
Many of the tests look to be pairs covering the same ground, except one version includes estimate gas assertions. Can the non-estimate gas tests be removed if the `assertDoesNotThrow(() -> { functionCall.send(); });` is added to the estimate gas tests?

2024-08-01 19:40 UTC, jnels124 commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        final var transactionHash = request.getParams().get(0).toString();
nit: can be replaced with `request.getParams().getFirst().toString()`

2024-08-02 07:41 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestUtil.java
> +public class ContractCallTestUtil {
You can add a private constructor, since it's a utility class

2024-08-02 08:19 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +        recordFilePersist();
Comment addressed.

2024-08-02 08:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +
I combined the ethCall and estimateGas tests into one. I did not plan to do that initially so that the junit tests can verify only one thing per test but you are right that this way we have a lot of duplication. Thanks.

2024-08-02 08:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        final var transactionHash = request.getParams().get(0).toString();
Comment addressed. Thanks.

2024-08-02 08:30 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestUtil.java
> +public class ContractCallTestUtil {
I added the `@UtilityClass` annotation. Thanks.

2024-08-02 20:26 UTC, steven-sheehy requested changes

2024-08-02 20:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +    enum DynamicCallsContractFunctions implements ContractFunctionProviderEnum {
Mark private to ensure it doesn't get used elsewhere. Should we open a ticket to also refactor `ContractDebugServiceTest`? Or is there another way to share test cases with debug like a shared `@Nested` class?

2024-08-02 20:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +    protected long gasUsedAfterExecution(final ContractExecutionParameters serviceParameters) {
Probably we should have an `AbstractContractCallServiceTest` with these methods and any common annotations and setup.

2024-08-02 20:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +    }
These and the `@Import` can move to a parent `AbstractContractCallServiceTest`.

2024-08-02 20:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +@TestInstance(PER_CLASS)
Why is this needed?

2024-08-05 07:09 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +    enum DynamicCallsContractFunctions implements ContractFunctionProviderEnum {
Yes, I think we need tickets to refactor `ContractDebugServiceTest` and `OpcodeServiceTest` as well using web3j.

2024-08-05 08:18 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +@TestInstance(PER_CLASS)
Actually, it is not. We don't need to keep any state.

2024-08-05 08:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +    protected long gasUsedAfterExecution(final ContractExecutionParameters serviceParameters) {
`AbstractContractCallServiceTest` is now created.

2024-08-05 08:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
> +    }
Moved as requested.

2024-08-05 14:55 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
> +    enum DynamicCallsContractFunctions implements ContractFunctionProviderEnum {
The issue for `ContractDebugServiceTest` - https://github.com/hashgraph/hedera-mirror-node/issues/8944.
The issue for `OpcodeServiceTest` - https://github.com/hashgraph/hedera-mirror-node/issues/8945.

2024-08-05 15:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +public abstract class AbstractContractCallServiceTest extends Web3IntegrationTest {
Can be package private

2024-08-05 15:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +    protected TestWeb3jService testWeb3jService;
Use constructor injection for parent classes with `@RequiredArgsConstructor`

```suggestion
    protected final TestWeb3jService testWeb3jService;
```

2024-08-05 15:51 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +public abstract class AbstractContractCallServiceTest extends Web3IntegrationTest {
Done

2024-08-05 15:51 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +    protected TestWeb3jService testWeb3jService;
Done

2024-08-05 15:56 UTC, steven-sheehy approved these changes
LGTM

2024-08-05 16:04 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-08-05 16:13 UTC, merged