feat: Refactor ContractCallEvmCodesTest
hashgraph/hedera-mirror-node pull request #8914
Opened 2024-08-01 13:24 UTC by kselveliev

**Description**:

This PR refactors **ContractCallEvmCodesTest**.
**ContractCallEvmCodes** now is independent from **ContractCallTestSetup** and is independent of persistEntities method.
Extracted historical tests -> they are working as before as currently we are able to integrate only latest block tests with the web3j plugin.
Extracted tests that use another contract **TestAddressThis** into another class since it is unrelated to evm codes and will be refactored in a later PR.

 

This PR modifies ... in order to support ...
* Add ContractCallAddressThis - moved tests using the address this into this class
* Modified ContractCallEvmCodesTest - refactored the test using the web3j plugin and make independent
* Added ContractCallEvmCodesTestHistorical - use old version of tests for historical 

**Related issue(s)**:

Fixes #8450

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-08-01 14:51 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        Thread.sleep(500);
Try to find a way to improve that.

2024-08-01 15:16 UTC, kselveliev commented
Need to figure out why codeHash test fails

2024-08-01 19:05 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +        String addressThisContractAddressWithout0x =
Nit, String can be var.

2024-08-01 19:05 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +        String successfulResponse = "0x000000000000000000000000" + addressThisContractAddressWithout0x;
```suggestion
        var successfulResponse = "0x" + StringUtils.leftPad( addressThisContractAddressWithout0x, 64, '0');
```

2024-08-01 19:06 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +        return addressThisContractEntityId;
Return value not used.

2024-08-01 19:37 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +        String addressThisContractAddressWithout0x =
Comment addressed

2024-08-01 19:37 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +        return addressThisContractEntityId;
Commend addressed, removed return value and made method void.

2024-08-01 19:38 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +        String successfulResponse = "0x000000000000000000000000" + addressThisContractAddressWithout0x;
Comment addressed

2024-08-01 20:08 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        assertThat(result.get(1)).isEqualTo(expetedList.get(1));
Something like this should simplify things, and then you can remove `convertBlake2HexToList`: 

```suggestion
final var contract = testWeb3jService.deploy(EvmCodes::deploy);
        List<byte[]> result = contract.call_blake2().send();
        var expectedResultHexString =
                "ba80a53f981c4d0d6a2797b69f12f6e94c212f14685ac4b74b12bb6fdbffa2d17d87c5392aab792dc252d5de4533cc9518d38aa8dbf1925ab92386edd4009923";
        var resultBytes = Bytes.concatenate(result.stream().map(Bytes::wrap).toArray(Bytes[]::new)).toArray();
        var expected = hexStringToByteArray(expectedResultHexString);
        assertArrayEquals(resultBytes, expected);
```

2024-08-01 20:11 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        var expectedResult = hexStringToByteArray("0000000000000000000000000000000000000000000000000000000000000000");
Can create a constant for `0000000000000000000000000000000000000000000000000000000000000000`, then replace the six usages.

2024-08-01 20:13 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        assertThat(result).isEqualTo(expectedResult);
Looks like the expectedOutput is always the same, can reference constant value directly and not pass in the second parameter.

2024-08-01 20:24 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        return data;
It seems like there should be a library to do this for us; however I tried a few and all tests pass except `testNonSystemContractEthCallCodeHash()`. I am unsure why that test fails with standard hex to byte[] conversions.

2024-08-01 21:40 UTC, jascks commented on hedera-mirror-web3/src/test/solidity/EvmCodes.sol
> +        selfdestruct(beneficiary);
While running `ContractCallAddressThisTest`, there are a number of Solidity compilation warnings reported.  Are these okay/expected? In this file, there is just the one below, but in `EthCall.sol`, there are five more.

```
Warning: "selfdestruct" has been deprecated. Note that, starting from the Cancun hard fork, the underlying opcode no longer deletes the code and data associated with an account and only transfers its Ether to the beneficiary, unless executed in the same transaction in which the contract was created (see EIP-6780). Any use in newly deployed contracts is strongly discouraged even if the new behavior is taken into account. Future changes to the EVM might further reduce the functionality of the opcode.
   --> src/test/solidity/EvmCodes.sol:234:9:
    |
234 |         selfdestruct(beneficiary);
    |         ^^^^^^^^^^^^```

2024-08-01 21:40 UTC, jascks commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
> +                .isInstanceOf(MirrorEvmTransactionException.class);
Should dig deeper. I can see in the debugger that the exception message is "INVALID_SOLIDITY_ADDRESS" which is indicated in the comment above. So, should assert the message is as expected not just the exception type.

2024-08-02 12:39 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        assertThat(result.get(1)).isEqualTo(expetedList.get(1));
Comment addressed. I applied the above suggestion.

2024-08-02 12:39 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        var expectedResult = hexStringToByteArray("0000000000000000000000000000000000000000000000000000000000000000");
Comment addressed. I created a constant.

2024-08-02 12:39 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        assertThat(result).isEqualTo(expectedResult);
Comment addressed.

2024-08-02 12:50 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +        return data;
I fixed the failing test. Now using ByteString.fromHex().toByteArray() allowed removing the custom method.

2024-08-02 13:32 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
> +                .isInstanceOf(MirrorEvmTransactionException.class);
You are right. Comment addressed. I am now also asserting for the expected exception message.

2024-08-02 14:19 UTC, kselveliev commented on hedera-mirror-web3/src/test/solidity/EvmCodes.sol
> +        selfdestruct(beneficiary);
Those are okay. I've actually refactored the EthCall.sol which should stop the warnings from appearing. I think we should still not change the selfdestruct one which will leave only one warning in the ci.

2024-08-02 15:39 UTC, jascks commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
> +                .isInstanceOf(MirrorEvmTransactionException.class);
Looks good. Thank you!

2024-08-02 15:44 UTC, jascks commented on hedera-mirror-web3/src/test/solidity/EvmCodes.sol
> +        selfdestruct(beneficiary);
Much nicer. 😄

2024-08-02 15:44 UTC, jascks approved these changes
LGTM

2024-08-02 21:10 UTC, steven-sheehy requested changes

2024-08-02 21:10 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +public class ContractCallAddressThisTest extends ContractCallTestSetup {
```suggestion
class ContractCallAddressThisTest extends ContractCallTestSetup {
```

2024-08-02 21:10 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +public class ContractCallAddressThisTest extends ContractCallTestSetup {
As I understand it, this is just moving things and we will refactor later to not extend `ContractCallTestSetup`. Can you please open a ticket under the epic for this future work?

2024-08-02 21:10 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
> +        evmCodesContractPersist();
Even if we can't use web3j to call the historical contract, we need to figure out a way to not depend upon our manually generated `.bin` and `.json` files. Can be a separate ticket.

2024-08-02 21:10 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void AltBN128MulPrecompiledContract() throws Exception {
I know it was that way before, but since we're refactoring we should adjust all methods to start with a lower case letter as per Java standards.

2024-08-04 05:52 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +public class ContractCallAddressThisTest extends ContractCallTestSetup {
Correct. I will open a ticket for that.

2024-08-05 08:16 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
> +        evmCodesContractPersist();
This will be a separate ticket since I still haven't found a way to avoid using the .bin in the historical tests.

2024-08-05 08:37 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
> +    void AltBN128MulPrecompiledContract() throws Exception {
Comment addressed

2024-08-05 08:37 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +public class ContractCallAddressThisTest extends ContractCallTestSetup {
Comment addressed

2024-08-05 10:08 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
> +public class ContractCallAddressThisTest extends ContractCallTestSetup {
This is the new [ticket](https://github.com/hashgraph/hedera-mirror-node/issues/8942) for this

2024-08-05 12:31 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
> +        evmCodesContractPersist();
With this corner case we'll need to revisit the other web3j-solidity plugin to generate the bin files from it instead of manually. So I'll reopen this task and work on it https://github.com/hashgraph/hedera-mirror-node/issues/8466.

2024-08-05 16:06 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Will need to be updated after https://github.com/hashgraph/hedera-mirror-node/pull/8912 is merged to use the new base class

2024-08-05 16:58 UTC, edwin-greene submitted a review, later dismissed
Looks good

2024-08-05 20:00 UTC, kselveliev commented
Updated from main to get changes from #8912

2024-08-05 20:26 UTC, steven-sheehy approved these changes

2024-08-05 20:29 UTC, merged