Remove `ContractReadFunctions` enum from `ContractCallServiceTest`
hashgraph/hedera-mirror-node pull request #8943
Opened 2024-08-05 12:36 UTC by IvanKavaldzhiev

**Description**:

This PR aims to partially recover `ContractCallServiceTest` by removing `ContractReadFunctions` enum.

A new abstract class is implemented having all of the needed common utilities. Temporarily it extends `ContractCallTestSetup`, since `ContractCallServiceTest` is not fully refactored and it has some dependencies to `ContractCallTestSetup`.

**Related issue(s)**: #8451 

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-05 12:47 UTC, kselveliev commented on hedera-mirror-web3/src/test/solidity/EthCall.sol
> +contract EthCall is HederaTokenService {
There are some warnings during compilation. Most of them could be removed with some small adjustments in the solidity file. 
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/c981276d-e635-4c86-a38d-50c8470c6204">

2024-08-05 12:50 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +public class AbstractContractCallServiceTest extends ContractCallTestSetup {
We could remove the `public` here

2024-08-05 16:06 UTC, IvanKavaldzhiev commented
There are some discrepancies with the other refactoring PRs, will refactor if after we merge #8912 to consume the common logic that is needed also here. Putting this PR as a Draft for now.

2024-08-07 22:51 UTC, steven-sheehy requested changes

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
> +    protected TestWeb3jService testWeb3jService;
Why are we moving this to the generic parent? I believe only children of the new `AbstractContractCallServiceTest` should need web3j

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
> +                        ? Address.wrap(Bytes.wrap(token.getTreasury().getAlias().toByteArray()))
Avoid extra allocations. Same for other change in file.

```suggestion
                        ? Address.wrap(Bytes.wrap(DomainUtils.toBytes(token.getTreasury().getAlias()))
```

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessor.java
> +                                ? ByteString.copyFrom(autoRenewAccount.getEvmAddress())
Avoid extra allocations. Same comment for other change in file.

```suggestion
                                ? DomainUtils.fromBytes(autoRenewAccount.getEvmAddress())
```

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
>      }
Can remove constructor and use `@RequiredArgsConstructor` now

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        ADMIN_KEY(BigInteger.valueOf(1)),
Clearer if you convert from integer to BigInteger in constructor.

```suggestion
        ADMIN_KEY(1),
```

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                contract.send_isTokenFrozen(getAddressFromEntity(tokenEntity), getAliasFromEntity(account));
Why are we do send vs call? If we use call we don't need the hack to add `TestWeb3jService.getTransactionResult()`.

2024-08-07 22:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        switch (tokenCreateNegativeCase) {
This parameterized test takes in a list of enums just to flatten it back it. Can we not convert it into separate tests?

2024-08-08 12:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +public class AbstractContractCallServiceTest extends ContractCallTestSetup {
Fixed

2024-08-08 15:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
> +    public static final BigInteger VALUE = BigInteger.valueOf(10000L * 100_000_000L);
Why do these need to be global constants? There isn't anything special about them that requires reuse. We should just define them separately within the individual methods. We can even vary their values as they don't even need to be the same for each test.

2024-08-08 15:47 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
For refactored tests in this class, we should follow the given/when/then syntax. It will help with readability especially here since we're coupling the given and the when too tightly.

```suggestion
        // Given
        final var contract = testWeb3jService.deploy(ModificationPrecompileTestContract::deploy);
        var entity = domainBuilder.entity().customize(e -> e.autoRenewPeriod(10L)).get();
        var token = domainBuilder.token().get();
        var hederaToken = convertTokenEntityToHederaToken(token, entity);

        // When
       var function = contract.send_createNonFungibleTokenExternal(hederaToken, BigInteger.valueOf(10));

        // Then
        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
```

2024-08-08 15:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        final var entity = domainBuilder.entity().get();
Believe these two domain classes should be linked.
```suggestion
        final var entity = domainBuilder.entity().customize(e -> e.id(token.getTokenId()).get();
```

2024-08-08 15:49 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    private Entity persistNft() {
Should move all private methods below all package private `@Test` methods.

2024-08-08 15:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    @CsvSource({"FUNGIBLE_COMMON", "NON_FUNGIBLE_UNIQUE"})
```suggestion
    @EnumSource(TokenTypeEnum.class)
```

2024-08-08 17:08 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +abstract class AbstractContractCallServiceTest extends ContractCallTestSetup {
If so, I should temporarily copy the utility classes from there into ContractCallServicePrecompileTest, but probably that's OK.

2024-08-08 17:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
> +            Key.newBuilder().setEd25519(ByteString.copyFrom(ED25519_KEY)).build();
We should create a token with a specific key value and then use read precompiles as `getTokenKey` to validate we read the exact same key.

2024-08-09 22:41 UTC, steven-sheehy approved these changes
LGTM. Just nits or can address in subsequent refactor PRs.

2024-08-09 22:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        final var expectedHederaToken = new PrecompileTestContract.HederaToken(
nit: The expected variables in each test should be defined within the "Then" section

2024-08-09 22:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                        .get()),
DomainBuilder invocation and complex object setup should be performed in the given section. Same comment elsewhere.

```suggestion
        final var contract = testWeb3jService.deploy(ModificationPrecompileTestContract::deploy);
        final var token = domainBuilder.token().customize(t -> t.supplyKey(new byte[0])).get();
        final var hederaToken = convertTokenEntityToHederaToken(token);

        // When
        final var function = contract.send_createNonFungibleTokenExternal(hederaToken,```

2024-08-12 14:48 UTC, kselveliev approved these changes

2024-08-12 14:54 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        final var expectedHederaToken = new PrecompileTestContract.HederaToken(
Will reflect that on consequent PR

2024-08-12 14:55 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                        .get()),
Will adapt in next PRs

2024-08-12 15:01 UTC, merged