Refactor ContractCallNestedCallsTest
hashgraph/hedera-mirror-node pull request #8955
Opened 2024-08-06 12:42 UTC by bilyana-gospodinova

**Description**:
With this PR the `ContractCallNestedCallsTest` integration test is refactored using the web3j plugin and the big enum is now replaced with multiple junit tests so that it is easier to debug a particular scenario. This way also the number of persisted entities per test is reduced significantly and now we persist only the ones that are needed in the particular test. With this implementation the execution time of the `ContractCallNestedCallsTest` is reduced 3 times (from about 38 seconds to 13 seconds, tested locally).

The `NestedEthCallContractFunctionsNegativeCases` and `NestedEthCallContractFunctions` enums are moved from `ContractCallNestedCallsTest` to `ContractDebugServiceTest` and `OpcodeServiceTest` respectively as they still need these enums and these test classes are not refactored yet.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/8455

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-08-06 13:19 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    public ContractCallNestedCallsTest(TestWeb3jService testWeb3jService) {
we can remove the public modifier here

2024-08-06 13:22 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +                    NON_FUNGIBLE_UNIQUE,    DELEGATABLE_CONTRACT_ID,    FEE_SCHEDULE_KEY,
One suggestion here is instead of having many lines with NON_FUNGIBLE_UNIQUE or FUNGIBLE_COMMON.
We can split the method into updatedFungibleTokenKeys.. and updateNonFungibleTokenKeys...
And with that we can remove the final TokenTypeEnum tokenType parameter and remove the if statement final var tokenEntityId = tokenType == TokenTypeEnum.FUNGIBLE_COMMON ? fungibleTokenPersist() : nftPersist(); 

And it will just be var tokenEntityId = fungibleTokenPersist() or tokenEntityId = nftPersist(). I think it is a bit cleaner that way

2024-08-06 13:31 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    void createFungibleTokenAndGetIsTokenAndGetDefaultFreezeStatusAndGetDefaultKycStatus(
Can't we just merge the below method into this createFungibleTokenAndGetIsTokenAndGetDefaultFreezeStatusAndGetDefaultKycStatusInheritKey

Probably if we add one more boolean in the csv like: 
true, true, true, false
false, false, false, false
false, false, false, true

The last boolean is the inherit key.

I think with this approach we can delete createFungibleTokenAndGetIsTokenAndGetDefaultFreezeStatusAndGetDefaultKycStatusInheritKey method.

2024-08-06 13:32 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    void createNFTAndGetIsTokenAndGetDefaultFreezeStatusAndGetDefaultKycStatusInheritKey() throws Exception {
This is probably same as the above comment.

2024-08-07 06:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    public ContractCallNestedCallsTest(TestWeb3jService testWeb3jService) {
Correct. It seems I forgot to update the modifier since this method is generated. Thanks.

2024-08-07 06:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +                    NON_FUNGIBLE_UNIQUE,    DELEGATABLE_CONTRACT_ID,    FEE_SCHEDULE_KEY,
Comment addressed.

2024-08-07 06:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    void createFungibleTokenAndGetIsTokenAndGetDefaultFreezeStatusAndGetDefaultKycStatus(
Comment addressed. Thanks.

2024-08-07 06:44 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    void createNFTAndGetIsTokenAndGetDefaultFreezeStatusAndGetDefaultKycStatusInheritKey() throws Exception {
Comment addressed. Thanks.

2024-08-07 07:01 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    private ContractCallNestedCallsTest(TestWeb3jService testWeb3jService) {
Making this package private fixes the code smell. I had the same issue in my pr.

2024-08-07 07:06 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    private ContractCallNestedCallsTest(TestWeb3jService testWeb3jService) {
Yes, but we don't really need to be able to make instances of this class even in the same package, so this code smell does not make sense to me.

2024-08-07 07:08 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    private ContractCallNestedCallsTest(TestWeb3jService testWeb3jService) {
I agree :)

2024-08-07 12:09 UTC, kselveliev submitted a review, later dismissed

2024-08-07 13:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +    private ContractCallNestedCallsTest(TestWeb3jService testWeb3jService) {
We can go back to not using constructor injection for the parent class if it makes this code smell go away. Just use `@Resource` to inject `TestWeb3jService` into parent.

2024-08-08 16:32 UTC, steven-sheehy requested changes

2024-08-08 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        testWeb3jService.setSender(Address.fromHexString(""));
Would be better to do in the before each

2024-08-08 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +        verifyEthCallAndEstimateGas(functionCall, contract);
It seems wasteful to call once to verify result, a second time to get actual gas used, and N times to calculate estimate. Maybe in the future (not this PR) we should consider enhancing `ContractCallService.processCall()` to return a wrapper object instead of just a String that we can always attach both the result and gas used to to improve efficiency of the tests.

2024-08-08 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +        testWeb3jService.setValue(CREATE_TOKEN_VALUE);
Believe this value is only used for creates. If so, instead of having a setter for it we should overload `TestWeb3jService.deploy()` to take in an extra value to supply for creates.

2024-08-08 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/KeyType.java
> +    KYC_KEY(BigInteger.valueOf(2)),
As noted in Ivan's PR, can just pass integer and convert to BigInteger in constructor.

2024-08-13 07:41 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +        verifyEthCallAndEstimateGas(functionCall, contract);
I agree. I opened issue https://github.com/hashgraph/hedera-mirror-node/issues/9012 for this enhancement.

2024-08-13 07:44 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
> +        testWeb3jService.setValue(CREATE_TOKEN_VALUE);
This seems a little misleading to me - I would expected that the passed value will be used during deploy, not in the subsequent requests. It seems more straightforward to me to set the value for the particular request that needs it.

2024-08-13 07:47 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        testWeb3jService.setSender(Address.fromHexString(""));
Moved to `BeforeEach`.

2024-08-13 07:48 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/KeyType.java
> +    KYC_KEY(BigInteger.valueOf(2)),
I removed this class as it already exists in `AbstractContractCallServiceTest` on main.

2024-08-13 14:34 UTC, kselveliev approved these changes

2024-08-13 14:51 UTC, steven-sheehy approved these changes
LGTM

2024-08-13 14:51 UTC, merged