Improve transaction hash v2 performance
hashgraph/hedera-mirror-node pull request #8970
Opened 2024-08-07 19:30 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Fixes #8896

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-08-07 19:32 UTC, xin-hedera commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionHash.java
> +    private short distributionId;
choose short so the value range should be big enough if ever we choose to increase the number of transaction_hash table shards in v2

2024-08-07 19:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
> +            from %%s
escape `%s`, it's the source table name, depends on whether it's v1 or v2, it can be just `transaction` or a partition, e.g. `transaction_p2024_02`

2024-08-07 19:35 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.1__add_transaction_hash_distribution_id.sql
> +alter table if exists transaction_hash add column distribution_id smallint;
this is just a table metadata change for v1 and it's fast

2024-08-07 19:36 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.1__add_transaction_hash_distribution_id.sql
> +      distribution_id     smallint
the column is the last since it's the newest addition, when we do `select * from transaction_hash`

2024-08-07 19:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.4.1__change_transaction_hash_distribution.sql
> +drop table if exists transaction_hash;
I need to test if migrating the existing data here is faster than reprocessing data in the java migration.

The steps will then be

- undistribute the table
- add the new column
- fill the value for the new column from the `hash` column
- redistribute the table on `distribution_id`

This involves copying the data twice (undistribute then redistribute), and scanning the whole table and writing value to the new column. It's hard to say which way is faster.

2024-08-07 19:39 UTC, xin-hedera commented on hedera-mirror-rest/middleware/httpErrorHandler.js
> +  DbError: httpStatusCodes.SERVICE_UNAVAILABLE,
all changes in this file are just spotless reformat

2024-08-07 19:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
> +              ('x' || encode(substring(transaction_hash from 1 for 2), 'hex'))::bit(32)::int >> 16,
The conversion here is tricky. The problem is postgresql doesn't support convert bit(16) to smallint.

`'x' || encode(substring(transaction_hash from 1 for 2), 'hex')` creates a bit string in hex format from the first 2 bytes;
then `::bit(32)` convert it to 32 bits by padding 16 bit 0s at then end, preserving the sign bit;
then `::int >> 16` converts `bit(32)` to a 4-byte int and right shift 16 to get the smallint with correct sign bit

2024-08-07 19:49 UTC, xin-hedera commented on hedera-mirror-rest/transactionHash.js
> +    params.push(hash.readInt16BE());
this is only tested in v2, however we don't upload v2 test coverage...

2024-08-09 14:12 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
> +                jdbcTemplate.execute(CREATE_TEMP_TABLE_SQL);
all lines in the file with missing test coverage are tested in v2 since only in v2 temp table is created & tables are partitioned by time.

2024-08-09 20:23 UTC, steven-sheehy requested changes

2024-08-12 14:47 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.4.2__get_transaction_info_by_hash.sql
> +create or replace function get_transaction_info_by_hash(transactionHash bytea)
had to put it to a separate sql migration because mixing it with V2.4.1 will fail without setting citus shard work mode to `sequential` from `parallel`, and that definitely will impact performance when there's a lot of data to read / write in V2.4.1

2024-08-12 14:48 UTC, xin-hedera commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/transaction/TransactionHashTest.java
> +        hash[1] = second;
bytes after the first 2 are randomized, so supposedly that provides better test coverage across many runs?

2024-08-12 14:57 UTC, steven-sheehy commented on hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/transaction/TransactionHashTest.java
> +        hash[1] = second;
Sure, missed that detail.

2024-08-12 19:22 UTC, steven-sheehy approved these changes
LGTM

2024-08-13 19:23 UTC, jnels124 approved these changes
LGTM

2024-08-13 20:17 UTC, merged