8456-Refactor contractCallServiceERCTokenTest class
hashgraph/hedera-mirror-node pull request #8985
Opened 2024-08-09 12:40 UTC by nickeynikolovv

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-09 12:59 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +    void ethCallIsApporvedForAllStatic() throws Exception {
Fix typo on method name

2024-08-09 13:24 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> -    void ercReadOnlyPrecompileOperationsTest(final ErcContractReadOnlyFunctions ercFunction, final boolean isStatic) {
Here we delete the method that tests eth_call.
But in our newly created suite we test for eth call and estimate gas response.
From what I see there is another method with the same parameter source that tests for estimate gas called 
`supportedErcReadOnlyPrecompileOperationsTest` i believe we could also delete that if im not mistaken

2024-08-09 13:55 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> -    void ercReadOnlyPrecompileOperationsTest(final ErcContractReadOnlyFunctions ercFunction, final boolean isStatic) {
Correct, removed

2024-08-09 13:55 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +    void ethCallIsApporvedForAllStatic() throws Exception {
fixed

2024-08-09 13:55 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +      final var treasuryEntityId = accountPersist();
fixed

2024-08-09 22:26 UTC, steven-sheehy requested changes

2024-08-09 22:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> +        TRANSFER_FROM("transferFrom", new Object[]{TREASURY_TOKEN_ADDRESS, SENDER_ALIAS, SPENDER_ALIAS, 2L}),
It looks like spotless is not running. Please run `./gradlew spotlessApply` and ensure going forward the git hook executes even if you have to change from committing via a UI to `git commit`.

2024-08-09 22:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> + * Copyright (C) 2023-2024 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C)2024 Hedera Hashgraph, LLC
```

2024-08-09 22:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +                ;
```suggestion
                .toEntityId();
```

2024-08-09 22:26 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +                .persist();
This sort of setup is in a number of tests. Might be useful to extract it to a helper method.

2024-08-12 06:52 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +    public ContractCallServiceERCTokenReadOnlyFunctionsTest(TestWeb3jService testWeb3jService) {
The modifier needs to be private as we don't need instances of this class.

2024-08-12 09:48 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +    public ContractCallServiceERCTokenReadOnlyFunctionsTest(TestWeb3jService testWeb3jService) {
fixed

2024-08-12 09:48 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +                .persist();
fixed - extracted in a separate method

2024-08-12 09:48 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> +                ;
fixed

2024-08-12 09:48 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
> + * Copyright (C) 2023-2024 Hedera Hashgraph, LLC
fixed

2024-08-12 09:48 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
> +        TRANSFER_FROM("transferFrom", new Object[]{TREASURY_TOKEN_ADDRESS, SENDER_ALIAS, SPENDER_ALIAS, 2L}),
done

2024-08-12 16:39 UTC, steven-sheehy reviewed
LG, just one code smell and need to fix merge conflicts

2024-08-13 10:57 UTC, bilyana-gospodinova approved these changes
LGTM

2024-08-13 14:32 UTC, kselveliev approved these changes

2024-08-13 14:49 UTC, steven-sheehy approved these changes

2024-08-13 14:49 UTC, merged