Handling numeric values for EntityId query parameters
hashgraph/hedera-mirror-node pull request #9009
Opened 2024-08-12 17:37 UTC by mgoelswirlds

**Description**:

This PR fixes rest-java nft allowance controller to accept numeric entity id in URL params.

This PR modifies ...
* EntityId to handle numeric entity not in the `shard.realm.num` format

**Related issue(s)**:

Fixes #8357

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-12 18:56 UTC, mgoelswirlds commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
> +        void allRangeConditionsNumericQueryParameters() {
For the reviewers, the upper bounds operators have the `shard.realm.num` format inspite of the original url have only the numeric code. This is to keep consistency with /token/allowances API

2024-08-13 15:31 UTC, jascks submitted a review, later dismissed
LGTM

2024-08-13 16:18 UTC, steven-sheehy requested changes

2024-08-13 16:18 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java
> +            return of(0, 0, parts.get(0));
This happens to work now, but will have issues later whenever we support non-zero shards. Instead, we should handle this at the rest-java layer and feed in the shard property as the default if it's missing.

2024-08-13 16:18 UTC, steven-sheehy commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java
> +        if (parts.size() == 1) {
We also support `realm.num` syntax on REST API

2024-08-13 18:11 UTC, mgoelswirlds commented on hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java
> +            return of(0, 0, parts.get(0));
The problem is this error occurs in the controller ParameterResolution for `EntityIdRangeParameter` itself. So I would need to handle it here. Also, I cannot access the shard property here.
But I agree when we support non-zero shards this will be a problem.

2024-08-14 22:47 UTC, steven-sheehy requested changes

2024-08-14 22:47 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/EntityIdRangeParameterTest.java
> -                "100000.000000001",
We should have positive tests for `realm.num` and `num`. Add negative tests with whitespace and negative numbers and 1 and 2 parts.

2024-08-14 22:47 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdRangeParameter.java
> +                .filter(n -> n >= 0)
This parsing is too permissive for user input. It would allow input like `" 0 .  0.1 "`

2024-08-14 22:47 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
> +        void allRangeConditionsNumericQueryParameters() {
Instead of a new test, we should make an existing test parameterized with a test enum:

```java
  private enum EntityIdType {
    NUM(e -> "" + e.getNum()),
    REALM_NUM(e -> "%d.%d".format(e.getRealm(), e.getNum()),
    SHARD_REALM_NUM(e -> e.toString());
...
 }
```

2024-08-15 16:32 UTC, steven-sheehy approved these changes
LGTM

2024-08-15 16:56 UTC, jascks approved these changes
LGTM

2024-08-15 17:21 UTC, merged