Fill ethereum hash when missing in record
hashgraph/hedera-mirror-node pull request #9019
Opened 2024-08-13 19:41 UTC by xin-hedera

**Description**:

This PR fixes the empty ethereum transaction hash bug

- Fill ethereum hash when missing in record
- Backfill existing empty ethereum hash

**Related issue(s)**:

Fixes #8922

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-08-13 20:49 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/EthereumTransactionHashServiceImpl.java
> +            byte[] value = Integers.toBytesUnsigned(new BigInteger(ethereumTransaction.getValue()));
The discrepancy has no impact on rest api since `[0]` and `[]` should both decode to bigint 0. It definitely causes hashing issue though.

2024-08-16 13:30 UTC, edwin-greene submitted a review, later dismissed
Looks good to me

2024-08-16 16:04 UTC, steven-sheehy requested changes

2024-08-16 16:11 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillEthereumTransactionHashMigration.java
> +                                    callDataId, t.getConsensusTimestamp(), t.getData()));
because the gas fields in the db table are converted, so we have to decode ethereum_transaction.data when the call data is offloaded and reconstruct.

We can of course have a single function `byte[] getHash(@NotNull EthereumTransaction ethereumTransaction);` and parse the `data` into a new `EthereumTransaction` regardless to make it work,  I just don't think that's a better approach.

2024-08-16 18:58 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/EthereumTransactionHashServiceImpl.java
> +                        List.of(
That would move the methods from the service to the parsers, and it looks cleaner.

2024-08-16 22:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillEthereumTransactionHashMigration.java
> +                                    callDataId, t.getConsensusTimestamp(), t.getData()));
the other reason is the migration uses a custom SQL so jdbcOperations and a row mapper to deserialize the data, so it'll fail to deserialize a bigint `call_data_id` to `EntityId callDataId` in `EthereumTransaction`

2024-08-16 22:56 UTC, steven-sheehy approved these changes
LGTM

2024-08-18 17:23 UTC, jnels124 approved these changes
LGTM

2024-08-19 13:56 UTC, merged