Finalize refactoring of `ContractCallServicePrecompileTest`
hashgraph/hedera-mirror-node pull request #9022
Opened 2024-08-14 12:35 UTC by IvanKavaldzhiev

**Description**:
This PR finalizes the refactoring of `ContractCallServicePrecompileTest` by using entirely the web3j library and remove the dependency from `ContractCallTestSetup`.

All historical tests are extracted in a separate class and are going to be refactored in a future work.

**Related issue(s)**:

Fixes #8451

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2024-08-15 00:05 UTC, steven-sheehy requested changes

2024-08-15 07:06 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        testEstimateGas(functionCall, contract, 0L);
suggestion: `0L` is used multiple times in the tests, can be extracted as constant

2024-08-15 07:52 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                testWeb3jService.getTransactionResult(), CREATE_TOKEN_FUNCTION_OUTPUT_PARAMETERS);
Because we need to send `value` for the transactions. These are methods are `payable` since the `tokenCreate` precompiles take value in addition to the gas. The `call_` methods cannot pass values.

2024-08-15 08:31 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
Is there an error code or error message that we can verify here? The call might fail but for a reason that is not the expected one. Same for other tests too.

2024-08-15 08:38 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                //                .sender(new HederaEvmAccount(Address.wrap(Bytes.wrap(domainBuilder.evmAddress()))))
This comment can be removed.

2024-08-15 09:31 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        testEstimateGas(functionCall, contract, 0L);
This 0 is passed as a third argument on each call of this method and there is no other value for it. Perhaps move it in the method?

2024-08-15 11:05 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        functionCall.send();
It might not be so clear, but the idea is that now invoking `call_` method with `send()` will both run `eth_call` and `eth_estimateGas` inside `TestWeb3jService` and in order to fetch the `estimatedGas` field inside `testEstimateGas`, we should first call `send()`. 

I'll refactor it to be more clear.

2024-08-15 14:15 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        testEstimateGas(functionCall, contract, 0L);
In the `createToken` tests different value amounts are passed.

2024-08-15 14:20 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
That is the same check performed in the current tests. I wanted to preserve the same behaviour.

We might extend them in the last task of polishing the tests.

2024-08-15 17:50 UTC, edwin-greene commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +import static com.hedera.mirror.web3.utils.ContractCallTestUtil.*;
Can you import the specifics and remove the wildcard? There should be some settings for intellij to not use wildcards for imports.

2024-08-15 20:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +import static com.hedera.mirror.web3.utils.ContractCallTestUtil.*;
Fixed

2024-08-23 03:48 UTC, steven-sheehy requested changes

2024-08-23 03:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        testWeb3jService.setSender(Address.ZERO);
Move to inside reset method. Also move reset method to beforeEach

2024-08-23 03:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        this.sender = sender;
Why have a setter if we generate one via lombok?

2024-08-23 03:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                testWeb3jService.getTransactionResult(), CREATE_TOKEN_FUNCTION_OUTPUT_PARAMETERS);
We could add a `TestWeb3jService.setValue()` that overrides the transaction value then we could use call. If we keep send, we should still not be encoding function parameters manually. Please use:

```java
final var functionCall = contract.send_createFungibleTokenExternal(token, initialSupply, decimals, value);
functionCall.send();
final var decodedResult = functionCall.decodeFunctionResponse(testWeb3jService.getTransactionResult());
```

2024-08-23 03:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    @CsvSource("true, false")
Same comment elsewhere

```suggestion
    @ValueSource(booleans = {true, false})
```

2024-08-23 06:46 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
Sure, but can you please note this down in the task for polishing the tests so that we don't forget?

2024-08-23 07:59 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        return Address.fromHexString(Bytes.wrap(entity.getEvmAddress()).toHexString())
Can't this be simplified to: `Bytes.wrap(entity.getEvmAddress()).toHexString();`?

2024-08-23 08:34 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        final var tokenToUpdateEntity = domainBuilder
This token persist code can be extracted in a separate method since this logic is duplicated in multiple tests. The same for NFT.

2024-08-23 08:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
Added - https://github.com/hashgraph/hedera-mirror-node/issues/9135

2024-08-23 08:38 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        this.entityId = entityId;
I think that we don't need to keep the contract entity id as a state in `TestWeb3jService` as this class keeps already too much fields. We can get the id this way:

```
final var contractAddress = Address.fromHexString(contract.getContractAddress());
final var contractEntityId = entityIdFromEvmAddress(contractAddress);
```
So far we keep in the `TestWeb3jService`'s state some variables that we are not able to get in any other way.

2024-08-23 08:38 UTC, nickeynikolovv requested changes

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void approve(final BigInteger allowance) throws Exception {
on my side when i ran this test it only executed with "1" value. Can you please check

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void updateTokenKey(final TokenTypeEnum tokenTypeEnum, final KeyValueType keyValueType) throws Exception {
on my side when i ran this test also it only executed with the first value from the enum "FUNGIBLE_COMMON, ED25519" value. Can you please check

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void associateToken(final Boolean single) throws Exception {
this one also executed with only "true"

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void approveNFT(final Boolean approve) throws Exception {
executed with only the "true" value

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void dissociateToken(final Boolean single) throws Exception {
this one also executed with the first value only - "true"

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
>      @Test
You can use directly `SENDER_ALIAS` from `ContractCallTestUtil`

2024-08-23 08:38 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
>      @Test
also here you can use `SENDER_ALIAS` from `ContractCallTestUtil`

2024-08-23 14:12 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void approve(final BigInteger allowance) throws Exception {
Good catch! The formatting was wrong.

2024-08-23 14:21 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void updateTokenKey(final TokenTypeEnum tokenTypeEnum, final KeyValueType keyValueType) throws Exception {
Great catch! Again wrong formatting, I found some failing cases.

2024-08-26 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
>      @Test
Fixed

2024-08-26 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
>      @Test
Fixed

2024-08-26 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void dissociateToken(final Boolean single) throws Exception {
Fixed

2024-08-26 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void approveNFT(final Boolean approve) throws Exception {
Fixed

2024-08-26 08:38 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void associateToken(final Boolean single) throws Exception {
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void updateTokenKey(final TokenTypeEnum tokenTypeEnum, final KeyValueType keyValueType) throws Exception {
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    void approve(final BigInteger allowance) throws Exception {
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        this.entityId = entityId;
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        final var tokenToUpdateEntity = domainBuilder
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        return Address.fromHexString(Bytes.wrap(entity.getEvmAddress()).toHexString())
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +    @CsvSource("true, false")
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
> +        this.sender = sender;
Fixed

2024-08-26 08:39 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        testWeb3jService.setSender(Address.ZERO);
Fixed

2024-08-26 16:01 UTC, steven-sheehy approved these changes
LGTM

2024-08-27 08:11 UTC, nickeynikolovv commented
LGTM

2024-08-27 08:12 UTC, nickeynikolovv approved these changes
LGTM

2024-08-27 14:22 UTC, merged