8345 upgrade stackgres to 1120
hashgraph/hedera-mirror-node pull request #9082
Opened 2024-08-20 19:01 UTC by jnels124

**Description**:
* bump stackgres to 1.11.0
* add `SGShardedDbOps` to perform a security upgrade

**Related issue(s)**:

Fixes #8345 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-20 19:04 UTC, jnels124 commented
Merging this may effect performance namespace so may wait until 0.113 is ready to be tagged

2024-08-20 19:05 UTC, jnels124 commented on docs/runbook/increase-pvc-size-for-statefulset.md
Not related to this PR but small enough to be done here

2024-08-25 19:39 UTC, jnels124 commented on charts/hedera-mirror/templates/stackgres/sharded-cluster-security-upgrade
Maybe this would be best to just apply manually when needed? Can move to a runbook or elsewhere.

2024-08-25 19:41 UTC, jnels124 commented on charts/hedera-mirror/values.yaml
> +  securityUpgrade: false
This being false means auto deploy deployments will need to be deployed twice (or added to environments on a previous deployment).

2024-08-25 21:18 UTC, jascks submitted a review, later dismissed
LGTM

2024-08-26 17:30 UTC, steven-sheehy requested changes

2024-08-26 17:30 UTC, steven-sheehy commented on charts/hedera-mirror/templates/stackgres/sharded-cluster-security-upgrade.yaml
> +    mode: InPlace
Not sure we should go this approach of adding a very specific db ops to our chart. Ops are one time operations. If we ever wanted it to run it again we'd have to delete it and recreate it or create an identical one with a new name.

These are manual operations anyway so we should just create the resource manually either in the deploy branch (then delete it), via kubectl apply, or via stackgres UI. Probably instead we should remove this and add an upgrade runbook with the yaml or UI steps.

2024-08-26 20:04 UTC, jnels124 commented on charts/hedera-mirror/templates/stackgres/sharded-cluster-security-upgrade.yaml
> +    mode: InPlace
I agree. Will remove and make sure the release manager for 0.113.0 runs it.

2024-08-26 21:05 UTC, steven-sheehy commented on charts/hedera-mirror/templates/stackgres/sharded-cluster-security-upgrade.yaml
> +    mode: InPlace
We should still have a run book to follow

2024-08-26 22:52 UTC, xin-hedera approved these changes
LGTM

2024-08-27 00:02 UTC, steven-sheehy approved these changes

2024-08-27 00:05 UTC, xin-hedera approved these changes
LGTM

2024-08-27 18:06 UTC, merged