Refactor `ContractCallServiceTest`
hashgraph/hedera-mirror-node pull request #9092
Opened 2024-08-21 11:30 UTC by bilyana-gospodinova

**Description**:
This PR refactors the rest of the tests in `ContractCallServiceTest` to use web3j. Some cleanup of unused methods is done in `ContractCallTestSetup`.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/8452

2024-08-21 15:59 UTC, steven-sheehy requested changes

2024-08-21 15:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        testWeb3jService.setBlockType(BlockType.LATEST);
We should move these to `TestWeb3jService.reset()` and call it here.

2024-08-21 15:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> -
Can we delete any of the bin/json/sol files that you're removing from this file?

2024-08-21 15:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
>          meterRegistry.clear();
Can remove this meterRegistry.clear() as it's done in a parent class already

2024-08-21 15:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        super.setup();
We should rename either child or parent setup() so we don't have to remember to manually invoke. Probably should make parent final, too.

2024-08-21 15:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +    @Autowired
Prefer standard `@Resource`

2024-08-21 15:59 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var senderEntity = accountPersist();
Adding Given/When/Then to tests might aid in readability.

2024-08-22 09:05 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +        testWeb3jService.setBlockType(BlockType.LATEST);
Moved

2024-08-22 09:06 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
> -
Good point. I deleted the redundant files.

2024-08-22 09:06 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
>          meterRegistry.clear();
Comment addressed. Thanks.

2024-08-22 09:08 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        super.setup();
After addressing the other comments, it seems that we don't need this `setup()` method in this class at all. I made the parent method final.

2024-08-22 09:09 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
> +        final var senderEntity = accountPersist();
I added some comments. Hopefully the readability is better now.

2024-08-22 17:50 UTC, steven-sheehy approved these changes
LGTM

2024-08-22 17:50 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> -        testWeb3jService.setSender(Address.fromHexString(""));
Probably reset should occur in beforeeach, but can do in follow ups

2024-08-23 07:13 UTC, kselveliev approved these changes

2024-08-23 13:34 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-08-23 16:38 UTC, merged