Add outstanding token airdrops to REST API
hashgraph/hedera-mirror-node pull request #9286
Opened 2024-09-06 20:34 UTC by edwin-greene

**Description**:
Adds the outstanding token airdrops endpoint to the REST API.

**Related issue(s)**:

Fixes #8276 

**Notes for reviewer**:
Currently only generates pagination links with two values, receiver.id and token.id. Pagination by serialnumber may be added later. 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-09-11 16:01 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +  /api/v1/accounts/{senderIdOrAliasOrEvmAddress}/airdrops/outstanding:
Believe this won't map properly unless we do
```suggestion
  /api/v1/accounts/{idOrAliasOrEvmAddress}/airdrops/outstanding:
```

2024-09-11 16:01 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Returns pending airdrops that have been sent by an account.
summary and description notes pending instead of outstanding

2024-09-11 16:02 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: "#/components/responses/NotFoundError"
Just to clarify this is for when path parameter is not in db, not for when no token_airdrop rows, right?

2024-09-11 16:04 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - accounts
Perhaps we should group these two under a separate tag
```suggestion
        - airdrops
```

2024-09-11 16:07 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: integer
Believe we should have `nullable: true`

2024-09-11 16:08 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^(\d{1,10}\.){0,2}(\d{1,10}|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))$
I don't think we need to support alias or EVM address, do we?

2024-09-11 16:17 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/TokenAirdropServiceTest.java
> +    void getOutstandingTokenAirdrops() {
Add test for no airdrops and for sender not present

2024-09-11 16:18 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/TokenAirdropServiceTest.java
> +    void getOutstandingAirdropByAlias() {
Add EVM address test

2024-09-11 16:22 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> -    }
Wondering if we can find a way to extract more logic to a common parent if we can generalize getMiddleCondition, getOuterBoundCondition, etc. Can do as follow up though.

2024-09-11 16:23 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +    private static final Map<OrderSpec, List<SortField<?>>> SORT_ORDERS = Map.of(
```suggestion
    private static final Map<OrderSpec, List<SortField<?>>> OUTSTANDING_SORT_ORDER = Map.of(
```

2024-09-11 21:09 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/IntegerRangeParameter.java
> +public record IntegerRangeParameter(RangeOperator operator, Integer value) implements RangeParameter<Integer> {
Thanks I have updated this.

2024-09-11 21:10 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/IntegerRangeParameter.java
> +            case 2 -> new IntegerRangeParameter(RangeOperator.of(splitVal[0]), Integer.valueOf(splitVal[1]));
Got it, I've added those checks.

2024-09-11 21:10 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +                .senderId(id)
Got it I have updated this.

2024-09-11 21:10 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +        var response = service.getOutstandingTokenAirdrops(request);
Sounds good I have updated this.

2024-09-11 21:11 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/OutstandingTokenAirdropRequest.java
> +public class OutstandingTokenAirdropRequest {
That should work, I have updated it and added comments as the fields have different meanings per endpoint.

2024-09-11 21:12 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/TokenAirdropsMapper.java
> +    @Mapping(source = "senderAccountId", target = "senderId")
The shortened names make sense, I've renamed them.

2024-09-11 21:12 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +    private static final Map<OrderSpec, List<SortField<?>>> SORT_ORDERS = Map.of(
Thanks I have renamed it.

2024-09-11 21:12 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/IntegerRangeParameterTest.java
> +        assertThat(new IntegerRangeParameter(RangeOperator.EQ, 2000)).isEqualTo(IntegerRangeParameter.valueOf("2000"));
Thanks I have added that test.

2024-09-11 21:13 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/IntegerRangeParameterTest.java
> +    @DisplayName("IntegerRangeParameter parse from string tests, negative cases")
Got it those tests have been added.

2024-09-11 21:13 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/TokenAirdropServiceTest.java
> +    void getOutstandingTokenAirdrops() {
Thanks I have added them.

2024-09-11 21:13 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/TokenAirdropServiceTest.java
> +    void getOutstandingAirdropByAlias() {
Got it I have added it.

2024-09-11 21:14 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +  /api/v1/accounts/{senderIdOrAliasOrEvmAddress}/airdrops/outstanding:
Thanks I have updated this.

2024-09-11 21:14 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Returns pending airdrops that have been sent by an account.
For now I have just removed that parameter. Do you think the description should be updated as well?

2024-09-11 21:14 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Returns pending airdrops that have been sent by an account.
Thanks I have fixed.

2024-09-11 21:14 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: "#/components/responses/NotFoundError"
That's correct.

2024-09-11 21:15 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - accounts
Got it, updated.

2024-09-11 21:15 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: integer
Sounds good I have added it.

2024-09-11 21:15 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^(\d{1,10}\.){0,2}(\d{1,10}|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))$
Got it, I have updated it.

2024-09-11 21:16 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
> +    }
I still need to add tests to validate that only a single receiverId/tokenId are present. If multiples are passed in then an error needs to be thrown.

2024-09-11 21:41 UTC, xin-hedera commented
> Pagination by serialnumber may be added later.

Can this even work?

Serial number should be in the order part so as to limit the entries in the response. If we don't support seiral number pagination, we won't have it in the next url, then wouldn't the endpoint provide incomplete response?

2024-09-11 22:00 UTC, xin-hedera requested changes

2024-09-11 22:00 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +    private final TokenAirdropsMapper tokenMapper;
nit 
```suggestion
    private final TokenAirdropsMapper tokenAirdropMapper;
```

2024-09-11 22:00 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +            Direction.DESC, List.of(TOKEN_AIRDROP.RECEIVER_ID.desc(), TOKEN_AIRDROP.TOKEN_ID.desc()));
how is this going to work without also order by serial number?

We'll get random order for the rows with same NFT token class and receiver when there are multiple serial numbers.

i.e., from a custom's perspective, given that the data in the database doesn't change, querying the same URL will return response with rows ordered differently.

2024-09-11 22:25 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.100.0__add_token_airdrop.sql
> +create index if not exists token_airdrop__receiver_id on token_airdrop (receiver_id, sender_id, token_id, serial_number);
We can't modify indexes after they've been deployed. If it's too much work we don't have to rename.

2024-09-11 22:27 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +            Direction.DESC, List.of(TOKEN_AIRDROP.RECEIVER_ID.desc(), TOKEN_AIRDROP.TOKEN_ID.desc()));
Probably we should exclude non fungible token IDs by excluding where serial number is not null.

2024-09-12 00:31 UTC, steven-sheehy requested changes

2024-09-12 00:31 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +                .and(getCondition(TOKEN_AIRDROP.TOKEN_ID, request.getTokenId()));
Even with only currently supporting two columns (or really 3 but one is static), we need to handle scenarios like `/api/v1/accounts/0.0.1/airdrops/outstanding?limit=1&receiver.id=gt:2&token.id=gt:4` where the results can still have receiver=3 and token=1. There's a lot more corner cases. Hence we need to extract the logic from NftAllowanceRepositoryCustomImpl or copy it for expediency.

2024-09-12 20:10 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/TokenAirdropsMapper.java
> +    @Mapping(source = "senderAccountId", target = "senderId")
Update: I've backed out the change to rename them.

2024-09-12 20:11 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
> -    }
I've moved these methods up to the `JooqRepository` class, they are now reused by the TokenAirdropsRepository.

2024-09-12 20:22 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/TokenAirdropsMapper.java
> +public interface TokenAirdropsMapper extends CollectionMapper<TokenAirdrop, com.hedera.mirror.rest.model.TokenAirdrop> {
Thanks I have renamed this.

2024-09-12 20:22 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/AbstractCustomRepository.java
> +abstract class AbstractCustomRepository {
Got it I have renamed this.

2024-09-12 20:23 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
> +    }
These have been updated to Bounds as pagination links need multiple values.

2024-09-12 20:24 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +    private final TokenAirdropsMapper tokenMapper;
Thanks this has been renamed.

2024-09-12 20:24 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +            Direction.DESC, List.of(TOKEN_AIRDROP.RECEIVER_ID.desc(), TOKEN_AIRDROP.TOKEN_ID.desc()));
Sounds good I have updated it to exclude NFTs.

2024-09-12 20:25 UTC, edwin-greene commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.100.0__add_token_airdrop.sql
> +create index if not exists token_airdrop__receiver_id on token_airdrop (receiver_id, sender_id, token_id, serial_number);
I see, I have reverted those changes.

2024-09-12 20:25 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/NumberRangeParameterTest.java
> +    @ValueSource(strings = {"a", ".1", "someinvalidstring", "-1", "9223372036854775808", ":2000"})
Thanks I have added them.

2024-09-12 20:26 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/TokenAirdropServiceImpl.java
> +        }
Thanks, it was only through a unit test that it was possible. I have removed these lines as the other layer should handle it.

2024-09-12 20:26 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
> +        void outstandingAirdropByEntityId(String id) {
Sounds good I have simplified all of the method names.

2024-09-12 20:27 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +                .and(getCondition(TOKEN_AIRDROP.TOKEN_ID, request.getTokenId()));
I have updated this section to use shared logic from NftAllowanceRespository, moved up to the JooqRepository. 

I have some tests that fail as a result, and some more tests to add, will continue fixing this section.

2024-09-12 20:46 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Returns pending airdrops that have been sent by an account.
Thanks I have updated the description.

2024-09-13 20:22 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +                .and(getCondition(TOKEN_AIRDROP.TOKEN_ID, request.getTokenId()));
These tests are now fixed and a few added, this section (the new JooqRepository) is ready for review.

2024-09-15 23:39 UTC, steven-sheehy requested changes

2024-09-15 23:39 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/NumberRangeParameterTest.java
> +    void testGte(RangeOperator operator) {
```suggestion
    void testRangeOperator(RangeOperator operator) {
```

2024-09-15 23:39 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/NumberRangeParameterTest.java
> +                .isEqualTo(NumberRangeParameter.valueOf(null));
Use parameterized input and assert order is backwards.

```suggestion
    @ParameterizedTest
    @NullAndEmptySource
    void testEmpty(String input) {
        assertThat(input).isEqualTo(NumberRangeParameter.EMPTY);
```

2024-09-15 23:39 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Returns outstanding fungible token airdrops that have been sent by an account. NFT airdrops will not be included in the response.
```suggestion
        Returns outstanding fungible token airdrops that have been sent by an account. This API is currently under development. Support for NFT airdrops will be added in a future release.
```

2024-09-15 23:39 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +                .and(TOKEN_AIRDROP.STATE.eq(AirdropState.PENDING));
Why add this condition to base condition but `.and(TOKEN_AIRDROP.SERIAL_NUMBER.eq(0L))` is separate. Probably should move this up next to serial_number.

2024-09-15 23:39 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +        return new ConditionalFieldBounds(primary, secondary);
Probably we should combine Bound and FieldBound by moving field into Bound. As long as we don't mind leaking jooq things into higher layers.

And we should have a n-ary ConditionalFieldBounds. Plus maybe we can put an interface on the `TokenAirdropRequest` to use as this. But let's do these as follow ups.

2024-09-16 15:03 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/NumberRangeParameterTest.java
> +    void testGte(RangeOperator operator) {
Thanks I have fixed the inaccurate name.

2024-09-16 15:03 UTC, edwin-greene commented on hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/NumberRangeParameterTest.java
> +                .isEqualTo(NumberRangeParameter.valueOf(null));
Thanks! I have updated this.

2024-09-16 15:04 UTC, edwin-greene commented on hedera-mirror-rest/api/v1/openapi.yml
> +        Returns outstanding fungible token airdrops that have been sent by an account. NFT airdrops will not be included in the response.
Thanks I have updated the description.

2024-09-16 15:04 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +                .and(TOKEN_AIRDROP.STATE.eq(AirdropState.PENDING));
Sounds good I have moved this condition up.

2024-09-16 16:07 UTC, steven-sheehy approved these changes
LGTM. I think we're missing corner case test coverage in the repository layer similar to what NftAllowanceRepositoryTest has. But probably we can figure out a way to have a common test framework for multi-column pagination in a follow up.

2024-09-16 16:08 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
> +        return new ConditionalFieldBounds(primary, secondary);
Please open a ticket for this and another one for NFT support.

2024-09-16 17:41 UTC, jascks approved these changes
LGTM

2024-09-16 20:55 UTC, xin-hedera approved these changes
LGTM

2024-09-16 21:20 UTC, jnels124 approved these changes
LGTM

2024-09-16 22:32 UTC, merged