Reducing cache-control for scheduled transactions.
hashgraph/hedera-mirror-node pull request #9327
Opened 2024-09-11 01:28 UTC by mgoelswirlds

**Description**:
Reduce cache for the transactions endpoint with scheduled transactions.

This PR modifies 
* Reduces the value of max-age for `ScheduleCreate` transactions

**Related issue(s)**:

Fixes #9174

**Notes for reviewer**:
I have removed a test case in order for the builds to pass.  I have a question here , if it makes sense to separate the tests out with scheduled transactions from the others.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-09-11 01:41 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/specs/transactions/{id}/no-params.json
> -    {
This test case has been removed in order for the builds to pass. I have a question here , if it makes sense to separate the tests out with scheduled transactions from the others.

2024-09-11 15:05 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseHandler.js
> +    if (!res.get('cache-control')) {
Use a constant from express

2024-09-11 15:07 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseHandler.js
> +    }
We should not omit all headers from config just because of one header being present. Even though it only has cache-control now, `response.headers` property is intended as a generic way to add extra headers not just cache-control.

2024-09-11 15:07 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +        res.set(CACHE_CONTROL_HEADER_NAME, `public, max-age=${cacheControlMaxAge}`);
Use a constants for value

2024-09-11 15:13 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +        res.set(CACHE_CONTROL_HEADER_NAME, `public, max-age=${cacheControlMaxAge}`);
Add a break after first instance to optimize.

2024-09-11 15:14 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +const scheduleCreate = TransactionType.getName(42);
Instead of converting a hardcoded number to a string, just hardcode the string directly here.

2024-09-11 15:18 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +        !filters.some((f) => f.key === constants.filterKeys.SCHEDULED && f.value === true)
This logic is not correct. Regardless of filters, the transaction rows can contain a scheduled transaction that should not be cached as long. Specifically we should look for a schedule create that does not have a corresponding scheduled=true for the same transaction ID row in the same list.

2024-09-11 15:19 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/transactions/{id}/scheduled-transactions/scheduled-false.json
This violates the folder hierarchy. We should not create folders that don't correspond to url paths.

2024-09-11 16:36 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/{id}/no-params.json
> -    {
The spec schema supports a `responseHeaders` to set test specific response headers to validate.

Perhaps the logic in `template.js` needs to be first add folder specific response headers or the default, then merge `spec.responseHeaders`

```javascript
const getResponseHeaders = (spec, specPath) => {
  spec.responseHeaders = {
    ...(spec.responseHeaders ?? {}),
    ...getResponseHeadersFromFileOrDefault(specPath),
  };
};
```

2024-09-11 17:04 UTC, xin-hedera requested changes

2024-09-11 17:07 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  }
we may want to and a configurable duration to go back to the default longer max-age for the situation that the scheduled transaction never executes (e.g. when not enough signatures collected in 30 minutes)

2024-09-12 03:38 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/integration/template.js
>      ...getResponseHeadersFromFileOrDefault(specPath),
The order of this has been changed in the template so that the headers from the spec file can take precedence.

2024-09-12 03:39 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +  }
Still need to address the configurable duration part.

2024-09-12 14:01 UTC, mgoelswirlds commented on hedera-mirror-rest/middleware/responseHandler.js
> +    if (!res.get('cache-control')) {
Removed this with current changes.

2024-09-12 14:22 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  }
should use the existing `maxTransactionConsensusTimestampRange` config, the default value is based on how long a schedule is valid for getting ready to execute, i.e., 30 minutes

there are more corner cases to consider

- if the `SCHEDULECREATE` tx fails (note there can be duplicate `SCHEDULECREATE` txs all reaching consensus, so here fail means all `SCHEDULECREATE` with the same tx id fail), don't override the max-age
- if there is `scheduled=?` in the request URL, don't override

2024-09-12 15:13 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  }
one more corner case: if it's a query by transaction hash, don't override, since a transaction hash should always map to exact one transaction, if it exists

2024-09-12 15:26 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +  }
Ok Thanks. Looking into the corner cases now.

2024-09-15 18:37 UTC, steven-sheehy requested changes

2024-09-15 18:37 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      !transaction.scheduled
Can remove this since `transaction.scheduled` has to equal false here (the db column is not null and has a default).

2024-09-15 18:37 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      timestamp = math.subtract(currSecs, math.bignumber(transaction.consensus_timestamp).toNumber());
`transaction.consensus_timestamp` should already be a bigint. And it seems to be doing arithmetic with mixed units. `currSecs` is in seconds but `math.bignumber(transaction.consensus_timestamp).toNumber()` will be in nanoseconds.

2024-09-15 18:37 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +  }
If transaction hash or scheduled=true then there will be only one result in the list so we can simplify.

```suggestion
  if (transactions.length < 2 || filters.some((f) => f.key === constants.filterKeys.SCHEDULED)) {
    return {}; // no override
  }
```

2024-09-15 18:37 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      !transaction.scheduled
The timestamp logic is incorrect. Instead of calculating it inline, you only need to check it inside `if (hasScheduleCreate && !scheduleExecuted)` at the end. 

But it's tricky if there's multiple schedule creates in the list. Not sure it's really worth trying to micro-optimize for this corner case. Be simpler to just use the shorter cache.

2024-09-16 13:17 UTC, mgoelswirlds commented
I still need to address the new comments on the PR @steven-sheehy

2024-09-16 14:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (filters.some((f) => f.key === constants.filterKeys.SCHEDULED) || isValidTransactionHash(transactionIdOrHash)) {
should return a query context object from `extractSqlFromTransactionsByIdOrHashRequest` with fields to indicate if there is `scheduled` query param and transaction hash path variable, instead of reparsing.

2024-09-16 14:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  const currSecs = Math.floor(new Date().getTime() / 1000);
`utils.nowInNs()`

2024-09-16 14:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (hasScheduleCreate && !scheduleExecuted) {
the logic starting from the for loop with the corner cases are way too complicated and buggy.

```
let successScheduleCreateTimestamp;

foreach transaction

  if transaction is SCHEDULECREATE
    if transaction is successful
      successScheduleCreateTimestamp = transaction's consensus timestamp;
    else if transaction.scheduled
      return SHORTER_CACHE_CONTROL_HEADER;

if successScheduleCreateTimestamp !== undefined && nowInNs() - successScheduleCreateTimestamp < maxTransactionConsensusTimestampRangeNs
  return SHORTER_CACHE_CONTROL_HEADER;

return {};
```

2024-09-16 15:04 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/transactions/{id}/scheduled-create-non-scheduled-transaction.json
> +        "valid_start_timestamp": "1896279200000000001",
this is impossible: two transactions with the same transaction id, both are successful, none of them has `scheduled = true`.

2024-09-16 16:47 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +  if (filters.some((f) => f.key === constants.filterKeys.SCHEDULED) || isValidTransactionHash(transactionIdOrHash)) {
Removing these.

2024-09-16 16:47 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +      !transaction.scheduled
Removing the condition due to the changes suggested by Xin.

2024-09-16 16:57 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (hasScheduleCreate && !scheduleExecuted) {
@mgoelswirlds I updated the pseudo code to fix the `else if` indentation

2024-09-16 18:06 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +      timestamp = math.subtract(currSecs, math.bignumber(transaction.consensus_timestamp).toNumber());
Actually, `transaction.consensus_timestamp ` is not a bigint so it would need explicit conversion. But will fix the equation.

2024-09-16 18:08 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +      timestamp = math.subtract(currSecs, math.bignumber(transaction.consensus_timestamp).toNumber());
Then you should go back use rows instead of the formatted transactions array

2024-09-16 19:35 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (filters.some((f) => f.key === constants.filterKeys.SCHEDULED) || isValidTransactionHash(transactionIdOrHash)) {
the changes made don't match what I asked for: `if there is scheduled query param` is not `if scheduled flag is true`

2024-09-16 19:39 UTC, xin-hedera requested changes

2024-09-16 19:39 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +        return SHORTER_CACHE_CONTROL_HEADER;
I updated my pseudo code and notified you, this is wrong logic.

2024-09-17 02:21 UTC, mgoelswirlds commented on hedera-mirror-rest/middleware/responseHandler.js
> +  responseContentType,
I did try changing this. Works for network supply but many other tests fail complaining about the `Invalid media type`. Looking further into what needs to be resolved here.

2024-09-17 20:36 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseHandler.js
> +    const contentType = (responseHeader === undefined || typeof responseHeader === 'object') ? APPLICATION_JSON : responseHeader ;
why is such logic needed?

Will this not work?

- default to application json content type, i.e., put it into the `headers.default` config (in the default application.yml file`
- override if needed in individual handlers

2024-09-17 20:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +    if (TransactionType.getName(transaction.type) === scheduleCreate) {
nit, just compare the transaction type proto id

2024-09-17 20:36 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +}
spacing please

2024-09-17 20:49 UTC, mgoelswirlds commented on hedera-mirror-rest/middleware/responseHandler.js
> +    const contentType = (responseHeader === undefined || typeof responseHeader === 'object') ? APPLICATION_JSON : responseHeader ;
This logic was needed because network controller was setting a different content type for supply.
So you are suggesting I move all of the custom logic to the applciation.yaml right? Will do that.

2024-09-17 21:07 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseHandler.js
> +    const contentType = (responseHeader === undefined || typeof responseHeader === 'object') ? APPLICATION_JSON : responseHeader ;
That is NOT my suggestion. What I said is move the default to where it’s supposed to be. And leave whatever customization in individual handlers…

2024-09-17 23:49 UTC, mgoelswirlds commented on hedera-mirror-rest/__tests__/middleware/responseHandler.test.js
> +    expect(mockResponse.set).toHaveBeenCalledWith({'Content-type': 'application/json; charset=utf-8'},headers.path[mockRequest.route.path]);
I have spent a lot of time trying to fix these 2 tests with this new approach. But have not been successful.
Would like to get the other parta approved and continue working on these on the side.

2024-09-18 21:41 UTC, steven-sheehy requested changes

2024-09-18 21:41 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +  if (scheduled || isTransactionHash) {
As I mentioned [previously](https://github.com/hashgraph/hedera-mirror-node/pull/9327#discussion_r1760252662).
```suggestion
function getTransactionsByIdOrHashCacheControlHeader(transactionsRows) {
  if (transactionsRows.length < 2) {
```

2024-09-18 21:41 UTC, steven-sheehy commented on hedera-mirror-rest/config/application.yml
> +          "Content-type": "application/json; charset=utf-8"}
Use consistent casing.
```suggestion
          "content-type": "application/json; charset=utf-8"}
```

2024-09-18 21:41 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      if (TransactionResult.isSuccessful(transaction.result)) {
We can combine these two if statements since it's not like a schedule create can have scheduled=true

2024-09-18 21:41 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +      && (utils.nowInNs() - successScheduleCreateTimestamp) < maxTransactionConsensusTimestampRangeNs ) {
nit: Readability

```suggestion
  const elapsed = utils.nowInNs() - successScheduleCreateTimestamp;
  if (successScheduleCreateTimestamp && elapsed < maxTransactionConsensusTimestampRangeNs ) {
```

2024-09-18 21:41 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +  let scheduledParamExists = false;
Think updates to this method can be undone with my other comment.

2024-09-18 22:07 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +      if (TransactionResult.isSuccessful(transaction.result)) {
ok.

2024-09-18 22:09 UTC, mgoelswirlds commented on hedera-mirror-rest/config/application.yml
> +          "Content-type": "application/json; charset=utf-8"}
Actually other places in the code so you `"Content-type"` but will change it here.

2024-09-19 01:41 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (scheduled || isTransactionHash) {
not entirely true. it's possible to have `schedule=false` query param and return multiple transactions for the same transaction id. Then we can have a successful schedulecreate in the response with all others failed, ideally we should use the longer max-age because the existence of the `schedule=?` query param.

However given that such scenario happens rarely, and using a shorter max-age doesn't hurt function, agree we can go with the simpler approach.

2024-09-19 13:59 UTC, steven-sheehy commented on hedera-mirror-rest/transactions.js
> +  if (scheduled || isTransactionHash) {
I missed that this scheduled variable represents the query param exists and not that it exists and is set to true, hence my comment. We can keep the scheduled check but omit isTransactionHash and just use list size for that.

2024-09-19 18:35 UTC, xin-hedera requested changes

2024-09-19 18:35 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +function getTransactionsByIdOrHashCacheControlHeader(transactionsRows, isTransactionHash, scheduled) {
coding style consistency, please use arrow function

```suggestion
const getTransactionsByIdOrHashCacheControlHeader = (transactionsRows, isTransactionHash, scheduled) =>  {
```

2024-09-19 18:35 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  const {query, params, scheduled, isTransactionHash} = await extractSqlFromTransactionsByIdOrHashRequest(
obviously missing test coverage,  the returned object no longer has `scheduled` key, the extracted value for `scheduled` will be always `undefined`

2024-09-19 18:53 UTC, mgoelswirlds commented on hedera-mirror-rest/middleware/responseHandler.js
> +    res.set(mergedHeaders);
I tried adding a unit test, but that would need to work with mocking the result and then there seemed no point to hardcode what set and get would do.
```
  test('should merge headers in a case insesitive manner', async () => {
    const path = '/api/v1/transactions/:transactionId';
    headers.path[path] = { "Cache-control": "public, max-age=1",
      "content-Type": "application/json; charset=utf-8" };
    mockResponse.locals[responseHeadersLabel] = { "cache-Control": "public, max-age=1",
      "Content-type": 'text/plain; charset=utf-8' };
    await responseHandler(mockRequest, mockResponse, null);
    expect(mockResponse.getHeader('content-type')).toHaveLastReturnedWith(mockResponse.locals[responseHeadersLabel]['Content-type']);
  });
```
The network/supply spec tests do test the case insensitiveness to some extend atleast for` headers.default` and `res.locals[responseHeadersLabel] `
If that is acceptable , I can work on a future PR to add a more comprehensive test for this .

2024-09-19 18:55 UTC, mgoelswirlds commented on hedera-mirror-rest/model/transactionResult.js
> +  return getSuccessProtoIds().includes(result);
I have added a constant which calls `getSuccessProtoIds()` once.

2024-09-19 20:18 UTC, xin-hedera requested changes

2024-09-19 20:18 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (scheduledParamExists || transactionsRows.length < 2) {
Well, we have to remove `transactionRows.length < 2` since this is exactly the most common scenario that we don't want to use the longer max-age for

- query by just transaction id, no `scheduled=?` flag
- the response is a single successful schedulecreate transaction, the scheduled transaction has yet to reach consensus

2024-09-19 20:18 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +const _SUCCESS_PROTO_IDS = TransactionResult.getSuccessProtoIds();
why prefix it with `_`? we never do that per our coding style.

2024-09-19 20:20 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (scheduledParamExists || transactionsRows.length < 2) {
a follow-up comment is, the test cases are either wrong, or there's missing coverage

2024-09-20 15:10 UTC, xin-hedera commented on hedera-mirror-rest/transactions.js
> +  if (scheduledParamExists || transactionsRows.length < 2) {
I don't know what stops you from creating a spec based integration test.

we have all building blocks. We can for sure set up data with just one successful schedule create transaction, or one successful schedule create transaction + many other failed transactions with the same tx id, we can use `fakeTime` feature in a spec test to mimic the scenario that the time elapsed from the schedule tx's consensus time to the `fakeTime` is less than `maxTransactionConsensusTimestampRangeNs`, then we should expect the shorter max-age.

When we don't use `fakeTime`, and set the schedulecreate consensus timestamp sufficiently old in the past, we should expect the standard longer max-age.

2024-09-20 20:23 UTC, mgoelswirlds commented on hedera-mirror-rest/transactions.js
> +  if (scheduledParamExists || transactionsRows.length < 2) {
I have added them with fake-time and the ones without were already added. Thanks.

2024-09-20 20:48 UTC, xin-hedera requested changes

2024-09-20 20:48 UTC, xin-hedera commented on hedera-mirror-rest/controllers/networkController.js
> +  static contentTypeTextPlain = {'Content-type' : 'text/plain; charset=utf-8'};
shouldn't this be all lower case and even better use a constant for the key instead?

```suggestion
  static contentTypeTextPlain = {'content-type' : 'text/plain; charset=utf-8'};
```

2024-09-21 02:01 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseHandler.js
> +const CONTENT_TYPE_HEADER = 'content-type';
why have the same constant defined in two places?

2024-09-21 02:03 UTC, xin-hedera approved these changes

2024-09-21 02:04 UTC, xin-hedera commented
I approved it since I'm off on Monday so don't unnecessarily block the PR. There is still one minor change I asked for.

2024-09-23 15:38 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-09-23 17:34 UTC, jascks approved these changes
LGTM

2024-09-23 17:38 UTC, mgoelswirlds commented on hedera-mirror-rest/middleware/responseHandler.js
> +  responseContentType,
I have updated this so marking this conversation resolved.

2024-09-23 17:39 UTC, mgoelswirlds commented on hedera-mirror-rest/middleware/responseHandler.js
> +const CONTENT_TYPE_HEADER = 'content-type';
Removed this and hence resolving it to unblock.

2024-09-23 17:41 UTC, jnels124 approved these changes
LGTM

2024-09-23 17:45 UTC, merged