Delete redundant web3j jars
hashgraph/hedera-mirror-node pull request #9348
Opened 2024-09-13 15:44 UTC by bilyana-gospodinova

**Description**:
After adding the gradle tasks for compiling historical contracts with older version of solidity - 0.8.7. After assemble task the build/libs directory is polluted with a new 0.8.7-web3j.jar and then running dockerBuild command fails encountering this 0.8.7 jar.

This PR adds a new gradle task that deletes these jars.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9344

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2024-09-13 15:47 UTC, kselveliev approved these changes

2024-09-13 17:39 UTC, steven-sheehy requested changes

2024-09-13 17:39 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +
This is the incorrect fix. It's not like there's two jars being produced, it's just one jar with the wrong version. The contents are identical to the one with the correct version in dockerBuild. 

The correct fix is to remove this line in `resolveSolidityHistorical` which accidentally overrides the project.version. It's not a solidity version property.

```java
version = historicalSolidityVersion
```

2024-09-14 09:31 UTC, bilyana-gospodinova commented on hedera-mirror-web3/build.gradle.kts
> +
Oh, nice catch! Fixed.

2024-09-14 14:22 UTC, steven-sheehy approved these changes

2024-09-14 17:56 UTC, merged