Initial commit, adding the bootstrap from export guide, bootstrap.sh script, and linking the bootstrap guide to the main DB README.md doc
hashgraph/hedera-mirror-node pull request #9390
Opened 2024-09-17 20:43 UTC by nirbosl

**Description**:
- Added a new script named `bootstrap.sh` which is used to import the exported mirrornode content found in the [mirrornode-db-export bucket](https://console.cloud.google.com/storage/browser/mirrornode-db-export)
- Added a new document named `bootstrap.md` which contains a guide with info and instructions on how to setup a fresh mirrornode DB, and how to import the exported data available in the bucket linked above.
- Updated `docs/database/README.md` with a paragraph linking to `bootstrap.md`

**Related issue(s)**:

- Closes https://github.com/swirlds/infrastructure/issues/6641
- Closes https://github.com/swirlds/infrastructure/issues/6642

**Checklist**

- [x] Documented
  - In-script comments
  - `bootstrap.md` as a how-to guide
- [x] Tested by importing a small dataset taken from an actual mainnet DB export

2024-09-18 16:37 UTC, nirbosl commented
I've tested the import script using a small dataset and it has completed successfully.

2024-09-18 20:02 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +  } | psql -q -v ON_ERROR_STOP=1; then
Should be able to reduce to one command. Not sure about quoting but something like: `psql -q -v ON_ERROR_STOP=1 --single-transaction --command="copy $table from program 'gunzip -c "$file"' WITH CSV HEADER"`

2024-09-18 20:21 UTC, nirbosl commented on docs/database/bootstrap.md
> +psql -f schema.sql
Uploaded it to the bucket now.

2024-09-19 15:31 UTC, nirbosl commented on docs/database/bootstrap.md
> +export PGHOST="DB_IP_ADDRESS"
PGPORT added.

2024-09-19 15:35 UTC, nirbosl commented on docs/database/bootstrap.md
> +This guide provides step-by-step instructions for setting up a fresh PostgreSQL 14 database and importing Mirror Node data into it. The process involves initializing the database, configuring environ
Modified - no more "14" in the intro, and 14 -> 16 in the prereqs section.

2024-09-19 15:35 UTC, nirbosl commented on docs/database/bootstrap.md
> +  - [Table of Contents](#table-of-contents)
Removed the two TOC lines.

2024-09-19 16:47 UTC, nirbosl commented on docs/database/bootstrap.md
> +Add the following line **before** running the `init.sh` script:
I've modified init.sh in a way that would allow making this conditional.
I've introduced `IS_GCP_CLOUD_SQL` and updated the guide to reflect it as well, Cloud SQL users will need to set it as an extra var in addition to the others (`export IS_GCP_CLOUD_SQL="true"`) and the init script will do the rest.

2024-09-19 16:55 UTC, nirbosl commented on docs/database/bootstrap.md
> +GRANT mirror_node TO postgres;
Done.
PGUSER is now being passed into the psql context and used in the grant.
`--set "pgUser=${PGUSER}"`

2024-09-19 17:23 UTC, nirbosl commented on docs/database/bootstrap.md
> +If you are using **Google Cloud SQL** for your PostgreSQL database, an additional step is required before running the `init.sh` script to ensure proper initialization.
Done.

2024-09-19 17:29 UTC, nirbosl commented on docs/database/bootstrap.md
> +- **Name:** `bootstrap.sh`
Agreed, that is my longer term plan.
Right now, I'm trying to get a working solution out the door.
In future development of this script we can try to make it closer to a one-stop-shop.

2024-09-19 17:34 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +set -m
I've tried to set that, however it does not play nice with the multiple parallel processes and causes the parent script to exit.

The script is built for resilience, hence individual threads failing will not stop it, it will however be logged, the correct status updated in the tracking file, then the failed files will be retried on the next run of the script while skipping files that have succeeded.

2024-09-19 18:25 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +log() {
Re-organized the script.

2024-09-19 18:25 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +LOCK_FILE="import_tracking.lock"
Re-organized the script.

2024-09-19 18:33 UTC, nirbosl commented on docs/database/bootstrap.md
> +- **Bash Version Compatibility:**
Added as a check in the script and removed this section from the doc.
The script will exit if it fails this check and print an appropriate message.

2024-09-19 18:41 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  grant mirror_node to :pgUser;
`revoke mirror_node from :pgUser` to roll back the change at the end

2024-09-19 18:52 UTC, nirbosl commented on docs/database/bootstrap.md
> +3. **Alternatively, Collect Specific Files to Re-import:**
True.
This is a relic I've missed since before the implementation of import tracking and the change to transactional sql commands that allows to safely restart files that have not been imported successfully.

I've revised the section, it's leaner now.

2024-09-19 19:30 UTC, nirbosl commented on docs/database/bootstrap.md
> +- **Required Tools:** Ensure that all required tools (`psql`, `gunzip`, `realpath`, `flock`) are installed on your system.
- Required tools removed, I've reworked the already-exiting check for the tools in the script, it will now check and aggregate all missing tool names into an array and print it out once, instead of stopping at the first missing tool.
- Resuming imports removed, seems redundant as it's very much like the summary of "Handling Failed Imports".
- Security note moved to a more appropriate location, under the "Configure Environment Variables" section.
- The rest of the notes - merged into the "Notes on data consistency" block under "Steps to Handle Failed Imports"

2024-09-19 22:14 UTC, nirbosl commented on docs/database/bootstrap.md
> +   Ensure you have the [Google Cloud SDK](https://cloud.google.com/sdk/docs/install) installed and authenticated:
Moved to pre-reqs.

2024-09-19 23:05 UTC, nirbosl commented on docs/database/bootstrap.md
> +   gsutil -u YOUR_GCP_PROJECT_ID -m cp -r gs://mirrornode-db-export/* /path/to/db_export/
Yes, subdirs named after the version they contain, then once implemented - another subdir in that, one for full and another for no-hcs.

I still need to think through how to prevent people from downloading the  newer version while it is partial - before the upload completes.
Might be able to set the content being uploaded as private until all the content is uploaded, then change to public.
Will need to look into this some more, not sure how to not break downloads in the middle when deleting the older version, maybe we'll keep two versions.
We'll cross that bridge once we get there.

In the meantime, I've created a directory named `0.111.0` in the bucket and moved all of the export's content into it.
Updated the doc accordingly.

2024-09-19 23:13 UTC, nirbosl commented on docs/database/bootstrap.md
> +- A Google Cloud Platform (GCP) account with a valid billing account attached (required for downloading data from a Requester Pays bucket).
There's a check in the script for these commands, however I've added them to the pre-requisites section as well, so people can set everything up first instead of finding out about this for the first time when the script will fail as they run it and print out the list of tools they need.

2024-09-19 23:14 UTC, nirbosl commented on docs/database/bootstrap.md
> +Before initializing your Mirror Node with the imported database, it's crucial to ensure version compatibility.
Moved this to #1 in the pre-requisites, as high up in the doc as possible.

2024-09-19 23:19 UTC, nirbosl commented on docs/database/bootstrap.md
> +### Steps to Handle Failed Imports:
Moved the "steps to handle failed imports" into the troubleshooting section.

2024-09-20 19:44 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +  } | psql -q -v ON_ERROR_STOP=1; then
Coonverted to:
`if gunzip -c "$file" | psql -q -v ON_ERROR_STOP=1 -c "\COPY $table FROM STDIN WITH CSV HEADER"; then`

Imported a file with it and compared to the select count(*) of the table - perfect match.

2024-09-20 19:47 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sh
> +  grant mirror_node to :pgUser;
Added a conditional revoke at the bottom of the script:

```
-- Conditional REVOKE statement for Google Cloud SQL
\if :isGcpCloudSql
  revoke mirror_node from :pgUser;
\endif
```

2024-09-20 22:29 UTC, steven-sheehy requested changes

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +- [Additional Notes](#additional-notes)
This ToC doesn't seem to be updated to reflect the headers. Please scan through all sections and update.

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +export WEB3_PASSWORD="SET_PASSWORD"
A better experience would be to create a `bootstrap.env` with all the exports and ask the user to just adjust all defaults. Then inside `bootstrap.sh` run `source ./bootstrap.env`.

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +curl -O https://raw.githubusercontent.com/hashgraph/hedera-mirror-node/main/hedera-mirror-importer/src/main/resources/db/scripts/init.sh
Technically they should download the init.sh version that's specified in MIRRORNODE_VERSION

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +psql -f schema.sql
It's confusing that both schema.sql and MIRRORNODE_VERSION files are referenced in the docs before they are requested to be downloaded. Users following the steps sequentially will get stuck.

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +- It is configured as **Requester Pays**, meaning you need a GCP account with a valid billing account attached to download the data.
It might be useful to [link](https://docs.hedera.com/hedera/core-concepts/mirror-nodes/run-your-own-beta-mirror-node/run-your-own-mirror-node-gcs#id-1.-obtain-google-cloud-platform-requester-pay-information) to the Hedera docs that show how to create such an account.

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +   ```
Screen/tmux might be a bit more complex then just adding nohup or disown to the bootstrap.sh command.

2024-09-20 22:29 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +   echo "EXIT STATUS: $?"
This only works if they are running it in the foreground. Better to have them check the final few lines of the log.

2024-09-23 03:14 UTC, nirbosl commented on docs/database/bootstrap.md
> +- [Additional Notes](#additional-notes)
Updated the ToC.
Clicked all ToC links that now lead to the correct sections.

2024-09-23 03:25 UTC, nirbosl commented on docs/database/bootstrap.md
> +export WEB3_PASSWORD="SET_PASSWORD"
Yes, I've gone ahead and brought the future plans to the present.

Added `bootstrap.env` for the users to download alongside the script and configure all the env vars in there.
Once done and the script is executed, it sources the .env file and uses its values whenever and however is required to get the job done.

The script now works like this, for a better UX and a lot less manual intervention:

- sources bootstrap.env for all the values it'd need
- grabs the version from MIRRORNODE_VERSION file
- downloads `init.sh` using the version number grabbed from the file: `INIT_SH_URL="https://raw.githubusercontent.com/hashgraph/hedera-mirror-node/refs/tags/v$MIRRORNODE_VERSION/hedera-mirror-importer/src/main/resources/db/scripts/init.sh"`
- sets +x to `init.sh`
- initializes the db by running `init.sh`
- if successful, changes PGUSER / PGDATABASE to `mirror_node` an assigns `PGPASSWORD="$OWNER_PASSWORD"`
- imports `schema.sql`
- if successful, begin transactional import of files: `if gunzip -c "$file" | psql -q -v ON_ERROR_STOP=1 -c "BEGIN; COPY $table FROM STDIN WITH CSV HEADER; COMMIT"; then`

2024-09-23 03:26 UTC, nirbosl commented on docs/database/bootstrap.md
> +curl -O https://raw.githubusercontent.com/hashgraph/hedera-mirror-node/main/hedera-mirror-importer/src/main/resources/db/scripts/init.sh
No longer relevant, the script has been changed to do most of the work internally, including grab the version from MIRRORNODE_VERSION and use it to download init.sh from the appropriate tag.

2024-09-23 03:27 UTC, nirbosl commented on docs/database/bootstrap.md
> +psql -f schema.sql
Again, the script does a lot more of the heavy lifting and the docs updated accordingly.

2024-09-23 03:28 UTC, nirbosl commented on docs/database/bootstrap.md
> +- It is configured as **Requester Pays**, meaning you need a GCP account with a valid billing account attached to download the data.
This topic has been revised and that link is included now.

2024-09-23 03:35 UTC, nirbosl commented on docs/database/bootstrap.md
> +   ```
The doc has been updated with the following start and stop commands:
Start: `nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log &`

Graceful stop: `kill -TERM -- -$(cat bootstrap.pid)`

Hard stop (may leave background jobs running): `kill -KILL -$(cat bootstrap.pid)`

2024-09-23 03:37 UTC, nirbosl commented on docs/database/bootstrap.md
> +   echo "EXIT STATUS: $?"
No longer relevant after the updated to the script and doc file.

2024-09-25 16:17 UTC, steven-sheehy requested changes

2024-09-25 16:17 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +  if gunzip -c "$file" | psql -q -v ON_ERROR_STOP=1 -c "BEGIN; COPY $table FROM STDIN WITH CSV HEADER; COMMIT"; then
nit: Can omit begin/commit as any single statement will run within a transaction. Or if you're extra concerned can add --single-transaction.

2024-09-25 16:54 UTC, nirbosl commented on docs/database/bootstrap.md
> +   nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log &
It does, but these extra params redirect the script's self `stderr` to the log, if the script itself stops / fails / throws errors, these errors will be written to `bootstrap.log`, albeit without a timestamp - but the error that caused the script to fail will be logged for easier debugging.

`stdout` is redirected to `/dev/null` (all this is written using the `log()` function in the script), and `stderr` is appended to `bootstrap.log`

Since the script is executed with nohup, if it were to fail - these are the errors thrown to the shell which ran it, hence they would not be visible/accessible without writing them to a file.

2024-09-25 16:56 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +  if gunzip -c "$file" | psql -q -v ON_ERROR_STOP=1 -c "BEGIN; COPY $table FROM STDIN WITH CSV HEADER; COMMIT"; then
I am concerned, mainly because if I use this very same command without begin/commit - the next execution fails due to data already existing.

I'll give it a whirl with `--single-transaction`.

2024-09-25 16:58 UTC, nirbosl commented on docs/database/bootstrap.md
> +  nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log & echo $! > bootstrap.pid
Correct, a relic from before I just added it into the script to populate the PID in this file.
Fixing it now.

2024-09-25 17:08 UTC, nirbosl commented on docs/database/bootstrap.md
> +   nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log &
Added this to the script instead, would result in a cleaner execution command:

```
# Redirect stderr to bootstrap.log in case the script itself fails
# Redirect stdout to /dev/null since the script uses the log() function to write all output to bootstrap.log
exec 1>/dev/null 2>>bootstrap.log
```

2024-09-25 17:39 UTC, nirbosl commented on docs/database/bootstrap.md
> +   nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log &
I take it back, while it is cleaner in terms of execution, when I run it like this - nohup throws this to screen and creates a `nohup.out` file:
`nohup: ignoring input and appending output to 'nohup.out'`

Do you have any idea how to do this differently? if not, I'll restore it to the way it was, with redirections in the command line.

2024-09-25 17:42 UTC, nirbosl commented on hedera-mirror-importer/src/main/resources/db/scripts/bootstrap.sh
> +  if gunzip -c "$file" | psql -q -v ON_ERROR_STOP=1 -c "BEGIN; COPY $table FROM STDIN WITH CSV HEADER; COMMIT"; then
Replaced begin/commit with --single-transaction.

2024-09-25 19:44 UTC, steven-sheehy commented on docs/database/bootstrap.md
> +   nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log &
No, can restore it. I was just concerned it was duplicating the logic like the pid file was.

2024-09-25 21:41 UTC, nirbosl commented on docs/database/bootstrap.md
> +   nohup setsid ./bootstrap.sh 8 /path/to/db_export > /dev/null 2>> bootstrap.log &
Reverted this change.

2024-09-26 04:52 UTC, steven-sheehy approved these changes
LGTM

2024-09-26 20:39 UTC, jnels124 approved these changes
LGTM

2024-09-26 20:45 UTC, xin-hedera approved these changes
LGTM

2024-09-26 20:52 UTC, merged