Add Various Citus Runbooks
hashgraph/hedera-mirror-node pull request #9398
Opened 2024-09-18 03:19 UTC by jnels124

**Description**:
* add runbook + script to take volume snapshot
* add runbook + script to restore volume snapshot
* add runbook to increase disk size
* add runbook to change citus machine type
* made slight adjustment to remove disk size from citus config map and node labels

**Related issue(s)**:

Fixes #7763 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-09-18 03:23 UTC, jnels124 commented
will fix formatting issues when addressing any other pr feedback

2024-09-18 03:24 UTC, jnels124 commented on docs/runbook/scripts/restore-volume-snapshot.sh
> +GCP_K8S_CLUSTER_NAME="${GCP_K8S_CLUSTER_NAME-snapshot-restore}"
will remove these defaults for lines 5 and 6

2024-09-24 02:25 UTC, jnels124 commented on docs/runbook/scripts/restore-volume-snapshot.sh
> +  CURRENT_CONTEXT=$(kubectl config current-context)
need to validate cluster name and cluster region

2024-09-30 13:53 UTC, steven-sheehy commented on docs/runbook/create-disk-snapshot-for-citus-cluster.md
> +   `./create-volume-snapshot.sh`
Where is this script?

2024-09-30 15:34 UTC, jnels124 commented on docs/runbook/create-disk-snapshot-for-citus-cluster.md
> +   `./create-volume-snapshot.sh`
oops renamed it to `volume-snapshot.sh`. It is in `doc/runbook/script`

2024-09-30 17:05 UTC, xin-hedera commented on docs/runbook/scripts/restore-volume-snapshot.sh
> +    );"
it's cleaner to just run the same SQL on every `master` of all the groups, instead of duplicating the same command and running it with `run_command_on_workers`

I think we can also move fixing superuser password part here.

2024-10-04 14:17 UTC, jnels124 commented on docs/runbook/scripts/restore-volume-snapshot.sh
> +    );"
will do

2024-10-10 01:32 UTC, jnels124 commented on docs/runbook/change-citus-node-pool-machine-type.md
> +   <br>
Since the stateful set is scaled down gracefully, this shouldn't be needed right? Just double checking because if it is needed here, I should add it to other run books that shut down the cluster

2024-10-10 17:22 UTC, xin-hedera commented on docs/runbook/change-citus-node-pool-machine-type.md
> +   <br>
checked again and in case of scaling down the statefulset, postgres server will indeed shut down gracefully, so restarting the whole cluster is not needed.

2024-10-10 17:38 UTC, xin-hedera requested changes

2024-10-11 18:55 UTC, steven-sheehy requested changes

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/change-citus-node-pool-machine-type.md
> +   `gcloud container node-pools update {poolName} --project {gcpProjectName} --cluster {k8sClusterName} --location {clusterRegion} --machine-type {machineType`
missing closing }

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/create-disk-snapshot-for-citus-cluster.md
> +   `gcloud container clusters get-credentials {clusterName} --region {clusterRegion} --project {gcpProjectName}`
Is this step necessary? Everyone should have the cluster credentials already.

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/increase-zfs-disksize.md
> +   `kubectl get pv -o json |jq -r '.items[]|select(.metadata.annotations."pv.kubernetes.io/provisioned-by"=="zfs.csi.openebs.io" and .status.phase == "Bound")|"\(.spec.claimRef.namespace) \(.spec.cla
Maybe show some example output since this step requires manual copying of part of the output.

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/increase-zfs-disksize.md
> +   `kubectl get pv -o json |jq -r '.items[]|select(.metadata.annotations."pv.kubernetes.io/provisioned-by"=="zfs.csi.openebs.io" and .status.phase == "Bound")|"\(.spec.claimRef.namespace) \(.spec.cla
Can simplify. Can add a grep -E '(coordinator|worker) to filter further if needed, but should be pretty obvious even without.

```suggestion
   `kubectl get pv -o custom-columns='NAME:.metadata.name,CAPACITY:..spec.capacity.storage,NODE_ID:.spec.nodeAffinity.required.nodeSelectorTerms[0].matchExpressions[0].values[0]' --sort-by=.spec.capacity.storage`
```

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/upgrade-k8s-version-citus-nodepool.md
> +   `flux suspend helmrelease -n {namespace} {releaseName}`
This is rendered on the same line as the text.

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/upgrade-k8s-version-citus-nodepool.md
> +   `flux resume helmrelease -n {namespace} {releaseName} --timeout=30m`
Rendered on same line

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/restore-citus-from-disk-snapshot.md
> +   `helm upgrade --install {releaseName} hashgraph/hedera-mirror --version {version} -n {clusterNamespace} --values {pathToCitusValuesYaml}`
Think we can omit these steps since we use gitops to deploy charts.

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/restore-citus-from-disk-snapshot.md
> +   `SNAPSHOT_ID=${SNAPSHOT_EPOCH} GCP_PROJECT=${TARGET_CLUSTER_PROJECT} GCP_K8S_CLUSTER_NAME=${TARGET_CLUSTER_NAME} GCP_K8S_CLUSTER_REGION=${TARGET_CLUSTER_REGION} GCP_SNAPSHOT_PROJECT=${GCP_SNAPSHOT
Move each env variable to a separate export line as the first step (except SNAPSHOT_ID). Or if it makes sense to read user input during the script.

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/scripts/volume-snapshot.sh
> +  echo "GCP_PROJECT is not set and is required. Exiting"
It's a good practice to add a log function that prints with a timestamp for all echo statements.

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/scripts/volume-snapshot.sh
> +
set -euxo pipefail

2024-10-11 18:55 UTC, steven-sheehy commented on docs/runbook/scripts/volume-snapshot.sh
> +DISK_PREFIX=$(helm get values "${HELM_RELEASE_NAME}" -n "${COMMON_NAMESPACE}" -o json |jq -r '.zfs.init.diskPrefix')
Preferably not depend upon helm and just have the user type in the disk prefix

2024-10-11 19:23 UTC, jnels124 commented on docs/runbook/change-citus-node-pool-machine-type.md
> +   <br>
they should be creating a new line, otherwise the command just starts next to the text if there is space.

2024-10-11 19:24 UTC, jnels124 commented on docs/runbook/change-citus-node-pool-machine-type.md
> +   `kubectl exec -it -n {namespace} -c patroni mirror-citus-coord-0 -- patronictl restart mirror-citus`
Yes it does. Going to remove this statement anyways as it was requested in a different comment but after further discussion determined it is not needed

2024-10-24 15:29 UTC, jnels124 commented on docs/runbook/create-disk-snapshot-for-citus-cluster.md
> +   `gcloud container clusters get-credentials {clusterName} --region {clusterRegion} --project {gcpProjectName}`
This is just indicating that they should change context to point to the cluster being snapshotted

2024-10-25 21:33 UTC, jnels124 commented on docs/runbook/scripts/utils.sh
> +  kubectl exec -it -n "${namespace}" "${HELM_RELEASE_NAME}-citus-coord-0" -- psql -U mirror_rest -d mirror_node -c "select * from transaction limit 10"
will add container

2024-10-28 15:31 UTC, xin-hedera approved these changes
LGTM

2024-10-28 18:29 UTC, steven-sheehy requested changes

2024-10-28 18:29 UTC, steven-sheehy commented on docs/runbook/upgrade-k8s-version-citus-nodepool.md
> +     unrouteTraffic "${namespace}"
Can move to a standalone script

2024-10-28 18:29 UTC, steven-sheehy commented on docs/runbook/upgrade-k8s-version-citus-nodepool.md
> +   export POOLS_TO_UPDATE=("${GCP_WORKER_POOL_NAME}" "${GCP_COORDINATOR_POOL_NAME}" "default-pool")
Could move to read user input to be consistent. Same for other runbook with env vars. Can also do as followup

2024-10-30 19:57 UTC, steven-sheehy approved these changes
LGTM

2024-10-30 20:07 UTC, xin-hedera approved these changes
LGTM

2024-10-31 15:04 UTC, merged