Add hedera app dependency to hedera-mirror-web3
hashgraph/hedera-mirror-node pull request #9399
Opened 2024-09-18 13:04 UTC by IvanKavaldzhiev

**Description**:
Add `com.hedera.hashgraph:app` as a dependency in web3, so that the work for integrating reusable services is unblocked.

In addition, this PR stabilizes some inconsistent failing integration tests.

Fixes #9249 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-09-18 17:36 UTC, steven-sheehy requested changes

2024-09-18 17:36 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return getSemanticEvmVersion().minor() > 46;
This is a breaking change whenever a major version bump occurs. Please use https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/HapiUtils.java#L38

2024-09-18 17:36 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/SemanticVersionConvertor.java
> +        return new SemanticVersion(0, Integer.parseInt(versions[1]), 0, "", "");
This breaks with non-zero major. Can we use https://github.com/hashgraph/hedera-services/blob/b2ea7600799d5df3921151e38be498a14d3d9af9/hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/SemanticVersionConverter.java instead of this class?

2024-09-18 17:36 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return !(getSemanticEvmVersion().minor() < 46
Same

2024-09-19 14:29 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/SemanticVersionConvertor.java
>  public class SemanticVersionConvertor implements Converter<String, SemanticVersion> {
Can we not directly use the upstream [SemanticVersionConverter.java](https://github.com/hashgraph/hedera-services/blob/b2ea7600799d5df3921151e38be498a14d3d9af9/hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/SemanticVersionConverter.java)? Is it not available in the library or just that we need to use it with Spring Converter interface? If the latter can just use this class to delegate to upstream.

2024-09-19 15:10 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/SemanticVersionConvertor.java
>  public class SemanticVersionConvertor implements Converter<String, SemanticVersion> {
We have access directly to the upstream `SemanticVersionConverter`, however it implements `ConfigConverter<SemanticVersion>`. I couldn't configure Spring to automatically use the upstream class without manually providing implementation for `Converter<String, SemanticVersion>`.

2024-09-19 19:01 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/SemanticVersionConvertor.java
>  public class SemanticVersionConvertor implements Converter<String, SemanticVersion> {
That's why I said delegate to upstream. 

```java
public class SemanticVersionConvertor implements Converter<String, SemanticVersion> {

    private final com.hedera.node.config.converter.SemanticVersionConverter delegate = new com.hedera.node.config.converter.SemanticVersionConverter();

    @Override
    public SemanticVersion convert(String source) {
        return delegate.convert(source);
    }
}

2024-09-19 19:12 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/SemanticVersionConvertor.java
>  public class SemanticVersionConvertor implements Converter<String, SemanticVersion> {
Oh, I thought you were referring to a way of completely removing the SemanticVersionConvertor class implementation. I will adapt this delegate approach.

2024-09-19 21:52 UTC, steven-sheehy approved these changes
LGTM

2024-09-19 21:53 UTC, merged