9379 update jooq repository conditionalfieldbounds to improve reusability
hashgraph/hedera-mirror-node pull request #9424
Opened 2024-09-20 21:13 UTC by edwin-greene

**Description**:
Updates the Bound class to include fields. 
Simplifies the JooqRepository to only accept Bounds as parameters.
Updates the JooqRepository to support N-numbered conditions. 

**Related issue(s)**:

Fixes #9379 

**Notes for reviewer**:
This should not be merged until the work for pagination for airdrop nfts is completed in #9378 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-09-20 21:16 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    public Bound(RangeParameter<Long>[] params, boolean primarySortField, String parameterName, Field<Long> field) {
Bounds can now be `NumberRangeParameter` bounds (because of the serial number bound), instead of just `EntityIdRangeParameter`, so I updated this from a list to an array to accept the interface of both `RangeParameter`.

2024-09-20 21:20 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/TokenAirdropRequest.java
> +    }
This class already contained the specifics concerning the ordering of the jooq Fields in `AirdropRequestType`, so it seemed to fit to place the specifics for the ordering of the bounds here. But we could place this in one of the other layers as well.

2024-09-30 19:45 UTC, steven-sheehy requested changes

2024-09-30 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    public Bound(RangeParameter<Long>[] params, boolean primarySortField, String parameterName, Field<Long> field) {
How does list vs array help? Can't you do `List<RangeParameter<Long>>`?

2024-09-30 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +            primary.setUpper(null);
Can't we just do this in the constructor of the Bound? Or possibly in the getters for lower/upper? This would keep the class more immutable. 

We also have to take into consideration 2nd of 3 params can probably also have this behavior.

2024-09-30 19:45 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +                    bound.setUpper(secondaryLower);
Can we move this logic into bound?

2024-09-30 19:56 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    public Bound(RangeParameter<Long>[] params, boolean primarySortField, String parameterName, Field<Long> field) {
I tried a few different ways but couldn't get it to compile as such. If the signature of Bounds is changed to `List<RangedParameter>` or `List<RangedParameter<Long>>` or `List<RangedParameter<?>>`  then
passing a `List<EntityIdRangeParameter>` errors with: 

```
Required type: List<RangeParameter>
Provided: List<EntityIdRangeParameter>>```

2024-09-30 20:46 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeParameter.java
> +        return operator() == RangeOperator.LT || operator() == RangeOperator.GT;
Thanks I have updated it.

2024-09-30 20:46 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdRangeParameter.java
> +    private static Long getEntityId(String entityId) {
Good catch, I have reverted that part.

2024-09-30 20:48 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +                .tokenIds(new Bound(tokenIds, false, TOKEN_ID, TOKEN_AIRDROP.TOKEN_ID))
If it is set to true, I found that certain next links became invalid, such as: 
```
?limit=1&receiver.id=lt:0.0.4&receiver.id=gte:0.0.3&token.id=lte:0.0.5&token.id=gt:0.0.5
```

That link is from the `allParameters()` test in `TokenAirdropsControllerTest`

2024-09-30 20:48 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/NftAllowanceRequest.java
> +        var secondaryBound = tokenIds == null ? Bound.EMPTY : tokenIds;
Sounds good, I have updated it.

2024-09-30 20:49 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/NftAllowanceRequest.java
> +        var primaryBound = ownerOrSpenderIds == null ? secondaryBound : ownerOrSpenderIds;
Thanks. I have updated this section, the variable matching the conditional is now the first item.

2024-09-30 20:49 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/NftAllowanceRequest.java
> +        return List.of(primaryBound, secondaryBound);
Sounds good, I have reworked this for both request types.

2024-09-30 20:49 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/TokenAirdropRequest.java
> +        return List.of(primaryBound, secondaryBound, tertiaryBound);
Got it, this has been reworked.

2024-09-30 22:14 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeParameter.java
> +        return operator() == RangeOperator.LT || operator() == RangeOperator.GT;
You updated the name, but didn't invert the logic. So now the logic is wrong.

2024-09-30 23:04 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeOperator.java
> +        return operator == RangeOperator.LT || operator == RangeOperator.GT;
It doesn't need to be static and the logic is inverted for being inclusive.

```suggestion
    public boolean isInclusive() {
        return this != RangeOperator.LT && operator != RangeOperator.GT;
```

2024-09-30 23:36 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeOperator.java
> +        return operator == RangeOperator.LT || operator == RangeOperator.GT;
Thanks I have fixed this.

2024-09-30 23:37 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeParameter.java
> +        return operator() == RangeOperator.LT || operator() == RangeOperator.GT;
I see! Thanks I have fixed it.

2024-10-01 00:38 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/NftAllowanceRequest.java
> +        return List.of(primaryBound, secondaryBound);
Alternatively, it'd be simpler to rationalize if for 3 column pagination we always had 3 items in the list. And for first item it would always be ownerOrSpender, second always tokenId and third always serial. Then the framework would be smart enough to handle empty items and we wouldn't need conditional logic in this getBounds()

2024-10-01 01:51 UTC, xin-hedera requested changes

2024-10-01 01:51 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +    default Condition getBoundCondition(List<Bound> bounds) {
I don't think the changes here can solve the N pagination column problem.

It's difficult to explain the issues thoroughly in symbolic representation or pseudo code. However, it should be quite straightforward by looking at a complicated request and the generated SQL.

Given the following request,

```bash
$ curl 'localhost:8084/api/v1/accounts/0.0.1500/airdrops/outstanding?receiver.id=gte:0.0.2000&receiver.id=lte:0.0.3000&token.id=gte:0.0.4000&token.id=lte:0.0.5000&serialnumber=gte:5&serialnumber=lte:100&limit=50'
```

we get the generated SQL and params

```
select "token_airdrop"."amount", "token_airdrop"."receiver_account_id", "token_airdrop"."sender_account_id", "token_airdrop"."serial_number", "token_airdrop"."state", "token_airdrop"."timestamp_range", "token_airdrop"."token_id"
from "token_airdrop"
where ("token_airdrop"."sender_account_id" = $1 and
  (
   ("token_airdrop"."receiver_account_id" = $2 and "token_airdrop"."token_id" >= $3 and "token_airdrop"."serial_number" >= $4) or
   ("token_airdrop"."receiver_account_id" >= $5 and "token_airdrop"."receiver_account_id" <= $6) or 
   ("token_airdrop"."receiver_account_id" = $7 and "token_airdrop"."token_id" <= $8 and "token_airdrop"."serial_number" <= $9)
  ) and
  "token_airdrop"."state" = cast($10 as "airdrop_state"))
order by "token_airdrop"."receiver_account_id" asc, "token_airdrop"."token_id" asc, "token_airdrop"."serial_number" asc
fetch next $11 rows only

parameters: $1 = '1500', $2 = '2000', $3 = '4000', $4 = '5', $5 = '2001', $6 = '2999', $7 = '3000', $8 = '5000', $9 = '100', $10 = 'PENDING', $11 = '50'
```

There are problems in these two conditions

- `("token_airdrop"."receiver_account_id" = $2 and "token_airdrop"."token_id" >= $3 and "token_airdrop"."serial_number" >= $4)`
-  `("token_airdrop"."receiver_account_id" = $7 and "token_airdrop"."token_id" <= $8 and "token_airdrop"."serial_number" <= $9)`

A concrete example of a token airdrop which should get included (let's assume there is no `limit`), however due to the bug in the first of the two conditions above, will never show up is as follows:

`(sender=0.0.1500, receiver=0.0.2000, token=0.0.4001,serialnumber=1)`

I agree the two-column pagination support itself is quite complicated and corner case optimizations make it even harder to understand and maintain, so expanding it to N-column is a much bigger challenge.

We should be able to generalize the problem and solve it recursively with the algorithm in the following psuedo code


```
function getConditions(Bound[] bounds) {
  primaryBound = bounds[0]
  if bounds.length == 1
    return condition created from primaryBound

  remaining = bounds[1...N]
  lowerCondition = ((primary column = inclusive lower bound value) or no condition if primaryBound doesn't have lower bound) and
    getConditions(lower bounds from remaining)
  middleCondition = getMiddleCondition(primaryBound)
  upperCondition = ((primary column = inclusive upper bound value) or no condition if primaryBound doesn't have upper bound) and
    getConditions(upper bounds from remaining)

  return lowerCondition or middleCondition or upperCondition
}

function getMiddleCondition(Bound bound) {
	lowerCondition = column >= lower value + 1 or no condition if there's no lower bound
	upperCondition = column <= upper value - 1 or no condition if there's no upper bound
	return lowerCondition and upperCondition
}
```

2024-10-03 19:00 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +            primary.setUpper(null);
I have updated this to be a new adjustment method in Bound.

2024-10-03 19:00 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +                    bound.setUpper(secondaryLower);
Got it, this has been moved to Bound

2024-10-03 19:01 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +        return processRequest(id, entityIdsBound, limit, order, serialNumbers, tokenIds, PENDING, SENDER_ID);
Thanks I have updated both of those.

2024-10-03 19:02 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +    default Condition getBoundCondition(List<Bound> bounds) {
Got it, I have reworked this section to implement a recursive solution. I have added this example as a test case in `TokenAirdropsControllerTest.allParametersNft`

2024-10-03 19:03 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +
Todo, I still need to add Javadocs as to how these conditions are generated with bounds and sql examples.

2024-10-03 20:27 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +        return processRequest(id, entityIdsBound, limit, order, serialNumbers, tokenIds, PENDING, SENDER_ID);
Don't think it's addressed per my change request.

What I meant is, for example, for pending request,  we shouldn't pass both type `PENDING` and `SENDER_ID`, since if it's PENDING, it has to be `SENDER_ID`, and the enum `AirdropRequestType` already has the info encapsulated.

For `entityIdsBound`, we should remove code duplication to moving it into function `processRequest`, we can do so because of the same reason, that for `PENDING`, it's always `SENDER_ACCOUNT_ID` as the primary sort column, and for `OUTSTANDING`, it's always `RECEIVER_ACCOUNT_ID` as the primary sort column.

2024-10-03 20:29 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
> +        return processRequest(id, entityIdsBound, limit, order, serialNumbers, tokenIds, PENDING, SENDER_ID);
umm, my bad, was looking at the stale code...

2024-10-07 22:21 UTC, xin-hedera requested changes

2024-10-07 22:21 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +    default Condition getCondition(RangeParameter<Long> param, Field<Long> field) {
there are many new methods which should be private instead of public with default implementation.

2024-10-07 22:21 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +        if (primary.isEmpty() && secondaryBounds.isEmpty()) {
this is dead code, since when the flow reaches here, `secondaryBounds.isEmpty()` is always `false`. There's probably no coverage either however needs to recheck after the condition is fixed

2024-10-07 22:21 UTC, xin-hedera commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +        if (bounds.isEmpty()) {
no test coverage here.

2024-10-08 14:29 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +    public Bound(Bound bound, boolean isUpper) {
Thanks I have changed this to those methods.

2024-10-08 14:31 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        }
It looks like it cannot be done to secondary bounds before the primary bound is analyzed, there are Nft repository tests that fail if this is done in the constructor.  

I have updated it and removed the Setters.

2024-10-08 14:31 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +        if (bounds.isEmpty()) {
Thanks I have added a test case for this.

2024-10-08 14:32 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +        if (primary.isEmpty() && secondaryBounds.isEmpty()) {
Good catch, I have removed this.

2024-10-08 14:32 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
> +    default Condition getCondition(RangeParameter<Long> param, Field<Long> field) {
Thanks I have updated them to private.

2024-10-08 14:32 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        if (params == null || params.length == 0) {
Got it, I have updated this.

2024-10-08 14:32 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        if (!this.isEmpty() && this.hasEqualBounds()) {
Thanks I have fixed this.

2024-10-08 15:39 UTC, steven-sheehy commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return createBound(bound.getUpper());
This was not what I suggested. It doesn't make sense to pass in the same bound that you're invoking it on.

```suggestion
    public Bound toLower() {
        return createBound(getLower());
    }

    // Returns a new bound with only an upper rangeParameter
    public Bound toUpper() {
        return createBound(getUpper());
```

2024-10-08 15:55 UTC, edwin-greene commented on hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
> +        return createBound(bound.getUpper());
Doh, thanks, much better. I have fixed it now.

2024-10-08 15:57 UTC, steven-sheehy approved these changes

2024-10-08 16:13 UTC, xin-hedera approved these changes

2024-10-08 16:54 UTC, merged