Implement `ContractStorageReadableKVState`
hashgraph/hedera-mirror-node pull request #9450
Opened 2024-09-25 08:40 UTC by bilyana-gospodinova

**Description**:
As part of the implementation for the reusable services we need to implement `ContractStorageReadableKVState`. It reads reads contract storage related data and converts slotValue to SlotValue PBJ type.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9254

**Checklist**
- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-09-25 10:13 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
I am not sure if we need to fetch the entity from the `Entity` table first to check if it exists. I would appreciate any opinions on this.

2024-09-25 14:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
If we have a record in `contract_state`, we should have corresponding contract saved in entity, otherwise we are having an incorrect state. I think we can directly read the `contract_state` table, so that we don't harm the performance with an additional query.

2024-09-25 14:30 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-09-26 12:06 UTC, kselveliev approved these changes

2024-09-26 14:51 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
Ok, thank you.

2024-09-27 15:24 UTC, edwin-greene submitted a review, later dismissed
Looks good to me

2024-09-27 18:23 UTC, steven-sheehy requested changes

2024-09-27 18:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +public class ContractStorageReadableKVState extends ReadableKVStateBase<SlotKey, SlotValue> {
This should be a bean via `@Named` since it's a singleton, right?

2024-09-27 18:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
For partial mirror nodes with start date not at genesis (which is quite common), it's not necessarily true that we should have a row in entity table. However, we should accommodate these partial mirror nodes and not add such a check. So agree with Ivan but just want to clarify.

2024-09-27 18:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
I imagine we'll have lots of places that convert pbj entities to `EntityId`. So we should add a util method to `EntityIdUtils` for this.

2024-09-27 18:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +                        entityId.getId(), slotKey.key().toByteArray()))
nit: Can pull up some method calls to clean it up a bit.

```suggestion
        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum()).getId();
        final var keyBytes = slotKey.key().toByteArray();

        return timestamp
                .map(t -> contractStateRepository.findStorageByBlockTimestamp(entityId, keyBytes, t))
                .orElse(contractStateRepository.findStorage(entityId, keyBytes))
```

2024-09-27 19:19 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        return 0;
Add tests to increase coverage.

2024-10-01 14:09 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        return 0;
Comment addressed

2024-10-01 14:11 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +                        entityId.getId(), slotKey.key().toByteArray()))
Comment addressed

2024-10-01 14:11 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +        final var entityId = EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
Comment addressed

2024-10-01 14:11 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +public class ContractStorageReadableKVState extends ReadableKVStateBase<SlotKey, SlotValue> {
Comment addressed

2024-10-01 14:11 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +import org.jetbrains.annotations.NotNull;
Comment addressed

2024-10-03 07:18 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
> +    private static final String KEY = "STORAGE";
The String is removed.

2024-10-03 08:19 UTC, kselveliev approved these changes

2024-10-03 14:01 UTC, steven-sheehy approved these changes

2024-10-03 14:24 UTC, merged