Implement `ContractBytecodeReadableKVState`
hashgraph/hedera-mirror-node pull request #9452
Opened 2024-09-25 13:10 UTC by bilyana-gospodinova

**Description**:
As part of the implementation for the reusable services we need to implement `ContractBytecodeReadableKVState`. It reads the contract's runtime bytecode and converts it to `Bytecode` PBJ type.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9255

**Checklist**
- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-09-25 14:32 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        final var runtimeCode =
We can skip `entity` check and directly read from `contract` table by `EntityId.of(contractID.getShard(), contractID.getRealm(), contractID.getNum()).getId()`

2024-09-25 14:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        final var runtimeCode =
The current implementation in `MirrorEntityAccess` calls `fetchEntityId` first. There we read the address from the `Entity` table and try to find it as an account. If we fail, we try to read it as a token. If it is not found again, we return `null` directly without any queries to the contract-related repositories. This is valid for both the runtime bytecode and the storage slot. I guess this was added because in there we don't have the id directly but only the address as a parameter and I wanted to double check.

2024-09-26 14:50 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        final var runtimeCode =
Comment addressed. Added also a case when we have an evm address set.

2024-09-27 12:38 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        final var runtimeCode = contractRepository.findRuntimeBytecode(entityId.getId());
One suggestion for this code section to be cleaner.
```
return contractRepository.findRuntimeBytecode(entityId.getId())
                .map(Bytes::wrap)
                .map(Bytecode::new)
                .orElse(null);
```

2024-09-27 13:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        final var runtimeCode = contractRepository.findRuntimeBytecode(entityId.getId());
You are right. It is better this way. Thanks, comment addressed.

2024-09-27 13:17 UTC, kselveliev approved these changes

2024-09-27 19:23 UTC, steven-sheehy requested changes

2024-09-27 19:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static EntityId convertContractIDToEntityId(final ContractID contractID) {
Use a simpler name so we can have many overloaded variants for each pbj type.

```suggestion
    public static EntityId toEntityId(final ContractID contractID) {
```

2024-09-27 19:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static EntityId convertContractIDToEntityId(final ContractID contractID) {
These need a test.

2024-09-27 19:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        return 0;
Add tests to increase coverage.

2024-09-27 19:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static EntityId convertContractIDToEntityId(final ContractID contractID) {
Should handle null and empty ContractID input

2024-09-27 19:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static Address convertPbjBytesToBesuAddress(final Bytes bytes) {
```suggestion
    public static Address toBesuAddress(final Bytes bytes) {
```

2024-09-27 19:23 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        }
If contractID can't be null, in what situations would this ever be null?

2024-10-03 09:08 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        }
I added it in order to keep the existing check in `MirrorEntityAccess#fetchCodeIfPresent`. We probably don't need it here. I am removing the check.

2024-10-03 09:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +public class ContractBytecodeReadableKVState extends ReadableKVStateBase<ContractID, Bytecode> {
Done

2024-10-03 09:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +public class Utils {
Moved

2024-10-03 09:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static EntityId convertContractIDToEntityId(final ContractID contractID) {
Renamed

2024-10-03 09:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static EntityId convertContractIDToEntityId(final ContractID contractID) {
Added tests.

2024-10-03 09:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        return 0;
Added tests

2024-10-03 09:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +    public static EntityId convertContractIDToEntityId(final ContractID contractID) {
Done

2024-10-03 10:27 UTC, kselveliev approved these changes

2024-10-03 10:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
> +        final var address = Address.fromHexString("0x0000000000000000000000000000000000000001");
`evmAddress` usually will be not a long zero string, but have letters and numbers like `388C818CA8B9251b393131C08a736A67ccB19297`. We can use more realistic evmAddress value.

2024-10-03 11:37 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static EntityId toEntityId(final com.hedera.hapi.node.base.ContractID contractID) {
After we merge this PR we should apply the same logic for AccountID. It seems the case for `evmAddress` is not covered there.

2024-10-03 14:51 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
> +        final var address = Address.fromHexString("0x0000000000000000000000000000000000000001");
I made the needed changes. It seems that we need to read the entity from the repository after all in order to get the entity id from an evm address.

2024-10-03 14:57 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +        }
We don't have to strongly comply with the legacy mono code, as now we have different business rules and checks.

2024-10-03 15:08 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return commonEntityAccessor
We can have a new method that returns only the EntityId instead of the whole Entity DTO, so that we reduce the throughput in DB and have a lighter query.

2024-10-03 15:24 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return commonEntityAccessor
Actually `entityIdNumFromEvmAddress` will return the EntityId of the evmAddress. It was already converted when we convert a `ContractID` to `Address` with `toAddress`. Even if it have a byte evm address it will be converted to a Long numeric value.

2024-10-03 16:00 UTC, steven-sheehy requested changes

2024-10-03 16:00 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return EntityId.of(entityIdNumFromEvmAddress(evmAddress));
Can simplify util execution chain by just keeping it at bytes.

```suggestion
                return DomainUtils.fromEvmAddress(evmAddress);
```

2024-10-04 07:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +            if (isMirror(evmAddress)) {
The conversion was not just for the `isMirror` check. `entityIdNumFromEvmAddress(address)` requires an `Address`.

2024-10-04 08:58 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return commonEntityAccessor
Yes, but if we have the address "b794f5ea0ba39494ce839613fffba74279579268" `entityIdNumFromEvmAddress` tries to convert it to 3285643.84543857934.203384024080 for example and an exception is thrown that the entity is not valid.

2024-10-04 09:28 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
> +            return false;
Added tests.

2024-10-04 09:29 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return EntityId.of(entityIdNumFromEvmAddress(evmAddress));
Done, thanks.

2024-10-04 09:30 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +            if (isMirror(evmAddress)) {
Done after the suggestion in https://github.com/hashgraph/hedera-mirror-node/pull/9452#discussion_r1786482220

2024-10-04 11:58 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return commonEntityAccessor
Added a new DB query.

2024-10-04 13:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +                .isNotNull();
We can assert that the entity returned by the query has the exact same EntityId as the persisted one

2024-10-04 14:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +            return EntityId.of(contractID.shardNum(), contractID.realmNum(), contractID.contractNum());
Done

2024-10-04 14:21 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +                .isNotNull();
Done

2024-10-04 14:31 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-10-04 14:32 UTC, kselveliev submitted a review, later dismissed

2024-10-04 15:13 UTC, steven-sheehy requested changes

2024-10-04 15:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                        .getEntityIdByEvmAddress(contractID.evmAddress().toByteArray())
Double conversion

```suggestion
                        .getEntityIdByEvmAddress(evmAddress)
```

2024-10-04 15:13 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return commonEntityAccessor
The old query was cached while the new one is not. So the use of the new query might actually result in reduced throughput if contract IDs are repeated in multiple requests (as they are in k6 tests). We can add the cache to the new query as well, but then we have two ways to cache the same evm address so we might be 50% less likely to actually hit a warm cache. Also, PostgreSQL reads rows in 8KiB pages so reducing selected columns in single row results doesn't necessarily help the database load. I think we should revert this change.

2024-10-07 07:13 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                return commonEntityAccessor
Thank you for the detailed explanation. I reverted the changes.

2024-10-07 16:51 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                        .getEntityIdByEvmAddress(contractID.evmAddress().toByteArray())
Still a problem

2024-10-08 06:56 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
> +                        .getEntityIdByEvmAddress(contractID.evmAddress().toByteArray())
Fixed. Thank you!

2024-10-08 11:03 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-10-08 14:01 UTC, kselveliev approved these changes

2024-10-08 14:46 UTC, steven-sheehy approved these changes

2024-10-08 14:47 UTC, merged