Add NFTReadableKVState
hashgraph/hedera-mirror-node pull request #9484
Opened 2024-10-01 08:17 UTC by kselveliev

**Description**:

* Add repository logic for reading nfts from DB - similar to `UniqueTokenDatabaseAccessor`
* Add a new converter between entity and nft DTO types to PBJ, so that the returned object is compliant with the hedera.app state
* Add NftReadableKVStateTest - test logic from `NftReadableKVState`

**Related issue(s)**:

Fixes #9418

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-01 21:54 UTC, steven-sheehy requested changes

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +    private static final String KEY = "NFTS";
Doesn't need to be static or declared outside constructor since it's never used again.

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +        final Optional<Long> optionalTimestamp = ContractCallContext.get().getTimestamp();
```suggestion
        final var timestamp = ContractCallContext.get().getTimestamp();
```

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +                .orElseGet(() -> nftRepository.findActiveById(key.tokenId().tokenNum(), key.serialNumber()))
We should never pass just the un-encoded num to the database. All database IDs are the encoded entity ID.
```suggestion
                .map(t -> nftRepository.findActiveByIdAndTimestamp(entity.getId(), key.serialNumber(), t))
                .orElseGet(() -> nftRepository.findActiveById(entity.getId(), key.serialNumber()))
```

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +        }
Why do we need to get the entity first when we don't use it as input to anything else? Is it just for existence check? For performance reasons and to support partial mirror nodes we don't generally do existence checks. Probably we should remove this logic.

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +                        new TokenID(tokenID.shardNum(), tokenID.realmNum(), tokenID.tokenNum()), nft.getSerialNumber()),
Isn't the TokenID parameter the same as this one we're creating?
```suggestion
                        tokenID, nft.getSerialNumber()),
```

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +        return new Nft(
Use the builder form to create so it's readable. Chain setters alphabetically.

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +                EntityIdUtils.toAccountId(nft.getSpender().getId()),
Use the EntityId form.
```suggestion
                EntityIdUtils.toAccountId(nft.getAccountId()),
                EntityIdUtils.toAccountId(nft.getSpender()),
```

2024-10-01 21:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +    private Timestamp convertToTimestamp(final long timestamp) {
Should probably be a util somewhere

2024-10-02 11:00 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
> +                EntityId.of(tokenID.shardNum(), tokenID.realmNum(), tokenID.tokenNum()), timestamp);
Use a suitable utility method from `EntityIdUtils`

2024-10-02 11:01 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/NftReadableKVState.java
> +        }
Agreed, we should directly read from `nft` table

2024-10-02 15:28 UTC, steven-sheehy approved these changes
LGTM

2024-10-03 08:37 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-10-03 09:35 UTC, bilyana-gospodinova approved these changes
LGTM

2024-10-03 15:28 UTC, merged