feat: Add token readable kv state
hashgraph/hedera-mirror-node pull request #9502
Opened 2024-10-04 12:47 UTC by kselveliev

**Description**:

Adding TokenReadableKVState for returning fungible token models into PBJ types, reading from DB.

**Related issue(s)**:

Fixes #9252

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-04 12:48 UTC, kselveliev commented
Need to add test for the new Token record

2024-10-08 11:15 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +        if (autoRenewAccountIdSupplier != null && autoRenewAccountIdSupplier.get() != null) {
What if `autoRenewAccountIdSupplier==null` but `DEFAULT.autoRenewAccountIdSupplier` is not? We won't get inside this if clause.

2024-10-08 11:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +        if (treasuryAccountIdSupplier != null) {
What about treasuryAccountIdSupplier == null, but thatObj.treasuryAccountIdSupplier != null? We will be missing this case

2024-10-08 11:19 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +            if (thisAccountId == null && thatAccountId == null) {
We can check if `thisAccount == null && thatAccountId != null` and return false and then in the `else` statement, directly compare  `!thisAccountId.equals(thatAccountId)`, thus having only 2 checks.

2024-10-08 11:21 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
> +                EntityId.of(tokenID.shardNum(), tokenID.realmNum(), tokenID.tokenNum()), timestamp);
Use EntityIdUtils for EntityId conversion

2024-10-08 11:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .tokenId(new TokenID(entity.getShard(), entity.getRealm(), entity.getNum()))
Sort all builder methods alphabetically.

2024-10-08 11:22 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .tokenId(new TokenID(entity.getShard(), entity.getRealm(), entity.getNum()))
Use EntityIdUtils for TokenID creation

2024-10-08 11:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +        return tokenRepository.findFungibleTotalSupplyByTokenIdAndTimestamp(tokenId, timestamp);
This statement should be wrapped in a Suppliers.memoize()

2024-10-08 11:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +        final var customFees = timestamp
This assignment should be also wrapped in the Suppliers.memoize()

2024-10-08 11:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +            var constructed = new CustomFee(
Use Builder for construction

2024-10-08 11:27 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +            final var fixedFee = new FixedFee(
Use builder for construction and EntityIdUtils for TokenID generation

2024-10-08 11:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                        new TokenID(
Use EntityIdUtils for TokenID generation

2024-10-08 11:46 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +            if (thisAccountId == null && thatAccountId == null) {
If we apply the following we are going to get 
**"thisAccountId" is null error** 
in the case where both suppliers return null accountIDs. Or I might be missing something but my test with 2 null values starts to fail. -> `testEqualsWithNullTreasuryAccountIdBoth`

2024-10-08 12:02 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .tokenId(new TokenID(entity.getShard(), entity.getRealm(), entity.getNum()))
Comments addressed

2024-10-08 12:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +        if (treasuryAccountIdSupplier != null) {
line 408 above this does -> 
```
 if (treasuryAccountIdSupplier == null && thatObj.treasuryAccountIdSupplier != null) {
            return false;
 }
```

this should be handling it, right?

2024-10-08 12:24 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                        new TokenID(
Comment addressed

2024-10-08 12:24 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +            final var fixedFee = new FixedFee(
Comment addressed

2024-10-08 12:27 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +        return tokenRepository.findFungibleTotalSupplyByTokenIdAndTimestamp(tokenId, timestamp);
Since this method is only called from `getTotalSupply` which is already wrapped in suppliers memoize we might not need it right?

2024-10-08 13:04 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +        return tokenRepository.findFungibleTotalSupplyByTokenIdAndTimestamp(tokenId, timestamp);
You're right

2024-10-08 13:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +            if (thisAccountId == null && thatAccountId == null) {
This was my initial implementation but we start getting into null pointers 
since the supplier might not be null but the value it returns can be null
**treasuryAccountIdSupplier.get().equals**

2024-10-09 08:39 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +        if (treasuryAccountIdSupplier == null && thatObj.treasuryAccountIdSupplier != null) {
It seems that we have a lot of similar lines - check if one of the suppliers is null and the other is not, then the reverse check, then check if their values differ. We can create a helper utility method that does that (comparing suppliers). This way we will make it easier to read the the `equals()` code and we will prevent accidentally forgetting to add one of the checks.

2024-10-09 08:45 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +    private static final String KEY = "TOKENS";
In the other PRs we don't define such constants. Reference: https://github.com/hashgraph/hedera-mirror-node/pull/9450#discussion_r1783574148

2024-10-09 08:53 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/TokenReadableKVStateTest.java
> +    private AccountID getAccountId(final Long shard, final Long realm, final Long num) {
This can be moved to `EntityIdUtils`.

2024-10-09 10:09 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +    private static final String KEY = "TOKENS";
Yeah i totally forgot, comment addressed.

2024-10-09 10:10 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/TokenReadableKVStateTest.java
> +    private AccountID getAccountId(final Long shard, final Long realm, final Long num) {
Comment addressed

2024-10-09 10:33 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
> +        if (treasuryAccountIdSupplier == null && thatObj.treasuryAccountIdSupplier != null) {
Pretty good idea, I added a new method in Suppliers util class to compare suppliers.

2024-10-09 11:46 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static com.hedera.hapi.node.base.AccountID getAccountId(final Long shard, final Long realm, final Long num) {
The other methods in this class are named `to<class_type>ID`. It will be more readable if we stick to this convention.

2024-10-09 12:03 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static com.hedera.hapi.node.base.AccountID getAccountId(final Long shard, final Long realm, final Long num) {
Comment addressed

2024-10-09 12:07 UTC, bilyana-gospodinova submitted a review, later dismissed
LGTM

2024-10-10 00:43 UTC, steven-sheehy requested changes

2024-10-10 10:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +            @Nonnull EntityRepository entityRepository) {
Comment addressed

2024-10-10 10:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static com.hedera.hapi.node.base.AccountID toAccountId(final Long shard, final Long realm, final Long num) {
Comment addressed

2024-10-10 10:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
> +        return toAccountId(entity);
Comment addressed

2024-10-10 11:00 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .pauseKey(Utils.parseKey(token.getPauseKey()))
Comment addressed

2024-10-10 11:09 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .map(EntityIdUtils::toAccountId)
The main reason is that we are currently just mirroring the TokenDatabaseAccessor logic which is also querying for the entities for autorenewAccount and treasury.

2024-10-10 11:36 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .paused(token.getPauseStatus().equals(TokenPauseStatusEnum.PAUSED))
`paused` should be before `pauseKey`

2024-10-10 11:51 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .paused(token.getPauseStatus().equals(TokenPauseStatusEnum.PAUSED))
Comment addressed

2024-10-10 11:51 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .map(EntityIdUtils::toAccountId)
We can see if we are going to need the whole entity models for other ReadableKVStates. If not, we can really simplify the queries as you suggested.

2024-10-10 11:55 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +        return tokenRepository.findFungibleTotalSupplyByTokenIdAndTimestamp(tokenId, timestamp);
This was copied from initial PR. Maybe the initial idea was that NFT kv state will handle it but there is no such logic there. I've equalized the logic as in the tokenDatabaseAccessor.

2024-10-10 15:36 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +                .map(EntityIdUtils::toAccountId)
We should create a ticket to capture these various future optimizations. There have been similar [comments](https://github.com/hashgraph/hedera-mirror-node/pull/9527#discussion_r1795085661) in other PRs about things we'd like to check later. Let's not forget these items.

2024-10-10 15:46 UTC, steven-sheehy requested changes

2024-10-10 15:46 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +public class TokenReadableKVState extends ReadableKVStateBase<TokenID, Token> {
Needs to have `@Named`

2024-10-10 16:41 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
> +public class TokenReadableKVState extends ReadableKVStateBase<TokenID, Token> {
Comment addressed

2024-10-10 16:44 UTC, steven-sheehy approved these changes
LGTM

2024-10-11 12:15 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-10-11 15:17 UTC, kselveliev commented
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/pull/9572

2024-10-11 15:17 UTC, closed without merging