Add HIP-991 design
hashgraph/hedera-mirror-node pull request #9503
Opened 2024-10-04 14:55 UTC by xin-hedera

**Description**:

This PR adds design doc for HIP-991

**Related issue(s)**:

Fixes #9465 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-04 14:58 UTC, xin-hedera commented on docs/design/topic-custom-fees.md
> +  - `ConsensusApproveAllowance`: consensus crypto / token fee schedule allowances
I don't see the value of adding a new transaction type just for the topic related allowances. The HIP itself also shows traces changing from adding the consensus crypto / token allowances to `CryptoApproveAllowance`, to a new `ConsensusApproveAllowance` transaction type, because the protobuf field numbers are somehow 4 and 5...

If the final protobuf changes, I'll update our design doc accorodingly.

2024-10-05 17:12 UTC, steven-sheehy requested changes

2024-10-07 19:15 UTC, edwin-greene approved these changes
Looks good to me other than existing suggestions.

2024-10-08 13:37 UTC, kselveliev commented on docs/design/topic-custom-fees.md
> +- Add an abstract `AbstractTopic` class. The class implements `Histoy` interface, and has the following fields
fix typo _History_

2024-10-08 14:50 UTC, steven-sheehy approved these changes
LGTM

2024-10-08 14:53 UTC, kselveliev approved these changes

2024-10-09 14:21 UTC, merged