Implement `AliasesReadableKVState `
hashgraph/hedera-mirror-node pull request #9527
Opened 2024-10-07 07:48 UTC by bilyana-gospodinova

**Description**:
As part of the implementation for the reusable services we need to implement `AliasesReadableKVState`. It reads the entity alias and converts it to `AccountID` PBJ type. In order to achieve this we need a new DB query that executes a select statement by alias. The query is an exact copy of the other query by evm address. Only the column is changed from evm_address -> alias.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9256

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-07 12:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                        .alias(Bytes.wrap(value.getAlias()))
We can directly set the `alias` argument we search by. Even if we want to use the found entity information - we should first check whether the `evmAddress` is populated and only if not - then read the `alias` (which may be a public key)

2024-10-07 12:23 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +        // Both entity and entity history will be queried in union but entity history record is the latest valid
You can use the `verify()` check to validate that the correct repository method was invoked

2024-10-07 12:25 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/AliasesReadableKVStateTest.java
> +            new AccountID(1L, 0L, new OneOf<>(AccountOneOfType.ALIAS, ALIAS_BYTES.value()));
You can use a suitable `EntityIdUtils` utility method

2024-10-08 07:02 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +        return entity.map(value -> AccountID.newBuilder()
Perhaps you mean "e" as in `Entity`?

2024-10-09 12:37 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
> +        // Both entity and entity history will be queried in union but entity history record is the latest valid
I'm not entirely sure if this test can be a real scenario since entity history record timestamp will be greater than the entity. While in theory entity should be the latest.

2024-10-09 12:38 UTC, kselveliev submitted a review, later dismissed

2024-10-09 13:50 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/AliasesReadableKVStateTest.java
> +            new AccountID(1L, 0L, new OneOf<>(AccountOneOfType.ALIAS, ALIAS_BYTES.value()));
Done

2024-10-09 13:50 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                        .alias(Bytes.wrap(value.getAlias()))
Done

2024-10-09 13:51 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +        return entity.map(value -> AccountID.newBuilder()
Renamed

2024-10-09 13:51 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +    Optional<Entity> findActiveByAliasAndTimestamp(byte[] alias, long blockTimestamp);
I combined the search in 1 query.

2024-10-09 13:56 UTC, kselveliev approved these changes

2024-10-09 15:48 UTC, steven-sheehy requested changes

2024-10-09 15:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                        .alias(e.getEvmAddress() != null ? Bytes.wrap(e.getEvmAddress()) : alias.value())
It doesn't make much sense to lookup an alias just to return an evm address or alias. Shouldn't this always return the `shard.realm.num` form?

2024-10-09 15:48 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +    Optional<Entity> findByEvmAddressOrAlias(byte[] alias);
At least right now we only need the entity.id field returned so we can optimize this and the other query.
```suggestion
    Optional<Long> findByEvmAddressOrAlias(byte[] alias);
```

2024-10-10 09:48 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                alias.value().toByteArray(), timestamp);
I believe AccountReadableKVState might be invoked in various cases where account can be search in various formats. That will be validated once we integrate everything and perform some tests. We can simplify the logic if needed, in another PR.

2024-10-10 09:49 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                        .alias(e.getEvmAddress() != null ? Bytes.wrap(e.getEvmAddress()) : alias.value())
Yes, in AliasesReadableKVState, the AccountID should be always in Hedera format with shard.realm.num

2024-10-10 09:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +    Optional<Entity> findByEvmAddressOrAlias(byte[] alias);
That's correct, we can simplify the query.

2024-10-10 11:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
> +    Optional<Entity> findByEvmAddressOrAlias(byte[] alias);
This method is now used in `CommonEntityAccessor#get` as well and we need the full entity in there. We can have 2 separate queries with different return types. However, I am not sure if we will gain any performance this way.

2024-10-10 11:25 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                        .alias(e.getEvmAddress() != null ? Bytes.wrap(e.getEvmAddress()) : alias.value())
Changed the return form to `shard.realm.num`.

2024-10-10 16:39 UTC, steven-sheehy requested changes

2024-10-10 16:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +public class AliasesReadableKVState extends ReadableKVStateBase<ProtoBytes, AccountID> {
Needs `@Named`

2024-10-10 16:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
> +    public Optional<Entity> getEntityByEvmAddressOrAliasAndTimestamp(byte[] alias, final Optional<Long> timestamp) {
Probably better to have a consistent naming with overloaded params. Another PR adds a `get(TokenID...)`.

```suggestion
    public Optional<Entity> get(byte[] alias, final Optional<Long> timestamp) {
```

2024-10-10 16:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
>      Optional<Entity> findActiveByEvmAddressAndTimestamp(byte[] evmAddress, long blockTimestamp);
Is there any reason why we can't change `EntityDatabaseAccessor` to also use the new method and delete the old methods? Or can we at least add a follow up item to the cleanup task to sweep through and remove and unused repository methods.

2024-10-11 01:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                alias.value().toByteArray(), timestamp);
Let's create a ticket to check these various optimizations later.

2024-10-11 07:53 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
>      Optional<Entity> findActiveByEvmAddressAndTimestamp(byte[] evmAddress, long blockTimestamp);
I did not remove the old methods in `EntityDatabaseAccessor` as I did not want to risk adding a regression at this point. At the end in the cleanup we will remove all database accessors, so we will remove any unused code. I added a comment in the cleanup task for the repository methods - https://github.com/hashgraph/hedera-mirror-node/issues/9263#issuecomment-2406758807

2024-10-11 08:52 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +public class AliasesReadableKVState extends ReadableKVStateBase<ProtoBytes, AccountID> {
Added

2024-10-11 08:53 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
> +    public Optional<Entity> getEntityByEvmAddressOrAliasAndTimestamp(byte[] alias, final Optional<Long> timestamp) {
I renamed the methods, thanks.

2024-10-11 08:56 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +                alias.value().toByteArray(), timestamp);
There is a ticket for optimizations - https://github.com/hashgraph/hedera-mirror-node/issues/9264. I will add a comment there.

2024-10-11 11:19 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +        return entity.map(e -> AccountID.newBuilder()
I believe we can use `EntityIdUtils` for constructing the `AccountID`

2024-10-11 12:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
> +        return entity.map(e -> AccountID.newBuilder()
Done, thanks.

2024-10-11 14:26 UTC, steven-sheehy approved these changes
LGTM

2024-10-11 15:01 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-10-11 15:02 UTC, merged