Add acceptance tests for fungible token airdrop
hashgraph/hedera-mirror-node pull request #9528
Opened 2024-10-07 12:52 UTC by nickeynikolovv

**Description**:
This PR adds acceptance tests for airdrop of fungible tokens
The tests include - Airdrop transaction, Claim airdrop, Cancel airdrop and validating the responses from the mirror node REST api for the pending and oustanding airdrops

**Related issue(s)**:

Fixes #8278 

**Notes for reviewer**:
The tests for Airdrops of NFT will be added in a separate PR

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-07 14:00 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private TokenAirdrop getPendingAirdropForSpecificToken(TokenId tokenId, AccountId accountId) {
The airdrop should be filtered out to be also from a specific `sender`, so that all test cases are correct.

2024-10-07 14:12 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private TokenAirdrop getOutstandingAirdropForSpecificToken(TokenId tokenId, AccountId accountId) {
Same comment as above. A given airdrop is determined by 3 components - token, sender and a recipient.

2024-10-07 14:57 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private TokenAirdrop getPendingAirdropForSpecificToken(TokenId tokenId, AccountId accountId) {
Fixed - added 3 way validation - tokenId, sender and receiver

2024-10-07 14:57 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private TokenAirdrop getOutstandingAirdropForSpecificToken(TokenId tokenId, AccountId accountId) {
Fixed - added 3 way validation - tokenId, sender and receiver

2024-10-08 11:11 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        for (TokenAirdrop tokenAirdrop : outstandingAirdrops) {
You can use Java's stream library and filter the results directly in the stream

2024-10-08 11:12 UTC, IvanKavaldzhiev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    private TokenAirdrop getOutstandingAirdropForSpecificToken(TokenId tokenId, AccountId sender, AccountId receiver) {
The name of this method and the one above might be misleading. We are getting an airdrop for a specific token, specific recipient and specific sender.

We can just leave the names to be:
-  getOutstandingAirdrop
- getPendingAirdrop

2024-10-08 11:58 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        for (TokenAirdrop tokenAirdrop : outstandingAirdrops) {
Done

2024-10-08 13:19 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-10-08 16:22 UTC, xin-hedera requested changes

2024-10-08 16:22 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Then("I verify {string} airdrop of {int} tokens to {account} from {account}")
Add retry logic so it'll auto retry in case mirrornode data isn't ready.
```suggestion
    @RetryAsserts
    @Then("I verify {string} airdrop of {int} tokens to {account} from {account}")
```

2024-10-08 16:22 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(tokenRelationshipReceiver.getTokens().getFirst().getTokenId())
`getFirst()` will throw if the list from `getTokens()` is empty. instead should do

```java
  assertThat(tokenRelationshipReceiver.getTokens())
     .hasSize(1)
     .first()
     .returns(...)
     .returns(...);
```

2024-10-09 10:17 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(tokenRelationshipReceiver.getTokens().getFirst().getTokenId())
done

2024-10-09 10:17 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    @Then("I verify {string} airdrop of {int} tokens to {account} from {account}")
done

2024-10-09 10:17 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            String status, int amount, AccountNameEnum receiverName, AccountNameEnum senderName) {
done

2024-10-09 10:17 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteCancelTokenAirdrop(
fixed

2024-10-09 10:17 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +        var response = executeTransactionAndRetrieveReceipt(transaction, KeyList.of(receiver.getPrivateKey()), sender);
fixed

2024-10-09 12:05 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                "Airdroped {} tokens of {} from {} to {} via {}",
nit: `Airdroped` typo.

2024-10-09 12:25 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +                "Airdroped {} tokens of {} from {} to {} via {}",
fixed

2024-10-09 13:12 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteClaimTokenAirdrop(
nit: typo in method name

2024-10-09 13:44 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(pendingAirdropForToken.getAmount()).isEqualTo(amount);
For the nfts I've added separate method for verifications called `verifyNftTokenAirdrop` because it checks additional responses from the REST API like `/accounts/{id}/nfts` and` /tokens/{id}/nfts/{serial}` so i think that if they are separated will be more readable. However in the following PR for the nft tests I can think of a way of combining verifications of airdrops in 1 common method with different assertions depending on the token type - either fungible or nft - Let me know what do you think?

2024-10-09 13:48 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteClaimTokenAirdrop(
fixed

2024-10-09 14:25 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-10-09 15:26 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(pendingAirdropForToken.getAmount()).isEqualTo(amount);
Cool sounds good

2024-10-09 15:27 UTC, edwin-greene submitted a review, later dismissed
Looks good to me

2024-10-09 21:07 UTC, steven-sheehy requested changes

2024-10-09 21:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(tokenAirdrop.getTokenId()).isEqualTo(tokenId.toString());
Always chain when you can.

```suggestion
        assertThat(tokenAirdrop)
            .isNotNull()
            .returns(receiver.toString(), TokenAirdrop::getReceiverId)
            .returns(sender.toString(), TokenAirdrop::getSenderId)
            .returns(tokenId.toString(), TokenAirdrop::getTokenId);
```

2024-10-09 21:07 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    }
These cancel, claim, airdrop hapi functions are pretty minimal. We can get ride of them completely if we either push assertions into client or add a verify method that wraps the call.

```suggestion
    private NetworkTransactionResponse verify(NetworkTransactionResponse response) {
        assertThat(response.getTransactionId()).isNotNull();
        assertThat(response.getReceipt()).isNotNull();
        networkTransactionResponse = response;
        return response;
    }
```

2024-10-10 09:07 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    }
Done - made it that way

2024-10-10 09:07 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertThat(tokenAirdrop.getTokenId()).isEqualTo(tokenId.toString());
done

2024-10-10 09:07 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            default -> log.warn("Invalid airdrop status");
fixed

2024-10-10 09:07 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        assertNotNull(networkTransactionResponse.getReceipt());
fixed

2024-10-10 14:56 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        networkTransactionResponse = airdropFungibleTokens(tokenId, amount, sender, receiver);
airdropFungibleTokens() helper can also be removed.

```suggestion
        verify(tokenClient.executeFungibleTokenAirdrop(tokenId, sender, receiver.getAccountId(), amount));
```

2024-10-10 17:20 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +        networkTransactionResponse = airdropFungibleTokens(tokenId, amount, sender, receiver);
Done

2024-10-10 17:23 UTC, steven-sheehy approved these changes
LGTM

2024-10-10 17:26 UTC, xin-hedera approved these changes

2024-10-10 17:33 UTC, merged