Add acceptance tests for NFT  airdrop
hashgraph/hedera-mirror-node pull request #9540
Opened 2024-10-09 13:51 UTC by nickeynikolovv

**Description**:
This PR adds acceptance tests for airdrop of non fungible token
The tests include - Airdrop transaction, Claim airdrop, Cancel airdrop and validating the responses from the mirror node REST api for the pending and oustanding airdrops

**Related issue(s)**:

Fixes #9529 

**Notes for reviewer**:
This PR depends on the PR for fungbile token airdrop #9528 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-10 12:19 UTC, kselveliev commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Retrieving outstanding airdrops for account '{}' returned by Mirror Node", accountId);
Here we are querying for nfts we can refactor the log message

2024-10-10 18:30 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteCancelNftAirdrop(
nit type in name: `exeucute`

2024-10-10 18:30 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteClaimNftAirdrop(
nit type in name: `exeucute`

2024-10-10 18:45 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            ExpandedAccountId receiver,
It looks like `TokenFeature` calls this and can provide either the `ExpandedAccountId` or `AccountId`. It looks like `receiver` can be `AccountId`. Then this signature would match the signature from the fungible airdrop method. This change could also work for the `executeClaimNftAirdrop` method as well.

2024-10-10 18:48 UTC, edwin-greene commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +            default -> log.warn("Invalid airdrop status");
Can change this to `IllegalArgumentException` like it is for the fungible airdrops.

2024-10-11 12:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
> +        log.debug("Retrieving outstanding airdrops for account '{}' returned by Mirror Node", accountId);
fixed

2024-10-11 12:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteCancelNftAirdrop(
fixed

2024-10-11 12:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteClaimNftAirdrop(
fixed

2024-10-11 12:05 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +    public NetworkTransactionResponse exeucuteClaimTokenAirdrop(
fixed

2024-10-11 12:08 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
> +            ExpandedAccountId receiver,
Made it that way for cancel airdrop. However for claim it won't work that way because the claim should be signed by the receiver and private key cannot be get from AccountId

2024-10-11 14:25 UTC, xin-hedera requested changes

2024-10-11 14:25 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void airdropNonFungibleToken(int serialNumber, AccountNameEnum accountName) {
should phrase and implement as `serial number index {int}`. there is no guarantee that the serial number exists, that's why the class holds a map with serial number index to serial number mapping,

```java
  tokenNftInfoMap.get(tokenId).get(serialNumberIndex).serialNumber();
```

2024-10-14 09:38 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
> +    public void airdropNonFungibleToken(int serialNumber, AccountNameEnum accountName) {
done

2024-10-15 00:09 UTC, steven-sheehy approved these changes

2024-10-15 00:09 UTC, merged