Automated Backup For Citus
hashgraph/hedera-mirror-node pull request #9541
Opened 2024-10-09 14:20 UTC by jnels124

**Description**:
* add minio to common chart
* add stackgres backup components

**Related issue(s)**:

Fixes #5306

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-11 15:50 UTC, xin-hedera requested changes

2024-10-11 15:50 UTC, xin-hedera commented on charts/hedera-mirror-common/values.yaml
> +        purge: true
what do `policy` and `purge` do? I can't find any reference in the chart's doc.

2024-10-11 15:50 UTC, xin-hedera commented on charts/hedera-mirror-common/Chart.yaml
> +    version: 14.7.10
latest is 14.7.15

2024-10-11 15:50 UTC, xin-hedera commented on charts/hedera-mirror-common/values.yaml
> +      namespace: common
should not hardcode namespace and we don't have to. If not set, the template function will use `.Release.Namespace`

2024-10-11 21:16 UTC, steven-sheehy requested changes

2024-10-11 21:16 UTC, steven-sheehy commented on charts/hedera-mirror-common/templates/zfs/volumesnaphotclass.yaml
> +  annotations:
Missing namespace and can sort annotations

2024-10-11 21:16 UTC, steven-sheehy commented on charts/hedera-mirror/templates/stackgres/stackgres-objectstorage-secret.yaml
> +{{- $secretData := $secret.data | default dict -}}
It's not clear what the point of this file is because it doesn't set any values from values.yml. It looks like it's created empty and this ensures that if it was modified afterwards outside helm that it will persist those changes. Is something modifying this outside helm? Maybe we can add a comment if so.

2024-10-15 16:28 UTC, jnels124 commented on charts/hedera-mirror-common/values.yaml
> +        purge: true
Those can actually be removed. will do so

2024-10-15 16:29 UTC, jnels124 commented on charts/hedera-mirror-common/templates/zfs/volumesnaphotclass.yaml
> +  annotations:
this is a global resource

2024-10-15 16:52 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-10-16 15:50 UTC, steven-sheehy approved these changes

2024-10-16 16:54 UTC, merged