Add FileReadableKVState
hashgraph/hedera-mirror-node pull request #9570
Opened 2024-10-11 08:46 UTC by kselveliev

**Description**:
This pr add FileReadableKVState

**Related issue(s)**:

Fixes #9258

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-11 08:59 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +import edu.umd.cs.findbugs.annotations.NonNull;
In the other PRs we use `jakarta.annotation.Nonnull`.

2024-10-11 09:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .expirationSecond(fileData.getConsensusTimestamp())
I believe this information should be taken from `entity` table

2024-10-11 11:03 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
> +        EntityId expectedEntityId = EntityId.of(shard, realm, fileNum);
EntityIdUtils method can be used here

2024-10-11 12:42 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +import edu.umd.cs.findbugs.annotations.NonNull;
Good catch. Comment addressed.

2024-10-11 12:44 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .map(t -> fileDataRepository.getFileAtTimestamp(fileId, t))
Not really sure if we can use this already existing getFileAtTimestamp since it is checking for transaction types 17 or 19. While find by id does not care about this. Probably we need another query here.

2024-10-14 06:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .map(t -> fileDataRepository.getFileAtTimestamp(fileId, t))
I think it's OK to continue filter by transaction type 17 and 19.

2024-10-14 10:58 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static EntityId toEntityId(final com.hedera.hapi.node.base.FileID fileID) {
We need a test for this new method.

2024-10-14 11:04 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/FileReadableKVStateTest.java
> +    private static final FileID FILE_ID = FileID.newBuilder()
A utility method can be used here.

2024-10-14 12:52 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/file/File.java
> +        if (expirationSecondSupplier == null && thatObj.expirationSecondSupplier != null) {
We introduced a utility method for this check in a previous PR -> `Suppliers#areSuppliersEqual`

2024-10-14 12:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/FileReadableKVStateTest.java
> +    void sizeIsAlwaysEmpty() {
nit: sizeIsAlways**Zero**

2024-10-14 13:04 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/FileReadableKVStateTest.java
> +    void sizeIsAlwaysEmpty() {
Comment addressed

2024-10-14 13:05 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/file/File.java
> +        if (expirationSecondSupplier == null && thatObj.expirationSecondSupplier != null) {
Comment addressed

2024-10-14 13:37 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .expirationSecond(fileData.getConsensusTimestamp())
Comment addressed, added it in a supplier field

2024-10-14 13:57 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
> +    public static EntityId toEntityId(final com.hedera.hapi.node.base.FileID fileID) {
Comment addressed

2024-10-14 13:57 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/FileReadableKVStateTest.java
> +    private static final FileID FILE_ID = FileID.newBuilder()
Comment addressed

2024-10-14 13:59 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
> +        EntityId expectedEntityId = EntityId.of(shard, realm, fileNum);
I believe this code got obsolete after the latest refactoring

2024-10-14 14:06 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/file/File.java
> +import edu.umd.cs.findbugs.annotations.NonNull;
This and the next import -> we use the imports from `jakarta`.

2024-10-14 14:38 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/file/File.java
> +import edu.umd.cs.findbugs.annotations.NonNull;
Comment addressed

2024-10-15 00:16 UTC, steven-sheehy requested changes

2024-10-15 00:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> + * mirror-node The object, which is read from DB is converted to the PBJ generated format, so that it can properly be
```suggestion
 * mirror-node. The file data, which is read from the database is converted to the PBJ generated format, so that it can properly be
```

2024-10-15 00:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .contents(Bytes.wrap(fileData.getFileData()))
nit: sort

2024-10-15 00:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertNotEquals(item1, item1WithDifferentContents);
Should always use assertj

2024-10-15 08:06 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertNotEquals(item1, item1WithDifferentContents);
Comment addressed

2024-10-15 08:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .contents(Bytes.wrap(fileData.getFileData()))
Comment addressed

2024-10-15 08:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> + * mirror-node The object, which is read from DB is converted to the PBJ generated format, so that it can properly be
Comment addressed

2024-10-15 08:44 UTC, bilyana-gospodinova approved these changes
LGTM

2024-10-15 10:33 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertThat(nullItem).isNotEqualTo(item1);
This can be replaced with: `assertThat(item1).isNotNull();`

2024-10-15 12:32 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertThat(nullItem).isNotEqualTo(item1);
I think changing this will switch a bit the aim of the test.
Right now in eventually does -> `if (actual == null) return other == null;` which compares both objects to null which is what we want.
While if we change to assertThat(item1).isNotNull(); we will check only item1.

2024-10-15 12:44 UTC, IvanKavaldzhiev approved these changes
LGTM

2024-10-15 12:54 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertThat(nullItem).isNotEqualTo(item1);
You are right about that. However, we can call: `assertThat(item1).isNotEqualTo(null);`
This is equivalent to `item1.equals(null)` which is what we want to check after all. And we don't have a valid case when we will compare `null.equals(item1)` since this will throw a NPE.

2024-10-15 13:18 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertThat(nullItem).isNotEqualTo(item1);
Applied the above suggestion

2024-10-15 13:39 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertThat(nullItem).isNotEqualTo(item1);
We don't need the `final File nullItem = null;` line anymore.

2024-10-15 13:44 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
> +        assertThat(nullItem).isNotEqualTo(item1);
done

2024-10-15 13:48 UTC, bilyana-gospodinova approved these changes
LGTM

2024-10-15 14:51 UTC, steven-sheehy approved these changes

2024-10-15 14:52 UTC, merged