Add REST API query normalization
hashgraph/hedera-mirror-node pull request #9591
Opened 2024-10-16 19:11 UTC by edwin-greene

**Description**:
Adds a means to normalize REST API queries.

**Related issue(s)**:

Fixes #9113 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-18 18:21 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const NON_SORTED_PARAMS = ['balance', 'block.hash', 'block.number', 'nonce', 'scheduled', 'timestamp'];
I don't understand how the sql query can change based upon the param order. That would make results inconsistent for users with the same params. Can you clarify maybe with an example?

2024-10-18 18:24 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const stringifyOptions = {encode: false, indices: false, sort: alphabeticalSort};
nit: Move constant object to the top of file

2024-10-18 18:28 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +        '/api/v1/transactions?limit=25&order=desc&timestamp=1639010141.000000001&timestamp=1639010141.000000000',
Shouldn't we sort by values for same param to provide consistent results and reduce cache misses?

2024-10-18 18:33 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/openapiHandler.js
> +    const map = new Map();
We should sort the map so that we iterate it in the order we want the normalized output.

2024-10-18 18:37 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +};
This is inefficient since it loops over N params once to generate a new list, then again to stringify and sort that list. Instead, we should have the OpenAPI params already sorted by name on startup and loop once to directly construct final sorted string. Then we also don't need to clone the params.

2024-10-18 18:46 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/openapiHandler.js
> +      .map((p) => p.$ref?.substring(24))
Should put `#/components/parameters/` in a constant and first filter the parameters by prefix and then use the string size to get substring.

2024-10-18 21:36 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +      expected: '/api/v1/blocks?limit=25&order=asc&unknown=3',
We shouldn't need to handle unknown query parameters since we throw an error if any unknown.

2024-10-21 15:41 UTC, edwin-greene commented on hedera-mirror-rest/middleware/openapiHandler.js
> +      .map((p) => p.$ref?.substring(24))
Sounds good I have updated this.

2024-10-21 15:44 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +        '/api/v1/transactions?limit=25&order=desc&timestamp=1639010141.000000001&timestamp=1639010141.000000000',
I have updated the comments with examples of when the array parameters should not be sorted, as in some cases the sorting of the array parameters changes the result.

2024-10-21 15:44 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const NON_SORTED_PARAMS = ['balance', 'block.hash', 'block.number', 'nonce', 'scheduled', 'timestamp'];
Thanks I added some examples that I found from running the query normalizer on the spec tests.

2024-10-21 15:45 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +};
Got it, I have updated this to generate the query string with a single loop.

2024-10-21 15:45 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const stringifyOptions = {encode: false, indices: false, sort: alphabeticalSort};
This should now be good, this method was removed.

2024-10-21 17:02 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +      expected: '/api/v1/blocks?limit=25&order=asc&unknown=3',
At this current revision I have simplified the looping to generate the query string to such an extent that it ignores unknown parameters. This may not be what we want, considering that the unknown parameter will later throw an error, I will work on fixing this next.

2024-10-21 19:03 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const NON_SORTED_PARAMS = ['balance', 'block.hash', 'block.number', 'nonce', 'scheduled', 'timestamp'];
I see. So it's for APIs that honor the last such parameter. But the way we implemented it it will occur for all APIs that have such param even if they don't have that behavior. 

Can we double check if any of these params are used in multiple APIs where one only uses last while other uses all? If they're always last one in wins then we can just change the behavior to collapse them in the normalizer as well.

2024-10-21 19:06 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const NON_SORTED_PARAMS = ['balance', 'block.hash', 'block.number', 'nonce', 'scheduled', 'timestamp'];
Either way, it might be nice to add some sentence to each parameter's description that indicates if multiple values are passed to this parameter, only the last one will be honored. Then we can search for that sentence when normalizing and use the presence of that wording to control normalizing logic.

2024-10-21 19:08 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +      expected: '/api/v1/blocks?limit=25&order=asc&unknown=3',
In the future, we could use this openapi map to implement the unknown parameter handling and remove all the custom logic we added throughout.

2024-10-23 19:33 UTC, xin-hedera requested changes

2024-10-23 19:33 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +describe('request normalizer', () => {
it's worth to register a test-only middleware inside openapiHandler `openApiValidator` function, after the OpenAPI 
validator middleware, to normalize the the request URL, and set it in the http response as done in this integration test.

That way, we can

- add expected normalized URLs to all existing json spec files, and
- update the integration template.js to validate it

That'll get us full coverage and less error-prone to miss it in the future.

It's a lot of work though, just to update all existing specs...

2024-10-23 19:33 UTC, xin-hedera commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  }
why can't we build an array of `k=v` fragments and do a `join('&')` at the end, instead of appending one by one?

2024-10-24 13:19 UTC, edwin-greene commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +describe('request normalizer', () => {
I am working on this now, I will add it as a separate comment to addressing the other feedback as it is a larger commit.

2024-10-25 20:13 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +describe('request normalizer', () => {
Can't we do this as a follow up?

2024-10-25 20:59 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
> +describe('request normalizer', () => {
fine with that.

2024-10-28 15:13 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-10-28 16:54 UTC, steven-sheehy requested changes

2024-10-28 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +    return name + '=' + valuesArray[valuesArray.length - 1];
Is it possible valuesArray can be empty in which case this would throw an error? Should add a check and a test just in case

2024-10-28 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  const openApiParameters = openApiMap.get(openApiRoute);
Is it possible the route is ever not found? Maybe add a check and a test just in case.
```suggestion
  const openApiParameters = openApiMap.get(openApiRoute) || {};
```

2024-10-28 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  return queryArray.length !== 0 ? path + '?' + queryArray.join('&') : path;
Why do we need an array just to generate a string? We can just concatenate strings inside the loop and avoid the array.

2024-10-28 16:54 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +      queryArray.push(name + '=' + param.defaultValue);
`name + '='` is repeated in multiple places. Pull up outside the conditionals so it occurs once per loop.

2024-10-28 16:56 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  return queryArray.length !== 0 ? path + '?' + queryArray.join('&') : path;
I see now you did have it that way then switched it based upon Xin's suggestion. Not sure why that wasn't discussed since I had suggested it be String earlier.

2024-10-28 19:40 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +    return name + '=' + valuesArray[valuesArray.length - 1];
Thanks, there is some trust in the parameters from OpenApi, where it seems that the object passed from it, if an array, is always an array with 2 elements. But if that changes at some point, I have added a check to the beginning of the method to check to see if at least 1 element is in the array, if not then the method doesn't need to go any further.

2024-10-28 19:40 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  const openApiParameters = openApiMap.get(openApiRoute);
I tried this, or something similar: ` const openApiParameters = openApiMap.get(openApiRoute) || []` and added a test case for a request that has no matching openApi parameters. I found that if that request had query parameters that the current iteration of the method would remove them. So instead I added a check for the open api parameters, and if missing, then the normalized query will be generated with querystring.

2024-10-28 19:40 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  return queryArray.length !== 0 ? path + '?' + queryArray.join('&') : path;
Thanks I see, I had thought that the second variation, which reintroduced the array, had kept the best loop performance enhancements of the first revision (the string concatenation revision), but I neglected to consider that the .join at the end was another loop through the same parameters. I have reverted it to the string concatenation version with some additions per feedback.

2024-10-28 19:40 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +      queryArray.push(name + '=' + param.defaultValue);
Thanks, I updated this to consolidate those concatenations. There is still one exception, when the query is an array of values then they are concatenated in that method to save the need from adding the .isArray conditional to the main loop a second time.

2024-10-28 19:43 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const COLLAPSABLE_PARAMS = [filterKeys.BALANCE, filterKeys.BLOCK_HASH, filterKeys.NONCE, filterKeys.SCHEDULED];
I've updated this list, adding block.hash

2024-10-28 19:46 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +  }
This is not covered in tests, as the OpenApi object doesn't seem to generate empty arrays.

2024-10-28 21:31 UTC, steven-sheehy approved these changes

2024-10-28 21:32 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const COLLAPSABLE_PARAMS = [filterKeys.BALANCE, filterKeys.BLOCK_HASH, filterKeys.NONCE, filterKeys.SCHEDULED];
Probably should updated description to note behavior of block.hash in openapi.yml

2024-10-28 21:49 UTC, jnels124 approved these changes
LGTM

2024-10-29 11:15 UTC, edwin-greene commented on hedera-mirror-rest/middleware/requestNormalizer.js
> +const COLLAPSABLE_PARAMS = [filterKeys.BALANCE, filterKeys.BLOCK_HASH, filterKeys.NONCE, filterKeys.SCHEDULED];
Thanks I have updated it

2024-10-29 13:30 UTC, xin-hedera approved these changes
LGTM

2024-10-29 14:41 UTC, steven-sheehy approved these changes

2024-10-29 14:42 UTC, merged