Implement `AirdropsReadableKVState`
hashgraph/hedera-mirror-node pull request #9598
Opened 2024-10-17 10:46 UTC by bilyana-gospodinova

**Description**:
As part of the implementation for the reusable (modularized) services we need to implement `AirdropsReadableKVState`. It reads a pending airdrop id and converts it to `AccountPendingAirdrop` PBJ type.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9257

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-17 13:01 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
Why do we need this statement?
If it is an nft should we just return AccountPendingAirdrop with an amount of 1. 
Since the default value is 0 in the model.
I'm not really sure what is the correct business logic here.

2024-10-17 13:04 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
I just saw the model docs -> 
  *               If the token is a non-fungible/unique token, this message SHOULD NOT be set, and if
  *               set, this field MUST be `0`.
 So this should be correct

2024-10-17 13:04 UTC, kselveliev submitted a review, later dismissed

2024-10-17 13:28 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
Correct - the model documentation requires this return value.

2024-10-18 19:12 UTC, steven-sheehy requested changes

2024-10-18 19:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
I don't think this is true. That means nft airdrops are not stored in state and always return empty? Instead, we should lookup nft airdrop in the db and just return AccountPendingAirdrop with unset value.

2024-10-18 19:12 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +                .pendingAirdropValue(mapToPendingAirdropValue(amount))
Do we not need to populate the next and previous links?

2024-10-21 13:50 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +                .pendingAirdropValue(mapToPendingAirdropValue(amount))
I think they are used in services for iterating for example trying to delete an account and fetching all their sent pending airdrops. We won't have such cases in our web3 simulations, so for the moment it seems redundant to populate these links.

2024-10-21 14:09 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-10-21 15:38 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
`AccountPendingAirdrop` has 3 fields:
```
@Nullable PendingAirdropValue pendingAirdropValue,
@Nullable PendingAirdropId previousAirdrop,
@Nullable PendingAirdropId nextAirdrop
```
The last two we set to `null` as per the comment here: https://github.com/hashgraph/hedera-mirror-node/pull/9598#discussion_r1808867018

The first field (`PendingAirdropValue`) has only: `long amount` as a field. So, why should we read the nft airdrop from the DB when we know that we are going to return `AccountPendingAirdrop` with all null values? @steven-sheehy, can you please clarify?

2024-10-21 16:41 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
The return value of `AccountPendingAirdrop.DEFAULT` is correct when the ID exists, but you have not verified existence of the `PendingAirdropId` in the database before returning it. If it does not exist you should return null.

You can see [upstream](https://github.com/hashgraph/hedera-services/blob/6d4c18868da1f4fb985615608b74e1ba18dcc6fd/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAirdropHandler.java#L352) that an AccountPendingAirdrop with a null value is put into the airdrop store for NFTs.

2024-10-22 11:57 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
> +        if (key.hasNonFungibleToken()) {
Got it. I updated the nft case implementation and added more tests.

2024-10-22 13:11 UTC, kselveliev approved these changes

2024-10-22 14:08 UTC, steven-sheehy approved these changes
LGTM

2024-10-22 14:22 UTC, merged