feat: Convert evm properties to a map of configuration properties
hashgraph/hedera-mirror-node pull request #9622
Opened 2024-10-21 09:57 UTC by kselveliev

Convert Mirror

**Description**:
Convert MirrorNodeEvmProperties to a map of configuration properties for transaction executors.

This PR modifies ... in order to support ...
* Add config property
* Change column name
* Remove ...
-->

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-22 17:07 UTC, steven-sheehy requested changes

2024-10-22 17:07 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ModularizedProperties.java
> +        propertiesMap.put(
The problem here is now we have two levels of properties each with their own validation and defaults: Spring boot properties and consensus node properties. If we have a default to match consensus nodes and later they change their default upstream, we won't be able to catch these types of problems.

I think since upstream has validation and defaults, we should just use those. That way we don't need to do explicit mapping between Spring properties and node properties. Only properties that we need to explicitly override to work with mirror node should be in that map. Everything else should be omitted to use the upstream default. Of course this results in extra properties for a little while until later we can delete the relevant hardcoded properties in MirrorNodeEvmProperties.


```java
@ConfigurationProperties(prefix = "hedera.mirror.web3.evm")
public class MirrorNodeEvmProperties {
    ...
    private final Map<String, String> properties = Map.of("contracts.chainId", chainIdBytes32().toBigInteger().toString());
}
```

Then we can override using application.yml:

```yaml
hedera:
  mirror:
    web3:
      evm:
        properties:
          contracts.allowCreate2: "false"
```


If any properties are dynamic per request, we just create a copy of `properties` and `put` the dynamic properties into that for reach request.

2024-10-23 10:26 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ModularizedProperties.java
> +    private static final String EVM_VERSION = "contracts.evm.version";
I’m not sure if we can read the keys directly from the upstream code
For example upstream reads the config from 
```
@ConfigData("contracts")
public record ContractsConfig(
        @ConfigProperty(defaultValue = "true") @NetworkProperty boolean itemizeStorageFees,
        @ConfigProperty(defaultValue = "1062787,1461860") Set<Long> permittedDelegateCallers,
        @ConfigProperty(defaultValue = "31536000") @NetworkProperty long referenceSlotLifetime,
        @ConfigProperty(defaultValue = "100") @NetworkProperty int freeStorageTierLimit,
        @ConfigProperty(defaultValue = "0til100M,2000til450M") @NetworkProperty String storageSlotPriceTiers,
        @ConfigProperty(defaultValue = "7890000") @NetworkProperty long defaultLifetime,

```

which as a string key will map to "contracts.itemizeStorageFees"

I think with reflection we might obtain the keys dynamically from the upstream class but it’s probablly not worth it.

Maybe here we can just use the default values as you said use a minimal set of ovverides in our map.

2024-10-23 13:41 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ModularizedProperties.java
> +        propertiesMap.put(
If this is okay then we can delete the ModularizedProperties class

2024-10-23 13:42 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private final Map<String, String> defaultOverrides = Map.of(
Contains properties which we definitely need to override like chainId.

2024-10-23 14:00 UTC, steven-sheehy requested changes

2024-10-23 14:00 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigKeyExtractor.java
> +    public static final String MAX_GAS_REFUND_PERCENTAGE_KEY = "maxRefundPercentOfGasLimit";
This class doesn't really serve any purpose since we have to hardcode strings to pass via reflection just to get back similar hardcoded strings. We should just directly use the hardcoded strings like `contracts.chainId` in `MirrorNodeEvmProperties`.

2024-10-23 14:00 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return Collections.unmodifiableMap(props);
The order is wrong. Defaults are used first and users can override them via properties config.

But why do we even need 4 maps to get the properties (including unmodifiable)? Why can't we just do what I suggested in my original comment?

```java
private Map<String, String> properties = Map.of("contracts.chainId", chainIdBytes32().toBigInteger().toString());
```

2024-10-23 14:02 UTC, bilyana-gospodinova commented
I think this PR is a good place to add a utility method that returns all of the properties (that need override) that we need to pass to the `TransactionExecutors` as a map.

2024-10-23 14:04 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return Collections.unmodifiableMap(props);
My concern here was if we have this yaml 
```
hedera:
  mirror:
    web3:
      evm:
        properties:
          contracts.allowCreate2: "false"
```

And we have default 
private Map<String, String> properties = Map.of("contracts.chainId", chainIdBytes32().toBigInteger().toString());


Then (i think) the end result will be [contracts.allowCreate2: "false"]  and we lose the contracts.chainId property in the map.

2024-10-23 14:05 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigKeyExtractor.java
> +            Field field = configClass.getDeclaredField(fieldName);
Perhaps this method can be used just in the tests instead in order to verify that a property in services has been renamed/deleted.

2024-10-24 13:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigKeyExtractor.java
> +    public static final String MAX_GAS_REFUND_PERCENTAGE_KEY = "maxRefundPercentOfGasLimit";
Comment addressed. Deleted the class.

2024-10-24 13:10 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        props.putAll(properties);
`properties` is just an empty `HashMap`, so why is it added at all? Do we need it?

2024-10-24 13:11 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +class ModularizedPropertiesTest extends Web3IntegrationTest {
There is a `MirrorNodeEvmPropertiesTest` class - can't we add the tests there? Is there a specific reason for a new class?

2024-10-24 13:12 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return Collections.unmodifiableMap(props);
Added integration tests covering the scenarios here.
It seems that we need 2 maps since yaml will overwrite any default values that we have in the initial map and we will lose them.
Switched the order as per the initial comment.
First we put the default values then we put the ones from the yaml config in properties.
Properties existing in both maps will be taken from the config and override initial values.

2024-10-24 13:12 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/ConfigKeyExtractor.java
> +            Field field = configClass.getDeclaredField(fieldName);
Comment addressed

2024-10-24 13:15 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +class ModularizedPropertiesTest extends Web3IntegrationTest {
The MirrorNodeEvmProperties currently only contains unit tests.
If we make it extend integration test and inject MirrorNodeEvmProperties we will have some failing tests.
I added the new tests in a new class since they are only integration tests

2024-10-24 13:20 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        props.putAll(properties);
I don't want to return the original properties since we'll later pass it into TransactionExecutors and then we can't be sure what will happen to it. So I prefer to copy the values in a new map an return it.

2024-10-24 13:26 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +class ModularizedPropertiesTest extends Web3IntegrationTest {
Ok, that's fine then.

2024-10-24 13:41 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        props.putAll(properties);
Got it - `properties` gets filled in from yaml.

2024-10-24 13:58 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +    void getModularizedProperties() {
Perhaps we need one more test for the case when we have the same property in defaultOverrides and in the yaml. Then we need to verify that the expected value is set.

2024-10-24 14:35 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +    void getModularizedProperties() {
Done

2024-10-24 14:35 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +    void getModularizedProperties() {
Added this scenario in the same test

2024-10-24 15:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +        return Collections.unmodifiableMap(props);
Just worked on my machine as well. Comment addressed.

2024-10-25 08:19 UTC, bilyana-gospodinova submitted a review, later dismissed
LGTM

2024-10-25 19:58 UTC, steven-sheehy requested changes

2024-10-25 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +class ModularizedPropertiesTest extends Web3IntegrationTest {
Agree with Bilyana. The standard is if there's both unit and integration to name it with `IntegrationTest` suffix.

```suggestion
class MirrorNodeEvmPropertiesIntegrationTest extends Web3IntegrationTest {
```

2024-10-25 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private Map<String, String> properties = Map.of(
Add `@NotNull`

2024-10-25 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    }
Why do we need to copy this every time it's requested? This would be extra memory overhead for no gain.

2024-10-25 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> -
We should revert the 3 new line deletions in this class since most variables have spacing in between and this would make it inconsistent.

2024-10-25 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +                .isEqualTo(MAX_GAS_REFUND_PERCENTAGE_KEY_CONFIG);
Instead of hardcoding the two, we should loop over properties.getProperties().keySet() and verify getConfigKey for each.

2024-10-25 19:58 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/resources/config/application.yml
> +          contracts.chainId: "297"
nit: sort

2024-10-28 09:43 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +class ModularizedPropertiesTest extends Web3IntegrationTest {
Comment addressed

2024-10-28 09:44 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private Map<String, String> properties = Map.of(
Comment addressed

2024-10-28 09:46 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    }
I was scared to pass the real reference to the modularized code. Then I check what it does with it, initially just loops over it and passes the values in a config builder and does not use it again.
So I removed this and now just use Getter annotation for getProperties.

2024-10-28 09:46 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/ModularizedPropertiesTest.java
> +                .isEqualTo(MAX_GAS_REFUND_PERCENTAGE_KEY_CONFIG);
Comment addressed

2024-10-28 09:46 UTC, kselveliev commented on hedera-mirror-web3/src/test/resources/config/application.yml
> +          contracts.chainId: "297"
Comment addressed

2024-10-28 12:01 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
> +        for (String configKey : propertyKeys) {
You can use java streams here

2024-10-28 12:02 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
> +        String fieldName = configKey.replace(CONTRACTS_CONFIG + DOT_SEPARATOR, "");
can use var

2024-10-28 12:08 UTC, nickeynikolovv commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
> +                .doesNotContainEntry(CHAIN_ID_KEY_CONFIG, "296")
Why is testnet chainId hardcoded - Isn't the test going to fail if run on testnet?

2024-10-28 13:46 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
> +        for (String configKey : propertyKeys) {
Comment addressed

2024-10-28 13:46 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
> +        String fieldName = configKey.replace(CONTRACTS_CONFIG + DOT_SEPARATOR, "");
Comment addressed

2024-10-28 13:49 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
> +                .doesNotContainEntry(CHAIN_ID_KEY_CONFIG, "296")
For integration tests the chainId is currently explicitly set in test yaml file to 297. This test yaml of the web3 is probably the same in every environment, so I don't think this could be an issue,.

2024-10-28 14:38 UTC, nickeynikolovv approved these changes
LGTM

2024-10-28 15:41 UTC, steven-sheehy approved these changes
LGTM

2024-10-28 15:43 UTC, merged