Add an application cache for REST API
hashgraph/hedera-mirror-node pull request #9626
Opened 2024-10-23 03:19 UTC by jnels124

**Description**:
* implement application cache

**Related issue(s)**:

Fixes #9111 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-25 00:41 UTC, xin-hedera requested changes

2024-10-25 00:41 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  return req.originalUrl;
we should use the hash of the url as the key. We can have very long URLs, and it'll be slower for redis. to lookup long keys.

Suggestion is try to utilize xxhash3 128bit hashing algorithm provided by https://github.com/ktrongnhan/xxhash-addon. The key will be 32 bytes, the hex encoding of the 128-bit hash.

2024-10-25 00:41 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +    const cacheControlHeaderExpiry = getCacheControlExpiry(res.getHeaders()[CACHE_CONTROL_HEADER]);
nit, encapsulate logic of the fallback into `getCacheControlExpiry`, perhaps rename the function to `getCacheControlExpiryOrDefault`

2024-10-25 01:57 UTC, jnels124 commented on hedera-mirror-rest/cache.js
> +    await this.redis
didn't see this will take a look

2024-10-25 14:22 UTC, xin-hedera requested changes

2024-10-25 14:22 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  const cachedTtlAndValue = await cache.getSingleWithTtl(responseCacheKey);
the handling of http HEAD requests should be different. We only need to know if the key exists and it's TTL, we should not need the body or compressed body. If the we have a cached response, we set response code to 304 and complete the processing with an empty body.

2024-10-25 14:22 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  if (responseBody && responseCacheKey && (res.statusCode === 200 || res.statusCode === 304)) {
we should handle all 2xx code and 304. we do return 206 in one endpoint.

It's also very likely when expressjs determines to return 304 for a HEAD request, the body is erased. So we'll be completely wrong here to cache an empty body.

The easiest way to handle 304 is just not handle it here. We can try to get a better understanding and improve the logic in the future.

2024-10-28 14:40 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  const cachedTtlAndValue = await cache.getSingleWithTtl(responseCacheKey);
Should it be 304 though? I thought that code indicates to the requester that they have the value in client cache and therefore would not actually need the response body to be sent on the following GET?

2024-10-28 14:44 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  if (responseBody && responseCacheKey && (res.statusCode === 200 || res.statusCode === 304)) {
This will only cache the 304 if the body is present. Often times, the computed etag will match the `if-none-match` header on the request (meaning this client already has the data). We should still cache the non empty response here to be available for other requesters.

2024-10-28 16:07 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  const cachedTtlAndValue = await cache.getSingleWithTtl(responseCacheKey);
this seems like the more appropriate logic.

```javascript
const startTime = res.locals[requestStartTime] || Date.now();
  const responseCacheKey = cacheKeyGenerator(req);
  const cachedTtlAndValue = await cache.getSingleWithTtl(responseCacheKey);

  if (cachedTtlAndValue) {
    const {ttl: redisTtl, value: redisValue} = cachedTtlAndValue;
    const cachedResponse = Object.assign(new CachedApiResponse(), redisValue);
    const compressedBody = cachedResponse.compressedBody;
    const clientCached = req.get(CONDITIONAL_HEADER) === cachedResponse.headers[ETAG_HEADER]; // 304
    const statusCode = clientCached ? 304 : 200;
    const isHead = req.method === 'HEAD';

    cachedResponse.headers[CACHE_CONTROL_HEADER] = `public, max-age=${redisTtl}`;
    
    if (isHead || clientCached) {
        res.set(cachedResponse.headers);
        res.status(statusCode);
        res.end();
        return;
    }

    if (compressedBody) {
      cachedResponse.body = Buffer.from(cachedResponse.body);
      const acceptsGzip = req.get('accept-encoding')?.includes('gzip');
      if (!acceptsGzip) {
        cachedResponse.body = unzipSync(cachedResponse.body).toString();
      } else {
        cachedResponse.headers[CONTENT_ENCODING_HEADER] = 'gzip';
      }
    }
    
    res.set(cachedResponse.headers);
    res.status(statusCode);
    res.send(cachedResponse.body);
```

2024-10-28 19:39 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  if (responseBody && responseCacheKey && (res.statusCode === 200 || res.statusCode === 304)) {
missed that the body is from the `locals` object. sounds good.

2024-10-28 19:39 UTC, xin-hedera commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  const cachedTtlAndValue = await cache.getSingleWithTtl(responseCacheKey);
yup this looks correct.

2024-10-28 20:28 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  next();
It wasn't going to the next middleware function because it was setup with `app.use` instead `app.useAsync`. I have changed that and moved the `ipmetrics` middleware to be invoked before the cache check handler so that it is not skipped when enabled.

2024-10-28 20:36 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  next();
It wasn't working because the middleware was enabled with `app.use` instead of `app.useAsync`.  Looking at things though, need to make some additional changes if we want the `ipMetrics` middleware to function correctly.

2024-10-28 22:14 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +  return req.originalUrl;
still working on this one. Needs to be recompiled when doing npm install for this package and having some issues

2024-10-29 15:36 UTC, jnels124 commented on hedera-mirror-rest/middleware/metricsHandler.js
> +  next();
nope

2024-10-29 16:29 UTC, xin-hedera submitted a review, later dismissed
LGTM

2024-10-30 21:15 UTC, steven-sheehy requested changes

2024-10-30 21:15 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +    const maxAge = headerValue.match(/^.*max-age=(\d+)/);
Move regex to a constant so it doesn't have to be recompiled.

2024-10-30 21:15 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +    );
We should not have another info level log for every request. That would double our log storage. Move to debug with if debug level check.

2024-10-31 14:37 UTC, jnels124 commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +    );
this will be the only line that logs. The response handler middleware will not run

2024-10-31 14:51 UTC, jnels124 commented on docs/configuration.md
> +| `hedera.mirror.rest.cache.response.enabled`                        | false                   | Whether or not the Redis based REST API response cache is enabled. If so, Redis itself must be enabled
Correct

2024-10-31 15:23 UTC, steven-sheehy commented on hedera-mirror-rest/middleware/responseCacheHandler.js
> +    );
Ah, sounds good

2024-10-31 20:53 UTC, jnels124 commented on hedera-mirror-rest/config/application.yml
> +        maxMemory: 750Mb
will be ready for that. And make adjustments if needed.

2024-10-31 21:39 UTC, steven-sheehy approved these changes

2024-11-01 15:29 UTC, xin-hedera approved these changes
LGTM

2024-11-01 22:30 UTC, merged