Add Developer Quickstart and Development Setup Documentation
hashgraph/hedera-mirror-node pull request #9666
Opened 2024-10-28 09:52 UTC by b-l-u-e

This PR introduces the development.md file that outlines the steps to set up the development environment for the Hedera Mirror Node project. It aims to provide a clear and concise guide for developers, especially first-time contributors, to bootstrap their environment and start contributing to the project.

Key Changes:

Added a development.md file with:
1:  List of required software and versions (Java, Docker, Gradle, Node.js).
2:  Instructions for setting up the development environment.
3:  Steps to compile the project.
4:  Guide on running tests (unit and integration).
5:  Troubleshooting common issues (e.g., Java version mismatch, dependency issues).
6:  Links to coding standards and contributing guidelines.

**Related issue(s)**:
Fixes #5851

2024-10-28 10:51 UTC, b-l-u-e commented
@steven-sheehy requesting for a review

2024-10-31 13:49 UTC, kselveliev commented on docs/development.md
> +### 1. **Java 17+**
You'll notice that all Dockerfiles in Mirror Node use the Java 21 Temurin distribution for building so this should be updated

2024-10-31 20:36 UTC, b-l-u-e commented on docs/development.md
> +### 1. **Java 17+**
You are right i forgot to change the version

2024-11-01 22:12 UTC, steven-sheehy requested changes

2024-11-01 22:12 UTC, steven-sheehy commented on docs/development.md
> +### IntelliJ IDEA Setup
Some other setup we should do is enable save actions with reformat code, optimize imports, rearrange code, run code cleanup, and build project all checked. We also have a java code style that should be imported. https://gist.github.com/steven-sheehy/b324eb91155373c0906387ac88b53207

2024-11-01 22:12 UTC, steven-sheehy commented on docs/development.md
> +   ./gradlew dockerBuild
Updating the example to show the extra docker properties that customize this would be useful. `-PdockerPlatform=linux/amd64 -PdockerRegistry=docker.io -PdockerTag=1.0.0-SNAPSHOT`

2024-11-01 22:14 UTC, steven-sheehy commented on docs/development.md
We should link to the guide somewhere in the root README.md

2024-11-05 00:30 UTC, b-l-u-e commented on docs/development.md
added already

2024-11-05 00:30 UTC, b-l-u-e commented on docs/development.md
> +  ```
done

2024-11-05 00:33 UTC, b-l-u-e commented
requesting for a review @kselveliev @steven-sheehy

2024-11-06 15:27 UTC, steven-sheehy requested changes
Looking good. Just a few more tweaks.

2024-11-06 15:27 UTC, steven-sheehy commented on docs/development.md
> +   ./gradlew dockerBuild \
Should also mention `dockerPush` command in case the developer needs to make that image available for use in a remote Kubernetes.

2024-11-06 15:27 UTC, steven-sheehy commented on docs/development.md
> +The mirror node often depends on containerized services such as **PostgreSQL** or **Prometheus**. These services are
Prometheus isn't required or in the docker-compose.yml but Redis is.

```suggestion
The mirror node often depends on containerized services such as **PostgreSQL** or **Redis**. These services are
```

2024-11-06 15:27 UTC, steven-sheehy commented on docs/development.md
> +      the [Java Code Style by Steven Sheehy](https://gist.github.com/steven-sheehy/b324eb91155373c0906387ac88b53207).
Instead of depending upon the mutable gist can we please add this file to the PR at `docs/palantir-style.xml`?

2024-11-06 17:38 UTC, steven-sheehy approved these changes
LGTM. Thanks for your contribution!

2024-11-06 21:36 UTC, andrewb1269hg approved these changes
Readme reviewed

2024-11-06 23:02 UTC, merged