fix: Fix contract deployment with value
hashgraph/hedera-mirror-node pull request #9668
Opened 2024-10-28 13:29 UTC by kselveliev

**Description**:

This PR fixes contract deployment when the contract deployment is made with value.

This PR modifies :
Modified ContractCallRequest - remove initial to parameter validation.
Modified ContractCallAddressThisTest - added tests for deployment of payable contract with and without value
Modified ContractCallServiceERCTokenModificationFunctionsTest - added tests for deployment of non payable contract with and without value.

**Related issue(s)**:

Fixes #9636 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-28 16:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> -    @AssertTrue(message = "must not be empty")
I think it is safer if we move the old check in the `ContractController` and add additional check before that if the `data` contains an init bytecode (and if it does - skip the other `to` checks, if not - make the old checks for `value`, `from`, empty `to`). This way we will cover the scenario in the issue and cut the failing requests as soon as possible and we will avoid doing any unnecessary computations while preserving the old validations.
If we just remove all validations of the `to` field, the response will change a bit in some situations. For example: a contract call with `to == null`. The controller will not cut the request, the users would not get a message that the "to" field is missing, the receiver will be assigned to `Address.ZERO`. the `ContractExecutionService` will be called, some address lookups of the sender and receiver will be made. Since the receiver is empty, the call will be assumed to be a contract create case instead of a contract call and so on. As a result the returned error might be misleading.

2024-10-28 18:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> -    @AssertTrue(message = "must not be empty")
I just added a new validation to check if data contains init bytecode. Can you check it

2024-10-29 08:04 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        return hasCodeCopy && hasReturn;
I am concerned about this check. If we have a normal contract call with function selector such as: "0xf30039" this check will say that this is a contract create and clearly it is not. I think that the position of these opcodes is important. We need to research this further.

2024-10-29 08:10 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
Why do we remove the old check for `value <= 0 || from == null`? If there is a direct transfer, there needs to have `from`, `to` and `value` set. This was validated in the `ContractControllerTest#callInvalidToDueToTransfer` which is now removed but I think it shouldn't be.

2024-10-29 08:13 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
Also, this way we verify twice if the `to` field is empty - once in `RuntimeBytecodeExtractor.isInitBytecode` and a second time in `StringUtils.isNotEmpty(to)` but I think this validation needs to be changed anyway as explained in my other comments.

2024-10-29 08:20 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +        contractCall(request).andExpect(status().isBadRequest());
Changing this test indicates there is a modification in the previous logic that was unexpected.

2024-10-29 09:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        return hasCodeCopy && hasReturn;
Yes this is correct. I see that the minimum size of the init bytecode for a valid contract deployment is around 14 bytes so I will add this in the check.

2024-10-29 09:13 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +        contractCall(request).andExpect(status().isBadRequest());
I don't think so. Previous version of the test did:

data: randomFunctionSelector(not init code)
to: empty
from: address

and expect success - which is not correct in my opinion.
As far as I understand the only time we can allow the "to" to be empty is when we do contract deployment.

2024-10-29 09:26 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +        contractCall(request).andExpect(status().isBadRequest());
Correct - the only time when "to" can be empty is on contract deploy. So, we need 2 parameterized tests:
1.  One in which the data is set as a correct init bytecode and the old check for success or we wouldn't have a test to verify the positive path for estimate gas.
2. Second parameterized test without "to" and non init bytecode data (but contract call) which is expected to return bad request response code.

2024-10-29 09:27 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
If we are looking only at the ‘to’ validation

As far as I know we can only allow empty ‘to’ when we do contract deployment
meaning: 
```
to: empty 
data: init code for contract deployment
```


In the case where we have direct transfer as you said we want to have 

```
from: address (not empty)
to: address (not empty)
value: some value set
```

from is already handled by its own validation 
to - it will verify that the address is not init bytecode and then it will just do the not empty check for 'to'
value - already has a positiveOrZero validation 

so this scenario should be covered. So this old check only confuses the reader `value <= 0 || from == null` - thats why I removed it.

Maybe I’m missing a corner case.

2024-10-29 10:13 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
Maybe you are right.

2024-10-29 11:19 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +        contractCall(request).andExpect(status().isBadRequest());
Comment addressed I added a couple more estimate gas tests.

2024-10-29 11:20 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        return hasCodeCopy && hasReturn;
Added one more condition to check for min size of the data

2024-10-29 12:26 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        return hasCodeCopy && hasReturn;
I still don't think this check is enough. Example: "getCustomFeesForToken(address)" -> function selector is: "44**f3**8bc8". And if you pass the address of token "00..0**39**", the data would look like: "0x44f38bc8000...039" and this method will identify it as an init bytecode.

2024-10-29 13:18 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
I think removing the previous check will require `to` to be set even if `from` is `null` and value is <=0. I think, we should add additional validation on top of the current one.

2024-10-29 13:33 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +    private static final String RETURN = "f3";
What if the return code is in uppercase ("F3")? The check will be bypassed.

2024-10-29 14:00 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        }
We can add additional logic checking if the data starts with `606060` or `608060` sequence, as this is the current format, where PUSH1 operation is inserting a free memory pointer. In this way we can fail fast, if the `data` doesn't even begin with this sequence. I believe in a lot of cases this check might be very efficient and enough to distinguish between a `bytecode` and `calldata`.

2024-10-29 15:51 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
> +        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
Comment addressed. I added the new logic on top of the current check.

2024-10-29 15:52 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +    private static final String RETURN = "f3";
Correct, I fixed that

2024-10-29 15:54 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        }
This is a great suggestion -> however doing that there was another corner case here you can observe one of the autogenerated solidity classes EthCall.sol init code starts with 6104d25. I'm not sure what this case is but perhaps we should handle it as well. I'm now thinking if there can be other cases like that which we might miss.

2024-10-30 10:00 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        }
I found [a great article](https://medium.com/coinmonks/evm-part-ii-the-journey-of-smart-contracts-from-solidity-code-to-bytecode-a21300b23dee) that explains the structure of the init bytecode. It seems that in each init bytecode there is the sequence "60806040" which is responsible for assigning a free memory pointer. Before that there could be some other instructions for constructing the contract. In your example for `EthCall.sol` the bytecode starts with "6104d2" and this means: "PUSH2 0x4D2", which is "push 1234" which is one of the fields in the contract. And also in each contract there is a `codecopy` instruction afterwards followed by the runtime bytecode. I think this method can be enhanced with these findings and also the position of the opcodes is important. For example - to contain "f3" for the `return` opcode after the `codecopy` and not anywhere in the string. The `codecopy` should be after the free memory pointer "60806040" and so on.

2024-10-30 13:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +    private static final String INIT_CODE = "0x60006000556000526000526000f3";
Perhaps it will be better to add a valid example of an init bytecode that is in compliance with the latest changes to avoid confusion.

2024-10-30 13:43 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
>  public class RuntimeBytecodeExtractor {
This class should be renamed as now it does not only extract runtime bytecode.

2024-10-30 13:46 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
> +        }
Thanks. Looks good now.

2024-10-30 14:00 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
>  public class RuntimeBytecodeExtractor {
Renamed to BytecodeUtils

2024-10-30 14:00 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
> +    private static final String INIT_CODE = "0x60006000556000526000526000f3";
Comment addressed I added a valid init code of and empty contract

2024-10-30 14:02 UTC, bilyana-gospodinova submitted a review, later dismissed
LGTM

2024-10-30 20:05 UTC, steven-sheehy requested changes

2024-10-31 12:02 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +        if (lowerCaseData.length() < MINIMUM_INIT_CODE_SIZE) {
With the new pattern I added this lowercase checking is removed and added in the pattern.

2024-10-31 12:03 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +        return returnIndex != -1;
Comment addressed

2024-10-31 12:31 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +    public static boolean isInitBytecode(String data) {
If not in properties you mean like having this in our code right? ->  
```
private static final boolean CHECK_INIT_CODE_ENABLED = 
        Boolean.parseBoolean(System.getenv("HEDERA_MIRROR_WEB3_EVM_CHECKINITCODE"));
```

2024-10-31 14:10 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +    public static boolean isInitBytecode(String data) {
Correct

2024-10-31 14:35 UTC, steven-sheehy requested changes

2024-10-31 14:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
Can pass Pattern.CASE_INSENSITIVE as a parameter to compile.

2024-10-31 14:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
Believe we should have anchoring `^...$` to ensure strings start and end at beginning. Add test.

2024-10-31 14:35 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
Instead of .* we can use \w* since it should be valid hex. BTW, are you sure it shouldn't be + instead of *?

2024-11-01 09:56 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
Don’t think we can achor we have some scenarios like EthCall.java binary 

where we have some characters before the begin 60806040 pattern → 6104d25…. 60806040

And for the ending achor we pretty much in all cases have f3… and then followed by some extra characters

2024-11-01 11:25 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +    public static boolean isInitBytecode(String data) {
Added the env variable similarly to -> HEDERA_MIRROR_IMPORTER_PARSER_HALTONERROR.
Env variable - HEDERA_MIRROR_WEB3_EVM_SKIPINITCODECHECK
Currently it defaults to false. If false it does the init bytecode check.
If set to true it skips the init bytecode check and the 'to" check works similarly as before

2024-11-01 11:25 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
Comment addressed

2024-11-01 11:29 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java
> +            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
Changed to [0-9a-z]*. It think + is better than * so changed it to +.

I experimented with getting the minimum initialization bytecode for an empty contract but could never achieve it with zero characters between the pattern variables.

2024-11-01 22:19 UTC, steven-sheehy approved these changes
LGTM

2024-11-01 22:20 UTC, merged