ci: Update as per Q3 audit findings
hashgraph/hedera-mirror-node pull request #9682
Opened 2024-10-31 14:26 UTC by mishomihov00

**Description**:

Update as per Q3 audit findings

**Related issue(s)**:

Related to #8832 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-31 14:28 UTC, steven-sheehy requested changes
This needs to be discussed. This is revoking ownership of these files from mirror node team and transferring them to another team. I thought with hiero we were moving away from this approach.

2024-10-31 14:37 UTC, mishomihov00 commented
@steven-sheehy The CODEOWNERS file is primarily used for assigning automatic reviewers for PR's. Of course, I can add the "mirror-node" team if you want, but if I don't, I don't think that this will change anything major. After all this file was missing before this PR, so there were no codeowners initially and I've added it due to the audit criteria. @rbarkerSL Please give your opinion also.

2024-10-31 15:00 UTC, rbarkerSL commented
I agree mirror node team should have full ownership of the repo; the intent is not to take over the ownership here.

I believe the default owner on this repo should be `@hashgraph/mirror-node` as opposed to `release-engineering-managers` and all of the devops-ci/devops-ci-committers lines can be changed over to the `@hashgraph/mirror-node` team as well.

@steven-sheehy do you agree?

2024-10-31 15:15 UTC, steven-sheehy commented
Roger I would agree with that. But would also say I don't think RE should own the README as it's documentation that we frequently change and has no CI impact. Also, we frequently change the gitignore so would like to at least be added to that file.

2024-10-31 15:24 UTC, rbarkerSL requested changes

2024-10-31 15:24 UTC, rbarkerSL commented on .github/CODEOWNERS
> +*   @hashgraph/release-engineering-managers
```suggestion
*   @hashgraph/mirror-node
```

2024-10-31 15:24 UTC, rbarkerSL commented on .github/CODEOWNERS
> +**/.gitignore.*                                 @hashgraph/devops-ci @hashgraph/release-engineering-managers
```suggestion
/.github/                                       @hashgraph/devops-ci @hashgraph/mirror-node @hashgraph/release-engineering-managers
/.github/workflows/                             @hashgraph/mirror-node @hashgraph/devops-ci

# Codacy Tool Configurations
/config/                                        @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/mirror-node
.remarkrc                                       @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/mirror-node

# Self-protection for root CODEOWNERS files (this file should not exist and should definitely require approval)
/CODEOWNERS                                     @hashgraph/release-engineering-managers

# Protect the repository root files
/README.md                                      @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/mirror-node
**/LICENSE                                      @hashgraph/release-engineering-managers

# CodeCov configuration
**/codecov.yml                                  @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/mirror-node

# Git Ignore definitions
**/.gitignore                                   @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/mirror-node
**/.gitignore.*                                 @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/mirror-node
```

2024-11-01 22:26 UTC, steven-sheehy approved these changes

2024-11-04 16:29 UTC, rbarkerSL approved these changes

2024-11-04 16:36 UTC, merged