09260- Add schema registry and migrator components
hashgraph/hedera-mirror-node pull request #9710
Opened 2024-11-05 14:33 UTC by kselveliev

**Description**:
This PR adds subcomponents needed for reusable services -
ServicesRegistryImpl, SchemaRegistryImpl and ServiceMigratorImpl components

This PR adds:
ServicesRegistryImpl class similar to FakeServicesRegistry in services + unit tests
SchemaRegistryImpl class similar to FakeSchemaRegistry in services + unit tests
ServiceMigratorImpl class similar to FakeServiceMigrator in services + unit tests

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-11-05 19:01 UTC, steven-sheehy requested changes

2024-11-05 19:01 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/SchemaRegistryImpl.java
> +    public void migrate(
Where is this method used?

2024-11-06 15:04 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/NetworkInfoImpl.java
> +        return List.of(mockSelfNodeInfo());
This method will be used when we build the state. That is why this change is in the PR

2024-11-06 15:05 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/ServicesRegistryImpl.java
> +    }
Comment addressed

2024-11-06 15:06 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/SchemaRegistryImpl.java
> +    }
Comment addressed

2024-11-06 15:07 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/ServiceMigratorImpl.java
> +public class ServiceMigratorImpl implements ServiceMigrator {
I think it can be both. I made it a bean.

2024-11-06 15:10 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/SchemaRegistryImpl.java
> +    public void migrate(
There will be a method which builds the state similarly to TransactionExecutorsTest in services. 
Here is the flow: 
```
 final var state = new FakeState();
        final var networkInfo = fakeNetworkInfo();
        final var servicesRegistry = new FakeServicesRegistry();
        registerServices(servicesRegistry);
        final var migrator = new FakeServiceMigrator();
        final var bootstrapConfig = new BootstrapConfigProviderImpl().getConfiguration();
        **migrator.doMigrations(**
                state,
                servicesRegistry,
                null,
                new ServicesSoftwareVersion(
                        bootstrapConfig.getConfigData(VersionConfig.class).servicesVersion()),
                new ConfigProviderImpl().getConfiguration(),
                networkInfo,
                new NoOpMetrics());
```
Migrator doMigrations will internally call migrate method of schemaRegistry.
We currenly have this working locally but is not yet on a PR.

2024-11-07 14:42 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/SchemaRegistryImpl.java
> +            }
Slightly above this code we do
-> `final var applications = schemaApplications.computeApplications(previousVersion, latestVersion, schema, config);`
For example in the case of tokenSchema - it returns a list of (STATE_DEFINITIONS, MIGRATION, RESTART)
And the `schema.migrate` populates our readable and writable states with the system accounts.

I've been testing this locally for the past day so I think we should leave them for now.

2024-11-08 15:16 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/SchemaRegistryImpl.java
> +        schemas.add(schema);
I think you are right. Added the remove like in MerkleSchemaRegistry.

2024-11-11 09:58 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/SchemaRegistryImpl.java
> +                stateDataSources.put(def.stateKey(), new ConcurrentHashMap<>());
Just tested a couple of scenarios of consecutive transactions with the same state object this collections are unchanged. So I believe things are handled under the hood. I’ll leave them as they are for now.

2024-11-18 11:48 UTC, bilyana-gospodinova approved these changes
LGTM

2024-11-18 15:56 UTC, merged