HIP-1056 Add block streams design
hashgraph/hedera-mirror-node pull request #9716
Opened 2024-11-07 18:20 UTC by edwin-greene

**Description**:
Adds the design for phase one, support for block stream files.

**Related issue(s)**:

Fixes #9573 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-11-07 18:21 UTC, edwin-greene commented on docs/design/block-streams.md
> +
More details on the missing entries still to come.

2024-11-07 18:24 UTC, edwin-greene commented on docs/design/block-streams.md
> +
I've created a prototype of a block to record file translator for the contract create transaction. If we'd like to include it I can push it up as well.

2024-11-21 21:38 UTC, edwin-greene commented on docs/design/block-streams.md
> +
Specific sql schema still to come

2024-11-25 20:21 UTC, edwin-greene commented on docs/design/block-streams.md
> +
Currently it is expected that there is a single `round` per `block`. The `round` has a `round_number` value that currently equals the block number. In the future multiple rounds could be included in a single block. I am not sure if we want to capture this somewhere.

2024-11-26 19:23 UTC, steven-sheehy requested changes

2024-11-26 19:23 UTC, steven-sheehy commented on docs/design/block-streams.md
> +Rename `record_file` to `block_file`.
Show the sql for these so we can agree on their data types

2024-11-26 19:23 UTC, steven-sheehy commented on docs/design/block-streams.md
> +
Rounds are sequential right? If so, can future proof by adding round_start, round_end columns.

2024-11-26 19:23 UTC, steven-sheehy commented on docs/design/block-streams.md
> +public class BlockStreamVerifier implements StreamFileNotifier, Closable {
Closable is misspelled. But why is it needed? This should be a singleton bean.

2024-11-26 19:23 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| sidecar_count      | Count of all transaction*output.\_transaction type*.sidecars in the blk file                                                        |
Should be zero. Sidecars should go away.

2024-11-26 19:23 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| version            | Record stream version - Perhaps a new version should be added to indicate "Translated from Block"                                   |
Just assume it's 7.

2024-11-26 19:23 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| entity.deleted | state_changes[i].state_change.map_update.value.deleted |
This value doesn't exist. This should be true i map_delete present or false for any other update.

2024-12-03 20:06 UTC, edwin-greene commented on docs/design/block-streams.md
> +![Data Flow](images/blockstream.png)
Thanks I have added it

2024-12-03 20:06 UTC, edwin-greene commented on docs/design/block-streams.md
> +![Data Flow](images/blockstream.png)
Got it, it has been added

2024-12-03 20:06 UTC, edwin-greene commented on docs/design/block-streams.md
> +
Sounds good, I have added them.

2024-12-03 20:07 UTC, edwin-greene commented on docs/design/block-streams.md
> +-Deprecate the REST API's State Proof Alpha. The record files and signature files will no longer be provided in the cloud buckets.
Fixed

2024-12-03 20:07 UTC, edwin-greene commented on docs/design/block-streams.md
> +public class BlockStreamVerifier implements StreamFileNotifier, Closable {
Got it, I have updated that part.

2024-12-03 20:07 UTC, edwin-greene commented on docs/design/block-streams.md
> +    public abstract void poll();
Sounds good, I have updated it to an interface.

2024-12-03 20:08 UTC, edwin-greene commented on docs/design/block-streams.md
> +    T translate(S s);
Good idea, I have changed it to transformer.

2024-12-03 20:08 UTC, edwin-greene commented on docs/design/block-streams.md
> +Rename `record_file` to `block_file`.
Thanks I have updated it and added a note to do it as a lower priority task at the end.

2024-12-03 20:09 UTC, edwin-greene commented on docs/design/block-streams.md
> +Rename `record_file` to `block_file`.
Thanks I have added the sql.

2024-12-03 20:11 UTC, edwin-greene commented on docs/design/block-streams.md
> +public class BlockStreamVerifier implements StreamFileNotifier, Closable {
Thanks I have removed that part, it will not be needed if StreamFileNotifier is used rather than implemented.

2024-12-03 20:11 UTC, edwin-greene commented on docs/design/block-streams.md
> +| sidecar_count      | Count of all transaction*output.\_transaction type*.sidecars in the blk file                                                        |
Got it I have updated it with a note.

2024-12-03 20:11 UTC, edwin-greene commented on docs/design/block-streams.md
> +| version            | Record stream version - Perhaps a new version should be added to indicate "Translated from Block"                                   |
Sounds good I have updated this to 7

2024-12-03 20:12 UTC, edwin-greene commented on docs/design/block-streams.md
> +| entity.deleted | state_changes[i].state_change.map_update.value.deleted |
Thanks for spotting, I have updated it to map_delete/key/value

2024-12-05 20:32 UTC, steven-sheehy commented on docs/design/block-streams.md
> +public class BlockItem implements StreamItem {
We should show the fields in BlockItem. We should filter out proto BlockItems that don't apply to mirror node like EventTransaction in the reader. Thus, our BlockItem doesn't correspond to proto BlockItems but actually aggregates them so that there's one of our BlockItem per Transaction that includes Transaction, result, output, and state changes.

2024-12-05 20:36 UTC, steven-sheehy commented on docs/design/block-streams.md
> +![Data Flow](images/blockstream.png)
It's still not quite right. StreamFileProvider is now there but the direction is wrong and the BlockStreamPoller also goes directly to S3. It should just be S3 <- provider <- poller.

2024-12-05 20:38 UTC, steven-sheehy commented on docs/design/block-streams.md
> +    add column if not exists software_version_patch        int          null,
We should add a note that we should migrate this to be populated from hapi_version* since they're always identical before block streams. And also set it in existing record file readers

2024-12-05 20:46 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| count              | Sum of the transaction_output and transaction_result typed block items in the blk file                                              |
```suggestion
| count              | Sum of the EventTransaction typed block items in the blk file                                              |
```

2024-12-05 20:47 UTC, steven-sheehy commented on docs/design/block-streams.md
> +- Deprecate the REST API's State Proof Alpha. The record files and signature files will no longer be provided in the cloud buckets.
We should have a section that discusses the non-functional requirements including performance testing. We should also enumerate the system test cases.

2024-12-05 20:49 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| contract.id                                   | transaction_output.contract_create.sidecars[i].bytecode.contract_id                                     |
sidecars has gone away in current HIP. please update this table

2024-12-05 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| contract.file_id                              | state_changes[i].state_change.map_update.value.file_value.file_id                                       |
We can get this from the transaction body. In which case we can omit this mapping.

2024-12-05 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| contract_action.consensus_timestamp           | transaction_output.contract_create.sidecars[i].consensus_timestamp                                      |
Believe this timestamp is going away. Can get timestamp from result

2024-12-05 20:52 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| contract_action.payer_account_id              | state_changes[i].state_change.map_update.value.account_value.account_id                                 |
Don't think this is accurate. Can get it from TransactionID

2024-12-05 20:53 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| contract_log.contract_id                      | transaction_output.contract_create.contract_create_result.log_info[i].contract_ID                       |
contract_ID casing

2024-12-05 20:53 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| contract_log.root_contract_id                 | transaction_output.contract_create.contract_create_result.contractID                                    |
The contract_create_result oneof has gone away in latest HIP.

2024-12-05 20:56 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| assessed_custom_fee.token_id                    | transaction_output.assessedCustomFees[i].tokenId                 |
These are in transaction_output.(crypto_transfer|token_airdrop). Please go over latest changes in HIP and update table

2024-12-05 20:57 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| token_transfer.token_id            | transaction_result.tokenTransferLists.tokenTransferList[i].token.tokenID                         |
Anything in `transaction_result` will be nested on level deeper under a transaction specific path.

2024-12-06 22:52 UTC, edwin-greene commented on docs/design/block-streams.md
> +public class BlockItem implements StreamItem {
Sounds good I have added them and noted that it is an aggregate of protobuf block items.

2024-12-06 22:52 UTC, edwin-greene commented on docs/design/block-streams.md
> +![Data Flow](images/blockstream.png)
Thanks, I have updated it.

2024-12-06 22:52 UTC, edwin-greene commented on docs/design/block-streams.md
> +    add column if not exists software_version_patch        int          null,
Good idea, I have added a note about the migration and the change to the readers.

2024-12-06 22:53 UTC, edwin-greene commented on docs/design/block-streams.md
> +| consensus_end      | consensus_timestamp of last transaction_output or transaction_result in the blk file                                                |
I've added a note to that line, and added some text around empty blocks to the reader.

2024-12-06 22:53 UTC, edwin-greene commented on docs/design/block-streams.md
> +| count              | Sum of the transaction_output and transaction_result typed block items in the blk file                                              |
Fixed.

2024-12-06 22:54 UTC, edwin-greene commented on docs/design/block-streams.md
> +- Deprecate the REST API's State Proof Alpha. The record files and signature files will no longer be provided in the cloud buckets.
Great idea, I have added a section on testing with some ideas.

2024-12-06 22:54 UTC, edwin-greene commented on docs/design/block-streams.md
> +| contract.id                                   | transaction_output.contract_create.sidecars[i].bytecode.contract_id                                     |
Got it, those are removed.

2024-12-06 22:54 UTC, edwin-greene commented on docs/design/block-streams.md
> +| contract.file_id                              | state_changes[i].state_change.map_update.value.file_value.file_id                                       |
Sounds good I have removed that line.

2024-12-06 22:54 UTC, edwin-greene commented on docs/design/block-streams.md
> +| contract_action.consensus_timestamp           | transaction_output.contract_create.sidecars[i].consensus_timestamp                                      |
I have update it.

2024-12-06 22:54 UTC, edwin-greene commented on docs/design/block-streams.md
> +| contract_action.payer_account_id              | state_changes[i].state_change.map_update.value.account_value.account_id                                 |
I see, I have fixed that line.

2024-12-06 22:55 UTC, edwin-greene commented on docs/design/block-streams.md
> +| contract_log.contract_id                      | transaction_output.contract_create.contract_create_result.log_info[i].contract_ID                       |
Got it, fixed

2024-12-06 22:55 UTC, edwin-greene commented on docs/design/block-streams.md
> +| contract_log.root_contract_id                 | transaction_output.contract_create.contract_create_result.contractID                                    |
Got it, I have updated it.

2024-12-06 22:57 UTC, edwin-greene commented on docs/design/block-streams.md
> +| assessed_custom_fee.token_id                    | transaction_output.assessedCustomFees[i].tokenId                 |
Thanks, I think I have caught them all.

2024-12-06 22:57 UTC, edwin-greene commented on docs/design/block-streams.md
> +| token_transfer.token_id            | transaction_result.tokenTransferLists.tokenTransferList[i].token.tokenID                         |
Got it, I believe I have caught them all.

2024-12-06 23:40 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| count              | Sum of the transaction_output and transaction_result typed block items in the blk file                                              |
Well, I guess it's only EventTransactions with application transaction field populated. So maybe better to just use transaction_result. Main thing was we shouldn't count both output and result since it would be double the count.

2024-12-06 23:41 UTC, steven-sheehy commented
We should discuss somewhere how we're going to handle filtered block items

2024-12-09 01:11 UTC, steven-sheehy commented on docs/design/block-streams.md
> +                        List<TransactionOutput> transactionOutput, // Note: List may be empty
There will be a 1:1 mapping between Transaction and TransactionOutput. I'm not sure if for transaction types that don't have an item in the output oneof whether they will include an empty TransactionOutput or no output. You should check.

```suggestion
                       TransactionOutput transactionOutput,
```

2024-12-09 13:55 UTC, jnels124 submitted a review, later dismissed
LGTM

2024-12-09 19:11 UTC, edwin-greene commented on docs/design/block-streams.md
> +                        List<TransactionOutput> transactionOutput, // Note: List may be empty
In testing I've found an `EventTransaction` that is a topic update transaction, and in that case the block contained just a `TransactionResult` and had no `TransactionOutput`. 

It may need to be a `List<TransactionOutput>` as an `EventTransaction` that is a token transfer looks like it can be followed by more than one `TransactionOutput`, a `CallContractOutput` and a `CryptoTransferOutput`.

2024-12-09 20:01 UTC, steven-sheehy commented on docs/design/block-streams.md
> +                        List<TransactionOutput> transactionOutput, // Note: List may be empty
You're right. Looks like EVM invoking transactions can contain an extra CallContractOutput.

2024-12-09 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| topic_message.running_hash_version | No longer submitted by the block stream: This is a fixed value that is only updated with a HIP change |
We should make this field nullable and stop populating it then. This can reduce the database size for such a large table.

2024-12-09 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| topic_message.topic_id             | state_changes[i].state_change.map_update.value.topicId                                                |
They don't need to update the topic id for a message submit. This will come from the body so can omit from mapping.

2024-12-09 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| Updates accessed_custom_fee        | Similar to crypto_transfer, accessed at transaction_output.token_airdrop                       |
```suggestion
| assessed_custom_fee        | Similar to crypto_transfer, accessed at transaction_output.token_airdrop                       |
```

2024-12-09 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| schedule.id | state_changes[i].state_change.map_update.value.schedule_value.scheduleID |
Will delete not use map_delete or will it do map_update and set a deleted=true flag in state? Either way, we can just map via schedule_id in body.

2024-12-09 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| schedule.id | transaction_output.schedule_create.scheduled_transaction_id |
a transaction ID is not the same as an entity ID

2024-12-09 20:51 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| node.node_id | state_changes[i].state_change.map_update.key.entity_number_key |
Are you sure it's entity_number_key? node_id is not an Entity ID as it has a separate counter. Maybe it's proto_long. Should double check.

2024-12-10 18:15 UTC, edwin-greene commented
> We should discuss somewhere how we're going to handle filtered block items

Thanks I have added a note about that to the ProtoBlockReader.

2024-12-10 18:17 UTC, edwin-greene commented on docs/design/block-streams.md
> +| topic_message.running_hash_version | No longer submitted by the block stream: This is a fixed value that is only updated with a HIP change |
I have updated the design with sql to make it nullable and then added a section for the importer to change the handling of the runningHashVersion.

2024-12-10 18:17 UTC, edwin-greene commented on docs/design/block-streams.md
> +| topic_message.topic_id             | state_changes[i].state_change.map_update.value.topicId                                                |
Thanks I have removed it.

2024-12-10 18:18 UTC, edwin-greene commented on docs/design/block-streams.md
> +| schedule.id | state_changes[i].state_change.map_update.value.schedule_value.scheduleID |
From my testing so far it will be in a map_update with delete flag. Since it will be in the body I have removed its mapping here.

2024-12-10 18:18 UTC, edwin-greene commented on docs/design/block-streams.md
> +| schedule.id | transaction_output.schedule_create.scheduled_transaction_id |
Thanks, I double checked and it is now fixed, it should be a value in state changes.

2024-12-10 19:44 UTC, xin-hedera commented on docs/design/block-streams.md
> +    private void verifyHashChain(String expected, String actual);
I don't think the claim is true. We should be able to calculate the current block's root hash given the data in `BlockProof`, there is previous block's root hash in `BlockHeader`. With the info, we can still verify the chain of hash. For example, suppose we are at block `N`, and the calculated root hash of `N` is `H(N)`; when the next block `N+1` is downloaded, we check `BlockHeader. previous_block_hash` against `H(N)`, a mismatch means we should not further process block `N+1`

What's unclear is the detailed algorithm to calculate `H(N)`, given the previous block root hash, event transactions, start state root hash, and state changes.

2024-12-10 19:44 UTC, xin-hedera commented on docs/design/block-streams.md
> +- Add `congestionPricingMultiplier`, `round_start`, `round_end` to the `record_file` table, these come from the block.
congestionPricingMultiplier is in `TransactionResult`, is there anywhere in the HIP stating it's the same across a whole block? I strongly doubt so, at least we have different throttles for different transactions, so it's normal for just one type of transaction having congestion pricing applied since only that type of transaction is hitting throttle.

2024-12-10 19:44 UTC, xin-hedera commented on docs/design/block-streams.md
> +Beginning from an `EventTransaction` block item, a record item is composed of one `TransactionResult` block item, zero to N `TransactionOutput` block items and zero to N `StateChange` block items.
there should be 0 to 1 `StateChanges` block item for an `EventTransaction`, since the `StateChanges` proto message itself is a container of multiple state changes

```protobuf
message StateChanges {
    /**
     * The consensus timestamp of this set of changes.
     * See the full specification above for how this value is determined.
     * <p>
     * This value SHALL be deterministic.
     */
    proto.Timestamp consensus_timestamp = 1;

    /**
     * An ordered list of individual changes.
     * <p>
     * These changes MUST be applied in the order listed to produce
     * a correct modified state.
     */
    repeated StateChange state_changes = 2;
}
```

2024-12-10 19:44 UTC, xin-hedera commented on docs/design/block-streams.md
> +| token_airdrop.token_id             | state_changes[i].state_change.map_update.key.tokenReference.tokenId                            |
TokenReference is a oneof, so token id can be either fungible_token_type or non_fungible_token.token_ID. similar comment for serial.

```
oneof token_reference {
 /**
  * A token ID.<br/>
  * This is the type of token for a fungible/common token airdrop.<br/>
  * This field is REQUIRED for a fungible/common token and MUST NOT be used for a
  * non-fungible/unique token.
  */
 TokenID fungible_token_type = 3;

 /**
  * The id of a single NFT, consisting of a Token ID and serial number.<br/>
  * This is the type of token for a non-fungible/unique token airdrop.<br/>
  * This field is REQUIRED for a non-fungible/unique token and MUST NOT be used for a
  * fungible/common token.
  */
 NftID non_fungible_token = 4;
}
```

2024-12-10 19:44 UTC, xin-hedera commented on docs/design/block-streams.md
> +
There is no `TokenClaimAirdropOutput` with token transfer list for claimed airdrops. I asked about it in the HIP, however was told that we can get the token transfers from state changes. What I don't understand is why we'd have the token transfer lists in `CryptoTransferOutput`, `TokenAirdrop`.

Btw there's still `token_tranfser_lists` in the global `TransactionResult`, my recollection is it should be removed.

The impact to our design is we may need a mapping from state change to token transfers somehwere.

2024-12-10 19:44 UTC, xin-hedera commented on docs/design/block-streams.md
> +| Database                               | Block Item                                              |
there is `TransactionRecord.transactionID`, however it's not in block stream `TransactionResult`. The impact to us is if the payer account is in the alias form, now we have to lookup its numerical account id from database, for partial mirrornode, we may not be able to get it. Perhaps, we should figure out how to get the info from state changes (the account pays the fee).

2024-12-10 19:56 UTC, xin-hedera commented on docs/design/block-streams.md
> +    private byte[] calculateBlockHash(byte[] previousBlockHash, List<StateChanges> stateChanges);
Per the [diagram](https://raw.githubusercontent.com/hashgraph/hedera-improvement-proposal/refs/heads/block-streams/assets/hip-1056/block-stream-merkle.svg) in the HIP, the following is needed to calculate the block hash

- previous block root hash
- root of input merkle tree (formed by event header and even transaction pairs)
- root of output merkle tree (formed by block header, transaction output, and state changes)
- root of state merkle tree at beginning of the block (this is included in BlockProof)

2024-12-10 21:20 UTC, edwin-greene commented on docs/design/block-streams.md
> +    private void verifyHashChain(String expected, String actual);
One thought, when block N+1 is downloaded and the check the previousBlockhash indicates that we have a mismatch... if we have already parsed block N, couldn't we have introduced invalid data into the database?

2024-12-10 21:29 UTC, xin-hedera commented on docs/design/block-streams.md
> +    private void verifyHashChain(String expected, String actual);
That’s what TSS signature is for. It replaces today’s multi node signature files. So when processing a block file we should also very tss signature in the block proof, though the details of the algorithm is left out from the HIP

2024-12-11 20:39 UTC, edwin-greene commented on docs/design/block-streams.md
> +    private byte[] calculateBlockHash(byte[] previousBlockHash, List<StateChanges> stateChanges);
Thanks Xin, this needs to be fixed. Looking into it more, the `root of input merkle tree` may be included in the last StateChange in a block, the value coming from `SingletonUpdateChange.BlockStreamInfo.inputTreeRootHash`. 

To get the `root of the output merkle tree` it looks like we will need to pass a List of BlockItems (only the specific ones you mentioned as shown in the diagram). 

At the moment this design calls for protobuf block items being filtered and consolidated into mirror node blockItems in the `BlockFileReader`. So the protobuf block items won't be present here in the transformer. One way to addess this may be for the reader to calculate the output hash for the consolidated mirror node block item and have that as another field on the block item domain object.

2024-12-11 22:27 UTC, edwin-greene commented on docs/design/block-streams.md
> +    private byte[] calculateBlockHash(byte[] previousBlockHash, List<StateChanges> stateChanges);
I have updated the design with a section for methods for the blockhash; depending on what we would like to do with the Reader, I will update that section to be fields from the domain objects or fields from the protobuf BlockItems.

2024-12-11 22:30 UTC, edwin-greene commented on docs/design/block-streams.md
> +    private void verifyHashChain(String expected, String actual);
I have updated this to remove the "cannot be verified" text. From the current schedule, it looks like the TSS Signatures will be mocked in Blockstreams phase 0; and included in Blockstreams phase 1. We may have to revise this section once more information has been nailed down.

2024-12-11 22:30 UTC, edwin-greene commented on docs/design/block-streams.md
> +- Add `congestionPricingMultiplier`, `round_start`, `round_end` to the `record_file` table, these come from the block.
Thanks, I have removed it from the record file; do you think it should be captured somewhere else? The transaction table?

2024-12-11 22:31 UTC, edwin-greene commented on docs/design/block-streams.md
> +Beginning from an `EventTransaction` block item, a record item is composed of one `TransactionResult` block item, zero to N `TransactionOutput` block items and zero to N `StateChange` block items.
Thanks I have updated this.

2024-12-11 22:31 UTC, edwin-greene commented on docs/design/block-streams.md
> +| token_airdrop.token_id             | state_changes[i].state_change.map_update.key.tokenReference.tokenId                            |
Thanks I have updated this section, with different rows for fungible/nft.

2024-12-12 14:27 UTC, xin-hedera commented on docs/design/block-streams.md
> +- Add `congestionPricingMultiplier`, `round_start`, `round_end` to the `record_file` table, these come from the block.
not sure how important the info is. if we want to persist it for future use cases, it should go to transaction table. Assume the default is `1` when no congestion pricing applied, we can make that as the column's default value to reduce table storage.

2024-12-13 16:21 UTC, xin-hedera commented on docs/design/block-streams.md
> +| Database                               | Block Item                                              |
alias form payer isn't supported in services yet, so can disregard it for now though it remains a future possiblity.

2024-12-16 10:54 UTC, IvanKavaldzhiev commented on docs/design/block-streams.md
> +    private byte[] calculateTransactionHash(EventTransaction transaction);
Note that there are ongoing activities to get rid of the `EventTransaction` wrapper. The block stream will include the Transaction proto type directly as a BlockItem and EventTransaction is going to be deprecated.

More information can be found [here](https://github.com/hashgraph/hedera-services/issues/16665).

2024-12-16 16:17 UTC, edwin-greene commented on docs/design/block-streams.md
> +    private byte[] calculateTransactionHash(EventTransaction transaction);
Thanks for pointing that out. I have added a bullet to the open issues to capture this feedback

2024-12-16 16:18 UTC, edwin-greene commented on docs/design/block-streams.md
> +
Thanks, I have added a bullet point to the open issues for this. Once the HIP is finalized we may have to go back and update our design

2024-12-17 23:10 UTC, steven-sheehy commented on docs/design/block-streams.md
> +| Updates accessed_custom_fee        | Similar to crypto_transfer, accessed at transaction_output.token_airdrop                       |
It still shows as accessed instead of assessed

2024-12-17 23:17 UTC, steven-sheehy commented on docs/design/block-streams.md
> +```
Can't you just store the necessary info in the `BlockFile` which also contains the list of block items?

2024-12-18 12:53 UTC, edwin-greene commented on docs/design/block-streams.md
> +```
Great idea, sounds good.

2024-12-18 12:53 UTC, edwin-greene commented on docs/design/block-streams.md
> +| Updates accessed_custom_fee        | Similar to crypto_transfer, accessed at transaction_output.token_airdrop                       |
Got it! Fixed now

2024-12-18 19:22 UTC, steven-sheehy approved these changes

2024-12-18 23:51 UTC, jnels124 approved these changes
LGTM

2024-12-19 00:06 UTC, xin-hedera approved these changes
LGTM

2024-12-19 15:23 UTC, merged