Updated the query to return all relevant transactions
hashgraph/hedera-mirror-node pull request #9719
Opened 2024-11-10 17:20 UTC by HarshSawarkar

**Description**:

Modified the query to return all relevant transaction
**Related issue(s)**:

Fixes #9606 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-11-11 19:13 UTC, jnels124 requested changes

2024-11-12 10:32 UTC, HarshSawarkar commented on hedera-mirror-rest/transactions.js
> +const transactionTypesToInclude = ['CRYPTOAPPROVEALLOWANCE', 'CRYPTOTRANSFER', 'CRYPTODELETEALLOWANCE'];
Updated.

2024-11-12 20:53 UTC, jnels124 requested changes

2024-11-12 20:53 UTC, jnels124 commented on hedera-mirror-rest/transactions.js
> +  or ${Transaction.getFullName(Transaction.TYPE)} in (${typesToInclude.map((type) => `'${type}'`).join(', ')})`;
Once other comments are addressed, `.map` can be removed. Also, we should only add condition if array is not empty.

2024-11-12 20:53 UTC, jnels124 commented on hedera-mirror-rest/config/application.yml
> +      transactions:
This should be the protoId of these types. See `TransactionType.java`.

2024-11-12 20:53 UTC, jnels124 commented on hedera-mirror-rest/config/application.yml
> +      transactions:
Also, this property should be added to `configuration.md`

2024-11-12 20:53 UTC, jnels124 commented on hedera-mirror-rest/transactions.js
> +  or ${Transaction.getFullName(Transaction.TYPE)} in (${typesToInclude.map((type) => `'${type}'`).join(', ')})`;
Should update the `hedera-mirror-rest/__tests__/specs/transactions/account-id.json` spec test to include these types of transactions.

2024-11-14 19:06 UTC, HarshSawarkar commented on hedera-mirror-rest/config/application.yml
> +      transactions:
Updated

2024-11-14 19:06 UTC, HarshSawarkar commented on hedera-mirror-rest/transactions.js
> +  or ${Transaction.getFullName(Transaction.TYPE)} in (${typesToInclude.map((type) => `'${type}'`).join(', ')})`;
Updated

2024-11-22 15:00 UTC, jnels124 commented on hedera-mirror-rest/config.js
> +const parseTransactionConfig = () => {
can parse this in `parseQueryConfg`

2024-11-23 09:09 UTC, closed without merging