Add admin key to get /network/nodes endpoint
hashgraph/hedera-mirror-node pull request #9776
Opened 2024-11-18 09:42 UTC by sdimitrov9

**Description**:
Adding admin_key to the get /network/nodes REST API

**Related issue(s)**:

Fixes #8757 

**Notes for reviewer**:
<img width="1421" alt="Screenshot 2024-11-18 at 11 38 06" src="https://github.com/user-attachments/assets/1609c4dd-2de8-4dd3-98e7-4b38563e55d4">
<img width="931" alt="Screenshot 2024-11-18 at 11 39 14" src="https://github.com/user-attachments/assets/50a68e7b-e70c-451c-a8e3-0636a22904ed">

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
<img width="414" alt="Screenshot 2024-11-18 at 11 43 48" src="https://github.com/user-attachments/assets/60e12206-7099-4fe1-a3ec-ccf436c38570">

2024-11-18 12:30 UTC, SvetBorislavov commented
Hey, the 'admin_key' value structure is not correct. The node's admin_key is of type 'Key', here is the definition inside the protobuf: https://github.com/hashgraph/hedera-protobufs/blob/main/services/state/addressbook/node.proto#L148
The mirror node currently returns this kind of 'Key' structure in the following format:
```
"key": {
        "_type": "ED25519",
        "key": "61f37fc1bbf3ff4453712ee6a305c5c7255955f7889ec3bf30426f1863158ef4"
      }
```
This is an example of the /accounts response:
Here is the whole request: https://testnet.mirrornode.hedera.com/api/v1/accounts?account.id=2159149

The structure should be such because the key may actually be a KeyList with multiple levels

2024-11-18 16:30 UTC, steven-sheehy requested changes

2024-11-18 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.admin_key = node.adminKey;
```suggestion
    this.admin_key = utils.encodeKey(node.adminKey);
```

2024-11-18 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/model/node.js
> + * Copyright (C) 2021-2024 Hedera Hashgraph, LLC
Copyrights should match the years in which the file was active.

```suggestion
 * Copyright (C) 2024 Hedera Hashgraph, LLC
```

2024-11-19 14:55 UTC, sdimitrov9 commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.admin_key = node.adminKey;
Done.

2024-11-19 14:56 UTC, sdimitrov9 commented on hedera-mirror-rest/model/node.js
> + * Copyright (C) 2021-2024 Hedera Hashgraph, LLC
Done.

2024-11-19 14:56 UTC, sdimitrov9 commented on hedera-mirror-rest/model/node.js
> +
Done.

2024-11-19 14:56 UTC, sdimitrov9 commented on hedera-mirror-rest/api/v1/openapi.yml
> +        admin_key: "421050820e1485acdd59726088e0e4a2130ebbbb70009f640ad95c78dd5a7b38"
Done.

2024-11-19 14:56 UTC, sdimitrov9 commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: "#/components/schemas/TimestampRange"
Done.

2024-11-19 16:08 UTC, steven-sheehy requested changes

2024-11-19 16:08 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/viewmodel/networkNodeViewModel.test.js
> +      adminKey: null,
The test should populate a valid key

2024-11-19 16:08 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/network/nodes/max-limit.json
> +        "admin_key": null,
All specs have the admin_key as null. We should populate valid admin keys for at least one file like this one. It should include different variations like ED25519, ECDSA, 3200 immutable key, and one complex key.

2024-11-22 16:03 UTC, sdimitrov9 commented on hedera-mirror-rest/__tests__/viewmodel/networkNodeViewModel.test.js
> +      adminKey: null,
New tests with valid keys are now added.

2024-11-22 16:51 UTC, steven-sheehy requested changes

2024-11-22 16:52 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/viewmodel/networkNodeViewModel.test.js
> +      adminKey: null,
You added new spec tests, but this test still should have at least one non-null key to specifically test view model.

2024-11-25 14:01 UTC, sdimitrov9 commented on hedera-mirror-rest/__tests__/viewmodel/networkNodeViewModel.test.js
> +      adminKey: null,
Updated.

2024-11-25 14:58 UTC, sdimitrov9 commented on hedera-mirror-rest/__tests__/specs/network/nodes/admin-key-ed25519.json
The unneeded specs are now removed.The existing spec files are updated with the admin_key of the different types as well. The complex type example is a hex value representing a list of keys. It is of type constants.keyTypes.PROTOBUF.

2024-11-25 16:10 UTC, steven-sheehy approved these changes
LGTM

2024-11-25 16:19 UTC, edwin-greene approved these changes
Looks good

2024-11-25 16:21 UTC, merged