fix: Fix file readable kv state for latest file
hashgraph/hedera-mirror-node pull request #9777
Opened 2024-11-18 12:34 UTC by kselveliev

**Description**:
Seems like there is an issue with the `FileReadableKVState` when we try to find latest file by id.

`FileDataRepository.findById` does not work with entity id since the primary key of the table is the consensus timestamp column and currently we pass as a parameter the entity id from the `FileID` object which is incorrect.

To fix it we can use the existing method `getFileAtTimestamp` which uses both the entity id and the consensus timestamp.
We will just pass current timestamp as a parameter and the entity id.

 

FileReadableKVState - For latest data we now use `getFileAtTimestamp` method passing current time.
Added FileReadableKVStateIntegrationTest which adds integration test for the latest scenario

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-11-18 16:10 UTC, steven-sheehy requested changes

2024-11-18 16:10 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .orElseGet(() -> fileDataRepository.getFileAtTimestamp(fileId, getCurrentTimestamp()))
This shouldn't be necessary since `timestamp` for LATEST block will be filled in with the latest block timestamp from the db via StaticBlockMetaSource. So we don't even need the `orElseGet()`.

```suggestion
```

2024-11-20 15:04 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .orElseGet(() -> fileDataRepository.getFileAtTimestamp(fileId, getCurrentTimestamp()))
Hmm, from what I've been testing and looking at the ContractCallService seems like we are only setting record file when we are passing a block which is not latest. 
```
// if we have historical call, then set the corresponding record file in the context
        if (params.getBlock() != BlockType.LATEST) {
            ctx.setRecordFile(recordFileService
                    .findByBlockType(params.getBlock())
                    .orElseThrow(BlockNumberNotFoundException::new));
        }
```
And then if we are using latest block then timestamp will be an empty optional since we are fetching it from ContractCallContext. I'm not sure if we can remove the line.

2024-11-21 11:04 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .orElseGet(() -> fileDataRepository.getFileAtTimestamp(fileId, getCurrentTimestamp()))
If we override `ContractCallContext.get().getTimestamp()` method to return current timestamp when Optional<Long> timestamp is empty, then we won't need to have `orElseGet()` statement.

2024-11-22 15:16 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .orElseGet(() -> fileDataRepository.getFileAtTimestamp(fileId, getCurrentTimestamp()))
Just debugged with contract create flow from feature-flag branch.
If we omit the orElseGet statement we are going to get -> Possibly CATASTROPHIC failure - exception thrown while handling dispatch java.lang.NullPointerException: Field currentRate is null -> since our code will return null for File.

So we should either use it how it is just getting the timestamp in some other way. Or another way to do it is to do 
`.orElseGet(() -> fileDataRepository.findByEntityId(fileEntityId))`

What do you think?

2024-11-22 21:16 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +                .orElseGet(() -> fileDataRepository.getFileAtTimestamp(fileId, getCurrentTimestamp()))
We can keep the current code.

2024-11-22 21:17 UTC, steven-sheehy approved these changes
LGTM

2024-11-22 21:17 UTC, merged