Add `MirrorNodeState` init with subcomponents
hashgraph/hedera-mirror-node pull request #9793
Opened 2024-11-21 11:20 UTC by bilyana-gospodinova

**Description**:
This PR adds the `MirrorNodeState` initialization and subcomponents invocation. Some additional changes were made in order for the init method to finish successfully.
It will stay in draft until the PR with the flag introduction is merged.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9791

2024-11-21 12:10 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/MirrorNodeStateTest.java
>  class MirrorNodeStateTest {
I thing we could also add a MirrorNodeStateIntegrationTest where we inject the MirrorNodeState and add a test 
that verifies that the MirrorNodeState is not null, has not empty states and contains as expected our custom kv states. 

This will test the init method in the MirrorNodeState and verify that it is populated in application startup

2024-11-21 12:41 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/MirrorNodeStateTest.java
>  class MirrorNodeStateTest {
Just added the following test locally and it seems to be working as expected. 
Just needs more assertions -> 
```
class MirrorNodeStateIntegrationTest extends Web3IntegrationTest {
    Resource
    private MirrorNodeState mirrorNodeState;

    Test
    void checkMirrorNodeState() {
        assertThat(mirrorNodeState).isNotNull();
    }


}
```

2024-11-21 12:54 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +        return SCOPED_VALUE.isBound() ? SCOPED_VALUE.get().timestamp : Optional.empty();
In this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/9777), it seems it might be beneficial to return Optional.of current/instant time. Do we have checks that are connected tightly to have Optional.empty() as return value that won't work with having the instant timestamp?

2024-11-21 13:02 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +        return SCOPED_VALUE.isBound() ? SCOPED_VALUE.get().timestamp : Optional.empty();
In a lot of tests we mock that the returned timestamp is `Optional.empty()`, so this will break a lot of tests.

2024-11-21 13:03 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/MirrorNodeStateTest.java
>  class MirrorNodeStateTest {
Yes, I debugged the initialization and it seems fine. I will try to add some integration tests.

2024-11-21 13:05 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +        final var genesisSchema = new V0490FileSchema();
Do we plan to use dynamically the most recent schema? Having a hardcoded schema will mean we will have to support it and change it from time to time.

2024-11-21 13:13 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +        final var genesisSchema = new V0490FileSchema();
This was the example in `TransactionExecutorsTest`. I haven't investigated yet if we need to pass here the latest schema. This can be done in a separate PR after we clear up most of the issues.

2024-11-21 13:26 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +                filesConfig.throttleDefinitions(), genesisSchema::genesisThrottleDefinitions);
Would execution fail if we leave only `filesConfig.feeSchedules()` and `filesConfig.exchangeRates()` to be set?

2024-11-21 14:35 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +        final var genesisSchema = new V0490FileSchema();
Agree, that we can check the schema population and adapt it if needed, in a future PR.

2024-11-21 16:04 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/MirrorNodeStateTest.java
>  class MirrorNodeStateTest {
Added some tests. They are not very extensive but will verify that the init method is called. Further verifications will be covered in all of the other existing integration tests.

2024-12-10 20:29 UTC, kselveliev approved these changes

2024-12-10 23:54 UTC, steven-sheehy requested changes

2024-12-10 23:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +                        new FileServiceImpl(),
Do we need the other services like consensus, schedule, util, etc? I would think util service would be used by prng precompile. Shouldn't we just register all of the ones services does so in case new precompiles come in then we don't have to change?

2024-12-10 23:54 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/MetricsImpl.java
> +public class MetricsImpl implements Metrics {
Can we use UnavailableMetrics?

2024-12-11 08:06 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +        final var genesisSchema = new V0490FileSchema();
I added this in the task for optimizations - https://github.com/hashgraph/hedera-mirror-node/issues/9264

2024-12-11 08:19 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +        return SCOPED_VALUE.isBound() ? SCOPED_VALUE.get().timestamp : Optional.empty();
This change was necessary because in the `MirrorNodeState` class we added an `init` method that runs all of the migrations and some of them require access to the DB and they use the `*ReadableKVState` classes. In them there is always logic when depending on the timestamp in the context we make a query against latest block or a historical block. This `init` method is run by the Spring container after the beans are initialized. At this point the scoped value is not always bound and this is why I added this check.

2024-12-11 08:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +                filesConfig.throttleDefinitions(), genesisSchema::genesisThrottleDefinitions);
It seems that the number of the failing tests does not change if I leave the code as you suggested.

2024-12-11 12:06 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +                        new FileServiceImpl(),
I have added only the minimal amount of services that we need for now. Note that when we start a test, all of the state initialization takes place including all of the services, migrations, subcomponents and this is quite slow even now. I am concerned that if we add more services this might slow down the development and the test execution even more. Also, the consumed memory will increase unnecessarily. We can't predict all future changes - there might be even a new services some day. In my opinion we should leave them like this for now.

2024-12-11 12:10 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/components/MetricsImpl.java
> +public class MetricsImpl implements Metrics {
We can, actually. I will remove the new class. Thanks.

2024-12-11 12:14 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +    private final TokenRelationshipReadableKVState tokenRelationshipReadableKVState;
Done, thanks.

2024-12-11 12:29 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +                        new FileServiceImpl(),
I doubt we would ever need consensus service, unless we support precompile functionality related to topics.

Schedule service, might be needed if there is a support for scheduled precompiles.

I agree with Bilyana to start with the minimal amount of services and schemas and add components on demand.

2024-12-11 12:31 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/MirrorNodeStateIntegrationTest.java
> +                CongestionThrottleService.class,
Does the state initiliazation fail if we remove `CongestionThrottleService`?

2024-12-11 12:32 UTC, IvanKavaldzhiev submitted a review, later dismissed
LGTM

2024-12-11 12:50 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/MirrorNodeStateIntegrationTest.java
> +                CongestionThrottleService.class,
Yes, I just tested it.

2024-12-11 17:15 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +        return SCOPED_VALUE.isBound() ? SCOPED_VALUE.get().timestamp : Optional.empty();
Then we should fix the init method to wrap it in `ContractCallContext.run()`. I tested locally and this works. Please revert getTimestamp() change.

Also, we should probably disable all these migrations if they're touching the database on startup. This will greatly slow down startup with probably no benefit since it's read only state.

2024-12-12 12:32 UTC, kselveliev approved these changes

2024-12-12 14:47 UTC, steven-sheehy approved these changes

2024-12-12 14:47 UTC, merged