Reduce Citus Disk Size
hashgraph/hedera-mirror-node pull request #9796
Opened 2024-11-22 00:42 UTC by jnels124

**Description**:

**Related issue(s)**:

Fixes #9274 
Fixes #9276

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-11-22 15:08 UTC, jnels124 commented on docs/runbook/scripts/reduce-citus-disk-size.sh
> +NAMESPACES=($(echo $ZFS_VOLUMES | jq -r '.[].namespace' | tr ' ' '\n' | sort -u | tr '\n' ' '))
will remove this line

2024-11-22 21:27 UTC, steven-sheehy requested changes

2024-11-22 21:27 UTC, steven-sheehy commented on docs/runbook/reduce-disksize-citus.md
> +- All Citus PVCS are defined are sized in Gi
```suggestion
- All Citus PVCS are defined in GiB
```

2024-11-22 21:27 UTC, steven-sheehy commented on docs/runbook/reduce-disksize-citus.md
> +- The kubectl context is set to the cluster you want to reduce disk size for from
```suggestion
- The kubectl context is set to the cluster with the over-sized disk
```

2024-11-22 21:27 UTC, steven-sheehy commented on docs/runbook/scripts/reduce-citus-disk-size.sh
> +done
Add a new line at EOF

2024-11-22 21:27 UTC, steven-sheehy commented on docs/runbook/scripts/reduce-citus-disk-size.sh
> +sleep 5
Why do we need the sleeps after deletes if we have the waits?

2024-11-22 21:27 UTC, steven-sheehy commented on docs/runbook/scripts/reduce-citus-disk-size.sh
> +  "${HELM_RELEASE_NAME}" -o yaml > "/tmp/sg-webhook-${EPOCH_SECONDS}.yaml"
nit: Move "/tmp/sg-webhook-${EPOCH_SECONDS}.yaml" to a constant at top and reuse it below

2024-11-22 21:37 UTC, jnels124 commented on docs/runbook/scripts/reduce-citus-disk-size.sh
> +sleep 5
Have had issues in the past where it doesn't see any pods with that label initially and the command just returns instantly with `error: no matching resources found`

2024-11-25 21:42 UTC, steven-sheehy approved these changes
LGTM

2024-11-25 23:37 UTC, merged