Add file id and init bytecode in context
hashgraph/hedera-mirror-node pull request #9799
Opened 2024-11-22 09:23 UTC by bilyana-gospodinova

**Description**:
During the implementation of the reusable services integration it turns out that now the contracts are deployed in 2 steps:

1. The initcode is uploaded and saved as a file using a `FileCreateTransactionBody`.
2. The returned file id from step 1 is then passed to a `ContractCreateTransactionBody`.
Each step performs a separate transaction.
For step 2 even if we pass the correct file id, since the mirror node data is readonly, the `FileReadableKVState` is not able to populate the contract's bytecode from the DB since it was never explicitly persisted in the DB.

This PR add 2 new fields in the `ContractCallContext` that preserve the file id and the contract's bytecode. If they are available when we call `FileReadableKVState#readFromDataSource` then we return them with priority.

These two fields might need to be cleared up at some point but this will probably added later when the correct place is found during testing.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9798

2024-12-11 00:06 UTC, steven-sheehy requested changes

2024-12-11 00:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private Optional<Bytes> initBytecode = Optional.empty();
Instead of storing two separate fields then combining them into a File, can't we just store a single File in the context? Or are they both not set at the same time?

2024-12-11 00:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +        if (contextFileId.isPresent()
While this might be fine for now, it seems a bit hacky. It would be better if we could use a cache in the KV state that spans transactions such that when the file create occurs it's persisted in the cache for the next contract create. Some sort of special cache that doesn't purge between transactions originating from the same request.

2024-12-11 12:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
> +        if (contextFileId.isPresent()
Yeah, we are going to need this caching mechanism in all of out states. I will add this in the optimizations task.

2024-12-11 12:34 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    private Optional<Bytes> initBytecode = Optional.empty();
I think we can. I combined the two fields into one.

2024-12-11 18:23 UTC, steven-sheehy approved these changes

2024-12-12 11:52 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    ;
remove extra ;

2024-12-12 12:15 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
> +    ;
Done, thanks.

2024-12-12 12:17 UTC, kselveliev submitted a review, later dismissed

2024-12-12 15:09 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-12-12 15:42 UTC, steven-sheehy approved these changes

2024-12-12 15:42 UTC, merged