Add spotlessCheck job to the security CI workflow
hashgraph/hedera-mirror-node pull request #9839
Opened 2024-11-27 11:53 UTC by sdimitrov9

**Description**:
This PR adds spotlessCheck job to the security CI workflow.

**Related issue(s)**:

Fixes #9023 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-11-27 16:08 UTC, edwin-greene approved these changes
Looks good to me

2024-11-29 00:22 UTC, steven-sheehy requested changes
Need to merge from main and verify spotless check now passes

2024-11-29 00:22 UTC, steven-sheehy commented on .github/workflows/security.yml
> +    if: github.event_name == 'push' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')
Remove this as this doesn't use any secret and we want it  to always run

2024-11-29 00:22 UTC, steven-sheehy commented on .github/workflows/security.yml
> +    runs-on: mirror-node-linux-large
This should probably run on mirror-node-linux-medium

2024-11-29 00:22 UTC, steven-sheehy commented on .github/workflows/security.yml
> +          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
Use shallow clones to speed it up

2024-11-29 00:22 UTC, steven-sheehy commented on .github/workflows/security.yml
> +          node-version: 21
Remove as it shouldn't need node

2024-11-29 08:45 UTC, sdimitrov9 commented on .github/workflows/security.yml
> +          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
Done, fetch-depth is now set to 10.

2024-11-29 10:52 UTC, sdimitrov9 commented
> Need to merge from main and verify spotless check now passes

Done.

2024-12-02 15:17 UTC, steven-sheehy requested changes

2024-12-02 15:17 UTC, steven-sheehy commented on .github/workflows/security.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Remove this secret

2024-12-02 15:59 UTC, sdimitrov9 commented on .github/workflows/security.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Done.

2024-12-03 15:29 UTC, steven-sheehy approved these changes

2024-12-03 16:33 UTC, closed without merging