Rosetta API 1.0
hashgraph/hedera-mirror-node pull request #984
Opened 2020-08-24 14:26 UTC by Daniel-K-Ivanov

**Detailed description**:
The following PR contains a WIP Rosetta API implementation based on https://www.rosetta-api.org/docs/welcome.html

**Important information:**
- The API is a Go RPC API that utilises the [Rosetta Go SDK](https://github.com/coinbase/rosetta-sdk-go) for the RPC interface
- The API is added as a service in the original `docker-compose.yml` file
- The API is validated using the [Rosetta CLI](https://github.com/coinbase/rosetta-cli)
- GitHub Actions workflow is added for Rosetta Validation

**Expected Changes/Work to be done**
- Dockerfile on the top level that runs all of the mirror node services in one container ([as per the Rosetta Requirements](https://www.rosetta-api.org/docs/automated_deployment.html#docker-deployment))
- Update the `/docs` files with additional installation, operations and deployment procedures
- Changes in the algorithm of querying Account Balances
- Add more unit tests
- Stabilise the CI/CD pipeline
- Examples for the Construction API

**Checklist**
- [X] Documentation added
- [X] Tests updated

2020-08-27 22:06 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/block.go
> +		ConsensusStartNanos: rBlock.BlockIdentifier.Index,
rosetta block index is not consensus start of a record file

2020-08-27 22:08 UTC, xin-hedera commented on hedera-mirror-rosetta/app/domain/types/block.go
> +		ConsensusEndNanos:   rBlock.Timestamp,
rosetta timestamp is in millisecond

2020-08-27 22:16 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistance/postgres/types/common.go
> +package types
q: why is the file named common and in package types?

2020-08-27 22:23 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/commons.go
> +		return c.blockRepo.FindByIndex(*bIdentifier.Index)
will panic if bIdentifier.Index is nil

2020-08-27 22:23 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/commons.go
> +		h := hex.SafeRemoveHexPrefix(*bIdentifier.Hash)
will panic if bIdentifier.Hash is nil

2020-08-27 22:24 UTC, xin-hedera commented on hedera-mirror-rosetta/app/services/commons.go
> +		return c.blockRepo.RetrieveLatest()
is this branch ever reachable?

2020-08-27 23:56 UTC, xin-hedera commented on Dockerfile
> +# ------------------------------  Rosetta  ------------------------------- #
1. Do this file and other related files have to be in the top level directory to comply with Rosetta requirement? If no, it's better to move these files to a sub folder in hedera-mirror-rosetta.
1. Do we need hedera-mirror-grpc and hedera-mirror-rest in this all-in-one docker image? hedera-mirror-rosetta does not depend on them.

2020-10-01 14:59 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/Dockerfile
> +FROM ubuntu:latest
You are right @xin-hedera. Unfortunately, Rosetta highly recommends the usage of ubuntu-based images. 
Link to resource: https://www.rosetta-api.org/docs/node_deployment.html#ubuntu-image-compatibility

2020-10-02 13:26 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/block/block.go
> +	if br.dbClient.Where(&recordFile{PrevHash: genesisPreviousHash}).Find(rf).RecordNotFound() {
Initially, I wanted to do the query as you suggest, but then I thought that a mirror node can be run to sync record files after timestamp X, so theoretically someone might be running mirror node, not synced from the genesis record file but later point in time. At that point the `RetrieveGenesis` won't be returning the actual genesis "block" (record file) of the network, but rather the first synced "block" (record file). 

We are mitigating this problem by specifying the `PrevHash` to be `0000..`

2020-10-05 11:20 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
> +	tr.dbClient.Find(&t, timestamp)
Actually, the `FindByTimestamp` is no longer used, so I will remove it altogether.

2020-10-06 08:36 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/addressbook/entry/entry.go
> +			panic(fmt.Sprintf(errors.CreateAccountDbIdFailed, abe.Memo))
You are right. Changing it to throwing Internal Server Errors

2020-10-06 08:36 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/addressbook/entry/entry.go
> +		panic(fmt.Sprintf(errors.CreateAccountDbIdFailed, abe.NodeId))
You are right. Changing it to throwing Internal Server Errors

2020-10-06 08:37 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
> +		panic(fmt.Sprintf(errors.CreateAccountDbIdFailed, encodedID))
You are right. Changing it to throwing Internal Server Errors

2020-10-06 11:57 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/domain/types/block.go
> +		ConsensusStartNanos: rBlock.BlockIdentifier.Index,
yes, you are right. It is a leftover from the previous version of the code. 
We are removing the `FromRosetta*` functionality, because:
1. It is unused
2. We cannot directly map Rosetta Block model to the Internal representation of a Block, because of the `ConsensusStartNanos` and `ConsensusEndNanos`

2020-10-06 11:57 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/domain/types/block.go
> +		ConsensusEndNanos:   rBlock.Timestamp,
addressed in the upper comment

2020-10-06 12:38 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/types/common.go
> +package types
Changed the folder to `common` along with the package. The name of the file was changed to `types` as this is the Go idiomatic way of handling common types.

2020-10-06 12:39 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/commons.go
> +		return c.blockRepo.FindByIndex(*bIdentifier.Index)
The Rosetta SDK validates the input and such use-case is not possible in the current implementation. Although relying on SDK validation makes this function vulnerable and not future proof. I've changed the code so that the issue is fixed.

2020-10-06 12:39 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/commons.go
> +		h := hex.SafeRemoveHexPrefix(*bIdentifier.Hash)
addressed in the upper comment

2020-10-06 13:20 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/commons.go
> +		return c.blockRepo.RetrieveLatest()
addressed in the upper comment

2020-10-06 13:23 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/block/block.go
> +	if br.dbClient.Where(&recordFile{PrevHash: genesisPreviousHash}).Find(rf).RecordNotFound() {
This problem is reproduced in a couple of other queries. We have created an [issue](https://github.com/LimeChain/hedera-mirror-node/issues/113) in order to address this bug.

2020-10-06 13:27 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/block/block.go
> +	selectLatestAddRank string = `SELECT * FROM (SELECT *, rank() OVER (ORDER BY consensus_start asc) FROM %s) AS res WHERE consensus_start = (SELECT MAX(consensus_start) FROM %s)`
We've updated the query to use `count` approach and not `rank`. Though we weren't able to benchmark it on a full testnet db yet.

2020-10-07 06:38 UTC, failfmi commented on hedera-mirror-rosetta/app/persistance/postgres/addressbook/entry/entry.go
> +	latestAddressBookEntries = "SELECT abe.* FROM %s AS abe JOIN %s AS ab ON ab.start_consensus_timestamp = abe.consensus_timestamp WHERE ab.end_consensus_timestamp IS NULL"
Public Key is not needed anywhere (even in metadata examples, provided by Rosetta).

2020-10-08 08:01 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/persistance/postgres/account/account.go
> +	if ar.dbClient.Where(&accountBalance{AccountRealmNum: int16(acc.Realm), AccountNum: int32(acc.Number)}).Where(fmt.Sprintf(whereClauseBeforeConsensusEnd, ab.TableName(), consensusEnd)).Find(&ab).Reco
Using the suggested optimisation we:
- decreased planning time with 25%
- decreased execution time with 25%

2020-10-08 22:23 UTC, steven-sheehy requested changes

2020-10-08 22:23 UTC, steven-sheehy commented on hedera-mirror-rosetta/app/persistence/postgres/transaction/transaction.go
> +	whereTimestampsInConsensusTimestamp string = "consensus_timestamp IN (%s)"
Use prepared statements

2020-10-08 22:23 UTC, steven-sheehy commented on hedera-mirror-rosetta/go.mod
> +replace github.com/hashgraph/hedera-sdk-go v0.9.1 => github.com/limechain/hedera-sdk-go v0.9.2-0.20200825132925-ccbc4019e257
Will these changes be ported to the sdk?

2020-10-08 22:23 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +RUN git clone https://github.com/LimeChain/hedera-mirror-node.git
Should these references to limechain git repo be changed before merge?

2020-10-08 22:23 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/Dockerfile
> +COPY --from=java-builder /hedera-mirror-node/hedera-mirror-importer/target/hedera-mirror-importer-0.19.0-rc1-exec.jar ./hedera-mirror-importer.jar
Shouldn't hardcode versions. Can this be changed to use wildcards?

2020-10-08 22:23 UTC, steven-sheehy commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +    yq write -i application.yml hedera.mirror.importer.downloader.accessKey $HEDERA_MIRROR_IMPORTER_DOWNLOADER_ACCESS_KEY
Do we need to manually map these env variables to yaml? Doesn't the go config support reading from env variable as well?

2020-10-09 06:33 UTC, failfmi commented on hedera-mirror-rosetta/build/run_supervisord.sh
> +    yq write -i application.yml hedera.mirror.importer.downloader.accessKey $HEDERA_MIRROR_IMPORTER_DOWNLOADER_ACCESS_KEY
Yes, but these are Importer related, not Rosetta. The idea is to somehow pass importer config in the all-in-one Dockerfile(Importer, SQL, Rosetta)

2020-10-09 08:01 UTC, failfmi commented on hedera-mirror-rosetta/build/Dockerfile
> +RUN git clone https://github.com/LimeChain/hedera-mirror-node.git
Yes, before merged to `master`

2020-10-09 08:09 UTC, failfmi commented on hedera-mirror-rosetta/build/Dockerfile
> +RUN git clone https://github.com/LimeChain/hedera-mirror-node.git
Yes, just before merging to `hashgraph:master`.

2020-10-09 11:27 UTC, failfmi commented on hedera-mirror-rosetta/config/application.yml
> +        username: mirror_node
Already addressed [here](https://github.com/LimeChain/hedera-mirror-node/issues/126),  will be added in a separate PR.

2020-10-09 11:27 UTC, failfmi commented on docs/configuration.md
> +| `hedera.mirror.rosetta.db.username`                     | mirror_node             | The username the processor uses to connect to the database                                     |
Same comment as above

2020-10-09 11:38 UTC, failfmi commented on hedera-mirror-rosetta/go.mod
> +replace github.com/hashgraph/hedera-sdk-go v0.9.1 => github.com/limechain/hedera-sdk-go v0.9.2-0.20200825132925-ccbc4019e257
There's an ongoing [PR](https://github.com/hashgraph/hedera-sdk-go/pull/87), will be removed after merged.

2020-10-09 11:45 UTC, failfmi commented on docs/configuration.md
> +| `hedera.mirror.rosetta.db.username`                     | mirror_node             | The username the processor uses to connect to the database                                     |
https://github.com/hashgraph/hedera-mirror-node/pull/984#discussion_r502363204

2020-10-09 12:59 UTC, Daniel-K-Ivanov commented on docker-compose.yml
> +      dockerfile: ./Dockerfile
Yes, you are right Steven. At some point, once the `hedera-mirror-rosetta` is deployed in the `mirrornode gcr`, this build should be changed to `image`.

2020-10-09 13:39 UTC, Daniel-K-Ivanov commented on docs/configuration.md
> +| `hedera.mirror.rosetta.realm`                           | 0                       | The default realm number within the shard                                                      |
We will have to discuss this topic and think about how the Rosetta API can support multiple realms as-well (if possible).

2020-10-09 15:29 UTC, xin-hedera requested changes

2020-10-09 15:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                           rcd_index.block_index
`rd.prev_hash` is not selected

2020-10-09 15:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/block/block.go
> +                                           rcd.block_index
same as above

2020-10-09 15:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	tr.dbClient.Where(fmt.Sprintf(whereTimestampsInConsensusTimestamp, timestampsStr)).Find(&cryptoTransfers)
potential sql injection

2020-10-09 15:29 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/account/account.go
> +		Where("account_realm_num=? AND account_num=? AND consensus_timestamp <= ?", int16(acc.RealmNum), int32(acc.EntityNum), consensusEnd).
there is a recent change to `account_balance` table which replaces `account_realm_num` and `account_num` with a new column `account_id` which is in the encoded form

2020-10-12 19:35 UTC, steven-sheehy approved these changes
LGTM. Any outstanding discussions items of mine can just be added to your todo list.

2020-10-12 22:24 UTC, Nana-EC approved these changes
Nice work, looking forward to follow up PR's

2020-10-12 22:25 UTC, xin-hedera requested changes

2020-10-12 22:25 UTC, xin-hedera commented on hedera-mirror-rosetta/app/persistence/transaction/transaction.go
> +	transactions = filterTransactionsForRange(transactions, consensusStart, consensusEnd)
should combine the consensus timestamp range constraint into the DB query

2020-10-12 22:31 UTC, xin-hedera commented on .github/workflows/rosetta-validation.yml
> +        cmd: yq write -i application.yml hedera.mirror.importer.startDate 2019-10-11T00:00:00.000000Z
nit: setting startDate for 'DEMO' network is no longer needed, PR #1091 now sets startDate to EPOCH

2020-10-13 13:23 UTC, xin-hedera approved these changes
LGTM

2020-10-13 14:23 UTC, merged