HIP 904 add token associate on claim airdrop
hashgraph/hedera-mirror-node pull request #9841
Opened 2024-11-27 21:31 UTC by edwin-greene

**Description**:
Associates a token when a claim airdrop occurs.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:
Tested with claim airdrop transaction on Testnet. With this change, the token airdrop correctly appears in the `token_account` table after the claim.
**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-12-03 22:39 UTC, xin-hedera requested changes

2024-12-03 22:39 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +                || tokenAccountRepository.findById(id).isPresent();
it's possible for the following transactions to happen in the same record file, assume there is no existing token association for `(A, T)`

1. `A` claims airdrop to accept some amount of token `T`
2. `A` sends all token `T` to someone else
3. `A` dissociate from token `T`
4. Another airdrop (pending) of token `T` for `A`
5. `A` claims airdrop of token `T`

We should create token association in step 1 and step 5. The logic here would only create it in step 1.

So not only we check the `TokenAccount` object existence in the context, we have to look at the associated flag too, i.e., when the associated flag is not null and is `false`, we need to merge and insert the new association.

Same applies to `TokenAccount` from the database, we need to check `associated` flag, and add such an association if it's `false`.

2024-12-03 22:45 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +                || tokenAccountRepository.findById(id).isPresent();
as a follow up, should rename the function to `isTokenAccountAlreadyAssociated` for better clarify.

2024-12-04 22:23 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
> +                || tokenAccountRepository.findById(id).isPresent();
Hopefully addressed

2024-12-04 22:37 UTC, xin-hedera approved these changes
LGTM

2024-12-04 22:44 UTC, edwin-greene reviewed
Looks good to me

2024-12-04 22:45 UTC, jnels124 approved these changes
LGTM

2024-12-04 22:47 UTC, merged