Add db migration to fix missing token association for claimed airdrops
hashgraph/hedera-mirror-node pull request #9877
Opened 2024-12-05 18:43 UTC by xin-hedera

**Description**:

**Related issue(s)**:

Related to #9865

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-05 18:46 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConfigurableJavaMigration.java
> +abstract class ConfigurableJavaMigration extends AbstractJavaMigration {
pull up common logic here for configurable migrations

2024-12-05 18:46 UTC, xin-hedera commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigrationTest.java
> +            TestPropertyValues.of("spring.flyway.target=" + version).applyTo(environment);
set proper flyway target for different profiles

2024-12-05 18:55 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +                        : Collections.<NftTransfer>emptyList();
will get some idea of how slow this can be. shouldn't be a problem for mainnet, as from 11/24/24 till now, there's a total of 25k nft tranfers

for testnet, worst scenario is we have to get all the nft transfers dated from 10/16/24, approximately 2M. however every batch returned by `getNftTransfers` is for 15-minute interval.

2024-12-05 19:08 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +              order by consensus_timestamp
Is this `order by` needed? It looks like the following `order by` may give the same order.

2024-12-05 19:09 UTC, edwin-greene commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +                log.info("There is no claimed airdrops with missing token association");
```suggestion
                log.info("There are no claimed airdrops with missing token associations");
```

2024-12-05 19:33 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +              order by consensus_timestamp
not needed and doesn't seem to harm either.

2024-12-05 19:50 UTC, steven-sheehy requested changes

2024-12-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> + * Copyright (C) 2023-2024 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2024 Hedera Hashgraph, LLC
```

2024-12-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +public class FixAirdropTokenAssociationMigration extends ConfigurableJavaMigration {
```suggestion
class FixAirdropTokenAssociationMigration extends ConfigurableJavaMigration {
```

2024-12-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +        return currentDate.getYear() != previousDate.getYear() || currentDate.getMonth() != previousDate.getMonth();
Isn't this brittle if we ever change the partitioning scheme. Shouldn't we use the TimePartitionService?

2024-12-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +            tokenAccountState.put(id, tokenAccountMeta);
Can't you just return tokenAccountState.values() at the end?

2024-12-05 19:50 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +                    missingTokenAccounts.getFirst().getTokenAccount().getCreatedTimestamp();
We should check if list is empty and return to be safe. It's possible a network has manually created all token accounts but has claimed airdrops.

2024-12-05 20:05 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +            tokenAccountState.put(id, tokenAccountMeta);
Nope. The list can contain multiple token accounts for the same account and token. That happens when there is a token dissociate between any two consecutive token claim airdrops. And the scenario is covered in the integration test.

2024-12-05 20:32 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixAirdropTokenAssociationMigration.java
> +                    missingTokenAccounts.getFirst().getTokenAccount().getCreatedTimestamp();
In theory the list can’t be empty here, since the previous steps have made sure there are claimed airdrops with missing associations. The list may be smaller than claimAirdrops because one missing token association can work for multiple pending airdrop claims (due to receiver signature required) however it can’t be empty.

I’ll add the check for safety though. We’d expect decreased test coverage.

2024-12-05 21:14 UTC, jnels124 reviewed
LGTM

2024-12-06 04:54 UTC, steven-sheehy approved these changes

2024-12-06 14:28 UTC, edwin-greene approved these changes
Looks good

2024-12-06 14:32 UTC, merged