Fix code smells
hashgraph/hedera-mirror-node pull request #9910
Opened 2024-12-09 13:49 UTC by sdimitrov9

**Description**:
Fix Sonar issues

**Related issue(s)**:

Partially fixes 9010

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-09 16:36 UTC, steven-sheehy requested changes

2024-12-09 16:36 UTC, steven-sheehy commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/repository/TopicMessageRepositoryTest.java
> -        TopicMessage topicMessage3 = domainBuilder.topicMessage().block();
Even though the variable is not referenced, these topic messages need to be created in the database to properly test the scenario. Maybe you can just remove the field declarations. 

Same comment for other changes in this file.

2024-12-09 17:33 UTC, sdimitrov9 commented on hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/repository/TopicMessageRepositoryTest.java
> -        TopicMessage topicMessage3 = domainBuilder.topicMessage().block();
Fixed.

2024-12-09 18:52 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-12-09 18:54 UTC, steven-sheehy commented
Looks like your change violates spotless check

2024-12-10 14:18 UTC, sdimitrov9 commented
> Looks like your change violates spotless check

Fixed + additional fixes added to the latest commit

2024-12-10 16:39 UTC, steven-sheehy approved these changes

2024-12-10 16:39 UTC, merged