Add modularized property
hashgraph/hedera-mirror-node pull request #9927
Opened 2024-12-10 09:05 UTC by bilyana-gospodinova

**Description**:
The integration of reusable services will span through multiple releases and will be delivered in chunks. That's why we need a feature flag to disable the new code before it's fully implemented and properly tested.

Fixes https://github.com/hashgraph/hedera-mirror-node/issues/9261

2024-12-12 12:19 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +                        e.type(EntityType.ACCOUNT).evmAddress(null).alias(null).balance(1_000_000_000_000L))
Тhis will need some adjustments since we observed that is causing some test failures in some tests

2024-12-12 13:38 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +                        e.type(EntityType.ACCOUNT).evmAddress(null).alias(null).balance(1_000_000_000_000L))
Comment addressed.

2024-12-12 16:32 UTC, steven-sheehy requested changes

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                result = processModularizedCall(params, estimatedGas);
Can we have at least one test in ContractCallServiceTest where modularized is enabled so we get code coverage? Whatever the simplest test is that can pass.

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    private Map<String, String> buildTransactionExecutorProperties() {
We can create this once and reuse between calls to improve performance.

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                : receipt.getFirst().transactionRecord().contractCallResult();
This repeats. Can move to a separate function. Or at least move up to calling function.

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                .build();
We can statically create the builder with all defaults then use to set custom fields per request. Same for other transaction bodies.

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                        .accountID(TREASURY_ACCOUNT_ID)
Shouldn't this be the sender?

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                .nodeAccountID(TREASURY_ACCOUNT_ID)
It probably doesn't matter, but we should use an actual node account like 0.0.3

2024-12-12 16:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            transactionBody = buildFileCreateTransactionBody(params, maxLifetime);
We should use `ContractCreateTransactionBody.initcode` to create as it will be quicker than having to process multiple transactions. This will also avoid need for `File` in context. Will `initcode` fail if exceeding 6 KiB max transaction size? Even if it does, we should use it for the cases when it's below max size.

2024-12-13 12:44 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    private Map<String, String> buildTransactionExecutorProperties() {
I will cache this value in a field. So far the properties are always the same but in the future when we get to the historical tests we will need to pass different collections with different properties depending on the EVM version, so this method might have to change again.

2024-12-13 12:47 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                .nodeAccountID(TREASURY_ACCOUNT_ID)
Is there any specific setup for a node account? I might need to change the integration tests setup, if so.

2024-12-13 16:06 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                .nodeAccountID(TREASURY_ACCOUNT_ID)
Does this incur an extra account load for every transaction? That is, if we change this to 0.0.3 and have payer as 0.0.2 does it load both accounts? If so, we might not actually want to have them separate. We should use the minimal number of accounts and even try to use an account from the request itself.

2024-12-16 09:17 UTC, kselveliev commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("com.esaulpaugh:headlong:6.1.1")
Why do we need to specify 6.1.1 version. I see that latest version is 12.

2024-12-16 09:34 UTC, bilyana-gospodinova commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("com.esaulpaugh:headlong:6.1.1")
This is the version that is used in the dependency. If we don't specify it here, we cannot decode successfully the response hex tuples.

2024-12-16 12:58 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
> +    private boolean modularizedServices;
Documented.

2024-12-16 12:59 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +    private Map<String, String> buildTransactionExecutorProperties() {
Added a method with lazy loading.

2024-12-16 12:59 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                : receipt.getFirst().transactionRecord().contractCallResult();
Extracted in a separate method.

2024-12-16 13:01 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                        .accountID(TREASURY_ACCOUNT_ID)
Correct. We don't always have a sender, since the field is optional when the `value` in the request is 0. I changed the code to set the sender if available and use the default treasury account, if optional and not set.

2024-12-16 13:02 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            transactionBody = buildFileCreateTransactionBody(params, maxLifetime);
Comment addressed. Added a check for the initcode length and added a new logic that uploads the initcode directly without using a file.

2024-12-16 19:28 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +        List<OperationTracer> operationTracers = new ArrayList<>();
Avoid allocating the list unless there is a non-null tracer.

2024-12-16 19:30 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +        if (receipt.getFirst().transactionRecord().receiptOrThrow().status() == ResponseCodeEnum.SUCCESS) {
We call `receipt.getFirst().transactionRecord()` 4 times and don't call anything else on `receipt`. Store the first transactionRecord into a var once and pass everywhere.

2024-12-16 19:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +                .persist();
This is a lot of setup work for every test that can slow down tests overall. Do we really need all these?

2024-12-17 09:24 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                .build();
I thought about that but I have some concerns. If we set:
`private static final ContractCreateTransactionBody.Builder CONTRACT_CREATE = ...`
as a field and then in each transaction:
`CONTRACT_CREATE.initcode(params.getCallData()...).build()`
each call will override the initcode value in the builder since they share the same object. This means that we will need to use synchronization which will also slow the performance down.

The other option is to set:
`private static final ContractCreateTransactionBody CONTRACT_CREATE = ...`
and then in each transaction we can call `CONTRACT_CREATE.copyBuilder().initcode(params.getCallData()...).build()` but this copyBuilder will create a new object as well. So we don't gain anything if we compare this approach to the current one.

2024-12-17 11:23 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +        List<OperationTracer> operationTracers = new ArrayList<>();
Comment addressed

2024-12-17 13:27 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            transactionBody = buildFileCreateTransactionBody(params, maxLifetime);
I tested it and it seems that the max transaction size is 6144 bytes. For contracts over this size, the contract create transaction fails on pre-check. The byte value is hardcoded and not configurable. So for larger contracts it seems that we still need to have the file upload logic.

2024-12-17 15:17 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            transactionBody = buildFileCreateTransactionBody(params, maxLifetime);
Is the 6144 a setting? If so, can just increase it.

2024-12-17 15:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +            final var mirrorNodeProperties = mirrorNodeEvmProperties.getProperties();
Comment addressed.

2024-12-17 15:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AccountReadableKVState.java
> +    }
Comment addressed.

2024-12-17 15:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +                    .filter(r -> r.getStateKey().equals("ACCOUNTS"))
Comment addressed.

2024-12-17 15:24 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +        if (receipt.getFirst().transactionRecord().receiptOrThrow().status() == ResponseCodeEnum.SUCCESS) {
Comment addressed.

2024-12-17 23:08 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +                : new OperationTracer[0];
Can store empty array as a static constant.

2024-12-18 09:18 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java
> +            // point.
Removed, thanks.

2024-12-18 09:19 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
> +                .persist();
I removed some of them. The others can be added just for the tests/suits that use them.

2024-12-18 09:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +            transactionBody = buildFileCreateTransactionBody(params, maxLifetime);
I opened an issue in the services repo to request to make it configurable - https://github.com/hashgraph/hedera-services/issues/17099.

2024-12-18 09:22 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                .nodeAccountID(TREASURY_ACCOUNT_ID)
Sure. Comment addressed.

2024-12-18 09:23 UTC, bilyana-gospodinova commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractCallService.java
> +                        .accountID(TREASURY_ACCOUNT_ID)
Comment addressed.

2024-12-18 09:47 UTC, kselveliev commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/TransactionExecutionService.java
> +                : new OperationTracer[0];
Comment addressed

2024-12-18 15:26 UTC, steven-sheehy approved these changes
LGTM

2024-12-18 15:26 UTC, merged