Add api proxy to the development docker environment
hashgraph/hedera-mirror-node pull request #9939
Opened 2024-12-11 02:20 UTC by Neurone

**Description**:

This PR adds a default API proxy to the Docker development environment when developers run `docker compose up`.

**Related issue(s)**:

Fixes #9938

**Notes for reviewer**:

This is not meant for production use, but it's good enough for development purposes and for those who want to use `docker compose' to run the mirror node on their local machine.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-12-12 17:02 UTC, steven-sheehy requested changes

2024-12-12 17:02 UTC, steven-sheehy commented on hedera-mirror-api-proxy/default.conf
> +    location /api/v1/contracts/call {
This is missing the optional opcodes endpoint:

`'/api/v1/contracts/results/((0x)?[A-Fa-f0-9]{64}|\d+\.\d+\.\d+-\d+-\d+)/opcodes'`

2024-12-12 17:02 UTC, steven-sheehy commented on hedera-mirror-api-proxy/default.conf
> +    location /api/v1/ {
We need to also add the rest-java, grpc, graphql, and rosetta routes to this file. You can see our route matching the helm chart values.yml under `ingress.hosts.paths`.

2024-12-12 17:02 UTC, steven-sheehy commented on hedera-mirror-api-proxy/default.conf
> +    listen       8888;
Think port 8080 would provide a better default

2024-12-12 17:02 UTC, steven-sheehy commented on docker-compose.yml
> -version: "3.8"
Why remove this?

2024-12-12 17:13 UTC, Neurone commented on hedera-mirror-api-proxy/default.conf
Cool, I didn't know this technique. I'll update the config.

2024-12-12 17:15 UTC, Neurone commented on docker-compose.yml
> -version: "3.8"
The `version` tag is obsolete and Compose does not use it anymore: https://docs.docker.com/reference/compose-file/version-and-name/

2024-12-13 17:07 UTC, xin-hedera commented on docker-compose.yml
> +        location /rosetta { proxy_pass http://$$rosetta_host$$request_uri; }
need to remove `/rosetta/` from the request url and pass the remaining to rosetta rest api.

```suggestion
        location /rosetta/ { proxy_pass http://$$rosetta_host/; }
```

2024-12-13 17:39 UTC, Neurone commented on docker-compose.yml
> +        location /rosetta { proxy_pass http://$$rosetta_host$$request_uri; }
Thanks for the note. So, you want that if the gateway receive `/rosetta/hello?world=1` the rosetta container receive `/hello?world=1` instead, right?

2024-12-13 19:43 UTC, steven-sheehy commented on docker-compose.yml
> +        location /rosetta { proxy_pass http://$$rosetta_host$$request_uri; }
Correct

2024-12-13 20:36 UTC, steven-sheehy requested changes

2024-12-13 20:36 UTC, steven-sheehy commented on docker-compose.yml
> +        location /com.hedera.mirror.api.proto.NetworkService { grpc_pass grpc://grpc_host; }
```suggestion
        location /com.hedera.mirror.api.proto { grpc_read_timeout 600s; grpc_pass grpc://grpc_host; }

```

2024-12-13 20:36 UTC, steven-sheehy commented on docker-compose.yml
> +    image: nginx:1.27.3-alpine
While it's best practice to use specific versions, since this isn't production supported prefer using a more frequently updated tag so we reduce our maintenance burden.

```suggestion
    image: nginx:1-alpine
```

2024-12-13 20:36 UTC, steven-sheehy commented on docker-compose.yml
>    rest-java:
While you're updating this file, can you add `HEDERA_MIRROR_REST_REDIS_URI: redis://redis:6379` to rest environment to fix the redis error?

2024-12-16 23:13 UTC, steven-sheehy approved these changes
LGTM. Thanks!

2024-12-16 23:32 UTC, xin-hedera approved these changes
LGTM

2024-12-16 23:35 UTC, merged