Fix sonar issues
hashgraph/hedera-mirror-node pull request #9944
Opened 2024-12-12 14:31 UTC by sdimitrov9

**Description**:
Fix issues detected by the sonar scanner.

**Related issue(s)**:

Partially fixes 9010

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-12 15:56 UTC, steven-sheehy requested changes

2024-12-12 15:56 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +val javaxInjectVersion = "1"
The correct fix is to move to root build.gradle.kts as `api("javax.inject:javax.inject:1")` then drop the version here.

2024-12-12 15:56 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +    List<NftAllowance> findByOwnerAndTimestampAndApprovedForAllIsFalse(long owner, long blockTimestamp);
Why are we adding this new repository method?

2024-12-12 15:56 UTC, steven-sheehy commented on hedera-mirror-test/build.gradle.kts
> +    group = "Testing"
Since test task is under verification group, it makes sense to also have acceptance there.

```suggestion
    group = "verification"
```

2024-12-12 15:56 UTC, steven-sheehy commented on build.gradle.kts
> +    group = "Versioning"
```suggestion
    group = "release"
```

2024-12-13 08:20 UTC, sdimitrov9 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +    List<NftAllowance> findByOwnerAndTimestampAndApprovedForAllIsFalse(long owner, long blockTimestamp);
Removed. Now an additional parameter is added to the existing repository method so we can set the approved_for_all property. In order not to modify the existing method calls across the classes a default method with the original signature is added as well:

`  
...         
nativeQuery = true)
    List<NftAllowance> findByOwnerAndTimestamp(long owner, long blockTimestamp, boolean approvedForAll);

    default List<NftAllowance> findByOwnerAndTimestampAndApprovedForAllIsTrue(long owner, long blockTimestamp) {
        return findByOwnerAndTimestamp(owner, blockTimestamp, true);
    }`

2024-12-13 08:21 UTC, sdimitrov9 commented on hedera-mirror-web3/build.gradle.kts
> +val javaxInjectVersion = "1"
Fixed.

2024-12-13 08:21 UTC, sdimitrov9 commented on hedera-mirror-test/build.gradle.kts
> +    group = "Testing"
Fixed

2024-12-13 19:38 UTC, steven-sheehy requested changes

2024-12-13 19:38 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +                                    and approved_for_all <= :approvedForAll
This now introduces a bug in production code where we're not filtering the nft_allowance table as well. Suggestion is to remove all changes to repository class. We shouldn't add new repository methods that are only used by tests. Instead just use findAll/findById to lookup and assert the approveForAll field in code.

2024-12-16 13:40 UTC, sdimitrov9 commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftAllowanceRepository.java
> +                                    and approved_for_all <= :approvedForAll
Fixed

2024-12-16 16:59 UTC, steven-sheehy approved these changes
LGTM

2024-12-16 16:59 UTC, merged