9917 add acceptance tests for long term scheduled transactions
hashgraph/hedera-mirror-node pull request #9963
Opened 2024-12-16 17:11 UTC by nickeynikolovv

**Description**:
This PR adds acceptance tests for long term scheduled transactions with the following scenarios:

- Scheduled transaction for HBAR transfer without expiry time and waitForExpiry = false 
- Deletion of Schedule
- Scheduled transaction for HBAR transfer with expiry time and waitForExpiry=true
- Scheduled transaction that expires without collecting the needed signatures
In the tests the respective validations for the scheduled transactions are added including the statuses - Executed, Not Executed, Deleted, Expired 

**Related issue(s)**:

Fixes #9917 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-12-17 22:26 UTC, steven-sheehy requested changes

2024-12-17 22:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    And the mirror node REST API should verify the "NON_EXECUTED" schedule entity "with" expiration time and wait for expiry "false"
Might be overkill to have two keys signing. Can simplify to just have treasury sign.

2024-12-17 22:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    And the mirror node REST API should verify the "EXECUTED" schedule entity "with" expiration time and wait for expiry "false"
We're missing the main scenario from HIP-423: wait_for_expiry=true and executes at expiration time since all sigs present.

2024-12-17 22:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +            "I successfully schedule a HBAR transfer from treasury to {account} {string} expiration time and wait for expiry {string} - plus {int} seconds")
It might be clearer where expiration time string can be `null` or a duration offset like `2s`. Can use `DurationStyle.detectAndParse(str)` for parsing simple duration strings.

```suggestion
            "I successfully schedule a HBAR transfer from treasury to {account} with  expiration time {string} and wait for expiry {string}")
```

2024-12-17 22:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        }
This will be a busy loop without any sleep. Instead use awaitility like we do elsewhere in acceptance tests.

2024-12-17 22:26 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private Instant convertStringToInstant(String timestamp) {
Use `TestUtil.convertTimestamp()`

2024-12-18 11:36 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    And the mirror node REST API should verify the "NON_EXECUTED" schedule entity "with" expiration time and wait for expiry "false"
Changed to use only 1 signature from treasury

2024-12-18 11:38 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    And the mirror node REST API should verify the "EXECUTED" schedule entity "with" expiration time and wait for expiry "false"
I actually added a tests for that scenario before, but decided to remove it to not overload the tests with the waits 😆  Added the test again

2024-12-18 11:38 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +            "I successfully schedule a HBAR transfer from treasury to {account} {string} expiration time and wait for expiry {string} - plus {int} seconds")
Changed it that way

2024-12-18 11:38 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        }
Fixed

2024-12-18 11:38 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private Instant convertStringToInstant(String timestamp) {
done

2024-12-18 16:21 UTC, xin-hedera commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    Given I successfully schedule a HBAR transfer from treasury to ALICE with expiration time "2s" and wait for expiry "true"
isn't 2 seconds too short given our finality time is 3-5 seconds? When the expiration time is so close to *now*, we run into the risk of

```
If the expiration_time is less than or equal to the current consensus time when the ScheduleCreate is processed then the new SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME error shall be returned.
```

2024-12-18 16:21 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    @Given("I wait for the schedule to expire")
because the scheduled transaction will execute after expiration time if all signatures are collected, a better description would be
```suggestion
    @Given("I wait until the schedule's expiration time")
```

2024-12-18 16:21 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        var expectedExecutedTimestamp = txConsensusTimestamp.plus(plusSecondsToExpire);
isn't the expiration time set in `ScheduleCreate` transaction more accurate than schedule create's consensus timestamp + expiration in seconds?

2024-12-19 08:35 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +        } else {
fixed

2024-12-19 08:37 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    Given I successfully schedule a HBAR transfer from treasury to ALICE with expiration time "10s" and wait for expiry "true"
Lowered it to 8s, but if we set it to 4 if the signature is not collected in time it will expire and the last check `And the mirror node REST API should verify the "EXECUTED" schedule entity with expiration time "8s" and wait for expiry "true"` will fail. However it wouldn't cause any delay in the tests since they run in parallel

2024-12-19 08:37 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    private Duration plusSecondsToExpire;
fixed

2024-12-19 08:37 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +                }
fixed

2024-12-19 08:38 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
> +    Given I successfully schedule a HBAR transfer from treasury to ALICE with expiration time "2s" and wait for expiry "true"
In that particular test I added 2 seconds to not overload the tests with additional waits, since the outcome is to expire.  I didn't hit that scenario, but I think you are right so i raised it to 5 seconds

2024-12-19 08:39 UTC, nickeynikolovv commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
> +    @Given("I wait for the schedule to expire")
done

2024-12-19 15:56 UTC, steven-sheehy approved these changes

2024-12-19 15:57 UTC, merged