Fix sonar issues
hashgraph/hedera-mirror-node pull request #9979
Opened 2024-12-18 14:05 UTC by sdimitrov9

**Description**:
Fix sonar issues

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-18 19:04 UTC, steven-sheehy requested changes

2024-12-18 19:04 UTC, steven-sheehy commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/UpdateTokenFreezeKycStatusMigrationTest.java
> +    // read
nit: Shorten comment so it and annotation appear on one line

2024-12-18 19:04 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/usage/token/entities/TokenEntitySizes.java
> +@SuppressWarnings("squid:S6548") // enum soon to be deleted with the introduction of reusable services
Is this still needed with sonar-project.properties?

2024-12-19 08:17 UTC, sdimitrov9 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/AbstractStreamFileProviderTest.java
> +    @SuppressWarnings("java:S1130") // Exception is thrown in the child classes setup method
Done

2024-12-19 08:17 UTC, sdimitrov9 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/AbstractStreamFileProviderTest.java
> +    @SuppressWarnings("java:S1172") // node is used in the child classes implementations
Done

2024-12-19 08:17 UTC, sdimitrov9 commented on hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/UpdateTokenFreezeKycStatusMigrationTest.java
> +    // read
Done

2024-12-19 08:17 UTC, sdimitrov9 commented on hedera-mirror-web3/src/main/java/com/hedera/services/fees/usage/token/entities/TokenEntitySizes.java
> +@SuppressWarnings("squid:S6548") // enum soon to be deleted with the introduction of reusable services
Shouldn't be, it is removed now.

2024-12-19 15:01 UTC, steven-sheehy approved these changes

2024-12-19 15:01 UTC, merged